### ISSUE TITLE
red color becomes darker after transform png to webp

### ISSUE THREAD

**Issue by sophister** [lovell/sharp#1000]
I'm using `sharp` to transform images, such as from `png` to `webp` format.

some **red text** in the final `webp` image, is **darker** than how it is in the origin `png` image.

I can't find any config or arguments to fix this.

following is my code:

```javascript
sharp( imageAbsolutePath )
        .webp({ quality : 100, alphaQuality : 100 })
        .toFile( webpAbsolutePath )
        .then( function( info ){
            info.webpPath = webpAbsolutePath;
            return info;
        });
```

This is the origin `png` image:

![origin](https://user-images.githubusercontent.com/219501/31886158-c9125f7a-b7b8-11e7-8a19-00c11553329f.png)

and this is the `webp` version:

![webp](https://user-images.githubusercontent.com/219501/31886177-e09e9ec4-b7b8-11e7-98f1-a5fbf7299186.png)

**Comment by lovell** [comment]
Hello, did you see the [webp](http://sharp.dimens.io/en/stable/api-output/#webp) `lossless` option, which is more suitable for this kind of image.

I believe a lossy WebP image at "100% quality" will still discard some chroma information, which is what I think is occurring here.

**Comment by sophister** [comment]
@lovell  Thx. 

`lossless : true` solves this.

**Comment by janwerkhoven** [comment]
Lossless indeed fixes the red colour issue, but using `lossless: true` also makes those images big!

My images are now 3MB instead of 189KB.

Causes red colour issue:
```
cwebp -q 90 -resize 2000 0 "$png_path" -o "$webp_path";
```

Causes big file issue:
```
cwebp -lossless -resize $size 0 "$png_path" -o "$webp_path";
```

**Comment by janwerkhoven** [comment]
JPG on the left, same colours as original PNG.
WEBP on the right, wrong colours...

![demo2](https://user-images.githubusercontent.com/4415419/74317502-a466f000-4dcf-11ea-8594-c1bea324fb6a.jpg)

**Comment by lovell** [comment]
There are a couple of other WebP options to experiment with for a given input, namely `nearLossless` and `smartSubsample`.

https://sharp.pixelplumbing.com/api-output#webp

**Comment by janwerkhoven** [comment]
Thanks :)
Sharp looks interesting...
I'm currently converting 20,000+ files using Bash scripts, not using Node (yet) for this task.
Do you know the `cwebp` command equivalent of `smartSubsample`?
https://developers.google.com/speed/webp/docs/cwebp

**Comment by lovell** [comment]
`cwebp -sharp_yuv` is the equivalent of `smartSubsample`.

**Comment by janwerkhoven** [comment]
Thanks, I've tried `-sharp_yuv` but without avail...
This feature was added in `v0.6.0` and I'm using `cwebp v1.1.0`.
Related:
https://bugs.chromium.org/p/webp/issues/detail?id=232
https://bugs.chromium.org/p/webp/issues/detail?id=340
I think I need to report this as a bug. I tried all cwebp options and combinations...

**Comment by janwerkhoven** [comment]
🎉 

I've found the solution: **normalise the colour profile** before converting to WEBP.

```
convert "image.png" -profile "./sRGB_v4_ICC_preference.icc" "normalised.png"

cwebp "normalised.png" -o "image.webp"
```

Converting PNGs exported by [Capture One](https://www.captureone.com/)  to WEBP resulted in dark red WEBPs. PNGS exported by [Sketch](https://www.sketch.com/) however, resulted in correctly coloured WEBPs. The difference is the colour profiles they use.

I used [ImageMagick](https://imagemagick.org/index.php) for converting the colour profile. Below is the ICC file that worked for me:

[sRGB_v4_ICC_preference.icc.zip](https://github.com/lovell/sharp/files/4474946/sRGB_v4_ICC_preference.icc.zip)

**Comment by porg** [comment]
## That same image conversion in [GraphicConverter](https://www.lemkesoft.de/en/products/graphicconverter)
1) Source: PNG with color profile Adobe RGB 1998
2) Menu > Edit > Convert to profile…
  - Source: Adobe RGB 1998 — This is fact, hence read only, you cannot change anything here.
  - Destination: sRGB
  - Conversion Priority
    - RGB/Grayscale: Default (perceptual for images and relative colorimetric for others)
    - CMYK: Relative Colorimetric — Leave it as-is. Is only relevant for print files anyhow.
3) Menu > File > Save as…
  - Format: WEBP
  - Options… → Opens sub-dialog
    - Use lossless ON.
    - All other options OFF (we do not include any metadata).
    - Close sub-dialog with OK.
  - SAVE under the same or another name, you won't conflict with your source PNG file as yours will be saved with a WEBP suffix anyhow.
  
Now you have:
- The original untouched PNG plus the WEBP with its pixel values converted to sRGB and no explicit embedded profile.
- For an image without a color profile web browsers assume sRGB.
- Which it is, hence in all Safari and Chrome and Preview.app this WEBP and the original file a PNG with an Adobe RGB 1998 profile and alternatively a PNG without a profile but with prior pixel data conversion to sRGB all look the same when opening each in its own tab/window and cycling through them.

**Comment by rufatpro** [comment]
> 🎉
> 
> I've found the solution: **normalise the colour profile** before converting to WEBP.
> 
> ```
> convert "image.png" -profile "./sRGB_v4_ICC_preference.icc" "normalised.png"
> 
> cwebp "normalised.png" -o "image.webp"
> ```
> 
> Converting PNGs exported by [Capture One](https://www.captureone.com/) to WEBP resulted in dark red WEBPs. PNGS exported by [Sketch](https://www.sketch.com/) however, resulted in correctly coloured WEBPs. The difference is the colour profiles they use.
> 
> I used [ImageMagick](https://imagemagick.org/index.php) for converting the colour profile. Below is the ICC file that worked for me:
> 
> [sRGB_v4_ICC_preference.icc.zip](https://github.com/lovell/sharp/files/4474946/sRGB_v4_ICC_preference.icc.zip)

This do not solve my problem.

Source file:
![normalised](https://github.com/lovell/sharp/assets/5204099/b6d83bf2-d03c-47c3-afe8-67ebcaa1f3c9)

Result file, screenshot in png of the webp, github do not support webp format:
![dst](https://github.com/lovell/sharp/assets/5204099/ad732dc7-cadc-4606-a9aa-3a329783b787)

**Comment by lovell** [comment]
I'm locking as this problem is due to a limitation of the WebP format and this issue is now attracting comments unrelated to sharp.
