### ISSUE TITLE
What command in sharp that is similar of 'quality' in imagemagick?

### ISSUE THREAD

**Issue by nicholasess** [lovell/sharp#1001]
In crop or resize has a property called quality, this is used for reduce a size of image.

Thanks

![screenshot 2](https://user-images.githubusercontent.com/3238901/31913361-c2437716-b825-11e7-8973-5ec9c965c572.png)

**Comment by lovell** [comment]
Hello, did you see the `quality` option available on the `jpeg`, `webp` and `tiff` output-selecting functions?

http://sharp.dimens.io/en/stable/api-output/

**Comment by nicholasess** [comment]
Nice @lovell 

Is ```sharp('image.png').jpg({quality: 10})``` ?

**Comment by lovell** [comment]
Almost, use `jpeg()` rather than `jpg()`, something like:
```javascript
sharp('image.png')
  .jpeg({quality: 10})
  .toFile('output.jpg', function(err, info) {
    ...
  });
```
As an aside, using a quality value of 10% will discard a lot of data so you'll see some 8x8 block artefacts.

**Comment by nicholasess** [comment]
@lovell thanks so much
