### ISSUE TITLE
Cannot find module 'caw'

### ISSUE THREAD

**Issue by kishe89** [lovell/sharp#1002]
i saw same issue #871
but my case is different.

i trying deploy my node application in CloudFoundry environment.
my local environment is success npm install but CloudFoundry environment is fail

cause is Cannot find module 'caw'

please help me

**Comment by lovell** [comment]
Hello, this is very likely to be a temporary problem with CloudFoundry, probably network related. You'll need to get the `npm install` log from CloudFoundry to see what happened. Good luck!

**Comment by kishe89** [comment]
Probably CloudFoundry npm cache problem. 
Thank you for quick response.
