### ISSUE TITLE
ERROR: https://dl.bintray.com/lovell/sharp/libvips-8.5.5-linux-x64.tar.gz status code 404

### ISSUE THREAD

**Issue by smaznet** [lovell/sharp#1004]
`npm install sharp` output:

```bash
ERROR: https://dl.bintray.com/lovell/sharp/libvips-8.5.5-linux-x64.tar.gz status code 404
gyp: Call to 'node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
```

**Comment by digitalica** [comment]
same issue here.

**Comment by yvele** [comment]
Related to https://github.com/lovell/sharp/issues/851 to upload pre-compiled ressources to [GitHub release assets](https://developer.github.com/v3/repos/releases/#upload-a-release-asset)

PS: This time it's not a `403` like in https://github.com/lovell/sharp/issues/964

**Comment by lovell** [comment]
Looks like temporary, intermittent Bintray problems for everything e.g. https://twitter.com/jack_martynov/status/924574543561347072

http://status.bintray.com/ says "All Systems Operational"

/cc @jbaruch

**Comment by clusteratlas** [comment]
I really hope we get to do the Github thing at #851 :+1:  :+1:

**Comment by xemasiv** [comment]
@lovell just created this https://hub.docker.com/r/xemasiv/node-env/

It's a modified version of TailorBrands' one, with the following changes:

* Base image is now pulled from official node directory, whose version is easily interchangeable
* Image is now inclusive with node-gyp dependencies for rebuilding libraries
* Image is also inclusive of 'sharp' npm package, npm-instealled as a global library
* Added tweaks that:
  * Allowed installation of global package in NPM (thru chown & sudo)
  * Allowed requiring of globally installed packages (thru ~/.bashrc fix)

Contents, setup, testing, usage & credits also provided.

**Comment by lovell** [comment]
Looks like everything is OK today so (tentatively) closing this.
