### ISSUE TITLE
Speed up the for  dynamical operation

### ISSUE THREAD

**Issue by exotfboy** [lovell/sharp#1007]
Hi:

I have a big jpg source file with size of (32768x32768), and I have to extract from the source and generate a new image according to the client request.

Before I found `sharp`, I use Java2D interfaces like `BufferedImage` to do the operation, and it will take almost 20s to load the image at the first time, and then the following operation like `resize` `crop` will take about 500ms more or less. However it cost almost 1.2GB memory.

When I tried `sharp`, I found that the same operation like `extract` `resize` will take up only 120M memory, this is amazing, however each request will take almost 15s. 

Is it possible to improve this?

**Comment by lovell** [comment]
Extracting multiple regions from the same input image sounds like you might be hand-rolling an image pyramid for some kind of "slippy map". If so, did you see [tile](http://sharp.dimens.io/en/stable/api-output/#tile)?

Please can you provide a sample of the code you are using.

**Comment by exotfboy** [comment]
Yes, something like the slippy map, and I know I can  use the `tile` to pre-generates images, however I want to serve the images only when requested.

core codes like this:

```
var app= require("express")();
var sharp=require("sharp");
var src = sharp("D:/test.jpg");
app.get("5/:x/:y",function(req,res){
   var x=req.params.x, y=req.params.y;
   src.resize(32768/2,32768/2).extract({left:x*256,top:y*256,256,256}).then(....);
});
app.listener(...)
```

**Comment by lovell** [comment]
A compromise between memory usage and processing speed might be to hold smaller compressed versions as singletons in memory, something like:

```javascript
const test16384 = await sharp("D:/test.jpg")
  .resize(32768 / 2, 32768 / 2)
  .toBuffer();

app.get("5/:x/:y", function (req,res) {
  const { x, y } = req.params;
  sharp(test16384)
    .extract({ left: x * 256, top: y * 256, ... )
    .toBuffer()
    .then( ... );
});
```

**Comment by exotfboy** [comment]
Thanks I got that.
