### ISSUE TITLE
"undefined symbol" upon launch on Centos6 32bit

### ISSUE THREAD

**Issue by owczar1981** [lovell/sharp#1010]
In reference to #649. I have built `libvips` from the tarball with some of the dependencies, but on runtime of the app i get:
````
Error: /root/app/build/node_modules/sharp/build/Release/sharp.node: undefined s$
mbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoI$
S_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorE      
   at Error (native)                                                           
   at Object.Module._extensions..node (module.js:434:18)                       
   at Module.load (module.js:343:32)                                           
   at Function.Module._load (module.js:300:12)                                 
   at Module.require (module.js:353:17)                                        
   at require (internal/module.js:12:17)                                       
   at Object.<anonymous> (/root/app/build/node_modules/sharp/lib/constructor.j$
:9:15)                                                                          
   at Module._compile (module.js:409:26)
   at Object.Module._extensions..js (module.js:416:10)
   at Module.load (module.js:343:32)
````

Output of `ldd ./app/build/node_modules/sharp/build/Release/sharp.node`:

````
linux-gate.so.1 =>  (0xb77d4000)                                        
libvips-cpp.so.42 => /usr/local/lib/libvips-cpp.so.42 (0xb7761000)      
libvips.so.42 => /usr/local/lib/libvips.so.42 (0xb73dc000)              
libgobject-2.0.so.0 => /lib/libgobject-2.0.so.0 (0xb738f000)            
libgthread-2.0.so.0 => /lib/libgthread-2.0.so.0 (0xb738a000)            
librt.so.1 => /lib/librt.so.1 (0xb7380000) 
libglib-2.0.so.0 => /lib/libglib-2.0.so.0 (0xb7263000)          [4/1991]
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0xb7178000)                  
libm.so.6 => /lib/libm.so.6 (0xb714e000)                                
libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xb7130000)                        
libpthread.so.0 => /lib/libpthread.so.0 (0xb7115000)                    
libc.so.6 => /lib/libc.so.6 (0xb6f7d000)
libz.so.1 => /lib/libz.so.1 (0xb6f69000)
libpng12.so.0 => /usr/lib/libpng12.so.0 (0xb6f41000)
libtiff.so.3 => /usr/lib/libtiff.so.3 (0xb6edf000)
libjpeg.so.62 => /usr/lib/libjpeg.so.62 (0xb6e88000)
libgmodule-2.0.so.0 => /lib/libgmodule-2.0.so.0 (0xb6e84000)
libexpat.so.1 => /lib/libexpat.so.1 (0xb6e5b000)
liblcms.so.1 => /usr/lib/liblcms.so.1 (0xb6e21000)
libgif.so.4 => /usr/lib/libgif.so.4 (0xb6e18000)
libexif.so.12 => /usr/lib/libexif.so.12 (0xb6ddf000)
/lib/ld-linux.so.2 (0xb77d5000)
libdl.so.2 => /lib/libdl.so.2 (0xb6dd9000)
libSM.so.6 => /usr/lib/libSM.so.6 (0xb6dd1000)
libICE.so.6 => /usr/lib/libICE.so.6 (0xb6db7000)
libX11.so.6 => /usr/lib/libX11.so.6 (0xb6c7d000)
libuuid.so.1 => /lib/libuuid.so.1 (0xb6c78000)
libxcb.so.1 => /usr/lib/libxcb.so.1 (0xb6c4f000)
libXau.so.6 => /usr/lib/libXau.so.6 (0xb6c4c000)
````
I'm running on `node 8`. Wiping and reinstalling `node_modules` doesn't help. Changing versions of node doesn't either. It works okay on my dev environment with the pre built binaries, but fails on production.
Any guesses? Maybe I need the python binding stuff for `libvips`?

**Comment by lovell** [comment]
It looks like `build/Release/sharp.node` has been compiled at `npm install` time against one version of V8 but is being used at run time with another V8 version.

Is your production system using the same major version of Node as the system on which `npm install` is being run?

**Comment by unski11ed** [comment]
Yes, both are running `node 8.6.0`, the only difference is that the app is compilled on a 64bit machine. But that shouldn't make a diferrence as the `npm install` is made on the server itself. I can even see in the output that sharp is building there.

**Comment by lovell** [comment]
What does "the app is compilled on a 64bit machine" mean?

Could the contents of `node_modules` generated on a 64-bit machine get copied to a 32-bit machine (even if "npm install is ran on the server itself")?

Are there any environment variables that could be altering compiler behaviour, e.g. `LDFLAGS`?

**Comment by unski11ed** [comment]
"Compile" isn't the right word i guess... Webpack building the application is what i meant ;)

`node_modules` aren't sent over the wire at all, only `package.json` and after it is complete it runs `npm install` there. I checked it out many times, after your first suggestion - I'm quite sure that different node version isn't the case here. Although you seem to be very confident that this is the case, which makes the case very wierd :O No other things come to your mind? `node-gyp` is throwing a warning about some deprecated constant - this is the one thing that looked odd for me.

`LDFLAGS` is only modified inside some other modules - `fibers` and `node-sass`, the app build mechanism itself doesn't tocuh it, at least I'm not aware of it.

**Comment by lovell** [comment]
Thank you, definitely a weird one. Are you able to see if this occurs with another major Node (and therefore V8) version, perhaps the latest v6.11.5?

**Comment by lovell** [comment]
@unski11ed Is this problem still occurring?

**Comment by unski11ed** [comment]
Sorry, forgot about this. I can't really tell at the moment. I had to switch for now for a pure JS solution which is slow as he'll. I'll be mangling with the production server in January so I will be able to investigate it more. I can't touch it at the moment. I'll post an update when I'll be able to look at it ok?

**Comment by lovell** [comment]
Closing for now but please feel free to re-open with more information if available in the future.
