### ISSUE TITLE
Typescript update

### ISSUE THREAD

**Issue by BorntraegerMarc** [lovell/sharp#1011]
Is the typescript definitions https://www.npmjs.com/package/@types/sharp compatible with version 18 ?

**Comment by lovell** [comment]
Hello, these are maintained by https://github.com/DefinitelyTyped/DefinitelyTyped

[types/sharp/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sharp/index.d.ts#L1) says "0.17" so perhaps you could submit a PR to that repo with any [changes](http://sharp.dimens.io/en/stable/changelog/).

**Comment by BorntraegerMarc** [comment]
thanks @lovell 
I don't see any changes to the API from v0.17 to v0.18. Am I wrong?

**Comment by lovell** [comment]
The following items in the [v0.18.x changelog](http://sharp.dimens.io/en/stable/changelog/#v018-ridge) all look like they involved (small) API changes:

* Remove the previously-deprecated output format "option" functions: quality, progressive, compressionLevel, withoutAdaptiveFiltering, withoutChromaSubsampling, trellisQuantisation, trellisQuantization, overshootDeringing, optimiseScans and optimizeScans.
* Include pixel depth (e.g. "uchar") when reading metadata.
* Expose libvips' "squash" parameter to enable 1-bit TIFF output.
* Add "jpg" alias to toFormat as shortened form of "jpeg".
* Expose libvips' xres and yres properties for TIFF output.

**Comment by lovell** [comment]
Please also see #472 for previous failed attempts to auto-generate typescript bindings from jsdocs. Happy to reconsider this if the tooling has improved since.

**Comment by lovell** [comment]
Please open an issue on the DefinitelyTyped repo that maintains these bindings should this still be required.
