### ISSUE TITLE
Memory usage doesn't drop after http requests are resolved

### ISSUE THREAD

**Issue by tiagofumo** [lovell/sharp#1013]
I have a small application that takes http requests and does some processing on large images (~4k resolution). I used the `ab` command to simulate a real world application with multiple requests and I noticed that memory usage went up very fast and didn't drop after all the requests finished. Apparently, memory is not being released after each request. I used `--max-old-space-size=256` on npm when starting the server, and also calling `global.gc()` with the `--expose-gc` flag, but nothing seems to work.

After some profiling I think the memory allocated on the `toBuffer()` calls isn't being release after the request is done. I have looked some other issues but I don't seem to find a way to deal with it. No matter what I do my memory usage will go up to 1.5G in my tests (1000 requests) and never come down, no matter how long I wait.

**Comment by lovell** [comment]
Hello, if you've not already seen them, please read the following previous issues to learn more about how RSS includes free memory that has not (yet) been returned to the OS.

https://github.com/lovell/sharp/search?utf8=%E2%9C%93&q=rss+%22returned+to+the+OS%22&type=Issues

**Comment by tiagofumo** [comment]
We ended up using another lib, so I  won't be able to add info about this issue (like trying fixes and giving feedback about the results).

**Comment by trev-dev** [comment]
@tiagofumo Would love to know what lib you ended up using, as I'm going through thread after thread on this issue. I'm getting super tired of not seeing a clear-cut method of getting memory under control while using both sharp or jimp short of killing my process and letting pm2 pick it back up.

**Comment by saxahan** [comment]
> We ended up using another lib, so I won't be able to add info about this issue (like trying fixes and giving feedback about the results).

Could you tell us the library please?
