### ISSUE TITLE
distortion or bend of image.

### ISSUE THREAD

**Issue by yuanzhanghu** [lovell/sharp#1014]
Hi There, 
Thanks for the beautiful software. I am currently using sharp to do image preprocessing in a deep learning  program.  To let deep neural network learn more generic features of images, i need to do some random distortion or bend on the input images,  while i didn't find such functionalities in sharp docs.  Is there any related APIs that i can use for this purpose?   Or if not,  do we have any plan to implement it ? 
Again, really appreciated for the great software!

**Comment by lovell** [comment]
Hello, do you think exposing the tilt, skew and scale features of `vips_affine` (as being tracked in issue #998 that you created) will provide what you need?

**Comment by yuanzhanghu** [comment]
Thanks for quick reply.    I haven't seen the render result of vips_affine,  if the skew feature is same to skew feature of photoshop, that would be really helpful!   Also i saw distort and warp operations in photoshop: https://www.youtube.com/watch?v=EeJIBD124eU which are really good to have features.

**Comment by lovell** [comment]
Let's track affine support using #998.

libvips supports mapping pixels from an input image via another image using its [mapim](http://jcupitt.github.io/libvips/API/current/libvips-resample.html#vips-mapim) function. We could expose this in sharp but you'd still need to work with raw pixel values to make the mapping image.

Perhaps libvips' Python bindings might be more appropriate for your need? http://libvips.blogspot.co.uk/2015/11/fancy-transforms.html

**Comment by yuanzhanghu** [comment]
sure.   Will do some research on it.  Thanks!
