### ISSUE TITLE
png compressed than the original larger

### ISSUE THREAD

**Issue by littlestar1998** [lovell/sharp#1017]
`
var sharpObj = Sharp(urlencode.decode(origin_full_path_file_name_path))

sharpObj = sharpObj.png({ compressionLevel: 9, adaptiveFiltering: false, force: false })
`

Hello

The original 100k, but after generation by .png({ compressionLevel: 9, adaptiveFiltering: false, force: false }) format 160k, the picture has an alpha transparent color. In addition to returning to the original image. What kind of ways can also be improved?

Thanks

**Comment by lovell** [comment]
Hello, please see #478 and #600 for previous answers to this question.
