### ISSUE TITLE
Got unsupported buffer, help investigate

### ISSUE THREAD

**Issue by gabrielstuff** [lovell/sharp#1018]
Hi, 
I'm currently trying to use sharp and testing it with `download` and `koa`. All packages are at there last version.

See code bellow: 

```
const pipeline = sharp()
    .rotate()
    .resize(null, 200)
    .toBuffer()
```

```
ctx.body = download('https://unicorn.com//img/images/header/logo.png')
    .pipe(pipeline)
```

using: `ctx.body = download('https://unicorn.com//img/images/header/logo.png')` works great when piping to the `pipeline` it does not work. I guess I miss a thing...

The main idea, is to download an image from a remote url, make it pass through the sharp process and return an image with correct header and mime-type to the user through koa.

**Comment by lovell** [comment]
Hello, in your code `pipeline` is being assigned to the result of `toBuffer()`, which returns a Promise rather than a Stream. Remove that method call and it should work.

**Comment by gabrielstuff** [comment]
Perfect and über fast ! Thanks
