### ISSUE TITLE
node js installation error

### ISSUE THREAD

**Issue by srinivasants** [lovell/sharp#1021]
115687 verbose stack Error: cloud-explorer@2.0.0 postinstall: npm run build:fonts && npm run build
115687 verbose stack Exit status 1
115687 verbose stack at EventEmitter. (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
115687 verbose stack at emitTwo (events.js:135:13)
115687 verbose stack at EventEmitter.emit (events.js:224:7)
115687 verbose stack at ChildProcess. (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
115687 verbose stack at emitTwo (events.js:135:13)
115687 verbose stack at ChildProcess.emit (events.js:224:7)
115687 verbose stack at maybeClose (internal/child_process.js:943:16)
115687 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
115688 verbose pkgid cloud-explorer@2.0.0
115689 verbose cwd E:\silex\Silex\Silex
115690 error Windows_NT 6.1.7601
115691 error argv "C:\Program Files\nodejs\node.exe" "C:\Users\admin\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install"
115692 error node v9.1.0
115693 error npm v4.3.0
115694 error code ELIFECYCLE
115695 error errno 1
115696 error cloud-explorer@2.0.0 postinstall: npm run build:fonts && npm run build
115696 error Exit status 1
115697 error Failed at the cloud-explorer@2.0.0 postinstall script 'npm run build:fonts && npm run build'.
115697 error Make sure you have the latest version of node.js and npm installed.
115697 error If you do, this is most likely a problem with the cloud-explorer package,
115697 error not with npm itself.
115697 error Tell the author that this fails on your system:
115697 error npm run build:fonts && npm run build
115697 error You can get information on how to open an issue for this project with:
115697 error npm bugs cloud-explorer
115697 error Or if that isn't available, you can get their info via:
115697 error npm owner ls cloud-explorer
115697 error There is likely additional logging output above.
115698 verbose exit [ 1, true ]

please help me to solve this issue

**Comment by lovell** [comment]
Hello, what part of this error gave the impression this might be a problem with sharp?

**Comment by srinivasants** [comment]
hello sir
       thanks for your response.when i install silexlabs(static website builder) by using npm i face some installation error.then i search for solution to this error i find your page related to my error.and the link is

https://github.com/lovell/sharp/issues/985
 
I follwed solution that you mentioned in that link.but it does not working for me.
stil i am facing some in installing silexlabs.
I also upload the error details.
[2017-11-11T16_02_37_365Z-debug.log](https://github.com/lovell/sharp/files/1465611/2017-11-11T16_02_37_365Z-debug.log)

please provide me a good solution to this error.

**Comment by lovell** [comment]
This is not a problem with sharp. You'll need to ask the people who maintain "silexlabs", perhaps https://github.com/silexlabs/Silex ?
