### ISSUE TITLE
.jpeg({quality:100}) results in larger image file size than the original

### ISSUE THREAD

**Issue by cheadle** [lovell/sharp#1025]
```
sharp('input.jpg')
  .jpeg({quality:100})
  .toFile();
```

The input file is 7.4MB (quality 100). The output file is 18.3 MB. Same thing happens with toBuffer(). Why? How can I output a jpeg with same quality as the original (instead of the default 80) without increasing  file size?

**Comment by lovell** [comment]
Hello, `quality` is not the only attribute that can affect JPEG file size. Concepts such as chroma subsampling and "fancy" downsampling can also have an impact, especially at higher "quality" levels.

Although you've not mentioned platform, my best guess would be that you're using OS X. If so, please see #1006 for a recent example and discussion.

(It's also worth mentioning that the ability for any software to determine the original "quality" setting of a JPEG image depends on it making assumptions about the quantisation tables used at compression time, which may not always be correct.)

**Comment by cheadle** [comment]
Thanks Lovell. Yes, I am on OS X. Looks like sharp v0.19.0 will fix this issue. Great work on this library. It's a pleasure to use.
