### ISSUE TITLE
SHARP_DIST_BASE_URL not working in windows 10

### ISSUE THREAD

**Issue by vinothvk** [lovell/sharp#1026]
I added the system environment variable SHARP_DIST_BASE_URL in windows 10 and did the npm install but  i am getting the error connect ETimedout 104.20.22.46:443. 
I am behind proxy and i self hosted the libvips windows x64 binary in localhost and added that path to the above environment variable
It doesn't look like the install using the variable. Any idea why the variable is not working in windows ?

**Comment by lovell** [comment]
> "connect ETimedout 104.20.22.46:443"

104.20.22.46 belongs to Cloudflare, but this isn't used by sharp so is probably unrelated. Are you able to share the full error log?

> "I am behind proxy and i self hosted the libvips windows x64 binary in localhost and added that path to the above environment variable"

What did you set it to? Are there any proxy-related environment variables set that could affect this?

**Comment by lovell** [comment]
Closing due to a lack of feedback but please re-open with the requested information if the problem persists.
