### ISSUE TITLE
Update Readme for use with TypeScript

### ISSUE THREAD

**Issue by MickL** [lovell/sharp#1029]
I ran into an error using sharp with TypeScript which took me a while to solve. 

You may note within the Readme that the use of TypeScript requires:
`npm install --save @types/sharp`

Also the import should be:
`import * as sharp from 'sharp';`

**Comment by lovell** [comment]
Hello, #975 recently added this to the docs. These will update after the next release.

**Comment by chris-kck** [comment]
@lovell does this library currently support typescript? I dove deep into the documentation but could not find how to use it with typescript. This image shows the error I was encountering both on my localon Mac and on AWS lambda. Please assist.
![Screenshot Capture - 2022-03-09 - 11-17-51](https://user-images.githubusercontent.com/22814329/157429695-1b10d30b-d72a-4466-ac03-42b1b9f0c2c1.png)
.

**Comment by lovell** [comment]
@chris-kck Please open [a new installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) and answer all of the questions if you still require help.
