### ISSUE TITLE
Error: shrink: parameter hshrink not set

### ISSUE THREAD

**Issue by coffeebite** [lovell/sharp#1030]
I have a 1x256 image that I am trying to crop to a 1x1 image using the attention strategy.

Image is here:

https://padlet-assets.s3.amazonaws.com/wallpapers/violet.png

This is how I am doing it:

```javascript
const fs = require('fs');
const sharp = require('sharp');

const img = fs.readFileSync('violet.png');

console.time('violet');
sharp(img)
  .resize(1, 1)
  .crop(sharp.strategy.attention)
  .toBuffer()
  .then(() => console.timeEnd('violet'));
```

I get the following error

```bash
(sharp:64338): GLib-GObject-WARNING **: value "0.031250" of type 'gdouble' is invalid or out of range for property 'hshrink' of type 'gdouble'
Error: shrink: parameter hshrink not set
```

**Comment by lovell** [comment]
Did you see #1003?

**Comment by coffeebite** [comment]
I did. In this case, though, I'm specifying a 1x1 dimension for the target image. In both #1003 and #767, it seems like the target dimensions were going to be sub 0.5. Why would that happen here?

**Comment by lovell** [comment]
Hello, this fails in v0.18.4 but works with the forthcoming v0.19.0 `suit` work-in-progress branch so it looks like https://github.com/lovell/sharp/pull/977 dealt with this.

**Comment by lovell** [comment]
sharp v0.19.0 now available.
