### ISSUE TITLE
Windows: error 127, Unhandled Exception

### ISSUE THREAD

**Issue by gaelgerard** [lovell/sharp#1033]
Hello, 

I'm trying to install a Reactjs script and am a real newbie in CLI.

When launching my installation on windows 10, I have this error

```
$ yarn dev
yarn run v1.3.2
$ gatsby develop -H 0.0.0.0
success delete html files from previous builds — 0.010 s
success open and validate gatsby-config.js — 0.007 s
success copy gatsby files — 0.060 s
error UNHANDLED EXCEPTION


  Error: error: 127\\?\C:\wamp64\www\reactjs.org\node_modules\sharp\build\Releas
  e\sharp.node

  - module.js:11 require
    internal/module.js:11:18

  - constructor.js:9 Object.<anonymous>
    [reactjs.org]/[sharp]/lib/constructor.js:9:15

  - module.js:11 require
    internal/module.js:11:18

  - index.js:3 Object.<anonymous>
    [reactjs.org]/[sharp]/lib/index.js:3:15

  - module.js:11 require
    internal/module.js:11:18


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.


```
As seen above, I run yarn v1.3.2
node v8.9.1

Does anyone have a solution ?

Thanks in advance
g

**Comment by lovell** [comment]
Hello, were there any errors when `yarn install` was run? Are all of the [prerequisites](http://sharp.dimens.io/en/stable/install/#prerequisites) installed?

**Comment by gaelgerard** [comment]
No error, some warnings but success message.
All the prerequisites are installed I think...

Thanks for your help

**Comment by lovell** [comment]
Are you using a 64-bit `node.exe`? http://sharp.dimens.io/en/stable/install/#windows-x64

**Comment by gaelgerard** [comment]
Not sure, I downloaded the msi at this page https://nodejs.org/en/download/.

Is there a better way to install node ?
Thanks

**Comment by lovell** [comment]
Thanks, that page is the right place. It provides both 32-bit and 64-bit versions - did the URL you used to download Node end in x64? `-x64.msi`?

If so, your best best is to open the `C:\wamp64\www\reactjs.org\node_modules\sharp\build\Release\sharp.node` file using [Dependency Walker](http://www.dependencywalker.com/) and see what problems it reports.

It's also worth trying npm rather than yarn to rule out the latter's sometimes-aggressive caching as a possible cause. Good luck!

**Comment by gaelgerard** [comment]
I opened the file using dependency walker with this result 
```
Error: At least one required implicit or forwarded dependency was not found.
Warning: At least one delay-load dependency module was not found.
Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module.
```
And a list of "Error opening file...Not found" essentially "API-MS-WIN..." and "EXT-MS-WIN..." prefixed files except one : IESHIMS.DLL

Do you think this is a clue?
Thanks

**Comment by gaelgerard** [comment]
Hello,
Finally I think my problem doesn't come from Sharp but from the library I'm installing on windows.

I found a begining of explanation [here](https://www.gatsbyjs.org/docs/gatsby-on-windows/) where I should have begin...

Thank you for your time.
Best regards,
g

**Comment by knoxcard** [comment]
This worked wonders for me on a Windows installation...

set GYP_MSVS_VERSION=2015
npm install --msvs_version=2015
npm install node-gyp -g
npm install sharp

Using Yarn?
I went into a different directory and just installed it there, it's all global so it works. Also did this so it wouldn't conflict with my yarn node_modules folder.
