### ISSUE TITLE
Does rotation work as expected?

### ISSUE THREAD

**Issue by 1001v** [lovell/sharp#1034]
Hello. I have a simple web app with route, which performs rotation of image using sharp. Simplified code of route action looks like this:

`let image = await sharp(imagePath)`
`await image.rotate(180).toFile(tmpImagePath)`
// Delete old image
`deleteImage(imagePath)`
// Replace it with tmp image (rename tmp to image)
`renameImage(tmpImagePath, imagePath)`

The problem is that rotation works only one time per app launch. I.e. if i start my app and call this action, everything works fine, but if i call the action another time, nothing will happen with image. It looks like rotated image is been reading as unrotated original image. Like it was cached somewhere, but it shouldn't happen. Please provide me some guidelines. Thank you.

**Comment by lovell** [comment]
Hello, did you see [cache](http://sharp.dimens.io/en/stable/api-utility/#cache)? libvips will cache input files, so if you plan to recycle filenames you'll probably want to disable the file cache.

**Comment by 1001v** [comment]
Yes, that did the trick. Thank you very much, sir!
