### ISSUE TITLE
Calling negate on images with alpha channel inverts all channels

### ISSUE THREAD

**Issue by adamkiss** [lovell/sharp#1035]
Hi,

first of all, thank you for this module. It's been a pleasure to work with, so far.

**The bug**
Running `negate()` on svg file negates the alpha channel of the image, not the colours, regardless of whether the image has been forced to PNG.

**Minimal reproducible test**
https://github.com/adamkiss/sharp-svg-negate-mintest

**Tested files**
- octocat.svg - random octocat svg I found on the internet
- illustrator.svg - default illustrator output of bad emoji with rectangle in the back
- imageoptim.svg - illustrator file I ran through SVGO in ImageOptim

**Expected result**
Transparent PNG with inverted colours.

**Real result**
White PNG with a transparent hole in the middle and white background.

**Versions**
node: 8.9.1
sharp: 0.18.4 (latest, atm)
vips: probably whatever Sharp downloads, but do have 8.5.8 installed on system

Thank you.

**Comment by lovell** [comment]
Hello, I think what we're seeing here is `negate` negating all channels, including the alpha channel. This means you can't see the negated colours because the alpha channel is also negated (if that makes sense).

Making the `negate` behaviour optional on the alpha channel, if any, would make a good enhancement. The improved API could look something like `negate({ alpha: false })` where `alpha` defaults to true, the current behaviour.

As always happy to accept a PR for this.

**Comment by adamkiss** [comment]
Hey @lovell 

* you're right. It negates/inverts all channels, and I've updated issue accordingly
* I've updated the test repo with a few more files, and added script to run vips as well
* vips inverts all channels at the same time as well :/

As for API change, I don't personally see any reason to negate image and it's mask at same time. I'd say adding `negateAlpha` which inverts only the mask and making `negate` to invert only the image would make more sense; but then again, I use only the basics of what Sharp can do, so maybe there are relevant uses for doing stuff on all channels.

Regardless, I am at the moment unable to provide PR - because the codebase is above my level and I don't have time to delve into it :/

Thank you for your work :)

**Comment by rexxars** [comment]
@lovell Can you think of any workarounds for this currently? There isn't a way to "remove the alpha channel and add it back again after inverting" or some such?

**Comment by lovell** [comment]
Implementing the `negate({ alpha: false })` option is probably the quickest option.

The best approach to take would be a bit like the `gamma` operation, where the alpha channel is separated then re-joined:

https://github.com/lovell/sharp/blob/7467fa8b50d280780dfa9fe9a7248deaa499c7a1/src/operations.cc#L106-L110

**Comment by AdamJessop** [comment]
This issue doesn't appear to be resolved. A transparent PNG doesn't negate the alpha channel anymore with the 'false' option, however it doesn't negate any of the colours either.

**Comment by lovell** [comment]
@AdamJessop I've just tried locally with [alpha-layer-1-fill.png](https://github.com/lovell/sharp/blob/master/test/fixtures/alpha-layer-1-fill.png) and it seems to work as-expected. Please can you open a new issue with an example image and code that allows someone else to reproduce this.

**Comment by lovell** [comment]
@AdamJessop Private email is for paid consulting, which I am happy to provide, but assume that's not what you're after here. Please can you open a new issue with an example input image, code that allows someone else to reproduce this, and details of the expected output(s).
