### ISSUE TITLE
Bug: toFile filename extension can take precedence over requested format

### ISSUE THREAD

**Issue by tomgallagher** [lovell/sharp#1037]
Hello

Sharp is super fast, I can't get over how fast it is. Well done!

I've got a question, which is defeating me at the moment.

Images coming in are in jpeg or png. I'm trying to convert to webp and set a different output quality for web and mobile.

Code is:

```
var buffer = fs.readFileSync("./output/" + filename);
var webOutputPath = "./processed_web_output/" + filename;
const pipeline = Sharp(buffer);
pipeline.toFormat('webp', {quality: 60}).toFile(webOutputPath).then(info => { console.log(info); });
```
I'm adjusting the quality settings for mobile to 20 and the output file size doesn't change. And the picture is the same.

Also, when I try to inspect the info afterwards, it is reporting the new file as in the old format. I've found that when using a stream, this doesn't happen. The stream info reports WEBP. I can see why this might be, the toFile might be keying off the file extension. I was wondering if this was another symptom of me doing something wrong.

Sorry for such a basic question. I haven't had these problems working with the stream format. 

Tom

**Comment by lovell** [comment]
Hello, given the full code isn't shown here my best guess would be that the "web" and "mobile" paths might be sharing a sharp instance. If so, try giving each their own instance, e.g.

```javascript
sharp(buffer).toFormat('webp', { quality: 60 }).toFile(webOutputPath)...
sharp(buffer).toFormat('webp', { quality: 20 }).toFile(mobileOutputPath)...
```

**Comment by tomgallagher** [comment]
Thanks a lot for getting back.

It wasn't that they were sharing an instance, I originally tried the above. Then I tried the cloning approach. In both cases I was not getting the correct file type from info and no transforms were happening.

I've moved back to streaming, which I can get to work. Which makes me think it was something to do with the filenaming conventions I have to use and how those interact with the Sharp file read and write processes. I read something about semi-colons in filenames in another issue.

I'd moved away from streaming because I was worried about memory issues as I'm going to be processing some big batches. So I'll just try and batch it before calling the sharp function instead. Or is there a need for batching if I set the Sharp concurrency to a manageable limit? What would you suggest?

Thanks for the attention - on a Sunday as well!

**Comment by lovell** [comment]
Ah, it looks like there's a bug here.
```javascript
sharp(pngBuffer)
  .toFormat('jpeg', { quality: 60 })
  .toFile('out.webp')...
```
...outputs in JPEG format but
```javascript
sharp(pngBuffer)
  .toFormat('webp', { quality: 60 })
  .toFile('out.jpg')...
```
...also outputs JPEG format, so the file extension can (inconsistently) take precedence.

Thanks for reporting. I'll take a look later this week.

**Comment by tomgallagher** [comment]
It's reassuring that I wasn't being totally dense!

Would that then have stopped the quality transformation as well?

**Comment by lovell** [comment]
> "Would that then have stopped the quality transformation as well?"

Yes, it's the same bug.

**Comment by lovell** [comment]
Commit 7115ae5 adds a couple of unit tests that would have caught this, plus the fix. This will be in v0.19.0 - thanks for reporting.

**Comment by lovell** [comment]
sharp v0.19.0 is now available, thanks for reporting this.

**Comment by tomgallagher** [comment]
Thanks for the fix
