### ISSUE TITLE
Weird orcexec.* file

### ISSUE THREAD

**Issue by BorntraegerMarc** [lovell/sharp#1039]
* **Node Version**: v8.9.1 
* **Platform**: Windows (with linux-alpine docker container) 

When running a alpine linux container on Windows every time a new weird file called `orcexec.*` is generated. Where the asterisk * is a placeholder for any string. So sometimes a file `orcexec.oneelL` or sometimes a file `orcexec.BCElgM` is generated. [Apparently these files](https://askubuntu.com/questions/336552/what-are-orcexec-files) are for a JIT compiler.

The problem comes in when committing something to git: I see every time I start my linux server that a new file `orcexec.*` was added and that it can be committed.

Can I disable the `orcexec.*` files?

**Comment by lovell** [comment]
Yes, these are from liborc. You can either try [simd](http://sharp.dimens.io/en/stable/api-utility/#simd) to prevent it being used, or add `orcexec.*` to your `.gitignore` file.
