### ISSUE TITLE
node.js v9.2.0 compatibility

### ISSUE THREAD

**Issue by FranckFreiburger** [lovell/sharp#1042]
After updating to Node.js v9.2.0, I get the following error:
```
Module build failed: Error: The module '\\?\C:\....\node_modules\sharp\build\Release\sharp.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 59. Please try re-compiling or re-installing
...
```

And when I reinstall+compile, I get the following error:
```
  ...
  common.cc
  metadata.cc
  operations.cc
  pipeline.cc
c:\....\.node-gyp\9.2.0\include\node\v8.h(2455): error C2144: syntax error : 'int' should be preceded by ';' (..\src\metadata.cc) [C:\....\node_modules\sharp\build\sharp.vcxproj]
c:\....\.node-gyp\9.2.0\include\node\v8.h(2455): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (....
```
Am I doing something wrong? or sharp has not been ported to nodejs 9.2 ?
Thanks.

**Comment by lovell** [comment]
Hello, please see #1008 for Node 9 discussion.

**Comment by springmeyer** [comment]
The error in #1008 looks different than this error. I hit this error as well at https://github.com/mapbox/node-sqlite3/issues/920.

**Comment by lovell** [comment]
Ah, thanks, looks like (un)setting `msvs_toolset` will solve this edge case.

The `master` branch of sharp seems to be quite happy with Node 9 on Windows - https://ci.appveyor.com/project/lovell/sharp/build/job/6dqeb2xe90mgrdn0
