### ISSUE TITLE
Confusing documentation with input

### ISSUE THREAD

**Issue by niftylettuce** [lovell/sharp#1045]
It is odd that you can pass `input` as a String/Buffer, and also `options` as an Object.  But can you pass both?  What happens when the input is a String and the options is an Object?  What happens when Input is an Object?  I think this needs clarified more in the docs.

**Comment by niftylettuce** [comment]
Is there a special use case when `options.create` exists in `options`?  What happens if both input and options are objects with `options.create`?

**Comment by lovell** [comment]
Hello, sometimes `input` as a String or Buffer needs `options` as an Object to fully describe it, such as for raw pixel input.

The logic to deal with all this is at https://github.com/lovell/sharp/blob/master/lib/input.js#L11 and I'm sure it can be improved

For example, as you suggest, when `input` is an Object then we should probably throw if there's an erroneous attempt to provide `options` also.

**Comment by lovell** [comment]
> "when input is an Object then we should probably throw if there's an erroneous attempt to provide options also"

I just tested this and it already throws an Error, phew.

Always happy to accept PRs to improve the docs.

**Comment by niftylettuce** [comment]
thanks for clarifying and for your hard work @lovell, as always
