### ISSUE TITLE
Document limitations of metadata()

### ISSUE THREAD

**Issue by niftylettuce** [lovell/sharp#1046]
At <http://sharp.dimens.io/en/stable/api-input/#metadata> we do not make a mention anywhere that you cannot call `sharp(input).resize(300, 300).metadata()`.  It will return metadata of the original input, not a resized input.  Therefore this output would yield: `{ width: 100, height: 100 }` and not `{ width: 300, height: 300 }` in the metadata object.

**Comment by niftylettuce** [comment]
Also if `sharp(input).resize(300, 300).metadata()` is possible, how would it be written?  Do we need more transforms?

**Comment by lovell** [comment]
Hello, the call to `resize(300, 300)` sets internal state ready for a subsequent call to `toBuffer`, `toFile` or `pipe` that triggers the processing pipeline.

The following should provide what you need:
```javascript
sharp(input)
  .resize(300, 300)
  .toBuffer((err, data, info) => {
    // info contains metadata for the resized image
  });
```

Perhaps sharp should warn (via the existing `NODE_DEBUG=sharp` infra) about a call to `metadata` after setting internal state?
