### ISSUE TITLE
File missing sharp.node'

### ISSUE THREAD

**Issue by pgengel** [lovell/sharp#1047]
Module not found: Error: Can't resolve '../build/Release/sharp.node' in the following files:
utility.js,
output.js,
input.js ,
constructor.js

**Comment by lovell** [comment]
Hello, are all of the [prerequisites ](http://sharp.dimens.io/en/stable/install/#prerequisites) installed? Are any errors reported when `npm install sharp` is run?

**Comment by pgengel** [comment]
Yes I did not install all the prerequisites with the new version; after installing it worked. 
I think the reason why I had the files initially is because a older version does not depend on the dependacies.
Thanks for the help :-)
