### ISSUE TITLE
Issue during installation

### ISSUE THREAD

**Issue by danikuci1** [lovell/sharp#1048]
hello-

I am having an issue during installation of an application and was pointed here.

Specifically, during installation the CLI outputs these errors:
`npm ERR! Failed at the epoll@0.1.22 install script 'node-gyp rebuild'.`
`npm ERR! Make sure you have the latest version of node.js and npm installed.`
`npm ERR! If you do, this is most likely a problem with the epoll package,`
`npm ERR! not with npm itself.`
`npm ERR! Tell the author that this fails on your system:`
`npm ERR! node-gyp rebuild`

and

`npm ERR! Failed at the sharp@0.16.2 install script 'node-gyp rebuild'.`
`npm ERR! Make sure you have the latest version of node.js and npm installed.`
`npm ERR! If you do, this is most likely a problem with the sharp package,`
`npm ERR! not with npm itself.`
`npm ERR! Tell the author that this fails on your system:`
`npm ERR! node-gyp rebuild`

See more details:
https://github.com/philipptrenz/photo-booth/issues/9

Any assistance you can offer would be fantastic. Thanks.

**Comment by lovell** [comment]
https://github.com/philipptrenz/photo-booth/issues/9
