### ISSUE TITLE
jpg resulting image is larger

### ISSUE THREAD

**Issue by littlestar1998** [lovell/sharp#1050]
I have a question, the original image is 5k, I use sharpObj.jpeg ({'quality': 100}) produced the picture even 9k?

**Comment by littlestar1998** [comment]
system version
Linux ip-172-31-18-158 4.9.62-21.56.amzn1.x86_64 #1 SMP Thu Nov 16 05:37:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

sharp version  
sharp@0.18.4

**Comment by lovell** [comment]
Hello, are you able to share the original image? (Preferably not directly via Github as it can mangle images.)

**Comment by littlestar1998** [comment]
Hello
https://www.dropbox.com/s/d0647h7jx4mo9f1/sharptest.jpg?dl=0

**Comment by littlestar1998** [comment]
test code 

const Sharp = require('sharp');
var sharpObj = Sharp("testsharp.jpg").jpeg({'quality':100}).toFile("/home/koios/newtestsharp.jpg",function () {

})
-rwxr-xr-x 1 root root  5380 Dec  4 04:10 testsharp.jpg*
-rwxr-xr-x 1 root root  9033 Dec  4 09:12 newtestsharp.jpg*

**Comment by lovell** [comment]
The original image was saved with a `quality` of 90. The new image is being saved with a `quality` of 100, so an increased file size is the expected behaviour.

**Comment by littlestar1998** [comment]
sharp how to get save with a  quality of 90

**Comment by lovell** [comment]
```javascript
.jpeg({ quality: 90 })
```
http://sharp.dimens.io/en/stable/api-output/#jpeg

**Comment by littlestar1998** [comment]
Thank you for your patience solution, but my point is, how do you know the quality of this image is 90,

**Comment by lovell** [comment]
Sadly you can't, please see https://github.com/lovell/sharp/issues/908#issuecomment-321993406
