### ISSUE TITLE
Questions regarding the resize function

### ISSUE THREAD

**Issue by Gomennasai** [lovell/sharp#1051]
Hi,

I have two questions that I couldn't answer myself by reading the documentation and trying out a few things.
How can i resize an image keeping the aspect ratio? I don't want it to be automatically cropped.
And if I enter a new width/height that doesn't match the previous aspect ratio, is there a way to simply add a transparent background? 
Example: Image 800 x 400 gets resized to 600 x 400.
Now I want the old picture to be in the centre of this 600 x 400 image with a size of 600 x 300 (same aspect ratio) and the "empty space" around the picture should be a transparent background.

Thanks a lot for your help and have a nice week :)

**Comment by lovell** [comment]
Hello, did you see [embed](http://sharp.dimens.io/en/stable/api-resize/#embed)?

**Comment by Gomennasai** [comment]
Hi,
this works for me.
Thanks a lot 👍
