### ISSUE TITLE
Pre-compiled libvips binaries from local path

### ISSUE THREAD

**Issue by Gomennasai** [lovell/sharp#1053]
Hi, 
is there a possibility to save the .tar.gz files from https://dl.bintray.com/lovell/sharp/ on a local folder and set a relative path like SHARP_DIST_BASE_URL="/lib/" to install them?
Currently it only works for me, when i get the files from your website, but i would like to store them locally.
Thanks for your help.
Kind regards,
Thomas

**Comment by lovell** [comment]
Hello, what is the workflow that leads to this requirement? I ask as I'd like to better understand what you're hoping for given running `npm install` already has a dependency on network connectivity.

**Comment by Gomennasai** [comment]
I would like to deploy an application to Cloud Foundry. Therefore I want to make sure that the application always uses the same version of the native libraries in productive stage.

**Comment by lovell** [comment]
If you're already pinning sharp to a specific version then the pre-compiled binaries will also be pinned - see [config.libvips](https://github.com/lovell/sharp/blob/master/package.json#L93).

**Comment by trigun539** [comment]
I would also like to see if we could add this functionality. Unfortunately, my work has a very strict firewall proxy and having sharp download something by itself is a no-no. We are currently using Nexus lifecycle to host npm modules. If I could tell sharp to use some local file it would be great!

**Comment by lovell** [comment]
@trigun539 Installing libvips globally before installing sharp may be a better solution to your problem.

**Comment by trigun539** [comment]
That's great, I'll test it out. Thanks @lovell

**Comment by trigun539** [comment]
@lovell I have tried multiple ways to install libvips globally, but since I am on windows not sure how to tell sharp that vips.exe is available. I have added it to the path and performed the steps mentioned [here](https://jcupitt.github.io/libvips/install.html#installing-the-windows-binary)

The issue comes from trying to install `gatsby-remark-images` which uses the `gatsby-plugin-sharp` which uses `"sharp": "^0.17.3"`

Please let me know if you have any thoughts on this. Thanks

**Comment by trigun539** [comment]
Also adding the `SHARP_DIST_BASE_URL="local-url"` doesn't work for the `0.17.3` version. It does work for the latest version.

**Comment by lovell** [comment]
Windows *and* strict proxies? The ultimate work-prevention combo.

Perhaps try, after the intial `npm install`, manually fetching then decompressing the contents of `libvips-x.y.z-win32-x64.tar.gz` into `node_modules/sharp/vendor` then run `npm rebuild`.

`SHARP_DIST_BASE_URL` was [added in v0.18.2](http://sharp.dimens.io/en/stable/changelog/#v0182-1st-july-2017)

**Comment by trigun539** [comment]
I know, they make it hard to get things done around here. I'll try that, thanks!
