### ISSUE TITLE
alternate install instructions for AWS Lambda

### ISSUE THREAD

**Issue by hakanson** [lovell/sharp#1054]
Instead of spinning up an EC2 instances, I used the Amazon Linux docker image locally
```
docker run -it amazonlinux:latest /bin/bash
```
Then on the docker image at the `bash-4.2#` prompt:
```
curl -sL https://rpm.nodesource.com/setup_6.x | bash -
yum install -y gcc-c++ nodejs-6.10.3
mkdir /var/task && cd /var/task
npm install sharp
```

Back on the host (in a separate terminal window), I copied node_modules to my project directory. (182008de1f47 is the CONTAINER ID from `docker ps`):
```
docker cp 182008de1f47:/var/task/node_modules .
```

Maybe these could be alternate install instructions in the AWS Lambda section of `docs/install.md`?

**Comment by lovell** [comment]
Hi Kevin, good to hear from you, hope all is well in Eagan.

As you may have guessed, the Lambda instructions were written before Amazon Linux was available as a container image so these could do with an update. Happy to accept a PR for this if you're able.

/cc @felixbuenemann, who wrote the current Lambda docs a couple of years ago and may be able to help review.

**Comment by lovell** [comment]
https://github.com/lambci/docker-lambda might also be suitable, especially image tagged with `:build`.

**Comment by hakanson** [comment]
Yes, https://github.com/awslabs/aws-sam-local even uses that docker-lambda image.  It is on my list to look at as well.

**Comment by hakanson** [comment]
I was able to add an npm script in my `package.json` and then do a `npm run dockerbuild` using that image.  I was also able to test inside the docker image after `npm install docker-lambda`

```
  "scripts": {
    "dockerbuild": "docker run -v \"$PWD\":/var/task lambci/lambda:build-nodejs6.10"
  },
```

**Comment by lovell** [comment]
I've updated the installation docs to recommend use of the `lambci/lambda` image - see http://sharp.dimens.io/en/latest/install/#aws-lambda

**Comment by love8587** [comment]
@lovell I'm sorry but I can't understand the document instruction. 
I added
```
"scripts": {
    "dockerbuild": "docker run -v \"$PWD\":/var/task lambci/lambda:build-nodejs6.10"
  },
``` in package.json and require the module in handler.js 

`const sharp = require('./sharp')`

But it fails to load the module. 

How can I use Sharp module in AWS Lambda !?

**Comment by stephan-nordnes-eriksen** [comment]
I am having some issue with this while using typescript and webpack. I do the docker-npm install, and that seems to do it's thing, but I still get this issue when deploying to AWS lambda. 

It says; `[684] external "sharp" 42 bytes {0} [built]`
and `Serverless: Packing external modules: sharp@^0.20.5`.

Perhaps serverless-webpack is changing the binary somehow?
