### ISSUE TITLE
Can't use the module

### ISSUE THREAD

**Issue by sbatururimi** [lovell/sharp#1056]
I got the following error after installing with npm:
```
/node_modules/sharp/build/Release/sharp.node'
0|RunOn_AP | was compiled against a different Node.js version using
0|RunOn_AP | NODE_MODULE_VERSION 48. This version of Node.js requires
0|RunOn_AP | NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
0|RunOn_AP | the module (for instance, using `npm rebuild` or `npm install`).
```
Running `npm rebuild` or `npm install` didn't help. Any suggestion?

PS:I'm using node v8.9.1

**Comment by lovell** [comment]
The error message says the version of Node used at `npm install` time is different to the version being used at run time.

NODE_MODULE_VERSION 48 is Node 5 and NODE_MODULE_VERSION 57 is Node 8 - see https://nodejs.org/en/download/releases/

There's probably an old version of Node 5 on your machine that `npm` is erroneously using.

**Comment by lovell** [comment]
@sbatururimi Were you able to make progress with this?

**Comment by sbatururimi** [comment]
@lovell Yes, I have finally fixed it by cleaning old module versions
