### ISSUE TITLE
Error with Input buffer on zeit/now platform

### ISSUE THREAD

**Issue by elrumordelaluz** [lovell/sharp#1058]
First of all, thanks for this great and useful module!

### Description
[This](https://github.com/elrumordelaluz/sharp-test/blob/master/index.js) code essentially converts an `svg` `String` into `Buffer` to pass as _input_ to `sharp` and then obtain its `png` _output_, works as expected.

Something like:
```js
const src = `<svg>…</svg>`
const buff = Buffer.from(src)
sharp(buff).toBuffer().then(data => console.log(data))
```

### Expected behaviour
Running it in my local machine works as expected:
![sharp1](https://user-images.githubusercontent.com/784056/33834035-e9579436-de81-11e7-8cc5-d6df49910e10.gif)

>  Local machine is Max OS X El Capital (10.11.6)

Works well also in another computer Ubuntu 16.04.3.

### Problem
I am trying to deploy a _microservice_ that use at some point similar code of [this](https://github.com/elrumordelaluz/sharp-test/blob/master/index.js) reproduction, and love the simplicity of [now](https://zeit.co/now), but when [deploying it](https://sharp-test.now.sh/) doesn't work as expected. Returns:

> Error: Input buffer contains unsupported image format

![sharp2](https://user-images.githubusercontent.com/784056/33834321-da46edc4-de82-11e7-91d4-560bb8362dac.gif)

### Repo

I created a repository with the simplest code I found break the functionality here: https://github.com/elrumordelaluz/sharp-test
The endpoint deployed using `now` is https://sharp-test.now.sh/

Please, let me know if you think is a issue related on `now` platform or deployment process instead if `sharp`.

Thanks in advance and congrats for the great work!

**Comment by lovell** [comment]
Hello, this looks a bit like #979, where `Buffer` is being replaced/polyfilled by a runtime environment.

Are you able to test if changing [instanceof Buffer](https://github.com/lovell/sharp/blob/master/lib/is.js#L48) to `Buffer.isBuffer` fixes this?

**Comment by elrumordelaluz** [comment]
Hi @lovell, yes seems pretty similar.

I made another `deploy` here https://sharp-test-hkhedybbve.now.sh/ adding 
```js
const buff = Buffer.from(src)
console.log({
  instanceof: buff instanceof Buffer,
  isBuffer: Buffer.isBuffer(buff)
})
```
and in both cases (local and zeit/now) logs:

```bash
{ instanceof: true, isBuffer: true }
```

![screen shot 2017-12-11 at 15 28 02](https://user-images.githubusercontent.com/784056/33835796-e7812216-de87-11e7-9988-512b94734578.png)

**Comment by elrumordelaluz** [comment]
Please let me know if I can do any other thing to test, super happy to contribute.

In the last comment you ask to make some change [here](https://github.com/lovell/sharp/blob/master/lib/is.js#L48). You mean to make a `fork` and then point the [repro](https://github.com/elrumordelaluz/sharp-test) to the forked module?

**Comment by lovell** [comment]
It's possible that the zeit/now platform provides a globally-installed vips that is being used. What does the following generate?
```javascript
console.log(sharp.format);
console.log(sharp.versions);
```
http://sharp.dimens.io/en/stable/api-constructor/#format
http://sharp.dimens.io/en/stable/api-constructor/#versions

**Comment by lovell** [comment]
https://github.com/zeit/now-cli/issues/639#issuecomment-306534497 suggests `vips` is made available globally to the zeit/now runtime. https://git.alpinelinux.org/cgit/aports/tree/testing/vips/APKBUILD does not include librsvg so SVG support will not currently be available.

**Comment by elrumordelaluz** [comment]
Here's the logs:
```bash
{ jpeg: 
   { id: 'jpeg',
     input: { file: true, buffer: true, stream: true },
     output: { file: true, buffer: true, stream: true } },
  png: 
   { id: 'png',
     input: { file: true, buffer: true, stream: true },
     output: { file: true, buffer: true, stream: true } },
  webp: 
   { id: 'webp',
     input: { file: true, buffer: true, stream: true },
     output: { file: true, buffer: true, stream: true } },
  tiff: 
   { id: 'tiff',
     input: { file: true, buffer: true, stream: true },
     output: { file: true, buffer: true, stream: true } },
  magick: 
   { id: 'magick',
     input: { file: false, buffer: false, stream: false },
     output: { file: false, buffer: false, stream: false } },
  openslide: 
   { id: 'openslide',
     input: { file: false, buffer: false, stream: false },
     output: { file: false, buffer: false, stream: false } },
  dz: 
   { id: 'dz',
     input: { file: false, buffer: false, stream: false },
     output: { file: false, buffer: false, stream: false } },
  ppm: 
   { id: 'ppm',
     input: { file: true, buffer: false, stream: false },
     output: { file: true, buffer: false, stream: false } },
  fits: 
   { id: 'fits',
     input: { file: false, buffer: false, stream: false },
     output: { file: false, buffer: false, stream: false } },
  gif: 
   { id: 'gif',
     input: { file: true, buffer: true, stream: true },
     output: { file: false, buffer: false, stream: false } },
  svg: 
   { id: 'svg',
     input: { file: false, buffer: false, stream: false },
     output: { file: false, buffer: false, stream: false } },
  pdf: 
   { id: 'pdf',
     input: { file: false, buffer: false, stream: false },
     output: { file: false, buffer: false, stream: false } },
  v: 
   { id: 'v',
     input: { file: false, buffer: false, stream: false },
     output: { file: false, buffer: false, stream: false } },
  raw: 
   { id: 'raw',
     input: { file: false, buffer: true, stream: true },
     output: { file: false, buffer: true, stream: true } } }

{ vips: '8.5.8' }
```
[Maybe related](https://zeit.co/blog/faster-javascript-deployments#2.-side-effects-caching)?

**Comment by lovell** [comment]
Thanks, this confirms that zeit/now provides a globally-installed libvips v8.5.8 that has been compiled without SVG support. You'll need to take this one up with them, good luck!

**Comment by elrumordelaluz** [comment]
Thanks for your support @lovell

**Comment by TooTallNate** [comment]
The version of libvips on ZEIT Now includes SVG input support now. I believe this issue can be closed.

**Comment by elrumordelaluz** [comment]
> includes SVG input support now.

I can confirm that works as expected [here](https://elrumordelaluz.github.io/micro-outline-stroke/)

Thanks @TooTallNate and @lovell
