### ISSUE TITLE
Cannot install vips on node:7.10-alpine

### ISSUE THREAD

**Issue by janrevis** [lovell/sharp#1060]
I cannot install the vips dependency as described in the  install.MD.  I've add the line to install the package as described the install docs:

RUN apk -U add openssl && \
    apk add vips-dev fftw-dev --update-cache --repository https://dl-3.alpinelinux.org/alpine/edge/testing/ && \
    apk add --no-cache git && \
    yarn global add pm2 && \
    yarn

But install vips fails with the following error:

ERROR: unsatisfiable constraints:
  so:libwebp.so.7 (missing):
    required by: vips-8.5.8-r0[so:libwebp.so.7]
                 vips-8.5.8-r0[so:libwebp.so.7]
                 vips-8.5.8-r0[so:libwebp.so.7]
                 vips-8.5.8-r0[so:libwebp.so.7]
  so:libwebpmux.so.3 (missing):
    required by:
                 vips-8.5.8-r0[so:libwebpmux.so.3]
                 vips-8.5.8-r0[so:libwebpmux.so.3]
                 vips-8.5.8-r0[so:libwebpmux.so.3]
                 vips-8.5.8-r0[so:libwebpmux.so.3]

**Comment by lovell** [comment]
`node:7.10-alpine` probably has an out-of-date libwebp and according to https://github.com/nodejs/docker-node/commit/a2600f4e0e4af5abd4a8e2a88cf46337500dbe7c it's also unsupported.

**Comment by damianobarbati** [comment]
@lovell does this means we cannot use sharp with alpine (3.7)?

```
error An unexpected error occurred: "/var/email-assistant/node_modules/sharp: Command failed.
Exit code: 1
Command: sh
Arguments: -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Directory: /var/email-assistant/node_modules/sharp
Output:
ERR! sharp Use with musl libc requires manual installation of libvips >= 8.6.1
ERR! sharp Please see http://sharp.pixelplumbing.com/page/install
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)".
```
