### ISSUE TITLE
Validate files to be non-corrupt before resizing

### ISSUE THREAD

**Issue by adriaanmeuris** [lovell/sharp#1061]
We're processing files using Sharp and see errors upon resizing corrupt files (libvips warnings like `Corrupt JPEG data: bad Huffman code` or `Invalid SOS parameters for sequential JPEG`).

These errors only occur during resize, retrieving metadata works just fine. Since we're storing the original files and only serve resized files on request, I was wondering if there's any way to validate a file to be non-corrupt, without needing to resize to check every uploaded image for errors.

Example image attached as a zip file to prevent GitHub from resizing it: [example-image.zip](https://github.com/lovell/sharp/files/1552179/example-image.zip)

You'll be able to retrieve metadata using this file, but trying to resize it, will throw the `Corrupt JPEG data: bad Huffman code` error. Any suggestions are greatly appreciated.

**Comment by lovell** [comment]
Hello, all the pixel data will need to be decoded/decompressed to validate an image.

Perhaps the forthcoming [stats](http://sharp.dimens.io/en/latest/api-input/#stats) feature in v0.19.0 may help, as it will do this but only return a summary of the pixel data (or provide an error for invalid data).

**Comment by adriaanmeuris** [comment]
appreciate your quick response - will definitely try that one on the image I provided.
This will help us to develop tests which can incorporate in our workflow.

Do you know af any image test suite that contains images which would trigger all errors that are listed in `jerror.h`of libvips?

**Comment by lovell** [comment]
Perhaps use a fuzzing tool such as [AFL](http://lcamtuf.coredump.cx/afl/) to generate bad images from good.
