### ISSUE TITLE
Will sharp work in AWS lambda node v6.10 ?   The docs talks about node 4.X.

### ISSUE THREAD

**Issue by martin-gillen** [lovell/sharp#1062]
This issue suggests it may work with node 6:

- https://github.com/lovell/sharp/issues/422

I would like to use sharp on AWS lambda with the latest node.js.

**Comment by lovell** [comment]
Hello, yes it will work, please see #1054 for some discussion about modernising the Lambda docs.

**Comment by martin-gillen** [comment]
Thanks!
