### ISSUE TITLE
Resized images are somehow corrupted using chokidar

### ISSUE THREAD

**Issue by karlpatrickespiritu** [lovell/sharp#1063]
Hi. Let me start off by saying this is a great library. I just encountered some problems when resizing on a mac. Images are somehow chopped. See sample image below.

![selection_016](https://user-images.githubusercontent.com/10472504/33936154-7ff018e2-e039-11e7-9087-2e6b30c2ea6a.png)

Did I miss something?

**Comment by lovell** [comment]
Hello, this looks like it could be a corrupt input image. Are you able to share the original image? Are you using Stream-based input that could have been truncated?

**Comment by karlpatrickespiritu** [comment]
Yeah the thing is the image isn't corrupt. I'm not using steam-based input. The way the app works is it watches for new files on a certain folder on a pc/laptop (I'm using [chokidar](https://github.com/paulmillr/chokidar)). And when new files are added, each of them gets resized and uploaded to s3. Funny thing is that most of the time it works perfectly, but sometimes it does this awkward resize.

**Comment by karlpatrickespiritu** [comment]
The resize part is pretty straight forward. Here is is:

```javascript
sharp(filePath)
        .rotate()
        .resize(700, 700)
        .max()
        .quality(80)
        .withMetadata()
        .toFile(outputFilePath)
        .then((resized)=> resolve(resized))
        .catch((error) => {
          console.log(error)
          reject({ resizeImage: error.stack })
        })
```

**Comment by lovell** [comment]
Has `chokidar` been configured via `awaitWriteFinish` to wait for the file to be complete before the event is fired?

> "By default, the add event will fire when a file first appears on disk, before the entire file has been written" https://github.com/paulmillr/chokidar#performance

**Comment by karlpatrickespiritu** [comment]
Thanks @lovell! So far not getting this on a ubuntu. But will cross test. Will close this after. Thanks
