### ISSUE TITLE
Multiple dependencies cause /vendor issues

### ISSUE THREAD

**Issue by mikestopcontinues** [lovell/sharp#1078]
My project depends on `sharp` and `smartcrop-sharp` which also, naturally, depends on `sharp`. When I attempt to deploy to netlify, only `smartcrop-sharp` installs `libvips` to `/vendor`, making it so that my script fails to run because my `sharp`'s `libvips` version doesn't exist. Thoughts?

**Comment by lovell** [comment]
Hello, libvips is loaded as a shared library, so the first version of sharp to be `require`d will "win". Either ensure `require('sharp')` occurs before `require('smartcrop-sharp')` or globally-install libvips before `npm install`.

https://github.com/jwagner/smartcrop-sharp/pull/3 should address this particular problem too as it moves sharp to be a peer dependency (as well as upgrading).
