### ISSUE TITLE
Alpine: which dependencies are unnecessary at runtime?

### ISSUE THREAD

**Issue by zhcsyncer** [lovell/sharp#1084]
It doesn't work on the alpine-based docker image when I delete the vips-dev.

**Comment by lovell** [comment]
Hello, the `vips` and `vips-dev` packages are required at `npm install` (compile) time but only the `vips` package is required at runtime when using Alpine.

**Comment by zhcsyncer** [comment]
thks.
When I used `apk add vips-dev` to install `vips-dev`, `vips` was installed as a dependency of `vips-dev`, so when `apk del vips-dev` was executed, `apk` was also deleted by `apk`.
