### ISSUE TITLE
Add option not to reduce images

### ISSUE THREAD

**Issue by rannn505** [lovell/sharp#1085]
Hey,

In my opinion, as there is the withoutEnlargement() option, it should also be the opposite of it. (withoutReduction() or something withoutShrink())
Is it expected to be implemented? Do you need help with this?

thx,
Ran

**Comment by lovell** [comment]
Hello, a `withoutReduction` feature does not currently exist nor am I aware of it having been requested before.

I think this would be approximately equivalent to the `<` geometry of *magick:

> "Enlarges an image with dimension(s) smaller than the corresponding width and/or height argument(s)." https://www.imagemagick.org/script/command-line-processing.php#geometry

As always, happy for a PR with tests to implement this.

**Comment by oaleynik** [comment]
@lovell found it: https://github.com/ImageMagick/ImageMagick/blob/aa413353e3dc86c56a44d23f1d1d4db67e0911ff/MagickCore/geometry.c#L1490

I will try to implement this on weekends. Unless you will know how to do this quickly :)

**Comment by christopherbradleybanks** [comment]
> Hello, a `withoutReduction` feature does not currently exist nor am I aware of it having been requested before.
> 
> I think this would be approximately equivalent to the `<` geometry of *magick:
> 
> > "Enlarges an image with dimension(s) smaller than the corresponding width and/or height argument(s)." https://www.imagemagick.org/script/command-line-processing.php#geometry
> 
> As always, happy for a PR with tests to implement this.

I'm currently working with Sharp in my project and required this feature so I took a stab at implementing it. 
https://github.com/lovell/sharp/pull/3006

**Comment by lovell** [comment]
v0.30.0 now available with this feature, thanks for the PR!

**Comment by rannn505** [comment]
@lovell @christopherbradleybanks cool guys .. thanks 🙏🏽 🥇
