### ISSUE TITLE
This png file makes the metadata function die

### ISSUE THREAD

**Issue by DaGaMs** [lovell/sharp#1088]
I noticed that this image failed to process when trying to create thumbnails. I'm not sure why that is. I tried 

    >$ vipsheader pileup_image_igv_tp53.png 
    pileup_image_igv_tp53.png: 2406x1192 uchar, 3 bands, srgb, pngload

with vips 8.6.1. That seems ok? Maybe the `3 bands` is the issue? The `metadata` function just returns with an empty object `{}` as error, and `undefined` as metadata. No other error message...

![pileup_image_igv_tp53](https://user-images.githubusercontent.com/236646/34836037-90f7bb56-f6ee-11e7-84a6-04a396dc4988.png)

**Comment by lovell** [comment]
Hello, this image works fine with v0.18.4 when I test locally.
```sh
$ node -v
v8.9.4
$ curl -O https://user-images.githubusercontent.com/236646/34836037-90f7bb56-f6ee-11e7-84a6-04a396dc4988.png
$ npm install sharp@0.18.4
$ node -e "require('sharp')('34836037-90f7bb56-f6ee-11e7-84a6-04a396dc4988.png').metadata(console.log)"
null { format: 'png',
  width: 2406,
  height: 1192,
  space: 'srgb',
  channels: 3,
  depth: 'uchar',
  density: 72,
  hasProfile: false,
  hasAlpha: false }
```
Which version of sharp? Which platform? Is GitHub de-mangling the image?

**Comment by DaGaMs** [comment]
Strange. I'm also on 0.18.4, compiled against vips 8.6.1 (on my mac, but I had the same issue on linux with an older version of vips and sharp). I'm attaching a zipped copy of the file, in case github accidentally "fixed" it.
[pileup_image_igv_tp53.png.zip](https://github.com/lovell/sharp/files/1625896/pileup_image_igv_tp53.png.zip)

**Comment by lovell** [comment]
Do you have the problem with v0.19.0 (released yesterday)?

**Comment by DaGaMs** [comment]
Not tried yet - let me see...

**Comment by DaGaMs** [comment]
I think there was some issue with my version of vips. I recompiled vips from source, with a different version of libtiff (4.0.8 instead of 4.0.9), and that seems to have fixed the metadata issue. I have no idea why. Anyway, sorry for the confusion. This took a lot of effort to chase down...
