### ISSUE TITLE
Idea: stepped resize to improve quality

### ISSUE THREAD

**Issue by homerjam** [lovell/sharp#109]
Hi,

This library is great and vips is going to provide much needed stability and performance in my use case. However a key difference for me between sharp/vips and gm/imagemagick is the quality when resizing down (downsampling?). Sharp produces "crunchier" images compared to gm, I experimented with different interpolation methods but found that it didn't really make a difference.

What I have ended up doing is a stepped resize, the first step simply takes the image and resizes it to double the desired size and the second step takes the output buffer of step one and performs the resize as normal. Obviously this effectively doubles the workload (I guess?) but when quality is paramount its acceptable for me, its also still at least twice as fast as gm.

My idea is basically to include an option that could perform a 'stepped resize' for you if needed.

Thanks

Sharp using stepped resize:
![image](https://cloud.githubusercontent.com/assets/1055769/4768432/0ca18724-5b6a-11e4-98cc-caff7d919fab.png)

Gm:
![image](https://cloud.githubusercontent.com/assets/1055769/4768436/2371911a-5b6a-11e4-8885-ab6da99dd88b.png)

Sharp without stepped resize:
![image](https://cloud.githubusercontent.com/assets/1055769/4768457/58766fac-5b6a-11e4-9897-64f2243e674b.png)

**Comment by lovell** [comment]
I hope to migrate to using the improved `vips_resize` as part of #310, thanks mainly to commit https://github.com/jcupitt/libvips/commit/8506ff13a674372d28b62b4a5e5f3e22e516fc01 from John.

I'm closing this issue so feel free to add comments/feedback at #310 - thanks again for all the help and suggestions you've made to improve image quality!
