### ISSUE TITLE
Scale up doesn't seem to work

### ISSUE THREAD

**Issue by MarkMurphy** [lovell/sharp#1090]
Attempting to scale an image that's 200x200 up to 300x300 doesn't seem to work.

```
image.resize(300).max();
```

Using sharp 
"0.18.4"

Here's my test image:
![example2](https://user-images.githubusercontent.com/873474/34901233-e1bf3af6-f7dd-11e7-966d-740cee6667f0.jpg)

**Comment by lovell** [comment]
Hello, sharp v0.18.4 and v0.19.0 produce the same, correct output for me with this input image.

```javascript
const sharp = require('sharp');
sharp('34901233-e1bf3af6-f7dd-11e7-966d-740cee6667f0.jpg')
  .resize(300)
  .max()
  .toFile('out.jpg', console.log);
```
prints:
```
null { format: 'jpeg',
  width: 300,
  height: 300,
  channels: 3,
  premultiplied: false,
  size: 15254 } null
```
and generates a 300x300 JPEG output:
```sh
$ identify out.jpg
out.jpg JPEG 300x300+0+0 DirectClass 8-bit 14.9Ki 0.000u 0:01
```

**Comment by MarkMurphy** [comment]
huh, weird...that works for me too. There must be something else going on it my script that's causing the problem.
