### ISSUE TITLE
Problem with image size

### ISSUE THREAD

**Issue by underscore05** [lovell/sharp#1092]
Why instead of reducing the image size because of resizing down. The image get's bigger?
```
Original image                = 5316 × 2795 = 520 KB
Resized image                = 1600 × 841   = 1.4 MB
(Optmized 70%) image   = 1600 × 841  = 613 KB
```

**Comment by lovell** [comment]
Hello, there's not a lot to go on here but my best guess would be that the original image is a JPEG at a low quality setting. If so, please see the `quality` option of [jpeg](http://sharp.pixelplumbing.com/en/stable/api-output/#jpeg).

**Comment by underscore05** [comment]
My bad. The image format of the original image is JPEG, while the resized image is PNG. Thank you.
