### ISSUE TITLE
Zoom control option

### ISSUE THREAD

**Issue by GretaLahitte** [lovell/sharp#1093]
Hi and thank you for your great job.
I'm using sharp to 'tilify' a pdf (3000px*2000px) and use it with leaflet library, it creates 12 folders so my max zoom level is 12.
Unfortunately this is not enough, i may missing something elementary but is there a way to specify the max zoom level?

**Comment by lovell** [comment]
Hello, the `layout` option of [tile](http://sharp.pixelplumbing.com/en/stable/api-output/#tile) provides access to other tile "layouts" such as Zoomify and Google Maps, which might be closer to what you need.

If you've not already done so, you might also want to try rendering the PDF at a higher initial resolution via [density](http://sharp.pixelplumbing.com/en/stable/api-constructor/#sharp), something like:

```javascript
sharp(pdfInput, { density: 300 })
  .tile()
  ...
```

**Comment by GretaLahitte** [comment]
Thank you, density do the trick.
However I will have a look to Zoomify and Googlify.

Thank you very much.

**Comment by lovell** [comment]
Great, glad to hear you got it working.
