### ISSUE TITLE
Add support for overriding Promise

### ISSUE THREAD

**Issue by hovosanoyan** [lovell/sharp#1094]
It will be great to have an option for using custom Promise library. I tried to find an existing issue but seems there is nothing about this feature.

**Comment by lovell** [comment]
Hello, are you able to expand on what benefit(s) this might provide?

**Comment by hovosanoyan** [comment]
All listed benefits in this [answer](https://stackoverflow.com/questions/34960886/are-there-still-reasons-to-use-promise-libraries-like-q-or-bluebird-now-that-we#answers-header). I think this must be enough for supporting options for changing it.

Not changing the default Promise but just adding option in API for changing it. Something like
```js
const sharp = require('sharp')

sharp.Promise = require('some-promise')
```

**Comment by lovell** [comment]
I'm not sure the 6 benefits in the quoted answer apply here.

1, 3 and 5 all relate to static, non-standard Promise methods that will be ignored by sharp internally. If people really need 2 then they are probably not going to be using Promises, be they native or library-provided. 4 relates to the unsupported client-side environment. 6 might be useful, but this would typically relate to a sharp-returned Promise joining an existing Promise chain that is already under the control of the calling code.

Given people can mix/wrap Promise instances returned by sharp with Promise instances returned by other libraries, is Promise-injection really needed? I prefer to keep things simple, but let's see what others think.

(Before the omnipresence of a Promise implementation in Node, sharp used to depend on bluebird exclusively.)

**Comment by lovell** [comment]
Thanks for the original suggestions. I'm going to close this due to lack of feedback and unclear benefits but please feel free to re-open or comment further if there is compelling evidence that this should be revisited.
