### ISSUE TITLE
On FreeBSD: version ZLIB_1.2.9 required by /usr/local/lib/libpng16.so .16 not found

### ISSUE THREAD

**Issue by jamesfmackenzie** [lovell/sharp#1095]
Similar but slightly different to some of the other issues out there. Unsure how to get this working on FreeBSD. 

1. I've installed libpng systemwide via ports:

`pkg install -y pkgconf vips`

2. I've confirmed this is installed correctly:

```
root@FreeBSD:/ # pkg-config --modversion vips-cpp                               
8.6.1
```

3. I've update package.json to reference the systemwide install of vips:

```
  "config": {                                                                   
    "libvips": "8.6.1"                                                          
  }
``` 

4. npm install completes successfully with no issues

5. At runtime, I receive the following error:

```
module.js:670                                                                   
  return process.dlopen(module, path.toNamespacedPath(filename));               
                 ^                                                              
                                                                                
Error: /lib/libz.so.6: version ZLIB_1.2.9 required by /usr/local/lib/libpng16.so
.16 not found
```

6. require('sharp') is the first line of my script. It's a very simple console script with not much else in there.

7. I have ZLIB 1.2.11 installed (ships with FreeBSD). Expecting this to be fine as it's >= 1.2.9

```
root@FreeBSD:/ # node -e "console.log(process.versions.zlib)"                   
1.2.11
```

**Comment by lovell** [comment]
Hello, `process.versions.zlib` tells you the version of zlib that Node was statically linked with at compile time. This is not the same version that a globally-installed libpng shared library will link with at run time.

From your report it looks like the `/usr/local/lib/libpng16.so` shared library will link with the `/lib/libz.so.6` shared library at run time.

https://www.google.co.uk/search?q=FreeBSD+ZLIB_1.2.9+libpng16.so+site:forums.freebsd.org suggests a system upgrade will help. Good luck!

**Comment by jamesfmackenzie** [comment]
Thanks. I created a new 11.1 Jail (previously I was on 11.0) and installed sharp. Everything working fine now!

An interesting side note - I was *not* able to get sharp working with libvips from ports. I had to make my own.

**Comment by vpzomtrrfrt** [comment]
For anyone who stumbles upon this later, what fixed it for me was requiring sharp *before* pg.  I don't know why it changed anything, but it seems to have worked

**Comment by Slapbox** [comment]
@lovell I'm using Linux Mint 18.3 which provides `zlib@1.2.11`, but when I try to run my Electron application in development it throws this same error, looking for `zlib@1.2.9`. I don't understand why Sharp is looking for `zlib@1.2.9` instead of `zlib@1.2.11` in this case. 

When I run `process.versions.zlib` I get `1.2.11`.

Can you help me understand what I'm missing here?

**Comment by lovell** [comment]
@Slapbox

* `ZLIB_1.2.9` is a symbol provided by all versions of zlib from v1.2.9 onwards.
* Mint 18.3 is based on Ubuntu 16.04, which provides zlib v1.2.8
* `process.versions.zlib` refers to the statically-linked version inside Node and is irrelevant here.
