### ISSUE TITLE
Add link to https://www.npmjs.com/package/windows-build-tools in Windows-specific install docs

### ISSUE THREAD

**Issue by vicwue** [lovell/sharp#1097]
Hi @lovell 
love what you have done!

I had some issues getting a simple command to work:
`npm install sharp --save`

i did follow the instructions on a clean win10 x64 machine listed here [Prerequisites sharp](http://sharp.dimens.io/en/stable/install/#prerequisites)
Python 2.7, Visual Studio 2017, node-gyp and even MinGW for g++ were installed.

all attempts failed with a"node-gyp" error so i'm guessing i do have a PATH problem somewhere ...

i had to look through closed issues to find the final hint ... please add this line to Prerequisites as a time saver of about 3h to troubleshooting Windows users! 
`npm install --global windows-build-tools`

Thanks.

**Comment by lovell** [comment]
Hello, glad you got it working in the end.

MSVC is a dependency of node-gyp for Windows - it's included on the page linked to by the [prerequisites](http://sharp.pixelplumbing.com/en/stable/install/#prerequisites) but I agree this could be a bit clearer.

Happy to accept a PR to add a link in the [Windows](http://sharp.pixelplumbing.com/en/stable/install/#windows-x64) section if you're able.

**Comment by lovell** [comment]
#186 removes the need for `node-gyp` for most users and updates the installation docs accordingly.
