### ISSUE TITLE
Metadata is just '{}', no proper error

### ISSUE THREAD

**Issue by JonasT** [lovell/sharp#1098]
I am trying to load an image, but `sharp(affected_image_path).metadata().width` is undefined. I also tried `JSON.stringify(sharp(affected_image_path).metadata())` which just gives me the output `"{}"`. 

It seems sharp somehow fails to load the image, or I am misunderstanding the docs fundamentally. If it's a loading error, I really would expect an error to be thrown or any sort of better feedback than just entirely missing metadata.

**Comment by JonasT** [comment]
Is there a synchronous way to read it? I don't mind the wait in the spot where that happens, I'm already showing a loading screen.

**Comment by lovell** [comment]
`metadata()` is always asynchronous, accepting either a callback or returning a Promise.

http://sharp.pixelplumbing.com/en/stable/api-input/#metadata
