### ISSUE TITLE
Multi-page TIFF support

### ISSUE THREAD

**Issue by ronanww** [lovell/sharp#1101]
Hi,

Is there any way to have a multi-page TIFF as input, select one page from the multi page and have it as the output as a JPG?

Thanks!

Ronan

**Comment by lovell** [comment]
Hello, please see PR #654 for a previous attempt at this. Happy to accept a new PR.

**Comment by theviking** [comment]
+1 please

**Comment by lovell** [comment]
v0.20.2 now available with this feature.
