### ISSUE TITLE
Meet-up: Paris (près de Station F, Chevaleret), 17:30h, mercredi 7 février, 2018

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#1103]
Bonjour à tous les utilisateurs de sharp (et libvips) en France.

Je m'attends à être à Paris le mercredi 7 février au soir et je serais ravi de rencontrer le plus grand nombre de personnes possible (ou d'ailleurs toute personne ayant plus qu'un intérêt passager pour les technologies Internet).

Si vous êtes disponible et que vous souhaitez vous rencontrer, abonnez-vous à ce "issue", ajoutez un commentaire ou envoyez-moi [un e-mail](https://github.com/lovell/sharp/blob/da5deb81776fba12cc99f08d2fc364f55a2a7f0b/package.json#L5) et nous pourrons faire le tri.

/

Hello to all the sharp (and libvips) users in France.

I expect to be in Paris on the evening of Wednesday, 7th February and would love to meet as many of you as possible (or for that matter anyone with more than a passing interest in Internet technologies).

If you're available and would like to meet up, subscribe to this "issue", add a comment or send me [an e-mail](https://github.com/lovell/sharp/blob/da5deb81776fba12cc99f08d2fc364f55a2a7f0b/package.json#L5) and we can sort something out.

**Comment by jaubourg** [comment]
Morning, afternoon or evening ? Could manage something at [Station F](https://stationf.co/) if it's on the morning or the afternoon :)

**Comment by jaubourg** [comment]
You said evening, silly me :P

**Comment by ncoden** [comment]
@lovell I would happy to see you at Station F too ;)

**Comment by lovell** [comment]
I've heard a lot about Station F and would be très happy to meet in that area. Recommendations for a suitable venue nearby are most welcome.

**Comment by jaubourg** [comment]
So, in theory, we can't have guests in the evening but at the Station... but I'll see if I can cook something up there. If it fails, we'll try and find some place else.

**Comment by jaubourg** [comment]
@lovell got my last mail?

**Comment by lovell** [comment]
Le plan est de rencontrer dans le pub [The Lions](http://www.thelionsparis.fr/), 153 Rue du Chevaleret, près de la *Station F* et métro Chevaleret, à partir de 18h ce mercredi. Je me réjouis de vous voir tous là.

/

The plan is to meet in [The Lions](http://www.thelionsparis.fr/) pub, 153 Rue du Chevaleret, near to *Station F* and Chevaleret métro, from about 6pm onwards this Wednesday. I look forward to seeing you all there.

**Comment by lovell** [comment]
I'm in Paris now and will at Station F for around 17h then at The Lions from 17:30h onwards, a little earlier than expected. See you all soon.

**Comment by lovell** [comment]
C'était super de vous rencontrer tous hier, merci d'être venus!

**Comment by jaubourg** [comment]
Likewise! Please please please, let me know when you're back in Paris :)

**Comment by florentb** [comment]
Now you have to publish your Raving Rabbids picture ;-)
