### ISSUE TITLE
Meet-up: London, 21st March 2018, 6:30pm at The Porcupine, near Leicester Square

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#1104]
Based partly on how well the planned [Paris meet-up](https://github.com/lovell/sharp/issues/1103) next month goes, I'm planning some form of London equivalent for the many UK-based users of sharp and libvips.

This will be an informal gathering to meet other users, ask questions, get advice and perhaps learn more about how you can contribute.

I expect it to take place on a Wed or Thurs evening mid to late March in central London, most likely in a relatively quiet pub.

If you're available and would like to meet up, subscribe to this "issue", add a comment or send me [an e-mail](https://github.com/lovell/sharp/blob/da5deb81776fba12cc99f08d2fc364f55a2a7f0b/package.json#L5) and we can sort something out.

**Comment by jcupitt** [comment]
Hi Lovell, sure, I'd enjoy a night out. I owe you quite a few beers!

**Comment by kmartinez** [comment]
Hi - I will try to make it too!

**Comment by jcupitt** [comment]
Shall I make a linked issue on the libvips tracker too? It might raise awareness.

**Comment by lovell** [comment]
@jcupitt That'd be great, thank you.

Any preference on the date? 21st, 22nd, 28th and 29th are all possibilities.

**Comment by jcupitt** [comment]
Yes, I can do any of those. I'll make a linked issue.

**Comment by kmartinez** [comment]
I can only make 21st and 22nd

**Comment by tomgallagher** [comment]
Only a user but I'd be interested to come along

**Comment by kmartinez** [comment]
no problem Tom! the more the better ;-)

**Comment by jcupitt** [comment]
In case you've not met @kmartinez, he was one of the original vips authors way back in the 1990s. He's now a prof at Southampton and uses libvips for some of his research.

**Comment by kmartinez** [comment]
21st please if possible...

**Comment by lovell** [comment]
Wednesday 21st is good for me. Shall we say from about 6pm onwards?

**Comment by kmartinez** [comment]
Super!

**Comment by jcupitt** [comment]
21st is good for me too. 

I'm rather out of the pub scene sadly :( Do you have any good ideas, Lovell? Kirk and I met at the Round Table by Leicester Square last time, but only because of familiarity. It's quiet and horrible.

**Comment by tomgallagher** [comment]
I'm still intending to come - anywhere central good for me.

**Comment by lovell** [comment]
@kmartinez Are you heading back to Southampton afterwards? If so, somewhere near Waterloo would make sense as you've got the furthest to travel. The Kings Arms on Roupell Street is excellent but can get a bit busy so unsure it meets the "quiet" criteria.

**Comment by jpadfield** [comment]
Really sad I will not be able to make this, hope it goes well

**Comment by Jondeen** [comment]
Incidently I'll actually be in London this week, and would gladly pop by to say hi and grab a quick beer if I'm not imposing!

**Comment by lovell** [comment]
@Jondeen Are you in London for QCon? I'm not attending but might be meeting up with some people that are, possibly on Wednesday evening. Drop me an [email](https://github.com/lovell/sharp/blob/master/package.json#L5) or [DM](https://twitter.com/lovell) if you're interested.

**Comment by rexxars** [comment]
I might also be in London around this time - if I am, I'd love to stop by and have a chat! Let me know if you come up with a more specific time and place :)

**Comment by anne23** [comment]
This is actually very relevant to current work interests, will definitely try to come.

**Comment by tomgallagher** [comment]
Is this still happening? If so, what's the location?

**Comment by kmartinez** [comment]
yes it is - we're just waiting for confirmation of the venue - central somewhere

**Comment by jcupitt** [comment]
I had a 'mo so I've booked a table at The Porcupine from 6:30pm on Wednesday 21st March:

https://www.nicholsonspubs.co.uk/restaurants/london/theporcupineleicestersquarelondon

Under the code name "john". The table's for 8, but I'm sure more/fewer is no problem, so all are very welcome.

**Comment by Jondeen** [comment]
I had a slight cognitive fumble and thought it was this Thursday! I'm afraid I won't be able to join you guys after all. My apologies, I do hope I'll get the chance to meet you all at a later occasion!

**Comment by anne23** [comment]
Sorry, not going to make it in the end, got caught up with (non-image-related) work

**Comment by lovell** [comment]
We're upstairs in The Porcupine.

**Comment by lovell** [comment]
Great to see you yesterday, thanks for coming along! Thank you also to the anonymous sponsor for the food and drinks.

For those who couldn't make it this time, we'll do another event in London later in the year. I'm usually in central London at least a couple of times a week so drop me an [e-mail](https://github.com/lovell/sharp/blob/master/package.json#L5) if you're in town and otherwise at a loose end.

**Comment by kmartinez** [comment]
Yes it was good to meet up!
If there was sufficient interest we could do a short hackathon-type event in London beforehand - I'm sure I could find a room in the University somewhere...

**Comment by tomgallagher** [comment]
Great to learn a bit about libvips and sharp, thanks for organising.

**Comment by jcupitt** [comment]
That webgl game: https://github.com/jcupitt/argh-steroids-webgl if your daughter needs a programming project.

**Comment by tomgallagher** [comment]
Is there another one of these planned? I'd like to catch up and ask some questions.

**Comment by lovell** [comment]
@tomgallagher There's nothing planned in London right now but we should definitely organise another gathering soon, perhaps early in the new year. Feel free to open a new issue with any question(s).

**Comment by tomgallagher** [comment]
@lovell @jcupitt That sounds good. I don't really have any specific Sharp questions but I was wondering how easy it was to extract in JS to extract image file type and dimensions from incoming chunks of an http request? Maybe this is better brought up elsewhere...

**Comment by lovell** [comment]
Please see https://github.com/libvips/libvips/issues/1222 for details of the March 2019 London meetup.
