### ISSUE TITLE
Using Sharp on Workspaces with virtual CPUs

### ISSUE THREAD

**Issue by tomgallagher** [lovell/sharp#1106]
I'm running Sharp on a Cloud9 workspace and on a hobby server on Heroku.

In both of these cases, you share a machine with a number of other users.

When I try this:
```
const numCPUs = require("os").cpus().length;
debug(`This Workpace / Dyno is reporting ${numCPUs} CPUs`);
```
it reports that 8 CPUs are available, which is clearly not right in terms of the virtual CPUs.

I read that Sharp assesses the number of CPUs available and divides the jobs accordingly.

How does this work in a shared environment?

**Comment by lovell** [comment]
Hello, did you see http://sharp.pixelplumbing.com/en/stable/api-utility/#concurrency ?

**Comment by tomgallagher** [comment]
Yes, I'm just experimenting with that at the moment.

I was just curious how the disconnect between actual CPUs (if you use similar method to the above) and vCPUs would manifest in a shared space. I'm seeing heavy usage of swap memory. The mem usage stats of Sharp look within bounds, but something's not right.

**Comment by tomgallagher** [comment]
Thanks for the pointers.
