### ISSUE TITLE
vips_image_new_from_image: symbol not found

### ISSUE THREAD

**Issue by digithunz** [lovell/sharp#1109]
I recently got  `/usr/app/node_modules/sharp/build/Release/sharp.node: vips_image_new_from_image: symbol not found`
on a `node:8-alpine` docker image
We used v0.18.4 in package.lock
```
package.json
 "sharp": "^0.18.4", 
package.lock
 "sharp": {
      "version": "0.18.4",
      "resolved": "https://registry.npmjs.org/sharp/-/sharp-0.18.4.tgz",
      "integrity": "sha1-/jKcDwaJbCiqJDdt8f/wKuV/LTQ=",
      "requires": {
        "caw": "2.0.1",
        "color": "2.0.0",
        "detect-libc": "0.2.0",
        "nan": "2.6.2",
        "semver": "5.4.1",
        "simple-get": "2.7.0",
        "tar": "3.2.1"
      }
    },
```

We used `apk add` in our Dockerfile
`RUN apk add make gcc g++ python vips-dev fftw-dev --no-cache --repository https://dl-3.alpinelinux.org/alpine/edge/testing/ && \
`
For some reason the vips lib we loaded from `https://dl-3.alpinelinux.org/..` during that time on 30th January was giving us the old version (v8.5.0) causing this issue, whereas vips_image_new_from_image is not present.

We did a temporary fix to our docker file
`RUN apk add vips-dev=8.6.1-r0 fftw-dev --update-cache --repository https://dl-3.alpinelinux.org/alpine/edge/testing/
`
At this point we did not get error anymore. I am not sure what caused this in the first place.

**Comment by lovell** [comment]
[vips_image_new_from_image](https://github.com/jcupitt/libvips/blob/v8.6.0/ChangeLog#L3) was added in libvips v8.6.0. It looks like sharp was compiled against v8.6.x but at runtime v8.5.x was provided.
