### ISSUE TITLE
PNG image larger after processing (was: How to optimize image?)

### ISSUE THREAD

**Issue by rightaway** [lovell/sharp#1110]
I have an image that gets cropped in the browser on the client-side before getting uploaded to the server as a png blob. However, the file is almost 100kb, which seems like a lot because it's just a small 350x200 thumbnail. Is there any way for sharp to optimize the image somehow, maybe by converting it to another type or whatever? I'd like to keep it the same dimensions, just have it be smaller if possible.

One strange thing, the file gets uploaded at about 95kb, but if I do sharp's `resize(350, 200)` on it just to see what would happen (so resize it to the same size), the resulting file that gets saved to disk is actually about 5-10kb higher. How could that be?

**Comment by lovell** [comment]
Hello, did you see #478, #600 and #1017, which all relate to the same question as to why a PNG file might be larger after processing.
