### ISSUE TITLE
[resolved] How to use a mask image ?

### ISSUE THREAD

**Issue by Felwin** [lovell/sharp#1113]
Hi,

I have an image that I successfully resized and croped (I mean extracted) and I would like to add a mask on it.
What I mean is that I would like to extract any color channel of the mask (this is quite easy `extractChannel('red')` ) and make that channel the alpha channel of the first image. 
Of course both images are the same size.

Hope you can help me out

**Comment by lovell** [comment]
Hello, did you see [joinChannel](http://sharp.pixelplumbing.com/en/stable/api-channel/#joinchannel)?

**Comment by Felwin** [comment]
Indeed, but I didn't figure it out how to make the red channel of image B being the alpha channel of image A.
Please forgive me if I am missing some obvious point here.

**Comment by lovell** [comment]
Of the top of my head, something like the following may work (untested):
```javascript
sharp(rgbImageB)
  .extractChannel('red')
  .toBuffer()
  .then(alpha -> {
    return sharp(rgbImageA)
      .joinChannel(alpha)
      .toBuffer();
  })
  .then(result => { ... });
```
Perhaps one of the examples from the unit tests will help? https://github.com/lovell/sharp/blob/master/test/unit/joinChannel.js

**Comment by Felwin** [comment]
Thank you for your help, it works fine !

I didn't understood joinChannel would only impact the alpha channel.

**Comment by LambdaFalcon** [comment]
This seems to work with some images and not work with others.
I have an sRGB image that just contains grayscale data that I want to use as the alpha channel of another image.

This is the code I'm using:
```javascript
sharp('mask.png')
        .extractChannel('red') // also B or G would work
        .toBuffer()
        .then((maskBuffer) => {
            sharp('image.png')
                .ensureAlpha()
                .joinChannel(maskBuffer)
                .toFile('output.png'); 
        });
```

And these are the two input images; the output image has the alpha channel, but it is fully opaque.
![image.png](https://user-images.githubusercontent.com/16280355/62135654-e1134400-b2e2-11e9-903b-10a4aa96ccc3.png)
![mask.png](https://user-images.githubusercontent.com/16280355/62135655-e1134400-b2e2-11e9-94e8-a8407b6bff18.png)
