### ISSUE TITLE
Adobe RGB 1998 Color Profile Retention?

### ISSUE THREAD

**Issue by hamiltondfp** [lovell/sharp#1114]
I am converting an image that is using Adobe RGB (1998) as the color profile. After the conversion, the new image's color profile is sRGB.

After scouring the issues for this library, and looking at libvips, I am currently under the impression that Adobe RGB is not a supported ICC (because it's not supported in libvips yet?), and because the transformations are done in the sRGB space, that is the profile that is retained instead.

Could you please confirm or clarify? Thank you.

**Comment by lovell** [comment]
Hello, if you didn't see it, #218 is the future possible feature that will allow this.

**Comment by hamiltondfp** [comment]
Yes, thanks! That's what I based my assumption on. 

Just for the sake of having a thorough understanding: #218 seems to be about converting from one colorspace to another. 

The issue I am having is that my image starts as Adobe RGB (1998) and is then sRGB after the transformations.

This is because there is no support for Adobe RGB (1998), right?

Thanks

**Comment by lovell** [comment]
> "the current behaviour is to always convert images to device-independent, non-linear sRGB colour space" https://github.com/lovell/sharp/issues/218#issuecomment-101414941

I've updated the title of #218 as it had become confusing. The following two comments best reflect my thoughts on the possible API.

https://github.com/lovell/sharp/issues/218#issuecomment-244566477
https://github.com/lovell/sharp/issues/218#issuecomment-257555145

In summary, it will provide what you're looking for so perhaps subscribe to it for updates.
