### ISSUE TITLE
Question: tiling

### ISSUE THREAD

**Issue by BiancoA** [lovell/sharp#1115]
I would like to change the ordering of the saved tiles. 

Using the "google" layout the tiles are stored following rows. For example on level 2, folder 0 contains files 0.jpg, 1.jpg, 2.jpg, 3.jpg that are on the same row on the starting image. I would like them to be extracted from a column.

This could be achieved (I think) by two 90 degrees rotations: a 90 degree rotation, tiling and than -90 degrees to each tile. Looking at http://jcupitt.github.io/libvips/API/current/Making-image-pyramids.md.html I saw that libvisp implements a --angle option for the tiling, could this be implemented in sharp? 

I could contribute with code myself if someone could point me to the part of the code where the interface with libvisp and tiling take place.

**Comment by lovell** [comment]
Hello, a Pull Request to expose the `angle` parameter of libvips' `dzsave` operation would be most welcome if you think it will help in this scenario, thank you.

PR #402 to expose the related `container` parameter should provide some initial guidance.

**Comment by lovell** [comment]
Added via #1121, thank you.

**Comment by lovell** [comment]
v0.19.1 now available, thanks for the PR.
