### ISSUE TITLE
Question: Quickly get a pixel color?

### ISSUE THREAD

**Issue by sam0x17** [lovell/sharp#1116]
What is the best way to quickly get the RGB value of a particular pixel? Is this possible using sharp? I've looked through the docs but don't see anything about this.

In particular, I'd like to avoid wasting large amounts of memory, as I really only need to sample 10 or so random pixel locations for my use-case.

**Comment by lovell** [comment]
Hello, did you see #934?

**Comment by sam0x17** [comment]
@lovell I did not -- thanks!
