### ISSUE TITLE
odd extract + resize behavior when resize width is same as extract width

### ISSUE THREAD

**Issue by kapouer** [lovell/sharp#1119]
Hi,
using sharp 0.19 with vips 8.6.1, when i'm doing
```
pipeline.extract({ left: 797, top: 0, width: 701, height: 2835 }).resize(722, 964)
```
the result is as expected.
However, when doing:
```
pipeline.extract({ left: 797, top: 0, width: 701, height: 2835 }).resize(701, 936)
```
the result is completely different. The image is very cropped and i'm not sure it is resized.
Than can't be right ?

**Comment by kapouer** [comment]
I also tried with vips 8.7.0 in case, same result.

**Comment by lovell** [comment]
Hello, are you able to provide a sample input image (or at least the dimensions of the input)?

**Comment by kapouer** [comment]
![Uploading piercan_3634_2-785ebc95.png…](sample image)

**Comment by lovell** [comment]
Thanks for the input image. Running the following code:
```javascript
const input = '36021532-63c9e970-0d86-11e8-8132-de2a34b03636.png';

sharp(input).extract({ left: 797, top: 0, width: 701, height: 2835 }).resize(722, 964).toFile('1.png', console.log);
sharp(input).extract({ left: 797, top: 0, width: 701, height: 2835 }).resize(701, 936).toFile('2.png', console.log);
```
...produces the output:
```sh
null { format: 'png',
  width: 701,
  height: 936,
  channels: 4,
  premultiplied: false,
  size: 444917 } null
null { format: 'png',
  width: 722,
  height: 964,
  channels: 4,
  premultiplied: true,
  size: 523621 } null
```
...and the images:
![1](https://user-images.githubusercontent.com/210965/36395207-e8a00fc2-15af-11e8-9c52-b5744eddfa79.png)
![2](https://user-images.githubusercontent.com/210965/36395208-e8c71716-15af-11e8-84b0-8559b05ef1b4.png)

Could there be logic missing from the original code sample, perhaps something modifying `pipeline`?

**Comment by kapouer** [comment]
It was https://github.com/kapouer/sharpie/commit/17fa21f497e385ce7993ef82cb556407811ee2d2.
Closing.
