### ISSUE TITLE
Error: /srv/api/node_modules/sharp/build/Release/../../vendor/lib/libvips-cpp.so.42: file too short

### ISSUE THREAD

**Issue by lucasbraum** [lovell/sharp#1122]
I am getting the following error when starting my nodejs application on the AWS server:
`Error: /srv/api/node_modules/sharp/build/Release/../../vendor/lib/libvips-cpp.so.42: file too short`

The npm install is working fine and it is also working on my local environment: macOS High Sierra.

On the server side, I am using a docker image based on ubuntu.

**Comment by lovell** [comment]
Hello, it sounds like that file has become truncated or otherwise corrupt. Has a large enough filesystem been allocated? What does running `ls -al /srv/api/node_modules/sharp/vendor/lib` display?

**Comment by lucasbraum** [comment]
So I managed to get it working by entering on the container after I deployed it to my amazon server and deleting the node_modules folder and running npm install again. For some reason it worked but I still have to figure it out how to make it work with my current build/deploy process.

Issue [637](https://github.com/lovell/sharp/issues/637) gave me a way to go.

**Comment by lovell** [comment]
Thanks for the update. `npm install` / `npm rebuild` has to occur on the runtime platform when there are native modules within `node_modules`. Good luck!

**Comment by MasterJames** [comment]
So many threads about all sorts of related problems. I discovered what is causing all of them potentially.
I use a VirtualBox VM of Ubuntu but I've mounted thew VM Hosts FileSystem a Windows 8.1 box via the mount command from a NetworkShare folder.
It does not allow symbolic links.
Only when I copied the npm project folder to the root (Not mounted FS) did npm rebuild solve the endless problems with the sharp dependency not building.
When I tried to copy the working one back to the mount point it reports that symbolic links can't be created. All the help I've found says you can override with a flag in Windows but this is a Share internal to the VM not via the NFS 'mount'. I'm still looking for a solution other then leaving real code buried in a VM's VDI (not cool).
Normally I found ways around via npm flags like --unsafe-perm --no-bin-links but for this sharp building .o for numjs over an NFS mount it seems impossible.
