### ISSUE TITLE
SVG position rendered incorrectly

### ISSUE THREAD

**Issue by bmurphy-affirma** [lovell/sharp#1125]
With this SVG input,

`<svg>
    <g>
        <rect x="79" y="15" width="170" height="25" style="fill:ivory;"></rect>
    </g>
</svg>`

The output looks like this,

![image](https://user-images.githubusercontent.com/23197949/36128543-c9b9030e-1017-11e8-9d49-e72b08179955.png)

The output doesn't seem to account for the x and y positions and ends up cutoff.

**Comment by lovell** [comment]
Hello, you'll need to add specific dimension attributes to the `<svg>` element, either both a `width` and `height` or a `viewBox`. Without these the underlying librsvg library is having to guess the desired canvas size.

```javascript
const svg = Buffer.from('<svg width="249" height="40"> <g> <rect x="79" y="15" width="170" height="25" style="fill:ivory;"></rect> </g> </svg>');
sharp(svg).toFile('out.png', console.log);
```

```
null { format: 'png',
  width: 249,
  height: 40,
  channels: 4,
  premultiplied: false,
  size: 209 } null
```

![](https://user-images.githubusercontent.com/210965/36199800-85b7fdf2-1172-11e8-89d7-0e40b918e1d7.png)

**Comment by lovell** [comment]
Hope this helped, please feel free to re-open with more details if required.

**Comment by bmurphy-affirma** [comment]
Setting the width and height properties did fix it. However, it did not work if just viewBox was set. Thanks!
