### ISSUE TITLE
"EPERM: operation not permitted, unlink '...\\services\\node_modules\\sharp\\build\\Release\\libcroco-0.6-3.dll'".

### ISSUE THREAD

**Issue by knoxcard** [lovell/sharp#1126]
"EPERM: operation not permitted, unlink '...\\services\\node_modules\\sharp\\build\\Release\\libcroco-0.6-3.dll'"

Getting this error when I execute **yarn upgrade** in **Windows 10**

**yarn version**: 1.4.1-20180119.1607
**node version**: 9.5.0
**OS**: Windows 10

**Comment by lovell** [comment]
Hello, this is very likely to be a temporary local filesystem permissions problem.

**Comment by knoxcard** [comment]
How do I fix that in Windows?  Do I have run my console program (ConEmu) in Administrative mode?

**Comment by lovell** [comment]
This looks very much like https://github.com/yarnpkg/yarn/issues/2685 (found via a web search for "yarn eperm unlink") so I suggest you help with that issue.

**Comment by cmcWebCode40** [comment]
m
