### ISSUE TITLE
basic function cutoffs the image resized on both sides

### ISSUE THREAD

**Issue by lesterjanpearson** [lovell/sharp#1127]
```
sharp(file3)
	.resize(400, 280)
	.toFile(file3x, function(err) {
	// output.jpg is a 200 pixels wide and 200 pixels high image
	// containing a scaled and cropped version of input.jpg
	});
```

is there another extra setting I need to add?

**Comment by lovell** [comment]
Hello, did you see http://sharp.pixelplumbing.com/en/stable/api-resize/ which provides details on the various resize options available and default behaviour?

**Comment by ryanvanderpol** [comment]
@lovell the documentation you linked says the following:

> By default, the resized image is centre cropped to the exact size specified.

But I don't see any way to change the default.  I'd like it to cut off from one side or the other, not the center.

**Comment by lovell** [comment]
@ryanvanderpol Did you see the various `gravity` options of [crop](http://sharp.pixelplumbing.com/en/stable/api-resize/#crop)?

**Comment by ryanvanderpol** [comment]
@lovell does `crop` chain off of the parameters in `resize`?  If so, this is probably the most confusing API I've ever seen.

**Comment by ryanvanderpol** [comment]
Apparently it does.  It seems to me that the parameters of `crop` directly affect how `resize` works so supplying the `gravity` as a parameter outside of `resize` is absolutely not intuitive and I would have never figured that out on my own.

For anyone else who is struggling with this, you can do the following:

```
	.sharp('image.png')
	.resize(100, 100)
	.crop(sharp.gravity.west)
	.toBuffer()
        .then(buffer => ...);
```

and your image will be cropped to 100x100 starting from left/middle.

**Comment by lovell** [comment]
@ryanvanderpol "probably the most confusing API I've ever seen" made me laugh. I've (finally) written a brief API history and a proposal at #1135 you might be interested in.

**Comment by lovell** [comment]
@ryanvanderpol Processing starts on the input image when one of `toFile()`, `toBuffer()` or `pipe()` are called to access the output image. This means a second call to `resize()` on the same pipeline before processing begins will update the internal state, replacing the parameters from the first call.

**Comment by lovell** [comment]
@lesterjanpearson Hope this helped, please feel free to re-open with more details if required.
