### ISSUE TITLE
Mask image 

### ISSUE THREAD

**Issue by e-tip** [lovell/sharp#1129]
Hi, 
sorry for the noob quertion but i've looked around and i didn't found what i'm looking for.
i want to mask an A image with a b image transforming  image b's pixels to transparent pixel and leaving imageb's white pixels as is...
in this Case A+C = C where C is an image with the same size of A and B but with alpha where not white

![Example Image](https://preview.ibb.co/eB4jvn/example.png)

Thanks in advance and sorry for my english

**Comment by lovell** [comment]
Hello, did you see the `cutout` option of [overlayWith](http://sharp.pixelplumbing.com/en/stable/api-composite/#overlaywith)?

The third example in the [README](https://github.com/lovell/sharp/blob/master/README.md) uses this.

**Comment by e-tip** [comment]
Hi, i tryed with a wrong png and it didn't worked, so i've posted the question. Using another png file it worked like a charm. 
`var mask = 'mask_test_2.png';
sharp('mask_test_1.png').overlayWith(mask,{
    cutout : true
}).toFile('prova.png');`
