### ISSUE TITLE
How to enable PDF Support for AWS Lambda

### ISSUE THREAD

**Issue by codecitizen** [lovell/sharp#1130]
Hi,

I was looking through the documentation and closed issues, but couldn't quite find a answer to my question:

I want to use sharp to convert PDF files to JPEGs on AWS Lambda. I managed to install the AWS lambda package following the instructions from the documentation page. But there seems to be no PDF support (looking at the output of `sharp.format`).

So do I need to compile libvips for Amazon Linux with PDF support myself and include in the ZIP Archive, which I upload to AWS Lambda? And how do I configure Sharp to use the included libvips installation? 

Thanks in advance for your answers!

**Comment by lovell** [comment]
> do I need to compile libvips for Amazon Linux with PDF support myself

Yes

> how do I configure Sharp to use the included libvips installation

sharp looks for a globally-installed libvips at `npm install` time. You'll need to ensure the file system location of all the shared libraries is the same at runtime as well. This is unlikely to be a simple task and StackOverflow may be a more appropriate place to get further help, good luck!

**Comment by lovell** [comment]
Glad this helped, please feel free to re-open with more details later.

**Comment by j** [comment]
@codecitizen did you end up doing this?

**Comment by johndevedu** [comment]
@lovell thank you for your great work. Like OP I already have sharp working in Lambda using Lambda Layers, but looking to add PDF support.

Similar to how sharp supports local [custom prebuilt libraries](https://sharp.pixelplumbing.com/install#custom-libvips) for sharp using `sharp_local_prebuilds` or `npm_config_sharp_local_prebuilds` npm option/env variable, does it support option/variable for libvips local prebuilds? I see there is support for custom URL but I don't see local prebuilds option. I'm looking for something like `libvips_local_prebuilds` or `npm_config_libvips_local_prebuilds`.

In addition, you mentioned above that the location of libvips needs to be in same location for both installation and runtime. Is it possible to add an option to specify the runtime location? If I can configure sharp to use a setting like [.executablePath('/opt/bin/libvips')](https://stackoverflow.com/questions/58021618/how-files-in-a-lambda-layer-will-be-copied-to-the-opt-bin-directory), I think I can get this to work.
