### ISSUE TITLE
[Suggestion] Handier versions of `.raw()`: `.opacity()`, `.hsl()`, `.hsv()`, `.rgb()`, and et cetera.

### ISSUE THREAD

**Issue by wlzla000** [lovell/sharp#1132]
There are plenty of colourspaces with a various number of channels. **[Obtaining desired information with `.raw()`](https://github.com/lovell/sharp/issues/934) is sometimes quite troublesome**, especially if the input image's colourspace is not certain one. For instance, in order to examine an image to know if it has an opaque red pixel, you would have to check whether it has an alpha channel or not, whether it is grayscale, RGB, or CMYK, and deal with all the cases.

 I suggest handier versions of `.raw()` for accessing image information: `.opacity()`, `.hsl()`, `.hsv()`, `.rgb()`, and et cetera. They give what their names imply, no matter what the image's colourspace is. They would be able to be implemented with [`vips_colourspace()`](https://jcupitt.github.io/libvips/API/current/libvips-colour.html#vips-colourspace).

 I'd appreciate hearing your opinion on this.

**Comment by lovell** [comment]
Hello, did you see [toColourspace](http://sharp.pixelplumbing.com/en/stable/api-colour/#tocolourspace), which should work with raw pixel output?

**Comment by wlzla000** [comment]
Oh, why couldn't I notice it, I'm sorry. Thank you so much!

```javascript
const data = await Sharp(......).toColourspace("hsl").raw().toBuffer();
```
