### ISSUE TITLE
smartcrop: bad extract area

### ISSUE THREAD

**Issue by pieh** [lovell/sharp#1134]
In very specific case resizing with cropping set to `sharp.strategy.attention` or `sharp.strategy.entropy` will result with error `smartcrop: bad extract area` 

Repository to reproduce - https://github.com/pieh/sharp-smartcrop-bad-extract-area-repro

This happens when `width` is set to `1110` and `height` is unspecified using image from above repository (it is 1600 x 1200)

In readme of repository I placed more outputs where it works fine:
- with crop set to `sharp.gravity.center`
- with slightly higher and lower widths (`1120` and `1100` respectively)
- with specified height (both calculated using source image aspect ratio and full image height)

This was originally reported in https://github.com/gatsbyjs/gatsby/issues/4142 (just to keep paper trail - reproduction repository should be enough)

**Comment by lovell** [comment]
Hi Michal, thank you for this detailed report and accompanying test repository.

The "attention" and "entropy" crop strategies rely on the `resize()` operation being provided with both a width and height but this isn't checked or enforced until after passing control to libvips.

I think the best fix here is for sharp to ignore the strategy choice should either width or height be missing as that situation will result in no crop taking place anyway. I'll take a look at this.

**Comment by pieh** [comment]
When resizing with just width (or height) crop strategy/gravity shouldn't have any effect - it's just scaling without cropping, right? What I find weird is that it works fine (doesn't throw error) with some width (f.e. 1120px or 1100px in my example) and not with others (1110px).

I will add conditional check to not use `attention` or `entropy` crop strategy in gatsby for now if it's just scaling and not cropping.

**Comment by lovell** [comment]
This error occurs when cumulative rounding during the resize operation occasionally produces an image 1px smaller along one edge than the expected target dimensions. The bug here is that there's no conditional guard to prevent a "smartcrop" operation taking place when the image is already small enough.

I've added your example dimensions as a new unit test locally, which currently fails, and expect to push the fix that will get this test to pass within the next 24 hours. Thanks for reporting!

**Comment by lovell** [comment]
v0.19.1 now available with the fix for this.

**Comment by ralrom** [comment]
Hi, I am getting the same error with a 1024x1034px  image on version 0.20.0. I am also using gatsbyjs

I have a project with quite a few images (about 100) and this is the only image that's causing problems:

![stmichael-church](https://user-images.githubusercontent.com/7953838/37238054-d19533f8-23eb-11e8-8bc7-f95f540bf8f2.jpg)

**Comment by lovell** [comment]
@ralrom Please can you open a new issue with a minimal code sample (using only sharp) that exhibits this behaviour.
