### ISSUE TITLE
Throw error on problem

### ISSUE THREAD

**Issue by Redsandro** [lovell/sharp#1136]
Some problematic files (e.g. a `.png` file that is accidentally a `.html` file because a download didn't 404 but 302 to html) cause `sharp` to hang indefinitely.

I think this should throw an Error in stead.

```javascript
try {
	sharp(src, {failOnError: true})
		.resize(width, height)
		.background(bg)
		.embed()
		.toFile(dest, cb)
}
catch (err) {
	// Never fires
	console.error(err.stack)
	cb()
}
```

**Comment by lovell** [comment]
Hello, `toFile()` is asynchronous and any error during image processing will be passed as the first parameter to the provided callback function, `cb` in your example.

If you want try/catch behaviour you'll need to use async/await.

```javascript
try {
	await sharp(src, {failOnError: true})
		.resize(width, height)
		.background(bg)
		.embed()
		.toFile(dest)
}
catch (err) {
	console.error(err.stack)
}
```

**Comment by Redsandro** [comment]
Great, thank you! :+1:
