### ISSUE TITLE
npm install doesn't work the first time

### ISSUE THREAD

**Issue by thelonious** [lovell/sharp#114]
We're seeing an issue on OS X Yosemite (and on Heroku) where when we run `npm install`, sharp doesn't build successfully. To resolve this issue, we have to run `npm install sharp` manually. This is happening with 0.6.2 and 0.7.1. It looks like node-gyp doesn't run in the first case, but does in the second. We're using NPM 2.1.2 and 2.1.4, I believe.

**Comment by lovell** [comment]
As there have been no more reports/update of this problem, I'm closing this item. Please feel free to re-open if it occurs again or if more information is available.
