### ISSUE TITLE
Crop to specific dimensions rather than with gravity

### ISSUE THREAD

**Issue by elliotthill** [lovell/sharp#1140]
Hi,

We want to be able to crop images with specific bounds like(Left: 0 Right: 2996 Top: 3000 Bottom: 503)

Is there any way to do this?

**Comment by lovell** [comment]
Hello, did you see [extract](http://sharp.pixelplumbing.com/en/stable/api-operation/#extract)?

**Comment by elliotthill** [comment]
Ah thank you - I was looking under 'Resizing images' section.
