### ISSUE TITLE
Unwanted output to stdout

### ISSUE THREAD

**Issue by josenobile** [lovell/sharp#1144]
I got this in STDOUT:
VIPS-INFO: 8 point mask
VIPS-INFO: reducev sequential line cache
VIPS-INFO: 7 point mask
Can it be removed?

**Comment by josenobile** [comment]
Maybe you are taking g_info to stdout, in some way.

**Comment by lovell** [comment]
Are the `G_MESSAGES_DEBUG` or `NODE_DEBUG` environment variables set?

**Comment by josenobile** [comment]
I tried with
process.env.VIPS_INFO = '0';
process.env.G_MESSAGES_DEBUG = '0';
process.env.NODE_DEBUG = '0';

The output still.

**Comment by jalamprea** [comment]
Disable debug messages from glib using:
process.env.G_MESSAGES_DEBUG = 'none';

**Comment by lovell** [comment]
Which version of sharp is this? If not the latest, does the latest version exhibit this problem?

**Comment by josenobile** [comment]
I solved by using @jalamprea fix. The env var needs to be set after including the library as Julian says. That's mean, the library (sharp library I guess) is enabling the debug inside them.

**Comment by lovell** [comment]
sharp does not set any environment variables.

I strongly recommend you check for other places that could be setting environment variables. Overwriting environment variables that should not be set is dealing with the effect rather than the cause and might be masking other problems.

**Comment by josenobile** [comment]
Analyze this:

Set the env var and include the sharp library: the debug output happen
Set the env var after include the sharp library: the debug output does not happen.

Ther places do you refer the [vips ](https://github.com/jcupitt/libvips) library?

**Comment by jalamprea** [comment]
The issue is with Sharp 0.18.4
That is the version included in the latest version of the lqip project [https://github.com/zouhir/lqip](https://github.com/zouhir/lqip)
