### ISSUE TITLE
Sharp how to get the best results

### ISSUE THREAD

**Issue by littlestar1998** [lovell/sharp#1146]
Sharp how to get the best results and the smallest picture size?

const Sharp = require('sharp');
var sharpObj = Sharp("1.jpg")
sharpObj.jpeg()
sharpObj.toFile("2.jpg")

the jpeg default quality is 80 But the picture quality is too bad  if  set  quality 90 The output picture is too large
How to output the best quality picture under the condition that the picture volume is the lowest

**Comment by lovell** [comment]
Hello, please see #836
