### ISSUE TITLE
Mime type wrong when creating an image

### ISSUE THREAD

**Issue by Ezechiele** [lovell/sharp#1152]
Hello, I have the need to concatenate two images to upload a single file with front-back of an ID to Stripe servers. I was able to achieve a concatenation using the following code:

    const path = "document.png";
    var r = await sharp(null, {
        create: {
            width: width,
            height: height,
            channels: 3,
            background: { r: 255, g: 255, b: 255}
        }
    }).png().overlayWith(document1,{top: 0, left: 0}).raw().toBuffer();

    await sharp(r, {raw: {
            width: width,
            height: height,
            channels: 3
    }}).overlayWith(document2,{top: metadata1.height, left: 0}).toFile(path);

But when I try to send the image to Stripe servers the response i get is that "this type of file is not supported, please send a file with mime type mime/jpg or mime/png".
If, however, i try to upload one of the original files everything works as expected.

If somebody has other solutions to achieve merging two images that would be highly appreciated, thank you!

**Comment by lovell** [comment]
Hello, does adding a call to `png()` before `toFile()` work?
```diff
- }}).overlayWith(document2,{top: metadata1.height, left: 0}).toFile(path);
+ }}).overlayWith(document2,{top: metadata1.height, left: 0}).png().toFile(path);
```

**Comment by Ezechiele** [comment]
Unfortunately it doesn't work, I've tried to remove the .png() in the first overlay too but it doesn't work either..

**Comment by Ezechiele** [comment]
It turns out it was my dumb mistake of passing the file path instead of the library, @lovell thank you for your help and this amazing library!
