### ISSUE TITLE
What is the pixel limit of the input image?

### ISSUE THREAD

**Issue by tomas365** [lovell/sharp#1155]
When I use a 3GB image, it throws an error and tells me that the input image exceeds the pixel limit.

**Comment by oliviertassinari** [comment]
https://github.com/lovell/sharp/blob/dbac4b9a634e20351c6014bbfc64401cd3f97042/src/pipeline.cc#L76-L81
https://github.com/lovell/sharp/blob/b154cd0418f40475ac0ffe55e2ba494655a23b37/lib/input.js#L322

**Comment by papandreou** [comment]
See https://github.com/lovell/sharp/issues/115#issuecomment-62873917
