### ISSUE TITLE
Error: The specified procedure could not be found. With canvas.

### ISSUE THREAD

**Issue by SeanSobey** [lovell/sharp#1157]
An issue already raised [here](https://github.com/Automattic/node-canvas/issues/930), but as of `sharp 0.20.0` it seems sharp is now raising the issue.

`npm i canvas`
`npm i sharp`

```json
  "dependencies": {
    "canvas": "^2.0.0-alpha.11",
    "sharp": "^0.20.0"
  }
```

```js
require('canvas');
require('sharp');
```

```
module.js:691
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified procedure could not be found.

\\?\<path>\node_modules\sharp\build\Release\sharp.node
```

Node v9.7.1
Windows 10 x64

**Comment by lovell** [comment]
Hello, the "GTK2" bundle of Gnome-provided dependencies recommended for Windows by `node-canvas` dates from 2010 and will be likely to contain many security vulnerabilities. If you're processing untrusted user input I would strongly recommend these are not used.

https://github.com/Automattic/node-canvas/wiki/Installation---Windows#2-installing-gtk-2

These old versions will conflict with the up-to-date dependencies provided by sharp and libvips.

https://github.com/jcupitt/build-win64/blob/master/8.6/vips.modules
https://github.com/lovell/sharp-libvips/#windows

**Comment by SeanSobey** [comment]
Thanks for your quick response!

Based on your feedback we have removed our usage of `node-canvas` and changed instead for a `puppeteer` based canvas render service. Not the ideal resolution but the best option we think given the situation.

**Comment by lynncyrin** [comment]
For anyone else arriving at this issue, this link doesn't work

> https://github.com/Automattic/node-canvas/wiki/Installation---Windows#2-installing-gtk-2

Ths proper link is this => https://github.com/Automattic/node-canvas/wiki/Installation%3A-Windows#2-installing-gtk-2
