### ISSUE TITLE
PNG file sizes increasing

### ISSUE THREAD

**Issue by Jakobud** [lovell/sharp#1158]
I have a PNG file that is about 11MB. I run it through Sharp:

```
sharp('./my-big-image.png')
    .png({
      compressionLevel: 9,
      progressive: true,
      adaptiveFiltering: true
    })
    .toFile(`./output.png`, (err, info) => {
      if (err) {
        console.error(err)
        return false
      }
      console.log(info)
    })
```

The resulting file is 15MB. If I run this same file through imagemin (pngquant) it drops it down to 3.5MB. Am I misunderstanding something here? Is sharp not supposed to be used for compression but rather to be used only for image manipulation and then you should use a different library for proper compression? I'm new to sharp so perhaps I misunderstood that about it. Or maybe I'm doing something really wrong.

**Comment by lovell** [comment]
Hello, please see #478, #600, #1017 and #1110, which all relate to the same question as to why a PNG file might be larger after processing.

**Comment by aishwarya4shrestha** [comment]
@lovell  is their any way to solve this ?

**Comment by dpkirchner** [comment]
> @lovell is their any way to solve this ?

Seems there isn't, unfortunately. The referenced issues don't provide a solution and it doesn't look like anyone's figured it out (or has figured it out and shared the result). Someone mentioned posterize but that word is only mentioned in that issue and not in the code.

**Comment by lovell** [comment]
Since sharp v0.28.0, libimagequant is included in the prebuilt binaries, which means `palette` PNGs can be generated.

https://sharp.pixelplumbing.com/api-output#png

```js
await sharp('./my-big-image.png')
  .png({ palette: true })
  .toFile(`./output.png`);
```
