### ISSUE TITLE
Feature request median filter

### ISSUE THREAD

**Issue by BiancoA** [lovell/sharp#1159]
Hi,

I would like to have the possibility to apply a median filter to an image, as documented on: https://jcupitt.github.io/libvips/API/8.6/libvips-morphology.html#vips-median .

I can try to provide a PR, any suggestion on how to do it?

**Comment by BiancoA** [comment]
I am working on it following what was done for `blur`

**Comment by lovell** [comment]
That's great, thank you Andrea, let me know if you need any help.

**Comment by lovell** [comment]
v0.20.1 now available, thank you for the PR.
