### ISSUE TITLE
Enhancement: composite with negative values for top and/or left

### ISSUE THREAD

**Issue by seripap** [lovell/sharp#1160]
Hello! 

Is there a reason why negative values are not supported with `top` and `left` from within overlayWith? I am not familiar with how libvips work as well, so feel free to close this if this is something that is specifically not supported.

A use case for this is composing coordinate-based map images (such as a radar image on top of a static base map).

For example, a base map could be cropped like this:

<img width="746" alt="screen shot 2018-03-16 at 9 27 24 am" src="https://user-images.githubusercontent.com/683200/37523097-4d801162-28fc-11e8-9804-70a7cc519c3c.png">

The square outlines for this base map indicates the position of a 256x256 tile image. From this information, we can calculate the pixel position of where tile should go and place them where they belong. So the first tile could be at x:-44,y:-102, second would be x:212,y:-102, and so on.

Please let me know if I missed something from the docs or this isn't something that is supported.

**Comment by zekth** [comment]
I have managed to do something this but needs to calculate top / left from metadata of base image and overlay image. But with this approach i don't use gravity because i'm forced to calculate the coordinates of the overlay.
For example setting an overlay in SouthEast with a margin of 20px. I can share my code if you want.

**Comment by christianflintrup** [comment]
Now that the new composite operation is implemented, is this feature request being considered for implementation? Or is it tricky due to how libvips works?

**Comment by lovell** [comment]
@christianflintrup Always happy to accept a PR, if you're able.

**Comment by ariklevin** [comment]
Hi,

Is there a workaround, until the PR is completed?

10x

**Comment by lovell** [comment]
v0.27.0 is now available, thank you for the PRs to improve this feature!
