### ISSUE TITLE
Feedback required: logo submissions

### ISSUE THREAD

**Issue by Yasujizr** [lovell/sharp#1163]
![sharp](https://user-images.githubusercontent.com/36993664/37572793-75bc5b1e-2b21-11e8-80e7-a0eb5d9c1147.jpg)

Hi, I have studied your work and I think a new design will make you more visible. I designed for you, I hope you like it and you want to use it. If you contact me here or from doganzr@gmail.com I can give you all the formats of the design free. If you want a change please specify. 

![example](https://user-images.githubusercontent.com/36993664/37572796-8391de8a-2b21-11e8-8958-25dfd6ce62e6.jpg)

**Comment by lovell** [comment]
Feedback on whether sharp would be improved with a logo and if so, suggestions for what it could look like, is very welcome.

My only request is that logo submissions are licensed under Creative Commons Attribution-ShareAlike 4.0 International [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) and fonts, if any, are licensed under the SIL Open Font License [OFL](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL_web) or very similar. It would be nice to have variants that could work with both a light and dark background.

@Yasujizr Thank you for your submission, are you able to confirm the licensing terms are applicable to your logo and font selection?

**Comment by Yasujizr** [comment]
Hi, the font is here ( https://fonts.google.com/specimen/Baloo ) license under (http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL_web), and my logo is license under (http://creativecommons.org/licenses/by/4.0) Creative Commons Attribution 4.0 International License

**Comment by Yasujizr** [comment]
Hi,

If you want, I can send you the logo. The black or white backplane is comfortable to use. Available in logos and logotype sizes of 512,196,148,96,72,48 px. If you want another color, you can also let me know.

**Comment by Yasujizr** [comment]
Hi, Lovell

What improvements do I make to using this logotype? If you do not like it, I'd really like to hear if there's another idea.

Thank u.

**Comment by lovell** [comment]
Here are a few colour/background variants of a logo concept that combines the act of resizing with the # sharp musical symbol.

![sharp-logo-ideas](https://user-images.githubusercontent.com/210965/47234339-6e794d80-d3cd-11e8-95ab-3e6eda7a28a4.png)

This logo is licensed under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/).

**Comment by lovell** [comment]
A slight refinement so it looks less like a number/hash/pound symbol and more like a musical sharp symbol.

![](https://user-images.githubusercontent.com/210965/48411491-92645080-e739-11e8-88d2-90dd9f909bc9.png)

**Comment by lovell** [comment]
Added as https://github.com/lovell/sharp/blob/master/docs/image/sharp-logo.svg
