### ISSUE TITLE
Forcing the use of pre-built binaries anyway

### ISSUE THREAD

**Issue by oncletom** [lovell/sharp#1164]
Hello,

I'm glad to discover the existence of pre-built binaries :-)
I'd like to speed up the Continuous Integration build process on a project I'm working on.

Is there any way to use pre-built binaries, regardless of the installed libvips version?

[`node-sass`](https://github.com/sass/node-sass#binary-configuration-parameters) provides a handy config. 

I added 

```
  "nodeSassConfig": {
    "binarySite": "https://github.com/sass/node-sass/releases/download"
  },
```

to my package.json file and it now downloads the pre-built binaries automatically.

Thanks for your help :-)

**Comment by lovell** [comment]
Hello, I think the `SASS_BINARY_SITE` env var is more akin to sharp's [SHARP_DIST_BASE_URL](http://sharp.pixelplumbing.com/en/stable/install/#pre-compiled-libvips-binaries) env var, which can be used to change *where* pre-compiled libvips binaries are downloaded from.

When you say "regardless of the installed libvips version", does this mean there is a globally-installed libvips in your CI environment? If so, are you looking for the ability to ignore the globally-installed version of libvips and instead always use a prebuilt binary?

**Comment by oncletom** [comment]
Yes you're right. SHARP_DIST_BASE_URL is the option I was investigating and realised it did not have the same meaning as per node-sass.

My use case is container-based Travis CI – I can't remove package but only add them.

There is a default version which is pre-installed and I guess it makes the cut because sharp builds using it :-D

So I'm indeed looking to ignore the existing libvips and/or to opt in for a download instead.

**Comment by lovell** [comment]
Thanks for confirming.

Perhaps we could add a new `SHARP_IGNORE_GLOBAL_LIBVIPS` environment variable and check for its presence in [useGlobalLibvips()](https://github.com/lovell/sharp/blob/master/lib/libvips.js#L48)? We should be able to add a unit test for this too.

As always, happy to accept a PR.

**Comment by lovell** [comment]
v0.20.2 now available with this feature, thank you for the PR!
