### ISSUE TITLE
Windows Docker build error with sharp@0.20.1

### ISSUE THREAD

**Issue by manjunathhale1** [lovell/sharp#1167]
For the project I am working on, I am trying to build Docker image using sharp.

npm install sharp
yarn add sharp

Sharp version in package.json "sharp": "^0.20.1"

Dockerfile below..

FROM node:8-alpine
EXPOSE 3000
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
RUN mkdir /app
WORKDIR /app
ADD package.json yarn.lock /app/
RUN yarn --pure-lockfile
ADD . /app
CMD ["yarn", "docker:start"]

I have the latest Docker for windows installed on my machine. I am running this command to build:
docker build -t .

I keep getting the following error during build:

[5/5] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error /app/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments:
Directory: /app/node_modules/sharp
Output:
ERR! sharp Use with musl libc requires manual installation of libvips >= 8.6.1
ERR! sharp Please see http://sharp.pixelplumbing.com/page/install
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | linux | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack at PythonFinder. (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.9.49-moby
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/sharp
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
The command '/bin/sh -c yarn --pure-lockfile' returned a non-zero code: 1

**Comment by lovell** [comment]
Hello, the salient part of the error message you've pasted here is:

> ERR! sharp Use with musl libc requires manual installation of libvips >= 8.6.1
> ERR! sharp Please see http://sharp.pixelplumbing.com/page/install

You're using Alpine so the "Alpine Linux" section of the page linked to in the error message is relevant.

**Comment by manjunathhale1** [comment]
Hi lovell,

Many thanks for the response .. we updated the Dockerfile as suggested (refer below) 

FROM node:8-alpine
EXPOSE 3000
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
RUN mkdir /app
WORKDIR /app
RUN apk add vips-dev fftw-dev --update-cache --repository https://dl-3.alpinelinux.org/alpine/edge/testing/
ADD package.json yarn.lock /app/
RUN yarn --pure-lockfile
ADD . /app

CMD ["yarn", "docker:start"]

We are getting the build error below ... it detects globally installed libvips and attempts to build from source. Is there an option to use prebuild packages rather than building from source? Or, are we missing something here .. please let us know. 


[5/5] Building fresh packages...
error /app/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments:
Directory: /app/node_modules/sharp
Output:
info sharp Detected globally-installed libvips v8.6.1
info sharp Building from source via node-gyp
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | linux | x64
gyp http GET https://nodejs.org/download/release/v8.9.4/node-v8.9.4-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v8.9.4/node-v8.9.4-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v8.9.4/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v8.9.4/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/app/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/8.9.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/8.9.4',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/8.9.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/app/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
/bin/sh: c++filt: not found
/bin/sh: readelf: not found
gyp: Call to 'if readelf -Ws "$(PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --variable libdir vips-cpp)/libvips-cpp.so" | c++filt | grep -qF __cxx11;then echo "1";else echo "0";fi' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.49-moby
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/sharp
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn --pure-lockfile' returned a non-zero code: 1

**Comment by lovell** [comment]
http://sharp.pixelplumbing.com/en/stable/install/#building-from-source

> Building from source requires:
> * C++11 compatible compiler such as gcc 4.8+, clang 3.0+ or MSVC 2013+
> * node-gyp and its dependencies (includes Python)

**Comment by kachkaev** [comment]
@manjunathhale1 I had the same issue when trying to build an alpine image with `"sharp": "^0.20.1"` and this worked for me in the end:

```dockerfile
FROM node:9.10.1-alpine

RUN apk add --no-cache \
    build-base \
 && apk add --no-cache --repository https://dl-3.alpinelinux.org/alpine/edge/testing/ \
    vips-dev \
    fftw-dev

# yarn install etc.
```
