### ISSUE TITLE
Image Resize - Quality Settings

### ISSUE THREAD

**Issue by JasonWolmarans** [lovell/sharp#1170]
Good day, I am trying to resize an image, currently 300x300 pixels down to 100x100...

sharp(bufferResponse)
.resize(100, 100)
.toBuffer((err, data, info) => {
      // handle resized response
});

I am having difficulty finding a setting for "quality" in the API docs which could apply to the above snippet. I need to retain the highest quality possible. Could someone point me in the right direction please?

Appreciate any assistance, Thanks in advance

**Comment by lovell** [comment]
Hello, if you're referring to the "quality" setting for JPEG output, please see the [jpeg](http://sharp.pixelplumbing.com/en/stable/api-output/#jpeg) docs.

**Comment by JasonWolmarans** [comment]
let bufferResponse = Buffer.concat(bufs);
	sharp(bufferResponse)
		.jpeg({ quality: 100, progressive: true })
		.resize(100, 100)
		.toBuffer((err, data, info) => {
			// handle resized response
		});

Issue resolved, thanks
