### ISSUE TITLE
GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

### ISSUE THREAD

**Issue by tommedema** [lovell/sharp#1171]
Steps to reproduce:

1. download this .png image:

![image](https://user-images.githubusercontent.com/331833/38055694-4ef97668-328f-11e8-8e09-d5a1c4a0bcfb.png)

2. run this test with mocha:

_test.js_

```
/* global describe, it */
require('loud-rejection/register')

const sharp = require('sharp')

describe('module', () => {

  it.only('should return a buffer', async () => {
    const editorScreenshot = await fs.readFile(__dirname + '/img.png')

    sharp(editorScreenshot)
      .toBuffer()
      .then((data, info) => { // 
        console.log(data)
      })
      .catch((err) => {
        console.log('sharp error catched')
        console.error(err)
      })
  })
```

it results in:

```

(sharp:19291): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:19291): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:19291): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:19291): GLib-CRITICAL **: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed

(sharp:19291): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed
Segmentation fault: 11
```

Running with node 8.10; also tried with v9. OSX High Sierra 10.13.3

**Comment by lovell** [comment]
Hello, these `g_hash_table_lookup` messages are usually a sign that something else is calling `process.exit` whilst sharp is still asynchronously processing an image.

The `loud-rejection` module depends on `signal-exit` that might be doing this.

Is there some other code not shown here that globally alters `fs.readFile` to return a Promise?

Do you still see this problem after removing some/all of these other dependencies?

**Comment by tommedema** [comment]
Sorry, I left out the `const fs = require('fs-extra')`. Will check when I have time and come back to you, thanks.
