### ISSUE TITLE
Is streaming transformation object reusable?

### ISSUE THREAD

**Issue by swftvsn** [lovell/sharp#1172]
Hi,

I have a service that returns json that contains an array of base64 encoded images. The images are transformed using sharp. Conversion happens like this: 

```ts
const imageTransform = sharp()
  .resize(1080, 1920)
  .max()
  .jpeg( { progressive: false, quality: 100 } )

for (const readStream of streamsFromDisk) {
  const base64Encoder = new b64.Encoder()
  readStream.pipe(imageTransform).pipe(base64Encoder)
  // Pipe to response using streamstream https://www.npmjs.com/package/stream-stream or similar
}
```

Is it advisable to reuse the imageTransform like that, or should I construct new instance for each stream? Example of this here:

```ts
for (const readStream of streamsFromDisk) {
  const imageTransform = sharp()
    .resize(1080, 1920)
    .max()
    .jpeg( { progressive: false, quality: 100 } )
  const base64Encoder = new b64.Encoder()
  readStream.pipe(imageTransform).pipe(base64Encoder)
  // Pipe to response using streamstream https://www.npmjs.com/package/stream-stream or similar
}
```
Which approach is correct?

And thank you for this awesome library!

**Comment by lovell** [comment]
Hello, Streams are async so you have to use the second approach otherwise bad things will happen e.g. randomly-ordered chunks of data from various `streamsFromDisk` piped into a single sharp instance.

This is more a Node Streams thing than a sharp thing. It's the same reason you're creating a new instance of `base64Encoder` inside the for-loop.

**Comment by swftvsn** [comment]
Hi!

Thanks for the explanation! I have a Java background, and there stream handlers can be shared as long as those are stateless ( and therefore thread safe ), hence the question. I'll make sure to always use new instances.

**Comment by lovell** [comment]
I work with Java occasionally and think of its stateless "stream" handlers like map/filter/reduce/sum as pure functions. Perhaps treat Node Streams more like Unix pipes, where a number of stateful processes are combined in an ordered list.

**Comment by ranihorev** [comment]
How can I reuse a sharp object (transformation stream object) that I receive as an input parameter?
