### ISSUE TITLE
Build fails with npm 5.8.0

### ISSUE THREAD

**Issue by benurb** [lovell/sharp#1173]
Hello 👋 

unfortunately I cannot build the sharp native module after an update to npm 5.8.0.

```
error An unexpected error occurred: "/home/user/workspace/project/src/node_modules/sharp: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /home/user/workspace/project/src/node_modules/sharp
Output:
module.js:549
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3".
```

This seems to be caused by https://github.com/npm/npm/issues/20163
I don't know if the issue is on sharp's side or on npm's, but I just wanted to make you aware of that.

Thanks for your great work 👍 
Best regards,
Ben

**Comment by lovell** [comment]
Hello, I agree this appears to be the same problem reported against npm.

sharp v0.20.0+ no longer requires the use of `node-gyp` on most platforms, so if you're able to upgrade that might help.

**Comment by dhruvdutt** [comment]
![image](https://user-images.githubusercontent.com/5961873/38627355-6e51a61e-3dcc-11e8-8ca4-0a11091d16e8.png)

Broken when doing `yarn` or `npm install` on one of this [package.json](https://github.com/appbaseio/reactive-manual/blob/v2/package.json)
