### ISSUE TITLE
use overlayWith based on the clipping path of a jpg

### ISSUE THREAD

**Issue by devicezero** [lovell/sharp#1174]
Hi! 

First of all: thanks for the great work, I enjoy using sharp :)

Is it possible to use an existing clipping path from an image and cut out only the pixels within the path? I know that I could use `overlayWith` to cut out one image based on another, but my use case is a little bit different (e.g. jpgs may have a named clipping path and I want to cut out along this path and convert them into a png with an alpha channel). I think this might be similar to the `-clip-path` option in ImageMagick (http://www.imagemagick.org/script/command-line-options.php#clip-path).

Cheers!

**Comment by lovell** [comment]
Hello, JPEG clipping paths are usually stored as Adobe-specific metadata rather than encoded pixel data. Perhaps use a tool such as Photoshop to export them as SVG first.

**Comment by devicezero** [comment]
I see, do you have any advise on how to extract the clipping path automatically? The clipping path might be different for every image so manual work with photoshop is not an option ;)

**Comment by lovell** [comment]
There's some documentation on the proprietary Adobe metadata at https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/#50577409_17587 if you'd like to attempt to parse it. Good luck!
