### ISSUE TITLE
How to add color tint to an image?

### ISSUE THREAD

**Issue by tjpc3** [lovell/sharp#1178]
Hello! I have multiple images that I would like to apply a color tint to. For example, I have this image: [https://i.imgur.com/6xqSOcj.png](https://i.imgur.com/6xqSOcj.png)
And I would like to apply a tint of 0xFFC224 which should look like this: 
[https://i.imgur.com/vYizj0L.png](https://i.imgur.com/vYizj0L.png)
Any ideas on how I might do this?

**Comment by lovell** [comment]
Hello, a PR was submitted to implement this at #825 but it might need a little bit of work before landing.

**Comment by Slapbox** [comment]
In the meantime you can use the composite image feature using a `png` file. I've currently yet to get that feature to accept any file format, but I'm sure it's my fault.

**Comment by tjpc3** [comment]
Sorry it took me a few days to respond, haven't been able to get back on my desktop. 
Slapbox you say you can use the composite image feature with a png file to get the tint effect? How?

**Comment by Slapbox** [comment]
Inside of an async function make _two_ `sharp` image buffers using:

`const someImg = sharp(someInput).toBuffer();`
`const someOtherImg= sharp(someOtherInput).toBuffer();`

Then use:
```
const composite = someImg.overlayWith(someOtherImg, { tile: true });
const imgBufferWithFilters= await composite.toBuffer();
```
Make your image to overlay with a 1px PNG with transparency. If you need various tints though, you'll need to generate PNG images to filter with on the fly, or store an array of the things.

**Comment by tjpc3** [comment]
I tried doing that but it results in the black pixels being modified. In the meantime I've found a solution that produces a close effect to the one I'm looking for. 

```
const image = sharp(buffer); // buffer contains a png buffer of the image I want to apply the effect to
const metadata = await image.metadata();

metadata.background = new Buffer([255, 194, 36]); // RGB values
const colorImageBuffer = await sharp(buffer)
    .boolean(await sharp({create: metadata}).png().toBuffer(), `and`)
    .png().toBuffer();

const tintedImage = await image.overlayWith(colorImageBuffer).resize(undefined, LINE_HEIGHT).png().toBuffer({resolveWithObject: true});
```
The result looks like this:
[https://i.imgur.com/qkw1Ai3.png](https://i.imgur.com/qkw1Ai3.png)
With colors that are either 0x000000 or 0xFFFFFF it works how it's supposed to work, but it doesn't work properly at colors in between. The best way to do this would be to multiply the color channels together instead of anding them together, but this works for time being.

**Comment by lovell** [comment]
v0.20.2 now available with this feature.

**Comment by wezside** [comment]
I'm trying to use this new feature however the RGB colour I'm passing in is not the one used to tint with. Maybe I'm not fully understanding what "Chroma" tint means but I expect to see:

**Red Tint**
`sharp(tmp)
.tint({r: 255, g: 0, b: 0})`

**Green Tint**
`sharp(tmp)
.tint({r: 0, g: 255, b: 0})`

I've also tried to generate the parameter using the color module:
`var c = color({r: 0, g: 255, b: 0});`
`sharp(tmp)
.tint(c)`

As a side note it would be great to have popular blendmodes added to this library.

**Comment by lovell** [comment]
@wezside Please can you create a new issue with a working code example and input image if this is still a problem.
