### ISSUE TITLE
PDF Support - feature request

### ISSUE THREAD

**Issue by nateevans** [lovell/sharp#1181]
It seems that libvips already supports reading pdf, would it be possible to have the sharp library support it as well? (at least for reading from pdf)

I know little to no c++ otherwise I would take a crack myself...

**Comment by nateevans** [comment]
Or does it already support it? I didn't see the docs say that PDF works for input but skimming the code I see PDF related things...

https://github.com/lovell/sharp/commit/1de0038516ad4e3e2a263ad337e66d91eb8f3159#diff-735742ac194c172d791e760898d80a03

Apologies if this already works, I'll run some tests

**Comment by lovell** [comment]
Hello, you'll need to compile and globally install a custom libvips with PDF support before installing sharp.

**Comment by swftvsn** [comment]
Would it be possible to consider building sharp libvips dist with pdfium now that it has landed to libvips here: https://github.com/jcupitt/libvips/issues/689? It is license compatible.

Other alternative would be to support custom built libvips that is not globally installed, as there are many environments where we aren't allowed to install a single thing. I believe this support was added here: https://github.com/lovell/sharp/issues/1164 and should be doable by overriding `SHARP_IGNORE_GLOBAL_LIBVIPS` and `SHARP_DIST_BASE_URL`. Is this correct?

Perhaps the best thing would be to provide both binaries: with or without pdfium? And use the without pdfium ones as default to be backwards compatible, and explain in readme that by providing the two env variables one ensures sharp always uses the pdfium enabled lib?

Is there any work that needs to be done in sharp to use the new pdfium support or is it transparent for sharp @lovell?

**Comment by lovell** [comment]
@swftvsn There may be a small change required to sharp to integrate with libvips' future pdfium loader but this won't happen until after libvips v8.7.0 is available.

If a globally-installed libvips is not possible and you want bleeding edge pdfium support then feel free to fork and modify [sharp-libvips](https://github.com/lovell/sharp-libvips/) to build your own binaries then point your installation process to them via `SHARP_DIST_BASE_URL`.

**Comment by zuohuadong** [comment]
@swftvsn @lovell   How's it going now?
