### ISSUE TITLE
How to compress png without losing transparency?

### ISSUE THREAD

**Issue by timetocode** [lovell/sharp#1183]
Apologies for the newbie question, but what options exist for reducing png filesize? I noticed other formats have quality settings, and the png does not -- presumably because it is lossless. 

So I figured I could convert pngs to jpegs employing the lossy compression and then convert them back to pngs. But in this scenario I've lost the transparency and I'm not sure A) how to convert a color in the jpeg back into transparency in the png, and B) whether this whole approach is even how to go about reducing png filesize.

Thank you

**Comment by lovell** [comment]
Hello, you are correct that PNG is lossless. JPEG does not support an alpha channel, hence the loss of transparency you're experiencing.

Further reduction in PNG filesize can be obtained by using a quantising (and therefore lossy) tool such as [pngquant](https://www.npmjs.com/package/pngquant).

**Comment by timetocode** [comment]
Thanks I was able to get compress the image using pngquant. 

I was also able to use sharp to convert from png to webp and back to png (which is super fast and kept the transparency).

I'll have to play with it all more.
