### ISSUE TITLE
Resize image to fit within circle?

### ISSUE THREAD

**Issue by greghesp** [lovell/sharp#1184]
I've been able to resize images, however I'm struggling how to get my head around this.

I've got a load of images that are normally 4500x5400, although the actual filled area could be a lot less.

What I need to do is create a new png that 485x485 at 300dpi and then draw a circle with a diameter of 485, then resize and overlay the image to sit within the circle

An example..

My 4500x5400 png
![image](https://user-images.githubusercontent.com/768908/38471481-7fdd12de-3b69-11e8-9ef9-8d273b7464ee.png)

Outcome:
![image](https://user-images.githubusercontent.com/768908/38471497-bdee5c0e-3b69-11e8-82e2-3e3ea103002e.png)

Can anyone help me achieve this please?

**Comment by lovell** [comment]
Cross-posted at https://stackoverflow.com/questions/49712421/overlaying-png-onto-svg-using-sharp
