### ISSUE TITLE
Add isProgressive flag to metadata output, requires libvips v8.7.0

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#1186]
http://sharp.pixelplumbing.com/en/stable/api-input/#metadata

* `isProgressive`: Boolean indicating whether the input image is interlaced (supported by JPEG and PNG)

See commit https://github.com/jcupitt/libvips/commit/15abbbe9863629227e7b0a04c78ef1b2d3aeb4b2

("progressive" is used in preference to "interlaced" to ensure consistency with the output functions.)

**Comment by rnanwani** [comment]
To add to this, I was wondering if it is possible to expose the subsampling used (4:2:0 or 4:4:4) on an image? And should these be exposed with metadata() or stats()?

**Comment by lovell** [comment]
@rnanwani Support for exposing `h_samp_factor` and `v_samp_factor` would need to be added to libvips' `read_jpeg_header` function first. Both these and `isProgressive` can be determined without decoding pixel data so belong in `metadata()`.

**Comment by rnanwani** [comment]
Subsampling related task completed in vips https://github.com/jcupitt/libvips/issues/954
I think it can now be appended to this task itself.

**Comment by lovell** [comment]
Added in commit 17f942c

**Comment by lovell** [comment]
v0.21.0 now available with this feature.
