### ISSUE TITLE
flatten making alpha 1.0?

### ISSUE THREAD

**Issue by mrkurt** [lovell/sharp#1188]
I want to put a png with alpha on a background with alpha. `flatten` isn't doing what I expect, it forces alpha to 1.0 on all the pixels instead of keeping the background alpha. Is this what it's supposed to be doing? It yields results like this:

![wat](https://user-images.githubusercontent.com/7724/38743173-0a5bd93e-3f04-11e8-829d-dd94916e8e0f.png)

Here's the code I'm using:
```javascript
let sharp = require('sharp')
let img = sharp("test.png")
img.background('rgba(255,0,0,0.5)').extend(20).flatten().toFile("wat.png")
```

And here's the input image:

![test](https://user-images.githubusercontent.com/7724/38743201-180c3d3a-3f04-11e8-81e6-bb15c43b15dd.png)

**Comment by mrkurt** [comment]
> As an aside, the flatten and extend operations both share the same background colour, which is a bit confusing so I've been planning to modify them to accept a colour of their own.

That would be fabulous.

**Comment by lovell** [comment]
The underlying `flatten` operation in libvips is there to remove an alpha channel, so sharp is at least consistent with its existing approach, and therefore this probably isn't a bug after all.

For this scenario I would suggest using [overlayWith](http://sharp.pixelplumbing.com/en/stable/api-composite/#overlaywith) to composite the `test.png` balloon image over a semi-transparent background image, something like (untested):

```javascript
const { width, height } = await sharp("test.png").metadata();

const create = {
  width: width + 40,
  height: height + 40,
  channels: 4,
  background: 'rgba(255,0,0,0.5)'
};

await sharp({ create })
  .overlayWith("test.png")
  .toFile("wat.png");
```

**Comment by mrkurt** [comment]
That's actually what we ended up doing! Thanks for digging in to this one.
