### ISSUE TITLE
Input buffer contains unsupported image format

### ISSUE THREAD

**Issue by jmcgui05** [lovell/sharp#1190]
I may be doing something wrong, and hopefully so. I'm using node https request to get an image from a url and pass that Buffer response into sharp. I was using the request module but due to a bunch of `ESOCKETTIMEDOUT` errors and after reviewing [this issue](https://github.com/request/request/issues/2906), I decided to switch back to https request. Now, I get this `Input buffer contains unsupported image format` error, which the headers show as a jpeg.

Node version: 8.9.4
sharp version: 0.20.1
example url that results in this error: https://farm5.staticflickr.com/4476/37774292932_eaed98bf7c_o.jpg

Example Response Headers:
    `

    { 
      date: 'Sat, 14 Apr 2018 01:40:57 GMT',
      'content-type': 'image/jpeg',
      'content-length': '74782',
      connection: 'close',
      'x-photo-farm': '5',
      p3p: 'policyref="https://policies.yahoo.com/w3c/p3p.xml", CP="CAO DSP COR CUR ADM DEV 
        TAI PSA PSD IVAi IVDi CONi TELo OTPi OUR DELi SAMi OTRi UNRi PUBi IND PHY ONL UNI 
        PUR FIN COM NAV INT DEM CNT STA POL HEA PRE LOC GOV"',
      'x-photo-origin': 'bf1',
      'cache-control': 'max-age=604800,public',
      expires: 'Sat, 21 Apr 2018 01:39:44 UTC',
      'last-modified': 'Fri, 20 Oct 2017 05:50:28 GMT',
      'accept-ranges': 'bytes',
      age: '73',
      via: 'http/1.1 pc-pool131.flickr.bf1.yahoo.com (ApacheTrafficServer [cHs f ])',
      server: 'ATS',
      'x-photo-farm-guess': '5',
      'access-control-allow-origin': '*',
      'access-control-allow-methods': 'POST, GET, OPTIONS' 
    }

`
Example code:

`

    https.get(url, (res) => {
      let body = '';
      res.on('data', (data) => {
        body += data;
      });
      res.on('end', () => {
        body = Buffer.from(body, 'utf-8');
        let resized = sharp(body).resize(width, height)
        resized.toBuffer()
          .then((outputBuffer) => {
            resolve(outputBuffer);
          })
          .catch((error) => {
            reject(error);
          });
      })
    })

`

**Comment by lovell** [comment]
Hello, the `data` chunks emitted by `res` are binary Buffer objects rather than strings, so the method of concatenation needs to be altered.

Luckily `res` is a `ReadableStream` so you can use it directly. Try something like (untested):

```javascript
https.get(url, res => {
  const resizer = sharp()
    .resize(width, height)
    .toBuffer()
    .then(resolve)
    .catch(reject);

  res.pipe(resizer);
});
```

This kind of general Node.js question is usually better asked at a site like StackOverflow as it's not specific to sharp.
