### ISSUE TITLE
Unknown pseudo-tag 65538 tiff2vips: unsupported tiff image type

### ISSUE THREAD

**Issue by kb47** [lovell/sharp#1191]
Hello,

When I trying to convert tiff image to jpeg following error occured.

`Error: TIFFSetField: C:\Users\kb\Desktop\000003.tif: Unknown pseudo-tag 65538
TIFFSetField: C:\Users\kb\Desktop\000003.tif: Unknown pseudo-tag 65538 tiff2vips: unsupported tiff image type`

I updated my sharp version to latest. But no luck. 
Here's the file which failed to convert. 
[000003.zip](https://github.com/lovell/sharp/files/1913611/000003.zip)

**Comment by lovell** [comment]
Hello, this image is using an obsolete TIFF format that is unsupported by libvips.
```sh
$ tiffinfo 000003.tif | grep Compression
  Compression Scheme: Old-style JPEG
```
This format was deprecated over 20 years ago - see
https://github.com/openpreserve/format-corpus/tree/master/tiff-examples/old-style-jpeg-compression
