### ISSUE TITLE
zip date time issue while working with AWS cloud9

### ISSUE THREAD

**Issue by stone12379** [lovell/sharp#1192]
sharp package seems contains some old files that preventing it to be automatically uploaded by AWS cloud9. Although this problem could be fixed by following command, I am wondering if it could be fixed in future release.

find . -mtime +13700 -ls -exec touch {} +

**Comment by lovell** [comment]
Hello, running `find . -mtime +13700 -ls` (last modified in 1980?) lists no files for me. Which files does it list for you?

**Comment by stone12379** [comment]
I used `npm install sharp` to install it in a new environment, then run `find . -mtime +13700 -ls` inside the node_modules folder and found following files problematic.


 42684   12 -rw-rw-r--   1 ec2-user ec2-user    10820 Jan  1  1970 ./bl/README.md
 42547    8 -rw-rw-r--   1 ec2-user ec2-user     6400 Jan  1  1970 ./bl/bl.js
 42629    4 -rw-rw-r--   1 ec2-user ec2-user     1216 Jan  1  1970 ./bl/LICENSE.md
 42344    4 drwxrwxr-x   2 ec2-user ec2-user     4096 Jan  1  1970 ./bl/test
 42364   20 -rw-rw-r--   1 ec2-user ec2-user    17556 Jan  1  1970 ./bl/test/test.js
 42434    4 -rw-rw-r--   1 ec2-user ec2-user     1147 Jan  1  1970 ./bl/.jshintrc
 42509    4 -rw-rw-r--   1 ec2-user ec2-user      198 Jan  1  1970 ./bl/.travis.yml
 42591    4 -rw-rw-r--   1 ec2-user ec2-user     2469 Jan  1  1970 ./fs-minipass/README.md
 42521    4 -rw-rw-r--   1 ec2-user ec2-user      765 Jan  1  1970 ./fs-minipass/LICENSE
 42449   12 -rw-rw-r--   1 ec2-user ec2-user     8967 Jan  1  1970 ./fs-minipass/index.js
 42520    4 -rw-rw-r--   1 ec2-user ec2-user     1770 Jan  1  1970 ./minipass/README.md
 42448    8 -rw-rw-r--   1 ec2-user ec2-user     7379 Jan  1  1970 ./minipass/index.js
 42595   40 -rw-rw-r--   1 ec2-user ec2-user    39100 Jan  1  1970 ./tar/README.md
 42892    4 -rw-rw-r--   1 ec2-user ec2-user      533 Jan  1  1970 ./tar/lib/winchars.js
 42821   12 -rw-rw-r--   1 ec2-user ec2-user     9613 Jan  1  1970 ./tar/lib/pack.js
 42897   12 -rw-rw-r--   1 ec2-user ec2-user    11583 Jan  1  1970 ./tar/lib/write-entry.js
 42883    4 -rw-rw-r--   1 ec2-user ec2-user      852 Jan  1  1970 ./tar/lib/update.js
 42853    4 -rw-rw-r--   1 ec2-user ec2-user     2467 Jan  1  1970 ./tar/lib/read-entry.js
 42652    4 -rw-rw-r--   1 ec2-user ec2-user      283 Jan  1  1970 ./tar/lib/buffer.js
 42861    8 -rw-rw-r--   1 ec2-user ec2-user     5492 Jan  1  1970 ./tar/lib/replace.js
 42374    4 -rw-rw-r--   1 ec2-user ec2-user      772 Jan  1  1970 ./tar/lib/high-level-opt.js
 42808    8 -rw-rw-r--   1 ec2-user ec2-user     5180 Jan  1  1970 ./tar/lib/mkdir.js
 42328   12 -rw-rw-r--   1 ec2-user ec2-user     8517 Jan  1  1970 ./tar/lib/header.js
 42835   12 -rw-rw-r--   1 ec2-user ec2-user    11991 Jan  1  1970 ./tar/lib/parse.js
 42875   16 -rw-rw-r--   1 ec2-user ec2-user    14867 Jan  1  1970 ./tar/lib/unpack.js
 42888    4 -rw-rw-r--   1 ec2-user ec2-user      309 Jan  1  1970 ./tar/lib/warn-mixin.js
 42349    4 -rw-rw-r--   1 ec2-user ec2-user     2824 Jan  1  1970 ./tar/lib/extract.js
 42869    4 -rw-rw-r--   1 ec2-user ec2-user     1095 Jan  1  1970 ./tar/lib/types.js
 42780    4 -rw-rw-r--   1 ec2-user ec2-user     1978 Jan  1  1970 ./tar/lib/large-numbers.js
 42794    4 -rw-rw-r--   1 ec2-user ec2-user     3152 Jan  1  1970 ./tar/lib/list.js
 42320    4 -rw-rw-r--   1 ec2-user ec2-user     2374 Jan  1  1970 ./tar/lib/create.js
 42842    4 -rw-rw-r--   1 ec2-user ec2-user     4070 Jan  1  1970 ./tar/lib/pax.js
 42525    4 -rw-rw-r--   1 ec2-user ec2-user      765 Jan  1  1970 ./tar/LICENSE
 42454    4 -rw-rw-r--   1 ec2-user ec2-user      683 Jan  1  1970 ./tar/index.js

**Comment by lovell** [comment]
Thanks. I don't see any files provided by sharp in this list.

https://github.com/npm/npm/issues/19968 is probably the underlying cause. Perhaps contact the other modules listed here and request they publish new versions.
