### ISSUE TITLE
Resize image to a small value than canvas?

### ISSUE THREAD

**Issue by greghesp** [lovell/sharp#1193]
I've got an image thats 4500x5400.

What I'm trying to do is resize this image to 440x440 (scaled), but setting the canvas of the png to 485x485.
How can I go about doing this?

**Comment by lovell** [comment]
Please see the [extend](http://sharp.pixelplumbing.com/en/stable/api-operation/#extend) operation (and the possible future enhancement discussed in #1072 may be relevant).

**Comment by greghesp** [comment]
Ah thanks :)
Reading it, I had assumed that operation added a "stroke" around the image
