### ISSUE TITLE
Rotation issue?

### ISSUE THREAD

**Issue by igorescobar** [lovell/sharp#1194]
Hey there!

Should auto rotate fix this?
![wrong-tiff](https://user-images.githubusercontent.com/24032/38890391-219f8ff0-4279-11e8-9a6d-3cea005a0643.jpg)

I'm currently using the `.rotate()` method to kinda auto-rotate the images for me (tested also without it)... but I recently stumbled on this picture that it isn't working as expected (end-user perspective) the output is always the same. I tested uploading this photo in popular social networks to see how they handled it and for example... facebook and gmail handles it ok but some of othersites don't.

Any idea on how to handle this situation correctly?

ps: I'm currently on sharp `v0.19.1`.

**Comment by igorescobar** [comment]
@lovell I think I found the problem. Aparrently, the `toBuffer()` is erasing the EXIF orientation. I added a `.withMetadata()` before the `toBuffer()` and it handled it nicely. Is this the expected behaviour?

**Comment by igorescobar** [comment]
I know it's weird but yeah, a single image passes through a few `toBuffer` during the process.

**Comment by lovell** [comment]
> "The default behaviour, when withMetadata is not used, is to strip all metadata" http://sharp.pixelplumbing.com/en/stable/api-output/#withmetadata

**Comment by igorescobar** [comment]
@lovell Oh! Sorry @lovell I missed that on the docs. All good.

**Comment by igorescobar** [comment]
@lovell I appreciate all the help.
