### ISSUE TITLE
how can be done create new image with sharp?

### ISSUE THREAD

**Issue by hbakhtiyor** [lovell/sharp#1196]
want to convert the simple canvas example using sharp, and get raw image.

```js
var Canvas = require('canvas');
// use node-canvas
var canvas = new Canvas(320, 240);
var ctx = canvas.getContext('2d');

// red rectangle
ctx.fillStyle = '#ff0000';
ctx.fillRect(0, 0, 320, 240);
```

**Comment by lovell** [comment]
Hello, did you see the "Create a blank 300x200 PNG image of semi-transluent red pixels" example at http://sharp.pixelplumbing.com/en/stable/api-constructor/#sharp ?

**Comment by hbakhtiyor** [comment]
hi @lovell, working with gifencoder and sharp, and the example doesn't work, is `raw` the right method to get 32bit RGBA?

```js
const fs = require('fs');
const sharp = require('sharp');
const GIFEncoder = require('gifencoder');

(async () => {
  const imageData = sharp({
      create: {
      width: 300,
      height: 200,
      channels: 4,
      background: { r: 255, g: 255, b: 255, alpha: 1 }
      }
  }).raw().toBuffer();

  const encoder = new GIFEncoder(300, 200);
  
  encoder.createReadStream().pipe(fs.createWriteStream('thumbs.gif'));
  
  encoder.start();
  encoder.setRepeat(-1);   
  encoder.setDelay(500);  
  encoder.setQuality(100);   

  encoder.addFrame(imageData);
  encoder.finish();
})()
```

**Comment by hbakhtiyor** [comment]
when passing without `alpha`, e.g. `background: { r: 255, g: 255, b: 255 }` or `background:'#ffffff', works well`

**Comment by hbakhtiyor** [comment]
also doesn't work with gifencoder when loading image and using `raw` method

https://github.com/eugeneware/gifencoder/issues/26

**Comment by lovell** [comment]
Colour JPEG images are 3 channel so `raw` will be RGB for these.

See https://github.com/lovell/sharp/issues/554#issuecomment-371405022 for an example of adding a 4th channel using `joinChannel`.

There's also a future possible enhancement https://github.com/lovell/sharp/issues/1153 that will simplify the concatenation of an alpha channel to a non-transparent input.

**Comment by hbakhtiyor** [comment]
when i use your example i got error

sharp version: 0.20.1

the sample code
```js
const fs = require('fs');
const sharp = require('sharp');
const GIFEncoder = require('gifencoder');

(async () => {
  const imageData = await sharp('thumbs.jpeg')
  .joinChannel({ create: { background: 'black', channels: 1, width: 1200, height: 630 } })
  .raw().toBuffer();

  const encoder = new GIFEncoder(1200, 630);
  
  encoder.createReadStream().pipe(fs.createWriteStream('thumbs.gif'));
  
  encoder.start();
  encoder.setRepeat(-1);   
  encoder.setDelay(500);  
  encoder.setQuality(100);   

  encoder.addFrame(imageData);
  encoder.finish();
})()
```

the output error
```
Error: Expected width, height, channels and background to create a new input image
    at Sharp._createInputDescriptor (/development/demo/node_modules/sharp/lib/input.js:81:15)
    at Sharp.joinChannel (/development/demo/node_modules/sharp/lib/channel.js:68:42)
    at repl:3:4
    at repl:17:3
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:440:10)
    at emitOne (events.js:120:20),
```

**Comment by lovell** [comment]
Sorry, my mistake, that (untested) example is incorrect as the `{ create: { ... } }` approach only supports 3 and 4 channel images.

There's another possible workaround in https://github.com/lovell/sharp/issues/554#issuecomment-371262164 to consider whilst waiting for #1153

**Comment by hbakhtiyor** [comment]
thanks, the workaround works well,

```js
const fs = require('fs');
const sharp = require('sharp');
const GIFEncoder = require('gifencoder');

(async () => {
  const width = 1200, height = 630;
  const imageData = await sharp('thumbs.jpeg')
  .joinChannel(Buffer.alloc(width * height, 255), { raw: { channels: 1, width, height} })
  .raw().toBuffer();

  const encoder = new GIFEncoder(width, height);
  
  encoder.createReadStream().pipe(fs.createWriteStream('thumbs.gif'));
  
  encoder.start();
  encoder.setRepeat(-1);   
  encoder.setDelay(500);  
  encoder.setQuality(100);   

  encoder.addFrame(imageData);
  encoder.finish();
})()
```
also about the `Buffer.alloc(width * height, 255)`, for what 255 here? just played with `Buffer.alloc(width * height)` and can't see any different visually

does the sharp workaround faster than the `canvas` alternative?
```js
const Canvas = require('canvas');
canvas = new Canvas(width, height);
ctx = canvas.getContext('2d');
img = new Canvas.Image;

img.src = fs.readFileSync('thumbs.jpeg');
ctx.drawImage(img, 0, 0, width, height);
```

**Comment by hbakhtiyor** [comment]
btw, any plans to support gif encoding in sharp module?

**Comment by lovell** [comment]
The future libvips v8.7.0 will add support for writing GIF files via *magick but exposing this in sharp will require some work and will require a global installation of libvips compiled with support for *magick (the precompiled binaries provided by sharp will not support this).

Your current approach of exporting raw pixel data and using an external encoder is probably the best for now.

**Comment by hbakhtiyor** [comment]
thanks, could you please answer to my previous questions

**Comment by lovell** [comment]
> "the result of the workaround is a bit blur from original, how to look it the same?"

My best guess would be that `encoder.setQuality(100);` is your problem - see https://github.com/eugeneware/gifencoder/issues/6 - please remember that GIF is lossy.

> "does the sharp workaround faster than the canvas alternative?"

You'll need to create a benchmark to test this.

**Comment by hbakhtiyor** [comment]
i meant when i use canvas the gif looks good, and with using sharp a bit blur
