### ISSUE TITLE
font warning only when no width, height and viewBox

### ISSUE THREAD

**Issue by DanielRuf** [lovell/sharp#1199]
```xml
<svg preserveAspectRatio="xMidYMid" xmlns="http://www.w3.org/2000/svg">
    <defs>
        <style>
            .cls-1 {
            fill: #33b6fa;
            fill-rule: evenodd;
            }
            .cls-2,
            .cls-3 {
            font-size: 22px;
            }
            .cls-3 {
            fill: #fff;
            font-family: "STHeitiSC-Light"
            }
        </style>
    </defs>
    <path class="cls-1" d="M0 0h40v43l-20-5.292-20 5.292v-43z"/>
    <text class="cls-2" x="9" y="27">
        <tspan class="cls-3">新</tspan>
    </text>
</svg>
```

```
$ node test/svg-sprite.1.js

(sharp:14508): Pango-WARNING **: couldn't load font ""STHeitiSC-Light" Not-Rotated 22", falling back to "Sans Not-Rotated 22", expect ugly output.
{ format: 'svg',
  width: 40,
  height: 43,
  space: 'srgb',
  channels: 4,
  depth: 'uchar',
  density: 72,
  hasProfile: false,
  hasAlpha: true }
```

```xml
<svg height="43" preserveAspectRatio="xMidYMid" viewBox="0 0 40 43" width="40" xmlns="http://www.w3.org/2000/svg">
    <defs>
        <style>
            .cls-1 {
            fill: #33b6fa;
            fill-rule: evenodd;
            }
            .cls-2,
            .cls-3 {
            font-size: 22px;
            }
            .cls-3 {
            fill: #fff;
            font-family: "STHeitiSC-Light"
            }
        </style>
    </defs>
    <path class="cls-1" d="M0 0h40v43l-20-5.292-20 5.292v-43z"/>
    <text class="cls-2" x="9" y="27">
        <tspan class="cls-3">新</tspan>
    </text>
</svg>
```

```shell
$ node test/svg-sprite.1.js
{ format: 'svg',
  width: 40,
  height: 43,
  space: 'srgb',
  channels: 4,
  depth: 'uchar',
  density: 72,
  hasProfile: false,
  hasAlpha: true }

```

**Comment by lovell** [comment]
Hello, it's always best to ensure an SVG input contains dimensions so its good to see that example working as expected.

In terms of the difference when dimensions are missing, I'd suggest the first thing to do is try to isolate these test cases using only the underlying librsvg renderer, perhaps using its `rsvg-convert` command line tool.

**Comment by DanielRuf** [comment]
> Hello, it's always best to ensure an SVG input contains dimensions so its good to see that example working as expected.

This is not always the case in reality ;-)

I am just confused about the inconsistence about the font warning. It should be shown in both cases.

**Comment by lovell** [comment]
If you're able to do some testing with the `rsvg-convert` command line tool then that may help narrow down what's going on here.

**Comment by DanielRuf** [comment]
Ok, I'll check what steps I have to do to test it. Is there some documentation about the right steps or can you recommend some resources?

**Comment by lovell** [comment]
I can't reproduce this locally, using either `rsvg-convert` or sharp itself.

`STHeitiSC-Light` is a (commercial?) iOS font according to https://steve.zazeski.com/mobile-app-fonts/. Is this problem on OS X? Perhaps there's a local misconfiguration - check in `/System/Library/Fonts` or `/Library/Fonts`. Good luck!

**Comment by DanielRuf** [comment]
Will try it with some more fonts and check if there was a bugfix in a newer sharp release.

The only issue is that it is not consistently throwing this warning (it should be thrown in both cases).
Not the font or setup itself.

**Comment by lovell** [comment]
@DanielRuf Were you able to make any progress with this anomaly?
