### ISSUE TITLE
accuracy of metadata.width and metadata.height for SVG input

### ISSUE THREAD

**Issue by DanielRuf** [lovell/sharp#1200]
It seems metadata outputs integers for svg elements which have dimensions with decimals.

**Comment by lovell** [comment]
Hello, the values reported are the integral pixel dimensions at which the input SVG will be rasterised.

**Comment by DanielRuf** [comment]
Sure but fraction pixels are also valid and needed for SVG as they do not always use full values without decimals.

An svg can be 34.5px * 38.75px or units in general. And many browsers also support image dimensions with fractions.

**Comment by DanielRuf** [comment]
The problem is that the values given by metadata are not exact

https://github.com/jkphl/svg-sprite/issues/254#issuecomment-382519476
https://github.com/jkphl/svg-sprite/blob/master/test/fixture/svg/special/without-dims.svg

**Comment by lovell** [comment]
sharp ultimately relies on librsvg for this, which reports integral pixel dimensions. Perhaps there's an additional library you could use such as https://www.npmjs.com/package/probe-image-size

**Comment by DanielRuf** [comment]
> sharp ultimately relies on librsvg for this, which reports integral pixel dimensions. Perhaps there's an additional library you could use such as https://www.npmjs.com/package/probe-image-size

Unfortunately this does not work with svg files which do not have width, height and viewBox.

In theory I expect the metadata to report the real data of the source file (without any type casting or transformations). I'll check the mentioned dependency and try to find a solution to get more data from it for the use in the metadata function.

**Comment by lovell** [comment]
Closing as there's not a lot sharp can do here given it simply reports dimensions from the upstream librsvg dependency.

If anyone finds an alternative that does provide more detailed information then please add a comment in case others are looking for a similar solution.

**Comment by teohhanhui** [comment]
Opened https://github.com/libvips/libvips/issues/1242
