### ISSUE TITLE
Image auto rotation even using withMetadata

### ISSUE THREAD

**Issue by Andresmag** [lovell/sharp#1203]
So, I'm using sharp v.0.20.1 in my node project and I'm uploading images to S3. The problem comes when I try to resize them. Some times sharp auto rotate the image and I don't understand why because I'm using the function .withMetadata().
This is my code:
`util.resizeAndCropImage = async (image, width, height, quality) => {
  return await sharp(image)
.resize(width, height)
.max()
.crop(sharp.gravity.centre)
.background('white')
.flatten()
.jpeg({ quality: quality })
.toFormat('jpg')
.withMetadata()
.toBuffer();
};` 
The parameters for width and height are "width": 1442, "height": 480. I tried to put the .withMetadata() in every place and the result is always the same so the position is not relevant.

And this an example of what is happening:
 - This is the normal image (sorry about the quality but is just a quick example)
![c5f58396-f1ee-41da-a763-1eac971cb111](https://user-images.githubusercontent.com/14923280/39149028-216d6fc4-473e-11e8-8844-009120031026.JPG)

- This is what I see in the browser:
<img width="1402" alt="captura de pantalla 2018-04-23 a las 21 40 05" src="https://user-images.githubusercontent.com/14923280/39149304-f0f3a7ea-473e-11e8-8195-2dc513837f40.png">

- And if I download the image this is what I get:
![background_5accd1718e14dd00cc087268](https://user-images.githubusercontent.com/14923280/39149329-029da13a-473f-11e8-9989-5368083ab636.jpg)

So it looks like it's rotating the image, then resizing it and finally making it vertical again. I need the resizing to happen with the image in its normal orientation. 

Any help is welcome! 

(EDIT) 
Ok, now I'm more confused. I don't know why the image appears turn to the left when in my library is upright...
<img width="249" alt="captura de pantalla 2018-04-23 a las 21 51 27" src="https://user-images.githubusercontent.com/14923280/39149764-80b1b682-4740-11e8-8848-892ff2d6c8f5.png">

**Comment by lovell** [comment]
The input image probably contains EXIF metadata with an Orientation tag and you're likely to be seeing the effects of different software's ability to handle that.

sharp will only auto-rotate the image if you add the `rotate()` operation.

**Comment by Andresmag** [comment]
Using the rotate() operation the images appears up straight! Thanks!

**Comment by Beraliv** [comment]
Thanks, it helped me too

**Comment by shneziri** [comment]
Thanks, helped me too!

**Comment by lovell** [comment]
For anyone else coming here, you're probably looking for [`autoOrient()`](https://sharp.pixelplumbing.com/api-operation/#autoorient)
