### ISSUE TITLE
metadata: expose VIPS_META_PAGE_HEIGHT, VIPS_META_N_PAGES, requires libvips v8.7.0

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#1205]
Multi-page images e.g. TIFF are treated by libvips as a "toilet-roll" image. sharp could expose this information via the existing `metadata` feature.

If an image has the `VIPS_META_PAGE_HEIGHT` integer property set, add two new properties to `metadata()` response:

* `pageHeight`: the value of `VIPS_META_PAGE_HEIGHT`
* `pages`: the (total) `height` divided by `VIPS_META_PAGE_HEIGHT`, i.e. the number of pages

**Comment by woolite64** [comment]
Does libvips have a way to count the number of TIFF directories? There are some situations (e.g. concatenated documents) where height may vary by page.

**Comment by lovell** [comment]
libvips requires that all the heights (and a few other properties) are the same when reading multiple "pages" of a TIFF file.

https://github.com/jcupitt/libvips/blob/5176b4a17ec9ca5151f1b8b503b2f237f3c83b27/libvips/foreign/tiff2vips.c#L2173-L2197

**Comment by woolite64** [comment]
If I'm reading correctly, it looks like that requirement only holds when you are retrieving more than one page at a time.

Before the snippet you linked, there is a call to rtiff_n_pages -- it appears to count the number of TIFF directories without requiring uniformity.

https://github.com/jcupitt/libvips/blob/5176b4a17ec9ca5151f1b8b503b2f237f3c83b27/libvips/foreign/tiff2vips.c#L495-L512

**Comment by lovell** [comment]
Good point, thank you, for multi-page TIFF input this only makes sense after the `n` property of [tiffload](http://jcupitt.github.io/libvips/API/current/VipsForeignSave.html#vips-tiffload) is exposed also (possibly with a more descriptive name).

**Comment by lovell** [comment]
Better yet, we can use [VIPS_META_N_PAGES](https://github.com/jcupitt/libvips/commit/da6f4fd04319677319173505b6a1ecc3ccf4c59f), available in the future libvips v8.7.0, for the value of `pages`.

**Comment by woolite64** [comment]
Thanks @lovell, you beat me to it. jcupitt was quick with that commit.

How do you manage development against the latest libvips changes? Willing to test and PR this, but I'm not sure where to start.

**Comment by lovell** [comment]
Features that require the future libvips v8.7.0 will need to wait until (a) it's released and (b) the next "major" version of sharp that places a minimum dependency on that version of libvips, which is likely to be sharp v0.21.0.

**Comment by lovell** [comment]
v0.21.2 now available with this feature.
