### ISSUE TITLE
Batch processing? Globs?

### ISSUE THREAD

**Issue by kokujin** [lovell/sharp#1216]
Can someone point me to an example that processes an image folder instead of a single image? Thanks.

**Comment by lovell** [comment]
Hello, perhaps use the [glob](https://www.npmjs.com/package/glob) module to build a list of files.
```javascript
glob("*.jpg", (err, files) => {
  for (const file of files) {
    sharp(file)...
  }
});
```

**Comment by lovell** [comment]
Hope this answered your question.
