### ISSUE TITLE
Setting hue, brightness

### ISSUE THREAD

**Issue by jonathan-kosgei** [lovell/sharp#1218]
There seem to be a couple things in libvips that are not currenty possible to do like setting the brightness and hue and possibly others https://github.com/jcupitt/libvips/issues/59

The instructions on how to do them in libvips come with a pretty steep learning curve and I was wondering if there was any reason they were not made available in sharp?

**Comment by lovell** [comment]
Hello, did you see #609?

**Comment by jonathan-kosgei** [comment]
Nope, sorry, I'll close this.
