### ISSUE TITLE
Wrong buffer

### ISSUE THREAD

**Issue by hellraisercenobit** [lovell/sharp#1219]
ToBuffer method returns a wrong buffer randomly

example:

```
sharp(imageFile)
          .resize(myWidth, myHeight)
          .background({r: 0, g: 0, b: 0, alpha: 0})
          .embed()
          .toFormat(sharp.format.jpeg)
          .toBuffer()
          .then(output) => {
// Sometimes buffer cannot be used as uint8Array, it's seems corrupted
console.log(output.buffer);
});
```

**Comment by lovell** [comment]
Hello, the first parameter passed to the [toBuffer](http://sharp.pixelplumbing.com/en/stable/api-output/#tobuffer) callback is an error, if any.
```diff
-          .toBuffer((output) => {
+          .toBuffer((err, data, info) => {
```

**Comment by hellraisercenobit** [comment]
Sorry i forgot then :)

**Comment by lovell** [comment]
Thanks for the code update.

* `output` is a `Buffer` instance, which implements the `Uint8Array` API.
* `output.buffer` is an `ArrayBuffer` instance.

Which type do you need?

**Comment by hellraisercenobit** [comment]
I need arraybuffer, my code is ok and working like a charm with sharp (really fast! :) congrat to you).
But in some cases, i can't use arraybuffer output as uint8array like expected.
It seems output is not a valid arraybuffer.
I don't have any error.
I have tried to write the image instead to use direct buffer without luke.
Maybe it come from an other part of my code.
I'll give you more feedback tomorrow.

**Comment by hellraisercenobit** [comment]
It was coming from an other lib :)
Shame on me.
You can close the issue!
Thx for your help anyway.

**Comment by josephfrazier** [comment]
I had a possibly related issue where the value returned by `toBuffer()` was a `Uint8Array` instead of a `Buffer`, which was causing problems when passed to another library, so I just wrapped the returned value with `Buffer.from()` to make it a proper `Buffer`. Just thought I'd write this down in case anyone else has a similar problem.

**Comment by lovell** [comment]
@josephfrazier You shouldn't need to do this as sharp always responds with a `Buffer` assigned via [Nan::NewBuffer](https://github.com/nodejs/nan/blob/master/doc/buffers.md#nannewbuffer). Perhaps another dependency is re-defining or monkey-patching the global `Buffer` class? Please open a new issue with a code sample if you're able to isolate this behaviour to sharp.

**Comment by josephfrazier** [comment]
Thanks for clarifying! I haven't looked into it closely, but I wouldn't be surprised if something was being monkey-patched. If I do end up isolating the behavior, I'll be sure to open an issue.
