### ISSUE TITLE
Can't obtain 1-channel TIFF output

### ISSUE THREAD

**Issue by OualidYousfi** [lovell/sharp#1225]
I have two images that I combine, and I want my output to be 1 BBP. I've tried `.toColorSpace('b-w')` but it doesn't work. Lowest I got is 8 BBP at ~31kb.

Both of the image inputs are 1 BBP. Let's call one overlayImage and the other baseImage.

overlayImage = 1 BBP, .tiff file, 2,62kb, 350x350, 2880 DPI
baseImage = 1 BBP, .png file, 1,50kb, 1155x1155, 72 DPI

```
let overlayImage = sharp(input1);

//a white border around the overlayImage
overlayImage.background({r: 255, g: 255, b: 255})
  .extend({
    top: x,
    bottom: y,
    left: x,
    right: y
}).png().toBuffer();

...

let baseImage = sharp(input2);
baseImage.overlayWith(overlayImage);

...

baseImage.toColorspace('b-w');
baseImage.tiff({compression: 'deflate', squash: true, xres: (dpi / 2.54), yres: (dpi / 2.54)})
```
resultImage = 8 BBP, .tiff file, 31,18kb, 1155x1155, 2880 DPI

irfanview shows compression used on resultImage as "AdobeDeflate, Grayscale".

**Comment by lovell** [comment]
Hello, the use of `.tiff({ squash: true })` should be enough to reduce TIFF output to 1 BBP. Are you able to provide a complete, working, minimal code sample that exhibits this behaviour?

**Comment by lovell** [comment]
Setting the `NODE_DEBUG=sharp` environment variable reveals a "can only squash 1 band uchar images -- disabling squash" warning.

Your PNG has an alpha channel so you'll need to `flatten()` it out plus set the TIFF predictor to "none", something like the following:

```javascript
sharp("overlay.tiff")
  .background({r: 255, g: 255, b: 255})
  .extend({
    top: 18,
    bottom: 17,
    left: 18,
    right: 17
  })
  .png()
  .toBuffer()
  .then(overlay => sharp("qrcode.png")
    .overlayWith(overlay)
    .flatten()
    .toColorspace("b-w")
    .tiff({
      compression: "deflate",
      predictor: "none",
      squash: true,
      xres: (2880 / 2.54),
      yres: (2880 / 2.54)
    })
    .toFile("resultImage.tiff")
  );
```
