### ISSUE TITLE
travis build fails with sharp as native dependency

### ISSUE THREAD

**Issue by karpawich** [lovell/sharp#1228]
I'm trying to build an Electron application with electron-builder via Travis-CI for Windows, Mac, and Linux and have sharp as a dependency. The electron-builder documentation just points to [a sample Travis build](https://github.com/develar/onshape-desktop-shell/blob/master/.travis.yml) for reference. My app uses [a modified version](https://github.com/karpawich/zoom/blob/master/.travis.yml) based on the sample. While building the executable for the app on my own Windows machine is successful, I'm greeted with the following error when running the Travis-generated executable:

![screenshot 18 _li](https://user-images.githubusercontent.com/34974152/39940093-275e722a-5526-11e8-81f2-b98544493065.jpg)

Likewise, I get the following error when installing the Travis-generated Debian package:

```
Error: libvips-cpp.so.42: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/zoom/resources/app.asar/node_modules/sharp/lib/constructor.js:10:15)
    at Object.<anonymous> (/opt/zoom/resources/app.asar/node_modules/sharp/lib/constructor.js:259:3)
```

Based upon the research I've done thus far, it seems that the error is related to having native dependencies (sharp) which aren't "linked" properly in the Travis build process.

Thanks for your help!

**Comment by lovell** [comment]
> "Perhaps it's because I'm trying to build using Wine inside of a Docker container, and I need to build my application on a native machine?"

Yes, perhaps try https://www.appveyor.com/

**Comment by karpawich** [comment]
According to the electron-builder documentation:
From the electron-builder documentation:
> "You cannot build for Windows using Docker if you have native dependencies and native dependency doesn't use prebuild."

Does sharp meet that criteria? Otherwise this issue can be closed. I'm trying out AppVeyor right now.

Thanks!

**Comment by karpawich** [comment]
After shifting the Windows build process over to AppVeyor, my app now runs without error _on Windows_. However, I have yet to test the binary for Linux, which also threw an error related to sharp's native dependencies. I will close this issue once I test the Linux binary soon.

**Comment by karpawich** [comment]
Linux binary still has an error with `libvips-cpp.so`, but it appears that it is an [electron-builder issue](https://github.com/electron-userland/electron-builder/issues/1376). Closing this issue.
