### ISSUE TITLE
Build error since version 0.8

### ISSUE THREAD

**Issue by jo** [lovell/sharp#123]
I just upgraded from 0.7.2 to 0.8.0 and npm install aborted with the following error:

```
../src/common.cc: In function ‘VipsImage* sharp::InitImage(sharp::ImageType, void*, size_t, VipsAccess)’:
../src/common.cc:77:74: error: ‘vips_tiffload_buffer’ was not declared in this scope
       vips_tiffload_buffer(buffer, length, &image, "access", access, NULL);
```
0.7.2 installs without a problem.

##### uname -a
`Linux localhost 3.17.3-1-ARCH #1 SMP PREEMPT Fri Nov 14 23:13:48 CET 2014 x86_64 GNU/Linux`
##### node -v
`v0.10.33`
##### node-gyp -v
`v1.0.2`

**Comment by jo** [comment]
Hi @lovell, thanks for your patience!

I was indeed able to install sharp `0.9.1` after installing vips `7.40.11` from AUR.

**Comment by lovell** [comment]
Great, glad to hear you got it working.
