### ISSUE TITLE
Random error messages in my log

### ISSUE THREAD

**Issue by 1Map** [lovell/sharp#1232]
Hi,

I get the following error messages in my log for my nodejs app:

```
(sharp:20979): GLib-GObject-WARNING **: 08:22:29.153: invalid uninstantiatable type '(null)' in cast to 'GObject'

(sharp:20979): GLib-GObject-CRITICAL **: 08:22:29.153: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed
```

Unfortunately I have only the above log to go by.  Any ideas?

**Comment by lovell** [comment]
Hello, you've provided very little to go on here.

What version  of Node and sharp is this, and on what platform?

Are you able to provide sample code and image(s) that reproduce this warning?

Are there any other dependencies that require glib e.g. node-canvas?

**Comment by 1Map** [comment]
Ubuntu 16.04 Server 64bit
Node Version 8.11.2
Sharp 0.20.2

Unfortunately I have different pieces of code that uses Sharp for various things, like converting tiff to jpeg, converting PDF to jpeg, creating deep zoom tiling from jpeg images, etc.  I cannot trace the exact line of code where this happens as it happens randomly.

**Comment by lovell** [comment]
All I can suggest here is to add more detailed logging to help narrow down the task and therefore code that's running when the message occurs.

**Comment by kevinswarner** [comment]
I also have been getting these messages.

```
(sharp:9): GLib-GObject-[1;33mWARNING[0m **: [34m16:34:33.204[0m: invalid uninstantiatable type '(null)' in cast to 'GObject'
(sharp:9): GLib-GObject-[1;35mCRITICAL[0m **: [34m16:34:33.205[0m: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed 
```

But, the messages are ONLY output when I use sharp.cache(...).

Also, my final image results appear to be just fine, even when these messages occur.

When...

sharp.cache(false)  -->  messages printed
sharp.cache({ memory: 5, files: 2, items: 10 })  -->  messages printed
sharp.cache(true) -->  NO messages printed

Of course, if I do not use sharp.cache at all, the messages to not appear.

But, again, it seems so far, my resulting images are fine. And, to confirm, the reason I was using sharp.cache(false) was to see if I could reduce the memory consumption. Glad to report that it does indeed do that!

So, I am not sure what to make of these messages. For now, I am going to focus on the results, which appear to be fine.

Hope this helps in the discussion. Thanks for a great library!

**Comment by 1Map** [comment]
Tried it with:
sharp.cache(true)
sharp.cache(false)

Same result on my side.  Just randomly.  Not always.

**Comment by lovell** [comment]
Please feel free to re-open with a code sample that consistently produces these messages.
