### ISSUE TITLE
overlayWith Error: vips_colourspace: no known route from 'cmyk' to 'srgb'

### ISSUE THREAD

**Issue by kevinswarner** [lovell/sharp#1233]
I am getting this error when attempting to overlay one CMYK tiff onto another CMYK tiff. I am very confused about any possible solution as I could not really follow the logic in the other existing issues reported.

What I want to do is simply "append" image2.tif to the right of image1.tif. So, I am taking the approach of first extending image1 by 400 pixels to the right, and then overlaying image2 starting at 400 pixels offset from the left edge.

I have the following...

image1.tif -> 400px by 400px, CMYK, 300ppi
image2.tif -> 400px by 400px, CMYK, 300ppi

I want to end up with...

output.tif -> 800px by 400px, CMYK, 300ppi

```
sharp('image1.tif')
    .extend({ top: 0, bottom: 0, left: 0, right: 400 })
    .overlayWith('image2.tif', { top: 0, left: 400 })
    .toFile('output.tif');
```

But, I get the error...

Error: vips_colourspace: no known route from 'cmyk' to 'srgb'

I tried adding toColorspace('cmyk'), and adding .tiff() thinking that was my issue, but no luck.

Again, I am confused by the potential solutions in existing issues. Am I doing something wrong here or missing something?

Thanks!

**Comment by lovell** [comment]
CMYK input `image1.tif` is converted to sRGB using either an embedded profile or, if missing, a generic profile. From memory the `overlayWith` operation does not currently handle CMYK so you'd have to convert `image2.tif` to sRGB first.

```javascript
sharp('image2.tif')
  .jpeg()
  .toBuffer()
  .then(image2 => sharp("image1.tif")
    .extend({ top: 0, bottom: 0, left: 0, right: 400 })
    .overlayWith(image2, { top: 0, left: 400 })
    .toFile('output.tif')
  )
  .then( ... )
```
CMYK output is not currently possible and I notice you've already commented on the increasingly confusing #218 that will soon be split, see https://github.com/lovell/sharp/issues/218#issuecomment-373722408

**Comment by kevinswarner** [comment]
Thanks. I ended up doing just what you said to get it to work (not the out to CMYK). No problem for now. I am going to use this library to do much of the manipulation work, and then simply convert to CMYK using a different library at a later stage. Thanks for your help!
