### ISSUE TITLE
Yarn add sharp fails with exit code 127

### ISSUE THREAD

**Issue by cocacrave** [lovell/sharp#1234]
node -v
v8.0.0

npm-v
5.4.2

yarn -v
1.3.2

When I try to install package `yarn add sharp` I get the following error.
`yarn install v1.3.2

[1/4] 🔍  Resolving packages...

[2/4] 🚚  Fetching packages...

[3/4] 🔗  Linking dependencies...

[4/4] 📃  Building fresh packages...

[1/1] ⠄ sharp: install No prebuilt binaries found (target=9.5.0 runtime=node arch=x64 platform=darwin)

[-/1] ⠄ waiting...

[-/1] ⠄ waiting...

[-/1] ⠄ waiting...

error /Users/cocacrave/Workspace/projects/functions/image_optimizer/node_modules/sharp: Command failed.

Exit code: 127

Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

Arguments:
Directory: /Users/cocacrave/Workspace/projects/functions/image_optimizer/node_modules/sharp

Output:`

**Comment by lovell** [comment]
Hello, given `node -v` reports v8.0.0 but part of the message suggests v9.5.0 is being used, could there be two conflicting versions of Node on this machine?

```
sharp: install No prebuilt binaries found (target=9.5.0 runtime=node arch=x64 platform=darwin)
```

**Comment by cocacrave** [comment]
I tried yarn add again without doing anything else and now it works. So confused... Anyways thanks!
