### ISSUE TITLE
installation on 32-bit windows

### ISSUE THREAD

**Issue by arushib11** [lovell/sharp#1236]
Hi, I am trying to install sharp on my 32-bit environment of windows. I red through the preivous comments and tried doing "npm install sharp@0.11.4 --save-dev --arch=ia32" but that doesnt work for me. This is the error message i am getting. Can anyone help me with this?
![capture](https://user-images.githubusercontent.com/18275494/40317946-065553aa-5cf1-11e8-882c-0eef37ab4682.PNG)
![capture](https://user-images.githubusercontent.com/18275494/40317959-0e402374-5cf1-11e8-9feb-8392829ec271.PNG)

**Comment by lovell** [comment]
The error says "can't find Python..." so that's a good place to start. I won't be able to help any further as 32-bit Windows is no longer supported. Good luck!

**Comment by David-OConnor** [comment]
Same problem on 64-bit Windows. I have Python 3.6 installed.
