### ISSUE TITLE
Add Lipo.io to the README

### ISSUE THREAD

**Issue by niftylettuce** [lovell/sharp#1237]
Just released <https://lipo.io/> and have it's API running.  It's a free service that's a drop-in replacement for Sharp (has the same API and requires no dependencies nor sharp installation on the machine).

Curious if we could add this to the README?  Everything is completely open source:

https://github.com/lipojs/lipo
https://github.com/lipojs/api.lipo.io
https://github.com/lipojs/lipo-koa
https://github.com/lipojs/lipo-express

The API uses @ladjs/api under the hood:

https://github.com/ladjs/api

**Comment by lovell** [comment]
Hello, this looks very interesting, especially to the (hopefully diminishing) numbers who for whatever reason are unable to install sharp. Perhaps there should be a "built with sharp" page/section in the docs?

Off the top of my head, a few thoughts:

* Is there a plan to deal with versioning, e.g. how might breaking API changes be handled?
* Could the dependency on the deasync native module cause similar problems to those seen with sharp?
* Might this be suitable for "containerisation" so people can self-host?
* Who is paying for the hosting costs of this service? Are there any uptime SLAs etc.?

**Comment by lovell** [comment]
The concept behind this is great, thank you. I'll close for now but would love to learn more about API versioning problems and how this might be able to help those unable to deal with native modules.
