### ISSUE TITLE
Feature Request: Composite Blend Modes

### ISSUE THREAD

**Issue by wezside** [lovell/sharp#1238]
I had a look and this appears to be available in libvips (issue #657) but not yet in sharp. It is one of the features I feel sharp is lacking that would make it very useful personally. 

     VImage VImage::composite( VImage other, VipsBlendMode mode, VOption *options );

Without having too much knowledge on the library I'd imagine a pseudo method as below could work?

	VImage Blend(VImage image, VImage overlayImage, VipsBlendMode mode) 
	{
		// check for same width + height
		// check for alpha
		return image.composite(overlayImage, mode, VImage::option());
	}

**Comment by lovell** [comment]
Hello, did you see #728?

**Comment by wezside** [comment]
I did but totally forgot about it. Will follow along the other discussion. I do think a single/simple method could be beneficial, even if the multiple overlay references this single/simple method. Feel free to close this.

**Comment by lovell** [comment]
Let's track this at #728, thanks.
