### ISSUE TITLE
Chained rotate().resize() does not resize to specific numbers in some cases

### ISSUE THREAD

**Issue by anahit42** [lovell/sharp#1241]
Hi there,

I have an image with 1920x1280 dimensions and want to rotate it 90 degrees then resize rotated image to 533x800.

Chained  rotate().resize() result is an image that has 533x799 dimensions, whereas when I separate them to different steps, it resizes image correctly.

Here is the code to replicate the issue:

chained case with incorrect 533x799 result: https://gist.github.com/anahit42/d36734aaa3fcaf31f04b29bc630a488e 

separate case with correct 533x800 result: https://gist.github.com/anahit42/b31241e4c21c5dc46da8783000b6bb5c

And some random 1920x1280 image:
https://drive.google.com/file/d/1C9v1LS5U3s6fY4X0qz049HRhXZD_Vg2u/view

Node version: v6.13.1
Sharp version: 0.20.3

**Comment by lovell** [comment]
Hello, thanks for the detailed report, my best guess would be that these specific dimensions are affected by a possible rounding error. I'll be able to take a closer look in a few days.

**Comment by lovell** [comment]
Apologies for the delay, this was due to a bug in sharp and will be fixed in the next release, v0.20.4. Thanks for reporting!

**Comment by anahit42** [comment]
Will be waiting for the new release. Thank you.

**Comment by lovell** [comment]
v0.20.4 now available.
