### ISSUE TITLE
Huge increase in size (progressive vs normal jpeg) image.

### ISSUE THREAD

**Issue by sumit-yadav** [lovell/sharp#1243]
I am resizing my images and making them progressive 

return imageSharpObj.withMetadata()
            .overlayWith(watermark, { gravity: Sharp.gravity.centre })
            .resize(width, height)
            .jpeg({
              quality: 100,
              progressive: true,
              optimizeScans : true
            })
            .toBuffer();

My Concerns are : 

1) There is a huge difference in the size of images ( progressive vs normal jpeg ) which is causing my lambda edge response function to return 502 with error message JSON not parseable as the limit is 1 MB and my image size is crossing that limit even for a 800px width image.

2) While resizing using image magick even for the progressive images the size is lower then normal jpeg generated using sharp.

Please tell me if I am doing something wrong here.

**Comment by sumit-yadav** [comment]
Hi Lovell,

Below are the url's for the same image. One is getting resized using sharp(at lambda edge) and another using php imagick on a normal EC2 instance.

1) Imagick : [](https://image.wedmegood.com/resized-nw/800X/uploads/project/12426/1486116697_sitting_in_dinning_area.jpg)

2) Sharp : [](https://testimage.wedmegood.com/resized-nw/800X/uploads/project/12426/1486116697_sitting_in_dinning_area.jpg)

Both are progressive please look at the size difference first one is of 203 KB and the later one is of 618 KB.

Also if you change the size from 800 to 1000 in the second url it will throw you a lambda JSON parsing error as the size is exceeding from the limit of 1MB.

**Comment by lovell** [comment]
Thanks, the quality and chroma sub-sampling factors are different.

imagick:
```
$ identify -verbose 1486116697_sitting_in_dinning_area.jpg | grep JPEG-
  JPEG-Quality: 94
  JPEG-Colorspace: 2
  JPEG-Colorspace-Name: RGB
  JPEG-Sampling-factors: 2x2,1x1,1x1
```
sharp:
```
$ identify -verbose 1486116697_sitting_in_dinning_area.jpg | grep JPEG-
  JPEG-Quality: 100
  JPEG-Colorspace: 2
  JPEG-Colorspace-Name: RGB
  JPEG-Sampling-factors: 1x1,1x1,1x1
```

Perhaps try the following with sharp to more closely match your imagick logic.
```javascript
.jpeg({
  quality: 94,
  progressive: true,
  chromaSubsampling: '4:2:0'
})
```
