### ISSUE TITLE
How to remove transparent pixels from all edges?

### ISSUE THREAD

**Issue by hellkni9ht** [lovell/sharp#1246]
Hi, 

I have PNG files that contain huge margins around the content, empty spaces that no one wants to see. 
Is there any way to detect and trim transparent pixels from edges without using
`raw()` data? Unfortunately, I didn't find it. Thanks for the help in advance.

**Comment by lovell** [comment]
Hello, did you see the [trim](http://sharp.pixelplumbing.com/en/stable/api-operation/#trim) operation?

**Comment by hellkni9ht** [comment]
Thanks for your response, @lovell 
**The problem was in my code. I have already fixed it. `trim` works perfectly fine.** 

I had the following code: 
```node
// convert .SVG to .PNG
await sharp(input)            
            .resize(width, height)
            .trim()
            .png()            
            .toFile(output);
```
## Input file
![original](https://user-images.githubusercontent.com/1088456/40838816-6fdc86a8-65a8-11e8-88df-e46cd36ff99d.png)

## Espected result
![expected](https://user-images.githubusercontent.com/1088456/40838829-7b046c08-65a8-11e8-8bcb-904a16dfbf8f.png)

## Actual result
![actual](https://user-images.githubusercontent.com/1088456/40838834-807c8e0e-65a8-11e8-922a-ed3d48b2584f.png)
The bottom and top was cutted more than I neded. Bad. But I didn't give up :) 

### I played with code and found a solution. Now it works as expected. 
```node
let buffer = await sharp(input)            
            .resize(width, height)            
            .png()            
            .toBuffer();

        await sharp(buffer)
            .trim()
            .toFile(output);
```
