### ISSUE TITLE
sharp.metadata() returns wrong values

### ISSUE THREAD

**Issue by misantronic** [lovell/sharp#1247]
I load the metadata of an image using

```js
const metadata = await sharp(buffer).metadata();
```

for the attached image, the result is 

```js
...
"width": 1233,
"height": 1773,
...
```

which is wrong. the actual width is 1219px, the height is correct.

![scan-1498206321447_o](https://user-images.githubusercontent.com/6033531/40840303-5be0b996-65a6-11e8-9de1-f11373554b55.jpg)

**Comment by lovell** [comment]
Hello, everything seems OK here with the use of `metadata` with Buffer-based input.

```sh
$ curl -Os https://user-images.githubusercontent.com/6033531/40840303-5be0b996-65a6-11e8-9de1-f11373554b55.jpg
```

```javascript
const fs = require('fs');
const sharp = require('sharp');

const buffer = fs.readFileSync('40840303-5be0b996-65a6-11e8-9de1-f11373554b55.jpg');

sharp(buffer)
  .metadata()
  .then(console.log);
```
Output:
```
{ format: 'jpeg',
  width: 1219,
  height: 1773,
  space: 'srgb',
  channels: 3,
  depth: 'uchar',
  density: 150,
  hasProfile: true,
  hasAlpha: false,
  icc: <Buffer 00 00 22 04 41 50 50 4c 02 20 00 00 6d 6e 74 72 52 47 42 20 58 59 5a 20 07 d6 00 02 00 02 00 02 00 14 00 00 61 63 73 70 41 50 50 4c 00 00 00 00 6e 6f ... > }
```
Is there additional logic in code not shown in your example that could alter `buffer`?

(Unit tests for metadata are in https://github.com/lovell/sharp/blob/master/test/unit/metadata.js should they help.)

**Comment by misantronic** [comment]
ok, thanks for checking that. I did a check as well with the original image and I get the correct metadata.

I have a file-wrapper which is provided by my backend-service which has a `download()`-method where I get the file as `Buffer`. So, there might be a problem.

thanks you!
