### ISSUE TITLE
Composing multiple images generated by Sharp

### ISSUE THREAD

**Issue by Brandoning** [lovell/sharp#1251]
Below is my code that will generate images of cards. It's a snippet of a much larger set of code, but only this section is relevant.

It runs up until "Overlaying suit icon..." that's the last output in the console. After that, "Overlaying card icon..." does not display.

The only way to make it run is to remove .toBuffer from the first promise callback (after Overlaying suit icon).

`return sharp(buff).overlayWith(suitIcon, {
								left: config.get('template.cards.suit-icon.left'),
								top: config.get('template.cards.suit-icon.top')
							}).toBuffer();`

Becomes

`return sharp(buff).overlayWith(suitIcon, {
								left: config.get('template.cards.suit-icon.left'),
								top: config.get('template.cards.suit-icon.top')
							});`

And then needless to say the code after that fails to complete. I've seen many solutions to overlaying multiple images on top of each other on here, many of them years old and actually I struggle to get any of the examples to work.

With promises / etc I am not expert, so any help is appreciated. Please refrain from tearing my code apart I know it is probably horrible.

```
var cardImage = sharp(cardPath + 'card-background.svg')
				.png()
				.toBuffer()
				.then(function(buff){
					// Red
					if( ['heart', 'diamond'].indexOf(cardCombo[card][1]) >= 0 ){
						var suitIcon = cardPath + 'icon-'+cardCombo[card][1]+'.svg';
						var cardIcon = cardPath + 'icn-'+cardCombo[card][0]+'-red.svg';
					}
					// Black
					else {
						var suitIcon = cardPath + 'icon-'+cardCombo[card][1]+'.svg';
						var cardIcon = cardPath + 'icn-'+cardCombo[card][0]+'-black.svg';
					}

					console.log('Overlaying suit icon...');
					return sharp(buff).overlayWith(suitIcon, {
								left: config.get('template.cards.suit-icon.left'),
								top: config.get('template.cards.suit-icon.top')
							}).toBuffer();

					
				}).then(function(buffTwo){
					console.log('Overlaying card icon...');
					console.log(buffTwo.toBuffer());
					return sharp(buffTwo, opts).overlayWith(cardIcon, {
						left: config.get('template.cards.card-icon.left'),
						top: config.get('template.cards.card-icon.top')
					}).png().toFile(finalFilePath + '.png');
				}).then(function(res){
					console.log(res);
				}).catch(err => {
					console.log(err);
				})
```

**Comment by lovell** [comment]
Hello, I can't see anything immediately wrong here, and you'll need to keep the `toBuffer()` call you highlight.

Are you able to create a standalone code sample or repo with input images that consistently produces this problem?

**Comment by Brandoning** [comment]
Hey,

I've uploaded the code to [this repository](https://bitbucket.org/ToneBrandon/image-generator/src/master/). It seems the second nested .toBuffer() works and returns a promise, but that promise is never resolved and is stuck at pending.

Node v10.1.0, have also tried v6

**Comment by Brandoning** [comment]
Update: It seems partly to do with an issue that it's in a loop and doing multiple operations all of the same time I think (approx 15-17k).

How can I prevent this issue? If I trigger all of them at the same time the code is blocked. If I limit to 1 item of the loop it finishes fine and all promises chain together for that 1 operation.

**Comment by Brandoning** [comment]
Andddd apologies but this seems it was from my lack of Node understanding! Or a quirk in the library, not too sure at this point.

Just in case anyone else gets stuck in a similar headache, if you're running a large amount of operations in nested promises (.toBuffers()) it seems it wants to finish all of level 1, before it triggers any promises of level 2.

E.g this section of code (green) will finish for all the items in my loop before the second section (red) starts at all, then all items are looped through as intended from what I can tell.

![screen shot 2018-06-06 at 10 16 35](https://user-images.githubusercontent.com/5629295/41029181-f5c70bda-6972-11e8-8981-b0b61529f1b9.png)

**Comment by lovell** [comment]
Image processing tasks are asynchronous and are queued and processed in the order they call `toBuffer` at a default parallelism of 4.

> "The maximum number of images that can be processed in parallel is limited by libuv's UV_THREADPOOL_SIZE environment variable." http://sharp.pixelplumbing.com/en/stable/api-utility/#concurrency

In this case I recommend introducing flow control to limit the parallelism, perhaps via something like [parallelLimit](https://caolan.github.io/async/docs.html#parallelLimit).

**Comment by xianghu1314** [comment]
you can do it by await/async like this:
`  img=await img.overlayWith(uname, { left:320, top:360 }).toBuffer();
    img=sharp(img);
    img = await img.overlayWith(cardid, { left:320, top:405 }).toBuffer();
    img=sharp(img);`
