### ISSUE TITLE
Weird coloring on greyscale images

### ISSUE THREAD

**Issue by adammenges** [lovell/sharp#1253]
Cropped and resized greyscale images get a weird coloring applied:

![37a17c8a16365be26bc5d5ed2a053e25315dee9b0443e0459def9fd53553e6d0__240](https://user-images.githubusercontent.com/817438/41051624-82623bda-696b-11e8-924a-bd3dd9895861.jpg)

here's the original:

![15723376](https://user-images.githubusercontent.com/817438/41051737-c911c12c-696b-11e8-97eb-99dd8c0acfe6.jpg)

Here's the relivent code:

``` javascript
function convertToRGB(image, metadata, buffer) {
	if (metadata.channels < 3) {
		const channelsToAdd = 3 - metadata.channels;
		let convertedImage = image;
		for (let i = 0; i < channelsToAdd; i++) {
			convertedImage = convertedImage.joinChannel(buffer);
		}
		return convertedImage;
	} else {
		return image;
	}
}

async function scaleImage(url, width, image) {
	// Load the image with sharp.
	const originalImage = sharp(image);
	
	// Get the metadata, which has the size and # channels in the image.
	const metadata = await originalImage.metadata();
	
	// Convert all images to RGB.
	const rgbImage = convertToRGB(originalImage, metadata, image);

	return rgbImage
		.resize(width)
		.withoutEnlargement()
		.rotate()
		.toBuffer();
}
```

This only happens on _some_ greyscale images. Having a hard time figuring out the pattern. For instance this one works just fine:

![12749926](https://user-images.githubusercontent.com/817438/41051950-62d78ae4-696c-11e8-8eab-ec34f645389b.jpg)

Any thoughts?

**Comment by lovell** [comment]
Hello, sharp is already converting to RGB for you so the 2 extra channels lead to what is assumed to be CMYK+A output. This means you should be able to remove the call to your `convertToRGB()` function entirely.

**Comment by adammenges** [comment]
Hum, for some reason I'm still getting it, I'll keep debugging. Lmk if you can think of any other reason. 😄

**Comment by lovell** [comment]
@adammenges Were you able to make any progress with this?

**Comment by adammenges** [comment]
Still experiencing the issue, tried a few things, but moved on to solve it on the backend with `Pillow`. Feel free to close this issue if you'd like. :)
