### ISSUE TITLE
"Error: Input buffer contains unsupported image format" for some remote images

### ISSUE THREAD

**Issue by sitalkio** [lovell/sharp#1255]
```
var resizer = sharp().resize( 300, 300 ).withoutEnlargement().max().toFile( 'public/img_thumbs/' + thumb_name, ( err, info ) =>
{
       console.log( err );
});

request( url ).pipe( resizer );
```

Any idea why I'm getting "Error: Input buffer contains unsupported image format" for remote images like these?

https://scontent.fsof3-1.fna.fbcdn.net/v/t1.0-9/34457169_729308874126794_510102304989380608_n.jpg?_nc_cat=0&oh=fec2a8806865bcbe2009a7a8108f543d&oe=5BAE65A5

https://i.redditmedia.com/xqXYvpuqZNxcLleQ-xQvT09_oLNiUuXi9RHTP6q15r8.jpg?fit=crop&crop=faces%2Centropy&arh=2&w=960&s=86914a55b26ff161fd02d0491f798438

I realize that maybe it's more of a request module issue but I can't figure out how to fix it specifically with sharp, besides the request response.headers['content-type'] returns correctly "image/jpeg".

**Comment by sitalkio** [comment]
I'm realizing now that it's more of a request module issue...

**Comment by lovell** [comment]
Hello, please see #930

**Comment by sitalkio** [comment]
I checked out the request documentation and tried that before posting here, but still no luck with those urls. Code as follows:

```
var resizer = sharp().resize( 300, 300 ).toFile( 'public/imgs/image.jpg', ( err, info ) =>
{
       console.log( err );
});
request( { url, encoding: null } ).pipe( resizer );
```

**Comment by sitalkio** [comment]
I solved it and it was the craziest thing!
Those url strings, coming from html input forms, had url encoded ampersands!

**Comment by jeffminsungkim** [comment]
@pig-cop Could you share how you actually solved it? I'm having the same issue.

**Comment by danielkhan** [comment]
Just in case anyone stumbled over this problem.

I used superagent to pipe the response directly to sharp.
I had the problem that this unhandled error crashed express every time someone uploaded a faulty image. try/catch didn't help.

Here is how I fixed it:
```js
const request = require('superagent');
// ... 
request({url, method: 'GET'}).pipe(transformer).on('error', (e) => {
  console.log(e);
}).pipe(res);
```
This will gracefully handle the error.

**Comment by zbauman3** [comment]
Furthering what @danielkhan wrote: If you clone a sharp stream, you need to add an error event listener to each new clone.

```javascript
const sharpDuplexStream = sharp();

sharpDuplexStream.on('error', (e)=>{
    // handle the error
});

sharpDuplexStream.clone().on('error', (e)=>{
    // sharp.clone() does not clone event listeners, so this must also be handled.
});
```

**Comment by mythicallabs** [comment]
I'm so confused because I'm using express
```
app.get('/photography/photo/:photo', (req, res) => {
    const photo = req.params.photo
    try{
        res.set('Content-Type', 'image/jpeg');
        filepath = path.join(process.cwd(), `/files/photography/photos/${photo}`)
        sharp(fs.readFileSync(filePath)).resize({ width: 100 }).toBuffer().then(data => {
            res.send(data)
        });
    }catch(err){
        res.set('Content-Type', 'text/html')
        deliver404error(req, res, err, 'Back to', 'photography', 'We couldnt find that photo')
    }
})
```
