### ISSUE TITLE
Callback on individual tiles creation

### ISSUE THREAD

**Issue by alvaromartmart** [lovell/sharp#1256]
Hello,

I'm using  `tile` to generate an image pyramid using google/zoomify layout and file output.
Is there any way I can execute some code when *each* output tile is created, instead of waiting for the whole process to be completed?

Thank you!

**Comment by lovell** [comment]
Hello, this is not possible with libvips. Perhaps you could watch for new files arriving in a directory with a tool like [chokidar](https://www.npmjs.com/package/chokidar) (but remember to set its `awaitWriteFinish` option to `true`).

**Comment by alvaromartmart** [comment]
Thank you for the clarification @lovell
