### ISSUE TITLE
What loader should I introduce to make it function properly, there is no error before the introduction

### ISSUE THREAD

**Issue by lololsiyuan** [lovell/sharp#1260]
ERROR in ./~/sharp/package.json
Module parse failed: node_modules/sharp/package.json Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:8)
    at Parser.pp$4.raise (node_modules/acorn/dist/acorn.js:2221:15)

ERROR in  /sharp/build/Release/sharp.node
Module parse failed:/sharp/build/Release/sharp.node Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '�' (1:0)
 @ ./~/sharp/lib/constructor.js 10:14-52

What loader should I introduce to make it function properly, there is no error before the introduction

**Comment by lovell** [comment]
Hello, is this using Webpack? If so, please see #932 and #794.

**Comment by lovell** [comment]
Hopefully this answered your question but please feel free to re-open if not.
