### ISSUE TITLE
Cannot force to use globally installed libvips

### ISSUE THREAD

**Issue by murbanowicz** [lovell/sharp#1262]
Hi,

I have issues running with locally installed libvips so I want to use gloablly installed version.
I put in my `package.json` following line:
```
"config": {
    "libvips": ">=8.6.3"
  }
```

but still when I run my docker image I am always getting `Error: Error loading shared library libresolv.so.2: No such file or directory (needed by /srv/node_modules/sharp/build/Release/../../vendor/lib/librsvg-2.so.2)
:
`

I am developing on Ubuntu 18.04, Node 10. 

Dockerfile:
```
FROM node:10 as builder

COPY package.json yarn.lock /srv/
WORKDIR /srv/
RUN yarn install --pure-lockfile

COPY . /srv

RUN yarn lint
RUN yarn test

FROM node:10-alpine
RUN apk update && apk upgrade
RUN apk add --update \
      --repository http://dl-3.alpinelinux.org/alpine/edge/testing \
      vips-tools \
      && rm -rf /var/cache/apk/*
COPY --from=builder /srv /srv
WORKDIR /srv/

CMD yarn start
```

Any help?

**Comment by lovell** [comment]
Hello, `yarn install` needs to occur on the same platform used at runtime.

In this example, `yarn install` uses Debian/glibc based `node:10` but the runtime uses Alpine/musl based `node:10-alpine`.

**Comment by murbanowicz** [comment]
How to solve it properly? For the builder the stand node should be used I suppose?

**Comment by lovell** [comment]
Yes, use the same base image. This is a relatively complex Dockerfile set-up so I'll assume you have the experience to solve this yourself - good luck!
