### ISSUE TITLE
How to overlayWith new sharp() then how to overlayWith text?

### ISSUE THREAD

**Issue by Antecer** [lovell/sharp#1263]
I find your sample code like this in #512 , but it do not work.
There is no `text `parameter here, it doesn't even exist in the [API documentation](http://sharp.dimens.io/en/stable/api-constructor/)
```javascript
sharp(null, {
    text: {
        text: string,
        font: string,
        width: integer,
        align: string,
        dpi: integer,
        spacing: integer
    }
})...
```

And then i find another sample code in #470 , there is no `create` parameter in overlayWith.
But i can find the `options.create` in your [API documentation](http://sharp.dimens.io/en/stable/api-composite/)
```javascript
sharp('input.jpg')
  .overlayWith(null, create: {
    width: 16,
    height: 32,
    channels: 4,
    background: rgba
})
```

So, did I use the wrong version, or did these features have not yet been developed?
Is there another alternative here? I just want to add a layer of translucent foreground color to the picture and print some text on it.

**Comment by lovell** [comment]
Hello, the API in https://github.com/lovell/sharp/issues/512#issuecomment-239620922 is *proposed*. Please see #512 for suggestions of using SVG as an alternative and subscribe to it for updates.

**Comment by Antecer** [comment]
@lovell 
Thanks for your help, i added the text successfully, but the new question appeared again.
this is my test code:
```js
const titlebar = new Buffer.from(
    `<svg width="1366" height="768">
        <style>
            @font-face {
                font-family: Aller_Light;
                src: url(${Aller_Light_Path}) format('truetype');
            }
        </style>
        <rect x="0" y="0" width="1366" height="768" fill="#000" fill-opacity="0.4"/>
        <rect x="0" y="0" width="1366" height="96" fill="#000" fill-opacity="0.8"/>
        <text class="title" style="font-size: 24; font-family:Aller_Light" x="5" y="22" fill="#FFF">
            Ling Yuan yousa - Shen De Shui Bo Zhu Liu [Pata-Mon's Hard]
        </text>
    </svg>`
);
sharp(Buffer.concat(imgArrayBuffer))
    .toFormat('jpeg')
    .overlayWith(titlebar)
    .toFile(recpath)
    .then(buf => {
        console.log(`[sharpOK]success!`);
    })
    .catch(err => {
        console.log(`[sharpErr]${err}`);
    });
```
I get this error:
`(sharp:6632): Pango-WARNING **: couldn't load font "Aller_Light Not-Rotated 24", falling back to "Sans Not-Rotated 24", expect ugly output.`

How can I successfully load the font？

**Comment by lovell** [comment]
Please see #1162

**Comment by Antecer** [comment]
@lovell 
Sorry, that doesn't seem to help, because I developed on win10 and then deployed to Heroku. 
How do I customize the Fonts folder?
