### ISSUE TITLE
Downloading libvips-8.6.1-win32-x64.tar.gz from github is too slow

### ISSUE THREAD

**Issue by Antecer** [lovell/sharp#1264]
when i install sharp, it tell me will download libvips-8.6.1-win32-x64.tar.gz
but,
Downloading ·libvips-8.6.1-win32-x64.tar.gz· from github is too slow, Is there a way to download it faster?
Every time you update sharp, you have to download it again. This is simply torture.
I think that when this package exists locally, it should not be downloaded again.

For network reasons, I often encounter the following error:
`(node:13036) UnhandledPromiseRejectionWarning: ZlibError: zlib: unexpected end of file`

**Comment by lovell** [comment]
Hello, is this in mainland China? If so, you're not alone - see https://github.com/lovell/sharp-libvips/issues/5

Those files can be self-hosted and configured via the `SHARP_DIST_BASE_URL` environment variable - see http://sharp.pixelplumbing.com/en/stable/install/#pre-compiled-libvips-binaries

**Comment by Antecer** [comment]
Thank you very much. This content is very useful to me
