### ISSUE TITLE
node v10.4.1 compatibility

### ISSUE THREAD

**Issue by qqdaiyu55** [lovell/sharp#1268]
**sharp**: 0.20.4
**node**: 10.4.1
**yarn**: 1.7.0
**electron**: 2.0.2
**OS**: MacOS High Sierra 10.13.2

---

Installation: `yarn add sharp`

Error:
```
Uncaught Error: The module '/Users/ME/Documents/Code/Project/ArtView/node_modules/sharp/build/Release/sharp.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```
And I also tried `npm rebuild sharp`, but it didn't work.

**Comment by lovell** [comment]
The suggestion of running `npm rebuild` after a major version upgrade of Node usually works. Maybe this is an inconsistency between npm vs yarn?

Does running `rm -rf node_modules/sharp && yarn add sharp` fix it?

**Comment by qqdaiyu55** [comment]
Thanks for the suggestion, I tried the command, the same error unluckily

**Comment by qqdaiyu55** [comment]
@lovell I reinstalled the node but the problem still existed. Finally I downgraded to node v8 and use `npm` to install sharp, and it worked. Thanks for the help anyway.

**Comment by ktutnik** [comment]
This issue can be happened if you used nodejs virtual environment (usually used in some hosting) which is uses different nodejs version. You need to enter the virtual environment first than install dependency from there.
