### ISSUE TITLE
Incorrect anchor links on documentation website

### ISSUE THREAD

**Issue by TheDancingCode** [lovell/sharp#1269]
The `Parameters` and `Examples` links in the Table of Contents of most pages on the documentation website point to the wrong heading id. The links contain hyphens and the id's contain underscores. For example, [api-output/#parameters-3](http://sharp.pixelplumbing.com/en/stable/api-output/#parameters-3) should instead point to [api-output/#parameters_3](http://sharp.pixelplumbing.com/en/stable/api-output/#parameters_3).

However, I'd rather adapt the id attributes in this case, and use hyphens in the urls.

**Comment by lovell** [comment]
Hello, JSDoc comments in the source are automagically converted to Markdown by [documentationjs](http://documentation.js.org/) and then converted into HTML by [Read The Docs](https://readthedocs.org/).

The former correctly outputs Markdown with references containing hyphens but it looks like the latter is inconsistently converting these to underscores some of the time. It's probably a bug in either the [recommonmark](https://github.com/rtfd/recommonmark) or [readthedocs](https://github.com/rtfd/readthedocs.org) repo. I had a quick look at the open issues but don't see anything related.

If you're able to isolate the problem further and submit a bug report upstream, that would be great.

**Comment by TheDancingCode** [comment]
I found the source of the problem to be [Python-Markdown](https://github.com/Python-Markdown/markdown/blob/master/markdown/extensions/toc.py#L35) that appends `_1`, `_2`, ... whenever it encounters duplicate headings. So it's not really a bug. Could ask for an option to use hyphens instead.

**Comment by lovell** [comment]
Great detective work, thank you Thomas.

Trying to get all the major Markdown libraries across all languages to agree on how to handle duplicate headers is probably a fool's errand.

Given that Read The Docs already generates its own TOC on the left, I'm not sure how valuable having another TOC at the top of each document is, so a quick fix might be to remove it via `documentation build --markdown-toc=false` - see https://github.com/lovell/sharp/blob/master/package.json#L59

Happy to accept a PR with this change if you're able.
