### ISSUE TITLE
@Types linear missing

### ISSUE THREAD

**Issue by hellraisercenobit** [lovell/sharp#1271]
Image operation "linear" is missing on index.d.ts

**Comment by lovell** [comment]
Hello, it looks like you're using the `@types/sharp` module. This is independent of sharp itself so perhaps you could submit a PR to the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sharp/index.d.ts) repo with this addition.

**Comment by hellraisercenobit** [comment]
Of course i can ;).
What's the min max value for multiplier/offset?

**Comment by hellraisercenobit** [comment]
@lovell Done https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26806
