### ISSUE TITLE
Wrong output when done resize after extend

### ISSUE THREAD

**Issue by 4R53N** [lovell/sharp#1274]
Hi!

I am trying to use the sharp in my app to add white padding to an image if it's aspect ratio is more than 2:1 then resize it to 5000x2500. The issue is it sets the width correct but leaves the height the same value after extend. What am I doing wrong?
```javascript
var padding = ((width/2)-height)/2;
          return image
          .background({r: 255, g: 255, b: 255, alpha: 1})
          .extend({top: padding, bottom: padding, left: 0, right: 0})
          .resize(5000, 2500)
          .toBuffer();
```

**Comment by lovell** [comment]
Hello,  two pipelines are required if you need to `resize` the result of `extend`.

> "This operation will always occur after resizing and extraction, if any."
> http://sharp.pixelplumbing.com/en/stable/api-operation/#extend

Try something like the following (untested):
```javascript
return image
  .background({r: 255, g: 255, b: 255, alpha: 1})
  .extend({top: padding, bottom: padding, left: 0, right: 0})
  .toBuffer()
  .then(data => sharp(data)
    .resize(5000, 2500)
    .toBuffer();
  );
``

**Comment by 4R53N** [comment]
Yeah I did exactly that! It worked. Thanks!
