### ISSUE TITLE
Creating text from SVG will have some noise

### ISSUE THREAD

**Issue by Antecer** [lovell/sharp#1275]
This is my test SVG:
```xml
const title = new Buffer.from(
    `<svg width="800" height="600">
        <text class="h1" x="3" y="${1+17}" font-size="16.92" fill="#FFF">
            Test Coding... This is test text!
        </text>
        <text class="h2" x="3" y="${26+12}" font-size="12.3" fill="#FFF">
            Test Coding... This is test text!
        </text>
        <text class="h3" x="3" y="${45+13}" font-size="12.9" fill="#FFF">
            Test Coding... This is test text!
        </text>
    </svg>`
);
```
This is how i use it:
```js
sharp(title).toFile('./test.jpg');
```
Then i get this image, the text have some noise. How do I make him pure white？
![test](https://user-images.githubusercontent.com/8684916/41911864-6d98ea76-7980-11e8-9372-d7f38aafb6af.JPG)

**Comment by lovell** [comment]
JPEG is a lossy format more suited to photographs. For text-as-an-image a lossless format such as PNG is more appropriate.

**Comment by lovell** [comment]
Please can you attach the unmodified 800x600 PNG output image.

**Comment by Antecer** [comment]
Yes, here it is:
![test](https://user-images.githubusercontent.com/8684916/41946663-2b5149c2-79e6-11e8-9d2d-eeb5a89aba17.png)

**Comment by Antecer** [comment]
@lovell Hello, do you know how to fix this problem?

**Comment by lovell** [comment]
The platform hasn't been mentioned but I'd guess Windows could be responsible for this. Are you able to try reproducing with either Linux or OS X?

**Comment by Antecer** [comment]
On Linux, it looks fine.

**Comment by lovell** [comment]
@Antecer Were you able to make any progress on this?

**Comment by Antecer** [comment]
Sorry, i don't know why it happend on Windows.
Fortunately, this program I developed on Windows, but runs on a Linux server.

**Comment by lovell** [comment]
Thanks for the update, I'll put this down to troublesome font rendering on Windows, for which sharp can do very little to help.
