### ISSUE TITLE
Provide prebuilt releases for older versions

### ISSUE THREAD

**Issue by ivasilov-h4** [lovell/sharp#1278]
Hi,

at our organization we're using an older version of Sharp (specifically 0.17.3) due to using Debian in production, which has an older version of libvips.

How hard would it be to backport the prebuilt releases functionality and publish that as 0.17.4 version?

**Comment by lovell** [comment]
Pre-built binaries for libvips and its dependencies are downloaded by sharp at install time should any globally-installed version of libvips not be recent enough. Do these meet your needs?

**Comment by ivasilov-h4** [comment]
But there aren't any prebuilt binaries for 0.17.3 version of sharp (for MacOS specifically). It always tries to compile sharp during `yarn install`.

Are you saying that there's already prebuilt binaries for older releases?

**Comment by lovell** [comment]
[Prebuilt binaries for sharp](https://github.com/lovell/sharp/releases) and [prebuilt binaries for libvips](https://github.com/lovell/sharp-libvips/releases) are independent.

Have you tried upgrading sharp to the latest version and seeing what happens?

**Comment by lovell** [comment]
By way of example, sharp v0.20.5 requires libvips v8.6.1+. At `npm install` time, if this version of sharp finds a globally-installed libvips v8.4.5, it will be ignored and sharp will download v8.6.1 instead.

You'll see all the install-time decisions relating to detection/download/compilation being logged via npmlog.

**Comment by ivasilov-h4** [comment]
Ok, so in order for us to use in production the globally-installed libvips v8.4.5, we need to set sharp v.0.17.3 in our project. 

When using sharp v.0.17.3 on local machines for development (on MacOS), yarn tries to compile sharp because there aren't any prebuilt binaries for v0.17.3. We're trying to avoid this (because of time, problems during compiling etc).

My original question was: Can we backport and provide prebuilt releases on older versions (specifically 0.17.3)?

**Comment by lovell** [comment]
Using a globally-installed version of libvips means sharp will always compile itself from source as shared libraries can have slightly different APIs and therefore ABIs between versions and can be in different locations. This is true even if a prebuilt sharp is available, so sadly the solution you propose won't help.

> "Sharp will be built from source at install time when... a globally-installed libvips is detected"
> http://sharp.pixelplumbing.com/en/stable/install/#building-from-source

Is there a specific reason you need to use the globally-installed, Debian-packaged libvips v8.4.5?
