### ISSUE TITLE
Most efficient way to chain sharp instances

### ISSUE THREAD

**Issue by biggyspender** [lovell/sharp#1279]
At the moment, in order to (for instance) perform two consecutive resizes on the same image, I am piping sharp instances into one another:

    previousSharpInstance.resize(1000,1000);
    const newSharpInstance = sharp().readSequential(true).resize(64, 64);
    previousSharpInstance.webp({ lossless : true }).pipe(newSharpInstance);

As can be seen, I'm converting to lossless `webp` while we bridge the gap. I wonder if there's a more efficient way of doing this (which also passes metadata from one instance to the next)?

**Comment by lovell** [comment]
Hello, if memory is not of concern then [raw](http://sharp.pixelplumbing.com/en/stable/api-output/#raw) output will avoid a (de)compression round trip, e.g. (untested):

```javascript
sharp(input)
  .resize(1000, 1000)
  .raw()
  .toBuffer({ resolveWithObject: true })
  .then(({ data, info }) => sharp(data, { raw: info })
    .resize(64, 64)
    .toBuffer()
  )
  .catch( ... );
```

**Comment by biggyspender** [comment]
So this would require 4-bytes per pixel to bridge the gap, meaning a 4000 x 4000 image would need a buffer of around ~60mb. This might be a bit on the high side, as we are constrained to about 300-400mb per compute instance and the "graph" of connections might be arbitrarily large. Ideally, I'd like to keep things as sequentially read streams. Does going via webp lossless is still on the table? It would be good if raw could be streamed in this scenario.

**Comment by lovell** [comment]
If memory _is_ of concern then either your suggestion of lossless WebP or PNG will be more suitable.
