### ISSUE TITLE
Enhancement: pass tile depth option to dzsave

### ISSUE THREAD

**Issue by dlong500** [lovell/sharp#1281]
Is there a way to pass other options to the `dzsave` command when writing an image to the DZI format?  I would like to pass the `--depth onetile` option to prevent an excessive number of small (and unused) files from being generated.

**Comment by lovell** [comment]
Hello, the `depth` flag would need to be exposed. Happy to accept and/or help with a PR if you're able. The existing `layout` property of `tile()` can be used as a guide for this.

**Comment by lovell** [comment]
v0.20.6 now available with this feature thanks to @alundavies
