### ISSUE TITLE
 write after end

### ISSUE THREAD

**Issue by danfergo** [lovell/sharp#1284]
I'm trying to use sharp to (max) resize images. But I keep getting an error, am I doing something wrong?

**Error**
```
 write after end
```

**code **
```
 let stream = bucket.openDownloadStream(mongoID); 
 stream = stream.pipe(sharp().resize(900, 900).max())
 stream.pipe(res)
.on('error', responses.handleError(res, 500))
.on('finish', function () {
                res.end()
});
```

**Comment by lovell** [comment]
Hello, the error handler in this code is attached to `res`. Are you sure sharp is causing this? Perhaps the call to `res.end()` is superfluous?

**Comment by lovell** [comment]
@danfergo Were you able to make any progress with this?

**Comment by lovell** [comment]
Feel free to re-open with more details if further help is required.

**Comment by danfergo** [comment]
Hi Lovell,
Sorry for only being replying now, I've been working on other stuff.
I've been now working on this, and I was able to do it by removing the finish handler and creating a temporary variable to hold the sharp transform.
```
const stream = bucket.openDownloadStream(mongoID);
const transform = sharp().resize(900, 900).max();
stream = stream.pipe(transform);
stream.pipe(res)
.on('error', responses.handleError(res, 500))
```
I don't know if babel was doing some optimization replacing the transform with a global constant or something like that, (wierd) but it is working now.

After that, I had also comment **res.set('Content-Length', size)**, else the response would end sooner than the desired and the image would be cut at the bottom.

Great library! :heart:
