### ISSUE TITLE

Xlib: extension "RANDR" missing on display ":99.0".

### ISSUE THREAD

**Issue by Glinkis** [lovell/sharp#1287]
I'm working on an electron app with sharp for image processing, and when I try to run my tests on Travis CI, I get the following error:

```
Xlib: extension "RANDR" missing on display ":99.0".

/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /home/travis/build/Glinkis/reverse-image-finder/node_modules/sharp/build/Release/../../vendor/lib/libpng16.so.16)
```

The tests runs just fine locally on both Windows and OSX.

[Link to the travis log](https://travis-ci.org/Glinkis/reverse-image-finder)

[Link to my repo](https://github.com/Glinkis/reverse-image-finder)

**Comment by lovell** [comment]
Hello, please see #892
