### ISSUE TITLE
font-size scales inversely to dpi

### ISSUE THREAD

**Issue by mike-marcacci** [lovell/sharp#1288]
Please see the [upstream issue on librsvg](https://gitlab.gnome.org/GNOME/librsvg/issues/310). I submitted a fix [in this PR](https://gitlab.gnome.org/GNOME/librsvg/merge_requests/92/diffs).

Once this gets merged, I'd love for it to get it applied here :)

**Comment by lovell** [comment]
sharp v0.21.x provides a prebuilt librsvg with the upstream change mentioned here.

(...but it caused a regression reported at https://github.com/lovell/sharp/issues/1460)

**Comment by mike-marcacci** [comment]
Hmm... interesting. I wonder if there is something platform-dependent here. I will explore upstream and report back.

**Comment by lovell** [comment]
No worries, thanks for providing updates here. The fix is in librsvg v2.44.5+, which sharp v0.22.0+ will provide.
