### ISSUE TITLE
Please add icc profile name to metadata

### ISSUE THREAD

**Issue by homerjam** [lovell/sharp#129]
Hi,

It'd be really useful to have the icc profile name in the metadata object, I've been trying to add it myself but c/c++ is like martian to me I'm afraid : (

Thought I might have been getting somewhere with this:

    const char * p;
    vips_image_get_string(image, VIPS_META_ICC_NAME, &p);

Thanks

**Comment by lovell** [comment]
Commit 321e0f2 on the `knife` branch exposes the raw ICC profile data in the response of the [metadata](https://github.com/lovell/sharp/tree/knife#metadatacallback) method.

This will be included in v0.11.0.

The ICC profile data can then be parsed by the [icc](https://www.npmjs.com/package/icc) module. https://github.com/lovell/sharp/blob/knife/test/unit/metadata.js#L50-L55 provides a good usage example.

**Comment by homerjam** [comment]
Awesome.
