### ISSUE TITLE
Remove alpha channel from png output

### ISSUE THREAD

**Issue by DerTieran** [lovell/sharp#1292]
Hi I try to compose an `icon.png` (with 4 channels) onto a background.
Right now my solution is like this
```js
const icon = sharp('icon.png').resize(size)
sharp({ create: { width, height, background, channels: 4 } })
  .overlayWith(await icon.toBuffer())
  .toFile('output.png')
```

Now I sometimes need to remove the alpha channel from the `output.png`,
I tried using `.flatten()` but the output image still has 4 channels.
It only worked when I also `.flatten()` the `icon` but then I get problems with the overlay.

Is there a solution for this or do I have thought error somewhere?
Thank you for your help.

**Comment by lovell** [comment]
Hello, sharp will flatten before adding the overlay. To flatten after, something like the following should work (untested):

```javascript
const rgbaImage = await sharp({ create: { width, height, background, channels: 4 } })
  .overlayWith(await icon.toBuffer())
  .toBuffer();

sharp(rgbaImage)
  .flatten()
  .toFile('output.png')
```

**Comment by DerTieran** [comment]
Thanks a lot that worked 👍 
I just needed to add `.png()` before converting it to a buffer otherwise I would get the
```
Input buffer contains unsupported image format
```

```js
const icon = sharp('icon.png').resize(size)
const buffer = await sharp({ create: { width, height, background, channels: 4 } })
  .overlayWith(await icon.toBuffer())
  .png()


  sarp.toFile('output.png')
```
