### ISSUE TITLE
sharp hangs on bulk image processing

### ISSUE THREAD

**Issue by arapocket** [lovell/sharp#1293]
I wanted to use sharp to resize large banks of photos (i'm trying with 12,000) and sharp seems to hang after processing a few. 

Any recommendations on how I can proceed?

I couldn't get node's cluster module to work on windows, so perhaps i'll try creating child processes next.

**Comment by lovell** [comment]
Hello, there's no code provided here but if you're using a loop, please remember that due to the async nature of sharp, some kind of flow control may be required. https://github.com/lovell/sharp/issues/1251#issuecomment-395011222 may be relevant.

(Using cluster and child processes will probably be slower.)

**Comment by arapocket** [comment]
I was actually able to get it working fine with require('child_process').fork

P.S. for anyone reading stackoverflow posts about being only able to strings with child.send()
-- do not listen to those idiots you can send objects

**Comment by abh153k** [comment]
@arapocket I am interested to know how you did it with `child_process`. Any hint is really appreciated.

**Comment by arapocket** [comment]
@abh153k 
Here's a snippet of my code

**PARENT**
`
const { fork } = require('child_process');
const fork = require('child_process').fork;
      const program = path.resolve('YOURCHILDPROCESS.js');
      const parameters = [];
      const options = {
        // stdio: [ 'pipe', 'pipe', 'pipe', 'ipc' ]
      };
      const child = fork(program, parameters, options);

      child.on('message', message => {
        console.log('message from child:', message);
        child.send({ files: files, moveFrom: moveFrom });
      });`

**YOURCHILDPROCESS.js**

`
const { fork } = require('child_process');

if (process.send) {
  process.send('child started');
}

process.on('message', message => {
 // DO STUFF HERE
});
`

**Comment by abh153k** [comment]
Thanks I will look into it and post an update.

**Comment by septagram** [comment]
This is a nasty one. Sharp doesn't just hang your current operation. (That would be a no-brainer workaround: just Promise.race with a timeout and retry.) No, it freezes the entire Node process. No other async operations can complete, timeouts and intervals never get called. I've tried the control flow as suggested in the comment referenced above: made sure all operations get called in a queue of my own, to no avail. I would rather not spawn a new process every time I need to clip or resize an image, or just [get its metadata](https://github.com/lovell/sharp/issues/1929).

**Comment by lovell** [comment]
@septagram This is an old issue, plus I note you've added a similar comment on another old issue too. If you're still require help, please open a new issue and provide a complete, minimal, standalone code sample that allows someone else to reproduce.
