### ISSUE TITLE
sharp with multer 

### ISSUE THREAD

**Issue by lonelywoman** [lovell/sharp#1294]
app.post('/upload', function (req, res, next) {
  sharp(req.files['image'].path).resize(200, 200).toBuffer(function (err, buf) {
    if (err) return next(err)

    // Do whatever you want with `buf`
  })
})

i use this example;but not work(i dont get error).If i use toFile works perfectly.

**Comment by lovell** [comment]
Please see https://github.com/expressjs/multer/issues/117#issuecomment-284335699
