### ISSUE TITLE
Incorrect resize ratio

### ISSUE THREAD

**Issue by blowsie** [lovell/sharp#1295]
I resized an image with the following dimensions  `2315x2639 ` with the following configuration.
```
  options: {
          background: {
            r: 255,
            g: 255,
            b: 255,
            a: 1,
          },
          flatten: true,
          resize: [300, null],
          quality: 100,
          trim: 1,
          embed: true,
          rename: '{base}.jpg',
        },
```

The result was an image with dimensions of `300x410`, which looks distrorted:
![image](https://user-images.githubusercontent.com/308572/42626038-2b03e074-85c1-11e8-9740-0d5ba8b66d9b.png)

I used an online calculator to see what the correct dimensions should be for the resize.

![image](https://user-images.githubusercontent.com/308572/42625873-beb465ce-85c0-11e8-85f0-c15215e26658.png)

I manually did this resize using these dimensions in photoshop, and sure enough the image renders without distortion.

How did sharp come to this size? Is it a bug or do I need to change my configuration?

**Comment by lovell** [comment]
Hello, I guess you're using an intermediate library/module. Are you able to reproduce this using sharp only? I suspect it may be the use of trim and resize at the same time causing this.

**Comment by blowsie** [comment]
Closing for now until i complete some tests
