### ISSUE TITLE
Worker Threads: segmentation fault

### ISSUE THREAD

**Issue by DuckerMan** [lovell/sharp#1297]
Hello.

[My Code](https://gist.github.com/DuckerMan/da800b5919e5389f49358245de1c893c)

I run this code in [Worker Threads](https://nodejs.org/api/worker_threads.html).

Arch linux, node 10.5.0, latest sharp

**Comment by DuckerMan** [comment]
[](http://test.ru)

**Comment by lovell** [comment]
https://nodejs.org/api/worker_threads.html#worker_threads_class_worker says:

> "Native addons are not supported yet."

Worker threads are designed for CPU-intensive JavaScript so would be unlikely to help sharp/libvips, which is compiled C/C++, makes effective use of CPUs and is typically I/O bound.

http://sharp.pixelplumbing.com/en/stable/api-utility/#concurrency provides details of the concurrency and parallelism options available.

**Comment by DuckerMan** [comment]
So, sharp dont block event loop?
