### ISSUE TITLE
Fastest way to check if image is processable?

### ISSUE THREAD

**Issue by rexxars** [lovell/sharp#1298]
Hi!

I have a project that receives user-uploaded images, stores them and later resizes requested images on the fly using sharp. Sometimes users upload images that are broken/invalid or not an image at all.

I want to validate that the images uploaded are actually processable (resizable) by sharp before I store them. So far, I've been doing something along the lines of:

```js
const image = sharp(bufferOfImage, {failOnError: true})
const metadata = await image.metadata()
if (!metadata.width || !metadata.height) {
  throw new Error('Could not determine width and height of image')
}
```

This catches most errors, but not all. Sometimes the image is in a shape where the metadata is valid, but where you cannot actually process the content when attempting to resize it.

If I do any resize operation, or even just do a `image.toBuffer({resolveWithObject: true})`  and check that the `info` property is set, the remaining errors are caught as well. This check obviously has a performance penalty, however, and I'd like to minimize it as much as possible. When doing no resizing and simply using `toBuffer()` on a 9MB PNG, the operation takes ~26 seconds, whereas resizing to a 300px wide image takes 366ms.

Do you have any suggestion on what the cheapest/fastest way is to check that the image is processable?

**Comment by lovell** [comment]
To be sure an image is not invalid, all the pixel values will need to be decoded/decompressed.

Perhaps try the [stats](http://sharp.pixelplumbing.com/en/stable/api-input/#stats) operation as that will decode every pixel value with the fewest memory allocations.

**Comment by rexxars** [comment]
Thanks, @lovell - that works like a charm!

**Comment by strarsis** [comment]
@lovell: Very useful information,  thank you!

**Comment by strarsis** [comment]
@lovell: Very useful inform, thank you!

Concerning API stability: The implementation of `stats` could change, becoming more efficient, so it doesn't require to decode all image data. It would be nice to have a dedicated function in the `sharp` API that loads and validates the complete image.
