### ISSUE TITLE
[Question] Gradient and transparent

### ISSUE THREAD

**Issue by z3niths** [lovell/sharp#1299]
## Description
I wanted to create a shadow of an image using
 - Flipped duplicated image + ensure opacity/alpha
 - Transparent Gradient

Now I use overlayWith to make it's transparent but still have some other black dot on the overlay.
```
.overlayWith(new Buffer ([0, 0, 0, 80]), {
                                raw: { width: 1, height: 1, channels: 4 }, tile: true
                            })
```

![image](https://user-images.githubusercontent.com/16873595/42917360-66ed6a2a-8b33-11e8-95d7-fe72ebe6a367.png)

Any example of function/ convolute matrix I can use for it ?
Or I need to wait for #1153

## Expected
I want to have something like this
![image](https://user-images.githubusercontent.com/16873595/42918633-c8dd0614-8b38-11e8-9ea3-469a073d94dd.png)

**Comment by lovell** [comment]
Hello, perhaps experiment with SVG for the transparent gradient as it provides a [linearGradient](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Gradients) element that can have stops with varying opacity.

**Comment by z3niths** [comment]
@lovell and which function I can use to apply the buffer from svg
to replace the alpha channel of my main image buffer.

- overlayWith() ?
- joinChannel() ?

I've tried both of them but still doesnt work. I probably miss something

**Comment by lovell** [comment]
You should be able to directly use `.overlayWith(Buffer.from(svg))` in a single operation.

**Comment by lovell** [comment]
Hope this helped, please re-open with more details if not.
