### ISSUE TITLE
Issue while installing the module on Centos 6 linux system.

### ISSUE THREAD

**Issue by arun-awnics** [lovell/sharp#1300]
I am facing an issue while installing `sharp` on my linux system using npm.

Here is a screen shot of the issue:
![image](https://user-images.githubusercontent.com/25379505/42990302-efd659b8-8c1f-11e8-98d0-8dbd048f68d8.png)

Is there any work around for this?
How do I fix this issue if not?

**Comment by lovell** [comment]
The salient part of this error message is:

> Use with glibc version 2.12 requires manual installation of libvips >= 8.6.1

It looks like you're using RHEL/Centos 6.

> For 32-bit Intel CPUs and older Linux-based operating systems such as Centos 6, it is recommended to install a system-wide installation of libvips from source http://sharp.pixelplumbing.com/en/stable/install/#linux

**Comment by arun-awnics** [comment]
Right... I am using CentOS 6 here.
I have to have a sharp directory to install the additional dependency right?
Or how does it work?

I am trying to install `sharp` individually and I get a new warning here: 

![image](https://user-images.githubusercontent.com/25379505/42991696-fcb1f94a-8c23-11e8-897e-46dcc6b30225.png)

**Comment by arun-awnics** [comment]
I installed **libvips** using this link https://gist.github.com/h2non/89bb2f87c6499d0b25f1. Doesn't seem to work either. I suppose it has installed `7.42 version`. Can you please help?

I still get these errors: 
![image](https://user-images.githubusercontent.com/25379505/43020728-9a8304de-8c7e-11e8-8418-c656161fdbea.png)

![image](https://user-images.githubusercontent.com/25379505/43020738-a5d669c0-8c7e-11e8-97de-7c83d5576fc5.png)

**Comment by lovell** [comment]
http://sharp.pixelplumbing.com/en/stable/install/#building-from-source

> Building from source requires:
> C++11 compatible compiler such as gcc 4.8+, clang 3.0+ or MSVC 2013+

I highly recommend upgrading to Centos 7 if possible as pre-compiled binaries are provided for this newer version.

**Comment by arun-awnics** [comment]
Isn't there any work around for the older versions @lovell apart from upgrading entire OS?

**Comment by lovell** [comment]
https://edwards.sdsu.edu/research/c11-on-centos-6/ might help. Good luck!
