### ISSUE TITLE
Resize webp image from buffer

### ISSUE THREAD

**Issue by a-cabinti** [lovell/sharp#1302]
Hi,

I have webp image from a buffer data and wants to resize using this code below:

sharp(data.Body)
.resize(myObjKey.width, myObjKey.height)
webp({ quality : appConfig.IMAGES_SETTINGS.QUALITY })
.toBuffer()
.then(data => {
  console.log(buffer data);
})

resizer function is successfully executed but when I see the image it crops the the original image according to the provided width and height instead of resizing it.

Is it the original behavior ?

**Comment by lovell** [comment]
Hello, as http://sharp.pixelplumbing.com/en/stable/api-resize/#resize says, by default it will resize and crop.

> "By default, the resized image is centre cropped to the exact size specified."

Perhaps you are looking for the http://sharp.pixelplumbing.com/en/stable/api-resize/#max option?

**Comment by a-cabinti** [comment]
Is there any way to resize only?

I tried all the options and provide it with .max() but it always crop the image.

**Comment by lovell** [comment]
Please can you provide a sample image, standalone code snippet and expected vs actual output.

**Comment by rodrigoalviani** [comment]
This could mantain the aspect ratio:

```javascript
sharp(data.Body)
  .resize(myObjKey.width, myObjKey.height)
  .max()
  .webp({ quality : appConfig.IMAGES_SETTINGS.QUALITY })
  .toBuffer()
  .then(data => {
    console.log(buffer data);
  });
```

**Comment by lovell** [comment]
Hope this helped, please re-open with more details if not.
