### ISSUE TITLE
Error using .overlayWith() on AWS Lambda

### ISSUE THREAD

**Issue by rodrigoalviani** [lovell/sharp#1305]
Im using sharp on AWS Lambda and its woks pretty good, but, when I try to use .quality(), it returns an TypeError, like this:

TypeError: sharp(...).resize(...).crop(...).quality is not a function

What Im doing wrong? Its works great locally.
Im building package at an AMI Ec2 instance (using Jenkins as builder).

**Comment by rodrigoalviani** [comment]
Just realized .overlayWith('image.png', {gravity: 'southwest'}) dont work as well

**Comment by lovell** [comment]
Hello, `quality()` was [deprecated in v0.17.0](http://sharp.pixelplumbing.com/en/stable/changelog/#v0170-11th-december-2016) and [removed in v0.18.0](http://sharp.pixelplumbing.com/en/stable/changelog/#v0180-30th-may-2017).

Please can you provide a code sample where `overlayWith()` is failing to work with `gravity: 'southwest`.

**Comment by rodrigoalviani** [comment]
Ow, I didnt saw quality was removed. I think this is wrong right?

overlayWith example:
`
sharp(buffer)
  .resize(options.w, options.h)
  .crop(options.g)
  .overlayWith('watermark.png', {gravity: 'southwest'})
  .toBuffer()
  .then(data => context.succeed({ isBase64Encoded: true, statusCode: 200, headers: { "Content-Type": contentType }, body: Buffer.from(data, 'base64').toString('base64') }))
  .catch(e => {
    console.log(e + JSON.stringify(url));
    return context.succeed({ isBase64Encoded: false, statusCode: 500, body: e.message })
  });
`

**Comment by lovell** [comment]
Please can you provide a complete code sample using only sharp, without any Lambda boilerplate, and the images that fail.

**Comment by rodrigoalviani** [comment]
Its works great at localhost or ec2 instance... but at lambda I receive this error:
`Input file is missing or of an unsupported image format`

I can mix buffer and file at overlayWith?

```javascript
// https://s3.amazonaws.com/sharp-testing/original.png
// https://s3.amazonaws.com/sharp-testing/wm.png
const aws = require('aws-sdk');
const s3 = new aws.S3({apiVersion: '2006-03-01'});
const sharp = require('sharp');

const params = { Bucket: 'sharp-testing', Key: 'original.jpg' };

s3.getObject(params, function (error, response) {
  if (error) {
    console.log(error);
    return false;
  }

  sharp(response.Body)
    .resize(500, 500)
    .crop()
    .overlayWith('watermarks/wm.png', { gravity: sharp.gravity.southeast })
    .toBuffer()
      .then(data => {
        console.log('done');
      })
      .catch(e => {
        console.log(e);
      });
});
```

**Comment by rodrigoalviani** [comment]
Sorry, just found the error, is because a file permission.

**Comment by Haseeb717** [comment]
@rodrigoalviani which permissions you give to file?
facing same issue

**Comment by rodrigoalviani** [comment]
Worked great with 755
