### ISSUE TITLE
Using Sharp to compress image size without changing aspect ratio of the image

### ISSUE THREAD

**Issue by nizam9** [lovell/sharp#1307]
I have an aws image file and Iam compressing the image using sharp , but after compressing, the file size is increasing hugely . In my case I have an image size of 6.5MB , which after compressing it is becoming 19.5MB.

The following is my code :

`const width = parseInt(image.height);`
 `const height = parseInt(image.width);`

` var getObjectParams = {`
` Bucket: BUCKET,`
  `Key: FILE_NAME`
`}`

 ` s3.getObject(getObjectParams).promise()
    .then(data => {`
      `sharp(data.Body)`
       `.resize(width, height)`
        `.ignoreAspectRatio()`
        `.toFormat('png')`
        `.toBuffer()`
        `.then((buffer) => {`
         ........
         ........
    `}`
   I have even tried using `.max()` ,

 `sharp(data.Body)`
` .withoutEnlargement()`
 `.resize(width, height)`
 `.toFormat('png')`
 `.toBuffer()`

The same issue , file size is increasing . In my case the image aspect ratio should be maintained. Any suggestions would be appreciated. Thanks

**Comment by Algae666** [comment]
Is your input data a JPG or also a PNG?

**Comment by nizam9** [comment]
It depends on the original file type. It can be either png or jpg

**Comment by Algae666** [comment]
If it is a JPG, you should expect converting to a PNG to be larger, if it is a PNG -> PNG, then you have a legitimate issue.

**Comment by nizam9** [comment]
The same issue ocurred when i upload a PNG file and trying to convert it to PNG again

**Comment by Algae666** [comment]
Is the original PNG something that you could share?

**Comment by nizam9** [comment]
Yes , but the PNG file size is 12mb and i cannot upload greather than 10mb here . I will upload the same file in jpg format  which is 6.5 mb
![blue_marble](https://user-images.githubusercontent.com/13588203/43280330-2fb0439c-912e-11e8-834b-3c550ef807c7.jpg)

**Comment by rodrigoalviani** [comment]
Im think its could be because .quality(), did you try it?

**Comment by Pomax** [comment]
Can you give some more information on what you're starting with? What are encoding format, the dimensions, and dpi values that you start with, and what are they after conversion? Also, have you verified this locally (just download the file from AWS) against the latest node + sharp? And if so, what does it do for that same image if you crop it to half a few times? Does it exhibit this "making the image bigger" for all pixel sizes, or does it work fine for small/small-size images but suddenly start blowing up once it passes a certain size threshold?

**Comment by OZZlE** [comment]
@lovell do you know if AWS Lambda supports `mozjpeg`? Or if I can include it somehow otherwise?
