### ISSUE TITLE
FreeBSD: improve installation experience when libvips is not installed

### ISSUE THREAD

**Issue by Bacaaa** [lovell/sharp#1310]
Hi, If I type in my server console npm install sharp I getting error:
`info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.6.1/libvips-8.6.1-freebsd-x64.tar.gz`
If i type in browser link `info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.6.1/libvips-8.6.1-freebsd-x64.tar.gz` I get too error 404, but if I change freebsd to linux in link I can download sharp from browser
Linux Ubuntu server
node -v v6.12.0
npm -v 5.8.0

**Comment by rodrigoalviani** [comment]
You can update your node version to latest LTS version? (v8.11.3 at this time)

**Comment by Bacaaa** [comment]
I have now v8.9.1 but my server work on freeBSD and I dont know how istall sharp. On localserver i work on windowsx64 and eveything work good

**Comment by rodrigoalviani** [comment]
I dont used at freebsd but did you try to install libvips manually?

**Comment by Bacaaa** [comment]
I made npm install -g libvips and this work, then I try install sharp but the same get the same error

**Comment by lovell** [comment]
Please see http://sharp.pixelplumbing.com/en/stable/install/#freebsd

The installation process could be improved to detect FreeBSD and provide a link to the relevant documentation so I'll leave this issue open to track that work (note to self/implementer: add a conditional statement in [here](https://github.com/lovell/sharp/blob/master/install/libvips.js#L30) somewhere).

**Comment by lovell** [comment]
Error messaging for FreeBSD improved in commit bd9f238

**Comment by lovell** [comment]
v0.20.6 now available with improved error messaging for this scenario.
