### ISSUE TITLE
overlayWith creates wrong colour for overlaid image.

### ISSUE THREAD

**Issue by adityapatadia** [lovell/sharp#1311]
I am trying to overlay one PNG over another.

This is the base image: http://www.pngmart.com/files/4/Car-PNG-Transparent.png

and this is the image which I want to overlay: https://vignette.wikia.nocookie.net/fantendo/images/6/6e/Small-mario.png/revision/latest

The Mario image which I am overlaying gets false colours as you can see form this resultant image: https://ibb.co/gt8Sw8

**Comment by zekth** [comment]
The problem here is that your Mario image has some ICC profile incorated in it. Check here:
http://metapicz.com
```
ProfileCMMType | APPL
-- | --
ProfileVersion | 2.4.0
ProfileClass | Display Device Profile
ColorSpaceData | RGB
ProfileConnectionSpace | XYZ
ProfileDateTime | 2011:04:04 15:47:16
ProfileFileSignature | acsp
PrimaryPlatform | Microsoft Corporation
CMMFlags | Not Embedded, Independent
DeviceManufacturer |  
DeviceModel |  
DeviceAttributes | Reflective, Glossy, Positive, Color
RenderingIntent | Perceptual
ConnectionSpaceIlluminant | 0.9642 1 0.82491
ProfileCreator | LOGO
ProfileID | 0
ProfileCopyright | Copyright by LOGO GmbH, Steinfurt
ChromaticAdaptation | 1.04309 0.03181 -0.05273 0.02284 1.00121 -0.02104 -0.00117 -0.0034 0.76315
RedMatrixColumn | 0.43509 0.21826 0.01617
GreenMatrixColumn | 0.39258 0.71776 0.07028
BlueMatrixColumn | 0.13654 0.06398 0.73845
MediaWhitePoint | 0.9642 1 0.82491
Luminance | 113.50124 119.62543 130.01166
RedTRC | (Binary data 14 bytes)
GreenTRC | (Binary data 14 bytes)
BlueTRC | (Binary data 14 bytes)
VideoCardGamma | (Binary data 1584 bytes)
ProfileDescription | CHG_09_110401
```

Which means that what you see when you're previewing it with your browser or even your computer is not the RAW data but the interprated one with the ICC profile. So as far as i know, you're overlaying just with the raw data. Could you provide your code?

**Comment by adityapatadia** [comment]
```javascript
original_image.overlayWith(await overlayImage.png().toBuffer());
```

**Comment by adityapatadia** [comment]
One more observation: If I invert the process overlay car above the Mario, I get same issue with car colors: https://ibb.co/fKyVjT

For your reference, please find ICC profiles read by sharp:

For mario:

```
{ format: 'png',
  width: 1473,
  height: 1854,
  space: 'srgb',
  channels: 4,
  depth: 'uchar',
  density: 350,
  hasProfile: true,
  hasAlpha: true,
  icc:
   <Buffer 00 00 18 dc 41 50 50 4c 02 40 00 00 6d 6e 74 72 52 47 42 20 58 59 5a 20 07 db 00 04 00 04 00 0f 00 2f 00 10 61 63 73 70 4d 53 46 54 00 00 00 00 00 00 ... > }
```

For car: 
```
{ format: 'png',
  width: 2000,
  height: 1312,
  space: 'srgb',
  channels: 4,
  depth: 'uchar',
  density: 72,
  hasProfile: false,
  hasAlpha: true }
```

The car photo does not have any ICC profile in it but its colors are not still not correct when overlaid.

**Comment by zekth** [comment]
Here is a working code for me:
```javascript
const sharp = require("sharp");
const fs = require("fs");
async function main() {
  let car = sharp("car.png");
  let mario = sharp("mario.png");
  await car
    .overlayWith(await mario.resize(200,200).withMetadata().toBuffer())
    .toFile("result.png");
}
main();
```
[result](https://ibb.co/bvacyo)

**Comment by zekth** [comment]
In fact the gamma correction is applied with the ICC profile, so in your case if you import metadatas the correction is applied too.

Note: you're not forced to put .png() if it's already a png file.

**Comment by adityapatadia** [comment]
I already import metadata but I don't write it in final output. I also checked that writing metadata in final output makes no difference. Please also note that not all images have input ICC profile and not doing gamma correction actually makes sharp producing wrong colors. 

A detailed explanation is available here: http://www.ericbrasseur.org/gamma.html

I have listed down everything here so anyone who experiences this in future can take informed decision.

**Comment by zekth** [comment]
Sorry but your overlay is not importing metadata here:

```javascript
original_image.overlayWith(await overlayImage.resize(800,800).max().png().toBuffer())
```
I was meaning importing the metadata of the overlay this way:

```javascript
original_image.overlayWith(await overlayImage.resize(800,800).max().png().withMetadata().toBuffer())
```

**Comment by adityapatadia** [comment]
I meant I tried the code with `.withMetadata()`. 

May be @lovell or @jcupitt can look into this? I feel this issue itself is a testimony to the problem. I think I will leave it open until some library developer looks into this.

**Comment by jcupitt** [comment]
`vips_thumbnail` has an option for linear-light resize:

http://jcupitt.github.io/libvips/API/current/libvips-resample.html#vips-thumbnail

I don't know if sharp exposes this. It'll give much better results than `gamma`. 

The downside is that it's extremely expensive, up to perhaps 10x slower. The biggest slowdown is because it prevents the use of jpeg shrink-on-load, unfortunately. 

Summary: don't use `gamma` for resize, use `linear` instead.

**Comment by adityapatadia** [comment]
I am just trying to understand this. Do you mean to say doing linear resize is "correct" way to resize rather than gamma? I am no expert in this field but this section of this article says something different: 
http://www.ericbrasseur.org/gamma.html#explanation.

**Comment by adityapatadia** [comment]
I was about to add this information (which I just learnt). 

Sharp documentation also says that when applying gamma correction, the library does not take advantage of shrink-on-load feature. They have also written that it first converts to linear scale, performs resize and then again converts to non-linear scale. The documentation is here: http://sharp.dimens.io/en/stable/api-operation/#gamma.

So in fact when we do `.gamma(2.2)` sharp actually applies linear logic which makes output correct. Now this also means that sharp would not be as fast as it claims. Doing approximate resize is super fast with sharp but doing 'correct' resize, sharp can be much slower.

Points by @jcupitt are also excellent. Rather than applying `2.2` factor for all color spaces, Sharp should use different logic for different color spaces. For example, Sharp default output is sRGB colorspace. Converting back from linear to non-linear colorspace with just factor of `2.2` makes output for sRGB inaccurate.

Correct formulas for this are given here: http://www.ericbrasseur.org/gamma.html#formulas. May be there should be separate issue to apply this correctness of formula.

**Comment by adityapatadia** [comment]
@jcupitt Just curious here, what formula does `vips_thumbnail` use to convert to linear scale when there is no ICC profile in input image?

**Comment by adityapatadia** [comment]
I am also curious that if input image is in sRGB and output is also sRGB, why would a resizing done in non-linear space will be wrong and resizing done in linear space is right? [This](http://jcupitt.github.io/libvips/API/current/libvips-resample.html#vips-thumbnail) also states that resizing will be done in sRGB space if `linear` parameter is not specified.

**Comment by adityapatadia** [comment]
To summerise main concern, when overlay image is applied on original image along with gamma correction on original image, the overlay image gets wrong colors. I am keeping this open so someone can look into it.

**Comment by jcupitt** [comment]
libvips has its own sRGB <-> XYZ which implements the correct formula. It obviously won't work for things like CMYK with no profile.

Of course it's for the sharp maintainers, but in my opinion, gamma should only be used for artistic effect. If you want to do gamma-correct resize, use the `linear` flag of `thumbnail`.

Yes, you need to linerarize sRGB images even if the output is also sRGB. Try writing the formula out and you'll see why.

**Comment by adityapatadia** [comment]
Understood. Thanks for your inputs. 👍

**Comment by zekth** [comment]
But @jcupitt could you give me a hint why with rendering the buffer of the overlay image withMetada works and without it doesn't?

Just trying to understand

**Comment by zekth** [comment]
Yes sounds like a gamma issue but as i mentionned in https://github.com/lovell/sharp/issues/1311#issuecomment-408595569 seems like the withMetada() func fix this issue. That's what i'm trying to understand.

**Comment by adityapatadia** [comment]
Just to be clear, withMetadata() has no effect on this. I tried with and without and result was the same.

**Comment by adityapatadia** [comment]
I mentioned in next comment. I was doing `.gamma(2.2)` on original image. I removed that and everything is working fine.

**Comment by zekth** [comment]
This does not answer the question but what ever... Seems like there is a difference of environnement if you've tried the sample i pasted and you haven't the same result.

**Comment by lovell** [comment]
Thanks all, I've created #1317 for adding a `linear` option to the `resize` operation.
