### ISSUE TITLE
Enhancement: Adding parameter to withMetadata

### ISSUE THREAD

**Issue by zekth** [lovell/sharp#1312]
Sharp provides a function to keep or not the metadata which is great but i think it can be improved. In my personnal use i need to keep all the EXIF metadatas but i don't want to keep the date of the picture and the GPS coordinates for example.

An enhancement would be to just keep or not the GPS coordinates for example. Maybe select the tags we want to keep or not.

In metadata.cc i've found
```c++
      if (image.get_typeof(VIPS_META_EXIF_NAME) == VIPS_TYPE_BLOB) {
        size_t exifLength;
        void const *exif = image.get_blob(VIPS_META_EXIF_NAME, &exifLength);
        baton->exif = static_cast<char*>(g_malloc(exifLength));
        memcpy(baton->exif, exif, exifLength);
        baton->exifLength = exifLength;
      }
```
So here in the case of withMetadata is called you copy the part of the file concerning EXIF. But anywhere else there is no mention of those data except for the orientation where i could find this part:

```c++
  /*
    Remove EXIF Orientation from image.
  */
  void RemoveExifOrientation(VImage image) {
    vips_image_remove(image.get_image(), VIPS_META_ORIENTATION);
  }
```

We could imagine a implementation like this: 

```javascript
.withMetadata(exif:{GPS:false,date:false,camera:true})
```

So my question is, would it be cool to develop this feature? I personnaly would enjoy it and can develop it and make a PR. What's your opinion?

**Comment by lovell** [comment]
Hello, did you see #650?

**Comment by zekth** [comment]
@lovell nice reference i haven't seen this. As you say in the referenced topic you'd prefer to use another third party to manipulate the exif datas which could be good if you want to pull another dependency and to set datas and so on. I've used the approach to directly code into the C++ file just to avoid the pull of another dependency and just to keep or not the EXIF datas. Because i don't really think we want to update fields with sharp, just keep or delete them.

But for the case of Piexifjs we have to ensure it supports buffer as an input, because stringify the data into base64 would slow the processing. Do you agree?

In both case i think it's a good idea and i can try to write this improvement.

I think here the choice is yours.

**Comment by lovell** [comment]
I'd prefer to allow people to use whichever EXIF manipulation library they desire and keep the the sharp API simple by accepting only a Buffer.

Let's track this at #650.

As a (shameless plug) aside, if you're concerned about base64 performance then https://github.com/lovell/64 may help (but sharp doesn't need to nor should it depend on that module).
