### ISSUE TITLE
Use text inside svg will cause memory leak

### ISSUE THREAD

**Issue by Shasharoman** [lovell/sharp#1313]
In a scene, I encountered this problem when I used SVG to synthesize text onto an image. 

This is a simplified code:

``` javascript
const sharp = require('sharp');

let count = 0;
setInterval(() => {
    if (++count % 100 === 0) {
        console.log(count, process.memoryUsage());
    }

    sharp(Buffer.from(`
        <svg>
            <text>example</text>
        </svg>
    `)).toBuffer();
}, 100);
```

After 500, 1000, 2000 times：

``` text
500 { rss: 343126016,
  heapTotal: 9256960,
  heapUsed: 7043760,
  external: 44416 }

1000 { rss: 641712128,
  heapTotal: 11354112,
  heapUsed: 8856440,
  external: 95232 }

2000 { rss: 1231851520,
  heapTotal: 12402688,
  heapUsed: 10316248,
  external: 125248 }
```

I guess the underlying code is causing this problem, but I'm not sure, so give you a feedback.

**Comment by lovell** [comment]
Hello, please see #955 (amongst other issues relating to RSS) for why this is unlikely to be a memory leak.

**Comment by Shasharoman** [comment]
Thank you for your reply.

I am not very familiar with the computer foundation. The original scene of this problem is that there is an HTTP interface in an application that uses sharp to synthesize images and text. After each call, the application RSS will grow and never drop, then I call the interface about 200. After that, the entire system (Centos 7.5, Memory: 2GB) is abnormal.

The surface reason I finally located is that svg+text mentioned above, I then changed the implementation method and there is no longer the problem of high RSS.

The new implementation is to convert text to a path representation as follows:

``` javascript
const sharp = require('sharp');

let count = 0;
setInterval(() => {
    if (++count % 100 === 0) {
        console.log(count, process.memoryUsage());
    }

    // The content of path is the letter `o`, get it using opentype.js
    sharp(Buffer.from(`
        <svg>
            <path d = "M13.32 13.46L13.32 13.46Q13.32 16.66 11.68 18.51Q10.04 20.36 7.29 20.36L7.29 20.36Q4.51 20.36 2.88 18.51Q1.24 16.66 1.24 13.46L1.24 13.46Q1.24 10.26 2.88 8.40Q4.51 6.55 7.29 6.55L7.29 6.55Q10.04 6.55 11.68 8.40Q13.32 10.26 13.32 13.46ZM11.05 13.46L11.05 13.46Q11.05 10.92 10.05 9.68Q9.06 8.45 7.29 8.45L7.29 8.45Q5.50 8.45 4.51 9.68Q3.52 10.92 3.52 13.46L3.52 13.46Q3.52 15.92 4.51 17.19Q5.51 18.46 7.29 18.46L7.29 18.46Q9.05 18.46 10.05 17.21Q11.05 15.95 11.05 13.46Z" />
        </svg>
    `)).toBuffer();
}, 100);

```

After 500, 1000, 2000 times：


``` text
500 { rss: 33103872,
  heapTotal: 8732672,
  heapUsed: 5761608,
  external: 16544 }

1000 { rss: 33406976,
  heapTotal: 8732672,
  heapUsed: 6061008,
  external: 42208 }

2000 { rss: 35184640,
  heapTotal: 8732672,
  heapUsed: 6613104,
  external: 68672 }
```

I think that no matter how RSS is defined, it should not cause the system to eventually crash without usable memory. This is why I came here to mention the issue.

**Comment by lovell** [comment]
I'm unable to reproduce this with the latest version of sharp on Linux using the "simplified code" of the first comment.
```
100 { rss: 47820800,
  heapTotal: 8208384,
  heapUsed: 5804256,
  external: 16960 }
500 { rss: 48328704,
  heapTotal: 8732672,
  heapUsed: 6690656,
  external: 36384 }
1000 { rss: 47693824,
  heapTotal: 8732672,
  heapUsed: 5918232,
  external: 25344 }
```
Which platform and versions are you using?

**Comment by Shasharoman** [comment]
I made a big mistake because my production environment is linux, and after a failure I used my own OS X (10.11.6) to locate and debug, and then guessed that using svg+text caused a memory leak.

After reading your last reply, I continued to run "simplified code" on OS X. This time I ran 8000 times and the RSS size was about 4.8G, but this may be because my machine's available memory is too large.

After that I went to the linux environment to run this code, the RSS size is always at 30M-40M, which forced me to think about the whole problem. I then used a complete local environment to test my application, making sure it should be an RSS issue. The last application crash was an exception caused by a shortage of system memory.

After confirming that it is not a memory leak, I should focus on how to optimize RSS. I think the OS X memory leak probability is low and will not be used as a production environment, so this issue should be closed. If you are interested, you can also run "Simplified Code" in the OS X environment.

Thank you very much for providing such a good tool library.
