### ISSUE TITLE
Request: allow TypedArray/ArrayBuffer as input

### ISSUE THREAD

**Issue by IvanSanchez** [lovell/sharp#1315]
Small feature request.

When providing raw image data, sharp currently accepts a `Buffer` as an input. However, I'm most used to work with `Uint8Array`s (and other `TypedArray`s) and `ArrayBuffer`s when dealing with binary data. Having some APIs that return `Uint8Array` as output and some other APIs that only accept `Buffer`s as input is slightly cumbersome.

I would like the constructor to accept any `TypedArray` or `ArrayBuffer` as input, and let sharp perform any conversion into `Buffer` internally.

**Comment by lovell** [comment]
Hello, did you see #1289?

**Comment by IvanSanchez** [comment]
@lovell Yeah, but #1289 that's a different issue - a new option for the constructor. My request is about the constructor allowing a different type for the image data, for [robustness](https://en.wikipedia.org/wiki/Robustness_principle)/convenience.

In other words, my code right now looks like:

```
    var bytes = new Uint8Array(/* stuff */);
    const image = new sharp(Buffer.from(bytes), {
        raw: { width: w, height: h, channels: 4 }
    });
```

And I would like it to look like 

```
    var bytes = new Uint8Array(/* stuff */);
    const image = new sharp(bytes, {
        raw: { width: w, height: h, channels: 4 }
    });
```

Whereas #1289 is asking for something along the lines of

```
    var bytes = new Float32Array(/* stuff */);
    const image = new sharp(Buffer.from(bytes), {
        raw: { width: w, height: h, channels: 4, bitsPerChannel: 32}
    });
```

**Comment by lovell** [comment]
#1289 will probably involve adding `TypedArray` support anyway so the `bitsPerChannel` option you've suggested can instead be implicitly determined from the input type. I'll add a comment to this effect.

**Comment by lovell** [comment]
Tracking this at #1289
