### ISSUE TITLE
Enhancement: provide wideGamut option to process in 16-bit linear colourspace

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#1317]
Proposed API:
```javascript
sharp(input, { wideGamut: true })
  ...
```

This will convert input pixel values to a 16-bit linear colourspace (either RGB16 or scRGB), which has a wider gamut than non-linear sRGB. It will use an embedded input profile, if any, converted via the XYZ connection space.

Setting this to `true` might infer `fastShrinkOnLoad: false` but need to think about that.

The [gamma](http://sharp.pixelplumbing.com/en/stable/api-operation/#gamma) docs need to be updated too.

See #1324 for custom *input* profile support.

See #1323 for custom *output* profile support.

**Comment by uasan** [comment]
Hi.
This function not implemented?
If I understand correctly, in the future it will be able to solve the problem of profile `Display P3`?
https://github.com/lovell/sharp/issues/218#issuecomment-261808262

Thanks.

**Comment by lovell** [comment]
For anyone subscribed to or interested in this feature, I've updated the original description as I think `wideGamut` is what most people are really after, and use of e.g. RGB16 would infer a linear colourspace anyway.

**Comment by lovell** [comment]
v0.29.0 now available with this feature - see https://sharp.pixelplumbing.com/api-colour#pipelinecolourspace
