### ISSUE TITLE
Resize + Crop giving wrong resolution 

### ISSUE THREAD

**Issue by igorescobar** [lovell/sharp#1318]
Hi there,

I'm using sharp `0.20.5`.

I have this image:
![error-image](https://user-images.githubusercontent.com/24032/43575303-6e63a56a-963e-11e8-8484-dd8e8ead3caf.jpg)

Have in mind that this is vertical image, github isn't displaying it correctly.

The transformation steps is as follows, for example:
```
sharp()
  .rotate()
  .resize(300, 200)
  .crop(sharp.gravity.center)
```

Instead of outputting an cropped image with 300x200. It is giving me a 200x300 as you can see here:
![error-output](https://user-images.githubusercontent.com/24032/43575517-e534bfe4-963e-11e8-8b02-709a8bc5ac9d.jpg)

Maybe this is a confusion with the orientation of the image. Seems like the transformation is being made before rotation being fixed.

Am I doing something wrong?

**Comment by lovell** [comment]
This looks very similar to the question you asked in #1194.

The source image has an EXIF orientation of 6 and produces the expected, cropped 300x200 output for me.

**Comment by igorescobar** [comment]
@lovell the question #1194 was about to the rotation that wasn't right and we sorted it out. Now, the rotation is fine but the output is 200x300 instead of 300x200. The code I shared above is a simplified version of the actual implementation... I will try to see if I missed something so you can also reproduce the same.

**Comment by lovell** [comment]
@igorescobar Were you able to solve this?

**Comment by igorescobar** [comment]
@lovell sorry about the delay on this. I will try to write a replication script this weekend.

**Comment by lovell** [comment]
Closing for now but please feel free to re-open with more information if this problem remains.
