### ISSUE TITLE
Blur operation takes a long time for large values

### ISSUE THREAD

**Issue by avaly** [lovell/sharp#1319]
The `blur` operation takes a long time for large values of `sigma`:

See code example at: https://gist.github.com/avaly/159bda86789989d75fd3c0ec94bd55ec

```
$ node benchmark.js 
Without blur: 0.516956388 seconds
With blur: 19.940638111 seconds
```

Compared to `imagemagick`, the same operation is done in less than half the time:

```
$ time convert result-without-blur.jpg -blur 0x120 result-imagemagick.jpg

real	0m8.940s
```

Is there anything that can be done to improve the performance of this operation?

**Comment by lovell** [comment]
`simd(true)` is likely to become the default behaviour soon - see #1213

In addition, a sigma of 120 is pretty big for the 1920x1920 image resolution in the code example. Halving the sigma from 120 to 60 will probably produce very similar output and should be much faster.

**Comment by avaly** [comment]
Sorry, for the late reply. TBH, we haven't given `simd` a try. We reverted to using `imagemagick` for our project.

We could not control/modify the `sigma` value that our consumers requested, so that was not an option for us anyway.
