### ISSUE TITLE
"requires mozjpeg", is this bundled up by default?

### ISSUE THREAD

**Issue by sean256** [lovell/sharp#1321]
I poked around to some previous issues and found that mozjpeg had to be installed separately. Yet when I used one of the 3 options that claim to require mozjpeg the resulting image is different.

So, is mozjpeg included? Or are these options using something else?

**Comment by lovell** [comment]
Hello, mozjpeg is not provided by the pre-compiled binaries. Are you able to provide two code samples that produce different results?

**Comment by lovell** [comment]
Please feel free to re-open with code examples if more help is required.
