### ISSUE TITLE
Feature request: Apply custom filter

### ISSUE THREAD

**Issue by serhiipalash** [lovell/sharp#1327]
Hi @lovell!
Thank you for this fantastic library!

I have one question. Is it possible to apply custom filter like Instagram filters on readable stream in Node.js? I see that CamanJS gives the possibility to do this, but it uses different approach for image processing.

I am not an expert of streams, but if it is be possible, I'd try to do it extending your library.

**Comment by lovell** [comment]
Hello, I've not seen the internals of Caman but "Instagram" style filters are usually implemented via either a recombination matrix (#164) and/or altering brightness/saturation/hue (#609), both of which are future possible enhancements.
