### ISSUE TITLE
svg 2 png with inner png

### ISSUE THREAD

**Issue by Lostbrokenkey** [lovell/sharp#1328]
hi,

is it possible to convert a svg to png with an linked png inside without loosing this inner png image? 
Recently i couldn't find a way to do that.

example svg: 
```
<?xml version="1.0" encoding="utf-8"?>
<svg viewBox="0 0 120 120" height="120" width="120" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">

  <rect x="0" y="0" width="120" height="120" fill="lightgreen"/>

  <!-- this image is not visible on the png output -->
  <image xlink:href="https://upload.wikimedia.org/wikipedia/commons/d/d6/MicroQR_Example.png" x="10" y="10" width="100px"/>

</svg>
```

The result is always just the green rect :/

my code:
```

const sharp = require('sharp');
var fs = require('fs');
let dir = "/Users/my/Desktop/";
let format = 'png';
sharp(dir + "test.svg")
  .resize(100, 100)
  .max()
  .toFormat('png', {
    compressionLevel: 6,
    adaptiveFiltering: false,
    progressive: true,
    optimiseScans: true
  })
  .toBuffer(function(err, data) {
    fs.writeFile(dir+'test2.out.'+format, data, function(err) {
      console.log("The file was saved!");
    })
  });
```

**Comment by Lostbrokenkey** [comment]
I also tried it with data-uri and base64 encoded png, same result...

**Comment by lovell** [comment]
Hello, this looks like OS X. Is `vips` installed via brew or are you relying on the prebuilt binaries that sharp provides?

**Comment by Lostbrokenkey** [comment]
Hi Lovell,

you're right, i'm on Mac. So i installed vips now but the problem persists. 
My goal is to get it working on AWS-Lambda, and it's the same there :/

**Comment by lovell** [comment]
If you want to install `vips` via `brew` then you'll need to explicitly install `gdk-pixbuf` with PNG support first. See https://github.com/lovell/package-libvips-darwin/blob/master/.travis.yml#L8 for how the prebuilt binaries are made.

Inline images within SVG have to be base64 encoded - see https://raw.githubusercontent.com/lovell/sharp/master/test/fixtures/struct-image-04-t.svg for an example from sharp's own test fixtures.

**Comment by Lostbrokenkey** [comment]
I got it working :D :D :D 

Thank your very very much, lovell
