### ISSUE TITLE
issue install sharp on ubuntu 18.04 

### ISSUE THREAD

**Issue by devMagics** [lovell/sharp#1329]
i am missing some thing about this issue
sudo npm install sharp
[sudo] password for cvb: 

> sharp@0.20.5 install /home/cvb/00000_Dev/00_My_Dev_Work/00000000_underDev/tradin_bot/server/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.6.1/libvips-8.6.1-linux-x64.tar.gz
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/home/cvb/00000_Dev/00_My_Dev_Work/00000000_underDev/tradin_bot/server/node_modules/sharp/21904-libvips-8.6.1-linux-x64.tar.gz'
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/cvb/00000_Dev/00_My_Dev_Work/00000000_underDev/tradin_bot/server/node_modules/sharp/build'
gyp ERR! System Linux 4.15.0-30-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/cvb/00000_Dev/00_My_Dev_Work/00000000_underDev/tradin_bot/server/node_modules/sharp
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN winston-daily-rotate-file@1.4.0 requires a peer of winston@2.x but none is installed. You must install peer dependencies yourself.
npm WARN server@1.0.0 No description
npm WARN server@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.20.5 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.20.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cvb/.npm/_logs/2018-08-11T17_15_14_247Z-debug.log

**Comment by lovell** [comment]
Hello, `EACCES: permission denied` suggests this is a local file permission issue. Is the use of `sudo` required?

**Comment by devMagics** [comment]
i did use sudo npm install sharp & install libvips so what i should do ?

**Comment by devMagics** [comment]
i solved it by adding
` --unsafe-perm=true --allow-root `
