### ISSUE TITLE
Strange thresholding behaviour on extractChannel in 2.0.4+

### ISSUE THREAD

**Issue by Pinpickle** [lovell/sharp#1330]
My use-case is extracting the alpha channel from an image and saving it as an alpha matte (greyscale image). When upgrading sharp, previously working code was adding strange artefacts on the boundaries of objects in images. I think this has something to do with the fix for #1257, as it this behaviour started in the version that fix was introduced, and it changes the way `.extractChannel` works.

I think there is some kind of thresholding going on, because aside from jpeg fuzziness, the output image seems to be either 100% white or black. This only happens with some images -- I can't figure out how to reproduce it, this image I had just happened to do it.

# The code and test image

![test_image](https://user-images.githubusercontent.com/3238878/44003807-c4ef9d34-9e50-11e8-8a0c-ae2854f6a63d.png)

``` js
const image = // buffer for image
return sharp(image).extractChannel(3).resize(2000, 2000).jpeg({ quality: 65 }).toBuffer();
```

# In v2.0.3 (expected)

![image](https://user-images.githubusercontent.com/3238878/44003795-b27fbca6-9e50-11e8-9553-d1f7b257fc41.png)

# In v2.0.4/v2.0.5 (actual)

![image](https://user-images.githubusercontent.com/3238878/44003713-6ae19442-9e4f-11e8-97c0-043c4e11a583.png)

## Up close on the artefacts

![image](https://user-images.githubusercontent.com/3238878/44003822-0aeb87a8-9e51-11e8-8417-bbce6742bbe9.png)

**Comment by lovell** [comment]
Hello, the example input image is 16-bit but the greyscale conversion was assuming 8-bit. Commit d705cff adds a test case for this, plus fixes the problem. Thanks for reporting!

**Comment by lovell** [comment]
v0.20.6 now available with this fix.
