### ISSUE TITLE
Resize not working, image getting distorted.

### ISSUE THREAD

**Issue by kushubham9** [lovell/sharp#1332]
Facing this issue on one of my debian machines. An image when resized gets completely distorted. The newly generated image is having the required dimension, but I see no image.

What could possibly go wrong here? 

I do not compile the modules on this server. My project is compiled on a different Debian machine and then the compiled version is deployed on this machine. Is it possible that something is getting missed in the installation process?

**Comment by lovell** [comment]
Hello, please can you provide the (standalone) code and input image that exhibit this behaviour.

**Comment by lovell** [comment]
Thanks, please can you provide the code that generated these images.

**Comment by kushubham9** [comment]
Hi lovell,
I did setup libvips v8.7.0 as per instructions given here https://jcupitt.github.io/libvips/install.html and is using sharp v0.20.4 on this test machine. 
On the compile machine, however, I haven't setup libvips. It is running debian but has a different CPU.

I am not sure how to use these precompiled binary on my test machine. (The configuration part) Couldn't figure out the documentation.

**Comment by lovell** [comment]
My best advice would be to try to reduce the differences between the two machines to help eliminate possible sources of conflict. I would guess this due to an ABI mismatch between different versions of a shared library. Good luck!
