### ISSUE TITLE
Cannot compositing images

### ISSUE THREAD

**Issue by francophongvu** [lovell/sharp#1333]
Hi,

I am trying put an overlay on top of image, my code as below: 

```
var sharp = require("sharp");
var request = require("request").defaults({ encoding: null });

request.get({ url, encoding: null }, function (err, res, body) {
        if (err) {
            reject(err);
        }
        sharp(body)
            .resize(WEB_WIDTH_MAX, WEB_HEIGHT_MAX)
            .overlayWith('./overlay.png', { gravity: sharp.gravity.southeast } )
            .toBuffer()
            .then(function (resizedBuffer) {
                console.log('Resize + overlay image Successfully');
            }).catch(function (error) {
                console.log(error);
                return;
            });
    });
```

> Error: Input file is missing or of an unsupported image format

the 'overlay.png' is placed in the same directory with the running file js, I tried different ways to point to the file, no luck.
Any suggestion is appreciated.

**Comment by lovell** [comment]
Hello, paths are relative to the working directory, which may not be the same as the current directory. The use of absolute paths is recommended.

**Comment by francophongvu** [comment]
Hi, by the way, I use serverless to write the function, my folder structure as image
![folder structure](https://user-images.githubusercontent.com/16016041/44048522-7a97cbf6-9f29-11e8-9d68-5d4d1e404e4f.png)

I tried paths:
"./overlay.png"
"/api/lambda/overlay.png"

Still no luck ...

**Comment by lovell** [comment]
AWS Lambda places code in `/var/task/...`

**Comment by Haseeb717** [comment]
you find its solution?
