### ISSUE TITLE
Saving Base64 format

### ISSUE THREAD

**Issue by sonnyk22** [lovell/sharp#1337]
Excellent library!!!  

Two quick questions.  

   1) Is there a way to `save `a Base64 image in a string variable as a resized image?
   2) are there available option(s) to read an image file (.jpg) and `overriding `it by saving a resized version of it in the same directory path?

Thank you!

**Comment by papandreou** [comment]
1. You can just use [`Buffer#toString`](https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings) and pass `base64`:

```js
const resizedImageBuf = await require('sharp')(pathToMyImage)
  .resize(32, 32)
  .toBuffer();

console.log(`data:image/png;base64,${resizedImageBuf.toString('base64')}`);
// data:image/png;base64,iVBORw0KGgoAAAANS...
```

**Comment by lovell** [comment]
2. When using the filesystem, the output file will be opened and written to before the input file has finished reading and closed, so these cannot be the same.

**Comment by sonnyk22** [comment]
Thank you to you both for helping me on this!

**Comment by sonnyk22** [comment]
One more quick question in relation to the question #1.

Let assume this time I have a Base64 image in a string variable and have already trimmed off the `Content-Type (data:image/png)`. How can I save the content in this variable to a file with the `.resize(32, 32)` function mentioned above?

Thank you!

**Comment by papandreou** [comment]
@sonnyk22, that sounds like a job for [`fs.writeFile`](https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback). Something like:

```js
const writeFileAsync = require('util').promisify(require('fs').writeFile);
const resizedImageBuf = await require('sharp')(pathToMyImage)
  .resize(32, 32)
  .toBuffer();

await writeFileAsync('outputFile.txt', resizedImageBuf.toString('base64'), 'utf-8');
```

**Comment by sonnyk22** [comment]
fantastic!  Another great solution to one of my issue.  Thank you again!

**Comment by GuiRitter** [comment]
> 1. You can just use [`Buffer#toString`](https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings) and pass `base64`:
> 
> ```js
> const resizedImageBuf = await require('sharp')(pathToMyImage)
>   .resize(32, 32)
>   .toBuffer();
> 
> console.log(`data:image/png;base64,${resizedImageBuf.toString('base64')}`);
> // data:image/png;base64,iVBORw0KGgoAAAANS...
> ```
> 
> (you need to match the `Content-Type` with the type of the resulting image, of course)

I was missing this and having to call `.png()` after creating a composite. Thanks!
