### ISSUE TITLE
Unable to open color profiles in electron app.

### ISSUE THREAD

**Issue by Glinkis** [lovell/sharp#1338]
I am struggling with converting color spaces in [my Electron app](https://github.com/Glinkis/reverse-image-finder), due to sharp not finding the icc files in my package.

<img width="547" alt="screen shot 2018-08-15 at 08 16 42" src="https://user-images.githubusercontent.com/8037927/44134128-a7d9c796-a063-11e8-9d28-d8e024c7cdd4.png">

However, if I extract my `app.asar`, the files are in the exact path specified in the error, so I'm not sure why it cannot find them.

**Comment by lovell** [comment]
Hello, did you see #941?
