### ISSUE TITLE
sharp(new Buffer(svg)) throws "corrupt headers" error whenever svg is larger than 10,000,000 bytes

### ISSUE THREAD

**Issue by LilyLauben** [lovell/sharp#1339]
Firstly, thank you for providing this robust and useful library!

We are encountering some difficulty with this piece of code: 

```node
exports.svgToPng = function(svg) {
   return new Promise(async function(resolve, reject) {
   let buffer = Buffer.from(svg);
   console.log(buffer);
   await sharp(buffer)
      .png()
      .toBuffer()
      .then(data => {
         console.log('svgToPng() succeeded');
         return resolve(data);
      }).catch(err => {
         console.log('svgToPng() returned error: ' + err)
         return reject(err.stack);
      });
   });
};
```

We have a set of svg's that we have tested this code against, and it works perfectly on our smaller svgs (less than 5.5MB), but it fails consistently with our larger svgs (larger than 12.5MB), with the error: `Error: Input buffer has corrupt header`.

We have double and triple checked our svg headers, and made sure that there weren't any problems ("<svg" tag was in first 300 characters, nothing crucial missing), and we have found that the headers of the succeeding svgs are identical to those of the failing svgs - the only difference is size.

We have tried manipulating a number of settings, such as changing the sharp cache, altering the density property, adding `.resize()` with various smaller sizes before the `.png()` command. None of these changed the behavior of the code. We even replaced all our sharp commands with:

```node
...
await sharp(buffer)
   .metadata()
   .then(data => {
      console.log(data);
   });
...
```
Still, the behavior was completely unchanged. Large files failed with the corrupt header warning, and smaller files worked just fine.

Our use case is that we have users uploading large dxf or svg files to AWS S3, and we wish to quickly convert them to pngs and upload those pngs back to AWS S3.

**Comment by lovell** [comment]
Hello, are you able to share an example image that fails in this manner?

**Comment by LilyLauben** [comment]
Hello, thank you for the fast reply! 

https://s3.amazonaws.com/roast-floorplans-olive/processing/ORTLIEBSLEVEL2NoBlocks_BIG.-2.svg

This is one of the offending files.

**Comment by lovell** [comment]
Thanks, this file has hit the `XML_PARSE_HUGE` limit for the XML parser used by librsvg, namely 10,000,000 bytes. The limit is there for safety/security purposes and the ability to remove this limit is not currently exposed by libvips. This would require an upstream change to libvips to allow setting the `RSVG_HANDLE_FLAG_UNLIMITED` flag.

From what I can tell, the API provided by librsvg to remove this limit might mean quite a few changes to the way libvips handles SVG files.

**Comment by LilyLauben** [comment]
Ah, that clears some things up! Thank you for the explanation, we just weren't making any headway trying to debug that ourselves. 

We will try to do some optimizations on our svgs, and see if we can't reduce their size, and, failing that, the library svg2png appears to handle the larger files decently. It's a bit of a bummer, because we wanted to use the same library for conversion as we do for handling the resulting pngs, but not an insurmountable problem.

Thanks again!

**Comment by LilyLauben** [comment]
One last question. In trying various alternatives, we considered reading the large svgs into sharp as a stream. Would this bypass the 10,000,000 byte limit?

**Comment by lovell** [comment]
Sadly the use of Stream-based input won't help as librsvg processes files as a whole.

If you've not already tried it, I can recommend [svgcleaner](https://github.com/RazrFalcon/svgcleaner) to losslessly pre-process SVG files. Your original example is now responding with a 403 status so I found a similarly-sized example, which svgcleaner was able to reduce by ~75% using its default settings.

```sh
$ curl -O https://upload.wikimedia.org/wikipedia/commons/1/1b/UK_vehicles_flows_2015.svg

$ vipsheader UK_vehicles_flows_2015.svg
vipsheader: glib: Error domain 1 code 1 on line 252563 column 1 of UK_vehicles_flows_2015.svg: internal error: Huge input lookup

$ svgcleaner UK_vehicles_flows_2015.svg UK_vehicles_flows_2015.clean.svg

$ vipsheader UK_vehicles_flows_2015.clean.svg
UK_vehicles_flows_2015.clean.svg: 1884x2792 uchar, 4 bands, srgb, svgload

$ ls -l UK_vehicles_flows_2015.*
 2594226 UK_vehicles_flows_2015.clean.svg
10654533 UK_vehicles_flows_2015.svg
```

**Comment by LilyLauben** [comment]
Thank you! We were also able to clean up and lighten our svgs, and now they work like a charm.

**Comment by waghanza** [comment]
Hi @lovell,

With the following code and a **jpeg** of `88`**KB**
~~~node
exports.handler = (event, context, callback) => {
  const buffer = Buffer.from(event.body, 'base64');
  sharp(buffer)
    .jpeg(options).toBuffer()
    .then(function (data) {
~~~

I have also a quite similar error
~~~json
{
    "errorMessage": "Input buffer has corrupt header",
    "errorType": "Error",
    "stackTrace": []
}
~~~

Do you have any idea ?

Regards,

**Comment by lovell** [comment]
@waghanza This issue relates to SVG support in sharp. Your issue looks like an unrelated AWS encoding problem. Please open a new issue with an example image and standalone (i.e. no AWS dependency) code sample that produce this behaviour if you're still having problems.

**Comment by lovell** [comment]
Related libvips issue at https://github.com/libvips/libvips/issues/1354

**Comment by lovell** [comment]
The future libvips v8.9.0 will provide an `unlimited` flag that sharp can elect to expose at that point - see https://github.com/libvips/libvips/issues/1354

**Comment by lovell** [comment]
librsvg has recently been reducing its dependence on libxml2, instead (pre)processing XML using Rust, and in newer releases it looks like this problem has pretty much gone away.

For example the following 40MB input file can now happily be processed by the current/latest version of sharp/libvips/librsvg.

https://commons.wikimedia.org/wiki/File:Location_map_San_Francisco_Bay_Area.svg

I'm going to close this as it's unlikely we'll need to expose this librsvg setting and I suspect it will be removed very soon.
