### ISSUE TITLE
Error while trying to run node

### ISSUE THREAD

**Issue by SridharRamasami** [lovell/sharp#1341]
Hi,
I installed sharp by:
npm install sharp

Then when I try to run the nodejs program, I get the following error:

Error: The module '/opt/captivePortal/node_modules/sharp/build/Release/sharp.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:681:18)

What should I do?

Please let me know what further info is needed to narrow down the issue.
Thanks

**Comment by lovell** [comment]
My best guess would be that there are two conflicting versions of Node on this machine.
