### ISSUE TITLE
Support Windows 32-bit

### ISSUE THREAD

**Issue by Tibus** [lovell/sharp#1347]
Hi,

Would like to know why sharp is not available on Windows 32-bit and if it's possible to get it work? 

Thanks

**Comment by lovell** [comment]
Hello, did you see #379?

**Comment by Tibus** [comment]
Yes but not compatible with electronJS

**Comment by lovell** [comment]
64-bit Electron on Windows should be OK, but yes, if you need 32-bit Electron on Windows then you'll have to work that one out for yourself. Good luck!

**Comment by aabuhijleh** [comment]
Hi @lovell, I also need to use 32-bit Electron on Windows. Do you have any suggestions on how to get sharp to work there or if there are other alternatives?

I have tried jimp. It's ok but it's way too slow.
