### ISSUE TITLE
node sharp install in docker on Aarch64 fails  

### ISSUE THREAD

**Issue by ajiratech2** [lovell/sharp#1349]
Platform is ODroid C2 - Amlogic S905 ARMv8 (AARCH64)
I'm trying to install sharp for use with node.js v 8.x. While building docker when use package.json to setup the environment, it completes and includes sharp. But when I do a require('sharp') I get the following error message:

`
Error: /usr/lib/aarch64-linux-gnu/libstdc++.so.6: version 'CXXABI_1.3.9' not found (required by /usr/src/app/node_modules/sharp/build/Release/../../vendor/lib/libvips-cpp.so.42)
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/app/node_modules/sharp/lib/constructor.js:9:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
`

 I tried to install sharp separately again - "RUN npm install sharp" (dockers way of doing it) and it fails and spits out the following error message:

`
Step 6/11 : RUN npm install sharp
 ---> Running in 9143ae79b1ab
npm ERR! path /usr/src/app/node_modules/color-name
npm ERR! code EINVAL
npm ERR! errno -22
npm ERR! syscall rmdir
npm ERR! EINVAL: invalid argument, rmdir '/usr/src/app/node_modules/color-name'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-22T17_46_49_359Z-debug.log
`

I find it odd that sharp wants to remove directory "/usr/src/app/node_modules/color-name" in the first place. Anyhow, I verified that this path it is trying to remove is valid, so I'm not sure why this is failing.

Please advice on how to troubleshoot this ?

**Comment by lovell** [comment]
Hello, it looks like you'll need to install the C++ runtime (this is usually installed by default on most flavours of Linux). On a Debian/Ubuntu based OS then something like the following should work:
```sh
sudo apt-get install libstdc++6
```

**Comment by ajiratech2** [comment]
Thanks lovell.

libstdc++6 is already installed and seems like it is the latest version. (although I don't know how to check the version). Here is output of two commands that should be useful:

```
root@aa8a054c5508:/usr/src/app# apt-get install libstdc++6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libstdc++6 is already the newest version.
libstdc++6 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@aa8a054c5508:/usr/src/app# 
root@aa8a054c5508:/usr/src/app# 
root@aa8a054c5508:/usr/src/app# strings /usr/lib/aarch64-linux-gnu/libstdc++.so.6 | grep CXXABI   
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_1.3.8
CXXABI_TM_1
root@aa8a054c5508:/usr/src/app# 
```

I'm not sure how to install the missing piece that will provide it with version 'CXXABI_1.3.9' we can clearly see from the strings command that it is indeed missing. I'll continue to search, but if you know how to get that installed then please advice. Thanks again.

**Comment by lovell** [comment]
The libvips binaries provided by sharp are compiled inside [a container](https://github.com/lovell/sharp-libvips/blob/master/linux-armv8/Dockerfile) using the `crossbuild-essential-arm64` metapackage on Debian Stretch, which uses gcc 6.3.0. This is the first version of Debian that provides proper arm64 cross-build tooling.

Your best bet is to compile libvips from source yourself using gcc 4, or as you suggest upgrade gcc to 6+ if that's possible.

**Comment by ajiratech2** [comment]
Thanks lovell. I'll need to spend some time figuring out how to do that. I'll report back in a couple of days.

**Comment by lovell** [comment]
https://jcupitt.github.io/libvips/install.html#building-libvips-from-a-source-tarball should help - good luck!
