### ISSUE TITLE
How to use progressive for resize for all formats?

### ISSUE THREAD

**Issue by macktab** [lovell/sharp#1350]
Hello.
I use such code for resizing images:
`
      .then(data => Sharp(data.Body)
        .resize(width,height)
        .jpeg({ progressive: true })
        .toBuffer({
          resolveWithObject: true
        })
      )
`
But it can resize only jpeg images (and this is obvious). But inputs can be also gif and png formats too.
As I read, option for just such code
`
      .then(data => Sharp(data.Body)
        .resize(width,height)
        .progressive()
        .toBuffer({
          resolveWithObject: true
        })
      )
`
is deprecated.
Can somebody advice me something?
(sorry for formatting)

**Comment by lovell** [comment]
Hope this helped.
