### ISSUE TITLE
Crop using aspect ratio instead of dimensions

### ISSUE THREAD

**Issue by habovh** [lovell/sharp#1351]
Hi!

This is probably a feature request, but I might as well be misusing the API.

# The idea

I think it would make a nice addition to the library if we could crop the input image providing an aspect ratio instead of dimensions in pixels.
This would allow to keep the maximum dimension from the original picture while changing its aspect ratio (basically cropping on the longest side's axis of the picture to fit the given ratio).

## The use case

For example, I'm generating a few thumbnails in my app, so I'm currently doing something like this:
```
sharp(imagePath).resize(320,320)
```

However, in some cases the input image is smaller than 320x320px, and I'd like to avoid generating a thumbnail bigger than the original picture, so I'm using the following:

```
sharp(imagePath).withoutEnlargement(true).resize(320,320)

```

### The problem

The problem is, now while it is true the image is no longer enlarged, it is also not cropped as a square in the center.

If an aspect ratio specific method would not be justified, the aspect ratio could also be inferred from the provided resolution in `resize()`.

What do you guys think about the idea?
Or maybe am I missing something and my use case can already be addressed?

Any help/advice/comment appreciated 😃

Jordan

**Comment by habovh** [comment]
@lovell Hi, thanks for replying pretty fast.

Unfortunately, doing so results in the image being scaled down to fit within the specified dimensions and keeping the original aspect ratio. In case the image is smaller than the specified dimensions, the image has the same size as the input.

**Comment by rodrigoalviani** [comment]
You want to scale up your file? You know it will degrade the image, right?

**Comment by habovh** [comment]
That's the thing, I do NOT want to scale up.
I want my picture to be cropped as a square first (1:1 ratio), and then scaled down if bigger than the specified dimensions.

**Comment by rn4391** [comment]
You can maybe read the image metadata before setting up the transformation pipeline. And get the image dimensions from the metadata. If smaller than what you need, then do a 1:1 crop using the `resize` command with the same value for height and width (use the larger of the input height or width). If larger, then do a 1:1 crop using the resize command with h = w = 320.

**Comment by habovh** [comment]
As suggested by @rn4391, I now first read the metadata prior processing the picture. I'm using the code as follows, in case someone has a similar scenario.
However, I still suggest the ability to have a `.aspect()` that would crop automatically using the provided image's dimensions would be welcome.

```js
const ImageTypes = [
  {
    name: 'medium',
    size: 750,
  },
  {
    name: 'sq_sm_2x',
    size: 88,
  },
];

const source = sharp('screenshot.png').rotate();

source
  .metadata()
  .then(({ width, height }) => {
    for (let { name, size, fit } of ImageTypes) {
      // sq_ is the prefix for square images. They always need to be cropped in the center, using 1:1 ratio.
      const adjustedSize = name.startsWith('sq_') ? Math.min(width, height, size) : size
      source
        .resize(adjustedSize, adjustedSize, {
          withoutEnlargement: true,
          fit: name.startsWith('sq_') ? 'cover' : 'inside',
        })
        .jpeg()
        .toFile(`output/${name}.jpg`);
    }
  })
```
