### ISSUE TITLE
How can i remove this black background?

### ISSUE THREAD

**Issue by Crackz** [lovell/sharp#1352]
i have followed this [Answer](https://stackoverflow.com/questions/49712421/overlaying-png-onto-svg-using-sharp?answertab=active#tab-top)

```
    sharp(imgBuffer)
        .resize(128, 128)
        .overlayWith(new Buffer(circleSVG), { cutout: true })
        .toFile(`${dest}/${resizedFileName}`);
```

but I got this ![result](https://www.imageupload.co.uk/images/2018/08/24/ffbd1991-ec97-48c6-976f-30bbe420c4fc_thumbnail.jpg)

how can i remove this black background !

**Comment by lovell** [comment]
Hello, did you see that the StackOverflow example includes a conversion to PNG to preserve transparency?

**Comment by Crackz** [comment]
Sorry for that noobie question  !
idk that The JPEG format does not support transparency 🤦

here is my solution.
```
    await sharp(imgBuffer)
        .resize(128, 128)
        .overlayWith(
            new Buffer('<svg width="128" height="128"><circle cx="64" cy="64" r="64"/></svg>'),
            { cutout: true })
        .toFormat(sharp.format.png)
        .toFile(`${dest}/${resizedFileName}`);
```
