### ISSUE TITLE
Is fastShrinkOnLoad really faster?

### ISSUE THREAD

**Issue by nicholas-littlelives** [lovell/sharp#1356]
I have run multiple tests using two instances with the exact same set up except one has fastShrinkOnLoad option disabled and the one with option disabled is nearly always faster with jpeg images.

In fact the cases where I thought fastShrinkOnLoad would help, i.e. where reduction factor is large, saw the one with option disabled perform noticeably faster. Small factor resizes had almost the same result with some variance due to network flight I believe.

My images are about 2000x2000 perhaps that's why the performance improvement is not kicking in.

**Comment by lovell** [comment]
Hello, are you able to share some sample code, images and, if you're using something like EC2, the instance types that exhibit this behaviour so I can attempt to profile it?

Producing smaller/thumbnail JPEG images with libvips is usually an IO-bound task on the input side, where the `fastShrinkOnLoad` feature will help as it reduces the work libjpeg has to do. Perhaps your scenario is somehow bound on the output side?

**Comment by lovell** [comment]
Feel free to re-open with more information if this problem remains.
