### ISSUE TITLE
Allow floating-point density for arbitrary SVG render size

### ISSUE THREAD

**Issue by aeirola** [lovell/sharp#1357]
First, thanks for an awesome library! I'm using it to create a tool for rendering PNG icons for React Native Android and iOS mobile applications from SVG source files. In general, everything goes smoothly until the SVG source file happens to be the wrong size relative to the desired output size. This of course feels a bit silly for *Scalable* Vector Graphics images.

The proper way to resize vector images with the sharp library seems to be to set the `density` constructor parameter when reading a vector image. Unfortunately the value is an integer, which means that it isn't possible to produce arbitrary sized SVG files. For example, it is not possible to render a 100x100 sized SVG image as a 72px x 72px PNG image. The target density would have to be

desiredOutputSize / inputSize * inputDensity = 100 / 72 * 72 = 51.84

which is an invalid value for the `density` parameter. It produces the error `Error: Invalid density (1 to 2400) 51.84`

The only workarounds I can think of is to either load the SVG initially at a higher resolution and the scale down the resulting raster to the desired size with the `resize` function, or alternatively edit the SVG source `width` and `height` attributes on the fly before passing the file to sharp. Both solutions have their issues, with the first possibly causing resizing artefacts in the resulting image, and the second requiring additional logic to parse XML and handle absolute SVG element dimensions with correct `viewBox` attribute.

Thus, I would like to ask if there is a way to support more flexible SVG resizing in sharp. I guess just passing floating point numbers as the `density` parameter probably won't be a good idea, since it has the possibility of rounding errors. Maybe it would be more appropriate to be able to pass a fixed width or height of the canvas the SVG image should be rendered on. I suppose passing both would be superfluous, since there shouldn't be a need to change the image aspect ratio.

Unfortunately though, it seems that libvips [svgload](http://jcupitt.github.io/libvips/API/current/VipsForeignSave.html#vips-svgload) only seems to support defining the rendered image size using density and scale values. Seems to support floating point numbers though, so maybe sharp could expose that API in some way then to allow a bit more control of the resulting image size.

**Comment by lovell** [comment]
Hello, the `density` parameter in sharp originates from *magick support where only integer values were allowed. As you point out, librsvg rendering can handle floating point values for this parameter so we should at least remove the integer-only limitation.

Happy to accept and/or help with a PR if you're able.

**Comment by aeirola** [comment]
Okay, that seems like a reasonable start for this. I'll make a PR for supporting floating point numbers. Then I can try around and see how well it would work for my use cases. If the rounding errors seem improbable, then this change would probably be enough.

**Comment by aeirola** [comment]
Created a PR for this at https://github.com/lovell/sharp/pull/1362.

**Comment by lovell** [comment]
v0.20.8 now available with your fix, thank you!

**Comment by aeirola** [comment]
Awesome, thanks! Seems to produce correct size images in my test cases. Of course very small or large source images will hit the allowed density range of 1-2400, but that should be a less frequent issue though.
