### ISSUE TITLE
Image transformation with no compression/resizing looses quality

### ISSUE THREAD

**Issue by gargol** [lovell/sharp#1360]
When reading and jpeg image from file and writing it back to a different file without applying any transformations it loses size. Example:
```
sharp('original.jpg').withMetadata().toFile('transformed.jpg');
```
During the tranformation output is following:
```
vips warning: exif: bad exif meta "exif-ifd3-GPSVersionID"
```

The version or sharp that is being used: `v0.20.7`
`file` output:
```
file *.jpg
original.jpg:    JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=16, height=3968, bps=0, width=2976], baseline, precision 8, 2976x3968, frames 3
transformed.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=15, height=3968, bps=0, width=2976], baseline, precision 8, 2976x3968, frames 3
```

The image that is being transformed `original.jpg`:
![original](https://user-images.githubusercontent.com/675397/44801874-8cd77f80-abba-11e8-9782-fbfcb10be2e9.jpg)
Transformed image `transformed.jpg`:
![transformed](https://user-images.githubusercontent.com/675397/44801882-982aab00-abba-11e8-90c0-f9ee92f3c7ab.jpg)
Node versoin: `v8.11.4`
OS: `Ubuntu 18.04`

Is this an expected behavior? What options could be specified to avoid  any transformatios but still use sharp for writing the output file (this is needed due to specifics of wrapper library implementation)?

**Comment by gargol** [comment]
Hey @lovell thanks for the prompt reply and an awesome library! How would I avoid using any kind of compression in this situation? Tried passing `quality: 100` into a constructor, but doesn't seem to prevent compression from kicking in.

**Comment by rodrigoalviani** [comment]
On the mostly cases, 100% quality increases original file size. 95% could be enough.

**Comment by gargol** [comment]
@lovell thanks! that approach worked, but as @rodrigoalviani mentioned it makes the image that is to be processed bigger size than it initially was. The use case for this processing was an image uploader in Ghost (https://github.com/TryGhost/Ghost/pull/9837). Initially, the idea was to allow configuring compression level and metadata stripping, but we decided to go with defaults that sharp uses as they are just the right ones we wanted in place. Because quality/compression configuration is so different between jpeg, png, webp etc. The more granular configuration will be available if users find a need for it eventually. Cheers!
