### ISSUE TITLE
some confusion with the right docker configuration for alpine-base

### ISSUE THREAD

**Issue by dohomi** [lovell/sharp#1361]
Hello

I really like your project an start using it as the base for a small image proxy based on Dockerfile:

https://github.com/lumen-cms/sharp-imageproxy/blob/master/Dockerfile

I have some problem with alpine-base:node-10, I would like to use alpine-base for smaller builds (the current is ~70mb big). So I did some trials to make sharp work with the smaller alpine-base (~20mb) but then I receive compile errors:

https://github.com/lumen-cms/sharp-imageproxy/blob/master/__Dockerfile

Did anybody successful deployed a docker image based on alpine-base? Thanks

**Comment by lovell** [comment]
Hello, are you able to share details of the "compile errors" referred to here?

**Comment by lovell** [comment]
Please see https://github.com/mhart/alpine-node/issues/35

**Comment by dohomi** [comment]
@lovell as sharp is using dynamic imports this means that I can use the non-base builds? 
Do you have any recommended Docker image which is working good with sharp? I am a bit confused why the generated Docker file is ~70 MB which seems a bit too large for an image processor service.

**Comment by lovell** [comment]
If container size is of concern then Docker provides a `--squash` flag that might help. Alternatively you could install libvips from source with only the dependencies needed.

**Comment by dohomi** [comment]
@lovell thanks I will keep that in mind.
