### ISSUE TITLE
toBuffer with webp has empty data

### ISSUE THREAD

**Issue by joehoyle** [lovell/sharp#1363]
This only happens with > 0.17. We recently upgraded to 0.20 and noticed some odd issues when converting PNG images to WebP. I also tested 0.18 and had the same issue there. Essentially `toBuffer` is calling the callback with `err, data, info` but `data` contains the info, and `info` is null. No warnings or other output that I can see. 

Doesn't happen with all, but it does with the attached image:

![reputation-manager-icon](https://user-images.githubusercontent.com/161683/44933800-663f5300-ad38-11e8-82db-6d39d3e8af68.png)

Logging `arguments` from the callback provided to `toBuffer` gives me:

```
{ '0': null,
  '1':
   { format: 'webp',
     width: 150,
     height: 160,
     channels: 4,
     premultiplied: true },
  '2': null }
```
Any ideas on this? If it doesn't ring a bell, I can do some more testing.

**Comment by lovell** [comment]
Are you using `withMetadata()` also? If so, see #1242.

**Comment by joehoyle** [comment]
Ah thanks!
