### ISSUE TITLE
About the ability to gravity an image that is being embded

### ISSUE THREAD

**Issue by campolinabh** [lovell/sharp#1365]
Hi @lovell,

I was reading #542 and I see someone added the support to gravity an image during the embed action, however when I try something like:

`.embed(sharp.gravity.west)` 

... the compiler says "embed" expects no arguments.

I am currently using the last release of Sharp: 

`"sharp": "^0.20.7",`

Would you please advise if I am missing anything or if there's any other way to gravity an image to the left or right when it's being embedded?

Thanks in advance!

Daniel

**Comment by lovell** [comment]
Hello, when you say "compiler", are you referring to TypeScript? If so, you'll need to check the bindings maintained by https://github.com/DefinitelyTyped/DefinitelyTyped are correct.

**Comment by campolinabh** [comment]
Hi Lovell,

Thanks for you response. 

So I found a fork from AzureByte that has this feature. Please access this URL and check like 12:

https://github.com/AzureByte/sharp/blob/feature/embedgravity/test/unit/embed.js

I'd like to avoid using the fork and use your official Sharp release. 

Is there any plan to release this feature?

**Comment by lovell** [comment]
What you need is already merged, documented and supported.
http://sharp.pixelplumbing.com/en/stable/api-resize/#embed

It looks like the independent TypeScript definitions require updating - https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sharp/index.d.ts#L132 - these are external to sharp and maintained in a different repo.

**Comment by campolinabh** [comment]
Sorry, but I have updated the sharp and types to the latest versions and the embed still requires no paramters:


```
"sharp": "^0.20.7",
"@types/sharp": "^0.17.10", 
```

Error:

`.embed(sharp.gravity.west)`

`error TS2554: Expected 0 arguments, but got 1.`

**Comment by lovell** [comment]
The `@types/sharp` module, which is not part of `sharp`, requires a code update so that the function definitions it contains matches that of `sharp`.

You'll need to report this downstream at the https://github.com/DefinitelyTyped/DefinitelyTyped repo.

**Comment by campolinabh** [comment]
Will do that. 

Thanks for all your support sir!

**Comment by campolinabh** [comment]
I will open a new thread on DefinitelyTyped community and report the issue. 

Thanks for all you support Lovell!
