### ISSUE TITLE
Ability to specify libvips config value on install

### ISSUE THREAD

**Issue by joehoyle** [lovell/sharp#1366]
Currently it's not possible to use `npm config` to set the value of `libvips` in https://github.com/lovell/sharp/blob/master/package.json#L115, as the `install` script spawns a new process for `node` in https://github.com/lovell/sharp/blob/master/package.json#L58.

It would be handy if I could run `npm run install --libvips=8.7.0` from this package. I believe I could also run `npm_config_libvips=8.7.0 npm install` in my own project, which means when `sharp` is installed as a dep, it would use the specific libvips version.

**Comment by lovell** [comment]
The prebuilt binaries for libvips and its dependencies are provided to help most of the people most of the time.

Those who want a more recent version of libvips than a given version of sharp has been extensively tested with are able to compile and install it globally themselves.

The `libvips` property to which you refer is not part of the public API of sharp and should be considered an internal configuration variable to aid with detecting a globally-installed libvips of the minimum required version as well as the absolute version it will attempt to download.

**Comment by joehoyle** [comment]
> Those who want a more recent version of libvips than a given version of sharp has been extensively tested with are able to compile and install it globally themselves.

Ah ok, this is mainly what I am trying to do, though in the easiest way possible! Per https://github.com/lovell/sharp/issues/1242 I am just trying get version 8.6.4, but it really seems non-trivial to be able to do that.

For patch version fixes in libvips, it seems the easiest thing to do is just waiting for a bump in `sharp`. I'm not sure if I trust myself enough to compile libvips manually and then somehow ship it with my JS function, without breaking more than the bug I'm looking to fix!

Thanks for the support though, if you happen to have a guide on how to compile libvips for use with sharp, that would be great, but no worries if not!

**Comment by lovell** [comment]
Please see https://jcupitt.github.io/libvips/install.html#building-libvips-from-a-source-tarball

The prebuilt libvips binaries provided by sharp are the product of https://github.com/lovell/sharp-libvips/

**Comment by avisiboni** [comment]
> 

What if, I needed to downgrade the version of libvips for some reason, would it be possible?
