### ISSUE TITLE
How to close the file?

### ISSUE THREAD

**Issue by yyx1111** [lovell/sharp#1367]
sharp('input.jpg')

The file is always locked
Unable to delete
How to close an object?

**Comment by lovell** [comment]
Hello, please see #415

**Comment by yyx1111** [comment]
before  sharp.cache( { files: 0 } );  It doesn't solve the problem
sharp.cache(false);  ok
Thank you for your prompt reply.

**Comment by RichardBradley** [comment]
It would be nice if there were a way to explicitly close the file handle and dealloc the memory, separately from `cache(false)`, which I think isn't exactly the same thing
