### ISSUE TITLE
Segmentation fault using sharp.grayscale

### ISSUE THREAD

**Issue by ralbertazzi** [lovell/sharp#1370]
I have a NodeJS server that needs to return grayscale image buffers by reading them from internal storage. This is the code snippet:

```       
sharp('image.jpeg')
    .grayscale()
    .resize(height, width)       
    .raw()
    .toBuffer()
    .then(data => {
        // Use the data
    })
    .catch(err => console.log(err))
```

However, using the `grayscale` method results in random segmentation faults (but rather frequently: something like 1 out of 5 times):

``` 
Segmentation fault (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 139
npm ERR! nv@2.0.1 start: `node src/server/nv-http.js`
npm ERR! Exit status 139
``` 

- When the segmentation fault happens, neither the `then` or the `catch` methods get called
- Writing `grayscale` before or after the `resize` function doesn't change the problem
- Removing the `grayscale` method automatically solves the problem! (No more segmentation faults)

My configuration: Ubuntu 16.04 LTS on VMWare, node v8.11.3, sharp 0.20.7

**Comment by lovell** [comment]
Hello, did you see #1344?

**Comment by ralbertazzi** [comment]
Thanks a lot! I spent an hour looking to issues but of course I didn't find that one :)
