### ISSUE TITLE
Lambda node6.10, cannot open shared object file

### ISSUE THREAD

**Issue by hareku** [lovell/sharp#1375]
```
"libvips-cpp.so.42: cannot open shared object file: No such file or directory",
```

I caught an error in lambda nodejs6.10

```
rm -rf node_modules
docker run --rm -v "$PWD":/var/task lambci/lambda:build-nodejs6.10 npm install sharp
```

What is the reason for not working?

Thanks.

**Comment by lovell** [comment]
Hello, were there any errors when running `npm install`?

**Comment by lovell** [comment]
Does the latest v0.20.8 exhibit this behaviour also? What are the contents of the `node_modules/sharp/vendor/lib` directory in the zip file you upload to Lambda?

**Comment by lovell** [comment]
What are the contents of the `node_modules/sharp/vendor/lib` directory in the zip file you upload to Lambda?

**Comment by lovell** [comment]
Feel free to re-open with more information if the problem persists.
