### ISSUE TITLE
Overlay circular cropped image

### ISSUE THREAD

**Issue by Silverbug** [lovell/sharp#1376]
Perhaps I'm just not understanding the documentation but I'm wondering if it's possible to overlay a circular cropped image on another one? I haven't been able to figure out how to do it.

I have a source jpg (a users profile picture), which I want to apply a transparent circular crop, and then overlay that onto another image. this new image would be used in emails.

Here's an example of the output I'm looking for.

![agenttest](https://user-images.githubusercontent.com/1179037/45355075-83ff9880-b613-11e8-8a0e-5329fd611572.jpg)

Would really appreciate some direction if possible.

Cheers,

Paul

**Comment by lovell** [comment]
Hello, the [overlayWith](http://sharp.pixelplumbing.com/en/stable/api-composite/#overlaywith) operation should do what you need if you haven't already seen it.

**Comment by Silverbug** [comment]
Yeah I think I stumbled onto an example right after I submitted this question :) Always the way.

Thanks for the quick reply.
