### ISSUE TITLE
NodeJS crashes when processing 50 images simultaneously

### ISSUE THREAD

**Issue by tybenz** [lovell/sharp#138]
50 images at once is usually fine, but every now and then it cause my whole node process to crash.

I understand that what I'm trying to do is intense, but isn't there a way sharp could catch the issue and try again in the event that memory is running out or whatever happens to be causing the crash?

My cache is set to 50mb. Concurrency is default (1).

Any ideas? Or at least a way to get an error message to tell me what's going on?

**Comment by lovell** [comment]
@tybenz Is everything working OK for you now?

**Comment by tybenz** [comment]
It is indeed! Thanks so much for the help!
