### ISSUE TITLE
Input image exceeds pixel limit

### ISSUE THREAD

**Issue by ishitatsuyuki** [lovell/sharp#1381]
libvips is designed to handle any malicious input without crashing, and the same should applies to sharp as well.

Unfortunately, you don't seem to propagate the errors detected in the worker thread.

I see things like:
```
Error: Input image exceeds pixel limit
```
and Node just dies with exit code 1.

**Comment by ishitatsuyuki** [comment]
Yes I know that exists. Removing/widening the limit means you may suffer from DoS, which is a more serious problem. So that's not a solution.

**Comment by ishitatsuyuki** [comment]
And please not edit the title to alter the purpose of this issue. The lack of the error handling is the point.

**Comment by lovell** [comment]
> "Unfortunately, you don't seem to propagate the errors detected in the worker thread."

Are you referring to Node worker threads? If so, please see #1297

**Comment by ishitatsuyuki** [comment]
No, I'm referring to the libuv tasks you spawn.

**Comment by lovell** [comment]
Thanks for confirming, please can you provide a code sample that fails in the manner you describe?

**Comment by ishitatsuyuki** [comment]
After some debugging, I found that `ts-node` was absorbing the cause message (`error` event on stream) and I found the way to fix it. Sorry for the disruption.

**Comment by oleg-koval** [comment]
@ishitatsuyuki can you please share a way you fixed it?

**Comment by ishitatsuyuki** [comment]
Sorry I don't remember anything from 4 years ago. You might want to fiddle with ts-node as the past me said.
