### ISSUE TITLE
Electron 3 symbol lookup error

### ISSUE THREAD

**Issue by ethernomad** [lovell/sharp#1384]
Electron v3.0.0
Chromium v66.0.3359.181
Node v10.2.0
v8 v6.6.346.32

/home/jbrown/dWeb/node_modules/electron/dist/electron --type=renderer --no-sandbox --service-pipe-token=8DB2450E4063849CBC23AE28C938D0B2 --lang=en-GB --app-path=/home/jbrown/dWeb/node_modules/electron/dist/resources/default_app.asar --node-integration=true --webview-tag=true --no-sandbox --num-raster-threads=2 --enable-main-frame-before-activation --enable-compositor-image-animations --service-request-channel-token=8DB2450E4063849CBC23AE28C938D0B2 --renderer-client-id=6 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101: symbol lookup error: /home/jbrown/dWeb/node_modules/sharp/build/Release/sharp.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE

**Comment by lovell** [comment]
Hello, this looks like https://github.com/electron/electron/issues/14167 and https://github.com/electron/libchromiumcontent/pull/570 - was `electron-rebuild` used?

**Comment by ethernomad** [comment]
Thanks - `electron-rebuild` fixed it!

**Comment by kevdotbadger** [comment]
FYI: I inherited a project that had sharp as a devDep (rather than a dep). So I was banging my head against the wall when electron-rebuild didn't work. electron-rebuild only looks for deps, not devDeps.
