### ISSUE TITLE
how can i crop by percentage?

### ISSUE THREAD

**Issue by aryeharmon** [lovell/sharp#1389]
i'd like to slice an image into 2 (bottom half + top half)

**Comment by lovell** [comment]
Hello, if I've understood you correctly, a combination of [metadata](http://sharp.pixelplumbing.com/en/stable/api-input/#metadata) and [extract](http://sharp.pixelplumbing.com/en/stable/api-operation/#extract) should help here, something like (untested):

```javascript
sharp(input)
  .metadata()
  .then(({ width, height }) => {
    const halfHeight = Math.round(height / 2);
    return [
      sharp(input)
        .extract({ top: 0, left: 0, width, height: halfHeight })
        .toBuffer(),
      sharp(input)
        .extract({ top: halfHeight, left: 0, width, height: height - halfHeight })
        .toBuffer()
    ];
  })
  .then(([upper, lower]) => { ... });
```

**Comment by lovell** [comment]
Hope this helped. Feel free to re-open with more details if not.
