### ISSUE TITLE
AWS Node install libvips fails to find binary, fails on build

### ISSUE THREAD

**Issue by jmscraig** [lovell/sharp#1390]
Hello.

Thanks for Sharp!!

I am seeing a deployment problem similar to this issue ( https://github.com/lovell/sharp/issues/1309 ) but did not see any path to resolution via hard searching in google. or in that issue post.    

Deploying latest Rocket.Chat meteor.   
Deployed to yesterday to exact same t2 EC2 instances using current meteor build with no errors

deploying to AWS t2.small Ubuntu 16.0.4  
server updated, installed build-essentials
Node installed via nvm lts/carbon
node v8.12.0
npm v6.4.1 
npm install -g node-gyp node-pre-gyp mkdirp rimraf tar fibers

"npm install"  in the root of the project directory fails with the error below.  /bundle/programs/server 

Then tried  these three and all looks great - no errors
npm install -g sharp
npm install --save --verbose sharp

"npm install"  again with no parameters so attempts to complete the initial install 

> sharp@0.20.3 install /home/ubuntu/bundle/programs/server/npm/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.6.1/libvips-8.6.1-linux-x64.tar.gz
fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
                 ^
Error: EEXIST: file already exists, mkdir '/home/ubuntu/bundle/programs/server/npm/node_modules/sharp/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at WriteStream.<anonymous> (/home/ubuntu/bundle/programs/server/npm/node_modules/sharp/install/libvips.js:61:10)
    at emitNone (events.js:106:13)
    at WriteStream.emit (events.js:208:7)
    at fs.close (fs.js:2095:12)
    at FSReqWrap.oncomplete (fs.js:135:15)
make: Entering directory '/home/ubuntu/bundle/programs/server/npm/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
In file included from ../vendor/include/glib-2.0/glib/galloca.h:32:0,
                 from ../vendor/include/glib-2.0/glib.h:30,
                 from ../vendor/include/glib-2.0/gobject/gbinding.h:28,
                 from ../vendor/include/glib-2.0/glib-object.h:23,
                 from ../vendor/include/vips/vips8:35,
                 from ../src/common.cc:25:
../vendor/include/glib-2.0/glib/gtypes.h:530:53: error: ISO C++ forbids declaration of ‘__declspec’ with no type [-fpermissive]
 #        define GLIB_VAR extern __declspec(dllimport)
                                                     ^
../vendor/include/glib-2.0/glib/gmem.h:361:1: note: in expansion of macro ‘GLIB_VAR’
 GLIB_VAR gboolean g_mem_gc_friendly;
 ^
../vendor/include/glib-2.0/glib/gtypes.h:530:53: warning: ‘__declspec’ initialized and declared ‘extern’
 #        define GLIB_VAR extern __declspec(dllimport)
... etc 

Any advice? 

Thanks!

**Comment by jmscraig** [comment]
In the project directory ran "npm install --verbose 

Ran fine until same errors as above.

At the end of those erorrs printed these.

../vendor/include/glib-2.0/gobject/gparamspecs.h:1160:1: note: in expansion of macro ‘GOBJECT_VAR’
 GOBJECT_VAR GType *g_param_spec_types;
 ^
sharp.target.mk:126: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: *** [Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/home/ubuntu/bundle/programs/server/npm/node_modules/sharp/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-1067-aws
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v8.12.0/bin/node" "/home/ubuntu/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/bundle/programs/server/npm/node_modules/sharp
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm verb lifecycle sharp@0.20.3~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.20.3~install: PATH: /home/ubuntu/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ubuntu/bundle/programs/server/npm/node_modules/sharp/node_modules/.bin:/home/ubuntu/bundle/programs/server/npm/node_modules/.bin:/home/ubuntu/.nvm/versions/node/v8.12.0/bin:/home/ubuntu/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ubuntu/bundle/programs/server/node_modules/.bin:/home/ubuntu/bin:/home/ubuntu/.local/bin:/home/ubuntu/.nvm/versions/node/v8.12.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
npm verb lifecycle sharp@0.20.3~install: CWD: /home/ubuntu/bundle/programs/server/npm/node_modules/sharp
npm info lifecycle sharp@0.20.3~install: Failed to exec install script
npm verb stack Error: sharp@0.20.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/home/ubuntu/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)

**Comment by lovell** [comment]
Hello, from your final comment it looks like there were no installation errors. Is this working for you now? (Avoid global installations via npm unless you absolutely have to.)

**Comment by jmscraig** [comment]
Hello.   Thanks for the reply.   

Thanks for the tip to avoid global installation of sharp when possible.

No, "it" is not working yet.  (Well in reference a phrase from 10 years ago.  ~"That depends on what the definition of 'it' is.")    Ha ha

Yes, the 'Npm install Sharp' runs correctly over and over again.  

Yet each time I run "Meteor build" to execute the Node build processes to complete the application this sharp-libvips errors in the first two posts above (short snips below) occur.

Any advice on the root cause or how to debug the problem?

Thanks,
James

.....................................................
sharp@0.20.3 install /home/ubuntu/bundle/programs/server/npm/node_modules/sharp
(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.6.1/libvips-8.6.1-linux-x64.tar.gz
fs.js:885
return binding.mkdir(pathModule._makeLong(path),
^
Error: EEXIST: file already exists, mkdir '/home/ubuntu/bundle/programs/server/npm/node_modules/sharp/vendor' at Object.fs.mkdirSync (fs.js:885:18)  at WriteStream. (/home/ubuntu/bundle/programs/server/npm/node_modules/sharp/install/libvips.js:61:10)
at emitNone (events.js:106:13)"        

....

./vendor/include/glib-2.0/gobject/gparamspecs.h:1160:1: note: in expansion of macro ‘GOBJECT_VAR’
GOBJECT_VAR GType *g_param_spec_types;
^
sharp.target.mk:126: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: *** [Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/home/ubuntu/bundle/programs/server/npm/node_modules/sharp/build'
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/home/ubuntu/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack at emitTwo (events.js:126:13)
....

**Comment by lovell** [comment]
The installation log is for v0.20.8 but the error log is for v0.20.3. Please can you make sure everything is using the same latest version.

**Comment by jmscraig** [comment]
Thx!

**Comment by lovell** [comment]
Feel free to re-open with more information if the problem persists.
