### ISSUE TITLE
Deprecation notice: move background function to relevant operations, affects embed/extend/flatten

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#1392]
This is advance warning that the [background](http://sharp.pixelplumbing.com/en/stable/api-colour/#background) method will be deprecated in v0.21.0 and instead become separate options of the operations it affects.

### embed

The following:
```javascript
sharp(input)
  .background({
    r: 0,
    g: 255,
    b: 0,
    alpha: 0.1
  })
  .resize(200, 300)
  .embed()
  ...
```
when combined with #1135 will become:
```javascript
sharp(input)
  .resize({
    width: 200,
    height: 300,
    fit: 'contain',
    background: {
      r: 0,
      g: 255,
      b: 0,
      alpha: 0.1
    }
  })
  ...
```

### extend

The following:
```javascript
sharp(input)
  .background({
    r: 255,
    g: 0,
    b: 0,
    alpha: 0.5
  })
  .extend({
    top: 10,
    bottom: 20,
    left: 10,
    right: 10
  })
  ...
```

will become:
```javascript
sharp(input)
  .extend({
    top: 10,
    bottom: 20,
    left: 10,
    right: 10,
    background: {
      r: 255,
      g: 0,
      b: 0,
      alpha: 0.5
    }
  })
  ...
```

### flatten

The following:
```javascript
sharp(input)
  .background('red')
  .flatten()
  ...
```

will become:

```javascript
sharp(input)
  .flatten({
    background: 'red'
  })
  ...
```

**Comment by lovell** [comment]
Commit a648446 deprecates `background` from v0.21.0 (and will be removed in v0.22.0).

**Comment by lovell** [comment]
v0.21.0 now available with this change.

**Comment by rn4391** [comment]
How do we just add a background to a PNG image with transparency - no other transform, just replace the transparency with a color?
