### ISSUE TITLE
Bug: gyp failed with exit code: 1

### ISSUE THREAD

**Issue by JohannBlake** [lovell/sharp#1393]
I get the following error when running npm install sharp:

```
[gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/johann/Work/Dev/Web/Projects/electron/apps/node_modules/sharp
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.17.3 install: `node-gyp rebuild`
npm ERR! Exit status 1](url)
```

**Comment by ChrisLang** [comment]
Also having this issue.

`{lamb} if not defined npm_config_node_gyp (node "C:\Users\chrisl\AppData\Roaming\nvm\v8.11.2\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\chrisl\AppData\Roaming\nvm\v8.11.2\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: self signed certificate in certificate chain
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
gyp ERR! stack     at emitNone (events.js:106:13)
gyp ERR! stack     at TLSSocket.emit (events.js:208:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:639:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\chrisl\\AppData\\Roaming\\nvm\\v8.11.2\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd X:\WorkSpaces\ChrisL\_node\sharp-image-processing\node_modules\sharp
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN @1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.20.8 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.20.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chrisl\AppData\Roaming\npm-cache\_logs\2018-10-02T14_21_38_981Z-debug.log`

**Comment by lovell** [comment]
@ChrisLang Your original, now-edited comment included a different "self signed certificate in certificate chain" error - please see https://github.com/nodejs/node-gyp/issues/695

**Comment by ChrisLang** [comment]
Hi Lovell, Sorry about the comment. Was having issues with formatting for code and got distracted. So all sorted now, but is this the only option "set NODE_TLS_REJECT_UNAUTHORIZED=0" to resolving this issue with node-gyp? Thanks for getting back to me appreciate it.

**Comment by lovell** [comment]
@ChrisLang Please can you open a new issue if this is still a problem.

**Comment by ChrisLang** [comment]
@lovell all sorted
