### ISSUE TITLE
passing a String variable to sharp() as file path input always gives me error

### ISSUE THREAD

**Issue by wobeng** [lovell/sharp#1395]
I'm having a similar issue to [stackoverflow](https://stackoverflow.com/questions/43028257/sharp-constructor-wont-take-a-variable-as-file-path-input-when-try-to-resize-im)

it is quite strange that when passing a String variable to sharp() as file path input always gives me this error -

[Error: Input file is missing or of an unsupported image format]

Anything we are missing?

**Comment by wobeng** [comment]
Hi @lovell 

Thanks for your reply. The path I'm using is /tmp/images.jpg. It's weird.

let path = '/tmp/images.jpg'

sharp('/tmp/images.jpg') works
sharp(path) don't work

when I try the same with jimp, both works

**Comment by lovell** [comment]
jimp is synchronous whereas sharp is asynchronous so my best guess would be that there's logic in your code, not shown here, that is modifying `path` (you could define it as `const` rather than `let` to verify this).

**Comment by lovell** [comment]
I'll assume from your follow-on question #1397 that this is solved.
