### ISSUE TITLE
APPDATA env var handling in WSL/wsltty

### ISSUE THREAD

**Issue by llchan** [lovell/sharp#1396]
When installing sharp under wsltty, there appears to be a `APPDATA=C:\Users\$USER\AppData\Roaming` environment variable that is confusing the installer:
```
error /path/to/package/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments:
Directory: /path/to/package/node_modules/sharp
Output:
ERR! sharp ENOENT: no such file or directory, mkdir 'C:\Users\$USER\AppData\Roaming/npm-cache'
ERR! sharp Please see http://sharp.pixelplumbing.com/page/install
```

Maybe we need an OS check or APPDATA validity check in addition to the environment variable presence?

For now my workaround is to explicitly unset the APPDATA env var. I'm guessing wslbridge passes it through for a specific reason, so this is just a temporary solution.

**Comment by lovell** [comment]
Hello, the logic in sharp to determine the npm cache location is the same as the logic in [prebuild-install](https://github.com/prebuild/prebuild-install/blob/master/util.js#L79) so even if we were to modify sharp you'd run into the same problem later in the installation process.

Given the technologies in this scenario are rather specific, I'd recommend you explicitly provide npm with a cache location via its config before running npm installl

```sh
npm config set cache /path/to/a/writeable/location
npm install
```

This approach will help you when using any other modules that might provide prebuilt binaries and not just sharp.

**Comment by llchan** [comment]
Thanks for the suggestion. I'll use that as a workaround (or just unset APPDATA in my shell since I have no need for it anyways). Just wanted to file it here in case you wanted to handle that case more gracefully.

Feel free to close this if you don't feel it's necessary. The workarounds here should be sufficient for anyone else that searches for this.
