### ISSUE TITLE
when I map data with code, both png and jpeg are converted with a white background though I have a condition to only do that when output ext is  jpeg or jpg

### ISSUE THREAD

**Issue by wobeng** [lovell/sharp#1397]
I'm trying to convert a transparent logo to jpg and png.  As you can see in my code below, I check to see if the file output ext is jpeg or jpg and if it is, it change the background to white and flatten it. 

For some strange reason, when I map data with function, both png and jpeg are converted with a white background though I have a condition to only do that when output ext is  jpeg or jpg

```
let local_file = '/tmp/output/295aadfd-f837-4ffb-b3a0-4a407cca54e0.png'

let data = [[700,
    null,
    'width',
    '/tmp/output/295aadfd-f837-4ffb-b3a0-4a407cca54e0_10',
    'png'],
    [700,
        null,
        'width',
        '/tmp/output/295aadfd-f837-4ffb-b3a0-4a407cca54e0_10',
        'jpg'],
    [1000,
        null,
        'width',
        '/tmp/output/295aadfd-f837-4ffb-b3a0-4a407cca54e0_10',
        'png'],
    [1000,
        null,
        'width',
        '/tmp/output/295aadfd-f837-4ffb-b3a0-4a407cca54e0_10',
        'jpg']]


Promise.all(data.map(convert_image_sharp(local_file))).then(() => {
                    console.log('image convert done');
                });


```

```
function convert_image_sharp(image_path) {
    let image = sharp(image_path);
    return data => image
        .metadata()
        .then(function (metadata) {
            let inputs = beatify_input(data);
            if (inputs['crop']) {
                image.extract(inputs['crop'][0], inputs['crop'][1], inputs['crop'][2], inputs['crop'][3])
            }
            image.resize(inputs['width'], inputs['height']);
            if (['jpg', 'jpeg'].includes(inputs['ext'])){
                console.log(inputs['ext']);
                image.background('white');
                image.flatten();
            }
            return image.toFile(inputs['write_path']);
        })

}

```

**Comment by lovell** [comment]
Hello, it's unclear what `data` refers to in the `convert_image_sharp` function. Are you able to provide a standalone, working code sample?

**Comment by wobeng** [comment]
Hi @lovell I updated what data is

**Comment by lovell** [comment]
The shared `image` instance is being mutated by each function invocation. You'll need to move the `sharp(image_path)` constructor into the anonymous function returned by `convert_image_sharp` to create a new sharp instance per function invocation.

```diff
function convert_image_sharp(image_path) {
-    let image = sharp(image_path) ;
-    return data => image
+    return data => sharp(image_path)
        .metadata()
```

**Comment by lovell** [comment]
The code sample provided doesn't appear to use `metadata` as provided by the call to `metadata()` so I'm not sure I understand what is needed. This might be more of a question for StackOverflow.

**Comment by lovell** [comment]
Here's a possible (untested) version of `convert_image_sharp` that should behave in a way that I have understood your `data.map` logic to expect.
```javascript
function convert_image_sharp(image_path) {
  return () => {
    const image = sharp(image_path);
    const { crop, ext, width, height, write_path } = beatify_input(data);
    if (crop) {
      image.extract(...crop);
    }
    image.resize(width, height);
    if (['jpg', 'jpeg'].includes(ext)) {
      image.background('white').flatten();
    }
    return image.toFile(write_path);
  };
}
```
This question is not really specific to sharp and is more of a general JavaScript coding question suited to a site such as StackOverflow.

**Comment by wobeng** [comment]
Got it,,,
 forgive me...I had to learn node js within 48 hours
