### ISSUE TITLE
Sharp insside for loop

### ISSUE THREAD

**Issue by a-cabinti** [lovell/sharp#1400]
Hi there,

I used sharp to convert multiple images to a webp format. My solution is to put my sharp method inside a for loop that calls the image every loop.

My code is like this:

for(let i = 0; i < images.length; i++){
      let  file = images[i].img;

      sharp(file.buffer)
      .webp({ quality : appConfig.IMAGES_SETTINGS.QUALITY })
     .toBuffer()
     .then(data => {
           console.log('Success conversion to webp image');
           s3.putObject({
               Bucket  : appConfig.aws.s3.bucket,
               Key : fileKey,
              Body  : data
           }, (err, data) => {
                if(err){
                     console.log(err);
                     return; 
                }
               console.log(`Successfully uploaded '${fileKey}'!`);
           });
      })
     .catch(err => {
            console.log('Error',err);
      });
}

I just want to know the best practice to do this. Thank you so much for your comments!

**Comment by Odrin** [comment]
It's not about sharp, but about promises generally. This code is 'ok', but can be much readable and structured after some refactoring ([async/await](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/async_function) and decomposition);

**Comment by lovell** [comment]
Hello, this question about asynchronous coding style is probably better suited to StackOverflow or similar.

**Comment by charleslouis** [comment]
@a-cabinti did you solve it ?

How ?

We face a similar issue using Sharp inside a loop.
