### ISSUE TITLE
An issue piping to a readStream.

### ISSUE THREAD

**Issue by nicroto** [lovell/sharp#1404]
Hi,

First of all - thanks for the amazing tool.

@lovell can you help me figure out why this doesn't work, please?

```javascript
  const imageProcessor = sharp();
  imageProcessor
    .on("info", function (metadata) {
      var width = Math.min (1080, metadata.width),
        height = (width / metadata.width) * metadata.height,
        resizeArgs = {
          width: width,
          height: height,
          fit: sharp.fit.cover,
          position: sharp.strategy.entropy
        };
      console.log (`Resizing image with opts: ${JSON.stringify (resizeArgs, null, 4)}`);

      return sharp ()
        .rotate ()
        .resize (null, null, resizeArgs)
        .jpeg();
    });

  var readableStream = fs.createReadStream(stream.path)
    .pipe (imageProcessor);
```

I want to
 - rotate to proper orientation (stripping the EXIF tag);
 - resizing to maximum 1080px-wide image and keep the original size if the width is smaller than that (while keeping the aspect ratio);
 - and encode as jpeg.

When doing this same thing without the metadata - it works like a charm. But since there is no max-width setting, I need to conditionally resize according to size and when I try to use the metadata somehow the image gets smaller in size, but doesn't get rotated or resized to new dimensions...

**Comment by nicroto** [comment]
OK, I discovered `withoutEnlargement` and this worked for me:

```javascript
        const imageProcessor =
          sharp()
            .rotate ()
            .resize (1080, null, {
              fit: sharp.fit.cover,
              position: sharp.strategy.entropy,
              withoutEnlargement: true
            })
            .jpeg();
```

Still interested to know why didn't the first thing worked out, though.

**Comment by lovell** [comment]
Hello, the logic in `function (metadata) { ... }` is (correctly) ignored.

> "Any values returned by the called listeners are ignored and will be discarded."
> https://nodejs.org/api/events.html#events_events

**Comment by nicroto** [comment]
OK. How do I implement it then? (resizing with context taken from the metadata)

**Comment by lovell** [comment]
Please see #236 for a possible future enhancement that would allow this.

**Comment by nicroto** [comment]
Thanks for the help, @lovell. Cheers!
