### ISSUE TITLE
sharp installation fails - Synology

### ISSUE THREAD

**Issue by Korte68** [lovell/sharp#1405]

**Comment by lovell** [comment]
The first error is `Cannot find module 'core-util-is'` so it looks like something went wrong whilst installing the dependencies of sharp, perhaps a temporary network problem.

```sh
npm cache clean --force
npm install sharp --force
```

**Comment by Korte68** [comment]
Tried it.

root@Syno412:/volume1/web/mokavar.hu# sudo npm install sharp --force
npm WARN using --force I sure hope you know what you are doing.

> sharp@0.20.8 install /volume1/web/mokavar.hu/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /root/.npm/_libvips/libvips-8.6.1-linux-x64.tar.gz
prebuild-install WARN install /lib/libz.so.1: version `ZLIB_1.2.9' not found (required by /volume1/web/mokavar.hu/node_modules/sharp/build/Release/../../vendor/lib/libpng16.so.16)
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 3.10.105
gyp ERR! command "/volume1/@appstore/Node.js_v8/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /volume1/web/mokavar.hu/node_modules/sharp
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
+ sharp@0.20.8
added 77 packages in 26.359s

but still fails.

Thank you

**Comment by lovell** [comment]
My best guess is that `/volume1/@appstore/Node.js_v8/usr/local/bin/node` was compiled using the `--with-system-zlib` flag so the (outdated? v1.2.8?) system zlib at `/lib/libz.so.1` will always be loaded before the newer version provided by sharp.

You'll either need to compile node with its own static zlib (v1.2.11) or compile libvips and its dependencies from source so everything uses the same system zlib.

**Comment by Korte68** [comment]
Ho can I check the node zlib version? Should  I add it to libvips gz?

**Comment by lovell** [comment]
[process.versions](https://nodejs.org/dist/latest-v8.x/docs/api/process.html#process_process_versions) is your friend.

The tarball of libvips and its dependencies already contains zlib 1.2.11.

**Comment by Korte68** [comment]
Thank you.

version 1.2.8

Can I download an earlier libvips with 1.2.8 zlib?

console.log(process.versions);
{ http_parser: '2.7.0',
  node: '8.9.4',
  v8: '6.1.534.50',
  uv: '1.15.0',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2k-fips',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }

**Comment by lovell** [comment]
The prebuilt binaries provided by sharp are created using the scripts at https://github.com/lovell/sharp-libvips

Further information about compiling libvips from source is at https://libvips.github.io/libvips/install.html#building-libvips-from-a-source-tarball

**Comment by Korte68** [comment]
Thank you
