### ISSUE TITLE
SVG to PNG- Alpine linux : Input file is missing or of an unsupported image format 

### ISSUE THREAD

**Issue by AjayLawrence** [lovell/sharp#1406]
Hi Lovell,

I am trying to convert SVG to PNG using sharp.

`sharp(buffer)
        .resize(width, height)
        .toFile(`./${pngPath}/${name}.png`, (err, info) => {
          if (err) {
            return reject(err);
          }
          return resolve(pngPath)
        })`

This code is working fine in Local. I can see PNG file is generated in my local.
But when I try to run this code in Docker (Alpine Linux) it throws the error.

`Input buffer contains unsupported image format`
`Input file is missing or of an unsupported image format 
`
I have downloaded the SVG dependency before compiling the LIBVIPS.
But i couldn't see the code is woking.

`RUN apk add --update --no-cache \
   --repository http://dl-3.alpinelinux.org/alpine/edge/testing \
   vips-dev fftw-dev librsvg-dev gcc g++ make libc6-compat`

Here is the console.log(sharp.format)
`{ jpeg:                                     
   { id: 'jpeg',                                                         
     input: { file: true, buffer: true, stream: true },                  
     output: { file: true, buffer: true, stream: true } },               
  png:                                                                   
   { id: 'png',                                                          
     input: { file: true, buffer: true, stream: true },                  
     output: { file: true, buffer: true, stream: true } },               
  webp:                                                                  
   { id: 'webp',                                                         
     input: { file: true, buffer: true, stream: true },                  
     output: { file: true, buffer: true, stream: true } },               
  tiff:                                                                  
   { id: 'tiff',                                                         
     input: { file: true, buffer: true, stream: true },                  
     output: { file: true, buffer: true, stream: true } },               
  magick:                                                                
   { id: 'magick',                                                       
     input: { file: false, buffer: false, stream: false },               
     output: { file: false, buffer: false, stream: false } },            
  openslide:                                                             
   { id: 'openslide',                                                    
     input: { file: false, buffer: false, stream: false },               
     output: { file: false, buffer: false, stream: false } },            
  dz:                                                                    
   { id: 'dz',                                                           
     input: { file: false, buffer: false, stream: false },               
     output: { file: false, buffer: false, stream: false } },            
  ppm:                                                                   
   { id: 'ppm',                                                          
     input: { file: true, buffer: false, stream: false },                
     output: { file: true, buffer: false, stream: false } },             
  fits:                                                                  
   { id: 'fits',                                                         
     input: { file: false, buffer: false, stream: false },               
     output: { file: false, buffer: false, stream: false } },            
  gif:                                                                   
   { id: 'gif',                                                          
     input: { file: true, buffer: true, stream: true },                  
     output: { file: false, buffer: false, stream: false } },            
  svg:                                                                   
   { id: 'svg',                                                          
     input: { file: false, buffer: false, stream: false },               
     output: { file: false, buffer: false, stream: false } },            
  pdf:                                                                   
   { id: 'pdf',                                                          
     input: { file: false, buffer: false, stream: false },               
     output: { file: false, buffer: false, stream: false } },            
  v:                                                                     
   { id: 'v',                                                            
     input: { file: false, buffer: false, stream: false },               
     output: { file: false, buffer: false, stream: false } },            
  raw:                                                                   
   { id: 'raw',                                                          
     input: { file: false, buffer: true, stream: true },                 
     output: { file: false, buffer: true, stream: true } } }`

Am I missing something or doing something wrong?

**Comment by lovell** [comment]
Hello, are you using the latest v0.21.0 of sharp? You should no longer need to install vips on Alpine if so and will pick up a number of improvements relating to SVG detection e.g. #1252

**Comment by AjayLawrence** [comment]
It worked. Many thanks. And hope you remember me.(From SD) :-)

**Comment by lovell** [comment]
Ah, I thought that face and first name looked familiar. Great to hear from you Ajay and glad to learn you're finding uses for sharp!

**Comment by AjayLawrence** [comment]
Thanks. Actually it works perfectly in local docker (Alpine Linux: 8.9.2). 
Now the problem is , after we deploy the code to aws (using  Jenkins) when we try to convert svg to png or resize png to PNGs the code flow stuck there. It is timing out after some time. Unfortunately we can't find the logs too. Do you have any idea why this is happening.
Do I need to double check any thing before deployment.

**Comment by AjayLawrence** [comment]
`import sharp from 'sharp';
import sizeOf from 'image-size';
import fs from 'fs';
import {log} from "../logger/logger";

export default function createPngFiles(filePath, buffer) {
  console.log(sharp.format);
  const pngPath = filePath.replace(/\.svg$/, '');
  const errorMsg = {
    status: 1,
  };

  return new Promise((resolve, reject) => {
    try {
      const dimensions = sizeOf(filePath);
      const width = dimensions.width;
      const height = dimensions.height;

      if (!fs.existsSync(`./${pngPath}`)) {
        fs.mkdirSync(`./${pngPath}`);
      }
      const promisesToMake = [
        convert(buffer, 3*width, 3*height, 'large', pngPath),
        convert(buffer, 2*width, 2*height, 'medium', pngPath),
        convert(buffer, width, height, 'small', pngPath)
      ];
      const promises = Promise.all(promisesToMake);
      promises.then(() => {
        return resolve('Successfully converted');
      }).catch((err) => {
        const logErrMsg = {message: 'Failed while converting to PNGs.'};
        log.error('createPngFiles', err, null, null, logErrMsg);
        errorMsg.message = err.message;
        return reject(errorMsg);
      })

    } catch (error) {
      log.error('createPngFiles catch block', error, null, null, "Error in Creating Png Files" + error.message);
      return reject(error);
    }
  });
}

function convert(buffer, width, height, name, pngPath) {
  return new Promise((resolve, reject) => {
    try {
      log.info('createPngFiles process started for resizing to ('+width+'*'+height+')');
      sharp(buffer)
        .resize(width,height)
        .toFile(`./${pngPath}/${name}.png`, (err, info) => {
          if (err) {
            log.error('Printing error.......: ', err);
            return reject(err);
          }
          log.info('Printing info', info);
          return resolve(pngPath)
        })
    } catch (error) {
      const errorMessage ="Error in Resizing to ("+width+"*"+height+"). Reason :";
      log.error('createPngFiles convert catch block', error, null, null, errorMessage+error.message);
      return reject(error);
    }
  })
}
`

**Comment by lovell** [comment]
Try proving absolute, rather than relative, file paths to the `toFile` function.
