### ISSUE TITLE
Resizing PNG seems to remove transparency from adjustable opacity watermark

### ISSUE THREAD

**Issue by Yamaha32088** [lovell/sharp#1409]
I am trying to resize a PNG and use it to watermark an image. The original size PNG has opacity and after resizing it, the PNG appears to lose transparency or the colors don't appear correct. I don't believe I am doing it right so any help would be greatly appreciated. I would also like to have the opacity of the watermark be adjustable.

Here is my code:
```
const sharp = require('sharp');

module.exports = function resize(path, format, width, height) {

	function resizeAndWatermarkImage() {
		resizeTheOriginalImage()
			.then((resizedImageBuffer) => {
				return watermarkTheImage(resizedImageBuffer);
			})
			.then((results) => {
				results.toFile('boom.jpg');
			})
	}

	function resizeTheOriginalImage() {
		return sharp('./blue_marble.jpg')
			.resize(width, height)
			.jpeg({
				quality: 80,
				chromaSubsampling: '4:4:4'
			})
			.background('white')
			.embed()
			.withoutEnlargement()
			.sharpen()
			.toBuffer();
	}

	function watermarkTheImage(resizedImageBuffer) {
		return resizeWatermarkImage()
			.then((resizedWatermarkImage) => {
				return sharp(resizedImageBuffer)
					.overlayWith(resizedWatermarkImage, {
						gravity: sharp.gravity.southeast
					});
			});
	}


	function resizeWatermarkImage() {
		var transparent = {r:0, b:0, g:0, alpha:0};
		var opaque = {r:0, b:0, g:0, alpha:1};
		const watermark = sharp('./sun.png')
			.flatten()
			.embed()
			.background(opaque)
			.resize(236,236)

		return applyOpacityToWatermarkImage(watermark).toBuffer();
	}

	function applyOpacityToWatermarkImage(watermarkImage) {
		return watermarkImage.overlayWith(
			new Buffer([255, 255, 255, 100]),
			{ tile: true, cutout: true, raw: { width: 1, height: 1, channels: 4} }
		).png();
	}

	resizeAndWatermarkImage();
}
```

With the above settings I get this output:
![boom](https://user-images.githubusercontent.com/6120946/46974938-fa683e00-d08a-11e8-9ae5-b5f2847749b5.jpg)

If I change the ```resizeWatermarkImage``` function to:

```
	function resizeWatermarkImage() {
		const watermark = sharp('./sun.png')
			.resize(236,236)

		return applyOpacityToWatermarkImage(watermark).toBuffer();
	}
```

The image looks like this and the colors do not look correct.
![boom](https://user-images.githubusercontent.com/6120946/46975078-559a3080-d08b-11e8-9010-072b659ca081.jpg)

Now if I don't resize the watermark with sharp but with another program to the desired dimensions and then use it everything looks like I would expect.
![boom](https://user-images.githubusercontent.com/6120946/46975181-972adb80-d08b-11e8-99a4-b9496bd35871.jpg)

**Comment by lovell** [comment]
Hello, the use of `flatten` in `resizeWatermarkImage` will remove the alpha channel, which I think is what's happening in the first image.

Is the use of `cutout: true` in `applyOpacityToWatermarkImage` intentional? It will discard one of the alpha channels when compositing two images.

Are you using the latest v0.21.0 version of sharp?

**Comment by Yamaha32088** [comment]
@lovell Thanks for the quick response! I am using sharp 0.20.8. Also yes the cutout: true is intentional because otherwise I was getting the same results as the first image where there was a background. I was using overlayWith to try and make the image semi-transparent.

**Comment by Yamaha32088** [comment]
I upgraded to the latest version and removed `flatten` and `cutout` here is what it looks like now
const sharp = require('sharp');

```
module.exports = function resize(path, format, width, height) {

	function resizeAndWatermarkImage() {
		resizeTheOriginalImage()
			.then((resizedImageBuffer) => {
				return watermarkTheImage(resizedImageBuffer);
			})
			.then((results) => {
				console.log('done!')
				results.toFile('boom.jpg');
			})
	}

	function resizeTheOriginalImage() {
		return sharp('./blue_marble.jpg')
			.resize(width, height, {
				withoutEnlargement: true,
				background: 'white'
			})
			.jpeg({
				quality: 80,
				chromaSubsampling: '4:4:4'
			})
			.sharpen()
			.toBuffer();
	}

	function watermarkTheImage(resizedImageBuffer) {
		return resizeWatermarkImage()
			.then((resizedWatermarkImage) => {
				return sharp(resizedImageBuffer)
					.overlayWith(resizedWatermarkImage, {
						gravity: sharp.gravity.southeast
					});
			});
	}


	function resizeWatermarkImage() {
		var transparent = {r:0, b:0, g:0, alpha:0};
		var opaque = {r:0, b:0, g:0, alpha:1};
		const watermark = sharp('./sun.png')
			.resize(236,236, {
				background: transparent,
				fit: 'contain'
			})

		return applyOpacityToWatermarkImage(watermark).toBuffer();
	}

	function applyOpacityToWatermarkImage(watermarkImage) {
		return watermarkImage.overlayWith(
			new Buffer([0, 0, 0, 100]),
			{ tile: true, raw: { width: 1, height: 1, channels: 4 } }
		)
	}

	resizeAndWatermarkImage();
}
```

![boom](https://user-images.githubusercontent.com/6120946/47020113-42847080-d11e-11e8-8ca5-d70035906376.jpg)

**Comment by lovell** [comment]
Please can you provide the input images.

My best guess is that `sun.png` is 3 channel RGB without an alpha channel and `applyOpacityToWatermarkImage` gives it a linear ~39% opacity.

Are you able to share the code that produces the expected output from "another program"?

**Comment by Yamaha32088** [comment]
Hello,
The reference to "another program" is just an online resizing tool so I don't have the source code to that. However the small sun1.png image is the image returned from the online image resizing service.

![sun](https://user-images.githubusercontent.com/6120946/47044094-f0127680-d154-11e8-8f95-604dc68c6e23.png)
![blue_marble](https://user-images.githubusercontent.com/6120946/47044102-f30d6700-d154-11e8-861f-1b31fbc529a1.jpg)
![sun1](https://user-images.githubusercontent.com/6120946/47044169-189a7080-d155-11e8-8074-4e876649450d.png)

**Comment by lovell** [comment]
`sharp` will be migrating from its own image composition logic to libvips' new-ish composite operation as part of #728, which might be enough to deal with the colour discrepancies seen here. It's also possible the "just an online resizing tool" you mention isn't quite premultiplying correctly, but without access to the source it's hard to tell.

Adjusting the opacity of the alpha channel is being tracked at #618
