### ISSUE TITLE
support PDF to png

### ISSUE THREAD

**Issue by zuohuadong** [lovell/sharp#1411]
support PDF to png

how to use it?

**Comment by lovell** [comment]
Hello, you'll need to compile and globally install a custom libvips with PDF support before installing sharp.

Please see #672 #1181

**Comment by zuohuadong** [comment]
@lovell  thanks

**Comment by TobiasGruberAT** [comment]
> Hello, you'll need to compile and globally install a custom libvips with PDF support before installing sharp.
> 
> Please see #672 #1181

Hello! :) Is it hard to do that? Because I also currently need to create a Thumbnail out of the first page of a PDF-File, but I have no experience in C++ (what I, as far as I have read, need to know for lipvips).

**Comment by lovell** [comment]
https://libvips.github.io/libvips/install.html#building-libvips-from-a-source-tarball
