### ISSUE TITLE
metadata.size is undefined in version 0.21.0

### ISSUE THREAD

**Issue by shaneharris** [lovell/sharp#1413]
I'm using `"sharp": "^0.21.0"` from npm and this property doesn't seem to exist when i read from the filesystem at least:

```javascript
 sharp('image_path')
    .metadata()
    .then(metadata=>{
        console.log(metadata.size); // undefined
    });
```

Related: #695

**Comment by lovell** [comment]
Hello, did you see the docs for [metadata](http://sharp.pixelplumbing.com/en/stable/api-input/#metadata)?

> "size: Total size of image in bytes, for Stream and Buffer input only"

The benefit of the `size` property is mainly for Stream-based input as [fs.stat](https://nodejs.org/api/fs.html#fs_fs_stat_path_options_callback) is already available for the filesystem.

**Comment by shaneharris** [comment]
Apologies i did read the docs but somehow i missed that! Thanks!
