### ISSUE TITLE
Possible buffer memory leak on fedora/centos systems 

### ISSUE THREAD

**Issue by agustik** [lovell/sharp#1415]
I'm writing a application to index large amount of images.

I'm getting large RSS (1.5 - 2gb after few hundred images) usage and it' is not going down. Heap is about 70mb.

If I run this code on my machine the RSS will just keep on growing.

current system: Fedora release 28 (Twenty Eight)
 http_parser: '2.8.0',
  node: '10.1.0',
  v8: '6.6.346.27-node.6',
  uv: '1.20.2',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.29.0',
  napi: '3',
  openssl: '1.1.0h',
  icu: '61.1',
  unicode: '10.0',
  cldr: '33.0',
  tz: '2018c' 

```
const sharp = require('sharp');
const path = require('path');
const fs = require('fs');
const async = require('async');
sharp.cache(false);


const filePath  = process.argv.pop();


function createArray(len){
  const array = [];

  for (let i = 0; i < len; i++){
    array.push(i);
  }

  return array;
}

const arr = createArray(10000);

const sourceBuffer = fs.readFileSync(filePath);

async function resize(source){
  const image = sharp(source).toBuffer();
  source = null;
  return image;
}

function logMemory(){
  const pr = process.memoryUsage();
  const logObject = {};
  for (let key in pr){
    logObject[key] =  parseInt((pr[key] / 1024 / 1024).toFixed(0));
  }

  console.log(logObject)

}

async.forEachLimit(arr, 1, async function (i){
  let resizedImage = await resize(sourceBuffer);

  resizedImage = null;
  logMemory();
}, function (err){

  console.log('done', err)
  setTimeout(logMemory, 3000)
})
```

The image is 24mb TIFF image

usage is : node test.js 'file.tiff'

**Comment by lovell** [comment]
Hello, did you see #955?

**Comment by agustik** [comment]
@lovell Well, i read it like few hours ago .. 

But sharp.concurrency(); seems to do the trick keeping the memory down ..


I't might fix the issue. I'm going to commit the code on my procject and deploy on my test servers..

**Comment by agustik** [comment]
RSS is about 500-700mb in production right now (more than just sharp)

concurrency is 1;
and cache is default enabled.

**Comment by lovell** [comment]
@agustik Were you able to make any progress with this?

**Comment by agustik** [comment]
No problems that I know off after i set concurrency to 1. I'll check the stats on the production system

**Comment by lovell** [comment]
Sounds like this problem has gone away but please re-open with more details if not.
