### ISSUE TITLE
Absolutely necessary files to run

### ISSUE THREAD

**Issue by tcz** [lovell/sharp#1417]
Hi,

I'm trying to reduce the size of a build artifact and I'd like to know which files are absolutely necessary for sharp to run. There seem to be a lot of files in the `node_modules` subdir that are development related but I'm having a hard time figuring out which one I can get rid of.

Thanks

**Comment by lovell** [comment]
Hello, as you've probably seen, `sharp` lists separate `devDependencies` from `dependencies` so at install time only the modules necessary for installation and runtime are added to `node_modules`. I suspect it's the former category you care about, the install time but not runtime dependencies.

Excluding sharp itself, the following are the `dependencies` that take up most disk space.
```sh
$ npm install sharp
$ du -sh node_modules/* | grep -v sharp | sort -rh
588K	nan
196K	tar
188K	mkdirp
172K	readable-stream
136K	tar-fs
104K	gauge
100K	minimist
...
```
At least the first 3 of these are, I think, currently used only at install-time so could probably be removed after `npm install` has completed. Beyond that you'd have to experiment - good luck!
