### ISSUE TITLE
Using sharp with canvas and electron-builder, runtime can't find dylibs (osx)

### ISSUE THREAD

**Issue by awbacker** [lovell/sharp#1419]
```
   sharp@0.20.5
   electron-builder@20.14.7
```

Can anyone provide me with some pointers on how to use `sharp` with electron-builder on os-x, since I am **sure** I am doing something wrong here.  I am having 2 issues when loading the `.dylib` files that always show up when the app is opened on another machine:

* Incompatible Version (see the error below)
  * Version in app.asar is 49, but version found is 42 (etc)
* File Not Found (`/opt/local/bin/libpixman-1.0.dylib`, etc)

I can't quite tell whats going on.  Sometimes it seems to find the dylib but its the wrong version (in the app.asar), which implies it used my local version as the version# it wants.  In other cases it appears to not find the dylib at all and complains with a "file not found", even though it _is_ in the app.asar.   

Here are the steps I am following, and my configuration:

* My machine has macports installed, with many of these libraries also installed/used
* OS-X 10.13.6 
* I am building with yarn, with basically this sequence of commands
  * yarn install
  * node postinstall
  * ng build -c productoin
  * npx electron-builder install-app-deps
  * npx electron-builder build --mac 
* App is packaged as dmg
  * app.asar contains the libs 
  * app.asar.unpacked/ also contains the libs  (both in node_modules/sharp/vendor/lib)

Also:

* I have cleared LIBRARY_PATH and CPLUS_INCLUDE_PATH
* I do not have DYLD_FALLBACK
* I expect to see "load @rpath/libping16.16.dylib" but I see "/opt/local/lib" :(
* I do not have a DYLD_FALLBACK_... setting in my environment

```
dlopen(/var/folders/2_/{rand}/T/.myapp.CZDwaU, 1): 
  Library not loaded: /opt/local/lib/libpng16.16.dylib  (this file does _not_ exist!)
  Referenced from: /var/folders/2_/{rand}/T/.product.CZDwaU
  Reason: Incompatible library version: .product.CZDwaU requires version 52.0.0 or later, but libpng16.16.dylib provides version 49.0.0 
        ^^^^ it found a file, the one in the app.asar (or app.asar.unpacked)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Applications/product.app/Contents/Resources/app.asar/node_modules/canvas/lib/bindings.js:3:18)
    at Object.<anonymous> (/Applications/product.app/Contents/Resources/app.asar/node_modules/canvas/lib/bindings.js:5:3)
```

I filed an issue in electron-builder, but I now think that _may_ be the wrong place (https://github.com/electron-userland/electron-builder/issues/3395)

**Comment by lovell** [comment]
Hello, the linked issue mentions `canvas`, which has dependencies on many of the same shared libraries as `sharp`.

If you're using the pre-built binaries of these dependencies for `sharp` but relying on OS versions for `canvas` then you'll need to ensure the correct loading order of those shared libraries for these two modules to co-exist.

See #371 and #1157 for related information.

**Comment by awbacker** [comment]
I'll be going through those now, and the suggestions.  Maybe that explains why it seems to not raise the _same_ dylib as being the problem each time, even on the same machine.  Could take a few days though.

**Comment by awbacker** [comment]
I'll be going through those now, and the suggestions.  Maybe that explains why it seems to not raise the _same_ dylib as being the problem each time, even on the same machine.  Could take a few days though.

**Comment by awbacker** [comment]
@lovell Thanks for your response, and helping me out here.  I'm doing the mac build for this internal app only, no dev, but I was still able to figure out how to fix this.  The answer: `remove canvas` and related code.  

Sharp is great, the libs are bundled and everything works as expected (all thanks to the sharp team!).   Since we didn't need canvas, and it was causing problems, it was just easier to remove it and try to find some workarounds or other packages for the minor functionality that had to be taken out.  

Apologies for posting this issue/help request here.  The fact that they rely on the same libs in many cases, plus the fact that sharp (properly) bundles them so I could see them in the asar, led me to erroneously conclude it was an issue with how we were including/building/loading *sharp*.  Again, sorry for that, and thanks for your help.
