### ISSUE TITLE
Failed at the sharp@0.8.3 install script.

### ISSUE THREAD

**Issue by yegya** [lovell/sharp#142]
Been trying hard in getting installed the sharp module in my node project, but hard time, never succeeded in last 2 days. Explored a lot, but still finding hard in succeeding. Am I doing something wrong? Tried with old version (0.5.1) as well, but same error. Please help. I'm using:
npm: 1.4.28
node: v0.10.33
The error follows:

npm ERR! sharp@0.8.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.8.3 install script.
npm ERR! This is most likely a problem with the sharp package,
npm ERR! not with npm itself.

**Comment by lovell** [comment]
Hi @yegya, were you able to make any progress with this?

**Comment by yegya** [comment]
nope sorry, it is dependent on lots of other things, and its too time consuming.

**Comment by lovell** [comment]
Thanks for the update Sanjay. I'll close this request for now but please do feel free to re-open if you return and are still having problems. (My best guess right now is that the solution lies somewhere between homebrew and pkg-config.)

**Comment by Couto** [comment]
I'm unsure if it's related, but I'm also experiencing some troubles to install sharp, but on an Ubuntu machine: you can check the log (silly level) on this gist: https://gist.github.com/Couto/0b4f94479d913ab20c3e

I can open a new issue, if you find this to be unrelated.

**Comment by lovell** [comment]
Hi @Couto, I believe the problem you've run into is that yesteday's 1.5.1 release of nan is more strict about 64 to 32 bit Integer conversion.

I've fixed this via https://github.com/lovell/sharp/commit/eefd471674e2a4869e80478da929d5af5677d8b7 on the intake branch. Please can you try:
```
npm install lovell/sharp#intake
```

**Comment by Couto** [comment]
It does seems to install correctly when using the intake branch.
Any ETA for the merge with the master branch?

Thanks for the quick answer.

**Comment by lovell** [comment]
@Couto The `intake` branch is work-in-progress so I've manually fixed this on master - see https://github.com/lovell/sharp/commit/065ce6454b0db9b60dc7b0acc38aec873d59c43

I'll get v0.8.4 published to npm in the next hour or so as I suspect others will run into this problem too.
