### ISSUE TITLE
Is sharp.js using GPU ?

### ISSUE THREAD

**Issue by golojads** [lovell/sharp#1424]
Hi,

I'd like to buy very powerful machine to do basic operations with sharp.js on JPEGs and PNG ( with Alpha) images - composition, scaling, rotation. But I'm not sure whether I need to invest more into VGA, CPU and/or RAM.
Does sharp.js uses power of GPU under the hood ?
If answer is yes, then:
- should I use any GPU specific API of sharp.js or need some flags while installing it ?
- will there be any significant performance differences between Linux(Ubuntu 18) or Windows 10 machines 

Thank you.

**Comment by lovell** [comment]
Please see #1202
