### ISSUE TITLE
Is sharp using cache when an image is resized?

### ISSUE THREAD

**Issue by kushubham9** [lovell/sharp#1426]
I am facing this strange thing. Say I have a given image at location '**/something/image.png**'. 

Now I update the image at the above location and resize the image a multiple times. 
`await sharp(inputFile).resize(width, height).toFile(destinationFile)`

What I am observing here, that the resized image somehow still refers to my old image. The new image is not resized. 

This is pretty strange to me. Any workaround here?

**Comment by EvgeniyGorbachev** [comment]
Also ran into this problem. Perhaps it is worth adding a mention of a cache to the main README.md file?

**Comment by lovell** [comment]
@kushubham9 I hope this answered your question.
