### ISSUE TITLE
Image not being resized

### ISSUE THREAD

**Issue by hornta** [lovell/sharp#1427]
When performing a resize, then an extract and then an resize again, the final image is not being resized(the actual image is resized, but not the dimensions)

Clone my repo and test https://github.com/hornta/sharp-resize-bug

```javascript
const sharp = require('sharp');
sharp('dog.jpg')
  .resize(50)
  .extract({
    left: 0, 
    top: 0, 
    width: 25, 
    height: 25
  })
  .resize(1000)
  .jpeg()
  .toFile('bigDog.jpg');
```

bigDog.jpg results in a 25x25 pixels image when it should end up with a 1000px wide image

**Comment by lovell** [comment]
Hello, if you want to resize to 50 pixels wide, extract the top-left 25x25 region then resize to 1000 pixels wide, try something like the following:
```javascript
sharp('dog.jpg')
  .resize(50)
  .extract({
    left: 0, 
    top: 0, 
    width: 25, 
    height: 25
  })
  .toBuffer()
  .then(data => sharp(data)
    .resize(1000)
    .toFile('bigDog.jpg')
  );
```

**Comment by hornta** [comment]
Is there a reason I have to do it like that? Why is not my example working? I think most people expect it to work like my example

**Comment by lovell** [comment]
Although `resize` can be called multiple times to set/update options, the current implementation supports one resize operation per instance.

You may be interested in a discussion about an alternative API at #241.
