### ISSUE TITLE
Resolve toBuffer Promise with an array (was: When using promises, how do you get image info)

### ISSUE THREAD

**Issue by salzhrani** [lovell/sharp#143]
if a callback is used with `toBuffer` for example the image `info` is passed to the callback, how do you get this info when using a promise ?

**Comment by strarsis** [comment]
Workaround using bluebird promise library:
```js
var Promise = require('bluebird'),
    sharp   = require('sharp');

Promise.promisifyAll(sharp.prototype, {multiArgs: true});
  // promisify the sharp prototype (methods) to promisify the alternative (for raw) callback-accepting toBuffer(...) method

sharp('./test.png') // simple test for demonstration purposes
.raw().toBufferAsync() // as raw to buffer
.then(function(dataAndInfo) { // multiArgs: true will spread the arguments to cb to array elements by their order
  var data = dataAndInfo[0], // nicely assigning the array elements back to variables for demonstration purposes
      info = dataAndInfo[1];

  return sharp(data, {raw: info}) // as usual...
  .metadata(); // triggering sharp to actually load that data (for demonstrating this works)
})
.then(function(meta) {
  console.log(meta); // should succesfully log the determined metadata
});
````
Hope this helps!

**Comment by lovell** [comment]
Given there's no easy deprecation route how about we go with a slight modification of @salzhrani's original suggestion of allowing `toBuffer` to accept a parameter indicating the desired behaviour?

This would look something like `toBuffer({ resolveWithArray: true })`, defaulting to false, the current behaviour.

**Comment by Vispercept** [comment]
From my point of view, it would be better if there would be a completely new function called `getInfo` for example. This function should return all info. `toBuffer` returning also info is a nice side-effect and one should not rely on that. Splitting the functionality oft `toBuffer` into two functions would also follow the clean-code principles (Functions should only do one thing – https://github.com/ryanmcdermott/clean-code-javascript/blob/master/README.md#functions-should-do-one-thing)

**Comment by lovell** [comment]
@Vispercept The `data` and `info` attributes "returned" by [toBuffer](http://sharp.dimens.io/en/stable/api-output/#tobuffer) are highly related to each other; `info` contains properties computed whilst processing the final output image. Perhaps you're thinking of the existing [metadata](http://sharp.dimens.io/en/stable/api-input/#metadata) call to access input image info?

Rather than the Promise resolving with an Array, how about resolving with an Object, which would allow for destructuring e.g.:

```javascript
sharp(input)
  .resize(123)
  .toBuffer({ resolveWithObject: true })
  .then( ({ data, info }) => {
    ...
  });
```

**Comment by Vispercept** [comment]
@lovell thanks for the clarification :-) didn't know that...

**Comment by lovell** [comment]
Commit 6fe5b30 adds the new `resolveWithObject` option to `toBuffer`. This will be in v0.17.3.

**Comment by lovell** [comment]
v0.17.3 now available, thanks everyone for the suggestions and discussions.
