### ISSUE TITLE
The system cannot find message text for message number 0x%1 in the message file for %2

### ISSUE THREAD

**Issue by skypatel125** [lovell/sharp#1433]
Error: The system cannot find message text for message number 0x%1 in the message file for %2.
\\?\D:\demo\server\**node_modules\sharp\build\Release\sharp.node**

please help me its urgent

working fine in browser but not in electron js
maybe i am using a 64bit build but building that module as 32-bit.

**Comment by lovell** [comment]
Hello, only 64-bit `node.exe` is supported on Windows.
http://sharp.pixelplumbing.com/en/stable/install/#windows-x64

**Comment by skypatel125** [comment]
i have installed 64 bit in my PC but sharp working proper in browser but not in electron

**Comment by skypatel125** [comment]
![sharp](https://user-images.githubusercontent.com/41112527/47568002-8dd42580-d94d-11e8-96aa-c7c947c22ee8.PNG)

i have installed 64 bit in my PC but sharp working proper in browser but not in electron.
please tell what i need to change or add?

**Comment by lovell** [comment]
[electron-rebuild](https://github.com/electron/electron-rebuild) will probably be required if the system version of Node doesn't match the Electron version of Node. Make sure the Electron executable is 64-bit also.

**Comment by Art4** [comment]
I had the same issue on Windows x64 with node v8.11.1 and on Electron with node v10.2.0.
electron-rebuild fixes this issue for me.
