### ISSUE TITLE
Reduce a logo SVG to one solid colour, and place it on top of a background of another solid colour

### ISSUE THREAD

**Issue by philwolstenholme** [lovell/sharp#1435]
Hi, 

I'm using the code below to change a SVG logo to use only one colour (red) via the `cutOut` option of the `overlayWith` function. This results in a red SVG on a transparent background. How could I add a background below the red SVG?

Thanks for your help 👍 

```
const sharp = require('sharp');

sharp({
  create: {
    width: 588,
    height: 438,
    channels: 4,
    background: 'red',
  },
})
  .overlayWith('logo.svg', {
    gravity: 'centre',
    cutout: true,
    density: 180,
  })
  .png()
  .toFile('screenshot.png');

```

**Comment by philwolstenholme** [comment]
Sorry, that was probably a poor explanation. Ideally, what I'm looking for is this:

* A background of one solid colour, e.g. red
* A center overlaid SVG logo which is of one solid colour, e.g. white

**Comment by lovell** [comment]
Hello, [flatten](http://sharp.pixelplumbing.com/en/latest/api-operation/#flatten) is your friend - you'll need to use a second pipeline, something like:
```javascript
  ...
  .png()
  .toBuffer()
  .then(data =>
    sharp(data)
      .flatten({ background: { r: 100, g: 100, b: 100 } })
      .toFile("screenshot.png")
  );
```

**Comment by philwolstenholme** [comment]
Ah yes, that worked perfectly! I hadn't spotted that `flatten` had a background param.

Thank you very much for your help 👍
