### ISSUE TITLE
Error when processing larger images on Alpine Linux

### ISSUE THREAD

**Issue by bodaniel** [lovell/sharp#1436]
Sharp/libvips fails when processing "larger" images on Alpine Linux. The same test works fine on Debian.

## Error
```
(node:111) UnhandledPromiseRejectionWarning: Error: VipsImage: unable to write to "/tmp/vips-0-3199096164.v"
unix error: Not supported
vips2png: unable to write to buffer
```

## A simple test project
The following project reproduces the issue for a large png image. Smaller pngs works fine. Large jpeg images seems to work fine as long as it is resized to a smaller jpeg.
https://github.com/bodaniel/sharp-test

**Comment by lovell** [comment]
Hello, to avoid libvips writing temporary files try setting the `VIPS_DISC_THRESHOLD` environment variable to a value greater than the default of 100MB.

https://libvips.github.io/libvips/API/current/VipsImage.html#vips-image-new-from-file

(Or alternatively provide Docker with a volume mapping for `/tmp`.)

**Comment by bodaniel** [comment]
According to df -h there is 42.7G available on /tmp in the Docker
container. Is that not true? Do you know why it fails?

When setting VIPS_DISC_THRESHOLD=200m it works fine.

Thanks, but I am still curious about why using /tmp fails :-)

Daniel


Den sön 28 okt. 2018 17:07Lovell Fuller <notifications@github.com> skrev:

**Comment by lovell** [comment]
What underlying system are you running Docker on? The prebuilt musl binaries might be assuming that `O_TMPFILE` is available in the kernel.

**Comment by bodaniel** [comment]
I have tried running Docker on my Mac. I have also tried running Docker on
AWS EC2 instances (Linux). Both fails.

So even though I can access /tmp when running the container interactively
(eg. /bin/sh, /bin/bash), libvips cannot access /tmp?

Daniel


Den mån 29 okt. 2018 15:01Lovell Fuller <notifications@github.com> skrev:

**Comment by lovell** [comment]
sharp v0.22.0 now available, providing libvips v8.7.4.

**Comment by jpsear** [comment]
@lovell I have a docker image that builds a gatsby site and uses `sharp` for image processing. Unfortunately, I'm still getting the following error upon upgrading `sharp` to `0.22.0`:

```
  Error: VipsImage: unable to write to "/tmp/vips-0-694863299.v"
  unix error: Not supported
  VipsImage: unable to write to "/tmp/vips-1-3438510708.v"
  unix error: Not supported

error UNHANDLED REJECTION
```

Any ideas?

**Comment by lovell** [comment]
@jpsear The latest Gatsby currently depends on sharp v0.21.3.

**Comment by jpsear** [comment]
Ah cool. I'll try a `resolutions` key in my `package.json` and see if I can force the upgraded version for now...

**Comment by jpsear** [comment]
Yup, that worked. For anyone else, for now you can use this in your `package.json`:
```
  "resolutions": {
    "sharp": "^0.22.0"
  },
```
