### ISSUE TITLE
Illegal hardware instruction when requiring on a Raspberry Pi

### ISSUE THREAD

**Issue by Mrtenz** [lovell/sharp#1437]
When I require sharp (v0.21.0) on a Raspberry Pi Zero W (ARMv6) the app crashes with
```
[1]    1946 illegal hardware instruction (core dumped)  node test.js
```

The contents of `test.js` are simply:
```javascript
require('sharp');
```

I have no issues installing sharp and `node-gyp` does not show any errors. Here is the full build output if that helps:
https://gist.github.com/Mrtenz/a818788786efb1e84ecb8b4a1a8e2d52

**Comment by Mrtenz** [comment]
Tried pre-installing `libvips`, now I get this error:
```
internal/modules/cjs/loader.js:717
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: libvips-cpp.so.42: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/morten/test/node_modules/sharp/lib/constructor.js:10:15)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
```

Output of `whereis libvips`:
```
libvips: /usr/local/lib/libvips.la /usr/local/lib/libvips.so /usr/local/lib/libvips.a
```

**Comment by Mrtenz** [comment]
Was able to resolve that by following [this](https://github.com/lovell/sharp/issues/327#issuecomment-167094002), but it would still be nice if this could be resolved without having to install libvips manually.

**Comment by lovell** [comment]
Hello, I suspect the prebuilt `libvips-8.7.0-linux-armv6.tar.gz` might be causing this.

It's cross-compiled using the Docker image at https://github.com/lovell/sharp-libvips/blob/master/linux-armv6/Dockerfile

I've seen problems in the past where Thumb 2 instructions, unsupported on the Pi Zero, were erroneously produced by gcc - see https://github.com/lovell/sharp-libvips/commit/0b190075a399479272b2ab849daa26888af0ee7d

We might need to add another compiler flag such as `-mnothumb`.

**Comment by lovell** [comment]
I've updated the ARMv6 container from gcc 6 to 8 and provided it with the specific CPU model used in the Pi Zero to help avoid any Thumb instructions - see commit https://github.com/lovell/sharp-libvips/commit/ef4893b380f5866fa70da65af4b79e16d75626df

Here's the binary it now produces: [libvips-8.7.0-linux-armv6.tar.gz](https://github.com/lovell/sharp/files/2527233/libvips-8.7.0-linux-armv6.tar.gz)


Are you able to test? If so, please save the above file to your local `~/.npm/_libvips` folder, uninstall the global libvips, delete `node_modules/sharp` then reinstall sharp.

**Comment by lovell** [comment]
I updated the container used for ARMv6 cross-compilation to use the [same crosstools](https://github.com/rvagg/rpi-newer-crosstools) as Node uses for its ARMv6 build and successfully tested the resultant tarball on a Pi Zero.

https://github.com/lovell/sharp-libvips/commit/f3daaf3a06fc7e7c7b5a436e3b0b3c9283e7c536

https://github.com/lovell/sharp-libvips/releases/download/v8.7.0/libvips-8.7.0-linux-armv6.tar.gz

You may need to clear your local `~/.npm/_libvips` directory before re-installing sharp.

Thanks for reporting this.

**Comment by Mrtenz** [comment]
Thank you for the update! I missed your previous message, but everything seems to work smoothly now.
