### ISSUE TITLE
Switching to MozJPEG?

### ISSUE THREAD

**Issue by chanon** [lovell/sharp#144]
MozJPEG is now at version 3.0 and looks very interesting:
http://calendar.perfplanet.com/2014/mozjpeg-3-0/

Would switching in mozjpeg for libjpeg-turbo provide any advantages in terms of compression / image quality? Has anyone looked into this?

**Comment by lovell** [comment]
With the default mozjpeg settings I see around 20% smaller file sizes for these 320x240px images, at a cost of compressing 2.2x more slowly.

```
libjpeg-turbo8: 17.19 ops/sec ±0.12% (83 runs sampled)
mozjpeg: 7.69 ops/sec ±0.10% (41 runs sampled)
```

```
10761 test/fixtures/output.blur-mild.jpg
 9317 test/fixtures/output.blur-mild.jpg
22989 test/fixtures/output.cmyk2srgb.jpg
18806 test/fixtures/output.cmyk2srgb.jpg
23194 test/fixtures/output.exif.5.jpg
18902 test/fixtures/output.exif.5.jpg
 3829 test/fixtures/output.flatten-hex-orange.jpg
 3251 test/fixtures/output.flatten-hex-orange.jpg
14918 test/fixtures/output.flip.jpg
12687 test/fixtures/output.flip.jpg
15028 test/fixtures/output.flop.jpg
12700 test/fixtures/output.flop.jpg
 2048 test/fixtures/output.gamma-2.2.jpg
 1807 test/fixtures/output.gamma-2.2.jpg
 5540 test/fixtures/output.gravity-centre.jpg
 4844 test/fixtures/output.gravity-centre.jpg
12483 test/fixtures/output.greyscale-gamma-2.2.jpg
 9641 test/fixtures/output.greyscale-gamma-2.2.jpg
14948 test/fixtures/output.sharpen-mild.jpg
12661 test/fixtures/output.sharpen-mild.jpg
```

**Comment by chanon** [comment]
Thanks for trying it out and sharing the results!
Hmm.. 20% sounds like a lot considering the image quality that could be gained while keeping the same file size.

**Comment by lovell** [comment]
An average reduction of 20% was better than expected, although I believe the appropriate phrase to use here is "your mileage may vary" :)

It's definitely worth testing with images that more closely resemble your given workload.

**Comment by lovell** [comment]
Closing this for now - feel free to reopen if you run into any problems with mozjpeg or if anyone would like to provide their own perf results.
