### ISSUE TITLE
running sharp on functionapp gives  'win32-x64' binaries cannot be used on the 'win32-ia32' platform. 

### ISSUE THREAD

**Issue by sidharthnayyar** [lovell/sharp#1443]
Hi,

I've got a javascript azure function app that I would like to run sharp on. When I do so I get the following error:

"Error: 'win32-x64' binaries cannot be used on the 'win32-ia32' platform. Please remove
the 'node_modules/sharp/vendor' directory and run 'npm install'."

I'm running it locally on VSCode on a Windows 10 machine on a 64 bit processor using sharp version 0.21.0 and I think it's using the libvips 8.7.0 I believe.

I've tried the following things:

1. removed the sharp/vendor and ran npm install. This unfortunately gave the error sharp.node is not a valid win32 application

2. We copied the function app core tools 1.0.15 64 bit version and put that manually into node_modules just to see if that gives a different error but it gave the same error.

3. We even tried to run this via the portal (and set the platform to 64 bit) but it gave
" Error: A dynamic link library (DLL) initialization routine failed.
\\?\D:\home\site\wwwroot\node_modules\sharp\build\Release\sharp.node" error

Any help would be much appreciated.

Kind regards
Sidharth

**Comment by lovell** [comment]
It looks like `npm install` was (correctly) run using 64-bit `node.exe` but 32-bit `node.exe` is being used at runtime.

> "Only 64-bit (x64) node.exe is supported."
> http://sharp.pixelplumbing.com/en/stable/install/#windows-x64

https://github.com/Azure/Azure-Functions/issues/376 might help you - good luck!
