### ISSUE TITLE
Flattening TIFF with transparency leaves outline artifacts

### ISSUE THREAD

**Issue by sylvainlegault** [lovell/sharp#1445]
Hi,

I'm using latest version '0.21.0' but I have tried few older versions with same results.

I'm converting TIFF with transparency to JPG with a white background but the image contain some artifacts around the edge of the image and the transparency.

Sorry githup doesn't support tiff extension (so renamed to tiff.txt)

TIFF file:
[test_white_1_main.tiff.txt](https://github.com/lovell/sharp/files/2542571/test_white_1_main.tiff.txt)

Image with artifact issue (see red box annotation):
![test_white_1_main](https://user-images.githubusercontent.com/39707773/47917744-daa18a00-de80-11e8-81a6-1de0f122428c.jpg)

Expected image:
![test_expected](https://user-images.githubusercontent.com/39707773/47917754-e2f9c500-de80-11e8-92c5-c04f69d6eed7.jpg)

```
const sharp = require('sharp')
sharp('test_white_1_main.tif')
  .jpeg()
  .flatten({background: 'white'})
  .toFile('test_white_1_main.jpg')  
```

I have tried different configuration but all result to the same issue.
Thanks in advance

**Comment by lovell** [comment]
Hello, the alpha channel in this image has been stored in its premultiplied form, referred to as "associated alpha" in TIFF.

I see the same effect using libvips at the command line:
```sh
vips flatten --background="255 255 255" test_white_1_main.tiff out.jpg
```

libvips may have to be modified to detect a TIFF with a premultiplied alpha channel and flag it as such, then ensure an unpremultiply operation before flattening.

**Comment by sylvainlegault** [comment]
Thanks for following up with libvips on this issue.

**Comment by lovell** [comment]
Note to self: requires libvips v8.8.0.

**Comment by adityapatadia** [comment]
@lovell lot of issues are related to release of libvips v8.8. Now that it's released, please let us know if we can close them. I can help closing issues if you direct what needs to be done.

**Comment by lovell** [comment]
@adityapatadia I'll close all issues that require libvips v8.8.0+ after sharp v0.23.0 is released as it will provide prebuilt binaries with at least that version.

**Comment by adityapatadia** [comment]
Let me know if I can speed up the process in any way. What is blocking 0.23 release?

**Comment by lovell** [comment]
sharp v0.23.0 / libvips v8.8.1 is now available.
