### ISSUE TITLE
png options.compressionLevel is not working?

### ISSUE THREAD

**Issue by aioros2016** [lovell/sharp#1446]
I import a PNG, and the exported PNG is larger than the pre-treatment size, and it seems that zlib compression is not working.

**Comment by lovell** [comment]
Hello, please see http://sharp.pixelplumbing.com/en/stable/api-output/#png

> "PNG output is always full colour at 8 or 16 bits per pixel. Indexed PNG input at 1, 2 or 4 bits per pixel is converted to 8 bits per pixel."

#478 is the canonical version of this question.
