### ISSUE TITLE
GLib-GObject-WARNING and GLib-GObject-CRITICAL

### ISSUE THREAD

**Issue by 1Map** [lovell/sharp#1449]
Although my code executes fine and generates the file 100%, I am getting the following error messages:

```
(sharp:157048): GLib-GObject-WARNING **: 21:49:04.120: invalid uninstantiatable type '(null)' in cast to 'GObject'

(sharp:157048): GLib-GObject-CRITICAL **: 21:49:04.120: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed
```

My code is as follow:

```
var sharpImg = sharp('file1.png');
sharpImg.metadata().then(function (metadata) {
	var origWidth = metadata.width;
	var origHeight = metadata.height;
	return sharpImg.resize(Math.round(origWidth / 2), Math.round(origHeight / 2));
}).then(function (data) {
	data.toFile('file2.png', function (err, info) {
		// Done with err == null (No errors here)
	});
});
```

**Comment by lovell** [comment]
Hello, this looks like #1320 - are you using the latest version?

**Comment by 1Map** [comment]
I am using Sharp version ^0.20.8

**Comment by lovell** [comment]
Are you able to reproduce with the latest v0.21.0 version?

**Comment by 1Map** [comment]
@lovell No, I upgraded to 0.21.0 and I was monitoring fro past day or so.  It seems the problem was fixed in the latest version, so you can go ahead and close this.  Thanks for the help.

**Comment by KillerCodeMonkey** [comment]
@lovell i do not know if it is a similar problem, but with electron 35 + sharp 0.34.1 i get similar warnings.

```BASH
[233292:0415/100821.737370:ERROR:browser_main_loop.cc(276)] GLib-GObject: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
[launcher] [233292:0415/100821.737382:ERROR:browser_main_loop.cc(276)] GLib-GObject: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```
They are not there with v0.33.

i am on ubuntu 24.04 and Kernel 6.11.0

In general i use sharp to resize images on the fly:

```TS
await sharp(path)
      .resize({
        background: {
          alpha: 0,
          b: 0,
          g: 0,
          r: 0
        },
        fit: 'contain',
        width,
        withoutEnlargement: true
      })
      .toBuffer()
```

It could be a new issue or my fault, but i just wanted to make sure before creating a new one.

**Comment by KillerCodeMonkey** [comment]
@lovell any feedback? :)
