### ISSUE TITLE
Question: what's the optimum/cleanest way of overlaying multiple images using streams

### ISSUE THREAD

**Issue by ovaris** [lovell/sharp#1450]
Hi,

just wanted to post a question to get suggestions how to make code simpler and possible improve performance. We're composing multiple images as one, using read streams (originating from Cloud Storage bucket), here's our implementation:
```
const composeImage = async imageReadStreams => {
  const baseSharpInstance = sharp();
  imageReadStreams[0].pipe(baseSharpInstance);
  //  read image dimensions from the first read img
  const metaData = await baseSharpInstance.metadata();

  const options: sharp.SharpOptions = {
    raw: {
      width: metaData.width,
      height: metaData.height,
      channels: 4,
    },
  };

  const base = baseSharpInstance.raw().toBuffer();

  imageReadStreams.shift();
  const buffer = await imageReadStreams.reduce((input, overlay) => {
    return input.then(async data => {
      const pipeline = sharp();
      overlay.pipe(pipeline);
      const asBuffer = await pipeline.raw().toBuffer();
      return sharp(data, options)
        .overlayWith(asBuffer, options)
        .raw()
        .toBuffer();
    });
  }, base);
  return sharp(buffer, options);
};
```
Function returns new Sharp instance which is then used create different sizes & outputs from composed img. 

Any suggestions are highly appreciated!

**Comment by lovell** [comment]
Hello, this is probably about the best that can be achieved using Stream-based input with the current API.

If you haven't already seen it, #728 is tracking proposed improvements and there's an open PR for the groundwork at #1440.

**Comment by lovell** [comment]
Hope this helped, feel free to re-open if not.
