### ISSUE TITLE
Manipulate buffer on the pixel level but let the rest of the image untouched

### ISSUE THREAD

**Issue by akidee** [lovell/sharp#1452]
My uncompressed input TIFF has 3 channels a 16 bits and important metadata and profile. I want to access and change some pixels by their raw values and then save the resulting image in the same format, size and with the same metadata:

```
img.metadata().then(data => {
	console.log(data)
	// Get metadata to known how to access single pixels ...
	img.toBuffer().then(buffer => {
		// Manipulate buffer ...
		img.clone() // Clone metadata, too - sharp(Buffer) would just set the raw buffer
		.overlayWith(buffer) // What is the best way to just re-set the buffer? What about joinChannel()?
		.toFile(newFileName).then(
			info => { console.log(info) },
			e => { console.error(e) }
		)
	}, e => { console.error(e) })
}, e => { console.error(e) })
```

Result: The image is saved as 8 bit TIFF with JPEG compression, and the metadata is missing.

**Comment by lovell** [comment]
Hello again, [withMetadata](http://sharp.pixelplumbing.com/en/stable/api-output/#withmetadata) provides control over output image metadata, [tiff](http://sharp.pixelplumbing.com/en/stable/api-output/#tiff) provides control over TIFF output options and your question at #1454 covers the bit depth.

**Comment by lovell** [comment]
Hope this helped, please feel free to re-open with more information if further help is required.
