### ISSUE TITLE
Question: Access buffer

### ISSUE THREAD

**Issue by akidee** [lovell/sharp#1453]
I want to manipulate a buffer on the pixel level. Is there a library that allows me to access and write (to) a Buffer (x, y, channel) correctly, depending on given sharp metadata?

An API like:

```
PixelAccess a = new PixelAccess(metadata, buffer)
var value = a.read(x, y, channel)
a.write(x, y, channel, newValue)
```

**Comment by akidee** [comment]
This question makes no sense as long as I cannot access the raw buffer. ( https://github.com/lovell/sharp/issues/1454 )

**Comment by lovell** [comment]
Closing in favour of #1454
