### ISSUE TITLE
Enhancement: set pixel depth on raw output

### ISSUE THREAD

**Issue by akidee** [lovell/sharp#1454]
I read a quite large uncompressed TIFF (107 MB) into a buffer:

`img.raw().toBuffer().then(buffer => { console.log(buffer.length) })`

Result: `53496576` which is only half of the expected value:
The image has 3 channels a 16 bits and its dimensions are 5208 x 3424, and so I'd expect `buffer.length` to be 5208 * 3424 * 3 * 2 = 106993152

It seems that the buffer is manipulated by reducing depth to 8 bit.

**Comment by lovell** [comment]
Hello, returning 8-bit integer pixel values is the current documented behaviour.

> "Force output to be raw, uncompressed uint8 pixel data."
> http://sharp.pixelplumbing.com/en/stable/api-output/#raw

**Comment by akidee** [comment]
I request this feature. Supporting 16 bit by request would be great since "raw" should at least imply that all information from the original image is accessible.

**Comment by lovell** [comment]
Optional parameters could be added to the [raw](http://sharp.pixelplumbing.com/en/stable/api-output/#raw) function, allowing a `depth` property e.g. `uchar` (default), `ushort`, `float` etc. to match [libvips' nicknames](https://github.com/libvips/libvips/blob/7da31386c73cacc17116529463529014f8525cc1/libvips/iofuncs/enumtypes.c#L748-L757).

**Proposed API:**
```javascript
sharp(input)
  .raw({ depth: 'ushort' })
  .toBuffer()
  ...
```

Happy to accept/help with a PR if you're able.

**Comment by lovell** [comment]
v0.29.0 now available with this feature.
