### ISSUE TITLE
how to get RGBA dataArray from png?

### ISSUE THREAD

**Issue by yyman001** [lovell/sharp#1456]
I need RGBA array from anywhere file from png, i need replace data from a new png, i know the data from web, look this demo, but i don't know how to get file data to `ImageData`, No API was found.
```js
        let colorObject = Color(this.color)
        let canvas = this.$el.querySelector('#canvas')
        let context = canvas.getContext('2d')
        var myImageData = context.createImageData(400, 400)
        let data = myImageData.data
        let dataLen = data.length
        for (let i = 0; i < dataLen; i += 4) {
          data[i] = colorObject.color[0]
          data[i + 1] = colorObject.color[1]
          data[i + 2] = colorObject.color[2]
          // 透明度 0 ~ 255
          data[i + 3] = 255 * colorObject.valpha
        }
        context.putImageData(myImageData, 0, 0)
```

   thanks you help!

**Comment by lovell** [comment]
Hello, did you see [raw](http://sharp.pixelplumbing.com/en/stable/api-output/#raw)?

**Comment by yyman001** [comment]
Thank you very much. There are few tutorials for this library, and sometimes it is difficult to find the required API, especially if there is another language version.
