### ISSUE TITLE
IPTC Metadata keywords

### ISSUE THREAD

**Issue by NimaiMalle** [lovell/sharp#1458]
I'd like to access the **Keywords** within jpg EXIF data.
With ImageMagick `identify -verbose` I can see the following data:
```
  Profiles:
    Profile-8bim: 7866 bytes
    Profile-exif: 6375 bytes
    Profile-icc: 3144 bytes
    Profile-iptc: 103 bytes
      City[1,90]: 0x00000000: 254700                                        -%
      City[1,90]: 0x00000000: 254700                                        -%
      unknown[2,0]: 
      Created Date[2,55]: 20170519
      Created Time[2,60]: 082914+0000
      unknown[2,62]: 20170519
      Keyword[2,25]: dance
      Keyword[2,25]: sundancers
      Keyword[2,25]: westwood
    Profile-xmp: 8848 bytes
```

I'd love to get those **Keyword**  values!  Is there a way to get my hands on those from the sharp metadata?  (These were from a file exported from Adobe Lightroom with keywords, but I hope they're standardized.)

**Comment by lovell** [comment]
Hello, these are available in the `iptc` property provided by [metadata](http://sharp.pixelplumbing.com/en/stable/api-input/#metadata).

```javascript
const { iptc } = await sharp(input).metadata();
```
You can then use a module like [iptc-reader](https://www.npmjs.com/package/iptc-reader) to parse the Buffer.

**Comment by NimaiMalle** [comment]
OH!  Sheesh.  I was looking into the exif section only.  Shoot.  In my head, I was dumping out all the data returned by `metadata` - my bad!  Thank you for the helpful reply.

I'm currently looking into an easy way to parse the iptc data buffer.  My current approach is using https://github.com/bpatrik/ts-node-iptc but I needed to make one of their private functions public, since the main API call there wants the whole image file data and `sharp` has already provided access directly to the iptc buffer.  This worked, and I got the parsed data out.  I've got a PR in to bpatrik to make that inner function public.  Please let me know if there's a simpler way, and thanks again!

**Comment by NimaiMalle** [comment]
PR accepted!  Sweet.

My code (TypeScript) now looks like this, where `metadata` is coming from the sharp metadata() function:
```
import { IptcParser } from 'ts-node-iptc'
...
	const iptcData = IptcParser.readIPTCData(metadata.iptc)
```

**Comment by laurent22** [comment]
For me it doesn't work if I read the "iptc" property provided by Sharp, it just says that it's an invalid image. However this works:

```
import {IptcParser} from "ts-node-iptc";
const data = await readFile(imagePath);
const iptcData = IptcParser.parse(data);
```

In other words, Sharp is not actually needed in this particular case.
