### ISSUE TITLE
Output file much smaller

### ISSUE THREAD

**Issue by LucidityDesign** [lovell/sharp#1466]
I'm using sharp to convert the colorspace but the output image is much smaller than the input. Is that expected behavior? How can I avoid it?

If I run the following code my input JPEG (2.5MB) gets saved with 1.7MB and my input PNG (4.6MB) with 3.7MB:

```
const converColorSpace = sharp()
      .withMetadata()
      .toColourspace('srgb')
```

If I convert all images to JPEG with `quality: 100` the file sizes increase (as expected) but I don't want to change the file-format.

**Comment by lovell** [comment]
Hello, did you see the `force` parameter of the [jpeg](http://sharp.pixelplumbing.com/en/stable/api-output/#jpeg) operation?

```javascript
sharp()
  .jpeg({
    quality: 100,
    force: false
  })
  ...
```

**Comment by LucidityDesign** [comment]
Thanks that solves the problem with JPEG images. However with
```
const converColorSpace = sharp()
  .withMetadata()
  .jpeg({
    quality: 100,
    force: false
  })
  .png({
    quality: 9,
    force: false
  })
  .toColourspace('srgb')
```
the output-png file is still smaller.

**Comment by lovell** [comment]
Did you see the `compressionLevel` and `adaptiveFiltering` properties of [png](http://sharp.pixelplumbing.com/en/stable/api-output/#png)? The default values are optimised for file size as the PNG format is lossless.
