### ISSUE TITLE
Sharp resizing quits with - exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by redevill** [lovell/sharp#1468]
Trying to track down an error while using the Sharp lib V0.21.0
Environment:
Win10
Node 9.10.1
Sharp V0.21.0
IISNode v0.2.18
chokidar V2.0.4
express V4.16.3

At initialization of express app, of the all the files in a watched folder are fed to sharp for resizing.
Local file folders are set as the source and destination. There are 15,000 files or so, and the startup thread dies with the exit code above.

Had it die with this exit code also:
Process finished with exit code -1073740940 (0xC0000374)

I am guessing some kind of interaction between it and iisnode
https://stackoverflow.com/questions/12282249/iis-app-pool-crashing-with-exception-0xc0000005

Any help would be appreciated.
Thanks

**Comment by lovell** [comment]
Has `chokidar` been configured via `awaitWriteFinish` to wait for the file to be complete before the event is fired?

> "By default, the add event will fire when a file first appears on disk, before the entire file has been written" https://github.com/paulmillr/chokidar#performance

The use of Node 9 suggests sharp was compiled from source. Are you able to use Node 8 or 10 and try with the pre-built binaries?

**Comment by redevill** [comment]
Hello Lovell,
Thank you for the suggestions!It is not configured to wait - !!! THANK YOU, this makes the most sense to be the cause.I will investigate this first!

*******During NPM install, I did need to make sure the python and compiler were available - so yes I believe it was compiled during install.I did not explicitly compile the binaries.
Will try and change the Node version - but this may not be so easy for me. Quite a few dependencies, and there is a happy medium where all the libs function.
Thank you
Et

**Comment by redevill** [comment]
**_Documenting Trials:_**
**Short answer** - File watcher was isolated away from sharp so, determined it is not the cause of the Error.

**Documented Detail:**
Lovell suggested, (nicely) that my file watcher implementation was bad.
Raising file addition events before the file was completed writing. This was indeed the case.
I changed this:

 `private init_FileWatcher(srcPath: string) {
    chokidar.watch(Config.ImageRepoPath,
      {ignored: [/(^|[\/\\])\../, /Thumbs\.db$/],
      // Does NOT fire add events when watch on dir starts
      ignoreInitial: true,
      // Make sure the file has finished writing before sending to Sharp for compression
      awaitWriteFinish: { stabilityThreshold: 2000, pollInterval: 200 }
      }).on('all',
      (event: string, path: string) => this.imageChangeHandler(event, path));
  }`

I also changed the action so that the file watcher would not be involved at startup. Simply feed the entire directory into sharp, to ensure the resized folder is synchronized with the source.
As follows:

` private startup_ProcessAllImages(srcPath: string) {
    const files: string[] = fs.readdirSync(srcPath);
    files.forEach((file: string) => {
      //Sending as a change event should ensure an overwrite for all compressed files.
      //Bringing the folder under synchronization when starting up.
      this.imageChangeHandler('change', srcPath + path.sep + file);
    });
  }`

The imageChangeHandler calls this relevant piece for the resize:

`    sharp(srcPath)
        .resize({width: myWidth})
        .toFile(outPath)
        .then((data: any) => {
          console.log('Done shrink of ' + srcPath + ' to ' + outPath);
        })
        .catch((err: Error) => {
          console.log('Resize for: ' + srcPath + ' had Error: ' + err.message);
        });`

**Comment by lovell** [comment]
Great, thanks for confirming this was the problem.
