### ISSUE TITLE
Building sharp with libvips 8.7.1?

### ISSUE THREAD

**Issue by msageryd** [lovell/sharp#1470]
I'm running sharp in an Alpine Docker container and libvips has problem writing to /tmp. It looks like this is fixed (by Lovell): https://github.com/lovell/sharp/issues/1436

Setting VIPS_DISC_THRESHOLD to a really high number makes it work, but this doesn't seem like a stable workaround.

Is there any way of building sharp with libvips 8.7.1? Or even better, are there any plans to include 8.7.1 in sharp?

Edit:
BTW, thank you soo much for this awesome library!

**Comment by lovell** [comment]
Hello, sharp will look for and use a globally-installed version of libvips. If you need libvips v8.7.1 you can build it from source, install globally then rebuild sharp.

**Comment by lovell** [comment]
http://sharp.pixelplumbing.com/en/stable/install/

**Comment by msageryd** [comment]
Thanks a bunch!
Do you know how building from source would affect my package-lock.json?

**Comment by lovell** [comment]
sharp will look for a globally-installed version of libvips that meets a required [minimum](https://github.com/lovell/sharp/blob/master/package.json#L120). If it fails to find this it will download and use pre-built binaries of that version. These decisions are logged during `npm install`.

Installing a specific version of libvips globally before `npm install` is run against a lockfile will provide a reproducible build.
