### ISSUE TITLE
Disable image smoothing

### ISSUE THREAD

**Issue by edwjusti** [lovell/sharp#1473]
Is it possible to disable smoothing on resized images so that images are pixeled?

**Comment by lovell** [comment]
Hello, did you see the `kernel` option of the [resize](http://sharp.pixelplumbing.com/en/stable/api-resize/#resize) operation? Try nearest-neighbour interpolation for a more pixellated output.

**Comment by edwjusti** [comment]
Oh thanks! That's exactly what I was looking for.
