### ISSUE TITLE
WebAssembly

### ISSUE THREAD

**Issue by DSM3DIA** [lovell/sharp#1476]
It would be amazing to get this compiled to WebAssembly!

I am specifically wanting to run Sharp on CloudFlare workers which doesn't support native binaries (libvips), but does support WebAssembly.

Thanks,

Dane

**Comment by lovell** [comment]
This has been discussed previously at https://github.com/libvips/libvips/issues/192 - libvips and its dependencies will also need to be compiled. Good luck!

**Comment by wis** [comment]
I appreciate @lovell 

> Good luck!

I with I could hear how you'd say that IRL, I can't over the internet, do you mean it's gonna be a really hard task?

[here is a list of libvips' dependencies:](https://www.archlinux.org/packages/community/x86_64/libvips/) 

- cfitsio [A library of C and Fortran subroutines for reading and writing data files in FITS (Flexible Image Transport System) data format]
- fftw [A library for computing the discrete Fourier transform (DFT)]
- imagemagick [An image viewing/manipulation program]
- libexif [A library to parse an EXIF file and read the data from those tags]
- libgsf [An extensible I/O abstraction library for dealing with structured file formats]
- libheif [HEIF file format decoder and encoder]
- libimagequant [Library for high-quality conversion of RGBA images to 8-bit indexed-color (palette) images]
- librsvg [SVG rendering library]
- libwebp [WebP library and conversion tools]
- libxml2 [XML parsing library, version 2]
- openexr [An high dynamic-range image file format library]
- orc [Optimized Inner Loop Runtime Compiler]
- pango [A library for layout and rendering of text]
- poppler-glib [Poppler glib bindings]

does sharp not use any of the functionalities that depend on any of these dependencies and thus it can be/was removed?
which dependencies do you think is gonna be the hardest to port/compile with emscripten?

**Comment by lovell** [comment]
Let's track this at https://github.com/libvips/libvips/issues/192
