### ISSUE TITLE
Correct way to convert 1, 3 or 4-channel images to RGBA

### ISSUE THREAD

**Issue by dstearnsadobe** [lovell/sharp#1481]
Sorry if this is a dumb question, but after hours of searching I couldn't find an answer, so I thought I'd try asking directly. I'm using sharp to decode source images into raw RGBA (downstream code wants that). The source images can be 1-channel grayscale, 3-channel RGB, or 4-channel RGBA images. What's the simplest and most reliable way to ensure that any of these types decode to a 4-channel RGBA buffer?

At first, we were doing:
```javascript
// sourceImageBuffer contains the bytes of the source image
const img = sharp(sourceImageBuffer);
const {width, height, hasAlpha} = await img.metadata();
if (!hasAlpha) {
  img.joinChannel(Buffer.alloc(width * height, 255), { raw: { width, height, channels: 1 }})
}
const decodedBuffer = await img.raw().toBuffer();
```

That works well for 3 and 4-channel images, but isn't working as expected for 1-channel grayscale images. That makes sense to me, as the `.joinChannel()` would add a second channel, not a fourth one.

I was able to make it work using code like this, but it seems rather awkward and possibly inefficient to me:

```javascript
// .raw() seems to automatically decode 1-channel to 3
let decoded = await sharp(sourceImageBuffer).raw().toBuffer({ resolveWithObject: true});
const {width, height, channels} = decoded.info;

// if there are still only 3 channels, add an opaque alpha channel
if (channels === 3) {
  decoded = await sharp(decoded.data, { raw: { width, height, channels }})
      .joinChannel(Buffer.alloc(width * height, 255), { raw: { width, height, channels: 1 }})
      .toBuffer({ resolveWithObject: true });
}

// decoded.data now has 4-channel RGBA bytes,
// regardless of input image
```

This code seems to work for 1, 3, or 4-channel source images. But I'm guessing there's an easier, more-elegant, and more-efficient way to accomplish this that I'm not seeing at the moment. Any advice/help you can provide would be most appreciated!

**Comment by dstearnsadobe** [comment]
I also tried the approach of conditionally adding `.joinChannel()` after the `.raw()` step, like so:
```javascript
let img = sharp(sourceImageBuffer);
const {width, height, channels} = await sharp.metadata();

let img = img.raw();
if (channels < 4) {
  img = img.joinChannel(Buffer.alloc(width * height, 255), { raw: { width, height, channels: 1 } });
}

let decodedBuf = await img.toBuffer();
```
This worked for 3 and 4-channel images, but the 1-channel grayscale image ended up all black. I thought this might work given that `.raw().toBuffer()` seems to convert the 1-channel grayscale image to 3-channel. But if I'm misunderstanding things, please correct me!

**Comment by lovell** [comment]
Hope this helped, please re-open with more details if not.
