### ISSUE TITLE
Quality for JPEG not work

### ISSUE THREAD

**Issue by extensionsapp** [lovell/sharp#1482]
Hello.

```
                Sharp('dog.jpg')
                    .resize({width: 500, withoutEnlargement: true})
                    .jpeg({quality: 10, progressive: true})
                    .webp({quality: 50, lossless: true})
                    .png({quality: 50, compressionLevel: 8})
                    .toFile(path.join(filepath, fieldname, size, filename),
                        function (err) {
                            console.log(err);
                        });
```

**Original: 44 KB**

![dog](https://user-images.githubusercontent.com/8192379/49263872-e0c16100-f454-11e8-93da-25fd52e859bc.jpg)

**Quality 10%: 270 KB**

![1543543222958-dog](https://user-images.githubusercontent.com/8192379/49263876-e8810580-f454-11e8-909e-0178be48df7d.jpg)

How to compress JPEG image?

**Comment by lovell** [comment]
Hello, the output you've posted here is PNG rather than JPEG, hence the larger size. PNG is lossless and does not have a `quality` setting.

Did you see the `force` option on the `jpeg()`, `webp()` and `png()` functions? You'll probably want to set it to `force: false` for all three if you're specifying all three.

**Comment by extensionsapp** [comment]
@lovell Thank you very much.

```
                Sharp('dog.jpg')
                    .resize({width: 500, withoutEnlargement: true})
                    .jpeg({quality: 10, progressive: true, force: false})
                    .webp({quality: 50, lossless: true, force: false})
                    .png({quality: 50, compressionLevel: 8, force: false})
                    .toFile(path.join(filepath, fieldname, size, filename),
                        function (err) {
                            console.log(err);
                        });
```

**Quality 10%: 18 KB**

![1543584532539-dog](https://user-images.githubusercontent.com/8192379/49292082-ec447480-f4b4-11e8-96b8-284f536c4b91.jpg)
