### ISSUE TITLE
Sharp is crashing on image conversion to .dz when the output folder name length is more than 24 character 

### ISSUE THREAD

**Issue by vinaymuthanna0727** [lovell/sharp#1487]
Hi ,

On Image conversion to .dz sharp is crashing.
When the image conversion output folder name length is more than 24 character sharp is crashing .
I have tried with multiple input with 24 and less than 24 number of character it works fine.
Its falling only when the folder name length is > 24 .

Below example ouput file name
 var outputPath = "E:/EDrive/Scan/TileScan_003--Stage00--t00--Z00--C00.dz"

TileScan_003--Stage00--t00--Z00--C00.dz has 36 character so it is failing. 

TileScan_003--Stage00--t.dz has 24 Its work .

**version of sharp/libvips are:** 
"sharp": "^0.20.0" and Windows platform ,OS windows 10 

**Standalone code**

var sharp = require('sharp');
var createDeepZoomImages = function (data) {
    return new Promise((resolve, reject) => {
        var inputPath = "E:/EDrive/ImageScan_001.tif";
        var fileName = "TileScan_003--Stage00--t00--Z00--C00";
        var outputPath = "E:/EDrive/Scan/TileScan_003--Stage00--t00--Z00--C00.dz"
        var pixels = 0;        
        getPixels(inputPath).then(function (numberOfPixels) {  
            sharp(inputPath)
                .png()
                .limitInputPixels(numberOfPixels + 1)
                .tile({size: 256})
                .toFile(outputPath, function (err, info) {
                    if (err) 
                        return reject(err);
                    
                    return resolve("1");
                });
        }, function (err) {
            return reject(err);
        });
    });
};

//This function will return the numberOfPixels(1920001)
var getPixels = function (inputPath) {
    return new Promise((res, rej) => {
        sharp(inputPath)
            .metadata()
            .then(function (metadata) {
                var pixels = (metadata.width * metadata.height) + 1;
                return res(pixels);
            }, function (err) {
                return rej(err);
            });
    });
};

It will great help if i get any solution the above problem 

Thanks
Vinay

**Comment by lovell** [comment]
Hello, are you able to reproduce using the latest version v0.21.0? Are you able to reproduce on a non-Windows platform such as Linux?

**Comment by vinaymuthanna0727** [comment]
Resolved .Tried in other windows PC it was working fine.
Thanks for the support
