### ISSUE TITLE
Webp Version 

### ISSUE THREAD

**Issue by aliaburas80** [lovell/sharp#1488]
Hi, can you please provide us with Webp version, and how could we update it to latest version.
Thanks

**Comment by lovell** [comment]
Hello, did you see [sharp.versions](http://sharp.pixelplumbing.com/en/stable/api-constructor/#versions)?

**Comment by aliaburas80** [comment]
Yes thanks webp version is 0.6.0, but the last update from google is 1.0.1, so there is away to update the webp with latest one?
Thank you

**Comment by lovell** [comment]
The precompiled binaries for the latest sharp v0.21.0 provide libwebp v1.0.0.

For libwebp v1.0.1 you will need to compile and globally-install libvips and its dependencies, including libwebp, from source, then re-install sharp.

**Comment by aliaburas80** [comment]
Thank you so much my webp now is webp: '1.0.0'
