### ISSUE TITLE
Jpeg 2000 & jpeg XR support 

### ISSUE THREAD

**Issue by RoyiNamir** [lovell/sharp#1489]
I think i've read somewhere that sharp supports also jpeg 2000 & jpeg xr
However - I don't see any support in the docs for it.

Do Sharp support those formats ? and if so , where is it in the docs ?

**Comment by lovell** [comment]
Hello, to read .jp2 and .jxr files you'll need to compile and globally-install libvips with *magick (or possibly openslide) support, then re-install sharp.

https://libvips.github.io/libvips/install.html

**Comment by RoyiNamir** [comment]
Wow. thanks for the speedy response !!!

**Comment by RoyiNamir** [comment]
@lovell 
And once I install all Exe and binaries , would Sharp be able to convert images to jp2? How ? The docs don't mention it.

**Comment by lovell** [comment]
If you're using Windows then all bets are off, sorry. As you suggest, if this were supported then it would be documented.
