### ISSUE TITLE
PNG with XMP metadata

### ISSUE THREAD

**Issue by GuyBachkhaznadji** [lovell/sharp#1491]
When using .metadata() on a png it loses the iptc attribute. 

imgBuffer below is an arrayBuffer than contains the image itself. 
```javascript 
sharp(imgBuffer)
    .metadata()
    .then((metadata) => {
      console.log(metadata)
    });
```

Is this expect behaviour, as it does not lose the iptc attribute with a jpeg?

**Comment by lovell** [comment]
Hello, are you able to share an example PNG image that both contains IPTC metadata and exhibits this behaviour?

**Comment by GuyBachkhaznadji** [comment]
Hi, thanks for getting back to me so quickly.

Yes here is a PNG with IPTC and when we run the code snippet above with it we don't seem to not see any of the IPTC. 

Also if we crop it and use `.withMetadata()` we also seem to lose IPTC on the output. (We also lose TIFF)

https://s3-eu-west-1.amazonaws.com/guy-cropping-test/cropped-images/strawberries.png

**Comment by lovell** [comment]
Thank you, what IPTC metadata are you expecting from this example image?

**Comment by GuyBachkhaznadji** [comment]
This is the IPTC that is on the PNG - https://s3-eu-west-1.amazonaws.com/guy-cropping-test/cropped-images/Screen+Shot+2018-12-05+at+00.26.15.png 

Also this is the TIFF data that also disappears - https://s3-eu-west-1.amazonaws.com/guy-cropping-test/cropped-images/Screen+Shot+2018-12-05+at+00.26.31.png

**Comment by lovell** [comment]
The metadata in the sample PNG image is XMP rather than IPTC.

libvips only recently added support for reading XMP metadata from PNG images - see https://github.com/libvips/libvips/issues/1073 - it will need to be compiled from source for this to work right now.

**Comment by GuyBachkhaznadji** [comment]
Okay great, thanks for identifying the issue. 

Is this something Sharp will be doing soon or something I need to do on my end?

**Comment by lovell** [comment]
This will be included in libvips v8.8.0, which a future version of sharp will bundle in its precompiled binaries.

**Comment by GuyBachkhaznadji** [comment]
Great thanks for all your help

**Comment by lovell** [comment]
sharp v0.23.0 / libvips v8.8.1 is now available.
