### ISSUE TITLE
metaReader

### ISSUE THREAD

**Issue by sm2017** [lovell/sharp#1495]
```js
const metaReader = sharp()
  .metadata()
  .then(info => {
    console.log(info)
  })
  .catch(err => {
    console.log(err)
  })
```

is metaReader fast enough to using it in a high throughput server? is it block thread?
I want to `pipe(metaReader)` a stream , stream is a file uploaded by end user

**Comment by lovell** [comment]
> "Everything remains non-blocking thanks to libuv, no child processes are spawned and Promises/async/await are supported."

http://sharp.pixelplumbing.com/en/stable/#fast

**Comment by sm2017** [comment]
@lovell I want to

* Get a file from end user
* Check dimension
 * must be square
   * larger than 100x100
   * less than 1000x1000
* Generate thumbnail

I want to check dimension in main thread , but generate thumbnail in a worker thread (using rabbitmq)

I see http://sharp.pixelplumbing.com/en/stable/performance/
You have 25.30 Ops/sec , is it 1000/25=40ms blocks thread? If yes I must use worker thread , If no , can I use main thread to generate thumbnail?
What about dimension? how much it block thread?

**Comment by lovell** [comment]
Please see #1297

**Comment by lovell** [comment]
Hope this helped, please feel free to re-open with more details if not.
