### ISSUE TITLE
sharp.format is not a function on require

### ISSUE THREAD

**Issue by DevCubeHD** [lovell/sharp#1496]
After installing sharp I get
`TypeError: sharp.format is not a function`
I already tried reinstalling. I'm using electron and webpack, is there any relation or does this error appear for more people?

**Comment by DevCubeHD** [comment]
![image](https://user-images.githubusercontent.com/10380127/49593221-53f63600-f973-11e8-8cfd-e834262d1e78.png)

**Comment by jaubourg** [comment]
If you minify the code, it may be related to https://github.com/lovell/sharp/issues/1474

**Comment by DevCubeHD** [comment]
Hm, I dont use minification in development, but as in the comment in your reference I think its something about the sharp.node file... running an older version I had versions with missing phyton installation... are there hidden dependencies?

**Comment by jaubourg** [comment]
I'm afraid this is then way above my knowledge of the internals of sharp then :/

I remember toying with sharp in electron at one point but it was before it came with prebuilts. I just know I had to rebuild the dependency when switching from normal node to electron. Not sure it may be related to your problem.

Let us summon @lovell ;)

**Comment by DevCubeHD** [comment]
Thank you sir @jaubourg and well, that was an quick answer @lovell!
I am using electron dev server with create-react-app... I think the app is just started by "electron ."

**Comment by lovell** [comment]
https://electronjs.org/docs/tutorial/using-native-node-modules

**Comment by DevCubeHD** [comment]
![image](https://user-images.githubusercontent.com/10380127/49602038-c5d87a80-f987-11e8-99f8-c31cb86d70c2.png)
Keeps on failing, I dont get it...

**Comment by lovell** [comment]
> "python (v2.7 recommended, v3.x.x is not supported)"

https://github.com/nodejs/node-gyp#installation

**Comment by DevCubeHD** [comment]
![image](https://user-images.githubusercontent.com/10380127/49616831-68a5ee80-f9b2-11e8-996c-923d4ed06317.png)
Thank you. Rebuild went trough now, but error does still occur.

Maybe the following warning helps you out:
![image](https://user-images.githubusercontent.com/10380127/49616906-a73ba900-f9b2-11e8-8b37-e58ba70c51b8.png)
It appears after the error in the console, might also be useless.

I also tried 0.20.8, different error which cannot be fixed with the given instructions
![image](https://user-images.githubusercontent.com/10380127/49617033-31840d00-f9b3-11e8-8166-970d3e255667.png)

**Comment by DevCubeHD** [comment]
Alright, I totaly agree with you. I will move my question to stackoverflow
