### ISSUE TITLE
Sharp doesnt generate changed values

### ISSUE THREAD

**Issue by vaxerski** [lovell/sharp#1497]
Hello,

So i have a script,
`svgToImg.from(cardSVG).toPng({`
`    path: './assets/newcard/text.png'`
`  }).then(function(){`
`      sharp('./assets/newcard/underlay.png')`
`        .overlayWith('./assets/newcard/bg.png')`
`        .toFile('./assets/newcard/step.png')`
`        .then(function(){`
`            setTimeout(function () {`
`      sharp('./assets/newcard/step.png')`
`        .overlayWith('./assets/newcard/text.png')`
`        .toFile('./assets/newcard/render.png')`
`          })`
`        })`
`}, 100)`

but when the image passed from svgToImg (text.png) changes, sharp doesn't generate new image with changes, it just passes the old one.

Deleting the old generated image doesn't work, sharp still generates with the first text.png, even if it changes.

Any solutions other than crashing the app after every render?

**Comment by lovell** [comment]
Hello, if the contents of a file change but the path remains the same then you'll need to disable caching within libvips via `sharp.cache(false)` - see http://sharp.pixelplumbing.com/en/stable/api-utility/#cache

**Comment by vaxerski** [comment]
thank you, fixed the issue.
