### ISSUE TITLE
VipsImage: memory area too small --- should be X bytes, you passed Y

### ISSUE THREAD

**Issue by dzaraev** [lovell/sharp#1499]
Hello, I checked all the "VipsImage: memory area too small" but didn't found my case;
My original image has size as 612x612 pixels and I'm trying to create sharp object out of buffer previously created from that image.
Firstly I load it and save its size to use later for "raw" options:
sharp("resources/board.png")
    .toBuffer((err, data, info) => {
        BoardBuffer = data;
        BoardHeight = info.height;
        BoardWidth = info.width;
        BoardChannels = info.channels;
    });

then, later in the code I'm trying to reuse this buffer like this:
let rawOptions = {
        raw: {
            width: BoardWidth,
            height: BoardHeight,
            channels: BoardChannels 
        }
    };
let basePromise = sharp(BoardBuffer, rawOptions ).raw().toBuffer();

but once it starts to work - there's exception occurs:
(node:14024) UnhandledPromiseRejectionWarning: Error: VipsImage: memory area too small --- should be 1498176 bytes, you passed 60229

but my rawOptions tells that 612*612*4 = 1498176 isn't it?

And I tried to hardcode that values like 
sharp(BoardBuffer, {raw:{ width: 612, height: 612, channels: 4 }}).raw().toBuffer();       
but that doesn't help.

I even tried to increase the height and width I put into the options manually but the "required" size just increased proportionally so I have no idea what that error's trying to tell me.

Please help and thanks in advance.

p.s. yes image is 612x612 I checked, many times)

**Comment by dzaraev** [comment]
Thanks for response!
Why should I add raw for the very first load of BoardBuffer? Couldn't I just make it as raw later - like below: sharp(BoardBuffer, rawOptions ).raw().toBuffer()  ?
Or raw works with loading from file only ?

**Comment by lovell** [comment]
Do you need `BoardBuffer` to contain compressed PNG data or uncompressed raw pixel data?

Pass `raw: { ... }` to sharp's constructor only when the input contains raw, uncompressed pixel data.

**Comment by dzaraev** [comment]
I need BoardBuffer to contain PNG data. But the topic is about this part: 
let basePromise = sharp(BoardBuffer, rawOptions ).raw().toBuffer();
And if I just remove raw() from everywhere - all will work fine.

But my original task was to make multiple overlayWith feature and I found recently in one of topics here the approach how to apply overlayWith subsequently:
https://github.com/lovell/sharp/issues/405
where your suggested code have contained .raw() options after sharp() and after overlayWith() parts
That's the reason I'm trying to use raw() here. 
But if I even add it after my sharp(BoardBuffer, rawOptions ) like 
let basePromise = sharp(BoardBuffer, rawOptions ).raw().toBuffer();
I'll get that error above. Without raw() all works fine but I suppose you added it for some reason like performance or something like..

**Comment by lovell** [comment]
The use of `raw` in the example given in #405 is to avoid the PNG decompression-compression round trip each time.

Please note the use of `sharp(input, options)` occurs only when `input` is raw, uncompressed pixel data. If the input is PNG then use `sharp(input)` only; providing `options` will cause the problem you're seeing (as sharp will attempt to treat compressed PNG data as uncompressed, raw pxiel data).

**Comment by dzaraev** [comment]
got it finally! a lot of thanks for that last clarification! Now all works fine and much more faster )
