### ISSUE TITLE
segmentation fault with broken jpeg

### ISSUE THREAD

**Issue by bkw** [lovell/sharp#150]
this tiny scripts crashes the node process both on ubuntu 14.04 and osx 10.9.5, both with libvips 7.42.1:

https://gist.github.com/bkw/5794006ac6e743a7e26e

vipsthumbnail cannot create a file from that source either, but it doesn't crash like sharp does.

**Comment by lovell** [comment]
It looks like the "JPEG datastream contains no image" error from libjpeg isn't correctly handled or bubbled up. This condition can be [reached](https://github.com/svn2github/libjpeg-turbo-code/blob/master/jdapimin.c#L259) when end-of-file (or Buffer in this case) occurs when reading image metadata.

An extra NULL reference check in sharp's image loading code should fix this - leave it with me - thanks for reporting.

Do you know of any IP/legal reasons that would prevent me adding the truncated/corrupted `02247503-02.jpg` file to sharp's test fixtures to prevent such a problem occurring again?

**Comment by bkw** [comment]
thanks for the quick response, lovell!
I have no idea wether there are any legal issues with copying that corrupt image, I'm neither working for them nor a lawyer. I doubt anybody would care or even notice.

**Comment by lovell** [comment]
This problem should now be fixed on the `intake` branch.

This will be included in the forthcoming v0.9.0 release. You can test this beforehand using:
```
npm install lovell/sharp#intake
```
I created an image with corrupt header for the tests via `head -c 1024 good.jpg >bad.jpg`

**Comment by bkw** [comment]
most excellent. I can confirm it works as expected for my usecase. Thanks a bunch!
