### ISSUE TITLE
Uncaught TypeError: exists is not a function

### ISSUE THREAD

**Issue by renz45x** [lovell/sharp#1501]
I just imported sharp in my react project then it returns this error

Uncaught TypeError: exists is not a function

Function.getRoot
node_modules/bindings/bindings.js:158
  155 |   dir = process.cwd();
  156 | }
  157 | 
> 158 | if (exists(join(dir, 'package.json')) || exists(join(dir, 'node_modules'))) {
      | ^  159 |   // Found the 'package.json' file or 'node_modules' dir; we're done
  160 |   return dir;
  161 | }

**Comment by lovell** [comment]
Hello, please see https://github.com/TooTallNate/node-bindings/issues/49 and the linked https://github.com/facebook/create-react-app/issues/3074

**Comment by renz45x** [comment]
so basically I can't use this with react only on server side like node?

**Comment by lovell** [comment]
You can, but not with `create-react-app` as it intentionally stubs out the `fs` module, which means that it is unsuitable for server-side rendering. You're likely to run into the same problem with many native modules, not just sharp.

**Comment by renz45x** [comment]
I see.. Thank you for this info! helps a lot! :)

**Comment by Gajendra28121996** [comment]
then how can a file upload work?
