### ISSUE TITLE
unable to install sharp npm in linux server

### ISSUE THREAD

**Issue by kash151183** [lovell/sharp#1504]
> sharp@0.21.1 install /usr/local/lib/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.0/libvips-8.7.0-linux-x64.tar.gz
/usr/local/lib/node_modules/sharp/install/libvips.js:80
          throw new Error(`Status ${response.statusCode}`);
          ^

Error: Status 403
    at /usr/local/lib/node_modules/sharp/install/libvips.js:80:17
    at f (/usr/local/lib/node_modules/sharp/node_modules/once/once.js:25:25)
    at ClientRequest.protocol.request.res (/usr/local/lib/node_modules/sharp/node_modules/simple-get/index.js:63:5)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:544:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
make: Entering directory `/usr/local/lib/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:25:22: fatal error: vips/vips8: No such file or directory
 #include <vips/vips8>
                      ^
compilation terminated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory `/usr/local/lib/node_modules/sharp/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.10.0-514.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/sharp
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.21.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.21.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-12T09_16_49_418Z-debug.log

**Comment by lovell** [comment]
Hello, the salient part of this error message is:
```
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.0/libvips-8.7.0-linux-x64.tar.gz
...
Error: Status 403
```
which suggests this machine cannot download the libvips binaries from GitHub. Perhaps there is a firewall or temporary network problem?

**Comment by lovell** [comment]
Hope this helped, please feel free to re-open with more details if not.

**Comment by AlexLich** [comment]
hello @lovell , similar problem: 

> > sharp@0.21.1 install C:\project\gatsby\lasted2\node_modules\sharp
> > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
> 
> info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.0/libvips-8.7.0-win32-x64.tar.gz
> C:\project\gatsby\lasted2\node_modules\sharp\install\libvips.js:77
>           throw err;
>           ^
> 
> Error: self signed certificate in certificate chain
>     at TLSSocket.onConnectSecure (_tls_wrap.js:1112:34)
>     at TLSSocket.emit (events.js:182:13)
>     at TLSSocket._finishInit (_tls_wrap.js:625:8)

Configure PC:

> OS:                                  Windows 10 Corporate 2016 
> Version OS:                     10.0.14393 build 14393
> Build OS:                         Multiprocessor Free
> Model system:                OptiPlex 5050
> Type system:                   x64-based PC
> Processor:                       Count Processors- 1.
>                                        [01]: Intel64 Family 6 Model 158 Stepping 9 GenuineIntel ~3408 MGz
> Version BIOS:                  Dell Inc. 1.6.5, 09.09.2017

$ npm config list -l

> ; cli configs
> long = true
> metrics-registry = "https://registry.npmjs.org/"
> scope = ""
> user-agent = "npm/6.5.0 node/v11.1.0 win32 x64"
> 
> ; userconfig C:\Users\MyName\.npmrc
> NODE_TLS_REJECT_UNAUTHORIZED = "0"
> msvs_version = "2017"
> proxy = "http://MyName:MyPass@domain:port/"
> python = "python2.7"
> registry = "https://registry.npmjs.org/"
> strict-ssl = false
> 
> ; builtin config undefined
> prefix = "C:\\Users\\My
> 
> Name\\AppData\\Roaming\\npm"
> 
> ; default values
> access = null
> allow-same-version = false
> also = null
> always-auth = false
> audit = true
> audit-level = "low"
> auth-type = "legacy"
> bin-links = true
> browser = null
> ca = null
> cache = "C:\\Users\\MyName\\AppData\\Roaming\\npm-cache"
> cache-lock-retries = 10
> cache-lock-stale = 60000
> cache-lock-wait = 10000
> cache-max = null
> cache-min = 10
> cafile = undefined
> cert = null
> cidr = null
> color = true
> commit-hooks = true
> depth = null
> description = true
> dev = false
> dry-run = false
> editor = "notepad.exe"
> engine-strict = false
> fetch-retries = 2
> fetch-retry-factor = 10
> fetch-retry-maxtimeout = 60000
> fetch-retry-mintimeout = 10000
> force = false
> git = "git"
> git-tag-version = true
> global = false
> global-style = false
> globalconfig = "C:\\Users\\MyName\\AppData\\Roaming\\npm\\etc\\npmrc"
> globalignorefile = "C:\\Users\\MyName\\AppData\\Roaming\\npm\\etc\\npmignore"
> group = 0
> ham-it-up = false
> heading = "npm"
> https-proxy = null
> if-present = false
> ignore-prepublish = false
> ignore-scripts = false
> init-author-email = ""
> init-author-name = ""
> init-author-url = ""
> init-license = "ISC"
> init-module = "C:\\Users\\MyName\\.npm-init.js"
> init-version = "1.0.0"
> json = false
> key = null
> legacy-bundling = false
> link = false
> local-address = undefined
> loglevel = "notice"
> logs-max = 10
> ; long = false (overridden)
> maxsockets = 50
> message = "%s"
> ; metrics-registry = null (overridden)
> node-options = null
> node-version = "11.1.0"
> noproxy = null
> offline = false
> onload-script = null
> only = null
> optional = true
> otp = null
> package-lock = true
> package-lock-only = false
> parseable = false
> prefer-offline = false
> prefer-online = false
> ; prefix = "C:\\Program Files\\nodejs" (overridden)
> preid = ""
> production = false
> progress = true
> ; proxy = null (overridden)
> read-only = false
> rebuild-bundle = true
> registry = "https://registry.npmjs.org/"
> rollback = true
> save = true
> save-bundle = false
> save-dev = false
> save-exact = false
> save-optional = false
> save-prefix = "^"
> save-prod = false
> scope = ""
> script-shell = null
> scripts-prepend-node-path = "warn-only"
> searchexclude = null
> searchlimit = 20
> searchopts = ""
> searchstaleness = 900
> send-metrics = false
> shell = "C:\\Windows\\system32\\cmd.exe"
> shrinkwrap = true
> sign-git-commit = false
> sign-git-tag = false
> sso-poll-frequency = 500
> sso-type = "oauth"
> ; strict-ssl = true (overridden)
> tag = "latest"
> tag-version-prefix = "v"
> timing = false
> tmp = "C:\\Users\\MyName\\AppData\\Local\\Temp"
> umask = 0
> unicode = false
> unsafe-perm = true
> update-notifier = true
> usage = false
> user = 0
> ; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch}" (overridden)
> userconfig = "C:\\Users\\MyName\\.npmrc"
> version = false
> versions = false
> viewer = "browser"

I work through a proxy as you can see from the configuration npm

**Comment by lovell** [comment]
@AlexLich This is a different problem to that originally reported. You're using an insecure proxy to access HTTPS content. If you have to do this then the `NODE_TLS_REJECT_UNAUTHORIZED=0` needs to be an environment variable instead of in your `.npmrc` file.

**Comment by AlexLich** [comment]
> @AlexLich This is a different problem to that originally reported. You're using an insecure proxy to access HTTPS content. If you have to do this then the `NODE_TLS_REJECT_UNAUTHORIZED=0` needs to be an environment variable instead of in your `.npmrc` file.

Sorry, do not tell me how to do this via CMD?

**Comment by lovell** [comment]
@AlexLich General questions about using Node with insecure proxies is more suited to a site such as StackOverflow - good luck!
