### ISSUE TITLE
Stream and metadata

### ISSUE THREAD

**Issue by sm2017** [lovell/sharp#1508]
How exactly metadata reader works in streams??
Do you unshift chunks?

https://nodejs.org/api/stream.html#stream_readable_unshift_chunk

I want to understand how exactly stream works? If we have an image stream, to read metadata we must consume some chunk of image stream, do you unshift it?as I see that after reading metadata we can consume stream without loosing data

**Comment by lovell** [comment]
Hello, the source code for sharp's `_write()` implementation is in https://github.com/lovell/sharp/blob/master/lib/input.js

**Comment by sm2017** [comment]
@lovel I'm willing for your response

**Comment by jcupitt** [comment]
All the image data is read into memory (but not decompressed), then various native libraries (libexif, libjpeg, libtiff, liblcms2, expat, etc.) are used to parse out metadata and present it.

When image processing starts, pixels are decompressed, processed, and recompressed without having the entire decompressed image in memory, so in a streaming manner. Metadata is reattached using various native libraries, and the memory area is sent to the output.

There has been some work in libvips to add a full streaming mode for some formats, so we would not need to buffer the whole compressed image in memory, but, for various reasons, it's not been merged.

https://github.com/lovell/sharp/issues/30 is the original discussion, I think.

**Comment by lovell** [comment]
If a single input Stream is required for multiple output purposes, e.g. to both read metadata and process the image further, the [clone](http://sharp.pixelplumbing.com/en/stable/api-input/#clone) function can help.
