### ISSUE TITLE
Build fails Windows 10 

### ISSUE THREAD

**Issue by ABQJuan** [lovell/sharp#1509]
I have followed the instructions on the Gatsby and Windows page [here](https://www.gatsbyjs.org/docs/gatsby-on-windows/) with the VS Studio 2017 configuration.

I have tried deleting the file found here: C:\Users\<user>\AppData\Roaming\npm-cache\\_libvips
I have also tried deleting the sharp.vcxproj file. 

> C:\Users\johnf\.node-gyp\11.3.0\x64\node.lib : fatal error LNK1127: library is corrupt [C:\Users\johnf\Projects\Traversy2\gatsby_crash_course\node_modules\sharp\build\sharp.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\johnf\Projects\Traversy2\gatsby_crash_course\node_modules\sharp
gyp ERR! node -v v11.3.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.21.0 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.21.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\johnf\AppData\Roaming\npm-cache\_logs\2018-12-13T14_27_46_127Z-debug.log

**Comment by lovell** [comment]
Hello, if you're able to use Node 10 then you'll get pre-compiled binaries that don't require MSVC.

**Comment by ABQJuan** [comment]
Node 11 installed. I had to uninstall and reinstall everything then I got it to install.

**Comment by Auxxy** [comment]
Hello,
I'm actually running a similar problem, just with sharp.node:
 Error: The specified procedure could not be found.
  \\?\G:\path\node_modules\sharp\build\Release\sharp.node

  - loader.js:752 Object.Module._extensions..node
    internal/modules/cjs/loader.js:752:18
[... Bunch of loader sets]
error UNHANDLED REJECTION

  TypeError: Cannot read property 'filter' of undefined
- api-runner-node.js:287 Promise.mapSeries.catch.then.results
    [checker]/[gatsby]/dist/utils/api-runner-node.js:287:42
[..Bunch of runners]

I've tried reinstalling VS redist, cleaning npm cache, reinstalling node, trying different node distribution in different project - nada. I've used Depends and I've found I'm missing a lot of UWP DLLs, is it possible that I uninstalled something and those have been deleted in the process? 
In all I'm missing over 30-something files, from things like "API-MS-WIN-CORE-APIQUERY-L1-1-0.DLL" to  "API-MS-WIN-CRT-UTILITY-L1-1-0.DLL", etc. 
However I've then used Depends with the same sharp set and it also found those dll's missing, so I'm guessing it's not system-related but rather installation related. 
Do you maybe have any advice as to how to continue?
