### ISSUE TITLE
format modifies options objects given to it

### ISSUE THREAD

**Issue by jaubourg** [lovell/sharp#1516]
```js
const options = {
  "type": "jpeg",
  "quality": 50,
};

sharpInstance.format( options );

options.hasOwnProperty( "trellisQuantisation" ); // true
```

Bumped into this while doing some unit testing where I was using the object given to `format` elsewhere in a `deepEqual`.

It's usually considered good practice not to modify objects passed as arguments. I personally thought I was going mad before realizing `sharp.format` had this undocumented side effect.

Not sure if this is generalized to the whole code base.

**Comment by jaubourg** [comment]
I had some brain malfunction, it's `jpeg()`, `webp()`, `png()`, etc.

Was thinking about the old API :/

**Comment by lovell** [comment]
Good spot, thanks for reporting this. The options of `jpeg` with an alternative spelling were affected - commit a54fe9f7 should deal with the problem.

**Comment by jaubourg** [comment]
Thanks for this @lovell and merry Christmas 😊

**Comment by lovell** [comment]
v0.21.2 now available.
