### ISSUE TITLE
Take advantage of libvips v8.1.0+ features

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#152]
Features of v8.1.0+ we can take advantage of:

* [x] Remove all the version-specific pre-processor `#if` statements
* [x] Switch to new `vips_(un)premultiply` API for transparencies
* [x] Allow `normalize` operation on win32 - see https://github.com/jcupitt/libvips/commit/7495690cd6cf387c76a6043897bbbf765a0dc846
* [x] Use NanAssignPersistent/NanDisposePersistent to prevent GC of input buffer instead of taking a memcpy - ses https://github.com/jcupitt/libvips/commit/6ff1d5320b111a526224f4ade070b8e65313f4cf

Supplying pre-built binaries as part of #42 should happen first.

**Comment by lovell** [comment]
This move can take advantage of the new `vips_resize` API - see also #126

**Comment by gasi** [comment]
:+1:

**Comment by lovell** [comment]
I plan to tackle this task in two stages:

1. Use libvips 8.1.x features via the C bindings, then (in a later release)
2. Switch to the C++ bindings

**Comment by oaleynik** [comment]
@lovell :+1:

**Comment by lovell** [comment]
Looks like Windows can't handle memory allocated by one shared library being freed in another - https://ci.appveyor.com/project/lovell/sharp/build/240 - will probably have to use [FreeCallback](https://github.com/nodejs/nan/blob/master/doc/buffers.md#api_nan_free_callback) to solve this.

**Comment by lovell** [comment]
C++ migration moved to #299

**Comment by lovell** [comment]
The `look` branch has now been merged to the `master` branch pending release.
