### ISSUE TITLE
Forced output format can sometimes be ignored when chained

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#1528]
As reported in https://github.com/lovell/sharp/issues/1156#issuecomment-450717812

Use of the following:
```javascript
sharp
  .png({
    force: true
  })
  .jpeg({
    force: false
  })
```
should produce PNG output for JPEG input, but instead produces JPEG output.

Need to modify the logic in the internal `_updateFormatOut` function to only update when `force: true`.

**Comment by lovell** [comment]
Commit 30ca424 adds the fix plus a test that would previously have failed.

**Comment by polarathene** [comment]
@lovell awesome thanks for this :)

I see that the v0.21.2 milestone is slowly growing with linked issues(all presently marked ready-to-ship), do you have any plans on when to release?(if it's a while away I guess I could build from the commit for now).

**Comment by lovell** [comment]
v0.21.2 now available.
