### ISSUE TITLE
w Webpack 4 browser-side is failing on libvips

### ISSUE THREAD

**Issue by rowntreerob** [lovell/sharp#1529]
Env.  ubuntu 16.04  / Webpack 4.0

installing sharp, running tests works fine in linux / bash using version of libvips that is a dependency of sharp. There is no installed version libvips on the system outside this package. 

BUT , when i run webpack build for std webapp, i get libvips warnings  -- PHOTO 1
--details --
the requires right at top of ./sharp/lib/libvips.js are failing...

```
const fs = require('fs');      *******  this module not found at runtime in browser
const os = require('os');
const path = require('path');
const spawnSync = require('child_process').spawnSync;
const semver = require('semver');
const platform = require('./platform');
```

 

And when i run in the browser , its failing on constructor for new Sharp()  --PHOTO 2

Im using standard webpack config for bundle on a JS file for an entrypoint. 

The webpack warn points at line 51  in libvips and i hava photo of that from devtools FWIW

im not expert at Webpack but it seems like the webpack build is mis-handling the dependecies for this node package for some reason??

==  webpack config    chunk 
```
  entry: {
    main: "./app/scripts/main.js",
...

  module: {
    rules: [   

   { test: /\.js$/,
        exclude: [
          path.resolve(__dirname, "node_modules"),
          path.resolve(__dirname, "app/scripts/cacheWorker.js")
        ],
        use: {
          loader: 'babel-loader',
            options: {
              presets: ['@babel/preset-env'],
              "plugins": [
                ["@babel/plugin-proposal-decorators", { "legacy": true }],
                ["@babel/plugin-syntax-dynamic-import"],
              ],
            }
        }
      },

```

[photo 1](https://user-images.githubusercontent.com/169984/50575880-1c847900-0dbb-11e9-9964-0b8d109702a1.png)

[photo 2](https://user-images.githubusercontent.com/169984/50575887-37ef8400-0dbb-11e9-855b-16a6a4720db1.png)

**Comment by lovell** [comment]
Hello, did you see https://webpack.js.org/configuration/externals/ ?

**Comment by rowntreerob** [comment]
I did not see that section. 

so i should use 'sharp' as an external   OR

i should use 'libvps' as an external ??  im confused.

**Comment by rowntreerob** [comment]
i want to use 'sharp' on the client?  need to downscale 12M photos from phone's camera before POST ing it to the back end.  If the sharp stuff is not bundled then it will not work on the client.

**Comment by lovell** [comment]
This is a native module for Node.js - it won't work in a web browser - perhaps try [jimp](https://www.npmjs.com/package/jimp).

**Comment by rowntreerob** [comment]
my mistake .. sorry
