### ISSUE TITLE
non-aspect resize?

### ISSUE THREAD

**Issue by bkw** [lovell/sharp#153]
After months of using this library I finally noticed that sharp behaves exactly like documented ;-)

Joking aside, I somehow managed to completely overlook the cropping behavior of resize() when used with two non-null parameters. Given the auto-logic when omitting one, and also having max() I somehow assumed that specifying both parameters would scale to the given size, ignoring the original aspect ratio, and essentially stretch and squeeze the image to fit.

I understand that this is a very uncommon and usually completely unwanted usecase for the general public. Unfortunately I do need it for my application, and I really don't want to switch to something else.

Am I overlooking something how this could be achieved already, or am I asking for a new feature that probably no one would use, except for me?

**Comment by lovell** [comment]
Hi Bernhard, does #118 sound similar enough to what you need? Feel free to add comment there if so.

**Comment by bkw** [comment]
I swear I looked through the issues before. Time to go to bed, sorry to bother.
