### ISSUE TITLE
glib error on resize

### ISSUE THREAD

**Issue by asgharmusani** [lovell/sharp#1535]
I am running node v10.5.0 on a shared hosting.

Calling the resize api produces this error.

```
Error: glib: Error creating thread: Resource temporarily unavailable

Emitted 'error' event at:
    at /home/ambthecu/thecustomshop/node_modules/sharp/lib/output.js:614:20

```

**Comment by lovell** [comment]
Hello, the "shared hosting" service has probably been configured to limit the number of threads you're able to spawn. This is a question for the provider - good luck!

**Comment by asgharmusani** [comment]
setting the sharp with concurrency(1) resolved this error.
