### ISSUE TITLE
YCbCr color space

### ISSUE THREAD

**Issue by cekvenich** [lovell/sharp#1536]
Can I use YCbCr color space? to reduce image size?

**Comment by lovell** [comment]
Hello, non-linear sRGB is currently used internally. There's an future possible enhancement to optionally use scRGB at #1317 - this is linear and provides a wider gamut.

Are you able to provide more information about the problem you're trying to solve? Why might the use of YCbCr help?

**Comment by cekvenich** [comment]
The use case is that using YCbCr you get 60% compression. 
eg: google compression shows 60% with their 'large' image example https://squoosh.app

So I want to see if using your tool I get same savings.

**Comment by lovell** [comment]
By default libjpeg(-turbo) already does the conversion to YCbCr for you. Neither sharp nor libvips change this default.

(Use of a RGB colour space in the encoded data of a JPEG image is very rare. It's odd to see this option made available in a tool aiming for smaller file sizes.)

**Comment by cekvenich** [comment]
OK, so I do nothing and I get YCbCr, correct?

**Comment by lovell** [comment]
Yes.

**Comment by cekvenich** [comment]
Great. THANK YOU! I'm using your lib for https://github.com/metabake.

Separate question: options.optimiseScans Boolean optimise progressive scans

I can't find what does that do or mean. Can you expand a bit or help please?

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/en/stable/api-output/#jpeg

> `options.optimiseScans` **Boolean** optimise progressive scans, forces progressive, requires mozjpeg (optional, default `false`)

`optimiseScans` is a feature of mozjpeg - you'll need to compile libvips from source with support for mozjpeg to use this.
