### ISSUE TITLE
can't install sharp

### ISSUE THREAD

**Issue by alexjidras** [lovell/sharp#1539]
$ npm i sharp

> sharp@0.21.1 install C:\Users\Alex\Work\server_test\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached C:\Users\Alex\AppData\Roaming\npm-cache\_libvips\libvips-8.7.0-win32-x64.tar.gz
info sharp Creating C:\Users\Alex\Work\server_test\node_modules\sharp\build\Release
info sharp Copying DLLs from C:\Users\Alex\Work\server_test\node_modules\sharp\vendor\lib to C:\Users\Alex\Work\server_test\node_modules\sharp\build\Release
prebuild-install WARN install No prebuilt binaries found (target=11.6.0 runtime=node arch=x64 platform=win32)

C:\Users\Alex\Work\server_test\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Users\Alex\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Alex\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
▒▒▒▒஥▒▒▒ ▒஥▒⮢ ▒ ▒⮬ ▒襭▒▒ ▒▒ ▒▒▒▒▒▒. ▒⮡▒ ▒▒▒▒▒▒▒ ▒▒ࠫ▒▒▒쭮▒ ▒▒▒▒஥▒▒▒, ▒▒▒▒▒▒▒ ▒▒ࠬ▒▒▒ "/m".
MSBUILD : error MSB3428: ▒▒▒▒㧪▒ ▒▒▒▒▒▒▒▒▒ Visual C++ "VCBuild.exe" ▒▒▒▒▒▒▒▒▒▒. ▒▒▒ᮡ▒ ▒襭▒▒ ▒஡▒▒▒▒: 1) ▒▒⠭▒▒▒▒ .NET Framework 2.0 SDK, 2) ▒▒⠭▒▒▒▒ Microsoft Visual Studio 2005 ▒▒▒ 3) 㪠▒▒▒▒▒ ▒▒▒▒ ▒▒▒▒▒▒▒▒▒ ▒ ▒▒⥬▒▒▒ ▒▒▒, ▒᫨ ▒▒▒▒▒▒▒▒▒ ▒▒⠭▒▒▒▒▒ ▒ ▒▒㣮▒ ▒▒▒▒.  [C:\Users\Alex\Work\server_test\node_modules\sharp\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Alex\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Alex\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Alex\Work\server_test\node_modules\sharp
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN marked-terminal@1.7.0 requires a peer of marked@^0.3.3 but none is installed. You must install peer dependencies yourself.
npm WARN myapp@1.0.0 No description
npm WARN myapp@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.21.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.21.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Alex\AppData\Roaming\npm-cache\_logs\2019-01-08T11_24_22_216Z-debug.log

[2019-01-08T11_24_22_216Z-debug.log](https://github.com/lovell/sharp/files/2736531/2019-01-08T11_24_22_216Z-debug.log)

**Comment by lovell** [comment]
Hello, if you're able to use Node 10 then you'll get pre-compiled binaries.

http://sharp.pixelplumbing.com/en/stable/install/

**Comment by blacksmoke26** [comment]
Same issue:

```G:\WebData\wwwroot\projects\foundation (exp -> origin)
λ npm install sharp -S

> sharp@0.21.1 install G:\WebData\wwwroot\projects\foundation\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached D:\WINDOWS\Roaming\npm-cache\_libvips\libvips-8.7.0-win32-x64.tar.gz
info sharp Creating G:\WebData\wwwroot\projects\foundation\node_modules\sharp\build\Release
info sharp Copying DLLs from G:\WebData\wwwroot\projects\foundation\node_modules\sharp\vendor\lib to G:\WebData\wwwroot\projects\foundation\node_modules\sharp\build\Release
prebuild-install WARN install No prebuilt binaries found (target=11.4.0 runtime=node arch=x64 platform=win32)

G:\WebData\wwwroot\projects\foundation\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Me\AppData\Local\Programs\Python\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd G:\WebData\wwwroot\projects\foundation\node_modules\sharp
gyp ERR! node -v v11.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.21.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.21.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\WINDOWS\Roaming\npm-cache\_logs\2019-01-08T16_08_03_743Z-debug.log```

**Comment by lovell** [comment]
If you wish to compile from source, please see the dependencies listed at http://sharp.pixelplumbing.com/en/stable/install/#building-from-source e.g. Python 2.7.

**Comment by rdunkle-nj** [comment]
I was getting similar errors. I had been using Node v12. I downgraded to the LTS Node v10 and that fixed the issue.
