### ISSUE TITLE
Support of custom scan file for jpeg compression

### ISSUE THREAD

**Issue by abarre** [lovell/sharp#1541]
I see that sharp supports progressive jpeg but I cannot find a way to specify a custom scan file. My goal is to be able to use a custom scan file as it is possible to do with `cjpeg -scan` [ref](https://github.com/mozilla/mozjpeg/blob/master/wizard.txt#L114): 
```
-scans FILE    Create multi-scan JPEG per script FILE
```
As far as I can tell the progressive option use this [scan file](https://github.com/cloudflare/jpegtran/blob/master/wizard.txt#L184)

However, I am aware of the article from Cloudinary [Progressive JPEGs and green Martians](https://cloudinary.com/blog/progressive_jpegs_and_green_martians) that demonstrates the usage of scan file to generate semi-progressive and steep-progressive jpeg.

semi-progressive scan file : 
```
0 1 2: 0 0 0 0;
0: 1 9 0 0;
2: 1 63 0 0 ;
1: 1 63 0 0 ;
0: 10 63 0 0;
```

steep-progressive scan file : 
```
0 1 2: 0 0 0 2;
0 1 2: 0 0 2 1;
0 1 2: 0 0 1 0;
1: 1 63 0 0 ;
2: 1 63 0 0 ;
0: 1 63 0 0;
```

There is also this [slide](https://speakerdeck.com/tbaldauf/your-hero-images-need-you-save-the-day-with-http2-image-loading?slide=31) from _Your Hero Images Need You! Save the Day with HTTP2 Image Loading_ that show another possible scan file.

**Comment by lovell** [comment]
Bonsoir, if you're this deeply into JPEG file size then, if you haven't already tried it, I'd suggest compiling libvips from source with support for mozjpeg and use the `optimiseScans` option.

https://sharp.pixelplumbing.com/en/stable/api-output/#jpeg

**Comment by abarre** [comment]
Thank you for your quick reply. I will try this option. I am not sure of the real effect on the scans number. The [code in mozjpeg](https://github.com/mozilla/mozjpeg/blob/cfb713852354b139ca25a8c382de4166a67d41a1/jcmaster.c#L333) is a bit opaque.

**Comment by lovell** [comment]
Hope this helped, please re-open with more details if not.

**Comment by praveenax** [comment]
Seems to be there is no way we can pass a scan file.
