### ISSUE TITLE
More specific error message rather than, "Input file is missing or of an unsupported image format"

### ISSUE THREAD

**Issue by mevinbabuc** [lovell/sharp#1542]
https://github.com/lovell/sharp/blob/9dd6510de6340c15e9bcd18a69af5a4115baffb1/src/common.cc#L294

Can we put a more specific error message here, so that these can be better handled programmatically.  If the file path is wrong, i expect it to report, that the file is missing and not an ambiguous one. And if it's of an unsupported format, maybe just say, this format is not supported.

**Comment by lovell** [comment]
Thanks for the suggestion - this generic error has been split into missing vs invalid - available in v0.21.3.
