### ISSUE TITLE
how to composite  many images buffer?

### ISSUE THREAD

**Issue by chengdonglin** [lovell/sharp#1548]
const base = sharp({
    create: baseOpt,
}).jpeg()
let imgs = []
for(let i=1;i<=4;i++){
    const result = fs.readFileSync(`./${i}.jpeg`)
    imgs.push(result)
}
base.overlayWith(imgs[0],{left:0,top:0}).overlayWith(imgs[1],{left:256,top:0})
.toBuffer().then(data=>{
    fs.writeFileSync('./111.jpeg',data)
})

when I composite by this methods, but the imgs[0] and imgs[1] can not composite to base? how to resolve?

**Comment by lovell** [comment]
Hello, did you see #728? There are examples of how to do this in the linked issues.

**Comment by chengdonglin** [comment]
Thank very much, I have seed the #728, but when I composite 64 images by this methods, It takes 4s to complete the stitching. it is too slow, how to resolve ?

**Comment by lovell** [comment]
You'll need to wait for #728.
