### ISSUE TITLE
Support background color with an alpha component.

### ISSUE THREAD

**Issue by jaubourg** [lovell/sharp#1553]
Maybe I'm missing something but every time I try to set a `background` color to something with an alpha component that is not `1` (for instance setting `{ background: "rgb(255,0,0,0.5)"}` as options to a `resize`), sharp defaults to solid black.

FYI, the source image is a png with an alpha channel.

AFAIK, the only other operations available to add a background are `extend` and `flatten` but the former only adds background to the padding and the latter, well, flattens the image and thus obviously does not support alpha.

Would it be possible for operations that have a `background` option to support non-solid colors ? Or am I definitely missing something ?

**Comment by lovell** [comment]
The following works for me:
```javascript
sharp("test/fixtures/alpha-layer-1-fill.png")
  .resize({
    fit: "contain",
    background: "rgb(255, 0, 0, 0.5)",
    width: 200,
    height: 200
  })
  .toFile("output.png")
```
![](https://user-images.githubusercontent.com/210965/51431819-498fb300-1c26-11e9-8959-f0c8292d0b11.png)

 Are you sure the output format supports an alpha channel?

**Comment by lovell** [comment]
What you're describing requires alpha compositing. The "underlayWith" concept will become possible with the `dest-over` blend mode introduced by #728.

**Comment by lovell** [comment]
`dest-over` will be in v0.22.0 - please see #728 for more details.
