### ISSUE TITLE
How to add a border over an image?

### ISSUE THREAD

**Issue by campolinabh** [lovell/sharp#1555]
Hi there,

I'd need to add a 1 pixel border (in a pre-defined color) over some images. 

Does anyone have any clue of how I could do that?

Thanks in advance!!

Daniel

**Comment by campolinabh** [comment]
Just a small update. My goal is not to enlarge the image with a border but add a border keeping it's original dimensions. Thanks.

**Comment by campolinabh** [comment]
Hello @lovell would you have any clue on this? Thanks in advance!

**Comment by lovell** [comment]
Hello, using [extract](https://sharp.pixelplumbing.com/en/stable/api-resize/#extract) to remove 1px from around the edge then [extend](https://sharp.pixelplumbing.com/en/stable/api-resize/#extend) to add 1px around the edge should do what you need.

**Comment by campolinabh** [comment]
Hi @lovell, first of all thanks for your feedback. 

So I tried the extract/extend suggestion but a new issue came up. The extended area is always black, regardless of the background color passed as parameter in the "extend". 

The code bellow is trying to add a white background but no matter which hexa or rgb color I add, the background of the extended area will always be black. 

```
image.metadata().then(meta => {
   
    image
    .extract({
      left: 1, 
      top: 1, 
      width: meta.width - 2,   
      height: meta.height - 2    
    })
    .extend({
      top: 5,
      bottom: 5,
      left: 5,
      right: 5,
      background: "#FFFFFF"
    }) 
    .toBuffer()
    .then(data => sharp(data)
      .toFile('out.jpg')
    );

});

```

Output image from the code above: [](https://imgur.com/a/MFA5BQb)

As a workaround I tried the add a ".background" after the ".extend". The extended area gets the color defined in the separated ".background" but the color is not 100% solid and it has some "dirty".

```
image.metadata().then(meta => {
    console.log(meta.width, meta.height);
   
  image
    .extract({
      left: 1, 
      top: 1, 
      width: meta.width - 2,   
      height: meta.height - 2    
    })
    .extend({
      top: 5,
      bottom: 5,
      left: 5,
      right: 5
    })
    .background('#D1D1D1')
    .embed()
    .toBuffer()
    .then(data => sharp(data)
      .toFile('out.jpg')
    );


});
```

Output image with dirty background: [](https://imgur.com/a/89hEarO) 

Any idea of what I am doing wrong or maybe it's a bug? 

Thanks!!

**Comment by campolinabh** [comment]
I just realized that the last Sharp version(0.23.1) has a fix and not the code works. Thanks.

**Comment by lovell** [comment]
The API you're using requires v0.21.x - glad you got it working - I think the "dirty background" is caused by JPEG compression artefacts.
