### ISSUE TITLE
Green border on letters when rendering svg with transparency.

### ISSUE THREAD

**Issue by JoelIF** [lovell/sharp#1556]
When running this code:

```
const sharp = require('sharp'),
	  fs = require('fs'),
          text = 'Fancy Text',
	  textH = 40,
	  textBgH = textH * 1.4
	  buffer = `
	<svg>
		<rect x="0" y="0" height="${textBgH}px" fill="none" width="100%"/>
		<text font-family="sans-serif" font-size="${textH}px" font-weight="bolder" x="0" y="${textH}" fill="white" >${text}</text>
	</svg>`;

sharp(Buffer.from(buffer))
    .png()
	.toFile('text.png');
```
the text is getting a green border:

![image](https://user-images.githubusercontent.com/29204598/51652244-1cb90400-1f76-11e9-9f0d-959519e85b7e.png)

Is it a bug or am I doing something wrong?

Thanks for the lib.

**Comment by lovell** [comment]
Hello, does this occur on Windows only? Did you see #1275?

**Comment by JoelIF** [comment]
I am using:

Win 10 v1803
Node v10.15.0
Sharp v0.21.3 pre-build

I can only test it on Windows. But it must be the same issue that [#1275](https://github.com/lovell/sharp/issues/1275) presented.

I'll search for a workaround, if I find out, I'll bring it here.

Thanks for the answer.

**Comment by JoelIF** [comment]
After some test with this code:

```
const sharp = require('sharp'),
	  fs = require('fs'),
      text = 'Fancy Text',
	  textH = 40,
	  textBgH = textH * 1.4
	  buffer = Buffer.from(`
		<svg>
			<rect x="0" y="0" height="${textBgH}px" width="100%" opacity=".4"/>
			<text style="
				font-family: sans-serif; 
				fill: none;
				stroke: white;
				stroke-width: 2px;
				font-size: ${textH}px;
			" x="0" y="${textH}">${text}</text>
		</svg>`);

sharp(buffer) 
    .png()
	.toFile('text.png');
```
I got

![image](https://user-images.githubusercontent.com/29204598/51722726-85b77f00-203d-11e9-9864-287490d3e0af.png)

So, I guess the problem is when trying to fill a font with a color.
