### ISSUE TITLE
sharp is cropping rather than resizing on png input

### ISSUE THREAD

**Issue by mreinstein** [lovell/sharp#1557]
my sample input is a `test.png`, a 580x320 unoptimized image

```bash
sharp-cli -i test.png -o out.png resize 500
```

I expected `out.png` to be 500x276 (this would be the behavior if I ran the above command with a .jpg for input) . but instead it produces a 500x500 image

Is this a bug or am I invoking the API incorrectly? using sharp-cli (which uses sharp version 0.21.1)

**Comment by mreinstein** [comment]
<img width="284" alt="test" src="https://user-images.githubusercontent.com/718067/51780200-6feb9d80-20c1-11e9-87da-927594f6cc9a.png">

Here's the file I've been testing with.

**Comment by lovell** [comment]
Hello, this is a question for the independently-maintained https://github.com/vseventer/sharp-cli

**Comment by mreinstein** [comment]
sorry, didn't mean to pollute this repo with irrelevant issues. That said, `sharp-cli` is directing people here, as evidenced from their readme.md:

<img width="702" alt="screen shot 2019-01-26 at 8 11 09 am" src="https://user-images.githubusercontent.com/718067/51789825-06f83a00-2142-11e9-9557-f34cf084ef1f.png">

might be worth pinging them and working that out
