### ISSUE TITLE
Resize jpeg/webp without changing quality

### ISSUE THREAD

**Issue by midevnull** [lovell/sharp#1561]
First, thanks for developing this great library Lovell. 
I was wondring if there is an option to resize an image without changing the quality. 
`sharp(buffer).resize(width).toBuffer()`
Adding the jpeg function increases the filesize:
`.jpeg({
    quality: 100
  })`
`.metadata() ` doesnt show the initial quality. Not sure if that is even possible. I just saw that pain.net recognizes the quality.

**Comment by lovell** [comment]
Hello, did you see #908?

**Comment by midevnull** [comment]
@lovell Thanks you very much. Found a solution in the linked issue.
