### ISSUE TITLE
the file built with BlobBuilder is not working

### ISSUE THREAD

**Issue by 79229788** [lovell/sharp#1562]
At the front end, file built with 'new Blob()', get buffer after uploading
`const sharpBuffer = await sharp(buffer).resize()......toBuffer();` 
This code works fine

but....built with BlobBuilder(I tested in android 4.3)，isn't working, found error: Input buffer contains unsupported image format

The front end uses the following method to convert, and upload the file using Ajax
```
  base64ToBlob: function (base64, contentType, cb) {
    const bytes = window.atob(base64);
    const buffer = new ArrayBuffer(bytes.length);
    const bufferArray = new Uint8Array(buffer);
    for (let i = 0; i < bytes.length; i++) {
      bufferArray[i] = bytes.charCodeAt(i);
    }
    let blob;
    try {
      blob = new Blob([buffer], {type: contentType});
    } catch (e) {
      window.BlobBuilder = window.BlobBuilder
        || window.WebKitBlobBuilder
        || window.MozBlobBuilder
        || window.MSBlobBuilder;
      if(e.name === 'TypeError' && window.BlobBuilder){
        const blobBuilder = new BlobBuilder();
        blobBuilder.append(buffer);
        blob = blobBuilder.getBlob(contentType);
      }
    }
    cb(blob);
  },
```

**Comment by lovell** [comment]
Hello, this question doesn't really relate to sharp and according to https://developer.mozilla.org/en-US/docs/Web/API/BlobBuilder the use of BlobBuilder is considered obsolete. Perhaps try StackOverflow to see if there's anyone else still using it - good luck!
