### ISSUE TITLE
Hi developer, imput file don't close

### ISSUE THREAD

**Issue by utherbone** [lovell/sharp#1563]
Module declaration:
`const sharp = require('sharp');`

The code I am using:
`sharp('out.jpg').overlayWith('x.png', { gravity: sharp.gravity.south } ).toFormat('png').toFile('output.png', function(err, info){});`

I do not understand why, when node.js finished merging / converting using "sharp" it does not close the input file, this is causing me a headache, I already see documentation but I do not say anything about closing the file.

The documentation that I have helped with and with honorable
StackOverflow:
https://sharp.pixelplumbing.com/en/stable/api-input/

**Comment by lovell** [comment]
Hello, please see #415

**Comment by utherbone** [comment]
Thanks @lovell This fixed my problem, I thank the compression I did not think that that insue would have anything to do with my problem, I think it is more because I do not speak English and it is certain that this may have harmed, but without delay you have done a great job, "Sharp" does amazing things
