### ISSUE TITLE
SVG font loading, Linux

### ISSUE THREAD

**Issue by warfrogsdf** [lovell/sharp#1565]

**Comment by lovell** [comment]
Hello, the numeric `FC_DEBUG` environment variable can be used to help debug font loading problems. Try a value of 1 to start with.

https://www.freedesktop.org/software/fontconfig/fontconfig-user.html#DEBUG

**Comment by warfrogsdf** [comment]
i solve this problem by import font to os font lib。but this method s Maintainability is so poor，i hope sharp have api to load font from project one sub directory txs。

**Comment by zvictor** [comment]
I am setting `FC_DEBUG=1 node myscript.js` but I don't see any new logging. Just to be sure, I also tried setting `export FC_DEBUG=8191` in the cli and `process.env.FC_DEBUG = '1'` inside my script, but none of these are giving me any debugging info. I am feeling stupid right now... Is there any other way to set `FC_DEBUG`?
