### ISSUE TITLE
error trying to require sharp on EC2

### ISSUE THREAD

**Issue by bedrocktv** [lovell/sharp#157]
Hi

I'm getting an error when trying to include sharp. I'm running on EC2 and have updated to the latest AMI.

Here are the steps I've taken (all from my ec2-user path).  

1> $ sudo curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | sudo bash -

2> $ npm install sharp
-
> sharp@0.9.0 install /home/ec2-user/node_modules/sharp
> node-gyp rebuild

make: Entering directory `/home/ec2-user/node_modules/sharp/build'
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/resize.o
  CXX(target) Release/obj.target/sharp/src/sharp.o
  SOLINK_MODULE(target) Release/obj.target/sharp.node
  SOLINK_MODULE(target) Release/obj.target/sharp.node: Finished
  COPY Release/sharp.node
make: Leaving directory `/home/ec2-user/node_modules/sharp/build'
sharp@0.9.0 node_modules/sharp
├── nan@1.6.1
├── semver@4.2.0
├── bluebird@2.9.3
└── color@0.7.3 (color-convert@0.5.2, color-string@0.2.4)

3> $ node server.js
<<< START >>>
http = [object Object]
https = [object Object]

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: libvips.so.37: cannot open shared object file: No such file or directory
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ec2-user/node_modules/sharp/index.js:11:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ec2-user/server.js:9:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

Here is my server.js located in ec2-user
console.log ( "<<< START >>>" );

var http = require('http');
console.log ( "http = " + http );

var https = require('https');
console.log ( "https = " + https );

var sharp = require('sharp');
console.log ( "sharp = " + sharp );

I'm new to EC2 and Node so no doubt I'm just missing something fairly simple. Any suggestions?

**Comment by lovell** [comment]
Please can you provide the console output from running the `preinstall.sh` script (step 1).

**Comment by bedrocktv** [comment]
The output file is 578k and I can't seem to drop it in here.  I can share it on my google drive\dropbox if that helps?

**Comment by lovell** [comment]
Yes please, or you could use a [gist](https://gist.github.com/).

**Comment by bedrocktv** [comment]
Ah, thanks.  Gist here

https://gist.github.com/bedrocktv/024abee2813b64c4825f

**Comment by lovell** [comment]
The first line `Found libvips 7.39.0 but require 7.40.0` suggests you've already tried to compile and install libvips via git clone, so there may be two conflicting versions of libvips.

I think you're compiling against one of them at install time but linking against the other at run time.

Run a command like `sudo find / -name libvips.so.*` to confirm which versions are installed.

**Comment by bedrocktv** [comment]
Yeah, I tried to install it a while back.  Here's the output

/home/ec2-user/vips-build/libvips/.libs/libvips.so.37
/home/ec2-user/vips-build/libvips/.libs/libvips.so.37.0.5
/usr/local/lib/libvips.so.37
/usr/local/lib/libvips.so.37.0.5
/usr/lib/libvips.so.40
/usr/lib/libvips.so.38
/usr/lib/libvips.so.38.1.0
/usr/lib/libvips.so.40.0.0

**Comment by lovell** [comment]
Please can you try with a fresh EC2 instance.

**Comment by bedrocktv** [comment]
Not to take advantage of your assistance but is there an alternative approach I can take to just clean my existing instance?

**Comment by lovell** [comment]
Sorry, I'm unable to solve individual environment problems here. Feel free to [e-mail](https://github.com/lovell/sharp/blob/master/package.json#L4) directly if you require paid-for consulting.

My recommendation would be to treat your EC2 instances as disposable. A couple of good articles about the concept of "immutable" infrastructure are:

* http://martinfowler.com/bliki/ImmutableServer.html
* http://chadfowler.com/blog/2013/06/23/immutable-deployments/

**Comment by bedrocktv** [comment]
Ok, fair comment and thanks for the links.

I'll try another instance.

**Comment by bedrocktv** [comment]
Hi

The fault was indeed with my previous environment.  My initial test works fine on a new instance.

Thanks for the pointer and great work.
