### ISSUE TITLE
Unable to sharp in Electron App: Uncaught Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by mubaidr** [lovell/sharp#1577]
```bash
Uncaught Error: Could not locate the bindings file. Tried:
 → D:\Current\image-parsing\build\sharp.node
 → D:\Current\image-parsing\build\Debug\sharp.node
 → D:\Current\image-parsing\build\Release\sharp.node
 → D:\Current\image-parsing\out\Debug\sharp.node
 → D:\Current\image-parsing\Debug\sharp.node
 → D:\Current\image-parsing\out\Release\sharp.node
 → D:\Current\image-parsing\Release\sharp.node
 → D:\Current\image-parsing\build\default\sharp.node
 → D:\Current\image-parsing\compiled\10.11.0\win32\x64\sharp.node
 → D:\Current\image-parsing\addon-build\release\install-root\sharp.node
 → D:\Current\image-parsing\addon-build\debug\install-root\sharp.node
 → D:\Current\image-parsing\addon-build\default\install-root\sharp.node
 → D:\Current\image-parsing\lib\binding\node-v69-win32-x64\sharp.node
    at bindings (bindings.js:124)
    at Object.<anonymous> (constructor.js:10)
    at Object../node_modules/sharp/lib/constructor.js (constructor.js:245)
    at __webpack_require__ (bootstrap:723)
    at fn (bootstrap:100)
    at Object../node_modules/sharp/lib/index.js (index.js:3)
    at __webpack_require__ (bootstrap:723)
    at fn (bootstrap:100)
    at Object.<anonymous> (index.js:10)
    at Object../src/utilities/index.js (renderer.js:140434)
```
![annotation 2019-02-14 150422](https://user-images.githubusercontent.com/2222702/52779518-2ece1580-2ffd-11e9-8ec4-2a7f8f787fad.jpg)

Can you please guide me what could be wrong? I have manually checked there is no `bindings` file in `sharp` js dir inside node_modules. (though `sharp.node`) is present. 

My project repo: https://github.com/mubaidr/image-parsing/
`Package.json`: https://github.com/mubaidr/image-parsing/blob/master/package.json
`Webpack` config: https://github.com/mubaidr/image-parsing/blob/master/_scripts/webpack.renderer.config.js

**Comment by mubaidr** [comment]
I see `bindings` is not looking for `sharp.node` in the right location.

**Comment by lovell** [comment]
If you're using webpack then include sharp in its [externals](https://webpack.js.org/configuration/externals/) config.

**Comment by mubaidr** [comment]
Did that, but the sharp module itself fails to load. I will again try it.

**Comment by mubaidr** [comment]
I am going to close this as this does not seems to be issue with `Sharp` but the webpack config itself.
