### ISSUE TITLE
VipsJpeg: Invalid SOS parameters for sequential JPEG

### ISSUE THREAD

**Issue by asilvas** [lovell/sharp#1578]
Repro example: https://gist.github.com/asilvas/773b902b2d175d452c6472a4ed128762

This is an issue that recently came up that seems related to a recent change. At first I brushed it off as a corrupt image, but quite a few of these cases have come up since. Every other image editor I try the image in works fine. Presumably this is a Jpeg decoder bug, but wanted to post it here since it may require an update to sharp builds.

**Comment by asilvas** [comment]
Looks like this might have been when it was introduced: https://github.com/lovell/sharp-libvips/commit/fad8f99e709b56b53fa78aeab7ecd2934d29008c#diff-9bb9cf79fcf14a477f1dd3bdc15d0917L26

And judging from changelog: https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/ChangeLog.md#202
Your latest build may resolve: https://github.com/lovell/sharp-libvips/commit/d020125bbad373b0bfd296bfa18d60c24fc7ddf4#diff-9bb9cf79fcf14a477f1dd3bdc15d0917L26

**Comment by lovell** [comment]
I've sent you an e-mail about this.

**Comment by bjornbos** [comment]
For anyone struggling with this issue like we did, you can suppress this error by setting the failOnError option in the sharp constructor to false.

**Comment by sachinB94** [comment]
@lovell Hey, when can we expect v0.22.0 ?

**Comment by lovell** [comment]
@sachinB94 Probably before Samsung, who make ~$60bn/year in profit, fix their buggy firmware.

**Comment by lovell** [comment]
sharp v0.22.0 with libvips v8.7.4 now available.

You'll need to explicitly set `failOnError: false` to read these buggy Samsung images. You must use libvips v8.7.4+ to safely set this option.

**Comment by axelpale** [comment]
Anyone looking for how to set `failOnError: false` (like I had to do), just give the options object as a second argument. The [constructor docs](http://sharp.pixelplumbing.com/en/stable/api-constructor/) are bit vague about how to give options when `input` is already given.

    sharp(filepath, { failOnError: false })
        .rotate()
        .resize(...)
        etc

Had this error with HDR and panorama images produced with Samsung Galaxy A3. Normal images worked fine.

**Comment by ccorcos** [comment]
How do I install libvips v8.7.4+?

**Comment by axelpale** [comment]
@ccorcos `npm install sharp` should do it for you, unless your system already has libvips (which can lead to problems)

**Comment by timothyallan** [comment]
I have this exact `Invalid SOS parameters for sequential JPEG` error, and `failOnError:false` is still not allowing me to read Samsung Gear 360 images with v0.22.1

I then get `Error: Unexpected data on Writable Stream (/server/node_modules/sharp/lib/input.js:129:14)`


Is there something else I could try, or is this more likely caused by Samsung throwing in yet more invalid jpeg info?

**Comment by lovell** [comment]
@timothyallan Please can you open a new issue with sample code and image that is failing.

**Comment by timothyallan** [comment]
@lovell yep will do. Just trying to get a repo case going now. Seems to work if read directly from a file, but piping from a stream fails.

**Comment by kennethmervin01** [comment]
> failOnError: false })

How to set failOnError in stream?

**Comment by kennethmervin01** [comment]
const file = fs.createWriteStream(path);
        const thumbnail = fs.createWriteStream(thumb);
        const createThumbnail = sharp()
          .rotate()
          .resize(200, 200);
        fields.myimage.pipe(file);
        fields.myimage.pipe(createThumbnail).pipe(thumbnail);

**Comment by lovell** [comment]
@kennethmervin01 Please see #1691
