### ISSUE TITLE
gm scale method equivalent in sharp

### ISSUE THREAD

**Issue by felipe-pereira** [lovell/sharp#158]
Hi, I'm sorry to ask about this since I feel that the answer is really simple, but I can't figure it out.

Due to performance, I'm migrating from gm to sharp, most of the work is done, but there is one particular feature that I havn't been able to write using sharp.

```
//original code using gm
gm(buffer)
.scale(w1, h1)
.crop(w, h, xoffset, yoffset)
.setFormat('jpg')
.toBuffer(...
```

The output of that: [original](http://i.imgur.com/kKqOLTG.jpg) is now [transformed](http://i.imgur.com/YMr4Lnj.jpg)

I tried  with some combinations of ```resize``` and ```max``` without success, so now I'm asking if there is a way of using gm ```scale``` in sharp.

thanks

**Comment by lovell** [comment]
Would #118 provide the feature you're looking for?

**Comment by felipe-pereira** [comment]
Hi, and thanks for the quick response, I managed to make it work as desired combining some methods on sharp:

```javascript
sharp(buffer)
.resize(Math.floor(w1), Math.floor(h1))
.extract(Math.floor(yoffset), Math.floor(xoffset), Math.floor(w), Math.floor(h))
.jpeg()
.toBuffer(...
```

Now, I'm not sure if this is the same thing required in that issue, since image processing isn't my strong point I'll have to let you judge that (now that you see the code I ended up using I think it will be easy for you to tell).

Last question (I hope): ```extract``` also requires integer Number?

**Comment by lovell** [comment]
Ah ha, I understand your question more clearly now, the code you've written looks good to me.

As you suggest, the `extract` method requires integers. Does `gm` accept floating point values? If so, I guess it'll implicitly `round`, `floor` or `ceil` them.

Having just looked at the `extract` method in the code it's not validating values as tightly as it could - that could definitely be improved, thanks for the tip!

**Comment by felipe-pereira** [comment]
Yes, gm accepts floating point values (no clue about what it does with these values then). 

In sharp I passed float values to ```extract``` and it worked fine (at least with offsets), but since ```resize``` does not accept floats I ```Math.floor``` them too to use in ```extract```

I'll leave ```Math.floor``` in my calls to ```extract``` then, thanks for your work.

**Comment by lovell** [comment]
Glad to hear you got it working. Improved validation of `extract` parameters added, thanks again.
