### ISSUE TITLE
Sharp doesn't work for me.

### ISSUE THREAD

**Issue by syntacticsolutions** [lovell/sharp#1581]
I'm trying to resize an image and it just isn't working for me. Also, I'm getting no error message in my responses.

This function is supposed to receive a base64 string from the frontend and then convert it to a buffer so that it can be passed to Sharp. Nothing comes back. All I get is a rejected promise with no reason for it being rejected.

```javascript
exports.uploadToBlog = (req, res) => {
    
    const image = sharp(Buffer.from(req.body.image, 'base64'))

    image
    .resize(300, 300, {
        fit: 'inside'
    })
    .toBuffer()
    .then(function(data) {
        console.log('beforeUpload')
        let base64Image = data.toString('base64')
        return gStorage.uploadImage('blog', uuid.v4(), base64Image)
    })
    .then(() => res.status(200).send('Image Uploaded'))
    .catch(err => res.status(500).send(err))
}
```

the `console.log` inside of the `.then` never gets called. and all I get is an empty object as my response with status 500.

**Comment by lovell** [comment]
Hello, please can you provide a standalone code sample that exhibits this behaviour without the dependency on the unknown `gStorage.uploadImage`.

**Comment by syntacticsolutions** [comment]
Sure https://github.com/syntacticsolutions/sharp-test

**Comment by syntacticsolutions** [comment]
I think I figured it out. I have to remove the header from the base64 image and then it works.
