### ISSUE TITLE
[Discussion] N-API over Node-ABI

### ISSUE THREAD

**Issue by mubaidr** [lovell/sharp#1583]
Is it possible to update this module to N-API module, seems like a good solution to pre-build problems, 
More info: https://nodejs.org/docs/latest/api/n-api.html and https://github.com/nodejs/abi-stable-node
a simple example: https://riptutorial.com/node-js/example/31631/hello-to-n-api

PS. I am fascinated by the performance of this module but at the same time, after updating electron package and nodejs upgrade I have never been able to run my project again due to build issues with this native dependency. Setting up build tools require too much effort but still every now and then something messes it up.

**Comment by lovell** [comment]
Hello, please see #1282 for N-API support and #1522 for details of why the latest Electron 4 doesn't work with native modules (including but not limited to sharp).

**Comment by mubaidr** [comment]
Ahh missed it. Sorru
