### ISSUE TITLE
Resize -> extract -> rotate leads to no rotate

### ISSUE THREAD

**Issue by deftomat** [lovell/sharp#1584]
We have the following code:
```js
sharp()
  .resize(600, 600)
  .extract({ width: 200, height: 50, left: 0, top: 0 })
  .rotate(90);
```

Result should be 50x200 however, it is 200x50 (rotate not applied).

When we do `resize` in a different instance, then the result is 50x200 as expected:
```js
const instance1 = sharp().resize(600, 600);
  
const instance2 = sharp()
  .extract({ width: 200, height: 50, left: 0, top: 0 })
  .rotate(90);

instance1.pipe(instance2);
```

Is this an expected behaviour? If yes, what's the reason for this?

Sharp version: 0.21.3

**Comment by lovell** [comment]
Hello, the ordering of applying both a rotate and extract operation post-resize is currently fixed so the two-pipeline approach you suggest is correct. Please see #241 for discussion about a future possible additional API.

**Comment by deftomat** [comment]
Oh, thats sad. We need to construct pipelines dynamically and using a lot of new instances hit the CPU really badly. In our code it is like 30ms vs 150ms or worse 😢

**Comment by lovell** [comment]
I suspect much of that time will be spent in the (de)compression round trips. If you've not already done so, it'd be worth experimenting with raw, uncompressed data for the intermediate stages.

```javascript
const instance1 = sharp().resize(600, 600).raw();
  
const instance2 = sharp({ raw: { width: 600, height: 600, channels: 3 }})
  .extract({ width: 200, height: 50, left: 0, top: 0 })
  .rotate(90);

instance1.pipe(instance2);
```

**Comment by deftomat** [comment]
Awesome! Thanks, It helps a lot.
