### ISSUE TITLE
Conver http response images with .webp to .jpg

### ISSUE THREAD

**Issue by taraa62** [lovell/sharp#1585]
Hi, I need help setting up sharp in converting pictures from webp to jpg | png ... when responding from the server.

example -
let response;
  const request = http.get ("/ test / test.webp", resp => {
             response = resp;
         })

// ***********************
// .webp to jpg
  const writeableStream = fs.createWriteStream ('test.jpg');
response.pipe (???). pipe (writeableStream);

I tried many options with the documentation, but nothing came of it.
Is it possible with this library?

**Comment by lovell** [comment]
Hello, you can create a Transform Stream that reads image data from a Readable Stream and writes JPEG data to a Writable Stream using something like:
```javascript
const jpegTransformer = sharp().jpeg();
```
This could then be used as:
```javascript
readableStream.pipe(jpegTransformer).pipe(writeableStream);
```
In your example I think you'll need to move the use of `response` into the `http.get` callback to ensure it is defined.
```javascript
http.get("/test/test.webp", response => {
  const writeableStream = fs.createWriteStream('test.jpg');
  response.pipe(jpegTransformer).pipe(writeableStream);
});
```

**Comment by lovell** [comment]
Hope this helped.

**Comment by taraa62** [comment]
Thanks for the answer, but the decision was not to convert the picture
