### ISSUE TITLE
can't install sharp on MacOS

### ISSUE THREAD

**Issue by chaims** [lovell/sharp#1586]
![image](https://user-images.githubusercontent.com/4903657/53227289-d233c000-36b8-11e9-8fba-9cd2613bf9c3.png)

**Comment by lovell** [comment]
Hello, please can you delete the `/Users/caihao/.npm/_libvips/libvips-8.7.0-darwin-x64.tar.gz` file and try again.

(The `zlib: unexpected end of file` error suggests there might have been a temporary network problem when downloading it originally.)

**Comment by chaims** [comment]
Thanks a lot, But here in lies another problem

<img width="568" alt="2019-02-25 9 23 14" src="https://user-images.githubusercontent.com/4903657/53308875-80b94a00-38df-11e9-9a81-d123f821f43e.png">

**Comment by lovell** [comment]
If you're using Electron then the use of [electron-rebuild](https://github.com/electron/electron-rebuild) is required.

(If possible, please copy and paste error messages as text rather than take screenshots as that makes it so much easier for everyone to read.)

**Comment by lovell** [comment]
Hope this helped, please re-open with more details if not.
