### ISSUE TITLE
.mrxs (MIRAX) slide interpreted as JPEG instead of TIFF

### ISSUE THREAD

**Issue by valeriancure** [lovell/sharp#1589]
Hi,

not sure if it's a bug or not, but I ran into the following issue with .mrxs files :

## Expected Behavior

Load `.mrxs` file (and its subfolder of `.dat` and `.ini` files) as `tiff` with OpenSlide (via libvips)

## Current Behavior

Because .mrxs files contain a JPEG thumbnail (I guess), Sharp returns metadata `format: "jpeg"`, and only loads the thumbnail (wich is of course ridiculously small compared to the expected image)

The subfolder is ignored, removing it doesn't change the behavior.

## Question / suggestion

I'm not familiar with C++ and probably not using the right terminology, but is there  way to force sharp to use the openslide (or tiff ?) loader for .mrxs files ?

## Steps to Reproduce
1. d/l and unzip http://openslide.cs.cmu.edu/download/openslide-testdata/Mirax/CMU-1-Saved-1_16.zip
2. load the .mrxs with sharp and get the metadata
3. format is jpeg and dimensions are small

## Context (Environment)
sharp 0.21.3 on Windows 10

**Comment by lovell** [comment]
Hello, the `CMU-1-Saved-1_16.mrxs` file walks, talks and quacks like a JPEG file.
```sh
$ file CMU-1-Saved-1_16.mrxs
CMU-1-Saved-1_16.mrxs: JPEG image data, JFIF standard 1.02, aspect ratio, density 1x1, segment length 16, comment: "Intel(R) IPP JPEG encoder [6.1.787] - Jun 10 2009", baseline, precision 8, 640x1292, frames 3
```
To use openslide with sharp/libvips you'll need to compile libvips from source with openslide support and globally install it. As an added gotcha sharp on Windows won't be able to use this so you'll also need to do all of this on some kind of virtualisation layer running Linux.

**Comment by valeriancure** [comment]
Thanks for your time.
For quick testing purposes I got it working on Windows 10 unconventionally, by replacing `node_modules/sharp/build/Release/libvips-42.dll` with the equivalent file from [vips-dev-w64-all-8.7.4.zip](https://github.com/libvips/libvips/releases/tag/v8.7.4)

It seems to work great, thanks.
I'm now working on properly building `sharp-libvips`.

Have a good day
