### ISSUE TITLE
Webp error: webp2vips: unable to read pixels

### ISSUE THREAD

**Issue by bpatrik** [lovell/sharp#1592]
Hi,

Thank you for the nice library! 

I have an issue using `sharp v0.21.3` (on win 10).
I try to read and resize a `webp` file and save it as `jpg` (I tried to save it to webp too with the same result).

I'm using this webp file: https://i.giphy.com/media/l4EoMWIMDVG156l6U/giphy.webp
I'm rearing, resizing and saving the file as jpg. ([~40 line source code here](https://github.com/bpatrik/pigallery2/blob/bbf7a44b5cec3bf990e313694f501325f3c603a7/backend/model/threading/ThumbnailWorker.ts#L184))

I get the following error during the process: `Error: webp2vips: unable to read pixels`

There is a related issue at libvpis: https://github.com/libvips/libvips/issues/823 but it seems to be solved. 

Can you give me some hints how to solve it?

Thank you !
Patrik

**Comment by lovell** [comment]
Hello, support for animated WebP in libvips will be available in the forthcoming v8.8.0 - see comment https://github.com/libvips/libvips/issues/823#issuecomment-442060482 in the issue you linked to.

**Comment by bpatrik** [comment]
Oh Ok.
Thank you for your help.

**Comment by pgsill** [comment]
@lovell now that libvips has support for animated WebP, has the status on this changed?
