### ISSUE TITLE
Enhancement: support page input option for PDF

### ISSUE THREAD

**Issue by ramiel** [lovell/sharp#1594]
I compiled libvips with pdf support. It's working well except that the `page` option is not considered.

```js
sharp('/path/file.pdf', {page: 3});
```

This is not loading page 3 from pdf but always the first page :cry: . This feature is supported by libvips. Can this be fixed?

**Comment by lovell** [comment]
Hello, the `page` feature is currently limited to TIFF. Support for PDF (and GIF - see #1566) needs to be added approximately [here](https://github.com/lovell/sharp/blob/master/src/common.cc#L246) and [here](https://github.com/lovell/sharp/blob/master/src/common.cc#L291).

Happy to accept a PR if you're able.

**Comment by ramiel** [comment]
Thank you. I'll try soon

**Comment by jcupitt** [comment]
The soon-to-be-finished libvips 8.8 supports `page` on webp and heif as well, fwiw.

You can also use `page` for magickload, but I guess that's harder to support since it (potentially) will work for any file type.

**Comment by lovell** [comment]
v0.22.0 now available, thanks for the PR @ramiel!
