### ISSUE TITLE
Azure installation error

### ISSUE THREAD

**Issue by revo91** [lovell/sharp#1598]
I'm getting an error:
`'linux-x64' binaries cannot be used on the 'linuxmusl-x64' platform. Please remove the 'node_modules/sharp/vendor' directory and run 'npm install'.`

node_modules is being created and installed in destination. 
How do I use sharp in Azure?

**Comment by lovell** [comment]
Hello, this message means that a musl-based Linux, probably Alpine, is being used at runtime but a glibc-based Linux was used at `npm install` time. Try using a musl-based Linux at `npm install` time or a glibc-based Linux at runtime so they match.

**Comment by lovell** [comment]
Hope this solved your problem, please re-open with more details if further help is required.

**Comment by itip** [comment]
If it's any use, I had the same issue and I found a solution (I'm assuming you're using the [Azure Web Apps](https://azure.microsoft.com/en-gb/services/app-service/web/) like me). For some reason it seems to download the dependencies on one Linux environment but run the app on another. Anyway, I was able to resolve the issue by adding the following "postinstall" script to my package.json file.

```
"scripts": {
    "postinstall" : "npm install --arch=x64 --platform=linuxmusl sharp"
}
```

This should install the _linuxmusl_ version of _libvips_, ready to be used when the app is run. 

It doesn't seem to cause any issue when not in production. However, if you only want to run this on Azure you can use something like [if-env](https://www.npmjs.com/package/if-env).

**Comment by revo91** [comment]
Thanks @itip, will try it.
