### ISSUE TITLE
Enhancement: expose TIFFTAG_PHOTOSHOP metadata

### ISSUE THREAD

**Issue by SanderVanLeeuwen** [lovell/sharp#1600]
For some files (usually tiff's) the extracted metadata doesn't contain any EXIF information, while the file itself does. See for example the attached tif (zipped, because GitHub doesn't support tif uploads).

Is there something wrong with the file itself, am I doing something wrong, or is this a bug?

[test.tif.zip](https://github.com/lovell/sharp/files/2931129/test.tif.zip)

**Comment by lovell** [comment]
Hello, I see the following `metadata` for this image:
```javascript
{ format: 'tiff',
  width: 317,
  height: 211,
  space: 'rgb16',
  channels: 3,
  depth: 'ushort',
  density: 72,
  isProgressive: false,
  pages: 1,
  hasProfile: true,
  hasAlpha: false,
  orientation: 1,
  icc:
   <Buffer 00 00 02 30 41 44 42 45 02 10 00 00 6d 6e 74 72 52 47 42 20 58 59 5a 20 07 cf 00 06 00 03 00 00 00 00 00 00 61 63 73 70 41 50 50 4c 00 00 00 00 6e 6f ... >,
  xmp:
   <Buffer 3c 3f 78 70 61 63 6b 65 74 20 62 65 67 69 6e 3d 22 ef bb bf 22 20 69 64 3d 22 57 35 4d 30 4d 70 43 65 68 69 48 7a 72 65 53 7a 4e 54 63 7a 6b 63 39 64 ... > }
```

I don't think this image has any EXIF metadata. Could it be the `TIFFTAG_PHOTOSHOP` metadata that you're expecting? libvips exposes this but sharp does not currently.

Do you have a non-TIFF example that exhibits this behaviour?

**Comment by SanderVanLeeuwen** [comment]
Thanks for looking in to this. You might be right that all files I encountered this with are TIFF's, I cannot remember any questions about JPG's from within our community.

To be honest I don't know all ins and outs about metadata locations in image files. For this specific example I just checked the data in Photoshop (available) and used a tool like http://metapicz.com/#landing to check the data (available), but where those tools are looking specifically I don't know.

Is it possible to easily expose this data in sharp too?

When I find a non-TIFF example I'll let you know!

**Comment by lovell** [comment]
v0.23.4 now available, which exposes the raw `TIFFTAG_PHOTOSHOP` metadata in the `tifftagPhotoshop` property.

**Comment by SanderVanLeeuwen** [comment]
An early Christmas present! Thanks; will experiment with it in the coming days! :)

**Comment by lovell** [comment]
No worries, you'll still need logic to parse the contents of the Buffer as this provides the raw data only. I'd be interested to learn if you are able to find/make something suitable to do this.
