### ISSUE TITLE
image resizing only working first time

### ISSUE THREAD

**Issue by zubair-0** [lovell/sharp#1607]
Node: 6.11.5
Sharp: 0.20.1 | 0.21.3

I've been trying to resize an image. Sharp returns the correct resized image on the first 1 or 2 tries. But afterwards it always returns the first resized image every time. Even the different input files to sharp has different hashes, but the output file of sharp has same hash.

For example:
>hash(inputFile1) -> inputFile1HASH
>sharp(inputFile1).resize(w, h).webp().toFile(outputFile1)
>hash(outputFile1) -> **outputFile1HASH** (GOOD)

>hash(inputFile2) -> inputFile2HASH
>sharp(inputFile2).resize(w, h).webp().toFile(outputFile2)
>hash(outputFile2) -> **outputFile1HASH** (BAD)

>hash(inputFile3) -> inputFile3HASH
>sharp(inputFile3).resize(w, h).webp().toFile(outputFile3)
>hash(outputFile3) -> **outputFile1HASH** (BAD)

This is the code
```javascript
sharp(inputFilePath)
.resize(width, height)
.webp()
.toFile(outputFilePath)
```

Any help would be appreciated. Or if i'm doing something wrong, please let me know.

**Comment by lovell** [comment]
Hello, if the contents of `inputFilePath` are changing but the path itself remains the same then you'll need to disable libvips cache via `sharp.cache(false)`.

https://sharp.pixelplumbing.com/en/stable/api-utility/#cache

**Comment by zubair-0** [comment]
Hello, thank you so much. This resolved the issue. It would be awesome to have this *same path is cached* and other things like this in the docs too. Thanks again. This saved a lot of trouble and time. A big salute to you and the sharp community for this awesome library.
