### ISSUE TITLE
Sandboxed API

### ISSUE THREAD

**Issue by avishnyak** [lovell/sharp#1614]
Since resizing untrusted images is a fairly common use case for this library, is it possible to provide a sandboxed version of the bindings?

https://security.googleblog.com/2019/03/open-sourcing-sandboxed-api.html?m=1

**Comment by lovell** [comment]
I have no immediate plans to do this but would be happy to review/consider a third party repo that provides a sandboxed implementation of [libvips C++](https://libvips.github.io/libvips/API/current/using-from-cpp.html) API.

**Comment by lovell** [comment]
I'll close this as it's not really something that I can see working directly in sharp, especially as there's not much support upstream for anything other than Debian-based Linux, plus for true sandboxing you'd probably want an abstraction layer between libvips and its dependencies too, which is a significant amount of rework.

libvips and many of its common, web-focussed dependencies are continously fuzz-tested via OSS-Fuzz - see https://github.com/google/oss-fuzz/tree/master/projects/libvips

For memory safety on Linux, the use of mimalloc is a future possible enhancement - see https://github.com/lovell/sharp-libvips/issues/95
