### ISSUE TITLE
Using sharp.strategy.entropy in v0.22 to smart crop?

### ISSUE THREAD

**Issue by mawtex** [lovell/sharp#1615]
How can I make Sharp do "smart crop" with v0.22? 

The examples I've looked at use crop(), which has been removed.

Thanks!!

**Comment by lovell** [comment]
```javascript
.resize({ position: sharp.strategy.entropy })
```

See the 4th example at https://sharp.pixelplumbing.com/en/stable/api-resize/#examples

**Comment by mawtex** [comment]
With the below code, I get the exact same output when setting position to sharp.strategy.entropy, sharp.strategy.attention and center (default). I'm using [this pic](https://ak3.picdn.net/shutterstock/videos/23496613/thumb/1.jpg) as input.

    const transformer = sharp()
        .resize({
            width: 100,
            height: 200,
            fit: sharp.fit.cover,
            position: sharp.strategy.entropy
        });

    var readStream = fs.createReadStream('./cat-in.jpg');    
    var writeStream = fs.createWriteStream('./cat-out.jpg');
    readStream.pipe(transformer).pipe(writeStream);

The output image change position for a option like sharp.gravity.east.

Using Sharp 0.22.0, tried this onnode v8.11.1 and v10.15.3 on Windows. 

Thank you for your support and big thanks a pretty impressive library, best performing and best compression I've seen so far on the portable node/.net options I've tested.

**Comment by lovell** [comment]
Here's what I see when I use the above sample image and code:

Centre:
![centre](https://user-images.githubusercontent.com/210965/54721276-71819100-4b59-11e9-97ef-a13f00c5cc01.png)

Attention:
![attention](https://user-images.githubusercontent.com/210965/54721275-71819100-4b59-11e9-8818-64fb9631c9b8.png)

Entropy:
![entropy](https://user-images.githubusercontent.com/210965/54721277-71819100-4b59-11e9-97da-3315cc573555.png)

(The accuracy of the "attention" strategy will be slightly improved, or at least less prone to noise, in the forthcoming libvips v8.8.0 thanks to https://github.com/libvips/libvips/pull/1083)

**Comment by mawtex** [comment]
You are right, it all works super well, I will just leave the below 'smallest working sample' for anyone else re-living my brain fart:

    const sharp = require("sharp");

    sharp('cat-in.jpg')
        .resize({
            width: 50,
            height: 100,
            fit: sharp.fit.cover,
            position: sharp.strategy.entropy
        })
        .toFile('cat-out.jpg');

Thanks @lovell
