### ISSUE TITLE
Can't rotate composite images

### ISSUE THREAD

**Issue by nikodraca** [lovell/sharp#1616]
I'm trying to do something like this, where `imageTwo` is an SVG.

```
let imageOne = await sharp(readStream).composite([
  {
    input: Buffer.from(imageTwo),
    blend: 'multiply',
    top: 280,
    left: 247,
    rotate: 40 // this
  }
]);
```

I have tried turning `imageTwo` into a Sharp object, rotating it, and exporting it as a buffer, however this compresses and blurs the image.

**Comment by lovell** [comment]
Hello, there is no `rotate` parameter on the [composite](https://sharp.pixelplumbing.com/en/stable/api-composite/#composite) operation.

The most efficient way to rotate an SVG is probably to wrap all the elements in `<g transform="rotate(40)"> ... </g>` before passing it in.

https://www.w3.org/TR/SVG11/coords.html#TransformAttribute

**Comment by nikodraca** [comment]
I've actually tried this and for whatever reason it seems to lose quality as well. I'm going to close this though because I think it's honestly a limitation of SVG more than anything else. Thanks for the reply!
