### ISSUE TITLE
Lower quality no difference in file size

### ISSUE THREAD

**Issue by OZZlE** [lovell/sharp#1617]
Hi, we are using AWS Lambda@Edge to compress and resize images on the fly, I saw that the compression for jpeg's wasn't no where near fully compressed by default so I added the following options. `requiredFormat` can be either `webp` or `jpeg`.

I tested with quality 56 first and then 25 but it made no difference in file size for an original image that is 30 MB (6000x600 px), resized down to 1920 px. Both files were 861 KB..

    const Sharp = require('sharp');
    // ...
    S3.getObject(s3Params).promise()
      // perform the resize operation
      .then(data => Sharp(data.Body)
        .resize({
          width: width,
          withoutEnlargement: true,
          quality: 25,
          progressive: false, // jpeg option
          optimiseScans: false, // jpeg, required mozjpeg support
          chromaSubsampling: '4:4:4', // jpeg
          trellisQuantisation: true, // jpeg, required mozjpeg support
          overshootDeringing: true, // jpeg, required mozjpeg support
          // lossless: true, // webp option
        })
        .toFormat(requiredFormat)
        .toBuffer()
      )
    .then(buffer => {
      S3.putObject({
        Body: buffer,
        Bucket: s3_bucket,
        ContentType: contentType,
        CacheControl: 'private, max-age=31536000',
        Key: key,
        StorageClass: 'STANDARD',
      })

According to https://tinyjpg.com/ it can compress the image 45% further and the image afterwards looks perfect.. 

Some options state in the documentation that they require mozjpeg, how do I know if it's installed on Lambda@Edge?

Using:

    "sharp": {
      "version": "0.21.3",

**Comment by OZZlE** [comment]
If I use quality: 100 or 90 it's also 861 KB...

**Comment by OZZlE** [comment]
I bit bloaty but I saw now that these options aren't for the resize function but rather the webp and jpeg functions so what works is doing this:

    S3.getObject(s3Params).promise()
      .then(data => (() => {
        const quality = 25;
        if (accept.includes(variables.webpExtension)) {
          return Sharp(data.Body)
            .webp({
              quality,
              lossless: true,
            })
            .resize({
              width,
              withoutEnlargement: true,
            })
            .toFormat(requiredFormat)
            .toBuffer();
        }
        return Sharp(data.Body)
          .jpeg({
            quality,
            progressive: false, // jpeg option
            optimiseScans: false, // jpeg, required mozjpeg support
            chromaSubsampling: '4:4:4', // jpeg
            trellisQuantisation: true, // jpeg, required mozjpeg support
            overshootDeringing: true, // jpeg, required mozjpeg support
          })
          .resize({
            width,
            withoutEnlargement: true,
          })
          .toFormat(requiredFormat)
          .toBuffer();
      })())
      .then(buffer => {
        S3.putObject({
          Body: buffer,
          Bucket: s3_bucket,
          ContentType: contentType,
          CacheControl: 'private, max-age=31536000',
          Key: key,
          StorageClass: 'STANDARD',
        })

Still wondering if AWS Lambda@Edge supports mozjpeg though?

**Comment by lovell** [comment]
You'll need to compile libvips from source with support for mozjpeg and make it available globally. How you do that with Lambda@Edge is a question for AWS to answer or perhaps someone on StackOverflow to help with - good luck!

**Comment by OZZlE** [comment]
@lovell thanks! Your right it's not your concern really that they happen to use your lib (you should be honored - albeit their service is hard to use) 

I think I can compile node modules in Lambda environment, are you willing to share how you do that under normal circumstances? :) 

Can we keep this ticket open for a bit, so I can post the full solution to my specific problem? thanks :)

**Comment by OZZlE** [comment]
Seems like they already support `mozjpeg` already because the images becomes much smaller using Lambda than locally where I don't think I have it installed :)
