### ISSUE TITLE
Error for non-integer value for options of extract

### ISSUE THREAD

**Issue by nipunbharti** [lovell/sharp#1620]
I'm just trying to extract some part of the image given the coordinates. All the coordinates are in float. When I try to run the code it throws me this error.
Code:
`const left = Number(0.4043), top = Number(0.3591), width = Number(0.2096), height = Number(0.4337);
	return image
	  .extract({ left, top, width, height })
	  .toBuffer();
	})`

I tried converting it to Number also but still, it didn't work out

`node:3221) UnhandledPromiseRejectionWarning: Error: Non-integer value for left of 0.4043`

**Comment by lovell** [comment]
Hello, the values are in pixels and therefore require integer values.

https://sharp.pixelplumbing.com/en/stable/api-resize/#extract

(The docs could be a bit clearer in this regard, I'll update them.)

**Comment by lovell** [comment]
I've made a small improvement to the `extract` docs in commit 6032171, thank you.
