### ISSUE TITLE
Bailing early if bindings are broken

### ISSUE THREAD

**Issue by sidharthachatterjee** [lovell/sharp#1624]
Hello!

We've seen some instances of `sharp` failing because of a broken installation or env issue (attempt at documenting them is in https://github.com/gatsbyjs/gatsby/issues/10841). 

To make debugging easier for the user, we added a try catch and friendly error in `gatsby-plugin-sharp` (https://github.com/gatsbyjs/gatsby/pull/10677)

What do you think about adding this around the require here?
https://github.com/lovell/sharp/blob/fc178de309d8e4055e86ffe1bbcfcf40754c885b/lib/constructor.js#L10

In case it helps, the error message we show if requiring `sharp` fails is 

```
The dependency "sharp" does not seem to have been built or installed correctly.
      - Try to reinstall packages and look for errors during installation
      - Consult "sharp" installation page at http://sharp.pixelplumbing.com/en/stable/install/
```

Happy to open a PR if you think this is useful. Thank you for all the great work!

**Comment by lovell** [comment]
Hi Sidhartha, this is a great idea, thank you. I'm always happy to accept PRs that make error messages easier to deal with.

**Comment by sidharthachatterjee** [comment]
Thank you so much, Lovell! Opened a PR adding this 🙂
