### ISSUE TITLE
AWS Elasticbeanstalk Upgrade Issue

### ISSUE THREAD

**Issue by abelabbesnabi** [lovell/sharp#1625]
Hi,

I'm trying to upgrade a live node application that resides in AWS Elastcibeanstalk from v8.12.0 to v10.13.0
and the only issue that I see is caused by sharp complaining about being built with a different version.

Here's the error:

Error: The module '/var/app/current/node_modules/sharp/build/Release/sharp.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

I can't upgrade our prod aws elb instances because of this issue.

Please help :)

**Comment by lovell** [comment]
The version of Node used at runtime should match that at install time.

Like my software, I offer my advice *on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND* but what you describe here sounds like a terrible way to upgrade a production system.

**Comment by abelabbesnabi** [comment]
You're saying that the node version in dev had to match the node version in prod?
