### ISSUE TITLE
PNG adaptiveFiltering is slow

### ISSUE THREAD

**Issue by nunoguerra** [lovell/sharp#1628]
Resize of png file (2048x2048 to 1920) is very slow, takes more than 6 seconds on (4gb ram and 2 vCPUs) CPU Optimized Droplet of Digital Ocean.

The code:

`
sharp(file.Body).resize({ width: 1920 }).png({ progressive:true, adaptiveFiltering:true }).toBuffer()
`

Versions and cache:
```
{ cairo: '1.16.0',
  croco: '0.6.12',
  exif: '0.6.21',
  expat: '2.2.6',
  ffi: '3.2.1',
  fontconfig: '2.13.1',
  freetype: '2.10.0',
  fribidi: '1.0.5',
  gdkpixbuf: '2.36.12',
  gettext: '0.19.8.1',
  gif: '5.1.4',
  glib: '2.56.4',
  gsf: '1.14.45',
  harfbuzz: '2.3.1',
  jpeg: '2.0.2',
  lcms: '2.9',
  orc: '0.4.28',
  pango: '1.42.4',
  pixman: '0.38.0',
  png: '1.6.34',
  svg: '2.45.5',
  tiff: '4.0.10',
  uuid: '2.33.1',
  vips: '8.7.4',
  webp: '1.0.2',
  xml: '2.9.9',
  zlib: '1.2.11' }

{ memory: { current: 0, high: 0, max: 50 },
  files: { current: 0, max: 20 },
  items: { current: 0, max: 100 } }
```

Some help to improve the resize time?

**Comment by lovell** [comment]
Hi, are you able to share an input image that exhibits this behaviour? I suspect this relates to the use of interlaced PNGs, which are relatively memory and CPU intensive (use of `adaptiveFiltering` also increases CPU time a little).

**Comment by nunoguerra** [comment]
The original image is here: http://ic.imgix.net/21218/15c9668e116003

Offtopic: With Sharp we can achieve the same lossless compression of Kraken.io?

Thanks.

**Comment by lovell** [comment]
Thanks for the sample image.

According to callgrind, about 80% of CPU time is spent in zlib's `longest_match` function, which relates to PNG adaptive filtering. Disabling this feature, the default sharp behaviour, makes it ~5x faster (although can result in larger images for "photographic" input).

I think Kraken is "lossy" rather than "lossless" but you'll need to experiment.

**Comment by nunoguerra** [comment]
@lovell Thanks I will disabling adaptiveFiltering for now.

About the PNG lossless optimization, what you recommend, to get the min size and the same quality with Sharp?

**Comment by lovell** [comment]
You'll need to experiment - good luck!
