### ISSUE TITLE
Duplicate image and mirror

### ISSUE THREAD

**Issue by janus-reith** [lovell/sharp#1629]
I have a use case where my input image should cover 1/4 of the image to be generated.
The image is the top left corner, and should be flipped and rotated to top right, bottom right, and bottom left.
What I have is:
![oneCorner](https://user-images.githubusercontent.com/1831220/55063736-f2b8b680-5078-11e9-86bd-ac9ce6a961ac.jpg)

And the output should be
![fourCorners](https://user-images.githubusercontent.com/1831220/55063744-f8160100-5078-11e9-91b7-dcb4a2a1de67.jpg)

Is this something that can be achieved using sharp?
And if, I'd appreciate an example of how to.
I took a quick look at the docs, but didn't find exactly what I was searching for.

**Comment by lovell** [comment]
Hi, did you see the [flip](https://sharp.pixelplumbing.com/en/stable/api-operation/#flip) and [flop](https://sharp.pixelplumbing.com/en/stable/api-operation/#flop) operations?

**Comment by janus-reith** [comment]
Yes, thank you, thats what I found aswell and thought that I'd probably need it. Putting ist Info a more general context, what is missing for me is: How to compose my input image into a new image where I duplicate that layer multiple times and apply operations on each of these copies. Thanks for your Help!

**Comment by lovell** [comment]
Try an approach like the following (untested):

```javascript
const { width, height, channels } = await sharp(topLeft).metadata();
const topRight = await sharp(topLeft).flip().toBuffer();
const bottomLeft = await sharp(topLeft).flop().toBuffer();
const bottomRight = await sharp(topLeft).flip().flop().toBuffer();

const result = await sharp({
  create: {
    width: width * 2,
    height: height * 2,
    channels,
    background: 'black'
  }
})
  .composite([{
    input: topLeft,
    gravity: 'northwest'
  }, {
    input topRight,
    gravity: 'northeast'
  }, {
    input: bottomLeft,
    gravity: 'southwest'
  }, {
    input: bottomRight,
    gravity: 'southeast'
  }])
  .toBuffer();
```

**Comment by janus-reith** [comment]
Great, exactly what i was searching for!
Will take this as a base, way easier for me to work upon that now.
Thank you

I guess I will need to use v0.22.0 as this is the new composite array input introduced there.

**Comment by janus-reith** [comment]
Does `composite` work with stream based input?
I`m struggling to get this to work.

```
const topLeft = await sharp();

// const { width, height, channels } = topLeft.metadata();
// Does not work, is undefined. However I dont rely on that information.

const topRight = await topLeft.flip();
const bottomLeft = await topLeft.flop();
const bottomRight = await topLeft.flip().flop();

return sharp({
create: {
    width: 400,
    height: 400,
    channels: 4,
    //background: { r: 255, g: 0, b: 0, alpha: 1 }
    background: "red"
}
})
.composite([{
    input: topLeft.toBuffer(),
    gravity: "northwest",
}, {
    input: topRight.toBuffer(),
    gravity: "northeast",
}, {
    input: bottomLeft.toBuffer(),
    gravity: "southwest",
}, {
    input: bottomRight.toBuffer(),
    gravity: "southeast",
}])
.toFormat(format)
.on('error', err => { throw new Error("error-sharp-resize-internal", err); });
```

This throws `Error: Unsupported input object`
I also tried  leaving out `toBuffer()` on the input elements, same error.

The three images topRight, bottomLeft and bottomRight are created properly.
When I return one of them instead, the image is stored properly, eg.:

```
return bottomRight
.resize({width: size, height: size, fit: sharp.fit[fit], withoutEnlargement: true})
.toFormat(format)
.on('error', err => { throw new ReactionError("error-sharp-resize-internal", err); });
```

works.

**Comment by lovell** [comment]
The `composite()` operation does not support Stream-based input. This is the documented behaviour.

https://sharp.pixelplumbing.com/en/stable/api-composite/#composite

> images[].input (Buffer | String)? Buffer containing image data or String containing the path to an image file.

**Comment by janus-reith** [comment]
Thanks for your quick feedback. Would there be any workaround to achieve this? Is this a libvips limitation or just not implemented in sharp? I don't really have an idea about the complexity of this.

**Comment by janus-reith** [comment]
Or , would it possible to read my image into buffer during the stream? and to write out the result? Appareantly this is not what `toBuffer` does with streams

**Comment by lovell** [comment]
Perhaps use a module like [get-stream](https://www.npmjs.com/package/get-stream) to convert from Stream to Buffer.

**Comment by janus-reith** [comment]
Tried with both `get-stream` and `concat-stream`, without sucess.

I am working with a transform stream, but can only mutate each chunk.

**Comment by janus-reith** [comment]
**I could solve this without external dependencies.**
And while this probably destroys most of the advantages of using a stream, it works great for my case.

I implemented a custom transform stream, where each transform pushes the chunk into an array and returns an empty string in the callback.

Then in the `_flush` function of that stream I run `Buffer.concat` on that error to have a Buffer that I can use with sharp.

Not sure why I have to use `_flush` as I'm running on Node 8 and expected `_final` to do this, but that did not return any data, and using `_flush` works.
