### ISSUE TITLE
Sharp Libvips currently downloads sharp directly from github. Would it be possible to provide an env var to a local version of the sharp download?

### ISSUE THREAD

**Issue by xdobtqletrmn** [lovell/sharp#1637]
In [this file reference](https://github.com/lovell/sharp/blob/master/install/libvips.js#L19), the download url is hard-coded to the github download url. Would it be possible to set an env var or similar which allows us to point to a locally stored version of the download?

I've also just seen https://github.com/lovell/sharp/issues/1418, which feels related - perhaps there's already a workaround/fix?

Thanks for the help.

**Comment by lovell** [comment]
Hi, did you see the `SHARP_DIST_BASE_URL` environment variable (referenced in the line of code you linked to)?

https://sharp.pixelplumbing.com/en/stable/install/#pre-compiled-libvips-binaries

**Comment by xdobtqletrmn** [comment]
Wow - sorry for wasting time! 🤦‍♂️
