### ISSUE TITLE
Recomb would be cool

### ISSUE THREAD

**Issue by richardkazuomiller** [lovell/sharp#164]
Thanks for making this!

I'd like to use a recombination matrix (`vips_recomb`) to do some color space conversions (sepia and all that fun stuff). It goes beyond resizing, but would that be a good addition to this project? I haven't tried implementing it yet but it looks straightforward enough.

**Comment by lovell** [comment]
Thanks for the suggestion. Taking advantage of more features of libvips will be significantly easier after #152.

**Comment by richardkazuomiller** [comment]
That sounds pretty good to me. In the meantime would you take a PR implementing it using the old methods?

**Comment by lovell** [comment]
Of course, that would be great, thank you. If you've not already seen it, there's a [contribution](https://github.com/lovell/sharp/blob/master/CONTRIBUTING.md) guide with a few more details.

Off the top of my head, things to consider include ensuring the matrix is freed from memory after use. The existing [flattening](https://github.com/lovell/sharp/blob/master/src/resize.cc#L363) logic provides an example of this. You may also need to `vips_cast` the resultant image back to integer from float/double.

You've probably already found a matrix suitable for a sepia effect, but if not, the "open source Instagram" that is GPUImage library provides [SepiaFilter](https://github.com/BradLarson/GPUImage/blob/master/framework/Source/GPUImageSepiaFilter.m).

Good luck!

**Comment by lovell** [comment]
The following (hard-coded) matrix seems to work for a sepia-like effect:
```cc
VImage sepia = VImage::new_matrixv(
  3, 3,
  0.3588, 0.7044, 0.1368,
  0.2990, 0.5870, 0.1140,
  0.2392, 0.4696, 0.0912
);
```
I need to think more about how the JavaScript API to expose/support recombination matrices might look.

**Comment by rnanwani** [comment]
Hi. This issue seems an old one. I can work on this if you can suggest a relevant JS API.
I was thinking of exposing this as something like

```
sharp().recombine("sepia").toBuffer()
```

The `recombine` can also be termed as `effect` and we can support only specific named values instead of complete recombination matrices.

**Comment by lovell** [comment]
Thanks Rahul, mirroring libvips' naming would suggest `recomb` is best for this and the API should at least support 2d matrices via an Array of Arrays, e.g.
```javascript
.recomb([[0.3588, 0.7044, 0.1368], [0.2990, 0.5870, 0.1140], [0.2392, 0.4696, 0.0912]])
```

Predefined matrices could live in a new `sharp.matrix` namespace, e.g.
```javascript
.recomb(sharp.matrix.sepia)
```
which as you suggest can be accessed via a `sharp.matrix[name]` lookup, e.g.
```javascript
.recomb('sepia')
```

**Comment by lovell** [comment]
Now available - see http://sharp.pixelplumbing.com/en/stable/api-operation/#recomb
