### ISSUE TITLE
DICOM input to JPEG output

### ISSUE THREAD

**Issue by adamwilbert** [lovell/sharp#1640]
What are you trying to achieve?

I am passing raw pixel data (single channel) from a dicom image into sharp and attempting to output a jpeg.  Everything appears to be parsing out of the dicom correctly and i can recreate the problem with jpg to jpg as well.

Have you searched for similar questions?
Yes

Are you able to provide a standalone code sample that demonstrates this question?
I am getting raw pixel data out of a dicom image and passing it into sharp, but the output is not at all as expected.  (i am getting a similar issue passing raw image data from a local jpg using sharp(jpg).raw().toBuffer() as the input.  Perhaps I am just not using this correctly?
```

const jpgBuffer = await sharp(imgBuffer, {
        raw: {
          width: image.width,
          height: image.height,
          channels: 1
        }
      })
        .jpeg({ quality: 100 })
        .toBuffer()

```
Are you able to provide a sample image that helps explain the question?
Output is overlaid on itself and not the entirety of original image.

![filename (4)](https://user-images.githubusercontent.com/15695586/55505607-4f334d00-5608-11e9-90a6-27bc4b9eac89.jpg)
![Screen Shot 2019-04-03 at 12 02 31 PM](https://user-images.githubusercontent.com/15695586/55505656-6eca7580-5608-11e9-806c-8e929c52fc54.png)

I would upload the dcm, but github does not support it, I have attached a quick screenshot to show the example

**Comment by lovell** [comment]
Hello, thanks for the detailed report. Are you able to share a (non-GitHub) link to the original DICOM image?

**Comment by adamwilbert** [comment]
https://deanvaughan.org/projects/dicom_samples/xr_chicken1.dcm

**Comment by adamwilbert** [comment]
I was also having a similar issue passing a sharp raw output into the same function

i.e.

`
const jpgBuffer = await sharp(sharp(aDifferentJpgBuffer).raw().toBuffer(), {
        raw: {
          width: image.width,
          height: image.height,
          channels: 1
        }
      })
        .jpeg({ quality: 100 })
        .toBuffer()
`

**Comment by lovell** [comment]
Thanks, this file is not raw pixel data, it also contains a DICOM header/metadata.

You'll need to compile libvips with support for ImageMagick and install it globally to read DICOM files.

**Comment by adamwilbert** [comment]
> Thanks, this file is not raw pixel data, it also contains a DICOM header/metadata.
> 
> You'll need to compile libvips with support for ImageMagick and install it globally to read DICOM files.

I am aware of that, I have used a different package to get the raw pixel data and am feeding that as a buffer to sharp.

**Comment by lovell** [comment]
Please can you share the code that extracts the raw pixel data from the DICOM file?

(The JPEG example will require `channels: 3`)

**Comment by adamwilbert** [comment]
```
const daikon = require('daikon')
const fs = require('fs')
const sharp = require('sharp')

const imgBuf = fs.readFileSync('/path/to/xr_chicken1.dcm')
const dicom = daikon.Series.parseImage(new DataView(imgBuf.buffer))
const dicomBuffer = Buffer.from(dicom.getRawData())


const jpgBuffer = sharp(dicomBuffer, {
        raw: {
          width: dicom.getCols(),
          height: dicom.getRows(),
          channels: dicom.getNumberOfSamplesPerPixel()
        }
      }).jpeg({ quality: 100 }).toBuffer().then((e, d) => console.log(e, d))

```

**Comment by lovell** [comment]
This input looks like 16 bit per pixel (bpp) but sharp currently only supports raw input with 8 bpp.

Please see #1289 for a future possible enhancement to accept a `TypedArray`, which would include the `Float32Array` returned by daikon's `getInterpretedData()` function.

**Comment by adamwilbert** [comment]
> This input looks like 16 bit per pixel (bpp) but sharp currently only supports raw input with 8 bpp.

Can you explain the jpeg issue then?  The output looked similarly problematic.  I'm just curious if there was another root cause.

**Comment by lovell** [comment]
Are you able to share the input JPEG image?

**Comment by adamwilbert** [comment]
changing the jpg from 1 channel to 3 channels seem to fix that issue from raw buffers created from jpegs in sharp.

**Comment by adamwilbert** [comment]
Also would it be possible to just downsample the dicom raw pixel buffer into 8bit values and feed that to sharp?

**Comment by lovell** [comment]
To downsample, the Node Buffer object's `readUInt16BE` and `readUInt16LE` methods provide access to the 16 bit values returned by `getRawData`.

**Comment by adamwilbert** [comment]
Thank you!

**Comment by lovell** [comment]
Please subscribe to #1289 if you're interested in updates to raw pixel support beyond a depth of 8 bit.

**Comment by echo1consulting** [comment]
@adamwilbert what was your solution? do you have example of your working code?
