### ISSUE TITLE
Don't want to use npm proxy to simple_get libvips

### ISSUE THREAD

**Issue by s524797336** [lovell/sharp#1641]
I install sharp in docker, I have a npm cache layer so i have to set npm proxy to my cache server, but sharp download libvips use this proxy, and have to use https, my proxy not support https, even i support https, i don't want it to use it, use proxy is good, but why read proxy from npm setting?

**Comment by lovell** [comment]
An HTTP proxy should work fetching the binaries from GitHub - there's logic to detect the protocol used by a proxy, if any.

You've not said so here but my best guess is that you're setting `SHARP_DIST_BASE_URL` to a custom URL, in which case you will need to provide an HTTPS URL (although this too can be proxied via HTTP).

https://sharp.pixelplumbing.com/en/stable/install/#pre-compiled-libvips-binaries

**Comment by s524797336** [comment]
I set npm_config_https_proxy and  npm_config_http_proxy

**Comment by lovell** [comment]
The `HTTP_PROXY` environment variable is used in preference to the npm settings so perhaps set that to your HTTP proxy.
