### ISSUE TITLE
Detecting whether withoutEnlargement is fired or not

### ISSUE THREAD

**Issue by Dayjo** [lovell/sharp#1642]
## What are you trying to achieve?
I am trying to create a set of sizes under the original size.  

The withoutEnlargement option works in that it does not scale up the image, however, ideally there would be a flag or something when doing toFile/toBuffer to say that the image was larger than the original image. 

The problem I have at the moment is that I'm doing the following;

```js
sharp(tmpFilePath)
        .resize(width, null, {
          withoutEnlargement: true
        })
        .toFile(thumbPath)
        .then((a) => {
// Upload file to GCS
});
```

And I would like to NOT create the new file in GCS if it is just the same as the original size, that way I don't have a file called '2000-image.jpg' when the width is actually 1500.

Is there something I'm missing, or an extra callback parameter or something that would allow me to know in the `then` function so I could decide not to upload it. 

## Have you searched for similar questions?
Yes

## Are you able to provide a standalone code sample that demonstrates this question?
Not immediately, but I can if needed.

## Are you able to provide a sample image that helps explain the question?
Any image under the size you're trying to resize to.

**Comment by lovell** [comment]
Hello, in your code example the `a` parameter passed to `then()` is an object that includes the post-resize dimensions. Perhaps add a test for `a.width` being less than `width`?

**Comment by Dayjo** [comment]
@lovell wonderful, that's a perfect solution thank you :)
