### ISSUE TITLE
install Zlib 1.2.9 failed

### ISSUE THREAD

**Issue by Mephiztopheles** [lovell/sharp#1644]
What are you trying to achieve?
I am trying to use sharp. So i need zlib 1.2.9.
I "installed" zlib 1.2.11 but if i use node -e "console.log(process.versions.zlib)", i get 1.2.8
so i guess i did not install it correctly, but i really dont know how to..

I switched from windows to linux (bought raspberry pi)
using raspbian stretch (NOOBS)

i already checked if i have node-canvas installed in my node_modules and it is not.

Have you searched for similar questions?
ya, but they are not answered or have other circumstances

Are you able to provide a standalone code sample that demonstrates this question?
can't even start the app

Are you able to provide a sample image that helps explain the question?
not related to image

**Comment by lovell** [comment]
What is the output of running `npm install --verbose sharp`?

**Comment by Mephiztopheles** [comment]
![Screenshot_20190404-233430](https://user-images.githubusercontent.com/6481850/55590133-56ef1080-5732-11e9-972f-c2010a1f43ee.jpg)
![Screenshot_20190404-233422](https://user-images.githubusercontent.com/6481850/55590134-56ef1080-5732-11e9-8aa5-3d508e37cc3f.jpg)
![Screenshot_20190404-233500](https://user-images.githubusercontent.com/6481850/55590135-56ef1080-5732-11e9-8074-62ed727f7a73.jpg)
![Screenshot_20190404-233454](https://user-images.githubusercontent.com/6481850/55590137-5787a700-5732-11e9-91c7-e612208fe02c.jpg)
![Screenshot_20190404-233414](https://user-images.githubusercontent.com/6481850/55590139-5787a700-5732-11e9-9e74-40f4b182079c.jpg)
![Screenshot_20190404-233407](https://user-images.githubusercontent.com/6481850/55590140-5787a700-5732-11e9-9de2-d7f10dbe7074.jpg)
I tried to get all lines

**Comment by Mephiztopheles** [comment]
They are not in correct order, i see

**Comment by lovell** [comment]
Thanks, no obvious problems there.

How was Node installed? I'd expect Node 8 to ship with an internal version of zlib 1.2.11 rather than 1.2.8. Could it have been compiled with the `--shared-zlib` flag?

**Comment by Mephiztopheles** [comment]
I dont know how to compile it.. can you tell me the full command?

Lovell Fuller <notifications@github.com> schrieb am Fr., 5. Apr. 2019,
11:10:

**Comment by lovell** [comment]
A quick way to test if a `node` executable was compiled with `--shared-zlib` is to look for zlib listed as a runtime dependency in the output of `ldd /usr/bin/node` (if that is the correct path).

**Comment by Mephiztopheles** [comment]
![Screenshot_20190405-141651](https://user-images.githubusercontent.com/6481850/55627084-99096800-57ad-11e9-9eff-c29752c4be9d.jpg)

**Comment by lovell** [comment]
Thanks, this means Node will load the /usr/lib/.../libz shared library first, which currently provides only 1.2.8, so your original idea to compile and install zlib 1.2.11 is still the best solution.

https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/FAQ#L85-L105

**Comment by Mephiztopheles** [comment]
I already installed it but without the clean... Can i now just do so, how declared in the guide or do i need to uninstall first?
If so ,how do i?

**Comment by Mephiztopheles** [comment]
I did kill my pi yesterday so i have no interest in killing it again today

**Comment by Mephiztopheles** [comment]
I tried 
make uninstall
make distclean
./configure
make
make install

but the problem still exists... 
and if i check the files in /lib/arm-linux-gnueabihf, i get:
lrwxrwxrwx  1 root root      13 Jan 29  2017 libz.so.1 -> libz.so.1.2.8
-rw-r--r--  1 root root   91884 Jan 29  2017 libz.so.1.2.8

**Comment by lovell** [comment]
Run `sudo ldconfig` then check `ldd /usr/bin/node` again.

**Comment by Mephiztopheles** [comment]
linux-vdso.so.1 (0x7ed15000)
        /usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76ebb000)
        libz.so.1 => /lib/arm-linux-gnueabihf/libz.so.1 (0x76e7e000)
        libhttp_parser.so.2.8 => /usr/lib/arm-linux-gnueabihf/libhttp_parser.so.2.8 (0x76e66000)
        libuv.so.1 => /usr/lib/arm-linux-gnueabihf/libuv.so.1 (0x76e36000)
        libcares.so.2 => /usr/lib/arm-linux-gnueabihf/libcares.so.2 (0x76e16000)
        libcrypto.so.1.0.2 => /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.2 (0x76c94000)
        libssl.so.1.0.2 => /usr/lib/arm-linux-gnueabihf/libssl.so.1.0.2 (0x76c35000)
        libicui18n.so.57 => /usr/lib/arm-linux-gnueabihf/libicui18n.so.57 (0x76a25000)
        libicuuc.so.57 => /usr/lib/arm-linux-gnueabihf/libicuuc.so.57 (0x768bb000)
        libicudata.so.57 => /usr/lib/arm-linux-gnueabihf/libicudata.so.57 (0x7502e000)
        libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x7501b000)
        librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0x75004000)
        libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0x74ebc000)
        libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x74e3d000)
        libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0x74e10000)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x74de7000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x74ca8000)
        /lib/ld-linux-armhf.so.3 (0x76ed1000)
        libnsl.so.1 => /lib/arm-linux-gnueabihf/libnsl.so.1 (0x74c84000)

**Comment by Mephiztopheles** [comment]
But /lib/arm-linux-gnueabihf/libz.so.1 is not linked to libz.so.1.2.11

**Comment by lovell** [comment]
Yes, this is intentional, the two versions will exist in different locations.

The `make install` step will place 1.2.11 in (I think) /usr/local/lib, which should take precedence over /lib when searching for shared libraries.

https://www.raspberrypi.org/forums/viewtopic.php?t=41871

This is well beyond being a sharp-specific problem so I'm going to have to bid you good luck here!

**Comment by Mephiztopheles** [comment]
hm... did not work for me
