### ISSUE TITLE
alpha weighted mean values of RGB channels in Sharp.stats

### ISSUE THREAD

**Issue by MrNghia123** [lovell/sharp#1645]
I am trying to get the "weighted" mean of the red, green and blue channels of a png image. The weight here is the alpha channel value. I am doing this to get a rough idea about the colors of the png image to choose a background
The "stats" function does provide mean values for red, green and blue channels, but the mean values are calculated over all of the pixels, regardless of the alpha value. Therefore the mean values are skewed by the hidden pixels, which make them useless for my use.
So instead of sum of the channels values and divide by the number of the pixels, 
a sumproduct with alpha before dividing by the number of the pixels would be the value I need.

In the two images below, the "opaque" one (black background) was created from the original by
sharp('/foreGround.png')
.removeAlpha()
.ensureAlpha()
.toFile('foreGround_opaque.png')

You can see that the "hidden" pixels in the original image is revealed in the "opaque" version, and they are all black in this case. In other cases, they can be in any colors.
 
I don't seem to find any other questions related to my problem.

Below is the code I am using to calculate the luminance of the mean colors
sharp('/foreGround.png')
.stats()
.then(result=>{
  const { channels: [rc, gc, bc] } = result
  const red = Math.round(rc.mean),
  green = Math.round(gc.mean),
  blue = Math.round(bc.mean)
  luminance = calculateLuminance([red,green,blue])
  console.log(red, green, blue, luminance)
})

Produce the same output for both original and opaque images

3 3 2 0.0008886663024342864

Original image

![foreGround](https://user-images.githubusercontent.com/12420944/55618562-0d99d200-57c1-11e9-8263-0a14d9c9665f.png)

Opaque version

![foreGround_opaque](https://user-images.githubusercontent.com/12420944/55618561-0d013b80-57c1-11e9-9b8c-7f4069369898.png)

**Comment by lovell** [comment]
It sounds like the logic required here is "don't include fully-transparent pixels in the averaging calculation", in which case you'll probably need to perform these yourself using the raw pixel data.

**Comment by MrNghia123** [comment]
That's right! Can you point me a bit further to the right direction about how to access the raw pixel data? Thanks.

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/en/stable/api-output/#raw
