### ISSUE TITLE
AWS Lambda Resize with cover property does not work as expected

### ISSUE THREAD

**Issue by ahbruinsma** [lovell/sharp#1646]
Hello,

I am trying to zoom-in an image and create a new one with the resize functions. So my flow is as follows:

1. I've got a transparant image with dimensions 5580x3488 which I save into a sharp buffer
2. I resize that image to 6920x4326 so the actual image looks bigger
3. Then I want to create a new image with the dimension of the first one but the content of the second one. So it looks like I'm zoom-ing in onto the image

Step 1 works en step 2 as well, but whenever I do step 3, I get an image back which has just been resized to the previous dimensions. My code looks a little bit like this:

`sharp(buffer_result).resize(6920, 4326).toBuffer().then(function(buffer_result_resize) {
  sharp(buffer_result_resize).resize({width: 5580, height: 3488, fit: sharp.fit.cover}).toBuffer().then(function(buffer_result_relative) {})})`

buffer_result is the starting image with the 5580x3488 resolution.

I've tried different syntaxing for the second resize which is being provided in the documentation, but none of them are working. (like .resize(200, 300, { fit: 'cover'}) or {width: 5580, height: 3488, fit: sharp.fit.cover} etc).

I am using version 0.21.0 on an AWS Lambda environment. Are there any issues known with this version or with AWS Lambda? Or am I taking a wrong approach to this?

With kind regards,
Andries

**Comment by lovell** [comment]
Did you see the [extract](https://sharp.pixelplumbing.com/en/stable/api-resize/#extract) operation, which I think is what you're describing at step 3.

**Comment by lovell** [comment]
Hope this helped, please feel free to re-open with more details if further help is required.
