### ISSUE TITLE
 Incompatible library version: libvips-cpp.dylib requires version 10.0.0 or later, but libtiff.5.dylib provides version 9.0.0

### ISSUE THREAD

**Issue by BiancoA** [lovell/sharp#1647]
What is the output of running `npx envinfo --binaries --languages --system --utilities`?
```
 System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
    Memory: 414.53 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.3.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Utilities:
    CMake: 3.13.1 - /usr/local/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.20.0 - /usr/local/bin/git
  Languages:
    Bash: 3.2.57 - /bin/bash
    Perl: 5.18.2 - /usr/bin/perl
    PHP: 7.1.23 - /usr/bin/php
    Python: 2.7.15 - /usr/local/bin/python
    Ruby: 2.3.7p456 - /usr/bin/ruby
```

After an update from sharp 0.20.8 to 0.22.0 I got this unexpected error while running my application. It looks funny, I though that sharp was using its own libraries stored in the vendor directory, so I don't understand if this is related to some other libtiff library present.

I use     `"electron-builder": "20.39.0"`,  to pack everything together, this is the error I get launching: `electron-webpack dev`
```
Error: dlopen(/Users/bianco/Src/AppWebPack/node_modules/sharp/build/Release/sharp.node, 1): Library not loaded: @rpath/libtiff.5.dylib
    Referenced from: /Users/bianco/Src/AppWebPack/node_modules/sharp/vendor/lib/libvips-cpp.42.dylib
    Reason: Incompatible library version: libvips-cpp.dylib requires version 10.0.0 or later, but libtiff.5.dylib provides version 9.0.0
      at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
      at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
      at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
      at Module.load (internal/modules/cjs/loader.js:602:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
      at Function.Module._load (internal/modules/cjs/loader.js:533:3)
      at Module.require (internal/modules/cjs/loader.js:640:17)
      at require (internal/modules/cjs/helpers.js:20:18)
      at bindings (/Users/bianco/Src/AppWebPack/node_modules/bindings/bindings.js:112:48)
      at Object.<anonymous> (/Users/bianco/Src/AppWebPack/node_modules/sharp/lib/constructor.js:10:34)
```

**Comment by lovell** [comment]
Hello, has libtiff (or vips) been installed globally via Homebrew? If so, has `brew update && brew upgrade` been run?

Are there any other native dependencies of your Electron app that might require libtiff?

**Comment by BiancoA** [comment]
hello,

updating the globally installed libtiff doesn't make any difference, I don't have visp installed.

I have another native dependency that require libtiff, I am trying to update that also. It is weird anyway that there is a conflict between the two, since they have different paths

**Comment by lovell** [comment]
Whichever dependency requires their libtiff shared library first will "win" for this is the shared library game.

**Comment by BiancoA** [comment]
The issue is solved updating the libtiff in the other native dependency. Thanks for the support!
