### ISSUE TITLE
flatten() ignoring background option

### ISSUE THREAD

**Issue by MacroMan** [lovell/sharp#1652]
What is the output of running `npx envinfo --binaries --languages --system --utilities`?
```
  System:
    OS: Linux 4.4 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (2) x64 Intel(R) Pentium(R) CPU G3250 @ 3.20GHz
    Memory: 630.13 MB / 3.79 GB
    Container: Yes
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 8.15.1 - /usr/bin/node
    npm: 6.9.0 - /usr/bin/npm
  Utilities:
    Make: 4.1 - /usr/bin/make
    GCC: 5.4.0 - /usr/bin/gcc
    Git: 2.7.4 - /usr/bin/git
  Languages:
    Bash: 4.3.48 - /bin/bash
    Perl: 5.22.1 - /usr/bin/perl
    PHP: 7.0.33 - /usr/bin/php
    Python: 2.7.12 - /usr/bin/python
    Ruby: 2.2.3p173 - /home/user/.rvm/rubies/ruby-2.2.3/bin/ruby
```

What are the steps to reproduce?
Run the supplied code with the supplied image

What is the expected behaviour?
The output image should have a white background, but has the default black background.

Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?
```
const sharp = require('sharp');

sharp('product.png')
.flatten('#FFF')
.toFile('product2.png', function(err) {
  if (err) {
    throw err;
  }
});
```
I have also tried with
* `.flatten({r:255, g:255, b:255})`
* `.flatten({background: '#FFF'})`
* `.flatten({background: {r:255, g:255, b:255}})`

Are you able to provide a sample image that helps explain the problem?
![product](https://user-images.githubusercontent.com/1306658/55786296-e5092500-5aab-11e9-995b-04b4222976fa.png)

Output image for all methods of flatten:
![product2](https://user-images.githubusercontent.com/1306658/55786532-5943c880-5aac-11e9-898f-6f255e35baca.png)

**Comment by MacroMan** [comment]
This might be related to #1651

**Comment by lovell** [comment]
Are you using the latest version?

Using the documented `.flatten({ background: '#FFF' })` approach works for me with the provided image.

https://sharp.pixelplumbing.com/en/stable/api-operation/#flatten

**Comment by MacroMan** [comment]
I'm running Sharp 0.22.0 on Node 8.15.1

Just checked with the following code and it's still producing a black background:

```
const sharp = require('sharp');

sharp('product.png')
.flatten({ background: '#FFF' })
.toFile('product2.png', function(err) {
  if (err) {
    throw err;
  }
});
```
What else might be causing this problem?

Just encase github upload is changing the image somehow, here is the original: https://img2.aplpackaging.com/apollo-dev/product.png?type=png

**Comment by MacroMan** [comment]
Seems I was running an old version from where I was running my script from. Now working. Sorry.
