### ISSUE TITLE
XDR 12 bit jpeg conversion

### ISSUE THREAD

**Issue by adamwilbert** [lovell/sharp#1653]
What are you trying to achieve?
I am importing XDR files.  When using sharp.metadata() sharp correctly identifies them as jpegs, but they are single channel, 12bit encoded.  When I attempt to pass the buffer to sharp I get
`VipsJpeg: Unsupported JPEG data precision 12`
which I suppose makes sense as sharp supports 8bit.  I have attempted to then pass it as a raw buffer and downsample to 8bit using readInt16LE, I end up getting 
`	VipsImage: memory area too small --- should be 2593728 bytes, you passed 308684`
despite specifying single channel data.

Am I missing something?  

Have you searched for similar questions?
Yes

Are you able to provide a sample image that helps explain the question?
Unfortunately I can not.

**Comment by lovell** [comment]
Please see https://github.com/libvips/libvips/issues/664

**Comment by adamwilbert** [comment]
I won't have the option to custom compile libvips/libjpeg to 12 bit as I am running serverless

Is it not possible to do the conversion manually before feeding the output to sharp?  I see the discussion of packed 12bit i.e. RR RG GG BB BR RR GG GB BB RR RG GG BB, but how does this apply to single channel?

Thanks!

**Comment by lovell** [comment]
The 12-bit JPEG will be compressed, not raw pixel data, so short of writing your own 12-bit JPEG decoder I'm not sure what options you've got if you can't compile libjpeg from source - perhaps ask on StackOverflow.
