### ISSUE TITLE
Uncaught svg manipulation error on linux

### ISSUE THREAD

**Issue by spencermountain** [lovell/sharp#1658]
hi, thank you so much for this library, it's amazing.

I've found an uncaught error when processing some svg images, under linux.

it seems to be a pretty niche bug, so apologies if it belongs in `librsvg` or something.

The following brings down the process, and doesn't appear to be try/catchable:
```js
const request = require('axios')
const link = 'http://pathways.io/assets/logo/svg/Pathways-2019.svg';

// fetch svg image to buffer
const response = await request.get(link, { responseType: 'arraybuffer' });
const buffer = Buffer.from(response.data, 'binary');

// resize + toBuffer
await Sharp(buffer)
    .resize(100)
    .toBuffer();
// never makes it here
```
it works on a mac - it even works if there's a needless `await img.toFile('output.png');` stuck in there before the resize.

most svgs seem to work fine, [here](https://upload.wikimedia.org/wikipedia/commons/1/1a/SVG_example_markup_grid.svg) is another that causes it. 

Do you have any recommendations?  I really appreciate your work.
cheers

```
  System:
    OS: Linux 4.9 Alpine Linux
    CPU: (6) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 122.00 MB / 1.95 GB
    Container: Yes
    Shell: 1.28.4 - /bin/ash
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Utilities:
    Git: 2.18.1 - /usr/bin/git
  Languages:
    Bash: 4.4.19 - /bin/bash
```

**Comment by lovell** [comment]
Hello, thanks for the report. Is this using the latest version? Do you experience this only on musl-based Linux, i.e. is a glibc-based Linux such as Ubuntu OK?

**Comment by spencermountain** [comment]
thanks Lovell, I'll try it out on Ubuntu tonight.

**Comment by spencermountain** [comment]
this works on Ubuntu! 
I'll close this, and use a less-weird docker image.
cheers
🙏
