### ISSUE TITLE
Anyone using sharp with Cordova for iOS?

### ISSUE THREAD

**Issue by p3v9d5ui** [lovell/sharp#1659]
I've tried to add this to my Cordova project, but when I build for iOS, I get several errors, including the following. Has anyone used this successfully in a Cordova/iOS project?

WARNING in ./node_modules/sharp/lib/libvips.js
51:22-69 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/sharp/lib/libvips.js
 @ ./node_modules/sharp/lib/constructor.js
 @ ./node_modules/sharp/lib/index.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/pages/LeadCapture.vue
 @ ./src/components/pages/LeadCapture.vue
 @ ./src/router.js
 @ ./src/main.js

WARNING in ./node_modules/sharp/lib/libvips.js
52:23-70 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/sharp/lib/libvips.js
 @ ./node_modules/sharp/lib/constructor.js
 @ ./node_modules/sharp/lib/index.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/pages/LeadCapture.vue
 @ ./src/components/pages/LeadCapture.vue
 @ ./src/router.js
 @ ./src/main.js

ERROR in ./node_modules/detect-libc/lib/detect-libc.js
Module not found: Error: Can't resolve 'child_process' in '/Users/kristiankauper/dev/hileadzz_app/node_modules/detect-libc/lib'
 @ ./node_modules/detect-libc/lib/detect-libc.js 4:16-40
 @ ./node_modules/sharp/lib/platform.js
 @ ./node_modules/sharp/lib/libvips.js
 @ ./node_modules/sharp/lib/constructor.js
 @ ./node_modules/sharp/lib/index.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/pages/LeadCapture.vue
 @ ./src/components/pages/LeadCapture.vue
 @ ./src/router.js
 @ ./src/main.js

ERROR in ./node_modules/sharp/lib/libvips.js
Module not found: Error: Can't resolve 'child_process' in '/Users/kristiankauper/dev/hileadzz_app/node_modules/sharp/lib'
 @ ./node_modules/sharp/lib/libvips.js 6:18-42
 @ ./node_modules/sharp/lib/constructor.js
 @ ./node_modules/sharp/lib/index.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/pages/LeadCapture.vue
 @ ./src/components/pages/LeadCapture.vue
 @ ./src/router.js
 @ ./src/main.js

ERROR in ./node_modules/sharp/build/Release/sharp.node
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/sharp/lib/utility.js 4:14-52
 @ ./node_modules/sharp/lib/index.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/pages/LeadCapture.vue
 @ ./src/components/pages/LeadCapture.vue
 @ ./src/router.js
 @ ./src/main.js

**Comment by aeirola** [comment]
The main documentation states that the library only supports running in Node.js, this means that it is not possible to run sharp in browser or mobile application environments. This limitation comes from the library being built on top of the libvips C binary library, which doesn't provide builds for web browser or mobile application runtime environments. I guess it would be technically possible to compile the libraries to web assembly, but that seems infeasible.

As an alternative, https://github.com/oliver-moran/jimp seems to be written entirely in JavasScript which would make it possible for it to work in Cordova.

**Comment by p3v9d5ui** [comment]
Yes, you're right @aeirola -- thanks!
