### ISSUE TITLE
clone() not working for streams

### ISSUE THREAD

**Issue by JulianWels** [lovell/sharp#1660]
I wanted to create two transform streams out of one, so I did the following:

```js
const baseTransform = sharp().removeAlpha().resize(400, 400)

const transform1 = baseTransform.clone().toFormat('png')
const transform2 = baseTransform.clone().toFormat('webp')
```
Sadly, this is the output I got

```
.../node_modules/sharp/lib/input.js:129
    callback(new Error('Unexpected data on Writable Stream'));
             ^
Error: Unexpected data on Writable Stream
    at Sharp._write (.../node_modules/sharp/lib/input.js:129:14)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Sharp.Writable.write (_stream_writable.js:294:11)
    at ReadStream.ondata (_stream_readable.js:666:20)
    at ReadStream.emit (events.js:182:13)
    at ReadStream.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at ReadStream.Readable.push (_stream_readable.js:219:10)
    at fs.read (internal/fs/streams.js:196:12)
    at FSReqCallback.wrapper [as oncomplete] (fs.js:478:5)

(sharp:1361): GLib-CRITICAL **: 13:06:33.398: g_hash_table_lookup: assertion 'hash_table != NULL' failed
```

So, with a bit of try and error I figured out that `clone()` is producing the error and I came up with this workaround:
```js
const baseTransform = () => sharp().removeAlpha().resize(400, 400)

const transform1 = baseTransform().toFormat('png')
const transform2 = baseTransform().toFormat('webp')
```

So I assume `clone()` only works on sharp instances with input-files or -buffers but not on streams.

If this is not a bug, then maybe this limitation should be noted in the docs and this would turn into a feature request for some sort of copy-constructor :)

**Comment by lovell** [comment]
Hi, `clone()` is intended for working with Streams. Your code samples don't show the full picture around how data is being piped in and out, but I'd guess that you should be piping data into `baseTransform`.

There's an example in the unit tests that might help:

https://github.com/lovell/sharp/blob/af7caa7b2529cb01355ae260ef9376212b3fe741/test/unit/clone.js#L56-L61

**Comment by JulianWels** [comment]
Thanks for the quick reply!

I think I understood my mistake now. I thought that I could use one (cloned) sharp instance as often as I want to when used inside of a stream pipeline. That it would just take an input, perform the transformation and send it to the next pipe, like this:

```js
const ws1 = fs.createWriteStream('test/output0.png')
const ws2 = fs.createWriteStream('test/output1.png')

const tf = sharp().rotate(90); 
const tf1 = tf.clone().resize(320, 240); 
const tf2 = tf.clone().resize(320, 240); 

// this works fine
fs.createReadStream('test/input0.png').pipe(tf1).pipe(ws1)
// the following won't work
fs.createReadStream('test/input1.png').pipe(tf2).pipe(ws2)
```
I think this cleared things up for me (so feel free to close this), altough it would be nice if I could use sharp the way I tried to.
