### ISSUE TITLE
Convert channel to alpha?

### ISSUE THREAD

**Issue by avpavp** [lovell/sharp#1662]
I have a grayscale image with alpha channel.

I'm trying to modify or generate a new image that takes the original grayscale data and uses it as alpha.  I want the black in my original img to be transparent and white to be opaque, and everything in between.

I know I can extract the alpha (I presume?) by:

```
var img = sharp("image.png")

// Extract the grayscale channel?
var gray = img.extractChannel(0)

// Now how do I use this as alpha?
```

but I'm not sure where to go next?

(Sorry, brand new to this sharp library!  Appreciate any help - thanks!)

**Comment by lovell** [comment]
Hello, if the `"image.png"` PNG is already single-channel without an alpha channel of its own then you can use it directly with [joinChannel](https://sharp.pixelplumbing.com/en/stable/api-channel/#joinchannel).

For an input of 1 or 3 channels to produce an output of 2 or 4 channels respectively, use something like:

```javascript
sharp('rgb.png')
  .joinChannel('greyscale.png')
  .toFile('rgba.png');
```

**Comment by avpavp** [comment]
Hi.

Thanks for your feed back.

The following code I believe achieves what I'm trying to do, but could you suggest how I could do it without writing the intermediate images?  

Thanks again


```
const sharp = require('sharp');


doStuff()

async function doStuff() {
    var img = sharp("orig.png")

    // Extract the grayscale channel (which will be my new alpha)?
    var alpha = img.extractChannel(0)
    await alpha.toColorspace("b-w")
        .toFile("newAlpha.png")
    
    // Extract my alpha, which will be the new image
    var gray = img.extractChannel(1)
    await gray.toColorspace("b-w")
        .toFile("newGray.png")
    
    sharp('newGray.png')
    .joinChannel('newAlpha.png')
    .toFile('good.png');
    
    }

```

**Comment by lovell** [comment]
Thanks for the update, glad you got it working. Intermediate images will be required for this scenario.
