### ISSUE TITLE
Support PNG input with >8MB of XMP metadata

### ISSUE THREAD

**Issue by pcvandamcb** [lovell/sharp#1664]
I'm trying to read the following PNG with sharp:
https://github.com/pcvandamcb/pcvandamcb.github.io/raw/master/1200989.png

Which is giving this error in sharp:
`Error: Input file has corrupt header:`

Now obviously there is something off with this PNG that my users are trying to have processed, but I've tried several other libraries for reading PNG's and they have no problem parsing the file, so I wonder if there is a way for sharp to ignore/discard headers for example. My current solution is to read it with another library and stream it to sharp, but this is making the process unnecessarily slow.

**Comment by jcupitt** [comment]
It seems libpng will refuse to open images with a metadata chunk larger than 8mb. This PNG has an XMP chunk of just over 20mb (!!!).

http://www.libpng.org/pub/png/libpng-manual.txt

```
Libpng imposes a limit of 8 Megabytes (8,000,000 bytes) on the amount of
memory that any chunk other than IDAT can occupy, originally or when
decompressed (prior to libpng-1.6.32 the limit was only applied to compressed
chunks after decompression). You can change this limit with

   png_set_chunk_malloc_max(png_ptr, user_chunk_malloc_max);
```

I disabled this check and your image loads now.

**Comment by pcvandamcb** [comment]
Thanks! No idea how they get those XMP chunks in there. It seems to have been saved by Photoshop and other than that it is a valid PNG.

**Comment by lovell** [comment]
sharp v0.23.0 / libvips v8.8.1 is now available.
