### ISSUE TITLE
Changing the quality or density of a png image does not seem to reduce its size.

### ISSUE THREAD

**Issue by wpitallo** [lovell/sharp#1672]
Changing the quality or density of a png image does not seem to reduce its size.

**Comment by lovell** [comment]
If you didn't see it, documentation for PNG output is at https://sharp.pixelplumbing.com/en/stable/api-output/#png - please note that some features require a custom installation of libvips.

Are you able to provide a standalone code sample that demonstrates this question?

**Comment by wpitallo** [comment]
Hi, thanks for the help,

Have a look at this: https://codesandbox.io/s/yqqqow853z

If you download the image you will see that they are the same size even when the quality is changed

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/en/stable/api-output/#png

> `options.quality` use the lowest number of colours needed to achieve given quality, **requires libvips compiled with support for libimagequant**

**Comment by wpitallo** [comment]
Ok great thanks, so I guess there is no cross platform out the box (node.js) way to get that working then?
