### ISSUE TITLE
flatten after composite doesn't flatten

### ISSUE THREAD

**Issue by aeirola** [lovell/sharp#1677]
```bash
$ npx envinfo --binaries --languages --system --utilities

  System:
    OS: macOS Mojave 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Memory: 3.25 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.14.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 10.14. - /usr/bin/gcc
    Git: 2.21.0 - /usr/local/bin/git
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 1.8.0_202 - /usr/bin/javac
    Perl: 5.18.2 - /usr/bin/perl
    PHP: 7.1.23 - /usr/bin/php
    Python: 2.7.10 - /usr/bin/python
    Ruby: 2.3.7p456 - /usr/bin/ruby
```

Chaining a call to `flatten` after a call to `composite` doesn't seem to flatten the composited image.

The following code draws a gray background, and cuts out a smaller square from it, and flattens it onto a black background. 

```javascript
const sharp = require("sharp");

const square = sharp(
  Buffer.from(
    '<svg viewBox="0 0 100 100"><rect width="100" height="100" fill="#888" /></svg>',
    "utf-8"
  )
);

const circle = sharp(
  Buffer.from(
    '<svg viewBox="0 0 100 100"><rect x="25" y="25" width="50" height="50" /></svg>',
    "utf-8"
  )
);

circle.toBuffer().then(circleBuffer =>
  square
    .composite([{ input: circleBuffer, blend: "dest-in" }])
    .flatten()
    .toFile("./test.png")
);
```

I would expect the result to be a gray square on a black background, but the result is a gray square on a transparent background, as seen in the image below

![test](https://user-images.githubusercontent.com/1143250/56898508-deae0d80-6a99-11e9-9f1d-af76b61e0485.png)

Writing the composite result into a buffer inbetween, as in the code

```javascript
square
  .toBuffer()
  .then(squareBuffer =>
    background.composite([{ input: squareBuffer, blend: "dest-in" }]).toBuffer()
  )
  .then(compositeBuffer =>
    sharp(compositeBuffer)
      .flatten()
      .toFile("./test.png")
  );
```

produces the expeted result show in the image

![test](https://user-images.githubusercontent.com/1143250/56898487-d48c0f00-6a99-11e9-82f6-cf123fd67fd5.png)

**Comment by lovell** [comment]
Hi, as you've discovered you'll have to do this as two pipelines. There's a discussion at #241 about how a more dynamic pipeline could be constructed as a future possible enhancement.

**Comment by aeirola** [comment]
Ah, seems like I incorrectly assumed chaining operations would be possible in the API. Good to know that this is not yet implemented.
