### ISSUE TITLE
Trying to make a unique copy of images, with minor change. 

### ISSUE THREAD

**Issue by axmccx** [lovell/sharp#1678]
What are you trying to achieve?

Make unique copies of an image. I have a picture with a black border on it. I'm currently using jimp to make multiple unique copies of this image, by setting a different bit along the border to red. jimp is slow and seems to use more memory than it needs. I want to try Sharp instead, and looking to see if there's any way I can accomplish this. 

Have you searched for similar questions?

I've been reading through the documentation. Seems like most operations work on the entire image at once. 

Are you able to provide a standalone code sample that demonstrates this question? 

This is what I'm currently doing with jimp:

    async function setRedPixel(orinalPath, dupPath, index, completeMsg) {
        return await new Promise((resolve, reject) => {
            try {
                Jimp.read(orinalPath)
                .then(image => {
                    image.scan(0, index, 1, 1, function(x, y, idx) {
                            this.bitmap.data[idx] = 255;
                            image.quality(90)
                        }
                    ).write(dupPath, () => {
                        console.log(completeMsg);
                        resolve();
                    });
                })
                .catch(err => { reject(err) });
            } catch (err) { reject(err) }
        });
    }

Are you able to provide a sample image that helps explain the question?

Example of a copy made by jimp. 
![image](https://user-images.githubusercontent.com/3931007/56910165-e1980680-6a77-11e9-9d32-b0abdd59cbe0.png)

**Comment by axmccx** [comment]
I figured it out! And boy is Sharp fast. I ended up using the composite function, and a red 1x1 png. This is now my function:

	async function setRedPixel(orinalPath, dupPath, index, completeMsg) {
		return sharp(orinalPath)
			.composite([{ input: 'misc/redDot.png', blend: 'over', top: index, left: 0 }])
			.toFile(dupPath)
			.then( () => { 
				console.log(completeMsg)
				resolve();
			})
			.catch(err => { 
				console.log(err)
			});
	}

**Comment by lovell** [comment]
Great, glad you worked it out, this would be my suggested approach also.
