### ISSUE TITLE
libvips wrong installation path

### ISSUE THREAD

**Issue by safead** [lovell/sharp#1679]
Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-win32-x64.tar.gz

No library at the path provided

**Comment by lovell** [comment]
What is the output of running `npm install --verbose sharp`?

What is the output of running `npx envinfo --binaries --languages --system --utilities`?

Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime?

**Comment by safead** [comment]
I have downloaded the libvips manually and successfully installed sharp. But after the compilation got these errors:

WARNING in C:/_dev/_trinity/reface.io/node_modules/sharp/lib/libvips.js 51:22-69
Critical dependency: the request of a dependency is an expression
 @ C:/_dev/_trinity/reface.io/node_modules/sharp/lib/constructor.js
 @ C:/_dev/_trinity/reface.io/node_modules/sharp/lib/index.js
 @ ../common/components/WebRTCCapture/WebRTCCapture.js
 @ ../common/components/WebRTCCapture/index.js
 @ ../common/components sync \.\/.*\/index\.js$
 @ ../common/components/index.js
 @ ../common/containers/App/index.js
 @ .
 @ multi .

WARNING in C:/_dev/_trinity/reface.io/node_modules/sharp/lib/libvips.js 52:23-70
Critical dependency: the request of a dependency is an expression
 @ C:/_dev/_trinity/reface.io/node_modules/sharp/lib/constructor.js
 @ C:/_dev/_trinity/reface.io/node_modules/sharp/lib/index.js
 @ ../common/components/WebRTCCapture/WebRTCCapture.js
 @ ../common/components/WebRTCCapture/index.js
 @ ../common/components sync \.\/.*\/index\.js$
 @ ../common/components/index.js
 @ ../common/containers/App/index.js
 @ .
 @ multi .

ERROR in C:/_dev/_trinity/reface.io/node_modules/detect-libc/lib/detect-libc.js
Module not found: Error: Can't resolve 'child_process' in 'C:\_dev\_trinity\reface.io\node_modules\detect-libc\lib'
 @ C:/_dev/_trinity/reface.io/node_modules/detect-libc/lib/detect-libc.js 4:16-40
 @ C:/_dev/_trinity/reface.io/node_modules/sharp/lib/platform.js
 @ C:/_dev/_trinity/reface.io/node_modules/sharp/lib/libvips.js
 @ C:/_dev/_trinity/reface.io/node_modules/sharp/lib/constructor.js
 @ C:/_dev/_trinity/reface.io/node_modules/sharp/lib/index.js
 @ ../common/components/WebRTCCapture/WebRTCCapture.js
 @ ../common/components/WebRTCCapture/index.js
 @ ../common/components sync \.\/.*\/index\.js$
 @ ../common/components/index.js
 @ ../common/containers/App/index.js
 @ .
 @ multi .

ERROR in C:/_dev/_trinity/reface.io/node_modules/sharp/lib/libvips.js
Module not found: Error: Can't resolve 'child_process' in 'C:\_dev\_trinity\reface.io\node_modules\sharp\lib'
 @ C:/_dev/_trinity/reface.io/node_modules/sharp/lib/libvips.js 6:18-42
 @ C:/_dev/_trinity/reface.io/node_modules/sharp/lib/constructor.js
 @ C:/_dev/_trinity/reface.io/node_modules/sharp/lib/index.js
 @ ../common/components/WebRTCCapture/WebRTCCapture.js
 @ ../common/components/WebRTCCapture/index.js
 @ ../common/components sync \.\/.*\/index\.js$
 @ ../common/components/index.js
 @ ../common/containers/App/index.js
 @ .
 @ multi .

ERROR in C:/_dev/_trinity/reface.io/node_modules/detect-libc/lib/detect-libc.js
Module not found: Error: Can't resolve 'fs' in 'C:\_dev\_trinity\reface.io\node_modules\detect-libc\lib'
 @ C:/_dev/_trinity/reface.io/node_modules/detect-libc/lib/detect-libc.js 5:18-31
 @ C:/_dev/_trinity/reface.io/node_modules/sharp/lib/platform.js
 @ C:/_dev/_trinity/reface.io/node_modules/sharp/lib/libvips.js
 @ C:/_dev/_trinity/reface.io/node_modules/sharp/lib/constructor.js
 @ C:/_dev/_trinity/reface.io/node_modules/sharp/lib/index.js
 @ ../common/components/WebRTCCapture/WebRTCCapture.js
 @ ../common/components/WebRTCCapture/index.js
 @ ../common/components sync \.\/.*\/index\.js$
 @ ../common/components/index.js
 @ ../common/containers/App/index.js
 @ .
 @ multi .

ERROR in C:/_dev/_trinity/reface.io/node_modules/sharp/lib/libvips.js
Module not found: Error: Can't resolve 'fs' in 'C:\_dev\_trinity\reface.io\node_modules\sharp\lib'
 @ C:/_dev/_trinity/reface.io/node_modules/sharp/lib/libvips.js 3:11-24
 @ C:/_dev/_trinity/reface.io/node_modules/sharp/lib/constructor.js
 @ C:/_dev/_trinity/reface.io/node_modules/sharp/lib/index.js
 @ ../common/components/WebRTCCapture/WebRTCCapture.js
 @ ../common/components/WebRTCCapture/index.js
 @ ../common/components sync \.\/.*\/index\.js$
 @ ../common/components/index.js
 @ ../common/containers/App/index.js
 @ .
 @ multi .

ERROR in C:/_dev/_trinity/reface.io/node_modules/sharp/build/Release/sharp.node 1:2
Module parse failed: Unexpected character '?' (1:2)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ C:/_dev/_trinity/reface.io/node_modules/sharp/lib/utility.js 4:14-52
 @ C:/_dev/_trinity/reface.io/node_modules/sharp/lib/index.js
 @ ../common/components/WebRTCCapture/WebRTCCapture.js
 @ ../common/components/WebRTCCapture/index.js
 @ ../common/components sync \.\/.*\/index\.js$
 @ ../common/components/index.js
 @ ../common/containers/App/index.js
 @ .
 @ multi .
i ?wdm?: Failed to compile.


libvips-8.7.4-win32-x64.tar.gz
sharp 0.22.1
OS: Windows
NPM: 6.9.0
Node 10.0.0

**Comment by safead** [comment]
npx envinfo --binaries --languages --system --utilities

C:\Users\Shadow\AppData\Roaming\npm-cache\_npx\5736\node_modules\envinfo\dist\cli.js

  System:
    OS: Windows 7
    CPU: (4) x64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
    Memory: 3.53 GB / 9.77 GB
  Binaries:
    Node: 10.0.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    PHP: 7.1.8 - C:\_www\usr\local\php5\php.EXE
    Python: 3.6.3 - C:\Users\Shadow\AppData\Local\Programs\Python\Python36\python.EXE

**Comment by lovell** [comment]
These look like webpack errors.

sharp is a native module that will not work in a browser. If you're using webpack to bundle code for use with Node.js then add sharp to its [externals](https://webpack.js.org/configuration/externals/) config.

**Comment by safead** [comment]
Yes, I wanted to integrate this lib in React app. Sadly it is not possible...
