### ISSUE TITLE
Detect transparency of a pixel

### ISSUE THREAD

**Issue by soosgyul** [lovell/sharp#1684]
Hi!
Ultimate goal is detect the background colour of an image and on resize use this colour as background. 
I do this by looking at the 4 top and 4 bottom rows, and first 4 and last 4 columns of the image and I look at the pixels individually and count the colours. If there is only one main colour, we're good. The problem comes when the edge of the image has other colours, gradients, or it is transparent. If we can't determine a clear winner, we just return white. 
Currently I'm stuck at getting the transparency value for these pixels.

The metadata.hasAlpha is too vague (just tells me wether is set or not, doesn't give values) and the stats.isOpaque gives me false, on http://www.stickpng.com/img/icons-logos-emojis/tech-companies/linux-logo

This is how I get the colour of each pixel:

> const getPixelColor = (data, channels, width, col, row) => {
    const offset = channels * (width * row + col);
    const red = data[offset];
    const green = data[offset + 1];
    const blue = data[offset + 2];
    return {red, green, blue};
};

How would you proceed to detect the transparency of these images?

**Comment by lovell** [comment]
Did you see [raw](https://sharp.pixelplumbing.com/en/stable/api-output/#raw)? This will return uncompressed raw RGBA pixel data for a PNG input containing an alpha channel.

**Comment by soosgyul** [comment]
Yes, I'm taking the individual pixel colours with that. So I just get the alpha channel same way as I get the rgb channels? offset+ 3?

**Comment by soosgyul** [comment]
Let me answer it. So yes, I check first and if there are 4 channels, I get the offset + 3 to get the alpha value.

**Comment by J-Cake** [comment]
what if the input format is a JPG file and transparent pixels aren't supported?
