### ISSUE TITLE
Enhancement: add skip-blanks option to tile generation

### ISSUE THREAD

**Issue by RaboliotTheGrey** [lovell/sharp#1685]
Hi,

With the upcoming version of libvips dzsave will support to skip blank tile during the tile generation.

I was thinking add this option :
```
tile.skipBlanks [Number] threshold to skip tile generation, a value  0 - 255 for 8-bit images or 0 - 65535 for 16-bit images (optional, default -1)
```
I will try make an PR  as soon as I can.
(Here is the upstream issue : https://github.com/libvips/libvips/issues/1185)

**Comment by lovell** [comment]
sharp v0.23.0 / libvips v8.8.1 now available. Thanks for the PR!
