### ISSUE TITLE
 I can remove background

### ISSUE THREAD

**Issue by GlauberF** [lovell/sharp#1686]
I can remove background ?

**Comment by lovell** [comment]
What are you trying to achieve?

Have you searched for similar questions?

Are you able to provide a standalone code sample that demonstrates this question?

Are you able to provide a sample image that helps explain the question?

**Comment by GlauberF** [comment]
My question, I would like to try to remove the background via code, same as the site https://remove.bg

**Comment by lovell** [comment]
Those services will typically use machine learning techniques to segment images, so no, sharp is the wrong tool for this job.
