### ISSUE TITLE
Difference between contain and inside

### ISSUE THREAD

**Issue by rightaway** [lovell/sharp#1688]
What is the difference between a `fit` value of `contain` ("Embed within both provided dimensions") and `inside` ("Preserving aspect ratio, resize the image to be as large as possible while ensuring its dimensions are less than or equal to both those specified")? The descriptions seems similar, could you please give an example of where it would lead to different results and when you would use one and not the other?

I can see how to set a background color when using `contain` (docs say use `options.background` to set "background colour when using a fit of contain, parsed by the color module, defaults to black without transparency"), but it doesn't say anything for `inside`, how could I set transparent background when using `inside` rather than `contain`?

**Comment by lovell** [comment]
Both of these `fit` values require both a width and height.

The output image for `contain` will always be exactly the dimensions you specify, using `background` for the additional pixels.

The output image for `inside` will have one dimension the same as you specify, but the other dimension will be smaller than specified (unless you happen to have chosen dimensions at the same aspect ratio as the input).

There are quite a few examples in the unit tests:

https://github.com/lovell/sharp/blob/master/test/unit/resize.js
https://github.com/lovell/sharp/blob/master/test/unit/resize-contain.js

**Comment by rightaway** [comment]
Thank you. When using `contain` and I want a transparent background without any color can I just add `background: { alpha: 0 }`?

When using the same image/dimensions, will using `contain` result in slightly larger file size than using `inside`, because `inside` has to add a background (even though it's transparent and has no color)?

**Comment by lovell** [comment]
Yes, and it depends on format/quality so you'll need to experiment.

**Comment by lovell** [comment]
Instances maintain state and processing is lazy so prefer to create new instances where possible.

**Comment by lovell** [comment]
(GitHub's ability to handle timezones is totally broken right now - these comments are appearing out of chronological order.)

**Comment by rightaway** [comment]
When I use `background: { alpha: 0 }` there's an error `Unable to parse color from object`. If I want transparent background couldn't it be changed to not require a color?

**Comment by lovell** [comment]
RGBA pixels still need a colour, even when the A is fully-transparent.

**Comment by ssnangua** [comment]
Is that right?
![Snipaste_2022-09-01_05-33-35](https://user-images.githubusercontent.com/66629730/187789384-951a8348-a8cf-4d8b-9f34-145f52d35c14.jpg)

**Comment by rightaway** [comment]
@lovell That picture from @ssnangua could be added to documentation?

**Comment by lovell** [comment]
@rightaway Please see https://github.com/lovell/sharp/pull/3350
