### ISSUE TITLE
The module ... was compiled against a different Node.js version

### ISSUE THREAD

**Issue by ant-i-c-s** [lovell/sharp#1689]
I'm using Node version `12.1.0` and trying to compile for electron. I have the error message 

```
The module '[project path]\node_modules\sharp\build\Release\sharp.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

I noticed that version 70 isn't listed on the [releases page](https://nodejs.org/en/download/releases/). I looked at the releases for this package and the electron release is titled `sharp-v0.22.1-electron-v70-win32-x64.tar.gz` but the non electron release is titled `sharp-v0.22.1-node-v72-win32-x64.tar.gz`.

**Comment by lovell** [comment]
Did you use [electron-rebuild](https://github.com/electron/electron-rebuild)?

**Comment by ant-i-c-s** [comment]
that did it!

**Comment by Edijae** [comment]
I'm not using electron. I need sharp for cropping images in my node js app. I had installed sharp as a local module and it was working fine but when i removed local modules in favor of global modules, i encountered the error below 

```
0|index  | Something went wrong installing the "sharp" module
0|index  | The module '/home/ubuntu/.nvm/versions/node/v12.2.0/lib/node_modules/sharp/build/Release/sharp.node'
0|index  | was compiled against a different Node.js version using
0|index  | NODE_MODULE_VERSION 72. This version of Node.js requires
0|index  | NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
0|index  | the module (for instance, using `npm rebuild` or `npm install`).
0|index  | - Ensure the version of Node.js used at install time matches that used at runtime
0|index  | - Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
0|index  | - Search for this error at https://github.com/lovell/sharp/issues
```

**Comment by jumpinvestor** [comment]
I'm running across the same thing. Node 12.2.0, latest version of Sharp. Reinstalling and rebuilding haven't had an effect. Not sure what I'm doing wrong.
