### ISSUE TITLE
Process PNG image data with sharp

### ISSUE THREAD

**Issue by hasen6** [lovell/sharp#1690]
I see that Sharp takes input as an actual file but I'm wondering if it can take for example PNG base64 image data as input? If so how would that be done? Or otherwise how can canvas.toDataURL be input into Sharp?

I did search but couldn't find this answer.

Thanks.

**Comment by lovell** [comment]
https://stackoverflow.com/questions/5867534/how-to-save-canvas-data-to-file/5971674#5971674
```javascript
// strip off the data: url prefix to get just the base64-encoded bytes
var data = img.replace(/^data:image\/\w+;base64,/, "");
```

**Comment by lovell** [comment]
(GitHub's ability to handle timezones is totally broken right now - these comments are appearing out of chronological order.)

**Comment by hasen6** [comment]
I tried this `test = test.replace(/^data:image\/\w+;base64,/, "");` as you suggested and it works now...but it still throws the deprecated error?

_DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead._

**Comment by hasen6** [comment]
Weird, your comment and my comment seem to have disappeared and all the time indexes on the previous comments are in the future..is it a problem my end or does github have a problem suddenly? I already replied to the comment that disappeared but my comment didn't appear either.

**Comment by lovell** [comment]
https://twitter.com/githubstatus/status/1126171459255185414

**Comment by hasen6** [comment]
Weird so there really was a problem. Anyway it seems to be ok now. So the code works now but still throws the buffer deprecated error as in my comment above - any ideas?

**Comment by lovell** [comment]
```javascript
sharp(Buffer.from(base64EncodedString, 'base64'))...
```

**Comment by hasen6** [comment]
Ok that fixed it. That was what I tried previously from the thread you suggested at the beginning but didn't try it after removing the url prefix from the canvas data. Thanks for your help and btw **Sharp** is just awesome. :)
