### ISSUE TITLE
failOnError: false with streams causes Input file is missing error

### ISSUE THREAD

**Issue by timothyallan** [lovell/sharp#1691]
What is the output of running `npx envinfo --binaries --languages --system --utilities`?
```
System:
    OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (6) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 231.25 MB / 1.95 GB
    Container: Yes
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 11.10.1 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  Utilities:
    Make: 4.1 - /usr/bin/make
    GCC: 6.3.0 - /usr/bin/gcc
    Git: 2.11.0 - /usr/bin/git
  Languages:
    Bash: 4.4.12 - /bin/bash
    Perl: 5.24.1 - /usr/bin/perl
    Python: 2.7.13 - /usr/bin/python
```
What are the steps to reproduce?

Using ` {failOnError : false}` constantly gives an `Input file is missing` error. Remove that option and everything works.
```
const fileName = __dirname + '/input.jpg';
const saver = sharp({ failOnError: false }).toFile(__dirname + '/output.jpg', function(err) {
  console.log('err', err);
  });
fs.createReadStream(fileName).pipe(saver);
```

What is the expected behaviour?

See output.jpg created.

Are you able to provide a sample image that helps explain the problem?

Any image seems to work.

**Comment by lovell** [comment]
I think this is related to #1579 - certain input options have previously (and appear to continue to) prevent sharp accepting Stream-based input.

As a workaround, please can you try `sharp(null, { failOnError: false })` to force sharp to expect Stream-based input.

**Comment by timothyallan** [comment]
Perfect! In order to stop TypeScript from yelling at you, you've got to use `sharp(undefined, { failOnError: false })`, but the end result is the same.

**Comment by lovell** [comment]
Test and fix in commit 6289968 to be included in v0.23.0. Thanks for reporting this.

**Comment by lovell** [comment]
sharp v0.23.0 is now available.

**Comment by mattcwebster** [comment]
Im still experiencing this error in latest version of Sharp with a Samsung S22, and even when using failOn: 'none'

[Error: VipsJpeg: Invalid SOS parameters for sequential JPEG
]
