### ISSUE TITLE
Resize and composite

### ISSUE THREAD

**Issue by soosgyul** [lovell/sharp#1694]
Hi.
I try to resize an image to a particular size. I need to remove the transparency from the image, and just replace it with the white colour. I tried to remove the alpha channel, but that's just replaces it with black. 
So the steps I'm taking are:
 
1. Create and await the resized image.
2. Create a white image.
3. Composite the resized image over the white one.

```node
    const resizedImage = await sharp(image)
        .resize({
            width,
            height,
            fit: "contain",
            background,
        })
        .toBuffer();

    const finalImage = await sharp({
        create: {
            width,
            height,
            channels: 4,
            background,
        },
    })
        .composite([{ input: resizedImage }])
        .toBuffer();
```

However, this gives me an error "UnhandledPromiseRejectionWarning: Error: Input buffer contains unsupported image format" and if I remove the .toBuffer() from the resized image, the composite part complaining about me not providing width and height, and stuff for the raw image... What am I missing?

**Comment by lovell** [comment]
Did you see the [flatten](https://sharp.pixelplumbing.com/en/stable/api-operation/#flatten) operation?

**Comment by soosgyul** [comment]
Dammit, I could swear that I've read the whole documentation back and forth a few hundred times. I'll try this later and let you know if it worked.
