### ISSUE TITLE
How to skip images unsupported format

### ISSUE THREAD

**Issue by stefanomonteiro** [lovell/sharp#1695]
Hi

I am getting the **Input file contains unsupported image format** Error. How can I skip images that supposedly are not the correct format?

**Comment by lovell** [comment]
You'll probably need to add some error handling to your code.

You've not provided any sample code here but `toFile()` or `toBuffer()` will either reject or pass an error to the callback depending on the context in which they are used.

**Comment by stefanomonteiro** [comment]
Thanks

I used node `path.extname(file)` and conditioned the code to run if the file is of extension I want to work with.

```
fs.readdir(path, function(err, files) {
    files.forEach(function(file) {
      if (path.extname(file) === ".jpg" || path.extname(file) === ".png") {
          ////CODE
      }
```
