### ISSUE TITLE
CircleCi issue

### ISSUE THREAD

**Issue by przemyslawpluta** [lovell/sharp#1699]
Are there specific installation requirements to use sharp on circleci? It does not look like it's compiled / downloaded properly ... all tests succeed locally but some which rely on sharp fail on circleci ...  

<img width="973" alt="ref" src="https://user-images.githubusercontent.com/221250/57723605-e2888500-7680-11e9-9fb0-5331878511a8.png">

https://circleci.com/gh/przemyslawpluta/removd/60

**Comment by lovell** [comment]
Hi, on that CI run I see a bunch of test failures with error messages unrelated to sharp. Am I missing something?

**Comment by przemyslawpluta** [comment]
Just tried to rerun the job but I'm getting below ...

<img width="1367" alt="ref" src="https://user-images.githubusercontent.com/221250/57729613-8298db00-768e-11e9-935d-49bd0d0c6bfc.png">

**Comment by przemyslawpluta** [comment]
Added `npm rebuild` after package installation which seems to force sharp into correct state ... half way there still have some issues with few tests where sharp is used. 

<img width="924" alt="rebuild" src="https://user-images.githubusercontent.com/221250/57730089-a0b30b00-768f-11e9-96ad-f1d8d678cf72.png">

**Comment by przemyslawpluta** [comment]
Looks like issue with small VM. Moved to streams which helped.
