### ISSUE TITLE
Get metadata from stream and upload stream to S3

### ISSUE THREAD

**Issue by jardakotesovec** [lovell/sharp#170]
Is sharp suitable for this use case? We don't want to modify image, just get metadata before we upload it to S3. Image is ReadableStream coming from network. And we don't want to load whole image to memory nor write it to disk. 

Is that possible with sharp and how could we approach it?

Thank you for any feedback! Very nice library!

**Comment by lovell** [comment]
Hi Jarda, the existing `metadata` method accepts data piped in, so what you describe should work, perhaps something like:

```javascript
sourceStream.pipe(s3stream);
sourceStream.pipe(sharp().metadata(function(err, metadata) {
  // do something with metadata
}));
```

**Comment by jardakotesovec** [comment]
Thanks a lot for hint! I wonder how it works behind the scenes, its very nice that `metadata` function can get metadata from stream.

Piping image to sharp and S3 would not work, because S3 use `readable` event which would not work with pipe together according to this [issue](https://github.com/joyent/node/issues/8568).

But serial approach seems to work well so far:

```
  var metadataTransformer = sharp().metadata(function (err, m){
    console.log(m);
  });

  var params = {Bucket: 'data', Key: filename , Body: image.pipe(metadataTransformer)};

  s3.upload(params, function(err, data) {
      if (err) {
        console.log(err)
      }

      console.log(data)
   });

```
