### ISSUE TITLE
Compositing API is a bit weird

### ISSUE THREAD

**Issue by sharpobject** [lovell/sharp#1700]
Hello,

If I want to composite a bunch of images, it seems like I need to have 1 promise and the rest buffers. It would be sweet if the API worked with all promises or all buffers.

**Comment by sharpobject** [comment]
I have this sort of code in my script as a result of this weirdness:
```js
      if (firstimage === undefined) {
        firstimage = thunk;
      } else {
        var layer = await thunk.toBuffer({resolveWithObject: true});
        layers.push({input: layer.data})
      }
```

**Comment by lovell** [comment]
Hello, the `composite()` operation does not accept Promises for its `input` properties.

It does accept Buffers, Strings (representing filesystem paths) and Objects describing a blank image.

https://sharp.pixelplumbing.com/en/stable/api-composite/

Are you able to share a more complete code example?

**Comment by sharpobject** [comment]
Sure. This is a script that takes any number of images that define where to put other images in that image, an equal number of folders full of many images each, and a mask to put on top of all that.

For example, if you run it with these files:
images/buf1.png
images/buf2.png
images/buf3.png
images/in1/a.jpg
images/in1/b.jpg
images/in2/hello.jpg
images/in2/world.jpg
images/in3/hewwo.jpg
images/in3/owo.jpg
images/mask.png

you should end up with one file that is (a.jpg in the position indicated by buf1.png + hello.jpg in the position indicated by buf2.png + hewwo.jpg in the position indicated by buf3.png + mask.png) and another file that is (b.jpg in the position indicated by buf1.png + world.jpg in the position indicated by buf2.png + owo.jpg in the position indicated by buf3.png + mask.png).

The composite API requires that the first thing I want to composite should be a different type from all the others. This is weird, and the code I posted above exists to work around it.

```js
const sharp = require('sharp');
const Promise = require("bluebird");
const fs = require('fs');

Promise.promisifyAll(fs);

var rootdir = 'images';
var toplayername;

async function main() {
  try {
  if (process.argv.length > 2) {
    rootdir = process.argv[2];
  }
  toplayername = rootdir + "/mask.png";
  var filenames = await fs.readdirAsync(rootdir);
  console.log(filenames)
  var srclists = [];
  var infos = [];
  var cutout = await sharp(toplayername)
    .toBuffer({ resolveWithObject: true});
  for(var i=1; ; i++) {
    var bufname = "buf" + i + ".png";
    var dirname = "in" + i;
    if ((!filenames.includes(bufname)) || (!filenames.includes(dirname))) {
      break;
    }
    srclists.push(await fs.readdirAsync(rootdir + "/" + dirname))
    infos.push((await sharp(rootdir + "/" + bufname)
      .trim()
      .toBuffer({ resolveWithObject: true })).info);
  }
  console.log(srclists);
  var N = 1e99;
  for (var i=0; i<srclists.length; i++)
    N = Math.min(N, srclists[i].length);
  for (var i=0; i<N; i++) {
    var firstimage = undefined;
    var layers = [];
    for (var j=0; j<srclists.length; j++) {
      var info = infos[j];
      var top = -info.trimOffsetTop;
      var left = -info.trimOffsetLeft;
      var right = cutout.info.width - info.width + info.trimOffsetLeft;
      var bottom = cutout.info.height - info.height + info.trimOffsetTop;
      var thunk = sharp(rootdir + "/" + "in" + (j+1) + "/" + srclists[j][i])
                    .png()
                    .ensureAlpha()
                    .resize({width: info.width, height: info.height, fit: "outside"})
                    .resize({width: info.width, height: info.height, fit: "cover"})
                    .extend({
                      top: top,
                      left: left,
                      right: right,
                      bottom: bottom,
                      background: {r: 0, g: 0, b: 0, alpha: 0}})
      if (firstimage === undefined) {
        console.log("set thunk")
        firstimage = thunk;
      } else {
        console.log("didn't set thunk")
        var layer = await thunk.toBuffer({resolveWithObject: true});
        console.log(layer.info);
        layers.push({input: layer.data})
      }
    }
    console.log(cutout.info);
    layers.push({input: cutout.data});
    console.log(layers)
    await firstimage.composite(layers)
            .toFile(rootdir + "/out/" + i + ".png");
  }
  }
  catch(err) {
    console.log(err)
  }
  finally {}
}

main();
```

**Comment by lovell** [comment]
Thanks, this makes things clearer, `firstimage` itself is an instance of `sharp` rather than a Promise; its `toBuffer()` method returns a Promise.

Based on the code above, you'll probably want to create a blank image to composite all the layers onto, something like:

```javascript
const { width, height } = cutout.info; // dimensions of final image
const background = { r: 0, g: 0, b: 0, alpha: 0 }; // fully-transparent
sharp({
  create: { width, height, background, channels: 4 }
})
  .composite(layers)
  ...
```

**Comment by lovell** [comment]
Hope this helped, please feel free to re-open with more details if further help is required.
