### ISSUE TITLE
Create single image tile

### ISSUE THREAD

**Issue by brenwkennedy** [lovell/sharp#1701]
I would like to create a single image tile instead of the entire tile set.

My requests adhere to the deepzoom spec as follows.

```
https://example.com/tiles/image.jpg_files/12/0_0.jpg
https://example.com/tiles/image.jpg_files/10/1_0.jpg
https://example.com/tiles/image.jpg_files/13/0_5.jpg
```

I'm using Lambda@Edge to handle these single tile requests. It would be much more performant to only generate the tile being requested in each Lambda invocation.

Unless I am missing something in the docs, I believe it is not possible to ask sharp for a specific tile. If there is a solution to this question, I would love to know! If there is not a solution, some general guidance on where to start in sharp/libvips would be greatly appreciated.

**Comment by lovell** [comment]
The [tile](https://sharp.pixelplumbing.com/en/stable/api-output/#tile) output options in sharp are a very thin wrapper around libvips' [dzsave](https://libvips.github.io/libvips/API/current/VipsForeignSave.html#vips-dzsave) operation.

**Comment by jcupitt** [comment]
I made a tiny fcgi tile server for openslide images using libvips:

https://github.com/jcupitt/tilesrv

It might be helpful.

**Comment by brenwkennedy** [comment]
Thanks for the link to tilesrv @jcupitt. Do you think a similar service can be written with sharp in node? There is a lot of reading I need to on how tiling actually works, but I have a lot of interest in creating a single tile as fast as possible, using node.

**Comment by brenwkennedy** [comment]
I've started writing a nodejs tile server that uses sharp. Thanks for the help!
https://github.com/brenwkennedy/sharptile

**Comment by kylajung** [comment]
Hi @rustyguts, I am trying to get a single image tile from a tiff file, so I was wondering if you have implemented tile reading with nodejs. Do you have any plans for sharing your work?  It would be really helpful for my project. Or can you give any general advice of how to implemented it? I was hoping to get some general idea before I digging into some n-api stuff...
