### ISSUE TITLE
PGM files cannot be read on Windows

### ISSUE THREAD

**Issue by vladh** [lovell/sharp#1705]
_What is the output of running `npx envinfo --binaries --languages --system --utilities`?_
```
npx: Installierte 1 in 2.453s

  System:
    OS: Windows 10
    CPU: (2) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 797.33 MB / 1.98 GB
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Bash: 4.4.23 - C:\Program Files\Git\usr\bin\bash.EXE
    Perl: 5.26.2 - C:\Program Files\Git\usr\bin\perl.EXE
```

_What are the steps to reproduce?_
1. `sharp('image.pgm').toFile('image.png')`
2. “Error: Input buffer contains unsupported image format”

_What is the expected behaviour?_
The PGM file is read and a PNG is output, as on e.g. macOS.

_Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?_
It's above.

_Are you able to provide a sample image that helps explain the problem?_
https://vladh.net/things/photo_0.pgm

—

On macOS I can work with PGM files just fine, but Windows throws an error while attempting to open them, for the same code and same images.

I suspect this has to do with how libvips and/or Imagemagick are compiled. Presumably on Windows somehow I don't end up having Imagemagick. Is there any way to specify that I want sharp to build libvips with support for all formats? I've tried installing Imagemagick globally without results, and I've tried installing the `-all` version of the latest libvips on Windows but am not sure how, short of copying it into the `node_modules/sharp/vendor` directory, which didn't seem to help.

Any tips would be very much appreciated, since I'm currently shipping a product to customers with this code.

Thank you so much for helping!

**Comment by lovell** [comment]
On OS X I suspect you've installed the `vips` package via Homebrew, which includes ImageMagick.

On Windows you'll need to use a custom compilation of libvips with support for ImageMagick to read PGM files.

The binaries provided by sharp are generated via https://github.com/lovell/sharp-libvips/blob/master/build/win.sh - you'd probably want to replace the use of the web-formats `vips-dev-w64-web-...` for the all-formats `vips-dev-w64-all-` zip file, which includes ImageMagick.

I can't offer any support for this, sorry, so you'll be on your own here - good luck!

**Comment by vladh** [comment]
Thank you for the help. Using your advice I've managed to create a custom build of libvips using `sharp-libvips` and publish it to a custom URL, allowing me to use the `SHARP_DIST_BASE_URL` flag to get it into my application. Everything worked out well!

**Comment by nobel6018** [comment]
Hello,
I have same problem.

`sharp('image.pgm').toFile('image.png')`

[Error: Input file contains unsupported image format]

I run on mac m1, AWS cloud9.
I used the pgm image [file](https://people.sc.fsu.edu/~jburkardt/data/pgma/pgma.html).

Could you give me any tips to help me. Thank you :)
