### ISSUE TITLE
Issue with error sharp@0.20.8 Linux

### ISSUE THREAD

**Issue by shadowdevcode** [lovell/sharp#1707]
After cloning my github repo of portfolio made with gatsby, I have latest versions of npm and node
`node -v` : 12.2.0
`npm -v` : 6.9.0
& cd in the directory, I entered `npm install` leads to error with sharp file @0.20.8 version tar.gz file. 
How do I fix it? Any suggestions?
@lovell 

![image](https://user-images.githubusercontent.com/39980643/57979546-df084b80-7a3c-11e9-850d-3eb76b31cf11.png)

**Comment by lovell** [comment]
Support for Node 12 was added in v0.22.1

https://sharp.pixelplumbing.com/en/stable/changelog/#v0221-25th-april-2019

**Comment by shadowdevcode** [comment]
Yeah, this is of not much of help to me.
As doing `npm install` will take the old sharp@version which gives me the
same problem again even clearing the .npm/_lib packages of it too.
