### ISSUE TITLE
GLib-CRITICAL **: 23:16:35.944: g_hash_table_lookup: assertion 'hash_table != NULL' failed

### ISSUE THREAD

**Issue by eyun-tv** [lovell/sharp#1709]
this picture

https://p.gu321.com/20190520232532.jpg

```


size = 16383
file = await sharp(data).resize(
            size
            size
            {withoutEnlargement:true,fit:'inside'}
        ).webp({
            quality: 75
        }).toBuffer()

```

nodejs crash with GLib-CRITICAL **: 23:16:35.944: g_hash_table_lookup: assertion 'hash_table != NULL' failed

**Comment by lovell** [comment]
Hello, the `g_hash_table_lookup: assertion 'hash_table != NULL' failed` message appears when the Node process unexpectedly dies whilst image processing is in-flight (Node doesn't wait for threads to join). This is usually a symptom of a lack of error handling elsewhere.

**Comment by lovell** [comment]
Hope this helped, please feel free to re-open with more details if further help is required.

**Comment by jlin95** [comment]
Hi, encountering this issue too. I'm using `gatsby-image` in my project, and querying for images in my page components (there are about 10 base pages, with each page having either 3 or 6 images queried).

**Comment by grantglidewell** [comment]
also having this same issue on a netlify build using gatsby, ill be filing an issue there as well

**Comment by jonearley** [comment]
Also getting this error with Netlify and gatsby-image.
