### ISSUE TITLE
setting libvip version

### ISSUE THREAD

**Issue by someotherdata** [lovell/sharp#1711]
I have a privately hosted repo of libvips, 8.6.4.

Is there a way I can use libvips 8.6.4 when I set my sharp dist base instead of the one stated in the package.json?

**Comment by lovell** [comment]
You'll either need to change the `package.json` or the URL if you're using an older version of libvips with a newer version of sharp.

Beware that if you're doing this you won't be able to rely on the prebuilt sharp binaries as they are linked against a specific version of libvips. They might appear to work but ABI inconsistencies and therefore undefined behaviour is likely.
