### ISSUE TITLE
Using with AWS Lambda 10.x appears to be broken

### ISSUE THREAD

**Issue by JonRowe** [lovell/sharp#1712]
After installing locally (On OS X) using:
```
npm install --arch=x64 --platform=linux --target=10.15.3
```

On uploading to AWS lambda, attempting to load the module with:

```
const sharp = require('sharp');
```

Causes:

```
Error: Cannot find module './constructor'
```

**Comment by wesselvdv** [comment]
I am actually running this successfully on AWS Lambda with nodejs10.x (10.15), only thing for me is that resizing doesn't seem to work.

**Comment by JonRowe** [comment]
@wesselvdv did you have to anything beyond `npm install` ? / what platform did you build it from?

**Comment by lovell** [comment]
@JonRowe Does the `node_modules/sharp/lib/constructor.js` file exist in your deployment zip file? Are you using a bundler such as webpack? Does Node 8 work?

**Comment by wesselvdv** [comment]
@JonRowe It's actually working for me, I mistakenly attributed the resize failure to sharp. I am using a Dockerfile as builder which uses `amazonlinux:2` as base. I am even running the entire lambda through Webpack (incl. Sharp).

**Comment by JonRowe** [comment]
Sorry, turns out this was user error in the install process, my build script didn't add all the files. Apologies for the waste of time!
