### ISSUE TITLE
Cannot install sharp centos with vips-8.7.2 ready installed

### ISSUE THREAD

**Issue by bachphuc** [lovell/sharp#1714]
Hi,

Thank for good library.
I'm having with install sharp on my server. 
I have libvips version 8.7.2

`vips -v` : output
vips-8.7.2-Wed Dec  5 17:37:43 UTC 2018

but when I run `npm install sharp` It's failed.

![image](https://user-images.githubusercontent.com/11581096/58187644-5eb64480-7ce1-11e9-8c6c-94fc55f752b3.png)

It's saying "Intel Architecture 32-bit systems require manual installation of libvips ". I read document and try to research and take a lot of time but I cannot install sharp success.

Can you help me about this?

Thanks

**Comment by bachphuc** [comment]
`pkg-config --modversion vips-cpp` output 8.7.2
and now it failed with other error

![image](https://user-images.githubusercontent.com/11581096/58192124-3e3eb800-7cea-11e9-857b-2c9224150030.png)

**Comment by lovell** [comment]
Hi, it looks like you're using an unsupported version of sharp (0.18.4) with an unsupported version of Node (9.2.0) so please upgrade first.
