### ISSUE TITLE
Image generation within a handlebars helper (webpack) (Error TypeError: process.exit is not a function)

### ISSUE THREAD

**Issue by cgpro** [lovell/sharp#1716]
I want to generate placeholder images within a handlebars helper. As standalone it works fine outside the Docker container (OSX). I copied the code into the container (did npm i for a fresh install to check libvips is present), works fine too, but it's not working in my handlebars helper.

**Error message**
TypeError: process.exit is not a function

**Desired behaviour**
The helper have to generate the image, without exiting the process.

**Versions:**
Node: 10.15.3
Webpack: 4.25.1
Sharp: 0.22.1
Docker: 18.09.2
Docker OS: Debian 9

**What I've done so far:**
- Added node-loader (fixed the Unexpected character '' (1:0) error)
`{
    test: /\.node$/,
    use: 'node-loader'
},`
- Added externals in my webpack.config.js (makes no difference)
`externals: {
    jquery: 'jQuery',
    sharp: 'commonjs sharp'
},`
- Tried this fix for the 'Unexpected character...' but the node-loaded solved it
https://jlongster.com/Backend-Apps-with-Webpack--Part-I#p28

**Code of my helper:**
`const fs = require('fs');
const sharp = require('sharp');

module.exports = function(options) {

    // variables
    let width = options.hash.width;
    let height = options.hash.height;
    let folder = '/var/www/src/img/content/res-images/image_';
    let outputPath = folder + width + 'x' + height + '.png';

    // svg text
    const textedSVG = new Buffer(`<svg width="${width}" height="${height}">
       <text x="${width/2}" y="${(height/2) + ((width * 0.15)/3)}" font-size="${width*0.15}" fill="#fff" text-anchor="middle" font-family="Arial">${width}x${height}</text>
    </svg>`);

    // check if image exists, otherwise create it
    try {
        if (!fs.existsSync(outputPath)) {
            sharp({
                create: {
                    width: width,
                    height: height,
                    channels: 3,
                    // channels: 4, // for transparency - change alpha to 0.x
                    background: { r: 106, g: 145, b: 206, alpha: 1 }
                }})
                .composite([{ input: textedSVG, gravity: 'center' }])
                .png()
                .toFile(folder + width + 'x' + height + '.png');
                //.on('error', err => console.log(`${err.message} from sharp`));
        }
    } catch(err) {
        console.error(err)
    }

    // not finished yet... TODO: image markup
    return options.hash.filename + ' ' + options.hash.width + ' ' + options.hash.height;

};`

**Error message in CLI/Browser-Output**
`Html Webpack Plugin:
  TypeError: process.exit is not a function
  
  - layout_termindatenbank_complete.hbs:33572 Object.
    /var/www/src/pages/layout_termindatenbank_complete.hbs:33572:11
  
  - layout_termindatenbank_complete.hbs:33809 Object../node_modules/sharp/lib/co    nstructor.js
    /var/www/src/pages/layout_termindatenbank_complete.hbs:33809:30
  
  - layout_termindatenbank_complete.hbs:21 __webpack_require__
    /var/www/src/pages/layout_termindatenbank_complete.hbs:21:30
  
  - layout_termindatenbank_complete.hbs:33823 Object../node_modules/sharp/lib/in    dex.js
    /var/www/src/pages/layout_termindatenbank_complete.hbs:33823:15
  
  - layout_termindatenbank_complete.hbs:21 __webpack_require__
    /var/www/src/pages/layout_termindatenbank_complete.hbs:21:30
  
  - layout_termindatenbank_complete.hbs:38211 Object.
    /var/www/src/pages/layout_termindatenbank_complete.hbs:38211:13
  
  - layout_termindatenbank_complete.hbs:38250 Object../src/helpers/image.js
    /var/www/src/pages/layout_termindatenbank_complete.hbs:38250:30
  
  - layout_termindatenbank_complete.hbs:21 __webpack_require__
    /var/www/src/pages/layout_termindatenbank_complete.hbs:21:30
  
  - layout_termindatenbank_complete.hbs:38546 3
    /var/www/src/pages/layout_termindatenbank_complete.hbs:38546:44
  
  - layout_termindatenbank_complete.hbs:6138 prog
    /var/www/src/pages/layout_termindatenbank_complete.hbs:6138:12
`

If I comment out 'const sharp = require('sharp');' webpack is running again.

**Comment by lovell** [comment]
My best guess would be that something in your webpack config is overriding/replacing/polyfilling Node's `process` global variable.

**Comment by cgpro** [comment]
Do you have any idea to trigger the image creation in another, eloquent way? Maybe with a "mini" express.js server? Its only for local development... I think its easier to exclude the image creation to an external service for example.

**Comment by lovell** [comment]
Perhaps use a separate build step for your images, independent of webpack/handlebars etc - good luck!
