### ISSUE TITLE
Error while trying to use composite

### ISSUE THREAD

**Issue by GunterJameda** [lovell/sharp#1717]
I'm trying to use composite like this:

```
const sharpFile = this.electronService.sharp(null, options);

const pagePhotos = page.allPhotos.map(photo => {
  return {
    input: photo.photo.sizes[0].localPath,
    top: Math.round(photo.y),
    left: Math.round(photo.x)
  };
});

console.log(pagePhotos);

const pageBuffer = sharpFile.composite(pagePhotos).toBuffer();

// localPath is something like this
// "/Users/username/Library/Application Support/projectname/projects/PKTFB45BW/photos/FKYCARH45MQ-1000.jpg"
```

I'm getting this error

```
Unhandled Promise rejection: Input buffer contains unsupported image format ; Zone: <root> ; Task: null ; Value: Error: Input buffer contains unsupported image format Error: Input buffer contains unsupported image format

Error: Input buffer contains unsupported image format
```

What am I doing wrong?

**Comment by lovell** [comment]
Hi, I might need a more complete code sample. What is `options` set to?

**Comment by GunterJameda** [comment]
Options is set to this:

```
const options: SharpOptions = {
  create:
    {
      width: Math.floor(page.width * page.zoom),
      height: Math.floor(page.height * page.zoom),
      channels: 3,
      background: ColorUtil.hex2rgb(page.backgroundColor)
    }
  };
```

**Comment by lovell** [comment]
Thanks. Is `photo.photo.sizes[0].localPath` a string? Are you able to provide an image that fails in this manner?

**Comment by GunterJameda** [comment]
Yes. As I previously said, it is a string like this:

`/Users/username/Library/Application Support/projectname/projects/PKTFB45BW/photos/FKYCARH45MQ-1000.jpg`

All images fail, to be precise. I don't understand why, since the path is absolute.

**Comment by lovell** [comment]
Please can you provide a complete, standalone code sample/repo that exhibits this behaviour.

**Comment by GunterJameda** [comment]
The code I just provided is as complete as it can be, but I'll write it all together and make some adjustments to be a working one.

```
const options: SharpOptions = {
  create:
    {
      width: 2000,
      height: 1000,
      channels: 3,
      background: {r:0,g:0,b:0}
    }
  };

const photos = [
'/Users/username/Library/Application Support/projectname/projects/PKTFB45BW/photos/A.jpg',
'/Users/username/Library/Application Support/projectname/projects/PKTFB45BW/photos/B.jpg',
'/Users/username/Library/Application Support/projectname/projects/PKTFB45BW/photos/C.jpg'
];

const sharpFile = this.electronService.sharp(null, options);

const pagePhotos = photos.map((photo, index) => {
  return {
    input: photo,
    top: 100 + 100 * index,
    left: 100 + 100 * index
  };
});

const pageBuffer = sharpFile.composite(pagePhotos).toBuffer();
```

I'm not sure if this will do the trick.

**Comment by lovell** [comment]
I'm unable to reproduce this problem using the provided code snippet.

The original report was an "Unhandled Promise rejection" so I can only suggest you add some error handling to your code to help narrow down exactly where the problem is occurring.

Perhaps there's some code not shown here that also uses sharp? What is `pageBuffer` (which is a Promise, not a Buffer) used for?

**Comment by GunterJameda** [comment]
It was thenned, after that and then the buffer would be injected in sharp again.

I was initially trying to change this snippet (which works all fine)

```
const pageBuffer: Promise<Buffer> = page.allPhotos.reduce<Promise<Buffer>>((bufferPromise: Promise<Buffer>, framePhoto) =>
      bufferPromise.then((buffer => this.electronService.sharp(framePhoto.photo.sizes[0].localPath)
        .rotate(undefined, {
          background: { r: 0, g: 0, b: 0 }
        })
        .resize(
          Math.round(framePhoto.width - framePhoto.borderThickness * 2),
          Math.round(framePhoto.height - framePhoto.borderThickness * 2))
        .extend({
          top: framePhoto.borderThickness,
          left: framePhoto.borderThickness,
          right: framePhoto.borderThickness,
          bottom: framePhoto.borderThickness
        })
        .toBuffer()
        .then(frameBuffer => this.electronService.sharp(buffer).overlayWith(
          frameBuffer,
          {
            top: Math.round(framePhoto.y),
            left: Math.round(framePhoto.x)
          }).toBuffer())
      ) as any)
      , sharpFile.jpeg().toBuffer() as any as Promise<Buffer>);
```

to `composite` method, which didn't work at all and threw that error. I tried to catch the error and the message was unclear, anyway. Here it is:

`Error: Input buffer contains unsupported image format`

**Comment by lovell** [comment]
Thank you for providing a more complete code sample.

If you've used `create` to create a new, blank image but have not specified any output format e.g. via `png()` etc. then the data returned by `toBuffer()` will be raw, uncompressed pixel data.

It looks like you might be feeding the resolved value of `pageBuffer` back into a new sharp instance, so you'll need to describe that raw data.

```javascript
sharp(rawBuffer, { raw: { width, height, channels }})...
```

**Comment by GunterJameda** [comment]
Thank you for your help!
It solved the issue! :)
