### ISSUE TITLE
MissingDependencyError in bundlephobia 

### ISSUE THREAD

**Issue by przemyslawpluta** [lovell/sharp#1718]
Is there a way around this error message visible in `bundlephobia` https://bundlephobia.com/result?p=removd

<img width="632" alt="MissingDependencyError" src="https://user-images.githubusercontent.com/221250/58278102-1e170380-7d93-11e9-8141-e472cdf4fa65.png">

**Comment by lovell** [comment]
Bundlephobia appears to be for client-side libraries - you'll have to ask its maintainers if it supports native modules.

**Comment by przemyslawpluta** [comment]
Thanks @lovell
