### ISSUE TITLE
How to use alpha channel from one image and apply as alpha channel of another

### ISSUE THREAD

**Issue by przemyslawpluta** [lovell/sharp#1720]
Is there a way to use alpha channel from one image e.g. png with transparency and apply its alpha channel to another image? Similar to IM `copy_opacity`:

```
composite -compose copy_opacity withAlpha.png withoutAlpha.jpg outcome.png
```

**Comment by przemyslawpluta** [comment]
Looks like this works ... in a single stream would be nicer
```js
(async () => {
   await sharp('withAlpha.png').extractChannel(3).toFile('alphaChannel.png');
   await sharp('withoutAlpha.jpg').joinChannel('alphaChannel.png').toFile('combined.png');
})();
```

**Comment by przemyslawpluta** [comment]
Looks like this works as well ... 
```js
(async () => {
   const extractAlpha = sharp().extractChannel(3);
   sharp('withoutAlpha.jpg')
       .joinChannel((await(fs.createReadStream('withAlpha.png').pipe(extractAlpha).toBuffer()))
       .toFile('combined.png');
})();
```

**Comment by lovell** [comment]
Try the `in` (or `dest-in`) blend mode of [composite](https://sharp.pixelplumbing.com/en/stable/api-composite/).

**Comment by lovell** [comment]
Hope this helped, please feel free to re-open with more details if further help is required.
