### ISSUE TITLE
Recoloring an image

### ISSUE THREAD

**Issue by Xenorio** [lovell/sharp#1721]
First of all, i'm a complete beginner in this image manipulation stuff, so i'm sorry if this is a noob question

Basically, i'm trying to change the color of an image to an exact rgb value (so not tinting it. the color needs to be the exact value.)

My input image: [Input](https://i.ibb.co/ZT1Zzy2/colorimg.png)

Desired output with ``#ff0000``: [Output](https://i.ibb.co/SxV6jkv/colorimg.png)

Hope you guys can help^^

**Comment by lovell** [comment]
Please see the future possible enhancement at #1648
