### ISSUE TITLE
Equivalent of pngquant with sharp

### ISSUE THREAD

**Issue by abarre** [lovell/sharp#1723]
I try to replace [pngquant](https://pngquant.org/lib/) by sharp. 

> Small, portable C library for high-quality conversion of RGBA images to 8-bit indexed-color (palette) images.

As far as I understand the usage of pngquant, pngquant replaces PNG 24bits by PNG 8bits.
I must admit that the change is not clear for me.

**Can you clarify if using the option `palette` with the value `true` of the output png will do the same as pngquant ?** 

Ref : `options.palette` Boolean quantise to a palette-based image with alpha transparency support, 

Best,

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/en/stable/api-output/#png

If libvips has been compiled from source with support for libimagequant and sharp has been compiled from source against that then you can access libimagequant features via e.g. the `options.palette` setting you mention.

These are the same libimagequant settings from the same underlying libimagequant library that pngquant uses.

**Comment by abarre** [comment]
Thank you for the confirmation.

**Comment by Mobe91** [comment]
@lovell I am using `sharp-cli@1.10.0` on Windows and tried to optimize a PNG using the `--palette` option but there is no reduction in the size of the resulting PNG. When I pass the same PNG to pnqquant there is a major reduction in size. How can I be sure that the libvips and libimagequant dependencies are set up correctly and are being used by sharp-cli when I pass the `--palette` option?

**Comment by lovell** [comment]
@Mobe91 If you're using Windows and require a command line tool for this purpose then I recommend you continue to use pngquant.

**Comment by Mobe91** [comment]
It would be nice if there was at least some warning the the libs are missing and that the `--palette` option won't have any effect. Otherwise it is hard to see what is going on.
