### ISSUE TITLE
Sharp crashes on invalid input

### ISSUE THREAD

**Issue by ejoebstl** [lovell/sharp#1724]
We're using sharp for handling all kinds of images user's throw at us. Sometimes, invalid images get uploaded, which we attempt to handle using try/catch. 

However, by coincidence, we found a file which crashes sharp, and with it the whole node process.

The error message is the following:

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
fish: 'ts-node crash.ts' terminated by signal SIGABRT (Abort)
```

Code to reproduce (using `ts-node`): 

```
import * as sharp from 'sharp'
import * as fs from 'fs'

sharp(fs.readFileSync("sharp_error.png.invalid")).metadata().then(console.log)
```

[File which caused the crash](https://www.dropbox.com/s/ierfpx4r2kfic32/sharp_error.png.invalid?dl=0).

**Comment by lovell** [comment]
Hi, this file is an HTML document with an embedded SVG, so is passed to librsvg to see if it can render it.

I see the following error with the latest version of sharp using prebuilt binaries:
```
Error: Input file has corrupt header: glib: XML parse error: Error domain 1 code 77 on line 68 column 1 of data: Premature end of data in tag html line 2
```

This is probably the same as #1572

What platform/OS does this occur with? Are you using the prebuilt binaries? What does `console.log(sharp.versions)` display?

**Comment by ejoebstl** [comment]
`console.log(sharp.versions)` is

```
{ cairo: '1.15.12',
  croco: '0.6.12',
  exif: '0.6.21',
  expat: '2.2.6',
  ffi: '3.2.1',
  fontconfig: '2.12.6',
  freetype: '2.9.1',
  fribidi: '1.0.5',
  gdkpixbuf: '2.36.12',
  gettext: '0.19.8.1',
  gif: '5.1.4',
  glib: '2.56.1',
  gsf: '1.14.44',
  harfbuzz: '1.8.7',
  jpeg: '1.5.3',
  lcms: '2.9',
  orc: '0.4.28',
  pango: '1.42.3',
  pixman: '0.34.0',
  png: '1.6.34',
  svg: '2.43.4',
  tiff: '4.0.9',
  vips: '8.7.0',
  webp: '1.0.0',
  xml: '2.9.8',
  zlib: '1.2.11' }
```

This is Arch Linux

`Linux archlinux 5.1.3-arch2-1-ARCH #1 SMP PREEMPT Tue May 21 23:16:12 UTC 2019 x86_64 GNU/Linux`

With 

```
ts-node v4.1.0
node v9.6.1
typescript v2.6.2
```

The binaries were built locally during `yarn`/`npm install`.

**Comment by lovell** [comment]
Thanks, it looks like you're using the prebuilt binaries so you'll need to upgrade from sharp v0.21.x to v0.22.x, the same as in #1572.

**Comment by ejoebstl** [comment]
That's it. 

Thank you, I should have looked more carefully.

**Comment by lovell** [comment]
@amyxguo Please can you upgrade to the latest version and if you're still having a problem, please open a new issue.
