### ISSUE TITLE
Piping stream through single transformation chain vs. multiple transformation chains results in different output

### ISSUE THREAD

**Issue by adriaanmeuris** [lovell/sharp#1726]
**What is the output of running `npx envinfo --binaries --languages --system --utilities`?**
```
  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz
    Memory: 151.29 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.npm-global/bin/npm
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 10.14. - /usr/bin/gcc
    Git: 2.20.1 - /usr/bin/git
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 1.8.0_171 - /usr/bin/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.1.23 - /usr/bin/php
    Python: 2.7.10 - /usr/bin/python
    Ruby: 2.3.7 - /usr/bin/ruby
```

**What are the steps to reproduce?**
Download the example input file: [input.jpg.zip](https://github.com/lovell/sharp/files/3226407/input.jpg.zip) and run the gist below.

**What is the expected behaviour?**
Both thumbnails should be equal in size, but they are not `AssertionError [ERR_ASSERTION]: 224087 == 224051`

When switching quickly between both output images in MacOS Quicklook, it looks like the output from multiple pipelines is warmer / closer to the original than using a single pipeline, although I can't see this difference when opening both images in Preview.

I've compared both outputs in Photoshop following [these steps](https://photo.stackexchange.com/a/11739), and it shows this result:
![difference](https://user-images.githubusercontent.com/16230038/58465971-0e077700-8139-11e9-9d6d-3373f8e4e9e7.png)

**Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?**
```js
(async () => {
  // Import modules
  const fs = require("fs");
  const sharp = require("sharp");
  const pump = require("pump");
  const assert = require("assert");

  // Multiple pipelines
  function multiplePipes() {
    return new Promise((resolve, reject) => {
      // Setup streams
      const rs = fs.createReadStream("./input.jpg");
      const ws = fs.createWriteStream("./output-multi.jpg");

      // 1. Resize pipeline
      const resizeOperations = sharp();
      resizeOperations.resize(2000, 1000);

      // 3. Conversion pipeline
      const convertOperations = sharp();
      convertOperations.jpeg();

      // Pipe the streams
      pump(rs, resizeOperations, convertOperations, ws, err => {
        if (err) {
          reject(err);
        } else {
          resolve(fs.readFileSync("./output-multi.jpg"));
        }
      });
    });
  }

  // Single pipeline
  function singlePipe() {
    return new Promise((resolve, reject) => {
      // Setup streams
      const rs = fs.createReadStream("./input.jpg");
      const ws = fs.createWriteStream("./output-single.jpg");

      // Single pipeline
      const operations = sharp();
      operations.resize(2000, 1000).jpeg();

      // Pipe the streams
      pump(rs, operations, ws, err => {
        if (err) {
          reject(err);
        } else {
          resolve(fs.readFileSync("./output-single.jpg"));
        }
      });
    });
  }

  // Run both pipes
  try {
    // Get output
    const buf1 = await multiplePipes();
    const buf2 = await singlePipe();

    // Compare results
    assert.equal(buf1.length, buf2.length);
  } catch (err) {
    console.error(err);
  }
})();

```

**Are you able to provide a sample image that helps explain the problem?**
yes: [input.jpg.zip](https://github.com/lovell/sharp/files/3226407/input.jpg.zip)

We have some byte-level checks in our test suite to always ensure the same output, and our tests failed while changing the code, although the output seems to be (quite) the same.

I'm wondering why both approaches have different results, and if there are any tips for combining multiple operations (as we'd like to pipe the raw pixel data through another image processing library after resizing with Sharp, and before encoding to jpeg with Sharp). Any help or insights would be greatly appreciated!

**Comment by lovell** [comment]
Hi, the mutliple pipeline approach involves a JPEG encode/decode roundtrip between `resizeOperations` and `convertOperations`, hence the compresion artefacts you're seeing.

To avoid these compression artefacts, ensure the output of `resizeOperations` is lossless, e.g. via raw, PNG or lossless WebP.

**Comment by adriaanmeuris** [comment]
Thanks for your quick response! 

Following your explanation , would it be wise to combine both `resize` and `jpeg` operations in a single pipeline, in terms of performance?

**Comment by lovell** [comment]
Yes, if possible.

**Comment by adriaanmeuris** [comment]
great, thanks for confirming!
