### ISSUE TITLE
How to bottom align when resizing

### ISSUE THREAD

**Issue by hybmg57** [lovell/sharp#1727]
What are you trying to achieve?
To bottom align trimmed image when resizing

Have you searched for similar questions?
Yes

Are you able to provide a standalone code sample that demonstrates this question?

```
sharp.resize(imageProcess.width, imageProcess.height)
      .embed()
      .background(background);

```

**Comment by lovell** [comment]
Hi, did you see the `position` option of resize?

https://sharp.pixelplumbing.com/en/stable/api-resize/#resize
```javascript
.resize(width, height, { fit: 'contain', position: 'south' })
```

**Comment by hybmg57** [comment]
Thanks for prompt reply. I've tried it but it didn't align bottom.

```
sharp.resize(imageProcess.width, imageProcess.height, { fit: 'contain', position: 'south' })
      .embed()
      .background(background);
```

I am using 0.18.4

**Comment by lovell** [comment]
You'll need to upgrade for this feature.

**Comment by hybmg57** [comment]
I just upgraded to latest 0.22.1 but still not working

**Comment by hybmg57** [comment]
https://ibb.co/rt7rVXX is the image

**Comment by hybmg57** [comment]
apologies. I had to remove all deprecated functions to resize and other options and it started working

```
sharp.resize(imageProcess.width, imageProcess.height, { 
        fit: 'contain', 
        position: 'south', 
        background: background
      });
```

**Comment by hybmg57** [comment]
https://github.com/lovell/sharp/blob/master/docs/changelog.md has good details
