### ISSUE TITLE
Sharp install OpenSSL error on MacOS High Sierra 10.13.6

### ISSUE THREAD

**Issue by jwijaya83** [lovell/sharp#1728]
Greetings,

I received this gyp build OpenSSL onWriteComplete error (trace out below). The project it self can be considered bare bone app.js with nothing in it. I did have self-signed certs inside my keychain. OpenSSL might have a problem with it so I removed it and restarted my mac but I still get the same error. I removed the libvips cache as well and force a download but I got the same result. Any idea ?

What is the output of running `npx envinfo --binaries --languages --system --utilities`?

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 213.21 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Utilities:
    CMake: 3.14.4 - /usr/local/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.17.2 - /usr/bin/git
  Languages:
    Bash: 3.2.57 - /bin/bash
    Perl: 5.18.2 - /usr/bin/perl
    PHP: 7.1.23 - /usr/bin/php
    Python: 2.7.16 - /usr/local/bin/python
    Ruby: 2.3.7 - /usr/bin/ruby

What are the steps to reproduce?
npm install sharp

Are you able to provide a sample image that helps explain the problem?
No but here is the error print out:

> sharp@0.22.0 install /realtimeDashboard/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=12.3.1 runtime=node arch=x64 libc= platform=linux)
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: write EPROTO 139928796378944:error:1425F175:SSL routines:ssl_choose_client_version:inappropriate fallback:../deps/openssl/openssl/ssl/statem/statem_lib.c:1944:
gyp ERR! stack 
gyp ERR! stack     at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
gyp ERR! System Linux 4.9.125-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /realtimeDashboard/node_modules/sharp
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.0 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.22.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-29T10_01_43_800Z-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 1

**Comment by lovell** [comment]
Node 12 support was added in v0.22.1.

https://sharp.pixelplumbing.com/en/stable/changelog/#v0221-25th-april-2019

**Comment by jwijaya83** [comment]
I believe the error is independent of the node version. Rather the native compile fails because OpenSSL is not happy about some state. Have you seen any duplicate on the matter ?
Error stack for v0.22.1 below:


node-pre-gyp WARN Using needle for node-pre-gyp https download 
[fsevents] Success: "/Users/j.wijaya/Workspace/drvlineViewer/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote

> sharp@0.22.1 install /Users/j.wijaya/Workspace/drvlineViewer/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /Users/j.wijaya/.npm/_libvips/libvips-8.7.4-darwin-x64.tar.gz

> nodemon@1.19.1 postinstall /Users/j.wijaya/Workspace/drvlineViewer/node_modules/nodemon
> node bin/postinstall || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate


> drvlineviewer@0.0.1 install /Users/j.wijaya/Workspace/drvlineViewer
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: write EPROTO 140736041915264:error:1425F175:SSL routines:ssl_choose_client_version:inappropriate fallback:../deps/openssl/openssl/ssl/statem/statem_lib.c:1944:
gyp ERR! stack 
gyp ERR! stack     at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/12.3.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/j.wijaya/Workspace/drvlineViewer
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! drvlineviewer@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the drvlineviewer@0.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/j.wijaya/.npm/_logs/2019-05-29T18_48_57_714Z-debug.log

**Comment by jwijaya83** [comment]
This is entirely macOS problem with LibreSSL. Nothing to do with sharp installation other than the support for node 12 on v0.22.1. The fix is to conpletely remove openssl and reinstall it to the latest version via homebrew. Closing
