### ISSUE TITLE
How to get dominent background colors

### ISSUE THREAD

**Issue by hybmg57** [lovell/sharp#1729]
What are you trying to achieve?
Trying to get background color to see if it's white

Have you searched for similar questions?
Yes #640 seems still open however

Are you able to provide a standalone code sample that demonstrates this question?
no code sample
Are you able to provide a sample image that helps explain the question?
https://ibb.co/rt7rVXX

**Comment by hybmg57** [comment]
only other alternative I can see is to use something like https://github.com/lokesh/color-thief together with Sharp

**Comment by lovell** [comment]
As you suggest, #640 is the relevant issue here so let's continue to track it there - please subscribe to it for updates.
