### ISSUE TITLE
Won't build Release/obj.target/sharp/src/common.o

### ISSUE THREAD

**Issue by fosteman** [lovell/sharp#1734]
Using:
    Make: 3.81 - /usr/bin/make
    GCC: 3.1 - /usr/bin/gcc

Upon installing sharp@0.21.3 with 
(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Something to do with V8... Peep into .log

[sharp_terminal.log](https://github.com/lovell/sharp/files/3236207/sharp_terminal.log)

**Comment by lovell** [comment]
Node 12 support was added in v0.22.1.

https://sharp.pixelplumbing.com/en/stable/changelog/#v0221-25th-april-2019

**Comment by fosteman** [comment]
Solved. Thanks!
