### ISSUE TITLE
Rotation degress span from -64 to 296

### ISSUE THREAD

**Issue by jamesmfriedman** [lovell/sharp#1738]
What is the output of running `npx envinfo --binaries --languages --system --utilities`?

```
 System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 820.18 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.14.0 - /usr/local/bin/node
    npm: 6.7.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Utilities:
    CMake: 3.11.1 - /usr/local/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 10.14. - /usr/bin/gcc
    Git: 2.20.1 - /usr/bin/git
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 1.8.0_131 - /usr/bin/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.1.23 - /usr/bin/php
    Python: 2.7.10 - /usr/bin/python
    Ruby: 2.4.0 - /Users/jamesmfriedman/.rvm/rubies/ruby-2.4.0/bin/ruby
```

What are the steps to reproduce?

Not sure exactly, but this code...
```
// this is loading an svg and converting it to a png
const img = sharp(path.join(paths.public, iconMap[type]));
  rotation = -Number(rotation);

  return img
    .rotate(rotation, { background: '#00000000' })
    .png()
    .toBuffer();
```

What is the expected behaviour?
For some reason outside of sanity, if the rotation number is less than -64 or greater than 296, the image will fail to render. -64 to 296 represents a 360 degree range, but I haven't the slighest clue why it is offset by -64, and I'm wary to put a solution for this in my own code.

Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?

Are you able to provide a sample image that helps explain the problem?
I don't know that I can provide much more with access to my code. It's a very bizarre issue.

**Comment by lovell** [comment]
Hi, are you able to provide a sample image that exhibits this behaviour?

Are you using prebuilt binaries or could libvips have been installed globally? What's the output of `console.log(sharp.versions)`?

**Comment by jamesmfriedman** [comment]
Sure thing
- Sample svg [vehicle.svg.zip](https://github.com/lovell/sharp/files/3254131/vehicle.svg.zip)
- I am uncertain of how to answer the second question. I'm sure libvips could have existed prior but can't be certain
```
{ cairo: '1.16.0',
  croco: '0.6.12',
  exif: '0.6.21',
  fontconfig: '2.13.1',
  freetype: '22.1.16',
  fribidi: '1.0.5',
  gdkpixbuf: '2.38.1',
  gif: '5.1.4',
  glib: '2.60.0',
  gsf: '1.14.45',
  harfbuzz: '2.3.1',
  jpeg: '9.3',
  lcms: '2.9',
  orc: '0.4.28',
  pango: '1.42.4',
  pixman: '0.38.0',
  png: '1.6.36',
  svg: '2.44.13',
  tiff: '4.0.10',
  vips: '8.7.4',
  webp: '1.0.2',
  xml: '2.9.4' }

```

**Comment by jamesmfriedman** [comment]
Please disregard this issue. I did an npm rebuild and it has magically resolved itself...
