### ISSUE TITLE
Feature request: `.min()`

### ISSUE THREAD

**Issue by LinusU** [lovell/sharp#174]
Thanks for the awesome library!

**request** I think it would be awesome if we could have a new function called `min()` which would be `max()`'s weird brother. It would take the shortest edge and scale that one inside the provided geometry.

**example** Given a image `test.jpg` with the dimensions `10800x2332` and the code `sharp('test.jpg').resize(1080, 1080).min()` it would resize the image to be `5002x1080`.

**use case** This is great when producing an image that is supposed to be viewed on a screen of a specific size, especially when dealing with panoramas.

Using something like `sharp('test.jpg').resize(1440, 1440).max()` works great for getting images that are `1400x1080` or `1080x1440`. But this only works when the images are `4:3`, processing a panorama will make a image that is only 233 pixels tall, this isn't very good when displaying on a screen.

**Comment by lovell** [comment]
Thanks for the suggestion. I'd be very happy to accept a PR if you're feeling brave :)

If it's known in advance that the input image is landscape then `sharp('test.jpg').resize(null, 1080)` might provide a workaround for now, at least for this example.

**Comment by LinusU** [comment]
I'm feeling brave! #175
