### ISSUE TITLE
The quality paramater is ignored when producing a lossless webp 

### ISSUE THREAD

**Issue by redneb** [lovell/sharp#1740]
I have the following piece of code

    await sharp("input.png")
    .webp({lossless: true, quality: 30})
    .toBuffer();

The issue is that changing the `quality` value seems to have no effect. I was expecting that it would allow me to control the compression level/speed. This exactly what the cli tool `cwebp` does with the `-q` flag when used in lossless mode.

**Comment by lovell** [comment]
Hello, the forthcoming `method` flag will do this - please see #1545

**Comment by redneb** [comment]
Hi,

The introduction of the `method` parameter would certainly help, but it appears that it is  complementary to `quality`. Here's what the [man page](https://developers.google.com/speed/webp/docs/cwebp) of `cwebp` says about those two parameters:

>-q float
>    Specify the compression factor for RGB channels between 0 and 100. The default is 75.
>    In case of lossy compression (default), a small factor produces a smaller file with lower quality. Best quality is achieved by using a value of 100.
>    In case of lossless compression (specified by the -lossless option), a small factor enables faster compression speed, but produces a larger file. Maximum compression is achieved by using a value of 100.

and

>-m int
>    Specify the compression method to use. This parameter controls the trade off between encoding speed and the compressed file size and quality. Possible values range from 0 to 6. Default value is 4. When higher values are used, the encoder will spend more time inspecting additional encoding possibilities and decide on the quality gain. Lower value can result in faster processing time at the expense of larger file size and lower compression quality.

There is also a related parameter, `-z`, which specifies a lossless preset. It's essentially a way to simply set both `quality` and `method`:

> -z int
>    Switch on lossless compression mode with the specified level between 0 and 9, with level 0 being the fastest, 9 being the slowest. Fast mode produces larger file size than slower ones. A good default is -z 6. This option is actually a shortcut for some predefined settings for quality and method. If options -q or -m are subsequently used, they will invalidate the effect of this option.

I am not sure how this parameter is exposed by `libwebp`, but [here's](https://github.com/webmproject/libwebp/blob/1394a2bb86243fd0ce46fd516f86833d4b50ae69/src/enc/config_enc.c#L135) the relevant part in the code.

**Comment by lovell** [comment]
I've opened https://github.com/libvips/libvips/pull/1331 to add support for this to libvips.

**Comment by xiekevin** [comment]
Hi, any update on this issue?

**Comment by lovell** [comment]
This is dependent on libvips v8.8.1.

**Comment by lovell** [comment]
sharp v0.23.0 / libvips v8.8.1 now available.
