### ISSUE TITLE
NEF & CR2 raw files to JPG

### ISSUE THREAD

**Issue by przemyslawpluta** [lovell/sharp#1742]
Is there a way to convert `NEF` & `CR2` raw files from DSLR camera to `JPG` with sharp?

**Comment by lovell** [comment]
Hi, did you see #616?

**Comment by przemyslawpluta** [comment]
Thanks.

**Comment by przemyslawpluta** [comment]
@lovell would the functionality similar to `extractJpgFromRaw` or `extractPreview` in `exiftool`be possible in `sharp`?
