### ISSUE TITLE
'Something went wrong installing the "sharp" module'

### ISSUE THREAD

**Issue by cekvenich** [lovell/sharp#1747]
What is the output of running `npx envinfo --binaries --languages --system --utilities`?

  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 6.02 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    Yarn: 1.16.0 - ~/Documents/GitHub/mBakeCLI/src/node_modules/.bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.21.0 - /usr/bin/git
  Languages:
    Bash: 3.2.57 - /bin/bash
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.1.23 - /usr/bin/php
    Python: 2.7.10 - /usr/bin/python
    Ruby: 2.3.7 - /usr/bin/ruby

What are the steps to reproduce?
 yarn add sharp
 npm publish
What is the expected behaviour?
I can deploy my npm package to npm.js
Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?
If it helps.
Are you able to provide a sample image that helps explain the problem?
I don't understand the question.

But let me tell you the error, my project ( https://github.com/metabake/mBakeCli ) uses sharp.
Today, when I publish my project I get an error: 
Something went wrong installing the "sharp" module

dlopen(/Users/code/.config/yarn/global/node_modules/sharp/build/Release/sharp.node, 1): Library not loaded: @rpath/libvips-cpp.dylib
  Referenced from: /Users/code/.config/yarn/global/node_modules/sharp/build/Release/sharp.node
  Reason: image not found

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues

**Comment by cekvenich** [comment]
I moved the code out of my main package to here:
https://github.com/metabake/mbakeAdvanced/tree/master/mbakeX

and then had to comment out sharp code. Same error

dlopen(/Users/code/.config/yarn/global/node_modules/sharp/build/Release/sharp.node, 1): Library not loaded: @rpath/libvips-cpp.dylib
Referenced from: /Users/code/.config/yarn/global/node_modules/sharp/build/Release/sharp.node
Reason: image not found

**Comment by lovell** [comment]
Hi, it looks like you might be using a globally-installed sharp rather than one stored locally in your project's `node_modules` directory. Perhaps there's a corruption or conflict between two different versions?

Try running `yarn global remove sharp` then `yarn install` in your project directory.

**Comment by cekvenich** [comment]
I am using global. 
I tried to remove sharp and remove my module globally as you suggested.

And then rebuild, reinstall: and I get the same error.  It says the image is not found for rpath/libvips, is that some dependency of yours or your code?

**Comment by lovell** [comment]
If you get the same error, namely one with the path `/Users/code/.config/yarn/global/node_modules/sharp/build/Release/sharp.node`, then sharp probably hasn't been globally removed yet.

Does the file referenced still exist? What happens if you delete `/Users/code/.config/yarn/global/node_modules/sharp`? Could another globally-installed module depend on (a different version of) sharp?

**Comment by cekvenich** [comment]
This worked, I think:
 yarn cache clean
 yarn upgrade

But I am concerned about downstream users of my package. 
Since I don't know who they all are. I can't tell all of them to do  yarn cache clean, yarn upgrade.
(One silly solution is that you bump the versions of your package more often, even w/ no changes, I know it is silly)
Also I don't think it is a different version of your package since your packages is ~ month old, and all my work was in last few days.

**Comment by lovell** [comment]
Glad you got it working.

I'm always concerned about downstream users of sharp, of which there are many, and luckily the problem you ran into is uncommon.

If you and your downstream users are able to avoid the need to globally-install sharp then this will avoid a whole class of possible problems.

**Comment by cekvenich** [comment]
Thanks. Unfortunately my package is global and I use sharp.

**Comment by lovell** [comment]
For CLI tooling I usually advise the use of either `npx` or `yarn dlx`. Both download each package version only once and cache so are as performant as installing globally but more importantly avoid making those packages available globally.

**Comment by cekvenich** [comment]
Oh... good trick!
