### ISSUE TITLE
Unexpected outcome with joinChannel and Orientation meta 

### ISSUE THREAD

**Issue by przemyslawpluta** [lovell/sharp#1750]
Assuming original image:

```js
await sharp('main.jpg').metadata()
```

```js
{ format: 'jpeg',
  width: 1080,
  height: 720,
  space: 'srgb',
  channels: 3,
  depth: 'uchar',
  density: 72,
  chromaSubsampling: '4:2:0',
  isProgressive: false,
  hasProfile: false,
  hasAlpha: false,
  orientation: 8
```

Where actual height is `1080` and width `720` as `Orientation` tag `8` = `Rotate 270 CW` indicates image has been rotated .

![canon_eos_70d_01](https://user-images.githubusercontent.com/221250/59344881-cd962480-8d06-11e9-9952-fdf4df0ae9b7.jpg)

And image to be applied as alpha:

```js
await sharp('alpha.png').metadata()
```

```js
{ format: 'png',
  width: 720,
  height: 1080,
  space: 'b-w',
  channels: 1,
  depth: 'uchar',
  density: 72,
  isProgressive: false,
  hasProfile: false,
  hasAlpha: false }
```
![alpha](https://user-images.githubusercontent.com/221250/59346079-63cb4a00-8d09-11e9-9bac-a127b4a0c6f5.png)

Produces unexpected outcome when using `joinChannel`:

```js
await sharp('main.jpg').joinChannel('alpha.png').toFile('combined.png');
```
![combined](https://user-images.githubusercontent.com/221250/59346133-865d6300-8d09-11e9-9ef1-45db7bcdefde.png)

**Comment by lovell** [comment]
If you want sharp to apply the EXIF orientation of `main.jpg` then you'll need to tell it that via the `rotate()` operation, something like (untested):
```javascript
await sharp('main.jpg')
  .rotate()
  .joinChannel('alpha.png')
  .toFile('combined.png');
```

**Comment by przemyslawpluta** [comment]
Perfect. Thanks @lovell 

![combined](https://user-images.githubusercontent.com/221250/59350416-ec4ee800-8d13-11e9-96ac-a9b75243e34c.png)

**Comment by darkCavalier11** [comment]
i extract all the channel from an image using `.extractChannel()`. now i want to join all of them to form single original image using `.joinChannel` but i cant understand how. if u can provide a snippet for joining image channel to make the original image that would be very helpful.
