### ISSUE TITLE
Possibility to remove png chunk (options and extensions)

### ISSUE THREAD

**Issue by abarre** [lovell/sharp#1751]
**What are you trying to achieve?**

I try to achieve a replacement of `pngcrush` by `sharp`. pngcrush has the ability to remove chunk that are optional. I personnally use : `pngcrush -rem alla -remove input.png output.png`.

This is an extract of the [doc](http://pwet.fr/man/linux/commandes/pngcrush/) : 

`-rem chunkname`
> Name of an ancillary chunk or optional PLTE to be removed. Be careful with this. Please don't use this feature to remove transparency, gamma, copyright, or other valuable information. To remove several different chunks, repeat: -rem tEXt -rem pHYs. Known chunks (those in the PNG spec or extensions document) can be named with all lower-case letters, so -rem bkgd is equivalent to -rem bKGD. But note: -rem text removes all forms of text chunks; Exact case is required to remove unknown chunks. To do surgery with a chain-saw, -rem alla removes all known ancillary chunks except for tRNS, and -rem allb removes all but tRNS and gAMA.

**What would you expect the API to look like?**

I would expect that the PNG output would produce PNG without optional chunks. Ancillary chunks would be kept only if `withMetadata()` is used.

I already asked the [question](https://github.com/libvips/libvips/issues/1336) to libvips project. It seems possible without changing the libvips.

Ref : https://sourceforge.net/p/pmt/code/ci/pngcrush/tree/pngcrush.c 
http://www.libpng.org/pub/png/book/chapter11.html#png.ch11.div.5

**Comment by lovell** [comment]
Hi, let's continue this at https://github.com/libvips/libvips/issues/1336 as sharp is relying on libvips to access lower-level libpng features.

**Comment by abarre** [comment]
Yes, sure.
