### ISSUE TITLE
Draw to image

### ISSUE THREAD

**Issue by morpheus-87** [lovell/sharp#1752]
What are you trying to achieve?

It would be great, if one could open an existing image and then draw f.e. a rectangle to that image. Is this possible?

Have you searched for similar questions?

Are you able to provide a standalone code sample that demonstrates this question?

Are you able to provide a sample image that helps explain the question?

**Comment by lovell** [comment]
Hello, I'd suggest using the [composite](https://sharp.pixelplumbing.com/en/stable/api-composite/) operation with an SVG containing the shapes you need.

**Comment by morpheus-87** [comment]
Thanks for your fast answer! The thing is that the reactangle is dynamic. Do you think this would also be possible?

**Comment by lovell** [comment]
The SVG can be dynamic, yes. Perhaps try it and see what happens.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further help is required.
