### ISSUE TITLE
Install Failed, Syntax Error

### ISSUE THREAD

**Issue by ardyfeb** [lovell/sharp#1753]
run `npm i sharp`

and get error like this
```
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\windows7\AppData\Local\Programs\P
ython\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[
:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:259:5)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\windows7\AppData\Roaming\npm\node_modules\expo-cli\node_mo
dules\sharp
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by lovell** [comment]
Hello, is this 32-bit Windows? If so, this is unsupported.

https://sharp.pixelplumbing.com/en/stable/install/#windows-x64

If this is 64-bit Windows and 64-bit `node.exe`, please can you provide more of the installation error log output prior to the bit you've pasted here.

**Comment by ardyfeb** [comment]
> Hello, is this 32-bit Windows? If so, this is unsupported.
> 
> https://sharp.pixelplumbing.com/en/stable/install/#windows-x64
>  
> If this is 64-bit Windows and 64-bit `node.exe`, please can you provide more of the installation error log output prior to the bit you've pasted here.

its worked !!, actually i want to install `expo-cli` but sharp is required depencies. thanks !!
