### ISSUE TITLE
 How to add gradient effects to images

### ISSUE THREAD

**Issue by liganghui** [lovell/sharp#1758]
I want to add a gradient to the image. I tried some of the methods in the documentation but didn't succeed. Can this component achieve a similar effect? 
![QQ截图20190620230201](https://user-images.githubusercontent.com/15844198/59859811-0e99d300-93b0-11e9-8b60-63b050560920.png)
![QQ截图20190620230317](https://user-images.githubusercontent.com/15844198/59859814-0f326980-93b0-11e9-892c-ce638bd05d07.png)

**Comment by liganghui** [comment]
Thanks, canvas should solve this problem.

https://stackoverflow.com/questions/3320417/is-it-possible-to-make-a-gradient-transparent-layer-masking-image-using-canvas/11757560?noredirect=1#comment45736276_11757560

**Comment by lovell** [comment]
See also #1299 and #1334

**Comment by liganghui** [comment]
> 另见[＃1299](https://github.com/lovell/sharp/issues/1299)和[＃1334](https://github.com/lovell/sharp/issues/1334)

Thank you, I will refer to
