### ISSUE TITLE
Automatically serve webp when support is detected

### ISSUE THREAD

**Issue by timkelty** [lovell/sharp#1760]
I'm migrating to Sharp from Thumbor, where I relied on the `AUTO_WEBP` feature: https://github.com/thumbor/thumbor/wiki/Configuration#auto_webp

This looked at the incoming request's `Accept` header, and if it contained `image/webp`, it would automatically serve the image as webp.

Here's an example from an existing Thumbor resizer:

With no `Accept` header (legacy browser):
```
❯ curl -Is "https://d3v5ux74ykdcrl.cloudfront.net/560x280/filters:quality(50):focal(959x539:961x541)/insights/Emil-Headshot.jpg" | grep "content-type"
content-type: image/jpeg
```

With `Accept: image/webp` (modern browser)
```
~
❯ curl -Is --header "Accept: image/webp" "https://d3v5ux74ykdcrl.cloudfront.net/560x280/filters:quality(50):focal(959x539:961x541)/insights/Emil-Headshot.jpg" | grep "content-type"
content-type: image/webp
```

I've looked through the docs but don't see an equivalent feature.

**Comment by lovell** [comment]
Hi, this module is all about image processing and doesn't provide any networking or HTTP logic so you'll have to write that bit yourself.

Perhaps look at something like https://github.com/papandreou/express-processimage or https://github.com/asilvas/node-image-steam

**Comment by timkelty** [comment]
gotcha, thanks for the quick response @lovell !
