### ISSUE TITLE
expo installation

### ISSUE THREAD

**Issue by ilahishaikh** [lovell/sharp#1761]
Something went wrong installing the "sharp" module

The module '\\?\C:\Users\Syneotek\AppData\Roaming\npm\node_modules\expo-cli\node_modules\sharp\build\Release\sharp.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

- Ensure the version of Node.js used at install time matches that used at runtime
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues

**Comment by Tanishqqjain** [comment]
I am also getting the same error

**Comment by drewthoennes** [comment]
I was also getting this error `/usr/local/lib/node_modules/expo-cli/node_modules/sharp/build/Release/sharp.node` and I fixed it by running `npm rebuild` in `/usr/local/lib/node_modules/expo-cli`

**Comment by lovell** [comment]
Please see #1696
