### ISSUE TITLE
how to fix Something went wrong installing the “sharp” module and Cannot find module '../build/Release/sharp.node' in expo

### ISSUE THREAD

**Issue by saidhappy010** [lovell/sharp#1762]
What are you trying to achieve?

Have you searched for similar questions?

Are you able to provide a standalone code sample that demonstrates this question?

Are you able to provide a sample image that helps explain the question?

**Comment by lovell** [comment]
Please see #1696

**Comment by saidhappy010** [comment]
@lovell Thank you very much

**Comment by huykon** [comment]
still have error :(
