### ISSUE TITLE
[Question] How to create a linear gradient

### ISSUE THREAD

**Issue by Kikobeats** [lovell/sharp#1763]
Hello,

Although this is related with #1758, I want to ask if exist just a simple approach to create a linear gradient, pretty similar how CSS works:

```css
background: linear-gradient(136deg, rgb(22, 135, 237), rgb(20, 55, 90));
```

getting something like this as output 

<img width="957" alt="Screenshot 2019-06-24 at 17 28 38" src="https://user-images.githubusercontent.com/2096101/60031717-86fcde80-96a5-11e9-8228-006deea12831.png">

occupying all the available space

**Comment by lovell** [comment]
Hi, have you tried an SVG-based approach for this (as mentioned in the linked issue)?

**Comment by Kikobeats** [comment]
Yes,  but not sure how I can set up 100% dimensions size

**Comment by lovell** [comment]
http://angrytools.com/gradient/ has an SVG option - perhaps try that?

**Comment by Kikobeats** [comment]
For people interested on this, I created [svg-gradient](https://github.com/Kikobeats/svg-gradient) that receives CSS linear gradient as input and return a SVG linear gradient as output.


```js
const svgGradient = require('svg-gradient')
const sharp = require('sharp')
const image = await sharp(Buffer.from(svgGradient(`linear-gradient(136deg, rgb(22, 135, 237), rgb(20, 55, 90))`)))
const buffer = await image.toBuffer()
```
