### ISSUE TITLE
Found vendored libvips v8.7.0 but require v8.7.4. Please remove the 'node_modules/sharp/vendor' directory and run 'npm install'.

### ISSUE THREAD

**Issue by evanlesmez** [lovell/sharp#1764]
Anytime I run expo start (or yarn start) in my React Native project directoy I get : 

``Found` vendored libvips v8.7.0 but require v8.7.4. Please remove the 'node_modules/sharp/vendor' directory and run 'npm install'.``

Here is my package.json for a react native expo project : 
```{
  "name": "babylon-app",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "electron-rebuild": "^1.8.5",
    "jest-expo": "^32.0.0",
    "react-devtools": "^3.6.1",
    "react-dom": "^16.8.6",
    "react-native-scripts": "1.14.0",
    "react-native-testing-library": "^1.9.1",
    "react-test-renderer": "16.3.1",
    "schedule": "^0.4.0"
  },
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "devtools": "react-devtools",
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "test": "jest",
    "react-devtool": "react-devtools"
  },
  "jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|sentry-expo|native-base)"
    ]
  },
  "dependencies": {
    "@expo/vector-icons": "^10.0.1",
    "@material-ui/core": "^3.1.0",
    "babel-plugin-module-resolver": "^3.2.0",
    "babel-plugin-require-all": "0.0.1",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "babel-plugin-wildcard": "^5.0.0",
    "expo": "^32.0.0",
    "lodash": "^4.17.11",
    "mobx": "^5.5.2",
    "mobx-react": "^5.3.6",
    "mobx-utils": "^5.4.1",
    "moment": "^2.22.2",
    "native-base": "^2.12.1",
    "react": "16.6.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-animatable": "^1.3.0",
    "react-native-chart-kit": "^1.1.8",
    "react-native-charts": "^3.0.0",
    "react-native-dash": "0.0.9",
    "react-native-extended-stylesheet": "^0.11.2",
    "react-native-modal-datetime-picker": "^6.1.0",
    "react-native-modal-selector": "^1.0.3",
    "react-native-svg": "^6.5.2",
    "react-native-tab-view": "^2.5.0",
    "react-navigation": "^3.5.1",
    "victory-native": "^30.5.0"
  }
} 
```

What is the expected behaviour?
No matter what conditions the folder is in I get the same output: 

``Found` vendored libvips v8.7.0 but require v8.7.4. Please remove the 'node_modules/sharp/vendor' directory and run 'npm install'.``

I tried clearing my cache, reinstall my modules, and _even running without node_modules_ but I always get the same output. This is pretty stressful right now because I am tring to get my app into production very soon but this hit me out of nowhere. Sharp is not even in my dependencies globally or here so where is this error coming from I am so confused. I tried reinstalling yarn still the same.

**Comment by evanlesmez** [comment]
I tried changing node version and everything and still get this I am so lost. I listed global packages and can't find sharp or libvips.

**Comment by lovell** [comment]
If you've installed expo-cli globally then please see https://github.com/lovell/sharp/issues/1696#issuecomment-496516725

**Comment by evanlesmez** [comment]
Thanks have a new issue now but at least I am past this one
