### ISSUE TITLE
toFile() does not warn if folder does not exist

### ISSUE THREAD

**Issue by jonathanjfshaw** [lovell/sharp#1765]
What is the output of running `npx envinfo --binaries --languages --system --utilities`?
  System:
    OS: Linux 4.9 Alpine Linux undefined
    CPU: (2) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    Memory: 1.45 GB / 1.93 GB
    Container: Yes
    Shell: Unknown - /bin/ash
  Binaries:
    Node: 10.15.3 - /usr/bin/node
    npm: 6.4.1 - /usr/bin/npm

Using latest gazf/alpine-sharp docker image.

### What are the steps to reproduce?

Use sharp().composite.toFile(file) where the file path is a directory that does not exist.
The file outputting fails, without error or warning.

### What is the expected behaviour?

I feel like I should have got some feedback that the output was failing because the folder did not exist.

### Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?

```
async function compositeDiff(file, width) {
  var margin = 10;
  sharp(diffDir + file)
      .extend({
        top: 0,
        bottom: 0,
        left: 0,
        right: ((width + margin) * 2)
      })
      .composite([
          {
            input: referenceDir + resizedDir + file,
            left: width + margin,
            top: 0
          },
          {
            input: testDir + resizedDir + file,
            left: (width + margin) * 2,
            top: 0
          },
      ])
      .toFile(comparisonDir + file)
}
```

Calling this function in a script that is called from a docker-compose command using the gazf/alpine-sharp image produces no error or warning output, but outputs no file.
Inserting a mkdir at the start of the function fixes the problem of no file being outputted.

**Comment by lovell** [comment]
Hi, I see the following error when attempting to write to a non-existent directory via `toFile()`:
```
Error: vips__file_open_write: unable to open file "does-not-exist/output.jpg" for writing
unix error: No such file or directory
```
Perhaps some error handling is required in the code that calls the `compositeDiff()` function shown in this example?

Please see #639 #874 #1052

**Comment by jonathanjfshaw** [comment]
Yeah, I'm no js dev, so probably just mishandling errors and promises.
