### ISSUE TITLE
is sharp(undefined, { raw: ... }) valid? if not, it would be handy to have it error.

### ISSUE THREAD

**Issue by ericblade** [lovell/sharp#1767]
I had some issues where I was trying to do some processing with sharp, and was getting stuck inside a promise that never resolved or rejected.  Turns out that I was accidentally passing in undefined variables as the first parameter to sharp(), and it took me quite a while to locate that as the culprit because there was no error or warning or anything.

**Comment by lovell** [comment]
Let's track this in #1768 as it's the same thing and benefits from a code sample.
