### ISSUE TITLE
Enhancement: improve fail-fast nature of constructor when null accidentally passed as input (a somewhat breaking change)

### ISSUE THREAD

**Issue by ericblade** [lovell/sharp#1768]
Discovered in relation to https://github.com/lovell/sharp/issues/1767 .  Also appears same as long closed https://github.com/lovell/sharp/issues/510

````
sharp(undefined, { raw: ... }).png().toBuffer()
````
never resolves or rejects.

**Comment by lovell** [comment]
Passing in an undefined input currently switches sharp into a WritableStream, in this case it would expect uncompressed, raw pixel data to be streamed in, the shape of which is defined by `raw: ...`

The above example is the same as using the `sharp({ raw: ... })...` syntax.

Are you expecting to use Stream-based input? If not, how are you planning to provide input data?

**Comment by ericblade** [comment]
I had *thought* i was passing it a buffer, but i was accessing the wrong key of my object that held the buffers. :-) I thought that's what it was doing, was giving me a WritableStream, but I wasn't sure if it was valid to pass (undefined, { raw.. }) to it. 

I'm thinking perhaps checking arguments.length then throwing if that doesn't match what would be expected?  (ie, if there are two arguments, but the first one is undefined, it probably means the user made a mistake, rather than the user intended to create a WritableStream)  .. that's the only way I can think of to achieve that without breaking the existing interface, anyway.

also, throwing on toBuffer() while there's nothing there? maybe?

**Comment by lovell** [comment]
The two-param constructor-function that allows the first param to be null/undefined was retained for backwards compatibility but I agree that it is confusing. Let's mark this as an enhancement to have that usage throw in the next major release.

(`toBuffer()` can't synchronously throw as input is asynchronously provided.)

**Comment by lovell** [comment]
v0.24.0 is now available with your suggested API improvement, thank you.
