### ISSUE TITLE
Image Resizing loses quality in Linux but working fine in Mac for less than 616 width.

### ISSUE THREAD

**Issue by anil-pawar** [lovell/sharp#1770]
Use Same Image to resize in Mac and Ubuntu, you can see image quality difference for width=482.

NOTE : Image width should me less than 616, its showing good quality for greater than 615 width.

```
const sharp = require('sharp');
var file='shirt.jpg';
sharp(file).resize(482).toFile('Output-Linux.jpg', function(err) {});
```
shirt.jpg
![shirt](https://user-images.githubusercontent.com/3750855/60395891-2bba6880-9b4b-11e9-876d-6c3476ac6b87.jpg)

Output-Linux.jpg
![Output-Linux](https://user-images.githubusercontent.com/3750855/60395892-2c52ff00-9b4b-11e9-970c-4e58162b0fde.jpg)

Output-Mac.jpg
![Output-Mac](https://user-images.githubusercontent.com/3750855/60395893-2c52ff00-9b4b-11e9-8ed3-2bbbf943e234.jpg)

**Comment by lovell** [comment]
Hello, did you see the `fastShrinkOnLoad` option of [resize](https://sharp.pixelplumbing.com/en/stable/api-resize/)?

> take greater advantage of the JPEG and WebP shrink-on-load feature, which can lead to a slight moiré pattern on some images. (optional, default true)

The prebuilt libvips binaries for OS X currently ship with libjpeg where Linux provides libjpeg-turbo. From the forthcoming sharp v0.23.0 onwards they will be consistent in their use of lijpeg-turbo - see https://github.com/lovell/package-libvips-darwin/pull/3

**Comment by anil-pawar** [comment]
It's working fine with `fastShrinkOnLoad`.
Thanks.
