### ISSUE TITLE
Make a image into several tile images once

### ISSUE THREAD

**Issue by Jongkeun** [lovell/sharp#1771]
**What are you trying to achieve?**
- I hope to make a image into several tiled image.
  For example, I want to make a 100*100 image to 4 images as 50*50 image.

**Have you searched for similar feature requests?**
- Yes

**What would you expect the API to look like?**
```
const srcImage = "image.png";
const destFolder = "./ImageFolder";
const keyword = "tile"

sharp(srcImage)
    .toTiles({ width: 50, height: 50 })
    .toFile(destImage, keyword)
    .then(function(new_file_info) {
      console.log("Images tiled and saved");      
    })
    .catch(function(err) {
      console.log(err);
    });
```

**What alternatives have you considered?**
- I used `extract`. But to make image tile, I had to repeat load and `extract` several times.
  I think this is wasted of resources. I want to load just once.

**Is there a sample image that helps explain?**
![캡처](https://user-images.githubusercontent.com/33743343/60412109-dd6c9e80-9c0a-11e9-8fa4-d809372cdb61.PNG)

After `toTiles`.

![img2](https://user-images.githubusercontent.com/33743343/60412123-ebbaba80-9c0a-11e9-82ac-a645b28f43a9.PNG)

4 image files are created

**Comment by lovell** [comment]
Hello, did you see the [tile](https://sharp.pixelplumbing.com/en/stable/api-output/#tile) operation?

**Comment by Jongkeun** [comment]
Yes I did @lovell .
```
sharp(srcImage)
    .png()
    .tile({
      size: 512
    })
    .toFile("output.dz", function(err, info) {
      // output.dzi is the Deep Zoom XML definition
      // output_files contains 512x512 tiles grouped by zoom level
    });
```

I don't know if I did well, but it was not what I expected.
I don't need zoomed image. I need pieces of original image.

So I tried to do like below code
```
sharp(srcImage)
    .extract({ width: 5, height: 5, left: 215, top: 121 })
    .toFile("dest1.png")
    .then(function(new_file_info) {
      console.log("Image cropped and saved");
    })
    .catch(function(err) {
      console.log(err);
    });

sharp(srcImage)
    .extract({ width: 5, height: 5, left: 220, top: 121 })
    .toFile("dest2.png")
    .then(function(new_file_info) {
      console.log("Image cropped and saved");
    })
    .catch(function(err) {
      console.log(err);
    });

....

```

**Comment by lovell** [comment]
Using a blank 100x100 input image:
```javascript
sharp({
  create: {
    width: 100,
    height: 100,
    channels: 3,
    background: "red"
  }
})
  .png()
  .tile({ size: 50, depth: "one" })
  .toFile("out.dz")
```
with the `tile` operation configured to your needs produces:
```sh
$ vipsheader out_files/0/*
out_files/0/0_0.png: 50x50 uchar, 3 bands, srgb, pngload
out_files/0/0_1.png: 50x50 uchar, 3 bands, srgb, pngload
out_files/0/1_0.png: 50x50 uchar, 3 bands, srgb, pngload
out_files/0/1_1.png: 50x50 uchar, 3 bands, srgb, pngload
```

**Comment by Jongkeun** [comment]
Yes! it works like what I want.
Thanks, @lovell

**Comment by Jongkeun** [comment]
@lovell.
I have an another question.
If `srcImage` was not a square, how can I make the image to square tiles when pivot is (0,0) ?

**Comment by lovell** [comment]
Please can you provide a worked example of this question (as you did with the 100x100 example before).

**Comment by Jongkeun** [comment]
Sorry. I changed logics.
Now it's enough to me.
Thanks!

**Comment by 1Map** [comment]
I get the following error when trying to create a deep zoom tile(s):

`rename: unable to rename file "/myfolder/output-C948Y0/output_files" as "/myfolder/output_files", Directory not empty`

Seems that tile creates a temp folder output-C948Y0/output_files that cannot be renamed / moved back to /output_files because /output_files is not empty.

I use:

```
sharp(srcImage)
    .tile({
      size: 256
    })
    .toFile("/myfolder/output.dz", function(err, info) {
      // output.dzi is the Deep Zoom XML definition
      // output_files contains 256x256 tiles grouped by zoom level
    });
```
