### ISSUE TITLE
Limit jpeg quality to that of source image

### ISSUE THREAD

**Issue by rightaway** [lovell/sharp#1774]
If the source image has a quality of 60 and I've set it to 50, then it should decrease to the limit of 50. But if the source image is 40, then perhaps it shouldn't increase to 50 in the output image.

I have files that are actually increasing in size after running them through sharp because my jpeg quality setting is higher than the source's, even though nothing else changes. I suppose there's no benefit to increasing the quality beyond what the source provides.

Could there be something (similar to the `withoutEnlargement` parameter for `resize` function) like `withoutIncrease` for `jpeg` function? And maybe a `same` parameter to make the quality of the output image the same as the source image without increasing or decreasing it?

**Comment by lovell** [comment]
Please see #908 for why this is not possible.
