### ISSUE TITLE
Is there a way to modify buffer and export it as a image file

### ISSUE THREAD

**Issue by DarylsJoy** [lovell/sharp#1775]
What are you trying to achieve?
I m trying to use LSB hide some information in png.

As the code below, I got an error:
> Error: Input buffer contains unsupported image forma

I noticed this in doc
> Note that raw pixel data is only supported for buffer output.

Is this the cause of this error?
Is there a way for me to export a file or am I use it in wrong way? Thanks

Have you searched for similar questions?
yes.

Are you able to provide a standalone code sample that demonstrates this question?
```
(async () => {
  const data = await sharp('./img/input.png').raw().toBuffer();

  // some code here
  // for example, data[0] = 255.
  // but even I do nothing here, still got the same error

  await sharp(data).toFile('./img/output.png');
})();
```

Are you able to provide a sample image that helps explain the question?
All images have same problem.

I already figure it out with another way, I just want to know can I achieve this with sharp

Thanks.

**Comment by lovell** [comment]
Raw, uncompressed pixel data provided as input must also include additional information about dimensions and channels.

```diff
-  await sharp(data).toFile('./img/output.png');
+  await sharp(data, { raw: { width: ... , height: ..., channels: ... }}).toFile('./img/output.png');
```

https://sharp.pixelplumbing.com/en/stable/api-constructor/

**Comment by DarylsJoy** [comment]
Thanks, sorry I didn't notice it here.
