### ISSUE TITLE
Usage with Axios?

### ISSUE THREAD

**Issue by qoonqode** [lovell/sharp#1778]
I'm currently trying to download an image using Axios and then resize the result and save it locally via Node in a GraphQL resolver.

This is the block of code I'm working with:
```javascript
axios.get(url)
                .then((response) => {
                    const { set, collector_number } = response.data;
                    const sourceUrl = response.data.image_uris.border_crop;
                    const filename = `${set}/${collector_number}.png`;
                    axios.get(sourceUrl, { responseType: 'arraybuffer' })
                        .then((res) => {
                            console.log(`Resizing Image!`)
                            sharp(res)
                                .resize(226, 321)
                                .toFile(`../cardimg/${filename}`)
                                .then(() => {
                                    console.log(`Image downloaded and resized!`)
                                })
                                .catch((err) => {
                                    console.log(`Couldn't process: ${err}`);
                                })
                        })
                })
```

When I execute the code (via GraphQL Mutation), it throws an error saying that states `Input file is missing`.

Not sure if it's misuse of Axios, or if I'm doing something wrong with Sharp.

Any suggestions?   I was originally worried that I needed to mess with the format of the response coming from the HTTP request, but from what I can gather, I'm doing it correctly.  

Thanks in advance!

I've used `console.log` to ensure that it's definitely grabbing an image and the URL is correct, so that's already been tested, so the `sourceUrl` is indeed grabbing an image, I'm just not sure how to properly do anything -with-  the data that I'm grabbing.

**Comment by lovell** [comment]
I think Axios returns an object on which the `data` property is of interest:

```diff
-    .then((res) => {
+    .then(({ data }) => {
```

**Comment by qoonqode** [comment]
You're right!

I used `.data` on the first Axios request but not the second one.

Oversight.  Oops.

Thank you!

I'll double check after work.  :)

**Comment by ChristianRich** [comment]
Doh... I just fell into the exact same trap and ended up here :-)
