### ISSUE TITLE
code only seems to work if intermediate file is used?

### ISSUE THREAD

**Issue by avpavp** [lovell/sharp#1779]
I have a chunk of code as follows:

```
      var img = sharp(path)
  
      // Extract the grayscale channel?
      // and save as 'newGrey.png'
      var grey = img.extractChannel(0)
      await grey.toColorspace("b-w")
(1)        .toFile("newGrey-"+ client.clientID + client.counter +".png")

      // Load new alpha and join
      let filename = 'transparencies/'+client.rasterConfig.transparency+'.png'
      //console.log(filename)
(2)      await sharp('newGrey-'+ client.clientID + client.counter + '.png')
        .toColorspace("b-w")
        .joinChannel(filename)
        .toBuffer((err, data, info) => { 

```

This code works.  

But as you can see, I'm basically writing the file to a temp image at point (1), then reload that same temp image at point (2).  This seems totally like it should be redundant.  But if I remove the toFile at (1) and the load at (2), I don't get the same resultant image.

What am I misunderstanding here?

Thanks

**Comment by lovell** [comment]
Hi, if you're using the channel operations then yes, intermediate images will be required. You could use raw, uncompressed pixel data, something like:
```javascript
const { width, height } = await sharp(path)
  .metadata();

const greyscale = await sharp(path)
  .extractChannel(0)
  .toColorspace("b-w")
  .raw()
  .toBuffer();

const result = await sharp(greyscale, { raw: { width, height, channels: 1 })
  .toColorspace("b-w")
  .joinChannel(filename)
  .toBuffer();
```

**Comment by avpavp** [comment]
Ah - thanks for the tip.  I've managed to get this working - with your help!
