### ISSUE TITLE
npm install / build error "../src/utilities.cc: In function ‘v8::Handle<v8::Value> format(const v8::Arguments&)’:"

### ISSUE THREAD

**Issue by jiivonen** [lovell/sharp#178]
Hello,

I'm trying to install sharp on a CentOS 6.6 machine. What I can see the preinstall script went thru ok.
But installing the sharp fails with following:
```
> sharp@0.9.3 install /tmp/sharptest/node_modules/sharp
> node-gyp rebuild

make: Entering directory /tmp/sharptest/node_modules/sharp/build
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
../src/utilities.cc: In function ‘v8::Handle<v8::Value> format(const v8::Arguments&)’:
../src/utilities.cc:99: error: expected initializer before ‘:’ token
../src/utilities.cc:99: error: expected primary-expression before ‘)’ token
../src/utilities.cc:99: error: expected ‘;’ before ‘)’ token
../src/utilities.cc:103: error: ‘f’ was not declared in this scope
make: *** [Release/obj.target/sharp/src/utilities.o] Error 1
make: Leaving directory `/tmp/sharptest/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 2.6.32-504.8.1.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/sharptest/node_modules/sharp
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by jiivonen** [comment]
I noticed that my node-gyp was very old and updated that to 1.0.2 just in case, but with no help.

**Comment by lovell** [comment]
Hi Joonas, if you're using the `gcc` compiler then [v4.6+ is required](https://github.com/lovell/sharp#prerequisites). I think Centos 6 provides v4.4.

Perhaps try the "dev toolset" http://superuser.com/questions/381160/how-to-install-gcc-4-7-x-4-8-x-on-centos/542091#542091

**Comment by jiivonen** [comment]
Excellent! Thanks for the fast reply.

Updating gcc to 4.7 solved this.

**Comment by brianviveiros** [comment]
Hi guys, I'm receiving the same compiler error on CenOS 6.6 using gcc 4.8.2.

Any other ideas?

**Comment by lovell** [comment]
@brianviveiros The `utilities.cc:99: error: expected initializer before ‘:’ token` error is the C++ compiler's way of saying it can't handle the use of a "range-based for loop".

Support for this feature was added in [gcc 4.6](https://gcc.gnu.org/gcc-4.6/changes.html#cplusplus).

Could something have set the `CXX` environment variable to override the version you think is in use?

**Comment by brianviveiros** [comment]
Perfect, that was it!

I followed the install instructions for devtools-2 but didn't export the environment variables.

Thanks!
