### ISSUE TITLE
Install sharp on windows32

### ISSUE THREAD

**Issue by haoxl3** [lovell/sharp#1785]
My project had to make windows32 support sharp, but I installed times incorrectly.
```javascript
Windows x86 (32-bit) node.exe is not supported
```
I have found the answer [#379](https://github.com/lovell/sharp/issues/379), But the download `vips-dev.x.y.z.zip` link  could not be found. So what do I do? Thank you

my node version: v10.16.0

**Comment by lovell** [comment]
Sorry, I cannot provide any support for 32-bit Windows - good luck!
