### ISSUE TITLE
GLib-CRITICAL **: 23:16:35.944: g_hash_table_lookup: assertion 'hash_table != NULL' failed #1709

### ISSUE THREAD

**Issue by jlin95** [lovell/sharp#1786]
Using gatsby-image 2.2.4 while doing a local production build (gatsby build). I am querying the images of different sizes (3 to be specific: desktop, tablet, mobile).

**Comment by lovell** [comment]
Hi, I notice you cross-posted this (and copied the title from) #1709 - the information in comment https://github.com/lovell/sharp/issues/1709#issuecomment-494045273 remains the same.

**Comment by bpicolo** [comment]
#1709 is locked, but wanted to put this context here for someone else that might hit this.

I had libvips installed via homebrew @ 8.8.0. Uninstalling my homebrew libvips corrected this error.
