### ISSUE TITLE
Flatten doesn't seem to be respecting background color

### ISSUE THREAD

**Issue by GimpMaster** [lovell/sharp#1787]
Hello, I have a PNG that has a transparent image. I'll try attaching it.  I want to resize and convert to JPEG but the transparent portion, no matter what I try, reverts to black. Hopefully its something I'm doing. See the Code below.

`
await sharp(finalImages.orig).flatten({ r: 255, g: 255, b: 0 }).resize({ width: imageSizes[i].width }).jpeg({ progressive: true }).toFile(destinationFilePath);
`

Thanks!

![ghost](https://user-images.githubusercontent.com/7818200/60924748-3073d080-a25f-11e9-8ba6-ea8c9258967b.png)

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/en/stable/api-operation/#flatten

```diff
- .flatten({ r: 255, g: 255, b: 0 })
+ .flatten({ background: { r: 255, g: 255, b: 0 }})
```

**Comment by GimpMaster** [comment]
Thank you Lovell. I knew I was missing something.
