### ISSUE TITLE
Using newer libvips 

### ISSUE THREAD

**Issue by PetrSnobelt** [lovell/sharp#1795]
What are you trying to achieve?
Try to use newer libvips with older version of sharp

Have you searched for similar questions?
Yes

Are you able to provide a standalone code sample that demonstrates this question?
add config to package.json
```
"config": {
    "libvips": "8.7.4"
  },
```
and set environment variable 
`SHARP_DIST_BASE_URL=https://github.com/avishnyak/sharp-libvips/releases/download/v8.7.4/`

But after this settings sharp still try download old version tar from 
https://github.com/avishnyak/sharp-libvips/releases/download/v8.7.4/libvips-8.7.0-linux-x64.tar.gz

**Comment by lovell** [comment]
> add config to package.json

This needs to be sharp's `package.json`. This approach is unsupported so you're on your own here - good luck!

**Comment by PetrSnobelt** [comment]
OK, I thought it could be possible - according to http://sharp.pixelplumbing.com/en/stable/install/#linux

"This allows the use of newer versions of libvips with older versions of sharp."

**Comment by lovell** [comment]
My use of "unsupported" in this context refers to me being unable to provide any help to those using third-party binaries.

At `npm install` time, sharp will always look for a globally-installed libvips. Alternatively, as you're doing, you can provide your own tarballs by setting `SHARP_DIST_BASE_URL` and/or patching the contents of sharp's `package.json`.
