### ISSUE TITLE
Output: Tile with google layout. 

### ISSUE THREAD

**Issue by Moser2010** [lovell/sharp#1796]
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 1.63 GB / 7.85 GB
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

![mapIssue](https://user-images.githubusercontent.com/14005608/61491929-edf47700-a975-11e9-9e8a-3bf661929d1b.PNG)

Here is the issue. I am using Leaflet.js for mapping. I have in the past used a script from photoshop to tile an image into the google pyramid structure. I have then made this map show up on the page correctly. I am now trying to use Sharp to do the same thing with other images and make other maps but what I am finding is that when I run the command for some reason it seems to be swapping the the top right corner of the map and the bottom left corner of the map and is putting them in the wrong x cordinate folder.

I am using the tile.layout "google" to do so.

Here is my code
```
//Sharp Calls
sharp("Public/Campaigns/" + map)
    .resize({
        width: 4096,
        fit: "fill",
        position: "centre"
    })
        .png()
        .tile({
            size: 256,
            depth: "onetile",
            container: "fs",
            layout: "google"

        })
        .toFile('Public/Campaigns/' + cName + "/map.jpg", (err, info) => {
            if (err) {
                console.log(err);

            }
            console.log(info);
            
        })
    //Process the map


}
//Leaflet.js map creation
var mymap = L.map('map', {
    zoomControl: false,
    attributionControl: false,
}).setView([0, 0], 0);
L.tileLayer('../../Campaigns/test/map.jpg/{z}/{x}/{y}.png', {
    minZoom: 0,
    maxZoom: 13,
    crossOrigin: true,
    continuousWorld: false,
    noWrap: true,
    bounds: bounds
}).addTo(mymap);
L.control.zoom({
    position: 'topleft'
}).addTo(mymap);
```

I know that my other map still works because I can pull it in and render it and it works. I also know that my css and js is working for Leaflet.js

What I am wondering is if the output file structure specifically for google is correct or if this is an error. What can I do to fix this. Please help.

**Comment by lovell** [comment]
Hi, the `tile()` operation in sharp is a (very) thin wrapper around libvips' [dzsave](https://libvips.github.io/libvips/API/current/VipsForeignSave.html#vips-dzsave) operation.

Are you able to reproduce this using `vips` at the command line?

Are you able to provide a sample input image that exhibits this behaviour?

**Comment by Moser2010** [comment]
![D_D_-_4th_Edition_-_Eberron_Map_Khorvaire](https://user-images.githubusercontent.com/14005608/61569258-2a92a200-aa4c-11e9-92c8-45d408c49c57.jpg)


Here is one of the images that I tried. Ill be honest I am having a heck of a time getting libvips to install on my windows machine. I will keep trying and test what you have asked from the command line if I can.

**Comment by Moser2010** [comment]
Okay I have gotten vips installed and can run the exe from the command line. I can not seem to find the correct command line command to tile the image. Can you point me in the right direction?

**Comment by Moser2010** [comment]
nvm I found the docs

**Comment by Moser2010** [comment]
Update: So it looks like tile() in Sharp is behaving the exact same way that libvips does when I run the following command. vips dzsave inputfile.jpg outputfile.jpg --layout google --centre

It laysout the pyramid folder structure the same way.  That said I know that this is not a leaflet issue or a google maps issue as I tried displaying the map pyramid outputs in both of those and I get the same results. I believe that it has something with how the file outputs are being structured in each folder. I am not convinced that this is an issue with Sharp at this time since you are just "wrapping" around the libvips command. I think that this is a libvips bug potentially and only a bug with the google map pyramid.

Thank you for your help.

**Comment by jcupitt** [comment]
Hello, libvips names tiles in google layout as `z/y/x.jpg`, ie. zoom-level / row-number / column-number. This is the usual google maps layout. It looks like your leaflet has been configured to load tiles as `z/x/y.jpg`. 

There's a JS function you give to leaflet to generate the URL for fetching tiles. Just override that to swap x and y.

**Comment by jcupitt** [comment]
If you're not doing this already, I would generate tiles to a zip container. At the command-line, it's:

```
vips dzsave my-huhe-map.png my-tiles.zip --layout google --centre
```

Windows is extremely slow at file creation, so making 1000s of tiny tile files just crawls. You'll find generating a single zip file gives you a ~3x speedup, plus the zip is simpler to copy around, of course. 

You can even serve tiles directly from the zip and never bother to unzip it. Replace the load-tile function you give leaflet with something to fetch the zip directory and read just the part you need.

**Comment by Moser2010** [comment]
@jcupitt I don't know a lot about libvips is there a way in the code, so not in the command line, to run the dzsave function? I want to build this to be automated as much as possible for the CMS I am building.

**Comment by jcupitt** [comment]
Sure, just use `tile()`. You'd need to check the docs to see how to make a zip.

**Comment by Moser2010** [comment]
Okay I did what you first suggested. Thank you so much. I don't know how me and my team missed that. You are amazing. This ticket can be closed. Hopefully this will help someone in the future as well. You guys are great!
