### ISSUE TITLE
Trim operation removes surrounding transparency and black colour

### ISSUE THREAD

**Issue by Lxstr** [lovell/sharp#1797]
What is the output of running `npx envinfo --binaries --languages --system --utilities`?

  System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz
    Memory: 103.23 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 10.14. - /usr/bin/gcc
    Git: 2.15.1 - /usr/local/bin/git
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: javac 10 - /usr/bin/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.3.5 - /usr/bin/php
    Python: 3.7.1 - /Users//anaconda3/bin/python
    Ruby: 2.5.1 - /Users//.rbenv/shims/ruby

What are the steps to reproduce?

Use trim operation (with threshold 1) on image with surrounding transparency. Black is the next colour in from the edge.

What is the expected behaviour?

Only the transparency (alpha 0) should be trimmed. The black colour should remain.

Actual behaviour?

Transparency and the black is removed.

Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?

If required.

Are you able to provide a sample image that helps explain the problem?

Attached input and output images.

![input](https://user-images.githubusercontent.com/15979196/61517198-08982000-aa4a-11e9-8366-5e5ac3a20466.png)
![output](https://user-images.githubusercontent.com/15979196/61517199-08982000-aa4a-11e9-8685-703865eeb6f9.png)

Initial feature request:
https://github.com/lovell/sharp/issues/491

**Comment by lovell** [comment]
Please can you provide a complete, standalone code sample that exhibits this behaviour.

**Comment by Lxstr** [comment]
Standalone example:
git@github.com:Lxstr/sharp-issue-1797.git
[https://github.com/Lxstr/sharp-issue-1797](url)
😃
In short...
`sharp('input.png').trim(1).toFile('output.png', function (err) {
	console.log(err);
});`

**Comment by lovell** [comment]
Thank you, this looks like the same problem as #1597 as the image is flattened to black before the trim but should flatten to the value of the `bKGD` chunk, in this case white.

**Comment by Lxstr** [comment]
Yes apologies, after reading through it seems this is a duplicate of that issue. 

Regarding the suggested solution, would flattening to white cause issues if the outline of the image was white instead? Is there any way it could be trimmed without flattening the alpha channel and simply recognise the alpha as a legitimate colour channel in it's own right?

I've had a brief look but can't understand the C.

**Comment by lovell** [comment]
Including the alpha channel in the trim operation would involve a change to libvips.

**Comment by lovell** [comment]
Let's track this at #1597
