### ISSUE TITLE
SVG change color

### ISSUE THREAD

**Issue by LuigiMaestrelli** [lovell/sharp#1798]
I'm trying to change a SVG file color and export the result to png.
The original color is black.
And when I try to tint the file to #ff0000 looks like the colors are merged and the result is darker.

`
await sharp(pathToFile).resize(512, 512).tint('#ff0000').png().toFile(outputFile);
`

Is it possible to achieve? 

I attached the original and the file with new color.
The red is not supposed to be that dark.

![original](https://user-images.githubusercontent.com/5038871/61572006-8c640380-aa6e-11e9-9807-678377f51d3a.png)
![result](https://user-images.githubusercontent.com/5038871/61572007-8cfc9a00-aa6e-11e9-9f2f-8607546b8062.png)

**Comment by lovell** [comment]
That looks like the expected output of tint.
https://sharp.pixelplumbing.com/en/stable/api-colour/#tint

Did you see the `modulate` operation, specifically its `hue` option?
https://sharp.pixelplumbing.com/en/stable/api-operation/#modulate

**Comment by LuigiMaestrelli** [comment]
Thanks for the response.

Will it work with unknown input and output color?

Red and black are just examples, the routine will not known the origin file color and the output color is set by the user.

**Comment by lovell** [comment]
Another possible alternative might be to change the fill colour in the source SVG.

**Comment by LuigiMaestrelli** [comment]
Thank you.
I solved changing the color before doing any resize and export with sharp.
