### ISSUE TITLE
Should I add a version number in SHARP_DIST_BASE_URL ?

### ISSUE THREAD

**Issue by tomoat** [lovell/sharp#1799]
https://github.com/lovell/sharp/blob/master/install/libvips.js#L19

Should I add a version number here?

```js
const distBaseUrl = `process.env.npm_config_sharp_dist_base_url/v${minimumLibvipsVersion}/` || `process.env.SHARP_DIST_BASE_URL/v${minimumLibvipsVersion}/` || `https://github.com/lovell/sharp-libvips/releases/download/v${minimumLibvipsVersion}/`;
```

**Comment by tomoat** [comment]
I can't change variables every time I upgrade，It's very cumbersome
```sh
export SHARP_DIST_BASE_URL="https://npm.taobao.org/mirrors/sharp-libvips/v8.7.4/"

```

**Comment by lovell** [comment]
Hi, I don't maintain `npm.taobao.org` so you'll need to speak to someone who does and ask them to remove version numbers if that's causing a problem.

**Comment by tomoat** [comment]
I don't think this has much to do with `npm.taobao.org`, because that's what the node lib file should look like

But the directory path for the extra version number should not be fixed because it is a variable

**Comment by lovell** [comment]
> because that's what the node lib file should look like

The files hosted at https://npm.taobao.org/mirrors/... appear to be unrelated to npm and are instead mirroring various sites and software, including some originally hosted by GitHub releases (and presumably harder to access inside mainland China) such as the prebuilt binaries for libvips that are used by sharp.

Have you asked the maintainers of that mirror? What did they say?

The prebuilt libvips binaries are provided to help most of the people most of the time. At install time, sharp will always look for and, if found, use a global libvips, which might be a more appropriate solution for your situation.

https://sharp.pixelplumbing.com/en/stable/install/#pre-compiled-libvips-binaries

**Comment by TheBegining** [comment]
You can use SHARP_DIST_BASE_URL=https://npm.taobao.org/mirrors/sharp-libvips with out specify a version.
