### ISSUE TITLE
I spend whole days to install sharp. Please help me!

### ISSUE THREAD

**Issue by Fogrunner** [lovell/sharp#1801]
What is the output of running `npm install --verbose sharp`?

[root@ip-172-31-30-243 ec2-user]# npm install sharp

> sharp@0.22.1 install /home/ec2-user/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

/home/ec2-user/node_modules/simple-get/index.js:18
    const { hostname, port, protocol, auth, path } = url.parse(opts.url)
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ec2-user/node_modules/sharp/install/libvips.js:10:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
sh: node-gyp: command not found
npm WARN ec2-user@1.0.0 No description
npm WARN ec2-user@1.0.0 No repository field.

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the sharp@0.22.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-22T19_38_49_581Z-debug.log

What is the output of running `npx envinfo --binaries --languages --system --utilities`?

  System:
    OS: Linux 4.14 Amazon Linux AMI 2018.03
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
    Memory: 219.01 MB / 959.51 MB
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
    npm: 6.10.1 - ~/.nvm/versions/node/v8.10.0/bin/npm
  Utilities:
    CMake: 2.8.12.2 - /usr/bin/cmake
    Make: 3.82 - /usr/bin/make
    GCC: 4.8.5 - /usr/bin/gcc
    Git: 2.14.5 - /usr/bin/git
  Servers:
    Apache: 2.4.39 - /usr/sbin/apachectl
  IDEs:
    Nano: 2.5.3 - /bin/nano
    Vim: 8.0 - /usr/bin/vim
  Languages:
    Bash: 4.2.46 - /bin/bash
    Perl: 5.16.3 - /usr/bin/perl
    PHP: 7.0.33 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Ruby: 2.0.0 - /usr/bin/ruby
  Databases:
    MySQL: 10.1.40 (MariaDB) - /usr/bin/mysql
    SQLite: 3.7.17 - /usr/bin/sqlite3

Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime?

[root@ip-172-31-30-243 ec2-user]# node -v
v8.10.0

[root@ip-172-31-30-243 ec2-user]# npm -v
6.10.1

**Comment by lovell** [comment]
The `SyntaxError: Unexpected token {` message suggests Node.js 4 or earlier is being used at install time so there are probably multiple, conflicting versions of Node.js on this machine.
