### ISSUE TITLE
Watermark

### ISSUE THREAD

**Issue by guiOLVR** [lovell/sharp#1804]
I trying input watermark in a picture like:
```
let sharp = require('sharp');
    let buffer = null;

    await sharp('./image.png')
        .composite([{ input: './logo.png', gravity: 'center' }])
        .sharpen()
        .withMetadata()
        .toBuffer()
        .then(function(outputBuffer) {
            // outputBuffer contains upside down, 300px wide, alpha channel flattened
            // onto orange background, composited with overlay.png with SE gravity,
            // sharpened, with metadata, 90% quality WebP image data. Phew!
            buffer = outputBuffer;
        });
    return buffer;
```

*This image just for test*
![31936580_1645504498859536_6987626660598120448_n](https://user-images.githubusercontent.com/16414250/61740249-86b73800-ad64-11e9-80f4-7af89b32de91.jpg)

But i want that logo have opacity like 30%, how can i do this?

**Comment by lovell** [comment]
Hi, you'll need to modify the alpha channel of `logo.png` first. To achieve this via sharp you'll need the future possible enhancement detailed in #618, which includes an alternative workaround via *magick.

**Comment by guiOLVR** [comment]
Thanks for your answer, i'm use Canvas to change image opacity:

```
   const Canvas = require('canvas');
   let canvas = Canvas.createCanvas(800, 800);
    let ctx = canvas.getContext('2d');

    await Canvas.loadImage('logo.png').then((logo) => {
        ctx.globalAlpha = 0.5;
        ctx.drawImage(logo, 10, 10);
    });
    //console.log(canvas.toBuffer());
    //canvas.createPNGStream().pipe(fs.createWriteStream(path.join(__dirname, 'globalAlpha.png')))
    let buff = canvas.toBuffer();
```

But when i try to composite using sharp, he give me an error like that:

`Error: Expected `from` parameter to be a Buffer, Stream, or a String`

The code:

```
await sharp(image)
        .composite([{ input: buff, gravity: 'northwest' }])
        .sharpen()
        .withMetadata()
        .toBuffer()
        .then(function(outputBuffer) {
            buffer = outputBuffer;
        })
        .catch(error => {
            console.log(error);
        });
```

**Comment by lovell** [comment]
I notice you've cross-posted this at https://github.com/Automattic/node-canvas/issues/1463 without linking to this issue; please don't do that.

**Comment by guiOLVR** [comment]
@lovell
Sorry about that.
