### ISSUE TITLE
Install on secure server without internet access

### ISSUE THREAD

**Issue by gilly3** [lovell/sharp#1805]
Is it possible to install sharp on a server without internet access?  My server has access to a private npm registry, but not to github.com.  I have added sharp as a project dependency, and when I go to install my project on my secure server, it always attempts to download libvips.  This, even when I specify:

```bash
$ npm i --build-from-source myPackage
```

It hangs on:

```
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-linux-x64.tar.gz
```

It's not surprising that it hangs, since the server is isolated from the web.  But, I thought that installing myPackage (which depends on sharp) with `--build-from-source` would cause it to skip that step.

I think I prefer to build from source, but alternatively I can set up a mirror to download whatever is required from within my network, if there is a setting that allows specifying a download mirror.

**Comment by lovell** [comment]
Hi, if you'd prefer to build from source, you'll need to make sure a recent-enough version of libvips is globally installed so it can be found by sharp at `npm install` time.

https://sharp.pixelplumbing.com/en/stable/install/#pre-compiled-libvips-binaries

**Comment by mesonoxian** [comment]
We are also facing the same situation, After adding **SHARP_DIST_BASE_URL** for the Pre-compiled libvips binaries, We still see connection timeout error for Github request. 

Further debugging, We figured that prebuild-install try's to download **sharp-v0.22.1=node-v64-linyxmusl-x64.tar.gz** and fails. Is there a setting that allows specifying a download mirror for sharp binary also?

**Comment by lovell** [comment]
@mesonoxian https://github.com/prebuild/prebuild-install#custom-binaries

**Comment by Ivaylo-Lafchiev** [comment]
Yep that's exactly what I'm looking for. I suggest adding this to the installation docs. Thanks.
