### ISSUE TITLE
TypeError: sharp.format is not a function

### ISSUE THREAD

**Issue by zbisj** [lovell/sharp#1807]
What is the output of running `npx envinfo --binaries --languages --system --utilities`?

System:
    **OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 1.72 GB / 11.59 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash**
  Binaries:
    **Node: 11.10.1 - ~/.nvm/versions/node/v11.10.1/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v11.10.1/bin/npm**
  Utilities:
    **Make: 4.2.1 - /usr/bin/make
    GCC: 8.3.0 - /usr/bin/gcc
    Git: 2.20.1 - /usr/bin/git**
  Languages:
    **Bash: 5.0.3 - /usr/bin/bash
    Java: 11.0.3 - /usr/bin/javac
    Perl: 5.28.1 - /usr/bin/perl
    Python: 2.7.16 - /usr/bin/python**

What are the steps to reproduce?
`npx create-react-app sharp-example`
`cd sharp-axample`
`yarn add sharp`
`yarn start`
inside of `App.js` write `const sharp = require('sharp');`

What is the expected behaviour?

**The biolerplate app or create-react-app should display** 

Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?

[here a test repo: sharp-example](https://github.com/zbisj/sharp-example.git)

Are you able to provide a sample image that helps explain the problem?
![sharp-example-img](https://user-images.githubusercontent.com/22472288/61910231-532b0800-af34-11e9-818a-25dc03d01c86.png)

**Comment by lovell** [comment]
This module requires the Node.js runtime and will not work in a browser.

**Comment by paddotk** [comment]
I've got the same issue when trying to read a file; within Electron (which runs on Node). I'm not calling the `.format()` function or anything.

```
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 9.09 GB / 15.89 GB
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.10.1 - C:\Users\tjard\AppData\Roaming\npm\npm.CMD
```
