### ISSUE TITLE
Error: Input buffer contains unsupported image format on composite

### ISSUE THREAD

**Issue by susannaHayrapetyan** [lovell/sharp#1808]
Hi
I have created a function which gets an image buffer(jpeg, png...).
It should resize images and depending from options also make them circle.
The code is working on my local machine.
It's also working on the server without circle block, but getting following error on the server for circle images:
` Error: Input buffer contains unsupported image format `
Can you please help me? Is it happening because of some packages versions difference?

```
const sharp = require('sharp');

module.exports = async function (image, options) {
    let img = sharp(image);
    const imgInfo = await img.metadata();
    let format = options.format || imgInfo.format;

    if (options.circle) {
        const circle = new Buffer(
            `<svg style="background-color: white">
                <circle cy="${options.height / 2}" cx="${options.width / 2}" r="${options.width / 2}" />
            </svg>`
        );

        format = 'png';
        img.composite([{ input: circle, blend: 'dest-in' }]);
    }

    switch (format) {
        case 'png':
            img = img.png({ quality: options.quality || 100 });
            break;
        default:
            img = img.jpeg({ quality: options.quality || 100 });
    }

    return img
        .resize(options.width, options.height)
        .toBuffer();
};
```

**Comment by lovell** [comment]
The output of `console.log(sharp.format)` will tell you which image formats are supported at runtime.

If you're using the prebuilt binaries these include librsvg. If you're relying on a globally-installed libvips this may be different.

**Comment by susannaHayrapetyan** [comment]
@lovell thank you, works now :)
