### ISSUE TITLE
Strange cropping issue

### ISSUE THREAD

**Issue by XenXenOfficial** [lovell/sharp#1809]
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 19.85 GB / 31.87 GB
  Binaries:
    Node: 10.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Bash: 4.3.48 - C:\Windows\system32\bash.EXE
    Perl: 5.28.0 - C:\Strawberry\perl\bin\perl.EXE
    PHP: 7.2.10 - C:\xampp\php\php.EXE
    Python: 3.6.0
    Ruby: 2.6.1 - C:\Ruby26-x64\bin\ruby.EXE

What are the steps to reproduce?
>1. Install sharp
>2. Process an jpg image to a buffer
>3. Convert to png, resize, then toFile.

What is the expected behaviour?
To properly resize the image according to the given width and height values.

Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?
```js
const sharp = require('sharp');

const process = async _=>{
    let buffer = require('fs').readFileSync('otter.jpg',_=>console.log(_));
    let image = sharp(buffer);
    await image.png()
               .resize({width:200, height:500})
               .toFile('otterNew2.jpg');
}
process()
```
Are you able to provide a sample image that helps explain the problem?

https://imgur.com/a/4tP9xOM

Quick little album post showing a 200x500 and a 500x200 resolution images, original is 668x576.

Seems to be referenced here: https://github.com/lovell/sharp/issues/29

**Comment by lovell** [comment]
Hi, did you see the docs for the `resize` operation, including the `fit` option? https://sharp.pixelplumbing.com/en/stable/api-resize/#resize

Those output images appear as I'd expect for the default `fit` value of `cover`.

**Comment by XenXenOfficial** [comment]
Hey! I didn't, but I'll definitely take a look! Thank you.

**Comment by XenXenOfficial** [comment]
Working as expected! Thanks for the help and sorry for the delay!
