### ISSUE TITLE
Failed at the sharp@0.22.1 install script.

### ISSUE THREAD

**Issue by ljvillarrealm** [lovell/sharp#1812]
1) What is the output of running `npm install --verbose sharp`?
$ sudo npm i -g sharp --verbose

npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', 'i', '-g', 'sharp', '--verbose' ]
npm info using npm@6.9.0
npm info using node@v12.3.1
npm verb npm-session 9826799c0862e583
npm http fetch GET 304 https://registry.npmjs.org/sharp 921ms (from cache)
npm timing stage:loadCurrentTree Completed in 957ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
npm http fetch GET 304 https://registry.npmjs.org/color 102ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/prebuild-install 253ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/detect-libc 264ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/nan 262ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/npmlog 263ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/semver 265ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tunnel-agent 265ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-get 271ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar 272ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-copy-file-sync 803ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-convert 80ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-string 82ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-name 87ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-swizzle 66ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-arrayish 76ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/gauge 97ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/set-blocking 101ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/console-control-strings 103ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/are-we-there-yet 104ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/readable-stream 89ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/delegates 93ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/core-util-is 80ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/isarray 91ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/inherits 121ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/string_decoder 120ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/process-nextick-args 122ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/safe-buffer 123ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/util-deprecate 359ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/string-width 94ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/object-assign 96ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/signal-exit 98ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/aproba 110ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/has-unicode 345ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/strip-ansi 345ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/wide-align 358ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-fullwidth-code-point 80ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/code-point-at 83ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/number-is-nan 339ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ansi-regex 95ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minimist 137ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mkdirp 138ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/expand-template 140ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/noop-logger 141ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/os-homedir 141ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/github-from-package 146ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/pump 150ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-abi 151ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/rc 150ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/napi-build-utils 157ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/which-pm-runs 72ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-fs 83ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/end-of-stream 78ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/once 80ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/wrappy 318ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/deep-extend 78ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ini 85ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/strip-json-comments 100ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 66ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-concat 338ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mimic-response 81ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-stream 88ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/chownr 91ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/to-buffer 87ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bl 90ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-constants 92ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/buffer-alloc 94ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/xtend 94ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/buffer-fill 64ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/buffer-alloc-unsafe 76ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/yallist 99ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minizlib 102ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-minipass 104ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minipass 107ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 4214ms
npm timing stage:loadIdealTree Completed in 4256ms
npm timing stage:generateActionsToTake Completed in 25ms
npm verb correctMkdir /home/USER/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/USER/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
npm timing action:extract Completed in 358ms
npm timing action:finalize Completed in 115ms
npm timing action:refresh-package-json Completed in 166ms
npm info lifecycle ansi-regex@2.1.1~preinstall: ansi-regex@2.1.1
npm info lifecycle aproba@1.2.0~preinstall: aproba@1.2.0
npm info lifecycle buffer-alloc-unsafe@1.1.0~preinstall: buffer-alloc-unsafe@1.1.0
npm info lifecycle buffer-fill@1.0.0~preinstall: buffer-fill@1.0.0
npm info lifecycle buffer-alloc@1.2.0~preinstall: buffer-alloc@1.2.0
npm info lifecycle chownr@1.1.2~preinstall: chownr@1.1.2
npm info lifecycle code-point-at@1.1.0~preinstall: code-point-at@1.1.0
npm info lifecycle color-name@1.1.3~preinstall: color-name@1.1.3
npm info lifecycle color-convert@1.9.3~preinstall: color-convert@1.9.3
npm info lifecycle console-control-strings@1.1.0~preinstall: console-control-strings@1.1.0
npm info lifecycle core-util-is@1.0.2~preinstall: core-util-is@1.0.2
npm info lifecycle deep-extend@0.6.0~preinstall: deep-extend@0.6.0
npm info lifecycle delegates@1.0.0~preinstall: delegates@1.0.0
npm info lifecycle detect-libc@1.0.3~preinstall: detect-libc@1.0.3
npm info lifecycle expand-template@2.0.3~preinstall: expand-template@2.0.3
npm info lifecycle fs-constants@1.0.0~preinstall: fs-constants@1.0.0
npm info lifecycle github-from-package@0.0.0~preinstall: github-from-package@0.0.0
npm info lifecycle has-unicode@2.0.1~preinstall: has-unicode@2.0.1
npm info lifecycle inherits@2.0.4~preinstall: inherits@2.0.4
npm info lifecycle ini@1.3.5~preinstall: ini@1.3.5
npm info lifecycle is-arrayish@0.3.2~preinstall: is-arrayish@0.3.2
npm info lifecycle isarray@1.0.0~preinstall: isarray@1.0.0
npm info lifecycle mimic-response@1.0.1~preinstall: mimic-response@1.0.1
npm info lifecycle decompress-response@3.3.0~preinstall: decompress-response@3.3.0
npm info lifecycle minimist@1.2.0~preinstall: minimist@1.2.0
npm info lifecycle minimist@0.0.8~preinstall: minimist@0.0.8
npm info lifecycle mkdirp@0.5.1~preinstall: mkdirp@0.5.1
npm info lifecycle napi-build-utils@1.0.1~preinstall: napi-build-utils@1.0.1
npm info lifecycle semver@5.7.0~preinstall: semver@5.7.0
npm info lifecycle node-abi@2.9.0~preinstall: node-abi@2.9.0
npm info lifecycle noop-logger@0.1.1~preinstall: noop-logger@0.1.1
npm info lifecycle number-is-nan@1.0.1~preinstall: number-is-nan@1.0.1
npm info lifecycle is-fullwidth-code-point@1.0.0~preinstall: is-fullwidth-code-point@1.0.0
npm info lifecycle object-assign@4.1.1~preinstall: object-assign@4.1.1
npm info lifecycle os-homedir@1.0.2~preinstall: os-homedir@1.0.2
npm info lifecycle process-nextick-args@2.0.1~preinstall: process-nextick-args@2.0.1
npm info lifecycle safe-buffer@5.1.2~preinstall: safe-buffer@5.1.2
npm info lifecycle set-blocking@2.0.0~preinstall: set-blocking@2.0.0
npm info lifecycle signal-exit@3.0.2~preinstall: signal-exit@3.0.2
npm info lifecycle simple-concat@1.0.0~preinstall: simple-concat@1.0.0
npm info lifecycle simple-swizzle@0.2.2~preinstall: simple-swizzle@0.2.2
npm info lifecycle color-string@1.5.3~preinstall: color-string@1.5.3
npm info lifecycle string_decoder@1.1.1~preinstall: string_decoder@1.1.1
npm info lifecycle strip-ansi@3.0.1~preinstall: strip-ansi@3.0.1
npm info lifecycle string-width@1.0.2~preinstall: string-width@1.0.2
npm info lifecycle strip-json-comments@2.0.1~preinstall: strip-json-comments@2.0.1
npm info lifecycle rc@1.2.8~preinstall: rc@1.2.8
npm info lifecycle to-buffer@1.1.1~preinstall: to-buffer@1.1.1
npm info lifecycle tunnel-agent@0.6.0~preinstall: tunnel-agent@0.6.0
npm info lifecycle util-deprecate@1.0.2~preinstall: util-deprecate@1.0.2
npm info lifecycle sharp@0.22.1~preinstall: sharp@0.22.1
npm info lifecycle tar@4.4.10~preinstall: tar@4.4.10
npm info lifecycle simple-get@3.0.3~preinstall: simple-get@3.0.3
npm info lifecycle semver@6.3.0~preinstall: semver@6.3.0
npm info lifecycle prebuild-install@5.3.0~preinstall: prebuild-install@5.3.0
npm info lifecycle nan@2.14.0~preinstall: nan@2.14.0
npm info lifecycle fs-copy-file-sync@1.1.1~preinstall: fs-copy-file-sync@1.1.1
npm info lifecycle color@3.1.2~preinstall: color@3.1.2
npm info lifecycle minizlib@1.2.1~preinstall: minizlib@1.2.1
npm info lifecycle fs-minipass@1.2.6~preinstall: fs-minipass@1.2.6
npm info lifecycle minipass@2.3.5~preinstall: minipass@2.3.5
npm info lifecycle yallist@3.0.3~preinstall: yallist@3.0.3
npm info lifecycle tar-fs@1.16.3~preinstall: tar-fs@1.16.3
npm info lifecycle tar-stream@1.6.2~preinstall: tar-stream@1.6.2
npm info lifecycle xtend@4.0.2~preinstall: xtend@4.0.2
npm info lifecycle pump@1.0.3~preinstall: pump@1.0.3
npm info lifecycle pump@2.0.1~preinstall: pump@2.0.1
npm info lifecycle simple-get@2.8.1~preinstall: simple-get@2.8.1
npm info lifecycle end-of-stream@1.4.1~preinstall: end-of-stream@1.4.1
npm info lifecycle once@1.4.0~preinstall: once@1.4.0
npm info lifecycle wrappy@1.0.2~preinstall: wrappy@1.0.2
npm info lifecycle npmlog@4.1.2~preinstall: npmlog@4.1.2
npm info lifecycle gauge@2.7.4~preinstall: gauge@2.7.4
npm info lifecycle wide-align@1.1.3~preinstall: wide-align@1.1.3
npm info lifecycle which-pm-runs@1.0.0~preinstall: which-pm-runs@1.0.0
npm info lifecycle bl@1.2.2~preinstall: bl@1.2.2
npm info lifecycle are-we-there-yet@1.1.5~preinstall: are-we-there-yet@1.1.5
npm info lifecycle readable-stream@2.3.6~preinstall: readable-stream@2.3.6
npm timing action:preinstall Completed in 29ms
npm info linkStuff ansi-regex@2.1.1
npm info linkStuff aproba@1.2.0
npm info linkStuff buffer-alloc-unsafe@1.1.0
npm info linkStuff buffer-fill@1.0.0
npm info linkStuff buffer-alloc@1.2.0
npm info linkStuff chownr@1.1.2
npm info linkStuff code-point-at@1.1.0
npm info linkStuff color-name@1.1.3
npm info linkStuff color-convert@1.9.3
npm info linkStuff console-control-strings@1.1.0
npm info linkStuff core-util-is@1.0.2
npm info linkStuff deep-extend@0.6.0
npm info linkStuff delegates@1.0.0
npm info linkStuff detect-libc@1.0.3
npm verb linkBins [
npm verb linkBins   { 'detect-libc': './bin/detect-libc.js' },
npm verb linkBins   '/usr/lib/node_modules/sharp/node_modules/.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff expand-template@2.0.3
npm info linkStuff fs-constants@1.0.0
npm info linkStuff github-from-package@0.0.0
npm info linkStuff has-unicode@2.0.1
npm info linkStuff inherits@2.0.4
npm info linkStuff ini@1.3.5
npm info linkStuff is-arrayish@0.3.2
npm info linkStuff isarray@1.0.0
npm info linkStuff mimic-response@1.0.1
npm info linkStuff decompress-response@3.3.0
npm info linkStuff minimist@1.2.0
npm info linkStuff minimist@0.0.8
npm info linkStuff mkdirp@0.5.1
npm verb linkBins [
npm verb linkBins   { mkdirp: 'bin/cmd.js' },
npm verb linkBins   '/usr/lib/node_modules/sharp/node_modules/.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff napi-build-utils@1.0.1
npm info linkStuff semver@5.7.0
npm verb linkBins [
npm verb linkBins   { semver: './bin/semver' },
npm verb linkBins   '/usr/lib/node_modules/sharp/node_modules/node-abi/node_modules/.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff node-abi@2.9.0
npm info linkStuff noop-logger@0.1.1
npm info linkStuff number-is-nan@1.0.1
npm info linkStuff is-fullwidth-code-point@1.0.0
npm info linkStuff object-assign@4.1.1
npm info linkStuff os-homedir@1.0.2
npm info linkStuff process-nextick-args@2.0.1
npm info linkStuff safe-buffer@5.1.2
npm info linkStuff set-blocking@2.0.0
npm info linkStuff signal-exit@3.0.2
npm info linkStuff simple-concat@1.0.0
npm info linkStuff simple-swizzle@0.2.2
npm info linkStuff color-string@1.5.3
npm info linkStuff string_decoder@1.1.1
npm info linkStuff strip-ansi@3.0.1
npm info linkStuff string-width@1.0.2
npm info linkStuff strip-json-comments@2.0.1
npm info linkStuff rc@1.2.8
npm verb linkBins [
npm verb linkBins   { rc: './cli.js' },
npm verb linkBins   '/usr/lib/node_modules/sharp/node_modules/.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff to-buffer@1.1.1
npm info linkStuff tunnel-agent@0.6.0
npm info linkStuff util-deprecate@1.0.2
npm info linkStuff readable-stream@2.3.6
npm info linkStuff are-we-there-yet@1.1.5
npm info linkStuff bl@1.2.2
npm info linkStuff which-pm-runs@1.0.0
npm info linkStuff wide-align@1.1.3
npm info linkStuff gauge@2.7.4
npm info linkStuff npmlog@4.1.2
npm info linkStuff wrappy@1.0.2
npm info linkStuff once@1.4.0
npm info linkStuff end-of-stream@1.4.1
npm info linkStuff simple-get@2.8.1
npm info linkStuff pump@2.0.1
npm info linkStuff pump@1.0.3
npm info linkStuff xtend@4.0.2
npm info linkStuff tar-stream@1.6.2
npm info linkStuff tar-fs@1.16.3
npm info linkStuff yallist@3.0.3
npm info linkStuff minipass@2.3.5
npm info linkStuff fs-minipass@1.2.6
npm info linkStuff minizlib@1.2.1
npm info linkStuff color@3.1.2
npm info linkStuff fs-copy-file-sync@1.1.1
npm info linkStuff nan@2.14.0
npm info linkStuff prebuild-install@5.3.0
npm verb linkBins [
npm verb linkBins   { 'prebuild-install': './bin.js' },
npm verb linkBins   '/usr/lib/node_modules/sharp/node_modules/.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff semver@6.3.0
npm verb linkBins [
npm verb linkBins   { semver: './bin/semver.js' },
npm verb linkBins   '/usr/lib/node_modules/sharp/node_modules/.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff simple-get@3.0.3
npm info linkStuff tar@4.4.10
npm info linkStuff sharp@0.22.1
npm timing action:build Completed in 39ms
npm info lifecycle ansi-regex@2.1.1~install: ansi-regex@2.1.1
npm info lifecycle aproba@1.2.0~install: aproba@1.2.0
npm info lifecycle buffer-alloc-unsafe@1.1.0~install: buffer-alloc-unsafe@1.1.0
npm info lifecycle buffer-fill@1.0.0~install: buffer-fill@1.0.0
npm info lifecycle buffer-alloc@1.2.0~install: buffer-alloc@1.2.0
npm info lifecycle chownr@1.1.2~install: chownr@1.1.2
npm info lifecycle code-point-at@1.1.0~install: code-point-at@1.1.0
npm info lifecycle color-name@1.1.3~install: color-name@1.1.3
npm info lifecycle color-convert@1.9.3~install: color-convert@1.9.3
npm info lifecycle console-control-strings@1.1.0~install: console-control-strings@1.1.0
npm info lifecycle core-util-is@1.0.2~install: core-util-is@1.0.2
npm info lifecycle deep-extend@0.6.0~install: deep-extend@0.6.0
npm info lifecycle delegates@1.0.0~install: delegates@1.0.0
npm info lifecycle detect-libc@1.0.3~install: detect-libc@1.0.3
npm info lifecycle expand-template@2.0.3~install: expand-template@2.0.3
npm info lifecycle fs-constants@1.0.0~install: fs-constants@1.0.0
npm info lifecycle github-from-package@0.0.0~install: github-from-package@0.0.0
npm info lifecycle has-unicode@2.0.1~install: has-unicode@2.0.1
npm info lifecycle inherits@2.0.4~install: inherits@2.0.4
npm info lifecycle ini@1.3.5~install: ini@1.3.5
npm info lifecycle is-arrayish@0.3.2~install: is-arrayish@0.3.2
npm info lifecycle isarray@1.0.0~install: isarray@1.0.0
npm info lifecycle mimic-response@1.0.1~install: mimic-response@1.0.1
npm info lifecycle decompress-response@3.3.0~install: decompress-response@3.3.0
npm info lifecycle minimist@1.2.0~install: minimist@1.2.0
npm info lifecycle minimist@0.0.8~install: minimist@0.0.8
npm info lifecycle mkdirp@0.5.1~install: mkdirp@0.5.1
npm info lifecycle napi-build-utils@1.0.1~install: napi-build-utils@1.0.1
npm info lifecycle semver@5.7.0~install: semver@5.7.0
npm info lifecycle node-abi@2.9.0~install: node-abi@2.9.0
npm info lifecycle noop-logger@0.1.1~install: noop-logger@0.1.1
npm info lifecycle number-is-nan@1.0.1~install: number-is-nan@1.0.1
npm info lifecycle is-fullwidth-code-point@1.0.0~install: is-fullwidth-code-point@1.0.0
npm info lifecycle object-assign@4.1.1~install: object-assign@4.1.1
npm info lifecycle os-homedir@1.0.2~install: os-homedir@1.0.2
npm info lifecycle process-nextick-args@2.0.1~install: process-nextick-args@2.0.1
npm info lifecycle safe-buffer@5.1.2~install: safe-buffer@5.1.2
npm info lifecycle set-blocking@2.0.0~install: set-blocking@2.0.0
npm info lifecycle signal-exit@3.0.2~install: signal-exit@3.0.2
npm info lifecycle simple-concat@1.0.0~install: simple-concat@1.0.0
npm info lifecycle simple-swizzle@0.2.2~install: simple-swizzle@0.2.2
npm info lifecycle color-string@1.5.3~install: color-string@1.5.3
npm info lifecycle string_decoder@1.1.1~install: string_decoder@1.1.1
npm info lifecycle strip-ansi@3.0.1~install: strip-ansi@3.0.1
npm info lifecycle string-width@1.0.2~install: string-width@1.0.2
npm info lifecycle strip-json-comments@2.0.1~install: strip-json-comments@2.0.1
npm info lifecycle rc@1.2.8~install: rc@1.2.8
npm info lifecycle to-buffer@1.1.1~install: to-buffer@1.1.1
npm info lifecycle tunnel-agent@0.6.0~install: tunnel-agent@0.6.0
npm info lifecycle util-deprecate@1.0.2~install: util-deprecate@1.0.2
npm info lifecycle readable-stream@2.3.6~install: readable-stream@2.3.6
npm info lifecycle are-we-there-yet@1.1.5~install: are-we-there-yet@1.1.5
npm info lifecycle bl@1.2.2~install: bl@1.2.2
npm info lifecycle which-pm-runs@1.0.0~install: which-pm-runs@1.0.0
npm info lifecycle wide-align@1.1.3~install: wide-align@1.1.3
npm info lifecycle gauge@2.7.4~install: gauge@2.7.4
npm info lifecycle npmlog@4.1.2~install: npmlog@4.1.2
npm info lifecycle wrappy@1.0.2~install: wrappy@1.0.2
npm info lifecycle once@1.4.0~install: once@1.4.0
npm info lifecycle end-of-stream@1.4.1~install: end-of-stream@1.4.1
npm info lifecycle simple-get@2.8.1~install: simple-get@2.8.1
npm info lifecycle pump@2.0.1~install: pump@2.0.1
npm info lifecycle pump@1.0.3~install: pump@1.0.3
npm info lifecycle xtend@4.0.2~install: xtend@4.0.2
npm info lifecycle tar-stream@1.6.2~install: tar-stream@1.6.2
npm info lifecycle tar-fs@1.16.3~install: tar-fs@1.16.3
npm info lifecycle yallist@3.0.3~install: yallist@3.0.3
npm info lifecycle minipass@2.3.5~install: minipass@2.3.5
npm info lifecycle fs-minipass@1.2.6~install: fs-minipass@1.2.6
npm info lifecycle minizlib@1.2.1~install: minizlib@1.2.1
npm info lifecycle color@3.1.2~install: color@3.1.2
npm info lifecycle fs-copy-file-sync@1.1.1~install: fs-copy-file-sync@1.1.1
npm info lifecycle nan@2.14.0~install: nan@2.14.0
npm info lifecycle prebuild-install@5.3.0~install: prebuild-install@5.3.0
npm info lifecycle semver@6.3.0~install: semver@6.3.0
npm info lifecycle simple-get@3.0.3~install: simple-get@3.0.3
npm info lifecycle tar@4.4.10~install: tar@4.4.10
npm info lifecycle sharp@0.22.1~install: sharp@0.22.1

> sharp@0.22.1 install /usr/lib/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-linux-x64.tar.gz
ERR! sharp EACCES: permission denied, open '/usr/lib/node_modules/sharp/6613-libvips-8.7.4-linux-x64.tar.gz'
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/page/install for required dependencies
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild'
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.3.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.15
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 12.3.1
gyp verb command install [ '12.3.1' ]
gyp verb install input version string "12.3.1"
gyp verb install installing version: 12.3.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 12.3.1
gyp verb build dir attempting to create "build" dir: /usr/lib/node_modules/sharp/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/sharp/build'
gyp ERR! System Linux 4.15.0-48-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/sharp
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm verb lifecycle sharp@0.22.1~install: unsafe-perm in lifecycle false
npm verb lifecycle sharp@0.22.1~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/lib/node_modules/sharp/node_modules/.bin:/usr/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
npm verb lifecycle sharp@0.22.1~install: CWD: /usr/lib/node_modules/sharp
npm info lifecycle sharp@0.22.1~install: Failed to exec install script
npm timing action:install Completed in 438ms
npm verb unlock done using /home/USER/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 88ms
npm timing stage:runTopLevelLifecycles Completed in 6504ms
npm verb stack Error: sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:200:13)
npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:200:13)
npm verb stack     at maybeClose (internal/child_process.js:1021:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
npm verb pkgid sharp@0.22.1
npm verb cwd /home/USER/PROJECTS/MMMM/MMMMM-XXXXXX-IV4
npm verb Linux 4.15.0-48-generic
npm verb argv "/usr/bin/node" "/usr/bin/npm" "i" "-g" "sharp" "--verbose"
npm verb node v12.3.1
npm verb npm  v6.9.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.22.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 6938ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/USER/.npm/_logs/2019-07-29T02_25_38_387Z-debug.log

2) What is the output of running `npx envinfo --binaries --languages --system --utilities`?
npx: installed 1 in 2.002s

  System:
    OS: Linux 4.15 elementary OS 5.0 Juno
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Memory: 8.77 GB / 11.64 GB
    Container: Yes
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 12.3.1 - /usr/bin/node
    npm: 6.9.0 - /usr/bin/npm
  Utilities:
    Git: 2.21.0 - /usr/bin/git
  Languages:
    Bash: 4.4.19 - /bin/bash
    Java: 1.8.0_212 - /usr/bin/javac
    Perl: 5.26.1 - /usr/bin/perl
    Python: 2.7.15 - /usr/bin/python
    Ruby: 2.5.1 - /usr/bin/ruby

3) Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime?

I don't know how to do that.

4) My observations.

The path " /sharp/6613-libvips-8.7.4-linux-x64.tar.gz " does not exists as the line does reference " ERR! sharp EACCES: permission denied, open '/usr/lib/node_modules/sharp/6613-libvips-8.7.4-linux-x64.tar.gz' ".

**Comment by lovell** [comment]
Hi, if you have to use `sudo` with `npm install` then you also need to pass it the `--unsafe-perm` flag. It's better to avoid needing to use sudo/root in the first place if you can.

**Comment by ljvillarrealm** [comment]
Nice! thanks a lot!

**Comment by GalGreenfield** [comment]
Why would you need to use `--unsfafe-perm` in the first place?

> Hi, if you have to use `sudo` with `npm install` then you also need to pass it the `--unsafe-perm` flag. It's better to avoid needing to use sudo/root in the first place if you can.

Why would you need to use `--unsfafe-perm` in the first place?
