### ISSUE TITLE
Pipe original sharp stream to another stream, then write with clone?

### ISSUE THREAD

**Issue by smurrayatwork** [lovell/sharp#1815]
Hello!

I'm trying to use sharp with streams, and I'd like to pipe a sharp stream to the [node-pngQuant](https://github.com/papandreou/node-pngquant) library for further processing, before finally streaming that processed result to disk with a sharp clone. Is this possible?

png images seem to have issues being read using native fs.createReadStream, so I've been using [fs-minipass ](https://www.npmjs.com/package/fs-minipass)read/write streams in sync mode:

```
const pipeline = sharp();
transformList.map((transformOptions) => {
  const { outputPath } = transformOptions
  const clonedPipeline = pipeline.clone();
  // fsm is fs-minipass.
  const readStream = new fsm.ReadStreamSync(inputFilePath);
  const quantStream = new PngQuant(quantOptions);
  const writeStream = new fsm.WriteStreamSync(outputFilePath);
  clonedPipeline.pipe(quantStream).pipe(writeStream);
  readStream.pipe(pipeline);
});
```

**Comment by lovell** [comment]
Perhaps create a new sharp instance inside each invocation of the map function and remove all use of `clone`.

In addition, if you know the `inputFilePath` then provide that to the sharp constructor rather than create `readStream`.

```javascript
sharp(inputFilePath)
  .pipe(quantStream)
  .pipe(writeStream);
```

**Comment by smurrayatwork** [comment]
@lovell Would not using clone() cause a lot of memory to be used?

**Comment by lovell** [comment]
If the input image is available on the local filesystem, creating a sharp instance using a path rather than a stream should be more efficient in terms of both CPU and RAM as it lets libvips control I/O.
