### ISSUE TITLE
Enhancement: allow use of ready-premultipled images with composite

### ISSUE THREAD

**Issue by Monokai** [lovell/sharp#1816]
I have two images: a blue one and a gradient that runs from solid white to fully transparent white:

![image1](https://user-images.githubusercontent.com/277589/62144985-fc864b00-b2f2-11e9-9be3-f2fcf4c63a42.png)
![image2](https://user-images.githubusercontent.com/277589/62144986-fc864b00-b2f2-11e9-869c-d4e41c10c88d.png)

I'm using sharp to overlay them:

```js
const sharp = require('sharp');
const fs = require('fs');

(async () => {
	const image = await sharp('image1.png')
		.composite([
			{
				input: 'image2.png',
				blend: 'overlay'
			}
		])
		.toBuffer();

	fs.writeFile('result-sharp.png', image, err => {
		console.log(err);
	});
})();
```

This is the result:

![result-sharp](https://user-images.githubusercontent.com/277589/62144989-fd1ee180-b2f2-11e9-9d34-b1b231df29a6.png)

It differs from imagemagick:

`convert image1.png image2.png -compose Overlay -composite result-imagemagick.png`

![result-imagemagick](https://user-images.githubusercontent.com/277589/62144987-fc864b00-b2f2-11e9-82cd-d56805e0d483.png)

And Photoshop:

![result-photoshop](https://user-images.githubusercontent.com/277589/62144988-fc864b00-b2f2-11e9-8896-3c28defcc982.png)

Any ideas what I'm doing wrong here?

**Comment by lovell** [comment]
Hi, which version of sharp (and libvips) is this with? If not the latest, does the latest exhibit the same behaviour?

**Comment by Monokai** [comment]
I'm using sharp 0.23.0. The code above sits in a folder where I only did `npm install sharp`.

**Comment by Monokai** [comment]
A quick test shows that other blend modes (`screen`, `lighten`) exhibit the same behavior. It looks a bit like an incorrect gamma correction is applied?

**Comment by lovell** [comment]
The example gradient image looks like it has already been premultiplied.

By default libvips (and therefore sharp) will premultiply images to be composited.

If you skip this step, e.g. via:
```sh
vips composite "image1.png image2.png" image3.png overlay --premultiplied
```
then the output looks very similar to Photoshop:

![](https://user-images.githubusercontent.com/210965/62241714-97eded80-b3d1-11e9-8ff7-1b8df6cf449a.png)

**Comment by Monokai** [comment]
That looks more like it, thanks. Is this also possible in sharp?

**Comment by lovell** [comment]
At the moment, sharp assumes that all images will require premultiplying.

:point_down:  **Proposed API, not yet available**

We could expose libvips' `--premultiplied` flag via a new, optional "options" parameter, something like:

```javascript
  .composite(arrayOfImages, { premultiplied: true })
```

The default behaviour would be for libvips to premultiply, so the following two are equivalent to each other (and the current behaviour):

```javascript
  .composite(arrayOfImages, { premultiplied: false })
```
```javascript
  .composite(arrayOfImages)
```

:point_up: **Proposed API, not yet available**

Happy to accept a PR if you're able.

**Comment by Monokai** [comment]
@Andargor beat us to it :) https://github.com/lovell/sharp/pull/1835#issue-306706357

**Comment by lovell** [comment]
v0.23.1 now available with this feature.
