### ISSUE TITLE
`.resize` does not throw error when `options.width` or `options.height` is supplied with float number.

### ISSUE THREAD

**Issue by yqlim** [lovell/sharp#1817]
I'm using version `0.23.0`.

When used with `width` and `height` as params and supplied with a float number, an error will be thrown:

```javascript
let width = 30/100;
let height = width;

sharp(buffer)
  .resize(width, height, {
    /* options */
  })

// Throws `Error: Expected positive integer for width but received 0.3 of type number`
```

However, when the same is written like so, no error will be thrown. It seems that the whole `.resize` operation is simply skipped:

```javascript
let width = 30/100;
let height = width;

sharp(buffer)
  .resize({
    width,
    height,
    /* options */
  })
```

I wasted half my day trying to find what went wrong because my image can never be resized.

According to the [documentation](https://sharp.pixelplumbing.com/en/stable/api-resize/), the `options.width` and `options.height` take higher priority. So it seems the same error should also be thrown here.

**Comment by lovell** [comment]
Hi, happy to accept a PR to address this if you're able.

**Comment by lovell** [comment]
Commit 69fe21a adds unit tests and the logic that would have caught this. Thanks for reporting, this will be in v0.23.1.

**Comment by lovell** [comment]
v0.23.1 now available.
