### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by 2015-lizaiyang** [lovell/sharp#1818]
What is the output of running `npx envinfo --binaries --languages --system --utilities`?
 System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
    CPU: (1) x64 Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
    Memory: 169.27 MB / 991.11 MB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 10.15.0 - /usr/bin/node
    npm: 6.4.1 - /usr/bin/npm
  Utilities:
    Make: 3.82 - /usr/bin/make
    GCC: 4.8.5 - /usr/bin/gcc
    Git: 1.8.3.1 - /usr/bin/git
  Servers:
    Nginx: 1.16.0 - /usr/sbin/nginx
  IDEs:
    Vim: 7.4 - /usr/bin/vim
  Languages:
    Bash: 4.2.46 - /usr/bin/bash
    Perl: 5.16.3 - /usr/bin/perl
    Python: 2.7.5 - /usr/bin/python
  Databases:
    MongoDB: 4.0.10 - /usr/bin/mongo
    SQLite: 3.7.17 - /usr/bin/sqlite3

What are the steps to reproduce?
npm install sharp
> sharp@0.23.0 install /root/demo/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

ERR! sharp EACCES: permission denied, mkdir '/root/.npm/_libvips'
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/page/install for required dependencies
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/root/demo/node_modules/sharp/build'
gyp ERR! System Linux 3.10.0-957.5.1.el7.x86_64
gyp ERR! command "/usr/local/lib/nodejs/node-v10.15.0-linux-x64/bin/node" "/usr/local/lib/nodejs/node-v10.15.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/demo/node_modules/sharp
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN demo@1.0.0 No description
npm WARN demo@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.23.0 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.23.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-31T08_01_34_571Z-debug.log

**Comment by lovell** [comment]
If you're using `sudo npm install` have you tried with the `sudo npm install --unsafe-perm` flag?

As an aside, I notice you selected the "possible bug" issue template. Do you remember what made you select that option instead of the "installation" issue template?

**Comment by mylastore** [comment]
is it better to install it globally since I am using it on several projects?

**Comment by lovell** [comment]
@mylastore If you're still having problems, please open a new installation issue and answer all of the questions - https://github.com/lovell/sharp/issues/new?assignees=&labels=installation&template=installation.md
