### ISSUE TITLE
Segmentation fault 11

### ISSUE THREAD

**Issue by melbourne2991** [lovell/sharp#182]
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Error: Input buffer has corrupt header
    at /Users/Will/dev/image-server/node_modules/sharp/index.js:555:32

(sharp:30625): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:30625): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:30625): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:30625): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:30625): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:30625): GLib-CRITICAL **: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed

(sharp:30625): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed
Segmentation fault: 11

-------
Any fix? I know for imagemagick there was some issue with running on a mac related to segault 11.

Running OSX 10.9.2.

Cheers

**Comment by lovell** [comment]
Hi there, it looks the input image data is corrupt and I suspect you're missing code to handle this error condition, so the `node` process exits.

The segfault 11 and `g_hash_table_lookup` warnings are probably from libvips-spawned threads still processing other images. The `node` process doesn't wait for running threads to "join" before exiting in the event of an error.

**Comment by melbourne2991** [comment]
@lovell ok thanks for that. Do you know whereabouts I might need to hande this error given the code below? 

Cheers
----

		async.map(images, function(imageUrl, callback) {
			var imageId = crypto.randomBytes(20).toString('hex'),
				fileExt = getFileExtension(imageUrl).toLowerCase();

			if(fileExt === 'jpg' || fileExt === 'png' || fileExt === 'gif') {

				var writeStream, writeStreamPath, passes = {},
					checkStream = function(name) {
						return function() {
							passes[name].done = true;

							if(_.every(passes, function(pass) {
								return pass.done
							})) {
								callback(null, {
									id: imageId,
									ext: fileExt
								});
							}
						};
					};

				_.forEach(imageSizes, function(imageSize) {
					writeStreamPath = __dirname;
					writeStreamPath += '/files/images/';
					writeStreamPath += id;
					writeStreamPath += '/';
					writeStreamPath += imageId ;
					writeStreamPath += '_' ;
					writeStreamPath += imageSize.name;
					writeStreamPath += '' ;
					writeStreamPath += '.' ;
					writeStreamPath += fileExt;

					writeStream = fs.createWriteStream(writeStreamPath);

					writeStream.on('finish', checkStream(imageSize.name));

					pass = new Pass();
					pass
						.pipe(sharp().resize(imageSize.dimensions.width, imageSize.dimensions.height))
						.pipe(writeStream);

					passes[imageSize.name] = {
						done: false,
						pass: pass
					}; 
				});

				request(imageUrl)
					.pipe(passes.small.pass)
					.pipe(passes.medium.pass)
					.pipe(passes.large.pass)
			} else {
				return callback();
			}
		}, function(err, results) {
			callback && callback(results);
		});

**Comment by lovell** [comment]
If you're using Streams, the [standard](https://nodejs.org/api/stream.html#stream_event_error_1) `error` event is emitted if there's an error.

I've added a usage example to the docs via https://github.com/lovell/sharp/commit/bd96a49de6259faadfdaaeb86fd6ee5758898978, which should hopefully provide you with enough information to add suitable error handling to your own code.

**Comment by melbourne2991** [comment]
Great thanks heaps :+1:

**Comment by lovell** [comment]
No probs, glad to hear this helped.

**Comment by jaredscheib** [comment]
Continuing to get the same error when passing invalid image data into a pipeline (`GLib-CRITICAL **: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed`):
`
    const pipeline = sharp()
      .withMetadata()
      .jpeg()
      .on('error', handler);
    pipeline.clone()
      .on('error', handler)
      .pipe(writableStreams[0]);
    pipeline.clone()
      .resize(options[1].width)
      .quality(options[1].quality)
      .on('error', handler)
      .pipe(writableStreams[1]);
    pipeline.clone()
      .resize(options[2].width)
      .quality(options[2].quality)
      .on('error', handler)
      .pipe(writableStreams[2]);
`

Any thoughts on why this isn't handling the errors properly? Segmentation fault happens as the process exits. I've tried every permutation of error handling that I can imagine and can't seem to catch the errors properly. Any help would be appreciated.

**Comment by lovell** [comment]
@jaredscheib Please can you create a new issue for this, if possible with a sample image that consistently fails, so we can generate a backtrace of the segfault.
