### ISSUE TITLE
Using an image as the alpha channel for another image

### ISSUE THREAD

**Issue by TiredFalcon** [lovell/sharp#1820]
_What are you trying to achieve?_
I have a grayscale image that I want to use as the alpha channel of another image.

_Have you searched for similar questions?_
The cookbook example posted in #1113 seems to not be working for many images that I have to merge this way.

_Are you able to provide a standalone code sample that demonstrates this question?_
Yes, this is the code I'm using:
```javascript
sharp('mask.png')
    .extractChannel('red') // also B or G would work
    .toBuffer()
    .then((maskBuffer) => {
        sharp('image.png')
            .ensureAlpha()
            .joinChannel(maskBuffer)
            .toFile('output.png'); 
    });
```

_Are you able to provide a sample image that helps explain the question?_
Yes, here is the image and the mask I am using (I had to draw a bit on them because they're from a client). The output image looks identical to the input one, with a completely opaque alpha channel.
![mask.png](https://user-images.githubusercontent.com/16280355/62214364-37e15200-b3a5-11e9-9f19-81f47ca6071c.png)
![image.png](https://user-images.githubusercontent.com/16280355/62214365-37e15200-b3a5-11e9-8a66-41a19594d7f5.png)

**Comment by lovell** [comment]
Try adding`.toColorspace('b-w')` in the first pipeline to ensure `maskBuffer` is single channel rather than sRGB.

**Comment by LambdaFalcon** [comment]
It still does not work.
Anyway, doesn't `.extractChannel('red')` already extract a single channel from the image?

**Comment by lovell** [comment]
Ah, I got the two example images the wrong way round, I thought the mask was the sRGB one.

Both of these images have an existing alpha channel that needs removing first. Try something like the following:

```javascript
const removeAlpha = input =>
  sharp(input)
    .removeAlpha()
    .toBuffer();

Promise.all(["image.png", "mask.png"].map(removeAlpha)).then(([image, mask]) =>
  sharp(image)
    .joinChannel(mask)
    .toFile("output.png")
);
```

**Comment by hssrrw** [comment]
I have problems with masking images too.

In sharp v0.21 the code was:
```javascript
  const roundedCorners = Buffer.from(
    `<svg><rect x="0" y="0" width="${width}" height="${width}" rx="${r}" ry="${r}"/></svg>`
  );

  sharp(sourceImagePath)
    .resize(width)
    .overlayWith(roundedCorners, { cutout: true })
    .toFile(outputPath);
```

Since `overlayWith` is no longer available in v.0.23, I tried this code (as @lovell suggested):
```javascript
let mask = sharp(roundedCorners)
  .removeAlpha()
  .toBuffer();

sharp(iconPath)
  .resize(size)
  .removeAlpha()
  .joinChannel(mask)
  .toFile(outputPath);
```
It produces an error
```
Error: Unsupported input object
```
for the line with `joinChannel`.

If I use Sharp object instead of Buffer:
```javascript
let mask = sharp(roundedCorners)
  .removeAlpha();
// ⚠️ mask is Sharp now

sharp(iconPath)
  .resize(size)
  .removeAlpha()
  .joinChannel(mask)
  .toFile(outputPath);
```
then the error becomes
```
Error: Expected width, height and channels for raw pixel input
```

Since things got more complicated and low level now, I have no idea where to go from here.
Although, it would be nice not to introduce extra dependency, I am just going to use another lib for masking.

Any help appreciated, thanks.

**Comment by hssrrw** [comment]
Sorry, my bad. Just realized `toBuffer` returns a Promise. The first snippet isn't valid then.

Still, can't figure why the second one doesn't work. Even if I read mask from PNG file, not SVG buffer.

**Comment by hssrrw** [comment]
I've found a solution using `composite()`:
```javascript
  const maskBuffer = await sharp(roundedCorners).toBuffer();
  const sourceBuffer = await sharp(iconPath)
    .resize(size)
    .toBuffer();

  return sharp(maskBuffer)
    .composite([{ input: sourceBuffer, blend: 'in' }])
    .toFile(outputPath);
```

**Comment by LambdaFalcon** [comment]
> Ah, I got the two example images the wrong way round, I thought the mask was the sRGB one.
> 
> Both of these images have an existing alpha channel that needs removing first. Try something like the following:
> 
> ```js
> const removeAlpha = input =>
>   sharp(input)
>     .removeAlpha()
>     .toBuffer();
> 
> Promise.all(["image.png", "mask.png"].map(removeAlpha)).then(([image, mask]) =>
>   sharp(image)
>     .joinChannel(mask)
>     .toFile("output.png")
> );
> ```

@lovell This works perfectly, even if we just remove the alpha channel from the image and just extract any channel from the mask.
However, and I believe this might need further investigation, while this works:
```javascript
sharp("mask.png")
  .extractChannel("red")
  .toBuffer()
  .then(mask =>
    sharp("image.png")
      .removeAlpha()
      .toBuffer()
      .then(image =>
        sharp(image)
          .joinChannel(mask)
          .toFile("output.png")
      )
  );
```

this seemingly equivalent code does not work:

```javascript
sharp("mask.png")
  .extractChannel("red")
  .toBuffer()
  .then(mask =>
    sharp("image.png")
      .removeAlpha()
      .joinChannel(mask)
      .toFile("output.png")
  );
```

**Comment by lovell** [comment]
In the second example, removeAlpha and joinChannel work against each other so you are correct to use three pipelines as in the first example.
