### ISSUE TITLE
Convert animated gif to animated webp

### ISSUE THREAD

**Issue by RaboliotTheGrey** [lovell/sharp#1823]
Salutations Lovell !

**What are you trying to achieve?**
I think I miss something, but I though with one of the latest version of libvips, it's possible to output animated webp.
So I tried with the new version of sharp (0.23.0) to convert a gif to a webp (that works but only for the first frame, like before).

Am I missing something or it needs an enhancement ?
If it need an enhancement, I will be glad to do it (but if you can pinpoint the direction, it would be awesome)

Have a nice day!

**Comment by jcupitt** [comment]
Hello, I don't know sharp well, but at the command-line it's:

```
vips copy cogs.gif[n=-1] x.webp
```

ie. by default it just loads page 0. Set `n` (number of pages) to -1 to load all pages. Animated HEIC, PDF, TIFF etc. work in the same way.

**Comment by jcupitt** [comment]
(answering because I think Lovell is on holiday)

**Comment by lovell** [comment]
As John says, you'll need to let libvips know you want all the "pages" rather than the default behaviour of just using the first page/frame. This will be something like (untested):

```javascript
sharp("cogs.gif", { pages: -1 }).toFile("x.webp")
```

https://sharp.pixelplumbing.com/en/stable/api-constructor/#parameters

**Comment by RaboliotTheGrey** [comment]
Oh thanks! I missed this bit of docs :/
Thanks John too for the answer :)

**Comment by pgsill** [comment]
@lovell I've managed to use that with no problem, and sure enough the output is an animated WebP. However, when using `.resize()` the output is just the first frame of the input GIF, with no animation. Is there something I'm missing?

**Comment by jcupitt** [comment]
Yes, if you run:

```
$ vips thumbnail cogs.gif[n=-1] tiny.gif 64
```

You get:

![tiny](https://user-images.githubusercontent.com/580843/66131281-0f671580-e5eb-11e9-9df4-aea156af3d04.gif)

But:

```
$ vips resize cogs.gif[n=-1] tiny.gif 0.5
```

Makes:

![tiny](https://user-images.githubusercontent.com/580843/66131358-34f41f00-e5eb-11e9-8eca-b0a47e96df99.gif)

This is because `thumbnail` has extra logic for resizing animated images. It has to pick a shrink factor which resizes each page exactly to the specified size, rather than resizing the whole toilet roll (sorry abou the name).

**Comment by shapish** [comment]
Are there any plans to implement the resizing of animated webp to Sharp? @lovell Would be very useful.

**Comment by lovell** [comment]
@shapish It's somewhat possible now if you use `resize()` and also manually set the `pageHeight` via `.webp({ pageHeight })`.

It will be much easier with #3013

**Comment by anasalaqeel** [comment]
all you need is to use ` { animated: true }` option

```js
await sharp('in.gif', { animated: true }).toFile('out.webp');
``` 
this works for me

**Comment by ZahidAliCodes** [comment]
![Colorful Summer Animated Instagram Post](https://github.com/user-attachments/assets/e1f89ffa-d66d-47c6-862c-516b4ae02b58)
i want change this in webp but same animated in webp
