### ISSUE TITLE
"heif" is missing from the list checked in toFormat

### ISSUE THREAD

**Issue by jaubourg** [lovell/sharp#1824]
https://github.com/lovell/sharp/blob/master/lib/output.js#L509

I can workaround by using `.heif()` directly (what `.toFormat()` actually does).

**Comment by lovell** [comment]
A PR to add this would be very welcome if you're able.

**Comment by jaubourg** [comment]
@lovell https://github.com/lovell/sharp/pull/1834

**Comment by lovell** [comment]
v0.23.1 now available, merci beaucoup for the PR.
