### ISSUE TITLE
Heroku: Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by salisbury88** [lovell/sharp#1827]
Hello,

Fairly new to sharp and absolutely loving it so far. I'm now at the point of pushing some changes to production but keep hitting two error messages. I've checked out the install guide and couldn't see anything obvious to explain my particular issues. 

I'm using node 10.16.2 and working with Heroku. Running the app locally works perfectly, however when I push to heroku I get the following error:

```
remote:        > sharp@0.23.0 install /tmp/build_76ec7bd4ab0de55261ad2345bfe14111/node_modules/sharp
remote:        > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
remote:        
remote:        ERR! sharp 'darwin-x64' binaries cannot be used on the 'linux-x64' platform. Please remove the 'node_modules/sharp/vendor' directory and run 'npm install'.
remote:        info sharp Attempting to build from source via node-gyp but this may fail due to the above error
remote:        info sharp Please see https://sharp.pixelplumbing.com/page/install for required dependencies
remote:        make: Entering directory '/tmp/build_76ec7bd4ab0de55261ad2345bfe14111/node_modules/sharp/build'
```
Performing the suggested steps of removing the 'node_modules/sharp/vendor' directory and running 'npm install' fixes this issue and allows me to push all changes through. However, when I come to then run the app locally again, I now see the following error:

```
Something went wrong installing the "sharp" module

dlopen(/Users/reubensalisbury/Documents/Development/Productstash/node_modules/sharp/build/Release/sharp.node, 1): Library not loaded: @rpath/libvips-cpp.42.dylib
  Referenced from: /Users/reubensalisbury/Documents/Development/Productstash/node_modules/sharp/build/Release/sharp.node
  Reason: image not found

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues
```

Again, performing the suggested steps of removing the "node_modules/sharp" directory, and running "npm install" fixes the issue, and I can now run the app locally; however the next time I push to production I get the first error message again - I seem to be stuck in this cycle.

I can't see any obvious errors running npm install --verbose sharp.

Any advice would be appreciated - thanks.

**Comment by lovell** [comment]
https://devcenter.heroku.com/articles/deploying-nodejs#how-to-keep-build-artifacts-out-of-git

**Comment by litotechenterprise** [comment]
Can you explain how this resolves the issue. I created a .gitignore file as the article suggest, however I still run into the same issue when pushing to heroku.

**Comment by litotechenterprise** [comment]
@lovell
