### ISSUE TITLE
prebuilt for electron@6?

### ISSUE THREAD

**Issue by Kilian** [lovell/sharp#1831]
Hi, electron@6 ([released](https://electronjs.org/blog/electron-6-0) at the beginning of this month) has an ABI of 73, but the [current highest version available in releases](https://github.com/lovell/sharp/releases/tag/v0.23.0) is v70 (matching electron@5) so a prebuilt can't be downloaded for electron@6. Can v73 be added?

**Comment by lovell** [comment]
The next release will include this *automagically*.

**Comment by lovell** [comment]
v0.23.1 now available with prebuilt binaries for Electron 6 (ABI 73).
