### ISSUE TITLE
overlayWith is not a function 

### ISSUE THREAD

**Issue by JakinMiao** [lovell/sharp#1837]
What is the output of running `npx envinfo --binaries --languages --system --utilities`?

What are the steps to reproduce?

What is the expected behaviour?

Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?

Are you able to provide a sample image that helps explain the problem?

**Comment by Jor2611** [comment]
Same issue

**Comment by Jor2611** [comment]
Ok I found that  overlayWith is deprecated you can use composite method instead.

**Comment by lovell** [comment]
Please use [composite](https://sharp.pixelplumbing.com/en/stable/api-composite/#composite).

`overlayWith` was deprecated in [v0.22.0](https://sharp.pixelplumbing.com/en/stable/changelog/#v0220-18th-march-2019) and removed in [v0.23.0](https://sharp.pixelplumbing.com/en/stable/changelog/#v0230-29th-july-2019).
