### ISSUE TITLE
Crashing silently when resizing large image

### ISSUE THREAD

**Issue by Sorgrum** [lovell/sharp#1838]
What is the output of running `npx envinfo --binaries --languages --system --utilities`?
```
  System:
    OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (1) x64 Virtual CPU a7769a6388d5
    Memory: 74.56 MB / 492.38 MB
    Container: Yes
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/bin/node
    Yarn: 1.16.0 - /usr/bin/yarn
    npm: 6.9.0 - /usr/bin/npm
  Utilities:
    Make: 4.1 - /usr/bin/make
    GCC: 6.3.0 - /usr/bin/gcc
    Git: 2.11.0 - /usr/bin/git
  Languages:
    Bash: 4.4.12 - /bin/bash
    Perl: 5.24.1 - /usr/bin/perl
    Python: 2.7.13 - /usr/bin/python
    Ruby: 2.3.3 - /usr/bin/ruby
```

What are the steps to reproduce?
1. Load in image from base64 (Crashes with >10mb)
```js
const base64Image = image.base64.split(',')[1]
const imageBuffer = Buffer.from(base64Image, 'base64')
const basePath = `images/${newId[0]}/`

Promise.all([
    resize(imageBuffer, basePath, 1000, 1000),
    resize(imageBuffer, basePath, 250, 250),
    resize(imageBuffer, basePath, 50, 50)
])
```
2. Resize image and write to file
```js
await sharp(imageBuffer)
    .resize(width, height) 
    .toFile(filePath)
```

What is the expected behaviour?
The file should be resized without crashing. 

Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?
If needed, yes.

Are you able to provide a sample image that helps explain the problem?
<img width="533" alt="Screen Shot 2019-08-15 at 12 33 23 AM" src="https://user-images.githubusercontent.com/3497076/63072939-52164680-bef4-11e9-973c-05c115916e66.png">

**Comment by lovell** [comment]
My best guess would be that 492.38MB may not be enough RAM for the task at hand. These images will be processed concurrently and there will be 3 copies of each input (`image.base64`, `base64Image` and `imageBuffer`) in memory at the same time. Could there be further concurrency not shown in this sample code, e.g. other requests still in memory that have yet to become eligible for GC?

If there are WebP and progressive JPEG images involved these can consume a lot of memory during encode and decode respectively.

Setting [sequentialRead](https://sharp.pixelplumbing.com/en/stable/api-input/#sequentialread) can help reduce memory usage.

We'll need a backtrace to debug this any further.

**Comment by Sorgrum** [comment]
Seems like `sequentialRead` has helped. Thank you!
