### ISSUE TITLE
Something went wrong installing the "sharp" module on gatsby

### ISSUE THREAD

**Issue by JaybeeClassical** [lovell/sharp#1840]
So, i just uninstalled my node.js version 10 and installed the current one node.js version 12 and went back to my gatsby project to run the *gatsby develop* and i got this error

success open and validate gatsby-configs - 0.141 s

Something went wrong installing the "sharp" module

The module '\\?\C:\Users\Jaybee\Desktop\Projects\IamJude\node_modules\sharp\build\Release\sharp.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

- Ensure the version of Node.js used at install time matches that used at runtime
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues

⠋ load plugins

I have done *npm install* and as well updated my gatsby cli but same error, please can i get help on this.

OS: windows 10
node.js version: 12.8.1
npm version: 6.10.2

Tried this #1747 already but didn't work for me

**Comment by lovell** [comment]
Native modules must be re-installed after a major upgrade of Node.js. Running `npm rebuild` (as suggested in the error message) usually fixes this.

**Comment by JaybeeClassical** [comment]
> Native modules must be re-installed after a major upgrade of Node.js. Running `npm rebuild` (as suggested in the error message) usually fixes this.

This worked 

Thanks

**Comment by calsal8** [comment]
I had the same issue after major Node upgrade (to v10.16.3) on my Windows build server. I ran `npm rebuild` as suggested in the error message. Now i get this error message instead:
```
Something went wrong installing the "sharp" module

The specified procedure could not be found.
\\?\C:\Build\WebbDev\node_modules\sharp\build\Release\sharp.node

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues
```

I can locate the `sharp.node` file in the file explorer.  I've tried to remove `node_modules/sharp` and the whole `node_modules` directory and then `npm install` again, same error. I've downgraded to Node v9.11.2 (the one I had before), same error. It works fine on my development environment.

I would be very happy for any ideas on this!
