### ISSUE TITLE
Worth using streams when requesting metadata?

### ISSUE THREAD

**Issue by jcebuck** [lovell/sharp#1841]
I'm processing an image that is uploaded via a form POST to express and the image is currently held in a buffer, resized multiple times and written to disk.
However, if the image is already smaller than one of the resize parameters the rest are short-circuited and processing stops (hence the need to get image metadata):
```
const resizeImage = async function(buffer, sizes, path, name) {
	let image = sharp(buffer);
	let metadata = await image.metadata();
	let isSmall = false;
	return Promise.all(sizes.sort((a, b) => a - b).map(dim => {
		if (isSmall) {
			return null;
		}
		if (metadata.width > dim || metadata.height > dim) {
			let promise = image.resize({width: dim, height: dim, fit: 'inside'})
				.toFile(`${path}${dim === sizes[sizes.length - 1] ? '' : dim + '/'}${name}`);
			image = sharp(buffer); // for next round of input
			return promise;
		} else {
			isSmall = true;
			return image.toFile(`${path}${name}`);
		}
	}));
};
```

Would there be any benefit, in terms of memory usage, by switching to streams based input and using `.clone()`? Currently, is a fully decompressed version of the image held in memory?
Also, it is necessary to recall the sharp constructor in the loop or just reuse the variable from outside the loop: `image = sharp(buffer); // for next round of input`?

**Comment by lovell** [comment]
As you've already got the input image in memory then the current approach looks sensible to me. The use of Streams would increase memory usage and GC pressure. You could create new sharp instances as required, rather than recycle them, as these have near-zero cost and improve immutability.

`metadata` does not decompress pixel data:

> "Fast access to (uncached) image metadata without decoding any compressed image data."
> https://sharp.pixelplumbing.com/en/stable/api-input/#metadata

**Comment by jcebuck** [comment]
Thanks @lovell.

Is a JPEG image fully decompressed in memory when resizing, and should I be using `sequantialRead` to stop this from happening when possible?

**Comment by lovell** [comment]
[sequentialRead](https://sharp.pixelplumbing.com/en/stable/api-input/#sequentialread) can help reduce memory consumption at the cost of increased CPU for repeated operations e.g. you mentioned "resized multiple times" in the original question.
