### ISSUE TITLE
toFile variant with support for file options

### ISSUE THREAD

**Issue by dantman** [lovell/sharp#185]
I'd like to be able to control the flags and mode that `toFile` uses for writing.

If `toFile` just tells vips to write to file in a way that can't be controlled. Then this `toFile` would pretty much be sugar for piping into a writable stream. And I understand if you want to give it a different method name.

Right now I'm working in an environment with promises and I'm writing to a tmp file which I want to make sure uses `{flags: 'wx', mode: '600'}`.

The current situation forces me to choose either:
A) A nice promise based interface with `toFile` but no control over the flags and mode.
B) Control over the flags and mode, but with ugly code that pipes through a stream and then does a `resolve` from a `new Q.Promise(...)` to promisify it.

**Comment by lovell** [comment]
Hi Daniel,

The flags are controlled by libvips within [vips__file_open_write](https://github.com/jcupitt/libvips/blob/master/libvips/iofuncs/util.c#L597). It doesn't use the `x` flag so will overwrite an existing file, which I guess is the problem you've run into. Given these are temp files, perhaps you could generate unique filenames to avoid collision?

To set `mode: '600'`, you could add something like `process.umask(0077);` to ensure newly-created files have user-only permissions.

**Comment by dantman** [comment]
Unique filenames are used, the `x` flag is standard practice for security with tmp files.

And modifying the global umask to change the mode of a single written file is terrible and will also result in bugs where files written in other parts of the process are given the wrong mode if the sharp operation is in progress at that time.

As I said, if the vips operation cannot be controlled directly, I'd like a new method that will create a writable stream with the options, pipe into that, and then resolve the callback or promise in the way that `toFile` does.

**Comment by lovell** [comment]
You could ask John over at the [libvips](https://github.com/jcupitt/libvips/issues) repo if he'd consider exposing file modes and flags.

The `x` mode of `fopen` is a C11 standard so you may need to wrap it with the `#if __STDC_VERSION__ >= 201112L` preprocessor conditional so it works on things like Windows.

To set file permissions, `fopen` would probably have to replaced with `open`, which I suspect would reduce performance (images are sequentially written and therefore can take advantage of `fopen`'s buffering).

Back in JavaScript-land, sharp's `toBuffer` method is as efficient memory-wise as piping data out via a Stream, so it's probably the most elegant way to achieve what you desire using Promises with the API as-is. (The following assumes `writeFileAsync` is a _promisified_ version of `fs.writeFile`.)

```javascript
sharp(input)
  .resize( ... )
  .toBuffer()
  .then(function(data) {
    return writeFileAsync(output, data, {mode: ... , flag: ... });
  })
  .then( ... )
```

**Comment by lovell** [comment]
The two possible solutions presented here either involve either a change to libvips or a change to the consuming code to use Buffer-based output, so I'll close this one for now.

As always I'm happy to consider a PR with an alternative approach.
