### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by chenxiai** [lovell/sharp#1850]
hello,
I am installing sharp in nodebb.
Here is an error when it goes to download from https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-win32-x64.tar.gz.

How can it be fixed? Thanks a lot.

D:\NodeBB-master>npm install sharp

> sharp@0.23.0 install D:\NodeBB-master\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-win32-x64.tar.gz
D:\NodeBB-master\node_modules\sharp\install\libvips.js:82
          throw err;
          ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:183:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}

D:\NodeBB-master\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  VError.cpp
  VInterpolate.cpp
  VImage.cpp
  win_delay_load_hook.cc
LINK : fatal error LNK1104: cannot open file '..\vendor\lib\libvips.lib' [D:\NodeBB-master\node_modules\sharp\build\lib
vips-cpp.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\NodeBB-master\node_modules\sharp
gyp ERR! node -v v12.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN eslint-config-airbnb-base@13.1.0 requires a peer of eslint@^4.19.1 || ^5.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN nodebb-plugin-emoji-android@2.0.0 requires a peer of nodebb-plugin-emoji@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN textcomplete.contenteditable@0.1.1 requires a peer of textcomplete@^0.14.2 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.23.0 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.23.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chen29\AppData\Roaming\npm-cache\_logs\2019-08-26T07_37_06_046Z-debug.log

D:\NodeBB-master>npm install sharp -> installlog.txt
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/- - Not found
npm ERR! 404
npm ERR! 404  '-@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chen29\AppData\Roaming\npm-cache\_logs\2019-08-26T07_45_32_153Z-debug.log

**Comment by lovell** [comment]
`ECONNRESET` is due to a (temporary? firewall?) network problem connecting to https://github.com/.

**Comment by chenxiai** [comment]
https://github.com/ is accessible in the web browser.
The firewall is closed.
How can the sharp be installed when the sharp and libvips are downloaded.

**Comment by chenxiai** [comment]
Yes. It's related to a network problem connecting to https://github.com/  in windows command line.
I test with the following command in two different computer. One is working. The server with nodebb is not working.


D:\11>git clone https://github.com/lovell/sharp
Cloning into 'sharp'...
fatal: unable to access 'https://github.com/lovell/sharp/': Unknown SSL protocol error in connection to github.com:443

**Comment by lovell** [comment]
Glad you worked it out.
