### ISSUE TITLE
Error: Input buffer contains unsupported image format when trying to resize an image

### ISSUE THREAD

**Issue by elndro85** [lovell/sharp#1852]
I'm trying to resize a .jpg image file that I have stored locally on my computer but I keep getting a `Input buffer contains unsupported image format` error even though this is a .jpg image, I've tried reviewing other issues in this repository but haven't been able to find a solution, 

Here's the jpg image i'm using (path is 28969679-180920.jpg):
![28969679-180920](https://user-images.githubusercontent.com/987341/63728832-4f83ed00-c822-11e9-8865-6e3fa9b98eb6.jpg)

Here's the code i'm using:

```
let image = fs.createReadStream("images/28969679-180920.jpg");

let transform = sharp();

transform.toFormat(config.format, {
        progressive: true,
        quality: config.quality
    });

transform.resize(100, 100, {
    fit: config.mode,
    background: { r: 255, g: 255, b: 255, alpha: 1 },
    withoutEnlargement: true
});

return image.pipe(transform);
```

**Comment by makepanic** [comment]
Seems like the file isn't really a jpeg file but a bmp.

See `file` output. Top is yours, bottom is some random jpeg.

![20190827-090808](https://user-images.githubusercontent.com/1205444/63748151-180c5380-c8a9-11e9-95c5-e4bdfadabc3c.png)

The magic bytes of jpeg are also missing:

![20190827-090827](https://user-images.githubusercontent.com/1205444/63748287-5bff5880-c8a9-11e9-9e17-be6643f61a1b.png)

**Comment by elndro85** [comment]
Thank you @makepanic, I appreciate your help. I solved my issue with the suggestions provided here https://github.com/lovell/sharp/issues/806#issuecomment-419661745

my code now looks like this: 

```
var bufferImage = fs.readFileSync(image.path);
var bitmap = bmp.decode(bufferImage, true);

var sharpImage = sharp(bitmap.data, {
        raw: {
            height: bitmap.height,
            width: bitmap.width,
            channels: 4
        }
    });

sharpImage.toFormat('jpg');
```
