### ISSUE TITLE
Composite with gravity, right and bottom params

### ISSUE THREAD

**Issue by dszymczuk** [lovell/sharp#1854]
**What are you trying to achieve?**

Put watermark using `gravity` in `composite` with an offset from left and bottom edge.

**Have you searched for similar feature requests?**
I didn't find it. I found just left and top params, but I have to place watermark manually.

What would you expect the API to look like?

Create offset param in object.

```javascript
await sharp('image.png')
  .composite([{
    input: 'watermark.png',
    gravity: 'southwest',
    offset: {
      left: 10,
      bottom: 10
    }
  }]).toFile('image.png');
```

**What alternatives have you considered?**

If I want to achieve this, I have to calculate image size, watermark size and make some calculation.

**Is there a sample image that helps explain?**

At now I have:
![without](https://user-images.githubusercontent.com/539352/64065000-87b37300-cc08-11e9-81bc-e7506f5f48c9.png)

I would like to achieve this:
![with](https://user-images.githubusercontent.com/539352/64064999-87b37300-cc08-11e9-8ddf-684708a6db23.png)

**Comment by lovell** [comment]
Hi, perhaps you could extend the watermark image by 10 transparent pixels along the left and bottom edges?

**Comment by dszymczuk** [comment]
You're right. I haven't thought about this 🤦‍♂

**Comment by SixBytesUnder** [comment]
I know this is an old one, but it'd be really great if you could add "right" and "bottom" options. It's not always possible to add this kind of margin to the image itself. Also it'd be a lot better to be able to fully control the position programmatically.
