### ISSUE TITLE
Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by barbgegrasse** [lovell/sharp#1857]
I cant't launch Gatsby on my new project 
_Something went wrong installing the "sharp" module

The specified procedure could not be found.
\\?\Q:\Work\www\ramen-contentful\node_modules\gatsby-plugin-manifest\node_modules\sharp\build\Release\sharp.node

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues_

I tried to delete my node module folder and reinstall, tried to install globally, tried to rebuild etc....

**Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime?**
Yes

**If you're (mis)using `sudo npm install` have you tried with the `sudo npm install --unsafe-perm` flag?**
yes

**What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?**
No errors, only when i launch gatsby develop

What is the output of running `npx envinfo --binaries --languages --system --utilities`?
  **System**:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
    Memory: 3.68 GB / 11.94 GB
  **Binaries**:
    Node: 10.16.3 - H:\Programmes\nodjs\node.EXE
    Yarn: 1.17.3 - H:\Programmes\yarn\bin\yarn.CMD
    npm: 6.11.2 - C:\Users\****\AppData\Roaming\npm\npm.CMD
  **Languages**:
    Bash: 4.4.12 - H:\Programmes\Git\bin\bash.EXE
    PHP: 7.1.9 - E:\Work\wamp64\bin\php\php7.1.9\php.EXE
    Ruby: 2.4.2 - H:\Programmes\Ruby24-x64\bin\ruby.EXE

**Comment by SergiOca87** [comment]
I keep getting this on 3 separate projects halting everything.

Removed everything, reinstalled everything several times, nothing.

"Something went wrong installing the "sharp" module"

**Comment by barbgegrasse** [comment]
i finally found a way to manage this....

From  the documentation. Trouble Shooting part :
https://www.gatsbyjs.org/packages/gatsby-transformer-sharp/

`npm install gatsby-plugin-sharp gatsby-plugin-manifest gatsby-remark-images-contentful gatsby-source-contentful gatsby-transformer-sharp gatsby-transformer-sqip`

**Comment by SergiOca87** [comment]
I wrote about this in 2019, still happening in 2022, crazy.

**Comment by lovell** [comment]
@SergiOca87 If you're still having problems installing the latest version of sharp, please open [a new installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md). If you're not using the latest version, please upgrade as there have been many, many improvements in the last 3 years.

**Comment by SergiOca87** [comment]
> @SergiOca87 If you're still having problems installing the latest version of sharp, please open [a new installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md). If you're not using the latest version, please upgrade as there have been many, many improvements in the last 3 years.

Thanks for the reply. I have everything on the latest version. There are a few posts about this error noting that the solution is to downgrade Node which is not a viable solution.

**Comment by SergiOca87** [comment]
After removing everything, I could install it, only to have the Gatsby build stuck at "building thumbnails", which I've read is also because of sharp. Downgraded Node, now seeing:

"npm ERR! sharp@0.30.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile 
&& node-gyp rebuild && node install/dll-copy)`"

![sharp](https://user-images.githubusercontent.com/20750614/155756346-63b83af4-09c9-4096-978d-57668ca796d0.JPG)

**Comment by lovell** [comment]
@SergiOca87 Please open [a new installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md).
