### ISSUE TITLE
Provide pre-built "sharp.node" binary for common platforms and Node versions

### ISSUE THREAD

**Issue by mikemorris** [lovell/sharp#186]
https://github.com/mapbox/node-pre-gyp

**Comment by lovell** [comment]
Hi Mike, node-pre-gyp looks interesting, thank you for the suggestion.

From scanning the mapnik examples, it looks like it statically links dependencies into a single pre-compiled `.node` binary for each combination of architecture, platform and node version.

Would we also need to build and provide statically compiled versions of libvips and its dependants first?

Is there any licensing impact to consider when static linking both LGPL and GPL2 dependencies with Apache 2.0 sources.

I'd be happy to accept a PR that integrates with node-pre-gyp.

The existing [preinstall.sh](https://github.com/lovell/sharp/blob/master/preinstall.sh) script could be used to populate a VM/container environment in which to build a statically linked version of libvips.

I'm able to provide an S3 bucket to host pre-compiled files in, if that's the easiest way to achieve this.

There are plenty of people to help test this amongst the contributors to the "meaning of life" issue that is #42.

**Comment by lovell** [comment]
Handy guide to using various CI providers as the build infrastructure for compiling binaries:
http://cylonjs.com/blog/2014/11/19/creating-multiplatform-precompiled-binaries-for-node-modules/

**Comment by lovell** [comment]
NPM's "[Roadmap area of focus: native modules](https://github.com/npm/npm/wiki/Roadmap-area-of-focus%3A-native-modules)" is relevant here.

**Comment by lovell** [comment]
Most of my comment https://github.com/lovell/sharp/issues/186#issuecomment-88019499 about static linking is no longer relevant as sharp ships with pre-built shared libraries that can be used to generate a `sharp.node` shared library.

Windows should probably be the priority/test case for this work.

**Comment by lovell** [comment]
I'm going to investigate the use of [prebuild-ci](https://github.com/juliangruber/prebuild-ci) and (a possibly-modified version of) [prebuild-install](https://github.com/mafintosh/prebuild-install).

The libvips-downloading logic in the binding.* files will need to be extracted as `node-gyp build` may no longer be run.

**Comment by mpseidel** [comment]
👍 - building sharp everytime in our docker builds has become a bottleneck

**Comment by jingsam** [comment]
Installing sharp is painful and error prone because of rebuilding from source. Providing precompiled binaries would alleviate this pain.

**Comment by jeremyfa** [comment]
Thanks for looking at this! _sharp_ is excellent and deserves to be as easy as possible to install 👍

**Comment by appjitsu** [comment]
+1

**Comment by ArmorDarks** [comment]
Worth to check out https://github.com/sass/node-sass and see how they solved similar issue. They shipping compiled`libsass` for various platforms too, and, thankfully, on Windows and other popular platforms it doesn't require nor `node-gyp`, nor anything like that.

For many Node projects the drop of `node-gyp` and Python will be a huge step forward, for sure.

**Comment by nanom1t** [comment]
Providing precompiled binaries would be awesome. Maybe there is a way to divide sharp into 2 parts: npm package and *.deb/*.rpm package in such way as graphicsmagick does:
```
sudo apt-get install graphicsmagick
```

**Comment by ArmorDarks** [comment]
> npm package and .deb/.rpm package in such way as graphicsmagick does:

Unfortunately, it will solve issue only for unix users, but not for Windows ones.

**Comment by Lange** [comment]
I highly recommend looking into [`prebuild`](https://github.com/prebuild/prebuild), it is the easiest way to provide prebuilt binaries of native node addons.

[`node-serialport`](https://github.com/node-serialport/node-serialport)'s CI configs ([`appveyor.yml`](https://github.com/node-serialport/node-serialport/blob/master/appveyor.yml) and [`.travis.yml`](https://github.com/node-serialport/node-serialport/blob/master/.travis.yml)) are great examples of how to set up `prebuild` in CI.

I also recently opened a PR to `node-usb-detection` (https://github.com/MadLittleMods/node-usb-detection/pull/47) to add `prebuild` support, This PR gives a nice clear outline of the whole process for getting `prebuild` up and running.

**Comment by lovell** [comment]
Quick update for this popular issue: I've successfully started using (and contributing patches to) `prebuild` with other native modules and agree it provides what we need. Before this can happen there is work to be done to separate the logic in the `binding.gyp`/`binding.js` files that deals with downloading libvips binaries from any compilation steps.

**Comment by lovell** [comment]
An organisation that uses sharp has offered to sponsor this task so expect some progress and requests to help test, especially on Windows, soon.

**Comment by lovell** [comment]
Work-in-progress branch at https://github.com/lovell/sharp/tree/prebuild

- [x] Move pkgconfig-based libvips detection logic from binding.gyp to JS
- [x] Move download logic from binding.gyp to JS
- [ ] Move Windows-only DLL copy logic from binding.gyp to JS
- [ ] Integrate with prebuild-ci
- [ ] Integrate with prebuild-install
- [ ] Test, test, test

**Comment by elijahbee** [comment]
Can't wait for this, building from source is rather problematic

`Failed at the sharp@0.19.0 install script 'node-gyp rebuild'.`

**Comment by lovell** [comment]
Should anyone be able to help test this, especially those using Windows, please try running the following in a newly-created temporary directory.
```sh
npm install lovell/sharp#prebuild
```
```
yarn add lovell/sharp#prebuild
```
This *should* download and use pre-compiled libvips and sharp binaries.

If a globally-installed copy of libvips is detected then it will intentionally fallback to building sharp from source.

If it works, please +1 this comment.

If it doesn't work, please add a comment with full details of the platform used, all relevant version numbers and a link to a Gist with the install log.

**Comment by lovell** [comment]
Success on Windows, finally.

Here's the log when installing on a fresh Windows machine without MSVC etc.

```sh
C:\Temp>node -v
v9.5.0

C:\Temp>npm install lovell/sharp#prebuild

> sharp@0.20.0-prebuild.test.1 install C:\Temp\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.6.1/libvips-8.6.1-win32-x64.tar.gz
info sharp Creating C:\Temp\node_modules\sharp\build\Release
info sharp Copying DLLs from C:\Temp\node_modules\sharp\vendor\lib to C:\Temp\node_modules\sharp\build\Release
prebuild-install info begin Prebuild-install version 2.5.0
prebuild-install info looking for local prebuild @ prebuilds\sharp-v0.20.0-prebuild.test.1-node-v59-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\...\AppData\Roaming\npm-cache\_prebuilds\https-github.com-lovell-sharp-releases-download-v0.20.0-prebuild.test.1-sharp-v0.20.0-prebuild.test.1-node-v59-win32-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ C:\...\AppData\Roaming\npm-cache\_prebuilds\https-github.com-lovell-sharp-releases-download-v0.20.0-prebuild.test.1-sharp-v0.20.0-prebuild.test.1-node-v59-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Temp\node_modules\sharp\build\Release\sharp.node
prebuild-install info unpack required C:\Temp\node_modules\sharp\build\Release\sharp.node successfully
prebuild-install info install Successfully installed prebuilt binary!

+ sharp@0.20.0-prebuild.test.1
added 70 packages in 43.907s
```

**Comment by xcb6** [comment]
win7, node -v (v8.9.3) => install ok 
thanks

**Comment by MatousLeadPages** [comment]
win10, node -v (v8.9.4) => works great

**Comment by KyleAMathews** [comment]
Tested on mac and it worked perfectly (well... once I deleted the global libvips install I forgot I had :-))

**Comment by kolpav** [comment]
win10, v9.6.0, works perfectly

**Comment by Prozi** [comment]
Win10 finally without problems <3

**Comment by pronebird** [comment]
Does one still need to compile libvips for prebuilt to work?

**Comment by lovell** [comment]
@pronebird sharp has provided a prebuilt libvips since v0.15.0 for most platforms.

> "If a globally-installed copy of libvips is detected then it will intentionally fallback to building sharp from source." https://github.com/lovell/sharp/issues/186#issuecomment-362691105

So if for whatever reason you are still compiling libvips and installing it globally then the prebuilt sharp has to be ignored and instead will be compiled against and linked with the global libvips version.

**Comment by pronebird** [comment]
@lovell I wasn't aware of this. 

Not that long ago I started seeing this error on my heroku-16 instance:

```
Error: libvips-cpp.so.42: cannot open shared object file: No such file or directory
```

**Comment by pronebird** [comment]
Unless I miss something you don't seem to have any build scripts in `package.json`. I have very little understanding how you even compile anything then or whatever. Switching from `yarn` to `npm` solved the problem. Waaaaat?

**Comment by lovell** [comment]
The `prebuild` branch has now been merged to the `master` branch and will shortly be released as v0.20.0.

```sh
npm install lovell/sharp
```
```sh
yarn add lovell/sharp
```

**Comment by pronebird** [comment]
@lovell does it change anything in terms of configuration or what's the benefit?

**Comment by pronebird** [comment]
@lovell ah right so it was still compiling sharp even though vips binaries were prebuilt. 👍

**Comment by lovell** [comment]
v0.20.0 is now available, thanks everyone for feedback/testing, and a big thank you to the sponsor of this work (that wishes to remain anonymous for now).
