### ISSUE TITLE
AWS Lambda Sam Local Layers "Runtime.ExitError"

### ISSUE THREAD

**Issue by surajndk** [lovell/sharp#1862]
Hi, I'm getting the following error while I was trying to deploy the sharp dependencies layers to AWS lambda. I have followed the instructions given at "https://sharp.pixelplumbing.com/en/stable/install/#aws-lambda". But there was no luck.
It works when I use it directly without any layers (Both SAM local and AWS Lambda).

> {
>   "errorType": "Runtime.ExitError",
>   "errorMessage": "RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72 Error: Runtime exited without providing a reason"
> }

Please help

**Comment by lovell** [comment]
What did AWS Support say when you asked them? How do you know that sharp is responsible for this message?

**Comment by surajndk** [comment]
I have not yet reached out to support as I'm getting this error by just adding the piece of code `const sharp = require("sharp");` into the program. Also tried it on an existing working code and gotten the same result. When I add the sharp dependencies directly to the app code, then there is no issue. It's happening only on layers.

**Comment by lovell** [comment]
Are you able to provide complete, standalone configuration and code that allows someone else to reproduce this problem?

**Comment by sbauschl** [comment]
I was just working with this yesterday and got it to work. I'm assuming you built the package on an ec2 machine that mimics the deployment environment first, but it sounds like you got it working directly. But anyways, package structure is VERY important. Make sure it is something like this zippedModuleName.zip -> nodejs -> node_modules

**Comment by surajndk** [comment]
@lovell  @sbauschl 
The error is happening on my local machine (Ubuntu 18.04). I have uploaded the layers to AWS lambda and in my SAM project I'm referring the layer with lambda arn. So when I run `sam local start-api`, it will automatically download and cache layers to the local machine. I followed the same folder structure as mentioned (just like the other working layers in the project)
Please take note, I'm not using serverless.com template instead the AWS default serverless approach (SAM)

**Comment by lovell** [comment]
@surajndk Were you able to make any progress with this?

**Comment by surajndk** [comment]
@lovell unfortunately, no :( . I had to create a separate project just handle the image processing by including all the sharp dependencies within the project.

**Comment by lovell** [comment]
Thanks for the update. Feel free to re-open with complete, standalone configuration and code that allows someone else to reproduce this problem if you'd like further help.

**Comment by haayhappen** [comment]
This is giving me a headach too. It seems to be connected to #1459 
I got the error statet in 1459 and when i removed vendor folder this error message popped up: Runtime.ExitError
