### ISSUE TITLE
SVG: CSS parsing error for custom properties/vars

### ISSUE THREAD

**Issue by sbauschl** [lovell/sharp#1864]
sharp does not correctly parse a svg with more complex css. For instance using the follow style in my svg causes the styles not to be applied with the following error:

<![CDATA[

 * {
    --hat-base: #FF88F9;
    --hat-accent: #A66EFF;
    --medallion-base: #A66EFF;
    --collar-base: #FF88F9;
    --cape-base: #A66EFF;
    --pants-base: #FF88F9;
    --boot-base: #9B4F40;
    --boot-accent: #C17D49;
    --hands-base: #FFFFFF;
    --hands-accent: #FF88F9;
    --wand-accent: #A66EFF;
}

 /*  L02 Legs/Pants  */
#legs #base {
    fill: var(--pants-base);
} 
]]>
_rest of file..._

(sharp:11024): librsvg-WARNING **: 18:07:56.250: CSS parsing error
(sharp:11024): librsvg-WARNING **: 18:07:56.254: CSS parsing error
(sharp:11024): librsvg-WARNING **: 18:07:56.255: CSS unrecoverable error

parsing error: 4:1:could not recognize next production
parsing error: 5:5:while parsing rulset: current char must be a '}'
parsing error: 5:4:while parsing declaration: next property is malformed

Assuming it's an underlying library issue. But I don't know how to fix it. Happens both on local windows 10 machine and remote AWS node. Thanks!

**Comment by lovell** [comment]
Are you able to provide a sample image that helps explain the problem?

**Comment by sbauschl** [comment]
of course! https://storage.opensea.io/0x2f4bdafb22bd92aa7b7552d270376de8edccbc1e/214-1567513338.svg is an example.

**Comment by lovell** [comment]
Thanks, the definition of CSS vars within this SVG is causing the problem, and will be dependent on an upstream task in librsvg - see https://gitlab.gnome.org/GNOME/librsvg/issues/237

As a workaround, removing the  `* { --hat-base: #2B2B2B; ... }` rule allows librsvg and therefore sharp to rasterise this SVG.

**Comment by sbauschl** [comment]
Thanks for the reply. However I really need them colored correctly. That basically just makes my svgs grayscale. Any easy way to fix that?

**Comment by lovell** [comment]
Perhaps pre-process the CSS using something like https://github.com/postcss/postcss-custom-properties first?

**Comment by lovell** [comment]
https://gitlab.gnome.org/GNOME/librsvg/-/issues/237 has been implemented and the sample image in this issue now works with the prebuilt binaries provided by the latest v0.26.0.
