### ISSUE TITLE
how to set input width and height when composite  image by background

### ISSUE THREAD

**Issue by JakinMiao** [lovell/sharp#1865]
how to set input width and height when composite  image by background

i can't resolve how to set square image to circle and  setting size by sharp

**Comment by JakinMiao** [comment]
![bug](https://user-images.githubusercontent.com/20729564/64613156-104fc180-d408-11e9-8d41-18e9901e9b5c.jpg)
I want to get a circle headimage

**Comment by lovell** [comment]
There's an example of applying rounded corners in the README - see https://github.com/lovell/sharp/blob/master/README.md#stream

I'm not quite sure I entirely understand what's required here but you may need two pipelines, one to apply the rounded corners to the "headimage" and a second to composite the resulting image over a background.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further help is required.
