### ISSUE TITLE
Is there a way to get an "Uint8ClampedArray" and create a sharp from it?

### ISSUE THREAD

**Issue by Darking360** [lovell/sharp#1868]
# What are you trying to achieve?

I'm trying to do some transformations to get a `Uint8ClampedArray ` since I need it to run `blurhash` on it, a blur library you can find [here](https://github.com/woltapp/blurhash/tree/master/TypeScript), but to get the `Uint8ClampedArray` I need to run some transformation from the `UInt8Array` that I get from running `.raw()` function.

Is there a way where I can get a `Uint8ClampedArray` from the sharp library, and set a sharp from a `Uint8ClampedArray`? Since I need to run this backward to get a base64 image at the very end?

# Have you searched for similar questions?

Yes, no luck so far, I was wondering maybe the creator or mantainers of the library can have a clue on this.

# Are you able to provide a standalone code sample that demonstrates this question?

```
const { data, info } = await sharp('input.jpg')
  .raw()
  .toBuffer({ resolveWithObject: true });
data.toClampedArray() // This is the method or hack I'm looking for
```

# Are you able to provide a sample image that helps explain the question?

No.

**Comment by lovell** [comment]
The Node.js `Buffer` type is already 8-bit unsigned so using something like `Uint8ClampedArray.from(data)` should "just work".

**Comment by lovell** [comment]
Hope this helped, please reopen with more details if not.

**Comment by Russell-Tran** [comment]
I can confirm this conversion is correct, thank you! However, not quite close enough to my needs. (Sorry to hijack this thread, but my problem also involves `Uint8ClampedArray` from `sharp`, so thought it good to continue here).   

I need `Uint8ClampedArray` as an input to jsQR, and I'm running into the same issue as: https://stackoverflow.com/questions/52194980/in-node-js-why-isnt-my-qr-code-being-read-correctly

It seems one potential answer is given as:
> Busy day... The "Malformed data passed to binarizer" error happens when height/width don't match up with the data you are passing. I might be wrong, but toRGBA8 returns 4 channels (rgba) where only 3 channels (rgb) are expected. – Thomas R. Koll Nov 6 '18 at 16:57

@lovell, do you happen to know if the `Buffer` output from `sharp('input.jpg').toBuffer()` is 4 channels (rgba) or 3 channels (rgb)? If rgba, is there a way to output rgb? Thank you!

**Comment by Russell-Tran** [comment]
Solved, it seems `.raw()` is simply needed in `sharp('input.jpg').raw().toBuffer()` to get everything to be compatible with jsQR. Thank you anyway, and hope this helps someone in the future.

**Comment by wmertens** [comment]
For future reference, this is how to calculate a 4x4 blurhash under Node using sharp and [blurhash](https://github.com/woltapp/blurhash/tree/master/TypeScript):

```js
const buf = await sharp('image.jpg').resize(64,64).ensureAlpha().raw().toBuffer()
const hash = await blurhash.encode(Uint8ClampedArray.from(buf), 64, 64, 4, 4)
```

I'm ignoring aspect ratio since it's all super blurry of course.

**Comment by wmertens** [comment]
But also note you can use a data URI as a backdrop and get a JS-less blurry preview. You need an image, which is much bigger than a blurhash, but still smallish (200 bytes or so), and with some cut'n'pasting you only need to store a part of that (https://github.com/joe-bell/plaiceholder/discussions/226)
