### ISSUE TITLE
PPA for Travis

### ISSUE THREAD

**Issue by automata** [lovell/sharp#187]
Is there any PPA available for Travis building instead the preinstall script?

**Comment by lovell** [comment]
Hi Vilson, I'm not aware of a PPA for Ubuntu 12.04 as used Travis.

Amongst many other packages, https://launchpad.net/~dhor/+archive/ubuntu/myway provides a pre-compiled libvips-dev and dependencies for 14.04 and 14.10.

If you know of one or would be willing to maintain one, I'd be very happy to use it :)

**Comment by gasi** [comment]
+1 for being able to install `sharp` on Travis CI’s new `sudo`-less container infrastructure: http://docs.travis-ci.com/user/workers/container-based-infrastructure/ Unfortunately, `preinstall.sh` currently requires `sudo`. We were forced to use the new infrastructure due to some other dependency (Sauce Connect) not working well on the old Travis infrastructure but I will give it another shot. Is there a way to make `preinstall.sh` work without `sudo`?

**Comment by lovell** [comment]
@gasi I believe PPAs require sudo access so this probably won't help you.

#42 is the best place to discuss non-root installation of libvips and #186 is the most tempting solution I've seen so far.

**Comment by gasi** [comment]
Small update: We’ve opted back into `sudo: required` on Travis and `preinstall.sh` works. However, all dependencies are installed via `apt-get` but `libvips` itself is compiled from source which unfortunately adds several minutes to our build process. When I add the following for Travis’ Debian _Precise_:
```
        precise|wheezy|maya)
          # Debian 7, Ubuntu 12.04, Mint 13

          # ...

          echo "Installing libvips via apt-get"
          apt-get install -y libvips-dev libgsf-1-dev
```

it seems to install `libvips` successfully but `sharp`’s build process fails with the message:

```
Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
```

Any suggestions on how to install via `apt-get` on Travis to avoid long compilation time?

**Comment by lovell** [comment]
I still believe #186 provides the best (potential) solution to avoid users having to compile dependencies *and* allow sudo-less installation.

**Comment by lovell** [comment]
For Ubuntu 12.04, a pre-compiled v7.40.6 of the libvips-dev package and friends are now available via:
```sh
sudo add-apt-repository ppa:lovell/precise-backport-vips
```
...and for Ubuntu 14.04:
```sh
sudo add-apt-repository ppa:lovell/trusty-backport-vips
```
This is the most recent version of vips that I can get to package correctly (dependencies etc.)

I can't use this PPA for sharp itself as the functional tests require v7.42.0+.

**Comment by gasi** [comment]
@lovell This is great — I just tested it and it works! :+1: 

For anyone else, who needs VIPS on Travis, ensure the following in `.travis.yml`:

1. Enable `sudo: required` 
2. Optional: 

          # Suggested setting for `apt`:
          # http://docs.travis-ci.com/user/caching/#Caching-Ubuntu-packages
          cache: apt

3. Install VIPS using PPA:

          before_install:
            - echo "Installing libvips..."
            - sudo add-apt-repository -y ppa:lovell/precise-backport-vips
            - sudo apt-get update
            - sudo apt-get install -y libvips-dev
            - echo "Completed libvips installation."

@lovell In order to use Travis’ more modern container-based infrastructure (using Docker), we’d need to add your PPA to this whitelist: https://github.com/travis-ci/apt-package-whitelist

See: http://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F

Want me to do it or would you like to?

**Comment by lovell** [comment]
@gasi If you're a paying customer of Travis then it makes sense for you to make this request. I can see one other PPA in the "whitelist", namely [libssl-dev/lucid](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise#L5378), so I guess its inclusion should be OK.

**Comment by gasi** [comment]
@lovell Thanks, I submitted it as travis-ci/travis-ci#4398. In the meantime, I learned that one can compile from source and then cache that:

- http://docs.travis-ci.com/user/migrating-from-legacy/#How-Do-I-Install-Custom-Software%3F
- http://docs.travis-ci.com/user/migrating-from-legacy/#How-Do-I-Cache-Dependencies-and-Directories%3F

I don’t have time to explore that at this point but if anyone wants to, this could get us back onto Travis’ container infrastructure (`sudo: false`).

**Comment by nordisk** [comment]
Are there any news on this topic? The `sudo preinstall.sh` is blocking our deployment from being moved to the newer Travis container infrastructure.

Thanks.

**Comment by lovell** [comment]
@nordisk I notice you've found and commented on https://github.com/travis-ci/apt-source-whitelist/issues/68 :)

**Comment by nordisk** [comment]
Aye. Still not sure how to proceed on this one tho :)

**Comment by lovell** [comment]
https://github.com/travis-ci/apt-source-whitelist/pull/137

**Comment by nordisk** [comment]
@lovell He told me that actually after I used sharp for one of our tools and he saw you as the author :)

**Comment by lovell** [comment]
If you've not already seen it, please subscribe to #42 for updates about the forthcoming dependency-less installation of sharp. This will allow for sudo-less operation on Travis CI e.g. https://travis-ci.org/lovell/sharp/jobs/87978123

**Comment by lovell** [comment]
Last call for comments on #42.

**Comment by lovell** [comment]
I'll be closing this question soon as v0.12.0 (and the current master branch) no longer require root/sudo access on 64-bit Linux, which includes Travis.

**Comment by nordisk** [comment]
Cheers!

**Comment by lovell** [comment]
v0.12.0 now available via npm

**Comment by nordisk** [comment]
Aces! thanks for the great work @lovell
