### ISSUE TITLE
Extract Issue

### ISSUE THREAD

**Issue by SjsolisZXA** [lovell/sharp#1872]
Hello,

So I have a method that extracts an image in C# based on the x1,y1,x2,y2 cords of an image, but sometimes it does not work. It seems like if I try extracting near the bottom or the right edge of the image it will fail. Is there a reason why it would work sometimes? The cords are always in bounds of the image.  Not sure if this is an issue with you guys or awslabs, but figured I posted here too.

Using AWS Serverless Image Handler V4 (which uses Sharp.js)

```
public string GetCropedImage(string bucketName, string key, string x1, string y1, string x2, string y2)
        {
            int X1 = Int32.Parse(x1);
            int Y1 = Int32.Parse(y1);

            int X2 = Int32.Parse(x2);
            int Y2 = Int32.Parse(y2);

            string mod =
            "{" +
                "\"bucket\":\"" + bucketName + "\"," +
                "\"key\":\"" + key + "\"," +
                "\"edits\":{" +
                    "\"extract\":{" +
                        "\"left\":" + X1 + "," +
                        "\"top\":" + Y1 + "," +
                        "\"width\":" + X2 + "," +
                        "\"height\":" + Y2 + "" +
                    "}" +
                "}" +
            "}";

            byte[] toEncodeAsBytes = ASCIIEncoding.ASCII.GetBytes(mod);
            string encriptedString = Convert.ToBase64String(toEncodeAsBytes);

            return imageHandlerURL + encriptedString;
        }
```

**Comment by lovell** [comment]
Cross-posted at https://github.com/awslabs/serverless-image-handler/issues/150

Please feel free to re-open with more details if the problem is later determined to be due to sharp itself.
