### ISSUE TITLE
How to know when an image is already compressed or doesn't need to be compress ?

### ISSUE THREAD

**Issue by stat1k** [lovell/sharp#1873]
Hello,
Like the title said, is it possible to know when an image doesn't need to be compress ? 
Because, if I reupload an already compressed file, I dont want it to be compressed again.

Other question, in my project, we let users upload their images in different formats and size, for you, what is the best settings ? 

For now, I have this settings for the jpeg : 

`sharp().jpeg({ progressive:true, quality: 80, force: true })`

Is this the best way ?

Thanks a lot for your time and effort in this module !

**Comment by lovell** [comment]
If the question here is _"how do I know the 'quality' value used for a given JPEG?"_ then please see #908 for why this is not possible.

**Comment by lovell** [comment]
Hope this helped, please reopen with more details if not.
