### ISSUE TITLE
Get difference from 2 images

### ISSUE THREAD

**Issue by zdev90** [lovell/sharp#1874]
Hi, 

I'm trying to get difference from two images. What I want is to get updated section of image2 compared to image1.

I tried sth like this:
sharp(image2)
  .composite([{
      input: image1,
      blend: 'difference'
  }])

This returns colors affected(Not an ordinary color from image2) and black background for the duplicated pixel(I want those to be transparent).

https://i.stack.imgur.com/vkh3S.png
something like above but instead of black background, I need transparent background.

I've tried some color and channel operators and no luck yet. 
Can you please guide me if u have any clue ? 

Many thanks in advance.

**Comment by lovell** [comment]
Hi, there's a future possible enhancement detailed at https://github.com/lovell/sharp/issues/284 that might provide what you're looking for.

**Comment by mooyoul** [comment]
or you can use [pixelmatch](https://github.com/mapbox/pixelmatch) to compute visual difference between two images. I use pixelmatch for testing & visualize visual regression of our media service outputs.

**Comment by lovell** [comment]
Let's track this at the existing #284.
