### ISSUE TITLE
VipsJpeg: Premature end of JPEG file Error message when running sharp nodejs app on AWS lambda

### ISSUE THREAD

**Issue by guneetsinghbhatia** [lovell/sharp#1878]
I have a issue resizing jpeg image to size 160X149 when running code on aws lambda.

Where as same image is processing fine on my local.

Error message on AWS lambda is shared below . But I am not getting any error in my local.
![download1-265be29445c542cdb99f9148ff879081](https://user-images.githubusercontent.com/14793330/65264453-a22c8e00-dadc-11e9-970f-6dd4979439b5.jpeg)

2019-09-19T16:39:40.978Z 9fc0fd4f-c625-4596-9e89-e7656947e7a3
{
    "errorMessage": "VipsJpeg: Premature end of JPEG file\n",
    "errorType": "Error",
    "stackTrace": [
        ""
    ]
}

Code --

"use strict";
process.env.VIPS_DISC_THRESHOLD = '600m';

const AWS = require("aws-sdk");
const S3 = new AWS.S3({
  signatureVersion: "v4"
});
const Sharp = require("sharp");
const stats = Sharp.cache();
const threads = Sharp.concurrency();
console.log(stats, ": stats");
console.log(threads, ": threads");

const BUCKET = process.env.BUCKET;
const URL = process.env.URL;

exports.handler = function(event, context, callback) {
  console.log("key" + event.queryStringParameters);
  const key = event.queryStringParameters.key;
  const match = key.match(/(\d+)x(\d+)\/(.*)/);
  const width = parseInt(match[1], 10);
  const height = parseInt(match[2], 10);
  const originalKey = match[3];
  console.log("New");
  console.log(BUCKET, ": BUCKET");
  console.log(match, ": match");
  console.log(width, ": width");
  console.log(height, ": height");
  console.log(originalKey, ": originalKey");
  console.log(URL, ": URL");

  console.log("getting before getObject");
  S3.getObject({ Bucket: BUCKET, Key: originalKey })
    .promise()
    .then(data => {
      console.log("getting inside getObject");
      return Sharp(data.Body)
        .resize(width, height, {
          fit: Sharp.fit.inside, // Preserve aspect ratio
          background: { r: 0, g: 0, b: 0, alpha: 0 }
        }) // Transparent canvas
        .toFormat(Sharp.format.png) // PNG to preserve transparency
        .toBuffer();
      console.log("getting after getObject");
    })
    .then(buffer => {
      console.log("getting in then1");
      S3.putObject({
        Body: buffer,
        Bucket: BUCKET,
        ContentType: "image/png",
        Key: key
      }).promise();
      console.log("getting in then2");
    })
    .then(() => {
      console.log("getting in callbaack1");
      callback(null, {
        statusCode: "301",
        headers: { location: `${URL}/${key}` },
        body: ""
      });
      console.log("getting in callbaack2");
    })
    .catch(err => callback(err));
  console.log("end of function");
};

**Comment by lovell** [comment]
Hello, the input image is not a valid JPEG, please see #1859

**Comment by guneetsinghbhatia** [comment]
Thanks for the quick reply .  This solution is working for Jpeg images but not for PNG images 

{
    "errorMessage": "vips2png: unable to write to buffer\n",
    "errorType": "Error",
    "stackTrace": [
        ""
    ]
}

**Comment by lovell** [comment]
Please can you provide a sample PNG image that fails in this manner.

**Comment by guneetsinghbhatia** [comment]
![atp-source](https://user-images.githubusercontent.com/14793330/65279000-3d346080-dafb-11e9-9357-1ebb4bdf28b8.png)

**Comment by lovell** [comment]
That PNG image looks OK to me. Is there enough memory assigned? Please can you remove all the AWS logic to see if you can reproduce this problem using only sharp itself.

**Comment by guneetsinghbhatia** [comment]
Yes we have assigned 1536 MB memory on Lambda . i am able to resize this image locally on MAC .
But resize fails on Lambda environment

**Comment by guneetsinghbhatia** [comment]
Logs from AWS
2019-09-19T20:32:08.571Z 9b0397e7-8460-4016-9f50-78c944a3c323 { memory: { current: 0, high: 0, max: 50 },
files: { current: 0, max: 20 },
items: { current: 0, max: 100 } } ': stats'
2019-09-19T20:32:08.573Z 9b0397e7-8460-4016-9f50-78c944a3c323 2 ': threads'

2019-09-19T20:32:08.575Z 9b0397e7-8460-4016-9f50-78c944a3c323 [ '160x149/attachments/images/origin/atp-source-86b94ee29b75422ea9658b0d3d026653.png',
'160',
'149',
'attachments/images/origin/atp-source-86b94ee29b75422ea9658b0d3d026653.png',
index: 0,
input: '160x149/attachments/images/origin/atp-source-86b94ee29b75422ea9658b0d3d026653.png' ] ': match'
2019-09-19T20:32:08.576Z 9b0397e7-8460-4016-9f50-78c944a3c323 160 ': width'
2019-09-19T20:32:08.576Z 9b0397e7-8460-4016-9f50-78c944a3c323 149 ': height'
2019-09-19T20:32:08.576Z 9b0397e7-8460-4016-9f50-78c944a3c323 attachments/images/origin/atp-source-86b94ee29b75422ea9658b0d3d026653.png : originalKey
2019-09-19T20:32:08.576Z 9b0397e7-8460-4016-9f50-78c944a3c323 https://dbnet8wpxx7xk.cloudfront.net : URL
2019-09-19T20:32:08.576Z 9b0397e7-8460-4016-9f50-78c944a3c323 getting before getObject
2019-09-19T20:32:08.616Z 9b0397e7-8460-4016-9f50-78c944a3c323 end of function
2019-09-19T20:32:08.737Z 9b0397e7-8460-4016-9f50-78c944a3c323 getting inside getObject
2019-09-19T20:32:08.755Z 9b0397e7-8460-4016-9f50-78c944a3c323
{
    "errorMessage": "vips2png: unable to write to buffer\n",
    "errorType": "Error",
    "stackTrace": [
        ""
    ]
}

END RequestId: 9b0397e7-8460-4016-9f50-78c944a3c323
REPORT RequestId: 9b0397e7-8460-4016-9f50-78c944a3c323 Duration: 181.65 ms Billed Duration: 200 ms Memory Size: 1536 MB Max Memory Used: 84 MB Init Duration: 244.75 ms
XRAY TraceId: 1-5d83e5c6-15f39a70150da699ee11d7d7 SegmentId: 5808dbd87b6e4b78 Sampled: false
Loading newer events...

**Comment by guneetsinghbhatia** [comment]
memory: { current: 0, high: 0, max: 50 } this is coming when i add const stats = Sharp.cache(); in my code does this mean max memory size is 50 MB.  If yes how can I increase it?
