### ISSUE TITLE
NodeJS v0.12 Cluster Mode - undefined symbol: node_module_register 

### ISSUE THREAD

**Issue by iq-dot** [lovell/sharp#188]
As the title says, when I run our app in cluster mode using NodeJS v0.12 I get the above error:

uncaughtException: /opt/builds/CURRENT/node_modules/sharp/build/Release/sharp.node: undefined symbol: node_module_register

However if I run this without clustering turned on, then it is fine, no errors.

For additional information I am using PM2 for my process management which also handles the cluster or normal fork mode.

**Comment by lovell** [comment]
Hi Iqbal, that error message looks like the sort of problem you might encounter when an addon is compiled against one version of Node and run against another.

Might a fresh installation/compilation via something like `rm -rf node_modules;npm install` help here?

**Comment by iq-dot** [comment]
Hi Lovell,

I did try that, unfortunately no luck, I am using NVM to manage my node versions while my system version is Node 0.10.

I don't suppose that should cause a problem should it when compiling sharp? I have set the node version to 0.12 using NVM so unless somehow sharp is still using the system wide installation.

Though node -v will give me 0.12.

**Comment by lovell** [comment]
The version of Node made available to node-gyp when `npm install` is used needs to match the version of Node at runtime.

It might be that there's a global node-gyp being picked up. `npm uninstall -g node-gyp` should remove it if so.

**Comment by iq-dot** [comment]
I've checked, no global node-gyp installed, could there be anything else you suspect?

**Comment by lovell** [comment]
> "I have set the node version to 0.12 using NVM so unless somehow sharp is still using the system wide installation."

`node_module_register` was [added to Node](https://github.com/joyent/node/commit/76b98462e589a69d9fd48ccb9fb5f6e96b539715) in v0.11.11 so sharp has been compiled against that version or later but is being run against an earlier version.

My best guess is that sharp is using 0.12 but pm2 is using 0.10.

**Comment by iq-dot** [comment]
Yes your right PM2 was using an older version, though the error was a bit misleading.

**Comment by lovell** [comment]
Glad to hear you got it working.
