### ISSUE TITLE
fatal error: 'vips/vips8' file not found

### ISSUE THREAD

**Issue by midgethoen** [lovell/sharp#1882]
I'm having problems installing sharp in a clean node:12 container. 

```
docker run --rm -it node:12 npm i sharp

> sharp@0.23.0 install /node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linux-x64.tar.gz
prebuild-install WARN install libvips-cpp.so.42: cannot open shared object file: No such file or directory
make: Entering directory '/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:25:22: fatal error: vips/vips8: No such file or directory
 #include <vips/vips8>
                      ^
compilation terminated.
sharp.target.mk:135: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: *** [Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.0.0-29-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/sharp
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.23.0 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.23.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-23T18_08_09_973Z-debug.log
```

The issue is quite unfamiliar to me and i havent find the cause yet. Im posting early hoping somebody can point me in the right direction.

**Comment by 8shaks** [comment]
![image](https://user-images.githubusercontent.com/40652815/65451473-3fedc900-de0d-11e9-82e4-bf44113cc53f.png)

I'm getting this issue too when trying to push to heroku.

**Comment by rrohan92** [comment]
I'm getting the same issue.

**Comment by jbdutton** [comment]
Also seeing this attempting to install `sharp@0.22.1` in a Google Cloud Function running Node 8:

```
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-linux-x64.tar.gz
prebuild-install
WARN install libvips-cpp.so.42: cannot open shared object file: No such file or directory
../src/common.cc:25:10: fatal error: vips/vips8: No such file or directory
 #include <vips/vips8>
^~~~~~~~~~~~
compilation terminated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-1044-gcp
gyp ERR! command \"/usr/bin/node\" \"/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /workspace/node_modules/sharp
gyp ERR! node -v v8.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.22.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
We've been running on this specific version of Sharp / Node / GCF for awhile now without any issues, it just began today.

**Comment by ChrisCates** [comment]
Guys, please review the documentation and use a libvips compatible container: https://github.com/TailorBrands/docker-libvips

**Comment by sidiliu** [comment]
Get the same issue without installing it on docker

**Comment by Workito** [comment]
I have same issue, without docker.

**Comment by hfukada** [comment]
for Ubuntu users: `apt install libvips-dev` fixes the issue for us.

**Comment by lovell** [comment]
There have been no changes to sharp or the prebuilt binaries since 29th July.

I've received about 30 emails and notifications about this problem within the last hour so would expect this to relate to a (transient) dependency that has been published within the last couple of hours.

**Comment by imkane** [comment]
Why would you close this without at least attempting to provide some guidance? You can see there's MANY people having this issue.

**Comment by lovell** [comment]
Whatever is causing this problem, it looks like it's affecting pretty much every native node module that provides prebuilt binaries

https://github.com/mapbox/node-pre-gyp/issues/477
https://github.com/mapbox/node-sqlite3/issues/1222

@imkane This issue is not closed, I am actively working on investigating it right now.

**Comment by imkane** [comment]
Sorry, my mistake! I misread the referenced issue statues. Good luck!

**Comment by emplums** [comment]
Is there any way to work around this for now?

**Comment by adamlacombe** [comment]
So far I've tried installing libvips-dev (https://github.com/lovell/sharp/issues/1882#issuecomment-534241405) and glib2.0-dev (https://github.com/lovell/sharp/issues/1148#issuecomment-370688930).

```dockerfile
FROM node:10
...
RUN apt-get update && apt-get install -y glib2.0-dev libvips-dev
...
RUN npm --build-from-source install
```

and the result is still:
```
> sharp@0.21.3 install /usr/src/app/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.0/libvips-8.7.0-linux-x64.tar.gz
make: Entering directory '/usr/src/app/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
In file included from ../src/common.cc:25:0:
/usr/include/vips/vips8:35:25: fatal error: glib-object.h: No such file or directory
 #include <glib-object.h>
                         ^
compilation terminated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
sharp.target.mk:128: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: Leaving directory '/usr/src/app/node_modules/sharp/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.43-microsoft-standard
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/app/node_modules/sharp
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by gate8team** [comment]
This one did help so far:

```
...
RUN apt-get update && apt-get install -y libvips-dev --no-install-recommends
...
```

**Comment by rrohan92** [comment]
Just ran:
```
apt-get update && apt-get install -y libvips-dev --no-install-recommends

```

and then

```
npm install sharp

```

Still got the same error.

**Comment by imkane** [comment]
> This one did help so far:
> 
> ```dockerfile
> ...
> RUN apt-get update && apt-get install -y libvips-dev --no-install-recommends
> ...
> ```

Not for us :(

**Comment by timothyallan** [comment]
Strange. `libvips-dev` on Docker with Node 12.10.0 image fixed it up for me.

**Comment by lovell** [comment]
My current line of inquiry is that this relates to a recent change in one of the dependencies used to unpack tar files. For example, the [minipass](https://www.npmjs.com/package/minipass) dependency, which is a dependency of [tar](https://www.npmjs.com/package/minipass) was published an hour ago.

**Comment by christianbundy** [comment]
Out of desparation I tried Yarn and I'm surprised to report that it works for me.

I installed on Debian Buster from [these instructions](https://yarnpkg.com/lang/en/docs/install/#debian-stable) and when I ran `yarn` it installed all of my modules without any problems. For what it's worth, I can confirm these things don't work (for me):

- changing Node version (node 10 and 12 both broken)
- using `npm install --sharp-cxx11=1`
- installing `libvips`, `libvips-dev`, or removing both
- turning it off and back on again

Of course, using Yarn is just a temporary workaround, but it might help if you're in a pinch.

@lovell Thanks so much for your work on this module!

**Comment by rrohan92** [comment]
Yes it worked on Docker with Node 12.10.0 image with libvips-dev.

**Comment by lovell** [comment]
It looks like commit https://github.com/isaacs/minipass/commit/40e1d612d3d58e415362b1ebb97df8b69da5374f has collided with https://github.com/mafintosh/end-of-stream/issues/11

Pinning minipass to v2.7.0 should workaround this for now.

**Comment by evallgar** [comment]
Follow up on this issue here:
[https://github.com/isaacs/minipass/issues/9](https://github.com/isaacs/minipass/issues/9)

**Comment by hypernova7** [comment]
I have same issue, but with NPM. How can i fix this?

**Comment by prescindivel** [comment]
same issue on mac os mojave

**Comment by toxuin** [comment]
I have fixed our CI build by adding following to the `package.json`:
```json
"dependencies": {
  "minipass": "2.7.0",
  "sharp": "^0.23.0"
}
```
It's silly because our app does not depend on `minipass`.

**Comment by Dave-Lindberg** [comment]
On Mac OS Mojave I removed .`npm/_libvips/libvips-8.7.0-darwin-x64.tar.gz` and reinstalled. No luck.

**Comment by Shane325** [comment]
> I have fixed our CI build by adding following to the `package.json`:
> 
> ```json
> "dependencies": {
>   "minipass": "2.7.0",
>   "sharp": "^0.23.0"
> }
> ```
> 
> It's silly because our app does not depend on `minipass`.

This also worked for me.

**Comment by tihuan** [comment]
https://github.com/lovell/sharp/issues/1882#issuecomment-534266128 <-- this worked for me! Thanks so much, @lovell 🙏

**Comment by liudonghua123** [comment]
I have the same problem, it was because my network I couldn't download `libvips-8.8.1-win32-x64.tar.gz` success, So I have to manual download it and put it on `%appdata%/npm-cache/_libvips`.

**Comment by DavidDudson** [comment]
I'm using lerna with npm. For those who are using npm and not yarn.

Add minipass as a dependency or dev-dependency depending on where your issues lie.

```
"dependencies": {
  "minipass": "2.7.0",
}
```

For me this affects:

- angular-cli/angular-compiler
- grpc
- sharp
- lerna (`@lerna/add`)

**Comment by hypernova7** [comment]
I tried using this in my package.json with webpack, but the problem persists

> "dependencies": {
  "minipass": "2.7.0",
  "sharp": "^0.23.0"
}

**Comment by harrisrobin** [comment]
Adding 
```
  "resolutions": {
    "minipass": "2.7.0"
  }
```

as @lovell suggested worked for me!

**Comment by liudonghua123** [comment]
> Adding
> 
> ```
>   "resolutions": {
>     "minipass": "2.7.0"
>   }
> ```
> 
> as @lovell suggested worked for me!

This works, but the same error when I install `expo-cli`, and I could not apply this patch.

**Comment by auctifera-josed** [comment]
> I have fixed our CI build by adding following to the `package.json`:
> 
> ```json
> "dependencies": {
>   "minipass": "2.7.0",
>   "sharp": "^0.23.0"
> }
> ```
> 
> It's silly because our app does not depend on `minipass`.

This also fixed the installation problem for us

**Comment by hypernova7** [comment]
@lovell minipass does not work in my webpack project, I am using favicons which depends on Sharp.

**Comment by hypernova7** [comment]
This is what the console prints, i using Heroku

```
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  10.x
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 10.x...
       Downloading and installing node 10.16.3...
       Using default npm version: 6.9.0
       
-----> Restoring cache
       - node_modules
       
-----> Installing dependencies
       Installing node modules (package.json)
       
       > sharp@0.22.1 install /tmp/build_729ee095c08666d6b22b28d278a7b552/node_modules/favicons/node_modules/sharp
       > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
       
       info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-linux-x64.tar.gz
       make: Entering directory '/tmp/build_729ee095c08666d6b22b28d278a7b552/node_modules/favicons/node_modules/sharp/build'
         TOUCH Release/obj.target/libvips-cpp.stamp
         CXX(target) Release/obj.target/sharp/src/common.o
       ../src/common.cc:25:10: fatal error: vips/vips8: No such file or directory
        #include <vips/vips8>
                 ^~~~~~~~~~~~
       compilation terminated.
       sharp.target.mk:128: recipe for target 'Release/obj.target/sharp/src/common.o' failed
       make: *** [Release/obj.target/sharp/src/common.o] Error 1
       make: Leaving directory '/tmp/build_729ee095c08666d6b22b28d278a7b552/node_modules/favicons/node_modules/sharp/build'
       gyp ERR! build error 
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit (/tmp/build_729ee095c08666d6b22b28d278a7b552/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
       gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
       gyp ERR! System Linux 4.4.0-1048-aws
       gyp ERR! command "/tmp/build_729ee095c08666d6b22b28d278a7b552/.heroku/node/bin/node" "/tmp/build_729ee095c08666d6b22b28d278a7b552/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       gyp ERR! cwd /tmp/build_729ee095c08666d6b22b28d278a7b552/node_modules/favicons/node_modules/sharp
       gyp ERR! node -v v10.16.3
       gyp ERR! node-gyp -v v3.8.0
       gyp ERR! not ok 
       npm ERR! code ELIFECYCLE
       npm ERR! errno 1
       npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the sharp@0.22.1 install script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.J8tES/_logs/2019-09-24T03_48_38_001Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Comment by xlanor** [comment]
Encountering this issue with turtle-cli. Will attempt the suggested solution and report back

**Comment by edcolyer** [comment]
> I have fixed our CI build by adding following to the `package.json`:
> 
> ```json
> "dependencies": {
>   "minipass": "2.7.0",
>   "sharp": "^0.23.0"
> }
> ```
> 
> It's silly because our app does not depend on `minipass`.

This workaround fixed the issue for us as well

**Comment by xlanor** [comment]
expo-cli does not work even with minipass added into dependencies.

**Comment by hypernova7** [comment]
@lovell minipass already works, I did not see that they omit '^' in the version, and now my application compile correctly

**Comment by RefersToTheLostYouth** [comment]
添加minipass可以正常编译了

**Comment by dlecan** [comment]
This issue is fixed for me with `minipass@^2.8.5` (forced via `resolutions` in `package.json`)

**Comment by midgethoen** [comment]
it works again for me too, even without adding minipass.  thnx for investigating

```$ docker run --rm -it node:12 npm i sharp

> sharp@0.23.0 install /node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linux-x64.tar.gz
npm WARN saveError ENOENT: no such file or directory, open '/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.

+ sharp@0.23.0
added 71 packages from 102 contributors and audited 164 packages in 6.931s
found 0 vulnerabilities
```

**Comment by lovell** [comment]
There was a breaking change in v2.8.2 of the upstream `minipass` dependency that has now been reverted in its v2.8.5 release.

If you work at a for-profit organisation that relies on sharp, and I can tell there are a lot of you based on the sheer volume of emails and notifications I've received about this problem over the last 15 hours, please consider donating to the libvips OpenCollective at https://opencollective.com/libvips to say thank you and help with its continued support.

**Comment by harryhazza77** [comment]
I've removed the resolution for minipass and can confirm it works. Thank you @lovell

**Comment by JandenMa** [comment]
I used `yarn` and `npm i` on my `Gatsby` project, and got the same issue.
