### ISSUE TITLE
Node Server crashes error on build

### ISSUE THREAD

**Issue by anandanguru** [lovell/sharp#1884]
i am getiing error after docker build provided by the given steps which are posted yesterday..

I am getting this error while uploading the document on particular path
**node: symbol lookup error: /node_modules/sharp/build/Release/sharp.node: undefined symbol: _ZN4vips6VImage15new_from_bufferEPKvmPKcPNS_7VOptionE**

**Comment by timothyallan** [comment]
I got this as well after the installation debacle yesterday with #1882 
I had to add`libvips-dev` to the node server build, as well as lock down minipass to ` "minipass": "2.7.0",` in package.json as described in that issue. 
Sharp appeared to install fine, but would crash with that error when used.

**Comment by lovell** [comment]
If you've not done so already, please undo/revert any changes made as a result of the various suggestions from the now-closed #1882.

**Comment by eshton** [comment]
Hey @lovell , I have this exact same issue. I already checked:
- node is running 12.13.1
- minimass is 2.8.5

I still have this error, only in Heroku, works fine on my local machine (Mac).

Thanks for help.

**Comment by lovell** [comment]
@eshton If you still require help, please open a new installation issue and answer all of the questions. https://github.com/lovell/sharp/issues/new?assignees=&labels=installation&template=installation.md&title=
