### ISSUE TITLE
Resized image is moved if compared to resize using regular vips methods

### ISSUE THREAD

**Issue by pigletto** [lovell/sharp#1886]
What is the output of running `npx envinfo --binaries --languages --system --utilities`?

> System:
>     OS: Linux 4.18 Amazon Linux 2
>     CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
>     Memory: 185.93 MB / 15.56 GB
>     Container: Yes
>     Shell: 4.2.46 - /bin/bash
>   Binaries:
>     Node: 10.16.3 - /var/lang/bin/node
>     npm: 6.9.0 - /var/lang/bin/npm
>   Utilities:
>     CMake: 2.8.12.2 - /usr/bin/cmake
>     Make: 3.82 - /usr/bin/make
>     GCC: 7.3.1 - /usr/bin/gcc
>     Git: 2.17.2 - /usr/bin/git
>     Clang: 7.0.1 (Amazon Linux 2 - /usr/bin/clang
>     Subversion: 1.7.14 - /usr/bin/svn
>   Languages:
>     Bash: 4.2.46 - /usr/bin/bash
>     Perl: 5.16.3 - /usr/bin/perl
>     Python: 2.7.16 - /usr/bin/python
>     Python3: 3.7.4 - /usr/bin/python3

What are the steps to reproduce?

1. Create a new image (using any tool, eg. gimp) with the following size: 4360 x 3565 containing white background and some black vertical and horizontal lines. My test image: https://i.postimg.cc/mDRQXbZg/testfile.jpg

1. Resize image using sharp to 512 x 418:
```
let image = sharp('testfile.jpg').resize({
  width: 512,
  height: 418
});
image.toFile('a_testfile.jpg');
```

What is the expected behaviour?
Image should be resized in the same way as it is done using vipsthumbnail or pyvips or gimp  but it is 'moved' when compared to the result of these other tools. Using different values for position or fit doesn't seem to help much, image is still moved or more blurry vs other tools result. The best results I got with:

```
let res = image.resize({
  width: 512,
  height: 418,
  fit: 'cover',
  position: 'left top',
});
```
but it is still worse than pyvips or vipsthumbnail and counterintuitive why other tools work with the default center position and sharp doesnt.

Code used to generate thumbnail with vipsthumbnaill:
  
`  vipsthumbnail testfile.jpg -s 512x418 -m centre -f jpg -o a_testfile_vthumbnail.jpg`

Code used to generate thumbnail using pyvips:
```
import pyvips
im = pyvips.Image.new_from_file('testfile.jpg')
im.resize(512/4360, vscale=418/3565).write_to_file('a_testfile_py.jpg')
```

Are you able to provide a sample image that helps explain the problem?
Gallery with the output images:
1. a_testfile.jpg  - sharp generated
2. a_testfile_gimp.jpg - gimp generated
3. a_testfile_py.jpg - pyvips generated
https://postimg.cc/gallery/gf4t6cgy/

Compare eg. left top corner using zoom, eg. in Gimp

**Comment by lovell** [comment]
Hi, were you able to experiment with the `fastShrinkOnLoad` option?

https://sharp.pixelplumbing.com/en/stable/api-resize/

**Comment by pigletto** [comment]
It is definitely better if fastShrinkOnLoad is disabled. 

With the following settings it is same as using vipsthumbnail etc :

```
let res = image.resize({
  width: 512,
  height: 418,
  fit: 'cover',
  position: 'left top',
  fastShrinkOnLoad: false
});
```

Not sure though, why does vipsthumbnail need **-m centre** and for pyvips' resize centre seems to be default (https://jcupitt.github.io/libvips/API/current/libvips-resample.html#vips-resize says "Downsizing is done with centre convention"), but with sharp I need 'left top'?

Thank you for the quick answer!

**Comment by lovell** [comment]
sharp uses the same underlying `vips_resize` operation as vipsthumbnail, which uses what is known as "centre convention" when downsampling multiple pixels into a single pixel.

The `position` option in sharp refers to any potential crop of whole pixels that occurs after resampling. Perhaps this is where the confusion lies.

**Comment by pigletto** [comment]
Thank you for the responses. I've finally made it work properly for me using fit: 'fill' and fastShrinkOnLoad: false
