### ISSUE TITLE
How to reduce Docker image after installing sharp?

### ISSUE THREAD

**Issue by extensionsapp** [lovell/sharp#1892]
Hello.

**OS:** Alpine 3.10
**Dockerfile**
```
...
RUN set -o pipefail \
    && apk update \
    && apk add vips-dev fftw-dev build-base --update-cache \
        --repository http://dl-3.alpinelinux.org/alpine/edge/community/ \
        --repository http://dl-3.alpinelinux.org/alpine/edge/main
...
```
After install 299 MB:
`4150afe90f70        3 minutes ago       /bin/sh -c set -o pipefail     && apk update…   299MB`

These packages are only needed for building, can uh be removed?
How can I reduce the size of the image?

**Comment by mooyoul** [comment]
You can just install sharp without installing dev libraries  - sharp provides pre-built vips.

<img width="988" alt="스크린샷 2019-09-29 오후 12 21 47" src="https://user-images.githubusercontent.com/2101743/65825592-bed27e00-e2b3-11e9-9087-00b24ed97bb2.png">

**Comment by wouterds** [comment]
Use [multiple build stages](https://docs.docker.com/develop/develop-images/multistage-build/), unrelated to this package.
