### ISSUE TITLE
Module did not self register on Electron 6

### ISSUE THREAD

**Issue by ethan-ou** [lovell/sharp#1896]
When installing sharp using ```npm install```, I'm unable to run an electron application because of this error:

```Something went wrong installing the "sharp" module. Module did not self-register.```

I found however that if I manually copied the prebuilt sharp files into the node_modules folder, sharp began working again. It appears that because of my setup or otherwise, sharp isn't recognising the correct version of electron.

Is there any other way of getting the right version of sharp without using ```electron-rebuild``` or manual copying?

**Comment by lovell** [comment]
Hi, you'll need to use `electron-rebuild`. This is a requirement of using native modules with Electron and is not unique to this module.

https://electronjs.org/docs/tutorial/using-native-node-modules

**Comment by ethan-ou** [comment]
Thanks for confirming. I'll close this issue.
