### ISSUE TITLE
Width, height & orientation in metadata not updated after `rotate()`

### ISSUE THREAD

**Issue by sngsweekeat** [lovell/sharp#1897]
Loaded an image with EXIF orientation indicating it is rotated CW 90deg. At this point, if I call `rotate()`, I expect that the image is rotated to the correct orientation, and also that the width and height metadata to be updated, but they are not. The image data itself is indeed rotated, but the metadata is unchanged.

```javascript
      let md = await normalizedImage.metadata();
      console.log(
        `Before rotate & flatten: ${md.width} x ${md.height} orientation: ${md.orientation}`
      );
      normalizedImage = await normalizedImage
        .rotate()
        .flatten({ background: { r: 255, g: 255, b: 255 } });

      md = await normalizedImage.metadata();
      console.log(
        `After rotate & flatten: ${md.width} x ${md.height} orientation: ${md.orientation}`
      );
```
Console output:
```
Before rotate & flatten: 2640 x 1980 orientation: 8
After rotate & flatten: 2640 x 1980 orientation: 8
```

**Comment by lovell** [comment]
Hi, in this code sample, the reference to `normalizedImage` remains unchanged and still refers to the original unprocessed image (as `flatten` returns the same instance for chaining purposes).

Try something like the following (untested):

```javascript
      const processedImage = await normalizedImage
        .rotate()
        .flatten({ background: { r: 255, g: 255, b: 255 } })
        .toBuffer();

      md = await sharp(processedImage).metadata();
```

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further help is required.

**Comment by mnpenner** [comment]
Hi, I'm trying to do this too. That solution does work, but it requires reading the image data twice. Is there a way to do this without calling `toBuffer()` inbetween?

**Comment by xucongli1989** [comment]
I have a same problem too, because if read twice, it's so slow.

**Comment by lovell** [comment]
Here's a possible approach for combining auto-orient and resize in a single pipeline.
```js
let { width, height, orientation } = await sharp(input).metadata();
if (orientation > 4) {
  [width, height] = [height, width];
}
await sharp(input).rotate().resize({ width, height })...
```
