### ISSUE TITLE
Can the toFile() or sharp() methods handle variables?

### ISSUE THREAD

**Issue by joseph-animasds** [lovell/sharp#1900]
In the toFile method I have a template string with a variable
![image](https://user-images.githubusercontent.com/45604274/66221409-227df200-e68c-11e9-8aec-66f0161a8ff1.png)

What are you trying to achieve?
crop an image
Have you searched for similar questions?
no
The reason for using a variable is because im mapping over the sharp promise and I would use a duplicate cropped image. So I needed to make the cropped image name unique

Are you able to provide a sample image that helps explain the question?
Maybe its the name of the file that it doesnt like? The error I get is this:
![image](https://user-images.githubusercontent.com/45604274/66221449-36c1ef00-e68c-11e9-9b66-98491f66d987.png)
Keep in mind, this works fine when I use a static path to write the file to. like "/opt/croppedImage/test.png", but again, I end up using an image twice when mapping and thats not good.

**Comment by lovell** [comment]
Hi, the appearance of "read error" in the message suggests there's a problem with the input rather than the output file path.

**Comment by joseph-animasds** [comment]
Hi, Thanks for responding quickly. What do you suggest I do?

**Comment by joseph-animasds** [comment]
Seems an issue on my side. Need to have the content of the variable available in time for sharp() to use it. perhaps and if statement or some kind of loop
