### ISSUE TITLE
Sharp as dependency of gatsby-plugin-manifest

### ISSUE THREAD

**Issue by solugebefola** [lovell/sharp#1903]
What is the output of running `npx envinfo --binaries --languages --system --utilities`?
```
System:
    OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (4) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 491.87 MB / 1.95 GB
    Container: Yes
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Utilities:
    Make: 4.1 - /usr/bin/make
    GCC: 6.3.0 - /usr/bin/gcc
    Git: 2.11.0 - /usr/bin/git
  Languages:
    Bash: 4.4.12 - /bin/bash
    Perl: 5.24.1 - /usr/bin/perl
    Python: 2.7.13 - /usr/bin/python
```
What are the steps to reproduce?
Building a Gatsbyjs site using gatsby-plugin-manifest in a docker container
What is the expected behaviour?
Locally, in MacOS, site builds normally.  In a docker container with the above system, build fails with the error:
```
node: symbol lookup error: /builds/project-0/node_modules/sharp/build/Release/sharp.node: undefined symbol: _ZNK4vips6VImage7pngsaveEPKcPNS_7VOptionE
```
Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?
no
Are you able to provide a sample image that helps explain the problem?
no

Additional info:
result of `npm ls sharp`
```
+-- gatsby-plugin-manifest@2.2.20
| `-- sharp@0.23.1  deduped
+-- gatsby-plugin-sharp@2.2.14
| `-- sharp@0.22.1 
+-- gatsby-transformer-sharp@2.2.14
| `-- sharp@0.23.0 
`-- sharp@0.23.1 
```

**Comment by lovell** [comment]
Please can you upgrade `gatsby-plugin-sharp` and `gatsby-transformer-sharp`.

**Comment by solugebefola** [comment]
Success!  Thanks a bunch!
