### ISSUE TITLE
How to resize without crop with center extend?

### ISSUE THREAD

**Issue by Dwite** [lovell/sharp#1904]
I want to resize images to 512x512 if their size is different and scale them only if width or height is not 512x512. Otherwise, just extend width or height with missing pixels.

For example, if the original image size is 512x300 I want just to increase 300 to 512 with transparent colour, the same with height.

If both height and width are not 512 I want to resize with keeping aspect ration to 512.

The idea is to have an output image 512x512 without scaling it if width or height is already 512.

I have tried to do it with something like this:

```
.resize(size, size, {
    fit: sharp.fit.contain,
    background: { r: 0, g: 0, b: 0, alpha: 0 },
    withoutEnlargement: false
})
```

But it scales the image content height

**Comment by lovell** [comment]
Hi, the code provided here appears to do what you're asking for, so I've probably misunderstood the question.

Here's a complete code sample that implements your "if the original image size is 512x300 I want just to increase 300 to 512 with transparent colour" requirement:

```javascript
sharp({
  create: {
    width: 512,
    height: 300,
    channels: 4,
    background: "red"
  }
})
  .resize(512, 512, {
    fit: sharp.fit.contain,
    background: { r: 0, g: 0, b: 0, alpha: 0 }
  })
  .toFile("out.png");
```
which produces a 512x512 image:

![out](https://user-images.githubusercontent.com/210965/66317513-8ebd5780-e911-11e9-878c-fb2992af8bc4.png)

Are you able to provide a complete worked example(s) to help me understand better?

**Comment by Dwite** [comment]
@lovell sorry, my bad. When I was checking the output, I checked it with the wrong image. You are right, the initial solutions work as intended, sorry for bothering.
