### ISSUE TITLE
Add support for frame delay information when loading GIF animations

### ISSUE THREAD

**Issue by rustyconover** [lovell/sharp#1905]
What are you trying to achieve?

I'd like to know the frame delay associated with each frame of a GIF animation.  Currently sharp can load the GIF animation as an image with a number of pages, but there is no information about the delay that should be taken before displaying each frame.

Have you searched for similar feature requests?

Yes.

What would you expect the API to look like?

An additional array of delay information in the response from .metadata().

What alternatives have you considered?

Loading the image using ImageMagick (but I don't want to do this).

**Comment by lovell** [comment]
libvips exposes this as an array of integers in the `delay` property so I agree that adding a property of the same name to the object returned by `metadata()` makes sense.

The `delay` property is also available for animated WebP images.

We should also consider exposing the `gif-loop` property at the same time, which represents the number of times to loop the animation.

Happy to accept a PR if you're able.

**Comment by lovell** [comment]
This is dependent on https://github.com/libvips/libvips/pull/1366 and therefore libvips v8.9.0.

**Comment by lovell** [comment]
v0.24.0 is now available with these fields exposed.

https://sharp.pixelplumbing.com/api-input#metadata
