### ISSUE TITLE
Links in README redirect to non-HTTPS page

### ISSUE THREAD

**Issue by vpzomtrrfrt** [lovell/sharp#1912]
Several links in the README (e.g. https://sharp.pixelplumbing.com/page/changelog) seem to be redirecting to an insecure HTTP URL, even though the server supports TLS.

**Comment by lovell** [comment]
Thanks for reporting this, I'm sure it was working back in January (see commit 8e70579). It looks like readthedocs added a new option relating to the use of HTTPS that hadn't been selected by default.

I've just ticked the "use HTTPS" box and now see:

```sh
$ curl -Is https://sharp.pixelplumbing.com/page/changelog | grep location
location: https://sharp.pixelplumbing.com/en/stable/changelog
```
