### ISSUE TITLE
Error: vips__file_open_write: unable to open file for writing , unix error: No such file or directory

### ISSUE THREAD

**Issue by rinkal-gohel** [lovell/sharp#1914]
here i am trying to get metadata and generate diffrent size of images but giving me error like this.
it will be really great if someone could give solution.

Error: vips__file_open_write: unable to open file for writing
unix error: No such file or directory

const imageToProcess = sharp(image);
await imageToProcess.metadata().then(async (metadata) => {
    const fileRect = {
        height: metadata.height,
        width: metadata.width,
    };
    if (metadata.orientation && metadata.orientation >= 4) {
        // Swap hieght and width for calculation
        fileRect.height = metadata.width;
        fileRect.width = metadata.height;
    }
    const rect = this.getRect(fileRect, thumb);
    const newImage = await imageToProcess.rotate().jpeg().resize(rect.width, rect.height);
    newImage.
        toFile(_thumb.thumbPath, (err) => {
            if (!err) {
                // do something
            } else {
                console.log(err);
            }
        });
}, (error) => {
    console.log(error);
});

**Comment by Fdebijl** [comment]
Sharp doesn't create a directory if it doesn't exist, so if `_tumb.thumbPath` points to a non-existing directory libvips will throw an error. You should check if the directory exists using `fs` and create the directory if it doesn't exist yet.

Alternatively you could use a package like [mkdirp](https://www.npmjs.com/package/mkdirp) to create the directory for you, if you're so inclined.

**Comment by rinkal-gohel** [comment]
Thank you @Fdebijl. it was helpfull to me, Actually directory was already created but i had a problem with path.

**Comment by yArfaj** [comment]
await sharp(req.file.path).toFile(<imgPath>);

await fs.unlink(req.file.path);          // i just added this line then it works
