### ISSUE TITLE
Svg files lacking a width and height throw errors

### ISSUE THREAD

**Issue by justinmchase** [lovell/sharp#1915]
I have a svg file which is fairly weird, it doesn't have a `width` or `height` anywhere in the file and uses a `<style>` + `@media` selectors to select a `<use>` element to make visible dynamically based on the screen size.

What appears to be happening is that sharp is interpreting this file as a 0x0 image and then fails lower down as a result.

Unfortunately for me this isn't my image, its coming from a 3rd party. I have a work around (try/catch and then render a blank image of the right dimensions 😬 ) but what I'd really love is for sharp to render the image successfully, as is. I think that it should have the ability to interpret the the width and height of the image based on the desired resize dimensions. If not I would be happy to pass to sharp any additional parameters it may need to successfully render the image.

## What is the output of running `npx envinfo --binaries --languages --system --utilities`?
```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 255.21 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.12.0 - ~/.nvm/versions/node/v11.12.0/bin/node
    npm: 6.11.2 - ~/.nvm/versions/node/v11.12.0/bin/npm
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.21.0 - /usr/bin/git
    Clang: 1100.0.33.8 - /usr/bin/clang
    Subversion: 1.10.4 - /usr/bin/svn
  Languages:
    Bash: 3.2.57 - /bin/bash
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.1.23 - /usr/bin/php
    Python: 2.7.15 - /usr/local/bin/python
    Python3: 3.7.0 - /usr/local/bin/python3
    Ruby: 2.3.7 - /usr/bin/ruby
    Rust: 1.18.3 - /Users/justin/.cargo/bin/rustup
```

## What are the steps to reproduce?
Using the attached svg file, simply try to resize it or do any other operation with it:
```
> sharp(fs.readFileSync('original.svg')).resize(100, 100).toBuffer().catch(console.error)
CSS parsing error
CSS parsing error
CSS parsing error
CSS parsing error
CSS parsing error
Promise { <pending> }
CSS parsing error
CSS parsing error
> CSS parsing error

(sharp:90891): GLib-GObject-WARNING **: 15:40:55.924: value "0" of type 'gint' is invalid or out of range for property 'width' of type 'gint'

(sharp:90891): GLib-GObject-WARNING **: 15:40:55.924: value "0" of type 'gint' is invalid or out of range for property 'height' of type 'gint'

(sharp:90891): GLib-GObject-WARNING **: 15:40:55.927: value "0" of type 'gint' is invalid or out of range for property 'width' of type 'gint'

(sharp:90891): GLib-GObject-WARNING **: 15:40:55.927: value "0" of type 'gint' is invalid or out of range for property 'height' of type 'gint'
[Error: svgload_buffer: SVG rendering failed
vips2png: unable to write to buffer
]
```

## What is the expected behaviour?
I expect it to render the svg at the provided size.

## Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?
Yes. 1-liner for nodejs console:
```
sharp(fs.readFileSync('original.svg')).resize(100, 100).toBuffer()
```

## Are you able to provide a sample image that helps explain the problem?
Yes: [original.svg.gz](https://github.com/lovell/sharp/files/3719546/original.svg.gz)

**Comment by lovell** [comment]
Hi, this is a limitation of the current librsvg API. The same problem can be seen using its `rsvg-convert` command line tool, even when providing dimensions:

```sh
$ rsvg-convert --version
rsvg-convert version 2.46.0
$ rsvg-convert original.svg -o out.png
CSS parsing error
CSS parsing error
CSS parsing error
CSS parsing error
CSS parsing error
CSS parsing error
CSS parsing error
CSS parsing error
The SVG original.svg has no dimensions
$ rsvg-convert original.svg -o out.png -w 100 -h 100
CSS parsing error
CSS parsing error
CSS parsing error
CSS parsing error
CSS parsing error
CSS parsing error
CSS parsing error
CSS parsing error
The SVG original.svg has no dimensions
```

A new `rsvg_handle_render_document` function has just been added to the librsvg API via https://gitlab.gnome.org/GNOME/librsvg/merge_requests/237 but this has not yet been released. Using it should solve this kind of problem, but will require a change to libvips first.
