### ISSUE TITLE
Tile overlap regression in v0.23

### ISSUE THREAD

**Issue by rustyguts** [lovell/sharp#1918]
I think I've found a regression with the `overlap` attribute in `tile()`.

Steps to reproduce

- yarn add sharp@0.23.1 or 0.23.0
- run script with an image

```json
width: 256,
height: 256,
```

- yarn add sharp@0.22.1
- run script with an image

```json
width: 257,
height: 257,
```

Script to reproduce

```js
(async () => {
  const sharp = require('sharp');
  const fs = require('fs-extra');

  const testImageName = 'test.jpg';

  fs.emptyDirSync(`${testImageName}_files`);
  fs.removeSync(`${testImageName}_files`);
  fs.removeSync(`${testImageName}.dzi`);

  await sharp(fs.readFileSync(testImageName))
    .tile({ size: 256, overlap: 1 })
    .toFile(`${testImageName}.dz`);

  const { width, height } = await sharp(
    `${testImageName}_files/13/0_0.jpeg`,
  ).metadata();

  console.log(`tile is ${width}x${height}`);
})();
```

**Comment by lovell** [comment]
Thanks for reporting this, I can reproduce it too.

It looks like there's a typo at the following line:

https://github.com/lovell/sharp/blob/ba46ad1fd9f9bea37fdc2146989e17ea55074ac1/lib/output.js#L577

...which should be `options.overlap`.

Happy to accept a PR if you're able, even better if it adds your sample code as a new unit test to help prevent future regression.

**Comment by rustyguts** [comment]
I'll make a PR and add some more unit tests, thanks!

**Comment by lovell** [comment]
v0.23.3 now available, thank you for fixing this.

**Comment by rustyguts** [comment]
Thanks for maintaining! 👍
