### ISSUE TITLE
Pixel Density or dpi

### ISSUE THREAD

**Issue by andrevenancio** [lovell/sharp#1920]
Hi, I'm using sharp as a npm dependency to save some images that are being draw using a canvas (2d)

I have a target resolution and density to match a printer setting, and I've worked out how much bigger in 72dpi do I need to have my canvas in order to get this done. But instead of saving the image at 72dpi can't I just "squash" into my final target width and height and dpi?

Example
target: 1054x744@300 dpi

My math to define the size of the canvas is : 
```
const width = 1054 * 300 / 72; // 4392px
const height = 744 * 300 / 72; // 3100px
```

So now I have an image saved as 4392x3100@72 dpi.
Is there a way of now squashing the image into my final target image and dpi?

Am I missing something?
Thanks

**Comment by annaelizabeth2019** [comment]
Having same issue! I need 72 DPI images, not sure if sharp can accommodate it?

**Comment by lovell** [comment]
Hi both, it depends on the output format being targetted.

TIFF is pretty much the only bitmap format that cares about pixel density, thanks mainly to its use in the print industry, hence the [tiff](https://sharp.pixelplumbing.com/en/stable/api-output/#tiff) operation exposing `xres` and `yres`.

JPEG doesn't deal with density, but some metadata added to JPEG can include values that might be interpreted as such - please see #967 for a related future possible enhancement.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further help is required.

**Comment by Umar0052** [comment]
await sharp(originalImagePath)
      .resize(622, 622)
      .withMetadata({ density: 72 })
      .toFile(resizedImagePath, { quality: 80 }, (err, info) => {
        if (err) {
          console.error('Error in toFile operation:', err);
        } else {
          console.log('File info:', info);
        }
      });
      
      
      this work for me
