### ISSUE TITLE
Combine rotate and resize operation results unexpected image resolution.

### ISSUE THREAD

**Issue by jasli2** [lovell/sharp#1922]
Image resolution is not correct after rotate and resize. 

For example, the original image resolution is 3000(w) x 2000(h).
what I am going to do is resize the image to 750(w) x 500(h) then rotate image by 90 degree. So the image resolution should be 500(w) x 750(h). Code is:

```
image.resize({ height: 500 }).rotate(90).then(...);
```

However, the resolution of image results at 333(w) x 500(h).
Seems like the rotate operation is done before resize no matter the operation order is.

I have confirmed if I separate this two operation into two script to process, I will got the correct image resolution.   So I believe a bug is in there.

**Comment by lovell** [comment]
Hello, you may be interested in the discussion at #241 about improvements to operation ordering in the API.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further help is required.
