### ISSUE TITLE
ELIFECYCLE errno 1 sharp@0.21.3 install

### ISSUE THREAD

**Issue by EricaLynnFL** [lovell/sharp#1925]
**I'm getting an ELIFECYCLE error when using npm install:** _(pastebin below incase this formatting doesn't work)_
`1055 verbose stack Error: sharp@0.21.3 install: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)\'
1055 verbose stack Exit status 1
1055 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
1055 verbose stack     at EventEmitter.emit (events.js:210:5)
1055 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
1055 verbose stack     at ChildProcess.emit (events.js:210:5)
1055 verbose stack     at maybeClose (internal/child_process.js:1021:16)
1055 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
1056 verbose pkgid sharp@0.21.3
1057 verbose cwd /Users/ericalynn/WebstormProjects/professor-hemlock
1058 verbose Darwin 19.0.0
1059 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--verbose" "sharp"
1060 verbose node v12.11.0
1061 verbose npm  v6.11.3
1062 error code ELIFECYCLE
1063 error errno 1
1064 error sharp@0.21.3 install: '(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)'
1064 error Exit status 1
1065 error Failed at the sharp@0.21.3 install script.
1065 error This is probably not a problem with npm. There is likely additional logging output above.
1066 verbose exit [ 1, true ]`

**Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/en/stable/install/)?** _Yes_

**Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime?** _Yes_

**If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?** _Yes_

**What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?**
_Pastebin:_ [https://pastebin.com/cu10yLUD](https://pastebin.com/cu10yLUD)

**What is the output of running `npx envinfo --binaries --languages --system --utilities`?**
  System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 173.29 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.11.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.23.0 - /usr/local/bin/git
    Clang: 1100.0.33.8 - /usr/bin/clang
    Subversion: 1.10.4 - /usr/bin/svn
  Languages:
    Bash: 3.2.57 - /bin/bash
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.3.8 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.7.3 - /usr/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby

Thanks!!
Erica

**Comment by EricaLynnFL** [comment]
I changed the version number in package.json to 23.1 and the installation seemed to work properly.

**Comment by lovell** [comment]
Hi, support for Node.js v12 was added in v0.22.1.

https://sharp.pixelplumbing.com/en/stable/changelog/#v0221-25th-april-2019
