### ISSUE TITLE
metadata get stuck

### ISSUE THREAD

**Issue by sm2017** [lovell/sharp#1929]
What is the output of running `npx envinfo --binaries --languages --system --utilities`?
```
  System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
    CPU: (4) x64 Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
    Memory: 2.71 GB / 7.64 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.9.0 - /usr/bin/npm
  Utilities:
    CMake: 2.8.12.2 - /usr/bin/cmake
    Make: 3.82 - /usr/bin/make
    GCC: 4.8.5 - /usr/bin/gcc
    Git: 1.8.3.1 - /usr/bin/git
    Clang: 3.4.2 - /usr/bin/clang
    Mercurial: 2.6.2 - /usr/bin/hg
  Languages:
    Bash: 4.2.46 - /usr/bin/bash
    Perl: 5.16.3 - /usr/bin/perl
    Python: 2.7.5 - /usr/bin/python

```
What are the steps to reproduce?

```js
const image = sharp();
inputJpgStream.pipe(image)


const imageMetadata = await image.metadata();
```

What is the expected behaviour?

It must calculate metadata , I am using shap to calculate metadata of files that uploaded from end users , My image file is stream and I pipe it to sharp , In some cases (Not always) , `metadata` never resolved or rejected , I test with try/catch/finally and see that metadata get stuck

Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?
May be later, it's a little hard to reproduce

Are you able to provide a sample image that helps explain the problem?
May be later, it's a little hard to reproduce

**Comment by lovell** [comment]
Hi, is there any error handling on the input Stream? Try adding something like:
```javascript
image.on("error", console.log);
```

**Comment by sm2017** [comment]
@lovell , I understand that it's not related to sharp it self

**Comment by septagram** [comment]
Appears to still be a thing, and also very hard to reproduce. In my case it manages to hang the entire Node process, even all the unrelated `setInterval` callbacks don't get called anymore, just dead silence.
