### ISSUE TITLE
dark reds in greyscale

### ISSUE THREAD

**Issue by bkw** [lovell/sharp#193]
I noticed that greyscaling with sharp gives quite different results than graphicsmagick or imagemagick, even with gamma correction applied. Without much experimentation it appears to me that the reds end up pretty dark in the greyscale result, as seen in this example: http://imgur.com/a/y7wNc

Is this a known thing or deliberate?

Code used:
```javascript
var sharp = require('sharp'),
    gm = require('gm');

sharp(process.argv[2])
  .gamma()
  .greyscale()
  .toFile('sharp.png');

gm(process.argv[2])
  .gamma(1/2.2)
  .colorspace('GRAY')
  .type('grayscale')
  .gamma(2.2)
  .write('gm.png', console.log);
```

Input file was http://i.imgur.com/dLKxTCk.jpg

**Comment by lovell** [comment]
Specifying `greyscale` delegates to [vips_colourspace](https://github.com/lovell/sharp/blob/master/src/resize.cc#L410) with `VIPS_INTERPRETATION_B_W`.

It's very likely this is not the best way of doing it. Perhaps using `vips_icc_transform` with an ICC greyscale profile will produce better results.

I'm going to have to call on someone with more grey matter on the subject here, namely @jcupitt.

**Comment by bkw** [comment]
I*m pretty sure this is the way to go. Some eons ago I did a couple of tests on this subsject (grayscaling customer images for print). I remember that we ended up using a profile extracted from OSX, since it gave best results for the midtones. Since we probably cannot redistribute that, I hope we find a good alternative.

**Comment by lovell** [comment]
Extracting the L component of LAB should provide good results too, and may be simpler/faster.

**Comment by bkw** [comment]
I tried that, but it's pretty dark: http://imgur.com/a/CL05R
But using a profile from ghostscript with sharp did quite well: http://imgur.com/a/IkuHp
I have no idea wether we'd be allowed to distribute the profile with sharp, though.
I tried some public-domain profiles, but they gave terrible results.

**Comment by bkw** [comment]
This looks interesting: http://ninedegreesbelow.com/photography/lcms-make-icc-profiles.html
I'll give this a go tomorrow.

**Comment by jcupitt** [comment]
Browsers display no-profile greyscale images by just copying the pixels to make an RGB, then displaying that RGB as sRGB. So the correct way to make a greyscale from an RGB jpg is to transform to sRGB, take G = 0.2 * R + 0.7 * G + 0.1 * B (everyone uses this mix) and save that without a profile.

At the command-line, you'd use:

```bash
john@katamata ~/pics $ vips icc_import mountain.jpg x.v --embedded
john@katamata ~/pics $ vips colourspace x.v x.png[profile=none] b-w
```

Which I think is what sharp is doing. I get this:

http://www.rollthepotato.net/~john/x.png

Though I can see that in this case, with so much in the red, the result is a bit unsatisfactory. 

If you want to match gm, we'd need to dig into their code and see what they are doing.

**Comment by jcupitt** [comment]
... although now I think about it, that RGB -> grey conversion should be in linear space. And looking at colourspace.c, it's not actually doing that, it's just taking the green channel. I'll fix it.

**Comment by lovell** [comment]
Thanks John, your command line example is equivalent to sharp's current behaviour.

**Comment by jcupitt** [comment]
With this change:

https://github.com/jcupitt/libvips/commit/a0aacad8711b0958535a1ed594824028bb59af9e

And the commands as before:

```bash
john@katamata ~/pics $ vips icc_import mountain.jpg x.v --embedded
john@katamata ~/pics $ vips colourspace x.v x2.png[profile=none] b-w
```

I now see this result:

http://www.rollthepotato.net/~john/x2.png

I think that's actually quite a bit better than the GM version, which I think looks too contrast-y compared to the original.

**Comment by jcupitt** [comment]
... and thanks @bkw for pointing this dumbness out, I credited you in the vips changelog. This is a nice improvement.

**Comment by bkw** [comment]
Wow! Quite a bit better indeed! Thanks for the lightning fast reaction!

**Comment by bkw** [comment]
Closing this, since this will become a non-issue with the release of libvips 8

**Comment by lovell** [comment]
Thank you @jcupitt!
