### ISSUE TITLE
Build against a more recent ilmbase?

### ISSUE THREAD

**Issue by ethernomad** [lovell/sharp#1930]
Upon updating Arch Linux, Sharp has missing libraries:

```
ldd node_modules/sharp/build/Release/sharp.node
libIlmImf-2_3.so.24 => not found
libImath-2_3.so.24 => not found
libHalf.so.24 => not found
libIex-2_3.so.24 => not found
libIexMath-2_3.so.24 => not found
libIlmThread-2_3.so.24 => not found
```

Files like the following are now present:
/usr/lib/libIlmImf-2_4.so.24

**Comment by ethernomad** [comment]
I was able to fix this locally by creating symlinks in my /usr/lib dir.

**Comment by lovell** [comment]
Hi, sharp does not provide prebuilt binaries that include ilmbase so I suspect you're using a global libvips compiled with OpenEXR support. You'll need to either run `ldconfig` or recompile sharp if there are minor/major version increments to globally-installed shared libraries upon which libvips depends.

**Comment by ethernomad** [comment]
Okay thanks!
