### ISSUE TITLE
 Fatal error C1083: Cannot open include file: 'vips/intl.h'

### ISSUE THREAD

**Issue by MFukazawa** [lovell/sharp#1931]
I'm running `gridsome create my-gridsome-site` to install the default Gridsome starter.  Any help is appreciated.  Sorry the pasted terminal output looks so horrible. 

>gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',                                                                                                      gyp info spawn args   '/nologo',                                                                                                                gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]                                                                                 

>Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 10/23/2019 4:18:56 PM.
Project "C:\Users\Micah\Desktop\my-gridsome-site\node_modules\sharp\build\binding.sln" on node 1 (default targ
ets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".                                                                                                Project "C:\Users\Micah\Desktop\my-gridsome-site\node_modules\sharp\build\binding.sln" (1) is building "C:\Use
rs\Micah\Desktop\my-gridsome-site\node_modules\sharp\build\libvips-cpp.vcxproj" (2) on node 1 (default targets
).
PrepareForBuild:
  Creating directory "Release\obj\libvips-cpp\".                                                                                                Creating directory "Release\obj\libvips-cpp\libvips-cpp.tlog\".
InitializeBuildStatus:
  Creating "Release\obj\libvips-cpp\libvips-cpp.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.                                   ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\CL.
  exe /c /I"C:\Users\Micah\.node-gyp\10.16.3\include\node" /I"C:\Users\Micah\.node-gyp\10.16.3\src" /I"C:\User                                  s\Micah\.node-gyp\10.16.3\deps\openssl\config" /I"C:\Users\Micah\.node-gyp\10.16.3\deps\openssl\openssl\incl                                  ude" /I"C:\Users\Micah\.node-gyp\10.16.3\deps\uv\include" /I"C:\Users\Micah\.node-gyp\10.16.3\deps\zlib" /I"                                  C:\Users\Micah\.node-gyp\10.16.3\deps\v8\include" /I..\vendor\include /I"..\vendor\include\glib-2.0" /I"..\v                                  endor\lib\glib-2.0\include" /Z7 /nologo /W3 /WX- /diagnostics:classic /MP /Ox /Ob2 /Oi /Ot /Oy /GL /D "NODE_                                  GYP_MODULE_NAME=libvips-cpp" /D USING_UV_SHARED=1 /D USING_V8_SHARED=1 /D V8_DEPRECATION_WARNINGS=1 /D WIN32                                  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _HAS_EXCEPTIONS=0 /D VIPS_CPLUSPLUS_EXPORTS /D                                     _ALLOW_KEYWORD_MACROS /D _WINDLL /GF /Gm- /EHsc /MT /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline                                  /GR- /Fo"Release\obj\libvips-cpp\\" /Fd"Release\obj\libvips-cpp\vc141.pdb" /Gd /TP /wd4351 /wd4355 /wd4800 /                                  wd4251 /wd4275 /wd4244 /wd4267 /FC /errorReport:queue ..\src\libvips\cplusplus\VError.cpp ..\src\libvips\cpl                                  usplus\VInterpolate.cpp ..\src\libvips\cplusplus\VImage.cpp "C:\Program Files\nodejs\node_modules\npm\node_m                                  odules\node-gyp\src\win_delay_load_hook.cc"
  VError.cpp
  VInterpolate.cpp
  VImage.cpp
  win_delay_load_hook.cc
c:\users\micah\desktop\my-gridsome-site\node_modules\sharp\src\libvips\cplusplus\verror.cpp(33): fatal error C
1083: Cannot open include file: 'vips/intl.h': No such file or directory [C:\Users\Micah\Desktop\my-gridsome-s
ite\node_modules\sharp\build\libvips-cpp.vcxproj]
c:\users\micah\desktop\my-gridsome-site\node_modules\sharp\src\libvips\cplusplus\vimage.cpp(41): fatal error C                                  1083: Cannot open include file: 'vips/intl.h': No such file or directory [C:\Users\Micah\Desktop\my-gridsome-s                                  ite\node_modules\sharp\build\libvips-cpp.vcxproj]
c:\users\micah\desktop\my-gridsome-site\node_modules\sharp\src\libvips\cplusplus\vinterpolate.cpp(34): fatal e                                  rror C1083: Cannot open include file: 'vips/intl.h': No such file or directory [C:\Users\Micah\Desktop\my-grid                                  some-site\node_modules\sharp\build\libvips-cpp.vcxproj]
Done Building Project "C:\Users\Micah\Desktop\my-gridsome-site\node_modules\sharp\build\libvips-cpp.vcxproj" (
default targets) -- FAILED.

>Done Building Project "C:\Users\Micah\Desktop\my-gridsome-site\node_modules\sharp\build\binding.sln" (default
targets) -- FAILED.

>Build FAILED.

>"C:\Users\Micah\Desktop\my-gridsome-site\node_modules\sharp\build\binding.sln" (default target) (1) ->
"C:\Users\Micah\Desktop\my-gridsome-site\node_modules\sharp\build\libvips-cpp.vcxproj" (default target) (2) ->                                  (ClCompile target) ->
  c:\users\micah\desktop\my-gridsome-site\node_modules\sharp\src\libvips\cplusplus\verror.cpp(33): fatal error                                  C1083: Cannot open include file: 'vips/intl.h': No such file or directory [C:\Users\Micah\Desktop\my-gridsome                                 -site\node_modules\sharp\build\libvips-cpp.vcxproj]
  c:\users\micah\desktop\my-gridsome-site\node_modules\sharp\src\libvips\cplusplus\vimage.cpp(41): fatal error                                  C1083: Cannot open include file: 'vips/intl.h': No such file or directory [C:\Users\Micah\Desktop\my-gridsome                                 -site\node_modules\sharp\build\libvips-cpp.vcxproj]
  c:\users\micah\desktop\my-gridsome-site\node_modules\sharp\src\libvips\cplusplus\vinterpolate.cpp(34): fatal                                  error C1083: Cannot open include file: 'vips/intl.h': No such file or directory [C:\Users\Micah\Desktop\my-gr                                  idsome-site\node_modules\sharp\build\libvips-cpp.vcxproj]

>0 Warning(s)  3 Error(s)                                                                                                                                                                                   
>Time Elapsed 00:00:02.96
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.                                 exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\b                                 uild.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)                                                                                      gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)                                                    gyp ERR! System Windows_NT 10.0.18362                                                                                                           gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu                                 les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Micah\Desktop\my-gridsome-site\node_modules\sharp                                                                         gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0                                                                                                                     gyp ERR! not ok                                                                                                                                 npm verb lifecycle sharp@0.23.1~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.23.1~install: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecy                                 cle\node-gyp-bin;C:\Users\Micah\Desktop\my-gridsome-site\node_modules\sharp\node_modules\.bin;C:\Users\Micah\De                                 sktop\my-gridsome-site\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS                                  Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\s                                 ystem32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\                                 Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\P                                 rogram Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Manage                                 ment Engine Components\IPT;C:\Program Files\Acer\Remote Files\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System                                 32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Pr                                 ogram Files\PostgreSQL\11\bin;C:\Program Files\nodejs\;C:\Users\Micah\AppData\Local\Microsoft\WindowsApps;C:\Us                                 ers\Micah\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Micah\AppData\Roaming\npm;C:\Program Files\hero                                 ku\bin
npm verb lifecycle sharp@0.23.1~install: CWD: C:\Users\Micah\Desktop\my-gridsome-site\node_modules\sharp                                        npm info lifecycle sharp@0.23.1~install: Failed to exec install script                                                                          npm timing action:install Completed in 8954ms
npm verb unlock done using C:\Users\Micah\AppData\Roaming\npm-cache\_locks\staging-ff34f6acc3a3afbc.lock for C:                                 \Users\Micah\Desktop\my-gridsome-site\node_modules\.staging
npm timing stage:rollbackFailedOptional Completed in 328ms                                                                                      npm timing stage:runTopLevelLifecycles Completed in 48472ms
npm verb stack Error: sharp@0.23.1 install: `(node install/libvips && node install/dll-copy && prebuild-install                                 ) || (node-gyp rebuild && node install/dll-copy)`
npm verb stack Exit status 1                                                                                                                    npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifec                                 ycle\index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:198:13)                                                                                      npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)         npm verb stack     at ChildProcess.emit (events.js:198:13) 
npm ERR!     C:\Users\Micah\AppData\Roaming\npm-cache\_logs\2019-10-23T07_19_00_524Z-debug.log                 

System specs:
                                                                                                                                                                                                   System:                                                                                                                                                                                            OS: Windows 10                                                                                                                                                                                   CPU: (4) x64 Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz                                                                                                                                            Memory: 2.79 GB / 7.89 GB        
                                                                                                                                                              Binaries:                                                                                                                                                                                          Node: 10.16.3 - C:\Program Files\nodejs\node.EXE                                                                                                                                                 npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

**Comment by mandaputtra** [comment]
Hi, could you run, `npm install sharp` ? and see if the errors occur because of sharp? If your installation is good then it is not because sharp. I can confirm that Gridsome had some issues in windows machine due to is build system/dev [system](https://github.com/gridsome/gridsome-starter-blog/issues/15) I run to similar issues back in the day.

Gridsome uses sharp to optimizing the image, in `<g-image />` I'm sure it's their build system on windows failed.

**Comment by lovell** [comment]
If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

(These questions were in the issue template.)

**Comment by MFukazawa** [comment]
> Hi, could you run, `npm install sharp` ? and see if the errors occur because of sharp? If your installation is good then it is not because sharp. I can confirm that Gridsome had some issues in windows machine due to is build system/dev [system](https://github.com/gridsome/gridsome-starter-blog/issues/15) I run to similar issues back in the day.
> 
> Gridsome uses sharp to optimizing the image, in `<g-image />` I'm sure it's their build system on windows failed.

npm install sharp succeeded, so it looks like sharp is not the problem. Thank you! 

lovell, sorry for taking your time.
