### ISSUE TITLE
can GIF Output support be added?

### ISSUE THREAD

**Issue by elndro85** [lovell/sharp#1934]
I was trying to use "gif" as a parameter for the .toFormat() but was unable to do it

`transform.toFormat(config.format, {
       quality: config.quality
});`

In [this issue](https://github.com/lovell/sharp/issues/1071#issuecomment-352740753) I saw that this is because libvps doesn't support gif output.

I was searching on libvips checking if I could compile my own version, and according to this https://github.com/libvips/libvips/issues/1167, it seems like it is supported since libvips version 8.7 via XXXX.

According to the [changelog ](https://sharp.pixelplumbing.com/en/stable/changelog/) the latest version is using libvips v8.8.1.

can gif output support be added? I tried doing so in the following commit on a fork I made

https://github.com/elndro85/sharp/commit/3a226018de6cadb524e5b447eb3f717e5f1204a3

As a mainly frontend developer c++ is not my strongest skill and I'm not sure on how to finish, can you help me out with this, or point me in the right direction to be able to get this to work.

**Comment by lovell** [comment]
Please see #1372
