### ISSUE TITLE
Module did not self-register on node 12.13.0/ubuntu

### ISSUE THREAD

**Issue by peteboere** [lovell/sharp#1936]
This is similar to other issues people are having but it points to an issue installing sharp on node 12.13.0 on ubuntu (linux/amd64)

Using the following Dockerfile, changing `NODE_VER` to 12.13.0 causes runtime to fail with the 'Module did not self-register'.  With `NODE_VER` set to 10.17.0 there are no problems.

Using latest sharp release: 0.23.1

```
FROM selenium/node-chrome:3.141.59-xenon

ENV PROTRACTOR_VER="^5.0.0"
ENV NODE_VER=10.17.0
ENV NODE_BIN=/usr/local/n/versions/node/$NODE_VER/bin
ENV NODE_LIB=/usr/local/n/versions/node/$NODE_VER/lib/node_modules
ENV BIN=/usr/local/bin

RUN sudo apt-get update
RUN sudo apt-get -y install git-all nodejs npm
RUN nodejs -v
RUN npm -v
RUN sudo npm cache clean -f
RUN sudo npm install -g n
RUN sudo n $NODE_VER
RUN sudo ln -sf $NODE_BIN/node $BIN/node
RUN sudo npm install -g protractor@$PROTRACTOR_VER
RUN sudo ln -sf $NODE_BIN/protractor $BIN/protractor
RUN sudo ln -sf $NODE_BIN/webdriver-manager $BIN/webdriver-manager
RUN sudo $BIN/webdriver-manager update
RUN node -v
RUN npm -v
```

This image is pulled via a bitbucket pipeline then the following steps reproduce the issue:

```
> npm install

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
added 17 packages from 4 contributors, removed 18 packages, updated 33 packages and audited 3503 packages in 3.906s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```

```
> node server.js

[system] ⚡ 85 startup: {env: ci, CPUs: 8}
[db] Connected
Something went wrong installing the "sharp" module
Module did not self-register.
- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues
```

**Comment by lovell** [comment]
Hi, it looks like there are two different `node` binaries inside this image, one installed by the `apt-get` package manager at the path `/usr/bin/node` and the other installed by `n` at the path `/usr/local/bin/node`. It's likely one is used at `npm install` time and another at runtime.

(This is why the installation issue template asks "Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime?")

If you intend to provide only one version of Node.js inside containers spawned from this image, then perhaps consider using the instructions at https://github.com/nodesource/distributions/blob/master/README.md#debian-and-ubuntu-based-distributions

**Comment by peteboere** [comment]
The package installed by apt-get is installed to `nodejs` on ubuntu, and the docker image build log confirms that the right node binary is on path:

```
Step 9/20 : RUN nodejs -v
v8.10.0
Step 10/20 : RUN npm -v
3.5.2
... after node update and link ...
Step 19/20 : RUN node -v
v12.13.0
Step 20/20 : RUN npm -v
6.12.0
```

 Just to double check I added a step before `npm install` to confirm that the test runner is  definitely using the same binary at install as it is at runtime. 

My reason for filing this as an issue is that this exact setup has been working for several years with no problem and has only broken with moving the image to node 12.x

**Comment by peteboere** [comment]
Ok, turns out it's an issue with bitbucket pipelines caching node modules.
Sorry for the interruption.
