### ISSUE TITLE
Reporting bug from installation

### ISSUE THREAD

**Issue by steowens** [lovell/sharp#1937]
Install failed on npm version 3.5.2 on Ubuntu 18.04.

No debug log was created.
Failure occurred when attempting to install Framework7.

npm ERR! Linux 5.0.0-31-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "framework7-cli" "cordova" "-g"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.23.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.23.1 install script '(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/steve/npm-debug.log

**Comment by scredii** [comment]
same for me

**Comment by lovell** [comment]
If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

(The above question is from the installation issue template - did you see this?)

**Comment by m00k** [comment]
same here, also on Ubuntu (18.10)
tried with `--unsafe-perm` - didn't help

**Comment by m00k** [comment]
works with node 12, fails with node 13

**Comment by lovell** [comment]
@m00k For Node.js 13, please see #1909

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further help is required.
