### ISSUE TITLE
is it possible to use a global installation of libvips (with imagemagicks) in windows?

### ISSUE THREAD

**Issue by elndro85** [lovell/sharp#1938]
Hi, I need to handle input and output of BMP files and after checking this issue https://github.com/lovell/sharp/issues/543 I found out that I need to globally install a version of libvips with support for *magick.

I was able to do this by downloading the windows binaries from https://github.com/libvips/libvips/releases and adding the bin folder to my PATH environment variable.

After doing this I was able to use libvips with BMP images manually from the cmd.

When trying to use it with sharp, I noticed that every time that I tried to install Sharp, it would always use the either download the precompiled binaries, or use the ones already in npm cache.

after searching in the code for a hint, I found that Sharp checks if libvips is installed by spawning some child processes, but only when  process.platform is different than win32 ([here](https://github.com/lovell/sharp/blob/master/lib/libvips.js#L40)), this means that even if libvips is installed globally in windows, it will always ignore it.

Is it possible to add support for globally installed versions of libvips in windows?

**Comment by lovell** [comment]
Use of a custom libvips isn't supported on Windows but you might be to get it to work by copying all the DLLs from the libvips Windows release tarball into the `node_modules/sharp/build/Release` directory after installation.

The script that converts libvips release tarballs into the minimal tarballs for use with sharp on Windows can be seen at https://github.com/lovell/sharp-libvips/blob/master/build/win.sh

**Comment by elndro85** [comment]
Thanks for the reply @lovell, I'll check it out and will report if I was able to make it work. appreciate the help.
