### ISSUE TITLE
Including multiple builds with app

### ISSUE THREAD

**Issue by echo1consulting** [lovell/sharp#1939]
Is there a way to provide all pre built versions as part of my app, and have my app detect which to use?

I would like to provide the app to people who may install my express app on different versions of Linux.

Regards,

**Comment by lovell** [comment]
The tarballs containing prebuilt binaries are at:

* https://github.com/lovell/sharp-libvips/releases for libvips and its dependencies, unpacked to the `vendor` directory
* https://github.com/lovell/sharp/releases for sharp, unpacked to the `build` directory

You'll need to write the logic to detect/install/switch the binaries for different libc implementations yourself - perhaps use https://www.npmjs.com/package/detect-libc for the detection.
