### ISSUE TITLE
Netlify Lambda: Something went wrong installing the "sharp" module  Cannot find module '../build/Release/sharp.node'

### ISSUE THREAD

**Issue by abythachet** [lovell/sharp#1943]
I am Trying to run netlify lambda function it run fine locally (i use a mac), i pushed the code with out the node_modules  and "run npm install"
while install no error
error is when when i call the function

```
12:02:17 PM: 2019-10-31T06:32:17.387Z	d7bd4f80-ba5c-4270-af48-a0e782291cd1	Something went wrong installing the "sharp" moduleCannot find module '../build/Release/sharp.node'- Remove the "node_modules/sharp" directory, run "npm install" and look for errors- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/- Search for this error at https://github.com/lovell/sharp/issues
12:02:18 PM: 2019-10-31T06:32:18.203Z	d7bd4f80-ba5c-4270-af48-a0e782291cd1	Something went wrong installing the "sharp" moduleCannot find module '../build/Release/sharp.node'- Remove the "node_modules/sharp" directory, run "npm install" and look for errors- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/- Search for this error at https://github.com/lovell/sharp/issues
12:02:18 PM: Duration: 312.93 ms	Memory Usage: 48 MB	
12:02:18 PM: RequestId: d7bd4f80-ba5c-4270-af48-a0e782291cd1 Process exited before completing request

```

i try pushing with node_module (i use npm "install --arch=x64 --platform=linux --target=10.15.0 sharp ") still same error (error only when i call the function)

os : Ubuntu Xenial 16.04
node: 10.15.0
sharp: 0.23.2
Thanks

**Comment by lovell** [comment]
https://docs.netlify.com/functions/build-with-javascript/#runtime-settings suggests Netlify uses Node.js 8 by default rather than Node.js 10.

https://github.com/netlify/netlify-lambda#webpack-configuration suggests the `webpack-node-externals` plugin is required when using native modules.

**Comment by abythachet** [comment]
i have given 10.15.0  as environment variable in an it is loading 10.15 (i checked the log)
and also i have configured webpack

**Comment by lovell** [comment]
Does `node_modules/sharp/build/Release/sharp.node` exist in the deployed zip file? Are you able to share your complete build configuration and/or provide any build logs from Netlify? What did Netlify say when you asked them for help?

**Comment by abythachet** [comment]
node_modules/sharp/build/Release/sharp.node file exist,

this is my build log
`9:50:38 AM: Build ready to start
9:50:43 AM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
9:50:43 AM: build-image tag: v3.3.2
9:50:43 AM: buildbot version: a2bab682ae0761baa4d123ebd00c57be933655dc
9:50:43 AM: Fetching cached dependencies
9:50:43 AM: Starting to download cache of 255.0KB
9:50:43 AM: Finished downloading cache in 102.06569ms
9:50:43 AM: Starting to extract cache
9:50:43 AM: Failed to fetch cache, continuing with build
9:50:43 AM: Starting to prepare the repo for build
9:50:44 AM: No cached dependencies found. Cloning fresh repo
9:50:44 AM: git clone git@bitbucket.org:nfnlabsdev/netlify-test-sharp
9:50:51 AM: Preparing Git Reference refs/heads/master
9:50:52 AM: Found netlify.toml. Overriding site configuration
9:50:52 AM: Different build command detected, going to use the one specified in the toml file: 'npm run build:lambda' versus '' in the site
9:50:52 AM: Different functions path detected, going to use the one specified in the toml file: 'lambda' versus 'functions' in the site
9:50:52 AM: Creating functions prep folder
9:50:52 AM: Starting build script
9:50:53 AM: Installing dependencies
9:50:55 AM: Downloading and installing node v10.15.0...
9:50:55 AM: Downloading https://nodejs.org/dist/v10.15.0/node-v10.15.0-linux-x64.tar.xz...
9:50:55 AM: 
#######
9:50:55 AM:                 11.0%
9:50:55 AM: 
#################################################
9:50:55 AM:                  68.8%
9:50:55 AM: 
##########################################
9:50:55 AM: ############################## 100.0%
9:50:56 AM: Computing checksum with sha256sum
9:50:56 AM: Checksums matched!
9:50:59 AM: Now using node v10.15.0 (npm v6.4.1)
9:51:00 AM: Attempting ruby version 2.6.2, read from environment
9:51:02 AM: Using ruby version 2.6.2
9:51:02 AM: Using PHP version 5.6
9:51:02 AM: Started restoring cached node modules
9:51:03 AM: Finished restoring cached node modules
9:51:03 AM: Installing NPM modules using NPM version 6.4.1
9:51:19 AM: > sharp@0.23.2 install /opt/build/repo/node_modules/sharp
9:51:19 AM: > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
9:51:19 AM: info
9:51:19 AM: sharp
9:51:19 AM:  Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linux-x64.tar.gz
9:51:23 AM: npm WARN netlify-test-sharp@1.0.0 No description
9:51:23 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
9:51:23 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
9:51:23 AM: added 621 packages from 453 contributors and audited 9732 packages in 19.068s
9:51:23 AM: found 0 vulnerabilities
9:51:23 AM: NPM modules installed
9:51:24 AM: Started restoring cached go cache
9:51:24 AM: Finished restoring cached go cache
9:51:24 AM: unset GOOS;
9:51:24 AM: unset GOARCH;
9:51:24 AM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
9:51:24 AM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
9:51:24 AM: go version >&2;
9:51:24 AM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
9:51:24 AM: go version go1.12 linux/amd64
9:51:24 AM: Installing missing commands
9:51:24 AM: Verify run directory
9:51:24 AM: Executing user command: npm run build:lambda
9:51:24 AM: > netlify-test-sharp@1.0.0 build:lambda /opt/build/repo
9:51:24 AM: > netlify-lambda build src/lambda --config ./webpack.conf.js
9:51:25 AM: netlify-lambda: Building functions
9:51:37 AM: Hash: 02b05821fff5d7af6e98
9:51:37 AM: Version: webpack 4.41.2
9:51:37 AM: Time: 11573ms
9:51:37 AM: Built at: 11/01/2019 4:21:37 AM
9:51:37 AM:             Asset      Size  Chunks             Chunk Names
9:51:37 AM: getimagefroms3.js  3.85 MiB       0  [emitted]  getimagefroms3
9:51:37 AM:          hello.js  1.03 KiB       1  [emitted]  hello
9:51:37 AM: Entrypoint getimagefroms3 = getimagefroms3.js
9:51:37 AM: Entrypoint hello = hello.js
9:51:37 AM:   [0] /opt/build/repo/node_modules/aws-sdk/lib/core.js 2.43 KiB {0} [built]
9:51:37 AM:   [1] /opt/build/repo/node_modules/aws-sdk/lib/node_loader.js 3.81 KiB {0} [built]
9:51:37 AM:   [2] /opt/build/repo/node_modules/aws-sdk/lib/util.js 30.6 KiB {0} [built]
9:51:37 AM:   [4] /opt/build/repo/node_modules/aws-sdk/clients/sts.js 573 bytes {0} [built]
9:51:37 AM:   [6] /opt/build/repo/node_modules/aws-sdk/lib/model/shape.js 11.6 KiB {0} [built]
9:51:37 AM:   [7] /opt/build/repo/node_modules/aws-sdk/lib/protocol/rest.js 4.45 KiB {0} [built]
9:51:37 AM:   [9] external "stream" 42 bytes {0} [built]
9:51:37 AM:  [22] /opt/build/repo/node_modules/aws-sdk/lib/protocol/json.js 2.17 KiB {0} [built]
9:51:37 AM:  [23] /opt/build/repo/node_modules/aws-sdk/lib/json/builder.js 1.51 KiB {0} [built]
9:51:37 AM:  [24] /opt/build/repo/node_modules/aws-sdk/lib/json/parser.js 1.68 KiB {0} [built]
9:51:37 AM:  [59] ./getimagefroms3.js 1.8 KiB {0} [built]
9:51:37 AM:  [60] /opt/build/repo/node_modules/aws-sdk/lib/aws.js 159 bytes {0} [built]
9:51:37 AM: [144] /opt/build/repo/node_modules/aws-sdk/clients/all.js 7.54 KiB {0} [built]
9:51:37 AM: [800] external ["sharp"] 42 bytes {0} [built]
9:51:37 AM: [801] ./hello.js 124 bytes {1} [built]
9:51:37 AM:     + 787 hidden modules
9:51:37 AM: Function Dir: /opt/build/repo/lambda
9:51:37 AM: TempDir: /tmp/zisi-5dbbb29650fe535e67c92def
9:51:38 AM: Prepping functions with zip-it-and-ship-it 0.3.1
9:51:42 AM: [ { path: '/tmp/zisi-5dbbb29650fe535e67c92def/getimagefroms3.zip',
9:51:42 AM:     runtime: 'js' },
9:51:42 AM:   { path: '/tmp/zisi-5dbbb29650fe535e67c92def/hello.zip',
9:51:42 AM:     runtime: 'js' } ]
9:51:42 AM: Prepping functions complete
9:51:42 AM: Caching artifacts
9:51:42 AM: Started saving node modules
9:51:42 AM: Finished saving node modules
9:51:42 AM: Started saving pip cache
9:51:42 AM: Finished saving pip cache
9:51:42 AM: Started saving emacs cask dependencies
9:51:42 AM: Finished saving emacs cask dependencies
9:51:42 AM: Started saving maven dependencies
9:51:42 AM: Finished saving maven dependencies
9:51:42 AM: Started saving boot dependencies
9:51:42 AM: Finished saving boot dependencies
9:51:42 AM: Started saving go dependencies
9:51:42 AM: Finished saving go dependencies
9:51:45 AM: Build script success
9:51:45 AM: Starting to deploy site from '/'
9:51:45 AM: Creating deploy tree 
9:51:45 AM: 0 new files to upload
9:51:45 AM: 0 new functions to upload
9:51:45 AM: Starting post processing
9:51:46 AM: Post processing done
9:51:46 AM: Site is live
9:52:09 AM: Finished processing build request in 1m25.8039486s`

**Comment by lovell** [comment]
The mention of zip-it-and-ship-it suggests you've run into https://github.com/netlify/zip-it-and-ship-it/issues/38

**Comment by justinmchase** [comment]
Nodejs requires binary modules to be compiled for the version of nodejs+platform it is being loaded into.

Sharp is a native module (aka binary module) and when you install it locally on a mac it will compile it (or download a pre-compiled binary if possible) and run that. If you then package it up and deploy it to a linux machine it will then crash as its trying to load a mac binary in linux, which doesn't work.

Therefore before deployment you need to compile it on linux using the exact same version of nodejs. Then when you package it up and deploy it it will have the right binary. I use Docker to do this.

Something like:
```
# Dockerfile
FROM node:10
WORKSPACE /app
RUN npm i
```

Then:
```
$ rm -rf node_modules
$ docker build -v $PWD:/app .
$ ./deploy.sh
```

Basically volume mount your repo into a docker container then run npm i in there and it will build it for linux. You may have to have a more complex docker image than that to get the build to work but after that succeeds your local `/node_modules` folder will have linux binaries in them.

**Comment by lovell** [comment]
Please subscribe to https://github.com/netlify/zip-it-and-ship-it/issues/38 for updates about this downstream problem.
