### ISSUE TITLE
How to resize the larger dimension between width and height?

### ISSUE THREAD

**Issue by Gappa88** [lovell/sharp#1944]
How can I resize the larger dimension between width and height of a stream?
what I would like to is something like [#236](https://github.com/lovell/sharp/issues/236) but `before` seems not implemented yet.

I would like to avoid saving the file on disk and read it again.

I also tried something else found in the sharp's issues:
```
let pipeline = sharp();
pipeline.clone().metadata(function(err,metadata){
if(metadata.width > metadata.height)
        pipeline.resize(100).pipe(this);
else
        pipeline.resize(null,100).pipe(this);
});
req.pipe(pipeline).pipe(resp);
```
but it doesn't work.

It seems that `metadata()` stops the stream somehow.

do you have any idea how to implement this?
thanks

**Comment by lovell** [comment]
Hi, yes, you'll need the future possible enhancement of #236 for this.

**Comment by Gappa88** [comment]
ah ok @lovell , is that feature scheduled for the closest future? I noticed that #236 has been opened in 2015

**Comment by lovell** [comment]
I'm always very happy to accept and provide help with Pull Requests if you're able.

**Comment by Gappa88** [comment]
understood

**Comment by Gappa88** [comment]
@lovell do you see any possible problem in the following?

```
const image = sharp();
image
  .metadata()
  .then((metadata) => {
    if (metadata.width > metadata.height) {
      return image
        .resize(100)
        .pipe(S3.uploadFromStream(params_norm));
    } else {
      return image
        .resize(null, 100)
        .pipe(S3.uploadFromStream(params_norm));
    }
  })
  .then((data)=> {
     console.log(data)
  });

req.pipe(image);
```

this way I can achieve my goal. 
Is that fine for you?

Thanks

**Comment by lovell** [comment]
Yes, that looks OK, glad you solved it.
