### ISSUE TITLE
Pre-built binaries for electron 7, OSX

### ISSUE THREAD

**Issue by larssvensby** [lovell/sharp#1948]
Hi, in sharp v0.23.2 there are pre-built binaries for electron 7 for linux and win but not for osx/darwin.
Can electron 7 binaries for OSX be added?

**Comment by lovell** [comment]
Oh, that's odd, they should have been generated by Travis in the build https://travis-ci.org/lovell/sharp/jobs/604051312 but I don't see Electron 7 in the log, only Electron 6.

My best guess would be that there was an old, cached version of the `node-abi` dependency kicking around at the point the task ran. I've restarted that specific build so let's see what happens...

**Comment by lovell** [comment]
It looks like Travis recently started caching npm dependencies by default, which means transitive dependencies could differ between build machines.

https://changelog.travis-ci.com/npm-caching-by-default-108216

I've manually deleted the Travis cache, plus updated the config to prevent this occurring again via commit b35b9f78.

Thanks for reporting this.
