### ISSUE TITLE
Handling vips warnings

### ISSUE THREAD

**Issue by Zewy** [lovell/sharp#195]
Is there a way to handel vips warnings? Or can I check if the image is ok before I use it?
here is a part of my supervisor log.

```
vips warning: VipsJpeg: read gave 3 warnings
vips warning:
vips warning: VipsJpeg: read gave 1 warnings
vips warning:
vips warning: VipsJpeg: read gave 2 warnings
vips warning:
vips warning: VipsJpeg: read gave 1 warnings
vips warning: VipsJpeg: Corrupt JPEG data: 490153 extraneous bytes before marker 0xd9
VipsJpeg: JPEG datastream contains no image

vips warning: VipsJpeg: read gave 2 warnings
vips warning:
vips warning: VipsJpeg: read gave 2 warnings
vips warning:
vips warning: VipsJpeg: read gave 6543 warnings
vips warning: VipsJpeg: Premature end of JPEG file
VipsJpeg: JPEG datastream contains no image

vips warning: VipsJpeg: read gave 6543 warnings
vips warning: VipsJpeg: Premature end of JPEG file
VipsJpeg: JPEG datastream contains no image

vips warning: VipsJpeg: read gave 2 warnings
vips warning:
vips warning: VipsJpeg: read gave 2 warnings
vips warning:
vips warning: VipsJpeg: read gave 2 warnings
vips warning:

**Comment by lovell** [comment]
You can set the `VIPS_WARNING` environment variable to silence ignorable warning messages. The [command](https://github.com/lovell/sharp/blob/master/package.json#L20) to run the functional tests uses this.

If an unrecoverable situation is reached when toFile or toBuffer are called, processing will stop and the error will be passed as the first parameter to the callback function.

**Comment by Zewy** [comment]
What I like to do is find out witch image that gave that warning so I can replace the broken file. So how do I capture the warning and print it like this instead?
```
vips warning: VipsJpeg: read gave 1 warnings on /home/user/images/img1024_2.jpg

**Comment by lovell** [comment]
If you've not already seen it, #113 is related to this question. You'll probably need to add support for what you need to libvips itself.

**Comment by Zewy** [comment]
Ah okej not mutch I can do about it then.
