### ISSUE TITLE
CI: Add Linux ARM64v8

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#1953]
### ~~FreeBSD~~

~~Depends on ports update of vips from v8.7.4 to at least v8.8.1~~

### Linux ARM64v8

Depends on https://github.com/lovell/sharp-libvips/commit/2e4202d671904666c012b142b8e21be017d30a28 and therefore its next release.

WIP branch at https://github.com/lovell/sharp/tree/ci-add-arm64

Sample failed build at https://travis-ci.org/lovell/sharp/jobs/608665895

**Comment by pouya-eghbali** [comment]
Ok so, vips was updated to 8.8.3 on freebsd ports and should be in latest repos soon.

**Comment by pouya-eghbali** [comment]
vips is 8.8.3 now on latest repos.

**Comment by lovell** [comment]
The FreeBSD CI job is now passing - https://cirrus-ci.com/task/6680438310961152

**Comment by lovell** [comment]
ARM64v8 CI job now passing - https://travis-ci.org/lovell/sharp/jobs/630581137
