### ISSUE TITLE
prebuild-install sharp binary blocked

### ISSUE THREAD

**Issue by Ivaylo-Lafchiev** [lovell/sharp#1954]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/en/stable/install/)?

Yes

Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime?

Yes

If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

No

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

Yes, can't share full output but here is the relevant bit:

> info sharp Downloading http://localhost:9000/libvips-8.8.1-darwin-x64.tar.gz
prebuild-install info begin Prebuild-install version 5.3.3
prebuild-install info looking for cached prebuild @ /Users/lafchi/.npm/_prebuilds/e4d137-sharp-v0.23.2-node-v64-darwin-x64.tar.gz
prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.23.2/sharp-v0.23.2-node-v64-darwin-x64.tar.gz
prebuild-install WARN install getaddrinfo ENOTFOUND github.com github.com:443
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.14.2 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp verb `which` failed     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /usr/local/lib/node_modules/npm/nod

What is the output of running `npx envinfo --binaries --languages --system --utilities`?

>   System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 274.75 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.14.2 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.21.0 - /usr/bin/git
  Languages:
    Bash: 3.2.57 - /bin/bash
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.1.23 - /usr/bin/php
    Python: 2.7.10 - /usr/bin/python
    Ruby: 2.3.7 - /usr/bin/ruby

My firm blocks downloading binaries from github, I was able to get around this for sharp-libvips by configuring SHARP_DIST_BASE_URL, but I can't find a similar option for the sharp node binary? Am I missing something or is this not configurable?

Building with node-gyp is also not an option.

**Comment by lovell** [comment]
Hi, did you see https://github.com/lovell/sharp/issues/1805#issuecomment-514591879 ?

**Comment by Ivaylo-Lafchiev** [comment]
Yep that's exactly what I'm looking for. I suggest adding this to the installation docs. Thanks.

**Comment by lovell** [comment]
@Ivaylo-Lafchiev I've added this in commit ff98d2e, thank you for the suggestion.
