### ISSUE TITLE
Png transparent images changes to black after resize

### ISSUE THREAD

**Issue by mayadafahim** [lovell/sharp#1956]
I am using rotate then extract to crop part of the image then i am doing 
image.resize().flatten() and it works correct to all images except for the ones with transparent background it changes them to black , any help ?

**Comment by lovell** [comment]
Hi, did you see the docs for the [flatten](https://sharp.pixelplumbing.com/en/stable/api-operation/#flatten) operation you are using? It defaults to flattening out the transparency with black, which is what you are seeing.

**Comment by mayadafahim** [comment]
@lovell i tried this before resize 
 .flatten({ background: { r: 0, g: 0, b: 0, alpha: 0 } })
but it didnot do anything differently

**Comment by mayadafahim** [comment]
i also tried removing flatten but it still turns to be black

**Comment by lovell** [comment]
If you're using JPEG as the output format then please remember it does not support transparency.

**Comment by mayadafahim** [comment]
am uploading JPG and i am not converting it , the output is still jpg and black

**Comment by mayadafahim** [comment]
![image](https://user-images.githubusercontent.com/31277826/68484235-2c6fb380-023d-11ea-9c97-22d1e47bbff9.png)

**Comment by lovell** [comment]
To help me understand this question, please can you provide the complete, standalone code you are using with this input image as well as the actual output image and if possible the expected output image.

**Comment by mayadafahim** [comment]
const image = sharp(this.buffer).rotate().resize() , thats all i am using buffer for the image, expected output : same as the input for this image case 
output: 
![image](https://user-images.githubusercontent.com/31277826/68485576-d9e3c680-023f-11ea-953b-efe3d9af856e.png)

**Comment by lovell** [comment]
Please can you provide the **complete** code you're using to produce this output.

**Comment by mayadafahim** [comment]
i do nothing more i just return the buffer await image.toBuffer() and thats all

**Comment by jcupitt** [comment]
>@lovell i tried this before resize
> .flatten({ background: { r: 0, g: 0, b: 0, alpha: 0 } })

0 is black. Perhaps try (just a guess):

```javascript
.flatten({ background: { r: 255, g: 255, b: 255, alpha: 255 } })
```

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with a complete, standalone code sample that would allow someone else to fully reproduce the issue if further help is required.

**Comment by BoneShooter** [comment]
> const image = sharp(this.buffer).rotate().resize() , thats all i am using buffer for the image, expected output : same as the input for this image case
> output:
> ![image](https://user-images.githubusercontent.com/31277826/68485576-d9e3c680-023f-11ea-953b-efe3d9af856e.png)

when you call rotate function，try this code
`sharp(this.buffer).rotate(angle, {background: { r: 0, g: 0, b: 0, alpha: 0 }})`

**Comment by pradeeshattlee** [comment]
@mayadafahim @lovell 
I have the same issue while trying to convert a png image with a transparent background  the size of the file is reduced but the image doesn't retain the transparency  

As @jcupitt suggested I tried to use 

**.flatten({ background: { r: 255, g: 255, b: 255, alpha: 255 } })**

The backgrounds changes to white but what the outcome must be transparent 

The code which @BoneShooter provided also doesn't do the trick.

I there any way I can achieve to reduce the png image size while retaining the transparency

**Comment by mayadafahim** [comment]
@pradeeshattlee i had to remove the resize eventually i couldn't find another solution

**Comment by mapmalith** [comment]
@mayadafahim 
```sharp(imageData)
        .jpeg({ quality: 50, force: true })
        .flatten({ background: { r: 255, g: 255, b: 255, alpha: 0 } })
        .resize({ width: 256 })```

As above you must use `.flatten` before `.resize`
