### ISSUE TITLE
Error: Input buffer contains unsupported image format

### ISSUE THREAD

**Issue by zhuping** [lovell/sharp#1957]
I downloaded a remote image using axios and always reported an `Input buffer contains unsupported image format` error when using sharp to convert to webp. There is no problem with the local mac system, and it will be reported to the server centos6.

```js
const dest = path.join(this.config.baseDir, `app/public/${fileName}.webp`);

return new Promise(resolve => {
    axios.get(url, { responseType: 'arraybuffer' })
    .then(({ data }) => {
        sharp(data)
        .webp({
            quality
        })
        .toFile(dest)
        .then(() => {
            resolve(dest);
        })
        .catch(e => {
            this.ctx.logger.error(new Error(e));
        });
    })
    .catch(e => {
        this.ctx.logger.error(new Error(e));
    });
});
```

Centos configuration
gcc：4.8+
python: 2.7+
libvips: 8.8.3

**Comment by lovell** [comment]
If you're using CentOS 6 then you'll probably have installed your own libvips. Was it compiled with support for the format of the input image you are using? Perhaps use [sharp.format](https://sharp.pixelplumbing.com/en/stable/api-constructor/#format) to find out.

**Comment by zhuping** [comment]
Thanks for your reply, I expect images in `jpeg` and `png` format to be converted.What causes this to happen? How can I fix this?
```js
{ id: 'jpeg',
input: { file: false, buffer: false, stream: false },
output: { file: false, buffer: false, stream: false } },
png:
{ id: 'png',
input: { file: false, buffer: false, stream: false },
output: { file: false, buffer: false, stream: false } },
webp:
{ id: 'webp',
input: { file: false, buffer: false, stream: false },
output: { file: false, buffer: false, stream: false } },
tiff:
{ id: 'tiff',
input: { file: false, buffer: false, stream: false },
output: { file: false, buffer: false, stream: false } },
magick:
{ id: 'magick',
input: { file: false, buffer: false, stream: false },
output: { file: false, buffer: false, stream: false } },
openslide:
{ id: 'openslide',
input: { file: false, buffer: false, stream: false },
output: { file: false, buffer: false, stream: false } },
dz:
{ id: 'dz',
input: { file: false, buffer: false, stream: false },
output: { file: false, buffer: false, stream: false } },
ppm:
{ id: 'ppm',
input: { file: true, buffer: false, stream: false },
output: { file: true, buffer: false, stream: false } },
fits:
{ id: 'fits',
input: { file: false, buffer: false, stream: false },
output: { file: false, buffer: false, stream: false } },
gif:
{ id: 'gif',
input: { file: false, buffer: false, stream: false },
output: { file: false, buffer: false, stream: false } },
svg:
{ id: 'svg',
input: { file: false, buffer: false, stream: false },
output: { file: false, buffer: false, stream: false } },
heif:
{ id: 'heif',
input: { file: false, buffer: false, stream: false },
output: { file: false, buffer: false, stream: false } },
pdf:
{ id: 'pdf',
input: { file: false, buffer: false, stream: false },
output: { file: false, buffer: false, stream: false } },
vips:
{ id: 'vips',
input: { file: true, buffer: false, stream: false },
output: { file: true, buffer: false, stream: false } },
raw:
{ id: 'raw',
input: { file: false, buffer: true, stream: true },
output: { file: false, buffer: true, stream: true } } }
```

**Comment by lovell** [comment]
When compiling libvips from source on CentOS 6, you'll need to ensure the optional dependencies for the formats you want are installed first, e.g. for JPEG you'll need to ensure the `libjpeg-turbo-devel` package is installed before compilation.

https://github.com/libvips/libvips#optional-dependencies

If you're able to use CentOS 7 then sharp will use prebuilt binaries that include common formats.

**Comment by zhuping** [comment]
Installing the `libjpeg-turbo-devel` package does not work, and finally solved this problem by upgrading to centos 7.😂

**Comment by patrickjane** [comment]
How would you solve this issue on e.g. MacOS? I am facing the same issue, trying to read a JPG. In the [installation instructions](https://sharp.pixelplumbing.com/install) page it says that `libvips` is shipped/downloaded during installation.

Do I have to do some manual installation on top of `npm install`? If so, is there a how-to or tutorial somewhere? Really I am just trying to follow the most basic example currently :)

**Comment by lovell** [comment]
@patrickjane Please [open a new question issue](https://github.com/lovell/sharp/issues/new?labels=question&template=question.md), ensuring you provide sample code and image(s).
