### ISSUE TITLE
0.23.x Sharp versions not detecting installed FreeBSD vips pkg

### ISSUE THREAD

**Issue by jhfoo** [lovell/sharp#1959]
Sharing the above for awareness and hopefully a long term fix. Details here: https://github.com/gridsome/gridsome/issues/783

Let me know if you need more info, or if I can help validate the fix.

**Comment by lovell** [comment]
Hi, this was very recently fixed via #1952 and will be included in v0.23.3

See also #1953 that will add FreeBSD to the CI matrix to prevent this occurring again.

**Comment by jhfoo** [comment]
Thanks looking forward to it!

**Comment by lovell** [comment]
v0.23.3 now available.

**Comment by jhfoo** [comment]
Validated issue solved without need for workaround.
