### ISSUE TITLE
Error: Input buffer containing unsupported image format

### ISSUE THREAD

**Issue by awsafanam** [lovell/sharp#1960]
Hi,
We have a jpeg file. The ImageMagick inspect output is as below:
`filename.jpeg BMP3 1280x960 1280x960+0+0 8-bit sRGB 3.51568MiB 0.016u 0:00.086`

When we try to resize the file using sharp, we get 
`Uncaught Exception: Input buffer containing unsupported image format`

Is there a fix to this error?
Is this happening because of the jpeg's file type (BMP3), Are there any plans to supporting this in the near future?

Thanks for the awesome tool.
![filename](https://user-images.githubusercontent.com/8945481/68528714-b17fc900-0320-11ea-91ef-a238b2baa47d.jpeg)

**Comment by lovell** [comment]
Hi, this image is in BMP format and is not a JPEG. Please see #806 for a possible way to preprocess BMP images for use with sharp.
