### ISSUE TITLE
Is it possible to .resize() an animated GIF?

### ISSUE THREAD

**Issue by eddiejibson** [lovell/sharp#1961]
Hi,

I tried to find this in the documentation, but couldn't really find it anywhere.

With other packages such as Imagemagik, you're able to effectively turn an animated GIF into a composite of images and then resize them individually - at the end putting them back into the original "sequence". Just wondering if this is possible with Sharp and if there's an example around. 

Thanks.

**Comment by lovell** [comment]
Please see #1372 for a future possible enhancement to allow GIF output.
