### ISSUE TITLE
 Failed at the sharp@0.23.2 install script.

### ISSUE THREAD

**Issue by ChiKaLiO** [lovell/sharp#1962]
What is the output of running `npx envinfo --binaries --languages --system --utilities`?

`System:
    OS: Linux 4.4 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (1) x64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
    Memory: 450.54 MB / 990.61 MB
    Container: Yes
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 10.16.3 - /opt/bitnami/nodejs/bin/node
    npm: 6.9.0 - /opt/bitnami/nodejs/bin/npm
  Utilities:
    Make: 4.1 - /usr/bin/make
    GCC: 5.4.0 - /usr/bin/gcc
    Git: 2.19.1 - /opt/bitnami/git/bin/git
  Languages:
    Bash: 4.3.48 - /bin/bash
    Perl: 5.22.1 - /usr/bin/perl
    Python3: 3.7.4 - /opt/bitnami/python/bin/python3
`

What are the steps to reproduce?
just npm install then node app.js on aws ec2 using ssh

What is the expected behaviour?
the error mentioned in the title ` Failed at the sharp@0.23.2 install script.`

**Comment by lovell** [comment]
What is the complete output of running `npm install --verbose sharp`?

**Comment by blakefaulds** [comment]
Having the same issue.
`npm verb lifecycle sharp@0.23.2~install: CWD: C:\wamp64\www\charlesNYC\node_modules\sharp
npm info lifecycle sharp@0.23.2~install: Failed to exec install script
npm timing action:install Completed in 5322ms
npm verb unlock done using C:\Users\bfaul\AppData\Roaming\npm-cache\_locks\staging-d53581ac797839c0.lock for C:\wamp64\www\charlesNYC\node_modules\.staging
npm timing stage:rollbackFailedOptional Completed in 205ms
npm timing stage:runTopLevelLifecycles Completed in 34739ms
npm WARN react-addons-css-transition-group@15.6.2 requires a peer of react@^15.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-addons-transition-group@15.6.2 requires a peer of react@^15.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-marquee@1.0.0 requires a peer of react@~0.14.0 || ~15.0.0 || ~16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-marquee@1.0.0 requires a peer of react-dom@~0.14.0 || ~15.0.0 || ~16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN ts-pnp@1.1.4 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN The package react is included as both a dev and production dependency.
npm WARN The package react-dom is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.1 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

npm verb stack Error: sharp@0.23.2 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:193:13)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:193:13)
npm verb stack     at maybeClose (internal/child_process.js:999:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
npm verb pkgid sharp@0.23.2
npm verb cwd C:\wamp64\www\charlesNYC
npm verb Windows_NT 10.0.17763
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose" "sharp"
npm verb node v11.14.0
npm verb npm  v6.7.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.23.2 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.23.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 38080ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bfaul\AppData\Roaming\npm-cache\_logs\2019-11-12T00_56_24_116Z-debug.log`

**Comment by blakefaulds** [comment]
Ok I solved it I should have included the full log as it included

C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 10.0.171
34.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarg
et solution". [C:\wamp64\www\testproject\node_modules\gatsby-plugin-manifest\node_modules\sharp\build\libvips-cpp.vcxproj]

I just needed to update my VS to include SDK v 10.0.171 through an update and all is right with world!

**Comment by lovell** [comment]
@ChiKaLiO Were you able to make any progress with this?

**Comment by mwaddell** [comment]
I'm having the same issue on a Jenkins CI Windows box.

The full npm log is attached:
[2019-11-27T00_22_18_964Z-debug.log](https://github.com/lovell/sharp/files/3898340/2019-11-27T00_22_18_964Z-debug.log)

**Comment by mwaddell** [comment]
Output of running npx envinfo --binaries --languages --system --utilities

  System:
    OS: Windows Server 2008 6.1.7601
    CPU: (4) x64 Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
    Memory: 2.53 GB / 8.00 GB
  Binaries:
    Node: 8.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Java: 1.8.0_05
    Perl: 5.18.2 - C:\strawberry\perl\bin\perl.EXE

**Comment by lovell** [comment]
@mwaddell Did you see the following entry in the log file you posted?

> 45267 warn lifecycle The node binary used for scripts is C:\Program Files (x86)\Jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJS\node.exe but npm is using C:\Program Files\nodejs\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

**Comment by mwaddell** [comment]
No, I missed that - I fixed that issue and now get the attached.

[2019-11-27T21_10_08_748Z-debug.log](https://github.com/lovell/sharp/files/3898873/2019-11-27T21_10_08_748Z-debug.log)

**Comment by lovell** [comment]
@mwaddell There are a lot of dependencies unrelated to sharp listed in there. Please can you run `npm install --verbose sharp` in an empty directory.

**Comment by mwaddell** [comment]
[log.txt](https://github.com/lovell/sharp/files/3898914/log.txt)

Looks like it's failing to find a C compiler - is that something sharp is looking for or is that a fallback because of a missing dependency?

**Comment by lovell** [comment]
> prebuild-install WARN install No prebuilt binaries found (target=11.3.0 runtime=node arch=x64 libc= platform=win32)

You're using Node.js 11, which reached end-of-life in June.

**Comment by mwaddell** [comment]
Yep - that was it -- @ChiKaLiO is using Node 10.16.3 so he's probably got the same problem.

Thanks,
Michael

**Comment by lovell** [comment]
Node.js 10 is still very much supported by sharp.

**Comment by mwaddell** [comment]
Thank you for your help. I'm very new to the node ecosystem. Hopefully ChiKaLiO can resolve his/her issue as well

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by ChiKaLiO** [comment]
sorry i was busy what i did is uninstall sharp but keeping it in package.json so the problem is that i'm pushing node module from windows machine to ubuntu (heroku)
