### ISSUE TITLE
Error: Cannot find module 'sharp' with webpack

### ISSUE THREAD

**Issue by BigIdeas** [lovell/sharp#1965]
Hi - I am trying to run an app that depends on sharp in a docker image with webpack but get the above error (`Error: Cannot find module 'sharp'`) when trying to run the image. I have instructed webpack to treat sharp as an external module as discussed in other issues by adding this to my webpack.config.js:

```
externals: {
  sharp: 'commonjs sharp'
}
```

Do I also need to add a step to my build process to build the module (for my specific environment)? How can I check that the module is built at a location where the loader can find it? Should I be using the `node-loader` package (it didn't help configuring webpack to use `node-loader` to load `.node` files but maybe I was doing something else wrong)?

**Comment by lovell** [comment]
@BigIdeas Were you able to make any progress with this?

**Comment by BigIdeas** [comment]
Thanks for following up! I got it working for now by adding `RUN npm install sharp` to my Dockerfile.

I think I'll try to resolve it properly by either moving the dependency on `sharp` from my workspace to the project's root (I'm using yarn and lerna) and/or running my project on a less bare bones container.

**Comment by JosiahVillanueva** [comment]
Hi @lovell can you help with this one. Also experiencing the same issue on my end

https://stackoverflow.com/questions/61634085/this-type-of-error-comes-cannot-find-module-sharp
