### ISSUE TITLE
Not working inside VScode extension

### ISSUE THREAD

**Issue by mbrammer** [lovell/sharp#1966]
When using sharp inside VScode, the following exception will be thrown.

```
TypeError: Cannot read property 'format' of undefined at Object.<anonymous> ([...]/node_modules/sharp/lib/constructor.js:250:22)
```

This is thrown because of:

`Module did not self-register.` -> `sharp = require('../build/Release/sharp.node');`

**Comment by mbrammer** [comment]
Probably relates to #1965.

**Comment by lovell** [comment]
VSCode is Electron-based so you'll need to use electron-rebuild.

https://electronjs.org/docs/tutorial/using-native-node-modules

**Comment by mbrammer** [comment]
Perfect! This was the missing information :) Thanks!
