### ISSUE TITLE
Cannot install Sharp on Windows 10  64bit

### ISSUE THREAD

**Issue by vndevil** [lovell/sharp#1967]
When I run install sharp I get this error

> npm verb stack Error: sharp@0.21.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Users\vndev\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:210:5)
npm verb stack     at ChildProcess.<anonymous> (C:\Users\vndev\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:210:5)
npm verb stack     at maybeClose (internal/child_process.js:1028:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
npm verb pkgid sharp@0.21.3
npm verb cwd D:\Working\Freelands\intracom.com.vn
npm verb Windows_NT 10.0.18363
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\vndev\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose" "sharp"
npm verb node v13.1.0
npm verb npm  v6.13.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.21.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.21.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 27415ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vndev\AppData\Roaming\npm-cache\_logs\2019-11-13T14_52_50_225Z-debug.log

**Comment by lovell** [comment]
Node.js 13 support was added in v0.23.2

#1909

**Comment by vndevil** [comment]
I was uninstall nodejs 13 and install nodejs 11 and it resolved this issue
