### ISSUE TITLE
SVG pipe support

### ISSUE THREAD

**Issue by naonak** [lovell/sharp#197]
Hi,

Sharp is just great but I find an issue.

libvips 7.42 and Sharp 0.9.3

Thanks for your help

```
// Work :
var transformer = sharp('Wikipedia-W-visual-balanced.svg')
  .background('#ffffff')
  .flatten()
  .jpeg()
  .toFile('output.jpg');

// Fail :
var transformer = sharp()
  .background('#ffffff')
  .flatten()
  .jpeg()

http.get('http://upload.wikimedia.org/wikipedia/commons/4/46/Wikipedia-W-visual-balanced.svg', function(response) {

  var writeStream = fs.createWriteStream('output.jpg');
  var stream = response.pipe(transformer).pipe(writeStream);

}).on('error', function (err) {
    console.log('An error occurred!', err);
})

```
```
Error: Error: Input buffer contains unsupported image format
    at /home/www/mar7.local/www/ma-reduc-com/mar-sidi/node_modules/sharp/index.js:555:32
```

**Comment by lovell** [comment]
Hi Fabien, you can see which formats/methods are available in your combination of sharp/libvips versions via the [format](https://github.com/lovell/sharp#format) attribute:
```javascript
var sharp = require('sharp');
console.dir(sharp.format);
```

For Stream-based (and Buffer-based) input of SVG and other "magick" formats, you'll need the bleeding edge libvips v8.0.0 (via its master branch on Github), which includes commit https://github.com/jcupitt/libvips/commit/dba1b1d81b640f06716d1ee95a3c8fc5d80cd843

You'll also need to use the forthcoming v0.10.0 release of sharp, which can be trialled via:
```sh
npm install lovell/sharp#judgement
```
Hope this helps.

**Comment by lovell** [comment]
Watch out for the low-resolution problem of #110 if you're using SVG input.

**Comment by naonak** [comment]
Thanks a lot for your answer !

**Comment by kapouer** [comment]
Using libvips 8.2 from debian/sid and sharp 0.12.2 i get
`Error: Input buffer contains unsupported image formatVipsForeignLoad: buffer is not in a known format`
using https://github.com/kapouer/url-inspector-daemon/blob/master/lib/sharpie.js

**Comment by kapouer** [comment]
Uuuh i see, this is related to https://github.com/lovell/sharp/issues/220 and probably the svg i'm testing it with is received gzipped.
