### ISSUE TITLE
Photoshop levels window

### ISSUE THREAD

**Issue by nastakhov** [lovell/sharp#1970]
Lovell, thank you for the awesome library!

Question is, is it possible to do manipulation with sharp, like it is done by photoshop  Levels window. 
In photoshop i do this by moving left arrow to the most right position:

From:
![from](https://user-images.githubusercontent.com/3192480/68994929-f364be00-0890-11ea-8a65-17defac07791.png)

To:
![to](https://user-images.githubusercontent.com/3192480/68994934-fb246280-0890-11ea-9e90-559751181264.png)

The overall goal is to show 'isolated' image. 

-----
Found image magick command line alternative:

**convert input.jpg -level 98%,100%,1.0 output.jpg**

**Comment by lovell** [comment]
Hi, what you need is not available right now, but there is a future possible enhancement being discussed at #1066 that might do something very similar.

**Comment by nastakhov** [comment]
Thank you, I'll watch that other task

**Comment by neave** [comment]
It's possible to adjust the input levels using `linear`.

If you have the first input level at 100 and the second input level at 200, and output levels the same at 0 to 255:

<img width="524" alt="Screenshot 2020-10-13 at 10 47 19" src="https://user-images.githubusercontent.com/129713/95845001-875d3500-0d41-11eb-968b-88b989e02e7c.png">

Then this would apply a levels effect:

```
const levelsToLinear = (min, max) => {
	const scale = 255 / (max - min);

	return {
		a: scale,
		b: -min * scale
	}
};

const { a, b } = levelsToLinear(100, 200);

await sharp(image).linear(a, b).png().toFile(...);

```

However this won't adjust the midtone level (the central input value of 1). Hopefully #1066 will help there.
