### ISSUE TITLE
404 error - Broken docs sub-pages links when opening from the version badge/button.

### ISSUE THREAD

**Issue by sebinbenjamin** [lovell/sharp#1971]
The version badge/button which provides options to view the docs for different release versions leads to a 404 error page, when used from any of the sub-topic pages (API, Performance etc). 

![Peek 2019-11-16 20-53](https://user-images.githubusercontent.com/4099066/68995443-fc1abb80-08b3-11ea-89ba-8e1ebe1eec0f.gif)

The links are in the wrong format https://sharp.pixelplumbing.com/en/v0.19.0/api-input.html instead of https://sharp.pixelplumbing.com/en/v0.19.0/api-input. I guess the unnecessary `.html` is added causing this issue. 

**Browsers Tested**
1. Mozilla Firefox 70.0.1 (64-bit)
2. Google Chrome Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by lovell** [comment]
Hi, this looks like a bug somewhere deep inside [readthedocs](https://readthedocs.org/).

I've been meaning to replace it with something like Docusaurus for a while as there are other related problems such as #1451.

**Comment by lovell** [comment]
The replacement of readthedocs is being tracked at #1974.
