### ISSUE TITLE
Docs: switch from readthedocs to docute

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#1974]
I've spent a while investigating and assessing various options to replace readthedocs, including but not limited to docusaurus, docsify, docpress, gitbook and vuepress.

I really like the docsify approach and then discovered the similar but-with-more-bells-attached [docute](https://github.com/egoist/docute) and it appears to support pretty much everything we need (and more):

* retrieves *versioned* markdown files from GitHub, optionally via jsdelivr
* customisable URL router to redirect existing readthedocs URLs
* easy to define navigation/sidebar/TOC
* custom components/banner/footer via Vue
* sends anonymous usage data to GA

(For examples of problems reported about readthedocs, please see #1451 and #1971.)

**Comment by sebinbenjamin** [comment]
docute looks good. Can I work on this ?

**Comment by lovell** [comment]
@sebinbenjamin Yes please, any help with this would be most welcome.

**Comment by lovell** [comment]
The Docute-based docs for the work-in-progress v0.24.0 release can be viewed at the temporary URL of https://pixelplumbing-sharp.firebaseapp.com/ - these will be promoted to become the main docs at the same time as v0.24.0 is published.

I intend to overhaul the installation page before that release too.

**Comment by lovell** [comment]
New docs now live, thanks again for your help Sebin.

https://sharp.pixelplumbing.com/
