### ISSUE TITLE
Memory leak when using with stream

### ISSUE THREAD

**Issue by EdmundMai** [lovell/sharp#1975]
What is the output of running `npx envinfo --binaries --languages --system --utilities`?
```

  System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 284.14 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.21.0 - /usr/bin/git
    Clang: 1100.0.33.8 - /usr/bin/clang
    Subversion: 1.10.4 - /usr/bin/svn
  Languages:
    Bash: 3.2.57 - /bin/bash
    Go: 1.12.4 - /usr/local/bin/go
    Elixir: 1.8.1 - /usr/local/bin/elixir
    Java: 1.8.0_112 - /usr/bin/javac
    Perl: 5.28.1 - /usr/local/bin/perl
    PHP: 7.3.8 - /usr/bin/php
    Python: 2.7.16 - /usr/local/bin/python
    Python3: 3.6.6 - /Library/Frameworks/Python.framework/Versions/3.6/bin/python3
    Ruby: 2.5.0 - /Users/edmundmai/.rbenv/shims/ruby


```

What are the steps to reproduce?
```
import S3 from "../services/s3";
import sharp from "sharp";

export default {
  Mutation: {
    updateProgressPics: async (parent, { file }, { models, currentUser }) => {
        const { createReadStream } = await file;
        const stream = createReadStream();

        const transformer = sharp()
          .rotate()
          .resize({
            width: 700,
            height: null,
          })
          .png();

        const resizedStream = stream.pipe(transformer);

        const { Location: url, Key: key, Bucket: bucket } = await S3.upload({
          stream: resizedStream,
          filename,
          folder: currentUser.id,
        });

        return true;
      }
  },
};
```

s3.js:

```
import AWS from "aws-sdk";

import { AWS_CONFIG, S3_BUCKET } from "../../config";

AWS.config.update(AWS_CONFIG);

const s3 = new AWS.S3();

export const upload = async ({ folder, filename, stream }) => {
  const params = {
    Bucket: S3_BUCKET,
    Key: `${folder}/${filename}`,
    Body: stream,
  };

  const options = { partSize: 10 * 1024 * 1024, queueSize: 1 };

  return s3.upload(params, options).promise();
};

export default {
  upload,
};

```

What is the expected behaviour?
I expect the memory usage of my server to stay flat. However my server with 512 MB of RAM and  other server with 1 GB of RAM are facing the same issue with the memory leak causing my servers to explode:

![skincare-tracker_·_Metrics___Heroku](https://user-images.githubusercontent.com/1857068/69026387-a79d3c00-0998-11ea-822a-1398629c374d.png)

When I removed my call to sharp, my memory usage was flat:

![skincare-tracker_·_Metrics___Heroku](https://user-images.githubusercontent.com/1857068/69026447-e206d900-0998-11ea-81ed-e4f76cf51725.png)

This person seems to have faced the exact same issue as I did: https://malcoded.com/posts/nodejs-image-resize-express-sharp/

> Secondly, image manipulation does cost some memory. I had sharp running on Heroku for a while to serve the images on this blog. Unfortunately, the machine had only 512MB of memory to work with. Even with garbage-collection set to "rampage"-mode, the server would occasionally hit the memory limit. That being said, I suspect that there was a memory leak going on, too.

Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?
Sort of, I think the memory leak will still happen even without s3.

Are you able to provide a sample image that helps explain the problem?
See above

**Comment by lovell** [comment]
If you didn't see it, please full read everything discussed in #955 to learn more about memory allocation and why it is unlikely you are seeing the effects of a memory leak.

(Your question says the system is "OS: macOS 10.15" and "Memory: 284.14 MB / 16.00 GB" but you later say "my server with 512 MB of RAM and other server with 1 GB of RAM..." so you may want to update the system details.)

**Comment by EdmundMai** [comment]
Adding the jemalloc buildpack on heroku fixed it!!! Thanks!!

**Comment by lovell** [comment]
I've added a reference to this buildpack in the Heroku-specific docs via commit 94d51a9
