### ISSUE TITLE
About offline installation

### ISSUE THREAD

**Issue by lchrennew** [lovell/sharp#1977]
What are you trying to achieve?
@lovell 
- I want to install PRECOMPILED sharp in an completely offline enviroment where cannot connect to WWW (for regulation reason)
- I need a full guide to do that. Thanks!
- I need a full installation pack to do that. Thanks!

Have you searched for similar questions?
Yes

Are you able to provide a standalone code sample that demonstrates this question?
NO

Are you able to provide a sample image that helps explain the question?
NO

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/en/stable/install/#pre-compiled-libvips-binaries provides information about environment variables that allow the of use of alternative/private URLs.

**Comment by lchrennew** [comment]
> https://sharp.pixelplumbing.com/en/stable/install/#pre-compiled-libvips-binaries provides information about environment variables that allow the of use of alternative/private URLs.

Thanks @lovell , but is there a tarball file I can use to install sharp?
```
npm install ./sharp.tgz
```

**Comment by lovell** [comment]
You could create such a tarball on a machine with network access first. Alternatively you could install libvips globally then sharp will compile itself from source.

**Comment by lchrennew** [comment]
> You could create such a tarball on a machine with network access first. Alternatively you could install libvips globally then sharp will compile itself from source.

Thank you @lovell
