### ISSUE TITLE
ERR! sharp Use with glibc version 2.12 requires manual installation of libvips >= 8.7.4

### ISSUE THREAD

**Issue by Jeromy-L** [lovell/sharp#1978]
I  want to install sharp on the server，but when I execute the npm install sharp, I got this error message.   Is this error because there is no dependency on the machine（libvips）?   And the package was installed in the private internet？ is it because installed private

![image](https://user-images.githubusercontent.com/16909700/69114730-2c837500-0ac1-11ea-8ff9-b3950827b3db.png)

**Comment by lovell** [comment]
The use of glibc 2.12, which is almost 10 years old, suggests this is RHEL/CentOS 6 so you'll need to install libvips yourself.

https://sharp.pixelplumbing.com/en/stable/install/#linux

> For 32-bit Intel CPUs and older Linux-based operating systems such as those based on Red Hat Enterprise 6 (e.g. CentOS 6) compiling libvips from source is recommended.
>  https://libvips.github.io/libvips/install.html#building-libvips-from-a-source-tarball

Prebuilt binaries are provided for more recent operating systems.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by muzixiaosanshi** [comment]
@lovell Dear Lovell,I came across same issue like above Jeromy , I saw you comment "install libvips by yourself" and I installed libvips already , but when i re-install sharp  the same question also happen .Do you know what's the reason?Thanks for your reply advance.  
![image](https://user-images.githubusercontent.com/18609558/100075467-ee125a00-2e7a-11eb-8ef9-bf38a41bd6d7.png)

**Comment by lovell** [comment]
@muzixiaosanshi https://sharp.pixelplumbing.com/install#custom-libvips

> To use a custom, globally-installed version of libvips instead of the provided binaries, make sure it is at least the version listed under config.libvips in the package.json file and that it can be located using pkg-config --modversion vips-cpp.
