### ISSUE TITLE
Error relocating /usr/lib/libheif.so.1: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found

### ISSUE THREAD

**Issue by wouterds** [lovell/sharp#1979]
Out of nowhere my node process started crashing while nothing has changed, I just rebuilt the image. I'm using sharp on an Alpine Docker image that's running on ARM, this used to work fine when I built this image a month or 2 back but now the process crashes with the following whenever Sharp is invoked.

```text
node_1   | Something went wrong installing the "sharp" module
node_1   | 
node_1   | Error relocating /usr/lib/libheif.so.1: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
node_1   | 
node_1   | - Remove the "node_modules/sharp" directory, run "npm install" and look for errors
node_1   | - Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
node_1   | - Search for this error at https://github.com/lovell/sharp/issues
```

![Screenshot 2019-11-22 at 13 30 07](https://user-images.githubusercontent.com/1210628/69425938-35c44a00-0d2c-11ea-8c03-6f27be1d6274.jpg)

My Docker image looks like this:
```Dockerfile
FROM arm32v6/node:12-alpine
WORKDIR /code

COPY ./package.json ./
COPY ./yarn.lock ./
COPY ./.next ./.next
COPY ./public ./public
COPY ./config.js ./next.config.js
COPY ./qemu-arm-static /usr/bin/qemu-arm-static
RUN apk add vips-dev build-base --upgrade --no-cache \
    --repository https://alpine.global.ssl.fastly.net/alpine/edge/community/ \
    --repository https://alpine.global.ssl.fastly.net/alpine/edge/main
RUN yarn --production

FROM arm32v6/node:12-alpine
WORKDIR /code

COPY --from=0 /code /code
COPY ./qemu-arm-static /usr/bin/qemu-arm-static
RUN apk add vips --upgrade --no-cache \
    --repository https://alpine.global.ssl.fastly.net/alpine/edge/community/ \
    --repository https://alpine.global.ssl.fastly.net/alpine/edge/main && \
    rm /usr/bin/qemu-arm-static

EXPOSE 3000

CMD ["npm", "start"]
```

**Comment by lovell** [comment]
Hi, this looks like a C++ ABI change unrelated to sharp:

https://github.com/search?q=_ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev&type=Issues

**Comment by wouterds** [comment]
Ok, I'm still somewhat clueless on what's next or how I can get sharp working. How do I get around this?

**Comment by wouterds** [comment]
The problem resolved itself, new builds are not crashing anymore 🙄...

**Comment by zee-german** [comment]
We encounter the same problem out of nowhere without any changes in the packages.

```
Something went wrong installing the "sharp" module

Error relocating /usr/lib/libheif.so.1: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
```

Tested Versions
Docker images are the official ones from docker hub (node:alpine)
- (Node) 12.13.1 and 10.17.0
- (sharp) 0.23.3 and 0.22.1

**Comment by lovell** [comment]
This recent commit in Alpine Linux aports is relevant:

https://github.com/alpinelinux/aports/commit/2f6bc1cb9b406078ebc8e9621231a50159680dd9

The issues linked to in the commit message are not relevant to either libvips or libheif and I cannot find any other PR or approval process for this change.

The user who made the change appears to have been recently granted permission to commit directly to the master branch of Alpine Linux aports:

https://github.com/alpinelinux/aports/commits?author=maxice8

**Comment by jredbeard** [comment]
We seem to be running into this same issue with github.com/steemit/imagehoster - Any ideas?

**Comment by lovell** [comment]
It looks like Alpine has moved from GitHub to its own GitLab instance, so you'll need to ask for help there.

https://gitlab.alpinelinux.org/alpine/aports/issues/10962

**Comment by jredbeard** [comment]
Thanks @lovell 👍

**Comment by ualasandro** [comment]
@wouterds , how did you solved it? I generated a new build but the problem is persisting.
Here is my Dockerfile:
````
FROM keymetrics/pm2:10-alpine

WORKDIR /usr/src/vamu.la

COPY src src/
COPY package.json .
COPY ecosystem.config.js .

ENV NPM_CONFIG_LOGLEVEL warn

RUN \
  apk add --update --no-cache --virtual .build-deps make gcc g++ python && \
  apk add --update --no-cache vips-dev fftw-dev build-base \
    --repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
    --repository http://dl-cdn.alpinelinux.org/alpine/edge/community && \
  npm install --production && \
  apk del .build-deps && \
  touch configs.yml

EXPOSE 3000

CMD [ "pm2-runtime", "start", "ecosystem.config.js" ]

````

**Comment by maxice8** [comment]
Someone asked me about this on the gitlab.a.o instance's issue. [Response](https://gitlab.alpinelinux.org/alpine/aports/issues/10962#note_56002)
