### ISSUE TITLE
SVG without encoding declaration but with non-ASCII characters can't be loaded

### ISSUE THREAD

**Issue by ugljesas** [lovell/sharp#1980]
What is the output of running `npx envinfo --binaries --languages --system --utilities`?
Reproduced in multiple envs

What are the steps to reproduce?
Try loading an SVG containing non-ASCII characters.

What is the expected behaviour?
The SVG is loaded correctly.

Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?
sharp(fs.readFileSync('test.svg')).toBuffer().catch(console.error)

Are you able to provide a sample image that helps explain the problem? attached
[test.svg.zip](https://github.com/lovell/sharp/files/3879957/test.svg.zip)

**Comment by lovell** [comment]
Hi, this file is missing the XML declaration:
```xml
<?xml version="1.0" encoding="UTF-8"?>
```

**Comment by ugljesas** [comment]
True, I just tested adding the declaration and it seems to work with that.

I guess I can implement a workaround for now.

Thanks!
