### ISSUE TITLE
Blurry image, when resizing from big size to small

### ISSUE THREAD

**Issue by Albertbol** [lovell/sharp#1982]
**Hey,**
First of all thanks for such a great library, i appreciate your time investment in this project for all of us!

Now to the question:
I have high quality image 2980x3974 .jpg, i want to make it smaller to 200px height and i set auto width, but i get very blurry image back, cant figure out what settings i need to pass to have good quality sharp image back.
**Code snippet:**
```
     await sharp(tmpFilePath)
      .resize(null, 200, {
        kernel: sharp.kernel.kernel
      })
      .jpeg({
        quality: 100,
        chromaSubsampling: '4:4:4',
        kernel: sharp.kernel.kernel
      })
      .sharpen()
      .rotate()
      .toFile(tmp200x200Path)

```
I tried to use sharpen only in one place, in two places, all possible options, tried kernel: 'cubic', but allways same result, with very blurry image.

**Comment by lovell** [comment]
Are you able to provide a sample image that helps explain the question?

**Comment by Albertbol** [comment]
Sure
Original image:
![original](https://user-images.githubusercontent.com/43991741/69477600-77b2c600-0de8-11ea-85e8-4e49d15ccd3c.jpg)
Resied:
![resized](https://user-images.githubusercontent.com/43991741/69477601-77b2c600-0de8-11ea-9adc-8893d0942ff2.jpeg)

**Comment by lovell** [comment]
Thanks, to help me understand your expectations, are you able to produce an image at the same dimensions using a different application to demonstrate how sharp compares?

The default resizing kernel used for downsampling by sharp (and libvips) is Lanczos 3, which usually produces the best results for the vast majority of cases.

In your code sample, I note you've set `kernel` to the undefined `sharp.kernel.kernel` so it will default to "lanczos3", plus you're passing an ignored `kernel` property to `jpeg()`.

JPEG is lossy, even at "100% quality", so perhaps try the lossless PNG format for output.

You might want also to explore changing the `fastShrinkOnLoad` property on `resize()`.

https://sharp.pixelplumbing.com/en/stable/api-resize/#resize
https://sharp.pixelplumbing.com/en/stable/api-output/#jpeg

**Comment by Albertbol** [comment]
Can i ask how to convert image?
```
 await sharp(tmpFilePath)
      .resize(null, 200, {
        kernel: sharp.kernel.kernel
      })
      .toFormat('png')
      .rotate()
      .toFile(tmp200x200Path)
```
Still saving as a jpeg...

**Comment by lovell** [comment]
Your code should produce PNG output (`toFormat` takes precedence over any filename extension - this is a tested scenario e.g. https://github.com/lovell/sharp/blob/master/test/unit/io.js#L526).

Were you able to produce an image at the same dimensions using a different application to demonstrate how sharp compares?

**Comment by Projkt-James** [comment]
I'm also having some issues with blurry downscale resizing.

Original:
![surface (orig)](https://user-images.githubusercontent.com/750541/71054130-85b3f680-219c-11ea-8a84-2c1ead373eeb.jpg)

Sharp (200px width, auto heigh downscale)
![surface (sharp 200)](https://user-images.githubusercontent.com/750541/71054131-8a78aa80-219c-11ea-93ed-e61a39bb39e0.jpg)

Paint (200px width downscale)
![surface (paint 200)](https://user-images.githubusercontent.com/750541/71054143-96fd0300-219c-11ea-87e8-3811efb194a2.jpg)

`
return Promise.resolve(sharpImageCopy
    .resize(resize.width, resize.height, {
            fastShrinkOnLoad: false
        })
        .jpeg({
            quality: 100
        })
        .toBuffer()
.catch(async (e) => {
    throw new ImageHandlerException({
        message: "Caught sharp error when resizing derivative.",
        code: ResultCode.GenerateDerivativeError,
        error: e,
        metadata: imageData
    })
}));
`

**Comment by Projkt-James** [comment]
After looking into this further, this may be an underlying vips issue as resize looks to be similar using vips-cli lanczos3.

`vips resize image.jpg image-vips.jpg 0.1041666666666667‬ --kernel lanczos3`

![image](https://user-images.githubusercontent.com/750541/71055864-df1f2400-21a2-11ea-9ee6-740fe6564789.png)

**Comment by lovell** [comment]
I think MS Paint uses GDI+ under the hood so will be either bilinear or bicubic interpolation:

https://docs.microsoft.com/en-us/windows/win32/gdiplus/-gdiplus-using-interpolation-mode-to-control-image-quality-during-scaling-use

**Comment by kleisauke** [comment]
According to https://stackoverflow.com/a/48855445/10952119 it seems MS Paint also sharpens the image with a convolution kernel after resizing. I tried this:
```bash
width=$(vipsheader -f width owl-black.jpg)
height=$(vipsheader -f height owl-black.jpg)
# size=$((width > height ? width : height))
# factor=$(bc <<< "scale=10; 200 / $size")
# vips resize owl-black.jpg x.v $factor --kernel cubic
hscale=$(bc <<< "scale=10; 200 / $width")
vscale=$(bc <<< "scale=10; 112 / $height")
vips resize owl-black.jpg x.v $hscale --vscale $vscale --kernel cubic

cat > mask.con <<EOF
3 3 1 0
0.0 -0.125 0.0
-0.125 1.5 -0.125
0.0 -0.125 0.0
EOF
vips conv x.v x.jpg mask.con --precision float
```
<sup>(I used bicubic interpolation instead of bilinear)</sup>

Output:
![x](https://user-images.githubusercontent.com/12746591/71097066-b3ef0180-21af-11ea-808e-098ed5fbf29e.jpg)
<sup>vips 8.8.4</sup>

![x2](https://user-images.githubusercontent.com/12746591/71097074-b7828880-21af-11ea-922b-586d046f582c.jpg)
<sup>vips 8.9.0 (with [this patch](https://github.com/kleisauke/vips-issue-703/blob/master/0001-Partially-fix-for-issue-703.patch) applied)</sup>

The patched vips image looks almost identical to the MS Paint one (try to switch the images in your browser at 500% zoom level). The owl's eye only looks more saturated in MS Paint, but I'm not sure if that's the "correct output".

**Comment by Projkt-James** [comment]
@kleisauke @lovell unfortunately I am only just starting down the rabbit hole of image interpolation, I apologise for my lack or knowledge in this space. Is the performance of lanczos3 treated as bug or desired output?

**Comment by lovell** [comment]
The use of bicubic interpolation can result in greater overshoot/halo/moire effects compared with Lanczos, but it depends on the source image.

I'll close this question as the ability to specify interpolator and convolution kernels are already available and supported in both libvips and sharp.

**Comment by Andrew-web-coder** [comment]
@lovell Please, provide a working solution to this issue. The homepage has tons of examples, and it is great, but isn't it ridiculous that the tool named "sharp" does not have any sample/info about how to make images sharp. I am creating thumbnails from big images and they are too blurry, I tried to use `sharpen` with random numbers (no idea what they are, because there is no demo/examples given), but I am not satisfied with the outcome.

**Comment by lovell** [comment]
@Andrew-web-coder If there's a specific image you'd like help with, please open a new issue with the code you are using and ensuring you detail all of the approaches you've tried so far, including the useful (and very much not "ridiculous") suggestions in this issue to try different [resizing kernels](https://sharp.pixelplumbing.com/api-resize#resize) and applying a [convolution kernel](https://sharp.pixelplumbing.com/api-operation#convolve).

**Comment by Andrew-web-coder** [comment]
I know, documentation is hard, I really do. I just wish there were more demos, more explanation about what those kernels are, how each parameter affects the result, etc. I wish you good luck and energy to continue working on your amazing tool. Thanks.

**Comment by Andrew-web-coder** [comment]
FYI, I ended up not resizing and not sharping my images using this tool, because browsers do much better job. So I simply created large images and let browser to do the rest.

**Comment by suresh-borad** [comment]
@Albertbol use this kernel: `kernel: sharp.kernel.lanczos3`

**Comment by maor-benami** [comment]
I also experience the same issue.

Source image (retina screen capture with selenium): 
<img width="628" alt="image" src="https://user-images.githubusercontent.com/85426848/208803763-f6cc0a58-17f7-4b46-a5db-e4767c95535f.png">

After resizing:
<img width="311" alt="image" src="https://user-images.githubusercontent.com/85426848/208803898-09a7dd4e-abfe-4f8b-81b1-b175f170c670.png">

**Comment by imanpalsingh** [comment]
This helped me 

```
.convolve({
        width: 3,
        height: 3,
        kernel: [0.0, -0.125, 0.0, -0.125, 1.5, -0.125, 0.0, -0.125, 0.0],
      })
```

**Comment by duongdinh98** [comment]
Using kernel: sharp.kernel.lanczos3 seem looks good to me
