### ISSUE TITLE
resize and cache

### ISSUE THREAD

**Issue by Alexufo** [lovell/sharp#1984]
I using sharp for resizing images on the fly. And when I upload image with the same name sharp doesn't want  return new resized image. Sharp show me old image until I restart node server.

I suppose It is not a browser or server caching. On direct link to files i have not see a problem. Problem when I call resize url where sharp's endpoint

```
            const newPayload = await sharp(localurl)
                .resize({ width: width, height:height}).
                jpeg({ quality: (quality||40) }).toBuffer(); 
            reply
                .code(200)
                .type('image/jpeg')
                .send(newPayload)
```
How I should  use sharp in my case?

**Comment by lovell** [comment]
If the input files are mutable, use `sharp.cache(false)` to disable libvips' file cache.

https://sharp.pixelplumbing.com/en/stable/api-utility/#cache

**Comment by Alexufo** [comment]
YES! :-)
