### ISSUE TITLE
Error relocating /usr/lib/libheif.so.1: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found

### ISSUE THREAD

**Issue by zee-german** [lovell/sharp#1985]
We encountered this problem out of nowhere without any changes in the packages.

```
Something went wrong installing the "sharp" module

Error relocating /usr/lib/libheif.so.1: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
```

the packages that use sharp are
- gatsby-transformer-sharp
- gatsby-plugin-sharp

Tested Versions
Docker images are the official ones from docker hub (node:alpine)
- (Node) 12.13.1 and 10.17.0
- (sharp) 0.23.3 and 0.22.1

**Comment by lovell** [comment]
I notice you added then deleted a comment on #1979 so you'll already be aware this is unrelated to sharp.

It's likely there's been a C++ ABI change in the libheif package on Alpine.
