### ISSUE TITLE
Error: replicate: parameter across not set

### ISSUE THREAD

**Issue by gtzinos** [lovell/sharp#1987]
Hello,

I use the version `0.17.3` to generate watermarks. 

Code:

```
sharp(sourceFilePath).overlayWith(path_of_watermark_image, {gravity: 'centre',tile: true}).toFile(watermarkedImage_destinationPath, function (error, info) {
            if (error) {
                console.log(error)
            } else {
                // ...
            }
        });
```

It works great, but when it goes on production sometimes I get the error message `replicate: parameter across not set.`

I thought that maybe it has to do with the combination of pm2, I mean multiple instances, each instance has pm2 (4 servers) and all of them try to access the same image in a mounted disk. Could you please let me know if you fixed it in the next versions?

**Comment by lovell** [comment]
Please upgrade, there have been many improvements since v0.17.3 released in April 2017.

You'll need to use the `composite` operation:
https://sharp.pixelplumbing.com/en/stable/api-composite/
