### ISSUE TITLE
png and quality

### ISSUE THREAD

**Issue by Zewy** [lovell/sharp#199]
Every time I convert a jpg to a png it's 10x then the original file size.
What am I doing wrong here? tried even with quality(1) it is 10x the file size.
```
sharp('input.jpg').toFormat('png').pipe(response);

**Comment by lovell** [comment]
The [quality](https://github.com/lovell/sharp#qualityquality) option is for lossy JPEG, WebP and TIFF output formats.

For lossless PNG, try setting [compressionLevel](https://github.com/lovell/sharp#compressionlevelcompressionlevel) to its max value of 9 and, if using libvips >= 7.42.0, experiment using [withoutAdaptiveFiltering](https://github.com/lovell/sharp#withoutadaptivefiltering).

Photographs usually compress much better as JPEG compared with PNG, which is more suited to line art and diagrams.

**Comment by Mirobit** [comment]
@lovell I am sorry to bring back this old issue but I am confused if png supports a quality param or not.
According to the docs it does: https://sharp.pixelplumbing.com/en/stable/api-output/#png

But setting the quality doesn't change anything regarding the output file (10 or 100 => same file size)

**Comment by lovell** [comment]
@Mirobit Please note the "requires libvips compiled with support for libimagequant" part of the docs you've linked to. Please see also https://github.com/lovell/sharp/search?q=libimagequant&type=Issues and open a new issue if you're still having problems.
