### ISSUE TITLE
Sharp does'nt reread file in the loop.

### ISSUE THREAD

**Issue by UserHyuser** [lovell/sharp#1991]
In my script I take a screenshot from android device, then crop it by sharp and compare with standart. I do it in the loop with 2 sec interval. Screenshots correctly pull to computer BUT sharp module don't read a replaced screenshot file as a new file. It takes old version of screenshot which it process. (May be I don't correct with cause).
So this bug was fixed by me: I read file by fs.readFile as a buffer and then proccess it by sharp.

What are the steps to reproduce?
1. Crop an image for the first time
2. Replace input file to another with same name
3. Crop image again with replaced file (even if you save cropped image to a new file problem persist)

What is the actual behaviour?
Cropped screenshot doesn't change

What is the expected behaviour?
Cropped new screenshot

Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?

`setInterval(async function () {
	await sharp(content).extract({
			width: w,
			height: h,
			left: l,
			top: t,
			right: r
		})
			.png()
			.toBuffer(async (err, data, info) => {
				fs.writeFileSync(path + 'cropped' + originalImage, data, {flag: 'w'});
			})
}, 2000)
`

Problem was solved by addind this operation right before crop.
`let content = fs.readFileSync(path + originalImage);`

**Comment by UserHyuser** [comment]
Well I can't understand how to correctly input code to the form sorry...

**Comment by lovell** [comment]
If the input files are mutable, use `sharp.cache(false)` to disable libvips' file cache.

https://sharp.pixelplumbing.com/en/stable/api-utility/#cache

**Comment by UserHyuser** [comment]
Ok, thanks! That wasn't obvious for me :)
