### ISSUE TITLE
Issue(s) deploying to Firebase

### ISSUE THREAD

**Issue by SeanOThomas** [lovell/sharp#1992]
This might not be an issue with Sharp, but I'm wondering if perhaps this has come up before.  When deploying to Firebase, I get this mysterious error: 

> `Error: There was an unknown problem while trying to parse function triggers. Please ensure you are using Node.js v6 or greater.`

When I remove sharp from the file, the parsing issue goes away.  Any help on solving this?

**Comment by lovell** [comment]
Searching for that error in Google returns https://stackoverflow.com/questions/56675535/firebase-deploy-functions-with-sharp-library-fails-in-google-cloud-build

**Comment by jacoviza** [comment]
I'm having the same issue. Logs aren't that helpful.

```
npm verb lifecycle functions@~deploy: CWD: <MyProjectPath>\functions
npm info lifecycle functions@~deploy: Failed to exec deploy script
npm verb stack Error: functions@ deploy: `firebase deploy --only functions`
npm verb stack Exit status 2
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:210:5)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:210:5)
npm verb stack     at maybeClose (internal/child_process.js:1021:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
npm verb pkgid functions@
npm verb cwd <MyProjectPath>\functions
npm verb Windows_NT 10.0.17134
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "deploy" "--verbose"
npm verb node v12.13.0
npm verb npm  v6.12.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! functions@ deploy: `firebase deploy --only functions`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the functions@ deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 2, true ]
npm timing npm Completed in 14147ms
```

**Comment by lovell** [comment]
@jacoviza sharp always outputs as much information as it can at `npm install` time, especially if the `--verbose` flag is detected, so you'll need to speak with Google if their logs hide or mask that.

**Comment by jacoviza** [comment]
Thanks @lovell, this issue is gone now. I cleared node_modules and run npm install again. I really don't know what caused it, but since I made some dependency changes I thought something was just messed up in my node_modules. I wish I could have more helpful information for anybody else having this same issue.

**Comment by jousi592** [comment]
I have just started getting the same issue, i deleted everything multiple times and re-installed, still no luck 😞 @jacoviza

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required, or open a new issue if you are having a different problem.
