### ISSUE TITLE
optimize svg to png

### ISSUE THREAD

**Issue by vincentsijben** [lovell/sharp#1993]
I came across https://github.com/lovell/sharp and was wondering if it could speed up my hires png generation process.

Currently I use Chrome Puppeteer to generate a PNG that's 9933 x 14043 in dimensions.
That takes approx. 90 seconds. Its about 15MB in filesize.
Generating an SVG however takes only 20 seconds. The SVG file is 19MB in filesize.

I've played around with sharp and it costs an additional 30 seconds to convert the SVG to that hires PNG. And it's 60MB in filesize.

I've tried this example and played with density, but it doesn't speed up the process or make the filesize smaller.
`const imageSVG = await sharp('/opt/node_app/app/public/img/test.svg')
    .resize(9933, 14043)
		.toBuffer();
	fs.writeFile('/opt/node_app/app/public/img/test.png', imageSVG, err => {
		console.log(err);
  });`

Are there some default settings that work best out of the box (besides the basic example I've provided), or settings that would speed up process time/make the file quality good but smaller?

**Comment by lovell** [comment]
Please see #1866 for details of an improvement in the forthcoming libvips v8.9.0 to reduce the rendering times of large SVGs.

**Comment by vincentsijben** [comment]
ok great news! I'll look forward to version 0.24.0 (guess it will be build on top of libvips 8.9.0). thanks
