### ISSUE TITLE
Fontconfig cache busting

### ISSUE THREAD

**Issue by cthorner** [lovell/sharp#1997]
What are you trying to achieve?

Adding fonts after sharp has already created an image. Adding a font before first image is created works great. Not so much for subsequent images.
This is on linux.

Have you searched for similar questions?

Looks like most topics are related to just fonts loading once. #1162 discusses a different issue. I have checked pango, cairo for issues and looked at the source code for those although I can't make much sense out of it.

Are you able to provide a standalone code sample that demonstrates this question?

I have tried reloading sharp with 
```javascript
let sharp = require('sharp')
// add fonts to fonts folder, create image
delete sharp
 delete require.cache[require.resolve('sharp')]
sharp = require('sharp')
// add more fonts, make sure fonts were added with fs, create another image with new fonts results in fallback font being used
```

Also tried changing cache settings, having read somewhere that the cache would be lost in the process:
```javascript
sharp.cache(false)
sharp.cache(true)
```

Are you able to provide a sample image that helps explain the question?

**Comment by cthorner** [comment]
I should mention that I don't have fontconfig installed on the linux machine and it looks like the cache is being created by code leveraging libfontconfig in pango or cairo or something like that...

No fonts-cache directory is being created, which if I install fontconfig and run fc-cache against the fonts.conf file it is created. I haven't figured out how to install fontconfig in production and I don't even know if manually creating the fonts-cache directory would fix anything.

My guess is I need to reload libvips somehow. Is this possible?

**Comment by lovell** [comment]
Hello, if you require this level of control over fontconfig then you'll probably be better off compiling sharp against a globally-installed copy of libvips and its dependencies, including fontconfig (rather than use the pre-compiled binaries provided by sharp).

You can control aspects of fontconfig via environment variables - see https://www.freedesktop.org/software/fontconfig/fontconfig-user.html

The discussion at https://gitlab.freedesktop.org/fontconfig/fontconfig/issues/60 might be relevant too.

**Comment by cthorner** [comment]
Ok, thanks! I'll take a look at that issue.

I've been playing around with the variables. And the fonts-cache directory is actually created on first load of sharp. Unfortunately it looks like librsvg just loads a cached version of the font map and never revalidates if the cache is up to date. I've tried deleting the cache directory and the cache files, just to make sure, and it doesn't seem to matter. I'll report back if I can get it working.

**Comment by cthorner** [comment]
For future reference here is where librsvg grabs the font map:

https://github.com/GNOME/librsvg/blob/mainline/rsvg_internals/src/text.rs#L892

And it never tries to check if the cache is still valid later on.

**Comment by kleisauke** [comment]
You can try to manually rebuild the font cache when fonts are added to the system:
```bash
fc-cache -v
```

This ensures that you can immediately use the fonts everywhere.

**Comment by cthorner** [comment]
I think I tried that, but I'm loosing track of what I have tried. I don't have fc-cache installed on my production servers, so I know I haven't tried it there. I think the reason it doesn't work is because librsvg caches the results(through pangocairo) and doesn't check if the cache is updated. That will do the trick on an application restart, but not after the application is started.

**Comment by kleisauke** [comment]
Indeed, changes will only be visible in newly launched applications. You could try to use the [cluster module](https://nodejs.org/api/cluster.html) of Node.js to handle configuration changes with zero-downtime (`pm2` has [this built-in](https://pm2.keymetrics.io/docs/usage/cluster-mode/)).

This is being tracked upstream: https://gitlab.gnome.org/GNOME/librsvg/issues/536.

**Comment by lovell** [comment]
Thanks both, it looks like progress is being made on the upstream librsvg issue so let's track it there.
