### ISSUE TITLE
Custom Compiled libvips For HEIC

### ISSUE THREAD

**Issue by smcguinness** [lovell/sharp#2000]
Following the prior HEIF/HEIC issue https://github.com/lovell/sharp/issues/1105 regarding the need for a custom compiled libvips package I did so. 

I've used this docker file https://github.com/jcupitt/docker-builds/blob/master/libvips-amazonlinux2/Dockerfile except I'm using `lambci/lambda:build-nodejs10.x` as a base to have nodejs support.

Installation of libvips goes well and is successful. It finds libheif and references it in the supported formats during install. 

Where I'm running into an issue is that when I install sharp I'm missing reference to the libvip lib files. 

![image](https://user-images.githubusercontent.com/61205/70261947-057fa100-1759-11ea-838e-3716644163b6.png)

**Comment by smcguinness** [comment]
Following this comment about adding a reference to ldconf  https://github.com/lovell/sharp/issues/327#issuecomment-167094002 I'm able to now see all the references to the libraries I'm supported in the custom libvip build. 

![image](https://user-images.githubusercontent.com/61205/70267246-aa9f7700-1763-11ea-823d-c1132907ac53.png)

But following the install I no longer have a vendors directory in the sharp directory of node_modules. My understanding is that the vendor folder contains the binaries of the libraries for sharp to use.

**Comment by lovell** [comment]
The `sharp/vendor` folder is for prebuilt binaries, which won't be created/present when a globally-installed libvips is detected, as is the case here.

**Comment by smcguinness** [comment]
@lovell Oh. I was expecting to get the output into `sharp/vendor` and be able to copy that over for usage into a Lambda Layer. 

So, in the case of that not happening, I'm needing to move all of the required binaries (w/ mappings) to be used on the Lambda?

**Comment by lovell** [comment]
https://github.com/lovell/sharp/blob/master/binding.gyp#L160 ensures the compiled `build/Release/sharp.node` file always contains the `vendor/lib` location in its rpath so it might "just work" if you put other shared libraries in the same directory.

Another option might be setting `LD_LIBRARY_PATH` - good luck!

**Comment by lovell** [comment]
@smcguinness Were you able to make any progress with this?

**Comment by smcguinness** [comment]
@lovell I wasn't able to make it work by reference to that directory. It certainly may have been an issue with the binaries, or something else, but the process was long as it required deployments to test. I ultimately went down the path of a custom lambda layer to allow the references to exist on the server environment instead of within the vendor/lib directory. 

Having the ability to do that would be definitely ideal because we ultimately moved away from doing Lamda@Edge because of the need for the layer. If we could have placed the compiled libraries with the run of a docker (extending the AWS release steps), I think it would be a great win for be able to add additional formats as needed (including the possibility of selectively compiling).

I've been hoping to put it together in a repo as I had to piece together repos, issues, and comments on my way through it to get work (first time using layers).

**Comment by Projkt-James** [comment]
@smcguinness I'm trying to do something similar with self compiled binary of libvips for heif support. I also was unable to make it work by reference to binaries in the sharp directory. Do you have any suggested online resources for building a layer with the binaries?

**Comment by smcguinness** [comment]
@Projkt-James I'm sorry for the quick dump but I've got this up https://github.com/smcguinness/SharpLayer as a getting started. Ultimately, you should be able to run the 2 commands and be off an running - but I'm sure there are lots of enhancements, and maybe even bugs in the docker install.

Ultimately, I'd love to get to a point of these dumping to the Sharp directory to read from, but for now, this has worked for me.

**Comment by lovell** [comment]
Thanks for the updates, I'll close for now, feel free to re-open with more information if required.

**Comment by zoellner** [comment]
For anyone coming here looking for a lambda layer: I've created one that includes sharp with HEIC/HEIF support: https://github.com/zoellner/sharp-heic-lambda-layer
It can be added to any lambda function. See repo for details.
