### ISSUE TITLE
HEIC conversion

### ISSUE THREAD

**Issue by orkc** [lovell/sharp#2004]
What are you trying to achieve?

Convert range of image types including HEIC to JPEG.  After reading the historical trail I can find I am confused as to if Sharp can be used for converting HEIC to JPEG and if so then how to achieve that.  I think that the current situation is that the answer is yes for input and experimental for output but not with the standard install.  However, I do not understand the steps required to complete an installation that will support HEIC conversion.  Can anyone confirm my understanding and if accurate provide the correct steps?

**Comment by lovell** [comment]
At `npm install` time, sharp will always look for and, if found, compile itself again a globally-installed copy of libvips.

This means you'll need to compile and install libvips with support for libheif before installing sharp.

Please see https://github.com/lovell/sharp/issues/1105#issuecomment-516010573

**Comment by vdongbin** [comment]
> At `npm install` time, sharp will always look for and, if found, compile itself again a globally-installed copy of libvips.
> 
> This means you'll need to compile and install libvips with support for libheif before installing sharp.
> 
> Please see [#1105 (comment)](https://github.com/lovell/sharp/issues/1105#issuecomment-516010573)
I install vips (brew install vips)
(brew info vips) command --------
vips: stable 8.8.4 (bottled)
Image processing library
https://github.com/libvips/libvips
/usr/local/Cellar/vips/8.8.4 (166 files, 11.5MB) *
  Poured from bottle on 2019-12-13 at 14:10:10
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/vips.rb
==> Dependencies
Build: pkg-config ✔
Required: cfitsio ✔, fftw ✔, fontconfig ✔, gettext ✔, giflib ✔, glib ✔, imagemagick ✔, libexif ✔, libgsf ✔, libheif ✔, libmatio ✔, libpng ✔, librsvg ✔, libtiff ✔, little-cms2 ✔, mozjpeg ✔, openexr ✔, openslide ✔, orc ✔, pango ✔, poppler ✔, webp ✔
==> Analytics
install: 2,531 (30 days), 6,027 (90 days), 19,448 (365 days)
install-on-request: 2,403 (30 days), 5,774 (90 days), 18,362 (365 days)
build-error: 0 (30 days)

I install sharp in my local lambda function folder.
(npm install --no-cache --arch=x64 --platform=linux --target=10.15.0 sharp)
However it is not work (Error: Input buffer contains unsupported image format) , When Lambda was excuted.

How to compile globally-installed copy of libvips??

**Comment by lovell** [comment]
@vdongbin I notice you opened #2006 so let's continue your question there.

**Comment by orkc** [comment]
just in case it is helpful to others... With the pointer given by Lovell (thanks) I got things working by installing in the following order:

libheif
libvips
sharp

**Comment by josephfrazier** [comment]
Thanks for posting this @orkc, I just got it working!

```
brew install libheif
brew install libvips
yarn remove sharp && yarn add sharp
```

**Comment by studentIvan** [comment]
> Thanks for posting this @orkc, I just got it working!
> 
> ```
> brew install libheif
> brew install libvips
> yarn remove sharp && yarn add sharp
> ```

thanks, it works on my mac, but still doesn't work on the ubuntu server :(
looking for the solution

I've installed the libvips42, libvips-dev, libvips-tools, libheif and rebuilt sharp
