### ISSUE TITLE
how to use sharp and sharp-cli in a docker container environment

### ISSUE THREAD

**Issue by oupala** [lovell/sharp#2007]
I want to use sharp and sharp-cli as an npm module called with `npx`.

What I've done is:

```bash
docker run -it --rm tailor/docker-libvips:node-10.9 /bin/bash
npx sharp-cli
```

and the error is:

> internal/modules/cjs/loader.js:583
    throw err;
    ^
> 
> Error: Cannot find module '/root/.npm/_npx/6/lib/node_modules/sharp-cli/node_modules/sharp/install/libvips'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, stat '/root/.npm/_npx/6/lib/node_modules/sharp-cli/node_modules/sharp/.node-gyp/10.9.0'
gyp ERR! System Linux 4.9.0-9-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/.npm/_npx/6/lib/node_modules/sharp-cli/node_modules/sharp
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.23.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.23.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-14T00_09_09_733Z-debug.log
Install for sharp-cli@latest failed with code 1

`npx` seems to install sharp-cli, but then does not find it (`Cannot find module '/root/.npm/_npx/6/lib/node_modules/sharp-cli/node_modules/sharp/install/libvips'`). That's strange...

I also wonder why I should use a specific docker image (with libvips pre-installed) while the sharp documentation tells that libvips is automatically installed when sharp and sharp-cli are getting installed.

**Comment by lovell** [comment]
I notice you've cross-posted this at https://github.com/vseventer/sharp-cli/issues/30 and https://github.com/TailorBrands/docker-libvips/issues/4

This looks like a permissions problem; you're trying to use `npx` as `root` when it is designed for non-root users.

```
gyp ERR! stack Error: EACCES: permission denied, stat '/root/.npm/_npx/6/lib/node_modules/sharp-cli/node_modules/sharp/.node-gyp/10.9.0'
```

If you want to run `npx sharp-cli` inside a Docker container then I recommend you use a well-maintained and up-to-date image such as `node:12`, ensuring you use a non-root user.

```sh
$ docker run -it --rm -u node node:12 /bin/bash
```

/cc @vseventer

**Comment by oupala** [comment]
You're right, I cross-posted my question because my usecase is at the crossroads of several usecases: sharp-cli + npx + docker + gitlab CI, and I did not knew exactly where was the problem.

I tested your solution and it works well, so thank you for the tip. It makes me realize that the problem might come from GitLab CI.

My problem is that I'm using sharp-cli with GitLab CI, and I have no control over how the containers are launched.

I can't apply your tip to my CI/CD pipeline and I don't now how to optimize image automatically, using the GitLab CI pipeline. Any tip for this configuration?

**Comment by oupala** [comment]
It seems that docker container in GitLab CI are always started with the default user set in the Dockerfile (root user if none is defined). There is a [feature request](https://gitlab.com/gitlab-org/gitlab/issues/23046) in GitLab CI tracker, but it is still open. Some workarounds are proposed in the comment of the issue, but none of them are really satisfying.

The problem of the node image is that it is declaring a node user, but it is not using it by default. That is a very strange thing, isn't it?

As GitLab CI does not allow to set the user for the moment, it is very complicated to use `sharp` and `sharp-cli` into GitLab CI...

**Comment by lovell** [comment]
Good to hear you worked out the source of your problem.

If you have to cross-post, please update issues to include links to the other issues/discussions so volunteers and maintainers don't waste everyone's time asking the same questions.
