### ISSUE TITLE
How to create pdf to png thumbnail?

### ISSUE THREAD

**Issue by subhendukundu** [lovell/sharp#2008]
I am trying to convert a pdf to png file which is throwing an error of  `Error: Input buffer contains unsupported image format`. But same code works for png. What am I missing here? Is there a different method to call?
I was looking at https://sharp.pixelplumbing.com/en/stable/api-constructor/#parameters which says pdf is supported now. Right?

What am I doing wrong?
```
const pdfUrl = 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf';
const optionsStart = {
  uri: pdfUrl,
  method: 'GET',
  encoding: null,
  headers: {
    'Content-type': 'application/pdf'
  }
};
async function getpdf() {
  const body = await rp(optionsStart);
  sharp(body)
    .resize(320, 240)
    .toFile('output.png', (err, info) => { console.log(info); });
  const imgbuffer = await sharp(body, {
    pages: 1,
    page: 0
  }).png().toBuffer();
  console.log(imgbuffer);
}

getpdf();
```
https://repl.it/@subhendukundu/EsteemedWhichSyntax

Thanks for the help

**Comment by lovell** [comment]
You'll need to compile libvips from source, ensuring you've configured it with support for PDF by installing one of the dependencies it can use to parse these first.

https://libvips.github.io/libvips/install.html#building-libvips-from-a-source-tarball

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by jamiegalbreath** [comment]
In the docs it says you can use "page" to export a page of a pdf. This works for the first frame of a gif but not a pdf.
