### ISSUE TITLE
unable to open 16-bit, single-band tiff in node JS using sharp

### ISSUE THREAD

**Issue by benkoch12** [lovell/sharp#2009]
We are trying to use sharp to try and do some initial processing using lambda and node js when an image is uploaded to S3.  The function `image_file_uploaded` is triggered by an S3 event.  Here is the image.

![image](https://user-images.githubusercontent.com/27734794/70865688-dbcb3480-1f25-11ea-802f-330b6f616158.png)

When run, Sharp throws the error
`ERROR	[Error: Input buffer contains unsupported image format]`

I'm not sure what additional information/log outputs would be helpful.

```module.exports.image_file_uploaded = (event,context,callback) => {
  console.log(`received: ${JSON.stringify(event)}`)
  const bucketName = event.Records[0].s3.bucket.name
  const keyName = event.Records[0].s3.object.key
  const origFileName = path.basename(keyName)
  console.log(`bucket: ${bucketName}`)
  console.log(`key: ${keyName}`)
  var headParams = {
    Bucket: bucketName,
    Key: keyName
  }

  s3.headObject(headParams,function(err,imageMetadata){
    if (err) console.log(err, err.stack); // an error occurred
    if (imageMetadata.Metadata.flownrouteassetid === undefined){
      console.log("no Metadata from image. exiting")}
    else {
      console.log(JSON.stringify(imageMetadata));
      console.log(`flownRouteAssetID: ${imageMetadata.Metadata.flownrouteassetid}`)
      console.log(`flownRouteID: ${imageMetadata.Metadata.flownrouteid}`)
      const yaw = parseInt(imageMetadata.Metadata.imageyaw)
      console.log(`plane yaw ${yaw}`)
      var rotateYaw = Math.round(yaw/90)*90
      console.log(`rotating image ${rotateYaw} degrees`)
      console.log(sharp.format)

      var newKey = `root/flown-route/
        ${imageMetadata.Metadata.flownrouteid}/
        ${imageMetadata.Metadata.assettypeasstring}/
        ${imageMetadata.Metadata.flownrouteassetid}/
        ${imageMetadata.Metadata.datetimecaptured}/
        ${origFileName}`

      const paramsDownload = {
        Bucket: bucketName,
        ResponseContentType: 'image/tiff',
        Key: keyName
      };

      s3.getObject(paramsDownload).promise()
      .then(data => sharp(data.Body)
      .rotate(rotateYaw)
      .toBuffer()
      )
      .then(buffer => s3.putObject({
        Body: buffer,
        Bucket: bucketName,
        ContentType: 'image/tiff',
        Key: newKey,
      }).promise()
      )
      .catch(err => {
        if(err.code === "NoSuchKey") err.message = "Image not found.";
        console.error(err)
      })
    }
  });
}

**Comment by lovell** [comment]
Are you able to reproduce this problem with this file locally, without all the S3 logic?

**Comment by benkoch12** [comment]
@lovell I not familiar with a good way to test this locally.  sharp-cli?

**Comment by lovell** [comment]
How do you currently (unit) test this logic without Lambda and/or S3?

Perhaps set `bucketName` and `keyName` to known values and attempt to run this logic on a local machine and not in the Lambda environment.

(This might be turning into a how-to-debug-AWS-services question, for which a site such as StackOverflow could be more appropriate.)

**Comment by benkoch12** [comment]
@lovell after some digging, it appears that the AWS sdk is adding some headers with `getObject`.  The original tiff has your standard `II*` where the buffer I'm getting from `getObject` is ```--c011e21d2ff5b66dece073c0f0a9dc5e836d03d77a71e2e2d137884030e3
Content-Disposition: form-data; name="file"; filename="img_00004.tiff"
Content-Type: application/octet-stream

II*```
