### ISSUE TITLE
/lib64/libz.so.1: version `ZLIB_1.2.9' not found

### ISSUE THREAD

**Issue by peter-snr** [lovell/sharp#2010]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/en/stable/install/)? Yes

Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime? Yes

If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag? No

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages? Yes ouput below.

peter@vulcan$ npm install --verbose sharp
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node',
npm verb cli   '/usr/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sharp' ]
npm info using npm@5.6.0
npm info using node@v9.11.2
npm verb npm-session cbdde56657455b1c
npm http fetch GET 304 https://registry.npmjs.org/sharp 191ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 100ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/fs-copy-file-sync 101ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color 111ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/prebuild-install 187ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/nan 189ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/npmlog 190ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/semver 202ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-get 207ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar 214ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/gauge 43ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/are-we-there-yet 50ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/console-control-strings 51ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/delegates 2ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/aproba 52ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/string-width 52ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/wide-align 53ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/has-unicode 57ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-fullwidth-code-point 42ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/github-from-package 50ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/napi-build-utils 60ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/noop-logger 61ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minimist 63ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/expand-template 66ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/pump 64ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-fs 125ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/which-pm-runs 155ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-abi 321ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-concat 48ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 53ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mimic-response 37ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-stream 41ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/chownr 48ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-constants 38ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bl 56ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/readable-stream 58ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-minipass 46ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/yallist 47ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minipass 49ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minizlib 52ms (from cache)
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm verb correctMkdir /home/peter/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/peter/.npm/_locks/staging-d09b69e385f28f0d.lock for /home/peter/git/Prism360IS/node_modules/.staging
npm info lifecycle sharp@0.22.1~preuninstall: sharp@0.22.1
npm info lifecycle sharp@0.22.1~uninstall: sharp@0.22.1
npm verb unbuild rmStuff sharp@0.22.1 from /home/peter/git/Prism360IS/node_modules
npm info lifecycle sharp@0.22.1~postuninstall: sharp@0.22.1
npm info lifecycle sharp@0.22.1~preinstall: sharp@0.22.1
npm info linkStuff sharp@0.22.1
npm verb linkBins sharp@0.22.1
npm verb linkMans sharp@0.22.1
npm info lifecycle sharp@0.22.1~install: sharp@0.22.1
info sharp Using cached /home/peter/.npm/_libvips/libvips-8.7.4-linux-x64.tar.gz
prebuild-install info begin Prebuild-install version 5.3.3
prebuild-install info looking for cached prebuild @ /home/peter/.npm/_prebuilds/642c61-sharp-v0.22.1-node-v59-linux-x64.tar.gz
prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.22.1/sharp-v0.22.1-node-v59-linux-x64.tar.gz
prebuild-install http 404 https://github.com/lovell/sharp/releases/download/v0.22.1/sharp-v0.22.1-node-v59-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=9.11.2 runtime=node arch=x64 libc= platform=linux)
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.11.2 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.5\n"
gyp verb get node dir no --target version specified, falling back to host node version: 9.11.2
gyp verb command install [ '9.11.2' ]
gyp verb install input version string "9.11.2"
gyp verb install installing version: 9.11.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 9.11.2
gyp verb build dir attempting to create "build" dir: /home/peter/git/Prism360IS/node_modules/sharp/build
gyp verb build dir "build" dir needed to be created? /home/peter/git/Prism360IS/node_modules/sharp/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/peter/git/Prism360IS/node_modules/sharp/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/peter/git/Prism360IS/node_modules/sharp/config.gypi
gyp verb common.gypi checking for gypi file: /home/peter/git/Prism360IS/node_modules/sharp/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/peter/git/Prism360IS/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/peter/.node-gyp/9.11.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/peter/.node-gyp/9.11.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/peter/.node-gyp/9.11.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/peter/git/Prism360IS/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/peter/.node-gyp/9.11.2
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/peter/git/Prism360IS/node_modules/sharp/build'
  touch Release/obj.target/libvips-cpp.stamp
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/peter/.node-gyp/9.11.2/include/node -I/home/peter/.node-gyp/9.11.2/src -I/home/peter/.node-gyp/9.11.2/deps/uv/include -I/home/peter/.node-gyp/9.11.2/deps/v8/include -I../node_modules/nan -I../vendor/include -I../vendor/include/glib-2.0 -I../vendor/lib/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-deprecated-declarations -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/common.o.d.raw   -c -o Release/obj.target/sharp/src/common.o ../src/common.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/peter/.node-gyp/9.11.2/include/node -I/home/peter/.node-gyp/9.11.2/src -I/home/peter/.node-gyp/9.11.2/deps/uv/include -I/home/peter/.node-gyp/9.11.2/deps/v8/include -I../node_modules/nan -I../vendor/include -I../vendor/include/glib-2.0 -I../vendor/lib/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-deprecated-declarations -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/metadata.o.d.raw   -c -o Release/obj.target/sharp/src/metadata.o ../src/metadata.cc
ION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/peter/.node-gyp/9.11.2/include/node -I/home/peter/.node-gyp/9.11.2/src -I/home/peter/.node-gyp/9.11.2/deps/uv/include -I/home/peter/.node-gyp/9.11.2/deps/v8/include -I../node_modules/nan -I../vendor/include -I../vendor/include/glib-2.0 -I../vendor/lib/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-deprecated-declarations -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/stats.o.d.raw   -c -o Release/obj.target/sharp/src/stats.o ../src/stats.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/peter/.node-gyp/9.11.2/include/node -I/home/peter/.node-gyp/9.11.2/src -I/home/peter/.node-gyp/9.11.2/deps/uv/include -I/home/peter/.node-gyp/9.11.2/deps/v8/include -I../node_modules/nan -I../vendor/include -I../vendor/include/glib-2.0 -I../vendor/lib/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-deprecated-declarations -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/operations.o.d.raw   -c -o Release/obj.target/sharp/src/operations.o ../src/operations.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/peter/.node-gyp/9.11.2/include/node -I/home/peter/.node-gyp/9.11.2/src -I/home/peter/.node-gyp/9.11.2/deps/uv/include -I/home/peter/.node-gyp/9.11.2/deps/v8/include -I../node_modules/nan -I../vendor/include -I../vendor/include/glib-2.0 -I../vendor/lib/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-deprecated-declarations -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/pipeline.o.d.raw   -c -o Release/obj.target/sharp/src/pipeline.o ../src/pipeline.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/peter/.node-gyp/9.11.2/include/node -I/home/peter/.node-gyp/9.11.2/src -I/home/peter/.node-gyp/9.11.2/deps/uv/include -I/home/peter/.node-gyp/9.11.2/deps/v8/include -I../node_modules/nan -I../vendor/include -I../vendor/include/glib-2.0 -I../vendor/lib/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-deprecated-declarations -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/sharp.o.d.raw   -c -o Release/obj.target/sharp/src/sharp.o ../src/sharp.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/peter/.node-gyp/9.11.2/include/node -I/home/peter/.node-gyp/9.11.2/src -I/home/peter/.node-gyp/9.11.2/deps/uv/include -I/home/peter/.node-gyp/9.11.2/deps/v8/include -I../node_modules/nan -I../vendor/include -I../vendor/include/glib-2.0 -I../vendor/lib/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-deprecated-declarations -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/utilities.o.d.raw   -c -o Release/obj.target/sharp/src/utilities.o ../src/utilities.cc
  g++ -shared -pthread -rdynamic -m64  -Wl,-soname=sharp.node -o Release/obj.target/sharp.node -Wl,--start-group Release/obj.target/sharp/src/common.o Release/obj.target/sharp/src/metadata.o Release/obj.target/sharp/src/stats.o Release/obj.target/sharp/src/operations.o Release/obj.target/sharp/src/pipeline.o Release/obj.target/sharp/src/sharp.o Release/obj.target/sharp/src/utilities.o -Wl,--end-group ../vendor/lib/libvips-cpp.so ../vendor/lib/libvips.so ../vendor/lib/libglib-2.0.so ../vendor/lib/libgobject-2.0.so ../vendor/lib/libcairo.so ../vendor/lib/libcroco-0.6.so ../vendor/lib/libexif.so ../vendor/lib/libexpat.so ../vendor/lib/libffi.so ../vendor/lib/libfontconfig.so ../vendor/lib/libfreetype.so ../vendor/lib/libfribidi.so ../vendor/lib/libgdk_pixbuf-2.0.so ../vendor/lib/libgif.so ../vendor/lib/libgio-2.0.so ../vendor/lib/libgmodule-2.0.so ../vendor/lib/libgsf-1.so ../vendor/lib/libgthread-2.0.so ../vendor/lib/libharfbuzz.so ../vendor/lib/libjpeg.so ../vendor/lib/liblcms2.so ../vendor/lib/liborc-0.4.so ../vendor/lib/libpango-1.0.so ../vendor/lib/libpangocairo-1.0.so ../vendor/lib/libpangoft2-1.0.so ../vendor/lib/libpixman-1.so ../vendor/lib/libpng.so ../vendor/lib/librsvg-2.so ../vendor/lib/libtiff.so ../vendor/lib/libwebp.so ../vendor/lib/libwebpdemux.so ../vendor/lib/libwebpmux.so ../vendor/lib/libxml2.so ../vendor/lib/libz.so -Wl,--disable-new-dtags -Wl,-rpath='${ORIGIN}/../../vendor/lib'
  rm -rf "Release/sharp.node" && cp -af "Release/obj.target/sharp.node" "Release/sharp.node"
make: Leaving directory `/home/peter/git/Prism360IS/node_modules/sharp/build'
gyp info ok
npm verb lifecycle sharp@0.22.1~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.22.1~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/peter/git/Prism360IS/node_modules/sharp/node_modules/.bin:/home/peter/git/Prism360IS/node_modules/.bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/peter/.npm-global/bin:/home/peter/.local/bin:/home/peter/bin:/bin:JRE_HOME/jre/bin:/opt/gradle/gradle-5.6.2/bin:/home/peter/.local/bin:/home/peter/bin
npm verb lifecycle sharp@0.22.1~install: CWD: /home/peter/git/Prism360IS/node_modules/sharp
npm info lifecycle sharp@0.22.1~postinstall: sharp@0.22.1
npm verb unlock done using /home/peter/.npm/_locks/staging-d09b69e385f28f0d.lock for /home/peter/git/Prism360IS/node_modules/.staging
npm verb saving [ { name: 'sharp', spec: '^0.22.1', save: 'dependencies' } ]
npm verb shrinkwrap skipping write for package.json because there were no changes.
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm verb shrinkwrap skipping write for package-lock.json because there were no changes.
npm info lifecycle undefined~postshrinkwrap: undefined
npm WARN prism360is@1.0.0 license should be a valid SPDX license expression
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

+ sharp@0.22.1
updated 1 package in 24.463s
npm verb exit [ 0, true ]
npm info ok

> sharp@0.22.1 install /home/peter/git/Prism360IS/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /home/peter/.npm/_libvips/libvips-8.7.4-linux-x64.tar.gz
prebuild-install info begin Prebuild-install version 5.3.3
prebuild-install info looking for cached prebuild @ /home/peter/.npm/_prebuilds/642c61-sharp-v0.22.1-node-v59-linux-x64.tar.gz
prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.22.1/sharp-v0.22.1-node-v59-linux-x64.tar.gz
prebuild-install http 404 https://github.com/lovell/sharp/releases/download/v0.22.1/sharp-v0.22.1-node-v59-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=9.11.2 runtime=node arch=x64 libc= platform=linux)
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.11.2 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.5\n"
gyp verb get node dir no --target version specified, falling back to host node version: 9.11.2
gyp verb command install [ '9.11.2' ]
gyp verb install input version string "9.11.2"
gyp verb install installing version: 9.11.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 9.11.2
gyp verb build dir attempting to create "build" dir: /home/peter/git/Prism360IS/node_modules/sharp/build

What is the output of running `npx envinfo --binaries --languages --system --utilities`?

npx envinfo --binaries --languages --system --utilities
npx: installed 1 in 1.737s

  System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
    CPU: (4) x64 Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz
    Memory: 1.46 GB / 7.55 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 9.11.2 - /usr/bin/node
    npm: 6.10.2 - ~/git/Prism360IS/node_modules/.bin/npm
  Utilities:
    Make: 3.82 - /usr/bin/make
    GCC: 4.8.5 - /usr/bin/gcc
    Git: 1.8.3.1 - /usr/bin/git
    Subversion: 1.7.14 - /usr/bin/svn
  Languages:
    Bash: 4.2.46 - /usr/bin/bash
    Perl: 5.16.3 - /usr/bin/perl
    PHP: 7.1.33 - /usr/bin/php
    Python: 2.7.5 - /usr/bin/python
    Python3: 3.6.8 - /usr/bin/python3

Something went wrong installing the "sharp" module

/lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /home/peter/git/Prism360IS/node_modules/sharp/build/Release/../../vendor/lib/libpng16.so.16)

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/1428#issuecomment-432558430 for 3 possible reasons.

Node.js 9 reached EOL in June 2018 - please upgrade - https://github.com/nodejs/Release#end-of-life-releases

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
