### ISSUE TITLE
Output colour is corrupted where input is 16-bit, 2-channel PNG with embedded ICC colour profile

### ISSUE THREAD

**Issue by janaagaard75** [lovell/sharp#2013]
### What is the output of running `npx envinfo --binaries --languages --system --utilities`?

```
  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 2.37 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.21.0 - /usr/bin/git
    Clang: 1100.0.33.8 - /usr/bin/clang
    Subversion: 1.10.4 - /usr/bin/svn
    FFmpeg: 4.2.1 - /usr/local/bin/ffmpeg
  Languages:
    Bash: 3.2.57 - /bin/bash
    Go: 1.13.3 - /usr/local/bin/go
    Java: 11.0.2 - /usr/bin/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.3.9 - /usr/bin/php
    Python: 3.7.4 - /usr/local/opt/python/libexec/bin/python
    Python3: 3.7.4 - /usr/local/bin/python3
    Ruby: 2.6.5 - /usr/local/opt/ruby/bin/ruby
```

### What are the steps to reproduce?

Run this script, using [this image](https://github.com/janaagaard75/desert-walk/blob/master/assets/50713-transparent.png) as input source. The image is a png with some fully transparent pixels and some that are almost transparent.

```javascript
const sharp = require('sharp');
sharp('./input.png').toFile('./output.png');
```

### What is the expected behaviour?

✅ Expected: I would expect that the output image is nearly indistinguishable from the input image.
🔴 Actual: The semi-transparent parts of the image become opaque.

### Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?

No.

### Are you able to provide a sample image that helps explain the problem?

Yes: <https://github.com/janaagaard75/desert-walk/blob/master/assets/50713-transparent.png>.

### Related issues

I started with an issue on `expo-cli`, <https://github.com/expo/expo-cli/issues/1373>, that spawned another on `sharp-cli`, <https://github.com/vseventer/sharp-cli/issues/31>, and now this one.

**Comment by lovell** [comment]
Hi, thanks for reporting, I can reproduce this using the sample image. This problem appears to affect 16-bit, 2-channel (greyscale+alpha) PNG images that contain an ICC colour profile.

As well as fix this, I'd like to add a test case to sharp to prevent it occurring again. Are you able to give permission to add this sample image to the sharp code base as a test fixture? (I note the repo it is from is MIT, but open source licenses don't always apply to images.)

**Comment by janaagaard75** [comment]
I had to look into this, and here's my conclusion: I think you can use this image, but only if you attribute where you have it from and link to the [Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license](https://creativecommons.org/licenses/by-sa/3.0/).

My image is based on <http://www.colourlovers.com/pattern/50713/pat>, at that image has a [Attribution-ShareAlike 3.0 Unported](https://creativecommons.org/licenses/by-sa/3.0/) license. My changes must then also follow this license. I've updated my readme, so that it links to the original and includes a link to the CC BY-SA 3.0 license.

Marking my repo as MIT is apparently not accurate, so good catch. And sorry. 😞

**Comment by lovell** [comment]
Thank you, commit 755a0ca fixes this and adds a test that would have caught it. This will be in v0.23.5 (or maybe v0.24.0 if that happens sooner).

**Comment by lovell** [comment]
v0.24.0 is now available.
