### ISSUE TITLE
sync sharp(inputBuffer).toBuffer()

### ISSUE THREAD

**Issue by TChengZ** [lovell/sharp#2017]
i want to know is there any way i can got the buffer of png in sync way?

**Comment by lovell** [comment]
`toBuffer()` returns a Promise so you can use something like:
```javascript
const outputBuffer = await sharp(inputBuffer).toBuffer();
```

**Comment by TChengZ** [comment]
> `toBuffer()` returns a Promise so you can use something like:
> 
> ```js
> const outputBuffer = await sharp(inputBuffer).toBuffer();
> ```

i don‘t need a promise, i just want to use it in sync way, is there a  way to do this?

**Comment by lovell** [comment]
Ah, that's a general Node.js programming question more suited to a site such as StackOverflow e.g. https://stackoverflow.com/questions/16586640/node-js-async-to-sync

**Comment by TChengZ** [comment]
> Ah, that's a general Node.js programming question more suited to a site such as StackOverflow e.g. https://stackoverflow.com/questions/16586640/node-js-async-to-sync

thanks a lot, it real help me .
