### ISSUE TITLE
Cannot find module 'nan'

### ISSUE THREAD

**Issue by thelonious** [lovell/sharp#202]
I'm trying to install sharp 0.10.0 for node 0.10.33 and I'm seeing the following error:

```
> sharp@0.10.0 install /Users/kevin/Documents/.../node_modules/sharp
> node-gyp rebuild

-
module.js:340
    throw err;
          ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3
gyp: Call to 'node -e "require('nan')"' returned exit status 8. while trying to load binding.gyp
```

I just updated to Xcode 6.3.1 and I'm thinking that is related.

FWIW, we ran into an issue with nan today in another module. That appeared to be related to https://github.com/iojs/nan/pull/318 and was fixed by referencing `"nan": "git+https://github.com/iojs/nan#155f1d31352d08a3ec9ac206383a670f25428ab7"` for now. I'm not sure if that is related to this issue, but I'm passing it on in case it is.

**Comment by jgillman** [comment]
:+1: I thought I was going crazy since "nothing changed" on my local machine. "Nothing" being some system updates which likely included Xcode stuff. :sweat_smile:

**Comment by thelonious** [comment]
This looks closer: https://github.com/iojs/nan/issues/320

**Comment by lovell** [comment]
Yes, it looks like today's nan release is missing a file, possibly related to https://github.com/npm/npm/issues/5082.

Let me know if the nan update (v1.8.2?) doesn't solve it.

**Comment by thelonious** [comment]
`nan` has been republished version `1.8.2` and sharp is building fine. I'll go ahead and close this.
