### ISSUE TITLE
How to apply resize AFTER rotate

### ISSUE THREAD

**Issue by adityapatadia** [lovell/sharp#2021]
What are you trying to achieve?
I am trying to resize image after rotate. For example, if an image is `100px` width and `50px` height, if I rotate it by 90 degree, height becomes 100px and width becomes 50px.

Now, if I pass `input.rotate(90).resize({width: 50, fit: 'inside'})`, I expect the output image to be of 50 pixel width and 100 pixel height but I get 25 pixel width and 50 pixel height image.

Question is how to change order or rotate and resize operations?

**Comment by lovell** [comment]
Hi, you'll need to separate this into two pipelines, see also #1922 for a similar question.

**Comment by adityapatadia** [comment]
Okay, that is already done. I thought it would be good if there was a way to do it in single pipeline.
