### ISSUE TITLE
Photoshop Auto Color

### ISSUE THREAD

**Issue by groboter** [lovell/sharp#2022]
I would like to automatically optimize the color of images at channel level, like in Photoshop using the _Auto Color_ function (possibly also _Auto Contrast_).

I tried it under sharp using `normalize` but the image is then optimized based on the luminance of all color channels, I need optimization at channel level (R, G, B separately).

Thanks for any help.

**Comment by lovell** [comment]
Hi, did you see #1066, which may provide something similar?

**Comment by groboter** [comment]
Thanks lovell for your tip but I could not use it. I asked this questions also on [stackoverflow ](https://stackoverflow.com/questions/59666277/remove-color-cast-using-libvips) and get good feedback from jcupitt.
