### ISSUE TITLE
Error: Input file contains unsupported image format with as-yet-unreleased libvips 8.9.0 and png

### ISSUE THREAD

**Issue by faradaytrs** [lovell/sharp#2023]
What is the output of running `npx envinfo --binaries --languages --system --utilities`?
  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (2) x64 Virtual CPU 82d9ed4018dd
    Memory: 363.41 MB / 3.84 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 13.5.0 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.13.4 - /usr/bin/npm
  Utilities:
    Make: 4.2.1 - /usr/bin/make
    GCC: 9.2.1 - /usr/bin/gcc
    Git: 2.20.1 - /usr/bin/git
  Languages:
    Bash: 5.0.3 - /bin/bash
    Go: 1.13.5 - /snap/bin/go
    Perl: 5.28.1 - /usr/bin/perl
    PHP: 7.4.1 - /usr/bin/php
    Python: 2.7.17 - /usr/bin/python
    Python3: 3.7.5 - /usr/bin/python3
What are the steps to reproduce?
I use sharp 0.23.4 with custom compiled libvips 8.9.0, because I need to use heic (which works)
What is the expected behaviour?
Successful encoding of png images.
Jpeg, tiff and webp work completely fine, so i find this problem very strange.
sharp.format.png gives {
  id: 'png',
  input: { file: true, buffer: true, stream: true },
  output: { file: true, buffer: true, stream: true }
}
sharp.versions returns { vips: '8.9.0' }
Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?
Even await sharp(input).metadata() fails.
Are you able to provide a sample image that helps explain the problem?
Any png image

File is loaded from disk with fs.readFile

**Comment by lovell** [comment]
libvips v8.9.0 is not released yet and contains a couple of breaking changes around file loaders. If you'd like to help test it with sharp then you can use the [wit](https://github.com/lovell/sharp/tree/wit) branch.

Please don't use any of this in production systems until after libvips v8.9.0 and sharp v0.24.0 have been released - there are still potential changes and (lack of) testing to address.

**Comment by faradaytrs** [comment]
Okay so should i use 8.8.4 instead?

**Comment by faradaytrs** [comment]
8.8.4 doesn't work as well
