### ISSUE TITLE
Composite input array as sharp objects

### ISSUE THREAD

**Issue by stefanak-michal** [lovell/sharp#2025]
Hi.

I want to use composite function, but I want to provide sharp objects instead of string (path)/buffer. The purpose is to boost speed for price of memory usage. Keeping sharp instances in memory whole time.

```js
let img1 = sharp('1.png')
let img2 = sharp('2.png')

sharp('blank.png')
  .composite([
    { input: img1, left: 10, top: 10 },
    { input: img2, left: 50, top: 50 }
  ])
  .toFile('output.png')
  .then(() => { console.log('done'); })
  .catch(err => { console.error(err); })
```

**Comment by lovell** [comment]
libvips (and therefore sharp) decompresses pixel data on-demand so I'm unsure of the usefulness of this - all it would probably end up doing is taking a reference to the same input.

If RAM isn't a problem then I'd just use Buffer objects for this purpose as this is usually, but not always, faster than disk IO.

If you're compositing one or more of the same images repeatedly then use of filesystem paths can take greater advantage of libvips' operation cache so might be faster.

Perhaps you could create a performance test using the existing approaches to help you determine if your scenario is IO or CPU bound.

**Comment by stefanak-michal** [comment]
I tried buffer as a first thing. It didn't improve my speed, because he is also creating sharp instance and loading buffer into it, that means copying data from memory to memory. If using buffer will use reference instead, it will be great.

I'll take a look if it's possible to make a performance test.

**Comment by lovell** [comment]
@stefanak-michal Were you able to make any progress with this?

**Comment by stefanak-michal** [comment]
> @stefanak-michal Were you able to make any progress with this?

No. I picked up another approach. I hold pictures as buffers in memory and for putting them together I'm using canvas. It's fastest solution from all options I've tried.
