### ISSUE TITLE
preinstall.sh fails on Debian Jessie (was: Debian Jessie build errors?)

### ISSUE THREAD

**Issue by bshack** [lovell/sharp#203]
Debian Jessie is out and when I did a build on it with sharp I noticed these errors:

----

> sharp@0.9.3 install /root/deploy/node_modules/sharp
> node-gyp rebuild

Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
gyp: Call to 'PKG_CONFIG_PATH=":$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --libs vips' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/deploy/node_modules/sharp
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

**Comment by bshack** [comment]
would it make any difference if I installed 'libvips' or 'libvips-dev' via apt before I run this:

curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | bash -;

Thanks!

**Comment by bshack** [comment]
i get this error when it is doing the check before compile:

configure: error: Package requirements (glib-2.0 >= 2.6 gmodule-2.0 libxml-2.0 gobject-2.0) were not met:

No package 'glib-2.0' found
No package 'gmodule-2.0' found
No package 'libxml-2.0' found
No package 'gobject-2.0' found

The work around I have found is to install 'libvips-dev' before running the preinstall script, that does the trick.

**Comment by lovell** [comment]
Thanks for the report @bshack.

Manually running `apt-get install libvips-dev libgsf-1-dev` will install everything you need without the preinstall.sh script on Debian 8. (Debian 9/Sid ensures libgsf-1-dev is a dependency of libvips-dev via https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=780750 )

@mvictoras Should the `if [ $enable_openslide -eq 1 ]` test you introduced [here](https://github.com/lovell/sharp/blob/master/preinstall.sh#L252) in commit 2d1e6f2 use `-eq 0` instead? Debian 8 can use the pre-packaged libvips-dev v7.40.6 available via apt if Openslide is not required.

**Comment by bshack** [comment]
yep that worked, thanks!

**Comment by mvictoras** [comment]
@lovell looks like you are right. The if clause is reverted. Looks like I did the same mistake for Fedora as well.

**Comment by lovell** [comment]
Thanks for confirming @mvictoras, your Fedora conditional looks correct to me. I'll reverse the if and else sections of the Debian 8 conditional to ensure a consistent use of `if [ $enable_openslide -eq 1 ]` throughout.

**Comment by lovell** [comment]
Commit 783826a should fix the preinstall script for the latest Debian 8 and Ubuntu 15.04 releases.

@bshack Are you able to retest?

**Comment by bshack** [comment]
I appears to be working, I no longer get the configure: error message.

thanks for the quick fix!

**Comment by lovell** [comment]
Great, thanks for confirming.
