### ISSUE TITLE
Access Libvips failure/warnings with failOnError flagged false

### ISSUE THREAD

**Issue by Projkt-James** [lovell/sharp#2032]
**What are you trying to achieve?**
Log/report libvips warnings when failOnError is flagged false.

**Have you searched for similar feature requests?**
Yes

**What would you expect the API to look like?**
Unsure

**What alternatives have you considered?**
Work around is to spawn sharp instance with failOnError flagged true, record any error message and then to try reprocess with failOnError flagged false.

**Is there a sample image that helps explain?**
I can provide if required.

**Comment by lovell** [comment]
The standard `NODE_DEBUG` environment variable is supported - ensure it includes the value `sharp`

https://nodejs.org/dist/latest/docs/api/util.html#util_util_debuglog_section

**Comment by Projkt-James** [comment]
Hi @lovell thank you for the quick response, unfortunately I'm writing results to a message queue and will require the error message within the process (Doesn't seem NODE_DEBUG would support this). Is it possible to please change this back to an enhancement, adding a list errors/warnings flag to the toBuffer() method similar to the resolveWithObject is probably the most viable option here.

**Comment by lovell** [comment]
Perhaps you could intercept these via `process.stderr.on('data', msg => { ... })`?

**Comment by lovell** [comment]
A sharp instance is already an `EventEmitter` so perhaps it could also emit "warning" events, which would allow the following:
```javascript
// Proposed API, not yet available
const instance = sharp();
instance.on("warning", msg => { ... });
```
This approach is independent of the method of input and output, so would support Buffer, Stream and filesystem, whilst allowing a consumer to tie a warning to the input instance that generated it.

**Comment by Projkt-James** [comment]
The EventEmitter design pattern would work perfectly and would tie back much more nicely with your previous work on the queue change event. Would love to assist with a PR in anyway possible, however I'm a novice C programmer at best. From quick dig around the code I take it these warning events would emit in the while block when you push the message to debuglog.

**Comment by lovell** [comment]
Commit 1998019 adds the `warning` event - this will be in v0.25.4.

**Comment by lovell** [comment]
v0.25.4 now available, thank you for suggesting this improvement.
