### ISSUE TITLE
Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by peterayeniofficial** [lovell/sharp#2034]
vt git:(master) ✗ gatsby develop
warn Node.js v8.16.1 has reached End of Life status on 31 December, 2019.
Gatsby will only actively support 10.13.0 or higher and drop support for Node 8
soon.
success open and validate gatsby-configs - 0.105 s

 ERROR

Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues

⠋ load plugins
-------------------

Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/en/stable/install/)?

Yes

Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime?

yes

If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

yes

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

vt git:(master) ✗ npm install --verbose sharp
npm info it worked if it ends with ok
npm verb cli [ '/Users/peterayeni/.nvm/versions/node/v8.16.1/bin/node',
npm verb cli   '/Users/peterayeni/.nvm/versions/node/v8.16.1/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sharp' ]
npm info using npm@6.4.1
npm info using node@v8.16.1
npm verb npm-session 992dd9a95f6d200d
npm http fetch GET 304 https://registry.npmjs.org/sharp 124ms (from cache)
npm timing stage:loadCurrentTree Completed in 6827ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 51ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 4298ms
npm http fetch GET 304 https://registry.npmjs.org/npmlog 52ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/detect-libc 95ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar 92ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/prebuild-install 93ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-get 109ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/semver 116ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/gauge 40ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/string-width 48ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/expand-template 48ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/napi-build-utils 47ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/which-pm-runs 48ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-abi 51ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-fs 54ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 41ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-concat 40ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mimic-response 30ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-stream 29ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/readable-stream 36ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minipass 129ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minizlib 134ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/yallist 133ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-minipass 135ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 12858ms
npm timing stage:loadIdealTree Completed in 20304ms
npm timing stage:generateActionsToTake Completed in 403ms
npm verb correctMkdir /Users/peterayeni/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/peterayeni/.npm/_locks/staging-9ec48310b3434d54.lock for /Users/peterayeni/Desktop/vt/node_modules/.staging
npm timing audit compress Completed in 61ms
npm info audit Submitting payload of 241243bytes
npm timing action:extract Completed in 342ms
npm info lifecycle sharp@0.23.4~preuninstall: sharp@0.23.4
npm info lifecycle sharp@0.23.4~uninstall: sharp@0.23.4
npm verb unbuild rmStuff sharp@0.23.4 from /Users/peterayeni/Desktop/vt/node_modules
npm info lifecycle sharp@0.23.4~postuninstall: sharp@0.23.4
npm timing action:unbuild Completed in 5ms
npm timing action:remove Completed in 18ms
npm timing action:finalize Completed in 8ms
npm timing action:refresh-package-json Completed in 12ms
npm info lifecycle sharp@0.23.4~preinstall: sharp@0.23.4
npm timing action:preinstall Completed in 0ms
npm info linkStuff sharp@0.23.4
npm timing action:build Completed in 1ms
npm info lifecycle sharp@0.23.4~install: sharp@0.23.4
npm info lifecycle sharp@0.23.4~install: ignored because ignore-scripts is set to true sharp@0.23.4
npm timing action:install Completed in 4ms
npm info lifecycle sharp@0.23.4~postinstall: sharp@0.23.4
npm timing action:postinstall Completed in 0ms
npm verb unlock done using /Users/peterayeni/.npm/_locks/staging-9ec48310b3434d54.lock for /Users/peterayeni/Desktop/vt/node_modules/.staging
npm timing stage:executeActions Completed in 420ms
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 29213ms
npm verb saving [ { name: 'sharp', spec: '^0.23.4', save: 'dependencies' } ]
npm verb shrinkwrap skipping write for package.json because there were no changes.
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm timing audit submit Completed in 4444ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 4444ms
npm timing audit body Completed in 7ms
npm verb shrinkwrap skipping write for package-lock.json because there were no changes.
npm info lifecycle undefined~postshrinkwrap: undefined
+ sharp@0.23.4
updated 1 package and audited 568105 packages in 33.34s
found 1970 vulnerabilities (1565 low, 146 moderate, 259 high)
  run `npm audit fix` to fix them, or `npm audit` for details
npm verb exit [ 0, true ]
npm timing npm Completed in 33761ms
npm info ok

What is the output of running `npx envinfo --binaries --languages --system --utilities`?

System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 22.57 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 8.16.1 - ~/.nvm/versions/node/v8.16.1/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 2.15.12 - ~/Desktop/vt/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Utilities:
    CMake: 3.15.4 - /usr/local/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.23.0 - /usr/local/bin/git
  Languages:
    Bash: 3.2.57 - /bin/bash
    Go: 1.13.4 - /usr/local/go/bin/go
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.3.9 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Ruby: 2.6.1 - /Users/peterayeni/.rvm/rubies/ruby-2.6.1/bin/ruby

**Comment by lovell** [comment]
The salient part of this log is:

> npm info lifecycle sharp@0.23.4install: ignored because ignore-scripts is set to true sharp@0.23.4

You'll need to set this to false via something like `npm config set ignore-scripts false`.

**Comment by peterayeniofficial** [comment]
Thank you very much this works. :)
