### ISSUE TITLE
why use toBuffer() is to slow

### ISSUE THREAD

**Issue by xiaoblack163** [lovell/sharp#2036]
when i use sharp is fast
![image](https://user-images.githubusercontent.com/6647266/72425760-5a382200-37c3-11ea-8d86-f2f792b9a5ee.png)

![image](https://user-images.githubusercontent.com/6647266/72425703-44c2f800-37c3-11ea-803f-9077f69625ff.png)

when i use toBuffer is to slow
![image](https://user-images.githubusercontent.com/6647266/72425797-68863e00-37c3-11ea-9126-201a91288f83.png)

![image](https://user-images.githubusercontent.com/6647266/72425514-e6961500-37c2-11ea-930a-643c65a1afcc.png)

why

**Comment by lovell** [comment]
A call to `sharp()` returns a lightweight instance. A call to `toBuffer()` on that instance invokes the processing pipeline.

**Comment by xiaoblack163** [comment]
Ok, I see. Thanks for your reply

**Comment by RafidMuhymin** [comment]
@lovell Is there any way to optimize this operation?

**Comment by lovell** [comment]
@RafidMuhymin Please open a new issue with complete sample code and images that demonstrate your question. https://github.com/lovell/sharp/issues/new?labels=question&template=question.md
