### ISSUE TITLE
Composited image occasionally doesn't render first input

### ISSUE THREAD

**Issue by rmrice** [lovell/sharp#2038]
Normally compositing works great, but I've been occasionally seeing the final composited image to just render the composite input (overlay) with a transparent background rather than with the background image. This has only happened a few times and it has been pretty random, but wondering if anyone else has seen this and if it could be a potential bug.

**What is the output of running `npx envinfo --binaries --languages --system --utilities`?**
(service running in a docker container)

```
  System:
    OS: Linux 4.9 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (2) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 2.69 GB / 7.79 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.17.0 - /usr/local/bin/node
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Bash: 4.4.20 - /bin/bash
    Perl: 5.26.1 - /usr/bin/perl
```

**What are the steps to reproduce?**

This seems to be happening randomly, so it's difficult to reproduce.

**What is the expected behaviour?**

I am trying to composite a background image with an arrow overlay. Expected behavior is an image renders with the arrow overlayed over the background image.

**Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?**

```
const composite = (baseImage, arrow) => {
  return new Promise((resolve, reject) => {
    sharp(baseImage.Body)
      .composite({ input: arrow.Body })
      .toBuffer()
      .then((result) => resolve(result))
      .catch((e) => reject(e));
  });
};
```

**Comment by lovell** [comment]
Hi, are `baseImage.Body` and `arrow.Body` both Buffer instances? What image format(s) are involved?

Perhaps set the `NODE_DEBUG=sharp` environment variable to see if there are any warnings that occur at the same time as the failure.

**Comment by lovell** [comment]
@rmrice Were you able to make any progress with this?

**Comment by rmrice** [comment]
@lovell yes, thanks for following up. The issue was an implementation issue on my part. I'll go ahead and close.
