### ISSUE TITLE
Error reopen when combining rotate and sequentialRead

### ISSUE THREAD

**Issue by stone12379** [lovell/sharp#2042]
The problem persists even when upgraded to 0.2.4.0

ERROR VipsJpeg: out of order read at line 3840
VipsJpeg: out of order read at line 3840
VipsJpeg: out of order read at line 3840
VipsJpeg: out of order read at line 3840
VipsJpeg: out of order read at line 3840
VipsJpeg: out of order read at line 3840
VipsJpeg: out of order read at line 3840
VipsJpeg: out of order read at line 3840
VipsJpeg: out of order read at line 3840
VipsJpeg: out of order read at line 3840
VipsJpeg: out of order read at line 3840
VipsJpeg: out of order read at line 3840
VipsJpeg: out of order read at line 3840
VipsJpeg: out of order read at line 3840
VipsJpeg: out of order read at line 3840
VipsJpeg: out of order read at line 3840
key:largeExif.jpg

What are the steps to reproduce?

await image
.rotate()
.sequentialRead
.tiff({ pyramid: true, tile: true, tileWidth: 512, tileHeight: 512 })
.toBuffer()

What is the expected behaviour?

normal buffer

Are you able to provide a sample image that helps explain the problem?

https://gsh-full-size-dz.s3-ap-southeast-1.amazonaws.com/largeExif.jpg

**Comment by lovell** [comment]
Apologies, the work for #2016 failed to also include the EXIF-based autorotate. Commit 1a98c39 does and will be in the next release.

**Comment by stone12379** [comment]
Appreciated for quick response.

**Comment by lovell** [comment]
v0.24.1 now available.
