### ISSUE TITLE
macOS librsvg regression: Spacing between text characters in rasterized SVGs is superwide in 0.24.0 vs 0.23.4

### ISSUE THREAD

**Issue by m1h4** [lovell/sharp#2043]
What is the output of running `npx envinfo --binaries --languages --system --utilities`?

```
  System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 2.60 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.6.0 - /usr/local/bin/node
    npm: 6.13.6 - /usr/local/bin/npm
  Utilities:
    CMake: 3.16.2 - /usr/local/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.25.0 - /usr/local/bin/git
    Clang: 1100.0.33.17 - /usr/bin/clang
    Subversion: 1.10.4 - /usr/bin/svn
    FFmpeg: 4.2.2 - /usr/local/bin/ffmpeg
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 12.0.1 - /usr/bin/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.3.9 - /usr/bin/php
    Python: 2.7.17 - /usr/local/bin/python
    Python3: 3.7.6 - /usr/local/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby
```

What are the steps to reproduce?

Use `sharp('file.svg', {density: 220}).toFile('file.png')` to process the following SVG:

```XML
<?xml version="1.0"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="100" height="50">
        <text x="10" y="20">ABCD</text>
</svg>
```

What is the expected behaviour?

With Sharp **v0.23.4** we get the following (correct) image:
![v0 23 4](https://user-images.githubusercontent.com/1467554/72712501-71806200-3b6b-11ea-8951-657b13e74e15.png)

But with Sharp **v0.24.0** for some reason we get the following image with huge spacing between characters:
![v0 24 0](https://user-images.githubusercontent.com/1467554/72712510-76451600-3b6b-11ea-93d9-0b0362a10861.png)

**Comment by lovell** [comment]
Hi, what's the output of running `console.log(require('sharp').versions)`?

**Comment by m1h4** [comment]
Here's the output:
```
{
  cairo: '1.16.0',
  croco: '0.6.13',
  exif: '0.6.21',
  fontconfig: '2.13.1',
  freetype: '23.1.17',
  fribidi: '1.0.8',
  gdkpixbuf: '2.40.0',
  gif: '5.2.1',
  glib: '2.62.4',
  gsf: '1.14.46',
  harfbuzz: '2.6.4',
  jpeg: '2.0.4',
  lcms: '2.9',
  orc: '0.4.31',
  pango: '1.44.7',
  pixman: '0.38.4',
  png: '1.6.37',
  svg: '2.46.4',
  tiff: '4.1.0',
  vips: '8.9.0',
  webp: '1.0.3',
  xml: '2.9.4'
}
```

**Comment by lovell** [comment]
Thanks, this problem appears to occur when using librsvg v2.46.4 but not with v2.47.1, so is an upstream bug that has been recently fixed.

The prebuilt binaries for macOS provide librsvg v2.46.4 (as this is what [Homebrew provides](https://github.com/Homebrew/homebrew-core/blob/11eacb09d88ff509da2fe321316bff5168d8461e/Formula/librsvg.rb#L4)) whereas for Linux a more recent librsvg v2.47.1 is provided.

To workaround this, you'll need to wait for Homebrew to catch up then either (a) install vips from Homebrew and reinstall sharp to use it or (b) wait for sharp v0.25.0, which by the time of release (I do not know and cannot say when this will be) will probably provide a more recent version of librsvg with this fix.

**Comment by m1h4** [comment]
Great, thanks for looking into this!

**Comment by lovell** [comment]
Upstream issue at https://github.com/Homebrew/homebrew-core/pull/51450

**Comment by lovell** [comment]
v0.26.0 now available with prebuilt binaries that include the upstream fixes.
