### ISSUE TITLE
Increasing brightness / exposure

### ISSUE THREAD

**Issue by dhowe** [lovell/sharp#2044]
I need to increase brightness and/or exposure for images taken in low light. I read through https://github.com/lovell/sharp/issues/609, but then didn't find modulate() in the API. It also _appeared_ that one could only decrease the brightness, or are values over 100% allowed?
An example would be amazing -- thanks for the great lib...

**Comment by lovell** [comment]
Did you see the [modulate](https://sharp.pixelplumbing.com/api-operation#modulate) operation?

**Comment by dhowe** [comment]
my bad, not sure how I didnt see that - thanks for all the good work
