### ISSUE TITLE
Failed to deploy on AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by MihaiZhaoDev** [lovell/sharp#2045]
I am trying to deploy on AWS Elastic Beanstalk and there are some errors with libvips. I tried to remove the node_modules folder and rebuild but it didn't work. I created the .npmrc file with unsafe-perm=true and still didn't work. I can't figure out what is the problem.

Any help? Thanks in advance.

Logs:
+ /opt/elasticbeanstalk/containerfiles/ebnode.py --action npm-install
npm WARN webpack-obfuscator@0.18.3 requires a peer of webpack@^4.3.0 but none is installed. You must install peer dependencies yourself.

audited 3635 packages in 4.468s
found 4 vulnerabilities (1 moderate, 3 high)
run `npm audit fix` to fix them, or `npm audit` for details

> sharp@0.23.1 install /tmp/deployment/application/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using existing vendored libvips v8.8.1
prebuild-install WARN install /tmp/deployment/application/node_modules/sharp/build/Release/../../vendor/lib/libvips-cpp.so.42: file too short
make: Entering directory `/tmp/deployment/application/node_modules/sharp/build'
TOUCH Release/obj.target/libvips-cpp.stamp
CXX(target) Release/obj.target/sharp/src/common.o
CXX(target) Release/obj.target/sharp/src/metadata.o
CXX(target) Release/obj.target/sharp/src/stats.o
CXX(target) Release/obj.target/sharp/src/operations.o
CXX(target) Release/obj.target/sharp/src/pipeline.o
CXX(target) Release/obj.target/sharp/src/sharp.o
CXX(target) Release/obj.target/sharp/src/utilities.o
SOLINK_MODULE(target) Release/obj.target/sharp.node
/usr/bin/ld:../vendor/lib/libvips-cpp.so: file format not recognized; treating as linker script
/usr/bin/ld:../vendor/lib/libvips-cpp.so:1: syntax error
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/sharp.node] Error 1
make: Leaving directory `/tmp/deployment/application/node_modules/sharp/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/opt/elasticbeanstalk/node-install/node-v10.17.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:193:23)
gyp ERR! stack at ChildProcess.emit (events.js:198:13)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.14.152-98.182.amzn1.x86_64
gyp ERR! command "/opt/elasticbeanstalk/node-install/node-v10.17.0-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v10.17.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/deployment/application/node_modules/sharp
gyp ERR! node -v v10.17.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.23.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.23.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /tmp/.npm/_logs/2020-01-20T12_56_56_196Z-debug.log
Running npm install: /opt/elasticbeanstalk/node-install/node-v10.17.0-linux-x64/bin/npm
Setting npm config jobs to 1
npm config jobs set to 1
Running npm with --production flag
Failed to run npm install. Snapshot logs for more details.
UTC 2020/01/20 12:56:56 cannot find application npm debug log at /tmp/deployment/application/npm-debug.log

Traceback (most recent call last):
File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 695, in <module>
main()
File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 677, in main
node_version_manager.run_npm_install(options.app_path)
File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 136, in run_npm_install
self.npm_install(bin_path, self.config_manager.get_container_config('app_staging_dir'))
File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 180, in npm_install
raise e
subprocess.CalledProcessError: Command '['/opt/elasticbeanstalk/node-install/node-v10.17.0-linux-x64/bin/npm', '--production', 'rebuild']' returned non-zero exit status 1.

**Comment by MihaiZhaoDev** [comment]
Here are the logs from eb-commandprocessor.log:

make: Entering directory `/tmp/deployment/application/node_modules/sharp/build'
  make: Warning: File `../binding.gyp' has modification time 12 s in the future
    ACTION Regenerating Makefile
  make: Leaving directory `/tmp/deployment/application/node_modules/sharp/build'
  make: Entering directory `/tmp/deployment/application/node_modules/sharp/build'
  make: Warning: File `../binding.gyp' has modification time 8.2 s in the future
    ACTION Regenerating Makefile
  make: Leaving directory `/tmp/deployment/application/node_modules/sharp/build'
  make: Entering directory `/tmp/deployment/application/node_modules/sharp/build'
  make: Warning: File `../binding.gyp' has modification time 4.3 s in the future
    ACTION Regenerating Makefile
  make: Leaving directory `/tmp/deployment/application/node_modules/sharp/build'
  make: Entering directory `/tmp/deployment/application/node_modules/sharp/build'
  make: Warning: File `../binding.gyp' has modification time 0.68 s in the future
    ACTION Regenerating Makefile
  make: Leaving directory `/tmp/deployment/application/node_modules/sharp/build'
  make: Entering directory `/tmp/deployment/application/node_modules/sharp/build'
    TOUCH Release/obj.target/libvips-cpp.stamp
    CXX(target) Release/obj.target/sharp/src/common.o
    CXX(target) Release/obj.target/sharp/src/metadata.o
    CXX(target) Release/obj.target/sharp/src/stats.o
    CXX(target) Release/obj.target/sharp/src/operations.o
    CXX(target) Release/obj.target/sharp/src/pipeline.o
    CXX(target) Release/obj.target/sharp/src/sharp.o
    CXX(target) Release/obj.target/sharp/src/utilities.o
    SOLINK_MODULE(target) Release/obj.target/sharp.node
  /usr/bin/ld:../vendor/lib/libvips-cpp.so: file format not recognized; treating as linker script
  /usr/bin/ld:../vendor/lib/libvips-cpp.so:1: syntax error
  collect2: error: ld returned 1 exit status
  make: *** [Release/obj.target/sharp.node] Error 1
  make: Leaving directory `/tmp/deployment/application/node_modules/sharp/build'
  gyp ERR! build error 
  gyp ERR! stack Error: `make` failed with exit code: 2
  gyp ERR! stack     at ChildProcess.onExit (/opt/elasticbeanstalk/node-install/node-v10.17.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:193:23)
  gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
  gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
  gyp ERR! System Linux 4.14.152-98.182.amzn1.x86_64
  gyp ERR! command "/opt/elasticbeanstalk/node-install/node-v10.17.0-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v10.17.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
  gyp ERR! cwd /tmp/deployment/application/node_modules/sharp
  gyp ERR! node -v v10.17.0
  gyp ERR! node-gyp -v v5.0.3
  gyp ERR! not ok 
  npm ERR! code ELIFECYCLE
  npm ERR! errno 1
  npm ERR! sharp@0.23.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
  npm ERR! Exit status 1
  npm ERR! 
  npm ERR! Failed at the sharp@0.23.1 install script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /tmp/.npm/_logs/2020-01-20T15_18_32_612Z-debug.log
  Running npm install:  /opt/elasticbeanstalk/node-install/node-v10.17.0-linux-x64/bin/npm
  Setting npm config jobs to 1
  npm config jobs set to 1
  Running npm with --production flag
  Failed to run npm install. Snapshot logs for more details.
  UTC 2020/01/20 15:18:32 cannot find application npm debug log at /tmp/deployment/application/npm-debug.log 
  
  Traceback (most recent call last):
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 695, in <module>
      main()
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 677, in main
      node_version_manager.run_npm_install(options.app_path)
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 136, in run_npm_install
      self.npm_install(bin_path, self.config_manager.get_container_config('app_staging_dir'))
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 180, in npm_install
      raise e
  subprocess.CalledProcessError: Command '['/opt/elasticbeanstalk/node-install/node-v10.17.0-linux-x64/bin/npm', '--production', 'rebuild']' returned non-zero exit status 1 (Executor::NonZeroExitStatus)

**Comment by lovell** [comment]
The message `../vendor/lib/libvips-cpp.so: file format not recognized` suggests that this file is somehow corrupt. It's a symlink, so my best guess would be that you need to ensure whatever you're using for packaging supports symlinks.

**Comment by MihaiZhaoDev** [comment]
Thank you lovell! The issues has been solved. I removed some of the packages and I added the AWS writting access .nmprc, somehow it worked. . Thank you so much!
