### ISSUE TITLE
Error: Input buffer has corrupt header: glib: XML parse error

### ISSUE THREAD

**Issue by NoTalk-ly** [lovell/sharp#2049]
What is the output of running `npx envinfo --binaries --languages --system --utilities`?
![image](https://user-images.githubusercontent.com/30374176/72874937-25c9e600-3d2e-11ea-98f4-e572eabda3c8.png)

What are the steps to reproduce?
https://gist.github.com/NoTalk-ly/11678ba68dc682498b92e5402333da68 this gistcan reproduce this case.
What is the expected behaviour?
no error.
Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?
above code snippet only depends on sharp.

Are you able to provide a sample image that helps explain the problem?
this error means sharp is not compatible some svg format？ but I use node-canvas to convert svg to png， it works without error，and the output image is correct.

**Comment by NoTalk-ly** [comment]
I try 3 version 0.22.0 0.23.0 0.24.0 and changed node version from 8.9.0 to 13.14.0. no one worked.

**Comment by lovell** [comment]
The backslash characters in the title need escaping to ensure the JavaScript string is valid XML.
```diff
- <title id="MathJax-SVG-1-Title">P \left( \bigcup \limits_{i=1}^{+ \infty}A_{i}\right) = \prod \limits_{i=1}^{+ \infty}P{\left( A_{i}\right)}</title>
+ <title id="MathJax-SVG-1-Title">P \\left\( \\bigcup \\limits_{i=1}^{+ \\infty}A_{i}\\right) = \\prod \\limits_{i=1}^{+ \\infty}P{\\left( A_{i}\\right)}</title>
```

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
