### ISSUE TITLE
Font issues from SVG to PNG when there are multiple font names

### ISSUE THREAD

**Issue by soetji** [lovell/sharp#2051]
What is the output of running `npx envinfo --binaries --languages --system --utilities`?

```
System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 66.81 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Utilities:
    CMake: 3.15.3 - /usr/local/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.23.0 - /usr/local/bin/git
    Clang: 1100.0.33.17 - /usr/bin/clang
    Subversion: 1.10.4 - /usr/bin/svn
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 1.8.0_40 - /usr/bin/javac
    Perl: 5.24.0 - /opt/local/bin/perl
    PHP: 7.3.9 - /usr/bin/php
    Python: 2.7.16 - /usr/local/bin/python
    Python3: 3.7.5 - /usr/local/bin/python3
    Ruby: 2.6.3 - /Users/soetjianto/.rbenv/shims/ruby
```

What are the steps to reproduce?

`sharp('test.svg').toFile('test.png')`

What is the expected behaviour?

The font in the svg should be in the png. It is not if multiple fonts are listed.

Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?

Below works. The svg and png show the same font.
```
<svg xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" xmlns="http://www.w3.org/2000/svg" height="50" width="100">
    <text x="10"  y="30" style="font-family:arial;font-size:20px;fill:#999999">TEST</text>
</svg>
```
If you change `style="font-family:arial;...` to `style="font-family:arial,helvetica;...`, the svg still works fine. However, the png shows what looks like the default system font.

Are you able to provide a sample image that helps explain the problem?

PNG from `style="font-family:arial;...`:

![font](https://user-images.githubusercontent.com/220015/73018236-37bf8d80-3def-11ea-96d5-c72759365cc0.png)

PNG from `style="font-family:arial,helvetica;...`:

![font](https://user-images.githubusercontent.com/220015/73018180-0fd02a00-3def-11ea-97a7-a85d67db22a2.png)

**Comment by lovell** [comment]
If librsvg is unable to parse a `font-family` value it will default to Times New Roman.

Try adding quotes around the list of font names:
```
style="font-family:'arial,helvetica';...
```

The SVG 1.1 spec is a little ambiguous about where the quotes should go:

> "Unless the family name corresponds to a CSS IDENT, it must be quoted."
> https://www.w3.org/TR/SVG11/text.html#FontPropertiesUsedBySVG

**Comment by soetji** [comment]
Yup, it works by adding quotes. Thank you!

I am curious why librsvg is unable to parse without the quotes while web browsers can.

**Comment by lovell** [comment]
Different SVG renderers use different parsers, which have different interpretations of the spec (and support different versions of the spec). As your question relates to librsvg, perhaps you could provide these examples and ask upstream at https://gitlab.gnome.org/GNOME/librsvg/

**Comment by soetji** [comment]
Good suggestion. I will ask librsvg. Thanks for your help.
