### ISSUE TITLE
toFile does not save all files.

### ISSUE THREAD

**Issue by AlexandrHovsepyan** [lovell/sharp#2053]
Using sharp for reading the image from the buffer. Resizing it then saving with toFile function, but when I check the directory, there are only 4 or 6, or 7 or the exact 8 of the 8 sent images saved.

await sharp(file.buffer)
          .resize(dimensions.width, dimensions.height + 1)     
          .resize(dimensions.width, dimensions.height)
          .toFormat(dimensions.type)                       
          .toFile(dir + `/${filename}` + fileFormat);

**Comment by lovell** [comment]
Please can you provide a complete, standalone code sample that allows someone else to reproduce this problem.

**Comment by AlexandrHovsepyan** [comment]
`const multer = require('multer');
const sharp = require('sharp');
const imageSize = require('image-size');

const storage = multer.memoryStorage();

exports.mediaResizeFiles = async (req, res, next) => {
      await Promise.all(
            req.files.map(async file => {
                let userId = req.user._id;
                let data = req.user._id + '-' + Date.now();
                let filename = crypto.createHash('md5').update(data).digest("hex");
                let fileFormat = path.extname(file.originalname);
                let directory = '';
    
                if (file.mimetype.startsWith('image')) {
                    
                    directory = 'image';
                     let dir = createMediaDir(userId, directory);

                    let dimensions = imageSize(file.buffer);
                
                    await sharp(file.buffer)
                            .resize(dimensions.width, dimensions.height + 1)
                            .resize(dimensions.width, dimensions.height) 
                            .toFormat(dimensions.type)                      
                            .toFile(dir + `/${filename}` + fileFormat);
                  }
          })
}`

This is the main part of the code related to the issue.

**Comment by lovell** [comment]
This bit of code, unrelated to sharp, will not generate unique filenames:
```
let data = req.user._id + '-' + Date.now();
let filename = crypto.createHash('md5').update(data).digest("hex");
```

**Comment by AlexandrHovsepyan** [comment]
I am sorry, I think there is a misunderstanding. Do you mean that in the 8 files there the cache (md5) is being matched with the each other?

**Comment by lovell** [comment]
The value of `filename` is an md5 hash of a timestamp that is not guaranteed to be unique.

**Comment by AlexandrHovsepyan** [comment]
After changes, I believe everything is fine now. Thank you for everything.
