### ISSUE TITLE
Composite produces a cropped result (bottom cropped)

### ISSUE THREAD

**Issue by alanzanattadev** [lovell/sharp#2059]
What is the output of running `npx envinfo --binaries --languages --system --utilities`?

 System:
    OS: Linux 5.3 Fedora 31 (Container Image) 31 (Container Image)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 1.22 GB / 15.50 GB
    Container: Yes
    Shell: 5.0.11 - /bin/bash
  Binaries:
    Node: 12.13.1 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.12.1 - /usr/bin/npm
  Utilities:
    Make: 4.2.1 - /usr/bin/make
    GCC: 9.2.1 - /usr/bin/gcc
    Git: 2.24.1 - /usr/bin/git
    Mercurial: 4.9 - /usr/bin/hg
    Subversion: 1.12.2 - /usr/bin/svn
  Languages:
    Bash: 5.0.11 - /usr/bin/bash
    Go: 1.13.5 - /usr/bin/go
    Perl: 5.30.1 - /usr/bin/perl
    Python: 3.7.5 - /usr/bin/python
    Python3: 3.7.5 - /usr/bin/python3
    Ruby: 2.6.5 - /usr/bin/ruby

What are the steps to reproduce?

`sharp(imageA)
          .composite([
            {
              input: imageB,
            }
          ])
          .toBuffer()`

where imageA and imageB are both Buffers, with imageB Buffer smaller than imageA Buffer but both with the same image size.

What is the expected behaviour?

The resulting image shouldn't be cropped on the bottom. imageB contains the text "watermark", and you can see a part of it, but the watermark is cropped and the imageA is cropped as well on the bottom. I noticed that the smaller would be imageB, the least cropped it would become.

Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?

Are you able to provide a sample image that helps explain the problem?
![image](https://user-images.githubusercontent.com/9500204/73387481-f1779c00-42d0-11ea-9265-d79a8c3a5afb.png)

**Comment by lovell** [comment]
Please can you provide both of the input images.

**Comment by alanzanattadev** [comment]
The first one is there: https://passbase.com/assets/images/logo.png
I generate the overlay with another library (gm):
`gm(width, height, "#00000000")
        .fill(color)
        .stroke(color)
        .strokeWidth(3)
        .font("Arial", size)
        .draw(`rotate`, 25, "gravity", "Center", `text 0,0 'watermark'`)
        // .bitdepth(depth)
        // .density(width, height)
        .toBuffer("PNG", (err, buffer: Buffer) => {
          // buffer is imageB
        });`

height and width are the result of the measure of the first image, you can use any value marked as variables it doesn't change the problem.

Thank you for your answer !

**Comment by alanzanattadev** [comment]
Some observations that might help you to troubleshoot:
  - If I use imageA and imageA (imageA as imageB), so twice the same image and compose, it works without cropping (same with twice imageB)
  - if I change the rotation of the watermark text, for some reasons it crops differently (the more it goes towards diagonal, the more it crops, the more it's horizontal or vertical, the less it crops, but still it crops)
  - the bigger the watermark text, the more it crops (it seems that it takes the available pixels somehow and that the cropping means "not enough pixels left")
  - if I remove the alpha using "flatten" on imageA, then it doesn't crop anymore

I hope it can help you :/ I spent 8h on the issue without finding out the reason

**Comment by lovell** [comment]
Please can you provide the second input image (the output of the gm command).

**Comment by alanzanattadev** [comment]
![test](https://user-images.githubusercontent.com/9500204/73430263-e6a72080-433d-11ea-9645-6f68001434ee.png)

**Comment by lovell** [comment]
Using the latest v0.24.0 of sharp and the following code:
```javascript
sharp("logo.png")
  .composite([{ input: "73430263-e6a72080-433d-11ea-9645-6f68001434ee.png" }])
  .toFile("out.png");
```
...I see the following output:

![](https://user-images.githubusercontent.com/210965/73495415-6967c400-43ae-11ea-89ba-5480d6faf9b8.png)

...which looks correct to me.

**Comment by alanzanattadev** [comment]
Indeed for you it works, that's super weird.

Is it possible that the underlying environment changes something about it ? I run this on fedora toolbox using the latest fedora 31, maybe the underlying library version is different ?

Did you try using buffers instead of files ?

Do you have any idea of how I can debug this on my own ? how to troubleshoot and what to look for ? 

Thank you

**Comment by alanzanattadev** [comment]
I figured out that the issue intervenes after the use of the library, I must cut the buffer somewhere for reasons that I still ignore, but I don't need to let the issue open because it's not of your concern :)

Thank you for having spent some time trying it out, ultimately it helped me figuring out the source of the issue !
