### ISSUE TITLE
Error: VipsOperation: class "icc_transform" not found

### ISSUE THREAD

**Issue by bradisbell** [lovell/sharp#206]
When converting from CMYK images, I'm getting this:

>2015-04-29T19:49:51.349Z - debug: Image metadata format=jpeg, width=400, height=200, space=cmyk, channels=4, hasProfile=false, hasAlpha=false
>2015-04-29T19:49:51.368Z - warn: Error response Error: VipsOperation: class "icc_transform" not found
>
>    at Error (native)

sharp v0.10.0, Node.js v0.12.2, ImageMagick 6.8.9, vips 7.40.2.

Any suggestions?

**Comment by lovell** [comment]
My best guess is that libvips was compiled without LCMS support - see https://github.com/jcupitt/libvips/#lcms2-lcms

**Comment by bradisbell** [comment]
That solved it!  Thanks.
