### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by sgpinkus** [lovell/sharp#2061]
*Description*

Vanilla install of sharp v0.24.0 on Debian Linux 9 get memory leak. Not releasing input image buffer? Install says "sharp Using cached /home/sam/.npm/_libvips/libvips-8.9.0-linux-x64.tar.gz ..."

Tried messing with `sharp.cache` settings and forcing `global.gc()` but neither fixed the issue.

*What is the output of running `npx envinfo --binaries --languages --system --utilities`?*

```
npx: installed 1 in 0.742s

  System:
    OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (1) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 3.12 GB / 3.86 GB
    Container: Yes
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 12.13.1 - /usr/bin/node
    npm: 6.12.1 - /usr/bin/npm
  Utilities:
    Make: 4.1 - /usr/bin/make
    GCC: 6.3.0 - /usr/bin/gcc
    Git: 2.11.0 - /usr/bin/git
  Languages:
    Bash: 4.4.12 - /bin/bash
    Perl: 5.24.1 - /usr/bin/perl
    PHP: 7.0.33 - /usr/bin/php
    Python: 2.7.13 - /usr/bin/python
    Python3: 3.5.3 - /usr/bin/python3
```

*What are the steps to reproduce?*
Run this code with k=1 or k=2 (k=0 case works fine):

```
const fs = require('fs')
const sharp = require('sharp')
const num = 300;

function test(k) {
  const testBuffer = fs.readFileSync('test.jpg');
  for(i=0; i < num; i++) {
    console.log(i);
    switch(k) {
      case 0:
        sharp(testBuffer).resize(20, 20, { fit: 'inside' }).png().toFile('/tmp/resized.png');
        break
      case 1:
        const b = fs.readFileSync('test.jpg');
        sharp(b).resize(20, 20, { fit: 'inside' }).png().toBuffer((err, buffer, info) => {
          fs.writeFileSync('/tmp/resized.png', buffer)
        });
        break
      case 2:
        sharp(fs.readFileSync('test.jpg')).resize(20, 20, { fit: 'inside' }).png().toFile('/tmp/resized.png');
        break
    }
  }
  console.log('Done')
}
test(1)
```

*What is the expected behaviour?*
Don't use all RAM.

*Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?*
As above.

*Are you able to provide a sample image that helps explain the problem?*
Just created a random large (8000x8000) JPG with gimp:

```
ls -lh test.jpg && file test.jpg 
-rw-r--r-- 1 admin admin 8.8M Jan 30 13:11 test.jpg
test.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 300x300, segment length 16, comment: "Created with GIMP", progressive, precision 8, 8000x8000, frames 3
```

**Comment by lovell** [comment]
Hi, although cases k=1 and k=2 use synchronous fs functions, they aren't using sharp in a synchronous manner so it's very likely that all 300 Buffer instances, either as input or output, will be in memory at once.

Perhaps you could try using async/await instead, something like:

```diff
- sharp(fs.readFileSync('test.jpg')).resize(20, 20, { fit: 'inside' }).png().toFile('/tmp/resized.png');
+ await sharp(fs.readFileSync('test.jpg')).resize(20, 20, { fit: 'inside' }).png().toFile('/tmp/resized.png');
```

**Comment by sgpinkus** [comment]
Thankw @lovell. That fixed it!

**Comment by sgpinkus** [comment]
FYI for anyone coming across this. The above test script was an imperfect distillation of some server code that was causing OOM when large WxH images were submitted to servers on containers with a 2G max memory limit. I did need to add an `await`, but this did not complete the fix. The fix was to drastically reduce sharp.cache to `{files: 10, items: 10}` or even smaller to be safe.
