### ISSUE TITLE
Something went wrong installing the "sharp" module. Module did not self-register.

### ISSUE THREAD

**Issue by wpdeema** [lovell/sharp#2065]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?

Yes

Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime?

I use Yarn

If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

N/A

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

N/A

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

There are no errors. It gives me successful message:

```
success Saved 1 new dependency.
info Direct dependencies
└─ sharp@0.24.0
info All dependencies
└─ sharp@0.24.0
```

What is the output of running `npx envinfo --binaries --languages --system --utilities`?

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 7.77 GB / 32.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 10.14. - /usr/bin/gcc
    Git: 2.20.1 - /usr/bin/git
    Clang: 1001.0.46.4 - /usr/bin/clang
    Subversion: 1.10.3 - /usr/bin/svn
  Languages:
    Bash: 3.2.57 - /bin/bash
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.1.32 - /usr/bin/php
    Python: 2.7.16 - /usr/local/bin/python
    Ruby: 2.3.7 - /usr/bin/ruby
```

**Comment by wpdeema** [comment]
I found a reason. That is `install-app-deps` script which is encouraged by `electron-builder`. It forces packages to rebuild.

**Comment by wpdeema** [comment]
I think I understood the problem. Even though my project is targeted for electron I normally execute it outside of it (basically have client-server running separately). In this case sharp is executed with regular node runtime (10.17.0) but `install-app-deps` compiles it for electron's node version (it's own fork). So we come to the condition when runtime does not match the target.

**Comment by wpdeema** [comment]
I am not sure whether many people have the same scenario like mine but for those who interested I'll share my further research. In my case I would need to be able to run application in two modes: standalone and under within electron. Therefore I would need to build packages depending on the mode.

Unfortunately, I could not find a solution how to fix the package for current Yarn version but there are still couple of options:

1. NPM has `rebuild` command. Once executed it will rebuild the package using correct Node version. Quite similar to what `install-app-deps` does for electron.
2. Upgrade to Yarn 2 which also has `rebuild` command but it is on early stage so far and looks like it is quite different to v1.

I personally chose to switch to NPM as it is much easier and more stable option at the moment.

**Comment by heysoypaez** [comment]
Hi, in my case i had this problem doing an installation of [gatsby](https://www.gatsbyjs.org/) . I could resolve it removing the .cache/ directory.

**Comment by Creizai** [comment]
> I am not sure whether many people have the same scenario like mine but for those who interested I'll share my further research. In my case I would need to be able to run application in two modes: standalone and within electron. Therefore I would need to build packages depending on the mode.
> 
> Unfortunately, I could not find a solution how to fix the package for current Yarn version but there are still couple of options:
> 
> 1. NPM has `rebuild` command. Once executed it will rebuild the package using correct Node version. Quite similar to what `install-app-deps` does for electron.
> 2. Upgrade to Yarn 2 which also has `rebuild` command but it is on early stage so far and looks like it is quite different to v1.
> 
> I personally chose to switch to NPM as it is much easier and more stable option at the moment.

Thank you this fixed my problem!

**Comment by adiusz** [comment]
@wpdeema Thank you very much!
I'm building Gatsby website and I stack with this error. `npm rebuild` helped.
