### ISSUE TITLE
Installing in CodeBuild and packaging for lambda

### ISSUE THREAD

**Issue by Russ-K** [lovell/sharp#2066]
Hi,

I'm attempting to use sharp in an AWS lambda function, the code for which is packaged as part of an AWS CodeBuild project.
The CodeBuild image is aws/codebuild/amazonlinux2-x86_64-standard:2.0 which should be the same image (or certainly environment) used in lambda.

When running the lambda function I get the following error:
```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'node_modules/sharp'",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'node_modules/sharp'",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
        "    at Module.load (internal/modules/cjs/loader.js:653:32)",
        "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
        "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",
        "    at startup (internal/bootstrap/node.js:283:19)"
    ]
}
```

The CodeBuild build platform should be the same as the lambda function and I've tried the various suggestions to no avail like

- unsafe-perms
- explicitly stating the build target environment (`--engine-strict=true --arch=x64 --platform=linux --target=10.14.1`)

I've attached the output for
`npm install -- verbose sharp`
[npm install output.txt](https://github.com/lovell/sharp/files/4139127/npm.install.output.txt)

and the output for
`npx envinfo --binaries --languages --system --utilities`
[npx envinfo output.txt](https://github.com/lovell/sharp/files/4139018/npx.envinfo.output.txt)

**Comment by lovell** [comment]
Everything appears to install OK so this looks like a packaging problem. Does the directory `node_modules/sharp` exist in the zip file you're deploying?

**Comment by Russ-K** [comment]
It does indeed:
![image](https://user-images.githubusercontent.com/4568306/73563705-ec902500-4455-11ea-826d-de577381b244.png)

**Comment by lovell** [comment]
Is sharp being imported at runtime via `const sharp = require('sharp');`? Is there any bundling via webpack or similar taking place?

**Comment by Russ-K** [comment]
So annoyed.
As part of the refactor to use a CD stack (CodeBuild) I moved a library method (the one that references sharp) to a sub folder...
Sorry for wasting your time but it certainly assisted me in finding the issue.
