### ISSUE TITLE
Sharp .recomb function get original matrix

### ISSUE THREAD

**Issue by IuriRiquesoDias** [lovell/sharp#2069]
What are you trying to achieve?
I am trying to apply a recomb matrix to a JPEG image

Have you searched for similar questions?
Yes

So from what I could understand, .recomb applies brightness to the RGB and their respective 3 tones. I need to know if there is a way I can fetch the image's current matrix and recomb it using it's previous matrix and my own generated offset.

**Comment by IuriRiquesoDias** [comment]
I figured it out. To get the original matrix, simply use the following array:

[1, 0, 0]
[0, 1, 0]
[0, 0, 1]

**Comment by nemoDreamer** [comment]
Some kind of guide or basic info on what recomb actually _does_ and what each point in the matrix represents would be really helpful... Not even the `VImage` library has _any_ information and searching for combinations of "image recomb recombination matrix" returns very obscure results or results related to DNA recombination...

Had to finally figure out via trial and error how I could use this to turn my 50% gray into a specific color, thanks in part to @IuriRiquesoDias's answer, and intuiting that it must be the three channels and their respective mixes.
