### ISSUE TITLE
Transparent PNG to Webp in Windows Machine using Gatsby

### ISSUE THREAD

**Issue by yudyananda** [lovell/sharp#2072]
i'm using [gatsby-transformer-sharp](https://www.npmjs.com/package/gatsby-transformer-sharp) that use sharp. Everything working as i expected except when i try to transform png to webp.

## expected result
![test](https://user-images.githubusercontent.com/29258979/73866361-48541700-4877-11ea-84eb-1e6c6aff75f5.png)

## result

![test](https://user-images.githubusercontent.com/29258979/73866015-b4824b00-4876-11ea-8954-3797463a327d.png)

I'm not realy sure but related to [this issue](https://github.com/gatsbyjs/gatsby/issues/14497) maybe this has something to do with sharp in **windows machine**.

~~~
System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz
    Memory: 5.24 GB / 9.90 GB
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Users\Yudy\AppData\Roaming\npm\npm.CMD
  Utilities:
    Git: 2.22.0. - C:\Program Files\Git\cmd\git.EXE
  Languages:
    Bash: 4.3.46 - C:\WINDOWS\system32\bash.EXE
    Go: 1.13 - C:\Go\bin\go.EXE
    PHP: 7.2.12 - C:\xampp\php\php.EXE
    Python: 2.7.16 - C:\Python27\python.EXE
~~~

**Comment by lovell** [comment]
Hi, are you able to reproduce this using only sharp? The comment at https://github.com/gatsbyjs/gatsby/issues/14497#issuecomment-499321445 suggests others have not (yet) been able to do so.

I think Gatsby does some post-processing of WebP images after sharp has finished, which is where I suspect this problem might arise.

**Comment by yudyananda** [comment]
Hi, you are right. After some test turns out sharp only working fine to transform png to webp in windows machine.
