### ISSUE TITLE
Question: how to optimize performance while generating many buffers with .toBuffer() ?

### ISSUE THREAD

**Issue by Aarbel** [lovell/sharp#2074]
I'm using Promise.all() to create many buffers from a streamed image (i'm making cropped images from one image).

I'm facing big performances issues, takes 2min to Ouput 100 streams to Buffer (very small images).

What could be the origin of the problem ? 

Thanks a a lot for your help !

**Full repo to clone and test in 1 min with the problem**
👉 https://github.com/Aarbel/sharp-slow-buffer-generation-test

**My code**

```JS
const _ = require('lodash');
const Promise = require("bluebird");
const fs = require('fs');
const sharp = require('sharp');
const fsExtra = require('fs-extra');

/* CONVERTS BIG IMAGE TO SMALL IMAGES TILES OF ZOOM LEVELS */

/* Returns all the tile transformers for a given zoom level. */
const zoomLevelTransformers = (sharpBigImageFileStream, zoomLevel) => {
    /* Using tiles of 512 x 512 */
    const rootSize = 512 * 2 ** zoomLevel;

    /* Resize the BigSquare image to root size of zoom level */
    const root = sharpBigImageFileStream.resize({
        width: rootSize,
        height: rootSize,
    });

    const tileColumnCount = 2 ** zoomLevel;

    return Promise.all(
        /* here lodash just iterates thru a grid array of 1 * 1 until 16 * 16 */
        _().range(tileColumnCount)
            .flatMap(x => _.range(tileColumnCount)
                .map(y => {
                    console.log('Start — :', `Z-${zoomLevel}-${x}-${y}`);
                    const rootClone = root.clone();

                    const cropedImage = rootClone.extract({
                        left: 512 * x,
                        top: 512 * y,
                        width: 512,
                        height: 512,
                    });

                    return cropedImage
                        .toBuffer()
                        .then((data) => {
                            console.log('createdBuffer success :', `Z-${zoomLevel}-${x}-${y}`);
                        })
                        .catch(err => { 
                            console.log('createdBuffer error :', err);
                        });
                })
            )
    )
};

exports.lambdaHandler = async () => {
    const bigImageFileStream = await fs.createReadStream('big.png');
    const sharpBigImageFileStream = sharp();
    sharpBigImageFileStream.setMaxListeners(0);
    bigImageFileStream.pipe(sharpBigImageFileStream);

    const zoomLevelRange = [0, 1, 2, 3, 4];

    await Promise.all(
        zoomLevelRange.map((zoomLevel) => {
            return zoomLevelTransformers(sharpBigImageFileStream, zoomLevel);
        }
        ),
    )

    return {
        body: "Success",
        statusCode: 200,
    };
};
```

**Comment by lovell** [comment]
Please can you provide a complete, standalone code sample and image that demonstrates this problem.

**Comment by Aarbel** [comment]
@lovell 
I updated my post, and pushed a public repo to test in 1min here 
https://github.com/Aarbel/sharp-slow-buffer-generation-test

**Comment by lovell** [comment]
Thank you for the complete example. Running this through callgrind via:
```sh
valgrind --tool=callgrind node -e "require('./app').lambdaHandler()"
```
reveals most of the time is spent (repeatedly) decoding PNG input via `inflate_fast`:
```
53,270,161,841  /build/glibc-KRRWSm/glibc-2.29/string/../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:__memcpy_avx_unaligned_erms
52,114,986,263  /build/glibc-KRRWSm/glibc-2.29/string/../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:__memset_avx2_erms
50,996,910,136  ???:inflate_fast
38,044,195,005  ???:adler32_z
 6,142,618,565  ???:0x00000000000643c0
```
sharp+libvips is on-demand, so every time you request an output image, it will decode the input image.

To avoid this you could create intermediate images, perhaps as raw pixel data to avoid the PNG de/encode roundtrip if memory is not of concern.

Alternatively, have a look at the existing [tile](https://sharp.pixelplumbing.com/api-output#tile) operation that provides very similar logic to your sample code.

**Comment by Aarbel** [comment]
> To avoid this you could create intermediate images, perhaps as raw pixel data to avoid the PNG de/encode roundtrip if memory is not of concern.

I use my function on aws lambda which is limited to 512 Mb of RAM, but my biggest image never exceed 5Mo.
I tried with this code but didn't resolved my problem, is that what you meant about `raw pixel data` ?
```JS
    const root = sharpBigImageFileStream.resize({
        width: rootSize,
        height: rootSize,
    }).raw();
```

**Comment by Aarbel** [comment]
Moreover the "tile" documentation is quite light to really see how i can manage zooms levels (it doesn't seem to manage it), and how i can export each tile to .png files or buffers (i can't use other files formats), do you know more examples ?

**Comment by Aarbel** [comment]
Thanks again for your help !

**Comment by Aarbel** [comment]
Ok solved with just replacing this bloc
```JS
    const bigImageFileStream = await fs.createReadStream('big.png');
    const sharpBigImageFileStream = sharp();
    sharpBigImageFileStream.setMaxListeners(0);
    bigImageFileStream.pipe(sharpBigImageFileStream);
```

by this one
```JS
const rawBigImage = sharp('big.png').raw();
```
