### ISSUE TITLE
sharp-v0.24.0-electron-v76-win32-x64.tar.gz 404

### ISSUE THREAD

**Issue by cnhuye** [lovell/sharp#2075]
my env:
electron 8.0.0
nodejs 12.13
windows7 64bit

When i run yarn, i got output:
...
[4/4] Building fresh packages...
$ install-app-deps
  • please use as subcommand: electron-builder install-app-deps
  • electron-builder  version=22.3.2
  • loaded configuration  file=package.json ("build" field)
  • rebuilding native dependencies  dependencies=sharp@0.24.0 platform=win32 arch=x64
  • install prebuilt binary  name=sharp version=0.24.0 platform=win32 arch=x64
  • build native dependency from sources  name=sharp
                                          version=0.24.0
                                          platform=win32
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 5.3.3
    prebuild-install info looking for cached prebuild @ C:\Users\Administrator\AppData\Roaming\npm-cache\_prebuilds\d8d157-sharp-v0.24.0-electron-v76-win32-x64.tar.gz
    prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.24.0/sharp-v0.24.0-electron-v76-win32-x64.tar.gz
    prebuild-install http 404 https://github.com/lovell/sharp/releases/download/v0.24.0/sharp-v0.24.0-electron-v76-win32-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=8.0.0 runtime=electron arch=x64 libc= platform=win32)

  • rebuilding native dependency  name=sharp version=0.24.0
Done in 1270.60s.

**Comment by lovell** [comment]
Prebuilt binaries that are compatible with Electron 8 (ABI version 76), which was released 4 days ago, will be provided with the next release of sharp.

**Comment by abdes** [comment]
When is the next release please?

**Comment by omenking** [comment]
I just switched my package.json to version 7
```
    "electron": "^7.0.0",
```
and then I installed `npm i electron-rebuild --save-dev`

And I ran this:
```
./node_modules/.bin/electron-rebuild -p -t "dev,prod,optional"
```

and I am no longer getting errors.

**Comment by lovell** [comment]
v0.24.1 now available with prebuilt binaries for Electron ABI 76.
