### ISSUE TITLE
Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by abanoubEssam** [lovell/sharp#2078]
Sharp running correctly with node js v8.12.0 on my local machine but has an issue on my ubuntu server have same node v on my local machine

///////////////////// this is the error on my terminal ////////////////////////////////////////
 Something went wrong installing the "sharp" module
 The module '/root/events-api/node_modules/sharp/build/Release/sharp.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 67. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
- Ensure the version of Node.js used at install time matches that used at runtime
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues
WARNING: NODE_APP_INSTANCE value of '0' did not match any instance config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode

**Comment by lovell** [comment]
Please ensure the version of Node.js used at install time matches that used at runtime.

You are trying to use code installed using Node.js 8 (NODE_MODULE_VERSION 57) with a runtime of Node.js 11 (NODE_MODULE_VERSION 67).

https://nodejs.org/en/download/releases/

**Comment by abanoubEssam** [comment]
i am sure i use node version 8.12.0 and sharp ^0.23.4

**Comment by lovell** [comment]
The message "This version of Node.js requires NODE_MODULE_VERSION 67" will only be generated by Node.js 11. There are probably multiple, conflicting versions of Node.js on the machine in question.

**Comment by abanoubEssam** [comment]
how i can solve this  conflicting versions of Node.js ?

**Comment by abanoubEssam** [comment]
@lovell 
you are right. this is the exact issue
