### ISSUE TITLE
Reduce Node Module Size

### ISSUE THREAD

**Issue by dillonsvincent** [lovell/sharp#2079]
What are you trying to achieve?
I'd like to know if there is someway to reduce the package size. I'm using sharp in an aws lambda and sharp being 33mb is my largest module. It looks like most of the space is from the vendor folder, can I remove that?

**Comment by lovell** [comment]
To reduce/remove the `vendor` folder, you'll need to provide your own libvips:

https://sharp.pixelplumbing.com/install#custom-libvips
https://sharp.pixelplumbing.com/install#custom-prebuilt-binaries

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
