### ISSUE TITLE
With multiple resize() chained together only the last seems to apply.

### ISSUE THREAD

**Issue by MonkeyNinja** [lovell/sharp#2080]
Trying to produce a simple pixelise filter, my plan was to just chain two resizes together, but sharp (or possibly libvips ) seems to optimize and only apply the last resize in the chain.

What are the steps to reproduce?

```
function pixelise(){
	sharp( "input.jpg").metadata( (e,md) => {
		sharp("input.jpg").resize( { width: Math.round( md.width / 100 ) } )
                                            .resize( { width: md.width , kernel:'nearest' })
                                            .toFile("output.jpg")
	})
}

pixelise()
```

What is the expected behaviour?

Output image should be 'pixelised'.

Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?

yes

Are you able to provide a sample image that helps explain the problem?

feed any image in...

**Comment by MonkeyNinja** [comment]
I have a workaround, extra steps but it appears to work.
But it feels like a bug that the multiple resize gets ignored.

```
ffunction pixelise(){

	const img = sharp( "input.jpg")

	img.metadata( (e,md) => {
		w = Math.round( md.width / 10 )
		sharp("input.jpg")
			.resize( { width: w } )
			.raw()
			.toBuffer( { resolveWithObject: true })
		.then( ( b , inf ) => {
			sharp( b.data , { raw: { width: b.info.width , height: b.info.height , channels: b.info.channels } } )
			.resize( { width: md.width , kernel:'nearest' })
			.toFile("output.jpg")
		})
	})
}

pixelise()
```

**Comment by lovell** [comment]
The use of two pipelines to perform two resize operations is correct as the pipeline is processed when output is requested.
