### ISSUE TITLE
Not respecting strict-ssl setting

### ISSUE THREAD

**Issue by Mikeysauce** [lovell/sharp#2081]
Hi, we have a `strict-ssl=false` flag set in our .npmrc and have provided a custom `sharp_dist_base_url`, however it doesn't seem like the fetch of the binary is respecting the strict-ssl flag. Any ideas?

**Comment by lovell** [comment]
Please set the Node.js environment variable `NODE_TLS_REJECT_UNAUTHORIZED=0` if you require this, but do so with care.

https://nodejs.org/api/cli.html#cli_node_tls_reject_unauthorized_value

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
