### ISSUE TITLE
Update Lambda docs to reference Node.js 12

### ISSUE THREAD

**Issue by avin-kavish** [lovell/sharp#2082]
Thanks for the great library. The docs mention using the `nodejs10.x` lambda runtime. But your package indicates anything above 10.13 is supported. Maybe its worth changing the docs to 10.13 or greater.

https://sharp.pixelplumbing.com/install#aws-lambda

**Comment by lovell** [comment]
AWS Lambda should always provide the latest minor+patch version of a given major release line, so e.g. if you specify `nodejs10.x` you will currently get v10.19.0, which is supported by sharp.

**Comment by avin-kavish** [comment]
That's not what I mean. I mean it may confuse someone into thinking that it may not work with node 12. Does it?

**Comment by lovell** [comment]
Yes, Node.js versions 10, 12 and 13 are all supported by the latest version of sharp.

Happy to accept a PR, if you're able, to update the Lambda docs to recommend the use of `nodejs12.x` along with  the required changes to the code samples in the same section to also use the latest version 12.

The next v0.25.0 release of sharp will use N-API internally so the problem of having to compile for a specific major version of Node.js will soon go away.

**Comment by lovell** [comment]
I've updated the docs in commit 86264e7 - these will be refreshed after the next release.

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/install#aws-lambda now updated.
