### ISSUE TITLE
Issue with Nodejs 13.8.0

### ISSUE THREAD

**Issue by averri** [lovell/sharp#2084]
I'm trying to run `sharp v0.24.1`  with `Nodejs v13.8.0` and this is the error when running the application (which works fine with Nodejs v.12):
```
/home/alex/dev/src/other/strenux/strenux-api/node_modules/sharp/lib/constructor.js:34
  throw new Error(error);

Error: 
Something went wrong installing the "sharp" module

Module did not self-register.

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (/home/alex/dev/src/other/strenux/strenux-api/node_modules/sharp/lib/constructor.js:34:9)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/alex/dev/src/other/strenux/strenux-api/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/alex/dev/src/other/strenux/strenux-api/src/middleware/medias/jpg-storage.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
```

I have removed `node_modules` and `yarn.lock` and run `yarn install` with no success.

**Comment by papandreou** [comment]
I cannot reproduce this with node 13.8.0 and sharp 0.24.1, except if I `npm install` with a different major version of node than I'm running the code with:

```
$ nvm use 13.8.0
Now using node v13.8.0 (npm v6.13.6)
$ npm i sharp

> sharp@0.24.1 install /home/andreas/work/throwaway/sharpz/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

[...]

+ sharp@0.24.1
updated 1 package in 11.626s

2 packages are looking for funding
  run `npm fund` for details

$ node -e "require('sharp')"
$ nvm use 12
Now using node v12.10.0 (npm v6.10.3)
$ node -e "require('sharp')"
/home/andreas/work/throwaway/sharpz/node_modules/sharp/lib/constructor.js:34
  throw new Error(error);
  ^

Error: 
Something went wrong installing the "sharp" module

Module did not self-register.
[...]
```

Are you sure that `npm --versions` and `node --version` agree? Does `npm rebuild` fix it?

**Comment by lovell** [comment]
- Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime?

- If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

- If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

- What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

**Comment by pfcodes** [comment]
> I cannot reproduce this with node 13.8.0 and sharp 0.24.1, except if I `npm install` with a different major version of node than I'm running the code with:
> 
> ```
> $ nvm use 13.8.0
> Now using node v13.8.0 (npm v6.13.6)
> $ npm i sharp
> 
> > sharp@0.24.1 install /home/andreas/work/throwaway/sharpz/node_modules/sharp
> > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
> 
> [...]
> 
> + sharp@0.24.1
> updated 1 package in 11.626s
> 
> 2 packages are looking for funding
>   run `npm fund` for details
> 
> $ node -e "require('sharp')"
> $ nvm use 12
> Now using node v12.10.0 (npm v6.10.3)
> $ node -e "require('sharp')"
> /home/andreas/work/throwaway/sharpz/node_modules/sharp/lib/constructor.js:34
>   throw new Error(error);
>   ^
> 
> Error: 
> Something went wrong installing the "sharp" module
> 
> Module did not self-register.
> [...]
> ```
> 
> Are you sure that `npm --versions` and `node --version` agree? Does `npm rebuild` fix it?

Current version of npm is 6.13.7 as of 20 days ago

**Comment by lovell** [comment]
Please ensure there are no conflicting or globally-installed outdated versions of sharp. The output of the following commands will help determine this:
```sh
npm ls sharp
npm ls -g sharp
```

**Comment by ntelkedzhiev** [comment]
I can confirm that this is an issue when running node 13.8.0. Switching to an older version doesn't trigget the error.

**Comment by lovell** [comment]
@ntelkedzhiev Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime?

**Comment by ntelkedzhiev** [comment]
> @ntelkedzhiev Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime?

Yes.

**Comment by farshed** [comment]
Was facing the same issue. This solved my problem.
- `npm install --save-dev electron-rebuild`
- `$(npm bin)/electron-rebuild`

**Comment by farshed** [comment]
If you're on windows, run `.\node_modules\.bin\electron-rebuild.cmd` instead of the second command.

**Comment by lovell** [comment]
There's existing help for Electron users at https://sharp.pixelplumbing.com/install#electron

**Comment by lovell** [comment]
@averri Were you able to make any progress with this?

**Comment by averri** [comment]
I have reverted the project to Node 12.16.0. It could be reopened again if someone find a reproducible steps.
