### ISSUE TITLE
Adjusting shadows/highlights

### ISSUE THREAD

**Issue by untitledlt** [lovell/sharp#2089]
Is it possible to brighten shadows or darken highlights?

I tried to look into documentation but wasn't able to find anything about such functionality.
Not sure how difficult is to implement it but i would be great addition to this library!

**Comment by lovell** [comment]
Hi, did you see the [normalise](https://sharp.pixelplumbing.com/api-operation#normalise) operation?

**Comment by untitledlt** [comment]
Yes, but it only accepts boolean.
I would like to have an option to specify how much to brighten shadows and/or highlights.
Or am I missing something here?

**Comment by lovell** [comment]
The future possible enhancement discussed at #1066 will probably provide what is required here so let's track any progress on that issue.
