### ISSUE TITLE
preinstall.sh works on Amazon Linux 2015.03 if you modify the release match

### ISSUE THREAD

**Issue by bradisbell** [lovell/sharp#209]
I've found your preinstall.sh script to work great on the 2015.03 Beanstalk AMI, but only if modified:

```
    elif [ -f /etc/system-release ]; then
      # Probably Amazon Linux
      RELEASE=$(cat /etc/system-release)
      case $RELEASE in
        "Amazon Linux AMI release 2015.03")
```

Also, prior to this modification there was no error message for unsupported OS.  The only output was:
> Could not find libvips using a PKG_CONFIG_PATH of ...

**Comment by lovell** [comment]
Thanks for confirming Brad - feel free to submit a PR if you're feeling lucky - there's probably a missing `*)` wildcard matcher for unsupported flavours of Amazon Linux.

**Comment by lovell** [comment]
Commit https://github.com/lovell/sharp/commit/b77877c83ddbd05d84f5ff754c2b2ba61014420a added the new Amazon Linux. Are you able to re-test?

**Comment by bradisbell** [comment]
Not at the moment, but I'll see if I can spin up another instance soon and get back to you.  From the looks of your change, I'm sure it will work just fine.

**Comment by lovell** [comment]
Closing this for now - feel free to re-open if there are still problems with Amazon Linux 2015.03.
