### ISSUE TITLE
Change jpeg quality default to 100

### ISSUE THREAD

**Issue by lcswillems** [lovell/sharp#2090]
I think the default jpeg quality should be 100, i.e. not deteriorating the input image. In my case, I thought by default, images where not deteriorated, but I discovered it wasn't the case.

**Comment by lovell** [comment]
Hi, did you see the default JPEG quality setting of 80 is documented at https://sharp.pixelplumbing.com/api-output#jpeg ?

If image deterioration is of concern then the lossy JPEG format is probably the wrong choice. Even at "100% quality" an output image will be missing data from the input image. Perhaps try a lossless format such as PNG.

**Comment by lcswillems** [comment]
Yes, I saw this page. It is how I learnt default was 80.

In my case, I do a image upload API. When user uploads a JPEG, I don't want to alter its quality. And I would say that a lot of people using `.jpeg` uses with the `force: false` option to only control format of the file, but I might be wrong.

**Comment by lovell** [comment]
> I don't want to alter its quality

Sadly JPEG images do not contain information about the "quality" with which they were originally created, so a decode/encode round-trip will always have to specify a desired new output quality, and you will always lose information in the round-trip regardless of quality.

(It is technically possible to reverse-engineer an approximate "quality" if certain assumptions are made about which Huffman tables were originally used, but the increasing variance of these means it's not very reliable.)

**Comment by lcswillems** [comment]
> You will always lose information in the round-trip regardless of quality

Okay, thank you I didn't know. In this case, it makes sense to have a default of 80.

Question: If I upload a JPEG with quality 80, and then transform it into a JPEG of quality 100 with `.jpeg({quality: 100})`, will the output JPEG of quality ~80?

**Comment by lovell** [comment]
> If I upload a JPEG with quality 80, and then transform it into a JPEG of quality 100 with .jpeg({quality: 100}), will the output JPEG of quality ~80?

It depends on the images, but approximately yes.

**Comment by lcswillems** [comment]
Okay, thank you!

**Comment by hafiedh** [comment]
when we called jpeg({quality: 50}) what function called in libvips?
