### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by pierreinglebert** [lovell/sharp#21]
I ran a batch using sharp on ~1000 files and it ended using >300MB ram.

I created a little [gist](https://gist.github.com/pierreinglebert/112094640) to "demonstrate" it, it download a large image and creates 800 thumbs at different sizes.
On my mbp, when finished, it takes 120MB ram (more if i increase the number of generated thumbs).

**Comment by puzrin** [comment]
FYI, we had to process 650000 of 800x600 images and `libvips` segfaulted after 5 min until disabled `liborc` in `configure`.

It certaintly worth to automate libvips build on install or write instructions to README.

**Comment by lovell** [comment]
Thanks @puzrin - are you able to provide more details of the liborc-caused segfault, ideally with a stacktrace, over at #172.
