### ISSUE TITLE
Is the licensing correct? (was: License)

### ISSUE THREAD

**Issue by pierreinglebert** [lovell/sharp#210]
Hi there, it's been quite a while.
I think your forgot something in your license file.
https://github.com/lovell/sharp/blob/master/LICENSE#L179

**Comment by lovell** [comment]
It's never too late
to remove boilerplate!
(Thank you for taking the time
to create a bug report that rhymes.)

**Comment by lovell** [comment]
The boilerplate is in the "APPENDIX"
after "END OF TERMS AND CONDITIONS".
This means it's not considered legally binding
amongst IP lawyers and logicians.

**Comment by lovell** [comment]
I believe the current licensing is legally correct,
but please re-open if this remains a defect.
