### ISSUE TITLE
Resize just crops the image

### ISSUE THREAD

**Issue by vijilvpillai007** [lovell/sharp#2100]
We are having static html pages hosted inserver. I need to take the screenshots after loading the page in a browser. I am using puppeteer for the same . When I am taking the page screeenshots using puppeteer its taking a full screenshot. But I need that image to be resized to 200*250. What is the best way to do the same without losing the image quality using sharp.

I am currently using the below code.

`buffer = await sharp(await getScreenshotBuffer(true))
                    .resize(200, 250, {
                        fit: sharp.fit.cover,
                        position: "top",
                        background: pageBackgroundColor,
                    })
                    .toBuffer();`

The above code works for some pages but for some pages it just crops instead if resizing.
Appreciate your help on the same.

**Expected image**

![expected](https://user-images.githubusercontent.com/46382776/75234701-0e749180-57e1-11ea-8ad0-e08e41542efc.PNG)

**Actual Image**

![actual](https://user-images.githubusercontent.com/46382776/75234818-4085f380-57e1-11ea-8c64-fcf0a4e2d6d3.PNG)

**Comment by vijilvpillai007** [comment]
This was previously working with  sharp v0.21.1

**Comment by lovell** [comment]
Hi, the code sample provided will output a 200x250 image but the "expected image" is 908x639, which is of a different aspect ratio and dimensions.

Please can you provide a complete, standalone, worked example with real input and output images.

**Comment by vijilvpillai007** [comment]
That images were samples. I cannot send the actual images due to client restrictions. But I figured out the issue. The headless chrome which I used had a viewport of `width: 1920, height: 1080` . I changed the same to `width: 1440, height: 1440 ` and then the same code was able to resize the image to 200*250. This was some issue with the source image dimensions.
