### ISSUE TITLE
"Input file contains unsupported image format" running in Docker container

### ISSUE THREAD

**Issue by mbklein** [lovell/sharp#2102]
At first glance, I thought this might be related to #2003, but the circumstances are different enough to warrant a separate look. I have a [project](https://github.com/nulib/node-pyramid) that implements one simple [pipeline](https://github.com/nulib/node-pyramid/blob/master/pyramid.js#L7-L36):

1. Fetch a TIFF from an Amazon S3 bucket to a temp file.
2. Load that file into sharp, convert it to a 15k-max-per-dimension, JPEG compressed, tiled pyramid TIFF, output to a buffer.
3. Send that buffer back to a different S3 bucket.

It runs inside a Docker container on Amazon Elastic Container Service, because it needs too much temporary disk space to run in a Lambda. The Docker container was, for a long time, based on the `node:11-alpine` base image (NodeJS 11.x running on Alpine Linux), but in the process of trying to fix this issue, I've changed it to `node:13-buster` (NodeJS 13.8.0 running on Debian Buster).

The processor has been chugging along nicely for some time, but yesterday, I noticed that there were 16 images that it failed to convert. The error it was throwing was `Input file contains unsupported image format`.

Here comes the weird part. When I run the node application on my Mac, it processes the outlier TIFFs just fine. When I run the _Docker container_ on my Mac, it throws the error. Both are running the same version of NodeJS with the same version of sharp and the prebuilt VIPS installed by sharp's installer. Obviously, one of them is compiled for `Darwin` and the other for `Linux x86_64`.

In an effort to narrow down the issue, I decided to see if Alpine was the problem, so I rebuilt the container on Debian Buster. This time, the containerized version was able to read 13 of the 16 outliers, but 3 still failed with `Input file contains unsupported image format`. 1 of those 3 works under Docker on my Mac using the Buster-based container; the other two don't.

I'll try to attach one of the failing test images later, but I have to get my employer to give the OK to share it. In the meantime, I'm not sure what I should be looking at next. Could this be a resource issue of some kind? RAM? CPU? ulimits?

**Comment by lovell** [comment]
Please can you provide a sample image and complete, standalone code to trigger this error.

**Comment by mbklein** [comment]
Welp, this one is on me. In whittling down my app to create a test case, I discovered that in some very narrow circumstances based on the size of the file and the chunk size of the download, the function responsible for downloading the source image was resolving its promise before the file was completely written to temp storage and closed. In this case, sharp would end up trying to read an incomplete file and report an error. I'm leaving this open so you can read this resolution, but feel free to close it as there's nothing to fix.
