### ISSUE TITLE
Improve docs relating to raw pixel output and extracting alpha (or, any other channel)

### ISSUE THREAD

**Issue by rpav** [lovell/sharp#2104]
First off, great package!  So much easier to use than ImageMagick.

### What are you trying to achieve?

I'm writing a bunch of tile-related utilities.  One of these splits tilemaps, another tests if any image is blank (every pixel has a=0).  You can probably see where this is going.

1. Raw doesn't seem to document order; metadata and info do not seem to indicate order.  Presumably channels 0-3 are RGBA respectively, but it's unclear if this is the order in the buffer, if they're byte-oriented, little-endian 32-bit uints, etc.

2. It doesn't seem possible to extract just the alpha channel using `3` or (presumably better) `"alpha"`.  This would be useful.

3. Extracting any channel doesn't seem to provide matching `channels = 1` in `info`, as the documentation indicates. I may be misunderstanding how one or more of these things work.

### Have you searched for similar questions?

Results returned by "extract alpha" or "raw order" do not seem relevant (or completely answer this).

### Are you able to provide a standalone code sample that demonstrates this question?

```js
// Why do these not work?
sharp(..).extractChannel(3) ...
sharp(..).extractChannel('alpha')

// Additionally, info provided does not actually seem to have `channels: 1` as 
// indicated by the docs
sharp("somefile.png")
  .extractChannel('red')
  .toBuffer((info, data, err) => {
    // info.channels == 3
  })
```

### Are you able to provide a sample image that helps explain the question?

Any png file should be relevant.  PNG files with an alpha channel should be relevant to alpha extraction.

**Comment by lovell** [comment]
Hello, yes, completely agree that the docs for the raw could do with expanding and examples:

> "Force output to be raw, uncompressed uint8 pixel data."
> https://sharp.pixelplumbing.com/api-output#raw

The number of channels in the output is based on the input, so e.g. 3 channels will be RGB and 4 channels will be RGBA.

If you always want RGBA then [ensureAlpha](https://sharp.pixelplumbing.com/api-channel#ensurealpha) is your friend.

When `extractChannel` is used then you should get a single channel so I suspect there's a bug in the reported channel count, thanks for reporting this.

**Comment by lovell** [comment]
Commit 258c9e8 improves the documentation relating to raw pixel output, especially single-channel, thanks for reporting this.

The default colourspace is RGB so if you need single channel greyscale output, use something like the following:

```javascript
sharp("somefile.png")
  .extractChannel('red')
  .toColourspace('b-w')
  .raw()
  .toBuffer((err, data, info) => {
    // info.channels === 1
  });
```

**Comment by lovell** [comment]
v0.25.0 is now available and the docs at https://sharp.pixelplumbing.com/api-output#raw have been updated.
