### ISSUE TITLE
png.toBuffer() causes high CPU usage

### ISSUE THREAD

**Issue by kingjerod** [lovell/sharp#2108]
When I try to convert a PNG to a buffer, my CPU usage goes from around 10-20% to over 100%. I'm doing this inside a Docker container and monitoring it from host with `docker stats`. I just need to take a png and upload to S3.

What are you trying to achieve?
Convert PNG to Buffer so I can upload it to S3.

Have you searched for similar questions?
Yes. Seems like this might be an issue inflate_fast? https://github.com/lovell/sharp/issues/2074

Are you able to provide a standalone code sample that demonstrates this question?
I just run this in a Docker container:
```
  for (let i = 1; i <= 300; i++) {
    console.log("On iteration " + i);
    sharp({
      create: {
        width: 500,
        height: 500,
        channels: 4,
        background: { r: 255, g: 0, b: 0, alpha: 0.5 }
      }
    }).png().toBuffer();
    await Bluebird.delay(10);
  }
```

Are you able to provide a sample image that helps explain the question?
Not needed.

**Comment by lovell** [comment]
This code is spawning up to 300 concurrent pipelines, hence a maxed-out CPU. Perhaps you meant to await the Promise returned by `toBuffer`?

```diff
-    sharp({
+    await sharp({
```

**Comment by kingjerod** [comment]
Changed to use await and I still go from 0 -> 80% CPU.

**Comment by kingjerod** [comment]
Does the same thing with webp.

**Comment by lovell** [comment]
Do you see a similar CPU utilisation without the use of Docker?

**Comment by kingjerod** [comment]
Created a t2.micro on AWS with ubuntu. Just installed NodeJS 12 + sharp. Checked with top:

![image](https://user-images.githubusercontent.com/2287252/75634092-5f103400-5bbf-11ea-9cfb-619e390a0775.png)

Tried both webp and png test:
```
const Bluebird = require("bluebird");
const sharp = require("sharp");
const image = {
    create: {
        width: 500,
        height: 500,
        channels: 4,
        background: { r: 255, g: 0, b: 0, alpha: 0.5 }
    }
};
async function pngTest() {
    console.log("Starting png test...");
    await Bluebird.delay(500);
    const start = Date.now();
    for (let i = 1; i <= 2000; i++) {
        console.log("On iteration " + i);
        await sharp(image).png().toBuffer();
    }
    console.log("Done. Total time: " + Math.round((Date.now() - start) / 1000) + " seconds");
}
async function webPTest() {
    console.log("Starting webp test...");
    await Bluebird.delay(500);
    const start = Date.now();
    for (let i = 1; i <= 2000; i++) {
        console.log("On iteration " + i);
        await sharp(image).webp().toBuffer();
    }
    console.log("Done. Total time: " + Math.round((Date.now() - start) / 1000) + " seconds");
}
pngTest();
```

**Comment by kingjerod** [comment]
Is this just the performance of vips? When I do a `vips copy svg png` in Docker it reaches over 70% CPU.

**Comment by lovell** [comment]
70% CPU is fairly efficient, a lower value might indicate being I/O bound. You'll need to profile your code to find out exactly what is taking most of the time, but there are a couple of settings that trade lower CPU time for larger output file sizes.

- For PNG images you can alter the `compressionLevel` setting - https://sharp.pixelplumbing.com/api-output#png
- For WebP images you can alter the `reductionEffort` setting - https://sharp.pixelplumbing.com/api-output#webp
