### ISSUE TITLE
Strip metadata while leaving ICC intact

### ISSUE THREAD

**Issue by OCannings** [lovell/sharp#2111]
It would be great if we could keep the image filesizes small by removing the metadata but ensure they're rendered correctly by optionally keeping the icc profile intact. I have found some sharp generated images look slightly different than their originals when rendered in Firefox on MacOS 10.14.6 due to the missing icc profile.

An optional list of metadata fields could be supplied to prevent them from being stripped automatically, e.g. `.withMetadata({ only: ['icc'] })`

Or a variation of https://github.com/lovell/sharp/issues/1324 which allows you to indicate that you'd like to use the icc profile already present in the image could also work.

A workaround which achieves the result I'm looking for is to use `.withMetadata()` and then pass the image through Imagemagick using `convert in.jpg -thumbnail '100%x100%' out.jpg` because the `-thumbnail` flag strips metadata but keeps icc:

> Before IM v6.5.4-7 the "-thumbnail" would strip ALL profiles from the image, including the ICC color profiles. From this version onward the color profiles will be preserved. If the color profile is not wanted then "-strip" all profiles.
http://www.imagemagick.org/Usage/thumbnails/

Some example images:
With all metadata stripped (default Sharp behaviour):
https://d1jzyhh1s7m7ri.cloudfront.net/optimise/marley-dress-in-pine-green.jpeg?quality=90&signature=eac836c956ede87b3761881ca916eb907a2827d2896378ab09216a3febb5c9b3&src=https%3A%2F%2Fbec2df9eb90bb6604cfc-660d71a7a33bc04488a7427f5fddcedf.ssl.cf3.rackcdn.com%2Fuploads%2Fproduct_image%2Fphoto%2F5b9a2703dd232e644eea6803%2Fxlarge_7V0A6464_C.jpg&width=275

![without-metadata](https://user-images.githubusercontent.com/950193/75673691-70b71180-5c7b-11ea-8295-e9bb009fc92b.jpeg)

With metadata intact:
https://d1v6u7haqkchb4.cloudfront.net/optimise/marley-dress-in-pine-green.jpeg?quality=90&signature=8187638eeaba4787c2bfef021c53a7d61f76e7ae434bc3731ab709845a986a18&src=https%3A%2F%2Fbec2df9eb90bb6604cfc-660d71a7a33bc04488a7427f5fddcedf.ssl.cf3.rackcdn.com%2Fuploads%2Fproduct_image%2Fphoto%2F5b9a2703dd232e644eea6803%2Fxlarge_7V0A6464_C.jpg&width=275

![with-metadata](https://user-images.githubusercontent.com/950193/75673681-6bf25d80-5c7b-11ea-8c09-97599bb0f75d.jpeg)

And here's a screenshot showing the difference between the two on Firefox on MacOS 10.14.6:

![Screenshot 2020-03-02 at 11 50 55 am](https://user-images.githubusercontent.com/950193/75674011-21bdac00-5c7c-11ea-8efe-0cff289ef7ec.png)

**Comment by lovell** [comment]
I think you might have posted these example images the wrong way round as the first has an ICC profile where the second does not.

> "I have found some sharp generated images look slightly different than their originals when rendered in Firefox on MacOS 10.14.6 due to the missing icc profile."

Sadly Firefox doesn't handle some embedded ICC profiles very well based on its underlying use of qcms - http://www.color.org/browsertest.xalter is a good example you can try in a few different browsers to prove this.

sharp relies on lcms2 and will correctly convert to non-linear sRGB using the embedded linear RGB profile so the output will be closer to the original colour intent.

**Comment by OCannings** [comment]
You're right, apologies for that. I have updated my post to correct the order of the images.
Thanks for sharing the browser test link, that's really interesting.

I believe my feature request still stands, given retaining the icc profile appears to make the images render consistently across all browsers. However, Firefox sadly has such a small usage share that it may be possible to ignore it.

**Comment by lovell** [comment]
Thanks, #1323 is the existing future possible enhancement for this so let's track it there.
