### ISSUE TITLE
Error: /tmp/upload_13xxxxx unable to open for read backend     | unix error: No such file or directory

### ISSUE THREAD

**Issue by webface** [lovell/sharp#2113]
I am developing in a dockerized container. Plugin works 70% of the time. Sometimes it throws this error and crashes my application
```
[Error: /tmp/upload_1367b9827347cc36d9a19d31b42bf989: unable to open for read
backend     | unix error: No such file or directory
backend     | ]
```
What is the output of running `npx envinfo --binaries --languages --system --utilities`?
`npx: installed 1 in 7.634s`
What are the steps to reproduce?
I'm running this code
```
const { file } = recordData;
	const fileName = uuid();
	const fileType = await FileType.fromFile(file.path);
	console.log('fileType',fileType);
	const syncMv = util.promisify(mv);
	sharp(file.path).resize(320, 240).toFile(`public/images/${fileName}-320x240.${fileType.ext}`, (err, info) => {
		if (err)
			throw (err);
		console.log('info', info);
	})
	const resp = await syncMv(file.path, `public/images/${fileName}.${fileType.ext}`);
	const image = `${fileName}.${fileType.ext}`;
	const updatedRecord = await record.update({ image });
```
What is the expected behaviour?
For the image to resize everytime with no errors
Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?

**Comment by lovell** [comment]
Hi, it might not be the reason, but there's a possible race condition in your code as nothing is waiting for `toFile()` before continuing.

Try something like the following:
```diff
-	sharp(file.path).resize(320, 240).toFile(`public/images/${fileName}-320x240.${fileType.ext}`, (err, info) => {
+	await sharp(file.path).resize(320, 240).toFile(`public/images/${fileName}-320x240.${fileType.ext}`);
```

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
