### ISSUE TITLE
Wrong number of arguments

### ISSUE THREAD

**Issue by danbulant** [lovell/sharp#2114]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?

**yes**

Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime?

**I couldn't even install it, so couldn't run it**

If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

**Non-sudo**

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

**Default options of npm**

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

**See https://filebin.net/29vzcx8s9c6cywe5**
(log)

What is the output of running `npx envinfo --binaries --languages --system --utilities`?

```
  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Memory: 2.22 GB / 11.60 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 13.9.0 - /usr/bin/node
    Yarn: 1.22.0 - /usr/bin/yarn
    npm: 6.13.7 - /usr/bin/npm
  Utilities:
    Make: 4.2.1 - /usr/bin/make
    GCC: 8.3.0 - /usr/bin/gcc
    Git: 2.20.1 - /usr/bin/git
    FFmpeg: 4.1.4 - /usr/bin/ffmpeg
  Languages:
    Bash: 5.0.3 - /usr/bin/bash
    Perl: 5.28.1 - /usr/bin/perl
    PHP: 7.3.14 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.7.3 - /usr/bin/python3
    Ruby: 2.5.5 - /usr/bin/ruby
```

**Comment by danbulant** [comment]
Here is live recording:
https://asciinema.org/a/307500

**Comment by lovell** [comment]
Support for Node.js 13 was added in sharp v0.23.2.

https://sharp.pixelplumbing.com/changelog#v0232---28supthsup-october-2019

**Comment by danbulant** [comment]
Oh so that means the package is using older version? I'll try updating it then.

Thanks!
