### ISSUE TITLE
Error occur when checking format supported for HEIC/HEIF

### ISSUE THREAD

**Issue by psteh** [lovell/sharp#2115]
Trying to install sharp on Docker Lambda for HEIC/HEIF support

installed libde265-1.0.5
installed libheif-1.6.2
installed vips-8.9.1

`npm install sharp`

```
> sharp@0.23.4 install /home/aws-lambda/s3-resize-upload/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Detected globally-installed libvips v8.9.1
info sharp Building from source via node-gyp
make: Entering directory `/home/aws-lambda/s3-resize-upload/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
  CXX(target) Release/obj.target/sharp/src/sharp.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  SOLINK_MODULE(target) Release/obj.target/sharp.node
  COPY Release/sharp.node
make: Leaving directory `/home/aws-lambda/s3-resize-upload/node_modules/sharp/build'
npm WARN s3-resize-upload@1.0.0 No description
npm WARN s3-resize-upload@1.0.0 No repository field.

+ sharp@0.23.4
added 84 packages from 168 contributors and audited 178 packages in 18.196s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

But when checking for format supported, got

```
Something went wrong installing the "sharp" module

libvips-cpp.so.42: cannot open shared object file: No such file or directory

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues
```

**Comment by lovell** [comment]
Did you see #2000?

**Comment by psteh** [comment]
Sorry don't quite understand from it.
From this comment you mean I need to to have to have the installed libraries (`libde265-1.0.5`, `libheif-1.6.2`, `vips-8.9.1`) same directory with the `build/Release/sharp.node`?

Sorry and  thank you for your explaination

> https://github.com/lovell/sharp/blob/master/binding.gyp#L160 ensures the compiled `build/Release/sharp.node` file always contains the `vendor/lib` location in its rpath so it might "just work" if you put other shared libraries in the same directory.
> 
> Another option might be setting `LD_LIBRARY_PATH` - good luck!

**Comment by lovell** [comment]
If you're providing a globally-installed libvips etc at install time then you'll need to ensure these are also made available at runtime. Did you see the https://github.com/smcguinness/SharpLayer repo linked to in #2000?

**Comment by psteh** [comment]
If I got it correctly, that means sharp couldn't detect the installed libraries when the function is called? 

If I could put it together into Sharp folder, I could just deploy to AWS Lambda all together?

Sorry if I got it wrongly again.

**Comment by psteh** [comment]
Followed the steps from #2000, got result as below
```
libvips-cpp.so.42 => /usr/local/lib/libvips-cpp.so.42 (0x00007f3a16d45000)
libvips.so.42 => /usr/local/lib/libvips.so.42 (0x00007f3a166aa000)
```
How can I have it to point to `/vendor/lib` so I can package it and deploy to AWS Lambda?
Sorry if this is stupid question.

**Comment by psteh** [comment]
Resort to another library to convert HEIC to JPG [heic-convert](https://www.npmjs.com/package/heic-convert)

Closing this.
