### ISSUE TITLE
fatal error: 'stdlib.h' file not found #include_next <stdlib.h>

### ISSUE THREAD

**Issue by danielkov** [lovell/sharp#2116]
Hello 👋

I'm having trouble installing `sharp` at the moment. I can remember it working a while ago, so I started with a clean slate, deleted `node_modules`, tried with `yarn` and `npm` install and none of them worked out. Here's some info:

**What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?**

[2020-03-05T20_30_59_589Z-debug.log](https://github.com/lovell/sharp/files/4295046/2020-03-05T20_30_59_589Z-debug.log)

**What is the output of running `npx envinfo --binaries --languages --system --utilities`?**

```txt
  [4mSystem:[0m
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 1.13 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  [4mBinaries:[0m
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  [4mUtilities:[0m
    Make: 3.81 - /Library/Developer/CommandLineTools/usr/bin/make
    GCC: 4.2.1 - /Library/Developer/CommandLineTools/usr/bin/gcc
    Git: 2.21.0 - /Library/Developer/CommandLineTools/usr/bin/git
  [4mLanguages:[0m
    Bash: 3.2.57 - /bin/bash
    Go: 1.10 - /usr/local/go/bin/go
    Java: 1.8.0 - /usr/bin/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.3.11 - /usr/bin/php
    Python: 2.7.17 - /usr/local/bin/python
    Ruby: 2.6.3 - /usr/bin/ruby
    Rust: 1.9.0 - /Users/danielkov/.cargo/bin/rustup
```

**Comment by lovell** [comment]
Support for Node.js 12 was added in sharp v0.22.1

https://sharp.pixelplumbing.com/changelog#v0221---25supthsup-april-2019

**Comment by danielkov** [comment]
I managed to mix and match NodeJS and `sharp`  versions finally. Another thing that helped is that I opted out of the MacOS Beta, so a prebuilt version could be pulled instead of having to have it built on my machine. I see that `"engines"` is set in `package.json`. I wonder why npm didn't warn me of incompatible versions.
