### ISSUE TITLE
limitInputPixels gives error when used with streams

### ISSUE THREAD

**Issue by kaYcee** [lovell/sharp#2118]
Version: **v0.25.0**

What are the steps to reproduce?
Declare a transformer to be used in a pipeline, with `limitInputPixels` set as follows,
based on a gist given [here](https://sharp.pixelplumbing.com/api-constructor)

```
const readableStream = fs.createReadStream(__dirname + "/sample.jpg");
const writableStream = fs.createWriteStream(__dirname + "/sample_out.jpg");

var transformer = sharp({limitInputPixels: false})
  .resize(300)
  .on('info', function(info) {
    console.log('Image height is ' + info.height);
  });

readableStream.pipe(transformer).pipe(writableStream);
```

What is the expected behaviour?
**Conversion without error.**

What is the error?
> undefined:0
> 
> Error: Input file is missing
> 

What is the output of running `npx envinfo --binaries --system`?
 

>  System:
>     OS: macOS 10.15.3
>     CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
>     Memory: 90.81 MB / 32.00 GB
>     Shell: 5.7.1 - /bin/zsh
>   Binaries:
>     Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
>     Yarn: 1.22.1 - ~/.nvm/versions/node/v10.15.3/bin/yarn
>     npm: 6.14.2 - ~/.nvm/versions/node/v10.15.3/bin/npm

Note:
This used to work when `limitInputPixels` was called in the chain (v 0.24.1 and older).

**Comment by lovell** [comment]
Hi, thanks for reporting this and apologies for the unintentionally-breaking change. Commit 4894c10 fixes this by ensuring input option detection is consistent (and takes advantage of existing unit tests that already covered this logic in the composite operation).

This will be in the next release, v0.25.2.

**Comment by lovell** [comment]
v0.25.2 is now available.
