### ISSUE TITLE
vips__region_start: start function failed for image

### ISSUE THREAD

**Issue by Zewy** [lovell/sharp#212]
Every time that image is resized sharp crashes for me.
Here is the image if you like to test it for your self.
![brokenimg](https://cloud.githubusercontent.com/assets/4577655/7491205/5dc0460c-f3e7-11e4-911b-b4c9f12b716f.jpg)

```events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Error: VipsJpeg: Corrupt JPEG data: 66 extraneous bytes before marker 0xc0
VipsJpeg: Corrupt JPEG data: 66 extraneous bytes before marker 0xc0
VipsJpeg: Corrupt JPEG data: 66 extraneous bytes before marker 0xc0
VipsJpeg: Quantization table 0x01 was not defined
vips__region_start: start function failed for image broken.jpg
VipsRegion: valid clipped to nothing
VipsRegion: valid clipped to nothing
VipsRegion: valid clipped to nothing

    at /home/node/node_modules/sharp/index.js:566:30
vips warning: VipsJpeg: read gave 1 warnings
vips warning:
vips warning: VipsJpeg: read gave 1 warnings
vips warning:
vips warning: VipsJpeg: read gave 1 warnings
vips warning:

**Comment by lovell** [comment]
Hi Zewy, it looks like Github also had a problem processing this image.

What program, if any, is able to decompress the image data? What is the result of running `identify -verbose filename.jpg`? Are you able to post the erroneous file using a different hosting service that doesn't try to pre-process it?

**Comment by Zewy** [comment]
Sorry don't have that command on my Debian 7.

here is the file http://www.filedropper.com/brokenimg

that site have a lot off banners just a heads up.

**Comment by lovell** [comment]
Looks like corrupt compressed data. Which program *is* able to open this file?

**Comment by Zewy** [comment]
Is there a way to save Sharp from crashing or detect a broken image?
Tried some programs none worked but Gimp 2.8.14 showed this error.
```
Corrupt JPEG data: 66 extraneous bytes before marker 0xc0

Quantization table 0x01 was not defined

**Comment by Zewy** [comment]
Can you add a event to sharp for .on('error') something like this
```
sharp('brokenimage.jpg').rotate().resize(200).webp().pipe(res).on('error', function(e) {
    console.error('Sharp Error: '+ e);
  });

**Comment by lovell** [comment]
Yes, if you're using Streams you'll need to listen for the `error` event - your example should work.

See also a similar example I added to the README in commit https://github.com/lovell/sharp/commit/bd96a49de6259faadfdaaeb86fd6ee5758898978

**Comment by Zewy** [comment]
I can't get it to work some how
```
var cfg = { http_port: 8888 }
sharp = require('sharp');
var file = 'brokenimg.jpg';

httpServer = require('http').createServer().listen(cfg.http_port, function(){
  console.log(' HTTP on port '+ cfg.http_port);
});

httpServer.on('request', function(req, res) {
  res.writeHead(200, {'Content-Type': 'image/webp'});
  sharp(file).rotate().resize(200).webp().pipe(res).on('error', function(e) {
    console.error('Sharp Error: '+ e);
    res.writeHead(404);
    res.end("");
  });
});

httpServer.on('error', function(e) {
  console.error('httpServer Error: '+ e);
});
```

I get this error
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Error: VipsJpeg: Corrupt JPEG data: 66 extraneous bytes before marker 0xc0
VipsJpeg: Corrupt JPEG data: 66 extraneous bytes before marker 0xc0
VipsJpeg: Corrupt JPEG data: 66 extraneous bytes before marker 0xc0
VipsJpeg: Quantization table 0x01 was not defined
vips__region_start: start function failed for image brokenimg.jpg
VipsRegion: valid clipped to nothing
VipsRegion: valid clipped to nothing
VipsRegion: valid clipped to nothing

    at /home/node/node_modules/sharp/index.js:566:30
vips warning: VipsJpeg: read gave 1 warnings
vips warning:
vips warning: VipsJpeg: read gave 1 warnings
vips warning:
vips warning: VipsJpeg: read gave 1 warnings
vips warning:

**Comment by lovell** [comment]
Ah ha, you're connecting the `error` listener to the output HTTP Stream, as returned by `pipe(res)`, rather than the instance of sharp.

You'll need to swap the order of `...webp().pipe(res).on('error', ...` to be more like `...webp().on('error', ... ).pipe(res)...`

**Comment by Zewy** [comment]
Did't think of that I did it like that. Can you add that to a new http example that fix a lot of crash problems :)
