### ISSUE TITLE
Issue with corrupt image

### ISSUE THREAD

**Issue by usmanikramcb** [lovell/sharp#2121]
What are you trying to achieve?
We are trying to make thumbnail of an image using sharp. But that image is corrupt (can view that image in browser and in preview [OSX] though).
When i use this function:

`const data = await sharp(input)
  .toFormat('png')
  .toBuffer();`

Instead of returning be `Sharp` it return me this:

```
{ format: 'jpeg',
        width: 116,
        height: 99,
        channels: 3,
        premultiplied: false }
```

I tried to fix this image using this tool: https://github.com/codepo8/image-data-cleaner
And then provided it to sharp like mentioned above for resizing then it works fine.

So my question is, is there a way sharp can solve this problem? I am using version `0.25.1`
 

Have you searched for similar questions?
 Yes i searched but could't find any solution

Are you able to provide a minimal, standalone code sample that demonstrates this question?

```
const config = {
      jpeg: {
        background: {
          r: 255,
          g: 255,
          b: 255,
          alpha: 1,
        },
        options: {
          quality: 90,
          chromaSubsampling: '4:4:4',
          progressive: true,
        },
        mimetype: 'image/jpeg',
        fileExtension: 'jpg',
      },
      png: {
        background: {
          r: 0,
          g: 0,
          b: 0,
          alpha: 0,
        },
        options: { progressive: false, compressionLevel: 9 },
        mimetype: 'image/png',
        fileExtension: 'png',
      },
      webp: {
        background: getBackgroundWebP(renderOptions.transparent),
        options: {
          quality: 90,
          alphaQuality: 70,
        },
        mimetype: 'image/webp',
        fileExtension: 'webp',
      },
    };

    Sharp.cache(false);

    let sharp = await Sharp(data, { failOnError: false });

sharp = await sharp
      .sequentialRead()
      .resize(resizeWidth, resizeHeight, {
        fit: renderOptions.maxSize ? 'inside' : 'contain',
        background: config[type].background,
      })
      .flatten(!renderOptions.transparent ? { background: config[type].background } : false)
      .jpeg(config.jpeg.options)
      .png(config.png.options)
      .webp(config.webp.options);

buffer = await sharp.toFormat(type).toBuffer();

```

Are you able to provide a sample image that helps explain the question?

![1389414](https://user-images.githubusercontent.com/47825518/76545757-9cf83c80-648a-11ea-8639-9cc5bd42cc9d.png)

**Comment by lovell** [comment]
Hi, I can confirm the image is corrupt (invalid IDAT length) but am unable to reproduce the same output, instead getting an error as expected.

Are you sure you're using the latest v0.25.1 as the code sample includes a call to `sequentialRead()` that was deprecated in v0.24.0 and removed in v0.25.0?

**Comment by usmanikramcb** [comment]
@lovell Thank you for your comment.
Yes image is corrupt but if i clean same image using https://github.com/codepo8/image-data-cleaner then it works fine with above code.

Yes i am using v0.25.1. I have removed `sequentialRead()` from my code now (it didn't gave me any error, i don't know why). But still no luck

**Comment by lovell** [comment]
Thanks. We won't be able to get sharp/libvips to read this corrupt image, however I'm concerned about the output you're receiving instead of an error. Please can you confirm that using exactly this code:
```
const data = await sharp(input) .toFormat('png') .toBuffer();
```
you are receiving this value of `data`:
```
 { format: 'jpeg',
        width: 116,
        height: 99,
        channels: 3,
        premultiplied: false }
```

where `input` is the data of the example image provided: https://user-images.githubusercontent.com/47825518/76545757-9cf83c80-648a-11ea-8639-9cc5bd42cc9d.png

If not, please can you create a small repo with code, image(s) and a `package.json` to enable someone else to reproduce this.

**Comment by usmanikramcb** [comment]
Not able to reproduce now. May be i am doing something wrong.
You can close this issue for now. If i face this again will create a repo for your.
But thanks for quick response.
