### ISSUE TITLE
PNG to WEBP silently fail and create 0 byte image

### ISSUE THREAD

**Issue by service-paradis** [lovell/sharp#2124]
### Are you using the latest version? 
`Yes`

### Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
```
$ npm ls sharp
-- sharp@0.25.1
$ npm view sharp dist-tags.latest
0.25.1
```

### What are the steps to reproduce?

I have a PNG image of 215ko (542px x 700px) that I want to convert to webp. I'm using the following code. Once the code is completed, there is a new file with the expected filename having 0 byte. I used `then` and `catch` with `console.log` on the promise to see what is happening, but I got nothing.

If I resize the image (`....clone().resize(250).webp(...`) before the webp transformation, it works. A memory error? I'm converting other large images and it works fine.

### What is the expected behaviour?

I expect a new webp image generated, and if not, an error to be thrown.

### Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

```
const initialPipeline = sharp(filePath);
...
filename = `${baseDest}/${fileName}.webp`;
pipeline
  .clone()
  .webp({
    quality: 80,
  })
  .toFile(filename);
```
Also tried with:
```
sharp.cache(false);
const initialPipeline = sharp(filePath, {
  sequentialRead: true,
});
```

### Are you able to provide a sample image that helps explain the problem?

Unfortunately, I cannot make this image available publicly.

### What is the output of running `npx envinfo --binaries --system`?

```
$ npx envinfo --binaries --system
npx: installed 1 in 2.613s

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Xeon(R) CPU E3-1505M v6 @ 3.00GHz
    Memory: 8.19 GB / 31.81 GB
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
```

**Comment by lovell** [comment]
If you're able to share the image privately, please use the email address in https://github.com/lovell/sharp/blob/master/package.json#L5

**Comment by service-paradis** [comment]
@lovell Thank you! I just sent you the image :)

**Comment by lovell** [comment]
I cannot reproduce this using the sample image and code. Please can you provide a complete, standalone code sample. Perhaps there is logic not shown here that is (re)moving files on the filesystem?

**Comment by service-paradis** [comment]
Oh well, I feel bad right now...
Sorry for your time, it was my mistake. It is part of a larger resizing scripts. Unfortunately, I was not awaiting the promise for the original webp transformation. It was working for some images, but not this one.
