### ISSUE TITLE
something went wrong installing sharp module 

### ISSUE THREAD

**Issue by SamimAzimi** [lovell/sharp#2127]
cannot find module '../build/release/sharp.node'
Require stack: 

/.nvm/version/node/v10.19.0/lib/node_modules/tileserver-gl/node_module/sharp/lib/constructor.js

run "npm rebuild --verbose sharp" and look for errors

**Comment by lovell** [comment]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?

Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime?

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

What is the output of running `npx envinfo --binaries --system`?

**Comment by pacocom** [comment]
I have the same issue.
Windows 10 Pro - compilation 18363

$ node -v
v12.3.1

$ npm -v
6.14.2

![image](https://user-images.githubusercontent.com/7735329/76933810-40fc4080-68ee-11ea-9981-d8d4a59fd32b.png)

I try 
npm install --unsafe-perm
npm install --ignore-scripts=false

but nothing work!!

Help!

**Comment by lovell** [comment]
@pacocom Please open a new installation issue and answer all of the questions - https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md

**Comment by DavidSabine** [comment]
I suggest close this issue. I've started a new one with the proper template at https://github.com/lovell/sharp/issues/2134

**Comment by reinisg** [comment]
with command `npm install --ignore-scripts=false` works fine

**Comment by lovell** [comment]
@SamimAzimi Were you able to make any progress with this? If not, please can you answer my questions for me to be able to help further.

**Comment by SamimAzimi** [comment]
The issue has been resolved , the issue happened cause NPM was not at latest version , after updated it solved the issue ,
