### ISSUE TITLE
Adding white background after creating a composite circular image 

### ISSUE THREAD

**Issue by madhur1991** [lovell/sharp#2129]
Hi I am trying to add a specific color background to a circular image.
The code I used to create the circular image is as follows.
sharp(image)
                            .resize(parseInt(req.query.width), parseInt(req.query.height))
                            .composite([{ input: Buffer.from(circleSVG), blend: 'dest-in' }])
                            .toBuffer((err2, dt1, info) => {
                                    res.set('Content-Type', 'image/jpeg');
                                    res.send(dt1);
                                });
The image is generated but I cannot add a specific color background to fill the bounding box of circular image in the background. I tried flatten with background but that does not work. what I want is that a person image is cropped in a circle and then put over a square background of a particular color.

**Comment by lovell** [comment]
Hi, `dest-in` is probably the wrong blend mode. Instead overlay an SVG containing a path of a circle-cut-from-a-square, see https://stackoverflow.com/a/26481923/4625124 for an example.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
