### ISSUE TITLE
Delete closed issues created prior to 2018 as they are very likely to contain outdated API and documention links

### ISSUE THREAD

**Issue by samdesota** [lovell/sharp#2132]
Hi, 

This github comment: https://github.com/lovell/sharp/issues/869#issuecomment-315305390

Links to very shady website. I assume documentation moved to a new location, but not great to have that linked to on issues.

Thank you

**Comment by mrapogee** [comment]
Note, the content linked at the linke seems to change every time it's clicked, but when I clicked on it the first time, it opened a webpage with a faked macOS system dialog trying to get me to download something.

**Comment by lovell** [comment]
Thanks for the notification, I've deleted that particular link. A proper clean up of old issues would be very useful as links using this domain will only appear in (closed) issues created in 2017 and earlier, which don't provide much useful information.

**Comment by lovell** [comment]
I've been through all the closed issues and removed dead links.
