### ISSUE TITLE
Something went wrong installing sharp module: multiple errors

### ISSUE THREAD

**Issue by DavidSabine** [lovell/sharp#2134]
Starting yesterday evening (March 20, 2020) depending what I try, I get various error messages including:

```
The specified procedure could not be found.
\\?\C:\Users\me\Documents\GitHub\scrum.works\node_modules\gatsby-plugin-sharp\node_modules\sharp\build\Release\sharp.node
```
```
Cannot find module '../build/Release/sharp.node'
```
```
Error: Found vendored libvips v8.9.1 but require v8.8.1. Please remove the 'node_modules/sharp/vendor' directory and run 'npm install'.
```

I'm thinking it's one problem -> multiple symptoms.

---
> Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?

Yes.

> Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime?

I'm unsure how to check this. But, I had Nodejs 12.0.0 installed, and then I tried Nodejs 12.6.1. I use nvm to install node and switch back and forth. Also, I've tried building my code on Netlify in both versions (NOTE: The build was successful on Netlify 2 days ago, but today the same tree is failing with the "cannot find module" message above.)

`yarn versions` tells me I'm using node 12.16.1 and yarn 1.22.4. (I keep things up-to-date.)

> Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

> If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

Not applicable. I'm on Windows. 

But I have tried everything in a Powershell Run as Administrator. (And I hit the same errors messages.)

> If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

`yarn config list` shows that ignore-scripts is set to false. So, yes.

> What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

```

> sharp@0.25.2 install C:\Users\david\Documents\GitHub\scrum.works\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)

+ sharp@0.25.2
added 2 packages, removed 2562 packages, updated 72 packages and audited 164 packages in 202.921s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

Note also, (I use yarnpkg) when I 'yarn' at the top-level of my repo, everything works fine and sharp appears to build normally.  (as in: "Building fresh packages..." and sharp is one of those packages.)

But I experience the problem when I run `gatsby build` on my gastby site. (Note: My gatsby site hasn't changed since 2 days ago ... it's the same code that's been building successfully all along... but last night I started hitting these problems with sharp.)

> What is the output of running `npx envinfo --binaries --system`?

```
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 23.72 GB / 31.97 GB
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
```
---

More info:

I use yarn workspace. My workspace looks like this:

> /root
> > /site  ( a gatsby site. this is the site I can no longer build successfully. _Sharp breaks `gatsby build` here._ )
> > /style (a gatsby theme, this site *I CAN* build successfully. _Yes, `gatsby build` works fine here._)

Here's the relevant excerpt from a recent attempt to build my site at Netlify. For command.

```
12:06:58 PM: $ gatsby build
12:07:03 PM: success open and validate gatsby-configs - 0.082s
12:07:04 PM: error Error in "/opt/build/repo/node_modules/gatsby-plugin-sharp/gatsby-node.js":
12:07:04 PM: Something went wrong installing the "sharp" module
12:07:04 PM: Cannot find module '../build/Release/sharp.node'
12:07:04 PM: Require stack:
12:07:04 PM: - /opt/build/repo/node_modules/gatsby-plugin-sharp/node_modules/sharp/lib/constructor.js
12:07:04 PM: - /opt/build/repo/node_modules/gatsby-plugin-sharp/node_modules/sharp/lib/index.js
12:07:04 PM: - /opt/build/repo/node_modules/gatsby-plugin-sharp/safe-sharp.js
12:07:04 PM: - /opt/build/repo/node_modules/gatsby-plugin-sharp/index.js
12:07:04 PM: - /opt/build/repo/node_modules/gatsby-plugin-sharp/gatsby-node.js
12:07:04 PM: - /opt/build/repo/node_modules/gatsby/dist/bootstrap/resolve-module-exports.js
12:07:04 PM: - /opt/build/repo/node_modules/gatsby/dist/bootstrap/load-plugins/validate.js
12:07:04 PM: - /opt/build/repo/node_modules/gatsby/dist/bootstrap/load-plugins/load.js
12:07:04 PM: - /opt/build/repo/node_modules/gatsby/dist/bootstrap/load-plugins/index.js
12:07:04 PM: - /opt/build/repo/node_modules/gatsby/dist/bootstrap/index.js
12:07:04 PM: - /opt/build/repo/node_modules/gatsby/dist/commands/build.js
12:07:04 PM: - /opt/build/repo/node_modules/gatsby-cli/lib/create-cli.js
12:07:04 PM: - /opt/build/repo/node_modules/gatsby-cli/lib/index.js
12:07:04 PM: - /opt/build/repo/node_modules/gatsby/dist/bin/gatsby.js
12:07:04 PM: - Run "npm rebuild --verbose sharp" and look for errors
12:07:04 PM: - Consult the installation documentation at https://sharp.pixelplumbing.com/install
12:07:04 PM: - Search for this error at https://github.com/lovell/sharp/issues
12:07:04 PM: 
12:07:04 PM:   Error: Something went wrong installing the "sharp" module
12:07:04 PM:   Cannot find module '../build/Release/sharp.node'
12:07:04 PM:   Require stack:
12:07:04 PM:   - /opt/build/repo/node_modules/gatsby-plugin-sharp/node_modules/sharp/lib/cons  tructor.js
12:07:04 PM:   - /opt/build/repo/node_modules/gatsby-plugin-sharp/node_modules/sharp/lib/inde  x.js
12:07:04 PM:   - /opt/build/repo/node_modules/gatsby-plugin-sharp/safe-sharp.js
12:07:04 PM:   - /opt/build/repo/node_modules/gatsby-plugin-sharp/index.js
12:07:04 PM:   - /opt/build/repo/node_modules/gatsby-plugin-sharp/gatsby-node.js
12:07:04 PM:   - /opt/build/repo/node_modules/gatsby/dist/bootstrap/resolve-module-exports.js  - /opt/build/repo/node_modules/gatsby/dist/bootstrap/load-plugins/validate.js
12:07:04 PM:   - /opt/build/repo/node_modules/gatsby/dist/bootstrap/load-plugins/load.js
12:07:04 PM:   - /opt/build/repo/node_modules/gatsby/dist/bootstrap/load-plugins/index.js
12:07:04 PM:   - /opt/build/repo/node_modules/gatsby/dist/bootstrap/index.js
12:07:04 PM:   - /opt/build/repo/node_modules/gatsby/dist/commands/build.js
12:07:04 PM:   - /opt/build/repo/node_modules/gatsby-cli/lib/create-cli.js
12:07:04 PM:   - /opt/build/repo/node_modules/gatsby-cli/lib/index.js
12:07:04 PM:   - /opt/build/repo/node_modules/gatsby/dist/bin/gatsby.js
12:07:04 PM:   - Run "npm rebuild --verbose sharp" and look for errors
12:07:04 PM:   - Consult the installation documentation at https://sharp.pixelplumbing.com/in  stall
12:07:04 PM:   - Search for this error at https://github.com/lovell/sharp/issues
```

And this is the exact codebase on my local machine:

```
$ gatsby build
success open and validate gatsby-configs - 0.228s

 ERROR

Error in "C:\Users\david\Documents\GitHub\scrum.works\node_modules\gatsby-plugin-sharp\gatsby-node.js":
Something went wrong installing the "sharp" module

The specified procedure could not be found.
\\?\C:\Users\david\Documents\GitHub\scrum.works\node_modules\sharp\build\Release\sharp.node

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

  Error: Something went wrong installing the "sharp" module
  The specified procedure could not be found.
  \\?\C:\Users\david\Documents\GitHub\scrum.works\node_modules\sharp\build\Release\sharp.node
  - Remove the "node_modules/sharp" directory then run
    "npm install --ignore-scripts=false --verbose" and look for errors
  - Consult the installation documentation at https://sharp.pixelplumbing.com/install
  - Search for this error at https://github.com/lovell/sharp/issues
```

**Comment by lovell** [comment]
What is the out of running `npm ls sharp` in the `C:\Users\me\Documents\GitHub\scrum.works` directory?

**Comment by DavidSabine** [comment]
Hi @lovell,

> What is the out of running `npm ls sharp` in the `C:\Users\me\Documents\GitHub\scrum.works` directory?

I'm sorry I can't answer that question any longer. I've made further adjustments and now cannot reproduce the problem.

## That's good news!

No more problem! We can close this issue.

*What changed?* You might ask.

I went out on a limb and I bumped ALL the versions of ALL my dependencies in the package.json files of my gatsby workspaces. (They weren't far behind, with `yarn outdated` I keep my modules very current.)

After doing that, I can now build everything as normal.

## That's bad news!

We'll never know what went wrong. I'll chalk it up to version conflicts in the mess of dependencies.

**Comment by lovell** [comment]
The error `Found vendored libvips v8.9.1 but require v8.8.1` would suggest both sharp v0.23.x and v0.25.x were in the same dependency tree and conflicting with each other.
