### ISSUE TITLE
ChromaSubsampling parameter ignored when converting to JPEG output

### ISSUE THREAD

**Issue by shamot12** [lovell/sharp#2135]
Hi,
I am trying to rotate a JPEG image, and this library makes a great job, however, the outputStream is bigger as the inputStream. After some tests, I found that the chromaSubsampling parameter is ignored during the transformation.
The original image has a chroma subsampling of 4:2:0. But when I set the output JPEG options like:
`{ quality : 100, chromaSubsampling : '4:2:0', force : false }` (as it's discussed on #659), run the rotate function, and read the metadata of the output image, its chromaSubsampling value is '4:4:4'.

**Comment by lovell** [comment]
Hi, libvips currently ignores the JPEG subsampling setting when quality >=90.

The future libvips v8.10.0 will allow us to take advantage of the proposed `subsample_mode` setting.

https://github.com/libvips/libvips/pull/1552

**Comment by shamot12** [comment]
Oh, it's ok.
Then I guess [https://sharp.pixelplumbing.com/api-output#jpeg](url) should be corrected, because it says on JPEG parameters: "options.chromaSubsampling String set to '4:4:4' to prevent chroma subsampling when quality <= 90". And it should be quality >= 90, shouldn't it?

**Comment by lovell** [comment]
I've expanded the `chromaSubsampling` docs via commit ecd01af.

Let's leave this issue open to track integration with the upstream improvements in libvips.
