### ISSUE TITLE
SHARP 32143: ignoring palette (no quantisation support)

### ISSUE THREAD

**Issue by d30jeff** [lovell/sharp#2136]
What are you trying to achieve?
- Enable compression in Linux AMI 2

Have you searched for similar questions?
- Yes, but I can't seem to find anything that is similar

Are you able to provide a minimal, standalone code sample that demonstrates this question?
- In my staging server, I added `export NODE_DEBUG=sharp`,
and I get this output in the terminal whenever I upload png files 
`SHARP 32143: ignoring palette (no quantisation support)`.
I would like to point out that JPEG files are working fine.

Are you able to provide a sample image that helps explain the question?
- [example image](https://lh3.googleusercontent.com/proxy/dWNU6e9yMH7-_jrN-_W1c2_NWJeFR2hzNDvIY-ipkvMGXvGibNqbY1HoXOyiWJvmTcZDgvA4h20NuWPA6dOF55as_6vYq1g8Wst_uXAYTQ4o1xW8MFcF79DLzA)

**Comment by lovell** [comment]
Have you globally-installed libvips compiled with support for libimagequant?

> `options.palette` `Boolean` quantise to a palette-based image with alpha transparency support, requires libvips compiled with support for libimagequant (optional, default false)

https://sharp.pixelplumbing.com/api-output#png

**Comment by d30jeff** [comment]
@lovell 
To be completely honest I'm not sure, 
is there a command that I can run to verify that libvips has been compiled with support for libimagequant?

**Comment by lovell** [comment]
If you're unsure, that means it has not. Please carefully follow the instructions at https://libvips.github.io/libvips/install.html#building-libvips-from-a-source-tarball ensuring any required optional dependencies such as libimagequant are installed first.

**Comment by d30jeff** [comment]
@lovell Got it! I'll get back to you once I'm done

**Comment by d30jeff** [comment]
@lovell 

I couldn't get `./configure` to recognize libimagequant after downloading version 8.9.1 from 
https://github.com/libvips/libvips/releases

```
checking for IMAGEQUANT... no
configure: WARNING: libimagequant not found; disabling 8bpp PNG support
```

Would you be able to point me in the right direction?

```
* build options
native win32:				no
native OS X:				no
open files in binary mode: 		no
enable debug:				no
enable deprecated library components:	yes
enable docs with gtkdoc:		no
gobject introspection: 			no
enable radiance support: 		yes
enable analyze support: 		yes
enable PPM support: 			yes

* optional dependencies
use fftw3 for FFT: 			no
Magick package: 			none
Magick API version: 			none
load with libMagick: 			no
save with libMagick: 			no
accelerate loops with orc: 		yes
  (requires orc-0.4.11 or later)
ICC profile support with lcms: 		no
file import with niftiio: 		no
file import with libheif: 		no
file import with OpenEXR: 		no
file import with OpenSlide:		no
  (requires openslide-3.3.0 or later)
file import with matio: 		no
PDF import with PDFium 			no
PDF import with poppler-glib: 		no
  (requires poppler-glib 0.16.0 or later)
SVG import with librsvg-2.0: 		no
  (requires librsvg-2.0 2.34.0 or later)
zlib: 					yes
file import with cfitsio: 		no
file import/export with libwebp:	no
  (requires libwebp, libwebpmux, libwebpdemux 0.6.0 or later)
text rendering with pangoft2: 		no
file import/export with libpng: 	yes (pkg-config libpng >= 1.2.9)
  (requires libpng-1.2.9 or later)
support 8bpp PNG quantisation:		no
  (requires libimagequant)
file import/export with libtiff:	no
file import/export with giflib:		no
file import/export with libjpeg:	yes (pkg-config)
image pyramid export:			no
  (requires libgsf-1 1.14.26 or later)
use libexif to load/save JPEG metadata: no
```
This is the summary after running the `./configure` command

**Comment by lovell** [comment]
How was libimagequant installed?

**Comment by d30jeff** [comment]
I follow the steps from 
https://centos.pkgs.org/6/epel-x86_64/libimagequant-2.5.2-5.el6.x86_64.rpm.html

```
Download latest epel-release rpm from
http://download-ib01.fedoraproject.org/pub/epel/6/x86_64/
Install epel-release rpm:
# rpm -Uvh epel-release*rpm
Install libimagequant rpm package:
# yum install libimagequant
```

What I did
```
wget https://download-ib01.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
sudo rpm -Uvh epel-release*rpm
sudo yum install libimagequant
```

**Comment by lovell** [comment]
Did you see the part of the libvips documentation referenced at https://libvips.github.io/libvips/install.html#building-libvips-from-a-source-tarball that says "You’ll need the dev packages for the file format support you want"? For CentOS these package names end in `-devel`, e.g. `libimagequant-devel`.

**Comment by d30jeff** [comment]
Yes, I have installed `libimagequant-devel` as well, but it still fails to recognize/detect it.
Let me try a different approach with: https://github.com/jcupitt/docker-builds

**Comment by d30jeff** [comment]
Update:

I tried the Docker build but to no avail.

I've taken a different approach since then:

1. I've followed the installation instruction here for libimagequant installation
  https://pngquant.org/lib/

```
wget https://github.com/ImageOptim/libimagequant/archive/2.12.6.tar.gz
tar xf 2.12.6.tar.gz
cd libimagequant-2.12.6
./configure --prefix=/usr
make libimagequant.so
```

2. I downloaded version 8.9.1 from https://github.com/libvips/libvips/releases
```
wget https://github.com/libvips/libvips/releases/download/v8.9.1/vips-8.9.1.tar.gz
./configure

* build options
native win32:				no
native OS X:				no
open files in binary mode: 		no
enable debug:				no
enable deprecated library components:	yes
enable docs with gtkdoc:		no
gobject introspection: 			no
enable radiance support: 		yes
enable analyze support: 		yes
enable PPM support: 			yes

* optional dependencies
use fftw3 for FFT: 			no
Magick package: 			none
Magick API version: 			none
load with libMagick: 			no
save with libMagick: 			no
accelerate loops with orc: 		no
  (requires orc-0.4.11 or later)
ICC profile support with lcms: 		no
file import with niftiio: 		no
file import with libheif: 		no
file import with OpenEXR: 		no
file import with OpenSlide:		no
  (requires openslide-3.3.0 or later)
file import with matio: 		no
PDF import with PDFium 			no
PDF import with poppler-glib: 		no
  (requires poppler-glib 0.16.0 or later)
SVG import with librsvg-2.0: 		no
  (requires librsvg-2.0 2.34.0 or later)
zlib: 					yes
file import with cfitsio: 		no
file import/export with libwebp:	no
  (requires libwebp, libwebpmux, libwebpdemux 0.6.0 or later)
text rendering with pangoft2: 		no
file import/export with libpng: 	yes (pkg-config libpng >= 1.2.9)
  (requires libpng-1.2.9 or later)
support 8bpp PNG quantisation:		no
  (requires libimagequant)
file import/export with libtiff:	no
file import/export with giflib:		no
file import/export with libjpeg:	no
image pyramid export:			no
  (requires libgsf-1 1.14.26 or later)
use libexif to load/save JPEG metadata: no
```

But it still fails to detect libimagequant.

Is there something that's obvious that I'm doing wrong?

**Comment by lovell** [comment]
You'll need to run `sudo ldconfig` after compiling and installing each shared library from source.

**Comment by d30jeff** [comment]
I tried that but libvips still fails to recognize `libimagequant`.
I have created a Dockerfile here: 
https://gist.github.com/d30jeff/857c55741b8aa39590c9ebd3402328b8

To reproduce the issue.

Helpful link:
https://github.com/lovell/sharp/issues/327#issuecomment-167094002

**Comment by lovell** [comment]
You'll need to run `ldconfig` after compiling and installing *each and every* shared library from source.

**Comment by d30jeff** [comment]
@lovell 
If it's not too much trouble, could you review:
https://gist.github.com/d30jeff/857c55741b8aa39590c9ebd3402328b8/revisions

P.S I'm not familiar with these kind of things, I'd appreciate your input

**Comment by lovell** [comment]
@d30jeff Were you able to make any progress with this?

**Comment by d30jeff** [comment]
@lovell No :(

We're considering a different distro for an alternative

**Comment by d30jeff** [comment]
@lovell 
We have decided to go with Ubuntu for now and everything works as expected.

Thank you for your time. Cheers
