### ISSUE TITLE
Stuck at info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-win32-x64.tar.gz

### ISSUE THREAD

**Issue by ForgottenTale** [lovell/sharp#2137]
i was installing sharp as a part of a gatsby starter template. The installation got stuck at 

`info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-win32-x64.tar.gz`

I waited for 1hr and nothing happened. So i tried again and again but no luck. I the terminal was stuck at showing 

`info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-win32-x64.tar.gz`

So i tried the `npm install sharp` and the terminal again got stuck at

 `info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-win32-x64.tar.gz`

**Comment by SmartArray** [comment]
Same here

**Comment by Ton0703** [comment]
I have the same problem,can you tell me how to fix it?
