### ISSUE TITLE
Extract Alpha Channel

### ISSUE THREAD

**Issue by turbobuilt** [lovell/sharp#2138]
### What are you trying to achieve?
Extract alpha channel

### Have you searched for similar feature requests?
Yes

### What would you expect the API to look like?
Just go ahead and add alpha channel to the extractChannel method. `.extractChannel('alpha')`

### What alternatives have you considered?
extractChannel

### Is there a sample image that helps explain?
No

**Comment by turbobuilt** [comment]
Ok, looks like you can just do `.extractChannel(3)`

**Comment by turbobuilt** [comment]
Actually I'm gonna reopen this because the docs should be updated.  Currently says:
`channel (Number  | String ) zero-indexed band number to extract, or red, green or blue as alternative to 0, 1 or 2 respectively.`

Should add something about alpha channel.

**Comment by lovell** [comment]
Commit 17ea70a adds support for this, which will be part of v0.25.4.

**Comment by lovell** [comment]
v0.25.4 now available, thank you for suggesting this improvement.

**Comment by turbobuilt** [comment]
Thanks for all your hard work on this great library!
