### ISSUE TITLE
Installation fails in ../src/utilities.cc

### ISSUE THREAD

**Issue by jiivonen** [lovell/sharp#214]
I'm trying to run npm install and get this:
> sharp@0.10.0 install /var/web/expresscuckoo/node_modules/sharp
> node-gyp rebuild

make: Entering directory `/var/web/expresscuckoo/node_modules/sharp/build'
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
../src/utilities.cc: In function ‘v8::Handle<v8::Value> format(const v8::Arguments&)’:
../src/utilities.cc:99: error: expected initializer before ‘:’ token
../src/utilities.cc:99: error: expected primary-expression before ‘)’ token
../src/utilities.cc:99: error: expected ‘;’ before ‘)’ token
../src/utilities.cc:103: error: ‘f’ was not declared in this scope
make: *** [Release/obj.target/sharp/src/utilities.o] Error 1
make: Leaving directory `/var/web/expresscuckoo/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-504.16.2.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/web/expresscuckoo/node_modules/sharp
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by jiivonen** [comment]
Hngh... I asked this same thing myself a couple of months ago.

**Comment by lovell** [comment]
No worries. For anyone else who discover this, #178 is the duplicate.

**Comment by lovell** [comment]
I've added a guard against this occurring again - see https://github.com/lovell/sharp/commit/4f72dcbf54557a5e97f33cd43dcd574da5fb7627
