### ISSUE TITLE
Resize/resample kernel

### ISSUE THREAD

**Issue by strarsis** [lovell/sharp#2140]
What are you trying to achieve?
Resize/downsample an image to specific resolution.
The quality should equal to what IrfanView / Photoshop (Bicubic sharper) show for zooming out/resampling the image.

Are you able to provide a minimal, standalone code sample that demonstrates this question?
````
sharp.resize(1920, null, { kernel: 'lanczos3' });
````

Are you able to provide a sample image that helps explain the question?
Any image with edges like roof tiles, vegetation.

**Comment by lovell** [comment]
Hi, did you see the "cubic" `kernel` option? https://sharp.pixelplumbing.com/api-resize

If you have a specific kernel in mind, perhaps for post-resize sharpening, you could also try the `convolve()` operation. https://sharp.pixelplumbing.com/api-operation#convolve

**Comment by strarsis** [comment]
@lovell: I try to get the same results (or approximation of) what the Photoshop Bicubic sharper filter does for downscaling (downsampling?) an image.

Photoshop Bicubic (Sharper):
![photoshop-bicubic-sharper](https://user-images.githubusercontent.com/9271436/77754834-64309980-702c-11ea-8693-0de06325a004.png)

Sharp Lanczos 3:
![sharp-lanczos3](https://user-images.githubusercontent.com/9271436/77754854-6b57a780-702c-11ea-9169-717231c5a334.png)

Note: These embedded images are somehow resized in the browser, open each image to see the original image to be able to correctly compare them both.

**Comment by lovell** [comment]
If the input format is JPEG, did you see the `fastShrinkOnLoad` option of `resize()`, which you might want to try setting to `false`? https://sharp.pixelplumbing.com/api-resize#parameters

It's a bit tricky to compare these output images pixel-by-pixel as they are cropped differently. How does using sharp/libvips' `kernel: 'cubic'` compare? Perhaps add a mild `sharpen()` operation after the resize? https://sharp.pixelplumbing.com/api-operation#sharpen

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
