### ISSUE TITLE
libvips with mozjpeg?

### ISSUE THREAD

**Issue by strarsis** [lovell/sharp#2141]
How can I ensure that libvips installed/used by sharp is actually compiled with mozjpeg?
Can I install a libvips that uses mozjpeg? Or force sharp to use a different libvips comes with mozjpeg?

**Comment by lovell** [comment]
Hi, did you see #586?

**Comment by strarsis** [comment]
@lovell: Is it possible to add some lines to the project npm to automate this?
Ideally `npm install` would build libvips with mozjpeg and ensure `sharp` uses this build.

**Comment by lovell** [comment]
No, sorry, you'll have to install this yourself.

**Comment by bruno-xo7** [comment]
What is the problem with mozjpeg to not be chosen as the standard lib for jpeg in sharp?
(just asking)
