### ISSUE TITLE
v0.24 and v0.25 cannot be loaded in Electron on Ubuntu 18.04

### ISSUE THREAD

**Issue by catdad** [lovell/sharp#2144]
**Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?**

Yes. Although, it affects the 2 latest versions, v0.24.x and v0.25.x.

**What are the steps to reproduce?**

Use v0.24 or v0.25 in Electron 7 or 8. Yes, I did use `electron-rebuild` to make sure it is using the correct binary.

**What is the expected behaviour?**

Sharp can be used successfully, the same way that v0.23 could be used.

**Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?**

Extract, then run:

```bash
npm install
./node_modules/.bin/electron-rebuild
npx electron main.js
```

[repro.tar.gz](https://github.com/lovell/sharp/files/4399484/repro.tar.gz)

Running `npm install sharp@0.23` shows that version working, but `npm install sharp@0.24` or `npm install sharp@0.25` does not work and produces the error in the image below.

Under Windows or MacOS, 0.24 and 0.25 work correctly.

**Are you able to provide a sample image that helps explain the problem?**

This is the error I get when requiring the module from the renderer:

![image](https://user-images.githubusercontent.com/2205537/77856353-91b04b00-71c4-11ea-81e8-548c64fa8779.png)

And here it is required from the main thread (same error, but I am including it just in case it is interesting somehow):

![image](https://user-images.githubusercontent.com/2205537/77856805-aa6e3000-71c7-11ea-86f9-ddc50e4edb24.png)

**What is the output of running `npx envinfo --binaries --system`?**

![image](https://user-images.githubusercontent.com/2205537/77856590-2b2c2c80-71c6-11ea-9763-70e83b1669bf.png)

**Comment by lovell** [comment]
Hi, did you see #2058?

**Comment by catdad** [comment]
Sorry, that is my mistake. I tried looking for an existing issue, but it looks like I failed. I will follow up on the existing one instead. Thanks!
