### ISSUE TITLE
Support for environment variable NO_PROXY when downloading binaries

### ISSUE THREAD

**Issue by alec-francis** [lovell/sharp#2145]
The `agent.js` file will look at the environment variables below when deciding whether to configure a proxy or not for downloading the archived binaries.

```
const proxies = [
  'HTTPS_PROXY',
  'https_proxy',
  'HTTP_PROXY',
  'http_proxy',
  'npm_config_https_proxy',
  'npm_config_proxy'
];
```

My server is situated in a network that uses proxy servers for some endpoints and no proxy for other endpoints. I believe the convention for this situation is to use the NO_PROXY environment variable to control which endpoints use the proxy.

**NO_PROXY**
[https://www.gnu.org/software/emacs/manual/html_node/url/Proxies.html](https://www.gnu.org/software/emacs/manual/html_node/url/Proxies.html)

Should I raise a PR? Any thoughts?

Cheers,

Alec

**Comment by lovell** [comment]
Hi Alec, a PR would be very welcome to integrate with something like https://www.npmjs.com/package/proxy-from-env to manage proxy logic for the prebuilt libvips binaries, thank you.

You'll probably also need to submit a similar PR to the https://www.npmjs.com/package/prebuild-install module as it is used for the prebuilt sharp binaries.

**Comment by alec-francis** [comment]
FYI, I didn't end up implementing the NO_PROXY logic.

I just placed the binaries in the npm cache of my source control.

I'll close this for now and we'll see if there is ever a demand for such a feature.

**Comment by dave-db** [comment]
I just diagnosed my team's install issues (behind a proxy) as being down to this - the installer tries to use the proxy even though we have the binaries mirrored within the network (and `NO_PROXY` set for local traffic), throws a 502. Would be great to get a bulletproof install - can we consider this demand as @alec-francis mentioned?

**Comment by hao-xx** [comment]
Tried the bypass solution from @alec-francis.
The issue for this solution is that, it's hard to get the proper version of sharp and sharp-libvips before-head. So have to pin the sharp version.
