### ISSUE TITLE
Development OS different than production OS

### ISSUE THREAD

**Issue by MaxvandeLaar** [lovell/sharp#2148]
**Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?**
Yep, left me a bit confused. Reading old issues didn't help understanding how to fix it either.

**Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime?**
This is definitely not the case. I am trying to run this on Athom Homey and I am writing my code on MacOS while the Homey runs Linux. I realise this is obviously the problem however I cannot seem to figure out how to install it correctly. 

I write and build all the code on MacOS which I need to upload to Homey, I cannot run npm on the Homey so I need to prebuilt everything on my MacOS before uploading. How do I accomplish this? The error message I get when running is very clear, however no clue how to fix it. Can you guide me in the right direction?

`darwin-x64' binaries cannot be used on the 'linux-armv6`

**Comment by lovell** [comment]
If you're building on macOS and deploying to Linux ARMv6, you'll need to tell `npm install` which platform and arch to use:

```sh
rf -rf node_modules/sharp
npm install --platform=linux --arch=arm sharp
```

However prebuilt Linux ARMv6 binaries are provided only for libvips and not for sharp.

https://sharp.pixelplumbing.com/install#prebuilt-binaries

> The following platforms have prebuilt libvips but not sharp:
> - Linux ARMv6

This means on macOS you'll need to (cross-)compile sharp itself, which can be pretty tricky to achieve on a non-ARMv6 machine, so it's probably easier to do this on the ARMv6 device itself.

**Comment by MaxvandeLaar** [comment]
@lovell, Thanks for the info, it's a bit clearer now 🙂 sadly I can't access the device itself so I needed to figure out a different solution.
