### ISSUE TITLE
How to force libvips installation?

### ISSUE THREAD

**Issue by jiivonen** [lovell/sharp#215]
I'm getting error
```
beta-3 (err): module.js:356
beta-3 (err):   Module._extensions[extension](this, filename);
beta-3 (err):                                ^
beta-3 (err): Error: libwebp.so.4: cannot open shared object file: No such file or directory
beta-3 (err):     at Module.load (module.js:356:32)
beta-3 (err):     at Function.Module._load (module.js:312:12)
beta-3 (err):     at Module.require (module.js:364:17)
beta-3 (err):     at require (module.js:380:17)
beta-3 (err):     at Object.<anonymous> (<path_here>/node_modules/sharp/index.js:11:13)
```

I'm quite sure this is because I updated libwebp from 0.3.1 to 0.4.3 and libvips is build against the earlier version.

Is there a way run preinstallation script so it forces a reinstallation of libvips? Or is my only solution try to copy the needed parts out of the preinstallation script and compile it manually?

**Comment by jiivonen** [comment]
To reply myself: Removing the pkgconfig about vips.

**Comment by lovell** [comment]
The [install_libvips_from_source](https://github.com/lovell/sharp/blob/master/preinstall.sh#L23) function may provide some help for installing libvips from source.

**Comment by lovell** [comment]
Closing this 6-week old question/answer - please do feel free to reopen if there are still problems.
