### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by ThomasHurek** [lovell/sharp#2150]
**What are you trying to achieve?**
Develop software with the sharp package.
During our license scans we came across several files in the precompiled vendor package for Linux like freetype that seem to have a GPLv2 or 3 license.
Sharp though comes with an Apache license. Does that mean that the files included with sharp in the vendor package for Linux are also part of the Apache license? Or is that not relevant because those files are part of the OS and as thus come with the OS license - e.g. https://centos.pkgs.org/8/centos-baseos-x86_64/freetype-2.9.1-4.el8.x86_64.rpm.html

**Have you searched for similar questions?**
Yes.

**Are you able to provide a minimal, standalone code sample that demonstrates this question?**
Not a code issue. Sample file:
.../node_modules/sharp/vendor/include/freetype/config/ftstdlib.h

**Are you able to provide a sample image that helps explain the question?**
See above.

Thank you for your help!

**Comment by lovell** [comment]
The prebuilt shared library binaries placed within the `node_modules/sharp/vendor` directory at install time are made available under various licences detailed in the `node_modules/sharp/vendor/THIRD-PARTY-NOTICES.md` file.

The latest version of this file can also be viewed online at https://github.com/lovell/sharp-libvips/blob/master/THIRD-PARTY-NOTICES.md

All of these licences are compatible with Apache 2.0 when used as shared libraries.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
