### ISSUE TITLE
The specified procedure could not be found

### ISSUE THREAD

**Issue by gregwhitworth** [lovell/sharp#2151]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

Yes and no. Sharp is utilized by the `gatsby-plugin-sharp` and the `gatsby-plugin-favicon`. Here is the tree breakdowns:

```
+-- gatsby-plugin-favicon@3.1.6
| `-- favicons-webpack-plugin@0.0.9 (git+https://github.com/Creatiwity/favicons-webpack-plugin.git#0872de414061baaad0a2853c77ae75bc38b8bbbf)
|   `-- favicons@5.5.0
|     `-- sharp@0.23.4
+-- gatsby-plugin-sharp@2.2.14
| `-- sharp@0.22.1
`-- sharp@0.25.2
```

**What are the steps to reproduce?**

Typing in `gatsby build`, results in the following error:

> The specified procedure could not be found.

I've reviewed two other issues on here to try and avoid creating a new one, but none of the suggestions fixed my issue. Following what the error states, deleting the directories and re-installing them via `npm install` doesn't fix the issue. And I've manually verified that it is there as well.

**Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?**

No

**What is the output of running `npx envinfo --binaries --system`?**

```
  System:
    OS: Windows 10 10.0.17763
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 4.30 GB / 15.82 GB
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Users\gregw\AppData\Roaming\npm\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by lovell** [comment]
Please can you increment the version of all the dependencies shown here so that they all use the latest sharp, e.g. `gatsby-plugin-sharp` is currently at v2.5.3.

**Comment by gregwhitworth** [comment]
Thanks - I've done that. Now the output for version of sharp across dependancies:

>  npm view sharp dist-tags.latest
> 0.25.2

Running the command to start the app results in the same error:

> Something went wrong installing the "sharp" module
> The specified procedure could not be found.
> \\?\C:\git\open-ui\research\node_modules\favicons\node_modules\sharp\build\Release\sharp.node

Thanks again for the help

**Comment by lovell** [comment]
What is the output of running `npm ls sharp` now? I ask as it looks like `favicons` still depends on `sharp` v0.24.x.

https://github.com/itgalaxy/favicons/blob/master/package.json#L56

If so, please can you submit a PR to that repo to update it.

**Comment by gregwhitworth** [comment]
Thanks @lovell - that command ended up showing that somehow those plugins sharp dependancies weren't installed. I cleared the npm cache and deleted the folder and re-installed everything. This resulted in it working correctly. Thank you!!

**Comment by Michael-Brooks** [comment]
I get the same error using 0.25.3 and I've cleared cache and removed the package from my project. Using the latest version of Windows 10.

**Comment by lovell** [comment]
@Michael-Brooks https://github.com/gridsome/gridsome/pull/1140
