### ISSUE TITLE
Error when deploying a lambda in AWS

### ISSUE THREAD

**Issue by chipironVacilon** [lovell/sharp#2153]
It fires this error: 
Module did not self-register: '/var/task/node_modules/sharp/build/Release/sharp.node'.
Is locally working when installed via docker:
docker run -v "$PWD":/var/task lambci/lambda:build-nodejs12.x npm install sharp 
But not when deployed on the cloud

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/install#aws-lambda

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
