### ISSUE TITLE
Not enough space on Lambda @ Edge

### ISSUE THREAD

**Issue by LiamBateman** [lovell/sharp#2154]
https://github.com/lovell/sharp/issues/1851

Potentially related to the closed issue above. 

When using Lambda@Edge and resizing larger files (Works fine with normal sized images, we do not have a threshold in placed yet) we get an error that the function has ran out of space in '/tmp'.

The above suggestion is to update the follow env variable: 

`VIPS_DISC_THRESHOLD=600m`

But as we are on Edge, there is no support for this variable. 

The system we have re-sizes millions of images, so the CloudFront Cache is super important. Are there any other ways to set the VIPS_DISC_THRESHOLD?

**Comment by LiamBateman** [comment]
And we managed to resolve this by moving to sequentialRead 

Hope this helps someone out!

**Comment by YukSeungChan** [comment]
```
process.env.VIPS_DISC_THRESHOLD = '1024m'
```

Working for me.
