### ISSUE TITLE
Question about trim/composite/resize

### ISSUE THREAD

**Issue by kevinludwig** [lovell/sharp#2155]
Hi,
I have a sample script that takes an input png image, and trims transparency from right and left, and then re-centers the content onto an image of identical to original aspect ratio. (Like imagine the image has text with transparency which is left or right aligned). So the script below works. 
```
#!/usr/local/bin/node
const sharp = require('sharp');

(async () => {
    const buf = await sharp('./input.png').resize(300).toBuffer();
    const img = sharp(buf);
    const metadata = await img.metadata();
    const overlay = await img
        .trim().rotate(180)
        .trim().rotate(0)
        .toBuffer();
    const options = {
        create: {
            width: metadata.width,
            height: metadata.height,
            background: {r: 0, g: 0, b: 0, alpha: 0},
            channels: 4
        }
    };
    await sharp(options)
        .composite([{
            input: overlay,
            gravity: 'center'
        }]).toFile('./output.png');
    console.log('wrote the image file');
}) ();
```

EDIT: I got it to resize properly, so now Im wondering if I can do this without creating two temporary buffers. Can this be done fully streaming?

**Comment by lovell** [comment]
Please see #179 for future possible enhancements relating to Stream-based I/O.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
