### ISSUE TITLE
Input buffer contains unsupported image format when using on Lambda

### ISSUE THREAD

**Issue by gk-devteam** [lovell/sharp#2156]
Hi! 
I am using Sharp to resize an image before uploading to S3, on a Lambda function.
Every time the function get invoked it fails and sends back `Input buffer contains unsupported image format` error.

I have checked if Sharp support the image using the format method and it supports every images format I tried.

I am using the code below to resize and upload:
```
const resizeAndCropImage = async (img: Buffer): Promise<Buffer> => {
  return sharp(img)
    .resize(CONFIG.IMAGE_WIDTH, CONFIG.IMAGE_HEIGHT, {
      fit: 'cover',
      position: 'center'
    })
    .toBuffer()
}

export const uploadImage = async (file: Image, filePath: string): Promise<void> => {
  try {
    const img = await resizeAndCropImage(file.data)
    const params = {
      Bucket: process.env.S3_BUCKET_NAME,
      Key: filePath,
      Body: img,
      ContentType: file.mimetype,
      ACL: 'public-read'
    }
    await s3.upload(params).promise()
  } catch (error) {
    throw error
  }
}
```
If I use file.data instead of img in the s3 upload params, it works fine.
Can someone please tell me if I am missing something here?

**Comment by lovell** [comment]
Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

Are you able to provide a sample image that helps explain the problem?

**Comment by gk-devteam** [comment]
@lovell Thank you for your answer. 
I am trying to separate the code so I can share a sample as soon as I can.

**Comment by gk-devteam** [comment]
@lovell 
I fixed my problem but I have no idea how....The code is exactly the same, but changed a few things on AWS side and it works now...
Really makes me hate AWS a bit more each time.

Anyway, thanks again for this great plugin, and for trying to help me this quickly!

**Comment by solomonmulatu** [comment]
@gk-devteam 
can you share what things you changed on aws?
