### ISSUE TITLE
SVG: does this package support the `<image>` tag?

### ISSUE THREAD

**Issue by BannerBomb** [lovell/sharp#2157]
What are you trying to achieve?
I would like for this package to support the `image` tag because on discord I would like to be able to embed the users profile image and have it show their current status over it. But I can't do this unless I can import the external profile image. Currently all it does it import a blank image.

Have you searched for similar questions?

Are you able to provide a minimal, standalone code sample that demonstrates this question?
```js
const sharp = require('sharp');
const { MessageAttachment } = require('discord.js');
return msg.channel.send({ files: [new MessageAttachment(sharp(Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="40" height="32" viewBox="0 0 40 32" style="pointer-events: none; position: absolute; display: block; height: 100%; width: auto;" aria-hidden="true"><embed src="https://cdn.discordapp.com/avatars/313807409195778053/1aeddeb82cee7ed953d16c237e089779.png" x="0" y="0" width="32" height="32" mask="url(#svg-mask-avatar-status-mobile-32)" alt=" " style="-o-object-fit: cover; object-fit: cover; pointer-events: none; display: block;" aria-hidden="true"/></svg>`)).png(), 'test.png')] })
```

Are you able to provide a sample image that helps explain the question?
These are what it's outputting

![image](https://user-images.githubusercontent.com/11788894/79009795-5b60bd00-7b2e-11ea-8911-996c661c1f7c.png)
![image](https://user-images.githubusercontent.com/11788894/79009812-6582bb80-7b2e-11ea-8bcc-ae31b5eb50a0.png)

and this is what I would like to have it look like

![image](https://user-images.githubusercontent.com/11788894/79009832-759a9b00-7b2e-11ea-8984-d1131411c2f7.png)

**Comment by lovell** [comment]
External, URL-based images within SVG files are not supported. Please see #1871

**Comment by BannerBomb** [comment]
Ok, that's fine. I found [svg-to-img](https://www.npmjs.com/package/svg-to-img) which was able to use URL-based images from svg code like I needed it to do. Thanks though.

**Comment by BannerBomb** [comment]
@lovell Sorry I also forgot to mention, what about if using a base64 encoded image?

**Comment by lovell** [comment]
Embedded base64 encoded PNG and JPEG images within SVG are supported and there's an example in the unit tests at https://github.com/lovell/sharp/blob/master/test/unit/svg.js#L66

Please ensure you trust the source of any images used with libraries (such as Puppeteer) that can make network requests.

**Comment by BannerBomb** [comment]
Ok, I figured out how to use the embedded form now. It's cause I wasn't using `xlink:href`.

One last question. Would it be possible to convert an animated svg to a gif?

**Comment by lovell** [comment]
Embedded GIFs are not supported by librsvg.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by apowers313** [comment]
[Comment above links](https://github.com/lovell/sharp/issues/2157#issuecomment-612621988) to a unit test on the master branch rather than on a git hash, so the link is kinda broken. For anyone looking for the answer in the future, [this link](https://github.com/lovell/sharp/blob/cb592ce5888edaa233ad55082c7e780f182dc792/test/unit/svg.js#L106-L109) should work.
