### ISSUE TITLE
Poor quality after down sizing

### ISSUE THREAD

**Issue by goodhoko** [lovell/sharp#2158]
**What are you trying to achieve?**
Resize and compress images so they can be used on a website. The target width they'll be displayed at is 800 px. I was trying to achieve the best visual quality / file size ratio and noticed that it is actually better to scale the image way above the final display width while using much lower output quality. In other words it is much better if the image is scaled down by the browser at render time than by the Sharp library before hand.

For example I took [this original image](https://raw.githubusercontent.com/goodhoko/sharp_test/master/output/3_original.jpg) and resized it with
```js
sharp('./input/3.jpg').jpeg({quality: 100})
        .resize(800)
        .toFile('./output/3_800_100.jpg')
```
This resulted in a [814 KB file](https://raw.githubusercontent.com/goodhoko/sharp_test/master/output/3_800_100.jpg). When viewing it side by side to the original with 800 physical pixels the original looks much better.

**Why am I loosing quality despite the `quality` parameter being at its maximum value? Why is the Sharp's downsizing producing lower quality than the computer's downsizing?**

Then I resized the original file with
```js
sharp('./input/3.jpg').jpeg({quality: 60})
        .resize(1500)
        .toFile('./output/3_1500_60.jpg')
```
This resulted in a [375KB file](https://raw.githubusercontent.com/goodhoko/sharp_test/master/output/3_1500_60.jpg). When displayed with 800 physical pixels this file looks significantly better than the former one while also being significantly smaller in bytes.

I was expecting, that when exporting image to be displayed on 800px display, the best approach is to export an 800px wide image and then tweak the compression ratio to an acceptable level. However, the above observation leads me to assume, that from some point it is impossible to achieve higher levels of visual quality without also increasing the pixel width. Interestingly, that doesn't necessarily mean the file size (in bytes) has to increase, because we can use more aggressive compression to (even over) compensate for the increase in pixel width.

**Is my assumption right?  If yes, why? Why can't I simply resize jpeg image to 800px so that it looks the same as viewing 2500px wide jpeg image on 800px screen? Is this a fundamental property of jpeg format, or is this caused by the algorithms Sharp uses for downsizing?**

Btw: [here's my repo](https://github.com/goodhoko/sharp_test/) with a script I used to generate various size/quality variations of several images for comparison. It also contains the exported files I linked above.

**Have you searched for similar questions?**
Yes
https://github.com/lovell/sharp/issues/2140 -> mentioned suggestions have no effect

**Are you able to provide a minimal, standalone code sample that demonstrates this question?**
See above.

**Are you able to provide a sample image that helps explain the question?**
See above.

Thank you.

**Comment by lovell** [comment]
Hi, did you see the `kernel` and `fastShrinkOnLoad` options of `resize()` that alter the way in which images are resized?

https://sharp.pixelplumbing.com/api-resize#parameters

**Comment by goodhoko** [comment]
Yes. Using `fastShrinkOnLoad: false` had no visible effect. Out of all the kernels the default `lanczos3` is subjectively the best looking one.

**Comment by goodhoko** [comment]
Just found out t[his article](https://www.netvlies.nl/tips-updates/algemeen/algemeen/retina-revolution/) that confirm my findings and explains them with
> The bottomline is that heavy compression doesn’t affect the final image as much as you would expect. This is because of the greater amount of pixels in the [bigger in pixel size] image, compression artifacts are scaled down and therefore almost unnoticeable.

**Comment by lovell** [comment]
Thanks for the update, glad you worked it out.

**Comment by goodhoko** [comment]
For anyone stumbling upon this: see also [this SO question](https://stackoverflow.com/questions/7982409/is-jpeg-lossless-when-quality-is-set-to-100), which pretty much explains all my questions above.
