### ISSUE TITLE
Simple image manipulation

### ISSUE THREAD

**Issue by Jonesie** [lovell/sharp#2160]
What are you trying to achieve?
Ive been using another library in our product and need to replace it (it's too memory hungry and slow).   Im using Sharp via the AWS Image Handler - hosted in a lambda function.  It works well and I have resizing, flip, flop, negate, blur and sharpen working fine. 

However I dont really understand all these technical terms around images so Im not sure what operations I need to implement.  I just need to allow the users to change:

- contrast and brightness
- color modes like gray scale (found that), black and white, others?
- opacity (possible with png only?)

Have you searched for similar questions?
Yes, hard to find any info on Sharp with google.  Not sure where to look.   (I did find a subreddit called Sharp - but I'm not a nazi so that was not relevant :)

Are you able to provide a minimal, standalone code sample that demonstrates this question?
Thats the problem - dont know where to start.

Are you able to provide a sample image that helps explain the question?
Not specific to a single image.

**Comment by Jonesie** [comment]
With a bit of playing around Ive figured out most of this.  I just cant see how to do opacity.  Is that possible?

**Comment by lovell** [comment]
Hi, please see #618 for a future possible opacity enhancement and some workarounds you can use for now.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
