### ISSUE TITLE
Node.js 8 (EOL) - Error: `make` failed with exit code: 2 on Ubuntu 18

### ISSUE THREAD

**Issue by YunisDEV** [lovell/sharp#2161]
Hello.
I am on Ubuntu 18 on Server.
I get this error log when installing sharp

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/happyhome/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-96-generic
gyp ERR! command "/usr/bin/node" "/root/happyhome/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /root/happyhome/node_modules/sharp
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN happyhome@1.0.0 No description
npm WARN happyhome@1.0.0 No repository field.
npm ERR! Linux 4.15.0-96-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "sharp"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.25.2 install: `(node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.25.2 install script '(node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/happyhome/npm-debug.log

**Comment by lovell** [comment]
Node.js 8 has reached end-of-life and is unsupported.

**Comment by CyHuH** [comment]
I have the same error on node.js 13.

**Comment by lovell** [comment]
@CyHuH Please open a new installation issue at https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md ensuring you answer all of the questions.

**Comment by CyHuH** [comment]
I just downgraded node.js version to 12, and now all works well.

**Comment by jpelton-stroud** [comment]
For anybody else who runs into this issue:  read a few lines above the error and check for `make: g++: Command not found` or similar output.  Took me a while to notice it, but then `sudo apt-get install build-essential && npm clean-install` was a simple enough fix.
