### ISSUE TITLE
document extract & crop methods

### ISSUE THREAD

**Issue by tomprogers** [lovell/sharp#2164]
What are you trying to achieve?

I'm trying to discover whether sharp can crop images. It seems sharp has an `extract` feature that does what I want, but I can't find formal documentation for it. There's also a `crop` method, which is also not documented.

Have you searched for similar questions?

Yes. Google shows they exist, but there is no formal documentation for either method.

Are you able to provide a minimal, standalone code sample that demonstrates this question?

N/A

Are you able to provide a sample image that helps explain the question?

N/A

**Comment by tomprogers** [comment]
It appears that `extract` is documented under "resizing," which strikes me as counter-intuitive. I only found that by searching the repo, and then working backward to the web docs.

**Comment by lovell** [comment]
Hi, the docs will hopefully be gaining a search feature soon - please see the upstream issue https://github.com/egoist/docute/pull/261 if you're able to help.

**Comment by lovell** [comment]
Ahead of full support for documentation search, I added some quick, rudimentary keyword-based searching to https://sharp.pixelplumbing.com/ - for example you can now search for the term "crop" and find details for `extract()`.
