### ISSUE TITLE
Segfaults, hash_table != NULL assertion fails, are back?

### ISSUE THREAD

**Issue by pvdz** [lovell/sharp#2167]
It seems the problems from #1986 are back :/

I've seen it on circleci and on Cloud. Have not tried to repro it myself, yet. Is it on your radar at all?

From circleci on node 12:

> sharp@0.25.2 install ~/proj/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
> info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-linux-x64.tar.gz

...

> (sharp:448): GLib-CRITICAL **: 13:55:03.441: g_hash_table_lookup: assertion 'hash_table != NULL' failed

From Cloud, also on node 12:

Gatsby version Gatsby CLI version: 2.11.8 Gatsby version: 2.20.22

> 15:21:04 PM:  (sharp:36518): GLib-CRITICAL **: 13:21:04.283: g_hash_table_lookup: assertion 'hash_table != NULL' failed
> 15:21:04 PM:  (sharp:36518): GLib-CRITICAL **: 13:21:04.283: g_hash_table_lookup: assertion 'hash_table != NULL' failed (sharp:36518): GLib-CRITICAL **: 13:21:04.283: g_hash_table_lookup: assertion 'hash_table != NULL' failed (sharp:36518): GLib-CRITICAL **: 13:21:04.283: g_hash_table_lookup: assertion 'hash_table != NULL' failed (sharp:36518): GLib-CRITICAL **: 13:21:04.283: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed (sharp:36518): GLib-CRITICAL **: 13:21:04.283: g_hash_table_lookup: assertion 'hash_table != NULL' failed
> 15:21:04 PM: ~/runner-command: line 29: 36518 Segmentation fault (core dumped) ${GATSBY} build --no-color

**Comment by pvdz** [comment]
Yeah that Gatsby Clould.

But I happen to get these locally as well, with little pressure, very early in a build of the main gatsby website, so I'm pretty sure it's not dependency related. Considering how fast it shows up, it might be a different case then before, too.

I'm running 
- node 10.13
- Gatsby CLI version: 2.11.0
- Gatsby version: 2.20.23
- sharp@0.25.2

(sharp:22227): GLib-CRITICAL **: 13:37:25.019: g_hash_table_lookup: assertion 'hash_table != NULL' failed
(sharp:22227): GLib-CRITICAL **: 13:37:25.060: g_hash_table_lookup: assertion 'hash_table != NULL' failed
(sharp:22227): GLib-CRITICAL **: 13:37:25.086: g_hash_table_lookup: assertion 'hash_table != NULL' failed

I'll try to get a stack trace.

**Comment by pvdz** [comment]
(The warnings don't emit a trace in CLI. Is there another place I could find them? Or is a segfault the only way?)

**Comment by pvdz** [comment]
Fwiw, I'm having a hard time reproducing anything in the previous benchmark we used. Even though it shows up really quickly when building the main website. That's interesting. And a little annoying :)

**Comment by pvdz** [comment]
I dunno. After deleting `~/.npm` AND `node_modules` it doesn't seem to repro anymore. It did before after an `npm rebuild`.

I'm still concerned for the cloud case, since there the npm cache shouldn't play a role. But as of right now, I have no solid repro to give you.

I'll leave this issue open for a few days. If I don't get any other reports, I'll consider it a legacy artifact of some kind and close it.

**Comment by cuddlycheetah** [comment]
having the same issue. not fixable by deleting or rebuilding

**Comment by lovell** [comment]
@cuddlycheetah Please ensure you are using the latest version of sharp, currently v0.25.2. To be able to help further we'll need either a backtrace of the crash and/or a complete, standalone code sample that consistently reproduces this problem.

**Comment by cuddlycheetah** [comment]
yes it is the latest version of sharp
![image](https://user-images.githubusercontent.com/28735045/79640311-335a0500-8191-11ea-80d4-5c6f1fefd80b.png)

**Comment by cuddlycheetah** [comment]
asyncjs is causing the problem...

**Comment by phifa** [comment]
facing the same issue when doing `gatsby new ...` 
Using nvm, node 12 on ubuntu 18. 
```

~/projects gatsby new myproject
info Creating new site from git:
Cloning into 'myproject'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 28 (delta 2), reused 14 (delta 2), pack-reused 0
Unpacking objects: 100% (28/28), done.
success Created starter directory layout
info Installing packages...

> sharp@0.25.2 install /home/me/projects/myproject/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-linux-x64.tar.gz
ERR! sharp Please delete /home/me/.npm/_libvips/libvips-8.9.1-linux-x64.tar.gz as it is not a valid tarball
ERR! sharp zlib: unexpected end of file
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
make: Entering directory '/home/me/projects/myproject/node_modules/sharp/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  AR(target) Release/obj.target/../node-addon-api/src/nothing.a
  COPY Release/nothing.a
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:23:10: fatal error: vips/vips8: No such file or directory
 #include <vips/vips8>
          ^~~~~~~~~~~~
compilation terminated.
sharp.target.mk:131: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: *** [Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/home/me/projects/myproject/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/me/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.3.0-46-generic
gyp ERR! command "/home/me/.nvm/versions/node/v10.20.1/bin/node" "/home/me/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/me/projects/myproject/node_modules/sharp
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.25.2 install: `(node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.25.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/me/.npm/_logs/2020-04-18T20_03_05_851Z-debug.log

 ERROR 


```

**Comment by lovell** [comment]
@phifa This issue is about possible segfaults at runtime. Your comment is about an installation problem, the solution to which was provided in the log pasted here.
```
ERR! sharp Please delete /home/me/.npm/_libvips/libvips-8.9.1-linux-x64.tar.gz as it is not a valid tarball
ERR! sharp zlib: unexpected end of file
```

**Comment by pvdz** [comment]
I'm going to close this issue. I've not had or seen actual confirmed reports that this is an issue right now. My gut feeling says it is, though, but I'll come back when I have concrete repro's for this.

Sorry for the noise :)
