### ISSUE TITLE
How to merge/join two images into one ?

### ISSUE THREAD

**Issue by nJinss** [lovell/sharp#2168]
What are you trying to achieve?

I am trying to join two images whose width and height is same.

Have you searched for similar questions?

I am searched and read all the related question but it didn't helped me as i was not able to find one code example.

Are you able to provide a minimal, standalone code sample that demonstrates this question?

I want to join two images together.
`imagepath= myimage`
`first= sharp(imagepath).extract(left,top,width, heigth).tobuffer();`
`second=sharp(imagepath).extract(left,top,width, heigth).tobuffer();`
`joined=sharp.JOIN?IDK`

You may be going to mention question related to this which is
https://github.com/lovell/sharp/issues/699 and more but they really didn't help and if possible then please update the documentation with example of joining images. 

Thank You.

**Comment by lovell** [comment]
Hi, did you see #1580 ?

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
