### ISSUE TITLE
Issues when running sharp via grunt with Jenkins

### ISSUE THREAD

**Issue by blowsie** [lovell/sharp#217]
For some reason, I get the following error when I run grunt-sharp from my CI system, Jenkins.
Any ideas what might be causing this?

```
08:51:35 Parsing D:\Builds\xxx\node_modules\grunt-sharp\package.json...OK
08:51:35 Loading "sharp.js" tasks...ERROR
08:51:35 >> Error: error: 126D:\Builds\xxx\node_modules\grunt-sharp\node_modules\sharp\build\Release\sharp.node
08:51:35 >>     at Error (native)
08:51:35 >>     at Module.load (module.js:355:32)
08:51:35 >>     at Function.Module._load (module.js:310:12)
08:51:35 >>     at Module.require (module.js:365:17)
08:51:35 >>     at require (module.js:384:17)
08:51:35 >>     at Object.<anonymous> (D:\Builds\xxx\node_modules\grunt-sharp\node_modules\sharp\index.js:12:13)
08:51:35 >>     at Module._compile (module.js:460:26)
08:51:35 >>     at Object.Module._extensions..js (module.js:478:10)
08:51:35 >>     at Module.load (module.js:355:32)
08:51:35 >>     at Function.Module._load (module.js:310:12)
08:51:35 >>     at Module.require (module.js:365:17)
08:51:35 >>     at require (module.js:384:17)
08:51:35 >>     at Object.module.exports (D:\Builds\xxx\node_modules\grunt-sharp\tasks\sharp.js:8:15)
08:51:35 >>     at loadTask (D:\Builds\xxx\node_modules\grunt\lib\grunt\task.js:325:10)
08:51:35 >>     at D:\Builds\xxx\node_modules\grunt\lib\grunt\task.js:361:7
08:51:35 >>     at Array.forEach (native)
```

When running the same tasks via command prompt, everything works as expected.

Maybe I need a environment variable or something?

https://github.com/unindented/grunt-sharp/issues/5

**Comment by lovell** [comment]
Hi Sam, as you suggest, this could well be related to the environment variables made available by Jenkins to node.

Was a `npm-debug.log` (or similar log file) generated when `npm install` was run by Jenkins? Are you able to get Jenkins to run `npm install --verbose` instead?

**Comment by lovell** [comment]
@blowsie Have you been able to make any progress with this?

**Comment by blowsie** [comment]
No, sorry I forgot about this.

Your response prompted me to test a few thinks in Jenkins, and I realised a few things in the environment had broken after an update; so ended up moving my project to TeamCity.
Closing this ticket for now, thanks for the help.
