### ISSUE TITLE
Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by mosicong** [lovell/sharp#2170]
Something went wrong installing the "sharp" module
3|nail_home  | libvips-cpp.so.42: cannot open shared object file: No such file or directory
3|nail_home  | - Remove the "node_modules/sharp" directory then run
3|nail_home  |   "npm install --ignore-scripts=false --verbose" and look for errors
3|nail_home  | - Consult the installation documentation at https://sharp.pixelplumbing.com/install
3|nail_home  | - Search for this error at https://github.com/lovell/sharp/issues
3|nail_home  |     at Object.<anonymous> (/service/nail_home/node/node_modules/sharp/lib/constructor.js:34:9)
3|nail_home  |     at Module._compile (internal/modules/cjs/loader.js:776:30)
3|nail_home  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
3|nail_home  |     at Module.load (internal/modules/cjs/loader.js:653:32)
3|nail_home  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
3|nail_home  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
3|nail_home  |     at Module.require (internal/modules/cjs/loader.js:690:17)
3|nail_home  |     at require (internal/modules/cjs/helpers.js:25:18)
3|nail_home  |     at Object.<anonymous> (/service/nail_home/node/node_modules/sharp/lib/index.js:3:15)
3|nail_home  |     at Module._compile (internal/modules/cjs/loader.js:776:30)
3|nail_home  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
3|nail_home  |     at Module.load (internal/modules/cjs/loader.js:653:32)
3|nail_home  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
3|nail_home  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
3|nail_home  |     at Module.require (internal/modules/cjs/loader.js:690:17)
3|nail_home  |     at require (internal/modules/cjs/helpers.js:25:18)
3|nail_home  |     at Object.<anonymous> (/service/nail_home/node/app/util/qrCodeUtils.js:7:15)
3|nail_home  |     at Module._compile (internal/modules/cjs/loader.js:776:30)
3|nail_home  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
3|nail_home  |     at Module.load (internal/modules/cjs/loader.js:653:32)
3|nail_home  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
3|nail_home  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
3|nail_home  | 2020-04-18 15:09:12,100 ERROR 6924 [agent_worker] exit with code:110
3|nail_home  | 2020-04-18 15:09:12,711 INFO 6959 [master] =================== egg start =====================
3|nail_home  | 2020-04-18 15:09:12,712 INFO 6959 [master] node version v10.16.0
3|nail_home  | 2020-04-18 15:09:12,712 INFO 6959 [master] egg version 2.9.0

**Comment by mosicong** [comment]
resolved. thanks

**Comment by giankocr** [comment]
How? I have the same issue: 
  System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
