### ISSUE TITLE
Channels reordering

### ISSUE THREAD

**Issue by Reon90** [lovell/sharp#2171]
What are you trying to achieve?
Save images from Graphics API like Vulkan
Have you searched for similar feature requests?
yeah
What would you expect the API to look like?
sharp(inputBuffer, { raw: { order: 'rgb | bgr ' } })
What alternatives have you considered?
Extract each channel and merge in right order
Is there a sample image that helps explain?
no

**Comment by lovell** [comment]
Hi, it should be possible to use the [recomb](https://sharp.pixelplumbing.com/api-operation#recomb) operation to convert from BGR to RGB, something like the following (untested):

```javascript
sharp(inputBuffer, { raw: { ... }})
  .recomb([[0, 0, 1], [0, 1, 0], [1, 0, 0]])
  ...
```

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
