### ISSUE TITLE
Blend with color

### ISSUE THREAD

**Issue by bartrylant** [lovell/sharp#2176]
Hi

Currently I am using imgIx but I want to swap to AWS Serverless Image Handler with Sharp. With imgIX I can do this: `{ blend: '1e3359', bm:'multiply', balph: '80' }`

I.e. blend the image with a color (#1e3359), with multiply and alpha 0.8. Can I do the same with Sharp?

**Comment by lovell** [comment]
Hi, the [composite](https://sharp.pixelplumbing.com/api-composite) operation is your friend. Try something like the following (untested):

```javascript
const { width, height, channels } = await sharp(input).metadata();

const output = await sharp(input)
  .composite([
    {
      input: { create: { width, height, channels, background: "#1e335980" } },
      blend: "multiply"
    }
  ])
  .toBuffer();
```

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
