### ISSUE TITLE
Jest Test - Is giving me the following error: Cannot find module 'sharp'

### ISSUE THREAD

**Issue by josoroma** [lovell/sharp#2177]
When trying to test my aws lambda endpoint or `thumbnail` service which imports an internal lib call `resize`, which imports `sharp` is giving me:

![image](https://user-images.githubusercontent.com/69951/79985430-d2b81a00-8467-11ea-9a18-a85e61946ff7.png)

Any ideas on how to make my test pass?

Thanks!

**Comment by lovell** [comment]
Are you able to provide a repo with a minimal, standalone code/config sample that demonstrates this question?
