### ISSUE TITLE
Extract area that may go out of bounds

### ISSUE THREAD

**Issue by iomturner** [lovell/sharp#2178]
I was wondering if anyone was able to use `.extract` on a region that goes out of bounds. I know you have `.extend` but is there a way to `.extract` but if it fails `.extend` then `.extract`?  Because sometimes I won't know how much to extend without being wasteful.

**Comment by lovell** [comment]
Did you see the future possible enhancement at #1907?

**Comment by iomturner** [comment]
Ah no I didn't that sounds great. Closing this issue.
