### ISSUE TITLE
Manipulating with ghostscript and multiple commands.

### ISSUE THREAD

**Issue by nJinss** [lovell/sharp#2179]
What are you trying to achieve?
I have a image whose some region i want to crop multiple times and them join them back. For joining i am using ImageMagick or 'convert' on ubuntu as sharp don't provide jpining images directly.

This is the code i am currently using 

    
    
    var img2;
    var file3 = '/home/kelly/Desktop/ecc_offline/functions/outFinal.jpeg';
    gs() //Ghostscript
        .batch().safer().nopause().res(600)
        .option('-dTextAlphaBits=4').option('-dGraphicsAlphaBits=4')
        .option('-sPDFPassword=' + Password)
        .device('jpeg').output(outImage).input(file)
        .exec((err, stdout, stderr) => {
            if (!err) {
                sharp(outImage)            //Cropping first area
                    .extract({ left: 306, top: 5490, width: 2053, height: 1275 })
                    .toBuffer(function (err, data, info) {
                        img1 = data.toString(); //don't know how to use this 
                        sharp(outImage)               //cropping second area     
                            .extract({ left: 2630, top: 5492, width: 2030, height: 1275 })
                            .toBuffer(function (err, data, info) {
                                img2 = data.toString(); 
                                spawn('convert', [img1, img2, '+append', file3]); // merging both
                                var tmp2 = performance.now();
                                console.log(tmp2 - tmp1);
                            })
                    });
            }
        });
    
     

The spawn or convert image is not created.
How can i chain this properly ?

**Comment by lovell** [comment]
Perhaps use [toFile](https://sharp.pixelplumbing.com/api-output#tofile) rather than `toBuffer` if external command line tools need to access the output.

**Comment by konlikha** [comment]
I thought using buffer over file would be faster as it have to write it to disk and then read it after. Is there a way that i can pipe these without saving it to disk ?

**Comment by lovell** [comment]
This question is about the use of child processes in Node.js so might be more suited to a site such as StackOverflow.
