### ISSUE TITLE
dependencies differ on different platforms

### ISSUE THREAD

**Issue by Monokai** [lovell/sharp#2180]
Just a question trying to understand how this works and if it isn't dangerous in some way.

sharp `25.2` installed on `macOS 10.15.4` has dependency `svg` version `2.46.4`
sharp `25.2` installed on `Docker node:12-alpine` has dependency `svg` version `2.48.0`

These versions differ and have different output because of a bug (#2172).

Shouldn't a specific sharp version always use the same dependency versions or is this impossible?

**Comment by lovell** [comment]
Hi, did you see the https://github.com/lovell/sharp-libvips/ repo?

We try to get dependency versions as close as possible, but the version of librsvg in Homebrew has been behind the latest for some time - I've just checked and 17 days ago https://github.com/Homebrew/homebrew-core/pull/51450 upgraded from v2.46.x to v2.48.x.

At install time, sharp will always look for and use a globally-installed libvips and its dependencies, such as librsvg mentioned here, should you wish to fix dependency versions.

**Comment by Monokai** [comment]
Ah ok, thanks for your clarification. So if I understand correctly the versions that sharp reports via `sharp.versions` are the dependencies from libvips, which is downloaded as a prebuilt package from the repo `sharp-libvips` at installation time. Depending on the installation environment it uses a different prebuilt package that could have slightly different dependencies.

I understand it's hard to fix all versions on all environments. Using the latest common version across all environments probably isn't possible and causes its own set of problems.

**Comment by lovell** [comment]
Yes, the prebuilt binaries are provided to help most people most of the time. The tarballs contain a `versions.json` for debugging purposes, exposed with `sharp.versions` as you saw.

**Comment by Monokai** [comment]
Got it, thanks!
