### ISSUE TITLE
Can't compress a 24 bit jpg to an 8 bit jpg

### ISSUE THREAD

**Issue by quinton-ashley** [lovell/sharp#2184]
What are you trying to achieve?
compress a 24 bit jpg to an 8 bit jpg

Have you searched for similar feature requests?
yes, couldn't find anything

What would you expect the API to look like?

await sharp(in).depth(8).toFile(out);

What alternatives have you considered?
pngquant but it's only for png files

Is there a sample image that helps explain?
no

**Comment by lovell** [comment]
Hi, JPEG images use 8 bits per channel, so a 24-bit JPEG is three-channel RGB and an 8-bit JPEG is single-channel greyscale.

(JPEG images can also use 12 bits per channel, but those are very rare and most software does not support them.)

**Comment by quinton-ashley** [comment]
Oh my bad, thanks for the explanation and for sharp! It's really good :)
