### ISSUE TITLE
Is there a way to 'colorize' image?

### ISSUE THREAD

**Issue by adityapatadia** [lovell/sharp#2185]
What are you trying to achieve?
I am trying to achieve result similar to `colorize` option in ImageMagick.

Have you searched for similar questions?
Yes, could not find anything similar.

Are you able to provide a minimal, standalone code sample that demonstrates this question?
`convert input.jpg --fill gray50 -colorize '10%' output.jpg`

Are you able to provide a sample image that helps explain the question?
Please check input and output images attached.
![output](https://user-images.githubusercontent.com/1086617/80366381-cf2cf480-88a6-11ea-9a61-515846924f91.jpg)
![input](https://user-images.githubusercontent.com/1086617/80366386-d18f4e80-88a6-11ea-9791-a4a325ab61e9.jpeg)

**Comment by lovell** [comment]
Did you see the [tint](https://sharp.pixelplumbing.com/api-colour#tint) operation?

**Comment by adityapatadia** [comment]
It creates problems with the main yellow color as well. Plus we can only specify the color but not its percentage.

**Comment by adityapatadia** [comment]
I might have missed something so if you feel tint can work, can you give an example?

**Comment by lovell** [comment]
Were you able to make any progress with this?

**Comment by adityapatadia** [comment]
Tint does not work for this. It produces results which are not as per requirement. 

I have unfortunately no knowledge of vips internals or C to do any work. You can either keep it or close it as you deem fit.
