### ISSUE TITLE
Cache or memory leak

### ISSUE THREAD

**Issue by rustam87** [lovell/sharp#2187]
Hi
i use sharp for resize image on Node
```
return axios({
    method: 'GET',
    url: photoUrl,
    responseType: 'arraybuffer',
    headers: {
      'Content-Type': 'image/*',
    }
  }).then((response) => {
    return sharp(response.data)
      .resize(100, 100, {
        fit: 'contain'
      })
      .toBuffer()
      .then((data) => {
        return {
          id: photoId,
          base64: Buffer.from(data).toString('base64'),
          url: photoUrl,
        }
      })
      .catch((err, msg) => {
        return {
        }
      });
  })
```

when axios got image from other server, sharp resize image
But i have this node memory
![with_sharp](https://user-images.githubusercontent.com/16744441/80582742-e93a1480-8a17-11ea-9137-b441f85b2b29.jpg)

when i disable sharp i get 
![without_sharp](https://user-images.githubusercontent.com/16744441/80582804-066ee300-8a18-11ea-9d79-541032bb2874.jpg)

as you see,  on second images, peaks - is axios donwload image and memory stabilize after download images

as you see,  on first images, peaks - is axios donwload image but memory not stabilizes after download image

i dont understand this is sharp's cache or sharp's memory leaks
If this is sharp's cache then how to disable it?
if this is sharp's memory leaks, what fix it?

node:  10.13.0
sharp: 0.23.0
 
Thanks

**Comment by lovell** [comment]
Caching within libvips can be disabled via https://sharp.pixelplumbing.com/api-utility#cache

Please see #955 for why you are likely to be seeing the effects of memory allocation and not a leak.

**Comment by rustam87** [comment]
1. I read this question, but  i found one solution - change node version
2. For disable cache 
```
  return sharp(response.data)
       .cache(false);
      .resize(100, 100, {
        fit: 'contain'
      })
```

is this code right?

**Comment by rustam87** [comment]
1. change node version to 12.16.2
2.  set sharp cache - false
![Screenshot of Namespace _ Controller _ Pod - Grafana](https://user-images.githubusercontent.com/16744441/80615491-6a110480-8a48-11ea-92b2-1906e313cf4b.jpg)
the same result

**Comment by lovell** [comment]
If these graphs show Resident Set Size (RSS) then please remember that this includes memory that has been freed but not yet returned to the OS.

Please ensure you've understood everything discussed in #955.

**Comment by rustam87** [comment]
Yes, this images show RSS
i understood that this memory has been freed but not yet returned, but this memory never returne , because when i load more and more images, memory reach limit of pod's memory(1,5 гб) and my pod restart.

![Screenshot of Namespace _ Controller _ Pod - Grafana (1)](https://user-images.githubusercontent.com/16744441/80680072-cb77b880-8ac6-11ea-980e-7d8b58977c43.jpg)

This image show RSS from yesterday 6:00 PM to current moment. As you see,  one pick from 95mb to 430 mb. But this memory not return never. if i load more images i will get more picks and this memory never return until my pod restart
Do you understand what i want to say.

if i again not right, i'll go to read #955 more details
Thanks

**Comment by lovell** [comment]
Please ensure you've read and understood everything discussed in #955.

> RSS reaching a plateau but not hitting OOM is indicative of free memory not being released back to the OS. It is not indicative of a leak.

> Have you tried different memory allocators that return free RSS back to the OS?

**Comment by rustam87** [comment]
Do you mean that it not a memory leak? Its my docker container not return allocated memory to Host system?

**Comment by rustam87** [comment]
i run my project and console.log rss, and i see a rss not grow 
My local project was run on alpine docker image 
In production project was running not alpine docker container
May be it's problem?

**Comment by dnlup** [comment]
@rustam87 the Alpine image should have an allocator that return free RSS as @lovell suggested.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
