### ISSUE TITLE
Help me understand how prebuilt binaries are created / published / found

### ISSUE THREAD

**Issue by marcvangend** [lovell/sharp#2190]
I tried building an existing project in the "alpine-14" Node JS docker image (https://github.com/nodejs/docker-node/blob/master/14/alpine3.11/Dockerfile). It failed with the message `No prebuilt binaries found (target=14.0.0 runtime=node arch=x64 libc=musl platform=linux)`. While this is understandable because Node 14 is pretty new, it made me realize: I don't quite understand how the process of creating prebuilt binaries works. More specifically, I wonder where the binaries are published (is it https://github.com/lovell/sharp-libvips/releases ?), and how I could check myself if there is a matching binary for a given environment.

Thank you for your time.

**Comment by lovell** [comment]
Please upgrade to the latest v0.25.x, which uses N-API and is therefore agnostic of the major version of Node.js.

**Comment by lovell** [comment]
Prebuilt binaries for sharp are downloaded from https://github.com/lovell/sharp/releases

Prebuilt binaries for libvips and its dependencies are downloaded from https://github.com/lovell/sharp-libvips/releases

**Comment by marcvangend** [comment]
Thanks for the prompt reply, I appreciate your help! Good to know that 0.25.x is agnostic of the major Node.js version.

Unfortunately for me, my project uses a package (gridsome) that depends on `sharp@^0.23.2`. What I didn't know until today, is that a caret version range (here `^0.23.2`) locks the left-most **non-zero** digit. This means that `^0.23.2` cannot resolve to version 0.25.2 (whereas `^1.23.2` could resolve to 1.25.2). 

I will ask gridsome to change the sharp version upstream. What do you think - would it be safe for them to change the version range to `>=0.25.2 <1.0.0` to allow for more upgrades in the future?

**Comment by lovell** [comment]
I recommend that modules with a dependency on sharp should (currently) specify `^0.25.2`.

**Comment by marcvangend** [comment]
Excellent. Thanks again!

**Comment by nabilfreeman** [comment]
I had to downgrade from v25 to v23 as I was getting this error when building on CodeShip:

```
prebuild-install WARN This package does not support N-API version undefined 
prebuild-install WARN install No prebuilt binaries found (target=undefined runtime=napi arch=x64 libc= platform=linux)
```

N-API version can't be detected... and then build failed...

```
warning: 
unrecognized command line option ‘
-Wno-cast-function-type
’
sharp.target.mk:123: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: *** [Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/home/rof/src/gitlab.com/lesalon/cms-media-resizer/node_modules/sharp/build'
```

**Comment by lovell** [comment]
@nabilfreeman Please open a new [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) and answer all of the questions if you are still having problems.
