### ISSUE TITLE
How to specify custom vendor path?

### ISSUE THREAD

**Issue by tommedema** [lovell/sharp#2194]
What are you trying to achieve?
I'm trying to specify a custom vendor path, because I'm unable to build for linux on every install as I am using yarn 1 which does not support building for a custom architecture. I've gone through a lot of trouble to get a "vendor folder" for linux x64 which I would now like to always include in my AWS lambda artifact/package under a top level vendor folder.

**Comment by lovell** [comment]
The path to to the vendor directory is baked into the prebuilt `build/Release/sharp.node` file and is defined here:

https://github.com/lovell/sharp/blob/40c00035eea878cd427488e49c53bb71b7ffe186/binding.gyp#L127-L132

If you update this, you'll also need to rebuild `sharp.node` against the alternative shared libraries as they are likely to have different APIs/ABIs.

**Comment by noherczeg** [comment]
You likely need two variables set:
- `sharp_dist_base_url`: https://sharp.pixelplumbing.com/install#custom-prebuilt-binaries
- `sharp_binary_host`: which should point to the url where the packages are available which it'd normally get from github: https://github.com/lovell/sharp/releases

**Comment by noherczeg** [comment]
If for whatever reason you'd need `cwebp-bin`, `mozjpeg`, or `pngquant-bin`, you are in for a hell of a ride. The only thing which worked for me is to download them, commit them in the repo, and copy to `node_modules` as a pre-install step in CI.

**Comment by tommedema** [comment]
Hmm, thanks for the info. This seems like a lot of effort, we've changed to using Jimp until Sharp is available on the Serverless Application Repository https://github.com/lovell/sharp/issues/1772

**Comment by lovell** [comment]
> "I am using yarn 1 which does not support building for a custom architecture"

Perhaps there's something that can be done to help here? Setting the `npm_config_arch` and `npm_config_platform` environment variables is equivalent to passing the `--arch` and `--target` flags to `npm`.
