### ISSUE TITLE
[Question] Would it be possible to cut out a polygon shape from image?

### ISSUE THREAD

**Issue by trsh** [lovell/sharp#2198]
I know there is not direct method documented but maybe it still can be same-have achieved?
![to2](https://user-images.githubusercontent.com/3727523/81318953-ab806000-9097-11ea-9916-a6c6d267dd5b.png)

**Comment by lovell** [comment]
Use an SVG of the shape you need with the [composite](https://sharp.pixelplumbing.com/api-composite#composite) operation.

The "Stream" example in the Readme document does this - see https://github.com/lovell/sharp/blob/master/README.md#stream

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
