### ISSUE TITLE
QESTION: Is it possible to generate thumbnails for PDF using sharp without compiling from source or any easy way?

### ISSUE THREAD

**Issue by shivarajnaidu** [lovell/sharp#2199]
What are you trying to achieve?
Want to generate thumbnail for PDF pages... but it involves compiling from source.. but is there any simple snippet or direct way to do this.. i mean without compiling anything ..

Have you searched for similar questions?
Yes.. find two similar
https://github.com/lovell/sharp/issues/2008
https://github.com/lovell/sharp/issues/1411

**Comment by lovell** [comment]
No, sorry, the two issues you link to provide the same answer.

**Comment by shivarajnaidu** [comment]
Thanks for quick response @lovell 
But my question is  similar to the questions mentioned  but different too..  I mean is there any simple straightforward way to do PDF thumbnail using sharp lib ?

**Comment by lovell** [comment]
No, sorry, the two issues you link to provide the same answer.
