### ISSUE TITLE
Accept raw buffer as input

### ISSUE THREAD

**Issue by mikemorris** [lovell/sharp#220]
For reading pixels from the GPU and then compressing to PNG or JPEG.

```
Error: Input buffer contains unsupported image formatVipsForeignLoad: buffer is not in a known format
```

**Comment by mikemorris** [comment]
It looks like this should be supported upstream by [vips_image_new_from_memory](http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/VipsImage.html#vips-image-new-from-memory), but may not be detected/implemented because of the differing naming convention from [vips_image_new_from_buffer](http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/VipsImage.html#vips-image-new-from-buffer). My local libvips-8.0.2 installed via Homebrew reports `raw` file input/output support when I add it to https://github.com/lovell/sharp/blob/master/src/utilities.cc#L99 and remove the [manual raw support description](https://github.com/lovell/sharp/blob/master/src/utilities.cc#L124-L141).

**Comment by lovell** [comment]
Yes, it should be quite easy to add this, thanks for the suggestion.

We'd need to work out a way for a user to provide the `width`, `height` and number of `channels` alongside the Buffer containing raw data, either as a second parameter to the constructor or via a new method.

This feature would probably have to assume, at least initially, that the raw data is 8 bits per pixel, with 1x channel for greyscale, 2x channel for greyscale+alpha, 3x channel for sRGB or 4x channel for sRGB+alpha.

**Comment by pajtai** [comment]
After trying to pass a buffer from the request npm, I can see that this does not currently work, but from the docs, what kind of buffers can be passed to the constructor?

http://sharp.dimens.io/en/stable/api/#input

    Buffer containing JPEG, PNG, WebP, GIF* or TIFF image data,

**Comment by lovell** [comment]
@pajtai This issue relates to the addition of support for uncompressed pixel data input.

The [sharp.format](http://sharp.dimens.io/en/stable/api/#format) attribute will tell you which compressed formats are available to you (depends on sharp+libvips versions).

> "I can see that this does not currently work"

If you're still having problems, feel free to create a new issue with more details of the error you're experiencing and, if possible, a code sample.

**Comment by pajtai** [comment]
Thanks @lovell - I created #247 with code snippet and explanation of what I'm trying to do.

**Comment by lovell** [comment]
Commit e380576 on the `mind` branch adds support for raw, uncompressed pixel data input via Buffer or Stream.

**Comment by nicolaspanel** [comment]
@lovell : could you share an example of how to use raw inputs?

I tried this:
```js
var H = 100, W = 100, C = 1, n = H*W*C, data = new Uint8Array(n);

for (var i=0; i<n; i++) {data[i] = 0;}

sharp(new Buffer(data.buffer), { rawWidth: W, rawHeight: H, rawChannels: C})
        .toBuffer()
        .then(function () {});
```
but it throws an error (__"Input buffer contains unsupported image format"__)

NB: I'm using v0.13.0 (from master branch)

**Comment by lovell** [comment]
@nicolaspanel Bonjour, please can you try something like `{ raw: { width: W, height: H, channels: C} }` (as `rawWidth` etc. are internal attributes).

Docs (for the master branch): http://sharp.dimens.io/en/latest/api/#sharpinput-options
Test/example: https://github.com/lovell/sharp/blob/master/test/unit/io.js#L915-L928

**Comment by nicolaspanel** [comment]
It works now :+1:  
Thanks a lot

**Comment by lovell** [comment]
v0.13.0 now available, thanks everyone for the original suggestion and help with testing.

**Comment by knyga** [comment]
I am currently on 0.28.3 and it looks like raw input is not supported. I try to execute basic case mentioned in the case: https://github.com/lovell/sharp/blob/master/test/unit/io.js#L915-L928

**Comment by lovell** [comment]
@knyga https://sharp.pixelplumbing.com/api-constructor#examples contains an example of using uncompressed pixel data as input.
