### ISSUE TITLE
Composite and cloud function

### ISSUE THREAD

**Issue by nseb** [lovell/sharp#2200]
Hello ,
I use sharp in google cloud function , I have a problem with composite , (without my code works) 
error: "Error: Input file is missing" , when i create overlay
Can you help me ?

exports.main = (req, res) => {
  const filename = req.query.f;
  let width = Number(req.query.width);
  let height = req.query.height? Number(req.query.height) :null
  if(!filename) {
    res.sendStatus(500).send("No file specified");;
    return;
  }

  const file = bucket.file(filename);
  file.getMetadata().then(function(data) {
  const metadata = data[0];
    res.set('Cache-Control', 'private,no-transform,max-age=300');
    let stream = file.createReadStream();
    stream.on('error', function(err) {
      console.error(err);
      res.sendStatus(err.code).end(err);
    });

    let warningStream = warning.createReadStream(); 
    warningStream.on('error', function(err) {
      console.error("Watning"+ err);
      res.sendStatus(err.code).end(err);
    });

    let transform = sharp()
    transform = transform.resize(width, height , {
      kernel: sharp.kernel.nearest,
      fit: 'cover',
      background: { r: 255, g: 255, b: 255, alpha: 0.5 }
  });
    let overlay = transform.composite([{
    input: warningStream
  }])
  stream.pipe(transform).pipe(overlay).pipe(res)
  });

**Comment by lovell** [comment]
Stream-based input is not supported by the `composite` operation.

https://sharp.pixelplumbing.com/api-composite#composite

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
