### ISSUE TITLE
HEIC isn't rotating correctly.

### ISSUE THREAD

**Issue by coffeebite** [lovell/sharp#2202]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
Yes

What are the steps to reproduce?
I'm using sharp / libvips compiled with libheif. I am trying to transform the attached image, shot from an iPhone. It doesn't seem to rotate correctly.

What is the expected behaviour?
Image rotates correctly.

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

```javascript
const imageUrl = 'https://padlet-uploads.storage.googleapis.com/12/cd405c2b88963128442daf88cc8ccab9/IMG_0620.HEIC'
request({ uri: imageUrl, encoding: null }, async (error, response, body) => {
  const img = sharp(body).rotate()
  const outputBuffer = img.toFormat('jpg').toBuffer()
})
```

Are you able to provide a sample image that helps explain the problem?
https://padlet-uploads.storage.googleapis.com/12/cd405c2b88963128442daf88cc8ccab9/IMG_0620.HEIC

N.B. when you view the image in Mac, it'll show as portrait, but it is actually landscape. 

The metadata I get from sharp for this image:

```
{
  format: 'heif',
  size: 1483481,
  width: 3024,
  height: 4032,
  space: 'srgb',
  channels: 3,
  depth: 'uchar',
  isProgressive: false,
  pages: 1,
  pageHeight: 4032,
  pagePrimary: 0,
  hasProfile: false,
  hasAlpha: false,
  orientation: 6,
  exif: <Buffer 45 78 69 66 00 00 4d 4d 00 2a 00 00 00 08 00 0b 01 0f 00 02 00 00 00 06 00 00 00 92 01 10 00 02 00 00 00 0a 00 00 00 98 01 12 00 03 00 00 00 01 00 06 ... 2162 more bytes>,
  isAnimated: false
}
```

What is the output of running `npx envinfo --binaries --system`?

**Comment by lovell** [comment]
libheif 1.5.0 and libvips latest master produces the expected width and height for me:
```
{
  format: 'heif',
  size: 1483481,
  width: 4032,
  height: 3024,
  space: 'srgb',
  channels: 3,
  depth: 'uchar',
  isProgressive: false,
  pages: 1,
  pageHeight: 3024,
  pagePrimary: 0,
  hasProfile: true,
  hasAlpha: false,
  orientation: 6,
  exif: <Buffer 45 78 69 66 00 00 4d 4d 00 2a 00 00 00 08 00 0b 01 0f 00 02 00 00 00 06 00 00 00 92 01 10 00 02 00 00 00 0a 00 00 00 98 01 12 00 03 00 00 00 01 00 06 ... 2162 more bytes>,
  icc: <Buffer 00 00 02 24 61 70 70 6c 04 00 00 00 6d 6e 74 72 52 47 42 20 58 59 5a 20 07 e1 00 07 00 07 00 0d 00 16 00 20 61 63 73 70 41 50 50 4c 00 00 00 00 41 50 ... 498 more bytes>
}

```

**Comment by lovell** [comment]
I note `isAnimated` is part of your output, but that is not from sharp, so I guess you're using a fork or wrapper, which could be the source of this problem.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by coffeebite** [comment]
Apologies for going MIA. I can confirm this works as expected using the latest version of `libheif`.
