### ISSUE TITLE
Windows SVG, Differences in rendering between 0.24.1 and 0.25.0

### ISSUE THREAD

**Issue by perrin4869** [lovell/sharp#2203]
Hi @lovell, over from https://github.com/itgalaxy/favicons/pull/306 :)
Using the svg in the zip below:
[favicon.zip](https://github.com/lovell/sharp/files/4603544/favicon.zip)

I don't have a windows machine to reproduce this locally, but appveyor (windows) CI in the issue above seemed to produce a different result from linux machines (both my desktop and travis consistently produced the same buffer in 0.24.x as in 0.25.x):

```javascript
const { readFileSync } = require('fs');
const xml2js = require('xml2js');
const sharp = require('sharp');
const sizeOf = require('size-of');

const svgtool = {
    ensureSize(svgSource, width, height) {
      let svgWidth = svgSource.size.width;
      let svgHeight = svgSource.size.height;

      if (svgWidth >= width && svgHeight >= height) {
        // If the base SVG is large enough, it does not need to be modified.
        return Promise.resolve(svgSource.file);
      } else if (width > height) {
        svgHeight = Math.round(svgHeight * (width / svgWidth));
        svgWidth = width;
      } else {
        // width <= height
        svgWidth = Math.round(svgWidth * (height / svgHeight));
        svgHeight = height;
      }

      // Modify the source SVG's width and height attributes for sharp to render
      // it correctly.
      log("svgtool:ensureSize", `Resizing SVG to ${svgWidth}x${svgHeight}`);
      return this.resize(svgSource.file, svgWidth, svgHeight);
    },

  resize(svgFile, width, height) {
      return new Promise((resolve, reject) => {
        xml2js.parseString(svgFile, (err, xmlDoc) => {
          if (err) {
            return reject(err);
          }

          xmlDoc.svg.$.width = width;
          xmlDoc.svg.$.height = height;

          const builder = new xml2js.Builder();
          const modifiedSvg = builder.buildObject(xmlDoc);

          resolve(Buffer.from(modifiedSvg));
        });
      });
    }
};

const svgBuf = readFileSync('path/to/logo.svg');
const svgSource = {
  size: sizeOf(svgBuf),
  file: svgBuf,
};

const background = { r: 0, g: 0, b: 0, alpha: 0 };
const { width, height } = size;

svgtool
            .ensureSize(svgSource, width, height)
            .then(svgBuffer =>
              sharp(svgBuffer)
                .resize({
                  background,
                  width,
                  height,
                  fit: sharp.fit.contain
                })
                .toBuffer() // buffer generated in linux is different from windows in sharp > 0.24.1
            )
```

for at least one of the following values of size:

```js
const sizes = [{
  width: 16,
  height: 16,
}, {
  width: 24,
  height: 24,
}, {
  width: 32,
  height: 32,
}, {
  width: 48,
  height: 48,
}, {
  width: 64,
  height: 64,
}];
```

Just out of curiousity, was wondering what the cause might be, if you have any insights into it. 
And apologies if there are mistakes in the snippet, I adapted it from `favicons` source code!
Thanks!!!

**Comment by perrin4869** [comment]
Oh, the above is true for node `10`, `12` and `14`

**Comment by kleisauke** [comment]
@lovell A possible reason for this difference could be that the MXE-based libvips Windows binaries were compiled with `-ffast-math` prior to the [v8.9.2](https://github.com/libvips/build-win64-mxe/releases/tag/v8.9.2) release.

**Comment by lovell** [comment]
Thanks Kleis, your suggestion would certainly explain this. Let's wait until sharp v0.26.0 picks up a new version of libvips with this change and check again.

**Comment by lovell** [comment]
...and thanks for reporting this Julian.

**Comment by lovell** [comment]
v0.26.0 now available, please can you test @perrin4869

**Comment by perrin4869** [comment]
@lovell Thanks! I don't have a windows machine to test this on unfortunately... neither am I familiar with how to setup a windows environment for developing node ><;;

**Comment by lovell** [comment]
@perrin4869 Thanks for the quick reply and no worries, your situation sounds pretty good to me.

I'll close this for now as I'm pretty certain the prior use of `-ffast-math` would have caused this.
