### ISSUE TITLE
Sharp doesn't recognise colour profile, and doesn't insert one.

### ISSUE THREAD

**Issue by cjroebuck** [lovell/sharp#2207]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
Yes - 0.25.2

What are the steps to reproduce?
1. Load an image with a colour profile, sharp metadata does not recognise the colour profile. 
2 a). Export with sharp using withMetadata(). Outputted image does not have colour profile. 
2 b). Export the same image without using withMetadata(). Outputted image does not have a colour profile.

What is the expected behaviour?
1. Expected sharp to recognise that the image has a colour profile.
2. a) Expected withMetadata() to keep the original EXIF (including the colour profile).
2. b) Expected sharp to insert a web friendly ICC colour profile when not using withMetadata().

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

```js
const run2 = async () => {
  let img = "../images/example.png";
  let sharpImg = await sharp(img);
  let meta = await sharpImg.metadata()
  console.log("metadata", meta); // 1. shows hasProfile: false

  await sharpImg.withMetadata().toFile("../images/exampleUsingwithMetadata.png");
  await sharpImg.toFile("../images/exampleWithoutwithMetadata.png");

  let meta1 = await sharp("../images/exampleUsingwithMetadata.png").metadata();
  console.log(meta1); // 2a. shows hasProfile: false

  let meta2 = await sharp("../images/exampleWithoutwithMetadata.png").metadata();
  console.log(meta2); // 2b. shows hasProfile: false
}

run2();
```

Are you able to provide a sample image that helps explain the problem?

![example](https://user-images.githubusercontent.com/12208/81818138-8a02f680-9525-11ea-92fa-5cc9b385d469.png)
Attached - hopefully github doesn't do anythign to the exif.

You can see the original image has colour profile according to macOS finder, both output images don't:
<img width="918" alt="image" src="https://user-images.githubusercontent.com/12208/81818412-e9610680-9525-11ea-88a5-047fa3556553.png">

What is the output of running `npx envinfo --binaries --system`?

  System:
    OS: Linux 4.19 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 3.47 GB / 7.78 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/bin/node
    npm: 6.14.5 - /usr/src/app/node_modules/.bin/npm

(I'm testing using a docker image based on ubuntu, docker host is macOS. Same issue when testing on macOS btw.)

**Comment by lovell** [comment]
Hi, the `withMetadata` docs are a bit confusing as the description has a mixture of default and non-default behaviour. I've just added commit https://github.com/lovell/sharp/commit/bbff1c222d60b5830a59dac1d436dc33acd04420 that should hopefully make the current behaviour a little easier to understand.

Please see #1323 for a future possible enhancement relating to non-sRGB output profiles.

**Comment by cjroebuck** [comment]
Thanks for that. I'm still confused why the default i.e. without `withMetadata` doesn't add the profile to the image. I noticed the tests only seem to test this feature with jpg not png. 

I'm not too bothered about non-sRGB profile for this case, just want the web friendly one.

**Comment by lovell** [comment]
The default behaviour of web browsers (and most other software) is that a profile-less "RGB" image is considered (non-linear) sRGB. By ensuring sRGB output, an ICC profile is no longer required.

**Comment by lovell** [comment]
The improvement to the docs is now published at https://sharp.pixelplumbing.com/api-output#withmetadata - let's continue to track the addition of custom output profiles at #1323
