### ISSUE TITLE
Throw error when passing invalid data to sharp()

### ISSUE THREAD

**Issue by mikemorris** [lovell/sharp#221]
Passing a ~~raw image buffer~~ JavaScript object to `sharp()` fails silently instead of throwing an error.

**Comment by lovell** [comment]
Hi Mike, input Buffer (and file) validation is "lazy" and occurs only when the `toBuffer` or `toFile` methods are called, or when data is first requested if using Streams.

I suspect the docs probably need to be a bit clearer about this behaviour.

Unless you've found a bug, which is entirely possible :)

**Comment by mikemorris** [comment]
Oops, turns out I was passing in an object instead of a buffer. In this case though, the callback below is never called, and no errors are thrown.
```
sharp({}).toBuffer(function(err, buffer, info) {
  console.log(err);
});
```

**Comment by lovell** [comment]
Ah ha, yes, the parameter-less constructor assumes you'll start to `pipe` the data in at some point, at which everything will come to life and, on completion, the callback function passed to `toBuffer` will be called.

The constructor logic could be tightened a little to throw an Error when something other than `String` or `Buffer` (or `undefined`) is provided. Leave it with me.

**Comment by lovell** [comment]
I've used your `sharp({})` example, amongst [others](https://github.com/lovell/sharp/commit/e2c53b59cefb5e5478163cb303b2ed7e84fa7115#diff-25005ca1e9df9f2579be55c57a358b97), to tighten this part of the API.

This is currently on the `knife` branch and will form part of v0.11.0.  Thanks for the original suggestion.
