### ISSUE TITLE
vips_foreign_heif_compression_get_type error on Raspberry Pi

### ISSUE THREAD

**Issue by narFnarF** [lovell/sharp#2210]
Hi!

I'm trying to run [Bibliogram](https://bibliogram.art/) on a Raspberry Pi 2. When I load a user profile, Bibliogram does something with Sharp and outputs this error before crashing:
`node: symbol lookup error: /media/cle2GB/apps/bibliogram/stage/node_modules/sharp/build/Release/sharp.node: undefined symbol: vips_foreign_heif_compression_get_type`

Bibliogram's creator tried to help me but ultimately suggested me to ask the question here.

For context:
- Running Raspbian GNU/Linux 9.11 (stretch), Kernel: Linux 4.19.66-v7+
   - Raspberry Pi model : 2B
- Bibliogram requires Sharp `^0.25.2`, which requires a recent version of libvips. Unfortunately, my `apt` doesn't have a recent version of libvips. The one available is `libvips42/oldstable,now 8.4.5-1+deb9u1 armhf`
- I tried to build libvips myself from source. This was succesful.
   - I had to install the libvips-dev package from apt to make this work: `libvips-dev/oldstable,now 8.4.5-1+deb9u1 armhf [installed]`
- When doing `npm install` in Bibliogram's folder, it seems that Sharp correctly detect my libvips that I compiled myself:
```
> sharp@0.25.2 install /media/cle2GB/apps/bibliogram/stage/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)

info sharp Detected globally-installed libvips v8.9.2
info sharp Building from source via node-gyp
make: Entering directory '/media/cle2GB/apps/bibliogram/stage/node_modules/sharp/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  AR(target) Release/obj.target/../node-addon-api/src/nothing.a
  COPY Release/nothing.a
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  CXX(target) Release/obj.target/sharp/src/sharp.o
  SOLINK_MODULE(target) Release/obj.target/sharp.node
  COPY Release/sharp.node
make: Leaving directory '/media/cle2GB/apps/bibliogram/stage/node_modules/sharp/build'
```

I tried to search here for `vips_foreign_heif_compression_get_type` and I found this topic: https://github.com/lovell/sharp/issues/1651
I'm still fairly new to the linux world so I didn't understood everything. However, I see it mentionned something about 2 conflicting installations of libvips on the machine. I suspect this might be the case, as there's the one I installed from `apt` and the one I built myself. I tried to uninstall and reinstall in different way but with no success.

Any help would be welcome.

**Comment by lovell** [comment]
> However, I see it mentionned something about 2 conflicting installations of libvips on the machine. I suspect this might be the case, 

Yes, I agree, it looks like the version of libvips found at install time (via pkgconfig) is different to the one found at runtime.

You do not require the `libvips-dev` package to install libvips from source, and this package is probably the source of conflict.

**Comment by narFnarF** [comment]
Thanks for you help

I tried to uninstall `libvips-dev` as you suggested. Now I can't install Sharp. I get this error:

```
info sharp Detected globally-installed libvips v8.9.2
info sharp Building from source via node-gyp
Package libgsf-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libgsf-1.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libgsf-1', required by 'vips', not found
gyp: Call to 'PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --cflags-only-I vips-cpp vips glib-2.0 | sed s\/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
```
I see the error mentions `pkg-config` that you also mentioned in your answer, but I don't know what this is or how to fix it. I'll try to search online in the meantime.

Thanks again

**Comment by lovell** [comment]
Please re-compile libvips from source, including running its `./configure` script to ensure it knows of the available dependencies.

https://libvips.github.io/libvips/install.html#building-libvips-from-a-source-tarball

**Comment by narFnarF** [comment]
I did just that. I re-compiled from source, then reinstalled Bibliogram with `npm install` (I deleted my `node_modules` folder before just to be safe)

Now Bibliogram produces a lot of these errors:
```
Sharp instance emitted an error: [Error: Input buffer contains unsupported image format]
Piped stream emitted na error: [Error: Input buffer contains unsupported image format]
```
I'm guessing I'm missing some libraries?


When I did `./configure`, I had the following output:
```
* build options
native win32:                           no
native OS X:                            no
open files in binary mode:              no
enable debug:                           no
enable deprecated library components:   yes
enable docs with gtkdoc:                no
gobject introspection:                  no
enable radiance support:                yes
enable analyze support:                 yes
enable PPM support:                     yes

* optional dependencies
use fftw3 for FFT:                      yes
Magick package:                         none
Magick API version:                     none
load with libMagick:                    no
save with libMagick:                    no
accelerate loops with orc:              no
  (requires orc-0.4.11 or later)
ICC profile support with lcms:          no
file import with niftiio:               no
file import with libheif:               no
file import with OpenEXR:               no
file import with OpenSlide:             no
  (requires openslide-3.3.0 or later)
file import with matio:                 no
PDF import with PDFium                  no
PDF import with poppler-glib:           no
  (requires poppler-glib 0.16.0 or later)
SVG import with librsvg-2.0:            no
  (requires librsvg-2.0 2.34.0 or later)
zlib:                                   yes
file import with cfitsio:               no
file import/export with libwebp:        no
  (requires libwebp, libwebpmux, libwebpdemux 0.6.0 or later)
text rendering with pangoft2:           no
file import/export with libpng:         yes (pkg-config libpng >= 1.2.9)
  (requires libpng-1.2.9 or later)
support 8bpp PNG quantisation:          no
  (requires libimagequant)
file import/export with libtiff:        no
file import/export with giflib:         no
file import/export with libjpeg:        no
image pyramid export:                   no
  (requires libgsf-1 1.14.26 or later)
use libexif to load/save JPEG metadata: no
```

Looks like I'm missing quite a few things that we previously provided by `libvips-dev`. How do I know which one(s) I really need, and then how will I install it/them?

(sorry, I know those are probably dumb questions. I'm new to this.) :)

**Comment by lovell** [comment]
See https://libvips.github.io/libvips/install.html#dependencies for the possible dependencies you may wish to make available to libvips when compiling it. You'll need the `-dev` variants of these, e.g. for JPEG support you'll need to install `libjpeg-dev` before compilation.

**Comment by narFnarF** [comment]
Ah, thanks for point that out about the `-dev` part. I saw the dependencies section but I was installing the non-dev ones. 

Thanks a lot for you help. It works fine now! :)
