### ISSUE TITLE
Issue: 'win32-x64' binaries cannot be used on the 'linuxmusl-x64' platform/Docker

### ISSUE THREAD

**Issue by sonnyk22** [lovell/sharp#2211]
Hi,

I've just added a `Dockerfile `into my Nodejs project.  I am currently running on `Window 10`.  Although my local Docker Desktop is set to `Linux Containers`, however, when running this `Dockerfile`, I get the below issue.  This same `Dockerfile `builds fine on my `Mac `machine.  

![sharp](https://user-images.githubusercontent.com/6744710/82171144-785a7f80-9894-11ea-9a56-916b493c7f1c.png)

I came across this issue post as well, but did not have luck with it.
[https://github.com/lovell/sharp/issues/1459](url)

What would you recommend me to add in my `Dockerfile `to overcome this issue in Windows 10.

Thank you!

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/install#common-problems

> The architecture and platform of Node.js used for npm install must be the same as the architecture and platform of Node.js used at runtime.

Follow the instructions in the error and run `npm install` inside the container.

**Comment by sonnyk22** [comment]
Thank you!
