### ISSUE TITLE
Resulting png image is larger than source jpg image when resizing down.

### ISSUE THREAD

**Issue by BobbyBabes** [lovell/sharp#2213]
First of all, I realise and accept that I'm doing something silly in my script. I just installed Sharp for the first time and quickly did the script. Less than 90 minutes ago.

---

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

Fresh `yarn add sharp` :
```
In package.json :

  "devDependencies": {
    "globby": "^11.0.0",
    "sharp": "^0.25.3"
  }
```
```
npm view sharp dist-tags.latest
0.25.3
```
```
npm view sharp dist-tags.latest
└── sharp@0.25.3
```
What are the steps to reproduce?
1) Download the following 2 images to a folder in your project:
 image 1 : [https://unsplash.com/photos/1B7vFqOn6og](https://unsplash.com/photos/1B7vFqOn6og) in `Original Size` of `6000 x 4000` (from the dropdown menu in the download button at the top right). File size : 3.6 MB.
image 2 : [https://unsplash.com/photos/fLI2FYqQ0Yo](https://unsplash.com/photos/fLI2FYqQ0Yo) in `Original Size` of `4608 x 2592` (from the dropdown menu in the download button at the top right). File size : 1.0 MB.
2) In the following script, change the input filepath in variable `srcMatchPatterns`.
3) In the following script, change the output file path argument in both occurrences of method `.toFile()`.
4) Run the following script from the root of the project folder with : `node ./source/js/normalise-images`. Or whatever you named it.
5) Adding `{quality: 80}` down to `{quality: 20}` to the `.png()` method has absolutely no effect. The file sizes remain bloated and exactly the same.

Image 1 : bloats from 3.6 MB at `6000 x 4000`, to 9.0 MB at `2560 x 1440`.
Image 1 : bloats from 3.6 MB at `6000 x 4000`, to 5.1 MB at `1920 x 1080`.
Image 1 : shrinks from 3.6 MB at `6000 x 4000`, to 1.2 MB at `720 x 720`.
Image 2 : bloats from 1.0 MB MB at `4608 x 2592`, to 6.0 MB at `2560 x 1440`.
Image 2 : bloats from 1.0 MB MB at `4608 x 2592`, to 3.5 MB at `1920 x 1080`.
Image 3 : shrinks from 1.0 MB MB at `4608 x 2592`, to 892.1 KB at `720 x 720`.
Etc, etc, etc.

```JavaScript
'use strict';
const globby = require("globby");
const sharp = require('sharp');
const path = require('path');
const srcMatchPatterns = ["src/img/**/*.@(png|jpg|jpeg|gif|ico|svg|apng|bmp)"],
      srcIgnore = ["**/node_modules/**"],
      imageFiles = globby.sync(srcMatchPatterns, {nodir: true, ignore: srcIgnore}),
      heightsRatio_16_9 = [1440, 1080, 900, 768, 750, 720, 480],
      heightsRatio_1_1 = [720, 600, 500, 400, 300, 200, 100]
;

if (imageFiles.length > 0) {

    imageFiles.forEach( (imagePath, i) => {
        const image = sharp(imagePath), imageExtension = path.extname(imagePath), imageBasename = path.basename(imagePath, imageExtension);
        const significantFilename = imageBasename.split('___'); // Only for limited testing.
            image
            .rotate()
            .metadata()
            .then( (metadata) => {
                console.log('w x h : ', metadata.width, ' x ', metadata.height);
                heightsRatio_16_9.forEach( (newHeight, i) => {
                    const newWidth = Math.ceil( (newHeight / 9) * 16 );
                    image
                        .resize(newWidth, newHeight, {fit: 'cover'})
                        .png()
                        .sharpen()
                        .toFile('images-magazine-content-01/' + significantFilename[0] + '_' + newWidth + 'x' + newHeight + '.png')
                    ;
                })
                heightsRatio_1_1.forEach( (newHeight, i) => {
                    const newWidth = newHeight;
                    image
                        .resize(newWidth, newHeight, {fit: 'cover'})
                        .png()
                        .sharpen()
                        .toFile('images-magazine-content-01/' + significantFilename[0] + '_' + newWidth + 'x' + newHeight + '.png')
                    ;
                })
            })
            .catch((err) => {
                console.error(err);
            })
    })

}
```

What is the expected behaviour?

That the file sizes will be far smaller because I'm resizing down, and the default compression level for png output is 9.
And especially because the largest image dimension in output is `2560 x 1440`, against input dimensions of `6000 x 4000` and `4608 x 2592` respectively.

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

**Yes**, see the script at Steps to reproduce above.

Are you able to provide a sample image that helps explain the problem?

**Yes**, see the script at Steps to reproduce above.

What is the output of running `npx envinfo --binaries --system`?

```
npx: heeft 1 in 1.593s geïnstalleerd

  System:
    OS: Linux 5.6 Arch Linux
    CPU: (64) x64 AMD Ryzen Threadripper 3970X 32-Core Processor
    Memory: 20.98 GB / 125.68 GB
    Container: Yes
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 14.2.0 - /usr/bin/node
    Yarn: 1.22.0 - ~/.yarn/bin/yarn
    npm: 6.14.5 - /usr/bin/npm
```

**Comment by lovell** [comment]
Hi, JPEG is a lossy format whereas PNG is a lossless format. For photographic input, PNGs are expected to be much larger than JPEG even when dimensions are smaller.

**Comment by BobbyBabes** [comment]
If that's the case, I need to resize at max quality with Sharp and find another tool to do the compression on the resized images. The quest continues.
Thanks for explaining.

**Comment by lovell** [comment]
When saving photographic images in the PNG format, the use of `adaptiveFiltering` can reduce file size:

https://sharp.pixelplumbing.com/api-output#png

**Comment by BobbyBabes** [comment]
I had already tried that, forgot to mention it. Apologies for that. The file sizes didn't change much though. We're talking up to 100 KB smaller on the 9 MB 1440p file.

Yesterday, after my last comment, I bumped into this site : [https://compress-or-die.com/](https://compress-or-die.com/). It managed to reduce file sizes of the images produced by Sharp dramatically. See the screenshots below for `2560 x 1440` (77% smaller) and `1280 x 720` (83.55% smaller) respectively. And it's OK for now.
Because after that, I found this wicked blog post "Optimizing images with Bash script" by Loïc Giraudel which I'm going to look further into : https://hugogiraudel.com/2013/07/29/optimizing-with-bash/

![compress-or-die-1440p-result_20200518_194642](https://user-images.githubusercontent.com/22870070/82328028-9bde1100-99df-11ea-90a1-6a70d36cbe1c.png)

![compress-or-die-720p-result_20200518_194925](https://user-images.githubusercontent.com/22870070/82328077-b2846800-99df-11ea-9257-6455e3f514e7.png)

**Comment by lovell** [comment]
The appearance of "colors: 256" in the screenshot suggests the above service involves a lossy quantisation step before compression. If lossy compression is acceptable, use JPEG not PNG.

**Comment by edreal** [comment]
I would use the JPEG too if I didn't need transparency.

I noticed that the size of sharp JPEG output (with that default 80% quality) can be like 5-10x smaller than PNG's without much noticeable changes in image quality.

**Comment by BobbyBabes** [comment]
Thanks chaps. I'm on it later today (it's 07:20 am here now) and report my findings.

**Comment by BobbyBabes** [comment]
I just ran the modified script (jpg in, jpg out) and the results are in the screenshot. When compared side-by-side with the compressed png versions, I don't notice any difference. But the file sizes are much, much smaller. I'm not a pro though. If an input file is jpg, I'm going to stick to that format at first.

![compress-or-die_sharp_image_sizes_20200520_203202](https://user-images.githubusercontent.com/22870070/82484822-c5c82e00-9ada-11ea-9192-e01d9698dacf.png)

**Comment by lovell** [comment]
Thanks for the updates, this has been a good discussion about lossless vs lossy image formats that applies to most image processing software. I'll close as it is not specific to sharp.

**Comment by squillace91** [comment]
I would like to open this issue again as the actual solution wasn't found yet. I am having issues where my PNG (3.5mb) out is bigger than my PNG IN (2.4mb). I tried changing the compression level but the output png size keeps the same

`     const bufferWithObject = await sharp(data.Body)
                .resize({
                    width: size.width,
                    height: size.height,
                    fit: crop ? sharp.fit.cover : sharp.fit.inside,
                    withoutEnlargement: true,
                })
                .png({ compressionLevel: 9 })
                .toBuffer({ resolveWithObject: true });`

**Comment by lovell** [comment]
@squillace91 Please see the `palette` option of https://sharp.pixelplumbing.com/api-output#png - if you're still having problems please open a new issue and provide sample input image(s) and complete, standalone code.
