### ISSUE TITLE
flatten does not work after using composite

### ISSUE THREAD

**Issue by GeraldWodni** [lovell/sharp#2214]
> Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

yes, at the time of writing this is version `0.25.3`

> What are the steps to reproduce?

1. create image A 
2. flatten, raw and toBuffer image A
3. create image B
4. composite A onto B
5. flatten, raw and toBuffer image B
6. image B still has 4 channels, and the wrong data size (opposed to image A, which flattened correctly)

> What is the expected behaviour?

When `flatten` is used, the resulting image is expected to have 3 channels.

> Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

```javascript
const sharp = require("sharp");
const size = 96;

/* create image A: */
sharp({
        create: {
            width:  size,
            height: size,
            channels: 4,
            background: { r: 100, g: 50, b: 0, alpha: 1.0 }
        }
    })
    .flatten()
    .raw()
    .toBuffer({ resolveWithObject: true })
    .then( buff => {
        /* works fine until here, now lets merge this image onto a new one */
        console.log( `Simple Create (expect size: ${size*size*3}):`, buff.info )

        /* broken */
        sharp({
                /* create image B */
                create: {
                    width:  size,
                    height: size,
                    channels: 4,
                    background: { r: 0, g: 100, b: 0, alpha: 1.0 }
                }
            })
            .composite([{
                /* merge A onto B */
                input: buff.data,
                raw: buff.info
            }])
            .flatten() // this seems to be ignored
            .raw()
            .toBuffer({ resolveWithObject: true })
            .then( buff => console.log( `Composite is not flat (expect size: ${size*size*3}):`, buff.info ) );
    });
```

Output:
```
Simple Create (expect size: 27648): { format: 'raw',
  width: 96,
  height: 96,
  channels: 3,
  premultiplied: false,
  size: 27648 }
Composite is not flat (expect size: 27648): { format: 'raw',
  width: 96,
  height: 96,
  channels: 4,
  premultiplied: true,
  size: 36864 }
```

> Are you able to provide a sample image that helps explain the problem?

I think in this case this step does not help, I care purely about the buffer size

> What is the output of running `npx envinfo --binaries --system`?

```
  System:
    OS: Linux 5.6 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz
    Memory: 1.21 GB / 15.59 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 10.20.1 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.5 - /usr/bin/npm
```

Submitting bugs makes me feel bad, so I wanna make sure to say thank you for providing this great library ;)

**Comment by lovell** [comment]
Hi, you'll need to split the flatten into a separate pipeline, something like the following (untested):

```javascript
const raw =  {
  width: size,
  height: size,
  channels: 4
};
/* create image B */
const create = {
  ...raw,
  background: { r: 0, g: 100, b: 0, alpha: 1.0 }
};
sharp({ create })
  .composite([
    {
      /* merge A onto B */
      input: buff.data,
      raw
    }
  ])
  .raw()
  .toBuffer()
  .then((data) => sharp(data, { raw }).flatten().raw().toBuffer())
  .then( ... )
```

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
