### ISSUE TITLE
How change Quality of Image regardless of file type (jpeg, png, ...)?

### ISSUE THREAD

**Issue by JoBurg007** [lovell/sharp#2220]
Hi, 
I try to change the quality of an image in a certain path after resizing to the width of 700px regardless of the file type.
In the sharp documentation, I only found solutions for certain file types but I like to change the quality for every uploaded image type to 90%.

I found things like:
```
sharp(file.path)
.resize({ 700 })
.jpeg({
    quality: 90
  })
```
But as said I like to change any image type. How to do this? I hope sharp is flexible enough?!

**Comment by lovell** [comment]
Hi, did you see the `force: false` option?

https://sharp.pixelplumbing.com/api-output#jpeg

**Comment by JoBurg007** [comment]
Oh, thanks!
It means with option `force: false`, the compression would only be realized if the file type does match? Something like this:
```
await sharp(file.path)
    .resize({ 700 })
    .jpeg({ quality: 90, progressive: true, force: false })
    .png({ compressionLevel: 9, progressive: true, force: false })
    .webp({ quality: 90, progressive: true, force: false })
    ....
    .toFile(file.path);
```

I think it is recommended to use progressive: true? Am not very sure what progressive scan means. It is scanning the filetype??

**Comment by lovell** [comment]
Please see https://en.wikipedia.org/wiki/Interlacing_(bitmaps) and note WebP does not support this.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
