### ISSUE TITLE
Editing image exposure

### ISSUE THREAD

**Issue by maartenweyns** [lovell/sharp#2221]
#### What are you trying to achieve?
- Edit the exposure of an image, instead of just brightness

#### Have you searched for similar feature requests?
- Yes, and I have not found any (except for one where the guy was also happy with just brightness and didn't find the modulate option in the API), but please tell me if I'm wrong and half-blind :)

#### What would you expect the API to look like?
- Just something like `sharp(input).modulate({exposure: 5});`

#### What alternatives have you considered?
- [Jimp](https://www.npmjs.com/package/jimp), but from what I found, this also does not support exposure, which makes me think it's relatively hard to accomplish? I might be interested in assisting to develop this feature if desired!

**Comment by lovell** [comment]
Hi, you might be able to achieve this by compositing an image over itself using either `multiply` or `screen` blend for shorter or longer exposure respectively.

```javascript
sharp(input)
  .composite([{ input, blend: "screen" }])
  ...
```

https://sharp.pixelplumbing.com/api-composite

**Comment by maartenweyns** [comment]
Right, I did not think of that! I'll give it a try! Thanks for the tip!

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
