### ISSUE TITLE
Openslide: select best input level based on output dimensions

### ISSUE THREAD

**Issue by TAYTS** [lovell/sharp#2222]
I am trying to generate thumbnail file from a large openslide format image(~2Gb), but the resize takes forever to run, not sure if I did it wrongly. Below are my code for trying to generate the thumbnails.

I manage to use `vipsthumbnail` to generate the thumbnail very fast(instant) and I am using the global libvips.

```javascript
sharp('test.scn', {limitInputPixels: false})
  .resize(500, 500)
  .png()
  .toFile('output.png')
  .then(info => console.log(info))
  .catch(err => console.log(err))
```

**Comment by lovell** [comment]
Are you able to provide a sample image?

What versions of sharp, libvips and openslide are you using? On what platform?

**Comment by kleisauke** [comment]
Note that `vipsthumbnail` uses shrink-on-load for Openslide images since version 8.8, which might explain the speed improvement you noticed. See:
https://github.com/libvips/libvips/commit/22ba9106b5c671765d156719ae39e2582279ad04
https://github.com/libvips/libvips/issues/1149

**Comment by TAYTS** [comment]
@lovell  Sorry for missing out the details.

sharp: 0.25.3
libvips: 8.9.2
openslide: 3.4.1
platform: macOS

I am afraid I am not able to provide the actual image but here is a link to a sample data:
http://openslide.cs.cmu.edu/download/openslide-testdata/Leica/Leica-3.scn

**Comment by TAYTS** [comment]
@kleisauke Is the `shrink-on-load` currently supported by sharp or I have missed out the resize configuration?

**Comment by TAYTS** [comment]
Is the fast thumbnail generation supported in the sharp as I can't seem to find the documentation about it?

**Comment by lovell** [comment]
Commit f5f1654 on the work-in-progress [openslide-shrink-on-load](https://github.com/lovell/sharp/tree/openslide-shrink-on-load) branch attempts to add this feature.

@TAYTS Please can you test this.

```sh
npm install lovell/sharp#openslide-shrink-on-load
```

**Comment by TAYTS** [comment]
@lovell I got `[Error: webp: unable to parse image]` after using the new version even with clean install. Do I need to configure the file type specifically? I am testing using the sample data from http://openslide.cs.cmu.edu/download/openslide-testdata/Leica/

**Comment by lovell** [comment]
I think the `Leica-3.scn` sample fails due to https://github.com/openslide/openslide/issues/189 - or are you referring to a different image?

**Comment by TAYTS** [comment]
@lovell  I have tried on the smaller image `Leica-1.scn` and it works on the current stable version (able to generate the output), but I get the same error (unable to parse image) for the new version.

**Comment by lovell** [comment]
Thank you. It looks like shrink-on-load for openslide input is a little more complex than providing a scaling factor. We need to calculate the best level to extract, based on its dimensions vs desired dimensions. Here's the relevant metadata from the [Leica-1.scn](http://openslide.cs.cmu.edu/download/openslide-testdata/Leica/Leica-1.scn) sample:

```
openslide.level-count: 5
openslide.level[0].downsample: 1
openslide.level[0].height: 153470
openslide.level[0].width: 53130
openslide.level[1].downsample: 3.9998986524159981
openslide.level[1].height: 38368
openslide.level[1].width: 13283
openslide.level[2].downsample: 15.998992404088622
openslide.level[2].height: 9592
openslide.level[2].width: 3321
openslide.level[3].downsample: 63.927109191868013
openslide.level[3].height: 2401
openslide.level[3].width: 831
openslide.level[4].downsample: 255.3952147062588
openslide.level[4].height: 601
openslide.level[4].width: 208
```
Let's tag this as an enhancement for now.

**Comment by lovell** [comment]
The "quickest" (to implement) solution to help with this is to allow the extraction of a specific level, rather than the current behaviour of always using the first/largest layer.

The first step in commit 760550c exposes levels via [metadata](https://sharp.pixelplumbing.com/api-input#metadata), e.g. for the `Leica-1.scn` example:

```
{
  format: 'openslide',
  width: 53130,
  height: 153470,
  space: 'srgb',
  channels: 4,
  depth: 'uchar',
  isProgressive: false,
  levels: [
    { width: 53130, height: 153470 },
    { width: 13283, height: 38368 },
    { width: 3321, height: 9592 },
    { width: 831, height: 2401 },
    { width: 208, height: 601 }
  ],
  hasProfile: false,
  hasAlpha: true
}
```

The next step is to allow the required `level` to be specified in the `sharp()` constructor options.

It will then at least be possible for someone to select the most relevant level based on their desired output dimensions.

**Comment by lovell** [comment]
Commit 7f142bd adds the `level` constructor option to use a specific level.

```javascript
sharp('Leica-1.scn', {
  level: 4,
  limitInputPixels: false
})
...
```
This will be in v0.25.4.

**Comment by lovell** [comment]
v0.25.4 is now available.
