### ISSUE TITLE
only metadata without processing

### ISSUE THREAD

**Issue by onip** [lovell/sharp#2225]
What are you trying to achieve?
read metadata of an image without modifying it.

Have you searched for similar questions?
yes

Are you able to provide a minimal, standalone code sample that demonstrates this question?
```js
'use strict';

const sharp = require ('sharp');

const s = sharp ('./avatar.png');

s.toFile ('./copy.png');
s.metadata().then (m => console.dir (m));
```

```bash
$ ls -l 
totale 664
-rw-r-----   1 onip onip 559959 mag 27 09:18 avatar.png
-rw-r--r--   1 onip onip  53737 mag 27 13:06 copy.png
```

as you can see the image is somehow processed (the size being reduced). I'd like any processing of the image to be forbidden.

the real use case is an image serving endpoint (multiple formats in) which can occasionally convert formats (`.tiff` -> `.png`). we need to set some custom headers in the HTTP response for our UI to perform his job. among those informations we send `X-Image-Size: <size>` which, of course, does not correspond to the actual body size being streamed to the browser.

thanks

**Comment by lovell** [comment]
Hi, I'm not quite sure I understand the question. If you require only metadata about the input, and do not require any output image ("any processing of the image to be forbidden"), then the call to `toFile` can be removed.

```diff
  const s = sharp ('./avatar.png');
- s.toFile ('./copy.png');
  s.metadata().then (m => console.dir (m));
```

**Comment by onip** [comment]
Hi, thanks for your answer.

as I said (maybe not clear enough) the real call to `sharp().metadata()` a piece of a nodejs pipeline: `minio stream -> metadata (+ optional convert) -> http response`. that code is just a minimal example.

another solution would be to to have two stream (there's no sane way to fork a `ReadableStream` that I know of), but I think doubling the calls to the source is just a waste of memory, network and processing power.

**Comment by lovell** [comment]
Thanks for the additional information, the use of Stream based IO was not clear from your original question.

Perhaps a more complete code sample that uses Stream based IO and demonstrates the "optional convert" logic would help me/others understand what you're trying to achieve?

**Comment by onip** [comment]
a more complete example.

```js
'use strict';

const { createReadStream } = require ('fs');
const { join } = require ('path');
const { pipeline } = require ('stream');

const express = require ('express');
const sharp = require ('sharp');

const app = express ();

app.get ('/', (req, res) => {
  const rs = createReadStream (join (__dirname, 'source.png'));
  const meta_reader = sharp ();

  meta_reader.metadata ((err, { height, width, size }) => {
    res.set ('X-Image-Height', height);
    res.set ('X-Image-Width', width);
    res.set ('X-Image-Size', size);
  });

  pipeline (rs, meta_reader, res, err => {
    if (err) { console.error (err); }
  });
});

app.listen (9000);
```

```bash
$ curl -v http://localhost:9000/ > dest.png
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9000 (#0)
> GET / HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< X-Powered-By: Express
< X-Image-Height: 245
< X-Image-Width: 245
< X-Image-Size: 559959
< Date: Thu, 28 May 2020 13:42:21 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
< 
{ [16190 bytes data]
100 53737    0 53737    0     0  1156k      0 --:--:-- --:--:-- --:--:-- 1166k
* Connection #0 to host localhost left intact
```

```bash
$ ls -l source.png dest.png 
-rw-rw-r-- 1 onip onip  53737 mag 28 15:42 dest.png
-rw-r----- 1 onip onip 559959 mag 28 15:37 source.png
```

as you can see the `X-Image-Size` header reports the same byte size as `source.png`, but `dest.png` is way smaller and also curl reports the "correct" downloaded size.

I'd like the original stream ( `source.png` ) to flow unmodified through the pipeline.

**Comment by lovell** [comment]
Thank you. I don't see any conditional logic here for the  "occasionally convert formats" / "optional convert" step, which I think might be key to the question.

**Comment by onip** [comment]
I omitted it for simplicity, also the one without conversion is the use case we care most of. using sharp just for reading metadata modifies the input image. 

it really is something like

```js
let meta_reader;
if (need_conversion) {
  meta_reader = sharp ().toFormat ('png')
} else {
  meta_reader = sharp ();
}
```

where `need_conversion` is a boolean passed to the factory function of the http handler.

**Comment by lovell** [comment]
@onip Were you able to make any progress with this?

**Comment by onip** [comment]
@lovell nope, problem is still present.

```js
'use strict';

const {
  createReadStream,
  createWriteStream,
} = require ('fs');
const { pipeline: _p } = require ('stream');
const { promisify } = require ('util');

const sharp = require ('sharp');

const pipeline = promisify (_p);

(async () => {
  try {
    await Promise.all ([
      pipeline (
        createReadStream ('./source.png'),
        createWriteStream ('./dest_raw.png'),
      ),

      (async () => {
        const meta_reader = sharp ();
        meta_reader.metadata ((err, { height, width, size }) => {
          if (err) {
            console.error (err);
          } else {
            console.log ('height', height);
            console.log ('width ', width );
            console.log ('size  ', size  );
          }
        });

        await pipeline (
          createReadStream ('./source.png'),
          meta_reader,
          createWriteStream ('./dest_sharp.png'),
        );
      }) (),
    ]);
  } catch (err) {
    console.error (err);
  }
}) ();

```

```bash
$ ls -l *.png
-rw-rw-r-- 1 onip onip 19907 mag 17 10:06 dest_raw.png
-rw-rw-r-- 1 onip onip 16556 mag 17 10:06 dest_sharp.png
-rw-rw-r-- 1 onip onip 19907 mag 17 09:59 source.png
$ npm ls sharp
sharper@1.0.0 /home/onip/workspace/sharper
└── sharp@0.28.2 
```

the interesting bit is that the size is correctly identified (`19907`) but is modified on output.
```bash
$ node index.js 
height 200
width  200
size   19907
```

**Comment by lovell** [comment]
Thanks for the update, I think I better understand the scenario now.

A `sharp` instance will always perform a decode/encode roundtrip when it is treated as a `ReadableStream`, that is when an _output_ image is requested from it.

The number of bytes required to read from a `ReadableStream` in order to determine valid `metadata` is not known e.g. there can be huge ICC profiles, XMP payloads etc.

I'd recommend the use of a module like https://www.npmjs.com/package/peek-readable to peek ahead a fixed number of bytes. You'll need to experiment with a given set of inputs to determine the best value for this. Perhaps try something like the following (untested):

```js
const {
  createReadStream,
  createWriteStream,
} = require ('fs');
const { StreamReader } = require('peek-readable');
const HEADER_SIZE = 1024;

const source = createReadStream('./source.png');
const dest = createWriteStream('./dest_sharp.png');
const converter = sharp().png();

const sourceReader = new StreamReader(source);
const sourceHeader = Buffer.alloc(HEADER_SIZE);
await streamReader.peek(sourceHeader, 0, HEADER_SIZE);

const metadata = await sharp(sourceHeader).metadata();
const need_conversion = ... // logic that uses metadata

if (need_conversion) {
  await pipeline(
    sourceReader,
    converter,
    dest
  );
} else {
  await pipeline(
    sourceReader,
    dest
  );
}
```

**Comment by onip** [comment]
ok, got it, thanks.

i guess this can be closed.
