### ISSUE TITLE
Using composite to join to images into a larger one, possible?

### ISSUE THREAD

**Issue by justuscook** [lovell/sharp#2228]
I was reading through issues and was trying to find out what the best way to go about "stacking" an image on top of another to make one larger image containing the provided 2 images.  What I gathered was to use a larger blank image, then composite the 2 desired images on to it.  Is this still the best way to do this currently?  Thanks for any help.

**Comment by lovell** [comment]
Are you able to provide a minimal, standalone code sample that demonstrates this question?

Are you able to provide a sample image that helps explain the question?

**Comment by justuscook** [comment]
I just tried it out, and was able to get it working for my case.  I am downloading images into a buffer, but it would be almost the same for a local image.  Maybe this will help the next person looking:
```
sharp({
            create: {
                width: 128,
                height: 256,
                background: {alpha: 1, r: 255, g: 0, b: 0},
                channels: 4
            }
        })
        .composite(
            [
            {input: image1Buffer,top: 0, left: 0},{input: image2Buffer, top: 128 , left: 0}
        ])
        .png()
        .toFile('testImage.png');
```

**Comment by lovell** [comment]
Thank you for providing a code sample. The possible future enhancement discussed in #1580 will help this scenario.
