### ISSUE TITLE
Sharp w/ React Native

### ISSUE THREAD

**Issue by destinybonavita** [lovell/sharp#2229]
What are you trying to achieve?

I'm trying to use Sharp with my Expo React Native Application

Have you searched for similar questions?

Yes. I've seen people in the `Issues` page list things related to Expo and React Native, but I haven't full understood how people are getting it to work.

What I've done is very simple so far:

In a terminal of your choice execute the following
```bash
# Select "Blank App" in Options
expo init App

# Move into App directory
cd app

# Install Sharp
npm install sharp --save
```

However, when actually trying to use Sharp I ran into multiple issues.
I've had to install `color-converter` and `events`, but even after that I started getting the error `Unable to resolve module util` but to my knowledge that won't be able to be resolved because of react native.

Is there an existing guide for using Sharp with React Native or with Expo?

**Comment by destinybonavita** [comment]
I just tried manually installing `util` and `stream`, but now I'm getting the error `Unable to resolve "../build/Release/sharp.node" from "node_modules/sharp/lib/constructor.js"`

**Comment by lovell** [comment]
This module requires a Node.js runtime. I think React Native uses Safari's JavaScriptCore engine, which won't work.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by KouSyurei** [comment]
I have the same problem now. Thank you very much. If you solve this problem, could you tell me your solution? @destinybonavita

**Comment by destinybonavita** [comment]
I didn't end up finding a solution unfortunately. I had to move on from the project that required sharp for a meantime but I do plan on looking back into it eventually. Sharp is an amazing tool for Node.js and I'd love for it to be accessible in React Native.

**Comment by hengkx** [comment]
Are there any other libraries that can be used on RN？

**Comment by dmitrizzle** [comment]
Looks like there's a solution out there. I don't use RN but perhaps it'll help someone: https://zameermfm.medium.com/handling-libvip-sharp-errors-in-react-native-expo-installation-8eb592b6314b

**Comment by CrackerKSR** [comment]
> Are there any other libraries that can be used on RN？
ffmpeg for RN is there but it is heavier.
