### ISSUE TITLE
Feature Request: Support for other "deep zoom" output formats (Google, Zoomify)

### ISSUE THREAD

**Issue by bdunnette** [lovell/sharp#223]
Since vips_dzsave supports output in different metadata & directory layouts (specifically, ones compatible with Zoomify and Google Maps) via its `layout` parameter, would it be possible to add this capability to sharp?

**Comment by lovell** [comment]
Yes, this should be a relatively straightforward addition, thank you for the suggestion.

I'm happy to help steer you through the process of adding this feature via a Pull Request, should you be feeling eager and/or brave :)

**Comment by bdunnette** [comment]
@lovell I'd be willing to try to make it a pull request, given a little guidance!

**Comment by lovell** [comment]
Excellent.

If you've not already seen it, the [CONTRIBUTING](https://github.com/lovell/sharp/blob/master/CONTRIBUTING.md) guide has a few basics.

For the API, I'd suggest extending the existing [tile](https://github.com/lovell/sharp#tilesize-overlap) method to be something like `tile([size], [overlap], [layout])`, where `layout` is one of `sharp.tile.zoomify`, `sharp.tile.google` or `sharp.tile.deepzoom` (the default).

**Comment by lovell** [comment]
@bdunnette Have you been able to make any progress? Anything I can help with?

**Comment by lovell** [comment]
Commit 38ddb3b on the `needle` branch adds the ability to use Zoomify and Google directory layouts.

This does break the existing `tile` API slightly, but with the benefit of making space for things like #337.

**Comment by lovell** [comment]
v0.14.0 now available via npm, thanks for the original suggestion.
