### ISSUE TITLE
How to get the MIME type of an image file and can sharp handle animated gifs?

### ISSUE THREAD

**Issue by aysiscore** [lovell/sharp#2232]
In the [docs](https://sharp.pixelplumbing.com/api-input), I can only see `metadata.format` as a way of telling what the file "decoder" is.

An `.exe` file can be given an innocent extension of `.jpg` which would be flagged up when checking the MIME type instead of just the file extension. Does `metadata.format` get the correct MIME type or just the file extension? 

And... if the file is an animated GIF, can sharp resize it without losing the animation or do I need to use ImageMagick for that?

**Comment by lovell** [comment]
The `format` property returned by `metadata()` is not the same as MIME type. You'll need to manage your own mapping, perhaps via something like https://www.npmjs.com/package/mime-db

Please see #1372 for a future possible enhancement that, when using a globally-installed libvips compiled with support for *magick, will allow GIF output.
