### ISSUE TITLE
When the constructor options is set to { limitInputPixels: 0 }, input high pixel images, the tile options.background { r: 0, g: 0, b: 0, alpha: 0 } does not take effect

### ISSUE THREAD

**Issue by aute** [lovell/sharp#2233]
**Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?**

Yes
***

**What are the steps to reproduce?**

**Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?**

```javascript
const image = sharp(`files/input/test.png`, { limitInputPixels: 0 });
image
    .png()
    .tile({
        layout: 'google',
        background: { r: 0, g: 0, b: 0, alpha: 0 }
    })
    .toFile(`files/output/test`, function (err, info) {});
```
The test.png  is 114000× 6000 pixels.
***

**What is the expected behaviour?**

I want the background is transparent. But now it's black.

I tested lower resolution images and the results were as expected.

**Comment by lovell** [comment]
Please can you provide a sample image that reproduces this behaviour.

**Comment by aute** [comment]
> Please can you provide a sample image that reproduces this behaviour.

![test](https://user-images.githubusercontent.com/17873165/83368372-23b61900-a3eb-11ea-9bb0-1a2d62fccdc3.png)

the 0-0-0.png
![0](https://user-images.githubusercontent.com/17873165/83368413-46e0c880-a3eb-11ea-8948-ac6be4f6188b.png)

**Comment by lovell** [comment]
Thanks, this sample input does not have an alpha channel, so if you want one on the output you'll need to add `ensureAlpha`.

```diff
 image
+    .ensureAlpha()
     .png()
     .tile({
```

https://sharp.pixelplumbing.com/api-channel#ensurealpha

**Comment by aute** [comment]
Thanks, you are right🙇‍♂️
