### ISSUE TITLE
does not work on node 14

### ISSUE THREAD

**Issue by zsolt-dev** [lovell/sharp#2235]
After upgrading to node 14 (from node 13) any image I try to upload fails with error:

```
[Error: VipsJpeg: Premature end of JPEG file
VipsJpeg: out of order read at line 256
```

My code:

```js
  const resizer = sharp()
    .resize(width, height)
    .rotate() // auto-rotated using EXIF Orientation tag
    .composite([{ input: watermark, gravity: 'southeast' }])
    .jpeg({ quality: 85, progressive: true });

  return new Promise((resolve, reject) =>
    stream
      .pipe(resizer)
      .on('error', (error) => {
        reject(error);
      })
      .pipe(file.createWriteStream({ resumable: false, ...metadata }))
      .on('error', (error) => {
        reject(error);
      })
      .on('finish', () => resolve())
  );
```

after adding failOnError: true, the image is incomplete (only the first third of the image is visible, the rest is grey)

Latest version of sharp:
sharp@0.25.3

  System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 245.39 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.3.0 - ~/.nvm/versions/node/v14.3.0/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v14.3.0/bin/npm

**Comment by lovell** [comment]
The error is occurring on the input side but it's unclear from this example what `stream` refers to.

There are a number of breaking changes in Node 14 relating to Stream-based I/O, unrelated to sharp - see https://nodejs.org/en/blog/release/v14.0.0/

Please can you provide a complete, standalone code sample and image, without other dependencies, that allows someone else to reproduce the problem.

**Comment by zsolt-dev** [comment]
You are right. 

It works fine with node 14, problem was with the changes in the streams.

Sorry

**Comment by MEsteves22** [comment]
Hello! Unfortunately, I am currently having the same problem where the bottom of my image is grey. If I don't resize my image everything is okay though. Were you able to solve this?

**Comment by dutscher** [comment]
i got now issues with node14 and a not working binary on my jenkins.

any news abot that?

cheers
