### ISSUE TITLE
The options for "binaries cannot be used" 

### ISSUE THREAD

**Issue by hg-pyun** [lovell/sharp#2236]
I have same issue known as "xx binaries cannot be used xxx"  with docker.
The best solution is that install in docker container. But, I am try to install outside docker. 

So, I find alternative solution.
```js
rm -rf node_modules/sharp
npm install --arch=x64 --platform=linux --target=8.10.0 sharp
```
Is `--arch` and `--platform` npm spec? I don't see the spec in official document.

**Comment by lovell** [comment]
Please can you provide (quite a bit) more information about what you are trying to achieve.
