### ISSUE TITLE
QUESTION: Is it possible to fill the background color dynamically with image background in contain fit?

### ISSUE THREAD

**Issue by sanjay22nava** [lovell/sharp#2237]
I have the original image with a size of 620 x 360. I'm trying to resize the image and maintaining the aspect ration and background color with the following code. 

```
sharp(input)
  .resize(400, 400, {
    fit: 'contain',
  })
```

With the fit: 'contain', It adds the black background or any background color specified in the code. It is possible to maintain background-color as an original image background color?

![ig2](https://user-images.githubusercontent.com/54605355/83585072-e0f15f80-a516-11ea-8fc3-6bc52c32c389.png)

Expected:
![ig](https://user-images.githubusercontent.com/54605355/83585032-c919db80-a516-11ea-84da-c894e550a95c.png)

**Comment by lovell** [comment]
You'll need to extract the background colour of a suitable pixel first.

The following example extracts the top-left pixel:

```javascript
const [r, g, b] = await sharp(input)
  .extract({ left: 0, top: 0, width: 1, height: 1 })
  .raw()
  .toBuffer();

const background = { r, g, b };
```

**Comment by sanjay22nava** [comment]
Thanks, this is exactly what I was looking for.
