### ISSUE TITLE
Is there a way to set a timeout for a conversion?

### ISSUE THREAD

**Issue by quekshuy** [lovell/sharp#2239]
What are you trying to achieve?
I'm trying to fail a conversion that takes too long?

Have you searched for similar questions? 
Yes.

Are you able to provide a minimal, standalone code sample that demonstrates this question?
No.

Are you able to provide a sample image that helps explain the question?
Taking any reasonably large image from https://pixabay.com/ and applying a blur on it.

**Comment by lovell** [comment]
Hi, you'll need to write your own logic to handle timeouts.

**Comment by quekshuy** [comment]
Got it. Thanks for answering.

**Comment by adityapatadia** [comment]
Just checking here, even if we want to write logic, what is best way to cancel `.toBuffer()` calls?

**Comment by haoxi911** [comment]
> Just checking here, even if we want to write logic, what is best way to cancel `.toBuffer()` calls?

I have the same question. In my scenario, I have an express server fulfill image requests from client apps, the app might send hundreds of image requests in a few seconds, most of the requests will be cancelled within 100ms. So I would hope there is a way to cancel `.toBuffer()` when `sharp` is still processing the image.

Right now, I am using debounce on server side as a workaround, it works though not perfect.

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/api-output#timeout
