### ISSUE TITLE
Support for 64-bit node.exe on Windows

### ISSUE THREAD

**Issue by sabrehagen** [lovell/sharp#224]
Hi,

I'm sorry if this question is documented somewhere - I searched, but I didn't find. Do you have plans to support 64-bit Windows? If so, do you know what date you plan to support it by?

Thanks.

**Comment by lovell** [comment]
Hi Jackson, we ran into quite a few problems whilst adding support for Windows in general as part of #19, with 64-bit support being particular elusive, most likely as libvips currently provides only [32-bit](http://www.vips.ecs.soton.ac.uk/supported/current/) pre-compiled libraries.

If you can make time to help get it working that would be great.

Step 1 is to remove the [_WIN64](https://github.com/lovell/sharp/blob/master/src/common.cc#L9) guard and discover/fix what breaks.

**Comment by lovell** [comment]
This module does work on 64-bit Windows when run using a 32-bit Node.js (or 32-bit io.js) executable. The [Windows CI](https://ci.appveyor.com/project/lovell/sharp) environment runs on the 64-bit Azure platform.

The enhancement here relates to use with a 64-bit Node.js executable.

**Comment by sabrehagen** [comment]
Thanks for clarifying, my error.

**Comment by lovell** [comment]
@sabrehagen Does your comment mean you're using a 32-bit Node.js executable and have been able to get it working?

**Comment by sabrehagen** [comment]
Sorry, no, I'm only using 64-bit io.js, and unfortunately don't have the skills to dedicate to fixing the 64-bit issue. Keenly awaiting somebody who does contributing to the project though! :)

**Comment by lovell** [comment]
https://github.com/jcupitt/build-win32/issues/10 will help greatly with this.

**Comment by jcupitt** [comment]
I'm trying to make a 64-bit Windows libvips binary here: https://github.com/jcupitt/build-win64

I'll update if I get it working.

**Comment by jcupitt** [comment]
I have a test build of 64-bit libvips for Windows:

http://www.vips.ecs.soton.ac.uk/development/vips-dev-w64-8.1.1.zip

I've not done much testing, but at least running `vips.exe` at the command-line seems to work, and it does appear to be a 64-bit binary. If anyone has time to give it a good kicking, that would be wonderful. 

Build script plus README here if anyone wants to make their own https://github.com/jcupitt/build-win64

**Comment by lovell** [comment]
Marvellous, thanks @jcupitt - I'll take a look over the weekend.

**Comment by lovell** [comment]
The [first attempt](https://ci.appveyor.com/project/lovell/sharp/build/job/frcjgu6wcsc29x8m) at using 64-bit everywhere with the Windows CI environment gives the dread "specified procedure could not be found" error at runtime. I'll try to reproduce/debug locally, possibly tomorrow.

**Comment by jcupitt** [comment]
Oh dear :-( it's built with the same compiler as before, just in 64-bit mode, so you'd think it would just drop in. Ah well.

I've just enabled some new shrink code with a nice performance boost, it should help sharp:

https://github.com/jcupitt/libvips/commit/11ce13d43d549d2ee367900ee8f27217f2cf3f3f

with `vipsthumbnail` and the old code I see:

```
$ time vipsthumbnail Chicago.png --vips-leak
memory: high-water mark 145.85 MB
real	0m4.300s
user	0m4.228s
sys	0m0.072s
```

With the new code it's:

```
$ time vipsthumbnail Chicago.png --vips-leak
memory: high-water mark 89.42 MB
real	0m3.843s
user	0m3.800s
sys	0m0.044s
```

**Comment by lovell** [comment]
@jcupitt I've been able to reproduce this problem locally. Dependency Walker reveals that the glib functions used by sharp are unavailable at runtime despite `libglib-2.0-0.dll` being available on `PATH`. I've checked there are no other/different glib versions lingering.

I notice [build-win32](https://github.com/jcupitt/build-win32/blob/master/8.1/get-win32-packages.sh#L27-L28) uses a pre-built glib whereas [build-win64](https://github.com/jcupitt/build-win64/blob/master/8.1/vips.modules#L434) compiles it from source.

I spotted the glib docs [recommend](https://github.com/GNOME/glib/blob/master/README.win32#L91) it be compiled with the `-mms-bitfields` flag to allow gcc-compiled (e.g. `libvips-42.dll`) and MSVC-compiled (e.g. sharp) code to both use it, but it looks like this is [already the case](https://github.com/jcupitt/build-win64/blob/master/8.1/jhbuildrc#L87-L89).

Would you be willing/able to create a win64 .zip that uses a prebuilt version of glib instead of compiling from source, if only to remove this as a possible conflict? The most recent win64 glib binary seems to be [v2.26](http://ftp.gnome.org/pub/GNOME/binaries/win64/glib/2.26/) (whereas for win32 it's [v2.28](http://ftp.gnome.org/pub/GNOME/binaries/win32/glib/2.28/)).

Great work on the shrink speed-up! As an aside, the next version of sharp will ship with the ability to download a pre-compiled libvips (but only after checking for a "global" install via `pkg-config`). This means everyone can take advantage of these sort of improvements as soon as possible. Subscribe to #42 if you're interested in updates.

**Comment by lovell** [comment]
@jcupitt The `.zip` generated by build-win32 provide import library files e.g. `lib\glib-2.0.lib` but the build-win64 does not. I was using the `.dll.a` files e.g. `lib\libglib-2.0.dll.a` for linking with MSVC but I now believe those are valid for for gcc only.

The solution here might be as "simple" as generating the `.lib` import library files for the corresponding glib/gobject/etc `.dll` files, especially as mingw-w64 provides the [dlltool](http://sourceforge.net/p/mingw-w64/wiki2/Answer%20generation%20of%20DLL%20import%20library/) to do this.

**Comment by jcupitt** [comment]
Sorry for the silence. Unfortunately the prebuilt win64 DLLs on the GNOME ftp site are too old. Reading the mailing lists, it seems they're giving up providing 64-bit DLLs due to lack of resources, so I had to compile a lot more from source. 

I'll see if I can make some .lib files.

**Comment by lovell** [comment]
@jcupitt Thanks for the update - I'm sorry for suggesting we use such an old version of glib - I'm pretty certain having the correct `.lib` files for at least glib and gobject will solve this.

On a partly related note, I've been experimenting with Travis+homebrew for the semi-automated provision of pre-compiled `.dylib` files for OS X users - see https://github.com/lovell/package-libvips-darwin-x64/blob/master/.travis.yml

**Comment by jcupitt** [comment]
Update: it seems there are many, many ways to generate the .lib and .def files, even the compiler can do it, if you get the flags right. What I've not found is a switch to configure or a script that will run over a set of DLLs and make the extra files for me. You'd think there'd be some liibtool flag for this.

I've posted a question on the gtk mailing lists asking how they used to handle this. It must be somwthing simple.

**Comment by jcupitt** [comment]
I heard back and I've had a go:

http://www.vips.ecs.soton.ac.uk/development/vips-dev-w64-8.1.1-1.zip

The vips package script now runs a thing over the `bin/` directory before zipping which attempts to generate any missing `.lib` and `.def` files with a combination of `gendef` and `dlltool`. I don't know if I'm handling names correctly, I can't test it :-( but it might work.

Patch to add this thing here:

https://github.com/jcupitt/build-win64/commit/5b12eab53bde32a0538685a7ba6aae5c9fe05189

**Comment by jcupitt** [comment]
The mailing list thread where I asked, for reference: https://mail.gnome.org/archives/gtk-devel-list/2015-November/msg00009.html

**Comment by lovell** [comment]
@jcupitt Hooray! https://ci.appveyor.com/project/lovell/sharp/build/224/job/6y0bq6dekflj2f6v Thank you for persisting with this.

@sabrehagen sharp will gain official support for Windows x64 in v0.12.0.

**Comment by jcupitt** [comment]
IT'S A MIRACLE

Well done @lovell!

**Comment by jcupitt** [comment]
... and I'll make a copy of that test w64 .zip in the official vips supported area.

**Comment by jcupitt** [comment]
There's now an official windows64 vips zip here:

http://www.vips.ecs.soton.ac.uk/supported/current/win32/vips-dev-w64-8.1.1-2.zip

It's slightly different from the zip you used for testing, but I think should still work.

**Comment by sabrehagen** [comment]
@lovell thank you, it has been very interesting to follow this thread!
