### ISSUE TITLE
How to only trim alpha=0 ?

### ISSUE THREAD

**Issue by SilenceLeo** [lovell/sharp#2240]
## What are you trying to achieve?

I just want to trim transparent pixels (alpha=0) when has alpha image.
Don't trim it when it is a solid color image.
The current Trim method cannot do this.
Whether possible to provide a new method or extend the params of the trim()?

## Have you searched for similar questions?
Yes, but not fix my question.

## Are you able to provide a minimal, standalone code sample that demonstrates this question?
```javascript
sharp(inputPath)
    .trim(1)
    .toFile(outputPath)
    .catch((e) => console.log(e));
```

## Are you able to provide a sample image that helps explain the question?

input image: ![image](https://user-images.githubusercontent.com/4632034/83719028-cf1fd180-a668-11ea-82f5-346b2de0fd48.png)  output img: ![image](https://user-images.githubusercontent.com/4632034/83719057-de9f1a80-a668-11ea-82ae-c6cef09fb3d4.png)   expect: no trim

input image: ![btn-share](https://user-images.githubusercontent.com/4632034/83719421-9fbd9480-a669-11ea-9f7f-695789c74f5a.png)   output img:  ![btn-share](https://user-images.githubusercontent.com/4632034/83719409-99c7b380-a669-11ea-8a10-479e9f787909.png)   expect: no trim

input image: ![color-black](https://user-images.githubusercontent.com/4632034/83719580-f75c0000-a669-11ea-9e9c-51797165eeda.png)    output img: [![color-black](https://user-images.githubusercontent.com/4632034/83719601-fe830e00-a669-11ea-9f2a-51c96cb864b7.png)]    expect: no trim

### Expect best output
input image:  ![image](https://user-images.githubusercontent.com/4632034/83720656-10fe4700-a66c-11ea-9934-e4811cbdc205.png)  output img: ![image](https://user-images.githubusercontent.com/4632034/83720668-1a87af00-a66c-11ea-8b7d-c15738f8f979.png)

At last , I'm sorry for my bad English.

**Comment by lovell** [comment]
Hi, please see the future possible enhancement at #2166.
