### ISSUE TITLE
Are tiled/pyramidal TIFF supported as input? And is single tile extraction from it possible?

### ISSUE THREAD

**Issue by ConPac** [lovell/sharp#2241]
Hi,

I'm currently using sharp as an image format converter: it's fluent API is very nice to use. I've read about its tiled output capabilities, but found nothing about tiled/pyramidal TIFF input (which I take for granted) and single tile extraction from it.

Given that my source images are tiled/pyramidal TIFFs, from which I extract single tiles using libtiff depending on level/zoom and tile's coordinates, I was wondering if sharp is capable of handling this in some way.

Thanks in advance,
Paco.

**Comment by lovell** [comment]
Hi, this is being discussed in #2222 

(You'll also need a globally-installed libvips compiled with support for OpenSlide.)

**Comment by ConPac** [comment]
Thanks @lovell, I'll keep an eye on #2222.
