### ISSUE TITLE
svg to png missing one line of pixel at bottom

### ISSUE THREAD

**Issue by c19** [lovell/sharp#2242]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

What are the steps to reproduce?
// icon.svg
```
<svg version="1.1" xmlns="http://www.w3.org/2000/svg">
    <defs>
        <linearGradient id="green" x1="0%" y1="0%" x2="0%" y2="100%">
            <stop offset="0%" style="stop-color:rgba(112,168,0,.2)"/>
            <stop offset="80%" style="stop-color:rgba(240,185,11,.2)"/>
            <stop offset="100%" style="stop-color:rgba(255,255,255,.2)"/>
        </linearGradient>
    </defs>
    <defs>
        <linearGradient id="red" x1="0%" y1="0%" x2="0%" y2="100%">
            <stop offset="0%" style="stop-color:rgba(234,0,112,.2)"/>
            <stop offset="80%" style="stop-color:rgba(240,185,11,.2)"/>
            <stop offset="100%" style="stop-color:rgba(255,255,255,.2)"/>
        </linearGradient>
    </defs>
    <defs>
        <linearGradient id="linear" x1="0%" y1="0%" x2="0%" y2="100%">
            <stop offset="0%" style="stop-color:rgba(240,185,10,.65)"/>
            <stop offset="80%" style="stop-color:rgba(240,185,10,.05)"/>
            <stop offset="100%" style="stop-color:transparent"/>
        </linearGradient>
    </defs>
    <g transform="translate(0.5,0.5)">
        <path d="M0 12 L4 12 L9 10 L13 12 L17 4 L22 4 L26 12 L30 8 L35 26 L39 29 L43 26 L48 17 L52 18 L57 12 L61 13 L65 8 L70 8 L74 6 L78 8 L83 8 L87 6 L91 1 L96 4 L100 6" stroke="rgba(240, 185, 10, 1)" fill="none" stroke-width="1"/>
        <path d="M0 28 L0 12 L4 12 L9 10 L13 12 L17 4 L22 4 L26 12 L30 8 L35 26 L39 29 L43 26 L48 17 L52 18 L57 12 L61 13 L65 8 L70 8 L74 6 L78 8 L83 8 L87 6 L91 1 L96 4 L100 6 L100 28" fill="url(#linear)" stroke="none"/>
    </g>
</svg>
```

`node index.js`

[result](https://imgur.com/Rh908SS)

What is the expected behaviour?

[expected](https://imgur.com/lOspKLZ)

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

// index.js
```
const sharp = require("sharp");

const sharpObj = sharp("icon.svg")
sharpObj.png()
    .toFile("icon.png")
```

What is the output of running `npx envinfo --binaries --system`?
```
 System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 62.23 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.3.0 - ~/.nvm/versions/node/v14.3.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.3.0/bin/npm
```

**Comment by lovell** [comment]
Hi, this is the expected output, which is the same as calling `rsvg-convert` on the command line:

![](https://user-images.githubusercontent.com/210965/83795671-b5e24980-a697-11ea-85c2-381a792bf6fe.png)

The unnecessary `translate(0.5,0.5)` transformation is introducing the use of round to nearest.

Remove this and you'll get the output you are hoping for:

![](https://user-images.githubusercontent.com/210965/83796155-7831f080-a698-11ea-92fb-aa33e6f6f98e.png)

**Comment by c19** [comment]
removed translate(0.5,0.5)
removed.svg
```
<svg version="1.1" xmlns="http://www.w3.org/2000/svg">
    <defs>
        <linearGradient id="linear" x1="0%" y1="0%" x2="0%" y2="100%">
            <stop offset="0%" style="stop-color:rgba(240,185,10,.65)"/>
            <stop offset="80%" style="stop-color:rgba(240,185,10,.05)"/>
            <stop offset="100%" style="stop-color:transparent"/>
        </linearGradient>
    </defs>
    <g>
        <path d="M0 12 L4 12 L9 10 L13 12 L17 4 L22 4 L26 12 L30 8 L35 26 L39 29 L43 26 L48 17 L52 18 L57 12 L61 13 L65 8 L70 8 L74 6 L78 8 L83 8 L87 6 L91 1 L96 4 L100 6" stroke="rgba(240, 185, 10, 1)" fill="none" stroke-width="1"/>
        <path d="M0 28 L0 12 L4 12 L9 10 L13 12 L17 4 L22 4 L26 12 L30 8 L35 26 L39 29 L43 26 L48 17 L52 18 L57 12 L61 13 L65 8 L70 8 L74 6 L78 8 L83 8 L87 6 L91 1 L96 4 L100 6 L100 28" fill="url(#linear)" stroke="none"/>
    </g>
</svg>
```

index.js
```
const sharp = require("sharp");
const sharpObj = sharp("removed.svg")

sharpObj
    .resize(100, 40, {
        kernel: sharp.kernel.nearest,
        fit: sharp.fit.contain,
        position: sharp.position.top,
        background: { r: 255, g: 255, b: 255, alpha: 0 }
    })
    .png()
    .toFile("icon.png")
```

Left is expected. (generated with java lib). right is generated with above removed.svg and index.js.
<img width="1350" alt="compare" src="https://user-images.githubusercontent.com/2505428/83845044-b54ebf00-a73a-11ea-8697-e9e693511dbf.png">

the bottom line of pixel is missing.

**Comment by c19** [comment]
oh, it's not that it's missing a line of pixel, it's rounding all the sharp edges.

**Comment by lovell** [comment]
It's been a while since I've use Java for handling SVG; is this Batik? I guess there will be small differences in the way it renders/rasterises/rounds vs librsvg as used by sharp/libvips.

Are you able to provide the standalone Java you're using? Is any kind of bounding/view box being set in your Java code? I want to make sure we're comparing like with like.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
