### ISSUE TITLE
[Question] PDF to JPG: Get pages length before converting?

### ISSUE THREAD

**Issue by kobsTheReal** [lovell/sharp#2243]
Is there is a way to get the number of pages before a conversion to later convert a fraction (let's say 50% for instance) of something like a PDF?

**Comment by lovell** [comment]
Hi, did you see the `pages` and `pageHeight` properties returned by `metadata()`?

https://sharp.pixelplumbing.com/api-input#metadata

**Comment by kobsTheReal** [comment]
GREAT stuff! You rock @lovell !
