### ISSUE TITLE
Sharp convert to jp2 format (JPEG2000)

### ISSUE THREAD

**Issue by hegyre** [lovell/sharp#2245]
Hello,
I'm using latest versions of sharp and libvips

What are you trying to achieve?
I want to convert images like .png to .jp2
I've compiled and installed libvips globally, with imagemagick, itself compiled with jpeg2000 support.

Have you searched for similar questions?
Only found that one from 2018: https://github.com/lovell/sharp/issues/1489

Are you able to provide a minimal, standalone code sample that demonstrates this question?
If you could help me understand what should I update in the code to support something like:
```
sharp(input)
  .toFormat('jp2')
  .toBuffer();
```

Thanks in advance.

**Comment by lovell** [comment]
The work to expose magick-based output has started with PR #2012

**Comment by hegyre** [comment]
OK so it seems that one should adapt that PR #2012 to allow support for additional imagemagick formats (like .jp2)

Thanks for your answer @lovell ! much appreciated.

**Comment by LosTigeros** [comment]
So is this finally a thing? I would like to use either `.toFormat('jp2')` or `.toFormat('jxr')`.

**Comment by lovell** [comment]
In the same way that https://github.com/lovell/sharp/pull/2012 exposed a `.gif()` function for GIF output via *magick, this will need someone to do similar for `.jp2()`. Always happy to accept PRs, if you're able.

**Comment by inukshuk** [comment]
@lovell with 8.11 jp2 should be supported directly by libvips if compiled with libopenjpeg2, right? I suspect that this will make supporting the a dedicated `.jp2()` function more straightforward. I'd be happy to take a stab at this, if you would like to see this in included (I could also add openjpeg2 to sharp-libvips if you would like to include it by default).

**Comment by lovell** [comment]
@inukshuk Great, yes please, libvips 8.11.0 added `jp2ksave` (and `jp2kload`) so a PR to expose this API is welcome, although I'd prefer not to include openjpeg in the prebuilt binaries.

**Comment by hegyre** [comment]
Hello @lovell ,
Just curious about not including openjpeg in prebuild binaries.
Any specific reason ?
Thanks!

**Comment by lovell** [comment]
v0.29.1 is now available with support for JP2 when you compile sharp from source using a globally-installed libvips that has been compiled with support for OpenJPEG.

https://sharp.pixelplumbing.com/api-output#jp2
