### ISSUE TITLE
[Question] Extract pdf pages in multiple images

### ISSUE THREAD

**Issue by kobsTheReal** [lovell/sharp#2250]
Is it possible to convert a multi page PDF to multiple images without recalling sharp() with the appropriate options?
Like:
page 1 > 1.jpeg
page 2 > 2.jpeg 
etc..

Many thanks!

**Comment by lovell** [comment]
No. It's unlikely being able to do so would be more performant, plus would introduce complexity.

**Comment by kobsTheReal** [comment]
ok thanks for your reply.
