### ISSUE TITLE
Installation error: libx265.so.165, needed by /usr/local/lib/libheif.so, not found

### ISSUE THREAD

**Issue by jumpinvestor** [lovell/sharp#2253]
OS: Ubuntu 20.04 LTS

I've tried the recommendations before posting. Sharp says it installs fine, but installing libvips 8.9.2 (all methods listed in the repo) ends with these errors:

libx265.so.165, needed by /usr/local/lib/libheif.so, not found
libIlmImf-2_2.so.23, needed by /usr/local/lib/libMagickCore-7.Q16HDRI.so, not found

<img width="977" alt="Screen Shot 2020-06-10 at 5 46 51 PM" src="https://user-images.githubusercontent.com/14829156/84333101-99d12300-ab43-11ea-94c6-810470454e2d.png">

Then running Sharp shows this error:

<img width="779" alt="Screen Shot 2020-06-10 at 5 47 06 PM" src="https://user-images.githubusercontent.com/14829156/84333058-7908cd80-ab43-11ea-872e-f714147b6c22.png">

Reinstalling everything doesn't change it.

What am I missing or doing wrong?

**Comment by lovell** [comment]
It looks like you've got broken/missing installations of libx265, libheif and libmagickcore. They will all require reinstallation.

Given this problem doesn't appear to relate to sharp or libvips you might find a more general site such as StackOverflow useful.
