### ISSUE TITLE
[Question] What are the best settings for image optimize/minify?

### ISSUE THREAD

**Issue by approached** [lovell/sharp#2254]
hi @ all

What are you trying to achieve?
I'm tring to optimize images after upload. I found many options to this job with sharp. But does has anybody a basic settings for good result? 

Have you searched for similar questions?
Yes, i found just a good documantion: https://sharp.pixelplumbing.com/api-output#jpeg

Are you able to provide a minimal, standalone code sample that demonstrates this question?
No

Are you able to provide a sample image that helps explain the question?
No

**Comment by lovell** [comment]
The default settings generally provide a good filesize/quality balance for lossy formats. Note that many of the JPEG options require a globally-installed libvips compiled with support for mozjpeg. If you'd like further help, please provide a sample image and code to use as a worked example.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
