### ISSUE TITLE
LAMBDA PACKAGE SIZE

### ISSUE THREAD

**Issue by robbiecode** [lovell/sharp#2257]
Hi,

I've followed your setup for lambda aws and it appears that size of .zip is over 32Mb

We need simple resizing on the fly to serve images from S3.  

https://sharp.pixelplumbing.com/install#aws-lambda

https://www.npmjs.com/package/sharp
it states Unpacked Size 403 kB

How can we have light script to resize from s3 stored file/buffer to serve our API Gateway/CloudFront?

Should we remove parts of the npm?

**Comment by lovell** [comment]
Hi, did you see https://sharp.pixelplumbing.com/install#prebuilt-binaries ?

> A ~10MB tarball containing libvips and its most commonly used dependencies is downloaded via HTTPS and stored within `node_modules/sharp/vendor` during `npm install`.

Please ensure that whatever tool you're using to create zip files can correctly deal with symlinks.

Package sizes reported by the npmjs website don't include any dependencies.

On Linux, the latest sharp and its dependencies consume ~13MB when zip compressed:

```sh
$ npm i sharp

> sharp@0.25.4 install /tmp/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)

+ sharp@0.25.4
added 79 packages from 162 contributors and audited 79 packages in 3.942s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ du -sh node_modules/
38M	node_modules/

$ zip -ry test.zip node_modules/

$ ls -hs test.zip 
13M test.zip
```

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
