### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Auxolust** [lovell/sharp#226]
C:\dev\web\genericServer>npm install sharp
-
> sharp@0.10.0 install C:\dev\web\genericServer\node_modules\sharp
> node-gyp rebuild

C:\dev\web\genericServer\node_modules\sharp>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_
modules\node-gyp\bin\node-gyp.js" rebuild
child_process: customFds option is deprecated, use stdio instead.
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  common.cc
C:\Program Files\Microsoft Visual Studio 10.0\VC\include\xlocale(323): warning C4530: C++ exception handler used, but u
nwind semantics are not enabled. Specify /EHsc [C:\dev\web\genericServer\node_modules\sharp\build\sharp.vcxproj]
..\src\common.cc(3): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [C:\dev\web\
genericServer\node_modules\sharp\build\sharp.vcxproj]
  utilities.cc
..\src\utilities.cc(2): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [C:\dev\w
eb\genericServer\node_modules\sharp\build\sharp.vcxproj]
  metadata.cc
..\src\metadata.cc(2): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [C:\dev\we
b\genericServer\node_modules\sharp\build\sharp.vcxproj]
  resize.cc
..\src\resize.cc(6): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [C:\dev\web\
genericServer\node_modules\sharp\build\sharp.vcxproj]
  sharp.cc
..\src\sharp.cc(2): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [C:\dev\web\g
enericServer\node_modules\sharp\build\sharp.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
67:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuil
d"
gyp ERR! cwd C:\dev\web\genericServer\node_modules\sharp
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i
nstall" "sharp"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.10.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.10.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\web\genericServer\npm-debug.log

C:\dev\web\genericServer>

**Comment by lovell** [comment]
Hello, has [VIPS_HOME](https://github.com/lovell/sharp#windows) been set to the location of libvips on this machine?

**Comment by lovell** [comment]
@Auxolust Have you been able to make any progress with this?

**Comment by Auxolust** [comment]
Hi @lovell, sorry for the delay, VIPS_HOME has been set correctly, I haven't been able to progress any further with the installation despite numerous attempts

**Comment by lovell** [comment]
Thanks for the update. Does the `$(VIPS_HOME)\include\vips\vips.h` file exist? Are you able to share the `node_modules\sharp\build\sharp.vcxproj` file generated during installation?

**Comment by DaveRevay2** [comment]
I'm getting the same error following the install instructions. VIPS_HOME is set:

```
C:\Users\DavidRevay\Documents\Git\stemn\node_modules\sharp>if not defined npm_config_node_gyp (node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp
.js" rebuild )  else (rebuild)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  common.cc
  utilities.cc
  metadata.cc
  resize.cc
  sharp.cc
..\src\metadata.cc(2): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [C:\Users\DavidRevay\Documents\Git\stemn\node_modules\sharp\build\sharp.vcxproj]
..\src\utilities.cc(2): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [C:\Users\DavidRevay\Documents\Git\stemn\node_modules\sharp\build\sharp.vcxproj]
..\src\sharp.cc(2): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [C:\Users\DavidRevay\Documents\Git\stemn\node_modules\sharp\build\sharp.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\xlocale(336): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\src\common.cc) [C:\User
s\DavidRevay\Documents\Git\stemn\node_modules\sharp\build\sharp.vcxproj]
..\src\resize.cc(6): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [C:\Users\DavidRevay\Documents\Git\stemn\node_modules\sharp\build\sharp.vcxproj]
..\src\common.cc(4): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [C:\Users\DavidRevay\Documents\Git\stemn\node_modules\sharp\build\sharp.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\DavidRevay\Documents\Git\stemn\node_modules\sharp
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sharp"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.10.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.10.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

I would like to capture the `sharp.vcxproj` file but the entire `node_modules\sharp` directory is removed after a failed install.

**Comment by lovell** [comment]
It looks like @Auxolust is using Visual Studio 2010 ("10.0") and @DaveRevay2 is using VS 2012 ("11.0").

I've tested installation works with VS 2013 (on a laptop) and VS 2014 (via [Azure](https://github.com/lovell/sharp/blob/master/appveyor.yml#L1)).

My best guess is that the environment variable is not being made available to the `msbuild.exe` process.

Please can you try `npm install --arch=ia32 --msvs_version=2012` (or `npm install --arch=ia32 --msvs_version=2010`). Alternatively are either of you in a position to try  a more recent version of Visual Studio?

**Comment by lovell** [comment]
@Auxolust @DaveRevay2 have either of you been able to make any progress with either the suggested `npm` flags or a newer version of Visual Studio?

**Comment by DaveRevay2** [comment]
```
C:\Users\DavidRevay\Documents\Git\stemn>npm install sharp --arch=ia32 --msvs_version=2012
npm WARN package.json mandrill-api@1.0.45 No README data
npm WARN package.json slack-node@0.1.0 No repository field.

> sharp@0.10.1 install C:\Users\DavidRevay\Documents\Git\stemn\node_modules\sharp
> node-gyp rebuild


C:\Users\DavidRevay\Documents\Git\stemn\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\n
ode-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  common.cc
  utilities.cc
  metadata.cc
  resize.cc
  sharp.cc
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\xlocale(336): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\src
\common.cc) [C:\Users\DavidRevay\Documents\Git\stemn\node_modules\sharp\build\sharp.vcxproj]
..\src\utilities.cc(80): warning C4344: behavior change: use of explicit template arguments results in call to 'v8::Local<T> NanNew<v8::String,char*>(A0)' [C:\Users\DavidRevay\Doc
uments\Git\stemn\node_modules\sharp\build\sharp.vcxproj]
          with
          [
              T=v8::String,
              A0=char *
          ]
          but the regular function 'v8::Local<T> NanNew(const char *)' is a better match
          with
          [
              T=v8::String
          ]
          if you expect 'v8::Local<T> NanNew(const char *)' to be called then you need to make it an explicit specialization
          with
          [
              T=v8::String
          ]
..\src\utilities.cc(99): error C2059: syntax error : '{' [C:\Users\DavidRevay\Documents\Git\stemn\node_modules\sharp\build\sharp.vcxproj]
..\src\utilities.cc(99): error C2143: syntax error : missing ';' before '}' [C:\Users\DavidRevay\Documents\Git\stemn\node_modules\sharp\build\sharp.vcxproj]
c1xx : fatal error C1063: INTERNAL COMPILER ERROR [C:\Users\DavidRevay\Documents\Git\stemn\node_modules\sharp\build\sharp.vcxproj]

           Please choose the Technical Support command on the Visual C++

           Help menu, or open the Technical Support help file for more information

..\src\resize.cc(286): error C3861: 'round': identifier not found [C:\Users\DavidRevay\Documents\Git\stemn\node_modules\sharp\build\sharp.vcxproj]
..\src\resize.cc(289): error C3861: 'round': identifier not found [C:\Users\DavidRevay\Documents\Git\stemn\node_modules\sharp\build\sharp.vcxproj]
..\src\resize.cc(295): error C3861: 'round': identifier not found [C:\Users\DavidRevay\Documents\Git\stemn\node_modules\sharp\build\sharp.vcxproj]
..\src\resize.cc(298): error C3861: 'round': identifier not found [C:\Users\DavidRevay\Documents\Git\stemn\node_modules\sharp\build\sharp.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\DavidRevay\Documents\Git\stemn\node_modules\sharp
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sharp" "--arch=ia32" "--msvs_version=2012"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.10.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.10.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\DavidRevay\Documents\Git\stemn\npm-debug.log
```
Still getting an error unfortunately.

**Comment by lovell** [comment]
@DaveRevay2 Thank you for checking. This helps us make progress as `syntax error : missing ';' before '}'` and `'round': identifier not found` are different errors to those you saw previously. These are due to the compiler's inability to understand certain features of C++11.

I suspect a minimum version of Visual Studio 2013 ("12.0") is what's really required to get it to compile. If either of you are in a position to install or use it, that will help narrow this problem down further.

**Comment by Auxolust** [comment]
@lovell , haven't made any progress, decided to switch to an alternative as the work I'm doing is time sensitive

**Comment by lovell** [comment]
I'm pretty certain this problem relates to older versions of Visual Studio and have declared a minimum of MSVC 2013 in the [documented prerequisites](http://sharp.dimens.io/en/stable/install/#prerequisites).

Please feel free to re-open if the problem persists when using MSVC 2013 or later.

**Comment by JSchermers** [comment]
I'm working with vs2015 and have the same issue. Unfortunately i have can share the sharp.vcxproj

here the log

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  common.cc
  utilities.cc
  metadata.cc
  resize.cc
..\src\metadata.cc(2): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [C:\Users\
Joost\Documents\projects\ddc\ddc2015\node_modules\gulp-responsive\node_modules\sharp\build\sharp.vcxproj]
..\src\utilities.cc(2): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [C:\Users
\Joost\Documents\projects\ddc\ddc2015\node_modules\gulp-responsive\node_modules\sharp\build\sharp.vcxproj]
  sharp.cc
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(341): warning C4530: C++ exception handler used,
 but unwind semantics are not enabled. Specify /EHsc (compiling source file ..\src\common.cc) [C:\Users\Joost\Documents
\projects\ddc\ddc2015\node_modules\gulp-responsive\node_modules\sharp\build\sharp.vcxproj]
..\src\sharp.cc(2): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [C:\Users\Joo
st\Documents\projects\ddc\ddc2015\node_modules\gulp-responsive\node_modules\sharp\build\sharp.vcxproj]
..\src\resize.cc(6): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [C:\Users\Jo
ost\Documents\projects\ddc\ddc2015\node_modules\gulp-responsive\node_modules\sharp\build\sharp.vcxproj]
..\src\common.cc(4): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [C:\Users\Jo
ost\Documents\projects\ddc\ddc2015\node_modules\gulp-responsive\node_modules\sharp\build\sharp.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\buil
d.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "
rebuild"
gyp ERR! cwd C:\Users\Joost\Documents\projects\ddc\ddc2015\node_modules\gulp-responsive\node_modules\sharp
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-
cli.js" "install" "--save-dev" "gulp-responsive"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.10.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.10.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Joost\Documents\projects\ddc\ddc2015\npm-debug.log

**Comment by lovell** [comment]
Hallo @JSchermers, the `Cannot open include file: 'vips/vips.h'` message suggests one or more of the following might be the case:

* the [VIPS_HOME](http://sharp.dimens.io/en/stable/install/#windows) environment variable is not set
* the VIPS_HOME environment variable is unavailable at compile time, e.g. user/permissions
* the [$(VIPS_HOME)/include/vips/vips.h](https://github.com/lovell/sharp/blob/master/binding.gyp#L39) file doesn't exist

Are you able to check and confirm?

**Comment by JSchermers** [comment]
Hello @lovell 

the VIPS_HOME environment variable is not set --
i tried this in user and system variables

the $(VIPS_HOME)/include/vips/vips.h file doesn't exist 
it does exist

so it can only be permissions? But the user and system variables are set to the vips path. That must be ok doesn't it

**Comment by lovell** [comment]
@JSchermers Does this mean you've been able to make progress? If you've not already tried it, adding the `--arch=ia32` flag to `npm` should force it to 32-bit.

**Comment by JSchermers** [comment]
@lovell 

yes there's progress , tnx very much.

the --arch=ia32 might do something but i still get the fatal error windows64 bit is currently unsupported

**Comment by lovell** [comment]
@JSchermers The `Windows 64-bit is currently unsupported` error is generated by https://github.com/lovell/sharp/blob/master/src/common.cc#L14 when `_WIN64` is detected.

I guess you're using the x86 32-bit node.exe on a 64-bit Windows machine.

It might be that you'll need to use the `msvs_version` flag to help `node-gyp` realise it should only be using 32-bit. The full command would then be `npm install --arch=ia32 --msvs_version=2013`.

**Comment by JSchermers** [comment]
@lovell

Sorry for the delay in response. 
Your right about my setup! I have 64 bit with 32 bit node.

i used the command to set node gyp version and then ran npm install gulp-responsive. But the error is still here

--------------------------------------------------
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(341): warning C4530: C++ exception handler used,
 but unwind semantics are not enabled. Specify /EHsc (compiling source file ..\src\common.cc) [C:\[projectdir]\node_modules\gulp-responsive\node_modules\sharp\build\sharp.vcxproj]
..\src\common.cc(11): fatal error C1189: #error:  Windows 64-bit is currently unsupported - see https://github.com/love
ll/sharp#windows [[projectdir]\node_modules\gulp-responsive\node_modules\sharp\build\s
harp.vcxproj]
  sharp.cc
..\src\resize.cc(988): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data [C:\Use
rs\Joost\Documents\projects\ddc\ddc2015\node_modules\gulp-responsive\node_modules\sharp\build\sharp.vcxproj]
..\src\utilities.cc(27): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [C:\[projectdir]\node_modules\gulp-responsive\node_modules\sharp\build\sharp.vcxproj]
c:\[projectdir]\node_modules\gulp-responsive\node_modules\sharp\node_modules\nan\nan_new.
h(214): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data (compiling source file ..\s
rc\resize.cc) [[projectdir]\node_modules\gulp-responsive\node_modules\sharp\build\shar
p.vcxproj]
  ..\src\resize.cc(968): note: see reference to function template instantiation 'v8::Local<v8::String> NanNew<v8::Strin
  g,const _Elem*,unsigned __int64>(A0,A1)' being compiled
          with
          [
              _Elem=char,
              A0=const char *,
              A1=unsigned __int64
          ]

------------------------------

**Comment by lovell** [comment]
@JSchermers The presence of `_WIN64` at compile-time tells me something about your environment is still trying to build 64-bit code. Have you ever had a 64-bit node executable installed at any point?

I updated the Appveyor CI environment to use MSVC 2015 and it seems to be able to [compile without error](https://ci.appveyor.com/project/lovell/sharp/build/109). It uses [64-bit Windows](https://github.com/lovell/sharp/blob/msvc-2015/appveyor.yml#L4) with [32-bit node](https://github.com/lovell/sharp/blob/msvc-2015/appveyor.yml#L23) - you can see the full config here https://github.com/lovell/sharp/blob/msvc-2015/appveyor.yml

Perhaps there's something in there that may help you - otherwise you're probably beyond the limit of my Windows knowledge and therefore ability to help with what appears to be an environment-specific problem.
