### ISSUE TITLE
AWS SAM - Install with Docker command

### ISSUE THREAD

**Issue by nsbingham** [lovell/sharp#2261]
I'm using AWS SAM CLI to run a AWS Lambda function on Windows 10. From what I understand, the CLI spins up a Docker image that matches my Lamda function, which should be using the `nodejs12.x` runtime. When the function is packaged up, it should include whatever is in the `npm_modules` directory.

I'm a little unclear what I should expect when I run: 
```
docker run -v "%cd%":/var/task lambci/lambda:build-nodejs12.x npm install sharp
```
When I run this as an Administrator and replace `$PWD` with `%cd%`, it appears to grab `libvips-8.9.1-linux-x64.tar.gz` and install fine. When I invoke the function, which is running from the Docker container, I get the error below.

```
{"errorType":"Error","errorMessage":"'win32-x64' binaries cannot be used on the 'linux-x64' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'linux-x64' platform."}
```

I thought running the docker command above was installing binaries for Linux x64 and storing those in the `node_modules` directory. Is that correct?

**Comment by lovell** [comment]
Did you see https://sharp.pixelplumbing.com/install#aws-lambda ?

> 'win32-x64' binaries cannot be used on the 'linux-x64' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'linux-x64' platform.

Please note the removal of any binaries previously installed for use with Windows.

**Comment by nsbingham** [comment]
@lovell Thanks for the quick reply! I did see that. It looks like the debugging tool for AWS SAM in vscode was not running the code in a docker container as I had thought, so the error makes sense.

For anyone else who happens upon this issue, I am building the code in a container by running `sam build --use-container` and then running locally with `sam local invoke`. This approach works. The aws-toolkit-vscode project is working on allowing you to set `use-container` via a config file in future versions - https://github.com/aws/aws-toolkit-vscode/issues/1146.

**Comment by passledevelopers** [comment]
> @lovell Thanks for the quick reply! I did see that. It looks like the debugging tool for AWS SAM in vscode was not running the code in a docker container as I had thought, so the error makes sense.
> 
> For anyone else who happens upon this issue, I am building the code in a container by running `sam build --use-container` and then running locally with `sam local invoke`. This approach works. The aws-toolkit-vscode project is working on allowing you to set `use-container` via a config file in future versions - [aws/aws-toolkit-vscode#1146](https://github.com/aws/aws-toolkit-vscode/issues/1146).

Thanks for this @nsbingham - it really helped me out. They have now added the config options you mentioned as well, so you can add the following to your launch.json to run it from vscode and get it to build in the container

```
"sam": {
    "buildArguments": ["--use-container"]
}
```

More details of what can be configured for a debug session here: https://github.com/aws/aws-toolkit-vscode/blob/162857540c2b0df8b20c20b76a358021f986f2c3/designs/sam-debugging/local-sam-debugging.md
