### ISSUE TITLE
Black outlines in image are removed when using trim()

### ISSUE THREAD

**Issue by curiousdustin** [lovell/sharp#2265]
version: `sharp@0.25.4`

### What are the steps to reproduce?
Attempt to trim the attached example file.

```js
sharp(inputFilePath)
    .trim()
    .toFile(outputFilePath)
```
#### Input
![animal-0002](https://user-images.githubusercontent.com/1706540/85081482-5735c900-b189-11ea-8456-0ee54803201c.png)

#### Output
![animal-0002](https://user-images.githubusercontent.com/1706540/85081473-500ebb00-b189-11ea-83dd-9231e26afbea.png)

### What is the expected behaviour?
Black outlines would be preserved.

### What is the output of running `npx envinfo --binaries --system`?
```
  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 47.95 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.12.0 - ~/.nvm/versions/node/v13.12.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v13.12.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman```

**Comment by curiousdustin** [comment]
This seems related to https://github.com/lovell/sharp/issues/1246, https://github.com/lovell/sharp/issues/1797, and https://github.com/lovell/sharp/issues/1597, which are all closed but my issue persists.

**Comment by lovell** [comment]
The black outline in this image is part of the alpha channel - please see #2166 for a future possible enhancement to address this.

**Comment by curiousdustin** [comment]
Is there another manipulation I can do prior to trimming to work around this issue? To somehow move the outline out of the alpha channel?

**Comment by curiousdustin** [comment]
I have found that if I `flatten` and `removeAlpha` it trims as expected. Except of course then I have the background color from the flatten. 

I was then able to using the offsets mentioned in the docs, to crop (`extract`) the original image with alpha.

```
The info response Object will contain trimOffsetLeft and trimOffsetTop properties.
```

```js
const flattened = await sharp(inputFilePath)
    .flatten({ background: { r: 255, g: 0, b: 255 } })
    .removeAlpha()
    .toBuffer();

sharp(flattened)
  .trim()
  .toBuffer((err, data, info) => {
    const crop = {
      left: -info.trimOffsetLeft,
      top: -info.trimOffsetTop,
      width: info.width,
      height: info.height,
    };

    return sharp(inputFilePath)
      .extract(crop)
      .toFile(outputFilePath)
  });
```

_This is probably a sluggish work around, but it appears to work well enough for my use case._

**Comment by curiousdustin** [comment]
Closing in favor of https://github.com/lovell/sharp/issues/2166
