### ISSUE TITLE
Possible bug - Getting `no space left on device` while saving an image.

### ISSUE THREAD

**Issue by peshrawahmed** [lovell/sharp#2269]
**Background Story:**

~~We were using Node v8.15.x along with sharp v0.17.0. Upgraded our node version to 12.x.x and sharp to 0.25.4. This caused some breaking changes regarding to .OverlayWith() function. find out that .OverlayWith function is depricated. Replaced that function with composite()~~

**The node version does not have a relation with the error.**

**The Issue**
~~After upgrading to 0.25.4~~ the following error happens in nearly 2% of images. 
![Screen Shot 2020-06-24 at 16 24 28](https://user-images.githubusercontent.com/35446007/85564760-3234d080-b637-11ea-9756-a07875ea3e68.png)
Our disks has enough storages and inodes. setted `VIPS_DISC_THRESHOLD` to 2g as stated in @brandonaaron https://github.com/lovell/sharp/issues/1851#issuecomment-529865331
But the issue still persists. 

example code:
```
sharp(this.inputFile)
            .composite([{ input: this.names.origin }])
            .toFile(this.names.tmp.overlayed);
```

filesystem output:
![Screen Shot 2020-06-24 at 16 32 01](https://user-images.githubusercontent.com/35446007/85565992-4a591f80-b638-11ea-8d80-fe9b8a1aca3d.png)

`npx envinfo --binaries --system` output:
![Screen Shot 2020-06-24 at 16 17 22](https://user-images.githubusercontent.com/35446007/85563656-42987b80-b636-11ea-9f78-ffcf39be555c.png)

`npm ls sharp` output:
![Screen Shot 2020-06-24 at 16 18 53](https://user-images.githubusercontent.com/35446007/85563892-77a4ce00-b636-11ea-8249-ae97cbbac1f0.png)

**Comment by lovell** [comment]
Hi, it looks like you're using containers. Did you also upgrade anything else at the same time, perhaps the version of Docker or CentOS? Did these changes imply any different default permissions or limits?

Given that it works >98% of the time, please remove all other possible sources of upgrade-related error first.

**Comment by peshrawahmed** [comment]
Hi Lovell, No did not update anything except node version. Trying to test going back to v8 to see if the issue persists. I will share the result with you

**Comment by peshrawahmed** [comment]
@lovell went back to v8. the same issue persists with a different error message.
```
Error: vips__file_open_write: unable to open file "./public/ucdn/images/4rkamz2pyos0kbthp8f5-78iy4uo33to0kbthp8f6-list.jpg-unminified.jpg" for writing
unix error: No space left on device
```
I also did a fallback to old codes so the example is 

```
return sharp(this.inputFile)
            .overlayWith(this.names.origin)
            .toFile(this.names.tmp.overlayed);
```

Also the code works for >89%.

**Comment by peshrawahmed** [comment]
Checked Sentry events and found that this issues indeed happened before updating node versions. First event 10 June. Node version update 16 June. I am changing the title because it may be misleading.

**Comment by peshrawahmed** [comment]
We are using NFS server and storing the output image on the NFS server. Asked our server to unmount the nfs and save files to the same machine to figure out if the issue related is related to NFS
Sorry if writing too much comments causes inconvenience but trying to update the issue for resolving the problem. At least for the people who will experience this issue at the future.

**Comment by peshrawahmed** [comment]
Found the issue and it was not about sharp. This is a very extreme situation and will be very useful for other people. Our production server was growing and was nearly 1TB of images. 

The issue was a linux error `ext[3/4]_dx_add_entry: Directory index full!` Where the maximum limit of sub directory index have to be less than 32000. 

I am copying notes that I get from our server manager to help you. We are running servers on a virtual private cloud.
**Please do not use the following commands if you are not an expert or not sure if you are experiencing the same problem or not**
* Removed temp files that freed up high amount of space.
* We started up rescue boot 
* run command `fsck -vcfy /dev/<disk partition>`
* we want to state that running `tune2fs -O ^dir_index /dev/device` will cause performance issu
* run command `e2fsck -D /dev/device`

you can search google for `ext4_dx_add_entry` to get more information about the issue.

Thank you. I am closing the issue. Please open it if you have any questions
