### ISSUE TITLE
Install: No package 'vips' found

### ISSUE THREAD

**Issue by benzmuircroft** [lovell/sharp#227]
npm install sharp
    npm WARN package.json http-gzip@1.0.0 No repository field.
    npm WARN package.json message-sockets@0.2.16 No repository field.
    |
    > sharp@0.10.0 install /home/engine/node_modules/sharp
    > node-gyp rebuild
    
    Package vips was not found in the pkg-config search path.
    Perhaps you should add the directory containing `vips.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'vips' found
    gyp: Call to 'PKG_CONFIG_PATH=":$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --libs vips' returned exit status 1. while trying to load binding.gyp
    gyp ERR! configure error 
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
    gyp ERR! System Linux 2.6.32-042stab094.8
    gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/engine/node_modules/sharp
    gyp ERR! node -v v0.10.38
    gyp ERR! node-gyp -v v1.0.1
    gyp ERR! not ok  
    npm ERR! sharp@0.10.0 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the sharp@0.10.0 install script.
    npm ERR! This is most likely a problem with the sharp package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls sharp
    npm ERR! There is likely additional logging output above.
    npm ERR! System Linux 2.6.32-042stab094.8
    npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "sharp"
    npm ERR! cwd /home/engine/node_modules
    npm ERR! node -v v0.10.38
    npm ERR! npm -v 1.4.28
    npm ERR! code ELIFECYCLE
    npm ERR! not ok code 0

**Comment by benzmuircroft** [comment]
I did:

    curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | bash -

But now I get

    npm install sharp
    npm WARN package.json http-gzip@1.0.0 No repository field.
    npm WARN package.json message-sockets@0.2.16 No repository field.
    |
    > sharp@0.10.0 install /home/engine/node_modules/sharp
    > node-gyp rebuild
    make: Entering directory `/home/engine/node_modules/sharp/build'
      CXX(target) Release/obj.target/sharp/src/common.o
      CXX(target) Release/obj.target/sharp/src/utilities.o
    ../src/utilities.cc: In function ‘v8::Handle<v8::Value> format(const v8::Arguments&)’:
    ../src/utilities.cc:99: error: expected initializer before ‘:’ token
    ../src/utilities.cc:99: error: expected primary-expression before ‘)’ token
    ../src/utilities.cc:99: error: expected ‘;’ before ‘)’ token
    ../src/utilities.cc:103: error: ‘f’ was not declared in this scope
    make: *** [Release/obj.target/sharp/src/utilities.o] Error 1
    make: Leaving directory `/home/engine/node_modules/sharp/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
    gyp ERR! System Linux 2.6.32-042stab094.8
    gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/engine/node_modules/sharp
    gyp ERR! node -v v0.10.38
    gyp ERR! node-gyp -v v1.0.1
    gyp ERR! not ok 
    npm ERR! sharp@0.10.0 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the sharp@0.10.0 install script.
    npm ERR! This is most likely a problem with the sharp package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls sharp
    npm ERR! There is likely additional logging output above.
    npm ERR! System Linux 2.6.32-042stab094.8
    npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "sharp"
    npm ERR! cwd /home/engine/node_modules
    npm ERR! node -v v0.10.38
    npm ERR! npm -v 1.4.28
    npm ERR! code ELIFECYCLE
    npm ERR! not ok code 0

**Comment by lovell** [comment]
Hi Benz, a [C++11 compatible compiler](https://github.com/lovell/sharp#prerequisites) is required. Perhaps you're using Centos 6? If so, see https://github.com/lovell/sharp/issues/178#issuecomment-77536262

(The next version of this moduke will provide a more informative error - see commit 4f72dcb)

**Comment by benzmuircroft** [comment]
Thanks, after I followed your link to http://superuser.com/questions/381160/how-to-install-gcc-4-7-x-4-8-x-on-centos/542091#542091 and followed the instructions I was able to `npm install sharp` with no problem whatsoever!

**Comment by lovell** [comment]
Glad to hear you got it working.

**Comment by chamnap** [comment]
@lovell, I have the same problem on mac, El capitan. I have been searched for few hours, but still couldn't find any solutions.

> Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
gyp: Call to 'PKG_CONFIG_PATH="/usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.11:$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --libs vips' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/chamnapchhorn/.nvm/versions/node/v0.12.9/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1075:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "node" "/Users/chamnapchhorn/.nvm/versions/node/v0.12.9/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/chamnapchhorn/.nvm/versions/node/v0.12.9/lib/node_modules/image-resizer/node_modules/sharp
gyp ERR! node -v v0.12.9
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/chamnapchhorn/.nvm/versions/node/v0.12.9/bin/node" "/Users/chamnapchhorn/.nvm/versions/node/v0.12.9/bin/npm" "install" "-g" "image-resizer"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE

> npm ERR! sharp@0.11.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.11.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

> npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chamnapchhorn/npm-debug.log

**Comment by lovell** [comment]
@chamnap It looks like the libvips dependency has not been installed, or at least `pkg-config` doesn't know about it. http://sharp.dimens.io/en/stable/install/#mac-os

**Comment by chamnap** [comment]
@lovell, Thanks a lot for the link. It works great :).
