### ISSUE TITLE
how to process gif every page

### ISSUE THREAD

**Issue by banli17** [lovell/sharp#2272]
i have get gif's pages ，but i dont know how to get every page's data 。

for example i want  one of page to add watermark or text。

**Comment by lovell** [comment]
HI, did you see the `pages` property of the constructor in the documentation?

https://sharp.pixelplumbing.com/api-constructor

```js
sharp(input, { pages: -1 })...
```

**Comment by banli17** [comment]
@lovell   yes， i have see，but i don't know how to foreach it。

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/pull/2012 for animated (multi-page) GIF output, currently unsupported.
