### ISSUE TITLE
Is it possible to reverse composition to the original images ?

### ISSUE THREAD

**Issue by lastboy13** [lovell/sharp#2273]
**What are you trying to achieve?**
> I'm trying to use sharp composition feature to encode and decode PNG images
I need to reduce the images size on its way to the server.
The Idea is to take the original PNG images, encode it to WebP composition.
And then extract it to get the original images.

**Have you searched for similar questions?**
> I did a research in general for such implementation 

**Are you able to provide a minimal, standalone code sample that demonstrates this question?**
> NA

**Are you able to provide a sample image that helps explain the question?**

> NA

**Comment by lovell** [comment]
Hi, please can you provide some sample before and after images (and ideally the code to generate them) to help explain this question.

**Comment by lastboy13** [comment]
Hi,

You are right, I was not clear because in the back of my head I thought about encode \ decode and using composite it misleading.

My idea is to use stacked webp images to reduce network bandwidth.
I thought that maybe I can use your great project for this task. 

**Example:** 
Lets say I have two images and I use the composite like so: (The composition will save the images as separate layers with delta only)

client side encode the images
```
sharp('test1.webp')
  .composite([{ input: 'test2.webp', layer: true }])
  .toBuffer()
  .then(function(outputBuffer) { 
      // buffer containing the images as stuck
      // saving the image to disk out.image
 });
```

server side decode the images
```
sharp('out.image')
  .uncomposite([ layer: true }])
  .then(function(images) { 
      // images = [test1.webp, test2.webp]
 });
```

Thank you,
-Arik

**Comment by lovell** [comment]
The composite operation is non-reversible - it does not layer images but rather "flattens" images onto one another.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
