### ISSUE TITLE
Compress(or resize) the image up to 100Kb

### ISSUE THREAD

**Issue by AlexanderIgnacz** [lovell/sharp#2274]
I've searched all issues with this feature but I'm not able to find. I want to compress any images up to 100kb and I don't mind how its quality is bad or resolution is small. Investigating several hours at online, I found this library is the best one for NodeJS. Please give me any possible idea to achieve this feature.

**Comment by lovell** [comment]
> "I want to compress any images up to 100kb and I don't mind how its quality is bad or resolution is small"

Please can you provide (quite a bit) more information, including sample images and code, to help someone else understand what you're trying to achieve.

**Comment by AlexanderIgnacz** [comment]
When I upload images to my server, I want to make sure that all image sizes are less than 100KB with compressing. To achieve this, I guess I should make images smaller or down the quality of the images but I'm not sure how I can implement this via this Sharp library.

**Comment by polarathene** [comment]
How would you expect Sharp to do this for you? You want images to use exactly 100KB no more, no less? Any reason why? If you don't care about quality, being less shouldn't matter.

If your input image dimensions can vary and be very large, your first step would be to resize to a more acceptable width/height size. You've not indicated how these images are intended to be used, if they're for display usage, you should size appropriately for the dimensions they'll actually be rendered at.

After that, you could then check file size after resize, and if it's above 100KB, then you can lower the quality(eg 90, 80, 70) and repeat until the file size is at or below 100KB.

If you want to know how to use Sharp, [the documentation](https://sharp.pixelplumbing.com/) is very nice and provides many examples for the API. You'll need to figure out what width/height you will resize images down to if needed, and add your own logic for the quality passes(checking file size is done with [nodejs APIs or other package](https://stackoverflow.com/questions/42363140/how-to-find-the-size-of-the-file-in-node-js)).

**Comment by AlexanderIgnacz** [comment]
Thanks @polarathene I did exactly same what you said. I wanted my image to use less than 100KB(not exactly) :)
