### ISSUE TITLE
Enhancement: improve animated/multipage image resizing

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#2275]
Given Safari will soon be supporting WebP, I suspect a shift away from the use of animated GIF images towards the use of animated WebP images, which are significantly more efficient, is coming.

~~Operations like extract and rotate on individual pages/frames might be rather complex, but a possible new `resizePages` operation to resize all pages/frames in an image to a given width _or_ height (these would have to be mutually exclusive, plus an optional kernel), would be relatively straightforward.~~

Update: this has been implement via https://github.com/lovell/sharp/pull/2789, which sets page heights automatically using the existing resize API.

**Comment by OJezu** [comment]
Why not load all pages by default, though? Is BC the only concern? I guess it can break "convert first frame of gif/tiff to jpeg" scenario.

**Comment by tpetry** [comment]
Why not simply apply all operations on all frames? I would need compositing functionality for animated gifs. Duplicating every method to apply for all frames would be a rather complex task.
It would be easier applying all operations on all frames and the ability to extract single frames or sequences and construct new animated images based on frames/sequences. So compositing images on a subset on frames can be implemented based on these primitives.

**Comment by Dramex** [comment]
Any news on this?

**Comment by Alex--wu** [comment]
+1, waiting for the resizePages API

**Comment by wchaws** [comment]
Hi, @lovell 

How about expose `arrayjoin` API in sharp to support animated/multipage image resizing? I found a sample code at https://github.com/libvips/libvips/issues/1167#issuecomment-440598247. It's quite simple. The only missing API is `arrayjoin`. I found this API is already existing in sharp source code.

https://github.com/lovell/sharp/blob/1ff84b20b7d9b351786fb06899255cea59aa123c/src/libvips/cplusplus/vips-operators.cpp#L283

**PROPOSED API**

```ts
sharp.arrayjoin([img0, img1, img2, ...], {})
```

**Comment by lovell** [comment]
@wchaws Please see #1580

**Comment by lovell** [comment]
This oft requested feature is now available in v0.30.0 - enjoy!

Thanks again, as always, to @kleisauke for doing the work to implement it.
