### ISSUE TITLE
unable to write to target

### ISSUE THREAD

**Issue by seanffy** [lovell/sharp#2276]
When the image of SVG is HTTP or HTTPS and Base64, render error:
handler [Error: svgload: SVG rendering failed
vips2png: unable to write to target

<svg width="750" height="1280" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
   <circle cx="200" cy="150" r="40" stroke="black" stroke-width="2" fill="red" />
   <image xlink:href="https://www.baidu.com/img/flexible/logo/pc/result.png" x="0" y="0" width="600" height="700" />
</svg >

sharp(`routers/pb/circle.svg`)
      .png()

      .toFile(`routers/image/new-file${num}.png`)
      .then(async function (info, data) {
          console.log('info',info);
          resolve(response);
      })
      .catch(function (err) {
        console.log('handler', err);
      });

**Comment by lovell** [comment]
Please can you provide a sample image that fails in this manner.

**Comment by seanffy** [comment]
https://image-c-dev.weimobwmc.com/test/d1a41cb3cd5249b789ab8fdcdb3096f5.png

**Comment by lovell** [comment]
Please can you provide a sample **SVG input** image that fails in this manner.

**Comment by seanffy** [comment]
<svg width="750" height="1280" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
   <circle cx="200" cy="150" r="40" stroke="black" stroke-width="2" fill="red" />
   <image xlink:href="https://image-c-dev.weimobwmc.com/test/d1a41cb3cd5249b789ab8fdcdb3096f5.png" x="0" y="0" width="600" height="700" />
</svg >

**Comment by seanffy** [comment]
svg width="750" height="1280" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
   <circle cx="200" cy="150" r="40" stroke="black" stroke-width="2" fill="red" />
   <image xlink:href="https://image-c-dev.weimobwmc.com/test/d1a41cb3cd5249b789ab8fdcdb3096f5.png" x="0" y="0" width="600" height="700" />
/svg

**Comment by lovell** [comment]
Please see #1871

**Comment by seanffy** [comment]
Is it impossible to solve this problem？

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/1871#issuecomment-532399146

**Comment by seanffy** [comment]
I read it, but the answer is that it can't be solved，Can it run in node？

**Comment by lovell** [comment]
If you need an SVG rasteriser to access the network for child images then sharp/libvips/librsvg is probably the wrong solution to your problem.
