### ISSUE TITLE
处理IOS图片的Orientation / Processing the orientation of IOS pictures

### ISSUE THREAD

**Issue by wangguanl** [lovell/sharp#2277]
如何使用sharp的rotate方法进行旋转为正确的方向

**Comment by lovell** [comment]
> How to use sharp's rotate method to rotate to the correct direction

Are you able to provide a minimal, standalone code sample that demonstrates this question?
您是否能够提供一个最小的独立代码示例来说明此问题？

Are you able to provide a sample image that helps explain the question?
您是否可以提供示例图片来帮助解释该问题？
