### ISSUE TITLE
base64编码字符串不正确的时候，try/catch没有捕获到error

### ISSUE THREAD

**Issue by tangna** [lovell/sharp#2278]
客户端
let buff = fs.readFileSync(fileName)
let base64Str = buff.toString('base64')
base64Str = base64Str.substring(0, base64Str.length - 100) （base64Str.length > 100)

服务端
try {
  let buffer = Buffer.from(base64Str, 'base64')
  let img = sharp(buffer)
  await img.metadata()
  sharp(buffer).resize(width, height)
} catch (error) {
  
}

有输出
Uncaught Error: VipsJpeg: Premature end of JPEG file
VipsJpeg: out of order read at line 1008

但是我没有在catch里面捕获到error，请问下是什么原因？

**Comment by lovell** [comment]
Does the following change, to `await` a call to `toBuffer`, ensure the error is caught?
```diff
- sharp(buffer).resize(width, height)
+ await sharp(buffer).resize(width, height).toBuffer()
```
If not, please provide a complete, standalone code sample and image that allows someone else to reproduce this problem.

**Comment by tangna** [comment]
> Does the following change, to `await` a call to `toBuffer`, ensure the error is caught?
> 
> ```diff
> - sharp(buffer).resize(width, height)
> + await sharp(buffer).resize(width, height).toBuffer()
> ```
> 
> If not, please provide a complete, standalone code sample and image that allows someone else to reproduce this problem.

**Comment by tangna** [comment]
谢谢，这样是可以的。
之前，我是想用sharp(buffer).resize(width, height)返回stream，然后上传到Aliyun OSS，而不用转成buffer；
这样有办法吗？

**Comment by tangna** [comment]
谢谢，这样是可以的。
之前，我是想用sharp(buffer).resize(width, height)返回stream，然后上传到Aliyun OSS，而不用转成buffer；
这样有办法吗？

**Comment by lovell** [comment]
The use of Stream-based output means you can no longer "catch" errors, instead you'll need to listen for the error event.
```diff
- sharp(buffer).resize(width, height)
+ sharp(buffer).resize(width, height).on('error', err => { ... })
```

(This is a Node.js concept rather than being specific to sharp.)

**Comment by tangna** [comment]
明白了，谢谢
