### ISSUE TITLE
Can I directly process buffer data

### ISSUE THREAD

**Issue by Shanmax1996** [lovell/sharp#2282]
I get buffer data to my program from external and I want to process buffer data and send it as a buffer also.
So I don't want to convert buffer into an image.
How can I do this?

I try this way but it not work.

`const process = await sharp(incoming_buffer_data).grayscale();`

`fs.writeFileSync('test.jpg', process);`  // I am using this for testing. Allways I am getting worng image format as an error

**Comment by lovell** [comment]
Hi, did you see https://sharp.pixelplumbing.com/api-output#tobuffer ?

```diff
- const process = await sharp(incoming_buffer_data).grayscale();
+ const outputBuffer = await sharp(incoming_buffer_data).grayscale().toBuffer();
```
