### ISSUE TITLE
Need some help, tried everything. (not an issue, just looking for help)

### ISSUE THREAD

**Issue by Jettucis** [lovell/sharp#2285]
Hi!

Tried to search for the same issue, but kinda didn't find one, that is similiar to mine.
I wanted to resize low size images (ex. 15x20) to 32x32, but sometimes (depends on the image size) if the image width or height has odd number then the Image becomes all smudged.
![unknown](https://user-images.githubusercontent.com/45320856/86891166-10dbe600-c107-11ea-8b10-1fb48117654b.png)

I knew why the issue exists and tried to use .extend in place of .resize, so the picture remains in the center, but the edges are extended till 32x32.

 Code:
`const x = dimensions.width,
                  y = dimensions.height;
            var top = 32-(y/2),
                bottom = 32-(y/2),
                left = 32-(x/2),
                right = 32-(x/2);

            while(!imageDone){
            sharp(inputPath)
                .extend({
                    top: top,
                    bottom: bottom,
                    left: left,
                    right: right,
                    background: { r: 0, g: 0, b: 0, alpha: 0 }
                })
                .toFile(outputPath);
                imageDone = true;
            }`

After that I received an error "Expected integer or object for extend but received [object Object] of type object". Obviously I understand why is that, but how can I do my thing then :/
Can there be any way for me to resize or extend the images that doesn't affect either their quality or size (needs to be 32x32 for all images)?
Looking forward for any ideas, thanks :)

**Comment by lovell** [comment]
Did you see the `kernel` option? Use of `nearest` would be more appropriate for bitmap images.

https://sharp.pixelplumbing.com/api-resize

**Comment by Jettucis** [comment]
Yeah, I've tried `nearest` as well, but that's not what I really wanted as I need the image to be equal to the stock one :/.

Result:
![image](https://user-images.githubusercontent.com/45320856/86902995-661ff380-c117-11ea-9c56-ee6663c4a893.png)

**Comment by lovell** [comment]
@Jettucis Were you able to make any progress with this?

**Comment by Jettucis** [comment]
@lovell Well I understand why this issue exists, because sometimes the "image" is not pixel perfect and can't be centered exactly in the center and must be moved 1px to one of the sides. You can close this issue, it's not relevant anymore. Thanks for the help!

**Comment by themre** [comment]
Hi, I'm trying to use `extend` functionality and I've used basic example like `await sharp(path).resize(200).extend(20)` and I get error `Expected integer or object for extend but received [object Object] of type object`. Does anyone knows what could be the reason? sharp version is `0.27.1`. Thanks!
