### ISSUE TITLE
Electron: 'linux-armv7' binaries cannot be used on the 'linux-armv6' platform

### ISSUE THREAD

**Issue by SteffenLammers** [lovell/sharp#2287]
Hey Guys,

i try to use sharp within a electron application on my raspberry pi 4 with 4 GB. When i use 'require("sharp")' i get the following error:

> Uncaught Error: 'linux-armv7' binaries cannot be used on the 'linux-armv6' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'linux-armv6' platform.

I tried to build sharp from Source, but no success.

When i run 'npm install sharp' i get some errors:

> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
> gyp ERR! System Linux 4.19.118-v7l+
> gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/pi/neu/photo-booth/node_modules/epoll
> gyp ERR! node -v v12.18.2
> gyp ERR! node-gyp -v v5.1.0
> gyp ERR! not ok

but 'npm install -g node-gyp' finished succesfull

Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime?

> How can i Check this?

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

> Yes

If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

> Yes

What is the output of running `npx envinfo --binaries --system`?

>   System:
>     OS: Linux 4.19 Raspbian GNU/Linux 10 (buster) 10 (buster)
>     CPU: (4) arm ARMv7 Processor rev 3 (v7l)
>     Memory: 870.39 MB / 3.81 GB
>     Container: Yes
>     Shell: 5.0.3 - /bin/bash
>   Binaries:
>     Node: 12.18.2 - /usr/local/bin/node
>     npm: 6.14.5 - /usr/local/bin/npm

**Comment by lovell** [comment]
Hi, it looks like the version of Node.js being used at runtime is for ARM v6 but the version used at install time is for ARM v7.

Please can you provide the output of running the following commands:
```sh
whereis node
node -p "process.config.variables"
npm config list | grep -i arm
```

**Comment by SteffenLammers** [comment]
Thanks for the fast Answer.

whereis node

> node: /usr/sbin/node /usr/local/bin/node /usr/share/man/man8/node.8.gz

node -p "process.config.variables"
> {
>   arm_float_abi: 'hard',
>   arm_fpu: 'vfpv3',
>   arm_thumb: 0,
>   arm_version: '7',
>   asan: 0,
>   build_v8_with_gn: false,
>   coverage: false,
>   dcheck_always_on: 0,
>   debug_nghttp2: false,
>   debug_node: false,
>   enable_lto: false,
>   enable_pgo_generate: false,
>   enable_pgo_use: false,
>   force_dynamic_crt: 0,
>   gas_version: '2.28',
>   host_arch: 'ia32',
>   icu_data_in: '../../deps/icu-small/source/data/in/icudt67l.dat',
>   icu_default_data: '',
>   icu_endianness: 'l',
>   icu_gyp_path: 'tools/icu/icu-generic.gyp',
>   icu_locales: 'en,root',
>   icu_path: 'deps/icu-small',
>   icu_small: true,
>   icu_ver_major: '67',
>   is_debug: 0,
>   llvm_version: '0.0',
>   napi_build_version: '6',
>   node_byteorder: 'little',
>   node_debug_lib: false,
>   node_enable_d8: false,
>   node_install_npm: true,
>   node_module_version: 72,
>   node_no_browser_globals: false,
>   node_prefix: '/',
>   node_release_urlbase: 'https://nodejs.org/download/release/',
>   node_shared: false,
>   node_shared_brotli: false,
>   node_shared_cares: false,
>   node_shared_http_parser: false,
>   node_shared_libuv: false,
>   node_shared_nghttp2: false,
>   node_shared_openssl: false,
>   node_shared_zlib: false,
>   node_tag: '',
>   node_target_type: 'executable',
>   node_use_bundled_v8: true,
>   node_use_dtrace: false,
>   node_use_etw: false,
>   node_use_node_code_cache: false,
>   node_use_node_snapshot: false,
>   node_use_openssl: true,
>   node_use_v8_platform: true,
>   node_with_ltcg: false,
>   node_without_node_options: false,
>   openssl_fips: '',
>   openssl_is_fips: false,
>   shlib_suffix: 'so.72',
>   target_arch: 'arm',
>   v8_enable_gdbjit: 0,
>   v8_enable_i18n_support: 1,
>   v8_enable_inspector: 1,
>   v8_no_strict_aliasing: 1,
>   v8_optimized_debug: 1,
>   v8_promise_internal_field_count: 1,
>   v8_random_seed: 0,
>   v8_trace_maps: 0,
>   v8_use_siphash: 1,
>   v8_use_snapshot: 1,
>   want_separate_host_toolset: 1
> }

npm config list | grep -i arm

> user-agent = "npm/6.14.5 node/v12.18.2 linux arm"

**Comment by lovell** [comment]
Thanks, and the following commands:
```
/usr/sbin/node -p "process.config.variables.arm_version"
/usr/local/bin/node -p "process.config.variables.arm_version"
```

**Comment by SteffenLammers** [comment]
/usr/sbin/node -p "process.config.variables.arm_version"
> This command does nothing

/usr/local/bin/node -p "process.config.variables.arm_version"
> 7

**Comment by lovell** [comment]
Thanks, what's happening here is that `/usr/local/bin/node` is compiled for ARMv7 and is being used at `npm install` time but `/usr/sbin/node` is compiled for ARMv6 and is being used at run time.

You'll need to ensure `/usr/local/bin/node` is also used at run time.

**Comment by SteffenLammers** [comment]
I did not know how to `You'll need to ensure /usr/local/bin/node is also used at run time.` So i just deleted `/usr/sbin/node` and run npm install again, but nothing changed.

**Comment by diegodev3** [comment]
I I'm having the same problem. found any solution?

**Comment by lovell** [comment]
@SteffenLammers Deleting files from `/usr/sbin` is usually a bad idea. If there are two versions of `node` on this system, you'll need to run the one that you want using its full path e.g. `/usr/local/bin/node script.js` rather than relying on the OS to select one for you.

**Comment by lovell** [comment]
@diegodev3 If your problem is exactly the name, namely you are seeing the exact same `'linux-armv7' binaries cannot be used on the 'linux-armv6' platform` error, then please provide answers to all of the questions I asked. If not, please open a new issue.

**Comment by diegodev3** [comment]
pi@raspberrypi:~ $ whereis node
node: /usr/bin/node /usr/local/bin/node /usr/include/node /usr/share/man/man1/node.1.gz
pi@raspberrypi:~ $ node -p "process.config.variables"
{
  arm_float_abi: 'hard',
  arm_fpu: 'vfpv3',
  arm_thumb: 0,
  arm_version: '7',
  asan: 0,
  build_v8_with_gn: false,
  coverage: false,
  dcheck_always_on: 0,
  debug_nghttp2: false,
  debug_node: false,
  enable_lto: false,
  enable_pgo_generate: false,
  enable_pgo_use: false,
  force_dynamic_crt: 0,
  gas_version: '2.28',
  host_arch: 'ia32',
  icu_data_in: '../../deps/icu-small/source/data/in/icudt67l.dat',
  icu_default_data: '',
  icu_endianness: 'l',
  icu_gyp_path: 'tools/icu/icu-generic.gyp',
  icu_locales: 'en,root',
  icu_path: 'deps/icu-small',
  icu_small: true,
  icu_ver_major: '67',
  is_debug: 0,
  llvm_version: '0.0',
  napi_build_version: '6',
  node_byteorder: 'little',
  node_debug_lib: false,
  node_enable_d8: false,
  node_install_npm: true,
  node_module_version: 72,
  node_no_browser_globals: false,
  node_prefix: '/',
  node_release_urlbase: 'https://nodejs.org/download/release/',
  node_shared: false,
  node_shared_brotli: false,
  node_shared_cares: false,
  node_shared_http_parser: false,
  node_shared_libuv: false,
  node_shared_nghttp2: false,
  node_shared_openssl: false,
  node_shared_zlib: false,
  node_tag: '',
  node_target_type: 'executable',
  node_use_bundled_v8: true,
  node_use_dtrace: false,
  node_use_etw: false,
  node_use_node_code_cache: false,
  node_use_node_snapshot: false,
  node_use_openssl: true,
  node_use_v8_platform: true,
  node_with_ltcg: false,
  node_without_node_options: false,
  openssl_fips: '',
  openssl_is_fips: false,
  shlib_suffix: 'so.72',
  target_arch: 'arm',
  v8_enable_gdbjit: 0,
  v8_enable_i18n_support: 1,
  v8_enable_inspector: 1,
  v8_no_strict_aliasing: 1,
  v8_optimized_debug: 1,
  v8_promise_internal_field_count: 1,
  v8_random_seed: 0,
  v8_trace_maps: 0,
  v8_use_siphash: 1,
  v8_use_snapshot: 1,
  want_separate_host_toolset: 1
}
pi@raspberrypi:~ $ npm config list | grep -i arm
user-agent = "npm/6.14.5 node/v12.18.2 linux arm"
pi@raspberrypi:~ $ /usr/sbin/node -p "process.config.variables.arm_version"
bash: /usr/sbin/node: No such file or directory
pi@raspberrypi:~ $ /usr/local/bin/node -p "process.config.variables.arm_version"
7

**Comment by lovell** [comment]
@diegodev3 Thanks, it looks like there are two ARMv7 `node` executables so I'm unsure why you're seeing an error message that includes `linux-armv6`. To help you debug this, the logic to determine the platform version in use at runtime is https://github.com/lovell/sharp/blob/master/lib/platform.js#L16

**Comment by diegodev3** [comment]
values of the variables used in https://github.com/lovell/sharp/blob/master/lib/platform.js
process.env.npm_config_arch `undefined`
process.arch `"arm"`
process.env.npm_config_platform `undefined`
process.platform `"linux"`
process.env.npm_config_arm_version `undefined`
process.config.variables.arm_version `undefined`

**Comment by lovell** [comment]
I'm confused. You stated that the value of `process.config.variables.arm_version` was `7` for both versions of node on your machine, but now it has the value `undefined`.

Are you running your script via an explicit path e.g. `/usr/local/bin/node script.js` ?

**Comment by diegodev3** [comment]
I'm using electron on my project.
`electron --disable-gpu .`

I changed the value '6' to '7' at https://github.com/lovell/sharp/blob/master/lib/platform.js#L16 and it worked normally!

**Comment by lovell** [comment]
Aha, it looks like Electron doesn't set `arm_version`. Electron provides binaries for ARMv7 and not ARMv6, so perhaps we should look for [process.versions.electron](https://www.electronjs.org/docs/api/process#processversionselectron-readonly) and consider its presence the equivalent of `arm_version=7`. Happy to accept a PR for this if you're able.

**Comment by SteffenLammers** [comment]
Hey @lovell i tried to uninstall and install node again, but nothing happens. I will post the new Output of the command above. I still dont know how to ensure that the ARMv7 node version is also used at run time.

whereis node

> node: /usr/bin/node /usr/include/node /usr/share/man/man1/node.1.gz

node -p "process.config.variables"

> { arm_float_abi: 'hard',
>   arm_fpu: 'vfpv3',
>   arm_thumb: 0,
>   arm_version: '7',
>   asan: 0,
>   build_v8_with_gn: false,
>   coverage: false,
>   debug_nghttp2: false,
>   enable_lto: false,
>   enable_pgo_generate: false,
>   enable_pgo_use: false,
>   force_dynamic_crt: 0,
>   gas_version: '2.28',
>   host_arch: 'ia32',
>   icu_data_in: '../../deps/icu-small/source/data/in/icudt64l.dat',
>   icu_endianness: 'l',
>   icu_gyp_path: 'tools/icu/icu-generic.gyp',
>   icu_locales: 'en,root',
>   icu_path: 'deps/icu-small',
>   icu_small: true,
>   icu_ver_major: '64',
>   llvm_version: 0,
>   node_byteorder: 'little',
>   node_debug_lib: false,
>   node_enable_d8: false,
>   node_enable_v8_vtunejit: false,
>   node_install_npm: true,
>   node_module_version: 64,
>   node_no_browser_globals: false,
>   node_prefix: '/',
>   node_release_urlbase: 'https://nodejs.org/download/release/',
>   node_shared: false,
>   node_shared_cares: false,
>   node_shared_http_parser: false,
>   node_shared_libuv: false,
>   node_shared_nghttp2: false,
>   node_shared_openssl: false,
>   node_shared_zlib: false,
>   node_tag: '',
>   node_target_type: 'executable',
>   node_use_bundled_v8: true,
>   node_use_dtrace: false,
>   node_use_etw: false,
>   node_use_large_pages: false,
>   node_use_openssl: true,
>   node_use_pch: false,
>   node_use_perfctr: false,
>   node_use_v8_platform: true,
>   node_with_ltcg: false,
>   node_without_node_options: false,
>   openssl_fips: '',
>   openssl_no_asm: 0,
>   shlib_suffix: 'so.64',
>   target_arch: 'arm',
>   v8_enable_gdbjit: 0,
>   v8_enable_i18n_support: 1,
>   v8_enable_inspector: 1,
>   v8_no_strict_aliasing: 1,
>   v8_optimized_debug: 0,
>   v8_promise_internal_field_count: 1,
>   v8_random_seed: 0,
>   v8_trace_maps: 0,
>   v8_typed_array_max_size_in_heap: 0,
>   v8_use_snapshot: true,
>   want_separate_host_toolset: 1 }

npm config list | grep -i arm

> user-agent = "npm/6.14.4 node/v10.21.0 linux arm"

/usr/bin/node  -p "process.config.variables.arm_version"

> 7

/usr/include/node -p "process.config.variables.arm_version"

> bash: /usr/include/node: Ist ein Verzeichnis

I hope u can help me again.

**Comment by diegodev3** [comment]
> Aha, it looks like Electron doesn't set `arm_version`. Electron provides binaries for ARMv7 and not ARMv6, so perhaps we should look for [process.versions.electron](https://www.electronjs.org/docs/api/process#processversionselectron-readonly) and consider its presence the equivalent of `arm_version=7`. Happy to accept a PR for this if you're able.

Changes to ensure armv7 version if using electron in #2292

**Comment by lovell** [comment]
v0.26.0 now available, thanks for the PR.
