### ISSUE TITLE
Installation issue on CentOS 6.6

### ISSUE THREAD

**Issue by ThomasWeiss** [lovell/sharp#229]
Hi there,

I successfully used sharp previously on a CentOS 7, but I'm having issues installing the package on a CentOS 6.6.

- node v0.12.4
- node-gyp v1.0.3
- python v2.7.6
- libvips installed through the provided script

Error when `npm install sharp`:
```
  CXX(target) Release/obj.target/sharp/src/utilities.o
../src/utilities.cc: In function ‘void format(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/utilities.cc:99: error: expected initializer before ‘:’ token
../src/utilities.cc:99: error: expected primary-expression before ‘)’ token
../src/utilities.cc:99: error: expected ‘;’ before ‘)’ token
../src/utilities.cc:103: error: ‘f’ was not declared in this scope
```
Looks like a "basic" C++ syntax issue? Any help would be greatly appreciated here!
Thanks

**Comment by lovell** [comment]
Hi Thomas,

> "Looks like a "basic" C++ syntax issue?"

You are correct, the version of gcc provided in Centos 6 doesn't support C+11. You'll need at least version 4.6 - see https://github.com/lovell/sharp/issues/178#issuecomment-77536262 for a possible solution.

**Comment by ThomasWeiss** [comment]
Hi!

Yep that was it, thanks a bunch!
And kudos to the first-class support you provide to us sharp users :smiley: 

Cheers

**Comment by lovell** [comment]
No probs, glad to hear you got it working. The forthcoming v0.10.1 will generate a more relevant compile time error when used with an incompatible version of gcc - see https://github.com/lovell/sharp/commit/4f72dcbf54557a5e97f33cd43dcd574da5fb7627
