### ISSUE TITLE
how to anti-alising image

### ISSUE THREAD

**Issue by constantank** [lovell/sharp#2295]
What are you trying to achieve?
i want to anti-alising image
Have you searched for similar questions?
yes i did, but no success... i was told by this handsome man named lovell (^_^)that the resize kernel option is provided, but i try everyone of them still no success
 
Are you able to provide a minimal, standalone code sample that demonstrates this question?
const sharp = require('sharp')

sharp('./static/a01.png')
  .resize({
    kernel: sharp.kernel.cubic,
  })
.toFile('./static/aa.png')
Are you able to provide a sample image that helps explain the question?
![a01](https://user-images.githubusercontent.com/24249173/87501314-5b260f80-c691-11ea-8a8a-8e3b236514c7.png)
![aa](https://user-images.githubusercontent.com/24249173/87501347-6f6a0c80-c691-11ea-8e4e-33437050364c.png)

**Comment by lovell** [comment]
Hi, a kernel will only have an effect when the image dimensions are changing.

A simple, fast, mild blur might provide what you're looking for:

```js
await sharp('./static/a01.png')
  .blur()
  .toFile('./static/aa.png')
```
https://sharp.pixelplumbing.com/api-operation#blur

**Comment by constantank** [comment]
const sharp = require('sharp')

sharp('./static/an.png')
  .resize({
    width: 1200,
    height: 1200,
    kernel: sharp.kernel.mitchell
  })
.toFile('./static/aa.png')

changed dimensions but still have no  effect

this is origin image
![image](https://user-images.githubusercontent.com/24249173/87661378-1387ac80-c793-11ea-9db7-58d48731712f.png)

this is output image
![image](https://user-images.githubusercontent.com/24249173/87661426-269a7c80-c793-11ea-8728-5be897c26246.png)


if i use blur , it blurs the whole image, i just want to blur the edge of the cup . is that possible?

**Comment by lovell** [comment]
In this second example, the image dimensions are being increased, so the kernel has no effect.

https://sharp.pixelplumbing.com/api-resize#resize

> `options.kernel` `String` the kernel to use for image reduction. (optional, default 'lanczos3')

The jagged edges are an artefact of upsampling, for which libvips will use bicubic resampling.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
