### ISSUE TITLE
Resize animated WebP

### ISSUE THREAD

**Issue by pkantsedalov** [lovell/sharp#2296]
Hi everyone.
Thanks for the great library!

I have a question regarding the animated WebP.
I can't resize it using the lib.
I'm trying:

```js
sharp(file, { pages: -1 })
      .resize(width, height)
      .withMetadata()
      .toBuffer()
      .then(handleData);

```

but no success - I get only static webp file, the 1st frame is used I guess.

I can do that only via CLI executing `vipsthumbnail ./anim.webp[n=-1] -s 40x120 -o anim-tiny.webp`.

Is there any way to do this job using `sharp`, or it's not yet supported (according to the open status of #2012)?

**Platform**: MacOS Catalina
**vips**: `pkg-config --modversion vips-cpp` returns `8.9.2`
**"sharp": "^0.25.4",**:

**Comment by lovell** [comment]
This requires #2012, specifically the addition of https://github.com/lovell/sharp/pull/2012/files#diff-3bf53c990b6a8e14d500ad32b70b7d87R272

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
