### ISSUE TITLE
Pre-built libvips docker image

### ISSUE THREAD

**Issue by dane-stevens** [lovell/sharp#2298]
I have pre-built a libvips docker image for public use as a base image:

https://hub.docker.com/repository/docker/tueri/docker-sharp

`docker pull tueri/docker-sharp`

# libvips version 8.9.2

Build contains:
* glib2.0-dev
* libexpat1-dev
* libtiff5-dev
* libgsf-1-dev
* libexif-dev
* libgif-dev
* librsvg2-dev
* libpoppler-glib-dev
* libtiff-dev
* libpng-dev

Based on the docker file from https://github.com/dnlup/docker-sharp

**Comment by lovell** [comment]
Hi, thanks for this, was use of the "enhancement" tag/template intentional or was this more for informational purposes?

**Comment by dane-stevens** [comment]
Really more for informational purposes. Wasn't sure where to put it so others could find it easily.

**Comment by lovell** [comment]
Great, thanks for confirming, let's hope this helps someone searching the issues archive.
