### ISSUE TITLE
Resizing image with a transparent background generates a thin white line in the output

### ISSUE THREAD

**Issue by andreban** [lovell/sharp#2299]
I'm resizing images to generate versions in different sizes - some larger and others smaller than the original, but always the same aspect ratio.

This is the code I'm using to resize the image:
``` typescript
    await sharp(data)
        .resize(size)
        .png()
        .toFile(fileName);
```

When resizing a PNG with a transparent background, the output image gets a thin white line where the transition from the alpha channel happens.

This is the original image:
![icon-default-512x512](https://user-images.githubusercontent.com/1733592/87870563-25d73580-c9a1-11ea-814a-16454aca07ef.png)

And this an example output:
![splash](https://user-images.githubusercontent.com/1733592/87870581-4901e500-c9a1-11ea-9d9b-d01a6e07bfe2.png)

At first sight, they seem exactly the same but when rendering the example output on top of a background with the same colour, we get this:
<img width="538" alt="Screen Shot 2020-07-19 at 09 23 07" src="https://user-images.githubusercontent.com/1733592/87870594-80709180-c9a1-11ea-920c-80b7fa0bc2ab.png">

A zoomed-in version:
<img width="400" alt="Screen Shot 2020-07-19 at 09 19 33" src="https://user-images.githubusercontent.com/1733592/87870605-98481580-c9a1-11ea-9d9d-dd1a9d5e3018.png">

I was able to produce an image without the issue by using the `nearest` kernel:

```typescript
    await sharp(data)
        .resize(size, size, {kernel: 'nearest'})
        .png()
        .toFile(fileName);
```

But the quality of the output image is much worse, as expected.

Flattening the image also removes the thin white line:

```typescript
    await sharp(data)
        .resize(size)
        .flatten({background: '#3A81FE'})
        .png()
        .toFile(fileName);
```
But is also undesirable, as we don't know which colour the background will look like before hand. 

I also tried other approaches, like setting the background colour on resize, other resize kernels, flattening the image with a transparent alpha channel,  but without luck.

This also happens with other images. I was able to reproduce with an SVG image as input.

Overall, any other approaches I could try?

**Comment by lovell** [comment]
Hi, thanks for the report, I can reproduce this using sharp v0.25.4 / libvips v8.9.1 but luckily this appears to work with the forthcoming libvips 8.10.0 so I think it might have been due to https://github.com/libvips/libvips/pull/1592

You can test this locally by installing sharp from the `lovell/sharp#zoom` work-in-progress branch.

**Comment by lovell** [comment]
v0.26.0 now available.
