### ISSUE TITLE
Two pipelines

### ISSUE THREAD

**Issue by tybenz** [lovell/sharp#230]
I'd like to do the following:

```javascript
var transform = sharp();
transform.resize(width, height)
.min()
.metadata( function( err, metadata ) {
    // calculate top and left based off new height and width
    transform.extract( top, left, maxWidth, maxHeight );
});

fileStream.pipe( transform ).pipe( response );
```

Is this possible? The extract call inside the metadata callback never seems to fire. In fact, if I log the metadata width and height it comes back as the original width and height.

Is there an easy way to have two processing pipelines and still use streams? That is, resize first, then get metadata, and use calculated top/left to call extract, and pipe the result to the http response?

**Comment by tybenz** [comment]
Got this to work. Ended up doing this:

```javascript
var resize = sharp()
    .resize( maxWidth, maxHeight )
    .min();
 
var metadataStream = sharp().metadata( function( err, metadata ) {
    var width = metadata.width;
    var height = metadata.height;
 
    var imageX = width * x;
    var imageY = height * y;
    var viewportX = maxWidth * x;
    var viewportY = maxHeight * y;
 
    var left = Math.max( viewportX - imageX, imageX - viewportX );
    var top = Math.max( viewportY - imageY, imageY - viewportY );
 
    extractStream.pipe( sharp().extract( top, left, maxWidth, maxHeight ) ).pipe( res );
});
 
var extractStream = new stream.PassThrough();
 
var resizedFileStream = file.pipe( resize );
resizedFileStream.on( 'data', function( data ) {
    metadataStream.write( data );
    extractStream.write( data );
});
resizedFileStream.on( 'end', function( data ) {
    metadataStream.end( data );
    extractStream.end( data );
});
```

**Comment by tybenz** [comment]
@lovell Please let me know if I made this overly complicated ^

**Comment by lovell** [comment]
The following *untested* code should hopefully help with an alternative approach.

The output of the resize operation is piped into two streams, one of which waits for the other to resume it.

```javascript
var extractor = sharp().pause();

var calculator = sharp()
  .metadata( function( err, metadata ) {
    var width = metadata.width;
    var height = metadata.height;

    var imageX = width * x;
    var imageY = height * y;
    var viewportX = maxWidth * x;
    var viewportY = maxHeight * y;

    var left = Math.max( viewportX - imageX, imageX - viewportX );
    var top = Math.max( viewportY - imageY, imageY - viewportY );

    extractor.extract( top, left, maxWidth, maxHeight ).resume();
  });

var resizer = sharp()
  .resize( maxWidth, maxHeight )
  .min();

resizer.pipe(calculator);
resizer.pipe(extractor).pipe(res);
file.pipe(resizer);

**Comment by tybenz** [comment]
Tried this one out... Didn't quite work. Getting an error based on the fact that you can only pipe the output of the `resizer` stream once.

**Comment by lovell** [comment]
Node's [stream.pipe docs](https://nodejs.org/api/stream.html#stream_readable_pipe_destination_options) say:

> This method pulls all the data out of a readable stream, and writes it to the supplied destination, automatically managing the flow so that the destination is not overwhelmed by a fast readable stream.
> Multiple destinations can be piped to safely. 

 Was the error from Node's Stream class or sharp?

**Comment by tybenz** [comment]
Node's Stream. I reverted the changes. I'll have to try again later and paste the error.

**Comment by lovell** [comment]
@tybenz you may be interested in the forthcoming [clone](https://github.com/lovell/sharp/tree/knife#clone) method - see https://github.com/lovell/sharp/blob/knife/test/unit/clone.js for an example of one input to two output Streams.
