### ISSUE TITLE
Performance of trim operation

### ISSUE THREAD

**Issue by LJNeon** [lovell/sharp#2300]
1. Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

Both show 0.25.4

2. What are the steps to reproduce?

I'm trimming a 400 x 40 PNG (no compression) to 290 x 39. This takes an average time of 442ms to complete. Doing the same thing with a different image that trims to 37 x 31 takes an average time of 243ms to complete. This performance is horrid.

3. What is the expected behaviour?

I'm using `node-canvas` to render text as an image using a custom font. This takes an average of 2ms to complete. I refuse to believe that rendering a word with a custom font should be hundreds of times faster than trimming transparent pixels off of that image afterwards. I would expect sharp to take under a millisecond to do this.

3. Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
```js
image = await sharp(image).trim().toBuffer(); // image is a PNG buffer
```

4. Are you able to provide a sample image that helps explain the problem?

Here's an example of an image before being trimmed.
![example](https://user-images.githubusercontent.com/23249107/87904448-290b0980-ca13-11ea-9adc-c6ae1901ded9.png)

5. What is the output of running `npx envinfo --binaries --system`?

```
  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (2) x64 QEMU Virtual CPU version 2.5+
    Memory: 191.82 MB / 3.85 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
```

**Comment by lovell** [comment]
Using the latest sharp, the same version of Node.js, Ubuntu Linux, on a 4 year old laptop, your sample image and the following code:
```js
// 2300.js
sharp(fs.readFileSync("2300.png")).trim().toBuffer();
```
...I see:
```
$ time node 2300.js

real	0m0.102s
user	0m0.092s
sys	0m0.020s
```
A little over 100ms for the complete process startup time, shared library linking, running and shutdown.

Profiling with callgrind I see the hottest 5 five functions are:
```
$ valgrind --tool=callgrind node 2300.js

348,828,511  PROGRAM TOTALS

54,574,545  ???:longest_match
13,171,741  ???:vips_rank_generate [sharp/vendor/lib/libvips.so.42.12.1]
 8,169,971  ???:v8::internal::Scanner::Next() [.nvm/versions/node/v14.5.0/bin/node]
 6,983,129  ???:Builtins_LdaNamedPropertyHandler'2 [.nvm/versions/node/v14.5.0/bin/node]
 6,361,923  /build/glibc-5mDdLG/glibc-2.30/elf/dl-lookup.c:do_lookup_x [/usr/lib/x86_64-linux-gnu/ld-2.30.so]
```

The `longest_match` function is the PNG compressor, which is about 16ms. The `vips_rank_generate` function used heavily by the `trim()` operation to search for regions of background colour takes around 4ms. The next two are v8 code parsing and garbage collection, and the final `do_lookup_x` represents shared library overhead, about 2ms in total.

You can speed up the PNG compression at the cost of file size by reducing the `compressionLevel` from its default of 9.

https://sharp.pixelplumbing.com/api-output#png

For example using the following:
```js
sharp(fs.readFileSync("2300.png"))
  .trim()
  .png({ compressionLevel: 6 })
  .toBuffer();
```
...reduces the time spent in `longest_match` by ~15x:
```
301,712,192  PROGRAM TOTALS

13,171,741  ???:vips_rank_generate [sharp/vendor/lib/libvips.so.42.12.1]
...
 3,710,344  ???:longest_match [.nvm/versions/node/v14.5.0/bin/node]
```

Please see #1994 for a similar question.

**Comment by LJNeon** [comment]
Why doesn't sharp keep the existing compression input PNGs? This seems unintuitive.

**Comment by lovell** [comment]
It's not possible to know exactly what compression level was used for a given PNG as zlib DEFLATE streams contain only a 2-bit `FLEVEL` flag, which is not enough to encode the 10 possible values 0-9.

https://tools.ietf.org/html/rfc1950

```
      FLEVEL (Compression level)
         These flags are available for use by specific compression
         methods.  The "deflate" method (CM = 8) sets these flags as
         follows:

            0 - compressor used fastest algorithm
            1 - compressor used fast algorithm
            2 - compressor used default algorithm
            3 - compressor used maximum compression, slowest algorithm
```

The value of this flag is not exposed by either libpng or libspng, so libvips and therefore sharp have no way of knowing it.

I'm unaware of any existing tools that extract and use the original PNG compression level when re-encoding.

libvips prefers libspng over libpng, so in terms of next steps may I kindly suggest you take your turn to be a helpful citizen of the open source community and submit a PR to the https://libspng.org/ repo exposing this flag, then we can expose this in libvips and sharp. If you're lucky someone might even say thank you.

**Comment by LJNeon** [comment]
Are there any other ways I can improve performance? A 400x40 image shouldn't take 100ms to trim I would think, and yet it does even after setting compression to 0.

**Comment by lovell** [comment]
Please provide a standalone repo with all the code and image(s) to allow someone else to reproduce the specific scenario and therefore ensure we're all benchmarking and profiling exactly the same logic.

**Comment by lovell** [comment]
@LJNeon Were you able to make any progress with this? If not, are you able to help me help you by providing a standalone repo to allow someone else to reproduce and therefore benchmark the same, exact scenario.

**Comment by LJNeon** [comment]
I ended up writing pure JS image manipulation code, which resolved my performance issues by removing sharp from the picture entirely. I never ended up investing the time into looking into this because of that.

**Comment by LJNeon** [comment]
Although looking at it, all of the relevant code and images are already in the initial issue description.

**Comment by LJNeon** [comment]
Correction, the pure JS code was for a different performance issue I was having with sharp (compositing), in this case I was using `node-canvas` to generate the text image. I realized I could resize the canvas (effectively creating a new canvas entirely) before drawing text on it. This ended up having an average runtime of 2ms for both text rendering and trimming, which is incomparable to the ~450ms sharp took just to trim the same image.

**Comment by lovell** [comment]
Thanks for the update, I was never able to fully reproduce the original problem.

When testing with callgrind locally with the sample code and image provided so far in this issue I witnessed ~4ms for the trim operation (independent of any PNG de/compression roundtrip), hence the request for more information to ensure we're all testing the same thing.

The original report mentions QEMU, so perhaps this relates to CPU emulation e.g. intrinsics.

If there are other scenarios, please provide complete code, images, container definitions, QEMU startup scripts etc, ideally as a standalone repo, and I'd be happy to help.

**Comment by LJNeon** [comment]
The source code in question isn't OSS and it's tens of thousands of lines, so providing the complete code isn't realistic. This is on a low-end VPS and I have no clue what container is being used or even what QEMU is, so I presume both are on the VPS end. If it's some kind of CPU issue, then neither `node-canvas` nor pure JS equivalents appear to trigger it, only `sharp` does.

**Comment by lovell** [comment]
QEMU is a hardware-as-software emulation layer used by low-end VPS providers to hide/mask (and usually over-commit) the underlying CPU, and in my experience is often misconfigured. Have you been able reproduce this in an environment that doesn't use QEMU virtualisation?

**Comment by LJNeon** [comment]
I might have some time to compare performance of the same code on a personal computer this weekend.

**Comment by LJNeon** [comment]
I've run this on an old(over 15 years) desktop and my personal laptop (roughly 2-3 years old), both were able to run it at the kind of fast speeds I would expect. It does appear that the VPS is the only one struggling with sharp. I'm still curious as to why only sharp is affected, and both pure JS and node-canvas run at fast speeds on the VPS.

**Comment by lovell** [comment]
Thanks for the update.

My best guess would be a combination of an overloaded CPU with a lack of core pinning at the virtualisation layer and therefore constant L2 cache thrashing plus software-emulated CPU SIMD intrinsics that are slower than non-SIMD.

In summary: ditch your VPS provider.
