### ISSUE TITLE
47KB 600x600 png is resized to 512x512, but the result is 133KB big

### ISSUE THREAD

**Issue by tim-kos** [lovell/sharp#2302]
> Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

```
$ npm ls sharp
transloadit-api2@2.100.2 /srv/current/api2
└── sharp@0.25.4
```

```
$ npm view sharp dist-tags.latest
0.25.4
```

> What are the steps to reproduce?

Run this:

```
const sharp = require('sharp')
const fs = require('fs')

const inputPath = 'grad16rgba.png'
const outputPath = 'result.png'

const start = Date.now()
let sharpObj = sharp(inputPath, { density: 72 })
sharpObj = sharpObj.png()

sharpObj
  .toFile(outputPath)
  .then(() => {
    const end = Date.now()
    console.log((end - start) / 1000)

    fs.stat(outputPath, (err, stat) => {
      console.log(err, stat)
    })
  })
  .catch(err => {
    console.error(err)
  })
```

Use the input image, which is 47KB in size. Notice the output:

```
$ node sharp_problem.js
0.041
null Stats {
  dev: 47,
  mode: 33188,
  nlink: 1,
  uid: 900,
  gid: 900,
  rdev: 0,
  blksize: 1048576,
  ino: 1366357,
  size: 128111,
  blocks: 264,
  atimeMs: 1595271174000,
  mtimeMs: 1595271175000,
  ctimeMs: 1595271175000,
  birthtimeMs: 1595271175000,
  atime: 2020-07-20T18:52:54.000Z,
  mtime: 2020-07-20T18:52:55.000Z,
  ctime: 2020-07-20T18:52:55.000Z,
  birthtime: 2020-07-20T18:52:55.000Z
}
```

A 133KB file. I did not compile libpngquant, so I didn't try quality and other parameters. This shouldn't happen, even without libpngquant, right?

> What is the expected behaviour?

Resizing a 47KB 600x600 png to 512x512 should not triple its file size. I would have expected something around 40KB.

> Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

See above.

> Are you able to provide a sample image that helps explain the problem?

![grad16rgba](https://user-images.githubusercontent.com/15005/87975072-6206b500-cacb-11ea-8886-70fb3c84056a.png)

> What is the output of running `npx envinfo --binaries --system`?

```
$ npx envinfo --binaries --system
npx: installed 1 in 0.937s

  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 401.44 MB / 3.85 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.16.1 - ~/.nix-profile/bin/node
    Yarn: 1.22.0 - ~/.nix-profile/bin/yarn
    npm: 6.13.4 - ~/.nix-profile/bin/npm
```

**Comment by lovell** [comment]
Hi, did you see the `adaptiveFiltering` option?

https://sharp.pixelplumbing.com/api-output#png

**Comment by tim-kos** [comment]
That makes it much better, thank you!
