### ISSUE TITLE
Custom libvips with ImageMagick 7 throws Input file contains unsupported image format. But vipsthumbnail handles the same images perfectly.

### ISSUE THREAD

**Issue by haritonstefan** [lovell/sharp#2303]
I'm trying to build a libvips from source with poppler and image magick, as I need to create .png thumbnails for BMP, PDF, PSD file formats.
After building, `vipsthumbnail` correctly creates thumbnails for BMP, WEBP, PDF, PSD. But if being used through sharp, it only handles PDF and WEBP, and raises `Error: Input file contains unsupported image format` for BMP and PSD.
I made this [repo](https://github.com/haritonstefan/sharp-custom-vips) to reproduce the described behaviour.

1. Yes to both.
![image](https://user-images.githubusercontent.com/2504457/88021324-7abcac80-cb57-11ea-877c-9ef6c42bd02f.png)

2. I've made a repo reproducing the issue: [sharp-custom-vips](https://github.com/haritonstefan/sharp-custom-vips)

3. The expected behavior is to have the thumbnails generated

4. Provided the link in answer no. 2

5. Yes, samples are inclued in the repo

6. `npx envinfo --binaries --system`
```
npx: installed 1 in 0.897s

  System:
    OS: Linux 5.4 Alpine Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 367.82 MB / 15.34 GB
    Container: Yes
    Shell: 1.31.1 - /bin/ash
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
```

**Comment by lovell** [comment]
Support for libvips compiled against ImageMagick 7 was added recently via https://github.com/lovell/sharp/pull/2258 and will be in the next release.

**Comment by haritonstefan** [comment]
Thank you @lovell for your answer.

**Comment by lovell** [comment]
v0.26.0 now available.
