### ISSUE TITLE
Content-Type differs when running Docker container locally, or on Google Cloud

### ISSUE THREAD

**Issue by joergd** [lovell/sharp#2306]
I am not sure where the issue lies. I have built a Docker container with sharp and express resizing images for me. The container runs totally fine when I run it locally. However, when I push it to Google Cloud Run, the served images comes back mangled, as the response content-type is set by Google Frontend Server to "text/html" - as opposed to the "image/jpeg" content-type.

I don't know why there would be a difference between running the container locally, or on GCloud. Or where the issue might lie? In the express app below, I have two routes: /test, and /test2. **Both routes work fine locally**, but only /test2 sends an image on Gcloud, whereas /test sends back "text/html" ....

    const sharp = require("sharp");
    const express = require("express");
    const fs = require("fs");

    const app = express();

    app.get("/test", (req, res) => {
      const transform = sharp()
        .resize(200, 200, { fit: "inside" })
        .toFormat("jpeg");

      const readStream = fs.createReadStream("./src/image.jpg");

      return readStream.pipe(transform).pipe(res);
    });

    app.get("/test2", (req, res) => {
      const transform = sharp()
        .resize(200, 200, { fit: "inside" })
        .toFormat("jpeg");

      const readStream = fs.createReadStream("./src/image.jpg");

      return readStream.pipe(transform).pipe(res).set("Content-Type", "image/jpeg");
    });

    const port = process.env.PORT || 8080;
    app.listen(port);

Any ideas on where to look - as to why the behaviour is different when the containers are run in different environments?

https://image-processor-74rmztaj4a-uc.a.run.app/test
https://image-processor-74rmztaj4a-uc.a.run.app/test2

**Comment by lovell** [comment]
HTTP response headers are completely unrelated to sharp.

However, I would expect you'd want to add these, as you do correctly in the second route, so a better question to ask (elsewhere, perhaps StackOverflow) is why does the first route work.
