### ISSUE TITLE
Insert SVG text failing on Amazon linux with latest 0.25.4 version

### ISSUE THREAD

**Issue by vjaitly** [lovell/sharp#2307]
The latest version seems to be breaking on Amazon linux machines, when I do an image composite with SVG text.
Output of  console.log(sharp.versions)  with sharp v 0.25.4:
```{
  cairo: '1.16.0',
  exif: '0.6.21',
  expat: '2.2.9',
  ffi: '3.3',
  fontconfig: '2.13.92',
  freetype: '2.10.1',
  fribidi: '1.0.9',
  gdkpixbuf: '2.40.0',
  gettext: '0.20.1',
  gif: '5.1.4',
  glib: '2.64.0',
  gsf: '1.14.46',
  harfbuzz: '2.6.4',
  jpeg: '2.0.4',
  lcms: '2.9',
  orc: '0.4.31',
  pango: '1.44.7',
  pixman: '0.38.4',
  png: '1.6.37',
  svg: '2.48.0',
  tiff: '4.1.0',
  vips: '8.9.1',
  webp: '1.1.0',
  xml: '2.9.10',
  zlib: '1.2.11'
} 
```

My code 
```
let text=`<svg xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" xmlns="http://www.w3.org/2000/svg" height="50" width="100">
    <text x="10"  y="30" style="font-size:20px;fill:#999999">TEST</text>
</svg>`;
let addText = {
        input: Buffer.from(text),
        blend: 'over',
           top: 50,
           left:50}
sharp({
  create: {
    width: 300,
    height: 200,
    channels: 4,
    background: { r: 255, g: 255, b: 255 }
  }
})
.composite([addText])
.toFile('failing.png'); 
```
This is the output of the above with 0.25.4
<img width="315" alt="image" src="https://user-images.githubusercontent.com/5145383/88390539-1b200480-cdd6-11ea-9236-9a98abe78295.png">

and here the output of the same code with 0.23.4
<img width="315" alt="image" src="https://user-images.githubusercontent.com/5145383/88390414-e8760c00-cdd5-11ea-9b96-bb41705e016b.png">

**Comment by lovell** [comment]
Hi, did you see #1875 ?

**Comment by vjaitly** [comment]
Hi @lovell , Yes I went through the other threads. I felt this would be different, since the same code did work on the same environment with the v 0.23.4 . No fonts added locally in both the cases.
I am not trying to use any custom font either - the system available font would do.

**Comment by lovell** [comment]
Thanks, what happened when you set `FC_DEBUG`? https://github.com/lovell/sharp/issues/1565#issuecomment-460298005

**Comment by vjaitly** [comment]
I tried using the FC_DEBUG=1 value, but could not make out  what values should I be interested in the response
A snippet from the output is given below ( have removed some of the fields like charsets ). There are multiple such sections for match patterns .. 
Which values would be of interest here ?
```
Match Pattern has 24 elts (size 32)
	family: "Bitstream Vera Sans"(w) "DejaVu Sans"(w) "Verdana"(w) "Arial"(w) "Albany AMT"(w) "Luxi Sans"(w) "Nimbus Sans L"(w) "Helvetica"(w) "Lucida Sans Unicode"(w) "BPG Glaho International"(w) "Tahoma"(w) "Nachlieli"(w) "Lucida Sans Unicode"(w) "Yudit Unicode"(w) "Kerkis"(w) "ArmNet Helvetica"(w) "Artsounk"(w) "BPG UTF8 M"(w) "Waree"(w) "Loma"(w) "Garuda"(w) "Umpush"(w) "Saysettha Unicode"(w) "JG Lao Old Arial"(w) "GF Zemen Unicode"(w) "Pigiarniq"(w) "B Davat"(w) "B Compset"(w) "Kacst-Qr"(w) "Urdu Nastaliq Unicode"(w) "Raghindi"(w) "Mukti Narrow"(w) "malayalam"(w) "Sampige"(w) "padmaa"(w) "Hapax Berbère"(w) "MS Gothic"(w) "UmePlus P Gothic"(w) "SimSun"(w) "PMingLiu"(w) "WenQuanYi Zen Hei"(w) "WenQuanYi Bitmap Song"(w) "AR PL ShanHeiSun Uni"(w) "AR PL New Sung"(w) "MgOpen Modata"(w) "VL Gothic"(w) "IPAMonaGothic"(w) "IPAGothic"(w) "Sazanami Gothic"(w) "Kochi Gothic"(w) "AR PL KaitiM GB"(w) "AR PL KaitiM Big5"(w) "AR PL ShanHeiSun Uni"(w) "AR PL SungtiL GB"(w) "AR PL Mingti2L Big5"(w) "ＭＳ ゴシック"(w) "ZYSong18030"(w) "TSCu_Paranar"(w) "NanumGothic"(w) "UnDotum"(w) "Baekmuk Dotum"(w) "Baekmuk Gulim"(w) "KacstQura"(w) "Lohit Bengali"(w) "Lohit Gujarati"(w) "Lohit Hindi"(w) "Lohit Marathi"(w) "Lohit Maithili"(w) "Lohit Kashmiri"(w) "Lohit Konkani"(w) "Lohit Nepali"(w) "Lohit Sindhi"(w) "Lohit Punjabi"(w) "Lohit Tamil"(w) "Meera"(w) "Lohit Malayalam"(w) "Lohit Kannada"(w) "Lohit Telugu"(w) "Lohit Oriya"(w) "LKLUG"(w) "FreeSans"(w) "Arial Unicode MS"(w) "Arial Unicode"(w) "Code2000"(w) "Code2001"(w) "sans-serif"(s) "Roya"(w) "Koodak"(w) "Terafik"(w)
	familylang: "en"(s) "en-us"(w)
	stylelang: "en"(s) "en-us"(w)
	fullnamelang: "en"(s) "en-us"(w)
	slant: 0(i)(s)
	weight: 80(f)(s)
	width: 100(i)(s)
	size: 12(f)(s)
	pixelsize: 12(f)(s)
	hintstyle: 3(i)(s)
	hinting: True(s)
	verticallayout: False(s)
	autohint: False(s)
	globaladvance: True(s)
	dpi: 72(f)(s)
	lang: "c"(s) "en"(w)
	fontversion: 2147483647(i)(s)
	embeddedbitmap: True(s)
	decorative: False(s)
	namelang: "en"(s)
	prgname: "sharp"(s)
	symbol: False(s)
	variable: DontCare(s)
	pangoversion: 14407(i)(s)

Best score 0 0 0 0 0 0 0 1085 0 1 6 0 0 0 0 0 0 0 0 0 0 0 0 0 2.14748e+12
...
...
(w)
	lang: aa|ab|af|av|ay|ba|be|bg|bi|br|bs|bua|ca|ce|ch|chm|co|cs|cv|da|de|en|eo|es|et|eu|fi|fj|fo|fr|fur|fy|gd|gl|gv|ho|hr|hu|ia|id|ie|ik|io|is|it|kaa|ki|kk|kl|kum|kv|ky|la|lb|lez|lt|lv|mg|mh|mk|mo|mt|nb|nds|nl|nn|no|nr|nso|ny|oc|om|os|pl|pt|rm|ro|ru|sah|se|sel|sh|sk|sl|sma|smj|smn|so|sq|sr|ss|st|sv|sw|tg|tk|tl|tn|tr|ts|tt|tyv|uk|uz|vo|vot|wa|wen|wo|xh|yap|zu|an|crh|csb|fil|hsb|ht|jv|kj|ku-tr|kwm|lg|li|mn-mn|ms|na|ng|pap-an|pap-aw|rn|rw|sc|sg|sn|su|za(w)
	fontversion: 0(i)(w)
	fontformat: "Type 1"(w)
	decorative: False(w)
	postscriptname: "NimbusSanL-Regu"(w)
	color: False(w)
	symbol: False(w)
	variable: False(w)
```

**Comment by lovell** [comment]
Yes, there's a lot of noise, but somewhere in there will hopefully be useful information. Please can you try running both the working version and the non-working version with `FC_DEBUG=1` then use a tool such as `diff` to remove the common "noise" and help you find out where they differ.

**Comment by vjaitly** [comment]
Hi @lovell , The main difference  that stands out is this :
For 0.23.4 `pangoversion: 14204(i)(s)`
For 0.25.4 `	pangoversion: 14407(i)(s)`
```
Best score 0 0 0 0 0 0 0 1085 0 1 6 0 0 0 0 0 0 0 0Match Pattern has 24 elts (size 32)
```
For 0.25.4
```
Best score 0 0 0 0 0 0 0 1085 0 1 6 0 0 0 0 0 0 0 0 0 0 0 0 0 2.14748e+12
```
I also see additional Font declarations in the 0.25.4 version, but nothing specific that stands out

**Comment by lovell** [comment]
Were you able to make any progress with this? There's a new version v0.26.0 available that provides prebuild binaries with more up-to-date upstream dependencies.

**Comment by metaskills** [comment]
FWIW, I did both the directions described here (https://github.com/lovell/sharp/issues/1875#issuecomment-583446249) and updated to 0.26.0 and everything worked for me.

**Comment by vjaitly** [comment]
I tried with the new version 0.26.0. Now I do not get the binary output as in 0.25.x version, but the text is still not visible. 
It is just blank. (No text visible)

Will follow the steps in #1875 and try it again. In version 0.23.x I did not have to follow the steps for simpler fonts that are available at system level.

**Comment by vjaitly** [comment]
To complete the discussion here, 
I followed the steps as in #1875 and was able to see the output correctly. This also worked for 0.25.x build. Since this seems to be the preferred step for working on AWS linux , will close the issue.

Thanks @lovell for patiently replying to the queries even though it now seems to be a repeat.
