### ISSUE TITLE
Installing linux binaries for AWS Lambda doesn't work

### ISSUE THREAD

**Issue by ElqBell** [lovell/sharp#2309]
What is the output of running `npx envinfo --binaries --system`?

  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i3-4360 CPU @ 3.70GHz
    Memory: 11.37 GB / 15.91 GB
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD

'npm install sharp' works perfectly fine. The problem is with 'npm install --arch=x64 --platform=linux sharp'. I want to use sharp with AWS Lambda but when i try to install linux binaries i get this error:

info sharp Using cached C:\Users\dmd\AppData\Roaming\npm-cache\_libvips\libvips-8.9.1-linux-x64.tar.gz
ERR! sharp EPERM: operation not permitted, symlink 'libpng16\pngconf.h' -> 'C:\Users\dmd\Desktop\sharp2\node_modules\sharp\vendor\include\pngconf.h'

I tried 'npm cache clean --force' but nothing changed. I have no idea how to fix this, please help.

Do I need to use VM or another drive with linux x64 for the installation to be successful? I think the filesystem just refuses to let symlink to be created?

I tried the Docker approach but the Docker itself doesn't even launch because for some reason it can't enable hyper-v on my windows, even though it's not the Home version.... I think my CPU doesn't even support virtualization.

Would it be possible to not go through installing linux on another HDD and instead download the files manually somehow or maybe there is an upload of sharp for lambda somewhere? Spent the whole day just to get to this conclusion im going insane

**Comment by lovell** [comment]
Please see #1969 #1671

**Comment by ElqBell** [comment]
Ok so i managed to install docker but now the problem is that when i try to run
"docker run -v "$PWD":/var/task lambci/lambda:build-nodejs12.x npm install sharp"
in the terminal, i get 
"docker: invalid reference format."

Am i supposed to do some additional steps to install sharp with linux dependencies?
