### ISSUE TITLE
Package vips was not found in the pkg-config search path.

### ISSUE THREAD

**Issue by canebat** [lovell/sharp#231]
Can you tell me what I'm doing wrong?

`node --version`

`v0.10.25`

`sudo apt-get install build-essential pkg-config glib2.0-dev libxml2-dev`

`sudo apt-get install libvips`
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libvips37' instead of 'libvips'
Recommended packages:
  nip2
The following NEW packages will be installed:
  libvips37
0 upgraded, 1 newly installed, 0 to remove and 41 not upgraded.
```

`npm install sharp`

```
// ....

> node-gyp rebuild

Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
gyp: Call to 'PKG_CONFIG_PATH=":$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --libs vips' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/mt/nodejs/imgtest/sharp
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by lovell** [comment]
Hello, the `libvips-dev` package includes the `vips.pc` file required by `pkgconfig`.

The mention of `libvips37` suggests the use of Ubuntu 14.04, which provides v7.38.x via `apt`. The minimum libvips version [required](https://github.com/lovell/sharp#prerequisites) is v7.40.0 (`vips -v` will provide the installed version) so the `preinstall.sh` script may help.

**Comment by canebat** [comment]
For system maintenance, how should I remove the packages built from source when a newer version is out?

**Comment by lovell** [comment]
To remove libvips when previously compiled/installed from source, one possibility is to download the [latest tarball](http://www.vips.ecs.soton.ac.uk/supported/current/) and run `sudo make uninstall`.

On Ubuntu the optional [CheckInstall](https://help.ubuntu.com/community/CheckInstall) tool allows you to run `sudo checkinstall` instead of `sudo make install` in the first instance.

Adding a +1 towards https://bugs.launchpad.net/ubuntu/+source/vips/+bug/1377030 may help get v7.40.x backported to 14.04 too.

**Comment by canebat** [comment]
Does this mean I can't run `sudo checkinstall preinstall.sh`?

Instead, after installing dependencies, should I just do (bits copied from preinstall):

```
apt-get install -y automake build-essential gobject-introspection gtk-doc-tools libglib2.0-dev libjpeg-dev libpng12-dev libwebp-dev libtiff5-dev libexif-dev libgsf-1-dev liblcms2-dev libxml2-dev swig libmagickcore-dev curl

./configure --disable-debug --disable-docs --disable-static --disable-introspection --enable-cxx=yes --without-python --without-orc --without-fftw $1

make

sudo checkinstall 
```

**Comment by canebat** [comment]
Okay, I just installed using checkinstall, and `npm install sharp` has completed!

**Comment by lovell** [comment]
Great, glad to hear you got it working.

**Comment by canebat** [comment]
Haha, sorry. Well, I got it to install, but when trying to include it in my app:

   var sharp = require('sharp');

I get this error:

```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: libvips.so.42: cannot open shared object file: No such file or directory
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

But when I do 

    whereis libvips

It shows:

    libvips: /usr/local/lib/libvips.la /usr/local/lib/libvips.so

**Comment by lovell** [comment]
Did you run [ldconfig](https://github.com/lovell/sharp/blob/master/preinstall.sh#L34) (or `sudo ldconfig`)?

**Comment by canebat** [comment]
Oops, no I didn't! Thanks.
