### ISSUE TITLE
AVIF compression does not work

### ISSUE THREAD

**Issue by adityapatadia** [lovell/sharp#2310]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
- YES

What are the steps to reproduce?

https://sharp.pixelplumbing.com/api-output#heif
When providing `compression` as `av1`, Sharp throws error: `heifsave: Unsupported compression`

I have compiled libvips with `libheif-dev` and `libaom-dev` packages.

What is the expected behaviour?
- AVIF output image should be produced.

What is the output of running `npx envinfo --binaries --system`?
```
  System:
    OS: Linux 4.14 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
    Memory: 2.39 GB / 7.45 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
```

**Comment by lovell** [comment]
Please can you try with libvips v8.10.0-rc1 and likewise ensure you're using up-to-date versions of all the dependencies involved here.

**Comment by adityapatadia** [comment]
I have tried to compile with latest version of libheif and libaom. I am still on libvips-8.9.2. The error disappeared but now I get this black image as output.
[sea.avif.zip](https://github.com/lovell/sharp/files/4994280/sea.avif.zip)

**Comment by lovell** [comment]
Please can you confirm that the `heif-convert` command line tool provided by the latest libheif (when compiled with support for the latest aom) works as expected for the same input/output. If it is working, please can you provide the input image and sample code you are using.

**Comment by adityapatadia** [comment]
I have tried converting this image with following command
https://demo.gumlet.io/sea.jpeg

`heif-enc sea.jpeg -A -o sea.avif`

It gives above given black image.

**Comment by adityapatadia** [comment]
I have opened issue there: https://github.com/strukturag/libheif/issues/264

**Comment by adityapatadia** [comment]
There is some issue in heif or libaom which causes this image shown as black in Chrome 85 Beta. Fixes will be found soon: https://github.com/strukturag/libheif/issues/264
