### ISSUE TITLE
'linuxmusl-x64' binaries cannot be used on the 'linux-x64' platform.

### ISSUE THREAD

**Issue by seraphzxz** [lovell/sharp#2312]
I'm getting an error:
'linuxmusl-x64' binaries cannot be used on the 'linux-x64' platform.
the container linux kernal is 3.10.0 x86_64.

**Comment by lovell** [comment]
If you're using a glibc-based Linux at runtime, you'll need to ensure a glibc-based Linux is used at `npm install` time (it looks like you're installing on a musl-based Linux such as Alpine).

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/install#common-problems

> The architecture and platform of Node.js used for npm install must be the same as the architecture and platform of Node.js used at runtime.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by PaulMest** [comment]
If it's helpful to anybody in the future, this is what our `Dockerfile` looked like before and after to get `sharp` to work on Node 14 Alpine.

### Before (Sharp didn't work)
```
FROM osgeo/gdal:alpine-normal-3.1.3

WORKDIR /usr/local/src/server

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
ARG PORT=80
ENV PORT=${PORT}
EXPOSE ${PORT}

# nodejs-current means nodejs Current, currently at 14.x
RUN apk add --no-cache --update nodejs-current ghostscript graphicsmagick

COPY ./dist/test ./test
COPY ./dist/src ./src

COPY ./dist/scripts ./scripts

CMD ["node", "src/main"]

```


### After (Sharp works)

```
FROM node:14-alpine as deps

WORKDIR /deps

COPY ./dist/src/yarn.lock .
COPY ./dist/src/package.json .
RUN yarn install --production

FROM osgeo/gdal:alpine-normal-3.1.3

WORKDIR /app

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
ARG PORT=80
ENV PORT=${PORT}
EXPOSE ${PORT}

# nodejs-current means nodejs Current, currently at 14.x
RUN apk add --no-cache --update nodejs-current ghostscript graphicsmagick

COPY ./dist/src .
COPY --from=deps /deps/node_modules ./node_modules

CMD ["node", "main"]
```

**Comment by Plamen5kov** [comment]
problem is if you do an npm install when your node is v16 for example and then you start up your docker with an image from alpine v14 the docs clearly state that it's going to fail. 
If you want to get it to work. 
run npm install when your local node used to run npm install is the same version as the docker specified container. This was my problem 

`nvm use v14.x`
`rm -rf node_modules`
`npm install`
`docker-compose up` << with alpine-v14
