### ISSUE TITLE
When outputting pictures, automatically use the extension of the original picture file.

### ISSUE THREAD

**Issue by wenlittleoil** [lovell/sharp#2314]
`
  sharp('src.jpg').rotate(180).toFile('dest');
`
I think keeping the original extension of the `src.jpg`  is a common scenario, for example, it should output `dest.jpg`. Maybe it should provide this optional usage.
Without this feature, I handle it myself like that:
`
const path = require('path');    
const src = 'src.jpg';    
const srcExt = path.extname(src);    
sharp(src).rotate(180).toFile('dest' + srcExt);
`

**Comment by lovell** [comment]
Thanks for the suggestion. Given the ease with which someone can manage filenames themselves, I do not see value in adding this feature to sharp itself.
