### ISSUE TITLE
[Error: Input file contains unsupported image format]. Tried various jpg, jpeg and png files

### ISSUE THREAD

**Issue by ibrag474** [lovell/sharp#2315]
`const sharp = require('sharp')`

    sharp('./utils/fileUpload/test.jpg')
        .rotate()
        .resize(320, 240)
        .toFile('./utils/fileUpload/output.jpg')
        .then(info => { console.log(info) })
        .catch(err => { console.log(err)}
I am using example from https://sharp.pixelplumbing.com/ to test, but I keep getting error. I tried several different images.
Also, I tried to use node fs readFile with `utf8` and `base64` encodings with no luck, error changes to`[Error: Input buffer contains unsupported image format]` with `utf8` and remains the same with `base64`.

Using Node v12.

**Comment by lovell** [comment]
What is the complete output of running `npm install --verbose sharp`?

**Comment by ibrag474** [comment]
npm install --verbose sharp
npm info it worked if it ends with ok
npm verb cli [ '/home/ibragim/.nvm/versions/node/v10.16.0/bin/node',
npm verb cli   '/home/ibragim/.nvm/versions/node/v10.16.0/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sharp' ]
npm info using npm@6.9.0
npm info using node@v10.16.0
npm verb npm-session c2ef18472d8e542c
npm http fetch GET 304 https://registry.npmjs.org/sharp 333ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/sharp/-/sharp-0.25.4.tgz 14ms (from cache)
npm timing stage:loadCurrentTree Completed in 1013ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 4ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 305ms
npm http fetch GET 304 https://registry.npmjs.org/color 80ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/prebuild-install 215ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar 215ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-addon-api 220ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-get 220ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/semver 222ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-string 93ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-convert 95ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-name 70ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-swizzle 73ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-arrayish 63ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/noop-logger 62ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/github-from-package 63ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/napi-build-utils 63ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/expand-template 64ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-abi 65ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/which-pm-runs 113ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-fs 844ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 53ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-concat 863ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mimic-response 65ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-stream 45ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mkdirp-classic 46ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bl 70ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/readable-stream 71ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/inherits 40ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/chownr 78ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mkdirp 80ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minizlib 81ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-minipass 82ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/yallist 81ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minipass 83ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 2889ms
npm timing stage:loadIdealTree Completed in 3303ms
npm timing stage:generateActionsToTake Completed in 30ms
npm verb correctMkdir /home/ibragim/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/ibragim/.npm/_locks/staging-5fbcd5dd503ae70f.lock for /home/ibragim/mclub/node_modules/.staging
npm timing action:extract Completed in 21ms
npm info lifecycle sharp@0.25.4~preuninstall: sharp@0.25.4
npm info lifecycle sharp@0.25.4~uninstall: sharp@0.25.4
npm verb unbuild rmStuff sharp@0.25.4 from /home/ibragim/mclub/node_modules
npm info lifecycle sharp@0.25.4~postuninstall: sharp@0.25.4
npm timing action:unbuild Completed in 2ms
npm timing action:remove Completed in 18ms
npm timing action:finalize Completed in 3ms
npm timing action:refresh-package-json Completed in 8ms
npm info lifecycle sharp@0.25.4~preinstall: sharp@0.25.4
npm timing action:preinstall Completed in 1ms
npm info linkStuff sharp@0.25.4
npm timing action:build Completed in 1ms
npm info lifecycle sharp@0.25.4~install: sharp@0.25.4

> sharp@0.25.4 install /home/ibragim/mclub/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)

info sharp Detected globally-installed libvips v8.9.2
info sharp Building from source via node-gyp
gyp info it worked if it ends with ok
gyp verb cli [ '/home/ibragim/.nvm/versions/node/v10.16.0/bin/node',
gyp verb cli   '/home/ibragim/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.16.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.17
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.16.0
gyp verb command install [ '10.16.0' ]
gyp verb install input version string "10.16.0"
gyp verb install installing version: 10.16.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.16.0
gyp verb build dir attempting to create "build" dir: /home/ibragim/mclub/node_modules/sharp/build
gyp verb build dir "build" dir needed to be created? /home/ibragim/mclub/node_modules/sharp/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/ibragim/mclub/node_modules/sharp/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/ibragim/mclub/node_modules/sharp/config.gypi
gyp verb common.gypi checking for gypi file: /home/ibragim/mclub/node_modules/sharp/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/ibragim/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ibragim/mclub/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ibragim/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ibragim/.node-gyp/10.16.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ibragim/.node-gyp/10.16.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/ibragim/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/ibragim/.node-gyp/10.16.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ibragim/mclub/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/ibragim/.node-gyp/10.16.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/ibragim/mclub/node_modules/sharp/build'
  touch Release/obj.target/libvips-cpp.stamp
  cc '-DNODE_GYP_MODULE_NAME=nothing' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' -I/home/ibragim/.node-gyp/10.16.0/include/node -I/home/ibragim/.node-gyp/10.16.0/src -I/home/ibragim/.node-gyp/10.16.0/deps/openssl/config -I/home/ibragim/.node-gyp/10.16.0/deps/openssl/openssl/include -I/home/ibragim/.node-gyp/10.16.0/deps/uv/include -I/home/ibragim/.node-gyp/10.16.0/deps/zlib -I/home/ibragim/.node-gyp/10.16.0/deps/v8/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer  -MMD -MF ./Release/.deps/Release/obj.target/nothing/node_modules/node-addon-api/nothing.o.d.raw   -c -o Release/obj.target/nothing/node_modules/node-addon-api/nothing.o ../node_modules/node-addon-api/nothing.c
  rm -f Release/obj.target/node_modules/node-addon-api/nothing.a && ar crs Release/obj.target/node_modules/node-addon-api/nothing.a Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
  rm -rf "Release/nothing.a" && cp -af "Release/obj.target/node_modules/node-addon-api/nothing.a" "Release/nothing.a"
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DNAPI_VERSION=3' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DBUILDING_NODE_EXTENSION' -I/home/ibragim/.node-gyp/10.16.0/include/node -I/home/ibragim/.node-gyp/10.16.0/src -I/home/ibragim/.node-gyp/10.16.0/deps/openssl/config -I/home/ibragim/.node-gyp/10.16.0/deps/openssl/openssl/include -I/home/ibragim/.node-gyp/10.16.0/deps/uv/include -I/home/ibragim/.node-gyp/10.16.0/deps/zlib -I/home/ibragim/.node-gyp/10.16.0/deps/v8/include -I/home/ibragim/mclub/node_modules/sharp/node_modules/node-addon-api -I/usr/local/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/common.o.d.raw   -c -o Release/obj.target/sharp/src/common.o ../src/common.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DNAPI_VERSION=3' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DBUILDING_NODE_EXTENSION' -I/home/ibragim/.node-gyp/10.16.0/include/node -I/home/ibragim/.node-gyp/10.16.0/src -I/home/ibragim/.node-gyp/10.16.0/deps/openssl/config -I/home/ibragim/.node-gyp/10.16.0/deps/openssl/openssl/include -I/home/ibragim/.node-gyp/10.16.0/deps/uv/include -I/home/ibragim/.node-gyp/10.16.0/deps/zlib -I/home/ibragim/.node-gyp/10.16.0/deps/v8/include -I/home/ibragim/mclub/node_modules/sharp/node_modules/node-addon-api -I/usr/local/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/metadata.o.d.raw   -c -o Release/obj.target/sharp/src/metadata.o ../src/metadata.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DNAPI_VERSION=3' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DBUILDING_NODE_EXTENSION' -I/home/ibragim/.node-gyp/10.16.0/include/node -I/home/ibragim/.node-gyp/10.16.0/src -I/home/ibragim/.node-gyp/10.16.0/deps/openssl/config -I/home/ibragim/.node-gyp/10.16.0/deps/openssl/openssl/include -I/home/ibragim/.node-gyp/10.16.0/deps/uv/include -I/home/ibragim/.node-gyp/10.16.0/deps/zlib -I/home/ibragim/.node-gyp/10.16.0/deps/v8/include -I/home/ibragim/mclub/node_modules/sharp/node_modules/node-addon-api -I/usr/local/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/stats.o.d.raw   -c -o Release/obj.target/sharp/src/stats.o ../src/stats.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DNAPI_VERSION=3' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DBUILDING_NODE_EXTENSION' -I/home/ibragim/.node-gyp/10.16.0/include/node -I/home/ibragim/.node-gyp/10.16.0/src -I/home/ibragim/.node-gyp/10.16.0/deps/openssl/config -I/home/ibragim/.node-gyp/10.16.0/deps/openssl/openssl/include -I/home/ibragim/.node-gyp/10.16.0/deps/uv/include -I/home/ibragim/.node-gyp/10.16.0/deps/zlib -I/home/ibragim/.node-gyp/10.16.0/deps/v8/include -I/home/ibragim/mclub/node_modules/sharp/node_modules/node-addon-api -I/usr/local/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/operations.o.d.raw   -c -o Release/obj.target/sharp/src/operations.o ../src/operations.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DNAPI_VERSION=3' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DBUILDING_NODE_EXTENSION' -I/home/ibragim/.node-gyp/10.16.0/include/node -I/home/ibragim/.node-gyp/10.16.0/src -I/home/ibragim/.node-gyp/10.16.0/deps/openssl/config -I/home/ibragim/.node-gyp/10.16.0/deps/openssl/openssl/include -I/home/ibragim/.node-gyp/10.16.0/deps/uv/include -I/home/ibragim/.node-gyp/10.16.0/deps/zlib -I/home/ibragim/.node-gyp/10.16.0/deps/v8/include -I/home/ibragim/mclub/node_modules/sharp/node_modules/node-addon-api -I/usr/local/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/pipeline.o.d.raw   -c -o Release/obj.target/sharp/src/pipeline.o ../src/pipeline.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DNAPI_VERSION=3' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DBUILDING_NODE_EXTENSION' -I/home/ibragim/.node-gyp/10.16.0/include/node -I/home/ibragim/.node-gyp/10.16.0/src -I/home/ibragim/.node-gyp/10.16.0/deps/openssl/config -I/home/ibragim/.node-gyp/10.16.0/deps/openssl/openssl/include -I/home/ibragim/.node-gyp/10.16.0/deps/uv/include -I/home/ibragim/.node-gyp/10.16.0/deps/zlib -I/home/ibragim/.node-gyp/10.16.0/deps/v8/include -I/home/ibragim/mclub/node_modules/sharp/node_modules/node-addon-api -I/usr/local/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/utilities.o.d.raw   -c -o Release/obj.target/sharp/src/utilities.o ../src/utilities.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DNAPI_VERSION=3' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DBUILDING_NODE_EXTENSION' -I/home/ibragim/.node-gyp/10.16.0/include/node -I/home/ibragim/.node-gyp/10.16.0/src -I/home/ibragim/.node-gyp/10.16.0/deps/openssl/config -I/home/ibragim/.node-gyp/10.16.0/deps/openssl/openssl/include -I/home/ibragim/.node-gyp/10.16.0/deps/uv/include -I/home/ibragim/.node-gyp/10.16.0/deps/zlib -I/home/ibragim/.node-gyp/10.16.0/deps/v8/include -I/home/ibragim/mclub/node_modules/sharp/node_modules/node-addon-api -I/usr/local/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/sharp.o.d.raw   -c -o Release/obj.target/sharp/src/sharp.o ../src/sharp.cc
  g++ -shared -pthread -rdynamic -m64  -Wl,-soname=sharp.node -o Release/obj.target/sharp.node -Wl,--start-group Release/obj.target/sharp/src/common.o Release/obj.target/sharp/src/metadata.o Release/obj.target/sharp/src/stats.o Release/obj.target/sharp/src/operations.o Release/obj.target/sharp/src/pipeline.o Release/obj.target/sharp/src/utilities.o Release/obj.target/sharp/src/sharp.o Release/obj.target/node_modules/node-addon-api/nothing.a -Wl,--end-group -L/usr/local/lib -lvips-cpp -lvips -lgobject-2.0 -lglib-2.0
  rm -rf "Release/sharp.node" && cp -af "Release/obj.target/sharp.node" "Release/sharp.node"
make: Leaving directory '/home/ibragim/mclub/node_modules/sharp/build'
gyp info ok 
npm verb lifecycle sharp@0.25.4~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.25.4~install: PATH: /home/ibragim/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ibragim/mclub/node_modules/sharp/node_modules/.bin:/home/ibragim/mclub/node_modules/.bin:/home/ibragim/.nvm/versions/node/v10.16.0/bin:/opt/node-v10.1.0-linux-x64/bin:/opt/node-v14.5.0-linux-x64/bin:/opt/node-v14.5.0-linux-x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
npm verb lifecycle sharp@0.25.4~install: CWD: /home/ibragim/mclub/node_modules/sharp
npm timing audit submit Completed in 1299ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 1299ms
npm timing audit body Completed in 0ms
npm timing action:install Completed in 9102ms
npm info lifecycle sharp@0.25.4~postinstall: sharp@0.25.4
npm timing action:postinstall Completed in 1ms
npm verb unlock done using /home/ibragim/.npm/_locks/staging-5fbcd5dd503ae70f.lock for /home/ibragim/mclub/node_modules/.staging
npm timing stage:executeActions Completed in 9167ms
npm timing stage:rollbackFailedOptional Completed in 4ms
npm timing stage:runTopLevelLifecycles Completed in 13632ms
npm verb saving [ { name: 'sharp', spec: '^0.25.4', save: 'dependencies' } ]
npm verb shrinkwrap skipping write for package.json because there were no changes.
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm verb shrinkwrap skipping write for package-lock.json because there were no changes.
npm info lifecycle undefined~postshrinkwrap: undefined
npm WARN mclub@1.0.0 No description
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

+ sharp@0.25.4
updated 1 package and audited 548 packages in 13.864s
found 0 vulnerabilities

npm verb exit [ 0, true ]
npm timing npm Completed in 14107ms
npm info ok

**Comment by lovell** [comment]
> info sharp Detected globally-installed libvips v8.9.2

You'll need to ensure that the globally-installed libvips has been compiled with support for the image formats you wish to process.
