### ISSUE TITLE
Error: Expected width, height and channels for raw pixel input

### ISSUE THREAD

**Issue by vladizs** [lovell/sharp#2316]
I need to calculate the size of the image, create a square with size based on images' size and then put image on created square

Getting an error with that code:
`Error: Expected width, height and channels for raw pixel input`

```js
const sharp = require('sharp');

const testImg = sharp('test.jpg');

const imgMin = 800;

testImg.metadata()
    .then(function (metadata) {
    let imgMax = imgMin > metadata.width && imgMin > metadata.height ?
    imgMin : metadata.width > metadata.height ? metadata.width : metadata.height;
    return sharp({
        create: {
            width: imgMax,
            height: imgMax,
            channels: 3,
            background: {r: 0, g: 255, b: 255}
        }
    })
    .jpeg()
    .toBuffer();
}).then( function (data) {
    sharp(data)
    .composite([{
        input: testImg,
        gravity: 'centre'
    }]).jpeg()
});

```

When I'm trying to set raw options, I'm getting an error:
`Error: Unsupported input '[object Object]' of type object when also providing options of type object`

Part of code with raw parameters:
```js
.then( function (data) {
    sharp(data)
    .composite([{
        input: testImg,
        gravity: 'centre',
        raw: {
            width: 800,
            height: 800,
            channels: 3
        }
    }]).jpeg()
});

```

**Comment by lovell** [comment]
Hi, the `input` parameter of `composite` accepts a Buffer or a String but you're trying to pass a sharp instance.

```diff
- input: testImg,
+ input: 'test.jpg',
```

If the image you're passing is JPEG (and therefore not raw, uncompressed pixel data) then you don't need to provide `raw` as an parameter.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
