### ISSUE TITLE
How Does Kernel Selection Affect CPU Usage & Processing Time When Resizing

### ISSUE THREAD

**Issue by UsamaAshraf** [lovell/sharp#2318]
I'm trying to minimize my application's CPU usage, which resizes ~18k images per minute using `sharp`, while at the same time not compromising too much on processing speed.

The default kernel (it being a resizing algorithm is the closest to what I understand about this) is `lanczos3`.

For all the other available kernels it was basically the same, except `nearest`.

From running a pretty basic stress test of 400 cycles which resizes **5 JPEG images of 320x240, about 20KB each**, to **640x480**, using the `nearest` kernel rather than the default has cut down CPU usage by ~52% and resizing time by ~65%. Which is pretty significant from my standpoint.

- Resizing is the only operation I need from `sharp`.

- The dimensions and disk sizes of the original images I do real processing on are fairly variable. Roughly 320x240 to 1024x768 and 15 KB to 3 MB. Though the majority are between 150 KB and 300 KB.
 

Wondering if someone could help me understand the relationship between these kernels and _both_ CPU usage and resizing time.

The code I used:

```js
const resizedImage = await sharp(imageBuffer, { failOnError: false })
                              .resize(640, 480, {
                                fit: 'fill',
                                //kernel: 'nearest',
                              })
                              .toBuffer()
```

I'm using a Macbook Pro, OS Catalina, i9, and 16GB RAM.

I have tried to Google a bit about this but nothing stood out, to me at least, that I could understand.

**Comment by lovell** [comment]
Hi, by selecting `nearest`, you're trading accuracy for speed. Use of a profiling tool such as [callgrind](https://valgrind.org/docs/manual/cl-manual.html) should allow you to determine which functions within libvips are consuming most CPU time for a given scenario.
