### ISSUE TITLE
How can I write to disk from a file stream?

### ISSUE THREAD

**Issue by canebat** [lovell/sharp#232]
I currently handle uploading images with:

    filestream.pipe(fs.createWriteStream(filepath));

Which will save to disk.

How do I replace this with sharp? I tried:
```
var transformer = sharp()
    .rotate()
    .resize(500,500);

var writeToDisk = sharp()
    .toFile(filepath);

filestream.pipe(transformer).pipe(writeToDisk);
```
But this gives:
```
_stream_readable.js:476
  dest.on('unpipe', onunpipe);
       ^
TypeError: Object [object Promise] has no method 'on'
```

**Comment by lovell** [comment]
Hi, try something like the following to achieve this:
```javascript
filestream.pipe(transformer).pipe(fs.createWriteStream(filepath));
```

**Comment by canebat** [comment]
I wanted to use `toFile` because this ticket suggested some headaches can be avoided if we let `libvps`  handle the writing.

https://github.com/lovell/sharp/issues/138

Is this no longer true?

**Comment by lovell** [comment]
The following is an example of Stream in, file out:
```javascript
var transformer = sharp()
    .rotate()
    .resize(500,500)
    .toFile(filepath, function(err) {
      // error handling
    });

filestream.pipe(transformer);
```
Whether filesystem vs Buffer vs Stream is best depends on environmental things such as IO and memory. I recommend you stress/performance test your code and systems to find out which is best for you - good luck!

If you're able to share details publicly, it's always interesting to learn what people are using `sharp` for over at the survey #35.

**Comment by canebat** [comment]
Ah okay, maybe I am just pre-optimizing too much. Thanks!
