### ISSUE TITLE
The picture becomes extremely blurry when resizing, but I just want to keep the clear quality and don’t care about the picture size.

### ISSUE THREAD

**Issue by wenlittleoil** [lovell/sharp#2321]
I have looked at this issue #1982 , but still it has not solved my problem, sorry for my poor english.  
```
    sharp('source.jpeg').resize(300, 168, {
      kernel: sharp.kernel.cubic,
      fit: 'cover',
    }).toFile('dest.jpeg');
```  
The `source.jpeg` with pixel of `1920*1080` and size of `220kb`, all i want is to resize it to pixel of `300*168` and keep the clear quality of source image. Actually i don't care about the byte size of destination at all. How to achieve it, I will appreciate your help.  
I have tried setting various kernel options, such as `nearest `, `cubic `, `mitchell `, `lanczos2 `, `lanczos3 ` etc.  However, It doesn't seem to work for me, same with setting `fastShrinkOnLoad: false`.

**Comment by lovell** [comment]
Please can you provide sample input, output and expected output images, plus the code/method used to generate them.

**Comment by wenlittleoil** [comment]
```
    sharp('source.png').resize(300, 347, {
      kernel: sharp.kernel.cubic,
      fit: 'cover',
    }).toFile('dest.png');
```    
![source](https://user-images.githubusercontent.com/26560615/90223631-fbae5180-de40-11ea-839a-c40154281b40.png)
![dest](https://user-images.githubusercontent.com/26560615/90223661-0ec12180-de41-11ea-81d4-0a4bdc61c7de.png)
  
As you can see above, the first image is `source.png`, the second image is `dest.png` which is much more blurred than the first image. I don't care about the byte size of the destination image, but it should be clearer in quality.

**Comment by wenlittleoil** [comment]
Here is another case, same problem with the above case:  
```
    sharp('test.jpeg')
    .resize(300,168, {
      kernel: sharp.kernel.cubic,
      fastShrinkOnLoad: false,
      fit: 'cover',
      position: 'center',
    })
    .jpeg({ quality: 100, progressive: true, force: false })
    .png({ quality: 100, progressive: true, force: false })
    .webp({ quality: 100, progressive: true, force: false })
    .toFile('result.jpeg');
```  
![test](https://user-images.githubusercontent.com/26560615/90225062-45983700-de43-11ea-8b90-37fa146655ae.jpeg)
![result](https://user-images.githubusercontent.com/26560615/90225076-49c45480-de43-11ea-8477-a9e1e30d618e.jpeg)

I saw this question raised by many partners, poor quality of image. I have tried `sharpen`, but it doesn't work at all. I'm going crazy because of this problem.

**Comment by wenlittleoil** [comment]
Wait, i seem to understand it. It seems that it only shows blur on my local MacBook machine, after uploading here, there is no quality problem. This issue can now be closed. Also thank you, sorry for my carelessness.

**Comment by polarathene** [comment]
> Wait, i seem to understand it. It seems that it only shows blur on my local MacBook machine

Out of curiosity, what changed? You're still viewing the images here via that same macbook? So the issue was how you were previously viewing the images? Did you view them at a larger resolution, despite reducing the dimensions? Was it via native image viewing app or in a website you were developing?

**Comment by wenlittleoil** [comment]
> > Wait, i seem to understand it. It seems that it only shows blur on my local MacBook machine
> 
> Out of curiosity, what changed? You're still viewing the images here via that same macbook? So the issue was how you were previously viewing the images? Did you view them at a larger resolution, despite reducing the dimensions? Was it via native image viewing app or in a website you were developing?

I'm developing a website. I put the picture `result.jpeg` with dimension 300*168 on a larger container with dimension 600*336, of course it looks more blurred. But if you put it on a container with dimension 300*168, the picture quality will not look so bad. You can understand by looking at the picture below located on my mac computer, then you will understand.  


<img width="852" alt="0051DFEA-3B7B-4172-9FD8-7161B6CACE21" src="https://user-images.githubusercontent.com/26560615/90841915-8d154a80-e390-11ea-9b8b-b636b72b15b2.png">

<img width="805" alt="DA09F879-7CBD-4F8C-80BA-C13813793195" src="https://user-images.githubusercontent.com/26560615/90841929-9999a300-e390-11ea-9684-8a4c4db9fd14.png">

**Comment by wenlittleoil** [comment]
> > > Wait, i seem to understand it. It seems that it only shows blur on my local MacBook machine
> > 
> > 
> > Out of curiosity, what changed? You're still viewing the images here via that same macbook? So the issue was how you were previously viewing the images? Did you view them at a larger resolution, despite reducing the dimensions? Was it via native image viewing app or in a website you were developing?
> 
> I'm developing a website. I put the picture `result.jpeg` with dimension 300*168 on a larger container with dimension 600*336, of course it looks more blurred. But if you put it on a container with dimension 300*168, the picture quality will not look so bad. Same on mac, you can understand by looking at the picture below located on my mac computer, then you will understand.
> 
> <img alt="0051DFEA-3B7B-4172-9FD8-7161B6CACE21" width="852" src="https://user-images.githubusercontent.com/26560615/90841915-8d154a80-e390-11ea-9b8b-b636b72b15b2.png">
> 
> <img alt="DA09F879-7CBD-4F8C-80BA-C13813793195" width="805" src="https://user-images.githubusercontent.com/26560615/90841929-9999a300-e390-11ea-9684-8a4c4db9fd14.png">

**Comment by polarathene** [comment]
This is an image preview from your file browser. It's irrelevant.

- It's scaling the image you're not viewing it at 100%
- It's not uncommon for other logic to affect image quality in these tools, it's a preview and that's how it should be treated.
