### ISSUE TITLE
Isn't ideal concurrency number of cpus minus 1?

### ISSUE THREAD

**Issue by adityapatadia** [lovell/sharp#2322]
I see sharp sets concurrency equal to number of CPUs. In a high load system, wouldn't it block event loop? I think it should be set to `number of cpus - 1`.

**Comment by lovell** [comment]
If "event loop" in this context refers to the Node.js event loop then the short answer is no, it does not block.

Did you see https://sharp.pixelplumbing.com/api-utility#concurrency which explains a little more about concurrency?

> Gets or, when a concurrency is provided, sets the number of threads libvips' should create to process each image. The default value is the number of CPU cores. A value of 0 will reset to this default.

> The maximum number of images that can be processed in parallel is limited by libuv's UV_THREADPOOL_SIZE environment variable.

**Comment by adityapatadia** [comment]
I am talking about a situation in which say all cores are busy processing image, won't the scheduling of nodejs event loop hampered?

**Comment by lovell** [comment]
Each thread's share of CPU time depends on the OS scheduler, e.g. Linux uses https://en.wikipedia.org/wiki/Completely_Fair_Scheduler

**Comment by adityapatadia** [comment]
Okay sounds good. Thanks a lot for help.
