### ISSUE TITLE
Why jemalloc greatly reduces memory usage?

### ISSUE THREAD

**Issue by adityapatadia** [lovell/sharp#2324]
I have tried running sharp on production system with jemalloc and without jemalloc running glibc with 20.04 ubuntu. I see jemalloc greatly reduces memory usage.

With Jemalloc:
<img width="479" alt="Screenshot 2020-08-15 at 10 58 14 AM" src="https://user-images.githubusercontent.com/1086617/90309466-8016d800-df06-11ea-9f99-3a61450e7396.png">

Without Jemalloc:
<img width="473" alt="Screenshot 2020-08-15 at 2 47 03 PM" src="https://user-images.githubusercontent.com/1086617/90309469-886f1300-df06-11ea-94a1-f0c356011c4b.png">

**Comment by lovell** [comment]
Did you see the canonical discussion about memory allocators at #955 ?

**Comment by adityapatadia** [comment]
I saw discussion and only thing I understand is Jemalloc is better retuning memory back to OS. It's strange that glibc which works super well in other scenarios does not work well with sharp/libvips workload. Anyway, this question was asked just out of curiosity.

I am happy with jemalloc.
