### ISSUE TITLE
Cyclic require() calls in comparator.js

### ISSUE THREAD

**Issue by TruffeCendree** [lovell/sharp#2325]
After many issues in my projects about cyclic imports, I now use the nocycle module (https://www.npmjs.com/package/nocycle).

The reason of my bugs was that inter-dependant `require()` may result to `undefined` insteadof of the right import. Example :

``` js
// a.js
console.log(require('B'))
module.exports = function () {};

// b.js
console.log(required('A'));
module.exports = function () {};
```

Currently, nocycle detect a require-loop in sharp.

```
cycle require is detected. require stack is:
	* node_modules/sharp/node_modules/semver/classes/comparator.js
	  node_modules/sharp/node_modules/semver/classes/range.js
	* node_modules/sharp/node_modules/semver/classes/comparator.js
	  node_modules/sharp/node_modules/semver/index.js
	  node_modules/sharp/lib/libvips.js
	  node_modules/sharp/lib/constructor.js
	  node_modules/sharp/lib/index.js
```

I do not have any issue with sharp. That is just a warning to prevent future regressions.

**Comment by lovell** [comment]
Did you intend to open this issue on the https://github.com/npm/node-semver repo, as that is the source of the cyclic import?

**Comment by TruffeCendree** [comment]
Oups. You are right. I did not see the source was in a nested node_modules. I had just checked the 'node_modules/sharp/' path prefix.

Thanks for you help.
