### ISSUE TITLE
Animated GIF to PNG spritesheet

### ISSUE THREAD

**Issue by almosnow** [lovell/sharp#2326]
I'm looking to create an image with all the frames from a GIF, concatenated, like this one:

![12-129142_exemplo-de-spritesheet-sprite-sheet-megaman-png-transparent](https://user-images.githubusercontent.com/4924797/90323072-dba28f00-df21-11ea-841b-22f77ba85ebe.png)

Is it possible with sharp? Any suggestions on how may I do it?

Thanks and sorry about this, I know it's more a request for help than an actual issue with your library.

**Comment by lovell** [comment]
The following will create a "toilet roll" image with all the frames of the GIF:
```js
sharp("input.gif", { pages: -1 }).toFile("output.png")
```
Input:
![](https://user-images.githubusercontent.com/210965/90380868-888d2100-e074-11ea-8f1f-2920212eb45c.gif)

Output:
![](https://user-images.githubusercontent.com/210965/90380894-8e830200-e074-11ea-9cbf-c0a58d1032d0.png)

**Comment by almosnow** [comment]
Thank you and thanks for this great library!

**Comment by natuan62** [comment]
@lovell can we config to sprite by horizontal direction instead of vertical ?
