### ISSUE TITLE
Is there a way to resize an image ONLY if the image is smaller or bigger than specified size?

### ISSUE THREAD

**Issue by aukan** [lovell/sharp#233]
I tried the max() and min() but of course those methods always resize the image and what I'm trying to find is how to tell sharp to only resize the image if (i.e.) the image is bigger than 640w and in any other case, leave the image as is.

**Comment by Zewy** [comment]
You can use the metadata method and make a if statement on width?
like this untested code.

```
var image = sharp('/image/path/img.jpg');
image.metadata(function( err, metadata ) {
if ( metadata.width > 640 ) {
image.resize(640, null).toFile('output.jpg');
} else {
image.toFile('output.jpg');
});

**Comment by aukan** [comment]
Thank you Zewy, that actually can solve the problem in case I have the image in my file system. But I was wondering if you could actually do that with streams, for example (using your code):

```js
// This code is just an idea. It does not currently work with sharp.
var readStream = fs.createReadStream('/image/path/img.jpg');
var transform = sharp(readStream).metadata(function(err, metadata ) {
  if ( metadata.width > 640 ) {
    transform.resize(640, null).toFile('output.jpg');
  } else {
    transform.toFile('output.jpg');
  }
  readStream.pipe(transform);
});
```

I tried this and the metadata callback never returns, which I suppose it means that sharp does not support streams for that. Maybe for a filesystem it's not so obvious why I would want to do this, but what if I have to download the image from a url?:

```js
// This code is just an idea. It does not currently work with sharp.
var http = require('http');
http.get('http://some.file/in/internet.jpg', function (err, res) {
  var transform = sharp(res).metadata(function( err, metadata ) {
    if ( metadata.width > 640 ) {
      transform.resize(640, null).toFile('output.jpg');
    } else {
      transform.toFile('output.jpg');
    }
    res.pipe(transform);
  });
});
```

In this case, in the same request that I did to obtain the image, I'm already processing it. 

Please correct me if I'm wrong but I believe that right now the only way is to download the image first and then get the metadata and then make the transformation, which is still fast, but it would be faster the way I just posted.

The thing is I'm not sure if this is even possible because I know that, in order to get the metadata, you might need to get at least the first chunk of data and maybe by then is impossible to pipe the stream to other streams. Any ideas?

**Comment by aukan** [comment]
Sorry, I closed by mistake. Reopened.

**Comment by Zewy** [comment]
Inside http.get
you need to do this. else you don't have the full image to work with.
I think this will work not sure.
```
http.get('http://some.file/in/internet.jpg', function (err, res) {
var data = '';
    req.on('data', function (chunk) {
        data += chunk;
    });
    req.on('end', function() {
     //Work with Sharp here!
    });
});

**Comment by lovell** [comment]
Hello, https://github.com/lovell/sharp/issues/230#issuecomment-107739934 and https://github.com/lovell/sharp/issues/230#issuecomment-107885877 provide a couple of possible solutions for setting `extract` parameters based on image metadata when using Streams. You might be able to rework these for the `resize` parameters.

**Comment by aukan** [comment]
Thank you @Zewy for your replies. 

@lovell, that is exactly the way I was looking to solve it. Thank you.
