### ISSUE TITLE
如何去(底色/背景)? / How to go (base color/background)?

### ISSUE THREAD

**Issue by zhangbowy** [lovell/sharp#2332]
比如这个图 如何把白色背景变透明?
![231f11ea82c503b26c38e21d433d8ab7](https://user-images.githubusercontent.com/33514252/91007908-b68fd980-e60f-11ea-882f-bc000d1ddc74.jpg)

**Comment by lovell** [comment]
> For example, how to make the white background transparent in this picture?

For JPEG input i.e. without an alpha channel, please see #1648

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by zhangbowy** [comment]
> > For example, how to make the white background transparent in this picture?
> 
> For JPEG input i.e. without an alpha channel, please see #1648

ok
