### ISSUE TITLE
How to cut beyond synthesis

### ISSUE THREAD

**Issue by banli17** [lovell/sharp#2333]
```js
const path = require('path')
const sharp = require('sharp')

sharp({
    create: {
        width: 550,
        height: 300,
        channels: 4,
        background: {r: 0, g: 0, b: 0, alpha: 0},
    }
})
    .composite([
        {input: "background.png", left: 0, top: 0, width: 450, height: 300},
        {input: "pkq.jpg", left: 400, top: 100, width: 30},
    ])
    // .extract({
    //     left: 0,
    //     top: 0,
    //     width: 450,
    //     height: 300
    // })
    .toFile(path.resolve(__dirname, "out2.png"))
```
![image](https://user-images.githubusercontent.com/12556069/91064239-97219c80-e661-11ea-9bfe-460efb2bae9a.png)

![image](https://user-images.githubusercontent.com/12556069/91063989-3abe7d00-e661-11ea-97e9-0f63291d0cfc.png)

i want this part jpg

![image](https://user-images.githubusercontent.com/12556069/91064061-5a55a580-e661-11ea-9a9a-19ae2cd1ae11.png)

but if i use extract,  result is below:

![image](https://user-images.githubusercontent.com/12556069/91064137-78230a80-e661-11ea-83f2-d096fcf8b5aa.png)

**Comment by lovell** [comment]
Hi, you'll need to break this into two pipelines:
```js
sharp({ create: { ... })
  .composite([ ... ])
  .toBuffer()
  .then(data => sharp(data)
    .extract({ ... })
    .toFile( ... )
  );
```

**Comment by banli17** [comment]
@lovell   thx

```
.toFormat('png')
        .toBuffer()
```
