### ISSUE TITLE
Issue installing gatsby templates that require sharp package

### ISSUE THREAD

**Issue by spk2dc** [lovell/sharp#2334]
I am unable to create a new gatsby project for any template that requires the sharp package and get errors with exit code 1 or 2. I have found forums indicating that many people seemed to be having this exact problem a year ago, but unfortunately all of the solutions I have tried from those posts have not fixed my errors. Below are 2 help threads in particular that I have been following and tried a few of the solutions including the author's 

`"resolutions": {
    "minipass": "2.7.0"
  },`

that was recommended as a workaround, but none have worked. 

**Related forum posts:**
https://github.com/lovell/sharp/issues/1882
https://github.com/isaacs/minipass/issues/9

**Here is the full output I get when trying to create a new gatsby project based off of a template that uses sharp:**

senthil@senthil-VirtualBox:~/Documents/projects/portfolio$ gatsby new gatsby-london https://github.com/ImedAdel/gatsby-london
info Creating new site from git: https://github.com/ImedAdel/gatsby-london.git
Cloning into 'gatsby-london'...
remote: Enumerating objects: 111, done.
remote: Counting objects: 100% (111/111), done.
remote: Compressing objects: 100% (107/107), done.
remote: Total 111 (delta 0), reused 97 (delta 0), pack-reused 0
Receiving objects: 100% (111/111), 10.18 MiB | 4.22 MiB/s, done.
success Created starter directory layout
info Installing packages...
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "gatsby-plugin-netlify > webpack-assets-manifest@3.1.1" has unmet peer dependency "webpack@>=4.4.0".
[4/4] Building fresh packages...
[-/6] ⠁ waiting...
[2/6] ⠁ sharp
[-/6] ⠁ waiting...
[-/6] ⠂ waiting...
error /home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/sharp
Output:
info sharp Using cached /home/senthil/.npm/_libvips/libvips-8.7.4-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=14.6.0 runtime=node arch=x64 libc= platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.6.0 | linux | x64
gyp info find Python using Python version 2.7.17 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/senthil/.cache/node-gyp/14.6.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/senthil/.cache/node-gyp/14.6.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/senthil/.cache/node-gyp/14.6.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
../src/stats.cc: In member function ‘virtual void StatsWorker::HandleOKCallback()’:
../src/stats.cc:130:37: error: no matching function for call to ‘v8::Array::Set(int&, v8::Local<v8::Object>&)’
         channels->Set(i, channelStat);
                                     ^
In file included from /home/senthil/.cache/node-gyp/14.6.0/include/node/node.h:67:0,
                 from ../src/stats.cc:19:
/home/senthil/.cache/node-gyp/14.6.0/include/node/v8.h:3670:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/senthil/.cache/node-gyp/14.6.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/senthil/.cache/node-gyp/14.6.0/include/node/v8.h:3673:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/senthil/.cache/node-gyp/14.6.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
sharp.target.mk:138: recipe for target 'Release/obj.target/sharp/src/stats.o' failed
make: Leaving directory '/home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/sharp/build'
make: *** [Release/obj.target/sharp/src/stats.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.4.0-42-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/sharp

 ERROR 

Command failed with exit code 1: yarnpkg

  Error: Command failed with exit code 1: yarnpkg
  
  - error.js:56 makeError
    [lib]/[gatsby-cli]/[execa]/lib/error.js:56:11
  
  - index.js:114 handlePromise
    [lib]/[gatsby-cli]/[execa]/index.js:114:26
  
  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5
  
  - init-starter.js:140 install
    [lib]/[gatsby-cli]/lib/init-starter.js:140:7
  
  - init-starter.js:210 clone
    [lib]/[gatsby-cli]/lib/init-starter.js:210:3
  
  - init-starter.js:351 initStarter
    [lib]/[gatsby-cli]/lib/init-starter.js:351:5
  
  - create-cli.js:421 
    [lib]/[gatsby-cli]/lib/create-cli.js:421:7
  

senthil@senthil-VirtualBox:~/Documents/projects/portfolio$ 

**And here is my system info in case it's necessary:**
`senthil@senthil-VirtualBox:~/Documents/projects/portfolio$ cat /proc/version`
`Linux version 5.4.0-42-generic (buildd@lgw01-amd64-023) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020`

**Comment by lovell** [comment]
>  prebuild-install WARN install No prebuilt binaries found (target=14.6.0 runtime=node arch=x64 libc= platform=linux)

Please upgrade gatsby-plugin-sharp and therefore sharp to the latest version.

As an aside, I notice you deleted a question from the installation issue template that might have helped you get to this answer yourself. Was there a reason for that? Could this question have been made clearer to help you and others?

* Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

**Comment by spk2dc** [comment]
Sorry, I thought adding everything from the template might make my question too cluttered and unclear. My mistake, I will add that information here and then respond to your comment as I am still unable to fix my error. 

**Template Responses**
_Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?_
yes

_Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime?_
npm 6.14.8
node 14.6.0

_Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?_
`npm view sharp dist-tags.latest`: 0.25.4
`npm ls sharp`: 0.22.1

I am unable to upgrade to the latest version, details are included below the rest of the template responses. 

_If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?_
not installing with sudo

_If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?_
not using ignore scripts

_What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?_
there are a few warnings but no error messages, and when I immediately check the installed version afterwards it says it's missing as shown in the attached file
[npm install --verbose sharp outputs.txt](https://github.com/lovell/sharp/files/5124501/npm.install.--verbose.sharp.outputs.txt)


_What is the output of running `npx envinfo --binaries --system`?_
npx: installed 1 in 1.446s

  System:
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (2) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    Memory: 489.96 MB / 2.87 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 14.6.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm



**Details on problems upgrading to latest version of sharp**
I have tried upgrading the to use the latest version of sharp but am still unable to successfully install it and run `gatsby develop`. When initially installing the template it uses sharp 0.22.1, so then I change `"gatsby-plugin-sharp": "^2.0.36"` to `"gatsby-plugin-sharp": "^2.6.24"` and `"gatsby-transformer-sharp": "^2.1.19"` to `"gatsby-transformer-sharp": "^2.5.12"` and run `npm i` to install the latest version of sharp 0.25.4, but it seems to not be successful. Any advice you could provide on how I can resolve this issue would be appreciated. 


**Logs from trying to update**
[2020-08-25T14_45_39_553Z-debug.log](https://github.com/lovell/sharp/files/5124418/2020-08-25T14_45_39_553Z-debug.log)

senthil@senthil-VirtualBox:~/Documents/projects/portfolio/gatsby-london$ npm ls sharp
gatsby-london@1.0.0 /home/senthil/Documents/projects/portfolio/gatsby-london
├─┬ gatsby-plugin-manifest@2.1.1
│ └── sharp@0.22.1 
├─┬ gatsby-plugin-sharp@2.0.36
│ └── sharp@0.22.1  deduped
└─┬ gatsby-transformer-sharp@2.1.19
  └── sharp@0.22.1  deduped

senthil@senthil-VirtualBox:~/Documents/projects/portfolio/gatsby-london$ npm i
npm WARN deprecated chokidar@2.1.2: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated flat@4.1.0: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.
npm WARN deprecated joi@12.0.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated graphql-import@0.7.1: GraphQL Import has been deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-import for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.
npm WARN deprecated @hapi/joi@15.1.1: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/address@2.1.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> husky@2.2.0 preuninstall /home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/husky
> node husky uninstall

husky > Uninstalling git hooks
husky > Done
npm WARN rm not removing /home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/.bin/semver as it wasn't installed by /home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/semver
npm WARN rm not removing /home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/.bin/regjsparser as it wasn't installed by /home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/regjsparser
npm WARN rm not removing /home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/.bin/json5 as it wasn't installed by /home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/json5
npm WARN rm not removing /home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/.bin/mime as it wasn't installed by /home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/mime
npm WARN rm not removing /home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/.bin/jsesc as it wasn't installed by /home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/jsesc
npm WARN rm not removing /home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/.bin/detect as it wasn't installed by /home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/detect-port
npm WARN rm not removing /home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/.bin/detect-port as it wasn't installed by /home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/detect-port

> sharp@0.25.4 install /home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/gatsby-plugin-sharp/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /home/senthil/.npm/_libvips/libvips-8.9.1-linux-x64.tar.gz

> sharp@0.25.4 install /home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/gatsby-transformer-sharp/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /home/senthil/.npm/_libvips/libvips-8.9.1-linux-x64.tar.gz

> sharp@0.22.1 install /home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /home/senthil/.npm/_libvips/libvips-8.7.4-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=14.6.0 runtime=node arch=x64 libc= platform=linux)
make: Entering directory '/home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
../src/stats.cc: In member function ‘virtual void StatsWorker::HandleOKCallback()’:
../src/stats.cc:130:37: error: no matching function for call to ‘v8::Array::Set(int&, v8::Local<v8::Object>&)’
         channels->Set(i, channelStat);
                                     ^
In file included from /home/senthil/.cache/node-gyp/14.6.0/include/node/node.h:67:0,
                 from ../src/stats.cc:19:
/home/senthil/.cache/node-gyp/14.6.0/include/node/v8.h:3670:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/senthil/.cache/node-gyp/14.6.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/senthil/.cache/node-gyp/14.6.0/include/node/v8.h:3673:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/senthil/.cache/node-gyp/14.6.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
sharp.target.mk:138: recipe for target 'Release/obj.target/sharp/src/stats.o' failed
make: *** [Release/obj.target/sharp/src/stats.o] Error 1
make: Leaving directory '/home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.4.0-42-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/senthil/Documents/projects/portfolio/gatsby-london/node_modules/sharp
gyp ERR! node -v v14.6.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/gatsby-recipes/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/gatsby-page-utils/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"14.6.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN gatsby-transformer-sharp@2.5.13 requires a peer of gatsby@^2.12.1 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-recipes@0.2.17 requires a peer of react@^16.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN @mdx-js/react@2.0.0-next.7 requires a peer of react@^16.13.1 but none is installed. You must install peer dependencies yourself.
npm WARN @mdx-js/runtime@2.0.0-next.7 requires a peer of react@^16.13.1 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-interface@0.0.166 requires a peer of gatsby@2.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-interface@0.0.166 requires a peer of react@16.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-interface@0.0.166 requires a peer of react-dom@16.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN @mdx-js/react@1.6.16 requires a peer of react@^16.13.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-reconciler@0.25.1 requires a peer of react@^16.13.1 but none is installed. You must install peer dependencies yourself.
npm WARN theme-ui@0.2.52 requires a peer of @mdx-js/react@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @turist/fetch@7.1.7 requires a peer of node-fetch@2 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.22.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/senthil/.npm/_logs/2020-08-25T14_45_39_553Z-debug.log
senthil@senthil-VirtualBox:~/Documents/projects/portfolio/gatsby-london$ npm ls sharp
gatsby-london@1.0.0 /home/senthil/Documents/projects/portfolio/gatsby-london
├─┬ gatsby-plugin-sharp@2.6.28
│ └── sharp@0.25.4 
└─┬ gatsby-transformer-sharp@2.5.13
  └── sharp@0.25.4

**Comment by lovell** [comment]
It looks like you'll need to upgrade gatsby-plugin-manifest as well. `npm ls sharp` will tell you which other dependencies might be responsible for outdated versions.

Given you've switched from using yarn to npm, you might need to run `rm -rf node_modules && npm install` too.

**Comment by spk2dc** [comment]
Ah ok that fixed my installation problems and I can now see the template locally when I run gatsby develop, thank you so much!! For anyone else having these problems the last thing I changed was `"gatsby-plugin-manifest": "^2.1.1"` to `"gatsby-plugin-manifest": "^2.4.21"`
