### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _g_once_impl

### ISSUE THREAD

**Issue by ctrlaltdylan** [lovell/sharp#2337]
Output during fatal error during `yarn dev`:

```
dyld: lazy symbol binding failed: Symbol not found: _g_once_impl
  Referenced from: /Users/pierce/dev/verdict/node_modules/sharp/build/Release/sharp.node
  Expected in: /Users/pierce/dev/verdict/node_modules/@vouched/client/node_modules/sharp/build/Release/../../vendor/lib/libvips.42.dylib

dyld: Symbol not found: _g_once_impl
  Referenced from: /Users/pierce/dev/verdict/node_modules/sharp/build/Release/sharp.node
  Expected in: /Users/pierce/dev/verdict/node_modules/@vouched/client/node_modules/sharp/build/Release/../../vendor/lib/libvips.42.dylib
```

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

Yes, running `sharp@0.26.0`

What are the steps to reproduce?

Initialize your application.

What is the expected behaviour?

For the application to start with `sharp` installed.

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

No, it's an infrastructure problem not a code problem.

Are you able to provide a sample image that helps explain the problem?

![Screen Shot 2020-08-25 at 10 26 26 PM](https://user-images.githubusercontent.com/2694734/91248167-065ec580-e722-11ea-8728-ce96dd56a5de.png)

What is the output of running `npx envinfo --binaries --system`?
```
  System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 185.94 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.5.0 - ~/.asdf/installs/nodejs/14.5.0/bin/node
    Yarn: 1.22.4 - ~/.asdf/shims/yarn
    npm: 6.14.5 - ~/.asdf/installs/nodejs/14.5.0/bin/npm
```

**Comment by ctrlaltdylan** [comment]
Building the npm packages from source fixed the issue:

`npm install --build-from-source`

**Comment by lovell** [comment]
Hi, you shouldn't need to compile from source.

The appearance of `vendor/lib/libvips.42.dylib` in the error message means this error is not from sharp v0.26.0. The latest version includes the libvips version in the path e.g. `vendor/lib/8.10.0/libvips.42.dylib`. Please make sure there are no old or mismatched versions in lockfiles etc.

**Comment by louh** [comment]
This is happening to me. Looking in `package-lock.json` it seems that the `@11ty/eleventy-img` package is installing `sharp@0.25.4` as a subdependency in a nested node_modules directory, although I specify `sharp@0.26.0` in my own dependency.

Why would my `require('sharp')` use the wrong version? How do I fix this?

**Comment by lovell** [comment]
@louh Please submit a PR to https://github.com/11ty/eleventy-img to upgrade sharp. The latest prebuilt binaries are statically linked and avoid many of these problems.

**Comment by letsfire** [comment]
dyld: lazy symbol binding failed: Symbol not found: _g_once_impl
  Referenced from: /Users/letsfire/ing-sports.com/efoto-app/grapher-pc/node_modules/sharp/build/Release/sharp.node
  Expected in: /usr/local/lib/libvips-cpp.42.dylib
dyld: Symbol not found: _g_once_impl
  Referenced from: /Users/letsfire/ing-sports.com/efoto-app/grapher-pc/node_modules/sharp/build/Release/sharp.node
  Expected in: /usr/local/lib/libvips-cpp.42.dylib

**Comment by 0123cf** [comment]
/node_modules/sharp/build/Release/../.././vendor/8.13.3/darwin-x64/lib/libvips-cpp.42.dylib
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by KeitelDOG** [comment]
Didn't get it at version `^0.29.1` in and older project, and now getting it at version `^0.31.3`. Is there any reason behind this? Or should I downgrade with deprecation and security risk?
