### ISSUE TITLE
Cannot use sharp on MacOS

### ISSUE THREAD

**Issue by scott-man** [lovell/sharp#2342]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)? `Yes`

Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime? `Yes`

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`? `Yes`

If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag? `Not installing as sudo`

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag? `Not using ignore-scripts`

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages? 

npm i --verbose sharp@^0.26.0
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'i',
npm verb cli   '--verbose',
npm verb cli   'sharp@^0.26.0'
npm verb cli ]
npm info using npm@6.14.6
npm info using node@v12.18.3
npm verb npm-session c77bbf3463a04d58
npm http fetch GET 200 https://registry.npmjs.org/sharp 12ms (from cache)
npm timing stage:loadCurrentTree Completed in 1136ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 13ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 613ms
npm http fetch GET 304 https://registry.npmjs.org/simple-get 125ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/prebuild-install 126ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/semver 128ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color 130ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-addon-api 129ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-fs 132ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-convert 30ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-name 30ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/expand-template 34ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/napi-build-utils 34ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/noop-logger 35ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-abi 39ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/github-from-package 45ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 25ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-concat 26ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mimic-response 24ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mkdirp-classic 32ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-stream 35ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/readable-stream 26ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-constants 33ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bl 100ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/buffer 30ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 1789ms
npm timing stage:loadIdealTree Completed in 2634ms
npm timing stage:generateActionsToTake Completed in 64ms
npm verb correctMkdir /Users/sheldon/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/sheldon/.npm/_locks/staging-c4593107e5dc1f55.lock for /Users/sheldon/projects/idplans/bpi/node_modules/.staging
npm timing action:extract Completed in 31ms
npm info lifecycle sharp@0.25.4~preuninstall: sharp@0.25.4
npm info lifecycle sharp@0.25.4~uninstall: sharp@0.25.4
npm verb unbuild rmStuff sharp@0.25.4 from /Users/sheldon/projects/idplans/bpi/node_modules
npm info lifecycle sharp@0.25.4~postuninstall: sharp@0.25.4
npm info lifecycle tar@6.0.5~preuninstall: tar@6.0.5
npm info lifecycle tar@6.0.5~uninstall: tar@6.0.5
npm verb unbuild rmStuff tar@6.0.5 from /Users/sheldon/projects/idplans/bpi/node_modules
npm verb unbuild rmStuff in /Users/sheldon/projects/idplans/bpi/node_modules/sharp/node_modules
npm info lifecycle tar@6.0.5~postuninstall: tar@6.0.5
npm info lifecycle minizlib@2.1.2~preuninstall: minizlib@2.1.2
npm info lifecycle minizlib@2.1.2~uninstall: minizlib@2.1.2
npm verb unbuild rmStuff minizlib@2.1.2 from /Users/sheldon/projects/idplans/bpi/node_modules
npm verb unbuild rmStuff in /Users/sheldon/projects/idplans/bpi/node_modules/sharp/node_modules
npm info lifecycle minizlib@2.1.2~postuninstall: minizlib@2.1.2
npm info lifecycle fs-minipass@2.1.0~preuninstall: fs-minipass@2.1.0
npm info lifecycle fs-minipass@2.1.0~uninstall: fs-minipass@2.1.0
npm verb unbuild rmStuff fs-minipass@2.1.0 from /Users/sheldon/projects/idplans/bpi/node_modules
npm verb unbuild rmStuff in /Users/sheldon/projects/idplans/bpi/node_modules/sharp/node_modules
npm info lifecycle fs-minipass@2.1.0~postuninstall: fs-minipass@2.1.0
npm info lifecycle minipass@3.1.3~preuninstall: minipass@3.1.3
npm info lifecycle minipass@3.1.3~uninstall: minipass@3.1.3
npm verb unbuild rmStuff minipass@3.1.3 from /Users/sheldon/projects/idplans/bpi/node_modules
npm verb unbuild rmStuff in /Users/sheldon/projects/idplans/bpi/node_modules/sharp/node_modules
npm info lifecycle minipass@3.1.3~postuninstall: minipass@3.1.3
npm info lifecycle yallist@4.0.0~preuninstall: yallist@4.0.0
npm info lifecycle yallist@4.0.0~uninstall: yallist@4.0.0
npm verb unbuild rmStuff yallist@4.0.0 from /Users/sheldon/projects/idplans/bpi/node_modules
npm verb unbuild rmStuff in /Users/sheldon/projects/idplans/bpi/node_modules/sharp/node_modules
npm info lifecycle yallist@4.0.0~postuninstall: yallist@4.0.0
npm info lifecycle mkdirp@1.0.4~preuninstall: mkdirp@1.0.4
npm info lifecycle mkdirp@1.0.4~uninstall: mkdirp@1.0.4
npm verb unbuild rmStuff mkdirp@1.0.4 from /Users/sheldon/projects/idplans/bpi/node_modules
npm verb unbuild rmStuff in /Users/sheldon/projects/idplans/bpi/node_modules/sharp/node_modules
npm info lifecycle mkdirp@1.0.4~postuninstall: mkdirp@1.0.4
npm info lifecycle chownr@2.0.0~preuninstall: chownr@2.0.0
npm info lifecycle chownr@2.0.0~uninstall: chownr@2.0.0
npm verb unbuild rmStuff chownr@2.0.0 from /Users/sheldon/projects/idplans/bpi/node_modules
npm verb unbuild rmStuff in /Users/sheldon/projects/idplans/bpi/node_modules/sharp/node_modules
npm info lifecycle chownr@2.0.0~postuninstall: chownr@2.0.0
npm timing action:unbuild Completed in 17ms
npm timing action:remove Completed in 166ms
npm timing action:finalize Completed in 7ms
npm timing action:refresh-package-json Completed in 10ms
npm info lifecycle sharp@0.26.0~preinstall: sharp@0.26.0
npm timing action:preinstall Completed in 1ms
npm info linkStuff sharp@0.26.0
npm timing action:build Completed in 3ms
npm info lifecycle sharp@0.26.0~install: sharp@0.26.0

> sharp@0.26.0 install /Users/sheldon/projects/idplans/bpi/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /Users/sheldon/.npm/_libvips/libvips-8.10.0-darwin-x64.tar.br
prebuild-install info begin Prebuild-install version 5.3.5
prebuild-install info looking for cached prebuild @ /Users/sheldon/.npm/_prebuilds/7f763b-sharp-v0.26.0-napi-v3-darwin-x64.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /Users/sheldon/.npm/_prebuilds/7f763b-sharp-v0.26.0-napi-v3-darwin-x64.tar.gz
prebuild-install info unpack resolved to /Users/sheldon/projects/idplans/bpi/node_modules/sharp/build/Release/sharp.node
prebuild-install info install Successfully installed prebuilt binary!
npm verb lifecycle sharp@0.26.0~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.26.0~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/sheldon/projects/idplans/bpi/node_modules/sharp/node_modules/.bin:/Users/sheldon/projects/idplans/bpi/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
npm verb lifecycle sharp@0.26.0~install: CWD: /Users/sheldon/projects/idplans/bpi/node_modules/sharp
npm timing audit submit Completed in 852ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 851ms
npm timing audit body Completed in 1ms
npm timing action:install Completed in 3311ms
npm info lifecycle sharp@0.26.0~postinstall: sharp@0.26.0
npm timing action:postinstall Completed in 1ms
npm verb unlock done using /Users/sheldon/.npm/_locks/staging-c4593107e5dc1f55.lock for /Users/sheldon/projects/idplans/bpi/node_modules/.staging
npm timing stage:executeActions Completed in 3559ms
npm timing stage:rollbackFailedOptional Completed in 0ms
npm timing stage:runTopLevelLifecycles Completed in 8703ms
npm verb saving [ { name: 'sharp', spec: '^0.26.0', save: 'dependencies' } ]
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm info lifecycle undefined~postshrinkwrap: undefined
+ sharp@0.26.0
removed 7 packages, updated 1 package and audited 1193 packages in 10.612s

37 packages are looking for funding
  run `npm fund` for details

found 4 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
npm verb exit [ 0, true ]
npm timing npm Completed in 11248ms
npm info ok 

What is the output of running `npx envinfo --binaries --system`?

  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 96.18 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm

**Comment by scott-man** [comment]
Additional logs from Docker:

bpi-container | /app/node_modules/sharp/lib/libvips.js:62
bpi-container |       throw new Error(`'${vendorPlatformId}' binaries cannot be used on the '${currentPlatformId}' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the '${currentPlatformId}' platform.`);
bpi-container |       ^
bpi-container | 
bpi-container | Error: 'darwin-x64' binaries cannot be used on the 'linux-x64' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'linux-x64' platform.
bpi-container |     at Object.hasVendoredLibvips (/app/node_modules/sharp/lib/libvips.js:62:13)
bpi-container |     at Object.<anonymous> (/app/node_modules/sharp/lib/constructor.js:7:22)
bpi-container |     at Module._compile (internal/modules/cjs/loader.js:1137:30)
bpi-container |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
bpi-container |     at Module.load (internal/modules/cjs/loader.js:985:32)
bpi-container |     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
bpi-container |     at Module.require (internal/modules/cjs/loader.js:1025:19)
bpi-container |     at require (internal/modules/cjs/helpers.js:72:18)
bpi-container |     at Object.<anonymous> (/app/node_modules/sharp/lib/index.js:3:15)
bpi-container |     at Module._compile (internal/modules/cjs/loader.js:1137:30)

**Comment by lovell** [comment]
> bpi-container | Error: 'darwin-x64' binaries cannot be used on the 'linux-x64' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'linux-x64' platform.

Have you ensured the platform and version of Node.js used for npm install is the same as the platform and version of Node.js used at runtime?

**Comment by scott-man** [comment]
@lovell 
These is what I get when I say `node -v`
`v12.18.3`

And this is the entry in my docker configuration: `FROM node:12.18.3`

**Comment by lovell** [comment]
Have you ensured the platform used for `npm install` is the same as the platform used at runtime? It looks you're doing the former on macOS (Darwin) and the latter on Linux.

**Comment by scott-man** [comment]
@lovell you are right. My Docker image was on Linux.
Got this resolved.
