### ISSUE TITLE
Processed image is too large for the WebP format

### ISSUE THREAD

**Issue by derom** [lovell/sharp#2344]
Hello! It looks like we get wrong value of pageHeight, so I tried to fix it in this pr #2343

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
yes, 0.26.0

What are the steps to reproduce?
Try to process webp with a "huge" amount of pages. For example,
height: 91800,
pages: 459,
pageHeight: 200

What is the expected behaviour?
image is succefuly processed toBuffer

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
provided in unit test

Are you able to provide a sample image that helps explain the problem?
provided in pr

**Comment by lovell** [comment]
v0.26.1 now available, thank you for fixing this.
