### ISSUE TITLE
Gaussian Noise in sharp

### ISSUE THREAD

**Issue by jbveepee** [lovell/sharp#2345]
I'm trying to add gaussian noise an image but can't find the function in sharp.js.
It exists in libvips, but can it also be added to / accessed from sharp.js?

I'm pretty new here and still finding my way, so please do redirect me if needed. Thanks in advance!

**Comment by lovell** [comment]
Hi, did you see #725 ?

**Comment by jbveepee** [comment]
Hi Mr. Lovell, thanks for your reply. Would it be better to reply on 725?
Again, new to git... Apologies if this is bad form.

I came across 725 Thursday but did not know what to do with the information. At this point I'm only trying to get conclusive information on whether it is currently possible. 725 states a dependency on #470. (Resolved since 01/04/2017) and is marked as an enhancement mentioning it needs exposing from libvips.

If it's not possible yet, I'm happy to try and contribute though I do not know C... Willing to give it a good old try though. :-)

All the best!

**Comment by lovell** [comment]
#725 is a future possible enhancement. PRs are always welcome If you're able to help.

I'll close this issue - let's continue to track this at #725.
