### ISSUE TITLE
AVIF image format

### ISSUE THREAD

**Issue by AndreiIgna** [lovell/sharp#2346]
After reading these articles
- https://reachlightspeed.com/blog/using-the-new-high-performance-avif-image-format-on-the-web-today/
- https://netflixtechblog.com/avif-for-next-generation-image-coding-b1d75675fe4
looks like AVIF image format has a lot of advantages and should start looking into how to implement it in dev projects.

As I use Sharp in a few projects, I checked if the format is already supported, but doing a search in this repo for "avif" I see there's only a note for it in this page https://sharp.pixelplumbing.com/api-output#heif

AVIF format support is added in Google Chrome, Firefox and a few other tools. Is this planned to be added in Sharp? Only want to start a discussion and see how this could be done.

Cheers

**Comment by lovell** [comment]
Please see #2289

**Comment by AndreiIgna** [comment]
Thanks, I'll close this.

That ticket was closed earlier today, and haven't seen it. Probably a good idea to keep it open so it's visible if someone else is looking for same thing.

Also thanks for building and maintaining this library 😀
