### ISSUE TITLE
Gif image resizing does not work as expected

### ISSUE THREAD

**Issue by xdays** [lovell/sharp#2347]
The original gif is: 

![](https://i.stack.imgur.com/DMQDi.gif)

But what I get is:

![](https://iili.io/dsdiIn.gif)

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

```
root@24d4f802e1f7:/tmp# vips -v
vips-8.10.0-Sat Jul 18 13:45:47 UTC 2020
root@24d4f802e1f7:/tmp# npm ls sharp
demo@1.0.0 /tmp
`-- sharp@0.26.0
```

What are the steps to reproduce?

```
const sharp = require('sharp');

sharp('t.gif', {
  animated: true
}).resize(160).toFile('o.gif', (err, info) => {
  console.log(err, info)
});
```

and I can resize with pyvips, so I'm sure libvips works:

```
import pyvips
thumb = pyvips.Image.thumbnail("t.gif[n=-1]", 160)
thumb.write_to_file("x.gif")
```

What is the output of running `npx envinfo --binaries --system`?

```
npx: installed 1 in 3.094s

  System:
    OS: Linux 4.19 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (4) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 6.01 GB / 7.78 GB
    Container: Yes
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
```

**Comment by lovell** [comment]
Hi, you'll need to manually set `pageHeight` - see https://sharp.pixelplumbing.com/api-output#gif

There's a future possible enhancement at #2275 to make this easier.

**Comment by xdays** [comment]
Thanks @lovell , it works now.
