### ISSUE TITLE
 Circular border on avatar photo

### ISSUE THREAD

**Issue by nastari** [lovell/sharp#2349]
I took the hook in this case -> "https://github.com/lovell/sharp/issues/1555". Does anyone with more experience know if it is possible to make a circular border around the image?

example: https://unilink.us/content/border/14.png

**Comment by nastari** [comment]
I understand that sharp should read a function instead of static values ​​like the one in the previous issue. So I don't know if is possible.

**Comment by nastari** [comment]
something like that: 


sharp('image.jpg').metadata().then(meta => {
  
  sharp('image.jpg')
  .extract({
    left: 1, 
    top: 1, 
    width: meta.width - 2,   
    height: meta.height - 2    
  })
  .extend({
    top: 0,
    bottom: 0,
    left: Math.PI * (something), <--- something like that, Math.PI is not working here, i dont know why too
    right: Math.PI * (something),
    background: "#fff"
  }) 
  .toBuffer()
  .then(data => sharp(data)
    .toFile('out.jpg')
  );

})

**Comment by lovell** [comment]
The readme has an example of adding rounded corners to an image by compositing an SVG over it.

https://github.com/lovell/sharp#stream

**Comment by nastari** [comment]
Ohhh!!! Awesome, sorry for the issue soo! xD
