### ISSUE TITLE
What is the impact of v0.26.0?

### ISSUE THREAD

**Issue by nukeop** [lovell/sharp#2353]
**What are you trying to achieve?**
I'm trying to bundle sharp for an electron application.

**Have you searched for similar questions?**
Yes

**Are you able to provide a minimal, standalone code sample that demonstrates this question?**
N/A

**Are you able to provide a sample image that helps explain the question?**
N/A

I have a program that uses sharp: https://github.com/nukeop/nuclear

Now I would like to bundle it with webpack and package correctly for all 3 platforms. I had some luck on Windows by using 
``` 
externals: {
      'sharp': 'commonjs sharp'
    },
```

in webpack, however this trick doesn't seem to be working on Linux. Using electron-builder, I'm building several versions, including snap, Appimage, and flatpak, as well as an unpacked version. In each of them, I am missing libvips and/or sharp. Is there a best practice way of bundling sharp with webpack?

It also looks like the new version affects the way I can bundle it, and it won't be found on Linux after it's packaged.

**Comment by lovell** [comment]
Does this question relate to something that worked prior to v0.26.0? A standalone repo with dependencies and build scripts that demonstrates the problem would be very helpful.

In terms of webpack config, including `sharp` in `externals` is likely to be the best approach regardless of platform.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
