### ISSUE TITLE
Can sharp beveled, perspective, deformed?

### ISSUE THREAD

**Issue by banli17** [lovell/sharp#2354]
![image](https://user-images.githubusercontent.com/12556069/92297261-0eafcf80-ef70-11ea-86b9-2f8a3675d103.png)

![image](https://user-images.githubusercontent.com/12556069/92297262-13748380-ef70-11ea-97ce-9adbe3fefce3.png)

I did not find such an api

**Comment by lovell** [comment]
Please see #2095
