### ISSUE TITLE
Output tile: centre

### ISSUE THREAD

**Issue by beig** [lovell/sharp#2357]
Hello,

how can I set the option to center the output tile as explained in the libvips docs?

https://libvips.github.io/libvips/API/current/Making-image-pyramids.md.html

https://sharp.pixelplumbing.com/api-output#tile Doesn't mention such an option.

**Comment by lovell** [comment]
The `centre` boolean property (defaulting to `false`) is not yet exposed via sharp. Happy to accept a PR to do so, if you're able.

(If possible, I'd prefer this to be exposed as both `centre` and `center`.)

**Comment by beig** [comment]
I'm trying to work on implementing the enhancement, but I have some trouble figuring out why libvips doesn't get called with the centre option.

Could you take a quick look @lovell ?

Much appreciated

https://github.com/beig/sharp/commit/b753e5b5b0c904f62844849bff1a5325d3a5ab21

**Comment by lovell** [comment]
@beig Thank you, I think you'll need to set `baton->centre` approximately [here](https://github.com/lovell/sharp/blob/master/src/pipeline.cc#L1406).

**Comment by beig** [comment]
@lovell I used this PR as a template -> https://github.com/lovell/sharp/pull/1342/commits/df2057d461bea4ec061e2c1ee6d1e15c747c2b4c

Setting `->set("centre", true)` does work tho

**Comment by beig** [comment]
Now I see it and it's working! Thank you!

Any idea how I can unit test if the image is centered?

**Comment by lovell** [comment]
v0.26.2 now available, thank you for the PR!
