### ISSUE TITLE
Setting "density" option (image DPI) not respected with PNG files

### ISSUE THREAD

**Issue by tjramage** [lovell/sharp#2358]
Version: `0.25.4`

**What are the steps to reproduce?**

Create a new PNG image (using the `composite([...])` API. Save output buffer to a file and check image metadata / image DPI. It is always set to 25 pixels/inch.

**What is the expected behaviour?**

The final image should have its image DPI (resolution) set to `144` (or whatever density is provided in the constructor options)..

**Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?**

```
const png = await sharp({
    create: {
      width: 5120,
      height: 2880,
      channels: 3,
      background: { r: 255, g: 255, b: 255 }
    },
    density: 144,
    limitInputPixels: false
  })
    .composite(images)
    .png()
    .flatten()
    .toBuffer()
```

**Are you able to provide a sample image that helps explain the problem?**

Yep. Below image is a composite of multiple "slices", stitched together. The resulting DPI is 25. This is meant to be a retina image and therefore its optimal viewing resolution should be at 50% of its actual size... If I could set the DPI to 144, applications like Preview (on macOS) will open the image at the correct setting.

![Test Image Export (2020-09-08 16-25-25)](https://user-images.githubusercontent.com/5517057/92503071-9e67af00-f1f8-11ea-80dc-75416b11d05d.png)

<img width="366" alt="Image Metadata" src="https://user-images.githubusercontent.com/5517057/92503252-e4247780-f1f8-11ea-974e-b0f72841ae2f.png">

**What is the output of running `npx envinfo --binaries --system`?**

Running within an AWS Lambda environment, so this is tricky to find out... Sorry!

**Comment by lovell** [comment]
Hi, did you see #967 ?

**Comment by tjramage** [comment]
@lovell — Thanks for the quick reply! I did do some initial digging into this but saw most of the discussion was for JPEGs... As I'm working with PNGs, which definitely support DPI metadata, is this possible to do with Sharp?

I'm not sure I am following the outcome of the discussion in #967. Do I need to find an alternative solution to modify the EXIF data of my PNG buffer?

**Comment by lovell** [comment]
I added PNG to the title of #967 as it should solve the problem for both. I'll close this issue - please subscribe to #967 for updates, or even better if you're able, a PR would be very welcome.
