### ISSUE TITLE
DNG support

### ISSUE THREAD

**Issue by thany** [lovell/sharp#2359]
What are you trying to achieve?
Reading DNG images. They are a pretty common lossless format in the world of semipro photography. They are produced by many point-and-shoot cameras, and some phones, as well as a handful of pro and semipro system cameras.

Writing DNG images isn't really important, as far as I'm concerned, so let's stick with reading only, at least for now.

Have you searched for similar feature requests?
Yeah, "DNG" as a search term yields absolutely nothing (at least it did, before I created this FR 😀).

What would you expect the API to look like?
Exactly the same as reading any other picture, I suppose?

What alternatives have you considered?
Any alternative DNG reader will do, in theory. But of course, it adds complexity, and an additional dependency. And I suspect sharp could do it a lot faster, as it can with other readable image formats.

Is there a sample image that helps explain?
Not really from me, but many cameras and some phones can shoot DNG pictures. So, examples are [easy to find](https://duckduckgo.com/?q=sample+dng+pictures&t=ffab&ia=web). On top of that, I don't really know the requirements for good sample pictures.

**Comment by lovell** [comment]
Hi, a globally-installed libvips compiled with support for ImageMagick or GraphicsMagick should allow you to read DNG files.

https://sharp.pixelplumbing.com/install#custom-libvips

You'll need to re-install sharp so it links itself against the global libvips after doing so.

https://sharp.pixelplumbing.com/install#building-from-source

**Comment by thany** [comment]
Thank you. I would consider that a workaround though. It's not ideal to add another dependency, and it's even less ideal to add a dependency that has to be installed globally *before* installing sharp.

I'm building an application and I really don't want in the installation instructions anything more than "npm i [my application name]` if I can help it. Anything that has to be installed globally, can (and will) eventually break for some odd reason, and because sharp is hard-linked to it, it might stop working alltogether.

Since I can't control what my (future) users are running, I feel I shouldn't instruct them to install any kind of custom builds or global installations of anything. I want my application to be able to either say "supports DNG", or not. The only waterproof way to do this, would be to fully depend on Docker, which is (more or less) Linux-only.

**Comment by lovell** [comment]
The prebuilt libvips binaries provided by sharp are highly unlikely to add *magick as a dependency and therefore won't be able to support DNG input.

The scripts that build them are open source, so you're free to modify, adapt and extend the libraries they contain via https://github.com/lovell/sharp-libvips/ and publish your own binaries.

**Comment by thany** [comment]
I get that, but I wasn't asking for *magick support in the libvips binaries. I was asking for native support.

Building a custom libvips binary is a no-go, as any `npm i sharp` will not magically use my build. Besides, I don't have any C++ skills.

**Comment by lovell** [comment]
sharp is probably the wrong solution to your problem, sorry.

**Comment by thany** [comment]
Alright, fair enough. I do use sharp for other image processing though, but I think a parser for another file format, if it spews out a raw array of pixels, can be fed into sharp for further processing. I'll have to figure that out on my own.

Thanks for the followups anyway. Keep up the good work 😎

**Comment by dmitrizzle** [comment]
@lovell I don't mind installing ImageMagick, will that enable me to write into DNG?
