### ISSUE TITLE
Show meaningful error message on missing file

### ISSUE THREAD

**Issue by JoaquimLey** [lovell/sharp#2360]
What are you trying to achieve?
I have the following sequence using sharp
```js
const result = await sharp(inputBuffer)
        .resize(460)
        .composite([{ input: watermark, gravity: 'center' }])
        .toFormat('webp', { quality: 90 })
        .toBuffer();
```
Everything should work as expected, the issue is:
- I've actually moved the current file where this processing takes place, therefore the `watermark` input file has a different path.
- One could argue I should use fully qualified paths but the issue I have is with the error message

```
Error: Input file is missing
```

I Found it super strange as this used to work just fine, but outputting this generic error got me through a google+stackoverflow+this-repo-issues rabbit hole thinking it was actually an issue with the `inputBuffer`.

### Suggestion

A better output would be 
```
Error: Could not <composite|process|etc> Input file at <provided path> is missing
```

**Comment by lovell** [comment]
Hi, thanks for the suggestion.

The error message originates from:

https://github.com/lovell/sharp/blob/76dcddfa3d6042b6a23239cf0e139ce93bf53ab5/src/common.cc#L334

The `InputDescriptor` passed to the `OpenInput` function would need some form of (string?) context to be able to add more details to this error message.

Happy to accept a PR if you're able.

**Comment by Brodan** [comment]
Seconding the need for this. I'm currently using sharp to composite 20+ layers of images so it's a massive pain to figure out which input file is missing when this error message doesn't tell me. 

I've not written almost any cpp code but I could take a crack at a PR. It seemed like it would be any easy fix but the response above leads me to believe that it actually isn't. I'll see what I can do.

**Comment by lovell** [comment]
v0.30.4 now available, thanks for the PR.
