### ISSUE TITLE
Segmentation fault (core dumped) with latest vips and libheif encoded with rave1

### ISSUE THREAD

**Issue by navanshu** [lovell/sharp#2361]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
0.26.0
What are the steps to reproduce?
Previously I was using an older version of libvips with libheif compiled with libaom. Now I replaced libaom with rave1. Heif-enc and Heif-convert are working properly
libvips config
native win32: no
native OS X: no
open files in binary mode: no
enable debug: no
enable deprecated library components: yes
enable docs with gtkdoc: no
gobject introspection: no
enable radiance support: yes
enable analyze support: yes
enable PPM support: yes
generate C++ docs: no
use fftw3 for FFT: yes
Magick package: MagickCore
Magick API version: magick7
load with libMagick: yes
save with libMagick: yes
accelerate loops with orc: yes
ICC profile support with lcms: yes (lcms2)
file import with niftiio: no
file import with libheif: yes
file import with OpenEXR: no
file import with OpenSlide: no
file import with matio: no
PDF import with PDFium: no
PDF import with poppler-glib: yes
SVG import with librsvg-2.0: yes
zlib: yes
file import with cfitsio: no
file import/export with libwebp: yes
text rendering with pangoft2: yes
file import/export with libspng: no
file import/export with libpng: yes (pkg-config libpng >= 1.2.9)
support 8bpp PNG quantisation: yes
file import/export with libtiff: yes (pkg-config libtiff-4)
file import/export with giflib: yes (found by search)
file import/export with libjpeg: yes (pkg-config)
image pyramid export: no
use libexif to load/save JPEG metadata: yes

What is the expected behaviour?
Sharp is not converting images and rather prints -- > Segmentation fault (core dumped).
I am not able to trace this error

What is the output of running ``?
npx: installed 1 in 1.615s

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 3.77 GB / 15.48 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.9.0 - ~/.nvm/versions/node/v14.9.0/bin/node
    npm: 6.14.8 - ~/.nvm/versions/node/v14.9.0/bin/npm
Tried it with latest node too. Doesn't seems like a node problem.

**Comment by lovell** [comment]
Hi, you're at the bleeding edge's bleeding edge here.

Please can you provide a Dockerfile or similar to allow someone else to recreate the exact environment as well as sample input images and code.

Please also heed the "Do not use this in production systems" warning at https://sharp.pixelplumbing.com/api-output#heif

**Comment by lovell** [comment]
I'm unsure how you've managed to compile libvips with support for libheif+rav1e as none of the pkgconfig config to detect this has been set up, so this is unlikely to be caused by the thing you think it's been caused by.

I've opened https://github.com/strukturag/libheif/pull/327 to expose `builtin_rav1e_encoder`, which will then require a change to libvips to detect.
