### ISSUE TITLE
Sharp ignores dominant-baseline when converting SVG to PNG

### ISSUE THREAD

**Issue by jordinl83** [lovell/sharp#2364]
Using sharp version `0.26` but it happens in older versions too.

The [dominant-baseline](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dominant-baseline) attribute is used to align text vertically on SVGs. 

When converting an SVG to a PNG, Sharp ignores `dominant-baseline`. See table below for an example of an actual SVG with different values for `dominant-baseline` and on the right side the resulting converted PNG.

| SVG | PNG |
| --- | --- |
| <img src="https://raw.githubusercontent.com/jordinl83/sharp-bug/f87abe2acade3fdba49a30223c6527c7e1b60272/dominant-baseline.svg" width="400" alt="SVG" /> |  <img src="https://raw.githubusercontent.com/jordinl83/sharp-bug/f87abe2acade3fdba49a30223c6527c7e1b60272/dominant-baseline.png" width="400" alt="PNG" />|

I've created a [repo](https://github.com/jordinl83/sharp-bug) that includes a [sample SVG](https://github.com/jordinl83/sharp-bug/blob/master/dominant-baseline.svg) and the [script](https://github.com/jordinl83/sharp-bug/blob/master/svg-to-png.js) used to convert the SVG to a PNG.

**Comment by lovell** [comment]
Hi, did you see #1996 ?

**Comment by jordinl83** [comment]
@lovell ah! I missed that one sorry.
