### ISSUE TITLE
Installing vips dependencies on 'npm install sharp'

### ISSUE THREAD

**Issue by ozkanonur** [lovell/sharp#2367]
If I'm not mistaken, the necessary vips dependencies are also installed in the background when installing sharp. How is this happening? I'm going to write a sharp like library for another language, but I have no idea how I should install the vips requirements on package installation. Any tips would be so great.

**Comment by lovell** [comment]
Did you see https://github.com/lovell/sharp-libvips ?

**Comment by ozkanonur** [comment]
No, thanks for that. And just saw this https://sharp.pixelplumbing.com/install#custom-prebuilt-binaries documentation now. Thanks for the quick response. @lovell
