### ISSUE TITLE
Specifying pages option on constructor gives an error when used as WritableStream

### ISSUE THREAD

**Issue by AcrylicShrimp** [lovell/sharp#2368]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`? **_YES(`0.26.0`)_**

What are the steps to reproduce? **_Run below code with `ts-node`_**

```js
import fs from 'fs';
import sharp from 'sharp';

(async () => {
	const transform = fs
		.createReadStream('test.gif')
		.pipe(sharp({ pages: -1 /* Here, pages: 1 will give a same result */ }).rotate());
        // This line will cause an error: Unexpected data on Writable Stream
	await transform.withMetadata().webp({ lossless: true }).toFile('test.webp');
})();
```

What is the expected behaviour? **_Writes a animated `test.webp` file without any issue._**

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem? **_See above_**

Are you able to provide a sample image that helps explain the problem? **_See below_**

<img width="1200" alt="Screenshot 2020-09-15 AM 1 23 13" src="https://user-images.githubusercontent.com/19178575/93111764-08e58700-f6f2-11ea-8e9c-72685cc27355.png">

What is the output of running `npx envinfo --binaries --system`?

```text
  System:
    OS: macOS 11.0
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 11.27 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.9.0 - ~/.nvm/versions/node/v14.9.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.9.0/bin/npm
```

**Comment by lovell** [comment]
Hi, this is the same problem as reported at #2362

**Comment by AcrylicShrimp** [comment]
Thank you for quick response, Ill check that.

**Comment by lovell** [comment]
Thanks, let's continue to track this in #2362
