### ISSUE TITLE
Creating cmyk tiff results in solid black apha channel

### ISSUE THREAD

**Issue by Fensterbank** [lovell/sharp#2371]
**Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?**
Yes, 0.26.0

**What are the steps to reproduce?**
Having an SVG file as input, creating a TIFF with cmyk colourspace.
The resulting TIFF has a complete black background.
I tried different variations, e.g. `removeAlpha()` before `toColourspace('cmyk')` and adding it again later.
If I only use `removeAlpha()`, I will get a 4 channel TIFF, which looks the same, so maybe it has something to do with the colourspace conversion.

![grafik](https://user-images.githubusercontent.com/1684826/93345796-8664e080-f833-11ea-8a3c-7ed5cd2f0d86.png)

While Photoshop can work with this file and the background looks transparent there, most image viewer and also Adobe InDesign will show the alpha channel as solid black.

**What is the expected behaviour?**
It should look like the TIFF without CMYK-Conversion.
So the same image without cmyk colourspace and icc profile will result in an RGB image like that:
![grafik](https://user-images.githubusercontent.com/1684826/93345929-b0b69e00-f833-11ea-9aa5-4c62a63849f8.png)

**Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?**
```javascript
const img = sharp('image.svg')
        .toColourspace('cmyk')
        .withMetadata({
          profile: './src/lib/generator/CoatedFOGRA39.icc',
        })
        .tiff({
          compression: 'lzw',
        });
```

Are you able to provide a sample image that helps explain the problem?

What is the output of running `npx envinfo --binaries --system`?
```
 System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 2.36 GB / 15.30 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.10.0/bin/npm
```

**Comment by lovell** [comment]
I notice you posted this question on StackOverflow but using ImageMagick to demonstrate the problem so I suspect this may be a limitation of InDesign.

https://stackoverflow.com/questions/63935576/converting-image-with-transparency-to-cmyk-tiff-results-in-solid-black-alpha-cha

I tried the example code above and it produced a 5 channel CMYKA image, the 5th channel of which appeared to have the correct values for transparency.

**Comment by Fensterbank** [comment]
Yes. Good point. Since I could reproduce this with ImageMagick too I don't think this has something to do with sharp at all and I think I can close this issue as invalid.
I still use the code above in the productive product and we did not hear any complaints about the CMYK image, so I assume there isn't really an issue and if professional graphic people are opening the CMYK image in their professional programs it probably works as expected. 🤷‍♂️
Thanks anyway for answering here.
