### ISSUE TITLE
Input image exceeds pixel limit

### ISSUE THREAD

**Issue by mlh-luanvvt** [lovell/sharp#2373]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

=> I'm using sharp@0.26.0. It's the latest version.

What are the steps to reproduce?

=> When I passed buffer of image (18MB - 30000 × 19043 pixels), I encountered the following problem.
```
[Error: Input image exceeds pixel limit]
```

What is the expected behaviour?
=> No error
I found this issue https://github.com/lovell/sharp/issues/1381. But I could not find any option like `limitInputPixels`.

What is the output of running `npx envinfo --binaries --system`?
=> I'm running on Lambda with memory 2048 MB

**Comment by lovell** [comment]
Hi, did you see the `limitInputPixels` property of the constructor?

https://sharp.pixelplumbing.com/api-constructor

```js
sharp(input, { limitInputPixels: ... })...
```

**Comment by mlh-luanvvt** [comment]
@lovell 
Thank you very much!
I tried that option. It worked perfectly.

**Comment by HTBernard** [comment]
Hello, I encounter a similar issue enven with `limitedInputPixels: false` activated. only happening when I `composite()` with an other image (base image is 15000x30000)
```js
const imgBytes = fs.readFileSync(fileData.file);
let img = sharp(imgBytes, {limitInputPixels:false,unlimited:true});

let finalHeight;
//Resize the image
if(fileData.size === "")
	finalHeight = (await img.metadata()).height;
else
	finalHeight = Number.parseInt(fileData.size);

//Add overlay logo
let imgLogo = getLogo();
if(imgLogo) {
	console.log("Adding overlay")
	imgLogo = await sharp(imgLogo, {limitInputPixels:false,unlimited:true})
							.resize(2*finalHeight, finalHeight, {fit:'inside', position:'bottom'})
							.toBuffer();
}

//Write image
console.log("Converting input with options to the final format")
const convertedImgBytes = await (imgLogo ? 
		img
			.resize(2*finalHeight, finalHeight, {fit: 'fill'})
			.composite([{ input: imgLogo, gravity: "southeast" }])
			.jpeg()
			.toBuffer() //Input image exceeds pixel limit
		:
		img
			.resize(2*finalHeight, finalHeight, {fit: 'fill'})
			.jpeg()
			.toBuffer()); //Here is fine
```

Any idea where this can come from ? Thanks !

**Comment by HTBernard** [comment]
Answer to my own question after a few more research : composite also takes a parameter "limitInputPixels" that must be set to false in this case
```js
const convertedImgBytes = await (imgLogo ? 
	img
		.resize(2*finalHeight, finalHeight, {fit: 'fill'})
		.composite([{ input: imgLogo, limitInputPixels:false}])
		.jpeg({quality:fileData.quality})
		.toBuffer()
	:
	img
		.resize(2*finalHeight, finalHeight, {fit: 'fill'})
		.jpeg({quality:fileData.quality})
		.toBuffer()
);
```
