### ISSUE TITLE
Trying to open PNG: Error: Input buffer contains unsupported image format

### ISSUE THREAD

**Issue by patrickjane** [lovell/sharp#2374]
### Version

`npm view sharp dist-tags.latest`:  0.26.0

### What are the steps to reproduce?

```
      sharp('/Users/s710/test.png')
      .toBuffer()
      .then((res) => {
         setImmediate(() => cb(null, { success: true, binaryResult: res }));
      })
      .catch((err) => setImmediate(() => {
         log.error(self, 'Failed to process image (' + err + ')');
         cb(500);
      }));
```

Prints: `Failed to process image (Error: Input file contains unsupported image format)`

### What is the expected behaviour?

Should return a buffer containing the PNG image.

It *does* work fine if I change the first line to `sharp('/Users/s710/test.jpg')` (that is, open a JPG file instead of a PNG file).

### Sysinfo

```
$ npx envinfo --binaries --system
npx: Installierte 1 in 2.048s

  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7287U CPU @ 3.30GHz
    Memory: 192.05 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
```

**Comment by lovell** [comment]
What is the output of running `node -p "require('sharp').format.png"`? Please can you provide the PNG file that fails in this manner?
