### ISSUE TITLE
gif generated size is too large

### ISSUE THREAD

**Issue by banli17** [lovell/sharp#2376]
I made a gif animation from the picture below，this jpg is only 380kb , but the result gif is too big, 1.2M, but I see others only 400kB, I use the compression tool imagemin to compress, even colors 24 still has 560kb, and it is better than others' The picture is sharper. colors 64 is good, but there are 850Kb.

```
sharp('./2.jpg').gif({
  loop: 0,
  pageHeight: 240,
  delay: [
    150, 150, 150, 150, 150,
    150, 150, 150, 150, 150,
    150, 150, 150, 150, 150,
    150, 150, 150, 150, 150,
    150, 150, 150, 150, 150,
    150, 150, 150, 150, 150,
    150, 150, 150, 150, 150,
    150
  ],
}).toFile('./x.gif')
```

**Comment by lovell** [comment]
Thanks for the report, I've added commit 6c5cde3 to ensure sharp takes advantage of existing GIF optimisation features of libvips+magick.

**Comment by lovell** [comment]
v0.26.1 is now available with this change.

**Comment by banli17** [comment]
@lovell  It doesn't seem to work. After I installed sharp 0.26.1, it is still that big

**Comment by adityapatadia** [comment]
Is there any more work pending here? We currently see output is not optimised.
