### ISSUE TITLE
Enabling HEIF/HEIC support on Windows

### ISSUE THREAD

**Issue by dpolivy** [lovell/sharp#2377]
*What are you trying to achieve?* I'd like support for HEIC source files in my Windows-based sharp image pipeline.

*Have you searched for similar questions?* Yes. I see HEIF/HEIC is supported from #1105 with a custom/global `libvips`. However, I also see that global `libvips` are not supported on Windows. I did also review #1938.

I'm wondering if anyone has solved this problem and has a workflow they can share for how to get this to work on Windows?

Additionally, I don't like modifying the directory structure/code of an installed node module. Is there any consideration for providing a way to pass `sharp` a path to a `libvips` build tarball which it can then install, to make this cleaner? Or to allow some sort of global libvips approximation on Windows?

*Are you able to provide a minimal, standalone code sample that demonstrates this question?* Not yet.

*Are you able to provide a sample image that helps explain the question?* Not yet.

**Comment by lovell** [comment]
You *might* be able to place the DLLs from the `vips-dev-w64-all-8.10.0.zip` file at https://github.com/libvips/build-win64-mxe/releases/tag/v8.10.0 into the `node_modules/sharp/build/Release` directory, overiding the files that were placed that at `npm install` time.

The same zip file contains the `vips` command line tool, which might be more appropriate if you have to use Windows.

Please note that the "all" zip file contains GPL-licenced libraries so *your* code must conform to the GPL when you use it.

**Comment by dpolivy** [comment]
Thanks, that's certainly easier than building myself. However, as you point out, the GPL license may be an issue. This is for a proprietary node.js web service, but it runs on a public cloud, so seems like we may not want to incorporate any GPL code since we don't own the hardware.

I do see you're pushing for libheif and aom to be added to the web build. In order to support iOS HEIC files, is it just libde256 that's missing? Or is x265 (GPL) required (and why this won't get incorporated in by default)? I'm wondering if I can fork the repo to customize the web build to include those extra modules.

**Comment by lovell** [comment]
The prebuilt binaries provided by sharp will not include an HEVC decoder or encoder whilst it is patent encumbered.

**Comment by lovell** [comment]
Please note that HEVC-related dependencies will no longer be included in the Windows "all" zip file as of the next releasetoo. This means you'll have to compile these binaries yourself (and therefore take on the patent risk yourself) - see https://github.com/libvips/build-win64-mxe/pull/14

**Comment by zczcyc0201** [comment]
> You _might_ be able to place the DLLs from the `vips-dev-w64-all-8.10.0.zip` file at https://github.com/libvips/build-win64-mxe/releases/tag/v8.10.0 into the `node_modules/sharp/build/Release` directory, overiding the files that were placed there at `npm install` time.
> 
> The same zip file contains the `vips` command line tool, which might be more appropriate if you have to use Windows.
> 
> Please note that the "all" zip file contains GPL-licenced libraries so _your_ code must conform to the GPL when you use it.

Hi, after overrideing DLLs into the `node_modules/sharp/build/Release` , I got error like

sharp-win32-x64.no is not a valid Win32 application

do you know how to fix it?thanks

**Comment by zczcyc0201** [comment]
> You _might_ be able to place the DLLs from the `vips-dev-w64-all-8.10.0.zip` file at https://github.com/libvips/build-win64-mxe/releases/tag/v8.10.0 into the `node_modules/sharp/build/Release` directory, overiding the files that were placed there at `npm install` time.
> 
> The same zip file contains the `vips` command line tool, which might be more appropriate if you have to use Windows.
> 
> Please note that the "all" zip file contains GPL-licenced libraries so _your_ code must conform to the GPL when you use it.

Hello,after I do this,I got a error:
The specified procedure could not be found.
\\?\D:\xxx\node_modules\sharp\buiild\Release\sharp-win32-x64.node

I copied all Dlls from vips-dev-w64-all-8.10.0.zip/bin to node_modules\sharp\buiild\Release\ then I got error

**Comment by zczcyc0201** [comment]
> Hello,after I do this,I got a error: The specified procedure could not be found. \?\D:\xxx\node_modules\sharp\buiild\Release\sharp-win32-x64.node
> 
> I copied all Dlls from vips-dev-w64-all-8.10.0.zip/bin to node_modules\sharp\buiild\Release\ then I got error There is no 'canvas' in my project.
> 
> If use vips-dev-w64-all-8.12.2 ,It works, but there is no 'hevc' supports in it, I tried complie from source in windows, but failed
> 
> If you are convenient， could you send me a vips-dev-w64-all-8.12.2 with hevc/heif dlls
> 
> thank you very much
> 
> my email is '[zczcyc0201@gmail.com](mailto:zczcyc0201@gmail.com)'
