### ISSUE TITLE
Pseudo error: Image to composite must have same dimensions or smaller.

### ISSUE THREAD

**Issue by infacto** [lovell/sharp#2378]
The operation `composite` should allow greater images than the source image.
It should use the source image dimensions.

For example: 

```js
appIcon = appIcon.composite([{ input: badge }]);
```

Btw.: The badge is a svg of square 1024px. The app icon too. Same size and I get the error:
`Error: Image to composite must have same dimensions or smaller`
But regardless of this "bug" it should just do the job using the appIcon dimensions.

Background: I have an app icon and want to overlay a badge image. In this case a svg with transparent background.

I use `Buffer.from('<svg>...</svg>')` to create the image. And general it works with other operations.
If I resize it using `sharp(theBuffer).resize(1024, 1024).toBuffer()` the `composite` throws an error: 
`Unsupported input object.` 🤔 Weird... (both are buffers)

Using `sharp(theBuffer).png()` throws:
`Expected width, height and channels for raw pixel input`

I have no idea how to achieve the overlay composite operation.
`sharp(input).composite([{ input: mask, blend: 'dest-in' }])` works. (another image with rounded corners.)

Version: `0.23.4` (because Node 10.x)

Maybe this issue should get the label "bug", because both images has the same size of 1024 x 1024 px and it throws: `Image to composite must have same dimensions or smaller`

`sharp(badge).toFile('test.png');` Creates a file with 1024x1024px. Same format like the app icon. But it does not work.

**Comment by chrisdeely** [comment]
Can you post a bit more of your sample code? It may be easier to diagnose in context. I just had a similar issue with the `Unsupported input object.` error and found that I was passing a `sharp` object instead of a `Buffer`.

I am having a potentially similar issue with `composite()` as I want to overlay a small image on top of a larger background, but want to use a blur mode which will keep the overlay pixels intact. I attempted to use `source` which seems like it should work, but it actually removes all of the background image's pixels because the overlay image does not contain any data at those locations.

**Comment by lovell** [comment]
The most recent v0.26.1 of sharp supports Node.js 10 - please upgrade.

If you're still having problems please provide complete, standalone code and input images that might allow someone else to reproduce this.

**Comment by infacto** [comment]
Ok, I installed the version `0.26.1` now, with the same problem. (Node `10.22.0`)
I also decreased the overlay image to 420x420px for the 1024 x 1024 px source image.

> Error: Image to composite must have same dimensions or smaller

I created a demo, but I cannot reproduce the bug there. Weird, because it's the same, except for the unrelated environment. 😞 Same images, same node version, same sharp version, same code. I also worked with sharp with such files before. I like it. But this bug is really annoying. I've wasted hours. ... I already reinstalled the node_modules. ... I continue the debugging and post the result here.

Short background at this moment. (Uploading demo project planned...)

- App icon with size 1024 x 1024 px PNG.
- Badge overlay 420 x 420 px (also tested with 1024 x 1024 px) transparent background. SVG

Sharp command:

```js
icon.composite([{ input: badge, top: 0, left: 0, blend: 'over' }])
```

It works in the demo project, but not in my productive project. The error is just a lie.
I also cropped the SVG. Because the elements (e.g. path) was overflow the viewport. This should not and was not the problem. ... I'm not allowed to upload the affected project. And the demo project - with the same code and images - does not have the bug. I going insane. 😭 ^^ ... debugging in progress.

**Comment by infacto** [comment]
Ok 😓 I found the problem. It was the chained methods of sharp to resize the image. This is weird, because I thought that the resize after composite does not affect to the composite operation. My solution is to convert it to buffer between composite and resize.

**does not work**

```js
const badge = createBadge();
let icon = sharp('./icon.png');
icon = icon.composite([{ input: badge, top: 0, left: 0, blend: 'over' }]);
icon = icon.resize(200, 200);
icon.png().toFile('./result.png');
```

Because the resize only affect to the source image. The composite seems to be completed after the resize. You can see it if you resize it with a size of greater that the badge. e.g. resize it to 512 px. You see that the badge is not resized.

**this works**

```js
const badge = createBadge();
let icon = await sharp('./icon.png').toBuffer();
icon = await sharp(icon).composite([{ input: badge, top: 0, left: 0, blend: 'over' }]).toBuffer();
icon = await sharp(icon).resize(200, 200).toBuffer();
sharp(icon).png().toFile('./result.png');
```

Use `toBuffer` to snapshot the state.
Why not chained directly? Because if-conditions.

Again: The resize after composite resizes the source image (icon) only. And the composite is executed after that. In this case, the resize method changed the size of the source image to 200px and executes the composite with the badge of 420px.
Note that `toBuffer` is async. I think this is the reason for sharp to behave like that. But I'm sure someone else can explain this better. Anyway... It works now. It's great that sharp can use svg and composite for dynamic auto-generated stuff. ❤️

**Comment by grdnkln** [comment]
I've been struggling with this for days. Thank you for your insight and letting me finally solve the issue.

I was trying to create a dynamic "compass" with a red arrow overlayed ontop using code like the below:

`        // Generate a compass graphic
        newimage = await sharp(imgdir + '/sprites/compass.png')
            .flatten()
            .composite([{input: imgdir + '/sprites/redarrow.png'}])
            .resize(icon_size, icon_size)
            .raw()
            .toBuffer()
`

And I was constantly getting the "Image to composite must have same dimensions or smaller", even though the 'redarrow.png' file was definitely smaller than 'compass.png'. Like you I was assuming that doing a resize() after the composite() wouldn't affect anything.

Changed my code to the following and it works fine:

`        // Generate the compass graphic
        compass2 = await sharp(imgdir + '/sprites/compass.png')
            .composite([{input: imgdir + '/sprites/redarrow.png'}])
            .toBuffer()

       newimage = await sharp(compass2)
            .flatten()
            .resize(icon_size, icon_size)
            .raw()
            .toBuffer()
`

I don't understand why this is the case, it seems like a bug to me.

**Comment by jeanbmar** [comment]
@lovell the issue was probably closed too fast by the author.  
Calling `composite(...).resize(...).png()` (and possibly other methods considering @grdnkln example) will trigger an error if the post-composite image size is smaller than the composite input image size.

**Comment by lovell** [comment]
You'll need to use two pipelines when resizing and compositing.

**Comment by june07** [comment]
> You'll need to use two pipelines when resizing and compositing.

Just ran into this myself.  Great project by the way... thanks.  Is that documented somewhere and I just missed it?

**Comment by foaudkajj** [comment]
I have struggled with this problem for hours.
Thanks.


> Ok 😓 I found the problem. It was the chained methods of sharp to resize the image. This is weird, because I thought that the resize after composite does not affect to the composite operation. My solution is to convert it to buffer between composite and resize.
> 
> **does not work**
> 
> ```js
> const badge = createBadge(); /* buffer */
> let icon = sharp('./icon.png');
> icon = icon.composite([{ input: badge, top: 0, left: 0, blend: 'over' }]);
> icon = icon.resize(200, 200);
> icon.png().toFile('./result.png');
> ```
> 
> Because the resize only affect to the source image. The composite seems to be completed after the resize. You can see it if you resize it with a size of greater that the badge. e.g. resize it to 512 px. You see that the badge is not resized.
> 
> **this works**
> 
> ```js
> const badge = createBadge(); /* buffer */
> let icon = await sharp('./icon.png').toBuffer();
> icon = await sharp(icon).composite([{ input: badge, top: 0, left: 0, blend: 'over' }]).toBuffer();
> icon = await sharp(icon).resize(200, 200).toBuffer();
> sharp(icon).png().toFile('./result.png');
> ```
> 
> Use `toBuffer` to snapshot the state. Q: Why not chained directly? A: Because if-conditions in the original code. Q: Why does my demo project work? You said: Same code. A: Yes, but focused on the composite method, because this was the error. I successively tested the code. I resized a lot of icons for Android. And some of them are smaller than the badge. And I didn't know that the composite is executed after resize, even if the order is composite().resize(). ...
> 
> Again: The resize after composite resizes the source image (icon) only. And the composite is executed after that. In this case, the resize method changed the size of the source image to 200px and executes the composite with the badge of 420px. Note that `toBuffer` is async. I think this is the reason for sharp to behave like that. But I'm sure someone else can explain this better. Anyway... It works now. It's great that sharp can use svg and composite for dynamic auto-generated stuff. ❤️

**Comment by zenstok** [comment]
I can confirm as well, if you try to apply resize on a composite image it will not work even though you know the images are the same size or lower.
In my case this didn't work:
```
sharp(sharpLayers.shift())
  .composite(sharpLayers)
  .resize({ width: 640, height: 860 })
  .toFile(`output.png`);
  ```

But this worked:
```
sharp(sharpLayers.shift())
  .composite(sharpLayers)
  .toBuffer()
  .then((buffer) =>
    sharp(buffer)
      .resize({ width: 640, height: 860 })
      .toFile(`output.png`),
  );
