### ISSUE TITLE
gif compression optimization does not seem to work

### ISSUE THREAD

**Issue by banli17** [lovell/sharp#2380]
I installed version 0.26.1, but after many attempts to compress the gif, the file has not changed and is still very large. I downloaded a gif image, and the file size remains the same after sharp.

My operation is:

```
sharp('./2a68da120702177c5f069500e92894e7.gif', {pages: -1}).jpeg().toFile('./out.jpg')
```

file size is 

```
2a68da120702177c5f069500e92894e7.gif    530kb
out.jpg      610kb
```

But when I synthesize the jpg image(out-aa.jpg) into a gif, the size of the gif is 1.97MB

```
sharp('./out.jpg', ) 
    .gif({
      pageHeight: 249,
      loop: 0,
      delay: [
        100, 100, 100, 100, 100,
        100, 100, 100, 100, 100,
        100, 100, 100, 100, 100,
        100, 100, 100, 100, 100,
        100, 100, 100, 100, 100,
        100, 100, 100, 100, 100,
        100, 100, 100, 100, 100,
        100, 100, 100, 100, 100,
        100, 100
      ],
    })
    // .metadata()
    // .then(r => {
    //     console.log(r)
    // })
    .toFile('./out_gif.gif')
```

out_gif size is 1.97MB

**Comment by lovell** [comment]
Given you've installed libvips globally, please can you try using the vips CLI directly:
```sh
vips copy out.jpg out.gif[page_height=249,optimize_gif_frames,optimize_gif_transparency]
```

**Comment by banli17** [comment]
I tried it, the file is really big, use global vips

**Comment by kleisauke** [comment]
Perhaps you *magick is too old? Could you try to pass `--vips-info` to the vips CLI? libvips should print a warning if layer/transparency optimization is not supported, see:
https://github.com/libvips/libvips/blob/01bbef36d5fc24c3e193c8f6480c78fb2424902e/libvips/foreign/magick.c#L503-L504
https://github.com/libvips/libvips/blob/01bbef36d5fc24c3e193c8f6480c78fb2424902e/libvips/foreign/magick.c#L517-L518

fwiw, I couldn't reproduce this with:
```bash
$ wget https://raw.githubusercontent.com/banli17/test/master/2a68da120702177c5f069500e92894e7.gif
$ ls -l 2a68da120702177c5f069500e92894e7.gif
-rw-r--r--. 1 root root 530710 Sep 23 12:09 2a68da120702177c5f069500e92894e7.gif
$ vips copy 2a68da120702177c5f069500e92894e7.gif[n=-1] out.gif[optimize_gif_frames,optimize_gif_transparency] --vips-info
$ ls -l out.gif
-rw-r--r--. 1 root root 529582 Sep 23 12:10 out.gif
```

**Comment by banli17** [comment]
@kleisauke like this ?

![image](https://user-images.githubusercontent.com/12556069/94001143-ad3e8c00-fdca-11ea-890b-2b60030097b3.png)

no warn ， i use mac with brew install vips

**Comment by banli17** [comment]
@kleisauke  
The same goes for my centos, the latest libvips installed a few days ago

```
[root@VM_0_2_centos www]# ls -alh
-rw-r--r--   1 sftp sftp 1.9M Sep 23 19:02 out-aa.gif
-rw-r--r--   1 sftp sftp 596K Sep 23 19:02 out-aa.jpg
-rw-r--r--   1 root root 1.9M Sep 23 19:03 out-aax.gif
[root@VM_0_2_centos www]# vips copy out-aa.gif[n=-1] out-aax.gif[optimize_gif_frames,optimize_gif_transparency] --vips-info
[root@VM_0_2_centos www]# ls -l out-aax.gif
-rw-r--r-- 1 root root 1991829 Sep 23 19:04 out-aax.gif
[root@VM_0_2_centos www]# vips copy out-aa.gif[n=-1] out-aax.gif[optimize_gif_frames,optimize_gif_transparency] --vips-info
[root@VM_0_2_centos www]# ls -lh
-rw-r--r--   1 sftp sftp 1.9M Sep 23 19:02 out-aa.gif
-rw-r--r--   1 sftp sftp 596K Sep 23 19:02 out-aa.jpg
-rw-r--r--   1 root root 1.9M Sep 23 19:05 out-aax.gif
[root@VM_0_2_centos www]# vips copy out-aa.jpg out-aax.gif[page_height=249,optimize_gif_frames,optimize_gif_transparency] --vips-info
[root@VM_0_2_centos www]# ls -lh
-rw-r--r--   1 sftp sftp 1.9M Sep 23 19:02 out-aa.gif
-rw-r--r--   1 sftp sftp 596K Sep 23 19:02 out-aa.jpg
-rw-r--r--   1 root root 2.0M Sep 23 19:06 out-aax.gif
```

**Comment by banli17** [comment]
Yes, I upgraded to ImageMagick7 and it was fine , thanks

**Comment by banli17** [comment]
I did not find a good way to install ImageMagick7, but installed it by manual rpm. Record it。

1. Install dependencies

```
yum install -y libjpeg* libpng* libtiff* libungif* freetype zlib
```

2.  Install ImageMagick7-libs、ImageMagick7、ImageMagick7-devel In order，from https://centos.pkgs.org/7/remi-x86_64

3.  You can find the installation method of the specific package.

![image](https://user-images.githubusercontent.com/12556069/94090778-1238c700-fe49-11ea-9b08-59cbc599e3f6.png)

4. If the installation requires dependent packages, continue to query and install，The installation method is on the package details page，such as

![image](https://user-images.githubusercontent.com/12556069/94090898-69d73280-fe49-11ea-97c9-5f8e068f5c7e.png)

5. Follow the [libvips](https://libvips.github.io/libvips/install.html)  document to install, the configuration should be noted:

```
./configure --with-magickpackage=ImageMagick --with-modules
```

I forgot whether it was this。Because it seems that there is no giflib to use *magick

```
./configure --with-magickpackage=ImageMagick --with-modules --without-giflib
```
![image](https://user-images.githubusercontent.com/12556069/94091126-0d284780-fe4a-11ea-959a-170a58279316.png)

**Comment by banli17** [comment]
@lovell @kleisauke  , 
I made a mistake yesterday, it seems there is still a problem,I use ImageMagick 7 and ImageMagick 7-devel

```
[root@VM_0_2_centos test]# vips copy 2a68da120702177c5f069500e92894e7.gif[n=-1] out.gif[optimize_gif_frames,optimize_gif_transparency] --vips-info
[root@VM_0_2_centos test]# ls -al
-rw-r--r-- 1 sftp sftp 530710 Sep 24 14:45 2a68da120702177c5f069500e92894e7.gif
-rw-r--r-- 1 root root 529582 Sep 24 15:02 out.gif

[root@VM_0_2_centos test]# vips copy out-aa.jpg out.gif[page_height=249,optimize_gif_frames,optimize_gif_transparency] --vips-info
[root@VM_0_2_centos test]# ls -alh
-rw-r--r-- 1 sftp sftp 596K Sep 23 19:02 out-aa.jpg
-rw-r--r-- 1 root root 2.0M Sep 24 15:04 out.gif
```

**is 2MB。**

![image](https://user-images.githubusercontent.com/12556069/94112342-e08b2480-fe77-11ea-9a74-42f045a34188.png)

out-aa.jpg url is [https://github.com/banli17/test/blob/master/out-aa.jpg?raw=true](https://github.com/banli17/test/blob/master/out-aa.jpg?raw=true)

**Comment by lovell** [comment]
Please can you try using the ImageMagick CLI directly by adding the `-layers Optimize -layers OptimizeTransparency` flags when converting.

**Comment by banli17** [comment]
Yes, it looks like a problem with ImageMagick

```
[root@VM_0_2_centos test]# magick out-aa.jpg -layers Optimize -layers OptimizeTransparency outx.gif
[root@VM_0_2_centos test]# ls -alh
-rw-r--r-- 1 root root 528K Sep 24 15:13 out-aa.jpg
-rw-r--r-- 1 root root 2.0M Sep 24 16:43 outx.gif
```

**Comment by banli17** [comment]
@lovell  
I found that I can increase -fuzz 10% to compress the gif, the effect is very good

```
[root@VM_0_2_centos test]# magick out.gif  -fuzz 10% -layers Optimize -layers OptimizeTransparency  out-image.gif
ls -alh
[root@VM_0_2_centos test]# ls -alh
-rw-r--r-- 1 root root 306K Sep 24 17:27 out-image.gif
-rw-r--r-- 1 root root 2.0M Sep 24 15:19 out.gif
```

**Comment by kleisauke** [comment]
I tested this on CentOS 8 with an up-to-date version of libvips and ImageMagick installed from [Remi's RPM repository](https://rpms.remirepo.net/). Here are the install instructions:

<details>
  <summary>Install instructions</summary>

```bash
# Install the EPEL repository configuration package
dnf install epel-release

# Install the Remi repository configuration package
dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm

# Install the RPM Fusion repository configuration package (for libheif)
dnf install --nogpgcheck https://download1.rpmfusion.org/free/el/rpmfusion-free-release-8.noarch.rpm

# Install the dnf-utils package (for the dnf config-manager command)
dnf install dnf-utils

# Enable Remi's RPM repository
dnf config-manager --set-enabled remi

# Enable the PowerTools repository since EPEL packages may depend on packages from it
dnf config-manager --set-enabled PowerTools

# Install libvips (full-fat version)
dnf install vips-full vips-full-devel vips-full-tools
```
</details>

See https://github.com/libvips/libvips/issues/1184#issuecomment-447973135, if you are using CentOS 7.

**Comment by banli17** [comment]
Hello, what is your test result? What is the size of GIF generated from JPG @kleisauke  

Can you help test the size of the GIF generated by this image


https://github.com/banli17/test/blob/master/out-aa.jpg?raw=true

**Comment by banli17** [comment]
thank
