### ISSUE TITLE
Fail at constructor incorrect parameter

### ISSUE THREAD

**Issue by julienvedebe** [lovell/sharp#2383]
Sharp is used in Strapi project I was able to init a new project with Strapi but when I start it it fails in Sharp constructor here : 

try {
  require('../build/Release/sharp.node');
} catch (err) {

I have the latest version (0.26.1).

Steps to reproduce : install strapi and boot the project with yarn develop

What is the output of running `npx envinfo --binaries --system`?

npx: installed 1 in 2.336s

  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 5.64 GB / 15.88 GB
  Binaries:
    Node: 12.18.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.7.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD

See in screenshot path look weird with \\?\ 

![sharp](https://user-images.githubusercontent.com/12135264/94154418-24812800-fe7e-11ea-8985-fe9567305aa9.png)

**Comment by lovell** [comment]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?

If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

**Comment by julienvedebe** [comment]
Hi thanks for your feedback I tried ignore-scripts as required by the error output and also --verbose to catch any errors and in fact there is no error installation goes well.
To be sure I just install again using --unsafe-perm and it fix the issue thanks you very much for your support.
