### ISSUE TITLE
Multiple PNGs to Animated GIF

### ISSUE THREAD

**Issue by cthorner** [lovell/sharp#2385]
What are you trying to achieve?
Create an animated GIF from multiple different images. I'm thinking it is possible with the latest release, but this may be a feature request? Not sure.

Have you searched for similar questions?
Yes

Are you able to provide a minimal, standalone code sample that demonstrates this question?
```
sharp([image1.png, image2.png, image3.png, image4.png], { animated: true , delay: [100,200,300,100]})
.toFile('animated.gif')
```

Are you able to provide a sample image that helps explain the question?

**Comment by lovell** [comment]
You'll probably need the future possible enhancement detailed at #1580 for this.
