### ISSUE TITLE
Simple mesh perspective manipulation.

### ISSUE THREAD

**Issue by infacto** [lovell/sharp#2388]
**What are you trying to achieve?**
Draw an image on a perspective mesh with four points.
A use case is to replace the screen on a image with a tablet. 

**Have you searched for similar feature requests?**
Yes, nothing found.

**What would you expect the API to look like?**
Pass 4 points like: 

```js
const screen = sharp('screen.png').perspective([
  {
    x: 206,
    y: 37,
  },
  {
    x: 610,
    y: 31,
  },
  {
    x: 458,
    y: 407,
  },
  {
    x: 58,
    y: 367,
  },
]).toBuffer();

sharp('tablet.png')
  .composite([{
    input: screen,
    blend: 'over',
    left: 58,
    top: 30
  }])
  .png()
  .toFile('result.png');
```

Points starts from left-top, clockwise.

**What alternatives have you considered?**
I don't think that "skew" work here. It should be perspective.
I could use JavaScript canvas. There are demos on web. Either in '2d' or 'webgl'.
This is just an idea. You can immediately close it, if you think that this should not be a part of sharp. Or if the effort would be immense.

**Is there a sample image that helps explain?**
![demo](https://user-images.githubusercontent.com/60390085/94563276-c6ca5280-0266-11eb-89dc-dca98f3ff7b9.jpg)
Here you see the mesh perspective feature of Affinity Photo.
![demo](https://user-images.githubusercontent.com/60390085/94577332-b9b55f80-0276-11eb-8c84-d8c54061df1b.gif)
(Recorded gif, with limitations for less file size. low fps and less color.)

**Comment by lovell** [comment]
Please see #2095
