### ISSUE TITLE
SVG text attribute alignment-baseline="central" does not work.

### ISSUE THREAD

**Issue by infacto** [lovell/sharp#2389]
**Possible bug**: SVG text attribute [alignment-baseline](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline) `central` does not work. It renders like not set.

Version `0.26.1` (as npm package, executed via node script.)

```xml
<svg width="600" height="600" viewBox="0 0 600 600">
  <rect width="600" height="600" fill="#222222"/>
  <text x="300" y="300" 
    style="font-family: 'Arial'; font-size: 120px; fill: #ffffff;" 
    text-anchor="middle" alignment-baseline="central">
    DEMO
  </text>
  <line x1="0" y1="300" x2="600" y2="300" stroke="yellow"/>
</svg>
```

This is rendered in e,g, browser like (**expected**): 
![image](https://user-images.githubusercontent.com/60390085/94596949-30f5ee00-028d-11eb-8dcb-e2017e485228.png)

And in sharp:
![image](https://user-images.githubusercontent.com/60390085/94597389-cb563180-028d-11eb-910e-b332fb7403eb.png)

The text should be centered vertically.

My current workaround: Just don't use this attribute and move the y-value. ...
Am I doing something wrong? Is this an experimental attribute? Because other valid values also not work in browser. 🤔 Maybe not supported SVG version in the sharp renderer. ...

**Comment by lovell** [comment]
Please see #1996
