### ISSUE TITLE
How can I use toFile pseudo-synchronusly?

### ISSUE THREAD

**Issue by scharpentier0** [lovell/sharp#2390]
I'm trying to resize a few images and then create .ico files from them. I'm using sharp to resize my files and save them as a different file temporarily. I need to keep executing after the file is actualy present in the fs to be able to convert them, but using async doesn't seem to do much. 

Is there any way to only keep execution once the file is done writing like with fs.write

here's mock code of what I'm doing:

```
//all paths are global (wiht drive letter), not relative (not starting with ".")
async function execution(globalLocation) {
	let allDir = getAllDirs(globalLocation);
	for (dir of allDir) {
		let pngFile = getPNGfile(dir); //returns path of file string
		let image = await sharp(pngFile)
			.resize(256, 256, {
				kernel: sharp.kernel.nearest,
				fit: 'contain',
				background: { r: 255, g: 255, b: 255, alpha: 0.0 },
			})
			.toFile(`${dir}\\tmp.png`, (err) => {
				if (err) {
					throw err;
				}
			});
		console.log(JSON.stringify(getAllFiles(dir))); //file is not in file system yet
		convertToICO(`${dir}\\tmp.png`)// throw error file doesn't exists
	}
}
```

**Comment by lovell** [comment]
Hi, did you see https://sharp.pixelplumbing.com/api-output#tofile ?

> A Promise is returned when callback is not provided.

Conversely, a Promise is not returned when a callback is provided.

**Comment by lovell** [comment]
Perhaps the docs, in this case written in a era when the use of callbacks were more common than Promises, be clearer in this regard? Happy for a PR to update the JSDocs in the code, if you're able.
