### ISSUE TITLE
await does not work?

### ISSUE THREAD

**Issue by m00nk** [lovell/sharp#2392]
My code:

```
const fs = require('fs');
const sharp = require('sharp');

const src = '/tmp/input.jpg';
const dst = '/tmp/output.jpg';

(async () => {
    await sharp(src).resize(100, 100).toFile(dst);
    await fs.chmod(dst, 0o666);
})();

```
I have got an error:
`exception: Error: ENOENT: no such file or directory, chmod '/tmp/output.jpg'`

It looks like chmod runs before the sharp has been done its job.

Any ideas?

**Comment by lovell** [comment]
Hi, `fs.chmod` does not return a Promise, so this might be the cause. Perhaps add a try/catch block around each use of `await`?

**Comment by m00nk** [comment]
I have tried this:

```
(async () => {
    await sharp(src).resize(100, 100).toFile(dst);
    await fs.promises.chmod(dst, 0o666);
})();
```

and had the same result - chmod runs before the output file has been created.

**Comment by lovell** [comment]
Please can you provide complete information about the versions, platform, OS etc. involved.

**Comment by m00nk** [comment]
Linux Mint (Ubuntu), Node 12.18, sharp 0.26.0

**Comment by lovell** [comment]
Thanks, I cannot reproduce this. Is there anything unusual about the /tmp filesystem on this machine? Does using a non-tmp path work? What happened when you added the separate try/catch blocks around each use of await?

**Comment by m00nk** [comment]
I have found very strange behavior. The code:

```js
console.log('START');

const proc = sharp(srcImg);
// some other code is here
proc
	.toFile(dstImg)
	.then(info => { console.log('INFO', info);})
	.catch(err => { console.log('ERR', err);});

try{
	await proc;
	console.log('DONE PROC');
}
catch(e){ console.log('EXCEPTION', e); }

console.log('FINISHED');
```

I have got:
```
START
DONE PROC
FINISHED
INFO {
   format: 'jpeg',
   width: 250,
   height: 90,
   channels: 3,
   premultiplied: false,
   size: 8098
 }
```

So last console.log runs before the image has been created. But if I use "the chain" like:

```js
const proc = sharp(srcImg)
	.toFile(dstImg)
	.then(info => {	console.log('INFO', info);	})
	.catch(err => {	console.log('ERR', err);	});
```
instead of
```js
const proc = sharp(srcImg);
proc.toFile(dstImg)
	.then(info => { console.log('INFO', info);})
	.catch(err => { console.log('ERR', err);});
```
I have got:

```
START
INFO {
   format: 'jpeg',
   width: 250,
   height: 90,
   channels: 3,
   premultiplied: false,
   size: 8098
}
DONE PROC
FINISHED
```

In this way all works right - last console.log runs AFTER the image has been created.

Can you explain this behaviour? I am not very good in JS, so maybe I do something wrong, but in my opinion that behoviour is very odd. 

Thank you.

**Comment by lovell** [comment]
Your code is mixing up Promise chains and await/try/catch notation.

The call to `toFile()` returns a Promise, so that's what you must `await`, e.g. `await proc.toFile(dstImg)`

You can't await a sharp instance itself, so e.g. `await proc` is incorrect (it resolves straight away).

**Comment by m00nk** [comment]
Ah, yes. Thank you ))
