### ISSUE TITLE
Piping a PDF to metadata() and writing a JSON response stream

### ISSUE THREAD

**Issue by joergd** [lovell/sharp#2401]
I have an express server, and one endpoint is to return only the JSON of the metadata of the PDF. I am using the stream API.

``` javascript
  let metadataPipe = sharp();

  metadataPipe = metadataPipe.metadata((err, data) => {
    console.log("metadata", data)
    // this works ...
  })

  pipeline(imgStream, metadataPipe, res)

```

I don't want to return the converted PDF, just the JSON metadata - what I am really looking for is the number of pages in a PDF.

However, I run into several issues here that I am not sure how to resolve.

The one issue is that sharp still wants to process the PDF, but because PDF isn't allowed as an output format, it blows up.

Ok fine, so I could just force a JPEG output - if this the only way - so be it - but now it is unnecessarily 'converting' the PDF, which I don't need - I only need to read it to get the metadata.

The other problem I then encounter is that because metadataPipe contains the image, it is piped to the express result.

What I do want to pipe to express result, is the JSON object that contains the metadata.

What is the best approach to deal with this?

**Comment by lovell** [comment]
Hi, although you can Stream data into a sharp instance, `metadata()` doesn't support Stream-based output of the metadata; access is either via a Promise or a callback.

https://sharp.pixelplumbing.com/api-input#metadata

```js
const metadataPipe = sharp();
imgStream.pipe(metadataPipe);
res.json(await metadataPipe.metadata());
```

**Comment by joergd** [comment]
Ah ok - thanks for clarifying. Got it to work like that.
