### ISSUE TITLE
Error: Expected positive integer for height but received 21.72972972972973 of type number

### ISSUE THREAD

**Issue by sagar-rout** [lovell/sharp#2406]
npm - 12.X - running on aws lambda runtime
"sharp": "^0.26.1"

What are the steps to reproduce?

1. Download the image : https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Clocktower_Panorama_20080622_20mb.jpg/8192px-Clocktower_Panorama_20080622_20mb.jpg

2. then try to find out the metadata information : 

```javascript
        sharp(image.Body).metadata().catch(err => {
            console.log("Unable to process the image.");
            console.log(err);
            return; // do not throw error, otherwise lambda will retry(2) which will eventually fail too.
        });
```

2020-10-10T11:50:30.746Z	c86da499-b0a2-47f7-b6ca-fb82ba87fb34	INFO	Error: Expected positive integer for height but received 21.72972972972973 of type number
    at Object.invalidParameterError (/var/task/node_modules/sharp/lib/is.js:101:10)
    at Sharp.resize (/var/task/node_modules/sharp/lib/resize.js:223:16)
    at resizeImage (/var/task/resizer.js:63:10)
    at async Object.createThumbnail (/var/task/resizer.js:31:5)
    at async Runtime.exports.handler (/var/task/index.js:40:9)

**Comment by lovell** [comment]
Hi, the stack trace mentions functions not included here e.g. `resizeImage`.

Please provide the complete code to reproduce this error.

**Comment by sagar-rout** [comment]
Hi, I am extremly sorry that I didn't paste complete code and I found the issue. I think issue or I would say I didn't understand the error message and I got confused. 

```
await sharp(imageBuffer)
        .resize(thumbnailWidthInPixel, thumbnailHeightInPixel, {fit: 'cover'})
        .toBuffer();
```
I was passing the value of `thumbnailWidthInPixel` and `thumbnailHeightInPixel` in float values and not in integer. If **you want**, I would love to make error messages more readable or userfriendly.

**Comment by lovell** [comment]
Glad you got it working, and always happy to accept PRs to improve error messaging.

In this example, what part of "Expected positive integer for height but received 21.72972972972973" was confusing?

**Comment by sagar-rout** [comment]
Yeah, You're right. I thought "Expected positive integer for height but received float 21.72972972972973" will immedidately take developer focus on integer and float. But this floating point number is self explanatory. I am closing this ticket with this comment. Thank you for this awesome lib.

**Comment by felipebutcher** [comment]
Weird for me I am sending 5504 (number, typescript) which should be an integer and getting the same message.

"Expected integer for height but received 5504 of type string"

**Comment by felipebutcher** [comment]
Found out it was the size of the image, if i use size - 1 (5403) i don't the the error.

**Comment by lovell** [comment]
To verify any parameter values that are expected to contain an integer, sharp uses [Number.isInteger()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger).

https://github.com/lovell/sharp/blob/eefaa998725cf345227d94b40615e090495c6d09/lib/is.js#L101-L107
