### ISSUE TITLE
Consuming a lot of memory while processing images

### ISSUE THREAD

**Issue by Artur-Frank** [lovell/sharp#2407]
Unfortunately I do not speak English well. therefore I am writing through a translator.
When I use sharp for image processing and turn off the cache, each image takes up memory.
Tracking memory consumption via pm2. And when I load a large image through api, it can increase memory consumption by 15-20mb.

Node: 14.11.0

```js
const sharp = require('sharp');
sharp.cache(false);
///
await sharp(_image[0].data).jpeg({ progressive: true }).toBuffer()
                    .then(async (buffer) => {
                        await fs.writeFile(`${workspaceRoot}/public/publication_${_datetime}_user${_id}_350_350.jpeg`, await sharp(buffer).resize(350, 350).toBuffer());
                        return await fs.writeFile(`${workspaceRoot}/public/publication_${_datetime}_user${_id}_orig.jpeg`, buffer)
                    })
```

**Comment by lovell** [comment]
Hi, did you see #955, which is the canonical guide to perceived memory issues? If not, please make sure you've read and understood all of it.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
