### ISSUE TITLE
macOS, homebrew, libvips 8.10.2, HEIC input, magickload: unsupported colorspace YCbCrColorspace

### ISSUE THREAD

**Issue by leereichardt** [lovell/sharp#2409]
Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime? **Same Version**

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`? **Yes**

If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag? **Not using root**

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag? **Not ignoring scripts**

What is the output of running `npx envinfo --binaries --system`?
  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 1.50 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.13.0 - ~/.nvm/versions/node/v14.13.0/bin/node
    npm: 6.14.8 - ~/.nvm/versions/node/v14.13.0/bin/npm

I installed lipvips to 8.10.2 as I wanted to try to get HEIC support. This installed find, however, when installed Sharp, either via Verbose mode or non-verbose mode, I get the following notices out the end:
```
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)

ld: warning: dylib (/usr/local/Cellar/vips/8.10.2/lib/libvips-cpp.dylib) was built for newer macOS version (10.15) than being linked (10.9)
ld: warning: dylib (/usr/local/Cellar/vips/8.10.2/lib/libvips.dylib) was built for newer macOS version (10.15) than being linked (10.9)
ld: warning: dylib (/usr/local/Cellar/glib/2.66.1/lib/libgobject-2.0.dylib) was built for newer macOS version (10.15) than being linked (10.9)
ld: warning: dylib (/usr/local/Cellar/glib/2.66.1/lib/libglib-2.0.dylib) was built for newer macOS version (10.15) than being linked (10.9)
ld: warning: dylib (/usr/local/opt/gettext/lib/libintl.dylib) was built for newer macOS version (10.15) than being linked (10.9)
```

The verbose obviously outputs more but from my limited knowledge of compilation, this all looks fine. If I then attempt to load a HEIC either via filename, or buffer, I get [Error: Input file has corrupt header: magickload: unsupported colorspace YCbCrColorspace].

Any ideas on what I've done wrong here? When installing lipvips via homebrew, there were a few libraries that it didn't link as there were already conflicting versions on my machine from the OS. Am I needing to link these versions rather than use the standard OS versions?

TIA

Lee

ADDED EDIT: This error is only occuring when trying HEIC files, everything is still working as expected with standard images

**Comment by lovell** [comment]
My best guess would be that the vips provided by homebrew depends on both imagemagick and libheif and is selecting the former to read HEIC files.

https://github.com/Homebrew/homebrew-core/blob/master/Formula/vips.rb

If so, this is probably a limitation or misconfiguration of the homebrew-installed imagemagick's ability to load HEIC files - it's telling libvips that it can load HEIC files, but then falls over when doing so.

This might relate to https://github.com/ImageMagick/ImageMagick/issues/1440

**Comment by lovell** [comment]
This might also relate to https://github.com/libvips/libvips/issues/1861

**Comment by leereichardt** [comment]
Awesome. I'll keep an eye on both of those, but it's sounding like that second one if I'm reading that correctly.

**Comment by lovell** [comment]
Yes, please can you provide a sample image that fails in this manner as a comment on https://github.com/libvips/libvips/issues/1861 to help confirm.

**Comment by leereichardt** [comment]
I think we can close this issue now. Update coming out in lipvips 8.10.3
