### ISSUE TITLE
conditionally download gzip or brotli libvips based on node version

### ISSUE THREAD

**Issue by wardpeet** [lovell/sharp#2410]
What are you trying to achieve?
Gatsby has set its engine to 10.13.0. We would love to move to 0.26.0, technically we could bump a major to achieve this. Would you be okay to have a node version check that fallback to gz download on < 10.16.0.

**Comment by lovell** [comment]
Hi Ward, I'd be OK with a test for `zlib.BrotliDecompress`, falling back to `zlib.Inflate`. Happy to accept a PR for this if you're able.

A couple of things off the top of my head that might be relevant:

* the `.tar.gz` tarballs _should_ contain the same files as the `.tar.br` tarballs but the former are no longer tested as part of CI
* Node.js 10.13.0 contains ~20 known security vulnerabilities

**Comment by ascorbic** [comment]
@lovell I've opened a PR that does this, but I don't know the steps to re-enable the tar.gz checks in CI
