### ISSUE TITLE
Resizing artifact

### ISSUE THREAD

**Issue by paya-cz** [lovell/sharp#2411]
Run the code below:

```js
const sharp = require('sharp');

sharp('.\\image.png')
    .rotate()
    .resize({
        width: 128,
        height: 128,
    })
    .png()
    .toFile('.\\output.png');
```

Use the following image as **image.png**:

![image](https://user-images.githubusercontent.com/10402560/96100088-2b8bdb00-0efe-11eb-8f9d-5439ecfe5673.png)

I would expect the resized image the visually look almost identical to an image resized manually via Paint.Net app. Paint.Net app produces the following 128x128 image:

![favicon-paintnet](https://user-images.githubusercontent.com/10402560/96100527-aa811380-0efe-11eb-9d6f-0c846e3ffd67.png)

But, the code above renders the image as:

![output](https://user-images.githubusercontent.com/10402560/96100656-d00e1d00-0efe-11eb-8eec-587df7402928.png)

It may be tricky to spot the difference, so I highlighted the graphical artifact below:

![artifact](https://user-images.githubusercontent.com/10402560/96101021-3430e100-0eff-11eb-8a05-1b5d885e5c18.png)

Surprisingly, this artifact is present only on the left side of the image. The right side is artifact-free and looks the way I would expect (you may need to open the image in an external editor with a black background color to see it).

  System:
    OS: Windows 10 10.0.19041
    CPU: x64 Intel(R) Core(TM) i7
  Binaries:
    Node: 12.18.4
    npm: 6.14.6
    sharp: 0.26.2

**Comment by kleisauke** [comment]
I could reproduce this on libvips master with:
```bash
vipsthumbnail x.png -s 128x128 -o tn_%s.png --vips-novector
```

PR https://github.com/libvips/libvips/pull/1769 should fix this. With that PR, the above image is resized as:
![tn_x](https://user-images.githubusercontent.com/12746591/96114294-b7453d80-0ee5-11eb-9ac8-b9de789712ea.png)

**Comment by paya-cz** [comment]
@kleisauke Thanks, that's great news. Any idea when that PR might end up being reflected in the sharp NPM package?

**Comment by lovell** [comment]
@kleisauke Thanks for confirming this is the same as #2408

@paya-cz Please subscribe to https://github.com/libvips/libvips/pull/1769 for updates.
