### ISSUE TITLE
Error when uploading image from google Pixel phone using Firebase extension

### ISSUE THREAD

**Issue by mikemey01** [lovell/sharp#2416]
The issue is with the Firebase resize image extension, an issue was opened with the Firebase team but redirected here. You can view that issue at https://github.com/firebase/extensions/issues/460

What are the steps to reproduce?
1. Take a picture with a Google pixel 2 or 4 XL (possibly other Android devices)
2. upload that image to a Firebase storage bucket
3. enable the resize extension in firebase.
4. Note the error that is produced in the Firebase extension logs:

`Error when resizing image [Error: VipsJpeg: Corrupt JPEG data: 18 extraneous bytes before marker 0xdb VipsJpeg: Corrupt JPEG data: 18 extraneous bytes before marker 0xdb VipsJpeg: Corrupt JPEG data: 18 extraneous bytes before marker 0xdb VipsJpeg: Corrupt JPEG data: 18 extraneous bytes before marker 0xdb VipsJpeg: Corrupt JPEG data: 18 extraneous bytes before marker 0xdb VipsJpeg: out of order read at line 0 VipsJpeg: out of order read at line 0 ]`

What is the expected behaviour?
The uploaded image is correctly resized.

**Comment by lovell** [comment]
The sample image at https://user-images.githubusercontent.com/8120855/95335125-d7c92400-0863-11eb-9440-5d47700ade4a.jpg is not a valid JPEG.

Lots of other people have run into this, so it's probably an Android bug.
https://www.google.com/search?q="extraneous+bytes+before+marker+0xdb"

You can work around this by allowing `failOnError`, but ensure you trust the source of the images before doing so.

```js
sharp(input, { failOnError: false })...
```

https://sharp.pixelplumbing.com/api-constructor#parameters

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by lovell** [comment]
`failOnError` was deprecated in https://sharp.pixelplumbing.com/changelog#v0304---18th-april-2022

The use of `failOn` offers a wider range of options, with perhaps `failOn: 'truncated'` being appropriate if you trust the source of input.

https://sharp.pixelplumbing.com/api-constructor

**Comment by lovell** [comment]
@wmelton TypeScript definitions are maintained independently at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/sharp - please submit changes/fixes there.

**Comment by wmelton** [comment]
Thanks!

For reference: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/61141
