### ISSUE TITLE
undefined symbol: vips_foreign_heif_compression_get_type

### ISSUE THREAD

**Issue by jvonachen** [lovell/sharp#2423]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?
**Yes**

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?
**Yes**

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
**jvonachen@sherwin:~/kpmusicvideomachine $ npm ls sharp
/home/jvonachen
└── sharp@0.26.2  -> /home/jvonachen/sharp

jvonachen@sherwin:~/kpmusicvideomachine $ npm view sharp dist-tags.latest
0.26.2
**

If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?
**Not installing as root**

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?
**Not using the ignore-scripts feature of npm**

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?
**jvonachen@sherwin:~/kpmusicvideomachine $ npm install --verbose sharp
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@6.14.8
npm info using node@v12.19.0
npm verb config Skipping project config: /home/jvonachen/.npmrc. (matches userconfig)
npm verb npm-session b6bea158525dfd6f
npm http fetch GET 200 https://registry.npmjs.org/sharp 393ms
npm timing stage:loadCurrentTree Completed in 1453ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 9ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 513ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 472ms
npm timing stage:loadIdealTree Completed in 1254ms
npm timing stage:generateActionsToTake Completed in 63ms
npm verb correctMkdir /home/jvonachen/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/jvonachen/.npm/_locks/staging-154bf45da5572c45.lock for /home/jvonachen/node_modules/.staging
npm timing action:extract Completed in 183ms
npm info lifecycle undefined~preuninstall: undefined
npm info lifecycle undefined~uninstall: undefined
npm verb unbuild rmStuff undefined from /home/jvonachen/node_modules
npm verb unbuild rmStuff in /home/jvonachen/node_modules/sharp/node_modules
npm info lifecycle undefined~postuninstall: undefined
npm info lifecycle sharp@0.26.2~preuninstall: sharp@0.26.2
npm info lifecycle sharp@0.26.2~uninstall: sharp@0.26.2
npm verb unbuild rmStuff sharp@0.26.2 from /home/jvonachen/node_modules
npm info lifecycle sharp@0.26.2~postuninstall: sharp@0.26.2
npm timing action:unbuild Completed in 33ms
npm timing audit submit Completed in 267ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 267ms
npm timing audit body Completed in 3ms
npm timing action:remove Completed in 21ms
npm timing action:finalize Completed in 10ms
npm timing action:refresh-package-json Completed in 22ms
npm info lifecycle sharp@0.26.2~preinstall: sharp@0.26.2
npm timing action:preinstall Completed in 3ms
npm info linkStuff sharp@0.26.2
npm timing action:build Completed in 5ms
npm info lifecycle sharp@0.26.2~install: sharp@0.26.2

> sharp@0.26.2 install /home/jvonachen/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Detected globally-installed libvips v8.11.0
info sharp Building from source via node-gyp
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild'
gyp verb cli ]
gyp info using node-gyp@5.1.0
gyp info using node@12.19.0 | linux | arm
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - executable path is "/usr/bin/python"
gyp verb find Python - executing "/usr/bin/python" to get version
gyp verb find Python - version is "2.7.13"
gyp info find Python using Python version 2.7.13 found at "/usr/bin/python"
gyp verb get node dir no --target version specified, falling back to host node version: 12.19.0
gyp verb command install [ '12.19.0' ]
gyp verb install input version string "12.19.0"
gyp verb install installing version: 12.19.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 12.19.0
gyp verb build dir attempting to create "build" dir: /home/jvonachen/node_modules/sharp/build
gyp verb build dir "build" dir needed to be created? /home/jvonachen/node_modules/sharp/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/jvonachen/node_modules/sharp/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/jvonachen/node_modules/sharp/config.gypi
gyp verb common.gypi checking for gypi file: /home/jvonachen/node_modules/sharp/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/jvonachen/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/jvonachen/.cache/node-gyp/12.19.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/jvonachen/.cache/node-gyp/12.19.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/jvonachen/.cache/node-gyp/12.19.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/jvonachen/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture arm
gyp verb node dev dir /home/jvonachen/.cache/node-gyp/12.19.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/jvonachen/node_modules/sharp/build'
  cc '-DNODE_GYP_MODULE_NAME=nothing' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' -I/home/jvonachen/.cache/node-gyp/12.19.0/include/node -I/home/jvonachen/.cache/node-gyp/12.19.0/src -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/openssl/config -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/openssl/openssl/include -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/uv/include -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/zlib -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/v8/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer  -MMD -MF ./Release/.deps/Release/obj.target/nothing/../node-addon-api/nothing.o.d.raw   -c -o Release/obj.target/nothing/../node-addon-api/nothing.o ../../node-addon-api/nothing.c
  rm -f Release/obj.target/../node-addon-api/nothing.a && ar crs Release/obj.target/../node-addon-api/nothing.a Release/obj.target/nothing/../node-addon-api/nothing.o
  rm -rf "Release/nothing.a" && cp -af "Release/obj.target/../node-addon-api/nothing.a" "Release/nothing.a"
  touch Release/obj.target/libvips-cpp.stamp
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNAPI_VERSION=3' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DBUILDING_NODE_EXTENSION' -I/home/jvonachen/.cache/node-gyp/12.19.0/include/node -I/home/jvonachen/.cache/node-gyp/12.19.0/src -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/openssl/config -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/openssl/openssl/include -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/uv/include -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/zlib -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/v8/include -I../../node-addon-api -I/usr/local/include -I/usr/include/OpenEXR -I/usr/include/arm-linux-gnueabihf -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-psabi -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/common.o.d.raw   -c -o Release/obj.target/sharp/src/common.o ../src/common.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNAPI_VERSION=3' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DBUILDING_NODE_EXTENSION' -I/home/jvonachen/.cache/node-gyp/12.19.0/include/node -I/home/jvonachen/.cache/node-gyp/12.19.0/src -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/openssl/config -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/openssl/openssl/include -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/uv/include -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/zlib -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/v8/include -I../../node-addon-api -I/usr/local/include -I/usr/include/OpenEXR -I/usr/include/arm-linux-gnueabihf -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-psabi -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/metadata.o.d.raw   -c -o Release/obj.target/sharp/src/metadata.o ../src/metadata.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNAPI_VERSION=3' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DBUILDING_NODE_EXTENSION' -I/home/jvonachen/.cache/node-gyp/12.19.0/include/node -I/home/jvonachen/.cache/node-gyp/12.19.0/src -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/openssl/config -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/openssl/openssl/include -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/uv/include -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/zlib -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/v8/include -I../../node-addon-api -I/usr/local/include -I/usr/include/OpenEXR -I/usr/include/arm-linux-gnueabihf -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-psabi -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/stats.o.d.raw   -c -o Release/obj.target/sharp/src/stats.o ../src/stats.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNAPI_VERSION=3' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DBUILDING_NODE_EXTENSION' -I/home/jvonachen/.cache/node-gyp/12.19.0/include/node -I/home/jvonachen/.cache/node-gyp/12.19.0/src -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/openssl/config -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/openssl/openssl/include -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/uv/include -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/zlib -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/v8/include -I../../node-addon-api -I/usr/local/include -I/usr/include/OpenEXR -I/usr/include/arm-linux-gnueabihf -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-psabi -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/operations.o.d.raw   -c -o Release/obj.target/sharp/src/operations.o ../src/operations.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNAPI_VERSION=3' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DBUILDING_NODE_EXTENSION' -I/home/jvonachen/.cache/node-gyp/12.19.0/include/node -I/home/jvonachen/.cache/node-gyp/12.19.0/src -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/openssl/config -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/openssl/openssl/include -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/uv/include -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/zlib -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/v8/include -I../../node-addon-api -I/usr/local/include -I/usr/include/OpenEXR -I/usr/include/arm-linux-gnueabihf -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-psabi -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/pipeline.o.d.raw   -c -o Release/obj.target/sharp/src/pipeline.o ../src/pipeline.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNAPI_VERSION=3' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DBUILDING_NODE_EXTENSION' -I/home/jvonachen/.cache/node-gyp/12.19.0/include/node -I/home/jvonachen/.cache/node-gyp/12.19.0/src -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/openssl/config -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/openssl/openssl/include -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/uv/include -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/zlib -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/v8/include -I../../node-addon-api -I/usr/local/include -I/usr/include/OpenEXR -I/usr/include/arm-linux-gnueabihf -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-psabi -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/utilities.o.d.raw   -c -o Release/obj.target/sharp/src/utilities.o ../src/utilities.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNAPI_VERSION=3' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DBUILDING_NODE_EXTENSION' -I/home/jvonachen/.cache/node-gyp/12.19.0/include/node -I/home/jvonachen/.cache/node-gyp/12.19.0/src -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/openssl/config -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/openssl/openssl/include -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/uv/include -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/zlib -I/home/jvonachen/.cache/node-gyp/12.19.0/deps/v8/include -I../../node-addon-api -I/usr/local/include -I/usr/include/OpenEXR -I/usr/include/arm-linux-gnueabihf -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-psabi -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/sharp.o.d.raw   -c -o Release/obj.target/sharp/src/sharp.o ../src/sharp.cc
  g++ -shared -pthread -rdynamic  -Wl,-soname=sharp.node -o Release/obj.target/sharp.node -Wl,--start-group Release/obj.target/sharp/src/common.o Release/obj.target/sharp/src/metadata.o Release/obj.target/sharp/src/stats.o Release/obj.target/sharp/src/operations.o Release/obj.target/sharp/src/pipeline.o Release/obj.target/sharp/src/utilities.o Release/obj.target/sharp/src/sharp.o Release/obj.target/../node-addon-api/nothing.a -Wl,--end-group -L/usr/local/lib -lvips-cpp -lvips -lgobject-2.0 -lglib-2.0
  rm -rf "Release/sharp.node" && cp -af "Release/obj.target/sharp.node" "Release/sharp.node"
make: Leaving directory '/home/jvonachen/node_modules/sharp/build'
gyp info ok 
npm verb lifecycle sharp@0.26.2~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.26.2~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/jvonachen/node_modules/sharp/node_modules/.bin:/home/jvonachen/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
npm verb lifecycle sharp@0.26.2~install: CWD: /home/jvonachen/node_modules/sharp
npm timing action:install Completed in 73488ms
npm info lifecycle sharp@0.26.2~postinstall: sharp@0.26.2
npm timing action:postinstall Completed in 3ms
npm verb unlock done using /home/jvonachen/.npm/_locks/staging-154bf45da5572c45.lock for /home/jvonachen/node_modules/.staging
npm timing stage:executeActions Completed in 73843ms
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 76834ms
npm WARN saveError ENOENT: no such file or directory, open '/home/jvonachen/package.json'
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm info lifecycle undefined~postshrinkwrap: undefined
npm WARN enoent ENOENT: no such file or directory, open '/home/jvonachen/package.json'
npm verb enoent This is related to npm not being able to find a file.
npm verb enoent 
npm WARN jvonachen No description
npm WARN jvonachen No repository field.
npm WARN jvonachen No README data
npm WARN jvonachen No license field.

+ sharp@0.26.2
removed 1 package, updated 1 package and audited 116 packages in 77.372s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm verb exit [ 0, true ]
npm timing npm Completed in 78872ms
npm info ok 
**

What is the output of running `npx envinfo --binaries --system`?
**jvonachen@sherwin:~/kpmusicvideomachine $ npx envinfo --binaries --system
npx: installed 1 in 4.074s

  System:
    OS: Linux 4.19 Raspbian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (4) arm ARMv7 Processor rev 4 (v7l)
    Memory: 181.20 MB / 926.08 MB
    Container: Yes
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 12.19.0 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
**

**Comment by lovell** [comment]
> info sharp Detected globally-installed libvips v8.11.0

A globally-installed libvips compiled from source using its master/unstable branch was detected at install time. My best guess would be that a different version was detected at runtime, which would suggest there are multiple, conflicting libvips on this machine.

**Comment by jvonachen** [comment]
I think I have a handle on this now.  Thanks.
