### ISSUE TITLE
Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by himanshu73188** [lovell/sharp#2425]
npm start
npm WARN lifecycle The node binary used for scripts is /home/reviiewi/nodevenv/public_html/api/10/bin/node but npm is using /opt/alt/alt-nodejs10/root/usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> deliva-api@1.0.0 start /home/reviiewi/public_html/api
> node app.js

/home/reviiewi/nodevenv/public_html/api/10/lib/node_modules/multer-sharp/node_modules/sharp/lib/constructor.js:34
  throw new Error(error);
  ^

Error:
Something went wrong installing the "sharp" module

/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/reviiewi/nodevenv/public_html/api/10/lib/node_modules/multer-sharp/node_modules/sharp/build/Release/sharp.node)

**Comment by lovell** [comment]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

What is the output of running `npx envinfo --binaries --system`?

**Comment by himanshu73188** [comment]
hi, here you go:

**npm ls sharp**
deliva-api@1.0.0 /home/reviiewi/public_html/api
+-- multer-sharp@0.6.2
| `-- sharp@0.25.1
`-- sharp@0.26.2

 **npm view sharp dist-tags.latest**
0.26.2

**npm install --verbose sharp**
npm info it worked if it ends with ok
npm verb cli [ '/opt/alt/alt-nodejs10/root/usr/bin/node',
npm verb cli   '/opt/alt/alt-nodejs10/root/usr/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sharp',
npm verb cli   '--prefix=/home/reviiewi/nodevenv/public_html/api/10/lib' ]
npm info using npm@6.14.6
npm info using node@v10.22.0
npm verb npm-session 0657df2d69dd4cab
npm http fetch GET 200 https://registry.npmjs.org/sharp 72ms (from cache)
npm timing stage:loadCurrentTree Completed in 3079ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 8ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 1396ms
npm http fetch GET 304 https://registry.npmjs.org/simple-get 206ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/semver 209ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-addon-api 214ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 28ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mimic-response 71ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 2215ms
npm timing stage:loadIdealTree Completed in 4116ms
npm timing stage:generateActionsToTake Completed in 183ms
npm verb correctMkdir /home/reviiewi/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/reviiewi/.npm/_locks/staging-94a2330453ab9f89.lock for /home/reviiewi/nodevenv/public_html/api/10/lib/node_modules/.staging
npm timing action:extract Completed in 142ms
npm info lifecycle sharp@0.26.2~preuninstall: sharp@0.26.2
npm info lifecycle sharp@0.26.2~uninstall: sharp@0.26.2
npm verb unbuild rmStuff sharp@0.26.2 from /home/reviiewi/nodevenv/public_html/api/10/lib/node_modules
npm info lifecycle sharp@0.26.2~postuninstall: sharp@0.26.2
npm timing action:unbuild Completed in 46ms
npm timing audit submit Completed in 604ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 605ms
npm timing audit body Completed in 2ms
npm timing action:remove Completed in 421ms
npm timing action:finalize Completed in 89ms
npm timing action:refresh-package-json Completed in 18ms
npm info lifecycle sharp@0.26.2~preinstall: sharp@0.26.2
npm timing action:preinstall Completed in 1ms
npm info linkStuff sharp@0.26.2
npm timing action:build Completed in 1ms
npm info lifecycle sharp@0.26.2~install: sharp@0.26.2
npm WARN lifecycle The node binary used for scripts is /home/reviiewi/nodevenv/public_html/api/10/bin/node but npm is using /opt/alt/alt-nodejs10/root/usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> sharp@0.26.2 install /home/reviiewi/nodevenv/public_html/api/10/lib/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /home/reviiewi/.npm/_libvips/libvips-8.10.0-linux-x64.tar.br
prebuild-install info begin Prebuild-install version 5.3.6
prebuild-install info looking for cached prebuild @ /home/reviiewi/.npm/_prebuilds/9cbf3f-sharp-v0.26.2-napi-v3-linux-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ /home/reviiewi/.npm/_prebuilds/9cbf3f-sharp-v0.26.2-napi-v3-linux-x64.tar.gz
prebuild-install info unpack resolved to /home/reviiewi/nodevenv/public_html/api/10/lib/node_modules/sharp/build/Release/sharp.node
prebuild-install info install Successfully installed prebuilt binary!
npm verb lifecycle sharp@0.26.2~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.26.2~install: PATH: /opt/alt/alt-nodejs10/root/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/node-gyp-bin:/home/reviiewi/nodevenv/public_html/api/10/lib/node_modules/sharp/node_modules/.bin:/home/reviiewi/nodevenv/public_html/api/10/lib/node_modules/.bin:/home/reviiewi/nodevenv/public_html/api/10/bin:/opt/alt/alt-nodejs10/root/usr/bin:/home/reviiewi/nodevenv/public_html/api/10/lib/bin/:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/jdk/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/X11R6/bin:/usr/local/bin:/usr/X11R6/bin:/root/bin:/opt/bin:/opt/cpanel/composer/bin:/home/reviiewi/.local/bin:/home/reviiewi/bin
npm verb lifecycle sharp@0.26.2~install: CWD: /home/reviiewi/nodevenv/public_html/api/10/lib/node_modules/sharp
npm timing action:install Completed in 8310ms
npm info lifecycle sharp@0.26.2~postinstall: sharp@0.26.2
npm timing action:postinstall Completed in 1ms
npm verb unlock done using /home/reviiewi/.npm/_locks/staging-94a2330453ab9f89.lock for /home/reviiewi/nodevenv/public_html/api/10/lib/node_modules/.staging
npm timing stage:executeActions Completed in 9095ms
npm timing stage:rollbackFailedOptional Completed in 55ms
npm timing stage:runTopLevelLifecycles Completed in 16879ms
npm verb saving [ { name: 'sharp', spec: '^0.26.2', save: 'dependencies' } ]
npm verb shrinkwrap skipping write for package.json because there were no changes.
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm verb shrinkwrap skipping write for package-lock.json because there were no changes.
npm info lifecycle undefined~postshrinkwrap: undefined
npm WARN deliva-api@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

+ sharp@0.26.2
updated 1 package and audited 556 packages in 17.895s

23 packages are looking for funding
  run `npm fund` for details

found 5 vulnerabilities (1 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
npm verb exit [ 0, true ]
npm timing npm Completed in 19376ms
npm info ok

**npx envinfo --binaries --system**
npx: installed 1 in 2.734s
(node:2847659) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at /home/reviiewi/.npm/_npx/2847659/lib/node_modules/envinfo/dist/envinfo.js:1:91046
(node:2847659) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2847659) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by lovell** [comment]
> | -- sharp@0.25.1

Please upgrade to v0.26.2. You might need to submit a PR to [multer-sharp](https://github.com/ikhsanalatsary/multer-sharp) in order to do this.

> WARN lifecycle The node binary used for scripts is /home/reviiewi/nodevenv/public_html/api/10/bin/node but npm is using /opt/alt/alt-nodejs10/root/usr/bin/node itself.

You've got multiple, conflicting versions of node installed, which would explain why commands like `npx` are failing.

**Comment by TooColline** [comment]
Hi, @lovell I'm getting the same thing, and here are my logs. Looks like there's no explicitly installed version of the module in my app, is there something I've missed?
<img width="814" alt="Screenshot 2020-11-02 at 17 01 24" src="https://user-images.githubusercontent.com/38856515/97876546-0c2de400-1d2d-11eb-842e-5709be42a6a1.png">

**Comment by lovell** [comment]
@TooColline Please open a new installation issue and answer all of the questions - https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md

**Comment by liuba-larousse** [comment]
Hello!
Having the same isssue

`Error in "/Users/luba/Desktop/WEB-DEVELOPMENT/Projects/e_com/shopify-sleepmask/node_modules/gatsby-transformer-sharp/gatsby-node.js":
Something went wrong installing the "sharp" module

When run npm rebuild --verbose sharp

Cannot find module '../build/Release/sharp.node'`

`npm verb cli [
npm verb cli   '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'rebuild',
npm verb cli   '--verbose',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@7.0.3
npm info using node@v15.0.1
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 1ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/Users/luba/Desktop/WEB-DEVELOPMENT/Projects/e_com/shopify-sleepmask/.npmrc Completed in 0ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:/Users/luba/.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:cafile Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:setUserAgent Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 5ms
npm verb npm-session 735119c3cd120e4c
npm timing npm:load Completed in 15ms
npm timing arborist:ctor Completed in 1ms
npm timing arborist:ctor Completed in 0ms
npm timing build:queue Completed in 2ms
npm info run sharp@0.25.4 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
npm info run sharp@0.25.4 install { code: 1, signal: null }
npm timing command:rebuild Completed in 4726ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:63:27)
npm verb stack     at ChildProcess.emit (node:events:327:20)
npm verb stack     at maybeClose (node:internal/child_process:1048:16)
npm verb stack     at Socket.<anonymous> (node:internal/child_process:439:11)
npm verb stack     at Socket.emit (node:events:327:20)
npm verb stack     at Pipe.<anonymous> (node:net:656:12)
npm verb pkgid sharp@0.25.4
npm verb cwd /Users/luba/Desktop/WEB-DEVELOPMENT/Projects/e_com/shopify-sleepmask
npm verb Darwin 19.6.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "rebuild" "--verbose" "sharp"
npm verb node v15.0.1
npm verb npm  v7.0.3
npm ERR! code 1
npm ERR! path /Users/luba/Desktop/WEB-DEVELOPMENT/Projects/e_com/shopify-sleepmask/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
npm ERR! info sharp Using existing vendored libvips v8.9.1
npm ERR! prebuild-install info begin Prebuild-install version 5.3.6
npm ERR! prebuild-install info install installing standalone, skipping download.
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/local/bin/node',
npm ERR! gyp verb cli   '/Users/luba/Desktop/WEB-DEVELOPMENT/Projects/e_com/shopify-sleepmask/node_modules/.bin/node-gyp',
npm ERR! gyp verb cli   'rebuild'
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@15.0.1 | darwin | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` succeeded python2 /usr/bin/python2
npm ERR! gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.16
npm ERR! gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 15.0.1
npm ERR! gyp verb command install [ '15.0.1' ]
npm ERR! gyp verb install input version string "15.0.1"
npm ERR! gyp verb install installing version: 15.0.1
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 15.0.1
npm ERR! gyp verb build dir attempting to create "build" dir: /Users/luba/Desktop/WEB-DEVELOPMENT/Projects/e_com/shopify-sleepmask/node_modules/sharp/build
npm ERR! gyp verb build dir "build" dir needed to be created? /Users/luba/Desktop/WEB-DEVELOPMENT/Projects/e_com/shopify-sleepmask/node_modules/sharp/build
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: /Users/luba/Desktop/WEB-DEVELOPMENT/Projects/e_com/shopify-sleepmask/node_modules/sharp/build/config.gypi
npm ERR! gyp verb config.gypi checking for gypi file: /Users/luba/Desktop/WEB-DEVELOPMENT/Projects/e_com/shopify-sleepmask/node_modules/sharp/config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: /Users/luba/Desktop/WEB-DEVELOPMENT/Projects/e_com/shopify-sleepmask/node_modules/sharp/common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
npm ERR! gyp info spawn /usr/bin/python2
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/luba/Desktop/WEB-DEVELOPMENT/Projects/e_com/shopify-sleepmask/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/luba/Desktop/WEB-DEVELOPMENT/Projects/e_com/shopify-sleepmask/node_modules/sharp/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/luba/Desktop/WEB-DEVELOPMENT/Projects/e_com/shopify-sleepmask/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/luba/.node-gyp/15.0.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/luba/.node-gyp/15.0.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/luba/Desktop/WEB-DEVELOPMENT/Projects/e_com/shopify-sleepmask/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/luba/.node-gyp/15.0.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/luba/Desktop/WEB-DEVELOPMENT/Projects/e_com/shopify-sleepmask/node_modules/sharp',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
npm ERR! 
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
npm ERR! 
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
npm ERR! 
npm ERR! gyp: No Xcode or CLT version detected!
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/luba/Desktop/WEB-DEVELOPMENT/Projects/e_com/shopify-sleepmask/node_modules/node-gyp/lib/configure.js:345:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:327:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
npm ERR! gyp ERR! System Darwin 19.6.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/Users/luba/Desktop/WEB-DEVELOPMENT/Projects/e_com/shopify-sleepmask/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/luba/Desktop/WEB-DEVELOPMENT/Projects/e_com/shopify-sleepmask/node_modules/sharp
npm ERR! gyp ERR! node -v v15.0.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm verb exit 1
npm timing npm Completed in 4906ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/luba/.npm/_logs/2020-11-11T17_11_11_852Z-debug.log`


Seems like my versions in npm ls sharp is different from npm view sharp

`➜  shopify-sleepmask git:(master) ✗ npx envinfo --binaries --system

  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 7.42 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.0.1 - /usr/local/bin/node
    npm: 7.0.3 - /usr/local/bin/npm

➜  shopify-sleepmask git:(master) ✗ npm view sharp dist-tags.latest
0.26.2
➜  shopify-sleepmask git:(master) ✗ npm sharp -v
7.0.3
➜  shopify-sleepmask git:(master) ✗ npm ls sharp
gatsby-shopify-starter@0.1.0 /Users/luba/Desktop/WEB-DEVELOPMENT/Projects/e_com/shopify-sleepmask
├─┬ gatsby-plugin-manifest@2.4.37
│ └── sharp@0.25.4 deduped
├─┬ gatsby-plugin-sharp@2.6.43
│ └── sharp@0.25.4 deduped
├─┬ gatsby-transformer-sharp@2.5.20
│ └── sharp@0.25.4 deduped
└── sharp@0.25.4`

But I am not sure how to fix it and if its the issue

Please help!

**Comment by lovell** [comment]
@liuba-larousse Gatsby is not yet using the latest sharp - please can you try using Node.js 14 LTS rather than 15. If you're still having problems, please open a new installation issue - https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md

**Comment by lovell** [comment]
@himanshu73188 I'm going to close this issue as the actions in https://github.com/lovell/sharp/issues/2425#issuecomment-719912251 should solve your problem. Please feel free to reopen with more information if you still require help.
