### ISSUE TITLE
Input buffer contains unsupported image format

### ISSUE THREAD

**Issue by jvonachen** [lovell/sharp#2426]
What are you trying to achieve?
I use sharp, so far, to convert SVG strings to PNG images which end up as animated movies.  Here's an example if you are interested: https://www.youtube.com/watch?v=wpCcg-vgAlo&t=367s

Have you searched for similar questions?
Yes

Are you able to provide a minimal, standalone code sample that demonstrates this question?
`sharp(new Buffer.from(movie.buildXML(widthPx, heightPx, opacity)))
            .png()
            // save it
            .toFile(`${rasterDim}/${frameName}.png`)
            .then(function (info) {
                delete pendingFrames[timeSec]; // delete the property
                if(movieMakingDebug) console.log(`${movieName} ${dimension} ${frameName}/${totalFrames} v>r ${Math.floor(timeSec * 100) / 100} sec.`);
                if(Object.keys(pendingFrames).length === 0) makeTheMovieFile();
            })
            .catch(function (err) {
                console.log(err)
            })`

movie.buildXML() returns a string with the SVG

Are you able to provide a sample image that helps explain the question?
A sample movie provided above in the YouTube link.

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

The SVGs it generates are pretty large.  I isolated one and it's about 2.4 MB, each one.  I'm running this on a raspberry PI, 3b+, with a beta 64 bit distro.  This same program runs without problem on my Macbook.  I validated the SVG on the W3 validator and it's fine.  I'm wondering if the size is a problem.  Would that cause sharp to reject it as an SVG?

**Comment by lovell** [comment]
Please can you provide a sample input SVG.

Does this mean that #2423 can be closed? Are you still using a globally-installed libvips? If so, please provide all the version numbers involved, including that of libvips and librsvg.

**Comment by jvonachen** [comment]
[oneSVGDoc.svg.zip](https://github.com/lovell/sharp/files/5470997/oneSVGDoc.svg.zip)

I have 6 RPIs.  One I was working on with #2423 **I gave up on trying to get it to work**.  I have always wanted to use my PIs to be a ray trace render farm with Renderman which needs 64 bit.  So on another one of my PIs I installed a beta of the new 64 bit Raspberry PI OS, previously known as Raspbian.  It turns out Renderman also requires intel chips, so, outaluck.

Either way I did all the things I think I needed to do to make sharp work on that new system.  So it's a system that is a brand new installation.  I thought that would help and I think it did.  Since my system is **Linux ARM64 (glibc <= 2.28, musl)** in the instructions it says **The following platforms require compilation of both libvips and sharp from source:**. 

jvonachen@moore:~/kpmusicvideomachine $ sudo ldconfig -v | grep libvips
[sudo] password for jvonachen: 
ldconfig: Can't stat /usr/local/lib/aarch64-linux-gnu: No such file or directory
ldconfig: Can't stat /usr/local/lib/arm-linux-gnueabihf: No such file or directory
ldconfig: Path `/lib/aarch64-linux-gnu' given more than once
ldconfig: Path `/usr/lib/aarch64-linux-gnu' given more than once
ldconfig: /lib/aarch64-linux-gnu/ld-2.28.so is the dynamic linker, ignoring

ldconfig: /lib/arm-linux-gnueabihf/ld-2.28.so is the dynamic linker, ignoring

	libvips.so.42 -> libvips.so.42.13.0
	libvips-cpp.so.42 -> libvips-cpp.so.42.13.0

jvonachen@moore:~/kpmusicvideomachine $ sudo ldconfig -v | grep librsvg
ldconfig: Can't stat /usr/local/lib/aarch64-linux-gnu: No such file or directory
ldconfig: Can't stat /usr/local/lib/arm-linux-gnueabihf: No such file or directory
ldconfig: Path `/lib/aarch64-linux-gnu' given more than once
ldconfig: Path `/usr/lib/aarch64-linux-gnu' given more than once
ldconfig: /lib/aarch64-linux-gnu/ld-2.28.so is the dynamic linker, ignoring

	librsvg-2.so.2 -> librsvg-2.so.2.44.10
ldconfig: /lib/arm-linux-gnueabihf/ld-2.28.so is the dynamic linker, ignoring

Hope that helps.  I have only scratched the surface on sharp and hope to use it more in my automated art.

**Comment by jvonachen** [comment]
Sorry.  These are not the versions you were probably wanting me to provide.  I first installed libvips from github, the source.  This distribution did not have a version of libvips on its own nor did I even try to install it through apt since I knew I would need to do it from source.  I did not want any confusion.  There were many other things I had to install to arrive at libvips successfully being installed, at least 3 or 4.  Then I installed sharp.  That's what I was supposed to do?

All these things developed to solve the problem of dependency: compilation, make, configure, autoconfigure, various systems of package management, and for some reason they still can't get it right.  How many years has this been worked on?  Decades?  **The definition of good engineering is allowing people to be able to use technology and gain value from it without needing to understand it.**  I'm a developer.  Probably not at the level of yourself but still.  Can't somebody figure this all out?  Do we have to depend on Apple doing everything for us?

**Comment by jvonachen** [comment]
On my mac console.log(sharp.format); displays
{
  jpeg: {
    id: 'jpeg',
    input: { file: true, buffer: true, stream: true },
    output: { file: true, buffer: true, stream: true }
  },
  png: {
    id: 'png',
    input: { file: true, buffer: true, stream: true },
    output: { file: true, buffer: true, stream: true }
  },
  webp: {
    id: 'webp',
    input: { file: true, buffer: true, stream: true },
    output: { file: true, buffer: true, stream: true }
  },
  tiff: {
    id: 'tiff',
    input: { file: true, buffer: true, stream: true },
    output: { file: true, buffer: true, stream: true }
  },
  magick: {
    id: 'magick',
    input: { file: false, buffer: false, stream: false },
    output: { file: false, buffer: false, stream: false }
  },
  openslide: {
    id: 'openslide',
    input: { file: false, buffer: false, stream: false },
    output: { file: false, buffer: false, stream: false }
  },
  dz: {
    id: 'dz',
    input: { file: false, buffer: false, stream: false },
    output: { file: true, buffer: true, stream: true }
  },
  ppm: {
    id: 'ppm',
    input: { file: false, buffer: false, stream: false },
    output: { file: false, buffer: false, stream: false }
  },
  fits: {
    id: 'fits',
    input: { file: false, buffer: false, stream: false },
    output: { file: false, buffer: false, stream: false }
  },
  gif: {
    id: 'gif',
    input: { file: true, buffer: true, stream: true },
    output: { file: false, buffer: false, stream: false }
  },
  **svg: {
    id: 'svg',
    input: { file: true, buffer: true, stream: true },
    output: { file: false, buffer: false, stream: false }
  },**
  heif: {
    id: 'heif',
    input: { file: false, buffer: false, stream: false },
    output: { file: false, buffer: false, stream: false }
  },
  pdf: {
    id: 'pdf',
    input: { file: false, buffer: false, stream: false },
    output: { file: false, buffer: false, stream: false }
  },
  vips: {
    id: 'vips',
    input: { file: true, buffer: false, stream: false },
    output: { file: true, buffer: false, stream: false }
  },
  raw: {
    id: 'raw',
    input: { file: false, buffer: true, stream: true },
    output: { file: false, buffer: true, stream: true }
  }
}

But on my PI it shows:
{ jpeg:
   { id: 'jpeg',
     input: { file: false, buffer: false, stream: false },
     output: { file: false, buffer: false, stream: false } },
  png:
   { id: 'png',
     input: { file: true, buffer: true, stream: true },
     output: { file: true, buffer: true, stream: true } },
  webp:
   { id: 'webp',
     input: { file: false, buffer: false, stream: false },
     output: { file: false, buffer: false, stream: false } },
  tiff:
   { id: 'tiff',
     input: { file: false, buffer: false, stream: false },
     output: { file: false, buffer: false, stream: false } },
  magick:
   { id: 'magick',
     input: { file: false, buffer: false, stream: false },
     output: { file: false, buffer: false, stream: false } },
  openslide:
   { id: 'openslide',
     input: { file: false, buffer: false, stream: false },
     output: { file: false, buffer: false, stream: false } },
  dz:
   { id: 'dz',
     input: { file: false, buffer: false, stream: false },
     output: { file: false, buffer: false, stream: false } },
  ppm:
   { id: 'ppm',
     input: { file: true, buffer: false, stream: false },
     output: { file: true, buffer: false, stream: false } },
  fits:
   { id: 'fits',
     input: { file: false, buffer: false, stream: false },
     output: { file: false, buffer: false, stream: false } },
  gif:
   { id: 'gif',
     input: { file: false, buffer: false, stream: false },
     output: { file: false, buffer: false, stream: false } },
  **svg:
   { id: 'svg',
     input: { file: false, buffer: false, stream: false },
     output: { file: false, buffer: false, stream: false } },**
  heif:
   { id: 'heif',
     input: { file: false, buffer: false, stream: false },
     output: { file: false, buffer: false, stream: false } },
  pdf:
   { id: 'pdf',
     input: { file: false, buffer: false, stream: false },
     output: { file: false, buffer: false, stream: false } },
  vips:
   { id: 'vips',
     input: { file: true, buffer: false, stream: false },
     output: { file: true, buffer: false, stream: false } },
  raw:
   { id: 'raw',
     input: { file: false, buffer: true, stream: true },
     output: { file: false, buffer: true, stream: true } } }

**Comment by jvonachen** [comment]
I solved my problem.  I did not have librsvg library installed when I built libvips.  I installed librsvg then rebuilt libvips.  Then it worked.  Thanks.
