### ISSUE TITLE
Convert Equirectangular image to Cubemap

### ISSUE THREAD

**Issue by leon** [lovell/sharp#2429]
What are you trying to achieve?

Hi!
I want to use sharp in our cloud pipeline to convert equirectangular images into cube faces for three.js.

## Demo Project
I have created a labs project here where you can test out my MVP.
https://github.com/leon/labs-sharp-pano

## Description
I found a couple of repos on github demonstrating how to do the math, and with some tweaking I have been able to use sharp to load the data as a raw byte buffer.

My problem and question lies on to get the performance up.

The main gist of how it works is.

read image into array of pixels
loop through pixels and by using a bit of math define which cube face we are rendering and where the pixel should go
then using different algorithms (nearest, bicubic, lanczos) read the pixel and place the pixel.

depending on which algorithm I use the performance goes down drastically (understandable),

using the lanczos algorithm is by far the one that gives the best quality.

## Help
But I feel that I should be able to replace the copyPixel function with something from sharp, that is much quicker at doing the iteration and math.
But I'm a novice when it comes to image processing so I could really need some help with which functions to use.
and how to break down the problem.

I hope someone can give me some insight 😄 

Ps.
Thank you for the amazing library 🏅

**Comment by lovell** [comment]
@leon Were you able to make any progress with this?

**Comment by lovell** [comment]
Please see https://github.com/libvips/libvips/discussions/2299
