### ISSUE TITLE
Image mockup distortion

### ISSUE THREAD

**Issue by matheusmorett2** [lovell/sharp#2432]
What are you trying to achieve?
Realistic TShirt mockups

Have you searched for similar questions?
Yes

Are you able to provide a minimal, standalone code sample that demonstrates this question?
No

Are you able to provide a sample image that helps explain the question?
Yes

Hello everyone! 

I'm trying to make a realistic mockup combining a TShirt with some Art/Image. Today i'm using composite + blend mode multilply, and I'm getting this 

<img width="600" alt="Screen Shot 2020-11-05 at 15 46 53" src="https://user-images.githubusercontent.com/24697383/98283282-362a1500-1f7e-11eb-8005-f5e852e7eef7.png">

I'm trying to reach this reality, eg distortions. Is it possible? 

<img width="572" alt="Screen Shot 2020-11-05 at 15 48 43" src="https://user-images.githubusercontent.com/24697383/98283583-9e78f680-1f7e-11eb-90d1-e92b66dcc4d2.png">

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/pull/2336

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
