### ISSUE TITLE
Something went wrong installing the \"sharp\" module

### ISSUE THREAD

**Issue by nhokvouu** [lovell/sharp#2433]
error sharp in lambda aws with nodejs 12. Please help me check
{
  "errorType": "Error",
  "errorMessage": "\nSomething went wrong installing the \"sharp\" module\n\n/var/task/node_modules/sharp/build/Release/sharp.node: invalid ELF header\n\n- Ensure \"linux\" is used at install time as well as runtime\n- Consult the installation documentation at https://sharp.pixelplumbing.com/install\n- Search for this error at https://github.com/lovell/sharp/issues\n",
  "trace": [
    "Error: ",
    "Something went wrong installing the \"sharp\" module",
    "",
    "/var/task/node_modules/sharp/build/Release/sharp.node: invalid ELF header",
    "",
    "- Ensure \"linux\" is used at install time as well as runtime",
    "- Consult the installation documentation at https://sharp.pixelplumbing.com/install",
    "- Search for this error at https://github.com/lovell/sharp/issues",
    "",
    "    at Object.<anonymous> (/var/task/node_modules/sharp/lib/constructor.js:34:9)",
    "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
    "    at Module.load (internal/modules/cjs/loader.js:653:32)",
    "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
    "    at Module.require (internal/modules/cjs/loader.js:692:17)",
    "    at require (internal/modules/cjs/helpers.js:25:18)",
    "    at Object.<anonymous> (/var/task/node_modules/sharp/lib/index.js:3:15)",
    "    at Module._compile (internal/modules/cjs/loader.js:778:30)"
  ]
}

**Comment by lovell** [comment]
> Ensure "linux" is used at install time as well as runtime
> Consult the installation documentation at https://sharp.pixelplumbing.com/install

Did you see the following?

https://sharp.pixelplumbing.com/install#common-problems

https://sharp.pixelplumbing.com/install#aws-lambda

**Comment by nhokvouu** [comment]
i tried but it did not run. Can you help me?

**Comment by lovell** [comment]
What is the output of running the commands documented at https://sharp.pixelplumbing.com/install#aws-lambda ?

**Comment by nhokvouu** [comment]
My function run in my macbook. But it can not run in lambda function with nodejs 12. The output of running the commands documented at https://sharp.pixelplumbing.com/install#aws-lambda  is: 
npm install --arch=x64 --platform=linux sharp

> sharp@0.26.2 install /Users/lucifer/Documents/resize-image/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Detected globally-installed libvips v8.10.2
info sharp Building from source via node-gyp
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  LIBTOOL-STATIC Release/nothing.a
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  CXX(target) Release/obj.target/sharp/src/sharp.o
  SOLINK_MODULE(target) Release/sharp.node
npm WARN resize-image@1.0.0 No description
npm WARN resize-image@1.0.0 No repository field.

+ sharp@0.26.2
added 1 package from 65 contributors, updated 1 package and audited 71 packages in 87.433s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by lovell** [comment]
A globally-installed libvips was found:

> info sharp Detected globally-installed libvips v8.10.2

Please see https://sharp.pixelplumbing.com/install#building-from-source

You'll need to set `SHARP_IGNORE_GLOBAL_LIBVIPS` to ignore the globally-installed libvips.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
