### ISSUE TITLE
How to resize animated webp/gif?

### ISSUE THREAD

**Issue by luizbim** [lovell/sharp#2434]
Hi guys, I'm trying to resize an animated webp but no success.
I saw today that some new API [calls](https://github.com/lovell/sharp/issues/2275) are being developed, but I thought that the animated resizing functionality already works in some way.

A little sample code:
```js
      sharp("originalFilePath.webp", { animated: true })
        .resize({
          width: 200,
          height: 200,
        })
        .webp({
          pageHeight: 200,
          loop: 0,
          delay: 130,
          force: true,
        })
        .toFile("resizedFilePath.webp", (err, info) => {
          if (err) {
            console.error(err);
          }
         console.log('file resized')
        });
```

My objective is to resize and convert animated images back and forth using webp and gif extensions to accomplish a more cheaper bandwidth cost for my current project.

Thank you in advance for your time.

**Comment by lovell** [comment]
Hi, if you're resizing `n` pages at once you'll need to set the height to a multiple of `n`:

```diff
  .resize({
-    width: 200,
+    width: 200 * n,
    height: 200,
  })
```

**Comment by luizbim** [comment]
I've tried that, but the animation changed completely. Look like an animation of first page moving from down to top.

**Comment by lovell** [comment]
Sorry, I got width and height the wrong way round in the diff, it should be:
```diff
  .resize({
    width: 200,
-   height: 200,
+   height: 200 * n,
  })

**Comment by luizbim** [comment]
Yeah, I've noticed that but the result is the same.

**Comment by lovell** [comment]
You're probably seeing the effects of rounding "errors" at the top and bottom of each page/frame, which is pretty much why #2275 exists as a future possible enhancement.

Are you able to provide a sample input file? You'll probably only get any success when resizing to exactly 1/2 or 1/4 etc. of the original dimensions as things stand.

**Comment by luizbim** [comment]
I've noticed that if the new size is below 50% the glitch appears. Above 50% the image is resized correctly.

The Image is [here](https://firebasestorage.googleapis.com/v0/b/com-daily-stickers.appspot.com/o/9c7f3bc2-1b18-4d1b-9fa4-0979b21bdc14%2F3456ee66-bfd8-42c8-83a7-8a8aadaa4a9f.webp?alt=media&token=d3abf4a5-b186-4d76-82bc-130d2fb4efce)

**Comment by luizbim** [comment]
Also, for some reason resized images are heavier than the original.
Original:
- 512x512: 32k
Resized: 
- 512x512: 60k
- 300x300: 92k
- 256x256: 68k

**Comment by lovell** [comment]
Please subscribe to #2275 for updates.

**Comment by luizbim** [comment]
Ok, thank you very much @lovell.

**Comment by CrackerKSR** [comment]
is the problem solved?
