### ISSUE TITLE
vulnerability: Remote Memory Exposure

### ISSUE THREAD

**Issue by amjedomar** [lovell/sharp#2435]
To avoid [Remote Memory Exposure](https://www.npmjs.com/advisories/1555) vulnerability

please update `tar-fs` package

```
npm i tar-fs@2.1.1
```

also update `prebuild-install` package (after this issue [prebuild-install#132](https://github.com/prebuild/prebuild-install/issues/132) closed)

```
npm i prebuild-install
```

**Comment by lovell** [comment]
The latest `sharp` specifies `tar-fs` semver `^2.1.0`, which includes the latest version `2.1.1`. This means no release is required, but you may need to update package manager lock files, e.g. running `npm audit fix` should do this.

**Comment by amjedomar** [comment]
Thanks for your help

delete `yarn.lock file` and run `yarn` fix the problem
