### ISSUE TITLE
Run sharp in the browser, WebAssembly maybe?

### ISSUE THREAD

**Issue by woss** [lovell/sharp#2436]
What are you trying to achieve?
Run the sharp or light version of it in the browser.

Have you searched for similar questions?

Yes, only thing i found is this https://libvips.github.io/libvips/2020/09/01/libvips-for-webassembly.html and not sure how sharp will react in this case.

I know that sharp is mainly for the node js env because it is tied to the libvips but i'd like to know is it even possible to use the sharp in the browser ( i'm sure not at the moment ) but is it possible if somehow we would be able to use the https://libvips.github.io/libvips/2020/09/01/libvips-for-webassembly.html ?

**Comment by lovell** [comment]
No, sorry, previous discussions about this can be found at https://github.com/lovell/sharp/search?q=wasm&type=issues
