### ISSUE TITLE
Is there a way to remove a certain color from the picture?

### ISSUE THREAD

**Issue by banli17** [lovell/sharp#2438]
![image](https://user-images.githubusercontent.com/12556069/98899320-557af200-24ea-11eb-932b-4ab6c4192791.png)

For example, I want to remove the black area of ​​the transparent png image above into the following one

![image](https://user-images.githubusercontent.com/12556069/98899497-9bd05100-24ea-11eb-92f6-d0c1b615a1e7.png)

**Comment by lovell** [comment]
Please see #1648
