### ISSUE TITLE
Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by fordtn** [lovell/sharp#2439]
**%npm start**

> pracman_backend@1.0.0 start /Users/aristoslabs/ITW/common_service
> node build/index.js

Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'
Require stack:
- /Users/aristoslabs/ITW/common_service/node_modules/sharp/lib/constructor.js
- /Users/aristoslabs/ITW/common_service/node_modules/sharp/lib/index.js
- /Users/aristoslabs/ITW/common_service/build/api/services/FileService.js
- /Users/aristoslabs/ITW/common_service/build/api/services/ClinicService.js
- /Users/aristoslabs/ITW/common_service/build/api/services/AuthService.js
- /Users/aristoslabs/ITW/common_service/build/api/services/UserService.js
- /Users/aristoslabs/ITW/common_service/build/api/controllers/AuthController.js
- /Users/aristoslabs/ITW/common_service/build/config/routes.js
- /Users/aristoslabs/ITW/common_service/build/app.js
- /Users/aristoslabs/ITW/common_service/build/index.js

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pracman_backend@1.0.0 start: `node build/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pracman_backend@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aristoslabs/.npm/_logs/2020-11-12T16_55_02_383Z-debug.log

**% npm install --verbose sharp**

npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/usr/local/Cellar/node/15.0.1/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@6.14.8
npm info using node@v15.0.1
npm verb npm-session 754d90706541b1b7
npm http fetch GET 304 https://registry.npmjs.org/sharp 715ms (from cache)
npm timing stage:loadCurrentTree Completed in 9639ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 65ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 1684ms
npm http fetch GET 304 https://registry.npmjs.org/color 333ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/prebuild-install 713ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-copy-file-sync 728ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-get 834ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/semver 843ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-string 229ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-swizzle 124ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-arrayish 109ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/expand-template 503ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/github-from-package 502ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mkdirp-classic 466ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-abi 465ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/napi-build-utils 470ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/pump 578ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/noop-logger 587ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-fs 587ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/which-pm-runs 591ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/end-of-stream 190ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-concat 351ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 357ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mimic-response 219ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-stream 281ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-constants 409ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/readable-stream 418ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bl 435ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/buffer 133ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 13316ms
npm timing stage:loadIdealTree Completed in 16659ms
npm timing stage:generateActionsToTake Completed in 578ms
npm verb correctMkdir /Users/aristoslabs/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/aristoslabs/.npm/_locks/staging-932e3abbd7e09294.lock for /Users/aristoslabs/ITW/common_service/node_modules/.staging
npm timing action:extract Completed in 613ms
npm info lifecycle sharp@0.22.1~preuninstall: sharp@0.22.1
npm info lifecycle sharp@0.22.1~uninstall: sharp@0.22.1
npm verb unbuild rmStuff sharp@0.22.1 from /Users/aristoslabs/ITW/common_service/node_modules
npm info lifecycle sharp@0.22.1~postuninstall: sharp@0.22.1
npm timing action:unbuild Completed in 264ms
npm timing action:remove Completed in 74ms
npm timing action:finalize Completed in 19ms
npm timing action:refresh-package-json Completed in 66ms
npm info lifecycle sharp@0.22.1~preinstall: sharp@0.22.1
npm timing action:preinstall Completed in 2ms
npm info linkStuff sharp@0.22.1
npm timing action:build Completed in 4ms
npm info lifecycle sharp@0.22.1~install: sharp@0.22.1

> sharp@0.22.1 install /Users/aristoslabs/ITW/common_service/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /Users/aristoslabs/.npm/_libvips/libvips-8.7.4-darwin-x64.tar.gz
prebuild-install info begin Prebuild-install version 5.3.6
prebuild-install info looking for cached prebuild @ /Users/aristoslabs/.npm/_prebuilds/901b41-sharp-v0.22.1-node-v88-darwin-x64.tar.gz
prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.22.1/sharp-v0.22.1-node-v88-darwin-x64.tar.gz
prebuild-install http 404 https://github.com/lovell/sharp/releases/download/v0.22.1/sharp-v0.22.1-node-v88-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=15.0.1 runtime=node arch=x64 libc= platform=darwin)
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/Cellar/node/15.0.1/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild'
gyp verb cli ]
gyp info using node-gyp@5.1.0
gyp info using node@15.0.1 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - executable path is "/usr/local/opt/python@2/bin/python2.7"
gyp verb find Python - executing "/usr/local/opt/python@2/bin/python2.7" to get version
gyp verb find Python - version is "2.7.16"
gyp info find Python using Python version 2.7.16 found at "/usr/local/opt/python@2/bin/python2.7"
gyp verb get node dir no --target version specified, falling back to host node version: 15.0.1
gyp verb command install [ '15.0.1' ]
gyp verb install input version string "15.0.1"
gyp verb install installing version: 15.0.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 15.0.1
gyp verb build dir attempting to create "build" dir: /Users/aristoslabs/ITW/common_service/node_modules/sharp/build
gyp verb build dir "build" dir needed to be created? /Users/aristoslabs/ITW/common_service/node_modules/sharp/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/aristoslabs/ITW/common_service/node_modules/sharp/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/aristoslabs/ITW/common_service/node_modules/sharp/config.gypi
gyp verb common.gypi checking for gypi file: /Users/aristoslabs/ITW/common_service/node_modules/sharp/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/local/opt/python@2/bin/python2.7
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/aristoslabs/ITW/common_service/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/aristoslabs/Library/Caches/node-gyp/15.0.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/aristoslabs/Library/Caches/node-gyp/15.0.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/aristoslabs/Library/Caches/node-gyp/15.0.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/aristoslabs/ITW/common_service/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/aristoslabs/Library/Caches/node-gyp/15.0.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
dyld: Symbol not found: _OBJC_IVAR_$_NSFont._fFlags
  Referenced from: /Applications/Xcode.app/Contents/SharedFrameworks/DVTDocumentation.framework/Versions/A/../../../../SharedFrameworks/DVTKit.framework/Versions/A/DVTKit
  Expected in: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 in /Applications/Xcode.app/Contents/SharedFrameworks/DVTDocumentation.framework/Versions/A/../../../../SharedFrameworks/DVTKit.framework/Versions/A/DVTKit
make: error: unable to locate xcodebuild, please make sure the path to the Xcode folder is set correctly!
make: error: You can set the path to the Xcode folder using /usr/bin/xcode-select -switch
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 71
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:327:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/Cellar/node/15.0.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/aristoslabs/ITW/common_service/node_modules/sharp
gyp ERR! node -v v15.0.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm verb lifecycle sharp@0.22.1~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.22.1~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/aristoslabs/ITW/common_service/node_modules/sharp/node_modules/.bin:/Users/aristoslabs/ITW/common_service/node_modules/.bin:/Users/aristoslabs/.rvm/gems/ruby-2.1.1/bin:/Users/aristoslabs/.rvm/gems/ruby-2.1.1@global/bin:/Users/aristoslabs/.rvm/rubies/ruby-2.1.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/opt/X11/bin:/Users/aristoslabs/.rvm/bin
npm verb lifecycle sharp@0.22.1~install: CWD: /Users/aristoslabs/ITW/common_service/node_modules/sharp
npm http fetch POST 400 https://registry.npmjs.org/-/npm/v1/security/audits/quick 2469ms
npm info lifecycle sharp@0.22.1~install: Failed to exec install script
npm timing action:install Completed in 42657ms
npm verb unlock done using /Users/aristoslabs/.npm/_locks/staging-932e3abbd7e09294.lock for /Users/aristoslabs/ITW/common_service/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 1351ms
npm timing stage:runTopLevelLifecycles Completed in 74377ms
npm WARN pracman_backend@1.0.0 No repository field.

npm verb stack Error: sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (node:events:327:20)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (node:events:327:20)
npm verb stack     at maybeClose (node:internal/child_process:1048:16)
npm verb stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
npm verb pkgid sharp@0.22.1
npm verb cwd /Users/aristoslabs/ITW/common_service
npm verb Darwin 19.6.0
npm verb argv "/usr/local/Cellar/node/15.0.1/bin/node" "/usr/local/bin/npm" "install" "--verbose" "sharp"
npm verb node v15.0.1
npm verb npm  v6.14.8
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.22.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 78745ms

**% npm ls sharp**
pracman_backend@1.0.0 /Users/aristoslabs/ITW/common_service
└── UNMET DEPENDENCY sharp@^0.22.1

npm ERR! missing: sharp@^0.22.1, required by pracman_backend@1.0.0
aristoslabs@Alabs-II common_service % npm view sharp dist-tags.latest
0.26.2
aristoslabs@Alabs-II common_service % npx envinfo --binaries --system
npx: installed 1 in 7.129s

  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz
    Memory: 194.00 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.0.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm

**Comment by lovell** [comment]
Please upgrade sharp to the latest version for Node,js 15 support.

**Comment by jonexume** [comment]
Please upgrade sharp for Node version 15.3.0.  Thank you
