### ISSUE TITLE
Webp vs. JPEG sizes?

### ISSUE THREAD

**Issue by RoosterH** [lovell/sharp#2442]
I am a newbie for image processing.  To my understanding, webp is supposed to have smaller size than jpeg.  However, from my experiment, this is not the case after converting to both format using Sharp.

I am actually getting smaller sizes when converting to JPEG.  
Here is my configurations:
```
sharp().resize({ width: 300 }).jpeg({ quality: 100 })
sharp().resize({ width: 300 }).webp({ lossless: true })
```
Original PNG size is 937 KB.
Converted JPEG is 408.7 KB
Converted WEBP is 584.9 KB

For resized smaller images are the same result.  
Am I missing something or this is expected?

**Comment by lovell** [comment]
Hi, JPEG is always lossy, even at a "quality" of 100.

A fairer comparison might be:
```diff
  sharp().resize({ width: 300 }).jpeg({ quality: 100 })
- sharp().resize({ width: 300 }).webp({ lossless: true })
+ sharp().resize({ width: 300 }).webp({ quality: 100 })
```

**Comment by RoosterH** [comment]
lovell,

Thanks a lot.  After trying 
```
 sharp().resize({ width: 300 }).webp({ quality: 100 })
```
The size was reduced to 217.3 LB.  This indeed is a great reduction!
