### ISSUE TITLE
Using Sharp Synchronously

### ISSUE THREAD

**Issue by jvonachen** [lovell/sharp#2444]
Asynchronous is great and fast but as we all know optimization for speed is often at the expense of memory.  If you try to do something beefy on a system that does not have enough RAM it can easily exceed it and even the swap.  Is it possible to use Sharp synchronously?

**Comment by lovell** [comment]
If you mean "limit the concurrency" then you can already control this in your own code using something like https://caolan.github.io/async/v3/docs.html#eachLimit

If you want fine-grained control over the underlying thread pools then https://sharp.pixelplumbing.com/api-utility#concurrency provides more details.

**Comment by jvonachen** [comment]
OK.  I found a solution.  This spreads out a schedule of calls with the assumption that the remaining calls will take more or less the same amount of time.  If you are doing a lot of calls like this on a system that has a small amount of memory and will swap and run out of swap this is how I'm doing it.

```
let frame = 0;
const startSharp = Date.now(); // measure how long it takes for one thing to happen
let spread; // This will contain the number of milliseconds it takes
sharp(/* parameters including i=0 */)
.then(function (info) {
    spread = Date.now() - startSharp;
    doTheRest();
})
function doTheRest() {
    frame++;
    for(let i = 1; i < max; i++) {
        setTimeout(function () {
            sharp(/* parameters with i starting at 1 */)
            .then(function (info) {
                /* do some stuff *//
            })
        }, spread * frame); // This will spread out the calls
    }
    frame++;
}
```
