### ISSUE TITLE
VipsJpeg: Invalid SOS parameters for sequential

### ISSUE THREAD

**Issue by gilcohen** [lovell/sharp#2445]
Hi, I use sharp (javascript) to resize images to webp and jpg from time to time I get this error without any idea why this is happening:

ERROR	catch message : VipsJpeg: Invalid SOS parameters for sequential JPEGVipsJpeg: out of order read at line 0vips2png: unable to write to target

Does somebody know why it's happening?

**Comment by lovell** [comment]
Please see #1578
```js
sharp(input, { failOnError: false })...
```
