### ISSUE TITLE
Tiff output option for 'ccittfax4' yeilds Error: Fax3SetupState: Bits/sample must be 1 for Group 3/4 encoding/decoding

### ISSUE THREAD

**Issue by rploserth** [lovell/sharp#2446]
npm view sharp dist-tags.latest:
Sharp Version: 0.26.3

A10239:tiff_jpg_sharp_mac $ npx envinfo --binaries --system
npx: installed 1 in 1.44s

  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 124.20 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.6.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm

Sharp errors when attempting to resize any one of four CMYK tiff separations and save them back as a Group 4 encoding. The file uploaded as a sample was renamed with a jpg extension. I was unable to upload a tif. Please just fix the extension to reproduce. I tried saving a number of different file formats as a tif with the same results.

Code snippet:

```
sharp(img2.tiff, {limitInputPixels: 0} )
    .metadata()
   .resize({ width: 1584,
                height: 3086
    })
   .withMetadata()
   .tiff({
        compression: 'ccittfax4',
        bitdepth: 1,
    })
   .toFile('./file1(K).tiff')
   then(info => { console.log("It worked") })
  .catch(err => { console.log("It Broke: " + err.stack) });
```

Error occurs on MacOs 10.15.6 Catalina.

![Y110220XD006XBYXXXE1b(M)](https://user-images.githubusercontent.com/11755955/99589431-fb7e9e80-29b9-11eb-8655-7d0b800d07b2.jpg)

**Comment by lovell** [comment]
Hi, you'll need to add ` toColourspace('b-w')` to ensure single channel output.

https://sharp.pixelplumbing.com/api-colour#tocolourspace

There's an example of this in the unit tests:

https://github.com/lovell/sharp/blob/c10888e6fe38885e2a21ee9598b941001920fd22/test/unit/tiff.js#L133-L140

**Comment by rploserth** [comment]
This is what ended up working for me. I neglected to mention that I was erroneously using resize to change the DPI. In addition to your notes, I added the density construct to my tiff output settings. The four separations were then joined and written as a jpg.
```
await sharp(tiffFile, {limitInputPixels: 0} )
        .sharpen()
        .resize({ width: 1584,
                     height: 3086
        })
        .toColourspace('b-w') // can only squash 1 band uchar images
        .tiff({
            bitdepth: 1,
            compression: 'none',
            predictor: 'none',
            density: 600
        })
        .toBuffer()
        .then((data) => {
            fs.writeFileSync(tiffFile, data);
            console.log("File: " + tiffFile + " resized.");
        })
        .catch(err => { console.log(err.stack) });
```
Thanks for your help and I believe we can close this one.
