### ISSUE TITLE
Error: pngload: non-recoverable state

### ISSUE THREAD

**Issue by ascorbic** [lovell/sharp#2448]
Hi Lovell. The attached image crashes the latest sharp every time with the error "pngload: non-recoverable state". This seems to be this issue: https://github.com/libvips/libvips/issues/1748

I'm assuming this is a regression, as it was apparently fixed here: https://github.com/lovell/sharp-libvips/pull/58

We upgraded gatsby's sharp version yesterday and [this bug report](https://github.com/gatsbyjs/gatsby/issues/28203) came from a user within hours, so I'm imagining it's not going to be rare.

Minimal reproduction: https://repl.it/@ascorbic/sharp-png-bug

Image: https://github.com/barbalex/apf2/blob/master/src/benutzerDoku/ekPlanen/ekplanen_ap.png

**Comment by lovell** [comment]
Hi, this PNG image is corrupt:
```
$ pngcheck ekplanen_ap.png 
ekplanen_ap.png  CRC error in chunk iCCP (computed 66723ff5, expected 62c14516)
```
To ignore this, set `failOnError` to `false`:

https://sharp.pixelplumbing.com/api-constructor#parameters

```js
sharp(input, { failOnError: false })...
```
