### ISSUE TITLE
Chaining operations without losing quality

### ISSUE THREAD

**Issue by igorescobar** [lovell/sharp#2453]
Hi 👋 ,

Sometimes you need to do operations on images that you need to do a `.toBuffer()` so the next step of the image manipulation would use the output & metadata of the previous step. 
The problem is that every time you do a `sharp(image)` the image seems to lose quality incrementally. Like

```node
image = sharp(buffer).trim().toBuffer()
// ... some logic ...
image = sharp(image).resize().toBuffer()
// ... some logic ...
image = sharp(image).extract().toBuffer()
```

The code above is just an example but you can imagine that each operation might be on different files and `image` is like a shared context.

Is there any way you would recommend/suggest to do this without losing quality every time we `sharp()` the image buffer?

I read this discussion earlier: https://github.com/lovell/sharp/issues/241 and it seems that it might solve this specific problem but it seems that it's only a "concept" for now.

Let me know if I need to provide more info!

Thanks! 🙏

**Comment by lovell** [comment]
Try a lossless format such as PNG, or (faster, higher memory usage) use [raw](https://sharp.pixelplumbing.com/api-output#raw) pixel data.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
