### ISSUE TITLE
Output density inconsistent

### ISSUE THREAD

**Issue by juliangruber** [lovell/sharp#2455]
I'm debugging an issue where png output density isn't 72, and noticed that the expected densities are all over the place:

```bash
$ find test/fixtures/expected/*.{png,jpg} | xargs identify -format "%x x %y\n" | sort | uniq
10 x 10
118.10999999999999943 x 118.10999999999999943
25.399999999999998579 x 25.399999999999998579
28.339999999999999858 x 28.339999999999999858
28.350000000000001421 x 28.350000000000001421
3628.3499999999999091 x 3628.3499999999999091
37.799999999999997158 x 37.799999999999997158
472.43999999999999773 x 472.43999999999999773
5.6699999999999999289 x 5.6699999999999999289
72 x 72
```

Maybe these files weren't generated with `sharp`, so I did a simple check:

```js
const sharp = require('.')

sharp(`${__dirname}/test/fixtures/expected/16-bit-grey-alpha-identity.png`)
  .toFile(`${__dirname}/out.png`)
```

```bash
$ node example.js && identify -format "%x x %y\n" out.png 
28.350000000000001421 x 28.350000000000001421
```

If you change the output format to `jpg`, it's basically 72x72:

```bash
$ node example.js && identify -format "%x x %y\n" out.jpg 
72.009000000000000341 x 72.009000000000000341
```

I wonder where these numbers are coming from. This is on git master.

**Comment by juliangruber** [comment]
For context, I discovered this converting files to PDFs, where pixel density is an important value to read

**Comment by lovell** [comment]
The test files are from all over the place so it doesn't surprise me that the density metadata is too :) 

PNG images use the rather unusual pixels per metre as their integer units for this, hence the rounding errors when converting to DPI - see https://www.cocoanetics.com/2013/02/72-009-dpi/

Please see #967 for a future possible enhancement to allow setting the xres and yres.

**Comment by juliangruber** [comment]
Thank you for the quick answer!

Why is it though that png outputs as 28.35 DPI and JPG as 72.009 DPI? Shouldn't both be 72 DPI (or as close as JPG is)? This could also be an imagemagick issue of course.

If all file formats reliably output 72 DPI (or as close as JPG is) that would solve this for me for now. I saw this issue again, and would be happy to contribute once we need to output custom DPI :)

**Comment by lovell** [comment]
Been a while but I did a quick check and the ImageMagick `identity` tool outputs PNG density as pixels/cm, so when it says 28.35 that's equivalent to 28.35 * 2.54 = 72.009 DPI, which I think is what you were expecting. Is this still a problem?
