### ISSUE TITLE
SVG with transform to PNG conversion result in a black image

### ISSUE THREAD

**Issue by zero41120** [lovell/sharp#2456]
#### Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
sharp@0.26.3

#### What are the steps to reproduce?
The following SVG file is an upside down checkmark:
```xml
<svg  width="512px" height="518px" viewBox="0 -69 512 518" xmlns="http://www.w3.org/2000/svg">
    <path d="M62,290 L62,290 L182,172 L449,437 Q461,449,475,449 L475,449 Q490,449,501,438 Q512,427,512,412 Q512,397,500,385 L500,385 L182,69 L11,238 Q0,249,0,264 Q0,279,11,290 Q22,301,37,301 L37,301 Q51,301,62,290 Z " fill="#0066cc" fill-rule="evenodd"></path>
</svg>
```
![image](https://user-images.githubusercontent.com/10471270/100178296-74816880-2e88-11eb-8bb6-5d2b38468895.png)

And converting with sharp yields correct result:
```javascript
const sharp = require("sharp");
sharp(path.join(__dirname, 'uniF10A.svg'))
    .png()
    .toFile(path.join(__dirname, 'uniF10A.png'));
```
![image](https://user-images.githubusercontent.com/10471270/100178469-c4602f80-2e88-11eb-9551-89e8842da184.png)

If we add transform to the svg to flip the checkmark, with following
```xml
<svg transform="scale(1 -1)" width="512px" height="518px" viewBox="0 -69 512 518" xmlns="http://www.w3.org/2000/svg">
    <path d="M62,290 L62,290 L182,172 L449,437 Q461,449,475,449 L475,449 Q490,449,501,438 Q512,427,512,412 Q512,397,500,385 L500,385 L182,69 L11,238 Q0,249,0,264 Q0,279,11,290 Q22,301,37,301 L37,301 Q51,301,62,290 Z " fill="#0066cc" fill-rule="evenodd"></path>
</svg>
```
![image](https://user-images.githubusercontent.com/10471270/100178659-30db2e80-2e89-11eb-9f82-a4f99eed7730.png)

Same conversion script yields a back image
```javascript
const sharp = require("sharp");
sharp(path.join(__dirname, 'uniF10A.svg'))
    .png()
    .toFile(path.join(__dirname, 'uniF10A.png'));
```
![image](https://user-images.githubusercontent.com/10471270/100178691-4c463980-2e89-11eb-82f7-f268abdffbd1.png)
Other type like `jpge` also result in a black image.

#### What is the expected behaviour?
The converted image should not be black and should contain the correct image after svg transformation. 

#### Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
The required image and script is provided in the reproduction step.

#### Are you able to provide a sample image that helps explain the problem?
The required image and script is provided in the reproduction step.

#### What is the output of running `npx envinfo --binaries --system`?
```
  System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Xeon(R) CPU E3-1505M v6 @ 3.00GHz
    Memory: 20.15 GB / 31.88 GB
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
```

**Comment by lovell** [comment]
Please see #1791
