### ISSUE TITLE
Add support for io.js v3 (and therefore Node v4)

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#246]
Placeholder to track the upgrade to the new version of io.js/V8 and all the nan changes this will require.

This requires comprehensive memory leak and Buffer performance checks.

**Comment by lovell** [comment]
V8 seems to have jumped on the monad bus with the (Haskell-inspired?) `MaybeLocal` type. This forces explicit exception handling, a good thing, but it does mean a fairly big code change to the marshalling of data between V8 and native C types.

**Comment by mahnunchik** [comment]
I've allowed failures in [gulp-responsive](https://github.com/mahnunchik/gulp-responsive) for iojs v3 for a while: https://github.com/mahnunchik/gulp-responsive/blob/master/.travis.yml#L7-L9

**Comment by lovell** [comment]
The work-in-progress branch for this can be tested via `npm install lovell/sharp#nan2`

Everything compiles and the functional tests pass using io.js v3.1.0.

I have yet to run the leak checks (will probably require additional suppression rules for new V8 API) or used the benchmarks to measure the effects, if any, of recent changes to the Buffer object.

**Comment by lovell** [comment]
Leak checks run on Node.js v0.12, io.js v2.5.0 and v3.1.0.

Changes were required - see https://github.com/lovell/sharp/commit/4e67a5025a9236b1bdb7544e01a41479bf3c95be

**Comment by lovell** [comment]
Benchmarks run using Node.js v0.12.7 and io.js v3.1.0.

There's no statistically significant performance impact - (de)compression I/O is still the bottleneck.

**Comment by lovell** [comment]
Support for io.js v3 now in master - this will be published to npm as part of v0.11.2.
