### ISSUE TITLE
Install sharp with --ignore-scripts tag

### ISSUE THREAD

**Issue by bhavya32** [lovell/sharp#2462]
I made an npm package for distribution to my clients. The only  main issue is "sharp". I run install with --ignore-scripts. 
This causes sharp to run into error and I have to rebuild sharp.

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/install#common-problems

> The `npm install --ignore-scripts=false` flag must be used when npm has been configured to ignore installation scripts.

**Comment by bhavya32** [comment]
@lovell I know that. I just wanted to say shouldn't this be fixed? Actually I have to distribute puppeteer too. So i install it with ignore scripts. Otherwise, it downloads a 150mb chromium copy. Can you suggest some fix?

**Comment by lovell** [comment]
It is a requirement of `sharp` that its "install" script be run at `npm install` time to ensure the correct prebuilt binaries are made available.

https://github.com/lovell/sharp/blob/c10888e6fe38885e2a21ee9598b941001920fd22/package.json#L76

You could run this manually if you do not wish `npm` to do it for you.

**Comment by fragilehm** [comment]
> It is a requirement of `sharp` that its "install" script be run at `npm install` time to ensure the correct prebuilt binaries are made available.
> 
> https://github.com/lovell/sharp/blob/c10888e6fe38885e2a21ee9598b941001920fd22/package.json#L76
> 
> You could run this manually if you do not wish `npm` to do it for you.

Will the same be applied using yarn? Or do I still need to run this manually?

**Comment by lovell** [comment]
@fragilehm yarn and npm both run the `install` script by default at install time unless you explicitly prevent them from doing so.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
