### ISSUE TITLE
sharp error on node version 14 last LTS

### ISSUE THREAD

**Issue by 1omercohen** [lovell/sharp#2463]
this is the error when install npm i sharp

c:\projects\blabla\node_modules\sharp\src\stats.cc(130): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Projects\appraisal-client\node_modules\sharp\build\sharp.vcxproj]

**Comment by lovell** [comment]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

What is the output of running `npx envinfo --binaries --system`?

**Comment by 1omercohen** [comment]
when updating to the latest node version, try to update sharp packaged.
I see the documentation' nothing about this error, in node version 12 the sharp packaged working.
it is only because node version but do you support the latest node version?

**Comment by lovell** [comment]
What is the complete output of running `npm install --verbose sharp?`

**Comment by spyfly** [comment]
> What is the complete output of running `npm install --verbose sharp?`

Here you go: https://gist.github.com/spyfly/1fe1fd4b120c2dbedb49ccf8acde8c34

**Comment by lovell** [comment]
The Gist you posted and deleted suggests you are not using the latest version; please upgrade.

**Comment by alxch** [comment]
> npm install --verbose sharp



> What is the complete output of running `npm install --verbose sharp?`

npm install --verbose sharp
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', 'install', '--verbose', 'sharp' ]
npm info using npm@6.14.12
npm info using node@v14.16.1
npm verb npm-session 677ee0e5672a03a5
npm http fetch GET 304 https://registry.npmjs.org/sharp 740ms (from cache)
npm timing stage:loadCurrentTree Completed in 5451ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 35ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 2614ms
npm http fetch GET 200 https://registry.npmjs.org/fs-copy-file-sync 95ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color 200ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/detect-libc 492ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/npmlog 504ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/prebuild-install 510ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-get 513ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar 535ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/semver 546ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/nan 561ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-string 248ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/are-we-there-yet 155ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/console-control-strings 164ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/gauge 169ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/delegates 153ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/readable-stream 162ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/isarray 147ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/string_decoder 180ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/aproba 208ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/has-unicode 211ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/wide-align 222ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/strip-ansi 229ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/string-width 240ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/code-point-at 145ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-fullwidth-code-point 174ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/number-is-nan 148ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ansi-regex 152ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/github-from-package 195ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mkdirp-classic 218ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minimist 232ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/expand-template 245ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-abi 258ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/noop-logger 268ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-fs 274ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/napi-build-utils 283ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/which-pm-runs 442ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-concat 131ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 147ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mimic-response 133ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-stream 153ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/chownr 162ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-constants 164ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bl 173ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/buffer 161ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/inherits 169ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ieee754 123ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minipass 164ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minizlib 172ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/yallist 178ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-minipass 202ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 7981ms
npm timing stage:loadIdealTree Completed in 11616ms
npm timing stage:generateActionsToTake Completed in 329ms
npm verb correctMkdir /home/alex/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/alex/.npm/_locks/staging-0c27d8a57197fd93.lock for /home/alex/F/app-back/node_modules/.staging
npm timing audit submit Completed in 857ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 860ms
npm timing audit body Completed in 4ms
npm timing action:extract Completed in 1011ms
npm timing action:finalize Completed in 308ms
npm timing action:refresh-package-json Completed in 458ms
npm info lifecycle readable-stream@2.3.7~preinstall: readable-stream@2.3.7
npm info lifecycle inherits@2.0.4~preinstall: inherits@2.0.4
npm info lifecycle readable-stream@3.6.0~preinstall: readable-stream@3.6.0
npm info lifecycle chownr@1.1.4~preinstall: chownr@1.1.4
npm info lifecycle ieee754@1.2.1~preinstall: ieee754@1.2.1
npm info lifecycle buffer@5.7.1~preinstall: buffer@5.7.1
npm info lifecycle bl@4.1.0~preinstall: bl@4.1.0
npm info lifecycle mimic-response@2.1.0~preinstall: mimic-response@2.1.0
npm info lifecycle mkdirp-classic@0.5.3~preinstall: mkdirp-classic@0.5.3
npm info lifecycle napi-build-utils@1.0.2~preinstall: napi-build-utils@1.0.2
npm info lifecycle node-abi@2.26.0~preinstall: node-abi@2.26.0
npm info lifecycle minimist@1.2.5~preinstall: minimist@1.2.5
npm info lifecycle color-string@1.5.5~preinstall: color-string@1.5.5
npm info lifecycle simple-concat@1.0.1~preinstall: simple-concat@1.0.1
npm info lifecycle tar-stream@2.2.0~preinstall: tar-stream@2.2.0
npm info lifecycle tar-fs@2.1.1~preinstall: tar-fs@2.1.1
npm info lifecycle prebuild-install@5.3.6~preinstall: prebuild-install@5.3.6
npm info lifecycle color@3.1.3~preinstall: color@3.1.3
npm info lifecycle nan@2.14.2~preinstall: nan@2.14.2
npm info lifecycle semver@6.3.0~preinstall: semver@6.3.0
npm info lifecycle sharp@0.22.1~preinstall: sharp@0.22.1
npm timing action:preinstall Completed in 21ms
npm info linkStuff readable-stream@2.3.7
npm info linkStuff inherits@2.0.4
npm info linkStuff readable-stream@3.6.0
npm info linkStuff chownr@1.1.4
npm info linkStuff ieee754@1.2.1
npm info linkStuff buffer@5.7.1
npm info linkStuff bl@4.1.0
npm info linkStuff mimic-response@2.1.0
npm info linkStuff mkdirp-classic@0.5.3
npm info linkStuff napi-build-utils@1.0.2
npm info linkStuff node-abi@2.26.0
npm info linkStuff minimist@1.2.5
npm info linkStuff color-string@1.5.5
npm info linkStuff simple-concat@1.0.1
npm info linkStuff tar-stream@2.2.0
npm info linkStuff tar-fs@2.1.1
npm info linkStuff prebuild-install@5.3.6
npm verb linkBins [
npm verb linkBins   { 'prebuild-install': 'bin.js' },
npm verb linkBins   '/home/alex/F/app-back/node_modules/.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff color@3.1.3
npm info linkStuff nan@2.14.2
npm info linkStuff semver@6.3.0
npm verb linkBins [
npm verb linkBins   { semver: 'bin/semver.js' },
npm verb linkBins   '/home/alex/F/app-back/node_modules/sharp/node_modules/.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff sharp@0.22.1
npm timing action:build Completed in 39ms
npm info lifecycle readable-stream@2.3.7~install: readable-stream@2.3.7
npm info lifecycle inherits@2.0.4~install: inherits@2.0.4
npm info lifecycle readable-stream@3.6.0~install: readable-stream@3.6.0
npm info lifecycle chownr@1.1.4~install: chownr@1.1.4
npm info lifecycle ieee754@1.2.1~install: ieee754@1.2.1
npm info lifecycle buffer@5.7.1~install: buffer@5.7.1
npm info lifecycle bl@4.1.0~install: bl@4.1.0
npm info lifecycle mimic-response@2.1.0~install: mimic-response@2.1.0
npm info lifecycle mkdirp-classic@0.5.3~install: mkdirp-classic@0.5.3
npm info lifecycle napi-build-utils@1.0.2~install: napi-build-utils@1.0.2
npm info lifecycle node-abi@2.26.0~install: node-abi@2.26.0
npm info lifecycle minimist@1.2.5~install: minimist@1.2.5
npm info lifecycle color-string@1.5.5~install: color-string@1.5.5
npm info lifecycle simple-concat@1.0.1~install: simple-concat@1.0.1
npm info lifecycle tar-stream@2.2.0~install: tar-stream@2.2.0
npm info lifecycle tar-fs@2.1.1~install: tar-fs@2.1.1
npm info lifecycle prebuild-install@5.3.6~install: prebuild-install@5.3.6
npm info lifecycle color@3.1.3~install: color@3.1.3
npm info lifecycle nan@2.14.2~install: nan@2.14.2
npm info lifecycle semver@6.3.0~install: semver@6.3.0
npm info lifecycle sharp@0.22.1~install: sharp@0.22.1

> sharp@0.22.1 install /home/alex/F/app-back/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /home/alex/.npm/_libvips/libvips-8.7.4-linux-x64.tar.gz
prebuild-install info begin Prebuild-install version 5.3.6
prebuild-install info looking for cached prebuild @ /home/alex/.npm/_prebuilds/dadf5b-sharp-v0.22.1-node-v83-linux-x64.tar.gz
prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.22.1/sharp-v0.22.1-node-v83-linux-x64.tar.gz
prebuild-install http 404 https://github.com/lovell/sharp/releases/download/v0.22.1/sharp-v0.22.1-node-v83-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=14.16.1 runtime=node arch=x64 libc= platform=linux)
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild'
gyp verb cli ]
gyp info using node-gyp@5.1.0
gyp info using node@14.16.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - "python" is not in PATH or produced an error
gyp verb find Python checking if "python2" can be used
gyp verb find Python - executing "python2" to get executable path
gyp verb find Python - executable path is "/usr/bin/python2"
gyp verb find Python - executing "/usr/bin/python2" to get version
gyp verb find Python - version is "2.7.18"
gyp info find Python using Python version 2.7.18 found at "/usr/bin/python2"
gyp verb get node dir no --target version specified, falling back to host node version: 14.16.1
gyp verb command install [ '14.16.1' ]
gyp verb install input version string "14.16.1"
gyp verb install installing version: 14.16.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 14.16.1
gyp verb build dir attempting to create "build" dir: /home/alex/F/app-back/node_modules/sharp/build
gyp verb build dir "build" dir needed to be created? /home/alex/F/app-back/node_modules/sharp/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/alex/F/app-back/node_modules/sharp/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/alex/F/app-back/node_modules/sharp/config.gypi
gyp verb common.gypi checking for gypi file: /home/alex/F/app-back/node_modules/sharp/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/alex/F/app-back/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/alex/.cache/node-gyp/14.16.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/alex/.cache/node-gyp/14.16.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/alex/.cache/node-gyp/14.16.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/alex/F/app-back/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/alex/.cache/node-gyp/14.16.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/alex/F/app-back/node_modules/sharp/build'
  touch Release/obj.target/libvips-cpp.stamp
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/alex/.cache/node-gyp/14.16.1/include/node -I/home/alex/.cache/node-gyp/14.16.1/src -I/home/alex/.cache/node-gyp/14.16.1/deps/openssl/config -I/home/alex/.cache/node-gyp/14.16.1/deps/openssl/openssl/include -I/home/alex/.cache/node-gyp/14.16.1/deps/uv/include -I/home/alex/.cache/node-gyp/14.16.1/deps/zlib -I/home/alex/.cache/node-gyp/14.16.1/deps/v8/include -I../node_modules/nan -I../vendor/include -I../vendor/include/glib-2.0 -I../vendor/lib/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-deprecated-declarations -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/common.o.d.raw   -c -o Release/obj.target/sharp/src/common.o ../src/common.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/alex/.cache/node-gyp/14.16.1/include/node -I/home/alex/.cache/node-gyp/14.16.1/src -I/home/alex/.cache/node-gyp/14.16.1/deps/openssl/config -I/home/alex/.cache/node-gyp/14.16.1/deps/openssl/openssl/include -I/home/alex/.cache/node-gyp/14.16.1/deps/uv/include -I/home/alex/.cache/node-gyp/14.16.1/deps/zlib -I/home/alex/.cache/node-gyp/14.16.1/deps/v8/include -I../node_modules/nan -I../vendor/include -I../vendor/include/glib-2.0 -I../vendor/lib/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-deprecated-declarations -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/metadata.o.d.raw   -c -o Release/obj.target/sharp/src/metadata.o ../src/metadata.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/alex/.cache/node-gyp/14.16.1/include/node -I/home/alex/.cache/node-gyp/14.16.1/src -I/home/alex/.cache/node-gyp/14.16.1/deps/openssl/config -I/home/alex/.cache/node-gyp/14.16.1/deps/openssl/openssl/include -I/home/alex/.cache/node-gyp/14.16.1/deps/uv/include -I/home/alex/.cache/node-gyp/14.16.1/deps/zlib -I/home/alex/.cache/node-gyp/14.16.1/deps/v8/include -I../node_modules/nan -I../vendor/include -I../vendor/include/glib-2.0 -I../vendor/lib/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-deprecated-declarations -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/stats.o.d.raw   -c -o Release/obj.target/sharp/src/stats.o ../src/stats.cc
../src/stats.cc: In member function ‘virtual void StatsWorker::HandleOKCallback()’:
../src/stats.cc:130:37: error: no matching function for call to ‘v8::Array::Set(int&, v8::Local<v8::Object>&)’
  130 |         channels->Set(i, channelStat);
      |                                     ^
In file included from /home/alex/.cache/node-gyp/14.16.1/include/node/node.h:67,
                 from ../src/stats.cc:19:
/home/alex/.cache/node-gyp/14.16.1/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/alex/.cache/node-gyp/14.16.1/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/alex/.cache/node-gyp/14.16.1/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/alex/.cache/node-gyp/14.16.1/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
make: *** [sharp.target.mk:138: Release/obj.target/sharp/src/stats.o] Error 1
make: Leaving directory '/home/alex/F/app-back/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.8.0-50-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/alex/F/app-back/node_modules/sharp
gyp ERR! node -v v14.16.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm verb lifecycle sharp@0.22.1~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.22.1~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/alex/F/app-back/node_modules/sharp/node_modules/.bin:/home/alex/F/app-back/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
npm verb lifecycle sharp@0.22.1~install: CWD: /home/alex/F/app-back/node_modules/sharp
npm info lifecycle sharp@0.22.1~install: Failed to exec install script
npm timing action:install Completed in 25508ms
npm verb unlock done using /home/alex/.npm/_locks/staging-0c27d8a57197fd93.lock for /home/alex/F/app-back/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 921ms
npm timing stage:runTopLevelLifecycles Completed in 46782ms
npm WARN @ljharb/eslint-config@16.0.0 requires a peer of eslint@^6.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN feather-test@0.0.0 No repository field.
npm WARN feather-test@0.0.0 No license field.
npm WARN The package nyc is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

npm verb stack Error: sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:315:20)
npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:315:20)
npm verb stack     at maybeClose (internal/child_process.js:1048:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm verb pkgid sharp@0.22.1
npm verb cwd /home/alex/F/app-back
npm verb Linux 5.8.0-50-generic
npm verb argv "/usr/bin/node" "/usr/bin/npm" "install" "--verbose" "sharp"
npm verb node v14.16.1
npm verb npm  v6.14.12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.22.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 49690ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alex/.npm/_logs/2021-05-11T19_29_15_633Z-debug.log
