### ISSUE TITLE
Render text to image

### ISSUE THREAD

**Issue by StringKe** [lovell/sharp#2465]
What are you trying to achieve?
Processes text like a browser, with automatic line breaks.

Have you searched for similar feature requests?
Yes, no relevant results were found.

What would you expect the API to look like?
```
sharp({
  create: {
    width: 300,
    height: 200,
    channels: 4,
    background: { r: 255, g: 0, b: 0, alpha: 0.5 }
  }
}).text('is very long text , this width max width is 1000',{fontSize:'24px',font:'arial'}).png()
```

What alternatives have you considered?
I know that there are some image libraries that can handle such as [pango](https://pango.gnome.org/) it is a solution for linux image interface

Is there a sample image that helps explain?
none

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/512
