### ISSUE TITLE
Non-integer value for left of 0.4541015625

### ISSUE THREAD

**Issue by prasannavsa** [lovell/sharp#2468]
Getting issue when using non-integer values 

My values are here 
        {
                "Width": 0.1533203125,
                "Height": 0.1533203125,
                "Left": 0.4541015625,
                "Top": 0.7255859375
            }

**Comment by lovell** [comment]
Hi, this is not a complete code sample, but I guess you're using extract

https://sharp.pixelplumbing.com/api-resize#extract

>  "...describes the region to extract using integral pixel values"

**Comment by prasannavsa** [comment]
Here is the example that I am using : 
const sharp = require("sharp");
let left = 0.4541015625;
let top = 0.7255859375;
let width = 0.1533203125;
let height = 0.1533203125;
let output="output.jpg";
sharp("./celebrities.jpg")
  .extract({ left: left, top: top, width: width, height: height })
  .toFile(output, function(err) {
    // Extract a region of the input image, saving in the same format.
  });

Response: Error: Non-integer value for left of 0.4541015625

**Comment by lovell** [comment]
Please note the documentation says "integral pixel values", so the properties are expected to be in pixels and have integral (integer, whole number) values.

**Comment by prasannavsa** [comment]
Thanks for your help.
