### ISSUE TITLE
toFormat: uppercase extensions not supported

### ISSUE THREAD

**Issue by emirkum** [lovell/sharp#2471]
I'm receiving error with JPG (uppercase of jpg) image extension. This extension should be supported right?

ERROR	Error resizing:  Error: Expected one of: heic, heif, jpeg, jpg, png, raw, tiff, webp for format but received JPG of type string
    at Object.invalidParameterError (/var/task/node_modules/sharp/lib/is.js:101:10)
    at Sharp.toFormat (/var/task/node_modules/sharp/lib/output.js:168:14)

**Comment by lovell** [comment]
Hi, the `toFormat` method currently expects lower case so you'll need to add a call to `toLowerCase()` in your code.

Happy to accept a PR that adds this call internally - see https://github.com/lovell/sharp/blob/master/lib/output.js#L175

**Comment by lovell** [comment]
Added via https://github.com/lovell/sharp/pull/2581 - v0.27.2 now available.
