### ISSUE TITLE
Sharp resize function doesn't actually resize

### ISSUE THREAD

**Issue by jamsmd** [lovell/sharp#2476]
After resize image dimensions remain the same..

What are the steps to reproduce?

```
const width = 100;
const height = 100;

const metadata = await artImage.metadata();
console.log(metadata);  // metadata.width: 300, metadata.height: 300 

await artImage.resize(width, height);

const newMetadata = await artImage.metadata();
console.log(newMetadata);  // newMetadata.width: 300, newMetadata.height: 300 
```
What is the expected behaviour?
after resize `newMetadata.height` and `newMetadata.width` should be `100`

Are you able to provide a sample image that helps explain the problem?
Any png.

Env:
```
sharp v0.25.4
node v12.14.1
npm v6.13.4
```

**Comment by lovell** [comment]
Hi, you'll need to generate output via [toBuffer](https://sharp.pixelplumbing.com/api-output#tobuffer).
```diff
- await artImage.resize(width, height);
- const newMetadata = await artImage.metadata();
+ const newImage = await artImage.resize(width, height).toBuffer();
+ const newMetadata = await newImage.metadata();
```

**Comment by jamsmd** [comment]
> Hi, you'll need to generate output via [toBuffer](https://sharp.pixelplumbing.com/api-output#tobuffer).
> 
> ```diff
> - await artImage.resize(width, height);
> - const newMetadata = await artImage.metadata();
> + const newImage = await artImage.resize(width, height).toBuffer();
> + const newMetadata = await newImage.metadata();
> ```

Hi , thank you for your quick response!

I did work before like this? Has anything changed recently?

**Comment by lovell** [comment]
I made a mistake in my example, sorry:
```diff
- const newMetadata = await newImage.metadata();
+ const newMetadata = await sharp(newImage).metadata();
```

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
