### ISSUE TITLE
Project with sharp@0.26.3 and favicons@6.2.0 - conflicts with libvips

### ISSUE THREAD

**Issue by nstuyvesant** [lovell/sharp#2478]
If I do a build (which uses sharp), I get this error:
On macOS 11.0.1, my project uses sharp 0.26.3 and favicons 6.2.0 (which uses sharp 0.25.2). When I try to build the site, I get an error...

> dyld: lazy symbol binding failed: Symbol not found: _g_once_impl
>   Referenced from: /Users/nates/dev/shy/node_modules/sharp/build/Release/sharp.node
>   Expected in: /Users/nates/dev/shy/node_modules/favicons/node_modules/sharp/build/Release/../../vendor/lib/libvips.42.dylib
> 
> dyld: Symbol not found: _g_once_impl
>   Referenced from: /Users/nates/dev/shy/node_modules/sharp/build/Release/sharp.node
>   Expected in: /Users/nates/dev/shy/node_modules/favicons/node_modules/sharp/build/Release/../../vendor/lib/libvips.42.dylib
> 

If I go to the directory for favicons and do a...
> npm install --build-from-source sharp@0.26.3

go back to my project directory and do another build, the problem goes away.

Seems the latest version of sharp expects the libvips.42.dylib with symbols and the one provided by the older version of sharp used by favicons doesn't have it. Guess it might be defaulting to want to use libvips.42.dylib in the favicons' sharp folder instead of the one that comes with sharp because of alphabetic order?

Should this be logged here or at the repo for favicons?

**Comment by lovell** [comment]
Cross-posted at https://github.com/itgalaxy/favicons/issues/324 - please submit a PR to favicons to upgrade sharp. See also #2337

**Comment by nstuyvesant** [comment]
Thanks - will do.
