### ISSUE TITLE
Metadata, why does this image not get density?

### ISSUE THREAD

**Issue by zhangbowy** [lovell/sharp#2479]
![image](https://user-images.githubusercontent.com/33514252/101709519-960a6300-3aca-11eb-94dd-bc8933243690.png)

![image](https://user-images.githubusercontent.com/33514252/101709639-cf42d300-3aca-11eb-81f0-3dbbae8e75b2.png)

How can I get the density?

sharp 0.25.2

**Comment by lovell** [comment]
Hi, the attached image is a PNG but the screenshot suggests a JPEG.

Please note that not all image formats contain a `density`.

https://sharp.pixelplumbing.com/api-input#metadata

> density: Number of pixels per inch (DPI), if present

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
