### ISSUE TITLE
bamboo Builds failing with error message Failed at the sharp@0.26.3 install script

### ISSUE THREAD

**Issue by shubhraj** [lovell/sharp#2480]
I am seeing the following error in the build logs :

npm ERR! code ELIFECYCLE
--
 npm ERR! errno 1
 npm ERR! sharp@0.26.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) \|\| (node-gyp rebuild && node install/dll-copy)`
 npm ERR! Exit status 1
 npm ERR!
 npm ERR! Failed at the sharp@0.26.3 install script

**Comment by lovell** [comment]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?

If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

What is the output of running `npx envinfo --binaries --system`?

**Comment by shubhraj** [comment]
@lovell Thanks for the quick reply! the issue was due to the node version, I have upgraded the bamboo plan to use node v10.x.x, and it's working now.
Thank you!
