### ISSUE TITLE
Metadata + PassThrough

### ISSUE THREAD

**Issue by 99uno** [lovell/sharp#2483]
I want to stream sharp output into PassThrough and calculate metadata at same time. I have a source code that is working fine locally, in some Amazon servers but it's not working for processing large images in a specific Amazon server (but it works for small images).
I found that when it doesn't work, the problem is that inside the metadata function, the finish event is not being triggered. My main concern is to discover why it's always working except for large images in one EC2.

https://pastebin.com/pLGLi5N6

**Comment by lovell** [comment]
Please provide a complete, minimal, standalone code sample (not a screenshot) and image that reproduces this.

**Comment by 99uno** [comment]
> Please provide a complete, minimal, standalone code sample (not a screenshot) and image that reproduces this.

https://pastebin.com/pLGLi5N6

**Comment by lovell** [comment]
Thanks for a partial code sample, it looks like it has other dependencies and cannot be run standalone (and doesn't have an image). Please can you try to make a more minimal code sample that can be run standalone e.g. `node script.js`, perhaps as a separate repo, that allows someone else to reproduce the problem.

**Comment by 99uno** [comment]
> Thanks for a partial code sample, it looks like it has other dependencies and cannot be run standalone (and doesn't have an image). Please can you try to make a more minimal code sample that can be run standalone e.g. `node script.js`, perhaps as a separate repo, that allows someone else to reproduce the problem.

https://pastebin.com/2YGF4Wqv

I removed child_process but I cannot remove stream dependency because otherwise my issue could not be reproduced.

**Comment by lovell** [comment]
Please can you provide a sample image that fails.

**Comment by 99uno** [comment]
> Please can you provide a sample image that fails.

https://drive.google.com/file/d/1GuGgeBMRklbqKpBsxA281vYOdnVGO4vm/view?usp=sharing

Remember that it's working for example on localhost. I discover the issue on an EC2 micro with the last Debian version

**Comment by lovell** [comment]
Some of the Stream objects created in this code appear to lack error handling. Adding this should help you find out what's going wrong, perhaps using Node.js's `pipeline` function. https://nodejs.org/api/stream.html#stream_stream_pipeline_streams_callback

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
