### ISSUE TITLE
Is Sharp stream a pure stream?

### ISSUE THREAD

**Issue by GeorgianStan** [lovell/sharp#2484]
## What are you trying to achieve?

To stream a resized file as an HTTP response
It looks like the request starts to drain after the image was processed and that's how the behavior feels like in the browser as well.
Shouldn't the image be received as it is processed?

## Have you searched for similar questions?
Yes

## Are you able to provide a minimal, standalone code sample that demonstrates this question?
```
const fs = require("fs");
const sharp = require("sharp");
const app = require("express")();

app.get("/", (req, res) => {
  const readStream = fs.createReadStream("image.jpg");

  const roundedCornerResizer = sharp().jpeg({
    quality: 100,
    progressive: true,
  });

  roundedCornerResizer.on("end", () => {
    console.timeEnd("e");
  });

  res.on("drain", () => {
    console.timeEnd("d");
  });

  console.time("e");
  console.time("d");

  readStream.pipe(roundedCornerResizer).pipe(res);
});

app.listen(3000, () => {
  console.log("app up");
});
```

## Are you able to provide a sample image that helps explain the question?

![image2](https://user-images.githubusercontent.com/25796932/102111843-8c248f00-3e3f-11eb-898c-b083cc5b848f.jpg)

**Comment by lovell** [comment]
Hi, did you see the discussion at #179?

**Comment by GeorgianStan** [comment]
Hi. From my understanding: this is not yet possible but is something that is taken in consideration for future development?

**Comment by lovell** [comment]
Yes, please subscribe to #179 for any updates.
