### ISSUE TITLE
Convert multi-page TIFF to other format

### ISSUE THREAD

**Issue by blangsmgi** [lovell/sharp#2486]
What are you trying to achieve?
I want to convert a multi-page TIFF (from a fax or scanner) into one image file per page (JPG or PNG).  I didn't find any examples in the API documentation that seem to show this. I am looking for an example of how to process each page of a multi-page TIFF into an individual image. If there is an example in the documentation that I've missed, please point me in the right direction. If there isn't, can someone please help me figure this out?

Have you searched for similar questions?
I have searched for issues with multipage and only found [Enhancement: improve animated/multipage image resizing #2275](https://github.com/lovell/sharp/issues/2275) which doesn't appear to be related at first glance.

Are you able to provide a minimal, standalone code sample that demonstrates this question?

```
const sharp = require("sharp");
// sample.tif and sample2.tif are multipage TIF files
// these examples output a jpg file for the first page only
sharp("sample.tif").toFile("sample.jpg", function (err) {});
sharp("sample2.tif").toFile("sample2.jpg", function (err) {});
```

Are you able to provide a sample image that helps explain the question?
Two sample TIF files can be found in the attached ZIP archive.
[sampletifs.zip](https://github.com/lovell/sharp/files/5698149/sampletifs.zip)

**Comment by lovell** [comment]
Hi, did you see the `page` option of the constructor?

https://sharp.pixelplumbing.com/api-constructor

```js
sharp("sample.tif", { page: 2 }).toFile("page2.jpg");
```

**Comment by blangsmgi** [comment]
Thank you. This helped me with my project.

**Comment by crapthings** [comment]
pages: -1 seems doesn't work.
should i use for loop to get multiple images?
