### ISSUE TITLE
After resizing, the top and left edges of the image will be deformed

### ISSUE THREAD

**Issue by gaoshun** [lovell/sharp#2487]
my code
```javascript
sharp(imgPath).resize(width).png({ quality }).toFile(distFile)
```

but after resizing, the top and left edges of the image will be deformed
Original image:
![](https://raw.githubusercontent.com/gaoshun/markdown-pics/master/imgs/source.png)
After resize:
![](https://raw.githubusercontent.com/gaoshun/markdown-pics/master/imgs/target.png)

You can see distortion on the left and top edges

Can anyone help me!
Thanks

**Comment by lovell** [comment]
Hi, this looks like the same problem as #2408, which relates to a rounding error in libvips - please subscribe to that issue for updates.
