### ISSUE TITLE
Affine chained with extract does not seem to work

### ISSUE THREAD

**Issue by casperno** [lovell/sharp#2488]
With 
```
let s = sharp(source); // 1920x1080px image
s.affine([
                    [2, 0],
                    [0, 2],
                ])
.extract({
                width: 1000,
                height: 1000,
                left:0,
                top: 0,
            })
toFile('out/affine_test.jpg')
```

I get a jpg that is 2000x2000px. The extracted area is top left as expected, but twice as big.

Is this a bug, or am I not understanding Sharp correctly?

**Comment by lovell** [comment]
Hi, you'll need to split this into two pipelines, something like:
```js
sharp(source)
  .affine([
    [2, 0],
    [0, 2],
  ])
  .toBuffer()
  .then((data) =>
    sharp(data)
      .extract({
        width: 1000,
        height: 1000,
        left: 0,
        top: 0,
      })
      .toFile("out.jpg")
  );
```

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by casperno** [comment]
Hi, 

Sorry for not responding before. 
Thanks, your answer is clarifying. But I still can't see when you need to split into a new pipeline. 
I'm using Sharp to generate frames for video, so speed is of the essens — another pipe seems to double processing time.
