### ISSUE TITLE
Reducing overall package size

### ISSUE THREAD

**Issue by chronoDave** [lovell/sharp#2489]
**What are you trying to achieve?**

Reducing the overall (production) package size

**Have you searched for similar feature requests?**

[Yes, I have](https://github.com/lovell/sharp/issues?q=label%3Aenhancement+package+size)

**What would you expect the API to look like?**

Currently, `sharp` requires **68** external packages (70 excluding `.bin` and `.yarn-integrity`). This can be reproduced using `yarn add sharp --prod`
 
 ![node_modules](https://i.imgur.com/Lft6BNK.png)

Packages that can (probably) be moved and / or replaced

- `array-flatten`: Can be replaced by the native Node [`Array.flat()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat) (requires node version >`11.0.0`)
- `detect-libc`: Not entirely sure if this package is required to _run_ `sharp`, but if this is the case, this could be moved to `devDependencies`
- `node-addon-api`: Not entirely sure if this package is required to _run_ `sharp`, but if this is the case, this could be moved to `devDependencies`. From my understanding, this package is only used to build native addons (such as `sharp`)
- `npmlog`: It's a logger, this probably should be moved to `devDepedencies`.
- `prebuild-install`: From my understanding, this package is used to install prebuild binaries, which probably works together with `node-addon-api`. Probably also should be moved to `devDepedencies`, if possible.
- `semver`: Package version parser, used by `libvips.js`. From my understanding, also used to install `sharp`, so probably should be a `devDepedency`
- `simple-get`: This can be replaced by using Node's built-in `http`:

```JS
libvips.js 104

const http = require('http')

http.get(url, { agent: agent() }, function (err, response) {
  // etc.
}
```

- `tar-fs`: This _can_ be replaced by using bash (`tar xzvf <tar.gz>`), but understandable if it must be a JS script. It is possible to execute this command using `child_process`, however. Even still, this probably also should be moved to `devDepedencies`
- `tunnel-agent`: Not entirely sure what this package does, but seems part of the installation toolchain, so can probably be moved to `devDepedencies`

If my assumptions are correct, this means that `sharp` could possibly be a 0 dependency package, which would be amazing!

**What alternatives have you considered?**

I've considered forking the package and removing the dependencies myself, but it's not that easy to simply remove dependencies without fully understanding how `sharp` uses it. If I understand the code correctly, most (if not all) of these dependencies are used to install and build `sharp`, which probably aren't mandatory when running `sharp`, if that makes sense?

**Motivation**

I'm currently using `sharp` in my own [project](https://github.com/chronoDave/Doombox/blob/5e8cf0e40e4578338d5c00aa2ccad0f5e63a093e/.electronconfig.js#L22) combined with `webpack` and `electron`. When building my application, I currently need to bundle all `sharp`'s packages to make it function, which adds (probably) unnecessary code to the application. 

I'd love to help out if needed!

**Comment by lovell** [comment]
This was asked previously in #1417

All of the modules listed in `dependencies` are currently required at either install time or runtime. As far as I know, there's no reliable way to separate these two concepts in `npm`. Perhaps you could delete any install time dependencies in your own packaging scripts?

**Comment by chronoDave** [comment]
> Perhaps you could delete any install time dependencies in your own packaging scripts?

Thank you for the recommendation. Looking at the `lib` folder, it's indeed possible to not bundle some of the packages mentioned above. Seems the only dependencies unable to be left out from the package are `semver` and `detect-libc`, as they are used by `libvips` and `platform` respectively (where `libvips` is required by `constructor`, which is required by `index`).

**Comment by chronoDave** [comment]
Managed to cut down the depedencies to just 10, including sharp itself. Many thanks for the suggestion!
