### ISSUE TITLE
Is it possible to apply the threshold operation specifically to the alpha channel?

### ISSUE THREAD

**Issue by GrumpyPirate** [lovell/sharp#2493]
Hello!

**What are you trying to achieve?**
I'm trying to apply a threshold operation specifically to the alpha channel of PNG images, with the intention of removing feathered edges after downsizing. The images themselves are pixellated sprites, that when resized down (e.g. with the bicubic algorithm), then posess pixels around the edge that have transparency. These translucent pixels need to either have their alpha increased to 100%, or decreased to 0%, basically, ensuring 'hard' edges around sprites.

I'm in the process of migrating an existing `gm` implementation of this over to `sharp`, and while I'm aware that sharp provides a `threshold` operator and the means to extract specific channels from an image, I've so far been unsuccessful in combining them, and I'm unsure of whether this is actually currently possible with the library.

The gm equivalent would be a 50% threshold operator on the opacity channel, e.g. 
```javascript
imageFile.operator('Opacity', 'Threshold', 50, '%'),
```

Does the same feature exist in sharp currently?

**Have you searched for similar questions?**
I have, and my results have turned up empty. I'm unsure whether I'm using the right terminology, which may be the issue.

**Are you able to provide a minimal, standalone code sample that demonstrates this question?**
I'm currently trying to use a 2-step process with sharp by 1) Extracting the alpha channel from a source image, 2) Apply a threshold operation on this, and then 3) Merge this back with the original image:
```javascript
// Extract the alpha channel, threshold it
const alphaChannel = await origImage
  .clone()
  .extractChannel('alpha')
  .threshold()
  .toBuffer();

// Combine it with original image
const newImageBuffer = await origImage.joinChannel(alphaChannel).toBuffer();
```

But it doesn't achieve the desired effect. I imagine I'm probably doing something wrong.

**Are you able to provide a sample image that helps explain the question?**
Absolutely. Here's an example source image, before resizing:
**Source 128x128 image**
![trowel](https://user-images.githubusercontent.com/6855824/102740928-ded2df00-4348-11eb-8694-e74e5aae1837.png)

**Example of feathering when downsized with `sharp` attempt**
<img width="668" alt="image" src="https://user-images.githubusercontent.com/6855824/102741142-76383200-4349-11eb-80f6-4cb9dac94131.png">

**Desired effect, achieved with current `gm` implementation**
<img width="659" alt="image" src="https://user-images.githubusercontent.com/6855824/102741290-e5158b00-4349-11eb-998b-b01350b05a5f.png">

**Comment by lovell** [comment]
Hi, you'll need to split this up into two pipelines to ensure the alpha is single channel (rather than sRGB), something like the following (untested):

```js
const alpha = await origImage
  .extractChannel('alpha')
  .toColourspace('b-w')
  .toBuffer();
const alphaThreshold = await alpha
  .threshold()
  .toBuffer();
```

https://sharp.pixelplumbing.com/api-channel#extractchannel

**Comment by GrumpyPirate** [comment]
Thank you, I'll give that a try!

**Comment by GrumpyPirate** [comment]
For reference, I got this to work in the end with your guidance, so a huge thank you.

Here's the end solution, which is likely more verbose than necessary:
```typescript
// Extract the alpha channel, threshold it
const alphaChannel = await origImage
  .clone()
  .extractChannel('alpha')
  .toColourspace('b-w')
  .toBuffer();
const alphaChannelThresholded = await sharp(alphaChannel).threshold().toBuffer();

// Combine it with original image
const newImageWithoutAlpha = await origImage.removeAlpha().toBuffer();
const newImageWithAlpha = await sharp(newImageWithoutAlpha)
  .joinChannel(alphaChannelThresholded)
  .toBuffer();
```
