### ISSUE TITLE
Some JPEG images are not converted to AVIF

### ISSUE THREAD

**Issue by adityapatadia** [lovell/sharp#2496]
![salvation-army-578x280](https://user-images.githubusercontent.com/1086617/102966695-6588e700-4516-11eb-868d-1d3236f86f62.jpg)

What are the steps to reproduce?

Convert this image to AVIF: https://www.kidsmust.com/wp-content/uploads/2020/12/salvation-army-578x280.jpg
It gives error "source: bad seek to 21875". This only happens on some systems.

What is the expected behaviour?

Image should be converted to AVIF.

What is the output of running `npx envinfo --binaries --system`?

```
  System:
    OS: Linux 4.14 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (4) x64 AMD EPYC 7R32
    Memory: 3.44 GB / 7.69 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm

```

**Comment by lovell** [comment]
Hi, this looks like https://github.com/libvips/libvips/issues/1901. Please ensure you are using v0.27.0 of sharp.

**Comment by adityapatadia** [comment]
I am running 0.27.0. This error still comes.

**Comment by adityapatadia** [comment]
I should mention, I am not using bundled libvips but I am building my own. I use 8.10.5, libheif 1.10.0. RAV1E 0.3.4.

**Comment by lovell** [comment]
Are you able to reproduce this problem using libvips at the command line independently of sharp? Are you able to provide a Dockerfile with the complete environment in which it occurs to enable someone else to reproduce it?

**Comment by adityapatadia** [comment]
I have figured out that simply swapping rav1e with libaom solves the issue. When rav1e is used, this error is raised.

**Comment by adityapatadia** [comment]
Problem is that we can't use libaom as it's too slow. I will see how can I reproduce but you can also try by using RAV1E. See if you can re-produce.

**Comment by adityapatadia** [comment]
I have removed `RUSTFLAGS="-C target-cpu=broadwell"` and everything started working!

**Comment by adityapatadia** [comment]
My bad, nothing is solved. There is still some issue. I am trying to give you code to re-produce.

**Comment by adityapatadia** [comment]
> Are you able to reproduce this problem using libvips at the command line independently of sharp? Are you able to provide a Dockerfile with the complete environment in which it occurs to enable someone else to reproduce it?

I tried to convert file with command line `vips copy salvation-army-578x280.jpg test.avif`. There is no error raised but the resultant image can't be opened in chrome so I suppose it's not valid AVIF file.

**Comment by adityapatadia** [comment]
Here is sample dockerfile: https://gist.github.com/adityapatadia/4875a2d2f1c7febe11c1aa53e488853d

**Comment by adityapatadia** [comment]
Again my bad, when this same image is converted to AVIF with this command, it works perfectly fine: `vips heifsave --compression av1 salvation-army-578x280.jpg test.avif`

**Comment by adityapatadia** [comment]
@lovell I am finding hard time to re-produce this on another linux machine as well. This problem only comes in production env with sharp. As you can see, even vips command line works fine. Can you tell me any other way to debug it? I can provide you everything you need.

**Comment by adityapatadia** [comment]
One pattern I noticed is when overlay is used with avif, this issue almost always comes.

**Comment by adityapatadia** [comment]
This issue was resolved when I created binaries by using sharp-libvips repo.

**Comment by kleisauke** [comment]
Are you sure it could be reproduced with the above JPEG image? I noticed that your [copied sharp-libvips repo](https://github.com/gumlet/sharp-libvips/) does not support AVIF (or HEIC) _decode_, so it's probably the same (or similar) problem as https://github.com/libvips/libvips/issues/1901 which only occurred when decoding AVIF/HEIC images.

**Comment by adityapatadia** [comment]
I will add HEIF decoding as well. Let's see. I am sure, it could be reproduced with single JPEG image.

**Comment by adityapatadia** [comment]
> so it's probably the same (or similar) problem as [libvips/libvips#1901](https://github.com/libvips/libvips/issues/1901) which only occurred when decoding AVIF/HEIC images.

You were correct, when I added decoder, the issue went away. It's still strange to see why it happened with single JPEG image.
