### ISSUE TITLE
image input size limit

### ISSUE THREAD

**Issue by anandthakker** [lovell/sharp#250]
Fantastic library--thanks for creating/maintaining!

I'm using it to resize some very large TIFs (> 1.5-2 billion pixels) and running into the input size limit.  I'm able to use `limitInputPixels()` to increase the pixel limit, but the highest value that works for me is `2^32 - 1 = 2147483647`.  My undersatnding is that this is because on the C++ side, the limit is read as a 32-bit integer [here](https://github.com/lovell/sharp/blob/01435977dea515d2fd371f444e4062c4a65cc4ff/src/pipeline.cc#L1149).  How feasible would it be to allow a larger value here?

**Comment by lovell** [comment]
Hello Anand, your understanding is correct. At the moment we're using 32-bit signed for which the max is 2^31-1.

It should be a one-line change (plus tests, of course) to switch this to 32-bit unsigned via `->Uint32Value()`, allowing 2^32-1 = 4294967295.

Alternatively/additionally, we could modify `limitInputPixels` to also accept a boolean, where `false` = remove limit and `true` = reset to default limit.

(The limit exists to prevent resource hogging - see #115 for the background - although you do have to trust the image metadata.)

**Comment by anandthakker** [comment]
Thanks for the quick response, @lovell.   I like the boolean option approach here, since, if someone's getting up above 2^31 pixels, it seems pretty likely that, like me, they actually just want no upper limit.  I'll try that out; happy to submit it back as a PR if you're interested.

**Comment by lovell** [comment]
Great, PR gladly accepted, thank you for your kind offer!

**Comment by kentongray** [comment]
@anandthakker did you have any luck with a pull request? I'd love to have this feature

**Comment by anandthakker** [comment]
Ah, I unfortunately got pretty swamped soon after this, so I never did get
a chance to work up a PR. Sorry :-(

**Comment by kentongray** [comment]
@anandthakker no problem I know how that is! I'll make a stab at it unless @lovell has any other thoughts :godmode:

**Comment by lovell** [comment]
@kentongray Thank you, go for it! Feel free to post questions here if you need help.

**Comment by mitselek** [comment]
I will do it unless I change my mind!

**Comment by lovell** [comment]
This feature will be in v0.14.1, thanks @kentongray.

**Comment by lovell** [comment]
v0.14.1 now available via npm, thanks both for your help with this.
