### ISSUE TITLE
tiff float cast

### ISSUE THREAD

**Issue by randyridge** [lovell/sharp#2500]
I noticed that in pipeline.cc when saving tiffs to a buffer the following code is run:

```
// Cast pixel values to float, if required
if (baton->tiffPredictor == VIPS_FOREIGN_TIFF_PREDICTOR_FLOAT) {
  image = image.cast(VIPS_FORMAT_FLOAT);
 }
```

However, saving tiff to a file does not have the same cast applied.  Is this by design?

**Comment by lovell** [comment]
No, this looks like a bug, thanks for reporting this. Happy to accept a PR if you're able.

**Comment by lovell** [comment]
v0.27.1 now available, thanks for the PR.
