### ISSUE TITLE
Metadata for AVIF, format returned as 'heif'

### ISSUE THREAD

**Issue by tomgallagher** [lovell/sharp#2504]
Using Sharp 27, which now supports AVIF and is great. Thanks!

Downloading this image and then extracting metadata with `sharp(inputavif).metadata()`

> http://download.opencontent.netflix.com.s3.amazonaws.com/AV1/Chimera/AVIF/Chimera-AV1-10bit-1280x720-2380kbps-100.avif

The format returned is `heif` as that's the encoder used by libvips.

Is it true that this metadata format will be returned for both `avif` and `heic` images?

If so, it's not going to be possible to use the metadata to distinguish between the two, one of which is patent-encumbered and cannot be processed without globally installed libvips, as I understand it.

Would it be possible for the libvips metadata to return `avif` as the format, for consistency with mime type headers and Sharp output format strings?

**Comment by lovell** [comment]
libvips v8.11.0 will contain logic to expose the `heif-compression` metadata - see https://github.com/libvips/libvips/pull/1850

**Comment by tomgallagher** [comment]
Not sure if this is related, but `metadata` throws error for this animated avif image

> https://colinbendell.github.io/webperf/animated-gif-decode/2.avif

I'm guessing not supported at the moment.

**Comment by lovell** [comment]
```sh
$ hexdump -C 2.avif | head -1
00000000  00 00 00 20 66 74 79 70  61 76 69 73 00 00 00 00  |... ftypavis....|
```
Please see https://github.com/strukturag/libheif/issues/377

**Comment by lovell** [comment]
v0.29.0 now available.

**Comment by adityapatadia** [comment]
When we use https://sharp.pixelplumbing.com/api-output#tobuffer with `resolveWithObject`, it does not return the new compression property.

**Comment by lovell** [comment]
@adityapatadia This issue relates to the `metadata()` function - please see https://github.com/lovell/sharp/commit/d000f577735c8e5d666ab1ed2440b0636648b03d#diff-7593ef01ed4401c670c4acf3cc96c2fbaee20979169fb66f81dddb45b91ec132 for a usage example.

**Comment by adityapatadia** [comment]
Yes, but ideally `resolveWithObject` should also return same data as `metadata()`. For example, when an image is compressed inside a function, its return info should ideally have all info about how was the image encoded.

**Comment by lovell** [comment]
The object returned/resolved by `toBuffer()` contains properties that are calculated or might change during processing. The `compression` property of `avif()` is known before processing and does not change during.
