### ISSUE TITLE
Excluding some metadata

### ISSUE THREAD

**Issue by abdul-ashour** [lovell/sharp#2507]
Is it possible to specify which metadata to include when using (.withmetadata), in my case I need to exclude XMP?

Your help will be highly appreciated.

**Comment by lovell** [comment]
Please see #650

**Comment by chrs-myrs** [comment]
What we need to do here is remove the EXIF embedded thumbnails.  They add several kb to each image after resizing, which is not great when you are trying to efficiently server 100's of millions of images each day.  Perhaps this would be better served by allowing sharp to control the stripping/generation of thumbnails

**Comment by lovell** [comment]
Please subscribe to #650 for updates.
