### ISSUE TITLE
sharp create image parameter with not int number throw error

### ISSUE THREAD

**Issue by shmilyoo** [lovell/sharp#2508]
```
const baseImg = sharp({
    create: {
      width: 200,
      height: 300.1234,
      channels: 4,
      background: { r: 0, g: 0, b: 0, alpha: 0 }
    }
  }).png();
```
the width and height is got from element.boundingBox.

throws Expected width, height, channels and background to create a new input image

but the ts doc:
```
    interface Create {
        /** Number of pixels wide. */
        width: number;
        /** Number of pixels high. */
        height: number;
        /** Number of bands e.g. 3 for RGB, 4 for RGBA */
        channels: Channels;
        /** Parsed by the [color](https://www.npmjs.org/package/color) module to extract values for red, green, blue and alpha. */
        background: Color;
    }
```

**Comment by lovell** [comment]
Hi, the value of `height` must be an integer.

(The TypeScript definitions are managed externally and are not part of sharp itself - please see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sharp/index.d.ts )

**Comment by shmilyoo** [comment]
@lovell thanks 
When I found this problem, I used Math.floor to convert height to plastic to solve the problem. 
Maybe you'd better mark this in the height parameter of ts or update the documentation.  
Using the width and height in the boundingBox of an element is a very common scenario, the height of the boundingBox is not necessarily an int type

**Comment by lovell** [comment]
Thank you, I've improved the docs via commit 39ddb6a
