### ISSUE TITLE
 After perspective, Can it continue to be transparent

### ISSUE THREAD

**Issue by banli17** [lovell/sharp#2510]
After the image passes through gm perspective, the bottom is black instead of transparent。 Can it continue to be transparent？

![image](https://user-images.githubusercontent.com/12556069/103408892-5a315d80-4b9f-11eb-8c5c-53a50f1a9ac7.png)

```
let a = gm('a.jpg')
    .out('-virtual-pixel', 'transparent')
    .out('+distort', 'Perspective', '0,0,0,0 183,0,183,23 0,368,-1,360 183,361,187,361')
    .toBuffer(function (err, buffer) {
        sharp(buffer).withMetadata().toFile('./x.png')
    })
```

**Comment by lovell** [comment]
What image format is `buffer`? Given you're using JPEG input, the output will probably also be JPEG, which does not support an alpha channel.

**Comment by banli17** [comment]
it's ok ,use `toBuffer('PNG', function(){})`
