### ISSUE TITLE
#FFFFFF becomes #FDFDFD after open/save webp file

### ISSUE THREAD

**Issue by IAkumaI** [lovell/sharp#2512]
### What are the steps to reproduce?
[100174.970.webp.zip](https://github.com/lovell/sharp/files/5761526/100174.970.webp.zip) (Github does not support webp attaches)
```
let image = sharp('path/to/file.webp'); // Attached file
await image.jpeg({quality:100}).toFile('path/to/save.jpg');
```

### What is the expected behaviour?
Original file has background #ffffff
But new file has background #fdfdfd

I tried all posiible options in formats. Also tried to save in webp. Nothing changes. Background becomes #fdfdfd
Also i tried to use online-converters and they does not has this bug.

**Comment by IAkumaI** [comment]
Sorry. After upgrading version all works fine.

**Comment by lovell** [comment]
Please see #2341
