### ISSUE TITLE
Push down image and add text on top

### ISSUE THREAD

**Issue by Glutch** [lovell/sharp#2514]
What are you trying to achieve?
![editly](https://user-images.githubusercontent.com/11299527/103532284-3dd93d80-4e8b-11eb-8a1b-6001a9dd57d9.jpg)

Have you searched for similar questions?
Yes

Hello! I need help with achieving this look. I want to add text on top of an image. Either by "pushing it down" and fitting into a 16:9 ratio. Or simply extending the picture with a "border-top: 50px; black" and adding text. Is this possible with sharp?

Thanks in advance

**Comment by lovell** [comment]
Hi, did you see `extend` and `composite`?

https://sharp.pixelplumbing.com/api-resize#extend
https://sharp.pixelplumbing.com/api-composite

```js
sharp(input)
  .extend({ top: 50 })
  .composite([{ input: Buffer.from("<svg><text> ... </text></svg>") }])
  ...
```

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
