### ISSUE TITLE
product of toFile is not a viable input for further processing as an input (Error: Input file contains unsupported image format)

### ISSUE THREAD

**Issue by balancemechanics** [lovell/sharp#2516]
first time user of .js, node, and sharp, so forgive me if my understanding is somewhat lacking. 

i'm just playing around with different fits, trying to resize and extract from that resulting image. i believe there are some specifics of toFile that are required to make the resulting image viable for processing once more in sharp. it is also highly likely i lack some .js knowledge which is impeding things for me, i apologise if so.

```
var fits = [sharp.fit.fill, sharp.fit.cover, sharp.fit.contain, sharp.fit.outside];

var file = "image.png";
var filename = file.replace(".png", "");
var out = "";

for (i = 0; i < fits.length; i++) {
out=(filename+"output-"+fits[i]+".png")

sharp(file)
  .resize({ width:w, height:h, fit: fits[i]})
  .toFile(out)

extractHeader(out, i)

}

function extractHeader(img,f) {

sharp(img)
  .extract({ left: headLeft, top: headTop, width: 975, height: 180 })
  .toFile("image-"+f+"-header.png")

}
```

**Comment by lovell** [comment]
Hi, did you see the documentation at https://sharp.pixelplumbing.com/api-output#tofile ?

The `toFile()` function is asynchronous and accepts either a callback function to call when complete, or returns an await-able Promise that resolves/rejects when complete.

For example, if you'd like to use an async/await style notation, you'll need to make the following change:

```diff
- sharp(file)
+ await sharp(file)
   .resize({ width:w, height:h, fit: fits[i]})
   .toFile(out)
```

**Comment by balancemechanics** [comment]
thank you. as expected it my meagre .js knowledge is lacking. thank you for your swift reply.
