### ISSUE TITLE
Input File is Missing

### ISSUE THREAD

**Issue by Person13851** [lovell/sharp#2519]
I am trying to load a png image with sharp and add two transparent rectangles on top. I looked on the docs and it said that Sharp(input) can be a String containing the filesystem path to an JPEG, PNG, WebP, AVIF, GIF, SVG or TIFF image file. so i did that. 
`sharp('../../data/images/two-buttons.png') 
    .composite([{
        input: blueRect,
        gravity: 'northeast'
    }, {
        input: greenRect,
        gravity: 'southwest'
    }])
  .toBuffer()
  .then(function(outputBuffer) {  });`
  
  but i get the error ` UnhandledPromiseRejectionWarning: Error: Input file is missing` even though the path is correct

**Comment by lovell** [comment]
Please remember that relative filesystem paths are relative to the process working directory (PWD). I usually recommend the use of absolute filesystem paths. You may also want to verify the value of `blueRect` in this example.

**Comment by Person13851** [comment]
Thank you, this worked, but how would i do it with an image link?

**Comment by lovell** [comment]
> how would i do it with an image link?

What do you mean by "image link"?

**Comment by Person13851** [comment]
I mean an imagine link like https://cdn.glitch.com/6da398da-dcf5-499a-9395-ab3ac6de59c5%2Fimages%20(2).jpeg?v=1605404598376

Where it is a link to an image. Is there like a way to buffer it and composite on top of another image

**Comment by lovell** [comment]
sharp does not provide any networking features, you'll have to write your own code to download the data and provide it as a Buffer.
