### ISSUE TITLE
Google Lighthouse complaining about sharp images not being "next gen formats"

### ISSUE THREAD

**Issue by Glutch** [lovell/sharp#2520]
How would i get "next gen formats" with sharp? Also. I tried .toFile('test.WebP') as google recommends, however the file size turned out to be the **exact same** as jpg. Possible bug?

**Comment by lovell** [comment]
Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

Are you able to provide a sample image that helps explain the problem?

**Comment by Glutch** [comment]
> Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
> 
> Are you able to provide a sample image that helps explain the problem?

```js
const sharp = require('sharp')
const fetch = require('node-fetch')

const test = async () => {
  const url = 'https://images.unsplash.com/photo-1602525653218-cac7c9e38807?ixid=MXwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2250&q=80'
  const res = await fetch(url)
  const buffer = await res.buffer()
  sharp(buffer).resize(1080).toFile('test.jpg')
  sharp(buffer).resize(1080).toFile('test.WebP')
}
test()
```

![image](https://user-images.githubusercontent.com/11299527/103783358-e7116680-5038-11eb-967b-669d43eb4857.png)

**Comment by lovell** [comment]
Please try the following:
```diff
-  sharp(buffer).resize(1080).toFile('test.WebP')
+  sharp(buffer).resize(1080).toFile('test.webp')
```

**Comment by Glutch** [comment]
> Please try the following:
> 
> ```diff
> -  sharp(buffer).resize(1080).toFile('test.WebP')
> +  sharp(buffer).resize(1080).toFile('test.webp')
> ```

That did something... i get an error
```
node:internal/process/promises:227
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: VipsOperation: class "icc_transform" not found
VipsOperation: class "webpsave" not found
]
```

**Comment by lovell** [comment]
Please upgrade vips to the latest version, then reinstall sharp.

**Comment by Glutch** [comment]
> Please upgrade vips to the latest version, then reinstall sharp. Please also ensure you are using the latest sharp v0.27.0.

upgraded vips to latest version with brew, removed node_modules, npm install, no difference. sharp is version 0.27.0.
i'm using apple m1 so might be a problem there somehow

**Comment by lovell** [comment]
Does `vips` work at the command line? Try `vips copy in.jpeg out.webp` - if it produces the same error then this is quite likely to be a Homebrew thing.

**Comment by Glutch** [comment]
> Does `vips` work at the command line? Try `vips copy in.jpeg out.webp` - if it produces the same error then this is quite likely to be a Homebrew thing.

```
vips copy test.jpg out.webp
VipsForeignSave: "out.webp" is not a known file format
```
can't find much online :/

**Comment by lovell** [comment]
This message suggests vips has been compiled without support for WebP images.

Perhaps try `brew update && brew reinstall vips --build-from-source`

**Comment by Glutch** [comment]
> This message suggests vips has been compiled without support for WebP images.
> 
> Perhaps try `brew update && brew reinstall vips --build-from-source`

still doesn't work, i give up. it works on my ubuntu server so thats what matters. thanks for trying!

**Comment by lovell** [comment]
No worries, Apple M1 users should probably expect to be at the bleeding edge until CI services start making this new hardware available to open source projects, which then allows us to build and test binaries that "just work".
