### ISSUE TITLE
Electron, ARMv7, Process killed with SIGSEGV error just after require('sharp')

### ISSUE THREAD

**Issue by Picardu57** [lovell/sharp#2522]
Hi,
I have a SIGSEGV error just after require('sharp'). After launch, I juste get this line :

`/home/pi/Public/me/node_modules/electron/dist/electron exited with signal SIGSEGV`

I use Electron 11.1.1 on a Raspberry Pi 4 (last OS), node 14.15.3 and sharp 0.27

I install all my dependencies with `npm install && ./node_modules/.bin/electron-rebuild`. I don't get any error during installation. Also I try without electron-rebuild, I got the same issue.
If I remove "require('sharp')" my program start correctly.

The same electron program on my MacBook work perfectly with sharp, it's a amazing tool ! I need to run on my Pi and i don't know why it doesn't work.

Can someone help me ?

Thx

**Comment by lovell** [comment]
The latest version of sharp uses [N-API](https://nodejs.org/api/n-api.html) v3 so the use of `electron-rebuild` is no longer required.

Please can you get a backtrace of the crash via `gdb`:

```
$ gdb /home/pi/Public/me/node_modules/electron/dist/electron

(gdb) run your-app.js

... wait for crash ...

(gdb) backtrace
```

**Comment by Picardu57** [comment]
Thx for your return. I noob on gdb but I find how to use it.
I already try without electron-rebuild, it's the same fing.

This is the trace of gdb, I don't get more information...
`gdb node
(gdb) run ./node_modules/electron/cli.js . PROD
Starting program: /usr/bin/node ./node_modules/electron/cli.js . PROD
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0xb6c09440 (LWP 25431)]
[New Thread 0xb62ff440 (LWP 25432)]
[New Thread 0xb5afe440 (LWP 25433)]
[New Thread 0xb52fd440 (LWP 25434)]
[New Thread 0xb4afc440 (LWP 25435)]
[New Thread 0xb6fb8440 (LWP 25436)]
[Detaching after fork from child process 25437]
/home/pi/Public/me/node_modules/electron/dist/electron exited with signal SIGSEGV
[Thread 0xb4afc440 (LWP 25435) exited]
[Thread 0xb52fd440 (LWP 25434) exited]
[Thread 0xb5afe440 (LWP 25433) exited]
[Thread 0xb62ff440 (LWP 25432) exited]
[Thread 0xb6c09440 (LWP 25431) exited]
[Thread 0xb6ff79d0 (LWP 25428) exited]
[Inferior 1 (process 25428) exited with code 01]
(gdb) backtrace
No stack.
(gdb) `

**Comment by lovell** [comment]
hHanks, the appearance of `gnueabihf` suggests it's trying to use ARMv7 but I'd expect aarch64/ARM64 on this device.

Please can you provide the full output of running `npm install --verbose sharp` on the Raspberry Pi.

**Comment by Picardu57** [comment]
This the looooong verbose =). For me, it use `libvips-8.10.5-linux-armv7.tar.br`

pi@me:~/Public/me $ npm install --verbose sharp
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/usr/bin/node',
npm verb cli   '/usr/bin/node_modules/npm/bin/npm-cli.js',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@6.14.9
npm info using node@v14.15.3
npm verb npm-session 39e3734716bc1ff0
npm http fetch GET 304 https://registry.npmjs.org/sharp 404ms (from cache)
npm timing stage:loadCurrentTree Completed in 4049ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 23ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 1896ms
npm http fetch GET 304 https://registry.npmjs.org/node-addon-api 164ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/array-flatten 288ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-fs 313ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/prebuild-install 321ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color 353ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-get 354ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/semver 372ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-string 96ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-convert 106ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-name 78ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-swizzle 72ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-arrayish 83ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/github-from-package 159ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/expand-template 175ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/napi-build-utils 173ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/noop-logger 181ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mkdirp-classic 196ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/which-pm-runs 192ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-concat 112ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 117ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mimic-response 71ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-stream 106ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-constants 69ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/readable-stream 98ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 3916ms
npm timing stage:loadIdealTree Completed in 6434ms
npm timing stage:generateActionsToTake Completed in 158ms
npm verb correctMkdir /home/pi/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/pi/.npm/_locks/staging-be800c0241d64ab1.lock for /home/pi/Public/me/node_modules/.staging
npm timing action:extract Completed in 107ms
npm info lifecycle sharp@0.27.0~preuninstall: sharp@0.27.0
npm info lifecycle sharp@0.27.0~uninstall: sharp@0.27.0
npm verb unbuild rmStuff sharp@0.27.0 from /home/pi/Public/me/node_modules
npm info lifecycle sharp@0.27.0~postuninstall: sharp@0.27.0
npm timing action:unbuild Completed in 8ms
npm timing audit submit Completed in 491ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 491ms
npm timing audit body Completed in 2ms
npm timing action:remove Completed in 355ms
npm timing action:finalize Completed in 10ms
npm timing action:refresh-package-json Completed in 21ms
npm info lifecycle sharp@0.27.0~preinstall: sharp@0.27.0
npm timing action:preinstall Completed in 2ms
npm info linkStuff sharp@0.27.0
npm timing action:build Completed in 3ms
npm info lifecycle sharp@0.27.0~install: sharp@0.27.0

> sharp@0.27.0 install /home/pi/Public/me/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /home/pi/.npm/_libvips/libvips-8.10.5-linux-armv7.tar.br
prebuild-install info begin Prebuild-install version 6.0.0
prebuild-install info looking for cached prebuild @ /home/pi/.npm/_prebuilds/b74d6b-sharp-v0.27.0-napi-v3-linux-arm.tar.gz
prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.27.0/sharp-v0.27.0-napi-v3-linux-arm.tar.gz
prebuild-install http 404 https://github.com/lovell/sharp/releases/download/v0.27.0/sharp-v0.27.0-napi-v3-linux-arm.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=3 runtime=napi arch=arm libc= platform=linux)
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild'
gyp verb cli ]
gyp info using node-gyp@5.1.0
gyp info using node@14.15.3 | linux | arm
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - executable path is "/usr/bin/python"
gyp verb find Python - executing "/usr/bin/python" to get version
gyp verb find Python - version is "2.7.16"
gyp info find Python using Python version 2.7.16 found at "/usr/bin/python"
gyp verb get node dir no --target version specified, falling back to host node version: 14.15.3
gyp verb command install [ '14.15.3' ]
gyp verb install input version string "14.15.3"
gyp verb install installing version: 14.15.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 14.15.3
gyp verb build dir attempting to create "build" dir: /home/pi/Public/me/node_modules/sharp/build
gyp verb build dir "build" dir needed to be created? /home/pi/Public/me/node_modules/sharp/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/pi/Public/me/node_modules/sharp/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/pi/Public/me/node_modules/sharp/config.gypi
gyp verb common.gypi checking for gypi file: /home/pi/Public/me/node_modules/sharp/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/Public/me/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/.cache/node-gyp/14.15.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/pi/.cache/node-gyp/14.15.3',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/pi/.cache/node-gyp/14.15.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/pi/Public/me/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture arm
gyp verb node dev dir /home/pi/.cache/node-gyp/14.15.3
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make : on entre dans le répertoire « /home/pi/Public/me/node_modules/sharp/build »
  touch Release/obj.target/libvips-cpp.stamp
  cc '-DNODE_GYP_MODULE_NAME=nothing' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' -I/home/pi/.cache/node-gyp/14.15.3/include/node -I/home/pi/.cache/node-gyp/14.15.3/src -I/home/pi/.cache/node-gyp/14.15.3/deps/openssl/config -I/home/pi/.cache/node-gyp/14.15.3/deps/openssl/openssl/include -I/home/pi/.cache/node-gyp/14.15.3/deps/uv/include -I/home/pi/.cache/node-gyp/14.15.3/deps/zlib -I/home/pi/.cache/node-gyp/14.15.3/deps/v8/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer  -MMD -MF ./Release/.deps/Release/obj.target/nothing/node_modules/node-addon-api/nothing.o.d.raw   -c -o Release/obj.target/nothing/node_modules/node-addon-api/nothing.o ../node_modules/node-addon-api/nothing.c
  rm -f Release/obj.target/node_modules/node-addon-api/nothing.a && ar crs Release/obj.target/node_modules/node-addon-api/nothing.a Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
  rm -rf "Release/nothing.a" && cp -af "Release/obj.target/node_modules/node-addon-api/nothing.a" "Release/nothing.a"
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNAPI_VERSION=3' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/pi/.cache/node-gyp/14.15.3/include/node -I/home/pi/.cache/node-gyp/14.15.3/src -I/home/pi/.cache/node-gyp/14.15.3/deps/openssl/config -I/home/pi/.cache/node-gyp/14.15.3/deps/openssl/openssl/include -I/home/pi/.cache/node-gyp/14.15.3/deps/uv/include -I/home/pi/.cache/node-gyp/14.15.3/deps/zlib -I/home/pi/.cache/node-gyp/14.15.3/deps/v8/include -I../node_modules/node-addon-api -I/home/pi/Public/me/node_modules/sharp/vendor/8.10.5/include -I/home/pi/Public/me/node_modules/sharp/vendor/8.10.5/include/glib-2.0 -I/home/pi/Public/me/node_modules/sharp/vendor/8.10.5/lib/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-psabi -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/common.o.d.raw   -c -o Release/obj.target/sharp/src/common.o ../src/common.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNAPI_VERSION=3' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/pi/.cache/node-gyp/14.15.3/include/node -I/home/pi/.cache/node-gyp/14.15.3/src -I/home/pi/.cache/node-gyp/14.15.3/deps/openssl/config -I/home/pi/.cache/node-gyp/14.15.3/deps/openssl/openssl/include -I/home/pi/.cache/node-gyp/14.15.3/deps/uv/include -I/home/pi/.cache/node-gyp/14.15.3/deps/zlib -I/home/pi/.cache/node-gyp/14.15.3/deps/v8/include -I../node_modules/node-addon-api -I/home/pi/Public/me/node_modules/sharp/vendor/8.10.5/include -I/home/pi/Public/me/node_modules/sharp/vendor/8.10.5/include/glib-2.0 -I/home/pi/Public/me/node_modules/sharp/vendor/8.10.5/lib/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-psabi -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/metadata.o.d.raw   -c -o Release/obj.target/sharp/src/metadata.o ../src/metadata.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNAPI_VERSION=3' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/pi/.cache/node-gyp/14.15.3/include/node -I/home/pi/.cache/node-gyp/14.15.3/src -I/home/pi/.cache/node-gyp/14.15.3/deps/openssl/config -I/home/pi/.cache/node-gyp/14.15.3/deps/openssl/openssl/include -I/home/pi/.cache/node-gyp/14.15.3/deps/uv/include -I/home/pi/.cache/node-gyp/14.15.3/deps/zlib -I/home/pi/.cache/node-gyp/14.15.3/deps/v8/include -I../node_modules/node-addon-api -I/home/pi/Public/me/node_modules/sharp/vendor/8.10.5/include -I/home/pi/Public/me/node_modules/sharp/vendor/8.10.5/include/glib-2.0 -I/home/pi/Public/me/node_modules/sharp/vendor/8.10.5/lib/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-psabi -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/stats.o.d.raw   -c -o Release/obj.target/sharp/src/stats.o ../src/stats.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNAPI_VERSION=3' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/pi/.cache/node-gyp/14.15.3/include/node -I/home/pi/.cache/node-gyp/14.15.3/src -I/home/pi/.cache/node-gyp/14.15.3/deps/openssl/config -I/home/pi/.cache/node-gyp/14.15.3/deps/openssl/openssl/include -I/home/pi/.cache/node-gyp/14.15.3/deps/uv/include -I/home/pi/.cache/node-gyp/14.15.3/deps/zlib -I/home/pi/.cache/node-gyp/14.15.3/deps/v8/include -I../node_modules/node-addon-api -I/home/pi/Public/me/node_modules/sharp/vendor/8.10.5/include -I/home/pi/Public/me/node_modules/sharp/vendor/8.10.5/include/glib-2.0 -I/home/pi/Public/me/node_modules/sharp/vendor/8.10.5/lib/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-psabi -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/operations.o.d.raw   -c -o Release/obj.target/sharp/src/operations.o ../src/operations.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNAPI_VERSION=3' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/pi/.cache/node-gyp/14.15.3/include/node -I/home/pi/.cache/node-gyp/14.15.3/src -I/home/pi/.cache/node-gyp/14.15.3/deps/openssl/config -I/home/pi/.cache/node-gyp/14.15.3/deps/openssl/openssl/include -I/home/pi/.cache/node-gyp/14.15.3/deps/uv/include -I/home/pi/.cache/node-gyp/14.15.3/deps/zlib -I/home/pi/.cache/node-gyp/14.15.3/deps/v8/include -I../node_modules/node-addon-api -I/home/pi/Public/me/node_modules/sharp/vendor/8.10.5/include -I/home/pi/Public/me/node_modules/sharp/vendor/8.10.5/include/glib-2.0 -I/home/pi/Public/me/node_modules/sharp/vendor/8.10.5/lib/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-psabi -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/pipeline.o.d.raw   -c -o Release/obj.target/sharp/src/pipeline.o ../src/pipeline.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNAPI_VERSION=3' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/pi/.cache/node-gyp/14.15.3/include/node -I/home/pi/.cache/node-gyp/14.15.3/src -I/home/pi/.cache/node-gyp/14.15.3/deps/openssl/config -I/home/pi/.cache/node-gyp/14.15.3/deps/openssl/openssl/include -I/home/pi/.cache/node-gyp/14.15.3/deps/uv/include -I/home/pi/.cache/node-gyp/14.15.3/deps/zlib -I/home/pi/.cache/node-gyp/14.15.3/deps/v8/include -I../node_modules/node-addon-api -I/home/pi/Public/me/node_modules/sharp/vendor/8.10.5/include -I/home/pi/Public/me/node_modules/sharp/vendor/8.10.5/include/glib-2.0 -I/home/pi/Public/me/node_modules/sharp/vendor/8.10.5/lib/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-psabi -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/utilities.o.d.raw   -c -o Release/obj.target/sharp/src/utilities.o ../src/utilities.cc
  g++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNAPI_VERSION=3' '-D_GLIBCXX_USE_CXX11_ABI=0' '-DBUILDING_NODE_EXTENSION' -I/home/pi/.cache/node-gyp/14.15.3/include/node -I/home/pi/.cache/node-gyp/14.15.3/src -I/home/pi/.cache/node-gyp/14.15.3/deps/openssl/config -I/home/pi/.cache/node-gyp/14.15.3/deps/openssl/openssl/include -I/home/pi/.cache/node-gyp/14.15.3/deps/uv/include -I/home/pi/.cache/node-gyp/14.15.3/deps/zlib -I/home/pi/.cache/node-gyp/14.15.3/deps/v8/include -I../node_modules/node-addon-api -I/home/pi/Public/me/node_modules/sharp/vendor/8.10.5/include -I/home/pi/Public/me/node_modules/sharp/vendor/8.10.5/include/glib-2.0 -I/home/pi/Public/me/node_modules/sharp/vendor/8.10.5/lib/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -Wno-psabi -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/sharp.o.d.raw   -c -o Release/obj.target/sharp/src/sharp.o ../src/sharp.cc
  g++ -shared -pthread -rdynamic -Wl,-s -Wl,--disable-new-dtags -Wl,-rpath='$ORIGIN/../../vendor/8.10.5/lib' -L/home/pi/Public/me/node_modules/sharp/vendor/8.10.5/lib  -Wl,-soname=sharp.node -o Release/obj.target/sharp.node -Wl,--start-group Release/obj.target/sharp/src/common.o Release/obj.target/sharp/src/metadata.o Release/obj.target/sharp/src/stats.o Release/obj.target/sharp/src/operations.o Release/obj.target/sharp/src/pipeline.o Release/obj.target/sharp/src/utilities.o Release/obj.target/sharp/src/sharp.o Release/obj.target/node_modules/node-addon-api/nothing.a -Wl,--end-group -l:libvips-cpp.so.42 -l:libvips.so.42
  rm -rf "Release/sharp.node" && cp -af "Release/obj.target/sharp.node" "Release/sharp.node"
make : on quitte le répertoire « /home/pi/Public/me/node_modules/sharp/build »
gyp info ok 
npm verb lifecycle sharp@0.27.0~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.27.0~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/Public/me/node_modules/sharp/node_modules/.bin:/home/pi/Public/me/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
npm verb lifecycle sharp@0.27.0~install: CWD: /home/pi/Public/me/node_modules/sharp
npm timing action:install Completed in 57629ms
npm info lifecycle sharp@0.27.0~postinstall: sharp@0.27.0
npm timing action:postinstall Completed in 2ms
npm verb unlock done using /home/pi/.npm/_locks/staging-be800c0241d64ab1.lock for /home/pi/Public/me/node_modules/.staging
npm timing stage:executeActions Completed in 58185ms
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 69411ms
npm verb saving [ { name: 'sharp', spec: '^0.27.0', save: 'dependencies' } ]
npm info lifecycle me@6.0.0~preshrinkwrap: me@6.0.0
npm info lifecycle me@6.0.0~shrinkwrap: me@6.0.0
npm verb shrinkwrap skipping write for package-lock.json because there were no changes.
npm info lifecycle me@6.0.0~postshrinkwrap: me@6.0.0
npm WARN bootstrap@4.5.3 requires a peer of popper.js@^1.16.1 but none is installed. You must install peer dependencies yourself.
npm WARN me@6.0.0 No description
npm WARN me@6.0.0 No repository field.
npm WARN me@6.0.0 No license field.

+ sharp@0.27.0
updated 1 package and audited 635 packages in 70.411s

30 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm verb exit [ 0, true ]
npm timing npm Completed in 72394ms
npm info ok

**Comment by Picardu57** [comment]
Raspberry Pi OS is 32bits. I beleive the 64bits version still in beta.

**Comment by lovell** [comment]
Are there any other native dependencies involved, e.g. `canvas`?

If possible, a complete, minimal, standalone repo with the config to allow someone else to attempt reproduce this issue would be helpful.

**Comment by lovell** [comment]
Are you able to test with the older v0.25.4 of sharp? It's possible this is the same problem as #2535.

**Comment by lovell** [comment]
I'm fairly certain this is the same problem as #2535 - let's continue to track it there.
