### ISSUE TITLE
sharp not converting image to AVIF format in AWS Lamba Function Layer that has timed out

### ISSUE THREAD

**Issue by saudpunjwani101** [lovell/sharp#2523]
I'm trying to convert a jpg image to avif format. So I'm using sharp in a Lambda Layer containing the latest version sharp@0.27.0. 

In the following handler function I'm sending an object to it containing the name of original image that is to be resized and converted to jpg, webp and avif. The original image could be a  jpg / png which should be resized to a specific size and then converted to the format jpg, webp and avif.

    const sharp = require('sharp')
  
    export default async event => {

	  try {
  
		  const {
			  input,
			  output,
			  format,
			  size,
		  } = event
  
		  console.log('get the original image from s3')
  
		  let buffer = await downloadFileFromImages(input)
  
		  console.log('got the original image, now preparing to resize and convert to format -', format)
                  
                  /* code works till here when the output format is avif.
                     the code is wrapped in try catch but I see no errors in the logs (CloudWatch).
                     NOTE: When I use the lambda layer containing the previous sharp version I was using @0.25.4, the next line calling 
                     the sharp function throws an error  "avif format not supported" which is expected. So I know the I have installed the 
                     correct version. But with version @.0.27.0 no error is thrown which making it hard to debug.
                  */
                  
		  buffer = await sharp(buffer)
			  .resize(size)
			  .toFormat(format)
			  .toBuffer()
			  
                  // only executes when the output format is jpg or webp.
                  
		  console.log('resized and converted to image format -', format)
                  
                  // uploads the buffer to S3 bucket
                  
		  let url = await uploadFileToImages({
			  buffer,
			  filename: output,
			  cacheControl: 'max-age=31536000, immutable',
		  })
  
		  return url
  
	    } catch (error) {
		    console.log('GOT ERROR ON UPLOADING IMAGE!!!', error)
	    }
    }

I'm using MacOS. The lambda layer is build and deployed to a staging environment, this is the build script,

// as described here https://sharp.pixelplumbing.com/install#aws-lambda

      rm -rf dist
      
      mkdir dist
      cd dist || exit
      
      mkdir nodejs
      cd nodejs || exit
      
      npm init -y
      
      SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install --arch=x64 --platform=linux sharp
      
      cd ..
      
      zip -r layer-sharp.zip nodejs

the zip file is then deployed to staging using the command,

  **aws lambda publish-layer-version \
  --layer-name sharp_0_27_0 \
  --description "sharp package" \
  --zip-file fileb://dist/layer-sharp.zip \
  --compatible-runtimes nodejs12.x**

The dependencies of the app in package.json,

    {
        "dependencies": {
          "@aws-cdk/assets": "1.39.0",
          "@aws-cdk/aws-apigateway": "1.39.0",
          "@aws-cdk/aws-certificatemanager": "1.39.0",
          "@aws-cdk/aws-cloudformation": "1.39.0",
          "@aws-cdk/aws-cloudfront": "1.39.0",
          "@aws-cdk/aws-cloudwatch": "1.39.0",
          "@aws-cdk/aws-ec2": "1.39.0",
          "@aws-cdk/aws-elasticloadbalancing": "1.39.0",
          "@aws-cdk/aws-events": "1.39.0",
          "@aws-cdk/aws-iam": "1.39.0",
          "@aws-cdk/aws-kms": "1.39.0",
          "@aws-cdk/aws-lambda": "1.39.0",
          "@aws-cdk/aws-logs": "1.39.0",
          "@aws-cdk/aws-route53": "1.39.0",
          "@aws-cdk/aws-route53-targets": "1.39.0",
          "@aws-cdk/aws-s3": "1.39.0",
          "@aws-cdk/aws-s3-assets": "1.39.0",
          "@aws-cdk/aws-s3-deployment": "1.39.0",
          "@aws-cdk/aws-sqs": "1.39.0",
          "@aws-cdk/core": "1.39.0",
          "@aws-cdk/cx-api": "1.39.0",
          "@aws-cdk/region-info": "1.39.0",
          "@emotion/core": "10.0.28",
          "atob": "2.1.2",
          "aws-sdk": "2.678.0",
          "aws-serverless-express": "3.3.8",
          "body-parser": "1.19.0",
          "btoa": "1.2.1",
          "bugsnag": "2.4.3",
          "compression": "1.7.4",
          "constructs": "3.0.3",
          "deepmerge": "4.2.2",
          "express": "4.17.1",
          "isomorphic-fetch": "2.2.1",
          "jsonwebtoken": "8.5.1",
          "localStorage": "1.0.4",
          "method-override": "3.0.0",
          "react": "16.12.0",
          "react-dom": "16.12.0",
          "react-helmet": "6.0.0",
          "react-router-dom": "5.1.2",
          "sharp": "0.27.0"
        },
        "devDependencies": {
          "@aws-cdk/assert": "1.39.0",
          "@babel/core": "7.9.6",
          "@babel/plugin-proposal-class-properties": "7.8.3",
          "@babel/preset-env": "7.9.6",
          "@babel/preset-react": "7.9.4",
          "@waiterio/shell": "0.0.0",
          "assets-webpack-plugin": "6.1.2",
          "aws-cdk": "1.39.0",
          "babel-loader": "8.1.0",
          "babel-plugin-emotion": "10.0.33",
          "clean-webpack-plugin": "3.0.0",
          "copy-webpack-plugin": "5.1.1",
          "cwtail": "1.4.1",
          "html-webpack-plugin": "4.5.0",
          "jest": "26.0.1",
          "scripty": "2.0.0",
          "source-map-support": "0.5.19",
          "supertest": "4.0.2",
          "webpack": "4.43.0",
          "webpack-bundle-analyzer": "3.7.0",
          "webpack-dev-server": "3.11.0"
        }
    }

And the Stack configuration referencing to use the lambda function,

    this.lambdaProcessImage = new lambda.Function(this, 'LambdaProcessImage', {
	    functionName: `${subdomain}-${environment}-process-image`,
	    code: lambda.Code.asset(path.join(__dirname, `../lambda-process-image-${environment}`)),
	    handler: 'handler.default',
	    runtime: lambda.Runtime.NODEJS_12_X,
	    memorySize: 512,
	    layers: [
		    lambda.LayerVersion.fromLayerVersionArn(
			    this,
			    'LambdaLayerSharp',
			    `arn:aws:lambda:${region}:${account}:layer:sharp_0_27_0:4`,
		    ),
	    ],
    })
  
  
 
the Logs screenshot from CloudWatch when output image format is Avif, as you can see it's like nothing is happening after the sharp function is called.

![Screen Shot 2021-01-09 at 1 39 36 PM](https://user-images.githubusercontent.com/19225141/104087292-7fe5f300-5280-11eb-8e71-cbc8bb10e6e1.png)

And the screenshot when the output image format is jpg, it's resized and converted as expected.

![Screen Shot 2021-01-09 at 1 40 00 PM](https://user-images.githubusercontent.com/19225141/104087304-a441cf80-5280-11eb-8383-2887053929a3.png)

Please help, I'm stuck on this.

**Comment by lovell** [comment]
The log you've provided says "Task timed out after 3.00 seconds" so I think the answer is in your question.

**Comment by saudpunjwani101** [comment]
Yup that was the issue. Sorry to bother and thanks for the help!
