### ISSUE TITLE
Error TypeError: Cannot destructure property 'width' of 'image.bitmap' as it is undefined

### ISSUE THREAD

**Issue by iyosayi** [lovell/sharp#2524]
What are you trying to achieve?
I was trying to resize images with the options that get passed through my API. The options are `width` and `height`.

Have you searched for similar questions?
- No.

Are you able to provide a minimal, standalone code sample that demonstrates this question?
Example code
```
// imageProcessor is `sharp` being injected as a dependency
const imageToResize = await imageProcessor(filepath)
      .resize({ width: modifiedWidth, height: modifiedHeight })
      .toFile(outputFile)
```
`modifiedWidth` and `modifiedHeight` are the `width` and `height` values that I convert to numbers using the `Number()` object wrapper.

Are you able to provide a sample image that helps explain the question?
- No.

**Comment by lovell** [comment]
Please can you provide a *complete*, minimal, standalone code sample that demonstrates this question? I suspect the error is occurring in code not shown here.

**Comment by iyosayi** [comment]
Okay, you were right, I did a little more digging and found the error. Closing this issue.
