### ISSUE TITLE
Docs: improve clarity of generaring 16bpp PNG output

### ISSUE THREAD

**Issue by mtaylor-tbpm** [lovell/sharp#2528]
Question about PNG output.  Documentation says: "PNG output is always full colour at 8 or 16 bits per pixel".  I don't see an option for specifying this and my 16bit PNGs are outputting at 8bit, even with only a simple .clone().toFile() operation.

Am I missing something?  Thank you.

**Comment by lovell** [comment]
Hi, try adding `toColourspace('rgb16')` to your pipeline, something like:

```js
sharp('16-bpp.png')
  .toColourspace('rgb16')
  .toFile('also-16-bpp.png')
```

https://sharp.pixelplumbing.com/api-colour#tocolourspace

(The docs could definitely be clearer about this.)

**Comment by mtaylor-tbpm** [comment]
Perfect, this worked.  Thanks

**Comment by lovell** [comment]
Great, I'll leave this issue open temporarily as a reminder to improve the docs.

**Comment by lovell** [comment]
Example added in commit https://github.com/lovell/sharp/commit/24d9e53c3f53a5b2b6e089b5727a8b058984604f
