### ISSUE TITLE
Crash when handle unsupported SVG and not throw error

### ISSUE THREAD

**Issue by jasonamavisca** [lovell/sharp#2530]
Hi all,
Thank you for the amazing library. 

I have an issue :
sharp is crash when _resize_ then write _toFile_ on specific svg

the problem is :
_toFile_ is not throw error when handle unsupported svg format.
sharp is crash

the log says :
Fontconfig error: Cannot load default config file: No such file: (null)

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
yes
```
version : sharp@0.27.0 
console.log(sharp.version):
{
  aom: '2.0.1',
  cairo: '1.17.4',
  exif: '0.6.22',
  expat: '2.2.10',
  ffi: '3.3',
  fontconfig: '2.13.93',
  freetype: '2.10.4',
  fribidi: '1.0.10',
  gdkpixbuf: '2.42.2',
  gettext: '0.21',
  gif: '5.1.4',
  glib: '2.67.1',
  gsf: '1.14.47',
  harfbuzz: '2.7.2',
  heif: '1.10.0',
  jpeg: '2.0.6',
  lcms: '2.11',
  orc: '0.4.32',
  pango: '1.48.0',
  pixman: '0.40.0',
  png: '1.6.37',
  svg: '2.50.2',
  spng: '0.6.1',
  tiff: '4.2.0',
  vips: '8.10.5',
  webp: '1.1.0',
  xml: '2.9.10',
  zlib: '1.2.11'
}
```

What is the expected behaviour?
`
Sharp method 'toFile' will throw error when handle unsupported SVG format instead of crash.
`

Are you able to provide a sample image that helps explain the problem?
[svg problem 1](https://upload.wikimedia.org/wikipedia/commons/8/80/Asia_%28orthographic_projection%29.svg)
[svg problem 2](https://upload.wikimedia.org/wikipedia/commons/8/8e/Oceania_%28orthographic_projection%29.svg)

What is the output of running `npx envinfo --binaries --system`?
```
  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 63.73 MB / 4.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
```

**Comment by lovell** [comment]
This is the same problem as #2515 - let's track it there.
