### ISSUE TITLE
Input buffer contains unsupported image format - only after comopsite

### ISSUE THREAD

**Issue by tan-tan-kanarek** [lovell/sharp#2532]
I get this error message only after calling composite, here is my code:
```
var png = sharp(buffer);
var data = await png.raw().toBuffer();
var alpha = Buffer.alloc(width * height);
// ... some calculation to create alpha channel base on the data
png.joinChannel(alpha, {
    raw: {width, height, channels: 1}
});
if(createBluredLayer) {
    var overlay = png.clone().blur(1)
    png.composite([{
        input: await overlay.toBuffer(),
        top: 0,
        left: 0,
    }])
}
var newBuffer = await png.toBuffer(); // this line triggers the error
```

So, if createBluredLayer is false, all goes well, if it's true, I get the error when calling toBuffer().
I don't understand how composite of the same image could change the format.

**Comment by lovell** [comment]
In this code example, the response of `await overlay.toBuffer()` will be raw, uncompressed pixel data due to the use of `png.raw()` so you'll need to describe it via `raw`:

```diff
png.composite([{
  input: await overlay.toBuffer(),
+ raw: { width, height, channels }
  top: 0,
```

**Comment by tan-tan-kanarek** [comment]
Thank you.
I would like to optimize this code as much as possible as I do it a lot.
Is there any difference, speed wise, if I create the overlay image using png.clone() or create a new one using the same buffer sharp(buffer)?

**Comment by lovell** [comment]
`clone` is for Stream-based input, so if you're using Buffer-based input it probably won't help.

**Comment by tan-tan-kanarek** [comment]
I encounter now another error, composite2: images do not have same numbers of bands.
My new code looks as followed:
```
var png = sharp(buffer);
var data = await png.raw().toBuffer();
var alpha = Buffer.alloc(width * height);

// ... some calculation to create alpha channel base on the data

png.joinChannel(alpha, {
    raw: {width, height, channels: 1}
})
.png();
if(createBluredLayer) {
    var overlay = sharp(await png.toBuffer()).blur(1)
    png.composite([{
        input: await overlay.toBuffer(),
        top: 0,
        left: 0,
    }])
}
var newBuffer = await png.toBuffer(); // this line triggers the error
```

I want to use the calculated alpha channel on both layers, sharp one overlayed on blured one in order to create soft edges to the transparent image.
