### ISSUE TITLE
Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by noobboon7** [lovell/sharp#2533]
**Having issues installing sharp on the m1, I've already installed vips via rosetta homebrew...**

  **System:**
    _OS: macOS 11.1
    CPU: (8) arm64 Apple M1
    Memory: 376.22 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh_
  **Binaries:**
    _Node: 15.4.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 6.14.10 - /opt/homebrew/bin/npm_

  success open and validate gatsby-configs - 0.044s

###  ERROR 

Error in
"/Users/squid/Dev/docker-gatsby/client/node_modules/gatsby-transformer-sharp/gatsby-node.js":
Something went wrong installing the "sharp" module

dlopen(/Users/squid/Dev/docker-gatsby/client/node_modules/sharp/build/Release/sharp.node, 1):
Symbol not found: __ZTVN4vips7VOptionE
  Referenced from:
/Users/squid/Dev/docker-gatsby/client/node_modules/sharp/build/Release/sharp.node
  Expected in: flat namespace
 in /Users/squid/Dev/docker-gatsby/client/node_modules/sharp/build/Release/sharp.node

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

  Error: Something went wrong installing the "sharp" module
  dlopen(/Users/me/Dev/docker-gatsby/client/node_modules/sharp/build/Release/sharp.node, 1): Sym
  bol not found: __ZTVN4vips7VOptionE
    Referenced from: /Users/squids/Dev/docker-gatsby/client/node_modules/sharp/build/Release/sharp.n
  ode
    Expected in: flat namespace
   in /Users/squids/Dev/docker-gatsby/client/node_modules/sharp/build/Release/sharp.node
  - Remove the "node_modules/sharp" directory then run
    "npm install --ignore-scripts=false --verbose" and look for errors
  - Consult the installation documentation at https://sharp.pixelplumbing.com/install
  - Search for this error at https://github.com/lovell/sharp/issues
  
  - constructor.js:34 Object.<anonymous>
    [client]/[sharp]/lib/constructor.js:34:9
  
  - v8-compile-cache.js:178 Module._compile
    [client]/[v8-compile-cache]/v8-compile-cache.js:178:30
  
  - loader:1137 Object.Module._extensions..js
    node:internal/modules/cjs/loader:1137:10
  
  - loader:973 Module.load
    node:internal/modules/cjs/loader:973:32
  
  - loader:813 Function.Module._load
    node:internal/modules/cjs/loader:813:14
  
  - loader:997 Module.require
    node:internal/modules/cjs/loader:997:19
  
  - v8-compile-cache.js:159 require
    [client]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - index.js:3 Object.<anonymous>
    [client]/[sharp]/lib/index.js:3:15
  
  - v8-compile-cache.js:178 Module._compile
    [client]/[v8-compile-cache]/v8-compile-cache.js:178:30
  
  - loader:1137 Object.Module._extensions..js
    node:internal/modules/cjs/loader:1137:10
  
  - loader:973 Module.load
    node:internal/modules/cjs/loader:973:32
  
  - loader:813 Function.Module._load
    node:internal/modules/cjs/loader:813:14
  
  - loader:997 Module.require
    node:internal/modules/cjs/loader:997:19
  
  - v8-compile-cache.js:159 require
    [client]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - safe-sharp.js:127 Object.<anonymous>
    [client]/[gatsby-plugin-sharp]/safe-sharp.js:127:11
  
  - v8-compile-cache.js:178 Module._compile
    [client]/[v8-compile-cache]/v8-compile-cache.js:178:30
  

not finished load plugins - 0.252s

**I've also** 
- removed node_modules 
- npm cache clean -f
- npm clean (runs gatsby clean)
- npm install 
- npm install --ignore-scripts=false --verbose
- npm i --verbose sharp@latest   
- npm rebuild

I'm out of idea's here... there something I can do manually?

**Comment by lovell** [comment]
Please see #2460 and ask there - Apple M1 is not yet officially supported by sharp and I cannot help with problems that relate to it as I do not have access to the necessary hardware, sorry.

**Comment by jdortegar** [comment]
I have the same problem, any solution ?

**Comment by lovell** [comment]
@jdortegar Please see #2460 and ask there.
