### ISSUE TITLE
Failed dependency resolution on using npm ci instead of npm install 

### ISSUE THREAD

**Issue by chandrasekhar1996** [lovell/sharp#2534]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?
Yes

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?
Yes, it is Rhel 7

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
I am using Next.js v10.0.5 and sharp 0.26.3 is a dependency of it.

If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?
Not using root or sudo

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?
Yes

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

What is the output of running `npx envinfo --binaries --system`?
System:
    OS: Linux 4.19 Red Hat Enterprise Linux Server 7.9 (Maipo)
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 623.18 MB / 1.94 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 14.15.4
    npm: 6.14.10

My project has a package-lock.json file and I use npm ci to install the node_modules.
For our build, we are generating an RPM for the UI.
The node_module sharp that gets downloaded on using npm ci vs on using npm install is different. While trying to install the rpm generated when using npm ci fails with the following error: 
` --> Processing Dependency: libvips.so.42()(64bit) for package: node-ui.el7.x86_64
  --> Processing Dependency: libvips-cpp.so.42()(64bit) for package: node-ui.el7.x86_64
  --> Finished Dependency Resolution
              Error: Package: node-ui.el7.x86_64
                         Requires: libvips-cpp.so.42()(64bit)
              Error: Package: node-ui.el7.x86_64
                         Requires: libvips.so.42()(64bit)`
 
 I don't get the same error on using npm install which is weird.
 On inspecting the node_module sharp, the differences are:
 
 npm ci : has a vendor folder and build folder with a sharp.node file         
 
 I am not sure if it is an issue with next or sharp. Can you please instruct on what may be causing this issue?

**Comment by lovell** [comment]
How is the rpm built? Are you explicitly specifying a dependency on libvips?

What is the output of running `npm ci --verbose`, especially the part when sharp is installed?

**Comment by chandrasekhar1996** [comment]
Using the rpmbuild utility, we just copy the node_modules,
I don’t specify any dependency on libvips explicitly

`npm info lifecycle sharp@0.26.3~install: sharp@0.26.3
> sharp@0.26.3 install /usr/src/app/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.0/libvips-8.10.0-linux-x64.tar.br
prebuild-install info begin Prebuild-install version 6.0.0
prebuild-install info looking for cached prebuild @ /root/.npm/_cacache/_prebuilds/3a1d54-sharp-v0.26.3-napi-v3-linux-x64.tar.gz
prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.26.3/sharp-v0.26.3-napi-v3-linux-x64.tar.gz
prebuild-install http 200 https://github.com/lovell/sharp/releases/download/v0.26.3/sharp-v0.26.3-napi-v3-linux-x64.tar.gz
prebuild-install info downloading to @ /root/.npm/_cacache/_prebuilds/3a1d54-sharp-v0.26.3-napi-v3-linux-x64.tar.gz.139-9230fb6b69499.tmp
prebuild-install info renaming to @ /root/.npm/_cacache/_prebuilds/3a1d54-sharp-v0.26.3-napi-v3-linux-x64.tar.gz
prebuild-install info unpacking @ /root/.npm/_cacache/_prebuilds/3a1d54-sharp-v0.26.3-napi-v3-linux-x64.tar.gz
prebuild-install info unpack resolved to /usr/src/app/node_modules/sharp/build/Release/sharp.node
prebuild-install info install Successfully installed prebuilt binary!
npm verb lifecycle sharp@0.26.3~install: unsafe-perm in lifecycle false
npm verb lifecycle sharp@0.26.3~install: PATH: /node/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/src/app/node_modules/sharp/node_modules/.bin:/usr/src/app/node_modules/.bin:/usr/bin:/opt/rh/devtoolset-8/root/usr/bin:/opt/rh/rh-git218/root/usr/bin:/opt/rh/rh-git218/root/usr/bin/:/bin64:/bin:/opt/rh/rh-git218/root/usr/bin:/bin64:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle sharp@0.26.3~install: CWD: /usr/src/app/node_modules/sharp
npm info lifecycle sharp@0.26.3~postinstall: sharp@0.26.3
`

**Comment by lovell** [comment]
That log looks OK, so my best guess is that there's something going wrong after this, perhaps in the rpmbuild configuration. Are you able to share this, perhaps as a separate, standalone repo that allows someone else to reproduce the problem?

**Comment by chandrasekhar1996** [comment]
Working on creating a separate repo.
Meanwhile, do you think that the node_module of sharp downloaded being separate on using `npm ci` and `npm install` is an issue?

**Comment by chandrasekhar1996** [comment]
@lovell https://github.com/chandrasekhar1996/libvips-issue
you can run the docker file and then try to install the rpm created in rpmbuild folder

**Comment by lovell** [comment]
You need to add an explicit `Requires:` section to the spec otherwise rpmbuild will do it for you.

https://rpm.org/user_doc/more_dependencies.html#automatic-dependencies

This is a feature of rpmbuild unrelated to sharp or libvips. Please consider a more general site such as StackOverflow for this kind of question.

**Comment by chandrasekhar1996** [comment]
Sorry for opening the issue but I am not sure I understand how using `Requires: ` would solve the issue.
The rpm shows a dependency on libvips-cpp.so.42 and libvips.so.42 which is present inside the `/sharp/vendor/8.10.0/lib/` in the rpm files.
So what would I need to specify in `Requires: ` field?

**Comment by chandrasekhar1996** [comment]
fyi, earlier I found an article of how it may be an issue of permission to the file and I added the following lines in %install of my spec file and I was able to install the rpm:

`chmod 0755 %{buildroot}/home/chandu/var/%{name}/node_modules/sharp/vendor/8.10.0/lib/libvips-cpp.so.42
chmod 0755 %{buildroot}/home/chandu/var/%{name}/node_modules/sharp/vendor/8.10.0/lib/libvips.so.42
`

not sure if this is the right fix so would like to understand it better
