### ISSUE TITLE
Windows installation fails on v0.27.0

### ISSUE THREAD

**Issue by alsguimaraes** [lovell/sharp#2536]
Hi lovell, first congratulations on such a great tool

The installation does work, however using the library (on Win32, x64) generates an error on require('sharp');

C:\projects\xx\node_modules\sharp\lib\constructor.js:34
  throw new Error(error);
  ^
Error:
Something went wrong installing the "sharp" module

The specified procedure could not be found.
\\?\C:\projects\xx\node_modules\sharp\build\Release\sharp.node
=====================
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?

Yes

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?

Yes, it does not help.

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

Yes. 0.27.0. (But the issue happens from v0.25 onwards).

If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

Not applicable.

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

Not using. adding the flag does not solve the issue.

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

npm install --verbose sharp
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@6.14.11
npm info using node@v12.16.3
npm verb npm-session af82da5da2f5ffbd
npm http fetch GET 200 https://registry.npmjs.org/sharp 319ms
npm timing stage:loadCurrentTree Completed in 2954ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 15ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 1122ms
npm http fetch GET 304 https://registry.npmjs.org/array-flatten 83ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/semver 149ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-addon-api 155ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-get 161ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/prebuild-install 163ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color 168ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-fs 265ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-string 43ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-convert 106ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-name 41ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-swizzle 47ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-arrayish 66ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/github-from-package 62ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/napi-build-utils 70ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mkdirp-classic 124ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/which-pm-runs 123ms (from cache) 
npm http fetch GET 304 https://registry.npmjs.org/noop-logger 142ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/expand-template 151ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-abi 179ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-stream 59ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-constants 55ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bl 67ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/readable-stream 74ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/buffer 54ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lru-cache 46ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/yallist 82ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 3043ms
npm timing stage:loadIdealTree Completed in 4513ms
npm timing stage:generateActionsToTake Completed in 159ms
npm verb correctMkdir C:\Users\user\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
npm verb makeCacheDir UID & GID are irrelevant on win32
npm verb lock using C:\Users\user\AppData\Roaming\npm-cache\_locks\staging-eff602f7fe0259b0.lock for C:\projects\xx\node_modules\.staging
npm timing action:extract Completed in 758ms
npm info lifecycle sharp@0.24.1~preuninstall: sharp@0.24.1
npm info lifecycle sharp@0.24.1~uninstall: sharp@0.24.1
npm verb unbuild rmStuff sharp@0.24.1 from C:\projects\xx\node_modules
npm info lifecycle sharp@0.24.1~postuninstall: sharp@0.24.1
npm info lifecycle prebuild-install@5.3.6~preuninstall: prebuild-install@5.3.6
npm info lifecycle prebuild-install@5.3.6~uninstall: prebuild-install@5.3.6
npm verb unbuild rmStuff prebuild-install@5.3.6 from C:\projects\xx\node_modules
npm info lifecycle prebuild-install@5.3.6~postuninstall: prebuild-install@5.3.6
npm info lifecycle tar@6.1.0~preuninstall: tar@6.1.0
npm info lifecycle tar@6.1.0~uninstall: tar@6.1.0
npm verb unbuild rmStuff tar@6.1.0 from C:\projects\xx\node_modules
npm verb unbuild rmStuff in C:\projects\xx\node_modules\sharp\node_modules
npm info lifecycle tar@6.1.0~postuninstall: tar@6.1.0
npm info lifecycle mkdirp@1.0.4~preuninstall: mkdirp@1.0.4
npm info lifecycle mkdirp@1.0.4~uninstall: mkdirp@1.0.4
npm verb unbuild rmStuff mkdirp@1.0.4 from C:\projects\xx\node_modules
npm verb unbuild rmStuff in C:\projects\xx\node_modules\sharp\node_modules
npm timing audit submit Completed in 1111ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 1124ms
npm timing audit body Completed in 3ms
npm info lifecycle mkdirp@1.0.4~postuninstall: mkdirp@1.0.4
npm info lifecycle minizlib@2.1.2~preuninstall: minizlib@2.1.2
npm info lifecycle minizlib@2.1.2~uninstall: minizlib@2.1.2
npm verb unbuild rmStuff minizlib@2.1.2 from C:\projects\xx\node_modules
npm verb unbuild rmStuff in C:\projects\xx\node_modules\sharp\node_modules
npm info lifecycle minizlib@2.1.2~postuninstall: minizlib@2.1.2
npm info lifecycle fs-minipass@2.1.0~preuninstall: fs-minipass@2.1.0
npm info lifecycle fs-minipass@2.1.0~uninstall: fs-minipass@2.1.0
npm verb unbuild rmStuff fs-minipass@2.1.0 from C:\projects\xx\node_modules
npm verb unbuild rmStuff in C:\projects\xx\node_modules\sharp\node_modules
npm info lifecycle fs-minipass@2.1.0~postuninstall: fs-minipass@2.1.0
npm info lifecycle minipass@3.1.3~preuninstall: minipass@3.1.3
npm info lifecycle minipass@3.1.3~uninstall: minipass@3.1.3
npm verb unbuild rmStuff minipass@3.1.3 from C:\projects\xx\node_modules
npm verb unbuild rmStuff in C:\projects\xx\node_modules\sharp\node_modules
npm info lifecycle minipass@3.1.3~postuninstall: minipass@3.1.3
npm info lifecycle chownr@2.0.0~preuninstall: chownr@2.0.0
npm info lifecycle chownr@2.0.0~uninstall: chownr@2.0.0
npm verb unbuild rmStuff chownr@2.0.0 from C:\projects\xx\node_modules
npm verb unbuild rmStuff in C:\projects\xx\node_modules\sharp\node_modules
npm info lifecycle chownr@2.0.0~postuninstall: chownr@2.0.0
npm timing action:unbuild Completed in 580ms
npm timing action:remove Completed in 629ms
npm timing action:finalize Completed in 63ms
npm timing action:refresh-package-json Completed in 122ms
npm info lifecycle array-flatten@3.0.0~preinstall: array-flatten@3.0.0
npm info lifecycle node-addon-api@3.1.0~preinstall: node-addon-api@3.1.0
npm info lifecycle prebuild-install@6.0.0~preinstall: prebuild-install@6.0.0
npm info lifecycle simple-get@4.0.0~preinstall: simple-get@4.0.0
npm info lifecycle sharp@0.27.0~preinstall: sharp@0.27.0
npm timing action:preinstall Completed in 105ms
npm info linkStuff array-flatten@3.0.0
npm info linkStuff node-addon-api@3.1.0
npm info linkStuff prebuild-install@6.0.0
npm verb linkBins [
npm verb linkBins   { 'prebuild-install': 'bin.js' },
npm verb linkBins   'C:\\projects\\xx\\node_modules\\.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff simple-get@4.0.0
npm info linkStuff sharp@0.27.0
npm timing action:build Completed in 107ms
npm info lifecycle array-flatten@3.0.0~install: array-flatten@3.0.0
npm info lifecycle node-addon-api@3.1.0~install: node-addon-api@3.1.0
npm info lifecycle prebuild-install@6.0.0~install: prebuild-install@6.0.0
npm info lifecycle simple-get@4.0.0~install: simple-get@4.0.0
npm info lifecycle sharp@0.27.0~install: sharp@0.27.0

> sharp@0.27.0 install C:\projects\xx\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached C:\Users\user\AppData\Roaming\npm-cache\_libvips\libvips-8.10.5-win32-x64.tar.br
info sharp Creating C:\projects\xx\node_modules\sharp\build\Release
info sharp Copying DLLs from C:\projects\xx\node_modules\sharp\vendor\8.10.5\lib to C:\projects\xx\node_modules\sharp\build\Release
prebuild-install info begin Prebuild-install version 6.0.0
prebuild-install info looking for cached prebuild @ C:\Users\user\AppData\Roaming\npm-cache\_prebuilds\9cc5aa-sharp-v0.27.0-napi-v3-win32-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ C:\Users\user\AppData\Roaming\npm-cache\_prebuilds\9cc5aa-sharp-v0.27.0-napi-v3-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\projects\xx\node_modules\sharp\build\Release\sharp.node
prebuild-install info install Successfully installed prebuilt binary!
npm verb lifecycle sharp@0.27.0~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.27.0~install: PATH: C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\projects\xx\node_modules\sharp\node_modules\.bin;C:\projects\xx\node_modules\.bin;C:\Python38\Scripts\;C:\Python38\;C:\Rtools\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program 
Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\WINDOWS\System32\OpenSSH\;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Users\user\AppData\Roaming\npm;C:\Program Files\Theme Kit;C:\Program Files\Pandoc\;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files\Git\cmd;C:\Users\user\AppData\Local\Yarn\bin;;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Amazon\AWSCLIV2\;C:\Users\user\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\heroku\bin;C:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\bin;C:\Users\user\AppData\Roaming\npm
npm verb lifecycle sharp@0.27.0~install: CWD: C:\projects\xx\node_modules\sharp
npm timing action:install Completed in 9585ms
npm info lifecycle array-flatten@3.0.0~postinstall: array-flatten@3.0.0
npm info lifecycle node-addon-api@3.1.0~postinstall: node-addon-api@3.1.0
npm info lifecycle prebuild-install@6.0.0~postinstall: prebuild-install@6.0.0
npm info lifecycle simple-get@4.0.0~postinstall: simple-get@4.0.0
npm info lifecycle sharp@0.27.0~postinstall: sharp@0.27.0
npm timing action:postinstall Completed in 33ms
npm verb unlock done using C:\Users\user\AppData\Roaming\npm-cache\_locks\staging-eff602f7fe0259b0.lock for C:\projects\xx\node_modules\.staging
npm timing stage:executeActions Completed in 12070ms
npm timing stage:rollbackFailedOptional Completed in 0ms
npm timing stage:runTopLevelLifecycles Completed in 20060ms
npm verb saving [ { name: 'sharp', spec: '^0.27.0', save: 'dependencies' } ]
npm verb shrinkwrap skipping write for package.json because there were no changes.
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle xx@1.0.0~shrinkwrap: xx@1.0.0
npm info lifecycle xx@1.0.0~postshrinkwrap: xx@1.0.0
npm WARN xx@1.0.0 No repository field.

+ sharp@0.27.0
added 3 packages from 75 contributors, removed 6 packages, updated 2 packages and audited 857 packages in 20.73s
17 packages are looking for funding
  run `npm fund` for details

found 16 vulnerabilities (13 low, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details
npm verb exit [ 0, true ]
npm timing npm Completed in 22125ms
npm info ok

What is the output of running `npx envinfo --binaries --system`?

  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 4.18 GB / 15.87 GB
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.3.2 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - ~\AppData\Roaming\npm\npm.CMD

**Comment by lovell** [comment]
Are you using any other native modules as dependencies e.g. `canvas`?

**Comment by alsguimaraes** [comment]
Not really. Pretty vanilla setup. Running simple js through node.js command line.

**Comment by lovell** [comment]
> Not really. 

Please can you provide the output of running `npm ls` in the `C:\projects\xx` directory.

**Comment by alsguimaraes** [comment]
You are right. I took a closer look and there is an indirect dependency on canvas. 
I checked it again on a clean project, and works just fine.
