### ISSUE TITLE
Is it necessary to use a worker thread or child process?

### ISSUE THREAD

**Issue by WarrenMfg** [lovell/sharp#2538]
What are you trying to achieve?
The docs say "Everything remains non-blocking thanks to libuv, no child processes are spawned and Promises/async/await are supported." So does that mean I don't need to spawn child processes or use a worker thread pool on my own?

I created an endpoint that uses a worker thread to fetch an image from AWS S3, then use sharp to extract it into 9 sections, then upload the 9 images to AWS S3. Finally, the frontend uses those 9 images to make an image scramble game (screenshot below). However, now I'm wondering if it's not necessary to use a worker thread (or a child process) for this.

Abridged code below. Any thoughts? Thank you!

Have you searched for similar questions? 
Yes

Are you able to provide a minimal, standalone code sample that demonstrates this question?

![sharp](https://user-images.githubusercontent.com/48572147/104855216-793b2980-58d9-11eb-817a-3d5986ec232a.png)

Are you able to provide a sample image that helps explain the question?

<img width="533" alt="piecemeal" src="https://user-images.githubusercontent.com/48572147/104855274-c7502d00-58d9-11eb-8663-7788c1dc8f59.png">

Thanks again!
Kent

**Comment by lovell** [comment]
The short answer is: "probably not". Was there a reason for using Workers in the first place?

I would imagine the bottleneck in this scenario will be network I/O rather than CPU. I notice the logic above waits for all image processing to complete before uploading so perhaps this is the bit to optimise.

**Comment by WarrenMfg** [comment]
Fairly new to image processing. So, I initially thought image processing would block the event loop. Then I re-read the bit about how everything remains non-blocking. Curious how that works, so I'll need to research it. But that's a great tip about the bottleneck. Thank you! Cheers!

**Comment by mindplay-dk** [comment]
@lovell is it doing the work on the main thread or in a worker?

I ask because I wrote a script that batch processes a large bulk of files - I noticed it was using only 25% CPU (so 1 of 4 cores, presumably) and decided to run multiple jobs in parallel.

Not a complete example, but something like:

```ts
(async () => {
  let jobs: Array<Promise<void>> = [];

  async function throttle(job: Promise<void>) {
    jobs.push(job);

    job.then(() => {
      jobs = jobs.filter(item => item !== job);
    });

    while (jobs.length > 10) {
      await Promise.race(jobs);
    }
  }
  
  for (let i=0; i<total; i++) {
    const filename = files[i];
  
    console.log(`[${i}/${total}] indexing: ${filename}`);

    await throttle(resizeImage(filename));
  }
})();
```

So this allows for 10 unresolved promises at any time - `resizeImage` starts a job and returns a `Promise<void>`, we keep running jobs in `jobs`, and and when a `job` finishes, we remove it.

This got me into the area of maybe 30-50% CPU, so still not running on all cylinders for some reason.

Do I need to manually spawn workers to make sure it's running on all cores?

I suppose it could be that I'm hitting an IO bottleneck, but I wouldn't guess so - JPEG files are small.

**Comment by mindplay-dk** [comment]
So I tried a few different things, I guess worth sharing. 🙂

First, I moved my files to a fast SSD, and yeah, I was definitely hitting an IO bottleneck - my CPU isn't even that fast (an old i7) so I guess `sharp` and `libvips` must be *very* fast! It's certainly the first time I've ever seen any kind of image processing go too fast for the drives to keep up. 😃

With the SSD at ~50% load, there was still room for improvements, so:

I tried [this library](https://www.npmjs.com/package/thread-puddle) which implements a Worker pool - I tried it both with and without my `throttle` implementation above. It works about the same either way. Some improvement, but still hovering around 50-60% CPU and the SSD definitely had more to give.

Clearly, the image operations are already running in threads - so nothing gained by adding threads on top of threads. (Most likely the contrary - it's probably just unnecessary extra overhead.)

I dropped the idea of adding workers/threads, and instead tuned the number of jobs in the script I posted above, and tuned the script itself - here's a copy-and-paste version of a helper function I extracted from the example above:

```ts
async function runJobs<T>(max_jobs: number, inputs: Iterable<T>, work: (input: T) => Promise<any>) {
  let jobs: Array<Promise<void>> = [];

  async function throttle(job: Promise<void>) {
    jobs.push(job);

    job.then(() => {
      jobs = jobs.filter(item => item !== job);
    });

    while (jobs.length >= max_jobs) {
      await Promise.race(jobs);
    }
  }
  
  for (const input of inputs) {
    await throttle(work(input));
  }
}
```

It uses an `Iterable` as input - if you're streaming a list of files, this helps processing everything on the fly, spawning the `work` for each `input` as needed.

I found that `os.cpus().length` provides a reasonable number of threads.

Example:

```ts
(async () => {
  const max_jobs = os.cpus().length;

  await runJobs(max_jobs, files, async filename => {
    console.log(`Processing: ${filename}`);

    await someHeavyWorkWith(filename);
  });
})();
```

@lovell it's still not clear to me why this extra layer is necessary?

Is there any particular reason why `sharp` doesn't internally schedule the work?

I tried setting e.g. `sharp.concurrency(4)`, which seems to make things worse on WSL2, so the rationale in the docs seems to be correct - so processing a single job in multiple threads doesn't make sense.

But processing only one image at a time doesn't lead to good performance either?

The tasks are running outside the main thread anyhow - if we can't process the individual operations concurrently, wouldn't the "next best thing" be an internal worker queue, so we can at least process multiple operations in parallel? 🤔

**Comment by lovell** [comment]
@mindplay-dk Did you see https://sharp.pixelplumbing.com/api-utility#concurrency ? The bit about libuv parallelism may be of interest, as that is responsible for managing the worker queue upon which sharp schedules tasks.

**Comment by mindplay-dk** [comment]
I did see that - as mentioned, I tried `sharp.concurrency(4)`, and it did return `4`, so it wasn't being limited by the libuv setting, I think?

Do I understand correctly that the concurrency this refers to is the concurrency of `sharp` intenally, then? I was actually under the impression it had to do with concurrency in `libvips` itself - e.g. decoding a very large JPEG or resizing an image would be a multithreaded operation, but maybe that's not even a feature?

**Comment by lovell** [comment]
@mindplay-dk 

`concurrency` controls how many threads libvips will use per task, which includes resizing.

Some en/decode libraries use single-threaded I/O, e.g. libjpeg, so if you're decoding large JPEGs this may be the bottleneck.

`UV_THREADPOOL_SIZE` controls how many worker threads libuv will spawn at startup and therefore determines the maximum number of parallel tasks. Tasks queue until a libuv worker thread is available. (The same thread pool is used by Node.js for potentially blocking I/O e.g. some DNS lookups.)

You probably don't need to use Node.js worker threads; doing so may cause extra overhead.

If you need further help, please create a standalone repo with all the code and images that allows someone else to reproduce the exact scenario.

**Comment by mindplay-dk** [comment]
> Some en/decode libraries use single-threaded I/O, e.g. libjpeg, so if you're decoding large JPEGs this may be the bottleneck.

That's exactly what I'm doing.

> You probably don't need to use Node.js worker threads; doing so may cause extra overhead.

That's what my results indicated, yes.

What is the "normal" way to batch process images?

My naive first attempt was something like:

```ts
for (const image of images) {
  await sharp(image)
    .resize(200) 
    .jpeg()
    .toFile(`{$image}.thumb`);
}
```

No matter what sharp is doing internally, this will process just one image at a time.

On the other hand, I tried something like this, which did *not* work well:

```ts
await Promise.all(
  images.map(image => sharp(image)
    .resize(200) 
    .jpeg()
    .toFile(`{$image}.thumb`)
  )
);
```

I don't know if that's intended or expected to work? I mean, even if sharp internally schedules this work and doesn't try to run everything all at once, this would create thousands of promises and sharp configuration states - it wouldn't give you a nice, streaming throughput, and also nothing indicates where you are in the process or how much work is left.

To get this running smoothly for large batches of files, with a progress indicator and so on, you would have to be doing something like what I implemented above, right?

I'm sure there are plenty of dreadfully wrong ways to go about this. There's not really a "standard" way to do this in Node or JS in general, right? Someone might pick out a thread pool library like I tried, which appears to work on the surface, but they end up shipping something that performs appallingly.

Maybe this should be in the manual?

What I came up with works okay, though I'm not sure if it's the best/simplest approach?

**Comment by lovell** [comment]
Did you see https://sharp.pixelplumbing.com/api-utility#queue , which might allow for progress monitoring?

Perhaps for your scenario you might try https://github.com/sindresorhus/p-limit (or if you want to manage the queue instead of libuv then try https://github.com/sindresorhus/p-queue).

**Comment by mindplay-dk** [comment]
> Did you see https://sharp.pixelplumbing.com/api-utility#queue , which might allow for progress monitoring?

Yes, but that's still not really appropriate for processing millions of files? You need a stream - an (async) generator to avoid startup overhead from creating a huge number of promises.

> Perhaps for your scenario you might try https://github.com/sindresorhus/p-limit (or if you want to manage the queue instead of libuv then try https://github.com/sindresorhus/p-queue).

Yes, these look like viable solutions - perhaps mention those in the manual? Batch processing is a common enough requirement.

I could help out and add a chapter to the manual, if you'd like?

I'd like to save others from the work I had to do to - trying the wrong approach, or the wrong libraries (threads instead of a simple promise queue/limit) to come up with the solution above. I could include that as an example and link to those libraries.

There are far too many ways to do something horribly wrong here. 😉
