### ISSUE TITLE
Create a PNG, the height cannot > 200000

### ISSUE THREAD

**Issue by mclxly** [lovell/sharp#2539]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
0.26.3

What are the steps to reproduce?
```
const LIMIT_INPUT_PIXELS = 177610406400

sharp({
            limitInputPixels: LIMIT_INPUT_PIXELS,
            create: {
              width: 2250,
              height: 201000, // cannot > 200000
              channels: 3,
              background: { r: 255, g: 255, b: 255 }
            }
          })
            .toFile(`./tmp.png`, function(err) {
    console.log(err)
  })
```
No error report but image is corrupted/unused.

What is the expected behaviour?
Creat image success

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

Are you able to provide a sample image that helps explain the problem?

What is the output of running `npx envinfo --binaries --system`?

**Comment by lovell** [comment]
Hi, this example works for me locally on Linux, albeit rather slowly. When dealing with such large PNG files you might want to lower the `compressionLevel` setting.

https://sharp.pixelplumbing.com/api-output#png

My best guess would be that you're running out of memory. The example image is 2250 x 201000 x 3 bytes, around 1.4GB, when held uncompressed in RAM.

**Comment by mclxly** [comment]
@lovell My system is MacOS Big Sur 11.1 with 16GB RAM. I guess other limitation in unknown place.
I'm building a tool for webpage screenshot, some pages are really height.

**Comment by lovell** [comment]
@mclxly Were you able to make any progress with this? The prebuilt binaries provided in the next release of sharp should offer faster PNG output - see https://github.com/lovell/sharp/issues/2604

**Comment by mclxly** [comment]
@lovell Thank you for your great job.  Currently I make all images lower than a fixed number. I will upgrade it later.

**Comment by lovell** [comment]
v0.28.1 is now available with improved PNG compression performance. Are you able to test to see if it has helped?

**Comment by mclxly** [comment]
@lovell no lucky, same error.
```
await sharp({
                  limitInputPixels: LIMIT_INPUT_PIXELS,
                  create: {
                    width: 1000,
                    height: 200000,
                    channels: 3,
                    background: { r: 255, g: 1, b: 255 }
                  }
                })
                  .toFile(`./job_tmp.png`)
// no problem here
```
```
                    height: 200100,
// can't open it
```

**Comment by lovell** [comment]
When you say "can't open it", what tool(s) are you using? Here's the output from the above code when I run it locally, which displays correctly in Chrome and Firefox:

https://user-images.githubusercontent.com/210965/113830428-83edb800-977e-11eb-95fb-4a0614365c56.png

**Comment by mclxly** [comment]
Sorry, you are right, it can be opened by Chrome.

It can't open with default preview tool on macOS Big Sur.
