### ISSUE TITLE
Make installable using pkg

### ISSUE THREAD

**Issue by MrTomRod** [lovell/sharp#2540]
`sharp` is a dependency of a package I use. I wanted to create a standalone executable from it, but `sharp` cannot be integrated unfortunately.

```
sudo npm i pkg -g pkg  # install pkg globally
git clone https://github.com/lovell/sharp.git && cd sharp
pkg .
```

I get this error message:

```
> pkg@4.4.9
> Error! Property 'bin' does not exist in
  /.../sharp/package.json
```

Would it be possible for you to configure your package so that this works?

**Comment by lovell** [comment]
This is probably a question best asked at https://github.com/vercel/pkg as https://github.com/vercel/pkg/tree/master/test/test-79-npm/sharp suggests it is supported and working.

I strongly recommend using official npm-published versions of sharp rather than cloning the git repo as it isn't always stable and includes many development files you won't need.

**Comment by MrTomRod** [comment]
I just used the official repo to give you an easy way to reproduce the "bug". In reality, I use the stable package.

Not sure I understand what you wrote...

npm-packaging is not the same as pkg. pkg needs more instructions, for example the `package.json` needs a `bin` property as suggested by the error message. Certain files that are not automatically detected must be included manually (`pkg` property).

Pretty sure it's not a pkg issue.

**Comment by lovell** [comment]
https://github.com/vercel/pkg#usage suggests the `bin` property needs to be in the `package.json` that you as a packager define and maintain and not that of any modules upon which your software depends. They provide an example of the sort of files that you will need to create at https://github.com/vercel/pkg/tree/master/examples/express
