### ISSUE TITLE
Provide 'speed' option for libimagequant

### ISSUE THREAD

**Issue by adityapatadia** [lovell/sharp#2541]
https://sharp.pixelplumbing.com/api-output#png

PNG output has many options for libimagequant but speed option is missing. https://pngquant.org/lib/#liq_set_speed

It would be great to get access to that param.

**Comment by lovell** [comment]
Hi, you'll need to add support for this to libvips first.

**Comment by lovell** [comment]
v0.30.0 now available with this feature.
