### ISSUE TITLE
>5 speed option for heif creating square artefacts in image

### ISSUE THREAD

**Issue by vatsaljrathod** [lovell/sharp#2542]
Converting an image into AVIF format with speed = 8 and av1 as compression is creating square artefacts at the right side of the image.
It's happening with some images. In addition, it will create such artefacts only for a small range of width resize option. For this sample image, it's from 385 to 391.

Are you using the latest version?
Yes, 0.27.0

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
```
let image = await sharp(inputImage)

  let resizeOptions = {
    kernel: 'lanczos3',
    fastShrinkOnLoad: true,
    width: 388,
    height: null,
    withoutEnlargement: true,
    fit: 'inside'
  };

  let heifOptions = {
    quality: 60,
    compression: 'av1',
    lossless: false,
    speed: 8
  }

  let imageBuffer = await image
    .rotate()
    .resize(resizeOptions)
    .sharpen()
    .heif(heifOptions)
    .toBuffer({resolveWithObject: true});

```

Are you able to provide a sample image that helps explain the problem?

Original Image - https://logan.nnnow.com/content/dam/nnnow-project/05-jan-20/6JAN21-HP-Winter-Shop-Stories_Sweater.jpg
Errored Image - https://ibb.co/1zPd6Q9

What is the output of running `npx envinfo --binaries --system`?
System:
    OS: Linux 4.14 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 AMD EPYC 7R32
    Memory: 3.58 GB / 7.69 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.15.3 - /usr/bin/node
    npm: 6.14.9 - /usr/bin/npm
  Libraries:
    sharp: 0.27.0
    libvips: 8.10.5
    libheif: 1.10.0

**Comment by lovell** [comment]
I cannot reproduce this. Are you using prebuilt binaries provided by sharp or a custom libvips?

**Comment by vatsaljrathod** [comment]
Apologies, found a similar issue with libheif. Will report my findings there.
Appreciate the quick response.
