### ISSUE TITLE
How to change the color of png image

### ISSUE THREAD

**Issue by BlackCubeNo99** [lovell/sharp#2543]
```js
let { data, info } = await sharp('./logo.png')
  .resize(300, null)
  .toBuffer({ resolveWithObject: true })

for (let y = 0; y < info.height; y++) {
  for (let x = 0; x < info.width; x++) {
  const offset = info.channels * (info.width * y + x)
  data[offset] = 255
  data[offset + 1] = 0
  data[offset + 2] = 0
}

const buffer = await sharp({
  create: {
    500,
    500,
    channels: 4,
    background: '#000000',
  }
})
  .composite([{ input: data }])
  .png()
  .toBuffer()
```

I want to set it to red(#ff0000) , It can't work(`UnhandledPromiseRejectionWarning: Error: Input buffer contains unsupported image format`), Can you help me ? @lovell

**Comment by lovell** [comment]
For raw, uncompressed pixel output you'll need to add `.raw()` - see https://sharp.pixelplumbing.com/api-output#raw

**Comment by BlackCubeNo99** [comment]
> For raw, uncompressed pixel output you'll need to add `.raw()` - see https://sharp.pixelplumbing.com/api-output#raw

```js
let { data, info } = await sharp('./logo.png')
  .resize(300, null)
  .raw()
  .toBuffer({ resolveWithObject: true })

for (let y = 0; y < info.height; y++) {
  for (let x = 0; x < info.width; x++) {
  const offset = info.channels * (info.width * y + x)
  data[offset] = 255
  data[offset + 1] = 0
  data[offset + 2] = 0
}

const buffer = await sharp({
  create: {
    500,
    500,
    channels: 4,
    background: '#000000',
  }
})
  .composite([{ input: data }])
  .png()
  .toBuffer()
```

I added `raw()`, but still show error(Error: Input buffer contains unsupported image format).

**Comment by lovell** [comment]
For raw, uncompressed pixel *input* passed to the composite operation, you'll need to describe that data - see https://sharp.pixelplumbing.com/api-composite
```diff
-  .composite([{ input: data }])
+  .composite([{ input: data, raw: { width, height, channels }}])
```

**Comment by BlackCubeNo99** [comment]
> For raw, uncompressed pixel _input_ passed to the composite operation, you'll need to describe that data - see https://sharp.pixelplumbing.com/api-composite
> 
> ```diff
> -  .composite([{ input: data }])
> +  .composite([{ input: data, raw: { width, height, channels }}])
> ```

solved, thank you very much.
