### ISSUE TITLE
Cannot install sharp on docker/CentOS 8/NodeJS 15

### ISSUE THREAD

**Issue by RazorDude** [lovell/sharp#2544]
Hi.
After recreating my docker container I am no longer able to install sharp.
Here's a link to the relevant output of npm i sharp@0.27.0 --unsafe-perm --verbose:
https://gist.github.com/RazorDude/4455167784ffb07640719f42cde816cc

I have searched all old issues, tried all suggestions and have had no success.
I'm using docker on linux, the container is centos:8 with node v15 latest.
Also tried v0.24.0, which used to work - same result.

npx envinfo --binaries --system produces this output:
`
sh-4.4# npx envinfo --binaries --system
sh: envinfo: command not found
npm ERR! code 127
npm ERR! path /apps/staffed-site
npm ERR! command failed
npm ERR! command sh -c envinfo "--binaries" "--system"

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-22T14_59_38_922Z-debug.log
`

**Comment by lovell** [comment]
> npm ERR! ERR! sharp EACCES: permission denied, mkdir '/root/.npm'

Please see https://github.com/lovell/sharp/issues/2526#issuecomment-757449711

**Comment by RazorDude** [comment]
Thank you so much - It helped! The immediate issue has been resolved. This constitutes another problem, however. Although it's not a problem with sharp itself, I thought I should point it out in case somebody runs into this and reads the issue or comment.
This being a Docker installation, changing the ownership of the folder and its contents to root will make you editors (vim, vscode, etc.) unable to change the files without you putting in your root password or running them in sudo mode (not a good idea).
You'll have to change the ownership back to your user from the terminal on your machine (not in Docker) after npm install has been completed.

**Comment by lovell** [comment]
This is a breaking change in npm v7, unrelated to sharp, so if you have further comments or suggestions please open a discussion at https://github.com/npm/feedback/discussions
