### ISSUE TITLE
Take metadata from jpg to tiff

### ISSUE THREAD

**Issue by groboter** [lovell/sharp#2546]
I'm trying to convert a `input.jpg` into `output.tiff` and take over the original metadata from `input.jpg` using `withMetadata()`.
But only the `output.jpg` contains the original metadata but not the `output.tiff` (it contains only a few new data).

Is it not possible to take metadata from a jpg-file over to a tiff-file?

I'm using the following code with [exiftool-vendored](https://www.npmjs.com/package/exiftool-vendored) to extract the exif data.

```
const sharp = require('sharp');
sharp.cache(false);     // No cacheing from sharp for files
const exiftool = require("exiftool-vendored").exiftool

// Original exif data
exiftool
.read("D:\\temp\\input.JPG")
.then(tags => {
  console.log('EXIF Data ORIGINAL -----------------------')
  console.log(tags)
})

// Save with metadata JPG
sharp("D:\\temp\\input.JPG")
.withMetadata()
.jpeg({ 
  quality: 100, 
})
.toFile("D:\\temp\\output.JPG")
.then(data => {
  console.log('Save output.JPG');
  exiftool
  .read("D:\\temp\\sharpWithMetadata.JPG")
  .then(tags => {
    console.log('EXIF Data JPG -----------------------')
    console.log(tags)
  })
})

// Save with metadata TIFF
sharp("D:\\temp\\input.JPG")
.withMetadata()
.tiff({ 
  compression: 'lzw',
  quality: 100, 
})
.toFile("D:\\temp\\sharpWithMetadata.TIFF")
.then(data => {
  console.log('Save output.TIFF');
  exiftool
  .read("D:\\temp\\output.TIFF")
  .then(tags => {
    console.log('EXIF Data TIFF -----------------------')
    console.log(tags)
  })
})
```

**Comment by lovell** [comment]
Hi, libvips does not currently support EXIF in TIFF files. There's been some discussion previously at https://github.com/libvips/libvips/issues/332 that suggests it is not straightforward to support.

**Comment by groboter** [comment]
Hi lovell ok thanks for your answer. I'm experimenting now to use either `rawtherapee`, `gimp` or `darktable` as child process because they can handle EXIF data and also 16 or even 32-bit TIFFs and RAW images.
