### ISSUE TITLE
Issue installing sharp

### ISSUE THREAD

**Issue by deniz946** [lovell/sharp#2547]
Hello sharp community, I resurected a project I had from mid 2018 where I was using sharp but right now I'm not being able to install its dependencies due to this Sharp error which I'm not even able to unterstand what is failing or which is the error, if I could get some help from the community please...

I was using node 14 and it didn't work, later I tried to use node 10.1.15 as that was the version of node on mid 2018, I thought it might be due to the node version but it is not and I'm without any other clues. Thanks in beforehand for reading this issue.

Log: https://paste.ubuntu.com/p/fPNYmNzmDp/

**Comment by lovell** [comment]
This log is for sharp v0.18.4 published Sept 2017, please upgrade.

**Comment by deniz946** [comment]
Omg I feel very stupid right now... it fixed my issue. THanks a lot @lovell
