### ISSUE TITLE
What's the best way to do a buildpack of Sharp with mozjpeg and libimagequant on DigitalOcean App Platform?

### ISSUE THREAD

**Issue by nuno360** [lovell/sharp#2549]
I have a small app to resize and optimize images and I'm trying to leave a dedicated server and move it to app platform of DigitalOcean. So I would like to understand what is the best way to install and mantain libvips with mozjpeg and libimagequant on app platform of DigitalOcean.

The package.json:

```
{
    "main": "src/server.js",
    "scripts": {
        "dev": "nodemon src/server.js",
        "start": "node src/server.js"
    },
    "dependencies": {
        "axios": "^0.21.1",
        "cors": "^2.8.5",
        "dotenv": "^8.2.0",
        "express": "^4.17.1",
        "helmet": "^4.4.1",
        "imagemin": "^7.0.1",
        "imagemin-gifsicle": "^6.0.1",
        "nodemon": "^2.0.7",
        "portfinder": "^1.0.28",
        "sharp": "^0.27"
    },
    "engines": {
        "node": ">= 12.0.0",
        "npm": ">= 6.0.0"
    }
}
```

There is some way to using Sharp/libvips with mozjpeg and libimagequant without custom build, just with package.json and npm install?

**Comment by ArunJRK** [comment]
Same issue could not find a way to configure libvips with libimagequant. Do you know the general method of doing it?
