### ISSUE TITLE
Custom font not rendering on Windows.

### ISSUE THREAD

**Issue by vsDizzy** [lovell/sharp#2550]
How to configure custom font on Windows?

```svg
<svg width="400" height="300" viewBox="0 0 400 300" xmlns="http://www.w3.org/2000/svg">
  <style>
    @font-face {
      font-family: 'pro';
      src: url('pro.ttf')
    }
  </style>
  <rect width="100%" height="100%" fill="#fff" />
  <text transform="translate(0 24)" style="font-family: 'pro'; font-size: 32px">Sample text</text>
</svg>
```

Expected:
![image](https://user-images.githubusercontent.com/5798340/105772353-b7d08400-5f6a-11eb-87e9-f6faed416d65.png)

Actual:
![image](https://user-images.githubusercontent.com/5798340/105772376-bef79200-5f6a-11eb-949b-056ac9d9b46f.png)

**Comment by lovell** [comment]
You'll either need to install the font so it's registered with Windows (and can be found via its name, rather than filename) or you'll need to configure `fontconfig` via its environment variables - see https://www.freedesktop.org/software/fontconfig/fontconfig-user.htm

**Comment by vsDizzy** [comment]
It only worked after I installed font for all users. And this requires admin rights and it is not portable. So I'll just keep that as a workaround.

I tried `fontconfig` variables, but could not get it to work.
Can you share working configuration for Windows? Or I could create bare repo and we can tune it up somehow.

**Comment by lovell** [comment]
All the documentation you need is at https://www.freedesktop.org/software/fontconfig/fontconfig-user.htm

**Comment by vsDizzy** [comment]
Here is the repo https://github.com/vsDizzy/sharp-app
`fonts.conf` does nothing for me

**Comment by vsDizzy** [comment]
So the repo above works perfectly under `Ubuntu/WSL` and ​it prints debug info when `FC_DEBUG` is used.
But on `Windows` it does nothing, nor prints info.

**Comment by vsDizzy** [comment]
Also it ignores environment variable and looks `fonts.cofig` elsewhere:
![image](https://user-images.githubusercontent.com/5798340/105911226-a2269180-6032-11eb-9562-bc3be6055480.png)

**Comment by vsDizzy** [comment]
Found it. Actually to get it working you need to set environment variable outside of the `app.js` e.g. in batch file
```bat
set FONTCONFIG_PATH=.
set FC_DEBUG=1
node app
```

**Comment by lovell** [comment]
Glad you got it working, thanks for the update.
