### ISSUE TITLE
ARM64 VC++ binary?

### ISSUE THREAD

**Issue by rockcat** [lovell/sharp#2553]
Is there a prebuilt binary for arm64 using the microsoft c++ compiler?
or could you give any hints on how to go about it?
What options do you use in libvips?
thanks

**Comment by lovell** [comment]
Prebuilt `win32-arm64v8` binaries are provided for libvips but not sharp. When a CI provider makes Windows ARM64 hardware available to open source projects then we can consider providing a prebuilt sharp too.

See also #2494 for a related discussion.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by lovell** [comment]
@slimandslam Are you aware of a CI provider that makes Windows ARM64 hardware available to open source projects?

**Comment by slimandslam** [comment]
I do not. Is deploying your own Windows 11 ARM runner not an option?

**Comment by slimandslam** [comment]
CircleCI is open for comments on the subject. Feel free to post the link around:
https://circleci.canny.io/cloud-feature-requests/p/windows-on-arm-support
