### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by Rensdn** [lovell/sharp#2559]
Hi, I ran into the same problem。 I'm running the resize for my PNG file，the final result contain a file that has a bigger size than the original.
The original size is as follows：
![image](https://user-images.githubusercontent.com/25653364/106746601-b7687500-665d-11eb-95e1-a1f633610021.png)
After cropping：
![image](https://user-images.githubusercontent.com/25653364/106746520-9f90f100-665d-11eb-8365-2e34b628fabe.png)

I started using this plugin (great work btw) this week and am trying to run a few resizing and optimisations with PNG and JPG files.
So far, no issues with JPG.

Today i'm running the resize for my PNG file and i noticed the final result contain a file that has a bigger size than the original.

Do you happen to know what would be the cause for this behaviour ? 

Btw, I had a look in the links provided here :) 

Thanks a lot!

my code:

```
const sharp = require('sharp')
const fs = require('fs')

const img = 'hero';
const inputPath = `./src/public/images/desktop/${img}.png`
const outputPath = `./src/public/images/mobile/${img}.png`

const start = Date.now()
let sharpObj = sharp(inputPath).resize(1024, 500, {
  fit: sharp.fit.inside,
  withoutEnlargement: true
})

// sharpObj = sharpObj.png({ adaptiveFiltering: true, pallete: true, quality: 70, dither: 1.0  })

sharpObj
  .toFile(outputPath)
  .then(() => {
    const end = Date.now()
    console.log((end - start) / 1000)

    fs.stat(outputPath, (err, stat) => {
      console.log(err, stat)
    })
  })
  .catch(err => {
    console.error(err)
  })
```

Result in `/mobile` folder:
<img width="635" alt="Screen Shot 2020-08-07 at 14 27 13" src="https://user-images.githubusercontent.com/2061031/89671869-1c632e00-d8ba-11ea-86bc-6db76c89e638.png">

My original image in `desktop` folder:
<img width="634" alt="Screen Shot 2020-08-07 at 14 27 03" src="https://user-images.githubusercontent.com/2061031/89671883-2422d280-d8ba-11ea-883c-8882458297ad.png">

original image:
![hero](https://user-images.githubusercontent.com/2061031/89672010-664c1400-d8ba-11ea-9f88-dd09c79bfe6f.png)

_Originally posted by @victorkurauchi in https://github.com/lovell/sharp/issues/1399#issuecomment-670626686_

**Comment by lovell** [comment]
Please see https://sharp.pixelplumbing.com/api-output#png

> PNG output is always full colour at 8 or 16 bits per pixel. Indexed PNG input at 1, 2 or 4 bits per pixel is converted to 8 bits per pixel.

**Comment by Rensdn** [comment]
@lovell  
Below is my code. In this way, the size of the picture becomes smaller. If there is a problem with this writing, I hope to get your answer。
![image](https://user-images.githubusercontent.com/25653364/106838598-8fb5f300-66d7-11eb-94ef-37967f1237ea.png)

![image](https://user-images.githubusercontent.com/25653364/106839016-4fa34000-66d8-11eb-801e-ed8bf5c68dd3.png)

**Comment by lovell** [comment]
The screenshot of sample code here appears to use `toFormat` to use lossy JPEG for output, which is likely to produce smaller file sizes than lossless PNG.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
