### ISSUE TITLE
Statically link vips?

### ISSUE THREAD

**Issue by brianreavis** [lovell/sharp#256]
Is this something you would be open to a PR for sometime? I'm building my app as an artifact (bundling all node_modules, etc) on a build server (same architecture as web server), zipping it up, and having web servers unzip it and start up the app. It's been fine for awhile, but when I spun up a new web server recently it hit "cannot find libvips.so.38" errors, which I assume is due to slightly different libvips versions on the boxes. Obviously "lock down libvips" is a solution, but (imo) it would be ideal if a `npm install` would package up everything it needed.

**Comment by lovell** [comment]
Hi Brian, might https://github.com/lovell/sharp/issues/42#issuecomment-121893131 have the potential to provide what you're looking for?

**Comment by brianreavis** [comment]
Ah perfect! Sorry for the issue noise – should have run across that :)

**Comment by brianreavis** [comment]
For anyone coming across this, here's an adaption of @lovell's script for installation of an exact version of libvips: https://gist.github.com/brianreavis/b0e1141453e616f1b990
