### ISSUE TITLE
Error: pngload: libpng read error vips2png: unable to write to target

### ISSUE THREAD

**Issue by balancemechanics** [lovell/sharp#2563]
greetings, just playing back with fits and sharp on the whole. it seems that the files generated by .toFile after resizing are only suitable for further processing in sharp when resized with the ```sharp.fit.outside``` fit. other files generated give the error
```
[Error: pngload: libpng read error
vips2png: unable to write to target image-output-fill-header.png
]
``` 

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
yes, sharp@0.27.1

What are the steps to reproduce?
Run this code, using a .png file called "image.png"

```
const sharp = require("sharp");
const w = 1920;
const h = 1080;
const headLeft = 473;
const headTop = 0;

var fits = [sharp.fit.fill, sharp.fit.cover, sharp.fit.contain, sharp.fit.outside];

var file = "image.png";
var filename = file.replace(".png", "");
var out = "";


for (i = 0; i < fits.length; i++) {
out=(filename+"-output-"+fits[i]+".png")

sharp(file)
  .resize({ width:w, height:h, fit: fits[i]})

  .toFile(out)

  .then(function(info) {
  console.log(info)
  })
  .catch(function(err) {
  console.log(err)
  })
console.log(filename+" resized to "+out)

extractHeader(out, i)
}

async function extractHeader(img) {
console.log("extracting header from "+img)
var outheader = img.replace(".png", "");


await sharp(img)
  .extract({ left: headLeft, top: headTop, width: 975, height: 180 })

  .toFile(outheader+"-header.png")


  .catch(function(err) {
  console.log(err)
  })
}
```

What is the expected behaviour?
8 images to be generated from one input .png.

4 cropped/stretched images from the input using different fits.
4 extracted "header" images from each of these generated images.

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
yes, please see above.

Are you able to provide a sample image that helps explain the problem?
<img width="480" alt="Screenshot 2021-02-07 at 14 30 55" src="https://user-images.githubusercontent.com/56348559/107149597-5c7e9880-6951-11eb-8412-b79139efe184.png">
What is the output of running `npx envinfo --binaries --system`?

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 1.64 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    npm: 7.5.2 - /usr/local/bin/npm

**Comment by lovell** [comment]
Hi, there's a race condition in this code. You need to wait for `toFile()` to complete before using its output. Perhaps move the call to `extractHeader()` inside the `then()` handler.

**Comment by balancemechanics** [comment]
thanks @lovell 

to confirm, problem persists with this modification - only sharp.fit.outside generates a header. 

however it is clear that the issue exists with my flow, so i will not clog up your repo with my noobish questions further. thanks for your time in making this library!

**Comment by lovell** [comment]
The call to `toFile()` is asynchronous so you must wait for it to complete before using the output.

https://sharp.pixelplumbing.com/api-output#tofile

The following diff should help:
```diff
- sharp(file)
+ await sharp(file)
```

Your code also looks like it might be asynchronously mutating `out` to cause a second race condition. If possible, try to use `const` instead of `var` to help avoid this kind of problem.
