### ISSUE TITLE
VipsOperation: class "magicksave" not found

### ISSUE THREAD

**Issue by LosTigeros** [lovell/sharp#2564]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
Yes (0.27.1)

What are the steps to reproduce?
I'm providing a code sample.

What is the expected behaviour?
It should resize the file.

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
```js
sharp(`path to file.gif`)
  .resize(200)
  .toFile(`path to out.gif`)
  .then(() => {
    console.log(`File file.gif resized successfully.`);
  });
```

Are you able to provide a sample image that helps explain the problem?
I'm trying to resize this file: https://cdn.animesoul.com/images/cards/6/1612643245549.gif
I only get this error:
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: VipsOperation: class "magicksave" not found
Unhandled rejection of Promise at:  Error: VipsOperation: class "magicksave" not found
 Promise {
  <rejected> [Error: VipsOperation: class "magicksave" not found]
 }
```

What is the output of running `npx envinfo --binaries --system`?
```
System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Xeon(R) E-2276G CPU @ 3.80GHz
    Memory: 2.83 GB / 125.82 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.17.0 - ~/.nvm/versions/node/v12.17.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.17.0/bin/yarn
    npm: 7.5.2 - ~/.nvm/versions/node/v12.17.0/bin/npm
```

**Comment by lovell** [comment]
Please see https://sharp.pixelplumbing.com/api-output#gif

> Requires libvips compiled with support for ImageMagick or GraphicsMagick. The prebuilt binaries do not include this - see [installing a custom libvips](https://sharp.pixelplumbing.com/install#custom-libvips).

**Comment by lovell** [comment]
Commit 7017af3 improves the error messaging for this scenario.

**Comment by LosTigeros** [comment]
Thank you ❤️
I've upgraded from 0.23.3 and just didn't see that now I've to compile my own version of libvips.
