### ISSUE TITLE
cmyk values

### ISSUE THREAD

**Issue by tiichy** [lovell/sharp#2565]
Is it possible to read cmyk pixel values from the Buffer or to get a cmyk pixel array?

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/api-colour#tocolourspace
https://sharp.pixelplumbing.com/api-output#raw

```js
const cmyk = await sharp(input)
  .toColourspace('cmyk')
  .raw()
  .toBuffer();
```

**Comment by tiichy** [comment]
Many thanks!
