### ISSUE TITLE
2 channel grey+alpha, resize with non-opaque background: vector must have 1 or 3 elements

### ISSUE THREAD

**Issue by banli17** [lovell/sharp#2569]
I used gm to convert the shadowed text into a picture, and then resize the picture with sharp resize, and it reported an error.

```
nodejs.unhandledRejectionError: linear: vector must have 1 or 3 elements
```

I tried to modify the color of the shadow and found that sometimes an error is reported, such as when the shadow is #000000. When I change to #040303, no error will be reported.

When I removed the background of sharp resize, I found that no error was reported. But I need transparent text images. Here is the code:

```
// buf is the png buffer generated by gm
const input = await sharp(buf);
this.imageBuffer = await input.resize({
             width: options.width,
             height: options.height,
             // kernel: sharp.kernel.nearest,
             fit: options.fit ||'contain',
             position: this.sharpPosition,
             background: {r: 0, g: 0, b: 0, alpha: 0 },
           })
             .png()
             .toBuffer();
```

**Comment by lovell** [comment]
Please can you provide a sample input image and standalone code (e.g. no undefined variables) to allow someone else to reproduce this problem.

**Comment by banli17** [comment]
This is the picture I generated with gm, I don’t know why I get an error when I use sharp

![image](https://user-images.githubusercontent.com/12556069/108620148-020f2d00-7465-11eb-8ca6-70fce9b41757.png)

```
sharp('./axxx.png')
    .resize({
        width: 120,
        height: 30,
        // kernel: sharp.kernel.nearest,
        fit: 'contain',
        background: {r: 0, g: 0, b: 0, alpha: 0},
    })
.png().toBuffer()
```

![image](https://user-images.githubusercontent.com/12556069/108620178-4d294000-7465-11eb-9f24-e51a9618db5d.png)

**Comment by lovell** [comment]
I cannot reproduce this on Linux using the latest sharp v0.27.1 with the input image and sample code provided.

I downloaded the sample `axxx.png` image as follows:
```sh
$ curl -so axxx.png https://user-images.githubusercontent.com/12556069/108620148-020f2d00-7465-11eb-8ca6-70fce9b41757.png
```

It might be that GitHub is altering the image. Please can you provide a standalone repo with a `package.json`, sample input and code that allows someone else to reproduce this.

**Comment by banli17** [comment]
please try  sharp 0.26.3

**Comment by lovell** [comment]
Thank you, I can now reproduce this. The input image is 16-bit, 2 channel (grey+alpha) and it fails when the `background` has a non-opaque alpha channel. I'll investigate further, thanks for reporting this.

**Comment by lovell** [comment]
This problem relates to sharp's alpha detection, which doesn't currently support 16-bit, 2 channel input. Luckily libvips now provides/exposes a much better `has_alpha` feature so commit https://github.com/lovell/sharp/commit/cc37b59309d18cd5461e08e41fca97b04fff7015 switches to use that instead.

**Comment by lovell** [comment]
v0.27.2 now available with the fix.
