### ISSUE TITLE
Replicating Photoshop's auto white-balance feature

### ISSUE THREAD

**Issue by dmitrizzle** [lovell/sharp#2573]
### What are you trying to achieve?
I'd like to set a white balance based on either a custom colour or the brightest pixel in the image:

![Photoshop](https://user-images.githubusercontent.com/8587882/107609927-24977f80-6bf5-11eb-8962-160f346074fd.gif)

### Have you searched for similar questions?
Yes. Any help is appreciated, even a starting point of some sort — I am clueless.

### Are you able to provide a minimal, standalone code sample that demonstrates this question?
Any image will do `sharp("image.jpg")`

### Are you able to provide a sample image that helps explain the question?
![portra-800_xa2](https://user-images.githubusercontent.com/8587882/107609912-1a758100-6bf5-11eb-9765-ceda42acc762.jpg)

**Comment by lovell** [comment]
I'm unsure if it's exactly what you're looking for, but the white point of an image can be altered by compositing solid grey over it using the colour-dodge blend mode.

https://sharp.pixelplumbing.com/api-composite

The following example uses middle grey:

```js
sharp(input)
  .composite([
    {
      input: {
        create: {
          width: 3406,
          height: 2256,
          channels: 3,
          background: "#777",
        },
      },
      blend: "colour-dodge",
    },
  ])
  ...
```
![](https://user-images.githubusercontent.com/210965/107982280-a56ec680-6fbb-11eb-9e71-6bfe5fe77581.jpg)

**Comment by dmitrizzle** [comment]
Thank you, that answers my question.
