### ISSUE TITLE
Prebuilt binaries for v0.18.4 and earlier will end April 2021, still ~1k downloads/day, please upgrade

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#2574]
The Bintray service used to distribute binaries for versions of sharp published in 2017 and earlier will go permanently offline at the end of April 2021.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

This means prebuilt binaries for libvips <= v8.5.5 as used by sharp <= v0.18.4 will no longer be available and installation will fail.

During the last 30 days there have been >30k downloads from the Bintray service so people are still using these old versions; please upgrade.

![](https://user-images.githubusercontent.com/210965/107704073-971b6480-6cb4-11eb-98b9-c85d38f50809.png)

**Comment by lovell** [comment]
The latest download stats suggest people haven't stopped using these, so the plan is to delete 8.3.1 today, delete 8.3.3 in 2 weeks, then do a "brownout" of 8.4.2 and 8.5.5 for a 24 hour period in early April to catch anyone still using them.

**Comment by dantovbein** [comment]
@lovell  I'm not sure what should I need to upgrade. Can I have more details about that? Thanks in advance

**Comment by lovell** [comment]
If you relied on prebuilt libvips binaries for sharp v0.18.4 (published Sept 2017) or earlier then you'll need to upgrade sharp to a more recent version. If you're not using sharp as a direct dependency then `npm ls sharp` should tell you what is.
