### ISSUE TITLE
Allow install of many platform binaries in same worktree

### ISSUE THREAD

**Issue by kohtala** [lovell/sharp#2575]
The error `'${vendorPlatformId}' binaries cannot be used on the '${currentPlatformId}' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the '${currentPlatformId}' platform.` appears on about 20 issues. This feature request would allow a different solution that supports both platforms from same worktree.

Sharp currently looks if the platform in `vendor/${minimumLibvipsVersion}/platform.json` file matches the `currentPlatformId`. For example [node-sass](https://github.com/sass/node-sass) does a little differently and uses instead the platform in the directory name `vendor/${process.platform}-${process.arch}-${process.versions.modules}`. That allows download of binaries for many platforms in the same worktree. They also have an [install.js](https://github.com/sass/node-sass/blob/master/scripts/install.js) script that by default downloads the binary for current platform, but takes options for other platforms.

Perhaps something like that would work for sharp as well?

As background, I have a worktree where I can code and need the dependencies for vscode intellisense and unit tests. But for integration tests and debugging, it needs to communicate with other services and I use docker-compose to set up containers in an isolated network environment. I just have Docker mount the worktree to the container as a volume and can develop and debug there on same copy of sources when necessary. But the node image is the alpine image with different platform from host. (I have made an exception for the development image to use a distribution compatible with host, and need no help there, but it would be better to be able to test and debug with the production platform.)

Alpine, btw., would have precompiled `libvips.so` binaries that seem new enough. But it does not ship with the `pkg-config` files sharp seems to be wanting. Would be nice if it would be possible to have the install use the binary from alpine distribution. It would help avoid external downloads. We would prefer limiting who we trust or verify all download sha256 hashes we can during build to know what we have in the image.

**Comment by lovell** [comment]
Yes, currently commands like `npm rebuild` are not well supported cross-platform. We'd need to do this for both the libvips binaries under `vendor` and the sharp binaries under `build`.

> takes options for other platforms.

If you hadn't seen, the host platform can be specified at install time, e.g. `npm install --platform=linuxmusl sharp`.

> Alpine... does not ship with the pkg-config files

You should be able to find these in Alpine's `vips-dev` package.

**Comment by kohtala** [comment]
Hi. I noticed there were possibilities to specify host platform, but I did not look closer because choosing it does not help when I need two platforms in same worktree.

Thanks for the `vips-dev`. Strange I did not notice it.

**Comment by SWederell** [comment]
I'm looking to do a similar thing for an Electron app that will be built for multiple platforms. Is there any news on this?

**Comment by lovell** [comment]
Commit https://github.com/lovell/sharp/commit/e141cbacad5ee2d54c25a16d49d775fa431a4c3e adds this feature and will be included in the forthcoming v0.29.0.

**Comment by lovell** [comment]
v0.29.0 now available.

**Comment by Slapbox** [comment]
@lovell it seems like the `.node` binaries for x64 and ARM64 are bundled in our app, but the `.dylib` file is only for x64. Is that expected? I'm guessing not.

![image](https://user-images.githubusercontent.com/6835891/230681664-b9578475-3da5-41c0-91c8-acfa5c87e193.png)


Relevant comment on another issue: https://github.com/electron-userland/electron-builder/issues/7512#issuecomment-1500613835

**Comment by kohtala** [comment]
> @lovell it seems like the `.node` binaries for x64 and ARM64 are bundled in our app, but the `.dylib` file is only for x64. Is that expected? I'm guessing not.

I think it is best you create a new issue. You can mention this issue there if you like.
