### ISSUE TITLE
Change image color to white from black. RGBA

### ISSUE THREAD

**Issue by iomturner** [lovell/sharp#2576]
I have a image that's rgba. I wanted to white wash it and basically recolor the whole thing one color. In photoshop you have a color filter similar to that. I tried using tint but I see it didn't work for black to white? Has anyone tried to do this?

**Comment by lovell** [comment]
Please can you provide some sample input and expected output images that help explain this question.

**Comment by iomturner** [comment]
before:
![baseline_accessibility_black_18dp](https://user-images.githubusercontent.com/52937057/107800241-290e8600-6d24-11eb-885e-f813920363c2.png)
after:
![baseline_accessibility_white_18dp](https://user-images.githubusercontent.com/52937057/107800237-26139580-6d24-11eb-9a6a-6a53987374cf.png)

Similar to how in a svg I could change the fill from black to white.

**Comment by iomturner** [comment]
Just a little update. I was able to get this working in Jimp. 

```jimp.read('./original.png', (err, img) => {
  img
    .color([
      { apply: 'mix', params: ['#FF0000'] }, // color
      { apply: 'tint', params: [80] } // color using white (brighter)
    ])
    .write('edit.png');
});```

![edit](https://user-images.githubusercontent.com/52937057/107805902-a4c00100-6d2b-11eb-815a-1abbcaf98eba.png)

It seems tint mixes in a color using white on Jimp. I'm now looking at adjusting the brightness before I tint in Sharp but haven't got it working yet.

**Comment by lovell** [comment]
The `original.png` input image can be "cut out" from solid white (or any other colour you like) using `dest-in` composition.

```js
sharp({
  create: {
    width: 36,
    height: 36,
    channels: 4,
    background: "white",
  },
})
  .composite([
    {
      input: "original.png",
      blend: "dest-in",
    },
  ])
  .toFile("edit.png");
```
https://sharp.pixelplumbing.com/api-composite

**Comment by iomturner** [comment]
Ah cool that works great! Thanks
