### ISSUE TITLE
Output TIFF 1/20th of the original in size and Photoshop throws error when trying to open

### ISSUE THREAD

**Issue by dmitrizzle** [lovell/sharp#2577]
What are you trying to achieve?
I'm trying to process a TIFF image and output TIFF

Have you searched for similar questions?
Yes

Are you able to provide a minimal, standalone code sample that demonstrates this question?
```javascript
sharp("file.tif")
    .flatten()
    .negate()
    .greyscale()
    .median()
    .normalize()
    .toFormat({
          id: "tiff",
          compression: "lzw"
     })
    .toFile("out.tiff");
```
<img width="532" alt="Screen Shot 2021-02-13 at 3 06 25 PM" src="https://user-images.githubusercontent.com/8587882/107863987-18860a80-6e0d-11eb-8e65-7e63ee195cfe.png">

Are you able to provide a sample image that helps explain the question?
Input:
[tif0005s.tif.zip](https://github.com/lovell/sharp/files/5976699/tif0005s.tif.zip)
Output:
[tif0005s [dfrs-m1N].tiff.zip](https://github.com/lovell/sharp/files/5976700/tif0005s.dfrs-m1N.tiff.zip)

**Comment by lovell** [comment]
To set the compression to LZW you'll need to use one of the following approachs:

```js
  .toFormat({
    id: "tiff"
  }, {
    compression: "lzw"
  })
```
or more simply:
```js
  .tiff({
    compression: "lzw"
  })
```

When you say "1/20th of the original in size", I see the same 1000x665 dimensions on the output image.

**Comment by dmitrizzle** [comment]
Ah I got the function signature wrong, thanks for the help, @lovell 😅

By 1/20th of the size, I meant file byte size (being the same format and compression I expected input and output to weigh roughly the same). Now that I fixed my code, file size/compression seems correct and Photoshop stopped complaining.
