### ISSUE TITLE
extend: use default value of zero for missing properties

### ISSUE THREAD

**Issue by themre** [lovell/sharp#2578]
Hi,
I'm trying to use `extend` function, but having issue with it. For a simple image I get this error:
`Expected integer or object for extend but received [object Object] of type object`. 

I'm using latest version on Windows, node v12, npm v6.

My code is the following:
```
const img = await sharp(path);
    const resized = await img
      .resize(200, 200)
      .extend({
        top: 20,
        bottom: 20,
      })
```

Below is also a sample image. Any idea what might be wrong? Thanks! 

![sample](https://user-images.githubusercontent.com/10845050/107937430-30cc6580-6f84-11eb-951c-31071da4f9fa.png)

**Comment by lovell** [comment]
Hi, you'll need to add values for `left` and `right` too.
```js
.extend({
  top: 20,
  bottom: 20,
  left: 0,
  right: 0
})
```
We should probably improve this so zero is used as the default value, as well as fix the error messaging.

**Comment by themre** [comment]
Yes, you are totally correct. Previous when I tried with all properties I had float number somewhere and was also strange. Thanks for the help!

**Comment by lovell** [comment]
No probs, I'm going to leave this issue open to track improvements to `extend` defaults/errors.

**Comment by lovell** [comment]
Missing edge values now default to zero as of v0.28.0.
