### ISSUE TITLE
Level adjustments based on histogram

### ISSUE THREAD

**Issue by dmitrizzle** [lovell/sharp#2579]
### What are you trying to achieve?
I would like to detect values `a` & `b` based on the distribution of brightness where `a` & `b` are positioned like so:

<img width="315" alt="Screen Shot 2021-02-15 at 4 21 39 PM" src="https://user-images.githubusercontent.com/8587882/108004253-2755f400-6faa-11eb-9ab0-22347ed58a09.png">

Perhaps I can start with a hard-coded % value that should treat the histogram data as noise and a/b can be on either side of "usable" data.

### Have you searched for similar questions?
Yes. I think this is similar to `normalize` but I'm looking to write something a little more custom that can discard "fogging" (i.e. the hard-coded %) in an image.

### Are you able to provide a minimal, standalone code sample that demonstrates this question?
Essentially, I'm trying to apply levels correction (like in the screenshot above) to each colour channel of an image. Below is an example of how I extract the green channel. Before sending it into a buffer, I apply `linear`. My goal is to detect what those values should be based on a histogram. In this case

```javascript
const levels = (min, max) => {
  const scale = 255 / (max - min);
  return [scale, -min * scale];
};
sharp("image.jpg")
  .extractChannel("green")
  .toColorspace("b-w")
  .linear(...levels(54, 185))
  .toBuffer();
```

### Are you able to provide a sample image that helps explain the question?
![example](https://user-images.githubusercontent.com/8587882/108004518-ef9b7c00-6faa-11eb-85d1-1af1dbee4faa.jpg)

**Comment by lovell** [comment]
Did you see https://sharp.pixelplumbing.com/api-input#stats ? The response includes per-channel min and max values, which might provide what you're looking for.

**Comment by dmitrizzle** [comment]
I have but the numbers don't seem to line up. With the above example in mind, the green channel (eyeballed via Photoshop UI) suggests setting levels to 54 and 185, however, the stats provide these values: `{ min: 33, max: 232 }`.

Perhaps I need some different or differently-calculated statistic or to implement something like this https://github.com/lovell/sharp/issues/1066#issuecomment-351558542 on a per-channel basis?

**Comment by lovell** [comment]
The `minX`, `minY`, `maxX` and `maxY` properties in the response from `stats` provide the pixel coordinates. From the screenshot of the histogram it looks like you might want to ignore the lowest and highest values, so perhaps apply a Gaussian blur first to "average" things out a bit.

```js
const blurred = await sharp(input).blur(5).toBuffer();
const { channels } = await sharp(blurred).stats();
```

**Comment by dmitrizzle** [comment]
This is brilliant, thank you. Is there a book you'd recommend where I can learn more colour manipulation techniques?

**Comment by lovell** [comment]
https://www.pearson.com/us/higher-education/program/Jain-Fundamentals-of-Digital-Image-Processing/PGM212327.html is an often-cited book.

https://www.wiley.com/en-gb/Fundamentals+of+Digital+Image+Processing%3A+A+Practical+Approach+with+Examples+in+Matlab-p-9780470844724 is possibly riding on having the same title but does looks like it covers most topics.

https://en.wikipedia.org/wiki/Category:Image_processing provides plenty of options if you're looking to fall down a Wikipedia-shaped rabbit hole.

**Comment by dmitrizzle** [comment]
Thank you!
