### ISSUE TITLE
.icns (macOS icons) to .png

### ISSUE THREAD

**Issue by elrumo** [lovell/sharp#2580]
### What are you trying to achieve?
Convert .icns to .png.
Would converting an macOS icon file (.icns) to .png? If not possible with Sharp, does anybody know of any other library or way this could be done?

### Have you searched for similar questions?
Yes, I could not find any questions related to .icns files.

### Are you able to provide a minimal, standalone code sample that demonstrates this question?
```
sharp('test.icns')
   .toBuffer()
   .then( data => {
      fs.writeFileSync("test.png", data);
   })
   .catch(err => {
      console.log("err: ", err)
 })
```

**Comment by lovell** [comment]
macOS provides a command line tool for this - see https://www.macworld.com/article/1060156/sipsicns.html

**Comment by elrumo** [comment]
Yeah, that works great but I'm looking for a way to do it on a Linux system. I've also found another node library called "iconutil" which worked fine on my mac, but not on the Ubuntu server I'd need it to run on.

**Comment by lovell** [comment]
The `icns2png` command line tool is available in most Linux distributions e.g. https://packages.ubuntu.com/focal/icnsutils

**Comment by elrumo** [comment]
@lovell That's what I've been using to convert png images to icns, but it doesn't work the other way around, .icns to .png.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by cdwmhcc** [comment]
> I hope this information helped. Please feel free to re-open with more details if further assistance is required.

sips does not support formats such as webp. Can sharp support icns?
