### ISSUE TITLE
recomb: bands in must equal matrix width, greyscale image

### ISSUE THREAD

**Issue by CharlieHess** [lovell/sharp#2584]
* Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
Yes

* What are the steps to reproduce?
``` js
sharp().recomb([
  [0.3588, 0.7044, 0.1368],
  [0.299, 0.587, 0.114],
  [0.2392, 0.4696, 0.0912],
])
```
On the image below (taken from TMDb's API). You'll get an error:

```
recomb: bands in must equal matrix width
```

* What is the expected behaviour?
The recomb operation succeeds instead of throwing

* Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
Code snippet above, combined with a `pipe`, is all you need

* Are you able to provide a sample image that helps explain the problem?
The image below, taken from TMDb's `backdrop_image` for Malcolm & Marie: https://image.tmdb.org/t/p/w1280/iOrjCeIyRb4vDY3vbPSaEBCA1D3.jpg

![722913-backdrop](https://user-images.githubusercontent.com/1865957/108230330-a7956a00-710e-11eb-9713-504d5a034240.jpeg)

* What is the output of running `npx envinfo --binaries --system`?
```
  System:
    OS: macOS 11.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 568.23 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
```

**Comment by lovell** [comment]
Hi, this sample input is a single-channel greyscale image. It looks like the `recomb` operation is correctly converting to sRGB but there's a bug where it uses the wrong channel count, in this example `image.bands()` will be `1`, from the single-channel image.

https://github.com/lovell/sharp/blob/df7b8ba73808fc494be413e88cfb621b6279218c/src/operations.cc#L152-L154

**Comment by CharlieHess** [comment]
Ah, good info @lovell thanks. In the meantime I've worked around it by checking `.metadata().channels` and skipping this step in my pipeline for greyscale images.

**Comment by lovell** [comment]
Commit https://github.com/lovell/sharp/commit/f6f16b91db11dd80658c009e90e53855d715e7fa adds a test for this, as well as fixing it. This will be in v0.27.2, thanks for reporting.

**Comment by lovell** [comment]
v0.27.2 now available with the fix.
