### ISSUE TITLE
require(sharp) throws error.

### ISSUE THREAD

**Issue by nph278** [lovell/sharp#2585]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`? I am on the latest version, 0.27.1

What are the steps to reproduce? `npm install sharp`, then run `const sharp = require("sharp")` in node.js `v14.15.5` use npm `v7.5.4`

What is the expected behaviour? You would get the sharp module from `require`.

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem? [sharp-error](https://github.com/nph278/sharp-error)

Are you able to provide a sample image that helps explain the problem?
![Screen Shot](https://user-images.githubusercontent.com/69152943/108374279-c9eebc80-71ce-11eb-96a3-bbc6b263ca72.png)

What is the output of running `npx envinfo --binaries --system`?

```
  System:
    OS: macOS 11.0.1
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 21.05 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.5 - /usr/local/bin/node
    npm: 7.5.4 - /usr/local/bin/npm
```

**Comment by nph278** [comment]
I found the problem: I globally set `npm` to ignore postinstall and preinstall scripts.

If you turn them back on with `npm config set ignore-scripts false`, it compiles and runs successfully.

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/install#common-problems

> The `npm install --ignore-scripts=false` flag must be used when `npm` has been configured to ignore installation scripts.
