### ISSUE TITLE
failed during Build

### ISSUE THREAD

**Issue by Adamkaram** [lovell/sharp#2587]
i was installing sharp for older project  but i got this 
`[4/4] Building fresh packages...
[12/12] ⠠ sharp
[-/12] ⠠ waiting...
[7/12] ⠠ sharp
[-/12] ⠠ waiting...
error C:\Users\Adam\Downloads\Ecommerce-project\server\node_modules\sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments:
Directory: C:\Users\Adam\Downloads\Ecommerce-project\server\node_modules\sharp
Output:
info sharp Using cached C:\Users\Adam\AppData\Roaming\npm-cache\_libvips\libvips-8.7.4-win32-x64.tar.gz
info sharp Creating C:\Users\Adam\Downloads\Ecommerce-project\server\node_modules\sharp\build\Release
info sharp Copying DLLs from C:\Users\Adam\Downloads\Ecommerce-project\server\node_modules\sharp\vendor\lib to C:\Users\Adam\Downloads\Ecommerce-project\server\node_modules\sharp\build\Release
prebuild-install WARN install No prebuilt binaries found (target=15.9.0 runtime=node arch=x64 libc= platform=win32)

C:\Users\Adam\Downloads\Ecommerce-project\server\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@15.9.0 | win32 | x64
gyp info find Python using Python version 3.9.2 found at "C:\Python39\python.exe"
gyp http GET https://nodejs.org/download/release/v15.9.0/node-v15.9.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v15.9.0/node-v15.9.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v15.9.0/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v15.9.0/win-x86/node.lib
gyp http GET https://nodejs.org/download/release/v15.9.0/win-x64/node.lib
gyp http GET https://nodejs.org/download/release/v15.9.0/win-arm64/node.lib
gyp http 200 https://nodejs.org/download/release/v15.9.0/SHASUMS256.txt
gyp http 404 https://nodejs.org/download/release/v15.9.0/win-arm64/node.lib
gyp http 200 https://nodejs.org/download/release/v15.9.0/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v15.9.0/win-x86/node.lib
gyp info find VS using VS2019 (16.8.30804.86) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python39\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Adam\\Downloads\\Ecommerce-project\\server\\node_modules\\sharp\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Adam\\AppData\\Local\\node-gyp\\Cache\\15.9.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Adam\\AppData\\Local\\node-gyp\\Cache\\15.9.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Adam\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\15.9.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Adam\\Downloads\\Ecommerce-project\\server\\node_modules\\sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Adam\\Downloads\\Ecommerce-project\\server\\node_modules\\sharp\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  VError.cpp
  VInterpolate.cpp
  VImage.cpp
  win_delay_load_hook.cc
     Creating library C:\Users\Adam\Downloads\Ecommerce-project\server\node_modules\sharp\build\Release\libvips-cpp.lib and object C:\Users\Adam\Downloads\Ecommerce-project\server\node_modules\sharp\build\Release\libvips-cpp.exp
  Generating code
  Previous IPDB not found, fall back to full compilation.
  All 910 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  libvips-cpp.vcxproj -> C:\Users\Adam\Downloads\Ecommerce-project\server\node_modules\sharp\build\Release\\libvips-cpp.dll
  common.cc
  metadata.cc
C:\Users\Adam\Downloads\Ecommerce-project\server\node_modules\sharp\src\metadata.cc(34,20): warning C4834: discarding return value of function with 'nodiscard' attribute [C:\Users\Adam\Downloads\Ecommerce-project\server\node_modules\sharp\build\sharp.vcxproj]
C:\Users\Adam\Downloads\Ecommerce-project\server\node_modules\sharp\src\metadata.cc(190,20): warning C4834: discarding return value of function with 'nodiscard' attribute [C:\Users\Adam\Downloads\Ecommerce-project\server\node_modules\sharp\build\sharp.vcxproj]
  stats.cc
C:\Users\Adam\Downloads\Ecommerce-project\server\node_modules\sharp\src\stats.cc(35,20): warning C4834: discarding return value of function 
with 'nodiscard' attribute [C:\Users\Adam\Downloads\Ecommerce-project\server\node_modules\sharp\build\sharp.vcxproj]
C:\Users\Adam\Downloads\Ecommerce-project\server\node_modules\sharp\src\stats.cc(130,1): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Adam\Downloads\Ecommerce-project\server\node_modules\sharp\build\sharp.vcxproj]
C:\Users\Adam\Downloads\Ecommerce-project\server\node_modules\sharp\src\stats.cc(140,20): warning C4834: discarding return value of function with 'nodiscard' attribute [C:\Users\Adam\Downloads\Ecommerce-project\server\node_modules\sharp\build\sharp.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Adam\Downloads\Ecommerce-project\server\node_modules\sharp
`
i'm in 
OS windows 10 
and using yarn install

**Comment by lovell** [comment]
It looks like you're using v0.22.x, which is 2 years old. Please upgrade for Node.js 15 support.

As an aside, I notice you ignored/deleted the questions in the installation issue template. Was there a reason for this?

**Comment by Adamkaram** [comment]
> It looks like you're using v0.22.x, which is 2 years old. Please upgrade for Node.js 15 support.
> 
> As an aside, I notice you ignored/deleted the questions in the installation issue template. Was there a reason for this?

it's worked fine after i install it separately and it 0.27.1 now 

yeah i know sorry for that but this the first time i use sharp i will be a good requester in the next time ❤

**Comment by lovell** [comment]
Great, glad you worked it out.

Issue templates in open source projects, not just this one, are usually there to help people help themselves. Suggestions for making them more relevant/useful are always welcome.
