### ISSUE TITLE
JPG isn't progressive

### ISSUE THREAD

**Issue by dnish** [lovell/sharp#2589]
Hey,
I'm using the following commands to manipulate a baseline JPG file and create a new one which should be progressive to.

```
     sharpInstance = sharp(filePath);
     sharpInstance.rotate();
     sharpInstance.resize({height: 2400, withoutEnlargement: true});
     sharpInstance.toFormat("jpg",{progressive:true});
        
     const buffer = await sharpInstance.toBuffer();
     await sharp(buffer).toFile(filePath);
```

The output file contains the following information:
```
file test.jpg
test.jpg: JPEG image data, baseline, precision 8, 1800x2400, components 3
```

The output file isn't progressive. I'm using version 0.27.1 and tested it on a Mac.

**Comment by lovell** [comment]
Hi, the contents of `buffer` will be a progressive JPEG, but `sharp(buffer).toFile(filePath)` processes that output via a new sharp instance, which will use the default of non-progressive output.

Try:
```diff
- const buffer = await sharpInstance.toBuffer();
- await sharp(buffer).toFile(filePath);
+ await sharpInstance.toFile(filePath);
```
or:
```diff
- await sharp(buffer).toFile(filePath);
+ await sharp(buffer).jpeg({ progressive: true }).toFile(filePath);
```

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
