### ISSUE TITLE
Clang/llvm segfaults when using multiple C++ addons (was: error when using with websockets)

### ISSUE THREAD

**Issue by aeosynth** [lovell/sharp#259]
app.js:
```
require('ws')
require('sharp')
```

```
$ node app.js 
fish: 'node app.js' terminated by signal SIGSEGV (Address boundary error)
```

[`websockets/ws`](https://github.com/websockets/ws) also recently added support for iojs v3

edit: this is using sharp master

**Comment by lovell** [comment]
Hi James, are you using gcc 4.9? This might be related to a problem with the use of `-O3` in the `bufferutil` dependency of `ws` - see https://github.com/websockets/bufferutil/issues/1

**Comment by aeosynth** [comment]
i'm on osx 10.9.5, and my gcc is llvm 6.0. removing the `bufferutil` dependency does not help.

**Comment by lovell** [comment]
I've not be able to reproduce this locally on Linux with io.js v3.2.0 and compiling with gcc 5.1. I'll try to run a similar test using a Mac tomorrow.

Given you're using llvm, are you able to run the app that segfaults via its `lldb` debugging tool and get a backtrace?

**Comment by aeosynth** [comment]
i've never used lldb before, but here's the trace:

```
$ lldb node app.js 
(lldb) target create "node"
Current executable set to 'node' (x86_64).
(lldb) settings set -- target.run-args  "app.js"
(lldb) run
Process 75395 launched: '/usr/local/bin/node' (x86_64)
Process 75395 stopped
* thread #1: tid = 0x6296a, 0x00000001017dcf96 sharp.node`Nan::imp::FunctionWrapper* Nan::imp::GetWrapper<void (*)(Nan::FunctionCallbackInfo<v8::Value> const&), Nan::imp::FunctionWrapper>(void (*)(Nan::FunctionCallbackInfo<v8::Value> const&)) [inlined] std::__1::__tree<std::__1::__value_type<void (__parent=<unavailable>, __child=0x00000001017c82c8, __new_node=0x00000001016422f0)(Nan::FunctionCallbackInfo<v8::Value> const&), Nan::imp::FunctionWrapper*>, std::__1::__map_value_compare<void (*)(Nan::FunctionCallbackInfo<v8::Value> const&), std::__1::__value_type<void (*)(Nan::FunctionCallbackInfo<v8::Value> const&), Nan::imp::FunctionWrapper*>, std::__1::less<void (*)(Nan::FunctionCallbackInfo<v8::Value> const&)>, true>, std::__1::allocator<std::__1::__value_type<void (*)(Nan::FunctionCallbackInfo<v8::Value> const&), Nan::imp::FunctionWrapper*> > >::__insert_node_at(std::__1::__tree_node_base<void*>*, std::__1::__tree_node_base<void*>*&, std::__1::__tree_node_base<void*>*) + 25 at __tree:1715, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001017dcf96 sharp.node`Nan::imp::FunctionWrapper* Nan::imp::GetWrapper<void (*)(Nan::FunctionCallbackInfo<v8::Value> const&), Nan::imp::FunctionWrapper>(void (*)(Nan::FunctionCallbackInfo<v8::Value> const&)) [inlined] std::__1::__tree<std::__1::__value_type<void (__parent=<unavailable>, __child=0x00000001017c82c8, __new_node=0x00000001016422f0)(Nan::FunctionCallbackInfo<v8::Value> const&), Nan::imp::FunctionWrapper*>, std::__1::__map_value_compare<void (*)(Nan::FunctionCallbackInfo<v8::Value> const&), std::__1::__value_type<void (*)(Nan::FunctionCallbackInfo<v8::Value> const&), Nan::imp::FunctionWrapper*>, std::__1::less<void (*)(Nan::FunctionCallbackInfo<v8::Value> const&)>, true>, std::__1::allocator<std::__1::__value_type<void (*)(Nan::FunctionCallbackInfo<v8::Value> const&), Nan::imp::FunctionWrapper*> > >::__insert_node_at(std::__1::__tree_node_base<void*>*, std::__1::__tree_node_base<void*>*&, std::__1::__tree_node_base<void*>*) + 25 at __tree:1715
   1712	    __new_node->__right_  = nullptr;
   1713	    __new_node->__parent_ = __parent;
   1714	    __child = __new_node;
-> 1715	    if (__begin_node()->__left_ != nullptr)
   1716	        __begin_node() = static_cast<__node_pointer>(__begin_node()->__left_);
   1717	    __tree_balance_after_insert(__end_node()->__left_, __child);
   1718	    ++size();
```

**Comment by lovell** [comment]
Thank you, the backtrace you've provided is very useful. `EXC_BAD_ACCESS (code=1, address=0x0)` suggests we're looking at a null pointer problem.

The `static std::map` created inside `Nan::GetWrapper` https://github.com/nodejs/nan/blob/master/nan_callbacks.h#L110 fails at https://github.com/llvm-mirror/libcxx/blob/master/include/__tree#L1704 when an insert takes place.

Function statics should be thread-safe by default however http://stackoverflow.com/questions/17623815/why-does-compile-order-sometimes-cause-a-segmentation-fault-when-using-stdmap has a suggestion to use an _Initializer Function Trick_.

Give me a day or two to see if I can reproduce this problem consistently using clang/llvm. If so, this might require a change to the `nan` module.

**Comment by lovell** [comment]
I can recreate this problem consistently using clang 6.0 (llvm 3.5) and io.js v3.2.0 with pretty much any two nan-based native modules that invoke a call to `Nan::GetWrapper` at require-time.

I think we've hit the same problem described in
http://stackoverflow.com/questions/19212474/clang-links-to-different-locations-when-referring-a-templated-static-variable-fr

@kkoopa are you able to provide any suggestions or help?

**Comment by kkoopa** [comment]
Remove https://github.com/lovell/sharp/blob/master/binding.gyp#L66

**Comment by lovell** [comment]
Thanks for the swift reply @kkoopa and great spot. The use of `libc++` is to support the `tuple` type but given its current (lack of) use I should be able to replace it with the more portable `pair` type.

**Comment by lovell** [comment]
See also the related https://github.com/strongloop/fsevents/issues/82 and possible fix https://github.com/nodejs/nan/pull/431.

**Comment by lovell** [comment]
@aeosynth This should be fixed on the `master` branch - are you able to re-test?

**Comment by aeosynth** [comment]
works for me, thanks!
