### ISSUE TITLE
Can i upload an image from a URL?

### ISSUE THREAD

**Issue by alexandredev3** [lovell/sharp#2592]
What are you trying to achieve?

I'm trying to load an image from a url, but it always returns an Error: ```Input file is missing```.
When I put the complete directory of my image, example: "/home/user/www/myapp/uploads/filename.png" works well, my question is: can I load a image from a url? or is this a bug? or something i'm doing wrong?

Are you able to provide a minimal, standalone code sample that demonstrates this question?

Works Well:
```ts
    sharp("/home/user/www/myapp/uploads/filename.png")
      .raw()
      .ensureAlpha()
      .resize({ width: 300, height: 300, fit: 'inside' })
      .toBuffer((err, buffer, { width, height }) => {
        if (err) {
          throw new Error(err);
        }

        return { buffer, width, height };
      });
```

Throw a Error: ```Input file is missing```:
```ts
    sharp("https://images.unsplash.com/photo-1614059632169-522876ce04c8?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=334&q=80")
      .raw()
      .ensureAlpha()
      .resize({ width: 300, height: 300, fit: 'inside' })
      .toBuffer((err, buffer, { width, height }) => {
        if (err) {
          throw new Error(err);
        }

        return { buffer, width, height };
      });
```

**Comment by lovell** [comment]
Ola, you'll need to add your own networking logic. See https://github.com/lovell/sharp/issues/1901 for some examples.

**Comment by alexandredev3** [comment]
> Ola, you'll need to add your own networking logic. See #1901 for some examples.

thanks man, it worked here!
