### ISSUE TITLE
Crash with 2 different versions of sharp running on Alpine Linux inside home-assistant inside a proxmox VM

### ISSUE THREAD

**Issue by danielo515** [lovell/sharp#2595]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

```
node-red-project@0.0.1 /config/node-red
├─┬ node-red-contrib-deepstack@0.0.11
│ └── sharp@0.26.3
└── sharp@0.27.1
```

Seems that I do not (latest is 0.27.2) and I in fact have two sharp versions.

What are the steps to reproduce?
Just loading a image from any of my security cameras triggers a core dump

In my case all I have to do is to load the attached image and try any operation on it: draw on it, resize or save to a different location. Everything triggers a crash + memory dump

What is the expected behaviour?

To not crash and perform the operations on the image

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
I'll try to do it later today

Are you able to provide a sample image that helps explain the problem?
Yes, find it attached

![raw_body](https://user-images.githubusercontent.com/2270425/109124577-61ae5680-774b-11eb-87bc-69b12e34966f.jpg)

What is the output of running `npx envinfo --binaries --system`?
npx: installed 1 in 4.142s

  System:
    OS: Linux 5.4 Alpine Linux
    CPU: (2) x64 Common KVM processor
    Memory: 105.91 MB / 3.74 GB
    Container: Yes
    Shell: 1.32.1 - /bin/ash
  Binaries:
    Node: 14.15.5 - /usr/bin/node
    npm: 6.14.11 - /usr/bin/npm

But I can provide details about the environment. The code runs inside a docker container that runs inside home-assistant that runs inside a proxmox VM.

**Comment by lovell** [comment]
>> What is the output of running `npx envinfo --binaries --system`?

> I'll try to do add it later (don't have access RN to the device)
> The code runs inside a docker container that runs inside home-assistant that runs inside a proxmox VM.

The output of this command run inside the container will help.

Please ensure installation was for the relevant platform - see https://sharp.pixelplumbing.com/install#common-problems

**Comment by lovell** [comment]
@danielo515 Were you able to make any progress with this?

**Comment by danielo515** [comment]
> @danielo515 Were you able to make any progress with this?

Sorry I forgot about this (I have been away from my homelab for a while anyway). I just updated the issue with the NPX env info

**Comment by lovell** [comment]
Thanks for the update, I spotted you posted at https://github.com/iceglow/node-red-contrib-deepstack/issues/3 too.

Prebuilt binaries are provided for musl-based Linux on x64, but it's possible two different versions of these are causing a conflict. Please can you upgrade/downgrade the versions of sharp so they match.

The next release of sharp, v0.28.0, will provide statically-linked binaries that should remove almost all possibility of this class of problem from occurring. Please subscribe to https://github.com/lovell/sharp/issues/2604 for updates.

**Comment by danielo515** [comment]
I am not sure that the conflicting version is library's fault. I installed it manually to test the problem with my own code but on the same environment. Do you think that removing it will fix the problem? I will try and comment again.

**Comment by danielo515** [comment]
I just uninstalled the version I installed, tried the same example and the same occurs:

![image](https://user-images.githubusercontent.com/2270425/112952308-a3606180-913c-11eb-8d7c-39304dbecf28.png)

The code of the outline function is here:

https://github.com/iceglow/node-red-contrib-deepstack/blob/7ac06c33bb726727323fbd1a8957aa6651e39551/image-manipulation.js

```
const outline = function(buffer, outlines, outlineColor) {
        return sharp(buffer).metadata().then(meta => {
            let svgOverlay = '';

            outlines.forEach(o => {
                svgOverlay += '<rect x="' + o.x + '" y="' + o.y + '" width="' + o.width + '" height="' + o.height + '" ' +
                    'style="fill:none;stroke:' + outlineColor + ';stroke-width:3;" />';
            });
            return '<svg width="' + meta.width + '" height="' + meta.height + '">' + svgOverlay + '</svg>';
        }).then(overlay => {
            return sharp(buffer).composite([{
                input: Buffer.from(overlay),
                blend: 'over'
            }]).toBuffer();
        });
    }

```

**Comment by danielo515** [comment]
I can confirm that upgrading sharp to the latest version (0.28) inside the library this problem dissapears, so now it is the task of the extension to update to latest sharp.

Thank you very much for your help on this.
