### ISSUE TITLE
yarn install, npm ci are not copying pre-built sharp...although logs say otherwise (Cannot find module '../build/Release/sharp.node')

### ISSUE THREAD

**Issue by mattpr** [lovell/sharp#2596]
Server complains/errors when trying to start strapi, a node_module that depends on sharp.

```
Something went wrong installing the "sharp" module
Cannot find module '../build/Release/sharp.node'
```

Indeed that file is missing.  It is not being built on the CI when running:
`yarn install --frozen-lockfile --production=true --verbose`

Same thing on mac builds fine...but verbose logs are not noticeably different.

No idea what is going on here.  "yarn not running build scripts" hasn't led me to anything useful.  It can't be completely broken as it works on the mac, but the fact it silently fails on the CI is frustrating.

# Questionnaire

**Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?**

Yes

**Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?**

Yes.  
CI: Docker Image: node:12.21.0-buster-slim (why it is running as root)
Server: Ubuntu 20 LTS
Both linux x86_64

Server complains `Cannot find module '../build/Release/sharp.node'` because of course the file isn't there because it isn't getting built (or prebuilt copied).

Even if there was an architecture mismatch (build vs use), it isn't getting built/copied at all in the single architecture CI.

**Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?**

Dependency of strapi.  Using (almost) latest strapi version.  If this is a version-specific issue (ie strapi needs to update their dependency), just let me know and I'll open the ticket there referencing this.  Thanks!

```
$ yarn why sharp
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "sharp"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "sharp@0.27.1"
info Reasons this module exists
   - "strapi-plugin-upload" depends on it
   - Hoisted from "strapi-plugin-upload#sharp"
info Disk size without dependencies: "35.6MB"
info Disk size with unique dependencies: "37.03MB"
info Disk size with transitive dependencies: "35.6MB"
info Number of shared dependencies: 42
✨  Done in 1.60s.
```

**If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?**

Using yarn as that is what strapi supports.

**If you are using npm v7, does the user running `npm install` own the directory it is run in?**

yarn.  Running within gitlab CI runner so have limited control over CWD and parent directory permissions.

**If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?**

Using yarn.  Yarn has `yarn install --ignore-scripts` **which we are not using**.  There doesn't appear to be a way to tell it to "NOT ignore scripts".  There are no `.{yarn,npm}rc` in the repo.

The CI is running: 
```bash
yarn install --frozen-lockfile --production=true --verbose > $ARTIFACT_PATH/yarn.log
```

Then it builds a tarball which is deployed to the ubuntu server by tarring current directory contents excluding a few directories.

```bash
tar -cvzf "$ARTIFACT_PATH/$ARTIFACT_NAME" --exclude .git --exclude "$NPM_CACHE_DIR" --exclude "$ARTIFACT_PATH" .   >> $ARTIFACT_PATH/yarn.log
```

**What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?**

No error messages.  The resulting npm_modules (as seen through verbose tar) shows that sharp does **not** have a `build` directory.

**Log** of the CI including:
- `yarn install --frozen-lockfile --production=true --verbose`
- `tar -cvzf "$ARTIFACT_PATH/$ARTIFACT_NAME" --exclude .git --exclude "$NPM_CACHE_DIR" --exclude "$ARTIFACT_PATH" .`

- Filtered to lines containing `/sharp/`: [yarn-sharp.log](https://github.com/lovell/sharp/files/6048617/yarn-sharp.log)
- Full verbose log: [yarn-full.log](https://github.com/lovell/sharp/files/6049152/yarn-full.log)

**What is the output of running `npx envinfo --binaries --system`?**

```
$ npx envinfo --binaries --system
npx: installed 1 in 1.126s
  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (1) x64 Intel(R) Xeon(R) CPU @ 2.30GHz
    Memory: 1.81 GB / 3.61 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 12.21.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
```

# Ideas

Pretty clear the problem is binary build script is not running as the `/build/` directory is not there in node_modules after running `yarn install` (well the longer flavor above).

Maybe incompatibility between sharp and yarn?  I'm not a yarn expert, just stuck with it because that is what the strapi guys support and what another developer started with when they decided to use strapi.

Could also be that the script is running but we don't see output for [some reason](https://github.com/yarnpkg/yarn/issues/5476#issuecomment-463633408).

> There is a known issue where if a script's output doesn't contains an ending newline, then it's output gets overwritten by yarn's own output. It is possible your script is being run, just the output is not being displayed?

On my dev machine (mac), if I `rm -rf node_modules` and then run the exact same `yarn install ...` command... the sharp `/build/` dir **IS** created...but the yarn verbose logs are not noticeably different between the mac and the CI.  

## Logs compared

The same section of log (`[5/5] Building fresh packages...`) on both mac and linux.

<details>
  <summary>mac (works)</summary>

```
$ rm -rf node_modules
$ yarn install --frozen-lockfile --production=true --verbose > ~/tmp/yarn-sharp.log
warning " > strapi-connector-bookshelf@3.5.0" has incorrect peer dependency "knex@^0.20.0".

--- Log Output ---

...
[5/5] Building fresh packages...
verbose 102.35097777 Font Awesome Free 0.2.34 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
verbose 102.473887125 
verbose 102.516914523 Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
verbose 102.61905779 Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
verbose 102.665427294 Font Awesome Free 1.2.34 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
verbose 103.132054789 Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
verbose 103.530208792 Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
verbose 104.171882315 Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
verbose 104.352220954 
verbose 109.949178202 gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.19.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/Users/USERNAME/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/USERNAME/dev/PROJECT-NAME/node_modules/fsevents/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/USERNAME/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/USERNAME/Library/Caches/node-gyp/12.19.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/USERNAME/Library/Caches/node-gyp/12.19.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/USERNAME/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/USERNAME/Library/Caches/node-gyp/12.19.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/USERNAME/dev/PROJECT-NAME/node_modules/fsevents',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
gyp info ok
verbose 111.003540588 info sharp Using cached /Users/USERNAME/.npm/_libvips/libvips-8.10.5-darwin-x64.tar.br
Done in 111.74s.
```  

</details>

<details>
  <summary>CI (docker/debian/node) - Does not build sharp</summary>
  
```
...
[5/5] Building fresh packages...
verbose 42.566726696 
verbose 42.74831815 Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
verbose 42.97349147 
verbose 42.97924712 
verbose 42.984474691 Font Awesome Free 0.2.34 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
verbose 43.21962385 Font Awesome Free 1.2.34 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
verbose 43.264945172 Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
verbose 43.304574139 Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
verbose 43.326543324 Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
verbose 44.764009003 info sharp Using cached /root/.npm/_libvips/libvips-8.10.5-linux-x64.tar.br
Done in 44.93s.
```
</details>

The difference is the node-gyp build for fsevents is not running...but fsevents is optional (mac only) dependency and the linux CI machine excludes it.

Both mac and linux say:
`... sharp Using cached /path/to/npm/cachedir/.npm/_libvips/libvips-8.10.5-ARCH.tar.br`

Weird thing is that other than that node-gyp output for fsevents on mac, I did not see any other script/build output with yarn install running in verbose mode.  In the complete mac log there is no reference to `/sharp/build/` (ie if a pre-built binary was copied).  Yet the binary and directory are there are the end of the yarn install.

Nothing else notable in yarn verbose log.  No obvious errors.  Just difference in resulting files in the `node_modules` directory.

# Anecdote that might be relevant

By default we use alpine images in the CI because they are usually lighter weight than debian for basic tasks.
When we first deployed we got an architecture mis-match error from sharp (MUSL vs glibc).
We switched the docker image from `node:12.21.0-alpine3.12` to `node:12.21.0-buster-slim` (debian) and of course the architecture mismatch went away.  However now we have the problem that either the build scripts for sharp aren't running or they are silently failing (we don't see anything in the yarn install verboselog) or yarn is overwriting script output due to missing newlines.
Just an idea.

# File Tree differences under `node_modules/sharp/` between mac and linux/CI

To make it easier (I hope) to see I justdiffed the two file lists (mac and linux) for `node_modules/sharp` and screenshotted the few differences.  

![image](https://user-images.githubusercontent.com/1196252/109287826-5f6bfb00-7824-11eb-9a32-b90c71b674e9.png)

![image](https://user-images.githubusercontent.com/1196252/109287885-76125200-7824-11eb-91b0-0c0835d58bc8.png)

![image](https://user-images.githubusercontent.com/1196252/109287932-85919b00-7824-11eb-88be-c7d40010f459.png)

![image](https://user-images.githubusercontent.com/1196252/109287979-93dfb700-7824-11eb-8135-c3a28afca2d5.png)

![image](https://user-images.githubusercontent.com/1196252/109288042-a528c380-7824-11eb-8b05-c28a6899e26f.png)

![image](https://user-images.githubusercontent.com/1196252/109288116-bc67b100-7824-11eb-9867-2eecc5b0b150.png)

![image](https://user-images.githubusercontent.com/1196252/109288164-cf7a8100-7824-11eb-8b4c-d39097be300e.png)

**Comment by mattpr** [comment]
I decided to also just test with `npm ci` instead of `yarn install --frozen-lockfile` to see if that makes a difference.

# Changes

Create a package-lock.json for the repo:
```
npm install --package-lock-only
```

Update CI script to use npm instead of yarn...

yarn (before)
```
    - YARN_CACHE_FOLDER=$NPM_CACHE_DIR
    - npx envinfo --binaries --system
    - mkdir -p "$ARTIFACT_PATH"
    - rm -rf node_modules
    - yarn install --frozen-lockfile --production=true --verbose > $ARTIFACT_PATH/yarn.log
    - tar -cvzf "$ARTIFACT_PATH/$ARTIFACT_NAME" --exclude .git --exclude "$NPM_CACHE_DIR" --exclude "$ARTIFACT_PATH" .   >> $ARTIFACT_PATH/yarn.log
```

npm ci
```
    - npm config set cache $NPM_CACHE_DIR
    - npm config set ignore-scripts false # make sure to run scripts
    - npx envinfo --binaries --system
    - mkdir -p "$ARTIFACT_PATH"
    - rm -rf node_modules # make sure we don't have node_modules for some reason
    - npm ci --cache $NPM_CACHE_DIR --prefer-offline --no-audit --only=prod --ignore-scripts=false --verbose > $ARTIFACT_PATH/npm.log
    - tar -cvzf "$ARTIFACT_PATH/$ARTIFACT_NAME" --exclude .git --exclude "$NPM_CACHE_DIR" --exclude "$ARTIFACT_PATH" .   > $ARTIFACT_PATH/tar.log
```

Unfortunately the build/binary is still not there.

In the npm log I do see the following...

```
> sharp@0.27.1 install /builds/USERNAME/PROJECT-NAME/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
```

For some reason a lot of npm's output did not get redirected, perhaps writing to stderr instead of stdout?

Looking in the CI output (stuff that didn't get redirected) I see the following...

```
npm info lifecycle sharp@0.27.1~install: sharp@0.27.1
info sharp Using cached /builds/USERNAME/PROJECT-NAME/.npm/_cacache/_libvips/libvips-8.10.5-linux-x64.tar.br
prebuild-install info begin Prebuild-install version 6.0.1
prebuild-install info looking for cached prebuild @ /builds/USERNAME/PROJECT-NAME/.npm/_cacache/_prebuilds/f832bb-sharp-v0.27.1-napi-v3-linux-x64.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /builds/USERNAME/PROJECT-NAME/.npm/_cacache/_prebuilds/f832bb-sharp-v0.27.1-napi-v3-linux-x64.tar.gz
prebuild-install info unpack resolved to /builds/USERNAME/PROJECT-NAME/node_modules/sharp/build/Release/sharp.node
prebuild-install info install Successfully installed prebuilt binary!
npm verb lifecycle sharp@0.27.1~install: unsafe-perm in lifecycle false
npm verb lifecycle sharp@0.27.1~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/builds/USERNAME/PROJECT-NAME/node_modules/sharp/node_modules/.bin:/builds/USERNAME/PROJECT-NAME/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle sharp@0.27.1~install: CWD: /builds/USERNAME/PROJECT-NAME/node_modules/sharp
npm info lifecycle sharp@0.27.1~postinstall: sharp@0.27.1
```

Perhaps this really is as simple as needing to set unsafe perm since the CI image is running as root?

```
npm verb lifecycle sharp@0.27.1~install: unsafe-perm in lifecycle false
```

Trying again with the following (added `--unsafe-perm`)
```
npm ci --cache $NPM_CACHE_DIR --prefer-offline --no-audit --only=prod --ignore-scripts=false --verbose --unsafe-perm > $ARTIFACT_PATH/npm.log 2>&1
```

```
npm info lifecycle sharp@0.27.1~install: sharp@0.27.1

> sharp@0.27.1 install /builds/USERNAME/PROJECT-NAME/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /builds/USERNAME/PROJECT-NAME/.npm/_cacache/_libvips/libvips-8.10.5-linux-x64.tar.br
prebuild-install info begin Prebuild-install version 6.0.1
prebuild-install info looking for cached prebuild @ /builds/USERNAME/PROJECT-NAME/.npm/_cacache/_prebuilds/f832bb-sharp-v0.27.1-napi-v3-linux-x64.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /builds/USERNAME/PROJECT-NAME/.npm/_cacache/_prebuilds/f832bb-sharp-v0.27.1-napi-v3-linux-x64.tar.gz
prebuild-install info unpack resolved to /builds/USERNAME/PROJECT-NAME/node_modules/sharp/build/Release/sharp.node
prebuild-install info install Successfully installed prebuilt binary!
npm verb lifecycle sharp@0.27.1~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.27.1~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/builds/USERNAME/PROJECT-NAME/node_modules/sharp/node_modules/.bin:/builds/USERNAME/PROJECT-NAME/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle sharp@0.27.1~install: CWD: /builds/USERNAME/PROJECT-NAME/node_modules/sharp
npm info lifecycle sharp@0.27.1~postinstall: sharp@0.27.1
```

These two lines...
```
prebuild-install info unpack resolved to /builds/USERNAME/PROJECT-NAME/node_modules/sharp/build/Release/sharp.node
prebuild-install info install Successfully installed prebuilt binary!
```
...imply that we are using prebuilt instead of building from source and that it will be installed to the correct path.
It says it is successfully installed.
However according to `tar` which later bundles up the entire working directory... no `node_modules/sharp/build` or `sharp.node` binary exist at the path stated.
You see the CI script above...there isn't anything interesting happening between the `yarn install` or `npm ci` and the `tar...` commands that should cause this file/folder to disappear.

So it seems this is not npm or yarn issue but rather some hidden failure specific to sharp and this particular docker image/environment (permissions issue, etc).

The other issue is that yarn's verbose output, while MUCH more noisy (27Mb) than npm's (364kb) is apparently useless because I had to switch to npm to get this script output detail.  Perhaps the yarn newline bug mentioned earlier?

**Comment by lovell** [comment]
Hello, thanks for all the detail. The first thing that doesn't look quite right is this line:

> prebuild-install info looking for cached prebuild @ /builds/USERNAME/PROJECT-NAME/.npm/_cacache/_prebuilds/f832bb-sharp-v0.27.1-napi-v3-linux-x64.tar.gz

I would expect the path to be something like `/builds/USERNAME/PROJECT-NAME/.npm/_prebuilds/...` without the `_cacache` part (`_cacache` is an opaque directory _within_ an npm cache and *not* the cache itself).

If `$NPM_CACHE_DIR` needs to be defined, to avoid the possibility of nested caches, then please can you try something like the following change:

```diff
- NPM_CACHE_DIR="/builds/USERNAME/PROJECT-NAME/.npm/_cacache"
+ NPM_CACHE_DIR="/builds/USERNAME/PROJECT-NAME/.npm"
```

**Comment by gita-v** [comment]
I am also having the same issue

**Comment by lovell** [comment]
@gita-v Please open a new installation issue and answer all of the questions - https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md

**Comment by lovell** [comment]
@mattpr Were you able to make any progress with this by changing the value of `$NPM_CACHE_DIR`?

**Comment by mattpr** [comment]
Hey, sorry it has been on my list to test this further and try to repro for you but have gotten buried under other tasks.

What I can say is that I was setting the cache dir (never changed) to the following:

`NPM_CACHE_DIR: ".npm"`

...and that was working correctly.  So I don't think that is the particular issue here.

I stopped using `npm ci` and started using `npm install` and for some reason that made a difference.  So perhaps an issue with the package-lock.json or something.  Very strange though.

I didn't solve the issue and instead worked around it.

I don't have time at the moment to open this can of worms back up, so I'll close this and if I get around to looking at this again I can re-open it with more details when it is fresh in my head again.

Thanks!
