### ISSUE TITLE
Converting to AVIF takes 100% of all cores, and 2.5GB+ RAM

### ISSUE THREAD

**Issue by jcontonio** [lovell/sharp#2597]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

Yes - 0.27.2

What are the steps to reproduce?

Converting a 4000px wide jpg to avif causes cpu to spike to 400% and takes 2.5gb of RAM vs a webp conversion taking 20% CPU and 200mb of RAM.

* It appears file size doesn't matter, only resolution. Tried with a 6MB jpg, and a 700k jpg as source, both 4000px wide
* This is happening on macOS and Debian

What is the expected behaviour?

Conversion to take up less RAM and CPU

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

```javascript
const avifOptions = {
  quality: 50,
  lossless: false,
  speed: 8, // default is 5
  chromaSubsampling: '4:2:0',
}

// AVif original
// -------------------------------------------------------------------------
await sharp(path.join(inputDirectory, file))
  .toFormat('avif')
  .avif(avifOptions)
  .toFile(path.join(outputDirectory, `test.avif`))

// Avif half
// -------------------------------------------------------------------------
await sharp(path.join(inputDirectory, file))
  .resize({ width: halfWidth })
  .toFormat('avif')
  .avif(avifOptions)
  .toFile(path.join(outputDirectory, `test@0.5x.webp`))
```

Are you able to provide a sample image that helps explain the problem?

![DSC_1147-4000_s](https://user-images.githubusercontent.com/2809/109366574-9f44d980-7848-11eb-82f5-fffa19163db1.jpg)

What is the output of running `npx envinfo --binaries --system`?

macOS:
```
  System:
    OS: macOS 11.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 1.70 GB / 40.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
```

Debian:
```
  System:
    OS: Linux 5.4 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 270.71 MB / 1.94 GB
    Container: Yes
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
```

**Comment by lovell** [comment]
Yes, this is expected as AVIF compression is relatively slow and memory hungry compared with most other formats.

Using the following code sample and your test image:
```js
await sharp("109366574-9f44d980-7848-11eb-82f5-fffa19163db1.jpg")
  .avif({ speed: 8 })
  .toFile("out.avif")
```

...when run locally on Linux (x64 CPU with AVX2) via callgrind using locally compiled and installed libaom, libheif and libvips with symbols intact, I see the top 10 "hottest" functions are:

```
74,895,067,224  PROGRAM TOTALS

9,771,380,136  /build/glibc-ZN95T4/glibc-2.31/string/../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:__memset_avx2_unaligned_erms [/usr/lib/x86_64-linux-gnu/libc-2.31.so]
9,227,999,443  ???:av1_optimize_txb [/usr/local/lib/libaom.so.2.0.0]
4,863,071,423  ???:prune_intra_mode_with_hog [/usr/local/lib/libaom.so.2.0.0]
4,185,373,503  ???:search_tx_type [/usr/local/lib/libaom.so.2.0.0]
3,096,177,196  ???:av1_dr_prediction_z2_avx2 [/usr/local/lib/libaom.so.2.0.0]
1,993,966,420  ???:av1_predict_intra_block [/usr/local/lib/libaom.so.2.0.0]
1,940,325,014  ???:build_intra_predictors [/usr/local/lib/libaom.so.2.0.0]
1,257,895,707  ???:block_rd_txfm [/usr/local/lib/libaom.so.2.0.0]
1,026,892,929  ???:av1_cost_coeffs_txb [/usr/local/lib/libaom.so.2.0.0]
  866,556,342  ???:lowbd_inv_txfm2d_add_no_identity_avx2 [/usr/local/lib/libaom.so.2.0.0]
```

These are all from within libaom or invoked by it.

By setting `speed` to 8, you're telling libaom to favour performance over all else. It's possible you might find that slowing it down also reduces memory consumption for some tasks.

The prebuilt binaries provided by sharp use libaom as it is the reference de/encoder with good cross-platform support. There is a plan to replace it with the slightly faster dav1d (decode) and rav1e (encode) combination, but I'm unsure of their relative memory consumption.

**Comment by jcontonio** [comment]
It seems any speed setting drives my CPU up to 400% and RAM to 2+GB. I think we'll probably ditch AVIF support in our app until that space matures a little more. Thanks for the detailed reply!

**Comment by lovell** [comment]
No worries, please subscribe to #2604 for updates about the migration to dav1d+rav1e.

**Comment by tom10271** [comment]
Sharing some of the results we tested with different parameters for converting images to AVIF then store in S3 by Lambda function. We ran 10 times and secSpent is the average seconds spent. Just in case people that do not know, more memory Lambda have, more CPU credits we can spend in the lambda function

```
Lambda RAM settings: 1024MB
{
  queryParameters: { noCache: 1, format: 'avif', effort: 0 },
  secSpent: 1.1503999999999999,
  sizeKB: 32.4169921875
}
{
  queryParameters: { noCache: 1, format: 'avif', effort: 1 },
  secSpent: 1.2476,
  sizeKB: 20.07421875
}
{
  queryParameters: { noCache: 1, format: 'avif', effort: 2 },
  secSpent: 5.9789,
  sizeKB: 14.7392578125
}

Lambda RAM settings: 2048MB
{
  queryParameters: { noCache: 1, format: 'avif', effort: 0 },
  secSpent: 1.0310000000000001,
  sizeKB: 32.4169921875
}
{
  queryParameters: { noCache: 1, format: 'avif', effort: 1 },
  secSpent: 1.0988,
  sizeKB: 20.07421875
}
{
  queryParameters: { noCache: 1, format: 'avif', effort: 2 },
  secSpent: 3.5351,
  sizeKB: 14.7392578125
}


Lambda RAM settings: 4096MB
{
  queryParameters: { noCache: 1, format: 'avif', effort: 0 },
  secSpent: 1.0706,
  sizeKB: 32.4169921875
}
{
  queryParameters: { noCache: 1, format: 'avif', effort: 1 },
  secSpent: 0.9771000000000001,
  sizeKB: 20.07421875
}
{
  queryParameters: { noCache: 1, format: 'avif', effort: 2 },
  secSpent: 3.2674,
  sizeKB: 14.7392578125
}


Lambda RAM settings: 10240MB
{
  queryParameters: { noCache: 1, format: 'avif', effort: 0 },
  secSpent: 1.0502,
  sizeKB: 32.4169921875
}
{
  queryParameters: { noCache: 1, format: 'avif', effort: 1 },
  secSpent: 1.0059,
  sizeKB: 20.07421875
}
{
  queryParameters: { noCache: 1, format: 'avif', effort: 2 },
  secSpent: 3.3095,
  sizeKB: 14.7392578125
}
```

**Comment by alexmacarthur** [comment]
It doesn't seem like the resource demands for the AVIF conversion process have lessened much, but if anyone has any ideas on how I can improve performance, I'd love to hear them. 

VM details:
<img width="625" alt="image" src="https://github.com/lovell/sharp/assets/8398220/22d9950f-8962-45fc-8e77-3b4f1ba63dad">
