### ISSUE TITLE
Permission Denied when install sharp

### ISSUE THREAD

**Issue by flyrk** [lovell/sharp#2599]
Hi!
When I run 'npm install sharp' on linux, it occured an error which is: 
```
File "/usr/lib64/python2.7/shutil.py", line 247, in rmtree
rmtree(fullname, ignore_errors, onerror)
File "/usr/lib64/python2.7/shutil.py", line 252, in rmtree
onerror(os.remove, fullname, sys.exc_info())
File "/usr/lib64/python2.7/shutil.py", line 250, in rmtree
os.remove(fullname)
OSError: [Errno 13] Permission denied: '/workspace/sharp-demo/node_modules/sharp/vendor/8.10.5/lib/libvips-cpp.so.42
```

And when I check the authorization of `libvips.so.42 & libvips.cpp.so.42`, it shows `-rw-r--r--`, so I can't install sharp which leads to build error.

Because I can't change the authorization of my machine which is not local enviorment, I Hope u can change the authorization of `libvips.so.42` & `libvips.cpp.so.42` into write.

Thanks!

**Comment by lovell** [comment]
The following questions in the installation issue template were ignored/deleted. Please can you answer them.

--


Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7, does the user running `npm install` own the directory it is run in?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

What is the output of running `npx envinfo --binaries --system`?

**Comment by flyrk** [comment]
Did you see the documentation relating to installation?
--- Yes, I'd seen.

Have you ensured the architecture and platform of Node.js used for npm install is the same as the architecture and platform of Node.js used at runtime?
--- Yes, I'm sure.

Are you using the latest version? Is the version currently in use as reported by npm ls sharp the same as the latest version as reported by npm view sharp dist-tags.latest?
--- Yes, my sharp version is 0.27.2

What is the complete output of running npm install --verbose sharp? Have you checked this output for useful error messages?
--- After run this, the output error messages are:
```
npm ERR! Error: EACCES: permission denied, rmdir '/myProject/node_modules/.sharp.DELETE/vendor/8.10.5/lib/glib-2.0'
```

What is the output of running npx envinfo --binaries --system?
--- the output is:
```
System:
    OS: Linux 3.10 Tencent tlinux 2.2 (Final)
    CPU: (48) x64 Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz
    Memory: 4.54 GB / 125.34 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 8.16.0 - /home/unibuild/node-v8.16.0/bin/node
    Yarn: 1.22.4 - /home/unibuild/yarn-v1.22.4/bin/yarn
    npm: 6.4.1 - /home/unibuild/node-v8.16.0/bin/npm
```

Hope this can help, thanks.

**Comment by lovell** [comment]
If you are using npm v6 or earlier and installing as a root or sudo user, have you tried with the `npm install --unsafe-perm` flag?

What is the complete output of running `npm install --verbose sharp`?

**Comment by flyrk** [comment]
> If you are using npm v6 or earlier and installing as a root or sudo user, have you tried with the `npm install --unsafe-perm` flag?
> I have tried this and it couldn't help.

> What is the complete output of running `npm install --verbose sharp`?
> The error message is:
```
npm verb stack Error: EACCES: permission denied, rmdir '/workspace/myProject/node_modules/.sharp.DELETE/vendor/8.10.5/lib/glib-2.0'
npm verb cwd /workspace/myProject
npm verb Linux 3.10.107-1-tlinux2_kvm_guest_nosign_args2-0052
npm verb argv "/data/ub/unibuild/node-v8.16.0/bin/node" "/home/unibuild/node-v8.16.0/bin/npm" "install" "--unsafe-perm" "--verbose" "sharp"
npm verb node v8.16.0
npm verb npm  v6.4.1
npm ERR! path /workspace/myProject/node_modules/.sharp.DELETE/vendor/8.10.5/lib/glib-2.0
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall rmdir
npm ERR! Error: EACCES: permission denied, rmdir '/workspace/myProject/node_modules/.sharp.DELETE/vendor/8.10.5/lib/glib-2.0'
npm ERR!  { Error: EACCES: permission denied, rmdir '/workspace/myProject/node_modules/.sharp.DELETE/vendor/8.10.5/lib/glib-2.0'
```

**Comment by lovell** [comment]
Please can you provide the **complete output** of running `npm install --verbose sharp`?

**Comment by flyrk** [comment]
> Please can you provide the **complete output** of running `npm install --verbose sharp`?

```
npm verb stack Error: EACCES: permission denied, rmdir '/data/ub/unibuild/workspace/myProject/node_modu
les/.sharp.DELETE/vendor/8.10.5/lib/glib-2.0'
npm verb cwd /data/ub/unibuild/workspace/myProject
npm verb Linux 3.10.107-1-tlinux2_kvm_guest_nosign_args2-0052
npm verb argv "/data/ub/unibuild/node-v8.16.0/bin/node" "/home/unibuild/node-v8.16.0/bin/n
pm" "install" "--unsafe-perm" "--verbose" "sharp"
npm verb node v8.16.0
npm verb npm  v6.4.1
npm ERR! path /data/ub/unibuild/workspace/myProject/node_modules/.sharp.DELETE/vendor/8.10.5/lib/glib-2
.0
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall rmdir
npm ERR! Error: EACCES: permission denied, rmdir '/data/ub/unibuild/workspace/myProject/node_modules/.s
harp.DELETE/vendor/8.10.5/lib/glib-2.0'
npm ERR!  { Error: EACCES: permission denied, rmdir '/data/ub/unibuild/workspace/myProject/node_modules
/.sharp.DELETE/vendor/8.10.5/lib/glib-2.0'
npm ERR!   cause: 
npm ERR!    { Error: EACCES: permission denied, rmdir '/data/ub/unibuild/workspace/myProject/node_modul
es/.sharp.DELETE/vendor/8.10.5/lib/glib-2.0'
npm ERR!      errno: -13,
npm ERR!      code: 'EACCES',
npm ERR!      syscall: 'rmdir',
npm ERR!      path: '/data/ub/unibuild/workspace/myProject/node_modules/.sharp.DELETE/vendor/8.10.5/lib
/glib-2.0' },
npm ERR!   stack: 'Error: EACCES: permission denied, rmdir \'/data/ub/unibuild/workspace/myProject/node
_modules/.sharp.DELETE/vendor/8.10.5/lib/glib-2.0\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rmdir',
npm ERR!   path: '/data/ub/unibuild/workspace/myProject/node_modules/.sharp.DELETE/vendor/8.10.5/lib/gl
ib-2.0' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current u
ser
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
npm verb exit [ -13, true ]
npm timing audit submit Completed in 754ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 754ms
npm timing audit body Completed in 0ms
npm timing npm Completed in 6645ms
```

**Comment by flyrk** [comment]
And the authorization of files is :
```
drwxr-xr-x 3 unibuild123 users         4096 Mar    1 11:03  glib-2.0
-rw-r--r--  1 unibuild123 users     240336 Dec  20 17:32 libvips-cpp.so.42
-rw-r--r--  1 unibuild123 users 26491568 Dec  20 17:32 libvips.so.42
```

**Comment by lovell** [comment]
This looks like https://stackoverflow.com/questions/35528425/enotempty-directory-not-empty-rename-javascript-npm-ubuntu-serve/54624637#54624637

Please can you try running `rm -rf node_modules/.sharp.DELETE` then reinstall sharp.

**Comment by flyrk** [comment]
I didn't find the file `node_modules/.sharp.DELETE`. And when I tried to delete `node_module`, it also showed permission error:
```
rm: cannot remove ‘sharp/vendor/8.10.5/include/libxml2/libxml/HTMLtree.h’: Permission denied
rm: cannot remove ‘sharp/vendor/8.10.5/include/libxml2/libxml/uri.h’: Permission denied
rm: cannot remove ‘sharp/vendor/8.10.5/include/libxml2/libxml/SAX2.h’: Permission denied
rm: cannot remove ‘sharp/vendor/8.10.5/include/libxml2/libxml/pattern.h’: Permission denied
rm: cannot remove ‘sharp/vendor/8.10.5/include/libheif/heif_cxx.h’: Permission denied
rm: cannot remove ‘sharp/vendor/8.10.5/include/libheif/heif_plugin.h’: Permission denied
rm: cannot remove ‘sharp/vendor/8.10.5/include/libheif/heif.h’: Permission denied
rm: cannot remove ‘sharp/vendor/8.10.5/include/libheif/heif_version.h’: Permission denied
rm: cannot remove ‘sharp/vendor/8.10.5/include/jmorecfg.h’: Permission denied
```

**Comment by flyrk** [comment]
I sincerely hope that the authorization of libvips.so.42 & libvips.cpp.so.42 can be changed so normal user can remove it. Right now I can't install sharp on remote machine. 
thanks!

**Comment by lovell** [comment]
My best guess is that `npm install` was originally run as `root` or using `sudo`. This means you'll need to do the same to remove those files, e.g. run `sudo rm -f node_modules`.

This is a filesystem and/or npm permissions thing rather than anything to do with sharp.

**Comment by flyrk** [comment]
Alright, I will figure out.
