### ISSUE TITLE
Improve flatten docs

### ISSUE THREAD

**Issue by NGPixel** [lovell/sharp#2601]
I'm using sharp (0.27.2) to resize images on the fly in a Node.js express application. However, I'm unable to keep the image transparency. The result always get an opaque white background.

The source is a read stream from AWS S3, which is piped into a sharp instance, which is then piped to the Express response. I tried setting the background to alpha 0 in both the `resize()` and `flatten()` operation, without success.

I created this sample code to recreate the problem with a simple read / write file stream:

```js
const fs = require('fs')
const sharp = require('sharp')

async function main () {
  const transformer = sharp()

  transformer.resize({
    width: 64,
    height: 64,
    background: { r: 255, g: 255, b: 255, alpha: 0 }
  }).flatten({
    background: { r: 255, g: 255, b: 255, alpha: 0 }
  })

  const originStream = fs.createReadStream('./test.png')
  const targetStream = fs.createWriteStream('./result.png')

  transformer.toFormat('png')

  originStream.pipe(transformer).pipe(targetStream)
}

main()
```

How can I make the output image keep its transparent background?

Thanks!

**Comment by lovell** [comment]
Hello, `flatten` will *always* remove the alpha channel.

https://sharp.pixelplumbing.com/api-operation#flatten

The docs could probably be a bit clearer, and perhaps `flatten` should throw an error if the `background` provided to it has an alpha value < 1.

**Comment by NGPixel** [comment]
@lovell I should have mentioned that I added flatten afterwards because I was having the issue with just resize as well.

Removing the flatten operation still results in a white background unfortunately.

**Comment by lovell** [comment]
Commit https://github.com/lovell/sharp/commit/f1f18fbb4af818df7a1c0b53f2cfe9eacdba0049 adds a note to the docs about this.
