### ISSUE TITLE
Unable to tile

### ISSUE THREAD

**Issue by 1Map** [lovell/sharp#2603]
I get the following error when trying to create a deep zoom tile(s):

`rename: unable to rename file "/myfolder/output-C948Y0/output_files" as "/myfolder/output_files", Directory not empty`

Seems that tile creates a temp folder output-C948Y0/output_files that cannot be renamed / moved back to /output_files because /output_files is not empty.

I use:

```
sharp(srcImage)
    .tile({
      size: 256
    })
    .toFile("/myfolder/output.dz", function(err, info) {
      // output.dzi is the Deep Zoom XML definition
      // output_files contains 256x256 tiles grouped by zoom level
    });
```

**Comment by lovell** [comment]
Hi, you'll need to remove any existing output, in this example `/myfolder/output_files`, before creating tile-based output into the same location.

See also https://github.com/libvips/libvips/issues/312

**Comment by 1Map** [comment]
This is strange as the folder is empty (newly created folder) and error is given inside sharp

**Comment by lovell** [comment]
This behaviour is by design in libvips - see https://github.com/libvips/libvips/issues/312#issuecomment-154346182 - the summary is that libvips should be allowed to create the directory.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by LMW-lmw** [comment]
Hello, I also encountered the same error, could you find a solution
