### ISSUE TITLE
npm install seem to work but on develop problem with sharp

### ISSUE THREAD

**Issue by NitsanCohen770** [lovell/sharp#2606]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?
yes
Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?
yes
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
yes
If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?
yes
If you are using npm v7, does the user running `npm install` own the directory it is run in?
yes
If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?
yes
What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?
no error as it seems
nitsancohen@LAPTOP-20FTURRE:/mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-starter-portfolio-cara$ --verbose sharp
--verbose: command not found
nitsancohen@LAPTOP-20FTURRE:/mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-starter-portfolio-cara$ npm install --verbose sharp
npm verb cli [
npm verb cli   '/usr/local/lib/node_modules/node/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@7.6.0
npm info using node@v15.10.0
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-starter-portfolio-cara/.npmrc Completed in 1ms 
npm timing config:load:project Completed in 2ms
npm timing config:load:file:/home/nitsancohen/.npmrc Completed in 0ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:cafile Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:setUserAgent Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 8ms
npm verb npm-session 7c5abb951e4a03fd
npm timing npm:load Completed in 23ms
npm timing arborist:ctor Completed in 1ms
npm timing idealTree:init Completed in 551ms
npm timing idealTree:userRequests Completed in 2ms
npm http fetch GET 304 https://registry.npmjs.org/sharp 2796ms (from cache)
npm timing idealTree:#root Completed in 2801ms
npm timing idealTree:buildDeps Completed in 2802ms
npm timing idealTree:fixDepFlags Completed in 23ms
npm timing idealTree Completed in 3396ms
npm timing reify:loadTrees Completed in 3420ms
npm timing reify:diffTrees Completed in 240ms
npm timing reify:retireShallow Completed in 97ms
npm timing reify:createSparse Completed in 16ms
npm timing reify:loadBundles Completed in 0ms
npm http fetch GET 304 https://registry.npmjs.org/rimraf 282ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/rimraf/-/rimraf-3.0.2.tgz 14ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/rimraf/-/rimraf-3.0.2.tgz 22ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/which 324ms (from 
cache)
npm http fetch GET 200 https://registry.npmjs.org/which/-/which-1.3.1.tgz 44ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/which/-/which-2.0.2.tgz 46ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/which/-/which-2.0.2.tgz 44ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/which/-/which-2.0.2.tgz 47ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/which/-/which-2.0.2.tgz 41ms (from cache)
npm timing reifyNode:node_modules/gatsby/node_modules/rimraf Completed in 424ms
npm timing reifyNode:node_modules/gatsby-core-utils/node_modules/rimraf Completed in 425ms
npm http fetch GET 304 https://registry.npmjs.org/semver 413ms (from cache)
npm timing reifyNode:node_modules/gatsby/node_modules/which Completed in 483ms
npm timing reifyNode:node_modules/which Completed in 488ms
npm timing reifyNode:node_modules/gatsby-recipes/node_modules/which 
Completed in 487ms
npm timing reifyNode:node_modules/cross-env/node_modules/which Completed in 488ms
npm http fetch GET 200 https://registry.npmjs.org/semver/-/semver-5.7.1.tgz 45ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/semver/-/semver-5.7.1.tgz 45ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/semver/-/semver-5.7.1.tgz 46ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/semver/-/semver-5.7.1.tgz 46ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/semver/-/semver-5.7.1.tgz 47ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/semver/-/semver-5.7.1.tgz 48ms (from cache)
npm timing reifyNode:node_modules/gatsby-cli/node_modules/which Completed in 509ms
npm timing reifyNode:node_modules/remark-mdxjs/node_modules/semver Completed in 590ms
npm timing reifyNode:node_modules/@babel/plugin-syntax-object-rest-spread/node_modules/semver Completed in 591ms
npm timing reifyNode:node_modules/@babel/plugin-syntax-jsx/node_modules/semver Completed in 591ms
npm timing reifyNode:node_modules/webpack/node_modules/semver Completed in 591ms
npm timing reifyNode:node_modules/remark-mdx/node_modules/semver Completed in 601ms
npm timing reifyNode:node_modules/@mdx-js/mdx/node_modules/semver Completed in 601ms
npm timing reify:unpack Completed in 601ms
npm timing reify:unretire Completed in 1ms
npm timing build:queue Completed in 8ms
npm timing build:link:node_modules/which Completed in 56ms
npm timing build:link:node_modules/@babel/plugin-syntax-object-rest-spread/node_modules/semver Completed in 58ms
npm timing build:link:node_modules/@babel/plugin-syntax-jsx/node_modules/semver Completed in 58ms
npm timing build:link:node_modules/@mdx-js/mdx/node_modules/semver Completed in 58ms
npm timing build:link:node_modules/cross-env/node_modules/which Completed in 59ms
npm timing build:link:node_modules/gatsby/node_modules/rimraf Completed in 58ms
npm timing build:link:node_modules/gatsby-core-utils/node_modules/rimraf Completed in 59ms
npm timing build:link:node_modules/gatsby/node_modules/which Completed in 58ms
npm timing build:link:node_modules/remark-mdx/node_modules/semver Completed in 59ms
npm timing build:link:node_modules/gatsby-cli/node_modules/which Completed in 60ms
npm timing build:link:node_modules/gatsby-recipes/node_modules/which Completed in 60ms
npm timing build:link:node_modules/remark-mdxjs/node_modules/semver 
Completed in 59ms
npm timing build:link:node_modules/webpack/node_modules/semver Completed in 60ms
npm timing build:link Completed in 62ms
npm timing build:deps Completed in 70ms
npm timing build Completed in 71ms
npm timing reify:build Completed in 71ms
npm timing reify:trash Completed in 134ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 1050ms
npm timing auditReport:getReport Completed in 1053ms
npm timing auditReport:init Completed in 0ms
npm timing reify:audit Completed in 1054ms
npm timing reify:save Completed in 245ms
npm timing reify Completed in 4893ms

changed 13 packages, and audited 2140 packages in 5s

218 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm timing command:install Completed in 4908ms
npm verb exit 0
npm timing npm Completed in 5045ms
npm info ok 
What is the output of running `npx envinfo --binaries --system`?
nitsancohen@LAPTOP-20FTURRE:/mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-starter-portfolio-cara$ npx envinfo --binaries 
--system

  System:
    OS: Linux 4.19 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 9.39 GB / 12.39 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 15.10.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /mnt/c/Users/nitsa/node_modules/.bin/yarn       
    npm: 7.6.0 - /usr/local/bin/npm

what I go to develop mode on gatsby it throws an error also when using yarn install it throws an error

**on gatsby develop:**

nitsancohen@LAPTOP-20FTURRE:/mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-starter-portfolio-cara$ gatsby develop
success open and validate gatsby-configs - 0.392s

 ERROR 

Error in "/mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-starter-portfolio-cara/node_modules/gatsby-plugin-manifest/gatsby-node.js":
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'
Require stack:
- /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-starter-portfolio-cara/node_modules/sharp/lib/constructor.js
- /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-starter-portfolio-cara/node_modules/sharp/lib/index.js
- /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-starter-portfolio-cara/node_modules/gatsby-plugin-manifest/safe-sharp.js 
- /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-starter-portfolio-cara/node_modules/gatsby-plugin-manifest/gatsby-node.js- /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-starter-portfolio-cara/node_modules/gatsby/dist/bootstrap/resolve-module-exports.js
- /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-starter-portfolio-cara/node_modules/gatsby/dist/bootstrap/load-plugins/validate.js
- /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-starter-portfolio-cara/node_modules/gatsby/dist/bootstrap/load-plugins/load.js
- /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-starter-portfolio-cara/node_modules/gatsby/dist/bootstrap/load-plugins/index.js
- /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-starter-portfolio-cara/node_modules/gatsby/dist/services/initialize.js   
- /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-starter-portfolio-cara/node_modules/gatsby/dist/services/index.js        
- /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-starter-portfolio-cara/node_modules/gatsby/dist/state-machines/develop/services.js
- /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-starter-portfolio-cara/node_modules/gatsby/dist/state-machines/develop/index.js
-
/mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-starter-portfolio-cara/node_modules/gatsby/dist/commands/develop-process.js- /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-starter-portfolio-cara/.cache/tmp-32326-OaQF40KefpkX

- Run "npm rebuild --verbose sharp" and look for errors
- Consult the installation documentation at
https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues   

  Error: Something went wrong installing the "sharp" module
  Cannot find module '../build/Release/sharp.node'
  Require stack:
  - /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-sta  rter-portfolio-cara/node_modules/sharp/lib/constructor.js
  - /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-sta  rter-portfolio-cara/node_modules/sharp/lib/index.js
  - /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-sta  rter-portfolio-cara/node_modules/gatsby-plugin-manifest/safe-sharp  .js
  - /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-sta  rter-portfolio-cara/node_modules/gatsby-plugin-manifest/gatsby-nod  e.js
  - /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-sta  rter-portfolio-cara/node_modules/gatsby/dist/bootstrap/resolve-mod  ule-exports.js
  - /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-sta  rter-portfolio-cara/node_modules/gatsby/dist/bootstrap/load-plugin  s/validate.js
  - /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-sta  rter-portfolio-cara/node_modules/gatsby/dist/bootstrap/load-plugin  s/load.js
  - /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-sta  rter-portfolio-cara/node_modules/gatsby/dist/bootstrap/load-plugin  s/index.js
  - /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-sta  rter-portfolio-cara/node_modules/gatsby/dist/services/initialize.j  s
  - /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-sta  rter-portfolio-cara/node_modules/gatsby/dist/services/index.js    
  - /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-sta  rter-portfolio-cara/node_modules/gatsby/dist/state-machines/develo  p/services.js
  - /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-sta  rter-portfolio-cara/node_modules/gatsby/dist/state-machines/develo  p/index.js
  - /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-sta  rter-portfolio-cara/node_modules/gatsby/dist/commands/develop-proc  ess.js
  - /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-sta  rter-portfolio-cara/.cache/tmp-32326-OaQF40KefpkX
  - Run "npm rebuild --verbose sharp" and look for errors
  - Consult the installation documentation at https://sharp.pixelplu  mbing.com/install
  - Search for this error at https://github.com/lovell/sharp/issues 

  - constructor.js:34 Object.<anonymous>
    [gatsby-starter-portfolio-cara]/[sharp]/lib/constructor.js:34:9 

  - v8-compile-cache.js:192 Module._compile
    [gatsby-starter-portfolio-cara]/[v8-compile-cache]/v8-compile-ca    che.js:192:30

  - loader:1120 Object.Module._extensions..js
    node:internal/modules/cjs/loader:1120:10

  - loader:971 Module.load
    node:internal/modules/cjs/loader:971:32

  - loader:812 Function.Module._load
    node:internal/modules/cjs/loader:812:14

  - loader:995 Module.require
    node:internal/modules/cjs/loader:995:19

  - v8-compile-cache.js:159 require
    [gatsby-starter-portfolio-cara]/[v8-compile-cache]/v8-compile-ca    che.js:159:20

  - index.js:3 Object.<anonymous>
    [gatsby-starter-portfolio-cara]/[sharp]/lib/index.js:3:15       

  - v8-compile-cache.js:192 Module._compile
    [gatsby-starter-portfolio-cara]/[v8-compile-cache]/v8-compile-ca    che.js:192:30

  - loader:1120 Object.Module._extensions..js
    node:internal/modules/cjs/loader:1120:10

  - loader:971 Module.load
    node:internal/modules/cjs/loader:971:32

  - loader:812 Function.Module._load
    node:internal/modules/cjs/loader:812:14

  - loader:995 Module.require
    node:internal/modules/cjs/loader:995:19

  - v8-compile-cache.js:159 require
    [gatsby-starter-portfolio-cara]/[v8-compile-cache]/v8-compile-ca    che.js:159:20

  - safe-sharp.js:132 Object.<anonymous>
    [gatsby-starter-portfolio-cara]/[gatsby-plugin-manifest]/safe-sh    arp.js:132:11

  - v8-compile-cache.js:192 Module._compile
    [gatsby-starter-portfolio-cara]/[v8-compile-cache]/v8-compile-ca    che.js:192:30

not finished load plugins - 18.623s

**and on yarn install:**
error /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-starter-portfolio-cara/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments:
Directory: /mnt/c/Users/nitsa/Documents/TYPESCRIPT/first-project/gatsby-starter-portfolio-cara/node_modules/sharp
Output:
info sharp Downloading https://npm.taobao.org/mirrors/sharp-libvips/v8.10.5/libvips-8.10.5-linux-x64.tar.br
ERR! sharp unable to get local issuer certificate
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
node:internal/modules/cjs/loader:926
  throw err;
  ^

Error: Cannot find module 'nopt'
Require stack:
- /usr/share/nodejs/node-gyp/lib/node-gyp.js
- /usr/share/nodejs/node-gyp/bin/node-gyp.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:923:15)
    at Function.Module._load (node:internal/modules/cjs/loader:768:27)
    at Module.require (node:internal/modules/cjs/loader:995:19)     
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/usr/share/nodejs/node-gyp/lib/node-gyp.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)   
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at Module.load (node:internal/modules/cjs/loader:971:32)        
    at Function.Module._load (node:internal/modules/cjs/loader:812:14)
    at Module.require (node:internal/modules/cjs/loader:995:19) {   
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/nodejs/node-gyp/lib/node-gyp.js',
    '/usr/share/nodejs/node-gyp/bin/node-gyp.js'

**Comment by lovell** [comment]
The salient part of this error is:

> info sharp Downloading https://npm.taobao.org/mirrors/sharp-libvips/v8.10.5/libvips-8.10.5-linux-x64.tar.br
> ERR! sharp unable to get local issuer certificate

Please see #1618

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
