### ISSUE TITLE
Possible upstream installation issue from Joplin

### ISSUE THREAD

**Issue by j-krl** [lovell/sharp#2609]
Hello,

Kind of a unique situation as I am not explicitly installing Sharp, but it is a dependency of the CLI install of a notes app called Joplin. There has been an issue with the install in the last couple weeks where the Joplin install has been tripped up by Sharp. [Here](https://discourse.joplinapp.org/t/unknown-profile-version/14419/26) is the Joplin forum post about it (only the end is really relevant) and below is the error log I am getting on install:
```
/Users/jkrl/.nvm/versions/node/v14.0.0/lib/node_modules/joplin/node_modules/sharp/lib/constructor.js:34
  throw new Error(error);
  ^

Error: 
Something went wrong installing the "sharp" module

dlopen(/Users/jkrl/.nvm/versions/node/v14.0.0/lib/node_modules/joplin/node_modules/sharp/build/Release/sharp.node, 1): Library not loaded: /usr/local/opt/vips/lib/libvips-cpp.42.dylib
  Referenced from: /Users/jkrl/.nvm/versions/node/v14.0.0/lib/node_modules/joplin/node_modules/sharp/build/Release/sharp.node
  Reason: image not found

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (/Users/jkrl/.nvm/versions/node/v14.0.0/lib/node_modules/joplin/node_modules/sharp/lib/constructor.js:34:9)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/jkrl/.nvm/versions/node/v14.0.0/lib/node_modules/joplin/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
```
The project maintainer thought it would be good to post here and see if there was some common fix or to shed some more light on the error and no one seems to know over there.

Thanks!

**Comment by lovell** [comment]
Please can you answer the installation issue template questions.

--

Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7, does the user running `npm install` own the directory it is run in?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

What is the output of running `npx envinfo --binaries --system`?

**Comment by j-krl** [comment]
Since it's a dependency install I haven't taken a very detailed look, but I'll go through and get back to you. Thanks!

**Comment by j-krl** [comment]
https://github.com/lovell/sharp/issues/2029#issuecomment-576036253

Found the issue. Looks like I had installed libvips with brew at some point (I have no memory of this). Ran `brew uninstall lipvips` and then reinstalled sharp and voila!

**Comment by jivinivan** [comment]
I experienced the same issue deploying to a cloud environment. In order to get this working again I had to clear the dependency cache for that environment.
