### ISSUE TITLE
Low JPEG image quality upon resize

### ISSUE THREAD

**Issue by OriginalEXE** [lovell/sharp#261]
Hello,

first of all, thank you very much for your hard work in maintaining this library.

I came across this library through https://github.com/jimmynicol/image-resizer and it works great, except that I get a pretty big decrease in image quality when it's resized (tested with multiple jpeg images).

The library I linked above still uses 10.1 so that might be the issue, so if you think it is let me know and I'll try to update sharp to the latest version.

Note that I am using quality 100 for the resizing.

Images comparison (original is a second image): http://imgur.com/tdwLBST,9C6RbcE#0

As you can see, image resized by even 1px loses it's sharpness quite noticeably.
Is this something that's expected, is it weird, am I expecting something impossible?

Would love your feedback on this, thanks again, appreciated.

**Comment by lovell** [comment]
Hello Ante, thanks for your kinds words.

I did a quick search in the `image-resizer` module for use of the [interpolateWith](http://sharp.dimens.io/en/stable/api/#interpolatewithinterpolator) method but found [no results](https://github.com/jimmynicol/image-resizer/search?utf8=%E2%9C%93&q=interpolateWith) so I suspect it uses the default bilinear interpolation.

Perhaps you could experiment with the other interpolators to see if they provide better results.

**Comment by OriginalEXE** [comment]
Hi,

thank you very much, spot on, other interpolation was the issue, quite an improvement with changing it to bicubic, locallyBoundedBicubic or nohalo.

Thanks again for the quick answer, awesome library :)

**Comment by CodeWithOz** [comment]
@lovell is this still an option for regular `resize` operations? I tried looking in the current docs and it seems interpolators are only available in `affine` operations. I get a reduction in the resolution of my images after resizing them so that's how I stumbled upon this thread.
