### ISSUE TITLE
Image is not rotating as expected

### ISSUE THREAD

**Issue by jl-gogovapps** [lovell/sharp#2610]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

```
sharp@0.27.1
```

What are the steps to reproduce?

```
const sharp = require('sharp')

sharp('rotated2.jpeg')
  .rotate()
  .toFormat('png')
  .png({ quality: 50 })
  .toFile('output.png')
```

What is the expected behaviour?

```
Image is rotated correctly and EXIF data is stripped
```

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

Are you able to provide a sample image that helps explain the problem?

![rotated2](https://user-images.githubusercontent.com/44532602/110392594-2fe49c00-8037-11eb-881b-62f737e0affc.jpeg)

EXIF:

<img width="320" alt="Screen Shot 2021-03-08 at 5 54 54 PM" src="https://user-images.githubusercontent.com/44532602/110392751-6f12ed00-8037-11eb-8983-91e510319a65.png">

What is the output of running `npx envinfo --binaries --system`?

```
Occurs in an AWS Lambda and local machine:
npx: installed 1 in 1.188s

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 3.89 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
```

**Comment by lovell** [comment]
Hi, ignoring the EXIF metadata, this image is a 768px high by 576px wide *portrait* image that is already in the correct orientation. The EXIF metadata is such that it will rotate out of orientation.

**Comment by jl-gogovapps** [comment]
@lovell thanks very much for the feedback.  I'm still a little bit confused about the explanation.  

If the image is 768px high by 576px wide, why is it showing on its side?

When I run it through `convert` it seems to rotate correctly:
```
convert rotated2.jpeg -density 100x100 -quality 50 -resize 300 -strip convert.jpeg
```

I also tried this pipeline based on the sizing feedback you mentioned:
```
sharp('rotated2.jpeg')
  .withMetadata()
  .resize({ fit: sharp.fit.inside, width: 300, height: 300 })
  .rotate()
  .png({ quality: 50 })
  .toFile('output.png')
```
But the output was still sideways

Thanks again for helping me further my understanding here!

**Comment by lovell** [comment]
> When I run it through convert it seems to rotate correctly:
> `convert rotated2.jpeg -density 100x100 -quality 50 -resize 300 -strip convert.jpeg`

This command is not rotating the image, but it is removing the EXIF metadata, so if it gives the correct _output_ then the _input_ must already be in the correct orientation and the EXIF metadata is wrong.

**Comment by jl-gogovapps** [comment]
🤦 im sorry i was definitely confused.  

```
convert rotated2.jpeg -density 100x100 -quality 50 -resize 300 -strip -auto-orient convert.jpeg
```

This command renders the same orientation as the sharp library, and you're right.  

Thanks for your help!
