### ISSUE TITLE
class "webpsave_buffer" not found - M1 Mac, Node.js 15.8.0

### ISSUE THREAD

**Issue by DennisKraaijeveld** [lovell/sharp#2614]
This week I started developing on my new Apple Mac Mini M1 and I am using Gatsby and GraphQL to develop a headless Shopify store. I installed vips and its dependancies trough `brew` but when running `yarn develop` I am getting the following error:

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

VipsOperation: class "webpsave_buffer" not found

   1 | fragment GatsbyImageSharpFluid_withWebp_tracedSVG on ImageSharpFluid {
   2 |   tracedSVG
   3 |   aspectRatio
   4 |   src
   5 |   srcSet
>  6 |   srcWebp
     |   ^
   7 |   srcSetWebp
   8 |   sizes
   9 | }
  10 |
  11 | query usersdennisDocumentsProjectenshopifyVivHeadlesssrctemplatesproductPageTsx938671302($handle: String!) {
  12 |   shopifyProduct(handle: {eq: $handle}) {
  13 |     title
  14 |     description
  15 |     tags
  16 |     createdAt

File path: /Users/dennis/Documents/Projecten/shopify-viv-headless/src/templates/product-page.tsx
Url path: /product/viv-home-luxuries-astrantia-zijden-bloem-fuchsia-paars-topkwaliteit-zijde-bloemen/
Plugin: none
HOMEBREW_VERSION: 3.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: ee52b19179d056f3dd2fdf9c52214d3d51dbb9d9
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e5cf1a1a7da039a0e654b70725a1c1fe39626cd9
Core tap last commit: 18 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.30.1 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.2-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
Rosetta 2: false

OS: MacOS 11.2.2

vips: stable 8.10.5 (bottled)
Image processing library
https://github.com/libvips/libvips
/opt/homebrew/Cellar/vips/8.10.5_2 (167 files, 14MB) *
Poured from bottle on 2021-03-08 at 15:43:15
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/vips.rb
License: LGPL-2.1-or-later
==> Dependencies
Build: pkg-config ✔
Required: cfitsio ✔, fftw ✔, fontconfig ✔, gettext ✔, giflib ✔, glib ✔, imagemagick ✔, libexif ✔, libgsf ✔, libheif ✔, libimagequant ✔, libmatio ✔, libpng ✔, librsvg ✔, libspng ✔, libtiff ✔, little-cms2 ✔, mozjpeg ✔, openexr ✔, openslide ✔, orc ✔, pango ✔, poppler ✔, webp ✔
==> Analytics
install: 4,879 (30 days), 15,221 (90 days), 49,699 (365 days)
install-on-request: 4,707 (30 days), 13,792 (90 days), 39,201 (365 days)
build-error: 0 (30 days)

When running which vips the output is: opt/homebrew/bin/vips
But there is also a vips-8.10 in /opt/homebrew/bin

**Comment by DennisKraaijeveld** [comment]
```
> node -p "process.arch"
arm64

> node -p "process.versions"

{
  node: '15.8.0',
  v8: '8.6.395.17-node.23',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '88',
  nghttp2: '1.42.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1i',
  cldr: '38.1',
  icu: '68.2',
  tz: '2020d',
  unicode: '13.0'
}

> npm ls sharp
dennis@ /Users/dennis
└── (empty)
```

Sorry for the crosspost, wasnt sure where to mention it.

**Comment by lovell** [comment]
Please can you run `npm ls sharp` in the same directory as your `package.json` file (might be `/Users/dennis/Documents/Projecten/shopify-viv-headless`).

**Comment by DennisKraaijeveld** [comment]
```
❯ npm ls sharp
picksy@1.2.0 /Users/dennis/Documents/Projecten/shopify-viv-headless
├─┬ gatsby-plugin-manifest@2.4.14
│ └── sharp@0.25.2
├─┬ gatsby-plugin-sharp@2.5.6
│ └── sharp@0.25.2 deduped
└─┬ gatsby-transformer-sharp@2.4.6
  └── sharp@0.25.2 deduped
```

**Comment by lovell** [comment]
Please can you upgrade to the latest `gatsby-*` packages.

**Comment by lovell** [comment]
It looks like the latest version of Gatsby is now using the latest version of sharp so M1-related problems should hopefully go away after upgrading - see https://www.gatsbyjs.com/docs/reference/release-notes/v3.3/
