### ISSUE TITLE
[Error: Input file is missing]

### ISSUE THREAD

**Issue by ChristianGrieger** [lovell/sharp#2615]
What are you trying to achieve?

Overlap two images but it tells [Error: Input file is missing].

Have you searched for similar questions?

Yes

Are you able to provide a minimal, standalone code sample that demonstrates this question?

```
const sharp = require('sharp')

sharp(__dirname + '/background_blue.png')
    .composite([{ input: __dirname + '/skin_blue.png', blend: 'over' }])
    .composite([{ input: __dirname + '/mouth_closed.png', blend: 'over' }])
    .resize(1000, 1000)
    .toFile(__dirname + 'output.png')
```

Are you able to provide a sample image that helps explain the question?

<img width="946" alt="Bildschirmfoto 2021-03-11 um 16 00 24" src="https://user-images.githubusercontent.com/8712219/110807332-349d9000-8283-11eb-9f95-c885a5aa972c.png">

**Comment by ChristianGrieger** [comment]
I found the problem was background_blue.png has to be .jpg but I still not get the result I want. 

The images provided are 100x100 I would like to add one over the other and at the end resize all to 1000x1000.

Maybe someone could provide me a help? :) TY

**Comment by lovell** [comment]
Try something like the following (untested):
```js
  const composited = await sharp(__dirname + '/background_blue.jpg')
    .composite([
      { input: __dirname + '/skin_blue.png', blend: 'over' },
      { input: __dirname + '/mouth_closed.png', blend: 'over' }
    ])
    .toBuffer();
  await sharp(composited)
    .resize(1000, 1000)
    .toFile(__dirname + 'output.png')
```

**Comment by ChristianGrieger** [comment]
Thanks for the fast reply :)

- Is it possible to disable round corners?
- And it looks like it does not only overlay but also optimize.

So instead of:

![__generate_appoutput](https://user-images.githubusercontent.com/8712219/110811890-687ab480-8287-11eb-985f-a5cb88981a67.png)

It should end as:

<img width="1024" alt="Bildschirmfoto 2021-03-11 um 16 35 26" src="https://user-images.githubusercontent.com/8712219/110812330-ceffd280-8287-11eb-9cf5-0bbd70719ade.png">

**Comment by lovell** [comment]
To avoid compression artefacts, do the PNG conversion earlier. It also looks like you want nearest neighbour interpolation when enlarging.

https://sharp.pixelplumbing.com/api-resize#resize

```diff
  const composited = await sharp(__dirname + '/background_blue.jpg')
    .composite([
      { input: __dirname + '/skin_blue.png', blend: 'over' },
      { input: __dirname + '/mouth_closed.png', blend: 'over' }
    ])
+   .png()
    .toBuffer();
  await sharp(composited)
-   .resize(1000, 1000)
+   .resize(1000, 1000, { kernel: 'nearest' })
    .toFile(__dirname + 'output.png')
```

**Comment by ChristianGrieger** [comment]
Perfect! Thank you very much :)
