### ISSUE TITLE
Wrong orientation, width and height on metadata

### ISSUE THREAD

**Issue by bvalentinaa** [lovell/sharp#2617]
I try to resize an image, but first I need to check if the image is portrait or landscape so I can give different dimensions (width and height).
function resizeImage(parameters) {
    const inputImage = sharp(inputPath);
        const compressedImage = inputImage
            .metadata()
            .then(async function(metadata) {
                console.log('orientation', metadata.orientation)
                const initialHeight = metadata.height;
                const initialWidth = metadata.width;
                console.log('width', initialWidth);
                console.log('height', initialHeight);
           if (initialWidth > initialHeight){ //image is landscape
                    return inputImage
                    .resize({
                        height: IMAGE_RESOLUTION,
                        fit: 'contain'
                    })
                    .toFile(outputFileFFmpeg720)
                    .then(async fileInfo => {
                       doSomething()
                    }).catch(err =>...)
} else...image is portrait
Besides the fact that it rotates my portrait images, which I fixed using .rotate(), metadata coming for portrait images is wrong, as it sets the width for height and viceversa. I tried to do the verification with the orientation number but turns out that for a mirrored image the orientation number is wrong.
Also, I tried using withMetadata() function. To sum up, what I want to do is to check either an image is portrait or landscape

**Comment by lovell** [comment]
> Besides the fact that it rotates my portrait images, which I fixed using .rotate(), metadata coming for portrait images is wrong, as it sets the width for height and viceversa

It sounds like your images contain EXIF metadata.

https://sharp.pixelplumbing.com/api-input#metadata

> width: Number of pixels wide (EXIF orientation is not taken into consideration)
height: Number of pixels high (EXIF orientation is not taken into consideration)

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
