### ISSUE TITLE
blur(sigma) and sharpen(radius, flat, jagged) failing with parameters out of range in 0.11.12

### ISSUE THREAD

**Issue by chrisriley** [lovell/sharp#262]
Hello,

With the upgrade to nan v2 in 0.11.12 the baton values for blurSigma, sharpenFlat, and sharpenJagged are being cast to int32_t causing blur(sigma) and sharpen(radius, flat, jagged) to fail with "parameters out of range" (at least with nodejs 0.12.7). Casting these values to doubles fixes the issues. I updated pipeline.cc in my local repo and was able to use floating point values for sigma, flat, and jagged again. I created a pull request with the patch.

Best Regards,
Chris

**Comment by lovell** [comment]
Thank you for reporting and fixing this problem via #263 Chris. I'll leave this issue open whilst I improve the sharpen tests to ensure this doesn't happen again.

**Comment by chrisriley** [comment]
Hi Lovell, thanks for responding so quickly and thank you for all of the great work you've done with sharp.

**Comment by lovell** [comment]
Commit 692e2d4 should improve the testing of blur and sharpen operations. I'll get your fix out in a v0.11.3 release either today or tomorrow. Thanks again.

**Comment by lovell** [comment]
v0.11.3 now available via npm
