### ISSUE TITLE
Support output with custom ICC from buffer

### ISSUE THREAD

**Issue by LazyLZ** [lovell/sharp#2621]
Hi, is there possible to set custom ICC from a buffer?

I'm trying to resize images and output with their original ICC. I use this code but it didn't work

```javascript
cursor = sharp(input, options)

const metadata = await cursor.metadata()

cursor = cursor.resize(width, height, { fit: 'cover' })

const outputBuffer = cursor.withMetadata({icc: metadata.icc}).toBuffer()
```

or is any other way to achieve this?

**Comment by lovell** [comment]
I think this is covered by #1323, which includes a possible workaround in comment https://github.com/lovell/sharp/issues/1323#issuecomment-812041129

**Comment by RKTZ** [comment]
This feature would be nice !
