### ISSUE TITLE
libimagequant for AWS Lambda function/Layer

### ISSUE THREAD

**Issue by ZANZAAA** [lovell/sharp#2623]
What are you trying to achieve?
I want to create a **Layer** for a Lambda function that contains all the modules for sharp.

I've read the documentation and I've used `npm install --arch=x64 --platform=linux sharp` to install sharp with Linux binaries.

Now, I want to use the option 'quality' when the output is png. However it "requires libvips compiled with support for libimagequant".

I'm on windows and I don't really want to install docker. I'm trying to find a way to get libimagequant working with sharp on windows and then create a script similar to the one above when I want to deploy to AWS.

Here are a few links I've used:
https://github.com/kleisauke/libvips-packaging/issues/2
https://github.com/lovell/sharp/issues/1631

Does anyone have already faced this problem?

**Comment by lovell** [comment]
The forthcoming v0.28.0 will include PNG quantisation features in the prebuilt binaries - please subscribe to https://github.com/lovell/sharp/issues/2604

**Comment by ZANZAAA** [comment]
Awesome, thanks for the quick reply :)
