### ISSUE TITLE
How to read a sharp object and convert it to a Blob?

### ISSUE THREAD

**Issue by btahir** [lovell/sharp#2625]
Hello!

Awesome library. I'm just getting into it and perhaps tripping on some basic things but my objective is simply to return an image from a nodejs api (I am using Nextjs) and render it on screen.

I am sending back the image with a .png() method on it which generates something like this:

```
obj: [
    {
      _readableState: [Object],
      readable: true,
      _events: {},
      _eventsCount: 0,
      _writableState: [Object],
      writable: true,
      allowHalfOpen: true,
      options: [Object]
    }
  ]
```

Then on my frontend I am trying to inject this into an img

```
const [src, setSrc] = useState('');
useEffect(() => {
    const blob = new Blob([data.obj], {type: 'image/png'})
    const urlBlob = URL.createObjectURL(blob)
    setSrc(urlBlob)
    
  }, [])

// return an image with the blob
return (
<img src={src} />
)
```

The image is blank currently and the Blob does not seem to have been created. I tried differnet otions like .raw() and .toBuffer() as well but no luck. I am probably just not passing the right property or using the correct operation before passing the object. Any help on this would be appreciated.

Thanks!

**Comment by lovell** [comment]
> I am sending back the image with a .png() method on it which generates something like this:
> ```
> obj: [
>    {
>      _readableState: [Object],
> ```

This looks like a partial Node.js `Stream` object.

If you want compressed, PNG output, use something like the follow:

```js
const data = await sharp(input).png().toBuffer();
```

If you need further help, please provide a more complete code sample.

**Comment by btahir** [comment]
Thanks. I added toBuffer(). This is how I am sending the object forward:

```
image
        .extract({ left: 0, top: 0, width: oneThirdWidth, height: oneThirdHeight })
        .png()
        .toBuffer()
        .then((data) => {
          res.json({ status: 'Success!', obj: data })
        })
        .catch(err => { console.log('err', err) });
```

and I can retrieve the object on the front end which looks something like this:

```
{
    format: 'png',
    width: 360,
    height: 540,
    channels: 3,
    premultiplied: false,
    size: 152956
  }
```

But this doesn't seem to have the actual data(binary info)? How do I convert it into a Blob so I can set it to an img tag? This is the code I am working with. I am use the createObjectURL.

```
const blob = new Blob([data.obj], {type: 'image/png'})
    const urlBlob = URL.createObjectURL(blob)
```

Thanks!

**Comment by lovell** [comment]
> and I can retrieve the object on the front end which looks something like this:
> ```
> {
>   format: 'png',
>   width: 360,
>   ...
> ```

This looks like the `info` property you might expect [toBuffer](https://sharp.pixelplumbing.com/api-output#tobuffer) to resolve with when it is called with `{ resolveWithObject: true }`.

Please can you provide a more complete code sample, ideally so someone else can reproduce this.

**Comment by btahir** [comment]
I was able to figure it out! There was something weird going on with the way I was calling the methods I guess because it worked fine when I simplified the code. Just in case anyone else asks this question I was sending back the Buffer object from Node like this:

```
await image
    .extract({ left: twoThirdWidth, top: twoThirdHeight, width: oneThirdWidth, height: oneThirdHeight })
    .jpeg()
    .toBuffer()
    .then(data => {
     // send data back
    })
    .catch(err => { console.log('err', err) });
```

And I managed to convert it into a Blob object to then display in an img tag with this:

```
const blob = new Blob([new Uint8Array(item.data)], {type: 'image/jpeg'})  
const urlBlob = URL.createObjectURL(blob)
```

Thanks for looking this over with me!
