### ISSUE TITLE
Image max size

### ISSUE THREAD

**Issue by aquaductape** [lovell/sharp#2627]
Is there a parameter equivalent that compresses or set a specific image size? 
An example would be if an image size is over 3.5MB, it would compress it to 3.5MB or below. Something similar to the client library [browser-image-compression](https://www.npmjs.com/package/browser-image-compression), here's a code example.

```js
const options = { 
  maxSizeMB: 3.5
}

imageCompression(file: File, options): Promise<File>
```

**Comment by lovell** [comment]
Hello, the `browser-image-compression` module will brute force this logic by reducing the PNG "quality" (number of colours in the palette?) by 5% on each iteration.

https://github.com/Donaldcwl/browser-image-compression/blob/0191a7ad0c7efaca13bb4545775974f3b3b862b7/lib/image-compression.js#L88-L97

Perhaps you could add something similar to your own code?

**Comment by aquaductape** [comment]
that makes sense why when using `browser-image-compression` module the  image size result wouldn't be exact to the parameter.

Yeah I don't mind building a scuffed version to fit my needs.
