### ISSUE TITLE
<image> xlink:href base64 WebP not rendering

### ISSUE THREAD

**Issue by wilddip** [lovell/sharp#2630]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`? Yes, 0.27.2

What are the steps to reproduce? Import my svg

What is the expected behaviour? Correct render image

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

```js
await sharp(Buffer.from(avatar), {width: 80, height: 80}).toBuffer();
```
[Working SVG](https://gist.github.com/wilddip/870f2ea183013a5327696a9ead7e36a4)
[Current SVG](https://gist.github.com/wilddip/3f46344c823c247c4162532fde783ff3) - [src](http://jsfiddle.net/b4L17p5v/3)
> 45 line
> Changing data:image/jpeg to data:image/png or data:image/webp doesn't help

Are you able to provide a sample image that helps explain the problem? [ofk](https://imgur.com/a/EvpL1QH)

What is the output of running `npx envinfo --binaries --system`?
```md
  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 8.34 GB / 15.93 GB
  Binaries:
    Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
 ```

**Comment by lovell** [comment]
Hi, the embedded image is in WebP format, which isn't supported in SVG.

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image
