### ISSUE TITLE
 Will sharp use multi-core

### ISSUE THREAD

**Issue by banli17** [lovell/sharp#2631]
I made an express application, which uses sharp, which is a 4-core server. If I only run an express process, will sharp use 4-core? I can't let express open 4 processes because there are a lot of fonts loaded into the memory in the application, which will cause insufficient memory. 
And I am going to make the picture synthesis (with the function of converting text to picture) into a single service, and finally only open one process, and then open 4 express processes to call this picture synthesis service. Don't know if it is reasonable

**Comment by lovell** [comment]
Yes, please see https://sharp.pixelplumbing.com/api-utility#concurrency for more fine-grained control over concurrency and parallelism.
