### ISSUE TITLE
Animated GIF to animated GIF (only) is weirdly slow

### ISSUE THREAD

**Issue by baptistecs** [lovell/sharp#2632]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
Yes, 0.27.2

What are the steps to reproduce?
I have done some tests with [this picture](https://mir-s3-cdn-cf.behance.net/project_modules/disp/921fb223795457.56328edb7b7bd.gif) (animated gif)
It's fast to convert this file to an animated webp (0.8 seconds)
Converting this file to a static jpeg takes 0.4 seconds)
But it's slow to convert this file to an animated gif (10.8 seconds)

What is the expected behaviour?
I don't think it should take that long for this file, something seems weird 🤷 

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
```jsx
await sharp(sourceFileFullPath, { animated: true }).toFile(targetFileFullPath);
```

```jsx
const transformer = sharp({ animated: true });
transformer.gif();
const readStream = createReadStream(sourceFileFullPath);
const writeStream = createWriteStream(targetFileFullPath);
readStream.pipe(transformer).pipe(writeStream).on('finish', () => /* ... */);
```

Are you able to provide a sample image that helps explain the problem?
[There](https://mir-s3-cdn-cf.behance.net/project_modules/disp/921fb223795457.56328edb7b7bd.gif) 

What is the output of running `npx envinfo --binaries --system`?
```shell
  System:
    OS: macOS 11.2.3
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
    Memory: 4.28 GB / 15.83 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 2.4.0 - ~/.yarn/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
```

**Comment by lovell** [comment]
Hi, as you've probably seen, GIF encoding is via ImageMagick (I suspect you've installed vips via HomeBrew). https://sharp.pixelplumbing.com/api-output#gif

As a result, I wouldn't expect this to be fast and I've never done any testing on how badly it might perform. To see if there's anything we can do, we'll need to profile the running code.

You can do this via valgrind. Use `brew install valgrind` to install it, then run `valgrind --tool=callgrind node script.js` to (slowly) generate a `callgrind.out.PID` file (where PID is the process ID), which can then be analysed by running `callgrind_annotate callgrind.out.PID`

As an aside, if there's a possible solution to your problem that involves removing animated GIFs entirely, then that's usually the best approach.

**Comment by baptistecs** [comment]
Hi,
Yes, I have installed Vips via HomeBrew, on my development computer, I will see how it goes once on an ARM linux server 🤞
Thank you for your help! 🙂
Kind regards
