### ISSUE TITLE
Extraced JPEG from PDF is much smaller

### ISSUE THREAD

**Issue by David-Kelm** [lovell/sharp#2635]
Sharp Version: 0.27.2

What are the steps to reproduce?
1. Compile libvips 8.10.6 with Pdfium 4455
2. Load a PDF with sharp
3. Extract a JPEG via `jpeg({quality: 100})`

The Problem is that the extracted JPEG is much smaller than the original JPEG.

What is the expected behaviour?
The extracted JPEG should have the same width and height as the original JPEG.

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
```javascript
const sharpImage = sharp(pdfPath, {
  page: 1,
  pages: 1,
  limitInputPixels: false,
});
sharpImage.jpeg({quality: 100});
```

Are you able to provide a sample image that helps explain the problem?
The original JPEG:
![960x640 Original](https://user-images.githubusercontent.com/54929831/112343341-50615700-8cc3-11eb-9516-7609edd3f4db.jpeg)

The PDF:
[Example.pdf](https://github.com/lovell/sharp/files/6198833/Example.pdf)

The extracted JPEG:
![230x152 Extracted](https://user-images.githubusercontent.com/54929831/112343486-77b82400-8cc3-11eb-885a-271410c32916.jpeg)

What is the output of running `npx envinfo --binaries --system`?
```
  System:
    OS: Linux 5.4 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (4) x64 Common KVM processor
    Memory: 3.63 GB / 15.64 GB
    Container: Yes
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
```
Incresing the `densitive` within the constructor helps, but it increases the JPEG size strongly. Perhaps is PDFium the reason.

**Comment by lovell** [comment]
> Incresing the densitive within the constructor helps, but it increases the JPEG size strongly. 

You're correct in that the `density` setting is what you'll need to alter when converting PDF-based input to a bitmap output. The use of `quality: 100` is probably too high for this image as it looks like the original was compressed with a "quality" of ~90.

It also looks like this sample PDF file has `x-ppi` and `x-ppi` metadata that might not be correct, so this could be an encoding problem, or possibly a pdfium decoding problem too.

```sh
$ pdfimages -list Example.pdf 
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image     960   640  rgb     3   8  jpeg   no        25  0   301   300  301K  17%
```

**Comment by David-Kelm** [comment]
Thank you for your fast reply.
Indeed, it was the PDF which was causing the problem. Trying out the same operation on a different PDF seemed to solve the problem.
