### ISSUE TITLE
Is it possible to just remove exif of an image?

### ISSUE THREAD

**Issue by ehsan2003** [lovell/sharp#2636]
What are you trying to achieve?
I want to remove image exif in sharp but in an efficient way and without additional library or using the existing methods like resizing without sizes ...
is it possible?
if it is not possible I think it may be a good feature for sharp because it is useful to just remove exif of an image with just sharp in a way which sharp doing things
Have you searched for similar questions?
yes
Are you able to provide a minimal, standalone code sample that demonstrates this question?

Are you able to provide a sample image that helps explain the question?

**Comment by lovell** [comment]
If you're hoping to do this without a de/compression roundtrip, I'd recommend something like the [jhead](https://linux.die.net/man/1/jhead) command line tool. See also the future possible enhancement #650 that covers modification of EXIF metadata and might be relevant.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
