### ISSUE TITLE
Jpg portrait picture from iphone is not resizing

### ISSUE THREAD

**Issue by garcia-marco** [lovell/sharp#2645]
### Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
Yes.

### What are the steps to reproduce?
Take a portrait picture with an iphone, share it in jpg (`Settings>Photos>Transfer to mac or pc` set to automatic).
Try to resize with sharp with metadata (without them the picture is not oriented correctly).
The picture is not resize.

### What is the expected behaviour?
The picture should resize.

### Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
```
const sharp = require('sharp')

await sharp('before.jpg')
    .resize(590, 394)
    .withMetadata()
    .jpeg()
    .toFile('after.jpg')
```

### Are you able to provide a sample image that helps explain the problem?
Before sharp
![before](https://user-images.githubusercontent.com/26541750/113004656-0faa8780-9174-11eb-8eea-cee296e97b71.jpg)
After sharp
![after](https://user-images.githubusercontent.com/26541750/113004652-0f11f100-9174-11eb-9633-c0495518319c.jpg)

### What is the output of running `npx envinfo --binaries --system`?
```
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 16.89 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.3 - ~/.volta/tools/image/node/14.15.3/bin/node
    Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
    npm: 6.14.11 - ~/.volta/tools/image/npm/6.14.11/bin/npm
```

### Workaround
I've managed to make a workaround but I don't think it's an expected behavior from the start. If it can help someone.
```
const sharp_img = await sharp('before.jpg')
if ((await sharp_img.metadata()).orientation === 6) {
    await sharp_img.rotate()
}
await sharp_img
    .resize(590, 394)
    .jpeg()
    .toFile('after.jpg')
```

**Comment by lovell** [comment]
The original image is 640x480 landscape with EXIF orientation 6.

Do you want to autorotate based on the EXIF metadata and therefore remove the EXIF metadata from the output, or do you want to ignore the EXIF metadata (i.e. no autorotate) and have the same EXIF metadata remain intact in the output?

**Comment by garcia-marco** [comment]
I want to keep the original orientation of the image and resize it (I don't need metadata after resize).

To explain a bit more, It's an upload system for users, so I need to resize files from any ratio, orientation or size to 590x394

**Comment by lovell** [comment]
When you say "original orientation", does "original" refer to the EXIF orientation, which would treat the input image as a 480x640 portrait, or does "original" refer to the pixel ordering (without EXIF), which would treat the input image as a 640x480 landscape?

**Comment by garcia-marco** [comment]
I'm refering to the EXIF orientation

**Comment by lovell** [comment]
Thanks, you should be able to use `rotate()` to autorotate based on the EXIF orientation and remove `withMetadata()` as you do not require this.
```js
await sharp('before.jpg')
    .rotate()
    .resize(590, 394)
    .toFile('after.jpg');
```

(EXIF orientation metadata can get rather confusing, especially as different software renders and/or reports it slightly differently.)

**Comment by garcia-marco** [comment]
Oh ok I hadn't understand the implication of the EXIF orientation metadata, thanks for the explaination and the help !

**Comment by philip-nicholls** [comment]
I only ask this because it's very confusing, but from what I can tell, doing:
`sharp('image.jpg').resize(600,400).toBuffer()`
and
`sharp('image.jpg').resize(600,400).withMetadata().toBuffer()`
either removes the orientation meta stored, or incorrectly orientates the output image so that it is the wrong orientation.  Yet:
`sharp('image.jpg').rotate().resize(600,400).toBuffer()`
seems to solve the issue.

Wouldn't it be better to just always call `.rotate()` internally when sharp imports an image?  I can't think why you wouldn't want to NOT lose the orientation.

This was also suggested here:
https://stackoverflow.com/a/58828508/2116253
