### ISSUE TITLE
Animation removed from webp

### ISSUE THREAD

**Issue by Nachtalb** [lovell/sharp#2648]
As per https://github.com/lovell/sharp/issues/518 and https://github.com/libvips/libvips/issues/823 sharp should be able to handle animated webps. 

I am not very fluent in sharp nor JS in general, so there may be something I am doing wrong. If that is the case please enlighten me :) 

Also question on the side, why can't I use `fileStream.pipe(sharp().foFile(destPath))` (results in `TypeError: dest.on is not a function`). If this is out of scope that's ok as well. 

Using sharp `0.28.0`

What are the steps to reproduce?
File used for testing: https://files.catbox.moe/lap1sg.webp
File saved by sharp: https://files.catbox.moe/3okmbm.webp

```js
const fileStream = ...  // FileStream of mentioned animated webp
const destPath = ...  // string of destination path

const chunks = []
fileStream.on('data', (chunk) => {
	chunks.push(chunk)
})
.on('end', () => {
	  const buffer = Buffer.concat(chunks);
	  // fs.writeFile(destPath, buffer, () => {});  // results in working animated webp at destPath
	  sharp(buffer).toFile(destPath)	// Removes metadata by default
		  .catch(abortWithError);
});
``` 

What is the expected behaviour?
Metadata removed and animation untouched

Running inside WSL 2.0 
```
❯ npx envinfo --binaries --system
npx: installed 1 in 0.811s

  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
    Memory: 4.19 GB / 7.74 GB
    Container: Yes
    Shell: 3.1.0 - /usr/bin/fish
  Binaries:
    Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.3/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.3/bin/npm
```

**Comment by lovell** [comment]
Hi, you can specify that you want all frames, rather than the default first frame, by using:

```diff
- sharp(buffer).toFile(destPath)
+ sharp(buffer, { animated: true }).toFile(destPath)
```
https://sharp.pixelplumbing.com/api-constructor#parameters

**Comment by Nachtalb** [comment]
ahh darn, I looked at the documentation about webp and toFile not at the sharp constructor itself... 🤦 
Thank you!

**Comment by lovell** [comment]
I've added an animated WebP example to the `webp()` docs via commit https://github.com/lovell/sharp/commit/08a25a0c8fb4dfaa5bddd7d0f4f0eea55cce2f65
