### ISSUE TITLE
Looping composition of image

### ISSUE THREAD

**Issue by codingenvy** [lovell/sharp#2649]
Hi all, I am trying to set up a filter to bend an image.
The input image is sliced in 1px wide columns and those columns will be composited onto a new image (with an offset lateron). I am able to extract stripes from the original image (straightImg) and get a composition, but the result has only one single stripe added to it.
As far as I can tell the behaviour is caused by me not being able to properly chain bentImg after each iteration. It looks as if it is always referencing the original empty image.
How could this be achieved?
 
```
let bentImg = await sharp({
    create: {
      width: inputWidth,
      height: inputHeight,
      channels: 4,
      background: { r: 255, g: 0, b: 0, alpha: 0.5 },
    },
  });  

for (let i = 0; i < inputWidth; i++) {
    let stripe = await straightImg
      .extract({
        left: i,
        top: 0,
        width: 1,
        height: inputHeight,
      })
      .toBuffer();
    bentImg = await bentImg
      .composite([
        {
          input: stripe,
          top: i,
          left: i,
        },
      ]);
  }
return await bentImg.png().toBuffer();
```

**Comment by lovell** [comment]
Hi, as `composite()` accepts an array, perhaps you could build that array within the loop, then only call it once after the loop.

**Comment by codingenvy** [comment]
Hi Lovell, thanks for getting back to me (and the great software!).
Creating the array beforehand and compositing later works, but only on fairly small images. I get an out of memory error quickly on larger files.
So far I have this - maybe there is a better solution than keeping all the stripes in memory until composition? I would like to build the bent image twice the size and scale down to get some anti-aliasing.
```
let stripes = [];
  let stripe;
  for (let x = 0; x < metadata.width; x++) {
    let radiusA = metadata.width / 2;
    let calcX = x - radiusA;
    let offsetY =
      radiusB * Math.sqrt(1 - (calcX * calcX) / (radiusA * radiusA));
    stripe = await straightImg
      .extract({
        left: x,
        top: 0,
        width: 1,
        height: metadata.height,
      })
      .toBuffer();
    stripes.push({ input: stripe, top: Math.floor(offsetY), left: x });
  }
  return await bentImg
    .composite(stripes)
    .png()
    .toBuffer();
```

**Comment by lovell** [comment]
An alternative might be to compress the intermediate files, a bit like (untested):
```diff
  let bentImg = await sharp({
    create: {
      width: inputWidth,
      height: inputHeight,
      channels: 4,
      background: { r: 255, g: 0, b: 0, alpha: 0.5 },
    },
-  });
+  }).png().toBuffer();

  for (let i = 0; i < inputWidth; i++) {
    let stripe = await straightImg
      .extract({
        left: i,
        top: 0,
        width: 1,
        height: inputHeight,
      })
      .toBuffer();
-    bentImg = await bentImg
+    bentImg = await sharp(bentImg)
      .composite([
        {
          input: stripe,
          top: i,
          left: i,
        },
-      ]);
+      ]).png().toBuffer();
  }
- return await bentImg.png().toBuffer();
+ return bentImg;

**Comment by codingenvy** [comment]
Yes - it is working now! Thank you for your help - next time I am in London you'll get a bottle of that gin we are building the label designer for ;) Cheers

**Comment by lovell** [comment]
No worries, that sounds amazing, offer gladly accepted.
