### ISSUE TITLE
preinstall.sh: vips was not found in the pkg-config path

### ISSUE THREAD

**Issue by jonathanong** [lovell/sharp#265]
https://travis-ci.org/#L224

do you know what's up with this? maybe travis is too old?

**Comment by lovell** [comment]
Hello. Which project/repo is this? (I think the URL is incomplete.)

**Comment by jonathanong** [comment]
LOL wow https://travis-ci.org/mgmtio/video-phash-service#L222

**Comment by lovell** [comment]
It looks like commit https://github.com/mgmtio/video-phash-service/commit/2eb286bf0fa06decc917ff04d928e8f017597503 added the `addons` option that will switch you to the non-sudo Docker-based infra.

Adding a `sudo: required` option should fix this and https://travis-ci.org/mgmtio/video-thumbnail-extractor

**Comment by jonathanong** [comment]
INTERESTING
