### ISSUE TITLE
The image transformed from PNG to webp cannot be displayed on IOS 14.4，why？

### ISSUE THREAD

**Issue by flitrue** [lovell/sharp#2650]
sharp 0.28.0

image here: 

![5C9E685CEF5F221803FF516A9C980E92](https://user-images.githubusercontent.com/15258895/113475563-089fb400-94a9-11eb-921e-7e6fcb141b11.png)

`sharp(input).webp().toFile()`

**Comment by lovell** [comment]
This is a 2-channel grey+alpha PNG image. The grey channel is fully zero (black) and the "picture" you see is in the alpha transparency layer letting through some of the (in this case white) background. The pixel values are preserved when converting to WebP, but the browser is probably rendering onto a black background. This is more a limitation of the WebP format and/or the browser.

If you know the picture is in the alpha channel, you can extract it via:

```js
sharp(input).extractChannel('alpha').webp().toFile()
```

https://sharp.pixelplumbing.com/api-channel#extractchannel

**Comment by flitrue** [comment]
thanks
