### ISSUE TITLE
converting png => jpeg outputs have quality difference between sharp and sharp-cli

### ISSUE THREAD

**Issue by ddevkim** [lovell/sharp#2652]
1. sharp-cli
: sharp -i image.png -q 100 -o image.jpeg

2. node sharp
: sharp(image)
  .jpeg({ quality: 100 })
  .toBuffer();
  
  and then create file using filesystem fs.writefile at somewhere

I tried above two file conversion with this image [https://s3.marpple.co/files/u_193535/2021/4/original/ed27427d55d67ff80eb6305ef4373d6a056117cb1.png](url)

but jpeg quality is deteriorated when using 2nd method.

Is there something that I do wrong?

**Comment by lovell** [comment]
sharp-cli is maintained independently of sharp - please see https://github.com/vseventer/sharp-cli

I think you'll need to set `chromaSubsampling` to `4:4:4` to match its current behaviour.

```diff
- .jpeg({ quality: 100 })
+ .jpeg({ quality: 100, chromaSubsampling: '4:4:4' })
```

https://sharp.pixelplumbing.com/api-output#jpeg

**Comment by ddevkim** [comment]
Thank you so much, lovell. You save my day!
