### ISSUE TITLE
Error on Docker

### ISSUE THREAD

**Issue by legion-zver** [lovell/sharp#2656]
After upgrade to latest sharp version from 0.27.2 get error:

```
Something went wrong installing the "sharp" module

Error relocating /usr/lib/libpangoft2-1.0.so.0: g_memdup2: symbol not found
```

# Install depends on docker file
```
FROM node:current-alpine3.13 As builder

RUN apk add --no-cache --virtual build-dependencies ca-certificates ffmpeg libheif libheif-dev libva-intel-driver python3-dev python3 py3-pip build-base

RUN apk add --update --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/community --repository http://dl-3.alpinelinux.org/alpine/edge/main vips-dev

WORKDIR /app
```

**Comment by lovell** [comment]
Hi, it looks like you're adding Alpine edge/community packages to an Alpine 3.13 base, which can cause this kind of conflict. This is an Alpine cross-version dependency problem unrelated to sharp or libvips.

sharp provides prebuilt binaries for the musl-based Alpine that should "just work", so perhaps remove the `vips-dev` package and its dependency chain.

**Comment by meodemsao** [comment]
I have same issues

**Comment by meodemsao** [comment]
> Hi, it looks like you're adding Alpine edge/community packages to an Alpine 3.13 base, which can cause this kind of conflict. This is an Alpine cross-version dependency problem unrelated to sharp or libvips.
> 
> sharp provides prebuilt binaries for the musl-based Alpine that should "just work", so perhaps remove the `vips-dev` package and its dependency chain.

Confirm remove ```vips-dev``` package resolve this issues
p/s: i upgrade using sharpjs 0.28.1

**Comment by lovell** [comment]
The underlying issue is that some Alpine edge packages are now dependent on the changes in https://gitlab.gnome.org/GNOME/glib/-/issues/2319 but the glib package from Alpine 3.13 does not provide it.
