### ISSUE TITLE
Sharp does not work in Electron production

### ISSUE THREAD

**Issue by fupdec** [lovell/sharp#2657]
> Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?

yes, i did

> Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

yep

I am making an application with Electron for all operating systems.
I need to make a build for Linux. I am using a virtual machine with Ubuntu 20.04. And I finally installed Sharp correctly using the command: `SHARP_IGNORE_GLOBAL_LIBVIPS=true npm install sharp`

Now my application can convert images, but only when I run it in development mode.
After building the app, when I try to convert an image, Sharp throws an error in the console:
`Uncaught (in promise) Error: Input buffer contains unsupported image format`

The same error occurred in development mode, before I installed Sharp without a flag `SHARP_IGNORE_GLOBAL_LIBVIPS=true`
From which I conclude that during the build Sharp takes the global libvips. 

This is the log during build:

 ```
INFO  Building app with electron-builder:
  • electron-builder  version=22.10.5 os=5.8.0-48-generic
  • writing effective config  file=dist_electron/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=sharp@0.28.1 platform=linux arch=x64
  • install prebuilt binary  name=sharp version=0.28.1 platform=linux arch=x64
  • build native dependency from sources  name=sharp
                                          version=0.28.1
                                          platform=linux
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 6.1.1
    prebuild-install WARN install prebuilt binaries enforced with --force!
    prebuild-install WARN install prebuilt binaries may be out of date!
    prebuild-install info looking for local prebuild @ prebuilds/sharp-v0.28.1-electron-v87-linux-x64.tar.gz
    prebuild-install info looking for cached prebuild @ /home/user/.npm/_prebuilds/ca00d1-sharp-v0.28.1-electron-v87-linux-x64.tar.gz
    prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.28.1/sharp-v0.28.1-electron-v87-linux-x64.tar.gz
    prebuild-install http 404 https://github.com/lovell/sharp/releases/download/v0.28.1/sharp-v0.28.1-electron-v87-linux-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=12.0.2 runtime=electron arch=x64 libc= platform=linux)
    
  • packaging       platform=linux arch=x64 electron=12.0.2 appOutDir=dist_electron/linux-unpacked
  • Unpacking electron zip  zipPath=undefined
  • downloading     url=https://github.com/electron/electron/releases/download/v12.0.2/electron-v12.0.2-linux-x64.zip size=79 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v12.0.2/electron-v12.0.2-linux-x64.zip duration=1m44.327s
  • building        target=AppImage arch=x64 file=dist_electron/AVDB-0.8.0.AppImage
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z size=1.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z duration=9.702s
 DONE  Build complete!
```

**Comment by lovell** [comment]
Please see https://github.com/develar/app-builder/pull/47 and https://github.com/electron-userland/electron-builder/issues/5438

**Comment by fupdec** [comment]
Thanks for the quick response. In other words, will I have to wait for the new version of the electron builder?

**Comment by lovell** [comment]
Yes, it looks like the `electron-builder` fix is merged but not yet released.

**Comment by marciomarim** [comment]
Having same issue here, is there any release date for this fix?

**Comment by AlanSean** [comment]
> 请参阅[develar / app-builder＃47](https://github.com/develar/app-builder/pull/47)和[electronic-userland / electron-builder＃5438](https://github.com/electron-userland/electron-builder/issues/5438)

I tried, but it didn't work
