### ISSUE TITLE
Can't use sharp in a web app

### ISSUE THREAD

**Issue by FeixuRuins** [lovell/sharp#2659]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
Yes

What are the steps to reproduce?
Install sharp and try to use it in a web app (for example, Vue)

What is the expected behaviour?
It should work.

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
```vue
<script lang="ts">
  import sharp from 'sharp';
  export default {
    // ...
    mounted() {
      sharp(/* buffer */)
        .toBuffer()
        .then(console.log)
        .catch(console.error);
    }
    // ...
  }
</script>
```

Are you able to provide a sample image that helps explain the problem?
![image](https://user-images.githubusercontent.com/66232834/114280018-62eac880-9a05-11eb-8a2f-b36968bb7321.png)

**Comment by lovell** [comment]
sharp requires the Node.js runtime so will not work as part of client-side code running in a web browser.

**Comment by FeixuRuins** [comment]
Disappointing. Is there any work that could be done to make Sharp available for client-side use?

**Comment by lovell** [comment]
I currently recommend the use of [jimp](https://www.npmjs.com/package/jimp) for client-side image processing.
