### ISSUE TITLE
Sharp doesn't unlock file when convert webp to something

### ISSUE THREAD

**Issue by OcelotJungle** [lovell/sharp#2660]
**Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?**
Yes.

**What are the steps to reproduce?**
Open webp file with sharp() constructor, convert to any format (even webp), save to file, try to fs.unlink source file.

**What is the expected behaviour?**
Unlinking source file.

**Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?**
```js
const imageResource = sharp(rawPath);
await imageResource.toFile(getJpgPath(type, name));
await imageResource.toFile(getWebpPath(type, name));
await fs.unlink(rawPath);
```

**Are you able to provide a sample image that helps explain the problem?**
![image](https://user-images.githubusercontent.com/7084102/114301447-64d48a80-9ade-11eb-8635-82650bffc8a4.png)

**What is the output of running `npx envinfo --binaries --system`?**
```
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz
    Memory: 8.44 GB / 15.67 GB
Binaries:
    Node: 14.15.1 - C:\Node.js\node.EXE
    npm: 6.14.8 - C:\Node.js\npm.CMD
```

With other source file's format it works well.

**Comment by lovell** [comment]
Please see #415

**Comment by OcelotJungle** [comment]
> Please see #415

Oops. Honestly, I tried to search. Couldn't imagine that ~bug can be caused by external lib. Thank you.
