### ISSUE TITLE
Apply CSS filter to SVG before rendering to PNG

### ISSUE THREAD

**Issue by igrek8** [lovell/sharp#2662]
I have the following svg content:

```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" fill="inherit" style="filter: invert(62%) sepia(71%) saturate(344%) hue-rotate(77deg) brightness(90%) contrast(90%);">
  <circle cx="50" cy="50" r="50"/>
</svg>
```

When I view this file in browser, the image is green. However, when I try to convert the svg to png it is black.

```js
await sharp(mySVG).resize(width).png().toFile(output);
```

How to make scharp render styles filter?

**Comment by lovell** [comment]
Hello, the CSS `filter` property is currently [a working draft](https://www.w3.org/TR/filter-effects/#FilterProperty) and has yet to be implemented in librsvg.

https://gitlab.gnome.org/GNOME/librsvg/-/issues/614

**Comment by igrek8** [comment]
@lovell thank you!
