### ISSUE TITLE
Package variants

### ISSUE THREAD

**Issue by arcanis** [lovell/sharp#2663]
Hi 👋

I've opened an RFC on Yarn to discuss a potential builtin (hopefully cross-package-manager) way to manage prebuilt packages. If you're interested to take a look (and check if it would be compatible with Sharp) it would be much appreciated 😃

Relevant issue: https://github.com/yarnpkg/berry/issues/2751

**Comment by lovell** [comment]
I'll close this notification issue and we can continue to track this at https://github.com/yarnpkg/berry/issues/2751
