### ISSUE TITLE
CI: Add CircleCI for arm64 builds

### ISSUE THREAD

**Issue by dennisameling** [lovell/sharp#2665]
This request didn't fit well into an existing issue template, so I decided to create a blank issue. Hope that's okay!

As you know, travis-ci.org will be shutting down at some point. They planned to do it in December 2020, but it's still live. I requested some OSS credits for travis-ci.com at the end of January, and only got a response 3 days ago, so that's 2.5 months later. They gave me 25k credits and asked me to contact them in case the credits start to run low again. This is not promising _at all_.

The good news is that CircleCI now started to offer preview access to arm64 runners as part of their free plan: https://circleci.com/pricing/#comparison-table. You can request access [here](https://www2.circleci.com/arm.html) and find the docs [here](https://github.com/CircleCI-Public/arm-preview-docs). Some OSS projects are already using this successfully, like [DDEV](https://github.com/drud/ddev/blob/master/.circleci/config.yml).

What do you think about adding CircleCI next to Travis as a back-up for arm64 builds? So that as soon as travis-ci.org shuts down, you can switch to CircleCI more easily?

I'm happy to set up the CI for you, but it would require you to first request access to the arm64 preview program as mentioned above 😊 

Thanks in advance!

**Comment by lovell** [comment]
It looks like next Monday will be the official Wave Goodbye to Travis CI day - https://blog.travis-ci.com/2021-05-07-orgshutdown

I've applied to Circle CI for access to their "Arm compute".

**Comment by lovell** [comment]
OK, we're in, and commit https://github.com/lovell/sharp/commit/69ccf1d2001649f695fde505a6060b3fd49e014a on the `circle` branch makes the switch for ARM64 builds from Travis to CircleCI.

There's an example build at https://app.circleci.com/pipelines/github/lovell/sharp/5/workflows/ba6d51fa-366a-43b9-8a6b-36277e96616c (this appears to require a CircleCI login to view, but is "public" after that).

I'm sure the config can be improved so PRs very welcome to simplify etc.
