### ISSUE TITLE
AVIF files produces are invalid and not displayed by recent Chrome Canary

### ISSUE THREAD

**Issue by kamituel** [lovell/sharp#2666]
AVIF files produced by sharp are displaying correctly in Chrome (stable), but not in latest Chrome Canary. This is because Canay has changed the way they handle (and validate) AVIF images.

This is caused [by the bug in libheif library](https://github.com/strukturag/libheif/issues/477), that is now fixed on libheif's master branch. Once they release, sharp will need to update the dependency.

[The Chromium bug I reported](https://bugs.chromium.org/p/chromium/issues/detail?id=1198455) last week contains a reproducible test case for this bug.

I've opened this issue to ensure sharp maintainers are aware of this bug in libheif. Hope that's ok.

**Comment by lovell** [comment]
Thanks for reporting this upstream and the notification, we'll pick up a new release when it's ready, I suspect this is likely to be alongside an upgrade to the forthcoming libvips v8.11.0.

**Comment by grantbeattie** [comment]
Chrome 91 (current Beta) is scheduled to be released on May 25, so hopefully a new libheif and libvips build will be available before then.

https://www.chromestatus.com/features/schedule

**Comment by adityapatadia** [comment]
Latest libheif is released.

**Comment by adityapatadia** [comment]
> Chrome 91 (current Beta) is scheduled to be released on May 25, so hopefully a new libheif and libvips build will be available before then.
> 
> https://www.chromestatus.com/features/schedule

It's actually coming in 92: https://bugs.chromium.org/p/chromium/issues/detail?id=1198455#c11

**Comment by grantbeattie** [comment]
> > Chrome 91 (current Beta) is scheduled to be released on May 25, so hopefully a new libheif and libvips build will be available before then.
> > https://www.chromestatus.com/features/schedule
> 
> It's actually coming in 92: https://bugs.chromium.org/p/chromium/issues/detail?id=1198455#c11
> Chrome 92 gets released on July 20 so we have enough time.

Nice pick up. Thanks.

I'm going to try a build with libheif 1.12.0 now.

**Comment by adityapatadia** [comment]
I already tried and everything is working fine with 1.12.0

—
Regards,
Aditya Patadia

**Comment by zachleat** [comment]
Howdy y’all—just a friendly ping to escalate this one a bit as Chrome 92 will be hitting the Beta channel on June 3 (per this comment: https://bugs.chromium.org/p/chromium/issues/detail?id=1198455#c11) and we’ll need some time to let everyone update to the newest dependencies so we don’t see broken images.

**Comment by lovell** [comment]
Luckily for all those people who will have to regenerate images as a result of this problem, AVIF encoding time in the next release will be significantly faster, almost halved - see https://github.com/strukturag/libheif/pull/496

(I intend to include the libheif patch in the prebuilt binaries provided by sharp even if it has not yet been merged/released.)

**Comment by grantbeattie** [comment]
> Luckily for all those people who will have to regenerate images as a result of this problem, AVIF encoding time in the next release will be significantly faster, almost halved - see [strukturag/libheif#496](https://github.com/strukturag/libheif/pull/496)
> 
> (I intend to include the libheif patch in the prebuilt binaries provided by sharp even if it has not yet been merged/released.)

That would be amazing. Do you have a timeframe in mind for this?

**Comment by kleisauke** [comment]
Looks like the 'pixi' box presence check was removed from Chrome 92 with commit https://github.com/chromium/chromium/commit/a5f93777d102a79dde5cfcd648f0fe3736b8d709. This allows Chrome to work properly again and decode AVIF images encoded with libheif v1.11.0 or older.

**Comment by lovell** [comment]
Phew, that's good news, the pressure is off. :sweat_smile:

**Comment by zachleat** [comment]
Seeing some additional commentary around images not rendering in Chrome Beta 93.

Did they re-enable this check?

https://github.com/11ty/eleventy-img/issues/91#issuecomment-894193142

**Comment by lovell** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1198455#c26 says

> Chrome M93 will start its transition to the Chrome Beta channel on Thu, Jul 17, 2021. We will evaluate whether to disable this check in Chrome M93 at that time.

> On the main branch (Chrome 93), I deliberately re-introduced this bug

I think this means that the strict checking has returned, might still be relaxed (again), but we should work with the assumption that it will stay. The release date for Chrome 93 is 31st August :sweat: 

The release of libvips v8.11.3 is imminent, then sharp v0.29.0 will be shortly after that, hopefully all in the next couple of weeks.

**Comment by lovell** [comment]
v0.29.0 now available, and with a whole two weeks to spare before Chrome 93 is released - go update your AVIF images.
