### ISSUE TITLE
How do I extract CYMK channels?

### ISSUE THREAD

**Issue by anthony-tron** [lovell/sharp#2669]
### What are you trying to achieve?
I have several images that I need to extract the four cyan, yellow, magenta, and black channels into separate images. The input images are already in CMYK colorspace (verified with `metadata()`)

### Have you searched for similar questions?
I have searched a lot but for some reasons it seems nobody has ever tried. Well, I think I found an issue where it was mentioned that Sharp isn't made to process with CYMK under the hood and there was no solution if I remember correctly.

### Are you able to provide a minimal, standalone code sample that demonstrates this question?

```ts
const src = sharp('img/mires-bandes-50.tif');

src.metadata()
    .then(console.log) // output : {... space: 'cmyk', ...}
    .catch(console.error);

src.withMetadata() // I think this line is useless?
    // .toColorspace('cmyk') this line doesn't change anything because input image is already cmyk
    .extractChannel(0)
    .toFile('out/channel0.tif')
    .then(info => console.log('done', info))
    .catch(console.error);
```

**Expected output** : The channel 0 as magenta according to the [docs here](https://sharp.pixelplumbing.com/api-channel#joinchannel).

**Actual output** : The channel 0 as red according to the same docs.

I'm aware that I'm referring to the wrong function (`joinChannel` instead of `extractChannel`) but the arguments are similar so I assumed that it made sense.

___

1. Is it possible to extract CYMK channels?
2. If so, how? I'm lost.

Thank you in advance!

**Comment by anthony-tron** [comment]
Update: I used libtiff to do that but it will be in C++
I would still like to know if this is possible to do that using *sharp*.

**Comment by lovell** [comment]
Hi, sorry I missed this question originally. The future possible enhancement at #2658 should make this possible.

**Comment by lovell** [comment]
Let's track this at #2658, which will be part of the next release.
