### ISSUE TITLE
Tif with mask to transparent png

### ISSUE THREAD

**Issue by ContsultGmbH** [lovell/sharp#2670]
Hello,

i try to convert a tif with a mask to a png file with a transparent background.
![image](https://user-images.githubusercontent.com/58774145/115724243-1007fe00-a381-11eb-96fb-733281c8c788.png)

Unfortunately i cannot manage to get it done. The output image still has a white background.

For some other images with an alpha channel it is working:
![image](https://user-images.githubusercontent.com/58774145/115724525-4e9db880-a381-11eb-96e0-6892c3460a12.png)

**My Code:**
`        newFileName = `${newFileName}.png`
        console.time(newFileName);
        sharp(file)
            .resize({width: 3500, height: 3500, fit: "inside"})
            .withMetadata()
            .png({compressionLevel: 9})
            .toFile(newFileName)
            .then(() => {
                console.timeEnd(newFileName)
            });`

Thanks!

**Comment by lovell** [comment]
Please can you provide a sample input image that exhibits this behaviour.

**Comment by ContsultGmbH** [comment]
Hi, thanks for your quick reply.

https://drive.google.com/file/d/1dd3yitrt-8dCjnn_d1ukeI-EyOLsYwm7/view?usp=sharing

**Comment by lovell** [comment]
Thank you, this is a 3-channel TIFF without alpha transparency.

```
$ identify -verbose 0011215412_perspektive_2.tif 
Image: 0011215412_perspektive_2.tif
  Format: TIFF (Tagged Image File Format)
  Geometry: 2682x3312
  Class: DirectClass
  Type: true color
  Depth: 8 bits-per-pixel component
  Channel Depths:
    Red:      8 bits
    Green:    8 bits
    Blue:     8 bits
  Channel Statistics:
    Red:
      Minimum:                     0.00 (0.0000)
      Maximum:                 65535.00 (1.0000)
      Mean:                    44092.35 (0.6728)
      Standard Deviation:      24074.22 (0.3673)
    Green:
      Minimum:                     0.00 (0.0000)
      Maximum:                 65535.00 (1.0000)
      Mean:                    46612.19 (0.7113)
      Standard Deviation:      24439.37 (0.3729)
    Blue:
      Minimum:                     0.00 (0.0000)
      Maximum:                 65535.00 (1.0000)
      Mean:                    42534.78 (0.6490)
      Standard Deviation:      24615.20 (0.3756)
  Resolution: 300x300 pixels/inch
  Filesize: 50.0Mi
  Interlace: No
  Orientation: TopLeft
  Background Color: white
  Border Color: #DFDFDF
  Matte Color: #BDBDBD
  Page geometry: 2682x3312+0+0
  Compose: Over
  Dispose: Undefined
  Iterations: 0
  Compression: Zip
  Artist: REV Ritter GmbH
  Copyright: REV Ritter GmbH
  Timestamp: 2021:04:21 14:41:32
  Make: Canon
  Model: Canon EOS 7D
  Software: Adobe Photoshop 22.0 (Windows)
  Signature: 7e5c3750c02c9347abfb67b343a6d52051f53173ac98997288c50a4ce716d87b
  Profile-color: 560 bytes
  Profile-iptc: 12724 bytes
    unknown:
  ��
  Profile-XMP: 16707 bytes
  Tainted: False
  User Time: 0.210u
  Elapsed Time: 0m:0.198964s
  Pixels Per Second: 42.6Mi
```
I think the IPTC metadata might contain a mask in a proprietary Photoshop format, but that's not part of the TIFF standard.

**Comment by ContsultGmbH** [comment]
Thank you very much!
