### ISSUE TITLE
Rotate() not rotating image.

### ISSUE THREAD

**Issue by davidmdm** [lovell/sharp#2671]
I am trying to have rotate() rotate the image based on existing EXIF data.

I am taking an image, rotating it with the library withMetadata, and then trying to rotate it back to what it was originally but this does not happen.

Here is a simple version of the code I am running:

```typescript
import sharp from 'sharp';
import fs from 'fs';
import util from 'util';
import stream from 'stream';

const pipe = util.promisify(stream.pipeline);

(async function () {
  await pipe(sharp('original.jpg').withMetadata().rotate(90), fs.createWriteStream('rotated.jpg'));
  await pipe(sharp('rotated.jpg').rotate(), fs.createWriteStream('output.jpg'));
})();
```

Why is the output.jpg the same as the rotated image and not the same as the original image?
thanks.

**Comment by lovell** [comment]
Hi, did you see https://sharp.pixelplumbing.com/api-operation#rotate ?

> The use of `rotate` implies the removal of the EXIF `Orientation` tag, if any.

**Comment by davidmdm** [comment]
`Rotate the output image by either an explicit angle or auto-orient based on the EXIF Orientation tag.`

`If no angle is provided, it is determined from the EXIF data. `

My assumption was that I was taking a photo without EXIF data ad by calling withMetadata().rotate(90), It would rotate the image and write EXIF data. That seems to be the case from what I can tell.

When I try to call rotate() with no argument, I expected it to `auto-orient` it back, It seems to do nothing other than strip the EXIF data and leave the image rotated by 90 Degrees.

Am I mis-reading the docs?
Thanks

**Comment by lovell** [comment]
To explicitly set the output EXIF Orientation of a rotated input image, provide an `orientation` value to `withMetadata`.
```js
.withMetadata({ orientation: ? })
```
https://sharp.pixelplumbing.com/api-output#withmetadata
