### ISSUE TITLE
When to use `.end()` and `.destroy()`?

### ISSUE THREAD

**Issue by SuricateCan** [lovell/sharp#2676]
I want to know if I need to call the `.end()` or `.destroy()` api after I'm done processing an image.
In my current scenario, I'm rotating an image, converting to jpeg and extracting a buffer like below:

```typescript
  const img = sharp(buffer, { failOnError: false });
  const result = await img.rotate().jpeg().toBuffer();
  return result;
```

The buffer is used to send the image to a cloud storage.
So, my question is, do I need to call any of the mentioned api to free resources?

```typescript
  const img = sharp(buffer, { failOnError: false });
  const result = await img.rotate().jpeg().toBuffer();

  //img.end(); //do I need this?
  //img.destroy(); //or even this?

  return result;
```

If not, when should I use `.end()` or `.destroy()`? Should I even use it at all?

**Comment by lovell** [comment]
You won't need to use those methods, they exist as a `sharp` instance implements [Transform](https://nodejs.org/api/stream.html#stream_class_stream_transform) for Stream-based I/O.

**Comment by SuricateCan** [comment]
Thanks for the reply, @lovell
