### ISSUE TITLE
Color conversion at every saved - how to disable

### ISSUE THREAD

**Issue by tars-mj** [lovell/sharp#2677]
Hello
I am creating a printing tool and I have a color problem. When I convert a file several times through the sharp library, it recalculates the colors every time even though there is the same color space and the same profile: Fogra39. Anyway, no matter what the profile is there, because even if I give any other profile, the effect is similar. Here is the original file, then saved the third time and finally the fifth time:

![v_1](https://user-images.githubusercontent.com/8572999/115925293-3319d700-a481-11eb-8083-66b5188ee1da.png)

![v_3](https://user-images.githubusercontent.com/8572999/115925317-3dd46c00-a481-11eb-9685-e1b32e2f1f10.png)

![v_5](https://user-images.githubusercontent.com/8572999/115925342-45941080-a481-11eb-94cc-209ef676830d.png)

My question is, is there any way to use sharp in such a way that it does not interfere with the colors when opening and saving? it's like opening and saving one file in Photoshop every time and there are different colors every time. 

Sharp perfectly fits my project needs, the only problem is the colors :)

_Originally posted by @tars-mj in https://github.com/lovell/sharp/issues/1323#issuecomment-825896212_

**Comment by lovell** [comment]
Please subscribe to future possible enhancement #1317 that relates to processing in a wider gamut.
