### ISSUE TITLE
'darwin-arm64v8' binaries cannot be used on the 'darwin-x64' platform

### ISSUE THREAD

**Issue by codin-play** [lovell/sharp#2678]
I have been running into issues getting this module to run and done countless uninstall / reinstall of npm, dependencies, etc. It appears the libvips downloads the `darwin-arm64v8.tar`. I would expect this version to be correct based on the version of everything but not sure why the platform reads as darwin-x64. Any thoughts here?

Diagnostics:

```
System:
    OS: macOS 11.2.3
    CPU: (8) arm64 Apple M1
    Memory: 3.34 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
    npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman

Node:::
mars@mars functions % nvm use 12
Now using node v12.22.1 (npm v6.14.12)

node -p 'process.arch'
arm64

Python:::

mars@mars functions % file $(which python)
/usr/bin/python: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/usr/bin/python (for architecture x86_64):      Mach-O 64-bit executable x86_64
/usr/bin/python (for architecture arm64e):      Mach-O 64-bit executable arm64e

npm view sharp dist-tags.latest
0.28.1

```

Install of latest version on Mac M1:

```
mars@mars functions % npm install              

> sharp@0.28.1 install /Users/mars/Desktop/Engineering/_tmp/functions/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.6/libvips-8.10.6-darwin-arm64v8.tar.br
prebuild-install WARN install No prebuilt binaries found (target=3 runtime=napi arch=arm64 libc= platform=darwin)
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  LIBTOOL-STATIC Release/nothing.a
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  CXX(target) Release/obj.target/sharp/src/sharp.o
  SOLINK_MODULE(target) Release/sharp.node
...
```

Error Response when attempting to run :

```
Error: 'darwin-arm64v8' binaries cannot be used on the 'darwin-x64' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'darwin-x64' platform.
    at Object.hasVendoredLibvips (/Users/mars/Desktop/Engineering/_Play/PlayFirebaseBackend/functions/node_modules/sharp/lib/libvips.js:80:13)
    at Object.<anonymous> (/Users/mars/Desktop/Engineering/_Play/PlayFirebaseBackend/functions/node_modules/sharp/lib/constructor.js:7:22)
    at Module._compile (internal/modules/cjs/loader.js:1136:30)
    at Module._compile (pkg/prelude/bootstrap.js:1394:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10)
    at Module.load (internal/modules/cjs/loader.js:984:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1024:19)
    at Module.require (pkg/prelude/bootstrap.js:1338:31)
    at require (internal/modules/cjs/helpers.js:72:18)
```

**Comment by codin-play** [comment]
Ok I figured this out and wanted to leave a comment for folks who have been banging their head against a wall.

SUMMARY:

With my new Mac/M1 I have installed node via `nvm`. When running via console to determine the architecture it printed what I expected it should be:
```
node -p 'process.arch'
arm64
```

But the conflict was when the dependency was running/ installed. To overcome this I resulted in installing node as x64 rather than the arm64. This seemed to correct my dependency woes:

1. Start a new iTerm console and change the terminals architecture version to `arch -x86_64 zsh`
2. Uninstall / reinstall node version 12 `nvm uninstall 12 && nvm install 12`. Now see the architecture version of x64 `node -p 'process.arch'` === `x64`
3. Reinstall dependencies `rm -rf node_modules && npm install`

**Comment by ColinRosati** [comment]
> Ok I figured this out and wanted to leave a comment for folks who have been banging their head against a wall.
> 
> SUMMARY:
> 
> With my new Mac/M1 I have installed node via `nvm`. When running via console to determine the architecture it printed what I expected it should be:
> 
> ```
> node -p 'process.arch'
> arm64
> ```
> 
> But the conflict was when the dependency was running/ installed. To overcome this I resulted in installing node as x64 rather than the arm64. This seemed to correct my dependency woes:
> 
> 1. Start a new iTerm console and change the terminals architecture version to `arch -x86_64 zsh`
> 2. Uninstall / reinstall node version 12 `nvm uninstall 12 && nvm install 12`. Now see the architecture version of x64 `node -p 'process.arch'` === `x64`
> 3. Reinstall dependencies `rm -rf node_modules && npm install`

**This worked for me!** 

```
 System:
    OS: macOS 12.3.1
    CPU: (8) x64 Apple M1 Pro
    Memory: 2.26 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
```

**Comment by ali-sajjad-rizavi** [comment]
Related StackOverflow link https://stackoverflow.com/questions/68814180/darwin-arm64v8-binaries-cannot-be-used-on-the-darwin-x64-platform/68814181

**Comment by shyaaam** [comment]
I was using node v18, so i installed node14 using `nvm install 14` and then `rm -rf node_modules`, reinstalled the packages, then the problem went away. 
In my case, i was using nx library and trying to run command "`nx serve myapp`" when the error had occured.
