### ISSUE TITLE
Removing transparency, with color

### ISSUE THREAD

**Issue by ile** [lovell/sharp#2679]
Hello!

First, the example [here](https://sharp.pixelplumbing.com/api-operation#flatten) doesn't seem to be right: 

I think `.flatten('#F0A703')` should be `.flatten({ background: '#F0A703' })`, right?

Also, a suggestion: this flatten() function was a bit difficult to find. How about putting this same option in `removeAlpha()`?

Using sharp@0.28.1.

**Comment by lovell** [comment]
Hi, the docs were recently fixed via https://github.com/lovell/sharp/pull/2654 and will be updated with the next release.

There's a difference between `flatten`, which merges pixel values with the alpha channel, and `removeAlpha` that simply removes it. We could add a link between the docs for the two operations to help people who've found one then find the other.

**Comment by lovell** [comment]
Commit https://github.com/lovell/sharp/commit/1b4d1521e0d7ace47fab304d42f628254aa180df adds cross-links to the docs between these two operations.
