### ISSUE TITLE
osx: how to use the mozjpeg methods?

### ISSUE THREAD

**Issue by privatmamtora** [lovell/sharp#268]
`trellisQuantisation()` / `trellisQuantization()`
`overshootDeringing()`
`optimiseScans()` / `optimizeScans()`

Every time I try to use these options I get the following message
`vips warning: vips2jpeg: Ignoring trellis_quant` (Similar for the other operations)

How exactly are these methods use?

**Comment by lovell** [comment]
Hello, as you'll probably have seen in the [docs](http://sharp.dimens.io/en/stable/api/#trellisquantisation-trellisquantization), these features require "libvips 8.0.0+ compiled against mozjpeg 3.0+".

You'll need to remove any existing vips installation before installing `mozjpeg` (via [homebrew](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/mozjpeg.rb)?). You can then install vips, telling it where you installed mozjpeg via its `--with-jpeg-includes` and `--with-jpeg-libraries` [configure-time flags](https://github.com/jcupitt/libvips#optional-dependencies).

Good luck!

**Comment by privatmamtora** [comment]
Alright that works.
I also added a `--with-mozjpeg`option to the brew.

**Comment by lovell** [comment]
Good news - looks like https://github.com/Homebrew/homebrew-science/pull/2740 is what you're referring to.
/cc @jcupitt

**Comment by lovell** [comment]
Closing as the homebrew patch has landed - feel free to re-open if there are still problems. Thanks!

**Comment by ram-you** [comment]
Hi,
I may be missing something, but I installed  **mozjpeg** via this link: http://mozjpeg.codelove.de/binaries.html

then I did: `curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | sudo bash -s -- --with-openslide --with-jpeg-includes=/opt/mozjpeg/include --with-jpeg-libraries=/opt/mozjpeg/lib64 --with-mozjpeg=/opt/mozjpeg/bin
`
but still have the warning : `vips warning: vips2jpeg: Ignoring trellis_quant` and same warnings for others:
_overshootDeringing()
optimiseScans() / optimizeScans()_

Can someone help please ?
Thank you.

**Comment by lovell** [comment]
@ram-you I assume this is on Linux (rather than the OS X discussed previously).

The (deprecated) preinstall script won't help here, or at least doesn't know about the flags you're trying to pass to it.

You'll need to manually run the steps to install libvips, passing your `--with-jpeg-includes` and `--with-jpeg-libraries` options to its `./configure` stage.

**Comment by ram-you** [comment]
Thank you @lovell . Yes I'm on Linux (ubuntu 14.04)
I'll make a try and will inform you.

**Comment by ram-you** [comment]
Now I start having a new problem : 

> Error: libjpeg.so.62: cannot open shared object file: No such file or directory

**Comment by ram-you** [comment]
> As of v0.12.0, sharp no longer has any external runtime dependencies for Linux and Windows users as it bundles a pre-compiled version of libvips. 

My question is why the pre-compiled version of libvips is not compiled against mozjpeg or as an option ?

**Comment by lovell** [comment]
> "libjpeg.so.62: cannot open shared object file"

This looks like a runtime problem, in that you need to tell it where the shared libraries you've compiled and linked against are. Perhaps set `LD_LIBRARY_PATH=/opt/mozjpeg/lib64`. Please open a new issue if you can't get this working.

> "why the pre-compiled version of libvips is not compiled against mozjpeg"

The pre-compiled version is provided to get people going as fast as possible with the most popular web-based formats. I don't intend to offer any optional nature to these as the support overhead will be too high.

sharp will always look for a global installation of libvips first so you will always be able roll your own combination of libvips' dependencies :)
