### ISSUE TITLE
Watermark Animated Gif

### ISSUE THREAD

**Issue by jeffweinberg** [lovell/sharp#2680]
**What are you trying to achieve?**

I am trying to add a watermark (overlay) to an animated gif. If I composite a base animated gif with a png, the png only shows for one frame. The same is true if I composite an animated gif base, with the overlay in the form of an animated gif with the same number of frames....it only shows for one frame. 

No matter how many frames the base animated gif is, the overlay only shows for 1 frame.

**Have you searched for similar questions?**

Yes

**Are you able to provide a minimal, standalone code sample that demonstrates this question?**

```
const baseGIF =
"pathToGIF/file.gif";

const overlay = [
  {
    input:
    "pathToOverlay/overlay.png", // also tried with gif overlay
  },
];

sharp(baseGIF, { animated: true })
.composite(overlay)
.toFile("output.gif", (err) => {
  if (err) {
    console.log("error: ", err);
  }
});
```

**Are you able to provide a sample image that helps explain the question?**

BASE (2 frames):
![tiedye-background](https://user-images.githubusercontent.com/75695113/116261701-e61a5700-a745-11eb-8f9f-6fb598754859.gif)

OVERLAY:
![test-overlay](https://user-images.githubusercontent.com/75695113/116262035-35f91e00-a746-11eb-8844-104a89747d9b.png)

OUTPUT (with single png):
![0](https://user-images.githubusercontent.com/75695113/116262273-6476f900-a746-11eb-92d2-a87f6a4f1f32.gif)

OUTPUT (with 2 frame gif overlay):
![0](https://user-images.githubusercontent.com/75695113/116262968-fc74e280-a746-11eb-8344-16ce8997ea57.gif)

**Comment by jeffweinberg** [comment]
Follow-up:
I have been able to achieve this by moving the overlay part of my processing pipeline to gm and automating with node. The command looks like the following, is there anyway to achieve the same with sharp?

`gm convert <background animated-gif path> -coalesce null: <overlay path> -layers composite <output path>
`

**Comment by lovell** [comment]
Perhaps try setting `tile: true` to ensure the overlay is repeated, a bit like the following (untested):
```diff
 const overlay = [
   {
     input:
     "pathToOverlay/overlay.png", // also tried with gif overlay
+    tile: true
   },
 ];
```
https://sharp.pixelplumbing.com/api-composite

**Comment by jeffweinberg** [comment]
@lovell - this worked! Thank you for your help, much appreciated!

**Comment by jeffweinberg** [comment]
@lovell - one more question about this...is it possible to composite two animated gifs together? Again, this works using the following gm command, but not with the sharp code I posted earlier using `tile: true` (or `tile: false`):

`gm convert <background animated-gif path> -coalesce null: <overlay animated-gif path> -layers composite <output path>`

**Comment by lovell** [comment]
Please subscribe to #1580 for a future possible enhancement that might help.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by eb-so** [comment]
@lovell Changing  `tile: true` repeated the overlay to cover all of the screen
I think it worked for @jeffweinberg Because his overlay was as big as his original gif but mine is a small png image 

Here is the output 
https://github.com/lovell/sharp/assets/89080323/89884574-efa0-4a60-bc14-ec20a5e19d24
