### ISSUE TITLE
site search does not work https://sharp.pixelplumbing.com/

### ISSUE THREAD

**Issue by nadalfederer** [lovell/sharp#2686]
Search is not working on the website.
![download (2)](https://user-images.githubusercontent.com/6043510/116624350-77f5b000-a950-11eb-9bae-ec3e3e2fc767.png)

**Comment by lovell** [comment]
This is a keyword auto-suggest rather than full-blown search engine.

I'll assume you were not seriously expecting a meaningful response from "dsghfsdhdf", but was there a particular word or phrase you tried searching for that did not suggest anything where you would expect it to?

**Comment by nadalfederer** [comment]
Oh, I see it only works for commands search like "tiff". I was looking for the word "text" to be able to insert a text in an image. I found the answer on Github.

**Comment by lovell** [comment]
The work to implement the future possible enhancement at https://github.com/lovell/sharp/issues/512 should hopefully mean the keyword "text" will then be indexed and therefore relevant result(s) displayed.
