### ISSUE TITLE
can you auto-crop socument images with sharp.trim?

### ISSUE THREAD

**Issue by benayat** [lovell/sharp#2689]
What are you trying to achieve?
I want to auto-crop receipt pictures, and remove the surroundings of the document, so only the receipt(or any document inside a picture) remains.

Have you searched for similar questions?
I didn't find any solution not involving building a machine learning model to identify edges...etc.

Are you able to provide a minimal, standalone code sample that demonstrates this question?
not relevant.

Are you able to provide a sample image that helps explain the question?
![23](https://user-images.githubusercontent.com/23525835/116828693-f51b6200-aba8-11eb-8275-87cb03643231.jpg)

**Comment by lovell** [comment]
Using `.trim(200)` produces the following output:

![](https://user-images.githubusercontent.com/210965/116915200-a2db4f00-ac43-11eb-8537-314c73ea9c71.jpg)

If you're planning to use OCR then try threshold too, e.g. `.trim(200).threshold()` produces the following output:

![](https://user-images.githubusercontent.com/210965/116915440-eb930800-ac43-11eb-832c-d96d8f44b1e1.png)

https://sharp.pixelplumbing.com/api-resize#trim
https://sharp.pixelplumbing.com/api-operation#threshold

**Comment by benayat** [comment]
Thanks alot for the fast reply!
That's more than enough for OCR, it gives me fantastic results with
tesseract.
but the problem arises when I want to have some formula to fit all the
receipts programmatically, without knowing the size of the receipt inside
the image by pixels.
worst case, maybe I'll just combine the two methods, find the
dimensions with ML and use this trim afterwards.
I just wanted to say thanks, sharp works unbelievably fast, way better than
all alternatives.

 Benaya

‫בתאריך יום ב׳, 3 במאי 2021 ב-21:16 מאת ‪Lovell Fuller‬‏ <‪
***@***.***‬‏>:‬

**Comment by lovell** [comment]
Please note that in the example I provided, the 200 in `trim(200)` is a threshold for the value/colour and is _not_ a pixel count, so is already relative to the contents of each input (you'll need to experiment to discover the best threshold for a given set of inputs.)
