### ISSUE TITLE
Empty file left over on resize failure

### ISSUE THREAD

**Issue by cassieramen** [lovell/sharp#269]
This seems to only happen whenever an error occurs. An empty file with name magick-{random-string} (i.e. magick-ruqEgyfV, magick-DnUbdl4w) is left over in the root of our project directory.

```js
  //The transform stream
  var transformer = sharp()
    .withoutEnlargement() //never enlarge the image
    .withMetadata()
    .resize(options.width, options.height)
    .quality(options.quality)
    .toFormat(options.format);

  transformer
    .on('error', function(e) {
      logger.error({
        err: "Failed to resize image",
        error: e,
        options: options
      });
    });

  readStream.pipe(transformer).pipe(writeStream);
```

I'm triggering the error by sending a pdf through. We're using sharp 11.3 and installing vips from your setup script https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh

Any help is appreciated, thanks!

**Comment by lovell** [comment]
Hello, libvips processes PDF inputs via Imagemagick, which can create temporary files when the resultant image is too big to fit in memory.

It looks like the lack of deletion you've discovered is a known problem, e.g. http://www.imagemagick.org/discourse-server/viewtopic.php?t=15960 and http://stackoverflow.com/questions/11875046/imagemagick-doesnt-delete-tmp-files

The advice seems to be that if you set one of `TMPDIR`, `MAGICK_TMPDIR` or `MAGICK_TEMPORARY_PATH` environment variables to point to a separate directory, you can then have some form of regular task (cron?) remove the files within.

The fact these files exist in the first place may point to an underlying problem, which in my experience of Imagemagick is most likely a lack of memory.

**Comment by lovell** [comment]
@cassieramen were you able to make any progress with this?

**Comment by cassieramen** [comment]
Sorry! Yes, this was extremely helpful. We have mostly been working to reduce our memory usage elsewhere in our image processing service. It is a rare that we're asked to process a PDF and this only leaves behind tiny empty files. Instead of piping to a directory, we have it running in a container that we can just kill off if this gets out of hand.

**Comment by lovell** [comment]
Great, glad to hear you got it working. If you're able to share details publicly there's a usage survey at #35 - good luck!
