### ISSUE TITLE
Resize Animated GIF to WEBP - Error: vips2webp: unable to encode

### ISSUE THREAD

**Issue by pingustar** [lovell/sharp#2690]
Version: `sharp@0.28.1`

```typescript
const response = await fetch(`https://ipfs.atomichub.io/ipfs/${ipfsHash}`);
const buffer = await response.buffer();

try {
    await sharp(buffer, { animated: true })
    .resize(width, height)
    .toFile(`./ipfs/${ipfsHash}.webp`);
} catch (e) {
    console.log(e);
}
```

**Error encountered:**
`Error: vips2webp: unable to encode`

**Expected behaviour:**
Convert animated GIF to animated WEBP image.

**Alternative options tried:**
Using `pages: -1` instead of `animated: true` leads to the same error.

**Sample image:**
https://ipfs.atomichub.io/ipfs/QmNWwPSTynhoGx6UR4SKZwykp5uEUhLq5mQ3dt9jtmVeh2

**Output of running `npx envinfo --binaries --system`?**
```bash
npx: installed 1 in 0.922s

  System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 25.84 GB / 64.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.0/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
```

**Comment by lovell** [comment]
What are the values of `width` and `height` for the sample image?

**Comment by pingustar** [comment]
@lovell 

`width`: 700
`height`: undefined

**Comment by lovell** [comment]
If you're resizing a multi-page image then you'll need to update the output with the new page height, in this example 700.
```js
.webp({ pageHeight: 700 })
```
https://sharp.pixelplumbing.com/api-output#webp

Please see #2275 for a future possible enhancement that relates to this.

**Comment by pingustar** [comment]
> If you're resizing a multi-page image then you'll need to update the output with the new page height, in this example 700.
> 
> ```js
> .webp({ pageHeight: 700 })
> ```
> 
> https://sharp.pixelplumbing.com/api-output#webp
> 
> Please see #2275 for a future possible enhancement that relates to this.

the above + `.resize(width, height * pages)`resolved my problem!!

Thank you very much!
