### ISSUE TITLE
ERROR: https://dl.bintray.com/lovell/sharp/libvips-8.3.3-linux-x64.tar.gz status code 403

### ISSUE THREAD

**Issue by rkhedekar** [lovell/sharp#2694]
Hi Suddenly started getting this error while trying to deploy new build on production env.

> sharp@0.16.2 install /home/circleci/GROW/node_modules/sharp
> node-gyp rebuild

ERROR: https://dl.bintray.com/lovell/sharp/libvips-8.3.3-linux-x64.tar.gz status code 403
gyp: Call to 'LDD_VERSION="ldd (Debian GLIBC 2.24-11+deb9u4) 2.24
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper." node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.15.0-1092-aws
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/circleci/GROW/node_modules/sharp
gyp ERR! node -v v6.17.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

Please help...

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/2574
