### ISSUE TITLE
AVIF lossless is not accurate

### ISSUE THREAD

**Issue by tomByrer** [lovell/sharp#2696]
> Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

v0.28.1

> What are the steps to reproduce?

`.avif({ quality:50, speed:2, lossless:true })`

> What is the expected behavior?

The diff to be equal to source .png

> Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

I'm not sure if you want my entire testing program copy/pasted here? (I use sharp to diff ;) )

> Are you able to provide a sample image that helps explain the problem?

src **.png**: (note: highly lossless compressed via FileOptimizer)
![_gray-7f7f7f](https://user-images.githubusercontent.com/1308419/117244985-a582a380-adff-11eb-9e10-9e9cc14e11cc.png)

sharp lossless CPU2 (note: file is really AVIF, but added .png at end to hack, urr I mean upload here)
![_gray-7f7f7f  avif](https://user-images.githubusercontent.com/1308419/117245861-2aba8800-ae01-11eb-9aee-546a4409d0ad.png)

diff:
![_gray-7f7f7f png__gray-7f7f7f avif diffnote](https://user-images.githubusercontent.com/1308419/117246001-66ede880-ae01-11eb-8536-6f99dc973725.png)

diff with the low levels increased to see artifacts easier; note the blocks of red, blue, & green show lossless shifts more than edges:
![_gray-7f7f7f png__gray-7f7f7f avif diffampnote](https://user-images.githubusercontent.com/1308419/117246053-8258f380-ae01-11eb-8852-8a18665d5d4f.png)

*avif.to* is much closer, though a few blocks & some edges still are not perfect:
![_gray-7f7f7f png__gray-7f7f7f avif diffampnote](https://user-images.githubusercontent.com/1308419/117246328-0dd28480-ae02-11eb-991b-efcfda5a522f.png)

*[squoosh.app](https://github.com/GoogleChromeLabs/squoosh/tree/dev/codecs/avif/enc)* has truelly perfect lossless.  Uses libavif also, but unsure how they encode lossless.  Diff would be blank (useless), so here is their AVIF lossless output:
![_gray-7f7f7f avif](https://user-images.githubusercontent.com/1308419/117247778-83d7eb00-ae04-11eb-969c-c3062513845c.png)

> What is the output of running `npx envinfo --binaries --system`?

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 2.28 GB / 31.85 GB
  Binaries:
    Node: 16.0.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.1 - C:\p\n\yarn\bin\yarn.CMD
    npm: 7.10.0 - C:\Program Files\nodejs\npm.CMD
    
  Thanks for your interest & sharp!

**Comment by hdmr14** [comment]
same here

**Comment by lovell** [comment]
Hi, this looks like the effects of chroma subsampling - please see #2562

**Comment by snapied** [comment]
Same here
