### ISSUE TITLE
Error: extract_area: bad extract area if display not main display in Windows

### ISSUE THREAD

**Issue by samarth-bola** [lovell/sharp#2698]
Hello. 

**Issue**: On a windows machine, when I am working with 2 displays, when I try to `extract` and then save `toBuffer` on a display which is not the main display, I get the following error: `Error: extract_area: bad extract area` . However, the same code works perfectly fine if I make that display as my main display.

**Expected Behavior**: I want to be able to `extract` and save `toBuffer` on a display which is not the main display.

**Sample Code**

```
    let bounds = { x: 2496, y: 25, width: 968, height: 702 }
    const cropped = await sharp(screenshotImg);
    const metadata = await cropped.metadata();
    const height = Math.min(metadata.height,bounds.height);
    const width = Math.min(metadata.width, bounds.width);
    const left = Math.max(0, bounds.x);
    const top = Math.max(0, bounds.y);
    const result = cropped.extract({ left: left, top: top, width, height });
    const bufferResult = await result.toBuffer();  // This line gives Error: extract_area: bad extract area
    return sharp(bufferResult, { height, width, channels: 3 });
```
I checked that the extraction bounds are within the limits of the image that I am trying to extract from. 

Any help is appreciated. Please let me know if you require more info. Thanks

**Comment by lovell** [comment]
Please can you provide a sample input image that fails in this manner. Based on the sample code provided it should be at least 3464x727 in dimensions.

**Comment by samarth-bola** [comment]
> Please can you provide a sample input image that fails in this manner. Based on the sample code provided it should be at least 3464x727 in dimensions.

The input image is the screenshot of the display screen (resolution: 1200x1920) in .png format. So the dimensions of the input image is 1200x1920. That would be the same if its the main display or the secondary display.

**Comment by lovell** [comment]
> I checked that the extraction bounds are within the limits of the image that I am trying to extract from.

The value of `left` in the code above will be 2496, which is already out of bounds for a 1200px wide image.

Perhaps you could provide a sample repo with code and images that allows someone else to reproduce this.

**Comment by samarth-bola** [comment]
> > I checked that the extraction bounds are within the limits of the image that I am trying to extract from.
> 
> The value of `left` in the code above will be 2496, which is already out of bounds for a 1200px wide image.
> 
> Perhaps you could provide a sample repo with code and images that allows someone else to reproduce this.

The value of `left` was definitely the issue. It was out of bounds which was giving the error in the first place. Thanks a bunch for pointing it out.
