### ISSUE TITLE
PNG-input to jpeg-output results in blank image

### ISSUE THREAD

**Issue by flash1293** [lovell/sharp#270]
Hi, I'm reading a png-image (
![badges_android_tools_stage1](https://cloud.githubusercontent.com/assets/1508364/9967182/4a7e1424-5e41-11e5-90ae-03ba656508f3.png)
), resize it and save it as a webp-image. Later I read back the webp-image and output it to a jpeg-image (
![output](https://cloud.githubusercontent.com/assets/1508364/9967186/50da5b34-5e41-11e5-93a8-b8eb37233ece.jpeg)
), but the jpeg-image is just a bit of black and white (i think it's only the alpha-channel or something like this).
Here is the code:
```
sharp(pngData)
    .resize(1440).webp().toBuffer(function(err, buffer) { /*save webp to disk*/
 });

//later
sharp(dataFromDisk)
    .quality(75).jpeg().toBuffer(function(err, buffer) { /*save jpeg to disk*/
 });
```

The webp-image is fine by the way. How can i configure the tool correctly to output not the alpha-channel but the color-channels?

**Comment by lovell** [comment]
Hello, this is probably related to #249. If so, you can add `flatten()` to your processing chain to remove the alpha channel as a workaround until libvips 8.1.0 is released in a couple of weeks.

**Comment by flash1293** [comment]
Works perfectly, thanks a lot for the fast support :-)
