### ISSUE TITLE
Rotate and then composite a large image => Error: Input image exceeds pixel limit

### ISSUE THREAD

**Issue by velsa** [lovell/sharp#2701]
> Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

Yes:
```
> npm view sharp dist-tags.latest
0.28.1
> npm ls sharp
sharp@0.28.1
```

> What are the steps to reproduce?
```
import { exec } from "child_process";
import sharp from "sharp";

const [width, height] = [16000, 16000];
const [xlWidth, xlHeight] = [25000, 25000];

(async () => {
  const compositeImg = await sharp({
    create: {
      background: "red",
      channels: 4,
      width,
      height,
    },
  })
    .toFormat("png")
    .toBuffer({ resolveWithObject: true });
  console.log("compositeImg", compositeImg.info);

  const rotatedImg = await sharp({
    create: {
      background: "green",
      channels: 4,
      width,
      height,
    },
  })
    .rotate(36)
    .toFormat("png")
    .toBuffer({ resolveWithObject: true });
  console.log("rotatedImg", rotatedImg.info);

  await sharp(compositeImg.data, { limitInputPixels: false })
    .resize(xlWidth, xlHeight, { fit: "contain", background: "black" })
    .composite([{ input: rotatedImg.data }])
    .toFile("/tmp/test.png");

  exec("open /tmp/test.png");
})();
```

The error is:
```
(node:57925) UnhandledPromiseRejectionWarning: Error: Input image exceeds pixel limit
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32
```

I also tried running node with increased memory heap size:

```
node --max_old_space_size=4096 -r ts-node/register --trace-warnings ./src/sharp-error.ts
```

> What is the expected behaviour?

I want to be able to rotate a 16000x16000 image and then make a composite of that rotated image with another 16000x16000 image and do it a number of times. Obviously, when the rotation is modulo 90 degrees – everything works fine, but when I use any other angle, the rotated image size (~22k x 22k) prevents the composite from working and throws an error.

> Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

Above 

> Are you able to provide a sample image that helps explain the problem?

The error happens with both image of the 16kx16k or when using `create: {...}`

> What is the output of running `npx envinfo --binaries --system`?

```
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 472.77 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    npm: 7.11.2 - ~/.nvm/versions/node/v14.16.1/bin/npm
```

**Comment by lovell** [comment]
You'll probably need to set `limitInputPixels` on the image to composite as well if it will exceed the safety limits, something like:

```diff
-  .composite([{ input: rotatedImg.data }])
+  .composite([{ input: rotatedImg.data, limitInputPixels: false }])
```

**Comment by velsa** [comment]
Since I'm using Typescript, it won't allow me to use `limitInputPixels: false`, since it's not part of the `OverlayOptions` interface. But when I added it to `@types/sharp/index.ts`, everything worked fine ) 

Will test it with my main app now.
Thanks a lot!

**Comment by velsa** [comment]
And there's an issue with `create`, it seems I can't use `limitInputPixels` there and it crashes with the same error when I specify the size of 25k x 25k

```
  let compositeShot = await sharp({
    create: {
      background: "white",
      channels: 4,
      width: 25000,
      height: 25000,
      limitInputPixels: false,
    },
  })
    .toFormat("png")
    .toBuffer();
```

**Comment by lovell** [comment]
Please try the following:
```diff
  let compositeShot = await sharp({
    create: {
      background: "white",
      channels: 4,
      width: 25000,
      height: 25000,
-     limitInputPixels: false,
    },
+   limitInputPixels: false,
  })
```
(A lack of error handling in this example code is causing the crash, not sharp.)

**Comment by velsa** [comment]
Thanks, it seems to work now.
Just wasn't obvious where to put limitInputPixels in each case )

**Comment by lovell** [comment]
Great, thanks for confirming. If you're able to submit a PR to the DefinitelyTyped repo to update the TypeScript definitions that would be useful for the next person who runs into this.

I'll leave this open as a reminder to add `limitInputPixels` to the [composite](https://sharp.pixelplumbing.com/api-composite) docs.

**Comment by lovell** [comment]
Docs updated via commit https://github.com/lovell/sharp/commit/81e388a4cc913c7c67a40df08580752a6c2a5e41
