### ISSUE TITLE
Uncaught Error: Cannot find module Util

### ISSUE THREAD

**Issue by samgermain** [lovell/sharp#2702]
I get this error when running sharp

```
constructor.js:3 Uncaught Error: Cannot find module 'util'
    at webpackMissingModule (constructor.js:3)
    at Object../node_modules/sharp/lib/constructor.js (constructor.js:3)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
    at Object../node_modules/sharp/lib/index.js (index.js:3)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
    at Module../src/utils/sharpImage.js (sharpImage.js:1)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
 ```
    
   Webpack version
   
```
    "webpack": "^5.10.0",
    "webpack-cli": "^4.2.0",
    "webpack-dev-server": "^3.11.0"

**Comment by lovell** [comment]
Hi, this module requires a Node.js runtime. It will not work in a client-side browser.

**Comment by samgermain** [comment]
@lovell Is there a basic Hellow World type example for this module?

**Comment by samgermain** [comment]
@lovell So how do you use the images produced from this module in a React project?

Is there a method using webpack?

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/install#webpack

If you're still having problems, perhaps you could create a standalone repo with sample code, images and dependencies that demonstrates what you're trying to achieve.

**Comment by samgermain** [comment]
@lovell [Here's a sandbox](https://codesandbox.io/s/holy-sun-5il46?file=/src/pages/Home.js) I would like to image too be optimized by sharp. How can I change the sandbox to do this

**Comment by lovell** [comment]
A search on npm for "[sharp webpack loader](https://www.npmjs.com/search?q=sharp%20webpack%20loader)" reveals https://www.npmjs.com/package/sharp-loader that might help.

(More general questions about React and Webpack are probably better suited to and are likely to get a quicker/better answer on a site such as StackOverflow.)

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
