### ISSUE TITLE
Converting to png from svg misses foreign objects

### ISSUE THREAD

**Issue by PAK90** [lovell/sharp#2705]
I'm using v0.28.1 and am trying to convert an svg with foreign objects into a png; the output I get is missing the text in the foreign objects. See the svg here: https://jsfiddle.net/rskjd2y8/, while the end result of the .png() is here:
![testpng](https://user-images.githubusercontent.com/1844422/117593936-4328ec00-b0fa-11eb-97d5-5eb3226c7158.png)

Svg is being generated and then passed into Sharp as follows:
```
sharp(Buffer.from(svg))
    .png()
    .toFile("testpng.png")
    .then(function (info) {
      console.log(info);
    })
    .catch(function (err) {
      console.log(err);
    });
```

Is it possible to export the foreign objects into png?

Output of `npx envinfo --binaries --system` is:
System:
    OS: macOS 11.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 346.28 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.16.1/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm

**Comment by lovell** [comment]
The SVG `foreignObject` element is unsupported by the underlying librsvg library. Given the use of embedded HTML in this example, a web browser would be a more appropriate rendering engine.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
