### ISSUE TITLE
Get the average color of the edge of an image

### ISSUE THREAD

**Issue by RubenVanEldik** [lovell/sharp#2708]
I am looking for a way to retrieve the average color at the edge of an image so I can [extend](https://sharp.pixelplumbing.com/api-resize#extend) the image with this color.

I have tried to search through the repo and issues, but I can't find anything. Is there any way to retrieve the average color of the edge of an image?

**Comment by lovell** [comment]
Perhaps use [extract](https://sharp.pixelplumbing.com/api-resize#extract) for a 1 pixel strip, e.g. the left edge:

```js
const { height } = await sharp(input).metadata();
const edge = await sharp(input).extract({ left: 0, top: 0, width: 1, height }).toBuffer();
```

You could then use [stats](https://sharp.pixelplumbing.com/api-input#stats) to get its average and/or dominant colours, something like (untested):

```js
const { channels, dominant } = await sharp(edge).stats();
// average
const [ r, g, b ] = channels.map(c => c.mean);
// dominant
const { r, g, b } = dominant;
```

**Comment by RubenVanEldik** [comment]
This is a great solution. I don't know why I hadn't thought of `extract` myself. 🙃 

Thank you Lovell!
