### ISSUE TITLE
Adding additional frames to webm animation?

### ISSUE THREAD

**Issue by justusbotlabsgg** [lovell/sharp#2709]
What are you trying to achieve?
Add a frame to the end of an existing webm animation clip. 

Have you searched for similar questions? Yes

Are you able to provide a minimal, standalone code sample that demonstrates this question?
No

Are you able to provide a sample image that helps explain the question? No

Not sure if this is possible but just something I'm currently trying to do.

**Comment by lovell** [comment]
WebM is a video container that uses the VP9 codec, so perhaps try ffmpeg - https://trac.ffmpeg.org/wiki/Encode/VP9

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
