### ISSUE TITLE
optimal way to omit alpha channel in output, SVG to PNG

### ISSUE THREAD

**Issue by cyrfer** [lovell/sharp#2711]
> What are you trying to achieve?

I want to convert SVG to PNG without an alpha channel in the result, as well as get an optimized rendering of the text.

I am successfully converting SVG to PNG files with code shown below. The problem is the result contains 4 channels, RGBA, rather than what I expect, which is 3 channels RGB.

The SVG will always be 2 tones, white text on black background.

What is the best way to omit the alpha channel in the output?
Can I describe the SVG input in a way that avoids the transparency?

Is `.resize()` the best way to render desired sizes? What is the impact on the text aliasing?

> Have you searched for similar questions?

Yes, it seems I can use operations like `.removeAlpha()` to prevent the output. Can this be optimized more?

Why is alpha added? Is the text causing the transparency?

Could I create a blank canvas of desired size and channels, and then composite the SVG onto it?

> Are you able to provide a minimal, standalone code sample that demonstrates this question?

```javascript
const fs = require('fs')
const sharp = require('sharp')

const metadata = {
  format: 'png',
  width: 1920,
  height: 1080,
}

const source = "<svg id=\"preview\" version=\"1.1\" baseProfile=\"full\" viewBox=\"0 0 1920 1080\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"> <style type=\"text/css\"> text { font-family: \"Roboto\", sans-serif } </style> <rect width=\"100%\" height=\"100%\" fill=\"black\" /> <text x=\"930\" y=\"370\" font-size=\"20\" text-anchor=\"end\" fill=\"white\">HELLO</text> <text x=\"990\" y=\"370\" font-size=\"20\" text-anchor=\"start\" fill=\"white\">WORLD</text> </svg>"

const bufferPromise = sharp(Buffer.from(source))
    //.removeAlpha()
  .resize(metadata.width, metadata.height)
  .toFormat(metadata.format)
  .toBuffer()

bufferPromise.then(buffer => {
    fs.writeFileSync(`./out.${metadata.format}`, buffer)
})
```

> Are you able to provide a sample image that helps explain the question?

See attached.

I check the channels using `magick identify -verbose out.png`

![out](https://user-images.githubusercontent.com/68076988/117898365-abeaa280-b279-11eb-9a8f-3ac5e4fc8d17.png)

**Comment by lovell** [comment]
SVG rendering is via librsvg, is always 4-channel RGBA and you are correct to use `removeAlpha` to reduce this to RGB output.

(32bpp RGBA is usually considered more optimal than 24bpp RGB for image processing as it can allow for the use of memory-aligned SIMD instructions.)

In terms of the use of `resize` vs `density` / `viewBox`, it depends on the image so you'll probably need to experiment for a given set of inputs.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
