### ISSUE TITLE
Bad seek errors when processing HEIC formats using Sharp 0.28.2 "Error: source: bad seek to 2994402 heif: Unsupported feature: Unsupported codec (4.3000)"

### ISSUE THREAD

**Issue by david-taggun** [lovell/sharp#2713]
**Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?**

Yes, version `^0.28.2`

**What are the steps to reproduce?**

Download and install latest libvips binaries from brew
Convert any HEIC photo to a buffer array, and then load it into sharp. The error is thrown immediately.

I can confirm that `heif-convert` can process the images
```
heif-convert IMG_4299.HEIC PNG_4299_CONVERTED.png 
File contains 1 images
Written to PNG_4299_CONVERTED.png
```

I can confirm that an older version of `sharp` continues without error
```
 "sharp": "^0.26.2"
```

**What is the expected behaviour?**

Continues without error, this issue is resolved by using an older version of sharp 

**Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?**

Sample Code
```js
const content = fs.readFileSync('./sample1.heic');

// This will throw the described error
const rotateImage = sharp(content);
```

Error Output
```
Error: source: bad seek to 2994402
heif: Unsupported feature: Unsupported codec (4.3000)
heif: Unsupported feature: Unsupported codec (4.3000)
```

**Are you able to provide a sample image that helps explain the problem?**

It's happening with all of our HEIC photos. But I can't supply a test sample publically sorry.

**What is the output of running `npx envinfo --binaries --system`?**

```
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 546.43 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 7.5.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
    libvips: vips-8.10.5-Fri Dec 18 10:14:09 UTC 2020
    heif-convert: 1.11.0
```

**Comment by lovell** [comment]
> libvips: vips-8.10.5-Fri Dec 18 10:14:09 UTC 2020

HEIC images require the use of a globally-installed libvips. sharp v0.28.x requires libvips 8.10.6, so you're probably using the prebuilt binaries that do not support HEIC images. Please can you upgrade libvips to 8.10.6 then re-install sharp.

**Comment by david-taggun** [comment]
Perfect. That was exactly the issue.

Just confirming that I upgraded my globally installed vips to 8.10.6; and rebuilt the binaries after a full rm -rf of the node_modules folder.

Thanks @lovell
