### ISSUE TITLE
Trimming to content while ignoring the text at top and footer ?

### ISSUE THREAD

**Issue by konlikha** [lovell/sharp#2717]
What are you trying to achieve? Trimming the image to content box

Have you searched for similar questions? Yes

Are you able to provide a minimal, standalone code sample that demonstrates this question? No

Are you able to provide a sample image that helps explain the question? Yes

I want to trim down my image to the main content box and then do some stuff with it.

This is the Image https://i.stack.imgur.com/rx4PA.png

Trim isn't working because of the text at top and bottom.

I Thought of using extend but it pad outside the image but i kinda want to overlay the text with the white background.

How can i trim to content ?

The Position of the box is not fixed.

**Comment by lovell** [comment]
If the lines of the inner box you want to keep are always thicker than the text you want to ignore, applying a Gaussian blur will erode the text more than the box. You can trim the blurred version to calculate the offsets, which can then be used to extract a region from the original image.

```js
  const blurred = await sharp("input.png").blur(10).toBuffer();

  const { width, height, trimOffsetLeft, trimOffsetTop } = await sharp(blurred)
    .trim(50)
    .toFile("trimmed.png");

  await sharp("input.png")
    .extract({
      top: Math.abs(trimOffsetTop),
      left: Math.abs(trimOffsetLeft),
      width,
      height,
    })
    .toFile("output.png");
```

Input: 
![](https://user-images.githubusercontent.com/210965/118401488-d499e000-b65d-11eb-987f-9a9934f0f7df.png)

Blurred and trimmed to calculate offsets:
![](https://user-images.githubusercontent.com/210965/118401512-e4b1bf80-b65d-11eb-92c4-b9609ba2175c.png)

Extracted image using the same offsets:
![](https://user-images.githubusercontent.com/210965/118401550-0612ab80-b65e-11eb-9117-b5492b401a22.png)

**Comment by konlikha** [comment]
Hello @lovell Thank you for the answer sir. The Blurring thing really went great but there's an issue regarding the performance. 
The process is taking about 5s to do the work. 
The Image Resolution is 2479x3508. 
The process will be executing in the Firebase Functions where the resources are limited. 

The process has to be completed under 2 second as there are some `pre-sharp` things needs to be done like converting the PDF to Image which takes about 2 sec.

I tried to reduce the time by remove the image save code part but no help.

    let file = "./Input/AA_CC17.jpeg";
    
    async function blurAndTrim() {
    
        console.time("blurAndTrim"); // 7.652s 5.5s 5.1s 5.15s
    
        let blurredBuffer = await sharp(file).blur(18).toBuffer(); // For blur, 18 is the amount needed for the original image to work properly
    
        let infoObject = await sharp(blurredBuffer).trim(50).toBuffer({ resolveWithObject: true });
    
        const { width, height, trimOffsetLeft, trimOffsetTop } = infoObject.info;    
    
        let trimBuffer = await sharp(file).extract({ top: Math.abs(trimOffsetTop), left: Math.abs(trimOffsetLeft), width, height }).toBuffer();
    
        await sharp(trimBuffer).trim().toFile("./final.jpeg");
        console.timeEnd("blurAndTrim")
    }
    
    blurAndTrim(); 


And on the second thought if it's possible to detect the dashed line inside the box with sharp ? this the region of interest i need to crop the image from there to bottom. The original image looks like this https://i.stack.imgur.com/PWdSY.jpg

**Comment by lovell** [comment]
Given the intermediate image is discarded, you can skip one compression step by returning raw pixel data.
```diff
- let infoObject = await sharp(blurredBuffer).trim(50).toBuffer({ resolveWithObject: true });
+ let infoObject = await sharp(blurredBuffer).trim(50).raw().toBuffer({ resolveWithObject: true });
```

**Comment by konlikha** [comment]
@lovell that didn't helped sir. It's the blur that's sucking up time here. using 15 half the time but ends up not working 18 is lowest working one. Any suggestions sir ? and about finding the dashed Line ?

**Comment by lovell** [comment]
Perhaps resize the 2479x3508 input image by 1/2 or 1/4, then scale everything else (smaller blur, larger extract region) accordingly.
