### ISSUE TITLE
 VipsJpeg: Corrupt JPEG data: premature end of data segment

### ISSUE THREAD

**Issue by mibuen** [lovell/sharp#2718]
I am trying to resize an array of images here is my code:
const Sharp = require('sharp');
const fs = require('fs');

const transformer = Sharp().resize(300);

const addFoto = async (request, h) => {
  const fotos = [].concat(request.payload.fotoFile);
  const smallerFotos = Promise.all(fotos.map(async (foto) => {
    const writeStream = fs.createWriteStream(foto.hapi.filename);
    return foto.pipe(transformer).pipe(writeStream);
  }));
the code works when the array length is one
but fails when more than file is in the array 
files are jpeg
thanks

**Comment by lovell** [comment]
You'll need to create a new sharp instance per input.
```diff
- const transformer = Sharp().resize(300);
+ const transformer = () => Sharp().resize(300);

  const addFoto = async (request, h) => {
  const fotos = [].concat(request.payload.fotoFile);
  const smallerFotos = Promise.all(fotos.map(async (foto) => {
  const writeStream = fs.createWriteStream(foto.hapi.filename);
- return foto.pipe(transformer).pipe(writeStream);
+ return foto.pipe(transformer()).pipe(writeStream);
  }));
```

**Comment by mibuen** [comment]
it works!
thank you very much
