### ISSUE TITLE
Loss of images when compositing after upgrate to 0.28.2

### ISSUE THREAD

**Issue by Able1991** [lovell/sharp#2719]
**Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?**
Yes - sharp@0.28.2

**What are the steps to reproduce?**
Update to latest sharp and use composite,with sharp@0.25.4 works fine

**What is the expected behaviour?**
Mosaic expected

result@0.25.4:
![result@0 25 4](https://user-images.githubusercontent.com/3898046/118471097-09666f80-b710-11eb-8d70-067c183717ab.jpg)
result@0.28.2:
![result@latest](https://user-images.githubusercontent.com/3898046/118471100-0b303300-b710-11eb-8823-c8d39137b037.jpg)

**Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?**
https://gist.github.com/Able1991/4befde2a00aa70df4d89428de58a2fae

**Are you able to provide a sample image that helps explain the problem?**
https://st.mvs.wtf/uploads/banner/itY_tAUN4/input.jpg

**What is the output of running `npx envinfo --binaries --system`?**
npx: installed 1 in 3.026s

  System:
    OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 2.72 GB / 15.88 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 13.14.0 - /usr/bin/node
    Yarn: 1.17.3 - /mnt/c/Users/User/AppData/Roaming/npm/yarn
    npm: 6.14.4 - /usr/bin/npm

**Comment by lovell** [comment]
v0.28.0 included the fix for https://github.com/lovell/sharp/issues/2571

The output from v0.25.4 is incorrect as the provided offsets (left=654, top=372) fall outside the 640x360 image dimensions.

https://sharp.pixelplumbing.com/changelog

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by Able1991** [comment]
> I hope this information helped. Please feel free to re-open with more details if further assistance is required.

thanks, it helped
