### ISSUE TITLE
Electron - 0.28.2 fails to find vips include folder.

### ISSUE THREAD

**Issue by janakg** [lovell/sharp#2720]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)? Yes

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime? Yes 

When I diff the 0.27.2 vs 0.28.2 in node_modules. The published version of 0.28.2 doesn't have an `include` dir inside the `vendor` dir of libvips.

`⨯ cannot execute  cause=exit status 1
                    out=yarn run v1.22.5
    $ (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
    sharp: Using existing vendored libvips v8.10.6
      CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
      LIBTOOL-STATIC Release/nothing.a
      TOUCH Release/obj.target/libvips-cpp.stamp
      CXX(target) Release/obj.target/sharp/src/common.o
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

                    errorOut=gyp info it worked if it ends with ok
    gyp info using node-gyp@5.0.5
    gyp info using node@12.13.0 | darwin | x64
    gyp info find Python using Python version 2.7.17 found at "/Users/janakg/anaconda3/envs/py27/bin/python"
    gyp info spawn /Users/janakg/anaconda3/envs/py27/bin/python
    gyp info spawn args [
    gyp info spawn args   '/Users/janakg/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'make',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/janakg/cosmos/repo/Sivi/packages/desktop/node_modules/sharp/build/config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/janakg/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/janakg/.electron-gyp/8.5.5/include/node/common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/Users/janakg/.electron-gyp/8.5.5',
    gyp info spawn args   '-Dnode_gyp_dir=/Users/janakg/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp',
    gyp info spawn args   '-Dnode_lib_file=/Users/janakg/.electron-gyp/8.5.5/<(target_arch)/node.lib',
    gyp info spawn args   '-Dmodule_root_dir=/Users/janakg/cosmos/repo/Sivi/packages/desktop/node_modules/sharp',
    gyp info spawn args   '-Dnode_engine=v8',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.'
    gyp info spawn args ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    ../src/common.cc:24:10: fatal error: 'vips/vips8' file not found
    #include <vips/vips8>
             ^~~~~~~~~~~~
    1 error generated.
    make: *** [Release/obj.target/sharp/src/common.o] Error 1
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/Users/janakg/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
    gyp ERR! System Darwin 19.6.0
    gyp ERR! command "/Users/janakg/.nvm/versions/node/v12.13.0/bin/node" "/Users/janakg/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/janakg/cosmos/repo/Sivi/packages/desktop/node_modules/sharp
    gyp ERR! node -v v12.13.0
    gyp ERR! node-gyp -v v5.0.5
    gyp ERR! not ok
    error Command failed with exit code 1.

                    command=/Users/janakg/.nvm/versions/node/v12.13.0/bin/node /Users/janakg/.nvm/versions/node/v12.13.0/lib/node_modules/yarn/bin/yarn.js run install
                    workingDir=/Users/janakg/cosmos/repo/Sivi/packages/desktop/node_modules/sharp
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

**Comment by lovell** [comment]
If you're using `electron-builder` then please see https://github.com/electron-userland/electron-builder/issues/5438 (you may recognise the person who opened it).

If not, please provide the complete output of running `npm install --verbose sharp`?

**Comment by janakg** [comment]
@lovell, thanks, I recognize :) I didn't realize it's still open. Sharp 0.27.2 is working for me.
