### ISSUE TITLE
font size rem unit not supported

### ISSUE THREAD

**Issue by baravak** [lovell/sharp#2721]
not supported rem unit in font-size and must change to "%" or "px" or "em"

**Comment by lovell** [comment]
The SVG spec doesn't mention support for `rem` in the `font-size` attribute.

https://www.w3.org/TR/SVG11/text.html#FontSizeProperty
https://www.w3.org/TR/SVG11/coords.html#Units

You might be able to use it via a `style` attribute.

Are you able to provide a sample image that helps explain the problem? _(This question is in the issue template but was deleted/ignored.)_
