### ISSUE TITLE
version 0.28.0 and later is not compatible with Intel Wolfdale E5xxx CPU

### ISSUE THREAD

**Issue by arm-ahh** [lovell/sharp#2723]
**Are you using the latest version?** 
yes

**What are the steps to reproduce?**
I just installed the latest version using npm. after adding this line of code:
```await sharp(req.file.path)```

I get this error:
```Illegal instruction (core dumped)```

**What is the output of running `npx envinfo --binaries --system`?**
```
  System:
    OS: Linux 5.4 Linux Mint 20 (Ulyana)
    CPU: (2) x64 Pentium(R) Dual-Core  CPU      E5300  @ 2.60GHz
    Memory: 172.51 MB / 3.84 GB
    Container: Yes
    Shell: 3.2.2 - /usr/bin/fish
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    npm: 7.6.1 - /usr/local/bin/npm
```

after trying a couple of older versions I found that the latest version that works for me is ```0.27.2```. I don't have any problem with this version yet.

**Comment by lovell** [comment]
The Intel Wolfdale E5300 CPU dates from 2008 so is currently 13 years old, which I think makes it old enough to get its own Facebook account.

As of v0.28.0 and https://github.com/lovell/sharp-libvips/pull/88, the prebuilt binaries for Linux x64 now require a Westmere CPU or later, which is pretty much all the Intel and AMD CPUs made in the last 11 years (so we can use SSE4.2, POPCNT, AES and PCLMUL intrinsics).

You are still able to compile your own libvips and install it globally before installing sharp - please see https://sharp.pixelplumbing.com/install#custom-libvips

**Comment by arm-ahh** [comment]
Yes, it's a pretty old CPU. I just wanted to report:) 
Especially since version `0.27.2`, which was released just a few months ago works for me I thought it could be solved.
Anyway, thanks for the reply.

**Comment by sineway** [comment]
> The Intel Wolfdale E5300 CPU dates from 2008 so is currently 13 years old, which I think makes it old enough to get its own Facebook account.
> 
> As of v0.28.0 and [lovell/sharp-libvips#88](https://github.com/lovell/sharp-libvips/pull/88), the prebuilt binaries for Linux x64 now require a Westmere CPU or later, which is pretty much all the Intel and AMD CPUs made in the last 11 years (so we can use SSE4.2, POPCNT, AES and PCLMUL intrinsics).
> 
> You are still able to compile your own libvips and install it globally before installing sharp - please see https://sharp.pixelplumbing.com/install#custom-libvips

The same here — Intel Pentium E6500 (launched in August 2009).
I believe that image processing library is not the reason to upgrade harware.

**Comment by leandro-machado-costa** [comment]
Could you tell me how to get around this? Well it's not working

**Comment by Lambdac0re** [comment]
Similar crash on AMD Athlon II X2 255 from 2010

**Comment by lovell** [comment]
v0.31.0 will provide prebuilt binaries for Linux that require the x64 v2 microarchitecture, which is approximately equivalent to the Intel Nehalem family of CPUs (slightly older than Westmere). This approach means we align with a growing number of Linux distributions that are starting to require this microarchitecture as a minimum for x64 - see https://github.com/lovell/sharp-libvips/pull/155
