### ISSUE TITLE
Remove Extra space Between boxes ?

### ISSUE THREAD

**Issue by konlikha** [lovell/sharp#2725]
What are you trying to achieve? Removing Extra Space Between two images.

Have you searched for similar questions? Yes

Are you able to provide a minimal, standalone code sample that demonstrates this question? No

Are you able to provide a sample image that helps explain the question? Yes

----------------------------------------------------------------------------------------------------------

I am trying to Crop out set of boxes as a single card from a image. But the space between the boxes is more than i want.

This is the image.

![cards](https://user-images.githubusercontent.com/53863343/118974132-185b5500-b990-11eb-8f51-ed89f7bde1a9.jpeg)
_After trimming there's no space at TBLR_

I can crop out both of manually and join them with join-images package but the width of images are not always same.
So Manual extraction is not the way i think.

How can i remove the extra space between the cards ?

**Comment by lovell** [comment]
This is probably more of a general software question better suited to a site such as StackOverflow.
