### ISSUE TITLE
Sharp Automatically Changing to sRGB, Which is unexpected.

### ISSUE THREAD

**Issue by totalard** [lovell/sharp#2727]
As i Need CMYK for Printing Application(Different Printing Purpose, Where i input File in CMYK jpeg, and i need resized JPEG from sharp with same CMYK,

buy sharp convert my input CMYK image to sRGB first, and then reconvert it to CMYK ,, which is not needed, I need Input and output both in CMYK, without any conversion, How is that possible.. 

because of CMYK -> sRGB -> CMYK, the input and output CMYK ratio has differences. Please fix this bug

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/1317 for a future possible enhancement to use a 16-bit gamut for the processing pipeline, which will encompass the most popular CMYK gamuts e.g. SWOP.

**Comment by lovell** [comment]
Please subscribe to #1317 for updates.
