### ISSUE TITLE
Still Having Difficulties Installing Sharp on M1 Device

### ISSUE THREAD

**Issue by mcewen87** [lovell/sharp#2729]
I have tried a handful of resolutions for this issue. Oddly enough, I was receiving the same error on another project, both Gatsby sites. But I was able to resolve the past issue by changing node versions. But now that isn't doing the trick. 

Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?

Yes

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?

Yes, they are both arm64

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

I'm trying to install the latest version of sharp and receiving errors. 

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7, does the user running `npm install` own the directory it is run in?

Yes

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

Yes, the output is 

npm ERR! code 1
npm ERR! path /Users/jonmcewen/Desktop/web design/jonmce/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Detected globally-installed libvips v8.10.6
npm ERR! sharp: Building from source via node-gyp
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.10.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.5 found at "/opt/homebrew/opt/python@3.9/bin/python3.9"
npm ERR! gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/jonmcewen/Desktop/web design/jonmce/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/jonmcewen/Desktop/web design/jonmce/node_modules/sharp/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/jonmcewen/Desktop/web design/jonmce/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/jonmcewen/Library/Caches/node-gyp/15.10.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/jonmcewen/Library/Caches/node-gyp/15.10.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/jonmcewen/Desktop/web design/jonmce/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/jonmcewen/Library/Caches/node-gyp/15.10.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/jonmcewen/Desktop/web design/jonmce/node_modules/sharp',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Package OpenEXR was not found in the pkg-config search path.
npm ERR! Perhaps you should add the directory containing `OpenEXR.pc'
npm ERR! to the PKG_CONFIG_PATH environment variable
npm ERR! Package 'OpenEXR', required by 'vips', not found
npm ERR! gyp: Call to 'PKG_CONFIG_PATH="/usr/lib/pkgconfig:/opt/homebrew/Library/Homebrew/os/mac/pkgconfig/11:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --cflags-only-I vips-cpp vips glib-2.0 | sed s\/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/jonmcewen/Desktop/web design/jonmce/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 20.4.0
npm ERR! gyp ERR! command "/Users/jonmcewen/.nvm/versions/node/v15.10.0/bin/node" "/Users/jonmcewen/Desktop/web design/jonmce/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/jonmcewen/Desktop/web design/jonmce/node_modules/sharp
npm ERR! gyp ERR! node -v v15.10.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jonmcewen/.npm/_logs/2021-05-22T22_44_09_337Z-debug.log

What is the output of running `npx envinfo --binaries --system`?

 System:
    OS: macOS 11.3
    CPU: (8) arm64 Apple M1
    Memory: 245.13 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.10.0 - ~/.nvm/versions/node/v15.10.0/bin/node
    npm: 7.14.0 - ~/.nvm/versions/node/v15.10.0/bin/npm

**Comment by lovell** [comment]
Hello, the install log suggests you've previously installed the `vips` package globally via Homebrew:

> npm ERR! sharp: Detected globally-installed libvips v8.10.6
> npm ERR! sharp: Building from source via node-gyp

But it looks like something went wrong with brew-managed dependencies when it was installed:

> npm ERR! Package OpenEXR was not found in the pkg-config search path.

If you don't need a custom libvips then you can run `brew uninstall vips` to remove this and sharp will use its own prebuilt binaries.

https://sharp.pixelplumbing.com/install#apple-m1

**Comment by mcewen87** [comment]
Hi, 

Thank you so much for this. I appreciate all of the time you put into helping developers. Thank you @lovell !!!

**Comment by ndan** [comment]
Same issue on intel based mac. Fixed by `brew uninstall vips`. Thanks @lovell.
