### ISSUE TITLE
GLib-GObject error

### ISSUE THREAD

**Issue by Nigelrex** [lovell/sharp#2732]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
I made a discord bot that scales images but something is wrong when i try to run my bot on https://repl.it.com

What is the expected behaviour?
it should be running normally showing server running and bot is online when i run it.

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

Are you able to provide a sample image that helps explain the problem?
![error](https://user-images.githubusercontent.com/75080457/119451515-fa587080-bd52-11eb-8959-75681f5c9887.png)

What is the output of running `npx envinfo --binaries --system`?
![npx](https://user-images.githubusercontent.com/75080457/119451615-1cea8980-bd53-11eb-9c05-80c32ec67bd7.png)

**Comment by Nigelrex** [comment]
@lovell this only happened before and after the latest release that you published 15hrs ago

**Comment by lovell** [comment]
Please can you provide a minimal, standalone repo with dependencies and code that demonstrates this problem.

**Comment by Nigelrex** [comment]
sure just a second

**Comment by lovell** [comment]
You'll need to get the `scale-pixel-art` dependency to update its dependencies, e.g. https://github.com/Beatso/ScalePixelArt/pull/8

```
$ npm ls sharp
craftyourworld-bot@2.0.0 CraftYourWorld-Bot
├─┬ scale-pixel-art@1.0.0
│ └── sharp@0.26.3 
└── sharp@0.28.2 
```

**Comment by Nigelrex** [comment]
but still it has not been published even tho it is updated in the repo

**Comment by lovell** [comment]
From v0.27.0 onwards, sharp has provided statically-linked prebuilt binaries that allows multiple versions to coexist in the same process (and avoid this kind of problem).

As you've got a transitive dependency on a version prior to v0.27.0, you'll need to use only versions on the same v0.26.x line. Once `scale-pixel-art` upgrades to at least sharp v0.27.0 then you'll be able to upgrade your direct dependency to the latest version of sharp.

**Comment by Nigelrex** [comment]
thankyou now i get it

**Comment by Beatso** [comment]
I've updated `scale-pixel-art` to use `sharp@0.28.3`, which should help you to fix the issue you were getting @Nigelrex

**Comment by Nigelrex** [comment]
Thanks I will be checking it out tomorrow ☺️
