### ISSUE TITLE
Error undefined symbol: vips_foreign_heif_compression_get_type

### ISSUE THREAD

**Issue by manzajaro** [lovell/sharp#2733]
Hi,

I'm use sharp version 0.28.3, libvips 8.11.0 and ubuntu 18.04 arch armv7l

When I do 'ldd node_modules/sharp/build/Release/sharp.node'

       

>  linux-vdso.so.1 (0xbedf0000)
>         libvips-cpp.so.42 => /usr/lib/arm-linux-gnueabihf/libvips-cpp.so.42 (0xb6ed3000)
>         libvips.so.42 => /usr/lib/arm-linux-gnueabihf/libvips.so.42 (0xb6bdc000)
>         libgobject-2.0.so.0 => /usr/lib/arm-linux-gnueabihf/libgobject-2.0.so.0 (0xb6b94000)
>         libglib-2.0.so.0 => /usr/lib/arm-linux-gnueabihf/libglib-2.0.so.0 (0xb6ab7000)
>         libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0xb69a4000)
>         libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0xb6923000)
>         libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0xb68fa000)
>         libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb68d5000)
>         libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb67dd000)
>         /lib/ld-linux-armhf.so.3 (0xb6f5f000)
>         libMagickCore-6.Q16.so.3 => /usr/lib/arm-linux-gnueabihf/libMagickCore-6.Q16.so.3 (0xb65d4000)
>         libpng16.so.16 => /usr/lib/arm-linux-gnueabihf/libpng16.so.16 (0xb65a4000)
>         libtiff.so.5 => /usr/lib/arm-linux-gnueabihf/libtiff.so.5 (0xb653d000)
>         libjpeg.so.8 => /usr/lib/arm-linux-gnueabihf/libjpeg.so.8 (0xb6505000)
>         libgmodule-2.0.so.0 => /usr/lib/arm-linux-gnueabihf/libgmodule-2.0.so.0 (0xb64f2000)
>         libpangoft2-1.0.so.0 => /usr/lib/arm-linux-gnueabihf/libpangoft2-1.0.so.0 (0xb64d3000)
>         libpango-1.0.so.0 => /usr/lib/arm-linux-gnueabihf/libpango-1.0.so.0 (0xb648d000)
>         libgsf-1.so.114 => /usr/lib/arm-linux-gnueabihf/libgsf-1.so.114 (0xb6453000)
>         libxml2.so.2 => /usr/lib/arm-linux-gnueabihf/libxml2.so.2 (0xb6331000)
>         libfftw3.so.3 => /usr/lib/arm-linux-gnueabihf/libfftw3.so.3 (0xb6256000)
>         liborc-0.4.so.0 => /usr/lib/arm-linux-gnueabihf/liborc-0.4.so.0 (0xb61f8000)
>         liblcms2.so.2 => /usr/lib/arm-linux-gnueabihf/liblcms2.so.2 (0xb61b2000)
>         libgif.so.7 => /usr/lib/arm-linux-gnueabihf/libgif.so.7 (0xb619c000)
>         librsvg-2.so.2 => /usr/lib/arm-linux-gnueabihf/librsvg-2.so.2 (0xb6168000)
>         libpoppler-glib.so.8 => /usr/lib/arm-linux-gnueabihf/libpoppler-glib.so.8 (0xb611d000)
>         libcairo.so.2 => /usr/lib/arm-linux-gnueabihf/libcairo.so.2 (0xb6060000)
>         libIlmImf-2_2.so.22 => /usr/lib/arm-linux-gnueabihf/libIlmImf-2_2.so.22 (0xb5dde000)
>         libopenslide.so.0 => /usr/lib/arm-linux-gnueabihf/libopenslide.so.0 (0xb5dac000)
>         libcfitsio.so.5 => /usr/lib/arm-linux-gnueabihf/libcfitsio.so.5 (0xb5c4f000)
>         libwebp.so.6 => /usr/lib/arm-linux-gnueabihf/libwebp.so.6 (0xb5c00000)
>         libmatio.so.4 => /usr/lib/arm-linux-gnueabihf/libmatio.so.4 (0xb5bb0000)
>         libz.so.1 => /lib/arm-linux-gnueabihf/libz.so.1 (0xb5b86000)
>         libexif.so.12 => /usr/lib/arm-linux-gnueabihf/libexif.so.12 (0xb5b49000)
>         libffi.so.6 => /usr/lib/arm-linux-gnueabihf/libffi.so.6 (0xb5b33000)
>         libpcre.so.3 => /lib/arm-linux-gnueabihf/libpcre.so.3 (0xb5ad6000)
>         liblqr-1.so.0 => /usr/lib/arm-linux-gnueabihf/liblqr-1.so.0 (0xb5abd000)
>         libfontconfig.so.1 => /usr/lib/arm-linux-gnueabihf/libfontconfig.so.1 (0xb5a7e000)
>         libfreetype.so.6 => /usr/lib/arm-linux-gnueabihf/libfreetype.so.6 (0xb5a03000)
>         libXext.so.6 => /usr/lib/arm-linux-gnueabihf/libXext.so.6 (0xb59e8000)
>         libX11.so.6 => /usr/lib/arm-linux-gnueabihf/libX11.so.6 (0xb58f7000)
>         libbz2.so.1.0 => /lib/arm-linux-gnueabihf/libbz2.so.1.0 (0xb58db000)
>         libltdl.so.7 => /usr/lib/arm-linux-gnueabihf/libltdl.so.7 (0xb58c5000)
>         libgomp.so.1 => /usr/lib/arm-linux-gnueabihf/libgomp.so.1 (0xb5896000)
>         liblzma.so.5 => /lib/arm-linux-gnueabihf/liblzma.so.5 (0xb586c000)
>         libjbig.so.0 => /usr/lib/arm-linux-gnueabihf/libjbig.so.0 (0xb5852000)
>         libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0xb583f000)
>         libharfbuzz.so.0 => /usr/lib/arm-linux-gnueabihf/libharfbuzz.so.0 (0xb57bd000)
>         libthai.so.0 => /usr/lib/arm-linux-gnueabihf/libthai.so.0 (0xb57a6000)
>         libgio-2.0.so.0 => /usr/lib/arm-linux-gnueabihf/libgio-2.0.so.0 (0xb5697000)
>         libicuuc.so.60 => /usr/lib/arm-linux-gnueabihf/libicuuc.so.60 (0xb5561000)
>         libgdk_pixbuf-2.0.so.0 => /usr/lib/arm-linux-gnueabihf/libgdk_pixbuf-2.0.so.0 (0xb5537000)
>         libpangocairo-1.0.so.0 => /usr/lib/arm-linux-gnueabihf/libpangocairo-1.0.so.0 (0xb551e000)
>         libcroco-0.6.so.3 => /usr/lib/arm-linux-gnueabihf/libcroco-0.6.so.3 (0xb54e9000)
>         libpoppler.so.73 => /usr/lib/arm-linux-gnueabihf/libpoppler.so.73 (0xb533c000)
>         libpixman-1.so.0 => /usr/lib/arm-linux-gnueabihf/libpixman-1.so.0 (0xb52b5000)
>         libxcb-shm.so.0 => /usr/lib/arm-linux-gnueabihf/libxcb-shm.so.0 (0xb52a2000)
>         libxcb.so.1 => /usr/lib/arm-linux-gnueabihf/libxcb.so.1 (0xb527a000)
>         libxcb-render.so.0 => /usr/lib/arm-linux-gnueabihf/libxcb-render.so.0 (0xb5261000)
>         libXrender.so.1 => /usr/lib/arm-linux-gnueabihf/libXrender.so.1 (0xb524a000)
>         librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0xb5234000)
>         libHalf.so.12 => /usr/lib/arm-linux-gnueabihf/libHalf.so.12 (0xb51e1000)
>         libIex-2_2.so.12 => /usr/lib/arm-linux-gnueabihf/libIex-2_2.so.12 (0xb51bc000)
>         libIlmThread-2_2.so.12 => /usr/lib/arm-linux-gnueabihf/libIlmThread-2_2.so.12 (0xb51a7000)
>         libsqlite3.so.0 => /usr/lib/arm-linux-gnueabihf/libsqlite3.so.0 (0xb50f8000)
>         libopenjp2.so.7 => /usr/lib/arm-linux-gnueabihf/libopenjp2.so.7 (0xb50ae000)
>         libcurl-gnutls.so.4 => /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so.4 (0xb5050000)
>         libhdf5_serial.so.100 => /usr/lib/arm-linux-gnueabihf/libhdf5_serial.so.100 (0xb4c85000)
>         libexpat.so.1 => /lib/arm-linux-gnueabihf/libexpat.so.1 (0xb4c53000)
>         libgraphite2.so.3 => /usr/lib/arm-linux-gnueabihf/libgraphite2.so.3 (0xb4c28000)
>         libdatrie.so.1 => /usr/lib/arm-linux-gnueabihf/libdatrie.so.1 (0xb4c14000)
>         libselinux.so.1 => /lib/arm-linux-gnueabihf/libselinux.so.1 (0xb4beb000)
>         libresolv.so.2 => /lib/arm-linux-gnueabihf/libresolv.so.2 (0xb4bcb000)
>         libmount.so.1 => /lib/arm-linux-gnueabihf/libmount.so.1 (0xb4b83000)
>         libicudata.so.60 => /usr/lib/arm-linux-gnueabihf/libicudata.so.60 (0xb31ca000)
>         libnss3.so => /usr/lib/arm-linux-gnueabihf/libnss3.so (0xb3107000)
>         libsmime3.so => /usr/lib/arm-linux-gnueabihf/libsmime3.so (0xb30de000)
>         libnspr4.so => /usr/lib/arm-linux-gnueabihf/libnspr4.so (0xb30aa000)
>         libXau.so.6 => /usr/lib/arm-linux-gnueabihf/libXau.so.6 (0xb3097000)
>         libXdmcp.so.6 => /usr/lib/arm-linux-gnueabihf/libXdmcp.so.6 (0xb3083000)
>         libnghttp2.so.14 => /usr/lib/arm-linux-gnueabihf/libnghttp2.so.14 (0xb305b000)
>         libidn2.so.0 => /usr/lib/arm-linux-gnueabihf/libidn2.so.0 (0xb3030000)
>         librtmp.so.1 => /usr/lib/arm-linux-gnueabihf/librtmp.so.1 (0xb300a000)
>         libpsl.so.5 => /usr/lib/arm-linux-gnueabihf/libpsl.so.5 (0xb2fed000)
>         libnettle.so.6 => /usr/lib/arm-linux-gnueabihf/libnettle.so.6 (0xb2fb2000)
>         libgnutls.so.30 => /usr/lib/arm-linux-gnueabihf/libgnutls.so.30 (0xb2eb2000)
>         libgssapi_krb5.so.2 => /usr/lib/arm-linux-gnueabihf/libgssapi_krb5.so.2 (0xb2e77000)
>         libldap_r-2.4.so.2 => /usr/lib/arm-linux-gnueabihf/libldap_r-2.4.so.2 (0xb2e34000)
>         liblber-2.4.so.2 => /usr/lib/arm-linux-gnueabihf/liblber-2.4.so.2 (0xb2e1b000)
>         libsz.so.2 => /usr/lib/arm-linux-gnueabihf/libsz.so.2 (0xb2e08000)
>         libblkid.so.1 => /lib/arm-linux-gnueabihf/libblkid.so.1 (0xb2dc7000)
>         libnssutil3.so => /usr/lib/arm-linux-gnueabihf/libnssutil3.so (0xb2d9a000)
>         libplc4.so => /usr/lib/arm-linux-gnueabihf/libplc4.so (0xb2d84000)
>         libplds4.so => /usr/lib/arm-linux-gnueabihf/libplds4.so (0xb2d71000)
>         libbsd.so.0 => /lib/arm-linux-gnueabihf/libbsd.so.0 (0xb2d4f000)
>         libunistring.so.2 => /usr/lib/arm-linux-gnueabihf/libunistring.so.2 (0xb2be4000)
>         libhogweed.so.4 => /usr/lib/arm-linux-gnueabihf/libhogweed.so.4 (0xb2bac000)
>         libgmp.so.10 => /usr/lib/arm-linux-gnueabihf/libgmp.so.10 (0xb2b54000)
>         libp11-kit.so.0 => /usr/lib/arm-linux-gnueabihf/libp11-kit.so.0 (0xb2a92000)
>         libtasn1.so.6 => /usr/lib/arm-linux-gnueabihf/libtasn1.so.6 (0xb2a76000)
>         libkrb5.so.3 => /usr/lib/arm-linux-gnueabihf/libkrb5.so.3 (0xb29de000)
>         libk5crypto.so.3 => /usr/lib/arm-linux-gnueabihf/libk5crypto.so.3 (0xb29a9000)
>         libcom_err.so.2 => /lib/arm-linux-gnueabihf/libcom_err.so.2 (0xb2994000)
>         libkrb5support.so.0 => /usr/lib/arm-linux-gnueabihf/libkrb5support.so.0 (0xb297d000)
>         libsasl2.so.2 => /usr/lib/arm-linux-gnueabihf/libsasl2.so.2 (0xb295c000)
>         libgssapi.so.3 => /usr/lib/arm-linux-gnueabihf/libgssapi.so.3 (0xb2927000)
>         libaec.so.0 => /usr/lib/arm-linux-gnueabihf/libaec.so.0 (0xb2911000)
>         libuuid.so.1 => /lib/arm-linux-gnueabihf/libuuid.so.1 (0xb28fb000)
>         libkeyutils.so.1 => /lib/arm-linux-gnueabihf/libkeyutils.so.1 (0xb28e8000)
>         libheimntlm.so.0 => /usr/lib/arm-linux-gnueabihf/libheimntlm.so.0 (0xb28d2000)
>         libkrb5.so.26 => /usr/lib/arm-linux-gnueabihf/libkrb5.so.26 (0xb2870000)
>         libasn1.so.8 => /usr/lib/arm-linux-gnueabihf/libasn1.so.8 (0xb280a000)
>         libhcrypto.so.4 => /usr/lib/arm-linux-gnueabihf/libhcrypto.so.4 (0xb27d4000)
>         libroken.so.18 => /usr/lib/arm-linux-gnueabihf/libroken.so.18 (0xb27b7000)
>         libwind.so.0 => /usr/lib/arm-linux-gnueabihf/libwind.so.0 (0xb277f000)
>         libheimbase.so.1 => /usr/lib/arm-linux-gnueabihf/libheimbase.so.1 (0xb2766000)
>         libhx509.so.5 => /usr/lib/arm-linux-gnueabihf/libhx509.so.5 (0xb272b000)
>         libcrypt.so.1 => /lib/arm-linux-gnueabihf/libcrypt.so.1 (0xb26ec000)
> 

My code is

`
sharp('/home/odroid/ServidorNode/images/base/local.jpg').resize(120, 120).toFile('/home/odroid/ServidorNode/images/base/local.png', function(err, info) {console.log("OKK")}); 
`

I recived the next error and nodejs close

`
node: symbol lookup error: /home/odroid/ServidorNode/node_modules/sharp/build/Release/sharp.node: undefined symbol: vips_foreign_heif_compression_get_type`

**Comment by lovell** [comment]
It looks like you've got multiple, conflicting versions of libvips installed.

The filesystem path of these files suggest they were installed via a package manager, possibly as part of libvips v8.4.5.

>  libvips-cpp.so.42 => /usr/lib/arm-linux-gnueabihf/libvips-cpp.so.42 (0xb6ed3000)

libvips v8.11.0 is not yet released, so I guess you're compiling libvips from the latest GitHub source.

https://libvips.github.io/libvips/install.html#building-libvips-from-a-source-tarball

Make sure the directory to which you're installing libvips is known to ldconfig.

**Comment by manzajaro** [comment]
Thanks @lovell.

I can solve it.

I didn't know I had another version installed via package.

https://github.com/lovell/sharp/issues/2210  

In this case, they recommended uninstalling the package `libvips-dev`, but I did not have it installed.

researching I have seen that the problem was in the package `libvips42`.

`apt-get remove libvips42
apt-get autoremove
`
