### ISSUE TITLE
Sharp not working on Some Windows 7

### ISSUE THREAD

**Issue by bhavya32** [lovell/sharp#2734]
I am really tired what is not working in my code. I install venom-bot which has sharp as a dependency. Sharp is installed correctly no errors. But I am getting errors on some windows 7 pc as following - 
![Screenshot 2021-05-25 200816](https://user-images.githubusercontent.com/55047586/119549613-05dc8380-bdb5-11eb-92ba-0ac6e177eea2.jpg)

It says sharp.node is not found while I checked its right where its checking it to be.  I uninstalled reinstalled and rebuild. But all failed. Does anyone here has any idea?
@lovell Please, I am in a tough situation if you can help.

**Comment by lovell** [comment]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7, does the user running `npm install` own the directory it is run in?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

What is the output of running `npx envinfo --binaries --system`?

**Comment by bhavya32** [comment]
@lovell As I said, there is no install error in sharp. Sharp is being installed successfully, I am on node v13 and tried everything other than npx envinfo. Will give it a try too.

**Comment by bhavya32** [comment]
@lovell does \\?\ before the path have any relation to the problem?

**Comment by lovell** [comment]
Node.js 13 reached end-of-life in June last year, please upgrade.

If you're still having problems, please can you provide the complete output of running the following commands in a brand new, empty directory.

```
node -v
```
```
npm install --verbose sharp
```
```
node -p "require('sharp').format"
```

**Comment by lovell** [comment]
@bhavya32 Were you able to make any progress with this? If you're still having problems, please can you provide the requested information.

**Comment by bhavya32** [comment]
@lovell Didn't find any solution. Tried many things, but none worked. I had to remove sharp to run on those systems.

Those were not my systems. I fear I won't be able to provide the requested output as none dev machine faced that. I can just assure that sharp installed correctly without any error.  Don't have access to those machines now. You can close the issue.
