### ISSUE TITLE
local libvips tar (not installed on the build env)

### ISSUE THREAD

**Issue by PlopTheReal** [lovell/sharp#2735]
I would like to install a libvips built from the source (with extra deps such as poppler) that are not installed on the build machine.
Is there is a way to provide a local path rather than a host via sharp_libvips_binary_host?
Or - is there is a way to 'embed' the libvips in the node modules rather than linking to the global libvips when building with the global libvips?

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/install#custom-libvips

https://sharp.pixelplumbing.com/install#custom-prebuilt-binaries

**Comment by PlopTheReal** [comment]
Thanks for such a quick reply! 
I've been through the doc a bunch but I still can't get it to work the way I want.

In my scenarion libvips isn't globally installed. Its sitting in a tar.gz waiting to be used.
I'm trying to self host over http via npm_config_sharp_libvips_binary_host but I can't get it to work so far (within a docker build).
I was wondering if that wouldn't be easier to be able to also specify a path to a local libvips build (not globally installed) rather than a http server.

On another note, if I use a globally installed libvips, `ldd node_modules/sharp/build/Release/sharp.node` show me that it's targeting the libs from the system. How can I make it target to the vendor embedded folder within the node_modules?

**Comment by lovell** [comment]
> Its sitting in a tar.gz waiting to be used.

How was this file built? What does it contain? Did you use a modified version of https://github.com/lovell/sharp-libvips/ ?

**Comment by PlopTheReal** [comment]
It's built via the following docker: 
```
FROM node:14-buster as base

RUN apt-get update -qq && \
    apt-get install -qq -y --no-install-recommends \
      build-essential \
      autoconf \
      automake \
      libtool \
      intltool \
      gtk-doc-tools \
      unzip \
      wget \
      git \
      pkg-config

RUN apt-get install -qq -y --no-install-recommends \
  libglib2.0-dev \
  libexpat1-dev \
  libjpeg-dev \
  libpng-dev \
  libtiff-dev \
  libgif-dev \
  libpoppler-dev \
  libpoppler-glib-dev \
  librsvg2-dev


ENV VIPS_VERSION=8.10.6

ARG WEBP_VERSION=1.2.0

ENV VIPSHOME /usr/local
ENV PKG_CONFIG_PATH $VIPSHOME/lib/pkgconfig

RUN cd /usr/src \
      && wget --no-check-certificate https://github.com/webmproject/libwebp/archive/v$WEBP_VERSION.tar.gz \
      && tar -xvf v$WEBP_VERSION.tar.gz \
      && cd libwebp-$WEBP_VERSION \
      && ./autogen.sh \
      && ./configure --prefix=$VIPSHOME --enable-libwebpmux --enable-libwebpdemux --enable-libwebpdecoder \
      && make \
      && make install \
      && ldconfig

ARG VIPS_URL=https://github.com/libvips/libvips/releases/download

RUN cd /usr/src \
      && wget --no-check-certificate ${VIPS_URL}/v${VIPS_VERSION}/vips-${VIPS_VERSION}.tar.gz \
      && tar xzf vips-${VIPS_VERSION}.tar.gz \
      && cd vips-${VIPS_VERSION} \
      && export PKG_CONFIG_PATH=/usr/src/vips/lib/pkgconfig \
      && ./configure --prefix=$VIPSHOME --disable-gtk-doc --without-magick --with-modules \
      && make \
      && make install \
      && ldconfig

RUN cd $VIPSHOME \
  && rm -rf build \
  && mkdir build \
  && tar czf \
    $VIPSHOME/build/libvips.tar.gz bin include lib

```

**Comment by lovell** [comment]
If you'd like to create a tarball that is "drop-in" compatible with the prebuilt libvips binaries then I recommend you follow the approach taken by the scripts and containers provided in https://github.com/lovell/sharp-libvips/

**Comment by PlopTheReal** [comment]
Thanks, I'll get the custom libvips (with poppler) from the global libvips as it seems quite easier.
