### ISSUE TITLE
I cannot redirect a webp animated of different height and width

### ISSUE THREAD

**Issue by GladistonXD** [lovell/sharp#2737]
"archive webp: dimension 400x500"
```
sharp('archive.webp', {animated: true})
	.resize(400)
	.webp({pageHeight: 400})
```
output: dimension 400x2100...

I can only get a satisfactory result with a file of equal dimensions, is it possible to get around this?

**Comment by lovell** [comment]
Please can you provide a sample input image to help explain your question.

**Comment by GladistonXD** [comment]
Yes exemple this webp animated 498x463

<a href="https://raw.githubusercontent.com/GladistonXD/teste.txt/master/Exemple"><img src="https://raw.githubusercontent.com/GladistonXD/teste.txt/master/archive%20498x463.webp" title="Exemple"/></a>

**Comment by lovell** [comment]
Thanks, this doesn't have quite the same dimensions as the original question, but here's how you might resize this to 400x372:

```js
const { pages } = await sharp("archive 498x463.webp").metadata();
await sharp("archive 498x463.webp", { animated: true })
  .resize({ width: 400, height: pages * 372 })
  .webp({ pageHeight: 372 })
  .toFile("out.webp")
```

Please subscribe to https://github.com/lovell/sharp/issues/2275 for a future possible enhancement that relates to this.

**Comment by GladistonXD** [comment]
Yes the one above was a short example, thanks, this solved the problem, I will subscrible the enhancement congratulations for the library.
