### ISSUE TITLE
How do you get a global custom libvips referring to vendor folders?

### ISSUE THREAD

**Issue by PlopTheReal** [lovell/sharp#2738]
When running npm install with a global vips installed I'm getting the following ref for libvips:

```
ldd node_modules/sharp/build/Release/sharp.node
        linux-vdso.so.1 (0x00007fff94dd6000)
        libvips-cpp.so.42 => /usr/local/lib/libvips-cpp.so.42 (0x00007f4881d55000)
        libvips.so.42 => /usr/local/lib/libvips.so.42 (0x00007f488184d000)
```

When running without global vips it gets it from sharp repository. Then ldd refer a libvips embedded to node_modules.
```
ldd node_modules/sharp/build/Release/sharp.node
        linux-vdso.so.1 (0x00007ffe599f6000)
        libvips-cpp.so.42 => /home/plop/testSharp/node_modules/sharp/build/Release/../../vendor/8.10.6/lib/libvips-cpp.so.42 (0x00007fd9af0f1000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd9aeefa000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd9aedab000)
```

How do you get the same result with a global libvips? (ie: having it pointing to vendor) 
The reason is I'd like the app to be packaged as a standalone binary with a tool such as pkg, nexe or appimage so the server that'll run the node app will not have libvips with poppler installed.

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/install#building-from-source

To ignore a globally-installed libvips at `npm install` time, set the `SHARP_IGNORE_GLOBAL_LIBVIPS` environment variable.

**Comment by PlopTheReal** [comment]
Thanks @lovell for the feedback.

The problem is that I can't use the default prebuilt binaries as I need lib poppler to support PDFs.
I've been through 2 main scenarios to try to sort that out:
1. I can get the custom global libvips installed but I would need libvips-cpp.so.42 located/referred from the vendor package instead of the system it was built on (the end app is running as a standalone exe).
2. I built the custom libvips packaged as a tar.gz and provided `npm_config_sharp_libvips_binary_host` but I haven't been able to get the installer pick it up over HTTP successfully so far (it's a bit harder within a docker build). I was thinking that it would be nice to be able to pass also a local path rather than only a HTTP host which might make such scenario easier but I think that's another thing.

**Comment by lovell** [comment]
My advice would be to bundle and invoke Poppler's `pdftocairo` utility as a separate process. It's simpler and will help avoid any potential GPL licensing issues that running libpoppler in the same process might bring.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
