### ISSUE TITLE
Documentation web site does not render anything.  

### ISSUE THREAD

**Issue by ghankerson** [lovell/sharp#2739]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?  N/A

What are the steps to reproduce?  Go to https://sharp.pixelplumbing.com. - it's just a white screen

What is the expected behaviour?  See the website 

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem? N/A

As a workaround you can go to the Way Back Machine https://web.archive.org/web/20210523064213if_/https://sharp.pixelplumbing.com/install

**Comment by lovell** [comment]
Hello, the site works for me and it works for WebPageTest too:
https://www.webpagetest.org/result/210602_BiDc15_cc26d6539ffbe51d33d31efba52ca26e/

Perhaps there was a temporary networking problem? 

It's fronted by Cloudflare CDN, uses Fastly CDN in the middle and is backed by Google Firebase Hosting, so the availability is expected to be very, very high.

Are you able to re-test? Are there any JavaScript errors in the console? Which browser/OS are you using?

**Comment by ghankerson** [comment]
Hmm I get all kinds of CORS Errors


`Content Security Policy: The page’s settings blocked the loading of a resource at https://cdn.jsdelivr.net.x.3d1398140012f049a0096e0054dce6d1b9ca.9270fa56.id.opendns.com/s/cdn.jsdelivr.net/gh/lovell/sharp@v0.28.3/docs/README.md?X-OpenDNS-Session=_3d1398140012f049a0096e0054dce6d1b9ca9270fa56_Yy369de0_ (“connect-src”).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn.jsdelivr.net/gh/lovell/sharp@v0.28.3/docs/README.md. (Reason: CORS request did not succeed).

Content Security Policy: The page’s settings blocked the loading of a resource at https://cdn.jsdelivr.net.x.9ada86190a99104208091bf0898c955b1459.9270fa5c.id.opendns.com/s/cdn.jsdelivr.net/gh/lovell/sharp@master/docs/image/sharp-logo.svg?X-OpenDNS-Session=_9ada86190a99104208091bf0898c955b14599270fa5c_S8WbeOD6_ (“img-src”).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn.jsdelivr.net/gh/lovell/sharp@master/docs/image/sharp-logo.svg. (Reason: CORS request did not succeed).

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.`

**Comment by lovell** [comment]
It looks like you're using some kind of OpenDNS-based web proxy that is intercepting and rewriting HTML.

The Content Security Policy in the sharp docs prevents "man in the middle" attacks from unknown URLs, which is what OpenDNS is effectively doing here with its random `*.id.opendns.com` hostnames.

https://github.com/lovell/sharp/blob/9f384e1c6c111bd98119d567a846c635f9ebbd59/docs/index.html#L8-L13

**Comment by ghankerson** [comment]
More likely our corporate custom certificate but point taken. Thanks - not sure what the resolution is here or if there is one but thanks for providing an explanation. 

I'll use wayback machine as a workaround

**Comment by m0jimo** [comment]
I can confirm that the problem is still active when accessing from our corporation

**Comment by lovell** [comment]
Commit https://github.com/lovell/sharp/commit/7467fa8b50d280780dfa9fe9a7248deaa499c7a1 reduces the reliance on jsdelivr, which should help with some corporate web proxies. I've re-published the docs with this change, although you may have to wait up to 24 hours for CDN caches to clear.
