### ISSUE TITLE
Can't install in NodeJs 4+ environment

### ISSUE THREAD

**Issue by giyyapan** [lovell/sharp#274]
I upgraded my nodejs to 4.1.1, but my application won't start.
In one of my environments it gives me a `segment fault`, and in another it tells me something's wrong with sharp. When I disabled sharp, my app works.

And I guess I need to upgrade sharp too, but `npm install sharp` failed.
here is my `$ vips -v`
```
vips-7.42.0-Thu Dec 11 17:35:58 CST 2014
```
and `$ pkg-config --print-provides vips`
```
vips = 7.42.0
```
and `$ npm install --verbose sharp` is here: https://gist.github.com/giyyapan/49e87b756b2d74d6f1e0

Additionally,  I've test this issue in two different machine and both node 4.0.0 and 4.1.1.

I've got stuck here for a while , Please help me :)
(and sorry for my poor English :p )

**Comment by lovell** [comment]
Hello, it looks like you're trying to install v0.9.3. For Node v4 support you'll need v0.11.2+.

http://sharp.dimens.io/en/stable/changelog/

**Comment by giyyapan** [comment]
Wow! super fast reply! 
It works great with v.0.11.3, thanks a looooooot! 

I wrote `"sharp": "^0.9.3"` in my package.json, and thought it will match the latest version, how silly! lol

Thanks for saving my ass again, cheers!

close now~
