### ISSUE TITLE
Best way to crop around a specified focal point

### ISSUE THREAD

**Issue by MaximilianLloyd** [lovell/sharp#2740]
I am trying to resize an image around a face. I have used another package to extract the bounding boxes of faces within the image. How could I use that position to correctly resize the image around it?

The only way I can see how to set it up with sharp is to set up a bunch of if statements to map it to one of the following alignment strategies.
![image](https://user-images.githubusercontent.com/10583205/120482309-4b9adc80-c3b1-11eb-8487-80c8c3a7e275.png)

**Comment by lovell** [comment]
Hi, did you see the `extract` operation? https://sharp.pixelplumbing.com/api-resize#extract

**Comment by MaximilianLloyd** [comment]
Thanks for the fast response :). Yes, but I'm not sure how I would go about using that in the usecase I outlined. The specific reason I ask is that I am cropping an input image to x number of output images with different ratios. The face should fit as best as possible inside all of the images outputted. One could be 4:3, the other 16:9. How could I go about using the extract operation to do this?

**Comment by lovell** [comment]
@MaximilianLloyd Were you able to make any progress with this? If not, please can you provide sample code and images to help explain your question.

**Comment by MaximilianLloyd** [comment]
> @MaximilianLloyd Were you able to make any progress with this? If not, please can you provide sample code and images to help explain your question.

Hi Lovell. No I wasn't able to make any progress with this. What I opted for was to just use the alignment strategies based on where the bounding box for the face was. But that solution is not optimal and I haven't implemented anything for the y axis yet. 

The user uploads an image that can be outputed in x amount of cropping formats, for example 5. I run facial recognition on the uploaded image and get the bounding boxes of the face. Based on that I want to make sure that the face is centered as much as possible in each of the different formats. Below you can find the relevant code and an example of the output. 

The config.formats contains an image which is a PNG overlay this is composited.

`router.js`
```js
import express from 'express';
import multer from 'multer';
import { fileURLToPath } from 'url';
import path from 'path';
import Sharp from 'sharp';
import { v4 as uuidv4 } from 'uuid';
import fs from 'fs';
import archiver from 'archiver';
import tf from '@tensorflow/tfjs-node';
import * as faceapi from '@vladmandic/face-api';
import * as canvas from 'canvas';
import makeDir from 'make-dir';
import slugify from 'slugify';

import { storage, imageFilter } from '../config/multer.js';
import setConnectionTimeout from '../middleware/timeout.js';
import getAlignmentStrategy from '../helpers/getAlignmentStrategy.js';
import getConfigFromSlug from '../helpers/getConfigFromSlug.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const upload = multer({ storage: storage, fileFilter: imageFilter });
const router = express.Router();

export async function init() {
  const { Canvas, Image, ImageData } = canvas;
  faceapi.env.monkeyPatch({ Canvas, Image, ImageData });

  await faceapi.nets.ssdMobilenetv1.loadFromDisk(
    path.resolve(__dirname, '../assets/models')
  );
}

async function processImage(file, config) {
  const { buffer } = file;
  const sharpImage = Sharp(buffer);
  const imageMetaData = await sharpImage.metadata();
  console.log(config);
  console.log('fit: ', config.useFacialRecognition);

  const { useFacialRecognition } = config;

  let detection;

  if (useFacialRecognition) {
    const tfBuffer = await sharpImage.jpeg().toBuffer();
    const img = tf.node.decodeImage(tfBuffer);
    const [_detection] = await faceapi.detectAllFaces(img);
    detection = _detection;
  }

  const imagesToReturn = config.formats.map(async (format, formatIndex) => {
    const overlay = format.image;

    const overlayMetaData = await overlay.metadata();
    const { width: overlayWidth, height: overlayHeight } = overlayMetaData;

    const clonedImage = sharpImage.clone();

    let alignmentStrategy = config.position;

    if (useFacialRecognition === true) {
      alignmentStrategy = getAlignmentStrategy(
        detection,
        imageMetaData,
        overlayMetaData
      );
    }

    clonedImage
    .rotate()
    .resize({
      height: overlayHeight,
      width: overlayWidth,
      fit: config.fit,
      position: alignmentStrategy,
    });

    clonedImage.composite([
      {
        input: await overlay.toBuffer(),
      },
    ]);

    return clonedImage.jpeg({
      quality: 95,
      chromaSubsampling: '4:4:4',
    });
  });

  return await Promise.all(imagesToReturn);
}

router.post(
  '/api/upload',
  setConnectionTimeout('1h'),
  upload.array('images'),
  async (req, res) => {
    const { configSlug } = req.body;

    const fetchedConfig = await getConfigFromSlug(configSlug);

    const imagesPerOverlay = await Promise.all(
      req.files.map((file) => processImage(file, fetchedConfig))
    );

    const imageNames = req.files.map((file) => file.originalname);
    const zipFileName = `${uuidv4()}.zip`;

    const output = fs.createWriteStream(
      path.resolve(__dirname, `../uploads/${zipFileName}`)
    );
    const archive = archiver('zip', {
      zlib: { level: 9 },
    });

    archive.pipe(output);

    for (const [formatIndex, images] of imagesPerOverlay.entries()) {
      const imageName = imageNames[formatIndex];

      for (const [index, image] of images.entries()) {
        const format = fetchedConfig.formats[index];
        const bufferData = await image.toBuffer();

        const folderPath = format.title;

        archive.append(bufferData, {
          name: `${fetchedConfig.title}/${folderPath}/${folderPath}_${imageName}`,
        });
      }
    }

    archive.finalize();

    res.status(200).send(zipFileName);
  }
);


router.post(
  '/api/upload-single',
  setConnectionTimeout('1h'),
  upload.single('image'),
  async (req, res) => {
    const { configSlug } = req.body;

    const fetchedConfig = await getConfigFromSlug(configSlug);
    const sharpImages = await processImage(req.file, fetchedConfig);

    const generatedDirectoryName = uuidv4();

    const rootPath = path.resolve(__dirname, `../uploads/${generatedDirectoryName}`);
    await makeDir(rootPath);

    for (const [index, image] of sharpImages.entries()) {
      const format = fetchedConfig.formats[index].title;

      const fileName = `${slugify(format)}.jpg`
      await image.toFile(`${rootPath}/${fileName}`);
    }

    res.status(200).send(generatedDirectoryName);
  }
);

export default router;
```


`getAlignmentStrategy.js`
```js
import Sharp from 'sharp';

function getAlignmentStrategy(detection, imageMetaData, overlayMetaData) {
  if (!detection) {
    console.log('No detection');
    return Sharp.strategy.attention;
  }

  const { width: overlayWidth, height: overlayHeight } = overlayMetaData;
  const { width: imageWidth, height: imageHeight } = imageMetaData;

  const xScalar = imageWidth / overlayWidth;
  const yScalar = imageWidth / overlayHeight;

  // scaled to overlay
  const x = detection.box._x * xScalar;
  const y = detection.box._y * yScalar;

  const imageCenter = overlayWidth / 2;
  const oneThirdOfImageWidth = overlayWidth / 3;

  if (Math.abs(imageCenter - x) < oneThirdOfImageWidth) {
    return 'center';
  }

  if (x < imageCenter) {
    return 'left'
  }

  if (x > imageCenter) {
    return 'right'
  }
}

export default getAlignmentStrategy;

```

![2021-07-28-12-28-demo batcher io](https://user-images.githubusercontent.com/10583205/127307740-3e885d86-f497-4fa9-805c-e9e8b3a27230.png)

**Comment by lovell** [comment]
Closing as this logic is custom to a particular use case, and sharp already provides enough API to achieve what's required.

**Comment by Tummerhore** [comment]
Just dropping by to say that I also would love to see inbuilt focal point support for image resizing and I think it's a common use case.

For everyone interested on how you could realize this right now: This is how I would probably do it:

![Rastergrafik](https://user-images.githubusercontent.com/45203603/195951989-4e609754-9464-4929-8504-58121565d852.png)

1. Scale (with `fit=cover`) the original image (green) to the needed size (yellow) by factor x so that it covers the requested dimensions (red dashed)
2. Also scale the focal point coordinates by factor x.
3. Calculate the corner coordinates of the result rectangle if it would be aligned to the scaled focal point at its center
4. The calculated coordinates may be out of bounds from the scaled image. So you have to shift them a minimal amount (differences of edge coordinates) until all of them are valid again.
5. Use the `extract` operation with the shifted corner coordinates on the scaled image.

**Comment by Tummerhore** [comment]
Sorry for the late reply @JeanLucEsser. I don't have any code for it right now but it should be straight forward if you follow my previous post. Maybe I find some time on the weekend to put something together.

**Comment by JessChowdhury** [comment]
+1 for adding focal point or custom alignment options

**Comment by thomas4Bitcraft** [comment]
+1 as a lot of other image services already provide this feature by now

**Comment by lovell** [comment]
If anyone would like to work on a PR for this, please open a new enhancement issue first with a proposed API as well as a list of edge cases that will need to be catered for (and tested).

**Comment by leevigraham** [comment]
Prior work: 

* Imgix: https://docs.imgix.com/apis/rendering/focalpoint-crop
* CraftCMS: https://craftcms.com/docs/4.x/assets.html#focal-points

**Comment by codeflorist** [comment]
Here is a function, that should be able to calculate the parameters for the `extract` function with stated original image dimensions, requested dimensions and focal point coordinates.

The function assumes, that the requested width and height fit inside the image width/height, meaning either the width or the height values are equal. So it's built to only crop either width or height, not both. You might have to add additional calculations, if you want to crop both width and height.

Focal points are assumed to be pixel coordinates of the image dimensions. So if the focal point is stated as percentage or relative values, you will need to convert it to pixel values.

```js
type GetExtractParamsFunction = (
    imageWidth: number,
    imageHeight: number,
    requestedWidth: number,
    requestedHeight: number,
    focalPointX: number,
    focalPointY: number
) => { left: number, top: number, width: number, height: number } | undefined

const getExtractParams: GetExtractParamsFunction = (
    imageWidth,
    imageHeight,
    requestedWidth,
    requestedHeight,
    focalPointX,
    focalPointY
) => {

    // First we get the ratios of width and height.
    const widthRatio = imageWidth / requestedWidth
    const heightRatio = imageHeight / requestedHeight

    // If both ratios are equal, nothing has to be cropped.
    // So we return undefined to signal no extraction has to take place.
    if (widthRatio === heightRatio) {
        return undefined
    }

    // If the width ratio is larger, we have to crop the width.
    // If the height ratio is larger, we have to crop the height .
    const cropWidth = widthRatio > heightRatio

    // Calculate the extract dimensions based on the crop ratio.
    const extractWidth = Math.round(cropWidth ? requestedWidth * heightRatio : imageWidth)
    const extractHeight = Math.round(cropWidth ? imageHeight : requestedHeight * widthRatio)

    // Calculate the top and left position of the crop area around the focal point.
    let extractLeft = cropWidth ? (focalPointX - (extractWidth / 2)) : 0
    let extractTop = cropWidth ? 0 : (focalPointY - (extractHeight / 2))

    // If the crop area is outside the original image dimensions, we have to adjust it to 0.
    extractLeft = Math.max(0, extractLeft)
    extractTop = Math.max(0, extractTop)

    // Now we return the calculated values to be fed into the extract function.
    return { left: extractLeft, top: extractTop, width: extractWidth, height: extractHeight }
}
```

A proposition for an API to include such a functionality in the `sharp` library would be to allow an alternative option-object for the `extract` function, that states the focal-coordinates instead of `left` and `top`:

```js
extract({ focusX: focusX, focusY: focusY, width: width, height: height })
```

For this, the possibility to crop both width and height has to be added to the function above, since it accounts only for cropping either width or height.
