### ISSUE TITLE
Image resize/crop specifying X and Y coordinates..?

### ISSUE THREAD

**Issue by HeCorr** [lovell/sharp#2742]
### What are you trying to achieve?
I'm trying to migrate from Jimp to Sharp as it's a lot faster but my current code does some math to find the correct cropping location and dimensions (x, y, w, h), but it seems that I cannot provide X and Y locations with Sharp..?

### Have you searched for similar questions?
Yes.

### Are you able to provide a minimal, standalone code sample that demonstrates this question?
The relevant Jimp code:
```ts
    // i = Jimp image loaded from a Base64 string
    // size = object specifying the crop dimensions
    const iw = i.getWidth()
    const ih = i.getHeight()
    
    let x = (cropData.pointF.x) - (size.w / 2)
    let y = (cropData.pointF.y) - (size.h / 2)
    
    // normalize coords to avoid cropping beyond the image bounds
    x = x + size.w > iw ? iw - size.w : x
    x = x < 0 ? 0 : x
    y = y + size.h > ih ? ih - size.h : y
    y = y < 0 ? 0 : y
    
    i.crop(x, y, size.w, size.h) // <-- I need X and Y in order to crop in the correct location
```

### Are you able to provide a sample image that helps explain the question?
Example of where it would crop:

![image](https://user-images.githubusercontent.com/75134774/120519946-99abe200-c3a9-11eb-9e76-4e0f6ab9085c.png)

**Comment by HeCorr** [comment]
Nevermind. `extract` is probably what I want but after hours trying to debug an installation error I learned that this package won't work alongside `canvas`.

You guys really should put that somewhere in the readme....

**Comment by lovell** [comment]
Glad you worked it out.

The problem with Windows and `canvas` is documented at https://sharp.pixelplumbing.com/install#known-conflicts

If you're processing untrusted user input on a Windows machine then I would strongly recommend `canvas` is not used.

**Comment by HeCorr** [comment]
I have a question. The doc says "These conflict with the modern, up-to-date binaries provided by sharp."

Is it possible for me to use those up-to-date binaries so I can use both canvas and sharp?

**Comment by lovell** [comment]
As far as I'm aware, canvas has a dependency on the version of cairo provided by GTK2.

https://github.com/Automattic/node-canvas/wiki/Installation%3A-Windows

Perhaps ask on the node-canvas repo if there's a way for it to use more recent dependencies on Windows?

**Comment by HeCorr** [comment]
Alright, thanks!  :)
