### ISSUE TITLE
Electron-Angular (electron-packager) run time error "Something went wrong installing "sharp" module"

### ISSUE THREAD

**Issue by sneaker102** [lovell/sharp#2744]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?
Yes

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?
I use electron-rebuild for this.
https://www.npmjs.com/package/electron-rebuild

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

npm ls sharp => sharp@0.28.3 
npm view sharp dist-tags.latest => 0.28.3

electron:  12.0.1,
electron-packager:  15.2.0,
electron-rebuild:  2.3.5

What is the output of running `npx envinfo --binaries --system`?
 System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
    Memory: 2.22 GB / 7.93 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD

**STEPS**
npm i sharp => success
.\node_modules\.bin\electron-rebuild.cmd => success (rebuild sharp module)
npm run build-win => success (via electron-packager)

run app =>
![image](https://user-images.githubusercontent.com/45992275/120895208-cc83ef00-c5d0-11eb-9c69-21a8df37ed51.png)

**PROJECT STRUCTURE**
![image](https://user-images.githubusercontent.com/45992275/120895280-153ba800-c5d1-11eb-8621-b04ffd2649b3.png)

**DEV MODE**
ng build --base-href ./ && electron .  => app runs as expected.

**Comment by lovell** [comment]
You probably don't need to use `electron-rebuild` as the interface between sharp and Electron uses Node-API (N-API) rather than the older Node.js/V8 APIs.

If you're still having a problem, please can you provide a complete, standalone, minimal repo that allows someone else to reproduce it.
