### ISSUE TITLE
How to produce a composited PNG with an alpha layer but "flattened" 

### ISSUE THREAD

**Issue by jblanche** [lovell/sharp#2750]
What are you trying to achieve?

I'm wondering if there's a way to manipulate pixels with Sharp so that every pixel with an alpha 0 is replaced with another pixel (keeping the alpha layer). 
aka going from 
![image](https://user-images.githubusercontent.com/11636/121507079-9ab1c480-c9e4-11eb-8c00-987169a83cc7.png)
to 
![image](https://user-images.githubusercontent.com/11636/121507369-dba9d900-c9e4-11eb-8885-bf2fd18901ba.png)

But with the same display as the pixels that changed have a 0 alpha. 

Have you searched for similar questions?

Yes, but noticed that flatten / remove_alpha completely removes the alpha layer is my understanding is correct.

**Comment by lovell** [comment]
Did you see the `blend` option of the `composite` operation? I think `dest-in` (or `in`, depending on the image order) would be appropriate for this scenario.

https://sharp.pixelplumbing.com/api-composite#composite

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
