### ISSUE TITLE
resize animated gif to animated webp not working

### ISSUE THREAD

**Issue by jyp85** [lovell/sharp#2752]
hi i have a question

i want to resize animated gif to animated webp with cover fit.

the original size is 320x446 and has 13 pages.

target size is 200x200 and has 13 pages.

i expect each frame size 200x200.

but each frame is not resized.

animated image cannot resize to different ratio?

please help me

const { pages } = await sharp(inDataBody, {animated: true, pages: -1}).metadata()
const outData = sharp(inDataBody, {animated: true, pages:-1} )
      .resize(width, height * pages, {
        fit: sharp.fit.cover,
        withoutEnlargement: true,
      });

outData.webp({ quality, pageHeight: height * pages
 }).toBuffer();

original image
![original](https://user-images.githubusercontent.com/73812770/121636467-ee92db00-cac2-11eb-8e77-c215b0857d22.gif)

result image animated with weired image
<img width="162" alt="스크린샷 2021-06-11 오후 10 23 41" src="https://user-images.githubusercontent.com/73812770/121693231-e6a75b00-cb03-11eb-9b2a-9d3fb1a626a9.png">
<img width="169" alt="스크린샷 2021-06-11 오후 10 25 46" src="https://user-images.githubusercontent.com/73812770/121693344-03439300-cb04-11eb-8aa3-4448568d18e7.png">

**Comment by lovell** [comment]
> the original size is 320x446 and has 13 pages.
> target size is 200x200 and has 13 pages.

Hi, it's not possible to crop animated images.

There's a future possible enhancement to make resizing animated images easier at https://github.com/lovell/sharp/issues/2275

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
