### ISSUE TITLE
/usr/include/vips/vips8:35:10: fatal error: glib-object.h: No such file or directory

### ISSUE THREAD

**Issue by WeebHiroyuki** [lovell/sharp#2753]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?
Yes.

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?
Yes.

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
Yes.

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7, does the user running `npm install` own the directory it is run in?
Yes.

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?
Yes.

What is the output of running `npx envinfo --binaries --system`?
```
  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (2) x64 Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz
    Memory: 2.40 GB / 3.85 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 16.3.0 - /usr/bin/node
    npm: 7.15.1 - /usr/bin/npm
```

# Overview

I have installed `libvips-dev`, and all of its dependencies have been met, including `libglib2.0-dev`. `/usr/include/glib-2.0/glib-object.h` also does exist. The error log/transcript is available on https://pastebin.com/mkW3Tr3D.

**Comment by WeebHiroyuki** [comment]
I was able to install sharp by downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linux-x64.tar.gz, unarchiving it, and then moving it into `~/.npm/_libvips`. Any reason the globally installed version doesn't work though?

**Comment by WeebHiroyuki** [comment]
I'm trying to install the dependencies for [Zeppelin](https://github.com/Dragory/ZeppelinBot) (see `npm ci` for the backend folder on the README). One thing to note is that `npm ci` doesn't work, but `npm i` does.

**Comment by lovell** [comment]
Please can you submit a PR to ZeppelinBot to upgrade sharp.

https://github.com/Dragory/ZeppelinBot/blob/f19e365bf630c126ef7242534a120cb449c8ee60/backend/package.json#L62

**Comment by WeebHiroyuki** [comment]
Ah I see. sharp was outdated. Could that have been the reason for all of this then?

**Comment by WeebHiroyuki** [comment]
One other thing to note when installing sharp: with Node.js _version 16.3.0_, it fails to compile some code. A full error log can be found  here. https://pastebin.com/dWFktzWP

**Comment by WeebHiroyuki** [comment]
I tested installation with Node.js v15.5.0 and it compiles perfectly.

**Comment by danielehrhardt** [comment]
I spend all night try to solve this :(

**Comment by lovell** [comment]
@danielehrhardt If you're still having problems, please open a new installation issue and answer all of the questions. https://github.com/lovell/sharp/issues/new?assignees=&labels=installation&template=installation.md
