### ISSUE TITLE
VipsOperation: class "heifsave_buffer" not found

### ISSUE THREAD

**Issue by kuba-orlik** [lovell/sharp#2754]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`? yes

What are the steps to reproduce? 

```ts
sharp(`path/to/file`).resize(200).toFormat("avif").toBuffer();
```
Then, observe error: `[Error: VipsOperation: class "heifsave_buffer" not found]`

What is the expected behaviour?

No error

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

I've tried very hard to do so, but I can't reproduce it in an isolated case. I've tried doing that on the same machine and using the same node_modules folder, but failed to reproduce it in an isolated case. I'd be thankful for tips on what else I can throw at it

Are you able to provide a sample image that helps explain the problem? No

What is the output of running `npx envinfo --binaries --system`?

```
  System:
    OS: Linux 5.9 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
    Memory: 1.67 GB / 15.45 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.1.0 - /usr/bin/node
    npm: 7.12.1 - /usr/bin/npm
```

**Comment by kuba-orlik** [comment]
Ok, I've resolved the issue, although I can't quite tell if it was a bug or not.

My project used two dependencies that used different versions of `sharp`. Hotfixing them so they use the same version solved the issue.

The thing is, I've tested avif in both versions separately and neither produced this issue. It seems the issue only appears if there are two dependencies using sharp in different versions

**Comment by lovell** [comment]
When using the prebuilt binaries, versions of sharp from v0.28.0 onwards can be mixed, but prior to that it was possible to run into this kind of problem.

The fix for this was https://github.com/lovell/sharp-libvips/pull/81

**Comment by kuba-orlik** [comment]
That explains it all. Thanks!

**Comment by At4m4n** [comment]
Hey @lovell. Not sure if it's me doing something wrong, but I still get this error, having the latest current versions of `sharp 0.28.3` and `libvips 8.11.2` (with the rest of compulsory dependencies). Maybe the issue is somehow related to AWS Lambda where I try to setup everything, but I don't have straight evidence yet. 

So, I have Makefile to customize nodejs12 environment with libvips and sharp. The javascript code uses sharp to resize heic image on this runtime and receives this:
`source: bad seek to 1495988, "VipsOperation: class \"heifsave_buffer\" not found"`
Makefile:

```
WEBP_VERSION=1.2.0
LIBDE265_VERSION=1.0.8
LIBHEIF_VERSION=1.12.0
VIPS_VERSION=8.11.2
SHARP_VERSION=0.25.1

PREFIX_PATH=/opt

export PKG_CONFIG_PATH=$(PREFIX_PATH)/lib/pkgconfig

build-SharpHEICLayer: libvips
	mkdir -p "$(ARTIFACTS_DIR)/nodejs"
	mkdir -p "$(ARTIFACTS_DIR)/lib"

	LD_LIBRARY_PATH=$(PREFIX_PATH)/lib npm --prefix "$(ARTIFACTS_DIR)/nodejs/" install sharp@$(SHARP_VERSION)
	ldd $(ARTIFACTS_DIR)/nodejs/node_modules/sharp/build/Release/sharp.node | sed -nE "s/^[^\/\n]*(\/[^ ]+)(.*)/\1/p" | xargs cp -t $(ARTIFACTS_DIR)/lib

libde265:
	# libde265
	curl -L https://github.com/strukturag/libde265/releases/download/v$(LIBDE265_VERSION)/libde265-$(LIBDE265_VERSION).tar.gz | tar zx
	cd libde265-$(LIBDE265_VERSION) && ./autogen.sh && ./configure --disable-dec265 --disable-sherlock265 --prefix=$(PREFIX_PATH) && make V=1 && make install

libheif: libde265
	# libheif
	curl -L https://github.com/strukturag/libheif/releases/download/v$(LIBHEIF_VERSION)/libheif-$(LIBHEIF_VERSION).tar.gz | tar zx
	cd libheif-$(LIBHEIF_VERSION) && ./autogen.sh && ./configure --prefix=$(PREFIX_PATH) && make V=1 && make install

libvips: installLib libheif
	# libvips
	curl -L https://github.com/libvips/libvips/releases/download/v$(VIPS_VERSION)/vips-$(VIPS_VERSION).tar.gz | tar zx
	cd vips-$(VIPS_VERSION) && ./configure --prefix=$(PREFIX_PATH) && make V=1 && make install

installLib:
	yum install -y \
		glib2-devel \
		expat-devel \
		lcms2-devel \
		libjpeg-devel \
		libjpeg-turbo-devel \
		libpng-devel \
		giflib-devel \
		libexif-devel \
		librsvg2-devel \
		libtiff-devel
```
I run it locally with `sam local invoke` if it's important.

**Comment by lovell** [comment]
@At4m4n Please open a new issue and provide complete steps to allow someone else to reproduce this, e.g. via a Dockerfile.
