### ISSUE TITLE
Installation of Sharp removes pdfkit and vice versa

### ISSUE THREAD

**Issue by nilachandan** [lovell/sharp#2755]
To be very strange, both sharp and pdfkit is running fine with Node JS in my windows development machine. But when I'm trying to install it in my production machine which is an Ubuntu machine resides in AWS, it removes the already installed Sharp. But then If I try to first install pdfkit its installs. But as soon as I install sharp, it removes pdfkit. I don't what's happening here? I have asked the same question in pdfkit forum. Awaiting for their response.

My npm version is 6.14 at AWS.

**Comment by lovell** [comment]
Please can you provide a minimal, standalone code repository that allows someone else to reproduce this.

Cross-posted at https://github.com/foliojs/pdfkit/issues/1263

**Comment by nilachandan** [comment]
It is nothing to do with code repository, as the problem with its installation and that too in AWS production server. Otherwise, it installation is fine with my development server which is an windows machine.

**Comment by nilachandan** [comment]
While installing Sharp with npm install --verbose sharp, I found out this information. "npm info lifecycle pdfkit@0.12.1~preuninstall: pdfkit@0.12.1
npm info lifecycle pdfkit@0.12.1~uninstall: pdfkit@0.12.1". It clearly states that while installing the sharp package, its uninstalls pdfkit. Now the question is why? and will you be able to solve the issue?

**Comment by lovell** [comment]
https://npm.community/t/npm-removes-packages-on-install/9432

This is unrelated to either sharp or pdfkit.

**Comment by nilachandan** [comment]
Any idea, on how to possibly solve this issue. If you were in my position, how to make it possible to install both the pdfkit and sharp?

**Comment by lovell** [comment]
Did you try the suggestions e.g. `--no-package-lock` discussed in https://npm.community/t/npm-removes-packages-on-install/9432?
