### ISSUE TITLE
Blur section of image with polygon

### ISSUE THREAD

**Issue by Asheboy** [lovell/sharp#2756]
## What are you trying to achieve?
Blur a section of an image from polygon coordinates. I can successfully achieve this with the `rectangle` function, but that only supports rectangles.

## Have you searched for similar questions?
Only similar issue I can find is https://github.com/lovell/sharp/issues/2198

## Are you able to provide a sample image that helps explain the question?
Input:
![car](https://user-images.githubusercontent.com/1822529/122100309-f1673600-ce0a-11eb-98b2-f134fe92fd6b.jpg)

Output, but want to be able to use any shape polygon:
![car-blurred](https://user-images.githubusercontent.com/1822529/122100138-bfee6a80-ce0a-11eb-9b95-c5c45240bad0.jpg)

**Comment by lovell** [comment]
Perhaps try to see if you can achieve what you need using only SVG first.

For example, add the input as a base64-encoded image, create the shape you need as a mask then apply a blur to it.

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feGaussianBlur

**Comment by Asheboy** [comment]
@lovell Here's my attempt, which I would have thought would work, but perhaps sharp doesn't handle the SVG correctly?

Same input image used as in my initial post.

Code:

```
const sharp = require('sharp')
const fs = require('fs')
const image = fs.readFileSync('/tmp/car.jpg')
const mask = Buffer.from(
  `<svg height="2000" width="3000">
    <clipPath id="mask">
    <polygon points="2441,968 2630,968 2630,1050 2441,1050" />
    </clipPath>
    <image id="image" clip-path="url(#mask)" href="data:image/jpeg;charset=utf-8;base64,${image.toString('base64')}" />
  </svg>`)

fs.writeFileSync('/tmp/mask.html', mask)

sharp(mask)
  .png()
  .toBuffer({ resolveWithObject: true }, (err, mask) => {
    fs.writeFileSync('/tmp/mask.png', mask)
  })

sharp(mask)
  .blur(15)
  .toBuffer({ resolveWithObject: true }, (err, blur) => {
    fs.writeFileSync('/tmp/blur.png', blur)

    sharp(image)
      .composite([{ input: blur }])
      .toBuffer({ resolveWithObject: true }, (err, output) => {
        fs.writeFileSync('/tmp/out.jpg', output)
      })
  })
```

Output files:

mask.html - generates correctly masked image - https://replit.com/@AshSummers/VioletOffensiveCron#index.html - you need to scroll down and to the right to see the image.
mask.png - a fully transparent image - ![mask](https://user-images.githubusercontent.com/1822529/122208242-f83d8980-ce9a-11eb-9a67-7d31aedd53b2.png)
blur.png - a fully transparent image - ![blur](https://user-images.githubusercontent.com/1822529/122208274-01c6f180-ce9b-11eb-97c8-afb1687dca53.png)
out.jpg - same as input image - ![out](https://user-images.githubusercontent.com/1822529/122208298-09869600-ce9b-11eb-8f6c-ae7ecfb735a1.jpg)

**Comment by Asheboy** [comment]
I've also tried the following, with the same results.

```

**Comment by Asheboy** [comment]
I come with the answers! the `<image>`s needed weight and height properties, as well as removing `charset=utf-8` from the `href`.
