### ISSUE TITLE
perf: input buffer 2.7x slower than file path

### ISSUE THREAD

**Issue by Flam3rboy** [lovell/sharp#2761]
If a buffer is passed as an input to sharp its 2.7x times slower than passing a path to a file.

I'm currently bypassing this issue by writing the buffer to a file and passing the path, but is there any other way for improving the performance of input buffers?

## Example
```js
const sharp = require("sharp")
const fs = require("fs")

// svg -> png (fs)
await sharp(fs.readFileSync("example.svg")).png().toBuffer()

// svg -> png (path)
await sharp("example.svg").png().toBuffer()
```

## Benchmark:
![image](https://user-images.githubusercontent.com/34555296/122685691-4f31be80-d20d-11eb-8faa-0c318ed581dc.png)

### Environment:
- System:
	- OS: macOS 10.15.7
	- CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
	- Memory: 377.67 MB / 16.00 GB
	- Shell: 5.7.1 - /bin/zsh-
- Binaries:
	- Node: 15.8.0 - /usr/local/bin/node
	- Yarn: 1.22.10 - /usr/local/bin/yarn
	- npm: 7.15.1 - /usr/local/bin/npm
	- Watchman: 4.9.0 - /usr/local/bin/watchman

**Comment by lovell** [comment]
Hi this looks like the effects of libvips' file cache.

If you disable this via a call to `sharp.cache(false)`, you should see more even results.

See https://sharp.pixelplumbing.com/api-utility#cache for more information.

**Comment by Flam3rboy** [comment]
Yes 😄 thank you, if I disable the cache I get nearly the same result.
Do you have any idea how to improve the performance of converting a svg to a png?
