### ISSUE TITLE
Warnings printed when using a SVG with 0 width or height

### ISSUE THREAD

**Issue by HKGx** [lovell/sharp#2766]
**Are you using the latest version?**
 yes

**What are the steps to reproduce?**
https://github.com/HKGx/rendertex/issues/2
1. Used MathJax to get SVG generated for `%5C`. The outputted SVG should be like 0x0
2. Putting that SVG as a buffer to `sharp` logs
```
(sharp:24296): GLib-GObject-WARNING **: 23:51:19.397: value "0" of type 'gint' is invalid or out of range for property 'width' of type 'gint'  
```

**What is the expected behaviour?**
No warnings outputted directly from sharp binaries. Maybe it should throw an error?

**Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?**

```js
import sharp from "sharp";
const svg = `<svg></svg>`;
sharp(Buffer.from(svg)).toBuffer()
```

Though it shows even more logs than my case

What is the output of running `npx envinfo --binaries --system`?
```
  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz
    Memory: 18.63 GB / 31.94 GB
  Binaries:
    Node: 16.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.8.0 - ~\node_modules\.bin\npm.CMD
````

**Comment by lovell** [comment]
Thanks for reporting, I've opened an upstream PR in libvips to improve the handling of this type of file - see https://github.com/libvips/libvips/pull/2318

**Comment by lovell** [comment]
v0.29.0 now available with this improvement.
