### ISSUE TITLE
Feature request: onlyScaleDown

### ISSUE THREAD

**Issue by andresribeiro** [lovell/sharp#2769]
In the resize function you could have the argument "onlyScaleDown", which would only resize the image to the passed values if the dimensions are above the passed ones.

For example, if you call the function resize(1920), but the image passed is 1280 width and 720 height, the image would not be resized

**Comment by lovell** [comment]
Hi, did you see the existing `withoutEnlargement` option?

https://sharp.pixelplumbing.com/api-resize#resize

**Comment by andresribeiro** [comment]
@lovell Sorry, I didn't see that 😅
