### ISSUE TITLE
watermark

### ISSUE THREAD

**Issue by slash-** [lovell/sharp#277]
i would like to use sharp library to put watermark on dynamic scaled pictures based on device resolution

i.e. watermark 100x80px
source picture 1920x1080px
resized source image 720x480px

with overlayWith function i would also have to scale the picture for watermark? or have to wait until https://github.com/lovell/sharp/issues/239 is improved to handle that correctly?

**Comment by lovell** [comment]
Hello, yes, it sounds like #239 should cover what you're looking for.

**Comment by lemnisk8** [comment]
Is it possible to tile/repeat image? Ruby-vips has an option for replicate image. It would be very useful for water marking with overlay with method.

**Comment by lovell** [comment]
@lemnisk8 I've added this to #239, thanks for the suggestion.

**Comment by lovell** [comment]
Closing this question as #239 should cover the requested feature - feel free to re-open if not.
