### ISSUE TITLE
Error: Input buffer contains unsupported image format 

### ISSUE THREAD

**Issue by SuppliedOrange** [lovell/sharp#2774]
I am getting the current error while trying to iterate through a loop of links of images. I'm using _sharp(buffered-link)_ and not directly using the request module as was the case in [930](https://github.com/lovell/sharp/issues/930).

```ts
let pfparray = ["https://i.imgur.com/KCskkMr.jpg" , "https://i.imgur.com/7KH3tBd.jpg" , "https://i.imgur.com/iDjptdL.jpg"]
 pfparray.forEach(link => {
             sharp(Buffer.from(link)) // encoding in utf-8
            .resize(100)
            .toBuffer()
            .then( data => { bufferArray.push(data) })
            .catch( err => { console.log(err + " | error!")});
        })
```
I may be missing something due to my lack of understanding of this function, but so far it shows no improvement. URL is a valid image. What could I be doing wrong?

Intended: Buffers images and executes accordingly
Actual: Throws following errors: 

```
Error: Input buffer contains unsupported image format | error!
Error: Input buffer contains unsupported image format | error!
Error: Input buffer contains unsupported image format | error!
```

**Comment by lovell** [comment]
You'll need to add your own networking logic. See #1901 for some examples.
