### ISSUE TITLE
PNG to JPEG: how to keep high quality

### ISSUE THREAD

**Issue by simon-tannai** [lovell/sharp#2776]
Hello ! 

I'm trying to convert PNG image buffer to a JPEG image buffer.
It's working but I have a quality loss when I'm displaying the JPEG from Buffer.

Here my simple code to convert PNG to JPEG:
```javascript
formatted = await sharp(pngImgBuffer)
      .toFormat('jpeg')
      .jpeg({ quality: 100, chromaSubsampling: '4:4:4', force: true })
      .toBuffer(); // JPEG buffer
```

And the reading part (with resize):
```javascript
resized = await sharp(jpegImgBuffer)
      .resize(width, height)
      .toFormat('jpeg')
      .jpeg({ quality: 100, chromaSubsampling: '4:4:4', force: true })
      .toBuffer();
```

Is there something wrong in my code ? Or something else to do to improve the quality of the result ?

**Comment by lovell** [comment]
PNG is a lossless format whereas JPEG is a lossy format, so you'll always lose some detail when encoding with the latter, even at maximum "quality".

(This applies to all software that creates JPEG images, not just sharp.)

**Comment by simon-tannai** [comment]
Many thanks @lovell  for your fast reply ! :) 

So, I suppose I have to keep the PNG format or switch to the WebP format if I want to keep a good image quality ?

**Comment by lovell** [comment]
If preventing any loss of original detail is important in your scenario, then yes, the use of PNG or lossless WebP will meet that need.

**Comment by simon-tannai** [comment]
Well, many thanks @lovell  👍
