### ISSUE TITLE
Resize after composite doesn't work

### ISSUE THREAD

**Issue by chrisdotn** [lovell/sharp#2778]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

Yes, 0.28.3

What are the steps to reproduce?

1. Create a sharp chain with a _composite_ step and a _resize_ step after the composite. (see below for an example)

```
  sharp({
    create: {
      width: 300,
      height: 200,
      channels: 3,
      background: { r: 66, g: 135, b: 245 },
    },
  })
    .composite([{
      input: {
        create: {
          width: 150,
          height: 100,
          channels: 4,
          background: { r: 245, g: 135, b: 35, alpha: 0.5 },
        },
      },
    }])
    .resize(100)
    .toFile('test.png')
    .then((info) => console.log(info))
    .catch((err) => console.error(err))
```

What is the expected behaviour?
The resize step is applied to the original (first) image only, whereas I was expecting it to be applied to the composed image. I was expecting the steps to happen like this: Create image -> add second image -> resize result to target size.

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
see above 

Are you able to provide a sample image that helps explain the problem?
see above

What is the output of running `npx envinfo --binaries --system`?
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 4.34 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    npm: 7.15.1 - /usr/local/bin/npm

**Comment by lovell** [comment]
Hello, did you see #1790 ?

**Comment by chrisdotn** [comment]
#1790 solves it.
