### ISSUE TITLE
Cannot download the Tar file from github

### ISSUE THREAD

**Issue by sayokbose91** [lovell/sharp#2779]
Hi,

I am using a win system for dev with node 14.0
when I try to install sharp...my company firewall blocks the tar file download from Github...

is there any override switch available if I want it to fetch it from a local source folder?

**Comment by lovell** [comment]
Please see https://sharp.pixelplumbing.com/install#custom-prebuilt-binaries

(The installation issue template, which was ignored/deleted, includes a link to this page.)

**Comment by cartok** [comment]
The page does not work

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
