### ISSUE TITLE
Error: VipsOperation: class "icc_transform" not found

### ISSUE THREAD

**Issue by misgina** [lovell/sharp#278]
Hi Lovell;

Thank you for the wonderful work.

I have been using sharp for the past couple of months and I am having some problem on some images. On my Centos 7 environment, I am getting the "Error: VipsOperation: class "icc_transform" not found" error (it happens when saving the process image to the a file), on jpg images on cmyk colorspace and with out icc profile. By the way i do not have this problem on my mac environment. Here is a sample image with this problem (which i took from some of the issues)
https://www.dropbox.com/s/026tppp744dmjbk/raw%20(7).jpg?dl=1.

Thanks

**Comment by lovell** [comment]
Hello, it looks like you've run into #206

**Comment by misgina** [comment]
Thanks for the quick reply. I will add the lcms and try again. I have used the script on the sharp homepage to install it though, that means it failed on installing lcms.

**Comment by lovell** [comment]
Ah ha, the package name in Centos 7 has changed to [lcms2-devel](http://pkgs.org/download/lcms2-devel) from [lcms-devel](https://github.com/lovell/sharp/blob/master/preinstall.sh#L250). Leave it with me.

**Comment by lovell** [comment]
The updated preinstall.sh script should now install the correct LittleCMS dependency on Centos 7. You'll probably need to remove any existing libvips installation first.

Centos 7 will be included in the upcoming Docker-based CI builds so this sort of problem should hopefully be detected sooner - thanks for reporting!

**Comment by misgina** [comment]
Thank you Lovell. It worked. Closing the issue.
