### ISSUE TITLE
Trying to get in touch with you regarding a security issue

### ISSUE THREAD

**Issue by huntr-helper** [lovell/sharp#2782]
Hi there,

I couldn't find a `SECURITY.md` in your repository and so am not sure how to best contact you privately to disclose the security issue.

Can you add a `SECURITY.md` file with your e-mail to your repository, so that I know who to contact? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, please let me know so I can ping you the info.

Thanks! (cc @JamieSlome)

**Comment by lovell** [comment]
If this is a genuine security question that cannot be shared publicly then please use email - see https://github.com/lovell/sharp/blob/master/package.json#L5

Given the @huntr-helper bot has posted the same message on many, many other repos I get the feeling this is spam-bot behaviour. If I don't hear anything by email in the next few days I'll report and block this user.

**Comment by JamieSlome** [comment]
@lovell - thanks for the prompt response!

You should receive an e-mail in the next hour including details about the vulnerability. I have sent this to:

`npm@lovell.info`

Let me know if you have any more questions!

**Comment by lovell** [comment]
Thanks for the email, I'm going to paste the summary here as it is a total non-issue.

> There is no sanity checks in the output file when using the library, if the output file is user controlled, users can overwrite files at any locations

This is like saying `fs.writeFile` in Node.js is vulnerable.

Please ensure a human checks these kinds of useless submissions before bots get involved.

**Comment by lovell** [comment]
I've now started receiving spam from Huntr.dev so you're blocked. Absolute waste of my time.
