### ISSUE TITLE
Getting "VipsOperation: class "heifsave_buffer" not found" on AWS Lambda custom runtime

### ISSUE THREAD

**Issue by At4m4n** [lovell/sharp#2783]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
 - yes, using sharp 0.28.3

What are the steps to reproduce?
Can't share complete templates and js handler code, but overall process is like this:
 1. Create lambda function (e.g. `sam init`)
 2. Reference custom lambda layer in the function template
 3. Specify `BuildMethod: makefile` for layer
 4. Use following Makefile to build layer
 ```
LIBDE265_VERSION=1.0.8
LIBHEIF_VERSION=1.12.0
VIPS_VERSION=8.11.2
SHARP_VERSION=0.28.3

PREFIX_PATH=/opt

export PKG_CONFIG_PATH=$(PREFIX_PATH)/lib/pkgconfig

build-SharpHEICLayer: libvips
	mkdir -p "$(ARTIFACTS_DIR)/nodejs"
	mkdir -p "$(ARTIFACTS_DIR)/lib"

	LD_LIBRARY_PATH=$(PREFIX_PATH)/lib npm --prefix "$(ARTIFACTS_DIR)/nodejs/" install sharp@$(SHARP_VERSION)
	ldd $(ARTIFACTS_DIR)/nodejs/node_modules/sharp/build/Release/sharp.node | sed -nE "s/^[^\/\n]*(\/[^ ]+)(.*)/\1/p" | xargs cp -t $(ARTIFACTS_DIR)/lib

libde265:
	curl -L https://github.com/strukturag/libde265/releases/download/v$(LIBDE265_VERSION)/libde265-$(LIBDE265_VERSION).tar.gz | tar zx
	cd libde265-$(LIBDE265_VERSION) && ./autogen.sh && ./configure --disable-dec265 --disable-sherlock265 --prefix=$(PREFIX_PATH) && make V=1 && make install

libheif: libde265
	curl -L https://github.com/strukturag/libheif/releases/download/v$(LIBHEIF_VERSION)/libheif-$(LIBHEIF_VERSION).tar.gz | tar zx
	cd libheif-$(LIBHEIF_VERSION) && ./autogen.sh && ./configure --prefix=$(PREFIX_PATH) && make V=1 && make install

libvips: installLib libheif
	curl -L https://github.com/libvips/libvips/releases/download/v$(VIPS_VERSION)/vips-$(VIPS_VERSION).tar.gz | tar zx
	cd vips-$(VIPS_VERSION) && ./configure --prefix=$(PREFIX_PATH) && make V=1 && make install
	echo $(vips --vips-config)

installLib:
	yum install -y \
		glib2-devel \
		expat-devel \
		x265-devel \
		lcms2-devel \
		libjpeg-devel \
		libjpeg-turbo-devel \
		libpng-devel \
		giflib-devel \
		libexif-devel \
		librsvg2-devel \
		libtiff-devel
 ```
 5. Invoke sharp .rotate or/and .resize on any .heic file in your code
 6. Build `sam build --use-container` and run lambda `sam local invoke -e <your_heic_event.json>`

What is the expected behaviour?
No errors, file processed sucessfully

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
```
let img = sharp(fileStream, {failOnError: false})
            .rotate(orientation)
            .resize(width, height, resizeOptions)
            .toColorspace(colorSpace);
            
            ...
            
return img.toBuffer();
```

Are you able to provide a sample image that helps explain the problem?

What is the output of running `npx envinfo --binaries --system`?
```
System:
    OS: Linux 5.4 Amazon Linux 2
    CPU: (4) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 1.26 GB / 6.79 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 12.22.1 - /var/lang/bin/node
    npm: 6.14.12 - /var/lang/bin/npm
```

**Comment by lovell** [comment]
Which HEIF encoder are you using? I don't see aom or x265 listed here.

**Comment by At4m4n** [comment]
> Which HEIF encoder are you using? I don't see aom or x265 listed here.

 I believe libheif is responsible for this

**Comment by lovell** [comment]
https://github.com/strukturag/libheif/blob/master/README.md

> Also install x265 and its development files if you want to use HEIF encoding.
> For AVIF support, make sure that libaom is installed.

**Comment by At4m4n** [comment]
Installed x265, but the error message remains the same

**Comment by lovell** [comment]
You'll need `x265-devel`.

**Comment by At4m4n** [comment]
@lovell Tried `x265-devel` (updated Makefile). Didn't help as well. 
I'll try to debug vips, maybe this it's not sharp-related

**Comment by At4m4n** [comment]
Vips installation [issue](https://github.com/libvips/libvips/discussions/2340)
