### ISSUE TITLE
How to use sharp in mac's universal app?

### ISSUE THREAD

**Issue by dogeFu** [lovell/sharp#2784]
What are you trying to achieve?
I want to use sharp in a universal app on mac OS.
Have you searched for similar questions?
yes
Are you able to provide a minimal, standalone code sample that demonstrates this question?
no
Are you able to provide a sample image that helps explain the question?
no

Hi,I want to use sharp in a universal app. A Universal App can support both apple m1 and intel device.I know that different platform needs different version of sharp. And I successfully supported two different platfrom.But I don't know how to put two version of sharp together when I pack two apps into a Universal App.
I use x64's version of sharp in the Universal App,then copy arm64's vendor directory to it.But it did not work.M1 mac can't find the proper libs.How can I support this?

**Comment by dogeFu** [comment]
I know what to do now.It's quiet easy. Just put two version of sharp together with a different name ,like sharp_arm,sharp_x64. then require the right one in you code.

`if ( isarm() ) require("sharp_arm")`

But it's better if the sharp can support different platform itself~

**Comment by lovell** [comment]
Please see #2575
