### ISSUE TITLE
Modifying raw pixel data in a pipeline

### ISSUE THREAD

**Issue by adriaanmeuris** [lovell/sharp#2785]
I'd like to change raw pixel data when using stream based input/output. I'm able to achieve the desired result when working with an underlying ArrayBuffer:

**Input: (RGBA image)**
![dices](https://user-images.githubusercontent.com/16230038/124718114-10d31980-df06-11eb-996c-f072fc805d35.png)

**Example output: (R-channel set to 255 for each opaque pixel)**
![dices2](https://user-images.githubusercontent.com/16230038/124718124-129cdd00-df06-11eb-81a8-7dcc7d63c436.png)

**Code**
```js
const { data, info } = await sharp('input.png').raw.toBuffer({ resolveWithObject: true });
const { width, height, channels, size } = info;
const arr = new Uint8ClampedArray(data.buffer);

for (let i = 0; i < size; i += 4) {
  if (arr[i + 3] === 255) arr[i] = 255;
}

await sharp(arr, { raw: { width, height, channels } }).toFile('output.png');
```

In this example, R is set to 255 for opaque pixels. This could be any other operation though, as long as the channel values of each single pixel are available in the loop - no access to other pixels is required.

Above code works fine, but I'd like to achieve the same goal using stream based input/output:

```js
const { createReadStream, createWriteStream } = require('fs');
const operations = sharp(); // ==> not sure how to apply the same transformation accessing raw pixel data in a pipeline
const rs = createReadStream('input.png');
const ws = createWriteStream('output.png');
rs.pipe(operations).pipe(ws);
```

Is there a way this can be achieved with Sharp? Alternatively, if you could you point me in the right direction on how to create a new operator that would allow such functionality, would be greatly appreciated.

**Comment by lovell** [comment]
Try something like the following (untested):
```js
const readable = createReadStream('input.png');
const writable = createWriteStream('output.png');

const transformToRaw = sharp().raw();

const transformPixels = new stream.Transform({
  transform(chunk, _, callback) {
    for (let i = 0; i < chunk.length; i += 4) {
      if (chunk[i + 3] === 255) chunk[i] = 255;
    }
    callback(null, chunk)
  }
});

const transformFromRaw = sharp({ raw: { width, height, channels }).png();

stream.pipeline(readable, transformToRaw, transformPixels, transformToPng, writable);
```

**Comment by adriaanmeuris** [comment]
Using your example I got this working like a charm. Thanks!
