### ISSUE TITLE
Equivalent of ImageMagick's sigmoidal contrast option?

### ISSUE THREAD

**Issue by BrianSHenderson** [lovell/sharp#2786]
I have been using the setting:
```
-sigmoidal-contrast 20x100%
```
with ImageMagick which was very useful at optimising faint scans, making them much more readable.

Is there a way this can be achieved with Sharp?  For example using linear or modulate methods?

Before:
<img width="843" alt="Screenshot 2021-07-07 at 13 53 52" src="https://user-images.githubusercontent.com/2174330/124762510-e21b6a00-df2a-11eb-829a-5c30bd12e59e.png">

After:
![Screenshot 2021-07-07 at 13 53 59](https://user-images.githubusercontent.com/2174330/124762535-e778b480-df2a-11eb-825d-b86c3b8a74d6.png)

**Comment by lovell** [comment]
There are no curve-based features currently available, and I think providing the sigmoidal features of *magick would involve sharp exposing libvips' [tonelut](https://libvips.github.io/libvips/API/current/libvips-create.html#vips-tonelut) operation.

If you're dealing with faint scans of handwriting then using [threshold](https://sharp.pixelplumbing.com/api-operation#threshold) with a high value might also be suitable, e.g. with `threshold(254)` I see:

<img width="843" src="https://user-images.githubusercontent.com/210965/125752556-45315abf-b5d0-4477-9fae-051ececaca8f.png">

The improvements to [normalise](https://sharp.pixelplumbing.com/api-operation#normalise) discussed in https://github.com/lovell/sharp/issues/200 might also help.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
