### ISSUE TITLE
sharp install via Docker on Centos8 issue

### ISSUE THREAD

**Issue by LeoFengFromChina** [lovell/sharp#2788]
hi，dear master,
when I used sharp with egg.js(based on Koa)，and deploy with docker,

the error is:
sharp: Installation error: Use with musl 1.1.20 requires manual installation of libvips >= 8.10.6

my dockerfile base:
FROM node:12.10.0-alpine

**Comment by lovell** [comment]
The `node:12.10.0-alpine` Docker image is out of date (and probably contains security vulnerabilities).

Please upgrade to at least Alpine 3.11 e.g. via `node:12-alpine3.11` or Alpine 3.13 via `node:12-alpine3.13`.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
