### ISSUE TITLE
Trouble converting specific images to pngs

### ISSUE THREAD

**Issue by cassieramen** [lovell/sharp#279]
We are running into an issue converting certain images to pngs. It happens extremely rarely but reliably with a certain image. The image gets strangely washed out. Here is an example:

**Original: http://i.imgur.com/GQcvWqx.jpg**
This image has an incorrect file extension. This is actually a png image. Exiftool gives us:
```
ExifTool Version Number         : 9.90
File Name                       : GQcvWqx.jpg
Directory                       : .
File Size                       : 658 kB
File Modification Date/Time     : 2015:09:28 12:07:04-04:00
File Access Date/Time           : 2015:09:28 18:00:07-04:00
File Inode Change Date/Time     : 2015:09:28 12:07:07-04:00
File Permissions                : rw-r-----
File Type                       : PNG
MIME Type                       : image/png
Image Width                     : 631
Image Height                    : 631
Bit Depth                       : 8
Color Type                      : RGB with Alpha
Compression                     : Deflate/Inflate
Filter                          : Adaptive
Interlace                       : Noninterlaced
Image Size                      : 631x631
Megapixels                      : 0.398
```

We're running a simple image conversion service. It succeeds in converting to jpg just fine:
**https://external-img-cdn-staging.signal.is/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1IjoiaHR0cDovL2kuaW1ndXIuY29tL0dRY3ZXcXguanBnIiwidiI6dHJ1ZX0.hidHIyZDb7k7EF-atLuvRvBblAq4j2gwVhFReLIIA3I?format=png**

But fails when trying to convert to a png. Which theoretically should be no conversion at all. The conversion pipe isn't emitting any errors and does return an altered image. As a note, we cache these images for 24 hours. You can get a fresh converted image by appending width and any value as a query parameter.
**https://external-img-cdn-staging.signal.is/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1IjoiaHR0cDovL2kuaW1ndXIuY29tL0dRY3ZXcXguanBnIiwidiI6dHJ1ZX0.hidHIyZDb7k7EF-atLuvRvBblAq4j2gwVhFReLIIA3I?format=jpeg**

Perhaps we have a setting misconfigured? We're piping these images directly from the source. So, sharp shouldn't be getting the incorrect metadata anyway. Seems like a red herring but it has been true of images we've seen this in.

**Comment by lovell** [comment]
Hello, this looks like #249. If so, and you know the output format will be JPEG, add `flatten()` to workaround this until libvips 8.1.0 is released.

**Comment by cassieramen** [comment]
Fixed it! Thank you. :)
