### ISSUE TITLE
Provide synchronous calls

### ISSUE THREAD

**Issue by dilyanpalauzov** [lovell/sharp#2790]
My application was using synchronous calls.  Because of sharp, and its asynchronous calls, I have rewritten the application to run asynchronous.  This created a lot of extra microtasks, which slow down the overall execution of the application.

**Comment by lovell** [comment]
Is there a benchmark we can use to provide evidence of how much overhead is added by using async/await/Promises in the context of image processing? Have you tried using callbacks, which will avoid microtasks?

**Comment by dilyanpalauzov** [comment]
Callbacks to do not help me, since I cant to continue once the image processing is done.  There are no evidence for the image processing.  Irrespective of the image processing, when I rewrite my application to use asynchronous calls, it slows significantly down, even when no image processing is done.  Rewriting the application to use async functions is necessary, since the sharp functions are async.

**Comment by lovell** [comment]
I'd be happy to look into this further should someone provide evidence of how much overhead such microtasks add, but my assumption would be that there are much "hotter" code paths to optimise first. Closing for now, but please feel free to re-open with evidence if further help is required.
