### ISSUE TITLE
i have issue using this in nuxtJS

### ISSUE THREAD

**Issue by opeodedeyi** [lovell/sharp#2791]
i tried using this in my Nuxt project, but it failed upon compiling

in my plugin/sharp.js
```
import vue from "vue"
import sharp from "sharp"
vue.use(sharp)
```

and i my nuxt.config.js
```
plugins: [
    '~plugins/sharp.js',
  ],
```

**Comment by lovell** [comment]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7, does the user running `npm install` own the directory it is run in?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

What is the output of running `npx envinfo --binaries --system`?

**Comment by opeodedeyi** [comment]
@lovell i read the documentation and tried it, it onstalled but upon searching for solution i read that it appears sharp runs on only the server and that would make it not work in my nuxt app  https://stackoverflow.com/questions/68340799/issue-using-sharp-package-i-nuxt/68340897#

**Comment by lovell** [comment]
Yes, sharp requires the Node.js runtime. You can use it as a server-side dependency with Nuxt via https://image.nuxtjs.org/providers/ipx

**Comment by shtse8** [comment]
> Yes, sharp requires the Node.js runtime. You can use it as a server-side dependency with Nuxt via https://image.nuxtjs.org/providers/ipx

but ipx currently isn't supported on Nuxt3. what can I do to use sharp with nuxt3?
