### ISSUE TITLE
TIFF Compression without bit depth loss

### ISSUE THREAD

**Issue by dartmoordunbar** [lovell/sharp#2796]
What are you trying to achieve?
I would like to compress (deflate) a 16bit tiff image with no loss of bitdepth.

Have you searched for similar questions?
Yes

Are you able to provide a minimal, standalone code sample that demonstrates this question?
Using imagemagick I can compress the image and not reduce the bit depth.
`mogrify -compress zip *.tiff`
It would be great to do the same with sharp but all my compressed Tiffs now have 8 bits
`options.bitdepth number  reduce bitdepth to 1, 2 or 4 bit (optional, default 8)
`
Are you able to provide a sample image that helps explain the question?
Not really...

**Comment by dartmoordunbar** [comment]
https://github.com/lovell/sharp/issues/534#issuecomment-236826614 seems to downsample if 16bit, I wondered what the reason was? Probably some ignorance on my part.

**Comment by lovell** [comment]
Hi, did you see [toColourspace](https://sharp.pixelplumbing.com/api-colour#tocolourspace)?

```js
await sharp('16-bit.tiff')
  .toColourspace('rgb16')
  .toFile('16-bit-too.tiff');
```

**Comment by dartmoordunbar** [comment]
Amazing. Thank you.
