### ISSUE TITLE
File not made after await toFile executes.

### ISSUE THREAD

**Issue by FurkanToprak** [lovell/sharp#2798]
### Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
Using version `sharp@0.27.2 `. I am not using the latest, 28.3.
### What are the steps to reproduce?
Perform `await` on `toFile()` and behold that there is no file produced after the await terminates. I've also tried this with the `.then()` callback as well. If you sleep for ~10 seconds, however, the output will reflect that the file exists.

### What is the expected behaviour?
I expect the png file to be created and the console to reflect so.
### Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
```
await sharp(pdfPath, {
            failOnError: true,
            page: pageNum,
            density: 150
        }).png().toFile(pngPath);
console.log(`${pngPath} exists: ${existsSync(pngPath)}`)
```
### Are you able to provide a sample image that helps explain the problem?
No
### What is the output of running `npx envinfo --binaries --system`?
```
  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.54 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.17.3 - ~/n/bin/node
    npm: 6.14.13 - ~/n/bin/npm
```

**Comment by lovell** [comment]
Hi, the variable `pdfPath` suggests you're using PDF input. Given you're using macOS, does this mean you have installed `vips` via Homebrew? Do you see the same behaviour when using non-PDF input?

**Comment by FurkanToprak** [comment]
This is extremely embarrassing, there was a race condition elsewhere in my code.
