### ISSUE TITLE
Compressed TIFF toFile and toBuffer results in different size. 

### ISSUE THREAD

**Issue by dartmoordunbar** [lovell/sharp#2799]
What are you trying to achieve?
I want to load a tiff into sharpjs, compress it into the buffer so I can then get the hash for it before saving the file to disk.

Have you searched for similar questions?
Yes

Are you able to provide a minimal, standalone code sample that demonstrates this question?
`if(sourceFileType.mime === 'image/tiff'){
                console.log("processing tiff image")
                compressedBuffer = await sharp(sourceFileBuffer).tiff({compression:'deflate'}).toBuffer()
                md5 = hasha(compressedBuffer, {algorithm: 'md5'})
                await sharp(compressedBuffer).toFile(`./master/${id}`) <------ 1.1MB
                meta = await sharp(compressedBuffer).metadata()
                console.log("Compressed MD5: " + md5)
              }`

But if I save straight to disk
`if(sourceFileType.mime === 'image/tiff'){
                console.log("processing tiff image")
                compressedBuffer = await sharp(sourceFileBuffer).tiff({compression:'deflate'}).toFile(`./master/${id}`) <--- 19.8MB
                //md5 = hasha(compressedBuffer, {algorithm: 'md5'})
                //await sharp(compressedBuffer).toFile(`./master/${id}`)
                //meta = await sharp(compressedBuffer).metadata()
                //console.log("Compressed MD5: " + md5)
              }`

The 1.1MB image says it has JPEG compression if that is a clue?

Are you able to provide a sample image that helps explain the question?

**Comment by dartmoordunbar** [comment]
I have just tried chaining in .tiff() before .toFile() with no change in the output

**Comment by dartmoordunbar** [comment]
It does what I expect if I save to file from the uncompressed buffer. So I have worked out a way but would love to know why the other approach didn't work. Thanks again for this great tool.

**Comment by lovell** [comment]
The default value for TIFF `compression` is "jpeg":

https://sharp.pixelplumbing.com/api-output#tiff

You'll need to add `.tiff({ compression: 'deflate' })` to all processing pipelines if you always want to use "deflate".

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
