### ISSUE TITLE
Enable overwriting input file

### ISSUE THREAD

**Issue by matylla** [lovell/sharp#28]
```
sharp('file.jpg').resize(100, 100).write('file.jpg', function(err) {
    console.log(err)l;
});
```

Gives:

```
VipsJpeg: Empty input file
vips__region_start: start function failed for image temp-1
VipsRegion: valid clipped to nothing
VipsRegion: valid clipped to nothing
VipsRegion: valid clipped to nothing
```

Any chance to implement file overwriting?

**Comment by MickL** [comment]
So is there no safe way to resize a file and overwrite it? Or is it okay to use toBuffer and then fs.writeFile() ?

**Comment by lovell** [comment]
@MickL

> "is it okay to use toBuffer and then fs.writeFile() ?"

Should be, yes. On Windows you'll probably need to use `sharp.cache(false)` too as it aggressively caches files.

**Comment by mwangiKibui** [comment]
has really helped in resizing my files

**Comment by gzurbach** [comment]
In case it helps anyone, I ended up using the following approach to resize my files before uploading them to S3. I didn't want to end up with a new filename. It seems to be working 👍 

```js
const sharp = require("sharp");
sharp.cache(false);

async function resizeFile(path) {
  let buffer = await sharp(path)
    .resize(2000, 2000, {
      fit: sharp.fit.inside,
      withoutEnlargement: true,
    })
    .toBuffer();
  return sharp(buffer).toFile(path);
}
```

**Comment by Zirafnik** [comment]
@gzurbach Is there a benefit to using `sharp(buffer).toFile(path)` instead of just using the native `fsPromises.writeFile(path, buffer)`? If anything, using sharp will cause a performance hit...?
