### ISSUE TITLE
SVG with large feMorphology radius can hang process

### ISSUE THREAD

**Issue by adityapatadia** [lovell/sharp#2802]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
Yes, latest version used. The outputs are same.

What are the steps to reproduce?
Take this image: https://dentalfin.netlify.app/_nuxt/img/purpleBg.0f9eb3f.svg
Try to convert the image to WebP by using 192 DPI in sharp constructor.
The process will hang and go on indefinitely. It uses 100% CPU.

What is the expected behaviour?
The image should be converted to WebP.

What is the output of running `npx envinfo --binaries --system`?
```
npx: installed 1 in 1.784s

  System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 112.60 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - /usr/local/opt/node@14/bin/node
    npm: 6.14.13 - /usr/local/opt/node@14/bin/npm
```

**Comment by adityapatadia** [comment]
Attaching SVG here:
[purpleBg.0f9eb3f.svg.zip](https://github.com/lovell/sharp/files/6832919/purpleBg.0f9eb3f.svg.zip)

**Comment by adityapatadia** [comment]
Is there a way to specify timeout or just cancel the operation?

**Comment by adityapatadia** [comment]
Btw, this happens with 72 DPI as well and with jpeg output as well.

**Comment by adityapatadia** [comment]
`rsvg-convert purpleBg.0f9eb3f.svg > out.jpeg` works fine. It takes a few seconds but at least gives output.

**Comment by kleisauke** [comment]
I think this is due to issue https://gitlab.gnome.org/GNOME/librsvg/-/issues/698, given that this SVG image contains an `feMorphology` with a large radius. This was fixed in librsvg 2.50.4 and 2.51.1.

The pre-built binaries provided by sharp >= 0.28.0 were built against librsvg 2.51.0.

**Comment by adityapatadia** [comment]
Seems possible. We are using debian librsvg which is 2.44 and for rsvg-convert, we are using homebrew version which gives 2.50.7.

Btw, shouldn't sharp have some sort of timeout to avoid such issues.

**Comment by adityapatadia** [comment]
I have upgraded library but still it seems to be taking forever. I checked with rsvg-convert after upgrade. Following is output

```
time rsvg-convert -d 192 purpleBg.0f9eb3f.svg > out.jpeg

real    0m21.178s
user    0m18.445s
sys     0m0.382s
```

When used with sharp, this does not work in 21 sec.

**Comment by lovell** [comment]
The forthcoming sharp v0.29.0 will provide librsvg v2.51.4 (or later) that include the upstream fix. The sample file provided takes about 18 seconds to render locally.

Perhaps you could check/block any untrusted input for the use of the expensive `feMorphology` filter.
