### ISSUE TITLE
Clarify usage of stats on processed/extracted images

### ISSUE THREAD

**Issue by reiv** [lovell/sharp#2803]
Is my understanding correct that `stats()` works solely on the source image and not on the result of any operations done on it - i.e. it cannot be piped this way:

```js
await sharp( ... ).extract( ... ).stats();
```

but needs a buffer to store the intermediate result like so:

```js
const buf = await sharp( ... ).extract( ... ).toBuffer();
await sharp(buf).stats();
```

If that's the case, could this usage perhaps be documented [here](https://sharp.pixelplumbing.com/api-input#stats)? Happy to send a PR your way.

For context: I was trying to do something similar to https://github.com/lovell/sharp/issues/2708 and couldn't work out for the life of me why `dominant` was giving me unexpected results.

**Comment by lovell** [comment]
Hello, yes, PRs that add further examples to the JSDocs are welcome, thank you for the offer.

https://github.com/lovell/sharp/blob/7467fa8b50d280780dfa9fe9a7248deaa499c7a1/lib/input.js#L339-L342

https://github.com/lovell/sharp/blob/master/.github/CONTRIBUTING.md#documentation
