### ISSUE TITLE
Image rotation increase buffer size

### ISSUE THREAD

**Issue by avichal-neweradeveloper** [lovell/sharp#2805]
Due to a rotation of the image in sharp, I used the rotate() function to fix the problem. 
Link of that issue - https://github.com/lovell/sharp/issues/903

Have you searched for similar questions?
--yes

here is the code
`Sharp(req.file.buffer)
         .resize({ width: 1000 })
         .webp()
         .rotate()
         .toBuffer()
         .then((data) => {
            console.log("buffer: ", data);
            console.log("base64: ", data.toString("base64"));
         })
         .catch((err) => {
            console.log("err: ", err);
         });`
image upload without rotation-
buffer:  <Buffer 52 49 46 46 86 4d 00 00 57 45 42 50 56 50 38 20 7a 4d 00 00 d0 10 02 9d 01 2a e8 03 c2 01 3e 6d 34 97 48 24 23 2a 25 a4 72 6a b1 40 0d 89 69 6e 50 15 ... 
19804 more bytes>

the result for the same image with rotation -
buffer:  <Buffer 52 49 46 46 aa 28 01 00 57 45 42 50 56 50 38 20 9e 28 01 00 f0 29 08 9d 01 2a e8 03 ae 08 3e 6d 36 96 48 24 23 2a 29 a6 d4 99 11 40 0d 89 69 6d e7 99 ... 
75904 more bytes>

This is not the case only of a single image others seem to behave like it.

I will be thankful if I get a working solution for the problem.

**Comment by lovell** [comment]
It looks like this code is both resizing and potentially converting the file format to WebP, so I would expect the output file size to be different.

Please can you provide a sample input image that you would expect not to increase in size after this series of transformations.

**Comment by avichal-neweradeveloper** [comment]
I am trying to say when the .rotate() is added to the image (after all other transformations) to display it correctly, which was the solution to https://github.com/lovell/sharp/issues/903 the buffer size is increasing since the file dimensions are the same buffer should not have to be increased and this behaviour seems odd to me.

I am using multer with sharp in nodejs(with express) to upload images.

here is an image I am working with-
https://user-images.githubusercontent.com/65894534/126290906-a66471c2-3bf5-4ac7-811b-6b4c8fa5272f.jpg

**Comment by lovell** [comment]
Processing the input image provided with the following code:

```js
await sharp(input)
  .resize({ width: 1000 })
  .webp()
  .rotate()
  .toBuffer();
```

...produces a WebP image that is 1000x2222 and 75954 bytes.

Processing the input image provided with the following code:

```js
await sharp(input)
  .resize({ width: 1000 })
  .webp()
  .toBuffer();
```

...produces a WebP image that is 1000x450 and 19854 bytes.

This seems like the expected behaviour, as the second image has smaller dimensions.

**Comment by avichal-neweradeveloper** [comment]
ok, thanks a lot I understood the mistake in my code, your package has helped a lot, I have just switched from jimp and this is the best support I ever got in a GitHub issue(I was surprised to see the owner of the repository himself answering).
