### ISSUE TITLE
Install guide for beginners

### ISSUE THREAD

**Issue by ArgTang** [lovell/sharp#281]
Hello
I am trying to install sharp but i am getting stuck. I dont think the guide explains enough:

* Ensure the node-gyp prerequisites are met.
* Download and unzip ```vips-dev.x.y.z.zip```.
* Set the ```VIPS_HOME``` environment variable to the full path of the ```vips-dev-x.y.z directory```.
* Add``` vips-dev-x.y.z\bin``` to ```PATH```.

1 and 2 i have done. But Then i dont know what to to. Where is ```VIPS_HOME```? is it in a config file somewhere or is it a command and what is this command.
For those of us not well versed in CLI it would be helpfull it these steps were more detailed.
I have started vips cli but i cant seem to find if i can set or how to set a variable ```VIPS_HOME`` here
4 Adding vips to the path of what program? 

regards

**Comment by lovell** [comment]
Hello, `VIPS_HOME` refers to an "environment variable" that needs to be configured and made available to any Node app that intends to use sharp. There's some guidance on doing this and modifying `PATH` at http://superuser.com/questions/284342/what-are-path-and-other-environment-variables-and-how-can-i-set-or-use-them

As part of #42 I'm working to remove the need to pre-install `vips` so hopefully very soon these steps will no longer be required, at least (initially) for Windows and Linux users.

**Comment by ArgTang** [comment]
Hi!
Thanks, this also helped alot: http://stackoverflow.com/questions/20394613/add-a-folder-to-the-python-library-path-once-for-all-windows

Would be nice to have a note about refering to python in there :) made it much easier to google when i realised taht python was in the mix

**Comment by lovell** [comment]
The Python dependency is more of a Node-level thing rather than being specific to sharp. All "native" modules built using C++ via node-gyp require it.

Whilst `PYTHON` needs to be set as per the [node-gyp instructions](https://github.com/nodejs/node-gyp#installation) linked to in step 1, you hopefully won't need to add anything to `PYTHONPATH` to use sharp.

**Comment by lovell** [comment]
@ArgTang You may want to subscribe to updates on #42 as the installation of sharp on Windows x86 is about to get a whole lot easier.

I'll close this question now as I think #42 covers what you're looking for, but feel free to re-open it if not.

**Comment by xianyuxiaobai** [comment]
I'm looking for this today, and I'm trying to instal sharp but do not know how to do. Now I will follow steps mentioned above and have a try.

**Comment by lovell** [comment]
The `look` work-in-progress branch now contains changes that remove the need to download/unpack libvips and set environment variables for Windows users.

If you're able, please can you try `npm install lovell/sharp#look` to test this, preferably on a Windows machine without libvips already installed (please report problems at #42).
