### ISSUE TITLE
get the output metadata before applying .toFile()

### ISSUE THREAD

**Issue by eng-dibo** [lovell/sharp#2812]
when resizing an image like this:
```
// img is a Sharp instance, the original image is 500X500
img.resize(100).metadata().then(info=>console.log(info))
```
the above code will log the original image metadata like this `{width: 500, ......}`
to output the resized version to a file we can do the following
```
img.resize(100).toFile('new-file.jpg').then(info=>console.log(info))
```
now it logs the resized version metadata like this `{width: 100, ...}`

that's fine, but sometimes we need the new metadata to dynamically set the output file path like this

```
img.resize.metadata().toFile(({input, output})=>{
 return `new-file/${input.width}X${input.height}-output.formal.input.format`
})
```
note that we used both the input and output metadata, and now `.toFile()` accepts a function instead of a string
`.metadata()` now returns two objects, the original and new metadata.

the resizes dimensions may not be available when applying `.toFile()` because we can dismiss one of the two dimensions.

`.on()` doesn't help, because it may emit after `.toFile()` finish its work, so it may be useless

```
img.resize(100).on('info',meta=>meta).toFile(`file-${meta.width}X${meta.height}`)
```

**Comment by lovell** [comment]
Hi, perhaps you could use a temporary file and rename?
```js
const { rename } = require('fs/promises');
const temp = 'temp.jpg';

sharp(input)
  .resize(100)
  .toFile(temp)
  .then(({ width, height }) => rename(temp, `file-${width}X${height}.jpg`))
  .then( ... );
```

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
