### ISSUE TITLE
/usr/lib/libcfitsio.so.9: undefined symbol: ffgkcl

### ISSUE THREAD

**Issue by ririen** [lovell/sharp#2821]
_Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?_

**Yes. `0.28.3`**

_What are the steps to reproduce?_

**Installing [Nuxt.js](https://nuxtjs.org) with the latest package [nuxt/image](https://image.nuxtjs.org) on Arch Linux.**

What is the expected behaviour?

**Get Nuxt up and running without any problems.**

_Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?_

**The problem is closely related to the operating system and its latest packages so this won't be necessary. Any code that I present on other systems will work fine.**

_Are you able to provide a sample image that helps explain the problem?_

I will provide the error code and an explanation. Arch Linux has the latest software packages up to date, recently the `cfitsio` package was updated from version `3.49` to `4.0.0` and after that the problems started. So `sharp` is not compatible with the latest version of `cfitsio`.

```sh
│   Error:                                                                                │
   │   Something went wrong installing the "sharp" module                                    │
   │                                                                                         │
   │   /usr/lib/libcfitsio.so.9: undefined symbol: ffgkcl      
```

_What is the output of running `npx envinfo --binaries --system`?_

```sh
  System:
    OS: Linux 5.13 Arch Linux
    CPU: (8) x64 AMD Ryzen 7 2700U with Radeon Vega Mobile Gfx
    Memory: 9.49 GB / 30.27 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 16.6.0 - /usr/bin/node
    Yarn: 1.22.11 - /usr/bin/yarn
    npm: 7.20.3 - /usr/bin/npm
```

**Comment by lovell** [comment]
It looks like you're using a globally-installed libvips. Do you see the same problems running `vips` at the command line?

Since you made a major upgrade to an optional dependency of libvips, have you rebuilt/upgraded libvips and/or sharp to ensure they are linking against this new version?

**Comment by ririen** [comment]
I contacted the packers about this. It turned out that I have damaged packages due to a failed installation for an undetermined reason. Reinstalling the packages helped. I close.
