### ISSUE TITLE
Can one install old versions of Sharp?

### ISSUE THREAD

**Issue by Eric-Gonzalez-Portfolio** [lovell/sharp#2824]
Can one install old versions of Sharp? If so, are downloads of previous versions available online, or is there a way to specify version number during npm installation from the command line?

**Comment by lovell** [comment]
https://nodejs.dev/learn/install-an-older-version-of-an-npm-package

Please note I cannot provide any support for older versions.

Does this mean #2773 can be closed?

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
