### ISSUE TITLE
Can't Install Sharp On Termux

### ISSUE THREAD

**Issue by NezukoChans28** [lovell/sharp#2825]
When I Try To Install Sharp In Termux, I Get Error Like This

![Screenshot_20210805-132157](https://user-images.githubusercontent.com/87556399/128301316-fdb53030-f565-41c6-ae5b-fe990b712947.png)

How Do I Fix Errors Like This?

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/1889#issuecomment-535840238
