### ISSUE TITLE
Why does dithering then convert to raw buffer require two constructor calls

### ISSUE THREAD

**Issue by techandsoftware** [lovell/sharp#2828]
What are you trying to achieve?
Source image is a jpeg.  I want to dither to two colours, convert to raw and output a buffer. I found a way to do that but it seems I have to invoke sharp() twice to get the result I want.  The question is - why doesn't the second example below work?

Have you searched for similar questions?
Yep

Are you able to provide a minimal, standalone code sample that demonstrates this question?
This code works, with two steps, 1) convert to dithered png, then 2) convert that to raw buffer
```
        const png = await sharp(filename)
            .resize(100)
            .png({
                colours: 2,
                dither: 1.0,
                quality: 0
            })
            .toBuffer();
        
        const raw = await sharp(png)
            .toColourspace('b-w')
            .raw().toBuffer({ resolveWithObject: true });
```
I'd expect this shorter version to work, but the output buffer isn't dithered.
```
        const raw = await sharp(filename)
            .resize(100)
            .png({
                colours: 2,
                dither: 1.0,
                quality: 0
            })
            .toColourspace('b-w')
            .raw().toBuffer({ resolveWithObject: true });
```
In both cases - I'm only converting to PNG first to get the dithering function.

Are you able to provide a sample image that helps explain the question?
I've been testing with https://upload.wikimedia.org/wikipedia/commons/0/09/A_focused_kitten_%28Pixabay%29.jpg

**Comment by lovell** [comment]
The pipeline is invoked when `toBuffer` is used. In the "shorter version" the `raw` output option overrides the `png` output option so you're correct to split this into two pipelines.

**Comment by techandsoftware** [comment]
Got it.  Thanks for the quick response :)

Rob
