### ISSUE TITLE
Input file is of an unsupported image format on passing jpeg, jpg or png

### ISSUE THREAD

**Issue by shamsher31** [lovell/sharp#283]
I have install dependency using following command on my ubuntu 14.04
```
curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | sudo bash -
```
Installation went good then I installed ```npm install sharp``` and trying to pass jpeg,jpg or png in following sample code from doc.

```
sharp('book.png')
  .resize(300, 200)
  .toFile('output.png', function(err) {
    
  });
```

and getting the following error
```
Input file is of an unsupported image format
```

**Comment by lovell** [comment]
Hello Shamsher, the error you're experiencing means either the file (or at least its metadata) cannot be understood or the file doesn't exist. If you're using relative paths, these are from the current working directory.

**Comment by shamsher31** [comment]
Thanks for your quick response @lovell , I have put image in my current directory, I will give try today with relative path and with different image types.

**Comment by shamsher31** [comment]
I have tried with relative path and with different image types and it works. thank @lovell

**Comment by excellencetechnologies** [comment]
hey lovell,  i am getting this error "Input file is of an unsupported image format" and my code is this 
sharp('mark.png')
  .resize(300, 200)
  .toFile('output.png', function(err) {

  });
