### ISSUE TITLE
How to get the best results when re-sizing? (same as HTML / CSS re-size)

### ISSUE THREAD

**Issue by eliezra236** [lovell/sharp#2830]
What are you trying to achieve? 
I am trying to reduce the loading time of my website, so I am uploading all the images to a CDN and I try to re-size them to save space, since in my website I am showing them in small size anyway. But when I try to use sharp.resize() I am getting a lower quality version compared to what's in the website right now (after HTML / CSS fix the image size).

Have you searched for similar questions?
Yes, couldn't find one.

Are you able to provide a minimal, standalone code sample that demonstrates this question?
Right now I am trying:
```
function ShrinkSize(path, imageFit = "fill", width = 235, height = 320) {
const resizeOptions = { fit: imageFit,   }; 

const image = sharp(path) 
.resize(width, height, resizeOptions) 
.withMetadata() 
.toBuffer({ resolveWithObject: true }); 
return image; }
```

Are you able to provide a sample image that helps explain the question?
https://imgur.com/a/YJooj3U

First image is the original (after HTML / CSS re-size it to fit), and second image is after Sharp.js re-size with the following code. Image size on the actual website is 227 x 304

How can I get the same result?

**Comment by lovell** [comment]
Hi, did you see the `kernel` option of the `resize` operation? The "nearest" kernel might be more appropriate for this kind of image.

https://sharp.pixelplumbing.com/api-resize#resize

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
