### ISSUE TITLE
Sharp work on older OSX?

### ISSUE THREAD

**Issue by DaBodey** [lovell/sharp#2831]
I have a Mac <10.13. Is there a process to make the sharp module work on such a device? It keeps stating the sharp module is incompatible with the version of my operating system.

**Comment by lovell** [comment]
If you're able to use Homebrew then you might have success installing libvips first via `brew install vips` then install sharp.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
