### ISSUE TITLE
How to use .png() to save a greyscale (1 channel), 1 bit image?

### ISSUE THREAD

**Issue by amitm02** [lovell/sharp#2834]
I'm trying to use the .png() function to save:
* An image to greyscale (1 channel), 1-bit png.
* An image to greyscale (1 channel), 2-bit png.

I couldn't understand from the [docs](https://sharp.pixelplumbing.com/api-output#png) what should be the right "options" parameters.
appreciate any help.
awsome library BTW.

**Comment by lovell** [comment]
Convert to greyscale and save as 1-bit palette PNG:
```js
const png1 = await sharp(input)
  .greyscale()
  .png({ colours: 2 })
  .toBuffer()
```

Convert to greyscale and save as as 2-bit palette PNG:
```js
const png2 = await sharp(input)
  .greyscale()
  .png({ colours: 4 })
  .toBuffer()
```

**Comment by amitm02** [comment]
am i to understand from [link](https://sharp.pixelplumbing.com/api-output#png )
`By default, PNG output is full colour at 8 or 16 bits per pixel. Indexed PNG input at 1, 2 or 4 bits per pixel is converted to 8 bits per pixel.`
That selecting `.png({ colours: 2 })` will not really reduce the file size?

**Comment by lovell** [comment]
> Set `palette` to `true` for slower, indexed PNG output.

> `options.colours` maximum number of palette entries, sets `palette` to `true` (optional, default `256`)

When you provide a value for `colours`, you are changing from the default behaviour of full colour output to instead using indexed colour output, which usually reduces the file size.

**Comment by amitm02** [comment]
I get a smaller file with
```
{
            const optimizedBuffer = await sharp(buffer)
            .greyscale()
            .resize(595)
            .png({quality: 30})
            .toBuffer();
        }
```
than 
```
 const optimizedBuffer = await sharp(buffer)
            .greyscale()
            .resize(595)
            .png({colors: 2})
            .toBuffer();  
```.
if (assumingly) in PNG,  quality just changes the palette,
How can it be? isn't 1bpp should give the smallest image size?

**Comment by lovell** [comment]
Dropping the colours to 2 may increase the amount of dithering, which can increase entropy and reduce the LZW compression ratio. Dropping `quality` allows the quantisation to throw detail away. You'll need to experiment for a given input, perhaps also setting `dither` to zero.

**Comment by amitm02** [comment]
setting dither to zero had no effect on image size

**Comment by lovell** [comment]
I hope this information helped. I'll close as it looks like #2855 supersede this, but please feel free to re-open with more details if further assistance is required.
