### ISSUE TITLE
Why Sharp 32bits would not be compatible with NodeJs 64bits ?

### ISSUE THREAD

**Issue by Menlog-DD** [lovell/sharp#2836]
Hello,

I encountered an issue that surprised me. We are building a server in 32bit to ensure the compatibility with 32bits and 64bits machines. To do so we are forcing native modules architecture with the command: npm install --arch=ia32

A few days ago I wanted to check if everything was right and when i started the programm with my Node.js in 64bits on my 64bits windows, the 32bits sharp made the server automaticaly crash with an error log, saying it was not compatible. Here is the log sample : 

"uncaughtException: 'win32-ia32' binaries cannot be used on the 'win32-x64' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'win32-x64' platform.\n"

This is a problem that we do not meet in production because even on x64 machines, we have a 32bits version of node and everything works (sharp 32bits works fine)

I searched for some documentation about this case but I only found the opposite case, saying 'win32-x64' cannot be used on 'win32-ia32' platform which makes perfect sense to me

Would someone take the time to explain me **why 'win32-ia32' binaries cannot be used on the 'win32-x64' platform ?**

I would really appreciate your help, and thank you for reading 👍

**Comment by lovell** [comment]
https://docs.microsoft.com/en-us/windows/win32/winprog64/process-interoperability

> On 64-bit Windows, a 64-bit process cannot load a 32-bit dynamic-link library (DLL). Additionally, a 32-bit process cannot load a 64-bit DLL.

**Comment by Menlog-DD** [comment]
So this is why on a 64bits Windows, a 32bits node.js can load 32bits sharp but a 64bits node.js can't
I wonder how i might be explained at low level but i have now enough to investigate further on my own

Thank you @lovell for your documented answer, i'm closing this question.

Have a good day
