### ISSUE TITLE
Lower requirement for prebuilt binary, arm64 

### ISSUE THREAD

**Issue by jpike88** [lovell/sharp#2837]
Amazon Linux 2 for ARM (graviton) has a glibc version of 2.26.

Prebuilt binary requires 2.29.

Can this requirement be lowered to 2.26?

**Comment by lovell** [comment]
Hi, please see https://github.com/lovell/sharp-libvips/commit/2e4202d671904666c012b142b8e21be017d30a28 and https://github.com/lovell/sharp-libvips/pull/86 for previous discussion and attempts to use an earlier glibc.

The summary is that a minimum of gcc 9.1.0+ is required to cross-compile libvips for ARM64, and gcc 9.1.0+ is only available on Debian-based OS with glibc 2.29+. (Other Linux flavours such as RHEL do not provide the cross-compilation toolchains we need.)

If anyone can solve this then a PR will be gladly accepted, but I'm going to close this request as it's probably a significant amount of work.

**Comment by lovell** [comment]
Possible future experiment that might help - see https://github.com/lovell/sharp-libvips/issues/114

**Comment by lovell** [comment]
Tracking this at https://github.com/lovell/sharp/issues/2938
