### ISSUE TITLE
Use system libvips when available

### ISSUE THREAD

**Issue by mkg20001** [lovell/sharp#2839]
When the system already has an installation of libvips then sharp should try to use that instead of downloading libvips, when compiling sharp.

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/install#custom-libvips

> To use a custom, globally-installed version of libvips instead of the provided binaries, make sure it is at least the version listed under `config.libvips` in the `package.json` file and that it can be located using `pkg-config --modversion vips-cpp`.

**Comment by mkg20001** [comment]
Ah I was missing pkg-config

Previously it worked that's what left me confused

Works now, thanks
