### ISSUE TITLE
Conversion of webp to webp takes too long and the result file is too large

### ISSUE THREAD

**Issue by faradaytrs** [lovell/sharp#2840]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
sharp@0.28.3

What are the steps to reproduce?
Image file is attached, 2.3mb

````js
await sharp(imageBuffer).rotate().webp({quality: 85, lossless: false}).toBuffer({
    resolveWithObject: true,
})
````

What is the expected behaviour?
Picture of size less than original or at least the same.
The most interesting that it takes 12 seconds to handle the image on my machine.
12 second for one picture, if I cut webp quality to 65 then it gets much quicker. 3.83 seconds. 
And the result size is 2.52mb which is still bigger than the original.
I don't know if it's a bug, or I don't understand how it works. I wouldn't want to use 65 for all pictures, just because this one takes so much time to handle. 

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

Minimal would be:
````js
await sharp(imageBuffer).webp({quality: 85, lossless: false}).toBuffer()
````

Are you able to provide a sample image that helps explain the problem?
[17ed26e9-dc7e-43d2-a251-9dc74b1e17a2.webp.zip](https://github.com/lovell/sharp/files/6981557/17ed26e9-dc7e-43d2-a251-9dc74b1e17a2.webp.zip)

What is the output of running `npx envinfo --binaries --system`?

  System:
    OS: macOS 11.5.1
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 2.87 GB / 32.00 GB
    Shell: 5.1.8 - /usr/local/bin/bash
  Binaries:
    Node: 16.6.2 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.20.3 - /usr/local/bin/npm

**Comment by lovell** [comment]
WebP images are relatively slow to encode. You can control the speed with the `reductionEffort` parameter.

https://sharp.pixelplumbing.com/api-output#webp

The timings provided here seem about right for the sample image. Perhaps try running `dwebp` and `cwebp` at the command line to gather some expected timings.

The difference in size is likely to be due partly to the rotation, but I suspect mostly due to the use of different encoder settings.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
