### ISSUE TITLE
`trim()` function should only trim transparent pixels but trims black pixels too

### ISSUE THREAD

**Issue by chescos** [lovell/sharp#2842]
### What are the steps to reproduce?

Trim the following image:

![input](https://user-images.githubusercontent.com/12296880/129482909-0f85ca77-63df-46c2-8eb0-66ab8e125167.png)

You'll get this result:

![output](https://user-images.githubusercontent.com/12296880/129482920-f7e880db-d7ef-47b6-aac0-edf2d6885b3b.png)

### What is the expected behaviour?

Only trim transparent pixels instead of transparent AND black pixels.

### Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

```js
const fs = require('fs');
const sharp = require('sharp');

const originalFileBuffer = fs.readFileSync('input.png');

(async () => {
    const newFileBuffer = await sharp(originalFileBuffer)
      .trim(1)
      .toFormat('png')
      .toBuffer();

    fs.writeFileSync('output.png', newFileBuffer);
})();
```

Run the above code snippet with this image as `input.png`:

![input](https://user-images.githubusercontent.com/12296880/129482796-c2735da7-f89b-460f-9f72-24ba441e4e77.png)

### What is the output of running `npx envinfo --binaries --system`?

```
  System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
    CPU: (16) x64 AMD Ryzen 7 PRO 5850U with Radeon Graphics
    Memory: 18.05 GB / 30.26 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 14.17.5 - /usr/bin/node
    npm: 6.14.14 - /usr/bin/npm
```

**Comment by lovell** [comment]
Please see #2166
