### ISSUE TITLE
Add ability to trim only transparent pixels

### ISSUE THREAD

**Issue by chescos** [lovell/sharp#2843]
### What are you trying to achieve?

I'm looking to "crop an image to its content". That is, remove/trim/crop all possible transparent pixels at the edges of the image. 

In some cases, this is possible with the `trim()` function. But there are cases where `trim()` behaves weird (see #2842) and then there are cases where the top left pixel is not transparent, but the bottom or right side of the image have transparent parts that can be trimmed.

### Have you searched for similar feature requests?

Yes

### What would you expect the API to look like?

I'm not sure, maybe `trimTransparent()`.

### What alternatives have you considered?

I've searched around Google and Github to find a solution for this, even with other JS libraries, but I haven't found anything that can reliably achieve this.

### Is there a sample image that helps explain?

Consider this image:

![in](https://user-images.githubusercontent.com/12296880/129483359-c3dc7dcb-91dd-474f-89ab-e9549b3602cf.png)

I'd like to trim all transparent pixels from the edges, resulting in this image:

![out](https://user-images.githubusercontent.com/12296880/129483378-b02fde08-f26c-4934-9d54-a5d5afa0cbef.png)

**Comment by lovell** [comment]
Please see #2166

**Comment by danielo515** [comment]
Sorry for comment in Ann old issue, but how is this achieved?
