### ISSUE TITLE
Image Element Not Rendered When Converting SVG to PNG Even With Embedded SVG Included As Base64 Data

### ISSUE THREAD

**Issue by dbdjre0143** [lovell/sharp#2844]
**What are you trying to achieve?**
I generate an SVG which includes <image> nodes, and want to convert that SVG to a PNG. When I do, the result is that everything is present except for the embedded images.
I have attempted this with three approaches, each with the same result:
- Referencing the embedded svgs at an HTTP resource. (My understanding is that this is expectedly impossible)
- Downloading them to the same directory as the "main" SVG and using the file:// path as the image href attribute
- Base64 encoding the SVG text and embedding it in the image href attribute.

**Have you searched for similar questions?**
Yes, I found https://github.com/lovell/sharp/issues/1871.
The latter comments in that question seem to propose two solutions, which are the second two solutions I attempted above.

**Are you able to provide a minimal, standalone code sample that demonstrates this question?**
`convertSvgToPngFile = async (svgFile) => {
    const fileName = '/tmp/' + uuidv4() + '.png';
    await sharp(svgFile).png().toFile(fileName);
    return fileName;
}`

**Are you able to provide a sample image that helps explain the question?**
_(I received a message about unsupported filetype when uploading an SVG, so posting the text contents here as code)_
`<svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.dev/svgjs" width="1920" height="1080"><rect width="800" height="1080" fill="#fb4f14"></rect><polyline points="799,0 1121,0 799,1080" fill="#fb4f14"></polyline><polyline points="1121,0, 1121,1080 799,1080" fill="#000000"></polyline><rect width="800" height="1080" fill="#000000" x="1120" y="0"></rect><image width="570" height="570" href="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxzdmcgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbDpzcGFjZT0icHJlc2VydmUiIGhlaWdodD0iMjY2IiB2aWV3Qm94PSIwIDAgMzc4LjgyMDA3IDI2Ni40NTA4MSIgd2lkdGg9IjM3OSIgdmVyc2lvbj0iMS4xIiB4bWxuczpjYz0iaHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbnMjIiB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iPjxnIHRyYW5zZm9ybT0ibWF0cml4KDEuMjUgMCAwIC0xLjI1IC0xOTAgNjI1KSI+PGcgc3R5bGU9IiI+PHBhdGggZD0ibTQyNCAzOTdjLTEuNiAwLjgxMi0xLjQgMi4yNi0wLjI0OCAzLjEyIDEzLjYgMTAuMSAyMi45IDIzLjEgMjIuOSA0My4xIDAgMjMuNy0xNyA1Ny04My4zIDU3aC0xNzFsLTM4LjctNjcuNWgyOC40YzMuMTggMCA1Ljc0LTIuNTYgNS43NC01Ljczdi02Ny4zYzAtMy4xNy0yLjU2LTUuNzMtNS43NC01LjczaC0zMC41bDM5LjEtNjcuMiAxODEgMC4wMjExYzU4LjMgMCA4My41IDMwLjQgODMuNSA2My4xIDAgMjEuNi0xNS40IDM5LjItMzEgNDcuMSIgZmlsbD0iI2ZmZiIvPjxwYXRoIGQ9Im0zMjMgNDA4aC0yOC4xdjI3YzAuMDI2NCAyLjgzIDIuMzIgNS4xMiA1LjE2IDUuMTJoMjIuOWMxMy41IDAgMTguNC02Ljg2IDE4LjQtMTUuOCAwLTkuNS01LTE2LjMtMTguNC0xNi4zem0wLTYyLjJoLTIyLjljLTIuODUgMC01LjE2IDIuMzEtNS4xNiA1LjE1djI3aDI4LjFjMTMuNSAwIDE4LjQtNi41OSAxOC40LTE1LjggMC05LjQ4LTUtMTYuMy0xOC40LTE2LjN6bTgwLjIgNDkuMmMtMi4wNiAwLjQ4NS0xLjcyIDMuMDEtMC4yMTYgMy41NyAxOC41IDcuMDIgMjkuNCAxOS41IDI5LjQgNDEuNSAwLjI1OCAyOS41LTI1LjggNDkuOC02OC4yIDQ5LjhoLTE2MWwtMjguMi00OS44aDE5LjRjMy44NCAwIDYuOTQtMy4xIDYuOTQtNi45NHYtODAuNGMwLTMuODQtMy4xLTYuOTQtNi45NC02Ljk0aC0xOS4ybDI4LjQtNDkuNiAxNjggMC4wMjExYzQ4IDAgNjcuNyAzMS45IDY3LjcgNTUuMyAwIDIwLjYtMTUuMiAzOC40LTM2LjMgNDMuNSIgZmlsbD0iI2ZiNGYxNCIvPjxwYXRoIGQ9Im0yNTggMzEwYy0yOS44IDU2LTM3LjYgMTIwLTI2LjUgMTgwaC0yOC4ybC0yOC4yLTQ5LjhoMTkuNGMzLjg0IDAgNi45NC0zLjEgNi45NC02Ljk0di02MS43YzE0LjUtMjMuNSAzNS40LTQ2IDU2LjUtNjEuMnptMTQxIDE3NGMtMzQuMS01MC42LTUyLjYtMTE1LTQ0LjMtMTc0IDEwLjIgNDkuNCAzNi43IDk1IDc4IDEyOCAwLjAxMDUgMC40OTEgMC4wNTI3IDAuOTY2IDAuMDUyNyAxLjQ3IDAuMTc0IDIwLjMtMTIuMiAzNi4zLTMzLjcgNDQuM3ptLTU3LjIgNS41NGMtNS4zNS0xNC0xMS0zMC45LTE1LjctNDkuOS0wLjg0NCAwLjA2MzQtMS43NCAwLjEtMi42NiAwLjFoLTIyLjljLTIuODQgMC01LjEzLTIuMjgtNS4xNi01LjEydi0yN2gyNC4xYy0xLjU5LTkuNjktMi44OC0xOS43LTMuNzQtMzBoLTIwLjR2LTI3YzAtMi44NSAyLjMxLTUuMTUgNS4xNi01LjE1aDE0LjFjMC4yMTEtMTYuMiAxLjY1LTMyLjggNC42OC00OS41aC0yMWMtMTYuNSAzOS45LTM5LjMgMTA3LTE2LjcgMTk0aDYwLjEiLz48L2c+PC9nPjwvc3ZnPgo=" x="195" y="255"></image><image width="570" height="570" href="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxzdmcgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbDpzcGFjZT0icHJlc2VydmUiIGhlaWdodD0iMTk2LjA2IiB3aWR0aD0iMTk2LjA2IiB2ZXJzaW9uPSIxLjEiIHhtbG5zOmNjPSJodHRwOi8vY3JlYXRpdmVjb21tb25zLm9yZy9ucyMiIHhtbG5zOmRjPSJodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgdmlld0JveD0iMCAwIDE5Ni4wNjI0OSAxOTYuMDYwMzYiPjxnIHRyYW5zZm9ybT0ibWF0cml4KC41IDAgMCAuNSAxLjEwNDEgMS4wNTQpIj48cGF0aCBkPSJtMi43ODI1IDE5NC42N2MwIDEwNS4zNSA4NS43MTIgMTkxLjA2IDE5MS4wNiAxOTEuMDZzMTkxLjA2LTg1LjcxMiAxOTEuMDYtMTkxLjA2YzAuMDEtMTA1LjM1LTg1LjctMTkxLjA2LTE5MS4wNi0xOTEuMDYtMTA1LjM0IDAtMTkxLjA2IDg1LjcwNi0xOTEuMDYgMTkxLjA2Ii8+PHBhdGggZD0ibTE5My44NCAzODEuNTRjMTAzLjIgMCAxODYuODctODMuNjY5IDE4Ni44Ny0xODYuODggMC0xMDMuMTktODMuNjctMTg2Ljg2LTE4Ni44Ny0xODYuODYtMTAzLjIgMC4wMDEyLTE4Ni44NyA4My42Ny0xODYuODcgMTg2Ljg3IDAgMTAzLjIxIDgzLjY2OSAxODYuODggMTg2Ljg4IDE4Ni44OCIgZmlsbD0iI2E1YWNhZiIvPjxwYXRoIGQ9Im0xOTMuODQgMzUxLjAyYzg2LjA5NCAwIDE1NS44OS02OS43OTQgMTU1Ljg5LTE1NS44OSAwLTg2LjA5LTY5Ljc5LTE1NS45LTE1NS44OS0xNTUuOXMtMTU1Ljg5IDY5LjgtMTU1Ljg5IDE1NS44OWMwIDg2LjA5NCA2OS43OTQgMTU1Ljg5IDE1NS44OSAxNTUuODkiIGZpbGw9IiNmZmYiLz48cGF0aCBkPSJtMTk0LjY2IDE5NS4zNGMxLjgwMDgtNjMuODUgNjIuMTE2LTc4Ljg0NCA3Ny4yNjktNzcuNDY5LTM3LjM1Ni0yLjAyODUtNzQuMjI1LTE3LjgxNC03Ny4wNjktNzYuODg4LTQuNTA2MiA1NC45MzgtMjYuNTUgNzAuNTU2LTc3LjM0NCA3Ny4wNzUgMzYuMjgxIDEuODM3NSA3My4wMTIgMTYuMTk0IDc3LjE0NCA3Ny4yODEiIGZpbGw9IiNlZWFkMWUiLz48cGF0aCBkPSJtMjcyLjE0IDI3NC4zN2MxLjgtNjMuODUgNjEuMDU2LTc5LjYwNiA3Ni4yMTItNzguMjMxLTM3LjQ4MS0xLjM4NzUtNzMuNTgxLTE5LjItNzYuNDI1LTc4LjI2OS00LjUgNTQuOTM4LTI2LjQ2OSA3MC45NS03Ny4yNjkgNzcuNDY5IDM2LjI4MSAxLjgzNzUgNzMuMzUgMTcuOTQ0IDc3LjQ4MSA3OS4wMzEiIGZpbGw9IiNjNjBjMzAiLz48cGF0aCBkPSJtMTk1LjYgMzUwLjM3YzEuNzk2NS02My44NjIgNjEuMzg5LTc3LjM3NSA3Ni41NS03Ni0zNy4zNTYtMi4wMzI4LTc0LjYzOC0xOS45NTQtNzcuNDgxLTc5LjAzMS00LjUwNjIgNTQuOTQ0LTI1LjkgNzEuNDQ0LTc2LjY5NCA3Ny45NjIgMzYuMjgxIDEuODUgNzMuNDg4IDE1Ljk5NCA3Ny42MjUgNzcuMDY5IiBmaWxsPSIjMDA1MzliIi8+PHBhdGggZD0ibTY4LjY5OCAxNzEuNzFjLTEuNDc1MyAwLjAxLTIuOTc3IDAuMzIzOTYtNC4zODE4IDAuOTQwNDUtMS42ODkgMC43MzkyLTIuODU4NCAyLjA4LTMuNjgzNiAzLjU0OTgtMC44MjUxNSAxLjQ4Ny0xLjI4OTQgMi42Njg2LTEuMzkyNiA0LjM2NjItMC4yMTQ4OSAzLjU4NDMgMS41Nzc0IDcuMzYyIDQuOTUxMiA5LjQ2OCAyLjM2MzggMS40Nzg0IDQuMDk1NSAxLjY3MTkgNi4xMDI1IDMuNjAxNiAxLjA2NTggMS4wMTQzIDAuOTgwNTUgMy42NDg5IDAuNjM2NyA0LjI1NDktMC45NzU2IDEuNzI3Ny0zLjUxMTYgMS4wOTE3LTQuMTM0OCAwLjQzODQ3LTAuNjI3NS0wLjY1NzU1LTAuOTAxOTUtMy4wMjYtMC43NzczNS0zLjk2MjlsLTYuNjkyNSAwLjAzOTFjLTAuMjU3ODcgMi45NDgyLTAuMDU1MDcgNC43NjIzIDAuODM4ODUgNi43NjA1IDAuOTA2OCAyLjAzNzEgMi4xNzg4IDIuODAyIDMuODI5MSAzLjU5MjggMy41ODQ0IDEuNzAxOSA4LjQxOTUgMS41NTk0IDExLjkwOS0xLjY5ODIgMC44NTUyNS0wLjc5NTA1IDEuMTY0MS0xLjcyNzYgMS4xNjQxLTEuNzI3NiAwLjgxMjI1LTEuOTcyNyAxLjcxOTYtNC4yMDcxIDEuMDg3OS03LjgwODUtMC4yOTY1Ni0xLjY4NDgtMS4wMjc1LTMuMDY0Mi0xLjQwMTQtMy41OTI4LTEuMjQyLTEuNzUzNS0yLjE2MjItMi41NDg3LTUuNDg0NS00LjE2OSAwLjA3NzM4IDAtMS4wNDg0LTAuNDgxNDQtMC45NjY4LTAuNDgxNDQtMy41MTU2LTEuMTIxNy00LjkxMi0zLjI3MDItMy44MjAzLTUuNTU2NSAwLjYwMTctMS4yNzIxIDIuODc5MS0xLjc3OTcgMy44ODQ4LTAuODY0MjUgMC42NzkgMC42MjMxIDAuODMzOCAxLjk1NTIgMC44ODk2NSAyLjk4MjRsMi4zNDI4LTAuMDE2Nmg0LjMwNTZjMC4wOTAyNC0yLjk2NTQtMC41NDU2LTQuNjMzNi0xLjE4MTctNS43NTEtMS42NjM2LTIuOTM3LTQuNzc5Ni00LjM4NjgtOC4wMjU1LTQuMzY1MnptNTYuOSAwLjYxMzN2MzIuOTQ4aDYuMzEzNXYtMzIuOTNsLTYuMzEzNS0wLjAxNzZ6bS0zOC4wMDkgMy43ODYyLTYuMjY2NSAzLjQzODV2Mi4xNTcybC0yLjQ3OTUgMC4wNzgxIDAuMDI1NCA1LjM5NzUgMi4zMzc5LTAuMDc3MiAwLjA0Nzg1IDEyLjQwN2MwLjAyNTggNi41ODg1IDUuNjcyNSA1LjU3NDUgOC42NTU1IDUuNjQ3NWwwLjAwNS03LjAwNWMtMi41MjcgMC4wMzg3LTIuMjk5OC0wLjQ2NDM4LTIuMjk5OC0xLjcyMzZ2LTkuMjA2bDIuNDExMiAwLjAzOTEtMC4wMjU0LTUuNTMxLTIuMzg1OCAwLjA1MTgtMC4wMjU0LTUuNjc0em04My4zMzUgNS4yOTVjLTEuMDYzOCAwLjAxNTYtMi4xMzE1IDAuMjQwNTEtMy4xMjQgMC43MjI2NS0wLjk1NDA1IDAuNDU5ODctMS42NTA2IDAuMzYwMzgtMy4yNDUxIDIuMzMzLTAuNzU2NCAwLjkzMjYtMC45NzA5IDIuMzE2Ni0xLjA0NCAzLjUxNTYtMC4xNTA0NCAyLjUzNTcgMC42ODc1NSA1Ljg3OTUgNC4xMzg2IDYuNzUyIDEuOTI5NyAwLjQ4NTYyIDQuMTI2MiAwLjczOTUgNS4xNTM1IDIuMjkxIDAuNTYzIDAuODQ2NiAwLjM5OTA3IDEuMTk4NyAwLjE0NTUxIDEuODQ3Ni0wLjM2MTA2IDAuOTE5NzUtMi40MTA2IDAuOTA3MzUtMy4yMzE0IDAuNTg0OTUtMC44MTIyNS0wLjMwOTQ0LTEuMzE5NC0xLjI1OTItMS4yMTE5LTIuMDgwMWwtNS4yNTIgMC4wMzQyYzAuMDk4OCAyLjAyODUgMC4xMTYwOSAzLjI1OCAwLjg4OTY1IDQuNzU3OCAwLjc0NzggMS40NTI3IDIuMjU1OCAyLjUwOTYgMy42Mzk2IDIuOTMwNiAyLjgxOTMgMC44NTUyNSA1LjkyMjUgMC43MDUzNSA4LjIyMTUtMC43MTI5IDAuNDIxMTktMC4yNjIxOSAxLjYwMzYtMS4zMzczIDIuMDg1LTIuMjAxMiAwLjc5MDgtMS40NDQgMS4yNTktMy4yOTE5IDAuNTQ5OC01LjcxNi0wLjMzNTE5LTEuMTY5LTAuMzY5NTEtMS4zMDE2LTAuNTgwMS0xLjcxLTEuMjUwNi0yLjM4NTItMi44NTgyLTIuODQ5NC00LjUyMTUtMy40MDgyIDAuMDU1OSAwLTEuNTQ3MS0wLjM3MDEyLTEuNDkxMi0wLjM3MDEyLTIuOTMxLTAuMzMwOTQtMy4xMTE0LTEuOTg5Mi0yLjcyNDYtMy4xMTUyIDAuMzIyMzItMC45MzI2IDEuMDY1Ni0xLjI0MjIgMi4wMjgzLTEuMjQyMiAwLjgxNjYgMC4wMDkgMS42MiAwLjU3OTk1IDEuNzcwNSAxLjE4MTYgMC4xMDMxMyAwLjQyOTc1IDAuMDkwOCAwLjkyNDMgMC4wOTA4IDEuNDg3M2w1LjQzMjUgMC4wMjU0Yy0wLjA0My0yLjExNDUtMC40MzAzNi00LjMwNjYtMS42MTIzLTUuNDk3LTEuNDQ3OC0xLjQ2ODUtMy43NjcyLTIuNDQ1NC02LjEwNzUtMi40MTEyem0tMTAuMDUyIDAuMTE2MjFjLTIuMDcxNiAwLjQ2NDEzLTIuNjIxNyAxLjQyNzQtMy41MzcxIDMuMDM5bC0wLjAyNjQtMi45MzU2LTYuMDg1IDAuMDY0NXYyMy4zOGg2LjIwMXYtMTMuNTUxYzAuMDY4Ny0xLjQwOTctMC4yNzkwMy0zLjI0NTYgNC45Ni0yLjg3NnYtNy4xMjFoLTEuNTEyN3ptLTYxLjY5IDAuMjExOTFjLTEuMjUzMy0wLjAyNTItMi42MTcxIDAuMjU3MDYtNC4zNzcgMS4wMjY0LTIuMDYzIDEuMzU4LTMuMjU3NiAzLjIyMy0zLjE0MTYgNS4zNjM1djExLjQwNmMwLjExNjA2IDIuODI4IDEuMzQxNSA0LjgzNDggMy44NjQyIDUuNzU5IDEuOTE2OCAwLjQwODI1IDMuOTcwNCAxLjAyMjkgNy4yNTQgMCAzLjA5NDQtMS4wNjU5IDMuODU0OC0zLjA1NTggMy44MDc2LTQuODg2N2wtMC4wMTI3LTIuNzU0OS01LjE1MjUgMC4wMjYzdjAuNjY2Yy0wLjExNiAyLjY0MzEtNC42OTggMi4yMTM1LTQuNzEwOSAwLjExNjIxbDAuMDA4OC0zLjIxNDhoOS44Njd2LTcuMjM3NWMtMC4wMzAxLTIuMzc2Ny0xLjE2NDMtNC4wNzg4LTMuNjkxNC01LjQ1NC0xLjMxOTQtMC40NTc2OC0yLjQ2MjUtMC43OTAyLTMuNzE1OC0wLjgxNTQ1em0xNy4xMDYgMGMtMS4yNTI4LTAuMDI1Mi0yLjYxNTggMC4yNTcwNi00LjM3OCAxLjAyNjQtMi4wNjMgMS4zNTgtMy4yNTc2IDMuMjIzLTMuMTQxNiA1LjM2MzV2MTEuNDA2YzAuMTE2MDYgMi44MjggMS4zNDA0IDQuODM0OCAzLjg2MzMgNS43NTkgMS45MjExIDAuNDA4MjUgMy45NzE0IDEuMDIyOSA3LjI1NSAwIDMuMDk0NC0xLjA2NTkgMy44NTA2LTMuMDU1OCAzLjgwNzYtNC44ODY3bC0wLjAxMjctMi43NTQ5LTUuMTUzNSAwLjAyNjN2MC42NjZjLTAuMTE2IDIuNjQzMS00LjY5NzEgMi4yMTM1LTQuNzEgMC4xMTYyMWwwLjAwOS0zLjIxNDhoOS44Njd2LTcuMjM3NWMtMC4wMzAxLTIuMzc2Ny0xLjE2NDMtNC4wNzg4LTMuNjkxNC01LjQ1NC0xLjMxOTQtMC40NTc2OC0yLjQ2Mi0wLjc5MDItMy43MTQ4LTAuODE1NDV6bTI1LjExNSAwYy0xLjI1MjgtMC4wMjUyLTIuNjE0OSAwLjI1NzA2LTQuMzc3IDEuMDI2NC0yLjA2NzIgMS4zNTgtMy4yNTc2IDMuMjIzLTMuMTQxNiA1LjM2MzV2MTEuNDA2YzAuMTE2MDcgMi44MjggMS4zNDA2IDQuODM0OCAzLjg2MzMgNS43NTkgMS45MjExIDAuNDA4MjUgMy45NzE0IDEuMDIyOSA3LjI1NSAwIDMuMDk0NC0xLjA2NTkgMy44NTQzLTMuMDU1OCAzLjgwMjgtNC44ODY3bC0wLjAwOC0yLjc1NDktNS4xNTcgMC4wMjYzdjAuNjY2Yy0wLjExMTc1IDIuNjQzMS00LjY5MzYgMi4yMTM1LTQuNzAyMiAwLjExNjIxbC0wLjAyMTUtMy4yMTQ4aDkuODkzNXYtNy4yMzc1Yy0wLjAyNTgtMi4zNzY3LTEuMTY0Ny00LjA3ODgtMy42ODc1LTUuNDU0LTEuMzIzNy0wLjQ1NzY4LTIuNDY2OS0wLjc5MDItMy43MTk3LTAuODE1NDV6bS00Mi4zMiA1LjM3MWMxLjQ2NjktMC4wNzI1IDMuMDM2OCAxLjA5NTMgMi41MjU0IDMuMjY2NmwtNC42Njc5LTAuMDE3NWMtMC4zNjY2NS0yLjE1NTYgMC44NDgyLTMuMTg1IDIuMTQyNi0zLjI0OXptMTcuMTA0IDBjMS40NjctMC4wNzI1IDMuMDM2OCAxLjA5NTMgMi41MjU0IDMuMjY2NmwtNC42NjctMC4wMTc1Yy0wLjM2NjY1LTIuMTU1NiAwLjg0NzI1LTMuMTg1IDIuMTQxNi0zLjI0OXptMjUuMTE2IDBjMS40NjctMC4wNzI1IDMuMDM2OCAxLjA5NTMgMi41MjU0IDMuMjY2NmwtNC42NjctMC4wMTc1Yy0wLjM2NjY1LTIuMTU1NiAwLjg0NzI1LTMuMTg1IDIuMTQxNi0zLjI0OXoiLz48L2c+PC9zdmc+Cg==" x="1150" y="255"></image></svg>`

Thank you for your time in helping me understand what I'm doing wrong!

**Comment by lovell** [comment]
Did you see #1378 (linked to by #1871)?

**Comment by dbdjre0143** [comment]
Aha! No I had missed that one. Thank you! So in that case, what do you think the best approach would be? Perhaps convert the embedded SVGs to PNGs and embed them as PNG in the outer SVG before converting?

**Comment by dbdjre0143** [comment]
Just wanted to report back that I did end up going with the approach (at least for now) of converting the embedded logos to PNG first, then converting the entire image to PNG after embedding the PNGs in SVG.
I'll go ahead and close the issue, but if you have any further pointers for a better approach, I'd love to hear them when you have a chance.
Thank you again for your time and such a quick response!

**Comment by dcsan** [comment]
@dbdjre0143 can you give a code snippet of how you convert the PNGs to the right base64 encoding to embed in an SVG file please? something like this?

```
const imageData = fs.readFileSync('./some-image.png', 'base64');
const output = `<image width="570" height="570" href="data:image/svg+xml;base64,${imageData}" />
```

**Comment by dcsan** [comment]
FWIW i tried the below - a few different options - and I get a blob but it doesn't render correctly.

```ts
    async embedImage(fname: string) {
        const base = process.cwd()
        const srcFile = path.join(base, '../assets/emos/parts', fname)
        let blob = fs.readFileSync(srcFile, 'base64')
        blob = blob.split(';base64,').pop() // not needed
        clog.info('blob', { blob })
        // const blob = await sharp(srcFile).toBuffer()
        // const base64 = blob.toString('base64')

        const xml = `<image x="0" y="0" width="500" height="500" href="data:image/svg+xml;base64,${blob}" />`
        clog.info('xml', { xml })
        return xml
    }
```

```
<svg width="1000" height="1000" viewBox="0 0 1000 1000" fill="none" xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink">
    <style>
        .big {
            font: bold 48px sans-serif;
        }
    </style>

    <rect width="1000" height="1000" fill="#66DDDD" />

    <image x="0" y="0" width="500" height="500" href="data:image/svg+xml;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAABRWlDQ1BJQ0MgUHJvZmlsZQAAKJFjYGASSSwoyGFhYGDIzSspCnJ3UoiIjFJgf8bAwiDCIAoUNkxMLi5wDAjwAbIZYDQq+HaNgRFEX9YFmRWiEf1gMetWbzETxdtW8n37MdWjAK6U1OJkIP0HiNOTC4pKGBgYU4Bs5fKSAhC7A8gWKQI6CsieA2KnQ9gbQOwkCPsIWE1IkDOQfQPIFkjOSASawfgCyNZJQhJPR2JD7QUBXh93hVCfkCDHcE8XVwLuJRmUpFaUgGjn/ILKosz0jBIFR2AopSp45iXr6SgYGRgZMTCAwhyi+vMNcFgyinEgxArEGBgsZgAFHyLE4oF+2C7HwMDfhxBTA/pXwIuB4eC+gsSiRLgDGL+xFKcZG0HY3NsZGFin/f//OZyBgV2TgeHv9f//f2/////vMgYG5lsMDAe+AQBIc19e/G/f+AAAAJZlWElmTU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAIdpAAQAAAABAAAAWgAAAAAAAABIAAAAAQAAAEgAAAABAAOShgAHAAAAEgAAAISgAgAEAAAAAQAAAAqgAwAEAAAAAQAAAAoAAAAAQVNDSUkAAABTY3JlZW5zaG90m7z2nwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAjtpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDYuMC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6ZXhpZj0iaHR0cDovL25zLmFkb2JlLmNvbS9leGlmLzEuMC8iCiAgICAgICAgICAgIHhtbG5zOnRpZmY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vdGlmZi8xLjAvIj4KICAgICAgICAgPGV4aWY6UGl4ZWxZRGltZW5zaW9uPjI2PC9leGlmOlBpeGVsWURpbWVuc2lvbj4KICAgICAgICAgPGV4aWY6VXNlckNvbW1lbnQ+U2NyZWVuc2hvdDwvZXhpZjpVc2VyQ29tbWVudD4KICAgICAgICAgPGV4aWY6UGl4ZWxYRGltZW5zaW9uPjI4PC9leGlmOlBpeGVsWERpbWVuc2lvbj4KICAgICAgICAgPHRpZmY6T3JpZW50YXRpb24+MTwvdGlmZjpPcmllbnRhdGlvbj4KICAgICAgPC9yZGY6RGVzY3JpcHRpb24+CiAgIDwvcmRmOlJERj4KPC94OnhtcG1ldGE+ClayNggAAAA5SURBVBgZY/wnIPafAQT+/2f4x8/DwPzoPsPd4mKGvOwsBrGfPxn+MjKCpZnAJBHEqEK8gUR08AAABzoNH0XFwToAAAAASUVORK5CYII=" />

    <text class="big" x="100" y="950" fill="black">v3.1</text>
    <rect width="100" height="100" x="0" y="900" fill="#00FF00" />

</svg>
```

which renders with a broken image tag (in chrome)

<img width="506" alt="image" src="https://user-images.githubusercontent.com/514002/164995264-31c2c0cb-dc1a-4976-afee-3380a2f06118.png">

**Comment by dcsan** [comment]
doh, wrong image type!
this works

```svg
    <image x="0" y="0" width="500" height="500" href="data:image/png;base64,iVBORw...." />
```
