### ISSUE TITLE
Is it possible to use & extract fourth channel (IR)?

### ISSUE THREAD

**Issue by dmitrizzle** [lovell/sharp#2847]
## What are you trying to achieve?
Certain film scanners can provide files with four channels: R, G, B, and IR (infrared). In theory, the latter channel can be used as a subtraction mask for the rest of the channels to minimize/remove dust and scratches from colour negative film.

I'd like to make sure that Sharp can take that input, isolate the IR channel, and use it as a mask.

## Have you searched for similar questions?
Yes.

## Are you able to provide a minimal, standalone code sample that demonstrates this question?
Not yet.

## Are you able to provide a sample image that helps explain the question?
I will provide an image with 4 channels if that's necessary to answer this question.

**Comment by lovell** [comment]
Did you see the [extractChannel](https://sharp.pixelplumbing.com/api-channel#extractchannel) operation? In your example, IR would be channel 3.

**Comment by dmitrizzle** [comment]
Makes sense, thank you 😅
