### ISSUE TITLE
Cannot find module '../build/Release/sharp-win32-x64.node'

### ISSUE THREAD

**Issue by webnoob** [lovell/sharp#2848]
Hi,

Pretty sure I've followed all the steps provided. I'm using `yarn add sharp`. I've also tried using `npm -i sharp` and other variations with me specifying the platform / arch as well.

This is the installed module: 
![image](https://user-images.githubusercontent.com/10404747/129893360-57c961a5-d305-47da-aa33-e3cde84ccd7c.png)

And the actual error: 
![image](https://user-images.githubusercontent.com/10404747/129893552-e75e169f-fdce-472d-8cea-6c978ec973a2.png)

Specs: 
![image](https://user-images.githubusercontent.com/10404747/129893205-aebeeada-864b-4110-b155-9f621f2a76d4.png)

I don't really know where to go from here with this.

**Comment by lovell** [comment]
What is the complete output of running `npm install --verbose sharp`?

**Comment by lovell** [comment]
Oh, the prebuilt tarballs for sharp v0.29.0 win32-x64 appears to be missing a file... let me fix this now.

**Comment by lovell** [comment]
Please can you remove any cached files from the `_prebuilds` directory in the npm cache (run `npm get cache` to show where this is located) any try again.

**Comment by webnoob** [comment]
> Please can you remove any cached files from the `_prebuilds` directory in the npm cache (run `npm get cache` to show where this is located) any try again.

Perfect - that's fixed it. Thanks so much for your speedy response!

**Comment by lovell** [comment]
Thanks for reporting this. Glad we got it fixed before the whole (Windows) world came beating at the door with the same problem.

**Comment by webnoob** [comment]
Took me longer to install the module than it did to make it work with my code.

Amazing job - thanks so much for your hard work on this.

**Comment by cduff** [comment]
Had the same problem and fixed by manually deleting files from the `_prebuilds` directory. Glad I found this issue. Thanks @webnoob and @lovell.
