### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by Wilson13** [lovell/sharp#2849]
This is not directly related to the library itself, but since a lot of documentation and knowledge depends on this website: [sharp.pixelplumbing.com](https://sharp.pixelplumbing.com). I'm just wondering if I'm the only one not able to load the site properly?

**Comment by lovell** [comment]
Someone reported yesterday that they had just run into a similar problem on a work machine, which presumably is using a misconfigured corporate web proxy and/or VPN - see https://twitter.com/justandydesign1/status/1427934084949581825

Do you see any errors in the browser console? Are any JS files not loading?

**Comment by Wilson13** [comment]
> Someone reported yesterday that they had just run into a similar problem on a work machine, which presumably is using a misconfigured corporate web proxy and/or VPN - see https://twitter.com/justandydesign1/status/1427934084949581825
> 
> Do you see any errors in the browser console? Are any JS files not loading?

Thank you for the swift reply, I think you're right.

**Comment by lovell** [comment]
What were the errors, if any, as we might be able to fix them? My best guess would be that this relates to jsdelivr.

**Comment by Wilson13** [comment]
These are the errors from the inspect console and true enough jsdelivr was mentioned.

![Screenshot 2021-08-19 at 4 00 08 PM](https://user-images.githubusercontent.com/5605451/130030958-19328357-c98e-40c0-b33c-fe717473d95e.png)

**Comment by lovell** [comment]
Thank you, it looks like you're using an OpenDNS-based web proxy that can both read *and modify* everything you access; I hope you trust it.

This came up previously at #2739

I'll see if we can remove the reliance on jsdelivr entirely.

**Comment by Wilson13** [comment]
@lovell 

It's a work device hence I really have no say over that. 

Absolutely appreciate your time and effort on analysing this issue I'm facing. I'm also working at my end to see if there's any way to configure the proxy so I'll be able to access the site.

And thank you for this awesome library!

**Comment by lovell** [comment]
Commit https://github.com/lovell/sharp/commit/17e50de5f00ff98caa97880b6418ef622d292c69 removes the dependence on jsdelivr for JS source code.
