### ISSUE TITLE
Regression in v0.29, it has bigger file sizes for avif images (37% worse)

### ISSUE THREAD

**Issue by samuelfernandez** [lovell/sharp#2850]
**Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?** 

Yes, actually caught the regression in my project with a renovate upgrade https://github.com/ng-easy/platform/pull/174

**What are the steps to reproduce?**

Compress an image to avif format

**What is the expected behaviour?**

Keep small filesizes

**Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?**

Let me know if truly needed

**Are you able to provide a sample image that helps explain the problem?**

Yes, attached [size regression avif sharp v0.29.zip](https://github.com/lovell/sharp/files/7014856/size.regression.avif.sharp.v0.29.zip)

**What is the output of running `npx envinfo --binaries --system`?**

```
  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 12.73 GB / 31.88 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
```

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/changelog#v0290---17th-august-2021

>  v0.29.0 - 17th August 2021
> AVIF encoding now defaults to 4:4:4 chroma subsampling. #2562

Try adding `.avif({ chromaSubsampling: '4:2:0' })` to use the same behaviour as the previous version.

Perhaps you could also experiment with the `quality` and `speed` settings to see what combination works best for your scenario.

https://sharp.pixelplumbing.com/api-output#avif

**Comment by samuelfernandez** [comment]
That was a fast answer! I noticed a similar problem with heif format, is there a similar fix?
