### ISSUE TITLE
Better document toFile behavior when directory are missing in the path

### ISSUE THREAD

**Issue by marcandjulien** [lovell/sharp#2851]
What are you trying to achieve?
I think that the documentation of the toFile function could be better. I lost a couple of hours before figuring out that the toFile function did not create the missing directories. I think we could mention in the doc that it is the library user's responsibility to check that the directory tree is coherent. Furthermore, in my case, sharp was failing silently (or was crashing the app before node could flush the log buffer).

Have you searched for similar feature requests?
#639 #874

What would you expect the API to look like?
N/A

What alternatives have you considered?
N/A

Is there a sample image that helps explain?
N/A

**Comment by lovell** [comment]
Added via commit https://github.com/lovell/sharp/commit/4e84f743e419abeb67614552f9f2692203f4262f

https://sharp.pixelplumbing.com/api-output#tofile (might have to wait a couple of hours for the CDN cache to clear)
