### ISSUE TITLE
Is it possible to use magickload?

### ISSUE THREAD

**Issue by 0x6A75616E** [lovell/sharp#2852]
I'm trying to convert RAW images to JPG. I've got vips compiled with magick support, and the following cli command works:

`vips magickload /test-photos/Nikon/RAW_NIKON_D3200.NEF /test-photos/Nikon/RAW_NIKON_D3200.JPG`

Now, when I try the same thing with Sharp, I get a really low resolution JPG as the output.

```
const sharp = require('sharp');
var fs = require('fs');

const filename = `/test-photos/Nikon/RAW_NIKON_D3200.NEF`
var readStream = fs.createReadStream(filename);


(() => {

    var writeStream = fs.createWriteStream(`${filename}.jpg`);

    writeStream.on('finish', () => {
        console.log("DONE")
    })

    
    const conv = sharp({
        failOnError: false
    })

    conv
        .jpeg({
            quality: 100,
            force: true
        })

    conv.pipe(writeStream)

    readStream.pipe(conv)

})()

```

I suspect what's happening is that the raw input has an embedded jpg thumbnail, and that's what's being converted here. Is there a way for me to specify that I want to use the full image data as input?

**Comment by lovell** [comment]
I think Nikon RAW files masquerade as TIFF files. Given you're building your own libvips, try compiling it without libtiff support via `./configure --without-tiff`

**Comment by 0x6A75616E** [comment]
Thanks @lovell. That'd most likely work, but wouldn't that leave me with no tiff support overall? That's something I still use.

Seems like the `magickload` command would work well. I was only wondering if it had been implemented. If it hasn't already, I may be able to put together a PR.

**Comment by lovell** [comment]
sharp currently relies on libvips to determine the relevant loader for a given input and I'm unsure if the added complexity (error handling, testing etc.) of code in sharp to specify the loader is worth it.

Given you're building your own libvips, perhaps you could patch one/both of the relative `priority` values?

https://github.com/libvips/libvips/blob/97f5417aaa16c0eda19d98816b823bc92ebc93b3/libvips/foreign/tiffload.c#L182
https://github.com/libvips/libvips/blob/97f5417aaa16c0eda19d98816b823bc92ebc93b3/libvips/foreign/magick7load.c#L356

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
