### ISSUE TITLE
sharp.format.avif returns undefined

### ISSUE THREAD

**Issue by akiryazov** [lovell/sharp#2853]
I am using latest version of sharp (0.29.0) and I noticed that ``sharp.format.avif`` returns undefined. Would you please investigate?

Best regards,
Angel Kiryazov

**Comment by lovell** [comment]
Hi, please see the `sharp.format.heif` property (AVIF files are HEIF files that use AV1 compression).
```sh
$ node -p "require('sharp').format.heif"
{
  id: 'heif',
  input: { file: true, buffer: true, stream: true },
  output: { file: true, buffer: true, stream: true }
}
```

**Comment by akiryazov** [comment]
Yes, I figured that out. Just wanted to point if this is an actual defect so you can take further action if needed :)

Thanks for your quick answer!

Best regards,
Angel Kiryazov
