### ISSUE TITLE
Incomplete cache in "_prebuilds" - breaks sharp installation without recovering

### ISSUE THREAD

**Issue by wardpeet** [lovell/sharp#2859]
I've been testing sharp@0.29.0 and encountered an issue on windows as one of the cached files got corrupted and I never got a proper error so I started digging.

The "3d5a53-sharp-v0.29.0-napi-v5-win32-x64.tar.gz" file was not fully downloaded so Sharp didn't copy all the files and threw an error.

![image](https://user-images.githubusercontent.com/1120926/130787218-79809484-2c7c-434c-9818-6e1f66d1e919.png)

Would it be beneficial to enable md5 checks on these caches to recover?

**Comment by lovell** [comment]
@wardpeet I'm not sure there's much we can do in sharp for this. If you hadn't seen, there's been recent movement in package managers with RFCs to gather feedback for "distributions" (npm) and "variants" (yarn), and either/both feel like the right approach to me.

That said, I'll close this issue, but please feel free to reopen with any suggestions for things we might be able to do in the meantime.
