### ISSUE TITLE
WebAssembly / CloudFlare workers support

### ISSUE THREAD

**Issue by antony** [lovell/sharp#2863]
What are you trying to achieve?

We'd love to deploy this on CloudFlare workers. As of early this year, libvips is now compiled for that target, so as I understand it, the remaining step is to compile sharp as WebAssembly.

Libvips issue is here https://github.com/libvips/libvips/issues/192

Have you searched for similar feature requests?

Yes - There is https://github.com/lovell/sharp/issues/1476 but it was closed and locked prior to the libvips changes.

What would you expect the API to look like?

I'm not at all familiar with WebAssembly, I'm afraid.

What alternatives have you considered?

Not using cloudflare workers

**Comment by okikio** [comment]
`wasm-vips` is now a thing, so, is it possible to have a wasm version of sharp?

**Comment by mukhtharcm** [comment]
Any update on this?

**Comment by eli-front** [comment]
Any updates here?

**Comment by hadnet** [comment]
It would be great if this package could work on CFW.

**Comment by nilansaha** [comment]
Nothing yet it seems. I coded up an image processing tool and then realized this does not work in Cloudflare workers

**Comment by peterhirn** [comment]
> `wasm-vips` is now a thing, so, is it possible to have a wasm version of sharp?

Unfortunately `wasm-vips` will not be able to run on Cloudflare in the foreseeable future, see https://github.com/kleisauke/wasm-vips/issues/2#issuecomment-1187416552

**Comment by lovell** [comment]
Experimental support for WebAssembly environments will be arriving in v0.33.0 - please see https://github.com/lovell/sharp/issues/3336 - however Cloudflare Workers does not currently support threading or the Web Workers API so you'll need to ask Cloudflare about this lack of support if you need to use their services.

**Comment by ThatGuySam** [comment]
> Experimental support for WebAssembly environments will be arriving in v0.33.0 - please see #3336 - however Cloudflare Workers does not currently support threading or the Web Workers API so you'll need to ask Cloudflare about this lack of support if you need to use their services.

@lovell Is there any kind of Single-Threaded mode for Sharp? 

Even a dramatically slower option could still be useful for processing ultra-small images such as 100x100 thumbnails, Favicons, 50x50 Profile Picture, etc...

**Comment by lovell** [comment]
@ThatGuySam Threading is fairly fundamental to libvips as well as an increasing number of the dependencies it relies on for image codecs. From what I can tell, Cloudflare Workers appears to be more suitable for tasks that are I/O bound rather than CPU bound. If performance isn't of concern then perhaps try [jimp](https://www.npmjs.com/package/jimp).

**Comment by tibotiber** [comment]
Pointing to [jimp](https://jimp-dev.github.io/jimp/) was super useful, it works in workers if you don't use custom Jimps. Thanks @lovell!

**Comment by mariusbolik** [comment]
> Pointing to [jimp](https://jimp-dev.github.io/jimp/) was super useful, it works in workers if you don't use custom Jimps. Thanks @lovell!

Yes, Jimp is a great solution. But keep in Mind that it takes nearly 10 times longer than Sharp to perform certain actions.

**Comment by tibotiber** [comment]
Agreed and thanks for pointing it out.
Here i'm using it in cloudflare workers, where sharp is not an option at all it seems.

**Comment by lovell** [comment]
Cloudflare Workers now supports use of OCI/Docker container images, provides scale-to-zero semantics and should "just work".

https://developers.cloudflare.com/containers/

(I visited the Cloudflare London office last year and someone mentioned this might be coming. I almost certainly signed an NDA on the way in but IIRC it uses gvisor under the hood, the same tech that Google uses for Cloud Run.)

**Comment by tibotiber** [comment]
That's pretty cool. Not worth the setup for my use-case i think (just the time to figure out the whole thing since i'm not a docker pro), but very cool nonetheless. Thanks @lovell
