### ISSUE TITLE
Error import sharp in vuejs

### ISSUE THREAD

**Issue by nhokvouu** [lovell/sharp#2866]
I can import sharp in vuejs 

error  in ./node_modules/sharp/node_modules/color/index.js

Module parse failed: Identifier directly after number (257:26)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|               for (const [i, element] of rgb.entries()) {
|                       const chan = element / 255;
>                       lum[i] = (chan <= 0.039_28) ? chan / 12.92 : ((chan + 0.055) / 1.055) ** 2.4;
|               }
| 

 @ ./node_modules/sharp/lib/colour.js 3:14-30
 @ ./node_modules/sharp/lib/index.js

**Comment by lovell** [comment]
sharp requires a Node.js runtime, so won't work in a web browser.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
