### ISSUE TITLE
RAW images give "Input file contains unsupported image format", but vips/ImageMagick handle them fine

### ISSUE THREAD

**Issue by paulstraw** [lovell/sharp#2867]
> Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

I currently have `lovell/sharp` specified in package.json, as reproducing this issue requires the fix for #2864.

> What are the steps to reproduce?

I've updated the example repo from my last issue with steps: https://github.com/paulstraw/sharp-magick-lambda

> What is the expected behaviour?

Metadata can be extracted from camera RAW files.

> Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

https://github.com/paulstraw/sharp-magick-lambda

> Are you able to provide a sample image that helps explain the problem?

Sample images in the linked repo

> What is the output of running `npx envinfo --binaries --system`?

```bash
npx: installed 1 in 2.449s

  System:
    OS: Linux 5.10 Amazon Linux 2
    CPU: (4) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 667.21 MB / 1.94 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 14.17.5 - /var/lang/bin/node
    npm: 6.14.14 - /var/lang/bin/npm
```

**Comment by lovell** [comment]
RAW images often masquerade as TIFF images, which these examples appear to do also, so libvips will use libtiff to open these however they aren't quite valid TIFF images and fail.

```
$ vipsheader -a Sony-A550.ARW 
(vipsheader:18334): VIPS-WARNING **: 19:35:37.776: Unknown field with tag 50341 (0xc4a5) encountered
vipsheader: VipsForeignLoad: "Sony-A550.ARW" is not a known file format
```

#2852 provides a suggested workaround for changing the priority of magickload.

**Comment by paulstraw** [comment]
Thanks for the information, that's very helpful. The priority workaround in #2852 makes sense, but I'd love the ability to continue using the libvips native TIFF support as well.

My plan was to detect raw images based on Sharp's metadata output, then convert them to TIFF with `dcraw -w` to preserve camera white balance settings. I would then use that TIFF output as input to Sharp for actual additional processing. It kind of seems like my only real option is going to be using IM for the "second generation" TIFF processing as well (since its priority will be higher than vips' internal handler in my custom build).  I believe LibRaw has a similar `use_camera_wb` setting, but as far as I can tell there's no way to set it via libvips/sharp.

**Comment by lovell** [comment]
I've not tried it, but I'm aware that one of the developers at Elastic (who use sharp in some of their tooling) created https://github.com/justinkambic/libraw.js that might help. Given you need to support both TIFF and RAW files, a possible workflow might be when sharp/libvips thinks a file is TIFF but then generates a decoding error, you could fall back to trying libraw.js next.
