### ISSUE TITLE
Error: Input buffer contains unsupported image format ( file svg )

### ISSUE THREAD

**Issue by basefox** [lovell/sharp#2869]
What are you trying to achieve? how to resolved this error

Have you searched for similar questions? already searched

Are you able to provide a minimal, standalone code sample that demonstrates this question?

```
conn.minioClientDev.getObject(item.name, obj.name, function (err, dataStream) {
                  if (err) {
                    return console.log(err)
                  }
                  dataStream.on('data', async (chunk) => {
                    size += chunk.length
                    libUsed = 'sharp';
                    fileNamed = obj.name
                    await sharp(chunk)
                    .toFile(
                      pathFile + fileNamed, function(err, info) {
                        if (err) {
                          console.log(err.toString() , item.name, ' File : ' , obj.name);
                        }else{
                          console.log(`download sukses : ${libUsed}`,' # '+ JSON.stringify(info));
                        }
                      }
                    )

                  })
                  dataStream.on('end', async() => {
                    //
                  })
                  dataStream.on('error', function(err) {
                    console.log(err)
                  })
                })
```

Are you able to provide a sample image that helps explain the question?

sample error : 

```
Error: Input buffer contains unsupported image format subscribe  File :  f74b4dd5-6e77-448b-8737-ac50f647cdf7.svg
Error: Input buffer contains unsupported image format subscribe  File :  c3317247-9a66-4430-ae97-97ad1c8bbf1b.svg
```

**Comment by lovell** [comment]
Hi, it looks like this code is only using the first data chunk from `dataStream`. You should be able to simply this with something like the following:
```js
const transform = sharp();
dataStream.pipe(transform);
await transform.toFile(pathFile + fileNamed);
```

**Comment by basefox** [comment]
> Hi, it looks like this code is only using the first data chunk from `dataStream`. You should be able to simply this with something like the following:
> 
> ```js
> const transform = sharp();
> dataStream.pipe(transform);
> await transform.toFile(pathFile + fileNamed);
> ```


my code has been modify with your instruction , and the result still same  :

sample output : 

```
 [Error: Input buffer contains unsupported image format] {
  name: 'f74b4dd5-6e77-448b-8737-ac50f647cdf7.svg',
  lastModified: 2021-08-10T02:12:39.835Z,
  etag: '09a155449e86788df7f97e309164ccd5',
  size: 136690,
  metadata: { 'content-type': 'image/svg+xml' }
}
[Error: Input buffer contains unsupported image format] {
  name: 'f74b4dd5-6e77-448b-8737-ac50f647cdf7.svg',
  lastModified: 2021-08-10T02:12:39.835Z,
  etag: '09a155449e86788df7f97e309164ccd5',
  size: 136690,
  metadata: { 'content-type': 'image/svg+xml' }
}
```

**Comment by basefox** [comment]
> Hi, it looks like this code is only using the first data chunk from `dataStream`. You should be able to simply this with something like the following:
> 
> ```js
> const transform = sharp();
> dataStream.pipe(transform);
> await transform.toFile(pathFile + fileNamed);
> ```

Hello sir... , many2 Thanks for your support and instruction .. 

![image](https://user-images.githubusercontent.com/44537592/131474772-a0e5d6e2-46c7-481d-b3d8-6879f9f47a06.png)

Thank you
