### ISSUE TITLE
i am trying to convert heic image into jpeg 

### ISSUE THREAD

**Issue by bhandurejitu** [lovell/sharp#2871]
source: bad seek to 41473\\nheif: Unsupported feature: Unsupported codec (4.3000)

in AWS Lambda I don't want to install other dependencies globally 

is there any solution?

my aim is just convert image heic to jpeg

**Comment by lovell** [comment]
The prebuilt binaries provided by sharp do not provide support for the patent-encumbered HEIC format so you'll need to find an alternative solution.

**Comment by joshdance** [comment]
you can use https://www.npmjs.com/package/heic-convert instead of sharp for out of the box heic support.
