### ISSUE TITLE
composite fails with empty array

### ISSUE THREAD

**Issue by fulldecent** [lovell/sharp#2872]
was expecting a no-op

**Comment by lovell** [comment]
Hello, the following code works for me:
```js
await sharp({
  create: {
    width: 1,
    height: 1,
    channels: 3,
    background: 'red'
  }
})
  .composite([])
  .toFile('out.png');
```

Are you able to provide a code sample that demonstrates this problem?

**Comment by d-s-i** [comment]
Hello,
I am trying to use your code @fulldecent and for me it doesn't work even if the composites array isn't empty. I am not sure if it's normal, but it always return a never fulfilled promised and the image is never updated ...

**Comment by lovell** [comment]
@fulldecent Were you able to make any progress with this?

**Comment by fulldecent** [comment]
Got it, sorry. Yes it looks like my issue was actually https://github.com/lovell/sharp/issues/2873 and I had thought the problem was the composite.

Closing.
