### ISSUE TITLE
shows incorrect density (cached metadata) if writing to the same file few times with different density

### ISSUE THREAD

**Issue by eugene-piatenko** [lovell/sharp#2874]
> Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

YES, sharp@0.29.0

> What are the steps to reproduce?

1. Read any image, for example inp.jpg with 100 DPI (just example)
2. Write to output image with 200 DPI
3. Read again same (any) input image with any DPI, 100 DPI for example
4. Write to SAME output image with 300 DPI
5. Checking output image DPI by metadata() function - it shows 200 DPI (first set)
6. and if you overwrite again and again same output image with different DPI, metadata() always will show (first) 200 DPI

probably steps 1 and 3 not important,
important is writing to the same file with different DPI
checking that file DPI will show always one initial value, that was set first, not last one

so looks like for each file (filename) metadata() DPI information is cached
solution is to call EACH time `sharp.cache(false);` then `sharp.cache(true);` to clean ALL CACHE
but it's ugly solution as it slows down all image manipulations

> What is the expected behaviour?

solution - on each write to the same file (filename), just clean it's metadata() information

> Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

```javascript
(async function() {
  var img, info, inp_file, out_file;
  inp_file = 'inp.jpg'; // input file with density for example 100 dpi
  out_file = 'out.jpg';

  // STEP 1 - increasing density + 100
  // reading inp.jpg and writing out.jpg with density + 100, should be 200 dpi
  img = sharp(inp_file);
  info = (await img.metadata());
  console.log(inp_file, info.density);
  img.withMetadata({
    density: info.density + 100
  });
  await img.toFile(out_file);

  // checking out.jpg density - should show 200 dpi
  img = sharp(out_file);
  info = (await img.metadata());
  console.log(out_file, info.density);


  // STEP 2 - same as STEP 1, but increasing density + 200
  // reading inp.jpg and writing out.jpg with density + 200, should be 300 dpi
  img = sharp(inp_file);
  info = (await img.metadata());
  console.log(inp_file, info.density);
  img.withMetadata({
    density: info.density + 200
  });
  await img.toFile(out_file);

  // checking out.jpg density - should show 300 dpi - but shows 200 dpi
  img = sharp(out_file);
  info = (await img.metadata());
  return console.log(out_file, info.density);


})();
```

> Are you able to provide a sample image that helps explain the problem?

any image

> What is the output of running `npx envinfo --binaries --system`?

pls, if you really need it - I will post it, I'm using Nodejs 16.0 on MacOS Catalina

**Comment by lovell** [comment]
Hello, as you've seen, you'll need to disable caching in libvips if you intend to reuse filenames. More fine-grained control over the cache is possible, e.g. `sharp.cache({ files: 0 })` will still provide some caching benefits.

https://sharp.pixelplumbing.com/api-utility#cache

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
