### ISSUE TITLE
Cannot install in nodejs apps on cpanel

### ISSUE THREAD

**Issue by martinamerigo** [lovell/sharp#2876]
stderr:
npm WARN lifecycle The node binary used for scripts is /home/amatiiom/nodevenv/landingpage/10/bin/node but npm is using /opt/alt/alt-nodejs10/root/usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

Something went wrong installing the "sharp" module

/usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.16' not found (required by /home/amatiiom/landingpage/node_modules/sharp/build/Release/sharp-linux-x64.node)

ERR! sharp Use with glibc version 2.12 requires manual installation of libvips >= 8.8.1 
info sharp Please see https://sharp.pixelplumbing.com/page/install for required dependencies

but I can't custom libvips in cpanel server

**Comment by lovell** [comment]
This looks like you're using RHEL or CentOS 6, which is too old for the prebuilt binaries. Are you able to upgrade to RHEL/CentOS 7?

**Comment by martinamerigo** [comment]
I can't upgrade RHEL/CENTOS because it's already provided from the hosting/server. Is there any other way for me to use sharp module with that RHEL/CentOS6??

**Comment by lovell** [comment]
CentOS 6 reached end-of-life in November 2020 and is no longer actively maintained. CentOS 7 was first released over 7 years ago, in July 2014; perhaps you need a new hosting provider?

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
