### ISSUE TITLE
Testing sharp with memfs error: [Error: Input file is missing]

### ISSUE THREAD

**Issue by koonfoon** [lovell/sharp#2877]
I had trouble testing my code that implement [```sharp```](https://www.npmjs.com/package/sharp) and [```memfs```](https://www.npmjs.com/package/memfs). I has codes that download image and cropping it to certain dimension. I use [```sharp```](https://www.npmjs.com/package/sharp) to achieve the cropping. When it comes testing, I use ```jest``` and [```memfs```](https://www.npmjs.com/package/memfs). My test code has 2 parts:
1. Download a image and save to mock volume/fileSystem that created with ```memfs```.
2. Cropping the downloaded image to certain dimension with ```sharp```.  

Part 1 worked perfectly, was able to download image to the fake volume and asserted with ```jest``` (exist in the fake volume).  
**But part 2 gave me error**:```[Error: Input file is missing]```.
~~~
const sizeToCrop = {
            width: 378,
            height: 538,
            left: 422,
            top: 0,
        };

sharp(`./downloadedImage.jpg`)
            .extract(sizeToCrop)
            .toFile(`./CroppedImage.jpg`)
            .then(() => {
                console.log(`resolve!`);
            })
            .catch((err: Error) => {
                console.log(err);
                return Promise.reject();
            });

// Error message: [Error: Input file is missing]
~~~
But when I test it with real volume. It worked fine.  
Anyone has idea how to solve this?
Thank you.

**Comment by lovell** [comment]
It looks like `memfs` is a memory-based filesystem, so you'll probably need to use something like the following:
```js
const { fs } = require('memfs');
const file = fs.readFileSync('./downloadedImage.jpg');
sharp(file)...
```

**Comment by koonfoon** [comment]
@lovell **your solution worked**, but when my codes hit ```.toFile(`./CroppedImage.jpg`)```, I got this error:
~~~
[Error: /temp/ofje-300-poster.jpg: unable to open for write
    unix error: No such file or directory
    ]
~~~
I guess what I need to do now is to figure out how to mock ```.tofile()```
~~~
// Inside code.test.ts

jest.mock('sharp', () => {
    const sharp = jest.requireActual('sharp');
    const { vol } = require('memfs');
    const mockSharp = (path: string): any => {
        const file = vol.readFileSync(path);
        return sharp(file);
    };
    return mockSharp;
});



// Inside code.ts

import sharp from 'sharp';

sharp(`./downloadedImage.jpg`)
            .extract(sizeToCrop)
            .toFile(`./CroppedImage.jpg`)
            .then(() => {
                console.log(`resolve!`);
            })
            .catch((err: Error) => {
                console.log(err);
                return Promise.reject();
            });
~~~
I am reading some solutions from [here](https://stackoverflow.com/questions/56589770/mocking-a-node-module-which-uses-chained-function-calls-with-jest-in-node) and [here](https://stackoverflow.com/questions/46158728/how-to-mock-third-party-modules-with-jest) for how to chain mocking.

**Comment by lovell** [comment]
You'll probably need to implement a mock `toFile` function that calls sharp's `toBuffer` then uses memfs' `writeFileSync`.

**Comment by koonfoon** [comment]
> You'll probably need to implement a mock `toFile` function that calls sharp's `toBuffer` then uses memfs' `writeFileSync`.

Well, this is beyond my current knowledge 😓. I haven't even figure out how to chain mock. Hope will figure out some day. Thanks.

**Comment by koonfoon** [comment]
The following jest mock codes worked for me for now:
~~~
// Inside code.test.ts

jest.mock('sharp', () => {
    const sharp = jest.requireActual('sharp');
    const { vol } = require('memfs');
    let inputFilePath: string;
    let sizeToCrop: any;
    let outputFilePath: string;
    const toFile = async (writePath: string): Promise<any> => {
        outputFilePath = writePath;
        try {
            return await starCropping();
        } catch (error) {
            console.log(`Error in mocked toFile()`, error);
        }
    };
    const extract = (dimensionSize: string): any => {
        sizeToCrop = dimensionSize;
        return { toFile };
    };
    const mockSharp = (readPath: string): any => {
        inputFilePath = readPath;
        return { extract };
    };
    async function starCropping(): Promise<void> {
        try {
            const inputFile = vol.readFileSync(inputFilePath);
            const imageBuffer = await sharp(inputFile).extract(sizeToCrop).toBuffer();
            vol.writeFileSync(outputFilePath, imageBuffer);
        } catch (error) {
            console.log(`Error in mocked sharp module`, error);
            return Promise.reject();
        }
    }

    return mockSharp;
});
~~~

**Comment by ogmaro** [comment]
> It looks like `memfs` is a memory-based filesystem;

 This was helpful.
 I, however, used `fs`

**Comment by foxxyz** [comment]
To anyone else looking for a way to easily mock `sharp` writing to the filesystem using `memfs`, this was an easier method than @koonfoon's above:
```
jest.mock('sharp', () => {
    const { fs } = require('memfs')
    const sharp = jest.requireActual('sharp')
    sharp.prototype.toFile = async function(fileout) {
        fs.writeFileSync(fileout, await this.toBuffer())
    }
    return sharp
})
```
