### ISSUE TITLE
Sharp do not release the gif input image

### ISSUE THREAD

**Issue by gilles-crealp** [lovell/sharp#2880]
For example, it is not possible to delete the gif image after passing it to Sharp.

``` javascript
import sharp from 'sharp'
import fs from 'fs'

let input = 'link to a gif image'
let output = '…'

async function start() {
  await sharp(input).png().toFile(output)

  fs.rmSync(input) // KO
  fs.rmSync(output) // OK
}

start()
```

**System**
- OS: Windows 10 10.0.19042
- CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
- Memory: 1.49 GB / 7.94 GB

**Binaries**
- Node: 14.17.0
- Yarn: 1.22.10
- npm: 7.19.0

**Comment by lovell** [comment]
Hi, did you see https://sharp.pixelplumbing.com/api-utility#cache
```js
sharp.cache(false);
```

**Comment by gilles-crealp** [comment]
Oops, sorry I hadn't seen. :sweat_smile:
