### ISSUE TITLE
Replicate image magick clut command in sharp

### ISSUE THREAD

**Issue by crizaf** [lovell/sharp#2882]
What are you trying to achieve?
A similar effect to image magick clut, https://imagemagick.org/script/command-line-options.php#clut. I'm trying to combine a grayscale image with a gradient.
Have you searched for similar questions?
I looked for similar questions but couldn't find one with this requirement
Are you able to provide a minimal, standalone code sample that demonstrates this question?
sharp("input.jpg")
    .composite([{ input: "gd.jpg" , blend: 'overlay'}])
    .toFile(`output.jpg`);
I tried all possible blend values, none provided an output similar to what i got from image magick
Are you able to provide a sample image that helps explain the question?
Input:
![input](https://user-images.githubusercontent.com/79195601/132858830-248003e3-8cf8-446f-a286-845db81fef42.jpg)
Gradient:
![gd](https://user-images.githubusercontent.com/79195601/132858875-18ca92f5-e015-4f57-81a5-86e55a6fd21e.jpg)
Sharp output:
![output](https://user-images.githubusercontent.com/79195601/132858912-5dc29d05-c02a-460a-b253-75b4f06bc030.jpg)
Image magick clut output:
![expected_output](https://user-images.githubusercontent.com/79195601/132858955-124d4f6b-6d9e-432a-922a-e4b2e2231953.jpg)

**Comment by lovell** [comment]
Hi, this looks like #1441 - libvips provides a `maplut` operation that we'd need to expose in sharp.

**Comment by crizaf** [comment]
Thank you very much for the answer. Is there a plan for introducing this ``maplut`` operation in sharp?

**Comment by lovell** [comment]
Let's track this at #1441. All issues tagged as "enhancement" are future possible enhancements and PRs to implement these are always welcome, if you're able.
