### ISSUE TITLE
SVG: direction="rtl" ignores text-anchor

### ISSUE THREAD

**Issue by AmirABody** [lovell/sharp#2885]
Hello there,
I have a problem when setting the direction="rtl" for text tag. In the SVG output, the attribute swaps the text-anchor meaning for the tag but in the PNG output, it remains the same. I don't know how to handle the problem, I would be grateful if anybody helps me.

**Comment by lovell** [comment]
Please can you provide a sample image that helps explain the question?

**Comment by AmirABody** [comment]
> Please can you provide a sample image that helps explain the question?

Here's an example:
```
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" xml:lang="fa">

<!--StartFragment-->

    <g direction="rtl" font-family="Dana-FaNum" font-weight="bold" font-size="16">
        <text x="50%" y="260" text-anchor="middle" font-family="Dana">x=50%</text>
        <line x1="50%" y1="0" x2="50%" y2="1000" stroke="red"/>
        <text x="50%" y="300" text-anchor="start">مشکلی در کتابخانه شارپ!</text>
    </g>

<!--EndFragment-->
</svg>
```
The SVG output looks like this:
![SVG Output](C:\Users\Mahdi\Desktop\svg.jpg)
But unfortunately, the PNG output doesn't look the same:
![PNG Output](C:\Users\Mahdi\Desktop\png.jpg)

That's because direction="rtl" attribute swaps the meaning of text-anchor="start" for SVG output, but for the PNG output, there's not any change!

If I omit the direction="rtl" attribute from the parent tag, both outputs look identical but the exclamation mark is not placed correctly in the RTL text (Persian).
Both the SVG & PNG output in absence of direction="rtl":
![](C:\Users\Mahdi\Desktop\without.jpg)

Note that if I set the text-anchor to "middle", there's no difference between the two outputs, the problem appears when we want the text-anchor to be either "start" or "end".

Thank you very much for the prompt reply.

**Comment by AmirABody** [comment]
> Please can you provide a sample image that helps explain the question?

Here's an example:
```
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" xml:lang="fa">

<!--StartFragment-->

    <g direction="rtl" font-family="Dana-FaNum" font-weight="bold" font-size="16">
        <text x="50%" y="260" text-anchor="middle" font-family="Dana">x=50%</text>
        <line x1="50%" y1="0" x2="50%" y2="1000" stroke="red"/>
        <text x="50%" y="300" text-anchor="start">مشکلی در کتابخانه شارپ!</text>
    </g>

<!--EndFragment-->
</svg>
```
The SVG output looks like this:
![svg](https://user-images.githubusercontent.com/40426839/132976580-6292ecb4-50cd-4755-88a6-7e44eac3fb29.JPG)
But unfortunately, the PNG output doesn't look the same:
![png](https://user-images.githubusercontent.com/40426839/132976587-0a1882a5-7114-4cc7-9a2a-f912b5e33bda.JPG)

That's because direction="rtl" attribute swaps the meaning of text-anchor="start" for SVG output, but for the PNG output, there's not any change!

If I omit the direction="rtl" attribute from the parent tag, both outputs look identical but the exclamation mark is not placed correctly in the RTL text (Persian).
Both the SVG & PNG output in absence of direction="rtl":
![without](https://user-images.githubusercontent.com/40426839/132976598-565ed941-646d-4cae-ac91-559863ec8259.JPG)

Note that if I set the text-anchor to "middle", there's no difference between the two outputs, the problem appears when we want the text-anchor to be either "start" or "end".

Thank you very much for the prompt reply.

**Comment by lovell** [comment]
Thank you, this is a great example, I also see the same problem when converting this sample SVG to PNG using the `rsvg-convert` command line tool.

Please can you report this upstream at https://gitlab.gnome.org/GNOME/librsvg

(As an aside, this looks like the same problem as previously-reported in #2722, but I'm not sure why that issue is closed.)

**Comment by lovell** [comment]
https://gitlab.gnome.org/GNOME/librsvg/-/issues/789

**Comment by lovell** [comment]
v0.30.0 now available with prebuilt binaries that include a version of librsvg with the upstream fix.
