### ISSUE TITLE
SVG: tspan tag inside rtl text reverses the ordering of words

### ISSUE THREAD

**Issue by AmirABody** [lovell/sharp#2886]
Hi there, 

In the code below:
```
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xml:lang="fa" direction="rtl">
    <g font-family="Dana-FaNum" font-size="16">
        <text x="50%" y="300" text-anchor="middle"><tspan font-weight="bold">نام: </tspan><tspan>مهدی</tspan></text>
    </g>
</svg>
```
The SVG output is:
![svg](https://user-images.githubusercontent.com/40426839/132989245-c03f4c6e-d08e-4710-ab0b-aead789943c2.JPG)
and the PNG output:
![png](https://user-images.githubusercontent.com/40426839/132989227-918dd049-f7e8-4ad9-a67a-029da74b17a9.JPG)
Looks like when I add the tspan tag to make part of text bold, librsvg reverses the ordering of words, assuming the text is in ltr mode. Adding direction="rtl" to the parent text tag also doesn't solve the problem.

If I omit the tspan tags and just write:
`<text x="50%" y="300" text-anchor="middle">نام: مهدی</text>`
‌Both outputs seem to be correct:
![without](https://user-images.githubusercontent.com/40426839/132989378-7b7d82c5-3a1e-455c-9588-00f7762f2877.JPG)
What do I do to solve the issue? Please, help me!

**Comment by lovell** [comment]
Hi, thanks for reporting this, I've been able reproduce it using the latest version of the `rsvg-convert` command line tool.

Please can you open an upstream issue for this at https://gitlab.gnome.org/GNOME/librsvg with full details.

**Comment by AmirABody** [comment]
> Hi, thanks for reporting this, I've been able reproduce it using the latest version of the `rsvg-convert` command line tool.
> 
> Please can you open an upstream issue for this at https://gitlab.gnome.org/GNOME/librsvg with full details.

**Comment by AmirABody** [comment]
> Hi, thanks for reporting this, I've been able reproduce it using the latest version of the `rsvg-convert` command line tool.
> 
> Please can you open an upstream issue for this at https://gitlab.gnome.org/GNOME/librsvg with full details.

Excuse me, Can I Ask which version of librsvg does the latest version of sharp (0.29.0) uses?

**Comment by lovell** [comment]
I have commented on the upstream issue at https://gitlab.gnome.org/GNOME/librsvg/-/issues/791

**Comment by AmirABody** [comment]
@lovell 
Excuse me, sounds like it's been a while that *librsvg* developers have solved this bug for the upstream library. May I ask, as an approximate estimation, How much time does it take for sharp to implement the changes?!

**Comment by lovell** [comment]
v0.30.0 now available with prebuilt binaries that include a version of librsvg with the upstream fix.
