### ISSUE TITLE
Cannot install sharp node 16

### ISSUE THREAD

**Issue by steveDL** [lovell/sharp#2887]
```
npm ERR! code 1
npm ERR! path /Users/steve/Sites/brighter-futures/node_modules/favicons/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
npm ERR! TOUCH Release/obj.target/libvips-cpp.stamp
npm ERR!   CXX(target) Release/obj.target/sharp/src/common.o
npm ERR! info sharp Using cached /Users/steve/.npm/_libvips/libvips-8.8.1-darwin-x64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.9.0 | darwin | x64
npm ERR! (node:15043) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /usr/bin/python2
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/steve/Sites/brighter-futures/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/steve/Sites/brighter-futures/node_modules/favicons/node_modules/sharp/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/steve/Sites/brighter-futures/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/steve/.node-gyp/16.9.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/steve/.node-gyp/16.9.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/steve/Sites/brighter-futures/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/steve/.node-gyp/16.9.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/steve/Sites/brighter-futures/node_modules/favicons/node_modules/sharp',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/common.cc:22:
npm ERR! In file included from /Users/steve/.node-gyp/16.9.0/include/node/node.h:63:
npm ERR! In file included from /Users/steve/.node-gyp/16.9.0/include/node/v8.h:30:
npm ERR! /Users/steve/.node-gyp/16.9.0/include/node/v8-internal.h:489:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
npm ERR!             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                 ~~~~~^~~~~~~~~~~
npm ERR!                                      remove_cv
npm ERR! /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:776:50: note: 'remove_cv' declared here
npm ERR! template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
npm ERR!                                                  ^
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/sharp/src/common.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/steve/Sites/brighter-futures/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 20.6.0
npm ERR! gyp ERR! command "/usr/local/Cellar/node/16.9.0/bin/node" "/Users/steve/Sites/brighter-futures/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/steve/Sites/brighter-futures/node_modules/favicons/node_modules/sharp
npm ERR! gyp ERR! node -v v16.9.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/steve/.npm/_logs/2021-09-14T13_06_11_323Z-debug.log****
```

**Comment by lovell** [comment]
Hi, it looks like you're using sharp v0.23.x (July 2019) with Node.js 16 (April 2021). Please can you upgrade sharp.

**Comment by steveDL** [comment]
Hey Thanks for the swift reply what is giving you the indication I am using v0.23.x ?

**Comment by lovell** [comment]
> what is giving you the indication I am using v0.23.x ?

sharp v0.23.x provided libvips v8.8.1

> npm ERR! info sharp Using cached /Users/steve/.npm/_libvips/libvips-8.8.1-darwin-x64.tar.gz

https://sharp.pixelplumbing.com/changelog#v023---vision

> I am getting the same error with npm i sharp

What is the complete output of running `npm install --verbose sharp`?

**Comment by steveDL** [comment]
`npm info run node-sass@4.14.1 install node_modules/node-sass node scripts/install.js
npm info run sharp@0.29.1 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm info run sharp@0.23.4 install node_modules/favicons/node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
npm info run fsevents@1.2.13 install node_modules/glob-watcher/node_modules/fsevents node install.js
npm info run node-sass@4.14.1 install { code: 0, signal: null }
npm timing build:run:install:node_modules/node-sass Completed in 1029ms
npm info run sharp@0.29.1 install { code: 0, signal: null }
npm timing build:run:install:node_modules/sharp Completed in 5328ms
npm info run sharp@0.23.4 install { code: 1, signal: null }
npm info run fsevents@1.2.13 install { code: 0, signal: null }
npm timing build:run:install:node_modules/glob-watcher/node_modules/fsevents Completed in 17785ms
npm timing reify:rollback:createSparse Completed in 5298ms
npm timing reify:rollback:retireShallow Completed in 0ms
npm timing command:install Completed in 75835ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
npm verb stack     at ChildProcess.emit (node:events:394:28)
npm verb stack     at maybeClose (node:internal/child_process:1064:16)
npm verb stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm verb pkgid sharp@0.23.4
npm verb cwd /Users/steve/Sites/brighter-futures
npm verb Darwin 20.6.0
npm verb argv "/usr/local/Cellar/node/16.9.0/bin/node" "/usr/local/bin/npm" "install" "--verbose" "sharp"
npm verb node v16.9.0
npm verb npm  v7.21.1
npm ERR! code 1
npm ERR! path /Users/steve/Sites/brighter-futures/node_modules/favicons/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
npm ERR! touch Release/obj.target/libvips-cpp.stamp
npm ERR!   c++ '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/steve/.node-gyp/16.9.0/include/node -I/Users/steve/.node-gyp/16.9.0/src -I/Users/steve/.node-gyp/16.9.0/deps/openssl/config -I/Users/steve/.node-gyp/16.9.0/deps/openssl/openssl/include -I/Users/steve/.node-gyp/16.9.0/deps/uv/include -I/Users/steve/.node-gyp/16.9.0/deps/zlib -I/Users/steve/.node-gyp/16.9.0/deps/v8/include -I../../../../nan -I../vendor/include -I../vendor/include/glib-2.0 -I../vendor/lib/glib-2.0/include  -O3 -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++11 -stdlib=libc++ -fexceptions -Wall -O3 -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/common.o.d.raw   -c -o Release/obj.target/sharp/src/common.o ../src/common.cc
npm ERR! info sharp Using cached /Users/steve/.npm/_libvips/libvips-8.8.1-darwin-x64.tar.gz
npm ERR! prebuild-install info begin Prebuild-install version 5.3.6
npm ERR! prebuild-install info install installing standalone, skipping download.
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/local/Cellar/node/16.9.0/bin/node',
npm ERR! gyp verb cli   '/Users/steve/Sites/brighter-futures/node_modules/.bin/node-gyp',
npm ERR! gyp verb cli   'rebuild'
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.9.0 | darwin | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` succeeded python2 /usr/bin/python2
npm ERR! gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.16
npm ERR! gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 16.9.0
npm ERR! gyp verb command install [ '16.9.0' ]
npm ERR! gyp verb install input version string "16.9.0"
npm ERR! gyp verb install installing version: 16.9.0
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 16.9.0
npm ERR! gyp verb build dir attempting to create "build" dir: /Users/steve/Sites/brighter-futures/node_modules/favicons/node_modules/sharp/build
npm ERR! gyp verb build dir "build" dir needed to be created? /Users/steve/Sites/brighter-futures/node_modules/favicons/node_modules/sharp/build
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: /Users/steve/Sites/brighter-futures/node_modules/favicons/node_modules/sharp/build/config.gypi
npm ERR! (node:20709) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp verb config.gypi checking for gypi file: /Users/steve/Sites/brighter-futures/node_modules/favicons/node_modules/sharp/config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: /Users/steve/Sites/brighter-futures/node_modules/favicons/node_modules/sharp/common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
npm ERR! gyp info spawn /usr/bin/python2
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/steve/Sites/brighter-futures/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/steve/Sites/brighter-futures/node_modules/favicons/node_modules/sharp/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/steve/Sites/brighter-futures/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/steve/.node-gyp/16.9.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/steve/.node-gyp/16.9.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/steve/Sites/brighter-futures/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/steve/.node-gyp/16.9.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/steve/Sites/brighter-futures/node_modules/favicons/node_modules/sharp',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp verb command build []
npm ERR! gyp verb build type Release
npm ERR! gyp verb architecture x64
npm ERR! gyp verb node dev dir /Users/steve/.node-gyp/16.9.0
npm ERR! gyp verb `which` succeeded for `make` /usr/bin/make
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/common.cc:22:
npm ERR! In file included from /Users/steve/.node-gyp/16.9.0/include/node/node.h:63:
npm ERR! In file included from /Users/steve/.node-gyp/16.9.0/include/node/v8.h:30:
npm ERR! /Users/steve/.node-gyp/16.9.0/include/node/v8-internal.h:489:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
npm ERR!             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                 ~~~~~^~~~~~~~~~~
npm ERR!                                      remove_cv
npm ERR! /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:776:50: note: 'remove_cv' declared here
npm ERR! template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
npm ERR!                                                  ^
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/sharp/src/common.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/steve/Sites/brighter-futures/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 20.6.0
npm ERR! gyp ERR! command "/usr/local/Cellar/node/16.9.0/bin/node" "/Users/steve/Sites/brighter-futures/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/steve/Sites/brighter-futures/node_modules/favicons/node_modules/sharp
npm ERR! gyp ERR! node -v v16.9.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm verb exit 1
npm timing npm Completed in 76490ms
npm verb unfinished npm timer reify 1631627300634
npm verb unfinished npm timer reify:build 1631627355354
npm verb unfinished npm timer build 1631627355359
npm verb unfinished npm timer build:deps 1631627355360
npm verb unfinished npm timer build:run:install 1631627355872
npm verb unfinished npm timer build:run:install:node_modules/favicons/node_modules/sharp 1631627355902
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/steve/.npm/_logs/2021-09-14T13_49_36_487Z-debug.log`

**Comment by lovell** [comment]
>  npm info run sharp@0.23.4 install node_modules/favicons/node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

This suggests you'll need to upgrade the `favicons` package.

**Comment by steveDL** [comment]
Seems to be pulling in all sorts here. Probably not an issue with this package my bad.

**Comment by sfonua10** [comment]
Here's the log I have when trying to deploy via on Netifly: 

8:05:34 PM: Build ready to start
8:05:36 PM: build-image version: 081db65c3e4ce8423fedb40e7689a87de6f84667
8:05:36 PM: build-image tag: v4.3.1
8:05:36 PM: buildbot version: 8fc02bca7ec1133b98312d7c1eea7917b6fe4dde
8:05:36 PM: Fetching cached dependencies
8:05:36 PM: Failed to fetch cache, continuing with build
8:05:36 PM: Starting to prepare the repo for build
8:05:36 PM: No cached dependencies found. Cloning fresh repo
8:05:36 PM: git clone https://github.com/sfonua10/alama
8:05:37 PM: Preparing Git Reference refs/heads/master
8:05:37 PM: Parsing package.json dependencies
8:05:38 PM: Different build command detected, going to use the one specified in the Netlify configuration file: 'npm run build && npm run export' versus 'next build && next export' in the Netlify UI
8:05:38 PM: Starting build script
8:05:38 PM: Installing dependencies
8:05:38 PM: Python version set to 2.7
8:05:39 PM: Downloading and installing node v8.17.0...
8:05:39 PM: Downloading https://nodejs.org/dist/v8.17.0/node-v8.17.0-linux-x64.tar.xz...
8:05:39 PM: Computing checksum with sha256sum
8:05:39 PM: Checksums matched!
8:05:41 PM: Now using node v8.17.0 (npm v6.13.4)
8:05:41 PM: Started restoring cached build plugins
8:05:41 PM: Finished restoring cached build plugins
8:05:41 PM: Attempting ruby version 2.7.2, read from environment
8:05:43 PM: Using ruby version 2.7.2
8:05:43 PM: Using PHP version 8.0
8:05:43 PM: Started restoring cached node modules
8:05:43 PM: Finished restoring cached node modules
8:05:43 PM: Installing NPM modules using NPM version 6.13.4
8:05:58 PM: npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
8:05:58 PM: > sharp@0.29.1 install /opt/build/repo/node_modules/sharp
8:05:58 PM: > (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
8:06:00 PM: sharp: Installation error: Expected Node.js version >=12.13.0 but found 8.17.0
8:06:00 PM: sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
8:06:02 PM: npm WARN alama@1.0.0 No description
8:06:02 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-darwin-x64@11.1.2 (node_modules/@next/swc-darwin-x64):
8:06:02 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-darwin-x64@11.1.2: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
8:06:02 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-darwin-arm64@11.1.2 (node_modules/@next/swc-darwin-arm64):
8:06:02 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-darwin-arm64@11.1.2: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
8:06:02 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-x64-msvc@11.1.2 (node_modules/@next/swc-win32-x64-msvc):
8:06:02 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-x64-msvc@11.1.2: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
8:06:02 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
8:06:02 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
8:06:02 PM: npm ERR! code ELIFECYCLE
8:06:02 PM: npm ERR! errno 1
8:06:02 PM: npm ERR! sharp@0.29.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)`
8:06:02 PM: npm ERR! Exit status 1
8:06:02 PM: npm ERR!
8:06:02 PM: npm ERR! Failed at the sharp@0.29.1 install script.
8:06:02 PM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
8:06:02 PM: npm ERR! A complete log of this run can be found in:
8:06:02 PM: npm ERR!     /opt/buildhome/.npm/_logs/2021-09-23T02_06_02_167Z-debug.log
8:06:02 PM: Error during NPM install
8:06:02 PM: Build was terminated: Build script returned non-zero exit code: 1
8:06:02 PM: Creating deploy upload records
8:06:02 PM: Failing build: Failed to build site
8:06:02 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
8:06:02 PM: Finished processing build request in 26.000772449s

========
When I run `npm install --verbose sharp` I get:

siosaia.fonua@rem-mb048 alama % npm install -verbose sharp
npm verb cli [
npm verb cli   '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '-verbose',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@7.24.0
npm info using node@v14.17.4
npm timing npm:load:whichnode Completed in 1ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 1ms
npm timing config:load:env Completed in 1ms
npm timing config:load:file:/Users/siosaia.fonua/pp/alama/.npmrc Completed in 0ms
npm timing config:load:project Completed in 0ms
npm timing config:load:file:/Users/siosaia.fonua/.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 1ms
npm timing config:load:credentials Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 7ms
npm timing npm:load:configload Completed in 7ms
npm timing npm:load:setTitle Completed in 14ms
npm timing npm:load:setupLog Completed in 0ms
npm timing config:load:flatten Completed in 2ms
npm timing npm:load:cleanupLog Completed in 2ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 0ms
npm timing npm:load Completed in 29ms
npm timing arborist:ctor Completed in 1ms
npm timing idealTree:init Completed in 228ms
npm timing idealTree:userRequests Completed in 2ms
npm timing arborist:ctor Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/sharp 286ms (cache revalidated)
npm timing idealTree:#root Completed in 296ms
npm timing idealTree:node_modules/sharp Completed in 0ms
npm timing idealTree:buildDeps Completed in 297ms
npm timing idealTree:fixDepFlags Completed in 9ms
npm timing idealTree Completed in 543ms
npm timing reify:loadTrees Completed in 545ms
npm timing reify:diffTrees Completed in 11ms
npm timing reify:retireShallow Completed in 1ms
npm timing reify:createSparse Completed in 2ms
npm timing reify:loadBundles Completed in 0ms
npm verb reify failed optional dependency /Users/siosaia.fonua/pp/alama/node_modules/@next/swc-win32-x64-msvc
npm verb reify failed optional dependency /Users/siosaia.fonua/pp/alama/node_modules/@next/swc-linux-x64-gnu
npm verb reify failed optional dependency /Users/siosaia.fonua/pp/alama/node_modules/@next/swc-darwin-arm64
npm timing reifyNode:node_modules/@next/swc-win32-x64-msvc Completed in 3ms
npm timing reifyNode:node_modules/@next/swc-linux-x64-gnu Completed in 3ms
npm timing reifyNode:node_modules/@next/swc-darwin-arm64 Completed in 4ms
npm timing reify:unpack Completed in 4ms
npm timing reify:unretire Completed in 0ms
npm timing build:queue Completed in 1ms
npm timing build:deps Completed in 1ms
npm timing build Completed in 1ms
npm timing reify:build Completed in 2ms
npm timing reify:trash Completed in 2ms
npm timing reify:save Completed in 100ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 253ms
npm timing auditReport:getReport Completed in 259ms
npm timing auditReport:init Completed in 0ms
npm timing reify:audit Completed in 259ms
npm timing reify Completed in 839ms

up to date, audited 504 packages in 1s

81 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm timing command:install Completed in 847ms
npm verb exit 0
npm timing npm Completed in 1050ms
npm info ok 



Any insights for me?

**Comment by lovell** [comment]
@sfonua10 Node.js 8.17.0 is unsupported. Please open a new issue if you're still having problems with Node.js >= 12.13.0.

**Comment by yunusemrq** [comment]
@steveDL  hello i am getting the same error can you help me too if you solved it
