### ISSUE TITLE
Error in using sharp package to call sharp method in Electron

### ISSUE THREAD

**Issue by blankTwo** [lovell/sharp#2888]
Electron v11
Windows 10.
The current problem is that everything is normal when I use `sharp` for local debugging.
After packaging with `electron-builder`, the error occurs when using `await sharp('test.webp').png().toBuffer()`

Try to execute `npm install --ignore-scripts=false --verbose sharp` and ` npm install --platform=win32 --arch=ia32 sharp`
That is, the command prompted in the picture, the same error after packaging
 I don't know what to do at the moment !!
![image](https://user-images.githubusercontent.com/45682935/133363585-7baf98ff-695b-4574-9fee-36782d489353.png)

**Comment by lovell** [comment]
The Electron packaging tools have only recently added support for the Windows + prebuild + Node-API combo so please make sure you're using the latest version of `electron-rebuild` (and not `electron-builder`).

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
