### ISSUE TITLE
yarn install stucks forever on bulding fresh package for sharp

### ISSUE THREAD

**Issue by FunnyPhantom** [lovell/sharp#2889]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?
Yes
Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?
Yes

Node version: 16.9.1
npm version: 7.21.1
yarn version: 1.22.5
shap version: ^0.25.2, (resolved 0.25.4)

Hi, I am using Ubuntu WSL which by default did not had libvips-tools package. 
Upon trying to install all the dependency of a project, the yarn command was stuck at `building fresh package` stage indefinitely

After the `libvips-tools` package was installed, the yarn install command installed all of the project dependency very smoothly.
I am adding this for future users searching upon this issue.

Anyway, I suspect, it would be a good idea to add libvips-tools as a dependency for linux systems. Although I believe current assumption is that most linux distros come with this library pre-built, so there should be no problem here). Dunno If I read the documentation right, but If you guys are onboard with adding this to documentation, could you help me where or how to add it to documentation? Much appreciated.

**Comment by lovell** [comment]
Ubuntu users do not need to install libvips-tools so it's likely you ran into another problem. Please can you uninstall that package and, assuming it's still failing, provide the complete output of running `npm install --verbose sharp`.

**Comment by FunnyPhantom** [comment]
Hmm, installing it with `npm install` does not run into any problem, but it seems like `yarn install` does. And also, `yarn install --verbose` did not give any useful information, since basically  it was stuck in the "creating fresh package..." stage on sharp library with no further information why.

Although Ubuntu users do not need to install libvips-tools, seems like _WSL ubuntu_ users may need to. commands like `vips` are not available on when the distro is installed and needs to be added manually. 

On the side note, I was trying to setup my system with windows to start to code, but there were a lot of minor inconveniences here and there and a major one -which was the fact that WSL needed a lot of ram- kinda stopped me from pursuing this forward 😁

Thanks for your answer and your time! 🎉
