### ISSUE TITLE
Webpack Compile Issue

### ISSUE THREAD

**Issue by eliteSchwein** [lovell/sharp#2892]
i get: 

      ERROR in ./node_modules/sharp/build/Release/sharp-win32-x64.node 1:2
      Module parse failed: Unexpected character '�' (1:2)

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
         -- sharp@0.29.1

What are the steps to reproduce?
execute webpack

What is the expected behaviour?
it should compile

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
no

Are you able to provide a sample image that helps explain the problem?
no

What is the output of running `npx envinfo --binaries --system`?

**Comment by lovell** [comment]
Hi, did you see https://sharp.pixelplumbing.com/install#webpack ?
