### ISSUE TITLE
Infinite loop (?) after upgrading to 0.29 in an Electron app

### ISSUE THREAD

**Issue by ivancuric** [lovell/sharp#2895]
I'm using sharp in an electron app, and it worked with version 0.28.x.

When upgrading to 0.29, the function itself can still be imported and calling `sharp()` works, but it seems as I pass a file or a buffer to it the process never finishes. There is no return value, no caught errors, but the app itself keeps consuming CPU and eventually becomes unresponsive.

This happens on both MacOS and Windows, on Electron 14.

Downgrading to 0.28.x fixes this issue

**Comment by lovell** [comment]
Please can you provide a minimal, standalone code sample/repo that allows someone else to reproduce.

**Comment by ivancuric** [comment]
After building a minimal code repo I couldn't reproduce the issue.

Think it might've been a `yarn.lock` issue.
