### ISSUE TITLE
When use overlayWith() to combine 2 PNG files and save into JPEG file

### ISSUE THREAD

**Issue by imkven** [lovell/sharp#290]
Here is my code:

```node
sharp('back.png')
  .overlayWith('fore.png')
  .flatten()
  .toFormat(sharp.format.jpeg)
  .toFile('f.jpg', next);
```

I have try save into PNG file, it work well. However, JPG not work.

JPG:
![f](https://cloud.githubusercontent.com/assets/541248/10662851/bc95c09e-78e9-11e5-9c3a-201ef1c7c285.jpg)

PNG:
![f](https://cloud.githubusercontent.com/assets/541248/10662854/c266d40e-78e9-11e5-9898-234cc7cf768e.png)

**Comment by lovell** [comment]
Hello, which version of libvips are you using? If you're not already doing so, are you able to try with libvips v8.1.0+?

**Comment by imkven** [comment]
Sorry, I not able to try in latest version. I install libvips with brew and it latest version is 8.0.2.

FYI, I has solve it by save image to PNG file, then convert to JPEG.

**Comment by lovell** [comment]
vips 8.1.0 is [now available](https://github.com/Homebrew/homebrew-science/blob/master/vips.rb#L3) via homebrew - please can you try `brew update && brew upgrade`.

**Comment by lovell** [comment]
@imkven Were you able to make any progress towards upgrading vips to 8.1.0?

**Comment by imkven** [comment]
Sorry, late to reply. It work well after I upgraded vips version.
Thanks, @lovell
