### ISSUE TITLE
Installed global libheif and vips but sharp heif errors (node:14-alpine3.14)

### ISSUE THREAD

**Issue by johnmarksilly** [lovell/sharp#2901]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?
Yes

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?
Yes

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
Yes

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?
N/A

If you are using npm v7, does the user running `npm install` own the directory it is run in?
N/A

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?
N/A

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?
Yes

What is the output of running `npx envinfo --binaries --system`?
  System:
    OS: Linux 5.10 Alpine Linux
    CPU: (4) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 131.32 MB / 1.94 GB
    Container: Yes
    Shell: 1.31.1 - /bin/ash
  Binaries:
    Node: 14.17.6 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    
I'm sorry for submitting an issue, but I'm at my wits end.

Background:
- Develop on Mac
- Global Mac libheif and vips installed using brew
- Local run of my app can process heif files
- Docker version can not

Sample Dockerfile mirrors my actual Dockerfile
```
FROM node:14-alpine3.14

RUN apk update
RUN apk add libheif libheif-dev vips-dev

COPY . .

RUN npm install --verbose sharp
RUN npm i

CMD [ "node", "./index.js" ]
```

Index.js is basic:
```
const sharp = require('sharp');
sharp("./sample1.heic").jpeg().toBuffer();
```

For some reason sharp is not finding my global vips or will vips will not associate my libheif as a dependency

**Comment by lovell** [comment]
What is the complete output of running `npm install --verbose sharp` inside the container?

Is the `heif-convert` command line tool able to read the `sample1.heic` file?

**Comment by johnmarksilly** [comment]
```
> sharp@0.29.1 install /node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Using cached /root/.npm/_libvips/libvips-8.11.3-linuxmusl-x64.tar.br
prebuild-install info begin Prebuild-install version 6.1.4
prebuild-install info looking for local prebuild @ prebuilds/sharp-v0.29.1-napi-v5-linuxmusl-x64.tar.gz
prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/a689bd-sharp-v0.29.1-napi-v5-linuxmusl-x64.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /root/.npm/_prebuilds/a689bd-sharp-v0.29.1-napi-v5-linuxmusl-x64.tar.gz
prebuild-install info unpack resolved to /node_modules/sharp/build/Release/sharp-linuxmusl-x64.node
prebuild-install info install Successfully installed prebuilt binary!
npm verb lifecycle sharp@0.29.1~install: unsafe-perm in lifecycle false
npm verb lifecycle sharp@0.29.1~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/node_modules/sharp/node_modules/.bin:/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle sharp@0.29.1~install: CWD: /node_modules/sharp
npm timing audit submit Completed in 142ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 141ms
npm timing audit body Completed in 1ms
npm timing action:install Completed in 1147ms
npm info lifecycle sharp@0.29.1~postinstall: sharp@0.29.1
npm timing action:postinstall Completed in 2ms
npm verb unlock done using /root/.npm/_locks/staging-781faa38490e6896.lock for /node_modules/.staging
npm timing stage:executeActions Completed in 1277ms
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 5272ms
npm verb saving [ { name: 'sharp', spec: '^0.29.1', save: 'dependencies' } ]
npm verb shrinkwrap skipping write for package.json because there were no changes.
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle test@0.0.0~shrinkwrap: test@0.0.0
npm verb shrinkwrap skipping write for package-lock.json because there were no changes.
npm info lifecycle test@0.0.0~postshrinkwrap: test@0.0.0
+ sharp@0.29.1
```

`heif-convert` does not appear to be in my path. Do you happen to know what bin folder it defaults to in alpine?

**Comment by johnmarksilly** [comment]
Okay I added heif-convert using `apk add libheif-tools` and I was able to convert the file in the Docker container. I copied it out and it was a proper jpeg.

Is `libheif-tools` a dependency for Sharp in Alpine? Should I try reinstalling my sharp package?

**Comment by lovell** [comment]
Thanks, you don't need `libheif-tools` (I forgot that Alpine places these in a separate package).

https://sharp.pixelplumbing.com/install#custom-libvips

> To use a custom, globally-installed version of libvips instead of the provided binaries, make sure it is at least the version listed under config.libvips in the package.json file and that it can be located using pkg-config --modversion vips-cpp.

sharp v0.29.x requires libvips v8.11.3

https://sharp.pixelplumbing.com/changelog#v029---circle

Alpine 3.14 provides libvips v8.10.6

https://pkgs.alpinelinux.org/package/v3.14/community/x86_64/vips-dev

**Comment by johnmarksilly** [comment]
<img width="507" alt="image" src="https://user-images.githubusercontent.com/11224731/134206434-ab997dfe-17d3-4300-aac2-083d2e93ac27.png">
I feel like a dope!

**Comment by lovell** [comment]
Alpine Edge provides libvips v8.11.3

https://pkgs.alpinelinux.org/packages?name=vips-dev&branch=edge&arch=x86_64

**Comment by johnmarksilly** [comment]
Awesome! Thank you so much. I'll try switching to edge and see where that lands me!

**Comment by mrjackwills** [comment]
> 
> 
> Alpine Edge provides libvips v8.11.3
> 
> https://pkgs.alpinelinux.org/packages?name=vips-dev&branch=edge&arch=x86_64

Sorry for, potentially, a stupid question, but does this mean that it is impossible to install sharp on a alpine docker container on a pi zero w (which runs arm6)

**Comment by lovell** [comment]
@mrjackwills Alpine Linux provides `armhf` packages e.g. https://pkgs.alpinelinux.org/packages?name=vips-dev&branch=edge&arch=armhf - if you're still having problems please open a new issue.

**Comment by johnmarksilly** [comment]
@lovell I got it! Thank you again for putting me on the right path. I had to keep on 3.14 due to some DevOps constraints, but I was finally successful. For those who come after me:

To get Sharp running with heif support in Docker on`node:14-alpine3.14`:
- Sharp package must not be greater than `v0.28`
- Must add `build-base libheif vips-dev vips` packages to the image using `apk add`
