### ISSUE TITLE
Outdated version of downstream sharp-phash

### ISSUE THREAD

**Issue by VySellathurai** [lovell/sharp#2904]
***Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?***
I use the lib sharp-phash@1.1.0 that use shap@0.25.4

***What are the steps to reproduce?***
This lib works perfectly well on classical AWS processor but I tried to run my code on **AWS Graviton with ARM Neoverse 64 bits** and I face this exception : 
```
Input buffer contains unsupported image format
```

- Note that I install libvips v8.9.1 in global

The code of sharp-phash is trying to use sharp on image as you can see : 
```javascript
module.exports = async function phash(image, opts = { sharp: sharp }) {
  const data = await opts.sharp(image)
```
[source code](https://github.com/btd/sharp-phash/blob/a9bc10ffb5e27034635864e9a46132fe54cfd3bd/index.js#L53)

***Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?***
No

***Are you able to provide a sample image that helps explain the problem?***
No

What is the output of running `npx envinfo --binaries --system`?
```
npx envinfo --binaries --system
npx: installed 1 in 3.953s

  System:
    OS: Linux 4.18 CentOS Linux 8
    CPU: (2) arm64 unknown
    Memory: 135.25 MB / 1.42 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.24.1 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.12 - /usr/bin/npm
```

### Questions / Notes
- Do you have any clue about what's going on ? 
- Is there any chance to run Sharp on **AWS Graviton with ARM Neoverse 64 bits** ?
- I'm guessing that this line of code in your lib is the origin of the problem : https://github.com/lovell/sharp/blob/master/src/common.cc#L260

Thank you for your time

**Comment by lovell** [comment]
Hi, did you mean to ask this question on the `sharp-phash` repo, which is a downstream consumer of sharp?

I recommend you upgrade to the latest  `sharp-phash`, which specifies `sharp` as a peer dependency, then add the latest v0.29.1 of `sharp` to your `package.json`.

https://github.com/btd/sharp-phash/blob/6c1f039b6ae925fa9130da302e8c072cb60bdd5e/package.json#L26-L28

**Comment by VySellathurai** [comment]
Hi,
tank you for your response.

I open an issue on sharp-phash repo : https://github.com/btd/sharp-phash/issues/10

I tested your recommendation : 
- `sharp-phash@2.0.0`
- I set `sharp@0.29.1` in the `resolutions` part of my package.json
- I set libvips `8.11.3` globally
- I'm using `node 14`

I still face the same problem

**Comment by lovell** [comment]
Are you able to reproduce this using only sharp (i.e. without phash) and without a globally-installed libvips?

**Comment by VySellathurai** [comment]
I just tested the installation without install libvips globally (with sharp-phase) and i face this error log : 
```
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)\nArguments: \nDirectory: /home/centos/xxxx/xxx/node_modules/sharp\nOutput:\nsharp: Installation error: Use with glibc 2.28 requires manual installation of libvips >= 8.11.3
```

I'm trying right now to test with only sharp. I will come back to you later

**Comment by VySellathurai** [comment]
Hi,

I cannot using sharp without installing libvips globally. You can see the installation just below.
Nevertheless I tried to use directly sharp (without phash) and the same error still came up : `Input buffer contains unsupported image format`

**Comment by lovell** [comment]
> Installation error: Use with glibc 2.28 requires manual installation of libvips >= 8.11.3



My advice is to use a more modern OS

**Comment by lovell** [comment]
Please see #2837 and https://github.com/lovell/sharp-libvips/issues/114
