### ISSUE TITLE
Alpine Linux 3.10 has reached end-of-life

### ISSUE THREAD

**Issue by masterpandabear** [lovell/sharp#2905]
Hello there, I recently tried to update sharp package from  0.25.2 to what is currently latest 0.29.1. `npm install` seems to install it just fine with no errors but when I try to run the service I get the following error

```
Something went wrong installing the "sharp" module

Error relocating /var/www/node_modules/sharp/build/Release/../.././vendor/8.11.3/linuxmusl-x64/lib/libvips-cpp.so.42: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found

Possible solutions:
- Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
- Install for the current runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
```

I am installing the node packages and running node using docker, here is the dockerfile
```
FROM node:14.17.0-alpine3.10

RUN apk add --no-cache make gcc g++ git && \
	rm -rf /tmp/* /var/cache/apk/* /root/.npm /root/.node-gyp ; mkdir -p /var/www ; \
	npm install -g express-generator mocha sinon should assert node-gyp nodemon eslint typescript

WORKDIR /var/www
EXPOSE 3000
CMD ["npm", "start"]
```

As you can see, I am running node 14.17.0 in alpine 3.10. I read some of the issues that had the same errors, but they seemed to be installing packages from edge branch, which as far as I know I am not. What is curious is that the possible solutions, detects the runtime platform as just `linux`, isn't it supposed to be `linuxmusl` ?

Any pointers, tips, suggestions would be much appreciated. Thanks

Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?

Yes

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?

As far as I can tell, yes, but I am using docker

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

Yes, I am using 0.29.1

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

Yes, I also tried with that flag

If you are using npm v7, does the user running `npm install` own the directory it is run in?

Not using npm v7

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?
Not using the `ingore-scripts` feature

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

```
npm info lifecycle sharp@0.29.1~install: sharp@0.29.1

> sharp@0.29.1 install /var/www/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.11.3/libvips-8.11.3-linuxmusl-x64.tar.br
prebuild-install info begin Prebuild-install version 6.1.4
prebuild-install info looking for local prebuild @ prebuilds/sharp-v0.29.1-napi-v5-linuxmusl-x64.tar.gz
prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/a689bd-sharp-v0.29.1-napi-v5-linuxmusl-x64.tar.gz
prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.29.1/sharp-v0.29.1-napi-v5-linuxmusl-x64.tar.gz
prebuild-install http 200 https://github.com/lovell/sharp/releases/download/v0.29.1/sharp-v0.29.1-napi-v5-linuxmusl-x64.tar.gz
prebuild-install info downloading to @ /root/.npm/_prebuilds/a689bd-sharp-v0.29.1-napi-v5-linuxmusl-x64.tar.gz.137-f53b0f0bcdb02.tmp
prebuild-install info renaming to @ /root/.npm/_prebuilds/a689bd-sharp-v0.29.1-napi-v5-linuxmusl-x64.tar.gz
prebuild-install info unpacking @ /root/.npm/_prebuilds/a689bd-sharp-v0.29.1-napi-v5-linuxmusl-x64.tar.gz
prebuild-install info unpack resolved to /var/www/node_modules/sharp/build/Release/sharp-linuxmusl-x64.node
prebuild-install info install Successfully installed prebuilt binary!
npm verb lifecycle sharp@0.29.1~install: unsafe-perm in lifecycle false
npm verb lifecycle sharp@0.29.1~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/node_modules/sharp/node_modules/.bin:/var/www/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle sharp@0.29.1~install: CWD: /var/www/node_modules/sharp
```

What is the output of running `npx envinfo --binaries --system`?

```
npx: installed 1 in 3.321s

  System:
    OS: Linux 5.10 Alpine Linux
    CPU: (4) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 366.32 MB / 3.84 GB
    Container: Yes
    Shell: 1.30.1 - /bin/ash
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
```

**Comment by lovell** [comment]
Hi, did you see https://sharp.pixelplumbing.com/install#prebuilt-binaries ?

> Ready-compiled sharp and libvips binaries are provided for use on the most common platforms:
> * Linux x64 (glibc >= 2.17, musl >= 1.1.24)

Alpine Linux 3.10 provides musl v1.1.22 - see https://pkgs.alpinelinux.org/packages?name=musl&branch=v3.10&arch=x86_64

Alpine Linux 3.10 reached end-of-life on 1st May 2021 - see https://alpinelinux.org/releases/

**Comment by masterpandabear** [comment]
@lovell Thank you for the fast response, I will update the alpine image with 3.14 and let you know.

**Comment by masterpandabear** [comment]
That did the trick, thank you again.
