### ISSUE TITLE
Picture auto enhancement

### ISSUE THREAD

**Issue by mathias22osterhagen22** [lovell/sharp#2906]
_I'm sorry if this question seems silly but I didn't see anywhere an "auto" mode other than for the rotation function._

**What are you trying to achieve?**
We have a lot of documents arriving in our system that are scanned and often not easily readable, we are looking to auto enhances (if necessary) the picture, the contrast, and the luminosity (like the filter of windows).
![image](https://user-images.githubusercontent.com/60438474/134546137-9a53bb9d-aef5-46f9-9af6-4b4b7d915b1a.png)

By "if necessary" I mean:  that we don't want to apply a `luminosity + 10` on an image already too bright or a `- 10` on one already too dark.

**Have you searched for similar questions?**
Yes, but I didn't found.

**Are you able to provide a minimal, standalone code sample that demonstrates this question?**
An example: 
1. **Input:**
![input](https://user-images.githubusercontent.com/60438474/134546162-d5b391ff-bc52-4831-8a43-660f4109a294.jpg)

2. **Output:**
![output](https://user-images.githubusercontent.com/60438474/134546221-909625db-af7b-40ab-b1a8-ef5ffb5a66ed.jpg)

**Are you able to provide a sample image that helps explain the question?**
(Yes see the two above)

**Comment by lovell** [comment]
Hi, did you see the [clahe](https://sharp.pixelplumbing.com/api-operation#clahe) and [normalise](https://sharp.pixelplumbing.com/api-operation#normalise) operations?

**Comment by mathias22osterhagen22** [comment]
Hello @lovell , thank you a lot for your answer!
I tried this morning the two functions you recommended but It doesn't seem to make a major improvement:
![image](https://user-images.githubusercontent.com/60438474/134640085-5975590e-d1dd-4be8-a645-185ace92acfd.png)

Do I'm doing something wrong ?
```js
const fs = require("fs");
const sharp = require("sharp");

let files = fs.readdirSync('./input');
console.log("Input files: ", files);
if (fs.existsSync('./output'))
    fs.rmdirSync('./output', { recursive: true, force: true });
fs.mkdirSync('./output');

files.forEach(fileName => {
    console.log('Convert: ./input/' + fileName + " -> ./output/" + fileName + " ...");
    let image = sharp('./input/' + fileName);
    image.metadata()
        .then(metadata => {
            image.clahe({ width: metadata.width, height: metadata.height })
                .normalise()
                .withMetadata()
                .toFile('./output/' + fileName);
        })
});
```

**Comment by lovell** [comment]
Perhaps try using CLAHE with a smaller local region.

https://en.wikipedia.org/wiki/Adaptive_histogram_equalization

For example using the following code with the above input:

```js
sharp(input)
  .clahe({ width: 21, height: 21 })
  .normalise()
  ...
```

produces:

![](https://user-images.githubusercontent.com/210965/134784243-acb4b2ff-6a9f-43ca-9730-5f17871740d2.png)

**Comment by mathias22osterhagen22** [comment]
Thank you @lovell, yes in fact with a smaller local region made it look better.

Is there a way to make it automatically brighter or darker?

**Comment by lovell** [comment]
The `normalise` operation will already have spread luminosity over the full range, so if you *always* want it to be brighter you'll need to use [modulate](https://sharp.pixelplumbing.com/api-operation#modulate) and pass either `lightness` (additive) or `brightness` (multiplicative).

**Comment by mathias22osterhagen22** [comment]
Then there is no way to detect it automatically? :/

**Comment by lovell** [comment]
Let's track this at #200, which is about improving `normalise` and should help with this kind of scenario.
