### ISSUE TITLE
Libvips with imagemagick not working

### ISSUE THREAD

**Issue by dvargas135** [lovell/sharp#2907]
I've built libvips from the source tarball with imagemagick support (used the --with-magickpackage flag on ./configure), When it finished running, the imagemagick option was flagged as enabled. 

`pkg-config --modversion vips-cpp` returns `8.11.4` and there are no errors when I do a `npm install sharp`. But when I try to use gif resize with sharp, I get this error:
`Error: GIF output requires libvips with support for ImageMagick`

What am I doing wrong?

**Comment by lovell** [comment]
I'll assume this is superseded by https://github.com/libvips/libvips/issues/2448
