### ISSUE TITLE
Sharp is not a function

### ISSUE THREAD

**Issue by brunoracosta** [lovell/sharp#2909]
Is the same case of [old issue](https://github.com/lovell/sharp/issues/1913), but I did it and not working

I am using:
- "sharp": "^0.29.1",
- "@types/sharp": "^0.29.2",

`    
    

    import sharp, { ResizeOptions } from 'sharp';
    export class image {

        async uploadImage(
            paramFile: Express.Multer.File
        ) {
            try {
                const newImages = [];
                const cropOption = {
                    width: 300,
                    heigth: undefined,
                    fit: undefined,
                    position: undefined,
                }
                const options: ResizeOptions = {
                    fit: cropOption.fit,
                    position: cropOption.position
                };
                const newImage = await sharp(paramFile.buffer)
                    .resize(
                        cropOption.width,
                        cropOption.heigth,
                        options
                    );
                console.log(newImage);

            } catch (error) {
                console.log('error', error);
            }
        }
    }
`

error TypeError: sharp_1.default is not a function

**Comment by brunoracosta** [comment]
I found a way to turn around the issue.

I just import list this:
`import * as Sharp from 'sharp';`

**Comment by anton000** [comment]
can also be fixed by setting `"compilerOptions" : {...,  "esModuleInterop": true }`  in tsconfig.json
