### ISSUE TITLE
Option to replace EXIF metadata

### ISSUE THREAD

**Issue by stackcoder** [lovell/sharp#2910]
**What are you trying to achieve?**
Discard all existing metadata of an image and only write entries specified within `withMetadata` to the file. The current behavior merges existing entries with the new ones.

**Have you searched for similar questions?**
Sure at least: #650, #2724, #2812, #2638, #2507

The `strip` [tag of libvips](https://github.com/libvips/libvips/blob/608a7cee9b2d00e903d5767915e8bfb3fa75e90c/cplusplus/include/vips/VImage8.h#L3601) is `!baton->withMetadata` [controlled](https://github.com/lovell/sharp/blob/f37ca8249afcd26777b7e3e1d0192640572341ef/src/pipeline.cc#L956) by `!baton->withMetadata`. So might be difficult to combine `strip` and updating metadata together within libvips. Is there any other option instead encoding the image twice?

```javascript
// My current workaround:
sharp.prototype.discardMetadata = async function () {
  const {data, info} = await this
    .raw()
    .toBuffer({resolveWithObject: true});
  return sharp(data, {raw: info});
};
```

**Are you able to provide a minimal, standalone code sample that demonstrates this question?**
Already exists, there you go: https://sharp.pixelplumbing.com/api-output#withmetadata

**Are you able to provide a sample image that helps explain the question?**
Not required.

**Comment by lovell** [comment]
This is being covered as part of the work integrating the new "keep" metadata feature of libvips - see https://github.com/lovell/sharp/issues/3824#issuecomment-1809148065

**Comment by lovell** [comment]
Please subscribe to #3824 for updates on the provision of a new `withExif()` function to replace all EXIF metadata.
