### ISSUE TITLE
Most efficient way to generate thumbnails of an image (many sizes, many formats)?

### ISSUE THREAD

**Issue by broofa** [lovell/sharp#2912]
What's the best way to generate thumbnails of various sizes and formats for a given image as efficiently as possible?

Specifically, let's say I have a very large source image (say... 4096 x 4096), "A",  that I'd like to generate 1024w, 512w, and 128w thumbnails for, in both WEBP and PNG formats.  Obviously, I could do something like this:
```javascript
const src = sharp('A');
for (let size of [1024, 512, 128]) {
  src.resize(size).toFile(`A_${size}.jpg`);
  src.resize(size).toFile(`A_${size}.png`);
}
```
... but (if I'm reading the `sharp` source right) that will result in a  full scan of the source image for each`toFile()` call, right?

A more efficient way to do this (I believe) would be to reduce the size of the image at each step, so not as much data needs to be processed each time, like so:
```javascript
let src = sharp('A');
for (let size of [1024, 512, 128]) {
  // replace src with downsampled version on each pass.
  // Using lossless WEBP here to avoid compounding compression artifacts
  // ISSUE: requires outputting to WEBP, then immediately reparsing. 😢 
  sizeSource = sharp(await src.resize(1024).toFormat('webp', {lossless: true}).toBuffer());

  sizeSource.resize(size).toFile(`A_${size}.jpg`);
  sizeSource.resize(size).toFile(`A_${size}.png`);

  src = sizeSource;
}
```
This is faster, but  the intermediate generation and reparsing of a WEBP image is (I presume) still pretty inefficient.

So... is there a better way to do this?

My understanding of how sharp works, based on reading the source, is that calls like `resize()` are just setting an internal option, that only takes effect when an output format is requested, at which time the input image is scanned and processed.   But this means (I think?) that there isn't a simple way of telling sharp to "apply" settings so that it (internally) has a smaller, more efficiently processed version of the image. So... yeah... I'm wondering if there's a better way.  E.g. something like `src.resize(size).apply()`... 

Does this make sense?

**Comment by lovell** [comment]
For repeated use of the same, filesystem based input, libvips' operation cache should store the decoded input and resized image, so something like the following is probably about as efficient (and simple) as it gets:
```js
const src = 'A';
for (let size of [1024, 512, 128]) {
  await sharp(src).resize(size).toFile(`A_${size}.jpg`);
  await sharp(src).resize(size).toFile(`A_${size}.png`);
}
```
Note the creation of a new sharp instance for each pipeline, and the use of `await` to ensure the first pipeline populates the cache before it's used by the second pipeline.

You may want to experiment with increasing the `memory` option.

https://sharp.pixelplumbing.com/api-utility#cache

**Comment by broofa** [comment]
Thanks for the response.

Unfortunately the way I phrased my question probably distracted from the issue I was trying to get at.  I'm not really concerned about file system I/O since I'm actually using `Buffer` objects throughout  (although it's good to know about `.cache()` and the behavior underlying that).  What I'm really interested in is the resizing performance used to generate the thumbnails.

To that end, I think I've figured out the answer to my original question, which was if there were a way to generate intermediate `sharp` objects at different resolutions without having to serialize-deserialize to a specific image format each time.  (Answer: _"Yes, use the `raw()` data structure"._)

If you could take a look at [this test I've put together](https://replit.com/@broofa/sharp-resizing-perf) [on repl.it] and let me know if I'm missing anything important, I'd appreciate it.   I believe this shows that downsampling the input file at each step yields a ~2X increase in performance.

Here's what I see when I run this:
```
Starting directResize
cache: {
  memory: { current: 0, high: 0, max: 50 },
  files: { current: 0, max: 20 },
  items: { current: 0, max: 0 }
}
1280: 1209.921ms
640: 685.143ms
320: 497.736ms
160: 395.622ms
directResize total: 2796.698ms

Starting cascadeResize
cache: {
  memory: { current: 0, high: 41, max: 50 },
  files: { current: 0, max: 20 },
  items: { current: 0, max: 0 }
}
1280: 977.504ms
640: 278.989ms
320: 97.568ms
160: 35.790ms
cascadeResize total: 1391.360ms
DONE
```

**Comment by broofa** [comment]
Note: If I comment out the code that flushes the `sharp` cache in that repl.it example, [lines 52-54], I get the following:

```
Starting directResize
1280: 939.922ms
640: 290.201ms
320: 414.594ms
160: 214.200ms
directResize total: 1861.157ms

Starting cascadeResize
1280: 763.884ms
640: 279.914ms
320: 90.598ms
160: 15.929ms
cascadeResize total: 1151.923ms
DONE
```

This shows a roughly 35% improvement in the `directResize()` performance... which seems odd to me.  That method is running first, so starts with a fresh cache in both cases.  So... why does resetting the cache before-hand have any effect at all?

Seems weird.

**Comment by broofa** [comment]
Quick question: Do you know if sharp/libvips take advantage of the GPU?  (Asking because this may impact how we provision our AWS environment.)

**Comment by lovell** [comment]
@broofa Were you able to make any progress with this?

**Comment by broofa** [comment]
I was, and thank you for reminding me to respond.  Here's what I ended up going with.  This bought us a ~25-30% perf improvement.  If you see any obvious mistakes or improvements, please let me know.  (Also, feel free to close, and thank you for your help!)
```javascript
const WIDTHS = [1280, 800, 512, 320];
const FORMATS = ['webp', 'jpg'];
let src = sharp(data);
const tasks = [];

// Go in descending order so output of one size can be used as input for the
// next (to reduce amount of data `sharp` has to process).
for (const thumbWidth of WIDTHS) {
  // Downsample to desired size (Using `lossless` to avoid compounding
  // compression artifacts).
  const {
    data,
    info: { width, height, channels }
  } = await src
    .resize({
      width: thumbWidth,
      height: Math.floor(thumbWidth * ASPECT_RATIO),
      fit: 'inside'
    })
    .raw()
    .toBuffer({ resolveWithObject: true });

  // Update `src` to reference downsampled data
  src = sharp(data, { raw: { width, height, channels } });

  // Write to various formats
  for (const format of FORMATS) {
    const thumbTask = src
      .toFormat(format as keyof FormatEnum)
      .toBuffer()
      .then((thumbData: Buffer) => {
        // Code to save thumbnail image goes here
      });

    tasks.push(thumbTask);
  }

  await Promise.all(tasks);
}
```
