### ISSUE TITLE
Interpret BGRA (windows raw screen buffer channel order) in `raw`

### ISSUE THREAD

**Issue by Smilebags** [lovell/sharp#2913]
## What are you trying to achieve?
I am trying to use Sharp to efficiently transfer partial screen captures at interactive rates. I have used RobotJS to create a screen capture containing a region of the screen, but the buffer it returns has an BGRA ordering as opposed to the traditional RGBA order. I am able to pre-process this buffer before the constructor but it is highly inefficient, causing a significant amount of load on the process. Is it possible to interpret the incoming raw data in a different order than RGBA? Or alternatively could I assign a custom colour space to the Sharp instance which has the R and B channels swapped, before converting to the output image?

## Have you searched for similar feature requests?
Yes, I haven't found anything asking for this yet.

## What would you expect the API to look like?
An additional property on `sharp.Raw` named `order` or something similar, with a type of `'RGB' | 'RGBA' | 'BGR' | 'BGRA'`. The `sharp.Raw` type could be a union of `3` or `4` channel objects so that the `order` type gets narrowed by specifying the `channels` property.

## What alternatives have you considered?
Manually re-ordering the buffer before providing it to Sharp.

## Is there a sample image that helps explain?
No. If working correctly, using `'BGRA'` on a regular order buffer should swap the R and B channels.

**Comment by lovell** [comment]
Hi, did you see https://github.com/lovell/sharp/issues/2171#issuecomment-616806979 ?

**Comment by Smilebags** [comment]
I hadn't seen that one, no. Thanks, will give that a try.

**Comment by Smilebags** [comment]
That seems to have worked. Apologies for the unnecessary issue and thanks for the help

**Comment by Smilebags** [comment]
Interestingly, comparing the performance of the two, it seems like simply iterating over the array is around 10-20% faster than using `recomb`. I would have expected it to be a faster operation in Sharp, but I guess it depends entirely on how that has been implemented. Since it's doing a whole matrix multiply in nearly the same time, I guess it makes sense.

**Comment by lovell** [comment]
If you're using a glibc-based Linux then perhaps try increasing the number of libvips threads - see https://sharp.pixelplumbing.com/api-utility#concurrency
