### ISSUE TITLE
Add output option to limit file size

### ISSUE THREAD

**Issue by Aliaksandr-Kasko-JazzTeam** [lovell/sharp#2916]
**What are you trying to achieve?**
I want to limit resulting file size

**Have you searched for similar feature requests?**
Yes

**What would you expect the API to look like?**
I.e. with png format, additional field in options,
`.png({ limitFileSize: 200000 })` (in bytes or kilobytes)

**What alternatives have you considered?**
I've googled a lot and found only alternatives for frontend, but these not applicable for Node.js

**Is there a sample image that helps explain?**
Any image

**Additional**
Now I made a workaround with binary search but for any iteration it performs redundant compressing and in the worst case number of redundant compressings reaches 9.

**Comment by lovell** [comment]
Please can you explain a little more about this. Are you suggesting that processing should be stopped and an Error thrown when the size of the compressed file exceeds the limit?

**Comment by Aliaksandr-Kasko-JazzTeam** [comment]
No. I suggest you to detect (without performing compression) optimal compression level and/or quality to reach limitfileSize. There's no need to throw an Error.

**Comment by lovell** [comment]
Thanks, the only way to know the output file size is to encode the image, so this would require brute force. You mentioned you're already using binary search for this, which seems like a sensible approach, and I'd recommend others who might need this do the same.

**Comment by lqzhgood** [comment]
this features I need that as well. 
I think add `.png({ limitFileSize: 200000 })` to `sharp` is better

**Comment by KishorJena** [comment]
this is very useful. there are many cases where we need the image file to be less then given file size while keeping it close to size limit to have highest quality possible .
