### ISSUE TITLE
libvips: pngload_buffer: too many text chunks

### ISSUE THREAD

**Issue by fvsnippets** [lovell/sharp#2917]
Transformations on some png images, report: "Input buffer has corrupt header: pngload_buffer: too many text chunks".

This "problem" (sometimes this error is ok to happen) was introduced with upgrade to libvips v8.11.3, which limits text chunks in exif metadata to 20.
In libvips v8.11.4, that limit was raised to 50, making it a little more flexible.

Please see https://github.com/libvips/libvips/issues/2433 for details.

So, please kindly upgrade libvips to v8.11.4.

Thank you!

**Comment by lovell** [comment]
To workaround this for now, please either use a globally-installed libvips or sharp v0.28.3.

**Comment by lovell** [comment]
v0.30.0 now available with libvips v8.12.2.
