### ISSUE TITLE
Convert JP2 to Image

### ISSUE THREAD

**Issue by YuanTian1991** [lovell/sharp#2923]
Hi:

Thanks for your hard work on Sharp.

What I need is a node converter to help me to transfer JP2 to normal image formats like JPEG/PNG .etc. I have been searching for solutions for a long time, I want to confirm a bit that Sharp can only export JP2, but not read in JP2 image right? Because in [the API Input page](https://sharp.pixelplumbing.com/api-input), I did not see jp2 listed.

And if anyone knows any other solution to do this job, you may suggest me, thanks a lot!

**Comment by lovell** [comment]
JP2 input and output requires the use of a custom, globally installed libvips.

https://sharp.pixelplumbing.com/api-output#jp2

> Requires libvips compiled with support for OpenJPEG. The prebuilt binaries do not include this - see [installing a custom libvips](https://sharp.pixelplumbing.com/install#custom-libvips).

**Comment by lovell** [comment]
@YuanTian1991 Were you able to make progress with this?

**Comment by YuanTian1991** [comment]
Oh, sorry I forget to follow this issue. I have solved my problem, by using other tools (a js solution, and OpenJPEG as well). I did not manage to get sharp working on JP2.

**Comment by lovell** [comment]
Thanks for the update, use of OpenJPEG with sharp requires the compilation of a custom libvips and is not straightforward (especially on Windows). Glad you worked something out.

**Comment by SariMorgenshtern** [comment]
> Thanks, I will try it, could you provide a demo for **JP2 to JPG/PNG** convertion?

where the example?
