### ISSUE TITLE
Outdated ansi-regex module deep in dependency chain

### ISSUE THREAD

**Issue by villesau** [lovell/sharp#2925]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

What are the steps to reproduce?

1. install sharp
2. run `npm audit --production`
3. above command fails due to vulnerability in `ansi-regex` package

What is the expected behaviour?

To my understanding, `prebuild-install` should be dev dependency and above command should not fail.

Here is the dependency tree:

```
└─┬ sharp@0.29.1
  └─┬ prebuild-install@6.1.4
    └─┬ npmlog@4.1.2
      └─┬ gauge@2.7.4
        └─┬ strip-ansi@3.0.1
          └── ansi-regex@2.1.1
```

**Comment by lovell** [comment]
Did you see [better-npm-audit](https://www.npmjs.com/package/better-npm-audit), which addresses many of the shortcomings of `npm audit`?
