### ISSUE TITLE
yarn ignore cross-platform arguments

### ISSUE THREAD

**Issue by sytolk** [lovell/sharp#2926]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?

yes

On MAC OS I'm installing sharp for linux like this: https://sharp.pixelplumbing.com/install#cross-platform

`npm install --platform=win32 --arch=x64` - successful installed prebuilt binaries for Windows platform
`yarn install --platform=win32 --arch=x64` - this install prebuilt binaries for darwin64 platform..

What is the output of running `npx envinfo --binaries --system`?

System:
    OS: macOS 11.6
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 3.34 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 7.22.0 - ~/.nvm/versions/node/v14.17.5/bin/npm
    Watchman: 2021.09.27.00 - /usr/local/bin/watchman

**Comment by sytolk** [comment]
This miss me.. Thanks @lovell maybe will be good to mention in doc that `--platform=win32 --arch=x64` command line arguments works only with npm

**Comment by lovell** [comment]
Running `npm_config_platform=win32 yarn add sharp` and, when there's a lockfile, `npm_config_platform=win32 yarn install` both install the correct binaries for me using yarn v1.22. (If you're using `x64` then you won't need to worry about the ARM version.)
