### ISSUE TITLE
Move platform.json in accessible place

### ISSUE THREAD

**Issue by sytolk** [lovell/sharp#2928]
What are you trying to achieve?

I want programmatically to check sharp installed platform in node_modules. The only place that show this is platform.json
![A1D37C38-CC06-4DAF-85E0-68445D3B1DDF](https://user-images.githubusercontent.com/1415463/137091742-2e487769-7e0b-47b6-97f7-db4994f67a2c.png)

to check is it right sharp platform installed in node_modules its need to write function like this:

```javascript
function checkInstalledSharpPlatform(targetPlatform, arch) {
 let shrapPath = require.resolve('sharp');
 shrapPath = path.join(shrapPath,'..','..','vendor','8.11.3','darwin-arm64v8','platform.json');

 if (!fs.existsSync(shrapPath)) {
      return false;
 }
 const data = fs.readFileSync(shrapPath, 'utf8');
 return data === '"' + targetPlatform + '-' + arch + '"';
}
```

but this function is not robust (`8.11.3` folder or `darwin-arm64v8` will be changed in the next sharp versions). Can we have platform.json in better place? (like node_modules/sharp/platform.json)

Have you searched for similar feature requests? YES

**Comment by lovell** [comment]
There can be multiple copies of the (internal, not part of the public API) `platform.json` file as multiple vendor binaries per platform-arch combination can co-exist within the same installation tree.

The value in each `platform.json` file should always equal the name of its parent directory. Its presence predates using named directories and isn't really required internally any more, so perhaps we could simplify things and remove these files entirely.

**Comment by lovell** [comment]
Added as `sharp.vendor` via commit https://github.com/lovell/sharp/commit/3da258f6fb1446bc8596070d06119e31c621a073

Example output:
```js
{ current: 'linux-x64', installed: [ 'linux-x64', 'win32-ia32' ] }
```
This will be in v0.30.0.

**Comment by lovell** [comment]
v0.30.0 now available with this feature.
