### ISSUE TITLE
Resizing HEIC issue

### ISSUE THREAD

**Issue by vulcaryn** [lovell/sharp#2929]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`? sharp 0.29.1 with globally installed livips 8.11.4

What are the steps to reproduce?
Try to resize an HEIC file.

What is the expected behaviour?
Get the file resized and readable.

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
```javascript
const fs = require('fs');
const sharp = require('sharp');

const rstream = fs.createReadStream('./test.HEIC');
const outFile = './test-thumbnail.HEIC'

try {
    fs.rmdirSync(outFile)
} catch (e) {}
const writeS = fs.createWriteStream(outFile);

const resizer = sharp().resize(200, 200, {fit: 'contain'});

rstream.pipe(resizer).pipe(writeS);
```
Are you able to provide a sample image that helps explain the problem?
The image is zipped to preserve all metadata and original format.
[test.HEIC.zip](https://github.com/lovell/sharp/files/7336260/test.HEIC.zip)

What is the output of running `npx envinfo --binaries --system`?
  System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 501.48 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.14.0 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman

**Comment by lovell** [comment]
Is this the same thing as you asked in #2924 ? If so, let's continue there.

**Comment by lovell** [comment]
Thanks, that looks like an AVIF image. For HEIF output, sharp uses AV1 compression by default.

https://sharp.pixelplumbing.com/api-output#heif

Perhaps try the following change if you want HEVC compression, as used by HEIC images.

```diff
- const resizer = sharp().resize(200, 200, {fit: 'contain'});
+ const resizer = sharp().resize(200, 200, {fit: 'contain'}).heif({ compression: 'hevc' });
```

**Comment by vulcaryn** [comment]
Thanks for the answer and the help.
