### ISSUE TITLE
Can I build a package that use sharp?

### ISSUE THREAD

**Issue by BadiaValdes** [lovell/sharp#2933]
Hi, I'm trying to create a package that allows me to work fast with sharp. The main functionality of my package are the possible options to modify the image with clarity. Then I use sharp and pass all the user options. When I tested locally it works fine, but when I create a separate project and submit it to full-featured github is when the error occurs.

The error says that sharp is not a function. I looked for similar problems and found that sharp cannot work without the node.js runtime, but I am trying to use my package in a Nest.js project, the same project where the raw code works. 

For my package I am using sharp 0.25.4, but it gave me the same error with 0.29.1 version

**Comment by BadiaValdes** [comment]
Import:

import {sharpImageProcess} from 'sharp-image-filter'

for reproduction:

 sharpImageProcess(pathToImage, ImageName,   res,   {
        outPutFormat: 'jpeg',
        adaptiveFiltering: true,
        width: 600,
        heigth: 600,
        fit: 'cover',
        quality: 50,
      },
    );

You can use it in a simple express call to test it.

I am using res (express response) because the project needs to display the final image on the web. After that you will see the main settings, it is optional so you can remove. The default values are outPutFormat: "webp", quality: 80, fit: "cover" and width and heigth null.

Sorry for all the problems, but in the main project, the load is via DB

**Comment by lovell** [comment]
Perhaps you could add a script to the `package.json` that allows someone else to reproduce this. I would expect to be able to clone the repo, run `npm install` then `npm run your-script` and see the error.

**Comment by BadiaValdes** [comment]
Ok, thanks for your time. I will do as you recommend. I will close the issue. If what you recommend me does not work I will put here the link to stackoverflow.com question. Thanks for answer my question.
