### ISSUE TITLE
Resizing png 16-bit colorspace stopped working after 0.29.1 update

### ISSUE THREAD

**Issue by gforge** [lovell/sharp#2934]
After updating to 0.29.1 from 0.29.0 my tests start failing when parsing buffers after resize

What are the steps to reproduce?
I have a resize function that uses `sharp` and where the data is sent over a buffer where `sharp` fails to reconstruct the `16-bit` data

To reproduce using `sharp`s own unit tests:
```
  it("16-bit PNG after resize should retain 16-bit space", async function () {
    const img = sharp(fixtures.inputPngWithTransparency16bit);
    const orgSpace = (await img.metadata()).space;

    const space = await new Promise((resolve, reject) => {
      img
        .resize(32, 16, { fit: "contain" })
        .toBuffer(async function (err, data, info) {
          if (err) throw err;

          resolve((await sharp(data).metadata()).space);
        });
    });
    assert.equal(space, orgSpace);
  });
```

**Comment by lovell** [comment]
Hi, v0.29.0 and v0.29.1 (and v0.28.3) produce the same result for me, namely that `orgSpace` is "rgb16" and `space` is "srgb", which is expected.

For "rgb16" output use `toColourspace()`, there's an example in the docs at https://sharp.pixelplumbing.com/api-colour#tocolourspace

**Comment by gforge** [comment]
Wow, thanks for the quick reply. Maybe I missed something when writing up my test. My original problem is with "grey16", the  debugging code in my app looks like this:

```ts
  const orgImg = imageCache(path);
  const resized = await orgImg.resize({
    width: maxWidthOrHeight,
    height: maxWidthOrHeight,
    fit: 'inside',
    withoutEnlargement: true,
  });
  const reverted = await new Promise((resolve) =>
    resized.toBuffer(async (err, data) => {
      resolve(await (await sharp(data).metadata()).space);
    }),
  );
  console.log({ org: (await orgImg.metadata()).space, resized: (await resized.metadata()).space, reverted });
```

In v0.29.0 I get the output:
`{ org: 'grey16', resized: 'grey16', reverted: 'grey16' }`

while if I upgrade to v0.29.1 I get:
`{ org: 'grey16', resized: 'grey16', reverted: 'b-w' }`

is this just as expected?

**Comment by gforge** [comment]
So I've been trying to dig a little deeper into this rabbit hole... Are these assumptions correct?

* A sharp object that is called `toBuffer()` on will be converted to 8-bit format
* Calling `.raw()` will inhibit the compression and allow a per-pixel output but in 8-bit (i.e. the length = width * height)
* Calling `.raw({ depth: 'ushort' })` will retain the full 16-bit resolution in the format of a Uint8Array with lower and upper byte separation (i.e. the length = width * height * 2)
* Recreating from the raw buffers is impossible as meta-data isn't available

The task that I'm trying to solve is sending a 16-bit image to the front-end and sometimes resizing the image but I don't want to drop the bit depth in the process. Currently I use `myResizedImage.pipe(expressRespons)` but maybe I've misunderstood how `sharp` works?

**Comment by gforge** [comment]
So I think everything stems from the issue that you set the pngBitDepth to 8 without allowing the user to modify this and it doesn't respond to the colorspace. So I get this test to pass:

```js
  it("16-bit PNG after resize should retain 16-bit space", async function () {
    const img = sharp(fixtures.inputPng16BitGrey16).toColourspace("grey16");
    const meta = await img.metadata();

    const space = await new Promise((resolve, reject) => {
      img
        .resize(32, 16, { fit: "contain" })
        .png({ pngBitdepth: 16 })
        .toBuffer(async function (err, data, info) {
          if (err) throw err;

          resolve((await sharp(data).metadata()).space);
        });
    });
    assert.equal(space, meta.space);
  });
```

after adding this section to the output > png():

```js
    if (is.defined(options.pngBitdepth)) {
      if ([8, 16].includes(options.pngBitdepth)) {
        this.options.pngBitdepth = options.pngBitdepth;
      } else {
        throw is.invalidParameterError('pngBitdepth', 'integer of 8 or 16', options.png);
      }
    }
```

There should probably be a section in the `toColourspace()` that sets the bit depth depending on the colors-space, e.g.

```
if (colourspace.match(/16$/)) {
   this.options.pngBitdepth = 16
} else {
   this.options.pngBitdepth = 8
}
```

I'm not working with the other formats but I guess an option worth considering is having a general bit depth setting makes more sense, a quick search indicates that you have both `pngBitDepth` and `tiffBitDepth` that most likely serve the same purpose.

**Comment by gforge** [comment]
Sorry for being slow, you are of course right in how this works. I've run a few more tests and it seems that no information is lost and the only problem is that it defaults to the 'b-w' colorspace. The following test code runs without any issues (the `inputPng16BitGrey16` is my own test image, a simple 50 x 50 grey16 image created in Gimp):

```js
  it("16-bit PNG to and from buffer should retain 16-bit space", async function () {
    const img = sharp(fixtures.inputPng16BitGrey16);
    const meta = await img.metadata();

    const { newMeta, newImg } = await new Promise((resolve, reject) => {
      img
        .resize(meta.width / 2, meta.height / 2)
        .toBuffer(async function (err, data, info) {
          if (err) throw err;

          const imgFromBuffer = sharp(data);
          resolve({
            newMeta: await imgFromBuffer.metadata(),
            newImg: imgFromBuffer,
          });
        });
    });

    const bufferOrg = await sharp(fixtures.inputPng16BitGrey16)
      .toColourspace(meta.space)
      .raw({ depth: "ushort" })
      .toBuffer();
    const bufferNew = await newImg
      .toColourspace(meta.space)
      .raw({ depth: "ushort" })
      .toBuffer();

    assert.equal(bufferOrg.length / 4, bufferNew.length);
    assert.equal(bufferNew.length, newMeta.width * newMeta.height * 2);
  });
``` 
It would be nice if there was a little more behind-the-scenes in the docs but I guess that wouldn't have saved me from making this mistake. For me the most important thing is that nothing is lost when sending the image through the pipe command.

It would be nice if the space was retained after running the image through a buffer but if this isn't possible then feel free to close this issue and once again, thank you for taking the time in answering my questions and building this awesome library!

**Comment by lovell** [comment]
Please can you create a standalone repo with code and images that allows someone else to reproduce this. I ask this as the appearance of `.png({ pngBitdepth: 16 })` suggests you are using a modified version of sharp; that option is not part of sharp's API.

**Comment by gforge** [comment]
Sure, I've pushed my suggested fix and linked a PR so that hopefully is clearer what I've done. It is the same fix that I mentioned in one of my above comments but this issue is becoming quite the read...

**Comment by lovell** [comment]
Thanks for the extra info. I've opened an upstream PR for this at https://github.com/libvips/libvips/pull/2515

Once that's landed, the fix to sharp should be a one-liner, something like:

```diff
--- a/src/pipeline.cc
+++ b/src/pipeline.cc
@@ -994,7 +994,7 @@ class PipelineWorker : public Napi::AsyncWorker {
             ->set("filter", baton->pngAdaptiveFiltering ? VIPS_FOREIGN_PNG_FILTER_ALL : VIPS_FOREIGN_PNG_FILTER_NONE)
             ->set("palette", baton->pngPalette)
             ->set("Q", baton->pngQuality)
-            ->set("bitdepth", baton->pngBitdepth)
+            ->set("bitdepth", sharp::Is16Bit(image.interpretation()) ? 16 : baton->pngBitdepth)
             ->set("dither", baton->pngDither));
           baton->formatOut = "png";
         } else if (baton->formatOut == "webp" || (mightMatchInput && isWebp) ||
```

**Comment by gforge** [comment]
Awesome, great to know that this isn't due to my lack of understanding.

**Comment by lovell** [comment]
v0.30.0 now available, thanks again for reporting.
