### ISSUE TITLE
Cannot install sharp from source on Windows 10 + Node.js 14 - Exception support not detected

### ISSUE THREAD

**Issue by JCMais** [lovell/sharp#2937]
I am trying to install sharp from source with debug symbols (as I'm trying to debug a segmentation fault), but I had the following error:

```
node_modules\node-addon-api\napi.h(33,1): fatal error C1189: #error:  Exception support not detected.       Define either NAPI_CPP_EXCEPTIONS or NAPI_DISABLE_CPP_EXCEPTIONS. [node_modules\sharp\build\sharp-win32-x64.vcxproj]
```

To fix it I had to open the Visual Studio solution directly and add the define (in my case I added `NAPI_DISABLE_CPP_EXCEPTIONS`) to make it work.

The error is coming from node-addon-api itself:

https://github.com/nodejs/node-addon-api/blob/cb228418e6df1d613bc262504b856f95c69900e1/napi.h#L26-L35

What is the output of running `npx envinfo --binaries --system`?

```
  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 4.03 GB / 31.95 GB
  Binaries:
    Node: 14.17.5 - E:\langs\nodejs\node.EXE
    Yarn: 1.22.5 - E:\Tools\Yarn\bin\yarn.CMD
    npm: 6.14.14 - E:\langs\nodejs\npm.CMD
```

**Comment by lovell** [comment]
Happy to accept a PR if you're able.
