### ISSUE TITLE
OS X + gcc (was: Node-gyp rebuild error)

### ISSUE THREAD

**Issue by bruno12mota** [lovell/sharp#294]
Hi @lovell was wondering if you could help me, trying to make relax support node 4, and I'm stuck on sharp build, getting the following:

`````
CXX(target) Release/obj.target/sharp/src/common.o
c++: error: unrecognized command line option '-stdlib=libc++'
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/brunomota/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/brunomota/.nvm/versions/node/v4.1.2/bin/node" "/Users/brunomota/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/brunomota/Sites/relax/node_modules/sharp
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/brunomota/.nvm/versions/node/v4.1.2/bin/node" "/Users/brunomota/.nvm/versions/node/v4.1.2/bin/npm" "i" "sharp"
npm ERR! node v4.1.2
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
`````

I'm using gcc version 4.8.4, am I missing something? Not my strong this area :disappointed: 

Thanks!

**Comment by lovell** [comment]
Hi Bruno, "Darwin 15.0.0" tells me you're using OS X 10.11, for which sharp assumes xcode/clang is being used rather than gcc.

Are you able to test the following change to binding.gyp locally to see if this works with gcc?
 
```
     'xcode_settings': {
       'OTHER_CPLUSPLUSFLAGS': [
-        '-std=c++11',
-        '-stdlib=libc++',
         '-fexceptions',
         '-Wall',
         '-O3'
       ],
+      'CLANG_CXX_LIBRARY': 'libc++',
+      'CLANG_CXX_LANGUAGE_STANDARD':'c++11',
       'MACOSX_DEPLOYMENT_TARGET': '10.7'
     },
```

**Comment by bruno12mota** [comment]
Just tried, added as a git dependency from this branch https://github.com/bruno12mota/sharp, the error is the same though. Should I look into updating clang instead? looking for a solution which would work the best to give as simple instructions for the users

**Comment by bruno12mota** [comment]
By the way my clang version, if needed:

Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin15.0.0
Thread model: posix

**Comment by lovell** [comment]
Did you recently upgrade to OS X 10.11? I've heard from a couple of sources that xcode might need to be reinstalled via `xcode-select --install`.

**Comment by bruno12mota** [comment]
Will try it out now, thanks so much for your help! Will let you know if it works

**Comment by bruno12mota** [comment]
Still no luck, updated xcode:

`````
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
`````

But getting the exact same error, tried with the changed fork, and with the current sharp version. Will try a few things out, will let you know if I can find a solution

**Comment by bruno12mota** [comment]
Tried removing the gcc version i had installed, so using the default xcode clang version, still errors out but it is a different one, any idea?

`````
CXX(target) Release/obj.target/sharp/src/common.o
/Users/brunomota/Sites/relax/node_modules/.bin/touch: line 1: syntax error near unexpected token `('
/Users/brunomota/Sites/relax/node_modules/.bin/touch: line 1: `var touch = require("../touch")'
make: *** [Release/obj.target/sharp/src/common.o] Error 2
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/brunomota/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/brunomota/.nvm/versions/node/v4.1.2/bin/node" "/Users/brunomota/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/brunomota/Sites/relax/node_modules/sharp
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
``````

**Comment by lovell** [comment]
Please can you provide the output `npm install --verbose`, perhaps as a gist.

https://github.com/node-inspector/node-inspector/issues/760#issuecomment-154361714 might be relevant too.

**Comment by bruno12mota** [comment]
https://gist.github.com/bruno12mota/efa055e9f02553fcb2d5 here it is, the sharp build part only. I'll take a look to the node-inspector issue

**Comment by bruno12mota** [comment]
OH, got it! made a npm install touch as someone said in the node-inspector issue and it compiled perfectly :smile: 

Cheers, thanks so much for your help!

**Comment by lovell** [comment]
Glad to hear you got everything working again after the upgrade.

I'm not sure how many people use the "proper" gcc instead of the default clang's gcc-like wrapper on OS X. Supporting both might be more of a gyp responsibility anyway.

There is a (very) basic OS X 10.9 + Node v0.10 test environment for sharp e.g. https://travis-ci.org/lovell/sharp-osx-ci/builds/90407217 and I hope to improve that situation via #248.

Closing this for now - feel free to re-open if this problem occurs again.

**Comment by objectiveSee** [comment]
@bruno12mota can you explain what issue was caused regarding `npm install touch` and how you fixed it?
