### ISSUE TITLE
It's not possible to install sharp

### ISSUE THREAD

**Issue by riccardobellomi** [lovell/sharp#2942]
I used sharp for about a year on another app, no problems at all for that period.
Now I am trying to install it on another app, through npm, and it is just not possible.
I tried upgrading my npm, I tried using both --unsafe-perm and --ignore-scripts, I tried deleting the npm_modules and package.json, to then run npm install... It just doesn't work!
I even tried adding "minipass": "2.7.0" on dependencies, nothing is fixing the issue.

I've seen the same issue popping up from 2019

ERROR:
`
sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.11.3/libvips-8.11.3-linux-x64.tar.br
remote:        sh: 1: prebuild-install: Permission denied
remote:        make: Entering directory '/tmp/build_e87a24ec/node_modules/sharp/build'
remote:          CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
remote:          AR(target) Release/obj.target/../node-addon-api/nothing.a
remote:          COPY Release/nothing.a
remote:          TOUCH Release/obj.target/libvips-cpp.stamp
remote:          CXX(target) Release/obj.target/sharp-linux-x64/src/common.o
remote:        ../src/common.cc:24:10: fatal error: vips/vips8: No such file or directory
remote:         #include <vips/vips8>
remote:                  ^~~~~~~~~~~~
remote:        compilation terminated.
remote:        sharp-linux-x64.target.mk:139: recipe for target 'Release/obj.target/sharp-linux-x64/src/common.o' failed
remote:        make: *** [Release/obj.target/sharp-linux-x64/src/common.o] Error 1
remote:        make: Leaving directory '/tmp/build_e87a24ec/node_modules/sharp/build'
remote:        gyp ERR! build error
`

**Comment by beita1** [comment]
> I had the same issue the first time when I executed `npm i sharp`, but the second time I executed `npm i -verbose sharp` and it installed successfully.

**Comment by CN91** [comment]
I am currently running into the same thing. I vendored the build, and the build is now going fine. But when uploaded to the cloud foundry environment the rebuild fails on this exact error. 

Even though 

```
NPM_CONFIG_SHARP_INSTALL_FORCE=true
   2022-06-20T13:38:21.54+0200 [STG/0] OUT        NPM_CONFIG_SHARP_LIBVIPS_LOCAL_PREBUILDS=tmp/app/prebuilds
   2022-06-20T13:38:21.54+0200 [STG/0] OUT        NPM_CONFIG_LOGLEVEL=verbose
   2022-06-20T13:38:21.54+0200 [STG/0] OUT        NPM_CONFIG_SHARP_LOCAL_PREBUILDS=tmp/app/prebuilds
   2022-06-20T13:38:21.54+0200 [STG/0] OUT        NPM_CONFIG_TARBALL=tmp/app/prebuilds/node_headers/node-v16.14.2-headers.tar.gz
```

is provided. However the path while building is different from the path on the cloud foundry environment. Could that be the issue?

**Comment by beita1** [comment]
已收到，谢谢
