### ISSUE TITLE
CANNOT LINK EXECUTABLE "node": cannot locate symbol "_emutls_get_addr ess" referenced by "/data/data/com. termux/files/usr/bin/node"..  Aborted

### ISSUE THREAD

**Issue by fauzichan** [lovell/sharp#2945]
I think this is quite confusing after I installed node js in 'termux' using the command "pkg install nodejs" after I installed it, how come there is some kind of writing that says 'CANNOT LINK EXECUTABLE "node": cannot locate symbol "_emutls_get_addr ess" referenced by "/data/data/com. termux/files/usr/bin/node"..

Aborted' like exactly the picture below
![Screenshot_2021-10-25-07-51-20-13](https://user-images.githubusercontent.com/92693677/138669401-9c911e63-acdc-4abe-9235-fba0c0bc47b5.jpg)
And I also hope to fix this case soon INFO
'emulator :' Termux
'Device :' Android
'Ver termux :' 0.101

**Comment by keli0729** [comment]
How to solve for you? I have the same proble as you.
