### ISSUE TITLE
HDR Support

### ISSUE THREAD

**Issue by Gatts011** [lovell/sharp#2947]
What are you trying to achieve?
Convert HDRI to anything else, libvips supports hdr format

Have you searched for similar feature requests?
Yes

What would you expect the API to look like?
```
  if (descriptor->rawChannels > 3) {   //channels are more than 3 - hdr has 10 ish?
          image.get_image()->Type = VIPS_INTERPRETATION_HDR;
   }
  ... flatten channels to RGB(3) something something..
```

```
fs.readFile("test.hdr", function (err, data) {
  if (err) throw err;
  // console.log(data);  
  sharp(data)
    .toFile('output.jpeg', (err, info) => {
      if (err) {
        console.log(err);
      }
      console.log(info)
    });
});
//[Error: Input buffer contains unsupported image format] :(
```

What alternatives have you considered?
Using libvibs directly? 

Is there a sample image that helps explain?
any hdri

**Comment by lovell** [comment]
Does this refer to the Radiance/RGBE image format? If so, you'll need to use a custom libvips compiled with support for this format as the prebuilt binaries do not include it.

https://sharp.pixelplumbing.com/install#custom-libvips

**Comment by Gatts011** [comment]
Im unfortunately using windows, so compiling a custom, globally-installed version of libvips will be difficult. I'll look into compiling with ubuntu for windows or hijack my brothers machine... unless you know a simpler way?

**Comment by lovell** [comment]
Using a custom libvips on Windows is unsupported.
