### ISSUE TITLE
toFormat resulting in error: "Cannot read property 'toLowerCase' of undefined" 

### ISSUE THREAD

**Issue by ed4becky** [lovell/sharp#2948]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

Yes

What are the steps to reproduce?

Using this code, I get the error in toFormat.  If I comment out the toFormat, all is well:
```
    const options = {
      fit: fit.cover,
      background: { r: 0, g: 0, b: 0, alpha: 1 },
      withoutEnlargement: true
    };
    const readableStream = this.getReadableFromURL(filePath);
    const smallWritableStream = this.getSmallWritable(filePath);
    const largeWritableStream = this.getLargeWritable(filePath);
    const pipeline = sharp();
    pipeline.clone()
      .resize(150, 150, options)
      .toFormat(format.jpg)
      .pipe(smallWritableStream);
    pipeline.clone()
      .resize(300, 300, options)
      .toFormat(format.jpg)
      .pipe(largeWritableStream);
    readableStream.pipe(pipeline);
```

This happens with any image, png or jpg

What is the expected behaviour?

Able to convert png files to jpg

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

Are you able to provide a sample image that helps explain the problem?

What is the output of running `npx envinfo --binaries --system`?

PS D:\Users\ed\IdeaProjects\WebstormProjects\evidentia> npx envinfo --binaries --system

  System:
    OS: Windows 10 10.0.22000
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 34.55 GB / 63.93 GB
  Binaries:
    Node: 14.17.5 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.14 - D:\Program Files\nodejs\npm.CMD

**Comment by lovell** [comment]
Perhaps try the following change to your code to ensure the value passed to `toFormat` is defined.
```diff
- .toFormat(format.jpg)
+ .toFormat(sharp.format.jpeg)
```

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
