### ISSUE TITLE
Error: Input buffer has corrupt header: pngload_buffer: too many text chunks

### ISSUE THREAD

**Issue by fredrikaurdal** [lovell/sharp#2949]
I'm converting a PNG file to JPG but getting the following error:

`Error: Input buffer has corrupt header: pngload_buffer: too many text chunks`

The code I'm running:

```
const got = require('got');
const sharp = require('sharp');

const url = 'https://gateway.pinata.cloud/ipfs/QmeJLkBxYayBNmpMej8C6dN5FHHbkiTN5G9jRyuynfxmGB/nft.png';
const request = await got(url).buffer();

const data = await sharp(request).resize({ width: 512 }).jpeg({ quality: 70 }).toBuffer();
```

It's an image of an NFT artwork stored on IPFS, which is why it can take some time to load the image. But that doesn't have anything to do with the error.

The only other related issue I could find is [this](https://giters.com/lovell/sharp/issues/2917), but it doesn't solve the problem I'm facing.

I'm using the latest version of sharp, 0.29.2.

**envinfo**:

System:

- OS: Windows 10 10.0.22000
- CPU: (6) x64 AMD Ryzen 5 4500U with Radeon Graphics
- Memory: 5.25 GB / 15.37 GB

Binaries:

- Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
- npm: 7.19.0 - C:\Program Files\nodejs\npm.CMD

**Comment by lovell** [comment]
Please see #2917
