### ISSUE TITLE
can not install sharp by npm

### ISSUE THREAD

**Issue by ElapsedSoul** [lovell/sharp#2950]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?
yes
Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?
yes
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
no
$ npm ls sharp
word@1.0.0 D:\work\code\js
`-- (empty)

$ npm view sharp dist-tags.latest
0.29.2

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?
yes
If you are using npm v7, does the user running `npm install` own the directory it is run in?
N/A
If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?
yes
What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?
npm verb node v12.18.0
npm verb npm  v6.14.4
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.29.2 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.29.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 38242ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\LENOVO\AppData\Roaming\npm-cache\_logs\2021-10-26T06_59_13_826Z-debug.log
What is the output of running `npx envinfo --binaries --system`?
npx: 1 安装成功，用时 4.531 秒

  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 5.81 GB / 15.60 GB
  Binaries:
    Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD

$ npm config list
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.14.4 node/v12.18.0 win32 x64"

; userconfig C:\Users\LENOVO\.npmrc
registry = "https://registry.npmjs.org/"
sharp_binary_host = "https://npm.taobao.org/mirrors/sharp"
sharp_libvips_binary_host = "https://npm.taobao.org/mirrors/sharp-libvips"

; builtin config undefined
prefix = "C:\\Users\\LENOVO\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = D:\work\code\js
; HOME = C:\Users\LENOVO
; "npm config ls -l" to show all defaults.

error infos:

sharp: Downloading https://npm.taobao.org/mirrors/sharp-libvips/v8.11.3/libvips-8.11.3-win32-x64.tar.br
sharp: Installation error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80
sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies

addition:npm proxy is null

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/1845#issuecomment-524580569

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
