### ISSUE TITLE
svg font: Input buffer has corrupt header: svgload_buffer: bad dimensions

### ISSUE THREAD

**Issue by ike666666** [lovell/sharp#2954]
Version: "sharp": "^0.29.2",

Problem description: Cannot support svg font

Error: Input buffer has corrupt header: svgload_buffer: bad dimensions
E.g:
![image](https://user-images.githubusercontent.com/80997875/139394126-561f55f1-8fbe-4b6e-a20e-6e2d33cbf15b.png)

**Comment by lovell** [comment]
You've attached a screenshot rather than an image file, which makes it hard for someone else to reproduce, but my best guess is that you need to add either a `width` and `height` or a `viewBox` to the `<svg>` element.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with a sample image (and not a screenshot) if further assistance is required.

**Comment by evansnicholas** [comment]
Just a little extra info on this. I am having the same issue with the following SVG file:

![reporter](https://user-images.githubusercontent.com/3777208/165789762-903d2285-96b0-4230-8a81-ce4acd1a46eb.svg)

This does work with sharp v0.23.4 but not with sharp v0.30.3. This SVG also doesn't have a width/height/viewbox but I tried adding one and then it does work. Somehow this doesn't feel quite right though as this is not a requirement on SVG's (the svg validates fine without it). So it seems like something has changed in the svg processing lib that has made it stricter...
