### ISSUE TITLE
Sharp resize function modifies image metadata

### ISSUE THREAD

**Issue by handriss** [lovell/sharp#2955]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
Used version: sharp@0.29.2

What are the steps to reproduce?
I am using sharp's resize function chained with the `withMetadata` function to preserve the source image's metadata in the output image.
To reproduce the issue:
- clone this repository: https://gitlab.com/andras.hinkel/sharp-resizer-so-question
- run `npm install`
- run `npm start`

This will print the metadata of the source image and the output image. There are differences between the two, for example:
- source image: '305': 'Adobe Photoshop Lightroom 5.5 (Macintosh)'
- output image: '305': 'Adobe Photoshop Lightroom 5.5 (Macintosh) (Adobe Photoshop Lightroom 5.5'

What is the expected behaviour?
The two metadata objects should be the same except for the fields that represent the size of the images.

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
To reproduce the issue:
- clone this repository: https://gitlab.com/andras.hinkel/sharp-resizer-so-question
- run `npm install`
- run `npm start`

Are you able to provide a sample image that helps explain the problem?
The sample source is in the repository.

What is the output of running `npx envinfo --binaries --system`?
```
  System:
    OS: Linux 5.8 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-6440HQ CPU @ 2.60GHz
    Memory: 741.55 MB / 15.53 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.0/bin/yarn
    npm: 7.16.0 - ~/.nvm/versions/node/v14.16.0/bin/npm
```

Note: I asked the same question on stackoverflow, too, in the hopes of a quicker resolution, it might have been already answered there by the time you read this: https://stackoverflow.com/questions/69771773/sharp-resize-function-modifies-image-metadata

**Comment by lovell** [comment]
Please see #2832
