### ISSUE TITLE
install sharp failed

### ISSUE THREAD

**Issue by huihuilovekuikui** [lovell/sharp#2957]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?
yes
Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?
yes
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
yes
If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?
yes

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@6.14.13
npm info using node@v14.17.3
npm verb npm-session 3ad46f8fb09b0c64
npm http fetch GET 304 https://registry.npmjs.org/sharp 972ms (from cache)
npm timing stage:loadCurrentTree Completed in 1072ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 13ms
npm http fetch GET 304 https://registry.npmjs.org/color 264ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-fs 714ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tunnel-agent 736ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/prebuild-install 753ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/detect-libc 773ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-get 774ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/semver 782ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-addon-api 828ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-convert 252ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-string 289ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-name 255ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-swizzle 260ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-arrayish 261ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mkdirp-classic 262ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minimist 266ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/napi-build-utils 265ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/rc 271ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/npmlog 273ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/github-from-package 284ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/expand-template 293ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-abi 293ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/pump 1390ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/are-we-there-yet 259ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/gauge 260ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/console-control-strings 266ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/set-blocking 886ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/delegates 268ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/readable-stream 278ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/process-nextick-args 243ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/safe-buffer 256ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/string_decoder 257ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/isarray 259ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/core-util-is 273ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/util-deprecate 277ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/inherits 921ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/signal-exit 248ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/strip-ansi 249ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/has-unicode 258ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/aproba 265ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/object-assign 267ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/string-width 291ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/wide-align 1555ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-fullwidth-code-point 271ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/code-point-at 277ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/number-is-nan 262ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ansi-regex 731ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/end-of-stream 255ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/once 2488ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/wrappy 249ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ini 239ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/deep-extend 267ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/strip-json-comments 267ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-concat 246ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 816ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mimic-response 730ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-stream 260ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/chownr 884ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bl 836ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-constants 889ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/buffer 283ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ieee754 250ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/base64-js 272ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lru-cache 781ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/yallist 246ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 16171ms
npm timing stage:loadIdealTree Completed in 16201ms
npm timing stage:generateActionsToTake Completed in 6ms
npm verb correctMkdir C:\Users\Administrator\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
npm verb makeCacheDir UID & GID are irrelevant on win32
npm verb lock using C:\Users\Administrator\AppData\Roaming\npm-cache\_locks\staging-0f9864afb43208ed.lock for D:\hui_workspace\study\nodejs课堂资料\code\03_learn-node\01_Buffer的 
使用\node_modules\.staging
npm timing action:extract Completed in 36ms
npm info lifecycle sharp@0.29.2~preuninstall: sharp@0.29.2
npm info lifecycle sharp@0.29.2~uninstall: sharp@0.29.2
npm verb unbuild rmStuff sharp@0.29.2 from D:\hui_workspace\study\nodejs课堂资料\code\03_learn-node\01_Buffer的使用\node_modules
npm info lifecycle sharp@0.29.2~postuninstall: sharp@0.29.2
npm timing action:unbuild Completed in 4ms
npm timing action:remove Completed in 12ms
npm timing action:finalize Completed in 3ms
npm timing action:refresh-package-json Completed in 9ms
npm info lifecycle sharp@0.29.2~preinstall: sharp@0.29.2
npm timing action:preinstall Completed in 1ms
npm info linkStuff sharp@0.29.2
npm timing action:build Completed in 1ms
npm info lifecycle sharp@0.29.2~install: sharp@0.29.2

> sharp@0.29.2 install D:\hui_workspace\study\nodejs课堂资料\code\03_learn-node\01_Buffer的使用\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.11.3/libvips-8.11.3-win32-x64.tar.br
sharp: Installation error: read ECONNRESET
sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm verb lifecycle sharp@0.29.2~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.29.2~install: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\hui_workspace\study\nodejs课堂资料\code\03_learn-node\01_Buffer的使用\node_modules\sharp\node_modules\.bin;D:\hui_workspace\study\nodejs课堂资料\code\03_learn-node\01_Buffer的使用\node_modules\.bin;D:\install\Git\mingw64\bin;D:\install\Git\usr\bin;C:\Users\Administrator\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;D:\install\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Program Files\nodejs;C:\Program Files\MySQL\MySQL Server 8.0\bin;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Administrator\AppData\Roaming\npm
npm verb lifecycle sharp@0.29.2~install: CWD: D:\hui_workspace\study\nodejs课堂资料\code\03_learn-node\01_Buffer的使用\node_modules\sharp
npm timing audit submit Completed in 363ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 363ms
npm timing audit body Completed in 0ms
npm info lifecycle sharp@0.29.2~install: Failed to exec install script
npm timing action:install Completed in 19722ms
npm verb unlock done using C:\Users\Administrator\AppData\Roaming\npm-cache\_locks\staging-0f9864afb43208ed.lock for D:\hui_workspace\study\nodejs课堂资料\code\03_learn-node\01_Buffer的使用\node_modules\.staging
npm timing stage:rollbackFailedOptional Completed in 11ms
npm timing stage:runTopLevelLifecycles Completed in 37109ms
npm WARN 01_buffer@1.0.0 No description
npm WARN 01_buffer@1.0.0 No repository field.

npm verb stack Error: sharp@0.29.2 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:375:28)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:375:28)
npm verb stack     at maybeClose (internal/child_process.js:1055:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm verb pkgid sharp@0.29.2
npm verb cwd D:\hui_workspace\study\nodejs课堂资料\code\03_learn-node\01_Buffer的使用
npm verb Windows_NT 10.0.19043
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose" "sharp"
npm verb node v14.17.3
npm verb npm  v6.14.13
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.29.2 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)`    
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.29.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 37437ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2021-10-31T14_55_48_879Z-debug.log
What is the output of running `npx envinfo --binaries --system`?
  System:
    OS: Windows 10 10.0.19043
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 6.68 GB / 15.93 GB
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD

**Comment by huihuilovekuikui** [comment]
and i can install sharp@0.28.3
![image](https://user-images.githubusercontent.com/66559869/139589985-6f744b7e-edb9-4e44-8ffc-c9beee2bcfc9.png)
and i can't install the latest

**Comment by lovell** [comment]
The salient part of this error message is:
```
sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.11.3/libvips-8.11.3-win32-x64.tar.br
sharp: Installation error: read ECONNRESET
```
If you're located in China and have problems connecting to GitHub, please see https://sharp.pixelplumbing.com/install#chinese-mirror

**Comment by huihuilovekuikui** [comment]
> The salient part of this error message is:
> 
> ```
> sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.11.3/libvips-8.11.3-win32-x64.tar.br
> sharp: Installation error: read ECONNRESET
> ```
> 
> If you're located in China and have problems connecting to GitHub, please see https://sharp.pixelplumbing.com/install#chinese-mirror

**Comment by huihuilovekuikui** [comment]
I failed to install sharp-libvips. Maybe in China. I solved this problem after setting up the image.thanks
