### ISSUE TITLE
metadata() returns original width and height after resize and rotation

### ISSUE THREAD

**Issue by lanyusan** [lovell/sharp#2959]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

Using sharp@0.29.1
Latest dist is: sharp@0.29.2

What are the steps to reproduce?

```
const img = sharp('abc.png')
const {width, height} = await img.metadata()

const { width: w2, height: h2} = await img.resize({width: width *2}).rotate(45).metadata()
```

What is the expected behaviour?

w2 should be changed to the actual width after resize and rotate. But it remains unchanged.

I had to use 
```
const meta = await sharp( await img.toBuffer()).metadata()
```
to get the new meta after transform. 

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

Are you able to provide a sample image that helps explain the problem?

What is the output of running `npx envinfo --binaries --system`?

**Comment by lovell** [comment]
This is the expected behaviour. I think the example provided here needs to `await` the `toBuffer` call also to work correctly.

```diff
- const meta = await sharp( img.toBuffer()).metadata()
+ const meta = await sharp(await img.toBuffer()).metadata()
```

The output is only generated when `toBuffer` or `toFile` (or, implicitly for Streams, `pipe`) are called.

**Comment by lanyusan** [comment]
Fixed the typo. It was keyed in on spot. 

Thanks for the clarification. Maybe clarify it in documentation? I was confused by it and spent some time to find it out.

**Comment by lovell** [comment]
Added via commit https://github.com/lovell/sharp/commit/2b8e4d20dea94f77fee2ae2f75b400550ce9abd0, thanks for the suggestion.
