### ISSUE TITLE
Error: Processed image is too large for the WebP format

### ISSUE THREAD

**Issue by detailcore** [lovell/sharp#2962]
I am getting an error in the console while converting PNG to WEBP. How can you get around this limitation? ( https://developers.google.com/speed/webp/faq#what_is_the_maximum_size_a_webp_image_can_be )

Image: https://drive.google.com/file/d/1Ovv6YVHzl_fAXBPfMblJpjl7JjMYhWZC/view?usp=sharing
Size image: 14,4Mb / w720px * h37062px

Example code:
```
const { data } = await sharp('path/file.png', { animated: true })
    .webp({ 
        lossless: true,
    })
    .toBuffer({ resolveWithObject: true });
const imageBuffer = new Uint8ClampedArray(data.buffer);
await sharp(imageBuffer).toFile('path/file.webp');
```

  Version: -- sharp@0.29.2
  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 15.73 GB / 23.94 GB
  Binaries:
    Node: 12.21.0
    npm: 6.14.8

**Comment by lovell** [comment]
https://developers.google.com/speed/webp/faq#what_is_the_maximum_size_a_webp_image_can_be
