### ISSUE TITLE
How to keep colors and size with this CMYK source image?

### ISSUE THREAD

**Issue by bruno-xo7** [lovell/sharp#2964]
Hello,

We have received an image that has the following characteristics:
- channels:4
- chromaSubsampling: '4:2:0:4'
- density:120
- space: 'cmyk'
- size:580847

A basic handle by sharp give a poor result in terms of color rendering:
```js
await sharp(imageContent).toBuffer();
```
and the result have this characteristics:
- channels:3
- chromaSubsampling:'4:2:0'
- density:72
- space:'srgb'
- size: 288137

| Original Image  | Sharp Output (1) |
| -------------------- | ----------------------- |
| ![original-image](https://user-images.githubusercontent.com/64070836/140497806-bbfd2763-1c43-43f0-b404-de0696bc1e73.jpg) | ![test](https://user-images.githubusercontent.com/64070836/140498913-324942e3-5aec-4c34-96cc-f63d9328d436.jpg) |

By spending time on the issues of the Sharp project, I success to improve the result with this code:
```js
await sharp(imageContent, {density: 72}).withMetadata({ icc: "cmyk" }).toBuffer();
```
and the result have this characteristics:
- channels:4
- chromaSubsampling:'4:4:4:4'
- density:120
- space:'cmyk'
- size: 1943204

| Original Image  | Sharp Output (2) |
| -------------------- | ----------------------- |
| ![original-image](https://user-images.githubusercontent.com/64070836/140497806-bbfd2763-1c43-43f0-b404-de0696bc1e73.jpg) | ![test](https://user-images.githubusercontent.com/64070836/140499781-56cf466a-4edc-454a-9d8d-1679918ec4ca.jpg) |

The colors are better and start to be acceptable but we still see a difference. Unfortunately the size has been multiplied by 4 compared to the source image. We can also see that the density is not respect and the chromaSubsampling are set to '4:4:4:4' instead of  '4:2:0:4'. I think that these two parameters make the size of the image bigger.

But if we set the `chromaSubsampling` we get this error:
```js
await sharp(imageContent, { density: 72 }).withMetadata({ icc: "cmyk" }).jpeg({ chromaSubsampling: "4:2:0:2" }).toBuffer();
```
> Expected one of: 4:2:0, 4:4:4 for chromaSubsampling but received 4:2:0:4 of type string

I also tried `pipelineColorspace` and `toColorspace` but it did not improve the result.

So my question is: how can I keep colors and size with Sharp on this CMYK source image?

I hope you have all the information you need and thank you very much @lovell to create and support this project!

**Original source image**: https://s3.eu-west-1.amazonaws.com/test.galaxy-distribution.tech/image_with_cmyk_colorspace.jpg

**Sharp version:** 0.29.2
**Platform:** Linux x64
**NPM:** 7.24.2
**Node.js:** 14.18.1

**Comment by lovell** [comment]
The sample CMYK input image appears to use chroma subsampling on the cyan and key channels, which I think is invalid according to the JPEG spec, but the image can still be loaded. When saving an image as CMYK, the image will always correctly have chroma subsampling disabled, which would account for an increase in file size.

The world of CMYK has a wide range of colour profiles for all manner of devices and my best guess would be that the input profile in the sample image is very different to sharp/libvips' built-in "cmyk" profile you're using for the output, so colours will appear differently. If you'd like the same profile on the output, you'll need to find/extract it as a file to pass to `withMetadata`.

What is the target for the output images? Is CMYK required?

**Comment by bruno-xo7** [comment]
Hello @lovell,

Thank you for this beginning of answer. The goal is to allow an user to upload an image and use it for the web (via transformations done by Sharp). My target for the output images is to respect the colors and make it light for the web, I have no obligation to keep the color space CMYK. But SRGB doesn't give good results on colors and also I can't ask an user to give me his image profil.

Do you think this is something that can be done for this kind of image? otherwise I could forbid this type of file at the upload step.

**Comment by lovell** [comment]
If the target is a web browser then I would avoid CMYK entirely as support for this varies wildly. Using sRGB currently still provides the most consistent experience on the web.

Looking again at the input image, I notice there is no embedded ICC profile. CMYK is a colour model rather than a colour space, so without a profile any software that decodes it will interpret the colours differently. You either need to find out what profile was *intended* to be used with this particular image in order to be able to convert it, or try various CMYK profiles until you find one that subjectively matches your expectations.

(I suspect the colour representation of this image in most web browsers is too dark, and the default CMYK profile used by sharp/libvips and therefore the sRGB output may be closer to what was intended.)

**Comment by bruno-xo7** [comment]
Thank you for your time
