### ISSUE TITLE
sharp caching metadata

### ISSUE THREAD

**Issue by gjbaxter** [lovell/sharp#2965]
This was a weird one.  I'm creating a sharp on a local jpg file :

let manipulator = sharp(localFilePath);

We then pull the metadata and determine if the image  is rotated.  If it is we have sharp rotate the image and we then save the rotated image back out OVERWRITING THE ORIGINAL.  This is the key point.

We then create a NEW sharp (or so we think) using the same file path since the file on disk has changed:

manipulator = sharp(localFilePath);

However, this new sharp still returns the old metadata.  If we try to scale the image.. it's all cached somehow and we get rotated versions of the image.  Maybe this is intentional but I couldn't find in the documentation that specified this behavior.

If we instead save the rotated image out to a new file and then create a new sharp, it all works perfectly.

**Comment by lovell** [comment]
If you're using mutable files, please switch off libvips cache via `sharp.cache(false)`

https://sharp.pixelplumbing.com/api-utility#cache

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
