### ISSUE TITLE
Electron app with Sharp yields [Error: VipsOperation: class "heifsave" not found] at runtime on Linux 

### ISSUE THREAD

**Issue by zluo01** [lovell/sharp#2966]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)? Yes

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime? Yes

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?  Yes. sharp@0.29.2

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag? N/A

If you are using npm v7, does the user running `npm install` own the directory it is run in? yes

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag? N/A

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

[out.txt](https://github.com/lovell/sharp/files/7489996/out.txt)

What is the output of running `npx envinfo --binaries --system`?

```
  System:
    OS: Linux 5.14 Fedora Linux 35 (KDE Plasma)
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 9.63 GB / 62.73 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    npm: 7.15.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
```

## Problem
I try to add sharp to my electron project and use it only in the main process. I am using [Nextron](https://github.com/saltyshiomix/nextron) which use electron-builder in background. 

Everything works properly when running in dev mode. But when I build the program which use electron-builder internally. It yields following error.

When I put sharp as a dev dependency, it will yeild error reports in #2716 during runtime which make sense as it is mark as dev. Then. when I make it as dependency, in the runtime, it will yeilds ` [Error: VipsOperation: class "heifsave" not found]` when I am calling `await sharpInstance.resize({ height: 360 }).avif().toFile(imageCachePath);`.

 I add the line to webpack configs as mentioned [here](https://sharp.pixelplumbing.com/install#webpack). I have also try `electron-rebuild` but does not fix my problem. 

I have also run ` electron-builder install-app-deps` to rebuild the native dependencies which print following logs.
```
  • rebuilding native dependencies  dependencies=sharp@0.29.2 platform=linux arch=x64
  • install prebuilt binary  name=sharp version=0.29.2 platform=linux arch=x64 napi=
```

I wonder what the cause is in this case ? Thank you very much.

**Comment by zluo01** [comment]
I also try out on my mac machine and it works properly at runtime. It seems like it is only happens on linux. I do not have a window machine to test on so not sure about windows.
```
  System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.05 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.2 - ~/.nvm/versions/node/v16.4.2/bin/node
    npm: 7.18.1 - ~/.nvm/versions/node/v16.4.2/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman

```

**Comment by lovell** [comment]
Could there be an older version of sharp in the dependency tree? Could there be an older version of libvips installed globally? What's the output of running the following?
```sh
npm ls sharp
npm ls -g sharp
```

**Comment by zluo01** [comment]
> Could there be an older version of sharp in the dependency tree? Could there be an older version of libvips installed globally? What's the output of running the following?
> 
> ```shell
> npm ls sharp
> npm ls -g sharp
> ```

Only one version of sharp 0.29.2 print out for both commands.

 I previously install libvips from dnf with version 8.11.3 so I removed it and deleted the node_module and ran `npm i` , built the program. It then yeilds following error also mentioned in #2305 but I do not build libvips myself but use the one come with npm install.
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: 
Something went wrong installing the "sharp" module

libvips-cpp.so.42: cannot open shared object file: No such file or directory
```

On my mac, I do not have libvips installed separately. 

Thanks.

**Comment by lovell** [comment]
> I previously install libvips from dnf with version 8.11.3 so I removed it

It looks like this might still be partially-installed, so please check this is completely removed, then reinstall sharp via `npm` (avoiding `electron-builder` if possible).

**Comment by zluo01** [comment]
> > I previously install libvips from dnf with version 8.11.3 so I removed it
> 
> It looks like this might still be partially-installed, so please check this is completely removed, then reinstall sharp via `npm` (avoiding `electron-builder` if possible).

I do not think that is the case. I also encounter the same issue on a brand new linux vm. I have also tried on windows and it works properly. Seems like the problem only exists on linux machine.
![image](https://user-images.githubusercontent.com/12102011/140626310-78657868-91ed-4624-a6c6-4a9681927d8e.png)

**Comment by lovell** [comment]
Please make sure you're using the latest version of `electron-builder` as I believe are quite a few bugs relating to native modules that use Node-API (such as sharp) that have recently been fixed.

Some of the Electron tooling, and I think `electron-builder` falls into this category, ignores the `install` script that sharp defines and instead assumes all native modules only require `node-gyp`. There's a good summary of this at https://github.com/lovell/sharp/issues/2764#issuecomment-871716837

You might get better results by running `rm -rf node_modules/sharp && npm install sharp` after `electron-builder` has run.

**Comment by zluo01** [comment]
It seems like electron-builder ignore linux. For who comes with this similar issues the following is the solution.
[#6200 (comment)](https://github.com/electron-userland/electron-builder/issues/6200#issuecomment-907830847)
