### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by 109km** [lovell/sharp#297]
> sharp@0.11.4 install /Users/xinhengs/Desktop/WebDevs/relax/node_modules/sharp
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: socket hang up
gyp ERR! stack     at TLSSocket.onHangUp (_tls_wrap.js:1076:19)
gyp ERR! stack     at TLSSocket.g (events.js:260:16)
gyp ERR! stack     at emitNone (events.js:72:20)
gyp ERR! stack     at TLSSocket.emit (events.js:166:7)
gyp ERR! stack     at endReadableNT (_stream_readable.js:905:12)
gyp ERR! stack     at doNTCallback2 (node.js:450:9)
gyp ERR! stack     at process._tickCallback (node.js:364:17)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xinhengs/Desktop/WebDevs/relax/node_modules/sharp
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN EPEERINVALID mongodb-core@1.2.21 requires a peer of kerberos@~0.0 but none was installed.
npm WARN EPEERINVALID mongodb-core@1.2.21 requires a peer of kerberos@~0.0 but none was installed.
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sharp" "--unsafe-perm"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.11.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.11.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xinhengs/Desktop/WebDevs/relax/npm-debug.log

**Comment by lovell** [comment]
Hello, the "Error: socket hang up" and "TLSSocket" bits suggest this is a (temporary?) HTTPS networking problem.

**Comment by OwaysisApp** [comment]
-I have the same:

 npm WARN EPEERINVALID mongodb-core@1.2.21 requires a peer of kerberos@~0.0 but none was installed.

**Comment by lovell** [comment]
@OwaysisApp That's an warning unrelated to sharp - https://github.com/christkv/mongodb-core/commit/a18e2490d2e25ef3c602acefab51dba1ccb2d53c suggests you can ignore it.

**Comment by OwaysisApp** [comment]
THANK YOU^^^

**Comment by 109km** [comment]
I cloned the code of sharp to my directory, then run`npm install`, I found the problem is caused by another module : `bufferutil`.
So you can close this one. Thanks very much.

**Comment by lovell** [comment]
Thanks for the update, glad to hear you got it working. `bufferutil` is a "devDependency" used by a test (as it has previously caused problems when used with `sharp`).
