### ISSUE TITLE
I am not able to install sharp library in aws ec2 arm64 

### ISSUE THREAD

**Issue by abdullbasitmemon** [lovell/sharp#2970]
I am following documentation https://sharp.pixelplumbing.com/install and not able to install sharp library in aws ec2 arm64. I  have tried multiple commands like `npm install --unsafe-perm --platform=linux --arch=arm64  sharp` but getting same error every time: 
`sharp: Installation error: Use with glibc 2.26 requires manual installation of libvips >= 8.11.3`
`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.29.2 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.29.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

Instance: Linux aarch64 GNU/Linux

**Comment by lovell** [comment]
Please see #2837 and https://github.com/lovell/sharp/issues/2875#issuecomment-940227974

**Comment by lovell** [comment]
Tracking at https://github.com/lovell/sharp/issues/2938
