### ISSUE TITLE
Sharp get crash when run on docker with node:12-alpine

### ISSUE THREAD

**Issue by sonnguyen16694** [lovell/sharp#2973]
I'm using the sharp version 0.26.3 to resize my images, when I run my application on local (using Windows 11), it working fine but when I deploy the code to server using docker with node:12-alpine image, my application crash when sharp resize uploaded image without any exception.
I was tried to set cache to false or set cache to  sharp.cache({ memory: 0, files: 0, items: 0 }) but nothing helpful.
My size image code
 const image = await sharp(`${destPath}/${fileName}`)
              .resize({ height })
              .toFormat('jpeg')
              .toFile(localStoragePath);

**Comment by lovell** [comment]
This is probably #2570, please can you upgrade to the latest version.

**Comment by sonnguyen16694** [comment]
> This is probably #2570, please can you upgrade to the latest version.

after after the latest version, it working correctly now. Thanks
