### ISSUE TITLE
How do I stitch multiple images to one image?

### ISSUE THREAD

**Issue by developomp** [lovell/sharp#2974]
**What are you trying to achieve?**

I have an array of small image buffers that I want to stitch together to create one, large image.
I searched for a solution in the [documentation](https://sharp.pixelplumbing.com/) and in the [issues](https://github.com/lovell/sharp/issues?q=) but it's not apparent how to achieve what I want.

**Have you searched for similar questions?**

[This](https://github.com/lovell/sharp/issues/405#issuecomment-208033263) seems to be closest to what I want but the function `overlayWith` is nowhere to be found.

**Are you able to provide a minimal, standalone code sample that demonstrates this question?**

No unfortunately :(

**Are you able to provide a sample image that helps explain the question?**

Not quite an image but I hope this enough for demonstration purpose:

```typescript
const SmallImages = [Pen, Pineapple, Apple, Pen]

const result = magicFunction(SmallImages)

console.log(result)
/*
Pen
Pineapple
Apple
Pen
*/
```

**Comment by lovell** [comment]
Hi, did you see https://sharp.pixelplumbing.com/api-composite ?

You may also be interested in the future possible enhancement at https://github.com/lovell/sharp/issues/1580

**Comment by developomp** [comment]
I take a look at https://sharp.pixelplumbing.com/api-composite again and `images[].top` seems useful.
