### ISSUE TITLE
Composite not working with Serverless

### ISSUE THREAD

**Issue by GuiFerrari** [lovell/sharp#2977]
_What are you trying to achieve?_

I have a code to resize an image with the background blurred. This code works great in tests and on HTTP servers, however, when uploading to AWS Lambda, the code doesn't work.
If I comment out the line, everything works perfectly: 

`.composite([{ input: foregroundBlur }])`

_Have you searched for similar questions?_

Yes, but apparently no one has tested the composite in serverless.

_Are you able to provide a minimal, standalone code sample that demonstrates this question?_

```js
module.exports.handle = async ({ Records: records }, context) => {
  try {
    await Promise.all(
      records.map(async record => {
        const { key } = record.s3.object;

        const image = await S3.getObject({
          Bucket: process.env.bucket,
          Key: key
        }).promise();

        const optimized = await sharp(image.Body)
          .resize(1000, 1000, { fit: "inside", withoutEnlargement: true })
          .toFormat("jpeg", { progressive: true, quality: 50 })
          .toBuffer();

        const foregroundBlur = sharp(image.Body)
          .resize(1000, 1000, { fit: 'cover' }).blur(15, { quality: 85 });

        console.log('Works great');

        const testImage = await sharp(optimized)
          .jpeg({ quality: 80, progressive: true })
          .composite([{ input: foregroundBlur }])
          .sharpen()
          .toBuffer();

        console.log('Works great again?');

        await S3.putObject({
          Body: testImage,
          Bucket: process.env.bucket,
          ContentType: "image/jpeg",
          Key: `compressed/${basename(key, extname(key))}.jpg`
        }).promise();
      })
    );

    return {
      statusCode: 301,
      body: { ok: true }
    };
  } catch (err) {
    return err;
  }
};
```

_Are you able to provide a sample image that helps explain the question?_

AWS CloudWatch logs:

![CloudWatch logs](https://i.imgur.com/llK1xCn.png)

Note that the second log does not appear and the code did not fall into the catch.

**Comment by lovell** [comment]
It looks like `foregroundBlur` is a sharp instance rather than an image. Try something like the following change (untested):

```diff
-       const foregroundBlur = sharp(image.Body)
-          .resize(1000, 1000, { fit: 'cover' }).blur(15, { quality: 85 });
+        const foregroundBlur = await sharp(image.Body)
+          .resize(1000, 1000, { fit: 'cover' }).blur(15, { quality: 85 }).toBuffer();
```

**Comment by GuiFerrari** [comment]
> It looks like `foregroundBlur` is a sharp instance rather than an image. Try something like the following change (untested):
> 
> ```diff
> -       const foregroundBlur = sharp(image.Body)
> -          .resize(1000, 1000, { fit: 'cover' }).blur(15, { quality: 85 });
> +        const foregroundBlur = await sharp(image.Body)
> +          .resize(1000, 1000, { fit: 'cover' }).blur(15, { quality: 85 }).toBuffer();
> ```

Same problem, but now the console.log that was below that line doesn't appear anymore either.  `console.log('Works great');`

**Comment by lovell** [comment]
It looks like your `handle()` function can return an `Error` whereas, if you want Lambda to handle it, you should `throw` an `Error`. Perhaps remove the try/catch block entirely.

This is more a question about the API provided by AWS and is unrelated to sharp.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
