### ISSUE TITLE
Emit 'metadata' event

### ISSUE THREAD

**Issue by oaleynik** [lovell/sharp#298]
Hi there!

I'm wondering - what steps are required to supercharge `sharp` with the formats from here http://www.imagemagick.org/script/formats.php? For now I'm interested in reading, not writing. Ideally I would like to have streamed approach to get input stream to the file, pipe it into sharp, read just enough bytes to identify the file (get metadata) and emit something like `metadata` event. Is this possible now with `sharp`? Is it possible in theory with `libvips`?

Thanks in advance!

**Comment by lovell** [comment]
Hi Oleg, assuming you're using sharp with libvips that has been compiled with *magick support, this should mostly work right now.

Sadly it's not as efficient as it could be. We don't know how big the metadata will be (>1MB header is not entirely unusual) so, as a result, the whole stream is buffered first.

I really like your idea of emitting a `metadata` event when "enough" data has been streamed in. That should be possible by testing the metadata with each chunk that arrives (with thresholds around minimum size and number of attempts).

**Comment by oaleynik** [comment]
@lovell the problem of unknown size of the image header is exactly what I'm trying to solve. While experimenting I ended up with the 512kb header. This works for me in 99%. However, at the moment I use graphicsmagick to read this header and fetch metadata from there. As this logic stays inside of the route of web server, under high requests rate I'm hammering server with hundreds/thousands of GM processes (nightmare). This is why I was wondering about an ability to read additional file formats and extract metadata via `sharp` in more "streamed" manner. 

Another use case where it can be useful is the fraction of image metadata - image dimensions. `image-size` (https://www.npmjs.com/package/image-size) package uses just 128kb of image header to get dimensions of the most popular image formats by testing bytes from the incoming buffer at the fixed offset (defined by standards) and works pretty well in most cases. However, it can have hard times with the "non standard" images (for instance, it has troubles with the images exported from the Lightroom).
I think we need less bytes to identify just image dimensions instead of whole set of image metadata.

I'm not very familiar with the all existing image formats, but I think there should be some kind of the common byte sequence indicating the end of the image header. 

I'm glad you liked my idea. I think it will be useful :)

**Comment by lovell** [comment]
Note to self: doing this with (or shortly after) #236 makes most sense.

**Comment by puzrin** [comment]
There are no way to get all metadata with guarantee, without reading full file. There are many block types and their sequence can be random. For example, comment can go both before and after image. Metadata structure is also not very stable and can make api too complex.

I'd suggest first to investigate 2 things we did four our project:

- https://github.com/nodeca/probe-image-size - true streaming image size extractor.
- https://github.com/nodeca/nodeca.users/blob/master/lib/filter_jpeg.js - streaming jpeg metadata shrinker (remove big fields, thumbnails + allow to add comment).

Personally, i would not miх this functionality with sharp. Those are almost not related technically.

**Comment by lovell** [comment]
@puzrin Sorry I missed your comment until now, thank you for your sage advice. I think there's still value in sharp emitting the `metadata` event when the entire of the input is available, but I agree that attempting to do so with partial input is a fool's errand!

**Comment by lovell** [comment]
Closing as I think https://github.com/nodeca/probe-image-size already provides what is needed here and its a bit of an edge case for sharp, which is more about processing than metadata.

**Comment by scottw-finao** [comment]
ok, but how can you get the image width/height while passing a string through to a sharp resize? I see multiple linked tickets, but can't seem to find an example.
