### ISSUE TITLE
How can I do with error  that  - Input file has corrupt header: pngload: reached chunk/cache limits

### ISSUE THREAD

**Issue by lix059** [lovell/sharp#2984]
What are you trying to achieve?
I was going to get a thumbnail from a png which is 254 M large, which occured that error.

Have you searched for similar questions?
yes, but I can not find out  how to fixed it.

Are you able to provide a minimal, standalone code sample that demonstrates this question?
that is my process code 
![image](https://user-images.githubusercontent.com/7779883/142755434-bd13195e-878a-4111-b21e-96ae1e7d7de9.png)

Are you able to provide a sample image that helps explain the question?
that is error tip
![image](https://user-images.githubusercontent.com/7779883/142755237-f95ab207-4e81-4e79-98fb-8c4a296bbdbf.png)

**Comment by lovell** [comment]
I suspect this image trips the `SPNG_CHUNK_COUNT_LIMIT` of 1000, which is a safety feature of libspng.

https://github.com/randy408/libspng/blob/master/docs/decode.md#memory-usage

To allow an optional increase in this value, we'd need to expose control over this in libvips first.

Are you able to provide a sample image that fails in this manner?

**Comment by lix059** [comment]
The sample image is large. Can you leave an email address?  I will post to you.

**Comment by randy408** [comment]
> I suspect this image trips the `SPNG_CHUNK_COUNT_LIMIT` of 1000, which is a safety feature of libspng.

Hopefully it's not that, I'll raise the default value if that's the case. Either way I'll be adding a new error code to differentiate from the other two limits.

**Comment by lovell** [comment]
@lix059 Thank you, if it's a really big file it might be worth using a file hosting service rather than email e.g. something like Dropbox or Google Drive.

https://github.com/lovell/sharp/blob/1ff84b20b7d9b351786fb06899255cea59aa123c/package.json#L5

**Comment by lix059** [comment]
> 

@lovell   I  posted the sample image download url to  npm@lovell.info  email. Thank you.

![image](https://user-images.githubusercontent.com/7779883/143029244-a07f9e90-6440-4b3f-8a0c-5e8c2a12edcd.png)

**Comment by lovell** [comment]
Thanks for the image, it has 143 chunks, two of which are text chunks that consume ~260MB when decompressed.

```sh
$ pngchunks preview221.png | grep "Chunk:" | wc -l
143
$ pngchunks preview221.png | grep zTXt
Chunk: Data Length 131093001 (max 2147483647), Type 1951945850 [zTXt]
Chunk: Data Length 131085202 (max 2147483647), Type 1951945850 [zTXt]
```

As Randy has pointed out, there's a new `unlimited` flag in libvips that we need to expose in sharp, which should then allow this image to be processed (this will be opt-in, as the safety features are there for a reason.)

**Comment by lix059** [comment]
@lovell  Thanks.

**Comment by lovell** [comment]
v0.30.0 now available with this feature.
