### ISSUE TITLE
Get the converted picture size for a long time

### ISSUE THREAD

**Issue by victorykong** [lovell/sharp#2986]
version: ^0.29.3

![image](https://user-images.githubusercontent.com/50655436/142870373-23dc243e-ff6f-4d63-a785-1804eee979cf.png)

expected behaviour:
1. get the converted picture size. 
2. Don't modify anything in the original picture, just convert the picture into webp.

-The picture below is zoomed.
![image](https://user-images.githubusercontent.com/50655436/142870546-5b019cd9-a944-4bbb-9555-719dc485bc70.png)
![image](https://user-images.githubusercontent.com/50655436/142870554-7a208938-71fe-437d-947f-9fbf8211f3f1.png)

What is the output of running `npx envinfo --binaries --system`?

**Comment by victorykong** [comment]
`npx envinfo --binaries --system`

`{ config: 'development' }`

**Comment by lovell** [comment]
From what I can tell, you need to start to pipe data into the `sharp` instance *before* you attempt to `await` any output.

Please can you paste a complete, standalone code sample rather than editor screenshots, and I'll be able to help further.

**Comment by victorykong** [comment]
@lovell https://github.com/victorykong/sharp-webp

**Comment by lovell** [comment]
Thanks, I see some commented out code that will hang if uncommented (due to the reason I stated above). What's the problem you're actually trying to solve? Are you trying to get the size of the output?

The `ReadableStream` returned by `img.pipe(webp)` will emit an `info` event, perhaps that might help?
```js
body.on('info', (info) => { ... });
```

**Comment by victorykong** [comment]
It doesn't seem to solve my problem. I want to get the picture size after webp conversion through metadata, just like the corresponding document in this link. 

https://github.com/lovell/sharp/issues/761#issuecomment-292807931

**Comment by lovell** [comment]
If I make the following change:
```diff
--- a/index.js
+++ b/index.js
@@ -24,6 +24,7 @@ app.use(async (ctx, next) => {
       const body = img.pipe(webp);
       ctx.set("Content-Type", "image/webp");
       ctx.body = body;
+      body.on('info', console.log)
       return;
     }
```
...then `npm run dev` then access `http://localhost:3000/test.png` I see:
```
{
  format: 'webp',
  width: 468,
  height: 468,
  channels: 3,
  premultiplied: false,
  size: 84806
}
```
