### ISSUE TITLE
Error : munmap_chunk(): invalid pointer, Node.js 13 (EOL)

### ISSUE THREAD

**Issue by stanly-johnson** [lovell/sharp#2988]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
Yes, `0.29.3`

What are the steps to reproduce?
Some large images trigger `munmap_chunk(): invalid pointer` error and kills the node process
 
What is the expected behaviour?
Should generate compress version of image

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
```
    return sharp(fileBuffer)
      .resize(height, width)
      .toBuffer()
      .then((data: any) => {
        return data;
      })
      .catch((err: any) => log.info(err, 'Failed to compress image!'));
```

Are you able to provide a sample image that helps explain the problem?
![image](https://user-images.githubusercontent.com/6850913/143022625-e60966ea-4fe0-4b44-972e-df002ec7fc14.png)

**Comment by lovell** [comment]
Are you using ARM64, and if so, is this only with PNG images?

**Comment by stanly-johnson** [comment]
This happens on an ec2 running x86_64. Happens for some png/jpg images. Although this issue does not happen with the same code running on my local (m1 BigSur)

**Comment by lovell** [comment]
Thanks, are you using the prebuilt binaries provided by sharp?

What is the output of running `npx envinfo --binaries --system` on the system that fails?

Are you able to create a standalone repo, with code and images, that allows someone else to reliably recreate this? If not, are you able to get a backtrace of the crash using a tool such as `gdb`?

**Comment by stanly-johnson** [comment]
Installed by `npm i sharp`

Output of `npx envinfo --binaries --system`
```
  System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (1) x64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
    Memory: 96.32 MB / 973.74 MB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 13.14.0 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm
```

**Comment by lovell** [comment]
Node.js 13 reached end-of-life on the 1st June 2020, please upgrade.

If you're still having problems after upgrading to a supported version of Node.js, please provide a backtrace of the crash.
