### ISSUE TITLE
Image bigger (in bits) after sharp operation than the original

### ISSUE THREAD

**Issue by parweb** [lovell/sharp#2989]
After using sharp like this with a jpg

```js
await sharp(input).trim().toFile(output);
```

or 

```js
await sharp(input).resize({ width: 1000 }).toFile(output);
```

the output is bigger than the original picture
original: 300 Kb
trimed: 7 Mb
resize: 7 Mb

Any advices ?

**Comment by lovell** [comment]
Please can you provide the input image.

**Comment by parweb** [comment]
http://apps-int.bca.fr/doc-num/api/v1/documents/download/PHOTOS/2021328/PHO_211124_35029728_1_135049727.jpg

**Comment by parweb** [comment]
and sharp version

`"sharp": "0.29.3"`

**Comment by lovell** [comment]
Thanks, this input image is saved at a very low quality:
```sh
$ identify -verbose PHO_211124_35029728_1_135049727.jpg | grep Quality
  JPEG-Quality: 13
```
If you'd like a similar low quality for the output, you can set this via:
```js
.jpeg({ quality: 13 })
```
https://sharp.pixelplumbing.com/api-output#jpeg

Finally, to answer your next question before you've asked it, please see #908

**Comment by parweb** [comment]
nice anticipation 👍
