### ISSUE TITLE
Switch to libvips C++ bindings

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#299]
The new `vips8` [C++ bindings](http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/using-from-cpp.html) now expose all of the libvips' features this module uses so we can migrate away from the C bindings.

This will simplify the code and ease memory management.

Other benefits:

* [x] Detach the alpha channel before applying a gamma correction - see 36ac882 - fixed in 4dfbf89

**Comment by binarykitchen** [comment]
yeah, that would be awesome to migrate away from the C bindings

**Comment by lovell** [comment]
Commit 12d66ee on the `mind` branch is the first pass at this. It removed around 450 lines of code.

**Comment by lovell** [comment]
Lots of warnings and linker errors on Windows, sigh. https://ci.appveyor.com/project/lovell/sharp/build/304/job/rct60twmmp2gds1a

**Comment by lovell** [comment]
Thanks to the name mangling car crash that is cross-linking C++ libraries on Windows, we'll need to either include and compile libvips C++ wrapper from source or build libvips-cpp.dll via MSVC instead of mingw-w64.

**Comment by lovell** [comment]
The vips8 C++ bindings are now being built as a DLL on Windows machines at `npm install` time. Looking much happier as a result. https://ci.appveyor.com/project/lovell/sharp/build/322

**Comment by lovell** [comment]
v0.13.0 now available.

**Comment by binarykitchen** [comment]
cool, well done!
