### ISSUE TITLE
Explanation of error handling

### ISSUE THREAD

**Issue by AndrewJDR** [lovell/sharp#2990]
Hi,

I recently observed that if I have code like the following, if an error occurs during the trim operation (e.g. "Unexpected error while trimming. Try to lower the tolerance"), the try/catch will not handle it, but rather the exception appears to be thrown further down, during the `await trimmedImage.toFile()`.  Perhaps using `trimmedImage = await sharp("file.png").trim().clone()` would be better, and cause the error to be thrown within then try/catch as I'd prefer in this case? Is there some further explanation of these particular error handling behaviors when in the documentation or elsewhere? I'd just like to make sure I'm using sharp correctly. Thanks!

```
let trimmedImage;

try
{
  trimmedImage = await sharp("file.png").trim();
}
catch (e) {}

await trimmedImage.toFile("output.png");
```

**Comment by lovell** [comment]
Hi, the input starts to be decompressed/decoded only when the output is ready, which means you'll definitely want error handling around the response of the `toFile()` call.

The `trim()` function call returns the sharp instance, and doesn't return a Promise so there's no need to `await`. It can throw an Error should any parameters passed to it be considered invalid, as documented at https://sharp.pixelplumbing.com/api-resize#trim

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
