### ISSUE TITLE
Trying to fix this sharp issue

### ISSUE THREAD

**Issue by talmax1124** [lovell/sharp#2991]
Hello! I don't know what is happening here. When running npm start on my repo, it is giving me an error:

Eleventy fatal error: (more in DEBUG output)
> Error in your Eleventy config file '/Users/carlosdiazplaza/11ty-netlifycms-templateforclients/.eleventy.js'.

`EleventyConfigError` was thrown
> Something went wrong installing the "sharp" module

dlopen(/Users/carlosdiazplaza/11ty-netlifycms-templateforclients/node_modules/eleventy-plugin-lazyimages/node_modules/sharp/build/Release/sharp.node, 0x0001): symbol not found in flat namespace '__ZTVN4vips7VOptionE'

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

`Error` was thrown:
    Error: 
    Something went wrong installing the "sharp" module
    
    dlopen(/Users/carlosdiazplaza/11ty-netlifycms-templateforclients/node_modules/eleventy-plugin-lazyimages/node_modules/sharp/build/Release/sharp.node, 0x0001): symbol not found in flat namespace '__ZTVN4vips7VOptionE'
    
    - Remove the "node_modules/sharp" directory then run
      "npm install --ignore-scripts=false --verbose" and look for errors
    - Consult the installation documentation at https://sharp.pixelplumbing.com/install
    - Search for this error at https://github.com/lovell/sharp/issues
    
        at Object.<anonymous> (/Users/carlosdiazplaza/11ty-netlifycms-templateforclients/node_modules/eleventy-plugin-lazyimages/node_modules/sharp/lib/constructor.js:34:9)
        at Module._compile (node:internal/modules/cjs/loader:1101:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Module.require (node:internal/modules/cjs/loader:1005:19)
        at require (node:internal/modules/cjs/helpers:102:18)
        at Object.<anonymous> (/Users/carlosdiazplaza/11ty-netlifycms-templateforclients/node_modules/eleventy-plugin-lazyimages/node_modules/sharp/lib/index.js:3:15)
        at Module._compile (node:internal/modules/cjs/loader:1101:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
carlosdiazplaza@Carloss-MacBook-Pro 11ty-netlifycms-templateforclients % 

I don't know what is happening. Anyone can help me out? Thanks! Here is my repo URL: https://github.com/talmax1124/11ty-netlifycms-templateforclients

**Comment by lovell** [comment]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

What is the complete output of running `npm install --verbose sharp`? 

What is the output of running `npx envinfo --binaries --system`?

**Comment by talmax1124** [comment]
<img width="822" alt="Screen Shot 2021-11-28 at 5 11 03 AM" src="https://user-images.githubusercontent.com/61528430/143763770-afcc3715-d25c-4b6e-9a24-8a2e45e30ef9.png">
[Log.docx](https://github.com/lovell/sharp/files/7613224/Log.docx)


Here is the output. 



@lovell

**Comment by talmax1124** [comment]
<img width="866" alt="Screen Shot 2021-11-28 at 5 13 31 AM" src="https://user-images.githubusercontent.com/61528430/143763832-de90d030-1c86-4b59-b9a4-bf10162c635a.png">

**Comment by lovell** [comment]
It looks like `eleventy-plugin-lazyimages` relies on an older version of sharp that does not support Apple M1.

https://github.com/liamfiddler/eleventy-plugin-lazyimages/blob/08c0624d7aa95f71ff3b4597ce84c3f67aeca759/package.json#L30

https://sharp.pixelplumbing.com/install#apple-m1

**Comment by talmax1124** [comment]
Ok, thanks! Let me try it now!

**Comment by talmax1124** [comment]
Hello! This worked! Thanks!

**Comment by lovell** [comment]
Great, perhaps you could submit a pull request to the https://github.com/liamfiddler/eleventy-plugin-lazyimages repo that upgrades sharp and helps prevent others running into the same problem.

**Comment by talmax1124** [comment]
Well, i just removed the plugin.

**Comment by talmax1124** [comment]
What version specifically supports the M1? @lovell

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/install#apple-m1

If you're upgrading, please upgrade to the latest.
