### ISSUE TITLE
Noticeable drop in resolution of resized images

### ISSUE THREAD

**Issue by CodeWithOz** [lovell/sharp#2993]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
Yes

What are the steps to reproduce?
Resize an image with the following config: 
```js
sharp
        .rotate()
        .resize(320, null, {
            fit: sharp.fit.inside,
        })
        webp({ lossless: true, quality: 100 })
        .toBuffer();
```

What is the expected behaviour?
The output image has a significantly reduced size but without a noticeable drop in quality

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
No

Are you able to provide a sample image that helps explain the problem?
Yes, this is it:
![annotated (4)](https://user-images.githubusercontent.com/28525986/143871383-d44ad77c-8b3b-4e96-8f3c-691389701705.jpeg)

What is the output of running `npx envinfo --binaries --system`?
I'll need a new deployment of my AWS lambda to get this info so I will update with this info when I get it.

**Comment by lovell** [comment]
Please can you provide the input image.

**Comment by CodeWithOz** [comment]
That image was from long ago so I couldn't find the originals, but these are 2 new ones from today (using WeTransfer so it's the raw files):
- before: [https://we.tl/t-8NtDVr23TF](https://we.tl/t-8NtDVr23TF)
- after: [https://we.tl/t-JEJ9I2dovr]

I couldn't get the envinfo because the lambda prohibits that command from running.

**Comment by lovell** [comment]
Thanks, the input is a 4000x3000 (12MP) JPEG, with EXIF orientation 6, originally saved at ~92% quality with chroma subsampling.

The output is a 320x427 (0.1MP) WebP saved using lossless compression, with a .jpeg file extension.

Here is the output WebP image losslessly re-converted to PNG:

![](https://user-images.githubusercontent.com/210965/144205290-62003a90-c9ec-4766-882f-01b9d5d23a9e.png)

Given the act of resizing reduces the number of pixels in the output to ~12% of those of the input, it appears pretty much as I would expect it to.

Please can you provide more information about your expectations for the output image given the same input image.

**Comment by lovell** [comment]
@CodeWithOz I hope this information helped. Please feel free to re-open with more details of your expectations if further assistance is required.
