### ISSUE TITLE
Sharp not installing on mbp m1

### ISSUE THREAD

**Issue by salish-gorinsys** [lovell/sharp#2994]
I have installed VIPs and GCC but sharp is not installing, help is appreciated.
here is the error log

npm ERR! code 1
npm ERR! path /Users/salishkumar/Desktop/Desktop/freelannce/gorin systems/sub-backend/node_modules/strapi-plugin-upload/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Using cached /Users/salishkumar/.npm/_libvips/libvips-8.10.6-darwin-arm64v8.tar.br
npm ERR!   CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR! prebuild-install WARN install No prebuilt binaries found (target=3 runtime=napi arch=arm64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.11.1 | darwin | arm64
npm ERR! (node:6132) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /usr/bin/python2
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/salishkumar/Desktop/Desktop/freelannce/gorin systems/sub-backend/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/salishkumar/Desktop/Desktop/freelannce/gorin systems/sub-backend/node_modules/strapi-plugin-upload/node_modules/sharp/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/salishkumar/Desktop/Desktop/freelannce/gorin systems/sub-backend/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/salishkumar/.node-gyp/16.11.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/salishkumar/.node-gyp/16.11.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/salishkumar/Desktop/Desktop/freelannce/gorin systems/sub-backend/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/salishkumar/.node-gyp/16.11.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/salishkumar/Desktop/Desktop/freelannce/gorin systems/sub-backend/node_modules/strapi-plugin-upload/node_modules/sharp',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "./gyp-mac-tool", line 611, in <module>
npm ERR!     sys.exit(main(sys.argv[1:]))
npm ERR!   File "./gyp-mac-tool", line 28, in main
npm ERR!     exit_code = executor.Dispatch(args)
npm ERR!   File "./gyp-mac-tool", line 43, in Dispatch
npm ERR!     return getattr(self, method)(*args[1:])
npm ERR!   File "./gyp-mac-tool", line 246, in ExecFilterLibtool
npm ERR!     if not libtool_re.match(line) and not libtool_re5.match(line):
npm ERR! TypeError: cannot use a string pattern on a bytes-like object
npm ERR! make: *** [Release/nothing.a] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/salishkumar/Desktop/Desktop/freelannce/gorin systems/sub-backend/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 21.1.0
npm ERR! gyp ERR! command "/Users/salishkumar/.nvm/versions/node/v16.11.1/bin/node" "/Users/salishkumar/Desktop/Desktop/freelannce/gorin systems/sub-backend/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/salishkumar/Desktop/Desktop/freelannce/gorin systems/sub-backend/node_modules/strapi-plugin-upload/node_modules/sharp
npm ERR! gyp ERR! node -v v16.11.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/salishkumar/.npm/_logs/2021-11-29T15_23_05_505Z-debug.log

**Comment by lovell** [comment]
Hi, please upgrade sharp.

https://sharp.pixelplumbing.com/install#apple-m1

**Comment by salish-gorinsys** [comment]
@lovell hi, i am still getting same error while running npm install

here are logs


npm ERR! code 1
npm ERR! path /Users/salishkumar/Desktop/Desktop/freelannce/gorin systems/sub-backend/node_modules/strapi-plugin-upload/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Using cached /Users/salishkumar/.npm/_libvips/libvips-8.10.6-darwin-arm64v8.tar.br
npm ERR! prebuild-install WARN install No prebuilt binaries found (target=3 runtime=napi arch=arm64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.0
npm ERR! gyp info using node@16.11.1 | darwin | arm64
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python You need to install the latest version of Python.
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm ERR! gyp ERR! find Python you can try one of the following options:
npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python For more information consult the documentation at:
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
npm ERR! gyp ERR! stack     at PythonFinder.fail (/Users/salishkumar/.nvm/versions/node/v16.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/Users/salishkumar/.nvm/versions/node/v16.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/Users/salishkumar/.nvm/versions/node/v16.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/Users/salishkumar/.nvm/versions/node/v16.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:404:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! gyp ERR! System Darwin 21.1.0
npm ERR! gyp ERR! command "/Users/salishkumar/.nvm/versions/node/v16.11.1/bin/node" "/Users/salishkumar/.nvm/versions/node/v16.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/salishkumar/Desktop/Desktop/freelannce/gorin systems/sub-backend/node_modules/strapi-plugin-upload/node_modules/sharp
npm ERR! gyp ERR! node -v v16.11.1
npm ERR! gyp ERR! node-gyp -v v8.4.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/salishkumar/.npm/_logs/2021-11-30T14_25_15_099Z-debug.log

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/install#apple-m1

> Prebuilt sharp and libvips binaries are provided for macOS on ARM64 from sharp v0.29.0.

It looks like you are using a version of sharp prior to v0.29.x, please upgrade.

**Comment by salish-gorinsys** [comment]
@lovell  i ran this command "npm install --arch=arm64 --platform=linuxmusl sharp"
but issue is same

**Comment by lovell** [comment]
```
npm install sharp@latest
```

**Comment by salish-gorinsys** [comment]
@lovell still 😩😩

npm ERR! code 1
npm ERR! path /Users/salishkumar/Desktop/Desktop/freelannce/gorin systems/sub-backend/node_modules/strapi-plugin-upload/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Using cached /Users/salishkumar/.npm/_libvips/libvips-8.10.6-darwin-arm64v8.tar.br
npm ERR!   CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR!   TOUCH Release/obj.target/libvips-cpp.stamp
npm ERR!   CXX(target) Release/obj.target/sharp/src/common.o
npm ERR! prebuild-install WARN install No prebuilt binaries found (target=3 runtime=napi arch=arm64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.0
npm ERR! gyp info using node@16.11.1 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.9 found at "/opt/local/bin/python3"
npm ERR! gyp info spawn /opt/local/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/salishkumar/.nvm/versions/node/v16.11.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/salishkumar/Desktop/Desktop/freelannce/gorin systems/sub-backend/node_modules/strapi-plugin-upload/node_modules/sharp/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/salishkumar/.nvm/versions/node/v16.11.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/salishkumar/Library/Caches/node-gyp/16.11.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/salishkumar/Library/Caches/node-gyp/16.11.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/salishkumar/.nvm/versions/node/v16.11.1/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/salishkumar/Library/Caches/node-gyp/16.11.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/salishkumar/Desktop/Desktop/freelannce/gorin systems/sub-backend/node_modules/strapi-plugin-upload/node_modules/sharp',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
npm ERR! clang: error: no such file or directory: 'systems/sub-backend/node_modules/strapi-plugin-upload/node_modules/sharp/vendor/8.10.6/include'
npm ERR! clang: error: no such file or directory: 'systems/sub-backend/node_modules/strapi-plugin-upload/node_modules/sharp/vendor/8.10.6/include/glib-2.0'
npm ERR! clang: error: no such file or directory: 'systems/sub-backend/node_modules/strapi-plugin-upload/node_modules/sharp/vendor/8.10.6/lib/glib-2.0/include'
npm ERR! make: *** [Release/obj.target/sharp/src/common.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/salishkumar/.nvm/versions/node/v16.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 21.1.0
npm ERR! gyp ERR! command "/Users/salishkumar/.nvm/versions/node/v16.11.1/bin/node" "/Users/salishkumar/.nvm/versions/node/v16.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/salishkumar/Desktop/Desktop/freelannce/gorin systems/sub-backend/node_modules/strapi-plugin-upload/node_modules/sharp
npm ERR! gyp ERR! node -v v16.11.1
npm ERR! gyp ERR! node-gyp -v v8.4.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/salishkumar/.npm/_logs/2021-11-30T16_18_40_695Z-debug.log

**Comment by lovell** [comment]
It looks like you're trying to install an outdated version of `strapi-plugin-upload`, which is now called `@strapi/plugin-upload`

https://github.com/strapi/strapi/blob/master/packages/core/upload/package.json

**Comment by salish-gorinsys** [comment]
@lovell i have updated version

**Comment by lovell** [comment]
Please can you confirm that you have completely removed use of the `strapi-plugin-upload` module and replaced it with `@strapi/plugin-upload` v4.0.0 (or later).

As an aside, when you're asking for free, unpaid help from volunteers, please re-consider your use of the "thumbs down" reaction against what they believe is a genuinely useful answer.

**Comment by DigitalCop** [comment]
I experience the same problem behind a proxy. Our proxy handles npm packages and sharp is in the proxy repo. The output is:
```
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.11.3/libvips-8.11.3-linux-x64.tar.br
npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! sharp: Installation error: getaddrinfo ENOTFOUND github.com
```
This happens when trying to run npm i sharp in a clean folder. Have tried with 0.29.3 and 0.29.0
I have also tried npm install sharp-0.29.3.tgz

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
