### ISSUE TITLE
SVG producing larger image than original

### ISSUE THREAD

**Issue by squillace91** [lovell/sharp#2995]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

npm ls sharp: sharp@0.29.3
npm view sharp dist-tags.latest: 0.29.3

What are the steps to reproduce?

Download this image https://file-examples-com.github.io/uploads/2017/10/file_example_PNG_3MB.png

```javascript
sharp(buffer)
  .resize({
    width: 2000,
    fit: sharp.fit.inside,
    withoutEnlargement: true,
  }).png({
    palette: true
  })
  .toFile('./test.png')
  .catch((err) => {
    console.log(err);
  });
```

What is the expected behavior?

I am expecting the file to be smaller than the original. The generated image is 4.75MB, and the original is 2.96MB. I tried a lot of different settings, none of them produce an image less than 4MB.

Are you able to provide a sample image that helps explain the problem?

Original
![image](https://user-images.githubusercontent.com/1086713/143925065-b84b9023-5508-42e0-b059-1647a3b4f0b6.png)

Output
![image](https://user-images.githubusercontent.com/1086713/143925274-55a41642-e33f-492b-aff7-53d55d31d9bd.png)

What is the output of running `npx envinfo --binaries --system`?

```
 System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 257.17 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
```

**Comment by lovell** [comment]
Correcting the sample code so it works:
```diff
-    2000,
+    width: 2000,
```
then running locally I see a `test.png` output file of 711632 bytes (the input file is 2964729 bytes).

**Comment by squillace91** [comment]
> Correcting the sample code so it works:
> 
> ```diff
> -    2000,
> +    width: 2000,
> ```
> 
> then running locally I see a `test.png` output file of 711632 bytes (the input file is 2964729 bytes).

@lovell apologies for the syntax issue there, will fix. It seems that your file is smaller (700kb). Would have any idea why my output file is much bigger? the same issue happens (file being bigger) when I deploy the same code to an AWS lambda function.

**Comment by lovell** [comment]
I note your output says "32-bit color" rather than "8-bit colormap", which means the `palette` option is being ignored. Please make sure you're using the latest version of sharp v0.29.3.

**Comment by squillace91** [comment]
I am using the latest version v.0.29.3. 

I used cmd `file` to check it from the terminal and indeed my output is 8-bit (not sure why my IDE was showing something different)

original: file_example_PNG_3MB.png: PNG image data, 2200 x 1467, 8-bit/color RGB, non-interlaced
output: test.png: PNG image data, 2000 x 1334, 8-bit/color RGB, non-interlaced

**Comment by squillace91** [comment]
I apologize. seems that my node_modules weren't up to date. Deleting the folder and reinstalling everything worked. 

Closing this and really appreciate the time!
