### ISSUE TITLE
Crashing with @napi-rs/canvas buffer, Check failed: result.second, Node.js 16

### ISSUE THREAD

**Issue by louisfoster** [lovell/sharp#2996]
- Using node v16

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

yes

What are the steps to reproduce?

When creating a raw buffer `.data()` from an [skr-canvas](https://github.com/Brooooooklyn/canvas) canvas, then passing it into sharp, sharp crashes (after the first or a few attempts on different instances) when using `toBuffer()` on this instance:

```
#
# Fatal error in , line 0
# Check failed: result.second.
#
#
#
#FailureMessage Object: 0x7ffceabb4970
 1: 0xb6f151  [node]
 2: 0x1bf56f4 V8_Fatal(char const*, ...) [node]
 3: 0xfc3f61 v8::internal::GlobalBackingStoreRegistry::Register(std::shared_ptr<v8::internal::BackingStore>) [node]
 4: 0xd151c8 v8::ArrayBuffer::GetBackingStore() [node]
 5: 0xab71b0 napi_get_typedarray_info [node]
 6: 0x7f097c75d1bf sharp::CreateInputDescriptor(Napi::Object) [/node_modules/sharp/build/Release/sharp-linux-x64.node]
 7: 0x7f097c766c2e pipeline(Napi::CallbackInfo const&) [/node_modules/sharp/build/Release/sharp-linux-x64.node]
 8: 0x7f097c773806 Napi::details::CallbackData<Napi::Value (*)(Napi::CallbackInfo const&), Napi::Value>::Wrapper(napi_env__*, napi_callback_info__*) [/node_modules/sharp/build/Release/sharp-linux-x64.node]
 9: 0xaadf9d  [node]
10: 0xd4a18e  [node]
11: 0xd4b5af v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x15e7959  [node]
Trace/breakpoint trap (core dumped)
```

That is to say, sometimes it _doesn't_ crash, but after a few re-runs of the function, it always eventually crashes.

What is the output of running `npx envinfo --binaries --system`?

```
  System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 1.83 GB / 15.22 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 8.1.0 - /usr/bin/npm
```

**Comment by lovell** [comment]
Please can you provide a standalone repo including dependency versions in a`package.json`, complete, minimal code and images that allows someone else to reproduce this.

My best guess would be that the `@napi-rs/canvas` module is susceptible to https://github.com/nodejs/node/issues/32463 and may need to add code to workaround a race condition when multiple Buffer instances can point to the same memory location.

sharp does not do this and is not susceptible to this problem on its own - please see #2196

**Comment by yisibl** [comment]
@Brooooooklyn PTAL, thanks.

**Comment by lovell** [comment]
@louisfoster Were you able to make any progress with this?

**Comment by louisfoster** [comment]
Instead of passing the canvas data directly, I use a pool of existing instances, along with buffers they copy to, and do the copy at the end of drawing and pass this copy into sharp. There's almost no noticeable time overhead. There's a separate issue regarding memory not being released but I don't think that's relevant here.
