### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Fax3SetupState: Bits/sample must be 1 for Group 3/4 encoding/decoding 

### ISSUE THREAD

**Issue by ompal-sisodiya** [lovell/sharp#2997]
As i am trying to convert svg to tiff using sharp library with ccittfax4 compression and 300 dpi(density) but getting below error:

**UnhandledPromiseRejectionWarning: Error: Fax3SetupState: Bits/sample must be 1 for Group 3/4 encoding/decoding
wbuffer_write: write failed**

**Sharp version : 0.28.3 
Node version : 14.16.0**

Code Snippet : 
````
const svgStream = fs.createReadStream("./samples-svgrepo-com.svg");
const writeStream = fs.createWriteStream("./output.tiff");

const converter = sharp({density:300,limitInputPixels : false}).on("data", (chunk) => {
     return sharp(chunk).toColourspace("b-w");
});
svgStream.pipe(converter).tiff({bitdepth: 1,compression: "ccittfax4",}).pipe(writeStream);

````

**Comment by lovell** [comment]
SVG input is rendered to RGBA and will always have an alpha channel, so you'll need to remove this via [removeAlpha](https://sharp.pixelplumbing.com/api-channel#removealpha) for 1-band CCITT4.

```js
const converter = sharp({ density: 300, limitInputPixels: false })
  .removeAlpha()
  .toColourspace("b-w")
  .tiff({ bitdepth: 1, compression: "ccittfax4" });

svgStream.pipe(converter).pipe(writeStream);
```

**Comment by ompal-sisodiya** [comment]
> SVG input is rendered to RGBA and will always have an alpha channel, so you'll need to remove this via [removeAlpha](https://sharp.pixelplumbing.com/api-channel#removealpha) for 1-band CCITT4.
> 
> ```js
> const converter = sharp({ density: 300, limitInputPixels: false })
>   .removeAlpha()
>   .toColourspace("b-w")
>   .tiff({ bitdepth: 1, compression: "ccittfax4" });
> 
> svgStream.pipe(converter).pipe(writeStream);
> ```

Hey @lovell , thanks for the response.
It is working for me .
