### ISSUE TITLE
GIF unsupported input

### ISSUE THREAD

**Issue by sabrehagen** [lovell/sharp#300]
Hi,

I'm trying to convert a GIF to JPEG, and I believe I'm using sharp correctly as per [this unit test] (https://github.com/lovell/sharp/commit/ab7408c96fae16d6264853d890354457205e629b). I'm using vips 8.1.0 and sharp 0.11.4. The following code produces the error `[Error: Input buffer contains unsupported image formatVipsForeignLoad: buffer is not in a known format]`.

```
sharp(fs.readFileSync(gifPath))
.resize(50, 50)
.jpeg()
.toBuffer((err, data, info) => {
    console.log(err) // [Error: Input buffer contains unsupported image formatVipsForeignLoad: buffer is not in a known format]
})
```
The GIF file I'm testing with is ![095fbbb5-7a4b-4064-a6ca-df90a9a85955](https://cloud.githubusercontent.com/assets/1094600/11167616/93b54370-8bbd-11e5-9b1d-1dd9be30844f.gif)

Is this an error, or am I doing something wrong?

**Comment by lovell** [comment]
Hi Jackson, was libvips compiled with support for ImageMagick/Graphicsmagick? You can test via:

```sh
$ vips --list | grep magick

VipsForeignLoadMagick (magickload_base), load with ImageMagick priority=-100
VipsForeignLoadMagickFile (magickload), load file with ImageMagick priority=-100, is_a, get_flags, get_flags_filename, header
VipsForeignLoadMagickBuffer (magickload_buffer), load buffer with ImageMagick priority=-100, is_a_buffer, get_flags, get_flags_filename, header
```

Also:

```javascript
> console.log(sharp.format.magick);

{ id: 'magick',
  input: { file: true, buffer: true, stream: true },
  output: { file: false, buffer: false, stream: false } }

```

Here's the output I get when running your example code:

![](https://cloud.githubusercontent.com/assets/210965/11167931/e87eacd6-8b70-11e5-8435-ae739bd25e8e.jpg)

**Comment by sabrehagen** [comment]
Running `vips --list | grep magick` returns nothing, so I expect not. I don't have GM or IM installed. Assuming I do install a magick variant, is it possible to treat transparent sections as white rather than black? My aim is to create a static thumbnail, and white is obviously a closer match than black.

**Comment by lovell** [comment]
> " is it possible to treat transparent sections as white rather than black?"

Yes, the [background](http://sharp.dimens.io/en/stable/api/#backgroundrgba) option is your friend here.

**Comment by sabrehagen** [comment]
Thank you for the assistance, much appreciated.

**Comment by sabrehagen** [comment]
I don't mean to hijack my own issue, but I'm getting `SHARP ERROR [Error: Input file is of an unsupported image format]` when running `sharp(imagePath).metadata()`. Vips has been compiled against ImageMagick as seen below, so I would expect as per the docs I'd have access to "JPEG, PNG, WebP, TIFF, OpenSlide, GIF and other libmagick-supported formats.". I've supplied the image I'm trying to get metadata for below.

```
$ vips --list | grep magick
        VipsForeignLoadMagick (magickload_base), load with ImageMagick priority=-100
          VipsForeignLoadMagickFile (magickload), load file with ImageMagick priority=-100, is_a, get_flags, get_flags_filename, header
          VipsForeignLoadMagickBuffer (magickload_buffer), load buffer with ImageMagick priority=-100, is_a_buffer, get_flags, get_flags_filename, header
```
![fe65e7cf-8eef-45af-865a-789b5822d5cd docx image8](https://cloud.githubusercontent.com/assets/1094600/11289039/1743cbd6-8f7d-11e5-9c27-5e9a1cf06f07.png)

**Comment by lovell** [comment]
@sabrehagen Perhaps check the filename is correct - see #283.

**Comment by sabrehagen** [comment]
Filename is definitely correct unfortunately. Can I provide you any other debug info?

**Comment by lovell** [comment]
Is the problematic image in PNG format or has Github converted it?

```javascript
sharp('1743cbd6-8f7d-11e5-9c27-5e9a1cf06f07.png').metadata().then(console.log);
```
produces:
```
{ format: 'png',
  width: 823,
  height: 648,
  space: 'srgb',
  channels: 3,
  hasProfile: false,
  hasAlpha: false }
```

**Comment by thalesfsp** [comment]
Hi @lovell! I still have the problem. My `vips --list | grep magick` returns:

```
VipsForeignLoadMagick (magickload_base), load with ImageMagick priority=-100
VipsForeignLoadMagickFile (magickload), load file with ImageMagick priority=-100, is_a, get_flags, get_flags_filename, header
VipsForeignLoadMagickBuffer (magickload_buffer), load buffer with ImageMagick priority=-100, is_a_buffer, get_flags, get_flags_filename, header
```

The error:

`Error while resizing OahuRE.gif. Error: Unsupported output __input' to equal null`

The image:

![oahure](https://cloud.githubusercontent.com/assets/750360/11326382/350b28b6-911d-11e5-95e0-248674d6c629.gif)

The code:

```js
var downloadStream = s3Client.getObject(params)
  .on('error', function (err) {
    return utils.logErrorAndPassToCallback('Error while downloading ' + params.Key + '. ' + err, cb);
  })
  .createReadStream() // need, because AWS S3 don't return one
  .pipe(sharp().resize(settings.width, settings.height)) // resize
  .on('error', function (err) {
    return utils.logErrorAndPassToCallback('Error while resizing ' + params.Key + '. ' + err, cb);
  });

  // ... upload back to AWS S3 code
};
```

**Comment by lovell** [comment]
@thalesfsp It looks like you're trying to output GIF - that's not supported - perhaps use an explicit [toFormat](http://sharp.dimens.io/en/stable/api/#toformatformat) method.

**Comment by thalesfsp** [comment]
@lovell So, what do you recommend to solve this problem? Check if the image is `.gif` and use GM instead of Sharp or `.toFormat()` solve that? Also, I'm not using `.toFormat()` because it's been piped to the AWS S3 uploader.

**Comment by thalesfsp** [comment]
@lovell ping

**Comment by innovation9** [comment]
very very useful, muchas gracias por favor!!! muchos muchos gracias!
