### ISSUE TITLE
PNG compression when use palette will lost some color

### ISSUE THREAD

**Issue by FengBryan** [lovell/sharp#3000]
What are you trying to achieve?
png file compression

Have you searched for similar questions?
no
Are you able to provide a minimal, standalone code sample that demonstrates this question?
yes
``` javascript
const fs = require('fs')
const sharp = require('sharp')
const path = require('path')
const uuidV4 = require('uuid').v4
;(async () => {
  const tmpDir = `${Date.now()}-${uuidV4().replace(/-/g, '')}`
  await fs.promises.mkdir(path.resolve(__dirname, `./result/${tmpDir}`), { recursive: true })
  const buffers = []
  const dirs = await fs.promises.readdir(path.resolve(__dirname, './assets'))
  for (const dirName of dirs) {
    console.log(dirName)
    const files = await fs.promises.readdir(path.resolve(__dirname, `./assets/${dirName}`))

    for (const fileName of files) {
      if (path.extname(fileName) === '.png') buffers.push({
        fileName: `${dirName}-${fileName}`,
        buffer: await fs.promises.readFile(path.resolve(__dirname, `./assets/${dirName}/${fileName}`))
      })
    }
  }

  for (const buf of buffers.slice(0, 1)) {
    const newBufferPng = await sharp(buf.buffer).toFormat('png', {  compressionLevel: 0  }) .toBuffer()
    // const newBufferJpeg = await sharp(buf.buffer).jpeg({ quality: 100, palette: true }).toBuffer()
    await fs.promises.writeFile(path.resolve(__dirname, `./result/${tmpDir}/${buf.fileName}`), newBufferPng)
    console.log('done')
    // await fs.promises.writeFile(path.resolve(__dirname, `./result/${tmpDir}/${buf.fileName}`.replace('png', 'jpg')), newBufferJpeg)
  }
  
})().then(console.log).catch(console.error)
```
Are you able to provide a sample image that helps explain the question?
without png option `quality` or `palette`
![image](https://user-images.githubusercontent.com/13618768/144752946-9961f065-eb1c-481a-802d-eb3a37b3ba9b.png)
with  png option `quality` or `palette`
![image](https://user-images.githubusercontent.com/13618768/144752961-42e00145-2689-416b-8a13-cd52af8f8359.png)

**Comment by lovell** [comment]
Yes, this is expected, the use of `palette` in this example is reducing a 32-bit per pixel "full colour" RGBA image down to an 8-bit per pixel indexed image, which is a "lossy" operation.

**Comment by FengBryan** [comment]
@lovell Which effected method or option I can use to reduce PNG file size, but not lose color info. 
I tried option `compressionLevel` but in the test, the size didn't change linerly.  
In some cases `compressionLevel` possibly make size larger than before comrpession
thx

**Comment by lovell** [comment]
For full-colour PNGs, `compressionLevel` and `adaptiveFiltering` affect output file size. You'll need to experiment to find the right setting for your scenario.

https://sharp.pixelplumbing.com/api-output#png

**Comment by FengBryan** [comment]
> For full-colour PNGs, `compressionLevel` and `adaptiveFiltering` affect output file size. You'll need to experiment to find the right setting for your scenario.

ok, thanks☻
