### ISSUE TITLE
Transparent png not negating as expected

### ISSUE THREAD

**Issue by AdamJessop** [lovell/sharp#3004]
Using the latest version of sharp I am unable to negate the png file found at this URL:
https://images.ctfassets.net/kzz49cs436ud/3znXc9IE9SvZyzmAr40c99/d7aae5c6f114e1061b0f88ae2a35baf6/SOCIOS_ENDPOINT-01_1.png

I have put together a code sandbox to show the output. The expectations are that the colours in the png would be inverted to black / grey with the alpha channel remaining intact.

codesandbox: https://codesandbox.io/s/node-js-forked-wqlkc?file=/src/index.js:188-310

**Comment by lovell** [comment]
Please try the following:
```diff
- .negate(false)
+ .negate({ alpha: false })
```
https://sharp.pixelplumbing.com/api-operation#negate

**Comment by AdamJessop** [comment]
Thanks, resolved.

Turns out the @types definition is wrong.

![image](https://user-images.githubusercontent.com/6536024/145003796-4bca19ae-65a3-4350-91ec-35b5156b0fe4.png)

**Comment by lovell** [comment]
Ah, those are from the independent [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo. Perhaps you could open an issue (or better, a PR) there.

**Comment by AdamJessop** [comment]
Yes will do, thanks.
