### ISSUE TITLE
upscale image from hd to 4k 

### ISSUE THREAD

**Issue by abd-maqableh** [lovell/sharp#3005]
Hello Dears,

can I upscale an image from HD of FHD resolution to 4k?

**Comment by lovell** [comment]
Please can you provide (significantly) more details, including sample images, the code you've written so far, and expectations about the output dimensions etc.

https://sharp.pixelplumbing.com/api-resize

**Comment by abd-maqableh** [comment]
I mean if I have an image that has resolution HD 1920 * 1080 and I need to make it to 3840 * 2160 resolution
Is it doable with sharp js?

**Comment by lovell** [comment]
Yes, something like:
```js
const output = await sharp(input)
  .resize({ width: 3840, height: 2160 })
  .toBuffer();
```

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
