### ISSUE TITLE
toBuffer() throws [Error: Input file is missing]

### ISSUE THREAD

**Issue by ManagerCat** [lovell/sharp#3009]
Running toBuffer() doesn't seem to work and instead throws the error:
<img width="466" alt="Screen Shot 2021-12-08 at 4 24 26 PM" src="https://user-images.githubusercontent.com/67668325/145312279-f90ee124-9f4a-48f4-bfa7-e2a9b2adc86a.png">

**Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?**
Yes
**What are the steps to reproduce?**
Run toBuffer() with a png instance of sharp
**What is the expected behaviour?**
returns the buffer of the png instance of sharp
**Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?**
It works without the dependency but the other dependency works with svg2png and other libraries.
```js
const mjAPI = require('mathjax-node');
const fs = require('fs');
const sharp = require('sharp');
mjAPI.typeset({
    math: 'E=mc',
    format: "TeX", // or "inline-TeX", "MathML"
    svg: true,      // or svg:true, or html:true
}, async function (data) {
    if (!data.errors) {
        sharp(data.svg)
            .png()
            .toBuffer()
            .then(buff => {
                fs.writeFile('test.png', buff, (err) => {
                    if (err) console.log(err)
                })
            })

    }
});
```

**What is the output of running `npx envinfo --binaries --system`?**
```System:
    OS: macOS 11.6
    CPU: (4) x64 Intel(R) Core(TM) i7-6660U CPU @ 2.40GHz
    Memory: 136.64 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.1.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
```

**Comment by lovell** [comment]
https://www.npmjs.com/package/mathjax-node says

>   svg:                        // a string of SVG markup if requested

So you'll need to convert `data.svg` from a string to a Buffer.

```diff
-        sharp(data.svg)
+        sharp(Buffer.from(data.svg))
```
