### ISSUE TITLE
Unable to use flip() twice on same input

### ISSUE THREAD

**Issue by AmeyMore98** [lovell/sharp#3012]
I'm using sharp(version 0.29.3), and trying to chain multiple `flip()` operations, but sharp applies this operation only once. I also tried disabling sharp's cache using `sharp.cache(false)`, but it still doesn't work. 
This happens for other operations also, like `flop()`, `rotate()` etc.

Here's my code:
```
const sharp = require("sharp");
sharp.cache(false);
sharp("/home/Downloads/temp/ip3.jpg").flip().flip().toFile("/home/Downloads/temp/op.jpg").then(console.log);
```

Input image:
![ip3](https://user-images.githubusercontent.com/13717006/145714383-bfbe2ba1-1d4c-4539-9108-2dad0387c27f.jpg)

Output image:
![op](https://user-images.githubusercontent.com/13717006/145714396-3e73c024-3220-4649-ba19-f1daaaf582d8.jpg)

Thanks for your help!

**Comment by lovell** [comment]
Yes, if you really need to do this then split the task into two pipelines.

**Comment by AmeyMore98** [comment]
Ok, got it. Is this required for all operations or just `flip()`? 
Also can you please help with some sample code or docs for the pipeline approach? 
Thanks.

**Comment by lovell** [comment]
If you need to repeat a given operation multiple times, yes. There's some discussion about this at #241

```js
const flippedOnce = await sharp(input).flip().toBuffer();
const flippedTwice = await sharp(flippedOnce).flip().toBuffer();
```

**Comment by AmeyMore98** [comment]
This works, thanks!
