### ISSUE TITLE
Proposed v0.30.0 release: GIF output, resize animated images

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#3013]
The next release will be from the [main](https://github.com/lovell/sharp/tree/main) branch. No "when..." questions please.

### GIF output for everyone

GIF input has been supported for many years, but GIF output has previously only been possible when using a custom libvips compiled with support for *magick.

Thanks to financial support from Shopify, libvips is now integrated with [cgif](https://github.com/dloebl/cgif) and this will be included in the prebuilt binaries provided by sharp v0.30.0.

```js
// Available from v0.30.0
const gif = await sharp(input).gif().toBuffer()
```

### Resizing improvements for animated and SVG images

Thanks to some great work by Kleis, it's going to be much easier to resize and extract regions from animated (multi-frame) images and this will work with GIF output. No more manually setting page heights.

```js
// Available from v0.30.0
await sharp('in.gif', { animated: true })
  .resize({ width: 128, height: 128 })
  .toFile('out.gif')
```

Rendering SVG images will no longer require that the `density` be manually provided. Instead the target dimensions provided to `resize` will determine the scale when rendering pixels.

```js
// Available from v0.30.0
await sharp('in.svg')
  .resize({ width: 32, height: 32 })
  .toFile('out.png')
```

This might be suitable for replacing older SVG to PNG converters that use browser-based rendering.

### Wider range of Linux OS for ARM64

Support for more Linux-based OS using ARM64 CPUs will be possible thanks to building binaries on native ARM64 hardware, therefore reducing the glibc requirement to 2.17.

This will include use with AWS Lambda running on Graviton 2 CPUs.

### Installation integrity checks

To help protect against supply chain attacks, Subresource Integrity hashes of the prebuilt libvips binaries will be included in sharp's `package.json` published to npm and will be verified at install time.

https://github.com/lovell/sharp/blob/3b492ea423b95c100d750d3b5e6c15fce623bbfe/package.json#L154-L166

### Potentially breaking changes

The parameter name to control CPU effort when encoding will be standardised as `effort`, and this applies to AVIF, WebP, PNG and GIF.

Any previous parameters relating to this such as `speed` and `reductionEffort` will be deprecated.

### Full changelog

There will be lots of smaller features and bug fixes, so please see the work-in-progress changelog for more details.

https://github.com/lovell/sharp/blob/main/docs/changelog.md#v030---dresser

**Comment by dveldhoen** [comment]
Hi, I was wondering what the ETA is on this update? The Lambda Graviton support would be a most welcome. Thanks in advance and good luck!

**Comment by lovell** [comment]
v0.30.0 is now available.
