### ISSUE TITLE
Tiff image density should be return 300 dpi(pixels per inch) by withMetadata({desnsity:300}) but it is returning wrong dpi unit (pixels/mm) 

### ISSUE THREAD

**Issue by ompal-sisodiya** [lovell/sharp#3014]
As i am trying to convert svg to tiff using sharp library with ccittfax4 compression and 300 dpi(Number of pixels per inch (DPI) 

but getting below response:

![tiff-image-output-property (1)](https://user-images.githubusercontent.com/79189318/146184730-c27a3a9e-1393-46d2-a9e2-96c933cf96d1.PNG)

But  response should be :

**Density: 300 DPI   //Number of pixels per inch**
**Resolution Unit: 2**

**Sharp version : 0.28.3
Node version : 14.16.0**

Code Snippet :

  function tiffConversion(streamData){
    
      const converter = sharp()
                    .flatten({ background: { r: 255, g: 250, b: 255, alpha: 255 } })
                    .toColourspace('b-w')
                    .threshold(255)
                    .tiff({bitdepth:1,compression:'ccittfax4',quality:100})
                   .withMetadata({density:300});
      
          return streamData.pipe(converter);
  }

  async function uploadImage(){
    const streamData= fs.createReadStream('./input.svg');
    const file =fs.createWriteStream('./out2.tiff');
    await pipelinePromise(tiffConversion(streamData),file);
  }
  uploadImage();

**Comment by lovell** [comment]
Please upgrade to the latest v0.29.3 to benefit from recent improvements to TIFF resolution handling.

https://sharp.pixelplumbing.com/changelog

**Comment by ompal-sisodiya** [comment]
@lovell  Thanks for quick response :    But after upgrade sharp version density is working fine but **resolution unit still 3.** but i feel  **it should be 2** because withMetadata({desnsity:300}) function return density in **pixels per inch**.
![tiff-image-300-density](https://user-images.githubusercontent.com/79189318/146311949-e3172788-ed9f-4518-9bb7-9ec9e93581c3.PNG)


A value of 2 means that the unit is inches, so the resolution is to be interpreted as dots per inch (dpi).
**A value of 3 means that the resolution should be interpreted in centimeters, that is dots per centimeter (dpcm or dpc).**

https://www.askingbox.com/question/tiff-what-does-a-resolution-unit-of-2-or-3-mean#:~:text=The%20resolution%20unit%20is%20the,centimeter%20(dpcm%20or%20dpc).

**Comment by lovell** [comment]
The resolution value appears to be as-expected due to libvips defaulting to pixels per millimetre rather than per inch when writing TIFF images. I think Windows might be auto-converting values for display purposes.

To control the resolution unit for TIFF output, we'd need to expose the `resunit` property of https://www.libvips.org/API/current/VipsForeignSave.html#vips-tiffsave in sharp (and then probably also remove any per inch to per mm conversions).

https://sharp.pixelplumbing.com/api-output#tiff

Happy to accept a PR, if you're able.

**Comment by ompal-sisodiya** [comment]
Hello @lovell 
I am ready with the changes but need the access to commit the code. 
Just for your ref getting below error :

**remote: Permission to lovell/sharp.git denied to ompal-sisodiya.**
**fatal: unable to access 'https://github.com/lovell/sharp.git/': The requested URL returned error: 403**

**Comment by lovell** [comment]
Thanks, if you haven't already you'll need to fork this repo then open a pull request.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by holgerschillack** [comment]
I'm not 100% sure if you were asking for that, but what I'm using for years now to get e.g. 1200dpi tiff files is

```
.tiff({
  quality: 100,
  compression: "lzw",
  bitdepth: 8,
  xres: 47.24,
  yres: 47.24,
})
```
So for 300dpi you need to use xres/yres: 11.81

**Comment by lovell** [comment]
v0.30.0 now available, thanks again for the PR.
