### ISSUE TITLE
Cant run on windows 7 32bit, The specified procedure could not be found, canvas is a dependency

### ISSUE THREAD

**Issue by Updour** [lovell/sharp#3016]
I try install sharp on whatsapp-web js using nodejs version 12.21.0 
But i have error ![IMG_20211217_001134.jpg](https://user-images.githubusercontent.com/36692358/146417628-41bf8b9a-dbce-46f9-84c8-4221aeb8c2b5.jpg)

**Comment by lovell** [comment]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7, does the user running `npm install` own the directory it is run in?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

What is the output of running `npx envinfo --binaries --system`?

**Comment by Updour** [comment]
Views version sharp 
No lates

![IMG_20211217_003116.jpg](https://user-images.githubusercontent.com/36692358/146420964-897ed9a8-69c2-4b24-9bac-e98751aec1ac.jpg)

**Comment by Updour** [comment]
output from npm install --verbose sharp 


H:\whatsapp\whatsapp-web.js-main>npm ls sharp
whatsapp-web.js@1.15.3 H:\whatsapp\whatsapp-web.js-main
`-- sharp@0.28.3


H:\whatsapp\whatsapp-web.js-main>npm install --verbose sharp
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@6.14.11
npm info using node@v12.21.0
npm verb npm-session 78969b5c2ba83302
npm http fetch GET 304 https://registry.npmjs.org/sharp 238ms (from cache)
npm timing stage:loadCurrentTree Completed in 967ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 4ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 381ms
npm http fetch GET 304 https://registry.npmjs.org/color 67ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-get 159ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/prebuild-install 163ms (from c
ache)
npm http fetch GET 304 https://registry.npmjs.org/detect-libc 185ms (from cache)

npm http fetch GET 304 https://registry.npmjs.org/tunnel-agent 187ms (from cache
)
npm http fetch GET 304 https://registry.npmjs.org/node-addon-api 1196ms (from ca
che)
npm http fetch GET 304 https://registry.npmjs.org/color-convert 100ms (from cach
e)
npm http fetch GET 304 https://registry.npmjs.org/color-string 105ms (from cache
)
npm http fetch GET 304 https://registry.npmjs.org/color-name 60ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-swizzle 57ms (from cach
e)
npm http fetch GET 304 https://registry.npmjs.org/is-arrayish 56ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/npmlog 75ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/github-from-package 83ms (from
 cache)
npm http fetch GET 304 https://registry.npmjs.org/expand-template 87ms (from cac
he)
npm http fetch GET 304 https://registry.npmjs.org/rc 88ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-abi 92ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/napi-build-utils 1001ms (from
cache)
npm http fetch GET 304 https://registry.npmjs.org/semver 53ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/set-blocking 68ms (from cache)

npm http fetch GET 304 https://registry.npmjs.org/are-we-there-yet 75ms (from ca
che)
npm http fetch GET 304 https://registry.npmjs.org/gauge 76ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/console-control-strings 86ms (
from cache)
npm http fetch GET 304 https://registry.npmjs.org/delegates 53ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/readable-stream 62ms (from cac
he)
npm http fetch GET 304 https://registry.npmjs.org/core-util-is 76ms (from cache)

npm http fetch GET 304 https://registry.npmjs.org/process-nextick-args 78ms (fro
m cache)
npm http fetch GET 304 https://registry.npmjs.org/string_decoder 83ms (from cach
e)
npm http fetch GET 304 https://registry.npmjs.org/safe-buffer 90ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/isarray 911ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/has-unicode 52ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/strip-ansi 79ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/wide-align 83ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/object-assign 90ms (from cache
)
npm http fetch GET 304 https://registry.npmjs.org/signal-exit 94ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/aproba 138ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/string-width 903ms (from cache
)
npm http fetch GET 304 https://registry.npmjs.org/is-fullwidth-code-point 49ms (
from cache)
npm http fetch GET 304 https://registry.npmjs.org/code-point-at 58ms (from cache
)
npm http fetch GET 304 https://registry.npmjs.org/number-is-nan 50ms (from cache
)
npm http fetch GET 304 https://registry.npmjs.org/ansi-regex 64ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/strip-json-comments 55ms (from
 cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 58ms (from
 cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-concat 272ms (from cach
e)
npm http fetch GET 304 https://registry.npmjs.org/mimic-response 46ms (from cach
e)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 5453ms
npm timing stage:loadIdealTree Completed in 5940ms
npm timing stage:generateActionsToTake Completed in 49ms
npm verb correctMkdir C:\Users\lacesaria\AppData\Roaming\npm-cache\_locks correc
tMkdir not in flight; initializing
npm verb makeCacheDir UID & GID are irrelevant on win32
npm verb lock using C:\Users\lacesaria\AppData\Roaming\npm-cache\_locks\staging-
0e72d13e6cefcd7b.lock for H:\whatsapp\whatsapp-web.js-main\node_modules\.staging

npm timing action:extract Completed in 65ms
npm info lifecycle sharp@0.28.3~preuninstall: sharp@0.28.3
npm info lifecycle sharp@0.28.3~uninstall: sharp@0.28.3
npm verb unbuild rmStuff sharp@0.28.3 from H:\whatsapp\whatsapp-web.js-main\node
_modules
npm info lifecycle sharp@0.28.3~postuninstall: sharp@0.28.3
npm timing action:unbuild Completed in 6ms
npm timing action:remove Completed in 173ms
npm timing action:finalize Completed in 22ms
npm timing action:refresh-package-json Completed in 80ms
npm info lifecycle sharp@0.28.3~preinstall: sharp@0.28.3
npm timing action:preinstall Completed in 2ms
npm info linkStuff sharp@0.28.3
npm timing action:build Completed in 1ms
npm info lifecycle sharp@0.28.3~install: sharp@0.28.3

> sharp@0.28.3 install H:\whatsapp\whatsapp-web.js-main\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node i
nstall/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Using cached C:\Users\lacesaria\AppData\Roaming\npm-cache\_libvips\libvip
s-8.10.6-win32-ia32.tar.br
sharp: Creating H:\whatsapp\whatsapp-web.js-main\node_modules\sharp\build\Releas
e
sharp: Copying DLLs from H:\whatsapp\whatsapp-web.js-main\node_modules\sharp\ven
dor\8.10.6\lib to H:\whatsapp\whatsapp-web.js-main\node_modules\sharp\build\Rele
ase
prebuild-install info begin Prebuild-install version 6.1.4
prebuild-install info looking for local prebuild @ prebuilds\sharp-v0.28.3-napi-
v3-win32-ia32.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\lacesaria\AppData\R
oaming\npm-cache\_prebuilds\1a2fc4-sharp-v0.28.3-napi-v3-win32-ia32.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ C:\Users\lacesaria\AppData\Roaming\npm-cache\_
prebuilds\1a2fc4-sharp-v0.28.3-napi-v3-win32-ia32.tar.gz
prebuild-install info unpack resolved to H:\whatsapp\whatsapp-web.js-main\node_m
odules\sharp\build\Release\sharp.node
prebuild-install info install Successfully installed prebuilt binary!
npm verb lifecycle sharp@0.28.3~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.28.3~install: PATH: C:\Program Files\nodejs\node_modu
les\npm\node_modules\npm-lifecycle\node-gyp-bin;H:\whatsapp\whatsapp-web.js-main
\node_modules\sharp\node_modules\.bin;H:\whatsapp\whatsapp-web.js-main\node_modu
les\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\Syst
em32\WindowsPowerShell\v1.0\;c:\Program Files\Microsoft SQL Server\90\Tools\binn
\;C:\Program Files\nodejs\;C:\Users\lacesaria\AppData\Roaming\npm
npm verb lifecycle sharp@0.28.3~install: CWD: H:\whatsapp\whatsapp-web.js-main\n
ode_modules\sharp
npm timing audit submit Completed in 401ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quic
k 401ms
npm timing audit body Completed in 0ms
npm timing action:install Completed in 1922ms
npm info lifecycle sharp@0.28.3~postinstall: sharp@0.28.3
npm timing action:postinstall Completed in 1ms
npm verb unlock done using C:\Users\lacesaria\AppData\Roaming\npm-cache\_locks\s
taging-0e72d13e6cefcd7b.lock for H:\whatsapp\whatsapp-web.js-main\node_modules\.
staging
npm timing stage:executeActions Completed in 2300ms
npm timing stage:rollbackFailedOptional Completed in 83ms
npm timing stage:runTopLevelLifecycles Completed in 9450ms
npm verb saving [ { name: 'sharp', spec: '^0.28.3', save: 'dependencies' } ]
npm verb shrinkwrap skipping write for package.json because there were no change
s.
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle whatsapp-web.js@1.15.3~shrinkwrap: whatsapp-web.js@1.15.3
npm verb shrinkwrap skipping write for package-lock.json because there were no c
hanges.
npm info lifecycle whatsapp-web.js@1.15.3~postshrinkwrap: whatsapp-web.js@1.15.3

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"
})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: ia32

+ sharp@0.28.3
updated 1 package and audited 331 packages in 9.692s

36 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm verb exit [ 0, true ]
npm timing npm Completed in 10406ms
npm info ok

**Comment by Updour** [comment]
output npx envinfo --binaries --system

H:\whatsapp\whatsapp-web.js-main>npx envinfo --binaries --system
npx: installed 1 in 2.153s

  System:
    OS: Windows 7 6.1.7600
    CPU: (4) ia32 Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz
    Memory: 1.54 GB / 3.39 GB
  Binaries:
    Node: 12.21.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD

**Comment by lovell** [comment]
Thanks, is `canvas` also in your dependencies? If so see https://sharp.pixelplumbing.com/install#known-conflicts

**Comment by Updour** [comment]
Sharp not support on windows n kanvas ?

**Comment by lovell** [comment]
Correct, there is no workaround.

> The prebuilt binaries provided by canvas for Windows depend on the unmaintained GTK 2, last updated in 2011.
>
> These conflict with the modern, up-to-date binaries provided by sharp.

**Comment by Updour** [comment]
but i try on windows 7 32 bit, with the same module it can work fine.


C:\Users\SMSCENTER>npx envinfo --binaries --system
npx: installed 1 in 1.662s

  System:
    OS: Windows 7 6.1.7601
    CPU: (2) ia32 Intel(R) Pentium(R) CPU G2030 @ 3.00GHz
    Memory: 1.92 GB / 3.20 GB
  Binaries:
    Node: 12.21.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by ueoeae** [comment]
> 

Is there an alternative to canvas?
