### ISSUE TITLE
X11 Mouse Cursor generated from PNG files upscaled from an SVG by sharp are broken in video recordings.

### ISSUE THREAD

**Issue by phisch** [lovell/sharp#3018]
First of all, i'm sorry for opening this oddly specific issue, but from my debugging, this can only be related to how sharp rasterizes SVG files.

I'm on the currently latest version of sharp: `0.29.3`

So I am trying to generate multiple upscaled PNG versions of an SVG, and use those PNG files to generate a X Mouse Cursor file from them. At first glance, this seems to work perfectly fine, and the cursor generated is displayed properly on the screen. But when recording a video that includes that cursor, it ends up having weird edges. When I open the cursor file that was generated that way with GIMP and just re-export it as is, the cursor starts looking fine in video recordings as well.

Here is the SVG used: [left_ptr.zip](https://github.com/lovell/sharp/files/7739616/left_ptr.zip)
It is a basic shape with an outline and a shadow.

This is how the cursor looks in screenshots and on screen:

![cursor](https://user-images.githubusercontent.com/1282767/146649665-1d99cf83-7efa-43b3-8a31-f0ca2a3a01db.png)

And this is how it looks in a video recording:

https://user-images.githubusercontent.com/1282767/146649676-d8bbe501-2f0f-41a8-9382-6e6172c977b5.mp4

This is unfortunately not an issue with the video recording though. As mentioned above, re-exporting that same generated X Mouse Cursor file with GIMP results in a cursor that looks good in videos too:

https://user-images.githubusercontent.com/1282767/146649886-ea74fa6f-3971-47f8-b51a-411ce11df3a2.mp4

This is the generated cursor file: [left_ptr_generated.zip](https://github.com/lovell/sharp/files/7739623/left_ptr_generated.zip)
And here is the same file opened and re-exported in GIMP: [left_ptr_GIMP.zip](https://github.com/lovell/sharp/files/7739625/left_ptr_GIMP.zip)

The code I am using to generate this file:
```js
const sharp = require('sharp');
const fs = require('fs');
const { Encoder } = require('xcursor');

(async () => {
  const size = 32;

  const images = await Promise.all(Object.values([1, 2, 4]).map(async (scale) => {
    const image = sharp('svg/left_ptr.svg', { density: 72 * scale });
    const scaled = image.resize(size * scale, size * scale);
    return {
      type: size * scale,
      xhot: 0,
      yhot: 0,
      data: await scaled.raw().toBuffer(),
      delay: 50,
    };
  }));

  const encoder = new Encoder(images);
  fs.writeFileSync('output/left_ptr', Buffer.from(encoder.pack()));
})();
```

I load the SVG using sharp, supplying the proper density for the scale I want to generate (1x, 2x and 4x), resize it, and grab the raw buffer generated by sharp. This data is used for a struct that will generate the x11 cursor file.

First things first, I did generate PNG files and ran them through the official `xcursorgen` application, and got the same result of a broken cursor. I have also read through and debugged the xcursor library. There is no issue in it, it properly assembles an X11 Mouse Cursor file. The xcursor library generates cursors that look fine in videos from PNG files generated by other applications. 

The issue only happens when the raw image data is generated by sharp.

I have also created a minimal test application that generates a cursor file: [cursor_example.zip](https://github.com/lovell/sharp/files/7739642/cursor_example.zip)

Currently I am completely out of ideas on how to proceed debugging this. Since you wrote sharp, I hope you have some magic advise for me.

**Comment by cmawhorter** [comment]
i'm currently working through my own set of unrelated issues with svg and i'll share what i've learned.

sharp uses librsvg to convert svgs.  AFAICT rsvg is a very incomplete implementation of svg and i'd be willing to wager it has poor support for the filters in your left_ptr cursor file:

```svg
<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
<g filter="url(#filter0_d_102_11)">
<path d="..." fill="#1F1F1F"/>
<path d="..." stroke="white" stroke-linejoin="round"/>
</g>
<defs>
<filter id="filter0_d_102_11" x="1.99995" y="1.99997" width="17.2" height="26.0001" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
<feFlood flood-opacity="0" result="BackgroundImageFix"/>
<feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
<feOffset dx="1" dy="1"/>
<feGaussianBlur stdDeviation="1"/>
<feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0"/>
<feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_102_11"/>
<feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_102_11" result="shape"/>
</filter>
</defs>
</svg>
```
maybe try simplifying it and converting those filters to regular elements?

**Comment by phisch** [comment]
@cmawhorter i have been debugging this all day long, and i am starting to believe this is not a sharp issue. It seems to be an issue with ffmpeg, the video recording software. I manually compared the raw image data pixel by pixel between the good version and the bad version of the cursor, and the only difference are a couple pixels lightness, which is probably due some sort of image compression gimp applied on top of the cursor generated with sharp png files.

I have also written an application that unpacks X11 Mouse Cursor files, compares their actual pixel difference, and then repacks them. So here is what the actual pixel difference looks like:
![image](https://user-images.githubusercontent.com/1282767/146656500-b734c68c-3c75-4bfe-becd-478412f94018.png)

Remember, ^ this difference is on a binary level, other than some tiny changes on those pixels, the files are identical. Yet one looks like this in a recording:
![image](https://user-images.githubusercontent.com/1282767/146656527-0bb57eef-d432-46f5-a91b-84042a3239da.png)
and the other like this: 
![image](https://user-images.githubusercontent.com/1282767/146656533-0df723b0-8387-43bc-a6a0-ca0b24e82aa6.png)

The visual difference is obviously way larger than the actual physical difference on a binary level. And this drives me crazy.
I will try to speak to some guys over on the ffmpeg irc, maybe they have some insights on why this might happen.

**Comment by phisch** [comment]
Ok, i am 99.99% sure this is some really weird bug in ffmpeg. Every other application that composits the cursor onto an image does not have this issue (screenshot tools and obs for example). Certainly not a bug in sharp, sorry for the noise.

**Comment by phisch** [comment]
Little update, it is now confirmed to be a bug in ffmpegs blend function used to composit the cursor on top of the video recording. That would have been my last thought, considering people have recorded cursors for decades...
