### ISSUE TITLE
Error With ForeignObject

### ISSUE THREAD

**Issue by sizeoftrickster** [lovell/sharp#3019]
Hello. I'm trying to make an SVG image that will automatically move the text to another line. I am using this code:
```
const sharp = require('sharp');

(async function () {

    let svg = `
    <svg width="1222" height="532" viewbox="0 0 1222 532">
        <style>
            .text {
                word-break: break-all;
            }
        </style>
    
        <foreignObject x="20" y="20" width="160" height="160">
           <div class="text">
                This is loooooooooooooooooooooooooong text
            </div>
        </foreignObject>
    </svg>
    `;

    await sharp('input.png')
        .composite([{ input: Buffer.from(svg) }])
        .toFile('output.png');

})();
```
Output: At the output I get the same image.

If you use this in an online SVG editor, everything works there, what could be the problem?
Output:
![изображение](https://user-images.githubusercontent.com/89731540/146927623-82ee65da-9cc5-4f0f-8a25-948d5c006322.png)

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/512
