### ISSUE TITLE
Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by harisghulam** [lovell/sharp#3022]
I've tried several existing solutions, but still not resolved

#npm install --verbose sharp

npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@8.1.0
npm info using node@v16.13.0
npm timing npm:load:whichnode Completed in 1ms
npm timing config:load:defaults Completed in 3ms
npm timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Compl
eted in 6ms
npm timing config:load:builtin Completed in 6ms
npm timing config:load:cli Completed in 4ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:C:\Users\GeeiKa.com\whatsapp-web\.npmrc Completed in
 0ms
npm timing config:load:project Completed in 2ms
npm timing config:load:file:C:\Users\GeeiKa.com\.npmrc Completed in 2ms
npm timing config:load:user Completed in 2ms
npm timing config:load:file:C:\Users\GeeiKa.com\AppData\Roaming\npm\etc\npmrc Co
mpleted in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 2ms
npm timing config:load:credentials Completed in 2ms
npm timing config:load:setEnvs Completed in 2ms
npm timing config:load Completed in 24ms
npm timing npm:load:configload Completed in 25ms
npm timing npm:load:setTitle Completed in 0ms
npm timing npm:load:setupLog Completed in 1ms
npm timing config:load:flatten Completed in 7ms
npm timing npm:load:cleanupLog Completed in 5ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 2ms
npm timing npm:load Completed in 138ms
npm timing arborist:ctor Completed in 2ms
npm timing idealTree:init Completed in 192ms
npm timing idealTree:userRequests Completed in 2ms
npm timing arborist:ctor Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/sharp 2496ms (cache revalidate
d)
npm timing idealTree:#root Completed in 2530ms
npm timing idealTree:node_modules/sharp Completed in 0ms
npm timing idealTree:buildDeps Completed in 2536ms
npm timing idealTree:fixDepFlags Completed in 4ms
npm timing idealTree Completed in 2745ms
npm timing reify:loadTrees Completed in 2747ms
npm timing reify:diffTrees Completed in 12ms
npm timing reify:retireShallow Completed in 0ms
npm timing reify:createSparse Completed in 0ms
npm timing reify:loadBundles Completed in 0ms
npm timing reify:unpack Completed in 1ms
npm timing reify:unretire Completed in 0ms
npm timing build:queue Completed in 0ms
npm timing build:deps Completed in 2ms
npm timing build Completed in 3ms
npm timing reify:build Completed in 4ms
npm timing reify:trash Completed in 0ms
npm timing reify:save Completed in 70ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/
bulk 1076ms
npm timing auditReport:getReport Completed in 1087ms
npm timing auditReport:init Completed in 0ms
npm timing reify:audit Completed in 1095ms
npm timing reify Completed in 3889ms

up to date, audited 127 packages in 5s

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm timing command:install Completed in 3914ms
npm verb exit 0
npm timing npm Completed in 4613ms
npm info ok

#npm ls sharp 

whatsapp-web@1.0.0 C:\Users\GeeiKa.com\whatsapp-web
+-- sharp@0.29.3
`-- whatsapp-web.js@1.15.3
  `-- sharp@0.28.3

#npm ls -g sharp

C:\Users\GeeiKa.com\AppData\Roaming\npm
`-- (empty)

#npx envinfo --binaries --system

 System:
   OS: Windows 8.1 6.3.9600
   CPU: (4) x64 Intel(R) Core(TM) i3 CPU       M 380  @ 2.53GHz
   Memory: 585.50 MB / 1.87 GB
 Binaries:
   Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
   npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD

**Comment by harisghulam** [comment]
C:\Users\GeeiKa.com\whatsapp-web\node_modules\whatsapp-web.js\node_modules\sharp
\lib\constructor.js:32
  throw new Error(error);
  ^

Error:
Something went wrong installing the "sharp" module

The specified module could not be found.
\\?\C:\Users\GeeiKa.com\whatsapp-web\node_modules\whatsapp-web.js\node_modules\s
harp\build\Release\sharp.node

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/inst
all
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (C:\Users\GeeiKa.com\whatsapp-web\node_modules\whatsap
p-web.js\node_modules\sharp\lib\constructor.js:32:9)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\GeeiKa.com\whatsapp-web\node_modules\whatsap
p-web.js\node_modules\sharp\lib\index.js:3:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

**Comment by lovell** [comment]
It looks like `whatsapp-web.js` is dependent on an older version, please upgrade (or ensure these match).
```
whatsapp-web@1.0.0 C:\Users\GeeiKa.com\whatsapp-web
+-- sharp@0.29.3
-- whatsapp-web.js@1.15.3 -- sharp@0.28.3
```

**Comment by indutny-signal** [comment]
Hello! I'm seeing the same error with `sharp@0.29.3` and I can easily reproduce it by downloading the prebuilt `.node` file from [the Releases page](https://github.com/lovell/sharp/releases/download/v0.29.3/sharp-v0.29.3-napi-v5-win32-x64.tar.gz) and opening it with node 16.9.1:

<img width="573" alt="image" src="https://user-images.githubusercontent.com/79877362/147001403-156f4e7f-32bc-416d-9244-a57636e9e13f.png">

**Comment by lovell** [comment]
@indutny-signal Hi Fedor, to emulate sharp's installation process manually, you'll also need to download the relevant tarball from https://github.com/lovell/sharp-libvips/releases/tag/v8.11.3 e.g. [libvips-8.11.3-win32-x64.tar.gz](https://github.com/lovell/sharp-libvips/releases/download/v8.11.3/libvips-8.11.3-win32-x64.tar.gz) and add its DLLs too.

https://github.com/lovell/sharp/blob/1ff84b20b7d9b351786fb06899255cea59aa123c/package.json#L85

The issue faced by @harisghulam is that there's a mixture/conflict in these DLLs between v0.29.3 and v0.28.3, both of which are present in their installation tree. Upgrading everything to the latest version of sharp should fix this.

**Comment by indutny-signal** [comment]
Ah, got it. My bad! Looks like dll's werent' included into our distribution by mistake. Thanks!

**Comment by lovell** [comment]
@indutny-signal No worries, more importantly thanks for everything you've contributed to the Node.js ecosystem over the years.

**Comment by indutny-signal** [comment]
Hey, you are too kind! Thanks for publishing this library, it is very useful to us!

**Comment by harisghulam** [comment]
I've updated sharp, and I'm getting a new error.

C:\Users\GeeiKa.com\geebot>npm ls sharp
geebot@1.0.0 C:\Users\GeeiKa.com\geebot
+-- sharp@0.29.3
`-- whatsapp-web.js@1.15.3
  `-- sharp@0.29.3


Error:
Something went wrong installing the "sharp" module

The specified module could not be found.
\\?\C:\Users\GeeiKa.com\geebot\node_modules\whatsapp-web.js\node_modules\sharp\b
uild\Release\sharp-win32-x64.node

Possible solutions:
- Install with the --verbose flag and look for errors: "npm install --ignore-scr
ipts=false --verbose sharp"
- Install for the current runtime: "npm install --platform=win32 --arch=x64 shar
p"
- Consult the installation documentation: https://sharp.pixelplumbing.com/instal
l
    at Object.<anonymous> (C:\Users\GeeiKa.com\geebot\node_modules\whatsapp-web.
js\node_modules\sharp\lib\sharp.js:30:9)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\GeeiKa.com\geebot\node_modules\whatsapp-web.
js\node_modules\sharp\lib\constructor.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
