### ISSUE TITLE
Is there an option to allow parsing of external entities with SVG ?

### ISSUE THREAD

**Issue by Anatharr** [lovell/sharp#3025]
### What are you trying to achieve?
I need to transform an image from SVG to PNG, resolving an external entity pointing to a web server. It seems like only internal entities are resolved. Is there a way to allow external entities ?
I am aware that it could lead to XXE injection and I am taking a lot of precaution while doing it.

### Have you searched for similar questions?
Yes

### Are you able to provide a minimal, standalone code sample that demonstrates this question?
```js
const sharp = require("sharp")

const svgFile = `
  <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
  <!DOCTYPE svg [
    <!ENTITY test1 "This is test 1">
    <!ENTITY test2 SYSTEM "http://localhost/test">
  ]>
  <svg width="256px" height="256px" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">
    <text font-size="16" x="0" y="16">&test1;</text>
    <text font-size="16" x="0" y="16">&test2;</text>
  </svg>
`.trim()

sharp(Buffer.from(svgFile))
  .png()
  .toFile("new-file.png")
  .then(function(info) {
    console.log(info)
  })
  .catch(function(err) {
    console.log(err)
  })
```

With http://localhost/test returning the following result:
```
$ curl http://localhost/test
This is test 2
```

The above code gives an error :
```
[Error: Input buffer has corrupt header: glib: XML parse error: Error domain 1 code 26 on line 8 column 46 of data: Entity 'test2' not defined


]
```

But if I remove `<text font-size="16" x="0" y="16">&test2;</text>` everything works as intended.

Thanks in advance !

**Comment by lovell** [comment]
The short answer is no, the long answer is also no, you'll have to resolve external entities yourself.

**Comment by Anatharr** [comment]
All right I will find another way then, thank you for your response.
