### ISSUE TITLE
Changing pixel value seems cumbersome?

### ISSUE THREAD

**Issue by erikpols** [lovell/sharp#3026]
This is either a question or a feature request;

What are you trying to achieve?

change the value of 1 pixel

I have a situation where I need to keep a map of something. I'm using sharp for this, since the uncompressed map would be very large. dimensions are 5000x5000 pixels sometimes. The map is updated quite regularly through user interaction. 

Have you searched for similar questions?

yes. the accepted solution seems to be to get the image to raw, then to a buffer, and then navigate to the correct offset in the buffer, then create a new image out of the modified buffer.  This seems very cumbersome when doing it. I would assume its also pretty slow, given that I just want to change 1 small value in memory.

Isn't there some kind of function like this? If there isn't, what the reason that that is not there?

image.setPixelAt(0,0, xFFFFFF)

Are you able to provide a minimal, standalone code sample that demonstrates this question?

sure, but im sure you get the point.

Are you able to provide a sample image that helps explain the question?

**Comment by lovell** [comment]
Have you tried compositing a 1x1 image at a given `top` and `left` position with a blend of `source`?

https://sharp.pixelplumbing.com/api-composite

```js
await sharp(input)
  .composite([{
    input: {
      create: {
        width: 1,
        height: 1,
        channels: 3,
        background: 'white'
      }
    },
    blend: 'source'
  }])
  .toBuffer()
```

**Comment by erikpols** [comment]
That is a little bit better, thank you. 

I also sometimes need to get the value for a pixel. Would you know a better way to do that than exporting the whole image to a buffer? Like so: 

image.getPixel(x,y)

Still wondering why there wouldn't be a shortcut function for this though? Seems a very common and simple thing to do

**Comment by lovell** [comment]
The `extract` operation, with a `width` and `height` of `1`, will allow you to select a single pixel of your choice.
 
https://sharp.pixelplumbing.com/api-resize#extract

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
