### ISSUE TITLE
Global libvips version does not get detected

### ISSUE THREAD

**Issue by tastnt** [lovell/sharp#3031]
I am trying to use the globally installed libvips with sharp, but it does not get detected during the npm install.

Dockerfile:
```Dockerfile
FROM alpine:3.15
WORKDIR /usr/src/app
RUN apk --update add nodejs=~16 npm build-base vips vips-dev
RUN pkg-config --modversion vips-cpp
RUN npm install --build-from-source --verbose sharp
```

Relevant parts from the console logs:
```
...
Step #0: Step 4/8 : RUN pkg-config --modversion vips-cpp
Step #0:  ---> Running in 9b8cfaddb573
Step #0: 8.12.1
...
Step #0: npm info run sharp@0.29.3 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
Step #0: npm info run sharp@0.29.3 install { code: 0, signal: null }
Step #0: npm timing build:run:install:node_modules/sharp Completed in 19607ms
Step #0: npm timing build:run:install Completed in 19608ms
...
```

It works if I follow the instructions described in this [issue](https://github.com/lovell/sharp/issues/2901), however, it uses an older version of sharp (0.28.0), alpine (3.14) and node (14).

What could be the reason that the globally installed libvips is not getting detected?

**Comment by lovell** [comment]
I cannot reproduce this. Please remember that the latest version of `npm` minimises install-time output, which even includes native module compilation.

Here are the commands I'm running inside a container spawned via `docker run -it --rm alpine:3.15`

```
# apk --update add nodejs=~16 npm build-base vips vips-dev
...
# pkg-config --modversion vips-cpp
8.12.1
# npm install --build-from-source --verbose sharp
...
npm info run sharp@0.29.3 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm info run sharp@0.29.3 install { code: 0, signal: null }
...
# ls -al node_modules/sharp/vendor
ls: node_modules/sharp/vendor: No such file or directory
# node -p "require('sharp').versions"
{ vips: '8.12.1' }
```

The output of `sharp.versions` includes only `vips`, which means that it's using the globally-installed version rather than prebuilt (plus you'll note the `vendor` directory is also missing).

**Comment by tastnt** [comment]
Thank you very much for the super-quick response. Hm, okay, I get the same result:
```
Step #0: Step 7/10 : RUN node -p "require('sharp').versions"
Step #0:  ---> Running in 66d205eee29e
Step #0: { vips: '8.12.1' }
```
I was expecting the `sharp: Detected globally-installed libvips...` message, so thanks for the explanation that the latest `npm` suppresses this. However, the other reason why I assumed that it did not work was because I am getting the error message `Error: Input buffer contains unsupported image format` when trying to process [this EXR file](https://storage.googleapis.com/cm-platform-prod-media/BxTDA54neqJ5quzNHRPAI4xf5NmzU5gBjuzwotJmydTjheKPqkdAsH83P3Ky76mEilNyf5NeXM8QtGUAdQuYW05nYKHLNRneBIvMQX2UAzni5BcOO08OwFe6jLwuWGUp).

The main reason I need the globally installed libvips is to be able to process EXR files. Based on [the package description](https://pkgs.alpinelinux.org/package/v3.15/community/x86_64/vips) the build should contain OpenEXR. Why do you think I still get the above error message?

**Comment by lovell** [comment]
libvips only supports opening EXR files via the filesystem, which I think is due to a limitation of OpenEXR.

The provided image works for me using the same container.
```
# node -e "require('sharp')('in.exr').metadata(console.log)"
null {
  format: 'exr',
  width: 2656,
  height: 2784,
  space: 'scrgb',
  channels: 4,
  depth: 'float',
  isProgressive: false,
  hasProfile: false,
  hasAlpha: true
}
```
```
# node -e "require('sharp')('in.exr').toFile('out.png').then(console.log)"
{
  format: 'png',
  width: 2656,
  height: 2784,
  channels: 4,
  premultiplied: false,
  size: 9235484
}
```

**Comment by tastnt** [comment]
Opening and converting EXR files is all what I am looking for. I get the same results as you running your commands above. I have found out that the error only comes up if I read the file into a buffer first (what I have been trying all the time):
```node
var fs = require("fs");
var sharp = require("sharp");
var data = fs.readFileSync("in.exr");
sharp(data).metadata(console.log);
// [Error: Input buffer contains unsupported image format]
```

Is there something wrong with this approach? 🤔

**Comment by lovell** [comment]
Did you see my comment above?

> libvips only supports opening EXR files via the filesystem

**Comment by tastnt** [comment]
Oh, for some reason I read your comment with emphasis on _opening_ (and not writing) instead of on _via the filesystem_. Okay, this explains everything then. I was looking for the solution at the wrong place all the time. Thank you very much for your help, Lovell.
