### ISSUE TITLE
Irregular masks in the image

### ISSUE THREAD

**Issue by siraisisatoru** [lovell/sharp#3032]
What are you trying to achieve?

Hello, I am writing an image processing script for my blog. I realised one of the [past issues](https://github.com/lovell/sharp/issues/1518) in this repo and commented with a related image but seems I can not reopen that issue. 

I originally want to implement a blurry function for multiple rectangular sections of the image but I think it is more important to understand on implement masks with irregular shapes. I initially implemented a similar version as [your responses](https://github.com/lovell/sharp/issues/1518#issuecomment-449487853) but kind of different.

1. When I tried to implement the blurry function, there will occur an extra 'double blurry' if two sections were overlayed. Is it possible to implement such multiple rectangular masks without overlay section issues?

2. Is it possible to implement the polygonal (or irregular) shape instead of the rectangular shape of blur masks? 

3. Apart from the blurring function, is it possible to have multiple polygonal (or irregular) shapes for colour filters? 

Have you searched for similar questions?

Yes, as mentioned above.

Are you able to provide a sample image that helps explain the question?

The overlay effect is show in the following example:

![IMG_0643_20fe32ec3](https://user-images.githubusercontent.com/37771374/145398033-3c1e9073-74de-4442-bd60-b63aa47ec121.jpg)
The blur rectangle has the same width and same height but the second one shifts to the right and below a bit for illustrating the overlay section. 

Your work is awesome and works fine for my project. I appreciate your work.
[This is my source code](https://github.com/siraisisatoru/hexo-sharp-script/blob/main/render/static.js) for your reference. I want to apologize if you indeed received the notifications and I duplicated this issue.

**Comment by lovell** [comment]
Perhaps try using an SVG for this. This will be something like embedding the JPEG image, creating a transparent path (of any shape) to be blurred, then applying an feGaussianBlur filter to that path.

**Comment by siraisisatoru** [comment]
@lovell Thank you for the quick response. That seems executable and answer my confusion in the past months. I will reopen this issue if  I get any further questions.
