### ISSUE TITLE
npm install doesn't work, optimized-images-loader has outdated dependency

### ISSUE THREAD

**Issue by Hisashin7331** [lovell/sharp#3033]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?
Yes

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?
Yes

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
Yes

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?
npm timing build:link Completed in 32ms
npm info run sharp@0.29.3 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm info run sharp@0.25.4 install node_modules/optimized-images-loader/node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
npm info run sharp@0.25.4 install { code: 1, signal: null }
npm info run sharp@0.29.3 install { code: 1, signal: null }
npm timing reify:rollback:createSparse Completed in 2279ms
npm timing reify:rollback:retireShallow Completed in 0ms
npm timing command:install Completed in 27050ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
npm verb stack     at ChildProcess.emit (node:events:390:28)
npm verb stack     at maybeClose (node:internal/child_process:1064:16)
npm verb stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm verb pkgid sharp@0.25.4
npm verb cwd /home/hisashin/Projects/iprzygoda
npm verb Linux 5.11.0-43-generic
npm verb argv "/snap/node/5645/bin/node" "/usr/local/bin/npm" "install" "--verbose" "sharp"
npm verb node v16.13.1
npm verb npm  v8.3.0
npm ERR! code 1
npm ERR! path /home/hisashin/Projects/iprzygoda/node_modules/optimized-images-loader/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
npm verb exit 1
npm timing npm Completed in 27248ms
npm verb unfinished npm timer reify 1640884092066
npm verb unfinished npm timer reify:build 1640884116399
npm verb unfinished npm timer build 1640884116406
npm verb unfinished npm timer build:deps 1640884116406
npm verb unfinished npm timer build:run:install 1640884116491
npm verb unfinished npm timer build:run:install:node_modules/sharp 1640884116491
npm verb unfinished npm timer build:run:install:node_modules/optimized-images-loader/node_modules/sharp 1640884116538
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hisashin/.npm/_logs/2021-12-30T17_08_11_869Z-debug-0.log

What is the output of running `npx envinfo --binaries --system`?
  System:
    OS: Linux 5.11 elementary OS 6.1 Jólnir
    CPU: (16) x64 AMD Ryzen 7 1800X Eight-Core Processor
    Memory: 3.77 GB / 15.56 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh

After deleting node_modules and package-lock.json I get this error.
npm ERR! code 1
npm ERR! path /home/hisashin/Projects/iprzygoda/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hisashin/.npm/_logs/2021-12-30T17_05_55_233Z-debug-0.log

And the log is:
12178 verbose npm  v8.3.0
12179 error code 1
12180 error path /home/hisashin/Projects/iprzygoda/node_modules/sharp
12181 error command failed
12182 error command sh -c (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
12183 verbose exit 1
12184 timing npm Completed in 90029ms
12185 verbose unfinished npm timer reify 1640883955418
12186 verbose unfinished npm timer reify:build 1640884042746
12187 verbose unfinished npm timer build 1640884042752
12188 verbose unfinished npm timer build:deps 1640884042753
12189 verbose unfinished npm timer build:run:install 1640884042839
12190 verbose unfinished npm timer build:run:install:node_modules/sharp 1640884042839
12191 verbose code 1
12192 error A complete log of this run can be found in:
12192 error     /home/hisashin/.npm/_logs/2021-12-30T17_05_55_233Z-debug-0.log

**Comment by lovell** [comment]
> npm info run sharp@0.29.3 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
> npm info run sharp@0.25.4 install node_modules/optimized-images-loader/node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)

It looks like you're trying to install two different versions of sharp, one of which is out of date.

You may need to upgrade or remove the `optimized-images-loader` dependency, and it looks like others are running into a similar problem - please see https://github.com/cyrilwanner/optimized-images-loader/issues/37

**Comment by Hisashin7331** [comment]
But I don't even have sharp or optimized-images-loader in my package.lock, maybe it is a react or nextjs dependency? How could I change without node-modules? I ran `npm i --ignore-scripts` and it worked, but doesn't it affect badly on my project? I ran `npm run dev` and I think everything worked properly.

**Comment by Hisashin7331** [comment]
Additionally, `npm install sharp` displays problem in path `/node_modules/optimized-images-loader/node_modules/sharp`, but installing any other library like react or idk emotion displays problem in path `/node_modules/sharp`

**Comment by lovell** [comment]
Perhaps you have a globally-installed package with an out-of-date dependency? What is the output of `npm ls -g sharp`?

**Comment by Hisashin7331** [comment]
nothing, I've never installed sharp XD

**Comment by lovell** [comment]
What is the output of running `npm ls sharp` in the `/home/hisashin/Projects/iprzygoda` directory?

**Comment by fabiopagoti** [comment]
I just had the same error when doing a `yarn install` on [https://github.com/Coding-Coach/coding-coach](https://github.com/Coding-Coach/coding-coach).

fabio@ubuntu:/storage/dev/coding-coach/coding-coach$ npm ls sharp
coding-coach-blog@0.1.0 /storage/dev/coding-coach/coding-coach
├─┬ gatsby-plugin-manifest@2.2.4
│ └── sharp@0.22.1
├─┬ gatsby-plugin-sharp@2.2.10
│ └── sharp@0.22.1 deduped
└─┬ gatsby-transformer-sharp@2.2.6
  └── sharp@0.22.1 deduped

**Comment by Hisashin7331** [comment]
`@aexol/next-js-starter@0.0.0 /home/hisashin/Projects/iprzygoda
└─┬ optimized-images-loader@0.4.0
  └── sharp@0.25.4`

days after `npm install --ignore-scripts` it looks like this

**Comment by lovell** [comment]
Thanks, this says that the `@aexol/next-js-starter` project/app has a dependency on `optimized-images-loader`, which has an outdated dependency on `sharp` v0.25.4.

The issue I previously linked to at https://github.com/cyrilwanner/optimized-images-loader/issues/37 is probably what you need to get fixed.

If you're using the `--ignore-scripts` flag, please ensure it is set to `false` i.e. `--ignore-scripts=false`.
