### ISSUE TITLE
Does Sharp not support basic bitmap files?

### ISSUE THREAD

**Issue by ljoy913** [lovell/sharp#3035]
What are you trying to achieve?
`Import a bitmap (.bmp) file to a buffer.`

Have you searched for similar questions?
`Yes, and found various similar failures online where the installation was questioned which implied support, but nothing was ever resolved beyond user error`

Are you able to provide a minimal, standalone code sample that demonstrates this question?
```
# sharp installs without issue.  canvas is not installed.  this is a clean install of Ubuntu 20 - which I created after getting the same error on a windows machine.
import sharp from 'sharp';
sharp('./test.bmp').toBuffer()
.then((buffer)=>{
    console.log('success');
})
.catch((error)=>{
    console.log(`fail ${error}`);
    // fail Error: Input file contains unsupported image format
});
```
Are you able to provide a sample image that helps explain the question?
`Pretty much any bitmap I have tried. (github doesn't allow me to attach a bitmap here)`

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/806 specifically https://github.com/lovell/sharp/issues/806#issuecomment-419661745

**Comment by ljoy913** [comment]
Thanks for the timely reply.  

For others that may just want to import a standard 24-bit bmp file into sharp without an additional bmp library, you can do something like this:
```
import fs from 'fs'
import sharp from 'sharp'

function importBmp24(filePath: string): sharp.Sharp {

    // open bmp file, create DataView to access headers properties & data, do rudimentary validation of bitmap structure
    const buff = fs.readFileSync(filePath);
    let dv = new DataView(buff.buffer, buff.byteOffset, buff.byteLength);
    if (buff.toString('ascii', 0, 2) !== 'BM' || dv.getUint32(2, true) !== fs.statSync(filePath).size) throw new Error('invalid bitmap');

    return sharp(
        // bitmap pixels are stored as BGR in rows from bottom to top. 'reverse()' fixes pixels to RGB and rows from top to bottom
        // the flop() is needed to correct the resulting horizontal flip.
        // a copy of the buffer with slice(0) is required because sharp ignores the byteOffset and byteLength properties of the buffer.
        (new Uint8Array(buff.buffer, buff.byteOffset + dv.getUint32(10, true) /*pixel offset*/, dv.getUint32(34, true)) /*data size*/).reverse().slice(0),
        { raw: { width: dv.getUint32(18, true) /*width*/, height: dv.getUint32(22, true) /*height*/, channels: 3 } }
    )
    .flop()
    .ensureAlpha();
}}

```

**Comment by lovell** [comment]
Glad to hear you worked it out, thanks for the update. The BGR to RGB conversion can also be achieved using the `recomb` operation - see https://github.com/lovell/sharp/issues/2171#issuecomment-616806979

**Comment by tx0c** [comment]
but if a solution is so simple, why can't include this logic into sharp?
