### ISSUE TITLE
Excessive memory usage, extremely slow

### ISSUE THREAD

**Issue by xtremeqg** [lovell/sharp#3039]
> Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

Yes (0.29.3).

> What are the steps to reproduce?

Resize image atlas by individually resizing each sub-image.

> What is the observed behavior?

After about 5 minutes only 10 of the 50 or so images had been converted. Script had to be terminated as it ate through 16 gigs of ram making my system very unhappy.

> What is the expected behavior?

Folder containing neatly resized images within some reasonable time frame.

> Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

```
const input_image = await sharp(input_filename);
const metadata = await input_image.metadata();
const horizontal_tiles = metadata.width / 16;
const vertical_tiles = metadata.height / 16;
const output_image = await sharp({create: {
	width: horizontal_tiles * 24,
	height: vertical_tiles * 24,
	channels: metadata.channels,
	background: metadata.background || { r: 0, g: 0, b: 0, alpha: 0 },
}});
const tiles = [];
for (let tx = 0; tx < horizontal_tiles; tx++) {
	for (let ty = 0; ty < vertical_tiles; ty++) {
		const tile = input_image.clone().extract({
			left: tx * 16,
			top: ty * 16,
			width: 16,
			height: 16,
		});
		tile.resize({ width: 24, height: 24 });
		tiles.push({
			input: await tile.toBuffer(),
			left: tx * 24,
			top: ty * 24,
			gravity: "northwest",
		});
	}
}
output_image.composite(tiles);
await output_image.toFile(output_filename);
```

> Are you able to provide a sample image that helps explain the problem?

No, but the issue is reproducible with any image.

> What is the output of running `npx envinfo --binaries --system`?

I'm not sure this is relevant.

> Other information

The images in question had maximum input dimensions of 512x512, 24-bit color depth with some having alpha channels. The output image would be 50% larger with the same color depth and alpha channel. Doing the math, no more than (`input dimensions` + `output dimensions`) x `bytes per pixel` x `image count` = (512 x 512 + 768 x 768) x 4 x 50 = 170 megs of memory should have been used yet somehow this library is using several orders of magnitude more. I suspect that extract isn't very smart and ends up loading the same source image a thousand times over and composite is calling getpixel / setpixel like its 1985.

It could be that I'm using this "High Performance" library wrong so I'm open to suggestions. Meanwhile, I'll remove the dependency and write my own image conversion routines. There's no way that something this trivial takes that long and consumes that much memory.

**Comment by xtremeqg** [comment]
Was able to perform the same operation on all 50 images in just a few seconds, ~100 megs of ram and fewer lines using the [canvas](https://github.com/Automattic/node-canvas) library:
```
const input_image = await canvas.loadImage(input_filename);
const horizontal_tiles = input_image.width / 16;
const vertical_tiles = input_image.height / 16;
const output_image = canvas.createCanvas(horizontal_tiles * 24, vertical_tiles * 24);
const ctx = output_image.getContext("2d");
for (let tx = 0; tx < horizontal_tiles; tx++) {
	for (let ty = 0; ty < vertical_tiles; ty++) {
		ctx.drawImage(input_image, tx * 16, ty * 16, 16, 16, tx * 24, ty * 24, 24, 24);
	}
}
await write_file(output_filename, output_image.toBuffer("image/png"));
```

Again, if I was using the sharp library the wrong way I would love to know what I did wrong.

**Comment by lovell** [comment]
This scenario looks like the sort of thing that #1580 will provide a dedicated API for.

**Comment by lovell** [comment]
I hope this information helped. Please subscribe to #1580 for updates.
