### ISSUE TITLE
Channels value inconsistent between metadata() and toBuffer() (resolveWithObject)

### ISSUE THREAD

**Issue by bneigher** [lovell/sharp#3041]
I am trying to understand why the channels (and probably generally the values from info) are not the same between calls from Sharp's `metadata()` and `toBuffer()` calls.  I'm assuming that the `.toBuffer()` is essentially coercing the raw values to RGB... but this is not desired behavior.

Attached below is a 1 channel file

```javascript
const Sharp = require("sharp");

(async () => {
  const file = "./1_tile.jpg"
  const meta = await Sharp(file).metadata()
  console.log(meta);
  const { data, info } = await Sharp(file).withMetadata().toBuffer({ resolveWithObject: true })
  console.log(info);
  console.log(meta.channels === info.channels);
})();
```

meta.channels = 1
info.channels = 3

![1_tile](https://user-images.githubusercontent.com/4627728/149419303-da818465-f833-433b-8b42-f0d933d4065d.jpg)

**Comment by lovell** [comment]
Hi, the default output is 3 channel sRGB. For 1 channel output add `.toColorspace("b-w")`:

```diff
-  const { data, info } = await Sharp(file).withMetadata().toBuffer({ resolveWithObject: true })
+  const { data, info } = await Sharp(file).withMetadata().toColorspace("b-w").toBuffer({ resolveWithObject: true })
```
https://sharp.pixelplumbing.com/api-colour#tocolourspace

**Comment by bneigher** [comment]
@lovell understood.  Does using `toColorspace("b-w")` imply we already know the image is NOT 1 channel?  My use case is determining the color channel to later operate differently if we're dealing with 1 channel, 2 channel, ect.  

To take a step out here, I'm trying to accomplish one call to both get the image buffer AND determine how many channels the image has.  From what I understand so far - the only way to accomplish this is by calling `metadata()`, and then calling `toBuffer` with `toColorspace` (with the appropriate arg).

Want to also say this is an awesome library - thank you for making this

**Comment by lovell** [comment]
What you describe sounds correct. The `metadata()` call is usually very fast as it does not decompress any pixel values.
