### ISSUE TITLE
Custom filter [Box filter] - very slow. Is there a better approach to aggregate pixel manipulation?

### ISSUE THREAD

**Issue by bneigher** [lovell/sharp#3042]
What are you trying to achieve?
> I'm trying to write my own image filter - as the selection provided by sharp and written in the underlying core libs don't let me accomplish my own algorithm.  Doing so (shown below) is quite slow on large images even though I am not using any additional space complexity and I believe this specific algorithm can't leverage any memoizing or any dynamic programming / pre-computation.

Have you searched for similar questions?
> Yes

Are you able to provide a minimal, standalone code sample that demonstrates this question?
> The following code should perform a Box Filter (or Average Filter) on the image (type of blur) that averages a the rgb values independently via a sliding window (3x3).  This filter is not to be confused with the [Median Filter](https://sharp.pixelplumbing.com/api-operation#median) [which is a supported method].  Because we are given the pixel values in a 1D array where each pixel is a slice of the array (i, i + numChannels) as this should support N channels.

```javascript
const Sharp = require('sharp');
// Helper function determining bounds of flat 2D matrix
const calculateIndex = (row, column, width, height, channels) => {
  if (row >= 0 && row < height && column >= 0 && column < width) return ((row * width) + column) * channels;
  return -Infinity;
}

try {
  const file = "./image.jpg"
  const info = await Sharp(file).metadata()
  const data = await Sharp(file).raw().toBuffer()

  const pixelArray = new Uint8ClampedArray(data);
  const filteredArray = Uint8ClampedArray.from({ length: pixelArray.length }).fill(0)
  const { channels, height, width } = info;

  for (let i = 0; i < pixelArray.length; i = i + channels) {
    const row = Math.floor((i / channels) / (width));
    const column = Math.floor((i / channels) % (width));
    for (let rgb = 0; rgb < channels; rgb++) {
      let topLeft = topCenter = topRight = left = center = right = bottomLeft = bottomCenter = bottomRight = -1
      topLeft = calculateIndex(row - 1, column - 1, width, height, channels) + rgb;
      topCenter = calculateIndex(row - 1, column, width, height, channels) + rgb;
      topRight = calculateIndex(row - 1, column + 1, width, height, channels) + rgb;
      left = calculateIndex(row, column - 1, width, height, channels) + rgb;
      center = i + rgb;
      right = calculateIndex(row, column + 1, width, height, channels) + rgb;
      bottomLeft = calculateIndex(row + 1, column - 1, width, height, channels) + rgb;
      bottomCenter = calculateIndex(row + 1, column, width, height, channels) + rgb;
      bottomRight = calculateIndex(row + 1, column + 1, width, height, channels) + rgb;

      // Calculates average pixel value, accounting for less neighbors on corners or edges of the image
      const sumInstructions = [topLeft, topCenter, topRight, left, center, right, bottomLeft, bottomCenter, bottomRight].reduce((acc, idx) => {
        const valid = Number.isInteger(pixelArray[idx]);
        if (valid) acc = [acc[0] + pixelArray[idx], acc[1]+1];
        return acc;
      }, [0, 0])
      filteredArray[i + rgb] = Math.floor(sumInstructions[0] / sumInstructions[1])
    }
  }

  const outputBuffer = await Sharp(filteredArray, { raw: { width, height, channels }})
    .toFormat(info.format)
    .withMetadata()
    .toBuffer();    

  return {
    data: outputBuffer,
    channels: info.channels >= 3 ? true : false,
    width: info.width,
    height: info.height,
  }
} catch (error) {
  console.error(error);
  throw error
}

```

Are you able to provide a sample image that helps explain the question?
> N/A

**Comment by lovell** [comment]
This looks like it might have the same effect as the 3x3 convolution matrix used for the parameter-less `blur()` operation.

https://sharp.pixelplumbing.com/api-operation#blur

https://github.com/lovell/sharp/blob/1ff84b20b7d9b351786fb06899255cea59aa123c/src/operations.cc#L133-L139

You could also use `convolve()` to define your own kernel.

https://sharp.pixelplumbing.com/api-operation#convolve

https://en.wikipedia.org/wiki/Kernel_(image_processing)

**Comment by lovell** [comment]
I added a note about this to the docs - see https://github.com/lovell/sharp/commit/638d540371f2808c519e6a7d9f23c31392dd7e80
