### ISSUE TITLE
Error: Input image exceeds pixel limit even with limitInputPixels false

### ISSUE THREAD

**Issue by Drjacky** [lovell/sharp#3045]
**What are you trying to achieve?**  
To convert a jpeg to a progressive jpeg

**Have you searched for similar questions?**  
Yes: https://github.com/lovell/sharp/issues/2683

Are you able to provide a minimal, standalone code sample that demonstrates this question?
```javascript
const sharp = require("sharp")

const main = async () => {
    try {
        const data = await sharp('/Users/i1.jpg', {limitInputPixels: false})
            .jpeg({
                quality: 100, // adjust the quality
                progressive: true,
            })
            .toBuffer();
        await sharp(data).toFile('/Users/i2-progressive.jpg')
    } catch (error) {
        console.log(error)
    }
}

main()
```

**Comment by lovell** [comment]
Did you intend to also set `limitInputPixels` on the second invocation?

```diff
- await sharp(data).toFile('/Users/i2-progressive.jpg')
+ await sharp(data, { limitInputPixels: false }).toFile('/Users/i2-progressive.jpg')
```

If you're still having problems, please can you provide a sample image that exhibits this behaviour.
