### ISSUE TITLE
combine channels and give new image

### ISSUE THREAD

**Issue by lokeshtejavath** [lovell/sharp#3046]
What are you trying to achieve?
I'm working on an image steganography service using node, I want to change pixel data in one of the channels and combine it with the rest of the channels to create a new image

Have you searched for similar questions?
Yes, I've searched. All could find was resizing and all.

Are you able to provide a minimal, standalone code sample that demonstrates this question?
```shell
async function getMetaData() {
    const red = await sharp("./images/loki.jpeg").extractChannel("red").raw().toBuffer();
    //orginal red[1] = 143
    red[1] = 150;
    // i want to change this value to 150 for now but in acutal project it will be changed based on message to be put on the image
    
    
}
````

**Comment by lovell** [comment]
This feels a bit like a homework question...

To achieve what you describe, I'd probably convert all channels to raw, then modify, then read back in again. The following example (untested) assumes 3 channel RGB.

```js
const { width, height } = await sharp('input.jpg').metadata();
const pixels = await sharp('input.jpg').raw().toBuffer();
pixels[0] = ...; // first red pixel
pixels[3] = ...; // second red pixel
// etc
await sharp(pixels, { raw: { width, height, channels: 3 } }).toFile('output.jpg');
```

Please note that JPEG compression is lossy so this may not do what you expect.

**Comment by lokeshtejavath** [comment]
Thank you so much for helping me out.

And also yes sir, I've accounted for the JPEG compression is lossy and I've work around for that by saving image in PNG format.

I've already done this project in Python as desktop application, and wanted to use node to extend the functionality into webapp
[Image Steganography in python](https://github.com/lokeshtejavath/mystiko-minyma)
