### ISSUE TITLE
is a fast path to relayout an image to CHW and convert the data to float in the range [0, 1.0]

### ISSUE THREAD

**Issue by zeeker999** [lovell/sharp#3049]
What are you trying to achieve?
I'd like to convert the layout to CHW  from HWC and the data to float in the range [0, 1.0], and then feed the raw data to a model. I wonder if there is room for improvement in the code below.

Have you searched for similar questions?
Yes

Are you able to provide a minimal, standalone code sample that demonstrates this question?
```javascript
const sh =  sharp('input.jpg')
const r = await sp.extractChannel(0).raw().toBuffer()
const g = await sp.extractChannel(1).raw().toBuffer()
const b = await sp.extractChannel(2).raw().toBuffer()
const data = new Float32Array(width * height * 3)
let offset = 0
for (const channel of [r, g, b]) {
   for (let i = 0; i < width * height; i++, offset++) {
       data[offset] = channel[i] / 255.0
   }
}
```

**Comment by lovell** [comment]
I'm unsure what CHW means - is this a colourspace?

You can reorder channels using the `recomb()` operation - see https://github.com/lovell/sharp/issues/2171#issuecomment-616806979 for an example.

There's a future possible enhancement for raw float output at #681.

**Comment by zeeker999** [comment]
> I'm unsure what CHW means - is this a colourspace?
> 
> You can reorder channels using the `recomb()` operation - see [#2171 (comment)](https://github.com/lovell/sharp/issues/2171#issuecomment-616806979) for an example.
> 
> There's a future possible enhancement for raw float output at #681.
An image with layout [rrrrrrrrrr][ggggggg][bbbbb] instead of [rgbrgbrgbrgb]...[rgbrgbrgbrgb]

**Comment by lovell** [comment]
Thanks for confirming, let's track this future possible enhancement to `raw()` at #681 - I'll close this question.
