### ISSUE TITLE
pngload_buffer: libpng read error on partical png

### ISSUE THREAD

**Issue by lukasa1993** [lovell/sharp#3050]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

using `0.29.3`

What are the steps to reproduce?
```await sharp(fs.readFileSync(`test.png`))
      .png()
      .toBuffer()```
What is the expected behaviour?
hopefully to normalise it and draw half baked as it is

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
[test.png.zip](https://github.com/lovell/sharp/files/7887339/test.png.zip)

attaching img as zip so github doesnt parse it

Are you able to provide a sample image that helps explain the problem?
yes

What is the output of running `npx envinfo --binaries --system`?

macos seem to preview it in half so i wonder if its possible to convert this half data to proper png with sharp
![Screenshot 2022-01-18 at 12 21 09](https://user-images.githubusercontent.com/1499012/149898215-25b0d96e-c284-4fc0-96ad-fcc1ba40466c.png)

**Comment by lovell** [comment]
This image is corrupt. You might be able to parse some of it by setting `failOnError` to `false`.

https://sharp.pixelplumbing.com/api-constructor

```js
sharp(input, { failOnError: false })...
```

**Comment by lukasa1993** [comment]
it will output proper png guaranteed right ? regardless what it will parse ?

**Comment by lovell** [comment]
If it's possible to rescue some pixel values then the output will be valid, but what it looks like cannot be guaranteed, and it may not appear the same as macOS and/or other software.

**Comment by lukasa1993** [comment]
> If it's possible to rescue some pixel values then the output will be valid, but what it looks like cannot be guaranteed, and it may not appear the same as macOS and/or other software.

its ok as long as something is visible

**Comment by lukasa1993** [comment]
seems to be solution thanks for quick response
