### ISSUE TITLE
Saving an image as "avif" returns format as "heif"

### ISSUE THREAD

**Issue by AmeyMore98** [lovell/sharp#3053]
Hello,
I'm trying to save the below jpeg images in avif format. 

I've tried these two approaches:
```
const image = sharp("/home/input.jpeg")
await image.avif().toFile("/home/output.avif")
```

```
const image = sharp("/home/input.jpeg")
await image.toFormat("avif").toFile("/home/output.avif")
```

Both of these approaches generate valid avif images, but the `info` object returned by `toFile` has the value 'heif' for `format`. Any idea why this happens? Thanks

Input Images:
![input](https://user-images.githubusercontent.com/13717006/150312715-71f8cb43-5be5-47df-9d0a-3f7cb3842a6e.jpeg)
![input2](https://user-images.githubusercontent.com/13717006/150313467-77a9e33f-7c10-4591-9eb8-4d4e76f07839.jpeg)

Sadly Github doesn't support avif images or else would have shared the outputs too.

**Comment by lovell** [comment]
Hi, this is as expected, the output format is `heif` and this is consistent with the `format` value provided by `metadata()`.

https://sharp.pixelplumbing.com/api-input#metadata

The use of `toFormat('avif')` is an alias for `heif({ compression: 'av1'})`.

https://sharp.pixelplumbing.com/api-output#heif

**Comment by AmeyMore98** [comment]
Cool, that explains it.
Thanks.
