### ISSUE TITLE
trim does not work as expected when using with joinChannel

### ISSUE THREAD

**Issue by deepakgupta191199** [lovell/sharp#3054]
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

Yes

What are the steps to reproduce?
I am trying to apply a b/w mask to an image and trim the transparent area. These are the input image and the mask.
[Image](https://user-images.githubusercontent.com/41531792/150627829-9085ed39-0837-4286-8da5-a6a2174e0fc8.jpg)
[Mask](https://user-images.githubusercontent.com/41531792/150627833-329e720e-4255-4306-8041-8d7783142b2f.png)
This is the code I am using:
```js
const sharp = require('sharp');
const fs = require('fs');

applyMaskAndTrim = async (image, mask) => {
    await sharp(image).joinChannel(mask).trim(10).toFile('output.png');
}

(async () => {
    var imageFile = fs.readFileSync("image.jpg");
    var maskFile = fs.readFileSync("mask.png");

    await applyMaskAndTrim(imageFile, maskFile);
    console.log("Done");
})();
```
What is the expected behaviour?
The expected output should be [Expected Image](https://user-images.githubusercontent.com/41531792/150628261-f52f4d90-bf08-41a5-916a-87439b8087c4.png)
But I get this  [Output Image](https://user-images.githubusercontent.com/41531792/150628341-fdfaf4f8-b968-459a-aa58-247a59b7461e.png)
However I get the correct output when using `joinChannel` and `trim` separately on separate files.

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
See code sample above

Are you able to provide a sample image that helps explain the problem?
See above images

What is the output of running `npx envinfo --binaries --system`?
```
  System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 2.43 GB / 7.83 GB
  Binaries:
    Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
```

**Comment by lovell** [comment]
Hi, yes, you'll need to split these operations into two pipelines, as the trim will always occur first. You might also run into #2166.

**Comment by deepakgupta191199** [comment]
@lovell Thank you for the quick response. 
Is there any other alternative to make the process faster as it adds additional time to encode the image twice.

**Comment by lovell** [comment]
As an intermediate image format, you could use either [raw](https://sharp.pixelplumbing.com/api-output#raw) pixel data or [png](https://sharp.pixelplumbing.com/api-output#raw) with a `compressionLevel` of `0`.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
