### ISSUE TITLE
Overlay multiple GIFs into one GIF file

### ISSUE THREAD

**Issue by jinglescode** [lovell/sharp#3056]
is it possible (if yes, how) to overlay 2 (or more) layers of animated GIFs on a background image (PNG). The GIF files have portions of the image where it has transparent, so lower layers can be seen (such as the background). All the GIFs and the PNG background are of the same size. All GIFs have the same number of frames. 

For example, I have a `sun.gif` file where it has 8 frames, and a `human.gif` has also 8 frames. Both GIFs are animating.
And a `grass.png`, a static image, how can I overlay `human.gif` and `sun.gif` on `grass.png`, so you see a sun and a human animating, on a grass background.

**Comment by newtykins** [comment]
Hey if you still have this issue you could check out how I managed to overlay gifs [on canvas-gif](https://github.com/newtykins/canvas-gif/blob/8fa1751358c9b8ce98df6b2d8063abea8203a91c/src/Gif.ts#L305). Currently all of the FPS values are synced but I'll be fixing that within the next few days. Hopefully this is at least of some use to you, and if you have any questions just give me a shout!

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
