### ISSUE TITLE
Bit depth is changed by Sharp

### ISSUE THREAD

**Issue by doussa2504** [lovell/sharp#3058]
sharp(Buffer.from(image, 'base64'))
    .flatten({background: 'white'})
    .resize(width, height, {
      fit:"cover",
      background:"white"
    })
    .toFormat('png')
    .toBuffer();

with the above code  the bit depth of an image from 2 is transformed  to 24 and I got a much bigger one (size: from 0.5 mb to 4.49 mb). 
How can I do to omit this behavior or at least how can I forecast the size (or bit depth) of the rendered image with the size of the actual one?

**Comment by lovell** [comment]
Hi, did you see https://sharp.pixelplumbing.com/api-output#png ?

For example, setting `colours` to `4` will give you a bit depth of 2.

```js
await sharp(input)
  .png({ colours: 4 })
  .toBuffer();
```

**Comment by doussa2504** [comment]
> Hi, did you see https://sharp.pixelplumbing.com/api-output#png ?
> 
> For example, setting `colours` to `4` will give you a bit depth of 2.
> 
> ```js
> await sharp(input)
>   .png({ colours: 4 })
>   .toBuffer();
> ```

Hi 
yes, I have seen it. In my case, the user can upload many images. It could be jpeg or png and the bit depth could be different for every image. Is it possible to keep the bit depth as it is after rendering the image?

**Comment by lovell** [comment]
Perhaps try something like the following (untested):

```js
const { paletteBitDepth } = await sharp(input).metadata();
const colours = 1 << paletteBitDepth;

const output = await sharp(input)
  .png({ colours })
  .toBuffer();
```

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by tobloef** [comment]
Hello, sorry to re-open this after to long, but this is the first result on google when searching for "sharp bit depth".

It seems that in version `0.32.4` or earlier, the `paletteBitDepth` field was removed. I see that we now have `depth` but that's only the datatype, as far as I understand. How can we get the actual bit depth? Alternatively, how can I make sure my output depth matches my input depth? In my case I'm reading a 32-bit grayscale `.tif` file and I would like to output a similar file.

**Comment by lovell** [comment]
@tobloef `paletteBitDepth` is still present in the `metadata()` response for palette-based images (GIF, some PNGs) but it appears it was missing from the docs, added via https://github.com/lovell/sharp/commit/0bc79cdb953c9c0f1cf9015be65fb231fd5ec520 - however it sounds like you want `depth`, which will probably be `ushort` for 32-bit greyscale (but that's a guess). Please open a new issue if you still require help.
