### ISSUE TITLE
Possible regression in `.resize` with `withoutEnlargement: true` and `fit: sharp.fit.contain`

### ISSUE THREAD

**Issue by medanat** [lovell/sharp#3067]
Hey, after upgrading to 0.30.0 we noticed an issue with the resizing method with `withoutEnlargement: true` and `fit: sharp.fit.contain`. The images are being enlarged despite the `withoutEnlargement` flag. 

The image correctly ignores the new width when `fit: sharp.fit.contain` is removed. Not sure if this is intended behaviour or a regression. I've added the failing test steps below.

Super stoked to see 0.30.0 come out 😄, thanks!

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

Yes

```
 sharp@0.30.0
 0.30.0
 ```

What are the steps to reproduce?

- resize image to a larger width than original with `withoutEnlargement: true` and `fit: sharp.fit.contain`

What is the expected behaviour?

Image width should not grow bigger than original

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?

I've included the test (passing in 0.29.3/failing in 0.30.0)

```
  it('does not make an image bigger', async () => {
    const { readFileSync } = require('fs');
    const sharp = require('sharp');
    const image = readFileSync('image-1.png');

    const { info: { width: originalWidth, height: originalHeight } } = await sharp(image).toBuffer({ resolveWithObject: true });
    const newWidth = originalWidth + 333;
    const { info: { width, height } } = await sharp(image)
      .resize(newWidth, undefined, {
        withoutEnlargement: true,
        fit: sharp.fit.contain
      })
      .toBuffer({ resolveWithObject: true });

    expect(width).to.not.eq(newWidth);
    expect(width).to.eq(originalWidth);
    expect(height).to.eq(originalHeight);
  });
```

Are you able to provide a sample image that helps explain the problem?

![image-1](https://user-images.githubusercontent.com/969646/152117082-73f6f420-b780-468b-a992-278d55b672dd.png)

What is the output of running `npx envinfo --binaries --system`?

```
  System:
    OS: Linux 5.10 Alpine Linux
    CPU: (5) arm64 unknown
    Memory: 2.06 GB / 3.84 GB
    Container: Yes
    Shell: 1.34.1 - /bin/ash
  Binaries:
    Node: 14.18.2 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
```

**Comment by lovell** [comment]
Hi, thanks for reporting, I can reproduce this.

The following patch ensures dimensions are clamped before the decision about embedding (a.k.a. `fit: 'contain'`):

```diff
--- a/src/pipeline.cc
+++ b/src/pipeline.cc
@@ -440,6 +440,14 @@ class PipelineWorker : public Napi::AsyncWorker {
       if (baton->height <= 0) {
         baton->height = inputHeight;
       }
+      if (baton->withoutEnlargement) {
+        if (baton->width > inputWidth) {
+          baton->width = inputWidth;
+        }
+        if (baton->height > inputHeight) {
+          baton->height = inputHeight;
+        }
+      }
 
       // Crop/embed
       if (inputWidth != baton->width || inputHeight != baton->height) {
```
@kleisauke Any possible alternatives you can think of?

**Comment by kleisauke** [comment]
IIUC, the `withoutEnlargement` parameter only specifies that the image itself should not be upsized (which is done correctly in this case).

I think the old behavior was incorrect. If one wants to embed a 768x576 pixel image in a 1101x576 box, it should produce a 1101x576 image (and not a 768x576 image). If no letterboxing/embedding is needed, you can always use `fit: 'inside'`.
```bash
$ node -e "require('sharp')('x.png').resize({ width: 1101, fit: 'contain', background: 'red' }).toFile('x2.png')"
$ vipsheader x2.png
x2.png: 1101x826 uchar, 3 bands, srgb, pngload
$ node -e "require('sharp')('x.png').resize({ width: 1101, withoutEnlargement: true, fit: 'contain', background: 'red' }).toFile('x3.png')"
$ vipsheader x3.png
x3.png: 1101x576 uchar, 3 bands, srgb, pngload
$ node -e "require('sharp')('x.png').resize({ width: 1101, withoutEnlargement: true, fit: 'inside', background: 'red' }).toFile('x4.png')"
$ vipsheader x4.png
x4.png: 768x576 uchar, 3 bands, srgb, pngload
```

**Comment by lovell** [comment]
@kleisauke Thanks Kleis, you're quite right, the previous behaviour doesn't match the documentation.

**Comment by medanat** [comment]
@lovell @kleisauke Thank you both! This was very informative, appreciate the follow-up!

**Comment by kleisauke** [comment]
@lovell In a similar context, I noticed that the current behavior of `withoutReduction: true` doesn't match the documentation. I was able to fix that with commit https://github.com/kleisauke/sharp/commit/26acd0b8c2c4d4d4c389839772c93ce6b5d4bcb3, let me know if you want a PR with that.

**Comment by lovell** [comment]
Good spot, we should fix this sooner rather than later so yes please, PR very welcome.
