### ISSUE TITLE
/var/app/node_modules/sharp/lib/sharp.js:30 throw new Error(help.join('\n'));

### ISSUE THREAD

**Issue by mohammedfellak** [lovell/sharp#3069]
I have sharp issue same as others had posted already
Yarn version: 1.22.17
Node version: v14.17.6
Os: Mac Os

I've tried yarn add sharp, npm install sharp, npm install --verbose sharp, remove cache etc..

Is there any other information i should provide?

The log:
`yarn run v1.22.15
$ nodemon ./bin/www
[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node ./bin/www`
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:245:13
/var/app/node_modules/sharp/lib/sharp.js:30
  throw new Error(help.join('\n'));
  ^

Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-linux-x64.node'
Require stack:
- /var/app/node_modules/sharp/lib/sharp.js
- /var/app/node_modules/sharp/lib/constructor.js
- /var/app/node_modules/sharp/lib/index.js
- /var/app/utils/file-helper.js
- /var/app/controllers/profile.controller.js
- /var/app/controllers/users.controller.js
- /var/app/validators/user.js
- /var/app/validators/index.js
- /var/app/bundles/web-kyc/routes/router.js
- /var/app/app.js
- /var/app/bin/www

Possible solutions:
- Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
- Install for the current runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/var/app/node_modules/sharp/lib/sharp.js:30:9)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/var/app/node_modules/sharp/lib/constructor.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/var/app/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/var/app/utils/file-helper.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
[nodemon] app crashed - waiting for file changes before starting...
ERROR: 1`

**Comment by lovell** [comment]
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7 or later, does the user running `npm install` own the directory it is run in?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

What is the output of running `npx envinfo --binaries --system`?

**Comment by mohammedfellak** [comment]
Have you ensured the architecture and platform of Node.js used for npm install is the same as the architecture and platform of Node.js used at runtime?
`Not sure how to check, but i use docker containers`

Are you using the latest version? Is the version currently in use as reported by npm ls sharp the same as the latest version as reported by npm view sharp dist-tags.latest?
```
It was working without any issues, and then when i pulled latest code it did happen, i tried to install sharp@latest
so, unfortunately i don't know exactly about the two versions that you have mentioned
```

If you are using npm v6 or earlier and installing as a root or sudo user, have you tried with the npm install --unsafe-perm flag? using 6. version
```no but is it safe to installing with that command```

If you are using the ignore-scripts feature of npm, have you tried with the npm install --ignore-scripts=false flag?
```yes, same log```

What is the complete output of running npm install --verbose sharp? Have you checked this output for useful error messages?
here is a snippet:
```https://gist.github.com/mohammedfellak/fd978616595b44ba78564002ebddd4eb```

What is the output of running npx envinfo --binaries --system?
```npx envinfo --binaries --system
npx: installed 1 in 1.347s

  System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 124.85 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
```

**Comment by lovell** [comment]
Did you see https://sharp.pixelplumbing.com/install#cross-platform ?

You'll either need to run `npm install` inside the container, or cross-install for the runtime environment.

```sh
npm install --platform=linux sharp
```

**Comment by mohammedfellak** [comment]
I found that doc little bit complicated to understand, especially the first part
when you say inside the container do you mean using docker-compose command?

also, i ran that command and still on same log

all my other friends doesn't have any issue, except me

**Comment by lovell** [comment]
It looks like you're copying a `node_modules` directory that has been created by running `npm install` on macOS into a Linux container and expecting it to work, which won't be the case.

Your choice is either to not copy the `node_modules` directory and instead create it by running `npm install` within the container, or, if you want to copy the `node_modules` directory between platforms, ensuring it is populated for the runtime platform using the command I provided. In either case you'll need to start over, removing any existing `node_modules` directory.

**Comment by mohammedfellak** [comment]
Sure, i will remove node_modules and run npm install and see
also do you think it matters whether using npm i or yarn add?

**Comment by mohammedfellak** [comment]
It did work this time, Thanks for your great follow up
