### ISSUE TITLE
How do i set bitmap data like Jimp?

### ISSUE THREAD

**Issue by GuckTubeYT** [lovell/sharp#3070]
Hello, how do i set bitmap data like Jimp?
In Jimp `image.bitmap.data.set(bufferImage)`
So, when i set the bitmap data, and then i want to save it to file

Sorry if my grammar is bad

**Comment by lovell** [comment]
Did you see the "Read a raw array of pixels and save it to a png" example at https://sharp.pixelplumbing.com/api-constructor ?

**Comment by GuckTubeYT** [comment]
> Did you see the "Read a raw array of pixels and save it to a png" example at https://sharp.pixelplumbing.com/api-constructor ?

Thanks for the answer @lovell
