### ISSUE TITLE
composite into a 4 vertices polygon

### ISSUE THREAD

**Issue by mariusa** [lovell/sharp#3071]
What are you trying to achieve?
Embed small photo1 into large photo2 which has a frame at an angle
![angle](https://user-images.githubusercontent.com/1283842/152306560-78a589e7-ff11-4130-8cb7-6dd4c4a2470d.jpg)

Have you searched for similar feature requests?
yes

What would you expect the API to look like?
composite() could take a 4 vertices polygon which represents the frame interior area.
Note that opposite borders don't have to be parallel.

What alternatives have you considered?
don't know other alternatives

Is there a sample image that helps explain?
![Side-Photo-of-Oil-Pinting](https://user-images.githubusercontent.com/1283842/152306907-993649a9-edb7-4a0e-b816-bc4e8481b116.jpg)

Any suggestions on how to accomplish this?
Thank you!

**Comment by lovell** [comment]
3 point [affine transformation](https://en.wikipedia.org/wiki/Affine_transformation), yes, please see https://sharp.pixelplumbing.com/api-operation#affine

4 point projection, no. It might be possible to achieve this with some of the new features of SVG, but you'll have to wait for #2884

**Comment by mariusa** [comment]
Thanks for clarification! Now that I know what to search for, I see this already requested in #2388 and #2095
Closing and following those.
