### ISSUE TITLE
detectLibc.isNonGlibcLinuxSync is not a function

### ISSUE THREAD

**Issue by tgrades** [lovell/sharp#3072]
Hi.

New 0.30 version produces this error in aws labmda env

```
{
    "errorType": "TypeError",
    "errorMessage": "detectLibc.isNonGlibcLinuxSync is not a function",
    "stack": [
        "TypeError: detectLibc.isNonGlibcLinuxSync is not a function",
        "    at module.exports (/opt/nodejs/node_modules/sharp/lib/platform.js:11:52)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/sharp/lib/libvips.js:23:80)",
        "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
        "    at Module.require (internal/modules/cjs/loader.js:974:19)",
        "    at require (internal/modules/cjs/helpers.js:93:18)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/sharp/lib/constructor.js:7:1)",
        "    at Module._compile (internal/modules/cjs/loader.js:1085:14)"
    ]
}
```

The reason is this change
https://github.com/lovell/sharp/commit/884947a0697b02bea3ef8e6b2c23b147ebba17a7#diff-69c8555fe1714c34d62f83b86f2040c16df16047cc5887d5b903ca7e610108c6R11

I will downgrade for now. But can someone elaborate what is happening here and why it is changed.
AWS lambda system is very lightweight, so I assume it's missing something?

**Comment by lovell** [comment]
Are you sure that detect-libc v2.0.0 was installed and deployed as a dependency of sharp?

Please make sure you're not pinning any dependencies to older versions, e.g. in a lockfile or via `overrides`.

**Comment by tgrades** [comment]
@lovell Thank you for a quick response. I have two lambda layers. And apparently 1 of them has old `detect-libc`. I will try to fix this and see if it helps.

**Comment by tgrades** [comment]
@lovell Everything works! 🙌 Thank you for your help and sorry for the inconvenience.
