### ISSUE TITLE
Possible to reduce GIF framerate?

### ISSUE THREAD

**Issue by holic** [lovell/sharp#3075]
I've dug through the docs and past issues but haven't seen anything related, but still gonna mark this as a "question" rather than "feature request" for now.

I'd like to take an existing GIF and reduce its framerate. I could see this coming in a few flavors:
- allow me to specify which pages get included in the output
- allow me to specify a framerate, which does the above and increase delay to compensate for reduced frames

**Comment by lovell** [comment]
Hi, did you see the `delay` option of [gif](https://sharp.pixelplumbing.com/api-output#gif)?

**Comment by holic** [comment]
Yep! Delay can add time between frames, but I’m looking to remove frames too. I want the visual speed and total time of the animation to remain the same but less frame rate. Adding delay just keeps the number of frames and slows the animation down.

**Comment by lovell** [comment]
You'll need to extract individual frames and create a new image from them.

To extract one frame/page use the zero-indexed `page` parameter on the constructor, e.g.
```js
sharp(animatedGifInput, { page: 2 })...
```

To create a new animated image from a series of frames, you'll probably want the future possible enhancement at #1580

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
