### ISSUE TITLE
Composite blend parameters like clear, source not working as expected.

### ISSUE THREAD

**Issue by g-abhishek** [lovell/sharp#3076]
What are you trying to achieve?
I am trying to have blend transformation, which is one of the property of composite api, for my image transformation and stucked in a output which is different than given in the [cairographics.org](https://www.cairographics.org/operators/) website

Have you searched for similar questions?
Yes, but didn't got any solution

Are you able to provide a minimal, standalone code sample that demonstrates this question?
```
try {
    await sharp("largeImage.jpeg")
      .composite([
        {
          input: "small.jpeg",
          gravity: “center”,
          blend: “clear”, // source, dest-out, etc
        },
      ])
      .toFile(“output.jpeg”);
  } catch (error) {
    console.log(error);
  }
}
```

Are you able to provide a sample image that helps explain the question?
Input images :-
![largeImage](https://user-images.githubusercontent.com/44929784/152769216-684e374a-7ab4-4dd4-8fa1-7130eb296d73.jpeg)
![small](https://user-images.githubusercontent.com/44929784/152769243-d55d7c7e-1237-4655-9691-244e2ec78335.jpeg)

Output images :-
for blend type clear,
![outputClear](https://user-images.githubusercontent.com/44929784/152769729-6c8a0926-1f3e-4380-b3e2-cd101e189813.jpeg)

for blend type source,
![outputSource](https://user-images.githubusercontent.com/44929784/152769737-f80c962a-3d48-4e4e-bb35-159b211b300c.jpeg)

**Comment by lovell** [comment]
Hi, most compositing blends/operators require an alpha channel on at least one image. The two input images provided here are both JPEGs, which does not support an alpha channel.

**Comment by g-abhishek** [comment]
I tried with PNGs images, with one image(big one) has alpha channel, but still getting the same output.

Input Images :- 
![large_png](https://user-images.githubusercontent.com/44929784/153205791-c3536cc4-7320-4f92-b5b9-f51fdd487c5b.png)
![200](https://user-images.githubusercontent.com/44929784/153205828-60e7b9f0-f8b4-478a-bb9f-6980e24c6d23.png)

Output Images :- 
for blend type clear,
![clear](https://user-images.githubusercontent.com/44929784/153206053-aa8d8570-1543-4b8f-9a19-6b503dd6931d.png)

for blend type source,
![source](https://user-images.githubusercontent.com/44929784/153206240-28d5cd31-2a37-4b8b-8b75-7cb58f175713.png)

**Comment by lovell** [comment]
Those outputs appear to be correct for `clear` and `source`, which aren't particularly useful blend modes. Perhaps you intended to use `over` (the default)?

**Comment by g-abhishek** [comment]
If you see the https://www.cairographics.org/operators/ documentation, output given here is different than the generated one for `clear` and `souce`

![cairographics](https://user-images.githubusercontent.com/44929784/153340871-105a4ad1-187f-4299-b8fd-9607edaff715.png)

**Comment by g-abhishek** [comment]
Can you please refer the https://www.cairographics.org/operators/ docs once and check is this correct or not?

**Comment by lovell** [comment]
The way the `composite` operation works has been improved via commit https://github.com/lovell/sharp/commit/c62002554b5938c43c14fefafad7353ae4d720cf

I noticed that when compositing 3 or more images, the accuracy of the blend mode could suffer, and the clear and source modes particularly so as they would consider the combination of the previous 2 layers rather than 1st layer. Thanks for bringing this to my attention - let's track this at https://github.com/lovell/sharp/issues/2286
