### ISSUE TITLE
Enhancement: statically link Windows C++ runtime

### ISSUE THREAD

**Issue by dertieran** [lovell/sharp#3086]
I ran into a very strange issue when upgrading from `sharp@0.29.3` to `sharp@0.30.1` on Windows.

```sh
Error:
Something went wrong installing the "sharp" module

The specified module could not be found.
\\?\C:\...\node_modules\sharp\build\Release\sharp-win32-x64.node
```

But when I check the diorectory the module exists

```
ls node_modules\sharp\build\Release

    Directory:
C:\...\node_modules\sharp\build\Release

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---            2/1/2022 10:49 AM        1580544 libglib-2.0-0.dll
-a---            2/1/2022 10:49 AM         292352 libgobject-2.0-0.dll
-a---            2/1/2022 10:49 AM       20575232 libvips-42.dll
-a---            2/9/2022  5:47 PM         257024 libvips-cpp.dll
-a---            2/9/2022  5:47 PM         226304 sharp-win32-x64.node
```

I also check other Issues I found related to this

- I don't have `canvas` installed
- Deleting `_prebuilds` doesn't help
- Installing with different flags doesn't help

The only thing that worked was downgrading to `sharp@0.29.3` again.

### System Info:
```
npx envinfo --binaries --system

  System:
    OS: Windows 10 10.0.19043
    CPU: (2) x64 Intel(R) Celeron(R) CPU G3900 @ 2.80GHz
    Memory: 7.34 GB / 11.87 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
```

**Comment by lovell** [comment]
Do you have any other dependencies in the same `node_modules` directory that use sharp? What's the output of `npm ls sharp`?

**Comment by Doko-Demo-Doa** [comment]
I have the same issue. Output for `npm ls sharp` is:

```
└── sharp@0.30.1
```

No other module uses sharp.

**Comment by mariusa** [comment]
FYI works for me on linux

**Comment by Palad1NPT** [comment]
any news on this?

**Comment by wardpeet** [comment]
I don't have the issue on my windows machine 🤔 - what about `npm rebuild sharp`

**Comment by lovell** [comment]
The two main reasons for seeing this error on Windows are:

* `canvas` is also a dependency - see https://sharp.pixelplumbing.com/install#canvas-and-windows for why this won't work.
* conflicts with older versions of sharp in the dependency tree - ensure `npm ls sharp` and `npm ls -g sharp` only shows the latest version.

The latest v0.30.1 now represents over 10% of downloads from npm so I'd expect a lot more noise if this affected everyone.

The classic manoeuvre of deleting the `node_modules` directory and running `npm install` again is, I believe, still a thing, so please try that too.

**Comment by dertieran** [comment]
I'm on holiday right now and don't have access to the machine in question.
*(I'm normally running Linux without any problems.)*
But I also tired to delete the `node_modules` already, that was why I was confused the the file in question actually existed.
When I ran `yarn why sharp` it only showed the direct dependency.

Maybe it just works again when I try again when I'm back.
*(For now downgrading also works for me, so no worries ☺️)*

**Comment by Palad1NPT** [comment]
thank you for your time @lovell 

results from `npm ls sharp` and `npm ls -g sharp` are:
![image](https://user-images.githubusercontent.com/28867981/155507201-26831964-3236-4ae0-99f5-8df32bdeb9f5.png)


other things that I tried inclued:

- removing `node_modules`
- `npm install --platform=win32 --arch=x64 sharp`
- `npm install --ignore-scripts=false --verbose sharp`
- used diferent versions of node, tried with LTS 12, 14 and 16

**Comment by kleisauke** [comment]
"The specified module could not be found" error can usually be easily analyzed with the [`Dependencies`](https://lucasg.github.io/Dependencies/) program (a rewrite of the legacy Dependency Walker). Open `node_modules/sharp/build/Release/sharp-win32-x64.node`, you should see something like this:
![sharp](https://user-images.githubusercontent.com/12746591/155512350-bd21c935-2c79-442e-8d07-9e212b39e79f.png)

Perhaps Microsoft C and C++ (MSVC) runtime libraries are not installed on your system (the `msvcp140.dll`, `vcruntime140.dll` and `vcruntime140_1.dll` DLLs)? Since commit https://github.com/lovell/sharp/commit/659cdabd8e8c284901a0ea17ccdcb13e17350a8e, these DLLs are dynamically linked (with the `/MD` option instead of `/MT`).

**Comment by lovell** [comment]
Thanks Kleis, I had thought Windows 10 now provides runtime libraries as standard, but it looks like that may be only for C and not C++. That would explain why this is only affecting a few people, as many Windows apps require/install the C++ runtime.

Do we lose the improved error handling introduced in https://github.com/lovell/sharp/commit/659cdabd8e8c284901a0ea17ccdcb13e17350a8e if we revert to static linking?

**Comment by kleisauke** [comment]
Indeed, when compiling with Visual Studio (and using the `/MD` option) it links against the non-universal Visual C++ CRT dependency that is not preinstalled on Windows 10. 

The improved error handling disappears if we revert to static linkage, I had tested that at the time with this gist:
https://gist.github.com/kleisauke/6526f33f6ea77a1216ca3a1222417799

There may be another way to solve this though, by setting up an empty invalid parameter handler during `vips_init()` (guarded with `defined(G_OS_WIN32) && defined(_UCRT)`) it will set the handler local to that instance of the DLL (`libvips-42.dll` and dependencies), which should also ensure that the application does not abort on invalid parameter calls.

We might also consider reverting commit 659cdabd8e8c284901a0ea17ccdcb13e17350a8e altogether (except for the added test case) and try to fix any invalid parameter calls in libvips (if any, just like PR https://github.com/libvips/libvips/pull/2571). I think this policy is similar to GLib where they use an empty invalid parameter handler only when necessary, see for example:
https://github.com/GNOME/glib/blob/b3311e82ee04c90136ff231358d356e8e587f4da/glib/gmessages.c#L2117-L2122
https://github.com/GNOME/glib/blob/ebf64a5024e4cf10af94632aede32ea211efe700/glib/gspawn-win32-helper.c#L222-L225

**Comment by Palad1NPT** [comment]
thanks for the response @kleisauke, used Dependencies and it seems like it's missing one of the dlls you've mentioned.

![image](https://user-images.githubusercontent.com/28867981/155616040-9fb0c59b-2ba1-48d8-8c72-5cebd5c63cac.png)

will try to install missing dependencies in a couple of hours and report it later!

**Comment by Palad1NPT** [comment]
Ok, problem solved. MSVC was already installed so I had to download the dll separately.

Thanks!

**Comment by lovell** [comment]
Thanks all, let's revert https://github.com/lovell/sharp/commit/659cdabd8e8c284901a0ea17ccdcb13e17350a8e and if we need to add any new Windows-specific error handling, can do so in the C layer of libvips rather than C++ of sharp.

**Comment by SergiOca87** [comment]
This did not fix it for me but the error did change since "0.30.1" from:

`Something went wrong installing the "sharp" module The specified module could not be found.`

to

`Error: The specified procedure could not be found. 
  \\?\E:\...\Gatsby\...\node_modules\lmdb\build\Release\lmdb.node`

**Comment by lovell** [comment]
@SergiOca87 When you say "This did not fix it", does "this" refer to you having installed the Windows C++ runtimes?

**Comment by lovell** [comment]
v0.30.2 now available, I'm going to close this.

Any remaining errors that look like this will probably be due to one of the two common problems detailed in https://github.com/lovell/sharp/issues/3086#issuecomment-1049154853

**Comment by SergiOca87** [comment]
> v0.30.2 now available, I'm going to close this.
> 
> Any remaining errors that look like this will probably be due to one of the two common problems detailed in [#3086 (comment)](https://github.com/lovell/sharp/issues/3086#issuecomment-1049154853)

I am now getting:

`Error: Cannot find module 'detect-libc'
npm ERR! Require stack:
npm ERR! - C:\Users\...\node_modules\gatsby-plugin-wpgraphql-seo\node_modules\sharp\install\libvips.js`


After updating the Windows C++ runtimes

**Comment by lovell** [comment]
@SergiOca87 Please open [a new installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) and answer all of the questions if you still require help.

**Comment by codeusb** [comment]
This error occurs when I want to run.
![屏幕截图 2023-02-02 121050](https://user-images.githubusercontent.com/75412910/216229809-0a6d2a2a-c44b-47ba-9cfa-73d1851524b4.png)
When I try: `npm install --platform=win32 --arch=x64 sharp`
The same error occurs again.
What shall I do?
