### ISSUE TITLE
Reducing memory usage

### ISSUE THREAD

**Issue by dmitrizzle** [lovell/sharp#3089]
### What are you trying to achieve?
I'm processing batches of 200-400MB TIFF files on an instance with 1GB of memory. It is occasionally not enough. I'm trying to understand what I can do better to manage memory.

### Have you searched for similar questions?
Yes, I've landed on #138 and related issues regarding streaming. But I'm not sure if this is the best approach.

My use case requires me to clone and downsample the entire image to be analyzed. I then use the analysis results for processing the full-size image. If I am to change the file to a stream, I may not be able to split it into two parts (one, downsized, for analysis and one for processing).

I currently start the instance on `node:14-alpine` container with `--optimize_for_size --max_old_space_size=320 --gc_interval=50`. Other than streaming, I'm also considering adding an artificial delay between jobs to ensure that the memory has time to empty out.

I would really appreciate some guidance here. Thank you so much!

### Are you able to provide a minimal, standalone code sample that demonstrates this question?
```javascript

// create a reduced-size image sample
const data = await sharp(image).clone().resize(500).toBuffer();

// this object will store values that will be used for full-size image manipulation
const prescriptions = {};

// determine values for full-size image manipulation
const channelNames = ["red", "green", "blue"];
const prescriptionsCalculators = channelNames.map(async (channel) => {
  const forAnalysis = await sharp(data)
  .extractChannel(channel)
  .toColorspace("b-w")
  .blur(1)
  .toBuffer();

  const stats = await sharp(forAnalysis).stats();
  const { channels } = stats;

  const range = [channels[0].min, channels[0].max];
  const linear = levels(range[0], range[1]);

  prescriptions[channel] = { linear, range };
  return await linear;
});
await Promise.all(prescriptionsCalculators);

// use the above data to process full-size image
const channels = {};
const channelEffects = channelNames.map(async (channel) => {
  const result = sharp(reversed)
    .extractChannel(channel)
    .toColorspace("b-w")
    .linear(...prescriptions[channel].linear)
    .toBuffer();
  channels[channel] = result;
  return result;
});
await Promise.all(channelEffects);

// reassemble channels into RGB
const positive = sharp(await channels["red"]).joinChannel([
  await channels["green"],
  await channels["blue"],
]);

return positive;
```

**Comment by lovell** [comment]
The quickest way to reduce memory usage would be to switch from RAM to filesystem. Have you tried replacing any of the `toBuffer` calls with `toFile`?

**Comment by dmitrizzle** [comment]
Thank you for the tip, @lovell! I tried replacing a few calls and memory usage seems to be a little more constrained.
