### ISSUE TITLE
Extracting frames of a gif file when encoding of each frame use previous one

### ISSUE THREAD

**Issue by mrbuds** [lovell/sharp#3090]
**What are you trying to achieve?**

I make a tool to convert gif files to a single image with each frames, goal is to use them in a World of Warcraft addon that can play animations, the game require width/height to be a power of 2, and TGA format (striped it in the example)

My solution may not be optimal but is mostly working, but i have an issue with gif generated from mp4 where each frame as a transparent background, like the `kekw.gif` 

Is there a parameter i am missing to make the gif decoding use previous frame for each image?
Or should i use composite() between each frames ?

**Have you searched for similar questions?** yes no success

**Are you able to provide a minimal, standalone code sample that demonstrates this question?
Are you able to provide a sample image that helps explain the question?**

sample code and images in this file [gif2tga.zip](https://github.com/lovell/sharp/files/8054017/gif2tga.zip)
kekw.gif is the example i have issue with, most gif i can find made from movies have same issue
monkey.gif is working like i want
the 2 png files included are the output

**Comment by lovell** [comment]
If you need to overlay multiple frames/pages of an animated image then the use of `composite()` would be a good approach, as you suggest.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
