### ISSUE TITLE
M1 macbook air vs windows speed discrepancy

### ISSUE THREAD

**Issue by jahbolero** [lovell/sharp#3091]
What are you trying to achieve?
Merge multiple photos(Hundreds)

Have you searched for similar questions?
Yes
Are you able to provide a minimal, standalone code sample that demonstrates this question?
No
Are you able to provide a sample image that helps explain the question?
No

I've been trying to run the sharp composite command to generate a large image set(1k). 
Running on my windows machine, it takes roughly 15 minutes to generate a thousand, while on a MacBook m1 air it takes 100 minutes to do the same number. 

Is there any incompatibility issue with the recent m1 chips? Or perhaps config that needs to be done for it to perform optimally?

**Comment by lovell** [comment]
There's not a lot of information to go on, but my best guess with the very limited detail provided here would be that if the task is CPU bound then you might be using Rosetta x64 emulation on the M1 (e.g. via Node.js 14).

For more help please provide complete, minimal, standalone code and image(s) that allows someone else to reproduce this.

**Comment by jahbolero** [comment]
My apologies for the delay. 
The same has been tested using the latest node version on a MacBook m1 and was only 20% faster than with the older node version. 

Just additional details for comparison:
Windows:Ryzen 7 4000
Macbook:M1 MacBook Air

Below is a sample snippet of generating multiple images.

```
const compositeImage = async (images) => {
  let inputArray = [];
  for (var i = 1; i < images.length; i++) {
    inputArray.push({ input: `${images[i]}` });
  }
  sharp(`${images[0]}`).composite(inputArray).toFile(`${1}.png`);
};
```

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/2286

**Comment by jahbolero** [comment]
I will try replicating the case again with the newest commit. However, there's something that I failed to add, which separates this issue with #2286. The complete code to replicate what was done in both machines for the case is below.

Given the difference in processing power, expectedly the MacBook m1 should be significantly faster than the windows ryzen 7 4000.

```
const compositeImage = async (images, id) => {
  let inputArray = [];
  for (let i = 1; i < images.length; i++) {
    inputArray.push({ input: `${images[i]}` });
  }
  sharp(`${images[0]}`).composite(inputArray).toFile(`${id}.png`);
};

let imageArray = ["image1.png","image2.png","image3.png","image4.png","image5.png","image6.png"];
for(let i = 0; i < 1000; i++){
console.log("start:"+new Date().toLocaleTimeString());
compositeImage(imageArray,i);
console.log("end:"+new Date().toLocaleTimeString());
}
```
