### ISSUE TITLE
Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by blankTwo** [lovell/sharp#3093]
```
Something went wrong installing the "sharp" module

The specified module could not be found.
\\?\C:\Program Files\xxxxxx\resources\app.asar.unpacked\node_modules\sharp\build\Release\sharp-win32-ia32.node

Possible solutions:
- Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
- Install for the current win32-ia32 runtime: "npm install --platform=win32 --arch=ia32 sharp"
```
The installation package built with electron-build is x64, and it can run normally when installed on windows 10 x64, but the error is that I installed it on windows 7 32-bit system, and the above error message appears when calling the processing images.

Does it currently support x86 platforms?

On x86, I tried tweaking the code and it works fine with images

![image](https://user-images.githubusercontent.com/45682935/154017585-63bc0f27-2981-4428-bb98-01e511ecbf64.png)

**Comment by blankTwo** [comment]
```
  if(platform === 'win32' && arch === 'x64') {
    arch = 'ia32';
  }
```

**Comment by lovell** [comment]
Hi, did you see the message in the error your provided?

> Possible solutions:
> - Install for the current win32-ia32 runtime: "npm install --platform=win32 --arch=ia32 sharp"

Did you see https://sharp.pixelplumbing.com/install#cross-platform ? (This was mentioned in the issue template that was deleted.)

**Comment by blankTwo** [comment]
> Hi, did you see the message in the error your provided?
> 
> > Possible solutions:
> > 
> > * Install for the current win32-ia32 runtime: "npm install --platform=win32 --arch=ia32 sharp"
> 
> Did you see https://sharp.pixelplumbing.com/install#cross-platform ? (This was mentioned in the issue template that was deleted.)

Unexpectedly, executing "npm install --platform=win32 --arch=ia32 sharp" to build the installation package, it still doesn't work on 32

**Comment by blankTwo** [comment]
> Hi, did you see the message in the error your provided?
> 
> > Possible solutions:
> > 
> > * Install for the current win32-ia32 runtime: "npm install --platform=win32 --arch=ia32 sharp"
> 
> Did you see https://sharp.pixelplumbing.com/install#cross-platform ? (This was mentioned in the issue template that was deleted.)


There is ```sharp-win32-ia32.node``` under the changed path but it doesn't work

![image](https://user-images.githubusercontent.com/45682935/154185121-3937ea4f-5e06-472a-a0e9-98ca3ff98e00.png)

**Comment by lovell** [comment]
Please ensure the other DLL files e.g. `libglib...` etc. in the `Release` directory are 32-bit, as it looks like you're attempting to install 32-bit and 64-bit together.

**Comment by blankTwo** [comment]
> * npm install --platform=win32 --arch=ia32 sharp



> Please ensure the other DLL files e.g. `libglib...` etc. in the `Release` directory are 32-bit, as it looks like you're attempting to install 32-bit and 64-bit together.

I will try again with a new project

After executing `npm install --platform=win32 --arch=ia32 sharp`, how to check if other dll files are 32-bit?

**Comment by blankTwo** [comment]
> Please ensure the other DLL files e.g. `libglib...` etc. in the `Release` directory are 32-bit, as it looks like you're attempting to install 32-bit and 64-bit together.

I don't understand it very well. I use the `npm install --platform=win32 --arch=ia32 sharp `command to install. The built installation package will still prompt an error message when using image processing. `Release\sharp-win32-ia32.node` cannot be found ，I made sure to install 32-bit ！

**Comment by Slapbox** [comment]
@lovell I hope you won't mind the necro.

> Please ensure the other DLL files e.g. libglib... etc. in the Release directory

We're trying to build in Docker and we're getting an error like below. The file it's complaining about does exist, but the related `.dll` files indeed do not.

It only occurs when we build for Windows inside of a Linux-based Docker (provided by Electron Builder)

I wonder if you'd expect this to be fixed by upgrading from Yarn v1 to the latest version, or if there's some other issue? I read over the install page including the cross-platform section but it's not clear to me that upgrading Yarn would fix this in the case of Docker. Outside of Docker it builds as expected on any platform.

I just know that's a big can of worms given our monorepo that includes React Native, so I don't want to jump into that gung ho if that's not the real problem here. I'm not certain it is since we at least yield the corrrect `sharp-win32-x64.node`.

Thank you so much for your excellent work, and if you can take the time to point me in the right direction here, thank you even more!

(unfortunately I can't simply test the prescribed command right now because Docker consumed my HDD) (#13723)

```
[2024-02-03 21:00:58.353] [error] Error: 
Something went wrong installing the "sharp" module

The specified module could not be found.
\\?\C:\Projects\docker-outputs\win-unpacked\resources\app.asar.unpacked\node_modules\sharp\build\Release\sharp-win32-x64.node

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current win32-x64 runtime: "npm install --platform=win32 --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (C:\Projects\docker-outputs\win-unpacked\resources\app.asar\node_modules\sharp\lib\sharp.js:37:9)
    at ........
```

**Comment by lovell** [comment]
@Slapbox For multi/cross platform installation, please upgrade both yarn and sharp. If you're still having problems, please open a new installation issue.
