### ISSUE TITLE
Tiff returns Input buffer contains unsupported image format

### ISSUE THREAD

**Issue by rawpixel-vincent** [lovell/sharp#3094]
## Possible bug

Loading the attached image returns the error `Input buffer contains unsupported image format`

### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
System:
    OS: Linux 5.10 Amazon Linux 2
    CPU: (2) arm64 unknown
    Memory: 166.59 MB / 2.92 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 14.18.3 - /var/lang/bin/node
    npm: 6.14.15 - /var/lang/bin/npm
  npmPackages:
    sharp: ^0.30.1 => 0.30.1 

```

we use pre-built binaries, fwiw we can process thousands of images without any issue, we encounter that error in very rare occasion. It is reproducible on every case with the attached file. 

### What are the steps to reproduce?

load the attached image from the filesystem in memory as a Buffer and use with the code:

```
const image = sharp(imageBuffer, {
      density: 300,
      limitInputPixels: 636805378,
      failOnError: false,
    });

    image.withMetadata({ icc: `....AdobeRGB1998.icc` });

      image.rotate().jpeg({
        quality: 100,
      });
    }

    image.toBuffer((err, buffer, info) => {
      if (err) {
        console.log(err);
      } else {
        console.log({ buffer, info });
      }
    });
```

### Please provide sample image(s) that help explain this problem

ICC profile https://rawpixel-marketing.s3.us-west-2.amazonaws.com/AdobeRGB1998.icc
Tiff https://rawpixel-marketing.s3.us-west-2.amazonaws.com/invalid-input-sharp.tif

sorry for the large image file size, this is the smallest one we have that trigger that error

**Comment by lovell** [comment]
Are you sure this is a TIFF image? It looks very much like a Photoshop PSD file to me.
```
$ file invalid-input-sharp.tif 
invalid-input-sharp.tif: Adobe Photoshop Image, 5800 x 5200, RGB, 3x 16-bit channels
```

```sh
$ hexdump -C invalid-input-sharp.tif | head -1
00000000  38 42 50 53 00 01 00 00  00 00 00 00 00 03 00 00  |8BPS............|
```

**Comment by rawpixel-vincent** [comment]
of course!
and the message `Input buffer contains unsupported image format` now makes total sense.. I'll remember to check the file type first next time I see that, and we'll definitely add a file type detection to that workflow
thanks a lot 🙏🏻
