### ISSUE TITLE
How do I delete the original file after modification?

### ISSUE THREAD

**Issue by 79percent** [lovell/sharp#3099]
# How do I delete the original file after modification?

I have a webp file and I want to convert it to JPG and delete the original webp file

My code looks like this

```js
 await sharp('./input.webp').toFile('./out.jpg');
 fs.unlinkSync(path.join(__dirname, './input.webp'));
```

toFile is effective, but report an error
> EBUSY: resource busy or locked, unlink

I try other Image format convert it to JPG

GIF report an error as well
>EPERM: operation not permitted, unlink 

But JPG and PNG file was deleted as expected

How to delete origin webp or gif file?

**Comment by centigrade-thomas-becker** [comment]
I have the same problem. When using a GIF file as a source for a resize operation then the source file has a lingering read lock that lasts as long as the node process is running. A possible workaround is to *not* read the file contents with sharp.

To expand on your code, I used "fs" to read the file contents and passed the buffer to sharp. This way there was no file lock on the original gif file:

```
const fileContent = fs.readFileSync('./input.webp');
 await sharp(fileContent ).toFile('./out.jpg');
 fs.unlinkSync(path.join(__dirname, './input.webp'));
```

My versions:

sharp: 0.30.5
Node: 14.16.1
Windows: 21H2, build 19044.1706

**Comment by lovell** [comment]
Please see https://sharp.pixelplumbing.com/api-utility#cache

```js
sharp.cache({ files: 0 })
```
or
```js
sharp.cache(false)
```

**Comment by MikeAwad662442** [comment]
Could you put an example where and when I should use it
sharp.cache({ files: 0 }) or sharp.cache(false)
Its use is important to me in an application and I did not know how to use it to delete the main file

**Comment by lovell** [comment]
`sharp.cache(false)` is equivalent to `sharp.cache({ memory:0, files: 0, items: 0 })`

https://sharp.pixelplumbing.com/api-utility#cache

Windows won't let you delete a file whilst it is held open by libvips' cache.

**Comment by MikeAwad662442** [comment]
Thank you for your answer, I have read this section before, but my question is where to put the instruction
I use "multer" to save pictures in express js
`
function fileDB(fileReQ: any, bodyREQ: any, imgType: string) {
  var type = imgType;
  var IMG: any;
  if (fileReQ !== undefined) {
    const imgPath: any = fileReQ.split(path.sep); // Get PATH & Split To ARRAY
    // [public , images , 1645211075347.png] //
    imgPath.shift(); // cut (remove) the first array object
    // [images , 1645211075347.png] //
    IMG = imgPath.join("/"); // join array to string then insert to database
    // images/1645211075347.png
// === Resize IMAGES === //
    if (type === 'image') { 
     var NewIMG = 1 + IMG;
        sharp(`${publicFile}/${IMG}`)
          .resize(300, 300, {
            fit: "cover"
          })
          .jpeg({ mozjpeg: true })
          .toFile(`${publicFile}/${NewIMG}`)
          //   , (err) => {
          //   if (err) { console.log('Error ' + `${publicFile}/${NewIMG}` + ' ' + err.toString());
          //   } else { console.log('made ' + `${publicFile}/${NewIMG}`);
          //     fs.unlink(IMG, (err) => {
          //       if (err) {
          //         console.log('error deleting ' + IMG + ' ' + err.toString());
          //       } else {
          //         console.log('deleted ' + IMG);
          //       }
          //     });
          //   }
          // })
      // console.log(NewIMG);
      return NewIMG;
    } else {
      return IMG;
    }
// === Resize IMAGES === //
  } else if (bodyREQ !== undefined) {
    IMG = bodyREQ;
    return IMG;
  }

}
`
