### ISSUE TITLE
sharp on electron-react-boilerplate

### ISSUE THREAD

**Issue by if4lcon** [lovell/sharp#3100]
Hi I have installed sharp on https://github.com/electron-react-boilerplate/electron-react-boilerplate

but when using it I get

`(0 , sharp_1.default) is not a function`

**Comment by lovell** [comment]
Hello, the issue template appears to have been ignored and/or deleted. Please open a new installation issue and answer all of the questions.

https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md

**Comment by if4lcon** [comment]
Sorry I have opened new issue with the template
