### ISSUE TITLE
multipage toBuffer

### ISSUE THREAD

**Issue by lublak** [lovell/sharp#3102]
### What are you trying to achieve?

I am trying to convert a multi-page tiff into several jpg buffers.
Does the buffer then include all pages or only the first one?
And what is the possibility to get an array?

The input is a tiff file. Wish would be an array with
```
[
  {
    buffer:Buffer,
    width:number,
    height:number
  }
]
```

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```ts
const data = await sharp(await readFile(filePath), { pages: -1}).jpeg().toBuffer({ resolveWithObject: true });
```

**Comment by lovell** [comment]
Did you see the `page` option of the constructor?

https://sharp.pixelplumbing.com/api-constructor

> `options.page` page number to start extracting from for multi-page input (GIF, WebP, AVIF, TIFF, PDF), zero based. (optional, default 0)

```ts
const { pages } = await sharp(input).metadata();
const range: number[] = Array.from(Array(pages).keys());

const outputs: Buffer[] = await Promise.all(
  range.map(page => sharp(input, { page }).toBuffer())
);
```

**Comment by lublak** [comment]
yes I have seen that. :)
But did not have the metadata in mind. So first extract metadata. And then the individual pages.
Is the file then completely loaded twice or is extracting the metadata really only header based (performant)?

In any case danek for the answer and also very fast!

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/api-input#metadata

> Fast access to (uncached) image metadata without decoding any compressed pixel data.

**Comment by lublak** [comment]
@lovell thanks allot! :)
