### ISSUE TITLE
A half invalid tiff file closes the nodejs process

### ISSUE THREAD

**Issue by lublak** [lovell/sharp#3103]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz
    Memory: 82.97 GB / 96.00 GB
  Binaries:
    Node: 17.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: ^0.30.1 => 0.30.1
```

### What are the steps to reproduce?

Load a tiff file works with but exit the node process without any error.
I can even save the buffers to files without problems. The jpeg files are completely valid.
I have an express server running but after a short time it just quits silent.

```ts
const { pages } = await sharp(input).metadata();
const range: number[] = Array.from(Array(pages).keys());

const outputs: Buffer[] = await Promise.all(
  range.map(page => sharp(input, { page }).toBuffer())
);
```
When I extract the tiff metadata this way an error message comes up (difference is only `, { pages: -1 }`)  `[Error: Input buffer has corrupt header: tiff2vips: page 1 differs from page 0 ]`:

```ts
const { pages } = await sharp(input, { pages: -1 }).metadata();
const range: number[] = Array.from(Array(pages).keys());

const outputs: Buffer[] = await Promise.all(
  range.map(page => sharp(input, { page }).toBuffer())
);
```

### What is the expected behaviour?

Since the jpeg buffers are completely valid, I would also like sharp not to simply close the process.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

Currently not possible because the tiff files contain personal data that unfortunately may not be published.
Unfortunately, no new ones can be created because they originate from an old system that has long since ceased to exist.

### Please provide sample image(s) that help explain this problem

Unfortunately as mentioned above I can not send them. But here the tiff info of it:

```
TIFF Directory at offset 0x8 (8)
  Subfile Type: multi-page document (2 = 0x2)
  Image Width: 1645 Image Length: 837
  Resolution: 200, 200 pixels/inch
  Bits/Sample: 1
  Compression Scheme: CCITT Group 4
  Photometric Interpretation: min-is-white
  FillOrder: msb-to-lsb
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Rows/Strip: 837
  Planar Configuration: single image plane
  Page Number: 0-2
  Software: ImageGear Version:  7.00.015
  DateTime: 2021: 2:23 07:36:24
  Artist: 1996-98 AccuSoft Inc., All rights reserved
TIFF Directory at offset 0x3321 (13089)
  Subfile Type: multi-page document (2 = 0x2)
  Image Width: 1643 Image Length: 836
  Resolution: 200, 200 pixels/inch
  Bits/Sample: 1
  Compression Scheme: CCITT Group 4
  Photometric Interpretation: min-is-white
  FillOrder: msb-to-lsb
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Rows/Strip: 836
  Planar Configuration: single image plane
  Page Number: 1-2
  Software: ImageGear Version:  7.00.015
  DateTime: 2021: 2:23 07:36:24
  Artist: 1996-98 AccuSoft Inc., All rights reserved
```

**Comment by lovell** [comment]
The input image is probably corrupt or invalid. You'll need to add some error handling e.g. a try/catch block to your code in order to deal with this scenario.

**Comment by lublak** [comment]
@lovell Around this code is now a try and catch. Catch is triggered with `, { pages: -1 }` => `[Error: Input buffer has corrupt header: tiff2vips: page 1 differs from page 0 ]` but not without this `, { pages: -1 }`.
Then the code runs through and I can even save the buffers as files.
Only after that the nodescript closes automatically and terminates the webserver without a message. So completely without.

**Comment by lublak** [comment]
@lovell this works fine. I try this command and i get 2 tif files without any erros.

**Comment by lovell** [comment]
Glad you worked it out, thanks for the update.
