### ISSUE TITLE
Adding Text to img without svg

### ISSUE THREAD

**Issue by BuddiesTV** [lovell/sharp#3104]
### What are you trying to achieve?
I want to add a Text to a img without using svg

### When you searched for similar issues, what did you find that might be related?
I found a text option, but this option is not working,
```js
sharp('img/background.png')
.text({
    text: "Hello, world!",
    width: 1920,
    height: 1080,
    alignment: "centre",
    verticalAlignment: "bottom",
    color: "#ffffff",
    backgroundColor: "#000000",
    fontName: "Arial",
    shouldJustify: false,
    dpi: 300,
    lineSpacing: 16,
})
.composite([{ input: 'img/logo.png', gravity: 'north' }])
.blur(5)
.png()
```

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question
Current Code:
```js
sharp('img/background.png')
.composite([{ input: 'img/logo.png', gravity: 'north' }])
.blur(5)
.png()
```

### Please provide sample image(s) that help explain this question

N/A

**Comment by lovell** [comment]
Please see the future possible enhancement being discussed at #512 (you appear to have quoted a suggested API from that discussion).

**Comment by BuddiesTV** [comment]
So, this API isn't a thing currently?

**Comment by lovell** [comment]
The API is under discussion and the code has yet to be written. A PR to implement it would be very welcome, if you're able. Let's track this at #512 - please subscribe to that issue for updates.

**Comment by BuddiesTV** [comment]
What is about this?
https://github.com/rorz/sharp/commit/76f0bf6bb447e3e0b37b6c70ef68655f0d27f3a0
it looks like rorz already added basic text functions.

**Comment by lovell** [comment]
That's not part of sharp; you're looking at a commit in a third-party fork.

**Comment by BuddiesTV** [comment]
Can't you use the third-party fork, to implement the feature in sharp?
