### ISSUE TITLE
HEIF produced by sharp is corrupted

### ISSUE THREAD

**Issue by kiloreux** [lovell/sharp#3108]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

npx: installed 1 in 2.023s

  System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz
    Memory: 1.46 GB / 3.84 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.5 - ~/.nix-profile/bin/node
    Yarn: 1.22.0 - ~/.nix-profile/bin/yarn
    npm: 6.14.14 - ~/.nix-profile/bin/npm

### What are the steps to reproduce?

Running the sample code will produce an heif image that is corrupted. 

### What is the expected behaviour?

An heif image that can be opened normally.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```
#!/usr/bin/env node

'use strict'

const sharp = require('sharp')

async function resizeImage () {
  try {
    await sharp('elephant.png')
      .resize({
        width     : 1000,
        height    : 1000,
        background: { r: '255', g: '255', b: '255', alpha: '0' },
      })
      .toFormat('heif')
      .toFile('wow-resized.heif')
  } catch (error) {
    console.log(error)
  }
}

resizeImage()

```

### Please provide sample image(s) that help explain this problem

![elephant](https://user-images.githubusercontent.com/6282557/155346757-8ec6ee8b-9134-48dd-af35-d8d90851d14d.png)

**Comment by juliangruber** [comment]
I can reproduce with

```
  System:
    OS: macOS 12.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 835.04 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  npmPackages:
    sharp: ^0.30.1 => 0.30.1

```

**Comment by juliangruber** [comment]
Interestingly https://www.checkfiletype.com/ can render a preview of the heif image

**Comment by lovell** [comment]
It works on my machine :tm:

The output appears to be a valid AVIF image, which is expected as the default compression is `av1`.

https://sharp.pixelplumbing.com/api-output#heif

**Comment by juliangruber** [comment]
Latest Photoshop on Mac can also not open the resulting file, btw

**Comment by juliangruber** [comment]
This is the file that is produced on my machine: https://we.tl/t-BQNWEikAXI

**Comment by juliangruber** [comment]
@lovell are you saying the file is valid but the standard isn't supported on hosts yet?

**Comment by lovell** [comment]
The default HEIF compression `av1` will give you an AVIF file, which can be viewed in most web browsers (Firefox opens the output image as-is, Chrome needs the extension changed to `.avif` before it will do so).

<details>
<summary>heif-info -d wow-resized.heif</summary>

```
MIME type: image/avif
main brand: avif
compatible brands: avif, mif1, miaf

Box: ftyp -----
size: 28   (header size: 8)
major brand: avif
minor version: 0
compatible brands: avif,mif1,miaf

Box: meta -----
size: 408   (header size: 12)
version: 0
flags: 0
| Box: hdlr -----
| size: 33   (header size: 12)
| version: 0
| flags: 0
| pre_defined: 0
| handler_type: pict
| name: 
| 
| Box: pitm -----
| size: 14   (header size: 12)
| version: 0
| flags: 0
| item_ID: 1
| 
| Box: iloc -----
| size: 52   (header size: 12)
| version: 0
| flags: 0
| item ID: 2
|   construction method: 0
|   data_reference_index: 0
|   base_offset: 444
|   extents: 0,1945 
| item ID: 1
|   construction method: 0
|   data_reference_index: 0
|   base_offset: 2389
|   extents: 0,32605 
| 
| Box: iinf -----
| size: 56   (header size: 12)
| version: 0
| flags: 0
| | Box: infe -----
| | size: 21   (header size: 12)
| | version: 2
| | flags: 0
| | item_ID: 1
| | item_protection_index: 0
| | item_type: av01
| | item_name: 
| | content_type: 
| | content_encoding: 
| | item uri type: 
| | hidden item: false
| | 
| | Box: infe -----
| | size: 21   (header size: 12)
| | version: 2
| | flags: 0
| | item_ID: 2
| | item_protection_index: 0
| | item_type: av01
| | item_name: 
| | content_type: 
| | content_encoding: 
| | item uri type: 
| | hidden item: false
| 
| Box: iprp -----
| size: 215   (header size: 8)
| | Box: ipco -----
| | size: 177   (header size: 8)
| | | Box: colr -----
| | | size: 19   (header size: 8)
| | | colour_type: nclx
| | | colour_primaries: 2
| | | transfer_characteristics: 2
| | | matrix_coefficients: 6
| | | full_range_flag: 1
| | | 
| | | Box: av1C -----
| | | size: 12   (header size: 8)
| | | version: 1
| | | seq_profile: 0
| | | seq_level_idx_0: 5
| | | high_bitdepth: 0
| | | twelve_bit: 0
| | | chroma_subsampling_x: 1
| | | chroma_subsampling_y: 1
| | | chroma_sample_position: 0
| | | initial_presentation_delay: not present
| | | config OBUs:
| | | 
| | | Box: ispe -----
| | | size: 20   (header size: 12)
| | | version: 0
| | | flags: 0
| | | image width: 1000
| | | image height: 1000
| | | 
| | | Box: pixi -----
| | | size: 14   (header size: 12)
| | | version: 0
| | | flags: 0
| | | bits_per_channel: 8
| | | 
| | | Box: auxC -----
| | | size: 56   (header size: 12)
| | | version: 0
| | | flags: 0
| | | aux type: urn:mpeg:mpegB:cicp:systems:auxiliary:alpha
| | | aux subtypes: 
| | | 
| | | Box: av1C -----
| | | size: 12   (header size: 8)
| | | version: 1
| | | seq_profile: 1
| | | seq_level_idx_0: 5
| | | high_bitdepth: 0
| | | twelve_bit: 0
| | | chroma_subsampling_x: 0
| | | chroma_subsampling_y: 0
| | | chroma_sample_position: 0
| | | initial_presentation_delay: not present
| | | config OBUs:
| | | 
| | | Box: ispe -----
| | | size: 20   (header size: 12)
| | | version: 0
| | | flags: 0
| | | image width: 1000
| | | image height: 1000
| | | 
| | | Box: pixi -----
| | | size: 16   (header size: 12)
| | | version: 0
| | | flags: 0
| | | bits_per_channel: 8,8,8
| | 
| | Box: ipma -----
| | size: 30   (header size: 12)
| | version: 0
| | flags: 0
| | associations for item ID: 1
| | | property index: 1 (essential: true)
| | | property index: 6 (essential: true)
| | | property index: 7 (essential: false)
| | | property index: 8 (essential: true)
| | associations for item ID: 2
| | | property index: 2 (essential: true)
| | | property index: 3 (essential: false)
| | | property index: 4 (essential: true)
| | | property index: 5 (essential: true)
| 
| Box: iref -----
| size: 26   (header size: 12)
| version: 0
| flags: 0
| reference with type 'auxl' from ID: 2 to IDs: 1 

Box: mdat -----
size: 34558   (header size: 8)
```

</details>

**Comment by lovell** [comment]
GIMP (v2.10.18) on Ubuntu 20.04 can open the resultant AVIF file quite happily.

Which Ubuntu tools are you using that you would normally expect to be able to parse AVIF images but cannot parse the resultant image provided in this issue?

**Comment by kiloreux** [comment]
I am using `heif-gdk-pixbuf` . And using GIMP on my machine fails also with this. 

![Screenshot from 2022-02-23 20-06-57](https://user-images.githubusercontent.com/6282557/155389904-99db0158-a573-448b-8c6e-551b36339501.png)

**Comment by lovell** [comment]
What version of libheif are you using? Are you using the PPA? https://launchpad.net/~strukturag/+archive/ubuntu/libheif

**Comment by kiloreux** [comment]
@lovell The issue was on my side and I fixed it now. Thank you very very very much :pray:

**Comment by danielehrhardt** [comment]
> 

I have the same Issue. What have you done to fix it?

**Comment by danielehrhardt** [comment]
> @lovell The issue was on my side and I fixed it now. Thank you very very very much 🙏

I have the same Issue. What have you done to fix it?
