### ISSUE TITLE
Problem with jpeg rendering in Ubuntu 1404

### ISSUE THREAD

**Issue by emathias** [lovell/sharp#311]
Hi, 

I'm having issues with jpeg rendering in Ubuntu 14.04. I did the installation as suggested and my code looks like this 

 sharp(buf)
        .resize(300, 300)
        .quality(50)
        .toFormat('jpeg')
        .toBuffer(function(error, outputBuffer) {
  // ... send buffer to AWS S3
 }

I have no errors whatsoever, but the resulting image file size is too not only small, but also wrong (i.e. image is not as expected). 

For info, It's working OK in MacOS (my dev machine) and png exports also work fine in both Ubuntu and Mac 

Here are some samples: 
- original: https://i.ytimg.com/vi/qRC4Vk6kisY/maxresdefault.jpg
- jpeg export mac: https://www.dropbox.com/s/lu688toxe4ivvts/output-mac.jpg?dl=0
- jpeg export ubuntu (the problematic one): https://www.dropbox.com/s/4lma3vxu80vwzdk/output-ubuntu.jpg?dl=0

For info, I'm running this vips version:
vips -v
vips-7.40.6-Thu Oct 16 23:20:47 UTC 2014

Is there anything I could try ? 

Thanks and regards.

**Comment by lovell** [comment]
This looks like #249. If so, this will be fixed in the next release. For now you can either add `flatten` to your pipeline or upgrade to libvips 8.1.0+.

**Comment by emathias** [comment]
Thanks a lot lovell. That was it.

Flatten solved the issue.  I was exactly in the same situation vips 7.4, Debian 8.2

Weird thing is that in command line, it was working fine. 

Anyways, thanks a lot for the help. You saved the day ;)

And congrats for 'sharp'. It's such a great piece of software and time savior!

**Comment by lovell** [comment]
No worries, glad to hear you got it working.
