### ISSUE TITLE
[Bug] sharp v0.30.0+ greyscale images with an embedded ICC profile change white pixels to dark grey

### ISSUE THREAD

**Issue by shodanwang** [lovell/sharp#3112]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
npx: installed 1 in 0.435s

  System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 9.07 GB / 15.59 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.0 - /usr/bin/node
    npm: 6.14.16 - /usr/bin/npm
```

### What are the steps to reproduce?

1. Download the image from [this link](https://i.imgur.com/nOk1vSs.jpg), rename it to `in.jpg`
2. Convert ( resize ) `in.jpg` with the following snippet:

```javascript
const sharp = require("sharp");

async function resizeImage() {
  try {
    await sharp("in.jpg")
      .resize({
        width: 480,
        height: 480
      })
      .toFile("out.jpg");
  } catch (error) {
    console.log(error);
  }
}

resizeImage();
``` 

3. Check the result ( out.jpg ), it should be something like [this](https://i.imgur.com/JDQOi2L.jpg).

### What is the expected behaviour?

You can see the image is filled with lots of grey area, tainting ( not sure if this is the right word ) the image. It should just resize the image instead of filling the image with grey area.  

Notice that this happens after `v0.30.0+` ( so both `v0.30.0` & `v0.30.1` suffered from this problem ), but not in the version before that. `v0.29.3` does not have this problem, it can convert the image normally.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

( Check the "how to reproduce" section )

### Please provide sample image(s) that help explain this problem  

( Check the "how to reproduce" section )

**Comment by lovell** [comment]
Hi, thanks for reporting, I can reproduce with the supplied input image using `sharp("in.jpg").toFile("out.jpg")`.

The input image is 8-bit greyscale with an embedded ICC profile that appears to be valid for such an image.
```
ColorSync color profile 2.1, type ADBE, GRAY/XYZ-prtr device by ADBE, 912 bytes, 3-6-1999 "Dot Gain 30%"
```

The input image undergoes an ICC transform via lcms (Little CMS) using its embedded profile, which is where things go wrong.

sharp v0.29.x provides lcms 2.12 whereas sharp v0.30.x provides lcms 2.13 so we're probably seeing the effects of the following upstream bug:

https://github.com/mm2/Little-CMS/commit/fdbfb7694f9d7048d53674b79ddfc38068bfdaf7

https://bugs.archlinux.org/task/73580
https://bugs.gentoo.org/832520

**Comment by lovell** [comment]
Commit https://github.com/lovell/sharp/commit/21a960796c769263e66f45f9ee1795d31be0272e temporarily ignores greyscale ICC profiles. We can revert this to re-introduce support later after we pick up a newer version of lcms with the upstream bug fix.

**Comment by lovell** [comment]
Created https://github.com/lovell/sharp/issues/3114 as a reminder to revert this temporary workaround later.

**Comment by lovell** [comment]
v0.30.2 now available with a quick fix for this, thanks again for reporting.
