### ISSUE TITLE
Unable to get correct height & width while converting SVG to TIFF

### ISSUE THREAD

**Issue by nishantjiit** [lovell/sharp#3113]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [X ] Running `npm install sharp` completes without error.
- [X] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [X ] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

I am converting SVG to TIFF like:

`const converter = sharp()
            .flatten({ background: { r: 255, g: 255, b: 255, alpha: 255 } })
            .toColourspace('b-w')
            .threshold(255)
            .withMetadata({ density: 300 })
            .tiff({bitdepth:1,compression:'ccittfax4', quality:100, resolutionUnit:'inch'});`

I am finally getting 4677 x 6622 Pixel but it should be  7016 x 9933 Pixel

Refer the URL for dimension calculations:

https://pixelcalculator.com/en and try with 594mm X 841mm and 200/300 dpi. 

Inspite of applying 300 DPI am still getting TIFF with 200DPI (Because the dimensions of final output image are 4677 x 6622 instead of 7016 x 9933).

**Comment by lovell** [comment]
To control the density at which SVGs are rendered, pass it to the constructor.
```diff
- const converter = sharp()...
+ const converter = sharp({ density: 300 })...
```
https://sharp.pixelplumbing.com/api-constructor

Alternatively, you can pass the required dimensions to `resize()`.

```diff
- const converter = sharp()...
+ const converter = sharp().resize({ width: 7016, height: 9933 })...
```
