### ISSUE TITLE
Change AWS Lambda /tmp to mounted EFS volume

### ISSUE THREAD

**Issue by nishantjiit** [lovell/sharp#3116]
When I try to convert SVG to TIFF with my Nodejs Application deployed on AWS LAMBDA, for the big files it gives me error vips_write: write failed, no space left on device. This is because the size of AWS Lambda /tmp is 512 MB and cannot be increased.

If I mount an EFS volume to my AWS Lambda function then is it possible to tell sharp to use mounted EFS volume instead of /tmp?

**Comment by lovell** [comment]
Did you see https://github.com/lovell/sharp/issues/1851 especially https://github.com/lovell/sharp/issues/1851#issuecomment-529865331 ?

**Comment by rawpixel-vincent** [comment]
you can define environment variables in LAMBDA try to set `TMP=/efs-mount-folder`

**Comment by lovell** [comment]
See also https://twitter.com/julian_wood/status/1465842874457763840

I'll close as this is a Lambda thing rather than a sharp thing.
