### ISSUE TITLE
Can I estimate the memory usage of sharp to load a file given the file size and format?

### ISSUE THREAD

**Issue by rawpixel-vincent** [lovell/sharp#3119]
## Question about an existing feature

**Is it possible to estimate the memory usage of a the simplest sharp pipeline given file size and format of the input file?**

### What are you trying to achieve?

I am deploying lambda functions that are using sharp to load and process tiff, jpeg, png files that could range to few kb to gigabytes.

I'm creating one function per format and file size range that are given different memory allocation and `VIPS_DISC_THRESHOLD` based on the file size.

So far I've been adjusting those ranges based on failures. And I found that the file sizes was not giving consistent memory usage and had to increase the memory allocated for smaller file size to cope with few cases.
Or seeing large file size consuming a lot less memory than smaller ones.

I wonder if there is a more reliable way to go about it. 

The memory allocated I'm curious about is only for the simplest pipeline operation, and it doesn't need to be accurate but rather consistent.

```

  new Promise((resolve, reject) => {
    const image = sharp(fileBuffer, {
      density: 300,
      // limitInputPixels is also defined for each ranges,
      failOnError: false,
    });
  
    image.withMetadata();

    if (isPng) {
      image.rotate().png();
    } else {
      image.rotate().jpeg({
        quality: 100,
      });
    }

    image.toBuffer((err, buffer, info) => {
      if (err) {
        reject(err);
      } else {
        resolve({ buffer, info });
      }
    });
  });
```

I understand if there is no consistent way to go about this, any clue is appreciated.

**Comment by lovell** [comment]
When you say "file size", do you mean the size in bytes of the file, or the dimensions of image based on header metadata? For the former, unlikely, for the latter, maybe but you'll need to experiment.

Remember that with AWS Lambda you get more CPU time when you request more RAM, so my advice is usually to give it as much memory as possible as that'll be more efficient in terms of time, money and maybe even energy consumption.

https://sharp.pixelplumbing.com/install#aws-lambda

**Comment by rawpixel-vincent** [comment]
I meant file size in bytes. I don't know the dimensions of the files at that point (I actually use sharp to know it).

I could work around to get the dimensions, but given my requirement, your comment on the time and energy consumption make a lot of sense.

For info thats what i got now:

```
const sizes = [
      { size: '3mb', memorySize: 768 },
      { size: '4mb', memorySize: 1280 },
      { size: '120mb', memorySize: 2048 },
      { memorySize: 4096 },
];
```

I'm thinking of getting rid of that now and run with 2048m with a fallback to 4096m on failure.

thank you

**Comment by rawpixel-vincent** [comment]
I've started to develop a library based on this, to provide boilerplate code to deploy lambda function that use sharps with sensible default.

My goal is to ship with two pre-coded lambda tasks that handle converting images and on-fly resizing, which will provide the basis to setup any type of tasks.

https://github.com/rawpixel-vincent/sharp-lambda-boilerplate/pull/1
