### ISSUE TITLE
Provide pre-compiled libvips+deps for OS X

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#312]
#42 provided the infrastructure and initial support for 64-bit Windows and Linux binaries.

- [x] **OS X**

We could use Travis' OS X environment + homebrew e.g.  https://github.com/lovell/package-libvips-darwin-x64/blob/master/.travis.yml

If we use this approach a shell script is required to update the paths in the .dylib files - this will look something like:
```
for each .dylib file (e.g. libvips.42.dylib):
- otool libvips.42.dylib
- install_name_tool -id @rpath/libvips.42.dylib libvips.42.dylib
- for any entry that does not start with /usr/lib (e.g. libGraphicsMagick.3.dylib):
  - install_name_tool -change /usr/local/opt/graphicsmagick/lib/libGraphicsMagick.3.dylib @rpath/libGraphicsMagick.3.dylib libvips.42.dylib
```

- [x] **ARM**

~~Best bet is to use a first generation Raspberry Pi Model B to compile ARMv6 binaries, possibly via Hypriot.~~ Support for ARMv6+ added in v0.12.2.

**Comment by lovell** [comment]
ARMv6 build machine in action. This might take some time.
![](https://cloud.githubusercontent.com/assets/210965/12070732/6fa8683c-b07e-11e5-8a93-143710485d94.jpg)

**Comment by lovell** [comment]
Commit a0e034a adds support for building and using pre-compiled libvips binaries on ARMv6+.

This will be included in sharp v0.12.2.

**Comment by lovell** [comment]
@davej Installation of `libvips` is already relatively easy on [OS X](http://sharp.dimens.io/en/stable/install/#mac-os) via:
```sh
brew install homebrew/science/vips
```
This task relates to making it even easier.

**Comment by homerjam** [comment]
@lovell I **think** what @davej means is - could you fallback to using sips instead of vips from sharp in order to support using sharp in electron apps on osx.

@davej can you clarify? And that link to sips leads nowhere? Can I find more info on that somewhere else? Thanks!

Just to mention - I'm mega interested in making an electron app that can use sharp cross platform under the hood.

**Comment by davej** [comment]
@homerjam [Here's the cached man page](https://webcache.googleusercontent.com/search?q=cache:KrTgSxrGjsgJ:https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/sips.1.html+&cd=1&hl=en&ct=clnk&gl=ie). I ended up creating my own lib to do cross-platform resizing of images on Electron, not the most performant approach but it works: https://github.com/davej/electron-image-resize

**Comment by lovell** [comment]
There's now an experimental [packaging script for OS X](https://github.com/lovell/package-libvips-darwin/tree/dylib-rpath) and commit https://github.com/lovell/sharp/commit/dac865477e0a2efa3f55ccc7f2df9753858f858c on the `osx-binaries` branch takes advantage of the pre-built binaries it creates.

I'd very much appreciate it if everyone interested in this feature can test it by running the following on a Mac where vips is not already installed (or has been removed via `brew unlink vips` or `brew uninstall vips`) and report back here.

```sh
npm install lovell/sharp#osx-binaries
```

**Comment by digital-flowers** [comment]
i am working on nw.js application and i was trying to make sharp portable so  i have tested this on OSX and it is working perfectly, Amazing :)
anyway i have some notes for anybody will use it:
1- if you have vips already installed you should uninstall it and then you can npm rebuild and it will work 
2- if you want image magick for some strange reason you need to copy the file  /usr/local/lib/libltdl.7.dylib manually to sharp/lib folder and do npm rebuild 
3- if you want to test your job you can use https://github.com/kwin/macdependency where you can see where all sharp.node library are pointing and if there is any error it will display it to you for example
![image](https://cloud.githubusercontent.com/assets/5216291/16381642/7abe341a-3cb8-11e6-9d97-461dbb30fe8d.png)

**Comment by sharpfuryz** [comment]
I would like to notice: this solution is working unless your app is packed in asar (which is default in electron-bootstrap). In my case it caused errors because nodejs can't resolve libraries inside app.asar, so I unpack to app/ and it fixed this issue.
![error](https://cloud.githubusercontent.com/assets/1875643/16923399/bbc2ee40-4d22-11e6-8776-498302f4a796.png)

**Comment by lovell** [comment]
Commit 36bfbde on the `pencil` (v0.16.0) branch adds the use of pre-compiled binaries for OS X.

https://travis-ci.org/lovell/sharp/jobs/147224162

**Comment by AlekzZz** [comment]
I get the following error:

`npm install -S lovell/sharp#osx-binaries`

npm ERR! git rev-list -n1 osx-binaries: fatal: ambiguous argument 'osx-binaries': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 osx-binaries: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 osx-binaries: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 osx-binaries: 
npm ERR! git rev-list -n1 osx-binaries: fatal: ambiguous argument 'osx-binaries': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 osx-binaries: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 osx-binaries: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 osx-binaries: 
npm ERR! git rev-list -n1 osx-binaries: fatal: ambiguous argument 'osx-binaries': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 osx-binaries: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 osx-binaries: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 osx-binaries: 
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "install" "-S" "lovell/sharp#osx-binaries"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.5
npm ERR! code 128

**Comment by lovell** [comment]
@AlekzZz Please use `npm install lovell/sharp#pencil` (I've updated my comment too, sorry).

**Comment by digital-flowers** [comment]
if i use "npm install lovell/sharp#pencil" i had the following errors:
clang: error: no such file or directory: 'node_modules/sharp/include'
clang: error: no such file or directory: 'node_modules/sharp/include/glib-2.0'
clang: error: no such file or directory: 'node_modules/sharp/lib/glib-2.0/include'
do i need to add these files manually ?

**Comment by lovell** [comment]
@digital-flowers Those should be created for you. Are you able to share the full npm install log?

**Comment by digital-flowers** [comment]
after trials i have found that this only happened if the project directory has space in it is name, i renamed the folder and it is working now

**Comment by digital-flowers** [comment]
so project folder should have no spaces to make this work

**Comment by lovell** [comment]
@digital-flowers Thanks, it looks like you ran into https://github.com/nodejs/node-gyp/issues/65

**Comment by digital-flowers** [comment]
exactly thank you :)

**Comment by digital-flowers** [comment]
there is any chance to include image magick in this prebuild version? i need it only because of bmp file format.

**Comment by lovell** [comment]
@digital-flowers The pre-built binaries only include shared libraries I'm willing to support and *magick is a security nightmare. Please install vips yourself if you need to use extra libraries and take your own precautions if using untrusted images.

**Comment by digital-flowers** [comment]
yes i understand thank you

**Comment by lovell** [comment]
@digital-flowers Commit da0dc28 on the `pencil` branch might help workaround the spaces-in-path problem.

**Comment by lovell** [comment]
v0.16.0 is now available via npm, providing pre-compiled shared library binaries for OS X.
