### ISSUE TITLE
Is there a way to get the size of an image after resizing?

### ISSUE THREAD

**Issue by adrian154** [lovell/sharp#3120]
Does Sharp offer a simple way to get the size of an image after it has been resized?

Here's roughly what I'm trying to accomplish:

```
const image = sharp(filepath);
// do other stuff with `image`
const thumbnail = image.clone().resize({height: THUMBNAIL_HEIGHT, fit: "inside"});
```

I'm using the inside fit option to automatically determine the correct width for the resized image. I thought `Sharp#metadata()` might be useful but then I read this line in the docs:

>  It does not include operations, such as resize, to be applied to the output image.

Does Sharp support what I am trying to accomplish?

**Comment by rawpixel-vincent** [comment]
yes you can use the info object from toBuffer response

```
/**
 * @param {import('sharp')} sharp
 * @param {string|Buffer} temporaryFilePathOrBuffer
 * @param {*} resizeBounds
 * @returns {Promise<{buffer:Buffer, info:import('sharp').OutputInfo}>}
 */
module.exports.convertSharp = (
  sharp,
  temporaryFilePathOrBuffer,
  resizeBounds = null,
  jpegQuality = 100,
  pathToIcc = null
) =>
  new Promise((resolve, reject) => {
    const image = sharp(temporaryFilePathOrBuffer);

    if (resizeBounds) {
      image.resize({
        height: resizeBounds,
        fit: 'inside',
      });
    }

    image.jpeg({
      quality: jpegQuality,
    });

    image.toBuffer((err, buffer, info) => {
      if (err) {
        reject(err);
      } else {
        resolve({ buffer, info });
      }
    });
  });

const {buffer, info} = await convertSharp(...);
console.log(info.width, info.height);
```

see https://sharp.pixelplumbing.com/api-output#parameters

if you use toFile() the promise resolve to the same object info
e.g. 

`const info = await image.toFile(...);`

you can also pass resolveWithObject option to toBuffer to get the buffer and info into an object like

`const {data, info} = await image.toBuffer({ resolveWithObject: true })`

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by Enchiridion** [comment]
Is there any way to get the updated dimensions without calling toBuffer() first?  Are the image transformations applied earlier simply queued up then only applied during toBuffer()?

**Comment by lovell** [comment]
@Enchiridion The call to `toBuffer()` (or `toFile`, or `pipe`) triggers the pipeline and starts the calculations. If you need the output dimensions before the output is generated then you'll have to calculate these in your own code.

**Comment by guillaume-net** [comment]
Anyway to know what kind of func is applied to the calculated dim? floor/ceil/round?

**Comment by pjhartin** [comment]
Thanks @rawpixel-vincent, I adapted your example with an async variant.

```js
const { info, data } = await sharp(fileOrBuffer)
    .withMetadata()
    .resize({
      width: 3000,
      height: 3000,
      withoutEnlargement: true,
      fit: 'inside'
    })
    .jpeg({
      quality: 80
    })
    .toBuffer({ resolveWithObject: true })
```

The size can then be accessed at `info.size` and the buffer is available at `data.buffer`.

Hope this helps someone else.
