### ISSUE TITLE
Composite on all frames of a gif

### ISSUE THREAD

**Issue by cppvoid** [lovell/sharp#3121]
### What are you trying to achieve?

Add an image over all frames of a gif. I would like to use the library for this and would like to know if there is a way.

### When you searched for similar issues, what did you find that might be related?

The documentation on composite says that it can be used to edit an image. With a gif, only the last image is changed. 

Here is the same Question -> https://github.com/lovell/sharp/issues/2772 but the link does not exists anymore
tile: true not working. It overwrites the entire image, but also each frame -> https://github.com/lovell/sharp/issues/2680
no difference with {pages: -1} -> https://github.com/lovell/sharp/issues/2272

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```
const image = await sharp('./test.gif', {animated: true})
const metadata = await image.metadata()
const imageWidth = metadata.width

const textImage = Buffer.from(
  `<svg width="${imageWidth}" height="45px" xmlns="http://www.w3.org/2000/svg">
      <rect width="100%" height="100%" fill="black"/>
        <text y="9" font-family="Roboto, Helvetica, Arial, sans-serif" font-size="7px" fill="white">
          Test
        </text>
    </svg>`
);

await image.composite([{
  input: textImage,
  gravity: 'south'
}]).toFile("./result.gif"); // Only the last frame has the text overlay
```

**Comment by lovell** [comment]
> tile: true not working. It overwrites the entire image, but also each frame -> https://github.com/lovell/sharp/issues/2680

The use of `tile: true` is the right approach, but it looks like the SVG image you are using as the upper layer when compositing does not have any regions of transparency, so none of the image beneath will be visible.

Perhaps you need to remove the `<rect width="100%" height="100%" fill="black"/>` element?

**Comment by cppvoid** [comment]
Thank you for the quick reply. Now I know how to solve the problem. I wish you a nice day :)
