### ISSUE TITLE
Custom libvips - undefined symbol: _ZNK4vips6VImage7gifsaveEPKcPNS_7VOption

### ISSUE THREAD

**Issue by ServOKio** [lovell/sharp#3123]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `node -e "require('sharp')"` completes without error.
- [x] Running `npm install sharp` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```

  System:
    OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (4) x64 Westmere E56xx/L56xx/X56xx (IBRS update)
    Memory: 431.97 MB / 3.86 GB
    Container: Yes
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 14.19.0 - /usr/bin/node
    npm: 8.5.1 - /home/main~/servokio.net/server/node_modules/.bin/npm
  npmPackages:
    sharp: ^0.30.2 => 0.30.2


```

### What are the steps to reproduce?

Build libvips-8.12.2 with prebuilded `cgif` and `libimagequant` or `quantizr` (just for test) and install
```
## File format support
JPEG load/save with libjpeg:            yes (pkg-config)
JXL load/save with libjxl:              no (dynamic module: no)
JPEG2000 load/save with libopenjp2:     no
 (requires libopenjp2 2.4 or later)
PNG load with libspng:                  yes
 (requires libspng-0.6 or later)
PNG load/save with libpng:              yes (pkg-config libpng >= 1.2.9)
 (requires libpng-1.2.9 or later)
quantisation to 8 bit:                  yes
 (requires libimagequant)
TIFF load/save with libtiff:            yes (pkg-config libtiff-4)
image pyramid save:                     no
 (requires libgsf-1 1.14.26 or later)
HEIC/AVIF load/save with libheif:       yes (dynamic module: no)
WebP load/save with libwebp:            yes
 (requires libwebp, libwebpmux, libwebpdemux 0.6.0 or later)
PDF load with PDFium:                   no
PDF load with poppler-glib:             no (dynamic module: no)
 (requires poppler-glib 0.16.0 or later)
SVG load with librsvg-2.0:              no
 (requires librsvg-2.0 2.34.0 or later)
EXR load with OpenEXR:                  no
OpenSlide support:                      no (dynamic module: no)
 (requires openslide-3.3.0 or later)
Matlab load with matio:                 no
NIfTI load/save with niftiio:           no
FITS load/save with cfitsio:            no
GIF save with cgif:                     yes
 (requires cgif, libimagequant)
Magick package:                         none (dynamic module: no)
Magick major API version:               none
load with libMagickCore:                no
save with libMagickCore:                no
```
Edit `package.json` and set `"libvips": "8.12.2"`
Then `npm install sharp`

### What is the expected behaviour?

Normal work with GIF files

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```js
const image = sharp(`image.gif`);
image.toFormat('gif').toFile('output.jpg', (err, info) => {
    if(err) return console.error(err);
});
```

### Error

```
node: symbol lookup error: /home/main/root/servokio.net/server/node_modules/sharp/build/Release/sharp-linux-x64.node: undefined symbol: _ZNK4vips6VImage7gifsaveEPKcPNS_7VOptionE
```

### Please provide sample image(s) that help explain this problem

Any GIF image

**Comment by lovell** [comment]
What is the output of running the following command?

```sh
ldd /home/main/root/servokio.net/server/node_modules/sharp/build/Release/sharp-linux-x64.node
```

**Comment by lovell** [comment]
What is the output of running the following command?
```sh
strings /usr/local/lib/libvips-cpp.so.42 | grep gifsave
```

**Comment by ServOKio** [comment]
> 

```
_ZNK4vips6VImage7gifsaveEPKcPNS_7VOptionE
_ZNK4vips6VImage14gifsave_bufferEPNS_7VOptionE
_ZNK4vips6VImage14gifsave_targetENS_7VTargetEPNS_7VOptionE
gifsave
gifsave_buffer
gifsave_target
_ZNK4vips6VImage7gifsaveEPKcPNS_7VOptionE
gifsave_target
_ZNK4vips6VImage14gifsave_targetENS_7VTargetEPNS_7VOptionE
gifsave_buffer
_ZNK4vips6VImage14gifsave_bufferEPNS_7VOptionE
gifsave
_ZNK4vips6VImage7gifsaveEPKcPNS_7VOptionE
_ZNK4vips6VImage14gifsave_bufferEPNS_7VOptionE
_ZNK4vips6VImage14gifsave_targetENS_7VTargetEPNS_7VOptionE
```

**Comment by lovell** [comment]
Thanks, that looks OK to me. Perhaps multiple, conflicting versions of libvips are present on this machine?

**Comment by ServOKio** [comment]
How can I check this ?

**Comment by marvinroger** [comment]
Hi!

I'm having a similar issue but without a custom libvips, since sharp 0.30.0. Any previous version is fine:

> Something went wrong installing the "sharp" module
> 
>     Error relocating /root/project/node_modules/sharp/build/Release/sharp-linuxmusl-x64.node: _ZNK4vips6VImage7gifsaveEPKcPNS_7VOptionE: symbol not found
> 
>     Possible solutions:
>     - Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
>     - Install for the current linuxmusl-x64 runtime: "npm install --platform=linuxmusl --arch=x64 sharp"
>     - Consult the installation documentation: https://sharp.pixelplumbing.com/install

>   System:
>     OS: Linux 5.11 Alpine Linux
>     CPU: (36) x64 Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
>     Memory: 8.49 GB / 68.58 GB
>     Container: Yes
>     Shell: 1.32.1 - /bin/ash
>   Binaries:
>     Node: 16.10.0 - /usr/local/bin/node
>     Yarn: 3.1.0 - /usr/local/bin/yarn
>     npm: 7.24.0 - /usr/local/bin/npm
>   npmPackages:
>     sharp: 0.30.2 => 0.30.2

Reproduction is easy: just use the `node:16.10.0-alpine` Docker image

**Comment by ServOKio** [comment]
> latest sharp v0.30.2
![2022-03-09_19-53](https://user-images.githubusercontent.com/51263003/157490833-d15e0d03-06ed-446e-a832-226f2fc09fc4.png)
> ....older versions present anywhere....
No, only the vips-8.12.2 build

**Comment by lovell** [comment]
Please can either of you create a Dockerfile or similar that allows someone else to reproduce.

**Comment by marvinroger** [comment]
@lovell I managed to reproduce the issue on a minimal repo: https://github.com/marvinroger/sharp-symbol-issue

It's in fact more subtle than just requiring sharp. I figured out that the issue appears when requiring two different versions of sharp:

- Requiring sharp `0.30.2` then `0.29.3` works fine
- Requiring sharp `0.29.3` then `0.30.2` throws on the `0.30.2` require

The issue is demonstrated on the above repo. Also, I was able to reproduce with musl-x64 and musl-arm64.
The issue is not present on darwin-arm64, but a colleague reported that darwin-x64 failed too (although I can't 100% validate this).

In my case, I'm using sharp on my own project (`0.30.2`) and I have a dependency which depends on `0.29.3`, so the use case for two different versions of sharp in the dependency tree is valid.

By the way, thanks for this awesome lib. 😉

**Comment by lovell** [comment]
@marvinroger Merci, please can you submit a PR to upgrade the version of sharp in any dependency you find using an outdated version. If that's not possible, please let me know which package(s) and I will do this.

There's a work-in-progress PR for libvips to improve symbol visibility that might help with this kind of problem at https://github.com/libvips/libvips/pull/2688

**Comment by lovell** [comment]
The addition of cgif to the prebuilt binaries for GIF output was a bit of an exception in v0.30.0+, but generally it's best to keep the versions in sync throughout the dependency tree.

Windows suffers from this the most, hence there's additional help displayed when a mismatch causes an error:

https://github.com/lovell/sharp/blob/fcbe4e1e01a1461651d1a206137e079e26a33250/lib/sharp.js#L24-L29

Perhaps this logic should have the Windows-only guard removed?

**Comment by marvinroger** [comment]
As illustrated, the problem happens on Alpine too, so I'd say the message is relevant on any OS.
Here's the PR, if you're fine with this change: https://github.com/lovell/sharp/pull/3132

**Comment by lovell** [comment]
@ServOKio Were you able to make any progress with this?

**Comment by ServOKio** [comment]
> @ServOKio Were you able to make any progress with this?

Yes, on version `^0.30.3` everything works fine
