### ISSUE TITLE
Get actual (rotated) width/height from metadata

### ISSUE THREAD

**Issue by mindplay-dk** [lovell/sharp#3124]
### What are you trying to achieve?

In an image server project, I need to check the image dimensions via `metadata()`, so I can decide whether to resize an image, or instead respond with a redirect.

### When you searched for similar feature requests, what did you find that might be related?

There is `rotate()`, which will fix the rotation - the script will use this if it decides to resize the image, but I'm trying to avoid loading images if I'm not going to resize them, so I need to use `metadata()` instead.

The information is of course available in the metadata object as `width`, `height` and `orientation` - but the documentation explicitly says that `orientation` is not taken into account with regards to `width` and `height`, which that means the *meaning* of `width` and `height` might actually be reversed.

### What would you expect the API to look like?

I would propose adding a second pair of properties for the actual (right-side-up) dimensions.

I don't know how you would name these... It's already a bit confusing to have `width` and `height` that might actually be reversed - but changing that would be a nasty breaking change, so I'm not suggesting that.

Instead maybe a new pair of properties named `normalWidth`, `rotatedWidth` or `actualWidth`, etc.?

### What alternatives have you considered?

I know I can implement this myself by checking the `orientation` - but it seems like this requirement is going to be common enough that it's worth adding?

Alternatively, the documentation could include an example of this? It currently states that "EXIF orientation is not taken into consideration", but doesn't offer any advice on how to deal with that.

If I had to guess, [based on this answer](https://stackoverflow.com/questions/7489742/php-read-exif-data-and-adjust-orientation), I would say maybe something along the lines of...

```js
function getNormalSize({ width, height, orientation }) {
  return orientation >= 5
    ? { width: height, height: width }
    : { width, height };
}
```

Did I get it right? EXIF orientation is confusing, and I *know* I'm going to get this wrong, I've done it before. 😅

**Comment by lovell** [comment]
A PR to add your example to the metadata documentation somewhere around [here](https://github.com/lovell/sharp/blob/23033e2050d9ef099ecb02dde0f56f9f23e8d30d/lib/input.js#L345) would be most welcome, thank you.

**Comment by mindplay-dk** [comment]
Still considering this for the API, or do you want to close it? 🙂

**Comment by lovell** [comment]
Let's close for now and see how your documentation addition goes, thanks again for doing that.

My honest opinion about EXIF orientation is that it should not exist, or at least become significantly less common. Manufacturers of camera devices that create images with EXIF orientation are externalising the cost of not auto-rotating images before saving onto their consumers.

**Comment by mindplay-dk** [comment]
That is such a great point. The camera obviously has a gravitational sensor, or it wouldn't be able to put that metadata there in the first place - why aren't they just storing the pixels right-side-up. 🤨

Meanwhile, this leaves me wondering, is there anything actually useful or interesting about exposing this information from the API of an image library? Is it useful to anybody?

If not, perhaps abstracting it away is actually worth considering?

By which I mean:

1. Report the normal, right-side-up width and height from the API.
2. Deprecate (or remove) the `orientation` property.
3. Internally use the `orientation` information to always auto-rotate the image.

Saving an image would always result in a file that is right-side-up - so `rotate` would always be automatically applied (using a private/internal orientation value) and there would be no need to write the orientation info back to metadata in output files.

Code, such as what I just added to the docs, would be useless but harmless, as long as the `orientation` property always returns either `0` or `undefined` - any code that uses the `orientation` property today has to expect it can be `undefined`, because it's optional, so it's not even technically a breaking change.

Code that calls `rotate` with no arguments simply wouldn't have any effect. (I expect that's already true if someone were to call `rotate` twice with no arguments?)

This way we could get rid of the problem entirely.

This is of course assuming we're *certain* that no one needs or wants this information - that it isn't somehow useful to somebody. I can't think of any use case for images being ingested or processed anywhere where you *wouldn't* want to fix the rotation, but maybe this is something you need to check with the community first? (Do you have a way to reaching out to users?)

What do you think?
