### ISSUE TITLE
HEIF images produced from transparent background turn to black backgrounds

### ISSUE THREAD

**Issue by kiloreux** [lovell/sharp#3128]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?
npx: installed 1 in 2.023s

System:
OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
CPU: (8) x64 Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz
Memory: 1.46 GB / 3.84 GB
Container: Yes
Shell: 5.0.17 - /bin/bash
Binaries:
Node: 14.17.5 - ~/.nix-profile/bin/node
Yarn: 1.22.0 - ~/.nix-profile/bin/yarn
npm: 6.14.14 - ~/.nix-profile/bin/npm

### What are the steps to reproduce?

Running the sample code will produce an heif image that has a black background even if you add ensureAlpha.

### What is the expected behaviour?

An image with a normal transparent background like the original PNG.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```
#!/usr/bin/env node

'use strict'

const sharp = require('sharp')

async function resizeImage () {
  try {
    await sharp('elephant.png')
      .ensureAlpha(0)
      .resize({
        width     : 1000,
        height    : 1000,
        background: { r: '255', g: '255', b: '255', alpha: '0' },
      })
      .toFormat('heif')
      .toFile('wow-resized.heif')
  } catch (error) {
    console.log(error)
  }
}

resizeImage()
```

### Please provide sample image(s) that help explain this problem

![xMCMOk3MdS_resize_0_wow](https://user-images.githubusercontent.com/6282557/157485096-2a04236e-48c8-4a0a-863d-969de1ec140a.png)

**Comment by lovell** [comment]
I'm unable to reproduce this using the sample input image and code.

The output is a valid AVIF image with the same transparent background as the PNG when viewed in both Chrome and Firefox. (GitHub does not support attaching .avif files to issues.)

Could this be related to the outdated heif libraries you reported in #3108 ?

**Comment by kiloreux** [comment]
It was related, although not in this context. I will be closing it now since it's solved. Thank you so much for your time. :pray:
