### ISSUE TITLE
exporting to CMKY reverted to RGB when using withMetadata({density: 300})

### ISSUE THREAD

**Issue by artplore** [lovell/sharp#3129]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 4.11 GB / 15.89 GB
  Binaries:
    Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: ^0.30.2 => 0.30.2 
```
### What are the steps to reproduce?

adding `.withMetadata({ density: 300 })`

The image is exported to CMYK as expected. However, when adding `.withMetadata({ density: 300 })` the result image becomes RGB.

### What is the expected behaviour?

Exported file has 300dpi in metadata and is a 32bit CMYK

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```
let pipe = sharp(buffer, { failOnError: false });
pipe = pipe.toColourspace('cmyk');
pipe = pipe.resize(param.resize);
pipe = pipe.withMetadata({ density: 300 }); // Removing this line will export a 32bit CMYK
pipe = pipe.toFormat('jpeg');
pipe = pipe.jpeg({ quality: 100 });
const file = await pipe.toFile('my_file.jpg');
```
### Please provide sample image(s) that help explain this problem

![for-printing](https://user-images.githubusercontent.com/98446371/157486537-c14168b3-3cc4-4b46-8e8c-6b6e640b59b7.jpg)

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/api-output#withmetadata

> This will also convert to and add a web-friendly sRGB ICC profile unless a custom output profile is provided.

You'll need to use the `icc` option of `withMetadata`. Either pass it a filesystem path to a CMYK profile of your choice (these can vary wildly) or use the string "cmyk" to use the built-in profile.

```js
  .withMetadata({ icc: 'cmyk' })
```

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
