### ISSUE TITLE
Use sharp within electron

### ISSUE THREAD

**Issue by tonypee** [lovell/sharp#313]
Im looking to resize images with an electron (http://electron.atom.io/) application. This means that the application cannot have external dependancies, eg installing libvips. Is it possible to link to static binaries? Has anyone done this before for sharp, and/or is it possible?

**Comment by lovell** [comment]
Hello, as of v0.12.0 a precompiled copy of libvips is downloaded and stored in `node_modules` for x64 Windows and Linux users at `npm install` time, so those platforms should "just work".

OS X and ARM are a bit trickier - any help you can provide will be most welcome at #312.

If you've not already seen it, https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md provides some relevant help.

**Comment by kurdin** [comment]
+1

**Comment by kurdin** [comment]
@lovell, for use with electron or nw.js can we just copy brew builded lib binary from /usr/local/Cellar/vips/8.1.1/ to app local folder and rebuild sharp using that library?

**Comment by lovell** [comment]
@kurdin That approach probably won't work as the .dylib files contain absolute path references - see the OS X section of #312

**Comment by lovell** [comment]
Closing this question as there hasn't been any update for a while but please do re-open if help is still required.

**Comment by davej** [comment]
@tonypee: I made a lib for resizing image with Electron: https://github.com/davej/electron-image-resize

**Comment by nantas** [comment]
Hi @lovell 

We are trying to use this excellent module with 32bit of Electron build but got a lot of link error:

```
VError.obj : error LNK2001:  [C:\Users\nantas\fireball-x\fb12\node_modules\sharp\build\libvips-cpp.vcxproj]
VInterpolate.obj : error LNK2001:  [C:\Users\nantas\fireball-x\fb12\node_modules\sharp\build\libvips-cpp.vcxpr oj]
VImage.obj : error LNK2001:  [C:\Users\nantas\fireball-x\fb12\node_modules\sharp\build\libvips-cpp.vcxproj]
C:\Users\nantas\fireball-x\fb12\node_modules\sharp\build\Release\libvips-cpp.dll : fatal error LNK1120: 79 [C: \Users\nantas\fireball-x\fb12\node_modules\sharp\build\libvips-cpp.vcxproj]
```

I've read that on Windows the precompiled libvips are downloaded during `npm install` and is probably x64 arch only. Is there any way we can compile the library for `ia32` arch ourselves?

Thanks a lot!

**Comment by lovell** [comment]
@nantas Not without a lot of pain. https://github.com/jcupitt/build-win32 might provide some guidance, but I am unable to help further with 32-bit Windows support. Good luck!
