### ISSUE TITLE
Difference between metadata sizes and toBuffer sizes of image ?

### ISSUE THREAD

**Issue by g-abhishek** [lovell/sharp#3130]
### What are you trying to achieve?
I am confused in the sizes of image generated after `metadata()` and `toBuffer()`. what is the differnce between the sizes of images.
I have provided the sample code with outputs, you can see the difference in sizes of image

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```

const file = fs.readFileSync("sample.png")
output: - 
<Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 13 88 00 00 13 88 08 03 00 00 00 6a 46 77 f9 00 00 03 00 50 4c 54 45 2f 1f 1d 2a 1a 19 29 19 18 ... 1676953 more bytes>

const sharpMetadata = await sharp(file).metadata()
output :-
{
  format: 'png',
  size: 1677003,
  width: 5000,
  height: 5000,
  space: 'srgb',
  channels: 4,
  depth: 'uchar',
  density: 72,
  isProgressive: false,
  paletteBitDepth: 8,
  hasProfile: false,
  hasAlpha: true
}


const {data, info} = await sharp(file).toBuffer({ resolveWithObject: true });
output : - 
<Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 13 88 00 00 13 88 08 06 00 00 00 5d 98 87 cb 00 00 00 09 70 48 59 73 00 00 0b 13 00 00 0b 13 01 ... 3270296 more bytes> {
  format: 'png',
  width: 5000,
  height: 5000,
  channels: 4,
  premultiplied: false,
  size: 3270346
}

```

**Comment by lovell** [comment]
The value from `metadata` relates to the input. The value from `toBuffer` relates to the output, which is created by decoding pixel values from the input and re-encoding.

I notice the input in this example has `paletteBitDepth` set, so you might want to add `.png({ palette: true })` to your code to ensure the ouput more closely matches the input.

https://sharp.pixelplumbing.com/api-output#png

**Comment by g-abhishek** [comment]
means after `toBuffer()`, if i use `toFile()` of output buffer, it will increase the image size as compared to the original one
am i right?

**Comment by lovell** [comment]
A call to `toFile` or `toBuffer` will almost always generate different output compared with the input, so should be treated as a "lossy" operation. Whether the output is larger or smaller depends entirely upon the processing operations/options you're using.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by g-abhishek** [comment]
Hi Lovell, there's some doubt while using `.png({ palette: true })`, why does it decreases the quality of the png image?

And I have one question, Is there any way to maintain the original size of an image while using `.toBuffer()`, because it increases the size?

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/api-output#png

> Set `palette` to `true` for slower, indexed PNG output.

Indexed PNG images that use a quantised palette are lossy.

https://en.wikipedia.org/wiki/Portable_Network_Graphics#Lossy_PNG_compression
