### ISSUE TITLE
The kernel doesn't seem to be increasing the quality of my image

### ISSUE THREAD

**Issue by Br3ikros** [lovell/sharp#3134]
In a previous question, I have been told to use kernel: "nearest" to increase the quality and resolution of an image that I am trying to resize to a bigger image than it is.

Say I have an image of 600 x 600, what I do is this:
.resize({height: 1800, width: 1800, kernel: "nearest"})
instead of this:
.resize({height: 1800, width: 1800})

However, the resolution and quality of the newly generated image does not seem to be improving, looking the same in both examples

### What are you trying to achieve?

I'm trying to go from this image:
![image](https://user-images.githubusercontent.com/26491229/158032594-e0404da3-1657-40e9-bbec-8010d88e13f0.png)

to this one:
![image](https://user-images.githubusercontent.com/26491229/158032589-920777b2-c472-41a9-8203-96d387bc6986.png)

Is it even possible?

**Comment by lovell** [comment]
Let's continue this in the original issue you opened at https://github.com/lovell/sharp/issues/3125 - please don't double post.
