### ISSUE TITLE
Negate doesn't work with create constructor

### ISSUE THREAD

**Issue by petrzjunior** [lovell/sharp#3139]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Linux 5.16 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 10.56 GB / 23.20 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.9.1 - ~/.nvm/versions/node/v16.9.1/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 7.21.1 - ~/.nvm/versions/node/v16.9.1/bin/npm
```

### What are the steps to reproduce?

```js
sharp({
  create: {
    width: 2,
    height: 2,
    channels: 3,
    background: { r: 10, g: 20, b: 30 }
  }
})
.negate()
.negate()
.toBuffer(function(err, data, info) {
  console.log('data', data);
});
```

### What is the expected behaviour?

Expected output: `data <Buffer 0a 14 1e 0a 14 1e 0a 14 1e 0a 14 1e>`
Actual output: `data <Buffer 00 00 00 00 00 00 00 00 00 00 00 00>`

### Additional information

Unit tests cover the case of loading PNG and JPEG which run correctly. But constructing the image manually via `create {}` turns all bytes into `00`.

Calling `negate` should negate the image, but `00` is instead set to all bytes. When `negate(true)` is called, `00` is set to all bytes expect for the alpha channel, which is kept untouched.

**Comment by lovell** [comment]
Thanks for reporting this. It looks like the bit depth of newly-created images was not always being correctly set internally, which triggered a float/int mix-up in the negate operation.

Commit https://github.com/lovell/sharp/commit/1d3693695495b53348a215586975852d9a537136 fixes this, adds a unit test that would previously have failed, and also simplifies and corrects the selection of the relevant colourspace.

**Comment by petrzjunior** [comment]
Thank you for fixing this. I will try it once the next version is out.

**Comment by lovell** [comment]
v0.30.4 now available, thanks again for reporting.

**Comment by bert27** [comment]
negate leaves me with an empty image.

const processedBuffer = await sharp(imageScreen)
.extract({ left: x, top: y, width, height })
.resize({ width: 1400, height: 360 })
.normalize()
.toBuffer()
.then((buffer) => {
return sharp(buffer)
.ensureAlpha() // Ensure the image has an alpha channel
.greyscale() // Convert the image to grayscale
.threshold(128) // Apply threshold, adjust value as needed
.toBuffer();
});

version: 0.33.5
