### ISSUE TITLE
Luminosity Masking Effect when Compositing

### ISSUE THREAD

**Issue by thesoulkiller** [lovell/sharp#3140]
### What are you trying to achieve?

Hello,
I'm using the composite function to composite multiple layers into one. In photoshop I'm using one of the layers as a luminosity mask so that some lights occur more bright but it doesn't change any coloring or so.

I've looked into https://www.cairographics.org/operators/  and I've found that I should use `CAIRO_OPERATOR_HSL_LUMINOSITY` method to achieve luminosity masking.

Is there any ways to do this operation in `.composite()` function ?

Thanks in advance !

**Comment by lovell** [comment]
Hi, the non-separable blend modes are currently unsupported in libvips.

https://www.libvips.org/API/current/libvips-conversion.html#VipsBlendMode

**Comment by thesoulkiller** [comment]
Thank you, I've migrated to https://github.com/Automattic/node-canvas for this particular reason
