### ISSUE TITLE
Input image form web url

### ISSUE THREAD

**Issue by kvetoslavnovak** [lovell/sharp#3141]
### What are you trying to achieve?

It would be great if sharp is able to input images from web urls. 
Similar to Jimp library like in this working example:
```
var Jimp = require('jimp');

  Jimp.read(
    "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
  )
    .then((image) => {
      image.write("GoogleImage.jpg");
    })
    .catch((err) => {
      console.log(err);
    });
```
### When you searched for similar feature requests, what did you find that might be related?

See example here. For now I am using node fetch to get the image from web url.

### What would you expect the API to look like?

See example here-above

### What alternatives have you considered?

Using node fetch or use Jimp.

### Please provide sample image(s) that help explain this feature

N/A

**Comment by lovell** [comment]
You'll need to add your own code to handling networking and all the additional problems this can bring - please see #1901
