### ISSUE TITLE
Is there a way to compose two images so the transparent background of one takes over the black background of the other?

### ISSUE THREAD

**Issue by Br3ikros** [lovell/sharp#3142]
### What are you trying to achieve?

I have image A. image A is an image with some transparent parts. Image A has a low resolution, so I send it over an AI Image Resolution API, and I get back a better version of that image but in jpeg format, which we call image B. Because image B is in jpeg format, the transparent parts are now black. 
My question is: is there a way to convert those black parts back to transparent, distinguishing between the parts that are black because they used to be transparent and the parts that should actually be black in the image? 

My idea was to compare the original image A with the new image B, assuming they are of the same size, and then make it so the transparent parts of Image A take over image B. Is there a way to do this with Sharp?

### When you searched for similar issues, what did you find that might be related?

I tried to simply convert the jpeg to png with sharp by saying .png() but the black remains and it is not converted back to transparent. Not sure what I should do

### Please provide sample image(s) that help explain this question

image A (png with transparent borders)
https://ratdao.mypinata.cloud/ipfs/QmVv7jcg4q1LdPgmM8pwQ3ia9VtYdzLexeCFujeakmF4md
image B (jpeg with black borders)
https://api.deepai.org/job-view-file/ffddfdc3-92af-4e0d-bbc4-1ee44118e542/outputs/output.jpg

**Comment by lovell** [comment]
The sample image B responds with 404.

Did you try all of the blend modes detailed at https://sharp.pixelplumbing.com/api-composite ? Perhaps try `out` or `dest-out`.

**Comment by Br3ikros** [comment]
hi. Sorry, I'll resend the image B, I saved it this time!
https://i.ibb.co/2d9Gp9J/output.jpg

**Comment by lovell** [comment]
@Br3ikros Were you able to make any progress with this?

**Comment by Br3ikros** [comment]
Hi! Sorry for the late reply! Yes i managed to! I don't have the code in
fron of me exactly but it was basically using blend functionality to create
a map to then compose again with the original image.
