### ISSUE TITLE
webp always same file size

### ISSUE THREAD

**Issue by wkng** [lovell/sharp#3143]
### What are you trying to achieve?
Im using sharp and want to convert our png/jpg images to webp.
did some testing to see if i can shrink the file size a bit but always get the same size.

Some example i used to test if i can get smaller images

    .resize({ width: IMAGE_WIDTH })
    .toFormat('webp')
    .webp({quality: 100})
    .toBuffer();

    .resize({ width: IMAGE_WIDTH })
    .webp({quality: 75})
    .toFormat('webp')
    .toBuffer();

    .resize({ width: IMAGE_WIDTH })
    .toFormat('webp')
    .webp({ nearLossless: true, quality: 50 })
    .toBuffer();

I'm quite new to this so maybe this is a correct behavior.
just curious if i'm doing something wrong

**Comment by lovell** [comment]
Please can you provide a sample input image and the complete code that allows someone else to reproduce different output image file sizes.

**Comment by wkng** [comment]
Did some mor testing now after lunch and my images has gone from  1mb to 100kb so maybe it was an cache in aws gateway.. you can close the issue
