### ISSUE TITLE
Issue: Rotate the image when using the resize function

### ISSUE THREAD

**Issue by abdooo9** [lovell/sharp#3144]
When I try to resize the image with sharp and save it rotates 90 degrees, I don't use any rotation function or anything.

Why does this happen and how to solve it?
```js
sharp(`./tmp/before/file.jpg`).resize(512, 512).toFile(`./tmp/after/file.jpg`)
```

**Comment by lovell** [comment]
Hi, it looks like you've ignored/deleted the issue template, which asks for a sample image.

My best guess would be that your input image contains an EXIF Orientation. If you want the output image to also contain this, use https://sharp.pixelplumbing.com/api-output#withmetadata

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details, including a sample image, if further assistance is required.
