### ISSUE TITLE
byteOffset of typedArray is not handled properly

### ISSUE THREAD

**Issue by codepage949** [lovell/sharp#3145]
https://github.com/lovell/sharp/blob/b609df4b48b46b6f6e2f0a9d81bb950fae80236f/lib/input.js#L38-L42

i think L42 should be like below to handle typedArray with byteOffset.

```
inputDescriptor.buffer = Buffer.from(input.buffer, input.byteOffset, input.byteLength);
```

using byteOffset seems unusal case but it will be nice to handle it.

**Comment by lovell** [comment]
Hello, thank you very much for the PR to fix this. Is this a problem you've run into that is actively preventing your use of sharp, or is this more of a theoretical future problem that others may find? I ask only as a way to determine the urgency of the fix.

**Comment by codepage949** [comment]
@lovell hello, it is preventing my use of sharp.

**Comment by gacord23** [comment]
@lovell I've typically seen a Uint8ClampedArray byteLength be 1-byte smaller than the image size as given in the metadata (height x width x channels).  my manual work around is to check for that delta and if so, then i:

 `Buffer.concat([typedArray], imagePixels)`
 
 @codepage949 perhaps you could add unit test to your PR to demonstrate the problem and the fix here?

**Comment by gacord23** [comment]
@lovell I've typically seen a Uint8ClampedArray byteLength be 1-byte smaller than the image size as given in the metadata (height x width x channels).  my manual work around is to check for that delta and if so, then i:

 `Buffer.concat([typedArray], imagePixels)`
 
 @codepage949 perhaps you could add unit test to your PR to demonstrate the problem and the fix here?

**Comment by lovell** [comment]
v0.30.4 now available, thank you very much for adding this feature.
