### ISSUE TITLE
ARMv7: Sharp won't install on Alpine 3.12 

### ISSUE THREAD

**Issue by hardillb** [lovell/sharp#3150]
## Possible install-time or require-time problem

- [x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Is this a problem with filesystem permissions?

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7 or later, does the user running `npm install` own the directory it is run in?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

### What is the complete output of running `npm install --verbose sharp`?

<details>

/data $ npm install --verbose sharp
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@6.14.15
npm info using node@v14.18.2
npm verb npm-session 537e6e739ad2a6fe
npm http fetch GET 200 https://registry.npmjs.org/sharp 157ms (from cache)
npm timing stage:loadCurrentTree Completed in 583ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 3ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 27ms
npm http fetch GET 200 https://registry.npmjs.org/color 341ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 340ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/node-addon-api 338ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/semver 320ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/simple-get 320ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/tar-fs 319ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/tunnel-agent 300ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/prebuild-install 590ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/color-convert 27ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/color-string 32ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/color-name 19ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle 12ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 15ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/minimist 135ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/expand-template 147ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/mkdirp-classic 142ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/node-abi 141ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/rc 168ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/github-from-package 240ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/pump 318ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/npmlog 328ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/napi-build-utils 347ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/lru-cache 15ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/yallist 11ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/are-we-there-yet 56ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/console-control-strings 58ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/gauge 64ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/set-blocking 67ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/delegates 14ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/aproba 70ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/has-unicode 71ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/signal-exit 74ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/string-width 76ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/strip-ansi 78ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/wide-align 80ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/object-assign 92ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/is-fullwidth-code-point 23ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/code-point-at 30ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/number-is-nan 13ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ansi-regex 135ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/once 30ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/end-of-stream 89ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/wrappy 86ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/ini 28ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/deep-extend 35ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/strip-json-comments 40ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/decompress-response 26ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/simple-concat 28ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/mimic-response 14ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/tar-stream 19ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/chownr 107ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/bl 32ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/fs-constants 35ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/readable-stream 91ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/buffer 98ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/base64-js 18ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/ieee754 21ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 2741ms
npm timing stage:loadIdealTree Completed in 2946ms
npm timing stage:generateActionsToTake Completed in 75ms
npm verb correctMkdir /usr/src/node-red/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /usr/src/node-red/.npm/_locks/staging-accc372ed0ccb0d8.lock for /data/node_modules/.staging
npm timing audit submit Completed in 1212ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 1213ms
npm timing audit body Completed in 29ms
npm timing action:extract Completed in 1813ms
npm timing action:finalize Completed in 306ms
npm timing action:refresh-package-json Completed in 680ms
npm info lifecycle ansi-regex@2.1.1~preinstall: ansi-regex@2.1.1
npm info lifecycle aproba@1.2.0~preinstall: aproba@1.2.0
npm info lifecycle base64-js@1.5.1~preinstall: base64-js@1.5.1
npm info lifecycle readable-stream@3.6.0~preinstall: readable-stream@3.6.0
npm info lifecycle chownr@1.1.4~preinstall: chownr@1.1.4
npm info lifecycle code-point-at@1.1.0~preinstall: code-point-at@1.1.0
npm info lifecycle color-name@1.1.4~preinstall: color-name@1.1.4
npm info lifecycle color-convert@2.0.1~preinstall: color-convert@2.0.1
npm info lifecycle console-control-strings@1.1.0~preinstall: console-control-strings@1.1.0
npm info lifecycle deep-extend@0.6.0~preinstall: deep-extend@0.6.0
npm info lifecycle delegates@1.0.0~preinstall: delegates@1.0.0
npm info lifecycle are-we-there-yet@1.1.7~preinstall: are-we-there-yet@1.1.7
npm info lifecycle detect-libc@2.0.1~preinstall: detect-libc@2.0.1
npm info lifecycle expand-template@2.0.3~preinstall: expand-template@2.0.3
npm info lifecycle fs-constants@1.0.0~preinstall: fs-constants@1.0.0
npm info lifecycle github-from-package@0.0.0~preinstall: github-from-package@0.0.0
npm info lifecycle has-unicode@2.0.1~preinstall: has-unicode@2.0.1
npm info lifecycle ieee754@1.2.1~preinstall: ieee754@1.2.1
npm info lifecycle buffer@5.7.1~preinstall: buffer@5.7.1
npm info lifecycle bl@4.1.0~preinstall: bl@4.1.0
npm info lifecycle ini@1.3.8~preinstall: ini@1.3.8
npm info lifecycle is-arrayish@0.3.2~preinstall: is-arrayish@0.3.2
npm info lifecycle mimic-response@3.1.0~preinstall: mimic-response@3.1.0
npm info lifecycle decompress-response@6.0.0~preinstall: decompress-response@6.0.0
npm info lifecycle minimist@1.2.5~preinstall: minimist@1.2.5
npm info lifecycle mkdirp-classic@0.5.3~preinstall: mkdirp-classic@0.5.3
npm info lifecycle napi-build-utils@1.0.2~preinstall: napi-build-utils@1.0.2
npm info lifecycle number-is-nan@1.0.1~preinstall: number-is-nan@1.0.1
npm info lifecycle is-fullwidth-code-point@1.0.0~preinstall: is-fullwidth-code-point@1.0.0
npm info lifecycle object-assign@4.1.1~preinstall: object-assign@4.1.1
npm info lifecycle set-blocking@2.0.0~preinstall: set-blocking@2.0.0
npm info lifecycle signal-exit@3.0.7~preinstall: signal-exit@3.0.7
npm info lifecycle simple-concat@1.0.1~preinstall: simple-concat@1.0.1
npm info lifecycle simple-swizzle@0.2.2~preinstall: simple-swizzle@0.2.2
npm info lifecycle color-string@1.9.0~preinstall: color-string@1.9.0
npm info lifecycle strip-ansi@3.0.1~preinstall: strip-ansi@3.0.1
npm info lifecycle string-width@1.0.2~preinstall: string-width@1.0.2
npm info lifecycle strip-json-comments@2.0.1~preinstall: strip-json-comments@2.0.1
npm info lifecycle rc@1.2.8~preinstall: rc@1.2.8
npm info lifecycle readable-stream@3.6.0~preinstall: readable-stream@3.6.0
npm info lifecycle tunnel-agent@0.6.0~preinstall: tunnel-agent@0.6.0
npm info lifecycle wide-align@1.1.5~preinstall: wide-align@1.1.5
npm info lifecycle gauge@2.7.4~preinstall: gauge@2.7.4
npm info lifecycle npmlog@4.1.2~preinstall: npmlog@4.1.2
npm info lifecycle wrappy@1.0.2~preinstall: wrappy@1.0.2
npm info lifecycle once@1.4.0~preinstall: once@1.4.0
npm info lifecycle end-of-stream@1.4.4~preinstall: end-of-stream@1.4.4
npm info lifecycle tar-stream@2.2.0~preinstall: tar-stream@2.2.0
npm info lifecycle pump@3.0.0~preinstall: pump@3.0.0
npm info lifecycle tar-fs@2.1.1~preinstall: tar-fs@2.1.1
npm info lifecycle sharp@0.30.3~preinstall: sharp@0.30.3
npm info lifecycle prebuild-install@7.0.1~preinstall: prebuild-install@7.0.1
npm info lifecycle node-addon-api@4.3.0~preinstall: node-addon-api@4.3.0
npm info lifecycle color@4.2.1~preinstall: color@4.2.1
npm info lifecycle node-abi@3.8.0~preinstall: node-abi@3.8.0
npm info lifecycle semver@7.3.5~preinstall: semver@7.3.5
npm info lifecycle lru-cache@6.0.0~preinstall: lru-cache@6.0.0
npm info lifecycle yallist@4.0.0~preinstall: yallist@4.0.0
npm info lifecycle simple-get@4.0.1~preinstall: simple-get@4.0.1
npm timing action:preinstall Completed in 149ms
npm info linkStuff ansi-regex@2.1.1
npm info linkStuff aproba@1.2.0
npm info linkStuff base64-js@1.5.1
npm info linkStuff readable-stream@3.6.0
npm info linkStuff chownr@1.1.4
npm info linkStuff code-point-at@1.1.0
npm info linkStuff color-name@1.1.4
npm info linkStuff color-convert@2.0.1
npm info linkStuff console-control-strings@1.1.0
npm info linkStuff deep-extend@0.6.0
npm info linkStuff delegates@1.0.0
npm info linkStuff are-we-there-yet@1.1.7
npm info linkStuff detect-libc@2.0.1
npm info linkStuff expand-template@2.0.3
npm info linkStuff fs-constants@1.0.0
npm info linkStuff github-from-package@0.0.0
npm info linkStuff has-unicode@2.0.1
npm info linkStuff ieee754@1.2.1
npm info linkStuff buffer@5.7.1
npm info linkStuff bl@4.1.0
npm info linkStuff ini@1.3.8
npm info linkStuff is-arrayish@0.3.2
npm info linkStuff mimic-response@3.1.0
npm info linkStuff decompress-response@6.0.0
npm info linkStuff minimist@1.2.5
npm info linkStuff mkdirp-classic@0.5.3
npm info linkStuff napi-build-utils@1.0.2
npm info linkStuff number-is-nan@1.0.1
npm info linkStuff is-fullwidth-code-point@1.0.0
npm info linkStuff object-assign@4.1.1
npm info linkStuff set-blocking@2.0.0
npm info linkStuff signal-exit@3.0.7
npm info linkStuff simple-concat@1.0.1
npm info linkStuff simple-swizzle@0.2.2
npm info linkStuff color-string@1.9.0
npm info linkStuff strip-ansi@3.0.1
npm info linkStuff string-width@1.0.2
npm info linkStuff strip-json-comments@2.0.1
npm info linkStuff rc@1.2.8
npm verb linkBins [ { rc: 'cli.js' }, '/data/node_modules/.bin', false ]
npm info linkStuff readable-stream@3.6.0
npm info linkStuff tunnel-agent@0.6.0
npm info linkStuff wide-align@1.1.5
npm info linkStuff gauge@2.7.4
npm info linkStuff npmlog@4.1.2
npm info linkStuff wrappy@1.0.2
npm info linkStuff once@1.4.0
npm info linkStuff end-of-stream@1.4.4
npm info linkStuff tar-stream@2.2.0
npm info linkStuff pump@3.0.0
npm info linkStuff tar-fs@2.1.1
npm info linkStuff simple-get@4.0.1
npm info linkStuff yallist@4.0.0
npm info linkStuff lru-cache@6.0.0
npm info linkStuff semver@7.3.5
npm verb linkBins [ { semver: 'bin/semver.js' }, '/data/node_modules/.bin', false ]
npm info linkStuff node-abi@3.8.0
npm info linkStuff color@4.2.1
npm info linkStuff node-addon-api@4.3.0
npm info linkStuff prebuild-install@7.0.1
npm verb linkBins [ { 'prebuild-install': 'bin.js' }, '/data/node_modules/.bin', false ]
npm info linkStuff sharp@0.30.3
npm timing action:build Completed in 208ms
npm info lifecycle ansi-regex@2.1.1~install: ansi-regex@2.1.1
npm info lifecycle aproba@1.2.0~install: aproba@1.2.0
npm info lifecycle base64-js@1.5.1~install: base64-js@1.5.1
npm info lifecycle readable-stream@3.6.0~install: readable-stream@3.6.0
npm info lifecycle chownr@1.1.4~install: chownr@1.1.4
npm info lifecycle code-point-at@1.1.0~install: code-point-at@1.1.0
npm info lifecycle color-name@1.1.4~install: color-name@1.1.4
npm info lifecycle color-convert@2.0.1~install: color-convert@2.0.1
npm info lifecycle console-control-strings@1.1.0~install: console-control-strings@1.1.0
npm info lifecycle deep-extend@0.6.0~install: deep-extend@0.6.0
npm info lifecycle delegates@1.0.0~install: delegates@1.0.0
npm info lifecycle are-we-there-yet@1.1.7~install: are-we-there-yet@1.1.7
npm info lifecycle detect-libc@2.0.1~install: detect-libc@2.0.1
npm info lifecycle expand-template@2.0.3~install: expand-template@2.0.3
npm info lifecycle fs-constants@1.0.0~install: fs-constants@1.0.0
npm info lifecycle github-from-package@0.0.0~install: github-from-package@0.0.0
npm info lifecycle has-unicode@2.0.1~install: has-unicode@2.0.1
npm info lifecycle ieee754@1.2.1~install: ieee754@1.2.1
npm info lifecycle buffer@5.7.1~install: buffer@5.7.1
npm info lifecycle bl@4.1.0~install: bl@4.1.0
npm info lifecycle ini@1.3.8~install: ini@1.3.8
npm info lifecycle is-arrayish@0.3.2~install: is-arrayish@0.3.2
npm info lifecycle mimic-response@3.1.0~install: mimic-response@3.1.0
npm info lifecycle decompress-response@6.0.0~install: decompress-response@6.0.0
npm info lifecycle minimist@1.2.5~install: minimist@1.2.5
npm info lifecycle mkdirp-classic@0.5.3~install: mkdirp-classic@0.5.3
npm info lifecycle napi-build-utils@1.0.2~install: napi-build-utils@1.0.2
npm info lifecycle number-is-nan@1.0.1~install: number-is-nan@1.0.1
npm info lifecycle is-fullwidth-code-point@1.0.0~install: is-fullwidth-code-point@1.0.0
npm info lifecycle object-assign@4.1.1~install: object-assign@4.1.1
npm info lifecycle set-blocking@2.0.0~install: set-blocking@2.0.0
npm info lifecycle signal-exit@3.0.7~install: signal-exit@3.0.7
npm info lifecycle simple-concat@1.0.1~install: simple-concat@1.0.1
npm info lifecycle simple-swizzle@0.2.2~install: simple-swizzle@0.2.2
npm info lifecycle color-string@1.9.0~install: color-string@1.9.0
npm info lifecycle strip-ansi@3.0.1~install: strip-ansi@3.0.1
npm info lifecycle string-width@1.0.2~install: string-width@1.0.2
npm info lifecycle strip-json-comments@2.0.1~install: strip-json-comments@2.0.1
npm info lifecycle rc@1.2.8~install: rc@1.2.8
npm info lifecycle readable-stream@3.6.0~install: readable-stream@3.6.0
npm info lifecycle tunnel-agent@0.6.0~install: tunnel-agent@0.6.0
npm info lifecycle wide-align@1.1.5~install: wide-align@1.1.5
npm info lifecycle gauge@2.7.4~install: gauge@2.7.4
npm info lifecycle npmlog@4.1.2~install: npmlog@4.1.2
npm info lifecycle wrappy@1.0.2~install: wrappy@1.0.2
npm info lifecycle once@1.4.0~install: once@1.4.0
npm info lifecycle end-of-stream@1.4.4~install: end-of-stream@1.4.4
npm info lifecycle tar-stream@2.2.0~install: tar-stream@2.2.0
npm info lifecycle pump@3.0.0~install: pump@3.0.0
npm info lifecycle tar-fs@2.1.1~install: tar-fs@2.1.1
npm info lifecycle simple-get@4.0.1~install: simple-get@4.0.1
npm info lifecycle yallist@4.0.0~install: yallist@4.0.0
npm info lifecycle lru-cache@6.0.0~install: lru-cache@6.0.0
npm info lifecycle semver@7.3.5~install: semver@7.3.5
npm info lifecycle node-abi@3.8.0~install: node-abi@3.8.0
npm info lifecycle color@4.2.1~install: color@4.2.1
npm info lifecycle node-addon-api@4.3.0~install: node-addon-api@4.3.0
npm info lifecycle prebuild-install@7.0.1~install: prebuild-install@7.0.1
npm info lifecycle sharp@0.30.3~install: sharp@0.30.3

> sharp@0.30.3 install /data/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.12.2/libvips-8.12.2-linuxmusl-armv7.tar.br
sharp: Installation error: Prebuilt libvips 8.12.2 binaries are not yet available for linuxmusl-armv7
sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm verb lifecycle sharp@0.30.3~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.30.3~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/data/node_modules/sharp/node_modules/.bin:/data/node_modules/.bin:/usr/src/node-red/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle sharp@0.30.3~install: CWD: /data/node_modules/sharp
npm info lifecycle sharp@0.30.3~install: Failed to exec install script
npm timing action:install Completed in 1689ms
npm verb unlock done using /usr/src/node-red/.npm/_locks/staging-accc372ed0ccb0d8.lock for /data/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 340ms
npm timing stage:runTopLevelLifecycles Completed in 10037ms
npm verb stack Error: sharp@0.30.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:400:28)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:400:28)
npm verb stack     at maybeClose (internal/child_process.js:1058:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
npm verb pkgid sharp@0.30.3
npm verb cwd /data
npm verb Linux 5.10.103-v7+
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--verbose" "sharp"
npm verb node v14.18.2
npm verb npm  v6.14.15
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.30.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.30.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 13445ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /usr/src/node-red/.npm/_logs/2022-03-21T09_31_11_116Z-debug.log

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
$ npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp
npx: installed 1 in 4.95s

  System:
    OS: Linux 5.10 Alpine Linux
    CPU: (4) arm ARMv7 Processor rev 4 (v7l)
    Memory: 298.20 MB / 972.75 MB
    Container: Yes
    Shell: 1.31.1 - /bin/ash
  Binaries:
    Node: 14.18.2 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
/data $ apk info musl
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.12/main: No such file or directory
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.12/community: No such file or directory
musl-1.1.24-r10 description:
the musl c library (libc) implementation

musl-1.1.24-r10 webpage:
https://musl.libc.org/

musl-1.1.24-r10 installed size:
499712

```

**Comment by hardillb** [comment]
Just for context all this is running in the nodered/node-red:2.2.2-14 docker container on a Pi 3b. Testing to gather logs and reproduce is done by starting the container then running `docker exect -it <container name> /bin/sh`. This runs as the `node-red` user and install is run in the `/data` directory which is owned by the `node-red` user.

**Comment by artforlife** [comment]
Seems to be identical to #3149. Also confirmed that the same exact thing happens on MacOS BigSur 11.6. Won't create a separate issue for it.

**Comment by lovell** [comment]
The salient part of the installation log is:

> sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.12.2/libvips-8.12.2-linuxmusl-armv7.tar.br
> sharp: Installation error: Prebuilt libvips 8.12.2 binaries are not yet available for linuxmusl-armv7
> sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies

https://sharp.pixelplumbing.com/install#prebuilt-binaries says

> The following platforms require compilation of both libvips and sharp from source:
> -    Linux ARMv7 (glibc <= 2.27, musl)

For musl-based Linux on ARMv7 devices, you'll need to follow the instructions at https://sharp.pixelplumbing.com/install#custom-libvips

**Comment by hardillb** [comment]
Just to be clear (so I can communicate this upstream) the only way to use sharp on a ARMv7 musl (Alpine) based container, is to manually build libvips and install it first?

Also has this changed (I have a user who suggests this used to work with just a npm install)?

**Comment by lovell** [comment]
Prebuilt libvips binaries for musl-based Linux on ARMv7 have never been provided by sharp, so you'll need to provide libvips globally somehow, which includes compilation from source or via OS package manager.

For Alpine, if you're using Edge, you should be able to take advantage of the latest `vips-dev` package.
https://pkgs.alpinelinux.org/package/edge/community/armv7/vips-dev

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
