### ISSUE TITLE
Is there a better or more efficient way I could be writing this Sharp code?

### ISSUE THREAD

**Issue by Br3ikros** [lovell/sharp#3151]
### What are you trying to achieve?

I'm sorry if this question looks dumb and silly... 

I have 2 images and for different reasons, I have to get the metadata of those images before doing anything else with them. I feel like there is a lot of repetition in my code and I wanted to understand what are the most CPU intensive tasks that I am doing and also if there is any way I could decrease the number of operations I'm doing. For example I do this:

`
const print_template = await sharp("./images/Sketch001.png")
const print_template_metadata = await print_template.metadata()
`

and then this later on:
`
    const print_file = await sharp("./images/Sketch001.png")
        .composite([{ input: final_nft }])
        .sharpen()
        .png()
        .toBuffer()
`

All I'd like to understand is, what is the most expending type of operation I'm doing with sharp in my program and is there any way I don't know of that I could do to do less operations and achieve the same result? For example when getting the metadata of an image, is there a way to get it from inside the .composite()?

I hope my question is not too messy and dumb. I put my code below to show what I mean. In the code below I get some images, apply some "filters" to extrapolate some new image etc. It's not important what I do I was just wondering if I was using sharp the wrong way basically.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

`
var result = await deepai.callStandardApi("torch-srgan", {
        image: "https://ratdao.mypinata.cloud/ipfs/QmVv7jcg4q1LdPgmM8pwQ3ia9VtYdzLexeCFujeakmF4md"
    });
    let url = await result.output_url

    const plain_nft_data = await axios.get("https://ratdao.mypinata.cloud/ipfs/QmVv7jcg4q1LdPgmM8pwQ3ia9VtYdzLexeCFujeakmF4md",  { responseType: 'arraybuffer' })
    const plain_nft_buffer = Buffer.from(plain_nft_data.data, "utf-8")

    const enhanced_nft_data = await axios.get(url,  { responseType: 'arraybuffer' })
    const enhanced_nft_buffer = Buffer.from(enhanced_nft_data.data, "utf-8")
    
    //
    const print_template = await sharp("./images/Sketch001.png")
    const print_template_metadata = await print_template.metadata()
    //

    const resized_nft_image = await sharp(plain_nft_buffer)
    .resize(Math.round(0.8 * print_template_metadata["width"]), Math.round(0.7 * print_template_metadata["height"]), {fit: "inside"})
    .png()
    .toBuffer()

    const nft = await sharp(resized_nft_image)
    const nft_image_metadata = await nft.metadata()

    const nft1 = await sharp(resized_nft_image)
        .sharpen()
        .png()
        .toBuffer()

    const enhanced_nft_image = await sharp(enhanced_nft_buffer)
    .resize(nft_image_metadata["width"], nft_image_metadata["height"])
    .png()
    .toBuffer()

    const map = await sharp(nft1)
        .composite([{ input: enhanced_nft_image, blend: "out" }])
        .sharpen()
        .png()
        .toBuffer()

    const final_nft = await sharp(map)
        .composite([{ input: enhanced_nft_image, blend: "out" }])
        .sharpen()
        .png()
        .toBuffer()`

**Comment by lovell** [comment]
PNG encoding will probably be the bottleneck here, so you might want to experiment with the `compressionLevel` option for intermediate images.

https://sharp.pixelplumbing.com/api-output#png

(The irony of worrying about a task being CPU intensive when this example appears to relate to an "NFT" is not lost on me.)

**Comment by Br3ikros** [comment]
ahahah nice, thank you for the help!! I'll look into that

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
