### ISSUE TITLE
Unable to convert SVG to image depending on dimensions, density or path fill: SVG rendering failed

### ISSUE THREAD

**Issue by adriaanmeuris** [lovell/sharp#3153]
### Is this a possible bug in a feature of sharp, unrelated to installation?
- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?
- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?
```
System:
    OS: macOS 12.3
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 111.55 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.3.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
npmPackages:
    sharp: 0.30.3 => 0.30.3 
```

### What are the steps to reproduce?
**index.js**
```js
const sharp = require('sharp');

const svgInput = `
  <svg version="1.1" id="Background" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0" y="0" viewBox="0 0 100 135" xml:space="preserve" width="100" height="135">
    <pattern x="-5385.06" y="-136.42" width="14.61" height="14.61" patternUnits="userSpaceOnUse" id="New_Pattern_Swatch_149" viewBox="0 -15.23 14.61 14.61" overflow="visible">
      <path fill="none" d="M0-15.23h14.61V-.62H0z"/>
      <path class="st1" d="M0-8.54h14.61v1.23H0zM0-15.84h14.61v1.23H0zM0-1.23h14.61V0H0z"/>
    </pattern>
    <pattern id="SVGID_1_" xlink:href="#New_Pattern_Swatch_149" patternTransform="translate(34.62 -1.059)"/>
    <path fill="url(#SVGID_1_)" d="M0 0h100v135H0z"/> <!-- Commenting out this line also resolves the error even with density set to 1 -->
  </svg>
`.trim();

(function runApp() {
  sharp(Buffer.from(svgInput), {
    density: 1,
    unlimited: true,
    limitInputPixels: false,
  })
    // .resize({ width: 883, height: 100 }) // Works
    .resize({ width: 884, height: 100 }) // Does not work with `density: 1`, but works with `density: 2` OR by commenting out the path in the input SVG
    // .resize({ width: 1600, height: 2160 }) // Does not work with a density outside the range of 2-9
  .toFile('OUT.png', (err) => {
    if (err) throw err;
    console.log('done');
  });
})();
```

**package.json**
```json
{
  "name": "sharp-svg",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {},
  "author": "",
  "license": "ISC",
  "dependencies": {
    "sharp": "0.30.3"
  }
}
```

**Dockerfile**
```
FROM node:16.14-bullseye-slim
WORKDIR /app
COPY package*.json ./
RUN npm ci --production --audit=false --fund=false
COPY index.js ./
CMD ["node", "index.js"]
```

**Script to run repro**
```sh
docker build . --tag 'sharp-svg-issue:latest' && docker run --memory 4g -it --rm -P -e NODE_ENV=production 'sharp-svg-issue'
```

### What is the expected behaviour?
The script should run successfully and should log `done` to the console, instead following error is thrown:
```
undefined:0


[Error: svgload: SVG rendering failed
glib: rendering error: NoMemory

vips2png: unable to write to target OUT.png
]
```

There are different changes that can be done to prevent the error:
- changing resize dimensions from `884x100` to `883x100`
- changing density from `1` to `2`
- commenting out following line in the input SVG: `<path fill="url(#SVGID_1_)" d="M0 0h100v135H0z"/>`

With bigger resize dimensions (`1600x2160`), I can only reproduce the error with the density set to `1` or greater than `9`. The other options `unlimited` and `limitInputPixels` do not seem to affect the behaviour in this case.

I've looked into https://github.com/lovell/sharp/issues/2276 and https://github.com/lovell/sharp/issues/1871. While the input svg does contain a path referencing a (local) pattern, it does not link to an external resource requiring network access (I can successfully resize with the density set to `2`). However it is strange that commenting out the path tag with the url fill also resolves the error, without changing the dimensions or density that otherwise raise an error.

Happy to update the repro with more scenarios if necessary. Any feedback would be very much appreciated.

**Comment by adriaanmeuris** [comment]
Thank you, I'll check and share my findings here.

**Comment by adriaanmeuris** [comment]
So I tried converting with: `rsvg-convert version 2.52.8`

I'm not entirely sure I'm mapping to the exact options as configured in Sharp (`d` and `p` voor dpi, `w` and `h` for dimensions). I get slightly different results running these commands:

`rsvg-convert -u -d 1 -p 1 -w 884 -h 100 -o output.png input.svg`
works without errors, did not work with sharp

`rsvg-convert -u -d 1 -p 1 -w 883 -h 100 -o output.png input.svg`
works without errors, did work with sharp

`rsvg-convert -u -d 1 -p 1 -w 1600 -h 2160 -o output.png input.svg`
results in error: `Error rendering SVG input.svg: rendering error: NoMemory`

`rsvg-convert -u -d 2 -p 2 -w 1600 -h 2160 -o output.png input.svg`
results in error: `Error rendering SVG input.svg: rendering error: NoMemory`, while this worked in Sharp

I'd be happy to add this as another example but first want to check if I'm mapping the instructions correctly from Sharp to `rsvg-convert` at the command line? Happy to run some other tests.

And, entirely unrelated: the upstream is what I understand is a dependency Sharp uses to process svg files, correct? Could you elaborate on what the downstream exactly is - would be much appreciated.

**Comment by lovell** [comment]
Thanks for testing this, as you've seen the parameter mapping won't be quite the same, but I'd say your third example looks approximately equivalent and fails equally so that's a good option to report to librsvg.

sharp relies on librsvg for rasterising SVG images. My comment about a downstream issue relates to Wikimedia being another consumer of librsvg (and not sharp), who have also run into the same problem.

**Comment by adriaanmeuris** [comment]
Thanks for your feedback. I reported my findings in the upstream issue.

Also thank you for explaining the downstream issue. I was about to ask if Sharp/Vips would ever support other libraries for rasterizing SVG images since I'm able to succesfully convert the example with `resvg`. Thanks for your links; it seems this is already part of a [discussion in vips](https://github.com/libvips/libvips/discussions/2048) and [wikimedia](https://phabricator.wikimedia.org/T40010).
