### ISSUE TITLE
Can't launch Electron app when sharp is packaged with asar

### ISSUE THREAD

**Issue by ZaValera** [lovell/sharp#3155]
If I run an unpackaged application, then everything works.
But if I pack the `/app` folder to `app.asar` then I get this error.
It is interesting that the file `C:\Users\zaval\AppData\Local\Temp\f8edd076-e814-4284-9114-8530aeb84b75.tmp.node` actually exists.
Application without `sharp` works both packaged and unpackaged

<img width="420" alt="image" src="https://user-images.githubusercontent.com/6653538/159480063-017d5ae0-764b-44ff-9f7e-5eaa4eb10ef4.png">

```text
A JavaScript error occurred in the main process
Uncaught Exception:
Error:
Something went wrong installing the "sharp" module
The specified module could not be found.
\\?\C:\Users\zaval\AppData\Local\Temp\f8edd076-e814-4284-9114-8530aeb84b75.tmp.node
Possible solutions:
- Install with the --verbose flag and look for errors: "npm install  --ignore-scripts=false --verbose sharp"
- Install for the current win32-x64 runtime: "npm install --platform=win32 --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
at Object.<anonymous>
(D:\tmp\changesize\resources\app.asar\node_modules\sharp\lib\sharp.js:31:9) 
  at Module._compile (node:internal/modules/cjs/loader:1116:14)
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10) 
  at Module.load (node:internal/modules/cjs/loader:988:32)
  at ModuleJoad (node:internal/modules/cjs/loader:829:12)
  at Functions Joad (node:electron/js2c/asar_bundle:5:13331)
  at Module.require (node:internal/modules/cjs/loader:1012:19) at require (node:internal/modules/cjs/helpers:102:18) 
  at Object.<anonymous>
(D:\tmp\changesize\resources\app.asar\node_modules\sharp\lib\constructor.js:8:1)
  at Module._compile (node:internal/modules/cjs/loader:1116:14)
```

**Comment by lovell** [comment]
Did you see https://github.com/lovell/sharp/issues/678#issuecomment-275956028 , specifically the use of `asarUnpack`?

**Comment by ZaValera** [comment]
Thanks a lot!
This is a working solution but it still looks like a dirty hack. But I suspect that this is an "electron" problem but not a "sharp".
Is it possible to do something? Can you explain the nature of the problem?

**Comment by lovell** [comment]
Glad to hear the use of `asarUnpack` works. I believe the problem is that by default Electron only unpacks files that appear in `require` statements, but sharp, like many native dependencies, has shared libraries that will be `dlopen`ed.

If you're using Electron Forge see https://www.electronforge.io/config/plugins/auto-unpack-natives

**Comment by ZaValera** [comment]
Thanks for your help and comprehensive answer!
