### ISSUE TITLE
Error: linear: vector must have 1 or 4 elements, srgb, 5 channel image, using .flatten

### ISSUE THREAD

**Issue by JamieVangeysel** [lovell/sharp#3156]
```javascript
const filename = './1221021360.tiff'
const background = '#FFFFFF'

await sharp(filename)
.resize({
  height: 120,
  width: 120,
  fit: 'contain',
  background
})
.flatten({ background })
.webp({ quality: 80 })
.toFile(filename + '.webp')
```
Throws error: [Error: linear: vector must have 1 or 4 elements]

metadata of the image:
```javascript
{
  format: 'tiff',
  width: 4400,
  height: 4400,
  space: 'srgb',
  channels: 5,
  depth: 'uchar',
  density: 300,
  isProgressive: false,
  pages: 1,
  resolutionUnit: 'inch',
  hasProfile: true,
  hasAlpha: true,
  orientation: 1,
  icc: ...
}
```

when leaving out .flatten() the code runs but the image comes out transparent obviously and we dont want that.

[Link to zip containing 2 .tiff files that will error.](https://pcm.groupclaes.be/v3/content/file/a2f16f21-bfe3-4ee9-92c1-daa47cea5c8e)

**Comment by lovell** [comment]
Hi, did you see #2266?

What would be your expectation of the output of the `flatten` operation when there are two alpha channels?

**Comment by JamieVangeysel** [comment]
Hi, no I missed it 😅.
I will move to the open issue, thanks.
