### ISSUE TITLE
Transforming File object (Blob) to use in constructor

### ISSUE THREAD

**Issue by DePasqualeOrg** [lovell/sharp#3168]
I'm trying to use Sharp to process uploaded images from a webpage. The images are provided with the web [File](https://developer.mozilla.org/en-US/docs/Web/API/File) API. I can't figure out how to transform the File object into something that Sharp will accept in its constructor. How can I get this to work?

**Comment by lovell** [comment]
Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question.

(You ignored/deleted the issue template that requested this.)

**Comment by DePasqualeOrg** [comment]
Sorry, it's hard for me to extract this code from my project into a standalone example. But I was finally able to get this to work as follows. I had to convert the File object to an ArrayBuffer, and then to a Buffer, which Sharp will accept as input:

```javascript
const arrayBuffer = await file.arrayBuffer();
const buffer = Buffer.from(arrayBuffer, 'binary');
const image = sharp(buffer);
```
