### ISSUE TITLE
electron-builder ignores npm_config_arch=ia32 when running yarn add sharp

### ISSUE THREAD

**Issue by huangruiqi** [lovell/sharp#3169]
## Possible install-time or require-time problem

- [ yes ] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [ yes ] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

- [ yes] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

running 'npm i sharp --arch=ia32' is working.

**Comment by lovell** [comment]
What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

What's the output of running `npm_config_arch=ia32 yarn add sharp --verbose`?

**Comment by huangruiqi** [comment]
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
    Memory: 12.29 GB / 31.78 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Enviroment\node_global\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: ^0.30.3 => 0.30.3

**Comment by huangruiqi** [comment]
running  npm_config_arch=ia32 yarn add sharp

![image](https://user-images.githubusercontent.com/23137020/160971099-eb890357-0a99-446f-ba5f-08c540901437.png)

**Comment by lovell** [comment]
This screenshot shows `electron-builder` is using `arch=x64`, so perhaps that package is where the problem lies.

If you need further help, please provide the complete output, as text (not an image), of running `npm_config_arch=ia32 yarn add sharp --verbose` in an empty directory.

**Comment by huangruiqi** [comment]
Running `npm_config_arch=ia32 yarn add sharp --verbose`

[test.txt](https://github.com/lovell/sharp/files/8387064/test.txt)

**Comment by lovell** [comment]
Thank you, here's the salient part:
```
verbose 9.1119807 sharp: Using cached C:\Enviroment\node_cache\_libvips\libvips-8.12.2-win32-ia32.tar.br
sharp: Integrity check passed for win32-ia32
sharp: Creating D:\QQWork\qq-web\pcqq-web\node_modules\sharp\build\Release
sharp: Copying DLLs from D:\QQWork\qq-web\pcqq-web\node_modules\sharp\vendor\8.12.2\win32-ia32\lib to D:\QQWork\qq-web\pcqq-web\node_modules\sharp\build\Release
success Saved 1 new dependency.
info Direct dependencies
└─ sharp@0.30.3
info All dependencies
└─ sharp@0.30.3
$ electron-builder install-app-deps
  • electron-builder  version=22.14.13
  • rebuilding native dependencies  dependencies=sharp@0.30.3 platform=win32 arch=x64
  • install prebuilt binary  name=sharp version=0.30.3 platform=win32 arch=x64 napi= 
```
This suggests sharp respected `npm_config_arch=ia32` as it installed binaries for the `win32-ia32` platform, however `electron-builder` is using `platform=win32 arch=x64` so I think the problem lies there, not with sharp.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
