### ISSUE TITLE
libvips is not installed on a windows machine

### ISSUE THREAD

**Issue by jtobinisaniceguy** [lovell/sharp#317]
Using VS 2015 with node.js tools installed, running npm install sharp get the following errors:
...
> sharp@0.11.4 install C:\Users\User Name\Documents\limelightserver-v2\node_modules\sharp
> node-gyp rebuild

C:\Users\User Name\Documents\limelightserver-v2\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program
Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebu
ild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  common.cc
  metadata.cc
  operations.cc
  pipeline.cc
  sharp.cc
  utilities.cc
..\src\operations.cc(1): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [C:\User
s\User Name\Documents\limelightserver-v2\node_modules\sharp\build\sharp.vcxproj]
..\src\utilities.cc(2): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [C:\Users
\User Name\Documents\limelightserver-v2\node_modules\sharp\build\sharp.vcxproj]
..\src\metadata.cc(2): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [C:\Users\
User Name\Documents\limelightserver-v2\node_modules\sharp\build\sharp.vcxproj]
..\src\sharp.cc(2): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [C:\Users\Use
r Name\Documents\limelightserver-v2\node_modules\sharp\build\sharp.vcxproj]
..\src\pipeline.cc(6): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [C:\Users\
User Name\Documents\limelightserver-v2\node_modules\sharp\build\sharp.vcxproj]
..\src\common.cc(4): fatal error C1083: Cannot open include file: 'vips/vips.h': No such file or directory [C:\Users\Us
er Name\Documents\limelightserver-v2\node_modules\sharp\build\sharp.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
70:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\User Name\Documents\limelightserver-v2\node_modules\sharp
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "sharp"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.11.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.11.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\User Name\Documents\limelightserver-v2\npm-debug.log

Log file is not created, which I think is a bug of npm, probably no one has decided to fix
libvips according to documentation should be installed by npm, however this is not the case

**Comment by lovell** [comment]
For 64-bit node.exe on Windows you'll need sharp v0.12.0+, which should "just work" - see http://sharp.readthedocs.org/en/stable/install/#windows

For 32-bit node.exe on Windows, which is no longer supported, you'll need to use v0.11.4 and manually install libvips - see http://sharp.readthedocs.org/en/v0.11.4/install/#windows

Hope this helps!

**Comment by jtobinisaniceguy** [comment]
Confirmed.
Using v0.12.0 works.
Thanks!
