### ISSUE TITLE
Building sharp for multiple platforms with electron-builder

### ISSUE THREAD

**Issue by Tenpi** [lovell/sharp#3170]
### What are you trying to achieve?

I am using macOS. I would like to build my app for multiple platforms with `electron-builder -mwl` but it appears that sharp is always downloading the macOS version for all platforms. To build my app for Windows I need to move to a Windows machine and compile manually. Obviously, this is very tedious to do.

### When you searched for similar issues, what did you find that might be related?

I have looked for similar issues but I haven't found anything to help. They mentioned setting this postinstall script but it did not work for me:
`"postinstall": "electron-builder install-app-deps"`

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question
This is my full package.json:
```
{
  "name": "photo-viewer",
  "version": "0.1.7",
  "description": "An image/GIF viewer that can apply various resizing and color effects.",
  "main": "dist/main.js",
  "scripts": {
    "start": "npm run clean && webpack && cross-env DEVELOPMENT=true electron dist/main.js",
    "clean": "del-cli ./dist",
    "build": "npm run clean ./build && webpack && electron-builder -p never",
    "release": "npm run clean ./build && webpack && electron-builder -mwl -p always",
    "rebuild": "npm rebuild --runtime=electron --target=14.0.0 --disturl=https://atom.io/download/atom-shell --abi=89",
    "postinstall": "electron-builder install-app-deps"
  },
  "keywords": [
    "photo",
    "viewer",
    "image",
    "photoshop",
    "anime",
    "cute"
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/Tenpi/Photo-Viewer"
  },
  "build": {
    "appId": "com.tenpi.photo-viewer",
    "productName": "Photo Viewer",
    "icon": "./assets/icon.png",
    "directories": {
      "buildResources": "assets",
      "output": "build"
    },
    "buildDependenciesFromSource": true,
    "mac": {
      "target": {
        "target": "dmg",
        "arch": "x64"
      },
      "category": "public.app-category.graphics-design"
    },
    "dmg": {
      "title": "${productName}",
      "background": "./assets/background.png",
      "window": {
        "width": 540,
        "height": 380
      }
    },
    "win": {
      "target": {
        "target": "nsis",
        "arch": "x64"
      }
    },
    "nsis": {
      "oneClick": false,
      "perMachine": true,
      "allowToChangeInstallationDirectory": true,
      "uninstallDisplayName": "Photo Viewer",
      "createDesktopShortcut": "always",
      "installerSidebar": "./assets/installer.bmp",
      "uninstallerSidebar": "./assets/installer.bmp"
    },
    "linux": {
      "target": {
        "target": "appImage",
        "arch": "x64"
      },
      "category": "Graphics"
    },
    "files": [
      "dist/**/*",
      "package.json"
    ],
    "publish": {
      "provider": "github",
      "repo": "Photo-Viewer",
      "owner": "Tenpi",
      "releaseType": "draft"
    },
    "fileAssociations": [
      {
        "ext": "jpg",
        "description": "JPG File"
      },
      {
        "ext": "jpeg",
        "description": "JPEG File"
      },
      {
        "ext": "png",
        "description": "PNG File"
      },
      {
        "ext": "webp",
        "description": "WEBP File"
      },
      {
        "ext": "tiff",
        "description": "TIFF File"
      },
      {
        "ext": "gif",
        "description": "GIF Filenp"
      }
    ]
  },
  "author": "Tenpi",
  "license": "MIT",
  "devDependencies": {
    "@tenpi/tslint": "^1.1.0",
    "@types/fluent-ffmpeg": "^2.1.18",
    "@types/get-pixels": "^3.3.1",
    "@types/gif-encoder": "^0.7.1",
    "@types/jquery": "^3.5.13",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/request": "^2.48.7",
    "@types/sharp": "^0.29.1",
    "@types/unzipper": "^0.10.5",
    "cross-env": "^7.0.3",
    "css-loader": "^5.0.1",
    "del-cli": "^3.0.1",
    "electron": "^14.0.0",
    "electron-builder": "^23.0.2",
    "file-loader": "^6.2.0",
    "fork-ts-checker-webpack-plugin": "^6.4.0",
    "html-loader": "^1.3.2",
    "html-webpack-plugin": "^5.5.0",
    "less": "^4.1.0",
    "less-loader": "^7.3.0",
    "mini-css-extract-plugin": "^1.3.5",
    "node-loader": "^1.0.2",
    "terser-webpack-plugin": "^5.1.1",
    "ts-loader": "^8.0.14",
    "typescript": "^4.1.3",
    "webpack": "^5.69.1",
    "webpack-cli": "^4.4.0"
  },
  "dependencies": {
    "@electron/remote": "^2.0.1",
    "axios": "^0.19.2",
    "bootstrap": "^4.6.0",
    "electron-shortcuts": "^0.4.0",
    "electron-store": "^8.0.0",
    "electron-updater": "^4.3.5",
    "gif-encoder": "^0.7.2",
    "gif-frames": "github:tenpi/gif-frames#no-cumulative",
    "image-pixels": "^2.2.2",
    "jquery": "^3.6.0",
    "pixiv.ts": "^0.4.2",
    "rc-slider": "^9.7.1",
    "react": "^17.0.1",
    "react-bootstrap": "^1.4.3",
    "react-dom": "^17.0.1",
    "react-draggable": "^4.4.3",
    "react-dropzone": "^11.3.4",
    "react-image-crop": "^9.0.4",
    "react-zoom-pan-pinch": "^2.1.3",
    "sharp": "^0.30.3",
    "unzipper": "^0.10.11"
  }
}

```

### Please provide sample image(s) that help explain this question

After building from my Mac, the Windows version generated does not work. The following appears after installation: 

![154205509-90f58e42-f68f-4358-a3b8-4357a168b8c6](https://user-images.githubusercontent.com/37512637/160958118-c8db6279-4046-43cc-a76b-d05ad78bd38c.png)

**Comment by lovell** [comment]
Did you see https://sharp.pixelplumbing.com/install#cross-platform ? This is probably a question for `electron-builder`. You may need to use one of the tools provided by Electron such as `electron-forge`.

**Comment by Tenpi** [comment]
OK, that has just given me the idea to split up the builds as follows:
```
"release": "npm run release:mac && npm run release:win && npm run release:linux",
"release:mac": "npm run clean ./build && webpack && npm run sharp:mac && electron-builder -m -p always",
"release:win": "npm run clean ./build && webpack && npm run sharp:win && electron-builder -w -p always",
"release:linux": "npm run clean ./build && webpack && npm run sharp:linux && electron-builder -l -p always",
"sharp:mac": "del-cli ./node_modules/sharp && npm install --platform=darwin --arch=arm64 sharp",
"sharp:win": "del-cli ./node_modules/sharp && npm install --platform=win32 --arch=x64 sharp",
"sharp:linux": "del-cli ./node_modules/sharp && npm install --platform=linux --arch=x64 sharp"
```
It's not as elegant as building all three at once, but at least this works now. The problem seems to be that `electron-builder` is not rebuilding any of the native dependencies. I notice that `node_modules/sharp` needs to be deleted to install it for a different OS, so that could also be the issue here. Since this workaround works fine for me, I'll close this, thanks.

**Comment by FileManagerKim** [comment]
> Did you see https://sharp.pixelplumbing.com/install#cross-platform ? This is probably a question for `electron-builder`. You may need to use one of the tools provided by Electron such as `electron-forge`.

Hello, I know this ticket is closed, however I ran into this error while using electron-forge. I've specified the platform and architecture when installing, however the error seems to persist. Is it okay to continue this thread, or should I open another ticket?

**Comment by dj-nuo** [comment]
Also fixed automatically with [this](https://sharp.pixelplumbing.com/install#cross-platform):

> Multiple platforms and architectures can be supported within the same installation tree. The following example for macOS installs x64 binaries then adds (via a rebuild) arm64 binaries:

```
npm install --platform=darwin --arch=x64 sharp
npm rebuild --platform=darwin --arch=arm64 sharp
```

### Solution for Mac OS (Apple Silicon / M1)
As a universal solution, include this in your `"scripts"` within `package.json`:
`"install": "npm uninstall sharp && npm install --platform=darwin --arch=x64 sharp && npm rebuild --platform=darwin --arch=arm64 sharp"`

n.b. uninstall step is needed in order to remove default `'sharp'` installation (which was installed for arm64 by default)
