### ISSUE TITLE
node-loader: Library not loaded: @rpath/libvips-cpp.42.dylib 

### ISSUE THREAD

**Issue by huangruiqi** [lovell/sharp#3171]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?
  System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 177.38 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.1 - /usr/local/bin/npm
  npmPackages:
    sharp: ^0.30.3 => 0.30.3 

### What are the steps to reproduce?

yarn dev

### Please provide sample image(s) that help explain this problem

![image](https://user-images.githubusercontent.com/23137020/161240309-5d03e1d3-6f35-4c51-ba0c-19f604693fd6.png)

**Comment by huangruiqi** [comment]
I didn't install vips.

**Comment by lovell** [comment]
Please don't use `node-loader`. There's information about use with webpack at https://sharp.pixelplumbing.com/install#bundlers

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
