### ISSUE TITLE
Error: Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by mluce194** [lovell/sharp#3173]
## I cannot run npm run dev or gatsby develop
I get this error: `Error: Something went wrong installing the "sharp" module
  dlopen(/Users/marie-luce/Documents/projets/gatsby contentful/node_modules/sharp/build/Release/sharp-darwin-x64.node, 1): Library not loa
  ded: @rpath/libvips-cpp.42.dylib
    Referenced from: /Users/marie-luce/Documents/projets/gatsby contentful/node_modules/sharp/build/Release/sharp-darwin-x64.node
    Reason: Incompatible library version: sharp-darwin-x64.node requires version 57.0.0 or later, but libvips-cpp.42.dylib provides version 55.0.0
  Possible solutions:
  - Update Homebrew: "brew update && brew upgrade vips"
  - Consult the installation documentation: https://sharp.pixelplumbing.com/install`

### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x ] Running `npm install sharp` completes without error.
- [x ] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [ x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
    Memory: 31.99 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 17.4.0 - ~/.nvm/versions/node/v17.4.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 2.15.12 - ~/Documents/projets/gatsby contentful/node_modules/.bin/npm
  npmPackages:
    sharp: ^0.30.3 => 0.30.3 

### What are the steps to reproduce?

Npm run dev

### What is the expected behaviour?

The development server should start.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

This is the link to my repo: https://github.com/mluce194/contentful-lawyer

**Comment by lovell** [comment]
Please ensure you're using the latest version of any Gatsby plugins, e.g. I note [`gatsby-plugin-sharp`](https://github.com/mluce194/contentful-lawyer/blob/master/package.json#L22) is well out of date and is mismatched against the major version of Gatsby.

Perhaps look back at the previous issue https://github.com/lovell/sharp/issues/3065 you opened, which also related to mismatched Gatsby plugins.

If you still require help, please open [a new installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) and answer all of the questions.
