### ISSUE TITLE
Very slow when processing animated gif images

### ISSUE THREAD

**Issue by heowc** [lovell/sharp#3176]
### What are you trying to achieve?

It's very slow to process animated gif images. The image I used as an example is 515kb. Just buffering that image without adding any options takes over 20 seconds. It takes 9 seconds to convert this to webp format.

I tried running this in docker environment. The image is `amazon/aws-lambda-nodejs:14.2022.03.23.16`

Is there any way I can do this quickly? Or is this the best?

### When you searched for similar issues, what did you find that might be related?

https://github.com/lovell/sharp/issues/2972

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```javascript
const sharp = require('sharp');

let image = sharp(`${process.cwd()}/app/astronaut-animation.gif`, { animated: true })
let buffer = image.toBuffer();
buffer.then(value => {
    console.log(`length: ${value.toString('base64').length}`);
    console.log(`total: ${new Date().getTime() - startTime.getTime()}`)
});
```

### Please provide sample image(s) that help explain this question

https://gifcop.com/best-tools-compress-gif-images/

**Comment by lovell** [comment]
Did you see the `effort` parameter of `gif`? https://sharp.pixelplumbing.com/api-output#gif

There's some discussion upstream about future possible improvements to GIF encoding performance at https://github.com/libvips/libvips/issues/2531 (and the somewhat related https://github.com/libvips/libvips/issues/2576).

**Comment by heowc** [comment]
Thank you for quick response. Thanks to the `effort` option you mentioned, it's about 2x faster. thank you. 

However, this cannot be said to be fast. 🤣  Let's look at the other issues you mentioned.

**Comment by heowc** [comment]
I have another question. What factors greatly affect performance? I was pretty fast on my personal laptop. I tried adding node options (`--max-old-space-size` etc) or changing `sharp.concurrency(num)` to no avail.

**Comment by heowc** [comment]
I eventually realized that this wasn't just an issue with animated gif images.

jpg file(5.2MB)
- `amazon/aws-lambda-nodejs:14.2022.03.23.16`
    - original: 4.2s
    - convert webp: 29s
    - convert webp(effort:1): 9.2s
- `node:14-buster-slim`
    - original: 0.7s
    - convert webp: 0.7s
    - convert webp(effort:1): 0.7s

**Comment by lovell** [comment]
Please subscribe to the upstream libvips issues for further updates.

**Comment by ffxsam** [comment]
@lovell Could you explain what impact `effort` has on the output? I tried effort of 1, and the GIFs look just fine to me quality-wise, and maybe just a tiny bit larger than the ones at effort 7, but it's negligible.

**Comment by lovell** [comment]
The GIF `effort` property controls how much CPU time to devote to generating the palette. More time should result in higher accuracy, especially when also using dithering (the default behaviour). It's the same as the `effort` property when generating palette-based PNG output.

**Comment by ffxsam** [comment]
Oof, I take back what I said about not a large increase in file size. Oddly enough, it seems like `effort` takes into consideration the power of your processor. At `effort: 1` on my Mac M1, there was hardly a file size difference from the default effort level of 7. But on AWS Lambda, `effort: 1` resulted in a 35MB GIF created from a 1.5MB file!
