### ISSUE TITLE
custom libvips for Windows

### ISSUE THREAD

**Issue by ptraversy** [lovell/sharp#3177]
I would like to add heif support to Sharp for a node application running on windows.  I understand that I need to create a custom build of libvips that I (assume) that I install globally.  However,  the notes on the sharp webpage say "The use of a globally-installed libvips is unsupported on Windows."  

Do I build libvips DLLs that I copy over the existing libvips DLLs in the node_modules folder of Sharp ?  

I am happy to pay anyone who might be able to give me advice on this.  Thanks!

**Comment by lovell** [comment]
There was some previous discussion about this at #2377

If this is to enable HEIC en/decoding, you might be able to use custom DLLs built from source via https://github.com/libvips/build-win64-mxe/#hevc-related-dependencies but please ensure you understand the various patent and licensing implications of doing so.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
