### ISSUE TITLE
Can be compiled with GCC4.4.7 with a few changes

### ISSUE THREAD

**Issue by debuggings** [lovell/sharp#318]
My server runs centos 6.5, and it's gcc version is 4.4.7.
It cannot be compiled of course. But after I edited a few lines of code, the code can be used on my server.
So I think there is no need to use those c++11 grammar.

**Comment by debuggings** [comment]
src/common.cc
```c
-#if ((!defined(__clang__)) && defined(__GNUC__) && (__GNUC__ < 4 || (__GNUC__ == 4 && __GNUC_MINOR__ < 6)))
-#error GCC version 4.6+ is required for C++11 features - see http://sharp.dimens.io/page/install#prerequisites
+#if ((!defined(__clang__)) && defined(__GNUC__) && (__GNUC__ < 4 || (__GNUC__ == 4 && __GNUC_MINOR__ < 4)))
+#error GCC version 4.4+ is required for C++11 features - see http://sharp.dimens.io/page/install#prerequisites
 #endif
```
 src/common.h
```c
 #ifndef SRC_COMMON_H_
 #define SRC_COMMON_H_
 
+#if ((!defined(__clang__)) && defined(__GNUC__) && (__GNUC__ < 4 || (__GNUC__ == 4 && __GNUC_MINOR__ < 6)))
+#define nullptr NULL
+#endif
```
 src/utilities.cc
```c
Local<Object> format = New<Object>();
-  for (std::string f : {"jpeg", "png", "webp", "tiff", "magick", "openslide", "dz"}) {
+  std::string format_array[7] = {"jpeg", "png", "webp", "tiff", "magick", "openslide", "dz"};
+  for (int i = 0; i<7;i++) {
+    std::string f = format_array[i];
 #endif
```

**Comment by lovell** [comment]
Hello, sharp is currently [tested on Centos 6](https://github.com/lovell/sharp/blob/master/packaging/test.sh#L21-L26) but as you point out, we have to [upgrade the version of gcc](https://github.com/lovell/sharp/blob/master/packaging/test/centos6.sh) to do so.

I'd be happy to accept a PR with this change for now, but please be aware that we'll probably stop testing against Centos 6 around June 2016 to coincide with RHEL6's "End of Production 1 phase".

(It's also slightly possible that during #299 to switch to libvips' C++ bindings, use of a newer feature of C++11 may become necessary.)

**Comment by debuggings** [comment]
I generally do not write C\C++ code, and those changes are not fully tested.
As you will switch to libvips' C++ bindings, I think it's not necessary to change the code for now.

**Comment by lovell** [comment]
> "I think it's not necessary to change the code for now"

Thanks for the update, I'll close this question.
