### ISSUE TITLE
Recoloring icon image

### ISSUE THREAD

**Issue by richardgirges** [lovell/sharp#3180]
## Question about an existing feature
Hello, I'm trying to understand how to recolor an icon image with a transparent background. Our icons are simple:
* We only need to change the foreground color
* We can assume the input foreground color of all of our icons is black
* We can make all of our input icons PNG or SVG, no preference

### What are you trying to achieve?
Change this:
![arrow-down](https://user-images.githubusercontent.com/1226126/162054542-d389187e-28fd-4cdd-baeb-d70aa0b14418.png)

To this (or any other hex/rgba color we want to use):
![arrow-down](https://user-images.githubusercontent.com/1226126/162054606-5fe643da-ee6d-43c3-9fc0-8bd83c135ce2.png)

### When you searched for similar issues, what did you find that might be related?
I couldn't find an issue that was as specific as mine. I did find the following potentially-related topics but the solutions proposed didn't work:

https://github.com/lovell/sharp/issues/2576
https://github.com/lovell/sharp/issues/1798

**Comment by lovell** [comment]
Are you able to provide an example of the input as an SVG? If you control this then it might be possible to set the path colour.

**Comment by richardgirges** [comment]
@lovell yep here's the SVG:
```svg
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M19 9L12 16L5 9" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
```

**Comment by lovell** [comment]
Thanks, have you tried changing the value of `stroke="black"` to the colour you need?
```diff
 <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
-<path d="M19 9L12 16L5 9" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
+<path d="M19 9L12 16L5 9" stroke="#f00" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
 </svg>
```

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
