### ISSUE TITLE
Dilate & Erode morphology

### ISSUE THREAD

**Issue by masotrix** [lovell/sharp#3183]
### What are you trying to achieve?

I am trying to dilate a black signature in a white transparent image after resizing it because it seems much thinner after the transformation

### When you searched for similar issues, what did you find that might be related?

I found an old issue #1719 that seems to be not resolved, but would like to know if there is a workaround

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question
```
// current
const scaledImg = await sharp(imBuffer).resize(130, 90);

// desired
const scaledImg = await sharp(imBuffer).resize(130, 90).dilate(1);
```

### Please provide sample image(s) that help explain this question

Here is the original version of the signature

![SIGNATURE](https://user-images.githubusercontent.com/12578105/162544654-ef1d4941-1a31-498a-9e42-b88712f92be3.PNG)

And here is the scaled version, which we would like to dilate to make it thicker

![smaillSignature](https://user-images.githubusercontent.com/12578105/162544682-5b221fd8-d05e-46cd-b024-db5b78583246.PNG)

**Comment by lovell** [comment]
Let's continue to track this at the existing, future possible enhancement at #1719
