### ISSUE TITLE
How to rotate image around the specified origin?

### ISSUE THREAD

**Issue by zeeker999** [lovell/sharp#3184]
### What are you trying to achieve?

rotate an image around the specified origin instead of the center of the image.

### When you searched for similar issues, what did you find that might be related?
the sharp.rotate() doesn't support this feature.

**Comment by lovell** [comment]
Hi, did you see the `affine` operation?

https://sharp.pixelplumbing.com/api-operation#affine

https://en.wikipedia.org/wiki/Affine_transformation

**Comment by zeeker999** [comment]
oh, I missed that. Thanks for pointing it out.
