### ISSUE TITLE
image-thumbnail package has outdated dependencies

### ISSUE THREAD

**Issue by JokerMartini** [lovell/sharp#3185]
Something went wrong installing the "sharp" module

I have a simple public repo which keeps giving me the following errors..

### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.
0.30.3

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    Memory: 1.32 GB / 7.87 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: ^0.30.3 => 0.30.3

### What are the steps to reproduce?

download simple repo --> https://github.com/JokerMartini/quasar-gallery
cd into the 'server' folder and run 'npm install' then 'npm start' 
it fails when running 'npm start'

### What is the expected behaviour?

Expect it to build successfully

Error message 
```
PS C:\Users\JokerMartini-Asus\Desktop\Trash\quasar-gallery\server> npm start

> server@1.0.0 start
> node index.js

C:\Users\JokerMartini-Asus\Desktop\Trash\quasar-gallery\server\node_modules\image-thumbnail\node_modules\sharp\lib\constructor.js:32
  throw new Error(error);
  ^

Error:
Something went wrong installing the "sharp" module

The specified procedure could not be found.
\\?\C:\Users\JokerMartini-Asus\Desktop\Trash\quasar-gallery\server\node_modules\image-thumbnail\node_modules\sharp\build\Release\sharp.node

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (C:\Users\JokerMartini-Asus\Desktop\Trash\quasar-gallery\server\node_modules\image-thumbnail\node_modules\sharp\lib\constructor.js:32:9)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\JokerMartini-Asus\Desktop\Trash\quasar-gallery\server\node_modules\image-thumbnail\node_modules\sharp\lib\index.js:3:15)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
```

**Comment by lovell** [comment]
Hi, it looks like you're using sharp via a dependency on the `image-thumbnail` package.

> If you are using another package which depends on a version of sharp that is not the latest, please open an issue against that package instead.

It looks like the `image-thumbnail` package needs to update its version of sharp, and others have already reported this e.g. https://github.com/onildoaguiar/image-thumbnail/issues/76

Perhaps you could open a pull request against that repo to update its dependencies.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
