### ISSUE TITLE
HOWTO set Photometric Interpretation to  min-is-white

### ISSUE THREAD

**Issue by geabenitez** [lovell/sharp#3186]
I am using this piece of code 
await sharp(`./${file}.tif`)
    .toColourspace('b-w')
    .tiff({ compression: 'ccittfax4', xres: size, yres: size, bitdepth: 1 })
    .toFile(`output_${dpi}.tif`)

but I am getting Photometric Interpretation: min-is-black and I need it to be min-is-white

Any suggestion on how I can achieve the min-is-white?

**Comment by dcbartlett** [comment]
Another term for this is Quantum Polarity.  I too am interested in figuring out how to set this using this library.

**Comment by lovell** [comment]
To support this we'll need to expose libvips' `miniswhite` setting as a property on `tiff()`

https://sharp.pixelplumbing.com/api-output#tiff

https://www.libvips.org/API/current/VipsForeignSave.html#vips-tiffsave

Happy to accept a PR, if you're able.

**Comment by geabenitez** [comment]
> To support this we'll need to expose libvips' `miniswhite` setting as a property on `tiff()`
> 
> https://sharp.pixelplumbing.com/api-output#tiff
> 
> https://www.libvips.org/API/current/VipsForeignSave.html#vips-tiffsave
> 
> Happy to accept a PR, if you're able.

Hey @lovell, I haven't worked on a project like this before, where should I be able find guidance so I can work on the PR? Tx.

**Comment by lovell** [comment]
@geabenitez Thank you for offering to take a look. Perhaps you could adopt a code path like that used with the existing `pyramid` boolean option of `tiff()`, as I would imagine adding `miniswhite` will be very similar.

https://github.com/lovell/sharp/blob/5b03579e5c29dc38e90b0c2bb685411ff89b570e/lib/output.js#L753-L755

https://github.com/lovell/sharp/search?q=tiffPyramid
