### ISSUE TITLE
Installation error on windows machine behind corporate proxy

### ISSUE THREAD

**Issue by Redarcher9** [lovell/sharp#3187]
## Possible install-time or require-time problem

- [x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Is this a problem with filesystem permissions?

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7 or later, does the user running `npm install` own the directory it is run in?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

### What is the complete output of running `npm install --verbose sharp`?

<details>

 3646 info run sharp@0.30.3 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
3647 info run sharp@0.27.2 install node_modules/gatsby-plugin-manifest/node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
3648 info run sharp@0.27.2 install node_modules/gatsby-plugin-sharp/node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
3649 info run sharp@0.27.2 install node_modules/gatsby-transformer-sharp/node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
3650 info run sharp@0.30.3 install { code: 1, signal: null }
3651 info run sharp@0.27.2 install { code: 1, signal: null }
3652 info run sharp@0.27.2 install { code: 1, signal: null }
3653 info run sharp@0.27.2 install { code: 1, signal: null }
3654 timing reify:rollback:createSparse Completed in 56932ms
3655 timing reify:rollback:retireShallow Completed in 0ms
3656 timing command:install Completed in 251226ms
3657 verbose stack Error: command failed
3657 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
3657 verbose stack     at ChildProcess.emit (node:events:520:28)
3657 verbose stack     at maybeClose (node:internal/child_process:1092:16)
3657 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
3658 verbose pkgid sharp@0.30.3
3659 verbose cwd C:\Innersource\devkit-frontend\devkit-frontend
3660 verbose Windows_NT 10.0.19042
3661 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose" "sharp"
3662 verbose node v16.14.0
3663 verbose npm  v8.3.1
3664 error code 1
3665 error path C:\Innersource\devkit-frontend\devkit-frontend\node_modules\sharp
3666 error command failed
3667 error command C:\WINDOWS\system32\cmd.exe /d /s /c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
3668 error sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.12.2/libvips-8.12.2-win32-x64.tar.br
3668 error sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
3669 error sharp: Installation error: unable to get local issuer certificate
3670 verbose exit 1
3671 timing npm Completed in 252667ms
3672 verbose unfinished npm timer reify 1649741506088
3673 verbose unfinished npm timer reify:build 1649741697413
3674 verbose unfinished npm timer build 1649741697444
3675 verbose unfinished npm timer build:deps 1649741697447
3676 verbose unfinished npm timer build:run:install 1649741698547
3677 verbose unfinished npm timer build:run:install:node_modules/sharp 1649741698547
3678 verbose unfinished npm timer build:run:install:node_modules/gatsby-plugin-manifest/node_modules/sharp 1649741698588
3679 verbose unfinished npm timer build:run:install:node_modules/gatsby-plugin-sharp/node_modules/sharp 1649741698616
3680 verbose unfinished npm timer build:run:install:node_modules/gatsby-transformer-sharp/node_modules/sharp 1649741698653
3681 verbose code 1
3682 error A complete log of this run can be found in:
3682 error     C:\Users\Snehit.Paunikar\AppData\Local\npm-cache\_logs\2022-04-12T05_31_44_688Z-debug-0.log

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

 System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 6.57 GB / 15.85 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/1618
