### ISSUE TITLE
Feature request: Add support for special regional characters

### ISSUE THREAD

**Issue by blowsie** [lovell/sharp#319]
Sharp fails which trying to process the following files, due to the file name.

```
ricarica_più.jpg
starcasinò.jpg
```

```
Running "sharp:build" (sharp) task
Warning: Error: Error: Input file is of an unsupported image formatVipsForeignLoad: file "src/assets/images/logos/ricarica_più.jpg" not found
 Use --force to continue.
```

Would it be possible to support such file names?

**Comment by lovell** [comment]
If this problem only occurs on Windows, then it's most likely to be related to https://github.com/jcupitt/libvips/issues/294. If so, perhaps try to convert the filenames to UTF-8 first.

**Comment by lovell** [comment]
@blowsie Were you able to make any progress?

**Comment by blowsie** [comment]
@lovell , Sorry i forgot to get back to you on this, I would not know how to go about doing this, I run `sharp` via `grunt-sharp`. Renaming the files to standard characters does work fine.

Willing to try and help where possible here, but I can live without this feature.

**Comment by lovell** [comment]
https://github.com/nodejs/node-v0.x-archive/issues/2387 is probably related also. I'm not sure what, if any, sane workaround we can apply right now.

**Comment by blowsie** [comment]
@lovell , Ok well thank you for your time, I will keep an eye out for a solution to this, closing for now.
