### ISSUE TITLE
Where is the 'vips thumbnail' command counterpart?

### ISSUE THREAD

**Issue by joesong168** [lovell/sharp#3194]
## Question about an existing feature

'vips thumbnail' is powerful command to generate small thumbnail from large image in amazing speed. However I couldn't find the equivalent in Sharp. Is it my problem?

**Comment by lovell** [comment]
Did you see https://sharp.pixelplumbing.com/api-resize ?

**Comment by joesong168** [comment]
Yes, I've tried extract before. However my experience is that extract() is far more slower that vip thumbnail when generating small thumbnail from large image. I don't know the implementation of extract(), I guess it uses vips crop instead of vips thumbnail in above situation.

**Comment by lovell** [comment]
Did you see `resize()`?
```js
await sharp('image.jpg').resize({ width: 200 }).toFile('tn_image.jpg');
```
is approximately equivalent to:
```sh
$ vipsthumbnail image.jpg --size=200x
```

**Comment by joesong168** [comment]
Here is my point. Following code did the same thing with two different ways, with or without using vips. The difference is more than 60x in speed. I guess there might be some performance penalty while using extract and size together. Might be there is something we can improve.
The image is available here: https://viewers.etu.wiki/fdb9fb7731cb9ddabf9107fc6e3b0ca9

```
const  fs  = require('fs');
const sharp = require('sharp')

const exec = require("child_process").execSync;
const imageFile = 'fdb9fb7731cb9ddabf9107fc6e3b0ca9'
let image = sharp(imageFile,  {
    limitInputPixels: false,
    sequentialRead: true
  });

const meta = await image.metadata()

const useVips = false

console.time('time')

const [x, y, w, h] = [0, 0, 274159, 5195]
const [width, height] = [268, 6]

if (useVips)  {
  console.log('thumbnail')
  const scale = Math.max(width/w, height/h)
  const [sx, sy, sw, sh] = [Math.round(x * scale), Math.round(y * scale), Math.round(w * scale), Math.round(h * scale)]

  const tempFile = imageFile + '.webp'
  console.log(meta.width * scale)
  exec(`vips thumbnail ${imageFile} ${tempFile} ${Math.round(meta.width * scale)}`);

  await sharp(tempFile).extract({left:sx,top:sy, width: sw, height:sh}).resize(width,height).toFile('result12.webp')
  fs.rmSync(tempFile)
} else {
  console.log('normal')
  await image.extract({left:x,top:y, width: w, height:h}).resize(width,height).toFile('result10.webp')
}

console.timeEnd('time')
```

**Comment by lovell** [comment]
This sample input is a 11 layer TIFF pyramid and `vips thumbnail ...` is able to select a lower resolution subifd as its input, whereas sharp will use the first/largest 274159x5195 layer.

If you add a command line call to `vips extract ...` before `vips thumbnail ...` to match the logic you're using in sharp, you'll see it's much slower as vips too must use the first layer and cannot use a "shrink-on-load" optimisation.

**Comment by kleisauke** [comment]
FWIW, here's the proof that `vipsthumbnail` selects page 9 from the TIFF pyramid during shrink-on-load and that sharp's resize logic is equivalent to `vipsthumbnail`.
```bash
$ vipsthumbnail fdb9fb7731cb9ddabf9107fc6e3b0ca9 -s 317x -o x.webp[Q=80,strip,effort=4] --vips-info
<snip />
VIPS-INFO: 11:07:06.694: input size is 274159 x 5195
VIPS-INFO: 11:07:06.702: loading with factor 9 pre-shrink
VIPS-INFO: 11:07:06.702: pre-shrunk size is 535 x 10
<snip />
$ vipsheader fdb9fb7731cb9ddabf9107fc6e3b0ca9[page=9]
fdb9fb7731cb9ddabf9107fc6e3b0ca9: 535x10 uchar, 3 bands, srgb, tiffload
$ node -e "require('sharp')('fdb9fb7731cb9ddabf9107fc6e3b0ca9', { page: 9 }).resize(317).toFile('x2.webp')"
$ sha256sum x*
1973a3e6e4e8f5963a95adcf0dfdd59ec4dce78e526108afe7cfec455e1a41e3  x2.webp
1973a3e6e4e8f5963a95adcf0dfdd59ec4dce78e526108afe7cfec455e1a41e3  x.webp
```

**Comment by joesong168** [comment]
Thank you both for the explanation. "shrink-on-load" seems to benefit a lot, especially for pyramid tiff. So leverage shrink-on-load to resize first and then to extract would be far more efficient than to do extract first and then to resize. I'll optimize the code accordingly.
