### ISSUE TITLE
Enhancement: add support for WebP compression within TIFF output

### ISSUE THREAD

**Issue by joesong168** [lovell/sharp#3198]
Actually vips support webp in pyramid tiff in certain platform like ubuntu but not windows. Is it possible for sharp to support webp in all platform when vips didn't. The basis for this feature relies on libtiff, so I guess updating libtiff to latest version would supposedly solve the problem.

https://github.com/libvips/libvips/issues/1839

Regards

**Comment by kleisauke** [comment]
I can confirm that this already works on Windows, tested with:
```shell
vips copy zebra.jpg x.tif[compression=webp,pyramid]
```

Perhaps the `packbits` compression should also be allowed? The prebuilt binaries should already include support for this.

We could also add `zstd` and `jp2k` to that list for users who have built sharp with a globally installed libvips with support for those TIFF compression options (using libzstd and OpenJPEG).

**Comment by lovell** [comment]
v0.31.0 now available with this improvement, thank you for the suggestion.
