### ISSUE TITLE
Editing all gif frames

### ISSUE THREAD

**Issue by Lorenzo0111** [lovell/sharp#3199]
### What are you trying to achieve?
I need to add a watermark to a gif

### When you searched for similar issues, what did you find that might be related?
Nothing

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

I tried this code but it didn't work:
```js
  await sharp(original, { animated: true })
  .composite([
    {
      input: watermark,
      gravity: 'center',
      blend: 'overlay'
    }
  ])
  .webp()
  .toFile(original + ".webp");
```

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/2680
