### ISSUE TITLE
Cache memory

### ISSUE THREAD

**Issue by vlapo** [lovell/sharp#320]
Hi, 

I have little problem with memory during upload and resizing image. I just upload file, get metadata, resize and save to disk and my memory increase about 330MB and stay on this high level.

Here is my cache stats:
```{ current: 2, high: 4, memory: 100, items: 500 }```

After disable cache ```sharp.cache(0)``` memory increase only about 15MB.

Is this normal behavior? I think cache has memory limit 100MB.

**Comment by vlapo** [comment]
After investigation ... Death to progress jpeg!!
https://github.com/jcupitt/libvips/issues/77

**Comment by lovell** [comment]
Glad you solved it. There'll be some enhancements to how libvips' cache is exposed and configured from sharp v0.13.0.

**Comment by vlapo** [comment]
Yeah, we disabled cache globally.
Actually I have little doubts  about behavior of libvips cache with progressive jpeg. 

Default, there is 100MB maximum memory size of cache. Why resize operation of progressive jpeg allocate over 300MB of memory in cache? Maybe I don`t understand memory limit of libvips cache ?

**Comment by lovell** [comment]
Memory allocated outside libvips is not included and I suspect libjpeg needs a lot of its own working memory for progressive decode.

**Comment by vlapo** [comment]
Of course. Thnx for explanation ;) 
First I saw increase memory (dont know used image is progressive jpeg) I thought it is memory leak.
Maybe disable cache for progressive jpeg could be nice improvement (sharp/libvips).
