### ISSUE TITLE
err code 1

### ISSUE THREAD

**Issue by sageeh** [lovell/sharp#3202]
## Possible install-time or require-time problem

- [ x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [ x] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

- [ x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Is this a problem with filesystem permissions?

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7 or later, does the user running `npm install` own the directory it is run in?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Users\\sagee\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   '--foreground-scripts',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@8.1.4
npm info using node@v16.14.2
npm timing npm:load:whichnode Completed in 1ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:C:\Users\sagee\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 3ms
npm timing config:load:builtin Completed in 3ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 1ms
npm timing config:load:file:C:\Users\sagee\Desktop\New folder (2)\.npmrc Completed in 0ms
npm timing config:load:project Completed in 4ms
npm timing config:load:file:C:\Users\sagee\.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:C:\Users\sagee\AppData\Roaming\npm\etc\npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 14ms
npm timing npm:load:configload Completed in 14ms
npm timing npm:load:setTitle Completed in 0ms
npm timing npm:load:setupLog Completed in 0ms
npm timing config:load:flatten Completed in 2ms
npm timing npm:load:cleanupLog Completed in 3ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 1ms
npm timing npm:load Completed in 36ms
npm timing arborist:ctor Completed in 1ms
npm timing arborist:ctor Completed in 1ms
npm timing idealTree:init Completed in 12ms
npm timing idealTree:userRequests Completed in 2ms
npm http fetch GET 200 https://registry.npmjs.org/sharp 502ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/node-addon-api 220ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/tar-fs 518ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/semver 528ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/prebuild-install 540ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 560ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/tunnel-agent 589ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color 1157ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/simple-get 1270ms (cache revalidated)
npm timing idealTree:#root Completed in 1795ms
npm http fetch GET 200 https://registry.npmjs.org/minimist 95ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color-string 204ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/expand-template 220ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/npmlog 218ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/node-abi 249ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/napi-build-utils 255ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/simple-concat 297ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/pump 342ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/mkdirp-classic 368ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/chownr 623ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/safe-buffer 639ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/rc 689ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/decompress-response 702ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/once 735ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/tar-stream 748ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/lru-cache 779ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/github-from-package 887ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-convert 1044ms (cache revalidated)
npm timing idealTree:node_modules/sharp Completed in 1091ms
npm http fetch GET 200 https://registry.npmjs.org/color-name 143ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle 322ms (cache revalidated)
npm timing idealTree:node_modules/color Completed in 344ms
npm timing idealTree:node_modules/color-convert Completed in 6ms
npm timing idealTree:node_modules/color-name Completed in 1ms
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 332ms (cache revalidated)
npm timing idealTree:node_modules/color-string Completed in 343ms
npm timing idealTree:node_modules/detect-libc Completed in 0ms
npm timing idealTree:node_modules/node-addon-api Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/set-blocking 163ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/are-we-there-yet 178ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/gauge 207ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/console-control-strings 227ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/end-of-stream 239ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/ini 238ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/strip-json-comments 245ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/deep-extend 268ms (cache revalidated)
npm timing idealTree:node_modules/prebuild-install Completed in 321ms
npm timing idealTree:node_modules/expand-template Completed in 0ms
npm timing idealTree:node_modules/github-from-package Completed in 0ms
npm timing idealTree:node_modules/minimist Completed in 0ms
npm timing idealTree:node_modules/mkdirp-classic Completed in 0ms
npm timing idealTree:node_modules/napi-build-utils Completed in 0ms
npm timing idealTree:node_modules/node-abi Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/delegates 207ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/readable-stream 213ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/object-assign 232ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/aproba 253ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/strip-ansi 251ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/string-width 261ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/signal-exit 278ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/has-unicode 291ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/wide-align 291ms (cache revalidated)
npm timing idealTree:node_modules/npmlog Completed in 315ms
npm http fetch GET 200 https://registry.npmjs.org/core-util-is 182ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/string_decoder 189ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/isarray 201ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/process-nextick-args 210ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/inherits 228ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/util-deprecate 928ms (cache revalidated)
npm timing idealTree:node_modules/are-we-there-yet Completed in 968ms
npm timing idealTree:node_modules/console-control-strings Completed in 0ms
npm timing idealTree:node_modules/delegates Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/is-fullwidth-code-point 139ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/ansi-regex 179ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/code-point-at 240ms (cache revalidated)
npm timing idealTree:node_modules/gauge Completed in 276ms
npm timing idealTree:node_modules/aproba Completed in 0ms
npm timing idealTree:node_modules/has-unicode Completed in 0ms
npm timing idealTree:node_modules/object-assign Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/wrappy 170ms (cache revalidated)
npm timing idealTree:node_modules/pump Completed in 184ms
npm timing idealTree:node_modules/end-of-stream Completed in 0ms
npm timing idealTree:node_modules/once Completed in 2ms
npm timing idealTree:node_modules/rc Completed in 3ms
npm timing idealTree:node_modules/deep-extend Completed in 0ms
npm timing idealTree:node_modules/ini Completed in 0ms
npm timing idealTree:node_modules/readable-stream Completed in 7ms
npm timing idealTree:node_modules/core-util-is Completed in 0ms
npm timing idealTree:node_modules/inherits Completed in 0ms
npm timing idealTree:node_modules/isarray Completed in 0ms
npm timing idealTree:node_modules/process-nextick-args Completed in 0ms
npm timing idealTree:node_modules/safe-buffer Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/yallist 171ms (cache revalidated)
npm timing idealTree:node_modules/semver Completed in 177ms
npm timing idealTree:node_modules/lru-cache Completed in 9ms
npm timing idealTree:node_modules/set-blocking Completed in 0ms
npm timing idealTree:node_modules/signal-exit Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/mimic-response 153ms (cache revalidated)
npm timing idealTree:node_modules/simple-get Completed in 168ms
npm timing idealTree:node_modules/decompress-response Completed in 3ms
npm timing idealTree:node_modules/mimic-response Completed in 0ms
npm timing idealTree:node_modules/simple-concat Completed in 0ms
npm timing idealTree:node_modules/simple-swizzle Completed in 3ms
npm timing idealTree:node_modules/is-arrayish Completed in 0ms
npm timing idealTree:node_modules/string_decoder Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/number-is-nan 231ms (cache revalidated)
npm timing idealTree:node_modules/string-width Completed in 257ms
npm timing idealTree:node_modules/code-point-at Completed in 0ms
npm timing idealTree:node_modules/is-fullwidth-code-point Completed in 8ms
npm timing idealTree:node_modules/number-is-nan Completed in 0ms
npm timing idealTree:node_modules/strip-ansi Completed in 4ms
npm timing idealTree:node_modules/ansi-regex Completed in 0ms
npm timing idealTree:node_modules/strip-json-comments Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/fs-constants 207ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/bl 215ms (cache revalidated)
npm timing idealTree:node_modules/tar-fs Completed in 235ms
npm timing idealTree:node_modules/chownr Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/buffer 171ms (cache revalidated)
npm timing idealTree:node_modules/tar-stream Completed in 202ms
npm http fetch GET 200 https://registry.npmjs.org/ieee754 176ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/base64-js 196ms (cache revalidated)
npm timing idealTree:node_modules/bl Completed in 211ms
npm timing idealTree:node_modules/buffer Completed in 6ms
npm timing idealTree:node_modules/base64-js Completed in 0ms
npm timing idealTree:node_modules/fs-constants Completed in 0ms
npm timing idealTree:node_modules/ieee754 Completed in 0ms
npm timing idealTree:node_modules/tunnel-agent Completed in 0ms
npm timing idealTree:node_modules/util-deprecate Completed in 1ms
npm timing idealTree:node_modules/wide-align Completed in 0ms
npm timing idealTree:node_modules/wrappy Completed in 0ms
npm timing idealTree:node_modules/yallist Completed in 0ms
npm timing idealTree:node_modules/bl/node_modules/readable-stream Completed in 0ms
npm timing idealTree:node_modules/tar-stream/node_modules/readable-stream Completed in 0ms
npm timing idealTree:buildDeps Completed in 7079ms
npm timing idealTree:fixDepFlags Completed in 4ms
npm timing idealTree Completed in 7109ms
npm timing reify:loadTrees Completed in 7112ms
npm timing reify:diffTrees Completed in 11ms
npm timing reify:retireShallow Completed in 1ms
npm timing reify:createSparse Completed in 88ms
npm timing reify:loadBundles Completed in 0ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 453ms
npm timing auditReport:getReport Completed in 464ms
npm timing auditReport:init Completed in 0ms
npm timing reify:audit Completed in 471ms
npm timing reifyNode:node_modules/number-is-nan Completed in 565ms
npm timing reifyNode:node_modules/code-point-at Completed in 567ms
npm timing reifyNode:node_modules/ansi-regex Completed in 568ms
npm timing reifyNode:node_modules/chownr Completed in 569ms
npm timing reifyNode:node_modules/is-fullwidth-code-point Completed in 569ms
npm timing reifyNode:node_modules/process-nextick-args Completed in 567ms
npm timing reifyNode:node_modules/once Completed in 567ms
npm timing reifyNode:node_modules/ini Completed in 569ms
npm timing reifyNode:node_modules/has-unicode Completed in 568ms
npm timing reifyNode:node_modules/strip-json-comments Completed in 572ms
npm timing reifyNode:node_modules/wide-align Completed in 572ms
npm timing reifyNode:node_modules/aproba Completed in 572ms
npm timing reifyNode:node_modules/strip-ansi Completed in 574ms
npm timing reifyNode:node_modules/string-width Completed in 573ms
npm timing reifyNode:node_modules/object-assign Completed in 574ms
npm timing reifyNode:node_modules/wrappy Completed in 576ms
npm timing reifyNode:node_modules/end-of-stream Completed in 577ms
npm timing reifyNode:node_modules/mkdirp-classic Completed in 575ms
npm timing reifyNode:node_modules/color-string Completed in 577ms
npm timing reifyNode:node_modules/color-name Completed in 578ms
npm timing reifyNode:node_modules/simple-swizzle Completed in 580ms
npm timing reifyNode:node_modules/lru-cache Completed in 590ms
npm timing reifyNode:node_modules/core-util-is Completed in 590ms
npm timing reifyNode:node_modules/tunnel-agent Completed in 585ms
npm timing reifyNode:node_modules/color Completed in 590ms
npm timing reifyNode:node_modules/ieee754 Completed in 607ms
npm timing reifyNode:node_modules/fs-constants Completed in 607ms
npm timing reifyNode:node_modules/mimic-response Completed in 605ms
npm timing reifyNode:node_modules/decompress-response Completed in 605ms
npm timing reifyNode:node_modules/inherits Completed in 605ms
npm timing reifyNode:node_modules/signal-exit Completed in 604ms
npm timing reifyNode:node_modules/set-blocking Completed in 605ms
npm timing reifyNode:node_modules/console-control-strings Completed in 607ms
npm timing reifyNode:node_modules/yallist Completed in 614ms
npm timing reifyNode:node_modules/napi-build-utils Completed in 610ms
npm timing reifyNode:node_modules/npmlog Completed in 611ms
npm timing reifyNode:node_modules/safe-buffer Completed in 617ms
npm timing reifyNode:node_modules/is-arrayish Completed in 622ms
npm timing reifyNode:node_modules/base64-js Completed in 630ms
npm timing reifyNode:node_modules/util-deprecate Completed in 626ms
npm timing reifyNode:node_modules/expand-template Completed in 624ms
npm timing reifyNode:node_modules/deep-extend Completed in 629ms
npm timing reifyNode:node_modules/simple-concat Completed in 635ms
npm timing reifyNode:node_modules/string_decoder Completed in 636ms
npm timing reifyNode:node_modules/detect-libc Completed in 632ms
npm timing reifyNode:node_modules/pump Completed in 637ms
npm timing reifyNode:node_modules/color-convert Completed in 643ms
npm timing reifyNode:node_modules/buffer Completed in 657ms
npm timing reifyNode:node_modules/simple-get Completed in 645ms
npm timing reifyNode:node_modules/isarray Completed in 653ms
npm timing reifyNode:node_modules/delegates Completed in 652ms
npm timing reifyNode:node_modules/tar-stream Completed in 663ms
npm timing reifyNode:node_modules/are-we-there-yet Completed in 660ms
npm timing reifyNode:node_modules/bl Completed in 682ms
npm timing reifyNode:node_modules/rc Completed in 682ms
npm timing reifyNode:node_modules/github-from-package Completed in 683ms
npm timing reifyNode:node_modules/node-abi Completed in 689ms
npm timing reifyNode:node_modules/prebuild-install Completed in 691ms
npm timing reifyNode:node_modules/gauge Completed in 708ms
npm timing reifyNode:node_modules/tar-fs Completed in 710ms
npm timing reifyNode:node_modules/minimist Completed in 715ms
npm timing reifyNode:node_modules/node-addon-api Completed in 717ms
npm timing reifyNode:node_modules/readable-stream Completed in 724ms
npm timing reifyNode:node_modules/tar-stream/node_modules/readable-stream Completed in 736ms
npm timing reifyNode:node_modules/bl/node_modules/readable-stream Completed in 739ms
npm timing reifyNode:node_modules/semver Completed in 752ms
npm timing reifyNode:node_modules/sharp Completed in 753ms
npm timing reify:unpack Completed in 769ms
npm timing reify:unretire Completed in 0ms
npm timing build:queue Completed in 3ms
npm timing build:link:node_modules/prebuild-install Completed in 10ms
npm timing build:link:node_modules/rc Completed in 9ms
npm timing build:link:node_modules/semver Completed in 10ms
npm timing build:link Completed in 12ms
npm info run sharp@0.30.4 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

> sharp@0.30.4 install
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.12.2/libvips-8.12.2-win32-x64.tar.brnstall/dll-copy && prebuild-install) || (node install/c 
sharp: Installation error: connect ETIMEDOUT 185.199.109.133:443l node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/c 
sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm info run sharp@0.30.4 install { code: 1, signal: null }
npm timing reify:rollback:createSparse Completed in 101ms
npm timing reify:rollback:retireShallow Completed in 0ms
npm timing command:install Completed in 30171ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (C:\Users\sagee\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
npm verb stack     at ChildProcess.emit (node:events:526:28)
npm verb stack     at maybeClose (node:internal/child_process:1092:16)
npm verb stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm verb pkgid sharp@0.30.4
npm verb cwd C:\Users\sagee\Desktop\New folder (2)
npm verb Windows_NT 10.0.19042
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\sagee\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose" "--foreground-scripts" "sharp"
npm verb node v16.14.2
npm verb npm  v8.1.4
npm ERR! code 1
npm ERR! path C:\Users\sagee\Desktop\New folder (2)\node_modules\sharp
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm verb exit 1
npm timing npm Completed in 30521ms
npm verb unfinished npm timer reify 1650670739518
npm verb unfinished npm timer reify:build 1650670747546
npm verb unfinished npm timer build 1650670747546
npm verb unfinished npm timer build:deps 1650670747546
npm verb unfinished npm timer build:run:install 1650670747564
npm verb unfinished npm timer build:run:install:node_modules/sharp 1650670747565
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sagee\AppData\Local\npm-cache\_logs\2022-04-22T23_39_29_702Z-debug.log

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
    Memory: 8.53 GB / 15.85 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.4 - C:\Program Files\nodejs\npm.CMD

#The error i get when i use "npm i sharp " 
npm ERR! code 1
npm ERR! path C:\Users\sagee\Desktop\New folder (2)\node_modules\sharp
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.12.2/libvips-8.12.2-win32-x64.tar.br
npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! sharp: Installation error: connect ETIMEDOUT 185.199.109.133:443

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sagee\AppData\Local\npm-cache\_logs\2022-04-22T23_47_29_354Z-debug.log

**Comment by lovell** [comment]
> npm ERR! sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.12.2/libvips-8.12.2-win32-x64.tar.br
>  npm ERR! sharp: Installation error: connect ETIMEDOUT 185.199.109.133:443

It looks like there is a networking problem connecting to github.com to download prebuilt binaries.

If you're based in China, please see https://sharp.pixelplumbing.com/install#chinese-mirror

**Comment by sageeh** [comment]
actullay im located at syria but the china method worked fine

**Comment by miaoihan** [comment]
But there is no relevant description of chinese-mirror at this link 
[](https://sharp.pixelplumbing.com/install#chinese-mirror)

**Comment by lovell** [comment]
This issue is out-of-date. As of sharp v0.33.0+ everything you require is published to npm and is therefore available via cnpm, with no extra mirror configuration needed.
