### ISSUE TITLE
pgrade the new version of sharp, can not be installed!

### ISSUE THREAD

**Issue by iori2882** [lovell/sharp#3203]
Upgrade node16, the old version of sharp reports an error, upgrade the new version of sharp, can not be installed!

- [√ ] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [ √] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

- [√ ] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Is this a problem with filesystem permissions? yes

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7 or later, does the user running `npm install` own the directory it is run in?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

C:\Windows\system32>npm install --verbose --foreground-scripts sharp
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Users\\doubleten\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   '--foreground-scripts',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@7.9.0
npm info using node@v16.14.2
npm timing npm:load:whichnode Completed in 3ms
npm timing config:load:defaults Completed in 2ms
npm timing config:load:file:C:\Users\doubleten\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 3ms
npm timing config:load:builtin Completed in 3ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:C:\Windows\system32\.npmrc Completed in 0ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:C:\Users\doubleten\.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:C:\Users\doubleten\AppData\Roaming\npm\etc\npmrc Completed in 1ms
npm timing config:load:global Completed in 1ms
npm timing config:load:validate Completed in 1ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 12ms
npm timing npm:load:configload Completed in 12ms
npm timing npm:load:setTitle Completed in 0ms
npm timing npm:load:setupLog Completed in 2ms
npm timing npm:load:cleanupLog Completed in 2ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 1ms
npm timing npm:load Completed in 38ms
npm timing config:load:flatten Completed in 2ms
npm timing arborist:ctor Completed in 1ms
npm timing idealTree:init Completed in 14ms
npm timing idealTree:userRequests Completed in 3ms
npm http fetch GET 304 https://registry.npmmirror.com/sharp 266ms (from cache)
npm http fetch GET 304 https://registry.npmmirror.com/tar-fs 99ms (from cache)
npm http fetch GET 304 https://registry.npmmirror.com/detect-libc 141ms (from cache)
npm http fetch GET 200 https://registry.npmmirror.com/color 155ms
npm http fetch GET 304 https://registry.npmmirror.com/tunnel-agent 167ms (from cache)
npm http fetch GET 200 https://registry.npmmirror.com/semver 172ms
npm http fetch GET 304 https://registry.npmmirror.com/simple-get 183ms (from cache)
npm http fetch GET 304 https://registry.npmmirror.com/node-addon-api 186ms (from cache)
npm http fetch GET 304 https://registry.npmmirror.com/prebuild-install 213ms (from cache)
npm timing idealTree:#root Completed in 495ms
npm http fetch GET 200 https://registry.npmmirror.com/safe-buffer 68ms
npm http fetch GET 200 https://registry.npmmirror.com/tar-stream 72ms
npm http fetch GET 200 https://registry.npmmirror.com/color-convert 94ms
npm http fetch GET 200 https://registry.npmmirror.com/decompress-response 88ms
npm http fetch GET 200 https://registry.npmmirror.com/once 109ms
npm http fetch GET 200 https://registry.npmmirror.com/minimist 119ms
npm http fetch GET 200 https://registry.npmmirror.com/color-string 125ms
npm http fetch GET 304 https://registry.npmmirror.com/chownr 119ms (from cache)
npm http fetch GET 304 https://registry.npmmirror.com/expand-template 130ms (from cache)
npm http fetch GET 200 https://registry.npmmirror.com/lru-cache 128ms
npm http fetch GET 200 https://registry.npmmirror.com/pump 145ms
npm http fetch GET 304 https://registry.npmmirror.com/github-from-package 155ms (from cache)
npm http fetch GET 304 https://registry.npmmirror.com/npmlog 156ms (from cache)
npm http fetch GET 304 https://registry.npmmirror.com/node-abi 161ms (from cache)
npm http fetch GET 304 https://registry.npmmirror.com/simple-concat 164ms (from cache)
npm http fetch GET 200 https://registry.npmmirror.com/rc 174ms
npm http fetch GET 304 https://registry.npmmirror.com/mkdirp-classic 187ms (from cache)
npm http fetch GET 304 https://registry.npmmirror.com/napi-build-utils 199ms (from cache)
npm timing idealTree:node_modules/sharp Completed in 213ms
npm http fetch GET 200 https://registry.npmmirror.com/color-name 42ms
npm http fetch GET 200 https://registry.npmmirror.com/simple-swizzle 43ms
npm timing idealTree:node_modules/color Completed in 47ms
npm timing idealTree:node_modules/color-convert Completed in 1ms
npm timing idealTree:node_modules/color-name Completed in 0ms
npm http fetch GET 200 https://registry.npmmirror.com/is-arrayish 65ms
npm timing idealTree:node_modules/color-string Completed in 68ms
npm timing idealTree:node_modules/detect-libc Completed in 0ms
npm timing idealTree:node_modules/node-addon-api Completed in 0ms
npm http fetch GET 200 https://registry.npmmirror.com/ini 28ms
npm http fetch GET 200 https://registry.npmmirror.com/strip-json-comments 52ms
npm http fetch GET 304 https://registry.npmmirror.com/gauge 66ms (from cache)
npm http fetch GET 304 https://registry.npmmirror.com/console-control-strings 77ms (from cache)
npm http fetch GET 304 https://registry.npmmirror.com/set-blocking 77ms (from cache)
npm http fetch GET 200 https://registry.npmmirror.com/deep-extend 110ms
npm http fetch GET 200 https://registry.npmmirror.com/end-of-stream 113ms
npm http fetch GET 304 https://registry.npmmirror.com/are-we-there-yet 122ms (from cache)
npm timing idealTree:node_modules/prebuild-install Completed in 130ms
npm timing idealTree:node_modules/expand-template Completed in 0ms
npm timing idealTree:node_modules/github-from-package Completed in 0ms
npm timing idealTree:node_modules/minimist Completed in 0ms
npm timing idealTree:node_modules/mkdirp-classic Completed in 0ms
npm timing idealTree:node_modules/napi-build-utils Completed in 0ms
npm timing idealTree:node_modules/node-abi Completed in 0ms
npm http fetch GET 304 https://registry.npmmirror.com/aproba 42ms (from cache)
npm http fetch GET 200 https://registry.npmmirror.com/signal-exit 43ms
npm http fetch GET 200 https://registry.npmmirror.com/strip-ansi 45ms
npm http fetch GET 200 https://registry.npmmirror.com/string-width 49ms
npm http fetch GET 304 https://registry.npmmirror.com/delegates 54ms (from cache)
npm http fetch GET 200 https://registry.npmmirror.com/readable-stream 58ms
npm http fetch GET 304 https://registry.npmmirror.com/wide-align 58ms (from cache)
npm http fetch GET 304 https://registry.npmmirror.com/object-assign 71ms (from cache)
npm http fetch GET 304 https://registry.npmmirror.com/has-unicode 73ms (from cache)
npm timing idealTree:node_modules/npmlog Completed in 79ms
npm http fetch GET 200 https://registry.npmmirror.com/core-util-is 33ms
npm http fetch GET 200 https://registry.npmmirror.com/string_decoder 49ms
npm http fetch GET 200 https://registry.npmmirror.com/isarray 57ms
npm http fetch GET 200 https://registry.npmmirror.com/inherits 59ms
npm http fetch GET 200 https://registry.npmmirror.com/process-nextick-args 61ms
npm http fetch GET 200 https://registry.npmmirror.com/util-deprecate 61ms
npm timing idealTree:node_modules/are-we-there-yet Completed in 69ms
npm timing idealTree:node_modules/console-control-strings Completed in 0ms
npm timing idealTree:node_modules/delegates Completed in 0ms
npm http fetch GET 200 https://registry.npmmirror.com/is-fullwidth-code-point 41ms
npm http fetch GET 304 https://registry.npmmirror.com/code-point-at 50ms (from cache)
npm http fetch GET 200 https://registry.npmmirror.com/ansi-regex 121ms
npm timing idealTree:node_modules/gauge Completed in 130ms
npm timing idealTree:node_modules/aproba Completed in 0ms
npm timing idealTree:node_modules/has-unicode Completed in 0ms
npm timing idealTree:node_modules/object-assign Completed in 0ms
npm http fetch GET 200 https://registry.npmmirror.com/wrappy 39ms
npm timing idealTree:node_modules/pump Completed in 43ms
npm timing idealTree:node_modules/end-of-stream Completed in 1ms
npm timing idealTree:node_modules/once Completed in 0ms
npm timing idealTree:node_modules/rc Completed in 1ms
npm timing idealTree:node_modules/deep-extend Completed in 0ms
npm timing idealTree:node_modules/ini Completed in 0ms
npm timing idealTree:node_modules/readable-stream Completed in 4ms
npm timing idealTree:node_modules/core-util-is Completed in 0ms
npm timing idealTree:node_modules/inherits Completed in 0ms
npm timing idealTree:node_modules/isarray Completed in 0ms
npm timing idealTree:node_modules/process-nextick-args Completed in 0ms
npm timing idealTree:node_modules/safe-buffer Completed in 0ms
npm http fetch GET 200 https://registry.npmmirror.com/yallist 40ms
npm timing idealTree:node_modules/semver Completed in 44ms
npm timing idealTree:node_modules/lru-cache Completed in 1ms
npm timing idealTree:node_modules/set-blocking Completed in 0ms
npm timing idealTree:node_modules/signal-exit Completed in 0ms
npm http fetch GET 200 https://registry.npmmirror.com/mimic-response 36ms
npm timing idealTree:node_modules/simple-get Completed in 40ms
npm timing idealTree:node_modules/decompress-response Completed in 1ms
npm timing idealTree:node_modules/mimic-response Completed in 0ms
npm timing idealTree:node_modules/simple-concat Completed in 0ms
npm timing idealTree:node_modules/simple-swizzle Completed in 0ms
npm timing idealTree:node_modules/is-arrayish Completed in 0ms
npm timing idealTree:node_modules/string_decoder Completed in 0ms
npm http fetch GET 304 https://registry.npmmirror.com/number-is-nan 46ms (from cache)
npm timing idealTree:node_modules/string-width Completed in 49ms
npm timing idealTree:node_modules/code-point-at Completed in 0ms
npm timing idealTree:node_modules/is-fullwidth-code-point Completed in 2ms
npm timing idealTree:node_modules/number-is-nan Completed in 0ms
npm timing idealTree:node_modules/strip-ansi Completed in 1ms
npm timing idealTree:node_modules/ansi-regex Completed in 0ms
npm timing idealTree:node_modules/strip-json-comments Completed in 0ms
npm http fetch GET 200 https://registry.npmmirror.com/bl 38ms
npm http fetch GET 304 https://registry.npmmirror.com/fs-constants 49ms (from cache)
npm timing idealTree:node_modules/tar-fs Completed in 53ms
npm timing idealTree:node_modules/chownr Completed in 0ms
npm http fetch GET 304 https://registry.npmmirror.com/buffer 51ms (from cache)
npm timing idealTree:node_modules/tar-stream Completed in 59ms
npm http fetch GET 304 https://registry.npmmirror.com/ieee754 49ms (from cache)
npm http fetch GET 304 https://registry.npmmirror.com/base64-js 51ms (from cache)
npm timing idealTree:node_modules/bl Completed in 55ms
npm timing idealTree:node_modules/buffer Completed in 1ms
npm timing idealTree:node_modules/base64-js Completed in 0ms
npm timing idealTree:node_modules/fs-constants Completed in 0ms
npm timing idealTree:node_modules/ieee754 Completed in 0ms
npm timing idealTree:node_modules/tunnel-agent Completed in 0ms
npm timing idealTree:node_modules/util-deprecate Completed in 0ms
npm timing idealTree:node_modules/wide-align Completed in 0ms
npm timing idealTree:node_modules/wrappy Completed in 0ms
npm timing idealTree:node_modules/yallist Completed in 0ms
npm timing idealTree:node_modules/bl/node_modules/readable-stream Completed in 0ms
npm timing idealTree:node_modules/tar-stream/node_modules/readable-stream Completed in 0ms
npm timing idealTree:buildDeps Completed in 1641ms
npm timing idealTree:fixDepFlags Completed in 1ms
npm timing idealTree Completed in 1663ms
npm timing reify:loadTrees Completed in 1664ms
npm timing reify:diffTrees Completed in 1ms
npm timing reify:retireShallow Completed in 0ms
npm timing reify:createSparse Completed in 39ms
npm timing reify:loadBundles Completed in 0ms
npm http fetch POST 301 https://registry.npm.taobao.org/-/npm/v1/security/advisories/bulk 93ms
npm http fetch POST 301 https://registry.npm.taobao.org/-/npm/v1/security/audits/quick 137ms
npm verb audit error FetchError: invalid json response body at https://registry.npm.taobao.org/-/npm/v1/security/audits/quick reason: Unexpected token < in JSON at position 0
npm verb audit error     at C:\Users\doubleten\AppData\Roaming\npm\node_modules\npm\node_modules\minipass-fetch\lib\body.js:77:31
npm verb audit error     at async Map.[getReport] (C:\Users\doubleten\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\audit-report.js:317:40)
npm verb audit error     at async Map.run (C:\Users\doubleten\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\audit-report.js:103:19)
npm verb audit error  FetchError: invalid json response body at https://registry.npm.taobao.org/-/npm/v1/security/audits/quick reason: Unexpected token < in JSON at position 0
npm verb audit error     at C:\Users\doubleten\AppData\Roaming\npm\node_modules\npm\node_modules\minipass-fetch\lib\body.js:77:31
npm verb audit error     at async Map.[getReport] (C:\Users\doubleten\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\audit-report.js:317:40)
npm verb audit error     at async Map.run (C:\Users\doubleten\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\audit-report.js:103:19) {
npm verb audit error   code: 'FETCH_ERROR',
npm verb audit error   errno: 'FETCH_ERROR',
npm verb audit error   type: 'invalid-json'
npm verb audit error }
npm timing auditReport:getReport Completed in 250ms
npm timing reify:audit Completed in 251ms
npm timing reifyNode:node_modules/chownr Completed in 254ms
npm timing reifyNode:node_modules/number-is-nan Completed in 256ms
npm timing reifyNode:node_modules/is-fullwidth-code-point Completed in 256ms
npm timing reifyNode:node_modules/code-point-at Completed in 257ms
npm timing reifyNode:node_modules/ansi-regex Completed in 258ms
npm timing reifyNode:node_modules/process-nextick-args Completed in 259ms
npm timing reifyNode:node_modules/strip-json-comments Completed in 259ms
npm timing reifyNode:node_modules/ini Completed in 260ms
npm timing reifyNode:node_modules/wrappy Completed in 261ms
npm timing reifyNode:node_modules/once Completed in 260ms
npm timing reifyNode:node_modules/end-of-stream Completed in 261ms
npm timing reifyNode:node_modules/wide-align Completed in 261ms
npm timing reifyNode:node_modules/strip-ansi Completed in 262ms
npm timing reifyNode:node_modules/object-assign Completed in 262ms
npm timing reifyNode:node_modules/aproba Completed in 263ms
npm timing reifyNode:node_modules/string-width Completed in 265ms
npm timing reifyNode:node_modules/has-unicode Completed in 265ms
npm timing reifyNode:node_modules/color-string Completed in 266ms
npm timing reifyNode:node_modules/mkdirp-classic Completed in 268ms
npm timing reifyNode:node_modules/simple-swizzle Completed in 267ms
npm timing reifyNode:node_modules/color-name Completed in 268ms
npm timing reifyNode:node_modules/ieee754 Completed in 272ms
npm timing reifyNode:node_modules/fs-constants Completed in 273ms
npm timing reifyNode:node_modules/mimic-response Completed in 274ms
npm timing reifyNode:node_modules/decompress-response Completed in 275ms
npm timing reifyNode:node_modules/lru-cache Completed in 276ms
npm timing reifyNode:node_modules/inherits Completed in 276ms
npm timing reifyNode:node_modules/core-util-is Completed in 277ms
npm timing reifyNode:node_modules/signal-exit Completed in 276ms
npm timing reifyNode:node_modules/set-blocking Completed in 277ms
npm timing reifyNode:node_modules/console-control-strings Completed in 277ms
npm timing reifyNode:node_modules/tunnel-agent Completed in 280ms
npm timing reifyNode:node_modules/base64-js Completed in 285ms
npm timing reifyNode:node_modules/color Completed in 282ms
npm timing reifyNode:node_modules/util-deprecate Completed in 286ms
npm timing reifyNode:node_modules/yallist Completed in 286ms
npm timing reifyNode:node_modules/expand-template Completed in 286ms
npm timing reifyNode:node_modules/simple-concat Completed in 290ms
npm timing reifyNode:node_modules/safe-buffer Completed in 291ms
npm timing reifyNode:node_modules/string_decoder Completed in 292ms
npm timing reifyNode:node_modules/deep-extend Completed in 292ms
npm timing reifyNode:node_modules/npmlog Completed in 292ms
npm timing reifyNode:node_modules/pump Completed in 292ms
npm timing reifyNode:node_modules/napi-build-utils Completed in 293ms
npm timing reifyNode:node_modules/is-arrayish Completed in 298ms
npm timing reifyNode:node_modules/isarray Completed in 299ms
npm timing reifyNode:node_modules/delegates Completed in 300ms
npm timing reifyNode:node_modules/color-convert Completed in 301ms
npm timing reifyNode:node_modules/detect-libc Completed in 302ms
npm timing reifyNode:node_modules/are-we-there-yet Completed in 305ms
npm timing reifyNode:node_modules/tar-stream Completed in 307ms
npm timing reifyNode:node_modules/simple-get Completed in 310ms
npm timing reifyNode:node_modules/buffer Completed in 314ms
npm timing reifyNode:node_modules/github-from-package Completed in 317ms
npm timing reifyNode:node_modules/rc Completed in 320ms
npm timing reifyNode:node_modules/bl Completed in 324ms
npm timing reifyNode:node_modules/prebuild-install Completed in 323ms
npm timing reifyNode:node_modules/node-abi Completed in 332ms
npm timing reifyNode:node_modules/gauge Completed in 343ms
npm timing reifyNode:node_modules/minimist Completed in 348ms
npm timing reifyNode:node_modules/readable-stream Completed in 368ms
npm timing reifyNode:node_modules/tar-stream/node_modules/readable-stream Completed in 376ms
npm timing reifyNode:node_modules/bl/node_modules/readable-stream Completed in 376ms
npm timing reifyNode:node_modules/node-addon-api Completed in 382ms
npm timing reifyNode:node_modules/semver Completed in 388ms
npm timing reifyNode:node_modules/tar-fs Completed in 389ms
npm timing reifyNode:node_modules/sharp Completed in 401ms
npm timing reify:unpack Completed in 405ms
npm timing reify:unretire Completed in 1ms
npm timing build:queue Completed in 3ms
npm timing build:link:node_modules/rc Completed in 7ms
npm timing build:link:node_modules/prebuild-install Completed in 9ms
npm timing build:link:node_modules/semver Completed in 8ms
npm timing build:link Completed in 10ms
npm info run sharp@0.30.4 install node_modules/sharp node-gyp rebuild

> sharp@0.30.4 install
> node-gyp rebuild

gyp info it worked if it ends with oknfo run sharp@0.30.4 install node_modules/sharp node-gyp rebuild
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\doubleten\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild'
gyp verb cli ]
gyp info using node-gyp@7.1.2
 info using node@16.14.2 | win32 | x64 info run sharp@0.30.4 install node_modules/sharp node-gyp rebuild
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python checking Python explicitly set from command line or npm configurationgyp rebuild
gyp verb find Python - "--python=" or "npm config get python" is "C:\Users\doubleten\.windows-build-tools\python310\python.exe"
gyp verb find Python - executing "C:\Users\doubleten\.windows-build-tools\python310\python.exe" to get executable path
gyp verb find Python - "C:\Users\doubleten\.windows-build-tools\python310\python.exe" is not in PATH or produced an error
gyp verb find Python Python is not set from environment variable PYTHONmodules/sharp node-gyp rebuild
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - executable path is "C:\Users\doubleten\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe"
gyp verb find Python - executing "C:\Users\doubleten\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe" to get version
gyp verb find Python - version is "3.10.4"un sharp@0.30.4 install node_modules/sharp node-gyp rebuild
gyp info find Python using Python version 3.10.4 found at "C:\Users\doubleten\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe"
gyp verb get node dir no --target version specified, falling back to host node version: 16.14.2
gyp verb command install [ '16.14.2' ]
gyp verb install input version string "16.14.2"arp@0.30.4 install node_modules/sharp node-gyp rebuild
gyp verb install installing version: 16.14.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 16.14.2
gyp verb build dir attempting to create "build" dir: C:\Windows\system32\node_modules\sharp\build
gyp verb build dir "build" dir needed to be created? C:\Windows\system32\node_modules\sharp\build
gyp verb find VS msvs_version not set from command line or npm config
gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp verb find VS checking VS2017 (15.9.28307.1216) found at:stall node_modules/sharp node-gyp rebuild
gyp verb find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp verb find VS - found "Visual Studio C++ core features"
gyp verb find VS - found VC++ toolset: v141
gyp verb find VS - found Windows SDK: 10.0.17763.0
gyp info find VS using VS2017 (15.9.28307.1216) found at: install node_modules/sharp node-gyp rebuild
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Windows\system32\node_modules\sharp\build\config.gypi
(node:37356) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp verb config.gypi checking for gypi file: C:\Windows\system32\node_modules\sharp\config.gypi
gyp verb common.gypi checking for gypi file: C:\Windows\system32\node_modules\sharp\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\doubleten\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\doubleten\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Windows\\system32\\node_modules\\sharp\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\doubleten\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\doubleten\\AppData\\Local\\node-gyp\\Cache\\16.14.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\doubleten\\AppData\\Local\\node-gyp\\Cache\\16.14.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\doubleten\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\doubleten\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.14.2\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Windows\\system32\\node_modules\\sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Windows\\system32\\node_modules\\sharp\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []ify:sharp: info run sharp@0.30.4 install node_modules/sharp node-gyp rebuild
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\doubleten\AppData\Local\node-gyp\Cache\16.14.2
gyp verb found first Solution file build/binding.sln
gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/nologo',
 info spawn args   '/p:Configuration=Release;Platform=x64'.4 install node_modules/sharp node-gyp rebuild
gyp info spawn args ]
MSBUILD : error MSB1009: 项目文件不存在。run sharp@0.30.4 install node_modules/sharp node-gyp rebuild
开关:build/binding.sln
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\doubleten\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\doubleten\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Windows\system32\node_modules\sharp
gyp ERR! node -v v16.14.2
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
npm info run sharp@0.30.4 install { code: 1, signal: null }
npm timing reify:rollback:createSparse Completed in 194ms
npm timing reify:rollback:retireShallow Completed in 0ms
npm timing command:install Completed in 6618ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (C:\Users\doubleten\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
npm verb stack     at ChildProcess.emit (node:events:526:28)
npm verb stack     at maybeClose (node:internal/child_process:1092:16)
npm verb stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm verb pkgid sharp@0.30.4
npm verb cwd C:\Windows\system32
npm verb Windows_NT 10.0.19041
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\doubleten\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose" "--foreground-scripts" "sharp"
npm verb node v16.14.2
npm verb npm  v7.9.0
npm ERR! code 1
npm ERR! path C:\Windows\system32\node_modules\sharp
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm verb exit 1
npm timing npm Completed in 7189ms
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\doubleten\AppData\Local\npm-cache\_logs\2022-04-23T15_45_53_065Z-debug.log

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

![image](https://user-images.githubusercontent.com/1480587/164934561-ebd8a977-c8a8-41f5-bf0f-32cbdfa49ea1.png)

![image](https://user-images.githubusercontent.com/1480587/164913267-10c83cbe-b4f9-4503-b168-9b90eb91603c.png)

### Do I need to run node-gyp rebuild separately? The result is as follows

![QQ截图20220423235756](https://user-images.githubusercontent.com/1480587/164913669-bd6a7534-bd1d-4583-8d91-91772326e6b9.png)

**Comment by iori2882** [comment]
Which version of node-gyp does sharp0.30 support?

**Comment by lovell** [comment]
It looks like you've run into a known bug in npm - please see https://github.com/npm/cli/issues/2606#issuecomment-924307833

**Comment by iori2882** [comment]
> It looks like you've run into a known bug in npm - please see [npm/cli#2606 (comment)](https://github.com/npm/cli/issues/2606#issuecomment-924307833)

npm still hasn't solved this bug, I can only choose to wait for npm to fix the bug or lower the version of node and npm before I can continue to use sharp? after all sharp is the best image processing framework for node, I am reluctant to give it up

**Comment by lovell** [comment]
Did you try `npx fix-has-install-script`? Perhaps also try upgrading to the latest version of npm and recreate your lockfile.

**Comment by metawrap-dev** [comment]
I am having the same issue. See. https://github.com/nuxt/nuxtjs.org/issues/2067#issuecomment-1110006523

**Comment by lovell** [comment]
@metawrap-dev Please can you open [a new installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) and answer all of the questions to make sure there's nothing else that might be causing this.

**Comment by Isaac-web** [comment]
I upgraded to the latest version of sharp ad the error is gone. You may try it.

**Comment by metawrap-dev** [comment]
The cause of the issue for me was having a `:` character in the file path. Looks like something deep in the toolchain is not escaping/unescaping properly.

**Comment by iori2882** [comment]
> @metawrap-dev Please can you open [a new installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) and answer all of the questions to make sure there's nothing else that might be causing this.



> I upgraded to the latest version of sharp ad the error is gone. You may try it.

是的,node16默认npm版本为8.5,当我升级npm版本为8.7的时候,sharp可以正常安装了.node-gyp的版本为6.10.十分感谢你们的帮助
