### ISSUE TITLE
DOCS: Unclear how to output buffer in explicitly set format

### ISSUE THREAD

**Issue by SuperCuber** [lovell/sharp#3204]
### What are you trying to achieve?

I want to take an image buffer in one format and produce a buffer in another format

### When you searched for similar issues, what did you find that might be related?

I searched for `toBuffer` and `format` and didn't see anything related

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```js
var input = new Buffer.from(...);
var output = await sharp(img).toBuffer(???);
```

After a lot of searching google I found `toFormat()` but this wasn't mentioned in the docs - it would be great if it was mentioned in toBuffer as the `options` object is where I would look for this, and the only mention of formats is `If no explicit format is set, the output format will match the input image, except SVG input which becomes PNG output.` with no mention of how to set format explicitly

**Comment by lovell** [comment]
Thanks, good idea, I've added more info via commit https://github.com/lovell/sharp/commit/58c2af3251b984e801a37d42a3f82fd80935bfb7
