### ISSUE TITLE
Contrast of text on backgrounds when using .resize()

### ISSUE THREAD

**Issue by albytomasiak** [lovell/sharp#3205]
Hey all, first of all, thank you for the continued support and work on Sharp! 

I have a question relating to text on images. We've stumbled on a compression issue when resizing large images to smaller variants. Mainly the text get's a decrease in quality. 

Below you can find the original and the resized variant (from 2500x1661 to 1440xAUTO).

The settings we currently have (and we've tried many different variants, but to no avail):
```
return image
    .png({
      quality: 100,
      force: false,
      effort: 10,
      adaptiveFiltering: true,
      progressive: true,
      palette: true,
      compressionLevel: 9
    })
    .resize({
      width: width,
      height: height,
      fit: 'cover',
      fastShrinkOnLoad: false,
    })
    .rotate()
    .toBuffer();
});
```

I tried playing with all of the png options, tried JPEG, webp, all the available kernels, you name it. 

The original image is:
![voor-albert](https://user-images.githubusercontent.com/103669879/165117031-1f0ad9f4-2997-4e87-96b8-58ceefe4a756.jpg)

The resized 1440xAUTO is:
![voor-albert (1)](https://user-images.githubusercontent.com/103669879/165117155-bc868db0-ef3e-469e-8533-cf993c031ba2.jpg)

The main issue we have is with the white text on the red background. 

Any tips/help on what settings we should play with to get that part crisp would be hugely appreciated!

**Comment by lovell** [comment]
The sample code provided suggests you're using PNG output but the sample output image provided is a JPEG.

https://graphicdesign.stackexchange.com/questions/21204/why-do-jpeg-files-blur-red-more-than-other-colors

Setting `chromaSubsampling` to `4:4:4` and increasing the `quality` usually helps with such images.

https://sharp.pixelplumbing.com/api-output#jpeg

**Comment by albytomasiak** [comment]
Nevermind! Just tested it with png's and the quality is much better indeed. I'll contact the responsible division and ask if they can export the images to png. 

Thanks for your help @lovell
