### ISSUE TITLE
SAM aws lambda local invocation of sharp gives architecture error after installing correct architecture flag.

### ISSUE THREAD

**Issue by anderskitson** [lovell/sharp#3207]
## Possible install-time or require-time problem

- [ x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [ x] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

- [x ] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Is this a problem with filesystem permissions?

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7 or later, does the user running `npm install` own the directory it is run in?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

➜  hello-world git:(feature/AWV-168) ✗ npm install --verbose --foreground-scripts sharp
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/Users/anderskitson/.nvm/versions/node/v14.17.6/bin/node',
npm verb cli   '/Users/anderskitson/.nvm/versions/node/v14.17.6/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   '--foreground-scripts',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@6.14.15
npm info using node@v14.17.6
npm verb npm-session 0cfc60bdc28b451d
npm http fetch GET 200 https://registry.npmjs.org/sharp 315ms
npm timing stage:loadCurrentTree Completed in 574ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 2ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 192ms
npm http fetch GET 304 https://registry.npmjs.org/color 65ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/semver 130ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-addon-api 141ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-get 147ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/prebuild-install 178ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/detect-libc 201ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tunnel-agent 1174ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-fs 1177ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-string 61ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-swizzle 58ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-arrayish 50ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mkdirp-classic 70ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/npmlog 73ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/rc 74ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minimist 77ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-abi 98ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/github-from-package 100ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/expand-template 102ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/napi-build-utils 114ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/pump 119ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lru-cache 59ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/yallist 51ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/are-we-there-yet 50ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/gauge 54ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/set-blocking 58ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/console-control-strings 59ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/delegates 50ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/readable-stream 56ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/isarray 79ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/string_decoder 96ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/process-nextick-args 98ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/core-util-is 100ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/util-deprecate 101ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/signal-exit 73ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/string-width 77ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/has-unicode 78ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/aproba 84ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/object-assign 84ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/strip-ansi 83ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/wide-align 83ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/code-point-at 53ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-fullwidth-code-point 56ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/number-is-nan 44ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ansi-regex 61ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/end-of-stream 51ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/strip-json-comments 43ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ini 55ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/deep-extend 64ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 57ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-concat 67ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mimic-response 51ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-stream 55ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/chownr 60ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bl 58ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-constants 63ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/buffer 46ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/base64-js 45ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ieee754 60ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 2678ms
npm timing stage:loadIdealTree Completed in 2922ms
npm timing stage:generateActionsToTake Completed in 13ms
npm verb correctMkdir /Users/anderskitson/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/anderskitson/.npm/_locks/staging-240c96172a952028.lock for /Users/anderskitson/acorn/acorn-cloud-functions/image-resizing-lambda-js/hello-world/node_modules/.staging
npm timing action:extract Completed in 32ms
npm info lifecycle sharp@0.30.4~preuninstall: sharp@0.30.4
npm info lifecycle sharp@0.30.4~uninstall: sharp@0.30.4
npm verb unbuild rmStuff sharp@0.30.4 from /Users/anderskitson/acorn/acorn-cloud-functions/image-resizing-lambda-js/hello-world/node_modules
npm info lifecycle sharp@0.30.4~postuninstall: sharp@0.30.4
npm timing action:unbuild Completed in 3ms
npm timing action:remove Completed in 13ms
npm timing action:finalize Completed in 2ms
npm timing action:refresh-package-json Completed in 8ms
npm info lifecycle sharp@0.30.4~preinstall: sharp@0.30.4
npm timing action:preinstall Completed in 1ms
npm info linkStuff sharp@0.30.4
npm timing action:build Completed in 1ms
npm info lifecycle sharp@0.30.4~install: sharp@0.30.4

> sharp@0.30.4 install /Users/anderskitson/acorn/acorn-cloud-functions/image-resizing-lambda-js/hello-world/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Using cached /Users/anderskitson/.npm/_libvips/libvips-8.12.2-darwin-x64.tar.br
sharp: Integrity check passed for darwin-x64
prebuild-install info begin Prebuild-install version 7.1.0
prebuild-install info looking for local prebuild @ prebuilds/sharp-v0.30.4-napi-v5-darwin-x64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/anderskitson/.npm/_prebuilds/7c6a98-sharp-v0.30.4-napi-v5-darwin-x64.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /Users/anderskitson/.npm/_prebuilds/7c6a98-sharp-v0.30.4-napi-v5-darwin-x64.tar.gz
prebuild-install info unpack resolved to /Users/anderskitson/acorn/acorn-cloud-functions/image-resizing-lambda-js/hello-world/node_modules/sharp/build/Release/sharp-darwin-x64.node
prebuild-install info install Successfully installed prebuilt binary!
npm verb lifecycle sharp@0.30.4~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.30.4~install: PATH: /Users/anderskitson/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/anderskitson/acorn/acorn-cloud-functions/image-resizing-lambda-js/hello-world/node_modules/sharp/node_modules/.bin:/Users/anderskitson/acorn/acorn-cloud-functions/image-resizing-lambda-js/hello-world/node_modules/.bin:/Users/anderskitson/.autojump/bin:/Users/anderskitson/.nvm/versions/node/v14.17.6/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/anderskitson/.fig/bin:/Users/anderskitson/.local/bin:/Users/anderskitson
npm verb lifecycle sharp@0.30.4~install: CWD: /Users/anderskitson/acorn/acorn-cloud-functions/image-resizing-lambda-js/hello-world/node_modules/sharp
npm timing audit submit Completed in 93ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 97ms
npm timing audit body Completed in 4ms
npm timing action:install Completed in 591ms
npm info lifecycle sharp@0.30.4~postinstall: sharp@0.30.4
npm timing action:postinstall Completed in 0ms
npm verb unlock done using /Users/anderskitson/.npm/_locks/staging-240c96172a952028.lock for /Users/anderskitson/acorn/acorn-cloud-functions/image-resizing-lambda-js/hello-world/node_modules/.staging
npm timing stage:executeActions Completed in 666ms
npm timing stage:rollbackFailedOptional Completed in 0ms
npm timing stage:runTopLevelLifecycles Completed in 4202ms
npm verb saving [ { name: 'sharp', spec: '^0.30.4', save: 'dependencies' } ]
npm verb shrinkwrap skipping write for package.json because there were no changes.
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle hello_world@1.0.0~shrinkwrap: hello_world@1.0.0
npm verb shrinkwrap skipping write for package-lock.json because there were no changes.
npm info lifecycle hello_world@1.0.0~postshrinkwrap: hello_world@1.0.0
+ sharp@0.30.4
updated 1 package and audited 160 packages in 4.244s

21 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm verb exit [ 0, true ]
npm timing npm Completed in 4496ms
npm info ok 

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

 System:
    OS: macOS 11.2.3
    CPU: (8) x64 Apple M1
    Memory: 207.29 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.17.6/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
  npmPackages:
    sharp: ^0.30.4 => 0.30.4 

Other Details

I am using SAM (serverless application model) I just setup a brand new node js 14 hello world example. I installed sharp with x86 architecture flag 

`npm install --platform=linux --arch=x64 --verbose sharp`

I get the following from that output

```
➜  hello-world git:(feature/AWV-168) ✗ npm install --platform=linux --arch=x64 --verbose sharp                      
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/Users/anderskitson/.nvm/versions/node/v14.17.6/bin/node',
npm verb cli   '/Users/anderskitson/.nvm/versions/node/v14.17.6/bin/npm',
npm verb cli   'install',
npm verb cli   '--platform=linux',
npm verb cli   '--arch=x64',
npm verb cli   '--verbose',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@6.14.15
npm info using node@v14.17.6
npm verb npm-session cef7a8083f2d0193
npm http fetch GET 200 https://registry.npmjs.org/sharp 12ms (from cache)
npm timing stage:loadCurrentTree Completed in 248ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 257ms
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 41ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/node-addon-api 41ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/prebuild-install 41ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/tar-fs 40ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/semver 214ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-get 218ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tunnel-agent 221ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color 244ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-string 156ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-swizzle 54ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 2ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/expand-template 14ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/node-abi 13ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/pump 13ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/mkdirp-classic 14ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/github-from-package 15ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/napi-build-utils 14ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minimist 52ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/rc 60ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/npmlog 69ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lru-cache 47ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/yallist 2ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/console-control-strings 8ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/set-blocking 8ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/are-we-there-yet 56ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/gauge 67ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/delegates 3ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/readable-stream 4ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/core-util-is 7ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/string_decoder 7ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/process-nextick-args 66ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/isarray 69ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/util-deprecate 69ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/has-unicode 8ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/signal-exit 9ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/wide-align 8ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/strip-ansi 9ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/aproba 63ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/object-assign 69ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/string-width 82ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/code-point-at 4ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-fullwidth-code-point 58ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/number-is-nan 2ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/ansi-regex 2ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/end-of-stream 2ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/deep-extend 61ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ini 70ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/strip-json-comments 74ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/simple-concat 5ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 54ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/mimic-response 1ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/chownr 2ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/tar-stream 3ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/fs-constants 9ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bl 55ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/buffer 6ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/base64-js 2ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ieee754 44ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 1261ms
npm timing stage:loadIdealTree Completed in 1570ms
npm timing stage:generateActionsToTake Completed in 13ms
npm verb correctMkdir /Users/anderskitson/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/anderskitson/.npm/_locks/staging-240c96172a952028.lock for /Users/anderskitson/acorn/acorn-cloud-functions/image-resizing-lambda-js/hello-world/node_modules/.staging
npm timing action:extract Completed in 31ms
npm info lifecycle sharp@0.30.4~preuninstall: sharp@0.30.4
npm info lifecycle sharp@0.30.4~uninstall: sharp@0.30.4
npm verb unbuild rmStuff sharp@0.30.4 from /Users/anderskitson/acorn/acorn-cloud-functions/image-resizing-lambda-js/hello-world/node_modules
npm info lifecycle sharp@0.30.4~postuninstall: sharp@0.30.4
npm timing action:unbuild Completed in 2ms
npm timing action:remove Completed in 14ms
npm timing action:finalize Completed in 2ms
npm timing action:refresh-package-json Completed in 8ms
npm info lifecycle sharp@0.30.4~preinstall: sharp@0.30.4
npm timing action:preinstall Completed in 1ms
npm info linkStuff sharp@0.30.4
npm timing action:build Completed in 0ms
npm info lifecycle sharp@0.30.4~install: sharp@0.30.4

> sharp@0.30.4 install /Users/anderskitson/acorn/acorn-cloud-functions/image-resizing-lambda-js/hello-world/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Using cached /Users/anderskitson/.npm/_libvips/libvips-8.12.2-linux-x64.tar.br
sharp: Integrity check passed for linux-x64
prebuild-install info begin Prebuild-install version 7.1.0
prebuild-install info looking for local prebuild @ prebuilds/sharp-v0.30.4-napi-v5-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/anderskitson/.npm/_prebuilds/da932c-sharp-v0.30.4-napi-v5-linux-x64.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /Users/anderskitson/.npm/_prebuilds/da932c-sharp-v0.30.4-napi-v5-linux-x64.tar.gz
prebuild-install info unpack resolved to /Users/anderskitson/acorn/acorn-cloud-functions/image-resizing-lambda-js/hello-world/node_modules/sharp/build/Release/sharp-linux-x64.node
prebuild-install info install Successfully installed prebuilt binary!
npm verb lifecycle sharp@0.30.4~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.30.4~install: PATH: /Users/anderskitson/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/anderskitson/acorn/acorn-cloud-functions/image-resizing-lambda-js/hello-world/node_modules/sharp/node_modules/.bin:/Users/anderskitson/acorn/acorn-cloud-functions/image-resizing-lambda-js/hello-world/node_modules/.bin:/Users/anderskitson/.autojump/bin:/Users/anderskitson/.nvm/versions/node/v14.17.6/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/anderskitson/.fig/bin:/Users/anderskitson/.local/bin:/Users/anderskitson
npm verb lifecycle sharp@0.30.4~install: CWD: /Users/anderskitson/acorn/acorn-cloud-functions/image-resizing-lambda-js/hello-world/node_modules/sharp
npm timing audit submit Completed in 119ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 118ms
npm timing audit body Completed in 0ms
npm timing action:install Completed in 622ms
npm info lifecycle sharp@0.30.4~postinstall: sharp@0.30.4
npm timing action:postinstall Completed in 1ms
npm verb unlock done using /Users/anderskitson/.npm/_locks/staging-240c96172a952028.lock for /Users/anderskitson/acorn/acorn-cloud-functions/image-resizing-lambda-js/hello-world/node_modules/.staging
npm timing stage:executeActions Completed in 696ms
npm timing stage:rollbackFailedOptional Completed in 0ms
npm timing stage:runTopLevelLifecycles Completed in 2560ms
npm verb saving [ { name: 'sharp', spec: '^0.30.4', save: 'dependencies' } ]
npm verb shrinkwrap skipping write for package.json because there were no changes.
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle hello_world@1.0.0~shrinkwrap: hello_world@1.0.0
npm verb shrinkwrap skipping write for package-lock.json because there were no changes.
npm info lifecycle hello_world@1.0.0~postshrinkwrap: hello_world@1.0.0
+ sharp@0.30.4
updated 1 package and audited 160 packages in 2.605s

21 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm verb exit [ 0, true ]
npm timing npm Completed in 2865ms
npm info ok 
```

When I build the project with `sam build` 

it runs the following fine

```
runtime: nodejs14.x metadata: {} architecture: x86_64 functions: ['HelloWorldFunction']
Running NodejsNpmBuilder:NpmPack
Running NodejsNpmBuilder:CopyNpmrcAndLockfile
Running NodejsNpmBuilder:CopySource
Running NodejsNpmBuilder:NpmInstall
Running NodejsNpmBuilder:CleanUpNpmrc
Running NodejsNpmBuilder:LockfileCleanUp
```

I run sam local start-api to initiate a docker container that creates an endpoint I can hit at localhost:3000

My app code looks like the following

```
// const axios = require('axios')
// const url = 'http://checkip.amazonaws.com/';
const sharp = require("sharp");
let response;

/**
 *
 * Event doc: https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format
 * @param {Object} event - API Gateway Lambda Proxy Input Format
 *
 * Context doc: https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html
 * @param {Object} context
 *
 * Return doc: https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html
 * @returns {Object} object - API Gateway Lambda Proxy Output Format
 *
 */
exports.lambdaHandler = async (event, context) => {
  try {
    // const ret = await axios(url);
    const parsedBody = JSON.parse(event.body);
    response = {
      statusCode: 200,
      body: JSON.stringify({
        message: parsedBody.imagePath,
        // location: ret.data.trim()
      }),
    };

    sharp("https://miro.medium.com/max/512/1*V395S0MUwmZo8dX2aezpMg.png")
      .resize({ width: 100 })
      .toBuffer()
      .then((data) => {
        // 100 pixels wide, auto-scaled height
        console.log("sharp data", data);
      });
  } catch (err) {
    console.log(err);
    return err;
  }

  return response;
};
```

I run a curl command to the endpoint locally

```
curl --request POST \
  --url http://127.0.0.1:3000/hello \
  --header 'Content-Type: application/json' \
  --data '{
	"imagePath": "https://miro.medium.com/max/512/1*V395S0MUwmZo8dX2aezpMg.png"
}'
```

and the logs inform me that I don't have the right arcitecture

```
Something went wrong installing the \"sharp\" module\n\nCannot find module '../build/Release/sharp-linux-x64.node'\nRequire stack:\n- /var/task/node_modules/sharp/lib/sharp.js\n- /var/task/node_modules/sharp/lib/constructor.js\n- /var/task/node_modules/sharp/lib/index.js\n- /var/task/app.js\n- /var/runtime/UserFunction.js\n- /var/runtime/Runtime.js\n- /var/runtime/index.js\n\nPossible solutions:\n- Install with the --verbose flag and look for errors: \"npm install --ignore-scripts=false --verbose sharp\"\n- Install for the current linux-x64 runtime: \"npm install --platform=linux --arch=x64 sharp\"\n- Consult the installation documentation: https://sharp.pixelplumbing.com/install"
```

pointing me back to the command I already ran 
`npm install --platform=linux --arch=x64 sharp`

My SAM Architecure for the lambda is

```
Architectures:
        - x86_64
```

Any help would be greatly appreciated. Thank you

**Comment by lovell** [comment]
Here's the line from the installation log where the `sharp-linux-x64.node` file is unpacked:

> prebuild-install info unpack resolved to /Users/anderskitson/acorn/acorn-cloud-functions/image-resizing-lambda-js/hello-world/node_modules/sharp/build/Release/sharp-linux-x64.node

If the above is correct, and you're seeing the error "Cannot find module '../build/Release/sharp-linux-x64.node'", then my best guess would be something else is going wrong somewhere between installation and deployment, perhaps a packaging related problem in configuration not shown here. For example, are all the relevant files still present after `sam build` has run?

**Comment by anderskitson** [comment]
Are all the relevant files still present after sam build has run? I am not entirely sure what you mean by that. 

Inside the build `.aws-sam` directory there is a `build` directory containing the `HelloWorldFunction` which contains `node_modules` with the following tree. This `.aws-sam` directory gets built on `sam build`

```
├── LICENSE
├── README.md
├── binding.gyp
├── build
│   └── Release
│       └── sharp-darwin-x64.node
├── install
│   ├── can-compile.js
│   ├── dll-copy.js
│   └── libvips.js
├── lib
│   ├── agent.js
│   ├── channel.js
│   ├── colour.js
│   ├── composite.js
│   ├── constructor.js
│   ├── index.js
│   ├── input.js
│   ├── is.js
│   ├── libvips.js
│   ├── operation.js
│   ├── output.js
│   ├── platform.js
│   ├── resize.js
│   ├── sharp.js
│   └── utility.js
├── package.json
├── src
│   ├── common.cc
│   ├── common.h
│   ├── libvips
│   │   └── cplusplus
│   │       ├── VConnection.cpp
│   │       ├── VError.cpp
│   │       ├── VImage.cpp
│   │       ├── VInterpolate.cpp
│   │       └── vips-operators.cpp
│   ├── metadata.cc
│   ├── metadata.h
│   ├── operations.cc
│   ├── operations.h
│   ├── pipeline.cc
│   ├── pipeline.h
│   ├── sharp.cc
│   ├── stats.cc
│   ├── stats.h
│   ├── utilities.cc
│   └── utilities.h
└── vendor
    └── 8.12.2
        └── darwin-x64
            ├── THIRD-PARTY-NOTICES.md
            ├── lib
            │   ├── glib-2.0
            │   └── libvips-cpp.42.dylib
            ├── platform.json
            └── versions.json
```

Or where am I to look for these `relevant files`?

**Comment by lovell** [comment]
Thanks, this suggests `sam build` is installing binaries for the current runtime rather than the Lambda runtime.

Did you see the `--use-container` option of `sam build`?

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html

**Comment by anderskitson** [comment]
I hadn't seen that. I have tried just now to use that flag, and it seems to just hang at the `Fetching public.ecr.aws/sam/build-nodejs14.x:latest-x86_64 Docker container image` part it's been running that for at least 10 mins. I tried to abort and try again, but it just seems to hang. Not sure if that is more a SAM question at this point.

**Comment by anderskitson** [comment]
Actually it did build it just took a while

So I think it installed correctly this time and is working, I am getting an error but I think it is a implementation issue on my part I get this error

```
ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: Input file is missing: https://miro.medium.com/max/512/1*V395S0MUwmZo8dX2aezpMg.png","reason":{"errorType":"Error","errorMessage":"Input file is missing: https://miro.medium.com/max/512/1*V395S0MUwmZo8dX2aezpMg.png","stack":["Error: Input file is missing: https://miro.medium.com/max/512/1*V395S0MUwmZo8dX2aezpMg.png"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: Input file is missing: https://miro.medium.com/max/512/1*V395S0MUwmZo8dX2aezpMg.png","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:400:28)","    at processPromiseRejections (internal/process/promises.js:245:33)","    at processTicksAndRejections (internal/process/task_queues.js:96:32)"]}
```

with this code 

```
try {
    // const ret = await axios(url);
    const parsedBody = JSON.parse(event.body);
    response = {
      statusCode: 200,
      body: JSON.stringify({
        message: parsedBody.imagePath,
        // location: ret.data.trim()
      }),
    };

    sharp("https://miro.medium.com/max/512/1*V395S0MUwmZo8dX2aezpMg.png")
      .resize({ width: 100 })
      .toBuffer()
      .then((data) => {
        // 100 pixels wide, auto-scaled height
        console.log("sharp data", data);
      });
  } catch (err) {
    console.log(err);
    return err;
  }
  ```
  
  I am not 100% sure but I think the error is from sharp and it is being caught in the try catch, maybe I am wrong. If you have any idea based on this code what might be wrong let me know, otherwise I will keep hacking away thanks

**Comment by anderskitson** [comment]
Should have read the docs that were outline so well.

It is working now with the following

```
const url = "https://miro.medium.com/max/512/1*V395S0MUwmZo8dX2aezpMg.png";

    //* gets the image from url in the arraybuffer
    const responseA = await axios.get(url, {
      responseType: "arraybuffer",
    });

    const buffer = Buffer.from(responseA.data, "base64");

    await sharp(buffer)
      .resize({ width: 100 })
      .toBuffer()
      .then((data) => {
        // 100 pixels wide, auto-scaled height
        console.log("sharp data", data);
      });
```

Could I ask why you think the `--use-container` flag fixes things, just curious. Thx!

**Comment by lovell** [comment]
Glad you got it working.

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html says:

> `--use-container` If your functions depend on packages that have natively compiled dependencies, use this option to build your function inside a Lambda-like Docker container.

An alternative approach might be to set the `npm_config_platform=linux` and `npm_config_arch=x64` environment variables before calling `sam build`.

https://sharp.pixelplumbing.com/install#cross-platform

If this works, it would probably make a good improvement to `sam` for these to be set internally automagically - perhaps you could suggest this to AWS?
