### ISSUE TITLE
I can't catch “too large” Error

### ISSUE THREAD

**Issue by MineYuanlu** [lovell/sharp#3210]
## Question about an existing feature
I tried to upload a 13680 * 18240 JPG image from the client. The size is about 20MB. I didn't make any additional size restrictions. I chose to keep the default value of Sharp's "limitinputpixels", but I encountered an error that I couldn't capture:
```
node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: Processed image is too large for the WebP format]
```
This error directly ends my server. This is very bad

### What are you trying to achieve?

Do I need to do some additional size restrictions? If restrictions are needed, how many pixels should I limit to?
Or is there a way for me to catch this error and return a bad request to the client instead of ending the process directly?

### When you searched for similar issues, what did you find that might be related?

From the perspective of error reporting, it should be an error caused by sharp calling other threads. This error cannot be caught by try catch

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question
My code like this:
```typescript
const buf=Buffer.from(clientData);
const data=sharp(buf,{sequentialRead: true}).webp();
data.toFile(file+".raw.webp");
data.resize(200).toFile(file+".small.webp");
```

### Please provide sample image(s) that help explain this question

![图片](https://user-images.githubusercontent.com/38997444/166407859-90d8458f-a360-47d7-a250-35ddaedd7085.png)
![图片](https://user-images.githubusercontent.com/38997444/166407871-8fd4582f-d3fb-4be0-8a92-af58b0719ba4.png)

**Comment by MineYuanlu** [comment]
Similarly, I encountered this problem:
```
node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: Input buffer contains unsupported image format]
```
I uploaded a non picture file, which caused this error. How can I judge whether the data is a picture? If this error could be caught, it would be much easier.

**Comment by lovell** [comment]
Did you see the documentation for `toFile()`?

https://sharp.pixelplumbing.com/api-output#tofile

You'll need to add some error handling, either a callback or a Promise chain or (if using within an `async` function) a try/catch block.

```js
.toFile(file+".small.webp", (err, info) => { if (err) ... })
```
```js
.toFile(file+".small.webp").catch(err => { ... })
```

WebP images can have dimensions up to 16383x16383 pixels.

https://developers.google.com/speed/webp/faq#what_is_the_maximum_size_a_webp_image_can_be

**Comment by MineYuanlu** [comment]
oh Sorry, I thought it was an error that would be thrown during creation. I only catch `sharp(buf,{sequentialRead: true}).webp()` before this
