### ISSUE TITLE
Resize pipe doesn't resize the image

### ISSUE THREAD

**Issue by DavidTanner** [lovell/sharp#3212]
### What are the steps to reproduce?

I'm following the example from the website on how to resize an image stream.  There is only one example of resize with a pipe.

https://sharp.pixelplumbing.com/api-resize

```javascript
// Minimized to reflect the unit test I copied.
const transformer = sharp()
  .resize(320);
readableStream
  .pipe(transformer)
  .pipe(writableStream);
```

### What is the expected behaviour?

The file should be resized.

[I created a unit test here that shows what I am seeing.](https://github.com/DavidTanner/sharp/commit/73f8eff9d5ca291abfc16ffc2ab8c4a160ccfa66)

**Comment by lovell** [comment]
The use of `input.pipe(output)` line in your `promisifiedPipe()` function is removing the sharp instance from the pipeline.

Were you aware of the `stream.pipeline()` function available in Node.js?

https://nodejs.org/api/stream.html#streampipelinestreams-callback

```js
const { pipeline } = require('node:stream/promises');
...
await pipeline(inStream, transformer, outStream);
```

In addition, `sharp(input).metadata()` already returns a Promise, so you can replace your `getMetadata()` function with something like the following.

```diff
- const info = await getMetadata(outFile);
+ const info = await sharp(outFile).metadata();
```

**Comment by DavidTanner** [comment]
Hey @lovell Thank you for responding so fast!  I figured there was something I wasn't doing correclty.  I was able to get it working with the following two examples.

This is for 12, 14
```javascript
const stream = require('stream');
const util = require('util');
const pipeline = util.promisify(stream.pipeline);

const transformer = sharp().resize(320);
await pipeline(inStream, transformer, outStream);
```

And in node 16+
```javascript 
const { promises: stream } = require('stream')


const transformer = sharp().resize(320);
await stream.pipeline(inStream, transformer, outStream);
```
