### ISSUE TITLE
Error : Image to composite must have same dimensions or smaller

### ISSUE THREAD

**Issue by reptincel-cpu** [lovell/sharp#3213]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [ x] Running `npm install sharp` completes without error.
- [ x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x ] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

  System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 7.02 GB / 15.82 GB
  Binaries:
    Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: ^0.30.4 => 0.30.4

### Explanation of the issue

I'm trying to composite a .gif animated image w/ animated layers. However, when I add the 'animated: true' parameter to the layers to be composed, I get the following error: 

`Image to composite must have same dimensions or smaller`

When I do not set the animated parameter to true the image is static and does not animate. 
The background and the body are non-animated .gif images, the rest (the composite layers) are supposed to be animated.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

` let overlay = `
         
        [
            {
                input : body,
                tile: true,
                animated : true,
            },

            {
                input: mouth,
                tile : true,
                animated : true
            },

            {
                input : eyes,
                tile : true,
                animated : true
            }
        ];

        let img = await sharp(background).toBuffer();
        img = await sharp(img).composite(overlay).toBuffer();
        /// img = await sharp(img).resize(1000, 1000).toBuffer();

        await sharp(img).gif()
            .toFile('animate_output/' + id + '.gif',  (err) => {
                if (err === null) {
                    console.log("IMAGE n°" + id + "done");
                } else {
                    console.log("ERR: ", err)
                }
            });

**Comment by lovell** [comment]
Please can you provide all of the sample input images required to reproduce.

**Comment by reptincel-cpu** [comment]
Hello, thanks for your reply, here the image : 

![background](https://user-images.githubusercontent.com/79871873/166560014-b6491a4b-c627-41a2-904e-5499e528082d.gif)
![body](https://user-images.githubusercontent.com/79871873/166560016-f7005d2a-0912-4b61-81a6-f280c026b874.gif)
![eyes](https://user-images.githubusercontent.com/79871873/166560017-2900c61d-a611-4f41-9a24-a465b49bb6eb.gif)
![mouth](https://user-images.githubusercontent.com/79871873/166560018-59790343-9fd4-435a-ae78-9b6a1fca904c.gif)

**Comment by EtDu** [comment]
Experiencing the same issue. All the files are absolutely the same size

**Comment by EtDu** [comment]
```
traitBuffers.push({
        input: buf,
        tile: isGif ? false : true,
        gravity: 'northwest',
        animated: isGif ? true : false,
        limitInputPixels: 2684026890
      })

let composite = traitBuffers.shift()

finalImage = sharp(composite.input, {
        animated: true,
        limitInputPixels: 2684026890,
      }).composite(traitBuffers).gif({ effort: 1 }).toBuffer()
```

**Comment by lovell** [comment]
The input image (`background` in this case) needs to have at least the same height as the combined height of all the frames. As it appears to be a solid colour, you could create a new, blank image as the input canvas, something like:

```js
sharp({
  create: {
    width: 1000,
    height: 1000 * frameCount,
    channels: 4,
    background: '#0000ff'
  }
})...
```

**Comment by reptincel-cpu** [comment]
Thank you very much 🙏

**Comment by reptincel-cpu** [comment]
Not working ... when I remove {animated : true} the composition works with exactly same parameters. But when I add it, there is the dimension error

**Comment by EtDu** [comment]
don't remove `animated:true`

I've found this code to work:
```
const { width, height} = imgMetadata[0]
          const totalPagesGif = imgMetadata
          .map(x => x.pages)
          .filter(x => typeof x === "number")
          .reduce((partialSum, a) => partialSum + a, 0)

          finalImage = sharp(
            {
              create: {
                width: width,
                height: height * totalPagesGif,
                channels: 4,
                background: '#0000ff'
              },
              animated: true,
              limitInputPixels: 2684026890,
            }
          )
          .composite(traitBuffers)
          .gif({ effort: 1 })
```

**Comment by EtDu** [comment]
basically just taking the sum of total gif frames in the composition and multiplying by the height in `create`

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
