### ISSUE TITLE
How text draw by svg automatic enter new line when full width

### ISSUE THREAD

**Issue by hieuntcasso** [lovell/sharp#3215]
This is my code to drawing the text 
`
 const svgImage = "
        <svg width="${data.width}" height="${data.height}">
          <style>
          .title { fill: ${data.color || "black"}; font-size: ${data.fontSize || "10px"}}
          </style>
          <text x="0" y="${data.fontSize || 10}}" text-anchor="start" class="title">${data.text}</text>
        </svg>
        "
`
Issue is if data.text too long , it will be disappear , not enter the new line.
How can i do it?
Ex: data.text = '123456789'
it only show '12345' . I would like the rest text will be entered new line.

**Comment by lovell** [comment]
Please see the future possible enhancement at #512
