### ISSUE TITLE
Error: Failed to download resource "libpng"

### ISSUE THREAD

**Issue by wenshan** [lovell/sharp#322]
==> Downloading https://dl.bintray.com/homebrew/mirror/libpng-1.6.18.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "libpng""

”https://dl.bintray.com/homebrew/mirror/libpng-1.6.18.tar.xz“ The libpng-1.6.18.tar.xz does not exist, please update the new installation package.

**Comment by lovell** [comment]
Hello, this looks like a homebrew problem. Perhaps try `brew update` first.

**Comment by wenshan** [comment]
Thank you, the problem is solved, the problem is Homebrew, new installation problem is solved.
