### ISSUE TITLE
Problem with resize heic image with width >~ 400

### ISSUE THREAD

**Issue by dogrocker** [lovell/sharp#3224]
## Question about an existing feature

When resize width is more than `400` or `Math.round(width / 2)` the image is not correct.

### What are you trying to achieve?

I try to resize heic image and save to same format with libsvips, libx265, libde265 in lambda.

### When you searched for similar issues, what did you find that might be related?

I'm search all issues seem like no answer for this.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

This is my code in lambda

```js
  const imageBuffer = await S3.get(file, bucket);

  const image = sharp(imageBuffer.Body);
  const { width, format, orientation } = await image.metadata();
  const outputBuffer = await image
          .resize({
            // width: Math.round(width / 3),
            width: 400,
            fit: sharp.fit.inside,
            // withoutEnlargement: true
          })
          .heif({ quality: 60, compression: 'hevc' })
          .toBuffer();

  let name = file.replace(/\.[^/.]+$/, '')
  let extension = file.split('.').pop()
  const newFileName = `${name}_thumb.${extension}`;
  await S3.write(outputBuffer, newFileName, bucket, imageBuffer.ContentType);
  return newFileName;
```

### Please provide sample image(s) that help explain this question

original
[sample1_original.heic.zip](https://github.com/lovell/sharp/files/8671019/sample1_original.heic.zip)

resized
[sample1_resized.heic.zip](https://github.com/lovell/sharp/files/8671018/sample1_resized.heic.zip)

**Comment by lovell** [comment]
The `resized` image you've provided seems OK to me. What do you mean by "the image is not correct"? Please provide a sample image that is not correct.

It looks like you're using a globally-installed version of libvips and its dependencies. Please provide versions numbers of all relevant dependencies, including libvips, libheif, libde265 and libx265.

Have you checked for possible bugs or yet-to-be-released fixes in the repos for these dependencies?

Have you been able to  use `heif-enc` at the command line to produce a valid HEIC output of the desired dimensions using the same versions of all dependencies?

**Comment by dogrocker** [comment]
@lovell This's image I mean. This is my makefile repo for create dependencies to lambda https://github.com/dogrocker/sharp-heic-lambda-layer/blob/main/layer/Makefile

<img width="2107" alt="Screen Shot 2565-05-11 at 23 05 23" src="https://user-images.githubusercontent.com/8379027/167896174-5597cea7-fd29-4ae0-842c-a21db4465e5b.png">

**Comment by lovell** [comment]
Are you sure this isn't a bug in the image viewer you're using?
```sh
$ curl -LsO https://github.com/lovell/sharp/files/8671018/sample1_resized.heic.zip
$ unzip sample1_resized.heic.zip 
Archive:  sample1_resized.heic.zip
  inflating: sample1_thumb.heic      
  inflating: __MACOSX/._sample1_thumb.heic  
$ heif-convert sample1_thumb.heic out.png
File contains 1 images
Written to out.png
```

![out](https://user-images.githubusercontent.com/210965/168013427-9169db82-3e0b-4eb6-9ca2-d6767e771f71.png)

**Comment by dogrocker** [comment]
@lovell Oh! not sure I'm using Preview app on mac. I will try another app.
