### ISSUE TITLE
Aborted when loading a specific png in ARM64 environments

### ISSUE THREAD

**Issue by tamaina** [lovell/sharp#3225]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (4) arm64 Neoverse-N1
    Memory: 20.15 GB / 23.31 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.1.0 - /usr/bin/node
    npm: 8.8.0 - /usr/bin/npm
  npmPackages:
    sharp: ^0.30.4 => 0.30.4 
```

(Oracle Cloud Infrastructure A1 instance)

### What are the steps to reproduce?
Download PixelFed's favicon.png: https://pixelfed.tokyo/img/favicon.png?v=2
![favicon](https://user-images.githubusercontent.com/7973572/168437391-12f574a4-ec1e-4a35-a532-ae47d84232a6.png)

Load...

```
await sharp('favicon.png').toBuffer();
```

It throws error.  
This error kills our software.

```
malloc(): corrupted top size
Aborted (core dumped)
```

### What is the expected behaviour?
No error and no killing

**Comment by tamaina** [comment]
Information:

It happens with sharp 0.30.0 or later.

Using libjemalloc2 resolves this bug but I hope it will work without any manipulation on our part.  
https://misskey.xianon.net/notes/8zrrs9qm9c

**Comment by lovell** [comment]
Thanks for reporting this, I'll try to reproduce on some ARM64 hardware when I can.

Please can you test the following code with the same image to help narrow down if this might be a decode or encode problem.
```js
await sharp('favicon.png').raw().toBuffer(); // decode only, no PNG encoding
```

sharp v0.29.x provides libspng v0.6.3 whereas sharp v.30.x provides libspng v0.7.1.

The sample input is palette-based, and when decoded on ARM64 will use libspng v0.7.1's NEON optimised path, which leads me to suspect this might relate to https://github.com/randy408/libspng/issues/189

**Comment by tamaina** [comment]
Thanks for your reply.  
It aborts as well in decode only.

![image](https://user-images.githubusercontent.com/7973572/168473333-7951f5c5-b6c8-4ca0-a2df-7c276e5dcacd.png)

**Comment by randy408** [comment]
> I think expand_palette_rgba8_neon also suffered from the same bug

This is confirmed to be the case. When the quickfix was released the root cause was not yet known, the image from the initial bug report did not trigger the same problem in the other function. It does with this new image.

The last release in February fixed both functions and also another issue that affected all platforms, so there was good reason to upgrade, even if it was assumed the quickfix introduced by v0.7.1 was complete.

**Comment by lovell** [comment]
Thanks all for confirming, the future v0.31.0 release of sharp will provide prebuilt binaries with a more recent version of libspng with the fix.

**Comment by maximeg** [comment]
In the meantime, pinning to `"sharp": "0.30.1"` in `resolutions` avoids the crash for me.

**Comment by ngladbach** [comment]
Same problem here on M1 Mac, fixing version to 0.29.3 helped. In my case it influences NextJS and the upload-plugin of Strapi.

**Comment by Lambdac0re** [comment]
Fixing version to 0.29.3 helps on aarch64 fedora

**Comment by oebilgen** [comment]
All versions above `0.28.3` crash on Windows 11, Intel i7-11800H with this error. Try/catch doesn't work; the error takes the node process down (not sure how?).

**Comment by lovell** [comment]
@oebilgen This issue relates only to ARM64. If you're seeing it on Intel hardware, please open a new issue and provide as much information as possible, including sample code with appropriate error handling, sample images, and ideally a backtrace of the crash.

**Comment by lovell** [comment]
v0.31.0 now available with prebuilt binaries that contain the upstream fix, thanks all for reporting/helping with this.
