### ISSUE TITLE
Tiled composition onto resized image using fit=outside fails

### ISSUE THREAD

**Issue by faradaytrs** [lovell/sharp#3227]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

Cannot provide output because it happens in AWS lambda environment with node16 runtime. 1024mb memory.

### What are the steps to reproduce?

I try to resize image and add watermark, watermark is resized before composing.

1. First resize first image with: { width: 5000, height: 250, withoutEnlargement: true, fit: 'outside' }'
fit=inside works fine.
2. Resize second image (watermark) with { height: 768 }
3. Compose them:
{
    input: await secondImage.toBuffer(),
    tile: true,
},
And then i have the following error:
(process:9): GLib-GObject-WARNING **: 03:40:16.528: value "0" of type 'gint' is invalid or out of range for property 'down' of type 'gint'
ERROR Invoke Error {"errorType":"Error","errorMessage":"replicate: parameter down not set\n","stack":["Error: replicate: parameter down not set",""]}

### What is the expected behaviour?

Expected to successfully generate image with watermark.

### Please provide sample image(s) that help explain this problem

[first image](https://user-images.githubusercontent.com/3426470/168516605-67842874-3f30-4f86-bd4f-79971c968b56.jpeg)
[watermark](https://user-images.githubusercontent.com/3426470/168516625-40b96ea9-34fd-4d36-bd24-33b735c9cce8.png)

**Comment by faradaytrs** [comment]
Watermark size is dynamicly calculated, and as i understand problem appears when resizing watermark size is large than requested original picture size:
for example i resize 1920x1920 image to { width: 500, height: 1600, withoutEnlargement: true, fit: 'outside' }
Because of fit=outside, result is expected to be 1600x1600.
So i calculate watermark to be { height: 640 }
And it fails. (Probably because watermark is 640, but requested original image resize has width:500, which is smaller.)

**Comment by faradaytrs** [comment]
As i understand it's not related to fit property, i think it's common pattern when requested resize properties are smaller than size of the composited image (althought resulting image is not that small).
With fit=inside it just never happens because image is always smaller or equal than requested size.

**Comment by lovell** [comment]
> for example i resize 1920x1920 image to { width: 500, height: 1600, withoutEnlargement: true, fit: 'outside' }
Because of fit=outside, result is expected to be 1600x1600.
So i calculate watermark to be { height: 640 }
And it fails.

The following works for me using the provided values:
```js
  const first = await sharp("first.jpg")
    .resize({
      width: 500,
      height: 1600,
      withoutEnlargement: true,
      fit: "outside",
    })
    .toBuffer();

  const watermark = await sharp("watermark.png")
    .resize({ height: 640 })
    .toBuffer();

  await sharp(first)
    .composite([
      {
        input: watermark,
        tile: true,
      },
    ])
    .toFile("out.jpg");
```
```sh
$ file first.jpg watermark.png out.jpg 
first.jpg:     JPEG image data, JFIF standard 1.01, resolution (DPI), density 96x96, segment length 16, comment: "CREATOR: gd-jpeg v1.0 (using IJG JPEG v80), quality = 75", baseline, precision 8, 1920x1920, components 3
watermark.png: PNG image data, 325 x 325, 8-bit/color RGBA, non-interlaced
out.jpg:       JPEG image data, baseline, precision 8, 1600x1600, components 3
```
I tried other combinations of the various values you provided but cannot reproduce. What changes do I need to make to my code to make it fail?

**Comment by faradaytrs** [comment]
Well for your example i now get: Error: replicate: parameter down not set
For my first example ({ width: 5000, height: 250, withoutEnlargement: true, fit: 'outside' }' etc):
Error: replicate: parameter down not set

What can be a reason for such errors? 
BTW i use arm64 first in amazon lambda nodejs 16 runtime.

**Comment by lovell** [comment]
Perhaps you could create a standalone repo with the exact code, images and dependency versions that allows someone else to reproduce.

**Comment by faradaytrs** [comment]
Yeah i will do it when i have time, but in your example you use toBuffer() after resize of the first image and make composite with new sharp object, but in my case i directly call composite(). I guess it's the key difference between our examples.

**Comment by lovell** [comment]
Thanks, I've been able to reproduce with your updated code sample. Commit https://github.com/lovell/sharp/commit/a75718565cf3c2ad24a5a3bfe50559b658e9785f fixes this and adds a test case based on the code in this issue, which would previously have failed.

**Comment by faradaytrs** [comment]
Thank you for your time on this matter! I appretiate that.

**Comment by lovell** [comment]
v0.30.7 now available with the fix, thanks for reporting this.
