### ISSUE TITLE
SVG with feImage to PNG

### ISSUE THREAD

**Issue by lucasnantonio** [lovell/sharp#3229]
### What are you trying to achieve?

I'm trying to convert an SVG to PNG, but the SVG contains an `feImage` filter that does not render.

### When you searched for similar issues, what did you find that might be related?

I haven't found issues mentioning `feImage`.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg width="1200" height="600" viewBox="0 0 1200 628" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
    <filter id="image" primitiveUnits="objectBoundingBox">
      <feImage xlink:href="https://images-na.ssl-images-amazon.com/images/I/51tti3lnX0L._SX422_BO1,204,203,200_.jpg" width="100%" preserveAspectRatio="xMinYMin" x="0" y="0"/>
    </filter>
    </defs>
    <rect width="100%" height="100%" fill="#fff"/>
    <rect x="100" y="120" width="310" height="350" style="filter:url(#image);"/>
</svg>
```

Expected output:
<img width="764" alt="CleanShot 2022-05-16 at 11 56 13@2x" src="https://user-images.githubusercontent.com/13240286/168634363-964531b5-1f9e-499a-b4dc-b93ef6714673.png">

Output:
<img width="766" alt="CleanShot 2022-05-16 at 11 56 30@2x" src="https://user-images.githubusercontent.com/13240286/168634415-30a1b577-83e3-4f58-a011-f5107a0f1298.png">

Is there a way to embed external images into my svgs to that they get rendered in the PNG output?

**Comment by lovell** [comment]
External images are not supported - please see #1871

**Comment by lucasnantonio** [comment]
Thank you, I didn't find that before writing my question. 

In case anyone is trying to solve a similar use case, I was able to achieve my goal by generating an initial PNG from my base SVG (with text, but without the external image):

![forever-peace-book](https://user-images.githubusercontent.com/13240286/169303102-2b08cf5b-8a00-4090-8954-62c1e0646061.png)


Then using `composite` to add my external image on top of it:

![forever-peace-book](https://user-images.githubusercontent.com/13240286/169303302-19ba6f05-aa9c-4372-9d73-d1c91f74e428.png)
