### ISSUE TITLE
Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.8.dylib

### ISSUE THREAD

**Issue by wenshan** [lovell/sharp#323]
Hello，

```
 ...Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.8.dylib
  Referenced from: /usr/local/opt/vips/lib/libvips.42.dylib
  Reason: Incompatible library version: libvips.42.dylib requires version 13.0.0 or later, but libjpeg.8.dylib provides version 9.0.0

```

**Comment by lovell** [comment]
Hello. Does running `brew update && brew upgrade` help? What command was run to install `vips`?

**Comment by lovell** [comment]
@wenshan Have you been able to make any progress?

**Comment by tomjoro** [comment]
try symlinking it from $ sudo ln -s /usr/local/Cellar/jpeg/8d/lib/libjpeg.8.dylib /usr/local/opt/jpeg/lib/libjpeg.8.dylib

**Comment by lovell** [comment]
IIRC running `brew unlink jpeg && brew link jpeg` might also produce a similar effect to that described by @tomjoro.

**Comment by tomjoro** [comment]
thanks. That worked for me too and is a better solution than manual symlink.

**Comment by lovell** [comment]
Closing this as it looks like the solution is working for people. Feel free to re-open if not.

**Comment by torrtuga** [comment]
I am getting the following error : https://stackoverflow.com/questions/45931476/library-not-loaded-usr-local-opt-jpeg-lib-libjpeg-8-dylib 
Can anyone help in how to remove the error?
