### ISSUE TITLE
Query about GIFs

### ISSUE THREAD

**Issue by hisRoyalty** [lovell/sharp#3231]
### What are you trying to achieve?

I'm trying to achieve an image which is 'pasted' on a gif for every frames using [Sharp Library](https://github.com/lovell/sharp/)

```js
const sharp = require('sharp')

const baseGIF =
"test.gif";

const baseImage = "unknown.png"

sharp(baseImage)
.resize(10,10)
.toBuffer().then(buffer => {
    const overlay = [
        {
          input:
          buffer,
          tile: true, gravity: 'northwest'
        },
      ];
      
      sharp(baseGIF, { animated: true })
      .composite(overlay)
      .resize(100, 100)
      .toFile("output.gif", (err) => {
        if (err) {
          console.log("error: ", err);
        }
      });
    
})  
```
I get returned this, with many of the same images.
I'm trying to make a image card with a photo of someone in the left, and the background is a GIF.
How can I also position the image?

![alt](https://media.discordapp.net/attachments/737983098351779870/976072825305698334/output.gif)

**Comment by lovell** [comment]
Does removing the following line produce the expected output (albeit at the wrong size)?
```diff
-       .resize(100, 100)
```

**Comment by hisRoyalty** [comment]
Unfortunately, it does not. I did the resize on the GIF so it looks more appropriately like a GIF card.
![alt](https://media.discordapp.net/attachments/737983098351779870/976806058246942760/output.gif)
These are my assets:
![alt](https://media.discordapp.net/attachments/737983098351779870/976806102266171452/test.gif)
(the gif)
![alt](https://media.discordapp.net/attachments/737983098351779870/976806452666724402/unknown.png)
(image)

I just want one of the image in a specific area, like the middle or left. Only one, not multiple. How can I achieve this?

**Comment by hisRoyalty** [comment]
@lovell 
Pretty much solved this problem.
However, is there a way you can like composite/dissolve a gif over an image?
For example :
A flag of america 'merged' or dissolved into an image making the image look like an american

**Comment by hisRoyalty** [comment]
figured out
