### ISSUE TITLE
Install sharp on Raspberry Pi

### ISSUE THREAD

**Issue by nschwa** [lovell/sharp#324]
Hello,
is there a way to install `sharp` on a Raspberry Pi (raspian jessie)?
When trying to `npm install sharp` I get the following [errormessage](https://gist.github.com/nschwa/80707924d321a6306c0e).
My npm-version is: 1.4.21
I ran the preinstall-script as described [here](http://sharp.dimens.io/en/stable/install/)
Is this a specific problem with `sharp` or a general one.
Thank you for suggestions, what a non Linuxexpert like me can do to fix it.  
All the best
Schwaddi

**Comment by lovell** [comment]
Hello, proper ARM support should arrive as part of #312.

I did manage to manually install libvips and most of its dependencies on a first generation Pi sometime last year, but it was't totally straightforward.

What is/was the output of running the following?
```sh
curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | sudo bash -
```

**Comment by nschwa** [comment]
Hi @lovell,
> What is/was the output of running the following?
> `curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | sudo bash -` 


I can't say I ran it last night :). I'll repeat it and report the output.  
Thanks so far
Schwaddi

**Comment by lovell** [comment]
I'll need to update that script to install libvips v8.1.0 from source on Jessie-based systems (as they only provide 7.40.6 via apt-get); leave it with me.

You should be able to use sharp v0.11.4 for now.

Thanks for reporting this!

**Comment by nschwa** [comment]
@lovell thanks for your help. Installation of sharp v0.11.4 worked perfect.

**Comment by lovell** [comment]
Commit 6d62051 should enforce the installation of libvips v8.1.1 and therefore allow the use of sharp v0.12.x on Raspbian Jessie systems.

Are you able to test this? It would be great to add documented support for Raspberry Pis in time for Christmas :)

**Comment by nschwa** [comment]
It's a bit late for *Christmas*, but today I was able to test the installation of sharp on a brand new Raspberry Pi 2 running Raspbian Jessie.
- Running the preinstall script worked and installed `libvips 8.1.1`
- Trying to `npm install sharp` resulted in an error concerning `node-gyp rebuild`
- so I did `apt-get remove nodejs` and followed [these instructions](http://node-arm.herokuapp.com/) to install lastest `node-arm`
- after a reboot `npm install sharp` worked like a charm  

Thx @lovell for your support

**Comment by lovell** [comment]
Great news, thanks for confirming.

If you'd be interested in `sharp` providing a pre-compiled libvips for the ARM architecture, please subscribe to #312 - we may require testers!

**Comment by alicenq** [comment]
If anyone is still having issues I was able to get it to work after much headache. Running raspbian gnu/linux 9.4 on a pi 3

npm version 5.6.0
node version 9.10.1

sudo npm install n -g --save
sudo apt remove node --purge
sudo apt install node-gym
sudo n stable

** Make sure you are the owner of ~, this was the cause of a bunch of cryptic messages for me
** If you aren't, sudo chown -R <your user> ~

npm install sharp --build-from-source
