### ISSUE TITLE
Memory corruption on arm64

### ISSUE THREAD

**Issue by alexdupre** [lovell/sharp#3243]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [X] Running `npm install sharp` completes without error.
- [X] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [X] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```

  System:
    OS: Linux 5.10 Amazon Linux 2
    CPU: (2) arm64 Neoverse-N1
    Memory: 1.36 GB / 1.81 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
```

### What are the steps to reproduce?

The issue is easily and 100% reproducible installing `strapi` on a Linux arm64 machine (like a t4g EC2 instance) and uploading the attached file in the media library (either via admin dashboard or api). The node app will crash with either `free(): invalid next size (fast)` (upload via dashboard) or `malloc(): memory corruption` (upload via api) when trying to create the image thumbnail.

### What is the expected behaviour?

The thumbnail of the image is created without issues.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

Unfortunately I wasn't able to create a minimal test case to show the memory corruption issue, without other running code the memory corruption doesn't create a visible crash.

### Please provide sample image(s) that help explain this problem

![download](https://user-images.githubusercontent.com/3694371/171677952-1ae4f128-de41-4ba4-aa8f-3dc6cc592378.png)

**Comment by lovell** [comment]
Please see #3225
