### ISSUE TITLE
heif hevc output mangled in more recent versions of sharp/libvips with alpine

### ISSUE THREAD

**Issue by elrob** [lovell/sharp#3244]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

(latest by platform support)

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

- node:16.15.0-alpine3.14 + vips-dev=8.10.6-r1 + sharp@0.28.3
```
   System:
     OS: Linux 5.10 Alpine Linux
     CPU: (4) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
     Memory: 7.99 GB / 9.73 GB
     Container: Yes
     Shell: 1.33.1 - /bin/ash
   Binaries:
     Node: 16.15.0 - /usr/local/bin/node
     Yarn: 1.22.18 - /usr/local/bin/yarn
     npm: 8.5.5 - /usr/local/bin/npm
   npmPackages:
     sharp: ^0.28.3 => 0.28.3
```

- node:16.15.0-alpine3.15 + vips-dev=8.12.1-r0 + sharp@0.29.3
```
   System:
     OS: Linux 5.10 Alpine Linux
     CPU: (4) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
     Memory: 7.99 GB / 9.73 GB
     Container: Yes
     Shell: 1.34.1 - /bin/ash
   Binaries:
     Node: 16.15.0 - /usr/local/bin/node
     Yarn: 1.22.18 - /usr/local/bin/yarn
     npm: 8.5.5 - /usr/local/bin/npm
   npmPackages:
     sharp: ^0.29.3 => 0.29.3
```

### What are the steps to reproduce?

[heif_issue.zip](https://github.com/lovell/sharp/files/8830468/heif_issue.zip)

4 files in above zip:
- Dockerfile
- heif-issue.js
- run.sh
- sharp.png

Unzip and run `bash run.sh`

It outputs `output/output.heif` and `output-new/output.heif`.

On my macbook, the outputs look like this:
- node:16.15.0-alpine3.14 + vips-dev=8.10.6-r1 + sharp@0.28.3
- `output/output.heif`
<img width="378" alt="image" src="https://user-images.githubusercontent.com/3116850/171810420-4603db09-d244-442b-9e3c-5f3b28d8f136.png">

- node:16.15.0-alpine3.15 + vips-dev=8.12.1-r0 + sharp@0.29.3
- `output-new/output.heif`
<img width="383" alt="image" src="https://user-images.githubusercontent.com/3116850/171810478-8aa3c0f5-099b-43f7-9c4c-dc7b04f4ac27.png">

### What is the expected behaviour?

Expected that the second image should be identical to the first image.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

(Included above)

### Please provide sample image(s) that help explain this problem

(Included above)

**Comment by lovell** [comment]
Did you see #3224? There appears to be a bug in macOS Preview relating to HEIC images where they are rendered with green rectangles.

**Comment by elrob** [comment]
Hmm.
Thank you! 

Yes, I have now reconverted the HEIC images back to png and they look fine.
It is strange that the conversion with older version of sharp, vips, libheif is loaded fine by macOS Preview and Photos but the newer one is not.

Now I need to check whether these load correctly on iOS as it seems I cannot trust what I see on the mac...

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by elrob** [comment]
Thanks.

Trying to migrate away from HEIC completely because it has become a pain.
- Apparently, I can't trust what I see on the mac (although older versions didn't have this issue) - and I don't have iOS device to see if the images render correctly there
- Bugs with odd dimensions and small dimensions that I've had to workaround previously and complicate the code
- Requires custom vips builds

**Comment by lovell** [comment]
Thanks for the update, HEIC is usually the wrong answer to any question.
