### ISSUE TITLE
Is it possible to warp an overlap image using Sharp 

### ISSUE THREAD

**Issue by smarajitWOW** [lovell/sharp#3245]
Is it possible to transform a composite image in Node Sharp that can achieve the below warp effect (desired final composite image on the right)?  

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/hprtc.jpg

I attempted using the affine operation but could not achieve the desired effect https://sharp.pixelplumbing.com/api-operation#affine

**Comment by lovell** [comment]
Please see #2095
