### ISSUE TITLE
@nodert-win10-c\windows.ui.notifications\build\Release\binding.node is not a valid Win32 application

### ISSUE THREAD

**Issue by OfficialGatesTechnologies** [lovell/sharp#3246]

**Comment by lovell** [comment]
I think this was meant for https://github.com/NodeRT/NodeRT

**Comment by OfficialGatesTechnologies** [comment]
@lovell thanks for you reply. I am getting following issue while installing the package
`\@nodert-win10-rs3\windows.ui.notifications\opaquewrapper.cpp : fatal error C1107: could not
find assembly 'platform.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment
 variable`

**Comment by lovell** [comment]
This is unrelated to sharp. Please search for similar issues and/or report this at https://github.com/NodeRT/NodeRT
