### ISSUE TITLE
Composite with `blend: "clear"` clears the whole second image

### ISSUE THREAD

**Issue by Nokel81** [lovell/sharp#3247]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 1.56 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 6.14.17 - ~/repos/lens/node_modules/.bin/npm
  npmPackages:
    sharp: ^0.30.6 => 0.30.6
```

### What are the steps to reproduce?

```ts
async function test() {
  const circleSvg = new JSDOM(`
    <body>
      <svg viewBox="0 0 32 32">
        <circle cx="20" cy="20" r="6" />
      </svg>
      <style>
        circle {
          fill: "black" !important;
        }
      </style>
    </body>
  `).window.document.getElementsByTagName("svg")[0];

  circleSvg.innerHTML += getSvgStyling("dark");

  const circleBuffer = await sharp(Buffer.from(circleSvg.outerHTML))
    .toBuffer();

  await sharp(circleBuffer)
    .resize({ width: 128, height: 128 })
    .composite([
      {
        input: circleBuffer,
        top: 90,
        left: 90,
        blend: "clear",
      },
    ])
    .png()
    .toFile("./output.png");
}

test();
```

### Outcome
![output](https://user-images.githubusercontent.com/8225332/172200097-91466a4d-5aa8-4757-b629-1d631a31bc33.png)

### What is the expected behaviour?

Something like the following (manually recreated in gimp)

![output](https://user-images.githubusercontent.com/8225332/172202142-7060a707-e2d3-4dca-9806-43a2a17f6716.png)

**Comment by lovell** [comment]
It looks like the effect you're trying to achieve, using the upper image to punch a hole in the lower image, should use the `dest-out` blend. You might need to adjust the offsets too.

Here's a sample image and the code to generate it:

![output](https://user-images.githubusercontent.com/210965/172234599-152b8d2d-f5a9-4853-a760-a6b8de561f72.png)

```js
  const circleSvg = Buffer.from(`
    <svg viewBox="0 0 32 32">
        <circle cx="20" cy="20" r="6" fill="black" />
    </svg>`);

  await sharp(circleSvg)
    .resize({ width: 128, height: 128 })
    .composite([
      {
        input: circleSvg,
        top: 50,
        left: 50,
        blend: "dest-out",
      },
    ])
    .toFile("./output.png");
```

**Comment by Nokel81** [comment]
Thanks, I guess I got the coordinates wrong. I did try `dest-out` after searching through the git history to figure out how `clipOverlay` was implemented just before it was removed.

Thanks for this answer so quickly.
