### ISSUE TITLE
 gif with { colors: 2 } options , the colors setting is completely ignored. If it is { colors: 3 } or larger, it works perfectly fine.

### ISSUE THREAD

**Issue by gaodeng** [lovell/sharp#3249]

**Comment by lovell** [comment]
Thanks for reporting, I've opened an upstream issue for this at https://github.com/libvips/libvips/issues/2852

**Comment by lovell** [comment]
v0.31.0 now available with prebuilt binaries that contain the fix, thanks for reporting this.

**Comment by gaodeng** [comment]
Thanks
