### ISSUE TITLE
Input buffer has corrupt header: source input: Old-style JPEG compression support is not configured

### ISSUE THREAD

**Issue by joanlouji** [lovell/sharp#3253]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [X] Running `npm install sharp` completes without error.
- [X] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [X] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  Binaries:
    Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.1/bin/npm
```

### What are the steps to reproduce?

Just tried to convert a tiff to png. 

### What is the expected behaviour?

Expecting the tiff image to be converted into png image

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```
        const imgbuffer = "............"; // Buffer
        const buffer = Buffer.from(imgbuffer, 'base64');
        const bitmap = await sharp(buffer).tiff().png().toBuffer();
```

### Please provide sample image(s) that help explain this problem
<img width="1467" alt="Screenshot 2022-06-11 at 2 47 36 PM" src="https://user-images.githubusercontent.com/75722167/173181794-047be782-fc71-4074-bceb-3c7c678034aa.png">

**Comment by lovell** [comment]
It looks like the TIFF input file you're trying to convert uses the "old style" JPEG compression, which has been deprecated since sometime in the 1990s, well over 20 years ago.

You might be able to compile your own libtiff with support for this, then compile libvips from source to use it, then compile sharp from source to use it - see https://sharp.pixelplumbing.com/install#custom-libvips
