### ISSUE TITLE
SVG: support for vector-effect SVG2 property

### ISSUE THREAD

**Issue by Annsanbudeyu** [lovell/sharp#3255]
-  environment
nodejs: 14.18.3
sharp: 0.30.6

- svg 
![svg in chrome](https://user-images.githubusercontent.com/31604995/173225733-d3c2c428-c0e6-4c03-96ff-7617ca579605.png)
![svg code](https://user-images.githubusercontent.com/31604995/173225775-a870027f-192f-406d-86e6-c4695ce54156.png)

- code
![convert code](https://user-images.githubusercontent.com/31604995/173225782-cfc9d090-d233-446f-9e2d-cf150f66c56f.png)

- output
![output png](https://user-images.githubusercontent.com/31604995/173225799-4fbad94e-e7b9-405e-9b20-91bc5aa8b607.png)

**Comment by lovell** [comment]
Please can you provide the complete source SVG image rather than screengrabs.

**Comment by Annsanbudeyu** [comment]
![svg](https://user-images.githubusercontent.com/31604995/173264159-5bfb71cf-97dc-4982-bb20-c1d65f89ce1d.svg)

**Comment by lovell** [comment]
Thank you, the `vector-effect` property is part of SVG2 and is not yet supported by librsvg:

https://gitlab.gnome.org/GNOME/librsvg/-/blob/main/src/properties.rs#L486

I can't find a specific tracking issue for this property at https://gitlab.gnome.org/GNOME/librsvg/-/issues so perhaps you could open an enhancement request and provide this SVG as an example.

**Comment by Annsanbudeyu** [comment]
Thank you for your answer; i will open an enhancement request for libsvg.

**Comment by kleisauke** [comment]
Looks like this has just been reported upstream at https://gitlab.gnome.org/GNOME/librsvg/-/issues/885.

**Comment by lovell** [comment]
Implemented in librsvg v2.56.0, which is included in the prebuilt binaries for sharp v0.32.0.
