### ISSUE TITLE
Setting WebP effort to 0 in constructor does not change the object's effort option to 0

### ISSUE THREAD

**Issue by AlexanderTheGrey** [lovell/sharp#3259]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [ X] Running `npm install sharp` completes without error.
- [ X] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [ X] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

System:
    OS: macOS 10.15.7
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 16.41 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  npmPackages:
    sharp: ^0.30.6 => 0.30.6

### What are the steps to reproduce?

Setting WebP effort to 0 (fastest) in the constructor does not change the effort option to 0.

However, setting WebP effort 1 in the constructor correctly changes the effort option to 1.

https://sharp.pixelplumbing.com/api-output#webp

### What is the expected behaviour?

The effort option should be set to 0.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

<pre>
const image = sharp(input.gif, { animated: true }).webp({ quality: 100, effort: 0 })

image.toFile(output.webp, (err) => {
    console.log("WebP Effort ====>", image.options.webpEffort);
    if (err === null) {
      console.log("Success");
    } else {
      console.log("Error")
    }
  });
</pre>

### Please provide sample image(s) that help explain this problem

https://en.wikipedia.org/wiki/GIF#/media/File:Rotating_earth_(large).gif

**Comment by lovell** [comment]
Good spot, the problem is here:

https://github.com/lovell/sharp/blob/b10d8f89ca8190b3973a5c4c0e419be21eab3777/lib/output.js#L498

Happy to accept a PR to fix this, if you're able.

**Comment by AlexanderTheGrey** [comment]
Sure, I can do that.

**Comment by lovell** [comment]
v0.30.7 now available, thank you for both reporting and fixing this.

**Comment by AlexanderTheGrey** [comment]
Thank you for making great open source software!
