### ISSUE TITLE
Converting GIF to WebP in lossless results in a smaller file size and higher image quality compared to lossy

### ISSUE THREAD

**Issue by AlexanderTheGrey** [lovell/sharp#3260]
### What are you trying to achieve?

I wan to convert GIF files to WebP with good quality and a small file size.

Using lossy compression on the example image "SmallFullColourGIF.gif" results in noticeably lower quality and a larger file.

When converting using lossless compression, the WebP output file is smaller and indistinguishable from the original GIF.

### When you searched for similar issues, what did you find that might be related?

Lossy compression should yield a smaller file size than lossless compression.

https://www.keycdn.com/support/lossy-vs-lossless

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

Lossless:

<pre>
const image = sharp(input.gif, { animated: true }).webp({ quality: 100, lossless: true, effort: 1 })

image.toFile(output.webp, (err) => {
    if (err === null) {
      console.log("Success");
    } else {
      console.log("Error")
    }
  });
</pre>

Lossy:

<pre>
const image = sharp(input.gif, { animated: true }).webp({ quality: 100, effort: 1 })

image.toFile(output.webp, (err) => {
    if (err === null) {
      console.log("Success");
    } else {
      console.log("Error")
    }
  });
</pre>

### Please provide sample image(s) that help explain this question

https://en.wikipedia.org/wiki/GIF#/media/File:SmallFullColourGIF.gif

**Comment by lovell** [comment]
Have you tried using the [gif2webp](https://developers.google.com/speed/webp/docs/gif2webp) command line tool with the same options to help eliminate sharp/libvips? My best guess would be that this is a libwebp thing.

**Comment by AlexanderTheGrey** [comment]
The default settings for gif2webp is lossless. gif2webp conversion using the default options converts the GIF into a much smaller file size and visually identical quality compared to sharp with default settings, which uses lossy as default.

gif2webp uses quality as a measure of compression with the default lossless compression, and sharp more efficiently compresses the WebP file when using maximum CPU. However, sharp still produces a significantly (15%) larger file size with maximum effort using lossy vs sharp lossless at minimum CPU effort.

When choosing the lossy setting for gif2webp, the same behavior occurs, where the quality is much lower, with obvious artifacting, and the file size is much larger than the original GIF.

So this seems to be a general issue of creating a lossy WebP from an animated image (GIF in this case).

Maybe the solution is to make lossless the default sharp option when the source file is a GIF/has pages?

**Comment by lovell** [comment]
> When choosing the lossy setting for gif2webp, the same behavior occurs, where the quality is much lower, with obvious artifacting, and the file size is much larger than the original GIF.

Thanks for checking, I agree, this sounds like a libwebp encoder problem. Perhaps you could ask the libwebp maintainers, although I'm unsure how much active development it sees as many of the team are now working on JPEG-XL.

I'd prefer to keep sharp's default output settings constant - it's relatively easy for someone to add their own logic to control these based on the input e.g. by calling `metadata()` first.

**Comment by lovell** [comment]
Closing as this appears to be a WebP thing and I don't think there's anything we can do in sharp to alleviate. Please feel free to reopen if evidence arises to show this isn't the case.
