### ISSUE TITLE
sharp.composite.toBuffer silently crashes

### ISSUE THREAD

**Issue by KaKi87** [lovell/sharp#3264]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
npx: installed 1 in 0.754s

  System:
    OS: Linux 5.4 Linux Mint 19.3 (Tricia)
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
    Memory: 571.78 MB / 23.44 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 14.19.3 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 6.14.17 - /usr/bin/npm
  npmPackages:
    sharp: ^0.30.6 => 0.30.6 
```

### What are the steps to reproduce?

- Run the following example ;
  
- The 1st `console.log` statement is reached ;
  
- The 2nd isn't.
  

### What is the expected behaviour?

The 2nd `console.log` statement is reached.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```js
import { promises as fs } from 'fs';
import sharp from 'sharp';

(async () => {
    const
        [buffer1, buffer2] = await Promise.all([fs.readFile(/* ... */), fs.readFile(/* ... */)]),
        { height: height1 } = await sharp(buffer1).metadata(),
        result = await sharp().composite([
            { input: buffer1, left: 0, top: 0 },
            { input: buffer2, left: 0, top: height1 }
        ]);
    console.log(result);
    console.log(await result.toBuffer());
})();
```

### Please provide sample image(s) that help explain this problem

Any picture from [picsum.photos](https://picsum.photos/) will reproduce the bug.

In fact, before reading the issue template, I was going to provide the following snippet :

```js
import axios from 'axios';
import sharp from 'sharp';

const getRandomImageBuffer = async () => Buffer.from((await axios.get('https://picsum.photos/100', { responseType: 'arraybuffer' })).data, 'binary');

(async () => {
    const
        [buffer1, buffer2] = await Promise.all([getRandomImageBuffer(), getRandomImageBuffer()]),
    // ...
})();
```

---
Thanks !

**Comment by lovell** [comment]
Hi, what happens if you add some error handling to this code sample? For example, `toBuffer()` returns a Promise that might reject, but I don't see anything here that is capturing it.

**Comment by KaKi87** [comment]
> `toBuffer()` returns a Promise that might reject, but I don't see anything here that is capturing it.

Something would still be logged.
For example, this :
```js
(async () => {
    throw new Error();
})();
```
Outputs this :
```
(node:XXXXX) UnhandledPromiseRejectionWarning: Error
    at file://
```
In order to properly catch errors, the last line can be replaed with `})().catch(console.error);`, which will output this :
```
Error
    at file://
```
But, in my case, the script just stops with no output, just like if it was the same as the following :
```js
(async () => {
    process.exit();
    throw new Error();
})().catch(console.error);
```

**Comment by lovell** [comment]
The use of the empty constructor in `sharp().composite(...)` means that the sharp instance becomes a `WritableStream` and is expecting the input to be piped in. However, nothing in this code ever supplies that input, so the output `Promise` never resolves (or rejects). Node.js correctly ends the process as there's nothing left to do.

Perhaps you meant to composite onto a blank background?
```js
result = sharp({
  create: {
    width: 100, height: 100, channels: 3, background: 'black'
  }
}).composite(...)
```

**Comment by KaKi87** [comment]
I understand, so I have to get the metadata of all pictures before creating the composite. Thanks

**Comment by lovell** [comment]
I suspect the future possible enhancement at #1580 will be of interest to you.

**Comment by KaKi87** [comment]
Definitely, since my goal is to generate sprite images. Thanks !
