### ISSUE TITLE
using the image that no longer exists, but that has the same name as an image that exists and is different

### ISSUE THREAD

**Issue by Gustavo13132** [lovell/sharp#3265]
I'm taking an image and overlaying two images and exporting it with the toFile() function. I get and export the images always with the same name inside the same folder. When I do that again I delete the folder and put the 3 images again with the same name but with different contents and when running the code it returns the image that was generated last time with the old contents. Can you help me to return the image with the right contents?
My code:
await sharp(__dirname + '/public/background.jpg')
    .resize({ width: 1000, height: 430 })
    .composite([{
      input: `${__dirname}/public/product.png`, top: 15, left: 30
    }, { input: `${__dirname}/public/text.png` }])
    .toFile(`${__dirname}/public/banner.jpg`)
    .then(info => {
      console.log(info)
    }).catch(error => {
      console.log(error)
    })
    fs.rm("./public", { recursive: true }, (err) => { 
      if (err) { 
        console.error(err);
      } 
      else { 
        console.log("Directory Deleted!"); 
        fs.mkdir(path.join(__dirname, 'public'), (err) => {
          if (err) {
            return console.error(err);
        }
        console.log('Directory created successfully!');
        })
      }
    });
    res.send("http://localhost:8080/files/banner.jpg")

**Comment by lovell** [comment]
If you're reusing filenames within the same process, please disable caching within libvips via `sharp.cache(false)`

https://sharp.pixelplumbing.com/api-utility#cache
