### ISSUE TITLE
In need of help / ideas on installing sharp on cflinuxfs3 - stack

### ISSUE THREAD

**Issue by CN91** [lovell/sharp#3269]
### What are you trying to achieve?

I'm trying to run Strapi or Directus on a cloud foundry instance with a nodejs buildpack. However both are failing due to depending on sharp. It's an environment that has no acces to the www. Trying to set the prebuild dependency still fails the install. 

### When you searched for similar issues, what did you find that might be related?

https://github.com/lovell/sharp/issues/1053
https://sharp.pixelplumbing.com/install#custom-prebuilt-binaries
https://github.com/lovell/sharp/issues/2482
https://stackoverflow.com/questions/72457804/yarn-installation-error-tunneling-socket-could-not-be-established-cause-conne 

I've tried several setups,  and at first setting the sharp_libvips_local_prebuild inside the .nprmc also was a challenge in itself. I had to put it inside a folder, with a version because:

`sharp_libvips_local_prebuilds: "/tmp/app/libvips-8.12.2-linux-x64.tar.br"`

 ends up as : 

 `sharp: Using local /tmp/app/libvips-8.12.2-linux-x64.tar.br/v8.12.2/libvips-8.12.2-linux-x64.tar.br`

Which is just confusing, because why can you set the file, but then it needs to be inside a folder with a version?
Anyway after somehow understanding that, I  hit another roadblock

```
npm ERR! code 1
   npm ERR! path /tmp/app/node_modules/sharp
   npm ERR! command failed
   npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
   npm ERR! sharp: Using local libvips from /tmp/app/libvips-8.12.2-linux-x64.tar.br/v8.12.2/libvips-8.12.2-linux-x64.tar.br
   npm ERR! sharp: Integrity check skipped for linux-x64
   npm ERR! prebuild-install warn install getaddrinfo ENOTFOUND github.com
   npm ERR! gyp info it worked if it ends with ok
   npm ERR! gyp info using node-gyp@8.4.1
   npm ERR! gyp info using node@16.14.2 | linux | x64
   npm ERR! gyp info find Python using Python version 3.6.9 found at "/usr/bin/python3"
   npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.2/node-v16.14.2-headers.tar.gz
   npm ERR! gyp WARN install got an error, rolling back install
   npm ERR! gyp ERR! configure error 
   npm ERR! gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
   npm ERR! gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad 
   npm ERR! gyp ERR! stack network settings.
   npm ERR! gyp ERR! stack     at go (/tmp/contents1144776509/deps/0/node/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:173:17)
   npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
   npm ERR! gyp ERR! stack     at async install (/tmp/contents1144776509/deps/0/node/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:62:18)
   npm ERR! gyp ERR! System Linux 4.15.0-177-generic
   npm ERR! gyp ERR! command "/tmp/contents1144776509/deps/0/node/bin/node" "/tmp/contents1144776509/deps/0/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
   npm ERR! gyp ERR! cwd /tmp/app/node_modules/sharp
   npm ERR! gyp ERR! node -v v16.14.2
   npm ERR! gyp ERR! node-gyp -v v8.4.1
   npm ERR! gyp ERR! not ok
   npm ERR! A complete log of this run can be found in:
   npm ERR!     /tmp/cache/final/.npm/_logs/2022-06-17T15_13_16_413Z-debug-0.log
          **ERROR** Unable to build dependencies: exit status 1
   Failed to compile droplet: Failed to run all supply scripts: exit status 14

```

I have tried in several ways to apply the prebuild, or use of 'SHARP_INSTALL_FORCE' however since it is a cloud foundry container / buildpack it seems to have it's own mind of handling things. I tried supplying the packages vendored, but it still goes into rebuild. And this container does not have acces to the wordwideweb, and whatever the sharp package is trying to do is really giving me a headache.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

We eventually tried with only sharp, that gives us the exact same error as when it is a nested dependency from strapi or directus.

package.json
```
{
  "dependencies": {
    "sharp": "^0.30.6"
  }
  "engines": {
    "node": "16.x.x",
    "npm": "8.x.x"
  },
}
```

manifest.yml
```
---
applications:
  - name: strapi
    # path: ./dist
    memory: 128M
    command: node server.js
    buildpacks:
      - nodejs_buildpack
    env:
        NPM_CONFIG_REGISTRY: <internal.nexus.hidden>
        NPM_CONFIG_SHARP_INSTALL_FORCE: true
        npm_config_sharp_libvips_local_prebuilds: "/tmp/app/libvips-8.12.2-linux-x64.tar.br"
    health-check-type: http
    health-check-http-endpoint: /health
```

.npmrc
```
sharp_libvips_local_prebuilds=/tmp/app/libvips-8.12.2-linux-x64.tar.br
sharp_install_force=true
```

The stack used on our cloud foundry is https://github.com/cloudfoundry/cflinuxfs3 with the https://github.com/cloudfoundry/nodejs-buildpack .

It seems like this package is heavily depending on having www-access and since this setup does not, I'm rather struggling how to get it install correctly so I can use Strapi or Directus.

**Comment by lovell** [comment]
Did you see https://sharp.pixelplumbing.com/install#custom-prebuilt-binaries ?

> To install the prebuilt sharp binaries from a directory on the local filesystem, set the sharp_local_prebuilds npm config option or the npm_config_sharp_local_prebuilds environment variable.

**Comment by CN91** [comment]
I did see and try the prebuild for the libvips, and like I said above that option works weird.

`sharp_libvips_local_prebuilds: "/tmp/app/libvips-8.12.2-linux-x64.tar.br"`

ends up as :

`sharp: Using local /tmp/app/libvips-8.12.2-linux-x64.tar.br/v8.12.2/libvips-8.12.2-linux-x64.tar.br` 

so if you don't place the .br file within nested folders with it's name and version it can't even find it. 

Next to that I couldn't find a prebuild that should be placed for "sharp_local_prebuilds" . The initial failure was on trying to download the libvips-8.12.2-linux-x64.tar.br from github.com so i downloaded that myself and put it in the repo with the `sharp_libvips_local_prebuilds` option.  The documentation is not really clear on when to use which option with which possible binary.

**Comment by lovell** [comment]
If the relevant libvips prebuild is located at `/tmp/app/v8.12.2/libvips-8.12.2-linux-x64.tar.br` then set `sharp_libvips_local_prebuilds` to `/tmp/app`. The relevant version and file name are always appended, as it says in the docs ("The version subpath and file name are appended to these"), as this allows you to have multiple versions if required.

Prebuilt binaries for sharp can be found under https://github.com/lovell/sharp/releases

**Comment by CN91** [comment]
While providing both it still somehows tries to get something from github.com 
`sharp_local_prebuild = "v0.30.6" -> sharp-v0.30.6-napi-v5-linux-x64.tar.gz `
`sharp_libvips_local_prebuilds = v8.12.2 -> libvips-8.12.2-linux-x64.tar.br `



```
 npm notice 
   npm ERR! code 1
   npm ERR! path /tmp/app/node_modules/sharp
   npm ERR! command failed
   npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
   npm ERR! sharp: Using local libvips from /tmp/app/prebuilds/v8.12.2/libvips-8.12.2-linux-x64.tar.br
   npm ERR! sharp: Integrity check skipped for linux-x64
   npm ERR! prebuild-install warn install getaddrinfo ENOTFOUND github.com
   npm ERR! gyp info it worked if it ends with ok
   npm ERR! gyp info using node-gyp@8.4.1
   npm ERR! gyp info using node@16.14.2 | linux | x64
   npm ERR! gyp info find Python using Python version 3.6.9 found at "/usr/bin/python3"
   npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.2/node-v16.14.2-headers.tar.gz
   npm ERR! gyp WARN install got an error, rolling back install
   npm ERR! gyp ERR! configure error 
   npm ERR! gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
   npm ERR! gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad 
   npm ERR! gyp ERR! stack network settings.
   npm ERR! gyp ERR! stack     at go (/tmp/contents2359305257/deps/0/node/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:173:17)
   npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
   npm ERR! gyp ERR! stack     at async install (/tmp/contents2359305257/deps/0/node/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:62:18)
   npm ERR! gyp ERR! System Linux 4.15.0-177-generic
   npm ERR! gyp ERR! command "/tmp/contents2359305257/deps/0/node/bin/node" "/tmp/contents2359305257/deps/0/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
   npm ERR! gyp ERR! cwd /tmp/app/node_modules/sharp
   npm ERR! gyp ERR! node -v v16.14.2
   npm ERR! gyp ERR! node-gyp -v v8.4.1
   npm ERR! gyp ERR! not ok
   npm ERR! A complete log of this run can be found in:
   npm ERR!     /tmp/cache/final/.npm/_logs/2022-06-18T16_35_58_444Z-debug-0.log
          **ERROR** Unable to build dependencies: exit status 1
   Failed to compile droplet: Failed to run all supply scripts: exit status 14
```

Does it have to do with the node version ? do I have to pick another? or for the sharp prebuild do i have to put in the .node file only instead of the tar.gz?

**Comment by lovell** [comment]
Please note the plural - it is `sharp_local_prebuilds` rather than `sharp_local_prebuild` - there's more help at https://github.com/prebuild/prebuild-install#local-prebuilds

**Comment by CN91** [comment]
i made a type here, it's plural in my manifest. Would it skip the whole node_gyp step if the prebuild is used? or would it still run? otherwise i still need to look at the next node-gyp issue. (https://stackoverflow.com/questions/42722457/how-to-prevent-node-gyp-from-downloading-node-headers-tar-gz-and-node-lib-from-i )

**Comment by CN91** [comment]
We eventually managed to make it work :

```
sharp_libvips_local_prebuilds = /tmp/app/binaries/libvips/
sharp_local_prebuilds = /tmp/app/binaries/sharp/v0.30.6/
```

The libvips requires the versionnumberr-folder while the sharp_local_prebuilds doesnt. Next to that it seemed very vulnerable for typos ( without starting / it would be relative to the node_modules folder for ex.)

**Comment by lovell** [comment]
Glad to hear you got it working. I've added some worked examples to the docs via commit https://github.com/lovell/sharp/commit/29e09898f78ba192ab620ea16f4dc323c785d6e5 to help others who might run into the same problem.

**Comment by corys** [comment]
> The libvips requires the versionnumberr-folder while the sharp_local_prebuilds doesnt. 

I also missed this detail in the documentation and didn't figure it out until seeing this issue. Also, it seems that when it can't find the local prebuild for `libvips` it throws an error, but if it can't find the `sharp` local prebuild it simply fetches it from GitHub.  So I didn't realize that my `sharp_local_prebuilds` value was wrong because the install was succeeding.

Anyway, thank you for this issue. It solved my problem.

**Comment by yibajianghudao** [comment]
At first, based on the following prompt:

```
npm ERR! sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.4/libvips-8.14.4-win32-x64.tar.br
npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! sharp: Installation error: read ECONNRESET
```

I downloaded `libvips-8.14.4-win32-x64.tar.br` from the provided URL. Then, I configured the `.npmrc` file as follows:

```
sharp_libvips_local_prebuilds = C:\Users\JiangHuDao\Downloads\
```

(I placed the downloaded file at `sharp_libvips_local_prebuilds = C:\Users\JiangHuDao\Downloads\libvips-8.14.4-win32-x64.tar.br`). After that, I attempted `npm install`, but encountered the error:

```
sharp: Installation error: ENOENT: no such file or directory, open 'C:\Users\JiangHuDao\Downloads\v8.14.4\libvips-8.14.4-win32-x64.tar.br'
```

I had to create a `v8.14.1` directory to make the file path become:

```
C:\Users\JiangHuDao\Downloads\v8.14.4\libvips-8.14.4-win32-x64.tar.br
```

(I initially added `\v8.14.4\` in the `.npmrc` file, but then I noticed that it was automatically included during path resolution, which required attention.) This issue seems to be caused by differences between Windows and Linux environments.
