### ISSUE TITLE
Sharp toFile doesn't save files to local machine when deployed on Heroku, it does work in localhost

### ISSUE THREAD

**Issue by yoontaemin** [lovell/sharp#3276]
Hello,

I'm trying to save uploaded images on the local disk, which is a mounted disk.

During upload tests on localhost it works perfectly fine, the images are directly appearing on the local disk.
When it's deployed on Heroku, the code executes without any error message, but the images don't appear at all on the local disk.

The folder structure is already in place, so there is no need to create new folders.

What am I missing here?

`
"node": "14.15.5"
"sharp": "^0.30.7"
"Windows 10": "build 19043.1766"
`

// Resize images
const resizeImages = async (req, res, next) => {
  // Get Property Data
  const propURL = new URL(req.headers.referer)
  const propertyData = propURL.searchParams
  const propertyCode = propertyData.get("code")
  const imgFolder = IMG-${propertyCode}
  const destination = Z:\\App\\Library\\${propertyCode}\\Inventory Website\\${imgFolder}

  // Check for image files
  if (!req.files) return next()

  // Array images
  req.body.images = []

  await Promise.all(
    req.files.map(async (file) => {
      const filename = file.originalname.replace(/\..+$/, "")
      const newFilename = RENAME-${filename}-${Date.now()}.jpg
      const targetPath = ${destination}\\${newFilename}
      await sharp(file.buffer).resize(2048).toFormat("webp").toFile(targetPath)
      req.body.images.push(newFilename)
    })
  )
  next()
}

**Comment by lovell** [comment]
The paths in this look like they are for Windows, but Heroku uses Linux and a different filesystem layout, so they are unlikely to work.

I also notice there's no error handling, which might explain why you're not seeing any errors.

**Comment by yoontaemin** [comment]
> The paths in this code look like they are for Windows, but Heroku uses Linux and a different filesystem layout, so they are unlikely to work.
> 
> I also notice there's no error handling, which might explain why you're not seeing any errors.

Hello, thank you for your reply.

My goal is to save the files locally on a Windows OS, while running the code on Heroku. Do I still in this case need to reformat the paths to Linux filesystem layout?

**Comment by lovell** [comment]
> My goal is to save the files locally on a Windows OS, while running the code on Heroku.

This isn't possible, is unrelated to sharp and is way beyond anything I can help with. Good luck.
