### ISSUE TITLE
How can I composite an image to bottom right with margin

### ISSUE THREAD

**Issue by shtse8** [lovell/sharp#3277]
I want to composite an image to another image with gravity southeast with 10px margin.
how can I do it?
I have checked the documentation, there are only `top`, `left` options which are not applicable to gravity.

**Comment by lovell** [comment]
Hi, from the information provided here my best guess would be that you'll need to calculate `top` and `left` based on the image dimensions.

I note the issue template was ignored/deleted. It requested the following information, which is the sort of thing that you'll need to provide for further help.

* Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question
* Please provide sample image(s) that help explain this question

**Comment by shtse8** [comment]
```ts
const logoBuffer = await sharp('./logo.jpg')
  .resize(100, 100)
  .toBuffer()
  .ensureAlpha(0)

const image = await sharp('./image.jpg')
  .composite([{
    input: logoBuffer,
    gravity: 'southeast'
    // I want bottom right with 10px margin
  }])
  .jpg()
```

**Comment by lovell** [comment]
The `gravity` option aligns the edges of images, but this scenario doesn't require that to be the case.

If you know the dimensions of 'image.jpg' then you can calculate the values for `top` and `left`.

* top = height of image - height of logo - height of margin
* left = width of image - width of logo - width of margin

**Comment by shtse8** [comment]
> The `gravity` option aligns the edges of images, but this scenario doesn't require that to be the case.
> 
> If you know the dimensions of 'image.jpg' then you can calculate the values for `top` and `left`.
> 
> * top = height of image - height of logo - height of margin
> * left = width of image - width of logo - width of margin

I'm afraid I can't get the image size as I am using stream input.
is it any easier way to achieve this? and any reason why there are no `bottom`, `right` while there are `top`, `left` properties. or having `origin` property is cool too.

**Comment by lovell** [comment]
Perhaps you could add a transparent margin to your logo, then it can be aligned to the edges.

**Comment by shtse8** [comment]
That's what I am doing to composite with margin. I just feel like so stupid for adding margin to logo before compositing.

**Comment by lovell** [comment]
An enhancement has been opened for this at #3309 so please subscribe there for any updates.
