### ISSUE TITLE
cannot process an image using sharp with node.js 14 on aws

### ISSUE THREAD

**Issue by fotso0244** [lovell/sharp#3278]
I have installed last version of sharp. after deploying my web server code (on node.js 14) on aws, it takes too long time to process an image. what is wrong please?? How to fix it??

**Comment by fotso0244** [comment]
I deployed my web server on amazon linux 2 instance by using elastic beanstalk

**Comment by lovell** [comment]
I'm going to close this issue as there is no useful information here that allows anyone to help you, plus the issue template that asks you to provide it was ignored/deleted.

If you have a genuine question that relates to sharp, where you've been able to prove that it is not your own code or AWS services that are the problem, please open a new `question` issue at https://github.com/lovell/sharp/issues/new?labels=question&template=question.md and answer all of the questions. Please provide too much information rather that not enough.
