### ISSUE TITLE
Animated WebP doesn't process

### ISSUE THREAD

**Issue by ProtoScott** [lovell/sharp#3279]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [X ] Running `npm install sharp` completes without error.
- [ X] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [ X] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What are the steps to reproduce?

Attempt to read in the animated webp image.
(I am able to run and process regular jpg and webp images without issues)

### What is the expected behaviour?

That it allows me to read in and resize the image.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

 processedImage = await sharp(imageObject.Body, { animated: true })
                .resize({
                    width: width,
                })
                .webp()
                .toBuffer()

(Doesn't seem to throw errors in try catch)

### Please provide sample image(s) that help explain this problem

https://cdn.watchcorridor.com/images/preview/c7fcd3d9-ba05-49f1-99b2-5d39bd1c8232/preview-50.webp

**Comment by ProtoScott** [comment]
Hi Lovell, 
Thanks for replying. That works for me locally as well, but doing the toBuffer on an AWS lambda fails.

![image](https://user-images.githubusercontent.com/73667130/177059050-f8777de3-c769-44a7-ba19-2c7deb3e8ce9.png)

![image](https://user-images.githubusercontent.com/73667130/177059248-f57b1844-e8b4-4f48-823d-d8cb778abbcb.png)

**Comment by lovell** [comment]
The bit that says "Billed Duration: 3000ms" suggests you're reaching a configured timeout on Lambda, unrelated to sharp.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
