### ISSUE TITLE
preinstall: cache build folders for faster ci tests

### ISSUE THREAD

**Issue by jonathanong** [lovell/sharp#328]
currently, on circleci, compiling libvips with the preinstall.sh script takes 2 minutes, which is more than 50% of the entire test. it takes so long because it's compiling libvips from source.

an optimization would be to check whether the cache folders already exist (ex. `vips-8.1.1`) and simplify install it, skipping the rest of the script. this would make installations much faster.

of course, in your CI test suite, you have to add the cache folder to your config.

any thoughts or ideas on this?

**Comment by lovell** [comment]
Hello, which version of sharp are you using?

v0.12.0+ should use a pre-compiled libvips on Circle CI's Ubuntu 12.04 via `npm install` without the need to run the almost-deprecated `preinstall.sh` script - see http://sharp.dimens.io/en/stable/install/#linux

**Comment by jonathanong** [comment]
ah i didn't know it was deprecated. thanks!

**Comment by lovell** [comment]
No worries. I say "almost deprecated" because Centos 6.
