### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by shweta-chalageri** [lovell/sharp#3280]
os=windows server 2008
node version=12.19.0
nvm=6.14.8
sharp version=0.30.6

getting this error:

PS E:\rendering\nodeapp> node app.js
E:\rendering\nodeapp\node_modules\sharp\lib\sharp.js:34
  throw new Error(help.join('\n'));
  ^

Error:
Something went wrong installing the "sharp" module

The specified module could not be found.
\\?\E:\rendering\nodeapp\node_modules\sharp\build\Release\sharp-win32-x64.node

**Comment by lovell** [comment]
Hi, the issue template was ignored/deleted. Please can you open a new installation issue and answer all of the questions. https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md
