### ISSUE TITLE
error while execution app which uses  sharp 

### ISSUE THREAD

**Issue by shweta-chalageri** [lovell/sharp#3281]
os=windows server 2008
node version=12.19.0
nvm=6.14.8
sharp version=0.30.6

getting this error:

PS E:\rendering\nodeapp> node app.js
E:\rendering\nodeapp\node_modules\sharp\lib\sharp.js:34
throw new Error(help.join('\n'));
^

Error:
Something went wrong installing the "sharp" module

The specified module could not be found.
\?\E:\rendering\nodeapp\node_modules\sharp\build\Release\sharp-win32-x64.node

**Comment by lovell** [comment]
As I politely requested in #3280, please answer all of the questions in the issue template. I cannot help without you having done so. These questions, and the answers you provide, exist to save both you and I time.
