### ISSUE TITLE
Max file size for image?

### ISSUE THREAD

**Issue by rbruhn** [lovell/sharp#3282]
Is there a function like ImageMagick jpeg:extent where the output file size will not be greater than the set amount? I've not been able to find an answer after reading the documents.

Example in ImageMagick (in php):
```
$this->imagickService->setOption('jpeg:size', '1540x1540');
$this->imagickService->setOption('jpeg:extent', '600kb');
```
This produces images within the dimensions but not greater than 600kb in size.
Thanks for any feedback.

**Comment by lovell** [comment]
Please see #3219 #3163 #2916 #2627 #1667
