### ISSUE TITLE
Can not convert larger tiff or svs files to deepzoomimages.

### ISSUE THREAD

**Issue by mohitKS777** [lovell/sharp#3283]
## I am trying to convert a sample svs file to a dzi image. I am able to do this for smaller files (<50MB). However on trying larger files it gives me `[Error: Input image exceeds pixel limit]`. Is this an issue with sharp or should I do something differently. I am adding my sample code below.
Additional info: I want to be able to convert files of upto 8GB in size as this is largest one that I have, but practically file size should not be a limit.

sharp("sampleFile.svs")
  .png()
  .tile({
    size: 512,
  })
  .toFile("output.dz", function (err, info) {
    // output.dzi is the Deep Zoom XML definition
    // output_files contains 512x512 tiles grouped by zoom level
    console.log(err);
  });

**Comment by lovell** [comment]
Did you see the `limitInputPixels` property on the constructor?

https://sharp.pixelplumbing.com/api-constructor

```js
sharp("sampleFile.svs", { limitInputPixels: false })...
```

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
