### ISSUE TITLE
Error! EPERM: operation not permitted, Scandir

### ISSUE THREAD

**Issue by sakibb019** [lovell/sharp#3285]
Hi all.
In our project, I just deployed a repository from Github to the [vercel](https://vercel.com/) account. i just complete all the steps but at end of the process I got an error that looks like this: 

`Error! EPERM: operation not permitted, scandir 'C:\Users\sakib\.........\ `

Does it the right way? i anything wrong with how to sort out this problem...

your valuable solution is appreciate for me
Thanks

**Comment by lovell** [comment]
Hi, the installation issue template was ignored/deleted. Please open a new installation issue and answer all of the questions.

https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md
