### ISSUE TITLE
Make source quality setting available

### ISSUE THREAD

**Issue by tastytea** [lovell/sharp#3288]
### What are you trying to achieve?

My original issue is with a program (from another person) that makes thumbnails of avatars. The quality was left at the default (80), but my JPEG-avatar needs at least 90 to not look awful. The obvious solution is to increase the quality, but that makes many other avatars needlessly large.

Some image formats, for example JPEG, save the quality setting in their metadata. Others, like WebP, save whether it is compressed lossy or lossless. It would be nice if sharp would expose that information, maybe even use it as default quality setting for the output image.

### When you searched for similar feature requests, what did you find that might be related?

#3260 is kind of similar, but only about animated images.

### What would you expect the API to look like?

I don't know since i don't program with sharp, i encountered it as a user of a program that uses it.

### What alternatives have you considered?

1. Always use a high quality setting — wastes space
2. Get the meta data some other way — it seems to make more sense to expose it in sharp since a metadata function already exists and i think it is useful for others, too.

**Comment by lovell** [comment]
Please see #908
