### ISSUE TITLE
Can't use sharp with pkg

### ISSUE THREAD

**Issue by rightaway** [lovell/sharp#3289]
Here's a package.json to reproduce the issue

```json
{
  "name": "test",
  "scripts": {
    "bundle": "pkg --compress gzip --output ./pkg ."
  },
  "dependencies": {
    "sharp": "0.27.2"
  },
  "devDependencies": {
    "pkg": "5.7.0"
  },
  "bin": "index.js",
  "pkg": {
    "assets": [
      "node_modules/sharp/build/Release/**/*",
      "node_modules/sharp/vendor/lib/**/*"
    ],
    "targets": [
      "node16-linux-x64"
    ]
  }
}
```

Here is index.js

```js
const sharp = require('sharp')

async function test() {
  console.log(await sharp('/tmp/test.jpg').metadata())
}

test()
```

If I run `node index.js` it works and I see the metadata of the file.

But if I run the `bundle` script from package.json I get these errors.

```
compression:  GZip
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules/sharp/build/Release
  %2: path-to-executable/sharp/build/Release
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules/sharp/vendor/lib
  %2: path-to-executable/sharp/vendor/lib
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules/sharp/build/Release
  %2: path-to-executable/sharp/build/Release
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules/sharp/vendor/lib
  %2: path-to-executable/sharp/vendor/lib
```

If I use the latest sharp version I get these lines as well. If I use 0.27.2 I don't.

```
prebuild-install WARN This package does not support N-API version v16.15.0
prebuild-install WARN install No prebuilt binaries found (target=v16.15.0 runtime=napi arch=x64 libc= platform=linux)
```

When I try to run the package created by sharp I get an error

```
pkg/prelude/bootstrap.js:1876
  throw error;
  ^

Error:
Something went wrong installing the "sharp" module

libvips-cpp.so.42: cannot open shared object file: No such file or directory
```

Can you reproduce these errors and do you know how I can solve it? https://github.com/vercel/pkg/issues/1075#issuecomment-930223024 says it should be working.

**Comment by lovell** [comment]
(Cross-posted at https://github.com/vercel/pkg/issues/1692 )

Looking at https://github.com/vercel/pkg/blob/main/dictionary/sharp.js I can see the following change might be required, but this is a guess.

```diff
-      ['vendor/lib', 'sharp/vendor/lib', 'directory'],
+      ['vendor', 'sharp/vendor', 'directory'],
```

**Comment by rightaway** [comment]
I tried changing that file in `node_modules/pkg/dictionary/sharp.js` but still getting the error.

**Comment by lovell** [comment]
May I suggest you create a standalone repo with all dependencies and code that allows someone else to reproduce.

**Comment by rightaway** [comment]
Does latest sharp not work with node 16.15.0? I don't get that warning with 0.27.2.

    prebuild-install WARN This package does not support N-API version v16.15.0
    prebuild-install WARN install No prebuilt binaries found (target=v16.15.0 runtime=napi arch=x64 libc= platform=linux)

**Comment by lovell** [comment]
This looks like a bug in `pkg` - it is hard-coding the target to be the version of Node.js, which is incorrect when the runtime is `napi`.

https://github.com/vercel/pkg/blob/62f6da937a915dde824e30e5b9af7f707ba391fb/lib/producer.ts#L228-L229

You'll need to report this downstream.

**Comment by lovell** [comment]
Looks like the problem in `pkg` has been fixed - see https://github.com/vercel/pkg/issues/1695
