### ISSUE TITLE
JPG Error: Input file is of an unsupported image formatVipsForeignLoad

### ISSUE THREAD

**Issue by abhijeetshah** [lovell/sharp#329]
When I run the following code

var imgInput ='/home/app/logo/logo100x100.jpg'
var imgOutput ='/home/app/logo/logo100x100.jpg'

sharp(imgInput)
  .resize(50, 50)
  .toFile(imgOutput, function(err) {
     if (err) console.log(err)
     // Some other code
  });

I get the following err ...

Error: Input file is of an unsupported image formatVipsForeignLoad: "/home/app/logo/logo100x100.jpg" is not a known file format ]

What could I be doing wrong ? I have rechecked twice and the jpg is of proper format.

**Comment by lovell** [comment]
Hello, if the input and output paths contain the same string value then this should be failing with "[Cannot use same file for input and output](https://github.com/lovell/sharp/blob/master/index.js#L623)".

The "unsupported image format" error can also be obtained when the input path is incorrect or invalid.

Finally, libvips may somehow have been compiled without JPEG support. This is unlikely but you can check via `sharp.format`.

**Comment by abhijeetshah** [comment]
You are correct my mistake. Had same path for input and output file.
