### ISSUE TITLE
opencvjs and sharp (instead of jimp)

### ISSUE THREAD

**Issue by yieldinov** [lovell/sharp#3291]
### What are you trying to achieve?

I'm trying to repeat opencv.js set up according to their tutorial but instead of `jimp` I'd like to use `sharp`
https://docs.opencv.org/4.6.0/dc/de6/tutorial_js_nodejs.html

Tutorial uses `jimp` to read file, accesses `bitmap` property, and feeds the result into `cv.matFromImageData`
```js
// load local image file with jimp. It supports jpg, png, bmp, tiff and gif:
var jimpSrc = await Jimp.read('./lena.jpg');
// `jimpImage.bitmap` property has the decoded ImageData that we can use to create a cv:Mat
var src = cv.matFromImageData(jimpSrc.bitmap);
//...
```
How can I achieve similar functionality but with `sharp`?

### When you searched for similar issues, what did you find that might be related?
googled, and looked for similar issues - found nothing

**Comment by lovell** [comment]
The OpenCV `matFromImageData()` function appears to accept an [ImageData](https://developer.mozilla.org/en-US/docs/Web/API/ImageData) object. The `data` property is raw RGBA pixel data, so perhaps try something like the following (untested):

```js
const { data, info } = await sharp(input)
  .ensureAlpha()
  .raw()
  .toBuffer({ resolveWithObject: true });

const { width, height } = info;
const mat = cv.matFromImageData({ data, width, height });
```

https://sharp.pixelplumbing.com/api-channel#ensurealpha
https://sharp.pixelplumbing.com/api-output#raw

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by lovell** [comment]
@mariusbolik Looks OK, perhaps delay `src.delete()` until after all processing has completed as, depending on the underlying type of `src.data`, the call to `Buffer.from()` might create a "view" rather than copy data.
