### ISSUE TITLE
Module did not self-register

### ISSUE THREAD

**Issue by KiranGire** [lovell/sharp#3293]
Something went wrong installing the "sharp" module

Module did not self-register: '/home/Project/node_modules/sharp/build/Release/sharp.node'.

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues

Above is the error coming up after npm install sharp

**Comment by lovell** [comment]
Hello, the installation issue template appears to have been ignored and/or deleted. Please open a new installation issue and provide answers to all of the questions.

https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md

In particular, please see https://sharp.pixelplumbing.com/install#worker-threads
