### ISSUE TITLE
How to append final image dimension in the filename?

### ISSUE THREAD

**Issue by crzyjcky** [lovell/sharp#3298]
### What are you trying to achieve?

I am trying to append image dimension in the filename after resizing (fit = contain). I don't the final dimension before processing.
e.g. image_400x250.jpg

### When you searched for similar issues, what did you find that might be related?
none.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```
      const {resizedBuffer, info} = await sharp(file)
      .resize({height: 200, width: 200, fit:  "contain"})
      .toFormat('jpeg', {mozjpeg: true})
      .toBuffer({resolveWithObject: true})

      sharp(resizedBuffer)
      .toFile(`${file}_${info.height}x${info.width}`)

Error: Invalid input
    at Sharp (/Users/yuenkit/Bhere/process_images/node_modules/sharp/lib/constructor.js:134:11)
    at /Users/crzyjcky/Code/process_images/readFiles.js:27:7
```

### Please provide sample image(s) that help explain this question
none

**Comment by lovell** [comment]
Please see #2812

**Comment by crzyjcky** [comment]
Hi @lovell thanks for the idea.

I can run the code for single image.

When I did it in a loop for multiple files, I encountered an error where only one file will be get resized.

I have 2 files in `./img` folder - sammy.png, tammy.png. Every time I run `node readFiles.js`, sometime I got `sammy.png-200x200.png`, sometime i got `tammy.png-200x200.png`.


```
% node readFiles.js
files in img folder [ 'sammy.png', 'tammy.png' ]
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, rename './img-resized/temp.png' -> './img-resized/tammy.png-200x200.png'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: './img-resized/temp.png',
  dest: './img-resized/tammy.png-200x200.png'
}
```

Here's my code:
```
// readFiles.js

const fs = require('fs/promises')

const sharp = require('sharp')

const getFilesAsync = async () => {
  files = await fs.readdir(process.cwd() + '/img')

  console.log('files in img folder', files)

  const temp = './img-resized/temp.png'

  const resizeds = files.map(async (file) => {
    
    sharp(file)
      .resize({height: 200, width: 200, fit:  "contain"})
      .toFile(temp)
      .then(({width, height}) => fs.rename(temp, `./img-resized/${file}-${width}x${height}.png`))
  })
}

getFilesAsync()

```

**Comment by lovell** [comment]
There's a race condition in your code where the outputs can potentially overwrite each other. Perhaps try a unique output filename based on the input, something like:
```diff
- const temp = './img-resized/temp.png'
+ const temp = `./img-resized/${file}-temp.png`
```

**Comment by crzyjcky** [comment]
Nice! Thank you.
