### ISSUE TITLE
How sharpness works with multi-page PDFs?

### ISSUE THREAD

**Issue by 4m4rel** [lovell/sharp#3299]
Hi,
First of all, thank you for this library, it's really great!

I'm wondering how is the sharpness calculated for PDF file?

For example, I have a PDF file with a few pages inside, I read it with `sharp` and convert to one large image. 
When I check it for the sharpness, what will I get: some average value for all the pages, minimal sharpness of the most blurred page or something else?

Sorry if there is an answer somewhere, couldn't find it.
Best regards!

**Comment by lovell** [comment]
The following will calculate the sharpness of all pages combined (imagine they have been stitched together top to bottom).
```js
const { sharpness } = await sharp(input, { pages: -1 }).stats();
```
If you want averages/min/max etc., you'll need to make one call per page and calculate yourself:
```js
const sharpnessFirstPage = (await sharp(input, { page: 0 }).stats()).sharpness;
const sharpnessSecondPage = (await sharp(input, { page: 1 }).stats()).sharpness;
...
```

**Comment by 4m4rel** [comment]
Yeah, I did that, but the operation was much slower.

So, if we have a PDF where one page is completely blurred and all the others fine, we get sharpness value just a little bit lower, but not the one that says "You might have a problem with blurred page in this file"...

Ok, I understood your point. Thanks a lot for the answer!
