### ISSUE TITLE
Possible dependency loop: Cannot find module 'brace-expansion'

### ISSUE THREAD

**Issue by dtoubelis** [lovell/sharp#330]
I've added `"sharp": "^0.12.1"` to my `package.json` and I'm using `npm install` to install the package on Ubuntu 14.04. It is failing with the following message:

```
> sharp@0.12.1 install /var/lib/jenkins/workspace/WebApp/node_modules/sharp
> node-gyp rebuild

module.js:328
    throw err;
    ^

Error: Cannot find module 'brace-expansion'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/lib/jenkins/workspace/WebApp/node_modules/minimatch/minimatch.js:10:14)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
gyp: Call to 'GLOBAL_VIPS_VERSION="7.38.5" node -e "require('./binding').use_global_vips()"' returned exit status 1. while trying to load binding.gyp
```
Subsequent run of `npm instal` is successful and I'm able to install and use the package, however, this  wrecks havoc with our automated builds.

**Comment by dtoubelis** [comment]
It seems like some sort of dependency loop. I had to create a `npm-shrinkwrap.json` in order to freeze the working configuration. Calling `npm install` with `npm-shrinkwrap.json` in place works around this problem.

**Comment by lovell** [comment]
`brace-expansion` is a dependency of `minimatch` which is likely to be a dependency of another module that ultimately sharp is dependent upon. It's also a dependency of `npm` itself.

My best guess here is that you've run into the https://github.com/npm/npm/issues/8152 race condition that I believe has been fixed in npm v3. Are you able to upgrade the globally-installed version of npm?

**Comment by dtoubelis** [comment]
My global version of npm is 3.3.12. It is one that came with nodejs v5.3.0.

**Comment by lovell** [comment]
Ah, in that case this problem looks more like https://github.com/nodejs/node/issues/3922

The stacktrace suggests `node` itself is looking in `/var/lib/jenkins/workspace/WebApp/node_modules/minimatch/...` for the `minimatch` module at require time. I'm not sure why it would do that - perhaps another dependency in `WebApp/package.json` has:

1. inserted some kind of require hook that relies on `minimatch`, or
2. an older version of `minimatch` that doesn't specify the `brace-expansion` dependency

**Comment by dtoubelis** [comment]
This is relevant section from my `package.json` if it helps:

```json
  "devDependencies": {
    "auto-reload-brunch": ">= 1.0 < 1.9",
    "chai": "^3.4.1",
    "clean-css-brunch": ">= 1.0 < 1.9",
    "css-brunch": ">= 1.0 < 1.9",
    "hippie": "^0.4.0",
    "javascript-brunch": ">= 1.0 < 1.9",
    "jshint": "~2.6.3",
    "less-brunch": "^1.8.1",
    "mocha": "^2.2.0",
    "mocha-bamboo-reporter": "^1.1.0",
    "stylus-brunch": "^1.8.1",
    "uglify-js-brunch": ">= 1.0 < 1.9"
  },
  "dependencies": {
    "aws-sdk": "^2.1.45",
    "bcrypt": "^0.8.5",
    "bcrypt-nodejs": "^0.0.3",
    "body-parser": "^1.13.3",
    "cache-manager": "^1.2.2",
    "cache-manager-redis": "^0.2.1",
    "connect-flash": "^0.1.1",
    "connect-memcached": "^0.1.0",
    "cookie-parser": "^1.3.5",
    "csurf": "^1.8.3",
    "express": "^4.13.3",
    "express-handlebars": "^2.0.1",
    "express-session": "^1.11.3",
    "handlebars": "^4.0.5",
    "jshint-brunch": "^1.8.0",
    "jsonwebtoken": "^5.4.1",
    "lodash": "^3.10.1",
    "memcached": "^2.1.0",
    "newrelic": "~1.24.0",
    "node-uuid": "^1.4.3",
    "nodemailer": "^1.4.0",
    "nodemailer-ses-transport": "^1.3.0",
    "passport": "^0.2.2",
    "passport-local": "^1.0.0",
    "pg": "^4.4.1",
    "pg-hstore": "^2.3.2",
    "sequelize": "^3.5.1",
    "sharp": "^0.12.1",
    "zxcvbn": "^4.2.0"
  }
```

**Comment by dtoubelis** [comment]
Oh BTW, Node.js v5.x is installed directly from the official `Nodejs.org` repository to a brand new Linode instance with Ansible automation script, so there is no traces of any bundled Node.js on the system. The only thing that happened to it - it was upgraded from v5.2.0 to v5.3.0 but it was way before I started using `sharp`, so I cannot tell if it worked before or not.

**Comment by lovell** [comment]
@dtoubelis Have you been able to make any progress with this problem?

**Comment by dtoubelis** [comment]
No not really, I run npm install twice and then shrinkwrap it. That is an extra step but it does it for me.

**Comment by lovell** [comment]
@dtoubelis Thanks for the update - I'll leave this open to see if others run into the same problem.

**Comment by verpixelt** [comment]
I'm running `node v5.11.0` and `npm 3.8.7` and I get the following error
```
module.js:341
    throw err;
    ^

Error: Cannot find module 'brace-expansion'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/node_modules/minimatch/minimatch.js:10:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by lovell** [comment]
Closing this as there have been no further reports of a similar problem in the last 6 months.

**Comment by pas4gok** [comment]
I am facing this issue as well. Any idea how it was fixed?

```
grunt --env=prod
Loading "clean.js" tasks...[31mERROR[39m
[31m>> [39mError: Cannot find module 'brace-expansion'
Loading "compress.js" tasks...[31mERROR[39m
[31m>> [39mError: Cannot find module 'brace-expansion'
```

**Comment by piyushmanurkar** [comment]
Same for node 8.9.4, npm 5.6.0

**Comment by lovell** [comment]
@piyushmanurkar https://github.com/npm/npm/issues/11088
