### ISSUE TITLE
AVIF conversion shows HEIC format output in console

### ISSUE THREAD

**Issue by defido** [lovell/sharp#3300]
## Possible bug

System is M1 Mac

### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.
- [x]
-  
### What are the steps to reproduce?

```
sharp(`./input.${type}`)
    .toFormat('avif')
    .toFile('./output.avif')
```

### What is the expected behaviour?

Show the format as AVIF on the output

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```
sharp(`./input.${type}`) // This simply is how we input the file
    .toFormat('avif')
    .toFile('./output.avif')
```

returns 

```
{
  format: 'heif',
  width: 924,
  height: 924,
  channels: 4,
  premultiplied: false,
  size: 6769
}
```
### Please provide sample image(s) that help explain this problem
![test10](https://user-images.githubusercontent.com/95591037/180143584-58b66ce8-c7bb-49e3-b437-2d755e279ada.png)
Output file: https://publicbucket.defido.workers.dev/output.avif
<img width="171" alt="Screen Shot 2022-07-21 at 4 25 58 pm" src="https://user-images.githubusercontent.com/95591037/180144113-60254881-be50-4865-b605-25c170aa3b06.png">

**Comment by lovell** [comment]
This is correct. Perhaps you're confusing HEIF with HEIC?

An AVIF image is a HEIF file that uses AV1 compression. A HEIC image is a HEIF file that uses HEVC compression.

When selecting the output format, sharp provides `avif` as a convenience wrapper around `heif`.

https://github.com/lovell/sharp/blob/e40a881ab4a5e7b0e37ba17e31b3b186aef8cbf6/lib/output.js#L817-L819

**Comment by defido** [comment]
> This is correct. Perhaps you're confusing HEIF with HEIC?

Well that's embarrassing 👍
