### ISSUE TITLE
support for blind watermark or digital text watermark

### ISSUE THREAD

**Issue by LeToNode** [lovell/sharp#3302]
### What are you trying to achieve?

I found this function  work with python，Java， but  I have not found work with Javascript。

https://github.com/guofei9987/blind_watermark

### When you searched for similar feature requests, what did you find that might be related?

those projects realize this function  by opencv.

**Comment by lovell** [comment]
This looks like a form of frequency-based stenography. If you want to do this with a Node.js runtime rather than Python, perhaps try https://github.com/Sherryer/blind-watermark/tree/master/scripts/blind-watermark ?

**Comment by LeToNode** [comment]
ok，i will try it first。
