### ISSUE TITLE
Sharp metadata twists height and width for some images

### ISSUE THREAD

**Issue by MichielS-1848709** [lovell/sharp#3305]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?
```
System:
    OS: Linux 5.15 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 AMD EPYC 7B12
    Memory: 14.12 GB / 62.80 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.2 - /nix/store/ra8r42571xvv1m85wanh1ll9mxmp0mwl-nodejs-16.13.2/bin/node
    Yarn: 1.22.17 - /nix/store/ylaybq7lj0yr3w5jcmrba9rhb8nlcflz-yarn-1.22.17/bin/yarn
    npm: 8.1.2 - /nix/store/ra8r42571xvv1m85wanh1ll9mxmp0mwl-nodejs-16.13.2/bin/npm
  npmPackages:
    sharp: 0.30.7 => 0.30.7
```
### What are the steps to reproduce?

1. Load the supplied image (see the standalone code example) in sharp
2. Call the `metadata()` function

### What is the expected behaviour?

According to Windows, the image has the following dimensions:
- `width`: 3024
- `height`: 4032

![image](https://user-images.githubusercontent.com/32015956/180645599-72f1163d-a895-4837-9b4c-9ce28b7a8d69.png)

However `sharp` generates the following metadata:
```
{
  format: 'jpeg',
  width: 4032,
  height: 3024,
  space: 'srgb',
  channels: 3,
  depth: 'uchar',
  density: 72,
  chromaSubsampling: '4:2:0',
  isProgressive: false,
  resolutionUnit: 'inch',
  hasProfile: true,
  hasAlpha: false,
  orientation: 6,
  exif: <Buffer 45 78 69 66 00 00 4d 4d 00 2a 00 00 00 08 00 06 01 12 00 03 00 00 00 01 00 06 00 00 01 1a 00 05 00 00 00 01 00 00 00 56 01 1b 00 05 00 00 00 01 00 00 ... 9302 more bytes>,
  icc: <Buffer 00 00 02 18 61 70 70 6c 04 00 00 00 6d 6e 74 72 52 47 42 20 58 59 5a 20 07 e6 00 01 00 01 00 00 00 00 00 00 61 63 73 70 41 50 50 4c 00 00 00 00 41 50 ... 486 more bytes>
}
```

For some reason sharp twists the width and height.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

https://replit.com/@michielswaanen1/Sharp-bug-report#index.js

### Please provide sample image(s) that help explain this problem

A sample image can be found in the standalone code sample

**Comment by lovell** [comment]
Hi, this output looks correct. The image is a 4032x3024 JPEG with an EXIF orientation of 6, so web browsers will auto-rotate it before displaying.

**Comment by MichielS-1848709** [comment]
Hey, looks like I didn't read the documentation well. So I need to look at the orientation and flip it myself? I'm using the metadata to display the image in NextJS.
