### ISSUE TITLE
Does it reduce quality and get blurry with bigger file-size when resizing to same resolution?

### ISSUE THREAD

**Issue by ktjd123** [lovell/sharp#3307]
### What are you trying to achieve?

Hi, I'm trying to resize the image to same resolution (detect user's web screen size and resize).

But when the same resolution hits the quality of image seems to be lower than the original one (pre-resized via sharp).

It seems it gets blurry and get bigger filesize.

### When you searched for similar issues, what did you find that might be related?

Jpeg quality can be lowered when compressed and de-compressed but it doesn't seem to be matter if it has same option I guess.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```ts
  const result = await image
    .resize(1920, undefined, {
      withoutEnlargement: true,
    })
    .flatten({ background: { r: 255, g: 255, b: 255, alpha: 1 } })
    .jpeg({ quality: 90, mozjpeg: true })
    .toBuffer();
```

I used this code to use to resize 1920 image to 1920 and it seems quality difference is big enough to notice.

### Please provide sample image(s) that help explain this question

ORIGINAL
![original](https://user-images.githubusercontent.com/15044488/180911369-db16123f-3ec0-4324-8c75-611ea85e4de1.png)
TRANSFORMED
![transformed](https://user-images.githubusercontent.com/15044488/180911383-b2cc6273-f386-4a6f-a5ed-30aba723abc8.jpeg)
RE-TRANSFORMED
![re-transformed](https://user-images.githubusercontent.com/15044488/180911393-df359880-e6a7-40da-a3b7-12b0a9aa7874.jpeg)

Thank you.

**Comment by lovell** [comment]
Hi, the original image is PNG, a format this is always lossless. The code you've provided will convert this to a JPEG, a format that is always lossy. Is there a reason for the format conversion?

**Comment by lovell** [comment]
Encoding as a JPEG is lossy, re-encoding a JPEG is lossy, so you're seeing the effects of two lossy passes over the image.

I would imagine that for this particular image, lossless PNG could produce a smaller file size, especially if you use palette-based output.

**Comment by ktjd123** [comment]
Hi,

I didn't know it reduces quality even with same quality factor.

Thank you for your help :)
