### ISSUE TITLE
Gatsby Build Error.

### ISSUE THREAD

**Issue by cy920820** [lovell/sharp#3311]
The compilation is normal under Mac OS system, and the compilation error is reported under Linux x64 system.

Specific error information:

![image](https://user-images.githubusercontent.com/21211512/181507607-f1c56201-05f5-4d00-b6a2-b2520ae3fee7.png)

My env info:

```js
{
  node: '15.6.0',
  v8: '8.6.395.17-node.23',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '88',
  nghttp2: '1.42.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1i',
  cldr: '38.0',
  icu: '68.1',
  tz: '2020b',
  unicode: '13.0'
}

```

```tree

├─┬ gatsby-plugin-manifest@3.14.0
│ └── sharp@0.29.3
├─┬ gatsby-plugin-sharp@3.14.3
│ └── sharp@0.29.3 deduped
└─┬ gatsby-transformer-sharp@3.14.0
  └── sharp@0.29.3 deduped
```

**Comment by lovell** [comment]
>   node: '15.6.0',

Node.js 15 reached end-of-live over a year ago, please upgrade.

> ├─┬ gatsby-plugin-manifest@3.14.0
│ └── sharp@0.29.3
├─┬ gatsby-plugin-sharp@3.14.3
│ └── sharp@0.29.3 deduped
└─┬ gatsby-transformer-sharp@3.14.0
  └── sharp@0.29.3 deduped

These are all out of date, please upgrade.

Finally, it looks like you're using sharp with a globally-installed libvips that has been compiled without support for WebP.

**Comment by cy920820** [comment]
> Finally, it looks like you're using sharp with a globally-installed libvips that has been compiled without support for WebP.

How should I operate it, because it is built automatically in the distribution machine， thx~~

**Comment by cy920820** [comment]
> > node: '15.6.0',
> 
> Node.js 15 reached end-of-life (EOL) over a year ago, please upgrade.
> 
> > ├─┬ gatsby-plugin-manifest@3.14.0
> > │ └── sharp@0.29.3
> > ├─┬ gatsby-plugin-sharp@3.14.3
> > │ └── sharp@0.29.3 deduped
> > └─┬ gatsby-transformer-sharp@3.14.0
> > └── sharp@0.29.3 deduped
> 
> These are all out of date, please upgrade.
> 
> Finally, it looks like you're using sharp with a globally-installed libvips that has been compiled without support for WebP.
In fact, the node version on the distribution machine is v12.22.10

**Comment by cy920820** [comment]
I just tested it on a Ubuntu machine, and it can be successfully built， gatsby info：

```md
System:
    OS: Linux 4.15 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (1) x64 Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.22.12 - /tmp/yarn--1659015785634-0.16321256410208718/node
    Yarn: 1.22.19 - /tmp/yarn--1659015785634-0.16321256410208718/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v12.22.12/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    gatsby: ^3.6.2 => 3.14.6
    gatsby-image: ^3.8.0 => 3.11.0
    gatsby-plugin-gatsby-cloud: ^2.6.1 => 2.11.0
    gatsby-plugin-image: ^1.6.0 => 1.14.2
    gatsby-plugin-manifest: ^3.6.0 => 3.14.0
    gatsby-plugin-offline: ^4.6.0 => 4.14.0
    gatsby-plugin-react-helmet: ^4.6.0 => 4.14.0
    gatsby-plugin-react-i18next: 1.2.3 => 1.2.3
    gatsby-plugin-sharp: ^3.8.0 => 3.14.3
    gatsby-plugin-stylus: ^3.8.0 => 3.14.0
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-filesystem: ^3.6.0 => 3.14.0
    gatsby-transformer-sharp: ^3.8.0 => 3.14.0
```

**Comment by lovell** [comment]
> How should I operate it, because it is built automatically in the distribution machine

https://sharp.pixelplumbing.com/install#building-from-source

> This module will be compiled from source at `npm install` time when:
> a globally-installed libvips is detected (set the `SHARP_IGNORE_GLOBAL_LIBVIPS` environment variable to skip this),

**Comment by cy920820** [comment]
Thank the author for his patience in answering this question. Thank you~~~~~~

But I have another question. What do you mean by not supporting webp?

**Comment by cy920820** [comment]
```js
    {
      resolve: `gatsby-plugin-sharp`,
      options: {
        formats: [`auto`],
        placeholder: `dominantColor`,
        quality: 50,
        breakpoints: [750, 1080, 1366, 1920],
        backgroundColor: `transparent`,
        tracedSVGOptions: {},
        blurredOptions: {},
        jpgOptions: {},
        pngOptions: {},
        webpOptions: {},
        avifOptions: {},
      }
    },

```
Remove webp from the formats configuration?

**Comment by cy920820** [comment]
I see. You mean the global one doesn't support it, right？

**Comment by lovell** [comment]
Yes, it looks like the globally-installed libvips was compiled without libwebp.

**Comment by cy920820** [comment]
Lovell bro, I've solved it. Thank you  very much. Then I'll close this issue.
