### ISSUE TITLE
Unable to install libvips

### ISSUE THREAD

**Issue by ZAurele** [lovell/sharp#3314]
When setting up my project I get the following error (see attached file for more details):

`npm ERR! code 1
npm ERR! path ...\node_modules\cordova-res\node_modules\sharp
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c C:\Users\myuser\AppData\Local\Temp\install-cb92a308.cmd
npm ERR! sharp: Downloading https://npmmirror.com/mirrors/sharp-libvips/v8.11.3/libvips-8.11.3-win32-x64.tar.br
npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! sharp: Installation error: tunneling socket could not be established, cause=read ECONNRESET`

I am using a compagny network under a proxy which is configured in .npmrc using proxy and https-proxy configurations which works fine for other npm packages.

I have tried adding sharp_libvips_local_prebuilds=libvips-8.11.3-win32-x64.tar.br has described in the following link

https://sharp.pixelplumbing.com/install#custom-libvips

But it does not work. However i am not sure where to put the libvips-8.11.3-win32-x64.tar.br file, the documentation is not really clear about it.

[sharp.txt](https://github.com/lovell/sharp/files/9231380/sharp.txt)

**Comment by lovell** [comment]
Hello, the installation issue template appears to have been ignored and/or deleted. Please open a new installation issue and provide answers to all of the questions.

https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md

**Comment by ZAurele** [comment]
The template is in the attached file: sharp.txt. 

But ok I'll open a new installation issue.

**Comment by lovell** [comment]
Thanks, I hadn't seen that, please see https://github.com/lovell/sharp/issues/3051 - this will be a misconfigured proxy.

If you want to use local prebuilds, please ensure you're using the latest version of sharp (cordova-res does not).
