### ISSUE TITLE
Different colours for horizontal and vertical fills when resizing images

### ISSUE THREAD

**Issue by SchneeHertz** [lovell/sharp#3315]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What are the steps to reproduce?
When I resize two different images, I find that the horizontal and vertical fill colours are different, only if the background colour alpha value is not 1

```
sharp(tempCoverPath)
  .resize(500, 707, {
    fit: 'contain',
    background: {r:0,g:255,b:0,alpha:0.2}
  })
  .toFile(coverPath)
```

### Please provide sample image(s) that help explain this problem

![](https://p.sda1.dev/6/ddc6258232099970fdb2713a567d9cc3/Snipaste_2022-08-01_15-38-38.png)

**Comment by lovell** [comment]
JPEG does not support an alpha channel, whereas PNG does. If you want to set a value for the alpha channel, please ensure the output format supports this.

**Comment by SchneeHertz** [comment]
> JPEG does not support an alpha channel, whereas PNG does. If you want to set a value for the alpha channel, please ensure the output format supports this.

Thank you for the answer, I understand
