### ISSUE TITLE
Unable to install libvips

### ISSUE THREAD

**Issue by ZAurele** [lovell/sharp#3316]
When setting up my project I get the following error (see attached file for more details):

```
npm ERR! code 1 
npm ERR! path ...\node_modules\cordova-res\node_modules\sharp 
npm ERR! command failed 
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c C:\Users\myuser\AppData\Local\Temp\install-cb92a308.cmd 
npm ERR! sharp: Downloading https://npmmirror.com/mirrors/sharp-libvips/v8.11.3/libvips-8.11.3-win32-x64.tar.br 
npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies 
npm ERR! sharp: Installation error: tunneling socket could not be established, cause=read ECONNRESET
```

I am using a compagny network under a proxy which is configured in .npmrc using proxy and https-proxy configurations which works fine for other npm packages.

I have tried adding sharp_libvips_local_prebuilds=libvips-8.11.3-win32-x64.tar.br has described in the following link

https://sharp.pixelplumbing.com/install#custom-libvips

But it does not work. However i am not sure where to put the libvips-8.11.3-win32-x64.tar.br file, the documentation is not really clear about it.

## Possible install-time or require-time problem

- [X] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [X] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

- [X] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

**yes, using 0.30.7**

### Is this a problem with filesystem permissions?

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag? 

**I am using npm 8.15.1 but i tried using --unsafe-perm**

If you are using npm v7 or later, does the user running `npm install` own the directory it is run in? 

**yes**

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

**yes**

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   '--foreground-scripts',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@8.5.5
npm info using node@v16.15.0
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 2ms
npm timing config:load:builtin Completed in 2ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:C:\Git\test\.npmrc Completed in 1ms
npm timing config:load:project Completed in 3ms
npm timing config:load:file:C:\Users\myuser-adm\.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:C:\Users\myuser-adm\AppData\Roaming\npm\etc\npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 2ms
npm timing config:load:credentials Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 14ms
npm timing npm:load:configload Completed in 14ms
npm timing npm:load:setTitle Completed in 0ms
npm timing config:load:flatten Completed in 2ms
npm timing npm:load:display Completed in 17ms
npm verb logfile C:\Users\myuser-adm\AppData\Local\npm-cache\_logs\2022-07-31T19_04_47_746Z-debug-0.log
npm timing npm:load:logFile Completed in 5ms
npm timing npm:load:timers Completed in 0ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load Completed in 39ms
npm timing arborist:ctor Completed in 0ms
npm timing arborist:ctor Completed in 0ms
npm timing idealTree:init Completed in 9ms
npm timing idealTree:userRequests Completed in 2ms
npm http fetch GET 200 https://registry.npmjs.org/sharp 92ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color 81ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tar-fs 91ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/semver 94ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 100ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/node-addon-api 103ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/simple-get 103ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/prebuild-install 137ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tunnel-agent 204ms (cache hit)
npm timing idealTree:#root Completed in 310ms
npm http fetch GET 200 https://registry.npmjs.org/expand-template 91ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color-string 120ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/pump 121ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/minimist 123ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/github-from-package 133ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/chownr 134ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/once 137ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tar-stream 137ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/mkdirp-classic 142ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/simple-concat 142ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/safe-buffer 142ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/node-abi 145ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/rc 147ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/napi-build-utils 149ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/decompress-response 150ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color-convert 157ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/lru-cache 154ms (cache hit)
npm timing idealTree:node_modules/sharp Completed in 172ms
npm http fetch GET 200 https://registry.npmjs.org/color-name 59ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle 93ms (cache hit)
npm timing idealTree:node_modules/color Completed in 98ms
npm timing idealTree:node_modules/color-convert Completed in 2ms
npm timing idealTree:node_modules/color-name Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 69ms (cache hit)
npm timing idealTree:node_modules/color-string Completed in 73ms
npm timing idealTree:node_modules/detect-libc Completed in 1ms
npm timing idealTree:node_modules/node-addon-api Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/deep-extend 70ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/ini 72ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/strip-json-comments 76ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/end-of-stream 86ms (cache hit)
npm timing idealTree:node_modules/prebuild-install Completed in 93ms
npm timing idealTree:node_modules/expand-template Completed in 0ms
npm timing idealTree:node_modules/github-from-package Completed in 0ms
npm timing idealTree:node_modules/minimist Completed in 0ms
npm timing idealTree:node_modules/mkdirp-classic Completed in 0ms
npm timing idealTree:node_modules/napi-build-utils Completed in 0ms
npm timing idealTree:node_modules/node-abi Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/wrappy 74ms (cache hit)
npm timing idealTree:node_modules/pump Completed in 78ms
npm timing idealTree:node_modules/end-of-stream Completed in 0ms
npm timing idealTree:node_modules/once Completed in 1ms
npm timing idealTree:node_modules/rc Completed in 2ms
npm timing idealTree:node_modules/deep-extend Completed in 0ms
npm timing idealTree:node_modules/ini Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/yallist 69ms (cache hit)
npm timing idealTree:node_modules/semver Completed in 72ms
npm timing idealTree:node_modules/lru-cache Completed in 1ms
npm http fetch GET 200 https://registry.npmjs.org/mimic-response 67ms (cache hit)
npm timing idealTree:node_modules/simple-get Completed in 70ms
npm timing idealTree:node_modules/decompress-response Completed in 1ms
npm timing idealTree:node_modules/mimic-response Completed in 0ms
npm timing idealTree:node_modules/simple-concat Completed in 0ms
npm timing idealTree:node_modules/simple-swizzle Completed in 1ms
npm timing idealTree:node_modules/is-arrayish Completed in 0ms
npm timing idealTree:node_modules/strip-json-comments Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/bl 74ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/fs-constants 75ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/inherits 75ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/readable-stream 89ms (cache hit)
npm timing idealTree:node_modules/tar-fs Completed in 96ms
npm timing idealTree:node_modules/chownr Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/util-deprecate 67ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/string_decoder 69ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/buffer 70ms (cache hit)
npm timing idealTree:node_modules/tar-stream Completed in 75ms
npm http fetch GET 200 https://registry.npmjs.org/base64-js 68ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/ieee754 69ms (cache hit)
npm timing idealTree:node_modules/bl Completed in 72ms
npm timing idealTree:node_modules/buffer Completed in 2ms
npm timing idealTree:node_modules/base64-js Completed in 0ms
npm timing idealTree:node_modules/fs-constants Completed in 0ms
npm timing idealTree:node_modules/ieee754 Completed in 0ms
npm timing idealTree:node_modules/inherits Completed in 0ms
npm timing idealTree:node_modules/readable-stream Completed in 2ms
npm timing idealTree:node_modules/string_decoder Completed in 2ms
npm timing idealTree:node_modules/safe-buffer Completed in 0ms
npm timing idealTree:node_modules/tunnel-agent Completed in 0ms
npm timing idealTree:node_modules/util-deprecate Completed in 0ms
npm timing idealTree:node_modules/wrappy Completed in 0ms
npm timing idealTree:node_modules/yallist Completed in 0ms
npm timing idealTree:buildDeps Completed in 1258ms
npm timing idealTree:fixDepFlags Completed in 1ms
npm timing idealTree Completed in 1274ms
npm timing reify:loadTrees Completed in 1275ms
npm timing reify:diffTrees Completed in 1ms
npm timing reify:retireShallow Completed in 0ms
npm timing reify:createSparse Completed in 10ms
npm timing reify:loadBundles Completed in 0ms
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm http fetch POST 426 http://registry.npmjs.org/-/npm/v1/security/advisories/bulk 71ms
npm timing reifyNode:node_modules/chownr Completed in 125ms
npm timing reifyNode:node_modules/strip-json-comments Completed in 126ms
npm timing reifyNode:node_modules/wrappy Completed in 127ms
npm timing reifyNode:node_modules/ini Completed in 127ms
npm timing reifyNode:node_modules/once Completed in 128ms
npm timing reifyNode:node_modules/end-of-stream Completed in 129ms
npm timing reifyNode:node_modules/mkdirp-classic Completed in 129ms
npm timing reifyNode:node_modules/simple-swizzle Completed in 130ms
npm timing reifyNode:node_modules/color-name Completed in 131ms
npm timing reifyNode:node_modules/color-string Completed in 131ms
npm timing reifyNode:node_modules/lru-cache Completed in 133ms
npm timing reifyNode:node_modules/tunnel-agent Completed in 134ms
npm timing reifyNode:node_modules/color Completed in 135ms
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm http fetch POST 426 http://registry.npmjs.org/-/npm/v1/security/audits/quick 63ms
npm verb audit error HttpErrorGeneral: 426 Upgrade Required - POST http://registry.npmjs.org/-/npm/v1/security/audits/quick
npm verb audit error     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\lib\check-response.js:104:15
npm verb audit error     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm verb audit error     at async Map.[getReport] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\audit-report.js:336:21)
npm verb audit error     at async Map.run (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\audit-report.js:106:19)
npm verb audit error  HttpErrorGeneral: 426 Upgrade Required - POST http://registry.npmjs.org/-/npm/v1/security/audits/quick
npm verb audit error     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\lib\check-response.js:104:15
npm verb audit error     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm verb audit error     at async Map.[getReport] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\audit-report.js:336:21)
npm verb audit error     at async Map.run (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\audit-report.js:106:19) {
npm verb audit error   headers: [Object: null prototype] {
npm verb audit error     date: [ 'Sun, 31 Jul 2022 19:04:49 GMT' ],
npm verb audit error     'content-type': [ 'text/plain' ],
npm verb audit error     'content-length': [ '271' ],
npm verb audit error     'npm-notice': [
npm verb audit error       'Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/'
npm verb audit error     ],
npm verb audit error     vary: [ 'Accept-Encoding' ],
npm verb audit error     server: [ 'cloudflare' ],
npm verb audit error     'cf-ray': [ '73389a1cc960734a-MRS' ],
npm verb audit error     'cache-control': [ 'proxy-revalidate' ],
npm verb audit error     connection: [ 'close' ],
npm verb audit error     'x-fetch-attempts': [ '1' ]
npm verb audit error   },
npm verb audit error   statusCode: 426,
npm verb audit error   code: 'E426',
npm verb audit error   method: 'POST',
npm verb audit error   uri: 'http://registry.npmjs.org/-/npm/v1/security/audits/quick',
npm verb audit error   body: <Buffer 42 65 67 69 6e 6e 69 6e 67 20 4f 63 74 6f 62 65 72 20 34 2c 20 32 30 32 31 2c 20 61 6c 6c 20 63 6f 6e 6e 65 63 74 69 6f 6e 73 20 74 6f 20 6e 70 6d 20 ... 221 more bytes>,
npm verb audit error   pkgid: undefined
npm verb audit error }
npm timing auditReport:getReport Completed in 158ms
npm timing reify:audit Completed in 158ms
npm timing reifyNode:node_modules/string_decoder Completed in 155ms
npm timing reifyNode:node_modules/inherits Completed in 158ms
npm timing reifyNode:node_modules/ieee754 Completed in 159ms
npm timing reifyNode:node_modules/fs-constants Completed in 162ms
npm timing reifyNode:node_modules/decompress-response Completed in 162ms
npm timing reifyNode:node_modules/mimic-response Completed in 163ms
npm timing reifyNode:node_modules/yallist Completed in 165ms
npm timing reifyNode:node_modules/napi-build-utils Completed in 166ms
npm timing reifyNode:node_modules/safe-buffer Completed in 168ms
npm timing reifyNode:node_modules/is-arrayish Completed in 169ms
npm timing reifyNode:node_modules/util-deprecate Completed in 171ms
npm timing reifyNode:node_modules/base64-js Completed in 172ms
npm timing reifyNode:node_modules/expand-template Completed in 173ms
npm timing reifyNode:node_modules/simple-concat Completed in 177ms
npm timing reifyNode:node_modules/deep-extend Completed in 177ms
npm timing reifyNode:node_modules/detect-libc Completed in 179ms
npm timing reifyNode:node_modules/pump Completed in 181ms
npm timing reifyNode:node_modules/buffer Completed in 183ms
npm timing reifyNode:node_modules/color-convert Completed in 183ms
npm timing reifyNode:node_modules/simple-get Completed in 183ms
npm timing reifyNode:node_modules/tar-stream Completed in 187ms
npm timing reifyNode:node_modules/bl Completed in 197ms
npm timing reifyNode:node_modules/rc Completed in 201ms
npm timing reifyNode:node_modules/github-from-package Completed in 202ms
npm timing reifyNode:node_modules/node-abi Completed in 203ms
npm timing reifyNode:node_modules/prebuild-install Completed in 209ms
npm timing reifyNode:node_modules/tar-fs Completed in 219ms
npm timing reifyNode:node_modules/minimist Completed in 221ms
npm timing reifyNode:node_modules/node-addon-api Completed in 224ms
npm timing reifyNode:node_modules/readable-stream Completed in 231ms
npm timing reifyNode:node_modules/sharp Completed in 252ms
npm timing reifyNode:node_modules/semver Completed in 257ms
npm timing reify:unpack Completed in 259ms
npm timing reify:unretire Completed in 0ms
npm timing build:queue Completed in 2ms
npm timing build:link:node_modules/semver Completed in 6ms
npm timing build:link:node_modules/rc Completed in 6ms
npm timing build:link:node_modules/prebuild-install Completed in 7ms
npm timing build:link Completed in 7ms
npm info run sharp@0.30.7 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
sharp: Installation error: tunneling socket could not be established, cause=read ECONNRESET install/libvips && node install/dll-copy && p
npm info run sharp@0.30.7 install { code: 1, signal: null }
npm timing reify:rollback:createSparse Completed in 44ms
npm timing reify:rollback:retireShallow Completed in 1ms
npm timing command:install Completed in 1902ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
npm verb stack     at ChildProcess.emit (node:events:527:28)
npm verb stack     at maybeClose (node:internal/child_process:1092:16)
npm verb stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm verb pkgid sharp@0.30.7
npm verb cwd C:\Git\test
npm verb Windows_NT 10.0.19044
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose" "--foreground-scripts" "sharp"
npm verb node v16.15.0
npm verb npm  v8.5.5
npm ERR! code 1
npm ERR! path C:\Git\test\node_modules\sharp
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm verb exit 1
npm timing npm Completed in 2166ms
npm verb unfinished npm timer reify 1659294288004
npm verb unfinished npm timer reify:build 1659294289563
npm verb unfinished npm timer build 1659294289563
npm verb unfinished npm timer build:deps 1659294289563
npm verb unfinished npm timer build:run:install 1659294289573
npm verb unfinished npm timer build:run:install:node_modules/sharp 1659294289574
npm verb code 1

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

<details>
  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
    Memory: 2.63 GB / 31.72 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
</details>

**Comment by lovell** [comment]
I've provided an answer at #3314

**Comment by lovell** [comment]
Closing as an answer was provided at #3314
