### ISSUE TITLE
Errors thrown by C++ component of sharp are not instances of Error class.

### ISSUE THREAD

**Issue by PizzaPartyInc** [lovell/sharp#3317]
### Is this a possible bug in a feature of sharp, unrelated to installation? - Yes

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp? - Yes, 0.30.7 at a time of checking

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?
```
npx: installed 1 in 1.4s

  System:
    OS: Windows 10 10.0.19044
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 14.84 GB / 31.86 GB
  Binaries:
    Node: 14.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
```

### What are the steps to reproduce?

- Make sharp produce one of the errors from C++ component. (e.g. try to get metadata from an empty file)
- catch an error
- evaluate expression `error instanceof Error` - it is false.

### What is the expected behaviour?

Expected evaluation of `error instanceof Error` for all errors thrown by `sharp` to be true.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```ts
import { resolve } from 'path';
import { createReadStream } from 'fs';
import sharp from 'sharp';

try {
  const filename = 'empty_image.bmp';
  const fileLocation = resolve(__dirname, filename);
  const readStream = createReadStream(fileLocation);

  const src = readStream.pipe(sharp());
  const getMetadata = await src.metadata();
  console.log(getMetadata); // this is just a line for a breakpoint that will not be hit, to make sure that line above fails
} catch (error) {
  const comparisonError = new Error(
    'Input buffer contains unsupported image format',
  );
  console.log(comparisonError instanceof Error); // true
  console.log(error instanceof Error); // false
}
```
If I debug the code above and put a breakpoint on one of the `console.log` calls inside of the catch and observe `error` and `comparisonError` in the `Watch` window (VScode) - I will see something like this:

![image](https://user-images.githubusercontent.com/37663061/182130044-78c0e8ee-780b-48ef-a66b-9536a477560b.png)

Both errors are nearly identical, so it would make sense for Error produced by `sharp` to also be evaluated as Error. When handling errors, evaluation `instanceof Error` is handy to make sure a component did not throw a string or a random object. In this case, such evaluation fails and a workaround like this is needed (e.g. if there is a dedicated error handling approach in the app and we want to produce more human-friendly errors):

```ts
    const assumedError = error as { message?: string; stack?: string };
    if ('message' in assumedError && 'stack' in assumedError) {
      const wrapper = new Error(assumedError.message);
      wrapper.stack = assumedError.stack;
      error = wrapper;
    }
```

### Please provide sample image(s) that help explain this problem

In test above, I was using an empty file, which is impossible to attach. So, just create a new text file and rename it to `empty_image.bmp`

**Comment by lovell** [comment]
The appearance of `__BluebirdErrorTypes__` as a property of `comparisonError` suggests you're using some kind of testing framework that is modifying the `Error` prototype, possibly via a call to `vm.runInNewContext`, but the `Error` returned/thrown by sharp will be "pure" and not modified in this manner.

**Comment by PizzaPartyInc** [comment]
I'll try to research this `__BluebirdErrorTypes__` a bit more. The screenshot above was made when I was debugging the code in the context of Jest test. I tried to debug this again during the actual app runtime, and now I see that in both cases they are recognized as instances of Error, and both have `__BluewbirdErrorTypes__`...
![image](https://user-images.githubusercontent.com/37663061/182154028-5096deed-aa89-4508-8bc9-59738057e083.png)

So, I guess it's not that it's a test framework modifying error prototype, it's that something is missing during jest tests execution which is not modifying the prototype of some errors (to make instanceof check work)? Really weird...

Either way, Thanks for the quick response and for pointing me in the right direction! :)

**Comment by lovell** [comment]
Jest runs tests in their own context via `vm.runInNewContext()`.

https://nodejs.org/api/vm.html

> This means invoked code has a different global object than the invoking code.

An `Error` from one context cannot be compared with an `Error` from another context.

**Comment by PizzaPartyInc** [comment]
And apparently, this is a very old Jest issue.... https://github.com/facebook/jest/issues/2549

Thanks again for the help )

**Comment by PizzaPartyInc** [comment]
Managed to resolve by adding a dev dependency `jest-environment-node-single-context` (of the version that matches the major version of jest) and overriding the default jest environment in a test file that had wron instanceof evaluation, by adding the following comment on top of the test file:
```
/**
 * @jest-environment jest-environment-node-single-context
 */
```
