### ISSUE TITLE
SVG does not render paths or text with feDropShadow

### ISSUE THREAD

**Issue by JohnCido** [lovell/sharp#3318]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?
  System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
    Memory: 5.40 GB / 7.73 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.0.0 - /home/linuxbrew/.linuxbrew/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 8.6.0 - /home/linuxbrew/.linuxbrew/bin/npm
  npmPackages:
    sharp: ^0.30.7 => 0.30.7 

### What are the steps to reproduce?
Resize this SVG: https://dev.image.cdn.connect3.world/a4f57310ce27ace3ce09322942a462d8.svg to any smaller size like 64:
https://dev.image.cdn.connect3.world/a4f57310ce27ace3ce09322942a462d8.svg?w=64&h=64
This is a CDN used by us that uses sharp, it might not be the latest version of sharp, but we're also using sharp on our website API to generate open graph images. **The same thing happens on our server side.** And we're using the latest sharp on the server.

### What is the expected behaviour?
Resized output with also the shapes and texts.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem
This is the code we use on our server:
```js
const image = sharp(buffer, {
  animated: false,
}).resize(width, height, {
  fit: 'cover',
  ...options,
})
```

### Please provide sample image(s) that help explain this problem
![image](https://user-images.githubusercontent.com/7105485/182561840-71987004-d3eb-44f7-83ca-0d4b2f27b88a.png)
![image](https://user-images.githubusercontent.com/7105485/182561882-7f0e63d6-2f89-40e8-8a1f-be02c001d424.png)

**Comment by lovell** [comment]
`feDropShadow` is unsupported, please see #1490.
