### ISSUE TITLE
How do I "reconfigure" libvips after adding missing libgsf-1 ?

### ISSUE THREAD

**Issue by sb3d** [lovell/sharp#332]
I used your preinstall.sh to install libvips on a centos6.7 i686 server and that went very smoothly but there was no libgsf-1 installed, therefore vips dzsave does not work. In issue 141 the answer to a similar situation was "Make sure you have libgsf-1-dev and try configure again." I've subsequently installed libgsf-1 (1.14.30). Now how do I "reconfigure" libvips? There are some gaps in my learning about make etc. Thank you! -Steve

**Comment by lovell** [comment]
Hello, `libgsf-1-dev` is the package name for Debian-based systems. For Centos the package name is `libgsf-devel` which the preinstall script *should* install for you before compiling libvips - see https://github.com/lovell/sharp/blob/master/preinstall.sh#L249

To manually uninstall libvips, you'll need to download and extract the source from http://www.vips.ecs.soton.ac.uk/supported/8.2/ then run the following commands:

```sh
cd vips-8.2.0
./configure
sudo make uninstall
sudo ldconfig
```

You can then run the preinstall script again to reinstall.

Hope this helps!

(Use of sharp with Centos 7 does not require use of the preinstall script as it downloads pre-compiled binaries at `npm install` time.)

**Comment by sb3d** [comment]
Thanks for the explanation but vips-8.2.0 remains after the uninstall. I have a couple guesses about what to do.

Here's history of the uninstall (I'm doing this as root so 'sudo' is moot):
 1001  2016-01-06 09:20:16 wget http://www.vips.ecs.soton.ac.uk/supported/8.2/vips-8.2.0.tar.gz
 1002  2016-01-06 09:20:30 ls
 1003  2016-01-06 09:22:10 tar -xf vips-8.2.0.tar.gz
 1004  2016-01-06 09:22:14 ls
 1005  2016-01-06 09:22:30 cd vips-8.2.0
 1006  2016-01-06 09:22:38 ./configure
 1007  2016-01-06 09:23:21 sudo make uninstall
 1008  2016-01-06 09:23:31 sudo ldconfig

I then ran preinstall.sh and it stopped right away reporting:
Found libvips 8.2.0

A find finds 'vips' in /usr/include/
root@server [~/sb/tmp]# find / -iname vips
/root/sb/tmp/vips-8.2.0/cplusplus/include/vips
/root/sb/tmp/vips-8.2.0/libvipsCC/include/vips
/root/sb/tmp/vips-8.2.0/libvipsCC/include/vips/vips
/root/sb/tmp/vips-8.2.0/libvips/include/vips
/usr/include/vips
/usr/include/vips/vips

Is this helpful?
ldconfig -v | grep vips
        libvips-cpp.so.42 -> libvips-cpp.so.42.2.0
        libvipsCC.so.42 -> libvipsCC.so.42.2.0
        libvips.so.42 -> libvips.so.42.2.0

ls /usr/lib/pkgconfig | grep vips
vipsCC.pc
vips-cpp.pc
vips.pc

Not sure I can remove those files without causing trouble. FYI, I came across comments about using checkinstall to keep track of all files installed by a make install. 

If I remove or rename those vips files in /usr/lib/pkgconfig and re-run your preinstall.sh presumably that would replace them. Do you see any red flags in that scenario?

What if I used a modified version of your script changing lines 100, 101 to skip check_if_library_exists and to set vips_exists = 0?

Thanks again.

**Comment by lovell** [comment]
Ah, sorry, this is Centos so we'll need to pass the installation location to the configure script by using `./configure --prefix=/usr`

Given you're re-installing the same version and have got this far, it'll probably be quicker to replace `make uninstall` with `make install` and let it overwrite existing files.

(I think `checkinstall` is a Debian thing rather than a Centos/RedHat thing.)

**Comment by sb3d** [comment]
Fabulous! After doing configure --prefix=/usr and make install, vips dzsave is working.
Thanks again for this Q&A and for providing the script in the first place.

**Comment by demepty** [comment]
Hello,
I have the same problem, unlike my extension does not work (jpg, png, tiff).
My console.log (sharp.format) shows this: 

{ jpeg:
{ id: 'jpeg',
input: { file: false, buffer: false, stream: false },
 output: { file: false, buffer: false, stream: false } },
png:
{ id: 'png',
input: { file: false, buffer: false, stream: false },
 output: { file: false, buffer: false, stream: false } },
webp:
 { id: 'webp',
input: { file: false, buffer: false, stream: false },
 output: { file: false, buffer: false, stream: false } },
tiff:
{ id: 'tiff',
input: { file: false, buffer: false, stream: false },
 output: { file: false, buffer: false, stream: false } },
 magick:
{ id: 'magick',
input: { file: false, buffer: false, stream: false },
output: { file: false, buffer: false, stream: false } },
openslide:
 { id: 'openslide',
 input: { file: false, buffer: false, stream: false },
 output: { file: false, buffer: false, stream: false } },
dz:
 { id: 'dz',
 input: { file: false, buffer: false, stream: false },
output: { file: false, buffer: false, stream: false } },
ppm:
{ id: 'ppm',
 input: { file: true, buffer: false, stream: false },
 output: { file: true, buffer: false, stream: false } },
fits:
 { id: 'fits',
 input: { file: false, buffer: false, stream: false },
output: { file: false, buffer: false, stream: false } },
 gif:
 { id: 'gif',
 input: { file: false, buffer: false, stream: false },
output: { file: false, buffer: false, stream: false } },
svg:
{ id: 'svg',
input: { file: false, buffer: false, stream: false },
output: { file: false, buffer: false, stream: false } },
pdf:
{ id: 'pdf',
 input: { file: false, buffer: false, stream: false },
output: { file: false, buffer: false, stream: false } },
 v:
{ id: 'v',
 input: { file: false, buffer: false, stream: false },
 output: { file: false, buffer: false, stream: false } },
raw:
{ id: 'raw',
 input: { file: false, buffer: true, stream: true },
 output: { file: false, buffer: true, stream: true } } }

The version of lipvibs 8.7.1, followed the steps mentioned and I can not make it work.
After the ./configure --prefix = / usr these data are shown:

* build options
native win32:                           no
native OS X:                            no
open files in binary mode:              no
enable debug:                           no
enable deprecated library components:   yes
enable docs with gtkdoc:                no
gobject introspection:                  no
enable vips7 C++ API:                   no (default)
enable vips7 Python binding:            no (default)
enable vips8 Python overrides:          no (default)
  (requires pygobject-3.13.0 or later)
enable radiance support:                yes
enable analyze support:                 yes
enable PPM support:                     yes

* optional dependencies
use fftw3 for FFT:                      no
Magick package:                         none
Magick API version:                     none
load with libMagick:                    no
save with libMagick:                    no
accelerate loops with orc:              no
  (requires orc-0.4.11 or later)
ICC profile support with lcms:          no
file import with niftiio:               no
file import with OpenEXR:               no
file import with OpenSlide:             no
  (requires openslide-3.3.0 or later)
file import with matio:                 no
PDF import with PDFium                  no
PDF import with poppler-glib:           no
  (requires poppler-glib 0.16.0 or later)
SVG import with librsvg-2.0:            no
  (requires librsvg-2.0 2.34.0 or later)
zlib:                                   no
file import with cfitsio:               no
file import/export with libwebp:        no
  (requires libwebp-0.1.3 or later)
support webp metadata:
  (requires libwebpmux-0.5 or later)
text rendering with pangoft2:           no
file import/export with libpng:         no
  (requires libpng-1.2.9 or later)
support 8bpp PNG quantisation:          no
  (requires libimagequant)
file import/export with libtiff:        no
file import/export with giflib:         no
file import/export with libjpeg:        no
image pyramid export:                   no
  (requires libgsf-1 1.14.26 or later)
use libexif to load/save JPEG metadata: no


Could you help me??
