### ISSUE TITLE
can't get any errors and the process crashes directly

### ISSUE THREAD

**Issue by shawon1220** [lovell/sharp#3324]
Most of the svg to png can work normally, but the following svg can't get any errors and the process crashes directly. Please help what happened, thank you.

I  can't get any errors from try catch or callback...

My code:
sharp(svgPath, {limitInputPixels: false }).toFile(pngPath).then(()=>{...}).catch((err)=>{...})

[topsvg.zip](https://github.com/lovell/sharp/files/9276176/topsvg.zip)

**Comment by lovell** [comment]
With the `limitInputPixels` safety feature off, the `viewBox="-10000 0 170000 150000"` on this image means it will attempt to render at 180000x150000 so ensure you have enough memory for the complete RGBA image, which will be at least 108 GB of RAM (180000x150000x4).

**Comment by shawon1220** [comment]
Thanks, After I upload to the server, it works normally, maybe my local performance is limited.
