### ISSUE TITLE
png({quality:100}) get different size of output file with png().

### ISSUE THREAD

**Issue by Mrluobo** [lovell/sharp#3325]
## Question about an existing feature
png output question
### What are you trying to achieve?
i think the two output will get same file size.because the default quality value is 100

### When you searched for similar issues, what did you find that might be related?

no

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```
sharp(path.resolve(__dirname, '../source/test.png'))
  .png()
  .toBuffer()
  .then(data => {
    fs.outputFileSync(path.resolve(__dirname, '../output/test1.png'), data, { recursive: true });
  });
sharp(path.resolve(__dirname,  '../source/test.png'))
  .png({
    quality: 100,
  })
  .toBuffer()
  .then(data => {
    fs.outputFileSync(path.resolve(__dirname, '../output/test2.png'), data, { recursive: true });
  });

```

### Please provide sample image(s) that help explain this question

the source image is:

![test](https://user-images.githubusercontent.com/9135512/183424281-75687d6f-f287-4846-b1af-b322c981354c.png)

the output image is:
![test1](https://user-images.githubusercontent.com/9135512/183424409-ed0d6b08-e25f-46ab-9b89-ed85a471af4a.png)
![test2](https://user-images.githubusercontent.com/9135512/183424433-7f605b84-55cf-4608-add0-9fcfc381d9c0.png)

hope for your help   thx

**Comment by lovell** [comment]
Hi, did you see https://sharp.pixelplumbing.com/api-output#png ?

> By default, PNG output is full colour at 8 or 16 bits per pixel. Indexed PNG input at 1, 2 or 4 bits per pixel is converted to 8 bits per pixel. Set `palette` to `true` for slower, indexed PNG output.

> `options.quality` use the lowest number of colours needed to achieve given quality, sets `palette` to `true`

When you provide a value for `quality`, you are selecting palette-based output.

**Comment by Mrluobo** [comment]
thank you so much. i miss the information, now i know it~
