### ISSUE TITLE
Composite images on Apple M1 Pro creates a broken image

### ISSUE THREAD

**Issue by Leon-Bor** [lovell/sharp#3328]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [X] Running `npm install sharp` completes without error.
- [X] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [X] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

  System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.39 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.5.2 - ~/.nvm/versions/node/v16.14.0/bin/npm
  npmPackages:
    sharp: ^0.30.7 => 0.30.7 

### What are the steps to reproduce?

1: Use an Apple M1 Pro or similar device
2: create an image with `sharp({create: { ... } })`
3: add some images with composite `sharp({create: { ... } }).composite([ ...images ]}`
3: write the image to your disk with `.toFile( ... )`

### What is the expected behaviour?

Both images should look the same.  
Please have a look at the images `output-works.png` and `output-broken.png` in the provided repo. 

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

1: Clone repo from [https://github.com/Leon-Bor/sharp-composite-images](https://github.com/Leon-Bor/sharp-composite-images)
2: run `npm i`
3: run `npm start`

### Please provide sample image(s) that help explain this problem

On my Apple M1 Pro I get the following images: 

#### output-broken.png
If I use the `sharp({ create: { ... })` the composite image looks like this.
![output-broken.png](https://github.com/Leon-Bor/sharp-composite-images/blob/6b1cc7407886650e5e4fd7e8ac2f79d6fe608f27/output-broken.png?raw=true)

#### output-works.png
If I hand in a normal image to sharp it is working well.
![output-works.png](https://github.com/Leon-Bor/sharp-composite-images/blob/6b1cc7407886650e5e4fd7e8ac2f79d6fe608f27/output-works.png?raw=true)

Another thing is, if I downgrade sharp to version 0.29.3 the problem is also gone. So both images look on version 0.29.3 the same. This problem seems to be an Apple related problem because it is not happening on windows or linux computers.

**Comment by lovell** [comment]
Given this occurs with PNG images on ARM64, my best guess would be that this is related to #3225

**Comment by lovell** [comment]
Let's track this at #3225
