### ISSUE TITLE
Optimize jpg/png images to pass Google PageSpeed Insights

### ISSUE THREAD

**Issue by pleaseshutup** [lovell/sharp#333]
I am resizing images to a number of sizes depending on the necessary size per website visitor screen size.

Google page speed insights: https://developers.google.com/speed/pagespeed/insights/ is complaining that my png images could be compressed anywhere from 8% to 50% better. 

Here is an example of what I am doing. I am uploading the original to s3 and then a task queue kicks in to take that and pipe it through sharp into a buffer to stream back up to s3:

sharp().resize(width)
.compressionLevel(6)
.withoutAdaptiveFiltering()
.toBuffer()

What I would like to do is the ideal settings for both png and jpg for images on the web. Compression/quality etc. My most important need is to figure out how to get PNG's compressed well so that pagespeed doesn't ding my on this. We are using page-speed insights as a means to market how we automatically optimize assets for our users.

**Comment by lovell** [comment]
Hello, let's focus on PNG to start with. Using `compressionLevel(9)` should help. I'd also suggest generating output with and without the use of `withoutAdaptiveFiltering()` to see which is smaller.

Page Speed Insights is probably using something like `pngcrush` under the hood. It tries combinations of compression level and row filter settings to see which produces the smallest output.

Are you able to provide an example URL we can use to work through?

**Comment by pleaseshutup** [comment]
Adding compressionLevel(9) seems to do the trick. I was confusing some cached and non cached resources when checking the differences in settings.

Thank you for taking the time to help me out.

**Comment by lovell** [comment]
No worries, glad you got it working.

**Comment by jaspersorrio** [comment]
Hey guys, using 
```
sharp().resize(width)
.compressionLevel(6)
```
got me an error where compressionLevel is not a function.. Am i missing something here?

**Comment by lovell** [comment]
@jaspersorrio `compressionLevel()` was deprecated in v0.17.0 and removed in v0.18.0 - see http://sharp.dimens.io/en/stable/changelog/

For v0.18.0+ you'll need to use the `compressionLevel` option of [png](http://sharp.dimens.io/en/stable/api-output/#png).
```javascript
sharp(input)
  .resize(width)
  .png({ compressionLevel: 6 })
  ...
```
