### ISSUE TITLE
How to build the libvips-cpp.so.42 binary in the vendor directory of sharp package?

### ISSUE THREAD

**Issue by usabe** [lovell/sharp#3330]
Hi, lovell,

I want to update my locally installed sharp package so that it could directly convert pdf to image. Based on your suggestion of re-compiling libvips from source in the page: https://github.com/lovell/sharp/issues/2008, I did that.

The method I use is mainly from the page you mentioned in the issue 2008: https://www.libvips.org/install.html#building-libvips-from-a-source-tarball. Also referred to: https://github.com/libvips/libvips/wiki/Build-for-Ubuntu, https://sharp.pixelplumbing.com/install#building-from-source. I successfully compiled the libvips from source (with both pdfium and poppler-glib installed) and tried installing them both globally and locally. But I didn't figure out how I can get the libvips binary file as the file **node_modules/sharp/vendor/8.12.2/linux-x64/lib/libvips-cpp.so.42**, which had a size of 18M+. The one I got in the **/usr/local/lib/x86_64-linux-gnu/libvips-cpp.so.42.16.0** directory is only around 360K, while the libvips.so.42.16.0 file in the same directory is only 3.8M.

The meson setup command I use is : **meson setup rootbuild --prefix=/usr/local --buildtype=release --default-library=static --libdir=lib**, also tried it without the --default-library=static option, but still didn't get the file libvips-cpp.so.42 which could replace the one in the sharp package.

Please shed some light on this issue.

Thank you!

**Comment by lovell** [comment]
Hi, sorry, you've already read all the information I might be able to link to in order to help, good luck!

**Comment by usabe** [comment]
Hi, Lovell,

Thanks for the reply. Could you please at least share with me how that vendor file libvips-cpp.so.42 is built in the sharp package?

**Comment by lovell** [comment]
https://github.com/lovell/sharp-libvips

**Comment by ansnoussi** [comment]
@usabe running into the same issue as you, have you managed to solve this ? 🤔
