### ISSUE TITLE
Rotate after composite throws "Image to composite must have same dimensions or smaller"

### ISSUE THREAD

**Issue by DanielStout5** [lovell/sharp#3333]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz
    Memory: 6.19 GB / 31.73 GB
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: 0.30.7 => 0.30.7
```

### What are the steps to reproduce?

Composite an image and then try to rotate the combined result:

```
  await sharp({
    create: {
      width: 1500,
      height: 1125,
      channels: 3,
      background: "#000",
    },
  })
    .composite([
      {
        input: img,
      },
    ])
    .rotate(90)
```

### What is the expected behaviour?

It should rotate the combined image by 90 degrees, but instead throws `Error: Image to composite must have same dimensions or smaller`, even though `img` and the created image are the exact same size.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

https://github.com/DanielStout5/SharpCompositeRotateBug

### Please provide sample image(s) that help explain this problem

Not image specific, but an image is included in the git repo above.

**Comment by lovell** [comment]
Hi, you'll need to break this into two pipelines.

  await sharp({
    create: {
      width: 1500,
      height: 1125,
      channels: 3,
      background: "#000",
    },
  })
    .composite([
      {
        input: img,
      },
    ])
    .rotate(90)
https://github.com/lovell/sharp/commit/e1bc8674fdcc2599ba199bdb97227acd496104f7

**Comment by DanielStout5** [comment]
Ah, okay, thanks for the reply - that's what I had implemented as a workaround but I assume rendering the image out to a buffer just to read it back in is somewhat inefficient.

Is there any chance of another approach being added to Sharp in the future, maybe some way to specify at what point the rotation occurs?

**Comment by lovell** [comment]
Please see the discussion at https://github.com/lovell/sharp/issues/241
