### ISSUE TITLE
WASM Support

### ISSUE THREAD

**Issue by ghostdevv** [lovell/sharp#3336]
### What are you trying to achieve?

In order for sharp to run on something like Stackblitz wasm support is needed, looking through all the various issues about it the main concern has been the lack of support from `vips` but that seems to be resolved now (https://github.com/libvips/libvips/issues/192#issuecomment-684847123)

Related: #2863 #1476 #1510 #2208 #2436

**Comment by lovell** [comment]
Hi, it looks you've already found https://github.com/kleisauke/wasm-vips - does that work for you?

**Comment by ghostdevv** [comment]
My main goal is to get it working on stackblitz, I am not 100% sure what is needed for that so asked some people who do!

**Comment by lovell** [comment]
For StackBlitz, did you see https://github.com/stackblitz/webcontainer-core/issues/147 ?

**Comment by EricSimons** [comment]
FYI on the StackBlitz side our polyfill is basically just a no-op, so having Sharp itself as a Wasm is still _very_ much needed and we'd love to help in any way we can @ghostdevv @lovell 🙏

**Comment by styfle** [comment]
There's a PR being worked on here: https://github.com/lovell/sharp/pull/3522

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/3750#issuecomment-1751172728 for details of a pre-release with Wasm support.

It probably won't work on StackBlitz yet as they are currently polyfilling sharp, but once v0.33.0 is released I suspect/hope the polyfill can be removed.

**Comment by lovell** [comment]
v0.33.0 is now available - please see https://sharp.pixelplumbing.com/install#webassembly

**Comment by 7heMech** [comment]
Has anyone managed to get it working with Cloudflare Workers, I'd love an example, thanks!

**Comment by eNkKVS4HxHc9jaq** [comment]
> v0.33.0 is now available - please see https://sharp.pixelplumbing.com/install#webassembly

Seriously? Its 32bit only? I was so excited until I found out. You should really compile to 64bit. Its 2025 now it was published in 2023 if I wanted to run something 32bit I would go back at least like 10 years

**Comment by lovell** [comment]
@eNkKVS4HxHc9jaq I assume your comment is either trolling or seriously misguided given WebAssembly didn't exist 10 years ago and, more importantly, its support for 64-bit address space was only [announced last month](https://webassembly.org/news/2025-09-17-wasm-3.0/) and consequently is not yet available in many runtimes.

**Comment by kleisauke** [comment]
@7heMech Please see #2863.

@eNkKVS4HxHc9jaq Besides its limited availability, 64-bit WebAssembly also comes with a [performance penalty](https://spidermonkey.dev/blog/2025/01/15/is-memory64-actually-worth-using.html).
