### ISSUE TITLE
npm ERR

### ISSUE THREAD

**Issue by LRT-stack** [lovell/sharp#3337]
![image](https://user-images.githubusercontent.com/68623860/185092364-c37e3f46-b951-4465-89ea-ebe764115185.png)

**Comment by cagolh** [comment]
I'm seeing the same when running `npm install` on GitaLab CI/CD. Node v14, Gatsby v4.20.0 which pulls in sharp@0.30.7. It runs successfully locally using the same version of node. Running `yarn why sharp` I can't see any other versions of sharp being pulled in:
```
=> Found "sharp@0.30.7"
info Reasons this module exists
   - "gatsby-plugin-manifest" depends on it
   - Hoisted from "gatsby-plugin-manifest#sharp"
   - Hoisted from "gatsby-plugin-sharp#sharp"
   - Hoisted from "gatsby-transformer-sharp#sharp"
   - Hoisted from "gatsby#gatsby-sharp#sharp"
 ```

**Comment by lovell** [comment]
Hello, the installation issue template appears to have been ignored and/or deleted. Please open a new installation issue and provide answers to all of the questions.

https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md
