### ISSUE TITLE
ImageMagick-style tint

### ISSUE THREAD

**Issue by shahkashani** [lovell/sharp#3338]
## Question about an existing feature

I'm pretty sure this is just me being stupid, but is there a way to use `tint` to achieve something like the below?

### ImageMagick

```convert "input.png" -fill "#c31306" -tint 100 "output.png"```

![output-im](https://user-images.githubusercontent.com/1395893/185453564-fcc08fa8-0443-4428-bc27-a56754324b56.jpg)

### Sharp

```await sharp(image).tint('#c31306')```

![output-sharp](https://user-images.githubusercontent.com/1395893/185453697-33d27e75-6e12-4557-a12c-988356250021.png)

Note how the highs and lows are also tinted in the Sharp case, but not with ImageMagick. 

The [ImageMagick source code](https://github.com/ImageMagick/ImageMagick/blob/master/MagickCore/visual-effects.c#L2972) indicates that they use a weighting function for their tinting:

```
%  TintImage() applies a color vector to each pixel in the image.  The length
%  of the vector is 0 for black and white and at its maximum for the midtones.
%  The vector weighting function is f(x)=(1-(4.0*((x-0.5)*(x-0.5))))
```

But I am not sure how to convert this into Sharp terms. Perhaps I could use `recomb` somehow?

I have even tried to use `composite`, but none of the blend modes seem to be able to achieve what I want. `multiply` gets close, but I think ultimately what I need is something like Cairo's `color` blend mode, which doesn't exist in Sharp or vips.

Any help would be highly appreciated!

### What are you trying to achieve?

A tint that preserves hights and lows.

### When you searched for similar issues, what did you find that might be related?

I found some tickets regarding tint not behaving as expected, but those issues have been resolved.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```
const image = await sharp('input.png').toBuffer();
const outputBuffer = await sharp(image).tint('#c31306');
await outputBuffer.toFile('output.png');
```

### Please provide sample image(s) that help explain this question

Raw image:

![sandwich](https://user-images.githubusercontent.com/1395893/185454088-9c627d29-c4b4-4d3d-9ce5-0fa4666bb566.png)

**Comment by lovell** [comment]
Bonjour, this has been discussed previously at #1235 - sharp sets the chroma in the LAB colour space and doesn't scale the luminance, but perhaps should. The suggestion in https://github.com/lovell/sharp/issues/1235#issuecomment-390907151 might be worth exploring, and happy to accept a PR, if you're able.

**Comment by shahkashani** [comment]
Much appreciated. I tried the above snippet and ended up with the following, which still isn't right (note how all the highs are gone), but I'll keep looking around.

### Desired result

![output-im](https://user-images.githubusercontent.com/1395893/185584779-d2371944-48bb-40a3-b8f9-c7206e262d46.jpg)

### Vips

![output-vips](https://user-images.githubusercontent.com/1395893/185584510-d19032aa-457a-4f11-96f1-de9e867a3dd2.png)

```
  let im = vips.Image.newFromFile(input);
  const start = [0, 0, 0];
  const stop = [42, 64, 55];   // #c31306
  let lut = vips.Image.identity().divide(255);
  lut = lut.multiply(stop).add(lut.multiply(-1).add(1).multiply(start));
  lut = lut.colourspace(vips.Interpretation.srgb, {
    source_space: vips.Interpretation.lab
  });
  if (im.hasAlpha()) {
    const withoutAlpha = im.extractBand(0, { n: im.bands - 1 });
    const alpha = im.extractBand(im.bands - 1);
    im = withoutAlpha.colourspace(vips.Interpretation.b_w)
      .maplut(lut)
      .bandjoin(alpha);
  } else {
    im = im.colourspace(vips.Interpretation.b_w).maplut(lut);
  }
  const outputBuffer = im.writeToBuffer('.png');
  fs.writeFileSync(output, outputBuffer);
```

**Comment by kleisauke** [comment]
> `The vector weighting function is f(x)=(1-(4.0*((x-0.5)*(x-0.5))))`

I think the equivalent in libvips would be `lut = (1 - (4.0 * ((lut - 0.5) ** 2))) * tint`. Using wasm-vips, this can be written like this:
```js
// #c31306 as CIELAB triple
const tint = [41.349, 63.353, 53.1];

// let lut = vips.Image.identity() / 255;
let lut = vips.Image.identity().divide(255);

// lut = (1 - (4.0 * ((lut - 0.5) ** 2))) * tint
lut = lut.subtract(0.5).pow(2).multiply(4).multiply(-1).add(1).multiply(tint);

lut = lut.colourspace(vips.Interpretation.srgb/* 'srgb' */, {
  source_space: vips.Interpretation.lab // 'lab'
});

// Load an image from file
let im = vips.Image.newFromFile('185454088-9c627d29-c4b4-4d3d-9ce5-0fa4666bb566.png');

if (im.hasAlpha()) {
  // Separate alpha channel
  const withoutAlpha = im.extractBand(0, { n: im.bands - 1 });
  const alpha = im.extractBand(im.bands - 1);
  im = withoutAlpha.maplut(lut).bandjoin(alpha);
} else {
  im = im.maplut(lut);
}

// Finally, write the result to a blob
const outBuffer = im.writeToBuffer('.png');
```
([Playground link](https://wasm-vips.kleisauke.nl/playground/?deflate=hVRrT9swFP0rV92kOFXjJM1jwACJIpCQkCbt8Ymi4SRuY-bYUeLQVYj_vuu4lKJp2pc4vj7n-NxHcjcJQ_hQJnES5cB6uLy5ur1YgOlEK_lSlVr1BoxQBs7gLo1pkh7PIE9okiUzyBIa339eqqVCEckNyMHinkTb05uGrTkVFVdGmC3xIYR5liH4PzhaiSfcEQT7e-kRTmIIgKQ0gikQYmMBRDTzYTqFue_jOhrFG0Y4Pmk_FKZjpSEWR1u9IXOfNoM0mN2WpAfvQexTVlUEl33MqjkPb4qllnro-paVnDj_yvCu7bhhRmhF-25dhFPw7OrBNJzB81IB9Egq-c-Rd7JL_D1RsgIwVQ9Xb6le9rnfalYBUyBsnWDV6QaKYbXi3Wtz3A7tsQ0TBlbclDXxamPa_iQMTUSVDOOjLM3S6OgoOC7z-adqfhyUaZEGaZVUGOJZEK1Ymud5UWR5Tlu19nxqaq5Ix_sWzs7BrpR1HdsuxvuIbx3aXormfSsV31yjyx3MuXPZiBUQ0dCa9ReyrRlKuOJglt94yzpmODB7AmXNlOLSHrokN8LUejAjD69DFf577OyCqYpEWGVQJzZc4L7HwYhhLOEr38n-RTwkOPiYzeFttGEtNt7Omz-CH7VQZNSzjBfgsucuj5GLkgcMi9g18looJuV2BptOYKJYXVtUnDUwGhgUUhf77y1CoZZ3K901TJVYU5xcq-WO0Zqrrrtu1PuudwX3XPf2YBP_Q8sBtORU6jV5uERz1sk7NQzoX_DxGUUCdPUCjZBS9ByZVU8f3mRwDNE_3oTdhwW-kru9y3vbHbNtcfC9cYpD69D154374-st0vFJy47jJHwpHnlpcE_s6RtWNGvEVbocGvxl7MBXktsdQX2XO674KZaI3GljbM9Zc7MjLLY3FfHQaTsYnHjWtlxVl7WQdjTWVmgym5ziHwlEdbacOOBycn4aYux8PJ3c_wE))

However, this would produce a different image than the one from ImageMagick.
![output](https://user-images.githubusercontent.com/12746591/193422226-aef4770b-3611-4afa-8397-4b8ceae3ea7d.png)

I probably made a mistake somewhere. 😅 /cc @jcupitt

**Comment by jcupitt** [comment]
I think the weighting function is an upside down parabola:

![image](https://user-images.githubusercontent.com/580843/194596714-9ce68dd6-0ee2-494c-ae43-53f89bcb033b.png)

So you need to multiply the tint by the weight, but then use a plain ramp for L (otherwise you'll send white back to black again).

I had a stab in python:

```python
#!/usr/bin/python3

import sys
import pyvips

# #c31306 as CIELAB triple
tint = [41.349, 63.353, 53.1]

lut = pyvips.Image.identity() / 255

# so max at 0.5, tailing to 0 at black and white
lab = (1 - 4.0 * ((lut - 0.5) * (lut - 0.5))) * tint

# we want L to stay the same, we just take ab from the lab tint
lut = (lut * 100).bandjoin(lab[1:])

# and turn to sRGB
lut = lut.colourspace("srgb", source_space="lab")

image = pyvips.Image.new_from_file(sys.argv[1], access="sequential")
image = image.colourspace("b-w").maplut(lut)
image.write_to_file(sys.argv[2])
```

To make:

![x](https://user-images.githubusercontent.com/580843/194597235-a37c1d8c-e037-4596-94ac-5c052a2554d4.jpg)

It looks a bit dark, but that's because it's in CIELAB and I think IM is working in RGB. Adding a gamma would probably fix it.

**Comment by shahkashani** [comment]
No. fricken. way. It looks fantastic! Thank you all so much, y'all are incredible! 🎉

**Comment by kleisauke** [comment]
Great! Here's an [updated wasm-vips playground link](https://wasm-vips.kleisauke.nl/playground/?deflate=lVRta9tIEP4rg-_AK2OvJFvyJbkmUIcWAoGDa_spDu1KWlubrHaFtKpqSv57Z7SO4lBK6RevNfvMM8-87d0kDOGvfBWvojWIFq5v3t2-3YBrVK3l1uTWtA6cMg4u4S6J-So5n8N6xVfpag7pisf3_27N1iCJlg50R7ivqm75TSX2kqtCGqfcgQUQwjJNEfwbHC_UV_xiCA5GapEhnMWwgIRHMAPGiGEBEU8DmM1gGeAxyBzwrYVKfAPhCDAHJ5RWZg_OQkTGTIv8EYQpoC-VG7P0UZCYt13mGpE7Rvy8tj1bBrzqtMOiHFhy8n8RB1wUBcNjtJGMUXovoRdYvVuK3jpxAFdKaEUl53T30FF5xaMEDL5rbDVckxKfjC8UaRrp4ygKeIbqH6wyDKFcfhvUbtDG4jl8B3NBFAOoxSrF8BR4QS90udW2a9pa5JL5Phgnm7qRTjhlDW-bfRbOYErnFGYh0m4NYGW7JpefB7-LYwNfO5J2zHuK53RrnsZC3FpRYM1BUb99qlm328nmufz-C-WJXigHO-nykk1L5-r2IgxdxI0O47M0SZPo7Gxxnq-X_xTL80WeZMkiKVYFmmS6iHYiWa_XWZau17w2-2nAsaKGNbKt4fIK6OSiacRhM8RjQ2VoJlX1eiSN7N-jyiPMq_PZqB0wVfFStG91XQqk8MXBLD_IWjTCYTvpBvJSGCM1Xfoke-VK27nBD8Mhy2nzomPz0HzaOwz67O9pf3I8dfDwIZvTaL_tePa5p4Zni576HRAJAK9EjeNC6_ZsGUdv0ELRnkDqVvoaDHFRzh9GO41DjMehea-M0PqAq9Lgog67gQ3ETaBtErjINhvfqAgD17LZ2aYSJsf-4doSl7_GMvhOenkD30d7bO7UT8oIdvEvuDzAasm13bMv1yiOlLxiQ4N9hL-_I8kCVT1BpbRWrUTPouVfXmjoIbL05OCkwQb_srtR5T1NgjvUuGTTYWNCUuhn4cX30_-36I6_PG8kTt1_2YPMHX4zun3BqmqPuMLmXYXP7BH8Tkv6Ysjvc8cT1z5H5JEbbaPPXrqjw-ZwU7ApKq07h9sl6lqa4rpUmsZwT0ST-eQNvuKgisvtxAO3k6s3IdquhtvJ_Q8) based on the above Python sample.

> It looks a bit dark, but that's because it's in CIELAB and I think IM is working in RGB. Adding a gamma would probably fix it.

Removing the monochrome colourspace conversion could also make it a bit brighter.

**Comment by shahkashani** [comment]
Man, you guys are the kindest. Thank you so much again, I could not be more appreciative! 🙏

**Comment by jcupitt** [comment]
... I thought of a simple way to fix the gamma problem. You build the initial LUT in RGB space, go to LAB, do the tint, then go back to RGB again. Now when you apply the LUT to an RGB image you don't distort the gamma.

```python
#!/usr/bin/python3

import sys
import pyvips

if len(sys.argv) != 3:
    print(f"usage: {sys.argv[0]} INPUT-IMAGE OUTPUT-IMAGE")
    sys.exit(1)

# #c31306 as CIELAB triple
tint = [41.349, 63.353, 53.1]

# start with an RGB greyscale, then go to LAB
lab = pyvips.Image.identity(bands=3).colourspace("lab", source_space="srgb")

# scale to 0-1 and make a weighting function
x = lab[0] / 100

# our tint with max weight at 0.5, tailing to 0 at 0 and 1
weighted = (1 - 4.0 * ((x - 0.5) * (x - 0.5))) * tint

# we want L to stay the same, we just take ab from the weighted ccolours
lab = lab[0].bandjoin(weighted[1:])

# and turn to sRGB
lut = lab.colourspace("srgb", source_space="lab")

image = pyvips.Image.new_from_file(sys.argv[1], access="sequential")
image = image.colourspace("b-w").maplut(lut)
image.write_to_file(sys.argv[2])
```

I see:

![x](https://user-images.githubusercontent.com/580843/194755979-0cd6e0f1-5cb3-40d5-a537-3e70b0cf8561.jpg)

From left to right, that's the original, this code, the IM result, and a block of `#c31306`. I think this code looks the best -- IM has made the image too bright (compare the detail visible in the dark areas compared to the original), and the tint looks washed out compared to the actual tint colour.

**Comment by kleisauke** [comment]
Nice! Looking at IM's code, I think they operate directly on RGB, which is probably the reason for this difference.

(here's an [updated wasm-vips playground link](https://wasm-vips.kleisauke.nl/playground/?deflate=tVVhT-NGEP0ro7RS1ijZ2JCkBz2QCLqrkJAqXdtPBHFre-MsbNauvSakiP_et7uOCa2quy9FIol338y8mXkvuR1MJvRDdpKcxHMSDQlDX35ZkK1VpeXSaGnJKmPpnG6T09mIktMRze-WZmkQZ9vakC3p6vrTzeViaTrkk6oafr0RheSpFtkjSxAXcSO3n-ty4y-Yg0Y8K3XZ1k0lMslClLGyrmpphVWl4VqkI3pZGqIGuEzee-hZV-E9tqmLdGleI54KkzeVVpZFP_ecUJwu61rsfGXeqL8kiyK-UlqzOOIbUTF2PyIV0fmF75gX0jIVcfFUAIhEvuPGitrSVtn1flJFLXdNJrQckV1LQ0XpJuLH4YaHDt5PROUSnOyOvZAnekYnBNL_xyR60o6eYxWPE9DOaSMeJQnaSlWs0WtBq9ZkLtTDn0EY5W7jO5pQEsdLk5WmsftzLp9tLTK7QCY3ulw9oScGoCuI-JAW4ITGNOUxHRFjz_gc81lER0d0HO1T9tBn3rSpT8scilfllh1jLa22EOKOTQ8-j6Elkecs6RvcStoKrPnGNYkV7dwqqBEbLAV3D-1bKazDh4S9hDa9Yh5KZRjrUEdeAtFtcnYHrj32n633cSHsjWJQ9yEaFnghc-az-L1jHgkW3_fg9rL3UwNh7UekWzcfF_Ytibi1f7dGkPBQIjelyJ2ildMorWBTStvVStZ7GuEJTMRWKEsrabM1G66trZqzycTG3OhJ8mE2nU3jDx_Gp9n8-Kf8-HScTdPpeJqf5DiSs3G8EtP5fJ6ms_mcV6YYRtyZhtWyqZzx3DsXzqYLXy84z_lIbd7bqPsy6WCB3YiGQzdmkWWygbE8_NI_8Eb-2TrjCY2h-67Vipja8LVoLnW1FigVZodp_CYrUQsLj7gbytbCGKndZSdb-L9srY8DLWR5J4xu1Tg-3DSK7uND2n8FHgYEuO_6sNo3RZDeb6FYwp_7ToN4GP73J71ePQFX4pWkbmRo3BcDh-8pcZjcpelk9FkZofUOrqsVxudciJXCFU7VglJdQnVhBjZGtUrWq7LeCJNho7C8yxWu0XDYbeDk8_1eduseBu30YJv8R64AKLXkuizY1yuQc0zeZcNB-Ug_viDJGKxeaYPfBNVIROYN__qWBiYA_-63ZIGP7LZneed2bncV3Db0Hpo4hmHrb7F_fLlBOF55Vkvo69f0QWYWz8zdvmHVpgAuL7N2A8124E9auieG_KF3vMPzGZBdbpz1Mfj16gIWu-ucDcG0ai38JqpKmvxqrbQTXOESDUaDj_gWJ5WfLwcBuBxcfJzg7MLfDu7-Bg))

**Comment by jcupitt** [comment]
Yes, RGB is really awful for colour work like this, it's very hard to control.

**Comment by james090500** [comment]
I'd love to see some progress on this. I tried to implement this with no avail on my side. Are we just waiting on a functional PR?

**Comment by jcupitt** [comment]
I don't know sharp well enough to make a PR, but I reworked that python code into c++, it might help someone else:

```C++
/* compile with
 *
 *  g++ tint.cc `pkg-config vips-cpp --cflags --libs`
 */

#include <vips/vips8>

using namespace vips;

// make a LUT which applies a tint to a mono image
static VImage
make_tint(std::vector<double> tint) 
{   
    // turn the tint to CIELAB
    tint = (VImage::black(1, 1) + tint) 
        .colourspace(VIPS_INTERPRETATION_LAB,
            VImage::option()->set("source_space", VIPS_INTERPRETATION_sRGB))
        .getpoint(0, 0);

    // start with an RGB greyscale, then go to LAB
    auto lab = VImage::identity(VImage::option()->set("bands", 3))
        .colourspace(VIPS_INTERPRETATION_LAB,
            VImage::option()->set("source_space", VIPS_INTERPRETATION_sRGB));
            
    // scale to 0-1 and make a weighting function
    auto l = lab[0] / 100;
    auto weight = 1 - 4.0 * ((l - 0.5) * (l - 0.5));
    
    // weight ab
    auto ab = (weight * tint)
        .extract_band(1, VImage::option()->set("n", 2));

    // we want L to stay the same, we just weight ab 
    lab = lab[0].bandjoin(ab);

    // and turn to sRGB
    return lab
        .colourspace(VIPS_INTERPRETATION_sRGB,
            VImage::option()->set("source_space", VIPS_INTERPRETATION_LAB));
}

int
main (int argc, char **argv)
{
    // #c31306 as an rgb triple
    auto tint = make_tint(std::vector<double> {195, 19, 6});

    auto image = VImage::new_from_file(argv[1], VImage::option()
        ->set("access", "sequential"));
    image = image.colourspace(VIPS_INTERPRETATION_B_W).maplut(tint);
    image.write_to_file(argv[2]);
}
```

**Comment by lovell** [comment]
Thanks @jcupitt! I've opened a PR with your LUT-based approach so it's easier to see the difference this improvement makes to the test fixtures/expectations - see https://github.com/lovell/sharp/pull/3859
