### ISSUE TITLE
Can libvips version be updated to support large size gif saving?

### ISSUE THREAD

**Issue by niwang55** [lovell/sharp#3340]
### What are you trying to achieve?

Save a gif larger than 2000x2000, currently it doesn't seem to be supported

### When you searched for similar issues, what did you find that might be related?

Question about same issue here
https://bytemeta.vip/repo/kleisauke/net-vips/issues/157

Could updating `libvips` to `8.13.0` solve this issue?

**Comment by lovell** [comment]
The forthcoming sharp v0.31.0 will provide prebuilt libvips v8.13.x - see https://github.com/lovell/sharp/commits/eagle for work-in-progress.
