### ISSUE TITLE
'darwin-x64' binaries cannot be used on the 'darwin-arm64v8' platform. 

### ISSUE THREAD

**Issue by tonyz0212** [lovell/sharp#3342]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?
```
  System:
    OS: macOS 12.4
    CPU: (10) x64 Apple M1 Pro
    Memory: 177.05 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 12.22.12 - ~/.nvm/versions/node/v12.22.12/bin/node
    npm: 6.14.16 - ~/.nvm/versions/node/v12.22.12/bin/npm
  npmPackages:
    sharp: ^0.30.7 => 0.30.7 
```

### What are the steps to reproduce?

Git push using intellj

### Please provide sample image(s) that help explain this problem
![Screen Shot 2022-08-25 at 6 46 00 PM](https://user-images.githubusercontent.com/11653063/186788030-fbb607df-3f48-41cb-ac11-1d30f0a74362.png)

**Comment by lovell** [comment]
Hello, the installation issue template appears to have been ignored and/or deleted. Please open a new installation issue and provide answers to all of the questions.

https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md
