### ISSUE TITLE
Error: gifsave_buffer: frame too large

### ISSUE THREAD

**Issue by sparanoid** [lovell/sharp#3348]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 124.95 MB / 64.00 GB
    Shell: 3.5.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.16.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.16.0 - /opt/homebrew/bin/npm
```

On server (inside Docker):

```
  System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC 7T83 64-Core Processor
    Memory: 4.15 GB / 7.63 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.7.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  npmPackages:
    sharp: ^0.30.3 => 0.30.7 
```

### What are the steps to reproduce?

When processing gif larger than 2000x2000. sharp (libvips) will throw error:

```
Error: gifsave_buffer: frame too large
```

### What is the expected behaviour?

sharp (libvips) should handle large gif without any issue.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```js
import sharp from 'sharp';
const media = sharp('test.gif', { animated: true })
const metadata = await media.metadata()
```

### Please provide sample image(s) that help explain this problem

[test.gif.zip](https://github.com/lovell/sharp/files/9479134/test.gif.zip)

**Comment by lovell** [comment]
Yes, the change you've highlighted is the reason for this. The forthcoming sharp v0.31.0 will provide prebuilt binaries for libvips v8.13.x.
