### ISSUE TITLE
auto rotate not working when orientation is 3

### ISSUE THREAD

**Issue by milamer** [lovell/sharp#3355]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

  System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 17.21 GB / 25.01 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - /mnt/c/Users/icyly/AppData/Roaming/npm/yarn
    npm: 8.5.4 - ~/.nvm/versions/node/v16.14.0/bin/npm

### What are the steps to reproduce?

There are two ways to recreate the problem:
- Try to rotate an image by 180 degrees
- Have an image with orientation: 3 and call rotate without arguments

### What is the expected behaviour?

Image is rotated by 180 degree.  
This still works if I downgrade to version `0.30.7`

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```ts
const img = fs.readFileSync("./test.jpg");
const image = sharp(img);
image.rotate();
const metadata = await image.metadata();
console.log("meta", metadata);
image.resize(320, 240);
const buffer = await image
  .jpeg({ force: true, quality: 75 })
  .toBuffer();
fs.writeFileSync("./out.jpeg", buffer);
```

#### Input
![test](https://user-images.githubusercontent.com/12884134/188804467-3aaaa040-7664-4114-80ed-f1909f73a5e5.jpg)

#### output 0.30.7
![out 30 7](https://user-images.githubusercontent.com/12884134/188806726-92b4ef82-6af5-4bb5-99e6-f4f821d55d1f.jpeg)

#### output 0.31.0
![out 31 0](https://user-images.githubusercontent.com/12884134/188806782-a0b80cc2-e16a-4f68-bdc3-50d4fc1ddc17.jpeg)

**Comment by lovell** [comment]
Hi, thanks for reporting, this is due to the same problem as #3352 - let's track it rhere.
