### ISSUE TITLE
sharp@0.31.0 doesn't detect custom libvips

### ISSUE THREAD

**Issue by Kikobeats** [lovell/sharp#3356]
Hello,

I was trying to upgrade from 0.30.7 to 0.31.0, but 0.31.0 can't detect the custom libvips I was using.

I reproduced the issue in this PR:

https://github.com/microlinkhq/splashy/pull/26

If you check the first commit, all is green and working as expected. There I enabled npm logs to understand better how sharp is being installed:

https://github.com/microlinkhq/splashy/runs/8229277255?check_suite_focus=true#step:4:7776

Here you can see I'm using a custom libvips installation (essentially using https://github.com/Kikobeats/docker-vips). 

So, the problem start when I upgrade the version in the second commit. Now tests are failing, because sharp is not detecting the custom libvips installation anymore:

https://github.com/microlinkhq/splashy/runs/8229647068?check_suite_focus=true#step:4:7776

**Comment by lovell** [comment]
sharp v0.31.0 requires libvips v8.13.1 - please see https://sharp.pixelplumbing.com/changelog

**Comment by Kikobeats** [comment]
ouch. I compiled `libvips@8.13.0`, but `libvips@8.13.1` is throwing an error

https://github.com/Kikobeats/docker-vips/runs/8254495026?check_suite_focus=true#step:4:8439

any idea why this is happening?

**Comment by lovell** [comment]
See https://github.com/libvips/libvips/issues/3024

**Comment by Kikobeats** [comment]
oh, it looks resolved, but `8.13.2` isn't being released yet

**Comment by Kikobeats** [comment]
resolved after using ubunt 22.04
