### ISSUE TITLE
Do something after multiple .toFile()

### ISSUE THREAD

**Issue by dsine-de** [lovell/sharp#336]
This has presumably been asked multiple times before, so my apologies, but I don't get how I can do something after multiple processed files have been saved.

Let's say I have this chain:
````javascript
sharp('image.jpg')
.resize(100, 100)
.toFile('processed_l.jpg'), function (err) {
	if (err) return console.log(err);
})
.resize(50, 50)
.toFile('processed_s.jpg'), function (err) {
	if (err) return console.log(err);
});
````

How do I know when both ```.toFile()``` are finished?

#230 should contain the answer, right? Or should I use the ```clone()```function? Or pipe multiple streams myself? Or use an ```.on('end')``` function on a returned promise?

Thanks for your help.

**Comment by lovell** [comment]
Hi Dennis, as you're using the filesystem I'd probably break this into two resize operations and use [async.parallel](https://github.com/caolan/async#parallel) to manage the parallelism.

```javascript
async.parallel([
  function(done) {
    sharp('image.jpg').resize(100, 100).toFile('processed.jpg', done);
  },
  function(done) {
    sharp('image.jpg').resize(50, 50).toFile(path.join(config.upload.images.directory, '_processed_s.jpg'), done);
  }
], function(err, results) {
  ...
});
```

**Comment by dsine-de** [comment]
Ok great, thank you.
