### ISSUE TITLE
Got error "extract_area: bad extract area" when using rotate()

### ISSUE THREAD

**Issue by j0k3r** [lovell/sharp#3361]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

I've tested on current master & 0.30.7.
Using the latest version 0.31.0 result in a different bug already fixed: https://github.com/lovell/sharp/issues/3352

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: macOS 12.5
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 41.27 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.13.2 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 2022.09.05.00 - /usr/local/bin/watchman
  npmPackages:
    sharp: https://github.com/lovell/sharp => 0.31.0
```

### What are the steps to reproduce?

```js
const fs = require('fs')
const sharp = require('sharp')

const image = fs.readFileSync('64e9860fb05e416e9f89ed80088d0baa.jpeg')

const cropAndResize = async (buffer, width, height, topleftX, topleftY, ratio) => {
  const { width: actualWidth, height: actualHeight } = await sharp(buffer).rotate().metadata()

  const newTopleftX = Math.round(topleftX) / 100
  const newTopleftY = Math.round(topleftY) / 100
  const newRatio = ratio / 100
  const left = newTopleftX * actualWidth
  const top = newTopleftY * actualHeight
  const widthToCrop = Math.min(newRatio * actualWidth, actualWidth - left)
  const heightToCrop = Math.min((newRatio * actualWidth) / (width / height), actualHeight - top)

  console.log({
    left: left ? Math.round(left) : 0,
    top: top ? Math.round(top) : 0,
    width: Math.round(widthToCrop),
    height: Math.round(heightToCrop),
    actualWidth,
    actualHeight,
  })

  const newBuffer = await sharp(buffer)
    .rotate()
    .extract({
      left: left ? Math.round(left) : 0,
      top: top ? Math.round(top) : 0,
      width: Math.round(widthToCrop),
      height: Math.round(heightToCrop),
    })
    .resize({
      height: height ? Number(height) : height,
      width: Number(width),
      withoutEnlargement: true,
    })
    .jpeg({ quality: 80 })
    .toBuffer()

  return newBuffer
}

;(async () => {
  const res = await cropAndResize(image, 1200, 768, 0, 19, 100)

  console.log(res)
})()
```

I'm using that image for my test (called `64e9860fb05e416e9f89ed80088d0baa.jpeg` in the script).

![64e9860fb05e416e9f89ed80088d0baa](https://user-images.githubusercontent.com/62333/189658108-7af16aa1-e6e7-4227-8838-16424fc2af34.jpeg)

### What is the expected behaviour?

It should log the Buffer after rotate + extract + resize.

```
$ node index.js
{
  left: 0,
  top: 287,
  width: 2016,
  height: 1225,
  actualWidth: 2016,
  actualHeight: 1512
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: extract_area: bad extract area
]
```

If I remove the `rotate()` action (the second one used), everything went fine.

I've checked EXIF data from the image (using http://exif-viewer.com/) and it seems to have the Orientation data.

key | value
-- | --
**create** | 2022-09-12T12:50:11+00:00
ColorSpace | 1
ExifImageLength | 1512
ExifImageWidth | 2016
ExifOffset | 38
Orientation | 6
**modify** | 2022-09-12T12:50:11+00:00
ColorSpace | 1
ExifImageLength | 1512
ExifImageWidth | 2016
ExifOffset | 38
Orientation | 6
**colorspace** | 2
ColorSpace | 1
ExifImageLength | 1512
ExifImageWidth | 2016
ExifOffset | 38
Orientation | 6
**sampling-factor** | 2x2,1x1,1x1
ColorSpace | 1
ExifImageLength | 1512
ExifImageWidth | 2016
ExifOffset | 38
Orientation | 6

It seems calling `.rotate()` as no action on the image.
I don't know if the problem is about the photo, libvips or sharp.

**Comment by lovell** [comment]
Please see the examples in https://sharp.pixelplumbing.com/api-input#metadata

The following change ensures `actualWidth` and `actualHeight` contain values that are "auto oriented".

```diff
-  const { width: actualWidth, height: actualHeight } = await sharp(buffer).rotate().metadata()
+  const metadata = await sharp(buffer).metadata()
+  const [actualWidth, actualHeight] = (metadata.orientation || 0) >= 5
+    ? [metadata.height, metadata.width]
+    : [metadata.width, metadata.height];
```

**Comment by j0k3r** [comment]
Thanks for that information, I was sure that using `.rotate()` before the `.metadata()` will return the correct value without extra code.
