### ISSUE TITLE
Error: Processed image is too large for the JPEG format

### ISSUE THREAD

**Issue by powerjett** [lovell/sharp#3362]
My Code
```javascript
// sharp version 0.28.3
const sharp = require('sharp')
const fs = require('fs')
const path = require('path')
const imgTransformer = sharp().resize(2000).jpeg({
  quality: 100,
  chromaSubsampling: '4:4:4'
})
const write = fs.createWriteStream('./adsadas.jpg')
const read = fs.createReadStream(path.resolve(__dirname, './96313250-89bd-4161-bad2-678cac76e1db.png'))
read.pipe(imgTransformer).pipe(write)
```

throw error message:

`Error: Processed image is too large for the JPEG format`

source Image url:

链接: https://pan.baidu.com/s/1jBW_NSbvoG_ROsZJVNxCoQ?pwd=6vhv 提取码: 6vhv

i need your help,your can download this image and run code

**Comment by lovell** [comment]
The JPEG format supports up to 65535 pixels for each dimension. I can't access your original image, but from the thumbnail it appears to be a very tall image, so when resized to 2000 pixels wide, the required height will probably be much greater than 65535 pixels.

**Comment by powerjett** [comment]
> The JPEG format supports up to 65535 pixels for each dimension. I can't access your original image, but from the thumbnail it appears to be a very tall image, so when resized to 2000 pixels wide, the required height will probably be much greater than 65535 pixels.
Thank you.

**Comment by dan-caldwell** [comment]
In case anyone comes across this, for me this was happening because I put `scale: 70` instead of `scale: 0.7`.
