### ISSUE TITLE
avif image is larger than webp image

### ISSUE THREAD

**Issue by yogarasu** [lovell/sharp#3363]
### What are you trying to achieve?

I was hoping that by supporting the conversion of avif format images, the images would be smaller than webp format images.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

I created and ran the following CLI in Node.js 18.8.0.

```zsh
npm install sharp tiny-glob commander

node sharp.mjs --src src --dist dist
```

```js
import { Command } from 'commander'
import { rm, mkdir } from 'node:fs/promises'
import { join, extname, dirname } from 'node:path'
import sharp from 'sharp'
import glob from 'tiny-glob'
;(async () => {
  const program = new Command()

  program
    .description('Convert image files to optimal png/webp/avif format.')
    .requiredOption('-s, --src [string]', 'Input directory path for image files')
    .requiredOption('-d, --dist [string]', 'Output directory path for image files')
    .parse(process.argv)

  const options = program.opts()

  const srcDirPath = options.src
  const distDirPath = options.dist
  const srcFilePathList = await glob(join(srcDirPath, '**/*.{jpg,jpeg,png,avif}'))

  await rm(distDirPath, { recursive: true, force: true })

  await Promise.all(
    srcFilePathList.map(async (srcFilePath) => {
      // Get output file path without extension
      const distFilePath = srcFilePath
        .replace(srcDirPath, distDirPath)
        .replace(extname(srcFilePath), '')

      // Create output directory for image files
      await mkdir(dirname(distFilePath), { recursive: true, force: true })

      // Convert image file
      sharp(srcFilePath)
        .png({ quality: 85 })
        .toFile(`${distFilePath}.png`, (error) => {
          if (error) console.error(error)
        })
        .webp({ quality: 85 })
        .toFile(`${distFilePath}.webp`, (error) => {
          if (error) console.error(error)
        })
        .avif({ quality: 85 })
        .toFile(`${distFilePath}.avif`, (error) => {
          if (error) console.error(error)
        })
    })
  )
})()
```

### Please provide sample image(s) that help explain this question

<img width="145" alt="sample" src="https://user-images.githubusercontent.com/68766032/189999220-0d4c8896-94be-44df-87bc-874f2f6a6ee6.png">

**Comment by lovell** [comment]
A WebP "quality" setting of 85 is approximately equivalent to an AVIF "quality" setting somewhere in the 50-60 range.

The sample image you've attached appears to be blank, was this intentional?

**Comment by yogarasu** [comment]
@lovell 
There is no special meaning in the sample image
I just thought that a simple monochromatic image with no complexity would have less individual differences, sorry.

Basically, if the "Quality" is lowered, the image will be smaller to some extent, and if the "Quality" is the same, I thought that a superior image format such as compression would be smaller, but is my understanding wrong?

**Comment by lovell** [comment]
The concept of "quality" is highly subjective, especially when different compression methods are used. You'll need to use concepts such as https://en.wikipedia.org/wiki/Structural_similarity to compare these.

**Comment by yogarasu** [comment]
I see, I learned a lot, thank you for taking the trouble to teach me.
I came to like sharp.js even more..
