### ISSUE TITLE
why output file size  bigger than the original image ?

### ISSUE THREAD

**Issue by dcyu007** [lovell/sharp#3364]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

 System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 282.68 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
  npmPackages:
    sharp: ^0.31.0 => 0.31.0 

### What are the steps to reproduce?

I'm trying to compress image with jpeg format with Sharp, but the output file is bigger than origin file.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

https://github.com/dcyu007/sharp-demo

**Comment by lovell** [comment]
The original image https://github.com/dcyu007/sharp-demo/blob/master/static/1.jpeg was created with a "quality" setting of approximately 29.
```sh
$ identify -verbose 1.jpeg | grep Quality
  JPEG-Quality: 29
```

**Comment by dcyu007** [comment]
> The original image https://github.com/dcyu007/sharp-demo/blob/master/static/1.jpeg was created with a "quality" setting of approximately 29.
> 
> ```shell
> $ identify -verbose 1.jpeg | grep Quality
>   JPEG-Quality: 29
> ```

Thanks ! But I'm confused, I thought earlier that image compression is based on input file data. So in this case, how do I know if some images can be compressed to a smaller size? Is there some option setting, when the set output quality is higher than the original image quality, it will output according to the original image?

**Comment by lovell** [comment]
Please see #908
