### ISSUE TITLE
Image Compression Performance Time

### ISSUE THREAD

**Issue by melogustavo** [lovell/sharp#3365]
### What are you trying to achieve?
- I have a list of images that I can not reduce its size when storing, so I need to reduce it on demand when I receive the request to generate a report.
- These images are usually at least 2mb each but can go up higher.
- So what I need to do is "compress" the image's total size without losing too much of the quality and having it remain the same visual size.
-  PS: This is doing as expected, its just taking a long time and I was wondering if I could be doing something wrong with the code.

### When you searched for similar issues, what did you find that might be related?
- I didn't find anything related

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question
- The canvas here is my "image", it is in svg format

```
    const compressCanvasPromise = sharp(canvas.toBuffer())
      .resize(1500)
      .trim(10)
      .jpeg({
        mozjpeg: true,
      })
      .toBuffer()
      .then((data) => `data:image/jpeg;base64, ${data.toString('base64')}`);
```
- Then after I have these promises I will execute them with Promise.all() to run them in parallel.
```
await Promise.all(
    data.map((sheet) => sheet.compressCanvasPromise),
  ).then((arrOfImages) =>
    arrOfImages.forEach((image, index) => (data[index].image = image)),
  );
```

**Comment by melogustavo** [comment]
I saw that the sharp lib already uses background threads, I even tried adding my own threads but it didn't improve any performance since this is already being done. 

I know that everything in programming hits a limit, so if there is no room for me to improve my code, I guess it's okay since there is not much to be done in that case anyways. There is the natural limitation that the bigger the image the longer it will take to compress.

BTW, congrats on this lib, it is really awesome to work with :)

**Comment by lovell** [comment]
Enabling the `mozjpeg` features will slow things down quite a bit, so that's probably the first thing to remove if greater performance is required.

**Comment by melogustavo** [comment]
I see, I had done that because of the size since it seems like it brings the size a little more down. I have a performance x size problem.

Is there any better way of resizing an image that I might have missed?

**Comment by melogustavo** [comment]
@lovell do you know if the `mozjpeg ` slows down exponentially?  I ran with 5 images and it didn't seem to change too much the time.

Let me share the results
```
{
  "timeOfExecutionInSeconds-WITH-MOZJPEG": 12.719,
  "timeOfExecutionInSeconds-WITHOUT-MOZJPEG": 12.09,
  "image1": {
    "compressedWithMozjpegSizeInKb": 122.26274672416655,
    "compressedSizeInKb": 152.63718692983915,
    "originalSizeInKb": 757.5880378172168
  },
  "image2": {
    "compressedWithMozjpegSizeInKb": 142.7823685519987,
    "compressedSizeInKb": 173.90379499087746,
    "originalSizeInKb": 1185.3456543373695
  },
  "image3": {
    "compressedWithMozjpegSizeInKb": 97.22520816055732,
    "compressedSizeInKb": 129.30286697628134,
    "originalSizeInKb": 639.354966827003
  },
  "image4": {
    "compressedWithMozjpegSizeInKb": 173.90379499087746,
    "compressedSizeInKb": 208.16841350140987,
    "originalSizeInKb": 1062.052426604744
  },
  "image5": {
    "compressedWithMozjpegSizeInKb": 46.920635262896006,
    "compressedSizeInKb": 62.26085254602754,
    "originalSizeInKb": 256.7472682036822
  }
}
```

**Comment by melogustavo** [comment]
I've made a bunch of other tests here with more images, (10, 15, and 30 images) and the diff in time between having or not having the `mozjpeg: true` is acceptable. In 30 sheets it takes 10s more

Based on the amount of size if reduces with that option I would say the extra time is acceptable.   

Other than this would there be anything else I could try?

**Comment by lovell** [comment]
If you need further help, perhaps you could provide a complete, standalone repo with all code and images that allows someone else to reproduce the same results as you.

**Comment by melogustavo** [comment]
Sure, I will do that. I'll send the link as soon as I get it ready

**Comment by melogustavo** [comment]
Hi @lovell sorry for the delay in giving feedback to you, the link to the repo with the code is https://github.com/melogustavo/compress-image.

I have done something similar to what I'm doing on the real project, which is getting an image, drawing something on it using canvas, and then compressing it. At first sight, it seems like the processing time is okay, but on the real project, the images are a lot bigger. 

Like I said in the beginning, I know that sometimes we get into the limitation of the software/hardware, so maybe my code is already close to the best it can be and the problem is just that there it hit the natural limit, so I would just love feedback to see if there is any room for improvment. Thanks alot :)

**Comment by lovell** [comment]
Thanks, the majority of the processing time is spent on the `trim()` operation.

**Comment by melogustavo** [comment]
I see, thank you @lovell for the feedback. In my case, I do need this or the image has some lines on the generated final image (when I put it in a PDF).

**Comment by lovell** [comment]
If you're using a CPU with more than 4 cores, try setting `UV_THREADPOOL_SIZE` to match the number of cores for potentially increased parallelism.

https://sharp.pixelplumbing.com/api-utility#concurrency

**Comment by melogustavo** [comment]
Yeah, that sounds like the remaining plan for this. Thanks again. I'm gonna close this issue :)
