### ISSUE TITLE
ColorMatrix conversion using sharp (modulate/recomb)

### ISSUE THREAD

**Issue by okaforcj** [lovell/sharp#3366]
## Question about an existing feature
Using the modulate/recomb features

### What are you trying to achieve?

I have a ColorMatrix which is applied via skia engine on mobile device/ using the SVG filter feColorMatrix on web Canvas API. I only have the color matrix applied on the front end. I was wondering if its possible to apply a color matrix directly to the image on the backend using sharp. I looked at the modulate and recomb apis but I cant seem to figure out how to make the mapping of the color matrix. Please can someone advice on how to either apply the 4 x 5 matrix direct in the sharp transformation or use the recomb/modulate api to transform the matrix and apply the filter onto the image.

### When you searched for similar issues, what did you find that might be related?
No specific question relating to the transformation of color matrices

**Comment by lovell** [comment]
Do you have an example of a specific matrix? You should be able to use the `recomb` (or possibly `linear`) operation for this. If the input and expected output are both 4 channel RGBA then your matrix should also be 4x4.

https://sharp.pixelplumbing.com/api-operation#recomb
https://sharp.pixelplumbing.com/api-operation#linear

**Comment by okaforcj** [comment]
yes i do! Thanks for taking the time. I have a 4x5 matrix which is from the webcanvas API filter tag feColorMatrix. I generate the filters from https://fecolormatrix.com/ and use it in the canvas on the web and also react-native-skia for rendering the UI. A sample grayscale filter is something like this:
```
 Greyscale: [
        0.2126, 0.7152, 0.0722, 0, 0,
        0.2126, 0.7152, 0.0722, 0, 0,
        0.2126, 0.7152, 0.0722, 0, 0,
        0,      0,      0,      1, 0,
    ],
```

**Comment by lovell** [comment]
Thanks, the alpha channel remains unchanged with this sample matrix, so the equivalent would be something like (untested):
```js
const data = await sharp(input)
  .recomb([
    [0.2126, 0.7152, 0.0722]
    [0.2126, 0.7152, 0.0722],
    [0.2126, 0.7152, 0.0722],
  ])
  .toBuffer();
```

**Comment by okaforcj** [comment]
> Thanks, the alpha channel remains unchanged with this sample matrix, so the equivalent would be something like (untested):
> 
> ```js
> const data = await sharp(input)
>   .recomb([
>     [0.2126, 0.7152, 0.0722]
>     [0.2126, 0.7152, 0.0722],
>     [0.2126, 0.7152, 0.0722],
>   ])
>   .toBuffer();
> ```

Amazing, this works and its a huge step for me in the right direction! I just tested that and it works but it rotates -90, could you explain whats going on there (or not, i just rotated it back 90 deg). I can see that I can apply this method for a number of use cases but im concerned about slightly more complicated examples. I currently even have presets like
```
[0.197 -0.394  1.080  0.000  0.176 
0.397  0.983 -0.201  0.000  0.176 
-0.693  1.180  0.422  0.000  0.176 
0.000  0.000  0.000  1.000  0.000]
```
and 
```
[ 0.272 -0.544  1.490  0.000  0.008 
0.549  1.360 -0.277  0.000 -0.049 
-0.958  1.630  0.584  0.000  0.001 
0.000  0.000  0.000  1.000  0.000]
```

Do you know what the 5th col signifies? from doing slight testing it seems to be a combination of adjusting brightness and contrast but not sure, do you know what to do for those or what they could signify by any chance?

**Comment by lovell** [comment]
> it rotates -90 for jpg but its fine for png(idk whats up), could you explain whats going on there (or not, i just rotated it back 90 deg)

You've not provided any sample image, but my best guess would be that it contains an EXIF orientation and your file explorer is using this to auto-orient. See https://sharp.pixelplumbing.com/api-operation#rotate for how to tell sharp to auto-orient if your input images contain this.

> Do you know what the 5th col signifies?

It looks like column 5 contains an addition rather than a multiplication, which you can apply via https://sharp.pixelplumbing.com/api-operation#linear

**Comment by okaforcj** [comment]
Hey @lovell  thanks for the help, but ive just played around with that and it seems like adjusting just the r, g and b channels, so its making the images, more red, blue or green. the 5th column on the other hand seems to be adjusting the brightness/contrast/exposure and i'm not sure what that maps to, directly in sharpjs's api?

**Comment by okaforcj** [comment]
Hey update here, I was randomly going through the documentation and i saw that you can read an svg string (didnt know this) to a buffer. The feColorMatrix is an attribute of svg implementation, so i just encoded my image to base64 and transformed it using the feColorMatrix filter. Hope someone else finds this helpful. Also thanks for the awesome library! @lovell 

```
 sharp("bless.png")
      .toBuffer()
      .then((res) => {
        const dataUri = res.toString("base64");
        const buffer = Buffer.from(
          `<svg viewBox="0 0 ${
            width + " " + height
          }" xmlns="http://www.w3.org/2000/svg"> 
          <defs>
          <filter id="filter">
          <feColorMatrix
            type="matrix"
            values=" 1.660 -0.654  0.107  0.000  0.079 
                    -0.131  1.330 -0.097  0.000  0.079 
                    -0.294 -0.426  1.810  0.000  0.079 
                     0.000  0.000  0.000  1.000  0.000">
          </feColorMatrix>
        </filter>
        </defs>
        <image href="data:image/png;base64,${dataUri}" filter="url(#filter)"/></svg>`
        );
sharp(buffer).toFile("bless2.png");
```
