### ISSUE TITLE
Deep Zoom / .tile() quality setting not used?

### ISSUE THREAD

**Issue by homerjam** [lovell/sharp#337]
Hi Lovell

I think this might be a vips issue but the quality setting doesn't seem to effect the output when using the `.tile()` method.

I've looked (bear in mind I don't have any C experience) and can't find any references to quality in the sharp/vips code relating to dz images so I'm assuming its using a default setting?

Thanks

James

**Comment by lovell** [comment]
Hi James, although there's currently no support for setting the image quality of tiles in sharp, libvips does expose a [suffix](https://github.com/jcupitt/libvips/blob/master/libvips/foreign/dzsave.c#L2065-L2066) option that could be used to control this.

I suspect other existing options relating to image formats and options could be passed through using this method, e.g. for line art drawings `.png[compression=9,filter=none]` might be more suitable.

Let's file this under enhancement - probably one to tackle at the same time as #223 - thanks for the suggestion!

**Comment by lovell** [comment]
PNG output is definitely required as part of this task - see #386

**Comment by lovell** [comment]
Added in #622 and now available in v0.17.0.
