### ISSUE TITLE
Saving image through sharp increases file size

### ISSUE THREAD

**Issue by LazyDkk** [lovell/sharp#3371]
Hi

I'm current trying to save some image files while making sure their dimensions don't exceed a certain width or height. I'm working in NodeJS and using the node-fetch package to fetch the images from a url and pass the buffer into sharp. All the images are I believe technically jpegs but they are in the png format using the png extension.

The problem I'm encountering is that when I save the image afterwards it has a larger file size than the original image. Saving the image from the browser yields a smaller file size than saving after passing the buffer through sharp. Below is some code to demonstrate what I mean.

```typescript
const response = await fetch('https://some-website.com/image.png');
const arrayBuffer = await response.arrayBuffer();
let image = sharp(Buffer.from(arrayBuffer));
const buffer = await image.toBuffer();
await fs.promises.writeFile('image.png', buffer); // Larger file size (76,2 KB)

await fs.promises.writeFile('image.png', Buffer.from(arrayBuffer)); // Smaller file size (40 KB)
```

For some reason saving the image after passing it through sharp increases the file size compared to just saving the image directly using the file system. Saving using the file system yields the same file size as if downloading the image from the website with the direct url.

So my question is why the file size would increase after passing it through sharp and is there a way to avoid this size increase? If compression is the only option then what would be the best way to reduce the file size while preserving the most quality possible?

Also I don't know if I'm simply doing it wrong but when I try to use `.png({ quality: 80 })` on the sharp image it doesn't seem to have any effect on the image.

**Comment by lovell** [comment]
If the inputs are palette-based PNG then you'll probably want to use `.png({ palette: true }` to also use this for the output (which is automagically selected for you when you use `.png({ quality: 80 })`. However if you're using the latest version then you might have run into #3357

**Comment by LazyDkk** [comment]
> If the inputs are palette-based PNG then you'll probably want to use `.png({ palette: true }` to also use this for the output (which is automagically selected for you when you use `.png({ quality: 80 })`. However if you're using the latest version then you might have run into #3357

I can confirm that I am most likely using the latest version as I just yesterday used the command `npm install --platform=win32 --arch=ia32 sharp` to install sharp. So it might very well be the bug you're referring to.

As mentioned I tried to use `.png({ quality: 80 })` and even adding `.png({ quality: 80, palette: true })` to force the palette mode but it also didn't seem to have any effect. I also just tried setting the `colors` to 16 like you said in the issue post (`.png({ colors: 16, palette: true })`) but although this results in a smaller file size it seems that the entire image becomes just a single color. Two images, before and after adding the colors option can be seen below.
[https://gyazo.com/ca58e9ec0e64aa6a7385908933819ed0](url)
The image to the left doesn't use any options but the image is the same regardless of using `quality` or `palette`.
The right image is using the `.png({ colors: 16 })` and I have even tried adding the `palette option`.

After doing some testing it seems that any colors value between 129-256 yields the original image with the larger than original file of 76,2 KB and with a colors value between 2-128 gives the image in what appears to be a single color and with a file size between 155 B and 307 B.

**Comment by lovell** [comment]
This definitely sounds like #3357 - let's track it there and I'll close this issue. The best (least bad) workaround for now is to downgrade to v0.30.7.

**Comment by NateWr** [comment]
Yes, that brings file sizes down to a more expected range:

```
$ ls -la dist/_astro
total 1556
drwxrwxr-x 2 nate nate   4096 May 30 12:35 .
drwxrwxr-x 3 nate nate   4096 May 30 12:35 ..
-rw-rw-r-- 1 nate nate 293209 May 30 12:35 city.tXwVt3cZ_1aVQ0G.png
-rw-rw-r-- 1 nate nate  85194 May 30 12:35 city.tXwVt3cZ_2omDQW.webp
-rw-rw-r-- 1 nate nate 443126 May 30 12:35 city.tXwVt3cZ.png
-rw-rw-r-- 1 nate nate 491262 May 30 12:35 city.tXwVt3cZ_Z1O9l35.png
-rw-rw-r-- 1 nate nate 156872 May 30 12:35 city.tXwVt3cZ_Z2eVdgC.webp
-rw-rw-r-- 1 nate nate  76763 May 30 12:35 city.tXwVt3cZ_Z2jxQ4m.png
-rw-rw-r-- 1 nate nate  27330 May 30 12:35 city.tXwVt3cZ_ZX6gIS.webp
```

Thanks!
