### ISSUE TITLE
sharp.fit.cover is not outputing the same image in macos and ubuntu

### ISSUE THREAD

**Issue by jRexhmati** [lovell/sharp#3374]
### What are you trying to achieve?
I installed sharp on my local machine
Macos Monterey - i9

I am using this config to generate the image

`.resize({
          width: targetWidth,
          height: targetHeight,
          // Needed for position strategy to work
          fit: sharp.fit.cover,
          // Do not enlarge images if width or height are bigger than original
          withoutEnlargement: true,
        })
        .webp({ quality: quality })
        .toFile(diskFilename)`

The same source code does not produce the same image in server 
Server specs (Taken from `lscpu`)
Architecture:                    x86_64
Flags:         ....sse4_1 sse4_2 ...sse2..etc

glibc is present as well

More specifically, cropping in the server simply does not work
I set the cropping, lets say to 300x300 and the real image dimensions are 1024x720 
It only gets resized with lower quality but dimensions are still 1024x720

While on my local machine, it is resized and cropped to 300x300

Server
Node version is: v16.13.1
Npm: version is: 8.1.2

### When you searched for similar issues, what did you find that might be related?

My hunch was at the [libvips](https://github.com/libvips/libvips)
Public
Tried to install that from the source as well, but still no difference in the image output
I think those dependencies are all set because when I execute 
` cd ./node_modules/sharp
npm run install
`
I get this response
`
> sharp@0.30.7 install
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Using existing vendored libvips v8.12.2
`

**Comment by lovell** [comment]
Please can you provide a sample image and complete, standalone code that allows someone else to reproduce.

**Comment by jRexhmati** [comment]
Hello @lovell 
The usage of sharp is very simple
This is the full code usage


`return await sharp('/path/to/image.jpg')`
`.resize({`
`          width: 200,`
`          height: 200`
`          fit: sharp.fit.cover,`
`          withoutEnlargement: true,`
`        })`
`        .webp({ quality: '100%' })`
`        .toFile(diskFilename);`

**Comment by jRexhmati** [comment]
The problem was not related with the system image libraries neither sharp installation but it was a permissions issue
Closing the issue
