### ISSUE TITLE
Setting Density in PNG (with transparent bg) is not working

### ISSUE THREAD

**Issue by Panagiotis-Vasiloglou** [lovell/sharp#3376]
Opened this issue because I couldn't find something.

I have a **PNG** image with **transparent background**.
However when I try to set the **density** of the output image,  doesn't seem to work.

**Wanted output** => 
a PNG image with :
- custom size
- keep the transparent background
- custom density/DPI (set by me)

My code which produces the issue(tried many snipets)
**NOTE:** You need an input PNG image with **Transparent Background**

```
buffer = await sharp(input).
  toFormat(format). // png
  resize(sharpOpts). // set height and width
  withMetadata({density: 70}).
  toBuffer(); 
return buffer;
```

However when I apply **flatten()** in the code above, setting density is working!
Of course this is not the output I wanted, because my final image **has background**😢

Thanks for your time

**Comment by lovell** [comment]
Hi, I'm unable to reproduce this using https://github.com/lovell/sharp/blob/main/test/fixtures/full-transparent.png and the following code:
```js
sharp('full-transparent.png')
  .resize({ width: 8 })
  .withMetadata({ density: 70 })
  .toFile('out70.png');

sharp('full-transparent.png')
  .resize({ width: 8 })
  .withMetadata({ density: 80 })
  .toFile('out80.png');
```
which produces the expected resolution:
```sh
$ pnginfo out*.png | grep Resolution
  Resolution: 70, 70 (pixels per meter)
  Resolution: 80, 80 (pixels per meter)
```
If you still require help, please provide the exact code and a specific image that allows someone else to reproduce.

**Comment by Panagiotis-Vasiloglou** [comment]
I'm so sorry, @lovell , I used the Windows Explorer(to check the density/DPI) which  **IS NOT** precise.
I'm currently using a more advanced tool to check DPI, and the code works perfectly! 🙂

Thanks for your reply.
