### ISSUE TITLE
Fastest way to check image integrity

### ISSUE THREAD

**Issue by michael-evans-seequent** [lovell/sharp#3379]
Is there a fast way to use sharp/vips to check the integrity of an image? We'd like to validate an uploaded image before saving it to storage.

Sharp could read the  image, convert into another format and then watch for exceptions. However, this still spends unneeded time on format conversion.

Any thoughts or suggestions on the best approach?

**Comment by lovell** [comment]
To ensure image integrity you'll need to decode all pixels, so I'd suggest `stats()` for this - see https://sharp.pixelplumbing.com/api-input#stats

**Comment by michael-evans-seequent** [comment]
Thx.
