### ISSUE TITLE
Applying Output ICC Profile to an Image

### ISSUE THREAD

**Issue by simonare** [lovell/sharp#3383]
### What are you trying to achieve?

Hi, I am trying to apply output ICC profile to an image.  
equivalent code with Little CMS Profile Applier for JPEG is `jpgicc -o "Noritsu2_Edge_Glossy8.icc" photolab-1_original.jpg out.jpg`

### When you searched for similar issues, what did you find that might be related?

I couldn't find similar approach in  #sharp library.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

I tried following transformer but this creates different result. I believe that this basically attaches profile to the image where as Little CMS approaches differently. (sorry for my semi-technical explaination as I am new into this)

```
    var iccTransformer = sharp()
        .withMetadata({
            icc: iccProfilePath
        })
        .on('info', (info) => {
            console.log("Image transormation is done", info?.metadata)
        })
```

### Please provide sample image(s) that help explain this question
Original Image
![photolab-1_original](https://user-images.githubusercontent.com/8443438/191987984-55794ee6-df6d-4188-ab48-1df66dab547a.jpg)

Expected Image
![out_2](https://user-images.githubusercontent.com/8443438/191988029-eabe1937-8842-45df-8032-548354d9f462.jpg)

Image with ICC Transformer Applied
![photolab-1_icc_applied](https://user-images.githubusercontent.com/8443438/191988567-1d75ad24-2497-4009-9d41-67dea824f555.jpg)

**Comment by lovell** [comment]
Hi, the "Expected Image" provided here is sRGB without a profile, so my understanding is that you want to transform the _input_ image using the `Noritsu2_Edge_Glossy8.icc` profile and convert to sRGB output _without_ metadata. If so, there is a future possible enhancement for this at #1324

As you've seen, `withMetadata()` will transform to the provided profile and attach it, which is not what you want.

**Comment by simonare** [comment]
Hey thank you for quick reply. That means I am stuck here. I will need to look at another  library. 
do you know if there is a fork which includes this feature?

**Comment by lovell** [comment]
Let's track this at #1324
