### ISSUE TITLE
Different number of channels for the same picture

### ISSUE THREAD

**Issue by detailcore** [lovell/sharp#3385]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 15.18 GB / 39.94 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: ^0.30.7 => 0.30.7
```

### What are the steps to reproduce?

```
  console.log('info.channels =>', info.channels) // info.channels = 3
  console.log('channels =>', channels) // channels = 1
```

### What is the expected behaviour?

```
  console.log('info.channels =>', info.channels) // info.channels = 1
  console.log('channels =>', channels) // channels = 1
```

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```
  const pathFile = './2_7d0d.png'

  const { info } = await sharp(pathFile, { animated: true }).toBuffer({ resolveWithObject: true }); // space: 'b-w'
  const { channels } = await sharp(pathFile).metadata(); // space: 'b-w'

  console.log('info.channels =>', info.channels) // info.channels = 3
  console.log('channels =>', channels) // channels = 1
```

### Please provide sample image(s) that help explain this problem

[2_7d0d.zip](https://github.com/lovell/sharp/files/9640480/2_7d0d.zip)

**Comment by lovell** [comment]
The default output from `toBuffer()` will be 3-channel sRGB, so this is correct.

For single channel output, please add `toColourspace('b-w')`:

```diff
- const { info } = await sharp(pathFile, { animated: true }).toBuffer({ resolveWithObject: true });
+ const { info } = await sharp(pathFile, { animated: true }).toColourspace('b-w').toBuffer({ resolveWithObject: true });
```

https://sharp.pixelplumbing.com/api-colour#tocolourspace

**Comment by detailcore** [comment]
Thank you!
