### ISSUE TITLE
npm package page is missing readme contents

### ISSUE THREAD

**Issue by ajmas** [lovell/sharp#3388]
The [npm page for sharp](https://www.npmjs.com/package/sharp) is missing the "read me" contents, is this a publishing issue or an npm issue:

<img width="1481" alt="image" src="https://user-images.githubusercontent.com/682269/192371293-dadfcdb2-ebdf-467d-b5a0-9d7bce923c68.png">

**Comment by lovell** [comment]
Probably a temporary npm problem.

![](https://www.site-shot.com/cached_image/x3wFUj3YEe2QuAJCrBEABg)
