### ISSUE TITLE
SVG to PNG in different sizes

### ISSUE THREAD

**Issue by aksunder** [lovell/sharp#3389]
### What are you trying to achieve?

I have a SVG file. I want to convert it into 3 different sized PNG file.
Ex: 
SVG File:
sample.svg => height : 100 width:100
PNG Files:
small.png => height : 100 width:100
medium.png => height : 200 width:200
large.png => height : 300 width:300

medium & large PNGs look pixelated.

### When you searched for similar issues, what did you find that might be related?

I have tried the same in svg2png npm. That produces the PNGs with good quality. But Phantomjs makes more problem in ARM64 processors.
<
svg2png(sourceBuffer, { width, height })
      .then((buffer) => {
        fs.writeFileSync(`./${pngPath}/${name}.png`, buffer);
        return resolve(pngPath);
      })
>

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

  <
Method:1
export async function svgToPng(sourceBuffer, width, height, pngPath) {
    const smallPNGLocation = `./${pngPath}/small.png`;
    const mediumPNGLocation = `./${pngPath}/medium.png`;
    const largePNGLocation = `./${pngPath}/large.png`;
    await sharp(sourceBuffer).png().toFile(smallPNGLocation);
    await sharp(smallPNGLocation).resize(2 * width, 2 * height).toFile(mediumPNGLocation);
    await sharp(smallPNGLocation).resize(3 * width, 3 * height).toFile(largePNGLocation);
    return pngPath;
}

Method:2, Calling this method 3 times using promise.all with different dimensions.
#Tried with `fill`, `cover`, `contain`
export async function svgToPng(sourceBuffer, width, height, name, pngPath) {
    const pngLocation = `./${pngPath}/${name}.png`;
    await sharp(sourceBuffer).png().resize(width, height, { fit: 'fill' }).toFile(pngLocation);
    return pngPath;
}
 >

What am I missing?
![foot_shape](https://user-images.githubusercontent.com/114530270/192634702-137d6dee-9eb6-43a1-a343-9d4e2beb519d.svg)
![large](https://user-images.githubusercontent.com/114530270/192634839-399f2ef4-7a4c-4c6e-a6d6-3cff570385d0.png)
![medium](https://user-images.githubusercontent.com/114530270/192634843-81d5b5ed-2818-466f-8c9c-2f14279eedc0.png)
![small](https://user-images.githubusercontent.com/114530270/192634845-459608ed-b3d0-4f59-958b-386d72a63263.png)

**Comment by lovell** [comment]
Are you sure you're using the latest version of sharp? All versions from v0.30.0 onwards should automatically calculate the correct DPI to render at when resize/output dimensions are provided, to avoid pixelation.

**Comment by aksunder** [comment]
Great. That worked with the latest version v0.31.0 Thanks Lovell.
Btw, A Hi from Ex-`Science Direct` colleague.

**Comment by lovell** [comment]
Ha ha, I didn't realise it was you Ajay, great to hear from you!
