### ISSUE TITLE
Input File is missing

### ISSUE THREAD

**Issue by MohammadKoolivand** [lovell/sharp#3396]
Im using sharp to resize image but i got this error 

**[Error: Input file is missing:]**

    var { file } = req.files;
    if (req.files.file) {
      sharp(file)
        .resize({
          width: 438,
          height: 365,
        })
        .toFile("test_smal.jpg")
        .then(() => console.log("done..."))
        .catch((e) => {
          console.log("error...", e);
        });
    }

then i test this even with a relative address image like this

      sharp("./test.jpg")
        .resize({
          width: 438,
          height: 365,
        })
        .toFile("test_smal.jpg")
        .then(() => console.log("done..."))
        .catch((e) => {
          console.log("error...", e);
        });

![image](https://user-images.githubusercontent.com/48600357/193444020-17d6414a-734d-4e43-b972-fc3169256da5.png)

but i got this error too.

**[Error: Input file is missing: ./test.jpg]**

**"sharp": "^0.31.1"**

**Comment by lovell** [comment]
Relative filenames are relative to the current working directory, as provided by `process.cwd()`, which might not be the same as the directory your script is in.

**Comment by MohammadKoolivand** [comment]
Thanks. But what is the problem with file that comes from front-end request

**Comment by lovell** [comment]
No idea, sorry, you'll need to do some debugging to work out why `file` in your code is an empty string. This is unrelated to sharp.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
