### ISSUE TITLE
ExpressJs return file

### ISSUE THREAD

**Issue by TonhaoSantos** [lovell/sharp#3397]
I'm creating an endpoint in my rest api with expressJs that resizes the passed image.

The endpoint only works with images that are in a database.

Endpoint: domain/image-resize?width=number&height=number

When I test in insomnia (img 1), the img is shown in the return, as expected, but this process I'm using to show the image in the <img> tag with vuejs, that is, I'm passing the image returned by the api in the src of the <img tag >.

But it looks like I'm doing something wrong because a type of string (img 2) is returned that is not possible to use in the <img> tag

**img 1**
![1](https://user-images.githubusercontent.com/12022023/193580567-5ed291c0-cbd0-4463-9958-440acf1d319f.png)

**img 2**
![2](https://user-images.githubusercontent.com/12022023/193581063-5d9a40f8-6d7f-427f-a5a4-5ee9f1d72ba6.png)

**code**
```
   const transform = await sharp(imageBuffer).toFormat('png').resize(currentWidth, currentHeight)
    
    res.type(`${currentFormat}`)
    res.status(200)
    return transform.pipe(res)
```

I'm doing it in a way that I don't need to create a file on the server side to be able to return, do you know how I can do it in this case?

**Comment by lovell** [comment]
This isn't really a question about sharp but my best guess would be that you'll need to ensure the correct value in the `Content-Type` HTTP response header. If you need further help, perhaps try a more general site such as StackOverflow for this sort of question. Good luck!
