### ISSUE TITLE
Png foramt resizing question

### ISSUE THREAD

**Issue by axisotherwise** [lovell/sharp#3398]
## Question about an existing feature
Hello, I'm Yoon Seung Geun. 
Thanks to Sharp Image Resizing service, the screen rendering speed of our service has increased geometrically.
What I'm curious about is how the resizing logic of the png image works. Looking at the attached image,
I think the higher the file size, the more efficient it is, is that right? And sometimes the file size after resizing is higher than the file size before image resizing, how does this work? The above is a question about PNG, not JPG extension. 
Thank you. God bless you and God bless England

### What are you trying to achieve?

How does the png file resize?

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question
```javascript
const AWS = require("aws-sdk");
const sharp = require("sharp");

const s3 = new AWS.S3();

exports.handler = async (event, context, done) => {
    const Bucket = event.Records[0].s3.bucket.name;
    const Key = event.Records[0].s3.object.key;
    const filename = Key.split("/")[Key.split("/").length - 1];

    const ext = Key.split(".")[Key.split(".").length - 1];
    const format = ext === "jpg" ? "jpeg" : ext;

    try {
        const s3Object = await s3.getObject({ Bucket, Key }).promise();

        const { width } = await sharp(s3Object.Body).metadata();

        if (width < 600) {
            await s3.putObject(
                {
                    Bucket,
                    Key: `comment-resized/${filename}`,
                    Body: resizedImage,
                }
                ).promise();
        } else {
            const resizedImage = await sharp(s3Object.Body)
            .resize(600,  600, { fit: "inside" })
            .toFormat(format)
            .toBuffer();

            await s3.putObject(
                {
                    Bucket,
                    Key: `comment-resized/${filename}`,
                    Body: resizedImage,
                }
                ).promise();
        }

        return done(null, `comment-resized/${filename}`);
    } catch (error) {
        return done(error);
    }
};
```

### Please provide sample image(s) that help explain this question

<img width="635" alt="문의 이미지" src="https://user-images.githubusercontent.com/94421127/193829400-34b9ff21-274f-44cd-8603-09db766359ee.PNG">

**Comment by lovell** [comment]
> sometimes the file size after resizing is higher than the file size before image resizing, how does this work?

Perhaps experiment with palette-based (indexed) PNG output via `.png({ palette: true })`

https://sharp.pixelplumbing.com/api-output#png

**Comment by axisotherwise** [comment]
> > sometimes the file size after resizing is higher than the file size before image resizing, how does this work?
> 
> Perhaps experiment with palette-based (indexed) PNG output via `.png({ palette: true })`
> 
> https://sharp.pixelplumbing.com/api-output#png

Thank you for your answer. The experiment was based on the information obtained from the answers.

**_The following is a comparison of the palletter options._**

1. _**paletter: false**_
<br>

![image](https://user-images.githubusercontent.com/94421127/193872591-18a89632-d550-4954-a04e-d2ff4b05c415.png)
<br>

2. **_paletter: true_**
<br>

![image](https://user-images.githubusercontent.com/94421127/193872796-62be26eb-a70e-43e0-a039-a55dfd1d1fe2.png)
<br>

What is the difference between the resizing palletter option true and false in a png format image? Why is the file size bigger after resizing than before resizing if it is false? And if it's true, does the file size get smaller after resizing? I looked at the official website, and I think it's related to alpha transparency Could you give me a more detailed answer to this logic?

**Comment by lovell** [comment]
It all rather depends on the input images, so you'll need to experiment with the various options to find the best settings for you.

https://sharp.pixelplumbing.com/api-output#png

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
