### ISSUE TITLE
How to combine multiple tiff files into a single tiff file for the nodeJS project

### ISSUE THREAD

**Issue by rajeesab** [lovell/sharp#3399]
### What are you trying to achieve?
I want to merge/concatenate a multi-tiff(multiple pages) file into a single tiff file for the nodeJs project.
I didn't find any examples in the API documentation that seem to show this. I am looking for an example of how to process each page of a multi-page TIFF and merge into single file. If there is an example in the documentation that I've missed, please point me in the right direction. If there isn't, can someone please help me figure this out?

**Comment by lovell** [comment]
You'll require the future possible enhancement at #1580 for this - please subscribe to it for updates.
