### ISSUE TITLE
How do I output multiple resized images in multiple formats?

### ISSUE THREAD

**Issue by rchrdnsh** [lovell/sharp#3403]
So far I have been able to figure out how to take in an image and output multiple sizes, like so:

```js
const sharp = require('sharp')

const image = `beach`;
const format = `jpg`;

const resize = size => sharp(`${image}.jpg`)
  .resize({ width: size })
  .toFile(__dirname + `/processed/${image}-${size}.${format}`)
;

Promise
  .all([2160, 1920, 1440, 1080, 720, 480, 320].map(resize))
  .then(() => {
    console.log('Image resizing is complete.');
  });
```

...and it works just fine.

Now I want to be able to output multiple formats of each resized image as well (`avif` is the preferred choice, but `jpg` is the fallback kind of thing), but can't figure it out...

I've tried this so far:

```js
const sharp = require('sharp')

const image = `beach`;
const format = [`jpg`, `avif`]

const resize = size => sharp(`${image}.jpg`)
  .resize({ width: size })
  .toFile(__dirname + `/processed/${image}-${size}.${format[0]}`)
  .toFile(__dirname + `/processed/${image}-${size}.${format[1]}`)
;

Promise
  .all([2160, 1920, 1440, 1080, 720, 480, 320].map(resize))
  .then(() => {
    console.log('Image resizing is complete.');
  });
```

...but it seems that I cannot chain two `toFile`'s together?

Been googling around but have not found anything yet...

Any help is greatly appreciated, thank you XD

**Comment by lovell** [comment]
Perhaps try something like (untested):
```js
const resize = (width) =>
  Promise.all(
    format.map((f) =>
      sharp(`${image}.jpg`)
        .resize({ width })
        .toFile(__dirname + `/processed/${image}-${width}.${f}`)
    )
  );
```

**Comment by rchrdnsh** [comment]
aha! that worked great...i think i understand...for each width do a map of each format... 

I don't know anything about `Promise.all` however, so i will go learn about it now, but thank you :-)
