### ISSUE TITLE
Resize without scaling.

### ISSUE THREAD

**Issue by infacto** [lovell/sharp#3404]
## Feature request

This feature is about resizing the document/canvas without touching the source image.
Not sure if this is already possible. Maybe not with the `resize` method. Maybe with create method.
Anyway, in this example you want to resize a icon image to a greater size. E.g. from 256 px to 512 px.
You don't want to resize the image itself. You just want to change the dimension with a defined background.

![image](https://user-images.githubusercontent.com/60390085/195105226-66a1d260-8266-45c5-b73f-756b70421d76.png)

Here you see the icon (blue, 256px) resized to 512px (white background) without scaling the icon itself. Just an abstract demo.

In a graphic program you just would change the document / canvas size without resize the content. Smaller sizes will crop the image.

**Comment by lovell** [comment]
Hi, did you see https://sharp.pixelplumbing.com/api-resize#extend ?

**Comment by infacto** [comment]
Well, no. :) Sorry... Thanks it looks promising. So get an absolute dimension of the output, I need the source image size. So it would be great if this method also accepts width, height and position (top, center, bottom etc, or center only).

```ts
const outHeight = 512;
const inHeight = 256;
const outWidth = outWidth;
const inWidth = inWidth;

const extendOptions = {
  top: (outHeight - inHeight) / 2,
  bottom: (outHeight - inHeight) / 2,
  left: (outWidth - inWidth) / 2,
  right: (outWidth - inWidth) / 2,
  background: { r: 0, g: 0, b: 0, alpha: 0 },
}
```

Just a suggestion. Feel free to close if you don't want to. Thanks again. 👍
