### ISSUE TITLE
.tile() can customize the output filenames starting index ? 

### ISSUE THREAD

**Issue by ouzhou** [lovell/sharp#3405]
I hope the file name does not start from 0, 0, but uses the starting index I provide.
Or let me decide the name of each tile file, toFile(name) now can only appoint one name.

**Comment by ouzhou** [comment]
in my case , i just want to slice a big photo into many 256*256 imgs，use for-loop funciton to crop() and toFile() is slow , i tried tail(), it is faster , but i dont know how to control each tile name

**Comment by ouzhou** [comment]
@lovell 
i dont need any layout like google or dz,  i want customize filename and output path,  like this
```
.tile({
  outputName: (x,y)=>{ return `./path/${x}/${y}.png`}
}).toFile()
```

current only i can do is fs.rename() after tile()

**Comment by ouzhou** [comment]
closed , i open a other issue to 
https://github.com/lovell/sharp/issues/3416

**Comment by jcupitt** [comment]
> .tile({
>   outputName: (x,y)=>{ return `./path/${x}/${y}.png`}
> }).toFile()

Google layout names tiles as `z/y/x.png`, I don't know if that helps. Are you certain you need to put tiles in columns rather than rows?

Another option might be to generate to a zip file, then use some other module to extract the tiles to separate files with names you control.
