### ISSUE TITLE
Possible way to remove shadow

### ISSUE THREAD

**Issue by kresent** [lovell/sharp#3406]
### What are you trying to achieve?

Hello! Im trying to figure out the best way to help text recognition system. 
some users make photos with their fingers casting shadows over text and I would like to reduce this effect. 

Unfortunately basic gamma manipulation or normalization do not help. Maybe there is a way I can do it with the library?

### When you searched for similar issues, what did you find that might be related?

I tried using normalization, gamma, linear contrast, but the root cause is that some images are too bright and others too dark

**Comment by lovell** [comment]
Please can you provide a sample image.

**Comment by kresent** [comment]
<img width="197" alt="Screenshot 2022-10-14 at 12 36 27" src="https://user-images.githubusercontent.com/22170427/195801918-69c94cc0-8b65-4b5a-bfd5-8124be98f1f0.png">
I'm using Sharp to help the MRZ reading algorithm

Unfortunately it is very demanding and situations like in this image make text not recognizable. The issue here is the shadow dropping on the part of the text.

I tried linear, it helps but it ruins "normal", non-shadowed images, making them overexposed.
Adding a threshold is also not a valid option since some photos are dim, while others are super bright.

I guess the correct solution would be making the letters fully black while the everything else fully white, but I can not figure out what is the correct order of Sharp methods to chain.
It would be great help if you have any tips on useful methods to solve this case.

**Comment by lovell** [comment]
This looks like a luminance problem, so try `normalise()` to stretch it, then experiment with a suitable value for `threshold()`, plus maybe a small `blur()` to remove noise.

Here's an example applied to the provided image:
```js
await sharp('in.png')
   .normalise()
   .blur()
   .threshold(64)
   .toFile('out.png');
```
<img width="197" alt="out" src="https://user-images.githubusercontent.com/210965/195926609-011e7a14-17fb-48c5-9f4c-9f88b85e9376.png">

**Comment by kresent** [comment]
<img width="286" alt="Screenshot 2022-10-15 at 20 04 30" src="https://user-images.githubusercontent.com/22170427/195996561-a4f24d59-8802-4752-9fdc-3914250e2bad.png">

Thank you, but this unfortunately does not solve the issue – there are photos like this that are too light for the threshold.
If I set the threshold to 64, then the above photo gets almost all-white. If I raise the threshold, the initial photo gets big black spots where the shadow was and becomes unreadable.
This is the result I get for the lighter document 
<img width="388" alt="Screenshot 2022-10-15 at 20 10 35" src="https://user-images.githubusercontent.com/22170427/195996703-77a01042-24ad-4b64-a8c9-28d22dfa7cdc.png">


Maybe there is a way to make the numbers (0, 0, 0) – completely black, so that the shadows do not interfere with the numbers?

**Comment by lovell** [comment]
v0.32.0 provides new `lower` and `upper` percentile options on the `normalise()` operation that might help here. These can be used to clip more pixel values below/above limits, which could then make the `threshold()` operation provide better results.

https://sharp.pixelplumbing.com/api-operation#normalise

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
