### ISSUE TITLE
0.30.7 and later versions have strange transparency when converting PNG images.

### ISSUE THREAD

**Issue by yogarasu** [lovell/sharp#3408]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```txt
  System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.86 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.9.0 - ~/.volta/tools/image/node/18.9.0/bin/node
    Yarn: 3.2.1 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
    npm: 8.19.1 - ~/.volta/tools/image/npm/8.19.1/bin/npm
  npmPackages:
    sharp: ^0.31.1 => 0.31.1 
```

### What are the steps to reproduce?

Convert png images by sharp ver 0.31.1.
There was no problem until sharp ver 0.30.7.

### What is the expected behaviour?

I would expect the image to be converted without any weird transparency.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

I created a repo that I can reproduce bug.
https://github.com/yogarasu/test-sharp-bug

### Please provide sample image(s) that help explain this problem

![test](https://user-images.githubusercontent.com/68766032/195958387-30c022c8-9ef7-46ec-a583-130a6a5fcb64.png)

**Comment by lovell** [comment]
Hi, this looks like the same problem as #3395

**Comment by yogarasu** [comment]
Thank you, I will wait for the release of the fix.

**Comment by lovell** [comment]
Let's track this at https://github.com/lovell/sharp/issues/3395
