### ISSUE TITLE
Build error on Windows 10

### ISSUE THREAD

**Issue by aayushkapoor206** [lovell/sharp#341]
Whenever I try `npm install sharp`, I get the error:
```
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified.
```

**Comment by lovell** [comment]
Hello, which version of Visual Studio are you using? Perhaps check you have all the Windows prerequisites for node-gyp.

http://sharp.dimens.io/en/stable/install/#prerequisites
https://github.com/nodejs/node-gyp#installation

**Comment by aayushkapoor206** [comment]
I'm using VS Community 2015 and have set GYP_MSVS_VERSION=2015

**Comment by lovell** [comment]
Others are reporting similar experiences when compiling native modules with this combination, so I suspect this problem is not specific to sharp.

http://stackoverflow.com/search?tab=newest&q=TRK0005%20%22windows%2010%22

https://twitter.com/despair/status/679136039303278593

**Comment by aayushkapoor206** [comment]
Haha! The twitter status. :laughing: 

It finally worked after I manually installed Visual C++ 
https://msdn.microsoft.com/en-IN/library/60k1461a.aspx

I had originally skipped:
> Install Visual Studio Community 2015 Edition. (Custom Install, Select Visual C++ during the installation)

**Comment by lovell** [comment]
Great, glad you got it working.

**Comment by aayushkapoor206** [comment]
It plays nicely with `npm install sharp` but when I run it using any script, the result is :skull: :skull: :skull:
```python
line 402, in SelectVisualStudioVersion
   versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
   KeyError: '2015'
```

**Comment by lovell** [comment]
That looks like an error from the Python code in node-gyp. I think you'll need at least node-gyp v2.0.0 for MSVC 2015 support.

**Comment by aayushkapoor206** [comment]
I am using meteor 1.2.1 that comes with node 0.10.40 and npm 1.4.9 using `meteorhacks:npm` to install sharp. Works great on OS X and Ubuntu but on Windows, after updating node-gyp to latest, I get
`ERROR: ARM and 32-bit systems require manual installation`

**Comment by lovell** [comment]
Only 64-bit Windows is supported - http://sharp.dimens.io/en/stable/install/#windows - you'll probably need to ensure you're using the x86_64 version of Meteor.

**Comment by aayushkapoor206** [comment]
Meteor does not have an option for 64-bit installation. It runs 32-bit version of node. Is there any workaround?

**Comment by lovell** [comment]
sharp v0.11.4 was the last version to support 32-bit `node.exe` on Windows. libvips v8.1.1 was the last version to provide pre-built 32-bit binaries.

There are some archived manual installation details at http://sharp.dimens.io/en/v0.11.4/install/#windows but you're on your own from here. Good luck!

**Comment by aayushkapoor206** [comment]
Thanks for all the support @lovell! Really appreciate it.
Meteor might eventually use 64-bit node in later updates. Till then I'll stick to v0.11.4 :smile:
