### ISSUE TITLE
Support prefix-less EXIF metadata generated by some newer Apple devices

### ISSUE THREAD

**Issue by paxvista** [lovell/sharp#3412]
### What are you trying to achieve?

I have a PNG image with Exif data and despite using the withMetadata call, the resulting conversion to jpeg does not include the Exif data.

### When you searched for similar issues, what did you find that might be related?

There is similar issue with exif-reader that errors on reading the Exif buffer because it doesn't recognize the first few characters.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

const pngMetadata = await sharp(pngWithExif.png').metadata();
const pngExif = exifReader(pngMetadata.exif);
const pngToJpegImage = await sharp(pngWithExif.png').withMetadata().jpeg().toBuffer();
const jpegMetadata = await this.sharp(pngToJpegImage).metadata();          
const jpegExif = this.exifReader(jpegMetadata.exif); 
assert.equal(pngExif.gps, jpegExif.gps); // jpegExif gps is missing along with other exif image data 

### Please provide sample image(s) that help explain this question

Any png with exif data.

**Comment by paxvista** [comment]
![png](https://user-images.githubusercontent.com/1660531/196560199-bf19d244-ff5a-4236-adde-95442889f286.png)

**Comment by lovell** [comment]
Thanks, upstream fix for this at https://github.com/libvips/libvips/pull/3100
