### ISSUE TITLE
Is it possible to save to SVG?

### ISSUE THREAD

**Issue by dword-design** [lovell/sharp#3415]
### What are you trying to achieve?

I want to crop (using extract) an SVG file and save it back to an SVG.

### When you searched for similar issues, what did you find that might be related?

https://sharp.pixelplumbing.com/api-output

It says it will save to PNG.

**Comment by lovell** [comment]
No. SVG is a vector format, and when used as an input it is rasterised as a bitmap image before any further processing.

A possible method of "cropping" an SVG is to edit its `viewBox` attribute.

**Comment by dword-design** [comment]
@lovell Ok I did that. Thanks for clarifying!
