### ISSUE TITLE
Is there any way to specify the output file names for tile() method?

### ISSUE THREAD

**Issue by ouzhou** [lovell/sharp#3416]
I tried all the parameters of this `tile()` method, but it couldn't specify the name of every generated file. 
So I tried to use `fs.rename` to modify the file name after all files were generated
` fs.rename` was very slow. `tile()` cost only 800ms, but `fs.rename` took 1300ms

by the way,  i tried `extract()` in a loop to do the same thing like `tile()`,  i can use `extract()`  to specify output file name,  but it seems like very very slow to cut a large image by using extract

any help?

**Comment by lovell** [comment]
Is there a reason for a new issue rather than continue the discussion in #3405?

**Comment by lovell** [comment]
Closing as this has been discussed in #3405
