### ISSUE TITLE
PNG to AVIF. Prebuilt & custom-built sharp outputs larger file size w/ bigger `effort`

### ISSUE THREAD

**Issue by o-alexandrov** [lovell/sharp#3418]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 689.75 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
  npmPackages:
    sharp: 0.31.1 => 0.31.1 
```

or another system bearing the same problem:

```
  System:
    OS: Linux 5.15 Amazon Linux 2
    CPU: (8) arm64 unknown
    Memory: 6.85 GB / 7.76 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 16.17.1 - /var/lang/bin/node
    npm: 8.15.0 - /var/lang/bin/npm
```

### What are the steps to reproduce?

1. Install sharp with pre-built binaries
2. Use image from `example.png` with the provided code snippet.
3. Observe the console to see: the higher effort results in bigger file size

On my device(s), it prints as:

```
Effort 0 size: 342380
Effort 4 size: 356314
Effort 9 size: 361679
```

### What is the expected behaviour?

Increase in effort doesn't make the size bigger (at least keeps it the same as with the lower effort)

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```js
const checkEffortAndSize = async (effort) => {
  const cmd = sharp(`./example.png`)
  const buffer = await cmd
    .avif({ quality: 64, effort })
    .toBuffer()

  console.info(`Effort ${effort} size: ${buffer.byteLength}`)
}

await Promise.all([checkEffortAndSize(0), checkEffortAndSize(9)])
```

### Please provide sample image(s) that help explain this problem

[example.zip](https://github.com/lovell/sharp/files/9868174/example.zip)

**Comment by o-alexandrov** [comment]
Some notable aspects based on my testing:

- this issue happens for at least 20% of `PNG` files, but never for `JPEG`; based on a testing of about `~5000 JPEG and ~5000 PNG` files
- when creating a `custom-built` sharp tried to:
  - use both `libpng` and `libspng`; same outcome
  - use `built-into` libheif AVIF encoder and `libaom`; same outcome

**Comment by lovell** [comment]
Hi, this sounds more like the behaviour of libaom encoding rather than being specific to sharp.

If you're able to reproduce this at the command line using either libheif's `heif-enc --avif -p aom:speed=...` or libaom's `aomenc --cpu-used=...` then perhaps you could provide this image as an example on the AV1 discussion group at https://groups.google.com/a/aomedia.org/g/av1-discuss/ as there might be something that can be improved in the upstream library.

**Comment by o-alexandrov** [comment]
@lovell thank you for the helpful link and time saving tips on related CLI commands.
1. I will test using libaom directly, if the issue is in libaom, then will report to the libaom’s group discussion.
2. If running libaom directly doesn’t have an issue, will test libheif and report there
3. Then, will test libvips and then come back 😅

**Comment by o-alexandrov** [comment]
@lovell thank you for the help so far. Please kindly let me know how could I assist in finding the problem further.
Unfortunately, I'm not a C++ developer, so my capabilities are limited in this case.

Does this issue belong here or at [libvips](https://github.com/libvips/libvips)?

You'd get 9 identical in size files, if you run the following cmd, using: 
- the provided `example.png` from the initial message above
```sh
heif-enc --avif -p aom:speed=1 -o 1.avif example.png &&
heif-enc --avif -p aom:speed=2 -o 2.avif example.png &&
heif-enc --avif -p aom:speed=3 -o 3.avif example.png &&
heif-enc --avif -p aom:speed=4 -o 4.avif example.png &&
heif-enc --avif -p aom:speed=5 -o 5.avif example.png &&
heif-enc --avif -p aom:speed=6 -o 6.avif example.png &&
heif-enc --avif -p aom:speed=7 -o 7.avif example.png &&
heif-enc --avif -p aom:speed=8 -o 8.avif example.png &&
heif-enc --avif -p aom:speed=9 -o 9.avif example.png
```

**Comment by lovell** [comment]
I'd expect those file sizes to vary. What is the output of `heif-enc --avif --list-encoders` and `heif-enc --avif --params`?

**Comment by o-alexandrov** [comment]
```sh
$ heif-enc --avif --list-encoders
Encoders (first is default):
- aom = AOMedia Project AV1 Encoder v3.5.0
```

```sh
$ heif-enc --avif --params
Parameters for encoder `AOMedia Project AV1 Encoder v3.5.0`:
  realtime, default=false
  speed, default=5, [0;9]
  threads, default=4, [1;16]
  quality, default=50, [0;100]
  lossless, default=false
  chroma, default=420, { 420,422,444 }
  tune, default=ssim, { psnr,ssim }
  min-q, default=1, [1;62]
  max-q, default=63, [0;63]
  alpha-quality, [0;100]
  alpha-min-q, [1;62]
  alpha-max-q, [0;63]
  lossless-alpha, default=false
```

**Comment by o-alexandrov** [comment]
Seems like we should have passed a slightly different parameter to `libheif`:
- instead of `aom:speed=VALUE` just `speed=VALUE`

By running:
```sh
heif-enc --avif -p quality=64 -p speed=0 -o 0.avif example.png &&
heif-enc --avif -p quality=64 -p speed=1 -o 1.avif example.png &&
heif-enc --avif -p quality=64 -p speed=2 -o 2.avif example.png &&
heif-enc --avif -p quality=64 -p speed=3 -o 3.avif example.png &&
heif-enc --avif -p quality=64 -p speed=4 -o 4.avif example.png &&
heif-enc --avif -p quality=64 -p speed=5 -o 5.avif example.png &&
heif-enc --avif -p quality=64 -p speed=6 -o 6.avif example.png &&
heif-enc --avif -p quality=64 -p speed=7 -o 7.avif example.png &&
heif-enc --avif -p quality=64 -p speed=8 -o 8.avif example.png &&
heif-enc --avif -p quality=64 -p speed=9 -o 9.avif example.png
```

We get:
```sh
353K 0.avif
349K 1.avif
349K 2.avif
350K 3.avif
348K 4.avif
348K 5.avif
345K 6.avif
327K 7.avif
328K 8.avif
334K 9.avif
```

**Comment by o-alexandrov** [comment]
Based on the above and the initial message:

|          | sharp   | libheif |
|----------|---------|---------|
| effort 0 | 342,380 | 341,895 |
| effort 4 | 356,314 | 355,463 |
| effort 9 | 361,679 | 360,908 |

So it's an issue with `libaom`, I apologize for wasting your time here.
Maybe, to get something here for `sharp`, you might want to examine where those 0.5KB are coming from.
- I guess, it might be because of how `libheif` and `sharp` handle metadata by default

**Comment by lovell** [comment]
Thanks for the update, and no worries, as you say this is a question for the libaom maintainers.

The small file size difference probably relates to chroma subsampling (sharp defaults to 4:4:4, i.e. none, whereas libheif defaults to 4:2:0).

**Comment by o-alexandrov** [comment]
Just for the record, [libaom maintainers think](https://groups.google.com/a/aomedia.org/g/av1-discuss/c/YUNkemV2GB8) `libaom` is working as expected.
- they think `cpu-used` (their internal parameter that is connected to sharp's effort) should affect the processing quality, which in turn results in a different output
