### ISSUE TITLE
ppm for Electron on Win/Osx

### ISSUE THREAD

**Issue by andrzejbl** [lovell/sharp#3419]
### What are you trying to achieve?

I'm trying to provide ppm support for Electron app on Win/Osx.
I already tried custom vips build, vips all build. No success. Am I doing something wrong, or it won't work on Windows?

**Comment by lovell** [comment]
For Windows, you might be able to copy the DLLs from the "all" packages into the `node_modules/build/Release` directory, removing any other DLLs in there (but leaving `sharp-win32-x64.node`).

https://github.com/libvips/build-win64-mxe/releases/tag/v8.13.2

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
