### ISSUE TITLE
png images resample to new palette gets wrong colors

### ISSUE THREAD

**Issue by FalkNisius** [lovell/sharp#3420]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

  System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 47.71 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.10.0 - /usr/local/opt/node@18/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  npmPackages:
    sharp: ^0.31.1 => 0.31.1 

Comment: the issue occurs also on alpine x64 containers

### What are the steps to reproduce?

Resample a png image to a 256 color 8bit palette, with same sizes:
```
import sharp from 'sharp'

const sharpImage = sharp('test.png')
// sharpImage.resize({ width: 892 })

sharpImage.png({
  compressionLevel: 8,
  palette: true,
  colors: 256,
  force: true
})

await sharpImage.withMetadata({ density: 96, exif: {} }).toFile('test_resized.png')
```

### What is the expected behaviour?

From the original:
![test](https://user-images.githubusercontent.com/762203/198038785-9e1c5504-ef9a-4ec5-b4b1-3ef8191825b8.png)

Should have the result comparable colors.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

The result without the out commented resize is:
![test_resized](https://user-images.githubusercontent.com/762203/198038999-7fe82f90-d3a3-4ce0-a37a-8e43d55cd628.png)

look the code above.

If you include the resize job to the same size, all is running fine, as a work a round for the first.
But it looks like an uninitialized variable, or an unexpected image format in the underlying libvips.

**Comment by lovell** [comment]
Hi, this looks like the same problem as https://github.com/lovell/sharp/issues/3395

**Comment by FalkNisius** [comment]
Yes it looks similar, but there are some hints:

- in earlier times if i remember it right, png 256 color palette, was always RGB, never RGBA, but it can be changed
- if you add a sharpImage.resize({width: <width from metadata>}), to the conversion pipeline, the error is gone

I assume after the resize, all variables needed to finally resample the image are well setted, without the resize it depends on the image and the used standard if all is well prepared for the image writing or not. Because the most of my images are resampled fine, that are only a few of them, with that behavior.

**Comment by FalkNisius** [comment]
oh my mistake, the width must differ, i transposed inadvertently digits, so that a real resize job occurs

**Comment by lovell** [comment]
I've confirmed this is the same problem as #3395 - please subscribe to it for updates.
