### ISSUE TITLE
How is `limitInputPixels` applied to GIFs?

### ISSUE THREAD

**Issue by travisofthenorth** [lovell/sharp#3421]
## Question about an existing feature

What does `limitInputPixels` mean in the context of an animated GIF?

### What are you trying to achieve?

I am seeing `Error: Input image exceeds pixel limit` for an animated GIF with dimensions 1024x768. The GIF is very long though...the file size is almost 200MB.

I want to understand how this logic is applied to GIFs so I can raise/lower it appropriately.

### When you searched for similar issues, what did you find that might be related?

I saw [this issue](https://github.com/lovell/sharp/issues/1381), but I think they were just dealing with images.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

N/A

### Please provide sample image(s) that help explain this question

N/A

**Comment by lovell** [comment]
The `limitInputPixels` value is for the combination of all frames, rather than an individual frame size, so you should be able to multiply your required frame size limit by required frame count limit to get a suitable overall limit.

**Comment by travisofthenorth** [comment]
@lovell thanks for the response. So using the example above, a GIF of dimensions 1024x768 has a frame size of 786432 pixels. Taking the default value of `limitInputPixels` of 268402689, that results in a limit of 341 frames. Is that correct?

**Comment by lovell** [comment]
Yes, that sounds about right. This feature is to help protect against untrusted input that could quickly consume memory. If you trust the input, the limit can be removed entirely with `limitInputPixels: false`.
