### ISSUE TITLE
Enhancement: support development/unreleased versions of glibc (e.g. Fedora Rawhide 38)

### ISSUE THREAD

**Issue by josenobile** [lovell/sharp#3423]
### What are you trying to achieve?

Install sharp on Fedora rawhide which is using glibc 2.36.9000.0

### When you searched for similar feature requests, what did you find that might be related?

none

### What would you expect the API to look like?

To support glibc 2.36.9000.0 AND be more descriptive about texr errors, I took a while to discover the text error is about glibc version

### What alternatives have you considered?

Use a stable version of Fedora

### Please provide sample image(s) that help explain this feature

![root@JOSENOBILEmntcwampwwwFITCOFITCO-AUTH-MICROSERVICE](https://user-images.githubusercontent.com/1683657/199171975-e664b27e-68f2-4cd8-9662-bdd5531b594e.png)

**Comment by lovell** [comment]
I've created an upstream enhancement for this at https://github.com/lovell/detect-libc/issues/16

Fedora 38 is scheduled for its first release in April 2023, so we've got a few months to address this.

**Comment by kleisauke** [comment]
> Fedora 38 is scheduled for its first release in April 2023, so we've got a few months to address this.

Looking at the history of [`version.h` in glibc](https://sourceware.org/git/?p=glibc.git;a=history;f=version.h;hb=HEAD), it seems that the trailing patch component is only included for development releases. Fedora 37 would [ship with glibc 2.36](https://fedoraproject.org/wiki/Changes/GNUToolchainF37), I expect Fedora 38 ship with glibc 2.37 rather than this yet-to-be-released version.

**Comment by lovell** [comment]
Commit https://github.com/lovell/sharp/commit/0f1e7ef6f6e9097c481dbbf35b091bf92fcc3fed adds support for installation to flavours of Linux that include a patch in the version of glibc they report, which currently includes Fedora 38.

(The summary is that we will ignore the patch version as reported by the upstream detect-libc, which I think is the easiest/cleanest solution.)

**Comment by lovell** [comment]
v0.31.3 now available, thanks for the original report.

**Comment by GavinRay97** [comment]
@lovell Might I suggest slightly tweaking the error message to say `invalid GLIBC version` or similar?

I almost opened another issue until finding this one by chance, I was super confused why the same repo with a frozen `package.lock.json` worked on one machine but didn't on another -- I thought I was going crazy! 😅

**Comment by lovell** [comment]
@GavinRay97 As of v0.31.3 you should not see any error. The message itself came from the underlying `semver` library, so I'm not sure how much we can do other than perhaps prefix it, but hopefully the logic is much tighter around glibc version handling now and we won't see it again.

**Comment by GavinRay97** [comment]
Ah understood, my apologies for the ping then!

Damn Node.js ecosystem I swear, I program in half a dozen other languages and nothing is as much a tangled fragile mess, haha.
