### ISSUE TITLE
"VipsJpeg: Premature end of input file" if use JPEG File Interchange Format(JFIF) file.

### ISSUE THREAD

**Issue by icemanpro** [lovell/sharp#3424]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [ ] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?
```
  System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
    Memory: 20.36 GB / 31.95 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: ^0.31.1 => 0.31.1
```

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```
const sharp = require('sharp')

async function run() {
 sharp(file_name).toFormat('png').toFile("D:\a.png");
}
run()
```

### Please provide sample image(s) that help explain this problem

![20220103sy4xsw1pjf-image](https://user-images.githubusercontent.com/1924688/199182573-1ef2b0a4-2930-4aa9-8fe1-06227837bca8.jpg)

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
