### ISSUE TITLE
 sharp: Installation error: EACCES: permission denied, mkdir '/root/.npm'

### ISSUE THREAD

**Issue by EvolutionAR** [lovell/sharp#3428]
path /seatom/seatom-server/resource-server/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c -- (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Are you trying to install as a root or sudo user?
npm ERR! sharp: - For npm <= v6, try again with the "--unsafe-perm" flag
npm ERR! sharp: - For npm >= v8, the user must own the directory "npm install" is run in
npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! sharp: Installation error: EACCES: permission denied, mkdir '/root/.npm'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-11-03T12_26_50_989Z-debug-0.log

**Comment by EvolutionAR** [comment]
Linux arm-build 4.18.0-80.7.2.el7.aarch64 #1 SMP Thu Sep 12 16:13:20 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux

**Comment by lovell** [comment]
Please follow the instructions for opening an installation issue as already provided to you in #3426 - the questions it asks will help you help yourself, and the answers you provide help me help you.
