### ISSUE TITLE
'npm install' fails on Ubuntu 15.10, Node v5.5.0, NPM v3.5.3

### ISSUE THREAD

**Issue by modomodo** [lovell/sharp#343]
Hi!
I'm trying to use this package as a dependency of the [gulp-responsive](https://github.com/mahnunchik/gulp-responsive#installation) plugin that I would like to use.

However, the installation fails with the following errors:
``` Shell
> sharp@0.12.2 install '[redacted]/Project-Part-1/node_modules/sharp/build'
> node-gyp rebuild

make: Entering directory
CXX(target) Release/obj.target/sharp/src/common.o
g++: error: [redacted]/Project-Part-1/node_modules/sharp/include: No such file or directory
g++: error:  [redacted]/Project-Part-1/node_modules/sharp/include/glib-2.0: No such file or directory
g++: error:  [redacted]/Project-Part-1/node_modules/sharp/lib/glib-2.0/include: No such file or directory
sharp.target.mk:109: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: *** [Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory 

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.0-25-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 

npm ERR! Linux 4.2.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save-dev" "gulp-responsive"
npm ERR! node v5.5.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.12.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.12.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
```

I can confirm that I have the latest version of Node and NPM. What exactly is causing the package to fail the installation process, even with everything updated?

**Comment by lovell** [comment]
Hi Michael, my best guess is that something went wrong during the download of the pre-compiled libvips binaries at install time, although this should generate an error.

Does this machine have Internet access?

What happens when you run the following at the command line when in the `[redacted]/Project-Part-1/node_modules/sharp` directory?

```sh
npm_package_config_libvips=8.2.0 node -e "require('./binding').download_vips()"
```

**Comment by modomodo** [comment]
Hi Lovell.

I repeated the installation of the [gulp-responsive](https://github.com/mahnunchik/gulp-responsive#installation) after pre-installing (node-gyp)[https://github.com/nodejs/node-gyp] globally, and the problem seems to have resolved itself! :sunny: 

However, I wonder, should (node-gyp)[https://github.com/nodejs/node-gyp] be pre-installed globally? Isn't it a dependency of `sharp`?

**Comment by lovell** [comment]
Glad to hear you got it working, this was probably a temporary network problem.

`node-gyp` [is a dependency](https://github.com/npm/npm/blob/master/package.json#L67) of `npm` itself, so you shouldn't need to install it manually.

**Comment by Tempurturtul** [comment]
I've been collaborating with modomodo and we've found that this problem occurs when spaces exist in folder names.  Removing the spaces resolved the issue.

**Comment by modomodo** [comment]
I concur... the spaces in the directory does result in some strange errors. All directories right done from home need to have no spaces in the name

**Comment by lovell** [comment]
Thanks for the update - this looks like an example of https://github.com/nodejs/node-gyp/issues/65
