### ISSUE TITLE
Why does calling sharp.composite twice with different image generate same output?

### ISSUE THREAD

**Issue by ghints** [lovell/sharp#3430]
### What are you trying to achieve?

I am generating 4 images (called "chart.png"/"chart1h.png"/"chart15m.png"/"chart1m.png")
Then calling sharp to combine 4 images to one output.
It works amazing on the first homemade method (generateImage) call.
However, when I run the same generateImage method again with different argument,
which updates 4 images then runs sharp again, 
**sharp generates the same old output instead of new one**

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

input.png is simple 1600x1200 white background image

```
const generateImage = async (ticker:string): Promise<void> => {
    // ... code that generates "chart.png"/"chart1h.png"/"chart15m.png"/"chart1m.png"
    await sharp("input.png")
        .composite([
            { input: "chart.png", gravity: "northwest" },
            { input: "chart1h.png", gravity: "northeast" },
            { input: "chart15m.png", gravity: "southwest" },
            { input: "chart1m.png", gravity: "southeast" }
        ])
        .toFile("output.png");
};

generateImage("BTCBUSD");
// do stuff with generated image
generateImage("ETHBUSD"); // !!!!!!!!! AFTER THIS, the output.png is still image from first call
```

I attempted to use following but had no luck on second run on

```
await sharp({ create: { width: 1600, height: 1200, channels: 3, background: { r: 0, g: 0, b: 0 } } })
        .composite( // ... rest are same
```

### Please provide sample image(s) that help explain this question

![output](https://user-images.githubusercontent.com/98143886/199800808-b60f7363-a6ab-4212-8a14-2a58040eb284.png)

**Comment by arnhrwd** [comment]
I've only just starting using sharp but try removing image caching? I think if you are reading/writing to the same files then previously files that have been read may have been cached and reused.

sharp.cache(false)

**Comment by ghints** [comment]
Thank you so much!!! That solved it!
