### ISSUE TITLE
Cropping images may lead to larger file sizes

### ISSUE THREAD

**Issue by Alexnortung** [lovell/sharp#3432]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

(0.31.1)

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Linux 5.15 NixOS 22.05 (Quokka) 22.05 (Quokka)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 7.32 GB / 15.36 GB
    Container: Yes
    Shell: 5.8.1 - /run/current-system/sw/bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nix-profile/bin/node
    npm: 8.11.0 - ~/.nix-profile/bin/npm
```

### What are the steps to reproduce?

This is an issue when trying to resize an image with Strapi. I am not 100% familiar with the source code of the project, but I will try to give some examples.

For reproducible steps in strapi see: https://github.com/strapi/strapi/issues/14457

1. Find an image (https://i.redd.it/tp2z5z6106p91.png) (file size: ~450kb)
2. Go to tinypng.com and upload the image (optimized file size: ~132kb)
3. Resize the image with sharp (520x675, fit: inside)
4. Observe the new file size (~524kb)

### What is the expected behavior?

I expected that the file size would get smaller and definitely not increase in size.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

-

### Please provide sample image(s) that help explain this problem

check https://github.com/strapi/strapi/issues/14457

or 

https://i.redd.it/tp2z5z6106p91.png

**Comment by lovell** [comment]
The service provided by tinypng performs a lossy, quantisation conversion to palette-based output.

If you want the resized output from sharp to also be a palette-based PNG, perhaps alter your workflow to remove tinypng entirely and allow sharp to perform both the resize and the quantisation.

```js
const data = await sharp(input)
   .resize({ ... })
   .png({ palette: true })
   .toBuffer();
```
This will help ensure no quality loss prior to resizing, and in most cases provide a smaller file size, albeit lossy at the final step.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
