### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by EvolutionAR** [lovell/sharp#3434]
### What is the complete output of running npm install --verbose --foreground-scripts sharp in an empty directory?

658 info run sharp@0.30.7 install { code: 1, signal: null }
659 timing reify:rollback:createSparse Completed in 87ms
660 timing reify:rollback:retireShallow Completed in 0ms
661 timing command:i Completed in 8632ms
662 verbose stack Error: command failed
662 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
662 verbose stack     at ChildProcess.emit (node:events:513:28)
662 verbose stack     at maybeClose (node:internal/child_process:1100:16)
662 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
663 verbose pkgid sharp@0.30.7
664 verbose cwd /seatom/seatom-server/resource-server
665 verbose Linux 4.18.0-80.7.2.el7.aarch64
666 verbose node v16.18.0
667 verbose npm  v8.19.2
668 error code 1
669 error path /seatom/seatom-server/resource-server/node_modules/sharp
670 error command failed
671 error command sh -c -- (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
672 error sharp: Are you trying to install as a root or sudo user?
672 error sharp: - For npm <= v6, try again with the "--unsafe-perm" flag
672 error sharp: - For npm >= v8, the user must own the directory "npm install" is run in
672 error sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
673 error sharp: Installation error: EACCES: permission denied, mkdir '/root/.npm'
674 verbose exit 1
675 timing npm Completed in 8757ms
676 verbose unfinished npm timer reify 1667530409399
677 verbose unfinished npm timer reify:build 1667530417651
678 verbose unfinished npm timer build 1667530417652
679 verbose unfinished npm timer build:deps 1667530417652
680 verbose unfinished npm timer build:run:install 1667530417662
681 verbose unfinished npm timer build:run:install:node_modules/sharp 1667530417670
682 verbose code 1
683 error A complete log of this run can be found in:
683 error     /root/.npm/_logs/2022-11-04T02_53_29_275Z-debug-0.log 

### What is the output of running npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp?

Linux 647135d47c0d 4.18.0-80.7.2.el7.aarch64 #1 SMP Thu Sep 12 16:13:20 UTC 2019 aarch64 Linux

**Comment by EvolutionAR** [comment]
## docker info
 Containers: 26
  Running: 6
  Paused: 0
  Stopped: 20
 Images: 638
 Server Version: 19.03.9
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.18.0-80.7.2.el7.aarch64
 Operating System: CentOS Linux 7 (AltArch)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 15.38GiB
 Name: arm-build
 ID: DEL6:3WN5:TRWD:T4NX:J72U:VOIH:SOJH:CIAQ:GKZW:U3GK:BGBA:5LDW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true

**Comment by lovell** [comment]
This is the third issue you've opened in the last 24 hours that ignores the installation issue template.

#3426 #3428

The issue template you have repeatedly ignored asks the question:

> If you are using npm v7 or later, does the user running `npm install` own the directory it is run in?

The error message you have posted says:

> For npm >= v8, the user must own the directory "npm install" is run in

This is probably the cause, but by ignoring the questions asked, and not providing answers, you've wasted both of our time, which means I'm going to have to block you from opening further issues on this repo.
