### ISSUE TITLE
Understanding Compositing of PNG over GIF

### ISSUE THREAD

**Issue by xsalazar** [lovell/sharp#3435]
### What are you trying to achieve?
I want to overlay a PNG with a transparency layer on top of a GIF without blending color layers but respecting transparency layers (if that makes sense and is possible).

Ideally, I'm trying to accomplish something similar to [ImageMagick's composite](https://imagemagick.org/script/composite.php) which seems like it overlays without blending layers, but still respecting the alpha transparency. It's hard to describe, but hopefully the GIFs below illustrate what I'm seeing versus what I want to get to, if possible.

Reading the documentation, it seemed like `source` is the blend mode that would do this for me, but it's not working how I imagined. Specifically where the overlay transparency would show the background underneath. Instead, it's behaving as if it's replacing the underlying background _with_ a transparency layer. What's odd here is the overlay still looks like it's blended the colors, so the background is having _some_ impact on the composition.

### When you searched for similar issues, what did you find that might be related?
- https://www.cairographics.org/operators/
- https://github.com/lovell/sharp/issues/618
- https://github.com/lovell/sharp/issues/3347
- https://github.com/lovell/sharp/issues/3206
- https://github.com/lovell/sharp/issues/2680

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question
```javascript
await sharp(backgroundPath, {
        animated: true,
      })
        .composite([
          {
            input: overlayPath,
            tile: true,
            top: 0,
            left: 0,
          },
        ])
        .toFile(outputPath);
```

#### Background GIF
![background](https://user-images.githubusercontent.com/14851080/200041081-9d5dd998-4f3b-4ccd-8ef4-45d7f0d99b01.gif)

#### Overlay PNG
![overlay](https://user-images.githubusercontent.com/14851080/200041141-d7f00e73-14cc-4236-951f-1577428f2348.png)

##### `over` blend mode
![combined-cS8Dk5NywlGLvaIV0r-over](https://user-images.githubusercontent.com/14851080/200041735-fca0d5b9-a2dd-4725-aa42-c885e9ee909c.gif)

##### `source` blend mode
![combined-cS8Dk5NywlGLvaIV0r-source](https://user-images.githubusercontent.com/14851080/200042188-82063c19-d4b2-4445-b441-eb39de214143.gif)

##### What I'm Looking to Accomplish
![ezgif com-gif-maker](https://user-images.githubusercontent.com/14851080/200042954-63de68a4-79d3-4bc4-b434-b2358f28a963.gif)

**Comment by xsalazar** [comment]
Closing this as I could never find an answer down this route. I ended up shelling out the command to the ImageMagick shell `convert` to accomplish this: https://github.com/xsalazar/image-wower/blob/main/app/app.js#L94-L96

**Comment by lovell** [comment]
Hi, sorry, I must have missed this question first time around.

This looks like a GIF palette optimisation problem. With the latest sharp v0.31.3 you'll need to add the following to your pipeline:
```js
  .gif({ reoptimise: true })
```

https://sharp.pixelplumbing.com/api-output#gif

From the next v0.32.0 release, `reoptimise` will be renamed `reuse`, but more importantly, it will automagically select the best option for you when compositing images so this problem goes away.

**Comment by xsalazar** [comment]
@lovell Thanks for the tip! I'll have to try this out soon to see if that fixes the problem. If so, you're going to save me so much headache, time, and money from how I managed to get this running in AWS.

**Comment by xsalazar** [comment]
@lovell I just wanted to thank you for being so responsive, and your tip above did solve my issue (though I ultimately pivoted away from `.gifs` altogether. ❤️ 

Just to give some context to this question, I work at Slack, and there's a long-standing in-"joke" to make :wow-emoji: for folks when we want to celebrate them, think they're neat, or just want to show that we think they're awesome. There's more detail in [this LinkedIn post](https://www.linkedin.com/posts/bradfordrjordan_wow-emojis-a-brief-history-once-upon-activity-6995975051451789312--teY) by the person who started the tradition.

At work, I make a lot of custom emoji for all sorts of silly reasons, but I also found myself in a position where I was creating a lot of these :wow-emoji: manually for people who wanted to spread joy. As any good engineer, after I did the first few hundred by hand, I thought to myself I could definitely automate this.

I took a few stabs, and ended up with an application that worked pretty well, but was running me about $60/mo. in AWS 🤯 I mostly got stuck on _this_ issue I filed here, and had to use a hacky workaround that needed a server running 24/7.

After your response, and seeing it worked, I was determined to engineer a better solution since I no longer needed the hacky workaround. That solution lives in https://github.com/xsalazar/image-wower and, while complex, works decently well! And, most importantly, it should be completely free now 💸

Though the point of this post is larger. I use your library for a lot of my little projects, and it's indispensable -- it's the first library I grab when I need to work with any sort of images. Your work supports https://wowemoji.dev, https://emojimosaic.dev/ and https://downloademoji.dev (currently not working because... Twitter).

All that to say, I made you a :wow-emoji: just to show that I think the work you do is awesome. If you use Slack, you can upload this file as a [custom emoji](https://slack.com/help/articles/206870177-Add-custom-emoji-and-aliases-to-your-workspace). If you don't use Slack, you can show your neighbor or print it out and hang it on your fridge.

![wow-lovell](https://user-images.githubusercontent.com/14851080/212522586-4105de28-01da-4323-866c-a060d5766c21.gif)

**Comment by lovell** [comment]
Ha ha, that's amazing, thank you very much Xavier.
