### ISSUE TITLE
Gulp error install sharp 

### ISSUE THREAD

**Issue by SergeyShurkhovetckii** [lovell/sharp#3437]
- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

install M1 -error .

When   "npm install --ignore-scripts=false --verbose sharp" error repeat .

**Comment by lovell** [comment]
Hello, the installation issue template appears to have been ignored and/or deleted. Please open a new installation issue and provide answers to all of the questions.

https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md
