### ISSUE TITLE
Globally-installed `libvips` w/ `sharp`. How to: minify `build/Release` & reproduce `vendors` from prebuilt installation

### ISSUE THREAD

**Issue by o-alexandrov** [lovell/sharp#3439]
- [x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.
- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

<details>
  <summary>$ npm install --verbose --foreground-scripts sharp</summary>

```sh
npm verb cli /var/lang/bin/node /var/lang/bin/npm
npm info using npm@8.15.0
npm info using node@v16.17.1
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/var/lang/lib/node_modules/npm/npmrc Completed in 2ms
npm timing config:load:builtin Completed in 3ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/var/task/.npmrc Completed in 0ms
npm timing config:load:project Completed in 5ms
npm timing config:load:file:/root/.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:/var/lang/etc/npmrc Completed in 1ms
npm timing config:load:global Completed in 1ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 13ms
npm timing npm:load:configload Completed in 13ms
npm timing npm:load:mkdirpcache Completed in 1ms
npm timing npm:load:mkdirplogs Completed in 1ms
npm verb title npm install sharp
npm verb argv "install" "--loglevel" "verbose" "--foreground-scripts" "sharp"
npm timing npm:load:setTitle Completed in 1ms
npm timing config:load:flatten Completed in 2ms
npm timing npm:load:display Completed in 6ms
npm verb logfile logs-max:10 dir:/root/.npm/_logs
npm verb logfile /root/.npm/_logs/2022-11-07T08_34_18_709Z-debug-0.log
npm timing npm:load:logFile Completed in 4ms
npm timing npm:load:timers Completed in 0ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load Completed in 27ms
npm timing arborist:ctor Completed in 0ms
npm timing idealTree:init Completed in 44ms
npm timing idealTree:userRequests Completed in 1ms
npm timing arborist:ctor Completed in 1ms
npm http fetch GET 200 https://registry.npmjs.org/sharp 381ms (cache miss)
npm timing idealTree:#root Completed in 390ms
npm timing idealTree:node_modules/sharp Completed in 0ms
npm timing idealTree:buildDeps Completed in 390ms
npm timing idealTree:fixDepFlags Completed in 0ms
npm timing idealTree Completed in 438ms
npm timing reify:loadTrees Completed in 439ms
npm timing reify:diffTrees Completed in 4ms
npm timing reify:retireShallow Completed in 2ms
npm timing reify:createSparse Completed in 0ms
npm timing reify:loadBundles Completed in 0ms
npm timing reify:unpack Completed in 1ms
npm timing reify:unretire Completed in 0ms
npm timing build:queue Completed in 0ms
npm timing build:deps Completed in 0ms
npm timing build Completed in 1ms
npm timing reify:build Completed in 1ms
npm timing reify:trash Completed in 0ms
npm timing reify:save Completed in 11ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 500ms
npm timing auditReport:getReport Completed in 504ms
npm timing auditReport:init Completed in 0ms
npm timing reify:audit Completed in 507ms
npm timing reify Completed in 960ms

up to date, audited 46 packages in 1s

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm timing command:install Completed in 968ms
npm verb exit 0
npm timing npm Completed in 1051ms
npm info ok 
```

</details>

<details>
  <summary>$ npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp</summary>
  
```sh
  System:
    OS: Linux 5.15 Amazon Linux 2
    CPU: (8) arm64 unknown
    Memory: 6.73 GB / 7.76 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 16.17.1 - /var/lang/bin/node
    npm: 8.15.0 - /var/lang/bin/npm
  npmPackages:
    sharp: ^0.31.2 => 0.31.2 
```
</details>

## Problem

When installing `sharp 0.31.2` with a globally-installed `libvips 8.13.3`:
- the output in `node_modules/sharp` is different comparing to the case when sharp downloads a pre-built `libvips`

The `PLATFORM` below is `linux-x64` for the details mentioned in the previous CLI commands.
1. When sharp downloads prebuilt `libvips`, `node_modules/sharp` has:
    - `build` directory, with a single file `Release/sharp-PLATFORM.node`
    - `vendor`, with few files, but the only usable file is `LIBVIPS_VERSION/PLATFORM/lib/libvips-cpp.so.42`

2. When sharp finds a globally-installed `libvips`, `node_modules/sharp` has:
    - `build` directory, with tens of different files, along with many duplicates, but also includes the same `Release/sharp-PLATFORM.node`
    - and there's no `vendor` directory, as sharp doesn't copy this file from the globally-installed location, in my case `usr/local/lib/libvips-cpp.so.42`

## Questions

Would the following steps break `sharp` or `libvips`?

In `node_modules/sharp` directory after installation of `sharp` w/ a globally-installed `libvips`:
- cleanup `build` directory, only leaving `Release/sharp-PLATFORM.node`
- and create `vendor` directory, copying `libvips-cpp.so.42` from `/usr/local/lib`

And after the steps above, zipping `node_modules` directory, and using it on a machine where global installation of `libvips` didn't happen (ex. in my case, using it as an AWS Lambda layer)

**Comment by lovell** [comment]
> cleanup build directory, only leaving Release/sharp-PLATFORM.node

Yes, the other files are build artefacts.

> and create vendor directory, copying libvips-cpp.so.42 from /usr/local/lib

You could, but you'd need to ensure the `sharp-PLATFORM.node` file has the directory set in its rpath at link time.

https://github.com/lovell/sharp/blob/9fa516e8496d96fc12a4cba25216e467e36d62b7/binding.gyp#L165-L168

**Comment by o-alexandrov** [comment]
Thank you very much, I'll attempt to make it to work on my end first and then, if it works, will create a PR to apply the same steps when `sharp` identifies a globally-installed `libvips`.
- cleaning up `build` by default
- and copying `libvips`, if a new environment variable is passed (ex. `COPY_GLOBAL_LIBVIPS`)

**Comment by lovell** [comment]
Logic to clean up temporary files in the `build` directory belongs in https://github.com/nodejs/node-gyp as it put them there.

Logic to copy around custom libvips shared libraries that may or may not have the correct rpath feels a bit too error-prone and niche for me to maintain, so I'm unsure that would be merged, but thanks for the offer.

**Comment by o-alexandrov** [comment]
Got it, thank you.
I respect your decision; though, imho, `build` directory should probably be identical, no matter the type of installation
