### ISSUE TITLE
Extract not always extracting from the correct positions.

### ISSUE THREAD

**Issue by timb-103** [lovell/sharp#3443]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 17.52 GB / 31.96 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE      
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD        
    npm: 8.5.4 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: 0.31.2 => 0.31.2

### What are the steps to reproduce?

Unfortunately I can't reproduce it, but it's been happening occasionally to my users. Have tried everything possible to reproduce, including using the same devices as my users that reported the issues.

Hoping that you may have some idea of what's going on!

### What is the expected behaviour?

Expected behaviour is to crop the image (using extend()) as the correct positions. Occasionally, it's being cropped incorrectly and the output image is wrong. Sometimes it looks like it just crops from the top left corner.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem
Here's the data I use for cropping (width, height, x, y):

```
croppedData: {
  height: 1280,
  width: 1280,
  x: 343,
  y: 0,
  aspectRatio: 1,
  scaleX: 1,
  scaleY: 1,
  rotate: 0,
  originalImage: {
    naturalWidth: 1920,
    naturalHeight: 1280,
    aspectRatio: 1.5,
    width: 298,
    height: 198.66666666666669,
    left: 0,
    top: -1.4210854715202004e-14
  }
}
```

And here's the function I use for cropping:

```
const croppedImage = await sharp(buffer)
.extract({
   width: parseInt(Math.floor(width)),
   height: parseInt(Math.floor(height)),
   left: parseInt(Math.floor(x)),
   top: parseInt(Math.floor(y)),
})
.toBuffer({ resolveWithObject: true })
```

And here's the output after cropping:

```
croppedImage: {
  format: 'jpeg',
  width: 1280,
  height: 1280,
  channels: 3,
  premultiplied: false,
  size: 245724
}
```

In the case of this example, the image was cropped what looks like ~20px further to the left than it was supposed to.

### Please provide sample image(s) that help explain this problem

The cropping process, image is perfectly centered:

https://ibb.co/QpCmj25

After the extract() the image is slightly off center to the left now:

https://ibb.co/sWJbXy3

**Comment by lovell** [comment]
Please can you provide the specific input image that relates to these values to allow someone else to reproduce.

**Comment by timb-103** [comment]
Hey Lovell,

Yeah sure - here's the same one from that example: https://sharemyinsights.azureedge.net/app/392583254957685/xxIeqvsqgz/scheduling/nIHJGzYnUQ

The issue is, I was never able to reproduce it from my end so that's the biggest problem. My users have been occasionally reporting this issue, and sending videos of it happening but I can't do it so I'm not exactly sure what's happening.

**Comment by lovell** [comment]
Thanks, here's the output I see locally when using `.extract({ width: 1280, height: 1280, left: 343, top: 0 })`:

![](https://user-images.githubusercontent.com/210965/200774980-ddcbd8c9-d8cc-49d5-9c45-7108bee98eac.jpg)

Is this the expected output?

> Unfortunately I can't reproduce it

If you can't reproduce it and I can't reproduce it then this is unlikely to be a bug in sharp.

**Comment by timb-103** [comment]
Alright, I'll continue to investigate then.

Love what you're doing with Sharp - thanks for your help!
