### ISSUE TITLE
Enlargement is slow even though withoutEnlargement is specified

### ISSUE THREAD

**Issue by travisofthenorth** [lovell/sharp#3445]
## Question about an existing feature

What happens when attempting to increase the size of a GIF when `withoutEnlargement` is true? Why would that take a long time (seconds) as opposed to being nearly instantaneous?

### What are you trying to achieve?

I have a GIF resizer, but I don't allow the size of the image to be increased. I set `withoutEnlargement` expecting the result to be the original image if a request tries to increase a dimension. The output is the same image, but it takes as long as a normal resize operation.

### When you searched for similar issues, what did you find that might be related?

Couldn't find anything

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```
const inStream = ...grab image from S3 (this request takes a few hundred ms)...

let transformer = sharp({ animated: true, failOnError: false })
transformer = transformer.resize({ width: 10000, withoutEnlargement: true })
transformer = transformer.gif()

inStream.pipe(transformer)
buffer = await transformer.toBuffer()
```

### Please provide sample image(s) that help explain this question

Any GIF should work. I'm testing with an ~8MB gif that's about 4-5 seconds long.

**Comment by lovell** [comment]
> Why would that take a long time (seconds) as opposed to being nearly instantaneous?

The input will always be decoded and the output will always be encoded, regardless of the operations that need to occur, if any. Encoding an 8MB animated GIF file is probably the bottleneck here.

**Comment by travisofthenorth** [comment]
@lovell thanks for the quick response! I guess I could just use the [metadata API](https://sharp.pixelplumbing.com/api-input) and skip the transform.

If anyone encounters this, you could modify the code above with something like:
```
inStream.pipe(transformer)

const metadata = await transformer.metadata()
if (withoutEnlargement && metadata.width < requestedWidth) {
  // skip transform
}
```

**Comment by travisofthenorth** [comment]
@lovell quick question. Is it expected that `.metadata()` throws transform errors (like `Input image exceeds pixel limit`)? I wasn't expecting to have to catch exceptions when using it.

**Comment by lovell** [comment]
Yes, it is a safety feature and all input is verified against this limit. A few of the more esoteric formats sometimes require pixel data to be decoded when determining metadata (e.g. custom libvips with support for *magick).
