### ISSUE TITLE
WSI not being converted to DZ file

### ISSUE THREAD

**Issue by NelsonFaria14** [lovell/sharp#3447]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 2.07 GB / 15.76 GB
  Binaries:
    Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: ^0.31.2 => 0.31.2
```

### What are the steps to reproduce?

1. Create a new folder
2. Inside it, run the command `npm install sharp`
3. Create a file with the provided code
4. Run `node ./<filename>.js`

### What is the expected behaviour?

The Aperio SVS image should be loaded and converted into a DZ file successfully.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```javascript
const sharp = require('sharp');

sharp('WSI.svs', { limitInputPixels: false })
    .toFile('./output.dz', (err, info) => {
        console.log(err);
        console.log(info);
    });
```

### Error

`Error: jp2k: libvips built without JPEG2000 support`

**Comment by lovell** [comment]
The prebuilt binaries provided by sharp do not include support for OpenSlide or JPEG2000.

You'll need to build your own libvips, and please note this is unsupported on Windows.

https://sharp.pixelplumbing.com/install#custom-libvips
