### ISSUE TITLE
Possible race condition in metadata() when using Stream-based input

### ISSUE THREAD

**Issue by lucakcustom** [lovell/sharp#3451]
Considering the following code
```
const image_path = "./Images/128x128.png"
const test = async() => {
    const image1 = sharp(image_path).pipe(sharp())
    const image2 = sharp(image_path).pipe(sharp())
    const data1 = await image1.metadata()
    console.log(data1)
    const data2 = await image2.metadata()  // on this instruction the node interpreter will exit
    console.log(data2)
}
```
When we await for the metadata of data2 the node interpreter will immediately exit without any error. I tried to debug it but I could not find the point in which the node interpreter is closed (I might assume this happens in native, but I'm not sure).

This issue never happens if we work on different images so the following code is totally fine and works as expected

```
const image_path = "./Images/128x128.png"
const image_path_2 = "./Images/256x256.png"

const test = async() => {
    const image1 = sharp(image_path).pipe(sharp())
    const image2 = sharp(image_path_2).pipe(sharp())
    const data1 = await image1.metadata()
    console.log(data1)
    const data2 = await image2.metadata()
    console.log(data2)
}
```

**Comment by lovell** [comment]
Thanks for reporting, there was a possible race condition when awaiting `metadata()` for Stream-based input, especially when the input Stream was very short i.e. smaller images.

Commit https://github.com/lovell/sharp/commit/df971207b88628c9f2cb4148732b85db2de7b1bd fixes this and adds a test that would previously have failed. This will be included as part of v0.31.3.

**Comment by lucakcustom** [comment]
Thanks for your answer. Just out of curiosity, why was the interpreter exiting without returning any error? I would have expected some sort of error, even like a segfault, but I was getting nothing in all the environment I tried

**Comment by lovell** [comment]
The "finish" event was already firing before the listener was attached, so the Promise returned by `metadata()` was never resolved or rejected.

I assume you invoked your sample by adding a call to `test()` at the top level rather than `await test()`. This means that once all other logic in the script had completed, the event loop would have been empty and with no callbacks remaining, the process ended.

**Comment by lucakcustom** [comment]
Now I see. Thanks again, I appreciated your answer.
