### ISSUE TITLE
In which byte order (endianness) does it produce 16-bit raw pixel data?

### ISSUE THREAD

**Issue by issuefiler** [lovell/sharp#3452]
https://github.com/lovell/sharp/blob/3a64a0529a1903cd395caa91bdf62507eb12c303/docs/api-output.md?plain=1#L530-L534

It explains the pixel arrangement and channel arrangement in each pixel, but doesn’t explain how bytes of a multibyte (16-bit) value in a pixel are arranged.

## Question

```javascript
await Sharp("test.png")
	.toColorspace("grey16") // or "rgb16"
	.raw({depth: "ushort"})
	.toBuffer()
```

In which byte order (endianness) does it produce 16-bit raw pixel data? Big endian, little endian, or the native byte order of the underlying platform (machine)?

## Related

https://github.com/lovell/sharp/issues/2104.

**Comment by lovell** [comment]
Good question, I would expect it to be native to the underlying architecture but we should probably verify this (e.g. via s390x/QEMU) and update the docs accordingly.

**Comment by lovell** [comment]
@issuefiler Were you able to verify the endianness? (I've not had a chance, nor will I for a while, so anything you can do to help here is much appreciated.)

**Comment by lovell** [comment]
v0.33.0 is now available with prebuilt binaries for Linux s390x that appear to work so I'm hoping this means native endianness is as expected.
