### ISSUE TITLE
Windows, encoding 8000x8000 AVIF image at very high quality, sharp.toBuffer() never resolves or rejects

### ISSUE THREAD

**Issue by ItsRealmy** [lovell/sharp#3454]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?
```
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 4600G with Radeon Graphics
    Memory: 2.18 GB / 7.38 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: ^0.31.2 => 0.31.2
```
The OS part is weird, as I am using Windows 11. I'm not sure if it makes a difference, though.

### What are the steps to reproduce?
When running the following code sample the first `console.log` executes, but the second doesn't as the `.toBuffer()` promise never resolves or rejects. The longer I keep it running the more my entire PC slows down.

### What is the expected behaviour?
It should return a buffer of an AVIF image.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem
```js
const proc = sharp(buffer)
proc.avif({
  quality: 75,
})
console.log('this works')
const convertedBuffer = await proc.toBuffer() // this never resolves or rejects
console.log('this doesnt')
```

### Please provide sample image(s) that help explain this problem
[I used a 5MB png image of r/place 2022.](https://imgbox.com/OPky15Yo)

### Additional info
I tried multiple versions of Node.js (v18 and v16), and I tried both sharp version `0.31.2` and `0.30.7` (which has actually worked for me in the past). All of them produce the same result.

**Comment by issuefiler** [comment]
Shouldn't it be chained?

**Comment by lovell** [comment]
This works for me locally on a Linux box. The decode PNG / encode AVIF processing of this 8000x8000 image takes about 6 minutes, with peak memory consumption just over 4GB. Perhaps you've hit a memory limit? Are you using 32 or 64-bit Node.js? Do you only experience this on Windows?

As an aside, the version number of "Windows 11" starts at 10.0.22000.0 and there's a patch making its way through the Node.js ecosystem to address this - see https://github.com/libuv/libuv/pull/3718

**Comment by lovell** [comment]
@ItsRealmy Were you able to make any progress with this? If not, please provide the requested information.

**Comment by ItsRealmy** [comment]
I think it had to do with the size of the image (in pixels). Guess my PC was just too weak.

**Comment by lovell** [comment]
Thanks for the update, AVIF encoding is highly CPU and memory intensive, and this definitely sounds like exhaustion of one/both that has led to Windows ending the process.
