### ISSUE TITLE
What exactly does `.convolve` produce?

### ISSUE THREAD

**Issue by issuefiler** [lovell/sharp#3455]
```javascript
const grayscale_image = Sharp("input.jpg")
	.flatten({background: "#FFFFFF"})
	.toColorspace("grey16");
const gaussian_blurred_image = grayscale_image.clone().blur(1 + Math.PI / 2);
const horizontal_gradient_magnitudes = gaussian_blurred_image
	.clone()
	.convolve({
		width: 3,
		height: 3,
		kernel: [
			-1, 0, 1,
			-2, 0, 2,
			-1, 0, 1
		]
	});
const vertical_gradient_magnitudes = gaussian_blurred_image
	.clone()
	.convolve({
		width: 3,
		height: 3,
		kernel: [
			-1, -2, -1,
			0, 0, 0,
			1, 2, 1
		]
	});
```

### `gaussian_blurred_image`
![3 gaussian_blurred_image](https://user-images.githubusercontent.com/57908781/201533235-24d1d97a-830d-4064-a347-3a9c7c23ae91.png)

### `horizontal_gradient_magnitudes`
![4 horizontal_gradients](https://user-images.githubusercontent.com/57908781/201533244-64c21f79-3ac8-4398-a990-46ea387def38.png)

### `vertical_gradient_magnitudes`
![5 vertical_gradients](https://user-images.githubusercontent.com/57908781/201533246-5fd8a4d3-74ec-4477-bc34-9c151c76f93e.png)

I was trying to implement the Sobel operator with the `.convolve` method, but ended up realizing something that is likely bad news.

# Questions

## Question 1 — Value range

https://github.com/lovell/sharp/blob/a9d692fb43db07ae204b62f49766e8184f7ca2e6/docs/api-operation.md?plain=1#L404-L418

 The `.convolve` method produces “_the raw pixel data representing the convolution_.” How does it represent the convolution whose elements are out of the pixel value range?

 For example, the Sobel operator produces elements that fall within the range **[-4×(the maximum pixel value), 4×(the maximum pixel value)]**, which is 8 times wider than the range of a pixel value, **[0, (the maximum pixel value)]**.

## Question 2 — Edge-handling

 Kernel convolution usually requires values from pixels outside of the image boundaries. How does the `.convolve` method extend/pad them?

![Discrete convolution](https://upload.wikimedia.org/wikipedia/commons/1/19/2D_Convolution_Animation.gif)

# Related

#3147.

**Comment by lovell** [comment]
All the underlying logic can be found in https://github.com/libvips/libvips/blob/master/libvips/convolution/convf.c

Calculations use 32-bit float(ing point) arithmetic, with results converted back to integer for the output so there could be some clipping.

The nearest edge pixels are copied outwards to fill "missing" values here https://github.com/libvips/libvips/blob/e24cee4e224af32d85ab2fd52f57c2482cc87d9c/libvips/convolution/convf.c#L331

**Comment by issuefiler** [comment]
If that’s the case, I think I need to go with another option to do this as I need values as precise as possible. Thank you for your answer and I appreciate all the work and time you spent on _Sharp_ for years.

**Comment by lovell** [comment]
Did you see the `depth` option of raw? Perhaps try `.raw({ depth: 'float' })` if you need the full precision of `Float32Array` output.
