### ISSUE TITLE
When Loading From Buffer, When is Memory Released and is it In Memory Only?

### ISSUE THREAD

**Issue by njho** [lovell/sharp#3456]
## Question about an existing feature
We're using `sharp` inside of our Google cloud functions and we've noticed that occasionally we run into an issue similar to below: 

```
Container worker exceeded memory limit of 2048 MiB with 2049 MiB used after servicing 22 requests total. Consider setting a larger instance class.
```

- Is there a chance that sharp is not releasing memory of images, or is storing somewhere when loading from `buffer`? 
- Buffer is an in-memory only operation? (ie. no storage in file system?)
- Is there a way to manually dump?

### What are you trying to achieve?

We are attempting to read the `image` data without relying on `contentType` (unreliable)

### When you searched for similar issues, what did you find that might be related?

Perhaps using `.cache` - https://github.com/lovell/sharp/issues/138

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

Call following > 22 times in cloud function
```
    const imageResponse = await axios({
      url: imgUrl,
      responseType: 'arraybuffer',
    });
    const buffer = Buffer.from(imageResponse.data, 'binary');
    const item = await sharp(buffer);
    const { size } = await item.metadata();
```

### Please provide sample image(s) that help explain this question
https://drive.google.com/file/d/1RiSvoIjzGw1Lev14DKK0_qaPpQAJd5-4/view?usp=share_link

**Comment by lovell** [comment]
sharp doesn't take a copy of the input, so the short answer is "whenever the input is no longer in scope and V8's garbage collector has removed it". Perhaps there is code not shown here that is holding on to references to the input beyond the request/response lifecycle?

This sample image is 13MB compressed and you'll have all of that in memory as `imageResponse.data` before you get anywhere near sharp.

You can probably remove the use of `Buffer.from()` in your code to avoid an unnecessary copy.
```js
const item = await sharp(imageResponse.data);
```

The underlying libvips keeps a small, shared operation cache, by default this will be up to 50MB, which can be removed via `sharp.cache(false)` if not required.

https://sharp.pixelplumbing.com/api-utility#cache

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
