### ISSUE TITLE
Enabling HEIF/HEIC support on Windows sharp@0.31.2

### ISSUE THREAD

**Issue by zczcyc0201** [lovell/sharp#3457]
I  built libvips 8.13.3  with hevc supports in windows ,and copy DLL files into on 'sharp 0.31.2' node_modules/sharp/build/Release , but not work for heic images(libvips works in command line )
 in sharp 0.28.3 , copy dlls works. can you help me?

**Comment by lovell** [comment]
You're welcome to try copying DLLs around, but I cannot help or provide any support for this.
