### ISSUE TITLE
Processing big SVG error on max pixels

### ISSUE THREAD

**Issue by themachho** [lovell/sharp#3458]
## Question about an existing feature

So, im trying to convert a big SVG that is created on FabricJs. The idea is to have a canvas to create paper labels up to 1200DPI so the max svg size can be 24''x8''@1200DPI so 28800x9600 pixels of max size. 

```cmd
npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp

  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 2.18 GB / 15.86 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.3 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: ^0.30.2 => 0.30.7
```

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

**SVG**
```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="7181" height="6000" viewBox="0 0 152 127" xml:space="preserve">
<desc>Created with Fabric.js 5.2.4</desc>
<defs>
</defs>
<rect x="0" y="0" width="100%" height="100%" fill="#E5E5E5"></rect>
<g transform="matrix(1 0 0 1 76.5 64)"  >
<rect style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: rgb(255,255,255); fill-rule: nonzero; opacity: 1;"  x="-76" y="-63.5" rx="0" ry="0" width="152" height="127" />
</g>
<g transform="matrix(1 0 0 1 47 51)" id="ogr1l"  >
<rect style="stroke: rgb(0,0,0); stroke-width: 4; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: rgb(219,251,253); fill-opacity: 0; fill-rule: nonzero; opacity: 1;" vector-effect="non-scaling-stroke"  x="-38" y="-32" rx="0" ry="0" width="76" height="64" />
</g>
</svg>
```
This is a smaller SVG, a 6''x5''@1200DPI , this is probably the most standard SVG size that will be used. Then, I use sharp to export it to tiff file:

```js
return new Promise((resolve, reject) => {
  sharp(Buffer.from(buffer, "utf-8"), {
    density: 1200,
    limitInputPixels: false,
  })
    .tiff()
    .toFile(tempLabelFile)
    .then(() => {
      resolve([200, "Image converted"]);
    });
}).catch((err) => {
  reject([400, `${err}`]);
});
```
But I have the error **'Input SVG image exceeds 32767x32767 pixel limit'** when the input image is 7181x6000pixels. If I dont use `limitInputPixels` I have the error **'Input image exceeds pixel limit'**. 

So the max pixels 32767x32767 is more than I need of my possible max size, then why cant I process the SVG file? Is something that im missing in when processing?

**Comment by lovell** [comment]
This example SVG image contains `width="7181" height="6000"` (so the `viewBox` is ignored) and if no `density` is specified, it will use the default of 72 and render at 7181x6000.

If you do specify a `density`, as the example code does, this will be a multiplier of the default density of 72 because the image has an explicit width and height. This means the requested input width will be 7181 * 1200 / 72 and height 6000 * 1200 / 72, or 119683x100000.

The maximum SVG size that can be rendered is 32767x32767 and this limit cannot be increased for SVG, even when attempting to use `limitInputPixels`.

**Comment by themachho** [comment]
So I have to use a multiplier that would be:   1200/72 = 16.66 = 100/6? .   
And then:
``` sharp(Buffer.from(buffer, "utf-8"), {
    density: 100/6,
    limitInputPixels: false,
  })
```
Thanks!

**Comment by lovell** [comment]
You could also let `resize()` handle the scaling for you, e.g.
```js
.resize({ width: 28800, height: 9600, fit: 'inside' })
```
...or modify the SVG so the width and height are as-expected, or remove these entirely and use only a `viewBox` to control dimensions.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
