### ISSUE TITLE
.stats() fails if sequentialRead is true

### ISSUE THREAD

**Issue by ssendev** [lovell/sharp#3462]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Linux 5.19 Fedora Linux 36 (Workstation Edition)
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 16.72 GB / 31.07 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.9.0 - ~/.nvm/versions/node/v18.9.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.1 - ~/.nvm/versions/node/v18.9.0/bin/npm
  npmPackages:
    sharp: ^0.31.2 => 0.31.2 
```

### What are the steps to reproduce?
Use `sequentialRead: true` and `.stats()` together which results in `Uncaught Error: VipsJpeg: out of order read at line 1776` or `Uncaught Error: pngload: out of order read at line 2048`

### What is the expected behaviour?

The docs for `sequentialRead` say used where possible so i would expect it silently ignoring the option alternatively an error message that the two are incompatible might also be a solution.
### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```js
await require('sharp')('img.jpg',{ sequentialRead: true }).stats()
```

**Comment by lovell** [comment]
Good catch, thanks for reporting, commit https://github.com/lovell/sharp/commit/a472aea025052720642b263e647feae0921ba794 fixes this and adds a test.

**Comment by lovell** [comment]
v0.31.3 now available, thanks again for reporting.
