### ISSUE TITLE
Execute script in ".svg" file

### ISSUE THREAD

**Issue by Jamu2800** [lovell/sharp#3463]
# about

I can write JavaScript in my svg files, is there any way to run them when loading them in sharp?
In this case, is there any way to draw the red rect into test.png?

I understand that writing the svg file and JavaScript separately will work.

# test code
main.ts
```
import sharp from 'sharp'

sharp('test.svg')
    .png()
    .toFile("test.png")
```

test.svg
```
<!DOCTYPE svg>
<svg width="100" height="100"
     xmlns="http://www.w3.org/2000/svg">
    <rect id="test_svg_rect"
          height="90" width="90"
          x="5" y="5"/>
    <script><![CDATA[
        const rect = document.getElementById("test_svg_rect");
        rect.setAttribute("fill", "red");
        ]]>
    </script>
</svg>
```

test.png
![test](https://user-images.githubusercontent.com/74401057/202969656-f5f0e816-e3da-42e3-8a7a-9cf36fc68d26.png)

chrome ver
![image](https://user-images.githubusercontent.com/74401057/202970626-1d3e3aa5-dcb1-4081-bd47-61ebc5418f5d.png)

**Comment by lovell** [comment]
There's no support for embedded scripts in SVG images nor is there ever likely to be.

**Comment by Jamu2800** [comment]
Thank you for taking the time to reply.
I understand that the script is not available.
