### ISSUE TITLE
compositing a very large image

### ISSUE THREAD

**Issue by endquote** [lovell/sharp#3464]
### What are you trying to achieve?

I'm trying to composite an image whose total dimensions will end up being 79288x111254.

I've successfully done this by generating a grid of 22x22 3508x4961 tiff files and merging them together using [GigaPX Tools](https://gigapxtools.com), and then using those same tools to export a Zoomify tile pyramid. Before that I tried imagemagick CLI which just set my computer on fire.

However my new image doesn't lend itself to being laid out in a grid, so I'm looking at `sharp`.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

First attempt -- make a very large canvas and just draw onto it?

```
await sharp({
  create: {
    width: 79288,
    height: 111254,
    channels: 3,
    background: { r: 255, g: 255, b: 255 },
  },
  limitInputPixels: false,
  unlimited: false,
})
  .composite([
    { input: "foo.png", left: 100, top: 100 },
    { input: "foo.png", left: 0, top: 0 },
  ])
  .toFile("output.tiff");
```

```
Error: Processed image is too large for the JPEG format
```

But I'm not using JPEG...

Without `limitInputPixels` I get:

```
Error: Input image exceeds pixel limit
```

Is it just not possible to make a canvas this big?

Could I break up the task into smaller images and combine them in a second step?

### Please provide sample image(s) that help explain this question

[source images](https://github.com/endquote/tdr-bingo-cli/tree/main/cache/artwork)

[this is the desired output](https://tdrbingo.endquote.com), except the layout wouldn't be in a convenient grid

**Comment by lovell** [comment]
> But I'm not using JPEG...

Did you see the `compression` option of `tiff()`, which defaults to JPEG?

https://sharp.pixelplumbing.com/api-output#tiff

> `options.compression` compression options: none, jpeg, deflate, packbits, ccittfax4, lzw, webp, zstd, jp2k (optional, default 'jpeg')

For example, to use DEFLATE:

```diff
+  .tiff({ compression: 'deflate' })
   .toFile("output.tiff");
```

**Comment by endquote** [comment]
Thank you for that tip. RTFM is usually the answer.

If I set my width/height to 36040/50570, I get a tiff at that size.

If  I double that, my process exits with no error.

```
const width = 72080; // works fine with lower values
const height = 101140;
console.log(width, height);
try {
  await sharp({
    create: {
      width,
      height,
      channels: 3,
      background: { r: 255, g: 255, b: 255 },
    },
    limitInputPixels: false,
    unlimited: false,
  })
    .tiff({
      compression: "deflate", // "none" doesn't work either
    })
    .toFile("output.tiff");
} catch (error) {
  console.log(error); // this is never hit
}

this.log("complete"); // this is never hit
```

This is node 18.12.0 and sharp 0.31.2 on Windows. On macOS I started getting errors like `Library not loaded: /usr/local/opt/vips/lib/libvips-cpp.42.dylib` as soon as I added the `compression` option.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by joesong168** [comment]
Encounter similar problem when dealing with tiff encoded in webp. I think the limitation for tiff-jpp should be removed for tiff-webp
