### ISSUE TITLE
Recommended config file for 2022

### ISSUE THREAD

**Issue by caxapexac** [lovell/sharp#3466]
I'm looking for recommended config file for small application, mainly mobile 3G devices, is there any place I can find these config examples? Sharp config file contains 50+ parameters and it's just too long to test manually (especially these `quality` settings which is really subjective) and I hope somebody already did this

**Comment by lovell** [comment]
This is a wide topic and most output-related settings are for the underlying image format libraries so this might be better suited to a more general discussion site such as StackOverflow.

**Comment by caxapexac** [comment]
This question would be closed on SO in nanosecond as 'too broad', thats why Im asking here

Could you please share just something that is a bit closer to recommended settings than nothing?

**Comment by lovell** [comment]
I'm glad you realise it's a broad topic. Perhaps you could narrow it down with a specific image, specific code that you've tried, and a specific set of expectations about the output.

**Comment by caxapexac** [comment]
Ive already narrowed it down to 'mobile web browsing'. Its implicitly lossy png+webp for small screens and slow internet speed. How can I narrow it further?
