### ISSUE TITLE
Operation "linear" does not work with uncompressed TIFF

### ISSUE THREAD

**Issue by stefanpieper** [lovell/sharp#3468]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.44 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  npmPackages:
    sharp: ^0.31.2 => 0.31.2 
```

### What are the steps to reproduce?

When doing a conversion to uncompressed tiff and "linear" in the same pipeline, the resulting image is not as expected.

### What is the expected behaviour?

The image should be output by the sample code below "as is" (_linear(1, 0)_ being an idempotent operation). This works well with other formats than uncompressed TIFF.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```
  let buffer = await fs.readFileSync(path.join(__dirname, "resources/images/random-small.jpeg"));
  buffer = await sharp(buffer)
    .tiff({compression: 'none'})
    .linear(1, 0)
    .toBuffer();
  await sharp(buffer)
    .jpeg()
    .toFile(path.join(__dirname, "resources/transformed/linear-fail.jpeg"));
```

### Please provide sample image(s) that help explain this problem

This is my test image that I would expect to remain basically unchanged in output with the code above:

![random-small](https://user-images.githubusercontent.com/4038523/203832958-40460c79-5006-4f4b-9dd0-0bfc71a371a2.jpeg)

This is what the code actually produces (the image is nearly all-white and can therefore hardly be seen):

![linear-fail](https://user-images.githubusercontent.com/4038523/203833139-83a66322-d17d-4791-857c-e78b4aa3668a.jpeg)

**Comment by lovell** [comment]
Thanks for reporting, commit https://github.com/lovell/sharp/commit/0265d305fe332ad500361bc9fc2c02ae66602fef ensures the output is integral rather than float, plus adds a couple of tests that would have caught this.

**Comment by lovell** [comment]
v0.31.3 now available, thanks again for reporting.
