### ISSUE TITLE
.extract fails while extracted bounds inside image?

### ISSUE THREAD

**Issue by lenscas** [lovell/sharp#3477]
## Question about an existing feature

I either am totally missing how `.extract()` works or I found a bug?

### What are you trying to achieve?

I'm trying to extract some tiles from a tilemap

### When you searched for similar issues, what did you find that might be related?

There are a couple of issues about extract on this repo like https://github.com/lovell/sharp/issues/407 but they all seem to be the result of user error with the extract area ending up outside the given image. However, as far as I can tell, that isn't the case for me and logging the sizes of everything seems to confirm that

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

My code in question:
```ts
const extract = async (a: Sharp, locations: number[][]) => {
    const size = conf.tile_config.size;
    return Promise.all(
        locations.map((tile) => {
            a.metadata().then((x) => console.log('image size:' + x.width + ',' + x.height));
            console.log(size * tile[1] + ' , ' + size * tile[0]);
            return a
                .extract({
                    top: size * tile[1],
                    left: size * tile[0],
                    width: size,
                    height: size,
                })
                .toBuffer();
        }),
    );
};
```
This prints:
```
0 , 0
image size:384,192
0 , 32
16 , 32
image size:384,192
image size:384,192
```
but still ends up causing the `Error: extract_area: bad extract area`. `size` is 16 and the same image is given to this extract function. 
So, either I am missing how `extract` works or I am getting this error while it is inside the image?

### Please provide sample image(s) that help explain this question
The image I am working with is the tilemap you can get from https://rekkimaru.itch.io/dungeon-rpg-tileset (you can download it for free from there, file name is `Dungeon tileset.png`)

**Comment by lovell** [comment]
Please can you provide the complete set of values for `locations` to allow someone else to reproduce.

**Comment by lenscas** [comment]
size was 16, locations was `[[0,0]]` the first time it was called and `[[2,0],[2,1]]` the second (There may have been more values in the second array but it always crashed at the second value)

For now, I changed the code so it creates a new `Sharp` object for every image rather than reusing the objects and that seems to have fixed it. Not entirely sure why that would have fixed it, because if the methods mutate the `Sharp` object then I would have expected it to crash while processing the first element from the second call (As that got the same object as what was got given for the first call)

I guess `toBuffer` resets the object then or something after it is done? Which it wouldn't be for the second element from the second call due to using `.map` and awaiting all the Promises at once.

**Comment by lovell** [comment]
Thanks, I'm unable to reproduce with the information and code provided so far. Perhaps there is logic not shown here that is mutating `a`, hence why creating a new instance works?

I note that there is no logic to await the response of `a.metadata()...` so the two uses of `console.log()` in the example code are asynchronously outputting their values, which may point to a race condition either here or elsewhere.

**Comment by lenscas** [comment]
I put the `console.log()` down to both check for my own sanity and to show that the values I was working with are indeed inside the image. So, I didn't bother waiting for its results as the problem was already happening before I added it and it was just some debug information anyway.

Am I correct in understanding that `.extrac()` should _not_ update the object it is called on? If so, I'll see if I can revert the change today and see how things go.


Thanks for diving into it anyway, especially if it turned out to be user error 😅

**Comment by lovell** [comment]
Calling `extract` does mutate the instance, but in the code example provided that doesn't matter as `toBuffer` is called directly afterwards, at which point a snapshot of the values is taken so subsequent mutation won't affect each call (hence my question about code not shown here).

If you're still having problems, perhaps you could create a standalone repo with the _complete_ code and image(s) that allows someone else to reproduce.

**Comment by lenscas** [comment]
The mutations are definitely affecting each other as I get this problem even if I swap the `.map` out for a normal loop so I can `await` the extraction.

```ts
const extract = async (a: Sharp, locations: number[][]) => {
    const size = conf.tile_config.size;
    const res: Array<Buffer> = [];
    for (const tile of locations) {
        res.push(
            await a
                .extract({
                    top: size * tile[1],
                    left: size * tile[0],
                    width: size,
                    height: size,
                })
                .toBuffer(),
        );
    }
    return res;
    ```
It stops happening if I create a new instance in the loop itself, rather than share instances from outside the loop.

I'll hope I can push all the code tomorrow.

**Comment by lovell** [comment]
You're quite right, calling `extract` a second time on a sharp instance will double-extract (this is to support pre and post extraction when also resizing). You'll definitely want to create a new instance for each iteration, and there's almost no overhead in doing so.

**Comment by lenscas** [comment]
Ok. That makes sense. Kind of sad that the only way to run multiple operations on the same image rather than on subsets requires me to load the image multiple times (unless Sharp does some internal caching or if I missed some way to clone the object).

But, yea, this issue was also a case of user error and it can probably be closed now.

Thanks for all the help :)

**Comment by lovell** [comment]
> load the image multiple times

Pipeline processing in sharp/libvips is lazy, which may be different to the experience you've had with other image tooling that decodes entire images into memory every time (coughmagickcough).

Only relevant regions of the input are "loaded" (decoded) when output is requested. In this case, using `extract`, only the pixels necessary to service the required output regions will be decoded. If you're using the filesystem for input then libvips can cache decoded regions too e.g. where there is overlap.

**Comment by MarcWeber** [comment]
You might want to improve the README.md by adding something like this
to the README very early:

Shapr uses a lazy streaming API meaning operations are remembered and then applied only consuming what is needed. See #3477 to learn about details.
Use pattern like this if you need a realized intermediate result:

```
const buffer = await shapr('path').toBuffer()
// Now you can use shapr(cache) to get a copy you can work with without decoding the image multiple times.
```

Decoding is heavy operation eg heif/heic is 10x slower than webp/or jpg when I tested it.

The code I wrote assuming each step does create a copy was:

```
        const i = sharp('slim_screen_shot-eg-600x20000.webp')

        const m = await i.metadata()
        console.log( JSON.stringify(m) );
        const mh = 5000
        const columns = Math.ceil(m.height! / mh )

        const combined = sharp({
            create: {
                width: columns * m.width!,
                height: mh,
                channels: 3,
                background: { r: 0, g: 0, b: 0, alpha: 255 }
            }
        })

        combined.composite(
            await Promise.all(_.range(columns).map( async (col) => {
                const eh = (col == columns-1) ? (m.height! % mh) : mh
                const box = i.extract({left: 0, top:  mh*col, width: m.width!, height: eh })
                return { input: await box.toBuffer(), top: 0, left: col * m.width! }
            }))).flatten().webp().toFile('/tmp/x.webp')
```

Summary: I think the behavior of the library is an important property so should be mentioned very early in the README. I got into this cause webp doesn't allow height > 16xxx.

Because you have examples in the README this detail is important.

Or would such example be better ?

Extract 2 regions of a file assuming you consume everything because copying in memory is faster than decoding the image ?
```
const x = await shapr(path).toBuffer()
const e1 = shapr(x).extract()
const e2 = shapr(x).extract()
```

Extract 2 regions of a file assuming you only consume a very small part
and the storage format is tiled using only as much memory as is required to extract the tiles
```
const e1 = shapr(path).extract()
const e2 = shapr(path).extract()
```

I think examples like this added to README would help picking up the library.
