### ISSUE TITLE
npm i sharp fails

### ISSUE THREAD

**Issue by bhavya3024** [lovell/sharp#3478]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [ ] Running `npm install sharp` completes without error.
- [ ] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What are the steps to reproduce?

`npm i sharp`

### What is the expected behaviour?

`execute successfully`

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem
```
 npm i sharp@latest

> sharp@0.31.2 install /Users/bhavya.dhiman/Documents/password-guesser/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Installation error: Expected Node.js version >=14.15.0 but found 12.22.12
sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm WARN notsup Unsupported engine for sharp@0.31.2: wanted: {"node":">=14.15.0"} (current: {"node":"12.22.12","npm":"6.14.16"})
npm WARN notsup Not compatible with your version of node/npm: sharp@0.31.2
npm WARN password-guesser@1.0.0 No description
npm WARN password-guesser@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.31.2 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.31.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bhavya.dhiman/.npm/_logs/2022-12-04T08_52_47_876Z-debug.log
```

**Comment by lovell** [comment]
Did you see the following message in the output you provided?

> sharp: Installation error: Expected Node.js version >=14.15.0 but found 12.22.12

Node.js 12 reached end-of-life in April this year and is no longer supported, please upgrade.

**Comment by bhavya3024** [comment]
oops, i missed that, thanks!!
