### ISSUE TITLE
how to avoid repeat compress images(png,jpg).

### ISSUE THREAD

**Issue by ToPeas** [lovell/sharp#3483]
### What are you trying to achieve?

I was wondering if there was a way to label the images , i don't compress same file

### When you searched for similar issues, what did you find that might be related?

by withMetadata set exif data. but png not support .

**Comment by lovell** [comment]
If this question is: "how do I update EXIF metadata without de/recompressing images?", then please see #3327

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
