### ISSUE TITLE
Trim does not remove transparent pixels

### ISSUE THREAD

**Issue by dragoon** [lovell/sharp#3484]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: macOS 12.6.1
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 510.26 MB / 16.00 GB
    Shell: 5.9 - /usr/local/bin/zsh
  Binaries:
    Node: 19.2.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
```

### What are the steps to reproduce?

I have made a simple pipeline like this

    sharp(f1)
      .extend({
          top: 100,
          bottom: 100,
          left: 100,
          right: 100,
          background: {r: 0, g: 0, b: 0, alpha: 0}
      })
      .trim({background: {r: 0, g: 0, b: 0, alpha: 0}, threshold: 0})
      .toFile(f2)

I actually wanted to blur the image after extending, but trim doesn't work even without it.

Here is my image (white cloud on transparent background):
![cloud0](https://user-images.githubusercontent.com/490130/206847525-4c12dc8e-59f6-43df-8649-2d740b376dc0.png)

Original size 255x102, after trimming still 455x302, as if nothing happened.

**Comment by lovell** [comment]
The `trim` operation is occurring before the other operations, so you'll need to break this into two pipelines, the first to make all the modifications you need (`extend`, `blur`) and the second to perform the `trim`, something like:
```js
sharp(in)
  .extend({
    top: 100,
    bottom: 100,
    left: 100,
    right: 100,
    background: { r: 0, g: 0, b: 0, alpha: 0 },
  })
  .blur()
  .toBuffer()
  .then(data => sharp(data)
    .trim({ background: { r: 0, g: 0, b: 0, alpha: 0 }, threshold: 0 })
    .toFile(out)
  );
```

**Comment by dragoon** [comment]
Thanks for the quick reply, I have just implemented it, but it doesn't seem to work.

**Comment by dragoon** [comment]
Okay I have tried `threshold: 1` and it worked. Could take quite some time to figure out :)
