### ISSUE TITLE
registerFont() method

### ISSUE THREAD

**Issue by zisra** [lovell/sharp#3485]
### What are you trying to achieve?

Ability to register fonts that are not installed in the OS/system. I'm not sure if this is possible with how sharp works right now (I'm no expert). I assume it is because it is possible with the text option, so why not allow it for embedded text in SVG?

### When you searched for similar feature requests, what did you find that might be related?

node-canvas has the ability to do this: https://github.com/Automattic/node-canvas#registerfont . Related to my issue #3479

### What would you expect the API to look like?

`sharp.registerFont('comicsans.ttf', { family: 'Comic Sans' })`

**Comment by lovell** [comment]
As I said in #3479, please see https://sharp.pixelplumbing.com/install#fonts

sharp uses `librsvg` for SVG rendering, which uses `fontconfig` for font discovery. You'll need to work out how to configure `fontconfig` to support the Railway runtime. It looks like it supports containers via Docker, so perhaps define a `Dockerfile` that installs `fontconfig` and all your required fonts to your choice of OS.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
