### ISSUE TITLE
[Error: VipsJpeg: Invalid SOS parameters for sequential JPEG ]

### ISSUE THREAD

**Issue by mattcwebster** [lovell/sharp#3488]
Im still experiencing this error in latest version of Sharp with a Samsung S22, and even when using failOn: 'none'

[Error: VipsJpeg: Invalid SOS parameters for sequential JPEG
]

**Comment by Dadibom** [comment]
I am seeing the same issue, I don't know anything about which images cause it unfortunately, just wanting to confirm that the error occurs

**Comment by lovell** [comment]
For anyone else coming here, please see #1578 for context.

Assuming the input is trusted, you can use the following approach to deal with invalid images generated by shoddy Samsung firmware.
```js
sharp(input, { failOn: 'error' })...
```

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by ackmanx** [comment]
Thanks for the info. Using the `failOn` option with `error` worked for me on being able to resize and save as a thumbnail from the shoddy Samsung original.
