### ISSUE TITLE
Error: vips_tracked: out of memory --- size == 32684MB

### ISSUE THREAD

**Issue by beig** [lovell/sharp#3489]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 11.71 GB / 31.93 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.24.0 - ~\AppData\Roaming\npm\npm.CMD
  npmPackages:
    sharp: ^0.31.2 => 0.31.2
```

### What are the steps to reproduce?

I am trying to extract the first page of an GeoTIFF which contains a huge JPG 

Metadata:

```
{
  format: 'tiff',      
  width: 70122,        
  height: 122189,      
  space: 'srgb',       
  channels: 3,
  depth: 'uchar',      
  isProgressive: false,
  pages: 1,
  hasProfile: false,   
  hasAlpha: false,
  orientation: 1
}
```
```
    await sharp(file, {page: 0, limitInputPixels: false, sequentialRead: true})
        .png({quality: 90})
        .toFile(output);
```

Using the `quality `option triggers the following error

```
[Error: vips_tracked: out of memory --- size == 32684MB
]
```

Without it, it works fine, but then the output image is 2.3GB

Is there any way to reduce the quality of the output?

**Comment by lovell** [comment]
When you provide a `quality` for PNG output you're requesting palette-based output. To achieve this, the image must be fully loaded uncompressed into memory as RGBA pixel data so will require 122189 * 70122 * 4 bytes, which is about 32GB.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
