### ISSUE TITLE
Resize after extract is very slow

### ISSUE THREAD

**Issue by adityapatadia** [lovell/sharp#3490]
We are trying to resize image after `extract`. The speed becomes worse as the output width increases. If the extract operation is removed, resize is crazy fast.

Here is sample code:

```node
import sharp from 'sharp';

async function image_process() {
    let transformer = sharp("test.jpg");
    transformer.extract({
        left: 5,
        top: 0,
        width: 8250,
        height: 5503
    }).resize({
        width:300
    }).toFile("output.jpg");
}

image_process();
```

This one takes around `0.8` second on my M2 Macbook Air. If I increase `width: 600` it takes around `1.3` seconds and `width: 900` takes around `2.1` seconds.

If we remove `extract` operation, resize generally takes less than `0.1` second. Is there a way to make extract and resize combination faster?

I have attached sample image.
![test](https://user-images.githubusercontent.com/1086617/207659918-060e5304-562c-477b-987f-ab3624a252c4.jpg)

**Comment by lovell** [comment]
Have you tried `sequentialRead`?
```diff
-     let transformer = sharp("test.jpg");
+     let transformer = sharp("test.jpg", { sequentialRead: true });
```

**Comment by adityapatadia** [comment]
Yes tried and had no effect on processing time.On 15-Dec-2022, at 3:22 AM, Lovell Fuller ***@***.***> wrote:﻿
Have you tried sequentialRead?
-     let transformer = sharp("test.jpg");
+     let transformer = sharp("test.jpg", { sequentialRead: true });

**Comment by adityapatadia** [comment]
Sorry for that response. Sequential read indeed seems to improve performance. It however still is much higher than only resize (~0.25 sec) and keeps increasing with increase in resized width.

In which case is it advantageous to use?

**Comment by lovell** [comment]
Performing an `extract` operation before `resize` means the shrink-on-load optimisation, as used when resizing JPEG images, cannot be taken advantage of. Perhaps you could reverse the order?

**Comment by adityapatadia** [comment]
Reversing order has bad consequences. Our users provide extract points as per original images and mapping them to output image is pain. We are trying to deploy sequential mode for all users. It has given 4x speed improvement. I hope it does not do any negative things.

**Comment by adityapatadia** [comment]
I have also tried to do `resize({width:4000}).extract({top:5, left: 0, width: 8300, height: 5500}).resize({width: 300})` but it seems using resize twice is not working.

**Comment by lovell** [comment]
Thanks, then it sounds like the shrink on load optimisation won't be possible in this scenario.

**Comment by adityapatadia** [comment]
I was wondering why center cropping image is much faster while extract is much slower? Anything that can be optimised here?

**Comment by lovell** [comment]
Please provide complete, standalone code (and further input images, if relevant) that allows someone else to reproduce this additional performance difference.

**Comment by adityapatadia** [comment]
`sequentialRead` deployed on production did help. We tried center crop which works super fast. Here is sample code:

```javascript

import sharp from 'sharp';

async function resize() {
    console.time("crop")
    await sharp("test.jpg",{ sequentialRead: true }).resize({
        fit: "cover",
        height: 255,
        width: 500
    }).toFile("cropped.jpg");
    console.timeEnd("crop")

    console.time("extract")
    await sharp("test.jpg",{ sequentialRead: true }).extract({
        left:0,
        top: 642,
        width: 8192,
        height: 4180
    }).resize({
        width: 500
    }).toFile("extracred.jpg");
    console.timeEnd("extract")
    
}

resize();
```
The output is:
```bash
crop: 119.845ms
extract: 404.435ms
```

Is there any way extract can utilise shrink-on-load? If not, getting that chaining of resize work would be best. We can resize it to 4000 pixel first and then perform extract before doing final resize.

**Comment by lovell** [comment]
I'll close as I don't think there's anything we can do here.
