### ISSUE TITLE
Problem reading large (stitched) images

### ISSUE THREAD

**Issue by BobFrankston** [lovell/sharp#3491]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x ] Running `npm install sharp` completes without error.
- [x ] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x ] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900KB @ 3.30GHz
    Memory: 31.70 GB / 63.58 GB
  Binaries:
    Node: 19.1.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: ^0.31.2 => 0.31.2
```
### What are the steps to reproduce?

It fails and exits node if I read a large file such as those produced by stitching
![STA_1220 Stitch](https://user-images.githubusercontent.com/5490484/207697006-7f6d4ce3-d15a-4c42-abd5-76173e6dc087.jpg)

### What is the expected behaviour?
Not die and exit rather than signaling an error

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem
Read in the above image

### Please provide sample image(s) that help explain this problem

See above

**Comment by lovell** [comment]
I'm able to successfully process the sample image, and have tried various operations and output formats.

Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem.

**Comment by lovell** [comment]
@BobFrankston Were you able to make any progress with this? Please provide the requested details if further help is required.

**Comment by BobFrankston** [comment]
Alas, I seem to have modified the code to avoid the dependency on Sharp. If I get time i can try to recreate it or I can provide you a copy of the image that causes the problem.

**Comment by lovell** [comment]
I'll close this as there's not much I can do without complete steps to reproduce, which I've been unable to do with the image alone.

**Comment by BobFrankston** [comment]
I understand. Will get back to you if I can find a repo.
