### ISSUE TITLE
Hard-light blend mode differences

### ISSUE THREAD

**Issue by VladimirMikulic** [lovell/sharp#3492]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

System:
    OS: Linux 6.0 KDE neon 5.26 5.26
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.1.3 - ~/.npm-global/bin/npm
  npmPackages:
    sharp: ^0.31.2 => 0.31.2

### What are the steps to reproduce?

First of all, let me thank you for creating sharp!
It's truly an amazing project and we're currently in the process of migration from Jimp to Sharp and got stuck a bit :)

Given that image is worth a thousand words, here's the gist of it:

![Screenshot_20221215_021904](https://user-images.githubusercontent.com/35997844/207751435-ab7b848e-17c7-4370-8eeb-e924ba5c0aab.png)

### What is the expected behaviour?

As you can see on the result above, the artwork is composed of three images:
 - Water (blend mode normal)
 - Ice (blend mode hard-light)
 - Fish (blend mode normal)

Browser renders the version I want, Jimp comes in second with very similar result, but Sharp has completely different result for "Ice" layer/image. I'd expect Sharp's hard-light blend mode to match the one browser uses or if it doesn't match exactly, that it's at least similar.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

Here's the repository that has the above results.html page with sharp.js and jimp.js scripts for creating the final image.
https://github.com/VladimirMikulic/hardlight-blend-mode-demo

### Please provide sample image(s) that help explain this problem

The three images used to compose an artwork can be found here: https://github.com/VladimirMikulic/hardlight-blend-mode-demo/tree/master/images

**Comment by lovell** [comment]
It looks like [ice.png](https://github.com/VladimirMikulic/hardlight-blend-mode-demo/blob/master/images/ice.png) has already been premultiplied. You can tell sharp this by using the following change:
```diff
-      { input: './images/ice.png', blend: 'hard-light' },
+      { input: './images/ice.png', blend: 'hard-light', premultiplied: true },
```

**Comment by VladimirMikulic** [comment]
Thank you so much for a fast reply @lovell.

That worked indeed and I noticed I need it for some other blend modes like `overlay`/`multiply`/`screen` to get the right result. However, it seems like it isn't needed for `over`/`exclusion`/`difference`.

Could you please explain what `premultiplied` does and how it makes a difference with some blend modes, but not with others? (it seems like Jimp handles automatically)

**Comment by lovell** [comment]
Best guess would be that it's something to do with blend modes that multiple the alpha values (rather than add/subtract them).

I can't find the documentation for jimp's `composite` feature so am unsure how it works, however it's unlikely to be able to automatically determine if an image is premultiplied so is probably expecting you to have done this already.
