### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _pthread_jit_write_protect_supported_np

### ISSUE THREAD

**Issue by 0123cf** [lovell/sharp#3494]
i install next-image-export-optimizer
```
"next-image-export-optimizer": "^1.1.0",
```

```
next-image-export-optimizer@^1.1.0:
  version "1.1.0"
  resolved "https://registry.npmmirror.com/next-image-export-optimizer/-/next-image-export-optimizer-1.1.0.tgz#9bd4fb9baf27b2788ddae82b1ba27e0a4343a2c7"
  integrity sha512-FaO7wllHhZO3g7LObMBHioXb5zG/IetTW4zDzvdTofthkA1T9oqJaDIXWz463i2WAp2fPA0dnfrtYRk7my9RGw==
  dependencies:
    cli-progress "^3.10.0"
    sharp "^0.31.0"
    typescript "^4.7.2"
```

[x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
[x]  I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

[x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Is this a problem with filesystem permissions?

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7 or later, does the user running `npm install` own the directory it is run in?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

```
added 45 packages, and audited 46 packages in 16s

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm timing command:install Completed in 15496ms
npm verb exit 0
npm timing npm Completed in 15714ms
npm info ok 
```

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
System:
    OS: macOS Mojave 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 62.69 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
```

**Comment by lovell** [comment]
Please see #3438
