### ISSUE TITLE
I am using a offline 'ubuntu' system which blocks github and I am trying to run Strapi v4 , it shows the error while installing sharp module in the offline system

### ISSUE THREAD

**Issue by govind-dev1012000** [lovell/sharp#3495]
## Possible install-time or require-time problem

- [ ] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [ ] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

- [ ] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Is this a problem with filesystem permissions?

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7 or later, does the user running `npm install` own the directory it is run in?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

</details>

**Comment by govind-dev1012000** [comment]
I have seen the prebuilt documentation and downloaded sharp and libvips from git and set the npm config too npm_config_sharp_local_prebuilds= /home/ubuntu/full_strapi/app/sharp/ npm_config_sharp_libvips_local_prebuilds= /home/ubuntu/full_strapi/app/libvips/ full_strapi\app\libvips\v8.13.1\libvips-8.13.1-linux-x64.tar.br full_strapi\app\sharp\sharp-v0.31.2-napi-v7-linux-x64.tar.gz But still it shows the error Screenshot (1642)

**Comment by lovell** [comment]
If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7 or later, does the user running `npm install` own the directory it is run in?

(These questions were asked in the issue template but were ignored.)

**Comment by govind-dev1012000** [comment]
Thank You @lovell , I have solved that issue , But Now it shows a different error .
![image](https://user-images.githubusercontent.com/114384578/207817655-d5dc315e-e255-4ccc-97b0-ca34fdaa0705.png)

while running the following command
npm install --verbose --foreground-scripts

**Comment by lovell** [comment]
What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

(This question was asked in the issue template but was ignored.)

**Comment by govind-dev1012000** [comment]
![image](https://user-images.githubusercontent.com/114384578/207822195-1b16985e-b31b-4b95-87a9-0912a71347f6.png)
The above is the output on empty directory
![image](https://user-images.githubusercontent.com/114384578/207822442-893d03d0-bc67-4f1a-b707-7b06b1e6c1c2.png)
The above is the output after I set the prebuilts
npm_config_sharp_local_prebuilds= /home/kupexadm/full_strapi/app/sharp/
npm_config_sharp_libvips_local_prebuilds= /home/kupexadm/full_strapi/app/libvips/

**Comment by lovell** [comment]
This screenshot appears to show a log that is still attempting to download binaries (and failing due to a self-signed certificate error on your local network/proxy).

If you're configuring `npm` directly, please use `sharp_local_prebuilds` as the setting; `npm_config_sharp_local_prebuilds` is an environment variable alternative.

https://sharp.pixelplumbing.com/install#custom-prebuilt-binaries

Please provide copy/pasted text rather than screenshots.

**Comment by govind-dev1012000** [comment]
Thank You for the info @lovell , Now I have created a .npmrc file and used the below 

sharp_libvips_local_prebuilds = /home/ubuntu/full_strapi/app/libvips/
sharp_local_prebuilds = /home/ubunt/full_strapi/app/sharp/

with downloaded br and .gz as shown below
full_strapi\app\libvips\v8.13.1\libvips-8.13.1-linux-x64.tar.br
full_strapi\app\sharp\sharp-v0.31.2-napi-v7-linux-x64.tar.gz

npm config list
; "project" config from /home/ubuntu/full_strapi/.npmrc

sharp_libvips_local_prebuilds = "/home/ubuntu/full_strapi/app/libvips/"
sharp_local_prebuilds = "/home/ubuntu/full_strapi/app/sharp/"

; node bin location = /usr/bin/node
; node version = v18.12.1
; npm local prefix = /home/ubuntu/full_strapi
; npm version = 8.19.2
; cwd = /home/ubuntu/full_strapi
; HOME = /root
; Run `npm config ls -l` to show all defaults.

and npm install shows this ERROR
npm ERR! /usr/include/vips/vips8:35:10: fatal error: glib-object.h: No such file or directory
npm ERR!    35 | #include <glib-object.h>
npm ERR!       |          ^~~~~~~~~~~~~~~

**Comment by lovell** [comment]
What is the *complete* output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

**Comment by govind-dev1012000** [comment]
npm verb cli /usr/bin/node /usr/bin/npm
npm info using npm@8.19.2
npm info using node@v18.12.1
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 2ms
npm timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 3ms
npm timing config:load:env Completed in 1ms
npm timing config:load:file:/home/kupexadm/sharp/.npmrc Completed in 1ms
npm timing config:load:project Completed in 23ms
npm timing config:load:file:/root/.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:/usr/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 1ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 34ms
npm timing npm:load:configload Completed in 35ms
npm timing npm:load:mkdirpcache Completed in 2ms
npm timing npm:load:mkdirplogs Completed in 0ms
npm verb title npm install sharp
npm verb argv "install" "--loglevel" "verbose" "--foreground-scripts" "sharp"
npm timing npm:load:setTitle Completed in 2ms
npm timing config:load:flatten Completed in 4ms
npm timing npm:load:display Completed in 14ms
npm verb logfile logs-max:10 dir:/root/.npm/_logs
npm verb logfile /root/.npm/_logs/2022-12-15T11_53_08_024Z-debug-0.log
npm timing npm:load:logFile Completed in 7ms
npm timing npm:load:timers Completed in 1ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load Completed in 62ms
npm timing arborist:ctor Completed in 1ms
npm timing arborist:ctor Completed in 0ms
npm timing idealTree:init Completed in 18ms
npm timing idealTree:userRequests Completed in 3ms
npm http fetch GET 200 https://registry.npmjs.org/sharp 1192ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color 229ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 473ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/semver 472ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/simple-get 476ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/tunnel-agent 485ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/prebuild-install 495ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/node-addon-api 499ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/tar-fs 514ms (cache revalidated)
npm timing idealTree:#root Completed in 1743ms
npm http fetch GET 200 https://registry.npmjs.org/minimist 254ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/node-abi 253ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/napi-build-utils 260ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/github-from-package 265ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-convert 271ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/expand-template 270ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/lru-cache 265ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/mkdirp-classic 279ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/simple-concat 414ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/safe-buffer 405ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/tar-stream 414ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/pump 509ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/mkdirp-classic 518ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/chownr 536ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/once 554ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/decompress-response 562ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/rc 590ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-string 601ms (cache revalidated)
npm timing idealTree:node_modules/sharp Completed in 641ms
npm http fetch GET 200 https://registry.npmjs.org/color-name 167ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-name 176ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle 178ms (cache revalidated)
npm timing idealTree:node_modules/color Completed in 188ms
npm timing idealTree:node_modules/color-convert Completed in 3ms
npm timing idealTree:node_modules/color-name Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 183ms (cache revalidated)
npm timing idealTree:node_modules/color-string Completed in 189ms
npm timing idealTree:node_modules/detect-libc Completed in 0ms
npm timing idealTree:node_modules/node-addon-api Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/strip-json-comments 186ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/ini 192ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/deep-extend 196ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/end-of-stream 217ms (cache revalidated)
npm timing idealTree:node_modules/prebuild-install Completed in 248ms
npm timing idealTree:node_modules/expand-template Completed in 0ms
npm timing idealTree:node_modules/github-from-package Completed in 0ms
npm timing idealTree:node_modules/minimist Completed in 0ms
npm timing idealTree:node_modules/mkdirp-classic Completed in 0ms
npm timing idealTree:node_modules/napi-build-utils Completed in 0ms
npm timing idealTree:node_modules/node-abi Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/wrappy 197ms (cache revalidated)
npm timing idealTree:node_modules/pump Completed in 205ms
npm timing idealTree:node_modules/end-of-stream Completed in 0ms
npm timing idealTree:node_modules/once Completed in 3ms
npm timing idealTree:node_modules/rc Completed in 7ms
npm timing idealTree:node_modules/deep-extend Completed in 0ms
npm timing idealTree:node_modules/ini Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/yallist 188ms (cache revalidated)
npm timing idealTree:node_modules/semver Completed in 193ms
npm timing idealTree:node_modules/lru-cache Completed in 4ms
npm http fetch GET 200 https://registry.npmjs.org/mimic-response 179ms (cache revalidated)
npm timing idealTree:node_modules/simple-get Completed in 189ms
npm timing idealTree:node_modules/decompress-response Completed in 2ms
npm timing idealTree:node_modules/mimic-response Completed in 0ms
npm timing idealTree:node_modules/simple-concat Completed in 0ms
npm timing idealTree:node_modules/simple-swizzle Completed in 2ms
npm timing idealTree:node_modules/is-arrayish Completed in 0ms
npm timing idealTree:node_modules/strip-json-comments Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/inherits 171ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/bl 186ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/readable-stream 190ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/fs-constants 853ms (cache revalidated)
npm timing idealTree:node_modules/tar-fs Completed in 860ms
npm timing idealTree:node_modules/chownr Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/string_decoder 174ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/buffer 179ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/util-deprecate 221ms (cache revalidated)
npm timing idealTree:node_modules/tar-stream Completed in 235ms
npm http fetch GET 200 https://registry.npmjs.org/ieee754 210ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/base64-js 222ms (cache revalidated)
npm timing idealTree:node_modules/bl Completed in 225ms
npm timing idealTree:node_modules/buffer Completed in 3ms
npm timing idealTree:node_modules/base64-js Completed in 0ms
npm timing idealTree:node_modules/fs-constants Completed in 0ms
npm timing idealTree:node_modules/ieee754 Completed in 0ms
npm timing idealTree:node_modules/inherits Completed in 0ms
npm timing idealTree:node_modules/readable-stream Completed in 4ms
npm timing idealTree:node_modules/string_decoder Completed in 2ms
npm timing idealTree:node_modules/safe-buffer Completed in 0ms
npm timing idealTree:node_modules/tunnel-agent Completed in 0ms
npm timing idealTree:node_modules/util-deprecate Completed in 0ms
npm timing idealTree:node_modules/wrappy Completed in 0ms
npm timing idealTree:node_modules/yallist Completed in 0ms
npm timing idealTree:buildDeps Completed in 4978ms
npm timing idealTree:fixDepFlags Completed in 2ms
npm timing idealTree Completed in 5006ms
npm timing reify:loadTrees Completed in 5008ms
npm timing reify:diffTrees Completed in 3ms
npm timing reify:retireShallow Completed in 2ms
npm timing reify:createSparse Completed in 285ms
npm timing reify:loadBundles Completed in 0ms
npm timing reifyNode:node_modules/chownr Completed in 294ms
npm timing reifyNode:node_modules/strip-json-comments Completed in 296ms
npm timing reifyNode:node_modules/ini Completed in 297ms
npm timing reifyNode:node_modules/wrappy Completed in 297ms
npm timing reifyNode:node_modules/once Completed in 298ms
npm timing reifyNode:node_modules/end-of-stream Completed in 299ms
npm timing reifyNode:node_modules/mkdirp-classic Completed in 300ms
npm timing reifyNode:node_modules/simple-swizzle Completed in 301ms
npm timing reifyNode:node_modules/color-name Completed in 302ms
npm timing reifyNode:node_modules/color-string Completed in 303ms
npm timing reifyNode:node_modules/ieee754 Completed in 311ms
npm timing reifyNode:node_modules/inherits Completed in 312ms
npm timing reifyNode:node_modules/fs-constants Completed in 313ms
npm timing reifyNode:node_modules/mimic-response Completed in 314ms
npm timing reifyNode:node_modules/decompress-response Completed in 315ms
npm timing reifyNode:node_modules/lru-cache Completed in 316ms
npm timing reifyNode:node_modules/tunnel-agent Completed in 316ms
npm timing reifyNode:node_modules/color Completed in 319ms
npm timing reifyNode:node_modules/util-deprecate Completed in 323ms
npm timing reifyNode:node_modules/base64-js Completed in 323ms
npm timing reifyNode:node_modules/yallist Completed in 324ms
npm timing reifyNode:node_modules/expand-template Completed in 325ms
npm timing reifyNode:node_modules/pump Completed in 329ms
npm timing reifyNode:node_modules/napi-build-utils Completed in 330ms
npm timing reifyNode:node_modules/safe-buffer Completed in 337ms
npm timing reifyNode:node_modules/string_decoder Completed in 338ms
npm timing reifyNode:node_modules/is-arrayish Completed in 338ms
npm timing reifyNode:node_modules/simple-concat Completed in 341ms
npm timing reifyNode:node_modules/deep-extend Completed in 341ms
npm timing reifyNode:node_modules/color-convert Completed in 342ms
npm timing reifyNode:node_modules/tar-stream Completed in 351ms
npm timing reifyNode:node_modules/detect-libc Completed in 351ms
npm timing reifyNode:node_modules/buffer Completed in 358ms
npm timing reifyNode:node_modules/simple-get Completed in 365ms
npm timing reifyNode:node_modules/prebuild-install Completed in 366ms
npm timing reifyNode:node_modules/bl Completed in 380ms
npm timing reifyNode:node_modules/github-from-package Completed in 379ms
npm timing reifyNode:node_modules/rc Completed in 382ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 396ms
npm timing auditReport:getReport Completed in 402ms
npm timing auditReport:init Completed in 0ms
npm timing reify:audit Completed in 405ms
npm timing reifyNode:node_modules/node-abi Completed in 417ms
npm timing reifyNode:node_modules/minimist Completed in 428ms
npm timing reifyNode:node_modules/readable-stream Completed in 443ms
npm timing reifyNode:node_modules/node-addon-api Completed in 444ms
npm timing reifyNode:node_modules/semver Completed in 457ms
npm timing reifyNode:node_modules/tar-fs Completed in 466ms
npm timing reifyNode:node_modules/sharp Completed in 472ms
npm timing reify:unpack Completed in 478ms
npm timing reify:unretire Completed in 1ms
npm timing build:queue Completed in 5ms
npm timing build:link:node_modules/prebuild-install Completed in 5ms
npm timing build:link:node_modules/rc Completed in 12ms
npm timing build:link:node_modules/semver Completed in 13ms
npm timing build:link Completed in 15ms
npm info run sharp@0.31.2 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

> sharp@0.31.2 install
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Using local libvips from /home/ubuntu/full_strapi/app/libvips/v8.13.3/libvips-8.13.3-linux-x64.tar.br& node install/dll-copy && prebuild-install) || (node install/can-compile && nod
sharp: Installation error: ENOENT: no such file or directory, open '/home/ubuntu/full_strapi/app/libvips/v8.13.3/libvips-8.13.3-linux-x64.tar.br'
sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
gyp info it worked if it ends with oknfo run sharp@0.31.2 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && nod
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild'
gyp verb cli ]
gyp info using node-gyp@9.1.0
gyp info using node@18.12.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configurations/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && nod
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - executable path is "/usr/bin/python3"stall node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && nod
gyp verb find Python - executing "/usr/bin/python3" to get version
gyp verb find Python - version is "3.8.10"un sharp@0.31.2 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && nod
gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"es/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && nod
gyp verb get node dir no --target version specified, falling back to host node version: 18.12.1
gyp verb command install [ '18.12.1' ]
gyp verb install input version string "18.12.1"arp@0.31.2 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && nod
gyp verb install installing version: 18.12.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 18.12.1
gyp verb build dir attempting to create "build" dir: /home/kupexadm/sharp/node_modules/sharp/build
gyp verb build dir "build" dir needed to be created? Yes
gyp verb python symlink creating symlink to "/usr/bin/python3" at "/home/kupexadm/sharp/node_modules/sharp/build/node_gyp_bins/python3"
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/kupexadm/sharp/node_modules/sharp/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/kupexadm/sharp/node_modules/sharp/config.gypi
gyp verb common.gypi checking for gypi file: /home/kupexadm/sharp/node_modules/sharp/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/kupexadm/sharp/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/18.12.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/18.12.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/18.12.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/kupexadm/sharp/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []ify:sharp: info run sharp@0.31.2 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && nod
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /root/.cache/node-gyp/18.12.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp verb bin symlinks adding symlinks (such as Python), at "/home/kupexadm/sharp/node_modules/sharp/build/node_gyp_bins", to PATH
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/kupexadm/sharp/node_modules/sharp/build'
  cc -o Release/obj.target/nothing/../node-addon-api/nothing.o ../../node-addon-api/nothing.c '-DNODE_GYP_MODULE_NAME=nothing' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' -I/root/.cache/node-gyp/18.12.1/include/node -I/root/.cache/node-gyp/18.12.1/src -I/root/.cache/node-gyp/18.12.1/deps/openssl/config -I/root/.cache/node-gyp/18.12.1/deps/openssl/openssl/include -I/root/.cache/node-gyp/18.12.1/deps/uv/include -I/root/.cache/node-gyp/18.12.1/deps/zlib -I/root/.cache/node-gyp/18.12.1/deps/v8/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer  -MMD -MF ./Release/.deps/Release/obj.target/nothing/../node-addon-api/nothing.o.d.raw   -c
  rm -f Release/obj.target/../node-addon-api/nothing.a && ar crs Release/obj.target/../node-addon-api/nothing.a Release/obj.target/nothing/../node-addon-api/nothing.oall/can-compile && nod
  ln -f "Release/obj.target/../node-addon-api/nothing.a" "Release/nothing.a" 2>/dev/null || (rm -rf "Release/nothing.a" && cp -af "Release/obj.target/../node-addon-api/nothing.a" "Release/nothing.a")
  touch Release/obj.target/libvips-cpp.stamp
  g++ -o Release/obj.target/sharp-linux-x64/src/common.o ../src/common.cc '-DNODE_GYP_MODULE_NAME=sharp-linux-x64' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNAPI_VERSION=7' '-DBUILDING_NODE_EXTENSION' -I/root/.cache/node-gyp/18.12.1/include/node -I/root/.cache/node-gyp/18.12.1/src -I/root/.cache/node-gyp/18.12.1/deps/openssl/config -I/root/.cache/node-gyp/18.12.1/deps/openssl/openssl/include -I/root/.cache/node-gyp/18.12.1/deps/uv/include -I/root/.cache/node-gyp/18.12.1/deps/zlib -I/root/.cache/node-gyp/18.12.1/deps/v8/include -I../../node-addon-api -I../vendor/8.13.3/linux-x64/include -I../vendor/8.13.3/linux-x64/include/glib-2.0 -I../vendor/8.13.3/linux-x64/lib/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++17 -std=c++0x -fexceptions -Wall -Os -Wno-cast-function-type -MMD -MF ./Release/.deps/Release/obj.target/sharp-linux-x64/src/common.o.d.raw   -c
In file included from ../src/common.cc:24:
/usr/include/vips/vips8:35:10: fatal error: glib-object.h: No such file or directory
   35 | #include <glib-object.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [sharp-linux-x64.target.mk:139: Release/obj.target/sharp-linux-x64/src/common.o] Error 1
make: Leaving directory '/home/kupexadm/sharp/node_modules/sharp/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.4.0-100-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/kupexadm/sharp/node_modules/sharp
gyp ERR! node -v v18.12.1
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok
npm info run sharp@0.31.2 install { code: 1, signal: null }
npm timing reify:rollback:createSparse Completed in 127ms
npm timing reify:rollback:retireShallow Completed in 0ms
npm timing command:install Completed in 7801ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
npm verb stack     at ChildProcess.emit (node:events:513:28)
npm verb stack     at maybeClose (node:internal/child_process:1091:16)
npm verb stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm verb pkgid sharp@0.31.2
npm verb cwd /home/kupexadm/sharp
npm verb Linux 5.4.0-100-generic
npm verb node v18.12.1
npm verb npm  v8.19.2
npm ERR! code 1
npm ERR! path /home/kupexadm/sharp/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c -- (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm verb exit 1
npm timing npm Completed in 7987ms
npm verb unfinished npm timer reify 1671105188206
npm verb unfinished npm timer reify:build 1671105194014
npm verb unfinished npm timer build 1671105194015
npm verb unfinished npm timer build:deps 1671105194015
npm verb unfinished npm timer build:run:install 1671105194037
npm verb unfinished npm timer build:run:install:node_modules/sharp 1671105194038
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-12-15T11_53_08_024Z-debug-0.log

**Comment by lovell** [comment]
The salient part of this log is:

> sharp: Using local libvips from /home/ubuntu/full_strapi/app/libvips/v8.13.3/libvips-8.13.3-linux-x64.tar.br
> sharp: Installation error: ENOENT: no such file or directory, open '/home/ubuntu/full_strapi/app/libvips/v8.13.3/libvips-8.13.3-linux-x64.tar.br'

You'll need to make sure the relevant file is available at the correct location on the filesystem.

**Comment by govind-dev1012000** [comment]
Hi @lovell 
sharp: Using local libvips from /home/ubuntu/full_strapi/app/libvips/v8.13.3/libvips-8.13.3-linux-x64.tar.br& node install/dll-copy && prebuild-install) || (node install/can-compile && nod
sharp: Installation error: ENOENT: no such file or directory, open '/home/ubuntu/full_strapi/app/libvips/v8.13.3/libvips-8.13.3-linux-x64.tar.br'

I have set the sharp_libvips_local_prebuilds to /v8.13.1/libvips-8.13.1-linux-x64.tar.br to v8.13.1 , but it is trying to get v8.13.3 from online github

**Comment by lovell** [comment]
Yes, that's intentional, as libvips v8.13.3 is required for sharp v0.31.2.

**Comment by govind-dev1012000** [comment]
Thank You @lovell , The issue got resolved its only the version error now I have changed the .br and .gz to libvips v8.13.3 and sharp v0.31.2 and set the   ### sharp_libvips_local_prebuilds and ### sharp_local_prebuilds , now the npm install is working.
