### ISSUE TITLE
Image not keeping color after jpeg() format applied

### ISSUE THREAD

**Issue by AHM77777** [lovell/sharp#3497]
### What are you trying to achieve?

We have an application that applies transformations to JPG and PNG images. After upgrading the system to Node 14 I updated the following libraries as well:

1. Sharp 0.22.1 -> 0.31.2
2. color 3.1.0 -> 4.2.3
3. imagemin 6.1.0 -> 7.0.1
4. imagemin-jpegtran 6.0.0 -> 7.0.0
5. imagemin-mozjpeg 8.0.0 -> 9.0.0
6. imagemin-optipng 6.0.0 -> 7.0.0

My current OS is macOS Monterey 12.3.1.

running Node version 12.3.1 for old sharp, and version 14.15.0 for new sharp.

I noticed that 3 of the tests in our unit tests started to fail, the test looks like this:

```
    const pointColor = Color('#ff00ff').object();

    const pointImage = await imageGenerator.imageBuffer(1, 1, pointColor);

    const image = await imageGenerator.extendedFromPosition(pointImage, 5, 5);

    const centerPixel = await pixelParser.getPixel(image, 'center');

    assert.deepEqual(centerPixel, pointColor, 'Color channels');
```
`imageGenerator.imageBuffer` simply creates a Sharp transform object using the passed color ({r: 255, g: 0, b: 255}) with 4 channels and the provided width and height (first two arguments). Then the first jpeg() formatting is applied `sharpTransformation.jpeg({ quality: 100 })`

```
  const transform = sharp(
    {
      create: {
        width,
        height,
        channels: 4,
        background: rgbaColor,
      },
    },
  );

  transform.jpeg({ quality: 100 });

  return transform.toBuffer();
```

At this stage the images are literally the same, but then we run into the first JPG formatting, and they now differ a bit.

**Before formatting**
image--SharpVersion0.31.2--original
![image--SharpVersion0.31.2--original](https://user-images.githubusercontent.com/12972508/208164462-44bd40b7-fb66-42d4-8dcf-574ed3688383.jpg)
image--SharpVersion0.22.1--original
![image--SharpVersion0.22.1--original](https://user-images.githubusercontent.com/12972508/208164606-81db8bee-17de-44d1-a872-46bc2487bbdf.jpg)
**After formatting**
image--SharpVersion0.31.2--firstJpegFormatting
![image--SharpVersion0.31.2--firstJpegFormatting](https://user-images.githubusercontent.com/12972508/208164998-8c89a045-4bdd-492c-8875-da828ed13cf6.jpg)
image--SharpVersion0.22.1--firstJpegFormatting
![image--SharpVersion0.22.1--firstJpegFormatting](https://user-images.githubusercontent.com/12972508/208165125-51883cf9-bc23-4ebf-9b7a-f1b07249b00e.jpg)

PD. _sorry if the images are this small at this point of the script._

After formatting the newest version returns a total of 270 bytes for the image, while the old one stays at 268 bytes, with jpeg formatting of `quality: 100`.

Then we extend the image by retrieving extension options, for this specific case the extension options are as follows:
```
const extOpts = {
  top: 2,
  bottom: 2,
  left: 2,
  right: 2,
  background: { r: 0, g: 0, b: 0, alpha: 0 }
};
const transform = sharp(colorImageBuffer).extend(extOpts);
transform.jpeg({ quality: 100 });
```

Once extended both images do look and weight almost the same (296 and 297 bytes respectively), with the center pixel a more gray colored version of the original pink.

**After extension**
image--SharpVersion0.31.2--afterExtension
![image--SharpVersion0.31.2--afterExtension](https://user-images.githubusercontent.com/12972508/208168113-1457ddb2-054b-48a1-a338-32dd5019d897.jpg)
image--SharpVersion0.22.1--afterExtension
![image--SharpVersion0.22.1--afterExtension](https://user-images.githubusercontent.com/12972508/208168316-b980c0c9-9b23-420d-a6e1-1669ac908cd0.jpg)

Then we apply the second jpeg formatting and in the old version ended up with a bright pink colored center pixel, which would make the test successful. But with the new version the center pixel is not even close to the original color (though it retains some traces of pink).

**After second formatting**
image--SharpVersion0.31.2--secondJpegFormatting
![image--SharpVersion0.31.2--secondJpegFormatting](https://user-images.githubusercontent.com/12972508/208168740-fb29a12f-7dd8-4ee7-9fb2-eefb9bbb282a.jpg)
image--SharpVersion0.22.1--secondJpegFormatting
![image--SharpVersion0.22.1--secondJpegFormatting](https://user-images.githubusercontent.com/12972508/208168801-d21ac0e8-5c62-402f-b65c-bfd20a924a35.jpg)

Images here are 387 and 412 bytes respectively, which would make in theory the old image bigger (retains more quality?) but if I mess with the settings for quality on the old version I'm able to match the color of the newer image with anything below 90%.

What could be possibly going on? While this is only affecting our tests, I fear that the library will end up doing unexpected manipulations on images, and from 95 tests only 3 are failing, one of them being described in this thread.

Failed tests output
```
  92 passing (4s)
  3 failing

  1) ImageProcessor: pixelParser
       should return center pixel from image buffer:

      Color channels
      + expected - actual

       {
      -  "b": 125
      -  "g": 89
      -  "r": 125
      +  "b": 255
      +  "g": 0
      +  "r": 255
       }

  2) ImageProcessor: WebP (THIS ONE IS DOING A RESIZE AND THEN APPLYING WEBP ENCODING TO THE SHARP OBJECT)
       should not resize image if no dpr, width and height provided (but does provide a byte reduction) :

      Image height
      + expected - actual

      -2986
      +2990

  3) ImageProcessor: resizer (THIS ONE IS DOING A SIMILAR PROCEDURE AS THE FIRST TEST, WHERE IT GENERATES A COLOR IMAGE TO PERFORM OPERATIONS ON)
       options: trim, trim_color
         should trim image by trim_color:

      Perceptually uniform color distance
      + expected - actual

      -55.26562668905151
      +2.5
```

Please let me know if more info will be needed, I'm open to discuss on this and I really do need help to understand the reason for this behavior, without having to trail the manually go through the whole library logging the outputs to understand how is data being manipulated and where does it gets messed up.

Thanks for the help!

### When you searched for similar issues, what did you find that might be related?

Didn't really found anything similar, nor any thread mentioning such errors from upgrades.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

Already provided code samples in the Issue, the code is private so I can't share it entirely.

### Please provide sample image(s) that help explain this question

Already provided images.

**Comment by lovell** [comment]
There have been *a lot* of changes in the 4 year period since sharp v0.22.1. Perhaps you could try rolling forward a few versions at a time (similar to `git bisect`) to see if you can work out when the change first occurred.

**Comment by AHM77777** [comment]
Understood, yeah at the end of the day I believe I will have to go bug hunting through both repos to see how is the data behaving.

I will keep updating this with my findings. Thanks!

**Comment by AHM77777** [comment]
Hi again, as an update, I found out that the error started happening since version 0.26.0. Every other previous version would pass the test, but from this one onwards the errors posted here started happening.

I'm trying to figure out which of the changes could have impacted the results.

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/changelog#v0260---25th-august-2020

> JPEG output `quality` >= 90 no longer automatically sets `chromaSubsampling` to `4:4:4`.

**Comment by AHM77777** [comment]
Yes! After changing that property the output was correct and the failing tests passed.

Now I moved to the latest version and only tests is failing.

  1) ImageProcessor: WebP
       should not resize image if no dpr, width and height provided (but does provide a byte reduction) :

      Image height
      + expected - actual

      -2986
      +2990
      
The test looks like this:
```
      const imagePath = '/test-image.jpeg';
      const expectedByteLength = 2990;

      const inputImage = getImageByPath(imagePath);

      const options = {};
      const outputImage = await webpProcessor(inputImage, options);

      assert.equal(outputImage.byteLength, expectedByteLength,
        'Image height');
```
In this test we aren't passing any options to the transformer object (`webpProcessor(imagePath)`), so it's just running something like this:
```
    sharpTransform.webp({
      quality: parseInt(compression || DEFAULT_COMPRESSION, 10),
      reductionEffort: WEBP_EFFORT,
    });

    const transformBuffer = await sharpTransform.toBuffer({ resolveWithObject: false });

```

Changing the WEBP_EFFORT won't change the returned bytes, but considering it's just a 4 bytes difference I think I can just update the test.

I'll identify exactly in which version from 0.26.0 to 0.31.2 this started happening and post it here as well.

But I can consider this solved! Thanks a lot!
