### ISSUE TITLE
Windows 8 (EOL): prebuilt win32-ia32 binaries require UCRT on x86 from v0.28.0

### ISSUE THREAD

**Issue by haoxi911** [lovell/sharp#3499]
## Possible install-time or require-time problem

- [x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

The output is `0.31.2` which is the latest version.

### Is this a problem with filesystem permissions?

I don't think so.

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   '--foreground-scripts',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@8.5.0
npm info using node@v16.14.2
npm timing npm:load:whichnode Completed in 1ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Compl
eted in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 1ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:C:\Users\Hao\Downloads\empty\.npmrc Completed in 0ms

npm timing config:load:project Completed in 1ms
npm timing config:load:file:C:\Users\Hao\.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:C:\Users\Hao\AppData\Roaming\npm\etc\npmrc Completed
 in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 0ms
npm timing config:load Completed in 7ms
npm timing npm:load:configload Completed in 7ms
npm timing npm:load:setTitle Completed in 1ms
npm timing config:load:flatten Completed in 3ms
npm timing npm:load:display Completed in 17ms
npm verb logfile C:\Users\Hao\AppData\Local\npm-cache\_logs\2022-12-19T03_07_38_
940Z-debug-0.log
npm timing npm:load:logFile Completed in 6ms
npm timing npm:load:timers Completed in 0ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load Completed in 34ms
npm timing arborist:ctor Completed in 0ms
npm timing arborist:ctor Completed in 1ms
npm timing idealTree:init Completed in 40ms
npm timing idealTree:userRequests Completed in 1ms
npm http fetch GET 200 https://registry.npmjs.org/sharp 23ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 192ms (cache reval
idated)
npm http fetch GET 200 https://registry.npmjs.org/tunnel-agent 196ms (cache reva
lidated)
npm http fetch GET 200 https://registry.npmjs.org/node-addon-api 202ms (cache re
validated)
npm http fetch GET 200 https://registry.npmjs.org/tar-fs 209ms (cache revalidate
d)
npm http fetch GET 200 https://registry.npmjs.org/semver 215ms (cache revalidate
d)
npm http fetch GET 200 https://registry.npmjs.org/prebuild-install 216ms (cache
revalidated)
npm http fetch GET 200 https://registry.npmjs.org/simple-get 219ms (cache revali
dated)
npm http fetch GET 200 https://registry.npmjs.org/color 222ms (cache revalidated
)
npm timing idealTree:#root Completed in 256ms
npm http fetch GET 200 https://registry.npmjs.org/github-from-package 127ms (cac
he revalidated)
npm http fetch GET 200 https://registry.npmjs.org/expand-template 149ms (cache r
evalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-convert 151ms (cache rev
alidated)
npm http fetch GET 200 https://registry.npmjs.org/color-string 153ms (cache reva
lidated)
npm http fetch GET 200 https://registry.npmjs.org/node-abi 143ms (cache revalida
ted)
npm http fetch GET 200 https://registry.npmjs.org/mkdirp-classic 145ms (cache re
validated)
npm http fetch GET 200 https://registry.npmjs.org/minimist 146ms (cache revalida
ted)
npm http fetch GET 200 https://registry.npmjs.org/tar-stream 142ms (cache revali
dated)
npm http fetch GET 200 https://registry.npmjs.org/safe-buffer 143ms (cache reval
idated)
npm http fetch GET 200 https://registry.npmjs.org/rc 159ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/chownr 168ms (cache revalidate
d)
npm http fetch GET 200 https://registry.npmjs.org/once 178ms (cache revalidated)

npm http fetch GET 200 https://registry.npmjs.org/lru-cache 195ms (cache revalid
ated)
npm http fetch GET 200 https://registry.npmjs.org/decompress-response 197ms (cac
he revalidated)
npm http fetch GET 200 https://registry.npmjs.org/napi-build-utils 448ms (cache
revalidated)
npm http fetch GET 200 https://registry.npmjs.org/simple-concat 616ms (cache rev
alidated)
npm http fetch GET 200 https://registry.npmjs.org/pump 620ms (cache revalidated)

npm timing idealTree:node_modules/sharp Completed in 660ms
npm http fetch GET 200 https://registry.npmjs.org/color-name 60ms (cache revalid
ated)
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle 71ms (cache rev
alidated)
npm timing idealTree:node_modules/color Completed in 81ms
npm timing idealTree:node_modules/color-convert Completed in 1ms
npm timing idealTree:node_modules/color-name Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 46ms (cache revali
dated)
npm timing idealTree:node_modules/color-string Completed in 49ms
npm timing idealTree:node_modules/detect-libc Completed in 0ms
npm timing idealTree:node_modules/node-addon-api Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/end-of-stream 54ms (cache reva
lidated)
npm http fetch GET 200 https://registry.npmjs.org/strip-json-comments 54ms (cach
e revalidated)
npm http fetch GET 200 https://registry.npmjs.org/ini 58ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/deep-extend 60ms (cache revali
dated)
npm timing idealTree:node_modules/prebuild-install Completed in 69ms
npm timing idealTree:node_modules/expand-template Completed in 0ms
npm timing idealTree:node_modules/github-from-package Completed in 0ms
npm timing idealTree:node_modules/minimist Completed in 0ms
npm timing idealTree:node_modules/mkdirp-classic Completed in 0ms
npm timing idealTree:node_modules/napi-build-utils Completed in 0ms
npm timing idealTree:node_modules/node-abi Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/wrappy 37ms (cache revalidated
)
npm timing idealTree:node_modules/pump Completed in 43ms
npm timing idealTree:node_modules/end-of-stream Completed in 0ms
npm timing idealTree:node_modules/once Completed in 1ms
npm timing idealTree:node_modules/rc Completed in 3ms
npm timing idealTree:node_modules/deep-extend Completed in 0ms
npm timing idealTree:node_modules/ini Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/yallist 48ms (cache revalidate
d)
npm timing idealTree:node_modules/semver Completed in 50ms
npm timing idealTree:node_modules/lru-cache Completed in 1ms
npm http fetch GET 200 https://registry.npmjs.org/mimic-response 47ms (cache rev
alidated)
npm timing idealTree:node_modules/simple-get Completed in 50ms
npm timing idealTree:node_modules/decompress-response Completed in 1ms
npm timing idealTree:node_modules/mimic-response Completed in 0ms
npm timing idealTree:node_modules/simple-concat Completed in 0ms
npm timing idealTree:node_modules/simple-swizzle Completed in 1ms
npm timing idealTree:node_modules/is-arrayish Completed in 0ms
npm timing idealTree:node_modules/strip-json-comments Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/inherits 48ms (cache revalidat
ed)
npm http fetch GET 200 https://registry.npmjs.org/fs-constants 51ms (cache reval
idated)
npm http fetch GET 200 https://registry.npmjs.org/bl 54ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/readable-stream 58ms (cache re
validated)
npm timing idealTree:node_modules/tar-fs Completed in 63ms
npm timing idealTree:node_modules/chownr Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/string_decoder 45ms (cache rev
alidated)
npm http fetch GET 200 https://registry.npmjs.org/buffer 47ms (cache revalidated
)
npm http fetch GET 200 https://registry.npmjs.org/util-deprecate 63ms (cache rev
alidated)
npm timing idealTree:node_modules/tar-stream Completed in 68ms
npm http fetch GET 200 https://registry.npmjs.org/base64-js 64ms (cache revalida
ted)
npm http fetch GET 200 https://registry.npmjs.org/ieee754 64ms (cache revalidate
d)
npm timing idealTree:node_modules/bl Completed in 67ms
npm timing idealTree:node_modules/buffer Completed in 2ms
npm timing idealTree:node_modules/base64-js Completed in 0ms
npm timing idealTree:node_modules/fs-constants Completed in 0ms
npm timing idealTree:node_modules/ieee754 Completed in 0ms
npm timing idealTree:node_modules/inherits Completed in 0ms
npm timing idealTree:node_modules/readable-stream Completed in 2ms
npm timing idealTree:node_modules/string_decoder Completed in 1ms
npm timing idealTree:node_modules/safe-buffer Completed in 0ms
npm timing idealTree:node_modules/tunnel-agent Completed in 0ms
npm timing idealTree:node_modules/util-deprecate Completed in 0ms
npm timing idealTree:node_modules/wrappy Completed in 0ms
npm timing idealTree:node_modules/yallist Completed in 0ms
npm timing idealTree:buildDeps Completed in 1489ms
npm timing idealTree:fixDepFlags Completed in 1ms
npm timing idealTree Completed in 1534ms
npm timing reify:loadTrees Completed in 1544ms
npm timing reify:diffTrees Completed in 1ms
npm timing reify:retireShallow Completed in 0ms
npm timing reify:createSparse Completed in 31ms
npm timing reify:loadBundles Completed in 0ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/
bulk 168ms
npm timing auditReport:getReport Completed in 171ms
npm timing auditReport:init Completed in 0ms
npm timing reify:audit Completed in 172ms
npm timing reifyNode:node_modules/chownr Completed in 347ms
npm timing reifyNode:node_modules/strip-json-comments Completed in 348ms
npm timing reifyNode:node_modules/ini Completed in 348ms
npm timing reifyNode:node_modules/wrappy Completed in 349ms
npm timing reifyNode:node_modules/once Completed in 350ms
npm timing reifyNode:node_modules/end-of-stream Completed in 349ms
npm timing reifyNode:node_modules/mkdirp-classic Completed in 354ms
npm timing reifyNode:node_modules/simple-swizzle Completed in 355ms
npm timing reifyNode:node_modules/color-name Completed in 355ms
npm timing reifyNode:node_modules/color-string Completed in 356ms
npm timing reifyNode:node_modules/lru-cache Completed in 368ms
npm timing reifyNode:node_modules/tunnel-agent Completed in 370ms
npm timing reifyNode:node_modules/color Completed in 372ms
npm timing reifyNode:node_modules/string_decoder Completed in 375ms
npm timing reifyNode:node_modules/ieee754 Completed in 445ms
npm timing reifyNode:node_modules/inherits Completed in 447ms
npm timing reifyNode:node_modules/fs-constants Completed in 447ms
npm timing reifyNode:node_modules/mimic-response Completed in 448ms
npm timing reifyNode:node_modules/decompress-response Completed in 450ms
npm timing reifyNode:node_modules/yallist Completed in 467ms
npm timing reifyNode:node_modules/napi-build-utils Completed in 467ms
npm timing reifyNode:node_modules/safe-buffer Completed in 472ms
npm timing reifyNode:node_modules/is-arrayish Completed in 479ms
npm timing reifyNode:node_modules/util-deprecate Completed in 547ms
npm timing reifyNode:node_modules/base64-js Completed in 548ms
npm timing reifyNode:node_modules/simple-concat Completed in 556ms
npm timing reifyNode:node_modules/expand-template Completed in 557ms
npm timing reifyNode:node_modules/deep-extend Completed in 559ms
npm timing reifyNode:node_modules/detect-libc Completed in 567ms
npm timing reifyNode:node_modules/pump Completed in 585ms
npm timing reifyNode:node_modules/color-convert Completed in 590ms
npm timing reifyNode:node_modules/buffer Completed in 593ms
npm timing reifyNode:node_modules/simple-get Completed in 606ms
npm timing reifyNode:node_modules/tar-stream Completed in 652ms
npm timing reifyNode:node_modules/bl Completed in 696ms
npm timing reifyNode:node_modules/github-from-package Completed in 743ms
npm timing reifyNode:node_modules/node-abi Completed in 756ms
npm timing reifyNode:node_modules/rc Completed in 762ms
npm timing reifyNode:node_modules/prebuild-install Completed in 815ms
npm timing reifyNode:node_modules/tar-fs Completed in 840ms
npm timing reifyNode:node_modules/minimist Completed in 881ms
npm timing reifyNode:node_modules/node-addon-api Completed in 900ms
npm timing reifyNode:node_modules/readable-stream Completed in 923ms
npm timing reifyNode:node_modules/semver Completed in 997ms
npm timing reifyNode:node_modules/sharp Completed in 1048ms
npm timing reify:unpack Completed in 1051ms
npm timing reify:unretire Completed in 0ms
npm timing build:queue Completed in 14ms
npm timing build:link:node_modules/prebuild-install Completed in 38ms
npm timing build:link:node_modules/rc Completed in 38ms
npm timing build:link:node_modules/semver Completed in 38ms
npm timing build:link Completed in 40ms
npm info run sharp@0.31.2 install node_modules/sharp (node install/libvips && no
de install/dll-copy && prebuild-install) || (node install/can-compile && node-gy
p rebuild && node install/dll-copy)

> sharp@0.31.2 install
> (node install/libvips && node install/dll-copy && prebuild-install) || (node i
nstall/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Using cached C:\Users\Hao\AppData\Local\npm-cache\_libvips\libvips-8.13.3
-win32-ia32.tar.br
[##################] | reify:sharp: infosharp: Integrity check passed for win32-
ia32
[##################] | reify:sharp: infosharp: Creating C:\Users\Hao\Downloads\e
mpty\node_modules\sharp\build\Release
 runsharp: Copying DLLs from C:\Users\Hao\Downloads\empty\node_modules\sharp\ven
dor\8.13.3\win32-ia32\lib to C:\Users\Hao\Downloads\empty\node_modules\sharp\bui
ld\Release
[##################] | reify:sharp: infoprebuild-install info begin Prebuild-ins
tall version 7.1.1
prebuild-install info looking for local prebuild @ prebuilds\sharp-v0.31.2-napi-
v7-win32-ia32.tar.gz
 runprebuild-install info looking for cached prebuild @ C:\Users\Hao\AppData\Loc
al\npm-cache\_prebuilds\e19317-sharp-v0.31.2-napi-v7-win32-ia32.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ C:\Users\Hao\AppData\Local\npm-cache\_prebuild
s\e19317-sharp-v0.31.2-napi-v7-win32-ia32.tar.gz
 sharp@0.31.2 install node_modules/prebuild-install info unpack resolved to C:\U
sers\Hao\Downloads\empty\node_modules\sharp\build\Release\sharp-win32-ia32.node
prebuild-install info install Successfully installed prebuilt binary!
npm info run sharp@0.31.2 install { code: 0, signal: null }
npm timing build:run:install:node_modules/sharp Completed in 3184ms
npm timing build:run:install Completed in 3186ms
npm timing build:deps Completed in 3241ms
npm timing build Completed in 3242ms
npm timing reify:build Completed in 3242ms
npm timing reify:trash Completed in 0ms
npm timing reify:save Completed in 12ms
npm timing reify Completed in 5904ms

added 45 packages, and audited 46 packages in 6s

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm timing command:install Completed in 5920ms
npm verb exit 0
npm timing npm Completed in 6182ms
npm info ok
</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

<details>
 System:
   OS: Windows 8.1 6.3.9600
   CPU: (1) ia32 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
   Memory: 2.70 GB / 3.50 GB
 Binaries:
   Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
   npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
 npmPackages:
   sharp: ^0.31.2 => 0.31.2
</details>

## Issue Description

The latest version of `sharp` (win32 + ia32) can't be loaded on Windows 8.1 Pro (32-bits) with Node.js 16.14.2 (32-bits). Here are the steps to reproduce:

- Find a PC with Windows 8.1 Pro (32-bits), I found the ISO file [here](https://www.softlay.com/downloads/windows-8-1-pro/2) and installed it in VirtualBox
- Install Node.js 16.14.2 (32-bits) on Windows 8.1, here is the download [link](https://nodejs.org/dist/v16.14.2/node-v16.14.2-x86.msi)
- Create an empty directory, run `npm init` and then `npm install --platform=win32 --arch=ia32 sharp`
- Run `node` CLI, type `require('sharp')` and observe errors

```
Uncaught Error:
Something went wrong installing the "sharp" module

The specified module could not be found.
\\?\C:\Users\Hao\Downloads\test\node_modules\sharp\build\Release\sharp-win32-ia32.node

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreg
round-scripts --verbose sharp"
- Install for the current win32-ia32 runtime: "npm install --platform=win32 --arch=ia32 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (C:\Users\Hao\Downloads\test\node_modules\sharp\lib\sharp.js:34:9)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

## More Information

I used a Visual Studio command line tool called `dumpbin`, and can confirm all `sharp` binaries installed are 32-bits. Also, it works if I install 32-bits Node & sharp, on 64-bits Windows 7/8/10/11.

I meet this problem because I am working an Electron app recently, I am using Electron version 19 (which uses Node 16.14.2).

I tried older version of `sharp` prebuilt binaries, version 0.27.2 is the most recent version that works on 32-bits Windows.

Feel free to let me know if you have any questions!

**Comment by lovell** [comment]
Windows 8 reached end-of-life a couple of years ago but my best guess would be that the Universal C Runtime (UCRT) will need installing manually (the UCRT is provided as standard on Windows 10+).

**Comment by haoxi911** [comment]
Thanks @lovell, you are correct, it is UCRT. I noticed `sharp@0.27` uses `libvips@8.10.5` and `sharp@0.28` uses `libvips@8.10.6`, but by looking at `libvips` [changelogs](https://github.com/libvips/libvips/blob/master/ChangeLog#:~:text=22/12/20%20start%208.10.6), I didn't see they mention anything about UCRT.

When you build `sharp` upon `libvips`, are you building `libvips` from source or you are using the prebuilt binaries? I am just wondering if you can provide any insights on rebuliding `sharp` and `libvips` so that it statically links to UCRT.

I am using `sharp` in a portable desktop software which doesn't require installations, so I would prefer to decouple `sharp` with UCRT dlls. Thank you!

---
For anyone else who meet the same issue, `sharp/libvips` starts requiring UCRT dlls since version `0.28.0`, this can be confirmed by Dependency Walker, see:
![Screenshot 2022-12-22 140923](https://user-images.githubusercontent.com/12502170/209209260-7d8d48a8-0cca-4170-ba3b-d0724d8ced8c.png)

These missing UCRT dlls can be installed from: https://support.microsoft.com/en-us/topic/update-for-universal-c-runtime-in-windows-c0514201-7fe6-95a3-b0a5-287930f3560c

**Comment by kleisauke** [comment]
The libvips Windows binaries are built with [llvm-mingw](https://github.com/mstorsjo/llvm-mingw) since v8.10.6, see:
https://github.com/libvips/build-win64-mxe/releases/tag/v8.10.6

This toolchain uses UCRT (the Universal C Runtime) which is only preinstalled since Windows 10, but can be installed on top of Vista or newer.

> so I would prefer to decouple `sharp` with UCRT dlls

You might be interested in this discussion: https://github.com/libvips/libvips/discussions/2292. Note that this is done on a best effort basis.

**Comment by haoxi911** [comment]
Thanks @kleisauke! That makes sense, I am going to close this issue as it is something related to upstream (i.e. `libvips`), will keep an eye on the Windows XP discussion.

**Comment by haoxi911** [comment]
Some additional information:
