### ISSUE TITLE
Module not found on AWS node 14x

### ISSUE THREAD

**Issue by Lschulzes** [lovell/sharp#3503]
## Possible install-time or require-time problem
I have researched besides only the documentation, several other posts and tried installing with many different commands.
The runtime is node 14x at AWS lambda.
The error message says it cant find that module, but I went in the sharp dir in node_modules and it is there.

tried with the following commands:
npm install --arch=x64 --platform=linux --target=14x sharp
npm install --arch=x64 --platform=linux sharp
SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install --arch=x64 --platform=linux --libc=glibc sharp

```
"Error: ",
        "Something went wrong installing the \"sharp\" module",
        "",
        "Cannot find module '../build/Release/sharp-linux-x64.node'"
```

- [x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Is this a problem with filesystem permissions?
NO
If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?
Not applicable
If you are using npm v7 or later, does the user running `npm install` own the directory it is run in?
Yes
If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?
Yes
### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

npm verb cli [
npm verb cli   '/home/lschulzes/.nvm/versions/node/v16.13.0/bin/node',
npm verb cli   '/home/lschulzes/.nvm/versions/node/v16.13.0/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   '--foreground-scripts',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@8.1.0
npm info using node@v16.13.0
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/home/lschulzes/.nvm/versions/node/v16.13.0/lib/node_modules/npm/npmrc Completed in 2ms
npm timing config:load:builtin Completed in 2ms
npm timing config:load:cli Completed in 1ms
npm timing config:load:env Completed in 1ms
npm timing config:load:project Completed in 0ms
npm timing config:load:file:/home/lschulzes/.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:/home/lschulzes/.nvm/versions/node/v16.13.0/etc/npmrc Completed in 1ms
npm timing config:load:global Completed in 1ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 8ms
npm timing npm:load:configload Completed in 8ms
npm timing npm:load:setTitle Completed in 0ms
npm timing npm:load:setupLog Completed in 0ms
npm timing config:load:flatten Completed in 2ms
npm timing npm:load:cleanupLog Completed in 2ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 0ms
npm timing npm:load Completed in 15ms
npm timing arborist:ctor Completed in 0ms
npm timing idealTree:init Completed in 7ms
npm timing idealTree:userRequests Completed in 2ms
npm http fetch GET 200 https://registry.npmjs.org/sharp 11ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color 16ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tunnel-agent 15ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 18ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/node-addon-api 17ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/simple-get 17ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/prebuild-install 18ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tar-fs 18ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/semver 20ms (cache hit)
npm timing idealTree:#root Completed in 42ms
npm http fetch GET 200 https://registry.npmjs.org/color-string 27ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/minimist 26ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/github-from-package 27ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/pump 26ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color-convert 29ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/expand-template 28ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/decompress-response 27ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/napi-build-utils 28ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/once 27ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/chownr 26ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/mkdirp-classic 29ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/lru-cache 29ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/node-abi 31ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/simple-concat 30ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/safe-buffer 28ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/rc 32ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tar-stream 30ms (cache hit)
npm timing idealTree:node_modules/sharp Completed in 49ms
npm http fetch GET 200 https://registry.npmjs.org/color-name 3ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle 3ms (cache hit)
npm timing idealTree:node_modules/color Completed in 6ms
npm timing idealTree:node_modules/color-convert Completed in 1ms
npm timing idealTree:node_modules/color-name Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 4ms (cache hit)
npm timing idealTree:node_modules/color-string Completed in 5ms
npm timing idealTree:node_modules/detect-libc Completed in 0ms
npm timing idealTree:node_modules/node-addon-api Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/ini 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/end-of-stream 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/strip-json-comments 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/deep-extend 7ms (cache hit)
npm timing idealTree:node_modules/prebuild-install Completed in 14ms
npm timing idealTree:node_modules/expand-template Completed in 0ms
npm timing idealTree:node_modules/github-from-package Completed in 0ms
npm timing idealTree:node_modules/minimist Completed in 0ms
npm timing idealTree:node_modules/mkdirp-classic Completed in 0ms
npm timing idealTree:node_modules/napi-build-utils Completed in 0ms
npm timing idealTree:node_modules/node-abi Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/wrappy 3ms (cache hit)
npm timing idealTree:node_modules/pump Completed in 6ms
npm timing idealTree:node_modules/end-of-stream Completed in 0ms
npm timing idealTree:node_modules/once Completed in 0ms
npm timing idealTree:node_modules/rc Completed in 2ms
npm timing idealTree:node_modules/deep-extend Completed in 0ms
npm timing idealTree:node_modules/ini Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/yallist 2ms (cache hit)
npm timing idealTree:node_modules/semver Completed in 4ms
npm timing idealTree:node_modules/lru-cache Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/mimic-response 3ms (cache hit)
npm timing idealTree:node_modules/simple-get Completed in 4ms
npm timing idealTree:node_modules/decompress-response Completed in 1ms
npm timing idealTree:node_modules/mimic-response Completed in 0ms
npm timing idealTree:node_modules/simple-concat Completed in 0ms
npm timing idealTree:node_modules/simple-swizzle Completed in 1ms
npm timing idealTree:node_modules/is-arrayish Completed in 0ms
npm timing idealTree:node_modules/strip-json-comments Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/bl 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/fs-constants 9ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/inherits 9ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/readable-stream 8ms (cache hit)
npm timing idealTree:node_modules/tar-fs Completed in 14ms
npm timing idealTree:node_modules/chownr Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/string_decoder 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/util-deprecate 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/buffer 6ms (cache hit)
npm timing idealTree:node_modules/tar-stream Completed in 10ms
npm http fetch GET 200 https://registry.npmjs.org/base64-js 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/ieee754 4ms (cache hit)
npm timing idealTree:node_modules/bl Completed in 6ms
npm timing idealTree:node_modules/buffer Completed in 1ms
npm timing idealTree:node_modules/base64-js Completed in 0ms
npm timing idealTree:node_modules/fs-constants Completed in 0ms
npm timing idealTree:node_modules/ieee754 Completed in 0ms
npm timing idealTree:node_modules/inherits Completed in 0ms
npm timing idealTree:node_modules/readable-stream Completed in 1ms
npm timing idealTree:node_modules/string_decoder Completed in 1ms
npm timing idealTree:node_modules/safe-buffer Completed in 0ms
npm timing idealTree:node_modules/tunnel-agent Completed in 0ms
npm timing idealTree:node_modules/util-deprecate Completed in 0ms
npm timing idealTree:node_modules/wrappy Completed in 0ms
npm timing idealTree:node_modules/yallist Completed in 0ms
npm timing idealTree:buildDeps Completed in 174ms
npm timing idealTree:fixDepFlags Completed in 1ms
npm timing idealTree Completed in 185ms
npm timing reify:loadTrees Completed in 185ms
npm timing reify:diffTrees Completed in 1ms
npm timing reify:retireShallow Completed in 0ms
npm timing reify:createSparse Completed in 5ms
npm timing reify:loadBundles Completed in 0ms
npm timing reifyNode:node_modules/chownr Completed in 95ms
npm timing reifyNode:node_modules/strip-json-comments Completed in 94ms
npm timing reifyNode:node_modules/ini Completed in 95ms
npm timing reifyNode:node_modules/once Completed in 95ms
npm timing reifyNode:node_modules/wrappy Completed in 95ms
npm timing reifyNode:node_modules/end-of-stream Completed in 95ms
npm timing reifyNode:node_modules/simple-swizzle Completed in 96ms
npm timing reifyNode:node_modules/color-name Completed in 96ms
npm timing reifyNode:node_modules/color-string Completed in 96ms
npm timing reifyNode:node_modules/mkdirp-classic Completed in 96ms
npm timing reifyNode:node_modules/ieee754 Completed in 98ms
npm timing reifyNode:node_modules/inherits Completed in 98ms
npm timing reifyNode:node_modules/fs-constants Completed in 98ms
npm timing reifyNode:node_modules/mimic-response Completed in 98ms
npm timing reifyNode:node_modules/decompress-response Completed in 98ms
npm timing reifyNode:node_modules/lru-cache Completed in 98ms
npm timing reifyNode:node_modules/tunnel-agent Completed in 99ms
npm timing reifyNode:node_modules/util-deprecate Completed in 102ms
npm timing reifyNode:node_modules/string_decoder Completed in 102ms
npm timing reifyNode:node_modules/base64-js Completed in 102ms
npm timing reifyNode:node_modules/yallist Completed in 102ms
npm timing reifyNode:node_modules/expand-template Completed in 102ms
npm timing reifyNode:node_modules/simple-concat Completed in 103ms
npm timing reifyNode:node_modules/deep-extend Completed in 103ms
npm timing reifyNode:node_modules/pump Completed in 103ms
npm timing reifyNode:node_modules/napi-build-utils Completed in 103ms
npm timing reifyNode:node_modules/color Completed in 103ms
npm timing reifyNode:node_modules/safe-buffer Completed in 106ms
npm timing reifyNode:node_modules/is-arrayish Completed in 105ms
npm timing reifyNode:node_modules/color-convert Completed in 105ms
npm timing reifyNode:node_modules/detect-libc Completed in 105ms
npm timing reifyNode:node_modules/tar-stream Completed in 108ms
npm timing reifyNode:node_modules/simple-get Completed in 107ms
npm timing reifyNode:node_modules/buffer Completed in 109ms
npm timing reifyNode:node_modules/rc Completed in 109ms
npm timing reifyNode:node_modules/bl Completed in 111ms
npm timing reifyNode:node_modules/github-from-package Completed in 110ms
npm timing reifyNode:node_modules/prebuild-install Completed in 109ms
npm timing reifyNode:node_modules/node-abi Completed in 112ms
npm timing reifyNode:node_modules/minimist Completed in 116ms
npm timing reifyNode:node_modules/readable-stream Completed in 120ms
npm timing reifyNode:node_modules/node-addon-api Completed in 120ms
npm timing reifyNode:node_modules/tar-fs Completed in 120ms
npm timing reifyNode:node_modules/semver Completed in 122ms
npm timing reifyNode:node_modules/sharp Completed in 123ms
npm timing reify:unpack Completed in 127ms
npm timing reify:unretire Completed in 0ms
npm timing build:queue Completed in 2ms
npm timing build:link:node_modules/prebuild-install Completed in 2ms
npm timing build:link:node_modules/semver Completed in 1ms
npm timing build:link:node_modules/rc Completed in 1ms
npm timing build:link Completed in 2ms
npm info run sharp@0.31.3 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

> sharp@0.31.3 install
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Using cached /home/lschulzes/.npm/_libvips/libvips-8.13.3-linux-x64.tar.br
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 394ms
npm timing auditReport:getReport Completed in 395ms
npm timing auditReport:init Completed in 0ms
npm timing reify:audit Completed in 396ms
sharp: Integrity check passed for linux-x64reify:audit Completed in 396ms
prebuild-install info begin Prebuild-install version 7.1.1pleted in 396ms
prebuild-install info looking for local prebuild @ prebuilds/sharp-v0.31.3-napi-v7-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/lschulzes/.npm/_prebuilds/3edfda-sharp-v0.31.3-napi-v7-linux-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ /home/lschulzes/.npm/_prebuilds/3edfda-sharp-v0.31.3-napi-v7-linux-x64.tar.gz
prebuild-install info unpack resolved to /home/lschulzes/node_modules/sharp/build/Release/sharp-linux-x64.node
prebuild-install info install Successfully installed prebuilt binary!
npm info run sharp@0.31.3 install { code: 0, signal: null }
npm timing build:run:install:node_modules/sharp Completed in 635ms
npm timing build:run:install Completed in 636ms
npm timing build:deps Completed in 640ms
npm timing build Completed in 640ms
npm timing reify:build Completed in 640ms
npm timing reify:trash Completed in 0ms
npm timing reify:save Completed in 9ms
npm timing reify Completed in 981ms

added 45 packages, and audited 46 packages in 1s

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm timing command:install Completed in 985ms
npm verb exit 0
npm timing npm Completed in 1146ms
npm info ok 

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?
System:
    OS: Linux 5.15 Arch Linux
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 17.36 GB / 31.27 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.19 - ~/.local/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm

**Comment by lovell** [comment]
The installation looks OK to me. Are you using any kind of code bundler (e.g. webpack, esbuild) that might be breaking/changing import/require paths?

**Comment by Lschulzes** [comment]
Yes, I am using esbuld on the serverless.yml file with the following script:

```
  esbuild:
    packagerOptions:
      scripts:
        - rm -rf node_modules/sharp
        - npm install --arch=x64 --platform=linux sharp
```

**Comment by lovell** [comment]
Does your configuration also include the following?
```yaml
  esbuild:
    external:
      - sharp
 ```
Please see https://sharp.pixelplumbing.com/install#esbuild

**Comment by Lschulzes** [comment]
It worked, I didnt see, that, thank you!

**Comment by jaman99** [comment]
aws lambda need layers FOLDER NAME ( nodejs ) than zip it upload on lambda layers . if your folder name not nodejs its not running on aws lambda layers .
