### ISSUE TITLE
sharp is not working fine with custom libvips for > v0.31.1

### ISSUE THREAD

**Issue by Kikobeats** [lovell/sharp#3504]
## Possible install-time or require-time problem

- [x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

**Yes**

<details>

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.
</details>

### Is this a problem with filesystem permissions?

**No**

<details>

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7 or later, does the user running `npm install` own the directory it is run in?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

</details>

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

- https://pastebin.com/NPiUARSW (GitHub is saying the output is too long)

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (5) x64 unknown
    Memory: 6.63 GB / 7.76 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.12.1 - /usr/bin/node
    npm: 9.1.3 - /usr/bin/npm
  npmPackages:
    sharp: ^0.31.3 => 0.31.3
```

---

Hello, I'm using a sharp with a custom libvips installation, essentially for allowing as many image extensions as possible. 

The custom libvips is available as Docker image at https://github.com/Kikobeats/docker-vips.

Also, I have a project called https://github.com/microlinkhq/splashy for detects predominant colors in an image. 

The repo also has unit test to be ensured the detection is deterministic:
https://github.com/microlinkhq/splashy/blob/master/.github/workflows/pull_request.yml

I started detecting something changed in sharp > v0.31.1 because automatic pull request for upgrading the version failed:

- with sharp v0.31.2 failed: https://github.com/microlinkhq/splashy/pull/36
- with sharp v0.31.3 failed: https://github.com/microlinkhq/splashy/pull/39

Just sharp v0.31.1 is the latest known version that worked: https://github.com/microlinkhq/splashy/pull/30

For debugging purpose I tried to setup different flags in the custom vips compilation in order to find the issue, but it looks to me something internally at sharp changed in a way new versions can't simply work as expected

**Comment by lovell** [comment]
Please can you try changing this line https://github.com/Kikobeats/docker-vips/blob/master/Dockerfile#L9

```diff
- ARG LIB_VIPS_VERSION=8.13.2
+ ARG LIB_VIPS_VERSION=8.13.3
```

**Comment by Kikobeats** [comment]
It's working fine with libvips v8.13.3 

tests are green: https://github.com/microlinkhq/splashy/pull/40

so closing this 🙂
