### ISSUE TITLE
jxl() and toFormat("jxl") are not in TypeScript definition

### ISSUE THREAD

**Issue by oofdere** [lovell/sharp#3505]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Linux 6.1 Arch Linux
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 7.61 GB / 31.26 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 19.3.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  npmPackages:
    sharp: ^0.31.3 => 0.31.3 
```

### What are the steps to reproduce?

1. Install `sharp@latest` with global `libvips`, compiled with `libjxl` (tried with and without `@sharp/types` just in case as well)
2. `import sharp from "sharp"`
3. Try to convert a file to jxl format using TS. Conversion works, but IDE (VSCode in my case) does not see the types.

The following errors are produced by the compiler:
`sharp(input).jxl()`: `Property 'jxl' does not exist on type 'Sharp'.ts(2339)`
`sharp(input).toFormat("jxl")`: `Argument of type '"jxl"' is not assignable to parameter of type 'keyof FormatEnum | AvailableFormatInfo'.ts(2345)`

### What is the expected behaviour?

Types should be available for `jxl()` and `toFormat("jxl")

### Please provide sample image(s) that help explain this problem

![image](https://user-images.githubusercontent.com/43102807/209457452-0b6ababe-6d84-435d-b348-6afcd77a5819.png)

**Comment by oofdere** [comment]
Some more info:

sharp.format:
```js
  format: {
    jpeg: { id: 'jpeg', input: [Object], output: [Object] },
    png: { id: 'png', input: [Object], output: [Object] },
    webp: { id: 'webp', input: [Object], output: [Object] },
    tiff: { id: 'tiff', input: [Object], output: [Object] },
    magick: { id: 'magick', input: [Object], output: [Object] },
    openslide: { id: 'openslide', input: [Object], output: [Object] },
    dz: { id: 'dz', input: [Object], output: [Object] },
    ppm: { id: 'ppm', input: [Object], output: [Object] },
    fits: { id: 'fits', input: [Object], output: [Object] },
    gif: { id: 'gif', input: [Object], output: [Object] },
    svg: { id: 'svg', input: [Object], output: [Object] },
    heif: { id: 'heif', input: [Object], output: [Object] },
    pdf: { id: 'pdf', input: [Object], output: [Object] },
    vips: { id: 'vips', input: [Object], output: [Object] },
    jp2k: { id: 'jp2k', input: [Object], output: [Object] },
    jxl: { id: 'jxl', input: [Object], output: [Object] },
    raw: { id: 'raw', input: [Object], output: [Object] }
  }
```

sharp.versions:
```js
versions: { vips: '8.13.2' }
```

**Comment by lovell** [comment]
TypeScript definitions are currently managed by DefinitelyTyped. Perhaps you could submit a PR to https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/sharp to add this?

(There are plans to integrate these into a future version of sharp, please see #3369.)

**Comment by oofdere** [comment]
Thanks for pointing that out, I''d be happy to add the types there if no one else is already working on it!

**Comment by lovell** [comment]
Added downstream via https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63711
