### ISSUE TITLE
`tint()` results in wrong colors

### ISSUE THREAD

**Issue by higoka** [lovell/sharp#3506]
Im trying to overlay a color over an image. I know there is the `tint()` function but it results in wrong colors.

I have this base image i want to colorize with the hex color `#ffc680`.

![Base Image](https://i.ibb.co/qChwkVf/base.png)

This is my code: 
```js
await sharp('base.png')
  .tint({ r: 255, g: 198, b: 128 }) // #ffc680
  .toFile('result.png')
```

### Result:
![Bad Image](https://i.ibb.co/z797k2D/bad.png)

### Expected:
![Good Image](https://i.ibb.co/ZL52B6y/good.png)

As you can see the colors are lighter than the expected result. Does anybody have a solution to this?

I also tried using Jimp and can create a correct image using Jimp's color filter: https://github.com/oliver-moran/jimp/tree/master/packages/plugin-color#color

```js
const baseImage = await Jimp.read('base.png')
const mask = baseImage.clone().color([
  { apply: 'mix', params: [ 'ffc680', 100 ] }
])

baseImage.composite(mask, 0, 0, { mode: Jimp.BLEND_MULTIPLY })
await baseImage.writeAsync('result.png')
```

Hope someone can help me.

**Comment by lovell** [comment]
Hi, did you see #3338? It contains some discussion around ways to improve `tint`.

**Comment by lovell** [comment]
Let's track this at #3338
