### ISSUE TITLE
WebP input can ignore resize kernel

### ISSUE THREAD

**Issue by rnavarroz** [lovell/sharp#3516]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [ x] Running `npm install sharp` completes without error.
- [ x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [ x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```

  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 1.93 GB / 15.27 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.14.0 - ~/.config/nvm/versions/node/v16.14.0/bin/node
    npm: 8.3.1 - ~/.config/nvm/versions/node/v16.14.0/bin/npm
```

### What are the steps to reproduce?

Attempt to read in the webp image with transparency.

### What is the expected behaviour?

Changing the value of the kernel should show a different output of size in bytes but always is the same regardless of which kernel uses:
nearest, cubic, mitchell, lanczos2,lanczos3

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```
 const { data, info } = await sharp('transparency-linux.wep').resize(293, 300, {
    withoutEnlargement: true,
    fit: 'inside',
    kernel: 'mitchell'
  } )
    .toBuffer({ resolveWithObject: true });
  console.log(info);

{
  format: 'webp',
  width: 293,
  height: 300,
  channels: 4,
  premultiplied: false,
  size: 9420
}
```
```
 const { data, info } = await sharp('transparency-linux.wep').resize(293, 300, {
    withoutEnlargement: true,
    fit: 'inside',
    kernel: 'cubic'
  } )
    .toBuffer({ resolveWithObject: true });
  console.log(info);

{
  format: 'webp',
  width: 293,
  height: 300,
  channels: 4,
  premultiplied: false,
  size: 9420
}
```
### Please provide sample image(s) that help explain this problem

[transparency-linux.tar.gz](https://github.com/lovell/sharp/files/10355988/transparency-linux.tar.gz)

**Comment by lovell** [comment]
Hi, did you see the `fastShrinkOnLoad` option of `resize()`? Setting it to `false` will prevent the use of libwebp's scaling and instead use the kernel.

(I've added a brief note about this to the docs via commit https://github.com/lovell/sharp/commit/e8273580af1b24580db34343afedbd39516f419f )

**Comment by rnavarroz** [comment]
I just did and try it but there is not different on the sizes:
```
  const { data, info } = await sharp('transparency-linux.webp')
  .resize(293, 300, {
    withoutEnlargement: true,
    fit: 'inside',
    kernel: 'mitchell',
    fastShrinkOnLoad: false
  })
  .toBuffer({ resolveWithObject: true });
  console.log(info);
```
result
```
{
  format: 'webp',
  width: 293,
  height: 300,
  channels: 4,
  premultiplied: false,
  size: 9420
}
```
