### ISSUE TITLE
Await sharp() seems to have strange behavior 

### ISSUE THREAD

**Issue by manfredipist** [lovell/sharp#3520]
## Possible bug
Callback of .toFile() method seems to be called without checking if picture has been successfully stored on hdd.

### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

  System:
    OS: macOS 13.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 87.87 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: 2022.12.26.00 - /usr/local/bin/watchman
  npmPackages:
    sharp: ^0.31.3 => 0.31.3 

### What are the steps to reproduce?

Compress a buffer image into webp format and the store it on disk using await to wait for completion.

### What is the expected behaviour?

I would expect to be able to download the stored image as soon as callback from toFile is called, thus await sharp() resolved but this doesn't seem to work. When sharpInstance (in the code below) gets resolved, the image is still being saved on filesystem and I can't return the url on a http request to let my client download the just updated picture. 
I've checked this theory by replacing `await new Promise((resolve) => setTimeout(resolve, 1000));` with the following one 
`
while(! filePath.exists()){
   console.log("file does not exists yet");
}
`

and the loop gets executed . I expect this not to happen. Currently I've resolved forcing my server to wait 1 more sec before returning the request.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

`module.exports = {
  storePictureInWebP: async function (binaryImage) {
    try {
      const fileName =
        Crypto.randomUUID({ disableEntropyCache: true }) + ".webp";
      const filePath = "public/assets/uploads/" + fileName;
      const sharpInstance = await sharp(binaryImage)
        .webp({
          nearLossless: true,
          quality: 70,
        })
        .toFile(filePath, function (err) {
          if (err) {
            throw new Error(err);
          }
        });
      await new Promise((resolve) => setTimeout(resolve, 1000));
      return sharpInstance.options.fileOut.slice(7);
    } catch (err) {
      loggerService.printError(
        path.basename(__filename),
        "storePictureInWebP",
        err.message
      );
      throw new Error(
        "Errore durante la memorizzazione della foto da te caricata"
      );
    }
  }
};`

**Comment by lovell** [comment]
Are you writing to the SSD or is this an external/network drive that might have some kind of synchronisation or possible write delay? Is there any other process "watching" the output, perhaps some kind of build tool, that might be modifying or moving it (I ask as I note `watchman` is mentioned)?

To be able to help further, I'll need a complete, standalone repo, without any other dependencies, that allows someone else to reproduce.

**Comment by manfredipist** [comment]
I'm writing on a SSD and I'm not watching the process in my production environment.
I've made a repo to let you test the issue. Inside the "test" folder you can find a demo of what happens in my use case.
https://github.com/manfredipist/sharp-issue-3520

**Comment by lovell** [comment]
Thanks. Because you're passing a callback function to `toFile()` it won't return a Promise, so there is nothing to `await`.

https://sharp.pixelplumbing.com/api-output#tofile

> A `Promise` is returned when `callback` is not provided.

It looks like you're already wrapping the call in a try/catch block, so remove the callback and it should all work. If possible it's usually best to try to avoid mixing callback and Promise style logic in the same function to help avoid this kind of problem.

**Comment by manfredipist** [comment]
Thanks you so much, problem solved!
