### ISSUE TITLE
Text appears as square blocks in image

### ISSUE THREAD

**Issue by chaloNitin** [lovell/sharp#3523]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 325.30 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 11.15.0 - ~/.nvm/versions/node/v11.15.0/bin/node
    npm: 6.7.0 - ~/.nvm/versions/node/v11.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
```

### What are the steps to reproduce?

This absolutely works fine in local environment, but as soon as I deploy it to server it start printing texts as square blocks.
From what I can understand this seems to be a version mismatch issue.

Went through a couple of issues #3485 #3479 and checked the fonts in my server. There exists a number of fonts but still facing this issue. This is an ubuntu machine

<img width="463" alt="server_ss" src="https://user-images.githubusercontent.com/119299305/211484689-11ba9fa8-8799-4cd6-9963-253a52716305.png">

@lovell please suggest what to do next here.

### What is the expected behaviour?

Text should've printed instead of boxes

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```
const addCaption = async (image, text, width = 165, height = 165) => {
    let svgText = `
    <svg width="${width}" height="${height}">
        <style>
        .title { fill: #001; font-size: 16px; font-weight: bold;}
        </style>
        <text x="50%" y="8%" text-anchor="middle" class="title">${text}</text>
    `
    const caption = Buffer.from(svgText);

    const sharpImage = await sharp(image)
    await sharpImage.composite([{ input: caption, gravity: 'center' }])
    return sharpImage
}
```

### Please provide sample image(s) that help explain this problem

![1234](https://user-images.githubusercontent.com/119299305/211473543-d86cfa55-ace0-487a-99fd-af35413176fc.png)

**Comment by lovell** [comment]
This looks like a font discovery problem - please see https://sharp.pixelplumbing.com/install#fonts

**Comment by chaloNitin** [comment]
I already went through this link @lovell, not able to figure out what exactly needs to be done

**Comment by lovell** [comment]
Did you try setting the `FC_DEBUG` environment variable to the various values as documented at https://www.freedesktop.org/software/fontconfig/fontconfig-user.html (and linked to by https://sharp.pixelplumbing.com/install#fonts ), which will help debug font discovery problems?

**Comment by chaloNitin** [comment]
My `fonts.conf` file was missing
I solved this issue by doing the following:

1. `sudo apt install fontconfig`
2. `export FONTCONFIG_PATH=/etc/fonts`
3. `export FONTCONFIG_FILE=/etc/fonts/fonts.conf`
4. Restart server

I think this solution is not the most optimised one as my deployment servers keep changing as per requirements, so probably will look for some other dependency or add the above commands in docker file.

**Comment by sergiuturus** [comment]
I have added fontconfig via the Dockerfile the following way

# Install fontconfig
RUN apk add --no-cache fontconfig

# Set FONTCONFIG_PATH and FONTCONFIG_FILE environment variables
ENV FONTCONFIG_PATH=/etc/fonts
ENV FONTCONFIG_FILE=/etc/fonts/fonts.conf

But it seems I can't get rid of the square blocks. Any clues on what am I doing wrong?  I can see the fonts.conf file in /etc/fonts

**Comment by GusMartins499** [comment]
Any updates? Same issue here
