### ISSUE TITLE
SVG: use of CSS Images Module Level 3 image-rendering attribute

### ISSUE THREAD

**Issue by 0xSharp** [lovell/sharp#3524]
### What are you trying to achieve?

I am trying to convert an SVG to PNG, utilizing nearest neighbor, you'll notice the converted PNG has one crisp image/layer and the rest is blurry

### When you searched for similar issues, what did you find that might be related?

I found multiple threads and attempted everything, from disabling fastShrink to messing with density.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

const convert = () => {
     sharp('./test.svg').resize(1106, 1230, { kernel: sharp.kernel.nearest, fastShrinkOnLoad: false}).png().toFile("./sample.png");
      console.log('Done!')
};

convert()

### Please provide sample image(s) that help explain this question

![test](https://user-images.githubusercontent.com/39307372/211672924-96234b07-6743-4056-ba4a-992a35a0c082.svg)
![sample](https://user-images.githubusercontent.com/39307372/211672950-f972a599-4616-4ab1-975f-21ade6c3f249.png)

**Comment by lovell** [comment]
Hi, this SVG is really three bitmap images wearing a vector jacket. It relies on `style="image-rendering:pixelated"`, which is part of the (draft) CSS Images Module Level 3 spec and not yet implemented in librsvg.

https://gitlab.gnome.org/GNOME/librsvg/-/blob/main/src/properties.rs#L449

Please can you request this as a new SVG2/CSS3 feature at https://gitlab.gnome.org/GNOME/librsvg/-/issues

**Comment by 0xSharp** [comment]
> Hi, this SVG is really three bitmap images wearing a vector jacket. It relies on `style="image-rendering:pixelated"`, which is part of the (draft) CSS Images Module Level 3 spec and not yet implemented in librsvg.
> 
> https://gitlab.gnome.org/GNOME/librsvg/-/blob/main/src/properties.rs#L449
> 
> Please can you request this as a new SVG2/CSS3 feature at https://gitlab.gnome.org/GNOME/librsvg/-/issues

Hi Lovell, thank you for the reply! I'll definitely request this, going forward is there any way you can suggest working around this?

**Comment by lovell** [comment]
sharp 0.32.5 provides librsvg 2.56.92 that includes upstream implementation https://gitlab.gnome.org/GNOME/librsvg/-/merge_requests/850
