### ISSUE TITLE
Loop through files in directory and process each one

### ISSUE THREAD

**Issue by JoshuaAPhillips** [lovell/sharp#3527]
Hi all,

This may be rather a basic question but I was wondering if there was any way to loop through images in a folder and iteratively process each one? I've been trying to create a loop using Node's fs module. The loop itself works fine - it can grab filenames with console.log for instance, but after that I'm a bit stuck. 

For instance, when I try this very basic example, it throws an error saying that the input file is missing: 

```
const fs = require('fs');
const sharp = require('sharp');

const inputDir = "./input";
const outputDir = "./output"

fs.readdirSync(inputDir).forEach(file => {
    sharp(file)
        .png(file + '.png')
        .toFile(outputDir)
    
})
```

Ultimately I'd like to use Sharp to convert some 300 or so large PNGs to DZI tiles, so finding a way to do this iteratively would be ideal.

Thanks in advance,
Josh

**Comment by lovell** [comment]
Perhaps take a look at the logic in https://github.com/lovell/avif-cli for inspiration. It uses `glob` to build a list of files based on wildcards then maps each file to a sharp pipeline (in this case, converting to AVIF).

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
