### ISSUE TITLE
How to make the value of a transparent pixel (0,0,0,0)

### ISSUE THREAD

**Issue by misty000** [lovell/sharp#3531]
### What are you trying to achieve?

I load the png image
```
function dump(data) {
    const n = data.length / 4
    for (let i = 0; i < n; i++) {
        const r = data[i * 4]
        const g = data[i * 4 + 1]
        const b = data[i * 4 + 2]
        const a = data[i * 4 + 3]
        console.log(i, '--', r, g, b, a)
    }
}

const s3 = await sharp('./assets/textures/metalness.png')
const d3 = await s3.raw().toBuffer()
console.log('d3')
dump(d3)
```
The value of transparent pixel is (255,255,255,0)
My expected value is (0,0,0,0)
What should I do?

### Please provide sample image(s) that help explain this question

![metalness](https://user-images.githubusercontent.com/3632834/212820106-54a12e53-1075-4054-a21f-67c653fd8432.png)

**Comment by lovell** [comment]
I think these look like the correct pixel values for this input image. An alpha value of 0 is fully transparent and means none of the RGB values will be considered, so it doesn't really matter what they are. For this image it just happens that the original author used 255, 255, 255; sharp is not altering these in any way.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
