### ISSUE TITLE
How to use both sharp and Canvas on windows?

### ISSUE THREAD

**Issue by Leyksnal** [lovell/sharp#3532]
## Question about an existing feature
Running `sharp` with `canvas`

### What are you trying to achieve?
I have an existing project that has `sharp` and `canvas` running together, but now I'm trying to run the codebase on a windows machine and its not working.

The error keeps coming up when I try to run the code
```
node:internal/modules/cjs/loader:1203
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified procedure could not be found.
\\?\C:\api\node_modules\canvas\build\Release\canvas.node
```

**Comment by lovell** [comment]
Please see https://sharp.pixelplumbing.com/install#canvas-and-windows
