### ISSUE TITLE
Error: Processed image is too large for the JPEG format

### ISSUE THREAD

**Issue by 82318179** [lovell/sharp#3533]
let sharp_baseOpt = {
        width: 1920,
        height: 86041,
        channels: 4,
        background: {
          r: 255,
          g: 255,
          b: 255,
          alpha: 1,
        },
      };
await sharp({ create: baseOpt }).jpeg().toFile(filepath_test);

then error like 
Error: Processed image is too large for the JPEG format

but await sharp({ create: baseOpt }).png().toFile(filepath_test);

the result is ok ,why?

**Comment by lovell** [comment]
#3362
