### ISSUE TITLE
Feature: extrude image

### ISSUE THREAD

**Issue by miltoncandelero** [lovell/sharp#3534]
### What are you trying to achieve?

currently `extend` uses a single color for all pixels, `extrude` would pick the closest pixel color

### What would you expect the API to look like?
the same as the `extend` api but without color
``` sharp.extrude(10)```
and
```
  sharp.extrude({
    top: 10,
    bottom: 20,
    left: 10,
    right: 10,
  })
```
### What alternatives have you considered?

extending with transparent and then going pixel by pixel replacing the transparent pixel. This defeats the idea of sharp.

### Please provide sample image(s) that help explain this feature

![image](https://user-images.githubusercontent.com/15253010/212920067-c4abfd71-16ad-4a85-81c8-dfc93a696335.png)

**Comment by lovell** [comment]
There's an existing `extend` option of `vips_embed` (as used by sharp's `extend()` method) that we could expose to support the scenario provided.

https://www.libvips.org/API/current/libvips-conversion.html#vips-embed

This would require `VIPS_EXTEND_COPY` (as `copy`), and I think we should also support at least `mirror` and `repeat`. A caller would need to set either the proposed `extend` option _or_ the existing `background` option, but not both.

```js
// PROPOSED API, NOT YET AVAILABLE
sharp.extend({
  ...
  extend: 'copy' | 'mirror' | 'repeat'
})
// PROPOSED API, NOT YET AVAILABLE
```

**Comment by tquetano-netflix** [comment]
I am actually trying to accomplish this exact feat right now, and its quickly becoming a blocker for me to replace our old system that uses ImageMagick with sharp, so you can count on my vote.

Is there even a way to accomplish this in the current API?
