### ISSUE TITLE
Quick Help: Sharp resize function is not working related with the width and height

### ISSUE THREAD

**Issue by luckybirdu** [lovell/sharp#3537]
Hello Sharp community,

I have a bug with a Sharp resize function.
The original image is:
![IMG_7661](https://user-images.githubusercontent.com/109105668/213953163-b1315de0-0432-45ba-86d5-60b5c719294f.jpg)
The resized image is:
![BD4ECEE7-662B-4870-914C-0E428A0AE57E](https://user-images.githubusercontent.com/109105668/213953193-e10cbb0d-cff3-437b-9896-18aaac490d33.jpeg)

I used Sharp resize function like below:

```
sharp(img.buffer)
      .resize({ width: 2500, height: 3333 })
      .withMetadata()
      .toBuffer();
```

But the result image's width is 3333 and height is 2500. The image and height were exchanged when resize the image.

Please help me quickly.

**Comment by lovell** [comment]
The code and image provided here works as-expected for me, but GitHub can remove/alter EXIF metadata when uploading images.

Any kind of mismatched dimensions/rotation are usually the result of EXIF orientation, so please check the input image. You can auto-orient based on EXIF data by adding `rotate()` to your pipeline.

https://sharp.pixelplumbing.com/api-operation#rotate

**Comment by luckybirdu** [comment]
Thank you lovell,

That works for me. I was impressed by using this module.
