### ISSUE TITLE
Is it possible to achieve Photoshop's Advanced Blending By Channel?

### ISSUE THREAD

**Issue by grimAgent** [lovell/sharp#3539]
### What are you trying to achieve?

Hi! I couldn't find a forum or other community to make questions, I hope this is the right place.
I'm trying to achieve the following effect by playing with `extractChannel` and blend options, but not successful at the moment. 
Here is how it is done on Photoshop

Source Image:
<img width="624" alt="Screen Shot 2023-01-25 at 4 00 58 PM" src="https://user-images.githubusercontent.com/90475821/214658170-ed4fc9f6-d940-4bcd-a9d2-8ddba607dcf7.png">

Duplicate layer, move it up 20 pixels and use this blending options (notice only the B is selected):
<img width="297" alt="Screen Shot 2023-01-25 at 4 01 27 PM" src="https://user-images.githubusercontent.com/90475821/214658296-4f3e133e-584d-4a52-bb74-5f09a93e59f3.png">
<img width="299" alt="Screen Shot 2023-01-25 at 4 02 15 PM" src="https://user-images.githubusercontent.com/90475821/214658474-bc57a495-49c3-4f78-a5b2-3b677b74a92d.png">

Output image:
<img width="754" alt="Screen Shot 2023-01-25 at 4 02 43 PM" src="https://user-images.githubusercontent.com/90475821/214658561-0188e891-d9c4-4e43-a77e-485ae2664420.png">

### When you searched for similar issues, what did you find that might be related?

I got somewhat close (not really, but as close as I could get) with this:
```
        const currentSharp = await sharp({
            create:{
                width: width,
                height: height,
                channels: 3,
                background: '#EAD057'
            }
        }).composite(currentOverlayOptions).toFormat('png').toBuffer()

        const blueChannel = await sharp(currentSharp).extractChannel('blue').toFormat('png').toBuffer()

        await sharp({
            create:{
                width: width,
                height: height,
                channels: 3,
                background: '#EAD057'
            }
        }).composite([
            { input: currentSharp },
            { input: blueChannel, left: 0, top: -20, blend: 'screen' }
        ]).toFile('blue.png')
```
<img width="239" alt="Screen Shot 2023-01-25 at 4 06 33 PM" src="https://user-images.githubusercontent.com/90475821/214659598-45aa1c24-8bb1-498d-a465-5f00b8fed2fc.png">

Thank you!

**Comment by grimAgent** [comment]
After a LOT of trial and error, I got the same result that I was looking for, but using a lot of steps:

```
        const currentSharp = await sharp(Buffer.from(currentSvgString)).resize(width, height).toBuffer()

        const blueChannel = await sharp({
            create:{
                width: width,
                height: height,
                channels: 3,
                background: '#0000FF'
            }
        }).composite([
            { input: currentSharp, blend:'darken' },
        ]).png().toBuffer()
        
        const yellowChannel = await sharp({
            create:{
                width: width,
                height: height,
                channels: 3,
                background: '#FFFF00'
            }
        }).composite([
            { input: currentSharp, blend:'lighten' },
        ]).png().toBuffer()

        const finalBlueChannel = await sharp(currentSharp).composite([
            { input: yellowChannel, blend:'darken', top: -14, left: 0 },
            { input: blueChannel, blend:'lighten', top: -14, left: 0 },
        ]).toFile('blue.png')
```

It would be nice to be able to do this with fewer steps, as it sounds like this will require a lot of processing, so if anyone has any other ideas, would love to hear them!

Thank you!

**Comment by lovell** [comment]
Glad you worked it out, this looks like a good approach for the scenario described, thanks for reporting back with a solution.
