### ISSUE TITLE
macOS Ventura can report high memory usage, might relate to its new allocator, probably nothing to worry about

### ISSUE THREAD

**Issue by MarianoFacundoArch** [lovell/sharp#3540]
When doing image operations with sharp, any king, like just asking the metadata, the process ram usage starts going up and up and never frees up.
It only happens in mac os, we have the same piece of software running on ubuntu and it doesn't have this problem.

It's a brand new installed MacOS with M2, and libvips was installed using homebrew.

**Comment by lovell** [comment]
>  libvips was installed using homebrew.

Do you see the same behaviour using the prebuilt binaries, or only with using with a globally-installed vips?

**Comment by MarianoFacundoArch** [comment]
Sorry for the delay, I was doing tests. It still happens. 
As I said it's curious how this happens only on Mac OS, as in ubuntu in doesn't happen at all, same piece of code.

**Comment by lovell** [comment]
Please can you answer the following questions, which were in the issue template but were ignored/deleted:

- Are you using the latest version of sharp?

- What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

- Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

- Please provide sample image(s) that help explain this problem

**Comment by lovell** [comment]
@MarianoFacundoArch Were you able to make any progress with this?

Without any further information, my best guess is that this relates to the new memory allocator in macOS Ventura. It now zeroes freed memory, which will have a performance impact, so may grab as much (virtual) memory as it can. I suspect it will also be less likely to return freed memory from a process back to the OS. Please make sure the tooling you're using to assess memory usage is aware of these changes.

https://developer.apple.com/documentation/macos-release-notes/macos-13-release-notes

**Comment by MarianoFacundoArch** [comment]
Hi Lovell, I've been working very tough on this, that is the conclusion I was coming to. What is curious is that I'm running Ventura 13.2, and in that release note it is not mentioned that problem with the allocator.
Is there anything that comes up to your mind? I'll keep you in touch once I confirm my findings and get a solution
Thanks.

**Comment by lovell** [comment]
It's less likely to be a problem with the allocator itself, more the tooling that is reporting "usage" and how that data is interpreted. For example, "Never frees up" is not the same as "Frees up but the OS doesn't need it back so keep hold for now as you might need some more".

**Comment by MarianoFacundoArch** [comment]
I thought it was a fragmentation issue at first. 
what is so curious is that when you go to activity monitor you don’t see such usage. The high usage is reported by tools such as top or grip and in activity monitor once you click in the process. 
it is so so curious. 
do we think apple has a bug here or that it is the way to work ?

**Comment by MarianoFacundoArch** [comment]
Yes! It's the memory allocator of apple!

**Comment by lovell** [comment]
Thanks, I'll close as there's probably not a lot we can do here.
