### ISSUE TITLE
JPEG input resize performance Issue introduced in v0.30.1

### ISSUE THREAD

**Issue by jian-ong** [lovell/sharp#3542]
🍐 @keeganstreet

## Overview 
When updating Sharp to the latest version from `v0.29.3`, we noticed a marked increase in transaction time when processing images. We have investigated and narrowed it down to it being introduced in `v0.30.1`. We ran some isolated tests where we processed 1000 images and recorded the duration it took. See [here](https://github.com/jian-ong/sharp-regression-test) for the repo used. 

Sharp `0.29.3` : 13,328 ms
Sharp `0.30.1` : 21,489 ms

Do you have any idea what could have caused this?

**Comment by lovell** [comment]
Thank you for the clear question and steps to reproduce.

The [changelog for v0.30.1](https://sharp.pixelplumbing.com/changelog#v0301---9th-february-2022) includes https://github.com/lovell/sharp/issues/3066, which is relevant here.

There was a potential quality issue for JPEG input in versions < 0.31.1 where over reliance on shrink-on-load could result in unwanted pixel shifts and moire patterns when resizing. Version 0.31.0 tried to improve this as part of the work to support multi-page (animated) resizing, but this made things worse for the specific case where one dimension was exactly halved. We agreed for version 0.31.1 that the simplest solution was to use (almost) the same approach that libvips uses for its `thumbnail` operation, which improves quality at a performance cost.

Things you can do now to improve performance:

- The forthcoming version 0.32.0 will switch to using sequential read by default, which is faster when resizing without rotation, and you can enable this in current versions via `sharp(input, { sequentialRead: true })...`
- If you're running Linux then please ensure a suitable [memory allocator](https://sharp.pixelplumbing.com/install#linux-memory-allocator) is used (anything but the stock glibc allocator).
- Does this question relate to code running at REA? Are you using still using AWS Graviton 2 CPUs? If so, see https://mastodon.social/@lovell/109546531190912845 for why upgrading to Graviton 3 is a very good idea.

**Comment by jian-ong** [comment]
Thanks for the explanation and suggestions @lovell ! We tried out the steps you outlined and have achieved some improvements by using `sequentialRead`. We _are_ working on code running at REA (how did you know? 😆) and are still on a 3rd gen Intel Xeon instance because we found that Graviton 2 was not performing as well as the Intel. Graviton 3 is still not available in the aws regions our system runs on, but definitely something that we could look into in the future when it becomes available. Thanks again for your assistance! :)

**Comment by grantbeattie** [comment]
Once we've upgraded to 0.31 and implemented some of these changes, we'll benchmark sharp/libvips on c6i vs Graviton 2 cores again.

I haven't been following libvips closely for a while, but I presume there have been some significant performance improvements on arm64 over the last little while.

Hopefully the 7g instances types will become available in more regions soon, though, as that would be a huge win.

**Comment by lovell** [comment]
Thanks for the updates, good to hear `sequentialRead` helped. Upgrading should reduce the likelihood of moire patterns appearing when resizing photos of things like tiled roofs and patterned wallpaper.

In terms of ARM64 improvements, liborc recently added support for aarch64 so the prebuilt binaries provided by sharp will now use NEON intrinsics for resizing. Performance results are now published for ARM64 as part of the docs at https://sharp.pixelplumbing.com/performance

I'll close, but please feel free to re-open with more details if further assistance is required.
