### ISSUE TITLE
Generate a single color silhouette with transparent background

### ISSUE THREAD

**Issue by X-Y** [lovell/sharp#3543]
### What are you trying to achieve?
I'd like to create silhouettes of existing images. They all have a white background, and grey scale portraits. The result should have a single colored foreground, and transparent background. 

### When you searched for similar issues, what did you find that might be related?
The problem is probably more to do with image processing than the library itself, but I can hardly find anything in the right direction so it would be great if you can give some help!

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question
First, I apply threshold. The image is basically what I would like to achieve, but with white background instead of transparent.
```
const base = await sharp(path)
				.resize(100)
				.ensureAlpha()
				.threshold()
				.toBuffer();
```
My idea is to extract one channel, convert it to alpha channel for the base image. But I'm really lost as of what to do
```
const mask = await sharp(base)
				.extractChannel('red')
				.toColorspace('b-w')
				.toBuffer();
const result = sharp(base)
				.removeAlpha()
				.joinChannel(mask)
				.toFile(...)
```

### Please provide sample image(s) that help explain this question

This is the result of 1st step:
![sample](https://user-images.githubusercontent.com/1042130/215510746-3be32574-4a37-42d9-9fd4-e0ffb87bacad.png)
This is what I'd like to achieve, with the white background converted to transparent, and foreground color replaced(which is not important here)
![sample2](https://user-images.githubusercontent.com/1042130/215511554-defe7bfd-25dc-4711-8e1b-678be1f07d4c.png)

**Comment by X-Y** [comment]
Ok I figured it out myself. Really good to have GIMP by the side so I can "debug"!

```
    const base = await file
        .resize(100)
        .negate()
        .png()
        .toBuffer();

    const fg = await sharp(base)
        .threshold()
        .toBuffer();

    const fgMask = await sharp(fg)
        .extractChannel('red')
        .toBuffer();

    const fgNoAlpha = await sharp(fg)
        .removeAlpha()
        .toBuffer()
    
    const result = await sharp(fgNoAlpha)
        .joinChannel(fgMask)
        .toFile('...')
```

Have to break apart the last 2 steps or the alpha channel becomes solid. How come is that?

**Comment by lovell** [comment]
This approach looks suitable, glad you worked it out. The use of `removeAlpha` takes priority over the use of `joinChannel`, so you are correct to split these into two pipelines.
