### ISSUE TITLE
Enhancement: Support ArrayBuffer as input

### ISSUE THREAD

**Issue by kapouer** [lovell/sharp#3545]
This doesn't work (using sharp 0.31.3)
```
const res = await fetch(imageUrl);
const buf = await res.arrayBuffer();
await sharp(buf);
```
instead one has to
```
await sharp(Buffer.from(buf));
```

**Comment by lovell** [comment]
Bonjour, I think the general idea (best practice?) with an `ArrayBuffer` is that it must be "cast" to a typed array before us. In the example you've provided, casting to a Node.js `Buffer` is approximately equivalent to casting to a `Uint8Array`.

My understanding is that the cast creates a view that will use the same underlying memory location (potentially a slice of it), and does not involve a copy.

However as you suggest, for convenience, we could assume an implicit cast of an `ArrayBuffer` to a `Buffer`. Happy to accept a PR if you're able.

**Comment by kapouer** [comment]
You're tempting me to add support for fetch's Response / Blob as well :)

**Comment by kapouer** [comment]
> You're tempting me to add support for fetch's Response / Blob as well :)

blob is somewhat useless, and Response would require an async call to get the buffer.
Or would require supporting `input(readableStream)`. It's another issue then.

**Comment by lovell** [comment]
v0.32.0 now available, thank you for the PR.
