### ISSUE TITLE
Tracker erro TRK0002 is back

### ISSUE THREAD

**Issue by PeterNierop** [lovell/sharp#355]
Not sure what the cause is. 
Running Windows 10  14251.rs1_release.160124-1509

Error is 
TRACKER : error TRK0002: Failed to execute command: "E:\vs\VC\bin\amd64\CL.exe @C:\Users\Peter\AppData\Local\Temp\tmp75
707f27af564a76891ebda8f5935380.rsp". The handle is invalid. [E:\img\node_modules\sharp\build\sharp.vcxproj]

Would it be a solution to add this to the sharp.vcxproj
<PropertyGroup><TrackFileAccess>false</ TrackFileAccess></ PropertyGroup>

**Comment by lovell** [comment]
Hello, the `sharp.vcxproj` file is created by `node-gyp`.

It looks like others have run into the same problem within the last month or so:

https://github.com/nodejs/node-gyp/issues/870
https://github.com/nodejs/node-gyp/issues/875

...so it's probably worth you subscribing to those to see if anyone is able to help.

**Comment by PeterNierop** [comment]
Aaaaand the issue is over again.  Windows build 14257.rs1_release. Installation works again. Tried both fresh install and a rebuild.
Pfeeeeuw

**Comment by lovell** [comment]
Thanks for the update, glad to hear it's working again. I guess I still shouldn't click the "Upgrade now" button on any Windows 7/8 machines yet.
