### ISSUE TITLE
How to add Add border/outline to a transparent (png) image?

### ISSUE THREAD

**Issue by hellpain2004** [lovell/sharp#3550]
Hi there,

I'd need to add a solid border around nontransparent part of png image.

Does anyone have any clue of how I could do that?

Thanks in advance!!

**Comment by lovell** [comment]
Did you see the [extend](https://sharp.pixelplumbing.com/api-resize#extend) operation?

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
