### ISSUE TITLE
How can I tell libvips, via the sharp API, what filename I want it to use in the tmp directory for any given file?  

### ISSUE THREAD

**Issue by rfornea** [lovell/sharp#3552]
I have a use case where I need to be able to have libvips store things in `/tmp` in a deterministic filename per image.  Is there a way via the sharp API that I can do this?  I know that libvips in theory supports this, but we're using sharp rather than directly using libvips.  

The reason for this is because when we get the `no space left on device` error, files seem to get orphaned in `/tmp`.  But I can't just clear `/tmp` because other processes might be using it.  But if I could name the files deterministically then I'd know specifically which things I can safely clear.  

This is in an AWS edge lambda where I only have 512 MB of tmp storage, but other instances of the lambda might also be using tmp.  That's why I cannot just delete everything in tmp.

**Comment by lovell** [comment]
>  I know that libvips in theory supports this,

Are you referring to the `TMPDIR` and/or `VIPS_DISC_THRESHOLD` environment variables? They should "just work", the same as they already when running `vips` at the command line.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
