### ISSUE TITLE
Sharp extract function results to high CPU usage

### ISSUE THREAD

**Issue by normancapule** [lovell/sharp#3554]
## Question about an existing feature

I'm working on a small tool that extracts multiple parts of an image into their own buffers. I'm using sharp's extract function to accomplish this.

Given an image, and multiple coordinates, the tool should extract each subsection of the image into multiple buffers.

With the current implementation (see script in repo below), executing the script at least once results to high CPU usage - 90%+. For context I'm using a machine with 16 cores and 32GB of RAM. I'm wondering if you peeps have any advice on how to reduce that? 

I also noticed that setting `sequentialRead` to `true` improved the time it took for the script to finish. From 1.4s to ~700 ms. 

Before | After
-- | -- 
![image](https://user-images.githubusercontent.com/780659/217860416-45eb0163-2143-4625-8b3e-90654381e29f.png) | ![image](https://user-images.githubusercontent.com/780659/217860469-d1657a9d-38fa-4e2f-a6d1-eb8996a010d4.png)

If anyone has any ideas on why this is happening, Pls do share. I want to understand 😀 

### What are you trying to achieve?

Reduce CPU usage when executing multiple sharp - extract from a single image. Also understand what I'm doing wrong.

### When you searched for similar issues, what did you find that might be related?

I think this issue is a bit similar to mine https://github.com/lovell/sharp/issues/2108.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

Here you go https://github.com/normancapule/test-sharp-cpu-spike/blob/main/index.ts

### Please provide sample image(s) that help explain this question

Here is the CPU usage after running the script once.

![WindowsTerminal_5cVC6MV6tw](https://user-images.githubusercontent.com/780659/217859538-2ff59293-b548-4976-b878-172f25d6bbff.png)

**Comment by lovell** [comment]
Thank you for the clear question and complete code to reproduce.

I ran this locally via `callgrind` and saw that most of the CPU time is spent in JPEG decode.
```
9,391,506,033 (36.54%)  ???:0x0000000000026f30 [/usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2]
3,615,724,968 (14.07%)  ???:0x00000000000373d0 [/usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2]
2,454,915,840 ( 9.55%)  ???:0x0000000000034030 [/usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2]
1,735,221,165 ( 6.75%)  ???:jpeg_fill_bit_buffer [/usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2]
1,567,322,987 ( 6.10%)  ./string/../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:__memset_avx2_unaligned_erms [/usr/lib/x86_64-linux-gnu/libc.so.6]
1,306,842,192 ( 5.09%)  ???:0x0000000000037290 [/usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2]
  876,380,803 ( 3.41%)  ???:0x0000000000020d40 [/usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2]
```
Rather than decoding the JPEG input for every output, perhaps use an intermediate raw data buffer.

With the following change:
```diff
diff --git a/index.ts b/index.ts
index df3f453..2f23063 100644
--- a/index.ts
+++ b/index.ts
@@ -124,13 +124,14 @@ const products: Product[] = [
   { x1: 1961, x2: 2105, y1: 2021, y2: 2147 },
 ];
 
-const cropBaseImage = async (imageBuffer: Buffer, product: Product) => {
-  return await sharp(imageBuffer, { sequentialRead: true  }).extract({
+const cropBaseImage = async (imageBuffer: Buffer, info: sharp.OutputInfo, product: Product) => {
+  const { width, height, channels } = info;
+  return await sharp(imageBuffer, { raw: { width, height, channels } }).extract({
     width: product.x2 - product.x1 + 1,
     height: product.y2 - product.y1 + 1,
     left: product.x1,
     top: product.y1,
-  }).toBuffer();
+  }).jpeg().toBuffer();
 };
 
 const sequential = async (promises: Promise<any>[]) => {
@@ -143,9 +144,9 @@ const sequential = async (promises: Promise<any>[]) => {
 };
 const runTest = async () => {
   const start = Date.now().valueOf();
-  const imageBuffer = await sharp("./sample.jpeg").rotate().toBuffer();
+  const { data, info } = await sharp("./sample.jpeg").rotate().raw().toBuffer({ resolveWithObject: true });
   const promises = products.map(async (product) => {
-    return cropBaseImage(imageBuffer, product);
+    return cropBaseImage(data, info, product);
   });
   const result = await sequential(promises);
```
I see a much lower CPU time, perhaps 5x faster, so much so that the ICC profile handling and auto-orientation of the first call outside the loop shows up.
```
768,144,384 (21.52%)  ???:0x000000000003e650 [/usr/lib/x86_64-linux-gnu/liblcms2.so.2.0.12]
409,195,776 (11.46%)  libvips/build/../libvips/conversion/rot.c:vips_rot90_gen [/usr/local/lib/x86_64-linux-gnu/libvips.so.42.17.0]
307,016,020 ( 8.60%)  ???:0x0000000000026f30 [/usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2]
274,337,280 ( 7.68%)  ???:0x000000000001dfb0 [/usr/lib/x86_64-linux-gnu/liblcms2.so.2.0.12]
```

**Comment by normancapule** [comment]
Hey @lovell thanks for this! Can confirm that performance has improved by using this solution. 

If you don't mind, can you help me understand about the shared data buffer? How does sharp make use of this?

Another Q - if there are parallel processes - do they use the same data buffer?

Last Q (promise! 😓) - Can you pls explain what does `sequentialRead: true` do? I noticed that the script performance improved using this - before using the raw data buffer.

Thank you again! 🙏

**Comment by lovell** [comment]
The bottleneck for this task was JPEG decoding of the input. For 116 output images, the input JPEG had to be (partially, depending on internal caching) decoded up to 116 times, which is approximately _O(n)_. Decoding this once and storing as raw pixel data in memory then extracting small, already-decompressed regions is closer to _O(1)_.

Using the diff I provided, the same intermediate `imageBuffer` input will be used for all outputs.

Sequential read will automagically become the default behaviour, where possible, in the forthcoming v0.32.0. It assumes input will be read top-to-bottom, which your use case matches, hence a small speed improvement.
