### ISSUE TITLE
What does `quality` map to in PNG output?

### ISSUE THREAD

**Issue by tquetano-netflix** [lovell/sharp#3555]
### What are you trying to achieve?

Understanding of `quality` usage in `png` output, and how it compares to usage with other file formats and potentially other implementations such as ImageMagick.

### When you searched for similar issues, what did you find that might be related?

I found several issues discussing the quality for `jpeg`, and some for `webp` ([example from `libvips` itself](https://github.com/libvips/libvips/issues/571)), but I was curious specifically about `quality` for `png`. I can't seem to find documentation explaining how `quality` relates to `png` output (compared to, say, `compressionLevel`), and searching the issues the only thing I could find was [that it was an advanced feature that you may not need](https://github.com/lovell/sharp/issues/2068#issuecomment-581546803) :sweat_smile:. I imagine it relates to compression level, so I'm curious how that applies, and if it differs from [ImageMagick's definition](https://imagemagick.org/script/command-line-options.php):

> For the MNG and PNG image formats, the quality value sets the zlib compression level (quality / 10) and filter-type (quality % 10). The default PNG "quality" is 75, which means compression level 7 with adaptive PNG filtering, unless the image has a color map, in which case it means compression level 7 with no PNG filtering.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```js
// These all produce different file sizes

// Smallest
const quality = await sharp("dice.png").png({ quality: 75 }).toFile("test-sharp-quality.png");
// Larger
const compressed = await sharp("dice.png").png({ adaptiveFiltering: true, compressionLevel: 7 }).toFile("test-sharp-compression.png");
// Largest
const compressedColorMap = await sharp("dice.png").png({ adaptiveFiltering: false, compressionLevel: 7 }).toFile("test-sharp-compression-color-map.png");
```

### Please provide sample image(s) that help explain this question

![PNG_transparency_demonstration_1](https://user-images.githubusercontent.com/44408771/217939181-c6bfef9b-9beb-40bd-bba7-f4a359e4ad05.png)

**Comment by lovell** [comment]
The `quality` parameter is used to control colour selection as part of the quantisation process, which generates a suitable palette from a full colour image. When you pass a `quality` value to `png()`, lossy palette-based output will be auto-selected.

Internally, this is the `maximum` passed to [liq_set_quality](https://pngquant.org/lib/#liq_set_quality).

**Comment by tquetano-netflix** [comment]
Perfect! Thank you so much, this is exactly what I was looking for. :)
