### ISSUE TITLE
esbuild & lambda: Cannot find module ../build/Release/sharp-linux-x64.node

### ISSUE THREAD

**Issue by simon-tannai** [lovell/sharp#3558]
Hello there 👋

I'm running Sharp on AWS Lambda with Node.js 18.
Everything was working fine with this install script: 
```shell
SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install --arch=x64 --platform=linux --libc=glibc --cache .yarn
```

Since few days, I have migrated my projet to a monorepository managed by Nx, built Node.js apps with esbuild and using this install script:
```shell
yarn --mutex file:/tmp/.yarn-mutex

rm -rf ./node_module/sharp

SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install --arch=x64 --platform=linux --libc=glibc sharp
```
 
Now, I have this error when running on AWS Lambda:
```shell
Cannot find module '../build/Release/sharp-linux-x64.node'
```

I have defined Sharp as external:
```json
"external": ["sharp", "fluent-ffmpeg", "@ffmpeg-installer/ffmpeg", "@ffprobe-installer/ffprobe"],
```

Did I missed something ?

**Comment by lovell** [comment]
There are quite a few moving parts here.

* Does the `node_modules/sharp/build/Release/sharp-linux-x64.node` file exist in the zip file deployed to AWS?
* What is the output of running `SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install --arch=x64 --platform=linux --libc=glibc --foreground-scripts sharp`?

**Comment by lovell** [comment]
@simon-tannai Were you able to make any progress with this?

**Comment by simon-tannai** [comment]
@lovell Finally it was an issue from Nx, not from Sharp ✌️

**Comment by iamhosseindhv** [comment]
@simon-tannai Could you explain what was the issue with NX please. I'm in the same boat (esbuild + lambda + migration to NX monorepo)

**Comment by BioCarmen** [comment]
Facing the same issue. @simon-tannai @iamhosseindhv any insight you can share?

**Comment by iamhosseindhv** [comment]
@BioCarmen I wanted to bundle my nodejs api (lambda) using esbuild, but the only dependency that couldn't get bundled was `sharp`. I ended up replacing sharp with a similar library, namely `image-size`. 

But if you're stuck with sharp, make sure you follow their installation instructions: https://sharp.pixelplumbing.com/install#aws-lambda

I believe this is NOT an NX issue, it's just about `node_modules/sharp/build` directory to exist with some binary files which is automatically downloaded by `sharp` during `postinstall`.
