### ISSUE TITLE
Error handling of Stream-based output

### ISSUE THREAD

**Issue by simplenotezy** [lovell/sharp#3560]
### What are you trying to achieve?

We have observed some pods to be restarting because sharp is trying to parse invalid XML.

### When you searched for similar feature requests, what did you find that might be related?

https://github.com/lovell/sharp/issues/2049

### What alternatives have you considered?

We tried wrapping it around in a try/catch but that did not work

**Comment by lovell** [comment]
> Prevent crash when invalid XML is parsed

> We tried wrapping it around in a try/catch but that did not work

Please can you provide complete, standalone code and sample input that allows someone else to reproduce.

**Comment by simplenotezy** [comment]
Sure, here's an example of invalid SVG:

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="500" height="300" viewBox="0 0 500 300">
    <g id="Group_1" data-name="Group 1" transform="translate(-775 -400)">
      <g id="dk" transform="translate(775 400)"><3
        <rect id="Rectangle_1" data-name="Rectangle 1" width="500" height="300" fill="#c60c30"/>
        <rect id="Rectangle_2" data-name="Rectangle 2" width="40" height="300" transform="translate(167.273)" fill="#fff"/>
        <rect id="Rectangle_3" data-name="Rectangle 3" width="500" height="40" transform="translate(0 130)" fill="#fff"/>
      </g>
    </g>
  </svg>

**Comment by lovell** [comment]
Thanks, I see the following error, which looks like the expected behaviour given this input.

> Input buffer has corrupt header: glib: XML parse error: Error domain 1 code 68 on line 3 column 45 of data: StartTag: invalid element name

Please can you provide complete, standalone code with appropriate error handling that allows someone else to reproduce the *crash*.

**Comment by simplenotezy** [comment]
```ts
try {
  const generatedPNG = await sharp(Buffer.from(`
    <svg xmlns="http://www.w3.org/2000/svg" width="500" height="300" viewBox="0 0 500 300">
      <g id="Group_1" data-name="Group 1" transform="translate(-775 -400)">
        <g id="dk" transform="translate(775 400)"><3
          <rect id="Rectangle_1" data-name="Rectangle 1" width="500" height="300" fill="#c60c30"/>
          <rect id="Rectangle_2" data-name="Rectangle 2" width="40" height="300" transform="translate(167.273)" fill="#fff"/>
          <rect id="Rectangle_3" data-name="Rectangle 3" width="500" height="40" transform="translate(0 130)" fill="#fff"/>
        </g>
      </g>
    </svg>
  `))
  .png({
    progressive: false,
    quality: 100,
    compressionLevel: 9,
  })
  .resize(630);

  return generatedPNG.pipe(res);
} catch (error) {
  // is not catched
}

**Comment by lovell** [comment]
This is unrelated to sharp.

Node.js Streams operate asynchronously and the use of try/catch here won't help as nothing is "awaiting" the pipeline.

I usually recommend `stream.pipeline()` for this.

```js
const { pipeline } = require('node:stream/promises');
```
```diff
-  return generatedPNG.pipe(res);
+  return await pipeline(generatedPNG, res);
```

https://nodejs.org/api/stream.html#streampipelinesource-transforms-destination-options

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by simplenotezy** [comment]
Ah, I see - thanks a lot for your reply @lovell - missed your reply, but I'll test it out
