### ISSUE TITLE
I can't install sharp on windows 10

### ISSUE THREAD

**Issue by victor-alf** [lovell/sharp#3561]
node version  v18.14.1

error D:\wgtwo.com\website\node_modules\sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
Arguments:
Directory: D:\wgtwo.com\website\node_modules\sharp
Output:
sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.12.2/libvips-8.12.2-win32-x64.tar.br
sharp: Installation error: aborted

**Comment by lovell** [comment]
Hello, the installation issue template appears to have been ignored and/or deleted. If you still require help, please open a new installation issue and provide answers to all of the questions. These are written in such as way as to allow you to help yourself, as well as allow others to help you.

https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md

In particular, ensure you're using the latest version of sharp and watch out for networking errors during installation.

I note this was cross-posted at https://github.com/working-group-two/wgtwo.com/issues/252 - in this example, please ensure `@docusaurus/plugin-ideal-image` is up-to-date.
