### ISSUE TITLE
Using sharp with electron and webpack

### ISSUE THREAD

**Issue by uSkizzik** [lovell/sharp#3562]
## Possible install-time or require-time problem
Hi so I'm trying to use sharp in my electron app. I've bundled my electron code with webpack and I'm using the node-loader module to bundle the binary file. My issue is that when I start up my packaged app (packaged with electron-builder but I doubt that matters), I get this:
```prolog
(node:44660) UnhandledPromiseRejectionWarning: Error: 
Something went wrong installing the "sharp" module

node-loader:
Error: The specified module could not be found.
C:\Users\rstoq\AppData\Local\Temp\8f2d9263-ad9d-49b5-ad74-a8f7ea721de9.tmp.node

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current win32-x64 runtime: "npm install --platform=win32 --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
- Ensure the version of sharp aligns with the sharp package: "npm ls sharp"
```

- [x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Is this a problem with filesystem permissions?

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7 or later, does the user running `npm install` own the directory it is run in?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>
npm verb cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
npm info using npm@8.19.2
npm info using node@v18.12.1
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 3ms
npm timing config:load:builtin Completed in 3ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:D:\Documents\asd\.npmrc Completed in 0ms
npm timing config:load:project Completed in 2ms
npm timing config:load:file:C:\Users\rstoq\.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:C:\Users\rstoq\AppData\Roaming\npm\etc\npmrc Completed in 1ms
npm timing config:load:global Completed in 1ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 11ms
npm timing npm:load:configload Completed in 11ms
npm timing npm:load:mkdirpcache Completed in 1ms
npm timing npm:load:mkdirplogs Completed in 0ms
npm verb title npm install sharp
npm verb argv "install" "--loglevel" "verbose" "--foreground-scripts" "sharp"
npm timing npm:load:setTitle Completed in 1ms
npm timing config:load:flatten Completed in 2ms
npm timing npm:load:display Completed in 13ms
npm verb logfile logs-max:10 dir:C:\Users\rstoq\AppData\Local\npm-cache\_logs
npm verb logfile C:\Users\rstoq\AppData\Local\npm-cache\_logs\2023-02-19T16_20_40_599Z-debug-0.log
npm timing npm:load:logFile Completed in 6ms
npm timing npm:load:timers Completed in 1ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load Completed in 34ms
npm timing arborist:ctor Completed in 1ms
npm timing arborist:ctor Completed in 0ms
npm timing idealTree:init Completed in 8ms
npm timing idealTree:userRequests Completed in 2ms
npm http fetch GET 200 https://registry.npmjs.org/sharp 137ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color 76ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/semver 87ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/tunnel-agent 91ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/prebuild-install 101ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/node-addon-api 104ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/tar-fs 106ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/simple-get 139ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 842ms (cache revalidated)
npm timing idealTree:#root Completed in 992ms
npm http fetch GET 200 https://registry.npmjs.org/color-convert 71ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-string 71ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/minimist 70ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/napi-build-utils 72ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/github-from-package 80ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/expand-template 84ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/rc 94ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/decompress-response 95ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/once 100ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/mkdirp-classic 103ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/simple-concat 111ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/node-abi 115ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/mkdirp-classic 120ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/tar-stream 116ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/pump 124ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/safe-buffer 119ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/chownr 122ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/lru-cache 131ms (cache updated)
npm timing idealTree:node_modules/sharp Completed in 147ms
npm http fetch GET 200 https://registry.npmjs.org/color-name 42ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-name 47ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle 51ms (cache revalidated)
npm timing idealTree:node_modules/color Completed in 55ms
npm timing idealTree:node_modules/color-convert Completed in 1ms
npm timing idealTree:node_modules/color-name Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 48ms (cache revalidated)
npm timing idealTree:node_modules/color-string Completed in 50ms
npm timing idealTree:node_modules/detect-libc Completed in 0ms
npm timing idealTree:node_modules/node-addon-api Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/end-of-stream 46ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/strip-json-comments 46ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/ini 54ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/deep-extend 66ms (cache revalidated)
npm timing idealTree:node_modules/prebuild-install Completed in 76ms
npm timing idealTree:node_modules/expand-template Completed in 0ms
npm timing idealTree:node_modules/github-from-package Completed in 0ms
npm timing idealTree:node_modules/minimist Completed in 0ms
npm timing idealTree:node_modules/mkdirp-classic Completed in 0ms
npm timing idealTree:node_modules/napi-build-utils Completed in 0ms
npm timing idealTree:node_modules/node-abi Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/wrappy 48ms (cache revalidated)
npm timing idealTree:node_modules/pump Completed in 51ms
npm timing idealTree:node_modules/end-of-stream Completed in 0ms
npm timing idealTree:node_modules/once Completed in 1ms
npm timing idealTree:node_modules/rc Completed in 3ms
npm timing idealTree:node_modules/deep-extend Completed in 0ms
npm timing idealTree:node_modules/ini Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/yallist 53ms (cache revalidated)
npm timing idealTree:node_modules/semver Completed in 55ms
npm timing idealTree:node_modules/lru-cache Completed in 1ms
npm http fetch GET 200 https://registry.npmjs.org/mimic-response 49ms (cache revalidated)
npm timing idealTree:node_modules/simple-get Completed in 52ms
npm timing idealTree:node_modules/decompress-response Completed in 1ms
npm timing idealTree:node_modules/mimic-response Completed in 0ms
npm timing idealTree:node_modules/simple-concat Completed in 0ms
npm timing idealTree:node_modules/simple-swizzle Completed in 1ms
npm timing idealTree:node_modules/is-arrayish Completed in 0ms
npm timing idealTree:node_modules/strip-json-comments Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/readable-stream 39ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/fs-constants 47ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/bl 49ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/inherits 56ms (cache revalidated)
npm timing idealTree:node_modules/tar-fs Completed in 60ms
npm timing idealTree:node_modules/chownr Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/string_decoder 42ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/util-deprecate 46ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/buffer 63ms (cache revalidated)
npm timing idealTree:node_modules/tar-stream Completed in 70ms
npm http fetch GET 200 https://registry.npmjs.org/base64-js 39ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/ieee754 43ms (cache revalidated)
npm timing idealTree:node_modules/bl Completed in 47ms
npm timing idealTree:node_modules/buffer Completed in 3ms
npm timing idealTree:node_modules/base64-js Completed in 0ms
npm timing idealTree:node_modules/fs-constants Completed in 0ms
npm timing idealTree:node_modules/ieee754 Completed in 0ms
npm timing idealTree:node_modules/inherits Completed in 0ms
npm timing idealTree:node_modules/readable-stream Completed in 3ms
npm timing idealTree:node_modules/string_decoder Completed in 1ms
npm timing idealTree:node_modules/safe-buffer Completed in 0ms
npm timing idealTree:node_modules/tunnel-agent Completed in 0ms
npm timing idealTree:node_modules/util-deprecate Completed in 0ms
npm timing idealTree:node_modules/wrappy Completed in 0ms
npm timing idealTree:node_modules/yallist Completed in 0ms
npm timing idealTree:buildDeps Completed in 1692ms
npm timing idealTree:fixDepFlags Completed in 1ms
npm timing idealTree Completed in 1707ms
npm timing reify:loadTrees Completed in 1707ms
npm timing reify:diffTrees Completed in 2ms
npm timing reify:retireShallow Completed in 1ms
npm timing reify:createSparse Completed in 19ms
npm timing reify:loadBundles Completed in 0ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 409ms
npm timing auditReport:getReport Completed in 414ms
npm timing auditReport:init Completed in 0ms
npm timing reify:audit Completed in 415ms
npm timing reifyNode:node_modules/chownr Completed in 423ms
npm timing reifyNode:node_modules/ini Completed in 432ms
npm timing reifyNode:node_modules/end-of-stream Completed in 433ms
npm timing reifyNode:node_modules/strip-json-comments Completed in 433ms
npm timing reifyNode:node_modules/mkdirp-classic Completed in 433ms
npm timing reifyNode:node_modules/wrappy Completed in 440ms
npm timing reifyNode:node_modules/once Completed in 440ms
npm timing reifyNode:node_modules/color-name Completed in 440ms
npm timing reifyNode:node_modules/simple-swizzle Completed in 440ms
npm timing reifyNode:node_modules/color-string Completed in 447ms
npm timing reifyNode:node_modules/lru-cache Completed in 454ms
npm timing reifyNode:node_modules/tunnel-agent Completed in 473ms
npm timing reifyNode:node_modules/string_decoder Completed in 476ms
npm timing reifyNode:node_modules/color Completed in 475ms
npm timing reifyNode:node_modules/fs-constants Completed in 497ms
npm timing reifyNode:node_modules/ieee754 Completed in 498ms
npm timing reifyNode:node_modules/inherits Completed in 502ms
npm timing reifyNode:node_modules/mimic-response Completed in 501ms
npm timing reifyNode:node_modules/decompress-response Completed in 504ms
npm timing reifyNode:node_modules/yallist Completed in 524ms
npm timing reifyNode:node_modules/napi-build-utils Completed in 531ms
npm timing reifyNode:node_modules/safe-buffer Completed in 535ms
npm timing reifyNode:node_modules/util-deprecate Completed in 536ms
npm timing reifyNode:node_modules/is-arrayish Completed in 535ms
npm timing reifyNode:node_modules/base64-js Completed in 568ms
npm timing reifyNode:node_modules/expand-template Completed in 568ms
npm timing reifyNode:node_modules/simple-concat Completed in 569ms
npm timing reifyNode:node_modules/deep-extend Completed in 594ms
npm timing reifyNode:node_modules/detect-libc Completed in 594ms
npm timing reifyNode:node_modules/simple-get Completed in 633ms
npm timing reifyNode:node_modules/pump Completed in 634ms
npm timing reifyNode:node_modules/buffer Completed in 636ms
npm timing reifyNode:node_modules/color-convert Completed in 668ms
npm timing reifyNode:node_modules/tar-stream Completed in 723ms
npm timing reifyNode:node_modules/bl Completed in 811ms
npm timing reifyNode:node_modules/github-from-package Completed in 840ms
npm timing reifyNode:node_modules/rc Completed in 894ms
npm timing reifyNode:node_modules/node-abi Completed in 978ms
npm timing reifyNode:node_modules/prebuild-install Completed in 1004ms
npm timing reifyNode:node_modules/tar-fs Completed in 1130ms
npm timing reifyNode:node_modules/node-addon-api Completed in 1135ms
npm timing reifyNode:node_modules/minimist Completed in 1136ms
npm timing reifyNode:node_modules/readable-stream Completed in 1149ms
npm timing reifyNode:node_modules/semver Completed in 1185ms
npm timing reifyNode:node_modules/sharp Completed in 1303ms
npm timing reify:unpack Completed in 1307ms
npm timing reify:unretire Completed in 0ms
npm timing build:queue Completed in 4ms
npm timing build:link:node_modules/prebuild-install Completed in 7ms
npm timing build:link:node_modules/rc Completed in 6ms
npm timing build:link:node_modules/semver Completed in 7ms
npm timing build:link Completed in 8ms
npm info run sharp@0.31.3 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

> sharp@0.31.3 install
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Using cached C:\Users\rstoq\AppData\Local\npm-cache\_libvips\libvips-8.13.3-win32-x64.tar.brlibvips & 
sharp: Integrity check passed for win32-x64n sharp@0.31.3 install node_modules/sharp (node install/libvips & 
sharp: Creating D:\Documents\asd\node_modules\sharp\build\Release node_modules/sharp (node install/libvips & 
sharp: Copying DLLs from D:\Documents\asd\node_modules\sharp\vendor\8.13.3\win32-x64\lib to D:\Documents\asd\node_modules\sharp\build\Release
prebuild-install info begin Prebuild-install version 7.1.1install node_modules/sharp (node install/libvips & 
prebuild-install info looking for local prebuild @ prebuilds\sharp-v0.31.3-napi-v7-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\rstoq\AppData\Local\npm-cache\_prebuilds\a376d2-sharp-v0.31.3-napi-v7-win32-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ C:\Users\rstoq\AppData\Local\npm-cache\_prebuilds\a376d2-sharp-v0.31.3-napi-v7-win32-x64.tar.gz
prebuild-install info unpack resolved to D:\Documents\asd\node_modules\sharp\build\Release\sharp-win32-x64.node
prebuild-install info install Successfully installed prebuilt binary!
npm info run sharp@0.31.3 install { code: 0, signal: null }
npm timing build:run:install:node_modules/sharp Completed in 1794ms
npm timing build:run:install Completed in 1794ms
npm timing build:deps Completed in 1808ms
npm timing build Completed in 1808ms
npm timing reify:build Completed in 1809ms
npm timing reify:trash Completed in 0ms
npm timing reify:save Completed in 11ms
npm timing reify Completed in 4879ms

added 45 packages, and audited 46 packages in 5s

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm timing command:install Completed in 4886ms
npm verb exit 0
npm timing npm Completed in 5052ms
npm info ok
</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?
```
  System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5700X 8-Core Processor
    Memory: 3.98 GB / 15.93 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.3.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: ^0.31.3 => 0.31.3
```

**Comment by lovell** [comment]
Did you see https://sharp.pixelplumbing.com/install#webpack ? Use `externals`, please don't use `node-loader`.

**Comment by uSkizzik** [comment]
Okay but how else do I include sharp in my packaged app? Do I just copy over its node_modules folder or?

**Comment by uSkizzik** [comment]
@lovell

**Comment by lovell** [comment]
There's a lot of missing context here. What have you tried? What did or didn't work? What configuration are you using? Are you using asar? Did you see https://github.com/lovell/sharp/issues/678#issuecomment-275956028 ?

If you're still having problems, perhaps create a minimal repo with dependencies and configuration that allows someone else to reproduce the problem.

**Comment by uSkizzik** [comment]
> There's a lot of missing context here. What have you tried? What did or didn't work? What configuration are you using? Are you using asar? Did you see [#678 (comment)](https://github.com/lovell/sharp/issues/678#issuecomment-275956028) ?

Yes I'm using asar but the comment linked seems to be referring to mac-targeted builds. I'm targeting Windows.  
As far as I understand, including sharp in the externals object would mean it doesn't get bundled and thus sharp is not getting included in the build. I'm asking if I should be copying over the node_modules folder which contains sharp when building or if there's some other solution.

**Comment by lovell** [comment]
>  thus sharp is not getting included in the build

My understanding of `electron-builder` is that any `dependencies` in `node_modules` will be packaged (but note that `devDependencies` will not). You'll probably need to ask the `electron-builder` maintainers if this is not the case.

**Comment by uSkizzik** [comment]
I remember I actually disabled dependencies from being included as I bundle my code which means they're included either way.

**Comment by uSkizzik** [comment]
Okay so I ended up resolving this by adding sharp as an external module and then installing it in an empty folder and then copying over the node_modules from that into my external resources. This way only sharp and its dependencies are included outside of the bundle file rather than all dependencies.

**Comment by TiddoLangerak** [comment]
Solutions for electron forge + asar:


Option 1: Add the sharp/{build,vendr} folders to the asar.unpack config. In your `forge.config`:
```
const config = {
  packagerConfig: {
    asar: {
      unpack: `**/node_modules/sharp/{build,vendor}/**/*`,
    },
  },
}
```

Option 2: Use the [`auto-unpack-natives`](https://www.electronforge.io/config/plugins/auto-unpack-natives) plugin, combined with manually adding the `vendor` folder (which isn't picked up by the plugin):

```
const config = {
  packagerConfig: {
    asar: {
      unpack: `**/node_modules/sharp/vendor/**/*`,
    },
  },
  plugins: [
    {
      name: "@electron-forge/plugin-auto-unpack-natives",
      config: {},
    },
  ]
}
```

**Comment by lovell** [comment]
@TiddoLangerak Please upgrade to the latest version of sharp, where the need to think about things like "vendor" directories has gone away.

Please see https://sharp.pixelplumbing.com/install#electron for the latest recommended Electron configuration.

**Comment by lichspace** [comment]
my solution: https://github.com/lichspace/lichspace.github.io/blob/master/docs/electron-sharp.md

**Comment by lovell** [comment]
@ryankashi Please remove `node-loader` - see my comment above https://github.com/lovell/sharp/issues/3562#issuecomment-1436041097

**Comment by ryankashi** [comment]
> @ryankashi Please remove `node-loader` - see my comment above https://github.com/lovell/sharp/issues/3562#issuecomment-1436041097

Apologies. I forgot to mention that also I tried removing both node-loader as well as the vercel-asset-relocater-loader, and I was still encountering the same error, using the same asar configuration as stated above.

This resulted in me getting the same error as before

**Comment by ryankashi** [comment]
@lovell Any updates on the following?

It seems that with the migration away from the original ```node_modules/sharp``` directory format, the packaging of sharp in electron apps remains broken without the fix proposed by @lichspace.

Removal of ```node-loader``` from config files did not address the issue.

Thanks!

**Comment by lovell** [comment]
@ryankashi Many people successfully use the latest sharp with electron and most reported problems are due to webpack plugins. If you still require help, please open a new issue and provide details of a separate, complete, minimal repo that allows someone else to reproduce.

**Comment by ryankashi** [comment]
Please see the following minimum example:
https://github.com/ryankashi/sharp-electron-issue

Built using Windows 10, 64 bit with Webpack, TypeScript, and React. Using Electron-forge, following their package:
https://www.electronforge.io/guides/framework-integration/react-with-typescript

Following webpack and electron build instructions provided at:
https://sharp.pixelplumbing.com/install

ts-loader: disabled

The solution at:
https://github.com/lichspace/lichspace.github.io/blob/master/docs/electron-sharp.md
works as intended
