### ISSUE TITLE
Sharp 0.31.x  fails to install on WSL

### ISSUE THREAD

**Issue by a-tonchev** [lovell/sharp#3563]
While trying to install latest sharp on WSL I get this error:

![image](https://user-images.githubusercontent.com/54528540/220080444-834ae255-e275-49a5-a2d1-04e8c9909157.png)

With sharp 0.30.7 there are no problems.

**Comment by lovell** [comment]
> Using cached /home/bux/.npm/_libvips/libvips-8.13.3-linux-x64.tar.br
> Installation error: Decompression failed

Please delete the `/home/bux/.npm/_libvips/libvips-8.13.3-linux-x64.tar.br` file, which looks like it is invalid/corrupt, and try again.

(Please, please paste text rather than use screenshots when opening GitHub issues.)

**Comment by bilibilikanpei** [comment]
牛逼，一开始没看到“Decompression”。
对于中国用户我来说，新电脑上的国内npm镜像设置错误了，导致下载了错误的libvips-8.14.5-win32-x64.tar.br，所以无法解压，并且被缓存到了npm-cache。
需要更正镜像为
```
sharp_binary_host "https://cdn.npmmirror.com/binaries/sharp"
sharp_libvips_binary_host "https://cdn.npmmirror.com/binaries/sharp-libvips"
```
再手动清空npm-cache/_libvips文件夹

**Comment by lovell** [comment]
For anyone else running into this, please upgrade sharp to the latest version as (from v0.33.0) all binaries are now served from the npm registry and installed via your choice of package manager.
