### ISSUE TITLE
vips__file_open_read: unable to open file "./sRGB.icm" for reading

### ISSUE THREAD

**Issue by julin69** [lovell/sharp#3566]
My system is windows 11, and my sharp version is 0.28.3, and i want to output the image file with icc profile and colorspace is srgb,so my code is below:
`sharp(buffer, {density: dpi || 300})
	.toColourspace('srgb')
	.withMetadata({icc: './sRGB.icm'})
	.jpeg({quality: 100,})
	.toFile(output, (error, info) => {
		if (error) {
			return callback({index}, error);
		}
	})`

but the error is:
vips__file_open_read: unable to open file "./sRGB.icm" for reading

sRGB.icm is exist and the path is right

I dont know how to solve this problem, Waiting for your replay!

**Comment by lovell** [comment]
When using relative paths, these will be relative to the process working directory, which may not be the same as the directory your source code is in.

**Comment by julin69** [comment]
Thanks for your reply
