### ISSUE TITLE
output image with custom icc profile

### ISSUE THREAD

**Issue by julin69** [lovell/sharp#3570]
Hello, my system is Windows 11 and my sharp version is 0.25.4, now i want to output image with custom sRGB icc profile,I have tried several methdos, but all not work, my code is below:
<pre>
sharp(buffer, {density: dpi || 300, profile: './sRGB.icm'})
	.toColourspace('srgb')
	.withMetadata({profile: './sRGB.icm'})
	.extract({left: left, top: 0, width: extractWidth, height: extractHeight})  
	.resize({
		width: finalOutputWidth,
		height: finalOutputHeight,
		fit: sharp.fit.fill,
	})
	.jpeg({quality: 20,})
	.toFile(thumb_output, (error, info) => {
		if (error) {
			return callback({index}, error);
		}
	});
</pre>
Now I want to know how to add my custom ICC profile to the image with sharp@0.25.4.
Waiting for your reply!

**Comment by lovell** [comment]
For custom *output* profiles, please upgrade to at least v0.26.0 (but ideally to the latest version, as I cannot provide support for older versions).

https://sharp.pixelplumbing.com/changelog#v0260---25th-august-2020

> Add support to withMetadata for custom ICC profile

Custom *input* profiles are a future possible enhancement, please subscribe to https://github.com/lovell/sharp/issues/1324

**Comment by julin69** [comment]
Hello, thanks you your reply, but for some reason, i can not upgrade sharp, is there other way to add sRGB profile?

**Comment by lovell** [comment]
Please upgrade.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
