### ISSUE TITLE
PDF support for sharp with lambda functions

### ISSUE THREAD

**Issue by eyaab** [lovell/sharp#3571]
I have a pdf buffer and I want to use Sharp in order to generate a pdf thumbnail. 
For that
- I'm using the latest version of sharp: 0.31.3
- I downloaded the binaries of libvips: libglib-2.0-0.dll, libgobject-2.0-0.dll, libvips-42.dll, libvips-cpp-42.dll, vips.exe, vipsedit.exe, vipsheader.exe, vipsthumbnail.exe.
- I'm using sharp like this: const imageBuffer = await sharp(pdfBuffer, { density: 150, pages: 1, format: "png", binPath: "../bin/bin" }).toBuffer(); (ps: "../bin/bin" is where I saved the binaries)

But, I still get the error in CloudWatch of "Input buffer contains unsupported image format"
Any help would be appreciated

**Comment by lovell** [comment]
Hi, as you've probably seen, the prebuilt binaries provided by sharp do not support PDF.

You'll need to compile your own libvips with support for libpoppler. In addition, getting custom shared libraries deployed to the AWS Lambda runtime is not straightforward. You might want to look at using a layer, and there's an example of how this could work at https://github.com/zoellner/sharp-heic-lambda-layer (in this case adding libde265 as a dependency).

From the info you've provided about what what has been tried so far, it looks like you're attempting to use Windows binaries and shared libraries on the Linux-based AWS Lambda, which won't work. In addition the `binPath` option doesn't exist so I'm unsure where that came from.

**Comment by eyaab** [comment]
Thank you for taking the time to answer my question. I will definitely try to create the layer as you suggested and see how it works out. I apologize for any confusion of not double-checking that parameter given by the chatbot before asking my question.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
