### ISSUE TITLE
rotate().metadata() doesn't return rotated metadata.

### ISSUE THREAD

**Issue by sugoidesune** [lovell/sharp#3579]
- [ x] Running `npm install sharp` completes without error.
- [x ] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [ x] I am using the latest version of `sharp` : 0.31.3

### What are the steps to reproduce?

```js
var metadata = await sharp(buffer).rotate().metadata()
// old metadata as if it wasn't rotated

var rotated_buffer = await sharp(buffer).rotate().toBuffer()
var rotated_metadata = await sharp(rotated_buffer ).metadata()
// rotated_metadata is now correctly rotated as the sharp instance was created from a rotated buffer.
```

### What is the expected behaviour?

```js
var metadata = await sharp(buffer).rotate().metadata()
// metadata should be rotated 
```

**Comment by lovell** [comment]
Please see https://sharp.pixelplumbing.com/api-input#metadata

> This is taken from the header of the input image. It does not include operations, such as resize, to be applied to the output image.

Please also see the "Based on EXIF rotation metadata..." example.

**Comment by lovell** [comment]
I've added further clarification to the docs via commit https://github.com/lovell/sharp/commit/fc03fba6021f2b24275d7cc2edc7390f229b7543
