### ISSUE TITLE
build configure

### ISSUE THREAD

**Issue by doudouodong** [lovell/sharp#3580]
I found some problems about vips. I want to rebuild sharp.js. How to build sharp.js on mac

**Comment by lovell** [comment]
Please provide **significantly** more information about the problem(s) you found, what you've tried so far, what documentation you followed, what versions are involved etc.

**Comment by doudouodong** [comment]
vips 8.14.1 not support negative linespace, I want rebuild sharp.js

**Comment by doudouodong** [comment]
node-gyp build 


gyp: Call to 'node -p "require('./lib/libvips').minimumLibvipsVersion"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp

**Comment by lovell** [comment]
Closing due to lack of information but please feel free to reopen with more details if further help is required.
