### ISSUE TITLE
Way to select encoder when saving AVIF

### ISSUE THREAD

**Issue by saschanaz** [lovell/sharp#3582]
### What are you trying to achieve?

Wanted to try rav1e as the default AVIF encoder was too slow, but it seems there's no way for that.

### When you searched for similar feature requests, what did you find that might be related?

Couldn't find one when querying with "select encoder". The caller isn't setting [`encoder`](https://www.libvips.org/API/current/VipsForeignSave.html#vips-heifsave), so I guess it's an issue anyway.

https://github.com/lovell/sharp/blob/844deaf48060d60eb05f3f61c567282e3611f12a/src/pipeline.cc#L915-L923

### What would you expect the API to look like?

Perhaps `.avif({ encoder: "rav1e" })`?

### What alternatives have you considered?

Wanted to try wasm-vips instead but it seemingly doesn't support heifsave at all. https://github.com/kleisauke/wasm-vips/issues/44

### Please provide sample image(s) that help explain this feature

(Not applicable)

**Comment by lovell** [comment]
To use rav1e, you'll need to compile your own libvips, libheif and rav1e and install them globally before re-installing sharp.

There's an issue tracking the future possible use of rav1e in the prebuilt binaries at https://github.com/lovell/sharp-libvips/issues/97 but there's a lack of recent evidence that it's still faster than aom, which is still under heavy development.
