### ISSUE TITLE
Update Installation Documentation Around The AWS Lambda Section

### ISSUE THREAD

**Issue by CCattano** [lovell/sharp#3585]
### What are you trying to achieve?

Update documentation in https://sharp.pixelplumbing.com/install

Add additional information to the existing AWS Lambda section or add a new AWS API Gateway section

### When you searched for similar feature requests, what did you find that might be related?

![image](https://user-images.githubusercontent.com/47487276/223729313-8b643e21-ba79-44d0-922c-ebda1e645811.png)

No one asking for documentation updates related to AWS

### What would you expect the API to look like?

The same, just think someone should append the docs.

### What alternatives have you considered?

None

### Please explain this feature

So the issue is AWS API Gateway is a common way to invoke Lambda functions.

For example, static frontend website content is stored in AWS S3

That content loads and makes a web request to your AWS API Gateway which forwards it to your lambda and this gets your backend code to run.

The problem with that is API Gateway doesn't support multi-part formdata out of the box.

You can see this discussed [here](https://stackoverflow.com/questions/41756190/)

It turns out the reason my sharp code always works in localhost but I couldn't get it to work once I deployed my code to my Lambda was because API Gateway was warping my multipart formdata payload. By time my Lambda received it, the file buffer was not in a valid format that sharp could process.

To preface, sharp is in no way at fault, or lacking functionality. It's a great library that's easy to use. What I'm advocating for is just adding another bit of installation advice to the docs.

I spent all of yesterday trying to add logs for info and deploy, add more logs for info and deploy, b/c I couldn't replicate in localhost. This made the discovery process super painful and slow.

I was deep in the weeds trying to do things like compile from source, install c++ compilers, install node-gyp, hunt down erroneous CLI errors, etc. B/c I was convinced the issue was that I couldn't get sharp to correctly install in my AWS Lambda environment.

It turned out none of that was necessary b/c the AWS Lambda installation instructions are right, and I was missing a different piece of the puzzle.

My desired outcome from this ticket would be that an AWS API Gateway section could be added to the Installation instruction group above or below the AWS Lambda group.

The exact change I made is the one detailed [here](https://stackoverflow.com/a/56132015/2293177).

My hope would be my chasing red-herrings and such could serve as a way to save others from doing the same in the future b/c I believe using API Gateway to access Lambdas is not a unique situation. 

Others could face the same challenges and I'd like to save them the time of getting lost in the weeds and chasing down the wrong solutions b/c the actual problem wasn't obvious.

So a new small section could be helpful I think. One stating you need to update the APIs in your AWS API Gateway to support multipart formdata if they're being used to upload the image buffer that you want sharp to process.

**Comment by lovell** [comment]
This has come up a few times before e.g. #889 #2085 

I've added a link to the relevant AWS docs via https://github.com/lovell/sharp/commit/2eaab59c48fda65fdc60e06faad23f8e4b6bde0c - the media type(s) to add will depend on the individual scenario.

As an aside, if you're using this as a way to "upload" files to S3, then its pre-signed URL feature might allow you to remove some of the complexity.
