### ISSUE TITLE
Sharp does not work for linux/arm64/v8 on node focal image for docker

### ISSUE THREAD

**Issue by ziyak97** [lovell/sharp#3587]
Using the node focal image for node 18 on docker gives me the following error

`Cannot find module '../build/Release/sharp-linux-x64.node'`

I am installing the following packages

`RUN apt update && apt install -y --no-install-recommends software-properties-common make g++ build-essential autoconf automake zlib1g-dev libpng-dev nasm bash libvips-tools`

Runs fine on non linux/arm64/v8  (Mac M2) architectures

**Comment by lovell** [comment]
Please open [a new installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) and answer all of the questions if you still require help.
