### ISSUE TITLE
Nested composite how to?

### ISSUE THREAD

**Issue by trangvu9** [lovell/sharp#3588]
Hi there,

How do I do nested composite? I tried to "toBuffer" the nested ones but it said "Input buffer contains unsupported image format".

Here's what it looks like:

```
const childBuffer = await sharp({
  create: {
    width, height, background: 'white', channels: 3
  }
}).composite([
  {
    top, left,
    input: {
      create: {
        width, height, background: "green", channels: 3
      }
    }
  }
]).toBuffer();

await sharp({
  create: {
    width, height, background: 'white', channels: 3
  }
}).composite(childBuffer).toFile(fileName); // Input buffer contains unsupported image format

**Comment by lovell** [comment]
You might need to specify what format you'd like the (intermediate) output to use, e.g.
```diff
- .toBuffer();
+ .png().toBuffer();
```
In addition, the `composite()` function accepts an array of Objects (rather than a Buffer):
```diff
- .composite(childBuffer)
+ .composite([{ input: childBuffer }])
```
https://sharp.pixelplumbing.com/api-composite

**Comment by trangvu9** [comment]
Thanks, it works. It’d be great if you can do nested composite without having to export to buffers.
