### ISSUE TITLE
Integrity check fails with prebuilt libvips binary

### ISSUE THREAD

**Issue by ansnoussi** [lovell/sharp#3590]
## Possible install-time or require-time problem
- Installing with custom prebuilt libvips binary ( built with pdf support ) fails because of integrity check, while integrity checks should only be ran for remote binaries.
- the local libvips binary is specified using the `sharp_libvips_local_prebuilds` env var.

- [x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?
Yes.

- [] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Is this a problem with filesystem permissions?

I set 644 permission for the binary : `chmod 644 v8.13.3/libvips-8.13.3-linux-arm64v8.tar.br`

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7 or later, does the user running `npm install` own the directory it is run in?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?
instead I ran : `npm_config_sharp_libvips_local_prebuilds=/var/task npm install --verbose --foreground-scripts sharp`
<details>

bash-4.2# npm_config_sharp_libvips_local_prebuilds=/var/task npm install --verbose --foreground-scripts sharp
npm verb cli /var/lang/bin/node /var/lang/bin/npm
npm info using npm@8.19.3
npm info using node@v16.19.1
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 2ms
npm timing config:load:file:/var/lang/lib/node_modules/npm/npmrc Completed in 0ms
npm timing config:load:builtin Completed in 0ms
npm timing config:load:cli Completed in 1ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/var/task/.npmrc Completed in 0ms
npm timing config:load:project Completed in 2ms
npm timing config:load:file:/root/.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:/var/lang/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 9ms
npm timing npm:load:configload Completed in 9ms
npm timing npm:load:mkdirpcache Completed in 4ms
npm timing npm:load:mkdirplogs Completed in 1ms
npm verb title npm install sharp
npm verb argv "install" "--loglevel" "verbose" "--foreground-scripts" "sharp"
npm timing npm:load:setTitle Completed in 1ms
npm timing config:load:flatten Completed in 1ms
npm timing npm:load:display Completed in 5ms
npm verb logfile logs-max:10 dir:/root/.npm/_logs
npm verb logfile /root/.npm/_logs/2023-03-16T11_52_24_522Z-debug-0.log
npm timing npm:load:logFile Completed in 4ms
npm timing npm:load:timers Completed in 0ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load Completed in 25ms
npm timing arborist:ctor Completed in 0ms
npm timing arborist:ctor Completed in 1ms
npm timing idealTree:init Completed in 12ms
npm timing idealTree:userRequests Completed in 2ms
npm http fetch GET 200 https://registry.npmjs.org/npm 1196ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/sharp 1334ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 250ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/tunnel-agent 280ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/simple-get 872ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/tar-fs 873ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/color 968ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/node-addon-api 1088ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/prebuild-install 1271ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/semver 1325ms (cache miss)
npm timing idealTree:#root Completed in 2672ms
npm http fetch GET 200 https://registry.npmjs.org/github-from-package 355ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/once 355ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/napi-build-utils 357ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/mkdirp-classic 369ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/mkdirp-classic 458ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/simple-concat 490ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/color-convert 542ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/safe-buffer 534ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/rc 577ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/pump 601ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/color-string 605ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/expand-template 642ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/decompress-response 641ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/tar-stream 1071ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/chownr 1076ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/node-abi 1080ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/lru-cache 1237ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/minimist 1536ms (cache miss)
npm timing idealTree:node_modules/sharp Completed in 1558ms
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle 446ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/color-name 712ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/color-name 1278ms (cache miss)
npm timing idealTree:node_modules/color Completed in 1291ms
npm timing idealTree:node_modules/color-convert Completed in 6ms
npm timing idealTree:node_modules/color-name Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 359ms (cache miss)
npm timing idealTree:node_modules/color-string Completed in 366ms
npm timing idealTree:node_modules/detect-libc Completed in 0ms
npm timing idealTree:node_modules/node-addon-api Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/deep-extend 418ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/ini 1530ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/strip-json-comments 1547ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/end-of-stream 1600ms (cache miss)
npm timing idealTree:node_modules/prebuild-install Completed in 1620ms
npm timing idealTree:node_modules/expand-template Completed in 0ms
npm timing idealTree:node_modules/github-from-package Completed in 0ms
npm timing idealTree:node_modules/minimist Completed in 0ms
npm timing idealTree:node_modules/mkdirp-classic Completed in 0ms
npm timing idealTree:node_modules/napi-build-utils Completed in 0ms
npm timing idealTree:node_modules/node-abi Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/wrappy 152ms (cache miss)
npm timing idealTree:node_modules/pump Completed in 157ms
npm timing idealTree:node_modules/end-of-stream Completed in 0ms
npm timing idealTree:node_modules/once Completed in 2ms
npm timing idealTree:node_modules/rc Completed in 4ms
npm timing idealTree:node_modules/deep-extend Completed in 0ms
npm timing idealTree:node_modules/ini Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/yallist 202ms (cache miss)
npm timing idealTree:node_modules/semver Completed in 206ms
npm timing idealTree:node_modules/lru-cache Completed in 2ms
npm http fetch GET 200 https://registry.npmjs.org/mimic-response 207ms (cache miss)
npm timing idealTree:node_modules/simple-get Completed in 213ms
npm timing idealTree:node_modules/decompress-response Completed in 3ms
npm timing idealTree:node_modules/mimic-response Completed in 0ms
npm timing idealTree:node_modules/simple-concat Completed in 0ms
npm timing idealTree:node_modules/simple-swizzle Completed in 2ms
npm timing idealTree:node_modules/is-arrayish Completed in 0ms
npm timing idealTree:node_modules/strip-json-comments Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/fs-constants 203ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/inherits 224ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/readable-stream 363ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/bl 1358ms (cache miss)
npm timing idealTree:node_modules/tar-fs Completed in 1366ms
npm timing idealTree:node_modules/chownr Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/string_decoder 233ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/util-deprecate 237ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/buffer 354ms (cache miss)
npm timing idealTree:node_modules/tar-stream Completed in 372ms
npm http fetch GET 200 https://registry.npmjs.org/base64-js 260ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/ieee754 262ms (cache miss)
npm timing idealTree:node_modules/bl Completed in 266ms
npm timing idealTree:node_modules/buffer Completed in 5ms
npm timing idealTree:node_modules/base64-js Completed in 0ms
npm timing idealTree:node_modules/fs-constants Completed in 0ms
npm timing idealTree:node_modules/ieee754 Completed in 0ms
npm timing idealTree:node_modules/inherits Completed in 0ms
npm timing idealTree:node_modules/readable-stream Completed in 3ms
npm timing idealTree:node_modules/string_decoder Completed in 4ms
npm timing idealTree:node_modules/safe-buffer Completed in 0ms
npm timing idealTree:node_modules/tunnel-agent Completed in 0ms
npm timing idealTree:node_modules/util-deprecate Completed in 0ms
npm timing idealTree:node_modules/wrappy Completed in 0ms
npm timing idealTree:node_modules/yallist Completed in 0ms
npm timing idealTree:buildDeps Completed in 10140ms
npm timing idealTree:fixDepFlags Completed in 2ms
npm timing idealTree Completed in 10159ms
npm timing reify:loadTrees Completed in 10161ms
npm timing reify:diffTrees Completed in 3ms
npm timing reify:retireShallow Completed in 1ms
npm timing reify:createSparse Completed in 19ms
npm timing reify:loadBundles Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz 376ms (cache miss)
npm timing reifyNode:node_modules/string_decoder Completed in 402ms
npm http fetch GET 200 https://registry.npmjs.org/ieee754/-/ieee754-1.2.1.tgz 374ms (cache miss)
npm timing reifyNode:node_modules/ieee754 Completed in 403ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 568ms
npm timing auditReport:getReport Completed in 573ms
npm timing auditReport:init Completed in 0ms
npm timing reify:audit Completed in 573ms
npm http fetch GET 200 https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz 593ms (cache miss)
npm timing reifyNode:node_modules/util-deprecate Completed in 619ms
npm http fetch GET 200 https://registry.npmjs.org/fs-constants/-/fs-constants-1.0.0.tgz 590ms (cache miss)
npm timing reifyNode:node_modules/fs-constants Completed in 618ms
npm http fetch GET 200 https://registry.npmjs.org/once/-/once-1.4.0.tgz 576ms (cache miss)
npm timing reifyNode:node_modules/once Completed in 619ms
npm http fetch GET 200 https://registry.npmjs.org/tar-stream/-/tar-stream-2.2.0.tgz 591ms (cache miss)
npm timing reifyNode:node_modules/tar-stream Completed in 621ms
npm http fetch GET 200 https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.4.4.tgz 583ms (cache miss)
npm timing reifyNode:node_modules/end-of-stream Completed in 623ms
npm http fetch GET 200 https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz 573ms (cache miss)
npm timing reifyNode:node_modules/color-name Completed in 622ms
npm http fetch GET 200 https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz 587ms (cache miss)
npm timing reifyNode:node_modules/wrappy Completed in 625ms
npm http fetch GET 200 https://registry.npmjs.org/base64-js/-/base64-js-1.5.1.tgz 598ms (cache miss)
npm timing reifyNode:node_modules/base64-js Completed in 628ms
npm http fetch GET 200 https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-2.0.1.tgz 596ms (cache miss)
npm timing reifyNode:node_modules/strip-json-comments Completed in 633ms
npm http fetch GET 200 https://registry.npmjs.org/chownr/-/chownr-1.1.4.tgz 605ms (cache miss)
npm timing reifyNode:node_modules/chownr Completed in 636ms
npm http fetch GET 200 https://registry.npmjs.org/mimic-response/-/mimic-response-3.1.0.tgz 604ms (cache miss)
npm timing reifyNode:node_modules/mimic-response Completed in 637ms
npm http fetch GET 200 https://registry.npmjs.org/pump/-/pump-3.0.0.tgz 587ms (cache miss)
npm timing reifyNode:node_modules/pump Completed in 638ms
npm http fetch GET 200 https://registry.npmjs.org/deep-extend/-/deep-extend-0.6.0.tgz 602ms (cache miss)
npm timing reifyNode:node_modules/deep-extend Completed in 642ms
npm http fetch GET 200 https://registry.npmjs.org/decompress-response/-/decompress-response-6.0.0.tgz 607ms (cache miss)
npm timing reifyNode:node_modules/decompress-response Completed in 642ms
npm http fetch GET 200 https://registry.npmjs.org/simple-concat/-/simple-concat-1.0.1.tgz 606ms (cache miss)
npm timing reifyNode:node_modules/simple-concat Completed in 643ms
npm http fetch GET 200 https://registry.npmjs.org/github-from-package/-/github-from-package-0.0.0.tgz 598ms (cache miss)
npm timing reifyNode:node_modules/github-from-package Completed in 645ms
npm http fetch GET 200 https://registry.npmjs.org/ini/-/ini-1.3.8.tgz 612ms (cache miss)
npm timing reifyNode:node_modules/ini Completed in 649ms
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle/-/simple-swizzle-0.2.2.tgz 600ms (cache miss)
npm timing reifyNode:node_modules/simple-swizzle Completed in 649ms
npm http fetch GET 200 https://registry.npmjs.org/mkdirp-classic/-/mkdirp-classic-0.5.3.tgz 602ms (cache miss)
npm timing reifyNode:node_modules/mkdirp-classic Completed in 650ms
npm http fetch GET 200 https://registry.npmjs.org/simple-get/-/simple-get-4.0.1.tgz 598ms (cache miss)
npm timing reifyNode:node_modules/simple-get Completed in 650ms
npm http fetch GET 200 https://registry.npmjs.org/color-string/-/color-string-1.9.1.tgz 601ms (cache miss)
npm timing reifyNode:node_modules/color-string Completed in 652ms
npm http fetch GET 200 https://registry.npmjs.org/expand-template/-/expand-template-2.0.3.tgz 604ms (cache miss)
npm timing reifyNode:node_modules/expand-template Completed in 652ms
npm http fetch GET 200 https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz 620ms (cache miss)
npm timing reifyNode:node_modules/yallist Completed in 654ms
npm http fetch GET 200 https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz 572ms (cache miss)
npm timing reifyNode:node_modules/inherits Completed in 656ms
npm http fetch GET 200 https://registry.npmjs.org/detect-libc/-/detect-libc-2.0.1.tgz 601ms (cache miss)
npm timing reifyNode:node_modules/detect-libc Completed in 655ms
npm http fetch GET 200 https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz 623ms (cache miss)
npm timing reifyNode:node_modules/lru-cache Completed in 658ms
npm http fetch GET 200 https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz 627ms (cache miss)
npm timing reifyNode:node_modules/safe-buffer Completed in 661ms
npm http fetch GET 200 https://registry.npmjs.org/napi-build-utils/-/napi-build-utils-1.0.2.tgz 595ms (cache miss)
npm timing reifyNode:node_modules/napi-build-utils Completed in 659ms
npm http fetch GET 200 https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz 612ms (cache miss)
npm timing reifyNode:node_modules/color-convert Completed in 662ms
npm http fetch GET 200 https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz 598ms (cache miss)
npm timing reifyNode:node_modules/tunnel-agent Completed in 664ms
npm http fetch GET 200 https://registry.npmjs.org/color/-/color-4.2.3.tgz 609ms (cache miss)
npm timing reifyNode:node_modules/color Completed in 665ms
npm http fetch GET 200 https://registry.npmjs.org/rc/-/rc-1.2.8.tgz 626ms (cache miss)
npm timing reifyNode:node_modules/rc Completed in 667ms
npm http fetch GET 200 https://registry.npmjs.org/buffer/-/buffer-5.7.1.tgz 646ms (cache miss)
npm timing reifyNode:node_modules/buffer Completed in 673ms
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.3.2.tgz 646ms (cache miss)
npm timing reifyNode:node_modules/is-arrayish Completed in 679ms
npm http fetch GET 200 https://registry.npmjs.org/prebuild-install/-/prebuild-install-7.1.1.tgz 615ms (cache miss)
npm timing reifyNode:node_modules/prebuild-install Completed in 680ms
npm http fetch GET 200 https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz 649ms (cache miss)
npm timing reifyNode:node_modules/minimist Completed in 695ms
npm http fetch GET 200 https://registry.npmjs.org/tar-fs/-/tar-fs-2.1.1.tgz 634ms (cache miss)
npm timing reifyNode:node_modules/tar-fs Completed in 701ms
npm http fetch GET 200 https://registry.npmjs.org/node-addon-api/-/node-addon-api-5.1.0.tgz 655ms (cache miss)
npm timing reifyNode:node_modules/node-addon-api Completed in 718ms
npm http fetch GET 200 https://registry.npmjs.org/semver/-/semver-7.3.8.tgz 658ms (cache miss)
npm timing reifyNode:node_modules/semver Completed in 726ms
npm http fetch GET 200 https://registry.npmjs.org/sharp/-/sharp-0.31.3.tgz 669ms (cache miss)
npm timing reifyNode:node_modules/sharp Completed in 735ms
npm http fetch GET 200 https://registry.npmjs.org/node-abi/-/node-abi-3.33.0.tgz 1354ms (cache miss)
npm timing reifyNode:node_modules/node-abi Completed in 1399ms
npm http fetch GET 200 https://registry.npmjs.org/bl/-/bl-4.1.0.tgz 1436ms (cache miss)
npm timing reifyNode:node_modules/bl Completed in 1466ms
npm http fetch GET 200 https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.2.tgz 1473ms (cache miss)
npm timing reifyNode:node_modules/readable-stream Completed in 1500ms
npm timing reify:unpack Completed in 1501ms
npm timing reify:unretire Completed in 0ms
npm timing build:queue Completed in 4ms
npm timing build:link:node_modules/prebuild-install Completed in 5ms
npm timing build:link:node_modules/rc Completed in 6ms
npm timing build:link:node_modules/semver Completed in 6ms
npm timing build:link Completed in 7ms
npm info run sharp@0.31.3 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

> sharp@0.31.3 install
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Using local libvips from /var/task/v8.13.3/libvips-8.13.3-linux-arm64v8.tar.brles/sharp (node install/libvips && node install/
sharp: Integrity expected: sha512-b+iI9V/ehgDabXYRQcvqa5CEysh+1FQsgFmYc358StCrJCDahwNmsQdsiH1GOVd5WaWh5wHUGByPwMmFOO16Aw==de install/
sharp: Integrity received: sha512-RbuIagjvP8CkdxhSLJbzM0h8IeY6Z1k6Yz4ub/DNANdnITv9unFQJMChr20Si6YppFUNacxjcBOumkGYLl9kNw==
sharp: Installation error: Integrity check failed for linux-arm64v8
sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm info run sharp@0.31.3 install { code: 1, signal: null }
npm timing reify:rollback:createSparse Completed in 46ms
npm timing reify:rollback:retireShallow Completed in 0ms
npm timing command:install Completed in 12652ms
npm notice 
npm notice New major version of npm available! 8.19.3 -> 9.6.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.6.2
npm notice Run npm install -g npm@9.6.2 to update!
npm notice 
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/var/lang/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
npm verb stack     at ChildProcess.emit (node:events:513:28)
npm verb stack     at maybeClose (node:internal/child_process:1100:16)
npm verb stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
npm verb pkgid sharp@0.31.3
npm verb cwd /var/task
npm verb Linux 5.15.49-linuxkit
npm verb node v16.19.1
npm verb npm  v8.19.3
npm ERR! code 1
npm ERR! path /var/task/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c -- (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm verb exit 1
npm timing npm Completed in 12744ms
npm verb unfinished npm timer reify 1678967544610
npm verb unfinished npm timer reify:build 1678967556327
npm verb unfinished npm timer build 1678967556328
npm verb unfinished npm timer build:deps 1678967556328
npm verb unfinished npm timer build:run:install 1678967556339
npm verb unfinished npm timer build:run:install:node_modules/sharp 1678967556339
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-03-16T11_52_24_522Z-debug-0.log
bash-4.2# 

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
bash-4.2# npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp

  System:
    OS: Linux 5.15 Amazon Linux 2
    CPU: (6) arm64 unknown
    Memory: 6.45 GB / 7.76 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 16.19.1 - /var/lang/bin/node
    npm: 8.19.3 - /var/lang/bin/npm

bash-4.2# 
```

**Comment by lovell** [comment]
> Installing with custom prebuilt libvips binary ( built with pdf support ) fails because of integrity check

I think this is working as intended. Use either the `--sharp-install-force` flag or set the `SHARP_INSTALL_FORCE` env var at install time to skip the check.

**Comment by ansnoussi** [comment]
thanks, adding the `SHARP_INSTALL_FORCE` does indeed skip the integrity check.
but shouldn't `SHARP_INSTALL_FORCE` be a default when using a local build of libvips (aka adding `npm_config_sharp_libvips_local_prebuilds` config ) ? 🤔 the whole purpose of the integrity check if making sure the downloaded pre-compiled libvips wasn't corrupted while downloading.

**Comment by ansnoussi** [comment]
Also is it normal when installing sharp using `SHARP_INSTALL_FORCE=true npm_config_sharp_libvips_local_prebuilds=/var/task npm install sharp` the node_modules for sharp are kept inside the sharp folder ( `node_modules/sharp/node_modules` ) ?

Because this makes the compressed layer 93mb zipped ! which is exceeds the limit of AWS ( 50mb )

Here's a screenshot of the whole layer compressed, vs only compressing the node_modules of sharp (71mb) :

<img width="436" alt="Screenshot 2023-03-17 at 00 07 33" src="https://user-images.githubusercontent.com/33237270/225772071-4dfbf125-a24c-4e4d-8ac0-2ed2a4f812ec.png">

**Comment by lovell** [comment]
The purpose of the integrity check is to ensure the integrity of the tarballs regardless of source.

There is logic to provide arch/platform specific integrity values via environment variables, which I think might be better for your scenario:
```
npm_package_config_integrity_linux_arm64v8="sha512-xxx..."
```
I've added a note to the docs about this via commit https://github.com/lovell/sharp/commit/1eefd4e562fa109e419aa0c83d78fb53b64d11b6

**Comment by lovell** [comment]
Your question about nested `node_modules` directories sounds like it relates to the package manager (and its version) you are using rather than sharp, which doesn't control such things.

**Comment by ansnoussi** [comment]
understood, thank you for your time, and for this amazing tool 🙏.
