### ISSUE TITLE
.trim() does not work as expected

### ISSUE THREAD

**Issue by cmette** [lovell/sharp#3591]
## Question about an existing feature

I want to use sharp to automatically crop historical photos from a mass scan. To do this, the scans are automatically and continuously stored as tif or jpg files by a scanner in a directory on the server. The files have a size between 10Mb and 200Mb.

I know node quite well but have no experience with sharp.js

The photos are cropped only from the top left. This is correct. **They are not cropped from the bottom and right**.

### What are you trying to achieve?

I have experimented with various parameters of **.trim()**. But unfortunately I do not get the desired result. Possibly .trim() does not work as I expect it too?

### When you searched for similar issues, what did you find that might be related?

I am not sure if this is an bug or not. Possibly my application of .trim() is also wrong?

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

Here's what I tried:  

    // at first
    let image = sharp(strPathToFile); // tested with *.jpg and *.tif
    image.trim();

    // 2nd try
    // The background of my pictures is almost white, but not always. There are also slight disturbances 
    // (from r:255, g:255, b:255 to r:248, g:248, b:248) in the white areas. See sample photos.
    image.trim({background: 'white', threshold: 45});

    // 3th try
    image.trim({background: 'yellow', threshold: 45});

    // 4th try
    image.trim({background: 'white', threshold: 100});

    // 5th try
    image.trim({background: Color({r: 248, g: 248, b: 248}), threshold: 100});

#### The Frontside.
![1123-1 front raw tif](https://user-images.githubusercontent.com/13376233/225682794-d3e5e5ca-ebef-4276-939c-5d394fe30524.jpg)

#### The Backside
![1123-1 back raw tif](https://user-images.githubusercontent.com/13376233/225682818-e7c8b48a-53bb-45bc-96e2-591b9ac34756.jpg)

### The Problem
After .trim() the images are trimmed from top and (almost always) left, but not from bottom and right. Is there a solution to trim properly from all sides?

**Comment by lovell** [comment]
The background colour is fairly uniform and matches the top-left corner so there's probably no need to "force" a background colour for this image when trimming. I notice a few grey spots down the right side, presumably dust/dirt on the scanner, so you will need to increase the threshold if you want to ignore these.

I tried using the threshold of 45 you provided, without any background colour, which would appears to do what you need for this sample image.
```js
sharp('225682794-d3e5e5ca-ebef-4276-939c-5d394fe30524.jpg').trim({ threshold: 45 }).toFile('out.png');
```
![out](https://user-images.githubusercontent.com/210965/225719927-b56ec0dd-dd5b-4d9f-bd4e-2593747144bd.png)

**Comment by cmette** [comment]
Thank you for your reply!

If I follow your procedure, I get a correctly cropped photo. i.e. I downloaded my own photo again from github and created it with the code line you described.

If I use my original photo or the backside, then it does not succeed. 

Can I also move the color sample from the upper left corner to the lower right or somewhere else? I have some color defects in the upper left corner of some photos.

Here are a few sources available: https://www.dropbox.com/sh/0k3owb6tmx2hurt/AACwwgaTv7Vb_tRdE372F39Ka?dl=0

**Comment by cmette** [comment]
I have now removed the area on the left side that is incorrectly generated by the scanner. This gives the photo a white background on all sides. But this has no effect on .trim(). Trim does not return a correct image.

stats 1123.back.raw.tif
    entropy: 3.395190274750348,
    sharpness: 0.8813908239138026,
    dominant: {r:248, g:248, b:248, alpha:undefined}

left disturbance area
stats part1
    entropy: 5.501107246891479,
    sharpness: 0.793556219627799,
    dominant: {r:104, g:104, b:104, alpha:undefined}

metadata after trim
metadata
    .format: jpeg,
    .size: undefined,
    .width: 6898,
    .height: 9827,
    .space: srgb,
    .channels: 3,
    .depth: uchar,

**Comment by lovell** [comment]
The 1962.* example images available via the Dropbox link have a thick dark grey line running down the left hand side, what appears to be the lid of the scanner. This is darker than much of the object being scanned, so trim is unlikely to be able to help here.

**Comment by cmette** [comment]
Yes, of course - as I wrote above, if I remove this area, save the photo without this border in a JPG file, reload the corrected image and then trim the result again, but unfortunately I don't get a correct result either. 

I would expect this output:
![1123 back raw correct trim](https://user-images.githubusercontent.com/13376233/225873823-8e98f457-5e76-401d-b117-0d5418911bfa.jpg)

Is my expectation wrong?

**Comment by cmette** [comment]
It seems, that the trim algorithm is stopped by dust and scratches.  

![1123 with lint and scratches](https://user-images.githubusercontent.com/13376233/225883098-af7a5b1c-9d6d-456b-9756-ab0102454dfa.jpg)

Is there a sharp.filter to remove these interferences?

**Comment by cmette** [comment]
Gotcha! .median(20) before .trim(45) does the trick!
Thank you @lovell
