### ISSUE TITLE
Does the format of the original image affects the processing time?

### ISSUE THREAD

**Issue by Dimitris24sta23** [lovell/sharp#3593]
Hi,

I'm using AWS lambda to process images on the fly and i'm trying to figure out if the format of the original image affects the processing time.

I did some tests and it seems that converting jpegs to webps is significantly faster than the other way around.
Is there a previous comparison table i can refer to, so i can make the right decision of what type my original images will be?

Below are my findings although i'm not sure they're accurate (simple node.js script running on localhost).

----------------------------

**Input: 30MB – JPG (13583x5417)**

| Dimension | To format | Quality | Processing time (ms) |
| --------- | --------- | ------- | -------------------- |
| 3840x2160 | JPEG      | 80      | 1355                 |
| 3840x2160 | WEBP      | 80      | 2642                 |
| 1600x1200 | JPEG      | 80      | 742                  |
| 1600x1200 | WEBP      | 80      | 1600                 |
| 1000x750  | JPEG      | 80      | 68                   |
| 1000x750  | WEBP      | 80      | 185                  |
| 640x480   | JPEG      | 80      | 23                   |
| 640x480   | WEBP      | 80      | 70                   |
| 320x240   | JPEG      | 80      | 17                   |
| 320x240   | WEBP      | 80      | 31                   |

-----------------

**Input: 8MB – JPG (3200x2400)**

| Dimension | To format | Quality | Processing time (ms) |
| --------- | --------- | ------- | -------------------- |
| 1600x1200 | JPEG      | 80      | 90                   |
| 1600x1200 | WEBP      | 80      | 390                  |
| 1000x750  | JPEG      | 80      | 33                   |
| 1000x750  | WEBP      | 80      | 151                  |
| 640x480   | JPEG      | 80      | 17                   |
| 640x480   | WEBP      | 80      | 63                   |
| 320x240   | JPEG      | 80      | 7                    |
| 320x240   | WEBP      | 80      | 21                   |

----------------------

**Input: 30MB – WEBP (13583x5417)**

| Dimension | To format | Quality | Processing time (ms) |
| --------- | --------- | ------- | -------------------- |
| 3840x2160 | JPEG      | 80      | 2388                 |
| 3840x2160 | WEBP      | 80      | 3571                 |
| 1600x1200 | JPEG      | 80      | 2168                 |
| 1600x1200 | WEBP      | 80      | 2638                 |
| 1000x750  | JPEG      | 80      | 2143                 |
| 1000x750  | WEBP      | 80      | 2261                 |
| 640x480   | JPEG      | 80      | 2113                 |
| 640x480   | WEBP      | 80      | 2216                 |
| 320x240   | JPEG      | 80      | 2105                 |
| 320x240   | WEBP      | 80      | 2158                 |

------------------------------

**Input: 2.5MB – WEBP (3200x2400)**

| Dimension | To format | Quality | Processing time (ms) |
| --------- | --------- | ------- | -------------------- |
| 1600x1200 | JPEG      | 80      | 239                  |
| 1600x1200 | WEBP      | 80      | 532                  |
| 1000x750  | JPEG      | 80      | 216                  |
| 1000x750  | WEBP      | 80      | 325                  |
| 640x480   | JPEG      | 80      | 201                  |
| 640x480   | WEBP      | 80      | 245                  |
| 320x240   | JPEG      | 80      | 195                  |
| 320x240   | WEBP      | 80      | 209                  |

*Quality doesn't seem to affect the time much

Thanks

**Comment by lovell** [comment]
The short answer is: yes.

The slightly longer answer is: yes, JPEG en/decoding is almost always faster than WebP, although the numbers here seem pretty extreme. Perhaps giving your function more RAM and therefore more CPU time could help smooth out the difference. The use of `sequentialRead: true` might also improve performance for lower RAM environments. https://sharp.pixelplumbing.com/api-constructor#parameters

**Comment by Dimitris24sta23** [comment]
Thanks @lovell !
