### ISSUE TITLE
How does sharp (and/or libvips) handle the manipulation of multi-resolution image sources?

### ISSUE THREAD

**Issue by mbklein** [lovell/sharp#3594]
### Background

I'm the maintainer of the [node-iiif](https://github.com/samvera/node-iiif) and [serverless-iiif](https://github.com/samvera/serverless-iiif) projects. At the heart of both of these is the ability to crop, resize, and rotate images on the fly. Our recommended source file format is a tiled, multi-resolution, JPEG-compressed TIFF, e.g., one created with

```
vips tiffsave source_image.tif output_image.tif --tile --pyramid --compression jpeg --tile-width 256 --tile-height 256
```

### Setup

I have one image with dimensions of `14499x12069` pixels, so it's large, but well below sharp's default pixel limit. Because it's a pyramid, it contains additional versions in the following sizes: `7249x6034`, `3624x3017`, `1812x1508`, `906x754`, `453x377`, `226x188`. The image is stored in Amazon S3, so I use the AWS SDK to create a readable stream.

Let's say someone requests a 3000-pixel wide version with no other transformations. I create a sharp pipeline, pipe the image stream through it, and return the resulting buffer.

```
async function resizeToWidth(source, width) {
  const stream = createReadableStreamFromS3(source);
  const pipeline = sharp().resize({ width, fit: "cover" });
  return await stream.pipe(pipeline).toBuffer();
}
```

This is a simplified version of the pipeline, which can be a lot more complex depending on the request. I've also tried loading the image with `sequentialRead: true` – it seems to help for some transformations, but not for others.

### Questions

When I perform an image operation this way, does the library attempt to optimize the operation by, say, starting with the 3624x3017 frame, since it's the closest to the requested size without going under? Or does it operate on the entire 15k-pixel-wide image? Is there a way to influence this behavior from the client-side?

The reason I'm asking is that some operations seem to take far longer than I'd expect on certain images. Most of the time, things are extremely fast. Requests for individual tiles or cropped sections of the image in question, with or without resizing, return in milliseconds. But a request for the full frame, even resized down to just a couple thousand pixels wide, sometimes takes 12-15 seconds or more. I've been trying to find the break-even point, but it's slow going. I thought I'd ask about optimization here while I continue to investigate the issue on my own.

I'm running this code in an AWS Lambda function, so I'm limited to a maximum of 10GB of memory (though it's only configured for 2GB at the moment), and 512MB of ephemeral disk space. (I can provision more, but it gets expensive quickly.) Increasing the RAM doesn't seem to help with performance much if at all.

Here's the [pyramidal TIFF in question](https://nul-public.s3.amazonaws.com/sharp-pyramid/sample.tif).

I'd greatly appreciate any pointers you have, or even followup questions that might uncover things I haven't thought about.

**Comment by sugoidesune** [comment]
It will process whatever you feed it so the real question is what does "createReadableStreamFromS3(source)` download?
You can check by reading the metadata : `sharp(src).metadata()`

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/api-input#metadata

> Dimensions in the response will respect the `page` and `pages` properties of the constructor parameters

To determine the dimensions of each page/frame and therefore the most suitable for the task at hand, call `metadata()` for as many values of `page` as required.

```js
const firstPage = await sharp('sample.tif', { page: 0 }).metadata();
const secondPage = await sharp('sample.tif', { page: 1 }).metadata();
```

**Comment by mbklein** [comment]
Ah, nice. I missed that the constructor worked that way. Thanks for the quick response. If it’s alright with you, I’ll leave this issue open until I have a moment to experiment but I should be able to close it out today.

**Comment by mbklein** [comment]
It turns out I do have a followup question. Is there any reasonable way to call `metadata()` without having the entire image present? The `sharp()` constructor (without an input) is great for creating transformation pipelines, but I haven't yet been able to find a way to call `metadata()` when the source is a readable stream.

**Comment by lovell** [comment]
```js
const writableStream = sharp({ page: 0 });
aReadableStream.pipe(writableStream);
const firstPage = await writableStream.metadata();
```

**Comment by mbklein** [comment]
Thank you!
