### ISSUE TITLE
Wasm version of sharp

### ISSUE THREAD

**Issue by delebash** [lovell/sharp#3596]
### What are you trying to achieve?

Ability to use sharp via webrowser

### When you searched for similar feature requests, what did you find that might be related?

https://github.com/lovell/sharp/issues/1476

libvips has had a wasm version for some time now.  Since https://github.com/kleisauke/wasm-vips is now available does this make it easier to turn sharp into a wasm version?

**Comment by lovell** [comment]
Please see #3336
