### ISSUE TITLE
Merge Alpha Channels

### ISSUE THREAD

**Issue by sops21** [lovell/sharp#3597]
### What are you trying to achieve?
I'm trying to combine 2 alpha channels. One from the original .png image and one from a .png mask I created and then apply the updated Alpha channel to the original image

### When you searched for similar issues, what did you find that might be related?
I believe that .joinChannel should be used 

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```javascript
 sharp("inputImageWithAlpha.png").extractChannel("alpha")
.toBuffer()
  .then(maskOne =>
    sharp("alphaMask.png")
      .extractChannel("alpha")
      .toBuffer()
      .then(mask =>
        sharp("inputImageWithAlpha.png")
          .removeAlpha()
          .toBuffer()
          .then(image =>
            sharp(image)
              .joinChannel([mask, maskOne])
              .toFile("output")
              .catch((e) => {
                console.log('Sharp Error')
                console.log(e);
            })
          )
      ).catch((e) => {
                    console.log('Sharp Error')
                    console.log(e);
                })
  ).catch((e) => {
                    console.log('Sharp Error')
                    console.log(e);
                });
```

### Please provide sample image(s) that help explain this question
Output:
[![HhYieTl.th.png](https://iili.io/HhYieTl.th.png)](https://freeimage.host/i/HhYieTl)
alphaMask:
 [![HhYiwvf.th.png](https://iili.io/HhYiwvf.th.png)](https://freeimage.host/i/HhYiwvf)
inputImageWithAlpha:
 [![HhYiNp4.th.png](https://iili.io/HhYiNp4.th.png)](https://freeimage.host/i/HhYiNp4)
Desired Output: 
[![HhYtQB2.th.png](https://iili.io/HhYtQB2.th.png)](https://freeimage.host/i/HhYtQB2)

**Comment by lovell** [comment]
Did you see `composite()`? You should be able to composite `mask` and `maskOne` before then using the result with `joinChannel()`.

https://sharp.pixelplumbing.com/api-composite

**Comment by lovell** [comment]
@sops21 Were you able to make any progress with this?
