### ISSUE TITLE
aws s3 write stream

### ISSUE THREAD

**Issue by fly2mun** [lovell/sharp#3598]
I used google cloud storage write stream method is 

remoteWriteStream = await storage.bucket(bucketName).file(fileName).createWriteStream();

sharp(srcBucketData).resize(300, 300, {fit: sharp.fit.inside, withoutEnlargement: true}).pipe(remoteWriteStream);

but aws s3 is not working.

Please let me know if there are any samples available in aws s3 storage

**Comment by lovell** [comment]
The unit tests include Stream-based input and output:

https://github.com/lovell/sharp/blob/844deaf48060d60eb05f3f61c567282e3611f12a/test/unit/io.js#L135-L151

This might be a question better suited to a site such as StackOverflow, for which you'll need to provide more information than "not working".

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
