### ISSUE TITLE
AWS Lambda module not found

### ISSUE THREAD

**Issue by bbobek** [lovell/sharp#3599]
Some answers to question below, but here is my error. I followed the AWS Lambda install guide. I deployed using serverless framework / yaml file which creates a sharp layer. I see my layer supporting x86, I see the sharp zip in S3. I'm really stumped. What have I done wrong?

CLOUDWATCH LOG:
2023-03-23T15:17:10.527Z	undefined	ERROR	Uncaught Exception 	{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'sharp'\nRequire stack:\n- /var/task/node_modules/join-images/lib/main.js\n- /var/task/src/utils/generate-grid.js\n- /var/task/src/prompt/create-image.js\n- /var/task/src/receiver.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'sharp'",
        "Require stack:",
        "- /var/task/node_modules/join-images/lib/main.js",
        "- /var/task/src/utils/generate-grid.js",
        "- /var/task/src/prompt/create-image.js",
        "- /var/task/src/receiver.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:996:17)",
        "    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1031:21)",
        "    at async start (file:///var/runtime/index.mjs:1194:23)",
        "    at async file:///var/runtime/index.mjs:1200:1"
    ]
}

DEPLOY LOG:
sls deploy --verbose
Running "serverless" from node_modules

Deploying samsung-publicis-dall-e to stage dev (us-east-1)

Packaging
Excluding development dependencies for function "receiver"
Excluding development dependencies for layer "sharp"
Excluding development dependencies for service package
Warning: Function sender has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 30 seconds.
Retrieving CloudFormation stack
Uploading
Uploading CloudFormation file to S3
Uploading State file to S3
Uploading service samsung-publicis-dall-e.zip file to S3 (56.31 MB)
Uploading service receiver.zip file to S3 (47.6 MB)
Uploading service sharp.zip file to S3 (272 B)
Updating CloudFormation stack
Creating new change set
Waiting for new change set to be created
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Executing created change set
  UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - samsung-publicis-dall-e-dev
  UPDATE_IN_PROGRESS - AWS::Lambda::Function - ApprovalsLambdaFunction
  UPDATE_IN_PROGRESS - AWS::Lambda::Function - SenderLambdaFunction
  UPDATE_IN_PROGRESS - AWS::Lambda::LayerVersion - SharpLambdaLayer
  UPDATE_IN_PROGRESS - AWS::Lambda::LayerVersion - SharpLambdaLayer
  UPDATE_COMPLETE - AWS::Lambda::LayerVersion - SharpLambdaLayer
  UPDATE_COMPLETE - AWS::Lambda::Function - ApprovalsLambdaFunction
  UPDATE_COMPLETE - AWS::Lambda::Function - SenderLambdaFunction
  UPDATE_IN_PROGRESS - AWS::Lambda::Function - ReceiverLambdaFunction
  CREATE_IN_PROGRESS - AWS::Lambda::Version - SenderLambdaVersionec4gldEK7KoQCW1disS3eEmmYZvZN8n0QppZgEipCB4
  CREATE_IN_PROGRESS - AWS::Lambda::Version - ApprovalsLambdaVersionQxB0JHkCqKAxBFyBSQ2LqzSVgTrxVip96wey93U
  CREATE_IN_PROGRESS - AWS::Lambda::Version - SenderLambdaVersionec4gldEK7KoQCW1disS3eEmmYZvZN8n0QppZgEipCB4
  CREATE_COMPLETE - AWS::Lambda::Version - SenderLambdaVersionec4gldEK7KoQCW1disS3eEmmYZvZN8n0QppZgEipCB4
  CREATE_IN_PROGRESS - AWS::Lambda::Version - ApprovalsLambdaVersionQxB0JHkCqKAxBFyBSQ2LqzSVgTrxVip96wey93U
  CREATE_COMPLETE - AWS::Lambda::Version - ApprovalsLambdaVersionQxB0JHkCqKAxBFyBSQ2LqzSVgTrxVip96wey93U
  CREATE_IN_PROGRESS - AWS::ApiGateway::Deployment - ApiGatewayDeployment1679583724340
  CREATE_IN_PROGRESS - AWS::ApiGateway::Deployment - ApiGatewayDeployment1679583724340
  CREATE_COMPLETE - AWS::ApiGateway::Deployment - ApiGatewayDeployment1679583724340
  UPDATE_COMPLETE - AWS::Lambda::Function - ReceiverLambdaFunction
  CREATE_IN_PROGRESS - AWS::Lambda::Version - ReceiverLambdaVersionxTyjxb3tvYUlBVJ9XeiVj17DEojAVkhHapgAIOBZM
  CREATE_IN_PROGRESS - AWS::Lambda::Version - ReceiverLambdaVersionxTyjxb3tvYUlBVJ9XeiVj17DEojAVkhHapgAIOBZM
  CREATE_COMPLETE - AWS::Lambda::Version - ReceiverLambdaVersionxTyjxb3tvYUlBVJ9XeiVj17DEojAVkhHapgAIOBZM
  UPDATE_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - samsung-publicis-dall-e-dev
  DELETE_IN_PROGRESS - AWS::ApiGateway::Deployment - ApiGatewayDeployment1679520594155
  DELETE_IN_PROGRESS - AWS::Lambda::LayerVersion - SharpLambdaLayer
  DELETE_SKIPPED - AWS::Lambda::Version - SenderLambdaVersionY0g1wNCQqwlOH3YIPLCkxX35jj9ppbLjOkMoIB0qew
  DELETE_SKIPPED - AWS::Lambda::Version - ApprovalsLambdaVersionPq6wJ0Qgwse8JmOvsQcFbbw5UFG3HuZZP1SEM9LU2Y
  DELETE_SKIPPED - AWS::Lambda::Version - ReceiverLambdaVersionj2C9EAjsrxYVxIkF1rQXpz26VaqfvlKuGDJpuEQ0
  DELETE_COMPLETE - AWS::ApiGateway::Deployment - ApiGatewayDeployment1679520594155
  DELETE_COMPLETE - AWS::Lambda::LayerVersion - SharpLambdaLayer
  UPDATE_COMPLETE - AWS::CloudFormation::Stack - samsung-publicis-dall-e-dev
Retrieving CloudFormation stack
Removing old service artifacts from S3

✔ Service deployed to stack samsung-publicis-dall-e-dev (133s)

endpoint: POST - https://8m5c5sen18.execute-api.us-east-1.amazonaws.com/dev/prompt
functions:
  sender: samsung-publicis-dall-e-dev-sender (56 MB)
  receiver: samsung-publicis-dall-e-dev-receiver (48 MB)
  approvals: samsung-publicis-dall-e-dev-approvals (56 MB)
layers:
  sharp: arn:aws:lambda:us-east-1:945515760670:layer:sharp:4

Stack Outputs:
  ReceiverLambdaFunctionQualifiedArn: arn:aws:lambda:us-east-1:945515760670:function:samsung-publicis-dall-e-dev-receiver:8
  ApprovalsLambdaFunctionQualifiedArn: arn:aws:lambda:us-east-1:945515760670:function:samsung-publicis-dall-e-dev-approvals:13
  SharpLambdaLayerHash: 20e069e1d0603266dd8dbfb0c3c3adc08300d6b2
  SharpLambdaLayerQualifiedArn: arn:aws:lambda:us-east-1:945515760670:layer:sharp:4
  SharpLambdaLayerS3Key: serverless/samsung-publicis-dall-e/dev/1679583734344-2023-03-23T15:02:14.344Z/sharp.zip
  SenderLambdaFunctionQualifiedArn: arn:aws:lambda:us-east-1:945515760670:function:samsung-publicis-dall-e-dev-sender:15
  ServiceEndpoint: https://8m5c5sen18.execute-api.us-east-1.amazonaws.com/dev
  ServerlessDeploymentBucketName: samsung-publicis-dall-e-serverlessdeploymentbuck-hbnwemnocylo

3 deprecations found: run 'serverless doctor' for more details

+++++

- [x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

- [] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

I was using 31.3 but got a peer dependency error with node_modules/join-images so I matched the root version with that one. Note that I was previously using the latest and receiving the same error, so I re-installed and downgraded this time to see if that would help. It didn't

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

  System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 206.98 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - /usr/local/bin/node
    npm: 8.19.3 - /usr/local/bin/npm
  npmPackages:
    sharp: ^0.30.7 => 0.30.7

**Comment by lovell** [comment]
> I see the sharp zip in S3. I'm really stumped. 

Is this the same file as referenced in the log here?

>  Uploading service sharp.zip file to S3 (272 B)

If so, I suspect this should be bigger than 272 bytes.

**Comment by bbobek** [comment]
Yes! That zip file only contains the readme.md file. So serverless is not packaging the file properly. I tried to package manuallly independent of deploying but it still just had the readme file.

**Comment by jaman99** [comment]
aws lambda need layers FOLDER NAME  (  nodejs ) than zip it upload on lambda layers  . if your folder name not nodejs its not running on aws lambda layers .
