### ISSUE TITLE
CRITICAL - sharp: Installation error: certificate has expired

### ISSUE THREAD

**Issue by AlbinoGeek** [lovell/sharp#3601]
## Possible install-time or require-time problem

- [x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

```

npm info run sharp@0.32.0 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

> sharp@0.32.0 install
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.2/libvips-8.14.2-win32-x64.tar.br
sharp: Installation error: certificate has expired
sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm info run sharp@0.32.0 install { code: 1, signal: null }
npm notice
npm notice New minor version of npm available! 9.5.1 -> 9.6.2
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.2>
npm notice Run `npm install -g npm@9.6.2` to update!
npm notice
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:53:27)
npm verb stack     at ChildProcess.emit (node:events:512:28)
npm verb stack     at maybeClose (node:internal/child_process:1098:16)
npm verb stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
npm verb pkgid sharp@0.32.0
npm verb cwd C:\Users\Belial\Documents\GitHub\sharp
npm verb Windows_NT 10.0.19045
npm verb node v19.8.1
npm verb npm  v9.5.1
npm ERR! code 1
npm ERR! path C:\Users\Belial\node_modules\sharp
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm verb exit 1
npm verb unfinished npm timer reify 1679691377894
npm verb unfinished npm timer reify:build 1679691378967
npm verb unfinished npm timer build 1679691378968
npm verb unfinished npm timer build:deps 1679691378968
npm verb unfinished npm timer build:run:install 1679691378975
npm verb unfinished npm timer build:run:install:node_modules/sharp 1679691378975
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Belial\AppData\Local\npm-cache\_logs\2023-03-24T20_56_17_847Z-debug-0.log

```

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Windows 10 10.0.19045
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 31.94 GB / 63.92 GB
  Binaries:
    Node: 19.8.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 4.0.0-rc.37 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: ^0.32.0 => 0.32.0
```

### Created in both repos, feel free to close one.

**Comment by AlbinoGeek** [comment]
Possibly should be: https://github.com/lovell/sharp-libvips/issues/179

**Comment by 7azin** [comment]
facing the same

Mar 24 09:59:34 PM  sharp: Installation error: certificate has expired
Mar 24 09:59:34 PM  sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
Mar 24 09:59:36 PM  npm ERR! code ELIFECYCLE

**Comment by andreivcodes** [comment]
This is probably causing it: https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/

**Comment by amilich** [comment]
Also experiencing

**Comment by MikeRippon** [comment]
Was experiencing, but looks like it might either be fixed or intermittent? `objects.githubusercontent.com` was serving up an expired certificate, but seems ok now?

![image](https://user-images.githubusercontent.com/9319632/227641816-b3ac398d-5cbd-4f9b-a989-00424ce11ff3.png)

**Comment by liamlows** [comment]
Can confirm that it is fixed on my end, just opened an issue as well. Looks like Github might have messed up their cert rotation or something.
![image](https://user-images.githubusercontent.com/1365914/227642523-a4ded791-48d0-40ba-9d34-540f4a0aeba3.png)

**Comment by lovell** [comment]
https://www.githubstatus.com/incidents/x7njwb481j9b
