### ISSUE TITLE
Expired certificate for tar download of package prevents install

### ISSUE THREAD

**Issue by liamlows** [lovell/sharp#3602]
## The Issue

Apologies for not following the traditional format of this issue but it wouldn't make sense for the problem...

We are attempting to upgrade our sharp package to latest while using yarn pnp. When attempting to build the package during installation we get the following error:

`sharp@npm:0.32.0 couldn't be built successfully (exit code 1)`

Looking at the logs for this error we see:

```
# This file contains the result of Yarn building a package (sharp@npm:0.32.0)
# Script name: install

sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.2/libvips-8.14.2-darwin-arm64v8.tar.br
sharp: Installation error: certificate has expired
sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
```

After further investigation when browsing to https://github.com/lovell/sharp-libvips/releases/download/v8.14.2/libvips-8.14.2-darwin-arm64v8.tar.br it appears the certificate is expired. Yarn will not install a package that has an expired certificate. Not sure what the best option is here.

___

## Possible install-time or require-time problem

- [x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### Is this a problem with filesystem permissions?

No this issue is not with filesystem permissions...

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

N/A, I am using yarn...

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.00 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 3.5.0 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
```

**Comment by liamlows** [comment]
Closing issue, randomly disappeared after a few minutes of retrying. Apologies.

**Comment by nick-romano** [comment]
same issue happening in remote CI env. for me

**Comment by collinmesser** [comment]
Same issue happening for us as well.

**Comment by liamlows** [comment]
Haha a lot of people with the same problem, looks like a cert rotation took too long or something

**Comment by lovell** [comment]
https://www.githubstatus.com/incidents/x7njwb481j9b

**Comment by pengfeiw** [comment]
Same issue happening.
![image](https://github.com/lovell/sharp/assets/37898750/082009e2-bd03-44a8-b3a7-056dc607007a)

**Comment by lovell** [comment]
@pengfeiw https://github.com/cnpm/cnpm/issues/439
