### ISSUE TITLE
Resize svg image content lost

### ISSUE THREAD

**Issue by fenrir-lijingxin** [lovell/sharp#3603]
### What are the steps to reproduce?

1. I have an image in s3 ：http://serverlessimageresizedev-imagebucket-112n6nuaxf6l4.s3-website-ap-northeast-1.amazonaws.com/yuantu.svg
2. Resizes images ：http://serverlessimageresizedev-imagebucket-112n6nuaxf6l4.s3-website-ap-northeast-1.amazonaws.com/423x423/yuantu.svg
3. The problem only occurs when the image pixels in the svg are super large
4. Sometimes this problem is reproducible, sometimes not. I'm confused about this

### What is the expected behaviour?

Image content is not lost

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

'use strict';

const AWS = require('aws-sdk');
const S3 = new AWS.S3({
  signatureVersion: 'v4',
});
const Sharp = require('sharp');

const BUCKET = process.env.BUCKET;
const URL = process.env.URL;
const ALLOWED_DIMENSIONS = new Set();

if (process.env.ALLOWED_DIMENSIONS) {
  const dimensions = process.env.ALLOWED_DIMENSIONS.split(/\s*,\s*/);
  dimensions.forEach((dimension) => ALLOWED_DIMENSIONS.add(dimension));
}

exports.handler = function(event, context, callback) {
  const key = event.queryStringParameters.key;
  const match = key.match(/((\d+)x(\d+))\/(.*)/);
  const dimensions = match[1];
  const width = parseInt(match[2], 10);
  const height = parseInt(match[3], 10);
  const originalKey = match[4];

  if(ALLOWED_DIMENSIONS.size > 0 && !ALLOWED_DIMENSIONS.has(dimensions)) {
     callback(null, {
      statusCode: '403',
      headers: {},
      body: '',
    });
    return;
  }

  S3.getObject({Bucket: BUCKET, Key: originalKey}).promise()
    .then(data => Sharp(data.Body)
      .resize(width, height)
      .toFormat('png')
      .toBuffer()
    )
    .then(buffer => S3.putObject({
        Body: buffer,
        Bucket: BUCKET,
        ContentType: 'image/png',
        Key: key,
      }).promise()
    )
    .then(() => callback(null, {
        statusCode: '301',
        headers: {'location': `${URL}/${key}`},
        body: '',
      })
    )
    .catch(err => callback(err))
}

### Please provide sample image(s) that help explain this problem

http://serverlessimageresizedev-imagebucket-112n6nuaxf6l4.s3-website-ap-northeast-1.amazonaws.com/yuantu.svg

**Comment by lovell** [comment]
Hi, I cannot reproduce this. I assume you're using AWS Lambda. Are you sure you're providing enough memory to your function?

**Comment by lovell** [comment]
Please can you provide complete, standalone (e.g. no networking, no AWS services) code that allows someone else to consistently reproduce this problem locally.
