### ISSUE TITLE
Is heif supported in AWS Lambda arm64?

### ISSUE THREAD

**Issue by ntekka** [lovell/sharp#3604]
## Question about an existing feature
I'm using AWS Lambda Arm64 architecture and have ran into this issue when processing heif images, which works fine in 86_x64.
Here is the error message: 
heif: Unsupported feature: Unsupported codec (4.3000)

Please help me figure out possible solutions without going back to 86_x64 arch.

### What are you trying to achieve?
Process HEIF files in Arm64 AWS Lambda architecture.

### When you searched for similar issues, what did you find that might be related?
Found nothing mentioning HEIF and Arm64 support.

**Comment by lovell** [comment]
The prebuilt binaries provided for both x64 and arm64 support AVIF (HEIF+AV1) images. None of the prebuilt binaries support patent-encumbered HEIC (HEIF+HEVC) images.

If your question is about the former, AVIF, then please can you provide a sample image that works on x64 but not arm64.

**Comment by ntekka** [comment]
I see, thank you for breaking it down like that, it makes much more sense. I guess I'm out of luck if it is HEIF+HEVC, but do you know if there is any possible workaround to decode HEIC?

**Comment by lovell** [comment]
https://github.com/lovell/sharp/issues/2000#issuecomment-756162296
