### ISSUE TITLE
Gamma filter is not applied on 16-bit images

### ISSUE THREAD

**Issue by SaraKaminska** [lovell/sharp#3606]
### Is this a possible bug in a feature of sharp, unrelated to installation?
- [X] Running `npm install sharp` completes without error.
- [X] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?
- [X] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 4.98 GB / 15.75 GB
Binaries:
    Node: 19.6.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.4.0 - C:\Program Files\nodejs\npm.CMD
npmPackages:
    sharp: ^0.32.0 => 0.32.0

### What are the steps to reproduce?
1. Read a 16-bit PNG image with Sharp.
2. Apply the gamma filter with any value, the default value also doesn't work as expected.
4. Apply toColorspace('grey16') to ensure the space is maintained.
5. Save the image to file. 

### What is the expected behavior?
The expected behavior is that the gamma filter is applied correctly and the output image is changed in the expected way. Instead applying gamma doesn't do anything to the image. No change can be observed. 
Something that I noticed is that if applying a modulate filter with any option before applying the gamma filter, a change can be observed.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem
```
const sharp = require("sharp");

const adjusted = sharp('16-bit.png')
  .gamma(3.0)
  .toColorspace('grey16')
  .toFile('gamma-16-bit.png')
```

### Please provide sample image(s) that help explain this problem
Original
![16-bit](https://user-images.githubusercontent.com/70136442/228498311-c1910446-0217-49f5-90e5-d7cdd711f7b8.png)

Output
![gamma-16-bit](https://user-images.githubusercontent.com/70136442/228498795-3f319c8e-3c4b-4c2d-8f3c-54f3efe0c6ad.png)

**Comment by lovell** [comment]
Hi, did you see the `gammaOut` parameter?

https://sharp.pixelplumbing.com/api-operation#gamma

To _change_ the gamma of the output, as opposed to temporarily adjusting it whilst resizing to correct for non-linear light, then you'll need to provide both input and output values, for example `gamma(2, 3)`.

**Comment by SaraKaminska** [comment]
Now it works as expected, thank you very much for your help! :)
