### ISSUE TITLE
Trim transparent pixels

### ISSUE THREAD

**Issue by acojocaru** [lovell/sharp#3608]
I have an image with transparent edges that I want to trim. `trim()` works perfectly if the top left pixel is transparent, but it does not work if it's not. I've tried passing it different parameters, but could not find a value that would work.

What value should I pass to `trim()` so that it always trims transparent edges, even if the top left pixel is not transparent?

**Comment by acojocaru** [comment]
@lovell Sure, here's a sample image:
![transparency-test](https://user-images.githubusercontent.com/9514608/230325499-8cfe7980-271a-4214-ac42-a4611f17de6d.png)

The transparent sections from right and down are not trimmed with this:
```
sharp(fs.readFileSync("image.png")).trim().toFile("trimmed.png");
```

What value should I pass to `trim()` so that it removes those transparent sections?

**Comment by lovell** [comment]
The `trim()` operation accepts a `background` parameter and the transparent area of this sample image has fully-transparent black pixel values, so the following should work:
```js
.trim({ background: '#00000000' })
```

**Comment by acojocaru** [comment]
That worked, thanks! Also, thanks for this amazing library and for your prompt support of it!
