### ISSUE TITLE
Animated GIF becomes up to 6x larger in size

### ISSUE THREAD

**Issue by EvHaus** [lovell/sharp#3610]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: macOS 13.3
    CPU: (8) arm64 Apple M1 Pro
    Memory: 52.78 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  npmPackages:
    sharp: 0.32.0 => 0.32.0
```

### What are the steps to reproduce?

Take the animated GIF attached below and process it through `sharp` with:

```js
sharp(inputFile, {animated: true}).gif({dither: 0}).toFile(filepath);
```

### What is the expected behaviour?

I'm hoping to use `sharp` for automating static web image optimizations to help reduce the file size of my files. It's working great for PNG and JPG files, but for animated GIFs I can't find any setting that makes the images smaller (or even the same size). They all come out WAY bigger than the source images.

I'm expecting the generated GIF to be no bigger (ideally smaller) in size than the original -- which is 13kb.  However, the output file is 76kb -- almost 6 times bigger in size.

I've tried playing around with `dither`, `interFrameMaxError` and `interPaletteMaxError` settings, but they seem to have no effect on the output file size. Am I doing something wrong, or was `sharp` not designed to optimize `.gif` files?

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

See above.

### Please provide sample image(s) that help explain this problem

![add-epic](https://user-images.githubusercontent.com/226640/229247694-accb4397-9c89-4664-8c20-2f45a7f0f653.gif)

**Comment by lovell** [comment]
This GIF image contains the comment "Optimized using ezgif.com", which usually means it was generated by a third party service that wraps the use of `gifsicle --optimize=3 ...` at the command line.

It appears to use a global 256 colour palette but most frames then define their own local palette of 4, 8, or 16 colours. Reducing the overall number of colours and preventing the use dithering will help here.

For example, the output file site when using `.gif({ colours: 16, dither: 0 })` is 14672 bytes.

![](https://user-images.githubusercontent.com/210965/229278885-80abb284-aa1d-4d7a-863d-ea89caf44b99.gif)

**Comment by EvHaus** [comment]
Thanks for the quick response @lovell. I think I was naively looking for a configuration solution that we could apply as a blanket statement across all our assets and have them come out optimized, but it sounds like with GIFs it might be more complex than that. I don't think we can simply set `colours: 16` for everything and expect all GIFs to come out both optimized and looking good.

Does `sharp` support an optimization strategy where palettes can be set per frame? Something similar to `gifsicle --optimize=3`?

**Comment by lovell** [comment]
Please see https://github.com/libvips/libvips/issues/2576 for some previous discussion about this. The summary is that libvips should ideally be as fast as possible whilst not producing images that are too big. For example, all the GIFs you see on Shopify-powered web sites use the same approach as sharp.

Tools such as `gifsicle` will "brute-force" their way through a lot of configuration combinations (and therefore CPU time) until they find the smallest output file size. Perhaps you could you create your own wrapper that attempts this?

In my experience, the most optimised animated GIF image is no longer a GIF but rather a video.
