### ISSUE TITLE
WMF and EMF support

### ISSUE THREAD

**Issue by evgenDer** [lovell/sharp#3613]
### What are you trying to achieve?

It will be gratefull adding conversion from svg to wmf and emf

### What would you expect the API to look like?

.toWmf()
.toEmf()

### Please provide sample image(s) that help explain this feature

Convert img to wmf/emf

**Comment by lovell** [comment]
Thanks for the suggestion but this is probably the wrong tool for a vector to vector conversion. Perhaps try `inkscape` at the command line for this kind of feature.
