### ISSUE TITLE
XML parse error

### ISSUE THREAD

**Issue by NugramN** [lovell/sharp#3614]
# Issue

## Possible bug
![Untitled](https://user-images.githubusercontent.com/44146448/229773591-e061c2e0-0f69-45b3-a2c1-72ab0d738485.png)

### Is this a possible bug in a feature of sharp, unrelated to installation?

Yes

- [x]  Running `npm install sharp` completes without error.
- [x]  Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

Yes

- [x]  I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What are the steps to reproduce?

Convert svg image with xmlns namespace. If namespace is not correct, you will get error

### What is the expected behaviour?

Error is not occurred. Not correct option is skipped.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

`<svg xmlns="custom"></>`

### Please provide sample image(s) that help explain this problem

Every image where xmlns is not url or not empty

Sometimes images can be not correct formatting. I think it’s better to skip this error than stopping the conversion.

**Comment by NugramN** [comment]
Hello @lovell,

Thank you for the response, but sometimes user provides incorrect params. 

Do you have an opportunity to handle this error?

Thank you in advance for response

**Comment by lovell** [comment]
If you suspect that user-provided XML input might be invalid then you'll need to verify/canonicalise it first.

**Comment by NugramN** [comment]
Yes, I got your point about parsing and removing of the file, but, unfortunately, it may cause performance reduce
