### ISSUE TITLE
jxlsave_buffer error on Mac when try compress into jxl

### ISSUE THREAD

**Issue by wacdev** [lovell/sharp#3617]
❯ ./civitai/lib/getimg.js
(node:4083989) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[Error: VipsOperation: class "jxlsave_buffer" not found]

❯ fd libvips --no-ignore -H
node_modules/.pnpm/sharp@0.32.0/node_modules/sharp/install/libvips.js
node_modules/.pnpm/sharp@0.32.0/node_modules/sharp/lib/libvips.js
node_modules/.pnpm/sharp@0.32.0/node_modules/sharp/src/libvips
node_modules/.pnpm/sharp@0.32.0/node_modules/sharp/vendor/8.14.2/linux-x64/lib/libvips-cpp.so.42

❯ cat /etc/issue
Ubuntu 22.04.2 LTS \n \l

❯ cat package.json|rg sharp
    "sharp": "^0.32.0",

**Comment by wacdev** [comment]
the same error on mac m2
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/127726508/230108230-13667891-27ed-414d-b64d-042f70c3cd58.png">

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/api-output#jxl

> This feature is experimental, please do not use in production systems.
> Requires libvips compiled with support for libjxl. The prebuilt binaries do not include this

Are you using a globally-installed libvips compiled with support for libjxl?

**Comment by wacdev** [comment]
<img width="1865" alt="image" src="https://user-images.githubusercontent.com/127726508/230260444-e5a34a9e-d810-43f3-98f6-9f08b1384460.png">
i complied libvips 8.15.0

pkg-config --modversion vips-cpp can see , as image above

but sharp not use this

I write 
```
 "config": {                                                                                 
    "libvips": "8.15.0"                                                                        
  }
```
in package.json , it not work too

**Comment by wacdev** [comment]
finnaly I make this work

```
export npm_package_config_libvips=8.15.0
rm -rf node_modules
pnpm i
```

**Comment by wacdev** [comment]
I do the same thing on my m2 mac, but it's not work ....

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/127726508/230272101-f248493b-e84c-4452-a092-a0c4fdaa8f77.png">

**Comment by lovell** [comment]
If you're using a globally-installed libvips you do not need to set `npm_package_config_libvips`. That is only for those creating their own local, statically-compiled tarballs, which you do not appear to be doing (and I would generally recommend against doing so).

You also appear to have compiled the latest, unstable `master` branch of libvips. I recommend you use one of the tagged releases, the latest being v8.14.2.

**Comment by wacdev** [comment]
i tryed compile 18.4.2 on mac and installed
the same error
sharp seems not use global libvips on mac

**Comment by lovell** [comment]
Please provide the complete output of `npm install --verbose --foreground-scripts sharp` when run in an empty directory.

**Comment by wacdev** [comment]
```
npm verb cli /Users/z/.local/share/rtx/installs/nodejs/19.8.1/bin/node /Users/z/.local/share/rtx/installs/nodejs/19.8.1/bin/npm
npm info using npm@9.5.1
npm info using node@v19.8.1
npm verb title npm install sharp
npm verb argv "install" "--loglevel" "verbose" "--foreground-scripts" "sharp"
npm verb logfile logs-max:10 dir:/Users/z/.npm/_logs/2023-04-08T06_19_32_430Z-
npm verb logfile /Users/z/.npm/_logs/2023-04-08T06_19_32_430Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/sharp 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/semver 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/node-addon-api 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tunnel-agent 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tar-fs 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/prebuild-install 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/simple-get 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 10ms (cache hit)
npm verb stack TypeError: Cannot read properties of null (reading 'matches')
npm verb stack     at Link.matches (/Users/z/.local/share/rtx/installs/nodejs/19.8.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1119:41)
npm verb stack     at Link.canDedupe (/Users/z/.local/share/rtx/installs/nodejs/19.8.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1073:15)
npm verb stack     at PlaceDep.pruneDedupable (/Users/z/.local/share/rtx/installs/nodejs/19.8.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:426:14)
npm verb stack     at new PlaceDep (/Users/z/.local/share/rtx/installs/nodejs/19.8.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:278:14)
npm verb stack     at /Users/z/.local/share/rtx/installs/nodejs/19.8.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:943:31
npm verb stack     at Array.map (<anonymous>)
npm verb stack     at [buildDepStep] (/Users/z/.local/share/rtx/installs/nodejs/19.8.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:943:8)
npm verb stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm verb stack     at async Arborist.buildIdealTree (/Users/z/.local/share/rtx/installs/nodejs/19.8.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:207:7)
npm verb stack     at async Promise.all (index 1)
npm verb cwd /Users/z/wac.tax/pkg/bot
npm verb Darwin 22.3.0
npm verb node v19.8.1
npm verb npm  v9.5.1
npm ERR! Cannot read properties of null (reading 'matches')
npm verb exit 1
npm verb unfinished npm timer reify 1680934772450
npm verb unfinished npm timer reify:loadTrees 1680934772451
npm verb unfinished npm timer idealTree:buildDeps 1680934772870
npm verb unfinished npm timer idealTree:node_modules/sharp 1680934772892
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/z/.npm/_logs/2023-04-08T06_19_32_430Z-debug-0.log

```

**Comment by wacdev** [comment]
it seems bug of pnpm , I try rm -rf node_modules , then use npm i, everything is ok
