### ISSUE TITLE
Outputted webP is larger than the original JPEG by a lot

### ISSUE THREAD

**Issue by ohabash** [lovell/sharp#3618]
### What are you trying to achieve?
compressed WebP

I am compressing a JPEG: `await sharp(inputImgPath).webp({ lossless: true }).toFile(compressedFilePath)`

but when i compare image sizes it appears the image is larger by a lot. I am new to image compression so i wonder if there is a better way to get a smaller webp than the original JPEG without loosing quality.

```
{
    "inSize": 175047,
    "outSize": 729520
}
```

here is the sample image ive been using 
https://www.decorilla.com/online-decorating/wp-content/uploads/2021/09/Contemporary-conference-room-by-Decorilla-office-interior-design-services-designer-Courtney-B.jpeg

**Comment by lovell** [comment]
The JPEG format is lossy, so the use of (the default) lossy WebP would make sense, especially for photographic images.

Lossless WebP is generally suitable for line art and diagrams, and not for photographic images.

You can use the `quality` setting to control how lossy these formats are.

If you're new to image compression, please see https://web.dev/learn/images/

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
