### ISSUE TITLE
Creating image from background color with transparent alpha channel loses alpha value

### ISSUE THREAD

**Issue by mrfigg** [lovell/sharp#3619]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Windows 10 10.0.19044
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 52.40 GB / 63.91 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.4.1 - C:\Program Files\nodejs\npm.CMD
```

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```javascript
const sharp = require('sharp')

;(async () => {
  // A transparent background color
  let color = {
    r: 255,
    g: 0,
    b: 0,
    alpha: 126,
  }

  // Create image
  let image = await sharp({
    create: {
      width: 100,
      height: 100,
      channels: 4,
      background: color,
    },
  }).png()

  // Output has an alpha channel but is not transparent
  await image.toFile('output.png')

  // Workaround
  image = await sharp(
    await image
      .removeAlpha()
      .ensureAlpha(color.alpha / 255)
      .toBuffer()
  )

  // Expected output has an alpha channel and is transparent
  await image.toFile('expected-output.png')
})()
```

### Please provide sample image(s) that help explain this problem

`output.png`
![output](https://user-images.githubusercontent.com/36649520/230535015-ab356af3-12b0-4fa4-91bd-16c9e9f8e351.png)

`expected-output.png`
![expected-output](https://user-images.githubusercontent.com/36649520/230535020-b07d6fc2-0e95-4fd7-ae67-659b2574d340.png)

**Comment by acojocaru** [comment]
Have you tried setting `alpha: 126 / 255`? That works for me. It appears that alpha must be between 0 and 1. I could not find this documented anywhere, but this is how the color package sets it: https://github.com/Qix-/color/blob/master/index.js#L107

(I'm not the library author, so take my suggestion with a grain of salt.)

**Comment by lovell** [comment]
>  I hope it gets added to the color modules documentation at some point

If you're able, I'm sure a PR to add this to the upstream documentation would be very welcome - please see https://github.com/Qix-/color/issues/181
