### ISSUE TITLE
Unhandled rejection Error on input buffers

### ISSUE THREAD

**Issue by rorph** [lovell/sharp#362]
Hello,

I'm processing images that could be potentially broken but it's impossible to properly handle invalid images. Apparently error is comming from libvips, there's no error events nor exception thrown, here's some code that will mimic the error: [http://pastebin.com/d5D1ZMgS](http://pastebin.com/d5D1ZMgS)

This will trigger a console.warn with :
> Unhandled rejection Error: Input buffer contains unsupported image format at Error (native)

I am missing something? Valid image buffers process just fine.

**Comment by lovell** [comment]
Ola Rodrigo,

`then` suggests you're using Promise-based behaviour, for which `catch` is the expected error handling technique. Perhaps try something like:

```javascript
sharp(body)
  .metadata()
  .then(function(info) {
    console.log('Info', info);
  })
  .catch(function(err) {
    console.log('Invalid image returned');
  });
 ```

Tudo bem?

**Comment by rorph** [comment]
Tudo bem,

Indeed that was the issue

thanks :)

**Comment by lovell** [comment]
De nada.
