### ISSUE TITLE
Extract an image or resizing it the metadata is not updated only in new instance for animated webp image.

### ISSUE THREAD

**Issue by lctcharly** [lovell/sharp#3623]
Hello team, I hope you are doing well.

I'm facing some problems with the metadata after calling the extract function, seems the metadata is not updated, at least when we create a Sharp instance from the image(width, height, pageHeight).

Example:
```
    this.options = {
      width: crop.width,
      height: crop.height,
      left: crop.x_axis,
      top: crop.y_axis
    };

    await this
      .image
      .extract(this.options);

//    console.info('this.image.metadata()', await this.image.metadata());
this.image.metadata() {
  format: 'webp',
  width: 400,
  height: 4800,
  space: 'srgb',
  channels: 4,
  depth: 'uchar',
  isProgressive: false,
  pages: 12,
  pageHeight: 400,
  loop: 0,
  delay: [
    70, 70, 70, 70, 70,
    70, 70, 70, 70, 70,
    70, 70
  ],
  hasProfile: false,
  hasAlpha: true
}

// console.info('new Instance', await sharp(await this.image.toBuffer(), {animated: true}).metadata())
new Instance {
  format: 'webp',
  size: 53014,
  width: 250,
  height: 3000,
  space: 'srgb',
  channels: 4,
  depth: 'uchar',
  isProgressive: false,
  pages: 12,
  pageHeight: 250,
  loop: 0,
  delay: [
    70, 70, 70, 70, 70,
    70, 70, 70, 70, 70,
    70, 70
  ],
  hasProfile: false,
  hasAlpha: true
}
```

Is there a possible configuration that helps to reload the metadata instead to create a new Sharp instance?

Thank you, and have a great day!

**Comment by lovell** [comment]
Did you see https://sharp.pixelplumbing.com/api-input#metadata ?

>  It does not take into consideration any operations to be applied to the output image, such as resize or rotate.

**Comment by lctcharly** [comment]
Hello @lovell thanks and good morning!

Regarding your questions, yes, here is an example where I'm getting a `extract_area: bad extract area` error.
**File**: https://mathiasbynens.be/demo/animated-webp

```
const sharp = require('sharp');
const file = 'animated-webp.webp';
imageWebp();

async function imageWebp() {
  let imageInstance = sharp(file, { animated: true }); // Loading a webp image.
  imageInstance.extract({ width: 250, height: 250, left: 75, top: 75 });

  /**
   * Removing the comment for the new instance, we are not getting the exception.
   *
   * Since the new metadata is "updated" after the new instance.
   */
  // imageInstance = sharp(await imageInstance.toBuffer(), { animated: true });

  const { pages, width, pageHeight } = await imageInstance.metadata();
  const frames = [];

  const image = sharp(await imageInstance.png().toBuffer());
  for (let i = 0; i < pages; i++) {
    const frame = image.clone().extract({
      left: 0,
      top: pageHeight * i,
      width: width,
      height: pageHeight
    });

    frames.push(sharp(await frame.toBuffer()));
  }
}

```

It can be fixed using a new instance to load the new metadata from the image result after extract, but I've doubts regarding that.

Since after removing the commented line "//" the image is loaded with the new dimensions/metadata, and it's not generating the exception.

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/api-input#metadata

`metadata()` does not take into consideration any operations to be applied to the output image, and this includes the `extract()` operation.

Your sample code includes a call to `extract()`, which returns a sharp instance for further chaining. Calling `extract()` doesn't perform the extraction, it's only when you request output e.g. via `toBuffer()` that the output image is lazily created. This output can then be passed into `metadata()`.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
