### ISSUE TITLE
Truncated JPGs And Sharp Version

### ISSUE THREAD

**Issue by tomreid76** [lovell/sharp#3624]
## Possible bug

Up to Sharp 0.30.7, a resize on some truncated JPGs would succeed when `{failOn: 'none'}`.  Starting in 0.31.0, these same JPGs now fail, no matter the `failOn` option.

### Is this a possible bug in a feature of sharp, unrelated to installation?

Yes.

### What are the steps to reproduce?

Given the following code, and the attached image, Sharp will result in different outcome between the aforementioned versions. 0.30.7 will succeed and produce output with gray area. 0.31.0 will throw error `VipsJpeg: Premature end of input file`

```js
let config = {
  failOn: 'none',
  sequentialRead: true,
  limitInputPixels: false
};

return sharp(data, config)
  .resize(100,100)
  .withMetadata()
  .jpeg({quality: 85})
  .toBuffer();
```

### What is the expected behavior?

My expectation is successful output. Perhaps this is something that changed in the underlying lib or a conscious change, but it was super-convenience for my preview generation system to product output.

### Please provide sample image(s) that help explain this problem
[venice.jpg.zip](https://github.com/lovell/sharp/files/11226629/venice.jpg.zip)

**Comment by lovell** [comment]
This sample image appears to be corrupted rather than truncated.

```
Corrupt JPEG data: found marker 0xd9 instead of RST5
```
Commit https://github.com/libvips/libvips/commit/df26bd1e46c67ed7745996627ca0d83e5a6d678d might explain why previous versions were able to handle it, but this image is very broken.

**Comment by tomreid76** [comment]
Thank you @lovell. I appreciate the response and the backstory on the change. 

We process ~5 million photos through Sharp a month and get a decent amount like this from the wild. For us, the bug has been a feature. Now that I know it was an intentional change and not a regression I can consider that in future upgrades.

**Comment by lovell** [comment]
Did you see the `unlimited` option? Please be careful when using it with untrusted content as it is possible to craft a JPEG image that generates 10000s of warnings.

https://sharp.pixelplumbing.com/api-constructor

```diff
 let config = {
   failOn: 'none',
+  unlimited: true,
   sequentialRead: true,
   limitInputPixels: false
 };
```
(As an aside, `sequentialRead` is now the default from v0.32.0, so you may be able to remove this.)

**Comment by tomreid76** [comment]
Ahh! I had missed that. Applying that property allows the above image, and others, to succeed in my tests. 

We run these through a Lambda function capped to 30s so worst case it times out and generates an error event.

Thank you for the assist.
