### ISSUE TITLE
Error Install Sharp in Window 11

### ISSUE THREAD

**Issue by elsiosanchez** [lovell/sharp#3627]
I get the same error after cloning my repository and running `yarn`

![image](https://user-images.githubusercontent.com/45974454/232140587-661dd589-a16b-47b1-8217-a4c3e4c99823.png)
I am using version of `node v16.20.0` and `Python 3.10.11`

The question would be what is the version of `node` with which I can work with `sharp` that does not give me a problem in the installation

#### Other relevant information
- Your OS: Windows 11
- Node.js version: v16.20.0
- Python  version:  3.10.11
- Sharp Version: ^0.23.4

**Comment by lovell** [comment]
Please upgrade to the latest version of sharp.

**Comment by elsiosanchez** [comment]
Excuse me, what is the version of node that supports the latest version of sharp?

**Comment by elsiosanchez** [comment]
> Please upgrade to the latest version of sharp.

Excuse me, what is the version of node that supports the latest version of sharp?

**Comment by lovell** [comment]
https://github.com/lovell/sharp/blob/b763801d68f6be945cda0f51a08430daeb47eaea/package.json#L179-L181
