### ISSUE TITLE
Very Large image processing fails with Error: Input image exceeds pixel limit #3628

### ISSUE THREAD

**Issue by mbproj** [lovell/sharp#3629]
## Question about an existing feature
Is there a limit to the image size Sharp can process?

### What are you trying to achieve?
I'm trying reduce the size of an image from say 10000 X 10000 to 2048x2046. Processing fails with below error:
Error: Input image exceeds pixel limit

### When you searched for similar issues, what did you find that might be related?
Not sure on any library handling such a huge images so want to know the upper limit for processing PNG, JPEG using Sharp libs
Tried to google the issue and it redirects to your old posts but without an answer

### Please provide sample image(s) that help explain this question
Try to process the image 1 - 2 GB if available

**Comment by lovell** [comment]
Please see #2373
