### ISSUE TITLE
jp2k: libvips built without JPEG2000 support, even when openjpeg 2.5 is installed in global vips

### ISSUE THREAD

**Issue by joesong168** [lovell/sharp#3631]
'npm install sharp --build-from-source' has been tried

### What are you trying to achieve?

windows 10
nodejs 16.7.0
vips-8.14.1

**Comment by lovell** [comment]
Did you see https://sharp.pixelplumbing.com/install#custom-libvips ?

> The use of a globally-installed libvips is unsupported on Windows

You might be able to copy the "all" variety of DLLs produced/published via https://github.com/libvips/build-win64-mxe into the `build/Release` directory, but I cannot provide any support for this.

**Comment by joesong168** [comment]
May I know why? I also noticed that jp2 api has been removed from sharp document. Are there any license concern in supporting jp2000?

**Comment by lovell** [comment]
It looks like the switch to a new JSDocs parser in commit https://github.com/lovell/sharp/commit/ef849fd63907d937afce0d06b07ae778692ec500 accidentally resulted in the removal of `jp2` from the docs. I've fixed this in commit https://github.com/lovell/sharp/commit/afed876f9078d032660064dce6d5a1e79dc98995 - thanks for reporting.
