### ISSUE TITLE
Unable to write GPS Exif Metadata

### ISSUE THREAD

**Issue by RollingSquirrel** [lovell/sharp#3633]
### What are you trying to achieve?

I am trying to add geo location data to an existing image without this information.
One example is taking a screenshot and adding exif data with the `withMetadata` method.

### When you searched for similar issues, what did you find that might be related?

I have found several discussions and issues about the metadata and the development from using other libraries to using sharp itself.
This allowed me to find several samples that work with common exif data, e.g. `Make` or `Model`. 
I have found the related documentation here: https://sharp.pixelplumbing.com/api-output#withmetadata

### Code Sample

```js
// given any image
const image = sharp(imageBuffer);

const outputImage = await image.withMetadata({
	exif: {
		IFD0: {
                        // these work without issues
			Make: 'Make',
			Model: 'Model',
			// I am unable to set these - strings are expected (error messages)
                        GPSLatitudeRef: 'N',
			GPSLatitude: '51,30,12.3456',
			GPSLongitudeRef: 'W',
			GPSLongitude: '0,7,54.321'
		}
	}
}).toBuffer();
```

I have tried to process an image with existing location data.
The information is not lost after processing with `image.withMetadata().toBuffer()`.
I think I am probably not passing the right arguments to the `withMetadata` call but I am unable to find similar issues or further documentation.

Any help is appreciated.

**Comment by lovell** [comment]
EXIF stores GPS metadata in `IFD3`, see also #2767

**Comment by RollingSquirrel** [comment]
Thanks for the quick reply.

I have changed the example according to the referenced issue:

```js
image.withMetadata({
		exif: {
			IFD0: {
				Make: 'TestMake',
				Model: 'TestModel'
			},
			IFD3: {
				GPSLatitudeRef: 'N',
				GPSLatitude: '55/1 43/1 5287/100',
				GPSLongitudeRef: 'E',
				GPSLongitude: '37/1 35/1 5571/100',
				GPSAltitudeRef: 'Sea level',
				GPSAltitude: '90514/693',
				GPSSpeedRef: 'K',
				GPSSpeed: '114272/41081',
				GPSImgDirectionRef: 'M',
				GPSImgDirection: '192127/921',
				GPSDestBearingRef: 'M',
				GPSDestBearing: '192127/921',
				GPSDateStamp: '2020:07:28'
			}
		}
	});
```

Using sharp again to parse the processed image and then parsing the raw exif data results in the expected output. 😃 


Thanks for the guidance - I had trouble finding any reference to this issue.

I suggest adding a quick link / some information where to search (if there is external documentation available) to the documentation of the withMetadata function. Providing types for the IFDX parameters would be awesome if possible.

**Comment by lovell** [comment]
Commit https://github.com/lovell/sharp/commit/d6b60a60c690548d006c25fe79eb019212e678ae updates the documentation to add an EXIF GPS example, thanks for the suggestion.

Happy to accept a PR to improve the TypeScript definitions, if you're able.

**Comment by RollingSquirrel** [comment]
I have found the following:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53942
https://github.com/lovell/sharp/issues/2760

These type definitions seem to be providing some help for the IFD0 values.
From my limited understanding of the EXIF specification I cannot tell if these are actually typed correctly.
But this looks like a great starting point.
