### ISSUE TITLE
v0.31 trim() failing with an unclear error message

### ISSUE THREAD

**Issue by mquandalle** [lovell/sharp#3636]
Updating sharp from v0.30.7 to v0.31.0, I'm getting an error with the following code: 

```js
const img = sharp(imgPath).trim();
await img.toFile(newImgPath)
```

The error message is a bit cryptic:

> [Error: linear: vector must have 1 or 4 elements]

Image:

![logo_ville_villeneuve_les_avignon](https://user-images.githubusercontent.com/1730702/233103521-83c8c655-f28e-413a-bd73-7379547fc68d.jpg)

The error is still present in v0.32

**Comment by lovell** [comment]
Hi, thanks for reporting, this image is CMYK and it looks like the `trim()` operation is erroneously dropping the K channel internally when determining the background colour, hence the rather cryptic error message. This code could probably do with a bit of a refactor anyway so leave it with me.

**Comment by lovell** [comment]
Commit https://github.com/lovell/sharp/commit/8408e99aa38a84be63986ca0210eae106d13cbc2 makes the background colour logic more generic, which fixes this problem. There's also a new test that would previously have failed.

**Comment by mquandalle** [comment]
Thank you so much for the super quick response and fix!

**Comment by lovell** [comment]
v0.32.1 now available.
