### ISSUE TITLE
Some JPEGs options seems to be default anyway

### ISSUE THREAD

**Issue by rawriddims** [lovell/sharp#3638]
With settings `.toFormat("jpeg", { quality: 60, mozjpeg: true })` I can see with `magick identify -verbose ` that chromaSubsampling: '4:2:0' is `true` (I can read  2x2,1x1,1x1) and `options.progressive` is `true` as well. Does this depends on `mozjpeg: true`?
Or is it more likely that I just happened to have the original jpeg with chromaSubsampling: '4:2:0 and progressive?

Update:
I verified the original JPEG and in effect it was already encoded with chromaSubsampling: '4:2:0',
BUT it is a baseline JPEG, not progressive! The mystery deepens.

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/api-output#jpeg

| Param | Type | Default | Description |
| --- | --- | --- | --- |
| [options.mozjpeg] | <code>boolean</code> | <code>false</code> | use mozjpeg defaults, equivalent to `{ trellisQuantisation: true, overshootDeringing: true, optimiseScans: true, quantisationTable: 3 }` |
| [options.optimiseScans] | <code>boolean</code> | <code>false</code> | optimise progressive scans, forces progressive |

**Comment by rawriddims** [comment]
Yes, `[options.optimiseScans]`, but the original jpeg was baseline, I did not set any progressive option, and Sharp processed a progressive jpeg anyway.

**Comment by rawriddims** [comment]
I did not see it before, the [options.optimiseScans] in mozjpeg. Thanks!
