### ISSUE TITLE
install fails (windows 10)

### ISSUE THREAD

**Issue by proreact-mj** [lovell/sharp#364]
npm install --verbose sharp result

```
gyp http GET http://nodejs.org/dist/v4.2.1/SHASUMS256.txt
gyp verb streaming 32-bit node.lib to: C:\Users\Mikael\.node-gyp\4.2.1\ia32\node.lib
gyp http GET http://nodejs.org/dist/v4.2.1/node.lib
gyp verb streaming 64-bit node.lib to: C:\Users\Mikael\.node-gyp\4.2.1\x64\node.lib
gyp http GET http://nodejs.org/dist/v4.2.1/x64/node.lib
gyp http 404 http://nodejs.org/dist/v4.2.1/node.lib
gyp WARN install got an error, rolling back install
...
gyp verb validating download checksum for node-v4.2.1.tar.gz (8861b9f4c3b4db380fcda19a710c0430c3d62d03ee176c64db63eef95a
672663 == 8861b9f4c3b4db380fcda19a710c0430c3d62d03ee176c64db63eef95a672663)
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading 32-bit node.lib
gyp ERR! stack     at Request.<anonymous> (C:\Users\Mikael\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\li
b\install.js:377:20)
..stack trace...
```
Full debug 
[npm-debug.txt](https://github.com/lovell/sharp/files/144135/npm-debug.txt)

Assumption:
Path for the 32-bit node.lib is incorrect, resulting in a 404, which messes up the process.

Suggestions on how to temporarily work-around would be very helpful and greatly appreciated.

**Comment by lovell** [comment]
Hello, this is unlikely to be a problem specific to `sharp` as quite a few others are reporting this problem.

https://github.com/search?q=%22404+status+code+downloading+32-bit+node.lib%22&type=Issues&utf8=%E2%9C%93

A common solution seems to be to ensure you're using a more recent version of (and removing any old versions of) `npm` and/or `node-gyp`.

Good luck!

**Comment by proreact-mj** [comment]
Thanks for the quick feedback (impressive!)
Updating NPM seems to have done the trick :satisfied: 

`npm install -g npm`
