### ISSUE TITLE
How to perform bilinear/bicubic resampling?

### ISSUE THREAD

**Issue by xenova** [lovell/sharp#3642]
### What are you trying to achieve?

I'm sorry if this is a really stupid question, but I am trying to replicate the way Python's PIL library handles image resampling. They define 6 different [options](https://github.com/python-pillow/Pillow/blob/a405e8406b83f8bfb8916e93971edc7407b8b1ff/src/libImaging/Imaging.h#L262-L268): NEAREST, BOX, BILINEAR, HAPPING, BICUBIC, LANCZOS.

According to the [sharp.js documentation for resizing images](https://sharp.pixelplumbing.com/api-resize), there are 5 different interpolation kernels: nearest, cubic, mitchell, lancsoz2, and lancsoz3.

In particular, I care about bilinear and bicubic resampling, and there does not seem to be a kernel for each of these.

### When you searched for similar issues, what did you find that might be related?

[This old issue](https://github.com/lovell/sharp/issues/41) suggests I should probably look into [affine transforms](https://sharp.pixelplumbing.com/api-operation#affine)/[interpolators](https://sharp.pixelplumbing.com/api-utility#interpolators), but I am not quite sure how to achieve what I want with it.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

This is the current code I am using. I load an image from raw pixel values, then perform resizing on it. I want to be able to perform bilinear and/or bicubic resampling
```js
// Create sharp image from raw data, and resize
let img = sharp(this.data, {
    raw: {
        width: this.width,
        height: this.height,
        channels: this.channels
    }
}).resize({
    // https://github.com/lovell/sharp/blob/main/docs/api-resize.md
    width, height,
    fit: 'fill',
    kernel: 'cubic'
});
```

**Comment by lovell** [comment]
You can use [affine](https://sharp.pixelplumbing.com/api-operation#affine) for accurate resampling with a specific interpolator.

The following example will scale the input to half of its original size using bilinear interpolation:
```js
sharp(input).affine([0.5, 0, 0, 0.5], { interpolator: 'bilinear' )...
```

**Comment by xenova** [comment]
Thanks for the response! Is there a way to specify the desired width and height instead of simply halving the width and height?

**Comment by lovell** [comment]
You could read the input image dimensions via [metadata](https://sharp.pixelplumbing.com/api-input#metadata) then use these to calculate the required scale based on the target output dimensions.

**Comment by danielholmes** [comment]
I had the same requirement (matching a Pillow resize exactly using sharp). The above suggestion worked for me. Some example code:

Python with Pillow:
```python
image = Image.open("./input.jpg")
image = image.resize((600, 300))
image.save("./output-python.jpg", quality=100)
```

Javascript with sharp:
```javascript
const image = sharp('./input.jpg');
const meta = await image.metadata();
image = image.affine([600 / meta.width, 0, 0, 300 / meta.height], { interpolator: 'bilinear' });
await image.jpeg({ quality: 100 }).toFile("./output-js.jpg");
```

One thing to note from the [Pillow resize docs](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.resize) is that this no-argument resize will behave differently depending on the image type:

> resample – An optional resampling filter. This can be one of [Resampling.NEAREST](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#PIL.Image.Resampling.NEAREST), [Resampling.BOX](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#PIL.Image.Resampling.BOX), [Resampling.BILINEAR](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#PIL.Image.Resampling.BILINEAR), [Resampling.HAMMING](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#PIL.Image.Resampling.HAMMING), [Resampling.BICUBIC](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#PIL.Image.Resampling.BICUBIC) or [Resampling.LANCZOS](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#PIL.Image.Resampling.LANCZOS). If the image has mode “1” or “P”, it is always set to [Resampling.NEAREST](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#PIL.Image.Resampling.NEAREST). If the image mode specifies a number of bits, such as “I;16”, then the default filter is [Resampling.NEAREST](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#PIL.Image.Resampling.NEAREST). Otherwise, the default filter is [Resampling.BICUBIC](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#PIL.Image.Resampling.BICUBIC)

**Comment by xenova** [comment]
> I had the same requirement (matching a Pillow resize exactly using sharp). The above suggestion worked for me. Some example code:
> 
> Python with Pillow:
> 
> ```python
> image = Image.open("./input.jpg")
> image = image.resize((600, 300))
> image.save("./output-python.jpg", quality=100)
> ```
> 
> Javascript with sharp:
> 
> ```js
> const image = sharp('./input.jpg');
> const meta = await image.metadata();
> image = image.affine([600 / meta.width, 0, 0, 300 / meta.height], { interpolator: 'bilinear' });
> await image.jpeg({ quality: 100 }).toFile("./output-js.jpg");
> ```
> 
> One thing to note from the [Pillow resize docs](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.resize) is that this no-argument resize will behave differently depending on the image type:
> 
> > resample – An optional resampling filter. This can be one of [Resampling.NEAREST](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#PIL.Image.Resampling.NEAREST), [Resampling.BOX](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#PIL.Image.Resampling.BOX), [Resampling.BILINEAR](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#PIL.Image.Resampling.BILINEAR), [Resampling.HAMMING](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#PIL.Image.Resampling.HAMMING), [Resampling.BICUBIC](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#PIL.Image.Resampling.BICUBIC) or [Resampling.LANCZOS](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#PIL.Image.Resampling.LANCZOS). If the image has mode “1” or “P”, it is always set to [Resampling.NEAREST](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#PIL.Image.Resampling.NEAREST). If the image mode specifies a number of bits, such as “I;16”, then the default filter is [Resampling.NEAREST](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#PIL.Image.Resampling.NEAREST). Otherwise, the default filter is [Resampling.BICUBIC](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#PIL.Image.Resampling.BICUBIC)

Thanks for this! I'll close the issue since I've got things working correctly on my side :)
