### ISSUE TITLE
Optimize compose large images (>=10MB each images)

### ISSUE THREAD

**Issue by XanhZ** [lovell/sharp#3645]
### My problem

Currently, I'm doing compose 4-5 images into solid background (fixed size), each image size is >= 10MB. I force it run in 1 CPU. As a result, it spend 4-5s even 7s completing.
My expectation is 1-2s.

### Dependencies

- Node version: 14.20.1
- OS: Ubuntu 20.04
- Sharp version: 0.32.0
- Sample code:
``` javascript
    /**
     * Merge all images together
     * 
     * @param {CompositeImagesArgs} args 
     * @returns {Promise<CompositeImagesOutput>}
     */
    async compositeImages(args) {
        const { background, images, format = ImageProcessor.PNG } = args
        const file = await FileHelpers.createTemporaryFile(format)
        const { height, size, width } = await sharp(background).composite(images).toFile(file)
        return { file, height, size, width, mime_type: `image/${format}` }
    }
```

### Example

- Here is some logs:
![image](https://user-images.githubusercontent.com/61658597/234503976-59ed83c4-6200-44b8-8d26-fe50540f88c7.png)

**Comment by lovell** [comment]
Please can you provide complete code and sample images that allows someone else to reproduce, perhaps as a standalone repo.

**Comment by XanhZ** [comment]
@lovell 
Here is full example code: [https://gitlab.com/datht3/sharp-compose-images](url)
Here is my test images: [https://drive.google.com/drive/folders/19-3NW93ubUfh3M6WM_I_xCm4Sp9-YxUX?usp=share_link](url)

**Comment by XanhZ** [comment]
> @lovell Here is full example code: [https://gitlab.com/datht3/sharp-compose-images](url) Here is my test images: [https://drive.google.com/drive/folders/19-3NW93ubUfh3M6WM_I_xCm4Sp9-YxUX?usp=share_link](url)

In this code, I'm running with full CPU cores with dependencies:
- OS: Ubuntu 20.04
- CPU: Intel® Core™ i3-9100 CPU @ 3.60GHz × 4 
- Sharp version: 0.32.0
- Node version: 14.20.1
And result is approximately 2.5s

**Comment by lovell** [comment]
Thanks, I see ~3.1s when run locally on an ageing i7-7500U.

Given you're using Ubuntu, did you see https://sharp.pixelplumbing.com/install#linux-memory-allocator ?

> For this reason, by default, sharp will limit the use of thread-based [concurrency](https://sharp.pixelplumbing.com/api-utility#concurrency) when the glibc allocator is detected at runtime.

If I add `sharp.concurrency(4)` I see the time reduce by ~10% to ~2.8s.

Removing the `composite()` operation to provide a "baseline" PNG roundtrip time, i.e. only decoding the background and encoding the output:
```js
 await sharp(backgroundPath).toFile(outPath)
```
I see ~1.1s for this, so the addition of a 7-image RGBA composition takes about ~1.7s.

Are you able to provide code using alternative tooling that performs the same operation more quickly? It's possible there might be scope for improvement within libvips using callgrind profiling or similar.

**Comment by XanhZ** [comment]
@lovell If I using code like this, it takes ~1.8s
``` javascript
async function main() {
    console.time('compose images')
    await sharp({
        create: {
            width: 12289,
            height: 5096,
            channels: 3,
            background: '#ffffff'
        }
    }).composite(images).png().toFile(outPath)
    console.timeEnd('compose images')
}

**Comment by lovell** [comment]
If the background is always a solid colour then yes, avoiding the largest PNG decode of this example will definitely help.

PNG decoding speed is often a function of image *width*, especially when this increases to a level where decompressed regions of the image may no longer fit in the CPU cache.

**Comment by XanhZ** [comment]
@lovell yes, I change the out format to JPG and it downs to <1s if aslo increasing UV_THREADPOOL_SIZE.
Thanks for your support
