### ISSUE TITLE
align text option not working?

### ISSUE THREAD

**Issue by Jupiternerd** [lovell/sharp#3647]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [ x ] Running `npm install sharp` completes without error.
- [ x ] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [ x ] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

  System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 14.64 GB / 31.91 GB
  Binaries:
    Node: 19.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.3 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: ^0.32.0 => 0.32.0

### What are the steps to reproduce?

I am not sure if it's a bug or I am misunderstanding something, but the text align does not seem to work when creating a new text in the constructor.

```js 
        var base = sharp({
            "create": {
                "width": 300,
                "height": 100,
                "channels": 3,
                "background": { "r": 255, "g": 255, "b": 255 }
            }
        })

        var text = sharp({
            text: {
                "text": "Hello World",
                "rgba": true,
                "font": "arial",
                "align": "right",
                "width": 300,
                "height": 25
            },
        })

        base.composite([{
            "input": await text.png().toBuffer()
        }])
```

Outputs this image: [image](https://imgur.com/a/xOGsNy3)

### What is the expected behaviour?

expectation was this: [image](https://imgur.com/a/lD3rbVC)

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

linked above.

### Please provide sample image(s) that help explain this problem

linked above

**Edit - used correct format.

**Comment by lovell** [comment]
Alignment applies to multi-line text. Perhaps add a newline `\n` to the text or alter the aspect ratio to see the effects. For example:
```js
  text: {
    text: "Hello World",
    rgba: true,
    font: "arial",
    align: "right",
    width: 100,
    height: 100,
  }
```
![](https://user-images.githubusercontent.com/210965/234796602-74e558e4-821f-4430-afa6-e9e481beab9c.png)

**Comment by lovell** [comment]
I've made a small improvement to the docs about this via commit https://github.com/lovell/sharp/commit/a2ca678854f1bb6fdf6a601dbd8a219d68239407

**Comment by Jupiternerd** [comment]
I see, thank you for the help.
