### ISSUE TITLE
How to force external libvips

### ISSUE THREAD

**Issue by felixbuenemann** [lovell/sharp#365]
On MacOS X sharp uses the system provided libvips, but on linux it uses it's own vendored libs in `node_modules/sharp/lib`.

How do I force using the system provided libvips on Linux?

My use case is that I would like to use mozjpeg instead of the bundle libjpeg-turbo.

I couldn't find anything in the docs about this, they just tell that on most Linux systems no external dependencies are needed.

**Comment by lovell** [comment]
Hi Felix, if a [given version or later](https://github.com/lovell/sharp/blob/master/package.json#L71) of libvips is discoverable via pkg-config, it will (or at least should) be [preferred](https://github.com/lovell/sharp/blob/master/binding.gyp#L67) at `npm install` time. Is this something you've been able to try?

**Comment by felixbuenemann** [comment]
I didn't think of pkg-config, I should be able to `export PKG_CONFIG_PATH` to point it to a custom build. I'll try that this evening.

**Comment by lovell** [comment]
Great. Please feel free to submit a PR to enhance the rather scant docs on this if you think it will help others:

> "Preference will be given to an existing globally-installed (via pkg-config) version of libvips that meets the minimum version requirement. This allows the use of newer versions of libvips with older versions of sharp."

https://github.com/lovell/sharp/blob/master/docs/install.md

**Comment by felixbuenemann** [comment]
Yes, I'll look into that.

**Comment by felixbuenemann** [comment]
I've had a quick test with vips installed into /opt/vips and the combination PKG_CONFIG_PATH during npm install and LD_LIBRARY_PATH at runtime did the trick. I haven't had time yet to look into updating the docs. When installing vips in /usr or /usr/local it should work without any environment variables.
