### ISSUE TITLE
Having a __dirname issue when using sharp in TypeScript project

### ISSUE THREAD

**Issue by markkevc** [lovell/sharp#3651]
### What are you trying to achieve?

I'm trying to use sharp to convert images to webp and some other stuff like crop, resize, etc. but I'm getting this error
`ERROR Runtime.UnhandledPromiseRejection: ReferenceError: __dirname is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension`

### When you searched for similar issues, what did you find that might be related?

Most of the answers I'm getting from web is just using the below codes, however, the __dirname is being used inside this module and cannot be changed in my local file.

`import { fileURLToPath } from 'url';`
`import { dirname } from 'path';`

`const __filename = fileURLToPath(import.meta.url);`
`const __dirname = dirname(__filename);`

Changing `type` to `commonjs` and/or removing it in package.json file didn't work.

Thank you.

**Comment by lovell** [comment]
This is probably a `tsconfig.json` misconfiguration in your project/repo, unrelated to sharp. For example, are you using Node.js / CommonJS module resolution?

https://www.typescriptlang.org/docs/handbook/module-resolution.html

**Comment by trsiddiqui** [comment]
> Thank you @lovell. I'll figure it out.

Did you ever figure it out?
