### ISSUE TITLE
bitdepth for tiff automatically sets to 32 when defined as 1

### ISSUE THREAD

**Issue by sivahari-acl** [lovell/sharp#3655]
The generated tiff ends up with a bitdepth of 32 even when it is defined as 1 in the format options.

The code below show the conversion of a png screenshot from Puppeteer to a tiff using sharp js:

`const browser = await Puppeteer.launch({
        args: [
          "--no-sandbox",
          "--disable-setuid-sandbox",
          "--disable-dev-shm-usage",
          "--disable-canvas-aa",
          "--disable-accelerated-2d-canvas",
          "--disable-gl-drawing-for-tests",
          "--disable-software-rasterizer",
          "--use-gl=swiftshader",
          "--headless",
          "--no-first-run",
          "--no-zygote",
          "--mute-audio",
          "--user-data-dir=./chromeData",
          "--single-process", // <- this one doesn't works in Windows
          "--disable-gpu",
        ],
        headless: true,
      });

      const page = await browser.newPage();

      await page.setViewport({
        width: 1654,
        height: 2339,
        deviceScaleFactor: 1,
      }); 
      
      await page.setContent(htmlOutput);
      
      const binaryScreenshot = await page.screenshot({
        encoding: 'binary',
        type: 'png',
      });

      const tiff = await sharp(binaryScreenshot)
      .withMetadata({ density: 300 })
      .toFormat('tiff', {
        compression: 'lzw',
        bitdepth: 1,
      })
      .toBuffer();
      
      await browser.close();
      return tiff;`

**Comment by lovell** [comment]
I guess `binaryScreenshot` will be RGBA so you'll probably need to add a colourspace conversion to greyscale too.
```js
  .toColourspace('b-w')
```
https://sharp.pixelplumbing.com/api-colour#tocolourspace

**Comment by sivahari-acl** [comment]
> I guess `binaryScreenshot` will be RGBA so you'll probably need to add a colourspace conversion to greyscale too.
> 
> ```js
>   .toColourspace('b-w')
> ```
> 
> https://sharp.pixelplumbing.com/api-colour#tocolourspace

I've tried that too but it made no difference, updated code below:
`const browser = await Puppeteer.launch({
        args: [
          "--no-sandbox",
          "--disable-setuid-sandbox",
          "--disable-dev-shm-usage",
          "--disable-canvas-aa",
          "--disable-accelerated-2d-canvas",
          "--disable-gl-drawing-for-tests",
          "--disable-software-rasterizer",
          "--use-gl=swiftshader",
          "--headless",
          "--no-first-run",
          "--no-zygote",
          "--mute-audio",
          "--user-data-dir=./chromeData",
          "--single-process", // <- this one doesn't works in Windows
          "--disable-gpu",
        ],
        headless: true,
      });

      const page = await browser.newPage();

      await page.setViewport({
        width: 1654,
        height: 2339,
        deviceScaleFactor: 1,
      }); 
      
      await page.setContent(htmlOutput);
      
      const binaryScreenshot = await page.screenshot({
        encoding: 'binary',
        type: 'png',
      });

      const tiff = await sharp(binaryScreenshot)
      .withMetadata({ density: 300 })
      .toColourspace('b-w')
      .toFormat('tiff', {
        compression: 'lzw',
        bitdepth: 1,
        predictor: "none" //https://github.com/lovell/sharp/issues/3486
      })
      .toBuffer();
      
      await browser.close();
      return tiff;`

**Comment by lovell** [comment]
You mention #3486 as being relevant, which it is. Did you try removing the alpha channel with `removeAlpha()` also?

**Comment by sivahari-acl** [comment]
@lovell, that was this missing piece, it is now generating the tiff with bitdepth of 1, thank you.
