### ISSUE TITLE
WebP compression artefacts relating to premultiplication rounding

### ISSUE THREAD

**Issue by violetviolinist** [lovell/sharp#3658]
### What are you trying to achieve?

The recent [change](https://github.com/lovell/sharp/commit/9e2207f37610d337e16d828c02d0d0bde41f157f#diff-49cc9aed5c4435b87316b7cbf2d477d84942baf6ed0f83d74aca6b483c838208) related to (un)premultiplication in resize() is producing artefacts in one of our images (messing up color in some pixels) when resize() + extend() is applied on it. It is a 158 x 31 image; a word of text on a fully transparent background, all letters having the same darg-gray (#333333) color. I verified this change to be the cause by reverting it and rebuilding sharp, and applying the resize again.

We would love to have an option added to the resize() operation to go back to not using integer (un)premultiplication. I would be happy to contribute with a PR. Just wanted to collect thoughts first.

### When you searched for similar feature requests, what did you find that might be related?

NA

### What would you expect the API to look like?

A new field `useIntegerPremultiply` added to resize(). Will default to `true` \:

```
resize(100, 100, {
  useIntegerPremultiply: false
})
```

**Comment by lovell** [comment]
Please can you provide a complete, standalone code sample that allows someone else to reproduce the problem you are experiencing as I'd like to understand this first before jumping into a solution.

**Comment by violetviolinist** [comment]
Here's sample code and the input image to reproduce the issue. The two outputs to compare are from v0.32.1 and v0.31.3. Although I have singled out the above mentioned [commit](https://github.com/lovell/sharp/commit/9e2207f37610d337e16d828c02d0d0bde41f157f#diff-49cc9aed5c4435b87316b7cbf2d477d84942baf6ed0f83d74aca6b483c838208) to be the culprit by recompiling v0.32.1 with only that change reverted in `pipeline.cc`.

*Note*: You may have to zoom in a little into the outputs to see the distorted pixels.

```
  (async () => {
    const origBuffer = fs.readFileSync(`./textsample.png`)

    const outBuffer = await sharp(origBuffer)
    .resize(800, 500, {
      fit: 'inside',
    })
    .extend({
      background: {r: 255, g: 255, b: 255, alpha: 0},
      bottom: 121,
      left: 0,
      right: 0,
      top: 120,
    })
    .webp()
    .toBuffer()
  
    fs.writeFileSync("./out.webp", outBuffer)
  })()
```

[textsample.png](https://drive.google.com/file/d/1Chmz4dblurDnck2Vtho0_sinV8Py9m1O/view?usp=sharing)

<img width="726" alt="image" src="https://user-images.githubusercontent.com/19747413/236234820-ed0e1f5e-f409-42f4-a294-29380159e164.png">

**Comment by lovell** [comment]
These look like WebP compression artefacts. For WebP output images that contain text, I recommend using either `lossless` or `nearLossless`.

**Comment by violetviolinist** [comment]
Yes, the artefacts seem to be limited to WebP encoding only. But even for WebP encoding, they did appear only after the premultiplication change. As for conditionally using `lossless` or `nearLossless` for images with text, we cannot do that since we do not always know the content of the image being processed. And we cannot afford the higher processing times if we were to use `nearLossless` on all images unconditionally.

Which is why making integer premultiplication configurable seems to be the only solution for us.

**Comment by lovell** [comment]
Does increasing the `quality` help? Does using `smartSubsample` help? These settings may be relevant if some images will contain text.

https://sharp.pixelplumbing.com/api-output#webp

If not, this might provide a good test image (as a PNG, without the artefacts) to use to ask the libwepb maintainers upstream.

**Comment by violetviolinist** [comment]
>Does increasing the quality help? Does using smartSubsample help? These settings may be relevant if some images will contain text.

Yes. Increasing quality and using `nearLossless` helps. However, one popular use case of Sharp (including ours) is to resize/optimize images in real-time. Detecting the presence of text in an image is not computationally cheap and desirable in the processing pipeline. 

Please confirm if my understanding is correct - With everything else being the same, we get the better output without premultiplication rounding vs with premultiplication rounding. That means the upstream library is producing consistent results.

If the above is true, wouldn't it be better to make premultiplication rounding configurable behind an option with the default value set to `true` to match the current behaviour of the library that works well for most of the images?

**Comment by violetviolinist** [comment]
I haven't asked them because without sharp's premultiplication rounding, libwebp is producing the artefact-free output. And since the rounding was introduced in sharp, I thought this would be the right place to ask.

Also, was this rounding change expected to be completely harmless across different combinations w/ resize()? I am trying to understand the reasoning behind incorporating this change across the board without the option to go back. At this point, taking this up with libwebp maintainers may or may not solve the issue. But allowing to opt-out of the rounding within sharp will definitely fix it.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
