### ISSUE TITLE
Cannot embed non-transparent image onto a transparent background

### ISSUE THREAD

**Issue by diegocsandrim** [lovell/sharp#366]
Hi!

There is a strange behavior when resizing JPEG to PNG in `embed` mode.

```javascript
sharp('input.jpg')
  .resize(2000, 1000)
  .background({ r: 0, g: 0, b: 0, a: 0 })
  .embed()
  .toFormat(sharp.format.png)
  .toFile('output1.png', function (err, info) {
    console.log(err || info);
  });
```

I am expecting to have the input image resized to maximum width or height, keeping aspect ratio, and above a transparent background.
But I am getting a full transparent image!

JPEG input
![JPEG input](https://raw.githubusercontent.com/diegocsandrim/sharp-test/master/input.jpg)
Rezize output
![Resize output](https://raw.githubusercontent.com/diegocsandrim/sharp-test/master/output1.png)

The same does not happens when input image is a PNG, with the same code:
```javascript
sharp('input.png')
  .resize(2000, 1000)
  .background({ r: 0, g: 0, b: 0, a: 0 })
  .embed()
  .toFormat(sharp.format.png)
  .toFile('output2.png', function (err, info) {
    console.log(err || info);
  });
```

PNG input
![JPEG input](https://raw.githubusercontent.com/diegocsandrim/sharp-test/master/input.png)
Rezize output
![Resize output](https://raw.githubusercontent.com/diegocsandrim/sharp-test/master/output2.png)

This is really strange to me, am I making a mistake?

A add a git repo to test it:
https://github.com/diegocsandrim/sharp-test

**Comment by lovell** [comment]
Hi Diego, I've been able to reproduce this thanks to your detailed report. I think I introduced this regression during sharp's recent switch from libvips' C to C++ binding.

When embedding a JPEG onto a background with transparency, we have to add a transparency layer to the decoded JPEG image. It looks like the opaque and transparent values are currently the wrong way round, so you're seeing an "opaque transparency", also known as "nothing" :)

Luckily it's a quick fix, and I'll add more test cases for this feature to (hopefully) prevent this occurring again.

**Comment by lovell** [comment]
Commit df33c30 adds automated tests that would have discovered this regression, as well as the fix.

Thanks for reporting this!

**Comment by diegocsandrim** [comment]
Thank you very much Lovell!

**Comment by lovell** [comment]
v0.13.1 out now
