### ISSUE TITLE
Color an image

### ISSUE THREAD

**Issue by itlboy** [lovell/sharp#3660]
Hello, How can I do it with sharp: https://support.cloudinary.com/hc/en-us/articles/202521302-How-can-I-color-an-image-

Thank you.

**Comment by lovell** [comment]
Did you see https://sharp.pixelplumbing.com/api-colour#tint ?

**Comment by itlboy** [comment]
> 

I tried, but it did not work as expect. I need to use code

`((async() => {
    console.time("process time");
    const color = "#245923";
    const imputImage = "fillcolor.png";
    var info = await sharp(imputImage).metadata();

    const data = await sharp({
        create: {
            width: info.width,
            height: info.height,
            channels: 4,
            background: color
        }
    }).composite([{
            input: imputImage,
            blend: "dest-in"
        }]).png()
          .toBuffer();
    fs.writeFileSync("fillcolor-result.png", data);
    console.timeEnd("process time");
}))()
`
