### ISSUE TITLE
Having trouble using correct architecture with yarn

### ISSUE THREAD

**Issue by SleeplessOne1917** [lovell/sharp#3663]
## Possible install-time or require-time problem
I'm trying to install sharp with yarn as part of a dockerfile. Here's the file:
```Dockerfile
FROM node:alpine as builder
RUN apk update && apk add curl yarn python3 build-base gcc wget git --no-cache

WORKDIR /usr/src/app

ENV npm_config_target_arch=x64
ENV npm_config_target_platform=linux
ENV npm_config_target_libc=musl

# Cache deps
COPY package.json yarn.lock ./
RUN yarn install --ignore-scripts --prefer-offline --pure-lockfile

# Build
COPY generate_translations.js \
  tsconfig.json \
  webpack.config.js \
  .babelrc \
  ./

COPY lemmy-translations lemmy-translations
COPY src src

# Set UI version 
RUN echo "export const VERSION = 'dev';" > "src/shared/version.ts"

RUN yarn install --ignore-scripts --prefer-offline
RUN yarn build:dev

FROM node:alpine as runner
COPY --from=builder /usr/src/app/dist /app/dist
COPY --from=builder /usr/src/app/node_modules /app/node_modules

EXPOSE 1234
WORKDIR /app
CMD node dist/js/server.js
```

yarn doesn't have the `--platform`, `--arch`, or `--libc` options for installation like npm does, so I'm trying to do it by setting the environment variables. Here is the error I get when trying to use the container:

```
docker-lemmy-ui-1  | Inferno is in development mode.
docker-lemmy-ui-1  | /app/node_modules/sharp/lib/sharp.js:37
docker-lemmy-ui-1  |   throw new Error(help.join('\n'));
docker-lemmy-ui-1  |   ^
docker-lemmy-ui-1  | 
docker-lemmy-ui-1  | Error: 
docker-lemmy-ui-1  | Something went wrong installing the "sharp" module
docker-lemmy-ui-1  | 
docker-lemmy-ui-1  | Cannot find module '../build/Release/sharp-linuxmusl-x64.node'
docker-lemmy-ui-1  | Require stack:
docker-lemmy-ui-1  | - /app/node_modules/sharp/lib/sharp.js
docker-lemmy-ui-1  | - /app/node_modules/sharp/lib/constructor.js
docker-lemmy-ui-1  | - /app/node_modules/sharp/lib/index.js
docker-lemmy-ui-1  | - /app/dist/js/server.js
docker-lemmy-ui-1  | 
docker-lemmy-ui-1  | Possible solutions:
docker-lemmy-ui-1  | - Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
docker-lemmy-ui-1  | - Install for the current linuxmusl-x64 runtime: "npm install --platform=linuxmusl --arch=x64 sharp"
docker-lemmy-ui-1  | - Consult the installation documentation: https://sharp.pixelplumbing.com/install
docker-lemmy-ui-1  |     at Object.<anonymous> (/app/node_modules/sharp/lib/sharp.js:37:9)
docker-lemmy-ui-1  |     at Module._compile (node:internal/modules/cjs/loader:1267:14)
docker-lemmy-ui-1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
docker-lemmy-ui-1  |     at Module.load (node:internal/modules/cjs/loader:1125:32)
docker-lemmy-ui-1  |     at Module._load (node:internal/modules/cjs/loader:965:12)
docker-lemmy-ui-1  |     at Module.require (node:internal/modules/cjs/loader:1149:19)
docker-lemmy-ui-1  |     at require (node:internal/modules/helpers:121:18)
docker-lemmy-ui-1  |     at Object.<anonymous> (/app/node_modules/sharp/lib/constructor.js:11:1)
docker-lemmy-ui-1  |     at Module._compile (node:internal/modules/cjs/loader:1267:14)
docker-lemmy-ui-1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
docker-lemmy-ui-1  | 
docker-lemmy-ui-1  | Node.js v20.1.0

```

- [x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Is this a problem with filesystem permissions?

I'm using yarn, so I'm not sure how to answer the questions in this section with respect to that.

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?
n/a

If you are using npm v7 or later, does the user running `npm install` own the directory it is run in?
n/a

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?
n/a

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

Instead of running the suggested command, I instead ran `npm_config_target_arch=x64 npm_config_target_platform=linux npm_config_target_libc=musl yarn install --verbose --foreground-scripts sharp`. The output is as follows:

<details>

yarn install v1.22.19
verbose 0.131432163 Checking for configuration file "/home/insomnia/projects/foo/.npmrc".
verbose 0.13162628 Checking for configuration file "/home/insomnia/.npmrc".
verbose 0.13183877 Checking for configuration file "/home/insomnia/.local/share/nvm/v18.16.0/etc/npmrc".
verbose 0.131967988 Checking for configuration file "/home/insomnia/projects/foo/.npmrc".
verbose 0.132119542 Checking for configuration file "/home/insomnia/projects/.npmrc".
verbose 0.132261913 Checking for configuration file "/home/insomnia/.npmrc".
verbose 0.132417493 Checking for configuration file "/home/.npmrc".
verbose 0.132858238 Checking for configuration file "/home/insomnia/projects/foo/.yarnrc".
verbose 0.13302322 Checking for configuration file "/home/insomnia/.yarnrc".
verbose 0.133125418 Found configuration file "/home/insomnia/.yarnrc".
verbose 0.13377118 Checking for configuration file "/home/insomnia/.local/share/nvm/v18.16.0/etc/yarnrc".
verbose 0.133902639 Checking for configuration file "/home/insomnia/projects/foo/.yarnrc".
verbose 0.134040913 Checking for configuration file "/home/insomnia/projects/.yarnrc".
verbose 0.134152323 Checking for configuration file "/home/insomnia/.yarnrc".
verbose 0.134263355 Found configuration file "/home/insomnia/.yarnrc".
verbose 0.134517107 Checking for configuration file "/home/.yarnrc".
verbose 0.136380372 current time: 2023-05-07T11:28:47.606Z
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Linux 6.2 RebornOS Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 19.12 GB / 31.17 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.16.0 - ~/.local/share/nvm/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.local/share/nvm/v18.16.0/bin/yarn
    npm: 5.10.0 - ~/projects/lemmy-ui/node_modules/.bin/npm
  npmPackages:
    sharp: ^0.32.1 => 0.32.1 
```

**Comment by lovell** [comment]
> RUN yarn install --ignore-scripts --prefer-offline

Please remove the `--ignore-scripts` flag.

**Comment by SleeplessOne1917** [comment]
Thank worked. Thanks!
