### ISSUE TITLE
Input Buffer not detected in composite with webpack 5

### ISSUE THREAD

**Issue by niug** [lovell/sharp#3665]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz
    Memory: 3.13 GB / 15.74 GB

  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 9.3.0 - C:\Program Files\nodejs\npm.CMD

  npmPackages:
    sharp: ^0.32.1 => 0.32.1

### What are the steps to reproduce?
File testSharp.js:
 ```
const img = "iVBORw0KGgoAAAANSUhEUgAAAUAAAAEACAYAAADCyK/GAAADB0lEQVR4Ae3BgQkDQRADsXH/RV+qeAispAVw1AI4agEctQCOWgBHLYCjFsBRC+CoBXDUAjhqARy1AI5aAEctgKMWwFEL4KgFcNQCOGoBHLUAjloARy2AoxbAUQvgqAVw1AI4agEctQCOWgBHLYCjFsBRC+CoBXDUAjhqARy1AI5aAEctgKMWwFEL4KgFcNQCOGoBHLUAjloARy2AoxbAUQvgqAVw1AI4agEctQCOWgBHLYCjFsBRC+CoBXDUAjhqARy1AI5aAEctgKMWwFEL4KgFcNQCOGoBHLUAjloARy2AoxbAUQvgqAVw1AI4agEctQCOWgBHLYCjFsBRC+CoBXDUAjhqARy1AI5aAEctgKMWwFEL4KgFcNQCOGoBHLUAjloARy2AoxbAUQvgqAVw1AI4agEctQCOWgBHLYCjFsBRC+CoBXDUAjhqARy1AI5aAEctgKMWwFEL4KgFcNQCOGoBHLUAjloARy2AoxbAUQvgqAX/5vVaCz624N+8XmvBxxb8m9drLfjYAjhqARy1AI5aAEctgKMWwFEL4KgFcNQCOGoBHLUAjloARy2AoxbAUQvgqAVw1AI4agEctQCOWgBHLYCjFsBRC+CoBXDUAjhqARy1AI5aAEctgKMWwFEL4KgFcNQCOGoBHLUAjloARy2AoxbAUQvgqAVw1AI4agEctQCOWgBHLYCjFsBRC+CoBXDUAjhqARy1AI5aAEctgKMWwFEL4KgFcNQCOGoBHLUAjloARy2AoxbAUQvgqAVw1AI4agEctQCOWgBHLYCjFsBRC+CoBXDUAjhqARy1AI5aAEctgKMWwFEL4KgFcNQCOGoBHLUAjloARy2AoxbAUQvgqAVw1AI4agEctQCOWgBHLYCjFsBRC+CoBXDUAjhqARy1AI5aAEctgKMWwFEL4KgFcNQCOGoBHLUAjloARy2AoxbAUQvgqAVw1AI4agEctQCOWgBHLYCjFsBRC+CoBXDUAjhqARy1AI5aAEctgKMWwFEL4KgFcNQCOGoBHLUAjloARy2Ao36z+gcBYOd9yQAAAABJRU5ErkJggg==";
const mask ="iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAIAAADTED8xAAADMElEQVR4nOzVwQnAIBQFQYXff81RUkQCOyDj1YOPnbXWPmeTRef+/3O/OyBjzh3CD95BfqICMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMO0TAAD//2Anhf4QtqobAAAAAElFTkSuQmCC";
const output = await sharp(Buffer.from(img, 'base64'))
                         .composite([{input: Buffer.from(img, 'base64'), gravity: 'center' }])
                         .toBuffer();
```
Execute the code directly with nodeJS: 
```
$node ./testSharp.js
```
and all run correctly, and then use webpack: 
```
$webpack
$node ./build/main.js
```
and nodeJS throw error 'Unsupported input '${input}' of type ${typeof input}'

### What is the expected behaviour?

When I execute the code in nodeJS works without problem, but when I execute the webpack command, the code doesn't work, throwing the error: 'Unsupported input '${input}' of type ${typeof input}'. Debugging Sharp library inside de node_modules I can see that the error is because the Buffer input is not identified as a Buffer in constructor of Composite.

In node_modules/sharp/lib/input.js there is a method _createInputDescriptor, that check if the input is a string, or a Buffer, or an ArrayBuffer,... in nodeJS directly the input type is Buffer, and it's run correctly, but after webpack the code, input instanceof Buffer returns false, and the method not detect the correct type and throw the undefined input error.

```
function _createInputDescriptor (input, inputOptions, containerOptions) {
  const inputDescriptor = {
    failOn: 'warning',
    limitInputPixels: Math.pow(0x3FFF, 2),
    ignoreIcc: false,
    unlimited: false,
    sequentialRead: true
  };
  if (is.string(input)) {
    // filesystem
    inputDescriptor.file = input;
  } else if (is.buffer(input)) {
    // Buffer
    if (input.length === 0) {
      throw Error('Input Buffer is empty');
    }
    inputDescriptor.buffer = input;
  } else if (is.buffer(input)) {
    // Buffer
    if (input.length === 0) {
      throw Error('Input Buffer is empty');
    }
    inputDescriptor.buffer = input;
  } else if (is.arrayBuffer(input)) {
    if (input.byteLength === 0) {
      throw Error('Input bit Array is empty');
    }
    inputDescriptor.buffer = Buffer.from(input, 0, input.byteLength);
  } else if (is.typedArray(input)) {
    if (input.length === 0) {
      throw Error('Input Bit Array is empty');
    }
    inputDescriptor.buffer = Buffer.from(input.buffer, input.byteOffset, input.byteLength);
  } 
```

When I debug the code after webpack, the method: is.buffer(input) returns false, this method check the input instanceof Buffer. And the other option for is.typedArray(input) return false too.

Buffer.from(img, 'base64') return an object that instanceof Buffer is false and object.constructor === Uint8array is also false.

If I add the check for Uint8array specificly the code run:

```
} else if (input instanceof Uint8Array) {
    if (input.length === 0) {
      throw Error('Input Buffer is empty');
    }
    inputDescriptor.buffer = input;
}
```
What can I do to not have to edit the module? There are some option that I don't know in Buffer?

Thanks a lot.

**Comment by lovell** [comment]
Make sure you're not polyfilling or otherwise overriding `Buffer`, including in another dependencies.

There were some breaking changes in Webpack 5 relating to this.
https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed

**Comment by niug** [comment]
Thanks lovell!

In my webpack.config.js file I use the node-polifyll package. I removed and all work very good.
