### ISSUE TITLE
gif flip()

### ISSUE THREAD

**Issue by JoeLeaf** [lovell/sharp#3666]
Hello, when I use gif flip, I will rewind the gif,May I ask if this is a bug, and I also hope to have a separate gif rewind function
^.^

**Comment by JoeLeaf** [comment]
sharp(buffer,{ animated: true }).flip()

**Comment by lovell** [comment]
Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem.

Please provide sample image(s) that help explain this problem.

(These questions were in the issue template that was ignored/deleted.)

**Comment by JoeLeaf** [comment]
`const sharp = require('sharp')
const fs = require('fs')
const url="https://gchat.qpic.cn/gchatpic_new/0/0-0-E598172EAFFC7E1AE02DA9385AC07979/0"
fetch(url).then(res => res.arrayBuffer()).then(buffer => {
    fs.writeFileSync('test.gif', Buffer.from(buffer))
    sharp(Buffer.from(buffer), { animated: true }).flip().toBuffer().then(data => {
        fs.writeFileSync('test2.gif', data)
    });
}).catch(err => {
    console.log(err)
})`

When the picture is upside down, it is also rewinded

**Comment by JoeLeaf** [comment]
const sharp = require('sharp')
const fs = require('fs')
const url="https://gchat.qpic.cn/gchatpic_new/0/0-0-E598172EAFFC7E1AE02DA9385AC07979/0"
fetch(url).then(res => res.arrayBuffer()).then(buffer => {
    fs.writeFileSync('test.gif', Buffer.from(buffer))
    sharp(Buffer.from(buffer), { animated: true }).flip().toBuffer().then(data => {
        fs.writeFileSync('test2.gif', data)
    });
}).catch(err => {
    console.log(err)
})

//When the picture is upside down, it is also rewinded

**Comment by lovell** [comment]
Thank you. Sadly the `flip` operation won't work properly on animated images. They are processed as a top-to-bottom stack of frames so mirroring about the x-axis will break this. I'll add something to the docs.

One possible approach might be to extract and flip one page/frame at a time, then join them back together.

As an aside, the `flop` operation should support animated images as frames aren't affected by mirroring about the y-axis.
