### ISSUE TITLE
"out of order read" when combining normalise() with composite()

### ISSUE THREAD

**Issue by jamiemill** [lovell/sharp#3669]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: macOS 13.3
    CPU: (8) arm64 Apple M2
    Memory: 88.88 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
    Watchman: 2023.05.08.00 - /opt/homebrew/bin/watchman
  npmPackages:
    sharp: ^0.32.1 => 0.32.1 
```

### What are the steps to reproduce?

```js
const sharp = require("sharp");

const img = sharp("image.png")
  .normalise()
  .composite([{ input: "watermark.png" }])
  .toFile("output.jpg");
```

throws error:

```
pngload: out of order read at line 79
```

and writes a zero byte image.

If I comment out either the `composite()` or `normalise()` step, it works fine. But it fails when both are used together.

It works if I downgrade to 0.31.3, so it could be related to https://github.com/lovell/sharp/issues/3600#issuecomment-1483452341

### What is the expected behaviour?

Expect to see the image.jpg overlaid with watermark.png.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

See the code snippet above, and test it with the images below.

### Please provide sample image(s) that help explain this problem

![image](https://github.com/lovell/sharp/assets/66421/f40e33d8-4e51-4d58-91c4-feb260e705e9)
![watermark](https://github.com/lovell/sharp/assets/66421/a52930e4-fd73-40cb-9f2d-abf2bcb45d45)

**Comment by lovell** [comment]
Hi, yes, this will be related to defaulting to sequential read in v0.32.0.

When the `normalise()` operation is used, sharp switches libvips into random access read for the input as sequential read is unsupported. However it should also be doing this for all of the `composite()` operation input(s) to match.

You should be able to workaround this for now via:
```diff
-   .composite([{ input: "watermark.png" }])
+   .composite([{ input: "watermark.png", sequentialRead: false }])
```

**Comment by jamiemill** [comment]
Thanks, that indeed fixes my test case. But in my real code, I'm using typescript and I get:

```
TSError: ⨯ Unable to compile TypeScript:
index.ts:5:41 - error TS2322: Type '{ input: string; sequentialRead: false; }' is not assignable to type 'OverlayOptions'.
  Object literal may only specify known properties, and 'sequentialRead' does not exist in type 'OverlayOptions'.

5   .composite([{ input: "watermark.png", sequentialRead: false }])
```

**Comment by lovell** [comment]
Commit https://github.com/lovell/sharp/commit/de0fc07092add57cefeabfd6c40a50b33e3cbfdd fixes the original access method problem, and commit https://github.com/lovell/sharp/commit/3340120aeaf10811eeae97f524281ba86d78a453 ensures the type definitions for `composite` include all the underlying input options, which includes `sequentialRead`.

A workaround for TypeScript might be something like (untested):
```diff
-   .composite([{ input: "watermark.png" }])
+   .composite([{ input: "watermark.png", sequentialRead: false } as unknown as OverlayOptions])
```

Thanks for reporting this, the changes will be in v0.32.2.

**Comment by lovell** [comment]
v0.32.2 now available.
