### ISSUE TITLE
Feature request: emit post-processing 'info' event

### ISSUE THREAD

**Issue by salzhrani** [lovell/sharp#367]
I am using sharp's raw input and output to do some color manipulation on images in addition to resize and crop. 
```
var input = sharp().raw().resize(600).max().withoutEnlargement();
var process = new ColorSaturationStream();
var output = sharp(null, {raw: {
    width: newWidth,
    height: newHeight,
    channels: newChannels
}}).toFormat('jpg');

someImageStream.pipe(input).pipe(process).pipe(output).pipe(response);
```

the challenge is that `output` must have the correct `newWidth` and `newHeight` or it will throw an error like:
`libc++abi.dylib: terminating with uncaught exception of type vips::VError` 
while knowing the original image size I can calculate what `newWidth` and `newHeight` can be, but since there is a possibility of using different rounding methods than sharp I might get the wrong values.

I currently use `Math.round` as sharp does but is it always going to be the case ?

One way that might help with this is to add a utility function that exposes sharp internal calculations so we can have the same values.

**Comment by lovell** [comment]
Hello, we could add a feature where an instance of `sharp` will emit an `info` event with the same details as the `info` parameter provided to the [toBuffer](http://sharp.dimens.io/en/stable/api/#tobuffercallback) callback. Do you think this might provide what you need?

Given the async nature of this, you would probably need to cork the `output` Stream of your example until this event was emitted by the `input` Stream.

As an aside, we also need to check why you're seeing "terminating with uncaught exception of type vips::VError" as that should have been caught and emitted as an `error` event.

**Comment by salzhrani** [comment]
this error message is on mac os, in linux I got more details which point to this [line](https://github.com/jcupitt/libvips/blob/master/libvips/iofuncs/image.c#L2026) which is becuase of the difference in size

**Comment by salzhrani** [comment]
an `info` event is useful, preferably if emitted early or even before pushing to the stream.

**Comment by lovell** [comment]
Commit 86815bc on the `needle` branch adds the `info` event for Stream-based output.

**Comment by lovell** [comment]
v0.14.0 now available via npm, thanks for the original suggestion!
