### ISSUE TITLE
.extract() after composite() not working

### ISSUE THREAD

**Issue by Treant** [lovell/sharp#3671]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
    Memory: 2.83 GB / 15.94 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: ^0.32.1 => 0.32.1

### What are the steps to reproduce?
```
const sharp = require('sharp');
async function cropImage() {
  try {
    await sharp({
      create: {
        width: 800,
        height: 600,
        channels: 4,
        background: { r: 0, g: 0, b: 0, alpha: 0 },
      }
    })
    .composite([{
      input: 'test.png', // test.png is picture 400x300
    }])
    .extract({
      top: 0,
      left: 0,
      width: 200,
      height: 150,
    })
    .toFile('result.png');
  } catch (error) {
    console.log(`An error occurred during processing: ${error}`);
  }
}

cropImage();
```

### What is the expected behaviour?

Expected cropped area of test.png image in file result.png, but i have error:
An error occurred during processing: Error: Image to composite must have same dimensions or smaller

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

See above.

### Please provide sample image(s) that help explain this problem
test.png
![test](https://github.com/lovell/sharp/assets/1297313/d9482c2a-03af-4b7d-ba02-75b9b4b2fb01)

**Comment by lovell** [comment]
You'll need to split this into two pipelines, generating the composited image in the first then extract the required area in the second.

The docs for `composite` hint at this, but I'll update these to make it clearer that `extract` is also included.

> Any resize or rotate operations in the same processing pipeline will always be applied to the input image before composition.

https://sharp.pixelplumbing.com/api-composite#composite

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by lovell** [comment]
@nick-kang Yes, that looks good.
