### ISSUE TITLE
Creating EXIF metadata in PNG output

### ISSUE THREAD

**Issue by constellates** [lovell/sharp#3676]
### What are you trying to achieve?
I am trying to write EXIF data to images in a variety of formats. I have been successful with jpg, webp and avif formats, but can't get it to work with png.

### When you searched for similar issues, what did you find that might be related?
I found #3637 and #3412. Both talk about issues with PNG EXIF data and seem to suggest sharp handles it to some extent, but they're not the same issue.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question
```javascript
const sharp = require('sharp'); // version 0.32.1

async function example() {
  // create jpeg with metadata -----------------------------------
  await sharp({
    create: {
      width: 300,
      height: 300,
      channels: 3,
      background: { r: 0, g: 0, b: 0 }
    }
  })
  .withMetadata({
    exif: {
      IFD0: {
        ImageDescription: 'example'
      }
    }
  })
  .toFile('example.jpg');

  // read jpeg exif metadata -------------------------------------
  const jpgMetadata = await sharp('example.jpg').metadata();
  console.log('logging jpg exif metadata...');
  console.log(jpgMetadata.exif);


  // create png with metadata ------------------------------------
  await sharp({
    create: {
      width: 300,
      height: 300,
      channels: 3,
      background: { r: 0, g: 0, b: 0 }
    }
  })
  .withMetadata({
    exif: {
      IFD0: {
        ImageDescription: 'example'
      }
    }
  })
  .toFile('example.png');

  // read png exif metadata --------------------------------------
  const pngMetadata = await sharp('example.png').metadata();
  console.log('logging png exif metadata...');
  console.log(pngMetadata.exif);
}

example();
```

The jpg format logs an expected exif buffer. The png version logs undefined.

example.jpg
![example](https://github.com/lovell/sharp/assets/4325905/b72ab278-1bb3-4fe2-873f-322c4014af04)

example.png
![example](https://github.com/lovell/sharp/assets/4325905/c72d7d5f-0de1-4cd7-af5b-a8290a42a5a6)

**Comment by lovell** [comment]
Upstream PR for this at https://github.com/libvips/libvips/pull/3510

**Comment by constellates** [comment]
Thanks!

**Comment by Profesor08** [comment]
@lovell  Is there any news when this will be released?

```js
import exif from "exif-reader";
import sharp from "sharp";

await sharp({
  create: {
    width: 300,
    height: 300,
    channels: 3,
    background: { r: 0, g: 0, b: 0 },
  },
})
  .withMetadata({
    exif: {
      IFD0: {
        ImageDescription: "example",
      },
    },
  })
  .toFile("example.png");

const metadata = await sharp("example.png").metadata();

console.log(metadata.exif ? exif(metadata.exif) : metadata.exif);
```

**Comment by lovell** [comment]
@Profesor08 This is dependent on a future possible libvips v8.15.0 release, which is provisionally tagged for inclusion in sharp v0.33.0. Please subscribe for updates.

**Comment by lovell** [comment]
v0.33.0 is now available - please see the new `withExif()` feature.

https://sharp.pixelplumbing.com/api-output#withexif
