### ISSUE TITLE
__dirname error using sharp library in aws lambda configured as module

### ISSUE THREAD

**Issue by MoisesLaris** [lovell/sharp#3681]
### Error: __dirname is not defined in ES module scope
Im trying to use sharp library for aws lambda but im getting `__dirname` error
I have my lambda configured as module (this was configured by setting `type: "module"` in package.json and extension of file is .mjs)

Do you have any idea of why this is happening?

I even tried to configure `__dirname` doing something like this
> import { dirname } from 'path';
> import { fileURLToPath } from 'url';
> const __dirname = dirname(fileURLToPath(import.meta.url));

And using `mlly` library
> import { createCommonJS } from "mlly";
> const { __dirname, __filename, require } = createCommonJS(import.meta.url);

**Comment by lovell** [comment]
This came up recently at #3651 - using `type: "module"` can make Node.js assume all `.js` files are ESM, which is most definitely not the case. Watch out for bundlers that move code around so the "nearest" `package.json` file might contain this property.

https://nodejs.org/docs/latest/api/packages.html#determining-module-system

**Comment by MoisesLaris** [comment]
I'll take a look, thanks

**Comment by djdembeck** [comment]
Did you ever find a solution? I have this issue too using SvelteKit, which requires `type: "module"`

**Comment by sirichaija** [comment]
> 
Hi @djdembeck, I got the same error for SvelteKit. Have you found the solution yet?

**Comment by djdembeck** [comment]
> > 
> 
> Hi @djdembeck, I got the same error for SvelteKit. Have you found the solution yet?
> 
> 

I had to move the sharp dependency from devDependencies to dependencies. This isn't optimal for build, but it works.

**Comment by sirichaija** [comment]
> djdembeck

Thank you very much. It works now.

**Comment by trsiddiqui** [comment]
I have the same issue, but neither do I have type: module in the package.json nor sharp is a dev dependency

**Comment by mwelwankuta** [comment]
Having the same issue in my aws lambda function with serverless
