### ISSUE TITLE
Sharp cannot export AVIF image as WEBP buffer

### ISSUE THREAD

**Issue by glomotion** [lovell/sharp#3685]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp
Need to install the following packages:
  envinfo@7.8.1
Ok to proceed? (y) y

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 698.11 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 3.5.0 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  npmPackages:
    sharp: ^0.32.1 => 0.32.1
```

### What are the steps to reproduce?

run this test node code:

```typescript
import axios from 'axios';
import sharp from 'sharp';

async function doStuff(imageUrl: string) {
  const originImageResponse = await axios({
    url: imageUrl,
    responseType: 'arraybuffer',
  });
  const sharpImageInstance = sharp(originImageResponse.data);
  const processedImageOutput = await sharpImageInstance
    .webp({ quality: 80 })
    .toBuffer({ resolveWithObject: true });
  console.log('@@@@@@@@@@@@', processedImageOutput);
}

doStuff(
  // 'https://towcardimages.s3.amazonaws.com/001/3/00003-hmsvictory-animated-test2.avif',
  // 'https://raw.githubusercontent.com/link-u/avif-sample-images/master/fox.profile1.10bpc.yuv444.avif',
  'https://raw.githubusercontent.com/link-u/avif-sample-images/master/hato.profile0.10bpc.yuv420.avif',
);
```

each AVIF image gives a similar error: 
```
> ts-node ./src-ts/node-debug.ts

[Error: source: bad seek to 328374
heif: Invalid input: Unspecified: Bitstream not supported by this decoder (2.0)]
```

### What is the expected behaviour?

Sharp should export the WEBP image buffer without error

### Please provide sample image(s) that help explain this problem

https://towcardimages.s3.amazonaws.com/001/3/00003-hmsvictory-animated-test2.avif
https://raw.githubusercontent.com/link-u/avif-sample-images/master/fox.profile1.10bpc.yuv444.avif
https://raw.githubusercontent.com/link-u/avif-sample-images/master/hato.profile0.10bpc.yuv420.avif

**Comment by lovell** [comment]
Please see #2688
