### ISSUE TITLE
Get error "extract_area: bad extract area" in second resize call

### ISSUE THREAD

**Issue by ningaro** [lovell/sharp#3687]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```bash
System:
    OS: macOS 12.6.1
    CPU: (8) arm64 Apple M1
    Memory: 96.81 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  npmPackages:
    sharp: 0.32.1 => 0.32.1 
```

### What are the steps to reproduce?

1. Resize any image
2. Extract piece of that image
3. Resize it again
4. Done

### What is the expected behaviour?

I expecting to get cropped part of image resized to 256 x 256 pixels

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

You can easily reproduce this bug by this code:

```ts
import sharp from 'sharp'

const source = sharp({
  create: {
    width: 3270,
    height: 948,
    channels: 3,
    background: '#fff',
  },
})

const bigSource = source.resize(4096, 1024, {
  kernel: 'cubic',
  fit: 'contain',
  background: '#000',
})

bigSource
  .extract({ left: 0, top: 0, width: 512, height: 512 })
  .resize(256, 256)
  .toFile('./build/test.result.png')

```

### Please provide sample image(s) that help explain this problem

_later_

**Comment by lovell** [comment]
Hi, did you see https://sharp.pixelplumbing.com/api-resize#resize ?

> Only one resize can occur per pipeline. Previous calls to resize in the same pipeline will be ignored.

**Comment by ningaro** [comment]
Thank you, I didn't even think it could work that way!
In this case, what is the fastest way to resize an image? 🤔
Only using toBuffer method and create new Sharp object?
