### ISSUE TITLE
Manipulating images with sharp is causing Node to crash

### ISSUE THREAD

**Issue by fr1sk** [lovell/sharp#3688]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1 Pro
    Memory: 34.55 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
  npmPackages:
    sharp: ^0.32.1 => 0.32.1

```

### What are the steps to reproduce?
I have an endpoint that will manipulate some images that are sent to it. I am cloning and changing the image size and getting the buffer of it using Sharp. Manipulation is done in parallel using `Promise.allSettled`. When I run only one image through manipulation, I get the result the first time, but next time I get the segfault. Running multiple images I always get errors. I tried both Node 16 and 18 but the issue is still there, and I am using the latest version of sharp 0.32.1. When I turn manipulation off and just return the images (completely removed sharp) I get no errors.

### What is the expected behaviour?
to not get SIGSEGV or SEGFAULT

```ts
await sharp(image)
        .clone()
        .resize(width)
        .toBuffer()
```

### Please provide sample image(s) that help explain this problem

<img width="721" alt="CleanShot 2023-06-01 at 10 30 38@2x" src="https://github.com/lovell/sharp/assets/15851195/9791bfd0-e861-4ee5-a8bc-22ede5f9065a">
<img width="773" alt="CleanShot 2023-06-01 at 10 29 37@2x" src="https://github.com/lovell/sharp/assets/15851195/907d44c2-ad51-4a4b-b1f7-06d7ad24311d">

**Comment by fr1sk** [comment]
Seems related to https://github.com/lovell/sharp/issues/3677#issue-1721529341, I was able to resolve it by adding `sharp.simd(false)` immediately after importing the `sharp`. However, this is merely a temporary fix rather than a comprehensive solution. Other users may encounter similar issues and waste their time (like I did 😢). It is essential that we take appropriate action to address this problem promptly and incorporate the fix ASAP.

**Comment by fr1sk** [comment]
I can still replicate the issue, but not sure how to get backtrace on SIGSEGV. Is report when running it with `--report-uncaught-exception --report-on-signal --report-on-fatalerror` enough or should I do something else? Can you help?

**Comment by lovell** [comment]
```
$ lldb node app.js
...
(lldb) run
...
wait for crash
...
(lldb) bt
```

**Comment by fr1sk** [comment]
> $ lldb node app.js
> ...
> (lldb) run
> ...
> wait for crash
> ...
> (lldb) bt

```c

Process 63390 stopped
* thread #19, name = 'libvips worker', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000115500776
->  0x115500776: pmullw %mm3, %mm5
    0x115500779: paddw  %xmm2, %xmm5
    0x11550077d: psraw  $0x6, %xmm5
    0x115500782: paddsw %xmm5, %xmm6
  thread #22, name = 'libvips worker', stop reason = EXC_BAD_ACCESS (code=1, address=0x7fffffffffffffff)
    frame #0: 0x000000015087b2ec libvips-cpp.42.dylib`orc_executor_run + 27
libvips-cpp.42.dylib`orc_executor_run:
->  0x15087b2ec <+27>: movq   (%rax), %rax
    0x15087b2ef <+30>: testq  %rax, %rax
    0x15087b2f2 <+33>: je     0x15087b2f7               ; <+38>
    0x15087b2f4 <+35>: popq   %rbp
  thread #24, name = 'libvips worker', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001155015a6
->  0x1155015a6: outsb  (%rsi), %dx
  thread #27, name = 'libvips worker', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000115500776
->  0x115500776: pmullw %mm3, %mm5
    0x115500779: paddw  %xmm2, %xmm5
    0x11550077d: psraw  $0x6, %xmm5
    0x115500782: paddsw %xmm5, %xmm6
  thread #33, name = 'libvips worker', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000115500776
->  0x115500776: pmullw %mm3, %mm5
    0x115500779: paddw  %xmm2, %xmm5
    0x11550077d: psraw  $0x6, %xmm5
    0x115500782: paddsw %xmm5, %xmm6
  thread #34, name = 'libvips worker', stop reason = EXC_BAD_ACCESS (code=1, address=0x7fffffffffffffff)
    frame #0: 0x000000015019f49e libvips-cpp.42.dylib`vips_format_sizeof_unsafe + 14
libvips-cpp.42.dylib`vips_format_sizeof_unsafe:
->  0x15019f49e <+14>: movq   (%rcx,%rax,8), %rax
    0x15019f4a2 <+18>: popq   %rbp
    0x15019f4a3 <+19>: retq
    0x15019f4a4 <+20>: nopw   %cs:(%rax,%rax)
Target 0: (node) stopped.
(lldb) bt
* thread #19, name = 'libvips worker', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x0000000115500776
(lldb)
```

**Comment by lovell** [comment]
Thank you, this looks very much like #3677, let's close this and continue to track it there.
