### ISSUE TITLE
Enhancement: expose libwebp jpeg_like option

### ISSUE THREAD

**Issue by rnavarroz** [lovell/sharp#3690]
Would be it possible to have it in .options for webp with Sharp?

**Comment by lovell** [comment]
I think you're referring to the (internal, undocumented) `emulate_jpeg_size` libwebp advanced encoding config, which the `cwebp` example tool exposes via `--jpeg_like`.

This is not exposed in libvips, and I'm unsure of the value in doing so.

When set, it alters the calculation of the "base coefficient" from the provided "quality". Perhaps you could reverse engineer the alternative (i.e. higher) "quality" value for yourself using its logic:

https://github.com/webmproject/libwebp/blob/cba300781f4eea9dd957990c6db3977718d4338a/src/enc/quant_enc.c#L323-L355

I think the summary here might be: if you care about quality, increase the "quality" value a bit more.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
