### ISSUE TITLE
Automatically resizing SVG image to fit its content

### ISSUE THREAD

**Issue by nbouvrette** [lovell/sharp#3691]
### What are you trying to achieve?

I am trying to convert a few SVG images into PNG format for one of my projects and doing this dynamically avoid having to maintain multiple versions of the same asset. Sharp has been great at doing this but I ran into this issue.

Some of my SVG images have no "padding" meaning that their strokes are pretty much the same dimension as the viewport.

When converting those images to SVG, I noticed that some of the "shadow" effects are being truncated. See an example below:

<img width="277" alt="image" src="https://github.com/lovell/sharp/assets/6453322/7c204f75-0a0f-4fe7-9bc7-8e87bedbb09d">

I tried to implement some sort of auto-margin/resizing code but I either I am doing something wrong, or the way the rastering is done won't allow me to do this. Here is a sample of the code:

```ts
sharp(svgContent)
    .metadata()
    .then(async (metadata) => {
      const { width, height } = metadata

      if (!width || !height) {
        throw new Error(`error getting svg image dimensions`)
      }

      // Increase the image dimensions to get a better quality PNG image.
      const newWidth = width * 4
      const newHeight = height * 4

      // Add transparent margins around the image since converting to PNG might require extra space to avoid cropping-like effects.
      const marginWidth = Math.round(newWidth * margin)
      const marginHeight = Math.round(newHeight * margin)

      // Create a new canvas with increased dimensions.
      const canvasWidth = newWidth + 2 * marginWidth
      const canvasHeight = newHeight + 2 * marginHeight

      const newSvgContent = await sharp(svgContent)
        .resize({ width: newWidth, height: newHeight, fit: 'inside' })
        .toBuffer()
      const buffer = await sharp({
        create: {
          width: canvasWidth,
          height: canvasHeight,
          channels: 4,
          background: { r: 0, g: 0, b: 0, alpha: 0 },
        },
      })
        .composite([{ input: newSvgContent, left: marginWidth, top: marginHeight }])
        .png()
```

### When you searched for similar feature requests, what did you find that might be related?

I search for "truncate" or "SVG" and couldn't find any opened or closed issue on this topic.

### What would you expect the API to look like?

I'm not sure but I was thinking of something like `.fitToContent()` to automatically resize the SVG's size to fit to content, including `stoke-width` - and maybe a nice to add `.addMargin()` that would make it simpler to add margins... or maybe when converting to other formats it could automatically detect the "shadows" and or have some kind of option to automatically handle this?

### What alternatives have you considered?

I thought about adding margins inside the SVG itself but from my research, there isn't an easy way to do this while keeping the content centered because there is no easy way to center content, and there is no concept of "margin" for SVG markup.

**Comment by lovell** [comment]
Typically the `viewBox` property of an SVG image defines the visible area. Are you able to share an example SVG image where this isn't working as expected?

**Comment by nbouvrette** [comment]
You're right @lovell - I should have provided a bit more context but I was trying to keep the issue simple. Basically, I am using [Svgr's Webpack](https://www.npmjs.com/package/@svgr/webpack) loader to dynamically transform SVG properties without having multiple versions of the same image.

So, for example, I can change the color of the SVG, but where this is causing issues is if I change the `strokeWidth`. When I do change the `strokeWidth` of an SVG and use it as an SVG image I can have the same image behave like this:

`<Phone stroke-width={0.2} />`

<img width="138" alt="image" src="https://github.com/lovell/sharp/assets/6453322/e291f6e6-458a-4359-8a84-5f3ba0c03ce5">

`<Phone stroke-width={1.2} />`

<img width="141" alt="image" src="https://github.com/lovell/sharp/assets/6453322/4c366898-eceb-4aa2-baf8-980168996c3a">

This is the image I used for the example:

```svg
<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
  <g
    class="center"
    fill="none"
    stroke="currentColor"
    stroke-linecap="round"
    stroke-linejoin="round"
    stroke-width="currentStrokeWidth"
    transform="matrix(1,0,0,1,0,0)"
  >
    <path
      d="M15.04,22.39l.012.007a5.533,5.533,0,0,0,6.884-.755l.774-.774a1.846,1.846,0,0,0,0-2.609L19.449,15a1.846,1.846,0,0,0-2.609,0h0a1.843,1.843,0,0,1-2.608,0L9.014,9.781a1.846,1.846,0,0,1,0-2.609h0a1.843,1.843,0,0,0,0-2.608L5.754,1.3a1.846,1.846,0,0,0-2.609,0l-.774.774a5.535,5.535,0,0,0-.756,6.884l.008.012A49.935,49.935,0,0,0,15.04,22.39Z"
    />
  </g>
</svg>
```

Having said that, while doing more tests, I did notice that if I put the `strokeWidth` thick enough, then the SVG image itself  also starts to be truncated.. which  might be the actual source of my issue:

<img width="279" alt="image" src="https://github.com/lovell/sharp/assets/6453322/28e0ed83-8109-4c6b-9fb2-a2de08c4d46b">

If I change the viewbox to `35` for example, this is what happens:

<img width="261" alt="image" src="https://github.com/lovell/sharp/assets/6453322/1fcc6adb-6eb5-43e9-9631-21535667bd38">

As far as I know, there isn't a way to recenter the `<g>` path in the middle of the viewbox, at least not using SVG properties - is this something Sharp could help with?

**Comment by nbouvrette** [comment]
Ok well apparently I found a solution to this, and it does work with Sharp, by using negative values in the viewbox this is the type of result I can get:

`<Phone stroke-width={3} viewBox="-2 -2 28 28" />`

<img width="187" alt="image" src="https://github.com/lovell/sharp/assets/6453322/7e165ac9-5525-4edf-bd8a-2ecca76e6e99">

I spent quite some time yesterday looking for this solution so apologies for opening this issue.. hopefully if anyone find it, it can help them as well.

I'm not sure if there could be anything on the Sharp side to make this easier but I think I can probably tweak my code and get rid of the margin stuff to resize the viewBox instead.
