### ISSUE TITLE
How to forcefully reduce sharp's cpu usage and accept appropriate reduction in running speed?

### ISSUE THREAD

**Issue by FuHongBiao** [lovell/sharp#3695]
## Question about an existing feature
At present, I use k8s to deploy a pod containing sharp, but when the input image is too large (about 10mb), the top command to view the cpu utilization even exceeds 100%, which may cause the container to restart. This is not what I want. I It is hoped that the container will not restart the order to accept the slowdown. I tried using the command but it didn't work.
`
      process.env.UV_THREADPOOL_SIZE =1;
      sharp.concurrency(0.4);
`
The following is the cpu configuration of the pod：
`
cpu: "0.5"
memory: 2Gi
`
### What are you trying to achieve?
How can I limit the cpu usage to prevent the container from restarting constantly?

**Comment by lovell** [comment]
> sharp.concurrency(0.4);

This should be an integral value, and if not will default to the number of cores, either virtual or physical (which one depends on various things), so you probably want to use `sharp.concurrency(1);`

You've not provided any information about the formats you're using. For anything that is relatively CPU-heavy such as AVIF then you may need to give it more CPU time as `cpu: "0.5"` may not be appropriate for a CPU-bound task.

**Comment by FuHongBiao** [comment]
> > sharp.concurrency(0.4);
> 
> This should be an integral value, and if not will default to the number of cores, either virtual or physical (which one depends on various things), so you probably want to use `sharp.concurrency(1);`
> 
> You've not provided any information about the formats you're using. For anything that is relatively CPU-heavy such as AVIF then you may need to give it more CPU time as `cpu: "0.5"` may not be appropriate for a CPU-bound task.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
