### ISSUE TITLE
Is it possible to access trim offsets for all sides and not just top and left?

### ISSUE THREAD

**Issue by gugiserman** [lovell/sharp#3696]
### What are you trying to achieve?

For my specific use case I need to have access to the size that was trimmed from all sides and not just top and left (trimOffsetTop, trimOffsetLeft) returned by the trim method.

The main reason is that I need to save the original position that the actual content had within the transparent background in its original canvas, so that I'm able to "recreate" the image if needed for example, by repositioning the content in a different canvas later.

In my cases there is no guarantee the top/bottom transparent space are equal, and the same applies to left/right as well.

Is it possible to achieve this with sharp right now? I could not find any related issues or discussions and I'm yet to read through the source code.

Something tells me I should be able to achieve this without sharp, before trimming, but I didn't want to come up with a solution that acts different than the `trim` and end up with inconsistent saved data vs output.

Thanks!

**Comment by lovell** [comment]
You can calculate this using the input and output dimensions.
```
right offset = input width - output width - left offset
bottom offset = input height - output height - top offset
```

**Comment by gugiserman** [comment]
> You can calculate this using the input and output dimensions.
> 
> ```
> right offset = input width - output width - left offset
> bottom offset = input height - output height - top offset
> ```

I'm dumb!
Thanks!
