### ISSUE TITLE
blur -> threshold chaining doesn't work as expected

### ISSUE THREAD

**Issue by thot-experiment** [lovell/sharp#3697]
- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What are the steps to reproduce?

When chaining `.blur().threshold()` the threshold step is not perfomed

### What is the expected behaviour?

`.threshold()` should be performed

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```js
import sharp from 'sharp'
import fs from 'fs/promises'

let file = await fs.readFile('test.png')

let onepass = await sharp(file)
.blur(10)
.threshold()
.toBuffer()

//as a temporary workaround one can do a second pass rather than chaining operations
let twopass = await sharp(onepass)
.threshold()
.toBuffer()

fs.writeFile('blurry_but_not_thresholded.png', onepass)
fs.writeFile('blurry_and_thresholded.png', twopass)
```

#### `test.png`
![test](https://github.com/lovell/sharp/assets/94414189/34b1136d-ed6d-43f3-a1fe-11bb476e8e7a)

#### `blurry_but_not_thresholded.png`
![blurry_but_not_thresholded](https://github.com/lovell/sharp/assets/94414189/82faa1c3-2631-41cf-bb56-abb72ad36480)

#### `blurry_and_thresholded.png`
![blurry_and_thresholded](https://github.com/lovell/sharp/assets/94414189/9d22c9ea-8b3a-4c39-8c8a-bf9d5e189fb9)

**Comment by lovell** [comment]
Hi, your approach to split this task into two passes is correct. (My understanding is that threshold then blur is more generally useful, or at least this was the case when this feature was added in 2015.)

**Comment by thot-experiment** [comment]
Is there guidance on how this is supposed to work? Intuitively it seems like I should be able to chain things in whatever order I want but this isn't the case? There's some internal order of precedence? Perhaps there's something I missed in the docs? I'm definitely intending to use the operations in the order listed here.

**Comment by lovell** [comment]
Please see #241 for discussion about future possible API improvements.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
