### ISSUE TITLE
Does sharp support BMFont format (.fnt)

### ISSUE THREAD

**Issue by VladimirMikulic** [lovell/sharp#3699]
Hi! I was wondering whether sharp supports BMFont format (.fnt)?
We're currently migrating from Jimp to Sharp and we write text with font files in .fnt format.
(see "Writing Text" section here https://www.npmjs.com/package/jimp)

I tried using those .fnt files with sharp (fontfile property), but they didn't work. (it works with ttf files)

**Comment by lovell** [comment]
Freetype is used for glyph rendering.

https://freetype.org/freetype2/docs/ft2faq.html#general-what

> It supports both bitmap and scalable formats, including TrueType, OpenType, Type1, CID, CFF, Windows FON/FNT, X11 PCF

I don't think it supports BMFont. If you'd prefer to use bitmap fonts, PCF (Portable Compiled Format) would be a good option.

**Comment by VladimirMikulic** [comment]
Thanks a lot for a fast reply @lovell! That helps.
