### ISSUE TITLE
ERROR: Download from https://dl.bintray.com/lovell/sharp/libvips-8.2.2-lin.tar.gz failed

### ISSUE THREAD

**Issue by binarykitchen** [lovell/sharp#370]
```
> sharp@0.13.1 install /var/www/videomail/staging/source/node_modules/sharp
> node-gyp rebuild

ERROR: Download from https://dl.bintray.com/lovell/sharp/libvips-8.2.2-lin.tar.gz failed: getaddrinfo ENOTFOUND akamai.bintray.com akamai.bintray.com:443
gyp: Call to 'LDD_VERSION="ldd (Ubuntu EGLIBC 2.19-0ubuntu6.7) 2.19
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper." node -e "require('./binding').download_vips()"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.17-rh17.xenU
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/videomail/staging/source/node_modules/sharp
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 4.1.17-rh17.xenU
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
```

Any ideas?

**Comment by lovell** [comment]
> ERROR: Download from https://dl.bintray.com/lovell/sharp/libvips-8.2.2-lin.tar.gz failed: getaddrinfo ENOTFOUND akamai.bintray.com akamai.bintray.com:443

Hello, this looks like a temporary DNS resolution problem somewhere between your system and Bintray/Akamai.

**Comment by binarykitchen** [comment]
you are right. not happening anymore. must have been a temporary glitch.

do you think you could add a loop and retry this at least three times before printing the error?

**Comment by lovell** [comment]
Temporary DNS resolution or network problems will affect more than just this module. If retry semantics are required, I'd recommend these be used at `npm install` level. 

Perhaps try something like:
```sh
while ! npm install; do sleep 1; done
```

**Comment by binarykitchen** [comment]
mmmmhh, good point. does this while loop exit on success?

**Comment by lovell** [comment]
> "does this while loop exit on success?"

Yes.

**Comment by binarykitchen** [comment]
great thanks. will add that to my batch. case closed.

**Comment by binarykitchen** [comment]
hmmm, @lovell, that didn't work. `while ! npm install; do sleep 1; done` seems to run forever

**Comment by lovell** [comment]
I guess something else is making `npm install` exit with a non-zero error code.

This beyond the realm of sharp now. Perhaps one of the following may help:

http://unix.stackexchange.com/questions/82598/how-do-i-write-a-retry-logic-in-script-to-keep-retrying-to-run-it-upto-5-times

http://serverfault.com/questions/80862/bash-script-repeat-command-if-it-returns-an-error

**Comment by binarykitchen** [comment]
right, sorry, thanks

**Comment by lovell** [comment]
No probs, good luck!

**Comment by tjohnman** [comment]
Sorry about commenting on such an old issue, but a Google search brought me here and I might not be the last. I'm getting this exact same problem and it doesn't seem to go away.

The URL this time is: https://dl.bintray.com/lovell/sharp/libvips-8.5.5-linux-x64.tar.gz

It looks like Bintray has been sunsetted:

> On May 1, 2021, the sunset will impact all existing Bintray users. Bintray users will be blocked and will no longer be able to use the Bintray service. This includes existing software distribution, account administrative access, UI access, and the REST API.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
