### ISSUE TITLE
how do i use sharp on linux?

### ISSUE THREAD

**Issue by kkeolmusae** [lovell/sharp#3705]
It was okay on mac, but when I deployed it to linux environment, there was a problem.
```bash
Something went wrong installing the "sharp" module
Cannot find module '../build/Release/sharp-linuxmusl-x64.node'
...
Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current linuxmusl-x64 runtime: "npm install --platform=linuxmusl --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
```

how do i fix it? I tried to add it to the docker file as follows, but it still doesn't work.

```dockerfile
...
COPY package.json package.json
COPY yarn.lock yarn.lock
RUN yarn install --immutable --immutable-cache --check-cache

# ADD
RUN rm -r node_modules/sharp
RUN yarn add --platform=linuxmusl --arch=x64 sharp@0.32.1

# Build
COPY src src
COPY tsconfig.json tsconfig.json
RUN yarn tsc
...
```

**Comment by kkeolmusae** [comment]
```
RUN yarn install --immutable --immutable-cache --check-cache

RUN rm -r node_modules/sharp
RUN SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm_config_arch=x64 npm_config_platform=linux yarn add sharp@0.32.1

# Build
COPY src src
```

**Comment by lovell** [comment]
Probably the simplest option here is to avoid copying `node_modules` from outside the container, so that running `yarn install` (without all those extra flags) inside the container will do so for the relevant platform.

If you still require help, please provide a complete `Dockerfile` that allows someone else to reproduce.

**Comment by kkeolmusae** [comment]
sir... i solve this problem...

The answer is 
`RUN SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm_config_arch=x64 npm_config_platform=linuxmusl yarn add sharp@0.32.1` 

Thank you for your help. I will try to be a great developer like you.

**Comment by cyango** [comment]
I'm trying all these solutions but still getting :

Cannot find module '../build/Release/sharp-linuxmusl-arm64v8.node'

**Comment by lovell** [comment]
@cyango If you're still having problems, please open a new [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) and try to answer as many of the questions as possible.

**Comment by lovell** [comment]
@mackignacio Adding platform-specific dependencies is not recommended as it potentially creates a future failure when dependencies get out of sync (I'm aware some people are suggesting it as a temporary workaround for an npm bug).

If you're working with multiple platforms, please see https://sharp.pixelplumbing.com/install#cross-platform for the suggested approach.
