### ISSUE TITLE
Artifacts in generated thumbnails on `glibc`-based images

### ISSUE THREAD

**Issue by adriaanmeuris** [lovell/sharp#3707]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.
**0.32.1**

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?
```
  System:
    OS: macOS 13.4
    CPU: (12) arm64 Apple M2 Pro
    Memory: 73.73 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  npmPackages:
    sharp: ^0.32.1 => 0.32.1 
```

### What are the steps to reproduce?
Please find a reproduction repository here: https://github.com/adriaanmeuris/sharp-test. You can can run it with `npm run dev`.

### What is the expected behaviour?
All thumbnails should be generated without artifacts.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem
Please find a reproduction repository here: https://github.com/adriaanmeuris/sharp-test. You can can run it with `npm run dev`.

### Please provide sample image(s) that help explain this problem
We're using `sharp` in production and see some artifacts generated in some thumbnails. We've narrowed down that this only occurs when having a lot of allocations / memory usage. 

We've looked at https://sharp.pixelplumbing.com/install#linux-memory-allocator and run the same tests in a `musl` based image, and don't see any issues there. Unfortunately, our base image is `glibc`-based and we can't switch to `musl` just yet due to dependencies on other packages.

Here our findings:
- using regular `toFile` output generates less artifacts (color shifts or sometimes a black image)
- using a pipeline based approach with streams produces more artifacts
- using `jemalloc` as suggested still produces artifacts

We're not sure if this is expected behaviour and if using another memory allocator would help. Also, we're running these tests on Apple Silicon which is something we did not investigate any further as we're running them in a Docker container with `FROM --platform=linux/amd64` and use Rosetta for x86/amd64 emulation.

Here is our base image (PNG file with transparency): [base.png.zip](https://github.com/lovell/sharp/files/11837439/base.png.zip)

This is an overview of artifacts:

### Using `toFile`:
| Good result | Color shift | Completely black |
|----------|----------|----------|
|   ![base-thumb-8](https://github.com/lovell/sharp/assets/16230038/58c992b0-d37e-4b01-83d2-a9dccec56bc4)   |   ![base-thumb-9](https://github.com/lovell/sharp/assets/16230038/0efd67f5-3b05-4c90-b1d0-d731c9f86edc)   |   ![base-thumb-12](https://github.com/lovell/sharp/assets/16230038/8692e8a2-e232-4ad3-a0c4-5912fcc7b350)   |

### Using a pipeline / streams:
| Color shift | Completely white | Lines |
|----------|----------|----------|
|   ![base-thumb-8](https://github.com/lovell/sharp/assets/16230038/8216d68d-ca8c-4f94-a70e-61aa315b1c0b)   |   ![base-thumb-7](https://github.com/lovell/sharp/assets/16230038/d61343d6-cef9-439c-ad8d-4a0d7ebc671a) |   ![base-thumb-75](https://github.com/lovell/sharp/assets/16230038/02d5d430-a80b-49fe-9d59-1c45d62be7d9)   |

### With `jemalloc` enabled:
| Artifacts 1 | Artifacts 2 |
|----------|----------|
|   ![base-thumb-37](https://github.com/lovell/sharp/assets/16230038/ae60668e-b0a8-4b74-a50a-9f3e8951f4db)   |   ![base-thumb-47](https://github.com/lovell/sharp/assets/16230038/ba6530f3-8efd-4cce-b92c-a159678ae309)   |

I can confirm none of these issues happen on `musl`-based images.

We're wondering if this is expected behaviour and if there's anything from our side we can do to improve results.

**Comment by kleisauke** [comment]
I could not reproduce this on Fedora 38 x86_64 with:
```console
$ git clone https://github.com/adriaanmeuris/sharp-test.git sharp-issue-3707
$ cd sharp-issue-3707
$ mkdir outputs
$ ./docker-dev.sh
$ expected_sha256=$(sha256sum "outputs/base-thumb-0.jpg" | awk '{ print $1 }')
$ for file in outputs/*.jpg; do echo "$expected_sha256 $file" | sha256sum --check --quiet; done
$ echo $?
0
```

i.e. deterministic results and the output of `base-thumb-0.jpg` is without any distortion.

Are you able to reproduce this using `sharp.simd(false);`?
```diff
--- a/index.js
+++ b/index.js
@@ -1,6 +1,8 @@
 const { createReadStream, createWriteStream } = require('fs');
 const sharp = require('sharp');
 
+sharp.simd(false);
+
 async function createThumbWithPipeline(outputPath) {
   const sharpOperations = sharp({
     failOn: 'none',
```

**Comment by adriaanmeuris** [comment]
Thank you for looking into this.

It seems I can not consistently reproduce this - on the first run I also don't get any issues. However on subsequent runs or when increasing the amount of thumbnails generated I can.

I've updated the repository so the checksums are checked while creating the thumbnails, only the ones that don't match the checksum are stored to disk. I've increased the amount of thumbs to generate to `500`. Wondering if you can reproduce this now, it seems memory usage related.

Disabling SIMD seems to work! Any pointers as to why this seems to resolve the distortions?

**Comment by lovell** [comment]
I suspect this may relate to the liborc thread-safety issue in #3677

**Comment by adriaanmeuris** [comment]
Great, I'll follow up there as it's likely that's the cause of the problem.

**Comment by kleisauke** [comment]
FWIW, I could not reproduce this with the updated repository either, so it could also be a bug in Rosetta's SSE* emulation layer.

For the jemalloc test case, it might be worth lowering the concurrency to 1 to rule things out. This would correspond to the default concurrency when using glibc memory allocator (commit 5a9cc835b33001c805a0d5fcb05e6d71135cc79d).
