### ISSUE TITLE
Issue converting large TIFF image to AVIF using Sharp 0.32.1

### ISSUE THREAD

**Issue by luckykellan** [lovell/sharp#3708]
I encountered an issue while trying to convert a TIFF image of size 2.3 GB to AVIF format using Sharp 0.32.1. Here is the code I used:
```javascript
const sharp = require('sharp');

const data = await sharp('1.tif', { limitInputPixels: false })
    .avif({ effort: 2 })
    .toFile('1.avif', (err, info) => {
        console.log(err);
        console.log(info);
    });
```
I am running the code on a Mac environment. The conversion process completes without any error messages, but the generated AVIF file is empty. Instead, I receive the following message: "Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)."

Please provide guidance on how to resolve this issue.

**Comment by lovell** [comment]
What are the dimensions of the image? This might be the same thing as #3701

**Comment by luckykellan** [comment]
182108x7595, Is there any temporary workaround available at the moment?

**Comment by lovell** [comment]
Thanks, a width of 182108 is well above the 65535 limit on HEIF (AVIF and HEIC) images dimensions.

We've just patched libvips to limit the output dimensions of HEIF images to 16384x16384 to match other software - please see https://github.com/libvips/libvips/issues/3509

**Comment by lovell** [comment]
Let's track this at #3701
