### ISSUE TITLE
Consider using prebuildify

### ISSUE THREAD

**Issue by charsleysa** [lovell/sharp#3709]
Please consider switching to using prebuildify and shipping the prebuilt binaries with the npm package so that it can be used in environments that don't/can't execute postinstall scripts.

This would open up support for environments like deno, and it's also the recommended configuration given by prebuild-install/prebuildify (see https://github.com/prebuild/prebuild-install#note).

**Comment by lovell** [comment]
Hi, please see https://github.com/lovell/sharp/issues/2741#issuecomment-853359390 for why prebuildify is probably the wrong solution (I'm one of the prebuild maintainers).

I'm hoping cross-package-manager support for `distributions` in `package.json`, a possible outcome of https://github.com/npm/rfcs/pull/519, will be a much better solution.

**Comment by charsleysa** [comment]
Would you consider using prebuildify just for shipping the `.node` files while keeping the libvips files still separate?
If I understand correctly, this should allow sharp to work by using a globally installed libvips without needing to run any npm install scripts as the missing component is the `.node` file.

**Comment by lovell** [comment]
A globally-installed libvips necessitates the compilation of sharp from source.

https://sharp.pixelplumbing.com/install#building-from-source

You mentioned Deno - see https://github.com/denoland/deno/issues/16164 for proposed opt-in install script support, a sensible compromise until `distributions` becomes a thing.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
