### ISSUE TITLE
Guard use of smartcrop premultiplied option

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#3710]
Commit https://github.com/lovell/sharp/commit/a8645f0f381558f00b234282d6742697cb5ed194 included in v0.32.1 takes advantage of a feature of the forthcoming libvips 8.15. Use of this API can generate a warning when unavailable so should be guarded with a version check.

See https://github.com/gatsbyjs/gatsby/issues/38257

**Comment by aquinaso** [comment]
Thanks a lot, Lovell.

I use sharp library, and this instruction did work for me.
I updated sharp library.

> npm install sharp@latest
