### ISSUE TITLE
 There is  a memory leak issue on processing specific image

### ISSUE THREAD

**Issue by rayne-jiang** [lovell/sharp#3712]
The original image size is **165kb**, however when I try to run the following code for 10 times, the memory usage increased to **300MB**, seems there is a **memory leak issue**, can help?

The specific image link:
https://d2ncjxd2rk2vpl.cloudfront.net/twelvesshokudo/product/63821cf601fcd000072169aa/3bd4b561-c470-4996-9cff-2073662476aa

Here is my code for reproduce in Typescript
```
async function resizeAndConvertImage(imageUrl: string): Promise<void> {
  try {
    // Download the image data using Axios and pipe it to a `sharp` transform stream to resize and convert it
    const response = await axios(imageUrl, { responseType: 'arraybuffer' });

    const sharpResult = await sharp(response.data).resize(419, 419).jpeg();

    const base64ImageBuffer= await sharpResult.toBuffer();

    const base64ImageString = base64ImageBuffer.toString('base64');

    return ;
  } catch (error) {
    console.error(`Error downloading the image: ${error}`);
    throw error;
  }
}

resizeAndConvertImage('https://d2ncjxd2rk2vpl.cloudfront.net/twelvesshokudo/product/63821cf601fcd000072169aa/3bd4b561-c470-4996-9cff-2073662476aa')
```

**Comment by lovell** [comment]
Please ensure you've fully read and understood everything discussed in https://github.com/lovell/sharp/issues/955

**Comment by lovell** [comment]
Closing as this is unlikely to be a leak and is more likely to represent the peak RSS requirement plus effects of the allocator holding on to memory because the OS hasn't asked for it back.
