### ISSUE TITLE
Image color changes when processed by sharp

### ISSUE THREAD

**Issue by adityapatadia** [lovell/sharp#3714]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M2
    Memory: 162.55 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - /opt/homebrew/opt/node@18/bin/node
    npm: 9.5.1 - /opt/homebrew/opt/node@18/bin/npm
  npmPackages:
    sharp: 0.32.1 => 0.32.1
```

### What are the steps to reproduce?

Process a sample image with sharp and it will change its color especially red.

### What is the expected behaviour?

Check the red color. It should not change.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```
import sharp from "sharp";

let transformer = sharp("./input.jpeg").toFile("./output.jpeg",() =>{});
```

### Please provide sample image(s) that help explain this problem

Linked here.
![input](https://github.com/lovell/sharp/assets/1086617/066c23cd-2229-41c7-a2bf-48d821b580fb)
![output](https://github.com/lovell/sharp/assets/1086617/6037f8f7-ac03-4376-b7ce-569e11dedbd0)

**Comment by lovell** [comment]
The second image uses 4:2:0 subsampling:
```
$ identify -verbose 249775478-6037f8f7-ac03-4376-b7ce-569e11dedbd0.jpeg | grep JPEG
  Format: JPEG (Joint Photographic Experts Group JFIF format)
  Compression: JPEG
  JPEG-Quality: 80
  JPEG-Colorspace: 2
  JPEG-Colorspace-Name: RGB
  JPEG-Sampling-factors: 2x2,1x1,1x1
```
whereas the first image does not:
```
$ identify -verbose 249775446-066c23cd-2229-41c7-a2bf-48d821b580fb.jpeg | grep JPEG
  Format: JPEG (Joint Photographic Experts Group JFIF format)
  Compression: JPEG
  JPEG-Quality: 86
  JPEG-Colorspace: 2
  JPEG-Colorspace-Name: RGB
  JPEG-Sampling-factors: 1x1,1x1,1x1
```

**Comment by adityapatadia** [comment]
Is it on by default? Converting it to webp also gives same result.On 29-Jun-2023, at 7:06 PM, Lovell Fuller ***@***.***> wrote:﻿
The second image uses 4:2:0 subsampling:
$ identify -verbose 249775478-6037f8f7-ac03-4376-b7ce-569e11dedbd0.jpeg | grep JPEG
  Format: JPEG (Joint Photographic Experts Group JFIF format)
  Compression: JPEG
  JPEG-Quality: 80
  JPEG-Colorspace: 2
  JPEG-Colorspace-Name: RGB
  JPEG-Sampling-factors: 2x2,1x1,1x1

whereas the first image does not:
$ identify -verbose 249775446-066c23cd-2229-41c7-a2bf-48d821b580fb.jpeg | grep JPEG
  Format: JPEG (Joint Photographic Experts Group JFIF format)
  Compression: JPEG
  JPEG-Quality: 86
  JPEG-Colorspace: 2
  JPEG-Colorspace-Name: RGB
  JPEG-Sampling-factors: 1x1,1x1,1x1

**Comment by adityapatadia** [comment]
Btw, I have tried this code and it still gives same result:

```
import sharp from "sharp";

let transformer = sharp("./input.jpeg").jpeg({chromaSubsampling: '4:4:4'}).toFile("./output.jpeg",() =>{});
```

**Comment by omprakashyadav** [comment]
Anyone any luck?

**Comment by adityapatadia** [comment]
Hi @lovell any luck with this? If you can provide some workaround, it would be best. One of our customer is stuck because of this.

**Comment by lovell** [comment]
In addition to the use of chroma subsampling, the first image contains an embedded P3 RGB profile and the second image is profile-less sRGB. Do you only see a "difference" on a wide-gamut display?

Use [withMetadata](https://sharp.pixelplumbing.com/api-output#withmetadata) to specify an output profile, plus experiment using [pipelineColourspace](https://sharp.pixelplumbing.com/api-colour#pipelinecolourspace) with a 16 bpp colourspace when working with wide-gamut images.

**Comment by adityapatadia** [comment]
Thanks!! This worked. Yes we can re-produce this only on wide-gamut display.
We now have to identify input image based on ICC profile and then make sure we process them correctly.
