### ISSUE TITLE
Firebase cloud function:  VipsOperation: class dzsave not found

### ISSUE THREAD

**Issue by diego9497** [lovell/sharp#3715]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [ ] Running `node -e "require('sharp')"` completes without error. (I don't know how to execute it in firebase cloud functions env)

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What are the steps to reproduce?

I just try to call `.tile()` and it fails, the same cloud function works fine in the emulators (I have libvips installed globally on my computer), but is failing with the deployed cloud function.

Other functions like `.toFormat` are working fine in the deployed cloud functions and were successfully uploaded to the bucket.

### What is the expected behaviour?

Generate the zip file.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

`  generateDZI = (req: functions.https.Request, resp: functions.Response<any>) => {
      const form = new formidable.IncomingForm();
  
    return new Promise((resolve, reject) => {
      form.parse(req, async function (err: any, fields: any, files: { file: any; }) {
        const file = files.file;
  
        if (!file) {
          reject(`no file to upload, please choose a file. ${JSON.stringify(files)}`);
          return;
        }
  
        const filePath = file.path;
  
        const fileDir = path.dirname(filePath);
        const DZIFilePath = path.normalize(path.format({ dir: fileDir, name: "test-dzi", ext: ".zip" }));
  
        const bucket = admin.storage().bucket();
  
          return sharp(filePath)
            .tile({
              size: DEFAULT_TILE_SIZE,
            })
            .toFile(DZIFilePath)
            .then(() => {
              // Uploading the zip file.
              return bucket.upload(DZIFilePath, { destination: "new-zone-map/12345/test-dzi.zip" });
            })
            .then((response: any) => {
              console.log("DZI image uploaded");
              fs.unlinkSync(DZIFilePath);
              fs.unlinkSync(filePath);
  
              resolve({ response });
              return;
            })
            .catch((err: any) => {
              reject("Failed to upload: " + JSON.stringify(err, replaceErrors));
            });
      });
    })
      .then((response) => {
        resp.status(200).json({ response });
        return;
      })
      .catch((err) => {
        resp.status(500).json({ error: err });
        return;
      });
   }`

### Please provide sample image(s) that help explain this problem

<img width="1137" alt="image" src="https://github.com/lovell/sharp/assets/43687883/8aae6d74-884a-4ac9-bb0e-f3332b713533">

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/3581
