### ISSUE TITLE
What is gravity?

### ISSUE THREAD

**Issue by Arcanorum** [lovell/sharp#3718]
## Question about an existing feature

I see `gravity` as an option all over the API, but I can't find anywhere in the docs that actually explains what it is. Is it like alignment or some kind of anchor point or...?

**Comment by lovell** [comment]
Hi, did you see https://sharp.pixelplumbing.com/api-resize#resize ?

> When using a fit of `cover` or `contain`, the default position is centre. Other options are:
> * sharp.gravity: north, northeast, east, southeast, south, southwest, west, northwest, center or centre.

This allows you to decide which part of the image to keep when the dimensions used in a resizing operation result in removal of some of the image.

**Comment by Arcanorum** [comment]
Yes I see the context differs a bit, such as with using composite it is basically the "wrap direction".
I figured "direction" would be a more commonly understood term, but perhaps that may get interpreted as applying some kind of rotation?
