### ISSUE TITLE
Problems running Sharp on AWS Lambda

### ISSUE THREAD

**Issue by alixaxel** [lovell/sharp#372]
I've installed version 0.13.1 from an Amazon Linux AMI 2015.09.2 EC2 instance. Since `curl` and `pkg-config` are already available on the machine, I just executed the `preinstall.sh` script via cURL (no errors popped up) and ran `npm install sharp` afterwards (on Node 0.10.42 / NPM 1.3.6).

This process seems to be pretty equivalent to what is described on the [AWS Lambda install instructions](http://sharp.dimens.io/en/latest/install/#aws-lambda).

I zipped the `node_modules/sharp` folder and packaged it with my existing Lambda function, but after deploying the function and executing the first test it doesn't seem that libvips is getting compiled statically.

```
{
  "errorMessage": "libvips-cpp.so.42: cannot open shared object file: No such file or directory",
  "errorType": "Error",
  "stackTrace": [
    "Module.load (module.js:356:32)",
    "Function.Module._load (module.js:312:12)",
    "Module.require (module.js:364:17)",
    "require (module.js:380:17)",
    "Object.<anonymous> (/var/task/node_modules/sharp/index.js:12:13)",
    "Module._compile (module.js:456:26)",
    "Object.Module._extensions..js (module.js:474:10)",
    "Module.load (module.js:356:32)",
    "Function.Module._load (module.js:312:12)",
    "Module.require (module.js:364:17)",
    "require (module.js:380:17)",
    "Object.<anonymous> (/var/task/index.js:3:13)",
    "Module._compile (module.js:456:26)",
    "Object.Module._extensions..js (module.js:474:10)",
    "Module.load (module.js:356:32)",
    "Function.Module._load (module.js:312:12)"
  ]
}
```

The uncompressed `node_modules/sharp` directory weights only 7.5 MB, which seems to be surprisingly low compared to the discussion over at https://github.com/lovell/sharp/issues/169 and https://github.com/lovell/sharp/issues/292.

Am I missing anything obvious? :)

**Comment by lovell** [comment]
Hello, running `preinstall.sh` to install a system-wide copy of libvips is not required (nor is mentioned in the AWS instructions?).

**Comment by alixaxel** [comment]
@lovell Right, I was something obvious after all. ;) Thanks for the quick reply!
