### ISSUE TITLE
Corrupted output upon (specific) JPG to AVIF conversion

### ISSUE THREAD

**Issue by Helcostr** [lovell/sharp#3726]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [X] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 4.36 GB / 15.87 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.7.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: ^0.32.1 => 0.32.1
```

### What are the steps to reproduce?

1.  simply converting image from specific jpeg to avif produces an unusable avif image (this is repeatable with the same file)

### What is the expected behaviour?

1.  simply converting image from specific jpeg to avif produces a usable avif image.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```
import sharp from 'sharp';
sharp('input.jpg')
  .avif({effort:0})
  .toFile('output.avif');
```

### Please provide sample image(s) that help explain this problem

[sample zip](https://github.com/lovell/sharp/files/11998252/example.zip)

**Comment by lovell** [comment]
The sample image is 8160x6120, please see #3701

**Comment by Helcostr** [comment]
Thanks @lovell, but I had a follow up question. As mentioned in #3708 about a "65535 limit"... what unit are we talking about? my specific case had an image below 16384x16384 dimensions (max size mentioned in aforementioned issue), so I am not sure of the similarities.

An is this an issue with sharp (and it's dependency libaom as mentioned in #3701?), or my client side?

**Comment by lovell** [comment]
All limits are in pixels. #3701 relates to libaom v3.6.0 writing "level 7" AVIF images that only libaom >= v3.6.0 can read. This only affects "large" dimensions, I'm unsure exactly what the threshold is, best guess is >= ~4096 pixels along one edge.
