### ISSUE TITLE
How to convert PNG to JPG with an output ICC profile without using `flatten`?

### ISSUE THREAD

**Issue by adriaanmeuris** [lovell/sharp#3727]
### What are you trying to achieve?

I'm trying to convert a PNG file to a JPEG file in combination with an output (CMYK) ICC profile.

### When you searched for similar issues, what did you find that might be related?

I've researched all output options and I'm able to do the conversion to a CMYK JPEG without an output ICC profile. If I'm using an ICC output profile, it triggers an error unless I also apply the `flatten` operation.  I'm unable to find any issues related to converting from PNG to JPG using an ICC profile.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question
**1. Working code, generic CMYK applied**
```js
    await sharp('input.png')
      .toColourspace('cmyk')
      .jpeg()
      .toFile('output-cmyk.jpg');
```

**2. Fails with error `Error: icc_transform: unable to load or find any compatible input profile`**
```js
    await sharp('input.png')
      .toColourspace('cmyk')
      .withMetadata({ icc: 'U.S. Web Coated (SWOP) v2.icc' })
      .jpeg()
      .toFile('output-cmyk.jpg');
```

**3. When adding the `flatten` operation it works and the ICC output profile applied correctly**
```js
    await sharp('input.png')
      .flatten({ background: '#fff' })
      .toColourspace('cmyk')
      .withMetadata({ icc: 'U.S. Web Coated (SWOP) v2.icc' })
      .jpeg()
      .toFile('output-cmyk.jpg');
```

I'd expect `2` not to trigger an error, I'm not sure why adding the `flatten` operation prevents this from happening.

**Comment by lovell** [comment]
Does this only occur for 4-channel RGBA PNG images? Does the use of [removeAlpha](https://sharp.pixelplumbing.com/api-channel#removealpha) also help?

There will be a few improvements around CMYK profile handling in a forthcoming libvips 8.15 release that might automagically fix this so let's wait until after that release to see if there's anything else we need to do in sharp.

https://github.com/libvips/libvips/issues/3159

**Comment by adriaanmeuris** [comment]
Thanks for your feedback @lovell, 
- removeAlpha solves the error
- working with 3 channel PNG (no alpha) solves the error as well.

Here are the files I used for testing:
[dices-alpha.png.zip](https://github.com/lovell/sharp/files/12013158/dices-alpha.png.zip)
[dices-noalpha.png.zip](https://github.com/lovell/sharp/files/12013159/dices-noalpha.png.zip)

**Comment by lovell** [comment]
@adriaanmeuris Is there anything else you need relating to this or can we close?

**Comment by adriaanmeuris** [comment]
Thank you @lovell, working as expected now.
