### ISSUE TITLE
Installing to my node server running on elastic beanstalk

### ISSUE THREAD

**Issue by anthonywebb** [lovell/sharp#373]
I've been through several libraries looking for something that I can just deploy to elastic beanstalk and it will "just work", it seems like every library out there fails due to dependencies or some cryptic gyp message that happens as EB does the "npm install"

I really want sharp to work, so I'm willing to spend the time to see if I can get it going.  Here is the error that is in the logs after I try to deploy to elastic beanstalk:

1193 info build /tmp/deployment/application/node_modules/sharp
1194 info preinstall sharp@0.13.1
1195 info linkStuff sharp@0.13.1
1196 silly linkStuff sharp@0.13.1 has /tmp/deployment/application/node_modules as its parent node_modules
1197 verbose linkBins sharp@0.13.1
1198 verbose linkMans sharp@0.13.1
1199 verbose rebuildBundles sharp@0.13.1
1200 verbose rebuildBundles [ '.bin', 'bluebird', 'color', 'nan', 'request', 'semver', 'tar' ]
1201 info install sharp@0.13.1
1202 verbose unsafe-perm in lifecycle false
1203 info sharp@0.13.1 Failed to exec install script
1204 verbose stack Error: sharp@0.13.1 install: `node-gyp rebuild`
1204 verbose stack Exit status 1
1204 verbose stack     at EventEmitter.<anonymous> (/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
1204 verbose stack     at emitTwo (events.js:87:13)
1204 verbose stack     at EventEmitter.emit (events.js:172:7)
1204 verbose stack     at ChildProcess.<anonymous> (/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:24:14)
1204 verbose stack     at emitTwo (events.js:87:13)
1204 verbose stack     at ChildProcess.emit (events.js:172:7)
1204 verbose stack     at maybeClose (internal/child_process.js:818:16)
1204 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
1205 verbose pkgid sharp@0.13.1
1206 verbose cwd /tmp/deployment/application
1207 error Linux 4.1.13-19.30.amzn1.x86_64
1208 error argv "/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/bin/npm" "--production" "rebuild"
1209 error node v4.2.3
1210 error npm  v2.14.7
1211 error code ELIFECYCLE
1212 error sharp@0.13.1 install: `node-gyp rebuild`
1212 error Exit status 1
1213 error Failed at the sharp@0.13.1 install script 'node-gyp rebuild'.
1213 error This is most likely a problem with the sharp package,
1213 error not with npm itself.
1213 error Tell the author that this fails on your system:
1213 error     node-gyp rebuild
1213 error You can get their info via:
1213 error     npm owner ls sharp
1213 error There is likely additional logging output above.
1214 verbose exit [ 1, true ]

> sharp@0.13.1 install /tmp/deployment/application/node_modules/sharp
  > node-gyp rebuild
  
  gyp ERR! clean error 
  gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
  gyp ERR! stack     at Error (native)
  gyp ERR! System Linux 4.1.13-19.30.amzn1.x86_64
  gyp ERR! command "/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
  gyp ERR! cwd /tmp/deployment/application/node_modules/sharp
  gyp ERR! node -v v4.2.3
  gyp ERR! node-gyp -v v3.0.3
  gyp ERR! not ok 
  
  npm ERR! Linux 4.1.13-19.30.amzn1.x86_64
  npm ERR! argv "/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/bin/npm" "--production" "rebuild"
  npm ERR! node v4.2.3
  npm ERR! npm  v2.14.7
  npm ERR! code ELIFECYCLE
  npm ERR! sharp@0.13.1 install: `node-gyp rebuild`
  npm ERR! Exit status 1
  npm ERR! 
  npm ERR! Failed at the sharp@0.13.1 install script 'node-gyp rebuild'.
  npm ERR! This is most likely a problem with the sharp package,
  npm ERR! not with npm itself.
  npm ERR! Tell the author that this fails on your system:
  npm ERR!     node-gyp rebuild
  npm ERR! You can get their info via:
  npm ERR!     npm owner ls sharp
  npm ERR! There is likely additional logging output above.
  
  npm ERR! Please include the following file with any support request:
  npm ERR!     /tmp/deployment/application/npm-debug.log
  Running npm install:  /opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/bin/npm
  Setting npm config jobs to 1
  npm config jobs set to 1
  Running npm with --production flag
  Failed to run npm install. Snapshot logs for more details.

**Comment by lovell** [comment]
Hello, `EACCES: permission denied, rmdir 'build'` suggests this is a permissions thing.

My best guess is the user that owns the files in `/tmp/deployment/application/node_modules` is different to the one running the command `Running npm install: /opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/bin/npm`.

Perhaps this is a root vs ec2-user thing?

**Comment by anthonywebb** [comment]
@lovell thanks for getting back to me.  I have been trying all sorts of things, but nothing concrete yet on how to fix it.  Some good info in these links:
https://github.com/strongloop/fsevents/issues/108
https://forums.aws.amazon.com/thread.jspa?messageID=620673

**Comment by anthonywebb** [comment]
And some info here about customizing your container, installing packages, and running custom command line commands (if I knew what packages and commands would fix my issue! :)

http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customize-containers-cw.html

**Comment by lovell** [comment]
It's been a couple of years since I last used Elastic Beanstalk but the "/tmp/deployment/application should probably be owned (recursively) by ec2-user or nodejs for the duration of the staging" comment sounds like it's on the money.

Perhaps run `npm install` on your application's `package.json` using another machine (EC2?) first and include the resultant `node_modules` directory it generates in the zip file you then deploy to Elastic Beanstalk. This might be enough to prevent `npm install` from trying to update the filesystem at deploy time.

Good luck!

**Comment by anthonywebb** [comment]
So I worked around it by before doing my "eb deploy" delete everything from node_modules so the server is forced to reinstall everything, when I did that everything deploys fine.  Oddly enough I have been using elastic beanstalk for years and never run into this issues.

Thanks again for the help!

**Comment by jschr** [comment]
Came across this issue after a full day of debugging the same error. Your workaround set me in the right direction so thanks for posting. The real issue ended up being because the .ebignore syntax requires a trailing slash for directories. 

.ebignore
```
node_modules/
```

Without the trailing slash, your node_modules folder will be uploaded by eb - including all your dev dependencies! Hopefully this helps someone else.

**Comment by geoyws** [comment]
Phew, @jschr ya saved my life. It's working now for me.

**Comment by Phuhwei** [comment]
Switch to t2.small instead of micro. Mine failed with t1.micro and someone reported the same on t2.micro.

**Comment by Ovid2020** [comment]
@jschr Thanks!! I too went down the debugging rabbit holes for a day, then found your fix here. Relieved it's such an easy one!
