### ISSUE TITLE
Gettting error on sharp defination

### ISSUE THREAD

**Issue by klub-DIpen-Ahir** [lovell/sharp#3734]
export = sharp;
         ~~~~~~~~~~~~~~~
    This module is declared with 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

I added esModuleInterop in tsconfig.json but still it's same
I checked in node.js version v19.9.0, 18.8.0,16.20.1
    
    
![image](https://github.com/lovell/sharp/assets/105340224/91f1142a-4728-4fb7-a1bc-5de6b42c3b38)

**Comment by lovell** [comment]
The advice in the error message to set `esModuleInterop` is correct. Check you've configured it in the right place, and that any tooling using the config has been restarted.

https://stackoverflow.com/questions/62273153/this-module-is-declared-with-using-export-and-can-only-be-used-with-a-defau

If you're still having problems, you'll need to provide a complete example with code and config, perhaps as a standalone repo, that allows someone else to reproduce.

**Comment by klub-DIpen-Ahir** [comment]
[ConvertImage.zip](https://github.com/lovell/sharp/files/12168158/ConvertImage.zip)


Please check code
I am usning NODE -v 19.9.0
unzip file
go to ConvertImage
run cmd - tsc .\index.ts

you will get same error

**Comment by lovell** [comment]
If you pass a file to `tsc` then it ignores `tsconfig.json`.

https://stackoverflow.com/questions/39399057/why-is-the-typescript-compiler-ignoring-tsconfig-json

**Comment by klub-DIpen-Ahir** [comment]
correct , Thanks
