### ISSUE TITLE
Unconditional Download during install breaks shrinkpack

### ISSUE THREAD

**Issue by tim-janik** [lovell/sharp#3737]
Preparing projects for reproducible builds or offline builds with [shrinkpack](https://github.com/JamieMason/shrinkpack) breaks during offline installation if sharp is part of the (nested) dependency list. Installation fails as follows:

```
$ rm -rf ~/.npm/    # purge NPM cache or run in a clean CI environment
$ npm ci --offline
npm ERR! code 1
npm ERR! path /tmp/bar/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.12.2/libvips-8.12.2-linux-x64.tar.br
npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! sharp: Installation error: getaddrinfo EAI_AGAIN github.com
```

The shrinkpack [README.md](https://github.com/JamieMason/shrinkpack#readme) contains further motivational details. Please consider supporting this use case.

**Comment by lovell** [comment]
Did you see https://sharp.pixelplumbing.com/install#custom-prebuilt-binaries for installation from filesystem (e.g. when networking is unavailable)?

**Comment by tim-janik** [comment]
> Did you see https://sharp.pixelplumbing.com/install#custom-prebuilt-binaries for installation from filesystem (e.g. when networking is unavailable)?

Thank you for the pointer, I have read through it.

I am just not sure if that could be integrated in an automatic way with shrinkpack, so that users of any derived package (not knowing about sharp) do not have to special case shrinkpack handling for an arbitrary number of dependencies.
Have you taken a look at e.g. the the [Target Problem](https://github.com/JamieMason/shrinkpack#target-problem) description of shrinkpack and see a remote possibility of making this work with sharp?

**Comment by lovell** [comment]
If you've not already seen it, you'll probably be interested in https://github.com/npm/rfcs/pull/519 , which is a proposal to standardise how npm (and yarn etc. by extension) installs platform-specific binaries, similar to the concept of Python "wheels". Once this is available relatively widely then I plan that sharp will very much take full advantage.

**Comment by lovell** [comment]
Please see also https://github.com/lovell/sharp/issues/3750
