### ISSUE TITLE
More tan 16k resulution

### ISSUE THREAD

**Issue by peterkimga** [lovell/sharp#3738]
### What are you trying to achieve?

Can we have some way of using bigger images than 16k resolution? In any way or even hard code this for one purpose?

**Comment by lovell** [comment]
Are you referring to input or output? Which format? Are you aware of the limits for the formats you're using? Perhaps you could provide some code or images that help explain your question.

**Comment by lovell** [comment]
Please see the `limitInputPixels` constructor option.

https://sharp.pixelplumbing.com/api-constructor

> Do not process input images where the number of pixels (width x height) exceeds this limit. Assumes image dimensions contained in the input metadata can be trusted. An integral Number of pixels, zero or false to remove limit, true to use default limit of 268402689 (0x3FFF x 0x3FFF).

```js
sharp(input, { limitInputPixels: false })...
```

**Comment by peterkimga** [comment]
Hi @lovell 

I found it today and I got rid of that error thanks. But is there a problem that you sorted out with this limit? So can I expect anything to happen with that limit ignored? Cause you added it in for a reason?

Regards
Peter

**Comment by peterkimga** [comment]
So as long as your input its an image then it can be as big as it can be?

Regards
Peter

**Comment by lovell** [comment]
PNG images can be up to 2147483647x2147483647 pixels. libvips is as memory efficient as it can be but ultimately available RAM will be the limit.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
