### ISSUE TITLE
Problem while compressing to avif

### ISSUE THREAD

**Issue by Berserk0001** [lovell/sharp#3741]
There is a problem with image compression to avif..I do not know why it happened..It may happen for other compression also..Please look.

Here is the link.
https://asura.gg/wp-content/uploads/2023/07/10-164.jpg

**Comment by lovell** [comment]
The example image is 800x19580 pixels. HEIF output, and therefore AVIF output, is limited to 16384x16384 pixels.

**Comment by Berserk0001** [comment]
Oh

**Comment by Berserk0001** [comment]
What should i do to decrease the memory to compress images to avif? It takes almost most of my memory while it is not the case for webp. Is there any issue with sharp 0.32.4?

**Comment by lovell** [comment]
Did you see #2597?

**Comment by Berserk0001** [comment]
Got it thanks...
