### ISSUE TITLE
Converting GIF to WebP, when can we use mixed and lossless?

### ISSUE THREAD

**Issue by lctcharly** [lovell/sharp#3742]
Hello team, I hope you are doing well!

## Question about an existing feature
I'm having some doubts regarding when to use mixed and when to use lossless compression for GIF to WebP conversion,
since using one or another helps to reduce the image file size which is our objective, but I still not able to identify what is the criteria used to enable or not lossless, I was thinking when the image contains alpha color but seems it's not.

### What are you trying to achieve?

We are converting a GIF to WEBP that contains 800 frames, when this conversion occurs, the final size is different for some criteria, let me add some examples.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

 Enabling lossless and mixed: true, we are obtaining 1.7MB of size.
```
    const quality = this.getQuality(); // 100
    this.image = sharp(buffer, { animated: true });
    await this
      .image
      .toFormat('webp', {
        quality,
        alphaQuality: quality,
        mixed: true,
        lossless: true
      });

    return await this.image.toBuffer();
```
 ![image](https://github.com/lovell/sharp/assets/32857798/0589775d-3f58-43b9-b770-5137706eb580)

 But disabling lossless and having mixed, we are obtaining 11.5MB of size.
```
    const quality = this.getQuality(); // 100
    this.image = sharp(buffer, { animated: true });
    await this
      .image
      .toFormat('webp', {
        quality,
        alphaQuality: quality,
        mixed: true,
        lossless: false
      });

    return await this.image.toBuffer();
```
![image](https://github.com/lovell/sharp/assets/32857798/a7af8305-8945-417f-a3f5-e2fc482305a0)

It is possible that sharp identifies the best type of compression for a resource, if this is not specified?

### Please provide sample image(s) that help explain this question

Size: 822242KB
This is the image that is passed as a buffer:
![gallery](https://github.com/lovell/sharp/assets/32857798/eaf992c6-73a2-4d30-9221-1b5384f76a15)

**Comment by lovell** [comment]
The underlying libwebp contains the logic to determine lossy vs lossless when using `mixed`. As you can see, it probably doesn't always get it right. It's possible that also passing `lossless` false might prevent libwebp from using lossless frames, but I'd need to check this.

Perhaps try experimenting with the `cwebp` command line tool then ask the libwebp maintainers at https://groups.google.com/a/webmproject.org/g/webp-discuss for a more accurate answer.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
