### ISSUE TITLE
Is there any difference between .heif(av1 codec) and .avif image format?

### ISSUE THREAD

**Issue by Berserk0001** [lovell/sharp#3746]
If I use:

const format = heif ? "heif" : "jpeg";

        let compressionQuality = quality * 0.1;
        quality = Math.ceil(compressionQuality);

	return sharp(input)
		.grayscale(grayscale)
		.toFormat(format, {
			quality: quality,
			effort: 1,
			compression: 'av1',
			chromaSubsampling: '4:4:4'
and

const format = avif ? "avif" : "jpeg";

         let compressionQuality = quality * 0.1;
        quality = Math.ceil(compressionQuality);

	return sharp(input)
		.grayscale(grayscale)
		.toFormat(format, {
			quality: quality,
			effort: 1,
			chromaSubsampling: '4:4:4'

Will it produce the same result?
Is heif with av1 faster than avif?

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
