### ISSUE TITLE
TypeScript: webp options type missing preset

### ISSUE THREAD

**Issue by pilotso11** [lovell/sharp#3747]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [ x ] Running `npm install sharp` completes without error.
- [ x ] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [ x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

  System:
    OS: macOS 13.4.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 38.89 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - /usr/local/bin/node
    npm: 9.3.1 - /usr/local/bin/npm
    pnpm: 8.6.11 - /opt/homebrew/bin/pnpm

### What are the steps to reproduce?

```typescript
sharp(src).webp({preset: 'photo').output(dest)
```
Results in a warning 
```
TS2345: Argument of type '{ quality: number; preset: string; }' is not assignable to parameter of type 'WebpOptions'.   Object literal may only specify known properties, and 'preset' does not exist in type 'WebpOptions'.
```

### What is the expected behaviour?

`preset` should be accepted.  it is missing on the type

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```typescript
sharp(src).webp({preset: 'photo').output(dest)
```

### Please provide sample image(s) that help explain this problem

Any image, this is just a problem with the types.

I will submit a pull request shortly.

**Comment by lovell** [comment]
v0.32.5 now available, thanks for the PR.
