### ISSUE TITLE
Single channel floating point imagery

### ISSUE THREAD

**Issue by blacha** [lovell/sharp#3749]
## Question about an existing feature

When loading a single channel float32 image into sharp and then dumping it back out using .raw() it gets converted into three channels, other than using `extractChannel(0)` is there anyway to stop sharp from making the extra channels?

### What are you trying to achieve?

I realise this may be well outside the scope of libvips, But I have been exploring how vips handle Digitial Elevation Models (DEMS) these are generally 1 channel float32 images (tiffs) where each pixel is the height in meters. Surprisingly vips seems to work with these images fine :D 

### When you searched for similar issues, what did you find that might be related?

I couldn't find anything related to channel expansion on 1 channel imagery

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```typescript
// Create a 1x1 float32 image buffer
const buf = new Float32Array(1);
buf[0] = 3.14;
// load into vips and convert it back to a buffer
const ret = await sharp(buf, { raw: { width: 1, height: 1, channels: 1, depth: 'float' } })
  .raw({ depth: 'float' })
  .toBuffer();

console.log(new Float32Array(ret.buffer)); // [3.14, 3.14, 3.14]
```

### Please provide sample image(s) that help explain this question

N/A any float32 array demonstrates this

**Comment by lovell** [comment]
You should be able to use `.toColourspace('b-w')` to switch from the default sRGB colourspace to single-band.

https://sharp.pixelplumbing.com/api-colour#tocolourspace
https://www.libvips.org/API/current/VipsImage.html#VipsInterpretation

**Comment by blacha** [comment]
Thanks soo much for the quick answer! You are 100% correct, When the raw image is created it is set as `colourspace: 'srgb'` and adding `.toColourspace('b-w')` drops it back down to 1 band output!
