### ISSUE TITLE
Pipeline chain order not respected when rotate is used after resize with fit mode "inside"

### ISSUE THREAD

**Issue by jozsefsallai** [lovell/sharp#3756]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Linux 5.15 Arch Linux
    CPU: (12) x64 AMD Ryzen 5 5600H with Radeon Graphics
    Memory: 13.00 GB / 15.48 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.asdf/installs/nodejs/18.16.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/18.16.0/bin/yarn
    npm: 9.5.1 - ~/.asdf/plugins/nodejs/shims/npm
  npmPackages:
    sharp: ^0.32.4 => 0.32.4
```

### What are the steps to reproduce?

Creating an image manipulation pipeline which first resizes the image to a set width of 400 pixels and then rotates it by 90 degrees. The [example code](https://sharp.pixelplumbing.com/api-operation#rotate) in the documentation works correctly, but in this scenario, the `fit` property of the `resize` pipeline is set to `fill`. However, in my use case, this property needs to be set to `inside`.

### What is the expected behaviour?

`rotate -> resize` should work consistently across both `fill` and `inside` fit modes and output images that have a height of 400 pixels. With the `fit: "inside"` property, the image does not have a height of 400 pixels after rotating it by 90 degrees. Instead, it retains the original image dimensions that were resulted by the resize operation. In other words, the order of the chained operations doesn't matter if the fit property is set to `"inside"`.

I am not entirely sure if this is a bug or intended behavior, however, I would have expected it to work sequentially in all cases. I work with streams so I would prefer to avoid having to create new sharp instances and work around my setup just to get around this.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

Minimal reproduction repo with unit tests to exemplify: https://github.com/jozsefsallai/sharp-resize-rotate-inside-repro

Relevant code:

```js
function runPipeline(inStream, outStream, pipeline) {
  const stream = inStream.pipe(pipeline).pipe(outStream);

  return new Promise((resolve, reject) => {
    stream.on("finish", resolve);
    stream.on("error", reject);
  });
}

async function rotateThenResizeFill(inStream, outStream) {
  // WORKS AS EXPECTED - produces an image that's rotated and has 400px width

  const pipeline = sharp().rotate(90).resize({ width: 400, fit: "fill" });
  return runPipeline(inStream, outStream, pipeline);
}

async function resizeThenRotateFill(inStream, outStream) {
  // WORKS AS EXPECTED - produces an image that's rotated and has 400px height

  const pipeline = sharp().resize({ width: 400, fit: "fill" }).rotate(90);
  return runPipeline(inStream, outStream, pipeline);
}

async function rotateThenResizeInside(inStream, outStream) {
  // WORKS AS EXPECTED - produces an image that's rotated and has 400px width

  const pipeline = sharp().rotate(90).resize({ width: 400, fit: "inside" });
  return runPipeline(inStream, outStream, pipeline);
}

async function resizeThenRotateInside(inStream, outStream) {
  // DOES NOT WORK AS EXPECTED - produces an image that's rotated and has 400px
  // width instead of height, the output is identical to rotateThenResizeInside

  const pipeline = sharp().resize({ width: 400, fit: "inside" }).rotate(90);
  return runPipeline(inStream, outStream, pipeline);
}
```

### Please provide sample image(s) that help explain this problem

- Original image: https://imgur.com/a/lZWBmis
- resize -> rotate, fit mode fill: https://imgur.com/a/A7bfvrp
- rotate -> resize, fit mode fill: https://imgur.com/a/MFSHguI
- resize -> rotate, fit mode inside: https://imgur.com/a/BUvfRy1
- rotate -> resize, fit mode inside: https://imgur.com/a/PAACaXo (shouldn't be the same as the one above)

**Comment by lovell** [comment]
Thanks for reporting, commit https://github.com/lovell/sharp/commit/5c19f6dd9bed9b28c507c08b108e9c02c86f62fb fixes this and adds a test that would previously have failed. This will be included in v0.32.5.

**Comment by kleisauke** [comment]
I've opened PR #3762 to simplify this logic. I think the previous logic still dates back prior commit https://github.com/lovell/sharp/commit/eacb8337fa0b868fcdffefd422acee4816fc428f where auto-orient vs manual orient was not separated.

**Comment by lovell** [comment]
v0.32.5 now available, thanks both.
