### ISSUE TITLE
OverlayWith JPEG input, JPEG output

### ISSUE THREAD

**Issue by rahbari** [lovell/sharp#376]
When OverlatWith is used on a jpeg input and the output is jpeg as well the produced image is weird:

`sharp('test.jpg').overlayWith('overlay.png').jpeg().pipe(res);`

![download](https://cloud.githubusercontent.com/assets/163890/13720062/e9a92450-e814-11e5-904a-27099a0abc75.jpeg)

When **input is png and output is jpeg** or when **input is jpeg and the output is png or webp** the result image is ok. This happens on both Windows and OSX, I haven't tested linux yet. My vips version is 8.2.2 on mac.

**Comment by lovell** [comment]
Hello, the forthcoming v0.14.0 will contain many improvements to the `overlayWith` feature, including support for 16-bit PNGs (which is what this example looks like). Are you able to test with the `needle` branch?

`npm install lovell/sharp#needle`

https://github.com/lovell/sharp/blob/needle/docs/api.md#overlaywithimage-options

**Comment by lovell** [comment]
See #239

**Comment by rahbari** [comment]
Hello lovell, thank you for this great library. 
I used photoshop "save for web" to create the overlay file. I tested 24bit PNG as well as 8bit png. In both case output is corrupted. This happens only when the source file is jpeg and the output is jpeg as well. I will test the needle branch now and update asap!

**Comment by rahbari** [comment]
The needle branch works ok with the same files! thank you so much lovell. when this branch is released?

**Comment by lovell** [comment]
Great, glad to hear v0.14.0 will solve this problem, thanks for confirming. Please subscribe to #239 for release updates.
