### ISSUE TITLE
`toColorspace('p3')` outputs an sRGB image

### ISSUE THREAD

**Issue by mertalev** [lovell/sharp#3760]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
System:
    OS: Linux 5.15 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (16) x64 AMD Ryzen 7 5800X3D 8-Core Processor
    Memory: 7.55 GB / 15.62 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.7 - /usr/local/bin/npm
```

### What are the steps to reproduce?

1. Convert a 16-bit image to a Display P3 JPEG/PNG/TIFF
2. Convert the same 16-bit image to the same format but to sRGB
3. Note that these are bit-exact images

The same appears to be the case when passing any random string to `toColorspace`, but some choices do work, e.g. `b-w`.

Notably, calling `withMetadata({icc: 'p3'})` does work in adding a P3 ICC profile (but doesn't convert the actual image).

### What is the expected behaviour?

The output image should be converted to Display P3. This is supported by libvips, though an error for invalid arguments would be expected as well.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```
const sharp = require('sharp');

sharp('dog.png')
  .toColorspace('p3')
  .toFile('dog_p3.jpeg');

sharp('dog.png')
  .toColorspace('srgb')
  .toFile('dog_srgb.jpeg');
```

### Please provide sample image(s) that help explain this problem

16-bit PNG image (converted from a .CR3 using Imagemagick):

![dog-small](https://github.com/lovell/sharp/assets/101130780/e0dbe600-93ad-4c65-8743-b1bfaf7e8641)

**Comment by lovell** [comment]
Hi, did you see https://sharp.pixelplumbing.com/api-colour#tocolourspace and its link to https://github.com/libvips/libvips/blob/3c0bfdf74ce1dc37a6429bed47fa76f16e2cd70a/libvips/iofuncs/enumtypes.c#L777-L794 ?

P3 is an RGB profile rather than a colourspace, so either RGB or RGB16 would be appropriate.

**Comment by mertalev** [comment]
If I try 'rgb', I get the error: `Uncaught Error: vips_colourspace: no known route from 'rgb16' to 'rgb'`.

**Comment by mertalev** [comment]
I did some testing and it seems calling `pipelineColorspace` is sometimes needed for the final image to have the right colors.

Given this original image in Display P3:

![Italy-P3](https://webkit.org/blog-files/color-gamut/Italy-P3.jpg)

Here are the outputs of the following two commands:

```
await sharp('Italy-P3.jpg')
  .withMetadata({icc: 'p3'})
  .rotate()
  .toFormat('jpeg', {quality: 100, chromaSubsampling: '4:4:4'})
  .toFile('Italy-P3-withMetadataP3.jpeg')
```

![Italy-P3-withMetadataP3](https://github.com/lovell/sharp/assets/101130780/72fa2b28-70ea-4b7c-a884-d7c0ba2dcf7c)

```
await sharp('Italy-P3.jpg')
  .pipelineColorspace('rgb16')
  .withMetadata({icc: 'p3'})
  .rotate()
  .toFormat('jpeg', {quality: 100, chromaSubsampling: '4:4:4'})
  .toFile('Italy-P3-withMetadataP3.jpeg')
```

![Italy-P3-withMetadataP3-pipetocolorspace-rgb16](https://github.com/lovell/sharp/assets/101130780/64d6712c-5170-4654-be0b-69e154f12fd4)

The version without `pipelineColorspace` has somewhat degraded colors compared to the version with it when viewed on a P3 display (but I think they look the same when color managed into sRGB). Since the original is 8-bit, shouldn't `rgb16` be unnecessary here?

**Comment by lovell** [comment]
If you're using wide-gamut input and would like wide-gamut output with a P3 profile then using 16-bit `rgb16` as the pipeline colourspace would be a good choice to avoid any narrowing of colour range.
```js
sharp(input)
  .pipelineColorspace('rgb16')
  .withMetadata({ icc: 'p3' })
  ...
```

**Comment by mertalev** [comment]
@lovell I forgot to mention, but I wasn't ever able to get `toColorspace('rgb')` to work regardless of the source image. While `VIPS_INTERPRETATION_RGB` is a [member ](https://www.libvips.org/API/current/VipsImage.html)of `VipsInterpretation`, it's not mentioned in the [docs](https://www.libvips.org/API/current/libvips-colour.html) describing each option. Not sure if this is a sharp issue or a libvips issue. Possibly related, `toColorspace('scrgb')` always produced a completely black image for me.

**Comment by lovell** [comment]
The colourspace conversions supported by libvips can been seen at https://github.com/libvips/libvips/blob/5fb9f6182ca9d396536f87bbd4ca08a993791c30/libvips/colour/colourspace.c#L221

**Comment by kleisauke** [comment]
AFAIK, one should use `VIPS_INTERPRETATION_sRGB` instead of `VIPS_INTERPRETATION_RGB` after commit https://github.com/libvips/libvips/commit/e48f45187b350344ca90add63b4602f1d1f5a0a0. Perhaps the libvips docs should be clearer about this.

> Possibly related, `toColorspace('scrgb')` always produced a completely black image for me. Should I make a new issue for this or re-open this one?

This is being tracked in issue https://github.com/libvips/libvips/issues/2858.
