### ISSUE TITLE
`withMetadata()` behaves differently than `withMetadata({icc: 'srgb'})`

### ISSUE THREAD

**Issue by mertalev** [lovell/sharp#3761]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
System:
    OS: Linux 5.15 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (16) x64 AMD Ryzen 7 5800X3D 8-Core Processor
    Memory: 7.55 GB / 15.62 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.7 - /usr/local/bin/npm
```

### What are the steps to reproduce?

1. Convert an image using `withMetadata` without any args
2. Convert an image using `withMetadata({icc: 'srgb'})
3. Note that the colors and file sizes are different (passing `{icc: 'srgb'}` produces better colors)
4. Also note that inspecting them with exiftool shows different data

### What is the expected behaviour?

The default behavior explained in the [documentation](https://sharp.pixelplumbing.com/api-output#withmetadata) suggests that these should be equivalent, with `options.icc` defaulting to 'srgb'.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```
const sharp = require('sharp');

await sharp('dog.png')
  .withMetadata()
  .toFile('dog-srgb-noargs.jpeg');

await sharp('dog.png')
  .withMetadata({icc: 'srgb'})
  .toFile('dog-srgb-icc.jpeg');
```

### Please provide sample image(s) that help explain this problem

Original:

![dog-small](https://github.com/lovell/sharp/assets/101130780/03e47a9f-46ba-4326-80c5-2f5528bfa391)

`withMetadata()`:

![dog-small-noicc-srgb](https://github.com/lovell/sharp/assets/101130780/4054a4ec-c0ad-4cb3-aadc-fd51334a204e)

`withMetadata({icc: 'srgb'})`:

![dog-small-icc-srgb](https://github.com/lovell/sharp/assets/101130780/4dddf8d2-1bb5-4f1c-adec-5f8a9e8d4815)

**Comment by lovell** [comment]
Thanks for reporting, not sure exactly when this regressed (the docs are correct), I've fixed this and added a test via commit https://github.com/lovell/sharp/commit/bb7469b2d170831c1e9c23ba945166d0b4a14e23
