### ISSUE TITLE
Get Metadata Only from a remote image

### ISSUE THREAD

**Issue by valeryan** [lovell/sharp#3765]
### What are you trying to achieve?

Is it possible to use Sharp to get only metadata about images? I could not find anything about this concept in your documentation. But, I have an operation where I am storing data about images in a s3 bucket for use in other operations.  I don't actually need to download these images I just need the metadata real quick. I considered using S3s API or something like https://github.com/nodeca/probe-image-size but I prefer to use an active package like yours that is really simple. 

The metadata provides what I need but I would like to save on the bandwidth if I can.

**Comment by lovell** [comment]
Did you see #3656?

**Comment by valeryan** [comment]
No, I will give that a try today, thanks.

**Comment by valeryan** [comment]
Based on the #3656 I think this does what I want and metadata is available. I don't that this is robust enough to handle all images I might encounter but for now this is at least workable for testing. Thanks for the help. 

```
const fetchImageChunk = async (
  url: string,
  start: number,
  end: number
): Promise<Buffer> => {
  try {
    const response = await fetch(url, {
      headers: { Range: `bytes=${start}-${end}` },
    });
    if (response.ok) {
      return Buffer.from(await response.arrayBuffer());
    } else {
      throw new Error(`Failed to fetch image. Status code: ${response.status}`);
    }
  } catch (error) {
    throw new Error(`Error fetching image chunk: ${error}`);
  }
};

const buffer = await fetchImageChunk(url, 0, 1000); // Max size for peeking
const metadata = await sharp(buffer).metadata();
```
