### ISSUE TITLE
Change in colour when using operations on BMP images

### ISSUE THREAD

**Issue by AmeyMore98** [lovell/sharp#3772]
### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: macOS 12.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 76.86 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  npmPackages:
    sharp: 0.32.5 => 0.32.5 
```

### What are the steps to reproduce?

Please run the below code snippet that reads a `bmp` file, performs a `flip` operation using sharp, and saves the output as `bmp` file. The output image changes to red color.

### What is the expected behavior?

The color of the input image should not change. But it keeps changing to red. Even when using other transformations like rotate, resize etc.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```
const sharp = require("sharp");
const bmp = require("@vingle/bmp-js");
const { readFileSync, writeFileSync } = require("fs");

const buffer = readFileSync("./input.bmp");
const bitmap = bmp.decode(buffer, true); // true: decode alpha channel

sharp(bitmap.data, {
    raw: {
        width: bitmap.width,
        height: bitmap.height,
        channels: 4,
    },
})
    .flip()
    .toBuffer({ resolveWithObject: true })
    .then(({ data, info }) => {
        const bitmap = bmp.encode({
            data,
            width: info.width,
            height: info.height,
        });

        writeFileSync("output.bmp", bitmap.data);
    });
```

### Please provide sample image(s) that help explain this problem

[input](https://cdn.pixelbin.io/v2/plain-frost-27ba3e/original/sharp_test/input.bmp)
[output](https://cdn.pixelbin.io/v2/plain-frost-27ba3e/original/sharp_test/output.bmp)

**Comment by AmeyMore98** [comment]
Thanks for your reply.

Setting `toRGBA` as `false` in `bmp.decode` fixes the issue. 
```
const bitmap = bmp.decode(buffer, false);
```

But I'm not sure whether this would work for all images.

**Comment by lovell** [comment]
Perhaps try https://www.npmjs.com/package/sharp-bmp ?

**Comment by lovell** [comment]
@AmeyMore98 Were you able to make any progress with this?

**Comment by AmeyMore98** [comment]
@lovell Yes, I solved this by using (bmj-js)[https://github.com/mooyoul/bmp-js] for encoding the images. Thanks for the help.
Sorry, didn't get a chance to update here.
