### ISSUE TITLE
Resizing an image after other operations doesn't work

### ISSUE THREAD

**Issue by AndreKR** [lovell/sharp#3775]
### What are you trying to achieve?

I want to:
- Create an image of 200 x 100 pixels.
- Render a text into it.
- Scale it up to twice the dimensions (400 x 200). (So that I can see the pixels better.)

Using the code below I get the image shown below. (No idea why the wrong font is used by the way, but that is an issue for another time - it works okay on my Raspberry Pi where this will eventually run.)

As you can see the text does not cover the whole image width.

My guess is that `resize()` is more like a `setSize()` function and is executed out-of-order? This sentence from the docs seems to allude to that:

> Only one resize can occur per pipeline. Previous calls to resize in the same pipeline will be ignored.

If that is the case, then how can I actually resize the image, *after* the composition?

### When you searched for similar issues, what did you find that might be related?

I skimmed all issues with "resize" in the name but found nothing similar.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```javascript
let sharp = require('sharp');

let image = sharp({
    create: {
        width: 200,
        height: 100,
        channels: 4,
        background: { r: 255, g: 255, b: 255, alpha: 1 }
    }
});

image = image.composite([{
  input: {
    text: {
      text: 'Test',
      width: 200,
      height: 100,
      fontfile: 'C:\\Windows\\Fonts\\BAHNSCHRIFT.TTF'
    }
  }
}]);

image
.resize(200 * 2, 100 * 2, { kernel: sharp.kernel.nearest })
.jpeg({
  quality: 100,
  chromaSubsampling: '4:4:4'
})
.toFile('image.jpg');
```

### Please provide sample image(s) that help explain this question

![image](https://github.com/lovell/sharp/assets/1188538/f9a24d38-8a67-409e-a034-37b83fc0c969)

**Comment by lovell** [comment]
Hi, did you see https://sharp.pixelplumbing.com/api-composite#composite ?

> Any resize, rotate or extract operations in the same processing pipeline will always be applied to the input image before composition.

Did you see the _"Generate an image from text"_ example at https://sharp.pixelplumbing.com/api-constructor#sharp ?

You might be able to simplify your sample code to remove the use of `composite`, for example:

```js
sharp({
  text: {
    text: 'Test',
    width: 200,
    height: 100,
    fontfile: 'C:\\Windows\\Fonts\\BAHNSCHRIFT.TTF'
  }
})
  .resize(200 * 2, 100 * 2, { kernel: sharp.kernel.nearest })
  ...
```

**Comment by AndreKR** [comment]
Indeed I didn't see that. I think I'm using sharp wrong. I assumed the various method calls represent steps in a processing pipeline that can be chained indefinitely, but now I think in fact they are setting configuration options (with a fluent API) for basically a single operation.

If I want to chain together multiple steps (to render a chart or a dashboard) I really need to make separate sharp instances for each step and glue them together with buffers containing TIFFs or uncompressed PNGs.

**Comment by AndreKR** [comment]
Question for better understanding the sharp API... are there *any* methods where the order in which they are called makes a difference?

**Comment by lovell** [comment]
The `resize` and `extract` operations are very common and support ordering, which is documented at https://sharp.pixelplumbing.com/api-resize#extract
