### ISSUE TITLE
Compositing another sharp instance

### ISSUE THREAD

**Issue by AndreKR** [lovell/sharp#3776]
### What are you trying to achieve?

Using a sharp instance as an input for a `composite()` operation.

(In my case I need this because the text rendered by the constructor is white-on-black while I need black-on-white, but even if there was an option to change the text color, this is a useful feature on its own.)

### When you searched for similar feature requests, what did you find that might be related?

Searches for "composite sharp object" and the like didn't turn up anything similar.

### What would you expect the API to look like?

```javascript
let image = sharp({
  create: {
    width: 200,
    height: 100,
    channels: 4,
    background: { r: 255, g: 255, b: 255, alpha: 1 }
  }
});

let text = sharp({
  text: {
    text: 'Test',
    width: 200,
    height: 100
  }
})
.negate();

image = image.composite([{
  input: text                                          // <---
}]);

image
.jpeg({
  quality: 100,
  chromaSubsampling: '4:4:4'
})
.toFile('image.jpg');
```

### What alternatives have you considered?

Currently a temporary buffer is necessary:
```javascript
let image = sharp({
  create: {
    width: 200,
    height: 100,
    channels: 4,
    background: { r: 255, g: 255, b: 255, alpha: 1 }
  }
});

let text = sharp({
  text: {
    text: 'Test',
    width: 200,
    height: 100
  }
})
.negate();

let temp = await text.png().toBuffer();                // <---

image = image.composite([{
  input: temp                                          // <---
}]);

image
.jpeg({
  quality: 100,
  chromaSubsampling: '4:4:4'
})
.toFile('image.jpg');
```

From reading other issues I can see that the temporary buffer actually seems like a common approach to "materialize" an image and then continue a different pipeline.

If this is the correct approach, maybe a special "format" could be added that contains width, height, channel depth and raw image data so that at least the PNG encoding would become unnecessary? I remember PNG encoding to be quite expensive performance-wise. Maybe TIFF is cheaper? Can it encode any channel depths that sharp supports?

Or, even better, this sharp->temp->sharp conversion could be wrapped into a function similar to `clone()`, like `materialize()`. This would also help with things like my issue #3775 which could then be written as `sharp().composite().materialize().resize()`.

### Please provide sample image(s) that help explain this feature

n/a

**Comment by lovell** [comment]
> so that at least the PNG encoding would become unnecessary?

Use `.png({ compressionLevel: 0 })` for a fast but more memory intensive intermediate image.

**Comment by AndreKR** [comment]
Alright, I'm now ejecting every intermediate step as a PNG with `compressionLevel: 0` and everything works great. Doesn't even seem to be particularly slow, sharp seem to be really fast in general.

**Comment by kmxz** [comment]
I still find adding such an API can be very helpful. `composite` not accepting another Sharp instance is slightly counterintuitive.

Also, to avoid PNG encoding, I'm using a raw buffer as the intermediate step. Could be faster in some cases.
```
const { data: input, info: raw } = await sharpInstance1.raw().toBuffer({ resolveWithObject: true }); 
sharpInstance2.composite([{ input, raw }]);
```

**Comment by AndreKR** [comment]
@kmxz I was planning to build an image manipulation library with a step-by-step API on top of sharp. Using the buffer is a good idea, I will make sure to do that.
