### ISSUE TITLE
Docs: function parameters

### ISSUE THREAD

**Issue by AndreKR** [lovell/sharp#3777]
The docs builder simplifies the headings here:

https://github.com/lovell/sharp/blob/95635683acf698728f589e9e6e8544b1aa13622e/docs/build.js#L32

I'm assuming this is because you previously used documentation.js and wanted to keep the anchors the same.

The issue with that is that it's not really clear that for example in the following screenshot `[angle]` and `[options]` are the first and the second parameter of `rotate()`:

![image](https://github.com/lovell/sharp/assets/1188538/8e9af003-26d0-46ed-a5f7-34c96f3ce7b7)

Took me a while to understand that I'm not supposed to pass an object with `angle` and `options` keys.

I took a look at how documentation.js deals with this and while it's also not great IMO, the indentation does make it more clear:

![image](https://github.com/lovell/sharp/assets/1188538/3767ddb3-edf6-4205-ac6e-4297576d6131)

Anyway, maybe you could add the full method signature as a code block right below the header? That would be easily doable just by extending the regex replace.

**Comment by lovell** [comment]
Thanks for reporting this, commit https://github.com/lovell/sharp/commit/67e927bdb621e5a7254e2c971670c43ee76fe102 ensures method signatures are included below headings.
