### ISSUE TITLE
Sharp Support for Bun install

### ISSUE THREAD

**Issue by birkskyum** [lovell/sharp#3779]
Due to the use of custom scripts, Bun install is currently not compatible.

The bun runtime is already compatible with sharp:
- #3511

This work in sharp could resolve this:
- #3750

This work in bun could help resolved this:
- https://github.com/oven-sh/bun/pull/4263

**Comment by lovell** [comment]
Please subscribe to https://github.com/lovell/sharp/issues/3750 for updates relating to the removal of the custom install script.
