### ISSUE TITLE
How to remove orientation metadata but keep the rest of the image metadata. 

### ISSUE THREAD

**Issue by alexluongfm** [lovell/sharp#3781]
## Question about an existing feature
How can I remove the orientation data from an image, but retain the rest of the image metadata?

`.rotate()` will strip away the orietnation data by default. `toBuffer()` removes all metadata. Which is why I have `withMetadata()`

However, the metadata contains the previous orientation data, `orientation: 6`, which then causes Mac osx preview to incorrectly rotate the image. This is fixed if I removed `withMetadata()`, however, now I lose my existing image metadata like the image dpi, and colour sync profile. 

```
    let rotatedImage = null;
    const metadata = await sharp(path).metadata();

    console.log('metadata rotation', metadata.orientation);

    if (metadata.format === 'jpeg') {
      rotatedImage = await sharp(path)
        .rotate(rotation)
        .withMetadata()
        .jpeg({
          quality: 100,
        })
        .toBuffer();

```

If I set the metadata orientation to 1 `.withMetadata({ orientation: 1 })`,  although the image preview is correctly rotated, the thumbnails are now incorrectly rotated. Only by removing the orientation values complete will it show correctly. 

Doesn't seem like I can completely override the withMetadata with the existing image metadata either (That's stripped of the orientation)

```

const metadata = await sharp(path).metadata();

      // Doesn't work
      rotatedImage = await sharp(path)
        .rotate(rotation)
        .withMetadata(metadata)
        .jpeg({
          quality: 100,
        })
        .toBuffer();
```

# Versions
`sharp: 0.32.1`
`macosx preview`

**Comment by lovell** [comment]
Hi, if you call `.rotate()` without providing an angle, it will auto-orient based on EXIF metadata and remove that metadata.

I noticed the docs are ambiguous about this behaviour so I've just clarified them via commit https://github.com/lovell/sharp/commit/8be6da1defaa06971d09ef78675285568a7ef063

If you want to provide your own angle to `.rotate(angle)` *and* set your own EXIF Orientation value, you can use `.withMetadata({ orientation: ... })`.

**Comment by lovell** [comment]
> However, the image thumbnails in finder aren't rotated.

This sounds like a bug/feature of Finder, as these image thumbnails are managed by it completely independently.

**Comment by dotrungduchd** [comment]
I call rotate() and it's work

"The use of rotate without an angle will remove the EXIF Orientation tag, if any."
