### ISSUE TITLE
How to make the output to be same on Windows, Linux and MacOS?

### ISSUE THREAD

**Issue by Profesor08** [lovell/sharp#3783]
## Question about an existing feature

After running code, to minimize the images, the resulting files are different on different platforms.

### What are you trying to achieve?

To have identical output on different platforms

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```ts
import fs from "fs";
import sharp from "sharp";

const test = async () => {
  const input = "img/test.jpg";
  const output = "img/output/test.jpg";

  const sharpImage = sharp(input, { animated: true });

  const image = await sharpImage.jpeg({ quality: 80 }).toBuffer();

  fs.writeFileSync(output, image, { flag: "w+" });
};

```

**Comment by lovell** [comment]
Please can you provide sample output JPEG images that differ, including as much information as possible about the machine used to generate each and versions of dependencies, including whether you're using prebuilt binaries vs a globally-installed libvips.

(The compressed DEFLATE output byte stream of a PNG can differ between CPU architectures, but the same input pixel values usually generate the same compressed output byte stream when using JPEG.)

**Comment by Profesor08** [comment]
There are images:

[avatar-example.zip](https://github.com/lovell/sharp/files/12454803/avatar-example.zip)

I have compared them byte by byte, and there are some differences in some places.

Library version is: `^0.31.3`
Node: `v20.3.1`

Binaries are prebuilt from `node_modules` in project directory. I don't use globaly installed modules.

**Comment by Profesor08** [comment]
Checked with latest version, and get different output to.

```javascript
import fs from "fs";
import sharp from "sharp";

const test = async () => {
  const input = `avatar-orig.png`;
  const output = `image-${process.platform}.png`;

  const sharpImage = sharp(input);

  const image = await sharpImage.png({ quality: 80 }).toBuffer({
    resolveWithObject: true,
  });

  console.log(image.info);

  fs.writeFileSync(output, image.data, { flag: `w+` });
};

test();

```

### win32

```js
$ node generate.mjs
{
  format: 'png',
  width: 88,
  height: 88,
  channels: 4,
  premultiplied: false,
  size: 5258
}
```

### linux

```js
$ node generate.mjs
{
  format: 'png',
  width: 88,
  height: 88,
  channels: 4,
  premultiplied: false,
  size: 5054
}
```

### Reproduction

[reproduction.zip](https://github.com/lovell/sharp/files/12457339/reproduction.zip)

**Comment by lovell** [comment]
Thanks, all these examples are PNG and not JPEG. As I said above, the compressed DEFLATE output byte stream of a PNG can differ between CPU architectures. The decompressed pixel values remains the same.

**Comment by lovell** [comment]
The underlying [zlib-ng](https://github.com/zlib-ng/zlib-ng) can also produce slightly different compressed byte streams when built with different compilers. The prebuilt binaries provided by sharp are compiled with either gcc (Linux) or llvm/clang (macOS, Windows).

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
