### ISSUE TITLE
How to install sharp into docker container?

### ISSUE THREAD

**Issue by Shakib448** [lovell/sharp#3784]
Hi there,

I'm submitting my docker container installation issue with Sharp. In my local Mac m1, it's working properly but when I run into the docker image it shows me an error. But my curious mind wants to know from you how I can resolve the issue.

Here is my docker image:
```
FROM node:18

WORKDIR /app

COPY package*.json ./

RUN npm install 

COPY . .

EXPOSE 8000

CMD npm run start:dev
```
Here is the error:

```
klassy_backend_container  | /app/node_modules/sharp/lib/sharp.js:37
klassy_backend_container  |   throw new Error(help.join('\n'));
klassy_backend_container  |         ^
klassy_backend_container  | Error: 
klassy_backend_container  | Something went wrong installing the "sharp" module
klassy_backend_container  | 
klassy_backend_container  | Cannot find module '../build/Release/sharp-linuxmusl-arm64v8.node'
klassy_backend_container  | Require stack:
klassy_backend_container  | - /app/node_modules/sharp/lib/sharp.js
klassy_backend_container  | - /app/node_modules/sharp/lib/constructor.js
klassy_backend_container  | - /app/node_modules/sharp/lib/index.js
klassy_backend_container  | - /app/dist/common/imageUploadProcess/index.js
klassy_backend_container  | - /app/dist/admin_staff_services/products/brand/brand.service.js
klassy_backend_container  | - /app/dist/admin_staff_services/products/brand/brand.module.js
klassy_backend_container  | - /app/dist/app.module.js
klassy_backend_container  | - /app/dist/main.js
klassy_backend_container  | 
klassy_backend_container  | Possible solutions:
klassy_backend_container  | - Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp" # I use it but not working
klassy_backend_container  | - Install for the current linuxmusl-arm64v8 runtime: "npm install --platform=linuxmusl --arch=arm64v8 sharp" # I used it but not working
```

Thanks

**Comment by lovell** [comment]
It looks like you're using a glibc-based Linux (Debian Bookworm) at `npm install` time but a musl-based Linux (Alpine?) at runtime.

https://sharp.pixelplumbing.com/install#cross-platform

**Comment by Shakib448** [comment]
Thanks for the replay.
Currently, I tried with this image.

```
FROM --platform=linux/arm64 node:18-bullseye-slim

WORKDIR /app

COPY package*.json ./

RUN npm install 
RUN npm install --arch=arm64 --platform=linuxmusl sharp

COPY . .

EXPOSE 8000
```

And here is my docker-compose build 
```
  klassy_docker_build:
    image: klassy_image_backend
    build: .
    container_name: klassy_backend_container
    env_file:
      - .env.development
    depends_on:
      - mysql_database
      - redis_cache
    networks:
      - backend
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    command: npm run start:dev
```
But still same issue not installing the sharp into the docker container.

**Comment by lovell** [comment]
The example provided at https://sharp.pixelplumbing.com/install#cross-platform appears to match your runtime scenario (musl-based Linux on ARM64):

```
npm install --arch=arm64 --platform=linux --libc=musl sharp
```

The Docker `COPY . .` command may be overwriting the contents of `node_modules` too.

**Comment by lovell** [comment]
It's unclear to me why a different OS is being used at install time vs runtime. Do you need to support multiple platforms using the same `node_modules` installation tree?

If so, use `npm rebuild ...` for any additional platforms, as documented at https://sharp.pixelplumbing.com/install#cross-platform

If not, a simpler and more stable solution would be to use the same OS at both install time and runtime.

**Comment by Shakib448** [comment]
@lovell Finally I solved the issue. The issue with docker-compose volumes. Thanks for your support and quick response.

**Comment by cyango** [comment]
Can you explain how you solved it? I'm having the same issue and it still gives same error

**Comment by netojose** [comment]
I solved using **node:21-alpine3.18** on docker

**Comment by DonAlexandro** [comment]
I managed to solve the problem by following the next 3 steps:
1. As @netojose suggested, I used **node:21-alpine3.18**
2. Added the next line `RUN npm install --force @img/sharp-linuxmusl-arm64` in the Dockerfile after the `npm install` command:
3. In docker-compose.yml, I've added the next volume `- /server/node_modules` for backend service

**Comment by DonAlexandro** [comment]
Mates, I want to add a few comments to my response here: https://github.com/lovell/sharp/issues/3784#issuecomment-1875958595
1. After you've installed alpine version of the node docker image, you might encounter the next error during the building of the image: `gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.` or something very similiar. Basically, this is the problem with `node-gyp` package.
2. To fix this issue, put `RUN apk --no-cache add g++ make py3-pip` command inside your Dockerfile

**Comment by anshour** [comment]
I managed to solve the issue by using this dockerfile:
```
FROM node:22.3-alpine 

WORKDIR /app

COPY . .

RUN npm install --platform=linuxmusl --arch=x64 --libc=musl

CMD ["npm", "start"]
```

**Comment by sheldon-welinga** [comment]
If anyone is facing this problem in yarn. I solved mine by upgrading the yarn version

```
yarn set version berry && yarn
```

Then in my Dockerfile I enabled corepack
```yaml
FROM node:20-slim

WORKDIR /app

COPY ./package.json .
COPY ./yarn.lock .
COPY ./.yarnrc.yml .
copy /.yarn .

RUN corepack enable # <--- Remember to enable corepack here
RUN yarn

COPY . .

EXPOSE ${PORT}

CMD [ "yarn", "dev" ]
```

Adding `corepack enable` line will allow upgrade yarn version in docker

**Comment by simboonlong** [comment]
TL;DR = Try not to use docker volumes binding.

This got me good for a few days. See this [portion](https://sharp.pixelplumbing.com/install#cross-platform), particularly here:

```
At install time, package managers will automatically select prebuilt binaries for the current OS platform and CPU architecture, where available.
```

The set of deps installed on your local computer will **differ** from the one installed in the docker container, depending of what image is used. Below uses `node:iron-alpine`. Notice the different deps installed when `npm i sharp`:

<img width="639" alt="deps" src="https://github.com/user-attachments/assets/36ad2bd8-9bee-4d13-9f49-17b9fc01a3cc">

With docker volume bind, we unintentionally loaded the local computer deps installed, which resulted in the error.

**Comment by angeldelacruzdev** [comment]
![image](https://github.com/user-attachments/assets/470a0369-6728-4884-b22a-a50b305b9d1f)

**Comment by angeldelacruzdev** [comment]
> I solved using **node:21-alpine3.18** on docker

Critical vulnerabilities were found in this base image: https://github.com/lovell/sharp/issues/3784#issuecomment-2251077102

**Comment by yuriyyakym** [comment]
For those using [Nixpacks](https://nixpacks.com), add `fontconfig` package to your `nixpacks.toml`.

This is my config:
```toml
[phases.setup]
nixPkgs = ["nodejs_22", "pnpm", "fontconfig", "dejavu_fonts", "vips"]
```

**Comment by dvcoolarun** [comment]
I know this issue has been repeated multiple times. During the Docker build, the **sharp package** is either not getting installed or there’s a platform mismatch. I’m not able to figure out what’s causing this. Could someone point me in the right direction?  

```
# Multi-stage build Dockerfile for service

FROM node:22-slim AS node_base

WORKDIR /app
# Set npm to run as root and configure for production
ENV NODE_ENV=production
ENV npm_config_cache=/tmp/.npm

# Install build deps (removed later with multi-stage)
# Install build deps for Debian
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    build-essential \
    && rm -rf /var/lib/apt/lists/*


# Copy package files and build node_modules (with native deps)
COPY package*.json ./
RUN npm ci --only=production && \
    npm install --cpu=x64 --os=linux --libc=glibc sharp && \
    npm install @img/sharp-darwin-arm64 @img/sharp-libvips-darwin-arm64 @img/sharp-libvips-linux-x64 @img/sharp-libvips-linuxmusl-x64 @img/sharp-linux-x64 @img/sharp-linuxmusl-x64 --force && \
    npm cache clean --force

# RUN npm install --cpu=x64 --os=linux --libc=musl sharp

# RUN npm install --force @img/sharp-linuxmusl-arm64

COPY api.js wrapper.js ./

# Final stage
FROM python:3.9-slim

# Install system dependencies first
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    gnupg \
    python3 \
    python3-pip \
    chromium \
    libpango-1.0-0 \
    libharfbuzz0b \
    fonts-liberation \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libatspi2.0-0 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libgbm1 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libx11-xcb1 \
    libxcb-dri3-0 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxrandr2 \
    xdg-utils \
    && rm -rf /var/lib/apt/lists/*

# Then install Node.js
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install -y nodejs

WORKDIR /app
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

# COPY Node.js files from first stage
COPY --from=node_base /app/node_modules ./node_modules
COPY --from=node_base /app/api.js ./api.js
COPY --from=node_base /app/wrapper.js ./wrapper.js
COPY package*.json ./

# Install pipenv 
RUN pip install --no-cache-dir pipenv

# Copy Pipfile and Pipfile.lock
COPY Pipfile Pipfile.lock ./

RUN pip install gevent==23.9.1 --no-build-isolation

RUN pipenv install --deploy --system

# Copy application files
COPY . .

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV CHROME_PATH=/usr/bin/chromium
ENV NODE_ENV=production
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

# Create non-root user
RUN useradd -m appuser && \
    chown -R appuser:appuser /app
USER appuser

# Default command
CMD ["sh", "-c", "uvicorn api:app --host 0.0.0.0 --port ${PORT:-8000}"]
```

**Comment by Michota** [comment]
> I know this issue has been repeated multiple times. During the Docker build, the **sharp package** is either not getting installed or there’s a platform mismatch. I’m not able to figure out what’s causing this. Could someone point me in the right direction?
> 
> ```
> # Multi-stage build Dockerfile for service
> 
> FROM node:22-slim AS node_base
> 
> WORKDIR /app
> # Set npm to run as root and configure for production
> ENV NODE_ENV=production
> ENV npm_config_cache=/tmp/.npm
> 
> # Install build deps (removed later with multi-stage)
> # Install build deps for Debian
> RUN apt-get update && apt-get install -y \
>     python3 \
>     make \
>     g++ \
>     build-essential \
>     && rm -rf /var/lib/apt/lists/*
> 
> 
> # Copy package files and build node_modules (with native deps)
> COPY package*.json ./
> RUN npm ci --only=production && \
>     npm install --cpu=x64 --os=linux --libc=glibc sharp && \
>     npm install @img/sharp-darwin-arm64 @img/sharp-libvips-darwin-arm64 @img/sharp-libvips-linux-x64 @img/sharp-libvips-linuxmusl-x64 @img/sharp-linux-x64 @img/sharp-linuxmusl-x64 --force && \
>     npm cache clean --force
> 
> # RUN npm install --cpu=x64 --os=linux --libc=musl sharp
> 
> # RUN npm install --force @img/sharp-linuxmusl-arm64
> 
> COPY api.js wrapper.js ./
> 
> # Final stage
> FROM python:3.9-slim
> 
> # Install system dependencies first
> RUN apt-get update && apt-get install -y \
>     build-essential \
>     curl \
>     gnupg \
>     python3 \
>     python3-pip \
>     chromium \
>     libpango-1.0-0 \
>     libharfbuzz0b \
>     fonts-liberation \
>     libasound2 \
>     libatk-bridge2.0-0 \
>     libatk1.0-0 \
>     libatspi2.0-0 \
>     libcups2 \
>     libdbus-1-3 \
>     libdrm2 \
>     libgbm1 \
>     libgtk-3-0 \
>     libnspr4 \
>     libnss3 \
>     libx11-xcb1 \
>     libxcb-dri3-0 \
>     libxcomposite1 \
>     libxdamage1 \
>     libxfixes3 \
>     libxrandr2 \
>     xdg-utils \
>     && rm -rf /var/lib/apt/lists/*
> 
> # Then install Node.js
> RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
>     apt-get install -y nodejs
> 
> WORKDIR /app
> ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
> 
> # COPY Node.js files from first stage
> COPY --from=node_base /app/node_modules ./node_modules
> COPY --from=node_base /app/api.js ./api.js
> COPY --from=node_base /app/wrapper.js ./wrapper.js
> COPY package*.json ./
> 
> # Install pipenv 
> RUN pip install --no-cache-dir pipenv
> 
> # Copy Pipfile and Pipfile.lock
> COPY Pipfile Pipfile.lock ./
> 
> RUN pip install gevent==23.9.1 --no-build-isolation
> 
> RUN pipenv install --deploy --system
> 
> # Copy application files
> COPY . .
> 
> # Set environment variables
> ENV PYTHONUNBUFFERED=1
> ENV CHROME_PATH=/usr/bin/chromium
> ENV NODE_ENV=production
> ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
> 
> # Create non-root user
> RUN useradd -m appuser && \
>     chown -R appuser:appuser /app
> USER appuser
> 
> # Default command
> CMD ["sh", "-c", "uvicorn api:app --host 0.0.0.0 --port ${PORT:-8000}"]
> ```

In think I have same issue as yours, but I use nestjs

**Comment by gregg-cbs** [comment]
Seems like using any version of node:slim causes issues because the correct dependencies are not installed.

Also as the docs say, we need to install the package with the correct flags inside of the docker container:
`RUN npm install --cpu=x64 --os=linux --libc=glibc sharp`

Even though I do all of this, when i process any image via sharp my VM runs out of memory and crashes. Im not sure how shrinking a 600kb image causes 100MBs of memory to be used.

**Comment by gregg-cbs** [comment]
If you are simply looking to resize an image, try doing it in the browser to save server resources and ditch the complexity of sharp.

You can see these two options:
https://github.com/nodeca/image-blob-reduce

https://github.com/sabercoy/picsquish

**Comment by lovell** [comment]
For anyone using multi-platform/arch setups, which includes things like `COPY --from=...` in a `Dockerfile`, I highly recommend the use of an alternative package manager such as pnpm v8+ or yarn v3+ that provides the explicit `supportedArchitectures` feature.

https://sharp.pixelplumbing.com/install/#cross-platform

**Comment by dvcoolarun** [comment]
Generally, Sharp failures aren't due to the library itself. My earlier post showed the solution was to ensure the correct node_modules were copied and the architecture was matched. More careful debugging ultimately resolved my issue.
