### ISSUE TITLE
Need a guide how to convert from heic in docker/macos

### ISSUE THREAD

**Issue by loremru** [lovell/sharp#3785]
### What are you trying to achieve?

Convert from .heic to .webp

### When you searched for similar issues, what did you find that might be related?

I already install libheif on macos, but I have an error. And I haven't any idea how to do it with docker

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

sharp(buffer).webp()

### Please provide sample image(s) that help explain this question

a random .heic image

**Comment by lovell** [comment]
> I already install libheif on macos, but I have an error.

If you're using macOS and Homebrew, you can try `brew install vips`, which will install libvips, libheif and x265. You can then (re)install sharp and the globally-installed libvips should then be detected and used.

**Comment by loremru** [comment]
> > I already install libheif on macos, but I have an error.
> 
> If you're using macOS and Homebrew, you can try `brew install vips`, which will install libvips, libheif and x265. You can then (re)install sharp and the globally-installed libvips should then be detected and used.

That actually doesn't work

**Comment by msageryd** [comment]
Did you get this to work?
I have just installed another library for HEIC conversion, because I didn't find anything about HEIC support in sharp.

Incidentally I found out that libvips has support for HEIC. Does this mean that Sharp also has HEIC support, but undocumented?

**Comment by loremru** [comment]
@msageryd 
I installed another library too. But I think problem was in yarn cache. Try to clean package cache. Sharp has heic support, but libvis connection has no docs

**Comment by msageryd** [comment]
Thanks.
I simply missed that because the menu said "heif".

I'll try to install libvips in my Alpine Docker container.

**Comment by lovell** [comment]
@msageryd If a globally-installed libvips is compiled to use pdfium or poppler, and sharp is compiled to use that libvips, then yes, you can render PDF documents as PNG. Watch out for licensing concerns around these e.g. poppler is AGPL.
