### ISSUE TITLE
python pillow vs NPM sharp performance 

### ISSUE THREAD

**Issue by jaman99** [lovell/sharp#3786]
python pillow vs NPM Sharp  performance comparison .which library better for image resizing speed .same size of server on AWS.

**Comment by lovell** [comment]
There are some performance comparisons that include both libvips and Pillow-SIMD at https://github.com/libvips/libvips/wiki/Speed-and-memory-use but you should do your own testing for your specific scenario(s) and formats as there are many factors involved.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by piotrekwitkowski** [comment]
Hi @lovell, thanks for the link! Do I understand it correctly that sharp's performance will be then corresponding with lilbvips' C/C++ perf in that table (plus some rather constant overhead that is related to node)?

**Comment by lovell** [comment]
@piotrekwitkowski Probably, but as mentioned above there are many factors involved so I always recommend anyone does their own testing.
