### ISSUE TITLE
armv7 pre-built binaries

### ISSUE THREAD

**Issue by XChikuX** [lovell/sharp#3788]
## Feature request
Hey folks!

Can we add **armv7** to the [prebuilt binaries](https://github.com/lovell/sharp/releases/tag/v0.32.5) list?

### What are you trying to achieve?

Some of us are running ghost on raspberry pi's since it works quite well.
I'd love support for it on armv7

### When you searched for similar feature requests, what did you find that might be related?

Nothing so far.

**Comment by lovell** [comment]
This probably falls under https://github.com/lovell/sharp/issues/3750, which I've just updated to explicitly mention provision of a prebuilt sharp package (in addition to the existing prebuilt libvips) specifically for 32-bit ARM.

This will be ARMv6 for wider support, ideally even on a first generation Pi B such as https://github.com/lovell/sharp/issues/312#issuecomment-168303258 :smile:

**Comment by lovell** [comment]
Let's track this at #3750

**Comment by XChikuX** [comment]
Sure, but closing this gives the impression the task is completed. 

You may want to implement it and close it after the fact. @lovell

**Comment by lovell** [comment]
OK, given ARMv7 binaries are not planned I've semantically re-closed this issue as "not planned" to avoid possible confusion.

#3750 will provide 32-bit ARMv6 binaries that can be used on ARMv7 devices.
