### ISSUE TITLE
Recommended image type for source image to be thumbnailed.

### ISSUE THREAD

**Issue by goldmerc** [lovell/sharp#3790]
Hello,

Very basic use case. User uploads image. I want to store a full size copy and then serve thumbnailed versions.

The thumbnails will be jpg or webp.

From a performance point of view is there a best format to use for the master image? jpg / webp / something else?

Also, is there any point storing the master image at a higher quality setting than the images that will be served? So, as an example, if I serve images at q:80, is there any benefit to using q:90 or even 100 for the master source image? Or is that just a waste of disk space?

Thanks in advance for any advice.

**Comment by lovell** [comment]
Assuming these are lossy, photographic-like images, I'd probably go for JPEG input of a "quality" at least as high as the highest you'll need for an output, maybe avoid the use of chroma subsampling too. (If the input is already JPEG don't re-process to change the quality as this will introduce another round of loss.)

**Comment by goldmerc** [comment]
Thanks @lovell. Yes, this would be photographic images. The user would be uploading a JPEG. Which would be run through sharp and saved. That would be the source image for future thumbnails. Just so I'm clear - you suggest not to use chroma subsampling when the source image is first saved or when the thumbnails are generated, or both? I was also planning to use the mozjpeg option. Is it best to avoid that on the source image too? Or can I use it for the source and thumbs? Thanks for the advice :-)

**Comment by lovell** [comment]
You'll probably need to experiment as it all depends on the source images.

**Comment by goldmerc** [comment]
Did some experiments and found the results quite surprising (not that I know anything about this stuff!). With the images I'm working with, it seems to make very little difference to the thumbnails if the source image has mozjpeg optimisations + chroma subsampling or not. The resulting thumbnail is either exactly the same size or extremely close and I can't see any difference in the image quality. Checking the speed with simple console.time, it also looks like it's either faster or almost as fast to create a thumbnail from a source jpeg with mozjpeg optimisations. So, for my case, looks like mozjpeg + chroma subsampling is best for source images and thumbnails. Thanks for advising to test it.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
