### ISSUE TITLE
Can I package Shard into my Node.js project by rollup or webpack?

### ISSUE THREAD

**Issue by wangyige0701** [lovell/sharp#3794]
I'm developing a VScode extension and my project needs Shard to complete some features, it runs normally in a development environment with node_modules.

But after I package my project with rollup, it encountered an error in a production environment like this:
```
Something went wrong installing the "sharp" module

The specified module could not be found.
\\?\c:\Users\Administrator\.vscode\extensions\wangyige.wangyige-0.6.7\dist\library\build\Release\sharp-win32-x64.node
```

At the beginning,  I tried to resolve it, but even if I packaged the `sharp-**.node` file for the production environment, it still encountered this error.

After that, I tried many more methods, like packaging sharp separately  into a single file and copying the Json files which were referenced by other sharp dependencies, but none of them worked. Until one time, I used `npm install sharp` in production environment, it worked.

So I want to confirm if Sharp can be packaged into a project or did I ignore some files? If not, which dependencies in node_modules do I need to publish along with my project? (Sharp is too quickly, so I do not want toreplace it with another plugin if possible.)

**Comment by lovell** [comment]
Did you see https://sharp.pixelplumbing.com/install#bundlers ?

For rollup use https://rollupjs.org/configuration-options/#external

**Comment by wangyige0701** [comment]
I have already excluded sharp from the packaged files, my current issue is that I am unsure of which files within node_modules to publish. I have tried including sharp and it's dependencies such as color and detect-libc, but it's not worked.

**Comment by lovell** [comment]
> \\?\c:\Users\Administrator\.vscode\extensions\wangyige.wangyige-0.6.7\dist\library\build\Release\sharp-win32-x64.node

I would expect to see `.../node_modules/sharp/build/Release/...` in this path so you'll need to work out why that's not present.

**Comment by chuongmep** [comment]
Hi @wangyige0701 , how you fix that problem ?

**Comment by wangyige0701** [comment]
> Hi @wangyige0701 , how you fix that problem ?

@chuongmep Sorry I just notice this message today, I don't know if these can still help you. 

I encountered this peoblem because of that sharp whill download a `.node` file and some `.dll` files when installed by npm, the download script is  `npm install` in sharp's package.json, if I package shap in production environment, this script will not execute. 

To address this, I also packaged the files which used to download files, they are: `node_modules/prebuild-install/bin` `node_modules/sharp/install/dll-copy` `node_modules/sharp/install/libvips`. In production environment, I use `child_process.spawnSync` to execute this three files, with the execution order being `use-libvip` then `copy` then `bin`.

There are also a few things to note, the `.node` file will be saved in `../build/Release` and `.dll` files in `../vendor/`, the `.dll` files are copied to Release folder after download. Therefore, you can delete all files in the vendor folder after download. Additionally, you should packaged the script files in a child directory of your project to prevent downloading files outside the root directory.

**Comment by chuongmep** [comment]
@wangyige0701 thanks you, it will help me alot, I removed everything relate but still facing with the issue long time.
