### ISSUE TITLE
 In the k8s pod, my sharpjs service is deployed, but when I execute toWebp toFile on an 8MB png, the pod is restarted.

### ISSUE THREAD

**Issue by FuHongBiao** [lovell/sharp#3797]
## Question about an existing feature
 In the k8s pod, my sharpjs service is deployed, but when I execute toWebp and toFile on an 8MB png, the pod is restarted.
The pod configuration is as follows：
`resources:
  limits:
    cpu: "1"
    memory: 2Gi
  requests:
    cpu: "0.5"
    memory: 2Gi`
How much CPU and memory does the sharpjs service need to allocate? Can the requirements be met under the existing configuration?

### What are you trying to achieve?
No matter what, I don't want my service to crash and restart, even if it's a little slower. 

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

`
const reSharp= sharpObj?.webp?.({ quality: 75});
const fileSize = await sharpObj.toFile(requalityPath); // cause nodejs crash and restart
`

**Comment by lovell** [comment]
It's unclear if your task is I/O bound or CPU bound. My best guess would be the latter, so make sure you've configured the pod with enough CPU *and* that you're not allowing k8s to evict pods when CPU-bound behaviour is detected.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
