### ISSUE TITLE
Is webp output always progressive?

### ISSUE THREAD

**Issue by rayshan** [lovell/sharp#380]
Hello,

Per documentation, there doesn't seem to be a way to generate a progressive webp image. With below chain, I get an output that loads progressively in Chrome 49. Is there a way to generate a non-progressive webp image?

```
            sharp(buffer)
                .resize(maxWidth, maxHeight)
                .webp()
                .interpolateWith(sharp.interpolator.bicubic)
                .max()
                .withoutEnlargement()
                .withMetadata()
                .toBuffer();
```

**Comment by lovell** [comment]
Hello, according to https://developers.google.com/speed/webp/docs/api#advanced_encoding_api the relevant setting here is probably `partitions` for which the "Default is set to 0 for easier progressive decoding."

This suggests a decode-time decision is made by Chrome to render progressively.

Does the [cwebp](https://developers.google.com/speed/webp/docs/cwebp) tool provide a flag or setting that supports what you're looking for?

**Comment by rayshan** [comment]
Thanks @lovell. I don't see any flags for `cwebp` that could help, granted some of the options are beyond my knowledge. I looked around at a few other references:
- https://groups.google.com/a/webmproject.org/forum/#!searchin/webp-discuss/progressive/webp-discuss/vm5kkcaC8G0/u_VDXCgE5IkJ
- `README` of https://github.com/webmproject/libwebp/

All signs point to decoder choosing to decode progressively as well.

My use case is I want to show a placeholder when the webp image is being loaded in a web app. Because of progressive decoding, user can see the placeholder and a slice of webp image at the same time. I'm using `picture` elements so I can't do `new Image()`, set its `src`, then wait for `load` event to insert into DOM (or maybe I just haven't found the way...). There are a few workarounds, such as hiding the image until `load` event fires.

Should we close this ticket?

**Comment by lovell** [comment]
I'm not sure we can do much here given it's a Chrome runtime thing. CSS is probably your friend. Good luck!

For future reference, any useful `cwebp` flags would need to be exposed (if not already) with a libvips' change, then made available in sharp's API.

**Comment by rayshan** [comment]
Thanks for your comments!
