### ISSUE TITLE
My electron app not getting start after installation because of this package.  

### ISSUE THREAD

**Issue by LogicRaysTechnology** [lovell/sharp#3800]
# Issue
## I'm creating a desktop app with electronjs framework. Using "24.3.0" version of electron and my Node version is "18.0.0". sharp package version is "0.32.5".
I've to apply image blur effect and so I've choose sharp package. I'm using below methods of sharp.

const imageBuffer = Buffer.from(base64Data, 'base64');
                sharp(imageBuffer, { format: 'jpeg' })
                  .blur(imgBlurRate)
                  .toBuffer((err, buffer) => {
                    if (err) {
                      console.log('err in blurring the image :: ', err);
                    } else {
                      let blurredBase64 = buffer.toString('base64');
                      blurredBase64 = 'data:image/png;base64,' + blurredBase64;
                      const blurredImg = blurredBase64;
                    }
                  });
                  
### The problem is that whenever I create a build with installing the sharp package and with include above code I didn't get any error and my build is getting created successfully with electron-builder package. I'm creating installable file so it is successfully getting creating without any error. But after Install the build whenever I try to run my app then it is not getting started. even the popup is not coming. Like whenever I click on the app nothing is happening there. Feels like clicking on any empty screen or that kind of thing. But If I try to create a build and run it without the sharp code included then it is working fine.

**Comment by lovell** [comment]
Please can you create a standalone repo with minimal dependencies and code that allows someone else to reproduce.

**Comment by lovell** [comment]
@LogicRaysTechnology Were you able to make any progress with this? If you still require help, please provide the requested information that allows someone else to reproduce.
