### ISSUE TITLE
Where can I edit the functions?

### ISSUE THREAD

**Issue by thezeptar** [lovell/sharp#3802]
## Question about an existing feature
I am trying to attempt making a pull request, changing the `blur()` function a bit, but I don't know where to find it.

### What are you trying to achieve?
Find the `blur()` function and modify it.

### When you searched for similar issues, what did you find that might be related?
I didn't get the wanted results.

**Comment by lovell** [comment]
> I am trying to attempt making a pull request, changing the blur() function a bit

Are you able to explain a little more about the proposed change, if only to help me direct you to the right place.
