### ISSUE TITLE
bitmap to buffer

### ISSUE THREAD

**Issue by garu097** [lovell/sharp#3805]
## Question about an existing feature
how to convert bitmap to back buffer after buffer to bitmap,
toFile() is work, but when i change to toBuff()  sharp occur error when read buffer

`

    const imageSharp = sharp('./image.png')
    const imageSharpBitmap = await imageSharp.raw().toBuffer({ resolveWithObject: true})
    const image = sharp(imageSharpBitmap.data, {
        raw: {
            width: imageSharpBitmap.info.width,
            height: imageSharpBitmap.info.height,
            channels: imageSharpBitmap.info.channels
        }
    });
    const imageBuffer = await image.toBuffer();
    const decodeImage = sharp(imageBuffer)

`

### When you searched for similar issues, what did you find that might be related?
Error: Input buffer contains unsupported image format

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/api-output#tobuffer

> If no explicit format is set, the output format will match the input image

This means `imageBuffer` contains raw pixel data. If you want to encode as PNG then use:

```diff
- const imageBuffer = await image.toBuffer();
+ const imageBuffer = await image.png().toBuffer();
```

**Comment by garu097** [comment]
@lovell thank you
