### ISSUE TITLE
Upscaling a GIF is creating an artefact

### ISSUE THREAD

**Issue by violetviolinist** [lovell/sharp#3806]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

>   System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 96.80 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.8.0/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v18.8.0/bin/npm
  npmPackages:
    sharp: ^0.32.6 => 0.32.6

### What are the steps to reproduce?

Apply a resize with any dimension larger than the original dimensions of the file (518 x 518). In the output image, there is a bar of color at the top that stretches horizontally across the width of the iphones. The colors in this bar change with every frame, and reflect the colors of the iphone that is in the frame.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```
const sharp = require("sharp");

(async () => {
  await sharp("./images/gif_black_line.gif", { animated: true })
  .resize(519, null, {
    fastShrinkOnLoad: false,
  })
  .webp({
    quality: 100,
    lossless: true,
    effort: 6,
  })
  .toFile("./gif_black_line_resized.webp")
})()
```

### Please provide sample image(s) that help explain this problem

Original: https://drive.google.com/file/d/1NG137c6l0N1xedUi5V356h1WVIlRh8xA/view?usp=share_link

Artefact location:
![image](https://github.com/lovell/sharp/assets/19747413/6cb3f19f-9fc3-43f0-a13d-8b7cdeae4791)

**Comment by lovell** [comment]
These are resize artefacts bleeding from one frame to the next. Using nearest neighbour resampling should be more appropriate for this scenario, which you can access via the `resize(... { kernel: 'nearest' })` option.

https://sharp.pixelplumbing.com/api-resize#resize

**Comment by violetviolinist** [comment]
Hi, I tried setting `kernel` to that value, but the output still has the same artefact.

```
const sharp = require("sharp");

(async () => {
  await sharp("./images/gif_black_line.gif", { animated: true })
  .resize(519, null, {
    kernel: "nearest"
  })
  .webp({
    quality: 100,
    lossless: true,
    effort: 6,
  })
  .toFile("./gif_black_line_resized.webp")
})()
```

**Comment by lovell** [comment]
I tried this locally and can reproduce the frame bleed. It's particularly noticeable for the dark phone at one edge on the light background.

If you know you're going to have to deal with animated images like this and will be upscaling then by only a small amount then you could resize the height 1 or 2 pixels above your target dimensions then extract/crop, for example:

```js
  .resize({ width: 519, height: 520 })
  .extract({ top: 1, left: 0, width: 519, height: 519 })
```

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
