### ISSUE TITLE
Electron reports error when running sharp

### ISSUE THREAD

**Issue by dylan-7** [lovell/sharp#3807]
## Possible install-time or require-time problem

- [x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Is this a problem with filesystem permissions?

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7 or later, does the user running `npm install` own the directory it is run in?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

I installed Sharp in Electron and got an error after running it under the windows system, as shown below.
The error is only reported in Windows system, but it is normal on Mac.

<img width="557" alt="Screenshot 2023-09-22 at 5 49 19 PM" src="https://github.com/lovell/sharp/assets/11660473/4dae712f-c7ee-4617-9ea2-71b3816fec15">

this is repo: https://github.com/dylan-7/sharp

electron/main/index.ts
```
import sharp from 'sharp'
ipcMain.handle('compress', async (_, arg) => {
  try {
    const base64 = arg.replace(/^data:image\/[jpeg|jpg]+;base64,/, '')
    const result = await sharp(Buffer.from(base64, 'base64')).jpeg().toBuffer()
    return `data:image/jpeg;base64,${result.toString('base64')}`
  } catch (e: any) {
    console.log(e)
    return e
  }
})
```

thank you for any help

**Comment by lovell** [comment]
Given you're using electron-builder, are you using asar / asarUnpack? Did you see https://github.com/lovell/sharp/issues/678#issuecomment-275956028 ?

**Comment by dylan-7** [comment]
> Given you're using electron-builder, are you using asar / asarUnpack? Did you see [#678 (comment)](https://github.com/lovell/sharp/issues/678#issuecomment-275956028) ?

I configured asar, but still got an error. You can look at the code [https://github.com/dylan-7/sharp/blob/main/electron-builder.json5](https://github.com/dylan-7/sharp/blob/main/electron-builder.json5)
```
  "asar": true,
  asarUnpack: ["**/node_modules/sharp/**/*"],
```

**Comment by WenWingGit** [comment]
I have also encountered this problem. Do you have a solution

**Comment by jeromeatneotek** [comment]
I have the same problem using electron-forge to package a windows.squirrel install.
I am sure it is to do with the way that electron forge decides to package the sharp module.
I have tried both using nm and yarn. The app runs fine in dev using electron-forge start.

I have searched the documentation for some hints on how to setup a basic electron App using Sharp on a windows platform. I have found lots of people with the same issue, but no examples of a solution.
 I am happing to provide a git example if I could get some guidance on what might be required.

Best regards
Jeorme

**Comment by lovell** [comment]
@dylan-7 Were you able to make any progress with this?

**Comment by lovell** [comment]
v0.33.0 is now available and relies entirely on your choice of package manager for installation, so this class of error goes away. There may of course still be problems, but the first place to look if someone does go wrong is the package manager logic.

**Comment by lovell** [comment]
@philkunz Please upgrade npm; you'll need at least v9.6.5.

https://github.com/lovell/sharp/blob/4d049ee8f54f12faf452492217db981ed26d086e/npm/darwin-arm64/package.json#L33

**Comment by philkunz** [comment]
@lovell I'm at 9.6.7
