### ISSUE TITLE
Question about mixing resizing algorithms

### ISSUE THREAD

**Issue by dtoubelis** [lovell/sharp#381]
In my application I need to resize images of different aspect ratios and with different orientations and I found that it makes sense to apply resizing algorithm twice as follows:

```
var image = sharp(filePath)
  .resize(320, 320)
  .min()
  .withoutEnlargement()
  .resize(720, 720)
  .max()
  .withoutEnlargement()
  .withMetadata()
  .jpeg();
```

This seems work but is this the correct way to do it? Will this operation incur double resizing or is sharp smart enough to  calculate final dimensions and do it only once? Do I need to specify `withoutEnlargement()` twice? Is there a better way to do this? Thanks.

**Comment by lovell** [comment]
Hello Dmitri, the second `resize` operation will replace the values of the first, and `max` will replace `min`, so your example is equivalent to:
```javascript
var image = sharp(filePath)
  .resize(720, 720)
  .max()
  .withoutEnlargement()
  .withMetadata()
  .jpeg();
```
Are you able to provide a couple of worked examples to help explain "resize images of different aspect ratios and with different orientations"?

**Comment by dtoubelis** [comment]
Thanks Lovell. Yes, I figured that much myself that it does not do what I want. Here ase few samples of what I'm trying to achieve:

1. source 860x360 -> resize(320, 320).min().withoutEnlargement() -> 764x320 -> resize(720,720).max().withoutEnlargement() -> 720x301

2. source 1280x720 -> resize(320, 320).min().withoutEnlargement() -> 569x320 -> resize(720,720).max().withoutEnlargement() -> 569x320

Essentially I want use case 2 to work and I was hoping that there is an easy way to avoid doing my own calculations on metadata or performing resize twice.

**Comment by lovell** [comment]
Thanks for the example, this looks like fairly specific logic so (if you're not using a Stream-based input) I'd go with the metadata approach as there's minimal performance impact in doing so.

**Comment by lovell** [comment]
Closing this as it's been dormant for a while - feel free to reopen if there are still questions/problems.
