### ISSUE TITLE
Cannot overlay an animated GIF on top of an image

### ISSUE THREAD

**Issue by alexzender** [lovell/sharp#3810]
Hi Sharp team,

I'm facing an issue when combining an animated GIF and an image, would appreciate any help!

### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x ] Running `npm install sharp` completes without error.
- [x ] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x ] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: macOS 13.5.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 480.83 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.19.1 - /opt/homebrew/bin/npm
  npmPackages:
    sharp: ^0.32.6 => 0.32.6
```

### What are the steps to reproduce?

```
 await sharp("background.png")
    .composite([
      { input: "input.gif", tile: true, top: 10, left: 10, animated: true },
    ])
    .toFile("combined.gif");
```

### What is the expected behaviour?

Frames from the animated GIFs are placed on top of the background and then saved as a final GIF.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```
 await sharp("background.png")
    .composite([
      { input: "input.gif", tile: true, top: 10, left: 10, animated: true },
    ])
    .toFile("combined.gif");
```

### Please provide sample image(s) that help explain this problem

Here is the background.png - https://ibb.co/0mdgpj6

And here is the input.gif - https://ibb.co/bd9xWhF

Thank you!

**Comment by lovell** [comment]
Did you see #3796 ?

**Comment by lovell** [comment]
@alexzender Were you able to make any progress with this?

**Comment by lovell** [comment]
I hope the information in https://github.com/lovell/sharp/issues/3796 helped. Please feel free to re-open with more details if further assistance is required.
