### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by tomgreco** [lovell/sharp#3813]
Can you include the changelog in the github releases?

**Comment by lovell** [comment]
To answer your original question, the changelog is at https://sharp.pixelplumbing.com/changelog - there's a link to it in the readme.

I haven't really thought too much about it yet, but the use of GitHub Releases may be superfluous once the work for https://github.com/lovell/sharp/issues/3750 lands. I suspect there'll be a follow-up task to publish packages directly to npm, which allows for things like package provenance/signing. The use of git tags will remain.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
