### ISSUE TITLE
Using .extract() multiple times causes undocumented behavior

### ISSUE THREAD

**Issue by Bengelkopf** [lovell/sharp#3814]
### What are the steps to reproduce?

Using .extract() twice, .trim() probably has the same problem.

### What is the expected behaviour?

I should be able to extract multiple times before and after resize. Otherwise the documentation should be corrected.

Currently, it simply notes the offsets and dimensions for pre-resize the first time .extract() is called and for post-resize the second time.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```
const sharp = require("sharp");
const img = sharp("input.jpg")
img
  .metadata()
  .then((metadata) => {
    const halfWidth = Math.floor(metadata.width / 2);
    const halfHeight = Math.floor(metadata.height / 2);
    img
      .extract({ left: 0, top: 0, width: halfWidth, height: metadata.height }) // Extract half vertically
      .extract({ left: 0, top: 0, width: halfWidth, height: halfHeight }) // Extract half horizontally (in reality, this will be done after resize and cause a bad extract area)
      .resize(halfWidth / 2, halfHeight / 2) // Resize to one eighth the original size
      .toFile("output.jpg");
  });

```

**Comment by lovell** [comment]
Commit https://github.com/lovell/sharp/commit/9161c605e1941cb9e67666eaa729b29caf3b0dac emits a warning for this scenario (via [NODE_DEBUG](https://nodejs.org/dist/latest/docs/api/cli.html#node_debugmodule)=sharp) and adds a clarification to the docs, which will update on the next release.

**Comment by Bengelkopf** [comment]
Thank you. The real-life problem was a lot more complicated.
