### ISSUE TITLE
Converting HEIC to PNG requires global libvips

### ISSUE THREAD

**Issue by blok5025** [lovell/sharp#3816]
## Possible bug
When doing:
`const data = await sharp(input)
  .png()
  .toBuffer();`
On a HEIF type of file,

I get: 
`"heif: Unsupported feature: Unsupported codec (4.3000)]"`
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [ X] Running `npm install sharp` completes without error.
- [ X] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [ X] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

**Comment by blok5025** [comment]
> Is the HEIF file using AV1 (AVIF) or HEVC (HEIC) compression? Did you see https://sharp.pixelplumbing.com/api-output#heif ?
> 
> > Support for patent-encumbered HEIC images using hevc compression requires the use of a globally-installed libvips compiled with support for libheif, libde265 and x265.

Yes I am using HEIC as the input. Do you have any instructions for installing libvips globally and getting the conversion to work?

**Comment by lovell** [comment]
Did you see https://sharp.pixelplumbing.com/install#custom-libvips ?

**Comment by blok5025** [comment]
> Did you see https://sharp.pixelplumbing.com/install#custom-libvips ?

I doubt this can work inside of a Google Cloud Function. I couldn't find any ways of using Meson inside of Google Cloud to install dependencies.

Unless you know any work arounds?

**Comment by lovell** [comment]
Waiting for the HEVC patents to expire (c2036) will probably take less time. Good luck!

**Comment by tomgreco** [comment]
@lovell I'm a bit confused, so what exactly do we do to solve this issue?

**Comment by lovell** [comment]
If you're dealing with patent-encumbered HEVC-compressed HEIC files and use a third-party runtime environment over which you have limited control then sharp is probably the wrong solution to your problem.
