### ISSUE TITLE
Why install sharp with rebuild not use Prebuilt binaries

### ISSUE THREAD

**Issue by nanwangnongfu** [lovell/sharp#3819]
## Possible install-time or require-time problem

- [x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Is this a problem with filesystem permissions?

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

If you are using npm v7 or later, does the user running `npm install` own the directory it is run in?

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

npm verb cli /usr/local/node-v16.20.1-linux-x64/bin/node /usr/bin/npm
npm info using npm@8.19.4
npm info using node@v16.20.1
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 2ms
npm timing config:load:file:/usr/local/node-v16.20.1-linux-x64/lib/node_modules/npm/npmrc Completed in 0ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/opt/tiger/data/.npmrc Completed in 0ms
npm timing config:load:project Completed in 2ms
npm timing config:load:file:/home/tiger/.npmrc Completed in 2ms
npm timing config:load:user Completed in 2ms
npm timing config:load:file:/usr/local/node-v16.20.1-linux-x64/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 1ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 12ms
npm timing npm:load:configload Completed in 13ms
npm timing npm:load:mkdirpcache Completed in 4ms
npm timing npm:load:mkdirplogs Completed in 0ms
npm verb title npm install sharp
npm verb argv "install" "--loglevel" "verbose" "--foreground-scripts" "sharp"
npm timing npm:load:setTitle Completed in 1ms
npm timing config:load:flatten Completed in 2ms
npm timing npm:load:display Completed in 7ms
npm verb logfile logs-max:10 dir:/home/tiger/.npm/_logs
npm verb logfile /home/tiger/.npm/_logs/2023-10-08T04_30_04_760Z-debug-0.log
npm timing npm:load:logFile Completed in 5ms
npm timing npm:load:timers Completed in 0ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load Completed in 30ms
npm timing arborist:ctor Completed in 1ms
npm timing arborist:ctor Completed in 0ms
npm timing idealTree:init Completed in 10ms
npm timing idealTree:userRequests Completed in 2ms
npm http fetch GET 200 https://npm/sharp 63ms (cache revalidated)
npm http fetch GET 200   ##https://npm/detect-libc 38ms (cache revalidated)
npm http fetch GET 200 https://npm/prebuild-install 48ms (cache revalidated)
npm http fetch GET 200 https://npm/color 52ms (cache revalidated)
npm http fetch GET 200 https://npm/tunnel-agent 60ms (cache revalidated)
npm http fetch GET 200 https://npm/node-addon-api 63ms (cache revalidated)
npm http fetch GET 200 https://npm/tar-fs 62ms (cache revalidated)
npm http fetch GET 200 https://npm/simple-get 64ms (cache revalidated)
npm http fetch GET 200 https://npm/semver 65ms (cache revalidated)
npm timing idealTree:#root Completed in 144ms
npm http fetch GET 200 https://npm/color-convert 72ms (cache revalidated)
npm http fetch GET 200 https://npm/mkdirp-classic 70ms (cache revalidated)
npm http fetch GET 200 https://npm/mkdirp-classic 65ms (cache revalidated)
npm http fetch GET 200 https://npm/expand-template 74ms (cache revalidated)
npm http fetch GET 200 https://npm/color-string 75ms (cache revalidated)
npm http fetch GET 200 https://npm/napi-build-utils 74ms (cache revalidated)
npm http fetch GET 200 https://npm/minimist 75ms (cache revalidated)
npm http fetch GET 200 https://npm/github-from-package 76ms (cache revalidated)
npm http fetch GET 200 https://npm/safe-buffer 72ms (cache revalidated)
npm http fetch GET 200 https://npm/decompress-response 80ms (cache revalidated)
npm http fetch GET 200 https://npm/node-abi 86ms (cache revalidated)
npm http fetch GET 200 https://npm/rc 86ms (cache revalidated)
npm http fetch GET 200 https://npm/lru-cache 86ms (cache revalidated)
npm http fetch GET 200 https://npm/simple-concat 90ms (cache revalidated)
npm http fetch GET 200 https://npm/once 91ms (cache revalidated)
npm http fetch GET 200 https://npm/pump 95ms (cache revalidated)
npm http fetch GET 200 https://npm/tar-stream 90ms (cache revalidated)
npm timing idealTree:node_modules/sharp Completed in 118ms
npm http fetch GET 200 https://npm/color-name 26ms (cache revalidated)
npm http fetch GET 200 https://npm/simple-swizzle 28ms (cache revalidated)
npm http fetch GET 200 https://npm/color-name 31ms (cache revalidated)
npm timing idealTree:node_modules/color Completed in 35ms
npm timing idealTree:node_modules/color-convert Completed in 2ms
npm timing idealTree:node_modules/color-name Completed in 0ms
npm http fetch GET 200 https://npm/is-arrayish 20ms (cache revalidated)
npm timing idealTree:node_modules/color-string Completed in 22ms
npm timing idealTree:node_modules/detect-libc Completed in 0ms
npm timing idealTree:node_modules/node-addon-api Completed in 0ms
npm http fetch GET 200 https://npm/deep-extend 31ms (cache revalidated)
npm http fetch GET 200 https://npm/end-of-stream 33ms (cache revalidated)
npm http fetch GET 200 https://npm/chownr 30ms (cache revalidated)
npm http fetch GET 200 https://npm/strip-json-comments 33ms (cache revalidated)
npm http fetch GET 200 https://npm/ini 35ms (cache revalidated)
npm timing idealTree:node_modules/prebuild-install Completed in 53ms
npm timing idealTree:node_modules/expand-template Completed in 0ms
npm timing idealTree:node_modules/github-from-package Completed in 0ms
npm timing idealTree:node_modules/minimist Completed in 0ms
npm timing idealTree:node_modules/mkdirp-classic Completed in 1ms
npm timing idealTree:node_modules/napi-build-utils Completed in 0ms
npm timing idealTree:node_modules/node-abi Completed in 0ms
npm http fetch GET 200 https://npm/wrappy 17ms (cache revalidated)
npm timing idealTree:node_modules/pump Completed in 21ms
npm timing idealTree:node_modules/end-of-stream Completed in 0ms
npm timing idealTree:node_modules/once Completed in 2ms
npm timing idealTree:node_modules/rc Completed in 3ms
npm timing idealTree:node_modules/deep-extend Completed in 0ms
npm timing idealTree:node_modules/ini Completed in 0ms
npm http fetch GET 200 https://npm/yallist 231ms (cache revalidated)
npm timing idealTree:node_modules/semver Completed in 233ms
npm timing idealTree:node_modules/lru-cache Completed in 2ms
npm http fetch GET 200 https://npm/mimic-response 16ms (cache revalidated)
npm timing idealTree:node_modules/simple-get Completed in 20ms
npm timing idealTree:node_modules/decompress-response Completed in 2ms
npm timing idealTree:node_modules/mimic-response Completed in 0ms
npm timing idealTree:node_modules/simple-concat Completed in 0ms
npm timing idealTree:node_modules/simple-swizzle Completed in 1ms
npm timing idealTree:node_modules/is-arrayish Completed in 0ms
npm timing idealTree:node_modules/strip-json-comments Completed in 0ms
npm http fetch GET 200 https://npm/fast-fifo 25ms (cache revalidated)
npm http fetch GET 200 https://npm/b4a 26ms (cache revalidated)
npm http fetch GET 200 https://npm/streamx 27ms (cache revalidated)
npm timing idealTree:node_modules/tar-fs Completed in 33ms
npm http fetch GET 200 https://npm/queue-tick 22ms (cache revalidated)
npm timing idealTree:node_modules/tar-stream Completed in 27ms
npm timing idealTree:node_modules/b4a Completed in 0ms
npm timing idealTree:node_modules/fast-fifo Completed in 0ms
npm timing idealTree:node_modules/streamx Completed in 1ms
npm timing idealTree:node_modules/queue-tick Completed in 0ms
npm timing idealTree:node_modules/tunnel-agent Completed in 1ms
npm timing idealTree:node_modules/safe-buffer Completed in 0ms
npm timing idealTree:node_modules/wrappy Completed in 0ms
npm timing idealTree:node_modules/yallist Completed in 0ms
npm http fetch GET 200 https://npm/inherits 21ms (cache revalidated)
npm http fetch GET 200 https://npm/fs-constants 23ms (cache revalidated)
npm http fetch GET 200 https://npm/bl 25ms (cache revalidated)
npm http fetch GET 200 https://npm/readable-stream 31ms (cache revalidated)
npm timing idealTree:node_modules/prebuild-install/node_modules/tar-fs Completed in 42ms
npm timing idealTree:node_modules/chownr Completed in 0ms
npm http fetch GET 200 https://npm/string_decoder 24ms (cache revalidated)
npm http fetch GET 200 https://npm/util-deprecate 24ms (cache revalidated)
npm http fetch GET 200 https://npm/buffer 30ms (cache revalidated)
npm timing idealTree:node_modules/prebuild-install/node_modules/tar-stream Completed in 38ms
npm http fetch GET 200 https://npm/ieee754 21ms (cache revalidated)
npm http fetch GET 200 https://npm/base64-js 23ms (cache revalidated)
npm timing idealTree:node_modules/bl Completed in 25ms
npm timing idealTree:node_modules/buffer Completed in 3ms
npm timing idealTree:node_modules/base64-js Completed in 0ms
npm timing idealTree:node_modules/fs-constants Completed in 0ms
npm timing idealTree:node_modules/ieee754 Completed in 0ms
npm timing idealTree:node_modules/inherits Completed in 0ms
npm timing idealTree:node_modules/readable-stream Completed in 2ms
npm timing idealTree:node_modules/string_decoder Completed in 0ms
npm timing idealTree:node_modules/util-deprecate Completed in 0ms
npm timing idealTree:buildDeps Completed in 840ms
npm timing idealTree:fixDepFlags Completed in 1ms
npm timing idealTree Completed in 854ms
npm timing reify:loadTrees Completed in 855ms
npm timing reify:diffTrees Completed in 2ms
npm timing reify:retireShallow Completed in 1ms
npm timing reify:createSparse Completed in 11ms
npm timing reify:loadBundles Completed in 0ms
npm timing reifyNode:node_modules/chownr Completed in 126ms
npm timing reifyNode:node_modules/strip-json-comments Completed in 127ms
npm timing reifyNode:node_modules/ini Completed in 127ms
npm timing reifyNode:node_modules/wrappy Completed in 127ms
npm timing reifyNode:node_modules/once Completed in 127ms
npm timing reifyNode:node_modules/end-of-stream Completed in 128ms
npm timing reifyNode:node_modules/mkdirp-classic Completed in 129ms
npm timing reifyNode:node_modules/color-name Completed in 129ms
npm timing reifyNode:node_modules/simple-swizzle Completed in 129ms
npm timing reifyNode:node_modules/color-string Completed in 129ms
npm timing reifyNode:node_modules/inherits Completed in 132ms
npm timing reifyNode:node_modules/fs-constants Completed in 132ms
npm timing reifyNode:node_modules/ieee754 Completed in 133ms
npm timing reifyNode:node_modules/fast-fifo Completed in 133ms
npm timing reifyNode:node_modules/mimic-response Completed in 133ms
npm timing reifyNode:node_modules/lru-cache Completed in 133ms
npm timing reifyNode:node_modules/decompress-response Completed in 134ms
npm timing reifyNode:node_modules/node-abi Completed in 133ms
npm timing reifyNode:node_modules/tar-fs Completed in 134ms
npm timing reifyNode:node_modules/tunnel-agent Completed in 134ms
npm timing reifyNode:node_modules/color Completed in 134ms
npm timing reifyNode:node_modules/util-deprecate Completed in 137ms
npm timing reifyNode:node_modules/string_decoder Completed in 137ms
npm timing reifyNode:node_modules/base64-js Completed in 138ms
npm timing reifyNode:node_modules/yallist Completed in 137ms
npm timing reifyNode:node_modules/expand-template Completed in 137ms
npm timing reifyNode:node_modules/streamx Completed in 139ms
npm timing reifyNode:node_modules/simple-concat Completed in 140ms
npm timing reifyNode:node_modules/deep-extend Completed in 139ms
npm timing reifyNode:node_modules/pump Completed in 139ms
npm timing reifyNode:node_modules/napi-build-utils Completed in 140ms
npm timing reifyNode:node_modules/safe-buffer Completed in 143ms
npm timing reifyNode:node_modules/is-arrayish Completed in 143ms
npm timing reifyNode:node_modules/queue-tick Completed in 144ms
npm timing reifyNode:node_modules/color-convert Completed in 144ms
npm timing reifyNode:node_modules/detect-libc Completed in 144ms
npm timing reifyNode:node_modules/tar-stream Completed in 147ms
npm timing reifyNode:node_modules/prebuild-install/node_modules/tar-stream Completed in 145ms
npm timing reifyNode:node_modules/simple-get Completed in 147ms
npm timing reifyNode:node_modules/buffer Completed in 150ms
npm timing reifyNode:node_modules/b4a Completed in 150ms
npm timing reifyNode:node_modules/github-from-package Completed in 149ms
npm timing reifyNode:node_modules/rc Completed in 150ms
npm timing reifyNode:node_modules/bl Completed in 152ms
npm timing reifyNode:node_modules/prebuild-install Completed in 150ms
npm timing reifyNode:node_modules/minimist Completed in 159ms
npm timing reifyNode:node_modules/readable-stream Completed in 163ms
npm timing reifyNode:node_modules/node-addon-api Completed in 164ms
npm timing reifyNode:node_modules/prebuild-install/node_modules/tar-fs Completed in 165ms
npm timing reifyNode:node_modules/semver Completed in 170ms
npm timing reifyNode:node_modules/sharp Completed in 172ms
npm timing reify:unpack Completed in 175ms
npm timing reify:unretire Completed in 0ms
npm timing build:queue Completed in 2ms
npm timing build:link:node_modules/prebuild-install Completed in 2ms
npm timing build:link:node_modules/rc Completed in 2ms
npm timing build:link:node_modules/semver Completed in 2ms
npm timing build:link Completed in 3ms
npm info run sharp@0.32.6 install node_modules/sharp node-gyp rebuild

> sharp@0.32.6 install
> node-gyp rebuild

gyp info it worked if it ends with oknfo run sharp@0.32.6 install node_modules/sharp node-gyp rebuild
gyp verb cli [
gyp verb cli   '/usr/local/node-v16.20.1-linux-x64/bin/node',
gyp verb cli   '/usr/local/node-v16.20.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild'
gyp verb cli ]
gyp info using node-gyp@9.1.0
gyp info using node@16.20.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - executable path is "/usr/bin/python3"stall node_modules/sharp node-gyp rebuild
gyp verb find Python - executing "/usr/bin/python3" to get version
gyp verb find Python - version is "3.4.2"
gyp verb find Python - version is 3.4.2 - should be >=3.6.0
gyp verb find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - executable path is "/usr/bin/python"nstall node_modules/sharp node-gyp rebuild
gyp verb find Python - executing "/usr/bin/python" to get version
gyp verb find Python - version is "2.7.9"
gyp verb find Python - version is 2.7.9 - should be >=3.6.0
gyp verb find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - executable path is "/usr/bin/python3"
gyp ERR! find Python - version is "3.4.2"
gyp ERR! find Python - version is 3.4.2 - should be >=3.6.0
gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - executable path is "/usr/bin/python"
gyp ERR! find Python - version is "2.7.9"
gyp ERR! find Python - version is 2.7.9 - should be >=3.6.0
gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
gyp ERR! find Python 
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

 System:
    OS: Linux 5.4 Debian GNU/Linux 8 (jessie) 8 (jessie)
    CPU: (96) x64 Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz
    Memory: 280.86 GB / 376.32 GB
    Container: Yes
    Shell: 4.3.30 - /bin/bash
  Binaries:
    Node: 16.20.1 - /usr/bin/node
    npm: 8.19.4 - /usr/bin/npm

**Comment by lovell** [comment]
This looks like the npm lockfile bug - see https://github.com/npm/cli/issues/2606#issuecomment-924307833

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
