### ISSUE TITLE
Setting orientation to 8 causes an exception

### ISSUE THREAD

**Issue by jtobinisaniceguy** [lovell/sharp#382]
Library states that only values 0-7 are allowed.
Values 1-8 are allowed for orientation field

**Comment by lovell** [comment]
The [logic](https://github.com/lovell/sharp/blob/master/index.js#L627-L628) and [docs](https://github.com/lovell/sharp/blob/master/docs/api.md#withmetadatametadata) both use 0-7 rather than 1-8. D'oh.

Great spot on this - I'm amazed no-one has run into this problem before - thanks for reporting.

**Comment by lovell** [comment]
Happy to accept a PR if you're willing and able :)

**Comment by lovell** [comment]
v0.14.0 now available via npm with your patch, thanks again for reporting this!
