### ISSUE TITLE
toFile never resolves after compositing images

### ISSUE THREAD

**Issue by c100k** [lovell/sharp#3820]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

N/A

### What are the steps to reproduce?

- [Composite](https://sharp.pixelplumbing.com/api-composite) different images
- Use `toFile` to save the result to the filesystem

### What is the expected behaviour?

It should save the file on my machine and resolves. But it stops without resolving the promise (see code sample below).

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

**Code**

```js
import sharp from 'sharp';

const height = 1920;
const width = 1080;
const channels = 3;
const format = 'png';
const dest = './file.png';

const layer1 = {
    input: {
        create: {
            background: '#ffffff',
            channels,
            height,
            width,
        },
    },
};
const layer2 = {
    input: {
        create: {
            background: 'red',
            channels,
            gravity: 'bottom',
            height: height * (9 / 10),
            width,
        },
    },
};

console.log('Waiting for a fake promise, just to confirm it is not a top/level async/await issue');

await new Promise((resolve) => {
    setTimeout(() => {
        resolve();
    }, 3000);
});

console.log('Generating...');

// ❌ Never resolves and does not generate any errors
const out = await sharp()
    .composite([layer1, layer2])
    .toFormat(format)
    .toFile(dest);

console.log('Done', { out });
```

**Output**

```sh
➜  sharp-issue node index.mjs
Generating...
```

**Comment by lovell** [comment]
The use of `sharp()` without an input creates a WritableStream for you to pipe input data.

Perhaps you meant something like the following (untested)?

```js
await sharp(layer1)
    .composite([layer2])
    ...
```

**Comment by c100k** [comment]
🤦🏽  Indeed, it solves my issue. Thanks a lot. Sorry for this false positive.
