### ISSUE TITLE
Corrupt JPEG data: premature end of data segment, even with failOn set to 'none'

### ISSUE THREAD

**Issue by lsrbrrd** [lovell/sharp#3825]
I have a issue resizing jpg image, it is a corrupted file but I need to process it too, could you please help me, thanks

the code
const readStreamObject = await s3Client.send(new GetObjectCommand({ Bucket: bucket, Key: key }));
    const objectBuffer = await new Promise((resolve, reject) => {
      const chunks = [];
      readStreamObject.Body.on('data', (chunk) => {
        chunks.push(chunk);
      });
      readStreamObject.Body.on('error', (err) => {
        reject(err);
      });
      readStreamObject.Body.on('end', () => {
        resolve(Buffer.concat(chunks));
      });
    }
    );
 
fixedImageBuffer = await sharp(objectBuffer, { failOn: 'none' })
      .resize({ width: 900, height: 675 })
      .withMetadata()
      .toBuffer();

![corrupted](https://github.com/lovell/sharp/assets/20818246/953e229f-4085-4452-856a-729c3b43db6e)

**Comment by lovell** [comment]
Hi, thanks for reporting, this looks like the problem that https://github.com/libvips/libvips/pull/3293 is trying to solve where the `failOn` setting is ignored for some truncated JPEG images.

**Comment by kleisauke** [comment]
These images can be processed by passing the `unlimited` flag.
```console
$ node -e "require('sharp')('corrupted.jpg', { failOn: 'none', unlimited: true }).resize({ width: 900, height: 675 }).withMetadata().toFile('x.jpg')"
$ vipsheader x.jpg
x.jpg: 900x675 uchar, 3 bands, srgb, jpegload
```

See: https://github.com/libvips/libvips/discussions/3289#discussioncomment-10441905.

**Comment by lovell** [comment]
@kleisauke Thanks Kleis, that makes sense.

@lsrbrrd Hope this helps, I'll close, feel free to reopen if there are still problems.
