### ISSUE TITLE
Transforming input stream into multiple output streams

### ISSUE THREAD

**Issue by hornta** [lovell/sharp#3827]
My input is a stream and I need to output two images from this stream, one which is blurred and one that is watermarked using composite(). I know how to achieve this using only one output since I can just do this.

For one output:
```ts
const passthrough = new PassThrough()
inputStream.pipe(sharp().blur(500)).pipe(passthrough);
passthrough.pipe(...)
```

For two output I want to do something like this but the problem is that the stream is consumed in the first sharp transformation so this doesn't work.
```ts
const passthrough = new PassThrough()
const passthrough2 = new PassThrough()
inputStream.pipe(sharp().blur(500)).pipe(passthrough);
inputStream.pipe(sharp().composite(...)).pipe(passthrough2);
passthrough.pipe(...)
passthrough2.pipe(...)
```

I've tried to do this but for some reason both images are getting blurred. I took this pattern from this issue comment: https://github.com/lovell/sharp/issues/235#issuecomment-113942895

```ts
const downloadStream = downloadResponse.data as Readable;
const transformer = sharp();
downloadStream.pipe(transformer);

const passthrough1 = new PassThrough();
const passthrough2 = new PassThrough();
transformer.jpeg().pipe(passthrough1);
transformer.blur(100).jpeg().pipe(passthrough2);
```

**Comment by lovell** [comment]
Did you see [clone](https://sharp.pixelplumbing.com/api-constructor#clone)?

**Comment by walinsta** [comment]
.....
const pipeline = sharp();
pipeline.clone().resize(.....; //1
pipeline.clone().webp(....; ...n
inputStream.pipe(pipeline);

It will create multiple streams from one inputtStream.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
