### ISSUE TITLE
problem converting svg file that has embedded jpegs

### ISSUE THREAD

**Issue by npomfret** [lovell/sharp#3829]
I'm trying to embed a jpeg in an svg, and convert the whole thing to a jpeg (or png). I've searched and found comments and unit tests that show it's possible, eg:  https://github.com/lovell/sharp/issues/2157#issuecomment-612621988 

If I understand correctly, I need to convert the jpeg to base64 first, and then in the image tag I use:

`xlink:href="data:image/jpeg;base64,...`

But my particular jpeg doesn't render in the converted image. Is there some feature of a jpeg that can break the conversion?  An example svg, that renders fine but doesn't convert to jpeg is here: 

https://gist.github.com/npomfret/953170e791949a2d4015322bcd4f162c

An example jpeg the is failing to render: https://fantasyfootballstats.org/static-image/images/official/EVE.jpeg

**Comment by lovell** [comment]
Hi, these images are PNGs:
```
$ curl -s https://fantasyfootballstats.org/static-image/images/official/EVE.jpeg | file -
/dev/stdin: PNG image data, 110 x 145, 8-bit/color RGBA, non-interlaced
```

**Comment by npomfret** [comment]
Ooops, sorry. Uploaded the wrong file. Thanks!
