### ISSUE TITLE
Why can't I gamma correct an image created from a text object?

### ISSUE THREAD

**Issue by AndreKR** [lovell/sharp#3831]
### What are you trying to achieve?

I'm wondering why gamma correction applied to a text image doesn't work, but it works after the text image has been composited onto a blank image.

### When you searched for similar issues, what did you find that might be related?

Nothing.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```javascript
let image = sharp({ create: {
	width: 100, height: 100, channels: 4, background: { r: 255, g: 255, b: 255, alpha: 1 }
} });

let text = sharp({ text: { text: 'Hello world', font: 'Arial 12', rgba: true, } });

text = sharp(await text.png({compressionLevel: 0}).toBuffer());

// text.gamma(2.2); // <--- uncommenting this has no effect

text = await text.png({compressionLevel: 0}).toBuffer();

image = image.composite([{input: text, left: 10, top: 10}]);

image = sharp(await image.png({compressionLevel: 0}).toBuffer());

// image.gamma(2.2); // <--- uncommenting this does have an effect

image.threshold(128, { grayscale: false });

image.jpeg({ quality: 100, chromaSubsampling: '4:4:4' }).toFile('test.jpg');
```

### Please provide sample image(s) that help explain this question

No `gamma()` calls:

![test](https://github.com/lovell/sharp/assets/1188538/ffb800c0-3c09-429f-a25e-6ae526eb37cd)

First `gamma()` call uncommented:

![test](https://github.com/lovell/sharp/assets/1188538/772d100a-b419-4751-8410-25b56d364422)

Second gamma call uncommented:

![test](https://github.com/lovell/sharp/assets/1188538/65ab8e0b-b11b-4e60-aeee-cdea03409738)

**Comment by lovell** [comment]
In your first example you're not applying any other operations in the same pipeline so gamma correction is essentially a no-op. In the second example you're applying a threshold on the gamma-corrected image, hence the difference.

Perhaps you meant to set a different value for `gammaOut`? https://sharp.pixelplumbing.com/api-operation#gamma

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by AndreKR** [comment]
I think I have a misconception about what `.gamma()` does.

I was assuming it just applies the gamma formula (`out value = in value ^2.something`) to every pixel's color values.

But instead it seems to set some parameter for other operations in the pipeline?
