### ISSUE TITLE
Failed at the sharp@0.32.6 install script

### ISSUE THREAD

**Issue by Yaman-kassas** [lovell/sharp#3833]
i am trying to start strapi on widows and its needs sharp package  , i trying the whole day and i face many errors with that

install" "--verbose" "--foreground-scripts" "sharp"
npm verb node v14.21.3
npm verb npm  v6.14.18
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.32.6 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.32.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 94249ms

npm ERR! A complete log of this run can be found in:

**Comment by patrickkabwe** [comment]
Hi @Yaman-kassas 
I had the same experience as well, but I managed to fix it by upgrading the node version to v18.17.0. 
I hope this works for you too.

**Comment by Yaman-kassas** [comment]
> Hi @Yaman-kassas I had the same experience as well, but I managed to fix it by upgrading the node version to v18.17.0. I hope this works for you too.

i use node v18.17.0 but it gives me this :
npm ERR! code 1
npm ERR! path C:\Users\z1h88\Desktop\web\New folder (2)\dev-blog\node_modules\sharp
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.5/libvips-8.14.5-win32-x64.tar.br
npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! sharp: Installation error: connect ETIMEDOUT 185.199.111.133:443

npm ERR! A complete log of this run can be found in: C:\Users\z1h88\AppData\Local\npm-cache\_logs\2023-10-28T23_43_10_652Z-debug-0.log

**Comment by lovell** [comment]
The salient error here is:

>  npm ERR! sharp: Installation error: connect ETIMEDOUT 185.199.111.133:443

This suggests that there was a (temporary?) networking problem between the installation machine and GitHub.

**Comment by lovell** [comment]
This whole class of possible installation problem will be going away in the forthcoming v0.33.0 - please see https://github.com/lovell/sharp/issues/3750#issuecomment-1751172728 for details of a release candidate.

**Comment by stepbystepcode** [comment]
I succeeded with this command 
```bash
sudo npm i -g cnpm
cnpm i sharp
```
