### ISSUE TITLE
Memory usage is insanely high

### ISSUE THREAD

**Issue by marvin-j97** [lovell/sharp#3834]
## Problem

Process starts at ~24 MB.

```ts
await sharp("in.jpg")
  .resize({
    width: 1920,
    height: 1080,
  })
  .toFormat("jpg", {
    mozjpeg: true,
  })
  .toBuffer();
```

Process is now at ~120 MB. Memory does not decrease (no GC).

Running the above code in a loop, memory shoots up to ~620 MB, and does not decrease either.

## Comparing with imagemagick

With the following code, using imagemagick, the memory stays constant at ~24 MB.
Tested with imagemagick 6.9.11.

```ts
const command = `convert in.jpg -resize 1920x1080^ -gravity center out.jpg`;

for (;;) {
  execSync(command);
}
```

## System

Node 20
Sharp 0.32.6
Ubuntu 22.04 LTS

**Comment by lovell** [comment]
Please ensure you've read and understood everything in https://github.com/lovell/sharp/issues/955 relating to memory allocators on Linux.

In addition, it looks like you're trying to compare many short-lived processes with one long-running process, which is _Äpfel mit Birnen vergleichen_.

**Comment by lovell** [comment]
sharp integrates with libvips via its C++ binding shared library. As you learnt when you read #955, memory management is controlled by the underlying allocator, which is usually the one provided by the OS (e.g. Ubuntu uses glibc).

The `vips` command line tool is intentionally simple, very much unlike the *magick and ffmpeg examples you've provided, and is therefore unsuitable for the more complex image processing pipelines that sharp allows. The approach we recommend to anyone integrating with libvips is to use one of its language bindings for anything other than very simple tasks.
