### ISSUE TITLE
Can we achive Digital Zooming using sharp package ?

### ISSUE THREAD

**Issue by syncthreads-sammith** [lovell/sharp#3835]
### What are you trying to achieve?

I have image of map which is tiff image width and hight is 1024x1024 px and it will over lap on our map application at certain zoom level (e.g.18) the image started to blur here i need to incorporate digital zoom can this possible with sharp npm package 

### When you searched for similar issues, what did you find that might be related?

i have searched for digital zooming i did not find any use full solution and i came across your sharp npm library 

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

i have not implemented any code snippet i have no idea where to start 
**My smiple Procject **
 I have react application where i can see my map which is [react_leaflet ](https://react-leaflet.js.org/)
**below is my client side code**
`import { MapContainer, TileLayer} from "react-leaflet"`
` <MapContainer
        ref={map}
        id="my-map"
        scrollWheelZoom={true}
        center={{ lat: 18.5276, lng: 73.8539 }}
        zoom={15}
        style={{ height: "100vh" }}
      >
        <TileLayer
          attribution='&amp;copy <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          // url={`${process.env.PUBLIC_URL}/pune/{z}/{x}/{y}.png`}
          zoom={17}
          maxZoom={22}
          maxNativeZoom={19}>
        </TileLayer>
        <ImageOverlay
              bounds={bounds}           
              url={`data:image/tiff;base64,${encodeImage(subimageData[0])}`}  **Here the image will over lap on TileLayer this image has to have digital zoomig functionality**
            />
      </MapContainer>`
**In server side i tried sharp package**
`/ sharp(subimage)
         .resize(Math.round(1024 * zoom), Math.round(1024 * zoom))
        .toFile(resizedTif, (err, info) => {
            if (err) {
                 console.error('Error interpolating image:', err);
                res.status(500).send('Error interpolating image');
             } else {
                 res.sendFile(resizedTif);
             }
         });`
but it just cut the image into certain pixel  
### Please provide sample image(s) that help explain this question

![Screenshot (20)](https://github.com/lovell/sharp/assets/111981576/e09f060b-3655-4559-9895-0a7bef4c52d3)

**Any solution in javascrip or react or in nodejs would be appreciate or any hint on how to achive digital zoom for web application Thanks in advance **

**Comment by lovell** [comment]
Does this question relate to deep zoom images? Did you see https://sharp.pixelplumbing.com/api-output#tile ?

**Comment by syncthreads-sammith** [comment]
Yes it dose, i need to deep zoom on image, but not on map tiles the above image your seeing in my earlier question is the tiff image which overlayes on the map container when i zoom on this tiff image location at 19 and above zoom level this image start to pixelate it want to some how keep the overlay image quality good,So user can work or mark a point at 22 or 25 zoom level so can this be achieve using sharp,if you know any alternative way in ReactJS OR NodeJS please let me know .
PC:How can i achieve digitla zooming concept in nodeJs or react Application 
Thanks...

**Comment by lovell** [comment]
It looks like you want to upsample an image so the output has greater dimensions than the input, where the values of unknown intermediate pixels are calculated using the known pixel values nearby. You can use the `kernel` option of resize to control how these values are calculated - see https://sharp.pixelplumbing.com/api-resize#resize

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
