### ISSUE TITLE
sharp libvips npm install error (MacOS 13)

### ISSUE THREAD

**Issue by gxiaosong** [lovell/sharp#3838]
## Possible install-time or require-time problem

- [x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Is this a problem with filesystem permissions?

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?

N/A

If you are using npm v7 or later, does the user running `npm install` own the directory it is run in?

Yes

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?

N/A

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

npm verb cli /Users/wang/.nvm/versions/node/v18.18.2/bin/node /Users/wang/.nvm/versions/node/v18.18.2/bin/npm
npm info using npm@9.8.1
npm info using node@v18.18.2
npm verb title npm install sharp in an empty directory
npm verb argv "install" "--loglevel" "verbose" "--foreground-scripts" "sharp" "in" "an" "empty" "directory"
npm verb logfile logs-max:10 dir:/Users/wang/.npm/_logs/2023-11-03T03_51_45_535Z-
npm verb logfile /Users/wang/.npm/_logs/2023-11-03T03_51_45_535Z-debug-0.log
npm http fetch GET 200 https://registry.npmmirror.com/sharp 163ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/in 353ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/an 338ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/empty 178ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/directory 250ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/color 106ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/prebuild-install 106ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/node-addon-api 108ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/semver 112ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/envify 120ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/tunnel-agent 118ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/detect-libc 121ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/simple-get 120ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/tar-fs 120ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/verror 148ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/multimatch 178ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/recursive-readdir-async 336ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/gextend 360ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/noop-console 530ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/through 70ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/jstransform 134ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/object-assign 65ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/source-map 68ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/base62 125ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/esprima-fb 129ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/commoner 133ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/assert-plus 68ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/extsprintf 67ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/array-union 70ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/core-util-is 68ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/minimatch 117ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/arrify 121ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/array-differ 124ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/@types%2fminimatch 140ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/private 79ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/amdefine 77ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/graceful-fs 81ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/mkdirp 81ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/iconv-lite 82ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/q 82ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/glob 99ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/commander 168ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/detective 194ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/recast 264ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/inherits 48ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/once 48ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/minimist 46ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/defined 80ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/safer-buffer 77ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/path-is-absolute 79ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/esprima 75ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/inflight 81ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/acorn 84ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/ast-types 126ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/wrappy 38ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/brace-expansion 67ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/concat-map 67ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/balanced-match 68ms (cache miss)
npm http fetch GET 200 https://registry.npmmirror.com/expand-template 47ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/pump 45ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/simple-concat 44ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/tar-stream 45ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/lru-cache 49ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/mkdirp-classic 53ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/github-from-package 55ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/decompress-response 52ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/rc 56ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/napi-build-utils 57ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/color-string 60ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/mkdirp-classic 54ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/color-convert 61ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/node-abi 57ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/safe-buffer 104ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/color-name 36ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/simple-swizzle 37ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/color-name 38ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/is-arrayish 37ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/chownr 41ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/ini 43ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/strip-json-comments 43ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/deep-extend 44ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/end-of-stream 46ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/yallist 38ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/mimic-response 42ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/streamx 42ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/fast-fifo 43ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/b4a 44ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/queue-tick 39ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/fs-constants 37ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/bl 39ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/readable-stream 39ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/string_decoder 36ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/buffer 40ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/util-deprecate 59ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/ieee754 39ms (cache hit)
npm http fetch GET 200 https://registry.npmmirror.com/base64-js 39ms (cache hit)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/assert-plus/1.0.0/assert-plus-1.0.0.tgz 280ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/array-union/2.1.0/array-union-2.1.0.tgz 278ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/array-differ/3.0.0/array-differ-3.0.0.tgz 283ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/amdefine/1.0.1/amdefine-1.0.1.tgz 286ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/%40types/minimatch/3.0.5/minimatch-3.0.5.tgz 283ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/path-is-absolute/1.0.1/path-is-absolute-1.0.1.tgz 292ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/extsprintf/1.4.1/extsprintf-1.4.1.tgz 298ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/core-util-is/1.0.2/core-util-is-1.0.2.tgz 300ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/brace-expansion/1.1.11/brace-expansion-1.1.11.tgz 296ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/esprima/3.1.3/esprima-3.1.3.tgz 301ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/defined/1.0.1/defined-1.0.1.tgz 298ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/private/0.1.8/private-0.1.8.tgz 303ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/ast-types/0.9.6/ast-types-0.9.6.tgz 314ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/arrify/2.0.1/arrify-2.0.1.tgz 340ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/mkdirp/0.5.6/mkdirp-0.5.6.tgz 334ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/concat-map/0.0.1/concat-map-0.0.1.tgz 338ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/inflight/1.0.6/inflight-1.0.6.tgz 336ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/balanced-match/1.0.2/balanced-match-1.0.2.tgz 337ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/minimatch/3.1.2/minimatch-3.1.2.tgz 345ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/detective/4.7.1/detective-4.7.1.tgz 349ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/safer-buffer/2.1.2/safer-buffer-2.1.2.tgz 359ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/glob/5.0.15/glob-5.0.15.tgz 359ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/verror/1.10.1/verror-1.10.1.tgz 358ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/q/1.5.1/q-1.5.1.tgz 365ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/graceful-fs/4.2.11/graceful-fs-4.2.11.tgz 366ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/source-map/0.4.4/source-map-0.4.4.tgz 367ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/through/2.3.8/through-2.3.8.tgz 400ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/envify/3.4.1/envify-3.4.1.tgz 406ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/base62/1.2.8/base62-1.2.8.tgz 413ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/multimatch/4.0.0/multimatch-4.0.0.tgz 413ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/object-assign/2.1.1/object-assign-2.1.1.tgz 419ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/commoner/0.10.8/commoner-0.10.8.tgz 419ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/commander/2.20.3/commander-2.20.3.tgz 421ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/iconv-lite/0.4.24/iconv-lite-0.4.24.tgz 429ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/recast/0.11.23/recast-0.11.23.tgz 433ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/esprima-fb/15001.1.0-dev-harmony-fb/esprima-fb-15001.1.0-dev-harmony-fb.tgz 430ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/jstransform/11.0.3/jstransform-11.0.3.tgz 445ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/source-map/0.5.7/source-map-0.5.7.tgz 488ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/acorn/5.7.4/acorn-5.7.4.tgz 505ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/gextend/0.6.0/gextend-0.6.0.tgz 519ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/an/0.0.8/an-0.0.8.tgz 538ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/noop-console/0.8.0/noop-console-0.8.0.tgz 679ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/recursive-readdir-async/1.3.0/recursive-readdir-async-1.3.0.tgz 680ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/empty/0.10.1/empty-0.10.1.tgz 709ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/directory/0.1.0/directory-0.1.0.tgz 708ms (cache miss)
npm http fetch GET 200 https://cdn.npmmirror.com/packages/in/0.19.0/in-0.19.0.tgz 849ms (cache miss)
npm info run sharp@0.32.6 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

> sharp@0.32.6 install
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Detected globally-installed libvips v8.14.532.6 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-ins
sharp: Building from source via node-gyp
gyp info it worked if it ends with ok run sharp@0.32.6 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-ins
gyp verb cli [
gyp verb cli   '/Users/wang/.nvm/versions/node/v18.18.2/bin/node',
gyp verb cli   '/Users/wang/.nvm/versions/node/v18.18.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild'
gyp verb cli ]
gyp info using node-gyp@9.4.0
gyp info using node@18.18.2 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb download using dist-url https://npm.taobao.org/dist
gyp verb find Python Python is not set from command line or npm configurationharp (node install/libvips && node install/dll-copy && prebuild-ins
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - executable path is "/usr/local/opt/python@3.11/bin/python3.11"
gyp verb find Python - executing "/usr/local/opt/python@3.11/bin/python3.11" to get version
gyp verb find Python - version is "3.11.6"sharp@0.32.6 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-ins
gyp info find Python using Python version 3.11.6 found at "/usr/local/opt/python@3.11/bin/python3.11"
gyp verb get node dir no --target version specified, falling back to host node version: 18.18.2
gyp verb command install [ '18.18.2' ]
gyp verb download using dist-url https://npm.taobao.org/distll node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-ins
gyp verb install input version string "18.18.2"
gyp verb install installing version: 18.18.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 11
gyp verb needs "installVersion" 11
gyp verb install version is good
gyp verb get node dir target node version installed: 18.18.2
gyp verb build dir attempting to create "build" dir: /Users/wang/Tmp/strapi-emtoy/node_modules/sharp/build
gyp verb build dir "build" dir needed to be created? Yes
gyp verb python symlink creating symlink to "/usr/local/opt/python@3.11/bin/python3.11" at "/Users/wang/Tmp/strapi-emtoy/node_modules/sharp/build/node_gyp_bins/python3"
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/wang/Tmp/strapi-emtoy/node_modules/sharp/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/wang/Tmp/strapi-emtoy/node_modules/sharp/config.gypi
gyp verb common.gypi checking for gypi file: /Users/wang/Tmp/strapi-emtoy/node_modules/sharp/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/local/opt/python@3.11/bin/python3.11
gyp info spawn args [
gyp info spawn args   '/Users/wang/.nvm/versions/node/v18.18.2/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/wang/Tmp/strapi-emtoy/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/wang/.nvm/versions/node/v18.18.2/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/wang/Library/Caches/node-gyp/18.18.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/wang/Library/Caches/node-gyp/18.18.2',
gyp info spawn args   '-Dnode_gyp_dir=/Users/wang/.nvm/versions/node/v18.18.2/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/wang/Library/Caches/node-gyp/18.18.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/wang/Tmp/strapi-emtoy/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Package xproto was not found in the pkg-config search path.all node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-ins
Perhaps you should add the directory containing `xproto.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xproto', required by 'x11', not found
gyp verb command build []ify:in: info run sharp@0.32.6 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-ins
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/wang/Library/Caches/node-gyp/18.18.2
gyp verb `which` succeeded for `make` /usr/bin/make
gyp verb bin symlinks adding symlinks (such as Python), at "/Users/wang/Tmp/strapi-emtoy/node_modules/sharp/build/node_gyp_bins", to PATH
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  cc -o Release/obj.target/nothing/../node-addon-api/nothing.o ../../node-addon-api/nothing.c '-DNODE_GYP_MODULE_NAME=nothing' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' -I/Users/wang/Library/Caches/node-gyp/18.18.2/include/node -I/Users/wang/Library/Caches/node-gyp/18.18.2/src -I/Users/wang/Library/Caches/node-gyp/18.18.2/deps/openssl/config -I/Users/wang/Library/Caches/node-gyp/18.18.2/deps/openssl/openssl/include -I/Users/wang/Library/Caches/node-gyp/18.18.2/deps/uv/include -I/Users/wang/Library/Caches/node-gyp/18.18.2/deps/zlib -I/Users/wang/Library/Caches/node-gyp/18.18.2/deps/v8/include  -O3 -gdwarf-2 -mmacosx-version-min=10.15 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/nothing/../node-addon-api/nothing.o.d.raw   -c
  rm -f Release/nothing.a && ./gyp-mac-tool filter-libtool libtool  -static -o Release/nothing.a Release/obj.target/nothing/../node-addon-api/nothing.o
warning: /Library/Developer/CommandLineTools/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
  touch Release/obj.target/libvips-cpp.stamparp@0.32.6 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-ins
  c++ -o Release/obj.target/sharp-darwin-x64/src/common.o ../src/common.cc '-DNODE_GYP_MODULE_NAME=sharp-darwin-x64' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNAPI_VERSION=7' '-DNODE_ADDON_API_DISABLE_DEPRECATED' '-DNODE_API_SWALLOW_UNTHROWABLE_EXCEPTIONS' '-DBUILDING_NODE_EXTENSION' -I/Users/wang/Library/Caches/node-gyp/18.18.2/include/node -I/Users/wang/Library/Caches/node-gyp/18.18.2/src -I/Users/wang/Library/Caches/node-gyp/18.18.2/deps/openssl/config -I/Users/wang/Library/Caches/node-gyp/18.18.2/deps/openssl/openssl/include -I/Users/wang/Library/Caches/node-gyp/18.18.2/deps/uv/include -I/Users/wang/Library/Caches/node-gyp/18.18.2/deps/zlib -I/Users/wang/Library/Caches/node-gyp/18.18.2/deps/v8/include -I../../node-addon-api  -O3 -gdwarf-2 -mmacosx-version-min=10.13 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++11 -stdlib=libc++ -fexceptions -Wall -Oz -MMD -MF ./Release/.deps/Release/obj.target/sharp-darwin-x64/src/common.o.d.raw   -c
In file included from ../src/common.cc:13:sharp@0.32.6 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-ins
/usr/local/include/vips/vips8:35:10: fatal error: 'glib-object.h' file not found
#include <glib-object.h>
         ^~~~~~~~~~~~~~~
1 error generated.#) ⠹ reify:in: info run sharp@0.32.6 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-ins
make: *** [Release/obj.target/sharp-darwin-x64/src/common.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/wang/.nvm/versions/node/v18.18.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
gyp ERR! System Darwin 22.5.0
gyp ERR! command "/Users/wang/.nvm/versions/node/v18.18.2/bin/node" "/Users/wang/.nvm/versions/node/v18.18.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/wang/Tmp/strapi-emtoy/node_modules/sharp
gyp ERR! node -v v18.18.2
gyp ERR! node-gyp -v v9.4.0
gyp ERR! not ok
npm info run sharp@0.32.6 install { code: 1, signal: null }
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/Users/wang/.nvm/versions/node/v18.18.2/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
npm verb stack     at ChildProcess.emit (node:events:517:28)
npm verb stack     at maybeClose (node:internal/child_process:1098:16)
npm verb stack     at ChildProcess._handle.onexit (node:internal/child_process:303:5)
npm verb pkgid sharp@0.32.6
npm verb cwd /Users/wang/Tmp/strapi-emtoy
npm verb Darwin 22.5.0
npm verb node v18.18.2
npm verb npm  v9.8.1
npm ERR! code 1
npm ERR! path /Users/wang/Tmp/strapi-emtoy/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm verb exit 1
npm verb unfinished npm timer reify 1698983505678
npm verb unfinished npm timer reify:build 1698983509951
npm verb unfinished npm timer build 1698983509951
npm verb unfinished npm timer build:deps 1698983509951
npm verb unfinished npm timer build:run:install 1698983509958
npm verb unfinished npm timer build:run:install:node_modules/sharp 1698983509958
npm verb code 1

npm ERR! A complete log of this run can be found in: /Users/wang/.npm/_logs/2023-11-03T03_51_45_535Z-debug-0.log

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

  System:
    OS: macOS 13.4
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400F
    Memory: 8.45 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.2/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm

Any help is appreciated, thank you!

**Comment by lovell** [comment]
Hi, the salient part of this log is:

> sharp: Detected globally-installed libvips v8.14.5
> sharp: Building from source via node-gyp
> ...
> Package xproto was not found in the pkg-config search path

It looks like you're using a globally-installed libvips, most likely via homebrew. Please run `brew update && brew upgrade` to fix any Homebrew-related problems first.

**Comment by gxiaosong** [comment]
After running `brew update && brew upgrade && brew uninstall vips`, Sharp has been successfully installed.
Thanks for the fast responses. Appreciate it. All is well now.
