### ISSUE TITLE
Input buffer has corrupt header: pngload_buffer: invalid eXIf chunk

### ISSUE THREAD

**Issue by yanOO1497** [lovell/sharp#3839]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

I'm reading a PNG file but getting the following error:
```
Error: Input buffer has corrupt header: pngload_buffer: too many text chunks
```
The code I'm running:
```ts
const sharp = require('sharp');
const imagePath = 'D://apple.png';
const metaData= await sharp(imagePath).metadata();
```
I'm using the version of sharp : 0.28.3.  the image is exported by blender, you can download here [apple.zip](https://github.com/lovell/sharp/files/13261799/apple.zip)

![Ch09_1001_Glossiness](https://github.com/cocos/3d-tasks/assets/2398658/446b4e2f-9b38-4a7a-997c-05ee16fbf0cc)

**Comment by lovell** [comment]
> I'm using the version of sharp : 0.28.3

Please see https://github.com/lovell/sharp/issues/2917 and upgrade to the latest version.
