### ISSUE TITLE
glib-object.h: No such file or directory on GitHub Actions with ubuntu-latest runner

### ISSUE THREAD

**Issue by skoesi** [lovell/sharp#3841]
## Possible install-time or require-time problem

- [x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### Is this a problem with filesystem permissions?

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?
- Using npm 9.8.1

If you are using npm v7 or later, does the user running `npm install` own the directory it is run in?
- think so

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?
- not using it

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

npm config set registry https://npm-proxy/api/npm/npm-group/
  npm install --unsafe-perm --verbose --foreground-scripts sharp@0.32.6
  shell: /usr/bin/bash -e {0}
  env:
    CODEQL_ACTION_FEATURE_MULTI_LANGUAGE: false
    CODEQL_ACTION_FEATURE_SANDWICH: false
    CODEQL_ACTION_FEATURE_SARIF_COMBINE: true
    CODEQL_ACTION_FEATURE_WILL_UPLOAD: true
    CODEQL_ACTION_VERSION: 2.22.3
    CODEQL_ACTION_WARNED_ABOUT_VERSION: true
    JOB_RUN_UUID: 62c5ffb4-42d1-4532-adbd-bea8a9e9d1bf
    CODEQL_ACTION_ANALYSIS_KEY: .github/workflows/codeql.yml:analyze
    CODEQL_WORKFLOW_STARTED_AT: 2023-11-07T08:00:52.406Z
    CODEQL_RAM: 9113
    CODEQL_THREADS: 16
    npm_config_disturl: https://npm-proxy/nodejs-org-raw-proxy/dist
    npm_config_sharp_libvips_binary_host: https://npm-proxy/github-com-raw-proxy/lovell/sharp-libvips/releases/download
  
npm verb cli /opt/hostedtoolcache/node/18.18.2/x64/bin/node /opt/hostedtoolcache/node/18.18.2/x64/bin/npm
npm info using npm@9.8.1
npm info using node@v18.18.2
npm verb title npm install sharp@0.32.6
npm verb argv "install" "--unsafe-perm" "--loglevel" "verbose" "--foreground-scripts" "sharp@0.32.6"
npm verb logfile logs-max:10 dir:/root/.npm/_logs/2023-11-07T08_04_04_122Z-
npm verb logfile /root/.npm/_logs/2023-11-07T08_04_04_122Z-debug-0.log
npm http fetch GET 200 https://npm-proxy/api/npm/npmjs-org-npm-proxy/sharp 70ms (cache skip)
npm http fetch GET 200 https://npm-proxy/api/npm/npmjs-org-npm-proxy/detect-libc 13ms (cache skip)
npm http fetch GET 200 https://npm-proxy/api/npm/npmjs-org-npm-proxy/tar-fs 24ms (cache skip)
npm http fetch GET 200 https://npm-proxy/api/npm/npmjs-org-npm-proxy/react 83ms (cache skip)
...
... all the fetching stuff ...
...
gyp verb get node dir target node version installed: 18.18.2
gyp verb build dir attempting to create "build" dir: /runner/_work/my-project/my-project/node_modules/sharp/build
gyp verb build dir "build" dir needed to be created? Yes
gyp verb python symlink creating symlink to "/usr/local/bin/python3" at "/runner/_work/my-project/my-project/node_modules/sharp/build/node_gyp_bins/python3"
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /runner/_work/my-project/my-project/node_modules/sharp/build/config.gypi
gyp verb config.gypi checking for gypi file: /runner/_work/my-project/my-project/node_modules/sharp/config.gypi
gyp verb common.gypi checking for gypi file: /runner/_work/my-project/my-project/node_modules/sharp/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/local/bin/python3
gyp info spawn args [
gyp info spawn args   '/opt/hostedtoolcache/node/18.18.2/x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/runner/_work/my-project/my-project/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/hostedtoolcache/node/18.18.2/x64/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/18.18.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/18.18.2',
gyp info spawn args   '-Dnode_gyp_dir=/opt/hostedtoolcache/node/18.18.2/x64/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/18.18.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/runner/_work/my-project/my-project/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /root/.cache/node-gyp/18.18.2
gyp verb `which` succeeded for `make` /usr/bin/make
gyp verb bin symlinks adding symlinks (such as Python), at "/runner/_work/my-project/my-project/node_modules/sharp/build/node_gyp_bins", to PATH
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/runner/_work/my-project/my-project/node_modules/sharp/build'
  touch Release/obj.target/libvips-cpp.stamp
  cc -o Release/obj.target/nothing/node_modules/node-addon-api/nothing.o ../node_modules/node-addon-api/nothing.c '-DNODE_GYP_MODULE_NAME=nothing' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' -I/root/.cache/node-gyp/18.18.2/include/node -I/root/.cache/node-gyp/18.18.2/src -I/root/.cache/node-gyp/18.18.2/deps/openssl/config -I/root/.cache/node-gyp/18.18.2/deps/openssl/openssl/include -I/root/.cache/node-gyp/18.18.2/deps/uv/include -I/root/.cache/node-gyp/18.18.2/deps/zlib -I/root/.cache/node-gyp/18.18.2/deps/v8/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer  -MMD -MF ./Release/.deps/Release/obj.target/nothing/node_modules/node-addon-api/nothing.o.d.raw   -c
rm -f Release/obj.target/node_modules/node-addon-api/nothing.a Release/obj.target/node_modules/node-addon-api/nothing.a.ar-file-list; mkdir -p `dirname Release/obj.target/node_modules/node-addon-api/nothing.a`
ar crs Release/obj.target/node_modules/node-addon-api/nothing.a @Release/obj.target/node_modules/node-addon-api/nothing.a.ar-file-list
  ln -f "Release/obj.target/node_modules/node-addon-api/nothing.a" "Release/nothing.a" 2>/dev/null || (rm -rf "Release/nothing.a" && cp -af "Release/obj.target/node_modules/node-addon-api/nothing.a" "Release/nothing.a")
  g++ -o Release/obj.target/sharp-linux-x64/src/common.o ../src/common.cc '-DNODE_GYP_MODULE_NAME=sharp-linux-x64' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNAPI_VERSION=7' '-DNODE_ADDON_API_DISABLE_DEPRECATED' '-DNODE_API_SWALLOW_UNTHROWABLE_EXCEPTIONS' '-DBUILDING_NODE_EXTENSION' -I/root/.cache/node-gyp/18.18.2/include/node -I/root/.cache/node-gyp/18.18.2/src -I/root/.cache/node-gyp/18.18.2/deps/openssl/config -I/root/.cache/node-gyp/18.18.2/deps/openssl/openssl/include -I/root/.cache/node-gyp/18.18.2/deps/uv/include -I/root/.cache/node-gyp/18.18.2/deps/zlib -I/root/.cache/node-gyp/18.18.2/deps/v8/include -I../node_modules/node-addon-api -I../vendor/8.14.5/linux-x64/include -I../vendor/8.14.5/linux-x64/include/glib-2.0 -I../vendor/8.14.5/linux-x64/lib/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++17 -std=c++0x -fexceptions -Wall -Os -Wno-cast-function-type -MMD -MF ./Release/.deps/Release/obj.target/sharp-linux-x64/src/common.o.d.raw   -c
In file included from ../src/common.cc:13:
/usr/include/vips/vips8:35:10: fatal error: glib-object.h: No such file or directory
   35 | #include <glib-object.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [sharp-linux-x64.target.mk:143: Release/obj.target/sharp-linux-x64/src/common.o] Error 1
make: Leaving directory '/runner/_work/my-project/my-project/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/hostedtoolcache/node/18.18.2/x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
gyp ERR! System Linux 5.10.197
gyp ERR! command "/opt/hostedtoolcache/node/18.18.2/x64/bin/node" "/opt/hostedtoolcache/node/18.18.2/x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /runner/_work/my-project/my-project/node_modules/sharp
gyp ERR! node -v v18.18.2
gyp ERR! node-gyp -v v9.4.0
gyp ERR! not ok 
npm info run sharp@0.32.6 install { code: 1, signal: null }
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/opt/hostedtoolcache/node/18.18.2/x64/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
npm verb stack     at ChildProcess.emit (node:events:517:28)
npm verb stack     at maybeClose (node:internal/child_process:1098:16)
npm verb stack     at ChildProcess._handle.onexit (node:internal/child_process:303:5)
npm verb pkgid sharp@0.32.6
npm verb cwd /runner/_work/my-project/my-project
npm verb Linux 5.10.197
npm verb node v18.18.2
npm verb npm  v9.8.1
npm ERR! code 1
npm ERR! path /runner/_work/my-project/my-project/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm verb exit 1
npm verb unfinished npm timer reify 1699344244427
npm verb unfinished npm timer reify:build 1699344286823
npm verb unfinished npm timer build 1699344286826
npm verb unfinished npm timer build:deps 1699344286827
npm verb unfinished npm timer build:run:install 1699344286928
npm verb unfinished npm timer build:run:install:node_modules/sharp 1699344287928
npm verb code 1

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-11-07T08_04_04_122Z-debug-0.log
Error: Process completed with exit code 1.

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

OS: Linux 5.10 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
CPU: (16) x64 AMD EPYC 7571
Memory: 121.57 GB / 124.66 GB
Container: Yes
Shell: 5.1.16 - /bin/bash
Binaries:
Node: 18.18.2 - /opt/hostedtoolcache/node/18.18.2/x64/bin/node
Yarn: 1.22.19 - /usr/bin/yarn
npm: 9.8.1 - /opt/hostedtoolcache/node/18.18.2/x64/bin/npm

**Comment by lovell** [comment]
>  ... all the fetching stuff ...

Please can you provide this bit of the log too, as that's where the salient messaging lies.

**Comment by skoesi** [comment]
[all-the-fetching-stuff-log.txt](https://github.com/lovell/sharp/files/13278009/all-the-fetching-stuff-log.txt)

What we basically want to do is to use  gatsby-source-storyblok

**Comment by lovell** [comment]
> sharp: Downloading https://npm-proxy/github-com-raw-proxy/lovell/sharp-libvips/releases/download/v8.14.5/libvips-8.14.5-linux-x64.tar.br
sharp: Integrity check passed for linux-x64
prebuild-install info begin Prebuild-install version 7.1.1
prebuild-install info looking for local prebuild @ prebuilds/sharp-v0.32.6-napi-v7-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/a89f17-sharp-v0.32.6-napi-v7-linux-x64.tar.gz
prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.32.6/sharp-v0.32.6-napi-v7-linux-x64.tar.gz
prebuild-install warn install write EPROTO C0772DC5D77F0000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled

It looks like you're intentionally blocking requests to github.com so prebuild-install cannot access prebuilt sharp binaries.

https://sharp.pixelplumbing.com/install#custom-prebuilt-binaries
https://github.com/prebuild/prebuild-install#custom-binaries

**Comment by skoesi** [comment]
You saved my day! THX.
I forgot to set npm_config_sharp_binary_host to our proxy

**Comment by lovell** [comment]
This problem will soon be going away entirely with #3750
