### ISSUE TITLE
feature request support BMP format as pointed in above #3509 (comment)

### ISSUE THREAD

**Issue by tx0c** [lovell/sharp#3843]
### What are you trying to achieve?

but it's same BMP format as pointed in above https://github.com/lovell/sharp/issues/3509#issuecomment-1368198557

so can I file a feature request for Windows BMP files?   if the browser can show it no problem, why cannot sharp process it?

_Originally posted by @tx0c in https://github.com/lovell/sharp/issues/3509#issuecomment-1796419637_

const res = await fetch(`https://raw.githubusercontent.com/Jeff-Tian/gatsby-js/26158879194071fb652efb0f9659edd6ab553d70/packages/gatsby-plugin-sharp/src/__tests__/images/metadata-error.png`);
const image = sharp(await res.arrayBuffer(), { animated: false, failOn: "none" });
const metadata = await image.metadata();

// then outer try catch got ERROR: [Error: Input buffer contains unsupported image format]
and it seems also PC bitmap format:

$ wget 'https://raw.githubusercontent.com/Jeff-Tian/gatsby-js/26158879194071fb652efb0f9659edd6ab553d70/packages/gatsby-plugin-sharp/src/__tests__/images/metadata-error.png'
$ file ./tmp/c16b9dbe-9d9f-4893-9b8b-f22f2656b479.png
./tmp/c16b9dbe-9d9f-4893-9b8b-f22f2656b479.png: PC bitmap, Windows 3.x format, 1280 x 720 x 24, resolution 3780 x 3780 px/m, cbSize 2764854, bits offset 54

### Please provide sample image(s) that help explain this feature

[
](https://raw.githubusercontent.com/Jeff-Tian/gatsby-js/26158879194071fb652efb0f9659edd6ab553d70/packages/gatsby-plugin-sharp/src/__tests__/images/metadata-error.png)

> Hi, this looks like a Windows bitmap (BMP) file.
```
$ curl -s https://raw.githubusercontent.com/Jeff-Tian/gatsby-js/26158879194071fb652efb0f9659edd6ab553d70/packages/gatsby-plugin-sharp/src/__tests__/images/metadata-error.png | file -
/dev/stdin: PC bitmap, Windows 98/2000 and newer format, 1710 x 624 x 32, cbSize 4268298, bits offset 138
```

_Originally posted by @lovell in https://github.com/lovell/sharp/issues/3509#issuecomment-1368198557_

and https://camo.githubusercontent.com/fd352155596f7d714ee12230f59da7323b626c729ca94c5d4b934e379bf52fe0/68747470733a2f2f6173736574732e6d6174746572732e6e6577732f656d6265642f63313662396462652d396439662d343839332d396238622d6632326632363536623437392e706e67

**Comment by tx0c** [comment]
in browser [image1](https://camo.githubusercontent.com/fd352155596f7d714ee12230f59da7323b626c729ca94c5d4b934e379bf52fe0/68747470733a2f2f6173736574732e6d6174746572732e6e6577732f656d6265642f63313662396462652d396439662d343839332d396238622d6632326632363536623437392e706e67) showing no problem, and the `convert` from ImageMagick can process it, why not `sharp` ?

**Comment by lovell** [comment]
Please see #543 #806 #3035 for possible methods of decoding BMP images.

**Comment by tx0c** [comment]
it's not complete, but if such a method like https://github.com/lovell/sharp/issues/3035#issuecomment-1011358125 exists, why can't merge this logic as a helper into sharp?

**Comment by lovell** [comment]
Supporting as many formats as possible is not an aim of sharp, so it may be the wrong tool to solve your problem.
