### ISSUE TITLE
Is it possible to select some frames of GIF before resize ?

### ISSUE THREAD

**Issue by natuan62** [lovell/sharp#3845]
### What are you trying to achieve?

- I have big GIFs (10 - 20MB) with ~ 2-400 frames and want to resize it. 
- But with use lambda aws to handle, so spend more time to handle. (> 60 - 120 - ... seconds)
- So could I select 100 frames from total frames before resize to reduce time handle or anyway to achieve !

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```
const imageResized = image.clone().resize(300, 300);
const data = await imageResized.webp().toBuffer()
```

### Please provide sample image(s) that help explain this question

[7IsD-example-gif](https://github.com/lovell/sharp/assets/10808157/d493d029-fe77-45b1-87b9-0f621ef795da)

**Comment by lovell** [comment]
Did you see the `pages` option of the constructor?

https://sharp.pixelplumbing.com/api-constructor

```js
sharp(animatedGifInput, { pages: 100 })...
```

**Comment by natuan62** [comment]
@lovell Thanks for quick reply. Sorry for my explain not detail.

With { pages: 100 } options it will get 100 pages first.

But I want 100 frames with indexes array like [0, 2, 4, ...200]

**Comment by lovell** [comment]
There's no support for a "step" - you'll have to extract frame-by-frame then reassemble, which will probably be slower than resizing anyway.

If you're using AWS Lambda for CPU-bound tasks, remember to assign as much RAM and therefore CPU time as possible.
