### ISSUE TITLE
Performance feedback

### ISSUE THREAD

**Issue by enapupe** [lovell/sharp#3847]
Hi, I've just set up a new media transformer server for this non-profit initiative and I'm curious if the performance I'm getting is expected or maybe I messed something up?

It's a really basic fetch/transform/respond thing, the code can be seen here https://github.com/OpenBeta/media-server/blob/develop/app.js

The service is running on google cloud run, 1gb ram and 2 cpus. Images take ~3s/4s to load.
[Example call of the service](https://media-server-dlaweekx6q-uc.a.run.app/u/e18e9699-07b1-4704-962d-10a8c3374585/pqKw9hbjdH.jpg?w=1200&q=75) and the [source image for this call](https://storage.googleapis.com/openbeta-prod/u/e18e9699-07b1-4704-962d-10a8c3374585/pqKw9hbjdH.jpg)

In the past I've set sharp and I had this feeling it was much faster, but maybe I was processing much smaller images, IDK.

I can't thank you enough for the huge effort you've been putting on this project.

**Comment by lovell** [comment]
Your code looks OK from an initial glance. If you want to see whether the effects of increasing RAM and therefore CPU share would benefit this task I guess you'll probably to remove networking I/O from any performance calculations to get more accurate timings.

It's a bit trickier to do this with Stream-based I/O, but perhaps in your code you could listen for and calculate the interval between events emitted by `pipeline.queue` - see https://sharp.pixelplumbing.com/api-utility#queue

**Comment by enapupe** [comment]
Thank you. I'll consider it to be ok until something prompts for deeper insights using `pipeline.queue`.
