### ISSUE TITLE
Termux, binaries are not yet available for android-arm64v8

### ISSUE THREAD

**Issue by innocentkiller22** [lovell/sharp#3850]
after running npm install sharp in termux . i found below error 

sharp: Installation error: Prebuilt libvips 8.14.5 binaries are not yet available for android-arm64v8

i am not able to run npm install
 
please help

**Comment by lovell** [comment]
For Termux, please see https://github.com/lovell/sharp/issues/1889#issuecomment-535840238

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
