### ISSUE TITLE
Shipping broken with esbuild

### ISSUE THREAD

**Issue by s1nistr4** [lovell/sharp#3854]
## Possible bug
This can't be used in Esbuild and likely any module bundler. 
If you use it, you get the following error: 

```
No loader is configured for ".node" files:
```
So I add
```
    loader: { 
        ".node": "file" 
    },
```

to my config, and after compiling get 

```
ji.format is not a function 
```

I can't compile my code with sharp installed, once sharp is removed everything compiles fine 

### Is this a possible bug in a feature of sharp, unrelated to installation?
Yes, no other node package has this issue.

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [ x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

**Comment by lovell** [comment]
Did you see https://sharp.pixelplumbing.com/install#esbuild ?

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
