### ISSUE TITLE
The terminal device is not displayed. The JFIF identifier is missing

### ISSUE THREAD

**Issue by zhongyao-x** [lovell/sharp#3855]
How to force changes
JFIF APP0 tag segment?？

**Comment by zhongyao-x** [comment]
Thank you very much for your reply.

I want to process jpeg and png into JPEG(JFIF) in a unified way, because the terminal only supports JFIF JPG. So I can use sharp output JFIF format

**Comment by lovell** [comment]
Did you try the suggestion to use `withMetadata()`?

**Comment by zhongyao-x** [comment]
> 您尝试过使用建议吗`withMetadata()`？

Yes, I tried. It does not handle jfif

**Comment by zhongyao-x** [comment]
this is a example.
`
const sharp = require("sharp");
const fs = require("fs");

// // 输入JPEG文件路径
const inputFilePath = "demo.jpg";
const outputFilePath = "demo2.jpg";


sharp(inputFilePath)
  .withMetadata()
  .jpeg({
        chromaSubsampling: "4:4:4",
  })
  .toFile(outputFilePath, (err, info) => {
        if (err) {
          console.error(err);
        } else {
          console.log("isJFIF:", isJFIF(outputFilePath));
        }
  });

function isJFIF(filePath) {
  const buffer = Buffer.alloc(5);
  const fileDescriptor = fs.openSync(filePath, "r");
  fs.readSync(fileDescriptor, buffer, 0, 5, 0);
  fs.closeSync(fileDescriptor);

  return (
    buffer[0] === 0xff &&
    buffer[1] === 0xd8 &&
    buffer[2] === 0xff &&
    buffer[3] === 0xe0 &&
    buffer[4] === 0x00
  );
}
`

**Comment by lovell** [comment]
Try:
```diff
-    buffer[3] === 0xe0 &&
+    buffer[3] === 0xe1 &&
```

https://superuser.com/questions/1657522/what-makes-two-main-jpeg-file-formats-jfif-and-exif-incompatible

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
