### ISSUE TITLE
Is there an existing way to selectively focus the foreground and blur the background, like a bokeh effect? 

### ISSUE THREAD

**Issue by peacechen** [lovell/sharp#3857]
## Question about an existing feature

I'd like to focus the foreground while blurring the background, similar to the feature that smartphone camera apps offer to simulate a bokeh effect. I suspect it's a complicated feature, but wanted to ask if someone has figured out how to do it with existing commands.

### What are you trying to achieve?

Background blur bokeh effect

### When you searched for similar issues, what did you find that might be related?

Don't see any existing tickets mentioning focus or bokeh.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

N/A

### Please provide sample image(s) that help explain this question

N/A

**Comment by lovell** [comment]
Perhaps try compositing an SVG with suitable filters, e.g. https://stackoverflow.com/questions/37632294/can-i-make-a-bokeh-blur-with-svg-filters-or-css-filters - you'll need to know the `clipPath` of foreground vs background though.

**Comment by peacechen** [comment]
Thanks @lovell for the insightful article. The key to this is the clip path that you mentioned. It might take an AI/ML pipeline to automatically produce that.
