### ISSUE TITLE
Cannot place text where i need it to be, or i just don´t understand it

### ISSUE THREAD

**Issue by hanssonrickard** [lovell/sharp#3858]
### What are you trying to achieve?

Hi.
I am trying to add text to an image. It should be placed in the bottom of the image, in a new white area that i first create using "extend".
But regardless of what i try, the text is only centered on my image.
How can i place it in bottom of image using composite?

### When you searched for similar issues, what did you find that might be related?

All i could find was how to generate text using SVG, but i am using the "built-in" composite function to generate the text, so i am unsure if any of the SVG info i find is helping in this case?

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

This is my code to extend image and place text.

```
image = await image.extend({
          bottom: 50,
          background: { 
            r: 255, 
            g: 255, 
            b: 255, 
            alpha: 1 
          }
        })
        .composite([{ 
          input: {
            text: {
              text: textContent, 
              rgba: true
            },
            gravity: "south"
          } 
        }])
```
### Please provide sample image(s) that help explain this question
This is regardless of input image.

**Comment by lovell** [comment]
Try moving `gravity` to be a sibling of `input` rather than a descendant:
```js
.composite([{ 
  input: {
    text: {
      text: textContent, 
      rgba: true
    }
  },
  gravity: "south"
}])
```
https://sharp.pixelplumbing.com/api-composite

**Comment by hanssonrickard** [comment]
Thanks, that was actually the only level i din´t test. 
I thought it was to "far out", but now looking at it it makes sense.
