### ISSUE TITLE
Alpha channel won't work with DeepZoom

### ISSUE THREAD

**Issue by rafaelnco** [lovell/sharp#386]
Hey guys, how are you?

I'm trying to figure out why does alpha channel won't work with DZI images.

```
  sharp('image.png')
  .tile(256)
  .background(0,0,0,0)
  .// here i've already tried { nothing, embed(), flatten() }
  .toFile('image.dzi', function(err, info) {
  });
```

This code will output a dzi image with black background and no transparency at all. I've already tried modifying index.js and changing background default option to background: [0, 0, 0, 0] but this does not seem to work either. Is there something I can help you with?

Thanks in advance
att Rafael

**Comment by lovell** [comment]
Ola Rafael, as you've discovered, tiled output currently uses the JPEG format so you'll lose any alpha channel. #337 includes adding support for other output settings so I've added a comment explicitly mentioning the PNG format. Shall we move this discussion to #337?

**Comment by rafaelnco** [comment]
Ola @lovell! Sorry for the delay!

I would really appreciate to help you with this quest, although I've mitigated this issue using libvips directly. Indeed, having sharp's PNG support at hand would be really useful but there are so many other issues my team got to solve right now that I can't spend much time on this. However, I'm lazily analysing sharp's code and trying to understand where exactly is the problem

**Comment by lovell** [comment]
Thanks for the reply - I'm going to close this in favour of #337 - tudo bom!
