### ISSUE TITLE
Support for edge runtime?

### ISSUE THREAD

**Issue by nooblyf** [lovell/sharp#3860]
## Feature request
Support for edge runtime / cloudflare workers

### What are you trying to achieve?
I'm trying to run sharp on my Next.js app's api endpoint hosted on cloudflare but they only support edge runtime.

### When you searched for similar feature requests, what did you find that might be related?
This closed issue
https://github.com/lovell/sharp/issues/2863

Saw this comment on libvips' support for wasm and i think it might be possible now?
https://github.com/libvips/libvips/issues/192#issuecomment-684847123

### What alternatives have you considered?
Deploying on vercel which supports node.js runtime works just fine :)

Thank you for all your hardwork on building & maintaining sharp ❤️

**Comment by lovell** [comment]
Support for WebAssembly will be part of the forthcoming v0.33.0 - please see https://github.com/lovell/sharp/issues/3336

However it won't work on Cloudfare Workers as, despite its name, there is no support for threading or Web Workers.

**Comment by coratype** [comment]
So Sharp doesn't support edge runtimes / won't / can't due to the nature of edge?

**Comment by coratype** [comment]
okay so i'm using cloudflare's next-on-pages utility, but cloudflare outlines that some node processes are compatible, would it qualify or no?

https://developers.cloudflare.com/workers/runtime-apis/nodejs/

**Comment by lovell** [comment]
@coratype  That's probably a question for Cloudflare support, but my understanding is that the Cloudflare Pages build process is a yes but the Cloudflare Workers runtime is a no.

**Comment by coratype** [comment]
from what i understand next-on-pages builds the static pages and turns the route files into workers, ill try it out myself and see what happens

**Comment by coratype** [comment]
<img width="905" alt="Screenshot 2024-04-02 at 12 00 38 PM" src="https://github.com/lovell/sharp/assets/136992864/0bdd290a-b558-44c9-afcb-83095ba0adc1">

yeah it seems like youre right, in that case ill just look into cloudflare images or something, thanks
