### ISSUE TITLE
Building libvips from source, vips_text_wrap_get_type: symbol not found

### ISSUE THREAD

**Issue by Exp1ry** [lovell/sharp#3861]
Hello. I am having trouble allowing HEIF/C -> JPEG. I am aware that in order to make it work, I need to have "libvips compiled with support for libheif, libde265 and x265.", however, I am quite new to sharp, and with some research, still am unable to get it working.

This is where I need to have them installed:
# ---- First Stage (Build) ----
FROM node:16-alpine as build

WORKDIR /app

ENV NODE_ENV=production

# Install necessary build dependencies
RUN apk add --no-cache build-base git libheif-dev vips-dev

# Copy package.json and package-lock.json separately
COPY package.json /app/
COPY package-lock.json /app/

# Install npm dependencies and TypeScript
RUN npm ci
RUN npm install typescript

# # Copy your application code
# COPY . /app

# # ---- Second Stage (Final Image) ----
# FROM node:16-alpine
# ENV NODE_ENV=production

WORKDIR /app

# Copy the built application from the previous stage
# COPY --from=build /app /app

EXPOSE 8080

RUN npm run build

CMD ["node", "server/app.js"]

I would love if you could show me step by step the procedure to have these installed, so I am able to successfully convert HEIF/C images.

**Comment by Exp1ry** [comment]
UPDATE:
I have managed to get libvips installed, and tested it locally, and was able to convert HEIF. However, the problem comes when I want to dockerize it. 
I am a JS error, and no matter all the fixes ive tried, which are:

* Installing sharp using --platform=darwin, or --platform=linuxmusl
* Deleting node_modules and re-installing,

I am unable to get it to work on the dockerfile. Here is the updated one:

```
 FROM node:16-alpine as build

WORKDIR /app

ENV NODE_ENV=production

 COPY package.json /app/
COPY package-lock.json /app/

 RUN npm ci

 
 
 

ENV LIBVIPS_VERSION_MAJOR=8 LIBVIPS_VERSION_MINOR=12 LIBVIPS_VERSION_PATCH=2
ENV LIBVIPS_VERSION=$LIBVIPS_VERSION_MAJOR.$LIBVIPS_VERSION_MINOR.$LIBVIPS_VERSION_PATCH

 RUN apk add --no-cache \
    build-base \
    git \
    libjpeg-turbo-dev \
    libpng-dev \
    libwebp-dev \
    zlib-dev \
    fftw-dev \
    librsvg-dev \
    libexif-dev \
    orc-dev \
    tiff-dev \
    giflib-dev \
    libheif-dev \
    vips-dev \
    curl \
    make \
    automake \
    autoconf \
    libtool \
        gtk-doc


 RUN curl -L https://github.com/libvips/libvips/releases/download/v$LIBVIPS_VERSION/vips-$LIBVIPS_VERSION.tar.gz > vips-$LIBVIPS_VERSION.tar.gz && \
    tar xf vips-$LIBVIPS_VERSION.tar.gz && \
    cd vips-$LIBVIPS_VERSION && \
    ./autogen.sh && \
    ./configure --enable-debug=no && \
    make && \
    make install

 ENV LD_LIBRARY_PATH="/usr/local/lib:${LD_LIBRARY_PATH}"

RUN rm -rf node_modules
# Install npm dependencies and TypeScript
RUN npm ci
RUN npm install typescript

 

EXPOSE 8080

 
CMD ["npm","run","start:prod"]

```

**Comment by Exp1ry** [comment]
STACK: Error: 
Something went wrong installing the "sharp" module
Error relocating /app/node_modules/sharp/build/Release/sharp-linuxmusl-arm64v8.node: vips_text_wrap_get_type: symbol not found
Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current linuxmusl-arm64v8 runtime: "npm install --platform=linuxmusl --arch=arm64v8 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/app/node_modules/sharp/lib/sharp.js:37:9)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:101:39)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/app/node_modules/sharp/lib/constructor.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)

**Comment by lovell** [comment]
> ENV LIBVIPS_VERSION_MAJOR=8 LIBVIPS_VERSION_MINOR=12 LIBVIPS_VERSION_PATCH=2

It looks like you're building libvips v8.12.2 from source, please upgrade to the latest version (and you'll need to switch from using autotools to meson).

**Comment by Exp1ry** [comment]
Thank you! It works now. What a dumb thing to miss!
