### ISSUE TITLE
Inconsistent white border in different image sizes

### ISSUE THREAD

**Issue by danielwerg** [lovell/sharp#3862]
### What are you trying to achieve?

Consistent output without white border.

### When you searched for similar issues, what did you find that might be related?

Nothing, not sure what to search for.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```ts
await sharp(svgPath).resize(1000).png().toFile(pngPath);
await sharp(svgPath).resize(1200).png().toFile(pngPath);
```

```xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 500">
  <path fill="white" d="M32 32h300v300H32Z" />
  <path d="M32 32h300l-172 54L332 332H32Z" />
</svg>
```

</details>

### Please provide sample image(s) that help explain this question

<details>
<summary>1000x (no white border)</summary>

![1000](https://github.com/lovell/sharp/assets/35052399/080e2511-90dc-442a-b5b2-efb476b45424)

</details>

<details>
<summary>1200x (white border)</summary>

![1200](https://github.com/lovell/sharp/assets/35052399/e1bbaaef-d772-44a3-8a4e-d73c97d899ff)

**Comment by lovell** [comment]
Both these images appear to be rendered as-expected, both have a transparent background.

I suspect your question relates to the semi-transparent pixels around some of the edges in the 1200px PNG example.

The logic to calculate the "natural size" of an SVG is not entirely straightforward - see https://github.com/libvips/libvips/blob/35053f55e372bd3e687e987c2d68ea5cf62f85cd/libvips/foreign/svgload.c#L402 - and may result in scaling via cairo, which can introduce anti-aliasing at edges for some dimensions.

Given the `viewBox` in this SVG is relatively simple (e.g. no offset), providing explicit `width` and `height` attributes will help everything involved in its rendering to determine the natural size.

```diff
- <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 500">
+ <svg xmlns="http://www.w3.org/2000/svg" width="500" height="500">
```

**Comment by danielwerg** [comment]
Thank you for pointing me to the right direction. Unfortunately neither replacing viewBox with width and height nor simply adding it along viewBox did not change output for 1200x.

**Comment by lovell** [comment]
You could also try using [shape-rendering](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/shape-rendering) to reduce anti-aliasing.

```diff
- <path d="M32 32h300l-172 54L332 332H32Z" />
+ <path d="M32 32h300l-172 54L332 332H32Z" shape-rendering="crispEdges" />
```

**Comment by danielwerg** [comment]
Doesn't really work in my case, it only made border slightly more obvious and made diagonal lines ugly (as expected).

<details>
<summary>1200x</summary>

![1200x](https://github.com/lovell/sharp/assets/35052399/be3489b0-e96e-44d1-a977-a8d7b666bf22)

</details>

**Comment by lovell** [comment]
@danielwerg Were you able to make any progress with this?

**Comment by danielwerg** [comment]
@lovell Nope, learned to accept it when I was still working on project that needed it.

**Comment by lovell** [comment]
Thanks for the update, I'll close for now.
