### ISSUE TITLE
Support of HEIC format dropped out after 0.26.2

### ISSUE THREAD

**Issue by marco-bertelli** [lovell/sharp#3866]
## Possible bug
Support of HEIC format dropped out after 0.26.2

### Is this a possible bug in a feature of sharp, unrelated to installation?

- [ x] Running `npm install sharp` completes without error.
- [ x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x ] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 22.04 GB / 31.11 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
  npmPackages:
    sharp: 0.32.6 => 0.32.6
```

### What are the steps to reproduce?

run the following code with HEIC image format (Take a random photo from iphone gallery):

```
const resizedFile = await sharp(location)
		.rotate()
		.resize(width, height, {
			fit: 'inside',
		})
		.toFile(destination);
```

with version leatest 0.32.6 i will get an error about the format but with version 0.26.2 i can do that without problems

### What is the expected behaviour?

be able to execute the code as the version 0.26.2

**Comment by lovell** [comment]
The prebuilt binaries provided by sharp have never supported HEIC (HEVC within HEIF).

Support for a globally-installed libvips compiled with support for libheif+x265 was added in v0.23.0, so I suspect you've been relying on this. Please ensure the version of libvips matches the minimum required for the corresponding version of sharp.

https://sharp.pixelplumbing.com/install#custom-libvips
https://sharp.pixelplumbing.com/changelog

**Comment by marco-bertelli** [comment]
yeah but why with the same version of libvips (is my local pc) and only changing the sharp version all work fine? same on heroku server, is not a problem to change the version but i want to understand what changed

**Comment by marco-bertelli** [comment]
Thanks @lovell i will close this
