### ISSUE TITLE
Wrong output: resize (ignore aspect ratio) -> rotate 90 degrees

### ISSUE THREAD

**Issue by kleisauke** [lovell/sharp#387]
Thanks for this awesome library, it's a great way to discover the speed and power of libvips.

After some testing I found a bug. See this testcase:
```javascript
var path = require('path');
var sharp = require('sharp');
var assert = require('assert');

sharp(path.resolve(__dirname, '2569067123_aca715a2ee_o.jpg')).resize(300, 300).ignoreAspectRatio().rotate(90).toFile(path.resolve(__dirname, '2569067123_aca715a2ee_o_2.jpg'), function(err, info) {
      if (err) throw err;
      assert.strictEqual('jpeg', info.format);
      assert.strictEqual(300, info.width);
      assert.strictEqual(300, info.height);
});
```

(No `AssertionErrors` are thrown but the output is wrong)

Output:
![Resize to 300x300 (ignore aspect-ratio) -> rotate 90 degrees - WRONG](https://cloud.githubusercontent.com/assets/12746591/14080615/94a337e4-f506-11e5-9516-df811a417327.jpg)

Expected output:
![Resize to 300x300 (ignore aspect-ratio) -> rotate 90 degrees - GOOD](https://cloud.githubusercontent.com/assets/12746591/14080649/cb99e518-f506-11e5-9928-bf04dfca2210.jpg)

Tested on Windows 10 x64, Node.js v5.9.1 with the latest Sharp (v0.13.1)

**Comment by lovell** [comment]
Hallo Kleis, great spot, thanks for reporting this. It looks like the x and y ratios need to be swapped when ignoring aspect with a 90 or 270 degree rotation. Should be an easy one to fix - thanks for the test case.

**Comment by lovell** [comment]
Commit 25b63a2 adds a test case that would previously have failed and the fix so it doesn't.

**Comment by kleisauke** [comment]
Thanks for the fix! It's working when the width and height are equal. However when the width and height and not the same then width === height. See this testcase (method order is first rotate then resize):
```javascript
var path = require('path');
var sharp = require('sharp');
var assert = require('assert');

sharp(path.resolve(__dirname, '2569067123_aca715a2ee_o.jpg'))
  .rotate(270)
  .resize(500, 250)
  .ignoreAspectRatio()
  .toBuffer(function(err, data, info) {
    if (err) throw err;
    assert.strictEqual(500, info.width);
    assert.strictEqual(250, info.height);
    sharp(data).metadata(function(err, metadata) {
      assert.strictEqual(500, metadata.width);
      assert.strictEqual(250, metadata.height);
    });
});
```

```shell
 AssertionError: 500 === 250
    at C:\testcase2.js:14:14
```

Is this the desired behavior? Should the final width and final height not be swapped when we first rotate 90 (or 270) degrees and then resize the picture?

**Comment by lovell** [comment]
Method ordering is (currently) only taken into consideration when both extracting and rotating. I agree that in this case the dimensions provided to `resize` should "win" when it comes to the output image dimensions.

We should probably also make the `info` object report on actual rather than calculated values!

Thanks again for providing test cases for previously uncharted paths through some of this code. Leave this one with me, heh heh.

**Comment by lovell** [comment]
Commit 24fb0c3 adds your non-square test case and its fix, which is to swap both dimensions and scaling factors. Thanks again for these great new test cases.

**Comment by kleisauke** [comment]
Just tested and I can confirm that this issue is resolved. :thumbsup:

Should I leave this issue open till [v0.14.0](https://github.com/lovell/sharp/milestones/v0.14.0) is released?

**Comment by lovell** [comment]
Great news, and yes please, let's leave this open. v0.14.0 is almost ready; only one more PR to land.

**Comment by lovell** [comment]
v0.14.0 now available via npm with the fix, thanks again for reporting.

**Comment by GermaVinsmoke** [comment]
`ignoreAspectRatio()` is deprecated. https://github.com/lovell/sharp/issues/935
Instead of this, one can specify the `fit` property inside the `resize()`.

```
sharp(input).resize({
  width: 1280,
  height: 480,
  fit: 'fill'
})
```
