### ISSUE TITLE
Is cropping (using "extract") for GIFs working/supported ?

### ISSUE THREAD

**Issue by lorcat9** [lovell/sharp#3874]
### What are you trying to achieve?

Cropping GIFs images (using `extract`), `resize` work fine instead. 

I'm using the version `0.32.6`.

### When you searched for similar issues, what did you find that might be related?

I haven't found anything related to cropping but only resizing.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question
The code runs fine when instead of using a GIF as input I use a JPEG image.
```
  const sharpImage = sharp(`${resourcesDirectory}/input.gif`, {
    animated: true
  })
  const metadata = await sharpImage.metadata()

  assert(metadata.height !== undefined)
  assert(metadata.width !== undefined)

  await sharpImage.clone()
  .resize(100, 100)
  .toFile(`${resourcesDirectory}/output_resize.${metadata.format}`)
  
  // it fails with GIFs 
  await sharpImage.clone()
    .extract({
      left: 100,
      top: 0,
      width: metadata.width - 100,
      height: metadata.height
    })
    .toFile(`${resourcesDirectory}/output_crop.${metadata.format}`)
```
The error is 
```
[Error: extract_area: bad extract area]
```

### Please provide sample image(s) that help explain this question

Tested with this GIF: https://upload.wikimedia.org/wikipedia/commons/2/2c/Rotating_earth_%28large%29.gif

**Comment by lovell** [comment]
Yes, you'll probably want extract the `pageHeight` (rather than the `height`, which is all frames combined).
```diff
-      height: metadata.height
+      height: metadata.pageHeight
```

**Comment by lorcat9** [comment]
@lovell yes that was it, thanks! :)
