### ISSUE TITLE
3D transformations possible?

### ISSUE THREAD

**Issue by peacechen** [lovell/sharp#3876]
## Question about an existing feature

I would like to rotate an image in arbitrary XYZ space. The existing rotations are 2D as far as I have found.

### What are you trying to achieve?

Here's an example of a 3D transformation. This was done in GIMP using its transformation tool.
https://temperal.co/

### When you searched for similar issues, what did you find that might be related?

Searched for 3D, transform, etc

**Comment by lovell** [comment]
Did you see #3071?

**Comment by peacechen** [comment]
Thanks @lovell for pointing me in the right direction. I wasn't aware of the affine operation. The discussions in the related threads are unresolved for achieving projections. Is that possible with affine?

**Comment by lovell** [comment]
Did you see https://github.com/lovell/sharp/issues/2095?
