### ISSUE TITLE
Enhancement Suggestion For toBuffer "info" parameter

### ISSUE THREAD

**Issue by kleite** [lovell/sharp#388]
Currently the "info" parameter in the 'toBuffer' callback provides "format, size, width, height and channels", which is very useful information about the finished image.  But it would be extremely helpful to have the original byte size of the input image so that the before/after difference could be determined.

Thanks,
Kris

**Comment by lovell** [comment]
The `info` parameter made available after processing is typically for values that are (potentially) calculated during processing, e.g. the calculated image height when only the width was specified.

I can see value in providing the compressed input size when using Stream-based input (behaves like a byte counter).

It makes most sense for the logic to live in the C++ part of the code, probably `HandleOKCallback`, and will need to use the cross-platform [g_stat](https://github.com/lovell/sharp/blob/master/src/pipeline.cc#L838-L839) call to size file-based input.

Happy to accept a PR for this - thanks for the suggestion!

**Comment by lovell** [comment]
This feature can be implemented outside of sharp using something like an intermediate byte-counting Stream such as https://github.com/yoshuawuyts/size-stream
