### ISSUE TITLE
Color overlay similar to Photoshop.

### ISSUE THREAD

**Issue by whoacowboy** [lovell/sharp#3880]
## Question about an existing feature

Is there a way to get a color overlay similar to Photoshop's effects Color Overlay?

### What are you trying to achieve?

I'd like to start with a transparent png with a slight shadow and do a color overlay that includes the shadow. 

![dog](https://github.com/lovell/sharp/assets/8116953/89eb5f5f-f0e4-4ebd-950f-ac3276c5da43)

![dog-overlay](https://github.com/lovell/sharp/assets/8116953/779cbc5c-6a21-4332-a5ce-aaaf1981e55c)

### When you searched for similar issues, what did you find that might be related?

I found a couple of ways to get a similar effect but they wash the shadow out when the colors are too similar.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

This is the closest:

```
async function overlay({ img, props }) {
  const grey = {
    create: {
      width: props.width,
      height: props.height,
      channels: 4,
      background: { r: 224, g: 224, b: 224, alpha: 1 },
    },
  };
  return await sharp(grey)
    .toFormat("png")
    .composite([
      {
        input: await img.toBuffer(),
        blend: "dest-atop",
      },
    ]);
}
```

This way also works for a silhouette

```
const img = await sharp(buffer, { failOn: "none" })
  .resize({
    width: props.width,
    height: props.height,
  })
  .modulate({
    brightness: 0,
    saturation: 0,
  })
  .toBuffer();
```

### Awesome library

Your library has been a life saver, thank you!

**Comment by lovell** [comment]
Did you see the docs relating to blend modes?

https://sharp.pixelplumbing.com/api-composite
https://www.cairographics.org/operators/

The "in" blend is probably most appropriate here.

> The first object is removed completely, the second is only drawn where the first was.

```js
const data = await sharp(input)
  .composite([
    {
      input: {
        create: {
          width: 460,
          height: 307,
          channels: 3,
          background: 'maroon',
        },
      },
      blend: 'in'
    },
  ])
  .toBuffer();
```
![](https://github.com/lovell/sharp/assets/210965/1330b666-5e65-46ed-9aea-42f1b85f4771)

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by whoacowboy** [comment]
@lovell This is great thank you.
