### ISSUE TITLE
When I apply Sharpen, the sizzle gets worse and the color tone seems to change a bit. What could be wrong?

### ISSUE THREAD

**Issue by henryfra14** [lovell/sharp#3882]
### What are you trying to achieve?

I want to reduce sizzle and keep the color the same as the original.

### When you searched for similar issues, what did you find that might be related?

no. couldn't find it

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```
await sharp('image.jpg')
.sharpen()
.jpeg({
   quality: 90,
   chromaSubsampling: '4:4:4'
})
.toFile('./image.jpg', (err, info) => {
....
})
```

### original
<img src="https://github.com/lovell/sharp/assets/44634829/58b60dd7-f076-40d5-a98c-2a5b5386a5c4"/>

### after sharpen
<img src="https://github.com/lovell/sharp/assets/44634829/5dfc8810-98af-4a60-aa94-efab0f056682" />

**Comment by lovell** [comment]
By "sizzle" I suspect you are referring to compression artefacts that appear on edges between areas of dark and light.

Given you're attempting to sharpen a compressed JPEG input, which already contains compression artefacts, the use of `sharpen()` will only make these more apparent.

Perhaps try using the `convolve()` operation with a 5x5 unsharp mask, the example at https://en.wikipedia.org/wiki/Kernel_(image_processing) would be a good place to start.

https://sharp.pixelplumbing.com/api-operation#convolve

**Comment by henryfra14** [comment]
I checked 'convolve' and '5x5 unsharp mask', but I don't understand them correctly.
```
cont result = sharp('image.jpg')
.convolve({
    width: 3,
    height: 3,
    kernel: [-1, 0, 1, -2, 0, 2, -1, 0, 1]
  })
.toBuffer({ resolveWithObject: true });
console.log(result.data);
```
Is the code above just detecting the edges of the image?
I am not sure how to proceed with the next steps with the buffer obtained above.

**Comment by lovell** [comment]
The [example 5x5 unsharp mask](https://en.wikipedia.org/wiki/Kernel_(image_processing)) could be used a bit like this (untested):
```js
.convolve({
  width: 5,
  height: 5,
  kernel: [
    1,  4,  6,  4, 1,
    4, 16, 24, 16, 4,
    ...
  ]
})
```

**Comment by henryfra14** [comment]
I proceeded by referring to what you sent.
```
.convolve({
  width: 5,
  height: 5,
  kernel: [
  -1/256,-4/256,-6/256,-4/256,-1/256,
  -4/256,-16/256,-24/256,-16/256,-4/256,
  -6/256,-24/256,476/256,-24/256,-6/256,
  -4/256,-16/256,-24/256,-16/256,-4/256,
  -1/256,-4/256,-6/256,-4/256,-1/256,
  ]
})
```
The result of applying the above code is as follows.
<img src='https://github.com/lovell/sharp/assets/44634829/ee416f23-b8b1-46b0-91d8-a13b1cfe9d6f' />

The "sizzle" seems to be worse than the result of the first question.

Is this the best outcome?

If there is a way to proceed further here, please advise.

Thank you for answering my continuing questions. :-)

**Comment by lovell** [comment]
Oh, that's definitely worse, but it was worth experimenting with. Your best bet is still to not apply any sharpening If you know you have JPEG input images with high contrast edges that are already likely to contain compression artefacts. Perhaps you could go back to the original source of the input images to see if there are higher quality or lossless versions.

**Comment by henryfra14** [comment]
Ok. So how can i check JPEG input images with high contrast edges? Can I check this with convolve as well? 
I think this may be a bit of a reckless question.
It would be nice if there was a way, but for service purposes it would be better not to apply sharpening overall.
