### ISSUE TITLE
cannot run tests using Vitest 1.0.1 on Windows 10

### ISSUE THREAD

**Issue by userquin** [lovell/sharp#3885]
### What are you trying to achieve?

I'm trying to add some sharp tests with Vitest in [@vite-pwa/assets-generator](https://github.com/vite-pwa/assets-generator) in this PR https://github.com/vite-pwa/assets-generator/pull/24 using [In-Source Testing](https://vitest.dev/guide/in-source).

When running the tests in my Windows laptop, it is failing:
![imagen](https://github.com/lovell/sharp/assets/6311119/45c3dbfa-75dd-41d4-9610-6cbd52631667)

Adding sharp to Vitest `optimizedDeps.include` I get this another error:
![imagen](https://github.com/lovell/sharp/assets/6311119/65141e70-e688-47a1-a936-94b3672826a9)

The test in question can be found here: https://github.com/vite-pwa/assets-generator/pull/24/files#diff-cdf2787c454e2cddb626af73f3a0573cce656012e887347927544a4a2d0a49aeR62-R76

### When you searched for similar issues, what did you find that might be related?

NA

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

You can clone the repo to your local and checkout `userquin/feat-add-api-support` branch, running from root project folder (requires pnpm with corepack enabled and Node 18/20):
- `pnpm install`
- `pnpm test`

You can also run the same test logic using `pnpm test1`, the script can be found in the scripts folder: `scripts/test.ts`.

Any idea what's wrong? It seems a problem with sharp and Vitest, I want to use both.

NOTE: I need to test it in separate test files, not yet tested.

### Please provide sample image(s) that help explain this question

check description

**Comment by lovell** [comment]
If you're using any form of code bundling you'll need to exclude sharp, which I think would be via `optimizedDeps.exclude` for vitest.

https://sharp.pixelplumbing.com/install#bundlers

**Comment by userquin** [comment]
should be a problem with `vite-node`, adding sharp to exclude list same error

**Comment by userquin** [comment]
Fixed, adding beforeEach and afterEach with same options here works in Windows: 
- https://github.com/vite-pwa/assets-generator/pull/24/files#diff-1e4edaa16e78d2446f90d1593d39563edfc10f65493008ed2f592a9846b60d0b
- https://github.com/vite-pwa/assets-generator/pull/24/files#diff-2ee894bf23aa44ff4ce12a3da8af19ab20180474ebf2176dbe5f2eea3f96dc92R6

thx @lovell
