### ISSUE TITLE
Electron forge build issues. Application and installer will not run, citing sharp as the issue.

### ISSUE THREAD

**Issue by cconley717** [lovell/sharp#3887]
## Possible install-time or require-time problem

- [x] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Are you using a supported runtime?

- [x] I am using Node.js with a version that satisfies `^18.17.0 || ^20.3.0 || >=21.0.0`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these,
please upgrade to the latest version
and try again before opening an issue.

### Are you using a supported package manager and installing optional dependencies?

- [x] I am using npm >= 9.6.5 with `--include=optional`
- [ ] I am using yarn >= 3.2.0 and I am not using the "Plug'n'Play" linker
- [ ] I am using pnpm >= 7.1.0 with `--no-optional=false`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these,
please upgrade to the latest version of your chosen package manager
and ensure you are allowing the installation of optional dependencies
before opening an issue.

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

PS C:\test> npm install --verbose --foreground-scripts sharp
npm verb cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
npm info using npm@10.2.3
npm info using node@v20.10.0
npm verb title npm install sharp
npm verb argv "install" "--loglevel" "verbose" "--foreground-scripts" "sharp"
npm verb logfile logs-max:10 dir:C:\Users\cconl\AppData\Local\npm-cache\_logs\2023-12-10T00_18_47_656Z-
npm verb logfile C:\Users\cconl\AppData\Local\npm-cache\_logs\2023-12-10T00_18_47_656Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/sharp 372ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/semver 455ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color 487ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 702ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-darwin-arm64 895ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-s390x 904ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-s390x 918ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-x64 927ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-darwin-x64 1095ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-darwin-x64 1110ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linuxmusl-arm64 1107ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-arm64 1106ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-arm64 1154ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-x64 1148ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-arm 1164ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-darwin-arm64 1177ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linuxmusl-x64 1169ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-wasm32 1175ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-arm 1187ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linuxmusl-x64 1186ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linuxmusl-arm64 1197ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-win32-ia32 1200ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-win32-x64 1201ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-string 81ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/lru-cache 80ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-convert 107ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@emnapi%2fruntime 580ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/tslib 53ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-name 68ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle 76ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-name 82ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 60ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/yallist 66ms (cache revalidated)
npm verb reify failed optional dependency C:\test\node_modules\@img\sharp-win32-ia32
npm verb reify failed optional dependency C:\test\node_modules\@img\sharp-wasm32
npm verb reify failed optional dependency C:\test\node_modules\@emnapi\runtime
npm verb reify failed optional dependency C:\test\node_modules\tslib
npm verb reify failed optional dependency C:\test\node_modules\@img\sharp-linuxmusl-x64
npm verb reify failed optional dependency C:\test\node_modules\@img\sharp-linuxmusl-arm64
npm verb reify failed optional dependency C:\test\node_modules\@img\sharp-linux-x64
npm verb reify failed optional dependency C:\test\node_modules\@img\sharp-linux-s390x
npm verb reify failed optional dependency C:\test\node_modules\@img\sharp-linux-arm64
npm verb reify failed optional dependency C:\test\node_modules\@img\sharp-linux-arm
npm verb reify failed optional dependency C:\test\node_modules\@img\sharp-libvips-linuxmusl-x64
npm verb reify failed optional dependency C:\test\node_modules\@img\sharp-libvips-linuxmusl-arm64
npm verb reify failed optional dependency C:\test\node_modules\@img\sharp-libvips-linux-x64
npm verb reify failed optional dependency C:\test\node_modules\@img\sharp-libvips-linux-s390x
npm verb reify failed optional dependency C:\test\node_modules\@img\sharp-libvips-linux-arm64
npm verb reify failed optional dependency C:\test\node_modules\@img\sharp-libvips-linux-arm
npm verb reify failed optional dependency C:\test\node_modules\@img\sharp-libvips-darwin-x64
npm verb reify failed optional dependency C:\test\node_modules\@img\sharp-libvips-darwin-arm64
npm verb reify failed optional dependency C:\test\node_modules\@img\sharp-darwin-x64
npm verb reify failed optional dependency C:\test\node_modules\@img\sharp-darwin-arm64
npm info run sharp@0.33.0 install node_modules/sharp node install/check

> sharp@0.33.0 install
> node install/check

npm info run sharp@0.33.0 install { code: 0, signal: null }

added 12 packages in 6s

2 packages are looking for funding
  run `npm fund` for details
npm verb exit 0
npm info ok
PS C:\test>

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

PS C:\test> npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp
Need to install the following packages:
envinfo@7.11.0
Ok to proceed? (y)

  System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 18.35 GB / 31.88 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: ^0.33.0 => 0.33.0

PS C:\test>

### Summary

I'm in the final stages of deployment for a Node.js Express application but have reached an issue with my Electron build concerning the sharp module. For some reason, Electron Forge simply refuses to output a working build and distribution. I've been hammering away at this pretty much all day today and yesterday to no avail. 

I've created a repository containing a minimal Node.js Express application for testing that reproduces the issue. I'm sure I'm overlooking something simple here, but I haven't been able to find any special considerations with regards to sharp and Electron.
https://github.com/cconley717/electron-sharp-test

![error](https://github.com/lovell/sharp/assets/26640616/ca760286-05a1-4920-b5d9-32d0a1c29cf1)

The following is Electron's process.versions output.
{
  node: '18.18.2',
  acorn: '8.10.0',
  ada: '2.6.0',
  ares: '1.19.1',
  brotli: '1.0.9',
  cldr: '43.0',
  icu: '73.1',
  llhttp: '6.0.11',
  modules: '119',
  napi: '9',
  nghttp2: '1.57.0',
  openssl: '1.1.1',
  simdutf: '3.2.14',
  tz: '2023c',
  undici: '5.26.3',
  unicode: '15.0',
  uv: '1.44.2',
  uvwasi: '0.0.18',
  v8: '12.0.267.8-electron.0',
  zlib: '1.2.13.1-motley',
  electron: '28.0.0',
  chrome: '120.0.6099.56'
}

**Comment by lovell** [comment]
Specifying `asarUnpack` usually fixes this kind of problem e.g. https://github.com/lovell/sharp/issues/678#issuecomment-275956028

With the latest sharp v0.33.0 you might need to set this to something like:
```
"asarUnpack": [ "**/node_modules/sharp/**/*", "**/node_modules/@img/**/*" ]
```

**Comment by cconley717** [comment]
I've applied the recommended changes to my package.json, but to no success, I'm afraid.

I've managed to get the complete output of the exception via the terminal so as to retrieve the non-truncated file paths. Strangely, the file paths that the exception claims do not exist do indeed exist.

![2](https://github.com/lovell/sharp/assets/26640616/80dfa1df-ba20-45cb-abfd-44f84103cdd0)
![1](https://github.com/lovell/sharp/assets/26640616/edb4888f-6d5b-47a0-8c40-01dc61cb80a2)

I've updated the repository with changes to reflect ongoing testing; main.js has commented code to print the exception when running the exe (out\electron-sharp-test-win32-x64\electron-sharp-test.exe) from the terminal, and package.json has been updated.

**Comment by lovell** [comment]
> I've applied the recommended changes to my package.json, but to no success, I'm afraid.

Do these changes need to be made to your `forge.config.js` file instead? https://github.com/cconley717/electron-sharp-test/blob/18042e23b9daf930c6f5be27d78a57940b5a29df/forge.config.js#L2-L4

**Comment by cconley717** [comment]
You're right, and I have further found success with some slight changes to the asar unpack directory syntax. I've made the appropriate changes to the repository and I will leave it up for public reference.

Both *out\make\squirrel.windows\x64\electron-sharp-test-1.0.0 Setup.exe* and *out\electron-sharp-test-win32-x64\electron-sharp-test.exe* now compile and run without issue.
