### ISSUE TITLE
PDF file can't be decoded

### ISSUE THREAD

**Issue by adityapatadia** [lovell/sharp#3889]
## Possible bug
We are not able to decode a PDF file.

### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.
- [x] 0.33.0

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?
```
  System:
    OS: macOS 14.1.2
    CPU: (8) arm64 Apple M2
    Memory: 105.22 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - /opt/homebrew/opt/node@20/bin/node
    npm: 10.2.3 - /opt/homebrew/opt/node@20/bin/npm
  npmPackages:
    sharp: 0.33.0 => 0.33.0
```

### What are the steps to reproduce?

Try to extract a page from PDF file given at below link (please request access, I will give it to limited set of people).

### What is the expected behaviour?

Sharp should be able to extract page from PDF file as Chrome browser which uses same PDFium extracts it perfectly fine.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```
import sharp from 'sharp';

async function transform() {
    let sharp_option = {
        failOn: 'none',
        page: 1,
        sequentialRead: true,
        density:   72
      };
    let tr = sharp("response.pdf", sharp_option);
    tr.toFile("page1.jpeg");

}
transform()
```

### Please provide sample image(s) that help explain this problem

https://drive.google.com/file/d/1JL5FRZnpnN9E2YQ46C-MoRVvFkbYLt9Y/view?usp=sharing

**Comment by lovell** [comment]
> which uses same PDFium

I assume you're using a globally-installed libvips compiled from source with support for pdfium.

What is the output of running `vipsheader -a response.pdf` at the command line?

**Comment by adityapatadia** [comment]
```vipsheader: command not found```

Where can it be found?

**Comment by adityapatadia** [comment]
Is it possible that sharp is not taking globally installed VIPS library and instead using its own VIPS? How can I check it?

**Comment by lovell** [comment]
Did you see https://sharp.pixelplumbing.com/install#building-from-source ? Please take time to read it again as there are changes in v0.33.0.

All decisions made by sharp at install time are logged. If you're using npm you may need to add the `--foreground-scripts` and `--verbose` flags to see these.

**Comment by adityapatadia** [comment]
Doing `npm -g node-addon-api node-gyp` solved it. Just a suggestion, please write such breaking changes in change log in depth.

Thanks for quick help.

**Comment by adityapatadia** [comment]
Sorry this still has not been resolved. Somehow sharp still does not take globally installed VIPS.

**Comment by adityapatadia** [comment]
For anyone reading this, you need `npm install node-addon-api node-gyp`. Don't use `-g` option.

**Comment by lovell** [comment]
https://github.com/lovell/sharp/blob/a584ae093e1198d9d7171ec924218f5aafcb2ff5/docs/install.md?plain=1#L111

**Comment by adityapatadia** [comment]
Noted. I just tried to do something that should not have been done.
