### ISSUE TITLE
incompatible library version

### ISSUE THREAD

**Issue by SuThaw** [lovell/sharp#389]
I got this error when i tried to run.

"Reason: Incompatible library version: libvips-cpp.42.dylib requires version 38.0.0 or later, but libpng16.16.dylib provides version 35.0.0"

**Comment by lovell** [comment]
Hello, running `brew update && brew upgrade` and/or `brew unlink libpng && brew link libpng` might help. See #323 too.

**Comment by SuThaw** [comment]
brew update && brew upgrade solve my problem. Thank you.
