### ISSUE TITLE
Issue with Resizing 16K Resolution Images using Sharp Library in AWS Lambda

### ISSUE THREAD

**Issue by mrudzevicius** [lovell/sharp#3891]
Hello Team,

I'm raising this issue as a question since I'm not entirely sure if it's a bug or a limitation with our current setup. We are using the Sharp library in an AWS Lambda environment (Node 16) to resize images. However, we are encountering errors when attempting to resize a 16K resolution photo (PNG format, image width 16000 pixels).

Here's the code snippet for our resizeImage function:
```
function resizeImage(inputBuffer, width, suffix) {
  console.log('Resizing image.');

  return new Promise((resolve, reject) => {
    sharp(inputBuffer)
      .resize(width, width, {
        fit: sharp.fit.inside,
        withoutEnlargement: true,
      })
      .rotate()
      .toBuffer()
      .then(outputBuffer => resolve({
        body: outputBuffer,
        suffix,
      }))
      .catch(err => {
        console.error('Resize image failed');
        reject(err);
      });
  });
}
```
The error logs from Lambda indicate an issue with storage.
<img width="1673" alt="Screenshot 2023-12-11 at 08 43 07" src="https://github.com/lovell/sharp/assets/104765732/8b48e959-5c47-45f3-9858-0f6583d2ac01">

However, we've determined that this is not the case as Sharp does not use Lambda's /tmp storage. Additionally, we are dealing with images of approximately 20MB in size, and the /tmp storage has a capacity of 2GB. The /tmp storage is also consistently cleared as the Lambda function terminates.

So, my question is: Does the Sharp library support resizing of 16K resolution photos? If it does, what could be the potential issues we're facing? Could it be related to the AWS Lambda serverless environment?

Any insights or suggestions would be greatly appreciated.

Thank you.

**Comment by lovell** [comment]
Did you see https://github.com/lovell/sharp/issues/1661 ?

If you weren't already aware, Node.js 16 is EOL and is no longer supported.
