### ISSUE TITLE
Input buffer contains unsupported image format

### ISSUE THREAD

**Issue by simoneb** [lovell/sharp#3892]
### What are you trying to achieve?

Process an image coming from a URL, which I retrieve via node-fetch. The same image, when loaded from the original url, works fine. When uploaded to imgurl, it doesn't. So I'm trying to understand why that would make any difference.

### When you searched for similar issues, what did you find that might be related?

Lots of issues mentioning this specific error, but I couldn't find anything that would related to the problem I'm seeing.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```js
import fetch from 'node-fetch'
import sharp from 'sharp'

const url = '...' // some image url

const imageRes = await fetch(url)
const sharpStream = sharp().resize(512, 512)
imageRes.body.pipe(sharpStream)
```

### Please provide sample image(s) that help explain this question

- the url of the image that works: https://daily.jstor.org/wp-content/uploads/2015/05/standardizedtests.jpg
- the url of the same image uploaded to imgur, which doesn't work: https://i.imgur.com/OPIItCu.jpg

Note that both of them open just fine in the browser

**Comment by lovell** [comment]
Do you need to check `imageRes.status`? (I ask as the Imgur service readily dishes out 429 status codes to certain user agents / IP addresses.)

**Comment by simoneb** [comment]
Good point, something I had not checked! Thanks for the quick response, I was looking at a red herring it seems.
