### ISSUE TITLE
Sharp and Canvas work fine running locally, but neither work in production :( 

### ISSUE THREAD

**Issue by jamierpond** [lovell/sharp#3899]
## Possible install-time or require-time problem

- [ ] I have read and understood all of the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [ ] I have searched for known bugs relating to this problem in my choice of package manager.

You must confirm both of these before continuing.

### Are you using the latest version of sharp?

- [ ] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Are you using a supported runtime?

- [ ] I am using Node.js with a version that satisfies `^18.17.0 || ^20.3.0 || >=21.0.0`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these,
please upgrade to the latest version
and try again before opening an issue.

### Are you using a supported package manager and installing optional dependencies?

- [ ] I am using npm >= 9.6.5 with `--include=optional`
- [ ] I am using yarn >= 3.2.0 and I am not using the "Plug'n'Play" linker
- [ ] I am using pnpm >= 7.1.0 with `--no-optional=false`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these,
please upgrade to the latest version of your chosen package manager
and ensure you are allowing the installation of optional or multi-platform dependencies
before opening an issue.

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

</details>

**Comment by lovell** [comment]
Please provide significantly more information, ideally a minimal, standalone repo with dependencies and code that allows someone else to reproduce.

**Comment by GiuseppeScottoLavina** [comment]
```js title=index.mjs
import sharp from "npm:sharp@next";

const image = await sharp('https://cdn.jsdelivr.net/gh/lovell/sharp@main/docs/image/sharp-logo.svg');

console.log(image);
```

`deno compile --allow-ffi --allow-read index.mjs`

**Comment by GiuseppeScottoLavina** [comment]
> Please provide significantly more information, ideally a minimal, standalone repo with dependencies and code that allows someone else to reproduce.

```js
import sharp from "npm:sharp@next";

const image = await sharp('https://cdn.jsdelivr.net/gh/lovell/sharp@main/docs/image/sharp-logo.svg');

console.log(image);
```

```bash
 deno run -A index.mjs
```
works correctly

```bash
 deno compile --allow-ffi --allow-read index.mjs
 ./compiled
```
don't work

**Comment by lovell** [comment]
@GiuseppeScottoLavina The use of `deno compile...` is unlikely to work. If you still require help, please open a [new issue](https://github.com/lovell/sharp/issues/new?assignees=&labels=question&projects=&template=question.md) rather than comment on an existing, unrelated issue.

**Comment by lovell** [comment]
@jamierpond I'm going to close this issue as there's not enough information for anyone to help you and, as you can see, these kind of blank/generic issues attract off-topic comments. Please feel free to re-open with more details if further assistance is required.
