### ISSUE TITLE
sharp building fails

### ISSUE THREAD

**Issue by ashish-soni** [lovell/sharp#390]
npm ERR! Linux 3.14.36-20150326-1131-6606ede
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.36
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.13.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.13.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

**Comment by lovell** [comment]
Please can you provide more of the error log that appears before this.

**Comment by ashish-soni** [comment]
@lovell  it was some npm related issue. I am able to bulid it now. Thanks.
