### ISSUE TITLE
Error during build while offile trying to fetch headers from unofficial nodejs

### ISSUE THREAD

**Issue by PCPbiscuit** [lovell/sharp#3901]
## Possible install-time or require-time problem

- [x] I have read and understood all of the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have searched for known bugs relating to this problem in my choice of package manager.

0.32.6 (latest in our company's nexus)
- [X] I am using Node.js with a version that satisfies `^18.17.0 || ^20.3.0 || >=21.0.0`
- [x] I am using npm >= 9.6.5 with `--include=optional`

I'm using node:alpine-18.17.0 with nexus hence no outside internet connection. 

I've tried installing vips and all the required libs within Docker, I've also tried redirecting downloads to our nexus using .npmrc. 
However, it always fails at the same step. 
```
gyp http GET https://unofficial-builds.nodejs.org/download/release/v18.17.0/node-v18.17.0-headers.tar.gz
gyp WARN install got an error, rolling back install
#0 34.42 npm ERR! gyp ERR! configure error
#0 34.43 npm ERR! gyp ERR! stack FetchError: request to https://unofficial-builds.nodejs.org/download/release/v18.17.0/node-v18.17.0-headers.tar.gz failed, reason: getaddrinfo EAI_AGAIN unofficial-builds.nodejs.org
```

It's trying to download some headers and obviously since I don't have any internet connection I can't. May be I'm missing something? I've read installation docs a thousand times already but I can't figure out what I'm doing wrong. Any suggestions would be greatly appeciated

**Comment by lovell** [comment]
> 0.32.6 (latest in our company's nexus)

Please upgrade to the latest v0.33.1.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
