### ISSUE TITLE
Image is black and white after resize

### ISSUE THREAD

**Issue by cuixiping** [lovell/sharp#3902]
### Is this a possible bug in a feature of sharp, unrelated to installation?
- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

I noticed that #3894 which is closed and with Linux.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM)2 Duo CPU     T7700  @ 2.40GHz
    Memory: 570.82 MB / 8.00 GB
  Binaries:
    Node: 20.10.0 - D:\nodejs-nvm\node.EXE
    npm: 10.2.3 - D:\nodejs-nvm\npm.CMD
  npmPackages:
    sharp: ^0.33.1 => 0.33.1
```

### What are the steps to reproduce?

resize, save, and preview the image.

Before & After:
![image](https://github.com/lovell/sharp/assets/1104492/205d7522-4cb0-421b-ad17-212e14303eb1)

### What is the expected behaviour?

keep correct colors

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```
const sharp = require('sharp');
sharp('demo.jpg').jpeg({quality: 70}).resize(800).toFile(`resized.jpg`);
```

### Please provide sample image(s) that help explain this problem

https://infinity.unstable.life/images/Screenshots/83/17/83171320-0625-47fd-99bf-272a0d02f3f3.jpg?type=jpg

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/3893

**Comment by cuixiping** [comment]
Thanks @lovell 
The issue is solved with `sharp.simd(false)`
