### ISSUE TITLE
Sharp library size up to >15MB on Vercel

### ISSUE THREAD

**Issue by mdjfs** [lovell/sharp#3904]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [ ] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

![image](https://github.com/lovell/sharp/assets/56895143/65a7ac07-637f-4417-b14e-e037affa284e)

### What are the steps to reproduce?

1. Use sharp in a project
2. Deploy to vercel and checks the lib size

### What is the expected behaviour?

A lightweight library under <1MB if is possible 

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

Just deploy an app to vercel using sharp

### Please provide sample image(s) that help explain this problem

![image](https://github.com/lovell/sharp/assets/56895143/65a7ac07-637f-4417-b14e-e037affa284e)

**Comment by lovell** [comment]
The prebuilt binaries provided by sharp are designed to support common image formats and be as small as possible without sacrificing speed. Depending on the platform, these binaries are typically around 16MB, as you've seen.

It's possible to compile a minimal libvips with support for only the formats you need, then compile sharp against this. However if you're dependent on a third party such as Vercel then there will be a lot of complexity surrounding this as you do not control the runtime.

https://sharp.pixelplumbing.com/install#custom-libvips

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
