### ISSUE TITLE
Allow for installing to target OS/CPU _without_ autodetecting current architecture

### ISSUE THREAD

**Issue by jsdalton** [lovell/sharp#3905]
### What are you trying to achieve?

This somewhat relates to the issue described here https://github.com/lovell/sharp/issues/3904. We are building sharp to deploy in an AWS lambda environment with some limitations around the size of the deployment artifact.

Installing sharp per the AWS lambda docs works fine with the new prebuilt installations. The problem is that it _also_ appears to autodetect the architecture where the install command is being run and install that. So e.g. installing on Mac OS but targeting linux x64 will get the VIPS for both linux and darwin. So then we end up with a huge artifact which messes with our deployment limits.

For now this is okay, we can manually remove the extra darwin files from `@img` for local development. In CI it's not an issue since we build on a linux architecture, so the files are the same as our target (ie AWS Lambda)

In brief, ideally there would be a way to suppress the check for the current archiecture and simply build to exactly the platform I specify.  So `npm install --cpu=x64 --os=linux sharp` build to linux 64 only and includes only those binaries, regardless of where I run it.

NOTE: we're on npm 9 so I my installation command looks like:

```
npm i @img/sharp-linux-x64 @img/sharp-libvips-linux-x64 sharp -f
```

I'm not sure if using that new platform targeting syntax for npm v10 would change things, but just wanted to be clear about what we're using.

### When you searched for similar feature requests, what did you find that might be related?

Checked PRs, issues and docs.

### What would you expect the API to look like?

In all honestly I'd expect the default behavior to not install extra files when I specify an architecture.

**Comment by lovell** [comment]
Did you see https://sharp.pixelplumbing.com/install#cross-platform ?

**Comment by jsdalton** [comment]
Thanks @lovell . I did see this and this is what I was following.

To be clear this _works_ in that it successfully installs the binary for the architecture I select.

But it _also_ installs the binary for the architecture of the machine I'm running the install on, and there seems to be no way to suppress this. We have to manually clean up node_modules/@img to remove the unneeded binaries.

**Comment by lovell** [comment]
Thanks, I think I need to update the AWS Lambda section to simply point mostly to the cross-platform section as I've realised directly installing the `@img/*` scoped packages is probably a bad long-term idea e.g. versions may not be pinned.

As you've seen, from sharp v0.33.x onwards, your choice of package manager and its features/bugs is now even more important. From what I can tell of the state of npm, I am currently recommending people use pnpm or yarn v3+ if they know that an installation tree and/or lockfile must support multiple platforms.

**Comment by lovell** [comment]
Updated via commit https://github.com/lovell/sharp/commit/cd5cf7ce2d7294faeacd0f9536e874bbea950ee7

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

For anyone else coming here, please see https://sharp.pixelplumbing.com/install#cross-platform for more information specific to your choice of package manager.
