### ISSUE TITLE
sharp doesn't work into a deno compiled self-contained executable

### ISSUE THREAD

**Issue by GiuseppeScottoLavina** [lovell/sharp#3912]
Hi @lovell, sorry for commenting on the wrong issue.

```js
import sharp from "npm:sharp@next";

const image = await sharp('https://cdn.jsdelivr.net/gh/lovell/sharp@main/docs/image/sharp-logo.svg');

console.log(image);
```

`deno run -A index.mjs` works great

```bash
deno compile --allow-ffi --allow-read --output compiled index.mjs
./compiled
```

doesn't work

**Comment by lovell** [comment]
This is a limitation of `deno compile`, which only bundles JavaScript/TypeScript files, and is probably unsuitable for native modules. Perhaps ask this question on the Deno repo.

**Comment by GiuseppeScottoLavina** [comment]
Ok @lovell thank you for your quick answer.

**Comment by lovell** [comment]
I had an afterthought... it looks like `deno compile` does include `.wasm` files, so you can use the [experimental WebAssembly](https://sharp.pixelplumbing.com/install#webassembly) package:
```
  "dependencies": {
    "sharp": "0.33.1",
    "@img/sharp-wasm32": "0.33.1"
  }
```
I've tested this locally and it works.

**Comment by GiuseppeScottoLavina** [comment]
Thank you so much for your help @lovell! :)

Now, the example I posted works perfectly, but I encounter an error when I try to use the "toBuffer" method.

```js
import sharp from "sharp";

const image = await sharp('https://cdn.jsdelivr.net/gh/lovell/sharp@main/docs/image/sharp-logo.svg');

const buff = await image.toBuffer();

console.log(buff);
```

```
error: Uncaught (in promise) TypeError: this.refHandle.ref is not a function
            this.refHandle.ref();
```

**Comment by lovell** [comment]
sharp does not provide any networking so you'll need to add your own code to download a remote image before providing it as input.

**Comment by GiuseppeScottoLavina** [comment]
Unfortunately, I have the same error even with a local file :(

**Comment by GiuseppeScottoLavina** [comment]
I managed to make the non-wasm native version work with a workaround:

I added the string

"@img+sharp-darwin-arm64@0.33"

to the paths array in sharp.js, and I included the node_modules folder in the build using the command

deno compile --include ./node_modules/** --allow-ffi --allow-read --output compiled index.mjs

I hope this can be helpful to someone

**Comment by GiuseppeScottoLavina** [comment]
Hi @lovell,
for now, I have solved it by importing the native version of Sharp (not wasm) and inserting this horrible workaround in the sharp.js file, right after the initialization of the "paths" constant:

```js
const { resolve } = require('node:path');
const { readdirSync, statSync, writeFileSync, readFileSync, mkdirSync } = require('node:fs');

const sharpDir = `/tmp/sharp-${ runtimePlatform }/lib`;
const sharpFile = `${ sharpDir }/sharp-${ runtimePlatform }.node`;
const libvipsDir = `/tmp/sharp-libvips-${ runtimePlatform }/lib`;
const libvipsFile = `${ libvipsDir }/libvips-cpp.42.dylib`;
const bundleDir = resolve(`${ __dirname }/../../../../../.deno/@img+sharp-${ runtimePlatform }@0.33.1/node_modules/@img`);
const bundleSharpFile = `${ bundleDir }/sharp-${ runtimePlatform }/lib/sharp-${ runtimePlatform }.node`;
const bundleLibvipsFile = `${ bundleDir }/sharp-libvips-${ runtimePlatform }/lib/libvips-cpp.42.dylib`;

mkdirSync(sharpDir, { recursive: true });
writeFileSync(sharpFile, readFileSync(bundleSharpFile));
mkdirSync(libvipsDir, { recursive: true });
writeFileSync(libvipsFile, readFileSync(bundleLibvipsFile));

paths.push(sharpFile);
```

I simply extract the .node module and the libvips library from the bundle, copying them to the /tmp folder with the required directory structure

**Comment by lovell** [comment]
Thanks for the update and yes, that does look quite horrible. All those hard-coded version numbers in paths are going to be tricky to maintain.

I would say to anyone else coming here in the future that the WebAssembly route I mentioned in https://github.com/lovell/sharp/issues/3912#issuecomment-1866214392 would be preferable if possible.

**Comment by GiuseppeScottoLavina** [comment]
Hi @lovell ,
I completely agree with you on everything.
What I reported is only a temporary workaround while waiting for a real solution to the problem.

**Comment by some-user123** [comment]
I tried to make this work with a minimal example:

```jsonc
// package.json
{
  "name": "sharp-deno",
  "private": true,
  "dependencies": {
    "sharp": "0.33.1",
    "@img/sharp-wasm32": "0.33.1"
  }
}
```

```ts
// sharp.ts
import sharp from "sharp";
const image = sharp(Deno.args[0]);
console.log(await image.metadata());
```

`deno run -A --allow-ffi sharp.ts foo.jpg` works.
`deno compile -A --allow-ffi sharp.ts` and then `sharp.exe foo.jpg` doesn't :-(

Output:
```
error: Uncaught (in promise) Error: Could not load the "sharp" module using the win32-x64 runtime
undefined: LoadLibraryExW failed
undefined: Cannot convert null to a BigInt
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
    yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=win32 --cpu=x64 sharp
    npm install --force @img/sharp-win32-x64
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
  throw new Error(help.join('\n'));
        ^
    at Object.<anonymous> (file:///C:/Users/.../AppData/Local/Temp/deno-compile-sharp.exe/node_modules/.deno/sharp@0.33.1/node_modules/sharp/lib/sharp.js:107:9)
    at Object.<anonymous> (file:///C:/Users/.../AppData/Local/Temp/deno-compile-sharp.exe/node_modules/.deno/sharp@0.33.1/node_modules/sharp/lib/sharp.js:110:4)
    at Module._compile (node:module:731:34)
    at Object.Module._extensions..js (node:module:745:10)
    at Module.load (node:module:656:32)
    at Function.Module._load (node:module:537:12)
    at Module.require (node:module:675:19)
    at require (node:module:789:16)
    at Object.<anonymous> (file:///C:/Users/.../AppData/Local/Temp/deno-compile-sharp.exe/node_modules/.deno/sharp@0.33.1/node_modules/sharp/lib/constructor.js:10:1)
    at Object.<anonymous> (file:///C:/Users/.../AppData/Local/Temp/deno-compile-sharp.exe/node_modules/.deno/sharp@0.33.1/node_modules/sharp/lib/constructor.js:446:4)
```

Can someone share a working example? I guess I'm missing something trivial...

**Comment by blowsie** [comment]
I can confirm sharp is working fine in deno2 :)

**Comment by magnussp** [comment]
A compiled deno binary, `deno compile --allow-ffi --allow-read`, produce the `TypeError: this.refHandle.ref is not a function` error. I have tried with using the `@img/sharp-wasm32` package and running Deno 2.0.4 and 2.0.6 and get the same issue.
If anyone has a workaround I'm all ears👂
@blowsie did you get it working with Deno2 when using `deno compile`?

**Comment by some-user123** [comment]
> I can confirm sharp is working fine in deno2 :)

That's good to hear :)

Could you please provide an example?

With https://github.com/lovell/sharp/issues/3912#issuecomment-1921364376 I still receive errors:
```
error: Uncaught (in promise) Error: Could not load the "sharp" module using the win32-x64 runtime
ENOENT: LoadLibraryExW failed: The specified module could not be found. (os error 126)
undefined: Cannot convert null to a BigInt
Possible solutions:
...
```

**Comment by timootten** [comment]
Hey, I am trying to use sharp too in a single compiled executable.
But unfortunatly nothing seems to work, are there any updates?

**Comment by blowsie** [comment]
I did not try to compile, sorry if my previous message was misleading. 😕

**Comment by londonbit** [comment]
![image](https://github.com/user-attachments/assets/0593294e-4c75-4fb5-b39a-7f7e16ebffac)
Screen from denodeploy
I think here still some error with Deno 2 
```
$ deno --version
deno 2.1.5 (stable, release, x86_64-pc-windows-msvc)
v8 13.0.245.12-rusty
typescript 5.6.2

```

**Comment by gvkhna** [comment]
> Thank you so much for your help [@lovell](https://github.com/lovell)! :)
> 
> Now, the example I posted works perfectly, but I encounter an error when I try to use the "toBuffer" method.
> 
> import sharp from "sharp";
> 
> const image = await sharp('https://cdn.jsdelivr.net/gh/lovell/sharp@main/docs/image/sharp-logo.svg');
> 
> const buff = await image.toBuffer();
> 
> console.log(buff);
> ```
> error: Uncaught (in promise) TypeError: this.refHandle.ref is not a function
>             this.refHandle.ref();
> ```

I actually encountered this and the issue is emnapi/runtime. I think a polyfill will be needed for the time being.

https://github.com/toyobayashi/emnapi/pull/142

**Comment by kleisauke** [comment]
FWIW, according to https://github.com/denoland/deno/issues/32198, this should no longer be an issue.
