### ISSUE TITLE
Generated animated webp image has transparent artifacts on Safari (iOS)

### ISSUE THREAD

**Issue by thefjhca** [lovell/sharp#3913]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

  System:
    OS: Linux 6.6 Artix Linux
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 8.01 GB / 125.69 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 21.4.0 - /usr/bin/node
    Yarn: 1.22.21 - /usr/bin/yarn
    npm: 10.2.5 - /usr/bin/npm
    pnpm: 8.12.1 - /usr/bin/pnpm

### What are the steps to reproduce?

1. Convert any animated image (gif/webp) to webp using sharp
2. Open webpage in Safari on iOS with served file

### What is the expected behaviour?

No artifacts on background 

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

    const buffer = await sharp("sticker.gif", {
        animated: true,
    }).webp().toBuffer();

### Please provide sample image(s) that help explain this problem
Original gif:
[sticker.zip](https://github.com/lovell/sharp/files/13743935/sticker.zip)

Frame with artifact
![image](https://github.com/lovell/sharp/assets/126906125/092886f3-ca75-4a64-85b5-205aaa065f50)
Next frame
![image](https://github.com/lovell/sharp/assets/126906125/ac413fd0-590a-40e5-a754-4a38daa168d6)

This is reproducible with many WebPs with animation:
![image](https://github.com/lovell/sharp/assets/126906125/f495e211-2b43-461a-8576-d6d5678033b7)
Webp for this image:
[bug.zip](https://github.com/lovell/sharp/files/13744027/bug.zip)

Sometimes there's a part missing, sometimes there's a part left over from the last frame
Output file renders correctly in all other browsers, but not Safari on iOS, so maybe it is their bug (but reproducible from iOS 14 to latest 17)
But if there is any workaround so that this can be fixed without waiting for a fix from Apple, I'd love to hear it

**Comment by lovell** [comment]
> Output file renders correctly in all other browsers, but not Safari on iOS, so maybe it is their bug

This is probably https://bugs.webkit.org/show_bug.cgi?id=217897 - you'll need to ask Apple.
