### ISSUE TITLE
Using affine to downscaling produces pixelated results

### ISSUE THREAD

**Issue by ollm** [lovell/sharp#3917]
## Possible bug

I am trying to resize images using `affine` instead of `resize`, in order to have access to different interpolation methods, such as `nohalo`, `bicubic`, etc. but the results look very pixelated.

### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

``` bash
  System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics
    Memory: 22.34 GB / 31.18 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.17.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.6.7 - /usr/bin/npm
    pnpm: 8.5.1 - /usr/bin/pnpm
```

#### Using `affine`

``` js
(async function(){

	const sharp = require('sharp');

	const image = sharp('sample.png');
	const meta = await image.metadata();

	image
		.affine([49 / meta.width, 0, 0, 49 / meta.height], {interpolator: 'bicubic'})
		.png({compressionLevel: 9, force: true})
		.toFile('affine-bicubic-49.png')
	
})();
```

Image result

![affine-bicubic-49](https://github.com/lovell/sharp/assets/18549191/99fd260e-0ab8-4db8-8fc6-f359fab99d8f)
![fox-affine-bicubic-49](https://github.com/lovell/sharp/assets/18549191/268e1663-1698-45c4-a2f4-09e148954d64)

#### Using `resize`

``` js
(async function(){

	const sharp = require('sharp');

	const image = sharp('sample.png');
	const meta = await image.metadata();

	image
		.resize({width: 49, kernel: 'cubic'})
		.png({compressionLevel: 9, force: true})
		.toFile('resize-cubic-49.png')
	
})();
```

Image result

![resize-cubic-49](https://github.com/lovell/sharp/assets/18549191/6089c459-5573-4535-9b09-0a1efbad751a)
![fox-resize-cubic](https://github.com/lovell/sharp/assets/18549191/d727e799-dded-4983-af7d-e6dbb533c4a7)

### What is the expected behaviour?

Downscaling with `affine` should give similar results to `resize`

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

``` js
(async function(){

	const sharp = require('sharp');

	const image = sharp('sample.png');
	const meta = await image.metadata();

	image
		.affine([49 / meta.width, 0, 0, 49 / meta.height], {interpolator: 'bicubic'})
		.png({compressionLevel: 9, force: true})
		.toFile('affine-bicubic-49.png')
	
})();
```

### Please provide sample image(s) that help explain this problem

![sample](https://github.com/lovell/sharp/assets/18549191/ae567a96-d9b6-4dff-b416-927debf3738b) ![sample-red](https://github.com/lovell/sharp/assets/18549191/1d6d90d8-6aac-47a8-a644-75e438543883)
![fox](https://github.com/lovell/sharp/assets/18549191/40dd5eb9-78f6-4510-a396-40813a7be4ce)

**Comment by lovell** [comment]
I think the current behaviour is expected. Bicubic interpolation tends to over-sharpen and can introduce ringing artefacts, which is what we're seeing here. Have you tried bilinear, which I think would be more appropriate for these images?

**Comment by ollm** [comment]
Thanks for the reply.

Yes, I have also tried `bilinear` and the others interpolators and they have similar results (sharp `v0.33.1` and `v0.26.3`)

I have also tried an old version of sharp (`v0.13.0`), when `interpolateWith` was used together with `resize`, the results are more expected, but I don't know if this is relevant to the issue.

## Sharp `v0.33.1`   using `affine`  with `interpolator`

##### bicubic

![sharp-33 1-bicubic](https://github.com/lovell/sharp/assets/18549191/0018c83e-dda6-4fca-90e5-4b4928cf777f) ![sharp-33 1-bicubic-red](https://github.com/lovell/sharp/assets/18549191/8b91c16a-3067-4ed8-bb25-0c35b0376d73)  ![sharp-33 1-bicubic-fox](https://github.com/lovell/sharp/assets/18549191/4c7950fe-97d1-4386-b37a-7b88fbf37696)

##### bilinear

![sharp-33 1-bilinear](https://github.com/lovell/sharp/assets/18549191/69717c83-272e-479c-8e4f-ec4f6d6a0025)  ![sharp-33 1-bilinear-red](https://github.com/lovell/sharp/assets/18549191/aa0b6cd5-64ac-498e-8bd6-058908cca69c) ![sharp-33 1-bilinear-fox](https://github.com/lovell/sharp/assets/18549191/aafa1f66-691e-4662-9b07-9540894a26e1)

##### lbb

![sharp-33 1-lbb](https://github.com/lovell/sharp/assets/18549191/2aeb20a2-7f84-4ebd-9799-6fef658a1dea)  ![sharp-33 1-lbb-red](https://github.com/lovell/sharp/assets/18549191/7702f40e-4d51-4272-8d8f-2cb727accf3b) ![sharp-33 1-lbb-fox](https://github.com/lovell/sharp/assets/18549191/0bf02c3a-9a81-4b2d-b939-9f884d5b1e54)

##### nearest

![sharp-33 1-nearest](https://github.com/lovell/sharp/assets/18549191/3fc35873-1a61-49a7-8101-537be4dd76f7) ![sharp-33 1-nearest-red](https://github.com/lovell/sharp/assets/18549191/278affcd-1a33-4ea1-bd61-554e84c9cdd6) ![sharp-33 1-nearest-fox](https://github.com/lovell/sharp/assets/18549191/c48d062e-ae32-475f-a4c4-b47a0734452b)

##### nohalo

![sharp-33 1-nohalo](https://github.com/lovell/sharp/assets/18549191/2495f6ef-cf42-4c1b-a69b-59d6eb82b1a8) ![sharp-33 1-nohalo-red](https://github.com/lovell/sharp/assets/18549191/d0ca801e-748d-460e-9318-b5dec6840a24) ![sharp-33 1-nohalo-fox](https://github.com/lovell/sharp/assets/18549191/c1aefae0-38d3-4d8b-bc82-ee47242a3420)


##### vsqbs

![sharp-33 1-vsqbs](https://github.com/lovell/sharp/assets/18549191/c1253e21-46d6-4719-a642-fb5a125ba986) ![sharp-33 1-vsqbs-red](https://github.com/lovell/sharp/assets/18549191/56c13f5e-b514-4a31-8839-a886ccd36e4b) ![sharp-33 1-vsqbs-fox](https://github.com/lovell/sharp/assets/18549191/8b04f004-cb6d-4c81-ae74-56ce4ccc268b)

## Sharp `v0.13.0`  using `resize`  with `interpolateWith`

##### bicubic

![sharp-13 0-bicubic](https://github.com/lovell/sharp/assets/18549191/4131ca6a-785d-4a58-9576-58ff3b99aa68) ![sharp-13 0-bicubic-red](https://github.com/lovell/sharp/assets/18549191/4d787e0e-788f-48ea-9c78-7f3a07830a56) ![sharp-13 0-bicubic-fox](https://github.com/lovell/sharp/assets/18549191/729f17fe-1744-4919-8e61-14d7615571a4)

##### bilinear
![sharp-13 0-bilinear](https://github.com/lovell/sharp/assets/18549191/1736ae5d-5dfe-4d4f-99bd-e92fe0b6d9cf) ![sharp-13 0-bilinear-red](https://github.com/lovell/sharp/assets/18549191/3c54f62c-6ffa-4fe0-86d7-8a4f36eb5ed1) ![sharp-13 0-bilinear-fox](https://github.com/lovell/sharp/assets/18549191/165349b1-08a0-4983-9ef1-978bd01bc75b)

##### lbb
![sharp-13 0-lbb](https://github.com/lovell/sharp/assets/18549191/e8d892e4-f768-42f3-88ab-b48c6659a269) ![sharp-13 0-lbb-red](https://github.com/lovell/sharp/assets/18549191/2f825239-1546-4b51-a828-2b0774ead29f) ![sharp-13 0-lbb-fox](https://github.com/lovell/sharp/assets/18549191/48f4504a-4935-4216-8dea-cda3bffd02e7)

##### nearest
![sharp-13 0-nearest](https://github.com/lovell/sharp/assets/18549191/33932838-db48-47b2-bf07-a6323fcb377f) ![sharp-13 0-nearest-red](https://github.com/lovell/sharp/assets/18549191/a4592d7c-24b9-46aa-b215-1661ec547961) ![sharp-13 0-nearest-fox](https://github.com/lovell/sharp/assets/18549191/6cb3c5e0-2b91-4797-9de9-342c1182b088)

##### nohalo

![sharp-13 0-nohalo](https://github.com/lovell/sharp/assets/18549191/faab7d7e-68ee-4ea7-8ca9-2eeee74ba195) ![sharp-13 0-nohalo-red](https://github.com/lovell/sharp/assets/18549191/324e06f6-0505-44a5-bfb0-37c9bb6122c7) ![sharp-13 0-nohalo-fox](https://github.com/lovell/sharp/assets/18549191/1899198c-4429-4420-9d77-53f0af17fe53)

##### vsqbs

![sharp-13 0-vsqbs](https://github.com/lovell/sharp/assets/18549191/e37a8e3d-9d29-407e-b563-b2d5f4b8b2e1) ![sharp-13 0-vsqbs-red](https://github.com/lovell/sharp/assets/18549191/148917fa-6265-4ad4-b1bf-a270694f1678) ![sharp-13 0-vsqbs-fox](https://github.com/lovell/sharp/assets/18549191/4604935c-d8eb-4d52-b0b3-ecb585e01bbc)

**Comment by lovell** [comment]
It's been a while since sharp v0.13.0 but IIRC, the interpolator provided via `interpolateWith` was used for the final stage of the image reduction. In the provided examples, scaling from 100 to 49 pixels would use a box shrink from 100 to 50 then affine from 50 to 49.

The modern day `affine` operation uses the interpolator for everything, so this means we're not really able to compare their output.

What we can do is to remove sharp from the equation and use `vips` at the command line.

I see the same results as sharp when e.g. running the following:
```sh
$ vips affine in.png out-bicubic.png "0.49 0 0 0.49" --interpolate=bicubic
$ vips affine in.png out-nohalo.png "0.49 0 0 0.49" --interpolate=nohalo
```
Are you able to experiment with `vips`?
