### ISSUE TITLE
Stream metadata and resize

### ISSUE THREAD

**Issue by shmueldarchi** [lovell/sharp#3918]
Hello,

I'm currently working with Sharp version 0.32.4 to obtain image sizes and subsequently resize them to 50% of their original dimensions using the resize function.

Here's a snippet of my code:

```
const transformer = sharp();
thumbnail.pipe(transformer);
const { width, height } = await transformer.metadata();
logger.info("Original width and height:", width, height);
const newWidth = width / 2;
const newHeight = height / 2;
const chain1 = transformer.resize(newWidth, newHeight)
                          .toFormat(config.imageThumbnail.format);
receivedFile.push({
  id,
  type: "thumbnail",
  name: thumbName,
  stream: chain1
});
```
This code performs well with very smallimages (around 20 KB), but I encounter issues when processing larger images. 
Specifically, the process seems to hang at the metadata function call, as indicated by the absence of the log print statement that follows it.

Could someone guide me on how to correctly handle images resize base on image metadata or suggest any adjustments to my current approach?
Thank you!

**Comment by lovell** [comment]
Perhaps try transforming via https://www.npmjs.com/package/peek-readable so you can "peek" at the first N bytes and check it for metadata e.g. https://github.com/lovell/sharp/issues/2225#issuecomment-847248142

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
