### ISSUE TITLE
unexpected operator in preinstall.sh

### ISSUE THREAD

**Issue by binarykitchen** [lovell/sharp#392]
```
./node_modules/sharp/preinstall.sh: 130: [: x86_64: unexpected operator
```

**Comment by lovell** [comment]
Hello, the preinstall script is no longer required on most 64-bit systems when using sharp v0.12.0+.

Is this Linux? Which flavour/version?

**Comment by binarykitchen** [comment]
Ubuntu 14.10 here

On 03/04/16 19:56, Lovell Fuller wrote:
>
> Hello, the preinstall script is no longer required on most 64-bit
> systems when using sharp v0.12.0+.
>
> Is this Linux? Which flavour/version?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lovell/sharp/issues/392#issuecomment-204905230>
>

-- 

Binary Kitchen
Michael Heuberger
1/33 Parrish Road
Sandringham
Auckland 1025
(New Zealand)

Mobile (text only) ...  +64 21 261 89 81
Email ................  michael@binarykitchen.com
Website ..............  http://www.binarykitchen.com

**Comment by lovell** [comment]
Thanks, assuming you're using sharp v0.12.0 or later, you won't need to run the preinstall script. We should probably stop publishing it to npm.

**Comment by binarykitchen** [comment]
yep using latest sharp here. but beware that i install it with the `--ignore-scripts` option, check in all node modules except the binaries into my private repo and call `npm rebuild` upon deployment.

**Comment by lovell** [comment]
sharp does not run `preinstall.sh` at install or rebuild time (and has never done so due to the sudo/root privilege requirement). Could something else be attempt to run it on your system/app?

**Comment by binarykitchen** [comment]
i see ... and suddenly i cannot reproduce the above anymore. very weird. feel free to close this ticket then.

but i had to run that bash script manually because my libvips version was outdated before (was v7) and sharp didn't complain!
