### ISSUE TITLE
Cannot find module '../build/Release/sharp-win32-x64.node'

### ISSUE THREAD

**Issue by agustinnunezz99** [lovell/sharp#3921]
Error (1): Failed to start the server. Review the error details for more information.
 -> C:\Users\ANUNEZ\AppData\Local\sf\node_modules\sharp\lib\sharp.js:34
  throw new Error(help.join('\n'));
  ^

Error:
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-win32-x64.node'
Require stack:
- C:\Users\ANUNEZ\AppData\Local\sf\node_modules\sharp\lib\sharp.js
- C:\Users\ANUNEZ\AppData\Local\sf\node_modules\sharp\lib\constructor.js
- C:\Users\ANUNEZ\AppData\Local\sf\node_modules\sharp\lib\index.js
- C:\Users\ANUNEZ\AppData\Local\sf\node_modules\@ind-rcg\backend\src\sfAttachmentsHandler.js
- C:\Users\ANUNEZ\AppData\Local\sf\node_modules\@ind-rcg\backend\src\local.js
- C:\Users\ANUNEZ\AppData\Local\sf\node_modules\@ind-rcg\backend\src\bootstrap.js
- C:\Users\ANUNEZ\AppData\Local\sf\node_modules\@ind-rcg\backend\src\server.js

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current win32-x64 runtime: "npm install --platform=win32 --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (C:\Users\ANUNEZ\AppData\Local\sf\node_modules\sharp\lib\sharp.js:34:9)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\ANUNEZ\AppData\Local\sf\node_modules\sharp\lib\constructor.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)

Node.js v18.18.2

i saw that in https://github.com/lovell/sharp/issues/3086#issuecomment-1049760793 talk about the dependencies, that it seems that i dont have it in the program but i have it already installed in my pc.
 For example: 
<img width="453" alt="image" src="https://github.com/lovell/sharp/assets/155084409/a3f7163d-675a-4c6e-b4b2-f34ec5a2e341">

<img width="429" alt="image" src="https://github.com/lovell/sharp/assets/155084409/c0082a9e-ed69-4ced-930f-b3a3d14fa0db">

-----
$ npm ls sharp
testeo@ C:\Users\ANUNEZ\Desktop\testeo
└── sharp@0.32.6

-----

$ node --version
v18.18.2

-----
$ npm --version
9.8.1

-----
$ npm ls -g sharp
C:\Program Files\nodejs -> .\
└── sharp@0.32.6

i already did npm rebuild, delete node_modules and installed again and nothing solve this issue. Any help please?

**Comment by lovell** [comment]
Please upgrade to the latest version of sharp, currently v0.33.1.

**Comment by agustinnunezz99** [comment]
Already upgrade and deleted the globally-installed sharp and i have the same error. 

$ npm ls -g sharp
C:\Program Files\nodejs -> .\
└── (empty)

Also i already upgrade node version from 18.18.2 to 19.3 and others and nothing happend

**Comment by lovell** [comment]
As this issue relates to installation, please can you open a new [installation issue](https://github.com/lovell/sharp/issues/new?assignees=&labels=installation&projects=&template=installation.md) and answer all of the questions.

**Comment by agustinnunezz99** [comment]
Sure. https://github.com/lovell/sharp/issues/3922
