### ISSUE TITLE
Cannot find module '../build/Release/sharp-win32-x64.node'

### ISSUE THREAD

**Issue by agustinnunezz99** [lovell/sharp#3922]
## Possible install-time or require-time problem

- [x] I have read and understood all of the [documentation relating to installation](https://sharp.pixelplumbing.com/install). 
- [x] I have searched for known bugs relating to this problem in my choice of package manager. 

You must confirm both of these before continuing.

### Are you using the latest version of sharp? 

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest,
please open an issue against that package instead.

### Are you using a supported runtime?

- [x] I am using Node.js with a version that satisfies `^18.17.0 || ^20.3.0 || >=21.0.0` 
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these,
please upgrade to the latest version
and try again before opening an issue.

### Are you using a supported package manager and installing optional dependencies?

- [x] I am using npm >= 9.6.5 with `--include=optional`
- [ ] I am using yarn >= 3.2.0
- [ ] I am using pnpm >= 7.1.0 with `--no-optional=false`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these, please upgrade to the latest version of your chosen package manager
and ensure you are allowing the installation of optional or multi-platform dependencies before opening an issue.

### What is the complete error message, including the full stack trace?

$ sf mdl simulate
Warning: IMPORTANT: The SQLite database and attachments that are created during the testing of the offline application may contain sensitive data from the Salesforce org that is synced with your device. Be aware that this data is not encrypted locally. We strongly recommend that for testing purposes, use only test data in a Salesforce org.
C:\Users\ANUNEZ\AppData\Local\sf\node_modules\sharp\lib\sharp.js:34
  throw new Error(help.join('\n'));
  ^

Error:
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-win32-x64.node'
Require stack:
- C:\Users\ANUNEZ\AppData\Local\sf\node_modules\sharp\lib\sharp.js
- C:\Users\ANUNEZ\AppData\Local\sf\node_modules\sharp\lib\constructor.js
- C:\Users\ANUNEZ\AppData\Local\sf\node_modules\sharp\lib\index.js
- C:\Users\ANUNEZ\AppData\Local\sf\node_modules\@ind-rcg\backend\src\sfAttachmentsHandler.js
- C:\Users\ANUNEZ\AppData\Local\sf\node_modules\@ind-rcg\backend\src\local.js
- C:\Users\ANUNEZ\AppData\Local\sf\node_modules\@ind-rcg\backend\src\bootstrap.js
- C:\Users\ANUNEZ\AppData\Local\sf\node_modules\@ind-rcg\backend\src\server.js

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current win32-x64 runtime: "npm install --platform=win32 --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (C:\Users\ANUNEZ\AppData\Local\sf\node_modules\sharp\lib\sharp.js:34:9)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\ANUNEZ\AppData\Local\sf\node_modules\sharp\lib\constructor.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)

Node.js v18.17.0
Error (1): Failed to start the server. Review the error details for more information.
 -> C:\Users\ANUNEZ\AppData\Local\sf\node_modules\sharp\lib\sharp.js:34
  throw new Error(help.join('\n'));
  ^

Error:
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-win32-x64.node'
Require stack:
- C:\Users\ANUNEZ\AppData\Local\sf\node_modules\sharp\lib\sharp.js
- C:\Users\ANUNEZ\AppData\Local\sf\node_modules\sharp\lib\constructor.js
- C:\Users\ANUNEZ\AppData\Local\sf\node_modules\sharp\lib\index.js
- C:\Users\ANUNEZ\AppData\Local\sf\node_modules\@ind-rcg\backend\src\sfAttachmentsHandler.js
- C:\Users\ANUNEZ\AppData\Local\sf\node_modules\@ind-rcg\backend\src\local.js
- C:\Users\ANUNEZ\AppData\Local\sf\node_modules\@ind-rcg\backend\src\bootstrap.js
- C:\Users\ANUNEZ\AppData\Local\sf\node_modules\@ind-rcg\backend\src\server.js

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current win32-x64 runtime: "npm install --platform=win32 --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (C:\Users\ANUNEZ\AppData\Local\sf\node_modules\sharp\lib\sharp.js:34:9)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\ANUNEZ\AppData\Local\sf\node_modules\sharp\lib\constructor.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)

Node.js v18.17.0 

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<$ npm install --verbose --foreground-scripts sharp
npm verb cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
npm info using npm@9.6.7
npm info using node@v18.17.0
npm verb title npm install sharp
npm verb argv "install" "--loglevel" "verbose" "--foreground-scripts" "sharp"
npm verb logfile logs-max:10 dir:C:\Users\ANUNEZ\AppData\Local\npm-cache\_logs\2023-12-28T15_42_01_379Z-
npm verb logfile C:\Users\ANUNEZ\AppData\Local\npm-cache\_logs\2023-12-28T15_42_01_379Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/sharp 134ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-darwin-arm64 97ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linuxmusl-x64 136ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linuxmusl-x64 158ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-s390x 162ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-darwin-x64 168ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-x64 175ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-darwin-arm64 181ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/semver 201ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-win32-x64 198ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color 211ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-win32-ia32 208ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-arm64 218ms (cache revalidated)   
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linuxmusl-arm64 224ms (cache revalidated)       
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-wasm32 1780ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-arm64 1795ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-arm 1896ms (cache revalidated)    
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-darwin-x64 2236ms (cache revalidated)   
npm http fetch GET 200 https://registry.npmjs.org/@emnapi%2fruntime 68ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/lru-cache 65ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-convert 72ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-string 75ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/tslib 38ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle 44ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-name 59ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-name 60ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 41ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/yallist 51ms (cache revalidated)
npm verb reify failed optional dependency C:\Users\ANUNEZ\Desktop\npmsharp\node_modules\@img\sharp-win32-ia32
npm verb reify failed optional dependency C:\Users\ANUNEZ\Desktop\npmsharp\node_modules\@img\sharp-wasm32      
npm verb reify failed optional dependency C:\Users\ANUNEZ\Desktop\npmsharp\node_modules\@emnapi\runtime        
npm verb reify failed optional dependency C:\Users\ANUNEZ\Desktop\npmsharp\node_modules\tslib
npm verb reify failed optional dependency C:\Users\ANUNEZ\Desktop\npmsharp\node_modules\@img\sharp-linuxmusl-x64
npm verb reify failed optional dependency C:\Users\ANUNEZ\Desktop\npmsharp\node_modules\@img\sharp-linuxmusl-arm64
npm verb reify failed optional dependency C:\Users\ANUNEZ\Desktop\npmsharp\node_modules\@img\sharp-linux-x64
npm verb reify failed optional dependency C:\Users\ANUNEZ\Desktop\npmsharp\node_modules\@img\sharp-linux-s390x 
npm verb reify failed optional dependency C:\Users\ANUNEZ\Desktop\npmsharp\node_modules\@img\sharp-linux-arm64 
npm verb reify failed optional dependency C:\Users\ANUNEZ\Desktop\npmsharp\node_modules\@img\sharp-linux-arm   
npm verb reify failed optional dependency C:\Users\ANUNEZ\Desktop\npmsharp\node_modules\@img\sharp-libvips-linuxmusl-x64
npm verb reify failed optional dependency C:\Users\ANUNEZ\Desktop\npmsharp\node_modules\@img\sharp-libvips-linuxmusl-arm64
npm verb reify failed optional dependency C:\Users\ANUNEZ\Desktop\npmsharp\node_modules\@img\sharp-libvips-linux-x64
npm verb reify failed optional dependency C:\Users\ANUNEZ\Desktop\npmsharp\node_modules\@img\sharp-libvips-linux-s390x
npm verb reify failed optional dependency C:\Users\ANUNEZ\Desktop\npmsharp\node_modules\@img\sharp-libvips-linux-arm64
npm verb reify failed optional dependency C:\Users\ANUNEZ\Desktop\npmsharp\node_modules\@img\sharp-libvips-linux-arm
npm verb reify failed optional dependency C:\Users\ANUNEZ\Desktop\npmsharp\node_modules\@img\sharp-libvips-darwin-x64
npm verb reify failed optional dependency C:\Users\ANUNEZ\Desktop\npmsharp\node_modules\@img\sharp-libvips-darwin-arm64
npm verb reify failed optional dependency C:\Users\ANUNEZ\Desktop\npmsharp\node_modules\@img\sharp-darwin-x64  
npm verb reify failed optional dependency C:\Users\ANUNEZ\Desktop\npmsharp\node_modules\@img\sharp-darwin-arm64
npm info run sharp@0.33.1 install node_modules/sharp node install/check

> sharp@0.33.1 install
> node install/check

npm info run sharp@0.33.1 install { code: 0, signal: null }

added 12 packages in 4s

2 packages are looking for funding
  run `npm fund` for details
npm verb exit 0
npm info ok>

### Please provide output of `npm install --verbose --foreground-scripts sharp` in an empty directory here. ###

< npm verb exit 0
npm info ok >

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?
  System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 6.52 GB / 15.71 GB
  Binaries:
    Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: ^0.33.1 => 0.33.1

**Comment by lovell** [comment]
Thanks for opening an installation issue, these are useful answers.

The error message you've provided here is not generated by the latest version v0.33.1 of sharp.

Please remove any outdated versions of sharp in files/directories such as `C:\Users\ANUNEZ\AppData\Local\sf\package.json` and `C:\Users\ANUNEZ\AppData\Local\sf\node_modules`.

**Comment by agustinnunezz99** [comment]
Done. 
<img width="248" alt="image" src="https://github.com/lovell/sharp/assets/155084409/e2447130-e577-4b96-9737-950a5c614dbb">

What do i do now?

**Comment by huangzsdy** [comment]
> Thanks for opening an installation issue, these are useful answers.
> 
> The error message you've provided here is not generated by the latest version v0.33.1 of sharp.
> 
> Please remove any outdated versions of sharp in files/directories such as `C:\Users\ANUNEZ\AppData\Local\sf\package.json` and `C:\Users\ANUNEZ\AppData\Local\sf\node_modules`.

Thanks!!! it also works for me
