### ISSUE TITLE
Does sharp fully download the image when retrieving metadata?

### ISSUE THREAD

**Issue by moonkorea00** [lovell/sharp#3925]
Hey team,

When making a request to get metadata(e.g. width and height) of an image(s) using `sharp(url).metadata()`, does sharp fully download the image?

[probe-image-size](https://www.npmjs.com/package/probe-image-size) states it "gets image size without full download". I was wondering if sharp makes a request to fully download the image in the process of retrieving metadata.

Thanks.

**Comment by lovell** [comment]
There is no networking support in sharp. You will need to add your own logic to download or setup a ReadableStream for any remote image data before passing to sharp.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
