### ISSUE TITLE
VIPS not taken into account for .heic files with Bun unless we run "npm install" in node_modules/sharp

### ISSUE THREAD

**Issue by baptistecs** [lovell/sharp#3931]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

  System:
    OS: macOS 11.7.10
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 1.95 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.5 - ~/.nvm/versions/node/v20.10.0/bin/npm
    bun: 1.0.21 - ~/.bun/bin/bun
  npmPackages:
    sharp: ^0.33.1 => 0.33.1 

### What are the steps to reproduce?

```shell
sudo port install vips # vips-8.15.1
curl -fsSL https://bun.sh/install | bash -s "bun-v1.0.21"
```

I added sharp to trustedDependencies in package.json

```
  "trustedDependencies": [
    "sharp"
  ],
```

**This doesn't work:**
```shell
BUN_DISABLE_COMPRESSION_FRAMEWORK=1 bun install sharp --verbose # v1.0.21 needs the ENV variable on old MacOS
```
<details>
BUN_DISABLE_COMPRESSION_FRAMEWORK=1 bun install --verbose sharp
bun add v1.0.21 (837cbd60)
Loaded 35 hoisted_dependencies
Loaded 45 resolutions
Loaded 45 dependencies
Loaded 4 extern_strings
Loaded 2605 string_bytes

 [0.00ms] [cache hit] sharp
   - "sharp": "" - sharp@0.33.1

 [0.00ms] [cache hit] color
   - "color": "^4.2.3" - color@4.2.3

 [0.00ms] [cache hit] detect-libc
   - "detect-libc": "^2.0.2" - detect-libc@2.0.2

 [0.00ms] [cache hit] semver
   - "semver": "^7.5.4" - semver@7.5.4

 [0.00ms] [cache hit] @img/sharp-darwin-arm64
   - "@img/sharp-darwin-arm64": "0.33.1" - @img/sharp-darwin-arm64@0.33.1

 [0.00ms] [cache hit] @img/sharp-darwin-x64
   - "@img/sharp-darwin-x64": "0.33.1" - @img/sharp-darwin-x64@0.33.1

 [0.00ms] [cache hit] @img/sharp-libvips-darwin-arm64
   - "@img/sharp-libvips-darwin-arm64": "1.0.0" - @img/sharp-libvips-darwin-arm64@1.0.0

 [0.00ms] [cache hit] @img/sharp-libvips-darwin-x64
   - "@img/sharp-libvips-darwin-x64": "1.0.0" - @img/sharp-libvips-darwin-x64@1.0.0

 [0.00ms] [cache hit] @img/sharp-libvips-linux-arm
   - "@img/sharp-libvips-linux-arm": "1.0.0" - @img/sharp-libvips-linux-arm@1.0.0

 [0.00ms] [cache hit] @img/sharp-libvips-linux-arm64
   - "@img/sharp-libvips-linux-arm64": "1.0.0" - @img/sharp-libvips-linux-arm64@1.0.0

 [0.00ms] [cache hit] @img/sharp-libvips-linux-s390x
   - "@img/sharp-libvips-linux-s390x": "1.0.0" - @img/sharp-libvips-linux-s390x@1.0.0

 [0.00ms] [cache hit] @img/sharp-libvips-linux-x64
   - "@img/sharp-libvips-linux-x64": "1.0.0" - @img/sharp-libvips-linux-x64@1.0.0

 [0.00ms] [cache hit] @img/sharp-libvips-linuxmusl-arm64
   - "@img/sharp-libvips-linuxmusl-arm64": "1.0.0" - @img/sharp-libvips-linuxmusl-arm64@1.0.0

 [0.00ms] [cache hit] @img/sharp-libvips-linuxmusl-x64
   - "@img/sharp-libvips-linuxmusl-x64": "1.0.0" - @img/sharp-libvips-linuxmusl-x64@1.0.0

 [0.00ms] [cache hit] @img/sharp-linux-arm
   - "@img/sharp-linux-arm": "0.33.1" - @img/sharp-linux-arm@0.33.1

 [0.00ms] [cache hit] @img/sharp-linux-arm64
   - "@img/sharp-linux-arm64": "0.33.1" - @img/sharp-linux-arm64@0.33.1

 [0.00ms] [cache hit] @img/sharp-linux-s390x
   - "@img/sharp-linux-s390x": "0.33.1" - @img/sharp-linux-s390x@0.33.1

 [0.00ms] [cache hit] @img/sharp-linux-x64
   - "@img/sharp-linux-x64": "0.33.1" - @img/sharp-linux-x64@0.33.1

 [0.00ms] [cache hit] @img/sharp-linuxmusl-arm64
   - "@img/sharp-linuxmusl-arm64": "0.33.1" - @img/sharp-linuxmusl-arm64@0.33.1

 [0.00ms] [cache hit] @img/sharp-linuxmusl-x64
   - "@img/sharp-linuxmusl-x64": "0.33.1" - @img/sharp-linuxmusl-x64@0.33.1

 [0.00ms] [cache hit] @img/sharp-wasm32
   - "@img/sharp-wasm32": "0.33.1" - @img/sharp-wasm32@0.33.1

 [0.00ms] [cache hit] @img/sharp-win32-ia32
   - "@img/sharp-win32-ia32": "0.33.1" - @img/sharp-win32-ia32@0.33.1

 [0.00ms] [cache hit] @img/sharp-win32-x64
   - "@img/sharp-win32-x64": "0.33.1" - @img/sharp-win32-x64@0.33.1

 [0.00ms] [cache hit] color-convert
   - "color-convert": "^2.0.1" - color-convert@2.0.1

 [0.00ms] [cache hit] color-string
   - "color-string": "^1.9.0" - color-string@1.9.1

 [0.00ms] [cache hit] lru-cache
   - "lru-cache": "^6.0.0" - lru-cache@6.0.0

 [0.00ms] [cache hit] @img/sharp-libvips-darwin-arm64

 [0.00ms] [cache hit] @img/sharp-libvips-darwin-x64

 [0.00ms] [cache hit] @img/sharp-libvips-linux-arm

 [0.00ms] [cache hit] @img/sharp-libvips-linux-arm64

 [0.00ms] [cache hit] @img/sharp-libvips-linux-s390x

 [0.00ms] [cache hit] @img/sharp-libvips-linux-x64

 [0.00ms] [cache hit] @img/sharp-libvips-linuxmusl-arm64

 [0.00ms] [cache hit] @img/sharp-libvips-linuxmusl-x64

 [0.00ms] [cache hit] @emnapi/runtime
   - "@emnapi/runtime": "^0.44.0" - @emnapi/runtime@0.44.0

 [0.00ms] [cache hit] color-name
   - "color-name": "~1.1.4" - color-name@1.1.4

 [0.00ms] [cache hit] simple-swizzle
   - "simple-swizzle": "^0.2.2" - simple-swizzle@0.2.2

 [0.00ms] [cache hit] yallist
   - "yallist": "^4.0.0" - yallist@4.0.0

 [0.00ms] [cache hit] tslib

 [0.00ms] [cache hit] is-arrayish
   - "is-arrayish": "^0.3.1" - is-arrayish@0.3.2

-- BEGIN SHA512/256(`${alphabetize(name)}@${order(version)}`) --
@emnapi/runtime@0.44.0
@img/sharp-darwin-arm64@0.33.1
@img/sharp-darwin-x64@0.33.1
@img/sharp-libvips-darwin-arm64@1.0.0
@img/sharp-libvips-darwin-x64@1.0.0
@img/sharp-libvips-linux-arm@1.0.0
@img/sharp-libvips-linux-arm64@1.0.0
@img/sharp-libvips-linux-s390x@1.0.0
@img/sharp-libvips-linux-x64@1.0.0
@img/sharp-libvips-linuxmusl-arm64@1.0.0
@img/sharp-libvips-linuxmusl-x64@1.0.0
@img/sharp-linux-arm@0.33.1
@img/sharp-linux-arm64@0.33.1
@img/sharp-linux-s390x@0.33.1
@img/sharp-linux-x64@0.33.1
@img/sharp-linuxmusl-arm64@0.33.1
@img/sharp-linuxmusl-x64@0.33.1
@img/sharp-wasm32@0.33.1
@img/sharp-win32-ia32@0.33.1
@img/sharp-win32-x64@0.33.1
@jridgewell/gen-mapping@0.3.3
@jridgewell/resolve-uri@3.1.1
@jridgewell/set-array@1.1.2
@jridgewell/source-map@0.3.5
@jridgewell/sourcemap-codec@1.4.15
@jridgewell/trace-mapping@0.3.20
@types/html-minifier-terser@7.0.2
@types/node@20.10.6
@types/ws@8.5.10
acorn@8.11.3
buffer-from@1.1.2
bun-types@1.0.21
camel-case@4.1.2
clean-css@5.3.3
color@4.2.3
color-convert@2.0.1
color-name@1.1.4
color-string@1.9.1
commander@2.20.3
commander@9.5.0
commander@10.0.1
detect-libc@2.0.2
dot-case@3.0.4
entities@4.5.0
html-minifier-terser@7.2.0
ip-regex@4.3.0
is-arrayish@0.3.2
lower-case@2.0.2
lru-cache@6.0.0
mkcert@1.5.1
no-case@3.0.4
node-forge@1.3.1
param-case@3.0.4
pascal-case@3.1.2
relateurl@0.2.7
semver@7.5.4
sharp@0.33.1
simple-swizzle@0.2.2
source-map@0.6.1
source-map-support@0.5.21
terser@5.26.0
tslib@2.6.2
typescript@5.3.3
undici-types@5.26.5
undici-types@5.28.2
yallist@4.0.0
-- END HASH--
Saving 4 trees
Saving 66 hoisted_dependencies
Saving 86 resolutions
Saving 86 dependencies
Saving 4 extern_strings
Saving 5533 string_bytes
[LifecycleScriptSubprocess] Starting scripts for "sharp"
[LifecycleScriptSubprocess] Spawning "install" script for package "sharp"
  ⚙️  sharp [1/1] [PackageManager] waiting for 1 scripts

# WELL DETECTED THOUGH:
sharp: Detected globally-installed libvips v8.15.1
sharp: Attempting to build from source via node-gyp
sharp: Please add node-addon-api to your dependencies

 installed sharp@0.33.1

 1 package installed [137.00ms]
</details>
Trying to convert an .heic image gives this:

```shell
Read error: source: bad seek to 3024940
heif: Unsupported feature: Unsupported codec (4.3000)
```

**This works:**
```shell
cd node_modules/sharp
npm install
```

### What is the expected behaviour?

Sharp should use Vips to convert the image

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```node
import sharp, { FormatEnum } from 'sharp';
import { createReadStream, createWriteStream } from 'fs';

const minPath = './test.jpg';
const transformer = sharp({ animated: true })
    .resize({
        width,
        height,
    })
    .toFormat('jpg');

const readStream = createReadStream(path).pipe(transformer);
const writeStream = createWriteStream(minPath);
```
### Please provide sample image(s) that help explain this problem

[sample1.heic.zip](https://github.com/lovell/sharp/files/13839707/sample1.heic.zip)

**Comment by lovell** [comment]
> sharp: Detected globally-installed libvips v8.15.1
> sharp: Attempting to build from source via node-gyp
> sharp: Please add node-addon-api to your dependencies

You'll need to add `node-addon-api` to your dependencies.

https://sharp.pixelplumbing.com/install#building-from-source

**Comment by baptistecs** [comment]
Oops, I missed that message, sorry and thank you!

It would be nice to automatize this step if possible, or to add a note in the documentation for Bum, we don't get any message unless we use --verbose

Installing `node-addon-api` & `node-gyp` worked, many thanks 👍
