### ISSUE TITLE
Unexpected image format?

### ISSUE THREAD

**Issue by poeticninja** [lovell/sharp#394]
I found a gif image and I am unable to use sharp with it.

URL: http://www.thinkactshare.com/wp-content/uploads/2012/07/spongebob1.gif

Is there a reason for this? Is it a bug or a bad image?

(also my compliments on this module. :smile: )

**Comment by lovell** [comment]
Hello, is this on OS X? If so, was the `--with-imagemagick` flag used when installing vips? http://sharp.dimens.io/en/stable/install/#mac-os

**Comment by poeticninja** [comment]
Hi! That flag was not used when installing vips. I some how missed that line. I would think everyone would want GIF support! :smile: 

Thanks!
