### ISSUE TITLE
Write custom tags into EXIF data

### ISSUE THREAD

**Issue by benjaminben** [lovell/sharp#3942]
### What are you trying to achieve?

Is there any capability to write custom tags? For example, stable diffusion software ComfyUI [writes a "prompt" tag into generated images](https://github.com/comfyanonymous/ComfyUI/blob/b4e915e74560bd2c090f9b4ed6b73b0781b7050e/comfy_extras/nodes_images.py#L93C34-L93C34). I was able to extract the data with [exifreader](https://www.npmjs.com/package/exifreader) and write it back into the converted jpg by specifying:
```
...
.withExifMerge({
  IFD0: {
    Software: "comfyui",
    ImageDescription: <previously extracted data>,
  },
})
...
```
This isn't ideal because ComfyUI expects the original tags when extracting a prompt from an image. So I'm wondering if there's a way to preserve the original tags, or rewrite them back into the output?

### When you searched for similar issues, what did you find that might be related?

[#3549](https://github.com/lovell/sharp/issues/3549)
[#3824](https://github.com/lovell/sharp/issues/3824)
[#3676](https://github.com/lovell/sharp/issues/3676)

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

The "prompt" and "workflow" tags don't keep when converting from png to jpg, even when including `keepExif()` or `keepMetadata()`. For example, using the attached image at the bottom of this post:
```
const buffer = await fs.readFile("ComfyUI_temp_ejdxc_00001_.png");
const output = await sharp(buffer)
  .toFormat("jpg")
  .keepExif()
  .keepIccProfile()
  .keepMetadata()
  .toBuffer();
await fs.writeFile("test.jpg", output);
```
The original tags are missing from the output jpg.

### Please provide sample image(s) that help explain this question

You can view an example of the tags I'm referring to by running the following image through e.g [this extractor util](https://exif.tools/).

Here is the original png (with tags):

![ComfyUI_temp_ejdxc_00001_](https://github.com/lovell/sharp/assets/12801745/cb4a9179-33f5-4db9-aab9-f06a4762e929)

Here is the sharp output jpg (missing tags):

![test](https://github.com/lovell/sharp/assets/12801745/c76daf43-7eb8-4ef1-9024-39f4df03a017)

**Comment by lovell** [comment]
These are `tEXt` chunks rather than EXIF, please see the existing future possible enhancement https://github.com/lovell/sharp/issues/3549
