### ISSUE TITLE
Using a custom libvips when upgrading to 0.33.x requires node-addon-api

### ISSUE THREAD

**Issue by Kikobeats** [lovell/sharp#3945]
## Possible bug

Hello,

I noted 0.33.x versions are failing in my CI tests, while the latest one working fine is 0.32.6

![CleanShot 2024-01-13 at 22 26 00@2x](https://github.com/lovell/sharp/assets/2096101/35809d00-403d-4c18-806d-e354da399375)

https://github.com/microlinkhq/splashy/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+0.32.6

Sorry for this vague issue description – I'm not actually reporting nothing specifically, just I thought you wanted to know something introduced in 0.33.x is preventing me (and probably more users) to upgrade.

If I run the test suite locally, (on a M1 laptop) I have the same results.

### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error. 

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

**Comment by lovell** [comment]
> I'm not actually reporting nothing specifically, just I thought you wanted to know something introduced in 0.33.x is preventing me (and probably more users) to upgrade.

It looks like you're using a custom, globally-installed libvips.

Please ensure you've read the documentation about building sharp from source as this has changed from v0.33.0+.

https://sharp.pixelplumbing.com/install#building-from-source

https://sharp.pixelplumbing.com/changelog#v0330---29th-november-2023

> Building from source requires dependency on `node-addon-api`.

**Comment by Kikobeats** [comment]
That's right; This is my the compiled libvips I'm using:
https://github.com/Kikobeats/docker-vips/blob/master/Dockerfile

I'm not seeing nothing related in the changelog 🤔

**Comment by lovell** [comment]
> is there any way to print some debug logs to understand what sharp is missing?

`npm install --verbose --foreground-scripts`

https://sharp.pixelplumbing.com/install#building-from-source

You'll need to add `node-addon-api` (and possibly `node-gyp` depending on your choice of package manager) to your `dependencies` in https://github.com/microlinkhq/splashy/blob/master/package.json

**Comment by Kikobeats** [comment]
It worked flawless <picture data-single-emoji=":chefkiss:" title=":chefkiss:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/chefkiss/93d24183f582e520.png" alt=":chefkiss:" align="absmiddle"></picture> https://github.com/microlinkhq/splashy/pull/60

Thanks @lovell for taking care
