### ISSUE TITLE
sharp.metadata will prevent process from gracefully exiting if performed on non-images

### ISSUE THREAD

**Issue by asilvas** [lovell/sharp#395]
It's at least super easy to repro with latest version of the sharp. It appears a handle is being left open somewhere if this function is invoked on a non-image, and thus when a process naturally would exit, it remains open, preventing its resources (including critical resources such as port bindings) from being released.

No exception is being thrown, the callback with error is being supplied as expected, but something is not being cleaned up, presumably.

A workaround currently is to capture SIG events and forcefully `process.exit`.

**Comment by lovell** [comment]
Hi Aaron, which platforms (Windows/Linux/OS X) are you seeing this behaviour on?

**Comment by asilvas** [comment]
Confirmed OSX

**Comment by lovell** [comment]
Here's a small test case that passes a non-image file (namely the source code file itself) to `metadata`:
```javascript
var sharp = require('sharp');
var assert = require('assert');

sharp(__filename).metadata(function(err, data) {
  assert(!!err);
  assert(!data);
  assert.strictEqual(2, process._getActiveHandles().length);  // stdout and stderr
  assert.strictEqual(0, process._getActiveRequests().length);
});
```
I've tried this with the latest sharp on OS X Yosemite and Linux Ubuntu 14.04 and both exit cleanly without any errors. Are you able to provide a file or code sample that consistently fails?

**Comment by asilvas** [comment]
Good to see that working for you. I don't have a simple stand-alone demo code (yet), but I'll continue to track it down and let you know what I find.

**Comment by asilvas** [comment]
Here's an example:

```
var sharp = require('sharp');
var fs = require('fs');
var path = require('path');
var http = require('http');

var fileDataPath = path.resolve(__dirname, './test/files/test.txt');
var fileData = fs.readFileSync(fileDataPath);

http.createServer(function(req, res) {
  sharp(fileData).metadata(function(err, meta) {
    if (err) res.end(err.stack || err);
    else res.end(JSON.stringify(meta, null, '\t'));
  });
}).listen(4444);
```

Invoked manually `node test.js`.

After hitting localhost:4444 which invokes `metadata` once on the text file, it'll respond with the proper error, but you cannot kill the worker without a forced exit.

**Comment by asilvas** [comment]
Verified, even in my case, that `process._getActiveHandles()` is identical before and after the "bad" metadata call. So appears unrelated to handles.

**Comment by lovell** [comment]
Pressing Ctrl+C and using `kill PID` both quite happily end your http-based example process on OS X and Linux for me (I fired ~500 req/s at it for a minute) :(

I've tried node v0.12, v4 and v5.

Are you able to check with a colleague to see if they also experience this behaviour on another system?

**Comment by asilvas** [comment]
Wow, bizarre. fyi using node `v4.4.0`. Up to you if you want to close, then. I'll work around it.

**Comment by lovell** [comment]
Let's leave this open for a bit to see if others can confirm/deny the same behaviour.

**Comment by lovell** [comment]
@asilvas Are you still experiencing this problem? Sadly I've never been able to reproduce this and there have been no further reports of a similar nature.

**Comment by asilvas** [comment]
Not sure since we no longer allow processing of non-images. I doubt it went away though ;-). I can test more after the Holidays. But feel free to close.

**Comment by lovell** [comment]
Thank you for the update, will close for now. 🎅
