### ISSUE TITLE
Deployment error in render

### ISSUE THREAD

**Issue by mbgalanttibay** [lovell/sharp#3951]
### What are you trying to achieve?
I'm trying to deploy my web app to render and keep failing.

I keep on getting the error

error @img/sharp-win32-x64@0.33.2: The platform "linux" is incompatible with this module.
error @img/sharp-win32-x64@0.33.2: The engine "yarn" is incompatible with this module. Expected version ">=3.2.0". Got "1.22.21"
warning @img/sharp-win32-x64@0.33.2: The engine "pnpm" appears to be invalid.
error Found incompatible module.

### Please provide sample image(s) that help explain this question

![renderFailed](https://github.com/lovell/sharp/assets/137662317/c757fdb6-7651-4d6f-a3e2-1f1a57241883)

I'm just starting to learn backend and now stuck with this error, i'm hoping for your solutions

**Comment by lovell** [comment]
Please ensure you've read and understood https://sharp.pixelplumbing.com/install

If you're using yarn, I highly recommend you upgrade to v3+.

**Comment by lovell** [comment]
@mbgalanttibay Were you able to make any progress with this?

**Comment by mbgalanttibay** [comment]
Hi, yes, after reading and taking your recommendation, it all worked just fine. Apparently i havent installed yarn on my project yet, after doing so and using v3+ and rebuilding it, i was able to deploy it on render.

thanks a lot and sorry for any inconvenience. Now i can progress thru my studies😊
