### ISSUE TITLE
become slow (x8) when deployed on el cheapo hosting company server

### ISSUE THREAD

**Issue by 7te3ep** [lovell/sharp#3952]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

Hello, 
I use sharp js to compose images and then send them to my bot discord. When I launch the bot on my machine (Ubuntu) I get a generation time of 200/300ms, to create an empty image, and add 6 images with "composing". 

The problem arises when I launch the bot on my server (bot hosting on sparked host), the generation time rises to 1600ms, and with each image generated, the ram fills up by 50Mib, so quickly the ram is full. 

I've looked at the memory leak issue, but I think I'm doing something simple wrong to have such a big problem. 
I disabled the cache with sharp.cache(false). 
However, the generated images seem to remain in the ram.

There is a risk that the problem comes from discord for the memory, but for the generation time it can only be sharp js (non-existent problem with canvas).

This is the first time I've opened an "issue" on github, if any information is missing I'll be very happy to provide it. 

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem
Here is how I resize each image before compsing with them (so the file is smaller)
```js
            const resizePromise = sharp(
               `src/assets/cards/${cards[index][0]}.jpg`
            )
               .resize({
                  width: Math.round(cardSize[0]),
                  height: Math.round(cardSize[1]),
               })
               .toBuffer()
               .then((buffer) => {
                  compose.push({
                     input: buffer,
                     top: pos[i][0],
                     left: pos[i][1],
                  });
               });
```
Here is how I compose.
```js
const data = await sharp({
   create: {
      width: Math.ceil(totalSizes[0]),
      height: Math.ceil(totalSizes[1]),
      channels: 4,
      background: { r: 255, g: 0, b: 0, alpha: 0 },
   },
})
   .composite(compose)
   .webp()
   .toBuffer();
return new AttachmentBuilder(data, {
   name: "inv.webp",
});
```
![Screenshot from 2024-01-15 20-13-07](https://github.com/lovell/sharp/assets/103881774/fc427e3e-0b5e-47ff-996c-389cb6f630de)
![Screenshot from 2024-01-15 20-14-09](https://github.com/lovell/sharp/assets/103881774/88beceae-7144-4d0f-8859-7c974fa151a7)

**Comment by lovell** [comment]
This doesn't sound like a memory leak. If you cannot reproduce locally then you'll need to ask "sparked host" support. I highly suspect they are a cheapo hosting company that are throttling CPU and limiting RAM. Running Node.js on anything under 1GB of RAM is going to cause problems.

**Comment by 7te3ep** [comment]
> This doesn't sound like a memory leak. If you cannot reproduce locally then you'll need to ask "sparked host" support. I highly suspect they are a cheapo hosting company that are throttling CPU and limiting RAM. Running Node.js on anything under 1GB of RAM is going to cause problems.

Thanks for the quick reply! 
Indeed the cpu goes up to 90% at each generation, that's what must slow down the generation. As for the ram increasing as if the image stayed in it, I can't explain it. You said that running node with >1GB of ram was complicated, does that mean it's normal for the ram to increase like that ad infinitum?

**Comment by followbl** [comment]
fwiw this update has made my vercel nextjs build fails, reverting back to `"sharp": "0.33.1",` fixed it.

**Comment by AndrewRPorter** [comment]
Downgrading to `0.33.1` fixed my issues. Was getting the following build failures in Next.js on `0.33.2`:

```
RangeError: Maximum call stack size exceeded
```

**Comment by lovell** [comment]
@7te3ep If you're using a budget hosting company with limited RAM, you'll need to read up about configuring Node.js for such an environment. For example, things like garbage collection can fail to kick in when using the default settings with 512MB RAM.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
