### ISSUE TITLE
"Maximum call stack" error in Vercel when upgrading from 0.33.1 to 0.33.2 while using Next.js

### ISSUE THREAD

**Issue by bring-shrubbery** [lovell/sharp#3958]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

Locally it works perfectly, and this is the output of the envinfo commant:

```
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 920.55 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 8.13.1 - ~/Library/pnpm/pnpm
  npmPackages:
    sharp: ^0.33.1 => 0.33.1 
```

But this breaks only in Vercel. I'm not sure what the output would be for them, but I'm using Node v18 in Vercel.

### What are the steps to reproduce?

- Upgrade to the `sharp@0.33.2` in an existing Next.js project (`next@14.0.4`).
- Try deploying your project to vercel.

Unfortunately, I'm not able to create a reproduction for demonstration.

### What is the expected behaviour?

Should deploy without problems.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

I've provided the error I'm getting from in Vercel console.

### Please provide sample image(s) that help explain this problem

See below, that's the only thing I see.

### Error

```
✓ Compiled successfully
--
18:57:30.021 | Linting and checking validity of types ...
18:58:06.485 | Collecting page data ...
18:58:10.907 | Generating static pages (0/58) ...
18:58:12.025 | Generating static pages (14/58)
18:58:12.626 | Generating static pages (28/58)
18:58:12.972 | Generating static pages (43/58)
18:58:13.395 | ✓ Generating static pages (58/58)
18:58:14.224 | Finalizing page optimization ...
18:58:14.224 | Collecting build traces ...

RangeError: Maximum call stack size exceeded
--
18:58:26.823 | at RegExp.exec (<anonymous>)
18:58:26.823 | at create (/vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/micromatch/index.js:15:18889)
18:58:26.823 | at create (/vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/micromatch/index.js:15:18918)
18:58:26.823 | at parse.fastpaths (/vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/micromatch/index.js:15:18997)
18:58:26.823 | at picomatch.makeRe (/vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/micromatch/index.js:15:21635)
18:58:26.823 | at picomatch (/vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/micromatch/index.js:15:19637)
18:58:26.823 | at /vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/micromatch/index.js:15:19294
18:58:26.823 | at Array.map (<anonymous>)
18:58:26.823 | at picomatch (/vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/micromatch/index.js:15:19286)
18:58:26.824 | at micromatch.isMatch (/vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/micromatch/index.js:15:1090)
18:58:26.913 | ELIFECYCLE  Command failed with exit code 1.
18:58:26.932 | Error: Command "pnpm run build" exited with 1
```

### Additional notes

A couple of facts that I'm sure about:
- I've identified that this happens specifically when updating from `sharp@0.33.1` to `sharp@0.33.2`.
- I'm deploying on Vercel.
- I'm using Node 18 everywhere with `pnpm` as package manager.
- **Locally it works fine, but breaks specifically in Vercel**.

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/3944

**Comment by bring-shrubbery** [comment]
Opps, sorry, missed that issue somehow 🤔
