### ISSUE TITLE
Unable to put an overlay of smaller size than the resized  image

### ISSUE THREAD

**Issue by sbsomya** [lovell/sharp#396]
Hi I have a functionality to put a default overlay on top of images of different sizes
and using sharp for generating those images 

The error comes up saying the overlay image should be of same size of resized image
Is there a way to do the same

**Comment by lovell** [comment]
Hello, please try with the latest version:

> "Improvements to overlayWith: differing sizes/formats, gravity, buffer input."

http://sharp.dimens.io/en/stable/changelog/#v0140-2nd-april-2016

**Comment by lovell** [comment]
@sbsomya Were you able to try with v0.14.0?

http://sharp.dimens.io/en/stable/api/#overlaywithimage-options

**Comment by sbsomya** [comment]
Yess lovell 
Thanks

**Comment by srameshr** [comment]
@lovell I am on 0.21.2 and this issue still exists
