### ISSUE TITLE
GIF decoder?

### ISSUE THREAD

**Issue by test3211234** [lovell/sharp#3973]
### What are you trying to achieve?

I want to use Sharp's GIF decoder in one of my projects, with credit of course, but I can't find the GIF decoder code. Also how would I go about putting Sharp's GIF decoder code into my own project so that I can get frame and pixel/color data from a byte string and use that data to display the GIF?

The reason is, the environment I'm working in I cannot install NPM libraries. I'm writing in Roblox using Roblox-ts, which transpiles TypeScript code to Lua.

### When you searched for similar issues, what did you find that might be related?

N/A

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

N/A

### Please provide sample image(s) that help explain this question

N/A

**Comment by lovell** [comment]
sharp uses https://github.com/libvips/libvips/tree/master/libvips/foreign/libnsgif to decode GIF images.

This library originates from the NetSurf browser - please see https://www.netsurf-browser.org/projects/libnsgif/ for the upstream code.

**Comment by test3211234** [comment]
Oh, that’s not typescript it’s c so I don’t think I can use it? Do you have any recommendations for what GIF decoder I can use?

**Comment by lovell** [comment]
https://github.com/deanm/omggif

**Comment by test3211234** [comment]
Cool, unfortunately it's JavaScript, not TypeScript. I need types or the code doesn't compile.

 Also, maybe you should start discussions so that people can mark as answer instead of everything in the issues section.

**Comment by lovell** [comment]
Perhaps try https://github.com/qq15725/modern-gif ?

In my experience having both GitHub issues and discussions causes too much fragmentation (e.g. now you have to search two places) so it's one or the other but not both.

**Comment by test3211234** [comment]
That's really complex, I just decided to use omggif but rewrite it in Lua. Thanks a ton for finding me that library, it's perfect for rewriting in Lua.
