### ISSUE TITLE
RangeError: Maximum call stack Exceeded (when with nextjs app deployed to vercel)

### ISSUE THREAD

**Issue by EsinShadrach** [lovell/sharp#3976]
After adding sharp to a nextJS app via `bun install sharp` a RangeError error happens when building on vercel. it successfully build locally tho

- Image 1 Local Build
- Image 2 Vercel build

<img width="736" alt="image" src="https://github.com/lovell/sharp/assets/102266348/3cdd70da-a4d4-4738-a90e-06ab98cb3b62">

<img width="1341" alt="Screenshot 2024-02-03 at 11 02 43 PM" src="https://github.com/lovell/sharp/assets/102266348/8d8728b5-f40d-4fa6-afc5-1923f81af771">

**Comment by EsinShadrach** [comment]
2 deployments with the only difference being the addition/removal of sharp

<img width="736" alt="image" src="https://github.com/lovell/sharp/assets/102266348/48eeab86-6d8a-4f21-b748-50f3b6a146fc">

**Comment by lovell** [comment]
This was a bug in Next.js, please see https://github.com/lovell/sharp/issues/3944
