### ISSUE TITLE
High memory usage when handling SVG with embedded base64 images

### ISSUE THREAD

**Issue by armisael** [lovell/sharp#3979]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: macOS 14.1.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 96.17 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.asdf/installs/nodejs/20.10.0/bin/node
    npm: 10.2.3 - ~/.asdf/plugins/nodejs/shims/npm
  npmPackages:
    sharp: 0.33.2 => 0.33.2 
```

### What are the steps to reproduce?

We are experiencing high memory usage when trying to resize some SVG files that contain a base64-encoded image; the images themselves are around 2.5MB, but the process takes around 300MB of memory; since it's run in a k8s container with limited resources, it gets killed without being able to handle the request properly.

### What is the expected behaviour?

The ideal behaviour would be to be able to process the input file without consuming too much memory; a more reasonable behaviour would be to be able to catch such cases and block the image processing when memory usage surpasses an allocated amount, providing a way to return an error instead.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

I published a simple example project here: https://github.com/armisael/test-sharp-memory-usage

To test it:

```sh
node index.js
```

You'll see RSS memory usage around 300MB.

### Please provide sample image(s) that help explain this problem

The aforementioned repository contains two sample images.

**Comment by lovell** [comment]
SVG images are processed via librsvg, and this includes embedded images. The sample SVG contains a base64-encoded 9662x3556 RGBA PNG, which librsvg will decompress into memory. You'll see a very similar memory consumption using `rsvg-convert` at the command line.

If you control the source of this SVG, perhaps consider using a drop-shadow filter instead of a bitmap.

**Comment by armisael** [comment]
Unfortunately we don't control the source of the images. Is there a way to pass to librsvg the `limitInputPixels` option?

**Comment by lovell** [comment]
librsvg does not provide a way to further limit dimensions of embedded images below its existing 32767x32767 overall limit.

A possible solution might be to inspect the SVG for embedded images, extract and convert from base64 then check the dimensions in the metadata.

**Comment by armisael** [comment]
Inspecting the SVG seems the only solution. Thank you for making everything clear.
