### ISSUE TITLE
Sharp leaves file resources open blocking file operations

### ISSUE THREAD

**Issue by kasium** [lovell/sharp#3980]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [X] Running `npm install sharp` completes without error.
- [X] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [X] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz
    Memory: 5.55 GB / 15.73 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: 0.33.2 => 0.33.2
```

### What are the steps to reproduce?

1. open a new node shell
2. `const sharp = require("sharp")`
3. `const buf= await sharp("somefile.jpg").toBuffer()`
4. Try to delete the file while the node process is still running

### What is the expected behaviour?

Either I can delete the file or sharp provides a method so that I can close any open resources

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```js
const sharp = require("sharp")
const fs = require("fs")
const buf= await sharp("somefile.jpg").toBuffer()
fs.rmSync("somefile.jpg")
```

### Please provide sample image(s) that help explain this problem

`Use any jpg image`

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/api-utility#cache
```
sharp.cache(false);
```

**Comment by kasium** [comment]
makes sense, thanks
