### ISSUE TITLE
HEIC support

### ISSUE THREAD

**Issue by hfrid** [lovell/sharp#3981]
### What are you trying to achieve?

Would like to  see HEIC support to enable conversion from HEIC to other supported formats. Any plans for HEIC support?

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/api-output#heif

> Support for patent-encumbered HEIC images using `hevc` compression requires the use of a globally-installed libvips compiled with support for libheif, libde265 and x265.

**Comment by hfrid** [comment]
This is for output though right?

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
