### ISSUE TITLE
WLS2 Ubuntu 22.04

### ISSUE THREAD

**Issue by JohnLeet** [lovell/sharp#3986]
## Possible install-time or require-time problem

- [x] I have read and understood all of the [documentation relating to installation](https://sharp.pixelplumbing.com/install).

You must confirm both of these before continuing.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest,
please open an issue against that package instead.

### Are you using a supported runtime?

- [x] I am using Node.js with a version that satisfies `^18.17.0 || ^20.3.0 || >=21.0.0`

If you cannot confirm any of these,
please upgrade to the latest version
and try again before opening an issue.

### Are you using a supported package manager and installing optional dependencies?

- [x] I am using npm >= 9.6.5 with `--include=optional`

If you cannot confirm any of these, please upgrade to the latest version of your chosen package manager
and ensure you are allowing the installation of optional or multi-platform dependencies before opening an issue.

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

make: Entering directory '/home/john/Sites/steel/slicing/node_modules/favicons/node_modules/sharp/build'
  touch Release/obj.target/libvips-cpp.stamp
  g++ -o Release/obj.target/sharp/src/common.o ../src/common.cc '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/home/john/.cache/node-gyp/21.6.1/include/node -I/home/john/.cache/node-gyp/21.6.1/src -I/home/john/.cache/node-gyp/21.6.1/deps/openssl/config -I/home/john/.cache/node-gyp/21.6.1/deps/openssl/openssl/include -I/home/john/.cache/node-gyp/21.6.1/deps/uv/include -I/home/john/.cache/node-gyp/21.6.1/deps/zlib -I/home/john/.cache/node-gyp/21.6.1/deps/v8/include -I../../../../nan -I/usr/include/libgsf-1 -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu/ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/orc-0.4 -I/usr/include/OpenEXR -I/usr/include/openjpeg-2.4 -I/usr/include/poppler/glib -I/usr/include/poppler -I/usr/include/librsvg-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/openslide -I/usr/lib/x86_64-linux-gnu/hdf5/serial/include -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/x86_64-linux-gnu -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++17 -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/common.o.d.raw   -c
In file included from /home/john/.cache/node-gyp/21.6.1/include/node/v8-handle-base.h:8,
                 from /home/john/.cache/node-gyp/21.6.1/include/node/v8-local-handle.h:12,
                 from /home/john/.cache/node-gyp/21.6.1/include/node/v8-array-buffer.h:12,
                 from /home/john/.cache/node-gyp/21.6.1/include/node/v8.h:24,
                 from /home/john/.cache/node-gyp/21.6.1/include/node/node.h:73,
                 from ../src/common.cc:22:
/home/john/.cache/node-gyp/21.6.1/include/node/v8-internal.h: In static member function ‘static constexpr int v8::internal::SmiTagging<4>::SmiToInt(v8::internal::Address)’:
/home/john/.cache/node-gyp/21.6.1/include/node/v8-internal.h:86:3: error: body of ‘constexpr’ function ‘static constexpr int v8::internal::SmiTagging<4>::SmiToInt(v8::internal::Address)’ not a return-statement
   86 |   }
      |   ^
/home/john/.cache/node-gyp/21.6.1/include/node/v8-internal.h: In static member function ‘static constexpr int v8::internal::SmiTagging<8>::SmiToInt(v8::internal::Address)’:
/home/john/.cache/node-gyp/21.6.1/include/node/v8-internal.h:111:3: error: body of ‘constexpr’ function ‘static constexpr int v8::internal::SmiTagging<8>::SmiToInt(v8::internal::Address)’ not a return-statement
  111 |   }
      |   ^
/home/john/.cache/node-gyp/21.6.1/include/node/v8-internal.h: In function ‘void v8::internal::PerformCastCheck(T*)’:
/home/john/.cache/node-gyp/21.6.1/include/node/v8-internal.h:976:38: error: ‘remove_cv_t’ is not a member of ‘std’; did you mean ‘remove_cv’?
  976 |             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
      |                                      ^~~~~~~~~~~
      |                                      remove_cv
/home/john/.cache/node-gyp/21.6.1/include/node/v8-internal.h:976:38: error: ‘remove_cv_t’ is not a member of ‘std’; did you mean ‘remove_cv’?
  976 |             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
      |                                      ^~~~~~~~~~~
      |                                      remove_cv
/home/john/.cache/node-gyp/21.6.1/include/node/v8-internal.h:976:50: error: template argument 2 is invalid
  976 |             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
      |                                                  ^
/home/john/.cache/node-gyp/21.6.1/include/node/v8-internal.h:976:63: error: ‘::Perform’ has not been declared
  976 |             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
      |                                                               ^~~~~~~
In file included from /home/john/.cache/node-gyp/21.6.1/include/node/v8-object.h:9,
                 from /home/john/.cache/node-gyp/21.6.1/include/node/v8-array-buffer.h:13,
                 from /home/john/.cache/node-gyp/21.6.1/include/node/v8.h:24,
                 from /home/john/.cache/node-gyp/21.6.1/include/node/node.h:73,
                 from ../src/common.cc:22:
/home/john/.cache/node-gyp/21.6.1/include/node/v8-maybe.h: At global scope:
/home/john/.cache/node-gyp/21.6.1/include/node/v8-maybe.h:106:27: error: ‘std::enable_if_t’ has not been declared
  106 |   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
      |                           ^~~~~~~~~~~
/home/john/.cache/node-gyp/21.6.1/include/node/v8-maybe.h:106:38: error: expected ‘>’ before ‘<’ token
  106 |   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
      |                                      ^
/home/john/.cache/node-gyp/21.6.1/include/node/v8-maybe.h:123:25: error: ‘std::enable_if_t’ has not been declared
  123 | template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
      |                         ^~~~~~~~~~~
/home/john/.cache/node-gyp/21.6.1/include/node/v8-maybe.h:123:36: error: expected ‘>’ before ‘<’ token
  123 | template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
      |                                    ^
In file included from ../src/common.cc:22:
/home/john/.cache/node-gyp/21.6.1/include/node/node.h:687:8: error: ‘optional’ in namespace ‘std’ does not name a template type
  687 |   std::optional<std::string> builder_script_path;
      |        ^~~~~~~~
/home/john/.cache/node-gyp/21.6.1/include/node/node.h:687:3: note: ‘std::optional’ is only available from C++17 onwards
  687 |   std::optional<std::string> builder_script_path;
      |   ^~~
/home/john/.cache/node-gyp/21.6.1/include/node/node.h:739:28: error: ‘std::string_view’ has not been declared
  739 |     Environment* env, std::string_view main_script_source_utf8);
      |                            ^~~~~~~~~~~
make: *** [sharp.target.mk:178: Release/obj.target/sharp/src/common.o] Error 1es/favicons/node_modules/sharp (node install/
make: Leaving directory '/home/john/Sites/steel/slicing/node_modules/favicons/node_modules/sharp/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/john/Sites/steel/slicing/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Linux 5.15.133.1-microsoft-standard-WSL2
gyp ERR! command "/home/john/.nvm/versions/node/v21.6.1/bin/node" "/home/john/Sites/steel/slicing/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/john/Sites/steel/slicing/node_modules/favicons/node_modules/sharp
gyp ERR! node -v v21.6.1
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
    Memory: 6.28 GB / 7.70 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 21.6.1 - ~/.nvm/versions/node/v21.6.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.6.1/bin/npm

I got the issue when I am installing the sharp

**Comment by JohnLeet** [comment]
@lovell Could you help me resolve the issue?

**Comment by lovell** [comment]
>  make: Entering directory '/home/john/Sites/steel/slicing/node_modules/favicons/node_modules/sharp/build'

It looks like you're installing `favicons` rather than `sharp`.

Please provide the *complete* output of running `npm install --verbose --foreground-scripts sharp` in an *empty directory*.

**Comment by JohnLeet** [comment]
@lovell 
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated gulp-group-css-media-queries@1.2.2: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated @stylelint/postcss-markdown@0.36.2: Use the original unforked package instead: postcss-markdown
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated figgy-pudding@3.5.2: This module is no longer supported.
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm WARN deprecated @stylelint/postcss-css-in-js@0.37.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm http fetch GET 200 https://registry.npmjs.org/electron-to-chromium/-/electron-to-chromium-1.4.665.tgz 9065ms (cache miss)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm http fetch GET 200 https://codeload.github.com/bem-tools/bem-tools-core/tar.gz/9a5c91b198a7ce1f2a6b6e64c505aefead27fc8f 4701ms (cache revalidated)
npm http fetch GET 200 https://codeload.github.com/bem-tools/bem-tools-create/tar.gz/bee9b839b6c89b956464be0cf8057d40f332f832 4715ms (cache revalidated)
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm info run husky@4.3.8 install node_modules/husky node husky install

> husky@4.3.8 install
> node husky install

husky > Setting up git hooks:core-js: info run husky@4.3.8 install node_modules/husky node husky install
husky > Done#######) ⠼ reify:core-js: info run husky@4.3.8 install node_modules/husky node husky install
npm info run husky@4.3.8 install { code: 0, signal: null }
npm info run node-sass@9.0.0 install node_modules/node-sass node scripts/install.js

> node-sass@9.0.0 install
> node scripts/install.js

Cached binary found at /home/john/.npm/node-sass/9.0.0/linux-x64-115_binding.nodees/node-sass node scripts/install.js
npm info run node-sass@9.0.0 install { code: 0, signal: null }
npm info run phantomjs-prebuilt@2.1.16 install node_modules/phantomjs-prebuilt node install.js

> phantomjs-prebuilt@2.1.16 install
> node install.js

PhantomJS not found on PATHy:core-js: info run phantomjs-prebuilt@2.1.16 install node_modules/phantomjs-prebuilt node insta
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...
  [----------------------------------------] 0%(##################) ⠋ reify:core-js: info run phantomjs-prebuilt@2.1.16 inst  [===========-----------------------------] 28%(##################) ⠋ reify:core-js: info run phantomjs-prebuilt@2.1.16 ins  [===================---------------------] 47%(##################) ⠋ reify:core-js: info run phantomjs-prebuilt@2.1.16 ins  [========================----------------] 61%(##################) ⠋ reify:core-js: info run phantomjs-prebuilt@2.1.16 ins  [=============================-----------] 72%(##################) ⠋ reify:core-js: info run phantomjs-prebuilt@2.1.16 ins  [=================================-------] 83%(##################) ⠋ reify:core-js: info run phantomjs-prebuilt@2.1.16 ins  [======================================--] 96%(##################) ⠋ reify:core-js: info run phantomjs-prebuilt@2.1.16 ins(##################) ⠋ reify:core-js: info run phantomjs-prebuilt@2.1.16 install node_modules/phantomjs-prebuilt node insta
Received 22866K total.
Extracting tar contents (via spawned process)
Removing /home/john/Sites/steel/slicing/node_modules/phantomjs-prebuilt/lib/phantomde_modules/phantomjs-prebuilt node insta
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1707534895212/phantomjs-2.1.1-linux-x86_64 -> /home/john/Sites/steel/slicing/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js fileeify:core-js: info run phantomjs-prebuilt@2.1.16 install node_modules/phantomjs-prebuilt node insta
Done. Phantomjs binary available at /home/john/Sites/steel/slicing/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
npm info run phantomjs-prebuilt@2.1.16 install { code: 0, signal: null }
npm info run sharp@0.33.2 install node_modules/sharp node install/check

> sharp@0.33.2 install
> node install/check

npm info run sharp@0.33.2 install { code: 0, signal: null }
npm info run sharp@0.23.4 install node_modules/favicons/node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

> sharp@0.23.4 install
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Detected globally-installed libvips v8.12.1.23.4 install node_modules/favicons/node_modules/sharp (node install/
info sharp Building from source via node-gyp
gyp info it worked if it ends with ok info run sharp@0.23.4 install node_modules/favicons/node_modules/sharp (node install/
gyp verb cli [
gyp verb cli   '/home/john/.nvm/versions/node/v20.10.0/bin/node',
gyp verb cli   '/home/john/Sites/steel/slicing/node_modules/.bin/node-gyp',
gyp verb cli   'rebuild'
gyp verb cli ]
gyp info using node-gyp@8.4.1
gyp info using node@20.10.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configurationles/favicons/node_modules/sharp (node install/
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - executable path is "/usr/bin/python3"install node_modules/favicons/node_modules/sharp (node install/
gyp verb find Python - executing "/usr/bin/python3" to get version
gyp verb find Python - version is "3.10.12"
gyp info find Python using Python version 3.10.12 found at "/usr/bin/python3"
gyp verb get node dir no --target version specified, falling back to host node version: 20.10.0
gyp verb command install [ '20.10.0' ]
gyp verb install input version string "20.10.0"sharp@0.23.4 install node_modules/favicons/node_modules/sharp (node install/
gyp verb install installing version: 20.10.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 11
gyp verb needs "installVersion" 9-js: info run sharp@0.23.4 install node_modules/favicons/node_modules/sharp (node install/
gyp verb install version is good
gyp verb get node dir target node version installed: 20.10.0
gyp verb build dir attempting to create "build" dir: /home/john/Sites/steel/slicing/node_modules/favicons/node_modules/sharp/build
gyp verb build dir "build" dir needed to be created? Yes
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/john/Sites/steel/slicing/node_modules/favicons/node_modules/sharp/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/john/Sites/steel/slicing/node_modules/favicons/node_modules/sharp/config.gypi
gyp verb common.gypi checking for gypi file: /home/john/Sites/steel/slicing/node_modules/favicons/node_modules/sharp/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/john/Sites/steel/slicing/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/john/Sites/steel/slicing/node_modules/favicons/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/john/Sites/steel/slicing/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/john/.cache/node-gyp/20.10.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/john/.cache/node-gyp/20.10.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/john/Sites/steel/slicing/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/john/.cache/node-gyp/20.10.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/john/Sites/steel/slicing/node_modules/favicons/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []ify:core-js: info run sharp@0.23.4 install node_modules/favicons/node_modules/sharp (node install/
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/john/.cache/node-gyp/20.10.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/john/Sites/steel/slicing/node_modules/favicons/node_modules/sharp/build'
  touch Release/obj.target/libvips-cpp.stampun sharp@0.23.4 install node_modules/favicons/node_modules/sharp (node install/
  g++ -o Release/obj.target/sharp/src/common.o ../src/common.cc '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/home/john/.cache/node-gyp/20.10.0/include/node -I/home/john/.cache/node-gyp/20.10.0/src -I/home/john/.cache/node-gyp/20.10.0/deps/openssl/config -I/home/john/.cache/node-gyp/20.10.0/deps/openssl/openssl/include -I/home/john/.cache/node-gyp/20.10.0/deps/uv/include -I/home/john/.cache/node-gyp/20.10.0/deps/zlib -I/home/john/.cache/node-gyp/20.10.0/deps/v8/include -I../../../../nan -I/usr/include/libgsf-1 -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu/ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/orc-0.4 -I/usr/include/OpenEXR -I/usr/include/openjpeg-2.4 -I/usr/include/poppler/glib -I/usr/include/poppler -I/usr/include/librsvg-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/openslide -I/usr/lib/x86_64-linux-gnu/hdf5/serial/include -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/x86_64-linux-gnu -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++17 -std=c++0x -fexceptions -Wall -O3 -Wno-cast-function-type -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/common.o.d.raw   -c
In file included from /home/john/.cache/node-gyp/20.10.0/include/node/v8-local-handle.h:12,
                 from /home/john/.cache/node-gyp/20.10.0/include/node/v8-array-buffer.h:12,
                 from /home/john/.cache/node-gyp/20.10.0/include/node/v8.h:24,
                 from /home/john/.cache/node-gyp/20.10.0/include/node/node.h:73,
                 from ../src/common.cc:22:
/home/john/.cache/node-gyp/20.10.0/include/node/v8-internal.h: In function ‘void v8::internal::PerformCastCheck(T*)’:
/home/john/.cache/node-gyp/20.10.0/include/node/v8-internal.h:893:38: error: ‘remove_cv_t’ is not a member of ‘std’; did you mean ‘remove_cv’?
  893 |             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
      |                                      ^~~~~~~~~~~
      |                                      remove_cv
/home/john/.cache/node-gyp/20.10.0/include/node/v8-internal.h:893:38: error: ‘remove_cv_t’ is not a member of ‘std’; did you mean ‘remove_cv’?
  893 |             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
      |                                      ^~~~~~~~~~~
      |                                      remove_cv
/home/john/.cache/node-gyp/20.10.0/include/node/v8-internal.h:893:50: error: template argument 2 is invalid
  893 |             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
      |                                                  ^
/home/john/.cache/node-gyp/20.10.0/include/node/v8-internal.h:893:63: error: ‘::Perform’ has not been declared
  893 |             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
      |                                                               ^~~~~~~
In file included from /home/john/.cache/node-gyp/20.10.0/include/node/v8-object.h:9,
                 from /home/john/.cache/node-gyp/20.10.0/include/node/v8-array-buffer.h:13,
                 from /home/john/.cache/node-gyp/20.10.0/include/node/v8.h:24,
                 from /home/john/.cache/node-gyp/20.10.0/include/node/node.h:73,
                 from ../src/common.cc:22:
/home/john/.cache/node-gyp/20.10.0/include/node/v8-maybe.h: At global scope:
/home/john/.cache/node-gyp/20.10.0/include/node/v8-maybe.h:106:27: error: ‘std::enable_if_t’ has not been declared
  106 |   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
      |                           ^~~~~~~~~~~
/home/john/.cache/node-gyp/20.10.0/include/node/v8-maybe.h:106:38: error: expected ‘>’ before ‘<’ token
  106 |   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
      |                                      ^
/home/john/.cache/node-gyp/20.10.0/include/node/v8-maybe.h:123:25: error: ‘std::enable_if_t’ has not been declared
  123 | template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
      |                         ^~~~~~~~~~~
/home/john/.cache/node-gyp/20.10.0/include/node/v8-maybe.h:123:36: error: expected ‘>’ before ‘<’ token
  123 | template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
      |                                    ^
In file included from ../src/common.cc:22:
/home/john/.cache/node-gyp/20.10.0/include/node/node.h:711:28: error: ‘std::string_view’ has not been declared
  711 |     Environment* env, std::string_view main_script_source_utf8);
      |                            ^~~~~~~~~~~
In file included from ../src/common.cc:24:
../../../../nan/nan.h: In function ‘bool Nan::IdleNotification(int)’:
../../../../nan/nan.h:688:63: warning: ‘bool v8::Isolate::IdleNotificationDeadline(double)’ is deprecated: Use MemoryPressureNotification() to influence the GC schedule. [-Wdeprecated-declarations]
  688 |     return v8::Isolate::GetCurrent()->IdleNotificationDeadline(
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
  689 |         idle_time_in_ms * 0.001);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/john/.cache/node-gyp/20.10.0/include/node/v8-initialization.h:13,
                 from /home/john/.cache/node-gyp/20.10.0/include/node/v8.h:34,
                 from /home/john/.cache/node-gyp/20.10.0/include/node/node.h:73,
                 from ../src/common.cc:22:
/home/john/.cache/node-gyp/20.10.0/include/node/v8-isolate.h:1293:8: note: declared here
 1293 |   bool IdleNotificationDeadline(double deadline_in_seconds);
      |        ^~~~~~~~~~~~~~~~~~~~~~~~
make: *** [sharp.target.mk:183: Release/obj.target/sharp/src/common.o] Error 1es/favicons/node_modules/sharp (node install/
make: Leaving directory '/home/john/Sites/steel/slicing/node_modules/favicons/node_modules/sharp/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/john/Sites/steel/slicing/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Linux 5.15.133.1-microsoft-standard-WSL2
gyp ERR! command "/home/john/.nvm/versions/node/v20.10.0/bin/node" "/home/john/Sites/steel/slicing/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/john/Sites/steel/slicing/node_modules/favicons/node_modules/sharp
gyp ERR! node -v v20.10.0
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok
npm info run sharp@0.23.4 install { code: 1, signal: null }
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/home/john/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
npm verb stack     at ChildProcess.emit (node:events:514:28)
npm verb stack     at maybeClose (node:internal/child_process:1105:16)
npm verb stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm verb pkgid sharp@0.23.4
npm verb cwd /home/john/Sites/steel/slicing
npm verb Linux 5.15.133.1-microsoft-standard-WSL2
npm verb node v20.10.0
npm verb npm  v10.4.0
npm ERR! code 1
npm ERR! path /home/john/Sites/steel/slicing/node_modules/favicons/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
npm verb exit 1
npm verb unfinished npm timer reify 1707534628208
npm verb unfinished npm timer reify:build 1707534886330
npm verb unfinished npm timer build 1707534886335
npm verb unfinished npm timer build:deps 1707534886338
npm verb unfinished npm timer build:run:install 1707534886468
npm verb unfinished npm timer build:run:install:node_modules/favicons/node_modules/sharp 1707534901253
npm verb code 1

**Comment by JohnLeet** [comment]
I dont know why favicons because i started `npm install --verbose --foreground-scripts sharp`

**Comment by lovell** [comment]
> npm info run sharp@0.23.4 install node_modules/favicons/node_modules/sharp 

You're using an out of date version of `favicons` that depends on an out of date version of `sharp` (0.23.4 was released in 2019), please upgrade.

**Comment by lovell** [comment]
Best guess would be a `package.json` and/or  `package-lock.json` file  in the same (or parent) directory with an outdated dependency. Also watch out for any globally-installed packages (run `npm ls -g` to list these).

**Comment by JohnLeet** [comment]
> Best guess would be a `package.json` and/or `package-lock.json` file in the same (or parent) directory with an outdated dependency. Also watch out for any globally-installed packages (run `npm ls -g` to list these).

Thank you :)
