### ISSUE TITLE
Sharp swaps width and height

### ISSUE THREAD

**Issue by musicchenko** [lovell/sharp#3987]
Sharp swaps width and height for certain images
Original meta:
![image](https://github.com/lovell/sharp/assets/53790866/f04a5a53-13b9-4b55-9ac1-eefbccf951e8)
What sharp displays:
![image](https://github.com/lovell/sharp/assets/53790866/b773e7f7-a700-41ff-9f8b-f580a5a5db17)

**Comment by lovell** [comment]
You've not provided a sample image but this almost certainly relates to EXIF Orientation metadata. You've not said what the source of the "Original meta" but I would assume that has taken EXIF Orientation into account and swapped the dimensions.

**Comment by musicchenko** [comment]
Sorry, that's the image

![IMG-20240211-WA0004](https://github.com/lovell/sharp/assets/53790866/b4ef73f2-03a1-4838-9da2-97202c01db42)

**Comment by lovell** [comment]
```
$ identify 303949899-b4ef73f2-03a1-4838-9da2-97202c01db42.jpeg 
303949899-b4ef73f2-03a1-4838-9da2-97202c01db42.jpeg JPEG 3840x2160+0+0 DirectClass 8-bit 801.8Ki 0.000u 0m:0.000000s
```
```
$ exiftool 303949899-b4ef73f2-03a1-4838-9da2-97202c01db42.jpeg | grep Orientation
Orientation                     : Rotate 90 CW
```

**Comment by akowalska622** [comment]
Hey @lovell, I have similar issue - when I upload portrait oriented images then width and height are swapped. No issue with horizontal oriented images. I'm not really sure how to apply your answer and I couldn't find any other issue targeting the same problem. I'd appreciate some help, cheers

**Comment by akowalska622** [comment]
Thanks!
