### ISSUE TITLE
Support for 16 bit color depth PNG

### ISSUE THREAD

**Issue by gillesboisson** [lovell/sharp#3988]
### What are you trying to achieve?

From 16 bits (ushort) pngs I would to keep color depth when it saved

### When you searched for similar feature requests, what did you find that might be related?

I didn't any option in PngOptions 

```js
const image = sharp('./my-image.png');


image.png({
   // color depth doesn't need to be supported if imagesource was ushort already
   colorDepth: 'ushort' // or 16 but it seams that specifying type seems to make sens, png support ubyte ushort 
});
```

### What alternatives have you considered?

No alternative apart from switching library

### Please provide sample image(s) that help explain this feature

My use case is mainly for GLTF export optimisation as I need to resize and compress texture, normal map and high quality require 16 bits color depth texture. In order to be used as it is, or compressed again in GPU texture format  

eg.
![Books_Oil_Lamps_and_Props_Normal](https://github.com/lovell/sharp/assets/11314830/bd1f42cf-ad5b-45f7-b1fd-ce29b55eb3a6)

**Comment by lovell** [comment]
Did you see https://sharp.pixelplumbing.com/api-colour#tocolourspace ?

```js
await sharp(input)
 .toColourspace('rgb16')
 .toFile('16-bpp.png');
```

In addition, if you hadn't seen it, https://github.com/donmccurdy/glTF-Transform uses sharp under the hood and may be of interest.

**Comment by lovell** [comment]
I've added some clarification and a further example to the docs via commit https://github.com/lovell/sharp/commit/0eb57698ec4b47cc9d67f8ec25d70bb4d3930fb5

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
