### ISSUE TITLE
unflatten images to make them transparent still keep white pixels around the edges of the image

### ISSUE THREAD

**Issue by Nivg** [lovell/sharp#3989]
I am using the `unflatten` command to make a version of a given image transparent.

Example for a given image:
![300](https://github.com/lovell/sharp/assets/6303616/35f2816d-96a1-4b64-800a-3f8837a61e9f)

Here is the result:
![300_transparent](https://github.com/lovell/sharp/assets/6303616/e600b249-5cad-40e5-80fa-2739e43377d2)

As you can see, I still have a residue of white pixels around the resulted image.

I'm not sure why, maybe I'm missing something regarding the understanding of how unflatten works?

Sample code (nothing special here):
`
    await sharp(path.join(productPath, fileName + ".png")).unflatten().toFile(path.join(productPath, fileName + "_transparent.png"));
`

**Comment by lovell** [comment]
Did you see https://sharp.pixelplumbing.com/api-operation#unflatten ?

It looks like the "background" of this image consists of white and light grey pixels, with `unflatten` operating only on the white pixels as documented.

**Comment by Nivg** [comment]
> Did you see https://sharp.pixelplumbing.com/api-operation#unflatten ?
> 
> It looks like the "background" of this image consists of white and light grey pixels, with `unflatten` operating only on the white pixels as documented.

Yes, I have read the docs. Didn't notice the very light grey pixels, thank you for this insight.

I'll try to use several steps, first to transform the light grey pixels to white and then use the unflatten command.

Thanks!

**Comment by lovell** [comment]
@Nivg Were you able to make progress with this?

**Comment by Nivg** [comment]
> @Nivg Were you able to make progress with this?

Unfortunately not yet; I am closing this, as the function is doing what it's suppose to do.
Thanks!
