### ISSUE TITLE
Support for sharp with bun in replit

### ISSUE THREAD

**Issue by 7heMech** [lovell/sharp#3990]
I tried using sharp with bun on linux on replit with many of the latest versions, it's the same issue:
```
109 |   }
110 |   help.push(
111 |     '- Consult the installation documentation:',
112 |     '    See https://sharp.pixelplumbing.com/install'
113 |   );
114 |   throw new Error(help.join('\n'));
              ^
error: Could not load the "sharp" module using the linux-x64 runtime
undefined: libstdc++.so.6: cannot open shared object file: No such file or directory
```

Repl: https://replit.com/@7heMech/Sharp-falis

The bun version you see in the .replit file is replit's internal versioning which is a static reference to their latest bun version 1.0.23 currently.

**Comment by lovell** [comment]
You'll need to ask Replit.

My best guess would be that the nix packaging they provide for Bun at https://github.com/replit/nixmodules/blob/main/pkgs/bun/default.nix needs to add support for `REPLIT_LD_LIBRARY_PATH` like https://github.com/replit/nixmodules/pull/198
