### ISSUE TITLE
Why does Tile skip folder numbers the higher the zoom?

### ISSUE THREAD

**Issue by GcodeG01** [lovell/sharp#3991]
I'm trying to use Sharp to tile an uploaded image for leaflet maps. I'm pretty close, but I found that leaflet is trying to grab say image url 4/0/0, and it's a failed get request. Taking a look at the tiled images sharp created and I found that zoom folder 4 skips the y coordinate folders 0 and 1, and start from 2. Zoom folder 5 skips 0 to 3, and start from 4. Besides the get request errors I'm getting, leaflet looks to work just fine. I'm just wondering if it's intentional? If so, I would like to know why and if I can do anything about it to just get rid of the request errors?

```js
await sharp(filePath)
      .composite([{ input: Buffer.from('<svg><rect x="0" y="0" width="256" height="256" style="fill:rgb(0,0,0);fill-opacity:0.0;"></rect></svg>') }]) // add transparent background
      .png() // convert to png so transparency is preserved
      .tile({
        size: 256,
        background: { r: 256, g: 256, b: 256, alpha: 0 },
        center: true,
        basename: 'tiles',
        container: 'fs',
        layout: 'google'
      })
      .toFile(`uploads/${key}/map.png`)
```
Here's an example of the folders sharp creates
```
[0]
[1]
[2]
[3]
[4]
  [2]
  [3]
  ...
[5]
  [4]
  [5]
  ...
```

**Comment by GcodeG01** [comment]
Looking more into it, it's because sharp automatically removes blank tiles and that is why sometimes the couple of first Y and now realizing a couple of the last Y coordinates are not created (Double so, because I have the tile centered). I store my tiled files into AWS S3, so I'm not sure if it's better to just have get errors than to have a bunch of empty tiles stored in S3, but that's a problem for me.

**Comment by lovell** [comment]
The "google" layout changes the default `skipBlanks` from -1 to 5 to match the behaviour of libvips.

https://www.libvips.org/API/current/VipsForeignSave.html#vips-dzsave

However this was undocumented in sharp, sorry, and I have just updated this via commit https://github.com/lovell/sharp/commit/bc95531f2dcd4e6eb2b207016a390fb066b4461a

**Comment by GcodeG01** [comment]
Okay, thanks!
