### ISSUE TITLE
Overlay image repeats vertically in animated GIF

### ISSUE THREAD

**Issue by EjDadivas** [lovell/sharp#3992]
## Possible bug

When using the composite method with tile: true to add an overlay to an animated GIF, the overlay image repeats vertically across the GIF, creating a scrolling effect.

![thumbFile](https://github.com/lovell/sharp/assets/99721216/2dcfb451-cdb7-43a3-ad42-9ed7fba18035)

```
  const overlay = await sharp('assets/images/sample.png')
  .resize(imgMaxWidth)
  .toBuffer()



sharp(inputGif, { animated: true })
    .composite([{ input: overlay, tile: true, gravity: 'center' }])
    .toFormat("gif")
    .gif({ loop: 0, force: true })
    .toFile(outputGif)
    .catch(console.error);

```

**Comment by lovell** [comment]
You'll need to ensure the image to overlay is the same dimensions (or an exact multiple thereof).

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
