### ISSUE TITLE
is the output file size for both avif and webp the same if it was down-sized from an original image and the quality set to the same value?

### ISSUE THREAD

**Issue by jerrywoo96** [lovell/sharp#3996]
### What are you trying to achieve?

Trying to find out which format has the best algorithm in storing image data whilst having the highest quality.
Don't different algorithms have different ways of storing image data that results in different file sizes?
Even if I set the quality options to a lower value, both formats still produce the same hash.

### When you searched for similar issues, what did you find that might be related?

No issues found related to comparing webp and avif.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```
const image = sharp(filePath.realPath).rotate();
image.resize({ width: 2048, height: 2048, fit: sharp.fit.inside, withoutEnlargement: true, kernel: sharp.kernel.nearest });
const options = { quality: 100, lossless: false, effort: 0 };
const avif = image.avif(options); const webp = image.webp(options);
await Promise.all([avif.toFile(`${output}.avif`), webp.toFile(`${output}.webp`)]);
```

### Please provide sample image(s) that help explain this question

Both having the same hash also means both are the same size.

![image](https://github.com/lovell/sharp/assets/26324139/f682b4b7-36cd-47c6-9edd-fb6be591ad9f)

**Comment by lovell** [comment]
If you're generating multiple, varying outputs from the same input at the same time, you'll need to [clone](https://sharp.pixelplumbing.com/api-constructor#clone) the sharp instance to avoid a race condition.
```diff
- const avif = image.avif(options); const webp = image.webp(options);
+ const avif = image.clone().avif(options);
+ const webp = image.clone().webp(options);
```
