### ISSUE TITLE
Error occurs when trying to resize webp images

### ISSUE THREAD

**Issue by HyeokjinKang** [lovell/sharp#3999]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

System:
- OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
- CPU: (4) arm64 Neoverse-N1
- Memory: 16.87 GB / 23.30 GB
- Container: Yes
- Shell: 5.1.16 - /bin/bash

Binaries:
- Node: 20.5.1 - /usr/bin/node
- npm: 9.8.0 - /usr/bin/npm

npmPackages:
- sharp: ^0.33.2 => 0.33.2

### What are the steps to reproduce?

Code
```
const fileBuffer: Buffer = await sharp(filePath)
      .resize({ width, height })
      .toBuffer();
```

Output
<img width="696" alt="image" src="https://github.com/lovell/sharp/assets/63301941/baccf5db-e11f-44ca-80ee-dc06b92314f5">

### What is the expected behaviour?

The resized image buffer must be stored in the variable.

**Comment by HyeokjinKang** [comment]
Sorry. I should have found out more about this problem and left a PR, but I was hasty.
The problem was not from resize.
What I'm trying to do is resize the image, save it as webp, and retrieve the image and convert it to png.
The error occurs in toBuffer() after png conversion.

```
const sharp = require("sharp");
const fs = require("fs");

const filePath = "/path/to/file.webp";
const width = 256;
const height = 256;

const readFile = async () => {
  const fileBuffer = await sharp(filePath)
    .resize({ width, height })
    .webp({
      quality: 70,
      effort: 6,
    })
    .toBuffer();
  console.log("resize worked");
  fs.writeFile(filePath, fileBuffer, async (err) => {
    if (err) throw err;
    const buffer = await sharp(filePath).png().toBuffer();
    console.log("png worked");
  });
};

readFile();

```

Weird thing I found while trying to do this test is that this code works fine in some webp files, but an error occurs in other webp files.
Also, if this test code fails, re-executing this code will work fine again.
Where does the problem occur?

Among the files used in the test, I will also upload the webp file where the error occurred.
[test.zip](https://github.com/lovell/sharp/files/14349275/test.zip)

**Comment by lovell** [comment]
This line of code introduces a possible race condition.
```js
  fs.writeFile(filePath, fileBuffer, async (err) => {
```
