### ISSUE TITLE
npm install sharp fails

### ISSUE THREAD

**Issue by motiooon** [lovell/sharp#40]
$ npm install sharp
npm http GET https://registry.npmjs.org/sharp
npm http 304 https://registry.npmjs.org/sharp
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> sharp@0.4.2 install /Users/gabrielbaciu/projects/node-image-processing/node_modules/sharp
> node-gyp rebuild

  CXX(target) Release/obj.target/sharp/src/sharp.o
../src/sharp.cc:6:10: fatal error: 'vips/vips.h' file not found
# include <vips/vips.h>

```
     ^
```

1 error generated.
make: **\* [Release/obj.target/sharp/src/sharp.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Darwin 13.2.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/gabrielbaciu/projects/node-image-processing/node_modules/sharp
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
npm ERR! sharp@0.4.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.4.2 install script.
npm ERR! This is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "sharp"
npm ERR! cwd /Users/gabrielbaciu/projects/node-image-processing
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/gabrielbaciu/projects/node-image-processing/npm-debug.log
npm ERR! not ok code 0

**Comment by homerjam** [comment]
FWIW

I had xcode tools installed already and this did the job for me:

```
$ brew unlink vips && brew link vips
```
I got a warning so did this afterward as directed:
```
$ brew link --overwrite vips
