### ISSUE TITLE
Error: Could not load the "sharp" module using the linux-x64 runtime on AWS Lambda

### ISSUE THREAD

**Issue by tpamsler** [lovell/sharp#4001]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

Cannot run above command as it's executed on AWS Lambda nodejs20.x

### What are the steps to reproduce?

Execute lambda on AWS Lambfda

### What is the expected behaviour?

Lambda function should load "sharp" image library without arrores

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

const sharp = require('sharp');

### Please provide sample image(s) that help explain this problem

{
  "errorType": "Error",
  "errorMessage": "Could not load the \"sharp\" module using the linux-x64 runtime\nPossible solutions:\n- Ensure optional dependencies can be installed:\n    npm install --include=optional sharp\n    yarn add sharp --ignore-engines\n- Ensure your package manager supports multi-platform installation:\n    See https://sharp.pixelplumbing.com/install#cross-platform\n- Add platform-specific dependencies:\n    npm install --os=linux --cpu=x64 sharp\n- Consult the installation documentation:\n    See https://sharp.pixelplumbing.com/install",
  "trace": [
    "Error: Could not load the \"sharp\" module using the linux-x64 runtime",
    "Possible solutions:",
    "- Ensure optional dependencies can be installed:",
    "    npm install --include=optional sharp",
    "    yarn add sharp --ignore-engines",
    "- Ensure your package manager supports multi-platform installation:",
    "    See https://sharp.pixelplumbing.com/install#cross-platform",
    "- Add platform-specific dependencies:",
    "    npm install --os=linux --cpu=x64 sharp",
    "- Consult the installation documentation:",
    "    See https://sharp.pixelplumbing.com/install",
    "    at Object.<anonymous> (/var/task/node_modules/sharp/lib/sharp.js:114:9)",
    "    at Module._compile (node:internal/modules/cjs/loader:1376:14)",
    "    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)",
    "    at Module.load (node:internal/modules/cjs/loader:1207:32)",
    "    at Module._load (node:internal/modules/cjs/loader:1023:12)",
    "    at Module.require (node:internal/modules/cjs/loader:1235:19)",
    "    at require (node:internal/modules/helpers:176:18)",
    "    at Object.<anonymous> (/var/task/node_modules/sharp/lib/constructor.js:10:1)",
    "    at Module._compile (node:internal/modules/cjs/loader:1376:14)",
    "    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)"
  ]
}

**Comment by tpamsler** [comment]
Update: Following the execution of `npm install --cpu=x64 --os=linux sharp` on my development system prior to deploying the code to AWS Lambda using Serverless Framework, everything is now functioning correctly.

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/install#aws-lambda
https://sharp.pixelplumbing.com/install#cross-platform

If you still require help, please open [a new installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) and answer all of the questions.

**Comment by eudoroolivares2016** [comment]
I am seeing the same issue @tpamsler you mentioned that as the solution but, for me running the `npm install --cpu=x64 --os=linux sharp` does not result in any changes to my package-lock file but, my development machine is macOs and I am using `"sharp": "^0.33.2"` what version of `sharp` are you using?

**Comment by eudoroolivares2016** [comment]
My result from `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp` is 
` System:
    OS: macOS 13.6.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 142.20 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
  npmPackages:
    sharp: ^0.33.2 => 0.33.2`
    So I believe that something is blocking the install from occurring as expected

**Comment by tpamsler** [comment]
I just ran `npm install --cpu=x64 --os=linux sharp` before deploying the lambda to AWS via `serverless deploy ...` and it had the correct binary in node_mudules during the deploy.

**Comment by eudoroolivares2016** [comment]
@tpamsler if you run that on your local machine or otherwise if you can see what went into the lambda, do you see what hte binaries are in the node_modules. Going into the node_modules/@img I see `sharp-darwin-x64         sharp-libvips-darwin-x64` but, I actually see the linux values: `node_modules/@img/sharp-libvips-linux-arm` and others in my package-lock file as I have run that same npm install targeted for linux

**Comment by tpamsler** [comment]
Here is what I have in my ***@***.***
```
sharp-darwin-arm64
sharp-libvips-darwin-arm64
sharp-libvips-linux-x64
sharp-libvips-linuxmusl-x64
sharp-linux-x64
sharp-linuxmusl-x64
```

**Comment by eudoroolivares2016** [comment]
Would you mind posting your package.json and/or package-lock.json file. I'm interested if there are any diffs between. I can get these linux binaries by doing a `npm install --force @img/sharp-linux-x64` etc. But, that is not good practice. It also leads to issues because then it'll try to install those on the dev machine and fail.

**Comment by tpamsler** [comment]
[package-lock.json](https://github.com/lovell/sharp/files/14389631/package-lock.json)
[package.json](https://github.com/lovell/sharp/files/14389632/package.json)

**Comment by trippingcats** [comment]
I hope this helps somebody: For me installing the packages manually was the only way to make it work on AWS, I am using Sharp v0.33.4, this it is probably not a good practice (as mentioned) but at least it works. 

```
npm install @img/sharp-darwin-arm64 @img/sharp-libvips-darwin-arm64 @img/sharp-libvips-linux-x64 @img/sharp-libvips-linuxmusl-x64 @img/sharp-linux-x64 @img/sharp-linuxmusl-x64 --force
```

**Comment by mattiLeBlanc** [comment]
@lovell 
Hi, I am having trouble using Sharp on a nodejs Lambda. 
it runs fine locally but when I add Sharp to my lambda layer for deploy, it is missing the linux runtime:
```
Could not load the \"sharp\" module using the linux-x64 runtime\nPossible solutions:\n- Ensure optional dependencies can be installed:\n    npm install --include=optional sharp\n- Ensure your package manager supports multi-platform installation:\n    See https://sharp.pixelplumbing.com/install#cross-platform\n- Add platform-specific dependencies:\n    npm install --os=linux --cpu=x64 sharp\n- Consult the installation documentation:\n    See https://sharp.pixelplumbing.com/install",
```

If I install the linux runtime, I can't build it locally because my npm will compain about these incompatible runtimes.
So I am adding those runtimes to `optionalDepedencies`  and see if that works.
But what is the best practice for my situation?

**Comment by amarsyla** [comment]
@mattiLeBlanc I've tried every single workaround mentioned here and anywhere else and nothing worked for me. The only thing that worked was adding sharp as a lambda layer.

**Comment by mattiLeBlanc** [comment]
@amarsyla yeah, I am using lambda layers. But I have 2 ways of installing:
1) deploy locally via CDK deploy on my Mac M1 machine. This will install the arm64 lib and I can run the lambda index locally and it resizes, works like a charm. But when I deploy, it deploys the wrong binaries to the lambda layer.
2) deploy via bitbucket, which I am trying now and that should run on a linux container, so hopefully that deploys the correct binaries via npm.

However, I would like to deploy locally from my mac to Lambda, with the correct binaries for lambda. Maybe that is not possible atm, hence my question to @lovell

**Comment by lovell** [comment]
> If I install the linux runtime, I can't build it locally because my npm will compain about these incompatible runtimes.

https://sharp.pixelplumbing.com/install#cross-platform
https://sharp.pixelplumbing.com/install#aws-lambda

The summary is that if you're attempting to run multiple/cross-platform then it's best to use a package manager that supports it. Most other approaches will involve you fighting against your choice of package manager.

**Comment by amarsyla** [comment]
@mattiLeBlanc Instead of building the binaries for the lambda layer I am using prebuilt packages:

https://github.com/pH200/sharp-layer

This is working great regardless of the deployment method.

**Comment by mattiLeBlanc** [comment]
@lovell I am using npm.
I am not really sure how to deal with cross platform. The article in the docs is very limited, I have to choose between 2 platforms it seems.

I guess what I want is to force the lambda layer package.json (npm) to always install the linux runtime because that is what is deployed to the lambda.
In the root of my mono repo, I have one package.json for all depedencies and there I can use the arm64 version because those are my local packages and the sharp would be a devDepedencies only.

Is that possible?

**Comment by mattiLeBlanc** [comment]
> @mattiLeBlanc Instead of building the binaries for the lambda layer I am using prebuilt packages:
> 
> https://github.com/pH200/sharp-layer
> 
> This is working great regardless of the deployment method.

@amarsyla thank you for this. 
I am not sure how to implement this atm (it is late at night here and my brain is cooked).
I am creating my lambda layers atm in my CDK project, installing the deps in the nodejs folder so how would I use this prebuild layer? Just upload the zip to my layers in AWS and reference it?

**Comment by amarsyla** [comment]
@mattiLeBlanc I am not exactly sure as I am using the serverless framework which makes things easier, but I'm assuming uploading the zip layer and attaching it to the function should do it. I am using [release-x64.zip](https://github.com/pH200/sharp-layer/releases/tag/0.33.5). I am also on a Mac M1 and this has been working great for me. I have also locked the `sharp` version to `0.33.5` in `package.json` to make sure I'm using the same version both locally and in the lambda function.

**Comment by mattiLeBlanc** [comment]
@amarsyla 
okay, I will have a look. Thanks for the suggestion.

**Comment by mattiLeBlanc** [comment]
@amarsyla 
Okay, I am using the zip file now. I just modified my CDK deployment slightly to support either installed node_modules or a zip archive. It works as a charm. Thanks for the suggestion,

**Comment by renanbronchart** [comment]
I found an other solution works weel for me.

1. Install latest nodejs@20 version (Change by the same than lambda node version)
    
    [https://nodejs.org/en/download](https://nodejs.org/en/download)
    Make sure you have the right path to node in you `.zshrc` or `.bash_profile`
    `export PATH=$HOME/bin:/usr/local/bin:$PATH`
    
2. remove package-lock.json
    
3. remove node_modules

4. remove dist folder in your lambda function folder
    
5. remove cache:
`npm cache clean --force` 

6. Add pre-install in `scripts` in `package.json` and replace target by lambda version of node and same architecture than lambda architecture.

`"preinstall": "npm install --platform=linux --arch=x64 --target=20x sharp@0.32.6"` 

1. Install and force sharp with linux configuration (like lambda configuration)

`npm install --platform=linux --arch=x64 --target=20x sharp@0.32.6 --force`

**Comment by remithomas** [comment]
I did what @amarsyla suggests by downloading this file https://github.com/pH200/sharp-layer/releases/tag/0.33.5 and I moved the file to an other directory `node22` for my case. So it is like this `/nodejs/node22/node_modules/`

**Comment by hongminpark** [comment]
> I did what @amarsyla suggests by downloading this file https://github.com/pH200/sharp-layer/releases/tag/0.33.5 and I moved the file to an other directory `node22` for my case. So it is like this `/nodejs/node22/node_modules/`

Thanks........... Spent whole day and this was the final workaround

**Comment by sher85** [comment]
I, too, did what @amarsyla suggested and it worked. My process was:

1. Download the [release-x64.zip](https://github.com/pH200/sharp-layer/releases/download/0.33.5/release-x64.zip) zip file to my local computer.
2. Create a layer named `sharp` in AWS set to `node 18.x` and `x86_64` and upload the zip file.
3. Tie that layer into my lambda function.
4. This is what my import looks like in my index.js file and I don't have any libraries in my package.json/package-lock.json:

`import sharp from 'sharp'`

**Comment by admin8756** [comment]
I’m encountering the following error when trying to run the bundled `index.js` file after using `ncc` to package the project:

```
Error: Could not load the "sharp" module using the darwin-arm64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=darwin --cpu=arm64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
```

The application works fine during development, but after packaging with `ncc`, it fails to run. I'm using `pnpm` for dependency management and have bundled the project with `ncc`. I couldn't find a detailed explanation in the `ncc` documentation regarding how to handle platform-specific dependencies like `sharp`.

I’ve tried some of the possible solutions mentioned in the error message (e.g., installing `sharp` with the `--include=optional` flag), but it doesn’t seem to resolve the issue. 

Could anyone help with this? Maybe provide some guidance on how to configure `ncc` or resolve this platform-specific problem?

Thanks in advance!

**Comment by lovell** [comment]
@admin8756 https://github.com/vercel/ncc/issues/1153
