### ISSUE TITLE
Checksum and flle size difference on Apple chip Macs vs Linux and Windows

### ISSUE THREAD

**Issue by shaunflagg** [lovell/sharp#4004]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [X ] Running `npm install sharp` completes without error.
- [ X] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [X ] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

System:
    OS: macOS 14.3
    CPU: (12) arm64 Apple M3 Pro
    Memory: 36.59 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.2 - ~/.nvm/versions/node/v21.6.2/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.6.2/bin/npm

### What are the steps to reproduce?

Apply resize to an image file such as a png or jpg. Generate the md5 checksum. Run the same process on the same image on Mac and Windows. The checksum will differ and likely this is because the file size differs. I checked metadata bytes and they match.

### What is the expected behaviour?

Checksums and file sizes should match across operating systems.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```
const sharp = require('sharp');
const fs = require('fs');
const crypto = require('crypto');

// Function to process image, resize it, and generate an MD5 checksum
async function resizeAndChecksum(imagePath) {
    console.log("Processing Image:", imagePath);

    // Read image buffer from the given image path
    const imageBuffer = fs.readFileSync(imagePath);

    // Resize the image to 192x108
    const resizedImageBuffer = await sharp(imageBuffer)
        .resize(192, 108)
        .withMetadata()
		.toBuffer();

    // Generate MD5 checksum of the resized image
    const checksum = crypto.createHash('md5').update(resizedImageBuffer).digest('hex');
    console.log("MD5 Checksum:", checksum);

    // Optional: Save the resized image to disk
    fs.writeFileSync('output/' + `resized_${Date.now()}.jpg`, resizedImageBuffer);

    return { checksum };
}

// Taking input from the terminal
const imagePath = process.argv[2];
if (!imagePath) {
    console.log("Please provide an image path.");
    process.exit(1);
}

resizeAndChecksum(imagePath)
    .then(result => console.log("Finished processing. Checksum:", result.checksum))
    .catch(err => console.error("Error processing image:", err));
```

### Please provide sample image(s) that help explain this problem

Any image off the internet will work but you can try this one https://www.pexels.com/photo/white-and-grey-kitten-on-brown-and-black-leopard-print-textile-45201/

**Comment by lovell** [comment]
There will be small differences in SIMD behaviour/rounding on different CPUs within various libraries upon which libvips depends (zlib-ng, libjpeg-turbo, highway etc.), which would explain why you're seeing slightly different checksums for the *compressed* pixel data. Perhaps you could look at *uncompressed*, raw pixel data if you need to compare images cross-platform.

See also https://github.com/lovell/sharp/issues/3783

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
