### ISSUE TITLE
Memory allocation failed

### ISSUE THREAD

**Issue by innxz** [lovell/sharp#4009]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

>   System:
>     OS: macOS 14.0
>     CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
>     Memory: 33.33 MB / 16.00 GB
>     Shell: 5.9 - /bin/zsh
>   Binaries:
>     Node: 20.8.1 - /usr/local/bin/node
>     npm: 10.1.0 - /usr/local/bin/npm
>   npmPackages:
>     sharp: ^0.33.2 => 0.33.2 

### What is the expected behaviour?

I am trying to convert a large SVG image to PNG. The original image size is around 29 megabytes, but I am encountering an error "Error: Input buffer has corrupt header: glib: XML parse error: Error domain 1 code 2 on line 1 column 10000601 of data: Memory allocation failed." Adding the flag --max-old-space-size=8096 does not provide any results.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```js
const sharp = require('sharp');
const fs = require('fs');

const inputFile = 'output.svg';
const outputFile = 'output.png';

const readStream = fs.createReadStream(inputFile);
const writeStream = fs.createWriteStream(outputFile);

readStream.pipe(sharp().resize(800, 600).png()).pipe(writeStream);

writeStream.on('finish', () => {
  console.log('Image processed successfully');
});

writeStream.on('error', (err) => {
  console.error('Error processing image:', err);
});
```

### Please provide sample image(s) that help explain this problem

` <?xml version="1.0" encoding="utf-8"?><!DOCTYPE svg  PUBLIC '-//W3C//DTD SVG 1.1//EN'  'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'><svg height="3248" version="1.1" viewBox="0 0 4724 3248" width="4724" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g><rect height="3248" style="fill: #ffffff;" width="4724"/></g><g transform="matrix(0.9838957055214724 0.0 0.0 0.9838957055214724 2362.0 1624.0)"><image height="3301" pipe="[{&quot;name&quot;: &quot;instagram&quot;}]" transform="scale(-1,1)" width="4800" x="-2400.0" y="-1650.5" xlink:href="data:image/png;base64,BIG-PNG-HERE">`
<img width="173" alt="Снимок экрана 2024-02-26 в 16 57 24" src="https://github.com/lovell/sharp/assets/20569655/5c748fce-df49-487f-b822-0c5b8706de64">

**Comment by lovell** [comment]
> xlink:href="data:image/png;base64,BIG-PNG-HERE

Did you see #3979?

**Comment by innxz** [comment]
I apologize for not seeing this topic. But in any case, I didn't quite understand the algorithm of actions.

**Comment by lovell** [comment]
Other than provide more RAM, #3979 provides the only known possible solution, namely to preprocess SVGs to detect when memory exhaustion might otherwise happen.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
