### ISSUE TITLE
WebP "nearLossless" ignores "quality" value

### ISSUE THREAD

**Issue by Juraj-Masiar** [lovell/sharp#4010]
### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i7-13700K
    Memory: 25.80 GB / 63.69 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: ^0.33.2 => 0.33.2

### What are the steps to reproduce?
Run this:
```js
const img1 =
  sharp({
    create: {
      width: 48,
      height: 48,
      channels: 4,
      background: { r: 255, g: 0, b: 0, alpha: 0.5 }
    }
  })
    .webp({quality: 20, nearLossless: true, effort: 6})
    .toBuffer();

const img2 =
  sharp({
    create: {
      width: 48,
      height: 48,
      channels: 4,
      background: { r: 255, g: 0, b: 0, alpha: 0.5 }
    }
  })
    .webp({lossless: true, effort: 6})
    .toBuffer();

Promise.all([img1, img2]).then(([img1, img2]) => {
  // compare if the images are the same
  console.log('Images are equal:', img1.equals(img2)); // true
});
```

### What is the expected behaviour?

It should print "false".
No matter what quality value I set, the result image is still the same as if the lossless is used.

Blog for the webp nearLossless feature:
https://groups.google.com/a/webmproject.org/g/webp-discuss/c/0GmxDmlexek

**Comment by lovell** [comment]
The near-lossless feature of libwebp acts as a pre-processor to lossless output and I suspect for these synthetic, plain images it won't be able to make much if any difference to that output.

Do you see the same behaviour from non-synthetic images such as photos or diagrams?

**Comment by Juraj-Masiar** [comment]
I've originally noticed it on a few small favicons and the result was always the same. 
For example:
![uMxFgBQ7p](https://github.com/lovell/sharp/assets/6358971/f38c6b0e-5de5-4d35-8756-0f0284f3a332)
(this is a webp image named as ".png" to allow upload to github :))

**Comment by Juraj-Masiar** [comment]
Oh, you were right. Using much more complex image will make a difference.
But for many icons/logos it will make no difference. That's super weird!

I'm sorry for bothering :)

**Comment by lovell** [comment]
It looks like the near-lossless feature is skipped for small dimensions:

https://github.com/webmproject/libwebp/blob/1fb9f3dcf18b2aff35dcb7a8f6fa4a6c756efb75/src/enc/near_lossless_enc.c#L125
