### ISSUE TITLE
Assigning metadata to color and non-color images

### ISSUE THREAD

**Issue by donmccurdy** [lovell/sharp#4011]
### What are you trying to achieve?

In 3D rendering use cases, it's common to have a collection of images (see: ["textures"](https://www.artstation.com/blogs/luismesquita/PwEm/everything-about-pbr-textures-and-a-little-more-part-1)) mapped onto the surface of a 3D model. Some of those textures represent color of the surface, sRGB-encoded. Other textures encode non-color data describing physical properties of the surface: roughness, specular reflectivity, etc.

In these 3D models, images' embedded color space metadata is frequently nonsense. Images with non-color data may be contain sRGB profiles, and images with color data may lack a color profile.

An open source tool I'm maintaining (https://gltf-transform.dev/) optimizes 3D models, including compressing their images using Sharp. Based on contextual use of the image, my software already knows whether each image is actually color or non-color data.  I'd like to assign that metadata — identifying sRGB or non-color data — to the optimized image without converting any pixel values, ideally using Sharp.

### When you searched for similar issues, what did you find that might be related?

I raised a question in https://github.com/lovell/sharp/issues/1323#issuecomment-1953037162 about this, thinking that the following code might work:

```javascript
await sharp(input, {ignoreIcc: true})
 .toColourspace('rgb')
 .toFile('output.png')
```

From your response, it sounds like I have misunderstood the API and how to identify non-color data. Are you aware of any way to differentiate color and non-color images, and is it possible to assign that sort of metadata to images using Sharp? Or is there no standard way to identify that the RGB channels in a PNG / JPEG / WebP image do not represent color information?

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

See above.

### Please provide sample image(s) that help explain this question

See the four images in this folder:

https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/AnisotropyBarnLamp/glTF

Only the image with the `_basecolor` suffix contains color data, but I don't think there's anything in the metadata to differentiate them currently.

**Comment by lovell** [comment]
>  I'd like to assign that metadata — identifying sRGB or non-color data — to the optimized image without converting any pixel values, ideally using Sharp.

sharp will always perform a decode/encode roundtrip. If you need to "set" an ICC profile without changing any pixel data then perhaps try exiftool.

https://exiftool.org/forum/index.php?topic=1958.0
https://www.npmjs.com/package/exiftool-vendored

**Comment by donmccurdy** [comment]
@lovell the decode/encode round-trip is OK! I do understand that requirement with Sharp. It would still be nice to be able to tell Sharp what the pixel data color space _already is_, if I know the metadata in the image is unreliable. But if that's out of scope for Sharp and exiftool should be used instead, no worries.

**Comment by lovell** [comment]
> is there no standard way to identify that the RGB channels in a PNG / JPEG / WebP image do not represent color information?

Not that I'm aware of. Are you mostly interested in lossless formats? PNG and lossless-WebP are RGB-only.

There is a standard EXIF tag named `PhotometricInterpretation` that supports values such as "RGB", "Transparency Mask" and "Depth Map".

https://exiftool.org/TagNames/EXIF.html

**Comment by donmccurdy** [comment]
Still "RGB" or "RGBA" in the sense that there are exactly 3-4 channels containing 8-bit values. But not representing any red/green/blue tristimulus, it is just data.

The only image format I'm closely familiar with is [KTX2](https://github.khronos.org/KTX-Specification/ktxspec.v2.html), which separately defines 'colorPrimaries' and 'transferFunction' properties. For my purposes I would normally set transferFunction=LINEAR and colorPrimaries=UNSPECIFIED.

It sounds like that's perhaps not the usual way color spaces are represented in image formats, though, and there is no particular way to represent "not a color" in JPG/PNG/WebP/AVIF/...?. I may need to ask browser vendors, then, if there's something one can put into an image that will prevent the browser from assuming sRGB and trying to convert to the shared [unpackColorSpace](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/unpackColorSpace).

In any case, there doesn't seem to be anything much Sharp can/should do here – thank you for your time and responses!

**Comment by lovell** [comment]
No worries, sorry I couldn't be more helpful. It's an interesting problem so good luck trying to solve this (and, if you do, I'd be keen to learn how).

**Comment by JannetGen** [comment]
This feels a lot like an ICC/profile handling difference somewhere between the original image, Sharp/libvips processing, and the final viewer/browser. I’ve seen cases where the pixel data was technically unchanged but the displayed colors still shifted because the embedded profile got stripped or converted unexpectedly.
One thing that helped me debug similar issues was comparing sampled pixel values before and after processing instead of only checking visually. I used [https://colorpickerimage.org/](https://colorpickerimage.org/) a couple of times for quick RGB/hex checks on exported images and it made it easier to confirm whether the data itself was changing or just the rendering.
