### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "transform.writable" property must be an instance of WritableStream. Received an instance of Sharp

### ISSUE THREAD

**Issue by antony** [lovell/sharp#4013]
Hi - great to meet you in person last night!

As discussed, here's the "possible bug" - may just be a documentation issue - or probably just a usage issue ;)

This code worked previously on a much older version of Sharp using body.pipe. The documentation states that you can construct Sharp with no arguments and pipe to it - so it seems that it should work.

The end goal is to stream directly from the source data, through an image transform, and out to the user - where the transformed image would get cached on the edge.

### Is this a possible bug in a feature of sharp, unrelated to installation?

- [X] Running `pnpm install sharp` completes without error.
- [X] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [X] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
  npmPackages:
    sharp: 0.33.0 => 0.33.0 
```

### What are the steps to reproduce?

1. Fetch image but don't consume body
2. Attempt to pipe fetch body to sharp.

### What is the expected behaviour?

The body data is piped to sharp which then runs transforms

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

[StackBlitz](https://stackblitz.com/edit/sveltejs-kit-template-default-ea5vps?file=src%2Froutes%2F%2Bserver.js)

**Comment by lovell** [comment]
Hi Antony, great to meet you too.

The `body` property provided by `fetch()` is a `ReadableStream`, which is somewhat confusingly part of the Web API rather than the Node.js Stream API. You can convert it to a `Readable` (i.e. a Node.js Stream) using [Readable.fromWeb()](https://nodejs.org/api/stream.html#streamreadablefromwebreadablestream-options).

```diff
-   const resizedImage = imageRes.body.pipeTo(transformer);
+   const resizedImage = Readable.fromWeb(imageRes.body).pipe(transformer);
```

I'll add an example to the docs as I suspect you won't be the only person who runs into this.

**Comment by antony** [comment]
Gotcha! This must have changed between node 16 and 20 which is why I suddenly ran into it.

I did see that there were two distinct types of stream, but the error thrown by node doesn't indicate the two types, but instead that the arg is a `Sharp` which masks the real issue!

Thank you for looking into this :)

**Comment by lovell** [comment]
Commit https://github.com/lovell/sharp/commit/045d54e2e62f14c3658ab246c760f8c4da28b303 modernises one of the existing examples in the docs to include use of `fetch()` and `.fromWeb()`.
