### ISSUE TITLE
Sharp not compressing image with resolution 

### ISSUE THREAD

**Issue by sujithnath** [lovell/sharp#4014]
Hello all, I am facing an issue. When I am trying to compress images with the higher resolution given below, sharp ignores it. Any idea why?

17783 × 7024 px
Rendered aspect ratio:	17783∶7024
File size:	16.1 MB

At the same time, compression with other images works.
sharp(buffer).webp({ quality: 1 }).toBuffer();

**Comment by lovell** [comment]
- Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem
- Please provide sample image(s) that help explain this problem

These questions were in the issue template but were ignored/deleted.

**Comment by sujithnath** [comment]
Hello, 

Thanks for the reply and I figured out the issue. Webp cannot process images that are higher in resolution. I guess more than 15000 px in width and height.

Sorry I had no choice to include image or more of the data due to compliance.

**Comment by lovell** [comment]
https://developers.google.com/speed/webp/faq#what_is_the_maximum_size_a_webp_image_can_be

> The maximum pixel dimensions of a WebP image is 16383 x 16383.

**Comment by jo-chemla** [comment]
Note cwebp (which powers libvips which powers sharp) can convert 16383² images (for example simple conversion jpeg -> webp), see reference [libvips thread](https://github.com/libvips/libvips/issues/3568#issuecomment-2074270144)
