### ISSUE TITLE
Usage of minSize in webp

### ISSUE THREAD

**Issue by ThomasKwan-shopline** [lovell/sharp#4017]
### What are you trying to achieve?

Hi, I am solving a issue on animated webp image and found there is a parameter `minSize` on `webp` output method. After study the related issue, I want to clarify the use of `minSize`. By the document, the description for `minSize` is "prevent use of animation key frames to minimise file size (slow)". Is this mean that

1. when minSize is True, so no animation key frames used and file size will lower
2. when minSize is False, animation key frames used and file size will higher

### When you searched for similar issues, what did you find that might be related?

- [Usage of minSize in webp](https://github.com/lovell/sharp/issues/3863)

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

N/A

### Please provide sample image(s) that help explain this question

N/A

**Comment by lovell** [comment]
The short answer is "mostly yes", the longer answer is to look at how `minimize_size`, `kmin` and `kmax` interact in the following places:

https://developers.google.com/speed/webp/docs/container-api#webpanimencoder_api

https://github.com/webmproject/libwebp/blob/1fb9f3dcf18b2aff35dcb7a8f6fa4a6c756efb75/src/mux/anim_encode.c#L129-L131

https://github.com/webmproject/libwebp/blob/1fb9f3dcf18b2aff35dcb7a8f6fa4a6c756efb75/src/mux/anim_encode.c#L119-L122

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
