### ISSUE TITLE
Is there another operation than composite to apply a highlighted rectangle to an image?

### ISSUE THREAD

**Issue by micronaut** [lovell/sharp#4024]
### What are you trying to achieve?

I want to highlight certain words in an image and crop and scale the image.  When I use composite with resize, since the coordinates for the highlight are based on the full-size image and composite is not applied first, the highlight is incorrectly placed. I can use toBuffer after composite to force it to happen, but this seems to impact the performance . Thanks! 

### When you searched for similar issues, what did you find that might be related?

I found this other related issue https://github.com/lovell/sharp/issues/3775

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/api-composite

> Any resize, rotate or extract operations in the same processing pipeline will always be applied to the input image before composition.

As you've suggested, using two pipelines is probably the right approach here. You could use raw, uncompressed pixel data for the intermediate image to avoid any compression/decompression roundtrip.

**Comment by micronaut** [comment]
Thanks @lovell . Can you give an example of using uncompressed pixel data?  Is that just a raw buffer, by not applying and format?
