### ISSUE TITLE
sharp is not compatible with the Node :- 17.9.1 NPM :-  8.11.0 

### ISSUE THREAD

**Issue by ramanabhinav7** [lovell/sharp#4026]
## Feature request
installation and compatibility
### What are you trying to achieve?
user should install easily

sharp is not compatible with the Node :- 17.9.1 NPM :-  8.11.0  version that need to be fiexed
### When you searched for similar feature requests, what did you find that might be related?
currently consumed into it.

no sharp version is compatible with these versions Node :- 17.9.1 NPM :-  8.11.0 
### What would you expect the API to look like?
api should be same as previous but it should start working with node 17.9.1 and npm 8.11.0

**Comment by lovell** [comment]
Node.js 17 reached end-of-life in 2022, please upgrade.

**Comment by ramanabhinav7** [comment]
Ok thanks for your reply.
