### ISSUE TITLE
 When you use sharp to convert svg to png, something is missing!

### ISSUE THREAD

**Issue by front-zero** [lovell/sharp#4027]
If you use satori to create an svg and then transform that svg to a png, there will be something missing. What should I do to solve this?

- result svg

![image](https://github.com/lovell/sharp/assets/96212261/d2a5a0eb-6a63-4262-b362-9004de83c4c7)

- result png

![image](https://github.com/lovell/sharp/assets/96212261/30df3e90-d943-4272-9256-82808ce792a3)

- attach svg file

![result](https://github.com/lovell/sharp/assets/96212261/58340113-6fb6-49f3-a9ce-7c94acc3e1af)

**Comment by ramanabhinav7** [comment]
but i am not able to download you png file please give your code and png file link so that i can check and test, it would be easy , because i got a chance to work on sharp i think i could help you.:)

**Comment by lovell** [comment]
This SVG contains nested, inline SVG images, which are unsupported.

> <image x="582" y="541" width="36" height="36" href="data:image/svg+xml;utf8,%3Csvg  xmlns= ...

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by kacem22** [comment]
@front-zero What do you use to convert an SVG from Satori to PNG using Sharp? I got this error: 'Input buffer contains unsupported image format' with this code:
`

    const markup = await html`<div style="color: red;">hello ${username}</div>`;
    const svg = await satori(markup, {
      width: 600,
      height: 500,
      fonts: [
        {
          name: 'Inter',
          data: await inter,
          weight: 400,
          style: 'normal',
        },
      ],
    });
    // console.log(svg);
    // Convert SVG string to buffer
    const svgBuffer = Buffer.from(svg, 'utf-8');
    // Convert SVG to PNG using sharp
    const pngBuffer = await sharp(svgBuffer)
      .png() // Convert to PNG (you can change to .jpeg() for JPEG)
      .toBuffer();
`
