### ISSUE TITLE
Using `clone` and `joinChannel` together apply channel operation to all output

### ISSUE THREAD

**Issue by nzh63** [lovell/sharp#4029]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 6800H with Radeon Graphics
    Memory: 5.66 GB / 13.69 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 4.1.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: ^0.33.2 => 0.33.2
```

### What are the steps to reproduce?

1. Create a sharp stream, then use `clone` to create three output.
2. Apply a `joinChannel` operation (add a alpha channel) to one of the output.
3. Use `fs.createReadStream` to create a readable stream, then pipe it to sharp.
4. We can observe that the function `joinChannel` has been applied to all of the output. Every output has an alpha channel.

### What is the expected behaviour?

Using `joinChannel` after `clone` should only affect one output. The rest outputs should not have an alpha channel.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```js
const fs = require('fs');
const sharp = require('sharp');

(async function () {
  let img = sharp({
    create: {
      width: 1000,
      height: 1000,
      channels: 3,
      background: '#f00'
    }
  });
  await img.toFile('img.png');
  let circle = sharp(Buffer.from('<svg><circle cx="500" cy="500" r="500" fill="white" /></svg>'));
  let alpha = await circle.extractChannel(0).png().toBuffer();

  let sharpStream = sharp();
  sharpStream.clone().grayscale().toFile('img-grayscale.png'); // bug? expect to get a gray rect, but get a gray circle
  sharpStream.clone().joinChannel(alpha).toFile('img-alpha.png'); // ok, get a red circle with alpha channel
  sharpStream.clone().toFile('img-do-nothing.png'); // bug? expect to get a red rect, but get a red circle

  fs.createReadStream('img.png').pipe(sharpStream);
})();
```

I also try the flowing code. It doesn't work, too.

```js
const sharp = require('sharp');

(async function () {
  let img = sharp({
    create: {
      width: 1000,
      height: 1000,
      channels: 3,
      background: '#f00'
    }
  });
  let circle = sharp(Buffer.from('<svg><circle cx="500" cy="500" r="500" fill="white" /></svg>'));
  let alpha = await circle.extractChannel(0).png().toBuffer();

  await img.clone().grayscale().toFile('img-grayscale.png'); // ok, get a gray rect
  await img.clone().joinChannel(alpha).toFile('img-alpha.png'); // ok, get a red circle with alpha channel
  await img.clone().toFile('img-do-nothing.png'); // bug? expect to get a red rect, but get a red circle
})();
```

### Please provide sample image(s) that help explain this problem

None. All image is create by the code above.

**Comment by lovell** [comment]
Thanks for reporting, I can reproduce this locally. The `joinChannel` operation stores channels in an array. However during `clone()` only a shallow copy is taken, leading to the array of channels being shared by all siblings.

Commit https://github.com/lovell/sharp/commit/7bc74feb113b5f34e7bdc0fe2de4b50820e4a4b2 switches to a deep copy and adds a test that would previously have failed.

**Comment by lovell** [comment]
v0.33.3 now available with the fix, thanks again for reporting this.
