### ISSUE TITLE
Issues during size scaling of images (mostly occurs with jpeg)

### ISSUE THREAD

**Issue by hyatt03** [lovell/sharp#403]
I have a hard time describing the issue, so I've attached an example instead:

![a333e056b387-48e8-8265-d2f96531b354_large](https://cloud.githubusercontent.com/assets/2140680/14380767/a08ebaa0-fd81-11e5-9086-ea8a0070f180.jpg)

As you can see, it seems an issue occurs while scaling jpeg images, however it's not a consistent issue, and libvips throws warnings when it happens. For example

```
vips warning: VipsJpeg: read gave 2 warnings
vips warning:
Assertion failed: (loop->watchers[w->fd] == w), function uv__io_stop, file ../deps/uv/src/unix/core.c, line 864.
Program node main.js exited with code null
```

If I can listen for these warnings, that would be sufficient.
Here is the original image:
![a333e056b387-48e8-8265-d2f96531b354](https://cloud.githubusercontent.com/assets/2140680/14380822/09685efa-fd82-11e5-8ed2-4178ce149b6b.jpg)

It seems to occur in about 0.6% of scaling jobs, for reference here is the code I use to scale the image (edited for brevity):
```
let imageObject = sharp(fileobj.name);
        imageObject.metadata().then((metadata) => {
          if (metadata.orientation) {
            imageObject.rotate();
          }

          return imageObject;
        }).then((image) => {
          imageObject = image;

          if (width && height) {
            imageObject.resize(width, height).withoutEnlargement();
          }
          else {
            imageObject.resize(width).max().withoutEnlargement();
          }

          imageObject.toBuffer()
            .then(function (outputBuffer) {
              logger.info('finished image transcoding job', {
                    size: width && height ? `${width}x${height}` : `${width}x${width}`,
                    data: job.data
                  });
                }
              );
            })
            .catch(function (err) {
              done();
              logger.error('an error occurred while transcoding image', {job: job.data, error: err});
            });
        }).catch((err) => {
          done();
          logger.error('an error occurred while transcoding image', {job: job.data, error: err});
        });
```

**Comment by lovell** [comment]
> "Assertion failed: (loop->watchers[w->fd] == w), function uv__io_stop, file ../deps/uv/src/unix/core.c, line 864."

Hello, this is an error I've not seen before.

The `vips warning` messages and the truncated JPEG suggest there might have been an unclean thread shutdown, possibly based on a fatal error in another thread.

Could `main.js` be dependent on any other modules that deal with file watching or hot-reloading? Are you able to share a list of the other (native) modules upon which it depends?

**Comment by lovell** [comment]
There are quite a few other modules with similar reports for this problem https://github.com/search?o=desc&q=Assertion+failed%3A+%28loop-%3Ewatchers%5Bw-%3Efd%5D+%3D%3D+w%29%2C+function+uv__io_stop&s=created&type=Issues&utf8=%E2%9C%93

**Comment by lovell** [comment]
If this is caused by libvips writing to `stderr` (rather than that being a side-effect of another problem) then https://github.com/nodejs/node/issues/3422 looks relevant with https://github.com/mscdex/node-mariasql/commit/f777a0e28d0517d954d0d0658c311ace6b857390 being the fix referred to.

sharp doesn't directly use any of libuv's file handling logic so my best guess remains that another module is doing so - if not MariaDB then perhaps a logging or monitoring library that's trying to watch `stderr`.

**Comment by hyatt03** [comment]
Thank you for the response! I've looked at our logs, and it turns out the assertion error doesn't always happen in conjunction with a read error, in fact, most of the time the read error happens with an assertion error. The process continues nontheless, without reporting an error, and that's our primary concern.

**Comment by lovell** [comment]
Are you able to set the `VIPS_WARNING=0` environment variable to silence these warnings? This will (temporarily, at least) help separate what might be two different problems interfering with each other.

**Comment by lovell** [comment]
Were you able to solve this? If so, are you able to share details in case others have the same problem? Thanks!

**Comment by hyatt03** [comment]
Thank you for trying to help me. I was not able to solve it, and I had to replace the library as it caused a sigabort (I think libvips -> imagemagick), which crashed my application (forever detected the sigabort and killed the process). If I get the time to look into the cause, I will, but for now I must leave you without an answer.
