### ISSUE TITLE
Keep only specified EXIF, IPTC, and XMP metadata tag values (similar to `withExifMerge`)

### ISSUE THREAD

**Issue by beschler** [lovell/sharp#4033]
## Question about an existing feature

The [documentation states](https://sharp.pixelplumbing.com/api-output#withexifmerge) that the output option `withExifMerge` can be used to retain only the specified _EXIF_ metadata from the input image into the output image. However, how can I also specify _other_ metadata, for example IPTC and XMP tags?

(Output option `keepMetadata` indicates that EXIF, ICC, XMP, IPTC metadata can be retained - so this indicates these tags are accessible from within `sharp`.)

Additionally, I'm looking to _retain the same values_ for the metadata tags specified, since they currently exist in the input file. (I'm not looking to manually specify override values.)

### What are you trying to achieve?

I'm a photographer using Adobe Lightroom Classic and adding copyright information to my photographs. I would like to use `sharp` to optimize my photos for my website, and strip all metadata (e.g. aperture, shutter speed, etc.) from my images _except_ retain metadata that relates to **copyright information** and **original creation date**. Specifically, I would like to remove all metadata except retain only the following fields:

- EXIF `Artist`
- EXIF `Copyright`
- EXIF `DateTimeOriginal`
- EXIF `OffsetTimeOriginal`
- IPTC `Date Created`
- IPTC `Time Created`
- IPTC `By-line`
- IPTC `By-line Title`
- IPTC `Credit`
- IPTC `Source`
- IPTC `Copyright Notice`
- XMP `DateCreated`
- XMP `Source`
- XMP `Credit`
- XMP `AuthorsPosition`
- XMP `creator`
- XMP `rights`
- XMP `UsageTerms`
- XMP `CreatorContactInfo`
  - `CreatorCity`
  - `CreatorRegion`
  - `CreatorWorkEmail`
  - `CreatorWorkUrl`
- XMP `WebStatement`

### When you searched for similar issues, what did you find that might be related?

- I found packages such as [`exifreader`](https://www.npmjs.com/package/exifreader) which can read metadata, and has some more flexibility to do things like convert the shutter speed value from a decimal (e.g. `0.005`) to a human readable fraction (`1/200`), but it cannot write or remove metadata.
- [`node-iptc`](https://www.npmjs.com/package/node-iptc) looks to be able to write metadata, but ultimately I'm not trying to _change_ values (or remove all and add back certain ones - they already exist).
- I couldn't find anything on StackOverflow or Reddit that related to removing _only some_ metadata tags, but leaving others.
- Since the `sharp` docs mention the ability to do this with _EXIF_ tags, I'm wondering if this can also be done with IPTC and XMP tags as well.
- [This StackOverflow post](https://stackoverflow.com/a/27638728/2241690) seems to somewhat outline the process, but not using `sharp`.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

(EXIF tags sourced from [EXIF docs](https://exiftool.org/TagNames/EXIF.html).)

```js
const outputWithSelectMetadata = await sharp(inputWithExif)
  .withExifMerge({
    IFD0: {
      Artist: ORIGINAL_FROM_FILE, // how do I retain the original value?
      Copyright: ORIGINAL_FROM_FILE
    },
    ExifIFD: { // is this a valid EXIF tag group in sharp?
      DateTimeOriginal: ORIGINAL_FROM_FILE,
      OffsetTimeOriginal: ORIGINAL_FROM_FILE
    }
  })
  .withIPTCMerge({ // for example
    'Date Created': ORIGINAL_FROM_FILE,
    'Time Created': ORIGINAL_FROM_FILE,
    'By-line': ORIGINAL_FROM_FILE,
    'By-line Title': ORIGINAL_FROM_FILE,
    'Credit': ORIGINAL_FROM_FILE,
    'Source': ORIGINAL_FROM_FILE,
    'Copyright Notice': ORIGINAL_FROM_FILE
  })
  .withXMPMerge({ // for example
    'DateCreated': ORIGINAL_FROM_FILE,
    'Source': ORIGINAL_FROM_FILE,
    'Credit': ORIGINAL_FROM_FILE,
    'AuthorsPosition': ORIGINAL_FROM_FILE,
    'creator': ORIGINAL_FROM_FILE,
    'rights': ORIGINAL_FROM_FILE,
    'UsageTerms': ORIGINAL_FROM_FILE,
    'CreatorContactInfo': ORIGINAL_FROM_FILE,
    'WebStatement': ORIGINAL_FROM_FILE
  })
  .toFile('output.jpg', (err, info) => { ... });
 ```

Any help is appreciated! Thanks so much!

**Comment by lovell** [comment]
EXIF metadata support in sharp is provided via libvips+libexif, which only parses EXIF, therefore IPTC and XMP are exposed as binary blobs for parsing with external tools.

You might have some luck with the slightly-misnamed [exiftool](https://www.npmjs.com/package/exiftool-vendored), which I believe can parse some IPTC and XMP metadata.

**Comment by beschler** [comment]
That's come up in my searches. I'll look there - thanks for the clarification!

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
