### ISSUE TITLE
default `limitInputPixels` is not set correctly for jpeg input, avif output, yields `Error: Input image exceeds pixel limit`

### ISSUE THREAD

**Issue by jo-chemla** [lovell/sharp#4034]
Hi all, here is a potential bug I've encountered when using [gltf-transform](https://github.com/donmccurdy/glTF-Transform) to encode/compress the 16k texture of a mesh from `jpg` to the `avif` format. The input image is 16384x16384, and it seems that the avif spec does not enforce that resolution limit - see the wiki [avif profiles](https://en.wikipedia.org/wiki/AVIF#Profiles), similar unconstrained resolution for jpg.

Sharp default `limitInputPixels` of 0x3FFF² (16383) won't let me input JPEG/output AVIF images with that 16384² resolution. 

### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.
version: 0.33.2

Related discussion in gltf-transform repo [here](https://github.com/donmccurdy/glTF-Transform/discussions/1305#discussioncomment-8839416). 
The line were the sharp encoding happens is [here](https://github.com/donmccurdy/glTF-Transform/blob/947faf21efac65c9f9a023ec937553a9df7791b1/packages/functions/src/texture-compress.ts#L322).

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12800H
    Memory: 18.60 GB / 31.62 GB
  Binaries:
    Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: ^0.33.2 => 0.33.2
```
### What are the steps to reproduce?

 - have a jpg 16384x16384 image in your workdir - can create one with gimp or use this [blank](https://www.dropbox.com/scl/fi/k7dfqx456x90pq8eufv86/blank_16384.jpg?rlkey=bpotmuxrmy7njwr93u4nsc8hg&dl=0) example
 - execute the following `node sharp-to-avif.js`
 - Yields `Error: Input image exceeds pixel limit`

```js
// node sharp-to-avif.js
const sharp = require('sharp');
const start = +new Date();
sharp("./input_1x16k_u0_v0_diffuse.jpeg").toFile("./out.avif", (err, output) => {
    console.log(err, output)
})
```

Complete stack: 
```
Error: Input image exceeds pixel limit
    at Sharp.toFile (workdir\node_modules\sharp\lib\output.js:89:19)
    at Object.<anonymous> (workdir\sharp-to-avif.js:3:85)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47 undefined
```

### What is the expected behaviour?

However, when using the following vips command, the encoding happens perfecty, and resulting 16384 avif image is created.
```bash
vips-dev-8.15\bin\vips.exe copy input_1x16k_u0_v0_diffuse.jpeg out.avif
```

Maybe the `limitInputPixels` option for the avif module could be set to a higher limit. 

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

See above steps to reproduce

### Please provide sample image(s) that help explain this problem
Here is a [blank demo file](https://www.dropbox.com/scl/fi/k7dfqx456x90pq8eufv86/blank_16384.jpg?rlkey=bpotmuxrmy7njwr93u4nsc8hg&dl=0)

**Comment by lovell** [comment]
The default value of `limitInputPixels` is 268402689 (= 16383 * 16383) and is unrelated to either input or output format.

https://sharp.pixelplumbing.com/api-constructor

If you trust the input, you can set/remove this limit as follows:
```diff
- sharp("./input_1x16k_u0_v0_diffuse.jpeg").toFile("./out.avif", (err, output) => {
+ sharp("./input_1x16k_u0_v0_diffuse.jpeg", { limitInputPixels: false }).toFile("./out.avif", (err, output) => {
```

**Comment by jo-chemla** [comment]
Thanks for getting back so fast. I assumed that `limitInputPixels` encoder limit was defined per format, but I think I mixed it up with references to `maxWidth/maxHeight` when searching the repo. Then indeed it's expected behavior, and changing that option within the constructor would be the way to go - at least it does work on that test-case.
