### ISSUE TITLE
sharp: Installation error: Prebuilt libvips 8.14.3 binaries are not yet available for win32-x64

### ISSUE THREAD

**Issue by giserman001** [lovell/sharp#4035]
sharp: Downloading https://npmmirror.com/mirrors/sharp-libvips/sharp-libvips/v8.14.3/libvips-8.14.3-win32-x64.tar.br
│ sharp: Installation error: Prebuilt libvips 8.14.3 binaries are not yet available for win32-x64
│ sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies

**Comment by giserman001** [comment]
How to solve this problem?

**Comment by lovell** [comment]
Please ensure you are using the latest version of sharp. If you are using another package which depends on a version of sharp that is not the latest, please open an issue against that package instead.

If you are still having installation problems, please open [a new installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) and answer all of the questions.
