### ISSUE TITLE
Google cloud storage integration

### ISSUE THREAD

**Issue by vitalijalbu** [lovell/sharp#4038]
Hi guys, my client uses **google cloud storage** to upload images, so I'd like to ask how to integrate sharp js for image processing and transformation?
Basically I would like to have it on a 3rd domain, [media.example.com](https://media.example.com/) but I can't understand how to integrate the code with the cloud bucket.. 
Meaning, if I do the code in another server, this means my code has no local access to the file, but it must download it, process and finally send it back to the client. 
Am I wrong? Many thanks
I did it before using a blank server (using php) but in this case cloud storage is different I think.

**Comment by lovell** [comment]
sharp (very intentionally) does not provide any networking capability so you'll have to look after this bit yourself.

The Google (Firebase) docs provide an example:
https://firebase.google.com/docs/functions/gcp-storage-events?gen=1st#example:-image

This question is probably more suited to a general programming site such as StackOverflow - good luck!
