### ISSUE TITLE
Suspect `sharp()....toFile()` do not release input file on Windows.

### ISSUE THREAD

**Issue by Shintarot** [lovell/sharp#4039]
### Is this a possible bug in a feature of sharp, unrelated to installation?

-   [x] Running `npm install sharp` completes without error.
-   [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

-   [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

I cannot run it because it is not in my environment. The known environments are as follows.

```
Windows 11
node.js v20.11.0
sharp 0.33.2

// webpack
"ts-loader": "^9.5.1",
"ts-node": "^10.9.2",
"webpack": "^5.90.3",
"webpack-cli": "^5.1.4",
"webpack-node-externals": "^3.0.0"
```

This error did not occur on macOS (12.7.3 x64).

### What are the steps to reproduce?

1. run `sharp(<targetFilePath>)....toFile(<destPath>)`.
2. after resolve, try to delete the file <targetFilePath> given to `sharp(<targetFilePath>)`.
3. the following error occurs.

```
[Error: EPERM: operation not permitted, unlink '<targetFilePath>'] {
    errno: -4048,
    code: 'EPERM',
    syscall: 'unlink',
    path: '<targetFilePath>'
}
```

### What is the expected behaviour?

The above error started happening after updating to `0.33.2`. Before the update, I was using `0.32.3` and had no errors. Then I reverted back to `0.32.3` and the above error no longer occurs. My code has not been changed.

I can only guess, but I suspect that `await sharp() ... .toFile(destPath);` do not release `<targetFilePath>` file even after resolve.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

Here is the actual code. Run it on Windows.

```
import sharp from 'sharp';
import { rm } from 'fs';

const remove = async (path: string): Promise<void | never> => {
    return new Promise<void | never>((resolve, reject) => {
        rm(path, { recursive: true }, (error) => {
            if (error) {
                reject(error);
                return;
            }
            resolve();
        });
    });
};

const resizeAndToWebp = async (
    targetFilePath: string,
    destPath: string,
    maxWidth: number,
    maxHeight: number,
    fit?: keyof sharp.FitEnum
) => {
    await sharp(targetFilePath)
        .rotate()
        .resize({
            width: maxWidth,
            height: maxHeight,
            fit,
            withoutEnlargement: true,
        })
        .webp({
            effort: 6,
        })
        .toFile(destPath);

    if (targetFilePath !== destPath) {
        await remove(targetFilePath); // an error occurs as above
    }
};

```

### Please provide sample image(s) that help explain this problem

No screenshots. A sample repository can be provided if needed.

**Comment by lovell** [comment]
Windows won't let you delete a file whilst it is held open by libvips' cache.

Please see https://github.com/lovell/sharp/issues/3099#issuecomment-1140900378
