### ISSUE TITLE
Conversion from PDF to image

### ISSUE THREAD

**Issue by IanDaly** [lovell/sharp#4040]
## Question about an existing feature
When calling Sharp using a path to PDF or a buffer it gives an error. The error thrown is **Error: Input buffer contains unsupported image format.**

### What are you trying to achieve?
To convert a PDF file to an image. 

### When you searched for similar issues, what did you find that might be related?
Similar issues point to using a globally installed version of Vips. Which I have installed through Homebrew. Conversion works as intended when calling Vips directly from the command line.

**Comment by lovell** [comment]
> using a globally installed version of Vips. Which I have installed through Homebrew

Please see https://sharp.pixelplumbing.com/install#building-from-source for the additional dependencies required to build sharp from source against a globally-installed libvips.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
