### ISSUE TITLE
Consider support for the JPEG-XL format in prebuilt binaries

### ISSUE THREAD

**Issue by ollm** [lovell/sharp#4043]
### What are you trying to achieve?

Currently JPEG-XL is increasing in popularity and is supported by more software, it would be interesting to consider adding it to the prebuilt binaries, would be helpful in situations where we can't install our own binaries, like electron apps (My use case)

Current JPEG-XL software support (Extracted from [Wikipedia](https://en.wikipedia.org/wiki/JPEG_XL#Official_software_support))

<details>
<summary><b>Official software support</b></summary>

Apple Inc.

- iOS/iPadOS 17 and later – system-wide reading including Files and Photos
- macOS Sonoma (version 14) and later – reading on Finder and Preview
- visionOS (presumed)
- watchOS 10 and later
- Safari 17 and later via the WebKit engine

Samsung

- One UI in Samsung Galaxy S24 - storage capacity in Expert Raw

Others

- Pale Moon v31.4.0 and later (v31.4.1 fixed wrong color of decoded JPEG XL images, v31.4.2 fixed JPEG-XL's transparency display for images with an alpha channel, and v32.0.0 support progressive decoding and animation for JPEG XL.)
- Epiphany 45 via the WebKitGTK engine
- ImageMagick – reading and writing of JPEG XL images
- KDE applications can be built with KImageFormats plugin with native JPEG XL support. This gives most KDE apps native support for both read and writing and works with all apps from the Dolphin file manager including Gwenview image viewer
- Krita digital painting tool and DigiKam photo manager.
- XnView – reading and writing of JPEG XL images

</details>

<details>
<summary><b>Unofficial or indirect support</b></summary>

- Microsoft Windows – A 3rd-party Windows Imaging Component (WIC) plugin adds viewing to File Explorer, Microsoft Photos, Windows Photo Viewer, and thumbnails, and aware apps. Only On Windows 7/10.
- Another Windows Imaging Component plugin, jxl-winthumb.
- macOS (prior to 14.0 Sonoma) – via a standalone app and a plugin for Quick Look
- GTK and GNOME image viewing apps (such as Eye of GNOME, GNOME Files, etc.) through the GDK pixbuf plugin provided by the JPEG XL project
- Qt support can be added with the qt-jpegxl-image-plugin

</details>

<details>
<summary><b>Preliminary web browser support</b></summary>

- Firefox web browser – introduced for testing in Firefox Nightly build

</details>

### When you searched for similar feature requests, what did you find that might be related?

https://github.com/lovell/sharp/issues/2731

**Comment by lovell** [comment]
Sadly my comment in https://github.com/lovell/sharp/issues/2731#issuecomment-1361717579 remains relevant here, namely that you'll need to ask web browser vendors.
