### ISSUE TITLE
Not getting density value for tiff files 

### ISSUE THREAD

**Issue by rajendraprasadyk** [lovell/sharp#4044]
I am not able to see the density value from tiff file but it works fine with jpg and png files.
  const image = sharp(fileResult.data);                          
 const metadata = await image.metadata();
{
  format: 'gif',
  size: 24521,
  width: 307,
  height: 290,
  space: 'srgb',
  channels: 3,
  depth: 'uchar',
  isProgressive: false,
  paletteBitDepth: 8,
  pages: 1,
  loop: 1,
  delay: [ 100 ],
  background: { r: 0, g: 0, b: 0 },
  hasProfile: false,
  hasAlpha: false
}

**Comment by lovell** [comment]
>  format: 'gif',

This looks like the metadata from a GIF image rather than a TIFF image.

**Comment by rajendraprasadyk** [comment]
sorry its my bad. please ignore this one, i have checked for tif file and its coming. Thank you

**Comment by rajendraprasadyk** [comment]
Its working as expected
