### ISSUE TITLE
Image darkening after updating to 0.32.6

### ISSUE THREAD

**Issue by nick-mon1** [lovell/sharp#4049]
## Question about an existing feature
I'm seeing image darkening when moving from `0.31.3` to `0.32.6` or `0.33.3` for both `jpeg` and `png`.

I'm using `gulp-responsive` to generate different sizes and `sharp` as the image processor.

```javascript
          {
            quality: 80,
            compressionLevel: 7,
            progressive: true,
            withMetadata: false,
            errorOnUnusedConfig: false,
            skipOnEnlargement: true,
            errorOnEnlargement: false,
            silent: true,
          }
```

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question
The darkening is mostly notable less on photo-like images and more for 2-3 color images.

<img width="694" alt="Screenshot 2024-04-01 at 4 35 47 PM" src="https://github.com/lovell/sharp/assets/104778659/19e42934-22ca-4628-a5b1-42cfeca8e38c">

<img width="744" alt="Screenshot 2024-04-01 at 4 42 39 PM" src="https://github.com/lovell/sharp/assets/104778659/75c5a9e7-49d3-4d86-b3f2-29a54ad35818">

</p>
</details>

**Comment by lovell** [comment]
The `gulp-responsive` package relies on an out-of-date version of `sharp` from 2019.

https://github.com/mahnunchik/gulp-responsive/blob/8091ebc2fd9d8fe757201600f63c3653446147bd/package.json#L49

Please can you provide the original, input images and sample code using only `sharp`, without any other dependencies, that allows someone else to reproduce.

**Comment by nick-mon1** [comment]
@lovell Thanks for the response. When using only `sharp` I **do not** see the image darkening effect.
Thanks for the response.

**Comment by davidmurdoch** [comment]
The reason it darkens is because `gulp-responsive` (and the more up-to-date version `@localnerve/gulp-responsive`) calls `image.normalize(config.normalize)` even when `config.normalize` is false. I imagine the `normalize` function must have accepted a boolean at some point, and now it doesn't.
