### ISSUE TITLE
Installing sharp with yarn causes "Could not load the "sharp" module using the linuxmusl-x64 runtime"

### ISSUE THREAD

**Issue by romanpastu** [lovell/sharp#4053]
## Possible install-time or require-time problem

- [x] I have read and understood all of the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have searched for known bugs relating to this problem in my choice of package manager.

You must confirm both of these before continuing.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.
0.33.3
If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest,
please open an issue against that package instead.

### Are you using a supported runtime?

- [x] I am using Node.js with a version that satisfies `^18.17.0 || ^20.3.0 || >=21.0.0`
20.9.0
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these,
please upgrade to the latest version
and try again before opening an issue.

### Are you using a supported package manager and installing optional dependencies?

- [ ] I am using npm >= 9.6.5 with `--include=optional`
- [x] I am using yarn >= 3.2.0
- [ ] I am using pnpm >= 7.1.0 with `--no-optional=false`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these, please upgrade to the latest version of your chosen package manager
and ensure you are allowing the installation of optional or multi-platform dependencies before opening an issue.

### What is the complete error message, including the full stack trace?

```
[TypeScript] 1:39:13 PM - Found 0 errors. Watching for file changes.
[Node] /admin-be/node_modules/sharp/lib/sharp.js:114
[Node]   throw new Error(help.join('\n'));
[Node]   ^
[Node] 
[Node] Error: Could not load the "sharp" module using the linuxmusl-x64 runtime
[Node] Possible solutions:
[Node] - Ensure optional dependencies can be installed:
[Node]     npm install --include=optional sharp
[Node]     yarn add sharp --ignore-engines
[Node] - Ensure your package manager supports multi-platform installation:
[Node]     See https://sharp.pixelplumbing.com/install#cross-platform
[Node] - Add platform-specific dependencies:
[Node]     npm install --os=linux --libc=musl --cpu=x64 sharp
[Node] - Consult the installation documentation:
[Node]     See https://sharp.pixelplumbing.com/install
[Node]     at Object.<anonymous> (/admin-be/node_modules/sharp/lib/sharp.js:114:9)
[Node]     at Module._compile (node:internal/modules/cjs/loader:1241:14)
[Node]     at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
[Node]     at Module.load (node:internal/modules/cjs/loader:1091:32)
[Node]     at Module._load (node:internal/modules/cjs/loader:938:12)
[Node]     at Module.require (node:internal/modules/cjs/loader:1115:19)
[Node]     at require (node:internal/modules/helpers:130:18)
[Node]     at Object.<anonymous> (/admin-be/node_modules/sharp/lib/constructor.js:10:1)
[Node]     at Module._compile (node:internal/modules/cjs/loader:1241:14)
[Node]     at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
[Node] 
[Node] Node.js v20.9.0
[Node] [nodemon] app crashed - waiting for file changes before starting...
```

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

npm verb cli [
npm verb cli   '/home/roman/.nvm/versions/node/v16.14.0/bin/node',
npm verb cli   '/home/roman/.nvm/versions/node/v16.14.0/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   '--foreground-scripts',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@8.3.1
npm info using node@v16.14.0
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/home/roman/.nvm/versions/node/v16.14.0/lib/node_modules/npm/npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 1ms
npm timing config:load:env Completed in 1ms
npm timing config:load:file:/home/roman/Documents/test/.npmrc Completed in 1ms
npm timing config:load:project Completed in 2ms
npm timing config:load:file:/home/roman/.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:/home/roman/.nvm/versions/node/v16.14.0/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 8ms
npm timing npm:load:configload Completed in 8ms
npm timing npm:load:setTitle Completed in 1ms
npm timing config:load:flatten Completed in 2ms
npm timing npm:load:display Completed in 5ms
npm verb logfile /home/roman/.npm/_logs/2024-04-03T13_40_56_076Z-debug-0.log
npm timing npm:load:logFile Completed in 3ms
npm timing npm:load:timers Completed in 0ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load Completed in 19ms
npm timing arborist:ctor Completed in 1ms
npm timing arborist:ctor Completed in 0ms
npm timing idealTree:init Completed in 8ms
npm timing idealTree:userRequests Completed in 2ms
npm http fetch GET 200 https://registry.npmjs.org/sharp 1073ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 273ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linuxmusl-arm64 542ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-x64 739ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-arm 744ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linuxmusl-arm64 744ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-x64 744ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-darwin-arm64 747ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-darwin-arm64 747ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linuxmusl-x64 746ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-arm 745ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-s390x 746ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-s390x 748ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-arm64 749ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-darwin-x64 750ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linuxmusl-x64 788ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-arm64 828ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/color 880ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/semver 901ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-win32-x64 948ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-wasm32 950ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-win32-ia32 953ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-darwin-x64 2003ms (cache miss)
npm timing idealTree:#root Completed in 3092ms
npm http fetch GET 200 https://registry.npmjs.org/color-convert 182ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/lru-cache 186ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-string 205ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@emnapi%2fruntime 277ms (cache miss)
npm timing idealTree:node_modules/sharp Completed in 328ms
npm timing idealTree:node_modules/@img/sharp-darwin-arm64 Completed in 0ms
npm timing idealTree:node_modules/@img/sharp-darwin-x64 Completed in 0ms
npm timing idealTree:node_modules/@img/sharp-libvips-darwin-arm64 Completed in 1ms
npm timing idealTree:node_modules/@img/sharp-libvips-darwin-x64 Completed in 0ms
npm timing idealTree:node_modules/@img/sharp-libvips-linux-arm Completed in 0ms
npm timing idealTree:node_modules/@img/sharp-libvips-linux-arm64 Completed in 0ms
npm timing idealTree:node_modules/@img/sharp-libvips-linux-s390x Completed in 0ms
npm timing idealTree:node_modules/@img/sharp-libvips-linux-x64 Completed in 0ms
npm timing idealTree:node_modules/@img/sharp-libvips-linuxmusl-arm64 Completed in 0ms
npm timing idealTree:node_modules/@img/sharp-libvips-linuxmusl-x64 Completed in 0ms
npm timing idealTree:node_modules/@img/sharp-linux-arm Completed in 0ms
npm timing idealTree:node_modules/@img/sharp-linux-arm64 Completed in 0ms
npm timing idealTree:node_modules/@img/sharp-linux-s390x Completed in 0ms
npm timing idealTree:node_modules/@img/sharp-linux-x64 Completed in 0ms
npm timing idealTree:node_modules/@img/sharp-linuxmusl-arm64 Completed in 1ms
npm timing idealTree:node_modules/@img/sharp-linuxmusl-x64 Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/tslib 172ms (cache revalidated)
npm timing idealTree:node_modules/@img/sharp-wasm32 Completed in 179ms
npm timing idealTree:node_modules/@emnapi/runtime Completed in 4ms
npm timing idealTree:node_modules/@img/sharp-win32-ia32 Completed in 0ms
npm timing idealTree:node_modules/@img/sharp-win32-x64 Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle 165ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-name 170ms (cache revalidated)
npm timing idealTree:node_modules/color Completed in 180ms
npm timing idealTree:node_modules/color-convert Completed in 1ms
npm timing idealTree:node_modules/color-name Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 186ms (cache revalidated)
npm timing idealTree:node_modules/color-string Completed in 188ms
npm timing idealTree:node_modules/detect-libc Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/yallist 179ms (cache revalidated)
npm timing idealTree:node_modules/semver Completed in 183ms
npm timing idealTree:node_modules/lru-cache Completed in 3ms
npm timing idealTree:node_modules/simple-swizzle Completed in 3ms
npm timing idealTree:node_modules/is-arrayish Completed in 0ms
npm timing idealTree:node_modules/tslib Completed in 0ms
npm timing idealTree:node_modules/yallist Completed in 0ms
npm timing idealTree:buildDeps Completed in 4177ms
npm timing idealTree:fixDepFlags Completed in 3ms
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'sharp@0.33.3',
npm WARN EBADENGINE   required: { node: '^18.17.0 || ^20.3.0 || >=21.0.0', libvips: '>=8.15.2' },
npm WARN EBADENGINE   current: { node: 'v16.14.0', npm: '8.3.1' }
npm WARN EBADENGINE }
npm timing idealTree Completed in 4195ms
npm timing reify:loadTrees Completed in 4197ms
npm timing reify:diffTrees Completed in 5ms
npm timing reify:retireShallow Completed in 1ms
npm timing reify:createSparse Completed in 10ms
npm timing reify:loadBundles Completed in 0ms
npm verb reify failed optional dependency /home/roman/Documents/test/node_modules/@img/sharp-win32-x64
npm verb reify failed optional dependency /home/roman/Documents/test/node_modules/@img/sharp-win32-ia32
npm verb reify failed optional dependency /home/roman/Documents/test/node_modules/@img/sharp-wasm32
npm verb reify failed optional dependency /home/roman/Documents/test/node_modules/@emnapi/runtime
npm verb reify failed optional dependency /home/roman/Documents/test/node_modules/tslib
npm verb reify failed optional dependency /home/roman/Documents/test/node_modules/@img/sharp-linuxmusl-x64
npm verb reify failed optional dependency /home/roman/Documents/test/node_modules/@img/sharp-linuxmusl-arm64
npm verb reify failed optional dependency /home/roman/Documents/test/node_modules/@img/sharp-linux-x64
npm verb reify failed optional dependency /home/roman/Documents/test/node_modules/@img/sharp-linux-s390x
npm verb reify failed optional dependency /home/roman/Documents/test/node_modules/@img/sharp-linux-arm64
npm verb reify failed optional dependency /home/roman/Documents/test/node_modules/@img/sharp-linux-arm
npm verb reify failed optional dependency /home/roman/Documents/test/node_modules/@img/sharp-libvips-linuxmusl-x64
npm verb reify failed optional dependency /home/roman/Documents/test/node_modules/@img/sharp-libvips-linuxmusl-arm64
npm verb reify failed optional dependency /home/roman/Documents/test/node_modules/@img/sharp-libvips-linux-x64
npm verb reify failed optional dependency /home/roman/Documents/test/node_modules/@img/sharp-libvips-linux-s390x
npm verb reify failed optional dependency /home/roman/Documents/test/node_modules/@img/sharp-libvips-linux-arm64
npm verb reify failed optional dependency /home/roman/Documents/test/node_modules/@img/sharp-libvips-linux-arm
npm verb reify failed optional dependency /home/roman/Documents/test/node_modules/@img/sharp-libvips-darwin-x64
npm verb reify failed optional dependency /home/roman/Documents/test/node_modules/@img/sharp-libvips-darwin-arm64
npm verb reify failed optional dependency /home/roman/Documents/test/node_modules/@img/sharp-darwin-x64
npm verb reify failed optional dependency /home/roman/Documents/test/node_modules/@img/sharp-darwin-arm64
npm timing reifyNode:node_modules/@img/sharp-win32-x64 Completed in 11ms
npm timing reifyNode:node_modules/@img/sharp-win32-ia32 Completed in 11ms
npm timing reifyNode:node_modules/@img/sharp-wasm32 Completed in 11ms
npm timing reifyNode:node_modules/@img/sharp-linuxmusl-x64 Completed in 11ms
npm timing reifyNode:node_modules/@img/sharp-linuxmusl-arm64 Completed in 11ms
npm timing reifyNode:node_modules/@img/sharp-linux-x64 Completed in 10ms
npm timing reifyNode:node_modules/@img/sharp-linux-s390x Completed in 10ms
npm timing reifyNode:node_modules/@img/sharp-linux-arm64 Completed in 10ms
npm timing reifyNode:node_modules/@img/sharp-linux-arm Completed in 10ms
npm timing reifyNode:node_modules/@img/sharp-libvips-linuxmusl-x64 Completed in 10ms
npm timing reifyNode:node_modules/@img/sharp-libvips-linuxmusl-arm64 Completed in 11ms
npm timing reifyNode:node_modules/@img/sharp-libvips-linux-x64 Completed in 11ms
npm timing reifyNode:node_modules/@img/sharp-libvips-linux-s390x Completed in 11ms
npm timing reifyNode:node_modules/@img/sharp-libvips-linux-arm64 Completed in 11ms
npm timing reifyNode:node_modules/@img/sharp-libvips-linux-arm Completed in 11ms
npm timing reifyNode:node_modules/@img/sharp-libvips-darwin-x64 Completed in 11ms
npm timing reifyNode:node_modules/@img/sharp-libvips-darwin-arm64 Completed in 11ms
npm timing reifyNode:node_modules/@img/sharp-darwin-x64 Completed in 11ms
npm timing reifyNode:node_modules/@img/sharp-darwin-arm64 Completed in 11ms
npm timing reifyNode:node_modules/color-name Completed in 76ms
npm timing reifyNode:node_modules/lru-cache Completed in 76ms
npm timing reifyNode:node_modules/yallist Completed in 77ms
npm timing reifyNode:node_modules/color-convert Completed in 77ms
npm timing reifyNode:node_modules/tslib Completed in 79ms
npm timing reifyNode:node_modules/semver Completed in 83ms
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.3.2.tgz 308ms (cache miss)
npm timing reifyNode:node_modules/is-arrayish Completed in 328ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 332ms
npm timing auditReport:getReport Completed in 336ms
npm timing auditReport:init Completed in 0ms
npm timing reify:audit Completed in 338ms
npm http fetch GET 200 https://registry.npmjs.org/sharp/-/sharp-0.33.3.tgz 541ms (cache miss)
npm timing reifyNode:node_modules/sharp Completed in 579ms
npm http fetch GET 200 https://registry.npmjs.org/@emnapi/runtime/-/runtime-1.1.1.tgz 570ms (cache miss)
npm timing reifyNode:node_modules/@emnapi/runtime Completed in 594ms
npm http fetch GET 200 https://registry.npmjs.org/color/-/color-4.2.3.tgz 1133ms (cache miss)
npm timing reifyNode:node_modules/color Completed in 1175ms
npm http fetch GET 200 https://registry.npmjs.org/color-string/-/color-string-1.9.1.tgz 1322ms (cache miss)
npm timing reifyNode:node_modules/color-string Completed in 1350ms
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle/-/simple-swizzle-0.2.2.tgz 1342ms (cache miss)
npm timing reifyNode:node_modules/simple-swizzle Completed in 1365ms
npm http fetch GET 200 https://registry.npmjs.org/detect-libc/-/detect-libc-2.0.3.tgz 1423ms (cache miss)
npm timing reifyNode:node_modules/detect-libc Completed in 1454ms
npm timing reify:unpack Completed in 1455ms
npm timing reify:unretire Completed in 0ms
npm timing build:queue Completed in 4ms
npm timing build:link:node_modules/semver Completed in 2ms
npm timing build:link Completed in 3ms
npm info run sharp@0.33.3 install node_modules/sharp node install/check

> sharp@0.33.3 install
> node install/check

npm info run sharp@0.33.3 install { code: 0, signal: null }
npm timing build:run:install:node_modules/sharp Completed in 83ms
npm timing build:run:install Completed in 83ms
npm timing build:deps Completed in 91ms
npm timing build Completed in 91ms
npm timing reify:build Completed in 92ms
npm timing reify:trash Completed in 7ms
npm timing reify:save Completed in 9ms
npm timing reify Completed in 5796ms

added 11 packages, and audited 12 packages in 6s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm timing command:install Completed in 5801ms
npm verb exit 0
npm timing npm Completed in 5980ms
npm info ok 

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

  System:
    OS: Linux 6.5 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 4.77 GB / 15.28 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 3.2.0 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
  npmPackages:
    sharp: ^0.33.3 => 0.33.3

**Comment by lovell** [comment]
> npm info using node@v16.14.0
>  Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node

It looks like you have multiple, possibly conflicting versions of Node.js on this machine.

> [Node] Error: Could not load the "sharp" module using the linuxmusl-x64 runtime
>  OS: Linux 6.5 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)

Additionally, it looks like you're using multiple Linux OS with different libc implementations. For yarn you'll need to configure its `supportedArchitectures` feature - please see https://sharp.pixelplumbing.com/install#cross-platform

**Comment by romanpastu** [comment]
Well the different version of node issue is because i have one node installed globally, and then I use nvm per project to manage different version, which is a pretty standard practice , in this case the project where im trying to install sharp is 20.9.0

But apparently the root of the issue was not having this file
```
.yarmc.yml
yarnPath: .yarn/releases/yarn-3.2.0.cjs
nodeLinker: node-modules
supportedArchitectures: {
  os: [
    "current",
    "darwin",
    "linux",
    "win32",
  ],
  cpu: [
    "current",
    "x64",
    "ia32",
    "arm64",
  ],
  libc: [
    "current",
    "glibc",
    "musl",
  ],
}
```

What i did is have that file in the root folder, and then when building the docker dev container 


```
# build commands 
FROM node:20.9-alpine

WORKDIR /workdir 
COPY ./package.json .
COPY ./.yarn/releases/yarn-3.2.0.cjs .yarn/releases/yarn-3.2.0.cjs #new
COPY ./.yarnrc.yml .yarnrc.yml #new
RUN yarn install

# run command
CMD yarn run watch
```

This fixed the issue for me
