### ISSUE TITLE
[Feature Request] Support for jpegli

### ISSUE THREAD

**Issue by Stanzilla** [lovell/sharp#4055]
## Feature request

Support for the jpegli encoder for jpgs

### What are you trying to achieve?

Integration of https://github.com/libjxl/libjxl/tree/main/lib/jpegli

See https://opensource.googleblog.com/2024/04/introducing-jpegli-new-jpeg-coding-library.html

**Comment by lovell** [comment]
Please se https://github.com/lovell/sharp/issues/4018
