### ISSUE TITLE
Failure on path with special characters

### ISSUE THREAD

**Issue by agustik** [lovell/sharp#406]
If i use a path with a special characters like icelandic I get an error:
[Error: Input file is missing or of an unsupported image format]

path example: "archives\agustik photos\233_AÁM.jpg"

Workaround: use buffer.

**Comment by lovell** [comment]
Hello, is this on Windows? If so, see https://github.com/lovell/sharp/issues/319 and https://github.com/jcupitt/libvips/issues/294

**Comment by agustik** [comment]
Yes sorry :)
