### ISSUE TITLE
Image is blurry after resizing puppeteer screenshot 

### ISSUE THREAD

**Issue by neilgandhi95** [lovell/sharp#4066]
## Question about an existing feature
I'm trying to resize a screenshot taken with Puppeteer, and finding the image to be very blurry

### When you searched for similar issues, what did you find that might be related?
I looked through a few threads here and the docs and tried messing with the kernel, but with no success

### Please provide a minimal, standalone code sample, wit
```javascript
const screenshotBuffer = await page.screenshot({ path: "screenshot.png" }); //puppeteer screenshot
const resizedBuffer = await sharp(screenshotBuffer)
        .resize(365, 206, {
          fit: "fill",
          kernel: "lanczos3",
          fastShrinkOnLoad: false,
        })
        .toBuffer();
``` 

### Please provide sample image(s) that help explain this question

**Without resize:**
![image](https://github.com/lovell/sharp/assets/22992531/b42aec9b-73c2-4797-8bd7-e5f641245e54)

**With resize:**
![image](https://github.com/lovell/sharp/assets/22992531/a2a18f62-e3d7-47a0-bfe6-313d49e5cf12)

**With resize, zoomed in to show blurry**
![image](https://github.com/lovell/sharp/assets/22992531/150ad83f-3fe0-425b-8174-526649e8411f)

**That same image resized in Figma is perfect quality**
![image 2 (2)](https://github.com/lovell/sharp/assets/22992531/5b89c7b2-32c6-4cf0-b7c9-d39d675316db)

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by zusamarehan** [comment]
Were you able to solve this? @neilgandhi95
