### ISSUE TITLE
Image stream hangs in Bun v1.1.3

### ISSUE THREAD

**Issue by justinhippo** [lovell/sharp#4067]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```  
System:
  OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
  CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
  Memory: 3.82 GB / 15.32 GB
  Container: Yes
  Shell: 5.8.1 - /usr/bin/zsh
Binaries:
  Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
  Yarn: 1.22.15 - ~/.nvm/versions/node/v16.16.0/bin/yarn
  npm: 8.16.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  pnpm: 6.11.0 - ~/.nvm/versions/node/v16.16.0/bin/pnpm
  bun: 1.1.3 - ~/.bun/bin/bun
npmPackages:
  sharp: ^0.33.3 => 0.33.3 
```

### What are the steps to reproduce?
Stream a `fetch` response through sharp in Bun. Outputting image hangs.

### What is the expected behaviour?

Image should be output as with Node and Deno

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```javascript
import sharp from "sharp";
import {Readable} from 'node:stream';

const server = Bun.serve({
  port: 8080,
  async fetch(req) {
    const res = await fetch("https://picsum.photos/1024");
    if (res.body === null) {
      return new Response('Unable to load source image', {status: 500});
    }
    const srcStream = Readable.fromWeb(res.body);
    const text = sharp({text: {text: "Hello world", font: 'sans 12', rgba: true, dpi: 300}}).resize(Math.floor(512 * 0.5), Math.floor(512 * 0.2), {fit: 'inside'}).negate({alpha: false}).toFormat('png');
    const transformer = sharp().resize(512, 512, {fit: 'inside'}).composite([{input: await text.toBuffer(), gravity: 'southeast'}]).on('info', ({height}) => {console.log(height)}).toFormat('jpeg');
    const transformed = srcStream.pipe(transformer);
    return new Response(await transformed.toBuffer(), {headers: {'Content-Type': 'image/jpeg'}})
  },
});

console.log(`Listening on http://localhost:${server.port} ...`);
```

**Comment by lovell** [comment]
Given the use of `Readable.fromWeb` I suspect this might relate to https://github.com/oven-sh/bun/issues/10066

**Comment by justinhippo** [comment]
Can confirm, adding 
```javascript
async function * readableFromWeb(webReadable: ReadableStream<any>) {
  for await (const chunk of webReadable) {
    yield chunk;
  }
}
```
and changing to use `const srcStream = Readable.from(readableFromWeb(res.body));` fixes the issue for me
