### ISSUE TITLE
'bad extract area' under some conditions

### ISSUE THREAD

**Issue by scorpp** [lovell/sharp#407]
For me issue happens only when image of 1920x1080 size is sourced. Then after doing extract with non-zero `top` i get the failure. Below is test program to reproduce and it's output.

Changing `top` to zero 'fixes' it.

```
'use strict';

var sharp = require('sharp');

// any image of 1920x1080 size. 
// e.g. http://hdimagesnew.com/wp-content/uploads/2015/11/Hd-Backgrounds-1080p-1920×1080-1.jpg
sharp('1.jpg')
    .metadata(function (err, metadata) {
        console.log(metadata);
    })
    .extract({left: 0, top: 2/*works when top: 0*/, width: 1080, height: 1080})
    .toBuffer('/tmp/1.jpg', function (err, data, info) {
        if (err) throw err;
        console.log(info);
    });
```

the output is 

```
{ format: 'jpeg',
  width: 1920,
  height: 1080,
  space: 'srgb',
  channels: 3,
  hasProfile: false,
  hasAlpha: false,
  orientation: 1,
  exif: <Buffer 45 78 69 66 00 00 49 49 2a 00 08 00 00 00 07 00 12 01 03 00 01 00 00 00 01 00 00 00 1a 01 05 00 01 00 00 00 62 00 00 00 1b 01 05 00 01 00 00 00 6a 00 ... > }
Unhandled rejection Error: extract_area: bad extract area

    at Error (native)
```

**Comment by lovell** [comment]
The `bad extract area` error looks like the expected behaviour based on the input image dimensions and values passed to `extract`.

Using `top: 2` means the `height` must be reduced by 2 (i.e. height <= 1078) to prevent the area to be extracted running off the bottom of the input image.

**Comment by scorpp** [comment]
sorry, my bad. this is indeed correct.

i'm having a trouble in my app, but it has proven to be difficult to extract the code to a small snippet to reproduce the issue. probably bug is on my side.

thank you for taking a look and sorry for false alarm!
