### ISSUE TITLE
Images arent closed after transforms

### ISSUE THREAD

**Issue by fraancosan** [lovell/sharp#4072]
- [ x ] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What are the steps to reproduce?

I upload an image with multer, then with Sharp I transform it to .webp and then save the image as .webp, then I try to delete the previous image but I can't because sharp keeps it open even though it has finished doing all its work.
I already checked and Multer is not the problem. I am trying to delete the images with fs.rm. I also tried with fs.unlink but to no avail.
Also to double check I tried to delete another image uploaded manually and then used to create a new image but the result was the same.
All the images that Sharp uses to create new ones does not close automatically. I also tried deleting the images manually but I get the same error (the problem is not fs.rm or fs.unlink), it only stops giving me the error if the application closes

#### Functions
![funtions](https://github.com/lovell/sharp/assets/78979358/bd619983-349f-4ebf-9cde-3919c795c07d)
#### Main
![execution](https://github.com/lovell/sharp/assets/78979358/eaf3244a-7e0c-40a4-9f60-d816fabcaf8b)
#### Error
![error](https://github.com/lovell/sharp/assets/78979358/15343290-0101-4aed-8339-35912299d2b3)

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/415
