### ISSUE TITLE
Issue setting a color of an element in an SVG

### ISSUE THREAD

**Issue by HyperGeil** [lovell/sharp#4073]
![qrframe](https://github.com/lovell/sharp/assets/35117943/883adf9c-0b6a-4cbd-9ee2-1abfd5032125)
## Question about an existing feature
How do I change the black part of the attached SVG - and sorry for the eventual newbee question

### What are you trying to achieve?

If I use .tint:
.tint({ r: 255, g: 0, b: 0})

I can hit the part but not the RED as it is "tint" if I use .flatten:
.flatten({background: {r: 255, g: 0, b: 0, alpha: 0.5 }})

I hit the corners.

### When you searched for similar issues, what did you find that might be related?

Haven't found anything really usable

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

import sharp from 'sharp';

async function resizeImage() {
  try {
    await sharp("./content/qrframe.svg")
    .resize({
      width: 800,
    })
    .flatten({background: {r: 255, g: 0, b: 0, alpha: 0.5 }})
    .toFile("./content/qrframe-resized.png");
  } catch (error) {
    console.log(error);
  }
}

resizeImage();

------

import sharp from 'sharp';

async function resizeImage() {
  try {
    await sharp("./content/qrframe.svg")
    .resize({
      width: 800,
    })
    .tint({ r: 255, g: 0, b: 0})
    .toFile("./content/qrframe-resized.png");
  } catch (error) {
    console.log(error);
  }
}

resizeImage();

### Please provide sample image(s) that help explain this question

Source SVG attached

**Comment by lovell** [comment]
> How do I change the black part of the attached SVG 

```diff
-        fill: #0d1b21;
+        fill: #ff0000;
```

**Comment by HyperGeil** [comment]
> > How do I change the black part of the attached SVG
> 
> ```diff
> -        fill: #0d1b21;
> +        fill: #ff0000;
> ```

Thank you so much - and now my newbee question, where do I put that in the code? :)

**Comment by lovell** [comment]
> where do I put that in the code?

You don't. The diff I provided is the change you'll need to make to the SVG file in order to alter the fill colour.

**Comment by HyperGeil** [comment]
Thank you for the assistance - I will get that tested.

**Comment by HyperGeil** [comment]
Closing
