### ISSUE TITLE
Remove white pixels to have a transparent background

### ISSUE THREAD

**Issue by LouisR-P** [lovell/sharp#4076]
### What are you trying to achieve?

I am trying to remove white pixels (RGB ➡️ 255 255 255, but also close values like 255 254 255 or 253 255 255 for example) from any random clothes images.

### When you searched for similar issues, what did you find that might be related?

I found [this](https://github.com/lovell/sharp/issues/3989), so I tried to use threshold and unflatten.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```
const processedPantsImage = await sharp(pantsImage)
        .threshold(0, { greyscale: false })
        .unflatten()
        .toBuffer();
```
With this code ⬆️, im having this result:
Before:
![trouser](https://github.com/lovell/sharp/assets/46956027/e5af78e7-9b09-473c-a02d-af03a87b3222)
After:
<img width="275" alt="image" src="https://github.com/lovell/sharp/assets/46956027/7074c4e3-d152-4075-8ed8-f51058460040">

This is good but not perfect, it seems to remove the whitest pixels (255 255 255) but not the darkest ones (253 255 255) for example as you can see still some white part staying around the pant.

So I tried different values/options in thresold but I never manage to found one. I tried 
```
const processedPantsImage = await sharp(pantsImage)
        .threshold(240, { greyscale: false })
        .unflatten()
        .toBuffer();
```
But I gave me a strange black pants in result 😅 Im not sure to really understand how this works

Could you help me finding the correct values I need or give me a better solution? Thanks!

**Comment by LouisR-P** [comment]
any clues? @lovell

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/api-operation#unflatten

> Existing alpha channel values for non-white pixels remain unchanged.

This means `unflatten` is probably the wrong solution to your problem as you also want non-fully-white pixels to become transparent.

I'd use `threshold` to create a single-channel negative mask:

```js
await sharp(input)
  .negate()
  .threshold(5)
  .toFile("mask.png");
```

You can then attach this as an alpha channel:

```js
await sharp(input)
  .joinChannel("mask.png")
  .toFile("output.png");
```

![](https://github.com/lovell/sharp/assets/210965/c98d5933-6549-475e-99d1-25b249399f80)

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
