### ISSUE TITLE
Question: Why does the result of image.raw().extractChannel('red').toBuffer.length != image.width * image.height?

### ISSUE THREAD

**Issue by ndtreviv** [lovell/sharp#4078]
### What are you trying to achieve?
I want to apply a moving box convolution over the image, which involves calculating the intensity of each pixel according to it's individual RGB values. 
To do this, I need to iterate over each pixel, extract the RGB values and then calculate the intensity, which is then used in a specific convolution calculation.

I noticed that the API offers an `.extractChannel(channel)` function, so I was running this for each channel and then indexing the buffer to get the R, G or B value.

However, the length of the buffers are not the same as the number of pixels in the image.

### When you searched for similar issues, what did you find that might be related?

I searched the documentation for clues.
I searched the issues in this repo for "extractChannel" for something else that might suggest I was doing something incorrectly.
I searched Google for how to extract RGB values, but didn't find much help beyond what I was already doing.
I asked ChatGPT, and it suggested memory limitations in this library cutting off the output.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```
const filePath = "path/to/my/file.jpg";
const imageData = fs.readFileSync(filePath);
let png = await sharp(imageData).removeAlpha().png().raw();
const metadata = await png.metadata();
const red = await png.extractChannel('red').toBuffer();
const green = await png.extractChannel('green').toBuffer();
const blue = await png.extractChannel('blue').toBuffer();
console.log("Pixels: ", metadata.width * metadata.height, "Red: ", red.length, "Green: ", red.length, "Blue: ", red.length);
//Output with test image below is: 7555168 2252000 2252000 2252000
```

### Please provide sample image(s) that help explain this question

![992E7F2E-580A-4F54-A300-5273CF85F752](https://github.com/lovell/sharp/assets/1530653/b9819c25-0c4b-4cf4-a618-6606def44971)

**Comment by lovell** [comment]
Assuming you want `png` to contain PNG image data and `red` etc. to contain raw pixel data, you'll probably need to make something like the following changes:
```diff
- let png = await sharp(imageData).removeAlpha().png().raw();
+ let png = await sharp(imageData).removeAlpha().png().toBuffer();
```

```diff
- const red = await png.extractChannel('red').toBuffer();
+ const red = await png.extractChannel('red').raw().toBuffer();
// etc.
```

**Comment by ndtreviv** [comment]
I have tried variations, including the one above, and I get the same results.

eg:
```
const imageData = fs.readFileSync(filePath);
let image = await sharp(imageData).removeAlpha().png();
const metadata = await image.metadata();

var width = metadata.width;
var height = metadata.height;
var channels = metadata.channels;

const total = await image.toBuffer(); // image.raw().toBuffer() has the same result

const red = await image.extractChannel('red').raw().toBuffer();
const green = await image.extractChannel('green').raw().toBuffer();
const blue = await image.extractChannel('blue').raw().toBuffer();

console.log("lengths", total.length, width, height, channels, red.length, green.length, blue.length);
// Output: lengths 6756000 3664 2062 3 2252000 2252000 2252000
// Actual number of pixels: 7,555,168
```

Perhaps I should be asking a different question: How do I access the R, G and B values for each pixel in the image using sharp?

ChatGPT suggests:
```
// Load the image
sharp('input.jpg')
  .raw() // Get the raw pixel data
  .toBuffer((err, data, info) => {
    if (err) throw err;

    const { width, height, channels } = info;
    
    // Iterate over each pixel
    for (let y = 0; y < height; y++) {
      for (let x = 0; x < width; x++) {
        // Calculate the index of the pixel in the raw data
        const pixelIndex = (y * width + x) * channels;
        
        // Extract R, G, and B values
        const red = data[pixelIndex];
        const green = data[pixelIndex + 1];
        const blue = data[pixelIndex + 2];

        // Do something with the R, G, and B values (e.g., log them)
        console.log(`Pixel at (${x}, ${y}): R=${red}, G=${green}, B=${blue}`);
      }
    }
  });
```
but to me, that would suggest that `.raw().toBuffer()` returns a Buffer that is `channels * (height * width)`, when it's actually smaller than `(height * width)`...

I feel like I'm definitely missing something here.
All/any help appreciated.

**Comment by ndtreviv** [comment]
OK, yeah, I was being an idiot. I've figured it out.
I was actually resizing the image without realising it (code paths), but had fetched the metadata before hand.
