### ISSUE TITLE
How to change OwnerName by withExifMerge?

### ISSUE THREAD

**Issue by ramoures** [lovell/sharp#4079]
### How to change OwnerName by withExifMerge?

The OwnerName of my photos is currently: undifined.
I want rewrite OwnerName tag:

`await sharp(process.cwd() + '/public/uploads/' + name).composite([{ input: svg }]).toFormat('jpg').jpeg({ mozjpeg: true }).withExifMerge({
        IFD0: {
            Artist: 'artist name',
            Copyright: 'artist name. All rights reserved.',
            ImageDescription: 'my desc',
            OwnerName: 'artist name'
        },
        ExifIFD: {
            OwnerName: 'artist name'
        }
 })`
 
 But only the OwnerName does not change.

**Comment by lovell** [comment]
Did you mean the `CameraOwnerName` property of the `Photo` (IFD2) directory?

```js
  .withExifMerge({
    IFD2: { CameraOwnerName: "artist name" },
  })
```

https://exiftool.org/TagNames/EXIF.html

**Comment by ramoures** [comment]
> Did you mean the `CameraOwnerName` property of the `Photo` (IFD2) directory?
> 
> ```js
>   .withExifMerge({
>     IFD2: { CameraOwnerName: "artist name" },
>   })
> ```
> 
> https://exiftool.org/TagNames/EXIF.html

Problem solved. Thank you!.
I didn’t know that OwnerName are the same as CameraOwnerName, and it should be in the IFD2 group.
OwnerName is in the `ExifIFD` group in the link you posted.
Is there another document that lists all the key/value that can be used with withExifMerge object in Sharp?
my english is not good. sorry.

**Comment by lovell** [comment]
I meant to add that the `ExifIFD` and `Photo` directories are equivalent, both being `IFD2`.

The source of truth is the libexif source code e.g. https://github.com/libexif/libexif/blob/95a752db3b1bdbc222872e42c36942c96faa8862/libexif/exif-tag.c#L909
