### ISSUE TITLE
Cross-compilation broken on npm@10.4.0 and 10.5.0

### ISSUE THREAD

**Issue by bhallstein** [lovell/sharp#4080]
## Possible install-time or require-time problem

- [x] I have read and understood all of the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have searched for known bugs relating to this problem in my choice of package manager.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### Are you using a supported runtime?

- [x] I am using Node.js with a version that satisfies `^18.17.0 || ^20.3.0 || >=21.0.0`

### Are you using a supported package manager and installing optional dependencies?

- [x] I am using npm >= 9.6.5 with `--include=optional`

### What is the complete error message, including the full stack trace?

When installing sharp with `npm i --cpu=x64 --os=linux --include=optional sharp@0.33.3`, the `node_modules/@img` directory is empty.

I believe this is a regression in npm so have raised an issue over at https://github.com/npm/cli/issues/7406, but thought it would be helpful to report here as well as it breaks sharp cross-compilation. I expect the fix will be to wait for npm to be fixed :)

**Comment by lovell** [comment]
Did you see https://sharp.pixelplumbing.com/install#cross-platform

> ⚠️ npm `package-lock.json` files can cause installation problems due to [npm bug #4828](https://github.com/npm/cli/issues/4828)

**Comment by lovell** [comment]
Works for me:
```sh
$ node -p "[process.arch,process.platform]"
[ 'x64', 'linux' ]

$ npm -v
10.5.0

$ rm -rf node_modules/ package-lock.json package.json

$ npm i --cpu=arm64 --os=darwin --include=optional sharp@0.33.3

added 13 packages in 5s

$ ls node_modules/@img/
sharp-darwin-arm64  sharp-libvips-darwin-arm64
```

**Comment by bhallstein** [comment]
@lovell Thanks for the replies. I perhaps should have mentioned that existing package.json and package-lock.json are already being removed by our build script before `npm i ...sharp@0.33.3` is called.

```
Desktop:$ mkdir temp; cd temp
temp:$ node -p "[process.arch,process.platform]"
[ 'arm64', 'darwin' ]
temp:$ npm -v; npm i --cpu=x64 --os=linux --include=optional sharp@0.33.3
10.5.0
added 11 packages in 1s
temp:$ ls -l node_modules/\@img/
total 0
```

Perhaps issue may be platform specific?

**Comment by lovell** [comment]
Thanks for the extra info. Assuming glibc-based Ubuntu is the target OS, does adding the `--libc=glibc` flag make any difference when run on the Mac?

https://github.com/npm/npm-install-checks

**Comment by bhallstein** [comment]
With `npm i --cpu=x64 --os=linux --libc=glibc --include=optional sharp@0.33.3`:

```
temp:$ ls -1 node_modules/\@img/
sharp-libvips-linux-x64
sharp-linux-x64
```

🎉

**Comment by lovell** [comment]
Thanks for confirming, I've updated the sharp docs via commit https://github.com/lovell/sharp/commit/ba843002be2b8318921776804d83411dc2d1ee5e to help clarify this.

It might be worth you updating https://github.com/npm/cli/issues/7406 with this information as the npm documentation could probably do with this detail too.

**Comment by bhallstein** [comment]
Thanks @lovell, just noting that in the linked npm issue they’ve confirmed that the npm 10.4.0+ behaviour is as intended, so your helpful documentation tweak should stand for the foreseeable future 👍
