### ISSUE TITLE
.trim().toBuffer() does not produce info response Object offset properties

### ISSUE THREAD

**Issue by Zirafnik** [lovell/sharp#4085]
## Possible bug

When using `.trim().toFile()` it will return a metadata object, which includes the `trimOffsetLeft` and `trimOffsetTop` properties.

When we instead save to buffer with `.trim().toBuffer()` no such properties will become available on the response object.

While I am not sure what is happening in the background, I believe that the offset data is available before saving the image (as this data is used in the operation itself) so it should also be available on the final returned object.

### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

**Comment by lovell** [comment]
Did you see the `resolveWithObject` property of `toBuffer()`?

https://sharp.pixelplumbing.com/api-output#tobuffer

```js
const { data, info } = await sharp(input).toBuffer({ resolveWithObject: true });
const { trimOffsetLeft, trimOffsetTop } = info;
```

**Comment by Zirafnik** [comment]
Thank your for the answer. I did not realize this would include the info object from `.trim()`. This now works.
