### ISSUE TITLE
Use of process.exit in mocha timeout causes GLib-CRITICAL on noflo-sharp

### ISSUE THREAD

**Issue by automata** [lovell/sharp#409]
First of all, I couldn't reproduce this on *sharp* alone, even using the same [code snippet](https://github.com/noflo/noflo-sharp/blob/master/components/Resize-node.coffee#L50-L53). However I can't help finding a solution for it, and since it's related with _sharp_, I'm hoping we can investigate it together :smile:.

While trying to send this [GIF file](https://github.com/noflo/noflo-sharp/blob/test-large-gif/spec/fixtures/big.gif) to `Resize` component on [noflo-sharp](https://github.com/noflo/noflo-sharp) (I have [a test](https://github.com/noflo/noflo-sharp/blob/test-large-gif/spec/Resize.coffee#L412-L424) for this case), I'm getting the following:

```
(sharp:5885): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed
Trace/breakpoint trap (core dumped)
```
I'm being able to reproduce it on an Ubuntu 14.04 box using latest _sharp_, and the same happens on [Travis CI](https://travis-ci.org/noflo/noflo-sharp/jobs/122859324#L3390).

While analyzing the core dump executing by `gdb --args $(which node) ./node_modules/.bin/mocha spec/Resize` (on noflo-sharp):

```
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/vilson/.nvm/versions/node/v4.2.6/bin/node...done.
(gdb) core core
warning: core file may not match specified executable file.
[New LWP 28674]
[New LWP 28667]
[New LWP 28668]
[New LWP 28664]
[New LWP 28665]
[New LWP 28666]
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `grunt                                          '.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  0x00007f7194078d0c in g_logv ()
   from /home/vilson/src/noflo/noflo-sharp/node_modules/sharp/build/Release/../../lib/libglib-2.0.so.0
(gdb) bt full
#0  0x00007f7194078d0c in g_logv ()
   from /home/vilson/src/noflo/noflo-sharp/node_modules/sharp/build/Release/../../lib/libglib-2.0.so.0
No symbol table info available.
#1  0x00007f7194078e92 in g_log ()
   from /home/vilson/src/noflo/noflo-sharp/node_modules/sharp/build/Release/../../lib/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f719405d9f4 in g_hash_table_lookup ()
   from /home/vilson/src/noflo/noflo-sharp/node_modules/sharp/build/Release/../../lib/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f7187b98824 in vips_cache_operation_lookup ()
   from /home/vilson/src/noflo/noflo-sharp/node_modules/sharp/build/Release/../../lib/libvips.so.42
No symbol table info available.
#4  0x00007f7187b98a59 in vips_cache_operation_buildp ()
   from /home/vilson/src/noflo/noflo-sharp/node_modules/sharp/build/Release/../../lib/libvips.so.42
No symbol table info available.
#5  0x00007f719439566c in vips::VImage::call_option_string(char const*, char const*, vips::VOption*) ()
   from /home/vilson/src/noflo/noflo-sharp/node_modules/sharp/build/Release/../../lib/libvips-cpp.so.42
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#6  0x00007f7194395c36 in vips::VImage::new_from_file(char const*, vips::VOption*) ()
   from /home/vilson/src/noflo/noflo-sharp/node_modules/sharp/build/Release/../../lib/libvips-cpp.so.42
No symbol table info available.
#7  0x00007f71945b6fc2 in MetadataWorker::Execute() ()
   from /home/vilson/src/noflo/noflo-sharp/node_modules/sharp/build/Release/sharp.node
No symbol table info available.
#8  0x0000000000fac641 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:95
        w = 0x2771740
        q = 0x2771758
#9  0x0000000000fbb279 in uv__thread_start (arg=<optimized out>)
    at ../deps/uv/src/unix/thread.c:49
        ctx_p = <optimized out>
        ctx = {entry = 0xfac5a0 <worker>, arg = 0x0}
#10 0x00007f7196ba0182 in start_thread (arg=0x7f717c22e700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7f717c22e700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140125390694144, -6163230216398523673,
                0, 0, 140125390694848, 140125390694144, 6094837594223063783,
                6094746548175287015}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0,
              0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
---Type <return> to continue, or q <return> to quit---
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#11 0x00007f71968cd47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.
(gdb)
```
Environment variable are pointing to sharp's:

```
echo $LD_LIBRARY_PATH
./node_modules/sharp/lib
```
If there's more information I should provide, please just ask.

**Comment by lovell** [comment]
Hello, this looks like #401, specifically https://github.com/lovell/sharp/issues/401#issuecomment-208280508 - I suspect there are multiple versions of libvips installed. sharp no longer needs libvips to be available globally - are you able to remove these manually, or perhaps try on a fresh (virtual) machine?

**Comment by automata** [comment]
@lovell funny thing is it's also happening on Travis CI which starts fresh at every new build. I tried to find `libvips.so`, `libvips.pc` following [a #401 comment](https://github.com/lovell/sharp/issues/401#issuecomment-209314056) but found only `*.so` files bundled together with _sharp_. However I'll try it in a fresh machine.

Please let me know if you suspect of something else. Thanks.

**Comment by automata** [comment]
Hmm comparing _sharp_'s Travis config with _noflo-sharp_'s, I have `libgif-dev` being installed. Unfortunately I can't remove it because _noflo-sharp_ also depends on _node-canvas_ which has `libgif` as dependency. Maybe it's related?

**Comment by lovell** [comment]
Aha, this could well be related to #371. Are you able to alter the `require` order of canvas and sharp so that sharp is always first and therefore its newer glib takes precedence?

**Comment by automata** [comment]
I altered `require` order but the issue continues: https://travis-ci.org/noflo/noflo-sharp/jobs/123116294

**Comment by lovell** [comment]
I think the problem you're seeing in Travis is that the `Resize component when passed a large GIF file should resize it to the specified dimension` test is timing out and `mocha` is calling `process.exit` in the middle of a resizing task.

Node (more specifically libuv) doesn't wait for any running threads to join before killing them, so what you're seeing is an assertion error from a libvips-spawned thread because a dying libuv-spawned thread took `hash_table` with it.

If you're likely to need to use `process.exit` whilst images are being processed then you probably want to also use `sharp.concurrency(1)` to reduce the effects this causes.

**Comment by automata** [comment]
@lovell in fact when I increase timeout the test passes. Probably the same is happening on production: something is killing resize while it is still resizing?

**Comment by automata** [comment]
I tried to use `sharp.concurrency(1)` and let timeout as it was but it crashes.

**Comment by lovell** [comment]
Thanks for confirming @automata and glad to hear you got it working.

Watch out for process "managers" that call `process.exit`. https://github.com/lovell/sharp/issues/180#issuecomment-85550923 might be relevant here too.

**Comment by automata** [comment]
@lovell do you know if people is using both `sharp` and `node-canvas` together? I'm experiencing the same glib errors but in random places now, on my project:

```
(sharp:9316): GLib-GObject-CRITICAL **: /build/buildd/glib2.0-2.32.4/./gobject/gtype.c:2722: You forgot to call g_type_init()
(sharp:9316): GLib-CRITICAL **: g_once_init_leave: assertion `result != 0' failed
(sharp:9316): GLib-GObject-CRITICAL **: /build/buildd/glib2.0-2.32.4/./gobject/gtype.c:2722: You forgot to call g_type_init()
(sharp:9316): GLib-CRITICAL **: g_once_init_leave: assertion `result != 0' failed
```

**Comment by lovell** [comment]
Ola, I see you've discovered the related #371. Are you requiring `sharp` before `node-canvas` and any other module that might use glib? The `/build/buildd/glib2.0-2.32.4` part of the error suggests something else invoked a call to the system-level shared library before `sharp` was `require`d.

**Comment by automata** [comment]
Probably, it's a NoFlo project, so components are loaded in mixed order. We have many `noflo-canvas` components.

**Comment by lovell** [comment]
If you're able to upgrade, the new Ubuntu 16.04 LTS provides the up-to-date [glib v2.48.0](http://packages.ubuntu.com/xenial/libglib2.0-dev) which should "fix" this.

**Comment by automata** [comment]
@lovell it's running at Heroku, so Ubuntu 16.04 LTS is not a possibility, unfortunatelly.

**Comment by automata** [comment]
@lovell aha! Downgrading to `sharp` 0.13.1` I don't get the `glib` error anymore.

Now I'm back to the case where my process is killed because it's using lots of memory with that large GIF :-)

**Comment by lovell** [comment]
If you can control how your app is started in Heroku then you can use the following to guarantee sharp's glib takes precedence:
```sh
LD_PRELOAD=/path/to/node_modules/sharp/lib/libglib-2.0.so /usr/bin/node yourapp.js
```

GIF support (speed, memory usage) will be vastly improved in v0.15.0 thanks to #369.

**Comment by automata** [comment]
@lovell as a workaround I'm using `gm` to extract first frame of GIFs before using `sharp`. I'm following #369, when done I'll remove `gm` and test it again.

About `glib` error, any thoughts about why it was happening only on ` sharp 0.14.x`?

**Comment by lovell** [comment]
> "About glib error, any thoughts about why it was happening only on sharp 0.14.x?"

sharp v0.14.x bundles [glib v2.47.6](https://github.com/lovell/sharp/blob/v0.14.1/packaging/lin/Dockerfile#L23) and sharp v0.13.x bundles [glib v2.47.5](https://github.com/lovell/sharp/blob/v0.13.1/packaging/lin/Dockerfile#L23). I don't see anything in the glib [changelog](https://github.com/GNOME/glib/blob/master/NEWS) about changes to gtype/gonce behaviour though :(

**Comment by automata** [comment]
I'll test it a bit more. Thank you for all your help until now @lovell!

**Comment by automata** [comment]
@lovel we're updating to sharp 0.15 to get GIF goodies and get rid of ImageMagick vulnerability, however I can confirm we're having the same issue (on Travis for now, will test in Heroku as soon as I get this fixed):

```
(sharp:9330): GLib-GObject-CRITICAL **: /build/buildd/glib2.0-2.32.4/./gobject/gtype.c:2722: You forgot to call g_type_init()
(sharp:9330): GLib-CRITICAL **: g_once_init_leave: assertion `result != 0' failed
(sharp:9330): GLib-GObject-CRITICAL **: /build/buildd/glib2.0-2.32.4/./gobject/gtype.c:2722: You forgot to call g_type_init()
(sharp:9330): GLib-CRITICAL **: g_once_init_leave: assertion `result != 0' failed
```

**Comment by lovell** [comment]
Thanks for the update. Your best options are still either ensuring `sharp` is require'd before `canvas` or set the `LD_PRELOAD=...` env variable.

**Comment by automata** [comment]
Yeah, I'm trying to `LD_PRELOAD=./node_modules/noflo-sharp/node_modules/sharp/lib/libglib-2.0.so ./node_modules/.bin/grunt test` but I'm still getting the same error.

**Comment by automata** [comment]
Thanks to @jonnor suggestion we used a workaround: we updated libvips to 8.3.1 on [this buildpack/bundle](https://github.com/jonnor/heroku-buildpack-vips) and we're using it in both Travis/Heroku. In this way, both node-canvas and sharp are using the same "global" GLib.

(At the same time we removed ImageMagick and included giflib/libsvgr to match dependencies for sharp 0.15 and to be free from IM vulnerability)

**Comment by automata** [comment]
@lovell should we close this? IMHO above workaround can be used as a suggestion to similar cases at future.

**Comment by lovell** [comment]
Yes, there's plenty of info in here for anyone else that wanders into this problem. Thanks again for all your thoughts, ideas and feedback here.

**Comment by automata** [comment]
@lovell I'll probably revisiting this issue soon while updating noflo-sharp to sharp 0.17. Do you know if we have some improvements on this issue? Thanks in advance.

**Comment by niftylettuce** [comment]
@lovell Per the other issue - my issue was due to `aws-sdk` (unrelated to sharp) - thank you 👍
