### ISSUE TITLE
When loading a picture using a file path, the size of the picture exceeds a certain size, and then deleting the picture will cause a problem of prohibiting deletion.

### ISSUE THREAD

**Issue by Vueu** [lovell/sharp#4093]
### Code that will cause errors
```js
const fs = require("fs/promises")

async function upload(){
  let path = './input.jpg'   // 5M
  await sharp(path)
    .resize({ width: 150, height: 150 })
    .webp({ quality: 100 })
    .toFile(path_webp);
  await fs.unlink(path)
}
```

### Error
```
Error: EPERM: operation not permitted, unlink 'C:\\Users\\user\\Desktop\\project\\public\\upload\\input.jpg'
```

### Possible bugs
Possible bug: When sharp loads a picture that is too large, the picture will not be closed, resulting in the picture being unable to be deleted.

### A solution to the problem
Read the data through `fs.readFile` and pass it to sharp.
```js
const fs = require("fs/promises")

async function upload(){
  let path = './input.jpg'   // 5M

  let data = await fs.readFile(path) 
  await sharp(data)
    .resize({ width: 150, height: 150 })
    .webp({ quality: 100 })
    .toFile(path_webp);
  await fs.unlink(path)
}
```

**Comment by lovell** [comment]
The issue template that was ignored/deleted provides the answer.

<hr>

### Does this problem relate to file caching?

The default behaviour of libvips is to cache input files, which can lead to `EBUSY` or `EPERM` errors on Windows.
Use [`sharp.cache(false)`](https://sharp.pixelplumbing.com/api-utility#cache) to switch this feature off.

**Comment by Vueu** [comment]
I'm glad to receive your reply. The method you mentioned effectively solved the problem. I will spend more time learning sharp. Thank you so much!
