### ISSUE TITLE
Using node js sharp package composite function is not giving an animated result

### ISSUE THREAD

**Issue by Niece7** [lovell/sharp#4094]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error..

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What are the steps to reproduce?

```
const Discord = require('discord.js');
const sharp = require('sharp');
const client = new Discord.Client({ intents: ["GUILDS", "GUILD_MESSAGES"] });

client.on('messageCreate', async message => {
    if (message.content === '!merge') {
        const background = await sharp('logo.png').resize(288, 288);
        const overlay = await sharp('animated.png').resize(288, 288); // PNG image that has animated frames like a gif

        const result = await background.composite([{ input: await overlay.toBuffer(), gravity: 'center' }]).toBuffer();

        message.channel.send({ files: [result] });
    }
});

client.login('your-token');
```

### What is the expected behaviour?

It was supposed to be an animated GIF result instead of a static image

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

=> I haven't found a solution to this problem for about a week.
### Please provide sample image(s) that help explain this problem

=> Get the result of a static image, not a moving image with frames

![result](https://github.com/lovell/sharp/assets/155916815/a0bdedfb-30c7-4b39-b864-81f53629a5f9)

=> I should get this perfect result that I wanted

![output-ezgif com-loop-count](https://github.com/lovell/sharp/assets/155916815/5d35854d-0569-452d-8040-f47a323bf10d)

**Comment by Niece7** [comment]
> The issue you are expressing does not exist. See this [SO Answer](https://stackoverflow.com/questions/78433605/how-to-composite-a-static-background-image-and-gif-with-sharp-nodejs-package/78433606#78433606) for how you might do this. And this [SO Answer](https://stackoverflow.com/questions/78430894/using-node-js-sharp-package-composite-function-is-not-giving-an-animated-result/78430915#78430915) addresses your specific code. The only annoying behavior I see here is the fact that the metadata result is unchanged as far as format, etc... But isn't a big problem.

Thanks for that. I want to ask you, is it possible to make a PNG image instead of a GIF, by merging it with a PNG image?

Because the PNG image contains animated frames,

thank,

**Comment by lovell** [comment]
Cross-posted, with possible solution, at https://stackoverflow.com/questions/78430894/using-node-js-sharp-package-composite-function-is-not-giving-an-animated-result

**Comment by Niece7** [comment]
Thank you all @TISHARP & @lovell
