### ISSUE TITLE
Issue with Color Consistency in CMYK Space When Using "Composite" in Sharp

### ISSUE THREAD

**Issue by tars-mj** [lovell/sharp#4097]
Hello,

I'd like to report an issue with the Sharp library regarding colors in the CMYK space. I know that in earlier versions there was a huge problem with this, but for some time now, you've significantly improved the flow of information related to CMYK colors, which makes the library more useful for working with CMYK. Now, it's possible to retain input colors in the output file after certain transformations. Below is an example where the input file is in CMYK, and the output colors are the same as the input:

```tsx
const modulatedImage = sharp('./input.tif', {ignoreIcc: true})
    .pipelineColourspace("cmyk")
		.toColourspace("cmyk")
		.keepIccProfile()
		.extend({
			top: 10,
			bottom: 20,
			left: 10,
			right: 10,
			background: { r: 0, g: 0, b: 0, alpha: 0 }
		})
		.toFile('./output.tif')
```

Below is a preview of the input and output files, which have exactly the same components in the CMYK space. This was not possible in Sharp before, so it's working great:

![image](https://github.com/lovell/sharp/assets/8572999/aba604b9-df85-48a3-8a13-a9bb61110352)

However, the problem I want to point out arises when using "composite”:

```tsx
const overlay = `<svg width="800" height="300">
    <text x="400" y="150" font-family="sans-serif" dominant-baseline="middle" font-size="150" text-anchor="middle">overlay</text>
    </svg>`

const modulatedImage = sharp('./input.tif', {ignoreIcc: true})
    .pipelineColourspace("cmyk")
		.toColourspace("cmyk")
		.keepIccProfile()
		.extend({
			top: 10,
			bottom: 20,
			left: 10,
			right: 10,
			background: { r: 0, g: 0, b: 0, alpha: 0 }
		})
		.composite([
			{
				input: Buffer.from(overlay),
				top: 0,
				left: 0,
				limitInputPixels: false,
				ignoreIcc: true,
			},
		])
		.toFile('./output.tif')
```

The output file unfortunately has different colors in the CMYK space.

![image](https://github.com/lovell/sharp/assets/8572999/9a907972-9aaa-4a8f-9fb7-644bfe54ab6d)

Overall, I'm very pleased with the addition of pipelineColourspace and keepIccProfile, but to fully enjoy this solution, the composite tool should be adjusted for it.

**Comment by lovell** [comment]
Did you see the future possible enhancement at https://github.com/lovell/sharp/issues/3650 ?

**Comment by tars-mj** [comment]
> Did you see the future possible enhancement at #3650 ?

Looks promising - I hadn't seen this, thanks!
