### ISSUE TITLE
Vector file to PNG doesn't preserve transparent alpha channel

### ISSUE THREAD

**Issue by lookfirst** [lovell/sharp#410]
The output is an image on a white background. I've tried various combinations of `embed()` and `background({a: 0})` to no effect.

```
	let transform = (width, height, density, toFormat) => {
		return sharp(null, {density: density})
			.resize(width, height)
			.max()
			.withoutEnlargement()
			.toFormat(toFormat);
	};
```

**Comment by lovell** [comment]
Is this on OS X? I suspect this is related to the version and fork of *magick in use. If you're using ImageMagick, are you able to try GraphicsMagick (or vice versa)? https://github.com/Homebrew/homebrew-science/blob/master/vips.rb#L50

**Comment by lookfirst** [comment]
I'm using GM and brew for everything. That said, you're right, I needed to update vips, which is my bad. Tried to brew upgrade and just got this (knowing full well this isn't the right forum but figured I'd let you know anyway):

```
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/vips/8.3.0 --with-magick --with-magickpackage=GraphicsMagick
==> make install
Last 15 lines from /Users/jon/Library/Logs/Homebrew/vips/02.make:
magick2vips.c:229:21: error: no member named 'scenes' in 'struct _ImageInfo'
                read->image_info->scenes = strdup( page );
                ~~~~~~~~~~~~~~~~  ^
3 errors generated.
make[2]: *** [magick2vips.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
l
```

**Comment by lovell** [comment]
https://github.com/Homebrew/homebrew-science/issues/3123 suggests an attempt to upgrade may require completely uninstalling vips and graphicsmagick (and their dependencies) before reinstalling vips.

**Comment by lovell** [comment]
See https://github.com/jcupitt/libvips/issues/423

**Comment by lookfirst** [comment]
Uninstalling GM and vips and then re-installing worked. Thanks!

**Comment by lookfirst** [comment]
Interesting, new error!

```
Error: Error: Input buffer contains unsupported image format
    at [object Object].<anonymous> (server.js:52:9)
    at emitOne (events.js:95:20)
    at [object Object].emit (events.js:182:7)
    at /Users/jon/gearlaunch/banksy/node_modules/sharp/index.js:856:18
```

I'm trying to convert a .ai file to a .png file. This used to work, but didn't give me the transparent alpha channel. =)

**Comment by lovell** [comment]
My best guess is that the version/fork of *magick you're now using was compiled without support for the .ai format.

**Comment by lookfirst** [comment]
I'm able to use `gm convert foo.ai foo.png` on the command line.

**Comment by lovell** [comment]
Sadly that's not necessarily the same *magick shared library that vips was compiled against.

**Comment by lookfirst** [comment]
Ah yea, I see your point. brew installed a vips binary. I just tried to re-install vips by recompiling it and can't cause of that other error. Ok, I'll wait it out then.

**Comment by felixbuenemann** [comment]
@lookfirst You likely did not enable imagemagick when reinstalling vips, you have to use:

```sh
brew install vips --with-imagemagick
```

You can check if imagemagick supports ai using:

```sh
convert -list format|grep AI
#        AI  PDF       rw-   Adobe Illustrator CS2
```

Or wait for https://github.com/Homebrew/homebrew-science/pull/3569 to land which will fix GraphicsMagick support.

**Comment by lookfirst** [comment]
Ok the above issue was resolved and I got everything re-installed and updated with brew.

I'm still getting the "Error: Error: Input buffer contains unsupported image format".

The same exact file goes through the npm gm module just fine.

**Comment by felixbuenemann** [comment]
Could you check `brew info vips` to ensure it's compiled with graphicsmagick support?

```
/usr/local/Cellar/vips/8.3.0 (186 files, 12.6M) *
  Built from source with: --with-openslide --with-webp --with-graphicsmagick --with-mozjpeg
```

**Comment by lookfirst** [comment]
```
brew info vips
homebrew/science/vips: stable 8.3.0 (bottled)
Image processing library
http://www.vips.ecs.soton.ac.uk/
/usr/local/Cellar/vips/8.3.0 (186 files, 12.6M) *
  Built from source with: --with-graphicsmagick
From: https://github.com/Homebrew/homebrew-science/blob/master/vips.rb
==> Dependencies
Build: pkg-config ✔
Required: fontconfig ✔, gettext ✔, glib ✔
Recommended: libpng ✔, jpeg ✔, orc ✔, libgsf ✔, libtiff ✔, fftw ✔, little-cms2 ✔, pango ✔, libexif ✔, gobject-introspection ✔, pygobject3 ✔, python ✔, poppler ✔, librsvg ✔, giflib ✔
Optional: openslide ✘, imagemagick ✔, graphicsmagick ✔, openexr ✘, cfitsio ✘, webp ✔, python3 ✘, libmatio ✘, mozjpeg ✘, jpeg-turbo ✘
```

**Comment by lookfirst** [comment]
```
brew info graphicsmagick
graphicsmagick: stable 1.3.23 (bottled), HEAD
Image processing tools collection
http://www.graphicsmagick.org/
/usr/local/Cellar/graphicsmagick/1.3.23_1 (478 files, 12.0M) *
  Built from source with: --with-ghostscript
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/graphicsmagick.rb
==> Dependencies
Build: pkg-config ✔
Required: libtool ✔
Recommended: jpeg ✔, libpng ✔, libtiff ✔, freetype ✔
Optional: little-cms2 ✔, jasper ✔, libwmf ✘, ghostscript ✔, webp ✔
```

**Comment by felixbuenemann** [comment]
Just wrote a small test script and I'm getting the same error, evven though `gm convert foo.ai foo.png` and `vips copy foo.ai foo.png` work. Maybe something broke in the loader detection code.

**Comment by felixbuenemann** [comment]
Ah, newer AI files actually embed a PDF file causing the file to be detected by the new poppler PDF loader, which sharp doesn't yet know about.

Vips is returning the loader VipsForeignLoadPdfFile in DetermineImageType().

**Comment by felixbuenemann** [comment]
@lookfirst Until this is fixed, you could work around the issue by reinstalling vips using `brew reinstall vips --with-graphicsmagick --without-poppler` to deactivate the new PDF loader in vips.

**Comment by lovell** [comment]
Great detective work @felixbuenemann - support for libvips compiled with poppler will be in v0.15.0 - see #369

**Comment by lovell** [comment]
@lookfirst Support in sharp for PDF loading via libpoppler is now available for testing on the `outfit` branch:
```sh
npm install lovell/sharp#outfit
```

**Comment by lovell** [comment]
v0.15.0 out now for all your libvips-compiled-with-poppler needs.
