### ISSUE TITLE
Strip EXIF data but keep original image unmodified

### ISSUE THREAD

**Issue by wjmazza** [lovell/sharp#4100]
## Question about an existing feature

Is it possible to use Sharp to strip all EXIF data from the source file and keep the image data unchanged (eg. no compression or lossy)?

### What are you trying to achieve?

Take uploaded photos, strip EXIF data, and then save two versions: the original ("uncompressed") and a low-res thumbnail (okay to be compressed).

When I do what is shown in the example code below, the output of `originalImage` does save without the EXIF data as expected but we did notice the file size compared to the  `sourceImage` was massively different. For example, if `sourceImage` was a 4MB JPEG, the generated `originalImage` is only ~1MB alluding to the possibility of image compression.

It may go against the purpose of Sharp to use it just to strip EXIF data, but we are curious if its possible to keep this as part of our Sharp "pipeline" instead of having to add another Node module, just for convenience sake.

### When you searched for similar issues, what did you find that might be related?

Unfortunately could not find any issues that specifically cover this.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```js
const sharpStream = sharp(sourceImage);

// originalImage
sharpStream.metadata().then((metadata) => {
  const { format } = metadata;
  sharpStream.clone().toFile(`original.${format}`);
});

// thumbnailImage
sharpStream
  .clone()
  .resize({ width: 150, height: 150 })
  .jpeg()
  .toFile("thumbnail.jpg");
```

I should mention that we also tried setting compression to zero and quality to 100 where applicable without any change (but file size does go smaller if we increase/decrease compression/quality respectively)

Node Version: v20.13.1
Sharp Version: 0.33.3

**Comment by lovell** [comment]
sharp will always perform a decode/encode roundtrip - perhaps try [exiftool-vendored](https://github.com/photostructure/exiftool-vendored.js).

Related: #3327

**Comment by wjmazza** [comment]
That is what we figured but wanted to confirm. Thank you for the reply and recommendation!
