### ISSUE TITLE
How to set JFIF with jpg format

### ISSUE THREAD

**Issue by penndev** [lovell/sharp#4102]
## Question about an existing feature

code `sharp(result.data).withMetadata().jpeg({ quality: 100 }).toBuffer()` output image is exif (file byte header`ff d8 ff e1`)

### What are you trying to achieve?

want output image is jfif (file byte header`ff d8 ff e0`)

like this image [avatar](https://avatars.githubusercontent.com/u/42759565?v=4)

### When you searched for similar issues, what did you find that might be related?

some old android tv box  device,just show jfif jpg file,not support exif jpg  
https://github.com/lovell/sharp/issues/700
https://github.com/lovell/sharp/issues/3855

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question
```
        const result = await axios.get(picUri, {
            timeout: 30 * 1000,
            responseType: 'arraybuffer'
        })
        if (result.status === 200 && result.data) {
            return await sharp(result.data).withMetadata().jpeg({ quality: 100 }).toBuffer()
        }
```

**Comment by lovell** [comment]
libvips configures libjpeg to use `ff d8 ff e1` as the first 4 bytes for images with EXIF metadata and `ff d8 ff db` ("raw") for images without EXIF metadata.

See https://github.com/libvips/libvips/issues/349

**Comment by penndev** [comment]
Got it. I need to conduct more in-depth research to solve my problem.
