### ISSUE TITLE
Install within Docker & PNPM

### ISSUE THREAD

**Issue by nike1v** [lovell/sharp#4106]
## Possible install-time or require-time problem
Should be install-time, but errors appears only after deployment.

- [x] I have read and understood all of the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have searched for known bugs relating to this problem in my choice of package manager.

You must confirm both of these before continuing.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest,
please open an issue against that package instead.

### Are you using a supported runtime?

- [x] I am using Node.js with a version that satisfies `^18.17.0 || ^20.3.0 || >=21.0.0`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these,
please upgrade to the latest version
and try again before opening an issue.

### Are you using a supported package manager and installing optional dependencies?

- [ ] I am using npm >= 9.6.5 with `--include=optional`
- [ ] I am using yarn >= 3.2.0
- [ ] I am using pnpm >= 7.1.0 with `--no-optional=false`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these, please upgrade to the latest version of your chosen package manager
and ensure you are allowing the installation of optional or multi-platform dependencies before opening an issue.

### What is the complete error message, including the full stack trace?

Could not load the "sharp" module using the linuxmusl-x64 runtime

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

Haven't run, because it's in a server docker, not in a local machine.

Haven't run, because it's in a server docker, not in a local machine.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

Haven't run, because it's in a server docker, not in a local machine.

My question is: How can I use sharp within the Docker container and using pnpm package manager, but I do want to use -no-optional flag, so no other packages won't install any of theirs optional packages, but since Sharp require one of those, my application fails. How can I install correct binnary for sharp separately?
Either I should add correct binnary to the dependencies or I should install it globally?
Hope for your help.

**Comment by lovell** [comment]
> I do want to use -no-optional flag, so no other packages won't install any of theirs optional packages

If you do not allow installation of optional dependences, you can add the `@img/sharp-linux...` package appropriate for your runtime environment as an explicit dependency in your own `package.json` file.

https://github.com/lovell/sharp/blob/55466f122cee94e97e94a114b8107e48a2cd13b5/package.json#L154-L159

You'll probably also want to pin to a specific version that matches the version of `sharp`.

**Comment by nike1v** [comment]
> You'll probably also want to pin to a specific version that matches the version of `sharp`.

That's what I thought, ok, Thank you for a quick response!

**Comment by lovell** [comment]
See also https://github.com/pnpm/pnpm/issues/7231
