### ISSUE TITLE
Support metadata for parsing gifs

### ISSUE THREAD

**Issue by hadesgo** [lovell/sharp#4110]
### What are you trying to achieve?

Support metadata for parsing gifs

### When you searched for similar issues, what did you find that might be related?

Input file contains unsupported image format
Error: Input file contains unsupported image format   
at Sharp.metadata (/app/node_modules/sharp/lib/input.js:486:17)

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```
  const result = await new Promise((resolve, reject) => {
    sharp(inputPath)
      .metadata()
      .then(({ exif }) => {
        if (exif) {
          try {
            const exifProperties = exifReader(exif)
            if (exifProperties.Image.Orientation && exifProperties.Image.Orientation > 1) {
              sharp(inputPath, { failOn: 'error' }).rotate().toFile(outPath).then(() => {
                resolve(true)
              }).catch((err) => {
                reject(err)
              })
            } else {
              resolve(false)
            }
          } catch (error) {
            logger.error('[EXIF] Images Path: %s, err: %o', inputPath, error)
            resolve(false)
          }
        } else {
          resolve(false)
        }
      }).catch((err) => {
        reject(err)
      })
  })
```

### Please provide sample image(s) that help explain this question

![664d8a62bc91e](https://github.com/lovell/sharp/assets/74448660/baafa7a6-cee2-475e-9b0b-fbc43d166113)

**Comment by lovell** [comment]
GIF images do support EXIF metadata.

**Comment by hadesgo** [comment]
> GIF images do support EXIF metadata.

But the code reports an error, do you know the reason?

**Comment by lovell** [comment]
The sample image provided works on my machine, the response from `metadata()` is:
```js
{
  format: 'gif',
  width: 300,
  height: 300,
  space: 'srgb',
  channels: 4,
  depth: 'uchar',
  isProgressive: false,
  paletteBitDepth: 7,
  pages: 24,
  loop: 0,
  delay: [
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0
  ],
  background: { r: 36, g: 24, b: 24 },
  hasProfile: false,
  hasAlpha: true
}
```

**Comment by hadesgo** [comment]
Sorry, I made a mistake. It is a picture in BMP format that will throw this error.
