### ISSUE TITLE
How to bundle sharp for AWS Lambda using esbuild CLI

### ISSUE THREAD

**Issue by garysassano** [lovell/sharp#4118]
I see that [the docs](https://sharp.pixelplumbing.com/install#esbuild) exclude `sharp` in esbuild, so that you are forced to create a layer to use it in a Lambda function.

I also saw that some people could find a [workaround](https://stackoverflow.com/questions/76408569/how-do-i-install-sharp-on-my-aws-lambda-via-the-cdk-with-a-custom-install-comman), but that it works only with CDK using the [nodeModules](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.BundlingOptions.html#nodemodules) property, which builds everything inside a docker container.

So I'm left wondering: how do you bundle `sharp` with esbuild?

**Comment by lovell** [comment]
You question mentions CDK. Does this question relate specifically and exclusively to it? Did you see the `nodeModules` options of `NodeJsFunction`?

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.BundlingOptions.html

If you're still having problems, please share a minimal example of the code/configuration you're using, enough to allow someone else to reproduce.

**Comment by garysassano** [comment]
As I explained, the problem is that you are able to easily bundle sharp only through the CDK. In my case, I want to bundle sharp using the esbuild CLI, so I cannot take that shortcut.

**Comment by lovell** [comment]
When you say you're using only the esbuild CLI, is this also responsible for creating a zip file to be deployed?

If you're still having problems, please share a minimal example of the code/configuration you're using, enough to allow someone else to reproduce.

**Comment by garysassano** [comment]
#### index.js

```js
import sharp from "sharp";

<do something>
```

Create the esbuild bundle:

```sh
npx esbuild index.js --bundle --platform=node --target=node20 --outfile=dist/index.js
```

Create the zip-archive for Lambda function:

```sh
zip -r index.zip dist/*
```

Upload the Lambda function.

Test with with a random payload and get the following error: `Could not load the "sharp" module using the X runtime`

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/install#esbuild

> esbuild app.js --bundle --platform=node --external:sharp

You'll need to mark `sharp` as external.

```diff
- npx esbuild index.js --bundle --platform=node --target=node20 --outfile=dist/index.js
+ npx esbuild index.js --bundle --platform=node --target=node20 --external:sharp --outfile=dist/index.js
```

...then include the relevant packages in your zip file:

```diff
- zip -r index.zip dist/*
+ zip -r index.zip dist/* node_modules/sharp/* node_modules/@img/*
```

**Comment by garysassano** [comment]
Zipping just `sharp` and `@img` results in an error being thrown because of missing deps. You have to zip the entire `node_modules` folder in order to actually make it work.

The problem is that, this doesn't answer my original question: why cannot you bundle `sharp`? What you are doing here is installing the `sharp` node module, not bundling it inside the `index.js` output file. I don't understand what's the reason preventing you from bundling.

**Comment by lovell** [comment]
You added but then deleted a comment that said you are using the pnpm package manager.

https://sharp.pixelplumbing.com/install#aws-lambda says "Some package managers use symbolic links but AWS Lambda does not support these within deployment packages."

If you are using pnpm, how are you managing/converting its use of symlinks?

> I don't understand what's the reason preventing you from bundling.

Tools such as esbuild bundle JavaScript files, however you are attempting to bundle a mixture of JavaScript files and native shared libraries. This is not unique to sharp, for example esbuild is a native dependency and cannot bundle itself. (If you would like to learn more about shared library linking, [rpath](https://en.wikipedia.org/wiki/Rpath) might be a good place to start.)

Some higher-level tooling designed for building and publishing packages for serverless functions and apps (e.g. Electron) contains logic to detect and manage selective inclusion of `node_modules`-based dependencies marked as "external" from bundling.

**Comment by garysassano** [comment]
> If you are using pnpm, how are you managing/converting its use of symlinks?

There are two possible solutions to this problem:

- Use the `--symlinks` option of the `zip` command to include symlinks in the Lambda function package.
- Use the `--shamefully-hoist` option of the `pnpm install` command to avoid symlinks in `node_modules`.

> Tools such as esbuild bundle JavaScript files, however you are attempting to bundle a mixture of JavaScript files and native shared libraries. This is not unique to sharp, for example esbuild is a native dependency and cannot bundle itself. (If you would like to learn more about shared library linking, [rpath](https://en.wikipedia.org/wiki/Rpath) might be a good place to start.)

Ok, so I'm trying to bundle binaries compiled for a specific architecture, which is obviously impossible inside a JavaScript file.

> [sharp.pixelplumbing.com/install#aws-lambda](https://sharp.pixelplumbing.com/install#aws-lambda) says "Some package managers use symbolic links but AWS Lambda does not support these within deployment packages."

So, you made me realize that I could reduce the size of my Lambda function package by half simply using `npm install --cpu=arm64 --os=linux --libc=glibc sharp`, while previously I wasn't specifying the `libc` option so it was installing both `musl` and `glibc`.

In the end, I created a script that mimics what the `nodeModules` of CDK does, but without using a container:
1. Create a temp dir.
2. Bundle all deps from `package.json` (sharp isn't specified there) using esbuild.
3. Install sharp for Lambda `nodejs20.x` runtime: `cpu=arm64` (Graviton CPU) + `--os=linux --libc=glibc` (AL2023 OS)
4. Take the esbuild bundle and sharp's `node_modules` and create a zip-archive for Lambda function.
5. Delete the temp dir.

**Comment by garysassano** [comment]
> If you are using pnpm, how are you managing/converting its use of symlinks?

There are two possible solutions to this problem:

- Use the `--symlinks` option of the `zip` command to include symlinks in the Lambda function package.
- Use the `--shamefully-hoist` option of the `pnpm install` command to avoid symlinks in `node_modules`.

> Tools such as esbuild bundle JavaScript files, however you are attempting to bundle a mixture of JavaScript files and native shared libraries. This is not unique to sharp, for example esbuild is a native dependency and cannot bundle itself. (If you would like to learn more about shared library linking, [rpath](https://en.wikipedia.org/wiki/Rpath) might be a good place to start.)

Ok, so I'm trying to bundle binaries compiled for a specific architecture, which is obviously impossible inside a JavaScript file.

> [sharp.pixelplumbing.com/install#aws-lambda](https://sharp.pixelplumbing.com/install#aws-lambda) says "Some package managers use symbolic links but AWS Lambda does not support these within deployment packages."

You made me realize that I could reduce the size of my Lambda function package by half simply using `npm install --cpu=arm64 --os=linux --libc=glibc sharp`, while previously I wasn't specifying the `libc` option so it was installing both `musl` and `glibc`.

In the end, I created a script that mimics what the `nodeModules` of CDK does, but without using a container:
1. Create a temp dir.
2. Bundle all deps from `package.json` (sharp isn't specified there) using esbuild.
3. Install sharp for Lambda `nodejs20.x` runtime: `cpu=arm64` (Graviton CPU) + `--os=linux --libc=glibc` (AL2023 OS)
4. Take the esbuild bundle and sharp's `node_modules` and create a zip-archive for Lambda function.
5. Delete the temp dir.

**Comment by garysassano** [comment]
> If you are using pnpm, how are you managing/converting its use of symlinks?

There are two possible solutions to this problem:

- Use the `--symlinks` option of the `zip` command to include symlinks in the Lambda function package.
- Use the `--shamefully-hoist` option of the `pnpm install` command to avoid symlinks in `node_modules`.

> Tools such as esbuild bundle JavaScript files, however you are attempting to bundle a mixture of JavaScript files and native shared libraries. This is not unique to sharp, for example esbuild is a native dependency and cannot bundle itself. (If you would like to learn more about shared library linking, [rpath](https://en.wikipedia.org/wiki/Rpath) might be a good place to start.)

Ok, so I was trying to bundle binaries compiled for a specific architecture, which is obviously impossible inside a JavaScript file.

In the end, I created a script that mimics what the `nodeModules` of CDK does, but without using a container:
1. Create a temp dir.
2. Bundle all deps from `package.json` (sharp isn't specified there) using esbuild.
3. Install sharp for Lambda `nodejs20.x` runtime: `cpu=arm64` (Graviton CPU) + `--os=linux --libc=glibc` (AL2023 OS)
4. Take the esbuild bundle and sharp's `node_modules` and create a zip-archive for Lambda function.
5. Delete the temp dir.

**Comment by lovell** [comment]
Thanks for the update, glad you worked it out.
