### ISSUE TITLE
Support for streaming RAW images

### ISSUE THREAD

**Issue by peacechen** [lovell/sharp#4120]
## Question about an existing feature

RAW images take up a lot of memory. Is there a way to stream RAW to reduce memory requirements?

### What are you trying to achieve?

Stream RAW input to reduce memory requirements.

### When you searched for similar issues, what did you find that might be related?

#220

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

Example from https://sharp.pixelplumbing.com/api-constructor has the entire image in memory instead of streaming.
```
// Read a raw array of pixels and save it to a png
const input = Uint8Array.from([255, 255, 255, 0, 0, 0]); // or Uint8ClampedArray
const image = sharp(input, {
  // because the input does not contain its dimensions or how many channels it has
  // we need to specify it in the constructor options
  raw: {
    width: 2,
    height: 1,
    channels: 3
  }
});
await image.toFile('my-two-pixels.png');
```

### Please provide sample image(s) that help explain this question

N/A

**Comment by lovell** [comment]
No, sorry, this is something that would probably be part of the future possible enhancement detailed at https://github.com/lovell/sharp/issues/179

**Comment by lovell** [comment]
Let's continue to track this at #179
