### ISSUE TITLE
runtime error : TypeError: require(...).availableParallelism is not a function with node version < v19.4.0

### ISSUE THREAD

**Issue by midoelhawy** [lovell/sharp#4121]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [ ] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp? **_Yes_**

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Linux 6.8 Pop!_OS 22.04 LTS
    CPU: (4) x64 Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz
    Memory: 3.15 GB / 15.50 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.12.1 - ~/.nvm/versions/node/v18.18.2/bin/pnpm
  npmPackages:
    sharp: ^0.33.3 => 0.33.4 
```

### Does this problem relate to file caching?

The default behaviour of libvips is to cache input files, which can lead to `EBUSY` or `EPERM` errors on Windows.
Use [`sharp.cache(false)`](https://sharp.pixelplumbing.com/api-utility#cache) to switch this feature off.

- [x] Adding `sharp.cache(false)` does not fix this problem.

### What are the steps to reproduce?
you can reproduce it by launching any node app that import sharp with node < v19.4.0

### What is the expected behaviour?
The full application crash becose of  require(...).availableParallelism is not a function at /sharp/lib/utility.js:158

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem
```JS
import sharp from sharp
```

Possible fix: you can add this line by adding 
```JS
if(require('node:os').availableParallelism){
    sharp.concurrency(require('node:os').availableParallelism());
}

```
AT [this line](https://github.com/lovell/sharp/blob/56fae3eda1d165c338625244123a91de306abd8c/lib/utility.js#L158C1-L159C1) 
or by changing Minimal node version supported to `v19.4.0`

**Comment by lovell** [comment]
Node.js 19 reached end-of-life in June 2023.

The [availableParallelism](https://nodejs.org/docs/latest/api/os.html#osavailableparallelism) feature was added to Node.js in version 18.14.0.

The versions of Node.js currently supported by sharp are detailed at:

https://github.com/lovell/sharp/blob/56fae3eda1d165c338625244123a91de306abd8c/package.json#L189
