### ISSUE TITLE
Extend to a specified width and height in single operation without knowing the prior width or height

### ISSUE THREAD

**Issue by twilson90** [lovell/sharp#4127]
It appears extend() only allows inputs of left, right, top and bottom, but it would be really convenient if there was a way to extend an image to a specified width or height without having to calculate the images width or height and using the differences in extend(), or using toBuffer on the image and creating a new image using composite(), both of which require async operations.

Is this already a feature? If not it would be nice.

**Comment by lovell** [comment]
If you only want to extend along one axis ("letterbox") then `.resize({ width, height, fit: 'inside' })` kind of does this.

Otherwise, yes, you'll need to calculate this using the metadata. Although it is async, the `metadata()` call is usually very fast as it does not decode any pixel data.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
