### ISSUE TITLE
Sharp/Vips crashed in almost all latest Linux

### ISSUE THREAD

**Issue by forza91** [lovell/sharp#4129]
Hi, 
We have an linux app which is using Sharp@0.28.3 and there is no way to update due to some reason, but after upgrading system it crashed everytime with this error:

```
ERROR:/__w/sharp/sharp/vendor/8.10.6/include/vips/VImage8.h:125:vips::VObject& vips::VObject::operator=(const vips::VObject&): assertion failed: (!a.vobject || VIPS_IS_OBJECT( a.vobject ))
Bail out! ERROR:/__w/sharp/sharp/vendor/8.10.6/include/vips/VImage8.h:125:vips::VObject& vips::VObject::operator=(const vips::VObject&): assertion failed: (!a.vobject || VIPS_IS_OBJECT( a.vobject ))
```

We have this library in the sharp folder:  
`sharp/vendor/8.10.6/lib/libvips-cpp.so.42`

The sharp is installed by npm.

Working: Debian12, Ubuntu20.04 (With Gnome43/45)
Not Working: Latest Debian, Ubuntu and Arch Linux (With Gnome46)

Is seems like the whole linux distros are getting some libraries upgraded, but we dont know which it is.

[VIPS issue on build (gatsby) #2684](https://github.com/lovell/sharp/issues/2684)
This thread can't solve the problem because this app is not able to upgrade Sharp. But I've upgrade to Sharp@0.29/0.31 and get the same error.

Here is the ldd dependencies:

```
ldd sharp.node

        linux-vdso.so.1 (0x00007ffee43f6000)
	libvips-cpp.so.42 => /home/xxx/../../vendor/8.10.6/lib/libvips-cpp.so.42 (0x00007f7d6e000000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f7d6dc00000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7d6f721000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7d6facf000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7d6faca000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7d6de1f000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f7d6fab7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7d6fab2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7d6fb08000)


ldd libvips-cpp.so.42

        linux-vdso.so.1 (0x00007fff94725000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f11ec4f8000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f11ec4e7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f11ec4e2000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f11eaa00000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f11ead1e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f11ea81b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f11ec516000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f11ec4b3000)
```

System info:

OS: Debian GNU/Linux trixie/sid x86_64 
Kernel: 6.7.12-amd64 
Uptime: 44 mins 
Packages: 1918 (dpkg) 
Shell: bash 5.2.21 
Resolution: 3840x2160 
DE: GNOME 44.9 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: gnome-terminal 
	

So, could anyone help point out some possible libraries which causing this error so we can downgrade to fix it?

Thanks!

**Comment by lovell** [comment]
> there is no way to update due to some reason, but after upgrading system it crashed everytime

Please upgrade sharp; if you can upgrade Linux then you can upgrade sharp. You might be able to use `npm` [overrides](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#overrides) to achieve this. There have been many improvements to sharp during the last 3 years that will help avoid this entire class of error.

 I cannot provide any support for old versions.

**Comment by Obamium69** [comment]
@forza91 did you fix the issue? I'm also getting the error
```
ERROR:/__w/sharp/sharp/node_modules/@img/sharp-libvips-dev/include/vips/VImage8.h:134:vips::VObject& vips::VObject::operator=(const vips::VObject&): assertion failed: (!a.vobject || VIPS_IS_OBJECT(a.vobject))
Bail out! ERROR:/__w/sharp/sharp/node_modules/@img/sharp-libvips-dev/include/vips/VImage8.h:134:vips::VObject& vips::VObject::operator=(const vips::VObject&): assertion failed: (!a.vobject || VIPS_IS_OBJECT(a.vobject))
```
With the versions
`sharp@0.33.5`
`extra/libvips 8.16.0-3`
