### ISSUE TITLE
make rectangular area transparent

### ISSUE THREAD

**Issue by jardakotesovec** [lovell/sharp#413]
We are happily using sharp for extract and resize operations.  And one operation in the pipeline that we currently need is to make some particular rectangular area transparent in the image - completely transparent, so also other channels should be changed to zeros so final image is as small as possible.

I would like to try write PR for it, but I am afraid its pretty specific feature to get into sharp so want to get your opinion first.

**Comment by jardakotesovec** [comment]
Api could look something like this: `.fillRect({left: left, top: top, width: width, height: height, r: 0, g: 0, b: 0, a: 0})`

**Comment by lovell** [comment]
Hi Jarda, it might be possible for you to achieve this in your own code fairly quickly by returning raw pixel data as a Buffer then using its [fill](https://nodejs.org/api/buffer.html#buffer_buf_fill_value_offset_end_encoding) method to set per-row ranges to zero. You'd need to calculate the offset/end into the RGBA data for each row.

Does this make sense? I can probably write some sample code to help explain if not.

**Comment by jardakotesovec** [comment]
Thanks a lot for hint. 

Calling fills per row is very efficient (usually faster than 1ms for 885x619 image).

I hoped to avoid copying uncompressed raw data to js (since input and output is png), but I don't know internals enough how faster it would get when it would be implemented directly in c++ using libvips?

**Comment by lovell** [comment]
Memory references are passed when moving between JS and C++ (and back again) rather than copies being taken. The 10ms you mention doesn't sound right at all :( I'll profile your code sample to see what's taking up all that time - this could be related to https://github.com/jcupitt/libvips/pull/402 if you're using libvips < v8.3.0.

I'd expect the PNG decompression+recompression part of this task to be about an order of magnitude slower than all the other operations combined, regardless of where they are carried out.

Using `embed()` onto a transparent `background()` will add an alpha channel. I've not tested this without a resize operation but it "should just work" (TM).

**Comment by jardakotesovec** [comment]
Thanks for these details - I tried to update to v8.3.0 and reinstall node_modules and I am still on 10ms with the snippet above. But comparing to other times its not big deal.. (doing extract and resize)  but if you find out whats happening during these 10ms.. I am curious :-).

I use operations chain -  extract().resize().background().embed().toBuffer(), and it works as you said 👍 

Feel free to close this issue, thanks a lot for help.

**Comment by lovell** [comment]
Glad to hear you got this working, thanks for the update. Let's leave this open whilst we investigate the unexpectedly long processing time you encountered.

**Comment by jardakotesovec** [comment]
Using more that embed feature I noticed that it works only if image has different ratio than resize. If ratio is same it make sense that it does not do embedding to background since no background would be visible.

As example:
```
// 2048x1536
sharp('./IMG_2896.JPG')
    .extract({
        left: 0,
        top: 0,
        width: 500,
        height:1000
    })
    .resize(250,500)
    .background({r: 0, g: 0, b: 0, a:0}).embed()
    .raw().toBuffer().then(buffer => {
        console.log(buffer.length);
    })
```
Produces buffer only with 3 channels, but if I change to `.resize(251,500)` or `.resize(249,500)` it does the embedding and returns buffer with 4 channels.

I tried to implement adding channel in JS:
```
function addChannel(buffer, width, height) {

    var bufSize = width * height * 4;
    var buf = Buffer.alloc(bufSize, 255);

    for (var i = 0, il = width * height; i < il; ++i) {

        buf[4 * i] = buffer[3 * i];
        buf[4 * i + 1] = buffer[3 * i + 1];
        buf[4 * i + 2] = buffer[3 * i + 2];
    }
    return buf;
}
```

And it works pretty fast: 8ms for 800x1600 image.  In case you have some idea how to make it faster using sharp or better js implementation I'm all ears :-)

**Comment by lovell** [comment]
It looks like sharp is making an unnecessary pair of premultiply+unpremultiply operations when processing an image with an alpha channel but not resizing or compositing. I'll fix this - thanks for the tip-off!

**Comment by lovell** [comment]
Commit c920180 reduces the processing time of a 1000x1000px RGBA image by ~8ms when no resize or overlay is required. Thanks again for reporting this Jarda!

**Comment by jardakotesovec** [comment]
Thank you :-).
