### ISSUE TITLE
how could I package sharp dependencies into electron app for mac

### ISSUE THREAD

**Issue by nouh** [lovell/sharp#414]
when use sharp on electron project, I use electron-packager on Mac  to package app for mac platform. but the packaged app still depend on libvips installed by homebrew

**Comment by lovell** [comment]
See also #312

**Comment by topmat** [comment]
follow the #312 instruction. 

Does the sharp.node require update the path of .dylib dep?

**Comment by lovell** [comment]
My comment about #312 was that when it is done, this becomes a lot easier for OS X.

**Comment by topmat** [comment]
Hi lovell, 

   I tried #312 in electron, I got coredump. 
I posted this issue in the electron github, they said this is not electron issue. 
Cloud you help me to check this?
https://github.com/electron/electron/issues/5641

If you need more information, I can provide you more.

**Comment by lovell** [comment]
@topmat Are you able to generate a backtrace of the crash by running your app via `lldb`?

**Comment by lovell** [comment]
Experimental support for pre-compiled libvips OS X binaries is now available for testing - please see https://github.com/lovell/sharp/issues/312#issuecomment-226841804

This should make cross-platform use with Electron significantly easier.

**Comment by lovell** [comment]
Looks like people are happy with progress on #312 so I'm going to close this as #312 should provide everything needed for this.
