### ISSUE TITLE
Video filter option to skip frames or set maximum time to read from input  

### ISSUE THREAD

**Issue by Jeanno** [lovell/sharp#4141]
### What are you trying to achieve?

Trying to process user uploaded animated images. Sometimes user uploads unreasonably long animation, but instead of bumping the `limitInputPixels` or throwing an exception, I would love to have an option to cut off after certain time (say 10 seconds).

### When you searched for similar feature requests, what did you find that might be related?

Many fellow devs mentioned the `limitInputPixels` error they've encountered but didn't really suggest a solution.

### What would you expect the API to look like?

I would expect it is an option in the constructor.
https://sharp.pixelplumbing.com/api-constructor

Probably sometime like `options.animationFilter` or `options.videoFilter`.

### What alternatives have you considered?

You mean workaround? Using another library to preprocess could be an option but performance wise it's really bad.

### Please provide sample image(s) that help explain this feature

Any super long animated WebP or GIF would do.

**Comment by lovell** [comment]
> I would love to have an option to cut off after certain time

Did you see the `pages` parameter of the constructor?

https://sharp.pixelplumbing.com/api-constructor

> `pages` Number of pages to extract for multi-page input

```js
sharp("super-long-animated.gif", { pages: 10 })...
```
The `delay` information provided by `metadata()` allows you to calculate the number of pages/frames of the input to use to reach a maximum time.

https://sharp.pixelplumbing.com/api-input#metadata

```js
const { delay } = await sharp("super-long-animated.gif", { animated: true }).metadata();
```

**Comment by Jeanno** [comment]
I must have missed it. I will close this for now. Thank you for your
detailed response.

Jeanno
