### ISSUE TITLE
Error: Could not load the "sharp" module using the linuxmusl-x64 runtime

### ISSUE THREAD

**Issue by Miri121** [lovell/sharp#4146]
i use node ts in "sharp": "^0.33.4", "@types/sharp": "^0.32.0",
I develop in window it worked well but in docker it doesn't run I get that Could not load the "sharp" module using the linuxmusl-x64 runtime

**Comment by lovell** [comment]
As I said in https://github.com/lovell/sharp/issues/4142, if you're still having problems, please open an installation issue and provide answers to all of the questions.

https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md

The questions in the issue template allow you to help yourself and the answers you provide allow me to help you.

This is the second time that the issue template has been ignored/deleted. If you open a third issue about this please prove that you've read the documentation to avoid wasting both my time and your own. Pay particular attention to https://sharp.pixelplumbing.com/install#cross-platform
