### ISSUE TITLE
Trim cuts off top of my image

### ISSUE THREAD

**Issue by aleclloyd-jumbo** [lovell/sharp#4148]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [X] Running `npm install sharp` completes without error.
- [X] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [X ] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Does this problem relate to file caching?

The default behaviour of libvips is to cache input files, which can lead to `EBUSY` or `EPERM` errors on Windows.
Use [`sharp.cache(false)`](https://sharp.pixelplumbing.com/api-utility#cache) to switch this feature off.

- [ ] Adding `sharp.cache(false)` does not fix this problem.

### Does this problem relate to images appearing to have been rotated by 90 degrees?

Images that contain EXIF Orientation metadata are not auto-oriented. By default, EXIF metadata is removed.

- To auto-orient pixel values use the parameter-less [`rotate()`](https://sharp.pixelplumbing.com/api-operation#rotate) operation.
- To retain EXIF Orientation use [`keepExif()`](https://sharp.pixelplumbing.com/api-output#keepexif).

- [ ] Using `rotate()` or `keepExif()` does not fix this problem.

**Comment by lovell** [comment]
Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem.

Please provide sample image(s) that help explain this problem.

**Comment by aleclloyd-jumbo** [comment]
async function save(fileName) {
    sharp(fileName)
        .trim()
        .toFile("/output/" + fileName);
}

**Comment by aleclloyd-jumbo** [comment]
Im trying to add the image, but it says tiff is an unsupported file type

**Comment by aleclloyd-jumbo** [comment]
[Original and trimmed image.zip](https://github.com/user-attachments/files/16074718/Original.and.trimmed.image.zip)

**Comment by lovell** [comment]
I hope this information helped. Let's continue to track this at https://github.com/lovell/sharp/issues/2266
