### ISSUE TITLE
Error VipsJpeg Corrupt JPEG data from CCTV Image Snapshot

### ISSUE THREAD

**Issue by mu-hasan** [lovell/sharp#4149]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `yarn add sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Does this problem relate to file caching?

The default behaviour of libvips is to cache input files, which can lead to `EBUSY` or `EPERM` errors on Windows.
Use [`sharp.cache(false)`](https://sharp.pixelplumbing.com/api-utility#cache) to switch this feature off.

- [x] Adding `sharp.cache(false)` does not fix this problem.

### Does this problem relate to images appearing to have been rotated by 90 degrees?

Images that contain EXIF Orientation metadata are not auto-oriented. By default, EXIF metadata is removed.

- To auto-orient pixel values use the parameter-less [`rotate()`](https://sharp.pixelplumbing.com/api-operation#rotate) operation.
- To retain EXIF Orientation use [`keepExif()`](https://sharp.pixelplumbing.com/api-output#keepexif).

- [x] Using `rotate()` or `keepExif()` does not fix this problem.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```js
    try {
        const image = sharp('filesample.jpg');
        image.jpeg({ mozjpeg: true, chromaSubsampling: '4:4:4' });
        const buff = await image.toBuffer();
        console.log(buff);
    } catch (err) {
        console.error(err);
    }
```

Then the error is
```
Error: VipsJpeg: Corrupt JPEG data: 608 extraneous bytes before marker 0xfe
VipsJpeg: Corrupt JPEG data: 608 extraneous bytes before marker 0xfe
    at Sharp.toBuffer (/path-to-project/node_modules/sharp/lib/output.js:161:17)
```

### Please provide sample image(s) that help explain this problem
![filesample](https://github.com/lovell/sharp/assets/8762248/de3b1404-35cb-414b-bd34-a834c65982de)

**Comment by lovell** [comment]
This JPEG is invalid, please use the `failOn` property if you trust the source of your input images.

https://sharp.pixelplumbing.com/api-constructor

```diff
- const image = sharp('filesample.jpg');
+ const image = sharp('filesample.jpg', { failOn: 'truncated' });
```

**Comment by mu-hasan** [comment]
cool. thanks for the information 🙌

**Comment by justyouhappy** [comment]
> This JPEG is invalid, please use the `failOn` property if you trust the source of your input images.
> 
> https://sharp.pixelplumbing.com/api-constructor
> 
> ```diff
> - const image = sharp('filesample.jpg');
> + const image = sharp('filesample.jpg', { failOn: 'truncated' });
> ```

Why is the picture invalid and what are the criteria for judging it?

**Comment by lovell** [comment]
@justyouhappy Attempting to process the sample image with Imagemagick generates the following error:

> Corrupt JPEG data: 608 extraneous bytes before marker 0xfe
