### ISSUE TITLE
How to generate animation picture from an  image sequence?

### ISSUE THREAD

**Issue by Zxilly** [lovell/sharp#4154]
## Question about an existing feature

Follow `https://sharp.pixelplumbing.com/api-constructor#sharp`, I didn't find a way to init a Sharp instance with `static image sequence` to multi pages. It this possible right now?

### What are you trying to achieve?

Read many pictures, assemble them to an animation gif/webp

### When you searched for similar issues, what did you find that might be related?

I didn't find any. I remember seeing some discussion about this in the past, but I can't find it now.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```javascript

sharp(inputPNGBufferArray)
  .gif()
  .toFile('output.gif', (err, info) => { ... });

```

**Comment by lovell** [comment]
There's an existing issue tracking this at https://github.com/lovell/sharp/issues/1580
