### ISSUE TITLE
Error: heifsave: Unsupported compression when using libvips with support of libheif

### ISSUE THREAD

**Issue by faradaytrs** [lovell/sharp#4155]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [X] Running `npm install sharp` completes without error.
- [X] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [X] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Does this problem relate to file caching?

The default behaviour of libvips is to cache input files, which can lead to `EBUSY` or `EPERM` errors on Windows.
Use [`sharp.cache(false)`](https://sharp.pixelplumbing.com/api-utility#cache) to switch this feature off.

- [X] Adding `sharp.cache(false)` does not fix this problem.

### Does this problem relate to images appearing to have been rotated by 90 degrees?

Images that contain EXIF Orientation metadata are not auto-oriented. By default, EXIF metadata is removed.

- To auto-orient pixel values use the parameter-less [`rotate()`](https://sharp.pixelplumbing.com/api-operation#rotate) operation.
- To retain EXIF Orientation use [`keepExif()`](https://sharp.pixelplumbing.com/api-output#keepexif).

- [X] Using `rotate()` or `keepExif()` does not fix this problem.

### What are the steps to reproduce?

We use self compilled libvips to support of libheif, with hevc compression (which works fine)
But when i try to generate avif or heif with av1 compression i get error:
Error: heifsave: Unsupported compression 

### What is the expected behaviour?

Generate image normally

### Please provide sample image(s) that help explain this problem

I attached libvips and sharp compile log

[libvips.txt](https://github.com/user-attachments/files/16140478/libvips.txt)

**Comment by lovell** [comment]
> But when i try to generate avif or heif with av1 compression i get error:
> Error: heifsave: Unsupported compression

I don't see any AV1 encoder/decoder mentioned in the installation log. The following entry suggests libheif can't it one either.

> -- Could NOT find AOM (missing: AOM_INCLUDE_DIR AOM_LIBRARIES)

**Comment by faradaytrs** [comment]
> > But when i try to generate avif or heif with av1 compression i get error:
> > Error: heifsave: Unsupported compression
> 
> I don't see any AV1 encoder/decoder mentioned in the installation log. The following entry suggests libheif can't find one either.
> 
> > -- Could NOT find AOM (missing: AOM_INCLUDE_DIR AOM_LIBRARIES)

I think it was compiled without libaom.. so it's not a sharp problem

**Comment by kleisauke** [comment]
Cross-posted at https://github.com/zoellner/sharp-heic-lambda-layer/issues/32, which is probably the right place for this.
