### ISSUE TITLE
Documentation should mention "pnpm >= 7.1.0 with `--no-optional=false`"

### ISSUE THREAD

**Issue by oscarhermoso** [lovell/sharp#4159]
### Documentation should mention "pnpm >= 7.1.0 with `--no-optional=false`"

Spent last 24 hrs trying to get `sharp` running in a Docker container, for a SvelteKit app deployed with pnpm. Ran through all of the [installation documentation](https://sharp.pixelplumbing.com/install#prerequisites), searched for other working examples on GitHub, StackOverflow etc.

Finally reached the point of raising an issue, only to discover the solution was in the issue template.

Would be great if this highlighted sentence could also be added to the Installation documentation.

![Screenshot from 2024-07-14 11-25-51](https://github.com/user-attachments/assets/eadd74d8-7c3c-44c7-8f02-5e79e01692ab)

### What alternatives have you considered?

Is it somehow possible to install sharp with `--no-optional=true` (instead of the recommended `--no-optional=false`) when using pnpm as a package manager?

### Please provide sample that help explain this feature

See below the working `Dockerfile`, `vite.config.ts`, and relevant parts of the `package.json` if anyone needs it:

<details><summary>Working configuration</summary>
<p>

#### Dockerfile

```Dockerfile
FROM node:20.14.0-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

ARG SHARP_FORCE_GLOBAL_LIBVIPS=1
ENV SHARP_FORCE_GLOBAL_LIBVIPS=1

RUN apt-get update && apt-get install -y --no-install-recommends \
  # Used to generate sitemap
  git \
  # Sharp image library
  libvips42 \
  # latest certs because of uWebSockets
  ca-certificates \
  && rm -rf /var/lib/apt/lists/*

FROM base AS build
ARG DOCKER_TAG
ENV DOCKER_TAG=${DOCKER_TAG}
ARG NPM_TOKEN

WORKDIR /usr/src/app
COPY . .
RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
  pnpm install --filter=@sites/frontend --frozen-lockfile
RUN pnpm run build --filter=@sites/frontend
RUN pnpm deploy --filter=@sites/frontend --prod --no-optional=false /pruned/sites/frontend

FROM base AS runtime
WORKDIR /app
COPY --from=build /pruned/sites/frontend ./
COPY ./sites/frontend/entrypoint.sh ./

# Max body size already guarded by NGINX
ENV BODY_SIZE_LIMIT=Infinity
ENV PORT=3000
EXPOSE ${PORT} 2222

ENTRYPOINT ["./entrypoint.sh"]
```

#### vite.config.ts

```ts
import { defineConfig } from 'vite';
import { sveltekit } from '@sveltejs/kit/vite';
import path from 'node:path';

const viteConfig = defineConfig({
	build: {
		rollupOptions: {
			external: ['sharp'],
		},
	},
	optimizeDeps: {
		exclude: ['sharp'],
	},
	resolve: {
		alias: {
			$lib: path.resolve(__dirname, './src/lib'),
			'$lib/*': path.resolve(__dirname, './src/lib/*'),
			$routes: path.resolve(__dirname, './src/routes'),
			'$routes/*': path.resolve(__dirname, './src/routes/*'),
		},
	},
	plugins: [
		sveltekit()
	],
});

export default viteConfig;
```

#### package.json

```json
{
	"name": "@sites/frontend",
	"version": "0.0.1",
	"private": true,
	"type": "module",
	"scripts": {
		"dev": "npm run dev:svelte",
		"dev:svelte": "vite dev --host",
		"build": "cross-env NODE_ENV=production npm run build:svelte",
		"build:svelte": "vite build",
		"check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
		"check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
		"preview": "vite preview",
		"prepare": "svelte-kit sync"
	},
	"dependencies": {
		"sharp": "^0.33.4"
	},
	"devDependencies": {
		"@sveltejs/adapter-node": "^4.0.1",
		"@sveltejs/kit": "^2.5.1",
		"@sveltejs/vite-plugin-svelte": "^3.0.1",
		"svelte": "^4.2.15",
		"vite": "^5.2.11"
	},
	"engines": {
		"pnpm": "^8.0.0"
	},
	"packageManager": "pnpm@8.15.7+sha256.50783dd0fa303852de2dd1557cd4b9f07cb5b018154a6e76d0f40635d6cee019",
	"supportedArchitectures": {
		"os": [
			"current",
			"linux"
		],
		"cpu": [
			"x64"
		]
	}
}
```

</p>
</details>

**Comment by lovell** [comment]
Did you see https://sharp.pixelplumbing.com/install ?

    ⚠️ Please ensure your package manager is configured to install optional dependencies

**Comment by oscarhermoso** [comment]
Thanks @lovell.

Honestly no, I did not see that banner when I was reading the docs. Scrolled right past it - not sure if that is a common problem because it's right at the top of the page, or just me missing it.
