### ISSUE TITLE
Errors processing heif files

### ISSUE THREAD

**Issue by mrbrahman** [lovell/sharp#4164]
### What are you trying to achieve?

Read a HEIC image and generate jpg thumbnails. Sharp throws the below error:

~~~
source: bad seek to 852104
heif: Unsupported feature: Unsupported codec (4.3000)
~~~

### When you searched for similar issues, what did you find that might be related?

https://github.com/lovell/sharp/issues/2713 comes up.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

Here's my system info from one of the commands in that issue.
~~~
$ npx envinfo --binaries --system

  System:
    OS: macOS 14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 296.80 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.20.4 - /usr/local/opt/node@18/bin/node
    npm: 10.7.0 - /usr/local/opt/node@18/bin/npm
~~~
(libvips does not come up in that list)

However, based on that issue, I updated libvps on my mac (by running `brew install vips`).

~~~
$ vips --version
vips-8.15.2
~~~

Also, 

~~~
$ npm view sharp dist-tags.latest
0.33.4
~~~

### Please provide sample image(s) that help explain this question

Don't think that's relevant here. But if needed, I can try to search some images that I can share.

**Comment by mrbrahman** [comment]
Thanks for your reply.

I didn't install libvips globally intentionally. I think I did a `brew install vips` by looking at the link https://www.libvips.org/install.html in order to get the latest version, based on the earlier issue #2713.

I have now uninstalled libvips globally (`brew uninstall vips`), removed sharp from my project, and did a `npm install sharp@latest`. However, I still see the same issue.

Any ideas? Is there any other debug info I can provide?

Thanks!

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/api-output#heif

> Support for patent-encumbered HEIC images using `hevc` compression requires the use of a globally-installed libvips compiled with support for libheif, libde265 and x265.

**Comment by mrbrahman** [comment]
Thanks, okay. So I have to install vips globally.

In the meantime I upgraded to node v22 (been a while now), and install of libvps is now failing. Let me try to debug more.

Thanks for looking into this.

**Comment by mrbrahman** [comment]
I managed to resolve the libvps installation issue. I also followed all instructions in the links you provided.

~~~
$ vips --version
vips-8.15.2

$ brew install libheif libde265 x265
Warning: libheif 1.17.6_1 is already installed and up-to-date.
To reinstall 1.17.6_1, run:
  brew reinstall libheif
Warning: libde265 1.0.15 is already installed and up-to-date.
To reinstall 1.0.15, run:
  brew reinstall libde265
Warning: x265 3.6 is already installed and up-to-date.
To reinstall 3.6, run:
  brew reinstall x265
~~~

I then removed sharp and re-installed with build-from-source

~~~
$ npm uninstall sharp

$ npm install --build-from-source --platform mac sharp
~~~

However, the npx command still does not show libvps (unlike #2713)

~~~
$ npx envinfo --binaries --system

  System:
    OS: macOS 14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 137.36 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 22.4.1 - /usr/local/bin/node
    npm: 10.8.1 - /usr/local/bin/npm
~~~

And also still getting the same error with sharp.

~~~
source: bad seek to 1065600
heif: Unsupported feature: Unsupported codec (4.3000)
~~~

Any other suggestions?

Thank you very much!

**Comment by lovell** [comment]
> $ npm install --build-from-source --platform mac sharp
Have you ensured everything mentioned in https://sharp.pixelplumbing.com/install#building-from-source has been installed?

**Comment by mrbrahman** [comment]
Yes, I did install those as well. Here's a snippet from my package.json

~~~json
  "dependencies": {
    "better-sqlite3": "^11.1.2",
    "chokidar": "^3.5.2",
    "compression": "^1.7.4",
    "configstore": "^6.0.0",
    "dateformat": "^5.0.2",
    "exiftool-vendored": "^27.0.0",
    "express": "^4.17.1",
    "fluent-ffmpeg": "^2.1.2",
    "mac": "^0.4.0",
    "minimist": "^1.2.5",
    "morgan": "^1.10.0",
    "node-addon-api": "^8.1.0",
    "node-gyp": "^10.2.0",
    "sharp": "^0.33.4",
    "uuid": "^10.0.0",
    "winston": "^3.8.2"
  },

~~~

Did I need to build them from source as well?

**Comment by mrbrahman** [comment]
Looks like I needed to build them from source as well. Finally it worked(!) after I did this:

~~~
$ npm install --build-from-source node-addon-api node-gyp sharp
~~~

Thanks for your help @lovell!

**Comment by mrbrahman** [comment]
A summary of what I had to do to get heif files to work:

~~~bash
# https://sharp.pixelplumbing.com/api-output#heif
brew install vips libheif libde265 x265

# https://sharp.pixelplumbing.com/install#building-from-source
npm install --build-from-source node-addon-api node-gyp sharp
~~~
