### ISSUE TITLE
Enhancement: add support for output format of SVG

### ISSUE THREAD

**Issue by RainmanVi** [lovell/sharp#4165]
### What are you trying to achieve?

Could you please consider adding support for the output format of SVG, so that we can use `.toFormat('svg')` or the corresponding `.svg()` to save the transformed images as SVG?

### When you searched for similar feature requests, what did you find that might be related?

I noticed a related question in [#3415](https://github.com/lovell/sharp/issues/3415). There is a need for the support of the output format of SVG.

Currently, we can achieve the purpose of converting any images to SVG using a combination of `sharp` and [`potrace`](https://github.com/tooolbox/node-potrace), with the latter being a node port of [Potrace](https://potrace.sourceforge.net/), which is a CLI tool that transforms bitmaps into vector graphics. But doing so requires an additional package that seems to lack maintenance. Considering the growing demand for SVG conversions, I would like to propose integrating native SVG support directly into `sharp`. This enhancement would streamline the usage and ensure a more robust and sustainable solution for all users of `sharp`.

### What would you expect the API to look like?

Now:

```JS
import { promisify } from 'node:util';
import sharp from 'sharp';
import { trace as _t } from 'potrace';

// Yes, it doesn't even support promises, so we have to wrap it first.
const trace = promisify(_t);

// Load and resize the image, then convert it to a binary format
const buffer = await sharp(inputImage)
  .resize(512, 512)
  .toFormat('png')
  .toBuffer();

// Trace the bitmap to get an SVG
const outputImage = await trace(buffer, { color: 'black', optTolerance: 0.2 });

// Write the SVG file
await writeFile('output.svg', outputImage);
```

After supported:

```JS
await sharp(inputImage)
  .resize(512, 512)
  // or .toFormat('svg', { color: 'black', optTolerance: 0.2 })
  .svg({ color: 'black', optTolerance: 0.2 })
  .toFile('output.svg'); // just fantastic like Sharp always is!
```

**Comment by lovell** [comment]
Hi, sharp is primarily for processing bitmap images, with vector input such as SVG rasterised on load.

If you need to convert from a bitmap to a vector format then you're correct to consider using an alternative tool such as potrace. Please be aware it is GPLv2, so watch out for possible conflicts with other licences, and that alone would be enough to prevent its inclusion in sharp as it is incompatible with Apache 2.0.

If you are concerned about lack of support around an existing Node.js package upon which you depend, perhaps you might consider offering to help maintain it.
