### ISSUE TITLE
sharp cannot render png in svg exported by PhotoShop

### ISSUE THREAD

**Issue by clshortfuse** [lovell/sharp#4166]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12600K
    Memory: 26.84 GB / 31.24 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
  npmPackages:
    sharp: ^0.33.4 => 0.33.4 
```

### What are the steps to reproduce?

Export SVG from Photoshop. Try to render SVG with sharp.

### What is the expected behaviour?

PNG should render. 

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```js
return await sharp(Buffer.from(svg)).
  .raw()
  .toFormat('png')
  .toBuffer();
```

### Please provide sample image(s) that help explain this problem

```svg
<svg 
 xmlns="http://www.w3.org/2000/svg"
 xmlns:xlink="http://www.w3.org/1999/xlink"
 width="400px" height="561px">
<image  x="0px" y="0px" width="400px" height="561px"  xlink:href="data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAIxBAMAAACROfMpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAElBMVEUA4f8A4f8A4f8A4f8A4f////8dZXD7AAAABHRSTlPe7vL2pDCBjAAAAAFiS0dEBfhv6ccAAAAHdElNRQfoBxAWOxt6hkHWAAACl0lEQVR42u3PAQ0EIRDAwLWAhbOAhfev6U2QMCEdBe3MesLMMyPf7wnf3C445Z2RfbvgjD3rdsIZqxFMI5pGNI1oGtE0omlE04imEU0jmkY0jWga0TSiaUTTiKYRTSOaRjSNaBrRNKJpRNOIphFNI5pGNI1oGtE0omlE04imEU0jmkY0jWga0TSiaUTTiKYRTSOaRjSNaBrRNKJpRNOIphFNI5pGNI1oGtE0omlE04imEU0jmkY0jWga0TSiaUTTiKYRTSOaRjSNaBrRNKJpRNOIphFNI5pGNI1oGtE0omlE04imEU0jmkY0jWga0TSiaUTTiKYRTSOaRjSNaBrRNKJpRNOIphFNI5pGNI1oGtE0omlE04imEU0jmkY0jWga0TSiaUTTiKYRTSOaRjSNaBrRNKJpRNOIphFNI5pGNI1oGtE0omlE04imEU0jmkY0jWga0TSiaUTTiKYRTSOaRjSNaBrRNKJpRNOIphFNI5pGNI1oGtE0omlE04imEU0jmkY0jWga0TSiaUTTiKYRTSOaRjSNaBrRNKJpRNOIphFNI5pGNI1oGtE0omlE04imEU0jmkY0jWga0TSiaUTTiKYRTSOaRjSNaBrRNKJpRNOIphFNI5pGNI1oGtE0omlE04imEU0jmkY0jWga0TSiaUTTiKYRTSOaRjSNaBrRNKJpRNOIphFNI5pGNI1oGtE0omlE04imEU0jmkY0jWga0TSiaUTTiKYRTSOaRjSNaBrRNKJpRNOIphFNI5pGNI1oGtE0omlE04imEU0jmkY0jWga0TSiaUTTiKYRTSOaRjSNaBrRNKJpRNOIphFNI5pGNI1oGtE0omlE04imEU0jmjX7dsIZe24XnPLOyHe74IxvZj1hnhn5A20o9l2gncMtAAAAAElFTkSuQmCC" />
</svg>
```

![test](https://github.com/user-attachments/assets/fd9a1058-7d46-4e6f-b786-635c2f129e7a)

<hr>

It's worth noting that svg seems to be read just fine. If it has text elements they all work. Compositing also works. It's just something about the PNG format, but other applications (Edge, Chrome, Firefox) handle it fine.

**Comment by lovell** [comment]
The `xlink:href` attribute contains an invalid mime type.

```diff
- ... xlink:href="data:img/png;base64 ...
+ ... xlink:href="data:image/png;base64 ...
```

**Comment by clshortfuse** [comment]
Thanks. I'm not sure how I missed that. It seems most (if not all) browsers use MIME sniffing to deal with unknown or invalid mime types within the image context:

* https://mimesniff.spec.whatwg.org/#sniffing-in-an-image-context

That would cover this instance.

Though this seems more an issue for the parser, not `sharp` directly.

**Comment by lovell** [comment]
The image loading logic for PNG-in-SVG is part of [librsvg](https://gitlab.gnome.org/GNOME/librsvg/-/blob/main/rsvg/src/document.rs#L632).

Given this appears to be due to a bug in Photoshop, perhaps you could report this to Adobe (annual revenue $19 billion), although good luck getting them to fix it :smile: .

**Comment by clshortfuse** [comment]
Thanks. I reached the same conclusion with `librsvg`. It seems it has code to sniff is there's no mime type. They added that because of another Adobe application: Illustrator, but I'm guessing there's no code if it's invalid (Photoshop). Adobe strikes again.

**Comment by federicomenaquintero** [comment]
Paging @dirkschulze - is this Photoshop bug something you could help us get fixed at Adobe? :smiley:
