### ISSUE TITLE
`Could not load the "sharp" module using the linux-x64 runtime` in Amplify environment

### ISSUE THREAD

**Issue by OussamaFadlaoui** [lovell/sharp#4167]
## Possible install-time or require-time problem

- [x] I have read and understood all of the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have searched for known bugs relating to this problem in my choice of package manager.

You must confirm both of these before continuing.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest,
please open an issue against that package instead.

### Are you using a supported runtime?

- [x] I am using Node.js with a version that satisfies `^18.17.0 || ^20.3.0 || >=21.0.0`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these,
please upgrade to the latest version
and try again before opening an issue.

### Are you using a supported package manager and installing optional dependencies?

- [ ] I am using npm >= 10.1.0 with `--include=optional`
- [ ] I am using yarn >= 3.2.0
- [x] I am using pnpm >= 7.1.0 with `--no-optional=false`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these, please upgrade to the latest version of your chosen package manager
and ensure you are allowing the installation of optional or multi-platform dependencies before opening an issue.

### What is the complete error message, including the full stack trace?

```
Error: Could not load the "sharp" module using the linux-x64 runtime
--
Possible solutions:
- Ensure optional dependencies can be installed:
npm install --include=optional sharp
yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
npm install --os=linux --cpu=x64 sharp
- Consult the installation documentation:
See https://sharp.pixelplumbing.com/install
```

Additional details:
 * AWS Amplify used as deployment environment;
 * Further inspection upon downloading the build artefacts reveals the platform and cpu-specific deps are not installed;
 * Tried explicitly adding above mentioned deps to package.json as suggested in https://github.com/lovell/sharp/issues/4106#issuecomment-2114981023 ;
 * Tried passing `--no-optional=false` flag;
 * Works fine locally.

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

[ serverless environment, cannot provide outputs for this ]

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
2024-07-18T07:46:34.288Z [INFO]: System:
OS: Linux 4.14 Amazon Linux 2023
CPU: (4) x64 Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
Memory: 6.33 GB / 7.50 GB
Container: Yes
Shell: 5.2.15 - /bin/bash
Binaries:
Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
Yarn: 1.22.19 - ~/.nvm/versions/node/v20.9.0/bin/yarn
npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
pnpm: 9.5.0 - ~/.nvm/versions/node/v20.9.0/bin/pnpm
npmPackages:
sharp: 0.33.4 => 0.33.4
```

**Comment by OussamaFadlaoui** [comment]
> `--binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

I managed to slip this into the `preBuild` commands. Updating the issue with this info.

**Comment by lovell** [comment]
Please can you provide the complete build log and make it as verbose as possible, perhaps via the `--reporter=ndjson` flag.

**Comment by OussamaFadlaoui** [comment]
> Please can you provide the complete build log and make it as verbose as possible, perhaps via the `--reporter=ndjson` flag if you're using pnpm.

Of course! Here it is: https://gist.github.com/OussamaFadlaoui/40916059651104687f50b21a4a52b5ff

GitHub didn't allow comments of this length, so I put it into a Gist

**Comment by OussamaFadlaoui** [comment]
> > Please can you provide the complete build log and make it as verbose as possible, perhaps via the `--reporter=ndjson` flag if you're using pnpm.
> 
> Of course! Here it is: [gist.github.com/OussamaFadlaoui/40916059651104687f50b21a4a52b5ff](https://gist.github.com/OussamaFadlaoui/40916059651104687f50b21a4a52b5ff)
> 
> GitHub didn't allow comments of this length, so I put it into a Gist

The verbosity reveals the optional deps for sharp are skipped:
```json
{
    "time": 1721297983914,
    "hostname": "247e3735f76c",
    "pid": 2900,
    "level": "debug",
    "name": "pnpm:skipped-optional-dependency",
    "details": "Error: Unsupported platform for @img/sharp-libvips-linux-arm@1.0.2: wanted {\"cpu\":[\"arm\"],\"os\":[\"linux\"],\"libc\":[\"any\"]} (current: {\"os\":\"linux\",\"cpu\":\"x64\",\"libc\":\"glibc\"})",
    "package": {
        "id": "@img/sharp-libvips-linux-arm@1.0.2",
        "name": "@img/sharp-libvips-linux-arm",
        "version": "1.0.2"
    },
    "prefix": "/codebuild/output/src1151117912/src/[repo hidden for privacy reasons]",
    "reason": "unsupported_platform"
}
```

Should i install the glibc versions?

**Comment by lovell** [comment]
Thanks, that all looks OK. Are you using any post-install bundling (I spy `esbuild` and `@next/swc` in there)? If so, please ensure you've read https://sharp.pixelplumbing.com/install#bundlers

**Comment by OussamaFadlaoui** [comment]
> Thanks, that all looks OK. Are you using any post-install bundling (I spy `esbuild` and `@next/swc` in there)? If so, please ensure you've read [sharp.pixelplumbing.com/install](https://sharp.pixelplumbing.com/install#bundlers)

It's a Next.js application, yes. `@next/swc` is used. But I don't see any instructions on the page you referenced to regarding that. As for `esbuild`, it might be used by Next.js, but I don't believe there's any way to control the options of that.

**Comment by lovell** [comment]
If you're using Next.js standalone, please ensure you're using the latest version of Next.js and in particular the latest version of its `@vercel/nft` dependency, as this performs bundling and older versions contained bugs relating to optional dependencies.

**Comment by OussamaFadlaoui** [comment]
> If you're using Next.js standalone, please ensure you're using the latest version of Next.js and in particular the latest version of its `@vercel/nft` dependency, as this performs bundling and older versions contained bugs relating to optional dependencies.

I am. Tried upgrading but now I get a message saying the build output is too large. Will report once I get that working.

**Comment by OussamaFadlaoui** [comment]
**Update:** I upgraded to NextJS 14 as per @lovell's suggestion. Builds are still failing within Amplify, however the required modules seem to be loading now upon further inspection in build artefacts;
```
 16M	./@img+sharp-libvips-linuxmusl-x64@1.0.2
 16M	./@img+sharp-libvips-linux-x64@1.0.2
```
