### ISSUE TITLE
resize + rotate occasionally cause slightly wrong image position

### ISSUE THREAD

**Issue by jardakotesovec** [lovell/sharp#417]
Hello again :-). 

I assume that these two output image should be identical, just second one rotated, right?
```
var sharp = require('sharp');

var width = 600;
var height = 500;
sharp('./testImage.png')
    .resize(width,height)
    .png().toFile('no_rotation.png')

sharp('./testImage.png')
    .resize(width,height)
    .rotate(180)
    .png().toFile('rotation.png')
```
But I am getting image slightly shifted - its easy to test it in Preview (OS X) where is easy to rotate the image and jump between two of them to see the difference. Its about 2px difference, which is big deal in my case. 

Any idea why this is happening?
I am attaching testImage.png so there is more likely you will successfully reproduce.
![testimage](https://cloud.githubusercontent.com/assets/1590681/14743280/15c8cc5a-08a1-11e6-8273-a2d40bce0842.png)

**Comment by lovell** [comment]
Hello, which version of libvips are you using for this? There are improvements (https://github.com/jcupitt/libvips/issues/404 https://github.com/jcupitt/libvips/issues/416) in v8.3.0 and sharp should get to take advantage of *some* of these without any code changes, although #310 is the ultimate goal.

**Comment by jardakotesovec** [comment]
8.3.0

**Comment by jardakotesovec** [comment]
I am wondering where it goes wrong in process. I would expect that it does the resize and than rotate, but result looks like it affects where exactly it extracts pixels from original.

**Comment by jardakotesovec** [comment]
My original usage is   .extract().resize().rotate(180) so even if its explicitly said where it should extract, it in some cases provides slightly shifted result.

**Comment by jardakotesovec** [comment]
With more testing I have just noticed that it goes wrong only if .extract().resize(width, height) has different ratio..   so resize does the calculation how to fit image.  If I use just resize(width) it seems to work correctly so far.  Which would be sufficient for me.

**Comment by lovell** [comment]
Thanks for the extra info Jarda, I'll take a closer look at this (and the 10ms delay when using raw pixels) over the weekend.

**Comment by jardakotesovec** [comment]
```
sharp('./testImage.png')
    .resize(width,height)
    .ignoreAspectRatio()
    .rotate(180)
    .png().toFile('rotation.png')
```

Also generate identical (correct) result for rotated vs non-rotated. So seems that cropping strategy gets somehow affected by rotation.

**Comment by lovell** [comment]
I think what we're seeing here is a rounding error during the final affine transformation. This is displacing the image 1px to one side and when rotating by 180 degrees displacing it 1px in the opposite direction, hence the 2px difference. The work for #310 should reduce the chance of this occurring by replacing `vips_affine` with the new `vips_reduce`.

**Comment by jardakotesovec** [comment]
I see, thanks. Does it make sense to keep it open until we can confirm that its not longer issue with `vips_reduce`?

**Comment by lovell** [comment]
Yes please.

**Comment by lovell** [comment]
The work for #310 is now available to test on the `outfit` branch. I see an improved 1px difference between the two output images from your example, which at least means rounding errors are having less of an effect.

:shipit: ?

**Comment by lovell** [comment]
@jardakotesovec Has the rounding behaviour of v0.15.0 improved the situation enough to mark this task as complete?

**Comment by jardakotesovec** [comment]
@lovell We made some changes and we don't have this rotate use case anymore. 

I still think that it would make sense that the output is identical, and just rotated. But probably does not worth spend time on it if there is no need for such use case. So feel free to close it.

Thanks for your help!

**Comment by lovell** [comment]
Thanks for the update @jardakotesovec. I'll close this for now as tracking down a rounding error will probably be more effort than it's worth. Should anyone with a little more time have the patience to work out where things might be going wrong, that would be amazing :)
