### ISSUE TITLE
Couldn't install sharp in docker image using GitHub actions.

### ISSUE THREAD

**Issue by rohit-nayak123** [lovell/sharp#4170]
## Possible install-time or require-time problem

What actually I am trying to do is to automatically build and push the docker image, using GitHub actions. Everything works well in local but not in github actions.
I am using _bun js_ and _hono js_ for making the app. Everything goes well until I try to run the docker image using github actions and  it starts showing me error. Using Github actions I was able to build the app and image however could not run it.

**Link : [Github repo](https://github.com/rohit-nayak123/compresspics)**

```cmd
94 |     name: "removeAttrs",
95 |     params: {
96 |       attrs: "(fill|stroke)"
9[7](https://github.com/rohit-nayak123/compresspics/actions/runs/9992429212/job/27617389244#step:6:8) |     }
98 |   }
99 | `;Dzi.fn=(i,n)=>{if(typeof n.attrs=="undefined")return console.warn(ozi),null;const l=typeof n.elemSeparator=="string"?n.elemSeparator:Tzi,c=typeof n.preserveCurrentColor=="boolean"?n.preserveCurrentColor:!1,u=Array.isArray(n.attrs)?n.attrs:[n.attrs];return{element:{enter:(d)=>{for(let w of u){if(w.includes(l)===!1)w=[".*",l,w,l,".*"].join("");else if(w.split(l).length<3)w=[w,l,".*"].join("");const a=w.split(l).map((f)=>{if(f==="*")f=".*";return new RegExp(["^",f,"$"].join(""),"i")});if(a[0].test(d.name))for(let[f,r]of Object.entries(d.attributes)){const x=c&&f=="fill"&&r=="currentColor",S=c&&f=="stroke"&&r=="currentColor";if(!x&&!S&&a[1].test(f)&&a[2].test(r))delete d.attributes[f]}}}}}}});var sY=W((tzi)=>{tzi.name="removeDimensions";tzi.type="perItem";tzi.active=!1;tzi.description="removes width and height in presence of viewBox (opposite to removeViewBox, disable it first)";tzi.fn=function(i){if(i.type==="element"&&i.name==="svg"){if(i.attributes.viewBox!=null)delete i.attributes.width,delete i.attrib
error: Could not load the "sharp" module using the linux-x64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
    yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=linux --cpu=x64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
      at /$bunfs/root/compressapp:99:65447
      at /$bunfs/root/compressapp:2:34[8](https://github.com/rohit-nayak123/compresspics/actions/runs/9992429212/job/27617389244#step:6:9)
      at /$bunfs/root/compressapp:[9](https://github.com/rohit-nayak123/compresspics/actions/runs/9992429212/job/27617389244#step:6:10)9:65893
      at /$bunfs/root/compressapp:2:348
      at /$bunfs/root/compressapp:99:144156
      at /$bunfs/root/compressapp:2:348
      at /$bunfs/root/compressapp:[10](https://github.com/rohit-nayak123/compresspics/actions/runs/9992429212/job/27617389244#step:6:11)9:127456
Bun v1.1.20 (Linux x64 baseline)
Error: Process completed with exit code 1.
```

- [x] I have read and understood all of the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have searched for known bugs relating to this problem in my choice of package manager.

You must confirm both of these before continuing.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest,
please open an issue against that package instead.

### Are you using a supported runtime?

- [ ] I am using Node.js with a version that satisfies `^18.17.0 || ^20.3.0 || >=21.0.0`
- [ ] I am using Deno
- [x] I am using Bun

If you cannot confirm any of these,
please upgrade to the latest version
and try again before opening an issue.

### Are you using a supported package manager and installing optional dependencies?

- [ ] I am using npm >= 10.1.0 with `--include=optional`
- [ ] I am using yarn >= 3.2.0
- [ ] I am using pnpm >= 7.1.0 with `--no-optional=false`
- [ ] I am using Deno
- [x] I am using Bun

If you cannot confirm any of these, please upgrade to the latest version of your chosen package manager
and ensure you are allowing the installation of optional or multi-platform dependencies before opening an issue.

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```cmd
#15 [build 6/8] RUN bunx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp
#15 0.194 Resolving dependencies
#15 0.257 Resolved, downloaded and extracted [4]
#15 0.257 Saved lockfile
#15 0.355 
#15 0.355   System:
#15 0.355     OS: Linux 6.5 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
#15 0.355     CPU: (4) x64 AMD EPYC 7763 64-Core Processor
#15 0.355     Memory: 13.29 GB / 15.61 GB
#15 0.355     Container: Yes
#15 0.355     Shell: 5.1.4 - /bin/bash
#15 0.355   Binaries:
#15 0.355     bun: 1.1.20 - /tmp/bun-node-ae1948925/bun
#15 0.355   npmPackages:
#15 0.355     sharp: ^0.33.4 => 0.33.4 
#15 0.355 
#15 DONE 0.4s
```

**Comment by lovell** [comment]
https://github.com/rohit-nayak123/compresspics/blob/934b4d8eb85ae8bc947f586916faf88c912102dc/Dockerfile#L11C5-L11C14

It looks like you're using `bun build...` as a code bundler so you'll need to mark `sharp` as an external, something like:

```sh
$ bun build --external sharp
```

https://sharp.pixelplumbing.com/install#bundlers

**Comment by rohit-nayak123** [comment]
Finally, I solved the problem. Actually, Sharp was not the problem at all, it was **Bun**, when I copy the build output from first stage to second stage in docker, it somehow won't work at all may be due to the different platform or whatever.

Well thanks for quick response😁.
