### ISSUE TITLE
Sharp not releasing memory after use.

### ISSUE THREAD

**Issue by darkdeathoriginal** [lovell/sharp#4171]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

System:
    OS: Linux 5.10 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
    Memory: 6.01 GB / 7.61 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.20.4 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.7.0 - /usr/local/bin/npm
  npmPackages:
    sharp: ^0.33.4 => 0.33.4

### Does this problem relate to file caching?

The default behaviour of libvips is to cache input files, which can lead to `EBUSY` or `EPERM` errors on Windows.
Use [`sharp.cache(false)`](https://sharp.pixelplumbing.com/api-utility#cache) to switch this feature off.

- [x] Adding `sharp.cache(false)` does not fix this problem.

### Does this problem relate to images appearing to have been rotated by 90 degrees?

Images that contain EXIF Orientation metadata are not auto-oriented. By default, EXIF metadata is removed.

- To auto-orient pixel values use the parameter-less [`rotate()`](https://sharp.pixelplumbing.com/api-operation#rotate) operation.
- To retain EXIF Orientation use [`keepExif()`](https://sharp.pixelplumbing.com/api-output#keepexif).

- [x] Using `rotate()` or `keepExif()` does not fix this problem.

### What are the steps to reproduce?

```js
const sharp = require("sharp");

//sharp configs
sharp.cache(false);
sharp.concurrency(2);

async function processImage(imagePath, doc, isLarge) {
  let newPath = null;
  let sharpInstance = null;

  try {
    sharpInstance = sharp(imagePath);
    const { width, height, format } = await sharpInstance.metadata();
    
    doc.addPage({ size: [width, height] });

    if (isLarge || format === 'unknown') {
      newPath = imagePath + ".jpeg";
      await sharpInstance
        .toFormat("jpeg", { quality: 80, mozjpeg: true })
        .toFile(newPath);
      doc.image(newPath, 0, 0);
    } else {
      doc.image(imagePath, 0, 0);
    }
    return
  } catch (error) {
    if(error.message.match("Unknown image format")){
      console.log("Error: Unknown image format");
      newPath = imagePath + ".jpeg";
      await sharpInstance
        .toFormat("jpeg", { quality: 80, mozjpeg: true })
        .toFile(newPath);
      doc.image(newPath, 0, 0);
      return
    }
    throw error;
  } finally {
    if (sharpInstance) {
      await sharpInstance.destroy();
    }
    sharpInstance = null;
    newPath = null;
  }
}
```

### What is the expected behaviour?

The function process the images and releases the memory

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

provided above

### Please provide sample image(s) that help explain this problem

'https://v7.mkklcdnv6tempv3.com/img/tab_27/04/64/46/uu997803/chapter_49/1-1718051747-n.webp',
  'https://v7.mkklcdnv6tempv3.com/img/tab_27/04/64/46/uu997803/chapter_49/2-1718051748-n.webp',
  'https://v7.mkklcdnv6tempv3.com/img/tab_27/04/64/46/uu997803/chapter_49/3-1718051749-n.webp',
  'https://v7.mkklcdnv6tempv3.com/img/tab_27/04/64/46/uu997803/chapter_49/4-1718051750-n.webp',
  'https://v7.mkklcdnv6tempv3.com/img/tab_27/04/64/46/uu997803/chapter_49/5-1718051751-n.webp',
  'https://v7.mkklcdnv6tempv3.com/img/tab_27/04/64/46/uu997803/chapter_49/6-1718051752-n.webp',
  'https://v7.mkklcdnv6tempv3.com/img/tab_27/04/64/46/uu997803/chapter_49/7-1718051754-n.webp',
  'https://v7.mkklcdnv6tempv3.com/img/tab_27/04/64/46/uu997803/chapter_49/8-1718051755-n.webp',
  'https://v7.mkklcdnv6tempv3.com/img/tab_27/04/64/46/uu997803/chapter_49/9-1718051757-n.webp',
  'https://v7.mkklcdnv6tempv3.com/img/tab_27/04/64/46/uu997803/chapter_49/10-1718051758-n.webp',
  'https://v7.mkklcdnv6tempv3.com/img/tab_27/04/64/46/uu997803/chapter_49/11-1718051758-n.webp',
  'https://v7.mkklcdnv6tempv3.com/img/tab_27/04/64/46/uu997803/chapter_49/12-1718051759-n.webp'

**Comment by lovell** [comment]
Please ensure you've fully read and understood everything discussed in https://github.com/lovell/sharp/issues/955

**Comment by darkdeathoriginal** [comment]
Alpine version of node solved it.
