### ISSUE TITLE
`tocolorspace` and `png({quality:x})` are mutually exclusive.

### ISSUE THREAD

**Issue by rambo-panda** [lovell/sharp#4174]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: macOS 14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.59 GB / 16.00 GB
    Shell: 3.6.1 - /usr/local/bin/fish
  Binaries:
    Node: 20.13.1 - /usr/local/bin/node
    npm: 10.5.2 - /usr/local/bin/npm
  npmPackages:
    sharp: ^0.33.4 => 0.33.4
```

### Does this problem relate to file caching?

The default behaviour of libvips is to cache input files, which can lead to `EBUSY` or `EPERM` errors on Windows.
Use [`sharp.cache(false)`](https://sharp.pixelplumbing.com/api-utility#cache) to switch this feature off.

- [x] Adding `sharp.cache(false)` does not fix this problem.

### Does this problem relate to images appearing to have been rotated by 90 degrees?

Images that contain EXIF Orientation metadata are not auto-oriented. By default, EXIF metadata is removed.

- To auto-orient pixel values use the parameter-less [`rotate()`](https://sharp.pixelplumbing.com/api-operation#rotate) operation.
- To retain EXIF Orientation use [`keepExif()`](https://sharp.pixelplumbing.com/api-output#keepexif).

- [x] Using `rotate()` or `keepExif()` does not fix this problem.

### What are the steps to reproduce?

The steps to reproduce are shown in the code below.

### What is the expected behaviour?

I hope both commands output `b-w`.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```js
var sharp = require("sharp");
var imgBuf = await fetch("https://cdn-ms.17zuoye.cn/zx-ptqlm/testing_2023_10_27/pdf_6d1e8d355613ef824d_0.webp").then(a => a.arrayBuffer());

assert.ok("b-w" === (await sharp(await sharp(imgBuf).toColorspace("b-w").png({}).toBuffer()).metadata()).space);
assert.ok("b-w" === (await sharp(await sharp(imgBuf).toColorspace("b-w").png({quality:100}).toBuffer()).metadata()).space); // throw Error
>
```

**Comment by lovell** [comment]
Palette-based PNG input is always decoded and interpreted as sRGB by libvips.

```js
const paletteBasedPng = await sharp(imgBuf).toColorspace("b-w").png({quality:100}).toBuffer();
const { space } = await sharp(paletteBasedPng).metadata();
assert.ok("srgb", space);
```
If you want to limit the size of the PNG palette to 2 entries then you can use the `colours` property.
```diff
- .png({ quality: 100 })
+ .png({ quality: 100, colours: 2 })
```
https://sharp.pixelplumbing.com/api-output#png

**Comment by rambo-panda** [comment]
> Palette-based PNG input is always decoded and interpreted as sRGB by libvips.
> 
> ```js
> const paletteBasedPng = await sharp(imgBuf).toColorspace("b-w").png({quality:100}).toBuffer();
> const { space } = await sharp(paletteBasedPng).metadata();
> assert.ok("srgb", space);
> ```
> 
> If you want to limit the size of the PNG palette to 2 entries then you can use the `colours` property.
> 
> ```diff
> - .png({ quality: 100 })
> + .png({ quality: 100, colours: 2 })
> ```
> 
> https://sharp.pixelplumbing.com/api-output#png

thank you for your guidance，I misunderstood the meaning of `quality`
