### ISSUE TITLE
Error sharp with HEIC files -  bad seek to 293616\nheif: Unsupported feature: Unsupported codec (4.3000)

### ISSUE THREAD

**Issue by mnjit20** [lovell/sharp#4175]
Hello Lovell Fuller, appreciate your efforts for this wonderful library.
I am on macOS Sonoma Version 14.5 (23F79), Node v22.3.0, npm 10.8.1 and I am trying to use sharp with HEIC files. I am getting below error.
While checking other similar older issues, I found older version v0.30.4 is working for me.
Mentioned by lovell https://github.com/lovell/sharp/issues/3239#issuecomment-1138263272

Any idea what's wrong with my setup? Thanks.

## Possible install-time or require-time problem

- [x] I have read and understood all of the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have searched for known bugs relating to this problem in my choice of package manager.

You must confirm both of these before continuing.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest,
please open an issue against that package instead.

### Are you using a supported runtime?

- [x] I am using Node.js with a version that satisfies `^18.17.0 || ^20.3.0 || >=21.0.0`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these,
please upgrade to the latest version
and try again before opening an issue.

### Are you using a supported package manager and installing optional dependencies?

- [x] I am using npm >= 10.1.0 with `--include=optional`
- [ ] I am using yarn >= 3.2.0
- [ ] I am using pnpm >= 7.1.0 with `--no-optional=false`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these, please upgrade to the latest version of your chosen package manager
and ensure you are allowing the installation of optional or multi-platform dependencies before opening an issue.

### What is the complete error message, including the full stack trace?
Error: `
{
    "status": "fail",
    "error": {
        "message": "./public/uploads/sample1.heic: bad seek to 293616\nheif: Unsupported feature: Unsupported codec (4.3000)"
    }
}
`

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

❯ npm install --verbose --foreground-scripts sharp
npm verbose cli /usr/local/bin/node /usr/local/bin/npm
npm info using npm@10.8.1
npm info using node@v22.3.0
npm verbose title npm install sharp
npm verbose argv "install" "--loglevel" "verbose" "--foreground-scripts" "sharp"
npm verbose logfile logs-max:10 dir:/Users/manjeet/.npm/_logs/2024-07-24T09_49_12_084Z-
npm verbose logfile /Users/manjeet/.npm/_logs/2024-07-24T09_49_12_084Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/sharp 755ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color 303ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/semver 334ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 339ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-darwin-arm64 382ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-darwin-x64 383ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-darwin-arm64 385ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-darwin-x64 395ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-s390x 82ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-arm64 92ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-x64 98ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linuxmusl-arm64 307ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-arm64 271ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-x64 211ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-wasm32 267ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-arm 597ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-win32-ia32 156ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linuxmusl-x64 868ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-arm 1323ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linuxmusl-arm64 933ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-s390x 1268ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linuxmusl-x64 1377ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-win32-x64 1385ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-string 188ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@emnapi%2fruntime 196ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-convert 751ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/tslib 183ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle 185ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-name 187ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-name 227ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 291ms (cache revalidated)
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@img/sharp-win32-x64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@img/sharp-win32-ia32
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@img/sharp-wasm32
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@emnapi/runtime
npm verbose reify failed optional dependency /Users/manjeet/node_modules/tslib
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@img/sharp-linuxmusl-x64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@img/sharp-linuxmusl-arm64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@img/sharp-linux-x64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@img/sharp-linux-s390x
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@img/sharp-linux-arm64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@img/sharp-linux-arm
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@img/sharp-libvips-linuxmusl-x64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@img/sharp-libvips-linuxmusl-arm64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@img/sharp-libvips-linux-x64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@img/sharp-libvips-linux-s390x
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@img/sharp-libvips-linux-arm64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@img/sharp-libvips-linux-arm
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@img/sharp-libvips-darwin-arm64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@img/sharp-darwin-arm64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@esbuild/win32-x64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@esbuild/win32-ia32
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@esbuild/win32-arm64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@esbuild/sunos-x64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@esbuild/openbsd-x64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@esbuild/netbsd-x64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@esbuild/linux-x64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@esbuild/linux-s390x
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@esbuild/linux-riscv64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@esbuild/linux-ppc64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@esbuild/linux-mips64el
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@esbuild/linux-loong64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@esbuild/linux-ia32
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@esbuild/linux-arm64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@esbuild/linux-arm
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@esbuild/freebsd-x64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@esbuild/freebsd-arm64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@esbuild/darwin-arm64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@esbuild/android-x64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@esbuild/android-arm64
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@esbuild/android-arm
npm verbose reify failed optional dependency /Users/manjeet/node_modules/@esbuild/aix-ppc64
npm info run sharp@0.33.4 install node_modules/sharp node install/check

> sharp@0.33.4 install
> node install/check

sharp: Detected globally-installed libvips v8.15.2
sharp: Attempting to build from source via node-gyp
sharp: Please add node-addon-api to your dependencies
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 404ms
npm info run sharp@0.33.4 install { code: 0, signal: null }

added 11 packages, and audited 20 packages in 10s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm verbose cwd /Users/manjeet/Downloads/not-to-sync/repos/projects/debug
npm verbose os Darwin 23.5.0
npm verbose node v22.3.0
npm verbose npm  v10.8.1
npm verbose exit 0
npm info ok
</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

<details>
npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp

  System:
    OS: macOS 14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 116.67 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.3.0 - /usr/local/bin/node
    npm: 10.8.1 - /usr/local/bin/npm

</details>

**Comment by lovell** [comment]
> sharp: Detected globally-installed libvips v8.15.2
sharp: Attempting to build from source via node-gyp
sharp: Please add node-addon-api to your dependencies

Please ensure you've read and understood the dependencies required to build from source as documented.

https://sharp.pixelplumbing.com/install#building-from-source

**Comment by mnjit20** [comment]
Thanks Lovell, let me check it once again.

**Comment by mnjit20** [comment]
@lovell thank you, I just found I missed one step `npm install --cpu=x64 --os=darwin sharp
` and after running this command its working.
