### ISSUE TITLE
Webpack node-loader support + cross-compilation

### ISSUE THREAD

**Issue by Vector-Green** [lovell/sharp#4176]
### What are you trying to achieve?

Hi, I'm working on embedded project and I need to be able to bundle node_modules into single js executable using webpack+node-loader+babel-loader
I need sharp to be able to load all .node files and run the one depending on the executable platform

### When you searched for similar feature requests, what did you find that might be related?

For example Mongoose uses this approach

### What would you expect the API to look like?

same

### What alternatives have you considered?

libv-wasm

### Please provide sample image(s) that help explain this feature

same)

**Comment by lovell** [comment]
If you're using a code bundler such as Webpack, please see https://sharp.pixelplumbing.com/install#bundlers and ensure you've configured sharp as part of your `externals`.

Please remove `node-loader` as it will cause more problems than it tries to solve. This is not the first time this dependency has been mentioned and I wonder if it's possible to make the `node-loader` dependency generate an error if someone tries to use it with sharp?

**Comment by Vector-Green** [comment]
The problem is I cannot use externals in embedded project(

**Comment by lovell** [comment]
You might have some luck with https://sharp.pixelplumbing.com/install#webassembly

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
