### ISSUE TITLE
Handling HEIC files in an Electron application and distributing

### ISSUE THREAD

**Issue by Xheldon** [lovell/sharp#4177]
### What are you trying to achieve?

An corss-platform electron application handle HEIC/HEIF images.

## Question:
I am using Electron-forge to build an Electron application. I installed sharp directly in the project (I'm not sure if there is libvips on the machine), and it handles common image formats well. So, I packaged it and distributed it to Mac x64 and arm64 platforms as well as Windows platforms, and it runs well.
Now, I want it to support HEIC/HEIF image formats, what should I do?

Additionally: The Mac version of my application is packaged and built on my local Mac arm64 machine, and my Windows version is packaged on Windows x64 Github Action.

I checked the relevant documentation like build-from-source, but I'm not clear if the global installation of libraries like libvips on my local machine will be packaged into my Electron application for distribution when I build the application? Or, is it only available locally (because only I have globally installed libvips on my local machine, and my users haven’t installed it, so they cannot process HEIC/HEIF)?

I looked into some issues like #4175 , and I encountered the same HEIC problem as they did, but it didn't resolve my doubt.

Thanks for the explanation!

**Comment by lovell** [comment]
The quick answer is: this will be a world of pain, look for an alternative.

**Comment by Xheldon** [comment]
Thanks for reply!
