### ISSUE TITLE
Feature Request: Please support running in a browser (without node.js)

### ISSUE THREAD

**Issue by boustanihani** [lovell/sharp#4179]
Feature Request:

Please also support a mode for running in modern browsers without the need for node.js :)

**Comment by lovell** [comment]
Sharp requires a Node-API compatible runtime. Perhaps take a look at https://github.com/kleisauke/wasm-vips if you need something similar for use in a web browser.

**Comment by boustanihani** [comment]
Thanks a lot for the quick reply.

**Comment by ToPeas** [comment]
I have the same need, is there a solution?

**Comment by boustanihani** [comment]
> I have the same need, do you have a solution? @boustanihani

Sorry, I do not have a solution.
