### ISSUE TITLE
GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed error

### ISSUE THREAD

**Issue by SuThaw** [lovell/sharp#418]
```
let img = sharp(config.root + '/' + image.path);
 	img
 		.resize(image.width,image.height)
 		.toFile(config.root+ '/public/img/'+ image.loc +'thumbs/' + image.name);

 	return config.host + '/img/' + image.loc + 'thumbs/' +  image;
```
I tested the above code with mocha. Sometimes it work, but sometime it showed the following error

**"GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed error"**

**Comment by lovell** [comment]
Hello, please can you increase the mocha timeout as this is likely to be related to https://github.com/lovell/sharp/issues/409#issuecomment-210111143

**Comment by lovell** [comment]
@SuThaw Have you been able to make any progress?

**Comment by lovell** [comment]
Closing due to lack of updates - please feel free to re-open if the problem persists.

**Comment by niftylettuce** [comment]
Same issue occurs for me with latest version and Node v8.2.x on OS X.

**Comment by niftylettuce** [comment]
Upon adding `.on('error', console.error)` to my `sharp` stream, I get the following output now:

```log
(sharp:29079): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:29079): GLib-CRITICAL **: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed

(sharp:29079): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed
[1]    29079 segmentation fault  node scripts/fix-broken-images.js
```

**Comment by lovell** [comment]
Hello, did you see https://github.com/lovell/sharp/issues/409#issuecomment-210111143 ? These warnings can appear when the `node` process exits, usually for reasons unrelated to sharp, but where images are still being processed. Please open a new issue if you're still experiencing problems due to an error from sharp.
