### ISSUE TITLE
how to cache sharp binaries?

### ISSUE THREAD

**Issue by sibelius** [lovell/sharp#4181]
## Question about an existing feature

Is it possible to cache sharp binaries ?

### What are you trying to achieve?

Try to cache sharp to make yarn install faster

### When you searched for similar issues, what did you find that might be related?

search on all issues

**Comment by lovell** [comment]
As of sharp v0.33.0+, all prebuilt binaries are distributed entirely via the npm registry and rely on your choice of package manager for caching features.
