### ISSUE TITLE
Sharp HEIC export is 4.4x bigger than equivalent macOS Finder export

### ISSUE THREAD

**Issue by trevor-e** [lovell/sharp#4182]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 124.69 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.0 - ~/.nvm/versions/node/v20.12.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.6.0 - ~/.nvm/versions/node/v20.12.0/bin/npm
    pnpm: 9.5.0 - /opt/homebrew/bin/pnpm
    Watchman: 2024.07.01.00 - /opt/homebrew/bin/watchman
  npmPackages:
    sharp: 0.33.4 => 0.33.4
```

### Does this problem relate to file caching?

The default behaviour of libvips is to cache input files, which can lead to `EBUSY` or `EPERM` errors on Windows.
Use [`sharp.cache(false)`](https://sharp.pixelplumbing.com/api-utility#cache) to switch this feature off.

- [x] Adding `sharp.cache(false)` does not fix this problem.

### Does this problem relate to images appearing to have been rotated by 90 degrees?

Images that contain EXIF Orientation metadata are not auto-oriented. By default, EXIF metadata is removed.

- To auto-orient pixel values use the parameter-less [`rotate()`](https://sharp.pixelplumbing.com/api-operation#rotate) operation.
- To retain EXIF Orientation use [`keepExif()`](https://sharp.pixelplumbing.com/api-output#keepexif).

- [x] Using `rotate()` or `keepExif()` does not fix this problem.

### What are the steps to reproduce?

- Take a PNG image and convert it to HEIC using sharp
- Open the same PNG image in macOS Finder, and export it to HEIC using the default settings
- Observe that the sharp image filesize is much bigger than (over 4x bigger) exports from macOS's Finder tool.

### What is the expected behaviour?

- The filesize should be the same, or there should be exposed options allowing us to configure compression to be the same

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```
await sharp(filePath)
  .heif({ quality: 85, compression: 'hevc', chromaSubsampling: '4:2:0' })
  .toFile(tempFilePath);
```

I manually compiled libvips from source with libheif support and linked the sharp binary against it.

I'm able to confirm that 85% compression is what Finder uses by writing an equivalent Swift program that uses `CGImageDestinationAddImage()`.

I wrote a script to compare the metadata of each output file and this is what I see:
```
Differences found in metadata:
  File Size:
    Finder export: 168 kB
    Sharp export:  741 kB
  Media Data Size:
    Finder export: 167403
    Sharp export:  740169
  Media Data Offset:
    Finder export: 806
    Sharp export:  359
  Compatible Brands:
    Finder export: mif1, miaf, heic, MiHB
    Sharp export:  mif1, miaf, heic
  Primary Item Reference:
    Finder export: 7
    Sharp export:  1
  Constraint Indicator Flags:
    Finder export: 176 0 0 0 0 0
    Sharp export:  0 0 0 0 0 0
  General Level IDC:
    Finder export: 90 (level 3.0)
    Sharp export:  120 (level 4.0)
  Temporal ID Nested:
    Finder export: No
    Sharp export:  Yes

Metadata only in Finder export:
  Meta Image Size: 896x1344
  Exif Byte Order: Big-endian (Motorola, MM)
  Orientation: Horizontal (normal)
  Color Profiles: nclx
  Color Primaries: Unspecified
  Transfer Characteristics: Unspecified
  Matrix Coefficients: BT.601
  Video Full Range Flag: 1
  Rotation: 0
```

Nothing in particular stands out to me that would cause such a big filesize difference.

### Please provide sample image(s) that help explain this problem

I'll edit this with some pictures afterwards.

**Comment by lovell** [comment]
> I'm able to confirm that 85% compression is what Finder uses

Are you able to explain more about this statement? What are the specific encoder settings that the "85% compression" refers to? Are you able to reproduce via `heif-enc` at the command line?

**Comment by trevor-e** [comment]
> > I'm able to confirm that 85% compression is what Finder uses
> 
> Are you able to explain more about this statement? What are the specific encoder settings that the "85% compression" refers to? Are you able to reproduce via `heif-enc` at the command line?

By this I mean I have a simple Swift program using Apple's `CoreGraphics` framework which appears to match Finder's output when I set the compression level to 85%:
```
CGImageDestinationCreateWithData(
  data, AVFileType.heic as CFString, 1, nil
)
let options: NSDictionary = [
  kCGImageDestinationLossyCompressionQuality: 0.85
]
CGImageDestinationAddImage(imageDestination, self, options)
CGImageDestinationFinalize(imageDestination)
```
That's why I used `.heif({ quality: 85, compression: 'hevc', chromaSubsampling: '4:2:0' })` for my `sharp` code. I expected the output files to be the same, but the Swift/Finder outputs are much smaller.

I just tested `heif-enc`:
```
heif-enc -q 85 test-input.png -o test-output.heic
stat test-output.heic
16777233 115633569 -rw-r--r-- 1 telkins staff 0 743270 "Jul 30 19:54:25 2024" "Jul 30 19:54:23 2024" "Jul 30 19:54:23 2024" "Jul 30 19:54:23 2024" 4096 1456 0 test-output.heic
```
The resulting size (743kb) roughly matches sharp, the 2kb difference I think is from not including chromaSubsampling, so I guess `sharp` is working correctly from this perspective. Curious if you have any guess at what might be happening, but sounds like I should redirect my question/findings to the `libheif` project. Thanks!

**Comment by lovell** [comment]
A single value of "quality" may be used by an h265 encoder to control many levers. Apple don't appear to provide this information for CoreGraphics, but we can see from the open source libheif/x265 that it uses "quality" in its calculation for the value of "ratefactor constant":

https://github.com/strukturag/libheif/blob/15ff08fea0695624c875ab92f48556d67fb453f0/libheif/plugins/encoder_x265.cc#L835

If you've not already done so, you should probably experiment with the `effort` parameter exposed by sharp, which maps onto libheif's `speed` setting and will influence output file size.

https://sharp.pixelplumbing.com/api-output#heif

There is also be a `complexity` setting in libheif, which is not currently exposed by sharp/libvips, that allows some control over "rate distortion optimisation" and is therefore another "quality"-like lever.

**Comment by trevor-e** [comment]
Thanks for the tips. I tried setting `effort` to both 0 and 9 (fastest/slowest) and unfortunately saw no change in the filesize.

**Comment by trevor-e** [comment]
@lovell Coming back to this, I was able to test this out:
```
heif-enc input.png -o output.heic -p preset=slower
```
which produces a much smaller image of 123KB (743KB with the default preset). 

I'm wondering if there's a bug going on with the `effort` mapping here between libheif/x265? Is it possible to expose custom options that we can pass through to the underlying libheif call or would that be ill-advised?

**Comment by lovell** [comment]
Moved to https://github.com/strukturag/libheif/issues/1266
