### ISSUE TITLE
Vercel production issue: .jpeg({ quality: XX }) not working at all - works in local env

### ISSUE THREAD

**Issue by Ehtz** [lovell/sharp#4183]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [ ] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [ x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

  System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 14.73 GB / 31.73 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.30.0 - ~\AppData\Local\pnpm\pnpm.EXE
  npmPackages:
    sharp: ^0.33.4 => 0.33.4

### Does this problem relate to file caching?

The default behaviour of libvips is to cache input files, which can lead to `EBUSY` or `EPERM` errors on Windows.
Use [`sharp.cache(false)`](https://sharp.pixelplumbing.com/api-utility#cache) to switch this feature off.

- [ ] Adding `sharp.cache(false)` does not fix this problem.

### Does this problem relate to images appearing to have been rotated by 90 degrees?

Images that contain EXIF Orientation metadata are not auto-oriented. By default, EXIF metadata is removed.

- To auto-orient pixel values use the parameter-less [`rotate()`](https://sharp.pixelplumbing.com/api-operation#rotate) operation.
- To retain EXIF Orientation use [`keepExif()`](https://sharp.pixelplumbing.com/api-output#keepexif).

- [ ] Using `rotate()` or `keepExif()` does not fix this problem.

### What are the steps to reproduce?

```
    const sharp = require('sharp');

    const uploadImage = async (picture: any, prefix = '') => {
      const fileName = `${prefix}${uuidv4()}.${picture.name.split('.').pop()}`;
      const bytes = await picture.arrayBuffer();
      const buffer = Buffer.from(bytes);

      // Compress the image using Sharp
      const compressedBuffer = await sharp(buffer)
        .jpeg({ quality: 50 }) // You can adjust the quality here
        .toBuffer();

      const { data: image, error: imageErr } = await supabase.storage
        .from('Image')
        .upload(`${folder}/${fileName}`, compressedBuffer);

      if (imageErr) throw new Error(imageErr.message);
    };

    // Store images in folder
    const pictureUploadPromises = pictures.map((picture: any) =>
      uploadImage(picture)
    );
    await Promise.all(pictureUploadPromises);
    
  ```

### What is the expected behaviour?

To reduce the size of the files according to diminishing of image jpeg quality

**Comment by Ehtz** [comment]
Works in local env no problem -  vercel NextJs used to work, not anymore. I tried versions 0.33.4 and 0.32.6. Same issues

**Comment by lovell** [comment]
What does "not working at all" mean? Is there a runtime error you're able to provide?

If this problem only occurs on Vercel, what did Vercel support say when you asked them?

**Comment by Ehtz** [comment]
Hi thank you for your response. I have checked Vercel Logs no issues to be registered however in the production console I am getting a payload error because of supabase limitation indicating that Sharp is not resizing the images:

<img width="176" alt="image" src="https://github.com/user-attachments/assets/4091d0d8-4d6f-43b2-8161-3587c2f11d36">

With the same code - in local I am getting no errors, Sharp is working perfectly

**Comment by lovell** [comment]
These errors appear to be from a browser console. Please remember that sharp requires a Node.js compatible runtime and will not work in a web browser.

If you still require help you'll need to create a minimal repo without any other dependencies (no networking, no Supabase etc.) that allows someone else to reproduce. I cannot help with Vercel or Supabase specific problems, please speak with their respective support teams.

**Comment by lovell** [comment]
@Ehtz Were you able to make any progress with this?

**Comment by Ehtz** [comment]
> @Ehtz Were you able to make any progress with this?

Hi, thank you for checking up - I haven't had time to look more into this issue. I think I am going to try another library - I've tested it today in local and still works perfectly just in production within Vercel doesn't...

**Comment by lovell** [comment]
Thanks for the update. What did Vercel support say when you asked them?

**Comment by Ehtz** [comment]
They reduced the payload recently per api call Great!
<img width="839" alt="image" src="https://github.com/user-attachments/assets/863dabc7-90de-4059-82d5-9273b9cc2a33">
https://vercel.community/t/413-payload-too-large/218/4

**Comment by Ehtz** [comment]
https://vercel.com/guides/how-to-bypass-vercel-body-size-limit-serverless-functions#upload-directly-to-the-source
