### ISSUE TITLE
PNG Conversion Failure

### ISSUE THREAD

**Issue by stefanpieper** [lovell/sharp#4184]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: macOS 14.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 54.48 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.12.2/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.6.0 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
  npmPackages:
    sharp: ^0.33.4 => 0.33.4 
```

### Does this problem relate to file caching?

The default behaviour of libvips is to cache input files, which can lead to `EBUSY` or `EPERM` errors on Windows.
Use [`sharp.cache(false)`](https://sharp.pixelplumbing.com/api-utility#cache) to switch this feature off.

- [x] Adding `sharp.cache(false)` does not fix this problem.

### Does this problem relate to images appearing to have been rotated by 90 degrees?

Images that contain EXIF Orientation metadata are not auto-oriented. By default, EXIF metadata is removed.

- To auto-orient pixel values use the parameter-less [`rotate()`](https://sharp.pixelplumbing.com/api-operation#rotate) operation.
- To retain EXIF Orientation use [`keepExif()`](https://sharp.pixelplumbing.com/api-output#keepexif).

- [x] Using `rotate()` or `keepExif()` does not fix this problem.

### What are the steps to reproduce?

See attached archive with test code and data. The PNG test image is loaded and resized, then written to a buffer.

[png-conversion-failure.zip](https://github.com/user-attachments/files/16508058/png-conversion-failure.zip)

When executing the test code, this error is thrown:

```
Error: pngload_buffer: libspng read error
    at Sharp.toBuffer (/Users/spieper/src/phoenix.imts-library/png-conversion-failure/node_modules/sharp/lib/output.js:161:17)
    at pngConversionFailure (/Users/spieper/src/phoenix.imts-library/png-conversion-failure/png-conversion-failure.js:8:49)
```

### What is the expected behaviour?

Process completes without error.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

See attached archive.

### Please provide sample image(s) that help explain this problem

See attached archive.

**Comment by lovell** [comment]
This looks like a corrupt/truncated PNG image. If you trust the source of this image, please see the `failOn` constructor property to relax how warnings and errors are handled.

https://sharp.pixelplumbing.com/api-constructor

```js
// USE THIS FOR TRUSTED INPUT ONLY
sharp(input, { failOn: 'none' })...
```

**Comment by stefanpieper** [comment]
Thanks a lot for your quick help!
