### ISSUE TITLE
Resize images while keeping the ICC profile and color space

### ISSUE THREAD

**Issue by ollm** [lovell/sharp#4186]
### What are you trying to achieve?

I'm trying to resize images while keeping the ICC profile and color space, currently it only seems to work with the P3 profile, with other profiles it seems like `sharp` stretches the image (And accumulates every time it is resized). I don't know if I'm doing something wrong.

I am using `sharp 0.33.4`

### When you searched for similar issues, what did you find that might be related?

https://github.com/lovell/sharp/issues/4008, https://github.com/lovell/sharp/issues/3906 and https://github.com/lovell/sharp/issues/4128

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

``` js
sharp('input.jpg')
	.keepIccProfile()
	.resize({kernel: 'lanczos3', width: 500})
	.png({compressionLevel: 0, force: true})
	//.toBuffer()
	.toFile('output.png');
```

Original
<img height="200" alt="Rose-ProPhoto" title="Rose-ProPhoto" src="https://github.com/user-attachments/assets/bc11564a-b9c4-4ca9-88d9-af22d13d0322">

Resized with `keepIccProfile` 
<img height="200" alt="Rose-ProPhoto-2" title="Rose-ProPhoto-2" src="https://github.com/user-attachments/assets/9b11c67d-2a16-467c-a3b3-4bc9be5c4a54">

Resized with `keepIccProfile`  2 times
<img height="200" alt="Rose-ProPhoto-3" title="Rose-ProPhoto-3" src="https://github.com/user-attachments/assets/8557b1c9-385e-4044-9ec1-165613fb241d">

### Please provide sample image(s) that help explain this question

[images.zip](https://github.com/user-attachments/files/16523520/images.zip)

**Comment by lovell** [comment]
Commit 2eb03b0 fixes this by preventing an unnecessary colour transformation plus adds a test that would previously have failed to help prevent regression, thanks for reporting.

**Comment by ollm** [comment]
Thanks you for the fix!

**Comment by lovell** [comment]
v0.33.5 now available with the fix.

**Comment by ollm** [comment]
Thanks you, I have tested the new version with different images and it works fine.
