### ISSUE TITLE
sharp 在获取某些webp图片元数据时导致文件句柄未被正确释放

### ISSUE THREAD

**Issue by jdhddsk** [lovell/sharp#4188]
## Describe the bug
当使用 `sharp` 获取某些图片的元数据时，发现某些webp图片的文件句柄没有被正确释放，导致进程持续占用这些文件。

## To Reproduce
1. 使用 `sharp` 加载一张.webp图片。
2. 调用 `metadata()` 方法获取图片元数据。
3. 观察文件句柄是否被正确释放。

## Expected behavior
文件句柄应该在处理完成后被正确释放。

## Environment
- sharp version: [0.33.4]
- OS: [Windows 10]
- Node.js version: [v20.14.0]

## Additional context
Error: EBUSY: resource busy or locked, unlink ....

**Comment by lovell** [comment]
It looks like the issue template was ignored/deleted.

If you still require help, please provide an answer to the following question from the issue template:

### Does this problem relate to file caching?

The default behaviour of libvips is to cache input files, which can lead to `EBUSY` or `EPERM` errors on Windows.
Use [`sharp.cache(false)`](https://sharp.pixelplumbing.com/api-utility#cache) to switch this feature off.

- [ ] Adding `sharp.cache(false)` does not fix this problem.

**Comment by jdhddsk** [comment]
> It looks like the issue template was ignored/deleted.
> 
> If you still require help, please provide an answer to the following question from the issue template:
> 
> ### Does this problem relate to file caching?
> The default behaviour of libvips is to cache input files, which can lead to `EBUSY` or `EPERM` errors on Windows. Use [`sharp.cache(false)`](https://sharp.pixelplumbing.com/api-utility#cache) to switch this feature off.
> 
> * [ ]  Adding `sharp.cache(false)` does not fix this problem.

Thank you, effective
