### ISSUE TITLE
In network contrained environement we shoud have a diferent url for github like an artifactory proxy

### ISSUE THREAD

**Issue by yodatak** [lovell/sharp#4193]
When we use in contrained environement it try to download already build binnary its great but i cannot use a different url to download this file and i cannot acces to github.com so i have to proxy it can we do a environement variable to permit to change this url  ?

Did they is a different workarround for this ?

Thanks !

from-github-release.js
https://github.com/lovell/sharp/blob/fc32e0bd3f9111b80cf078df7b0cfc355695674e/npm/from-github-release.js#L42

**Comment by lovell** [comment]
Please ensure you are using the latest version as everything is published to the npm registry and nothing is downloaded from GitHub.

(The file you link to contains pre-publish logic and does not run on your machine.)
