### ISSUE TITLE
How to maintain oiriginal image quality?

### ISSUE THREAD

**Issue by henryfra14** [lovell/sharp#4202]
I'm trying to watermark or resize the original image.

and I want to save it in jpeg format and maintain the quality of the original image.

When saving after work, the quality seems to be set to default 80.

If the quality of the original image is 90, is there a way to save or output the work result while maintaining this quality?

```
await sharp('image.jpg')
.composite([{input: watermark, gravity: 'centre'}])
.jpeg({
   quality: 100
})
```

Should I set the quality to 100 as above to maintain the same quality as the original image? Or is there another way?

**Comment by lovell** [comment]
Please see #908
