### ISSUE TITLE
App loading issue while using Sharp in React Native App

### ISSUE THREAD

**Issue by dsriny** [lovell/sharp#4205]
sharp 0.33.5 
Node.js v18.20.4

used in mobile react native component by importing sharp library and calling sharp functions 
await sharp()

Does sharp supports for above node ? If yes then what could be reason for this errors, did couple of things to resolve
- Installed all dependant modules for sharp but still get loading issues., Any suggestions
- 
- [color](https://www.npmjs.com/package/color) ( its dependencies as listed )
- [detect-libc](https://www.npmjs.com/package/detect-libc)
- [semver](https://www.npmjs.com/package/semver)

Errors

node_modules/sharp/lib/constructor.js: node:util could not be found within the project or in these directories:
  node_modules/sharp/node_modules
  node_modules
  ../node_modules
  ../../node_modules
  ../../../node_modules
  4 | 'use strict';
  5 |
> 6 | const util = require('node:util');
    |                       ^
  7 | const stream = require('node:stream');
  8 | const is = require('./is');
  9 |]

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/2229#issuecomment-635330403

**Comment by dsriny** [comment]
Thanks @lovell Got it,  this libray is not supported for React Native
