### ISSUE TITLE
Composite keep tiling even if tile is false

### ISSUE THREAD

**Issue by egstar** [lovell/sharp#4209]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp,next --npmGlobalPackages=sharp`?

```text
  System:
    OS: Linux 4.18 AlmaLinux 8.10 (Cerulean Leopard)
    CPU: (2) x64 AMD EPYC 7543P 32-Core Processor
    Memory: 4.83 GB / 7.77 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 22.8.0 - ~/.nvm/versions/node/v22.8.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v22.8.0/bin/yarn
    npm: 10.8.2 - ~/.nvm/versions/node/v22.8.0/bin/npm
  npmPackages:
    next: 14.2.5 => 14.2.5 
    sharp: ^0.33.5 => 0.33.5 
```

### What are the steps to reproduce?

The tile options works normally on localhost, but when i use after on Almalinux 8 server it ignores false status

[test link](https://hp.burhams.com/rent/home/test/test/66c9d73fc331deaa356f7f09)

### What is the expected behaviour?

To have a single logo in the center of the original image.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```js
await sharp(image).webp({ quality: 100 })
                    .composite([
                        {
                            input: 'src/data/assets/images/logo.webp',
                            gravity: 'center',
                            blend: 'overlay',
                            tile: false,
                        }
                    ])
                    .toBuffer()
                    .then((img) => {
                        data = `${img.toString('base64')}`
                    })

```

### Please provide sample image(s) that help explain this problem
Current result ( On server )
![currentres](https://github.com/user-attachments/assets/0a359ad5-8ac4-45df-8c84-3b5f8469fbe3)
-----
Expected result ( Same as on localhost )
![expected](https://github.com/user-attachments/assets/6b164a04-0ca6-426e-8bb6-0097c06d21b4)

**Comment by lovell** [comment]
Please can you provide a minimal, standalone code sample and image that allows someone else to reproduce.

**Comment by egstar** [comment]
Oh, after testing the standalone function, i found the typo, that the source of image was already saved with the tiles, that's why, Sorry for bothering you, has been fixed..

Thanks for your reply
