### ISSUE TITLE
chromaSubsampling removed from webp in sharp 0.33.5?

### ISSUE THREAD

**Issue by Tor-sudo** [lovell/sharp#4219]
Should we now use `smartSubsample` instead of `chromaSubsampling` for webp images?
Is `smartSubsample:false` similar to `chromaSubsampling: '4:2:0'`?

**Comment by lovell** [comment]
WebP images are always 4:2:0 subsampled and there has never been a `chromaSubsampling` option.

The `smartSubsample` option tells the encoder to spend a bit more CPU time on the RGB to YUV conversion, which can improve colours around edges.

https://sharp.pixelplumbing.com/api-output#webp

**Comment by Tor-sudo** [comment]
> WebP images are always 4:2:0 subsampled and there has never been a `chromaSubsampling` option.
> 
> The `smartSubsample` option tells the encoder to spend a bit more CPU time on the RGB to YUV conversion, which can improve colours around edges.
> 
> https://sharp.pixelplumbing.com/api-output#webp

Ok. But can i use it for avif?

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/api-output#avif

| Param | Type | Default | Description |
| --- | --- | --- | --- |
| [options.chromaSubsampling] | <code>string</code> | <code>&quot;&#x27;4:4:4&#x27;&quot;</code> | set to '4:2:0' to use chroma subsampling |
