### ISSUE TITLE
Can't install sharp v0.12.2 with node 6

### ISSUE THREAD

**Issue by MichaelBuen** [lovell/sharp#422]
Error shown when I tried to install:

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.12.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.12.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm instal

**Comment by lovell** [comment]
Please can you try with v0.14.1, the latest version.

**Comment by MichaelBuen** [comment]
Thanks Lovell, it worked!
