### ISSUE TITLE
Error: Could not load the "sharp" module using the darwin-arm64 runtime

### ISSUE THREAD

**Issue by BhupenPal** [lovell/sharp#4225]
## Possible install-time or require-time problem

- [x] I have read and understood all of the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have searched for known bugs relating to this problem in my choice of package manager.

You must confirm both of these before continuing.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest,
please open an issue against that package instead.

### Are you using a supported runtime?

- [x] I am using Node.js with a version that satisfies `^18.17.0 || ^20.3.0 || >=21.0.0`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these,
please upgrade to the latest version
and try again before opening an issue.

### Are you using a supported package manager and installing optional dependencies?

- [ ] I am using npm >= 10.1.0 with `--include=optional`
- [ ] I am using yarn >= 3.2.0
- [x] I am using pnpm >= 7.1.0 with `--no-optional=false`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these, please upgrade to the latest version of your chosen package manager
and ensure you are allowing the installation of optional or multi-platform dependencies before opening an issue.

### What is the complete error message, including the full stack trace?

```
Provided module can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: Error: Could not load the "sharp" module using the darwin-arm64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=darwin --cpu=arm64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at ./node_modules/.pnpm/sharp@0.33.5/node_modules/sharp/lib/sharp.js (/Users/bhupenpal/Drive/DPI Corporation/picasso/dist/index.js:9815:9)
    at __webpack_require__ (/Users/bhupenpal/Drive/DPI Corporation/picasso/dist/index.js:10159:42)
    at ./node_modules/.pnpm/sharp@0.33.5/node_modules/sharp/lib/constructor.js (/Users/bhupenpal/Drive/DPI Corporation/picasso/dist/index.js:4994:1)
    at __webpack_require__ (/Users/bhupenpal/Drive/DPI Corporation/picasso/dist/index.js:10159:42)
    at ./node_modules/.pnpm/sharp@0.33.5/node_modules/sharp/lib/index.js (/Users/bhupenpal/Drive/DPI Corporation/picasso/dist/index.js:5453:15)
    at __webpack_require__ (/Users/bhupenpal/Drive/DPI Corporation/picasso/dist/index.js:10159:42)
    at ./src/index.ts (/Users/bhupenpal/Drive/DPI Corporation/picasso/dist/index.js:4246:33)
    at __webpack_require__ (/Users/bhupenpal/Drive/DPI Corporation/picasso/dist/index.js:10159:42)
    at /Users/bhupenpal/Drive/DPI Corporation/picasso/dist/index.js:10176:37
    at Object.<anonymous> (/Users/bhupenpal/Drive/DPI Corporation/picasso/dist/index.js:10181:12)
Could not load the function, shutting down.
```

<details>
npm verbose cli /opt/homebrew/Cellar/node/22.7.0/bin/node /opt/homebrew/bin/npm
npm info using npm@10.8.2
npm info using node@v22.7.0
npm verbose title npm install sharp
npm verbose argv "install" "--loglevel" "verbose" "--foreground-scripts" "sharp"
npm verbose logfile logs-max:10 dir:/Users/bhupenpal/.npm/_logs/2024-10-01T14_07_42_046Z-
npm verbose logfile /Users/bhupenpal/.npm/_logs/2024-10-01T14_07_42_046Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/sharp 287ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 76ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/color 197ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/semver 206ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-darwin-x64 209ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-arm 279ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-darwin-arm64 365ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-darwin-x64 405ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-arm64 270ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-darwin-arm64 477ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-x64 268ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-s390x 272ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linuxmusl-arm64 223ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linuxmusl-x64 299ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-arm 280ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-arm64 220ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-s390x 219ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linuxmusl-arm64 263ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-x64 278ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linuxmusl-x64 274ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-wasm32 294ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-win32-ia32 278ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-win32-x64 278ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/color-convert 62ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-string 76ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@emnapi%2fruntime 82ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/tslib 60ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-name 62ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/color-name 64ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle 64ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 68ms (cache revalidated)
npm verbose reify failed optional dependency /Users/bhupenpal/Desktop/cronner/node_modules/@img/sharp-win32-x64
npm verbose reify failed optional dependency /Users/bhupenpal/Desktop/cronner/node_modules/@img/sharp-win32-ia32
npm verbose reify failed optional dependency /Users/bhupenpal/Desktop/cronner/node_modules/@img/sharp-wasm32
npm verbose reify failed optional dependency /Users/bhupenpal/Desktop/cronner/node_modules/@emnapi/runtime
npm verbose reify failed optional dependency /Users/bhupenpal/Desktop/cronner/node_modules/tslib
npm verbose reify failed optional dependency /Users/bhupenpal/Desktop/cronner/node_modules/@img/sharp-linuxmusl-x64
npm verbose reify failed optional dependency /Users/bhupenpal/Desktop/cronner/node_modules/@img/sharp-linuxmusl-arm64
npm verbose reify failed optional dependency /Users/bhupenpal/Desktop/cronner/node_modules/@img/sharp-linux-x64
npm verbose reify failed optional dependency /Users/bhupenpal/Desktop/cronner/node_modules/@img/sharp-linux-s390x
npm verbose reify failed optional dependency /Users/bhupenpal/Desktop/cronner/node_modules/@img/sharp-linux-arm64
npm verbose reify failed optional dependency /Users/bhupenpal/Desktop/cronner/node_modules/@img/sharp-linux-arm
npm verbose reify failed optional dependency /Users/bhupenpal/Desktop/cronner/node_modules/@img/sharp-libvips-linuxmusl-x64
npm verbose reify failed optional dependency /Users/bhupenpal/Desktop/cronner/node_modules/@img/sharp-libvips-linuxmusl-arm64
npm verbose reify failed optional dependency /Users/bhupenpal/Desktop/cronner/node_modules/@img/sharp-libvips-linux-x64
npm verbose reify failed optional dependency /Users/bhupenpal/Desktop/cronner/node_modules/@img/sharp-libvips-linux-s390x
npm verbose reify failed optional dependency /Users/bhupenpal/Desktop/cronner/node_modules/@img/sharp-libvips-linux-arm64
npm verbose reify failed optional dependency /Users/bhupenpal/Desktop/cronner/node_modules/@img/sharp-libvips-linux-arm
npm verbose reify failed optional dependency /Users/bhupenpal/Desktop/cronner/node_modules/@img/sharp-libvips-darwin-x64
npm verbose reify failed optional dependency /Users/bhupenpal/Desktop/cronner/node_modules/@img/sharp-darwin-x64
npm http fetch GET 200 https://registry.npmjs.org/detect-libc/-/detect-libc-2.0.3.tgz 63ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/color-string/-/color-string-1.9.1.tgz 63ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/color/-/color-4.2.3.tgz 63ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle/-/simple-swizzle-0.2.2.tgz 78ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/sharp/-/sharp-0.33.5.tgz 78ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img/sharp-darwin-arm64/-/sharp-darwin-arm64-0.33.5.tgz 86ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img/sharp-libvips-darwin-arm64/-/sharp-libvips-darwin-arm64-1.0.4.tgz 451ms (cache miss)
npm info run sharp@0.33.5 install node_modules/sharp node install/check

> sharp@0.33.5 install
> node install/check

npm info run sharp@0.33.5 install { code: 0, signal: null }

added 11 packages in 4s

3 packages are looking for funding
  run `npm fund` for details
npm verbose cwd /Users/bhupenpal/Desktop/cronner
npm verbose os Darwin 24.0.0
npm verbose node v22.7.0
npm verbose npm  v10.8.2
npm verbose exit 0
npm info ok
</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?
```
  System:
    OS: macOS 15.0
    CPU: (8) arm64 Apple M1
    Memory: 55.61 MB / 8.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 22.7.0 - /opt/homebrew/bin/node
    npm: 10.8.2 - /opt/homebrew/bin/npm
    pnpm: 9.7.0 - /opt/homebrew/bin/pnpm
  npmPackages:
    sharp: ^0.33.5 => 0.33.5 
```

**Comment by lovell** [comment]
>     at __webpack_require__ (/Users/bhupenpal/Drive/DPI Corporation/picasso/dist/index.js:10159:42)

It looks like you're using Webpack to bundle your code, please see https://sharp.pixelplumbing.com/install#webpack

**Comment by BhupenPal** [comment]
Yup, actually figured out. Thank you so much for taking out time and replying to this issue.
Marking it as closed!
