### ISSUE TITLE
Image resizing prioritizes image ratio higher than resize target dimensions

### ISSUE THREAD

**Issue by BernhardBehrendt** [lovell/sharp#4226]
## Question about an existing feature => resize(number, number, { fit: 'inside' })

Using the resize method to scale down an image into a target format

> Existing and occurring dimensions written on filenames.

```javascript
import sharp from 'sharp';

sharp('input-image-1650×1275.jpg')
  .resize(610, 854, { fit: 'inside' })
  .toFile('output-image-610×471.jpg');

```

### What are you trying to achieve?

Keeping the desired dimension:

The resulting output image is 610 × 471 and desired taget height of 854 is not applied as value for the down sized image. 
I think especially with `fit:inside`option set that the output image has a size of 610x854 with the image having a size of 610x471 vertically centered. Is this somehow achievable? Thanks very much for any guidance :-)

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question
The code above is a working example that can be reproduced by e.g. using this image:
![Sample Image](https://placehold.co/1650x1275.jpg)

**Comment by lovell** [comment]
Did you see https://sharp.pixelplumbing.com/api-resize#resize ? What you describe sounds more like `fit: contain`.

**Comment by BernhardBehrendt** [comment]
Thanks yes using fit contain it's working. Had another issue that made it appear contain was the wrong solution.
Thank you so much for pointing me to the right direction.
