### ISSUE TITLE
Can't read an image, modify it, then save it with the same name

### ISSUE THREAD

**Issue by zelms** [lovell/sharp#4230]
## Edit

I realize this is more of a feature request than it is an issue, since the code does give an error if the output file name is the same as the input file name. I will leave my original question below, but add in the related data for a feature request.

### What are you trying to achieve?

Can have input file name the same as output file name.

### When you searched for similar feature requests, what did you find that might be related?

I could not find a similar feature request.

### What would you expect the API to look like?

The call to write out data would appear the same as always, but now accept the input and output names to be the same.

### What alternatives have you considered?

Alternatively you could save the image under a temporary name, delete the original image, then save under the original name again. 

### What are you trying to achieve?

I would like to read an image, modify it, and then save it with the same name, effectively overwriting the original image file.

### When you searched for similar issues, what did you find that might be related?

I thought my issue may be similar to #3265, but disabling the cache doesn't change anything. For now I've been saving the image under a temporary name, deleting the original image, then saving under the original name again. 

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```js
const sharp = require("sharp");

sharp.cache(false);

sharp("image.jpg")
  .rotate(270)
  .toFile("image.jpg", (err, info) => { console.log(info) });
```
"undefined" is printed to the console and the original file is unmodified

**Comment by lovell** [comment]
This is the expected behaviour as output and input are overlapped and the same file cannot be used for both. If you add some error handling to your sample code you should see a relevant message about this.

```diff
-  .toFile("image.jpg", (err, info) => { console.log(info) });
+  .toFile("image.jpg", (err, info) => { console.log(err, info) });
```

**Comment by zelms** [comment]
Ok sounds good, thank you!

**Comment by zelms** [comment]
For anyone else with a similar issue, here is my solution to it.

```js
const sharp = require("sharp");
const fs = require("fs");

//sharp.cache(false);

const filename = "image.jpg"

async function rotateImage(filename, cb) {
  try {
    sharp(filename)
      .rotate(270)
      .toFile(filename + ".tmp", (err, info) => {
        if(err) { cb(err, null); }

        sharp(filename + ".tmp")
          .toFile(filename, (err, info) => {
            if(err) { cb(err, null); }

            fs.unlink(filename + ".tmp", error => {
              cb(error, info);
            });
          }); 
      });
  } catch (error) {
    cb(error, null);
  }
}

rotateImage(filename, function(err, info) {
  console.log(err);
  console.log(info);
});

```
