### ISSUE TITLE
Sharp Library Fails to Load in Packaged Electron Application on Windows

### ISSUE THREAD

**Issue by dengwoadeng** [lovell/sharp#4233]
## Issue Description

I am using the **sharp** library to handle images in an Electron application. Everything works fine in the development environment. However, when I package the application into a Windows platform **.exe** file using an Electron packaging tool and install and run it, I encounter the following error:

```
Could not load the "sharp" module using the win32-x64 runtime
```
![image](https://github.com/user-attachments/assets/950987b5-61c0-4542-ac70-940abc8d772f)

## Environment Information

- **Electron Version**: 23.3.13
- **Sharp Version**: 0.33.5
- **Node.js Version**: 18.20.3
- **Operating System**: Windows 11
- **Packaging Tool**: electron-builder

## Attempted Solutions

- yarn add sharp --ignore-engines
- electron_builder: asarUnpack: ["\*\*\/node_modules\/sharp\/\*\*\/\*","\*\*\/node_modules\/\@img\/\*\*\/\*"],
- npm install --os=win32 --cpu=x64 sharp

but the problem persists.

## Desired Assistance

- I hope to receive guidance on why the **sharp** library cannot be loaded in the packaged Electron application.
- If there are any known solutions or plans for a fix, please let me know.

## Thanks

Thank you for your help. Looking forward to your response.

**Comment by lovell** [comment]
The error message suggests you're using an unsupported version of Node.js via an unsupported version of Electron.

**Comment by dengwoadeng** [comment]
Thank you for your response. I have confirmed that my development environment and packaging environment and runing environment  are consistent, It's the same computer,and the Node.js version used is 18.20.3.

**Comment by lovell** [comment]
The error message in the screenshot you provided says "Please upgrade Node.js: Found 18.12.1". You need to upgrade to a supported version of Electron.

**Comment by lovell** [comment]
Please provide a minimal repo, ensuring it includes the documented configuration, which allows someone else to reproduce.

https://sharp.pixelplumbing.com/install#electron

**Comment by ArceDaniel** [comment]
I’m experiencing exactly the same issue with the following versions:  
- **Electron Version**: 27.3.11  
- **Sharp Version**: 0.33.5  
- **Node.js Version**: 20.12.0  
- **Operating System**: Windows 11  
- **Packaging Tool**: electron-builder

cc: @lovell @dengwoadeng

**Comment by Xiaoyang-Huang** [comment]
Same here...

Electron Version: 33.2.0
Sharp Version: 0.33.5 (I also tried downgrade version to 0.32.0, doesn't working as well)
Node.js Version: v20.18.0
NPM Version: 10.8.2
Operating System: Windows 10

and I'm prety sure the file is existing:
![image](https://github.com/user-attachments/assets/0e59aea0-0be8-465c-b8fa-b8d84d94bb9a)

**Comment by Xiaoyang-Huang** [comment]
haha. I got it solved, the anwser is this one:
https://github.com/lovell/sharp/blob/hat/docs/install.md#electron-forge

so electron doesn't means electron-forge, I'm just a fresh user for electron.js...it really confuse me...maybe you should update document on https://github.com/lovell/sharp/blob/hat/docs/install.md#electron-forge
@lovell

**Comment by lovell** [comment]
@Xiaoyang-Huang The docs will be updated as part of the next release.
