### ISSUE TITLE
Unable to load sharp module when building Immich v1.117.0 on FreeBSD

### ISSUE THREAD

**Issue by zebrapurring** [lovell/sharp#4235]
## Possible install-time or require-time problem

- [X] I have read and understood all of the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [X] I have searched for known bugs relating to this problem in my choice of package manager.

You must confirm both of these before continuing.

### Are you using the latest version of sharp?

- [X] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest,
please open an issue against that package instead.

### Are you using a supported runtime?

- [X] I am using Node.js with a version that satisfies `^18.17.0 || ^20.3.0 || >=21.0.0`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these,
please upgrade to the latest version
and try again before opening an issue.

### Are you using a supported package manager and installing optional dependencies?

- [ ] I am using npm >= 10.1.0 with `--include=optional`
- [X] I am using yarn >= 3.2.0
- [ ] I am using pnpm >= 7.1.0 with `--no-optional=false`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these, please upgrade to the latest version of your chosen package manager
and ensure you are allowing the installation of optional or multi-platform dependencies before opening an issue.

### What is the complete error message, including the full stack trace?

```
error during build:
Error: Could not load the "sharp" module using the freebsd-x64 runtime
Possible solutions:
- Manually install libvips >= 8.15.3
- Add experimental WebAssembly-based dependencies:
    npm install --cpu=wasm32 sharp
    npm install @img/sharp-wasm32
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/usr/local/share/immich/web/node_modules/sharp/lib/sharp.js:113:9)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/usr/local/share/immich/web/node_modules/sharp/lib/constructor.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
```

Packages `vips` and `pkgconf` are installed in the system, as specified in https://sharp.pixelplumbing.com/install#freebsd:

```
$ pkg-config --modversion vips-cpp
8.15.3
```

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

npm verbose cli /usr/local/bin/node /usr/local/bin/npm
npm info using npm@10.8.3
npm info using node@v20.17.0
npm verbose title npm install sharp
npm verbose argv "install" "--loglevel" "verbose" "--foreground-scripts" "sharp"
npm verbose logfile logs-max:10 dir:/root/.npm/_logs/2024-10-13T22_33_22_840Z-
npm verbose logfile /root/.npm/_logs/2024-10-13T22_33_22_840Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/sharp 24ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-wasm32 98ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-x64 99ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-win32-x64 101ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-arm64 100ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-darwin-x64 103ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-s390x 102ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linuxmusl-x64 103ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-x64 102ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-darwin-arm64 106ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-arm 105ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linuxmusl-arm64 107ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-arm 115ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-win32-ia32 116ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-arm64 112ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-darwin-arm64 111ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-darwin-x64 114ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-s390x 114ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linuxmusl-arm64 112ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linuxmusl-x64 114ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 221ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/color 227ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/semver 232ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@emnapi%2fruntime 9ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color-convert 54ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/color-string 56ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/tslib 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color-name 54ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/color-name 56ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle 53ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 50ms (cache miss)
npm verbose reify failed optional dependency /root/test/node_modules/@img/sharp-win32-x64
npm verbose reify failed optional dependency /root/test/node_modules/@img/sharp-win32-ia32
npm verbose reify failed optional dependency /root/test/node_modules/@img/sharp-wasm32
npm verbose reify failed optional dependency /root/test/node_modules/@emnapi/runtime
npm verbose reify failed optional dependency /root/test/node_modules/tslib
npm verbose reify failed optional dependency /root/test/node_modules/@img/sharp-linuxmusl-x64
npm verbose reify failed optional dependency /root/test/node_modules/@img/sharp-linuxmusl-arm64
npm verbose reify failed optional dependency /root/test/node_modules/@img/sharp-linux-x64
npm verbose reify failed optional dependency /root/test/node_modules/@img/sharp-linux-s390x
npm verbose reify failed optional dependency /root/test/node_modules/@img/sharp-linux-arm64
npm verbose reify failed optional dependency /root/test/node_modules/@img/sharp-linux-arm
npm verbose reify failed optional dependency /root/test/node_modules/@img/sharp-libvips-linuxmusl-x64
npm verbose reify failed optional dependency /root/test/node_modules/@img/sharp-libvips-linuxmusl-arm64
npm verbose reify failed optional dependency /root/test/node_modules/@img/sharp-libvips-linux-x64
npm verbose reify failed optional dependency /root/test/node_modules/@img/sharp-libvips-linux-s390x
npm verbose reify failed optional dependency /root/test/node_modules/@img/sharp-libvips-linux-arm64
npm verbose reify failed optional dependency /root/test/node_modules/@img/sharp-libvips-linux-arm
npm verbose reify failed optional dependency /root/test/node_modules/@img/sharp-libvips-darwin-x64
npm verbose reify failed optional dependency /root/test/node_modules/@img/sharp-libvips-darwin-arm64
npm verbose reify failed optional dependency /root/test/node_modules/@img/sharp-darwin-x64
npm verbose reify failed optional dependency /root/test/node_modules/@img/sharp-darwin-arm64
npm info run sharp@0.33.5 install node_modules/sharp node install/check

> sharp@0.33.5 install
> node install/check

sharp: Detected globally-installed libvips v8.15.3
sharp: Attempting to build from source via node-gyp
sharp: Please add node-addon-api to your dependencies
npm info run sharp@0.33.5 install { code: 0, signal: null }

added 9 packages in 2s

1 package is looking for funding
  run `npm fund` for details
npm verbose cwd /root/test
npm verbose os FreeBSD 13.1-RELEASE-p9
npm verbose node v20.17.0
npm verbose npm  v10.8.3
npm verbose exit 0
npm info ok

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: freebsd
  Binaries:
    Node: 20.17.0 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.8.3 - /usr/local/bin/npm
  npmPackages:
    sharp: ^0.33.5 => 0.33.5
```

**Comment by lovell** [comment]
The salient part of the installation log is:

> sharp: Detected globally-installed libvips v8.15.3
> sharp: Attempting to build from source via node-gyp
> sharp: Please add node-addon-api to your dependencies

You're using a globally-installed libvips so please ensure you've read https://sharp.pixelplumbing.com/install#building-from-source and have the additional dependencies.

**Comment by zebrapurring** [comment]
I was able to solve it by using `npm` instead and running:

```sh
npm install --cpu=wasm32 sharp
```
