### ISSUE TITLE
HEIC support for Windows

### ISSUE THREAD

**Issue by dvwgerritsen** [lovell/sharp#4237]
Hello,

I would like to get HEIC support for Windows. So far I have managed to get a custom libvips build working which is able to convert images from HEIC to JPEG without any issue. There is something however that confuses me regarding the installation guide and I don't understand how to progress from here.

So the installation guide says ``The use of a globally-installed libvips is unsupported on Windows and on macOS when running Node.js under Rosetta.``

Does this mean HEIC support for Windows is not possible? And if it would be, how would you be able to have a sharp instance that depends on libvips with HEIC support?

**Comment by lovell** [comment]
Probably not impossible, but definitely unsupported. I wish you good luck but cannot help if you choose to do so.

**Comment by dvwgerritsen** [comment]
Alright will see how I go further, thanks a lot for your quick reply
