### ISSUE TITLE
Add documentation to github page

### ISSUE THREAD

**Issue by AlijonMurodov** [lovell/sharp#4241]
## Feature request
Please upload sharp documentation to repsitory webpage,
I can't access to webpage (sharp.pixelplumbing.com)

**Comment by lovell** [comment]
All the documentation is in the `/docs` folder of this repo and you can run the site locally via `npm run docs-serve`.

https://github.com/lovell/sharp/blob/1533bf995acda779313fc178d2b9d46791349961/package.json#L106

Are you able to explain more about why you cannot access https://sharp.pixelplumbing.com/ ? Is there an error?

**Comment by AlijonMurodov** [comment]
My browser said website running over http, and this message comes out:
`<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>0AlUWZwAAAAD+gzHfjPpyQ6feoq5oAl9gSVNUMzBFREdFMDQxNgBFZGdl`

**Comment by lovell** [comment]
That looks like a message from Microsoft Azure. The sharp docs are hosted on Google Firebase and fronted by Cloudflare, so I guess this is a (temporary?) problem with your network/connection.

**Comment by AlijonMurodov** [comment]
it's not temporary, but it works fine with vpn. I don't know why I guess there is a server problem with Cloudflare turkey region.
