### ISSUE TITLE
Image cut off after set <failOn: 'none'> to ignore "VipsJpeg: Premature end of input file" error

### ISSUE THREAD

**Issue by natuan62** [lovell/sharp#4244]
First of all. Thank you for great library !

### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

  System:
    OS: macOS 15.0.1
    CPU: (8) arm64 Apple M1
    Memory: 71.58 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.4 - ~/.nvm/versions/node/v18.20.4/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 7.20.0 - ~/.config/yarn/global/node_modules/.bin/npm
    pnpm: 7.9.5 - ~/Library/pnpm/pnpm
  npmPackages:
    sharp: ^0.33.5 => 0.33.5 

### Does this problem relate to file caching?

The default behaviour of libvips is to cache input files, which can lead to `EBUSY` or `EPERM` errors on Windows.
Use [`sharp.cache(false)`](https://sharp.pixelplumbing.com/api-utility#cache) to switch this feature off.

- [x] Adding `sharp.cache(false)` does not fix this problem.

### Does this problem relate to images appearing to have been rotated by 90 degrees?

Images that contain EXIF Orientation metadata are not auto-oriented. By default, EXIF metadata is removed.

- To auto-orient pixel values use the parameter-less [`rotate()`](https://sharp.pixelplumbing.com/api-operation#rotate) operation.
- To retain EXIF Orientation use [`keepExif()`](https://sharp.pixelplumbing.com/api-output#keepexif).

- [x] Using `rotate()` or `keepExif()` does not fix this problem.

### What are the steps to reproduce?

Use sharp resize() with { failOn: 'none' } options.
 
### What is the expected behaviour?

- Sharp can resize image without cut off

### Please provide sample image(s) that help explain this problem

- original.jpeg link 
[original.jpeg.zip](https://github.com/user-attachments/files/17520514/original.jpeg.zip)

```javascript
// use sharpjs lib

const fs = require('fs');
const sharp = require('sharp');

const rawImage = './assets-input/original.jpeg';

const main = async () => {
  try {
    const file = fs.readFileSync(rawImage);

    const result = sharp(file, { failOn: 'none' }).resize(1000, 1000);
    const data = await result.toBuffer();
    fs.writeFileSync('./assets-output/resized.jpeg', data);
    return;
  } catch (error) {
    console.error('error', error);
  }
};

main();

```
And after resize, image was cut off
![image](https://github.com/user-attachments/assets/0b4ff647-c1a7-46d6-8ed7-7bb454148701)

```javascript
// use gm lib

const gm = require('gm').subClass({ imageMagick: '7+' });

gm('./original.jpeg')
  .resize(1000, 1000)
  .write('./resized-by-gm.jpeg', function (err) {
    if (!err) console.log('done');
  });

```
While resize with another lib like gm, image not cut off
![image](https://github.com/user-attachments/assets/f78a3f26-bab8-40f2-ba14-1b7440a80c05)

**Comment by kleisauke** [comment]
Did you see https://github.com/lovell/sharp/issues/3825#issuecomment-2308747731?

**Comment by kleisauke** [comment]
Ah, I see what you mean. Did you see https://sharp.pixelplumbing.com/api-resize#resize? What you describe sounds like `fit: 'inside'`.
```javascript
const sharp = require("sharp");

sharp('assets-input/original.jpeg', { failOn: 'none' })
  .resize(1000, 1000, { fit: 'inside' })
  .toFile('assets-output/resized.jpeg');
```

**Comment by natuan62** [comment]
@kleisauke Thank you!! It works fine
