### ISSUE TITLE
SVG input: "Memory allocation failed : Huge input lookup"

### ISSUE THREAD

**Issue by PPDEMOone** [lovell/sharp#4246]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [ ] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### Does this problem relate to file caching?

The default behaviour of libvips is to cache input files, which can lead to `EBUSY` or `EPERM` errors on Windows.
Use [`sharp.cache(false)`](https://sharp.pixelplumbing.com/api-utility#cache) to switch this feature off.

- [x] Adding `sharp.cache(false)` does not fix this problem.

### Does this problem relate to images appearing to have been rotated by 90 degrees?

Images that contain EXIF Orientation metadata are not auto-oriented. By default, EXIF metadata is removed.

- To auto-orient pixel values use the parameter-less [`rotate()`](https://sharp.pixelplumbing.com/api-operation#rotate) operation.
- To retain EXIF Orientation use [`keepExif()`](https://sharp.pixelplumbing.com/api-output#keepexif).

- [x] Using `rotate()` or `keepExif()` does not fix this problem.

### What are the steps to reproduce?
when use the `toBuffer` method can get this error:

```Uncaught Error Error: Input buffer has corrupt header: glib: XML parse error: fatal error code=2 (1) in (null):4:10000002: Memory allocation failed : Huge input lookup```

### What is the expected behaviour?
Calling this method outputs the buffer correctly.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem
I used two relatively large SVG images for testing. `example.svg` will encounter this error 

Look at this  [https://stackblitz.com/~/github.com/PPDEMOone/sharp-error-snippet?file=index.mjs]()

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/api-constructor

| Param | Type | Default | Description |
| --- | --- | --- | --- |
| [options.unlimited] | <code>boolean</code> | <code>false</code> | Set this to `true` to remove safety features that help prevent memory exhaustion (JPEG, PNG, SVG, HEIF). |

```diff
-  const sharpObject = sharp(inputBuffer);
+  const sharpObject = sharp(inputBuffer, { unlimited: true });
```
