### ISSUE TITLE
0.33.5 => Optimization of PNG rendering results in partially lost color

### ISSUE THREAD

**Issue by JensUweB** [lovell/sharp#4247]
## Possible bug
We're running a Node.js based CMS (Strapi 4) which serves a lot of high quality png renderings (resolution up to 2160p) for a web app. We noticed that on some of our renderings, we partially loose color after they got optimized in size with sharp.

I tested this manually with a small node script and could reproduce this bug, so It has nothing to do with Strapi. Strangely enough this is not a problem with all of our renderings - it seems to mainly occur on images with one of those wall boxes.

The image in question is a rendering from a scene in Unreal Engine - if that matters.

### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead. The problem occurres on our ubuntu servers as well as on my local macOS dev machine.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: macOS 14.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 105.41 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    Watchman: 2024.07.01.00 - /usr/local/bin/watchman
  npmPackages:
    sharp: ^0.33.5 => 0.33.5 

```
### Does this problem relate to file caching?
**No.**

The default behaviour of libvips is to cache input files, which can lead to `EBUSY` or `EPERM` errors on Windows.
Use [`sharp.cache(false)`](https://sharp.pixelplumbing.com/api-utility#cache) to switch this feature off.

- [x] Adding `sharp.cache(false)` does not fix this problem.

### Does this problem relate to images appearing to have been rotated by 90 degrees?
**No.**

Images that contain EXIF Orientation metadata are not auto-oriented. By default, EXIF metadata is removed.

- To auto-orient pixel values use the parameter-less [`rotate()`](https://sharp.pixelplumbing.com/api-operation#rotate) operation.
- To retain EXIF Orientation use [`keepExif()`](https://sharp.pixelplumbing.com/api-output#keepexif).

- [x] Using `rotate()` or `keepExif()` does not fix this problem.

### What are the steps to reproduce?

1. Place the provided example image as well as the reproducible code somewhere on your machine.
2. Run the code with `node sharp-test.js`.
3. Inspect the optimized image and look for the small square on the center left wall box.

### What is the expected behaviour?

The color of the png rendering should not change during quality optimization.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```js
const sharp = require('sharp');
const fs = require('node:fs');

async function run() {
    // Load image as buffer
    const image = fs.readFileSync('./admin-building.png');
    // Optimize image
    const finalImage = await sharp(image).png({ quality: 90}).toBuffer();
    // Write image to disk
    fs.writeFileSync('./optimized_image.png', finalImage);
}

void run();
```

### Please provide sample image(s) that help explain this problem
**Original rendering in 2160p (8,86 MB size) resolution:**
![admin-building](https://github.com/user-attachments/assets/b1d2fda6-38cc-407c-8b77-6bb31af73492)

**Optimized rendering with partially lost color:**
![optimized_image](https://github.com/user-attachments/assets/e0bfaff2-28a8-436b-9a60-06c167928408)

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/api-output#png

| Param | Type | Default | Description |
| --- | --- | --- | --- |
| [options.quality] | <code>number</code> | <code>100</code> | use the lowest number of colours needed to achieve given quality, sets `palette` to `true` |

By setting `quality` you've chosen lossy, palette-based output images. Remove `quality` for lossless output.

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
