### ISSUE TITLE
Fontconfig can't find default config error, even though it works on the command line

### ISSUE THREAD

**Issue by WarrenHullStunts** [lovell/sharp#4249]
### What are you trying to achieve?

Node: 20.14.0 
npm: 10.7.0 with optionals
sharp: 0.33.5

I'm trying to create text based images and composite them with another image within an Express backend. It works on my local device, but on my AWS EC2 instance, when I hit the endpoint, I receive the error:

`Fontconfig error: Cannot load default config file: No such file: (null)`

### When you searched for similar issues, what did you find that might be related?

- I tried changing to recommended force install of sharp 
`npm install --force --cpu=x64 --os=linux --libc=musl sharp` 
- I tried creating my own FONTCONFIG_FILE and FONTCONFIG_PATH
- I tried setting the file permissions on the config files and paths to 644 and 755 respectively, hoping it was a permissions issue
- I tried setting FC_DEBUG=1 and running fc-cache and fc-match to make sure it can find fonts
<img width="700" alt="image" src="https://github.com/user-attachments/assets/f10a3703-879e-4ff8-9042-21ba917dd896">

- I tried creating my own simple font config file and pointing to it

<img width="498" alt="image" src="https://github.com/user-attachments/assets/c0236168-d6e7-45b8-ba91-06cf8b157a90">

- I also tried writing a script that would run on installation of sharp
<img width="731" alt="image" src="https://github.com/user-attachments/assets/c5fad690-797d-4197-938a-525003bf0302">

This last test I did to make it easier to test whether or not it was working, but this ended up giving me a normal metadata result instead of the Fontconfig error that I was expecting.

Here is the copy-able code:
`const sharp = require('sharp');
async function run(){
  const image = await sharp({ text: { text: 'Hello', width: 100, height: 100 } });
  const meta = await image.metadata();
  console.log(meta)
}
run();`

This is the exact same code that I am running inside of the Express app as a test and in my buildspec.yml to test. It works in my buildspec when building the project, but not inside of the app itself when hit from its IP address.

Do you have any idea why it can't find the Fontconfig config file in the Express node process itself and what I can do to fix the problem?

**Comment by lovell** [comment]
It looks like you might be using Alpine Linux. Ensure the OS-provided `fontconfig` package is installed and it should provide everything you need, without the need to set any environment variables.

https://sharp.pixelplumbing.com/install#fonts

**Comment by WarrenHullStunts** [comment]
My understanding of Amazon Linux 2023 is that it's a mix of Fedora and CentOS. I have confirmed that the `fontconfig` package is installed, and I have tried not setting any of the environment variables. Still no change in app.

I had a long list of everything else that I've tried, but I'm now thinking that this is an issue with where the code is being built vs where it's being deployed. Since I am able to run fontconfig reliant scripts during the build process, but not after deployment, I checked to see if the fc-list, fc-match, etc. files existed after deployment. 

<img width="594" alt="image" src="https://github.com/user-attachments/assets/836d1275-a44d-47ef-94ee-c78c791aaa4d">

And they do not. So now I'm going to see if a simple install of `fontconfig` after deployment will solve the issue. I'll report back with more questions or close this thread with a confirmation.

**Comment by WarrenHullStunts** [comment]
So the issue was actually that AWS CodeBuild was building the code in a VM that had `fontconfig` installed, but the server that the build was deployed on did not have it. I'm adding it to the `appspec.yml` file to make sure it's installed on the deployment target, not just the build target.
