### ISSUE TITLE
Animation is lost after Gif to Avif

### ISSUE THREAD

**Issue by conanliuhuan** [lovell/sharp#4250]
When I convert an animated Gif file to an Avif file, the animation is lost , only the first frame of the image is visible

**Comment by lovell** [comment]
Animated AVIF sequences are unsupported by libheif and therefore also libvips and sharp. Please see the upstream discussion at https://github.com/strukturag/libheif/issues/377

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Comment by SupertigerDev** [comment]
https://github.com/strukturag/libheif/issues/377#issuecomment-3398616976

has there been an update to this?

**Comment by pereorga** [comment]
Upstream issue has been closed as fixed.

I tried to convert an image using sharp 0.35.1:

```
await sharp('input.gif', { animated: true }).toFormat('avif') .toFile('output.avif');
```

but I got `heifsave: image too large`.

The input GIF image is not especially big (480x480 px, 46 frames, 2.9 MB).

**Comment by lovell** [comment]
Please see https://github.com/libvips/libvips/issues/3629
