### ISSUE TITLE
Potential update to configuration docs to match Electron Forge ASAR plugin docs

### ISSUE THREAD

**Issue by Ymihere03** [lovell/sharp#4258]
## Question about an existing feature

I recently spent a week solving an issue between sharp and Electron Forge regarding the error `The specified module could not be found: sharp-win32-x64.node`. Would it be possible to update sharp's Forge-specific documentation to match Electron Forge's documentation on ASAR plugin?

### What are you trying to achieve?

The documentation for installing sharp with Electron, https://sharp.pixelplumbing.com/install#electron, is a bit outdated and no longer matches the correct way to use Forge's ASAR plugin with sharp.

Forge's current documentation is located at https://www.electronforge.io/config/plugins/auto-unpack-natives and shows the plugin configuration should be 
```
module.exports = {
  packagerConfig: {
    asar: true // or an object containing your asar options
  },
  plugins: [
    {
      name: '@electron-forge/plugin-auto-unpack-natives',
      config: {}
    }
  ]
};
```

Sharp's asarUnpack external link in the section is also broken.

### When you searched for similar issues, what did you find that might be related?

My proposed doc update came from #4116 which also had a problem regarding Forge's ASAR plugin. This is where I originally found the solution to the problem I was having regarding the win32-x64 environment.

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

I am proposing that the config in https://sharp.pixelplumbing.com/install#electron should use the following example:
```
packagerConfig: {
    asar: {
      unpack: "**/node_modules/{sharp,@img}/**/*"
    }
  },
```

Additionally, the external link in https://sharp.pixelplumbing.com/install#electron should point to https://www.electronforge.io/config/plugins/auto-unpack-natives

For comparison, here is the old config that I think should get replaced:
```
{
  "build": {
    "asar": true,
    "asarUnpack": [
      "**/node_modules/sharp/**/*",
      "**/node_modules/@img/**/*"
    ]
  }
}
```

**Comment by lovell** [comment]
The docs at https://sharp.pixelplumbing.com/install#electron currently relate to electron-builder, whereas electron-forge is, as you say, slightly different. We should provide help for both.

The broken link should probably be updated to https://www.electron.build/app-builder-lib.interface.platformspecificbuildoptions#asarunpack

PR welcome, if you're able, thank you.

**Comment by lovell** [comment]
Thanks again for the PR, the docs will be updated with your additions as part of the next release.

**Comment by elya5** [comment]
Hi
the suggested documentation change does not work for me. When I start a new electron project with electronforge (with webpack), install sharp and add the specified asar config, I still get an exception when running the build: `Error: Could not load the "sharp" module using the linux-x64 runtime
`
When using electronforge with Vite, I don't even get that far. I just get a `Error: Cannot find module 'sharp'
`.

Are there other changes required as well?

**Comment by Fm-s** [comment]
Helo,

I'm having the same issue but when the application is packed, already tried with electron-forge 7.5.0,  and electron builder 24.13.3, tried on Windows and Mac

On webpack.main.config, I tried with and without:
externals: {
    sharp: "commonjs sharp",
},

With electron-forge config:
```
 packagerConfig: {
    asar: {
      unpack: "**/node_modules/sharp/**/*,**/node_modules/@img/**/*,**"
}
```

With electron-build:
```
"build": {
    "asar": true,
    "asarUnpack": [
      "**/node_modules/sharp/**/*",
      "**/node_modules/@img/**/*",
      "**/*.{node,dll}"
    ]
}
```

Both with Typescript, maybe that the problem, I tried with minimal boiler plate of:

electron-build:
https://github.com/chentsulin/electron-react-boilerplate

electron-forge
npm init electron-app@latest my-new-app -- --template=webpack-typescript

always the Error: Could not load the "sharp" module using the darwin-arm64 runtime on Mac and win32x64 on windows

I've attempted to use both Yarn and npm, on electron-forge I used make command and electron-builder I used build to generate the Apps, @elya5 did npm start or yarn start already raised your error?

**Comment by elya5** [comment]
`npm start` worked for me. It's just the packaged application (via `npm run make`) that fails. I used Javascript, so I don't think it's a Typescript issue.

**Comment by Fm-s** [comment]
@elya5 It worked with electron build, on the template when adding sharp to package.json dependencies object on release/app, which adds to webpack.config.base.ts as external: [ 'sharp'], tried doing the same thing on forge, but no success, I'll just replace my old project with electron-build and never look back

**Comment by elya5** [comment]
@Fm-s Glad it worked for you. Which operating system are you using? I've got it to work with electron-vite on Linux but  packaging and running it on Windows fails.

**Comment by Fm-s** [comment]
Worked on both windows and Mac, on windows I had to run yarn package from cmd with admin privileges
