### ISSUE TITLE
Fail to use `libvips/build-win64-mxe` for custom libvips

### ISSUE THREAD

**Issue by Saraiby** [lovell/sharp#4259]
### What are you trying to achieve?

I want to use a custom libvips with *magick on Windows 11. I try to overide the default libvips refer to this comment [#2377](https://github.com/lovell/sharp/issues/2377#issuecomment-696686581). But it can not work.

1. An initial project install sharp with version 0.33.5.
2. Download vips-dev-w64-all-8.15.3 from [build-win64-mxe](https://github.com/libvips/build-win64-mxe/releases/tag/v8.15.3).
3. Put the files from folder `bin` into `node_modules\@img\sharp-win32-x64\lib` or `node_modules\sharp\build\Release`.
4. Test reading image metadata.
5. Failed with messages :
```
D:\MyData\Studio\Development\test\test-sharp\node_modules\sharp\lib\sharp.js:113
  throw new Error(help.join('\n'));
  ^

Error: Could not load the "sharp" module using the win32-x64 runtime
ERR_DLOPEN_FAILED: The specified module could not be found.
\\?\D:\MyData\Studio\Development\test\test-sharp\node_modules\@img\sharp-win32-x64\lib\sharp-win32-x64.node
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=win32 --cpu=x64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (D:\MyData\Studio\Development\test\test-sharp\node_modules\sharp\lib\sharp.js:113:9)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (D:\MyData\Studio\Development\test\test-sharp\node_modules\sharp\lib\constructor.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)

Node.js v20.13.1
```

### When you searched for similar issues, what did you find that might be related?

https://github.com/lovell/sharp/issues/2377#issuecomment-696686581

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```
    let imgPath = path.join(process.cwd(), "file", "3.jpg");
    let origImg = sharp(imgPath);
    console.log(await origImg.metadata());
```

**Comment by lovell** [comment]
https://sharp.pixelplumbing.com/install#custom-libvips

> The use of a globally-installed libvips is unsupported on Windows

Sorry, I cannot help with any questions relating to the use of custom libvips on Windows - it might work, but you're on your own - good luck!

**Comment by Saraiby** [comment]
> https://sharp.pixelplumbing.com/install#custom-libvips
> 
> > The use of a globally-installed libvips is unsupported on Windows
> 
> Sorry, I cannot help with any questions relating to the use of custom libvips on Windows - it might work, but you're on your own - good luck!

OK, thank you all the same.
