### ISSUE TITLE
Unable to get sharp working with heif support in any alpine or debian slim docker

### ISSUE THREAD

**Issue by phazei** [lovell/sharp#4267]
I've installed the packages:

```
RUN apk --update --no-cache add \
>     vips \
>     vips-dev \
>     libheif-dev \
>     libheif-tools \
>     vips-heif
```

But no matter what:
```
# node
Welcome to Node.js v18.20.4.
Type ".help" for more information.
> const sharp = require('sharp');
undefined
> sharp.format.heif
{
  id: 'heif',
  input: { file: true, buffer: true, stream: true, fileSuffix: [ '.avif' ] },
  output: { file: true, buffer: true, stream: true, alias: [ 'avif' ] }
}
```

The documentation to get this support is very thin.  Has anyone got it working?

**Comment by lovell** [comment]
This looks like an installation issue. Please open [a new installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) and provide answers all of the questions if you still require help.

**Comment by phazei** [comment]
Wow, this was such a complete and utter pain.  Not really sharp at fault, but just the whole how picky everything is.  Also, the libvips version required by this library is bumped faster than any repo is ever going to update their version, so the global libvips version will always be behind the `config.version`. In the process I also eventaully got stuck up with the errors they were getting over here as well: https://github.com/lovell/sharp/issues/4204

I'm only venting because I have a solution that will hopefully help someone in the future.  I  created a build container that would package the build so it could be stashed somewhere and used in our deploy container.

```
FROM --platform=linux/amd64 alpine:3.20

# Install build dependencies
RUN apk add --no-cache \
    build-base python3 cmake autoconf automake libtool \
    pkgconfig glib-dev x265-dev x265-dev libjpeg-turbo-dev \
    libde265-dev expat-dev glib-dev \
    meson ninja \
    # Additional deps for libvips
    giflib-dev libexif-dev libjpeg-turbo-dev \
    libpng-dev librsvg-dev libtool \
    orc-dev poppler-dev \
    tiff-dev libwebp-dev

# Setup build environment variables
ENV PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/lib/pkgconfig
ENV LD_LIBRARY_PATH=/usr/local/lib

# Build and output libs
WORKDIR /build

# Build and install libheif with plugins disabled
RUN wget https://github.com/strukturag/libheif/releases/download/v1.17.6/libheif-1.17.6.tar.gz \
    && tar xf libheif-1.17.6.tar.gz \
    && cd libheif-1.17.6 \
    && mkdir build && cd build \
    && cmake .. \
        -DCMAKE_INSTALL_PREFIX=/usr/local \
        -DCMAKE_INSTALL_LIBDIR=/usr/local/lib \
        -DENABLE_PLUGIN_LOADING=NO \
    && make -j$(nproc) && make install \
    && cd ../.. && rm -rf libheif-1.17.6*

# Build and install libvips
RUN wget https://github.com/libvips/libvips/releases/download/v8.15.5/vips-8.15.5.tar.xz \
    && tar xf vips-8.15.5.tar.xz \
    && cd vips-8.15.5 \
    && meson setup build \
        --prefix=/usr/local \
        --libdir=lib \
        -Dmodules=auto \
        -Ddeprecated=false \
        -Dintrospection=disabled \
        -Dorc=disabled \
        -Dhighway=disabled \
        -Dpoppler=disabled \
        -Dpoppler-module=disabled \
    && cd build \
    && meson compile \
    && meson install \
    && cd ../.. && rm -rf vips-8.15.5*

# Create the output directory and copy built files
WORKDIR /output
RUN mkdir -p /output/usr/local && \
    cp -r /usr/local/lib /output/usr/local/ && \
    cp -r /usr/local/include /output/usr/local/ && \
    cp -r /usr/local/bin /output/usr/local/ && \
    # Copy pkg-config files
    mkdir -p /output/usr/local/lib/pkgconfig && \
    cp /usr/local/lib/pkgconfig/*.pc /output/usr/local/lib/pkgconfig/

# Create a tarball of the built files
RUN tar -czf /libs.tar.gz -C /output .
```
That handles all the flags and complication needed for libheif, and libvips.
I run it with this to get the libs.tar.gz out:
```
#!/bin/bash
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BUILT_LIBS_DIR="$(dirname "$SCRIPT_DIR")/built-libs"
mkdir -p "$BUILT_LIBS_DIR"

docker build -f "$SCRIPT_DIR/BuildLibs.dockerfile" -t heif-builder "$SCRIPT_DIR"
docker create --name heif-builder-temp heif-builder
docker cp heif-builder-temp:/libs.tar.gz "$BUILT_LIBS_DIR/"
docker rm heif-builder-temp
docker rmi heif-builder
```

Then in our main Docker we use it like so:

```
FROM --platform=linux/amd64 node:18-alpine

# Env variables
ENV NODE_ENV=development
ENV LD_LIBRARY_PATH=/usr/local/lib
ENV PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

# System dependencies - only runtime libraries
RUN apk --update --no-cache add \
    # For libheif
    libde265 \
    libsharpyuv \
    x265-libs \
    libjpeg-turbo \
    #
    # Install vips package (without binaries) to get all runtime dependencies.
    # This provides ~50 system libraries needed by our custom build.
    # Our custom build will install to /usr/local and take precedence,
    # while utilizing these underlying system dependencies.
    vips

# Copy and extract our pre-built libraries
COPY built-libs/libs.tar.gz /
RUN tar -xzf /libs.tar.gz -C / && rm /libs.tar.gz

# Create app directory
WORKDIR /usr/app

# Force sharp to use our custom libvips
ENV SHARP_IGNORE_GLOBAL_LIBVIPS=0
ENV SHARP_FORCE_GLOBAL_LIBVIPS=1

#rest of your docker file here, this isn't a complete file
```

I only needed heic support to convert videos and images to mp4 and jpg, so I don't know what it supports beyond that.

**Comment by lovell** [comment]
The fault here lays entirely with HEVC patent holders (and their multiple patent pools), which prevent sharp from providing prebuilt binaries containing the codec.

>  I would have thought that the additional fileSuffixes would have been in that list

Yes, I agree that doesn't look right, what is the output of `require("sharp").versions`?

**Comment by phazei** [comment]
```
/usr/app # node
Welcome to Node.js v18.20.5.
Type ".help" for more information.
> require("sharp").versions
{
  aom: '3.9.1',
  archive: '3.7.4',
  cairo: '1.18.0',
  cgif: '0.4.1',
  exif: '0.6.24',
  expat: '2.6.2',
  ffi: '3.4.6',
  fontconfig: '2.15.0',
  freetype: '2.13.2',
  fribidi: '1.0.15',
  glib: '2.81.1',
  harfbuzz: '9.0.0',
  heif: '1.18.2',
  highway: '1.2.0',
  imagequant: '2.4.1',
  lcms: '2.16',
  mozjpeg: '4.1.5',
  pango: '1.54.0',
  pixman: '0.43.4',
  png: '1.6.43',
  'proxy-libintl': '0.4',
  rsvg: '2.58.93',
  spng: '0.7.4',
  tiff: '4.6.0',
  vips: '8.15.3',
  webp: '1.4.0',
  xml: '2.13.3',
  'zlib-ng': '2.2.1',
  sharp: '0.33.5'
}
```

**Comment by lovell** [comment]
@phazei That output is from an installation of sharp using its own prebuilt binaries rather than a globally-installed libvips.

**Comment by phazei** [comment]
Well...  when I did a install of sharp on its own, it wouldn't do a thing with heic files.  After doing this, it did... so I don't know what to say 🤷 

What would the difference be in the versioning?

**Comment by markg85** [comment]
(i can open a new issue but it seems appropriate in this one)

I have exactly that (vips and sharp):
```
Welcome to Node.js v20.8.0.
Type ".help" for more information.
> require("sharp").versions
{
  aom: '3.6.1',
  archive: '3.7.0',
  cairo: '1.17.8',
  cgif: '0.3.2',
  exif: '0.6.24',
  expat: '2.5.0',
  ffi: '3.4.4',
  fontconfig: '2.14.2',
  freetype: '2.13.1',
  fribidi: '1.0.13',
  gdkpixbuf: '2.42.10',
  glib: '2.77.0',
  harfbuzz: '8.0.1',
  heif: '1.16.2',
  imagequant: '2.4.1',
  lcms: '2.15',
  mozjpeg: '4.1.3',
  orc: '0.4.34',
  pango: '1.50.14',
  pixman: '0.42.2',
  png: '1.6.40',
  'proxy-libintl': '0.4',
  rsvg: '2.56.90',
  spng: '0.7.4',
  tiff: '4.5.1',
  vips: '8.14.3',
  webp: '1.3.1',
  xml: '2.11.4',
  'zlib-ng': '2.1.3',
  sharp: '0.32.4'
}
```

`heif-enc` also is proper for an HEIC encoder:
```
❯ heif-enc --list-encoders
HEIC encoders:
- x265 = x265 HEVC encoder (3.6) [default]
AVIF encoders:
- aom = AOMedia Project AV1 Encoder v3.10.0 [default]
- svt = SVT-AV1 encoder v2.2.1-dirty
- rav1e = Rav1e encoder
VVIC encoders:
JPEG encoders:
JPEG 2000 encoders:
HT-J2K encoders:
```

Any conversion of whatever image to heic just doesn't work. I didn't do any manual compile.
The error:
```
[Error: heifsave: Unsupported compression]
```

The code:
```
await sourceImageSharp.resize(resizeOptions).heif({ compression: 'hevc' }).toFile(path.join(IMAGEFOLDER, destinationFile))
```

No clue why this is failing, it's all according to the docs.
Technically this is resizing a jpeg image to a smaller HEIC one.

**Comment by lovell** [comment]
@markg85 Please see https://sharp.pixelplumbing.com/install#building-from-source for prerequisites and ensure you're using the latest version of everything involved. Please open [a new installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) and answer all of the questions if you still require help.

**Comment by starlight-akouri** [comment]
If this was figured out, it'd be great to add a sample Dockerfile that compiles Libvips and sharp from source somewhere in `/examples`

**Comment by Bovojon** [comment]
Still facing this issue for docker file:

heif: Error while loading plugin: No decoding plugin installed for this compression format

My dockerfile part where I install dependencies:

RUN apt-get update && \
    apt-get install -y \
    libvips-dev \
    libheif1 \
    libheif-dev \
    libde265-0 \
    libde265-dev \
    libx265-dev \
    libx265-199 \
    libjpeg-dev \
    libpng-dev \
    libaom-dev \
    libvips-tools \
    libvips42 \
    && ldconfig \
    && rm -rf /var/lib/apt/lists/*


Anyone figured it out?

**Comment by sasankm-adt** [comment]
I encountered the same issue. To resolve it, you can try using the `heic-convert` package, which is another library for converting HEIC images into a format compatible with Sharp.

**Comment by aylabbs** [comment]
@lovell can there be a working dockerfile somewhere in the docs that uses a globally-installed libvips  with a base of node22-alpine or slim (or any LTS) that just works?
This seems to be a fairly common pain point.
You can add `RUN node -e "console.log(require('sharp').versions)"` to prove it is working

**Comment by markg85** [comment]
+1 for a docker image! I've given up on this as it's just too loaded with open for interpretation documentation (or none). I used image magick and ffmpeg instead which do just work. No clue why either libvips or this project are so damn hard to get right. I'm not gonna try anymore on my end.

I was at a point where "it should work" but it didn't and that's where i draw the line. As the next step would be in code debugging and that's a step too far for what i was after back when i made my previous comment here.

Also the whole notion that a heif file is a "[container](https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format)" that can be JFIF, AV1 or HEVC encoded and defaults to AVIF makes the whole format so ludicrously idiotic that i don't want to have anything to do with this format anymore. I would even go as far as thinking that they intentionally fucked up the heif format to promote avif. It's ruined and loaded with easy mistakes that everybody will make at first because it's... just... dumb. I moved on to AVIF (in an avif file, never gonna use heif again). And to make it even more confusing. There is also the HEI**C** format which is HEIF too but with a guaranteed HEVC encoded image in it.  It's _nearly_ easier to create a new container format that is logical then to use HEIF/HEIC.

End of my rant :) I'd still like to be able to use it! My preference shifted to AVIF though.

Side note, this issue should not be closed. Unless you plan to drop HEIF/HEIC entirely.

**Comment by aylabbs** [comment]
Ok, I got it!

Many thanks to  @jenssegers in #4273 

```
FROM node:22-alpine

ENV SHARP_FORCE_GLOBAL_LIBVIPS=1
ENV NODE_PATH=/usr/local/lib/node_modules

RUN apk add --no-cache --update \
    --repository=https://dl-cdn.alpinelinux.org/alpine/edge/main \
    --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community \
    --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing \
    vips \
    vips-dev \
    vips-heif \
    libheif \
    libpng \
    libjpeg-turbo \
    libde265 \
    libwebp \
    g++ \
    make \
    gcc \
    build-base \
    python3 \
    pkgconfig

# Install Sharp globally
RUN npm install -g --no-package-lock node-addon-api node-gyp && \
    npm install -g --no-package-lock --build-from-source sharp && \
    npm cache clean --force

# Optional cleanup
RUN apk del g++ make gcc build-base

COPY image.heic image.heic

RUN node -e "require('sharp')('image.heic').resize(200).toFile('image.jpg')"
```
Confirm working:
- make sure you have an image.heic in the same directory
- build and copy image.jpg back into host

```
docker build -t myimage .
docker create --name temp myimage
docker cp temp:/image.jpg ./image.jpg
docker rm temp
```
easy peasy

**Comment by lovell** [comment]
If someone is willing to *maintain* a working Dockerfile then I'd be happy to link to it in the docs. I really don't want to hear any more rants about the patent-encumbered HEIC format so am going to lock this issue.
