### ISSUE TITLE
Possible JPEG optimisation: apply blur to AB channels of LAB in low entropy regions

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#427]
I'm aware of at least a few people using sharp for image optimisation.

Here's a technique I first saw almost 12(!) years ago that hasn't seen much love recently - http://www.websiteoptimization.com/speed/tweak/blur/

The description is of a manual process, but here's how it can be automated:
1. Convert to LAB colourspace.
2. Find low entropy regions.
3. Reduce the entropy further by applying a mild blur (3x3 kernel, can use SIMD) to the A+B chroma channels.

This should make the frequency-based JPEG algorithm a little more efficient, and could also be used to remove noise.

**Comment by lovell** [comment]
Google's new [Guetzli](https://github.com/google/guetzli) JPEG encoder appears to do something very similar:
https://github.com/google/guetzli/blob/547b45e2899069bb7084bd50daadd93f607d8c5d/guetzli/preprocess_downsample.cc#L238

It also sharpens dark red regions:
https://github.com/google/guetzli/blob/547b45e2899069bb7084bd50daadd93f607d8c5d/guetzli/preprocess_downsample.cc#L220

**Comment by sedubois** [comment]
Guetzli achieves apparently quite impressive compression. Any plans to support it?

**Comment by lovell** [comment]
@sedubois Did you see the comments in the linked-to https://github.com/jcupitt/libvips/issues/623 ?

**Comment by sedubois** [comment]
Thanks, hadn't seen.

**Comment by lovell** [comment]
The JPEG-XL format builds on the Guetzli features mentioned above, plus I believe similar techniques are being used with AVIF, so I think this idea is probably now superseded by their more advanced encoders.
