### ISSUE TITLE
PNG from SVG (composite) String hangs forever, no error, no output

### ISSUE THREAD

**Issue by AlbinoGeek** [lovell/sharp#4270]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i5-10500H CPU @ 2.50GHz
    Memory: 43.09 GB / 63.79 GB
  Binaries:
    Node: 22.11.0 - C:\Program Files\nodejs\node.EXE       
    Yarn: 4.5.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD 
    npm: 10.8.3 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: ^0.33.5 => 0.33.5
```

### Does this problem relate to file caching?

- [x] Adding `sharp.cache(false)` does not fix this problem.

### Does this problem relate to images appearing to have been rotated by 90 degrees?

- [x] Using `rotate()` or `keepExif()` does not fix this problem.

### What are the steps to reproduce?

1) Use `ReactDOMServer.renderToString`, `ReactDOM.render`, `ReactDOMServer.renderToStaticMarkup`, or a literal string with `<svg>...` in it.
2) Attempt to convert the SVG to PNG using various sample codes.

```tsx
  const svg = ReactDOMServer.renderToString(<SvgComponent />)
  console.log('Rendering composite...')
  const png = sharp().resize(24, 24).composite([{
    input:   Buffer.from(svg),
    gravity: 'centre',
  }])
  console.log('Converting to buffer...') // is logged
  const buf = await png.toBuffer() // hangs forever
  console.log('Returning base64...') // never logged
```

You may ask, "why not `sharp(Buffer.from(svg))`?" Well, see my next issue...

### What is the expected behaviour?

PNG output

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

"Without dependencies" is hardly possible in the NPM ecosystem, come on now. However, this can be reproduced in the minimal `create-react-app` as well as the `create-next-app` (this is a NextJS application.)

### Please provide sample image(s) that help explain this problem

Any image from MaterialUI Icons, literally any of them (yes, I looped through the entire namespace to test.) What I want working atm however are `<Facebook />`, `<Instagram />` etc brand logos.

**Comment by AlbinoGeek** [comment]
Related: #4271

**Comment by lovell** [comment]
The parameter-less constructor is used to create a `Writable` stream that the input image can be piped into.

```diff
+ readableStream.pipe(png);
  const buf = await png.toBuffer() // hangs forever
```

**Comment by AlbinoGeek** [comment]
I am confused on how to implement this. `ReadableStream` has no constructors matching this use-case, and `sharp` does not appear to have a `.readableStream()` on its builder either. Where would I get that from?

**Comment by lovell** [comment]
In my example, `readableStream` is an instance of a Node.js [stream.Readable](https://nodejs.org/api/stream.html).

I suspect you may not want to use Stream-based input, in which case you can create a blank image as your input upon which to composite other images.

https://sharp.pixelplumbing.com/api-constructor

```js
sharp({
  create: { ... }
})...
```

**Comment by AlbinoGeek** [comment]
As frustrated as I may be with the whole issue, thank you for being on top of this.

As found in the other issue, SVGs with styles (or from strings apparently) just isn't a feature, moving to manually-transmogrified strings written out to files, it "works" about as well as expected. To be fair, keeping the written/converted images around isn't the end of the world for my use-case.

Thank you for being on top of issues :)
