### ISSUE TITLE
PNG from SVG Buffer fails with "Input buffer has corrupt header: glib: XML parse error"

### ISSUE THREAD

**Issue by AlbinoGeek** [lovell/sharp#4271]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i5-10500H CPU @ 2.50GHz
    Memory: 43.09 GB / 63.79 GB
  Binaries:
    Node: 22.11.0 - C:\Program Files\nodejs\node.EXE       
    Yarn: 4.5.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD 
    npm: 10.8.3 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: ^0.33.5 => 0.33.5
```

### Does this problem relate to file caching?

- [x] Adding `sharp.cache(false)` does not fix this problem.

### Does this problem relate to images appearing to have been rotated by 90 degrees?

- [x] Using `rotate()` or `keepExif()` does not fix this problem.

### What are the steps to reproduce?

1) Use `ReactDOMServer.renderToString`, `ReactDOM.render`, `ReactDOMServer.renderToStaticMarkup`, or a literal string with `<svg>...` in it.
2) Attempt to convert the SVG to PNG using various sample codes.

```tsx
  const svg = ReactDOMServer.renderToString(<SvgComponent />)
  console.log('Rendering composite...')
  const png = sharp(Buffer.from(svg))
    .png()
    .resize(24, 24)
  console.log('Converting to buffer...')
  const buf = await png.toBuffer() // errors here
  console.log('Returning base64...')
```

I've also tried the simpler

```tsx
  const svg = ReactDOMServer.renderToString(<SvgComponent />)
  const buffer = await sharp(Buffer.from(svg))
    .png()
    .toBuffer()
```

Same error.

```
Error: Input buffer has corrupt header: glib: XML parse error: Error domain 1 code 5 on line 1 column 425 of data: Extra content at the end of the document
```

You may ask, "why not `composite`?" Well, see my previous issue.

### What is the expected behaviour?

PNG output

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

"Without dependencies" is hardly possible in the NPM ecosystem, come on now. However, this can be reproduced in the minimal `create-react-app` as well as the `create-next-app` (this is a NextJS application.)

Code directly from my app:

```tsx
import Facebook from '@mui/icons-material/Facebook' // or any other icon
import ReactDOMServer from 'react-dom/server'
import sharp from 'sharp'

const svgToImage = async (SvgComponent: typeof Facebook): Promise<Buffer> => {
  // Also tried all the other render methods, output is valid SVG
  const svg = ReactDOMServer.renderToStaticMarkup(<SvgComponent />)
  return await sharp(Buffer.from(svg))
    .png()
    .toBuffer()
}
```

### Please provide sample image(s) that help explain this problem

Any image from MaterialUI Icons, literally any of them (yes, I looped through the entire namespace to test.) What I want working atm however are `<Facebook />`, `<Instagram />` etc brand logos.

**Comment by lovell** [comment]
> or a literal string with \<svg\>... in it.

Please can you provide an example string that represents a valid SVG that fails in this manner.

**Comment by lovell** [comment]
Thanks, this sample string is not valid XML so that's why you're seeing an "XML parse error" message. As you suggest you'll need to (re)move the `<style>` element as valid SVG must be valid XML, and valid XML must have a single root node.

**Comment by AlbinoGeek** [comment]
Mmmm.... I'm having trouble understanding how both `Resend.js` and NextJS itself manage to display these SVGs, using the `sharp` library no less, while retaining the style. I suppose they have some magic surrounding forcing the styles into the SVG's individual path/rect/etc, if I had to guess?

How would you recommend I approach this issue then, considering that removing the styling destroys the images (in the case of these brand images, they do not render correctly without the styles.)

**Comment by AlbinoGeek** [comment]
Well I suppose if anyone find this later...

The above snipper will get you "close enough", maybe?

The colours are wrong, the images are fuzzy, but hey, it "works"?

Closing as this is apparently just not a feature of `sharp`, which, fair.
