### ISSUE TITLE
Switch from aom to svt-av1-psy

### ISSUE THREAD

**Issue by CutestNekoAqua** [lovell/sharp#4276]
## Feature request

svt-av1-psy is a (potentially) better encoder for AV1 and Avif offering both a huge speed increase over aom and much better perceptual image quality.

We encountered this issue with sharp thanks to one of our contributors @snaakey who is severely autistic when it comes to Avif images. 

Also if this library switches, it could potentially also expose more options for video encoding with avif.

**Comment by CutestNekoAqua** [comment]
PS: thanks for maintaining a awesome library :)
saying this as most people underestimate the work of library devs :tulip:

**Comment by snaakey** [comment]
Just to clarify SVT-AV1-_PSY_ is a soft fork of SVT-AV1 with overall better perceptual quality, some changed defaults and some additional options that are very useful.

**Comment by snaakey** [comment]
I just realised that you are using libvips and not libaom directly

**Comment by snaakey** [comment]
Nontheless exposing all encoder options in this library would be extremely awesome.

**Comment by lovell** [comment]
A future possible switch to an alternative AV1 encoder as part of the prebuilt binaries is being discussed at https://github.com/lovell/sharp-libvips/issues/97 - I've added a note about svt-av1-psy, thanks for the suggestion - let's continue to track it there.
