### ISSUE TITLE
Autorotate not working

### ISSUE THREAD

**Issue by lsrbrrd** [lovell/sharp#4280]
Using rotate() don't work, I need to calculate the angle to rotate it correctly

![rotate6](https://github.com/user-attachments/assets/3ab20759-759c-4c62-8b0a-ead52656a9fb)

let objectBuffer = await GetFile(s3Client, bucket, key);
const orientation = exifData && exifData.Orientation && exifData.Orientation.value ? parseInt(exifData.Orientation.value) : 1;
if (orientation != 1) {
      objectBuffer = await sharp(objectBuffer, { limitInputPixels: 0 })
        .rotate()
        .toBuffer();
        const uploadKeyFixed = `${filePath}[FIXED]-${responseApi.id}.${extension}`;
        await UploadFile(s3Client, bucket, uploadKeyFixed, objectBuffer, extension, 'image');
    }

when I change only the rotate line for .rotate(90) the image was rotate correctly

**Comment by lovell** [comment]
This image is from a Samsung device and contains out-of-order EXIF tags,  please see https://github.com/lovell/sharp/issues/3947
```
$ exiftool -validate -warning -a 389079114-3ab20759-759c-4c62-8b0a-ead52656a9fb.jpg 
Validate                        : 37 Warnings (13 minor)
Warning                         : Entries in IFD0 are out of order
...
```
```
$ exiftool -D 389079114-3ab20759-759c-4c62-8b0a-ead52656a9fb.jpg 
 ...
  259 Compression                     : JPEG (old-style)
  513 Other Image Start               : 864
  514 Other Image Length              : 54674
  271 Make                            : samsung
  274 Orientation                     : Rotate 90 CW
...
