### ISSUE TITLE
Add CI for Node.js 22.x?

### ISSUE THREAD

**Issue by trivikr** [lovell/sharp#4281]
### What are you trying to achieve?

I was looking into the CI setup for `sharp` as part of upgrading Node.js 20.x version in https://github.com/bluesky-social/social-app/issues/6357, and noticed that CI is not run on Node.js 22.x which went LTS on  2024-10-29

### When you searched for similar feature requests, what did you find that might be related?

N/A. There is no issue discussing running CI in Node.js 22.x

### What would you expect the API to look like?

No change in API. It's a request to test sharp in latest LTS of Node.js, i.e. 22.

### What alternatives have you considered?

Waiting for Node.js 18.x support to be dropped, when Node.js 22.x support will likely be added, like it was done in https://github.com/lovell/sharp/commit/ba20b8ada42bf5e4b6f9313b203d6a1b440735b4

### Please provide sample image(s) that help explain this feature

N/A

**Comment by lovell** [comment]
Please see commit https://github.com/lovell/sharp/commit/6480a941815d4ea920e45010ce0172d9bef9f3aa on the "hat" work-in-progress branch for this addition. Node.js 18 support will only be dropped after it reaches end-of-life, which is currently April 2025.

I would fully expect the existing latest version of sharp to work with Node.js 22. From what I can tell, the linked issue(s) relate to a previous version of Alpine Linux that provided a version of musl with an unusual/unexpected semver suffix.
