### ISSUE TITLE
Image transformation with no compression/resizing looses quality

### ISSUE THREAD

**Issue by igorescobar** [lovell/sharp#4286]
### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Linux 6.6 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (10) arm64 unknown
    Memory: 6.33 GB / 7.66 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 22.11.0 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 9.9.3 - /usr/local/bin/npm
  npmPackages:
    sharp: ^0.33.5 => 0.33.5
```

### What are the steps to reproduce?

```js
sharp('./test/images/image.jpeg')
  .jpeg({ quality: 100 })
  .toFile('output.jpeg');
```

### What is the expected behaviour?

I'm trying to understand why the generated image quality is considerably worse even though no image manipulation was made. Is there any way to prevent this?

Original image:
![image](https://github.com/user-attachments/assets/9d7d9449-e0d0-48e6-b0e6-ab4d54f7040f)

Generated image:
![image](https://github.com/user-attachments/assets/fa16089d-4ba5-4793-8014-75ce001a0f11)

**Comment by lovell** [comment]
The input image is a PNG and the requested output image is JPEG, which as a format is always lossy.

**Comment by igorescobar** [comment]
Makes sense!
