### ISSUE TITLE
Colorscale

### ISSUE THREAD

**Issue by StellarCodeOrg** [lovell/sharp#4287]
Dear Lovell, 

What a nice work!

### What are you trying to achieve?

I would like to apply a custom colorscale to an image, i.e. something almost identical to greyscale, but instead of using the standard 256 shades of grey, I would like to use a custom array of 256 color values (hex strings or hex numbers, whichever is the fastest to process). 

Is it possible to achieve this with sharp?

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

Something like
`const scale = ["#000000",...,"#ff0000"]; // 256 custom values`
`// Or const scale = [0x000000,...,0xff0000]; // Any 256-step path within the RGB cube`

And the command (either chained after greyscale or not, whichever is the most convenient / fastest)
`const output = await sharp(input).greyscale().colorscale(scale).toBuffer();`
`const output = await sharp(input).colorscale(scale).toBuffer();`

### Please provide sample image(s) that help explain this question
This would allow to redraw the Mona Lisa with the very nice Viridis (or Magma) colorscale... (a quick Google search to see what I mean)... or generally to do interactive work with scientific images. 

Is it possible to achieve this currently, or, if not yet, to implement the feature?

**Comment by lovell** [comment]
Hello, this sounds like the sort of thing that mapping via a lookup-table would help with. This feature is not currently available, but there is a future possible enhancement relating to this at https://github.com/lovell/sharp/issues/1441

**Comment by StellarCodeOrg** [comment]
Hi. Thanks.

I have zero knowledge in images, but if a greyscale image is basically an array of integers n between 0 and 255, then the new image would be simply obtained by replacing n by table[n] (with 3 channels of course). From the outside, this looks extremely quick and easy to do (much simpler than any crazy convolutions or sophisticated filters). 

Something like
```
function (image, table) {
  return image.map(n => table[n])
}
```
Isn't it not? (Why?)

I'm not familiar with the sharp codebase, but if you tell me where in the code to look at, I could give it a try.

**Comment by lovell** [comment]
The discussion in #1441 went a bit off-topic, but ultimately it's about exposing `vips_maplut` to map input pixel values to output values via a per-channel lookup table (LUT). Providing a 1-channel LUT should probably force the image to greyscale first.

I'm always keen to add features that can help people with colour-blindness (I have a mild form). I've updated the title of #1441 - let's continue to track it there, thanks for opening this issue.

**Comment by StellarCodeOrg** [comment]
Thank you for the explanations. 

Of course, intuitively, the way I saw a possible solution was to copy/paste the greyscale function (whatever that is), add an array as a second argument, and change a few lines in the return statement, which looked very simple. But with a closer look I now understand we need to deal with the libvips library first. 

Understood. 

I will look more closely at the #1441 discussion.
