### ISSUE TITLE
Error: Could not load the "sharp" module using the win32-x64 runtime

### ISSUE THREAD

**Issue by wanghaisheng** [lovell/sharp#4291]
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [ ] Running `npm install sharp` completes without error.
- [ X] Running `node -e "require('sharp')"` completes without error.

If you cannot confirm both of these, please open an [installation issue](https://github.com/lovell/sharp/issues/new?labels=installation&template=installation.md) instead.

### Are you using the latest version of sharp?

- [ X] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.
0.33.5
If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest, please open an issue against that package instead.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```

  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 5.02 GB / 15.37 GB
  Binaries:
    Node: 20.14.0 - D:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - D:\Program Files\nodejs\npm.CMD
    pnpm: 9.3.0 - ~\AppData\Roaming\npm\pnpm.CMD
  npmPackages:
    sharp: ^0.33.5 => 0.33.5 
```
### Does this problem relate to file caching?

The default behaviour of libvips is to cache input files, which can lead to `EBUSY` or `EPERM` errors on Windows.
Use [`sharp.cache(false)`](https://sharp.pixelplumbing.com/api-utility#cache) to switch this feature off.

- [ ] Adding `sharp.cache(false)` does not fix this problem.

### Does this problem relate to images appearing to have been rotated by 90 degrees?

Images that contain EXIF Orientation metadata are not auto-oriented. By default, EXIF metadata is removed.

- To auto-orient pixel values use the parameter-less [`rotate()`](https://sharp.pixelplumbing.com/api-operation#rotate) operation.
- To retain EXIF Orientation use [`keepExif()`](https://sharp.pixelplumbing.com/api-output#keepexif).

- [ ] Using `rotate()` or `keepExif()` does not fix this problem.

### What are the steps to reproduce?

npm i sharp

node -e "require('sharp')"

```
$ node -e "require('sharp')"
D:\Download\audio-visual\100websites\ScrewFast\node_modules\sharp\lib\sharp.js:113
  throw new Error(help.join('\n'));
  ^

Error: Could not load the "sharp" module using the win32-x64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=win32 --cpu=x64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (D:\Download\audio-visual\100websites\ScrewFast\node_modules\sharp\lib\sharp.js:113:9)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (D:\Download\audio-visual\100websites\ScrewFast\node_modules\sharp\lib\constructor.js:10:1)        
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)

Node.js v20.14.0
```
npm ls sharp give me 
```
ScrewFast@0.0.1 D:\Download\audio-visual\100websites\ScrewFast
├─┬ @vite-pwa/assets-generator@0.2.6
│ └── sharp@0.32.6
├─┬ astro-imagetools@0.9.0
│ └─┬ imagetools-core@3.0.2
│   └── sharp@0.29.3
├─┬ astro@4.16.13
│ └── sharp@0.33.5 deduped
├─┬ sharp-ico@0.1.5
│ └── sharp@0.33.5 deduped
└── sharp@0.33.5


```

**Comment by lovell** [comment]
> ├─┬ @vite-pwa/assets-generator@0.2.6
│ └── sharp@0.32.6
├─┬ astro-imagetools@0.9.0
│ └─┬ imagetools-core@3.0.2
│   └── sharp@0.29.3

These dependencies are using old, unsupported versions of sharp. Please search for and/or report this at their respective repos.

https://github.com/vite-pwa/assets-generator/issues
https://github.com/RafidMuhymin/astro-imagetools/issues
