### ISSUE TITLE
Changing exif data question

### ISSUE THREAD

**Issue by ihopciklumer** [lovell/sharp#4295]
Hi, could you please explain how to change ExifImageWidth and ExifImageHeight? I use withMetadata() and Ideally I want to copy all metadata except ExifImageWidth, ExifImageHeight. ImageHeight and ImageWidth copied too and it's not correct when I change orientation. Please help.

**Comment by lovell** [comment]
Please try something like the following:
```js
.withExif({
  IFD0: {
    PixelXDimension: "123",
    PixelYDimension: "456"
  }
})
```

**Comment by ihopciklumer** [comment]
Thanks! It helped!
