### ISSUE TITLE
Problem comparing images: Buffer length of each extract piece

### ISSUE THREAD

**Issue by crisconru** [lovell/sharp#4297]
## Goal: Split an image and get only the non repetitive parts

I am doing a lib / utility which goal is to insert an image, split into pieces and get non repetitive ones.  I made with Jimp while I am migrating to sharp (performance is way better).

I have use this to code:

- Dev enviroment is:
  - OS: Elementary OS 8 x86_64 (derivated from Ubuntu 24.04)
  - Node version: 22.11.0
  -  sharp version: 0.33.5
  - sharp-phash version: 2.2.0
- Image of reference
  - ![chess](https://github.com/user-attachments/assets/2504edb9-cea5-4df2-b182-809e4c298ef2)

### How Jimp compare images?

Jimp has changed its docs but in the past they suggest to use two metrics:

1. [Distance](https://jimp-dev.github.io/jimp/api/jimp/functions/distance/) (%) -> hamming distance of two images based on their perceptual hash
2. [Difference](https://jimp-dev.github.io/jimp/api/jimp/functions/diff/) (%) -> diffs two images

These metrics are between 0-1, so to say images are equal Jimp proposed to do something like this

```typescript
import { Jimp, diff, distance as dist } from 'jimp'

const MAX_DISTANCE = 0.01 // up to you
const MAX_DIFFERENCE = 0.01 // up to you

const areEquals = (image1: Jimp, image2: Jimp): boolean => {
    const distance = dist(image1, image2)
    const difference = diff(image1, image2)
    return (distance < MAX_DISTANCE) && (difference < MAX_DIFFERENCE)
}
```

## Getting Hamming distance with Sharp

In order to get the hamming distance based on perceptual hash I am using the dependency [sharp-phash](https://www.npmjs.com/package/sharp-phash). So to get the distance is something like this

```typescript
import { Sharp } from 'sharp'
import phash from 'sharp-phash'
import dist from 'sharp-phash/distance'

const getDistance = async (image1: Sharp, image2: Sharp): Promise<number> => {
    const [buffer1, buffer2]: [Buffer, Buffer] = await Promise.all([image1.toBuffer(), image2.toBuffer()])
    const [phash1, phash2]: [string, string] = await Promise.all([ buffer1, buffer2])
    // denominator is in order to get as a %
    return dist(phash1, phash2) / Math,max(phash1.length, phash2.length)
}
```

It works perfect... BUT. When I try to compare some similar images like these two images, I get `0` as distance

![test-grid-1](https://github.com/user-attachments/assets/0fe70b5d-5864-43c3-b65b-72e50ccd1172) ![test-grid-9](https://github.com/user-attachments/assets/7eb0a117-564c-434e-aa3d-4172e837dfcf)

## Getting Difference with Sharp

Checking how Jimp calculates the difference, they use the dependency [pixelmatch](https://www.npmjs.com/package/pixelmatch). This dep compare two Buffer and get the number of pixels which differs. So to get the difference is something like this

```typescript
import { Sharp } from 'sharp'
import pixelmatch from 'pixelmatch'

// suppose image1 & image2 have the same size (width & height)
const getDifference = async (image1: Sharp, image2: Sharp): Promise<number> => {
    const [buffer1, buffer2] = await Promise.all([image1.toBuffer(), image2.toBuffer()])
    const { width, height } = await image1.metadata()
    const numDifferentPixels = pixelmatch(buffer1, buffer2, null, width, height)
    return numDifferentPixels / (width * height)
}
```

The problem I'm having here is when I split the hole chess, each part has different Buffer length. Following the example with the hamming distance, the next images have 1268 and 1261 of length in its Buffer respectively

![test-grid-1](https://github.com/user-attachments/assets/0fe70b5d-5864-43c3-b65b-72e50ccd1172)
Buffer.length = 1268

![test-grid-9](https://github.com/user-attachments/assets/7eb0a117-564c-434e-aa3d-4172e837dfcf)
Buffer.length = 1261

pixelmatch cannot compare Buffers of different length.

## Doubts

- How is possible that each part, which has the same size, has different Buffer length?
- When I extract / crop each part (next is the code I use to do it), if I check the metada, each part has the same width and height than the original image (720px x 720px) but when I save as a file, each part is correct (90px x 90px), how could it be?
    ```typescript
    import { Sharp } from 'sharp'
    const getPart = (image: Sharp, x: number, y: number, width: number, height: number): Sharp => (
        image.clone().extract({ left: x, top: y, width, height})
    )
    ````

**Comment by lovell** [comment]
It looks like pixelmatch accepts raw pixel data, whereas it appears you may be passing it compressed PNG image data.

https://sharp.pixelplumbing.com/api-output#raw

```diff
- const [buffer1, buffer2] = await Promise.all([image1.toBuffer(), image2.toBuffer()])
+ const [buffer1, buffer2] = await Promise.all([image1.raw().toBuffer(), image2.raw().toBuffer()])
```

**Comment by crisconru** [comment]
Hi @lovell ,

Yes, the example images are png.

If I try that approach I have the error `Error: Image data size does not match width/height.`. It comes from this [line in pixelmatch](https://github.com/mapbox/pixelmatch/blob/cce03e19070870f724839a30a8443ef345fd9416/index.js#L20).

It looks like the obtained buffer (with `raw().toBuffer()` does not have the length width * height * 4. I don't know why is 4 (probably the channels R-G-B-Aplha?).

I'm a bit lost here. How do you compare images with sharp?

**Comment by crisconru** [comment]
@lovell there is another effect I don't understand. After extract / crop an image, if I take a look of its metada, it has the same width and height of the original image. I apply a `clone()` function before using `extract()` and I do not apply any `resize()` before or after (do I have to?)

**Comment by lovell** [comment]
> I don't know why is multiplied 4 (probably the channels R-G-B-Aplha?).

Yes, try https://sharp.pixelplumbing.com/api-channel#ensurealpha

> If I take a look of its metada, it has the same width and height of the original image.

https://sharp.pixelplumbing.com/api-input

"It does not take into consideration any operations to be applied to the output image, such as resize or rotate."

This statement includes the `extract` operation.

The use of `clone` is typically used for Stream-based input, so probably isn't required.

**Comment by crisconru** [comment]
Now it works, thanks a lot @lovell !!!

This can be a nice feature in sharp -> Compare Images. I leave there as suggestion XD

Thanks again @lovell
