### ISSUE TITLE
How to use the specified node version, v8 version and arch for wasm pre-build

### ISSUE THREAD

**Issue by Howlcn1997** [lovell/sharp#4298]
I am calling sharp in Adobe Effects Extensions (CEP). I currently use the npm install --cpu=wasm32 sharp command to install the wasm version of sharp, but CEP's runtime environment uses node 17.7.2 and v8 version 9.9.115.10. How can I use a specific node version and v8 version to pre-build wasm for use in CEP?

- [x] I have read and understood all of the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have searched for known bugs relating to this problem in my choice of package manager.

You must confirm both of these before continuing.

### Are you using the latest version of sharp?

- [ ] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

I can only use version 0.33.0 of sharp at the moment, because the node version in the CEP runtime is 17.7.2

### Are you using a supported runtime?

- [ ] I am using Node.js with a version that satisfies `^18.17.0 || ^20.3.0 || >=21.0.0`
- [ ] I am using Deno
- [ ] I am using Bun

I can only use version 0.33.0 of sharp at the moment, because the node version in the CEP runtime is 17.7.2

### Are you using a supported package manager and installing optional dependencies?

- [ ] I am using npm >= 10.1.0 with `--include=optional`
- [ ] I am using yarn >= 3.2.0
- [ ] I am using pnpm >= 7.1.0 with `--no-optional=false`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these, please upgrade to the latest version of your chosen package manager
and ensure you are allowing the installation of optional or multi-platform dependencies before opening an issue.

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

  System:
    OS: macOS 15.0.1
    CPU: (8) arm64 Apple M3
    Memory: 102.08 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 17.7.2 - ~/.nvm/versions/node/v17.7.2/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.11.1/bin/yarn
    npm: 8.5.2 - ~/.nvm/versions/node/v17.7.2/bin/npm
    Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
  npmPackages:
    sharp: ^0.33.5 => 0.33.5

**Comment by lovell** [comment]
Node.js 17 reached end of life in June 2022. You'll need to ask Adobe (annual revenue ~US$19 billion) to upgrade.
