### ISSUE TITLE
deploying to vercel can't read input buffer

### ISSUE THREAD

**Issue by surrealroad** [lovell/sharp#4299]
## Question about an existing feature
Hi there I wonder if you can help. When testing locally in dev sharp works as expected but then when on vercel it doesn't seem to be able to read the input buffer correctly.
Almost certainly this is something I'm doing wrong or misunderstanding but maybe someone can help.

### What are you trying to achieve?

Create thumbnails after uploading an image

### When you searched for similar issues, what did you find that might be related?

Searched google, github issues and LLM (got gibberish, naturally)

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this question

```
const response = await fetch(imageUrl);
if (!response.ok) {
	return json({ error: 'Failed to fetch image URL' }, { status: 400 });
}
const arrayBuffer = await response.arrayBuffer();
inputBuffer = Buffer.from(arrayBuffer);
const outputBuffer = await sharp(inputBuffer)
.resize(width, height, {
	fit: 'contain',
	withoutEnlargement: true
})
.webp({ quality:80 })
.toBuffer();
```
Works fine locally, but in prod on vercel I get this error:
`Error: Unsupported input '����JFIF…`

### Please provide sample image(s) that help explain this question
Happens with any image

**Comment by lovell** [comment]
My best guess would be that something is monkey-patching or polyfilling `Buffer` at runtime in a non-standard way.

You can pass an `ArrayBuffer` straight to sharp, so perhaps try that directly:
```diff
  const arrayBuffer = await response.arrayBuffer();
- inputBuffer = Buffer.from(arrayBuffer);
- const outputBuffer = await sharp(inputBuffer)
+ const outputBuffer = await sharp(arrayBuffer)
```

**Comment by surrealroad** [comment]
that did it! thanks so much 😄
