### ISSUE TITLE
Unable to install on Windows (appveyor cloud CI)

### ISSUE THREAD

**Issue by tawashley** [lovell/sharp#430]
I've been having issues getting a green build using sharp on appveyor.

The output error states `ERROR: Intel Architecture 32-bit systems require manual installation - please see http://sharp.dimens.io/en/stable/install/`, however going to this page mentions additional Windows installation steps are not required. The documentation mentions x64 compatibility only, however this build has previously been working up to mid April before being unable to install.

I wonder if you could advise if this coincides with a release or change to the code?

* Appveyor project, with the build history (https://ci.appveyor.com/project/tawashley/cartridge-images)
* The output from the most recent failed build can be found:
https://ci.appveyor.com/project/tawashley/cartridge-images/build/job/ftriuqsvv4rie9yu

Thanks

Tris

**Comment by lovell** [comment]
Hello, the log says "Installing node 0.12.13 (x86)..." which suggests Appveyor is installing and running a 32-bit `node.exe`.

If you didn't see it, https://github.com/lovell/sharp/blob/master/appveyor.yml contains a couple of `x64` references to ensure Appveyor exhibits 64-bit behaviour. Perhaps add one at the end of https://github.com/cartridge/cartridge-images/blob/develop/appveyor.yml#L8

**Comment by tawashley** [comment]
@lovell I didn't notice that no, should have looked first. I've now added this and with it green builds across the board. 

Thanks for your help!
