### ISSUE TITLE
Transparency problem while overlay with SVG

### ISSUE THREAD

**Issue by gpstmp** [lovell/sharp#431]
I'm trying to overlay JPEG image with an SVG. Both images have the same size.
Everything is ok when i show preview in the browser (this fact makes me think that SVG is transparent).
Here is [the plunker with preview](https://plnkr.co/edit/5tfvMGfOqb43rFRUeAHT?p=preview)
But this is not working on the server when i try to merge these two images.
Here is the code (images are the same as in plunker, i'm using node v4.2.3 and sharp v0.14.1):

    const sharp = require('sharp');
    sharp('autumn-beauty.jpg')
      .overlayWith('test.svg')
      .toFile('output.png');

SVG image overlaps JPEG completely (seems like SVG is not transparent).

Is it correct behaviour? Or maybe i'm wrong with my attempts.

Thanks for the nice lib!

**Comment by lovell** [comment]
Hello, are you able to try with the latest code in the `master` branch? The next release v0.15.0 will contain many improvements to the handling of SVG files.

```sh
npm install lovell/sharp
```

**Comment by gpstmp** [comment]
@lovell thanks for response!
I have tried the latest code and it worked as expected!
The only problem now for me is installation on Centos (with Docker). I have this error stack:

    > sharp@0.15.0 install /var/betterview/images/node_modules/sharp
    > node-gyp rebuild
    
    gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
    gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
    ERROR: glibc version 2.12 requires manual installation - please see http://sharp.dimens.io/en/stable/install/
    gyp: Call to 'LDD_VERSION="ldd (GNU libc) 2.12
    Copyright (C) 2010 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    Written by Roland McGrath and Ulrich Drepper." node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
    gyp ERR! configure error 
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Linux 3.13.0-24-generic
    gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /var/betterview/images/node_modules/sharp
    gyp ERR! node -v v4.2.3
    gyp ERR! node-gyp -v v3.3.0
    gyp ERR! not ok 
    npm ERR! Linux 3.13.0-24-generic
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
    npm ERR! node v4.2.3
    npm ERR! npm  v3.7.4
    npm ERR! code ELIFECYCLE

**Comment by lovell** [comment]
Centos 6 requires a manual installation of the libvips dependency.

> "ERROR: glibc version 2.12 requires manual installation - please see http://sharp.dimens.io/en/stable/install/"

Centos 7, if you're able to use it, automagically works :)

**Comment by gpstmp** [comment]
Thanks again!
The issue is solved completely.
`npm install lovell/sharp` on top of sharp v0.14.1 did not work for me but installing everything from scratch solved the problem.
When to expect a new release of this super lib?

**Comment by lovell** [comment]
> "When to expect a new release of this super lib?"

Thanks. I need to run the memory leak tests against all the recent code and dependency changes, then update the performance benchmarks as there should be a slight improvement, then we're ready to go.

**Comment by lovell** [comment]
v0.15.0 out now.
