### ISSUE TITLE
Does sharp(my_buffer) get cached?

### ISSUE THREAD

**Issue by jedateach** [lovell/sharp#436]
I had an issue with memory filling up with multiple `extract()` calls on the same, reasonably large image.

When I switched from `sharp(my_buffer)` to `sharp(my_image_path)`, memory use dropped, and my code runs much faster.

I'm running sharp 0.11.4, OSX el capitan.

**Comment by lovell** [comment]
Hi Jeremy, the libvips' docs provide a [brief overview](http://www.vips.ecs.soton.ac.uk/index.php?title=How_it_works#Operation_cache) about its operation cache. IIRC "the same arguments" means the same memory location for an input buffer. If you're using the same Buffer object then the memory location of the backing data should remain consistent.

If you turn caching off, via `sharp.cache(false)`, does the performance between the two input methods "equalise"?

**Comment by jedateach** [comment]
Hi Lovell, I didn't get any performance "eqaualise" change with `sharp.cache(false)`, but I did with `sharp.cache(0, 1)` ...perhaps even slower than the buffer approach.
...which I assume is the correct way of adjusting the cache on the sharp version I'm using?

**Comment by lovell** [comment]
Thanks for confirming that turning the libvips cache off means you're seeing an "equal" performance. Sorry I forgot the API for `cache` changed more recently. 

Are you able to try with a more recent version of sharp? What you need is commit https://github.com/lovell/sharp/commit/ede2ee9ce3656ff224c187efdfdd3aacdfc4e3bc to ensure the memory location of the Buffer remains the same between invocations.

**Comment by lovell** [comment]
@jedateach Were you able to try a more recent version?

**Comment by jedateach** [comment]
Not yet sorry, I'm presently side-tracked with another feature.

**Comment by lovell** [comment]
Closing this for now - feel free to re-open if the problem, ahem, persists, with the latest version.

**Comment by jedateach** [comment]
No worries. Will reply if necessary when I get around to upgrading sharp. Cheers.
