### ISSUE TITLE
Add an alpha channel before extending with a transparent background

### ISSUE THREAD

**Issue by frulo** [lovell/sharp#437]
I'm trying to extend an image with a transparent background. But sharp extend the image with a black background. What is my mistake?

```
sharp( 'test.jpg' )
    .background( 0, 0, 0, 0 )
    .toFormat( sharp.format.png )
    .extend( {top: 0, bottom: 256, left: 0, right: 256} )
    .toFile( 'test.png' )
```

kind regards,

Orlando

**Comment by lovell** [comment]
Hello, please can you try `.background({r: 0, g: 0, b: 0, a: 0})` - see http://sharp.dimens.io/en/stable/api/#backgroundrgba

**Comment by frulo** [comment]
Hello, 
thanks for the fast response. I tried it with .background({r: 0, g: 0, b: 0, a: 0}) and have the same problem. If the  source image have already an Alpha value, than I can extend with a transparent  background. But with a jpeg as source I have this problem...

**Comment by lovell** [comment]
Sorry, yes you're quite correct, `extend` doesn't currently add an alpha transparency channel.

It should be easy to add this feature, thank you for highlighting this.

**Comment by frulo** [comment]
I have create a pull request therefore #439

**Comment by lovell** [comment]
Thanks for the fix, this will be in v0.15.1.

**Comment by lovell** [comment]
v0.15.1 now available, thanks again.

**Comment by perekrestov-igor** [comment]
Looks like issue described above is still actual for webp format
