### ISSUE TITLE
Enhancement Suggestion: Adding tile/replicate option to overlays/watermarks

### ISSUE THREAD

**Issue by lemnisk8** [lovell/sharp#438]
Needed  an option to tile/replicate the overlay image ( watermark ) across the image so it fills up the whole of the image. 
I've made a few minor changes to the library enabling such behaviour.

API Usage: 
`sharp('input.png') 
.overlayWith('overlay.png', { tile: true} )`

Need some feedback regarding it. 
This is my first time working with modules. It would be great if someone could could help / suggest the test for this.

@lovell should I submit a PR, so others can check it out / further work on it...

Thanks & Regards
Chintan

**Comment by lovell** [comment]
Great idea - I'd be happy to accept PR for this - thank you for offering.

I'd suggest creating a new function in `operations.cc` that uses a combination of `vips_replicate` and `vips_extract` to build a tiled image of the same dimensions as the image to be overlaid.

**Comment by lovell** [comment]
Added via #443, thank you.

**Comment by lovell** [comment]
v0.15.1 now available, thanks again.
