### ISSUE TITLE
VipsKernel was not declared in this scope

### ISSUE THREAD

**Issue by binarykitchen** [lovell/sharp#441]
```
../src/pipeline.cc: In member function ‘virtual void PipelineWorker::Execute()’:
../src/pipeline.cc:479:11: error: ‘VipsKernel’ was not declared in this scope
           VipsKernel kernel = static_cast<VipsKernel>(
```

Seeing this when rebuilding with your latest version v15 :( @lovell

**Comment by binarykitchen** [comment]
Btw, I have removed all traces of libvips mentioned in #401 and `echo $PKG_CONFIG_PATH` is empty, outputs nothing. Think these conditions are OK.

**Comment by binarykitchen** [comment]
Also, using node v6.2 here

**Comment by lovell** [comment]
`VipsKernel` was introduced in libvips v8.3.0 so it looks like you're attempting to compile against a version prior to that. Are you able to try on a clean machine/VM?

**Comment by binarykitchen** [comment]
@lovell i thought sharp automatically installs libvips, so i am supposed not to worry about libvips versions? on my machine, i have removed every trace of libvips, yet, i can't install sharp nor build it.

**Comment by binarykitchen** [comment]
http://sharp.dimens.io/en/stable/install/ says

"libvips and its dependencies are fetched and stored within node_modules/sharp/lib during npm install. This involves an automated HTTPS download of approximately 6.7MB."

**Comment by lovell** [comment]
What does `pkg-config --modversion vips-cpp` say?

**Comment by binarykitchen** [comment]
```
$ pkg-config --modversion vips-cpp                                                                                                                                                                                                    
Package vips-cpp was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips-cpp.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips-cpp' found
```

**Comment by binarykitchen** [comment]
@lovell if that's wrong, why didn't sharp's installation script warn me about this?

**Comment by lovell** [comment]
If a global version of libvips is available (via pkg-config) and is of a recent-enough version, then sharp will use it - see https://github.com/lovell/sharp/blob/master/binding.gyp#L67-L68 - otherwise it will download a pre-compiled binary of its own.

Are you able to try on a clean machine/VM?

**Comment by binarykitchen** [comment]
well, i dont have it installed via pkg-config. which means the download and installation of the precompiled binary failed somehow.

btw, this only happens on my remote ubuntu 15 server, not on my local machine.

**Comment by binarykitchen** [comment]
For now, I had to manually run `curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | sudo bash -` to fix this ...

**Comment by lovell** [comment]
Closing this as it appears to have been local to one machine.
