### ISSUE TITLE
Provide a "cookbook" of common image processing recipes

### ISSUE THREAD

**Issue by kennetpostigo** [lovell/sharp#444]
I found this library after googling for ten minutes, I'm wondering if this resizes images and also compresses them. Does it do both? If not do you have any recommendations for libraries that do compression for images well?

**Comment by lovell** [comment]
Hello, what do you mean by "compresses"? This module can output a number of compressed formats such as JPEG, PNG etc. but I suspect you might mean more than that.

**Comment by kennetpostigo** [comment]
"compress" as in the file size of a 3mb image to a smaller size like 100kb. Sorry for the confusion.

**Comment by lovell** [comment]
If you're referring to image optimisation, then there are few features available to you.

http://sharp.dimens.io/en/stable/#optimal

JPEG: http://sharp.dimens.io/en/stable/api/#qualityquality
PNG: http://sharp.dimens.io/en/stable/api/#compressionlevelcompressionlevel and http://sharp.dimens.io/en/stable/api/#withoutadaptivefiltering

**Comment by kennetpostigo** [comment]
Thank you @lovell, going through the docs, is there an examples section?

**Comment by lovell** [comment]
There are a few examples in the API docs, but not a specific examples section, so we should add one!

Any thoughts on what other topics people might to have examples for, beyond image optimisation?

**Comment by kennetpostigo** [comment]
You would probably want examples for most of the API surface. Examples folder in the directory would help alot, allows people to clone the repo and run examples live to play with the library.

**Comment by lovell** [comment]
[HyperDev](https://hyperdev.com/about/) supports native modules so would make an excellent host for "living" code examples.

![](https://pbs.twimg.com/media/Cj4cDdbWkAADVrv.jpg)

**Comment by lovell** [comment]
I've created a "[cookbook](https://github.com/lovell/sharp/issues?utf8=%E2%9C%93&q=label%3Acookbook%20)" label to tag possible "recipes".

**Comment by vsc-github** [comment]
@lovell Hey, I am unable to find quality/compressionLevel articles in the API docs. The links you've posted above aren't pointing to them anymore. Are they taken out of sharp or am I missing something here? Could you please help me find those, I'm looking to adjust the quality of images to reduce their size. Thanks!

**Comment by lovell** [comment]
@vsc-github I've updated my comment.
