### ISSUE TITLE
Disable warnings

### ISSUE THREAD

**Issue by strarsis** [lovell/sharp#445]
When using sharp in nodejs, warning messages can be emitted for some input files - 
how can these warning messages be suppressed in case they aren't relevant to the end user?

Example warning messages:
````
[...]
vips warning: TIFFReadDirectory: Unknown field with tag 37724 (0x935c) encountered
vips warning: TIFFFetchNormalTag: Incompatible type for "RichTIFFIPTC"; tag ignored
vips warning: TIFFReadDirectory: Unknown field with tag 37724 (0x935c) encountered
vips warning: TIFFFetchNormalTag: Incompatible type for "RichTIFFIPTC"; tag ignored
[...]
````

**Comment by lovell** [comment]
Hello, the [VIPS_WARNING](https://github.com/lovell/sharp/blob/master/package.json#L30) environment variable is your friend here.

**Comment by strarsis** [comment]
So an environment variable makes more sense than an option?
Is this because it is actually related to the underlying VIPS library, 
that may also be used by other programs - hence a global switch?

**Comment by lovell** [comment]
> "Is this because it is actually related to the underlying VIPS library"

Yes, it's a libvips-defined variable - see https://github.com/jcupitt/libvips/blob/master/libvips/iofuncs/error.c#L476-L477
