### ISSUE TITLE
Library not loaded: /usr/local/opt/orc/lib/liborc-0.4.0.dylib

### ISSUE THREAD

**Issue by zilions** [lovell/sharp#453]
Unable to run the module due to an error of `Library not loaded: /usr/local/opt/orc/lib/liborc-0.4.0.dylib`.

I used `brew install homebrew/science/vips` to install all dependancies. Everything was installed correctly (after around 10 minutes), yet the module still fails to run.

Any idea on how to fix this?

**Comment by lovell** [comment]
Hello, this looks like #323. Please can you try:
```sh
brew update && brew upgrade
brew unlink orc && brew link orc
```

**Comment by zilions** [comment]
That did the trick! Thanks @lovell

**Comment by Tiendq** [comment]
@lovell I got the same error yesterday on my OSX and your trick worked, thanks :)

Error ==========================

1): Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /usr/local/opt/vips/lib/libvips-cpp.42.dylib
  Reason: Incompatible library version: libvips-cpp.42.dylib requires version 40.0.0 or later, but libpng16.16.dylib provides version 38.0.0
