### ISSUE TITLE
Resulting image is larger than source image with no operations

### ISSUE THREAD

**Issue by adityapatadia** [lovell/sharp#454]
I have tested this on following image which has size 13.3 kb.

https://www.google.co.in/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png

If I pass this image through sharp without any operations, the size becomes 30.3 kb. Why there is increase in size?

**Comment by lovell** [comment]
Hello, that logo will probably have been `pngcrush`ed to death. Take a look at #333, specifically the `compressionLevel(9)` and `withoutAdaptiveFiltering()` suggestions.
