### ISSUE TITLE
Featurerequest: dithering

### ISSUE THREAD

**Issue by neophob** [lovell/sharp#455]
Hi

I would like to support a color conversion function (like dithering) to improve display quality for a 16bpp display when the source image is 32bpp).

I wrote a simple Jimp function which looks like this:

```
Jimp.prototype.dither565 = function (cb) {
    var rgb565_matrix = [
      1, 9, 3, 11,
      13, 5, 15, 7,
      4, 12, 2, 10,
      16, 8, 14, 6
    ];

    for (var _y = 0; _y < this.bitmap.height; _y++) {
      var idx = this.bitmap.width * _y;
      for (var _x = 0; _x < this.bitmap.width; _x++) {
        const tmp = (idx + _x) << 2;
        const tresshold_id = ((y & 3) << 2) + (x % 4);
        const dither = rgb565_matrix[tresshold_id];
        this.bitmap.data[tmp  ] = Math.min(this.bitmap.data[tmp]   + dither, 0xff);
        this.bitmap.data[tmp+1] = Math.min(this.bitmap.data[tmp+1] + dither, 0xff);
        this.bitmap.data[tmp+2] = Math.min(this.bitmap.data[tmp+2] + dither, 0xff);
      }
    }

    if (isNodePattern(cb)) return cb.call(this, null, this);
    else return this;
}
```

**Comment by lovell** [comment]
I wonder if this is an operation that might better be suited to live in libvips itself. /cc @jcupitt

**Comment by neophob** [comment]
I think this would make sense. Currently I convert the image to raw(), do the dithering then encode it as image. So performance wise it's a no brainer. Maybe a custom dither LUT might be an option to make the dither function more general.

**Comment by jcupitt** [comment]
Oh, interesting, I didn't think dithering was very useful any more. Isn't almost everything 24+ bits now? 

Are you adding the dither to all images, or is there an easy way to detect a 16bpp display?

**Comment by neophob** [comment]
Well unfortunately not ;) I use it for a specific display which has only 16bpp. I encode the image on a ARM machine, apply dithering, send it to the device (technically still as 24bpp image) and on the display device the image the converted on the fly.

Currently resizing the image takes about 400ms, my js dithering code takes about 800ms.

**Comment by jcupitt** [comment]
Ah, some sort of picture frame, or static display? That makes sense. 

Yes, it'd be simple to add to vips, though very specialized. libvips supports plugins, maybe it would be better as a plugin rather than in the core library? You'd still need to modify sharp to expose it. Do you need it from node?

**Comment by neophob** [comment]
Yes I use it from node. A plugin should work - however I think the setup process would a bit more complicated - @lovell are plugins supported when doing an `npm install`?

**Comment by jcupitt** [comment]
There's a plugin here you could copy the boilerplate from:

https://github.com/jcupitt/vips-gmic

It's a bit complicated, I'll make a simpler example.

**Comment by jcupitt** [comment]
Here's your dither as a vips plugin:

https://github.com/jcupitt/vips-dither

Install and run like this:

```
john@kiwi:~/GIT/vips-dither (master)$ make release
cc -shared -fPIC  -O3 `pkg-config vips --cflags`  -c -o dither.o dither.c
cc -o vips-dither.plg -shared dither.o 
john@kiwi:~/GIT/vips-dither (master)$ make install
mkdir -p /home/john/vips/lib/vips-plugins-8.4
cp vips-dither.plg /home/john/vips/lib/vips-plugins-8.4
john@kiwi:~/GIT/vips-dither (master)$ vips dither
4x4 ordered dither
usage:
   dither in out
where:
   in           - Input image, input VipsImage
   out          - Output image, output VipsImage
operation flags: sequential 
john@kiwi:~/GIT/vips-dither (master)$ time vips dither ~/pics/k2.jpg x.jpg

real	0m0.062s
user	0m0.096s
sys	0m0.008s
```

**Comment by neophob** [comment]
Phew thanks @jcupitt for that! Very cool, I'll try to integrate it

**Comment by lovell** [comment]
@neophob There's currently no support in sharp for libvips plugins - that probably belongs with #241 - will using the command line for the final dither operation be acceptable for now?

**Comment by neophob** [comment]
thanks @lovell - well unfortunately thats a no go for my use case, as I want to resize multiple images on a low end ARM machine. So using the cli would waste too much resources.

As this issue drifts away from "I need a dither function" to "support libvips plugin" - should I open a new issue or add it to #241?

**Comment by lovell** [comment]
@neophob I've found the `vips` command line tool to be highly memory efficient, at least on a first gen 256MB ARMv6 Raspberry Pi.

Let's add this to #241, although we'd need to think about how plugins are included in the pre-compiled binaries and how best to use libvips plugins that use the C API from the C++ API.

**Comment by jcupitt** [comment]
I tried a 1920x1080 RGB on my raspberry pi2, I see:

```
$ time vips invert x.v x2.v
user 0.308
``` 

I don't know if that's fast enough. That's with the ancient libvips which comes with raspbian, a more modern one might be a bit quicker.

**Comment by neophob** [comment]
Sorry that my explanation was vague - I do have my image data in memory, if I would try to use the CLI I need to save the file to (ram)disc, executer the external program from node, check rc, read the new image file etc.
