### ISSUE TITLE
overlayWith coordinates

### ISSUE THREAD

**Issue by strarsis** [lovell/sharp#457]
It would be great if sharp allows to specify the exact coordinates of an image to overlay with, 
currently only the edges can be selected (gravity option).
I actually want to individually composite multiple images on a sharp "artboard".

**Comment by lovell** [comment]
Hello, this sounds like a sensible addition - are you thinking an API that looks something like `overlayWith(image, { x: Number, y: Number })`?

If you've not already seen it, https://github.com/lovell/sharp/issues/405#issuecomment-208033263 provides an example of how you might composite multiple images.

**Comment by strarsis** [comment]
Yes, x + y coordinates should be already sufficient 
because any other operation (resize, crop, ...) can be performed by the other sharp API methods.
[node-blend](https://github.com/mapbox/node-blend) somehow resembles this (although with an external mapnik dependency), similar to jpegjoin.

**Comment by webbrandon** [comment]
This can be achieved with SVG also (See #450).  The example I left there is a dumbed down version but with that I gave myself positioning, scaling, and even repeating (is a sharp native option now) abilities.

**Comment by rnanwani** [comment]
+1 for `overlayWith(image, { x: Number, y: Number })`
IMO, for the values of x and y, if the values are positive then the would start from the left and top edge respectively. If x and y are negative then the position would start from the right and bottom edge respectively. Any thoughts?

If this is not being implemented then I can take this up.

**Comment by lovell** [comment]
Maybe `overlayWith(image, { top: Number, left: Number })` would be more explicit (and keep it simpler to implement, e.g. reject negative values)?

**Comment by strarsis** [comment]
And it could make sense renaming the method to something like 'insertImageAt(...)', 
because the original/current overlayWith(...) is rather thought to lay things over?

**Comment by lovell** [comment]
@strarsis The images will be composited to respect alpha channels so I think `overlayWith` remains a valid name.

**Comment by rnanwani** [comment]
Also the current tile option in overlayWith #443 is built on gravity option. I don't think it is much of a use case to have tiling areas be calculated with x,y offset values so I will be skipping that part. So now if I make the changes in overlayWith method following cases will be encountered

- if top,left and gravity are all present -> top,left offset is preferred for positioning
- if tiling is present and top,left are present - then tiling goes on with default gravity center and composition is done using top,left values
- both top and left should be present for positioning

**Comment by lovell** [comment]
@rnanwani How about we fail-fast in the JS code (by throwing an Error) if unsupported combinations are provided?

**Comment by rnanwani** [comment]
Created new pull request https://github.com/lovell/sharp/pull/473
Please check if it looks fine. Added test cases as well.
Had to refactor some C++ code to avoid code duplication with gravity method. Haven't written C++ in a while so please review those specially.

**Comment by lovell** [comment]
v0.15.1 now available, thanks @rnanwani

**Comment by Dylan-G** [comment]
It will be nice to have a bottom right too
