### ISSUE TITLE
https://dl.bintray.com/lovell/sharp/libvips-8.1.1-lin.tar.gz not found

### ISSUE THREAD

**Issue by joelmukuthu** [lovell/sharp#459]
When installing sharp 0.12.0 it tries to download the above file which doesn't exist. This might be an older version of sharp but I can see this easily causing some broken builds out there :)

**Comment by lovell** [comment]
Hi Joel, please see #424 - it's a broken builds vs compromised machines thing :(

**Comment by joelmukuthu** [comment]
Oh, I understand. I think taking it down was the right thing to do. Sorry for not having done proper homework on this, I think this issue can be closed since there are others keeping track of the issue.
