### ISSUE TITLE
Can't install with npm install sharp

### ISSUE THREAD

**Issue by eonezhang** [lovell/sharp#46]
> sharp@0.4.2 install /private/tmp/node_modules/sharp
> node-gyp rebuild

/bin/sh: pkg-config: command not found
gyp: Call to 'PKG_CONFIG_PATH="/usr/local/Library/ENV/pkgconfig/10.8:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --libs vips' returned exit status 127.
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/src/node-v0.10.26-darwin-x64/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:337:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Darwin 13.2.0
gyp ERR! command "node" "/usr/local/src/node-v0.10.26-darwin-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/tmp/node_modules/sharp
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! sharp@0.4.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.4.2 install script.
npm ERR! This is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.2.0
npm ERR! command "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "install" "sharp"
npm ERR! cwd /private/tmp
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /private/tmp/npm-debug.log
npm ERR! not ok code 0

**Comment by Cedric12114** [comment]
Hi @lovell 
Trying to install sharp dependency in package.json
'npm install node-gyp --s'
'npm install sharp --s'
I get no errors. Node-gyp appears in the dependency but sharp is nowhere to be found. 
What am I missing?

**Comment by lovell** [comment]
@Cedric12114 Is your use of the `--s` flag intentional? It means `npm` will be "silent" and suppress errors. Perhaps try without and see what is says. Feel free to open a new issue if there's an error that no one else has previously reported.
