### ISSUE TITLE
alpine-linux / APKBUILD

### ISSUE THREAD

**Issue by AVVS** [lovell/sharp#460]
I've been playing around libvips to actually make sharp 0.15.x work on alpine linux, here is what I've got:

https://gist.github.com/AVVS/c56026dee71f7aff29167532d2b96960

Could you help me and tell which libraries should be aded / removed from dependencies and whether I should add some specific compilation options? Thanks in advance

When its finalized I will try to publish it so that other can use it as well

**Comment by lovell** [comment]
Thanks @AVVS, you should probably speak with @wjordan who created https://github.com/alpinelinux/aports/pull/29 to get libvips into Alpine's "aports" repo.

**Comment by lovell** [comment]
Looks like there's some activity on the aports PR so I'm going to close this issue in preference to https://github.com/alpinelinux/aports/pull/29

**Comment by AVVS** [comment]
Been 18 days, so I'm not sure about activity :)
