### ISSUE TITLE
Sharp Fails to Build on Google Cloud Functions

### ISSUE THREAD

**Issue by don4of4** [lovell/sharp#462]
Google Cloud Functions is essentially the Google response to AWS Lambda and Azure's Functions package.

I am having difficulty with getting Sharp to compile, and I suspect the issue is relatively trivial to fix.  Essentially, my understanding is that functions are pushed to Google Cloud Functions (GCF) with the node_modules folder.  Google executes (npm rebuild??), and it blows up since the vips dependency was prepared for windows and not flushed.

Could someone take a look at my error log and provide some feedback?  Does my guess sound correct?  If so, can the install script be modified to identify when the environment has changed (and/or flush the files required therein)?

Error log:
[error.txt](https://github.com/lovell/sharp/files/310421/error.txt)

Google Bug Report:
https://code.google.com/p/google-cloud-sdk/issues/detail?id=895

**Comment by lovell** [comment]
> "it blows up since the vips dependency was prepared for windows"

Yes, this is the problem. If you want to take advantage of the pre-compiled libvips binaries you'll need to ensure `npm install` is run on the same platform as the deployed code. Any modern Linux should work.

**Comment by don4of4** [comment]
Shouldn't `npm rebuild` ideally redownload (or build) precompiled binaries?

**Comment by lovell** [comment]
https://cloud.google.com/functions/writing says

> "You can either pre-package fully materialized dependencies within your function package, or simply declare them in the package.json file and Cloud Functions will download them for you when you deploy."

so perhaps exclude the `node_modules` folder.

**Comment by don4of4** [comment]
@lovell It fails outright (missing modules), so I do believe this is a case of outdated documentation.  I will await their response on this.

**Comment by lovell** [comment]
@don4of4 Have you able to make any progress or get a response from Google?

**Comment by lovell** [comment]
Closing this as I assume everything is now working. Feel free to re-open if not.

**Comment by killtw** [comment]
I have same issue.
Tried some answer from internet, sadly all failed.
