### ISSUE TITLE
Separate repo for libvips build?

### ISSUE THREAD

**Issue by teohhanhui** [lovell/sharp#463]
i.e. What if I want to use the latest libvips?

**Comment by lovell** [comment]
Hello, did you see http://sharp.dimens.io/en/latest/install/#linux ?

> To use your own version of libvips instead of the provided binaries, make sure it is at least the version listed under `config.libvips` in the `package.json` file, that it can be located using `pkg-config --modversion vips-cpp`.

**Comment by teohhanhui** [comment]
Yes, I know, and I'm talking about what's under the `packaging` directory...

**Comment by teohhanhui** [comment]
Since `preinstall.sh` is deprecated, perhaps we should provide instructions for how to use what's under `packaging`...

**Comment by lovell** [comment]
Thanks Teoh. I'm not quite sure I understand the problem you're trying to solve.

As you've probably seen, the `packaging` directory contains build scripts that compile libvips and its dependencies for the most common use cases on the most common platforms. This is all very much behind the scenes and not something that most people will ever need to look at.

Changes to these scripts usually involve a related change to `binding.gyp` and/or the tests hence everything lives in the same repo for ease of version control.

**Comment by teohhanhui** [comment]
The deprecated `preinstall.sh` had a role to play for those who want an easy way to build libvips. What I'm proposing is for easy-to-follow usage instructions to be written for the build setup under `packaging`, so that it can take the front and center role for those who need / want to build libvips on their own (for whatever reasons).

**Comment by teohhanhui** [comment]
In other words, replace any reference to `preinstall.sh` with `packaging` in the docs, with the appropriate instructions of course.

**Comment by lovell** [comment]
> "so that it can take the front and center role for those who need / want to build libvips on their own"

For the benefit of all libvips' users, not just sharp users, I'd love to see this kind of thing live in libvips itself, perhaps as a [community-maintained Wiki page](https://github.com/jcupitt/libvips/wiki), and would be very happy to direct people to it.

**Comment by lovell** [comment]
> "What I'm proposing is for easy-to-follow usage instructions to be written for the build setup under packaging"

The `packaging` directory now has a README - https://github.com/lovell/sharp/tree/pencil/packaging

**Comment by lovell** [comment]
Docs now in master - https://github.com/lovell/sharp/tree/master/packaging - feel free to submit PRs to add/improve these, thanks for the original suggestion.
