### ISSUE TITLE
Should add build-essentials to Docs

### ISSUE THREAD

**Issue by EduardJS** [lovell/sharp#464]
Hello guys. You should add the following command to `Docs` or `FAQ` regarding the `node-gyp rebuild` fail as I see lots of people having problems on UNIX at least regarding that one, even after setting the corerct path.

```apt-get install build-essential g++```

Then you can easily run ```npm install sharp``` again with success this time.

**Comment by lovell** [comment]
Hello, the docs currently contain a [prerequisites](http://sharp.dimens.io/en/stable/install/#prerequisites) section with a link to `node-gyp`'s platform-specific prerequisites.

I'd be happy to accept a PR to make this clearer (as long as it's not simply repeating the contents of the `node-gyp` docs).
