### ISSUE TITLE
ERROR: https://dl.bintray.com/lovell/sharp/libvips-8.2.2-lin.tar.gz status code 404

### ISSUE THREAD

**Issue by jolks** [lovell/sharp#467]
<img width="1100" alt="screen shot 2016-06-15 at 11 56 38 am" src="https://cloud.githubusercontent.com/assets/765292/16066668/483b7ef2-32f0-11e6-9aed-51946ec96ca1.png">

By checking the URL https://dl.bintray.com/lovell/sharp/, we can see:-

<img width="530" alt="screen shot 2016-06-15 at 11 57 50 am" src="https://cloud.githubusercontent.com/assets/765292/16066683/69222eea-32f0-11e6-8b26-83348efb144c.png">

Seems like I need to update sharp version on my end. On the other hand, may I know the reason why the older versions are not available on https://dl.bintray.com/lovell/sharp/ ?

**Comment by papandreou** [comment]
https://github.com/lovell/sharp/issues/449

**Comment by jolks** [comment]
Thanks for the quick reply. I updated my version to 0.15.0. Noted on the security purpose.
