### ISSUE TITLE
Windows installation fails: libvips 8.2.0 no longer downloadable

### ISSUE THREAD

**Issue by franksrevenge** [lovell/sharp#469]
Sharp 0.12.2 produces the following error on Windows installations:

> ERROR: https://dl.bintray.com/lovell/sharp/libvips-8.2.0-win.tar.gz status code 404

It appears that the only available version via bintray is 8.3.1.

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/424 (and https://github.com/lovell/sharp/issues/449).
