### ISSUE TITLE
Fall-back to libmagick or libgraphicsmagick for GIFs

### ISSUE THREAD

**Issue by matylla** [lovell/sharp#47]
Is it possible to add support for GIFs (including animated GIFs) with a simple fall-back to libmagick or libgraphicsmagick? As mentioned in here jcupitt/ruby-vips#38 libvips does not support GIFs directly.

**Comment by muratcorlu** [comment]
Link is broken now. Do you still have an example for that?

**Comment by lovell** [comment]
@muratcorlu This is an old issue. GIF input is now supported (via giflib) since [v0.15.0](http://sharp.dimens.io/en/stable/changelog/#v0150-21st-may-2016). Please open a new issue if you're still having problems.
