### ISSUE TITLE
Enhancement: create blank/empty image of given dimensions/channels

### ISSUE THREAD

**Issue by pjarts** [lovell/sharp#470]
Is it possible to create an empty canvas image with Sharp and process it through a stream or do I need to load a canvas image file from disk?

**Comment by lovell** [comment]
Are you able to provide more information about the problem you're trying to solve? What do you mean by "canvas" in this context?

**Comment by pjarts** [comment]
The lwip node module has a method called "create" ([](https://github.com/EyalAr/lwip#create-a-new-image)) that creates an empty image. I was wondering if it is possible to accomplish the same thing in sharp, or if I always have to start off from an existing image file.

**Comment by lovell** [comment]
You could use a [raw](http://sharp.dimens.io/en/stable/api/#sharpinput-options) pixel input buffer for this, something like this (ES2015) example:

```javascript
const width = 200;
const height = 100;
const channels = 4;
const rgbaPixel = 0x00000000;

const canvas = Buffer.alloc(width * height * channels, rgbaPixel);

sharp(canvas, { raw : { width, height, channels } })...
```

**Comment by lovell** [comment]
@pjarts Were you able to make any progress with this?

**Comment by strarsis** [comment]
Would a little helper function in sharp make sense, like one that uses the canvas code above?

**Comment by pjarts** [comment]
@lovell, sorry for the late reply. Yes your code seems to do what I was looking for, although I agree with @strarsis that a helper function would be nicer.

**Comment by lovell** [comment]
@pjarts Thanks for confirming.

Let's leave this issue open to track adding such a helper - I'll need to have a think about what the API might look like.

**Comment by strarsis** [comment]
1. A kind of factory/'static' method:
````
sharp.empty()
````

2. With configuration object passed:
````
sharp({ width: 1024, height: 768 });
````

3. With no arguments passed at all or some constant? - using resize to achieve the desired dimensions:
````
sharp()
sharp(sharp.EMPTY_IMAGE)
````

**Comment by lovell** [comment]
The forthcoming v0.16.0 release moves all image input logic to a common location, namely the [_createInputDescriptor](https://github.com/lovell/sharp/blob/master/index.js#L172) function in JavaScript then [CreateInputDescriptor](https://github.com/lovell/sharp/blob/master/src/common.cc#L24) method in C++.

This is the best place to add such a "create image" helper, so any part of the API that can handle input images will be able to use it.

Here's how the API could work:
```javascript
sharp(null, {
  create: {
    width: 1024,
    height: 768,
    channels: 3,
    background: rgb
  }
})...
```
```javascript
sharp('input.jpg')
  .overlayWith(null, create: {
    width: 16,
    height: 32,
    channels: 4,
    background: rgba
  })...
```
where `rgb` and `rgba` are parsed by the `color` module, the same approach used by the existing [background](http://sharp.dimens.io/en/stable/api/#backgroundrgba) function.

**Comment by strarsis** [comment]
sharp@v0.16.0 doesn't seem to support it yet.

**Comment by lovell** [comment]
@strarsis That's correct. My comment about v0.16.0 was that it provided the ground work for this feature request.

**Comment by 5im0n** [comment]
Is this feature gonna be available in a next release ?

**Comment by lovell** [comment]
@5im0n I'm happy to help with a PR if you're able.

**Comment by lovell** [comment]
Commit 1aa053c adds the ability to create a blank image using the API described by comment https://github.com/lovell/sharp/issues/470#issuecomment-239620622 above. This will be available in v0.17.3.

**Comment by lovell** [comment]
v0.17.3 now available, thanks for all the suggestions.

**Comment by wmertens** [comment]
To combine multiple images, I did this instead of the empty canvas:

```js
	for (let i = 1, left = singleWidth; i < imgCount; i++, left += singleWidth) {
		// only one overlay per pipeline
		if (i > 1) {combined = sharp(await combined.toBuffer())}
		combined.overlayWith(imgBufs[i], {left, top: 0})
	}
```

so basically forcing sharp to process the pipeline once there is more than one overlay. Async/await makes this nice, with promises this code would be a bit harder.
