### ISSUE TITLE
Incompatible library version: libopencv_highgui.2.4.dylib requires version 13.0.0 or later, but libjpeg.8.dylib provides version 9.0.0

### ISSUE THREAD

**Issue by PardoAlejo** [lovell/sharp#471]
Hi,

I'm trying to run: Make runtest after the installation of caffe. And i get the following message:

Incompatible library version: libopencv_highgui.2.4.dylib requires version 13.0.0 or later, but libjpeg.8.dylib provides version 9.0.0

Can you help me please?

**Comment by lovell** [comment]
Was this question intended for a different repo?

**Comment by lovell** [comment]
Cross-posted at http://stackoverflow.com/questions/37956202/incompatible-library-version-libopencv-highgui-2-4-dylib-requires-version-13-0
