### ISSUE TITLE
Resize no longer accept null for auto scale at v0.15

### ISSUE THREAD

**Issue by yskeat** [lovell/sharp#476]
Resize no longer accept null for auto scale as mention at http://sharp.readthedocs.io/en/stable/api/#resizewidth-height-options after update to 0.15

**Comment by lovell** [comment]
Hello, there's a passing test case for fixed height and null=auto-width at https://github.com/lovell/sharp/blob/master/test/unit/resize.js#L32-L41

I modified this locally for an example of fixed width, null=auto-height, which also passed:
```javascript
  it('Fixed width', function(done) {
    sharp(fixtures.inputJpg).resize(320, null).toBuffer(function(err, data, info) {
      if (err) throw err;
      assert.strictEqual(true, data.length > 0);
      assert.strictEqual('jpeg', info.format);
      assert.strictEqual(320, info.width);
      assert.strictEqual(261, info.height);
      done();
    });
  });
```
Are you able to provide more details of the error and/or effects of the problem you're experiencing?

**Comment by yskeat** [comment]
Sorry, false alarm. 
My console some how return null instead of NaN when I attempt to parseInt(null).
