### ISSUE TITLE
How to dynamically write text to image?

### ISSUE THREAD

**Issue by S-YOU** [lovell/sharp#477]
Is there a way to write dynamic text to image? 
If so, can someone provide some hint on how to do that?

**Comment by lovell** [comment]
Hello, the best way to do this is probably to pass an SVG containing the text as the overlay image passed to the [overlayWith](http://sharp.dimens.io/en/stable/api/#overlaywithimage-options) operation.

**Comment by S-YOU** [comment]
Good idea, thank you.

**Comment by strarsis** [comment]
The image into which the text SVG is overlayed is resized (and cloned) multiple times - 
the sharp SVG  instance has to be resized then to achieve the same relative size. 
However, resizing using the resize(...) sharp API method will 
degrade the quality (apparently the SVG is rasterized when being loaded by sharp).

How can I achieve the same relative text/font/dimensions of a SVG 
overlayed into a sharp image of varying dimensions?

**Comment by S-YOU** [comment]
svg is a text, so may be create each svg on the fly?

**Comment by strarsis** [comment]
[text-to-svg](https://www.npmjs.com/package/text-to-svg) and [vectorize-text](https://www.npmjs.com/package/vectorize-text) both accept the font-size in pt. Also there is kerning and other irregularities - so in the end a reliable method for calculating the right font-size 
for a specific width of resulting SVG text is needed.

**Comment by lovell** [comment]
> "apparently the SVG is rasterized"

If you've not seen it, the `density` option of sharp's [constructor](http://sharp.dimens.io/en/stable/api/#sharpinput-options) can be used to alter the resolution at which vector inputs are converted to a bitmap.

**Comment by DetectiveFalcon** [comment]
@lovell by chance do you have an example of how the SVG (with the text) can be created in line to then be passed to sharp for the overlay? I'm struggling to find any examples on it. It's the last piece to the puzzle for this project.

**Comment by onigor** [comment]
Basic svg:
```
<svg xmlns="http://www.w3.org/2000/svg">
  <text x="0" y="35" font-size="35" fill="black" stroke="none">Example Text</text>
</svg>
```
You can write function to replace text:
``` 
const newSVG = (text)=>{ return `<svg xmlns="http://www.w3.org/2000/svg">
  <text x="0" y="35" font-size="35" fill="black" stroke="none">${text}</text>
</svg>`  };

newSVG('Welcome!');
newSVG('Test!');

```
