### ISSUE TITLE
Large files

### ISSUE THREAD

**Issue by titel** [lovell/sharp#478]
Hello,

I've implemented the sharp package and I'm seeing great performance in terms of speed and resources used. However, for large resolution resizes, the resulted file more often than not, tends to be bigger than the original.

For a 1000px x 750px PNG file I ran a test with for instance, the original file was a little less than 1 MB and the resulting file (same resolution as this size is less than the set .max() I was testing with) was 1.4 MB.

I should also mention that I used compressionLevel set to 9 and withoutAdaptiveFiltering for this test. What are the other recommended methods / settings to be used with the resize function that would result in a smaller file size for PNGs? What about JPEG files?

Thanks,
Constantin

**Comment by lovell** [comment]
Hi there, I suspect you've run into a limitation of libvips' PNG output supporting a minimum of 8 bits per pixel. PNG tools such as `pngquant` use quantisation to reduce this to 1, 2 or 4 bits per pixel.

**Comment by lovell** [comment]
Hope this answered your question. Feel free to re-open if not :)

**Comment by lovell** [comment]
Since sharp v0.28.0, libimagequant is included in the prebuilt binaries, which means palette PNGs can be generated.

https://sharp.pixelplumbing.com/api-output#png

```js
await sharp(input)
  .png({ palette: true })
  .toBuffer();
```
