### ISSUE TITLE
Slow resize + png for YCbCr images

### ISSUE THREAD

**Issue by luciferous** [lovell/sharp#481]
I have an image ([ycbcr.tif](https://gist.github.com/luciferous/8d8d25b534a6047cd07e78a4e36cddf1/raw/f9d69ae83c8cba768cc20492f72fbfc378bda291/ycbcr.tif)) that I want to resize and convert to PNG. Using `resize` and `png` the operation takes about 9 seconds.

```javascript
// resize.js
require('sharp')(process.argv[2]).png().resize(100).toBuffer(() => {
  console.log('done processing', process.argv[2]);
});
```

```
$ time VIPS_WARNING=0 node resize.js ycbcr.tif
done processing ycbcr.tif

real    0m8.934s
user    0m8.298s
sys     0m0.601s
```

The same image using `vipsthumbnail` takes 75ms.

```
$ time VIPS_WARNING=0 vipsthumbnail --size=100 --format='%s.png' ycbcr.tif

real    0m0.075s
user    0m0.063s
sys     0m0.010s
```

Curiously, if I process ycbcr.tif with `gdalwarp -dstalpha`, and use the output (`alpha.tif`), sharp's operations become much faster.

```
$ gdalwarp ycbcr.tif alpha.tif -dstalpha
$ time VIPS_WARNING=0 node resize.js alpha.tif
done processing alpha.tif

real    0m0.202s
user    0m0.176s
sys     0m0.058s
```

(Note: I've described the images as YCbCr and alpha, but I don't know what differences exactly account for the processing time discrepancy. These are just the formats I happen to be using when I encountered the issue.)

**Comment by lovell** [comment]
Hello, a quick look at your input file suggests it contains 8 pages/images, which could explain some of the difference, although the default behaviour of both sharp and vips should be to use the first page/image only.

I wonder if this could also have something to do with colour space conversion. I'll do some code profiling and report back here - thanks for the report!

**Comment by lovell** [comment]
Adding [sequentialRead()](http://sharp.dimens.io/en/stable/api/#sequentialread) to the processing chain "fixes" this by preventing libtiff from decoding too far ahead. `vipsthumbnail` always uses the sequential approach.

**Comment by luciferous** [comment]
@lovell Thanks. Yes, I'm also seeing that adding sequentialRead speeds up the operation.

**Comment by lovell** [comment]
Thanks for confirming.

If it's OK with you I'd like to leave this open until I've had a chance to inspect the libvips-libtiff-libjpeg bridge more closely. I spotted some possible efficiencies whilst profiling this code, e.g. the mostly-unnecessary "fancy upsampling" feature of libjpeg seemed to always be enabled.

**Comment by luciferous** [comment]
Of course, let's leave it open. I'm interested in following along with the developments.

**Comment by lovell** [comment]
On closer inspection, it appears libtiff commit https://github.com/vadz/libtiff/commit/16eb07a48f2b4ca3e12f52a254a868c197e024da (unofficial mirror) fixes the `do_fancy_upsampling` related performance problem I was seeing.

**Comment by luciferous** [comment]
@lovell This image has a transparency mask but with only three channels. Sharp doesn't seem to be use it to make transparent PNGs, or perhaps I'm missing an option. Could this be part of the issue? I can create another ticket if it's unrelated.

**Comment by lovell** [comment]
This image appears to be an 8 page TIFF, with the transparency on the second page, and then 6 more pages after that.

```sh
$ identify ycbcr.tif
ycbcr.tif[0] TIFF 1667x1674+0+0 DirectClass 8-bit 789.9K 0.000u 0:01
ycbcr.tif[1] TIFF 1667x1674+0+0 DirectClass 1-bit 789.9K 0.000u 0:01
ycbcr.tif[2] TIFF 834x837+0+0 DirectClass 8-bit 789.9K 0.000u 0:01
ycbcr.tif[3] TIFF 417x419+0+0 DirectClass 8-bit 789.9K 0.000u 0:01
ycbcr.tif[4] TIFF 209x210+0+0 DirectClass 8-bit 789.9K 0.000u 0:01
ycbcr.tif[5] TIFF 834x837+0+0 DirectClass 1-bit 789.9K 0.000u 0:01
ycbcr.tif[6] TIFF 417x419+0+0 DirectClass 1-bit 789.9K 0.000u 0:01
ycbcr.tif[7] TIFF 209x210+0+0 DirectClass 1-bit 789.9K 0.000u 0:01
```

 Currently, sharp only uses the first page of a multi-page TIFF file.

If you need multi-page support please create a new issue, although this will only allow you to extract/process one numbered page at a time.

To then create an RGBA PNG, you'll have to write the logic to perform the joining of pages (there will soon be a joinChannel operation via #513 to help with this).
