### ISSUE TITLE
 ubuntu 16 installation fails

### ISSUE THREAD

**Issue by ickeep** [lovell/sharp#482]
root@ubuntu:~# npm install -g sharp

> sharp@0.15.0 install /usr/lib/node_modules/sharp
> node-gyp rebuild

gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn EACCES
gyp ERR! stack     at exports._errnoException (util.js:873:11)
gyp ERR! stack     at ChildProcess.spawn (internal/child_process.js:298:11)
gyp ERR! stack     at exports.spawn (child_process.js:362:9)
gyp ERR! stack     at exports.execFile (child_process.js:151:15)
gyp ERR! stack     at checkPythonVersion (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:371:5)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:338:9
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:88:20
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 4.5.5-x86_64-linode69
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/sharp
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! Linux 4.5.5-x86_64-linode69
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "sharp"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.15.0 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the sharp@0.15.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

**Comment by lovell** [comment]
Hello, please see https://github.com/lovell/sharp/issues/428#issuecomment-218827659
