### ISSUE TITLE
Own version of libvips vs provided binaries

### ISSUE THREAD

**Issue by florentb** [lovell/sharp#485]
Just a question @lovell. How to know if Sharp has been built with a custom version of libvips or with the provided binaries ?

**Comment by lovell** [comment]
Bonjour, the [sharp.versions](http://sharp.dimens.io/en/stable/api/#versions) attribute will contain only a single entry, namely `vips`, when built against a globally-installed version of libvips.

**Comment by lovell** [comment]
Hope this answered your question. Feel free to re-open if not :)
