### ISSUE TITLE
debian and non-free icc profiles

### ISSUE THREAD

**Issue by kapouer** [lovell/sharp#486]
Hi,
since i'm using sharp and am also a debian maintainer, i figured i could avoid the trouble of rebuilding it by packaging it for debian. So i started to review the files, to find that both ICC profiles are not distributable in the main debian archive because they are non-free. I think it's possible to replace them with free version found in icc-profiles-free package; maybe you could help picking the right ones:

```
/usr/share/color/icc/CineonLog_M.icc
/usr/share/color/icc/TR005.ti3
/usr/share/color/icc/ITULab.icc
/usr/share/color/icc/LStar-RGB.icc
/usr/share/color/icc/TR006.ti3
/usr/share/color/icc/compatibleWithAdobeRGB1998.icc
/usr/share/color/icc/LCMSXYZI.ICM
/usr/share/color/icc/CineonLog_M_Knee_60.icc
/usr/share/color/icc/Gray-CIE_L.icc
/usr/share/color/icc/sRGB.icc
/usr/share/color/icc/CineonLog_M_Knee_10.icc
/usr/share/color/icc/Gray.icc
/usr/share/color/icc/FOGRA28L.ti3
/usr/share/color/icc/CineonLog_M_Knee_30.icc
/usr/share/color/icc/FOGRA29L.ti3
/usr/share/color/icc/LCMSLABI.ICM
/usr/share/color/icc/TR003.ti3
/usr/share/color/icc/FOGRA40L.ti3
/usr/share/color/icc/CineLogCurve.icc
/usr/share/color/icc/FOGRA39L.ti3
/usr/share/color/icc/TR002.ti3
/usr/share/color/icc/CineonLog_M_Knee_20.icc
/usr/share/color/icc/FOGRA30L.ti3
```

Why the current profiles are not free is:
- sRGB_IEC61966-2-1_black_scaled.icc is [ICC licensed](http://www.color.org/srgbprofiles.xalter) with a clause `free to distribute provided that the file is not changed` that makes it non-free (as seen from a free software point of view)
- USWebCoatedSWOP.icc seems to have the license here: https://www.adobe.com/support/downloads/detail.jsp?ftpID=4075 and it isn't a free software license either `No other distribution of the Software is allowed; including, without limitation, distribution of the Software when incorporated into or bundled with any application software. You may not modify the Software.`

Thank you for your attention.

**Comment by jcupitt** [comment]
libvips went through this issue a few years ago. After some research we settled on this CMYK profile:

http://www.argyllcms.com/cmyk.icm

It's a good default CMYK profile, probably better than USWebCoatedSWOP.icc. You can see the licence here:

https://sourceforge.net/p/lcms/mailman/message/32755884/

The srgb profile is much less critical. The `/usr/share/color` one is fine.

**Comment by jcupitt** [comment]
I meant to add, Debian does not currently have (as far as I know) a good CMYK profile. How about formally adopting the Argyll one? It's an excellent profile, and public domain.

**Comment by lovell** [comment]
I'm surprised at the ICC licensing terms for their v2 sRGB profile :( but using the existing Debian-provided version will be fine.

Thanks for the details of a suitable PD CMYK profile John. I'll update sharp to use both of these instead.

Jérémy, are there any licensing limitations in Debian around documentation? The sharp docs do not currently have a separate licence beyond the overall Apache 2.0, which probably isn't that suitable. Would it make it easier to have this as CC0?

**Comment by kapouer** [comment]
There is no problem with the Apache 2.0 license, as far as debian is concerned.

**Comment by kapouer** [comment]
The only other problem that could arise is the embedded profiles in the images in the fixtures directory. I'll inspect them and report a bit later (gtg).

**Comment by lovell** [comment]
@kapouer Are you able to create a package without the `test` directory (also anything mentioned in https://github.com/lovell/sharp/blob/master/.npmignore )?

**Comment by kapouer** [comment]
The fixtures with a copyrighted ICC profile:
First i searched all things with a copyright in it:
```
find . -type f -exec identify -verbose '{}' \; | grep -i copyright
```

Then
```
fgrep -Rl "Copyright 2007 Apple Inc., all rights reserved" *
test/fixtures/Landscape_7.jpg
test/fixtures/Portrait_7.jpg
test/fixtures/Landscape_5.jpg
test/fixtures/Landscape_2.jpg
test/fixtures/Landscape_6.jpg
test/fixtures/Portrait_3.jpg
test/fixtures/Portrait_6.jpg
test/fixtures/Landscape_4.jpg
test/fixtures/Landscape_3.jpg
test/fixtures/Landscape_8.jpg
test/fixtures/Portrait_4.jpg
test/fixtures/Portrait_8.jpg
test/fixtures/Portrait_2.jpg
test/fixtures/Portrait_5.jpg
```
```
fgrep -Rl "Copyright 2000 Adobe Systems, Inc." *
icc/USWebCoatedSWOP.icc
test/fixtures/Channel_digital_image_CMYK_color.jpg
```
```
fgrep -Rl "Copyright (c) 1998 Hewlett-Packard Company" *
test/fixtures/low-contrast.jpg
```

I'm now trying to figure the corresponding licenses. It doesn't look that bad.

**Comment by lovell** [comment]
Commit 91e1ed1 switches the profiles in `icc/*` to their free alternatives.

**Comment by lovell** [comment]
v0.15.1 includes the free alternatives discussed here in its `icc` directory.

**Comment by lovell** [comment]
@kapouer Are there any other files (apart from the test directory that can be removed from a binary distribution) that might prevent Debian packaging?

**Comment by kapouer** [comment]
As of version 0.17, except for embedded profiles in test pictures, everything else looks all right.
Thanks !
