### ISSUE TITLE
Fails with paths including spaces

### ISSUE THREAD

**Issue by strarsis** [lovell/sharp#488]
On Windows, node-sharp fails when a valid path to an image file is passed that also contains spaces:
````
[Error: Input file is missing or of an unsupported image format]
````

In contrast, e.g. the fs module can successfully use the same path, 
including spaces, to read the image file into buffer.

One could use this as workaround, first reading the image file into buffer, 
then passing that buffer to node-sharp - 
but there may be performance degrading, as optimizations in node-sharp 
like streaming or peeking for metadata are skipped.

Maybe resolving the path + getting a file/stream handle could be handled by node, 
then used by the existing C++ implementation?

**Comment by lovell** [comment]
Hello, are there any UTF-16 chars in the path? #319 and #406 are examples of these failing on Windows.

**Comment by strarsis** [comment]
After testing a bit more, I conclude it isn't the space character causing this issue 
but special characters indeed, umlauts (e.g. 'ö') in file and/or folder name.
