### ISSUE TITLE
How to solve the dependence version incorrect problem

### ISSUE THREAD

**Issue by JiaJiaJiang** [lovell/sharp#489]
testing on osx 10.11.5

Uncaught Exception: Error: dlopen([****project dir****]/node_modules/sharp/build/Release/sharp.node, 1): Library not loaded: /usr/local/opt/orc/lib/liborc-0.4.0.dylib
  Referenced from: /usr/local/opt/vips/lib/libvips-cpp.42.dylib
  Reason: Incompatible library version: libvips-cpp.42.dylib requires version 26.0.0 or later, but liborc-0.4.0.dylib provides version 24.0.0

**Comment by lovell** [comment]
Hello, please see #453

**Comment by JiaJiaJiang** [comment]
thank you very much!
