### ISSUE TITLE
Sharpening images with alpha channel results in vips_colourspace: no known route between 'multiband' and 'srgb'

### ISSUE THREAD

**Issue by jwagner** [lovell/sharp#490]
To reproduce:
```
var sharp = require('sharp');
var request = require('request');
var img = sharp();
// this fails:
img.sharpen(2.0, 0.125, 0.2);
// this works: img.sharpen();
img.toFile('test.png');
request('http://bin.staticlocal.ch.s3-website-eu-west-1.amazonaws.com/localplace-logo/c5/c5d70ab09e8a39f3481ca488560b92e3a1ff0b86/amaya_logo.png').pipe(img);
```
Expected behaviour:
The sharpened image is saved

Actual behaviour:
```
Unhandled rejection Error: vips_colourspace: no known route between 'multiband' and 'srgb'
    at Error (native)
```

It only happens on certain images. I'm not sure whats exactly triggering it.

**Comment by lovell** [comment]
Hi Jonas, the parameter-less version of `sharpen` uses a fast, kernel-based convolution. The with-params version calls `vips_sharpen`, which converts to the LAB colourspace. It looks like the output ends up being the generic "multiband" when the input, such as your example, contains an alpha channel.

Commit 4c172d2 adds a (previously failing) test case for this as well as the fix.

Thanks for reporting!

**Comment by jwagner** [comment]
You are very quick sir! :) Thank you!

**Comment by lovell** [comment]
v0.15.1 now available.
