### ISSUE TITLE
Feature request: Trim support

### ISSUE THREAD

**Issue by kevin1024** [lovell/sharp#491]
Would love to have this feature, similar to ImageMagick.  It removes borders around images:

![](http://2.bp.blogspot.com/-qqiFk9xjlDo/UvpYznotYAI/AAAAAAAAAc4/5c13ph5acxg/s1600/x.jpg)

I noticed there is a blog post about how to implement it in libvips here, might be a good starting point!

http://libvips.blogspot.com/2014/02/trim-auto-crop-with-ruby-vips.html

**Comment by lovell** [comment]
Hello, this feature, including sample code, has been mentioned previously at https://github.com/lovell/sharp/issues/295#issuecomment-203442516

The trim operation would probably make sense occurring before any resize operation.

As always I'm happy to accept a PR and/or provide help to anyone who'd like to attempt to implement this.

**Comment by kleisauke** [comment]
I was trying to implement the trim operation with the [example](https://gist.github.com/jcupitt/eecd6d24692c388799e5) provided by @jcupitt. However it's currently not working (the input image is the same as the output). It would be great if someone could look at it. See: [tree#feature-trim](https://github.com/kleisauke/sharp/tree/feature-trim)

**Comment by jcupitt** [comment]
Hi @kleisauke, you use `.project()` like this:

```C++
    VImage rows;
    VImage columns = mask.project(&rows);
```

Same for `.profile()`. It's a little awkward, unfortunately.

**Comment by kleisauke** [comment]
Thanks @jcupitt! A pull request has been made for this feature at #492.

**Comment by lovell** [comment]
In what will probably be the biggest "patch" release ever, the `trim` feature will be available in v0.15.1 thanks to the marvellous @kleisauke.

**Comment by kevin1024** [comment]
This is amazing, thanks so much!

**Comment by lovell** [comment]
v0.15.1 now available, thanks @kleisauke for the code and @kevin1024 for the suggestion.
