### ISSUE TITLE
sharp-cxx11 flag doesn't get picked up from npm command line

### ISSUE THREAD

**Issue by mhirsch** [lovell/sharp#494]
I'm trying to build sharp for use with a package manager installed vips library. When I build it as described in the docs (`install.md`) with `npm install --sharp-cxx=1` the resulting binary `sharp.node` is not built with the CXX11 ABI. However, if I change line 54 of `binding.gyp` to read `'sharp-cxx11%': '1',`, I get a CXX11 ABI binary, as expected. I'm not too familiar with gyp files -- any idea why this might not be getting connected?

**Comment by lovell** [comment]
It looks like the dash in the variable name prevents it getting passed from npm to node-gyp, at least on . Changing it to `sharp_cxx11` works as expected.

https://github.com/npm/npm/blob/master/node_modules/node-gyp/lib/configure.js#L147

@kapouer Any problem if we change this to use a underscore instead?

**Comment by kapouer** [comment]
Oh, that explains everything :+1:

**Comment by lovell** [comment]
Commit 7689fbe is your friend. Thanks for reporting this Matt.

**Comment by mhirsch** [comment]
Thanks for the quick fix!

**Comment by lovell** [comment]
Commit https://github.com/lovell/sharp/commit/07d66da57b7829fca938d7e3c5c4b47a981b1d17 should fully automate this, and therefore removes the `sharp-cxx11` flag.
