### ISSUE TITLE
Error while sharpening transparent png image

### ISSUE THREAD

**Issue by digiperfect-sandeep-kumar** [lovell/sharp#495]
Hi 

I am getting following error when using a transparent image png and trying sharpen it using the API of sharp with sigma value. example  : sharpen(0.7)

After calling sharpen function when I call toBuffer function, I get the following error in callback.
Error: vips_colourspace: no known route between 'multiband' and 'srgb'

    at Error (native)

 I am using 0.15.0 version of sharp and 8.3.1 version of vips.
image link : http://orig04.deviantart.net/cbe1/f/2009/067/a/a/green_humming_bird_png_by_pixievamp_stock.png

**Comment by lovell** [comment]
Hello, this looks like #490, which will be fixed in the forthcoming v0.15.1.

**Comment by digiperfect-sandeep-kumar** [comment]
Thanks for quick response. :)
 
By when can we expect v0.15.1 to released ?
