### ISSUE TITLE
Allow empty sharp image

### ISSUE THREAD

**Issue by strarsis** [lovell/sharp#505]
For specific applications, like with using overlayWith(...), 
it may be necessary or easier to just create an wholly empty image 
(maybe with specific dimensions or just 1px x 1px and extend(...) it).

However, using sharp() without any argument 
results in non-functional output methods.

One workaround may be using a dummy input image - 
but this unnecessarily complicates the application.

**Comment by lovell** [comment]
Hello, did you see #470, a similar question?

**Comment by strarsis** [comment]
Yes, this seems to be the same issue.
