### ISSUE TITLE
Allow overlayWith(...) with source-/overlay-image without an alpha channel

### ISSUE THREAD

**Issue by strarsis** [lovell/sharp#506]
One may want to customarily tile solid images using overlayWith(...).
This isn't currently possible as those source-/overlay-images got no alpha channel (e.g. jpg images).

Alternatively an extra method could be added to sharp that allows adding an alpha channel - 
and when it is just 100% solid so that overlayWith(...) is satisfied.

**Comment by lovell** [comment]
Automagically adding an opaque alpha channel is probably the way to go here. PR welcome, as always :)

**Comment by strarsis** [comment]
I would even propose an opposite to extract(...) method - and then using this in the automagical code.

**Comment by lovell** [comment]
Fixed in v0.16.0 thanks to @cmtt and now available via npm.
