### ISSUE TITLE
unable to install npm in local project directory

### ISSUE THREAD

**Issue by redrowthueswar** [lovell/sharp#507]
i am trying npm installation, some problems  npm installtion time....
i was given python path  cmd prompt ..like..(npm config set python C:\Python27\python.exe)
that time its display below errors......how to  resolve this errors?

![npm issue](https://cloud.githubusercontent.com/assets/20437102/16800324/5ad039bc-4912-11e6-855f-901f3561e579.png)

**Comment by lovell** [comment]
It looks like this error is from the unrelated [contextify](https://www.npmjs.com/package/contextify) module. What was it about the error that made you think this module, sharp, might be involved?

**Comment by redrowthueswar** [comment]
@lovell Thanks for the quick turnaround .... This is the first time I am using npm to be installed in to my local project. Is there any possibility of routing it to respective module owners? or you want me to contact "brianmcd <brianmcd05@gmail.com>" which I got up on running "npm owner ls contextify"> please advice.

**Comment by lovell** [comment]
Please ask at https://github.com/brianmcd/contextify (but note the "YOU DON'T NEED THIS MODULE ON NODE >= 0.12" warning)
