### ISSUE TITLE
0.15.1: Additional error from libvips when attempting to extract an invalid area

### ISSUE THREAD

**Issue by papandreou** [lovell/sharp#509]
```
$ node -e "require('sharp')('testdata/turtle.jpg').extract({left: 10000, top: 10000, width: 10, height: 10}).toBuffer(console.log);"
Error: enum 'VipsOperationBoolean' has no member 'null', should be one of: and, or, eor, lshift, rshift
enum 'VipsOperationBoolean' has no member 'null', should be one of: and, or, eor, lshift, rshift
extract_area: bad extract area

    at Error (native) null null
```

(turtle.jpg is a 481x424 image)

With sharp 0.15.0 only the last part ("extract_area: bad extract area") was logged. Is that reason for concern?

**Comment by papandreou** [comment]
Also happens on master (15a5778).

**Comment by mhirsch** [comment]
I submitted a pr for this. I'm not sure what happened -- these assignments used to be surrounded by a check for whether the operation in question was requested. The pr takes the approach of checking whether the operations exist in the options object rather than special casing the 'null' operation. Does that sound ok to you?

**Comment by lovell** [comment]
@papandreou Are you able to confirm @mhirsch's fix (and associated test case) fixes this?

**Comment by papandreou** [comment]
@lovell Confirmed -- doesn't happen on master now.

**Comment by mhirsch** [comment]
I think this could be closed now, unless anyone objects.

**Comment by papandreou** [comment]
@mhirsch I didn't close it because @lovell usually likes to keep issues open until the a fix has been released.

**Comment by lovell** [comment]
v0.16.0 is now available via npm.
