### ISSUE TITLE
toBuffer Promise never fullfilled

### ISSUE THREAD

**Issue by katagaStyle** [lovell/sharp#510]
```
let transformer = sharp()
      .rotate()
      .png()
      .toBuffer();

transformer.then( ( outputBuffer: any ) =>
{
    console.log( 'buffer' );
} );

readableStream.pipe( transformer );
```

The Promise will never be fullfilled. Any ideas?

**Comment by lovell** [comment]
Hello, there's an example of Stream-in/Promise-out in the tests.

https://github.com/lovell/sharp/blob/master/test/unit/io.js#L81-L91

Perhaps there's an error that needs a `catch`?

**Comment by lovell** [comment]
@katagaStyle Were you able to make any progress with this?

**Comment by lovell** [comment]
Closing this as there's been no update for a while - feel free to re-open if there's more information.
