### ISSUE TITLE
node-gyp rebuild fails

### ISSUE THREAD

**Issue by CecilWesterhof** [lovell/sharp#517]
When doing:
    npm install sharp
I get:
npm ERR! Failed at the sharp@0.15.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild

This is on openSUSE 13.2

**Comment by lovell** [comment]
Please can you provide more of the error log.

**Comment by CecilWesterhof** [comment]
That was fast. :-D

7074 verbose about to build /home/cecil/node_modules/sharp
7075 info build /home/cecil/node_modules/sharp
7076 info linkStuff sharp@0.15.1
7077 silly linkStuff sharp@0.15.1 has /home/cecil/node_modules as its parent node_modules
7078 verbose linkBins sharp@0.15.1
7079 verbose linkMans sharp@0.15.1
7080 verbose rebuildBundles sharp@0.15.1
7081 verbose rebuildBundles [ '.bin', 'bluebird', 'color', 'nan', 'request', 'semver', 'tar' ]
7082 info install sharp@0.15.1
7083 verbose unsafe-perm in lifecycle true
7084 info sharp@0.15.1 Failed to exec install script
7085 verbose unlock done using /home/cecil/.npm/_locks/sharp-21ec4f5a81f17b9e.lock for /home/cecil/node_modules/sharp
7086 verbose stack Error: sharp@0.15.1 install: `node-gyp rebuild`
7086 verbose stack Exit status 1
7086 verbose stack     at EventEmitter.<anonymous> (/usr/lib64/node_modules/npm/lib/utils/lifecycle.js:217:16)
7086 verbose stack     at emitTwo (events.js:87:13)
7086 verbose stack     at EventEmitter.emit (events.js:172:7)
7086 verbose stack     at ChildProcess.<anonymous> (/usr/lib64/node_modules/npm/lib/utils/spawn.js:24:14)
7086 verbose stack     at emitTwo (events.js:87:13)
7086 verbose stack     at ChildProcess.emit (events.js:172:7)
7086 verbose stack     at maybeClose (internal/child_process.js:827:16)
7086 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
7087 verbose pkgid sharp@0.15.1
7088 verbose cwd /home/cecil
7089 error Linux 4.1.12-1-default
7090 error argv "/usr/bin/node" "/usr/bin/npm" "install" "sharp"
7091 error node v4.4.5
7092 error npm  v2.15.5
7093 error code ELIFECYCLE
7094 error sharp@0.15.1 install: `node-gyp rebuild`
7094 error Exit status 1
7095 error Failed at the sharp@0.15.1 install script 'node-gyp rebuild'.
7095 error This is most likely a problem with the sharp package,
7095 error not with npm itself.
7095 error Tell the author that this fails on your system:
7095 error     node-gyp rebuild
7095 error You can get information on how to open an issue for this project with:
7095 error     npm bugs sharp
7095 error Or if that isn't available, you can get their info via:
7095 error
7095 error     npm owner ls sharp
7095 error There is likely additional logging output above.

**Comment by lovell** [comment]
Is `node-devel` installed? Might be some hints in the set-up script for the (Docker-based) OpenSUSE packaging tests at https://github.com/lovell/sharp/blob/master/packaging/test/opensuse.sh

**Comment by CecilWesterhof** [comment]
That was the problem. Maybe good to mention at http://sharp.dimens.io/en/stable/install/? npm is nodejs package manager, but because I was installing something for Clojure I did not think about that.

By the way: it is nodejs-devel. ;-)

**Comment by ChuanHit** [comment]
@Westerhof, I am facing the same problem, cannot install sharp in a CentOS. 
Could you help to tell me how to solve the problem?
I have npm installed, not sure if this is the nodejs-devel you mentioned.
Thanks

**Comment by CecilWesterhof** [comment]
No, npm is the node.js package manager. You probably need to do:
    yum install nodejs-devel

**Comment by tcober** [comment]
On a mac and getting the same error
