### ISSUE TITLE
gif to webp conversion without losing animation

### ISSUE THREAD

**Issue by ashish-soni** [lovell/sharp#518]
conversion of gif to webp loses the animation.

`sharp('/home/ashish/Pictures/200.gif').toFormat(sharp.format.webp).toFile('/home/ashish/Pictures/200_s.webp', function (err) {
		console.log('gif', err);
	});`

**Comment by lovell** [comment]
Hello, animated GIFs are unsupported by libvips and hence sharp. #245

**Comment by hbakhtiyor** [comment]
hi @lovell , is animated webp supported?

**Comment by lovell** [comment]
@hbakhtiyor See https://github.com/libvips/libvips/issues/823
