### ISSUE TITLE
Installation failed in Windows 64-bit OS

### ISSUE THREAD

**Issue by bhushankumarl** [lovell/sharp#522]
Hello,

The node-gyp failed on installation of sharp :
npm install sharp or 
npm install sharp -g
http://prntscr.com/bvqnko

As you can see in above image, it shows error of 32-bit OS. You can see here http://prntscr.com/bvqo3k, It's 64-bit.

Please let me know, if I does something wrong.

Thank You

**Comment by lovell** [comment]
Hello, it looks like you're using a 32-bit `node.exe` (even though the OS is 64-bit).

http://sharp.dimens.io/en/stable/install/#windows

**Comment by bhushankumarl** [comment]
@lovell 
After replace current node version with 'node-v4.4.7-x64' , issue has been solved.

Thank you
