### ISSUE TITLE
Promises and raw buffers -- awkward with current API

### ISSUE THREAD

**Issue by mhirsch** [lovell/sharp#523]
If using a raw buffer, it's hard to also use promises, as I don't currently see a convenient way to get the buffer size information along with the raw buffer.

For example, this is a pattern (perhaps misguded?) that I've seen come up a lot with raw buffers:

```javascript
sharp(input)
  .someop()
  .raw()
  .toBuffer(function callback(err, buf, info) {
    doSomethingWithBuffer(buf, info);
  });
```

As you could, for example, run another processing stage with sharp in `doSomethingWithBuffer()`:

```
sharp(buf, {raw: info})...
```

It would be great to use promises for this, which I would like to use this way:

```javascript
sharp(input)
  .someop()
  .raw()
  .toBuffer()
  .then( doSomethingPromise );
```

But at the moment, the promise returned by `toBuffer()` only populates the first argument (I think, to spec) so

```javascript
doSomethingPromise(err, buf, info) {
  console.log(err, buf, info);
}
```

Prints:

```
<Buffer xx yy zz ... > undefined undefined
```

This leaves you with a buffer in the processing chain with no structure information. One could imagine, for the purpose of a raw buffer promise, returning an object like this, rather than just the node buffer:
```
buffer {
  buf: nodeBuffer,
  info: { 
    format: 'raw',
    width: 200,
    height: 200,
    channels: 4,
    size: 12345 
  }
}
```

I'm not sure how to balance backward compatibility with that approach. I.e. would all sharp buffers be embedded in such an object? All sharp raw buffers? Only those returned by a promise?

Another compounding problem (bug?) is that `sharp().metadata()` doesn't work if the input to sharp was a raw buffer.

Interested in hearing people's thoughts.

**Comment by mhirsch** [comment]
In bluebird, `promisify` has a `multiArgs` option, which returns multiple arguments to a callback in an array. Maybe this is the standard to follow.

**Comment by lovell** [comment]
Hi Matt, did you see #143?

**Comment by lovell** [comment]
@mhirsch bump

**Comment by mhirsch** [comment]
It would be great if `toBuffer` returned a promise that resolved with an argument array, following bluebird `multiArgs: true` and your suggestion in #143.

**Comment by mhirsch** [comment]
I realized maybe you were asking if I could use the workaround. As noted above, `sharp().metadata()` doesn't work when the input is a raw buffer.

**Comment by lovell** [comment]
@mhirsch Do the forthcoming ImageDescriptor changes make raw pixel input work with `metadata()`? If it's OK with you, let's track this API-breaking change via #143.

**Comment by mhirsch** [comment]
Ah, yes. Metadata now works with raw buffers on the `pencil` branch. I'm happy to close this and track the api change on #143. Thanks!
