### ISSUE TITLE
How to prevent crash on unhandled errors when using streams?

### ISSUE THREAD

**Issue by dsine-de** [lovell/sharp#528]
Hi,

what is the recommended way of preventing a crash of the application if I'm using sharp as follows and the buffer data is undefined or has unsupported image data in it?
The 'error' event is not being fired in this case. Do I need to incorporate a try/catch block somehow?

````js
var pipeline = sharp()
.on('error', err => console.log('error'))
.pipe(fs.createWriteStream('filename.jpg'));

var readStream = new stream.PassThrough();
readStream.end(someBuffer);

readStream.pipe(pipeline);
````

When ```someBuffer``` is undefined, I get this error and the app crashes.

````
     Error: Input file is missing or of an unsupported image format
        at Error (native)
````

**Comment by lovell** [comment]
Piping `undefined` into a `sharp` instance will (currently) result in a zero-length Buffer being processed by libvips. This situation can be improved, but I would expect it to still emit the `error` event. I'll need to take a closer look.

**Comment by dsine-de** [comment]
Thank you - that helped a lot.

**Comment by papandreou** [comment]
`on` is chainable, but `pipe` returns the target (writable) stream, so the original snippet pipes the readable stream directly into the writable stream.

**Comment by afrozl** [comment]
I'm trying to follow this example, but I am clearly missing something as I am unable to trap the error. 
my pipeline looks like:
```
 var remoteWriteStream = bucket.file('assets/images/lead/' + file).createWriteStream({metadata: { contentType: 'image/jpeg'}});
 var pipeline = sharp('./public/images/tmp/' + file)
 .resize(1280, 800)
 .crop(sharp.gravity.north)
 .quality(85)
 .on('error', err => console.log('error');
 pipeline.pipe(remoteWriteStream)

sharp error: Error: Input file is missing or 
of an unsupported image format

**Comment by lovell** [comment]
@afrozl Perhaps try using an absolute path instead of the relative `./public/images/...` (as paths are relative to the working directory, which isn't always the same as the directory containing your script).

**Comment by afrozl** [comment]
Thanks, looks like I was receiving the error but not handling the unpipe correctly
