### ISSUE TITLE
Windows 10 gulp-responsive error

### ISSUE THREAD

**Issue by genyklemberg** [lovell/sharp#529]
Please, here you can find err log file. Can't use "npm install -save--dev gulp-responive".
[npm-debug.txt](https://github.com/lovell/sharp/files/384082/npm-debug.txt)

**Comment by lovell** [comment]
Hello, the salient error is:
```
7684 error Windows_NT 10.0.10586
7685 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose" "sharp"
7686 error node v4.4.5
7687 error npm  v2.15.9
7688 error code ELIFECYCLE
7689 error sharp@0.15.1 install: `node-gyp rebuild`
7689 error Exit status 1
```
Are node-gyp and its dependencies installed?

http://sharp.dimens.io/en/stable/install/#prerequisites

**Comment by lovell** [comment]
@genyklemberg Have you been able to make any progress?

**Comment by lovell** [comment]
Closing due to lack of updates. Feel free to re-open with more details if the problem persists.
