### ISSUE TITLE
Sharp Unstable and install slowly sometimes

### ISSUE THREAD

**Issue by djangogao** [lovell/sharp#530]
![image](https://cloud.githubusercontent.com/assets/12482872/17179858/439fa868-544d-11e6-9cc7-e566129da121.png)
![image](https://cloud.githubusercontent.com/assets/12482872/17179884/52e869f4-544d-11e6-90d7-e132645e7864.png)

![image](https://cloud.githubusercontent.com/assets/12482872/17180202/3d044f8a-544e-11e6-8c37-78c177416985.png)

ENV: Centos7 Aliyun Node Version4.4.5

**Comment by djangogao** [comment]
![image](https://cloud.githubusercontent.com/assets/12482872/17180132/ff0dacbc-544d-11e6-9e9c-8b807f799aaf.png)

**Comment by lovell** [comment]
I suspect this is due to (temporary?) network problems connecting to the [dl.bintray.com](https://github.com/lovell/sharp/blob/master/binding.js#L13) host via HTTPS.

**Comment by tianshaofandine** [comment]
@lovell We do frequently have the 'Module did not self register' problem in our servers hosted in Amazon EC2 during nightly build. Manually 'npm rebuild' will fix it. Have you ever seen this problem before?

Thanks

**Comment by lovell** [comment]
`Module did not self register` usually means the version of node used at `npm install` time is different to that used at run time - see #196

**Comment by lovell** [comment]
Closing this as I think everything has been covered. Please feel free to re-open if not.
