### ISSUE TITLE
I can not rebuild it in win10x64, who can offer some sugeestion?

### ISSUE THREAD

**Issue by shanyuk** [lovell/sharp#531]
`yp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\xiao\node_modules\sharp`

**Comment by lovell** [comment]
Please can you provide more of the error log.

**Comment by shanyuk** [comment]
Thank you,  I have solved it.  It is wrong with the node-gyp. I rebuild the node-gyp as https://github.com/nodejs/node-gyp#installation.  And   I set  the path :  set_ VCTargetsPath=C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0.
