### ISSUE TITLE
Digital stamps to search duplicated images

### ISSUE THREAD

**Issue by puzrin** [lovell/sharp#532]
I'm not 100% sure this request should be a part of "sharp", need your opinion.

There are many situations, when duplicated images should be detected. Those can be not binary egual - different resolution, cropped parts. I don't know all possible details, but algorithms are known and not secret http://stackoverflow.com/questions/75891/algorithm-for-finding-similar-images.

It would be interesting to have digital stamps for images. What do you think?

**Comment by lovell** [comment]
Hello Vitaly, the [phash-image](https://www.npmjs.com/package/phash-image) module provides bindings to the pHash library mentioned.

sharp's functional tests use a slightly altered version of the [dhash-image](https://www.npmjs.com/package/dhash-image) logic for image similarity matching - https://github.com/lovell/sharp/blob/master/test/fixtures/index.js#L13-L38

Both pHash and dHash are scale-invariant. In my limited testing I found dHash to be more accurate but have not tried either on a large corpus of images.

sharp also measures colour distance via [vips_dE00](http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-colour.html#vips-dE00) for tests where colour matters. There was talk of exposing this at #284.

**Comment by puzrin** [comment]
Thank you for overview of existing packages.

I think, there are no need to keep this ticket open here.
