### ISSUE TITLE
Change bits per channel

### ISSUE THREAD

**Issue by strarsis** [lovell/sharp#534]
Is there a feature in sharp for changing bits per channel (e.g. from 32bit or 16bit to 8bit) 
before processing/saving the loaded image?

**Comment by lovell** [comment]
At the end of the processing pipeline, before generating the output image, 16-bit pixel values are cast to 8-bit - see https://github.com/lovell/sharp/blob/master/src/pipeline.cc#L844

When you say 32-bits per channel, do you mean an 8-bit per pixel image with 4 channels? If so, you may be looking for quantisation, which is not supported.

**Comment by jdalton** [comment]
I ran into an issue with [compatibility with pngjs](https://github.com/niegowski/node-pngjs#documentation) for 
> As input any color type is accepted (grayscale, rgb, palette, grayscale with alpha, rgb with alpha) but 8 bit per sample (channel) is the only supported bit depth. Interlaced mode is not supported.

I too was wondering if there was a way to output a compatible png.

**Comment by lovell** [comment]
Hello @jdalton, the following code seems to produce PNG output images from `sharp` that can be parsed by `pngjs`, at least when testing locally with a few different formats from the [fixtures](https://github.com/lovell/sharp/tree/master/test/fixtures).

```javascript
const assert = require('assert');
const pngjs = require('pngjs');
const sharp = require('sharp');

const input = '5_webp_a.webp';
const width = 100;
const height = 100;
let channels = 0;

const pngParser = new pngjs.PNG();

pngParser
  .on('parsed', (data) => {
    assert.strictEqual(data.length, width * height * channels);
  })
  .on('error', (err) => {
    assert.ifError(err);
  });

const transcoder = sharp(input)
  .resize(width, height)
  .png();

transcoder.on('info', (info) => {
  channels = info.channels;
});

transcoder.pipe(pngParser);
```

Perhaps a particularly tricky or complex input image is causing problems?

**Comment by jdalton** [comment]
> Perhaps a particularly tricky or complex input image is causing problems?

Ah yeah. Turns out it was a OptiPNG process causing the issue.

**Comment by lovell** [comment]
@strarsis has your original question been answered?

**Comment by strarsis** [comment]
This was meant to be used to solve this issue: https://github.com/peterbraden/node-opencv/issues/436
So sharp should remove alpha-transparency completely, including the channel itself so opencv can handle the matching.

**Comment by lovell** [comment]
@strarsis If OpenCV's matchTemplate feature doesn't support an alpha-transparency channel then I'd suggest using [flatten()](http://sharp.dimens.io/en/stable/api/#flatten) to remove it.

**Comment by strarsis** [comment]
Thanks!
