### ISSUE TITLE
Extend the resize functionality

### ISSUE THREAD

**Issue by chamini2** [lovell/sharp#535]
I don't know if this is already doable with the current API, but I didn't find it in the docs.

I was looking for an option to pass to the `resize` function to match the first one of the two dimensions and scale the other one accordingly.

That means, if we had a `500x400` image and did `resize(200,200)` it would return a `250x200` image.

We could even expand the option to match either by minimum or maximum:

```js
resize(width, height, options)
```

`options` has the `kernel` and `interpolation` options and a new one:

- `match`: a string representing to match by minimum (`min`) or maximum (`max`) value.

***

That would mean that:

```js
image500x400.resize(200,200, {match: 'min'}) // = 250x200
image500x400.resize(200,200, {match: 'max'}) // = 200x160
image500x400.resize(800,800, {match: 'min'}) // = 1000x800
image500x400.resize(800,800, {match: 'min'}) // = 800x640
```

**Comment by lovell** [comment]
Hola Matteo, it sounds like you need the existing [min](http://sharp.dimens.io/en/stable/api/#min) and [max](http://sharp.dimens.io/en/stable/api/#max) options.
```javascript
image500x400
  .resize(200, 200)
  .min()
  .toBuffer(function(err, data, info) {
    // info.width=250, info.height=200
  });
```

**Comment by chamini2** [comment]
Well yes! I think I focused on the `resize` method exclusively in the docs. Thank you! 

PS: Isn't it weird that I even used `min` and `max` as the keywords to use?

**Comment by lovell** [comment]
Great. The API you describe, where the min/max/other "canvas" option becomes a third, optional Object-based parameter, is probably where things will move at some point in the future.
