### ISSUE TITLE
Should crop or resize be the fallback for min or max with only one of the two dimesion params?

### ISSUE THREAD

**Issue by chamini2** [lovell/sharp#536]
I find it counter-intuitive that the default behaviour for `max` and `min` is to `crop` the image. I would just like to understand the reasons for this decision.

IMHO it makes sense that if someone wants to crop they call the `crop` function, and only resize when `resize` is used.

Right now I'm currently checking like this:

``` js
function formatImage(buffer, width, height) {
  return Promise.resolve(sharp(buffer).clone())
    .then((image) => width || height ? image.resize(width, height) : image)
    .then((image) => width && height ? image.min() : image)
}
```

**Comment by lovell** [comment]
The docs for [max](http://sharp.dimens.io/en/stable/api/#max) and [min](http://sharp.dimens.io/en/stable/api/#min) state:

> "Both width and height must be provided via resize otherwise the behaviour will default to crop."

The utility of min and max is dependent on having two dimensions to work with, both the width and height. Cropping is not the default behaviour but rather a fallback behaviour should one dimension be missing.

Perhaps the docs could be clearer?

**Comment by chamini2** [comment]
> Perhaps the docs could be clearer?

I think it's clear; I understood what it does. I just was questioning if `crop` should be the _fallback_ (I wrongly used _default_ in my first comment) behaviour instead of `resize`.

**Comment by lovell** [comment]
Thanks for clarifying, your comment makes more sense now.

How would you expect it to behave if a dimension is missing?

**Comment by chamini2** [comment]
I would expect it to fallback to `resize`, by that I mean ike the docs say:

> `width` is the integral Number of pixels wide the resultant image should be, between 1 and 16383 (0x3FFF). Use `null` or `undefined` to auto-scale the width to match the `height`.
>
> `height` is the integral Number of pixels high the resultant image should be, between 1 and 16383. Use `null` or `undefined` to auto-scale the height to match the `width`.

**Comment by lovell** [comment]
Initially I'd like to at least add some test cases for this documented fallback behaviour to prove what it's really doing. We can then change it to behave as people would expect it to, as no one likes surprises :)

Thanks for bringing this to my attention.

**Comment by chamini2** [comment]
Sure thing! Thanks for the response.

If you want I could write those tests, let me know. 👍

**Comment by mikestopcontinues** [comment]
I would also expect the fallback to be resize. +1

**Comment by lovell** [comment]
v0.21.0 will deprecate the `min` and `max` functions in preference for a `fit` option on the `resize` operation and in doing so hopefully prevent the confusion discussed here  - see #1135 for details.
