### ISSUE TITLE
Meteor: "Unable to resolve some modules"

### ISSUE THREAD

**Issue by Nico-L** [lovell/sharp#537]
Hi,

I would like to use sharp for image manipulation in a meteor project I am working on. I add the sharp dependency in my package.json:
`"sharp": "^0.15.1"`

I didn't add any dependencies

When start the app, I have this error:
```
Unable to resolve some modules:

  "path" in /mnt/vdb/web/site-LBF/node_modules/sharp/index.js (web.browser)
  "util" in /mnt/vdb/web/site-LBF/node_modules/sharp/index.js (web.browser)
  "stream" in /mnt/vdb/web/site-LBF/node_modules/sharp/index.js (web.browser)
  "events" in /mnt/vdb/web/site-LBF/node_modules/sharp/index.js (web.browser)
  "./build/Release/sharp" in /mnt/vdb/web/site-LBF/node_modules/sharp/index.js (web.browser)
```

Theses modules are not the dependencies listed in the npm page. I tried to add the dependencies to the package.json:
```
"tar": "^2.2.1", 
    "request": "^2.74.0", 
    "semver": "^5.3.0", 
    "nan": "^2.4.0", 
    "color": "^0.11.3", 
    "bluebird": "^3.4.1",
    "sharp": "^0.15.1"
```
It doesn't change anything.

Am I missing any prerequisites ?

Thanks

**Comment by lovell** [comment]
Hello, those modules are provided by node.

https://github.com/meteor/node-stubs
https://guide.meteor.com/1.3-migration.html#modules

**Comment by Nico-L** [comment]
Hi Lovell,

Thanks, indeed installing node-stubs fixed the issue.

Now I have a different problem: 
```
Unable to resolve some modules:

  "./build/Release/sharp" in /mnt/vdb/web/site-LBF/node_modules/sharp/index.js (web.browser)
```

I have uninstalled and re-installed sharp several times with not much success, through package.json and manually `npm install sharp`. And indeed, there is no sharp directory under /build/Release/. I have looked into past issues here but nothing that helped me.

Would you have an idea?

Thanks

**Comment by lovell** [comment]
I have no experience of Meteor.

https://guide.meteor.com/using-npm-packages.html suggests `meteor npm install` should be run.

Is there any useful error or debug information when running `meteor npm install sharp`?

**Comment by Nico-L** [comment]
Thank you for having done these research. I tried npm install and meteor npm install. logSharpInstall is the verbose log of `meteor npm install --verbose`.
[logSharpInstall.txt](https://github.com/lovell/sharp/files/403479/logSharpInstall.txt)

The following log corresponds to the `meteor npm install sharp --verbose` command
[logSharpInstallManual.txt](https://github.com/lovell/sharp/files/403484/logSharpInstallManual.txt)

Oddly enough, this isn't much of a big red error.

Thanks

**Comment by lovell** [comment]
https://github.com/meteor/meteor/issues/6726 might be relevant but you're way beyond my knowledge of Meteor.

Let's leave this question open in case others can help.

**Comment by isjackwild** [comment]
Hey, having the same problem here — wondering if anyone's found a solution?

**Comment by ogermann** [comment]
same here

**Comment by Nico-L** [comment]
I did not find any solution. I ended up using the cfs:imagemagicks Meteor package

**Comment by isjackwild** [comment]
I found a 'solution':

`$ cd node_modules/sharp/build/Release`
`$ ln -s sharp.node sharp`

**Comment by ogermann** [comment]
I took Nico-L' way and switched to graphicsmagick... works fine

**Comment by lovell** [comment]
Thank you @isjackwild, your workaround has just provided the inspiration for a solution.

It looks like Meteor doesn't add the `.node` extension in its (custom?) implementation of `require()` like Node does - https://nodejs.org/api/all.html#addons_loading_addons_using_require

Changing https://github.com/lovell/sharp/blob/master/index.js#L12 to explicitly include the `.node` might fix this.

```diff
- var sharp = require('./build/Release/sharp');
+ var sharp = require('./build/Release/sharp.node');
```

I'll need to test this to ensure everything else still works cross-platform.

**Comment by isjackwild** [comment]
Awesome news! Fingers crossed that works…

I spent hours trying to figure this one out. ;)


On 5 Oct 2016, at 10:23, Lovell Fuller <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you @isjackwild<https://github.com/isjackwild>, your workaround has just provided the inspiration for a solution.

It looks like Meteor doesn't add the .node extension in its (custom?) implementation of require() like Node does - https://nodejs.org/api/all.html#addons_loading_addons_using_require

Changing https://github.com/lovell/sharp/blob/master/index.js#L12 to explicitly include the .node might fix this.

- var sharp = require('./build/Release/sharp');
+ var sharp = require('./build/Release/sharp.node');

I'll need to test this to ensure everything else still works cross-platform.

**Comment by lovell** [comment]
Commit 739178d explicitly adds the `.node` extension that is lacking in Meteor's `require()` implementation, intentionally or otherwise.

Everything appears to still work when `require()`d by Node on Linux, OS X and Windows.

Is anyone able to test this with Meteor?

**Comment by lovell** [comment]
This enhancement is in v0.16.1, now available via npm.
