### ISSUE TITLE
Paste an extracted region

### ISSUE THREAD

**Issue by applefreak** [lovell/sharp#541]
Hello, I want to do something that I'm not sure if it's possible with this library. I've done this using `node-canvas` but I think there's better/faster library for the job.

I want to extract a part of an image (like a strip), then paste it to a new drawing area. Then extract another strip and paste besides the first strip. 

I think extracting is not the problem, but the idea of "drawing area" and "pasting" is something I'm not familiar with this library. Can someone give me some pointers?

Thanks!

**Comment by lovell** [comment]
Hello, you'll probably want to experiment with multiple calls to [extract](http://sharp.dimens.io/en/stable/api/#extract-left-left-top-top-width-width-height-height), "saving" the outputs to a [raw](http://sharp.dimens.io/en/stable/api/#raw) pixel format, then using these as an input in combination with [extend](http://sharp.dimens.io/en/stable/api/#extendextension) and [overlayWith](http://sharp.dimens.io/en/stable/api/#overlaywithimage-options) to assemble a final image.

**Comment by lovell** [comment]
Feel free to re-open with more details if there are related questions.

**Comment by tannerhodges** [comment]
In case others find this looking for examples of how to copy/paste images with sharp, I ended up using the [`clone`](http://sharp.dimens.io/en/stable/api-input/#clone) method keep the extracted area separate from the initial image:

```js
let image = sharp(file.contents);

// Get image info for calculating `overlayWith` coordinates
image.metadata((error, imageInfo) => {
  // Copy image and extract 100x100 area from top left corner
  return image.clone().extract({ left: 0, top: 0, width: 100, height: 100 })
    // "Save" extracted area
    .toBuffer((error, copy, copyInfo) => {
      // Extend image to fit copy in bottom right corner
      return image.extend({ top: 0, right: copyInfo.width, bottom: copyInfo.height, left: 0 })
        // Paste copy in bottom right corner
        .overlayWith(copy, { left: imageInfo.width, top: imageInfo.height })
        // Hand off final image to pipeline
        .toBuffer(function(error, output, info) {
          callback(null, output);
        });
    });
});
```

I was working on a gulp plugin so I kept the final image in a buffer, but if you just want to save the file directly you can replace that last `toBuffer` with a call to `toFile`:

```js
        // Save to file
        .toFile('output.jpg', function(err, info) {
          callback(null, file);
        });
```

For reference, [here's the final code I ended up using](https://github.com/tannerhodges/gulp-zorrosvg/blob/a094d75ab3f91e159c5febe15bffacfb65df09a2/index.js#L46-L86).

Thanks @lovell for all your work on sharp. Really appreciate it.
