### ISSUE TITLE
BMP file

### ISSUE THREAD

**Issue by keithics** [lovell/sharp#543]
Hello guys,

I am having issues with BMP file.
http://ilab.engr.utk.edu/ilabdocs/Epilog/BMP%20sample%20files/test.bmp

	Unhandled rejection Error: Input file is missing or of an unsupported image format
	at Error (native)
	From previous event:

it works okay on my mac but fails in ubuntu/centos. Am i missing something?

**Comment by lovell** [comment]
Hello, BMP input support in libvips is provided via *magick. The pre-built binaries, as used by Linux, do not include this, hence the messages you're experiencing. If you need support for BMP images on Linux, please (globally) install your own copy of libvips.

**Comment by lovell** [comment]
Closing. Feel free to re-open with more details if (related) questions remain.

**Comment by hbakhtiyor** [comment]
@lovell how about supporting output?

**Comment by lovell** [comment]
@hbakhtiyor Please use [raw](http://sharp.dimens.io/en/stable/api-output/#raw) output with a module like https://github.com/shaozilee/bmp-js
