### ISSUE TITLE
no libvips support for sharp on Amazon EC2 (AMI) server

### ISSUE THREAD

**Issue by ilagace** [lovell/sharp#544]
My nodejs code (plus sharp) is working fine on my Windows development machine.  The same code (and images) are not working when deployed on my AWS AMI server.

I am getting Error: Input file is of an unsupported image format when handling a jpeg file

I have checked the path by opening the same file with fsReadSync(path) and it works fine.

When I do console.log(sharp.format) I get:

{ jpeg:
   { id: 'jpeg',
     input: { file: false, buffer: false, stream: false },
     output: { file: false, buffer: false, stream: false } },
  png:
   { id: 'png',
     input: { file: false, buffer: false, stream: false },
     output: { file: false, buffer: false, stream: false } },   etc...

My guess was that I had a problem with my sharp/vips installation.

Since it is a recent Linux distribution:

Linux 4.4.14-24.50.amzn1.x86_64 x86_64
Amazon Linux AMI release 2016.03

I followed the standard sharp Linux installation instructions on http://sharp.readthedocs.io/en/stable/api/ but since vips was not present on the server I had to install it manually.  I got version 8.3.1 in a tarball and installed it.  Installation went OK (no error message).

I installed sharp after that and it went fine.  
Nodejs var sharp = require('sharp') is fine.

vips got installed in /usr/local/bin so I had to create a usrlocal.conf file in /etc/ld.so.conf.d and run sudo ldconfig to fix that.

After a lot of research if found I had to do some work so I could get the following:

$ vips --version
vips-8.3.1-Mon Aug 15 19:14:10 UTC 2016 

$ pkg-config --modversion vips-cpp
8.3.1

after doing
$ export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

So now I am stuck with the above error and incorrect sharp.format settings

I would like to re-install the whole lot but I do not know how-to.  I tried:

npm uninstall sharp
npm install sharp

No joy!  No error whatsoever...

Log:

> sharp@0.15.1 install /home/ec2-user/node_modules/sharp
> node-gyp rebuild

make: Entering directory `/home/ec2-user/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
  CXX(target) Release/obj.target/sharp/src/sharp.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  SOLINK_MODULE(target) Release/obj.target/sharp.node
  COPY Release/sharp.node
  TOUCH Release/obj.target/win_copy_dlls.stamp
make: Leaving directory `/home/ec2-user/node_modules/sharp/build'
sharp@0.15.1 node_modules/sharp
├── semver@5.3.0
├── color@0.11.3 (color-convert@1.4.0, color-string@0.3.0)
├── nan@2.4.0
├── bluebird@3.4.1
├── tar@2.2.1 (block-stream@0.0.9, fstream@1.0.10)
└── request@2.74.0 (aws-sign2@0.6.0, forever-agent@0.6.1, oauth-sign@0.8.2, caseless@0.11.0, is-typedarray@1.0.0, aws4@1.4.1, extend@3.0.0, tough-cookie@2.3.1, qs@6.2.1, combined-stream@1.0.5, form-data@1.0.0-rc4, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)

In some place I found some instructions to put a libvips tarpall in sharp/packaging and redo the install but it is not recommended...  I just want to use the standard libvips anyway...??

Should I use the command:
curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | sudo bash -
but this is deprecated...??

I am lost as I have libvips installed but I think that sharp does not see it (incorrect settings).  Any idea on how to re-install the whole lot properly?

Thanks!

**Comment by ilagace** [comment]
OK found the problem.

When vips is installed manually you have to also install the individual "image libraries" separately for each type of image (jpg, png, tiff, etc...).  One must watch carefully when typing $ ./configure in vips folder before installing.  You get some warnings in the mass of information being dumped.

You still have to find which library is available for each distribution.  Anyway jpeg on AWS is called jpeg-turbo-devel (not jpeg-turbo8-dev as mentioned in the vips documentation).  I have to check the others as needed in future.

You have to reinstall vips after that.

I will leave this here for others who might have the same issue in future...

Problem resolved as the jpeg flags are set properly in sharp.format now and I can resize my files...

**Comment by lovell** [comment]
> "since vips was not present on the server I had to install it manually"

I'm interested to know what made you think you *had* to install libvips? sharp downloads and uses its own pre-built libvips if not already present.  Perhaps the documentation needs to be made clearer in this regard?

**Comment by ilagace** [comment]
Good question.  I have to remember what happened yesterday morning... lol

At first during the install:

$ npm install sharp 

I had to install gcc-c++ to be able to rebuild node-gyp.  I was getting quite a few errors initially.  Even after installing node-gyp via npm install.

One thing for sure I was getting the "Error: Input file is of an unsupported image format"
At that point since I did not know where to look for I began a long and exhaustive search on google leading me to vips not being installed...

So one post on  the Internet was telling me to check for 

$ vips --version 

and since I was not getting anything I thought I had to install vips to get the libraries.  This is what I did.

But you are right maybe viplibs was installed already, I do not know.

But if viplibs was installed already... I guess I was still missing the jpeg-turbo-devel library??  Or do you normally install that library with viplibs too?

As you can see I am still confused.  It took me a long time to find the sharp.format command as well.  I had seen in the doc but it was not obvious to use it for debugging the error I had.

Maybe a few spotcheck in the install instructions would help guys like me such as:

check viplibs is installed
check jpeg support
check png support, etc...
check sharp.format in nodejs

Anyway, just a suggestion as your doc is already much better than most nodejs modules...

And your module is working perfectly now on AWS.  Thanks!

**Comment by lovell** [comment]
If sharp finds a global installation of libvips of at least a [suitable minimum version](https://github.com/lovell/sharp/blob/master/package.json#L84) then it will use that in preference to downloading and using its own local copy. There's no check for which formats are available in the globally-installed version.

The libraries and therefore formats made available by the pre-compiled binaries are listed at http://sharp.dimens.io/en/stable/install/#licences

I feel information about compiling libvips from source with/without certain formats is more within the scope of libvips' own documentation, for the benefit of all its users and not just sharp-based users.

Glad to hear you got it all working in the end!

**Comment by klemensz** [comment]
@ilagace How did you solve it in the end?

I also get the `Error: Input file is missing or of an unsupported image format` on Amazon Linux (AMI release 2017.03).
