### ISSUE TITLE
Clarification/bug: Using raw pixels as input format

### ISSUE THREAD

**Issue by strarsis** [lovell/sharp#545]
In order to 'realize' some sharp operations, the sharp image instance 
has to be outputted to buffer and fed back as input for a new sharp image instance.

For less overhead and simplicity, I want to use raw pixel format instead the default one (png).
However, in contrast to using e.g. png as format for the intermediate buffer contents, 
raw pixel doesn't seem to work - an exception is thrown when using it as input.

Edit: I added some promise handling so second sharp call has a chance of complaining all the time:
```js
var sharp = require('sharp');

sharp('./input.jpg')
.raw().toBuffer()
.then(function(rawBuf) {
  return sharp(rawBuf) // unsupported image format error
          .metadata();
})
.then(function(info) {
  console.log(info);
});
````
````
[...]Input file is missing or of an unsupported image format
         at Error (native)

````

**Comment by lovell** [comment]
Hello, the `width`, `height` and `channels` are required as additional parameters for raw pixel input as the Buffer contains only the pixel values.

Luckily the second parameter of the `toBuffer` callback contains what you need:

```javascript
sharp('./input.png')
  .raw()
  .toBuffer(function(data, info) {
    sharp(rawBuf, { raw: info })...
  });
```
http://sharp.dimens.io/en/stable/api/#sharpinput-options

**Comment by strarsis** [comment]
But when I use the promise, there is only one parameter passed from it, namely only the pixel values.
Wouldn't it make sense adding the info parameter also to the parameters passed?

``js
var sharp = require('sharp');

sharp('./input.jpg')
.raw().toBuffer()
.then(function(rawBuf, rawInfo) {
  console.log(typeof rawBuf, typeof rawInfo); // object undefined
});
````

**Comment by lovell** [comment]
Please see #143

**Comment by strarsis** [comment]
A realize() method could help a bit. When the changes can be directly applied in-place, 
there would be less to no need using the raw() approach.

**Comment by lovell** [comment]
Did you see #241?
