### ISSUE TITLE
withMetadata not add sRGB profile to metadata

### ISSUE THREAD

**Issue by vlapo** [lovell/sharp#546]
Hi lovell, 

I have problem add sRGB profile to images originally without them using withMetadata() function.
```javascript 
sharp('./input.png')
    .resize(1000,1000)
    .max()
    .withMetadata()
    .toFile('output.png');
```
Where `input.png` is PNG without embeded profile in RGB colourspace. After I check metadata of `output.png` there is no profile:
```javascript
sharp('./output.png')
    .metadata(function(err,metadata){
        console.log(metadata);
    });
```
`output.png` metadata:
```javascript
{ format: 'png',
  width: 778,
  height: 1000,
  space: 'srgb',
  channels: 4,
  density: 72,
  hasProfile: false,
  hasAlpha: true }
```
`input.png` metadata:
```javascript
{ format: 'png',
  width: 5444,
  height: 7000,
  space: 'srgb',
  channels: 4,
  density: 72,
  hasProfile: false,
  hasAlpha: true }
```
Acording to documentation I think it will add embeded profile to output.png. 
> Include all metadata (EXIF, XMP, IPTC) from the input image in the output image. This will also convert to and add the latest web-friendly v2 sRGB ICC profile.

**Environment:**
Windows 10, I tested it on sharp v0.16 and v0.15 with the same result. Node v4.4.1

It's a bug or am I just misunderstood documentation?

**Comment by lovell** [comment]
Hello, the [current logic](https://github.com/lovell/sharp/blob/master/src/pipeline.cc#L682-L683) is to only include a profile in the output if there's a profile in the input.

The documentation is ambiguous in the case of an input with no profile, which is the scenario you've run into. Perhaps for now the simple "fix" is to clarify the current behaviour in the docs.

I think PNG uses sRGB as the default colourspace so a lack of sRGB profile shouldn't matter - I'd be interested to know how well/badly browsers handle PNGs with profiles :)

The `withMetadata` option is probably due for a revisit to improve the control around which items of metadata are to be included.

**Comment by vlapo** [comment]
I understand. I ask this question because we have some case where our users upload various images, and we need to have sRGB profile included if there is not in the original. Sure browsers don't have any problem with these PNGs. But our print provider has. Mainly we solve it by communication with our print provider and manual steps, but I want to solve it by embed profile to PNG programmatically by default in future.

Do you know any method or node package with this functionality?

**Comment by lovell** [comment]
The work to add an ICC profile if none if present probably makes most sense being tracked under the existing #218, which also happens to have its origins in a print-related request :)

**Comment by lovell** [comment]
Closing - let's track this in #218.
