### ISSUE TITLE
Confusion over documentation location

### ISSUE THREAD

**Issue by philmander** [lovell/sharp#548]
I've managed to find the documentation for Sharp in two different places.

http://sharp.dimens.io/en/stable/install/
http://sharp.readthedocs.io/en/stable/install/

The Read The Docs version seems out of date. Sorry, I'm not actually sure how I found the the link to the RTD version, but I thought I'd point out the disparity. 

---

On a side note, I'm temporarily using my wife's Macbook Air (Yosemite 10.10.5) and I've noticed that I have to manually install lib vps for Sharp 0.15.1 to work, unlike stated in the latest docs. I'm sure on my regular computer (Ubuntu 14.04) this, as expected, wasn't necessary. Shall I raise this as a separate issue?

**Comment by lovell** [comment]
Hi Phil, I think those two hostnames should both CNAME resolve to the same place - I'll need to read the Read The Docs docs to check - perhaps there's a stale cached version somewhere?

Please can you try v0.16.0 as it is the [first version](http://sharp.dimens.io/en/stable/changelog/#v0160-18th-august-2016) to remove the need to manually install libvips on OS X.

**Comment by philmander** [comment]
0.16 now works nicely without libvps being preinstalled.

I think it was just coincidental that I was looking up the docs around 0.16 being released and a cache was stale somewhere.

Thanks
