### ISSUE TITLE
Pipe buffer image data into Uint8ClampedArray format

### ISSUE THREAD

**Issue by abagshaw** [lovell/sharp#549]
Thought I would post http://stackoverflow.com/questions/39087314/node-js-pipe-buffer-image-data-into-uint8clampedarray-format here as well.

I am trying to pipe image data into a function that I have been successfully using in the browser.

The code in the browser is as follows

    var myImageData = context.getImageData(0, 0, width, height);
    var gray = tracking.Image.grayscale(myImageData.data, width, height);

That works just fine and from what I understand appears to be generating an ImageData object from an image in the `canvas`. The `.data` property of the ImageData object appears to be a `Uint8ClampedArray` that reads `[r1, g1, b1, a1, r2, g2, b2, a2.....]` Looking at the pattern, every fourth number is `255` which makes sense as none of the image is transparent at all.

I am trying to get this to work in Node.JS in a similar fashion, except I am getting my image data from a buffer generated by smarp see code below:

    sharp(body)
        .resize(newWidth, newHeight)
        .raw()
        .toBuffer(function (err, buffer, info) {
            var gray = tracking.Image.grayscale(buffer, newWidth, newHeight);
        });

The problem is - this clearly doesn't work. I can't pass the buffer directly to the function. I've tried a ton of things and the only process that actually shows me an array is `buffer.toJSON().data`. Looking at that the numbers are all at or below 255, however I can't see any *every fourth number is 255* pattern which indicates something is wrong.

---

**My question is:**

How can I get an `Uint8ClampedArray` with the proper `[r1, g1, b1, a1, r2, g2, b2, a2.....]` formatting from the image buffer in node that I can then pass to my function?

---

I can see there are other buffer encoding methods like `.png()` or `.jpeg()` but neither of those have worked for me and I would assume that the `.raw()` function which I am currently using would give me what I want. Any help is much appreciated!

**Comment by lovell** [comment]
> "I can't see any every fourth number is 255 pattern which indicates something is wrong."

Hello, does the input (`body` in your example) contain an alpha transparency channel?

**Comment by abagshaw** [comment]
That was my problem. I assumed that the output would contain a transparency channel regardless of my input. Sorry for the trouble.
