### ISSUE TITLE
Change opacity/alpha

### ISSUE THREAD

**Issue by strarsis** [lovell/sharp#554]
It would be great if the opacity/alpha of a sharp image instance could be directly changed, 
e.g. making it semitransparent, putting out as raw to buffer and overlaying another image with it.
(Also useful for visually debugging overlay compositions).

**Comment by lovell** [comment]
Hello, a possible workaround for this might be to overlay with a raw pixel buffer containing tiled, semi-transparent pixel value, something like the following (untested):

```javascript
sharp(input)
  .overlayWith(
    new Buffer([0, 0, 0, 128]),
    { tile: true, raw: { width: 1, height: 1, channels: 4 } }
  )...
```

**Comment by strarsis** [comment]
Thanks. Though an API method could be more intuitive.

**Comment by strarsis** [comment]
```js
sharp(input)
  .overlayWith(
    new Buffer([0, 0, 0, 128]),
    { tile: true, raw: { width: 1, height: 1, channels: 4 } }
  )
````
The code works insofar that it adds an alpha channel - 
but the output image is now different compared to the input image, much darker.

When I remove tile: true there will be still one pixel changed - 
but the output image should be identical to input image plus an alpha channel.

**Comment by lovell** [comment]
Hello, `[0, 0, 0, 128]` was an example of adding a semi-transparent alpha channel. If you want it to be fully-transparent, you can use `[0, 0, 0, 0]`.

If you know the image dimensions then an alternative method of adding a fully-transparent alpha channel is by passing a zero-filled Buffer to [joinChannel](http://sharp.dimens.io/en/stable/api/#joinchannelchannels-options), for example (untested):

```javascript
sharp(input).joinChannel(Buffer.alloc(width * height), {
  raw: {
    width: width,
    height: height,
    channels: 1
  }
})...

```

**Comment by stefanobaldo** [comment]
It would be possible to do this with an image preserving its transparency? When I try to change the opacity of a transparent png using this method I end up with a rectangle around the image, like this:

![opacity](https://user-images.githubusercontent.com/1918151/31343923-8bec21e8-ace7-11e7-9ca0-155584515de3.png)

Actually what I need is to dissolve an image into another by a given percent (like IM/GM dissolve).
Is there any way of doing this?

**Comment by stefanobaldo** [comment]
@lovell Could you help me with this? ☝️ 😄

**Comment by quinton-ashley** [comment]
I can't get join channel to work for me.  It seems to make the whole image clear, I just want to add an alpha channel.  It would be nice to just have a dedicated method like `img = sharp(file).addAlpha();`
```
	let img, meta;
		try {
			img = sharp(file);
			meta = await img.metadata();
			img = await img.joinChannel(Buffer.alloc(meta.width * meta.height), {
				raw: {
					width: meta.width,
					height: meta.height,
					channels: 1
				}
			});
		} catch (err) {
			error(err);
			return;
		}
		const {
			data,
			info
		} = await img.raw().toBuffer({
			resolveWithObject: true
		});
		let imageData = {
			width: info.width,
			height: info.height,
			data: data
		};
		let svgstring = ImageTracer.imagedataToSVG(imageData, 'Detailed');
```

**Comment by lovell** [comment]
Rather than dealing with raw data and Buffer allocation, something like the following might be a bit simpler (`create` was added in [v0.17.3](http://sharp.pixelplumbing.com/en/stable/changelog/#v0173-1st-april-2017)).

```javascript
.joinChannel({ create: { background: 'black', channels: 1, width, height } })
```

**Comment by quinton-ashley** [comment]
Why even make it that verbose though?  If someone is adding an alpha channel to an image it must be for the entire image.  You can't selectively make one part of the image RGB format and another RGBA format.

**Comment by lovell** [comment]
@quinton-ashley I've created #1153 for this suggestion; PRs always welcome.

**Comment by slavafomin** [comment]
Hello!

I was also looking for a simple method to change the image transparency, but couldn't find one.

Why is this issue closed and why is it classified as a question? I think it's a perfectly valid feature request. @lovell 

I would really like to see this in the library. Thank you for your hard work.

**Comment by lovell** [comment]
@slavafomin This feature request is being tracked at #618
