### ISSUE TITLE
How to use the VIPS library from Microsoft Visual C++ project?

### ISSUE THREAD

**Issue by alonit** [lovell/sharp#556]
Hi,

 I am looking for a way to build a short program (compile and link) that uses the VIPS C++ API library on top of Windows 7.

The program is Visual C++ Win32 Console Application running under Visual Studio 2015 project, VC14, in Windows 7 64bit station - After short investigation it turns out that sharp have a way to do it.

It would be greatly appreciated if you can point me to stuff that can help me implement this - An MSVC project file that builds the VIPS C++ API will be greatly useful for me.

Thanks.

**Comment by lovell** [comment]
Cross-posted at https://github.com/jcupitt/libvips/issues/508 so closing.
