### ISSUE TITLE
Is sharp blocking?

### ISSUE THREAD

**Issue by RichardJECooke** [lovell/sharp#557]
Does sharp block the event loop, or does it use timeouts every few milliseconds while processing?

Otherwise someone uploading a big file will hang our server for a few seconds while it resizes.

This isn't mentioned in the performance section of the API, where it would be nice to see.

**Comment by lovell** [comment]
http://sharp.dimens.io/en/stable/#fast says

> "Everything remains non-blocking thanks to libuv, no child processes are spawned..."

Does this answer your question?

Perhaps the "performance" section of the docs should be renamed "benchmarks tests" to clarify its role?

**Comment by lovell** [comment]
Feel free to re-open if your question has not been answered.
