### ISSUE TITLE
Accept svg string

### ISSUE THREAD

**Issue by strarsis** [lovell/sharp#558]
Edit: The string containing the SVG file contents must be converted to a buffer first, 
it would be nice if sharp also converts a SVG file to string to buffer.

**Comment by lovell** [comment]
Hello, string-based input is used for filesystem paths. I'm not convinced content sniffing is the way to go here given the simplicity of a `sharp(new Buffer(svg))...` wrapper.

**Comment by sultanmyrza** [comment]
@lovell suggestion worked for me
```javascript
const png = await sharp(Buffer.from(svg)).png().toBuffer();
const image = await loadImage(png);
```
