### ISSUE TITLE
[Error: im_local_dmask: nonsense mask parameters] When using convolve()

### ISSUE THREAD

**Issue by abagshaw** [lovell/sharp#561]
I am trying to do a simple sobel edge filter with the below code. When I trigger the request I get the following error `[Error: im_local_dmask: nonsense mask parameters]` and nothing is returned in the `buffer`. What am I doing wrong?

    app.get('/', function (req, res) {
        var requestOptions = { encoding: null, uri: "https://hd.unsplash.com/photo-1470214304380-aadaedcfff84" };
        var imgReq = request(requestOptions, function (error, response, body) {
         sharp(body)
             .resize(1000)
             .convolve({
                 width: 3,
                 height: 3,
                 kernel: [-1, 0, 1, -2, 0, 2, -1, 0, 1]
            })
            .webp()
            .toBuffer(function(err, buffer) {
                console.log(err);
                res.end(buffer, 'binary');
            });
        });
    });

**Comment by lovell** [comment]
Hello, I wonder if this is because the default "scale" for a mask is calculated by adding up all the kernel values, which in this case results in zero. Are you able to try adding `scale: 1` to the convolve parameters to work around this?

**Comment by abagshaw** [comment]
Perfect! That worked. Thanks so much. Maybe you want to change the docs to include the `scale: 1`

http://sharp.dimens.io/en/stable/api/#convolvekernel

Thanks again!

**Comment by lovell** [comment]
Thanks for confirming there's a (temporary) workaround. Rather than make the API more complex than it needs to be, I'm inclined to automagically clamp the `scale` to a minimum value of 1; leave it with me.

**Comment by lovell** [comment]
Commit af9d09f clamps the kernel scale to a minimum value of 1, plus adds the documented horizontal Sobel operator example as a test. Thanks for reporting this!

**Comment by lovell** [comment]
This fix is in v0.16.1, now available via npm.
