### ISSUE TITLE
Clean up/destroy sharp instances

### ISSUE THREAD

**Issue by strarsis** [lovell/sharp#571]
Is it possible explicitly clean up/destroy a sharp instance (when it is not needed anymore)?

**Comment by lovell** [comment]
A sharp instance is a standard JavaScript Object and therefore will be subject to garbage collection when no references remain.

libvips cache can be cleared via `sharp.cache(false)` - see http://sharp.dimens.io/en/stable/api/#sharpcacheoptions

**Comment by lovell** [comment]
Feel free to re-open if there are still further questions related to this.

**Comment by beenotung** [comment]
This 

> A sharp instance is a standard JavaScript Object and therefore will be subject to garbage collection when no references remain.

We may mention this in the documentation and readme. I was in doubt if I need to explicitly call the destroy() method to free up the resources. (And didn't saw mention on this method in the documentation website and the readme)
