### ISSUE TITLE
npm install fails for sharp in centos 6.4

### ISSUE THREAD

**Issue by mxshrestha** [lovell/sharp#572]
I installed sharp using the curl command, setup the pkg-config path to env. However when i run npm install i get following exception:
```
make: Entering directory `/usr/local/image-service-master/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
../src/pipeline.cc: In member function ‘virtual void PipelineWorker::HandleOKCallback()’:
../src/pipeline.cc:904:9: error: ‘GStatBuf’ was not declared in this scope
         GStatBuf st;
         ^
../src/pipeline.cc:904:18: error: expected ‘;’ before ‘st’
         GStatBuf st;
                  ^
../src/pipeline.cc:905:40: error: ‘st’ was not declared in this scope
         g_stat(baton->fileOut.data(), &st);
                                        ^
make: *** [Release/obj.target/sharp/src/pipeline.o] Error 1
make: Leaving directory `/usr/local/image-service-master/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-431.17.1.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/image-service-master/node_modules/sharp
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 2.6.32-431.17.1.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.16.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.16.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.
```

**Comment by lovell** [comment]
Hello, I no longer test on Centos 6, but I suspect the version of glib it provides may be quite old.

`src/pipeline.cc:904:9: error: ‘GStatBuf’ was not declared in this scope` is the salient error here.

My best guess would be that we might have to add `#include <glib/gstdio.h>` near the top of [src/pipeline.cc](https://github.com/lovell/sharp/blob/master/src/pipeline.cc). Are you able to make this change locally to see if it fixes it for you?

**Comment by mxshrestha** [comment]
@lovell adding the include did not help at all.

**Comment by lovell** [comment]
Which version of glib2 is installed? It should be at least [v2.28.8](https://pkgs.org/centos-6/centos-x86_64/glib2-2.28.8-5.el6.x86_64.rpm.html) and running `yum list installed | grep glib2` will confirm.

**Comment by mxshrestha** [comment]
Ah. i have 2.22.5.
```
glib2.x86_64                            2.22.5-7.el6            installed       
glib2-devel.x86_64                      2.22.5-7.el6            @base
```
how do i install latest?

**Comment by lovell** [comment]
Probably `yum update glib2-devel` but Google is your friend from here, good luck!

**Comment by mxshrestha** [comment]
yea. Thanks @lovell . i will update glib and see how it goes.

**Comment by mxshrestha** [comment]
updating glib fixed it. Thanks!

**Comment by cybercoder** [comment]
'''
[root@dev karnoAPI]# npm install --save sharp

> sharp@0.18.2 install /root/karnoAPI/node_modules/sharp
> node-gyp rebuild

make: Entering directory `/root/karnoAPI/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
make: g++: Command not found
make: *** [Release/obj.target/sharp/src/common.o] Error 127
make: Leaving directory `/root/karnoAPI/node_modules/sharp/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.0-327.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/karnoAPI/node_modules/sharp
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN karno@1.0.0 No description
npm WARN karno@1.0.0 No repository field.
npm WARN karno@1.0.0 license should be a valid SPDX license expression

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.18.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.18.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-08T09_55_09_763Z-debug.log
'''
CentOS 7 and i did install gcc,python 2.7 and glib2-devel
