### ISSUE TITLE
overlayWith fails with some grayscale base PNG

### ISSUE THREAD

**Issue by strarsis** [lovell/sharp#574]
When using some grayscale PNGs (like the grayscale sample 
'basn0g02 - 2 bit (4 level) grayscale' from [pngsuite](http://www.schaik.com/pngsuite/pngsuite_bas_png.html)). 
as base ("surface/target") for overlaying, an exception occurs:
````
Unhandled rejection Error: linear: vector must have 1 or 2 elements                                                                                                                                                                                 at Error (native) 
````

**Comment by lovell** [comment]
Hello, I've not been able to reproduce this. 

![](https://cloud.githubusercontent.com/assets/210965/18568902/7932f63a-7b97-11e6-9cdd-b4836f4e5a04.png) is the output when overlaying http://www.schaik.com/pngsuite/basn0g02.png with http://www.schaik.com/pngsuite/tbgn2c16.png via:
```javascript
sharp('basn0g02.png').overlayWith('tbgn2c16.png')...
```


Are you able to share a code fragment that generates this error?

**Comment by strarsis** [comment]
This happened during development, if this issue occurs again, I will post code to reproduce it.
