### ISSUE TITLE
Enhancement: expose libvips' VImage format (bit depth) in existing metadata function

### ISSUE THREAD

**Issue by moedusa** [lovell/sharp#577]
Hello,

Is it possible somehow to figure out color bit depth of an image with metadata() call?

**Comment by lovell** [comment]
Hello, this is not available at present, although it should be relatively easy to add.

Note to implementer: the libvips C++ API exposes this via the `VImage::format()` method, but perhaps we should expose the string value of the VIPS_FORMAT enum mapping in a `depth` attribute.

**Comment by jcupitt** [comment]
You can also use `VImage::get_int("format")` and get the enum value as an int. A string is probably more useful though, as you say.

**Comment by lovell** [comment]
Commit 95850d7 on the [ridge](https://github.com/lovell/sharp/tree/ridge) branch adds this feature, which will be included in v0.18.0.

**Comment by lovell** [comment]
v0.18.0 now available.
