### ISSUE TITLE
Question - Why do I constantly get "Input buffer contains unsupported image format"

### ISSUE THREAD

**Issue by afgallo** [lovell/sharp#578]
I might be doing something wrong but I keep getting the error above. I've reviewed the docs for [input stream](http://sharp.readthedocs.io/en/stable/api/#input) as well as #220, followed all suggestions and still can't get this to work. My backend code is below:

```
//image-processor.js
import Sharp from 'sharp';
import Hoek from 'hoek';

class ImageProcessor {
    constructor(imageBuffer) {
        Hoek.assert(imageBuffer, 'You need to provide a buffer.');
        Hoek.assert(Buffer.isBuffer(imageBuffer), 'Invalid buffer.');
        this._transformer = Sharp(imageBuffer);
        //console.log(Sharp.format);
    }

    resize(width, height) {
        Hoek.assert(Hoek.isInteger(width), 'Width needs to be an integer.');
        Hoek.assert(Hoek.isInteger(height), 'Height needs to be an integer.');

        return this._transformer.resize(width, height).toBuffer();
    }
}

module.exports = exports = ImageProcessor;
```

```
   //model.js
      if (photo) {
              const processor = new ImageProcessor(photo);

              processor.resize(750, 750).then((outputBuffer) => {

                  model.set('photo', outputBuffer);

                  resolve();
             }).catch((err) => {

                  reject(err);
              });
          }
```

My javascript client sends the "photo" parameter as a base64 encoded string like below:

```
{
  photo: "
"ÿØÿàJFIF``ÿáDExifMM*&z ²1&¾2äiøên¬êPhoto Editor 10.0.10011.16384"
}
```

Any help would be very appreciated. Thanks.

**Comment by lovell** [comment]
Perhaps `photo` is a Buffer containing a base64 encoded string?
````javascript
const photoBufferConvertedFromBase64 = Buffer.from(photo.toString(), 'base64');
const processor = new ImageProcessor(photoBufferConvertedFromBase64);
...
```

**Comment by afgallo** [comment]
Hi @lovell, thanks for your prompt response. Yes, it is. Made changes as per your example above but am still getting the same issue. It does look like a buffer to base64 encoding problem but can't find where .... I am using hapi.js and Joi for validating the my payload so wonder if that's where the issue is ....

**Comment by afgallo** [comment]
Hi @lovell, found out what the errors were:

1. Client side app sending uploaded file as **readAsBinaryString** instead of **readAsDataURL**
2. Server side app failing to remove _"data:image/png;base64,"_ part of the base64 encoded string. 

Cheers!

**Comment by GuiRitter** [comment]
> Hi @lovell, found out what the errors were:
> 
> 1. Client side app sending uploaded file as **readAsBinaryString** instead of **readAsDataURL**
> 2. Server side app failing to remove _"data:image/png;base64,"_ part of the base64 encoded string.
> 
> Cheers!

I've been looking for hours and this fixed my issue! It should be written somewhere that the `data:image/png;base64,` bit has to be removed before being sent to the `Buffer`.
