### ISSUE TITLE
Convert from icc profile to another icc profile?

### ISSUE THREAD

**Issue by moedusa** [lovell/sharp#579]
Hello,

I need to convert images with icc profiles involved. I've found that there is a libvips method vips-icc-transform: http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-colour.html#vips-icc-transform And icc-profile-export as well. Is it possible to expose this method[s] in sharp? Writing sharp images using withMetadata() does something like that already. But with sRGB profile, not a given one.

Unfortunately, my knowledge of C is C/0, so this is a feature request.

**Comment by lovell** [comment]
Hello, #218 should cover this - feel free to add suggestions there.
