### ISSUE TITLE
toFormat(format)

### ISSUE THREAD

**Issue by nitin42** [lovell/sharp#582]
When I am converting a jpeg to svg, this method is not working!!?.

**Comment by lovell** [comment]
Hello, SVG output is not supported. http://sharp.dimens.io/en/stable/api/#toformatformat

If you need to covert from bitmap (e.g. JPEG) to vector (e.g. SVG) formats then you'll need a tool such as [potrace](http://potrace.sourceforge.net/).

**Comment by nitin42** [comment]
Thanks!
