### ISSUE TITLE
How to get the trimmed pixel size of each edge?

### ISSUE THREAD

**Issue by natural-law** [lovell/sharp#583]
@lovell 
I want to use sharp to trim my image and **get the trimmed pixel size from each edge**. Now I don't know how to get the trimmed pixel size of each edge.

On the other way, I've tried to calculate the data myself. **But there is not a interface to get the pixel of specified position.**

Could you please show my a way to implement it? Thanks very much!

**Comment by lovell** [comment]
Hello, the logic for the `trim` operation lives fairly deep within the image processing pipeline - see https://github.com/lovell/sharp/blob/master/src/operations.cc#L410

The values used for the extraction are based on calculations performed with an intermediary image, which may already have undergone rotation and will potentially then undergo further extraction and resizing operations. This means the values won't necessarily relate to either the input or output dimensions. Although this might meet your specific use case, I'd be hesitant to expose it for all users.

**Comment by natural-law** [comment]
@lovell Thanks for your reply! I'm reading the source code now. Yep, I found trim is only a step in pipeline.

How about add a interface to read the pixel data of image? Then I can read the pixel & calculate the trimmed edge myself.

**Comment by lovell** [comment]
Pixel data is available using the [raw](http://sharp.dimens.io/en/stable/api/#raw) output format.

**Comment by natural-law** [comment]
Sorry for my careless. I've solved my problem. Thanks for your amazing work!
