### ISSUE TITLE
Error when colorspace is set to cmyk

### ISSUE THREAD

**Issue by yotamlaufer** [lovell/sharp#584]
Hi,

I have been trying to parse svg using cmyk. I have tried all possible combinations of output formats and methods to no avail.

When `toColorspace(sharp.colorspace.cmyk)` is invoked the following error is reported `Error: vips_colourspace: no known route between 'srgb' and 'cmyk'`

Without the method invocation everything works as expected.

Thanks.

**Comment by lovell** [comment]
Hi Yotam, conversion to CMYK output is device-dependent and therefore requires an ICC profile. This is a forthcoming feature awaiting development - see https://github.com/lovell/sharp/issues/218#issuecomment-240661431 onwards for more details and please offer help there if you're able.

I'm sorry you ran into this - we should probably flag the `toColorspace` feature as "semi-experimental" until #218 is ready.

**Comment by yotamlaufer** [comment]
Hi @lovell, thanks for the quick reply. If I understand correctly, explicitly setting an icc profile will allow cmyk conversion as demoed here:

```
sharp(rgbInput)
  .toColorspace('cmyk')
  .withMetadata({
    profile: '/path/to/alternative-cmyk-profile.icc'
  })
```

**Comment by lovell** [comment]
@yotamlaufer Yes, bearing in mind that is a proposed API and has yet to be implemented.

**Comment by lovell** [comment]
Closing as this is probably best discussed further under #218 - please do feel free to re-open if not.
