### ISSUE TITLE
How to npm install to include to libvips mozjpeg support

### ISSUE THREAD

**Issue by golojads** [lovell/sharp#586]
Hi! 
trellisQuantisation() / trellisQuantization() && overshootDeringing() requires libvips to have been compiled with mozjpeg support.
How to I "npm install" sharp.js to include mozjpeg?

Thank you.

**Comment by lovell** [comment]
Hello, sharp searches for and supports a globally-installed libvips at `npm install` time.

http://sharp.dimens.io/en/stable/install/#linux

You'll need to install libvips from source, with its `--with-jpeg-includes` and `--with-jpeg-libraries` flags being appropriate here.

https://github.com/jcupitt/libvips#optional-dependencies

Good luck!

**Comment by golojads** [comment]
Thnak you for prompt reply.
Doest it mean that if there is no libvips on my machine yet, then during "npm install" sharp.js package will install basic version of libvips to my machine ? But if I want to use extra libraries than I have to install libvips from source myself with flags mentioned in your reply?

**Comment by lovell** [comment]
http://sharp.dimens.io/en/stable/install/#linux

> libvips and its dependencies are fetched and stored within node_modules/sharp/lib during npm install. This involves an automated HTTPS download of approximately 6.5MB.

> To use your own version of libvips instead of the provided binaries, make sure it is at least the version listed under config.libvips in the package.json file and that it can be located using pkg-config --modversion vips-cpp.
