### ISSUE TITLE
OSX - GdkPixbuf-WARNING when converting an SVG to PNG 

### ISSUE THREAD

**Issue by dynamite-ready** [lovell/sharp#588]
I'm running Sharp 0.16.0 on OSX 10.11.6, and am currently trying to convert a buffered SVG to a PNG file with the following code:

`sharp(cmon).toFile('new.png');`

The SVG contains an embedded image (data URL). 
This works fine on Windows. The PNG is produced as expected. 

However, on OSX, the PNG file prints, but does not display the embedded image. 
The terminal window also prints the following:

```
(sharp:8201): GdkPixbuf-WARNING **: Cannot open pixbuf loader module file '/usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being
```

Has anyone else encountered this issue? Are there any simple fixes or work arounds?

**Comment by lovell** [comment]
Hello, are you using a global version of libvips installed via homebrew? `brew info vips` should tell you.

**Comment by dynamite-ready** [comment]
Hi, I did actually switch to using the Homebrew version of libvips found here - http://www.vips.ecs.soton.ac.uk/index.php?title=Build_on_OS_X - and it worked.
You can probably close this, but it would be cool if the npm installation process was fixed, or the documentation helped to troubleshoot the issue better.

Thank you for looking into the issue.

**Comment by lovell** [comment]
Use of a homebrew-installed copy of vips is not required to use sharp on OS X. However I know some people do use it and the mention of a global path `/usr/local/lib/...` in your error message suggested this might be the case here, so I asked only to help narrow down the problem.

The SVG to PNG use case is [included in the tests](ttps://github.com/lovell/sharp/blob/f672f86b539d578026f2505151452ee08196f963/test/unit/io.js#L672) and [seems to work](https://travis-ci.org/lovell/sharp/jobs/164250087) on OS X using the pre-built binaries.

A recent commit to https://github.com/Homebrew/homebrew-core/pull/4259 suggests the "Cannot open pixbuf loader module file" error is or at least has been a known problem with a homebrew-installed gdk-pixbuf.

My best guess here is that an older version of gdk-pixbuf has previously been installed globally (perhaps as a dependency of something else) and was somehow being used in preference to sharp's own bundled version of it.
