### ISSUE TITLE
Loss of colour when using sharp as compared to original/mozjpeg3/vips from command line

### ISSUE THREAD

**Issue by rnanwani** [lovell/sharp#589]
Hi

I have jpeg image which I want to optimise to quality 80. The original image is 246KB and can be seen below
![image](https://cloud.githubusercontent.com/assets/4739557/19029434/cbcc3878-8963-11e6-8b51-eb15999dec08.png)

I used sharp to reduce quality to 80 and output format as jpeg (.quality(80).jpeg()). The image I get is a rather washed out one. The size is 87.7KB.
![image](https://cloud.githubusercontent.com/assets/4739557/19029443/f4a25aac-8963-11e6-9b0a-289cb7d7efd2.png)

I used mozjpeg CLI for the same (./cjpeg -quality 80 <input> > <output>)
The size I get is 82.6KB. This smaller size can be noticed in the considerable reduction in the sharpness of the tree leaves.
![image](https://cloud.githubusercontent.com/assets/4739557/19029495/6f55c8d8-8964-11e6-8384-4557c18e57a0.png)

I used vips CLI (vips copy <input> <output>[Q=80]. The size i get is 105KB
![image](https://cloud.githubusercontent.com/assets/4739557/19029565/04ebd860-8965-11e6-804f-dbed41f8ff02.png)

I want to know, if there is a specific setting/command that is "reducing" the colors in the image and can it be avoided in sharp. I understand that the compression ratios of mozjpeg and vips vary. Thus, there is a slight color change from the original image, and the output image file sizes vary for the two CLIs. What is it that is additionally used in sharp to get a file size that is lower than that obtained using command line vips.

**Comment by lovell** [comment]
Hello, are you able to share the original JPEG image? (Everything here is a PNG image, likely due to Github mangling.)

**Comment by rnanwani** [comment]
Can you check on the link here
https://drive.google.com/drive/u/0/folders/0BznBgV252hG1d0l0WnVUdzVtcUU

Also, I noticed, and I might be wrong in this observation, that the color difference is more pronounced when the images are opened in the browser versus viewing the same images in some other application (like viewer on Mac or Sketch)

**Comment by jcupitt** [comment]
Your images have about 15 - 20kb of metadata attached to them. If I run `vipsheader -a` I see:

```
$ vipsheader -a original.jpg 
...
jpeg-thumbnail-data: VIPS_TYPE_BLOB, data = 0xe94bb0, length = 2370
exif-data: VIPS_TYPE_BLOB, data = 0xe92aa0, length = 2682
ipct-data: VIPS_TYPE_BLOB, data = 0xe95570, length = 4728
xmp-data: VIPS_TYPE_BLOB, data = 0xe967f0, length = 3718
icc-profile-data: VIPS_TYPE_BLOB, data = 0xe97680, length = 3144
```

sharp is stripping all this off in order to make the thumbnail smaller. Something is different (perhaps rendering intent?) between sharp's treatment of the ICC profile and the way your viewer is handling it, making the colour looks a little different.

**Comment by jcupitt** [comment]
Here's the "most correct" version of your image. I imported `original.jpeg` to CIELAB with perceptual intent using the embedded profile, then exported to 8-bit sRGB PNG with no profile. It should look the same in all viewers. 

![x](https://cloud.githubusercontent.com/assets/580843/19033314/aeca9c78-8955-11e6-8310-04b129829778.png)

Put the samples into separate tabs in your web browser, then try flipping between them. The closest is the winner.

**Comment by lovell** [comment]
The original JPEG image is in a device-dependent RGB colourspace.

sharp converts to the device-independent sRGB using the embedded RGB profile with a perceptual intent, then removes the original profile as it is no longer relevant.

The reason for always using sRGB output is that web browsers have generally been pretty bad at device-dependent colour rendering, although the situation is improving. There's a great test page at https://kornel.ski/en/color

The gamut of sRGB is usually narrower than RGB, especially with green and blue hues.

There's some discussion at #218 about exposing the ability to provide custom profiles.

**Comment by rnanwani** [comment]
Thanks for clarifying :)
