### ISSUE TITLE
Bad Extract Area error for valid extract coordinates

### ISSUE THREAD

**Issue by mxshrestha** [lovell/sharp#590]
Extract function errors out even with valid coordinates.
```
> sharp('Portrait_7.jpg').extract({left:0, top: 75, width: 450, height: 450}).toFile('./tmp/p7.jpg')
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
> Unhandled rejection Error: extract_area: bad extract area

    at Error (native)
```

**Comment by mxshrestha** [comment]
Here is the file. @lovell please let me know if there is something wrong with my code.
![portrait_7](https://cloud.githubusercontent.com/assets/1475253/19059533/30026bfe-89a6-11e6-89d5-85254bc771d5.jpg)

**Comment by lovell** [comment]
Hello, this image is 600px wide by 450px high, so 450+75 is out of bounds for the vertical dimension.

Perhaps you were expecting the image to be auto-rotated based on EXIF headers? If so, you'll need to add `rotate()` into the processing chain. File explorers and web browsers usually do this automagically, so it's a common source of confusion.

**Comment by mxshrestha** [comment]
I see. Thank you @lovell . you rock!
