### ISSUE TITLE
How to properly resize and crop?

### ISSUE THREAD

**Issue by niftylettuce** [lovell/sharp#591]
Perhaps @lovell can answer this - the documentation is super confusing in general by the way.  The use of `min`, `max`, `crop` and the sequence at which the stream is transformed is confusing.  It appears like you specify in `resize` the width/height that the following transforms apply with?  It's just super confusing and I probably will just use a different package now.

Anyways, I'm trying to do something simple, but getting really odd results.

Here's my image:

![apple-touch-icon](https://cloud.githubusercontent.com/assets/523141/19073522/76fd93f4-8a09-11e6-8528-3ff480b23b22.png)

As you can see, it's a 152x152 image.

Now I want to resize this to 600x600.  But I want to take into consideration that this 152x152 image could be 80x500 or 2000x1000, and I want to resize the width to 600, and then crop anything else past the height of 600 (filling in the entire image with either the image itself resized or `#fff` background).

I get weird output though.

```js
const thumbnailer = sharp().resize(600, 600);
```

Outputs the image, but it's missing half of the image:

![apple-touch-icon](https://cloud.githubusercontent.com/assets/523141/19073513/6e538e2a-8a09-11e6-8870-37be45326588.png)

**Comment by niftylettuce** [comment]
It was because I was using content length in my S3 upload BEFORE applying sharp transformation, not AFTER 👍

**Comment by lovell** [comment]
> "The use of min, max, crop and the sequence at which the stream is transformed is confusing."

Yes, I (and other feedback) agree with you, so you're definitely not alone in thinking this.

The existing crop/embed/min/max options-as-functions will eventually become an `options` parameters of the `resize()` operation.

Glad to hear you got it working :)
