### ISSUE TITLE
Gravity coordinates

### ISSUE THREAD

**Issue by jiri-smolik** [lovell/sharp#592]
Is it possible, or any workaround to apply gravity when cropping for custom coordinates and not just specified north, south and so on?

**Comment by lovell** [comment]
Hello, did you see the [extract](http://sharp.dimens.io/en/stable/api/#extract-left-left-top-top-width-width-height-height) operation, which might provide what you're looking for?

**Comment by jiri-smolik** [comment]
Hi, thank you for quick response,
I know of extract, but I thought it behaves differently. So crop is just extract with clipped boundaries?

**Comment by lovell** [comment]
Think of [crop](http://sharp.dimens.io/en/stable/api/#cropoption) as an option that's available when resizing to a fixed width and height.

(The API is a little confusing, sorry. `crop` will eventually become an option of the `resize()` operation to which it belongs.)

**Comment by jiri-smolik** [comment]
Oh I see now! Thank you very much for your explanation.

**Comment by ramiel** [comment]
I ask my question here since it seems related. What you said before means that
```
.resize(200,200)
.crop(sharp.gravity.northwest)
```

is the same as

```
.extract({top: 0, let: 0, width: 200, height: 200})
```

?

**Comment by lovell** [comment]
@ramiel No, because `resize` might scale where `extract` will not.
