### ISSUE TITLE
Support non-JPEG TIFF output by exposing VipsForeignTiffCompression

### ISSUE THREAD

**Issue by changyh** [lovell/sharp#594]
After image of tif file resize() the result file is almost double size then original tif file size.
I use the tif file on your test dir, G31D.TIF, and the code as the following:

```
var image = sharp('G31D.TIF');
image.metadata(function(err, metadata) {
    if(err){
        console.log('err= ',err);
    } else {
        console.log('metadate= ', metadata);
        return image.resize(Math.round(metadata.width/2)).toFile('G31D_1.TIF');
    }  
 });
```

-rw-r--r--@  1 xxxx  staff  125824 Sep 25 19:13 G31D.TIF   //2464 × 3248
-rw-r--r--@  1 xxxx   staff  235499 Oct  5 11:15 G31D_1.TIF  //1232 × 1624

The image file property is correct.

May I know why and how to change it?

Thanks,

**Comment by onebook0505** [comment]
+1，I have the same problem．

**Comment by lovell** [comment]
Hello, the compression type used for TIFF output is currently [always JPEG](https://github.com/lovell/sharp/blob/master/src/pipeline.cc#L830).

We'll need to expose some of libvips' other [VipsForeignTiffCompression options](http://www.vips.ecs.soton.ac.uk/supported/8.3/doc/html/libvips/VipsForeignSave.html#VipsForeignTiffCompression) if there's a requirement for lossless (i.e. non-JPEG) output.

**Comment by onebook0505** [comment]
How do I reduce the file size? ( e.g. 2MB -> 500KB )

Are there other alternatives? ( to reduce the file size )

Thanks.

**Comment by lovell** [comment]
If TIFF container output is required then, currently, the compression format is limited to JPEG.

The TIFF/JPEG quality, and therefore file size, is configurable using the existing [quality](http://sharp.dimens.io/en/stable/api/#qualityquality) setting, but you can expect more compression artefacts at lower values.

**Comment by changyh** [comment]
Hi Iovell,

Does this mean the sharp only good for JPEG performance?
The other format in sharp couldn't get the performance as JPEG, is it?

Thanks,

**Comment by lovell** [comment]
@changyh I recommend you run your own comparative performance tests for your specific use case and hardware.

Like sharp itself, the source for the benchmarks is open and available. Perhaps you could add your own TIFF-based tests to it? https://github.com/lovell/sharp/blob/master/test/bench/perf.js

**Comment by kristojorg** [comment]
I would like to be able to export to TIFF in ZIP or LZW format, which it looks like libvips does support. This is for use in an electron.js desktop photo application. I'm not manipulating images for web transport, and would like to keep images in highest quality possible while also reducing file size (by compressing TIFFs). 

Is this something you would also like to support in sharp and if so how should we proceed to implement it?

**Comment by lovell** [comment]
@kristojorg The work for this will expose DEFLATE and LZW compression, yes. PR welcome, as always.

**Comment by kristojorg** [comment]
Addressed by https://github.com/lovell/sharp/pull/738

**Comment by lovell** [comment]
v0.17.3 now available, thanks both for the PR and the original suggestion.
