### ISSUE TITLE
Optimizing an already optimised image results in a larger image

### ISSUE THREAD

**Issue by rnanwani** [lovell/sharp#595]
All files are in this https://drive.google.com/open?id=0BznBgV252hG1aWNYZ2NtVFBKS3M
I have an optimized image (image_original.jpg)

I used sharp and vips cli both to give a jpeg output with quality = 80. What is possibly happening that results in the resultant image being larger than the original image (by a couple of kBs)?

**Comment by lovell** [comment]
Hello, the original image is Q=75, the output is Q=80:

```sh
$ diff <(identify -verbose image_original.jpg) <(identify -verbose image_after_sharp.jpg) | grep Q
<   JPEG-Quality: 75
>   JPEG-Quality: 80
```

The difference between vips and sharp is that there's an EXIF header in the former:

```sh
$ diff <(identify -verbose image_after_vips_cli.jpg) <(identify -verbose image_after_sharp.jpg) | grep P
<   Profile-EXIF: 114 bytes
```

**Comment by rnanwani** [comment]
Please correct me if I am wrong, but if I apply a Q=80 transform over the original image (which already has Q=75), shouldn't the output be smaller than Q=75 (like quality of 0.8 * 75 = 60).

**Comment by lovell** [comment]
Although the perceived quality may reduce on each decode/encode round-trip, the value of the JPEG "quality" setting is not cumulative.

(The JPEG "quality" setting tells the encoder how much data it can discard when assessing each 8x8 block of raw, uncompressed pixel data. A higher value means less data discarded means a larger file size.)

**Comment by rnanwani** [comment]
Thanks .

Is is possible to add Quality as an output in `.metadata()` instead of having to use imagemagick's identify for this?

**Comment by lovell** [comment]
No, sorry, JPEG images do not contain the value for the "quality" setting.

ImageMagick attempts to [reverse engineer the value](https://github.com/ImageMagick/ImageMagick/blob/master/coders/jpeg.c#L818), but this is sometimes wrong, e.g. mozjpeg uses different quantization tables.

**Comment by rnanwani** [comment]
Thanks for the clarification :)
