### ISSUE TITLE
How to manually manage the cache?

### ISSUE THREAD

**Issue by natural-law** [lovell/sharp#599]
@lovell 
I found that `sharp` has an interface `cache` can set the limitation of the cache. But how can I force open a file without reading the data from cache?

I want to enable the caching. And once an image file changed(I know it's changed), I can read the latest data of it but not the cached data.

Is there an interface can remove the cached data of specified file? Or a method can force read the latest file data?

Would appreciate any feedback / help....Thanks for your time and God Bless....

**Comment by lovell** [comment]
Hello, the cache belongs to libvips and stores the result of intermediate image operations.

If you need custom, fine-grained cache control beyond that already provided, I would suggest managing it yourself outside of sharp/libvips.

**Comment by natural-law** [comment]
@lovell Thanks for your quickly reply.

I found a way to implement it:
Disable caching when I want to read latest file data, and enable caching again after the reading.

It works well by now. Thanks for your time again!
