### ISSUE TITLE
Error in `node': corrupted double-linked list

### ISSUE THREAD

**Issue by spro** [lovell/sharp#6]
I'm running a batch of node services that are cropping images on demand with sharp. Every once in a while one of them will get this error which requires a hard restart (I'm running the services with forever but the error doesn't seem to be raised at the correct "level" for forever to handle it). I haven't been able to track it down to sharp specifically, perhaps it has something more to do with libvips, but I'm starting at the top of the chain.

Stack trace here:
https://gist.github.com/spro/8839678

**Comment by binarykitchen** [comment]
@lovell i think i am experiencing a very similar issue like this one with the latest libvips/sharp update. very weird, reported it to node too and do not have much information to investigate.

**Comment by lovell** [comment]
@binarykitchen Please can you open a new issue for this if/when you have more information or have produced a small test case that always fails. The `catchsegv` tool can be used to generate a backtrace.
