### ISSUE TITLE
PNG resulting image is larger with more metadata

### ISSUE THREAD

**Issue by rnanwani** [lovell/sharp#600]
Attached is the diff for the two images using `identify`

1c1
<  Image: /Users/rahul/Downloads/outofbox.png
  Image: /Users/rahul/Downloads/outofbox-2.png
6c6,8

<   Units: Undefined
@@@
   Resolution: 28.34x28.34
   Print size: 44.566x35.9915
   Units: PixelsPerCentimeter
160,161c162,163

<     date:create: 2016-10-13T17:28:54+06:00
<     date:modify: 2016-10-13T17:28:44+06:00
@@@
     date:create: 2016-10-13T17:57:26+05:00
     date:modify: 2016-10-13T17:57:18+05:00
164,165c166,167

<     png:IHDR.color-type-orig: 3
<     png:IHDR.color_type: 3 (Indexed)
@@@
     png:IHDR.color-type-orig: 6
     png:IHDR.color_type: 6 (RGBA)
168c170

<     png:PLTE.number_colors: 78
@@@
     png:pHYs: x_res=2834, y_res=2834, units=1
170d171

<     png:tRNS: chunk was found
173c174
<     filename: /Users/rahul/Downloads/outofbox.png
@@@
     filename: /Users/rahul/Downloads/outofbox-2.png
176c177

<   Filesize: 23.7KB
@@@
   Filesize: 40.5KB

**The one after @@@ is the new image, The one before is the original image.**

The resulting image is larger than the original image with some extra data in the `identify` command. What could be the reason that the resulting image is larger. pngquant can return this image in exactly the same size. I am using `pipeline = pipeline.compressionLevel(9).withoutAdaptiveFiltering().png()` and if i remove `withoutAdaptiveFiltering()` the output size is even more 60.4Kb. The original image could have probably been run through tinypng or something. How do I ensure that the output image is not larger than the input image

**Comment by lovell** [comment]
```
< png:IHDR.color-type-orig: 3
< png:IHDR.color_type: 3 (Indexed)
@@@
> png:IHDR.color-type-orig: 6
> png:IHDR.color_type: 6 (RGBA)
```

Hello, libvips doesn't support indexed PNG output. See also #478.

**Comment by lovell** [comment]
Hope this answered your question. Feel free to reopen with more details if not.
