### ISSUE TITLE
Precalculating trim dimensions

### ISSUE THREAD

**Issue by teroparvinen** [lovell/sharp#608]
I am contemplating using sharp for creating sprite sheets from individual animation frame image files for use with CSS. I would like to trim each animation to cut out excess blank space, but all frames in a single animation need to be trimmed equally. For this, I would need to first determine the minimum trim rectangle for each frame, calculate the smallest total I can use and then use this to crop all frames with the same crop rectangle.

Is it feasible to try and get this kind of support from sharp?

**Comment by lovell** [comment]
Hello, I'd probably try something like the following:

1. use the [trim](http://sharp.dimens.io/en/stable/api/#trimtolerance) operation on all the images and note the output dimensions
2. select the image with the largest output dimensions (the least "boring" image)
3. extract the pixel values from it via [raw](http://sharp.dimens.io/en/stable/api/#raw)
4. inspect its pixels value with whatever custom logic is required to determine how much to trim off every edge
5. use [extract](http://sharp.dimens.io/en/stable/api/#extract-left-left-top-top-width-width-height-height) for the same region of all images

**Comment by teroparvinen** [comment]
Thanks for the quick response.

Finding the largest output dimensions is not feasible, imagine an animation where a character is hanging with their hands from something and swinging their legs left to right (in the image). All frames might be of a relatively similar width, but the effective crop area needs to be from the extreme left pixel  when swinging left to the extreme right pixel when swinging right.

If I simply use `raw` to get the pixel data and do all logic from there and use `extract` for the final processing, I'm doing a lot of inefficient processing in javascript. I was hoping that the `project`, `profile`, `fliphor` and `flipver` methods used in the trim code could help me directly, and actually make the operation more efficient.

**Comment by lovell** [comment]
This use case sounds quite specialised, so raw pixel inspection is probably your best bet.

If performance is of concern, perhaps resize/reduce images and/or convert to single channel greyscale to ensure the Buffer that represents the raw pixel values fits within your CPU's L2 cache before running your pixel inspection logic over it.
