### ISSUE TITLE
Brightness, Saturation and Hue

### ISSUE THREAD

**Issue by diegocsandrim** [lovell/sharp#609]
Hi @lovell,
Does sharp support brightness, saturation and hue?
I was looking for something similar to `modulate` of [imagemagick](http://www.imagemagick.org/Usage/color_mods/#modulate) or [graphicsmagick](http://www.graphicsmagick.org/GraphicsMagick.html#details-modulate).
I took a look at the docs but could not find.

**Comment by lovell** [comment]
Hello, *magick's "modulate" operator is approximately equivalent to a colourspace conversion to LCH (Luminance, Chroma, Hue) then a multiplication of pixels in the L and C channels. libvips supports these operations, but this is not currently exposed in sharp.

As always, I'm happy to accept a PR and help with discussions about how the API for this might work.

**Comment by adityapatadia** [comment]
I would like to work on this. Can you point me to some resource which teaches about how can this be done?

**Comment by lovell** [comment]
@adityapatadia Thanks for your interest.

This feature will involve a combination of converting to the LCH colourspace via [colourspace](http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-colour.html#vips-colourspace), splitting out any channels to be "modulated", using [multiply](http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-arithmetic.html#vips-multiply) to modify them with the relevant value before joining the channels back up again.

You probably won't need to worry about the colourspace conversion away from LCH as there's already logic to clean up at the end of the pipeline.

* L(ightness) ~= brightness
* C(hroma) ~= saturation
* H(ue)

The API could look something like:

```javascript
// identity transform, 100 means 100% of the original value so no change
.modulate({ brightness: 100, saturation: 100, hue: 100 }) 
```

```javascript
// reduce saturation by ~25%
.modulate({ saturation: 75 }) 
```

```javascript
// convert red to green etc.
.modulate({ hue: 166 }) 
```

**Comment by adityapatadia** [comment]
I would be asking much more questions.
Apart form API, how do I implement in the C code? Which files should I add the operations? Can you show me sample from which I can learn?

**Comment by lovell** [comment]
@adityapatadia Although it's marked `patch-welcome`, this is a relatively complex task. Perhaps look at implementing something like #577 first?

**Comment by lovell** [comment]
@jonathan-kosgei Thank you for the offer of help.

sharp uses libvips C++ API
http://jcupitt.github.io/libvips/API/current/using-from-cpp.html

Your idea to start with an existing operation such as blur is a good idea. Perhaps follow `blurSigma` as it moves through the various layers.

https://github.com/lovell/sharp/search?q=blurSigma&type=Code

https://github.com/lovell/sharp/blob/master/lib/operation.js#L180
https://github.com/lovell/sharp/blob/master/src/pipeline.cc#L1209
https://github.com/lovell/sharp/blob/master/src/operations.cc#L237

I'm always happy to help with and provide feedback on partially-complete PRs.

**Comment by lovell** [comment]
v0.22.1 now available with this feature.
