### ISSUE TITLE
Feedback please: Node v4 as minimum required runtime

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#610]
Maintenance for Node v0.10 ends in 10 days' time, which means no more security fixes for things like OpenSSL bugs.

Maintenance for Node v0.12 is up at the end of this year, just over two months' time.

https://github.com/nodejs/LTS#lts-schedule

The usual Node version laggards seem to be ready for v4:
- AWS Lambda v4.3.2
- Meteor v4.4.7

I'd like to drop support for versions of Node prior to v4 in the next "major" release, v0.17.0.

Are there any objections or reasons why we shouldn't do this? Feedback very much welcome here.

**Comment by sachinwalia2k8** [comment]
@lovell - is there a constraint on what maximum version of Node I can use with sharp. At present for my application I am using Node 6.9 and wondering if sharp will have any compatibility issue?

**Comment by lovell** [comment]
@sachinwalia2k8 With each major Node version there are often breaking API changes with the version of V8. Sometimes these require updates to [nan](https://github.com/nodejs/nan) upon which this module depends. This change might then require a version bump and release of this module, but it depends.

There are CI environments for [Linux, OS X](https://github.com/lovell/sharp/blob/master/.travis.yml) and [Windows](https://github.com/lovell/sharp/blob/master/appveyor.yml), the config for which lists the versions being tested against. This includes the latest v6.x.x release.

The [changelog](http://sharp.dimens.io/en/stable/changelog/) contains details about support for a new major version of Node only when a change is required for that version. It will also contain details of dropping support for older versions when we do so.

**Comment by sachinwalia2k8** [comment]
@lovell - Thanks for the info. For what it's worth I tried installing it against Node 6.9.1 and I am getting an error. I am attaching the npm-debug.log if you want to take a look at it and suggest what  would be the approach to resolve it. Thanks a lot for your help.
[npm-debug.txt](https://github.com/lovell/sharp/files/545906/npm-debug.txt)

**Comment by lovell** [comment]
@sachinwalia2k8 Probably https://github.com/lovell/sharp/issues/602#issuecomment-253741472, new issue if not please.

**Comment by sachinwalia2k8** [comment]
@lovell - Thanks. Existing install of libvips 8.4+ via homebrew seems to be an issue.

**Comment by wtgtybhertgeghgtwtg** [comment]
This would mean you could drop the `bluebird` dependency, right?

**Comment by lovell** [comment]
@wtgtybhertgeghgtwtg Good question. I believe the use of native Promises may incur a slight performance hit - see some relevant discussion at https://github.com/lovell/sharp/pull/55#issuecomment-45713315 - but we can benchmark this.

**Comment by wtgtybhertgeghgtwtg** [comment]
It probably will, but it's a 599KB dependency duplicating natively available stuff.  So you could see it as a choice between absolute performance or a smaller dependency graph.

**Comment by lovell** [comment]
For those interested in reducing the number of bytes downloaded and/or stored on disk, a move to Node v4 as a minimum will allow a move from `request` to a module more focussed on the simple GET-a-file use case (e.g. no cookies) like the [got](https://www.npmjs.com/package/got) + [caw](https://www.npmjs.com/package/caw) combo.

**Comment by wtgtybhertgeghgtwtg** [comment]
Unless #593 makes it.  And it's not just about disk size.  More dependencies means more places it can break.

**Comment by lovell** [comment]
A slightly modified version of the existing sharp [benchmark test](http://sharp.dimens.io/en/stable/performance/) run locally with Node v6.9.1 (V8 v5.1) suggests V8's Promise implementation has a ~-0.5% impact on performance compared with the Bluebird implementation.

http://v8project.blogspot.co.uk/2016/07/v8-release-53.html suggests there is at least a 20% performance improvement to native Promise performance in V8 v5.3 and this will be in the forthcoming Node v7 (V8 v5.4).

**Comment by lovell** [comment]
I've managed to reduce the total number of production (sub-)dependencies from 93 to 50, with an associated disk usage reduction of 5.2MB.

**Comment by sachinwalia2k8** [comment]
@lovell - NodeJS 7 has been released today and I can try out if sharp has any compatibility issues.

**Comment by sachinwalia2k8** [comment]
I have been testing sharp with Node 7.0 and haven't encountered any issues so far.

**Comment by lovell** [comment]
v0.17.0 now available with a Node v4 minimum runtime dependency. Thanks for all the +ve feedback.
