### ISSUE TITLE
Cannot run app with sharp

### ISSUE THREAD

**Issue by sscaff1** [lovell/sharp#612]
```
(sharp:585): GLib-GObject-WARNING **: cannot register existing type 'gchar'
**
GLib-GObject:ERROR:gvaluetypes.c:455:_g_value_types_init: assertion failed: (type == G_TYPE_CHAR)
```

I've tried uninstalling all of my node modules, reinstalling them. I tried to remove all of my global packages and completely remove node (then brew reinstall) and nothing seems to work. I still get the above error any ideas?

**Comment by lovell** [comment]
Hello, are you also using the `canvas` module?

**Comment by sscaff1** [comment]
Yes I am.

**Comment by lovell** [comment]
Thanks for confirming, please see https://github.com/lovell/sharp/issues/575#issuecomment-247304262

**Comment by sscaff1** [comment]
Thank you - I will reopen if I have any trouble!
