### ISSUE TITLE
Cannot open source file: weird path issue? Windows 10 64-bit

### ISSUE THREAD

**Issue by NgJason** [lovell/sharp#613]
I've installed newest release version of node and 2015 MS build tool, but this error won't go away and I cannot install sharp.

F:\n>npm install sharp

> sharp@0.16.2 install F:\n\node_modules\sharp
> node-gyp rebuild

F:\n\node_modules\sharp>if not defined npm_config_node_gyp (node "D:\nodejs\node
_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebu
ild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  VError.cpp
  VInterpolate.cpp
  VImage.cpp
  win_delay_load_hook.cc
     Creating library F:\n\node_modules\sharp\build\Release\libvips-cpp.lib and
   object F:\n\node_modules\sharp\build\Release\libvips-cpp.exp
  Generating code
  Finished generating code
  libvips-cpp.vcxproj -> F:\n\node_modules\sharp\build\Release\\libvips-cpp.dll
  libvips-cpp.vcxproj -> F:\n\node_modules\sharp\build\Release\libvips-cpp.pdb
  (Full PDB)
  win_delay_load_hook.cc
c1xx : fatal error C1083: Cannot open source file: '..\nan /I..\include /I..\in
clude\glib-2.0 /I..\lib\glib-2.0\include /Zi /nologo /W3 /WX- /Ox /Ob2 /Oi /Ot
/Oy /GL /D NODE_GYP_MODULE_NAME=sharp /D USING_UV_SHARED=1 /D USING_V8_SHARED=1
 /D V8_DEPRECATION_WARNINGS=1 /D WIN32 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONS
TDC_NO_DEPRECATE /D _HAS_EXCEPTIONS=0 /D _ALLOW_KEYWORD_MACROS /D BUILDING_NODE
_EXTENSION /D _WINDLL /GF /Gm- /EHsc /MT /GS /Gy /fp:precise /Zc:wchar_t /Zc:fo
rScope /Zc:inline /GR- /FoRelease\obj\sharp\ /FdRelease\obj\sharp\vc140.pdb /Gd
 /TP /wd4351 /wd4355 /wd4800 /wd4251 /wd4275 /errorReport:queue /MP ..\src\comm
on.cc ..\src\metadata.cc ..\src\operations.cc ..\src\pipeline.cc ..\src\sharp.c
c ..\src\utilities.cc D:\nodejs\node_modules\npm\node_modules\node-gyp\src\win_
delay_load_hook.cc': No such file or directory [F:\n\node_modules\sharp\build\s
harp.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\nodejs\node_modules\npm\node_modul
es\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\node_mod
ules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\n\node_modules\sharp
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'F:\n\package.json'
npm WARN n No description
npm WARN n No repository field.
npm WARN n No README data
npm WARN n No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cl
i.js" "install" "sharp"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.16.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.16.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\n\npm-debug.log

**Comment by lovell** [comment]
Hello, this looks like a local environmental problem. Adding the `--verbose` flag might provide more clues.

```sh
npm install --verbose sharp
```
Feel free to provide the (unmodified) log as an gist if you'd like me to take a quick look.

**Comment by NgJason** [comment]
Hi @lovell , thanks for replying. Here is the npm-debug.log with --verbose. 
https://gist.github.com/NgJason/7a1d41cdaec7cad5a17c0dd08ada2409

I reinstalled with v.4.6.1 Node and the problem still persist.

**Comment by lovell** [comment]
Thanks. I can't find "Cannot open source file" or "C1083" within the gist. Is this the same problem?

**Comment by NgJason** [comment]
@lovell , my apology, I am not sure how to save the (unmodified) log. Windows PowerShell seems to only keep the last 3000 lines. 

I put npm install --verbose sharp into a PowerShell script and ran it with >./output.txt, the content is as follow. (short , but contains the error)
https://gist.github.com/NgJason/92842cfc72c74f8d53051366371a557e

Here is the log that contains the last 2999 lines, error can be found on the bottom.
https://gist.github.com/NgJason/f0d250ca558317eb363301e125e0d8f6

**Comment by lovell** [comment]
This bit looks wrong to me:

````
/I"..\Active code page: 850
  node_modules\nan"
```

The path to the nan module is generated by https://github.com/lovell/sharp/blob/master/binding.gyp#L95

Running the following in `F:\n` will confirm the path being used on your machine.

```sh
node -e "console.log(require.resolve('nan'))"
```

**Comment by NgJason** [comment]
```
Active code page: 850

F:\n>node -e "console.log(require.resolve('nan'))"
module.js:327
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.require.resolve (internal/module.js:16:19)
    at [eval]:1:21
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:409:26)
    at node.js:579:27
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

F:\n>
```

**Comment by NgJason** [comment]
@lovell , after npm install nan -g : 

https://gist.github.com/NgJason/f3b58e5b8527724b88f987d209fe0f8f

**Comment by lovell** [comment]
You won't need to install `nan` globally as it is a dependency of `sharp`. (I usually recommend against globally installing modules via npm as that can cause hard-to-debug dependency problems in the future.)

The most recent gist still includes the "Active code page: 850" in the path:
```
/I"..\Active code page: 850
  node_modules\nan"
```
My best guess is that there's a directory involved with a character encoding that node/nan/node-gyp can't handle. Without being able to access the system there's not a lot more I can do to help.

Do other native addons fail in a similar manner?
```sh
npm install --build-from-source bcrypt
```

**Comment by NgJason** [comment]
It results in a similar error.

https://gist.github.com/NgJason/2d184403e0dd3996b79c001f433654ba

I am going to try different code pages and report back.

**Comment by lovell** [comment]
Given bcrypt is failing in a similar manner this is most likely a problem somewhere between gyp and your local environment rather than something specific to sharp. Good luck!

**Comment by cipriano98** [comment]
Try to run
``` bash
npm config set msvs_version 2017
```
