### ISSUE TITLE
toFile with *.dzi uses a different directory name

### ISSUE THREAD

**Issue by gouroujo** [lovell/sharp#619]
Hello,

The above code generate  'output.dzi.dzi' file and 'output.dzi_files' folder. The expected behavior is 
'output.dzi' and 'output_files' folder

I'm using sharp v0.15.1 (I have the same issue with 0.16)

```javascript
sharp(bodyBuffer)
          .tile({
                size: 512,
              })
              .toFile('output.dzi', (e, info) => {
                if (e) {
                  reject(e);
                } else {
                  resolve(info);
                }
              });
```

thanks !

**Comment by lovell** [comment]
Hello, is this with a global/custom installation of libvips? There were some tile-related changes in libvips v8.4+ and the appearance of `output.dzi_files` suggests you might be using it.

I had to change some of the tests to accommodate the v8.3 to v8.4 upgrade, e.g. https://github.com/lovell/sharp/commit/95e7aae040335a25138855b2bea08dc1f1f670ca#diff-7771a88b9cf9cdbbb1db2741144708f7

**Comment by gouroujo** [comment]
I'm using vips installed with Homebrew (mac OSX) => v8.4.2

**Comment by lovell** [comment]
Thanks, so it's probably to a change in libvips' behaviour between v8.3 and v8.4 rather than anything in sharp.

Are there problems with the generated image files or does the use of "is broken" here mean only "uses a different directory name"?

**Comment by gouroujo** [comment]
Ok thanks without the globally installed lib it's now working.
 
I have changed the issue title to reflect what is actually wrong.
I leave the issue open as it's probably required a fix to be compatible with the 8.4 version but feel free to close it.
Thanks @lovell !

**Comment by lovell** [comment]
sharp passes the output filename straight to libvips via its `vips_dzsave` API and therefore behaves in the same manner as the `vips dzsave ...` command line for any given version of libvips.

Changing the filename from `output.dzi` to `output.dz` seems to provide what you're looking for with libvips v8.4.2:
```sh
$ vips dzsave input.jpg output.dz
$ ls output*
output.dzi
output_files:
0  1  10  11  12  2  3  4  5  6  7  8  9
```

**Comment by lovell** [comment]
Updated docs with this change via commit 4af702e
