### ISSUE TITLE
resize causes degradation in quality

### ISSUE THREAD

**Issue by umasudhan** [lovell/sharp#621]
I am trying to resize a png ( 
![1039](https://cloud.githubusercontent.com/assets/15900590/19987516/aa8d9dd0-a26f-11e6-99fa-8ce1f821c1bc.png)
).  My requirement is to resize the image preserving aspect ratio as close as possible to the passed in width/height and then embed it in a transparent background. 

My snippet is:
`sharp('1039.png')//249*150
    .resize(70, 70)
    .background({r: 0, g: 0, b: 0, a: 0})
    .embed()
    .toFormat(sharp.format.png).toFile('output.png');`

The output seems to have suffered quite a bit- please see 
![output](https://cloud.githubusercontent.com/assets/15900590/19987595/0b36a956-a270-11e6-9710-114460a8d418.png)
I also tried with resize preserving the aspect ratio and no embed- like so:
`sharp('1039.png')//249*150
    .resize(83, 50)
    .toFormat(sharp.format.png).toFile('output1.png');`

but there is still a loss in quality- 
![output1](https://cloud.githubusercontent.com/assets/15900590/19987639/56a6d9a6-a270-11e6-9b26-e8cf3bd09b7b.png)

I read the documentation but there does not seem to be any option for antialias (maybe its turned on by default?). Could you tell me if its something I am doing wrong? Or is it that I am being overtly finicky and this is the best I can get?

**Comment by lovell** [comment]
Hello, did you see the `kernel` option of the [resize operation](http://sharp.dimens.io/en/v0.16.2/api/#resizewidth-height-options)? Perhaps try `cubic` for this rather blurred input image.
```javascript
sharp('1039.png').resize(70, 70, { kernel: 'cubic' })...
```

**Comment by umasudhan** [comment]
Thanks @lovell - I have decided to stick with the default filter- closing this.
