### ISSUE TITLE
Mysticism: sharp reacalls old type-related buffer from somewhere?

### ISSUE THREAD

**Issue by greenais** [lovell/sharp#625]
My app uploads jpg/png files (type is restricted in app) to server, source image is saved to certain path (it works).
Then I apply following resize routine:

 ```
//Processing logo
              sharp(logoPath + '/logo_upload')
                .resize(640,120)
                .max()
                .toFormat('jpeg')
                .toFile(logoPath + '/logo.jpg', function(err, info) {
                  if (err) {console.error(err); throw (err)}
                  console.log('120 info: ', info)
                });
```

The issue is **very** strange:
1) I upload "1.jpg", sharp works - 1.jpg image resized/saved, no problem
2) upload "2.png", sharp works as well -  image resized/saved (always under the same name - logo.jpg)
3) upload "3.jpg", sharp resizes and saves "1.jpg" content (WTF?! from where?) 
After that no matter what I upload (source file logo_upload changes every time - I double-checked) - sharp output stays the same, "1.jpg" ((
Versions: sharp - 0.16.2, node - 4.4.5

Guys, what I'm doing wrong? What to consider to check in approach?

**Comment by lovell** [comment]
Hello, it looks like the input filename remains the same so you're probably seeing the effects of libvips' operation cache serving the previous contents to the processing pipeline.

http://sharp.dimens.io/en/stable/api/#sharpcacheoptions

Perhaps try adding the following before any processing:
```javascript
sharp.cache({files: 0});
```

**Comment by greenais** [comment]
Wow, you are right - that cache plays tricks.
Tried your suggestion, 
`sharp.cache({files: 0});`
doesn't work.

`sharp.cache({items: 0});`
does.

Probably it's a good idea to put this in FAQ.
Thank you for your great job and support.
