### ISSUE TITLE
libvips / node-gyp rebuild error

### ISSUE THREAD

**Issue by cewen** [lovell/sharp#626]
`npm install --verbose sharp` is failing on my Centos 6 environment. I'll add a full log below. Please help.

[error.txt](https://github.com/lovell/sharp/files/593280/error.txt)

**Comment by cewen** [comment]
I've run the manual installation script for libvips as well, to no avail...

**Comment by lovell** [comment]
The salient part of the error is `ERROR: glibc version 2.12 requires manual installation - please see http://sharp.dimens.io/en/stable/install/`

As the referenced URL says, you'll need to manually install libvips on Centos 6.

My strong recommendation here would be to use Centos 7 if you're able.

I'm unable to provide support for Centos 6, so will have to close this and wish you good luck!
