### ISSUE TITLE
Get meta data about actual transformation

### ISSUE THREAD

**Issue by qqilihq** [lovell/sharp#628]
(OT: `sharp` is awesome, thank you for your efforts!)

Is there some API available which can give me a set of meta data about applied transformations? I would like to store this data with along with my image, so that transformations can be re-applied later.

My use case is the following:

A user uploads an arbitrary image which is automatically scaled to 400 x 400 square dimensions using `resize` and `max`, additionally, we store the original image. 

We also provide an image cropper within the browser, which optionally allows the user to perform a custom cropping. When opening this image cropper, I would like to show the original image, but initialize the cropper to `sharp`'s automatically determined dimensions. Therefor I would need to know, how `sharp` placed the crop.

**Comment by lovell** [comment]
Hello, using `sharp(input).resize(400, 400).max().toBuffer()...` shouldn't result in any cropping. The length of the longest edge will equal 400 pixels and the length of the shortest edge will be less than or equal to 400 pixels.

I've probably misunderstood your question. Are you able to provide a fully worked example that highlights the missing data?

**Comment by qqilihq** [comment]
Hi Lovell,

thank you for quick response! In the meantime I spent some more time understanding our cropping library and sharp's APIs. So, reading my question again, it indeed sounds confusing even to me and was probably caused just because of my initial lack of understanding how the cropping works :)

Everything is working now as expected, so I'll close this one.

Best
Philipp
