### ISSUE TITLE
How to load Imagemagick formats

### ISSUE THREAD

**Issue by sachinwalia2k8** [lovell/sharp#629]
I am wondering if as part of installation do we need to specify any setting to allow linking Imagemagick / GraphicsMagick. I need support for PPM file conversion which I believe requires IM / GM.

**Comment by lovell** [comment]
Hello, you'll need to compile and install libvips with support for *magick, then install sharp so it detects the global libvips installation.

https://github.com/jcupitt/libvips#building-libvips-from-a-source-tarball

Good luck!

**Comment by sachinwalia2k8** [comment]
It worked after using local install of vips so closing this issue.
