### ISSUE TITLE
error on sharp.tile

### ISSUE THREAD

**Issue by hpze2000** [lovell/sharp#633]
**env: virtual box  centos 7** 

```js
sharp('file')
          .tile()
          .toFile(outputFilePath + 'output.dzi', function(err, info) {
            console.log(err);
            console.log(info);
          });
```

jpg filesize (139 MB), 21250px * 7950px

```
vips warning: vips_mapfile: map failed (Invalid argument), running very low on system resources, expect a crash soon
vips warning: vips_mapfile: map failed (Invalid argument), running very low on system resources, expect a crash soon
Error: vips_mapfile: unable to mmap
unix error: Invalid argument
vips_mapfile: unable to mmap
unix error: Invalid argument
```

**Comment by lovell** [comment]
Hello, the error suggests libvips is failing to mmap enough memory for an operation at [mapfile.c#L176](https://github.com/jcupitt/libvips/blob/master/libvips/iofuncs/mapfile.c#L176). The flags used for the mmap call include [MAP_SHARED](https://github.com/jcupitt/libvips/blob/master/libvips/iofuncs/mapfile.c#L162).

http://stackoverflow.com/a/18421071/4625124 suggests VirtualBox (sensibly) prevents memory sharing outside the hypervisor's boundary. Ensuring all file system operations use the guest drive should allow you to work within the security constraints of VirtualBox.
