### ISSUE TITLE
Advice Needed: How to create deep zoom image if I already have tiles?

### ISSUE THREAD

**Issue by Taytay** [lovell/sharp#636]
If I had a single large .tif, my understanding is that I could create a Deep Zoom image from this single large file quite easily by using the `tile` method: http://sharp.dimens.io/en/stable/api/#tileoptions

However, my large image is already split up into a regular grid of non-overlapping tiles. One approach would be to stitch this array of tiles into a single large .tif first. If I were to go that approach, I'm not sure that `sharp` has a method to stitch so many files, and if it did, I'm not sure that it exposes a way to do it without needing to have the entire final image in memory at some point. I'd love to be wrong on both of these points!

Essentially, I need to treat these tiles as the full-resolution image somehow, and then have the images further split and compressed to generate the various resolutions necessary for the Deep Zoom format. Do you have any advice on how to go about this with Sharp?

Many thanks.

**Comment by lovell** [comment]
Hi Taylor, rather than use sharp, `vips_arrayjoin` is probably your friend here. When vips is installed you can use it via the command line, for example the following will stitch 4 tiles into a 2x2 grid:

```sh
vips arrayjoin 1.png 2.png 3.png 4.png 2x2.png --across 2
```

**Comment by Taytay** [comment]
Thank you @lovell! I'll give it a shot!

**Comment by lovell** [comment]
Closing this as I think you now have an answer but please feel free to re-open if further help is required.
