### ISSUE TITLE
vips Command line vs sharp

### ISSUE THREAD

**Issue by rnanwani** [lovell/sharp#638]
The results for carrying out the same operation on an image (strip metadata and quality 80 jpeg) are significantly different.

Command Line = `vips copy voonik.jpg voonik-sharp.jpg[Q=80,strip]`
Sharp = `pipeline.quality(80).jpeg()` where pipeline is `sharp(originalImageBuffer)`.

The difference in the two images using the `identify` command can be seen here https://drive.google.com/open?id=0B3CnCQhw6PquMmN4Z1JKVGNtUXM

The visual difference can be seen here 
https://drive.google.com/open?id=0B3CnCQhw6PquQ1l6Z3FRYkRYNnc
![image-difference](https://cloud.githubusercontent.com/assets/4739557/20755286/6b02e132-b734-11e6-9dd5-626c73f8ff09.png)

The image generated with sharp https://drive.google.com/file/d/0B3CnCQhw6PquVHprRW1uOTB5MGs/view?usp=sharing

The image generated using vips cli
https://drive.google.com/file/d/0B3CnCQhw6PquQWh2UkNLS0hISFE/view?usp=sharing

The original image 
https://drive.google.com/file/d/0B3CnCQhw6PquUUU0eTBDUkJQcWM/view?usp=sharing

Can anyone suggest what is that that is being done differently that the images have slightly varying colors, though sharp is using the same vips module internally?

**Comment by lovell** [comment]
Hello, the original image has an embedded RGB profile so the pixel values should be considered linear RGB.

sharp always uses such a profile to convert to non-linear sRGB (via libvips+lcms) then strips the profile.

`vips copy voonik.jpg voonik-sharp.jpg[Q=80,strip]` will strip the RGB profile but not perform any colour conversion. `vipsthumbnail ...` will perform the colour conversion.

**Comment by rnanwani** [comment]
So is there a way to convert the output from sharp (or vipsthumbnail) to the output of vips-cli?

**Comment by lovell** [comment]
sharp currently always converts to sRGB, which can reduce the gamut, but does ensure the same output on all devices and browsers.

See #218 for discussion about how we should best expose the use of other colourspaces and profiles.

Remove the `strip` flag from your `vips copy ...` example to retain the profile in the output.

**Comment by rnanwani** [comment]
As of now, the approach used is to strip all metadata except color profile and use `.withMetadata()` in sharp. Closing this for now as 218 is being tracked.
