### ISSUE TITLE
tif compression

### ISSUE THREAD

**Issue by elgubenis** [lovell/sharp#641]
when i create a sharp from a base64 pngs buffer and do a toFile('a.tif') and then check the tif with tiffinfo i get the information that the Compression Scheme is JPEG but for another tool i use to put that tif into a pdf (hummus js) i need the tif to have a different compression (thats at least what i guess why it fails with sharps tif)

working tif's tiffinfo:
```sh
TIFF Directory at offset 0x7df0 (32240)
  Image Width: 1728 Image Length: 2376
  Resolution: 200, 200 pixels/inch
  Bits/Sample: 1
  Compression Scheme: CCITT Group 4
  Photometric Interpretation: min-is-white
  FillOrder: lsb-to-msb
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Rows/Strip: 2376
  Planar Configuration: single image plane
  DocumentName: Standard Input
  ImageDescription: converted PBM file
```

failing tif's tiffinfo (created using a png base64 buffer, and toFile with .tif extension:
```sh
TIFF Directory at offset 0x7df0 (32240)
  Image Width: 530 Image Length: 215
  Resolution: 28.34, 28.34 pixels/cm
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: JPEG
  Photometric Interpretation: RGB color
  Extra Samples: 1<assoc-alpha>
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 4
  Rows/Strip: 128
  Planar Configuration: single image plane
  JPEG Tables: (289 bytes)
```

sharps tif is viewable at does not seem corrupt on my os x fs, attached.
sharps tif: https://www.dropbox.com/s/g9krrehydqid2ch/636f85f0-b762-11e6-b401-951da7f96ed8.TIF?dl=0
working tif: https://www.dropbox.com/s/o9yiovn7mfweh48/CCITT_5.TIF?dl=0

**Comment by lovell** [comment]
Cross posted at https://github.com/galkahana/HummusJS/issues/123

**Comment by lovell** [comment]
Closing as cross-posted question is also closed.
