### ISSUE TITLE
Improve resize invalid parameter errors

### ISSUE THREAD

**Issue by spikeon** [lovell/sharp#642]
I was receiving data through a get request for the size of the output.  Passing it to sharp directly was creating a 500 error.  

> Error: Invalid width (1 to 16383) 200

I solved the issue by declaring my variable as:

`let size = req.params.size * 1;
`

It would be nice if resize would attempt to cast strings as int before sending out a 500 error, or at least change the error message to "Error: Width cannot be a string" to save developers the headache caused by reading the error message and going "200 IS BETWEEN 1 AND 16383 YOU &$@&#^@$#" like I did.

**Comment by spikeon** [comment]
Hell, just adding a note to the resize documentation on the lines about height and width that the parameter must be cast as an integer and making it bold would've been a huge help.

**Comment by lovell** [comment]
Hello, the current [resize docs](http://sharp.dimens.io/en/stable/api/#resizewidth-height-options) state `width is the integral Number of pixels wide...`

I've spent a lot of time recently improving the JSDoc comments, including around types and linking. For example, a parameter that is expected to be a JavaScript `Number` type links to the Mozilla JavaScript docs about the `Number` type. You can see an example of this, which will be included in v0.17.0, at http://sharp.dimens.io/en/latest/api-resize/#resize

> "&$@&#^@$#"

Please direct your energy about problems with JavaScript's dynamic typing into a Pull Request that improves the error reporting or documentation further.

As an aside, the intent of your code sample:
```javascript
let size = req.params.size * 1;
```
might be more clearly written as:
```javascript
const size = Number(req.params.size);
```

**Comment by lovell** [comment]
Commit 70a3d4f hopefully improves the error messaging for invalid resize parameters.

**Comment by lovell** [comment]
sharp v0.17.1 now available.
