### ISSUE TITLE
Lack of callback when loading unsupported images

### ISSUE THREAD

**Issue by almosnow** [lovell/sharp#645]
Hi,

As you may already know, when you load an invalid or unsupported image format you just get an error from the library (libvips I guess?).

Something like:

`Error: Input buffer contains unsupported image format
    at Error (native) null`

I have found no way to know if this had happened (at sharp) in order to react appropriately.

Any ideas on how to fix/workaround this?

**Comment by lovell** [comment]
Hello, sharp doesn't start to process the input until it needs to, so it's the callback passed to the output-triggering `toBuffer` or `toFile` that will receive an Error as the first parameter should the input is unsupported.

Perhaps an initial [metadata](http://sharp.dimens.io/en/stable/api/#metadatacallback) call would be more appropriate for your need?

**Comment by almosnow** [comment]
You are right, a call to metadata before issuing any *processing* command is all that's needed.

Thank you and thanks for sharp. 👌
