### ISSUE TITLE
Process CMYK images without converting to RGB

### ISSUE THREAD

**Issue by caesar** [lovell/sharp#647]
When Sharp loads an image it automatically converts it to sRGB.
I am using Sharp in a print pipeline, with mostly CMYK input files. I need to be able to process (resize, mostly) images with Sharp, without converting them to a different colourspace.

I am aware of the `toColourspace` function, however, I have a few problems with that as a solution.

The first problem is that I would *much* prefer not to convert my images to RGB and then back to CMYK, which is what Sharp seems to be going to do. I'd rather keep them in CMYK all the way through. Is this not a possibility?

Another, more minor, problem is that I have to use `metadata()` to find the current colourspace, and then call `toColourspace()` with the result and do all my further work inside the calback from `metadata()`. It introduces another layer of complexity – it would be nicer if keeping the existing colourspace was a simple option when the image was loaded.

The biggest problem at the moment though is it seems not to work...!
With this code (roughly):
```javascript
image.metadata().then((metadata) => {
	image.toColourspace(metadata.space)
		.resize(1024,1024).max().withoutEnlargement()
		.toBuffer().then((buf) => { vinylFile.contents = buf; })
});
```
I get the following error:
```
Error: vips_colourspace: no known route between 'srgb' and 'cmyk'
```

Do you have any idea what is causing that error?
I am on OS X 10.11.6. So far as I'm aware I don't have an installed `vips` beyond what is bundled with Sharp.

(I guess the first part of this is a feature request and the second part is a bug report, maybe they should be separate... sorry!)

**Comment by lovell** [comment]
Hello, did you see #218, which should improve the use of non-sRGB profiles and prevent unnecessary conversions?

**Comment by caesar** [comment]
Hi Lovell, thanks for the reply. I did find #218 and read through the discussion there, but I didn't find a solution there really.

Seemingly the `toColourspace` method was created as a result of the discussion on that issue, but it doesn't seem to work for me. Even using `toColourspace` as the first command after loading an image, the image is first converted to sRGB – and then Sharp (or vips) can't convert it back… Am I using it wrong?

There is also discussion on that issue of adding a further option to the `withMetadata` method – or (better, IMO) to the `sharp` constructor – to tell Sharp not to change the colourspace (I think) but seemingly that functionality hasn't been implemented yet. Or am I missing something?

**Comment by caesar** [comment]
Just added a comment on #218, which may be a better place to continue the discussion about maintaining the source colourspace.

But I am still unsure about one thing, so perhaps you could clarify: is CMYK output (nevermind what happens internally in terms of conversion to sRGB and back) implemented at all yet, or is the `toColourspace` function just a stub for the moment?

**Comment by lovell** [comment]
`toColourspace` as it stands definitely needs some attention, especially for non-(s)RGB use cases. As you've seen from the more recent comments on #218 this is starting to take on a more fully-formed API proposal so let's continue the discussion there.

**Comment by caesar** [comment]
Sure, happy to participate in the discussion there. I would have just commented there in the first place, except that I assumed the error I was getting was a bug – I hadn't realised it was simply as-yet-unimplemented functionality.
