### ISSUE TITLE
BPG support

### ISSUE THREAD

**Issue by mhf-ir** [lovell/sharp#648]
What about using BPG?
http://xooyoozoo.github.io/yolo-octo-bugfixes/

**Comment by lovell** [comment]
Hello, compressed image format support within sharp is via third-party loaders accessed through libvips.

The libbpg library provides logic only for the decoding side but I suspect most people would want the encoding side, so "BPG support" is very unlikely to happen.

Finally, the BPG format itself is based on H.265 and therefore is very likely to be patent encumbered.
