### ISSUE TITLE
Autorotate and updateFile, generated thumbnail uses old metadata

### ISSUE THREAD

**Issue by adriaanmeuris** [lovell/sharp#652]
I really love Sharp for image manipulation, but the thumnbail size is incorrect when generating it after updating a file on disk. When restarting node and generating the thumbnail again, the same code behaves correctly.

**Steps to reproduce**
1. autorotate a file based on the exif information (source file has exif orientation 6, portrait picture)
2. save the autorotated file to the original path
3. generate a thumbnail

For steps 1 and 2, I first tried following command:
`sharp(obj.path).rotate().toFile(obj.path);`

However, this throws following error:
`Cannot use same file for input and output`

I successfully changed this code to update the file on disk using fs:
```
sharp(obj.path).rotate().toBuffer().then(
  function (buffer) {
    return new Promise(function (resolve, reject) {
      // Write buffer
      fs.writeFile(obj.path, buffer, function (err) {
        if (err) {
          reject(err);
        } else {
          sharp(obj.path).metadata().then(
            function (meta) {
              // Update the metadata (with and height have switched)
              obj.meta = meta;

              // Resolve with the object
              resolve(obj);
            }
          ).catch(
            function (err) {
              reject(err);
            }
          );
        }
      });
    });
  }
);
```

**Next, step 3: resize this image to a width of 1000px and output it to a browser:**
```
sharp(path).resize(1000, null, {}).toBuffer(
  function(err, data) {
    res.writeHead(200, {'Content-Type': doc.mimetype});
    res.end(blob, 'binary');
  }
);
```

The image shown now is resized to 1000 x 750, which is wrong (calculated based on the dimensions before autorotating).

If I restart node and run step 3 (generating thumbnail) again, the image shown is 1000 x 1333, which is correct.

I guess maybe this is due to a caching mechanism in Sharp / Libvips which keeps the original dimensions for a specific path cached.

See attached the original file with exif + generated thumbnails (both incorrect and correct version).

**original file (with exif)**
![img_7023](https://cloud.githubusercontent.com/assets/16230038/21232333/796b1a24-c2eb-11e6-8138-27e9d0fbbb66.JPG)

**incorrect thumbnail**
![1000_wrong](https://cloud.githubusercontent.com/assets/16230038/21232332/7969d704-c2eb-11e6-8f04-d5dd80b68f06.jpeg)

**correct thumbnail**
![1000_right](https://cloud.githubusercontent.com/assets/16230038/21232334/796b606a-c2eb-11e6-9fb7-854019cd7c4e.jpeg)

Any ideas?

**Comment by lovell** [comment]
> "I guess maybe this is due to a caching mechanism in Sharp / Libvips which keeps the original dimensions for a specific path cached."

Spot on. [sharp.cache](http://sharp.dimens.io/en/stable/api-utility/#cache) can be used to modify/disable the libvips file cache.

**Comment by adriaanmeuris** [comment]
Thanks for your quick reply! I managed to fix the issue by disabling and re-enabling the cache after writing the file - since I want the cache to be used.

**Fix:**
```
sharp(obj.path).rotate().toBuffer().then(
  function (buffer) {
    // Remember old caching settings
    var oldCache = sharp.cache();

    return new Promise(function (resolve, reject) {
      // Write buffer
      fs.writeFile(obj.path, buffer, function (err) {
        if (err) {
          reject(err);
        } else {
          sharp(obj.path).metadata().then(
            function (meta) {
              // Update the metadata (with and height have switched)
              obj.meta = meta;

              // Set the sharp cache to false and back to the old cache
              sharp.cache(false);
              sharp.cache(oldCache);

              // Resolve with the object
              resolve(obj);
            }
          ).catch(
            function (err) {
              reject(err);
            }
          );
        }
      });
    });
  }
);
```

Is this a good approach?

And secondly, any chance I can reduce this code to something like:
`sharp(obj.path).rotate().toFile(obj.path);`

.. without throwing this error:
`Cannot use same file for input and output`

(I was thinking using clone / a pipeline, but I'm not familiar enough with that concept)

**Comment by lovell** [comment]
When using the file system, libvips concurrently reads from the input file and writes to the output file, hence this limitation.

`sharp.cache(false)` empties the cache so I'd probably just disable it altogether if you really need to write to the same path.

**Comment by adriaanmeuris** [comment]
Great, thanks thanks for your help!
