### ISSUE TITLE
overlayWith

### ISSUE THREAD

**Issue by iiAku** [lovell/sharp#653]
Hello,
Thanks for giving us such lib.
I am wondering how can I merge multiple images to a single one?
My input (assuming they are in the same folder): images input0.png, input1.png .... input7.png
I tried to use overlayWith in a chained way giving it the different images but it seems it does not work.

```
    sharp('output0.png')
      .overlayWith('output1.png', {
        gravity: sharp.gravity.southeast
      })
      .overlayWith('output2.png', {
        gravity: sharp.gravity.southeast
      })
      .quality(100)
      .toFile('merged.png', (err, info) => {
        if (err) {
          console.log(err)
        } else {
          console.log('it worked')
        }
      })
```
I also tried to merge partialy through a loop but it failing:

Merge of output0.png with output1.png => merged0.png
Merge of merged0.png with output2.png => merged1.png FAIL (corrupted file)
Merge of merged1.png with output3.png => merged2.png FAIL
Merge of merged2.png with output4.png => merged3.png FAIL
Merge of merged3.png with output5.png => merged4.png FAIL
Merge of merged4.png with output6.png => merged5.png FAIL
Merge of merged5.png with output7.png => merged6.png FAIL

Help will be apreciated 👍 . Do you have an idea about how I can achieve this?

NB: My files has some transparency, but they all have the same dimensions

**Comment by lovell** [comment]
Hello, only the parameters passed to the final call to `overlayWith()` will be applied.

See https://github.com/lovell/sharp/issues/405#issuecomment-208033263 for a possible `reduce`-based solution.

**Comment by iiAku** [comment]
Thanks you so much I'll test this that sounds good.
