### ISSUE TITLE
debian multiarch libvips-cpp.so path

### ISSUE THREAD

**Issue by kapouer** [lovell/sharp#655]
Hi,

on debian/stretch, the path is `/usr/lib/x86_64-linux-gnu/libvips-cpp.so`,
thus the check in binding.gyp fails.
Otherwise it compiles all right with system-installed vips 8.4.4.
That script is obscure to me, so i can't propose a PR.

**Comment by kapouer** [comment]
Haha
> pkg-config --variable libdir vips-cpp
> /usr/lib/x86_64-linux-gnu

**Comment by kapouer** [comment]
Could you release that ? I might find a minute to upload it in debian.

**Comment by lovell** [comment]
I should get some time for this after the new year. 🎆

**Comment by lovell** [comment]
@kapouer v0.17.1 est disponible maintenant.

**Comment by kapouer** [comment]
Merci
