### ISSUE TITLE
vips warning: VipsJpeg: error reading resolution

### ISSUE THREAD

**Issue by mahnunchik** [lovell/sharp#657]
I've faced with a lot of warnings like:
```
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
```

macOS 10.12.1
sharp@0.17.0
```bash
$ node -v
v6.7.0
```
libvips was downloaded by sharp

**Comment by lovell** [comment]
Hello, my best guess would be that this is related to https://github.com/jcupitt/libvips/pull/518 introduced in libvips v8.4.2.

These warnings are mostly harmless and can be ignored by setting the `VIPS_WARNING` environment variable.

(See also https://github.com/jcupitt/libvips/issues/544 for some future possible improvements around logging.)

**Comment by jcupitt** [comment]
Hi @mahnunchik, I'm the libvips maintainer. Could you post a sample image that produces a warning? I'd like to fix this, if I can.

**Comment by mahnunchik** [comment]
Hi @jcupitt 

Sample images:
* http://www.aranzadi.eus/fileadmin/images/micologia/Eskaneatuak/11_digital/Agaricus_abruptibulbus_paa_090619.jpg
* http://www.first-nature.com/fungi/images/agaricaceae/agaricus-silvicola1.jpg

Tell me If you need more images with the same behavior.

**Comment by jcupitt** [comment]
OK, I've removed the warning. This change will be in libvips 8.5. Thanks!

Your images have exif data but no exif resolution fields, even though they are required by the spec, since (I think) CS3 is assuming that readers will fall back to the jfif resolution settings. 

The libvips reader does this, so the warning for out of spec exif is probably not useful.

**Comment by jyotman** [comment]
@lovell version 8.5.1 has been released :1st_place_medal:. Check [here](https://github.com/jcupitt/libvips/releases/tag/v8.5.1).

**Comment by lovell** [comment]
Warning messages from libvips will be suppressed by default in sharp v0.18.0+, which will require libvips v8.5.2+. Please subscribe to #607 for details and updates.
