### ISSUE TITLE
GLib-CRITICAL (collision with pnquant?)

### ISSUE THREAD

**Issue by strarsis** [lovell/sharp#661]
sharp is used by gulp-responsive and resulting images are piped to imagemin-pngquant.

An error occurs when the quality string for pngquant contains a too narrow range (e.g. '80-90'):
````
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Command failed: /home/user/test/node_modules/pngquant-bin/vendor/pngquant --output /tmp/06882c02-6fe8-41d9-b706-3e8ab3eb2f17 /tmp/13322606-798c-4f90-b540-e384134c9280 --quality 90-100 --speed 3

    at /home/user/test/node_modules/execa/index.js:170:11
    at process._tickCallback (node.js:385:9)

(sharp:57559): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:57559): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed
````
Note the last two log lines where sharp is mentioned.

**Comment by lovell** [comment]
This error suggests the node process exited whilst libvips was in the middle of processing an image.

sharp runs libvips tasks on the libuv-managed threadpool, which doesn't wait for threads to join/complete when shutting down the node process. What you're seeing is one libvips thread attempting to read data from another thread that's already been destroyed due to the process exiting.

**Comment by strarsis** [comment]
So this is a pngquant issue as pngquant binary seems to exit with error code and 
imagemin-pngquant fails and the main script exits with an error.

**Comment by lovell** [comment]
The warning you're seeing is a side effect of processing images with sharp/libvips at the same time as something else calling `process.exit`, be that pngquant or anything else.

**Comment by lovell** [comment]
I notice imagemin-pngquant uses a Promise-based API. Perhaps you need to provide a `.catch( ... )` handler for any rejection?

**Comment by strarsis** [comment]
.catch is indeed used in the imagemin-pngquant module.
According to the error variable, pngquant binary exited with a specific code (https://github.com/pornel/pngquant#--quality-min-max).
The plugin should handle this instead failing.
