### ISSUE TITLE
How crop works?

### ISSUE THREAD

**Issue by ile** [lovell/sharp#662]
Hi,

I couldn't figure out if I can crop at arbitrary points, similarly as with [ImageMagick/GraphicsMagick](http://aheckmann.github.io/gm/docs.html):

```
crop
Crops the image to the given width and height at the given x and y position.

gm("img.png").crop(width, height, x, y)
```

So, I would like to crop a small portion of an image at exactly `x, y`. Is this possible?

Thanks.

**Comment by ile** [comment]
I just realized, that `extract` seems to do what I was asking.

I'll close this now as it's resolved. However, it's not totally clear what crop now does then :) Maybe make it more clear and point to the extract function from where the crop is explained?

**Comment by lovell** [comment]
Hello, you're not the first to run into the *magick crop vs libvips extract confusion.

I expect the existing `crop` function to soon be deprecated, instead becoming an optional parameter of the `resize` operation. Whether we (eventually) recycle `crop` to become a synonym for `extract` remains to be seen :)

**Comment by markgoho** [comment]
@lovell any update on this? I think it's pretty confusing to everyone coming from any kind of photo manipulation tool to have an API called crop that doesn't accept coordinates. Extract doesn't seem very intuitive either as the method for "cropping with coordinates" as indicated by a few Issues that ask how to crop with coordinates.

**Comment by lovell** [comment]
Please subscribe to #1135 for updates.
