### ISSUE TITLE
Stop processing of stream before completion

### ISSUE THREAD

**Issue by whats0n0** [lovell/sharp#665]
Is it possible to force stop the processing of a stream before it has completed?
Imagine that a user is uploading (streaming) an image through http which is directly piped through sharp, and that the upload stream suddenly ends because the image's file size exceeds the upload limit etc.

Then the sharp stream will not get any more data and the error below is thrown along with tons of vipspng "not enough data in buffer" errors.

Is there any way to stop the stream processing when the upload limit is reached?

```
vips warning: linecache: error in tile 0 x 3992
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not enough data in buffer
vipspng: not en
...
    at Error (native)
vips warning: linecache: error in tile 0 x 3992
vips warning: linecache: error in tile 0 x 3992
```

**Comment by lovell** [comment]
Hello, perhaps you could try piping through a byte-counting Transform stream such as [stream-meter](https://github.com/brycebaril/node-stream-meter).

This should take care of "unpiping" the sharp instance when the limit is reached and prevent the `end` event from triggering.

**Comment by whats0n0** [comment]
After looking through stream-meter i managed to find the issue, apparently busboy doesn't unpipe the stream correctly when reaching the limit so you have to do it manually. Thank you!
