### ISSUE TITLE
Maybe memory leak?

### ISSUE THREAD

**Issue by 2youyou2** [lovell/sharp#667]
Hi,
I was building a texture packer with sharp, and i use `sharp.overlayWith` to pack small pictures to a big picture.
I found the way to overlay multiple pictures to a picture in #405. But it seems this will increase memory usage to a huge number and memory will not be release.

Before pack textures: memory usage 88.8 m
![image](https://cloud.githubusercontent.com/assets/1862402/21677267/7390666a-d374-11e6-85a8-494dd5942430.png)

After pack textures: Memory usage 1.67 g
![image](https://cloud.githubusercontent.com/assets/1862402/21677275/7a9f914c-d374-11e6-8382-3081bec83bad.png)

I have also disable the cache with `sharp.cache(false)`, but it has no effect.

The example is here: https://github.com/2youyou2/electron-pitfalls
Please follow these steps:
- git clone https://github.com/2youyou2/electron-pitfalls.git
- npm install
- npm start sharp-memory

Thanks for looking this.

**Comment by lovell** [comment]
Hello, the first thing to try is to force a garbage collection.

Please can you start Electron with `--js-flags="--expose-gc"` then add a call to `gc` after processing is [complete](https://github.com/2youyou2/electron-pitfalls/blob/master/sharp-memory/index.html#L62-L65), e.g.:

```javascript
        input.then(data => {
          return Sharp(data, opts)
            .toFile(dest);
        }).then(global.gc);
```

**Comment by 2youyou2** [comment]
Hi, thanks for your reply.
Now can use `node ./run.js "sharp-memory/" --js-flags='--expose-gc'` to enable `global.gc`

I have updated the code to :
```javascript
        input.then(data => {
          return Sharp(data, opts)
            .toFile(dest);
        }).then(global.gc);
```
But it seems still have two problems:
- `global.gc` not clean all memory increase by sharp, still left about 200m. But if type `global.gc` in electron inspector console panel after all progress, it will clean all memory.

- Pack textures may use too much memory, the more textures the more memory alloc. In my case, memory usage may increase to 8g. So i add `global.gc` to every sharp progress to test, see [commit](https://github.com/2youyou2/electron-pitfalls/blob/f5269e22385661f116d71c95ba180f8518469bc6/sharp-memory/index.html#L57-L65). The memory will not grow too much, but i think it may cause window not stable?

**Comment by lovell** [comment]
The final `input` is still in scope when `then(global.gc)` is called so it will not yet be eligible for GC (6000 x 6000 x 4 = 144MB). When calling `gc` manually from the Electron inspector, `input` is no longer referenced so is eligible for GC.

The Node/Electron process will grab as much memory as it can before resorting to a GC. If you artificially limit the memory assigned to the process, it will trigger GC more often and free no-longer referenced Buffer data.

See #429 for a more thorough discussion of the memory usage with various versions of Node.

**Comment by 2youyou2** [comment]
Thanks for your answer! I fixed the problems.
