### ISSUE TITLE
32-bit Ubuntu 16.04 + yarn: Cannot find module '../build/Release/sharp.node'

### ISSUE THREAD

**Issue by eksperimental** [lovell/sharp#669]
I'm running Ubuntu 16.04 32bits,
I have installed libvips according to https://github.com/jcupitt/libvips#building-libvips-from-a-source-tarball

and i'm using yarn, NodeJS v7.4.0 with Node Version Manager.

```
module.js:472
    throw err;
    ^

Error: Cannot find module '../build/Release/sharp.node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/eksperimental/project/node_modules/sharp/lib/constructor.js:8:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

any ideas how to solve this?

**Comment by lovell** [comment]
Please can you provide the output of running `yarn add sharp --json` (removing any existing `node_modules/sharp` directory first).

**Comment by eksperimental** [comment]
sure. here's the output.
https://gist.github.com/eksperimental/55a0ac9ac1234f448c713c95988e18d7

**Comment by lovell** [comment]
Please can you try in an empty directory, without the existing package noise.

**Comment by alonoz** [comment]
Same issue on node v6.9.4 + npm 1.3.10
by `npm install` from package.json
How can we assist in debugging this?

**Comment by lovell** [comment]
@alonoz This issue is about yarn and 32-bit Ubuntu. Please open a new issue if you're still having problems once you've verified all of the [prerequisites](http://sharp.dimens.io/en/stable/install/#prerequisites) are installed.

**Comment by lovell** [comment]
@eksperimental Were you able to make any progress?

**Comment by samjbmason** [comment]
Yeah this does look like its blowing up on my heroku builds which I would I assume is because of the same thing as it is since we moved to yarn

**Comment by eksperimental** [comment]
@lovell sorry i have been superbusy and temporarily moved from that project. do you have a clean sample repo that I can install and see if this problem happens. I can run it straight away

**Comment by lovell** [comment]
@samjbmason This issue relates to 32-bit Ubuntu 16.04. I think Heroku is 64-bit Ubuntu 14.04 so please open a new issue with the Heroku build log if you're still having problems on that platform.

@eksperimental Please can you provide the results of running `yarn add sharp --json` in an empty directory on 32-bit Ubuntu 16.04.

**Comment by samjbmason** [comment]
This looks more like a know yarn problem and less specific on sharp. So nothing to worry about for now. 






On Fri, Feb 17, 2017 at 2:19 PM +0000, "Eksperimental" <notifications@github.com> wrote:












@lovell sorry i have been superbusy and temporarily moved from that project. do you have a clean sample repo that I can install and see if this problem happens. I can run it straight away

**Comment by lovell** [comment]
I've not seen any update that suggests this is a problem specific to this module but please do re-open if there is evidence to the contrary,
