### ISSUE TITLE
There should be a way to get the resulting image size / dimensions.

### ISSUE THREAD

**Issue by chanon** [lovell/sharp#67]
When using max() or withoutEnlargement() or giving only a width or a height, the user of sharp will not know the resulting image size.

For my project for example, I need to at least know the aspect ratio of the image which the resulting width and height can tell.
#32 covers getting the size before resize operation. This issue is about getting the size after the resize operation.

**Comment by ArashMotamedi** [comment]
Is there a way to get the width and height at any interim step? For example, after a resize operation, before a file is written.
