### ISSUE TITLE
PDF support?

### ISSUE THREAD

**Issue by nickroberts** [lovell/sharp#672]
I was wondering if there is PDF support. We are building an Electron app and our use case is that we need to convert a PDF to an image (could be multipage, as well) so we can print the image(s) using node-printer.

When I try to use sharp with a PDF, it says it is not supported (or invalid).

We need to be able to bundle everything with the Electron app, so it would be great if there were no external dependencies.

I'm also trying to work with node-gm and node-imagemagick-native, as well, to try to handle this. node-gm has ghostscript / graphicsmagick dependencies, and node-imagemagick-native does not work with multi-page PDFs.

I'm up for other suggestions, as well.

Great module, by the way!

**Comment by lovell** [comment]
Hello, libvips can be compiled with support for libpoppler, but its use of GPL would mean the source of your Electron app becomes GPL as it all runs in the same process.

To avoid runtime dependencies you'd need to build your own sharp-compatible pre-compiled binary tarball - see https://github.com/lovell/sharp/tree/master/packaging#using-a-custom-tarball - but it's not straightforward.

**Comment by nickroberts** [comment]
Thanks for your input! I think we are going to end up writing a service to do this in the long run, so it will take the conversion out of the app.

Good info to know, though! Thanks, again, and great work on this!

**Comment by supermoos** [comment]
Look like lipvips has a new option for loading pdf's: 

> "There’s a new, optional PDF loader based on Google’s PDFium project. libvips has had a PDF loader based on poppler-glib for a while, but the poppler GPL licence is unsuitable for some projects. This new PDFium loader should be more widely useful." - https://jcupitt.github.io/libvips/2018/07/26/What's-new-in-8.7.html

Is there any chance sharp could be updated to use this to enable pdf support by default?

**Comment by lovell** [comment]
@supermoos pdfium has made (and is still making?) breaking changes to its API so the libvips integration doesn't work at the moment anyway - see https://github.com/libvips/libvips/issues/957

In terms of adding to the pre-built binaries, I'd need to assess the build-time complexity and the extra download weight it brings; the shared libraries were huge (>50MB) when I last looked.
