### ISSUE TITLE
Keep transparency png to tiff conversion

### ISSUE THREAD

**Issue by iiAku** [lovell/sharp#677]
Hello,

Sorry If I misunderstood/misread the documentation, I tried to find an answer but I did not figure it out.
I am currently generating a background with transparency and composing it with multiple images at different positions with Sharp.

- Background is in PNG
- Images are in PNG
- Output should be in tiff (conserving transparency)

See test with a single overlay:

```
const sharp = require('sharp')
const gd = require('node-gd')
const img = gd.createSync(200, 200)
const transparency = img.colorAllocate(255, 255, 255)
img.colorTransparent(transparency)
img.saveFile('test.png', (err) => {
 if (err) {
   console.log(err)
 } else {
   sharp('test.png')
   .tiff({quality: 100, force: false})
   .overlayWith('overlay.png', { gravity: sharp.gravity.center } )
   .toFile('test.tiff', (err, info) => {
       console.log('test.tiff saved')
     })
 }
})
```
![capture d ecran 2017-01-11 a 11 27 22](https://cloud.githubusercontent.com/assets/21042952/21844972/04bf55c6-d7f1-11e6-9bfe-1373949e0aaa.png)

Each time I'm doing this (only with tiff, it  works with png), the transparency is gone and I have a black bacground. How can fix this and keep transparency while exporting in tiff?

**Comment by lovell** [comment]
Hello, please see #594

**Comment by iiAku** [comment]
Thanks you 👍
