### ISSUE TITLE
Ubuntu 12.04: Dependencies

### ISSUE THREAD

**Issue by gooor** [lovell/sharp#683]
"OS X, Windows (x64), Linux (x64, ARM) systems do not require the installation of any external runtime dependencies." - what do you mean by that? - it fails on Ubuntu 12.04 on missing libvips - so does it indeed need runtime dependency or  not?

**Comment by lovell** [comment]
http://sharp.dimens.io/en/stable/install/#linux

At `npm install` time, 64-bit Linux with glibc v2.13+ will retrieve pre-built runtime dependencies if a recent enough version of libvips is not found globally via `pkg-config`.

glibc v2.13+ means that Debian 7 and Ubuntu 12.04 are included, but e.g. Centos 6 is excluded. https://en.wikipedia.org/wiki/GNU_C_Library#Version_history

If you're seeing failures with x64 Ubuntu 12.04, please provide the output of running `npm install --verbose sharp`.

**Comment by gooor** [comment]
I was digging around and ended up with compiling libvips. I'm using sharp in Meteor app, and on production bundle it was messing around with paths and it couldn't find libvips in vendor. I'm closing as it's related to meteor rebuild process.

**Comment by mdorn** [comment]
@gooor I'm having trouble with a Meteor build for an app that uses sharp as well -- could you please provide some more details here as to what you ended up doing? I'm deploying to Galaxy but developing on OSX so I'm worried that doing my own compilation might not work anyway.
