### ISSUE TITLE
Error: VipsImage: memory area too small --- should be N bytes, you passed 0

### ISSUE THREAD

**Issue by tjwoon** [lovell/sharp#686]
Hi

I am trying to use this library on a Raspberry Pi 3. Every time I run the toFile() function, I get this error:

`Error: VipsImage: memory area too small --- should be N bytes, you passed 0`

(N changes based on image dimensions).

I have tried the following versions:

- 0.17.1
- 0.16.0
- 0.15.0

The following failed to install (node-gyp rebuild error):

- 0.14.0
- 0.13.0
- 0.12.0
- 0.11.0

(I believe v0.12.2 did install fine once shortly before, but as of this writing, running `npm install sharp@0.12.2` fails...)

I am using NodeJS v6.9.1, downloaded from the NodeJS website. ARMv7 version.

Is it likely my native compiler toolchain is not setup correctly? Could you point me in the correct direction?

Thanks & Regards,
TJ

**Comment by lovell** [comment]
Hello, what input are you using with the `sharp()` constructor? The `memory area too small` error suggests raw pixel data. Are you able to provide a complete code sample that fails?

**Comment by tjwoon** [comment]
Sorry, it looks like I was calculating the size of my images incorrectly. It is working now that I am passing in the correct values for raw.width and raw.height.

Apologies for the mistake!
