### ISSUE TITLE
When converting png to jpeg, transparent areas are filled with black.

### ISSUE THREAD

**Issue by almosnow** [lovell/sharp#687]
I'm using sharp to convert images to jpeg. However, when I supply a png with transparent regions the resulting jpeg has these areas filled in with black.

Can one change the default black color that sharp applies on these situations?

I tried using .background({ ... }) before the conversion, but no luck yet.

**Comment by lovell** [comment]
Hello, did you see the [flatten](http://sharp.dimens.io/en/stable/api-operation/#flatten) operation?

**Comment by almosnow** [comment]
.background(...).flatten().jpeg(...) works flawlessly.

Thank you!

**Comment by jyotman** [comment]
Hey, @lovell I'm using `.background({r: 0 g: 0, b: 0, alpha:0}).flatten().jpeg({quality: 30});` but still getting black background. Any idea what I'm doing wrong? Thanks!

**Comment by lovell** [comment]
@jyotman Your example attempts to flatten to a fully-transparent [background](http://sharp.dimens.io/en/stable/api-colour/#background) (`alpha: 0`), which has no effect, then converts to the JPEG format which doesn't support transparency. Please open a new issue if you're still having problems.
