### ISSUE TITLE
API changes to support further interpolators (was: Bicubic interpolation causes a grid artifact on images)

### ISSUE THREAD

**Issue by chanon** [lovell/sharp#69]
This is the original image:
![dsc03591](https://cloud.githubusercontent.com/assets/357737/3655315/cb69fe80-1177-11e4-9e12-4bcc395c66f6.JPG)

This is the image resized to 1840 width with bicubic interpolation at 100 quality:
![bg9_2080_1384](https://cloud.githubusercontent.com/assets/357737/3655351/7bd11902-1178-11e4-9266-a5c81c500161.jpg)

This is the image resized to 1840 width with the default (bilinear?) interpolation at 95 quality:
![bg9_2080_1384 1](https://cloud.githubusercontent.com/assets/357737/3655358/9caed164-1178-11e4-86bd-0886b462f3a9.jpg)

The bicubic interpolated version, when viewed at 100%, if you look closely at the blue sky, there is a grid of artifacts covering the whole sky.

**Comment by Xaekai** [comment]
What happened to nohaloInterpolation?
