### ISSUE TITLE
Would it be possible to make sharp().metadata() contain image size

### ISSUE THREAD

**Issue by Vispercept** [lovell/sharp#695]
It would be great if one doesn't have to call `toBuffer()` to gather information about an image size. 

Instead of doing something like that:
```javascript
sharp()
.toBuffer((err, buf, info) => {
  console.log(info.size)
});
```

it would be great to receive the size as an property when calling `sharp().metadata()`. The advantage would be that one doesn't have to work on buffers and can instead get the size by using just the stream.

**Comment by lovell** [comment]
Hello, this should be fairly straightforward to add, thank you for the suggestion.

Ideally we would extract and make common the logic currently in [pipeline.cc](https://github.com/lovell/sharp/blob/master/src/pipeline.cc#L966-L975) so it can also work with [metadata.cc](https://github.com/lovell/sharp/blob/master/src/metadata.cc#L68).

```javascript
sharp().metadata().then( ({ size }) => console.log(size) );
```

**Comment by KaptaanBarbosa** [comment]
I need to create new image with updated metadata  and create empty file but how to add updated metadata in new image

**Comment by lovell** [comment]
v0.21.0 now available with this feature.

**Comment by shaneharris** [comment]
I'm using `"sharp": "^0.21.0"` from npm and this property doesn't seem to exist when i read from the filesystem at least:

```javascript
 sharp('image_path')
    .metadata()
    .then(metadata=>{
        console.log(metadata.size); // undefined
    });
```
