### ISSUE TITLE
[Question] How to copy alpha channel to RGB?

### ISSUE THREAD

**Issue by tannerhodges** [lovell/sharp#696]
Hi @lovell, thanks for making such an awesome tool. Really appreciate all your work.

## Problem

I'm using sharp for a gulp task that creates alpha masks for transparent PNGs. At first I used [`threshold`](http://sharp.dimens.io/en/stable/api-operation/#threshold) to convert all the non-black pixels to white, but that crushes semi-transparent values and drops black values altogether:

```js
image.clone().threshold(1).toBuffer((error, output, info) => { ... }
```
([Here's the full source code.](https://github.com/tannerhodges/gulp-zorrosvg/blob/aefe55448ff092781f0b1edebf00206eb854addf/index.js#L83-L102))

For example, the following `source.png` should produce `output-correct.jpg` but currently produces `output-incorrect.jpg`:

| `source.png` | ✅ `output-correct.jpg` | ❌ `output-incorrect.jpg`
|:--|:--|:--|
| ![smoke4](https://cloud.githubusercontent.com/assets/1619485/22492027/7a553102-e7f5-11e6-8060-56e5ed5675dc.png) | ![smoke4-mask-correct](https://cloud.githubusercontent.com/assets/1619485/22492026/7a538f5a-e7f5-11e6-9845-b40be0f92cb0.jpg) | ![smoke4-mask-incorrect](https://cloud.githubusercontent.com/assets/1619485/22492028/7a557be4-e7f5-11e6-972c-55e41f263c5e.jpg) |

## Attempted Solutions

I thought I could manually update the values of `toBuffer`'s `output` like this:

```js
for (var i = 0; i < output.length; i += 4) {
  // Use alpha channel to define luminance 
  output[i + 0] = output[i + 3];
  output[i + 1] = output[i + 3];
  output[i + 2] = output[i + 3];
  output[i + 3] = 255;
}
```

### Error Messages

But I keep getting the following error:

```bash
$ gulp zorrosvg
[20:51:43] Starting 'zorrosvg'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: ✘ File `smoke4.png`: Input buffer contains unsupported image format
```

And depending on the image that error changes:

```bash
$ gulp zorrosvg
[20:57:50] Starting 'zorrosvg'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: ✘ File `smoke2.png`: Input buffer contains unsupported image format

(sharp:36492): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:36492): GLib-CRITICAL **: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed

(sharp:36492): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed
Segmentation fault: 11
```

### Other Issues

I thought maybe it was similar to #680 and [forcing the addition of an alpha channel](https://github.com/lovell/sharp/issues/680#issuecomment-272235682) would help, but that produced the same errors as above.

I also tried tweaking your [`joinChannel` example](https://github.com/lovell/sharp/issues/680#issuecomment-272682318) but couldn't figure out how  it works exactly. I assume there's a way to join a layer of white pixels?

Thanks again for all your work. Appreciate the help.

**Comment by lovell** [comment]
Hello, if you need uncompressed pixel data then [raw](http://sharp.dimens.io/en/stable/api-output/#raw) is your friend.

You can use it with [greyscale](http://sharp.dimens.io/en/stable/api-colour/#greyscale) and [toColourspace('b-w')](http://sharp.dimens.io/en/stable/api-colour/#tocolourspace) for single channel (greyscale) output.

For a RBGA input image, [extractChannel(3)](http://sharp.dimens.io/en/stable/api-channel/#extractchannel) should give you the alpha channel.

**Comment by tannerhodges** [comment]
Awesome, thanks! I'll try `extractChannel(3)` and close this for now. Will re-open if I have any more questions.

**Comment by tannerhodges** [comment]
Just following up with what solved my problem:

Realized I was just confused about how to convert the `raw` buffer back to a sharp instance. [@smremde's example](https://github.com/lovell/sharp/issues/552#issuecomment-243452196) helped me figure it out. The [`options.raw`](http://sharp.dimens.io/en/stable/api-constructor/#sharp) property was what I had missed:

```js
sharp(buffer, { raw: { width: info.width, height: info.height, channels: info.channels } })
```

Here's what I ended up with:

```js
sharp(file.contents).raw().toBuffer(function(error, buffer, info) {

  // Create a luminance mask based on the original image's alpha channel
  for (let i = 0; i < buffer.length / 2; i = i + 4) {
    let alpha = buffer[i + 3];
    buffer[i + 0] = alpha;
    buffer[i + 1] = alpha;
    buffer[i + 2] = alpha;
    buffer[i + 3] = 255;
  }

  // Compress as JPG
  sharp(buffer, { raw: { width: info.width, height: info.height, channels: info.channels } })
    .jpeg().toBuffer(function(error, finalBuffer, finalInfo) {

    // Pipe new file to gulp stream
    callback(null, new gutil.File({
      cwd: file.cwd,
      base: file.base,
      path: file.path.replace('.png', '.jpg'),
      contents: finalBuffer
    }));
  });
});
```

[Full source code.](https://github.com/tannerhodges/gulp-zorrosvg/blob/76b907ad855979b354f0fc64ae0a8ec9e12e9d88/index.js#L78-L147)
