### ISSUE TITLE
EXR support?

### ISSUE THREAD

**Issue by viridia** [lovell/sharp#698]
I've been using sharp to do some simple image processing, but my company is an animation studio and we need EXR support. The underlying libvips library supports EXR, how difficult would it be to expose this functionality in sharp?

**Comment by jcupitt** [comment]
libvips EXR support isn't great. It was added using the C API to OpenEXR, which (at the time anyway, perhaps it's better now) did not support features like colour management. libvips now supports C++ operators, so the EXR loader could be rewritten to use the much better OpenEXR C++ API. 

If your needs are basic, current libvips EXR might be good enough. I'd do some experiments at the command line first to try it out.

**Comment by lovell** [comment]
sharp can take advantage of a globally-installed copy of libvips that has been compiled with EXR support.

However the EXR loader will need exposing in [DetermineImageType](https://github.com/lovell/sharp/blob/master/src/common.cc#L139) before sharp can use it.

**Comment by lovell** [comment]
v0.26.2 now available with this feature, which requires use of a globally-installed libvips compiled with support for OpenEXR.

**Comment by zigabostner** [comment]
Is there currently any way how the writing of EXR files could be done in sharp?

**Comment by AndrewRayCode** [comment]
[The libvips readme](https://github.com/libvips/libvips) says that it comes with OpenEXR support. There is an `openexr` [(meson?) option](https://github.com/libvips/libvips/blob/3698b934969b00e8d7497186d64f8f18a49b68cf/meson_options.txt#L146-L149) with the value of `auto` - does this mean that modern versions of lipvips support exr out of the box?

On my Amazon EC2 instance, which is Amazon linux, I tried to run
```js
const fs = require('fs');
const sharp = require('sharp');
sharp('./myfile.exr').jpeg({ mozjpeg: true }).toBuffer().then(data => fs.writeFile('./hi.jpg', data))
```

Which raises the error

> Uncaught Error: Input file contains unsupported image format

How can I confirm if

> has been compiled with EXR support

 on Linux?

**Comment by lovell** [comment]
@AndrewRayCode Reading EXR files requires the use of a globally-installed libvips compiled with support for OpenEXR. You can run `vips -l VipsForeignLoad` at the command line to view the file types available for input.

**Comment by AndrewRayCode** [comment]
I'm sure you don't want to provide support for vips, I'm trying to document instructions for others to follow to get this working.

On Debian, I ran 
```
sudo apt install libvips
sudo apt install libvips-tools
```

Your command did not work:

```
vips -l VipsForeignLoad
vips: 'VipsForeignLoad' is not the name of a vips class
```

But I do see exr (?support?)
```
vips -l | grep exr
        VipsForeignLoadOpenexr (openexrload), load an OpenEXR image (.exr), priority=200, is_a, get_flags, get_flags_filename, header, load
```

However same result in node:
```
> const sharp = require('sharp'); const fs = require('fs');
> sharp('./file.exr').jpeg({ mozjpeg: true }).toBuffer().then(data => fs.writeFile('./hi.jpg', data))
Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 309,
  [Symbol(trigger_async_id_symbol)]: 307
}
> Uncaught Error: Input file contains unsupported image format
    at Sharp.toBuffer (/var/www/site/node_modules/sharp/lib/outp
```

There is no information available online about how to compile vips with EXR support, but it looks like vips natively supports exr now? If that's true then I'm not sure how to debug further.

**Comment by lovell** [comment]
@AndrewRayCode You'll need to build sharp from source too so it can link against the globally-installed libvips - please see https://sharp.pixelplumbing.com/install#building-from-source
