### ISSUE TITLE
jpeg output is not compatible with some software

### ISSUE THREAD

**Issue by weijarz** [lovell/sharp#700]
I found jpeg images generated by sharp are not compatible with some software.

The `file` command output of sharp generated image is different from images generated by other image lib (jimp/gimp/PIL etc),  there is no `JFIF standard 1.01, aspect ratio, density 1x1` prefix.

```sh
$ file other.jpg sharp.jpg 
sharp.jpg: JPEG image data, baseline, precision 8, 1080x565, frames 3
jimp.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 800x391, frames 3
```

```js
// "sharp": "^0.17.1"
export default async function compressImage(data) {
    const destData = await sharp(data)
        .limitInputPixels(MAX_PIXELS)
        .resize(MAX_WIDTH, MAX_HEIGHT)
        .background('white')
        .max()
        .withoutEnlargement()
        .flatten()
        .jpeg({quality: 65})
        .toBuffer()
    return await destData
}
```

**Comment by lovell** [comment]
Hello, the JFIF standard (rather than the JPEG standard) requires a [mandatory APP0 metadata](https://en.wikipedia.org/wiki/JPEG_File_Interchange_Format#JFIF_APP0_marker_segment) chunk. Adding [withMetadata](http://sharp.dimens.io/en/stable/api-output/#withmetadata) should do this.

Are you able to provide an example of "some software" that can't handle APP0-less JPEG?

**Comment by weijarz** [comment]
@lovell Thank you, it works now. 

Amazon Kindle (E-Ink version)'s builtin .mobi viewer (in periodical mode) does not show images without metadata.

**Comment by zhongyao-x** [comment]
> ```js
> withoutEnlargement
> ```

请教一下，怎么写的我也遇到这个问题

**Comment by zhongyao-x** [comment]
> @lovell Thank you, it works now.
> 
> Amazon Kindle (E-Ink version)'s builtin .mobi viewer (in periodical mode) does not show images without metadata.

请教一下，怎么写的我也遇到这个问题

**Comment by zhongyao-x** [comment]
@weijarz  请教一下最后怎么解决的，我也遇到相同的问题，该如何配置 withMetadata

**Comment by weijarz** [comment]
@zhongyao-x 不需要配置啊，只直接一个空参数调用 .withMetadata() 就可以了。

**Comment by penndev** [comment]
> @zhongyao-x 不需要配置啊，只直接一个空参数调用 .withMetadata() 就可以了。

这样生成的图片都是 exif 的格式，但是有些老设备必须 jfif，也就是 e0 开头的才能展示，exif是 e1。 看了半天也没找到配置jfif的选项。
