### ISSUE TITLE
Confusing behaviour of `force`parameter in output

### ISSUE THREAD

**Issue by rnanwani** [lovell/sharp#706]
Consider a pipeline which has a WebP image buffer as input

```
pipeline.jpeg().jpeg({chromaSubsampling: '4:4:4', force: false})
```
This leads to an output image in WebP format (input format) because the call with `force = false` comes second.

This is because the `_updateFormatOut` function sets the output format to 'input' if `force=false` regardless of the previous value.

Is this behaviour intentional? Or should there be a check on the existing output format value before changing it in `_updateFormatOut` function?

**Comment by lovell** [comment]
Hello, in this case I think the behaviour is expected as the use of `force: false` means "use the input format". Like with (most) other repeated operations, the most recently provided settings will "win".

Did you see https://github.com/lovell/sharp/issues/659#issuecomment-272688339 ?
