### ISSUE TITLE
Can libvips do "unsharp-mask"?

### ISSUE THREAD

**Issue by Algae666** [lovell/sharp#708]
I'm looking into using sharp as a Scene7 replacement, and unsharp-mask is the only feature I've come across so far that I can't figure out how to reproduce with sharp.

**Comment by lovell** [comment]
Hello, the existing [sharpen](http://sharp.dimens.io/en/stable/api-operation/#sharpen) operation can accept optional `sigma`, `flat` (m1) and `jagged` (m2) parameters to do this.

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-convolution.html#vips-sharpen

**Comment by Algae666** [comment]
Is there a way to control the radius? It doesn't look like VIPS exposes that in the sharpen API...

**Comment by lovell** [comment]
http://sharp.dimens.io/en/stable/api-operation/#sharpen

> `sigma` **[Number](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number)?** the sigma of the Gaussian mask, where `sigma = 1 + radius / 2`.

**Comment by Algae666** [comment]
Ah, so I guess what I'm really missing is not the radius, but the "amount" param from Scene7:
http://crc.scene7.com/is-docs/pages/HTTP-Protocol-Reference.htm#_op_sharpen_Sharpen_Image
I guess there is no equivalent.

**Comment by lovell** [comment]
The `amount` value looks most like libvips' `m2`, which is exposed in sharp as `jagged`.

You can experiment with all of the [libvips sharpen options](http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-convolution.html#vips-sharpen), including the not-yet-exposed `x1`, `y2` and `y3`, using the command line:
```sh
vips sharpen in.jpg out.jpg --sigma 0.5 --x1 2 --y2 10 --y3 20 --m1 0 --m2 3
```
@jcupitt can probably help further.

**Comment by Algae666** [comment]
Thanks, that helps!

**Comment by lovell** [comment]
Closing as I hope the original question has been answered.
