### ISSUE TITLE
Question: Is it possible to autoOrient Images?

### ISSUE THREAD

**Issue by kabirbaidhya** [lovell/sharp#711]
Hi, I'm wondering if it's possible to `autoOrient` images with sharp? 

For instance with the [`gm`](https://github.com/aheckmann/gm) package it's possible to do this but it needs imagemagick. How do we do similar thing with sharp?

```javascript
// auto-orient an image
gm('/path/to/img.jpg')
.autoOrient()
.write('/path/to/oriented.jpg', function (err) {
  if (err) ...
});
```

**Comment by lovell** [comment]
Hello, did you see the [rotate](http://sharp.dimens.io/en/stable/api-operation/#rotate) operation?

**Comment by kabirbaidhya** [comment]
Okay, seems like it's possible with a little tweak. Thanks.

**Comment by lovell** [comment]
> "with a little tweak"

Are you able to expand on this comment? Is there something that could be improved?

Your example, using sharp instead of gm, would look something like:
```javascript
// auto-orient an image
sharp('/path/to/img.jpg')
  .rotate()
  .toFile('/path/to/oriented.jpg', function (err) {
    if (err) ...
  });
```

**Comment by kabirbaidhya** [comment]
Yes, the above code just did work fine as expected. 
Just the difference was `gm` would overwrite the original file with the auto-oriented result. And `sharp` would return new result and we had to do `toFile` to save it to new file. 

So, we just had to do little tweak to fit our needs but that really wasn't a big deal.
