### ISSUE TITLE
Converting tiff to png

### ISSUE THREAD

**Issue by RomanZaiats** [lovell/sharp#712]
I have tiff image with 200 pages. How can i get needed page or all pages in png format? 
When i do convert to png result always will be first page

**Comment by lovell** [comment]
Hello, please see #654 for a PR-in-progress that will expose the ability to select a given page for TIFF-based input.

**Comment by RomanZaiats** [comment]
Thanks! Is it works with stream?  
can i write something like "var image = sharp(readStream, {page:4})" ?

**Comment by RomanZaiats** [comment]
sharp('D:/cps/images/manypages.tif', {page: 4}).png().toFile('D:/cps/images/output_4page.png', function(err) {
            if(err) console.log(err);
        });
This code doesnt work(
sharp version "^0.17.1"

**Comment by lovell** [comment]
This feature is a proposed Pull Request that requires further work before it can be merged and released.

**Comment by RomanZaiats** [comment]
Thank you very much!
