### ISSUE TITLE
Large SVG input image creates an empty image

### ISSUE THREAD

**Issue by kimmobrunfeldt** [lovell/sharp#715]
I'm trying to convert a very large SVG canvas to a png file. Its size is width: 8268px, height: 11811px. I'm using sharp@0.17.2 on OS X 10.10.5 (16GB RAM) with node 4.5.0 version (also verified with 6.7.0). When using a smaller density, such as 280, the image is saved correctly but density 300 fails. 

I don't get any errors, just an empty result as image.png. Why could this be happening? ~~Another thing I was wondering is that why does the density setting actually affect the file size? I have thought that DPI is only metadata for png files and it shouldn't affect the file size.~~ edit: it doesn't affect the file size when pixel dimensions are the same, I tested it incorrectly.

I created a new repository where this case is separated and testable:
https://github.com/kimmobrunfeldt/node-sharp-error-case. Beware: the repo includes a huge >90MB earth.png file.

To reproduce, run:

```
git clone https://github.com/kimmobrunfeldt/node-sharp-error-case.git
cd node-sharp-error-case
npm i
# Downloads a large earth image and resizes it to correct size
bash install.sh  

# This is the actual failing script
node case.js
```

**Comment by lovell** [comment]
Hello, there's a chain of shared libraries involved here. The precompiled libvips provided with sharp will open SVG files using librsvg, which will load embedded images with gdk-pixbuf, which will use libjpeg to decode the JPEG image.

I believe gdk-pixbuf will attempt to decompress the full JPEG image into memory, which I'd estimate at ~340MB for your example JPEG image. I suspect this will then be copied as it passes through each library, with an alpha channel being added somewhere along the way.

My best guess would be that one of these is silently failing or swallowing an error, possibly related to a maximum dimension or memory limit being tripped. It might take a while to track down where this is happening :(

**Comment by kimmobrunfeldt** [comment]
@lovell Ok thanks for sharing.

**Comment by CesarLanderos** [comment]
I am also experiencing this but with `toBuffer`, obviously there is no relation between those 2 functions, i have a big svg as well which i then set its density to 300 when converting it to png. I do get an error because this setting get to the pixel limit, so if i lower the dpi to 200, the convertion does “works”, but i get an empty image, if i use a dpi of 72 or 100, the png renders correctly, i havent tested what happens if i convert the svg to jpg with this setting

**Comment by jcupitt** [comment]
Hello, huge SVG rendering (>32767 pixels on the horizontal axis) is now fixed in libvips master, see the issue above.

**Comment by lovell** [comment]
@jcupitt Brilliant, thanks John.

**Comment by lovell** [comment]
sharp v0.19.0 with libvips v8.6.1 now available.
