### ISSUE TITLE
Checking Quality of a webp image

### ISSUE THREAD

**Issue by rnanwani** [lovell/sharp#716]
Might be a stupid thing on my part, but I am not able to check for a WebP image's quality level using `sharp.metadata()` or `identify -verbose`. Pointers will be appreciated.

**Comment by lovell** [comment]
Hello Rahul, as far as I know, the value of the "quality" setting is not preserved in a WebP file.

At WebP compression time, the "quality" setting is used to control the level of quantisation in the VP8 encoder (lower quality = quantise more = discard more data). Given this step is adaptive and splits the image into (up to) four regions, I'm not sure it's even possible to reverse engineer a single value given the compressed data.

**Comment by lovell** [comment]
Closing this as I hope your question has been answered, even if that answer is only "sorry, not possible".
