### ISSUE TITLE
Using BMP format input images on Heroku

### ISSUE THREAD

**Issue by jonnathan002** [lovell/sharp#717]
Im trying to load the 2 JPGs metadata from the following urls as buffers

http://artwork-cdn.vubiquity.com/P/V_EPIK_POST0000000003281596.jpg

http://artwork-cdn.vubiquity.com/P/H_EPIK_TVNC0000000001049578.jpg

the first one works perfectly but the second one throws this error

Error: Input buffer contains unsupported image format

I have no idea whats going on, can someone help me?

**Comment by lovell** [comment]
Hello, the second image is in the BMP format (rather than JPG).
```sh
$ file H_EPIK_TVNC0000000001049578.jpg 
H_EPIK_TVNC0000000001049578.jpg: PC bitmap, Windows 3.x format, 320 x 240 x 24
```

**Comment by jonnathan002** [comment]
is there anything i could do for it to work with sharp? ( i just need to retrieve the height and width )

**Comment by lovell** [comment]
Support for the BMP format is available in sharp if there's a globally-installed copy of libvips that has been compiled with *magick support.

**Comment by jonnathan002** [comment]
would it work on heroku if i added this buildpack?

https://github.com/alex88/heroku-buildpack-vips

it seems a bit outdated

**Comment by lovell** [comment]
Perhaps try a fork, e.g. https://github.com/the-grid/heroku-buildpack-vips/tree/update-vips-8.4.5

**Comment by sagivf** [comment]
@lovell Thanks for this module! 

I to am having a similar issue:
![image](https://cloud.githubusercontent.com/assets/1857466/24145742/3b6b6198-0e3b-11e7-8f87-e3c280b078b0.png)

I to am using heroku and when running `sharp.versions` I get the same result with or without the buildpacks (both alex88 and the-grid#update-vips-8.4.5). Seems like it's using the binaries that come with node and ignoring the buildpacks binaries.

Running from my mac this never happens.

I noticed that "jpeg": "8.4" is different then "jpeg”: "1.5.1" which I get on heroku.

Perhaps you have advice?
Thanks in advance

**Comment by lovell** [comment]
@sagivf Is your input image in BMP format? My best guess for the version difference would be that you've run `npm install` on an OS X machine then checked in `node_modules` and are attempting/failing to use them on Linux/Heroku.

**Comment by lovell** [comment]
@sagivf This issue was about a BMP input file that required the use of a buildpack with libvips compiled with *magick. The [sharp.versions logic](https://github.com/lovell/sharp/blob/master/lib/constructor.js#L23) is pretty simple. Please open a new issue if you're still having problems.

**Comment by sagivf** [comment]
OK, from [sharp.versions logic](https://github.com/lovell/sharp/blob/master/lib/constructor.js#L23) I understand that the buildpack should install the libs inside the `node_modules/sharp/vendor/lib` right? Maybe https://github.com/alex88/heroku-buildpack-vips/pull/26 fixes the issue.
I will do some more tests and see if there is a need for a new issue, thanks 👍

**Comment by sagivf** [comment]
@lovell just a quick FYI.
1) Seems like my issue was the Heroku server piping an image from a url resource to the s3 via sharp. The connections was being cut off, not sure why this was the result. Switching to a dedicated server fixed the issue.
2) I'm not sure regarding the described `heroku buildpack`, not that it's really up to you but:
  a) It works without them
  b) If the buildpacks are there for using different vendor versions I couldn't get it to work, not very 
      clear how to use it. 

Thanks again for you time :)

**Comment by lovell** [comment]
> "It works without them"

Thank you, that's good feedback, a PR to update the docs would be most welcome.

**Comment by lovell** [comment]
Closing as I hope the original question has been answered.

**Comment by sagivf** [comment]
@lovell was going to add a pull request, but then I saw you already did it https://github.com/lovell/sharp/commit/5e015cc3ca6f66237d75a5f3a1f13ecd1ccfd1e2
Sorry took me to long to get to it 😄  added some more info - https://github.com/lovell/sharp/pull/748
