### ISSUE TITLE
overlayWith raw input: memory area too small

### ISSUE THREAD

**Issue by iiAku** [lovell/sharp#718]
Hello,

node version: v7.4.0
ImageMagick version 6.9.6-8 Q16 x86_64 2016-12-12

I am doing images compositions and sometime I am getting this error:
Error: VipsImage: memory area too small
Error: VipsImage: memory area too small --- should be 8000000 bytes, you passed 5262436

According to what I read on issues this is related to the raw option object given to sharp for overlayWith.

What am I doing?

```
base {
  "name": "38db6773-da81-402f-b457-b609e8966147-border.png",
  "path": "/tmp/38db6773-da81-402f-b457-b609e8966147-border.png",
  "dimensions": {
    "width": 2048,
    "height": 3591,
    "type": "png"
  },
  "options": {
    "raw": {
      "channels": 4,
      "width": 2048,
      "height": 3591
    }
  },
  "gravity": {
    "gravity": 0
  }
}
other ressource [
  {
    "name": "66b9f2dd-1b6b-48e1-b7b6-8b010b37ef97-qr.png",
    "path": "/tmp/66b9f2dd-1b6b-48e1-b7b6-8b010b37ef97-qr.png",
    "dimensions": {
      "width": 1147,
      "height": 1147,
      "type": "png"
    },
    "options": {
      "raw": {
        "channels": 4,
        "width": 1147,
        "height": 1147
      }
    },
    "gravity": {
      "gravity": 0
    }
  },
  {
    "name": "e29eca8c-01e2-4302-9b33-c59478826cf9-label.png",
    "path": "/tmp/e29eca8c-01e2-4302-9b33-c59478826cf9-label.png",
    "dimensions": {
      "width": 2000,
      "height": 1000,
      "type": "png"
    },
    "options": {
      "raw": {
        "channels": 4,
        "width": 2000,
        "height": 1000
      }
    },
    "gravity": {
      "gravity": 3
    }
  }
]
```

Base is the first ressource (the bigger one), and other ressources are the ressource I want to merge into it.

My composition:
```
   const composite = filesShifted.reduce((image: any, overlay: any) => {
    return image.then((raw: any) => {
     return sharp(raw, overlay.options).overlayWith(overlay.path, overlay.gravity).raw().toBuffer()
    })
   }, base)
```

I already had this error in another case and I managed to sort it out, while giving the bigger raw overlay.options for all of my ressource (meaning I was using only the overlay.options from the base for all ressources). However I supposed this is not the right way, and I supposed I had the chance that the allocated memory was enough for all of my ressources, but actually the raw options was innapropriate.

The right thing would be to iterate over my ressource and give the associated options. Actually this is what I am trying to do, but it does not work there. I get the vips error. Do you have an idea about how I can fix this?

Thanks in advance

**Comment by iiAku** [comment]
Thanks in advance

**Comment by lovell** [comment]
Hello, the `raw` option passed to the constructor needs to have the correct dimensions of the raw pixel input. Perhaps use the "base" values every time as these won't change.

**Comment by iiAku** [comment]
As I said I wanted to provide the exact dimension of the image but for some reasons sometimes it does not work.
Is the dimension in pixel of image may be different from the raw pixel input as you said (I mean are we talking about the same thing).

**Comment by iiAku** [comment]
Again I made a check.. My scripts are running pretty well but I'm sure option parameters are wrong.

```
base options { raw: { channels: 4, width: 2048, height: 3591 } } /tmp/0a8cfba0-2cd1-4e39-951c-baf7a226a1be-border.png
overlay options { raw: { channels: 4, width: 492, height: 492 } } /tmp/af276999-94c5-4b7c-be01-1af9f7c680f6-qr.png
overlay options { raw: { channels: 4, width: 2000, height: 1000 } } /tmp/7c0b422a-1ac9-4bf9-ba5f-2d9edc3d219a-label.png
```

See options this will not work and I'll get:
`Error: VipsImage: memory area too small --- should be 8000000 bytes, you passed 968256`

This will work without any error:
```
base options { raw: { channels: 4, width: 2048, height: 3591 } } /tmp/0e2c896b-f050-467c-89ac-543513510ea8-border.png
overlay options { raw: { channels: 4, width: 2048, height: 3591 } } /tmp/33ec6740-2552-4368-a080-a068a0b20337-qr.png
overlay options { raw: { channels: 4, width: 2048, height: 3591 } } /tmp/9ec23b16-f09d-4d09-be79-d3f86249edf9-label.png
```
Overlays provided width/height options does not correspond to images, but it only works like this 👎 ..

From libvips I saw the error is comming from this check:
https://github.com/jcupitt/libvips/blob/0a5375b6cdbf9440e73c70bb89341f6c014118e0/libvips/iofuncs/image.c

```
	/* Allow len == 0, meaning don't check. Used for im_image()
	 * compatibility.
	 */
	if( size > 0 && 
		size < VIPS_IMAGE_SIZEOF_IMAGE( image ) ) {
		vips_error( "VipsImage",
			_( "memory area too small --- "
				"should be %zd bytes, you passed %zd" ),
			VIPS_IMAGE_SIZEOF_IMAGE( image ), size ); 
		VIPS_UNREF( image );
		return( NULL );
	}
```

Do you have an idea how I can fix this?

**Comment by lovell** [comment]
If you're calling `overlayWith` multiple as part of a reduction, the dimensions passed to the constructor need to always be those of the base image.

The output dimensions of a base image overlaid with a second image will be the same as the base image.

```diff
-     return sharp(raw, overlay.options).overlayWith(overlay.path, overlay.gravity).raw().toBuffer()
+     return sharp(raw, base.options).overlayWith(overlay.path, overlay.gravity).raw().toBuffer()
```

**Comment by iiAku** [comment]
Ok got it ! Thanks you so much for your help and Sharp. 👍
