### ISSUE TITLE
Erroneous Error in promise when used with Electron

### ISSUE THREAD

**Issue by McPo** [lovell/sharp#719]
```
    sharp(attachment.path)
        .toBuffer()
        .catch(err => window.console.error('sharp', err))
        .then(data => {
                attachment.thumbnail = b64.encode(data);
                this.setState({ attachment });
                window.console.debug('sendAttachment', attachment);
         });
```

It appears an error is thrown even though the operation was successful.
By removing the check for an error at  https://github.com/lovell/sharp/blob/master/lib/output.js#L439 and always calling resolve, everything appears to have worked as expected.

The value of the error passed to catch is true.

The library is being utilised in within an electron app OSX app.
The file is a WebP image (I cant attach it to Github, If its requested I can upload it somewhere else)

**Comment by lovell** [comment]
Hello, `err` should always be an instance of an `Error` object. What is the value of `err.message`? If you're able to share the image (but not via Github as it mangles images) that would be great.

**Comment by McPo** [comment]
Heres the image.

https://drive.google.com/file/d/0ByzxikYZsRc1TWx1RjBJUnJHcTQ/view

err.message is undefined as err is a boolean (Confirm via `typeof err`)

Cheers,
Emmet

**Comment by kleisauke** [comment]
My analysis to check if this is reproducible:
I couldn't reproduce this with the provided WEBP image and the following script:

```javascript
const sharp = require("sharp");
  
sharp('test.webp')
    .toBuffer()
    .catch(err => console.error(err))
    .then(data => console.log(data.toString('base64')));
```

(Tested on `Windows 10` & `CentOS 7.3` with `sharp v0.17.2`)

The base64 of the image is always printed to the `console.log`, and the error is never thrown. I also did some checks on the provided WEBP image and couldn’t find any error(s) indicating that the WEBP is invalid. So it looks like this is an Electron specific error.

**Comment by lovell** [comment]
@McPo Thanks for the image. Are you able to reproduce this outside of Electron?

I'm unable to reproduce this using Node v7.4.0 (as used by the latest Electron) on OS X.

The only place in the code that can create `err` does so as either [null](https://github.com/lovell/sharp/blob/81f55894112f9c84bace204e3ccfb5a6508cd07e/src/pipeline.cc#L914) or an instance of [Error](https://github.com/lovell/sharp/blob/81f55894112f9c84bace204e3ccfb5a6508cd07e/src/pipeline.cc#L917).

**Comment by McPo** [comment]
I was not able to reproduce this outside of electron.
Node v6.2.2, OS X 10.11.6, sharp v0.17.2

Ive created a quick start electron project to reproduce this issue.
```
git clone https://github.com/McPo/electron-quick-start.git
cd electron-quick-start
git checkout sharp-issue-719
npm install
npm start
```

Also note that Im using an older version of electron. Newer versions of electron do not appear to be compatible with the pre-built binaries provided, sometimes this can be fixed with electron-rebuild. Basically even if this problem is solved, newer electron builds will run into other issues which will also need to be solved to have full electron support.

**Comment by lovell** [comment]
This is an Electron problem - the version of V8 and the version of Node they are shipping are incompatible - please see https://github.com/electron/electron/issues/5851

**Comment by lovell** [comment]
> "Newer versions of electron do not appear to be compatible with the pre-built binaries provided"

With the following changes to [your example package.json](https://github.com/McPo/electron-quick-start/blob/sharp-issue-719/package.json):
```diff
@@ -4,7 +4,8 @@
   "description": "A minimal Electron application",
   "main": "main.js",
   "scripts": {
-    "start": "electron ."
+    "start": "electron .",
+    "rebuild": "electron-rebuild"
   },
   "repository": {
     "type": "git",
@@ -23,7 +24,8 @@
   },
   "homepage": "https://github.com/electron/electron-quick-start#readme",
   "devDependencies": {
-    "electron-prebuilt": "1.2.3",
+    "electron": "1.6.2",
+    "electron-rebuild": "1.5.7",
     "sharp": "0.17.2"
   }
 }
```
...running the following seems to  work for me, so it appears (at least) the latest version of Electron is compatible with sharp and has fixed its own internal ABI incompatibility.
```sh
npm install
npm run rebuild
npm start
```

**Comment by lovell** [comment]
@McPo Is this still a problem?
