### ISSUE TITLE
Resize losing EXIF data

### ISSUE THREAD

**Issue by paulieo10** [lovell/sharp#720]
Hi,

I am using Sharp to resize images after upload to my NodeJS webserver. I'm doing this to reduce the file size saved on the server. However, I would like to retain the EXIF data, specifically the GPS data and this is being lost.

Is this possible?

Many thanks,
Paul

**Comment by lovell** [comment]
Hello, did you see [withMetadata](http://sharp.dimens.io/en/stable/api-output/#withmetadata)?

**Comment by paulieo10** [comment]
Hi, not I didn't spot that.

Thank you very much, all working now :)

**Comment by jessehallam** [comment]
For new arrivals, the broken link in @lovell's post is corrected with: https://sharp.pixelplumbing.com/en/stable/api-output/
