### ISSUE TITLE
Enhancement: expose image stats (e.g. min, max, avg, sum, isOpaque)

### ISSUE THREAD

**Issue by huesforalice** [lovell/sharp#723]
Hi @lovell, thanks for a great and super fast library. I have a set of pngs which all have alpha channels, but I need to determine wether the channel is actually being used, or wether I can convert those pngs to jpgs for better web delivery performance. Is there an easy way to do this with sharp?

**Comment by kleisauke** [comment]
You could try something like this:

```javascript
const sharp = require("sharp");
  
const image = sharp('PNG_transparency_demonstration_1.png');
image
  .metadata()
  .then(function(metadata) {
      // if the image has an alpha transparency channel
      if(metadata.hasAlpha) {
        // return the buffer of the orginal image
        return image.toBuffer();
      }
      // else convert it to an JPEG buffer
      return image.jpeg().toBuffer();
  })
  .then(function(data) {
    // data contains a JPEG image if the source image hasn't an alpha transparency channel
    // else it will honor the origin image format (a WebP or PNG).
  });
```

**Comment by huesforalice** [comment]
Hey @kleisauke , thanks for the quick answer. I have already found the metadata method, in my case though, the PNGs do all have an alpha channel, just some of them don't use it, meaning all pixels are set to fully opaque. So I need a method to find those pngs which do not really use their alpha channel.

**Comment by kleisauke** [comment]
@huesforalice Ah I see, you are looking for an `isOpaque()` method in sharp. Currently there is no operation in sharp to accomplish that.
@lovell If you want (not sure how much demand there is for this feature), I can make a pull request implementing a `isOpaque()` function (and maybe also the `isTranslucent()` function). 
See: https://github.com/jcupitt/libvips/issues/547#issuecomment-260369224 for the C-code of `isOpaque()` (I think, for translucent function it will need to check if the [`vips_min()`](http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-arithmetic.html#vips-min) of the alpha channel is between `1-254`).

**Comment by huesforalice** [comment]
@kleisauke, that would be very helpful. Maybe there is a way to give more general access to the actual pixel color values of an image, so these kind of things can actually be done within sharp without you guys having to expose specialized functions for each an every desired operation?

**Comment by kleisauke** [comment]
@huesforalice See https://github.com/lovell/sharp/issues/241 for this. Personally, I hope someday that this library is just like the [Python](http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/using-from-python.html), [Ruby](https://rubygems.org/gems/ruby-vips) and [PHP](https://github.com/jcupitt/php-vips) libvips bindings.

**Comment by lovell** [comment]
Hello, raw pixel alpha values can currently be accessed via something like:
```javascript
sharp(rgbaInput)
  .extractChannel(3)
  .raw()
  .toBuffer( (err, data, info) => {
    // data is a Buffer containing raw pixel data of length info.width x info.height
  });
```
...which can then be looped over in JS. Sadly not very CPU cache efficient.

As for improving this, exposing [vips_stats](http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-arithmetic.html#vips-statsvips_stats) would provide the calculated data needed here in a much more efficient way.

Possible API:
```javascript
sharp(input)
  .stats( stats => console.log(stats.channel[3].min) );
```
`stats` would "return" (via callback or Promise) an Object with a `channel` Array, one element per channel, of Objects with the `min`, `max`, `sum` etc. attributes from the underlying `vips_stats` call. A derived `stats.isOpaque` "helper" attribute could also be provided.

**Comment by 0fork** [comment]
I would love to see this happen so huge +1 from me. We have a bit of a performance problem with detecting if alpha is really being used right now.

**Comment by rnanwani** [comment]
I can take this up. A possible suggestion for the API to be exposed. Can we club it with the `metadata` function with an optional parameter set to true that provides the extended stats.

```
//current API
sharp(input).metadata(function(err, metadata) { 
    //has the current implementation data
})

//possible implementation
sharp(input).metadata({
    extended_stats : true
}, function(err, metadata) { 
    //has existing metadata plus other stats 
})
```

This change in `metadata()` API can be made backward compatible and will ensure we have only one async call for any metadata related stuff in the future with an option to control the output.

Your thoughts?

**Comment by lovell** [comment]
@rnanwani Thank you for your kind offer.

As for the API, I still believe image stats should be accessed by a separate, named function and not mixed with the existing `metadata` behaviour.

* "metadata" refers to non-pixel data and is *about* the image.
* "stats" refers to pixel data and is *derived from* the image.

Perhaps think about metadata vs stats as the difference between "has alpha" and "uses alpha".

> "ensure we have only one async call for any metadata related stuff in the future"

If both metadata and stats are required, use of a Promise-based approach via `Promise.all` will keep consuming code clean.

**Comment by rnanwani** [comment]
@lovell I am working on this and I am stuck with a small problem. To provide an array of channel objects in the output, I need to pass a C++ vector of structs containing channel stats back to JS.

`Set(info, New("channels").ToLocalChecked(), baton->channelStats);`

Now obviously `baton->channelStats` needs to be cast into some other form before being sent back. I am not a C++ person, any heads up on how this can be best solved.

**Comment by rnanwani** [comment]
I have solved this by iterating through the vector and populating the v8::Array / v8::Objects correctly. 

```
      v8::Local<v8::Array> channels = New<v8::Array>();

      std::vector<ChannelStats>::iterator it;
      int i = 0;
      for (it=baton->channelStats.begin() ; it < baton->channelStats.end(); it++, i++) {
        v8::Local<v8::Object> c = New<v8::Object>();
        Set(c, New("min").ToLocalChecked(), New<v8::Number>(it->min));
        Set(c, New("max").ToLocalChecked(), New<v8::Number>(it->max));
        Set(c, New("mean").ToLocalChecked(), New<v8::Number>(it->mean));
        Set(c, New("stdev").ToLocalChecked(), New<v8::Number>(it->stdev));
        channels->Set(i, c);
      }
```

And then return `channels`. Is this the right way to go about it? Or is there a better way?

**Comment by lovell** [comment]
@rnanwani That looks like a sensible approach, thank you for picking this up.

**Comment by rnanwani** [comment]
Created a pull request. Please review

**Comment by rnanwani** [comment]
This can be closed as #915

**Comment by lovell** [comment]
@rnanwani Thanks Rahul, this enhancement is tagged as v0.19.0 so will get closed after release.

**Comment by lovell** [comment]
sharp v0.19.0 is now available, thanks everyone for your help implementing and providing feedback about this feature.
