### ISSUE TITLE
sharp should return input png if image is the same dimensions but larger after processing 

### ISSUE THREAD

**Issue by srcspider** [lovell/sharp#739]
I'd don't expect sharp to necesarily produce the best results but if it's a case of "nothing actually happened" then if it can't do better it should simply re-use the input as the output.

eg. http://wallpapercave.com/wp/udzjdgl.png

```js
const inputPath = '/path/to/sample.png';
const outputPath = '/path/to/output.png';

const sharp = require('sharp');

sharp(inputPath)
	.rotate() // does this even affect png metadata? as it does jpg exif data
	.withoutEnlargement(true)
	.resize(9000, 9000) // input image is 1920x1200
	.jpeg({ quality: 95, force: false })
	.webp({ quality: 95, force: false })
	.png({ compressionLevel: 9, force: false })
	.toFile(outputPath);
```

In the case jpeg and webp you have lossy compression (though technically webp can be lossless) so there's no judgement that can be made on if A is better then B however in the case of png the compression level makes no difference on how the image actually looks. I've added compressionLevel 9 there just for the sake of it, but it only makes a difference of 60kb or so (1mb vs 940kb). 

I guess sharp could probably even guess based on pixel / kb ratio if it should even bother; given no operations would otherwise be performed. But regardless, if the only thing it actually does to the image is re-apply compression then if after applying it the result is larger then the input (and no other manipulation happened), then it should just return the input, since the output is clearly inferior (940kb at max compression vs input which is 592kb).

**Comment by lovell** [comment]
Hello, it looks like `udzjdgl.png` is an indexed PNG file. libvips does not support indexed output, so you'll get full-colour.

It's worth trying without [adaptiveFiltering](http://sharp.dimens.io/en/stable/api-output/#png) given the uniformity of the background of this image.
```javascript
  .png({ compressionLevel: 9, adaptiveFiltering: false, force: false })
```

**Comment by princesoniversatile** [comment]
@[6262]([url]([url](url)))
