### ISSUE TITLE
Problems on AWS Lambda

### ISSUE THREAD

**Issue by JakubMatejka** [lovell/sharp#740]
I can't get the Sharp work on Lambda. I use Docker image for the deployment to AWS (including yarn install) which is based on official Amazon image (https://hub.docker.com/r/library/amazonlinux/) but my Lambda function fails on this error: `Module version mismatch. Expected 46, got 51.` which can be traced to `sharp/lib/constructor.js:8:15`.

Problem could be in fact that Lambda environment is based on Amazon AMI 2016.03 but that image can't be used anymore (it cannot be even run in EC2 if I would proceed according to your guide http://sharp.dimens.io/en/stable/install/#aws-lambda), there is only version 2016.09.

Would you have any idea how I could solve the problem?

**Comment by lovell** [comment]
Hello, did you see #468 and #733?

**Comment by JakubMatejka** [comment]
Hi, oh my, I missed them. I look mainly to issues relating lambda. Thank you very much for a fast hint, I am going to try and let you know if it helps.

**Comment by JakubMatejka** [comment]
I haven't found Node 4.3 which is used in aws but it looks that it is ok with 4.8. Thanks a lot.
