### ISSUE TITLE
Possible to get raw, non 8-bit values?

### ISSUE THREAD

**Issue by mikew** [lovell/sharp#741]
We're working with 16-bit images, and I want to get a quick average of the pixels. Using `sharp('foo.tif').raw()` results in an 8-bit buffer. Is there any way to disable that?

**Comment by lovell** [comment]
Hello, as you've seen the raw pixel output is currently unsigned 8-bit per channel (uint8).

If you're after average pixel values, there's been some recent discussion about the possibility of exposing `vips_stats`, which should provide what you need - see https://github.com/lovell/sharp/issues/723#issuecomment-282544766

**Comment by lovell** [comment]
Closing as hopefully #723 will provide what is needed here.
