### ISSUE TITLE
possible to supply 32-bit precompiled files as well?

### ISSUE THREAD

**Issue by Freundschaft** [lovell/sharp#745]
hey there,

i just wanted to ask if its possible to supply 32 bit precompiled files as well (i need them for windows)

microsoft unfortunately only runs nodejs 32 bit on their web app services. its possible to install a custom 64-bit version, but npm and automated npm installation stays 32-bit, which breaks my automated build and deploy pipeline.

what are the reasons for not supplying 32-bit precompiled binaries and am I able to assist there somehow? :)

Thanks!

**Comment by lovell** [comment]
Hello, did you see #379?

**Comment by Freundschaft** [comment]
Hello, thanks for the swift reply!
so the proposed solution is to use an outdated version of the library? if so, then the topic can be closed, I'll use a workaround to deploy the 64-bit version manually to azure then :)

**Comment by lovell** [comment]
Supporting 64-bit is as much hair as I'm willing to shave from the Windows yak, but I'd be happy to consider support for ARM-based Windows in the near future :)

**Comment by Freundschaft** [comment]
by the way, I managed to fix it by setting the npm_config_arch environment variable to x64, that did the trick, and sharp installed correctly, even when installing with 32-bit npm :)

**Comment by simeyla** [comment]
@Freundschaft Can you explain exactly how to do this. 
I was about to give up with Sharp on azure. Thanks!

**Comment by Freundschaft** [comment]
You can just set the npm_config_arch environment variable to x64, that will force azure npm to use that processor setting

**Comment by zavr-1** [comment]
@Freundschaft you can install sharp for x64 with your method but unfortunately it won't run on Azure Functions:

```sh
Exception: Worker was unable to load function WebUpload: 'Error: \\?\D:\home\site\wwwroot\node_modules\sharp\build\Release\sharp.node is not a valid Win32 application.
```

**Comment by Freundschaft** [comment]
hhm, never tried it with azure functions, but solution should be similar

**Comment by zavr-1** [comment]
yeah on azure functions with continuous deployment you would have to use your method replace vendored node with an x64 version and use the env variable that you've mentioned, like in the answer here https://github.com/Azure/azure-functions-nodejs-worker/issues/158#issuecomment-472492284. So thanks your comment has been very helpful.
