### ISSUE TITLE
error MSB8036: The Windows SDK version 8.1 was not found

### ISSUE THREAD

**Issue by doyledesigns** [lovell/sharp#746]
I'm getting an error when installing sharp on windows.

The error appears to be:
 gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1

In case it matters. I have visual studio 2010 and 2015 installed on my system.  I'm running Windows 7.

Debug log file is attached.

Regards.

[npm-debug.zip](https://github.com/lovell/sharp/files/879231/npm-debug.zip)

**Comment by lovell** [comment]
Hello, I'm probably missing something but I don't see the "Error: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe failed with exit code: 1" message in the attached log file.

Given there are multiple copies of Visual Studio, was the following [installation step](https://github.com/nodejs/node-gyp#installation) run?
```sh
npm config set msvs_version 2015
```

**Comment by doyledesigns** [comment]
[install output.zip](https://github.com/lovell/sharp/files/879782/install.output.zip)

I attached the command prompt output from running the install.  There may be several attempts, but the error is there.  I did run the "npm config set msvs_version 2015 installation step. before submitting the issue.

**Comment by lovell** [comment]
The salient part of the log is:
> error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".

https://developer.microsoft.com/en-us/windows/downloads/windows-8-1-sdk

**Comment by lovell** [comment]
@doyledesigns Were you able to make any progress with this?

**Comment by karakosemertcan** [comment]
Hello;
I have same problem but when I enter to MSBuild file, there are no "14.0". Just "15.0".
