### ISSUE TITLE
Possibility of porting entire capabilities of libvips into sharp

### ISSUE THREAD

**Issue by SuhairZain** [lovell/sharp#749]
I was trying to get some pixel-by-pixel manipulation done using Node and came across this library. I asked a doubt regarding what I wanted to get done and he sent me a snippet for Python which used the bandsplit() and bandjoin() functions . I looked at the sharp documentation for the JS equivalent, but it seems that sharp only has a subset of the capabilities offered by libvips.

Is there a chance that sharp might grow to include all the features of libvips or is this intended to be a lightweight library?

**Comment by lovell** [comment]
Hello, did you see #241, a discussion of how this might be achieved?

**Comment by SuhairZain** [comment]
Hi @lovell,
I read the discussion as well as the discussion on libvips on the same(https://github.com/jcupitt/libvips/issues/103). The last comment on these were made in September and I wonder what happened to those projects.

**Comment by lovell** [comment]
#241 is still open and therefore under active consideration. Shall we close this question and continue any discussion there?
