### ISSUE TITLE
Can I rotate to any angle rather than 90/180/270?

### ISSUE THREAD

**Issue by xiongjiabin** [lovell/sharp#751]
Newer to sharp. 
I need to rotate to 15, 30 angle. 
Does Sharp have way to do that?

**Comment by lovell** [comment]
Hello, libvips provides a [similarity](http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-resample.html#vips-similarity) operation that can do this, but it is not yet exposed in sharp and may not do exactly what you need.

I'd suggest you install and experiment with `vips` at the command line to see if it will help, e.g.:
```sh
vips similarity in.jpg out.jpg --angle 15
```

**Comment by xiongjiabin** [comment]
I see！Thanks!
