### ISSUE TITLE
Install fails on zeit now platform (coreos)

### ISSUE THREAD

**Issue by jessegavin** [lovell/sharp#755]
I created a simple express app which uses sharp. It works perfectly in my local Mac OS environment.

I want to use https://zeit.co/now for hosting this app. When I attempt to install, I get the following error.

I notice that `now` uses Linux 4.7.0-coreos.  Does anyone know if there are special considerations for this distribution?

```
> module.js:598
>   return process.dlopen(module, path._makeLong(filename));
>                  ^
> Error: Error loading shared library libvips-cpp.so.42: No such file or directory (needed by /home/nowuser/src/node_modules/sharp/build/Release/sharp.node)
>     at Object.Module._extensions..node (module.js:598:18)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/nowuser/src/node_modules/sharp/lib/constructor.js:8:15)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
> npm ERR! Linux 4.7.0-coreos
> npm ERR! node v7.6.0
> npm ERR! npm  v4.2.0
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! @ start: `node server.js`
> npm ERR! Exit status 1
```

**Comment by jessegavin** [comment]
I was able to contact some folks from the team at Zeit. Here's what they said.

> we're working on getting that fixed as we speak. in short, the `libvips.so` file isn't present in the application deployment environment at the moment

> also the reason it doesn't "just work" with their prebuilt Linux binaries is that Now deployments use Alpine Linux, which is generally incompatible with most Linux binaries that uses glibc, since Alpine uses MUSL C

**Comment by lovell** [comment]
Hello, as you've seen, the pre-built binaries are currently glibc-only so you'll need to ensure libvips is installed globally for a musl-based OS. It is [available](http://pkgs.alpinelinux.org/package/edge/testing/x86_64/vips) in Alpine's "testing" repo should you be able to use that.
