### ISSUE TITLE
No promise response or error.

### ISSUE THREAD

**Issue by webbrandon** [lovell/sharp#757]
I have a command that was working in `16.2.0` but stopped responding with `17.3.0`.   I tried my old method first and have even updated it with noted depreciations. 

**Older method**
```
sharpObj.png().quality( PIXEL_QUALITY ).limitInputPixels(PIXEL_LIMIT).resize(2000,2000).toBuffer(  )
            .then( function returnOutputFile( buffer ) {
                return buffer;
            }).catch( logReadError );
```

**New Method**
```
sharpObj.png({ quality: PIXEL_QUALITY }).limitInputPixels(PIXEL_LIMIT).resize(2000,2000).toBuffer( { 'resolveWithObject': true } )
            .then( function returnOutputFile( buffer ) {
                return buffer;
            }).catch( logReadError );
```

Problem is I recieve no error response.

**Comment by lovell** [comment]
Hello, for this example you can omit the new, optional `resolveWithObject: true` setting.

If you really need `resolveWithObject: true` then perhaps try:
```diff
-                return buffer;
+                return buffer.data;
```

**Comment by webbrandon** [comment]
Thank you for responding @lovell.  I have tried omitting this and still get a stuck process.  Ensured I removed old global and local instances of `sharp` also.  

I am on Mac OSX 10.11.6.  Could there be a new libvips dependency not included in the common files?  Is there some sort of development mode that produces more verbose logging?

**Comment by lovell** [comment]
Are you able to share how `sharpObj` is constructed?

As an aside, the `quality` option of `png({ quality: PIXEL_QUALITY })` is ignored as PNGs are lossless.

**Comment by webbrandon** [comment]
It gets stuck with a resize only command also.  I can call metadata still. :)

```

**Comment by webbrandon** [comment]
**FYI** Elaborating on my use of `apply`:

```
    commands.forEach( function ( cmd ) {
        sharpObj[ cmd.cmd ].apply( sharpObj, cmd.args );
    });
```

I have applied the command chain directly and dynamically ( as I always have ).

**Comment by webbrandon** [comment]
> As an aside, the quality option of png({ quality: PIXEL_QUALITY }) is ignored as PNGs are lossless.

Thank you for pointing that out but the way this is implemented is dynamic on format, I just chose a bad example to pull.

The issue ended up being a issue with node.js not sending the proper error. As always sharp is perfect!
