### ISSUE TITLE
Expose libvips op-cache max items (was: Image files never closed...)

### ISSUE THREAD

**Issue by chanon** [lovell/sharp#76]
I sometimes got `Error: EMFILE, too many open files` errors during testing of my app. Today I tried to find the root cause using `$ lsof` and `$ lsof | grep node`.

What I found is that my node process (an express app) which is using sharp isn't closing any source image files it processes.

I'm not sure if this is due to `vips_shutdown()` never being called or not. I tried tracing and verified that `at_exit()` and thus `vips_shutdown()` was never called. 

``` c++
static void at_exit(void* arg) {
  myLog << "Bye World"; // trace to log file here never shows up in the log
  NanScope();
  vips_shutdown();
} 
```

I guess `at_exit()` would be called if the node process terminates, however for long running processes the number of open files keep building up.

This or I'm missing something.

**Comment by gaillard** [comment]
@lovell do you perhaps have any insight on https://github.com/jcupitt/libvips/issues/432 since it seems similar?
