### ISSUE TITLE
Is there a way to know the history of file versions on `https://dl.bintray.com/` ?

### ISSUE THREAD

**Issue by mikemimik** [lovell/sharp#765]
I am using this library to do some image work, and specifically use the internal `vips` library because I don't want our environments to have to deal with extra things. I was running into an issue where certain files would fail with the library and others would not. Specifically around the metadata tags. MS Paint would create some wonky structure to the tags, but also some images off the internet also saw this problem.

Recently it seems to be fixed and I'm wondering if the versions of the libraries hosted on `https://dl.bintray.com/lovell/sharp/` have changed?

Is there any way to find this information out so I can track down this issue. Thanks in advanced.

**Comment by lovell** [comment]
Hello, the pre-compiled binary version of libvips and its dependencies published to bintray are frozen as soon as an npm-published version of sharp depends upon them.

https://bintray.com/lovell/sharp/libvips#files

(e.g. the npm-published sharp v0.17.x depends on libvips v8.4.2; the next sharp release will target the latest available libvips v8.5.x)

**Comment by mikemimik** [comment]
That was a helpful lead.

I'm still not sure what the issue was but v0.17.3 definitely fixed the problem. As far as I can tell, it wasn't just that though, it might have been a combination of things, because I explicitly installed `sharp@0.17.2` in order to get whatever `libvips` came with that version. 

However `v0.17.2` worked with images it used to break with, so I'm not sure why it succeeded. Best guess is that buffers and V8 have something to do with it all. From `v0.17.2` to `v0.17.3` there was some minor changes and code clean up _(from what I can tell)_ and I think some of those small tweaks, perhaps coupled with something else allowed things to work smoothly. 

The more I think about this issue, the more it seems like an edge case. The thing is we saw it quite often in our implementation, which confuses me if I stick with the assumption that it's an edge case.

I appreciate your help with the above comment @lovell. I'm very much looking forward to `v0.18.0`.

**Comment by lovell** [comment]
> However v0.17.2 worked with images it used to break with

There was a possible race condition when using Stream-based input that was fixed in v0.17.2.

If you didn't see it, there's a changelog at http://sharp.dimens.io/en/stable/changelog/
