### ISSUE TITLE
Using sharp with react

### ISSUE THREAD

**Issue by TimMenninger** [lovell/sharp#766]
Is there a reason this shouldn't work with React? I was using sharp and it worked well until I moved the front end to React. Now, I get `ERROR in ./~/sharp/index.js
Module not found: Error: Can't resolve './build/Release/sharp' in '/path/to/node_modules/sharp'` as if it doesn't recognize the .node extension.

**Comment by lovell** [comment]
Hello, are you trying to use sharp in a web browser? If so, that won't work as it is a native module requiring the Node runtime.

**Comment by TimMenninger** [comment]
Shoot, I am. Sorry for the novice question, I'm new to web dev... I'll Google for workarounds.
Thanks!

**Comment by ohenepee** [comment]
@lovell Would you happen to know any library similar to yours that work in the browser? Or could you compile port yours to WebAssembly? Wish I knew C++, perhaps I would have done the WASM part by now. :(

@TimMenninger did you find the worksround?

I'm particularly interested in WebP support.
