### ISSUE TITLE
Sharp does not fail when passing null or undefined as filename. 

### ISSUE THREAD

**Issue by kub1x** [lovell/sharp#768]
When passing only `null` or `undefined` into the constructor of sharp, sharp doesn't throw any error, even when a `.toBuffer()` or other output method is called. This behavior is really hard to debug as it simply doesn't do anything, even though the mistake is detectable via `arguments.length === 1 && !is.defined(arguments[0])`. 

I tried running `sharp(req.files.input.path).toBuffer()` but the *path* was actually in `req.files.input.file` as I changed a middleware in the meantime. It took me a lot of rewriting and some rubberducking to figure that out. 

I'd expect the constructor to fail when *a single `undefined` argument is passed*, just like it fails on numeric and other undefined types. 

Or maybe even fail when I call `toBuffer()` and there is nothing to feed the output from..? But I guess the that one is intentional for using in pipes or something (I'm not familiar with those yet). 

I thought about writing the fix, but wanted to ask about your opinion on the behavior first.

**Comment by kub1x** [comment]
Well, like this https://github.com/lovell/sharp/compare/master...kub1x:master ;)

**Comment by lovell** [comment]
Hello, the current behaviour  where null-or-undefined infers a Stream-based input is [documented](https://github.com/lovell/sharp/blob/master/lib/constructor.js#L74), although anything we can do to make using sharp easier is a good thing.

Your change looks like a sensible approach. I suspect there may be existing code that relies on the current behaviour so this would be a breaking change.

If you'd like to open a PR for this, please can you set the destination to be the [ridge](https://github.com/lovell/sharp/tree/ridge) branch and we can consider this for the v0.18.x release.

Feedback from other sharp users would be very much welcome here too.

**Comment by lovell** [comment]
Perhaps we should tighten the constructor parameters further to limit to only the following:
```javascript
sharp()                   // Stream input
sharp('filename.jpg')     // Filesystem input
sharp('f.svg', { ... })   // Filesystem input that requires description, e.g. SVG density
sharp(buffer)             // Buffer input
sharp(buffer, { ... })    // Buffer input that requires description, e.g. raw pixel data
sharp({ ... })            // Stream input that requires description or blank image
```
...and absolutely everything else will throw an Error.

This would mean that the current approach for handling a Stream-based input of raw pixel data would change from:
```javascript
sharp(null, { raw: { ... } })
```
to the less clunky:
```javascript
sharp({ raw: { ... } })
```
It would also allow for increased validation of the options, e.g. can't specify an input filename and attempt to create a new image at the same time.

**Comment by kevinchn** [comment]
I ran into the same problem. I accidentally passed undefined and it took a bit of time to debug why it wasn't working since it just did nothing.

**Comment by lovell** [comment]
This change, based on the excellent work of @kub1x, can be found in commit c41d755 on the [ridge](https://github.com/lovell/sharp/tree/ridge) branch and will be in v0.18.0.

**Comment by lovell** [comment]
v0.18.0 now available, thank you for all the feedback.
