### ISSUE TITLE
Fail in VS2017 : TRK0005: Failed to locate: "CL.exe"

### ISSUE THREAD

**Issue by himadrinath** [lovell/sharp#771]
`Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\himad\Documen
ts\Visual Studio 2017\Projects\BlankNode\BlankNode\node_modules\sharp\build\libvips-cpp.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\himad\Documents\Visual Studio 2017\Projects\BlankNode\BlankNode\node_modules\sharp
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.17.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.17.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\himad\AppData\Roaming\npm-cache\_logs\2017-04-16T15_03_11_790Z-debug.log`

**Comment by lovell** [comment]
Hello, did you see #341

**Comment by himadrinath** [comment]
@lovell two different machine running in same configration

![testing](https://cloud.githubusercontent.com/assets/12247490/25094138/64e70512-23b3-11e7-835b-2a4e460435cd.gif)

**Comment by lovell** [comment]
It looks like you're using node-gyp v3.6.0, which [added VS2017 support](https://github.com/nodejs/node-gyp/blob/master/CHANGELOG.md#v360-2017-03-16), so that's a good start.

`KeyError: '2017'` suggests node-gyp can't detect the version of Visual Studio. Perhaps try forcing it using:
```sh
npm config set msvs_version 2017
```

**Comment by himadrinath** [comment]
@lovell i did every thing because i run the `npm config set msvs_version 2017` command thats why is showing `KeyError: '2017'` if i remove it it will show another error 
`MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framew
ork 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it i
s installed elsewhere.  [C:\Users\himad\Desktop\testProject\node_modules\sharp\build\binding.sln]` 
and if i run it with `npm config set msvs_version 2015` if will show a another error

`error MSB4019: The imported proj
ect "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and t
hat the file exists on disk.`

i install all the component needed to run like here it says
https://github.com/nodejs/node-gyp/issues/1144

but still not working in this pc

**Comment by lovell** [comment]
Thanks for the update. Given it works on one machine but not another, this is unlikely to be a problem with sharp. I can see you're commenting on the linked node-gyp issue so I'll close this.

**Comment by refack** [comment]
Bug is in `node-gyp@3.6.0` incompatible with super new SDKs `10.0.15063.Desktop`
See edit in https://github.com/nodejs/node-gyp/issues/1144#issuecomment-290253041

**Comment by sigma67** [comment]
`npm i node-gyp --global`
Fixed the issue for me by installing the latest node-gyp version (5.0.4).
