### ISSUE TITLE
Error loading shared library libvips-cpp.so.42: No such file or directory

### ISSUE THREAD

**Issue by bassie1995** [lovell/sharp#773]
Hi,

I've been trying to install sharp, but it's telling me it can't find libvips-cpp.so.42.
I'm running Ubuntu 16.10 and have install libvips-dev (vips -v shows 8.5.3), not from source, because sharp's installer wouldn't seem to download it on its own and told me it was missing dependencies from libvips-dev.

I tried installing from source anyway, that's not helping either. The file is there in the /usr/local/lib folder, that might be from the source install?

I'm happy to provide any more info you need.

**Comment by lovell** [comment]
Ubuntu 16.10 [provides libvips v8.3.3](http://packages.ubuntu.com/yakkety/libvips-dev) via package manager. If you're seeing v8.5.3 from `vips -v` then that has probably been built from source so my best guess would be an incomplete/corrupt installation.

> "sharp's installer wouldn't seem to download it on its own"

If you don't need a custom, global installation of libvips then are you able to remove all trace of it so we can look into why this is failing?

**Comment by bassie1995** [comment]
I've autoremoved it and chucked it out of /usr/local/bin and /usr/local/lib. I also `npm uninstall`'d sharp.

Running npm i --save sharp@0.16.2 now outputs
```
Package gobject-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gobject-2.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gobject-2.0', required by 'vips', not found
gyp: Call to 'PKG_CONFIG_PATH=":$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --libs vips-cpp' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
```

As before, it did the same then.

**Comment by lovell** [comment]
It looks like you've still got a (partial) global installation of libvips. Specifically, the following command is still returning a value therefore sharp will try to use it.

```sh
pkg-config --modversion vips-cpp
```

**Comment by bassie1995** [comment]
Alright, I `sudo make uninstall`'d libvips and autoremoved libvips-dev, and it gave me
```
Package vips-cpp was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips-cpp.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips-cpp' found
```
So that seems better.

Running `npm i --save sharp@0.16.2` succeeds, starting the app gives me the following now:
```
Error loading shared library libresolv.so.2: No such file or directory (needed by /app/node_modules/sharp/build/Release/../../lib/librsvg-2.so.2)
```
I've seen this one before too, I assumed it's not installing libvips correctly?

**Comment by lovell** [comment]
`Error loading shared library libresolv.so.2: No such file or directory` looks like a slightly broken OS as that file is part of libc, e.g. http://packages.ubuntu.com/yakkety/amd64/libc6/filelist

**Comment by bassie1995** [comment]
Hm, can't remember messing with anything else like that. In the meantime I ran `ldd node_modules/sharp/build/Release/sharp.node` and got 
```
linux-vdso.so.1 =>  (0x00007ffda3fd8000)
        libvips-cpp.so.42 => /huisordner/node_modules/sharp/build/Release/../../lib/libvips-cpp.so.42 (0x00007f5a32b4d000)
        libvips.so.42 => /huisordner/node_modules/sharp/build/Release/../../lib/libvips.so.42 (0x00007f5a32548000)
        libglib-2.0.so.0 => /huisordner/node_modules/sharp/build/Release/../../lib/libglib-2.0.so.0 (0x00007f5a321d8000)
        libgobject-2.0.so.0 => /huisordner/node_modules/sharp/build/Release/../../lib/libgobject-2.0.so.0 (0x00007f5a31f84000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5a31bf0000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5a318e5000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5a316ce000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5a31307000)
        libpng16.so.16 => /huisordner/node_modules/sharp/build/Release/../../lib/libpng16.so.16 (0x00007f5a310cf000)
        libtiff.so.5 => /huisordner/node_modules/sharp/build/Release/../../lib/libtiff.so.5 (0x00007f5a30e56000)
        libz.so.1 => /huisordner/node_modules/sharp/build/Release/../../lib/libz.so.1 (0x00007f5a30c3f000)
        libjpeg.so.8 => /huisordner/node_modules/sharp/build/Release/../../lib/libjpeg.so.8 (0x00007f5a309c2000)
        libgmodule-2.0.so.0 => /huisordner/node_modules/sharp/build/Release/../../lib/libgmodule-2.0.so.0 (0x00007f5a307bf000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5a305b7000)
        libgsf-1.so.114 => /huisordner/node_modules/sharp/build/Release/../../lib/libgsf-1.so.114 (0x00007f5a3036e000)
        libxml2.so.2 => /huisordner/node_modules/sharp/build/Release/../../lib/libxml2.so.2 (0x00007f5a30083000)
        liborc-0.4.so.0 => /huisordner/node_modules/sharp/build/Release/../../lib/liborc-0.4.so.0 (0x00007f5a2fdec000)
        liblcms2.so.2 => /huisordner/node_modules/sharp/build/Release/../../lib/liblcms2.so.2 (0x00007f5a2fb81000)
        libgif.so.7 => /huisordner/node_modules/sharp/build/Release/../../lib/libgif.so.7 (0x00007f5a2f978000)
        librsvg-2.so.2 => /huisordner/node_modules/sharp/build/Release/../../lib/librsvg-2.so.2 (0x00007f5a2f73a000)
        libgio-2.0.so.0 => /huisordner/node_modules/sharp/build/Release/../../lib/libgio-2.0.so.0 (0x00007f5a2f37a000)
        libgdk_pixbuf-2.0.so.0 => /huisordner/node_modules/sharp/build/Release/../../lib/libgdk_pixbuf-2.0.so.0 (0x00007f5a2f158000)
        libcairo.so.2 => /huisordner/node_modules/sharp/build/Release/../../lib/libcairo.so.2 (0x00007f5a2ee61000)
        libwebp.so.6 => /huisordner/node_modules/sharp/build/Release/../../lib/libwebp.so.6 (0x00007f5a2ebd9000)
        libexif.so.12 => /huisordner/node_modules/sharp/build/Release/../../lib/libexif.so.12 (0x00007f5a2e993000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5a2e775000)
        libffi.so.6 => /huisordner/node_modules/sharp/build/Release/../../lib/libffi.so.6 (0x00007f5a2e56d000)
        /lib64/ld-linux-x86-64.so.2 (0x0000556ff9d81000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5a2e369000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f5a2e14c000)
        libpangocairo-1.0.so.0 => /huisordner/node_modules/sharp/build/Release/../../lib/libpangocairo-1.0.so.0 (0x00007f5a2df3f000)
        libpangoft2-1.0.so.0 => /huisordner/node_modules/sharp/build/Release/../../lib/libpangoft2-1.0.so.0 (0x00007f5a2dd28000)
        libharfbuzz.so.0 => /huisordner/node_modules/sharp/build/Release/../../lib/libharfbuzz.so.0 (0x00007f5a2da9d000)
        libpango-1.0.so.0 => /huisordner/node_modules/sharp/build/Release/../../lib/libpango-1.0.so.0 (0x00007f5a2d84e000)
        libgthread-2.0.so.0 => /huisordner/node_modules/sharp/build/Release/../../lib/libgthread-2.0.so.0 (0x00007f5a2d64b000)
        libpixman-1.so.0 => /huisordner/node_modules/sharp/build/Release/../../lib/libpixman-1.so.0 (0x00007f5a2d38d000)
        libfontconfig.so.1 => /huisordner/node_modules/sharp/build/Release/../../lib/libfontconfig.so.1 (0x00007f5a2d141000)
        libfreetype.so.6 => /huisordner/node_modules/sharp/build/Release/../../lib/libfreetype.so.6 (0x00007f5a2ce9a000)
        libcroco-0.6.so.3 => /huisordner/node_modules/sharp/build/Release/../../lib/libcroco-0.6.so.3 (0x00007f5a2cc5e000)
```
So the file is definitely there.
I reinstalled build-essentials, no luck there either.

**Comment by lovell** [comment]
The pre-compiled glibc-expecting binaries do not work with the musl-based Alpine.

**Comment by bassie1995** [comment]
Hm, haven't found anything about that so I don't feel as dumb! I'll try using the normal Node docker container.

**Comment by bassie1995** [comment]
It's starting up without errors now, thanks! Weird I didn't find anything about the incompatibility, though.

Thanks for the help anyway, really appreciate the great support :)

**Comment by lovell** [comment]
Glad to hear you got it working.

My best guess for the `Error loading shared library libresolv.so.2: No such file or directory` error is that Ubuntu/glibc was use at compile (`npm install`) time but Alpine/musl was used at run time.

There is a small mention in the docs about glibc but this could probably be improved.

> Most recent Linux-based operating systems with glibc running on x64 and ARMv6+ CPUs should "just work"...

http://sharp.dimens.io/en/stable/install/#linux

**Comment by bassie1995** [comment]
Might be, I'm also seeing the warning that Alpine and glibc don't work well in some Docker image repos.
I saw the warning there, but never quite made the connection. Maybe I should have researched and thought about the 'pipeline' a bit more. I can change that wording a bit and submit a PR real quick if you want?

Have tried to get it working with some pre-packaged Docker images with vips (like @wjordan's) and/or glibc or glibc for Alpine, but no luck; next challenge!

Anyway, that's irrelevant. Thanks for the help!

**Comment by wjordan** [comment]
@bassie1995 for Alpine, [`vips`](http://pkgs.alpinelinux.org/packages?name=vips*&branch=&repo=&arch=x86_64&maintainer=) has been integrated upstream into the official `edge`/`testing` repository, so my s3 repo is obsolete/unmaintained and you should be able to run something like the following to install:

```sh
apk add vips-dev -U -X http://dl-3.alpinelinux.org/alpine/edge/testing/
```

There's probably some documentation I should update to reflect this (I haven't been very actively maintaining this recently), but in the meantime I hope this helps.

**Comment by bassie1995** [comment]
@wjordan Thanks for the info, great news!

I'm having to install the dependencies (I'm too spoiled by npm doing this for me haha), and I was looking at your Dockerfile: what's the difference in run-deps and dev-deps? Does it use only one depending on something?

**Comment by wjordan** [comment]
@bassie1995 I assume you're talking about [wjordan/docker-sharp](https://github.com/wjordan/docker-sharp) docker scripts?

In the Alpine ecosystem most packages are split between the base package and a `-dev` subpackage, which contains development files only needed when building other packages. Refer to the Alpine Linux wiki on [subpackages](https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package#subpackages):

> #### subpackages
> $subpackages are made to split up the normal "make install" into separate packages. The most common subpackages we use are doc and dev. Because we like to keep our target system small we move documentation and development files (only needed when building packages) into separate packages. To use the specific program a user only need to install the base apk without package-doc or package-dev, but if he wants to read the manual he will need to install package-doc.

Similarly, when building a minimal Docker image for a runtime binary you can install the `-dev` subpackages during the build process then remove them after the build step, only the base packages needed for dynamic linking at runtime on the final flattened image.

**Comment by bassie1995** [comment]
Ah, so it's automatic? That's pretty cool.

I seem to have it working now, using your libvips image and installing Node into that (which takes a pretty long time to build :P).

Thanks so much for the help guys!

**Comment by bassie1995** [comment]
Gonna use this real quick: @wjordan I need to still install Sharp using the line for Alpine in the installation guide, when I base my container on Alpine Node and use the install script for vips-tools that you're using.
What happens otherwise is node-gyp says it can't find python.

Don't know if you have this issue, thought I'd let you know.

**Comment by dotgithub** [comment]
I've just starting experiencing this exact today on Ubuntu 18.04 when running a gatsby build. Was working yesterday and my project is using sharp via `gatsby-plugin-manifest`, sharp version 0.21.1 in the `package-lock.json` file. I manually changed the dependency to 0.23.0 and still get the same issue.

Typing `pkg-config --modversion vips-cpp` gives:
```
Package vips-cpp was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips-cpp.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips-cpp' found
```
I'm going to post this in Gatsby as well but wanted to add it here for anyone searching in Google and at a loss like me.
