### ISSUE TITLE
Enhancement: save 1 bit-depth TIFF images

### ISSUE THREAD

**Issue by YvesBos2** [lovell/sharp#774]
I'm trying to create a TIFF file that contains only black or white, nothing in between. In the end result there were  always some very light grey pixels. I've fixed this by setting the quality to 100 but it still has a bit depth of 24. 
Is there a way to force using a bit depth of 1?

**Comment by lovell** [comment]
Hello, did you see the [tiff](http://sharp.dimens.io/en/stable/api-output/#tiff) options, specifically `compression`?

**Comment by YvesBos2** [comment]
Hello, thanks for answering.

Yes I've looked at the compression options, this gives me the best result:

```
sharp(Buffer.from(data), {raw: {width: W, height: H, channels: C}})
    .resize(H*cell_in_pix,W*cell_in_pix, {kernel: sharp.kernel.nearest,
                interpolator: sharp.interpolator.nearest})
    .toColourspace('b-w')
    .tiff({quality: 100, compression: 'deflate', predictor: 'horizontal'})
    .toFile(dir+'/'+uuidV4()+'.tiff', function(err, info) {
      ...
    });
```
But the images still have a bit-depth of 8, is there no way I can force it to 1?

**Comment by lovell** [comment]
For 1-bit output, we'd need to expose the `squash` property of libvips' TIFF writer. http://jcupitt.github.io/libvips/API/current/VipsForeignSave.html#vips-tiffsave

**Comment by lovell** [comment]
v0.18.0 now available, thanks for the PR!
