### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by jijo-paulose** [lovell/sharp#779]
Error: Module version mismatch. Expected 48, got 51.
Sharp not working with pm2 module. 

 Error: Module version mismatch. Expected 48, got 51.
0|GO       |     at Error (native)
0|GO       |     at Object.Module._extensions..node (module.js:597:18)
0|GO       |     at Module.load (module.js:487:32)
0|GO       |     at tryModuleLoad (module.js:446:12)
0|GO       |     at Function.Module._load (module.js:438:3)
0|GO       |     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
0|GO       |     at Module.require (module.js:497:17)
0|GO       |     at require (internal/module.js:20:19)
0|GO       |     at Object.<anonymou>(/home//node_modules/sharp/lib/constructor.js:8:15)
0|GO       |     at Module._compile (module.js:570:32)
0|GO       |     at Object.Module._extensions..js (module.js:579:10)
0|GO       |     at Module.load (module.js:487:32)
0|GO       |     at tryModuleLoad (module.js:446:12)
0|GO       |     at Function.Module._load (module.js:438:3)
0|GO       |     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
0|GO       |     at Module.require (module.js:497:17)
0|GO       |     at require (internal/module.js:20:19)
0|GO       |     at Object.<anonymous> (/home//node_modules/sharp/lib/index.js:3:15)
0|GO       |     at Module._compile (module.js:570:32)
0|GO       |     at Object.Module._extensions..js (module.js:579:10)
0|GO       |     at Module.load (module.js:487:32)
0|GO       |     at tryModuleLoad (module.js:446:12)

**Comment by lovell** [comment]
Please see #468 #733 #740 #750

**Comment by dreamcatcha** [comment]
I've looked at ever answer to the mismatch error you have linked too but I must be missing something as none of it has fix the issue for me

I have deleted the node_modules folder, I have done the node install and even the node rebuilt afterwards even but I still get this mismatch error in pm2 logs, is there anything else I could be missing?

**Comment by lovell** [comment]
> "Module version mismatch. Expected 48, got 57"

NODE_MODULE_VERSION 48 is Node 6, which is being used at `npm install` time.

NODE_MODULE_VERSION 57 is Node 8, which is being used at run time by pm2.

There are two versions of Node installed that are conflicting with each other.
