### ISSUE TITLE
resize() can cause slight (~1px) cropping on circular features

### ISSUE THREAD

**Issue by chrisfrancis27** [lovell/sharp#780]
Using sharp 0.17.3:

I've got a 370x370px source PNG image which features a white circle with a light grey border around it, and an alpha-transparent background:

![370](https://cloud.githubusercontent.com/assets/273311/25283125/98202932-26aa-11e7-8d75-759ceb0f7f24.png)

Resizing it down causes the grey circle to lose a pixel from the edges. For example, scaling it down to 369x369px (clipping visible on top/left edges):

![369](https://cloud.githubusercontent.com/assets/273311/25283155/b44b3336-26aa-11e7-8cb6-3196b4a732f2.png)

And here it is at 100x100px (clipping visible on bottom/right edges):

![100](https://cloud.githubusercontent.com/assets/273311/25283811/f377d1a2-26ac-11e7-8937-c7fc350c1d14.png)

However, resizing it to exactly half of its original dimensions (185px) does not have the problem:

![185](https://cloud.githubusercontent.com/assets/273311/25283950/76701fce-26ad-11e7-9093-9b1f24f3d12a.png)

Here's the code:
```
sharp(png)
    .resize(options.width, options.height, {
        kernel: sharp.kernel.cubic,
        centreSampling: true
    })
    .max()
    .toFile(outFile, err => /*...*/);
```

I tried messing about with kernel settings and centre-sampling but they all seemed to have similar issues. As a test, I called `.rotate(180)` both before and after the `resize()` call and the cropping was visible on the opposite edges to before, suggesting it is something in the resize algorithm itself that is doing it. 

I'm no expert on image scaling algorithms :) Any ideas what could be causing this? I'm aware it's probably not an issue with sharp itself, but maybe the underlying image lib. Many thanks!

**Comment by chrisfrancis27** [comment]
**Update:** I've found a workaround, which is to `extend()` the image by 1 transparent pixel on each side, then pipe the result of that into the `resize()` function. 

![jpn](https://cloud.githubusercontent.com/assets/273311/25286274/1813d65c-26b5-11e7-94de-75353a80d802.png)

No more visible clipping! 👍

**Comment by lovell** [comment]
Hello, for this example you're at the mercy of the kernel used for any non-integral reduction. As you've probably spotted, halving the dimensions uses a fast box shrink but anything beyond this can involve rounding "errors" at the edges.

Use of `centreSampling` is your best bet to keep the behaviour consistent with *magick but in summary this is a maths problem rather than a sharp problem :(

**Comment by chrisfrancis27** [comment]
@lovell thanks for the quick reply! Yeah, after playing a round a bit more I started to realise the scale (no pun intended) of the problem, it's pretty complex... Fiddling around with extra padding on the edges and a bit of trial and error has yielded good results so I'm happy if you want to close this issue.
Thanks for the awesome library! 💯

**Comment by lovell** [comment]
Thanks for the update, glad to hear you got the desired result.

**Comment by gnitsenko93** [comment]
Hey @chrisfrancis27 glad you have solved the problem. If your approach is generic enough can you share your solution?
Thanks in advance!
