### ISSUE TITLE
Aliasing problem due to shrink-on-load(?)

### ISSUE THREAD

**Issue by kleisauke** [lovell/sharp#781]
I discovered this bug by chance while testing some images. See this testcase:
```js
const sharp = require("sharp");

sharp('test_800x600.jpg')
  .resize(400)
  .toFile('test_800x600_aliasing.jpg');
```
<sup>(original picture can be downloaded from [here](http://www.rollthepotato.net/~john/kevill2/test_800x600.jpg))</sup>

Output (tested with sharp v0.17.3):
![test_800x600_aliasing_wrong](https://cloud.githubusercontent.com/assets/12746591/25302938/ca6583a2-2749-11e7-986c-052ccfea6f92.jpg)
<sup>(nasty aliasing artifacts at the roof)</sup>

Expected output:
![test_800x600_aliasing_good](https://cloud.githubusercontent.com/assets/12746591/25302939/cf1ea81a-2749-11e7-85d7-c6c8d607b442.jpg)
<sup>(with vipsthumbnail)</sup>

The thumbnail operator from libvips has fixed this by leaving at least a factor of two for the final resize step. See [thumbnail.c#L203-L217](https://github.com/jcupitt/libvips/blob/0a5375b6cdbf9440e73c70bb89341f6c014118e0/libvips/resample/thumbnail.c#L203-L217), and the [wiki](
https://github.com/jcupitt/libvips/wiki/HOWTO----Image-shrinking#block-shrink).

While looking at the source code of sharp, I noticed that the shrink-on-load doesn't take this into account. See [pipeline.cc#L230-L241](https://github.com/lovell/sharp/blob/088d36b47b7bc5a76735d5f6ac0afaaffb761d4f/src/pipeline.cc#L230-L241).

In an attempt to fix this, I came to this patch ([line 230-241 in pipeline.cc](https://github.com/lovell/sharp/blob/088d36b47b7bc5a76735d5f6ac0afaaffb761d4f/src/pipeline.cc#L230-L241)):
```diff
-        if (xshrink >= 8) {
+        if (xshrink >= 16) {
          xfactor = xfactor / 8;
          yfactor = yfactor / 8;
          shrink_on_load = 8;
-        } else if (xshrink >= 4) {
+        } else if (xshrink >= 8) {
          xfactor = xfactor / 4;
          yfactor = yfactor / 4;
          shrink_on_load = 4;
-        } else if (xshrink >= 2) {
+        } else if (xshrink >= 4) {
          xfactor = xfactor / 2;
          yfactor = yfactor / 2;
          shrink_on_load = 2;
        }
```

But that doesn't seem to work (maybe I'm missing something).

**Comment by lovell** [comment]
Hallo Kleis, great work, it's always good to improve the quality of output images.

To get your patch to do what we need, I think we'd also need to change the "shrink" vs "reduce" ratio to be more like [libvips/resample/resize.c#L132](https://github.com/jcupitt/libvips/blob/0a5375b6cdbf9440e73c70bb89341f6c014118e0/libvips/resample/resize.c#L132).

It might be worth experimenting with applying this change only when there will be no floating point residual, i.e. only when `shouldReduce` is false . When vips_reduceh/vips_reducev are used, they deal with any aliasing from the integral shrinking stages, be that "on load" or via vips_shrinkh/vips_shrinkv.

Another thing to consider is that libwebp's shrink-on-load uses a different algorithm to libjpeg's, so this might have to be conditional based on format.

**Comment by lovell** [comment]
> "worth experimenting with applying this change only when there will be no floating point residual"

Quick update: I've got a prototype working that dynamically varies the use of shrink-on-load and box shrink based on the level of kernel-based reduction. The tl;dr is "same high performance most of the time, occasionally take a slight performance hit to ensure high quality".

**Comment by lovell** [comment]
Commit e398b47 adds the dynamic shrink(-on-load) behaviour to ensure a kernel-based reduction will always occur. This will be in v0.18.0. Thanks again for your original, well-written report about this.

**Comment by jcupitt** [comment]
*When vips_reduceh/vips_reducev are used, they deal with any aliasing from the integral shrinking stages, be that "on load" or via vips_shrinkh/vips_shrinkv.*

I'm not sure that's quite right (or I've misunderstood), you must do at least the final 200% with reduce to avoid aliasing from the block shrink. Some people say it should be slightly more than 200%, perhaps 210%, to be safe, though `vipsthumbnail` just leaves the last 200%.

**Comment by lovell** [comment]
@jcupitt Yes, sharp is still taking a bit of a shortcut by reducing only the final 101%-200%. This change at least prevents it skipping the reduce operation entirely (the "100% scenario").

**Comment by jcupitt** [comment]
Ah OK, then I think you will still see aliasing with some shrink factors. I think I'd add another factor of two to the amount of reduce you do.

**Comment by lovell** [comment]
v0.18.0 now available (with the slight improvement for the 100% case).
