### ISSUE TITLE
eps,.psd,.pdf  support   sharp 

### ISSUE THREAD

**Issue by karthikeyandls** [lovell/sharp#784]
hello 
  i  have   some   doubt  eps,psd,pdf  this  source  files support for  sharp, and how  much maximum size files   support   like (1 GB,2 GB)    

regards
karthi

**Comment by jcupitt** [comment]
[libvips](https://jcupitt.github.io/libvips/) (the image processing library that sharp uses) supports PDF via poppler. Poppler is licenced under the GPL, so it's slightly problematic to distribute binaries with it compiled in. If you need PDF support in sharp, you need to install libvips yourself and include poppler support. This is easy to do on linux hosts or macOS, a little harder on Windows. 

Regarding maximum filesize: it depends on the document, you would need to experiment. Is it a single page, or many pages? Are there large embedded images, or is the page drawn? 

I would install the libvips command-line tools and try:

```
$ vipsthumbnail somefile.pdf
```

And see how long it takes and what peak memory use is. 

libvips supports EPS and PSD via an ImageMagick loader, which can be very slow, and can have security consequences. Again, it would be best to experiment.
