### ISSUE TITLE
tif  to jpg   thumbnail not generated  error  ocuar 

### ISSUE THREAD

**Issue by karthikeyandls** [lovell/sharp#786]
hi  
the  following  code  using 

// Import both http & https for handling different uris
var http = require('http');  
var https = require('https');  
// in order to write to the filesystem we need the `fs` lib
var fs = require('fs');  
// import the lib
var sharp = require('sharp');

// create the resize transform
var resizeTransform = sharp().resize(300, 300).max();

var imageUri = 'https://localhost/test.tif';

// determine wether we need to use `http` or `https` libs
var httpLib = http;  
if ( /^https/.test(imageUri) ) {  
  httpLib = https;
}
// begin reading the image
httpLib.get(imageUri, function(downloadStream) {  
  var writeStream = fs.createWriteStream('./output-300x300.jpg');
  downloadStream.pipe(resizeTransform).pipe(writeStream);
  downloadStream.on('end', () => {
    console.log('downloadStream', 'END');
  });
  writeStream.on('error', (err) => {
    console.log('writeStream', err);
  });
  downloadStream.on('error', (err) => {
    console.log('writeStream', err);
  });
  resizeTransform.on('error', (err) => {
    console.log('resizeTransform', err);
  });
});

i  got   error   :vips warning: TIFFFetchNormalTag: ASCII value for tag "Artist" contains null byt
e in value; value incorrectly truncated during reading due to implementation lim
itations
vips warning: TIFFFetchNormalTag: Incompatible type for "RichTIFFIPTC"; tag igno
red     any solution  please  update  me

**Comment by lovell** [comment]
Please see #607 for details of how to suppress warnings in the current v0.17.x release of sharp.
