### ISSUE TITLE
AWS Cloudfront Lambda@Edge

### ISSUE THREAD

**Issue by aayler** [lovell/sharp#787]
Greetings,

At http://sharp.dimens.io/en/stable/install/#aws-lambda, there is documentation supporting AWS Lambda using Node.js 4.3.

Is there also support for Cloudfront using Lambda@Edge (and Edge Node.js 4.3 runtime)?

Thanks!

**Comment by lovell** [comment]
Hello, Lambda@Edge is new and currently very limited. I doubt there are enough resources for image processing, e.g. the tiny 1MB limit on code and dependencies.

http://docs.aws.amazon.com/lambda/latest/dg/lambda-edge.html#lambda-edge-limits

**Comment by aayler** [comment]
Thanks @lovell for the prompt response! We're looking only to resize on the fly the images from Cloudfront ...
