### ISSUE TITLE
eps file works with filepath input but not buffer input?

### ISSUE THREAD

**Issue by kevinchn** [lovell/sharp#788]
Filepath input:
```
> sharp('img.eps').metadata().then(d => console.log(d)).catch(e => console.log(e))
Promise { <pending> }
> { format: 'magick',
  width: 780,
  height: 150,
  space: 'rgb16',


  channels: 4,
  hasProfile: false,
  hasAlpha: true }
```

Buffer input:
```
> sharp(fs.readFileSync('img.eps')).metadata().then(d => console.log(d)).catch(e => console.log(e))
Promise { <pending> }
> Error: Input buffer contains unsupported image format
    at Error (native)
```

Is there something I'm missing?
img.eps: [img.zip](https://github.com/lovell/sharp/files/961862/img.zip)

Thanks,
Kevin

**Comment by lovell** [comment]
Hello, it looks like you're using a globally-installed version of libvips compiled with support for *magick. Which version of libvips are you using?

**Comment by kevinchn** [comment]
Right, I should've specified that.

vips: 8.4.3
sharp: 0.17.2

**Comment by kevinchn** [comment]
I'll try with latest vips.

**Comment by lovell** [comment]
Thanks for confirming, I'll need to attempt to reproduce this locally as the loading of images via *magick is not covered by the existing test suite (as *magick is intentionally excluded from the pre-compiled libvips binaries).

**Comment by kevinchn** [comment]
@lovell thanks for looking into it. I'll provide this Dockerfile in case it helps you reproduce it.

```
FROM amazonlinux

ARG node_version=6.10.0

RUN curl -s https://rpm.nodesource.com/setup_6.x | bash -
RUN yum install -y nodejs-${node_version} && npm install npm@latest -g

ARG vips_version=8.5.4

RUN yum install -y gcc-c++ glib2-devel expat-devel jbigkit-devel libffi-devel ImageMagick-devel libwebp-devel libpng-devel libtiff-devel giflib-devel libjpeg-turbo-devel libexif-devel

RUN mkdir -p vips
RUN curl -Ls https://github.com/jcupitt/libvips/releases/download/v${vips_version}/vips-${vips_version}.tar.gz | tar xzC vips --strip-components=1
WORKDIR vips
RUN ./configure --disable-static
RUN make && make install
WORKDIR ..

RUN PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/ npm install sharp
ENV LD_LIBRARY_PATH=/usr/local/lib
```

**Comment by kevinchn** [comment]
Extra detail: As far as I know, bmp input is also supported via *magick, but I don't run into this problem with bmp files.

**Comment by lovell** [comment]
@kevinchn Are you still experiencing this problem with the latest libvips?

**Comment by lovell** [comment]
I had a closer look at this and discovered *magick appears to process EPS files using the Ghostscript-provided `gs` command line tool with (temporary) images on the filesystem, which would explain why it doesn't work in-memory.

```sh
$ identify -verbose img.eps
identify identify: "gs" "-q" "-dBATCH" "-dMaxBitmap=50000000" "-dNOPAUSE" "-sDEVICE=pnmraw" "-dTextAlphaBits=4" "-dGraphicsAlphaBits=4" "-r72x72" "-g780x150" "-sOutputFile=/tmp/gm5w4wGi" "--" "/tmp/gm18NCGE" "-c" "quit".
Image: img.eps
  Format: PS (Adobe PostScript)
  Geometry: 780x150
...
```

Sadly this is a current limitation of *magick so there's not a lot we can do.
