### ISSUE TITLE
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".

### ISSUE THREAD

**Issue by sansroman** [lovell/sharp#789]
I try to reinstall NPM, node, SDK, vc++build, but still not resolved

It's my log:
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are"14.0". "4.0".
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\liang\AppData\Roaming\npm\node_modules\cnpm\node_modules\_node-gyp@3.6.0@node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\soft\\node\\node.exe" "C:\\Users\\liang\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\_npminstall@2.29.2@npminstall\\node-gyp-bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\school\tools\node_modules\_sharp@0.17.3@sharp
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
× Install fail! Error: post install error, please remove node_modules before retry!
Run "C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild" error, exit code 1
Error: post install error, please remove node_modules before retry!

**Comment by lovell** [comment]
Hello, there are some suggestions at https://github.com/chjj/pty.js/issues/60 that might help here.

**Comment by sansroman** [comment]
thank you for your help,  I try to set msvs_version ,but still not resolved,and  I fount that I only  have  32 bit .NET version, I try to install vs express  tomorrow

**Comment by sansroman** [comment]
I installed visual studio today,but it's not resolved my problem,even make  my cmder and xshell is bad，so I give up  and install Linux .thinks
