### ISSUE TITLE
`metadata` method doesn't use cache, other methods do

### ISSUE THREAD

**Issue by josephrocca** [lovell/sharp#796]
There seems to be some inconsistency on the use of the cache. Is this expected behaviour? It can make debugging [quite confusing](https://github.com/lovell/sharp/issues/797). Great package, btw - thanks to lovell and contributors!

**Comment by lovell** [comment]
Hello, this is more a feature of libvips than anything else so perhaps we should add something to the docs about it.

**Comment by lovell** [comment]
Added in commit d45f8ef, thank you for the suggestion.
