### ISSUE TITLE
OSX: sharp/build/Release/sharp.node: invalid ELF header

### ISSUE THREAD

**Issue by ChrisPiechowicz** [lovell/sharp#800]
version 0.17.3
node 6.8.0

**Comment by lovell** [comment]
Hello, "invalid ELF header" suggests sharp has been compiled for the wrong architecture. Was `npm install` run on the same machine that exhibits this error?

**Comment by ChrisPiechowicz** [comment]
Thank you for your help. The app runs in a docker machine, but I was installing sharp locally...

**Comment by willfarrell** [comment]
Anyone running into this on AWS Lambda?

**Comment by DonkiKoi** [comment]
I had the same issue. I have developed an AWS Lambda function using sharp on my Mac, which should then run on AWS. However, the `node_modules` were installed on the Mac and then deployed to AWS together with the code. As a result, I ran into the error "invalid ELF header".

My solution: Download an AWS Linux container, include all the required files in it via volume and then install the packages in the container. This way, the packages are assembled correctly for the target environment (in my case AWS Lambda).

```shell
# 1. Start container
docker run --name amazonlinux -v <path/to/project>:/data -it amazonlinux:latest /bin/bash

#2. Install npm & node_modules
$ yum install npm
$ cd /data
$ npm install
```
