### ISSUE TITLE
adding node-images to performance test

### ISSUE THREAD

**Issue by hbakhtiyor** [lovell/sharp#801]
would be nice to add [node-images](https://github.com/zhangyuanwei/node-images) to performance test

**Comment by lovell** [comment]
Commit b7b6fdb adds [images](https://www.npmjs.com/package/images) to the perf test.

I see the following results when run locally on an i3-4170.

| module | ops/sec |
| :----- | ------: |
| gm     |    5.59 |
| images |    6.19 |
| sharp  |   32.64 |

In summary, the `images` module is faster than gm (no process forking) but appears to use a blocking API and offers only bicubic interpolation (gm and sharp use Lanczos 3 in these tests).

I'll update the full performance test results before the v0.18.0 release. Thanks for reporting this.
