### ISSUE TITLE
problems with building docker image with alpine

### ISSUE THREAD

**Issue by rpuchalapalli** [lovell/sharp#803]
Hi 

I am getting this error building a docker image with sharp. Please Help

Sharp Version: 0.17.3

Docker file
___________________
FROM mhart/alpine-node:7.10
ARG NPM_TOKEN
WORKDIR /opt/server
COPY package.json package.json  
COPY etc/npmrc .npmrc
RUN apk add --no-cache --virtual build_tools make gcc g++ python && npm install -q && npm cache clean && apk del build_tools
COPY . /opt/server
RUN rm .npmrc
ENV NODE_ENV production
EXPOSE 4012
CMD ["node", "src/index.js"]

log
_______________________
> ursa@0.9.4 install /opt/server/node_modules/ursa
> node-gyp rebuild

make: Entering directory '/opt/server/node_modules/ursa/build'
  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
  SOLINK_MODULE(target) Release/obj.target/ursaNative.node
  COPY Release/ursaNative.node
make: Leaving directory '/opt/server/node_modules/ursa/build'

> sharp@0.17.3 install /opt/server/node_modules/sharp
> node-gyp rebuild

[91mERROR: musl libc (x86_64) requires manual installation - please see http://sharp.dimens.io/en/stable/install/
[0m[91mgyp: Call to 'LDD_VERSION="musl libc (x86_64)
Version 1.1.14
Dynamic Program Loader
Usage: ldd [options] [--] pathname" node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m configure error 
[0m[91mgyp ERR![0m[91m stack Error: `gyp` failed with exit code: 1
[0m[91mgyp ERR! [0m[91mstack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
[0m[91mgyp ERR! stack     at ChildProcess.emit (events.js:191:7)
[0m[91mgyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[0m[91mgyp [0m[91mERR![0m[91m System[0m[91m Linux 4.1.12-61.1.25.el7uek.x86_64
[0m[91mgyp ERR! command[0m[91m "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
[0m[91mgyp ERR! cwd[0m[91m /opt/server/node_modules/sharp
[0m[91mgyp ERR![0m[91m node -v v6.9.5
gyp ERR! [0m[91mnode-gyp -v v3.4.0
[0m[91mgyp[0m[91m [0m[91mERR! not ok

**Comment by lovell** [comment]
Hello, the salient part of the error is:
ERROR: musl libc (x86_64) requires manual installation - please see http://sharp.dimens.io/en/stable/install/

You'll need to install vips-dev via apk:
http://pkgs.alpinelinux.org/package/edge/testing/x86_64/vips-dev

**Comment by rpuchalapalli** [comment]
I downgraded sharp to version 0.16.2 and added  the below line in the docker file. It worked
`

> RUN apk add vips-dev --update-cache --repository http://wjordan-apk.s3.amazonaws.com/ --allow-untrusted

`
