### ISSUE TITLE
SVG Filter Support

### ISSUE THREAD

**Issue by zbryikt** [lovell/sharp#804]
I use sharp + SVG to render png, it's quite convenient.

yet I found it can't render the svg filter correctly in this case, with feMorphology:

```
<?xml version="1.0" encoding="utf-8"?>
<svg width="800px" height="300px" viewBox="0 0 800 300">
  <defs><filter id="extrude">
    <feMorphology operator="dilate" radius="3"/>
    <feColorMatrix type="matrix" values="0 0 0 0 1  0 0 0 0 1  0 0 0 0 1  0 0 0 1 0"/>
  </filter></defs>
  <rect x="0" y="0" width="160" height="300" fill="#28292f"/>
  <text x="10" y="290" stroke="none" fill="#fff" filter="url(#extrude">My Lovely Color</text>
  <text x="10" y="290" stroke="none" fill="#000">My Lovely Color</text>
</svg>
```

this is what sharp generates:

![with sharp](https://cloud.githubusercontent.com/assets/2672307/25980046/b80479b0-36fe-11e7-9bd9-e01bf7961b68.png)

and this is what we have in Chrome:
![with chrome](https://cloud.githubusercontent.com/assets/2672307/25980074/eae73890-36fe-11e7-89ae-b3b4548ca7de.png)

this is how I render the svg content:

```
sharp(new Buffer(code))
  .resize(800, 300)
  .toFile("out.png");
```

I think it's a issue about libvips / libRsvg, although it looks like they have [implemented this long time ago](https://github.com/GNOME/librsvg/blob/master/rsvg-filter.c#L2921)?

**Comment by lovell** [comment]
Hello, it looks like you're missing a closing bracket on the filter attribute value.

```diff
-   <text x="10" y="290" stroke="none" fill="#fff" filter="url(#extrude">My Lovely Color</text>
+   <text x="10" y="290" stroke="none" fill="#fff" filter="url(#extrude)">My Lovely Color</text>
```

**Comment by zbryikt** [comment]
oops! you are right. sorry, not mean to let you debug for me... with a closing bracket it renders normally. thanks!
