### ISSUE TITLE
how to get metadata of output image?

### ISSUE THREAD

**Issue by hbakhtiyor** [lovell/sharp#808]
the current example only get input image metadata, not output, if the input image's size is 1200x1200, we get  `{width: 1200, height: 1200, ...}` not `{width: 400, height: ?, ...}`

```js
      const sharpInstance = sharp(buf).resize(400);
      const resizedBuf = await sharpInstance.toBuffer();
      const metadata = await sharpInstance.metadata();
```

**Comment by lovell** [comment]
Hello, I think you're looking for the metadata of the processed image, which would be:
```javascript
const metadata = await sharp(resizedBuf).metadata();
```

From v0.17.3+, you could also use:
```javascript
const { data, info } = await sharpInstance.toBuffer({ resolveWithObject: true });
```

**Comment by hbakhtiyor** [comment]
thanks

**Comment by ajhool** [comment]
Can this be achieved without calling toBuffer? It seems like a common use-case that somebody would need to know the metadata of the transformed file.

**Comment by lovell** [comment]
@ajhool Please can you provide a code sample demonstrating how you think this might be improved.

**Comment by kghost** [comment]
@lovell
Eg, I want to convert an unknown sized image to 200*100 with { fit: inside }. after resize call, the size of processed image is unknown, I need to calculate paddings and call extend to extend the image to 200*100.

I don't know if it is a bug. After

```
img..resize(200,100,{fit:sharp.fit.inside})
``` 

I got an 100*100 image when input is square.
