### ISSUE TITLE
Provide a CLI wrapper around the existing API

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#81]
Although not as fully featured, this will have far lower memory requirements than existing tools like ImageMagick's `convert`.

Thoughts:
* Will allow compressed image data (JPEG, PNG, WebP) to be piped in from `stdin` and back out to `stdout` without resorting to pseudo-filenames like `-`.
* Will support input and output filename [globbing](https://github.com/isaacs/node-glob) for bulk processing.

I consider this a low priority task right now. Happy to accept a pull request implementing any of the above.

**Comment by lovell** [comment]
Given the sharp-based Grunt and Gulp plugins as well as the presence of vipsthumbnail itself, I'm going to drop this for now.

**Comment by vseventer** [comment]
Sorry to give this old ticket a kick - I've been maintaining the [sharp-cli](https://www.npmjs.com/package/sharp-cli) package for a while, recently rewrote it to implement the full sharp API (per 0.17.1), plus things like reading from stdin & bulk processing.

**Comment by lovell** [comment]
@vseventer Thank you. Feel free to submit a PR with a new "CLI tools" section after "Build tools" and include a link to your module. https://github.com/lovell/sharp/blob/master/docs/install.md#build-tools
