### ISSUE TITLE
Baseline JPEG to  Progressive JPEG

### ISSUE THREAD

**Issue by anks333** [lovell/sharp#810]
is there is any way to convert a baseline JPEG to Progressive JPEG using Sharp Module ?

**Comment by anks333** [comment]
sorry i was not aware of progressive() function

**Comment by lovell** [comment]
Hello, the `progressive()` function is deprecated - try something like the following:
```javascript
sharp('input.jpg')
  .jpeg({ progressive: true })
  .toFile('output.jpg');
```
