### ISSUE TITLE
Error: `make` failed with exit code: 2 (CentOS 6)

### ISSUE THREAD

**Issue by ickata** [lovell/sharp#811]
Hi,

Just the next CentOS issue...

I am getting the following error on `npm install`:

```
make: *** [Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory `/srv/bookit/backend/node_modules/sharp/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-696.1.1.el6.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/bookit/backend/node_modules/sharp
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
```

I have read [installation instructions](http://sharp.dimens.io/en/stable/install/#linux) and manually installed libvips. Installation required also installing the following packages:

  - glib
  - gtk-doc
  - expat-devel
  - gcc gcc-c++
  - centos-release-SCL

I installed them all. I also installed python 2.7 as [required here for node-gyp](https://github.com/nodejs/node-gyp#installation). 

  - CentOS release 6.9 (Final)
  - libvips 8.5.5
  - NodeJS v6.10.3
  - npm 4.6.1
  - gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)
 
Please advise. Thanks!

**Comment by lovell** [comment]
Hello, you'll need gcc v4.8+ for C++11 support.
http://sharp.dimens.io/en/stable/install/#prerequisites

**Comment by ickata** [comment]
@lovell ,

Many thanks for the quick response! I didn't notice that I installed older version of gcc. I followed [this guide on how to install gcc 4.8+](http://hiltmon.com/blog/2015/08/09/c-plus-plus-11-on-centos-6-dot-6/). `sharp` installed properly.

Thanks!
