### ISSUE TITLE
Unsupported output format jpg 

### ISSUE THREAD

**Issue by jingsam** [lovell/sharp#812]
image.toFormat('jpg') throws error but image.toFormat('jpeg') not.
Should we add a alias to support jpg?

**Comment by thisconnect** [comment]
Yes

**Comment by jingsam** [comment]
Sent a PR #814

**Comment by lovell** [comment]
v0.18.0 now available, thanks for the PR.

**Comment by HdSeKenny** [comment]
Hi, @lovell. Is it only support "jpg" and "jpeg" format right now? Therefore, if I want to deal with the png format, how can I do? Change "png" to "jpg" or "jpeg" format first?

**Comment by lovell** [comment]
@HdSeKenny Please see http://sharp.dimens.io/en/stable/api-output/
