### ISSUE TITLE
Fastest way to access pixel data.

### ISSUE THREAD

**Issue by almosnow** [lovell/sharp#816]
I'm looking forward to write an utility (in Node) that extracts things like prominent colors from images.

Considering the most recent version of sharp, what would be the fastest way to access and read the raw pixel data from an image?

I'm not interested in writing or transforming the image later.

**Comment by lovell** [comment]
Hello, did you see [raw](http://sharp.dimens.io/en/stable/api-output/#raw)?

**Comment by almosnow** [comment]
Ok, that would work, thanks.

**Comment by exxy** [comment]
> Hello, did you see [raw](http://sharp.dimens.io/en/stable/api-output/#raw)?

This link points to a hijacked site?

**Comment by lovell** [comment]
@exxy Thanks, I've updated the original comment.

(Please see #2132 for an existing enhancement to clean/update/remove issues from 2017 and earlier, such as this.)
