### ISSUE TITLE
Problem installing on windows 10

### ISSUE THREAD

**Issue by elguesmi** [lovell/sharp#818]
many problems appear when executing node-gyp rebuild 

i'm using vs 2017 and the project need vs 2010 
 

can you attatch the release folder for us

**Comment by lovell** [comment]
> many problems appear when executing node-gyp rebuild

Are you able to provide more details?

If you've not already seen it, https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules provides a lot of relevant information.

**Comment by baltzer** [comment]
Greetings,
I'm getting something similar when I try to install sharp.

I found this in my log: 

> 
> 3087 error Windows_NT 10.0.14393
> 3088 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sharp" "--save"
> 3089 error node v6.10.2
> 3090 error npm  v3.10.10
> 3091 error code ELIFECYCLE
> 3092 error sharp@0.18.1 install: `node-gyp rebuild`
> 3092 error Exit status 1
> 3093 error Failed at the sharp@0.18.1 install script 'node-gyp rebuild'.
> 3093 error Make sure you have the latest version of node.js and npm installed.
> 3093 error If you do, this is most likely a problem with the sharp package,
> 3093 error not with npm itself.
> 3093 error Tell the author that this fails on your system:
> 3093 error     node-gyp rebuild
> 3093 error You can get information on how to open an issue for this project with:
> 3093 error     npm bugs sharp
> 3093 error Or if that isn't available, you can get their info via:
> 3093 error     npm owner ls sharp
> 3093 error There is likely additional logging output above.
> 3094 verbose exit [ 1, true ]

I did not have Python installed at first, I do now, and the result was the above.
I have done a global node-gyp install.

**Comment by lovell** [comment]
@baltzer Which version of MS Visual Studio are you using?

**Comment by elguesmi** [comment]
before installing sharp we need to install python and windows build tools to run node-gyp 

the best solution works with differents windows edition is : 
# npm install --global --production windows-build-tools
