### ISSUE TITLE
Problem with installing - Error 401

### ISSUE THREAD

**Issue by niezborala** [lovell/sharp#819]
I get error 401 when i try to build my app on travis

> ERROR: https://dl.bintray.com/lovell/sharp/libvips-8.3.3-linux-x64.tar.gz status code 401
> gyp: Call to 'LDD_VERSION="ldd (Ubuntu EGLIBC 2.19-0ubuntu6.9) 2.19
> Copyright (C) 2014 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> Written by Roland McGrath and Ulrich Drepper." node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
> gyp ERR! configure error 
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (/home/travis/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> gyp ERR! System Linux 4.4.0-51-generic
> gyp ERR! command "/home/travis/.nvm/versions/node/v6.10.3/bin/node" "/home/travis/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

**Comment by lovell** [comment]
http://status.bintray.com/incidents/gc6bhb1hb6m6

**Comment by lovell** [comment]
Looks like the Bintray incident has been marked as resolved.

**Comment by SoriS** [comment]
Guys, still the same.
ERROR: https://dl.bintray.com/lovell/sharp/libvips-8.3.3-linux-x64.tar.gz status code 401

**Comment by lovell** [comment]
Intermittent Bintray problems again according to https://twitter.com/search?f=tweets&q=bintray

**Comment by lorengreenfield** [comment]
Yep, still happening.

**Comment by lovell** [comment]
Seems to be OK again. Anyone still seeing 401 errors?

**Comment by lorengreenfield** [comment]
Seems like it's passed. All good today.

**Comment by PickRelated-FM** [comment]
Nevermind. It's gone now. File is being downloaded successfully.
