### ISSUE TITLE
Tests crashing in 'Partial image extraction - webp'

### ISSUE THREAD

**Issue by rikh42** [lovell/sharp#821]
I get the following error:-

```
Partial image extraction
    ✓ JPEG
    ✓ PNG
    2) WebP
Segmentation fault (core dumped)
npm ERR! Test failed.  See above for more details.
```

One other test fails for this test causes the crash, here...

```
 Embed
    ✓ JPEG within PNG, no alpha channel
    1) JPEG within WebP, to include alpha channel .  <-- failed test
```

I've cloned the repo and I am running the tests in a vagrant VM running Ubuntu 16.04.2 LTS. (host is OSX)

I found this as I was preparing to add a new feature and wanted to get everything working before I started.

Any suggestions?

**Comment by lovell** [comment]
Hello, does this only occur inside vagrant/virtualbox with OS X as the host?

My best guess is the runtime CPU feature detection of libwebp is clashing with your virtualbox config.

**Comment by rikh42** [comment]
`sudo apt-get install webp` has changed things. All the webp tests still fail, but it no longer crashes at the same place. I now get a memory related crash while trying to run the 'TIFF jpeg compression shrinks test file' test.

**Comment by rikh42** [comment]
Running the tests in OSX results in about 150 failing tests, all reporting the same error - `Uncaught Error: linear: vector must have 1 or 4 elements`

**Comment by rikh42** [comment]
I've moved to trying to run all the tests on OSX now. Rebuilt everything and there are no more crashes. However, all the webp related tests still fail. It appears that vips just doesn't have any webp related features compiled in...

```
  1) Embed JPEG within WebP, to include alpha channel:
     Uncaught Error: VipsOperation: class "webpsave_buffer" not found

  

  2) Input/output Output filename with unknown extension Match WebP input:
     Uncaught Error: Input file is missing or of an unsupported image format
  

  3) Image metadata WebP:
     Uncaught Error: Input file is missing or of an unsupported image format
  

  4) Negate negate (webp):
     Uncaught Error: Input file is missing or of an unsupported image format
  

  5) Negate negate (webp, trans):
     Uncaught Error: Input file is missing or of an unsupported image format
  

  6) Resize dimensions WebP shrink-on-load rounds to zero, ensure recalculation is correct:
     Uncaught Error: VipsOperation: class "webpsave_buffer" not found

  

  7) Threshold threshold default webp transparency:
     Uncaught Error: Input file is missing or of an unsupported image format
  

  8) Tile Google layout with webp format:
     Uncaught Error: VipsForeignSave: ".webp" is not a known buffer format
VipsForeignSave: ".webp" is not a known buffer format
VipsForeignSave: ".webp" is not a known buffer format
VipsForeignSave: ".webp" is not a known buffer format
wbuffer_write: write failed
unix error: Unknown error: -1
```

**Comment by rikh42** [comment]
OK, Solved it.

I had previously installed vips using `brew install vips`. I removed that with `brew uninstall vips`, then deleted the `node_modules`, `build` and `vendor` folders (vendor was the one I had been missing for the last couple of days). 

A fresh `npm install` resulted in the correct libs being fetched and compiled in, so all the tests passed.

I can only assume that the version of vips installed by brew was missing any support for webp.

Thanks for your help.

**Comment by lovell** [comment]
Thanks for the update, webp support is [optional](https://github.com/Homebrew/homebrew-science/blob/master/vips.rb#L43) when libvips is installed via `brew`.

Is the Vagrant-based setup working too?

**Comment by rikh42** [comment]
I've not tried that again just yet - switched back to my dev branch and been adding support for Tinting images. 

I'll give that another go soon, but it might well have been down to stuff in the vendor folder from the wrong os (eg, I might have `npm install`ed in OSX, then re-compiled in Vagrant with the wrong libs...

**Comment by lovell** [comment]
> "might well have been down to stuff in the vendor folder from the wrong os"

This is the most likely cause. I'll close but please do re-open if there are still problems.
