### ISSUE TITLE
Installation Fails in Ubuntu 16.04 WSL

### ISSUE THREAD

**Issue by Bluejay47** [lovell/sharp#822]
When I attempt to install Sharp on Ubuntu 16.04 in Windows Subsystem for Linux the installation process crashes on the following line:

npm ERR! sharp@0.17.3 install: `node-gyp rebuild`
npm ERR! Exit status 1

I have the following installed:
node-gyp 3.6.1
make (4.1-6)
gcc 4:5.3.1-1ubuntu1
npm 3.10.10
nodejs v6.10.3

I attempted to install sharp using the command line
sudo npm install sharp --save

I have attached the debug log.

[npm-debug.zip](https://github.com/lovell/sharp/files/1027463/npm-debug.zip)

Any advice would be appreciated. Thanks.

**Comment by lovell** [comment]
Sorry, I've got no experience of the new Windows/Linux subsystem. 

Do other native modules work, e.g. `npm install --build-from-source bcrypt`?

**Comment by Bluejay47** [comment]
That didn't work either so I will go bug the node-gyp dev's and see if they have some insight. Thanks.
