### ISSUE TITLE
Manually set DPI TIFF image

### ISSUE THREAD

**Issue by YvesBos** [lovell/sharp#823]
In reference to #181 .

Because we're developing an application which will be used for printing, it is absolutely necessary to have the correct dpi.

How straightforward would it be to add this functionality, is it just a matter of exposing the xres and yres in vips_tiffsave?

Could you point me in the right direction?

Thanks in advance!

**Comment by lovell** [comment]
Hello, yes exposing the `xres` and `yres` parameters of libvips' `tiffsave` operation should do what you need. Happy to accept a PR for this like #783.

http://jcupitt.github.io/libvips/API/current/VipsForeignSave.html#vips-tiffsave

**Comment by lovell** [comment]
v0.18.2 now available, thanks for the PR.

**Comment by Andriy-Kulak** [comment]
@lovell @YvesBos is it possible to do this for jpg/png images too? I have a similar need to specify DPI for printing but I am always dealing with JPG and PNG images, not TIFF ones. Thanks!

**Comment by lovell** [comment]
@Andriy-Kulak JPEG does not contain DPI information for printing. PNG can store pixels/mm in its metadata but not sure how widespread support for that is.

https://stackoverflow.com/questions/27323561/do-pngs-or-jpgs-have-a-dpi-or-is-it-irrelevant-when-building-for-retina

PRs accepted, as always!

**Comment by jcupitt** [comment]
I don't know if this is any help, but the official libvips way to do this is with `copy`:

http://jcupitt.github.io/libvips/API/current/libvips-conversion.html#vips-copy

So something like:

```c++
VImage b = a.copy(VImage::option()->set("xres", 99)->set("yes", 99)); 
```

Now when `b` is written, the file format writers will attempt to tag it with the appropriate resolution metadata.

**Comment by lovell** [comment]
Thanks John, the (future) ability to set xres and yres on JPEG images is now at #967

**Comment by kevinswarner** [comment]
I think the instructions for tiff xres and yres are off. It indicates pixels/mm. I think is is behaving like pixels/cm. An image saved as a tiff with no res specified shows in Photoshop as 2.54 pixels/inch. Also, to get my image out at 300 pixels per inch, I have to set xres and yres to 118.1102. Maybe my math is off. Just an observation. If the values were pixels/mm, wouldn't I need to use 11.81102 as the xres and yres values to get a 300 pixels/inch image?

**Comment by lovell** [comment]
@kevinswarner Yes, those numbers do sound like px/cm.

The sharp docs currently match the libvips docs so if this is wrong then both will need updating.

http://sharp.pixelplumbing.com/en/stable/api-output/#tiff
http://jcupitt.github.io/libvips/API/current/VipsForeignSave.html#vips-tiffsave

/cc @jcupitt

**Comment by jcupitt** [comment]
Hello, you can test at the command-line:

```
john@kiwi:~/pics$ vips copy k2.jpg x.tif --xres 11
john@kiwi:~/pics$ tiffinfo x.tif
TIFF Directory at offset 0x87f008 (8908808)
  Image Width: 1450 Image Length: 2048
  Resolution: 110, 28.346 pixels/cm
...
```

So the 11 pixels/mm you set from libvips becomes 110 pixels/cm (the default tiff resolution unit) in the tiff file. You can change the tiff resunit like this:

```
john@kiwi:~/pics$ vips copy k2.jpg x.tif[resunit=inch] --xres 11
john@kiwi:~/pics$ tiffinfo x.tif
TIFF Directory at offset 0x87f008 (8908808)
  Image Width: 1450 Image Length: 2048
  Resolution: 279.4, 71.9988 pixels/inch
...
```

So libvips is always pixels/mm everywhere, and it gets translated into the format's resolution unit on save. You can (separately) tell the saver the resolution unit to use, though I think only png and tif support switchable resolution units.

**Comment by jcupitt** [comment]
... and the same thing for jpg:

```
john@kiwi:~/pics$ vips copy k2.jpg x.jpg --xres 11
john@kiwi:~/pics$ vipsheader -a x.jpg
x.jpg: 1450x2048 uchar, 3 bands, srgb, jpegload
width: 1450
height: 2048
xres: 11
yres: 2.8346
filename: x.jpg
vips-loader: jpegload
jpeg-multiscan: 0
jpeg-chroma-subsample: 4:2:0
exif-data: 162 bytes of binary data
resolution-unit: cm
exif-ifd0-XResolution: 110000/1000 (110.000, Rational, 1 components, 8 bytes)
exif-ifd0-YResolution: 28346/1000 (28.346, Rational, 1 components, 8 bytes)
exif-ifd0-ResolutionUnit: 3 (Centimetre, Short, 1 components, 2 bytes)
orientation: 1
```

You can see it's saved as pixels/cm (the default exif resolution unit). You can set the `resolution-unit` metadata item as well.
