### ISSUE TITLE
Reach out for using pkg

### ISSUE THREAD

**Issue by kaminoo** [lovell/sharp#826]
Hello!
I love your library, super helpful and fast. Thanks for building it.

This issue is not exactly with the library, but you might have some idea and shed some light on an issue I've been having. I have a project I want to compile using [zeit/pkg](https://github.com/zeit/pkg).
[Pkg](https://github.com/zeit/pkg) handles .node files in a specific way, and it seems its causing sharp to not work properly, thus I'm unable to package my project. The .node needs to be copied in the same directory as the final executable, and I believe the rest of your needed libraries are causing some problem with this.

I left a report over at: https://github.com/zeit/pkg/issues/107

Maybe you guys can tell me what sort of thing the sharp.node might be doing that is causing this problem?

Any help would be appreciated!

**Comment by lovell** [comment]
https://github.com/zeit/pkg/issues/104#issuecomment-302335175 might be relevant.

**Comment by kaminoo** [comment]
@lovell thank you very much for responding!
It certainly seemed like a fix at the time... I figured that using yarn+nvm might be the problem. I defaulted to plain node with npm, but still get the same problems. It seems sharp.node has something specific that just won' work. Thanks for the time, maybe eventually pkg will have something better for .node files.

**Comment by kaminoo** [comment]
@lovell hi! I have an update on this!
The new pkg 4.0.0 is out, and when running it it shows a better error description, and now can see why the sharp.node object is not loaded.

Error: dlopen(/build/sharp.node, 1): Library not loaded: @rpath/libvips-cpp.42.dylib Referenced from: /build/sharp.node Reason: image not found

How does the sharp.node handling using these external libraries? I tried putting the dylib in the same directory without luck.

Any ideas?

**Comment by lovell** [comment]
> "How does the sharp.node handling using these external libraries? I tried putting the dylib in the same directory without luck."

For OS X, see https://github.com/lovell/sharp/blob/master/binding.gyp#L141-L142
```
# Ensure runtime linking is relative to sharp.node
'-rpath \'@loader_path/../../vendor/lib\''
```

**Comment by kaminoo** [comment]
@lovell I just finally managed to make this work, thanks to your invaluable input.
I'm leaving this comment for other people that might run into this issue.
My best solution for using zeit/pkg with sharp, was to make a folder named "modules" next to the executable that pkg makes. Inside that, copy the entire sharp that you find in your node_modules, which has a compiled sharp.node for the platform you are running (if you need to build on a platform, and run on another, I don't think its going to work as of pkg@4.0.0). From there, pkg requires that the .node files are located in the same folder as the final executable. But since sharp need a specific folder structure, I just did a symbolic link pointing to the proper location. The structure is left with something like this:

```
/build/your_executable_from_pkg
/build/sharp.node -> /build/modules/sharp/build/Release/sharp.node
/build/modules/sharp (entire folder that is left in node_modules after npm install)
```

@lovell THANK YOU VERY MUCH for this awesome library, for the awesome support you give to it. And I hope it comes back to you 10 times what you give the community. Much love from us in Argentina.

**Comment by lovell** [comment]
Thanks for the updates, glad to hear you got it working.
