### ISSUE TITLE
Zero-byte files sporadically generated when overlaying images

### ISSUE THREAD

**Issue by christianflintrup** [lovell/sharp#829]
Only sometimes, when overlaying a PNG watermark onto a JPEG image using the attached code, no resulting data will be streamed from Sharp to the destination file.

- On Mac OS X, the issue never occurs.
- On eight different tested Linuces (Ubuntu 14.04, 16.04, 16.10, 17.04, 17.10, Debian 7, 8, 9), it occurs sporadically.
- The smaller the overlay size, the less often the issue occurs.
- Node.js versions 6 and 7 tested, with no difference.
- Sharp 0.17.3 with the bundled libvips 8.4.2
- Higher concurrency seems to cause the issue to occur less frequently, but raising it more than the number of physical cores seems to have no further effect.
- When the issue occurs, the internal sharp `process` counter will have a value of zero. When it's generating the image, the value is one.

```
const sharp = require('sharp')
const fs = require('fs')

const inputStream = fs.createReadStream('in.jpg')
    
const sourceSharp = sharp()
inputStream.pipe(sourceSharp).resume()

sourceSharp.metadata().then(sourceInfo => {
  
  const mark = 'overlay.png'

  sharp(mark).metadata().then(markInfo => {
    return sharp(mark)
    .resize(160, 96)
    .toBuffer({ resolveWithObject:true })
    .then(buffer => {
      
      console.log('sharp counters: ', sharp.counters())
      
      const transformer = sharp()
        .resize(1600, 960)
        .overlayWith(buffer.data, { left: 0, top: 0 })
      
      const imageStream = sourceSharp.pipe(transformer)
      
      const outStream = fs.createWriteStream('out.jpg')
      
      imageStream.pipe(outStream)
      return imageStream
    })
    
  })
  
})
```

The code is nested as such because image dimensions for both the overlay and background image are needed for calculations of sizing and placement of the overlay, before conducting the final transformation.

The images in question used for testing can be found [here](https://github.com/lovell/sharp/files/1037254/sample.zip). Here's a [Dockerfile](https://github.com/lovell/sharp/files/1037251/Dockerfile.txt) that I'm using for running it.

**Comment by lovell** [comment]
Hello, this code is calling `resume()` on the readable (output) side of the sharp instance before the pipe to the `transformer` destination has been set up, which will lead to a race condition. Try the following change:

```diff
- inputStream.pipe(sourceSharp).resume()
+ inputStream.pipe(sourceSharp)
```

**Comment by christianflintrup** [comment]
Thanks a lot, that worked. I'd had issues previously where it wouldn't trigger the render for some reason, except if I added the `.resume()`.
