### ISSUE TITLE
Installed sharp module on MacOs does not work on AWS Lambda(Ubuntu)

### ISSUE THREAD

**Issue by vkkis93** [lovell/sharp#830]
I have my code and installed sharp module on MacOs Sierra.
I zipped these in zip file.
After that I am uploading my zip file to AWS Lambda.
When I run my lambda function I always see error
`module initialization error: Error
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
 `
If I install sharp module on ubuntu os and copy it to  aws lambda - will work.
How I can fix it ?

**Comment by lovell** [comment]
Hello, the pre-compiled binaries for OS X will not work on Linux. `npm install` has to occur on the same platform as the runtime.

http://sharp.dimens.io/en/stable/install/#aws-lambda
