### ISSUE TITLE
attention mode crop problems (0.18)

### ISSUE THREAD

**Issue by puzrin** [lovell/sharp#832]
To continue https://github.com/lovell/sharp/issues/727.

I do image thumbnals, with slightly reduced width (170*150px), and some images a cropped on wrong side. See sources below for experiments.

Properly cropped:

- https://www.flickr.com/photos/dproductions57/8911435334/

Improperly cropped (at wrong side):

- https://www.flickr.com/photos/136807076@N07/24161551991/
- https://www.flickr.com/photos/136807076@N07/24161549231/

Result:

![cropped](https://cloud.githubusercontent.com/assets/319465/26592580/db6f8c40-4569-11e7-9763-107ec4b23e1e.png)

I don't know where the problem happens, because this bug was reported to libvips and fixed there.

**Comment by kleisauke** [comment]
I think this is the result of libvips check for the presence of skin tones, see:
![skin-check1](https://cloud.githubusercontent.com/assets/12746591/26596802/3f8d37a8-4570-11e7-84d2-39ea6c325460.png)
![skin-check2](https://cloud.githubusercontent.com/assets/12746591/26596803/3f8f8dd2-4570-11e7-8268-6666fbbca651.png)

`vipsthumbnail -s 170x150 --smartcrop attention input.jpg` gives the same results as you've specified.

/cc @jcupitt

**Comment by puzrin** [comment]
@kleisauke thanks! Seems i'm lucky with finding bad images, those were first 3 random ones :). 

[smartcrop.js](https://29a.ch/sandbox/2014/smartcrop/examples/testbed.html) works better.

@jcupitt should we move to to libvips tracker?

**Comment by jcupitt** [comment]
Hello, thanks for the samples, I've made an issue on libvips for this: https://github.com/jcupitt/libvips/issues/672

**Comment by puzrin** [comment]
@lovell https://github.com/jcupitt/libvips/issues/672#issuecomment-307365416

**Comment by KyleAMathews** [comment]
@lovell I think we need to update sharp to use libvips 8.5.7 to get the improvements?

**Comment by lovell** [comment]
@KyleAMathews Yes, that's right. sharp v0.19.x will depend upon (and provide) libvips v8.6.0.

**Comment by KyleAMathews** [comment]
Great!

What version of libvips is sharp 0.18 on? It looks like 8.5.5 still? My question was about getting the libvips improvements created from this thread which were added in libvips 8.5.7.

**Comment by lovell** [comment]
@KyleAMathews sharp v0.18.2 requires a [minimum of libvips v8.5.5](https://github.com/lovell/sharp/blob/v0.18.2/package.json#L91) and therefore pre-built binaries for this specific version are provided for local use. During installation, sharp will look for and work with a globally-installed version of libvips equal to or greater than this. This means libvips v8.5.7 can be used with sharp v0.18.2 but you'll need to globally install it first.

**Comment by KyleAMathews** [comment]
@lovell any reason not to bump the version of libvips that gets installed to the latest in the 8.5.x series? 8.5.9 was just released yesterday https://github.com/jcupitt/libvips/releases/tag/v8.5.9

**Comment by lovell** [comment]
@KyleAMathews The version of the prebuilt libvips binaries is fixed per sharp release. To bump the patch version to libvips v8.5.9 we'd need to also bump a new patch version of sharp, e.g. v0.18.5. Unfortunately this would pick up an SVG bug introduced in libvips v8.5.7 that v8.6.0 fixes - see https://github.com/jcupitt/libvips/pull/724

To makes things a little easier (for me at least) to manage and help troubleshoot, I've been providing the same version of libvips for all patch releases of a given minor version of sharp. 

sharp v0.19.0 is currently sitting in the [suit](https://github.com/lovell/sharp/tree/suit) branch and will be merged to the master branch and published as soon as libvips v8.6.0 is out.

It'll be interesting to see how much impact moving gatsby from sharp v0.17.3 to v0.19.0 will have on the libvips download stats. Currently ~60% of libvips binaries requests are for v8.4.2 (as used by sharp v0.17.x).

![](https://screenshots.firefoxusercontent.com/images/e3b122d8-a627-42d8-8f14-f2759c8b1c64.png)

**Comment by KyleAMathews** [comment]
Makes sense! Looking forward to libvips 8.6 & sharp v0.19.0!

**Comment by lovell** [comment]
sharp v0.19.0 with libvips v8.6.1 now available.
