### ISSUE TITLE
vips compiled with imagemagick fails with pdfs

### ISSUE THREAD

**Issue by BoLaMN** [lovell/sharp#834]
managed to create a custom tar ball with imagemagick but when I try to input a PDF it throws "Input buffer contains unsupported image format"

I can see in sharp.format that magick is all true while pdf is all false, guessing this is due to not compiling with poppler which the libvips documentation says it should fallback to imagemagick which is what I'm looking for due to the lack of cmyk support with poppler.

any hints?

**Comment by BoLaMN** [comment]
managed to work around it by using gm to preconvert it and then use sharp to handle all the transforming but its probably not the nicest work around due to the increased dep size

``` javascript
let preConvertFormats = 
  {pdf: 'png'};

let format = 'pdf';
let formatTo = preConvertFormats[format];
  
http.get(url, function(err, stream) {
  let image;
  if (formatTo) {
    image = gm(stream).stream(formatTo).pipe(sharp());
  } else { 
    image = stream.pipe(sharp()); 
  }
});```

**Comment by lovell** [comment]
Hello, was Imagemagick compiled with PDF support?

**Comment by BoLaMN** [comment]
i compiled magick with `./configure --prefix=${TARGET} --enable-shared --disable-static --disable-dependency-tracking --with-modules --with-gslib --without-magick-plus-plus`

im going to try compiling poppler with `--enable-cmyk: Include support for CMYK rasterization.` and see what the results are 

cheers

**Comment by lovell** [comment]
Does #840 mean you've been able to make progress with this?

**Comment by lovell** [comment]
Closing as I suspect from further questions that this is resolved, please feel free to re-open if not.
