### ISSUE TITLE
Docs: FreeBSD Latest VIPS Port Version

### ISSUE THREAD

**Issue by mkastner** [lovell/sharp#839]
I've just spent quite some time on a FreeBSD production server wondering why node-gyp wouldn't build. The error message was:

`fatal error: 'vips/vips.h' file not found`

Finally, after hours of following the wrong trails, I rather coincidentially read this sentence in the Linux section of the documentation:

> To use your own version of libvips instead of the provided binaries, make sure it is at least the version listed under config.libvips in the package.json file that it can be located using pkg-config.

So I checked my versions and found out that 4.4.5 was the version on the FreeBSD machine and 4.5.5 was the latest version of sharp release v0.18.1.

I confess, that I had only sloppily read the linux section, but it just didn't occur to me that there'd be anything written that would address FreeBSD too.

So to make this long story short: please, copy the hint I quoted above about the versions to the FreeBSD section. I think most of the FreeBSD Users are actually building their programs from ports.

And a further request would be, that if possible, fire an error message if the BSD/Linux build version is below the one required in package.json(config.libvips).

**Comment by lovell** [comment]
Hello, happy to accept a PR with this useful doc change.

The work for #186 will improve "info" level messaging around attempts to find (or not) the most suitable libvips to use.

**Comment by mohd-akram** [comment]
To install on FreeBSD 11 I used version 0.17.3 of sharp and ran this first:

    pkg install -y pkgconf vips

**Comment by lovell** [comment]
The FreeBSD isntall docs have seen a number of small improvements recently.

https://github.com/lovell/sharp/blob/suit/docs/install.md#freebsd

PRs for further improvements are always welcome.
