### ISSUE TITLE
pass --vips-tile-height for pdfload

### ISSUE THREAD

**Issue by BoLaMN** [lovell/sharp#840]
currently testing out libvips with poppler and was wondering how to pass the --libvips-tile-height argument like https://github.com/jcupitt/libvips/blob/fc7f9d49410e955c5086a3814a413745d37d27ad/libvips/foreign/pdfload.c#L693 

currently converting a PDF is taking about 5 - 6 seconds but only using ~30 - 50mb of memory out of ~1500mb so was looking to try bench mark it with larger tile heights to see if I can return quicker results 

cheers

**Comment by lovell** [comment]
Hello, this libvips init-time parameter is currently unavailable via sharp.

Given you are compiling your own libvips from source, perhaps modify [private.h#L145-L149](https://github.com/jcupitt/libvips/blob/a5b04091ee95d28bf2725c00ed253ab2b3ad49bd/libvips/include/vips/private.h#L145-L149) with the values you need.

**Comment by BoLaMN** [comment]
So I've been doing some benchmarks and a lot of recompiling and it seems poppler looses a lot of speed when piped through cairo so I'll still use sharp for the image conversion side of things

In the mean while I'm going to do some bench marks against the opensourced project pdfium from google + foxit that runs in chromium (https://pdfium.googlesource.com/pdfium/)

From the benchmarks I've seen it's atleast 7x quicker, handles colorspaces correctly and is actively maintained with similar low memory usage 

not sure the chances of libvips getting direct intergration with pdfium but would be nice seeing that it's opensource and could be included by default.

cheers!

**Comment by lovell** [comment]
Thanks for the update. Perhaps suggest the future possible use of pdfium over at the libvips repo. (I had a quick look but it seems to be lacking in API documentation and has yet to be made widely available as "libpdfium".)

**Comment by jcupitt** [comment]
Here's an enhancement issue in libvips for pdfium:

https://github.com/jcupitt/libvips/issues/689

As you say @lovell, it looks promising but a little immature at the moment.

**Comment by adityapatadia** [comment]
@lovell is there any possibility to add this parameter after these years?

**Comment by adityapatadia** [comment]
I have tried changing the parameter directly in source as suggested but it does not seem to be taking effect.

**Comment by adityapatadia** [comment]
Is there any way to check in compiled vips if the parameter is taking effect?
