### ISSUE TITLE
Questions: overlayWith() + large images, metadata preservation...

### ISSUE THREAD

**Issue by tbarela** [lovell/sharp#844]
Hi there,

I'm working on an app thats canvas based, but uses sharp for high quality downscaling of overlays. However, we now need features beyond what the browser and canvas support(metadata and color management/profiles, more image formats, etc. ). Sharp almost seems to be the natural choice here. I would like to have it handle the whole load-render-export process. But I'm having some trouble wrapping my head around some pieces...

1. Is there a reason why overlayWith() cannot use an overlay image larger than the bg image? Is this a hard limit of libvips? Any work arounds besides manually clipping?

2. Is it possible to set/inject metadata back into a new sharp instance? I've been thinking I could use sharp to load in the image and any metadata, send pixels to a buffer where I do some operations, and then write it back to a new instance and then export it, but I don't see how to preserve the metadata. Is this possible?

Thank you for your hard work. Any pointers you can provide are much appreciated!

**Comment by lovell** [comment]
Hello,

1. No hard limits, happy to accept a PR if you'd like to introduce clipping.
2. See [withMetadata](http://sharp.dimens.io/en/stable/api-output/#withmetadata) and #650 for possible future enhancements.

**Comment by lovell** [comment]
@tbarela Hope this answered your question, please re-open with more details if not.
