### ISSUE TITLE
Failure to convert a Zeiss .lsm file to png

### ISSUE THREAD

**Issue by DaGaMs** [lovell/sharp#845]
I'm trying to convert a 12-bit RGB raw Zeiss microscope image to a png. This used to work in v0.17.2, but is broken in 0.18.1. Unfortunately I get absolutely no error output, but the resizer triggers `on("error")` with a `{}` argument.

Any ideas what might be going on?

[zeiss_710_3_channel_1024x1024_12bit.lsm.zip](https://github.com/lovell/sharp/files/1075978/zeiss_710_3_channel_1024x1024_12bit.lsm.zip)

**Comment by DaGaMs** [comment]
By the way: the `.lsm` is effectively a TIFF, you can open it as such in any graphics program

**Comment by DaGaMs** [comment]
hmm, ok, this is actually not a Sharp issue but a problem in libvips - upgrading to version 8.4.2 seems to have triggered the failed tests, even when using Sharp 0.17.2

**Comment by lovell** [comment]
@DaGaMs Is this still a problem? Is there a libvips reference (I can't find one)?

**Comment by lovell** [comment]
See https://github.com/jcupitt/libvips/issues/651
