### ISSUE TITLE
Tips for implementing small blurred previews?

### ISSUE THREAD

**Issue by wmertens** [lovell/sharp#846]
Facebook Engineering posted this a while ago: https://code.facebook.com/posts/991252547593574/the-technology-behind-preview-photos/

How could I do the same with sharp? I imagine I'd resize the image, maybe apply blur to it (before or after resize?) and then grab the image from the buffer, as well as the image dimensions, and store these in the image database.

Then convert this to base64, and on the client side make a data url containing the default header, dimensions and image data. When using server-side rendering, these images could be embedded in the html (should compress well), and css could take care of the blur client side. => instant images

Does that sound reasonable? I just don't know what parts of the header need to be retained, and if blurring while resizing is a good idea.

I suppose this is more of a usage question than a feature request, so if I should be asking this elsewhere I apologize.

**Comment by papandreou** [comment]
Looks like the lqip webpack loader does [exactly that using sharp](https://github.com/zouhir/lqip-loader/blob/master/index.js#L65-L76). Showcase here: https://lqip-loader.firebaseapp.com/

**Comment by lovell** [comment]
In sharp, a blur operation will always occur after a resize, if any, a behaviour that matches what would be required here.

The Facebook "trick" is to have the client already hold a common JPEG header, including Huffman tables, for a given JPEG percentage "quality". This fixed header can be removed from the data transferred by the server, then prepended to the incoming compressed pixel data on the client.

First thing I'd do would be to generate a few JPEG images of the same dimensions and quality and see how many bytes at the start are the same.

If you're using base64 then I can't not recommend https://github.com/lovell/64 :)

**Comment by lovell** [comment]
@wmertens Hope these answers helped, please feel free to re-open with more details if not.

**Comment by tomlokhorst** [comment]
I'm also looking into building small preview images.

It seems the Facebook "trick" doesn't work with sharp, because the Huffman tables [are optimised when generating JPEGs](http://sharp.pixelplumbing.com/en/stable/#optimal). Therefor the headers for different JPEGs are different from each other.

Am I understanding this correctly?
