### ISSUE TITLE
TypeError: Buffer.alloc is not a function, requires Node v4.5.0

### ISSUE THREAD

**Issue by bvarga** [lovell/sharp#847]
Got the following error:

> sharp@0.18.0 install /tmp/test/node_modules/sharp
> node-gyp rebuild

/tmp/test/node_modules/sharp/node_modules/tar/lib/pack.js:32
const EOF = Buffer.alloc(1024)
                   ^

TypeError: Buffer.alloc is not a function
    at Object.<anonymous> (/tmp/test/node_modules/sharp/node_modules/tar/lib/pack.js:32:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/tmp/test/node_modules/sharp/node_modules/tar/lib/create.js:6:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
gyp: Call to 'GLOBAL_VIPS_VERSION="" node -e "require('./binding').use_global_vips()"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error

seems like 0.18.x version is using a newer tar module which is not compatible with node 4.x

installing 0.17.x works fine.

**Comment by lovell** [comment]
Hello, it looks like `Buffer.alloc` was added in Node [4.5.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V4.md#4.5.0) so I guess that's the new minimum. Happy for a PR to bump the minimum [engine](https://github.com/lovell/sharp/blob/master/package.json#L94) value to this.

**Comment by rick-rheo** [comment]
This also fails under Node 4.8

```
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Volumes/code/privateEye/node_modules/sharp
gyp ERR! node -v v4.7.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sharp@0.17.1"
npm ERR! node v4.7.0
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.17.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.17.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/code/privateEye/npm-debug.log

```

**Comment by lovell** [comment]
Added in commit ec617f2, thanks for the report!

**Comment by stevensacks** [comment]
I'm still getting this error in node 6.10 on AWS builds.

```/builds/project/node_modules/sharp/node_modules/tar/lib/pack.js:32
const EOF = Buffer.alloc(1024)
                   ^

TypeError: Buffer.alloc is not a function
    at Object.<anonymous> (/builds/project/node_modules/sharp/node_modules/tar/lib/pack.js:32:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/builds/project/node_modules/sharp/node_modules/tar/lib/create.js:6:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
gyp: Call to 'GLOBAL_VIPS_VERSION="" node -e "require('./binding').use_global_vips()"' returned exit status 1. while trying to load binding.gyp
ERROR: Job failed: exit code 1```

**Comment by lovell** [comment]
@stevensacks `Buffer.alloc` was added in [v5.10.0](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_alloc_size_fill_encoding) (and backported to Node v4.5.0).

The [Changelog for Node v6.0.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#2016-04-26-version-600-current-jasnell) also mentions its availability.

The [CI job for sharp v0.18.1 ran cleanly on Node v6.10.3](https://travis-ci.org/lovell/sharp/jobs/237662072).

**Comment by stevensacks** [comment]
Yeah. I'm definitely confused about this. Not sure why I'm getting this error on builds.

**Comment by kduraiswami** [comment]
@stevensacks  I was stuck on this for a while, just wanted to let you know what I did: 

Use [NVM](https://github.com/creationix/nvm/blob/master/README.md#usage) to get latest version of Node (I went to latest - 8.1.2)
nvm use node 
npm install 

and now everything is fine 👍
