### ISSUE TITLE
Enhancement: add "shrinkOnLoad: false" option to prevent use of libjpeg/libwebp shrink-on-load

### ISSUE THREAD

**Issue by jardakotesovec** [lovell/sharp#848]
I am trying to find out why I have different resize result directly from vips cmd (vips-8.5.6-Thu Jun  8 16:24:42 BST 2017) and sharp (0.8.1).

Source file (having centered artwork.. so its easy to determine the shifts in small resized images):
![source](https://user-images.githubusercontent.com/1590681/27219515-3cc5e9ec-5282-11e7-98ce-5bbce22bd73d.jpeg)

Resize with sharp:
```
sharp('source.jpeg')
.resize(25, 35, {
    centreSampling: true
})
.toFile('sharp.png')
```
![sharpwithcentre](https://user-images.githubusercontent.com/1590681/27219630-af9e1dd6-5282-11e7-910e-57c96dce5f9c.png)

Resize with vips:
```
 vips resize --centre source.jpeg vips.png 0.014285714285714
```
![vipscentre2](https://user-images.githubusercontent.com/1590681/27219622-a07c4a94-5282-11e7-884d-79d115687621.png)

Result with vips is nicely centered, but with sharp is shifted to left top and also somehow stretched. I also tried to add `.ignoreAspectRatio()` option, but did not make difference.

Is there any other option I have missed to get the same result with vips? Any hint appreciated.

**Comment by lovell** [comment]
Hello, `vips resize ...` doesn't use JPEG shrink-on-load, which would be my first guess as to what could be causing this. Do you still see this problem if you add the [gamma](http://sharp.dimens.io/en/stable/api-operation/#gamma) operation into your pipeline?

**Comment by jardakotesovec** [comment]
@lovell Hi, thanks for quick feedback. You are right, when there is gamma operation in pipeline to suppress the shrink-on-load, it looks correctly.

**Comment by jardakotesovec** [comment]
@lovell I guess that there is not much that can be done about it other than just having option to skip that shrink-on-load optimization?

**Comment by lovell** [comment]
That's correct, perhaps as a new resize option - let's file under possible future enhancement.

**Comment by jardakotesovec** [comment]
With further testing. I end up shifted result from sharp again, even when using gamma function. Only difference is the resolution of the source image. Tried both with and without `ignoreAspectRatio`. Result from vips cmd still looks precisely centered.

Source file:
![868_616](https://user-images.githubusercontent.com/1590681/27482532-2a4b7ffc-5822-11e7-9639-294b45cf1c19.jpeg)

Resize with sharp:
```
sharp('source_868_616')
// .ignoreAspectRatio()
.resize(25, 35, {
    centreSampling: true
})
.toFile('sharp.png')
```
![sharp868_616_1withcentregamma](https://user-images.githubusercontent.com/1590681/27482604-64694412-5822-11e7-99f9-d98f2cee4b27.png)

vips:
```
vips resize --centre source_868_616.jpeg vips_868_616.png 0.040584415584416
```
![vips_868_616](https://user-images.githubusercontent.com/1590681/27482635-845b06ca-5822-11e7-9560-c93c56864214.png)


@lovell Can you think of anything else except the load-on-shrink (disabled by gamma operation) that could make difference between using the vips resize and sharp.resize?

**Comment by lovell** [comment]
Did you see #781? The `vips_resize` operation is a combination of `vips_shrink` and `vips_reduce`. Sharp uses these two operations directly, but with a slightly higher preference for shrink than the logic in `vips_resize`. This can cause a tiny bit of aliasing at certain ratios but is much faster (although I should probably revisit the performance as `vips_reduce` has seen recent improvements). This would explain the difference seen here.

**Comment by jardakotesovec** [comment]
@lovell I see, can you point me where I could adjust the ratio to have same result as vips_resize, so I can test if thats what make the difference. As it seems not only different antialiasing but there is overall image shift to the left top.

**Comment by lovell** [comment]
[pipeline.cc](https://github.com/lovell/sharp/blob/master/src/pipeline.cc) contains the logic - you're looking for anything that can modify `shrink_on_load`, `xshrink` and `yshrink` - set them all to 1.

**Comment by jardakotesovec** [comment]
@lovell Great, thanks for hint. I have done some initial experiments.. and I achieved different results when changing xshrink and yshrink. It could not be 1 (`reducev: reduce factor too large`), but tried somewhat smaller values than are calculated. Result was less shifted, but still shifted.

I also tried these two source images from above with vipsthumbnail cli and got always perfectly centered thumbnail. And if I understand correctly vipsthumbnail is also using the jpeg shrink-on-load trick, but its somehow not causing the shift.

And last experiment was just to hack in the `pipeline.cc` to replace current resizing just with `image.thumbnail`. And measure time in javascript for resize operation. In both cases I was getting around 50ms using the source image 1750x2461 and target resolution 25x35. But with `image.thumbnail()` the result was nicely centered.

Disclaimer: it was really just initial test and I am pretty new to the implementation details so I don't want to make any conclusive claims. 

But based on this test it seems reasonable to investigate if maybe using the image.thumbnail would make sense for sharp? What do you think?

**Comment by jardakotesovec** [comment]
To lower the chance that `vipsthumbnail` results in centered image 'just' by luck (as combination of source resolution and processing thresholds) I generated 25 source images with various resolutions ranging from 400-1500 widths and in next step I used these source images to generate 25x35 thumbnails and all resulting thumbnails were nicely centered. Which suggests that this shift can be avoided.

Do you have some suggestions what to test to find out if possibly image.thumbnail could be good fit for sharp?

**Comment by jardakotesovec** [comment]
@lovell Is there something I can help with to move this issue forward?

**Comment by lovell** [comment]
Ahoj @jardakotesovec, I still plan to revisit the shrink vs reduce ratio, sorry for any delay. I'll take you up on your offer of help soon :)

**Comment by lovell** [comment]
@jardakotesovec Commit 7e9bbde on the [improve-shrink-vs-reduce-ratio](https://github.com/lovell/sharp/tree/improve-shrink-vs-reduce-ratio) branch seems to improve things based on some quick testing, and at minimal performance cost. Are you able to take a look?

**Comment by jardakotesovec** [comment]
@lovell oki, great.. will do some testing in 30 minutes..

**Comment by jardakotesovec** [comment]
@lovell My test still indicates its moving for certain source resolutions. I generated various source resolution and applied sharp from master and branch on it to resize it all to 25x35 as well as vipsthumbnail. You can see that vipsthumbnail results are not moving when you flick through the results:

https://www.dropbox.com/sh/pwm8ner26i1lsyn/AACE8Hq-zCzMQMgxeblW1DNpa?dl=0

**Comment by lovell** [comment]
Thanks for testing. The next step would be to experiment with slightly lower values in the `xresidual > 0.9 || yresidual > 0.9` condition, most likely between 0.5 and 0.9, to see where the sweet spot lies. The lower the number the more a floating-point reduce will be favoured over an integral shrink.

**Comment by jardakotesovec** [comment]
@lovell And reason for not using directly image.thumbnail from vips is performance? As I mentioned in one of my previous posts when I tried resize via original implementation vs image.thumbnail for image 1750x2461 and target resolution 25x35 I was getting 50ms in both cases. But big part in that performance could have done that shrink-on-load optimization. So maybe if I would do that with png I would get some difference.

So maybe I could do some additional tests to see if maybe the image.thumbnail fast enough?

**Comment by lovell** [comment]
@jardakotesovec The main reason for not using `vips_thumbnail` directly is that sharp provides operations such as rotation, extraction and (for compositing) premultiplication in the same pipeline as resizing. Trying to conditionally use `vips_thumbnail` would result in more complex code that is less efficient, potentially incurring more than one premultiply-unpremultiply round trip.

**Comment by jardakotesovec** [comment]
@lovell And any reason not using logic from vips_resize  (which decide how exactly to use shrink and reduce), since never had issue there. I can try to understand whats difference between your implementation and vips_resize.. 

Just checking before I spend time on that if its maybe something you already know that you don't want to do (because of the performance)?

**Comment by lovell** [comment]
Ahoj Jarda, sorry I haven't been able to spend much time on this, it's still something I'd like to look at before the next major release. I believe the first thing to do is allow the shrink-on-load feature to be optional, which should prevent most of the artefacts you were originally seeing.

If you have the time to experiment with replacing sharp's use of vips_shrink/vips_reduce with vips_resize then please do go ahead, thank you!

**Comment by jardakotesovec** [comment]
Ahoj Lovell,
spent some time today to use directly vips_resize. With simple replacement for original implementation I have 3 failing tests.. will look into it more tomorrow.

```
      if (xfactor != 1.0 || yfactor != 1.0) {
        VipsKernel kernel = static_cast<VipsKernel>(
          vips_enum_from_nick(nullptr, VIPS_TYPE_KERNEL, baton->kernel.data()));
        if (
          kernel != VIPS_KERNEL_NEAREST && kernel != VIPS_KERNEL_CUBIC && kernel != VIPS_KERNEL_LANCZOS2 &&
          kernel != VIPS_KERNEL_LANCZOS3
        ) {
          throw vips::VError("Unknown kernel");
        }

        image = image.resize(1.0 / xfactor, VImage::option()
          ->set("vscale", 1.0 / yfactor)
          ->set("kernel", kernel)
          ->set("centre", baton->centreSampling));
      }

```

```
  1) Embed PNG with alpha channel:
     Error: Expected maximum similarity distance: 5. Actual: 12.
      at test/fixtures/index.js:157:27
      at test/fixtures/index.js:33:9

  2) Partial image extraction Extract then rotate:
     Error: Expected maximum similarity distance: 5. Actual: 8.
      at test/fixtures/index.js:157:27
      at test/fixtures/index.js:33:9

  3) Gamma correction alpha transparency:
     Error: Expected maximum similarity distance: 20. Actual: 23.
      at test/fixtures/index.js:157:27
      at test/fixtures/index.js:33:9

```

I looked more into 2) and not sure whats the issue as visually they seem identical, will double check tomorrow. Maybe its also something with alpha channel as others.

Btw as I recall I did not have issue with shrinkOnLoad when testing these centering issues with vipsthumbnails.. so maybe option for disable that might not be necessary.

Only performance test was one resize (run several times) from big resolution and consistently saw difference original sharp: around 55ms and vips_resize around 70ms. You have some benchmark suite?

**Comment by rnanwani** [comment]
Hi

I was experimenting with this issue.
I changed the condition with `xresidual` and `yresidual` values to this

` if (xshrink > 1 && yshrink > 1 && (xresidual >= 0.5 || yresidual >= 0.5)) {`

Though, I get the results I expect, what is the side effect of reducing the value to this low a factor? 

I am trying to avoid Moire effect in images on resizing. You can pick up a striped shirt like this 

https://assets.myntassets.com/v1/assets/images/1861658/2017/5/26/11495781007283-ether-Men-Grey--White-Slim-Fit-Striped-Casual-Shirt-6401495781007085-1_mini.jpg

Normally you would end up with something like this 
![image](https://user-images.githubusercontent.com/4739557/30647348-d2d17152-9e38-11e7-8403-f00f15af6d5f.png)

(Note the curved stripes around the pocket)

With the modified if statement, I end up with this
![image](https://user-images.githubusercontent.com/4739557/30647386-ea447d98-9e38-11e7-9eed-28f47fb05dc3.png)

`vipsthumbnail` from the command line gives the correct result without the moire effect.

**Comment by lovell** [comment]
v0.19.0 now available, thanks for all your work on this @jardakotesovec !

**Comment by jardakotesovec** [comment]
@lovell Wohoo :-) Thank you!
