### ISSUE TITLE
Support download package on Alpine Linux

### ISSUE THREAD

**Issue by tangkhaiphuong** [lovell/sharp#850]
I use Docker with image from https://github.com/wjordan/dockerfile-libvips with
npm install sharp.

The build raise error:
LDD_VERSION musl libc (x86_64) requires manual installation - please see http://sharp.dimens.io/en/stable/install/

How can I use this library on Alpine ?

Here my Dockerfile: 
[Dockerfile.txt](https://github.com/lovell/sharp/files/1082637/Dockerfile.txt)

**Comment by lovell** [comment]
Hello, you'll need to install [vips-dev](http://pkgs.alpinelinux.org/package/edge/testing/x86_64/vips-dev), see also #803

**Comment by lovell** [comment]
I've added a section to the docs about Alpine - see commit 29354ba
