### ISSUE TITLE
Switch pre-compiled libvips+dependencies binaries from Bintray to Github releases

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#851]
Bintray no longer provides a reliable enough service for people to depend upon, plus we're starting to breach the 1TB/month limit.

See #841

**Comment by neophob** [comment]
Thanks @lovell for sharp!

I wanted to use the prebuild binaries for arm7 (as the build time is pretty long on those machines) but i found that npm just compile the binaries anyway. 

so prebuild binaries are currently not working and will be fixed when this issue has been closed?

**Comment by lovell** [comment]
@neophob This task relates to moving the hosting provider for the existing prebuilt libvips and its dependencies, which includes ARMv7.

See #186 for the possible future enhancement to provide a prebuilt `sharp.node` for multiple platforms.

**Comment by lovell** [comment]
The packaging scripts and hosted binaries for libvips and its dependencies have moved to https://github.com/lovell/sharp-libvips/ and will be used from v0.19.0 onwards.

**Comment by lovell** [comment]
I've contacted Bintray customer support about the rate-limiting that's currently being applied.

**Comment by oliviertassinari** [comment]
I have been facing the same issue today. Have you considered using GitHub for hosting the binary?

**Comment by lovell** [comment]
@oliviertassinari Yes, hence the title of the issue you commented on ;)

**Comment by yvele** [comment]
For reference: Limit has been reached on 29 Sept https://github.com/lovell/sharp/issues/964 and is causing a lot of trouble

**Comment by haskellcamargo** [comment]
Same problem here. I'm unable get my Node project working because `yarn` fails on Bintray's error.
+1 for Github releases.

**Comment by clusteratlas** [comment]
This is frustrating as hell lol I thought the problem was on my end, turns out it's a 404 bintray error on `npm install sharp --save --verbose` haha

**Comment by chickahoona** [comment]
Im still hitting:
ERROR: Download of https://dl.bintray.com/lovell/sharp/libvips-8.5.5-linux-x64.tar.gz failed: Response code 404 (Not Found)

So sadly not solved for me :/

**Comment by lovell** [comment]
v0.19.0 now available.

**Comment by pronebird** [comment]
I have the same issue. i can't run on heroku anymore. The latest rebuild libvips i see is 8.5.x wtf...
