### ISSUE TITLE
How to do color manipulation?

### ISSUE THREAD

**Issue by RussellRC** [lovell/sharp#852]
Hi guys,

Is it possible to do image manipulation like brightening, darkening, contrast... or applying some function to the whole image on pixel by pixel basis?

Thanks,
Russell

**Comment by lovell** [comment]
Hello, did you see #609?

**Comment by Algae666** [comment]
I 2nd the request to expose libvips modulate functionality in sharp, definitely would make a useful addition.

**Comment by lovell** [comment]
@RussellRC Hopefully #609 will provide what you need, please feel free to re-open with more details if not.
