### ISSUE TITLE
How can i condition the max() or min() without breaking the chain

### ISSUE THREAD

**Issue by BogdanBucsa** [lovell/sharp#854]
Sharp(data.Body)
      .resize(imageWidth, imageHeight)
      (.max()<- this should be optional, for ex: if nocrop == true)
      .toFormat(imageFormat)
      .toBuffer()

**Comment by papandreou** [comment]
I think this is pretty much your only option:

```js
var sharpInstance = Sharp(data.Body)
  .resize(imageWidth, imageHeight);
if (nocrop) {
  sharpInstance = sharpInstance.max();
}
sharpInstance
  .toFormat(imageFormat)
  .toBuffer();
```

**Comment by lovell** [comment]
If it absolutely has to be a single chain then the following is untested but will probably work:
```javascript
Sharp(data.Body)
  .resize(imageWidth, imageHeight)
  [nocrop ? 'max' : 'crop']()
  .toFormat(imageFormat)
  .toBuffer()
```
...but please use @papandreou's suggestion for more easily maintained code :)
