### ISSUE TITLE
Is there a way to blend two images?

### ISSUE THREAD

**Issue by Andriy-Kulak** [lovell/sharp#859]
I would like to blend two images using a percentage (let's say 30% of image 1 and 70% of image 2). They will be exact same size. Is this possible to do with sharp package? I was not able to find much about this in documentation.

Thanks!

**Comment by lovell** [comment]
Hello, assuming neither has a transparency (e.g. both JPEG) then this should be possible. Try something like the following (untested), which adds a transparency to the first image then composites this over the second image.

```javascript
const { width, height } = await sharp.metadata(image1);

const thirtyPercentGrey = Math.round(0.30 * 255);
const thirtyPercentTransparency = Buffer.alloc(width * height, thirtyPercentGrey);

const image1WithThirtyPercentTransparency = await sharp(image1)
  .joinChannel(
    thirtyPercentTransparency,
    { raw: { width, height, channels: 1 } }
  )
  .raw()
  .toBuffer();

const result = await sharp(image2)
  .overlayWith(
    image1WithThirtyPercentTransparency,
    { raw: { width, height, channels: 4 } }
  )
  .toBuffer();
```

**Comment by lovell** [comment]
@Andriy-Kulak Hope this answered you question.
