### ISSUE TITLE
Error: /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /some_path/my_project/node_modules/sharp/build/Release/../../vendor/lib/libpng16.so.16)

### ISSUE THREAD

**Issue by purepear** [lovell/sharp#860]
So... it was working... the server is CentOS... i'm working with nvm, pm2 and i know i got it running last time. Because of how all of that was installed(nvm, pm2) i had to switch users and `nvm use X`.. but it worked!! ... i remember i had to install sharp again(i think this is sth to do with another C/C++ compiled module - uws)... now no matter with what user(root, myUser) i `npm install` and run it i have this error^...any suggestions?

**Comment by lovell** [comment]
Please see #843

**Comment by purepear** [comment]
Thank you @lovell ... i put `require('sharp')` on the first line of the app and the error was gone :)

**Comment by elliotthill** [comment]
I'm getting this error and putting the require on the first line of the app is not a good solution for me. I only have one specific API endpoint that needs this.

I don't have electron, node-canvas or any other image libraries being required.

Its looking for 1.2.9:
`Error: /lib64/libz.so.1: version `ZLIB_1.2.9' not found`

But 1.2.7 seems to be the one installed:

`node -e "console.log(process.versions.zlib)"
1.2.7
`

Any ideas?

**Comment by lovell** [comment]
@elliotthill Please see #892
