### ISSUE TITLE
Installation failed on Dreamhost VPS, Ubuntu 12.04, gcc 4.6

### ISSUE THREAD

**Issue by T-Specht** [lovell/sharp#862]
Sharp could not be installed successfully on my dreamhost VPS. Is there anything wrong with my configuration?
`npm i sharp --verbose` output is included in 
[npm-debug.txt](https://github.com/lovell/sharp/files/1109952/npm-debug.txt) file.

**Comment by lovell** [comment]
Hello, are the prerequisites, especially the C++11 compiler requirements, in place?
http://sharp.dimens.io/en/stable/install/#prerequisites

https://www.dreamhost.com/hosting/vps/ suggests Ubuntu 12.04, which provides gcc v4.6 and therefore doesn't meet the v4.8+ requirement.

**Comment by T-Specht** [comment]
Ok, that's true,  I have a version of gcc below 4.8. Is there anything besides updating that I can do? Because updating isn't really an option without root access to the VPS which Dreamhost does not provide.

**Comment by lovell** [comment]
https://www.dreamhost.com/cloud/ ?
