### ISSUE TITLE
Is there a way to stop current queued tasks?

### ISSUE THREAD

**Issue by rylphs** [lovell/sharp#863]
Hello! I am coding an application that reads a selected folder, generates image thumbnails from all images in that folder and show them as soon as they are generated, using resize function. When user selects another folder I need to stop all queued resizes and start new ones on the selected folder. Is there a way to do that?

Thanks!

**Comment by lovell** [comment]
Hello, you'll need to implement your own flow control that ensures only 4 images are "in-flight" at a time (or whatever the value of `process.env.UV_THREADPOOL_SIZE` is - see http://sharp.dimens.io/en/stable/api-utility/#concurrency). Something like [async.eachLimit](http://caolan.github.io/async/docs.html#eachLimit) might help.

**Comment by rylphs** [comment]
Let me see if I understood. You sugestion is to use async to start resize asynchrounous? Isn't there a problem in using async to control another async function? Thank you for your quick reply.

**Comment by lovell** [comment]
Here's a quick (untested) example. Set `cancelled` to `true` to cancel the queued resize operations.

```javascript
const async = require('async');

const images = [ image1, image2, image3, image4, image5, image6, ... ];
const concurrency = process.env.UV_THREADPOOL_SIZE || 4;

let cancelled = false;

async.eachLimit(images, concurrency, (image, done) => {
  sharp(image)
    .resize(200)
    .toBuffer((err, data, info) => {
      if (err) {
        done(err);
      } else if (cancelled) {
        done(new Error('Operation cancelled');
      } else {
        // do something with data/info
        done();
      }
    }
}, (err) => {
  console.log(err);
});

// further logic that can set cancelled to true
```

**Comment by rylphs** [comment]
Thanks lovell! It worked like a charm. I'll close the issue.
