### ISSUE TITLE
[question] concating images

### ISSUE THREAD

**Issue by Bnaya** [lovell/sharp#864]
Lets say i have 4 100X100 images
And i want to concat them for a 100X400 image.

I've tired to do this:
```js
    const fullScreenshotSharp = sharp(Buffer.from([]), <any>{
        create: {
            width: 100,
            height: 400,
            channels: 4,
            background: "rgba(0, 0, 0, 0)",
        }
    }); 
```
And then 
```js
        fullScreenshotSharp.overlayWith(screenshotFragmentBuffer, {
            top: i,
            left: 0,
        });
```
For each image with the appropriate `i`
But in each tick the rest of the image is covered with the ` background: "rgba(0, 0, 0, 0)"`
deleting my previous work

Thanks!

*EDIT*
What i did for now is to recreate sharp object on each iteration from the output of the last one.
```
        fullScreenshotSharp = await sharp(await fullScreenshotSharp.toBuffer());
```

I hope there's a better way

**Comment by lovell** [comment]
#728 is tracking a possible future enhancement that will make this easier. #699 is also relevant here.

**Comment by joemanfoo** [comment]
I use the `extend` (1) method for enlarging the output image with appended images by `overlayWith` (2)


1) [http://sharp.dimens.io/en/stable/api-operation/#extend](http://sharp.dimens.io/en/stable/api-operation/#extend)
2) [http://sharp.dimens.io/en/stable/api-composite/#overlaywith](http://sharp.dimens.io/en/stable/api-composite/#overlaywithl)

**Comment by lovell** [comment]
@Bnaya Hope this answered your question. Please subscribe to the linked issues for updates should you be interested.

**Comment by Bnaya** [comment]
Will do, thanks
