### ISSUE TITLE
TypeError: Buffer.alloc is not a function on install

### ISSUE THREAD

**Issue by molipha** [lovell/sharp#865]
Hi,

I had sharp working awesome then tried another install in another directory which choked. So I upgraded npm and nodejs but same result. Below is the output from the install script. (One thing that's weird is the output shows node -v 4.2.4 but I thought it was now called nodejs which is nodejs -v 8.1.3)
Any ideas?

sharp@0.18.2 install /home/michael/Staging/node_modules/sharp
> node-gyp rebuild

/home/michael/Staging/node_modules/tar/lib/pack.js:32
const EOF = Buffer.alloc(1024)
                   ^

TypeError: Buffer.alloc is not a function
    at Object.<anonymous> (/home/michael/Staging/node_modules/tar/lib/pack.js:32:20)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/michael/Staging/node_modules/tar/lib/create.js:6:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
gyp: Call to 'GLOBAL_VIPS_VERSION="" node -e "require('./binding').use_global_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-83-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/michael/Staging/node_modules/sharp
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/michael/Staging/package.json'
npm WARN Staging No description
npm WARN Staging No repository field.
npm WARN Staging No README data
npm WARN Staging No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.18.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.18.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/michael/.npm/_logs/2017-07-05T22_17_06_278Z-debug.log

**Comment by molipha** [comment]
Rebooted, researched, rejigged and now it works.

**Comment by raghavgarg1257** [comment]
@molipha , can you please explain the points, `researched`, `rejigged`. I am stuck at this error for a while now.

**Comment by lovell** [comment]
@raghavgarg1257 Node 4.5.0+ is required for `Buffer.alloc`.
