### ISSUE TITLE
Retrieve coordinates from Entropy and Attention crop

### ISSUE THREAD

**Issue by mirohristov-com** [lovell/sharp#868]
Is there a way to get  the coordinates used for the `sharp.strategy.entropy` or `sharp.strategy.attention` crop? 

I want to be able to store the crop data to database as `x,y,width,height` so that I can generate a cropbox on the front-end to match the already cropped thumbnail when users try to manually adjust it crop. Right now I'm placing the cropbox in the center which is confusing because it doesn't match the current thumbnail. Here's what I want the cropbox to look like: (matching the entropy-based thumbnail)
![2017-07-09_221622](https://user-images.githubusercontent.com/7188826/28000593-a05bffda-64f4-11e7-8f2b-45ba3378dae6.jpg)

**Comment by lovell** [comment]
Hello, this was previously available (up to v0.17.x) in undocumented/unsupported properties in the `info` part of the output.

To provide this in a supported manner we'd need to expose the results from libvips' `smartcrop` operation (which used and improved upon some of the original sharp logic of the same name).

**Comment by lovell** [comment]
This will be in v0.19.0 - https://github.com/lovell/sharp/blob/suit/lib/output.js#L19

**Comment by homerjam** [comment]
Hey @lovell will `cropOffsetLeft` / `cropOffsetTop` be available using `toBuffer()` method?

Looking forward to v0.19.0!

**Comment by lovell** [comment]
@homerjam Yes, I've updated the docs in commit 7067bed to make this clearer.

**Comment by lovell** [comment]
sharp v0.19.0 now available.
