### ISSUE TITLE
Background alpha option

### ISSUE THREAD

**Issue by Electriccc** [lovell/sharp#869]
Hi, i have one question...
When i upload an image i need to make some thumbnails... If i upload an image that already has transparent background, no matter my "`.background({ r: 0, g: 0, b: 0, alpha: 0 })`" code, sharp sets the background to color black, but if i upload normal picture it will set it to transparent.
So my question is.. Is that a bug or am i doing something wrong ?
This is the whole sharp code...

```
var image = Sharp(source)
 image.rotate()
        .resize(width, height)
        .withoutEnlargement()
        .crop(Sharp.strategy.center)
        .background({ r: 0, g: 0, b: 0, alpha: 0 })
        .flatten()
        .jpeg()
        .toFile(dest)
```

**Comment by lovell** [comment]
Hello, perhaps you meant to use `alpha: 1` instead of `alpha: 0`?

> "The alpha value is a float between 0 (transparent) and 1 (opaque)."

http://sharp.dimens.io/en/stable/api-colour/#background

**Comment by lovell** [comment]
@Electriccc Were you able to make progress with this?

**Comment by Electriccc** [comment]
Yea i solved it, problem was that jpeg pictures doesnt support background
transparent i meeded to convert to .png

**Comment by eugenesaenko** [comment]
I have the same bug.
I do thumbnails too, and when I have png input files It misses their transparency and background sets to black.

```
const instance = sharp().resize(1440, null);
const png = instance
   .flatten(true)
   .embed()
   .background({r:255, b:255, g:255, alpha:0})
   .png({progressive: true});
const jpeg = instance.jpeg({progressive: true});
const ext = mime.getExtension(this.bodyMimeType);
const stream$ = ext === "jpeg" || ext === "jpg"
    ? jpeg
    : png;
```

**Comment by eugenesaenko** [comment]
The problem in `.png();`. It just ignores an input's alpha channel.

**Comment by eugenesaenko** [comment]
Okay, I solved this. The problem was that image was resized before calling `.embed()`.

**Comment by SephReed** [comment]
Could somebody please show me how to resize and image without making the background black?

**Comment by SephReed** [comment]
I figured it out.  There was a .png image saved with .jpg ending.
