### ISSUE TITLE
Enhancement: default to adaptiveFiltering=false for PNG output

### ISSUE THREAD

**Issue by wmertens** [lovell/sharp#872]
When I make a thumbnail from a certain PNG image, it is 6KB. Google PageSpeed then says it's too big, and creates a 4KB image with the same canvas size and seemingly same pixels.

I used compression level 9, I don't include image metadata, I can't see anything obvious when looking at the hex dump.

Thoughts?

This is the 6KB image:
![ikea thumb](https://user-images.githubusercontent.com/54934/28413734-01d90904-6d49-11e7-9c0b-36096aad99dd.png)
And Google's 4KB version:
![ikea](https://user-images.githubusercontent.com/54934/28413763-11fafb80-6d49-11e7-87e1-f7b0c90094b9.png)

**Comment by lovell** [comment]
Hello, turning off the [adaptiveFiltering](http://sharp.dimens.io/en/stable/api-output/#png) option will help for this image. The smaller PNG file may be using an indexed palette, unsupported by libvips. See also #478, #600, #739.

**Comment by wmertens** [comment]
Right, that must be it. Hmm, would it be possible/easy to use another lib
for PNG output only?

Also, how about an "adaptiveFiltering: 'auto'" setting to compress with and
without and keep the shortest result? I don't mind the extra CPU time as
much as I mind the extra bytes…

**Comment by lovell** [comment]
The most common use of PNG is for line art, diagrams and logos for which `adaptiveFiltering: false` usually produces the smallest file. Perhaps simply making it the default (rather than `true`) would offer the simplest approach here?

**Comment by wmertens** [comment]
Sounds good!

**Comment by lovell** [comment]
PNG output will default to adaptiveFiltering=false, compressionLevel=9 from v0.19.0.

(Added in commit da3a598, although this SHA may change after a possible future rebase.)

**Comment by lovell** [comment]
v0.19.0 now available.
