### ISSUE TITLE
Cannot build for FreeBSD 11, _LIBCPP_TRIVIAL_PAIR_COPY_CTOR is no longer supported

### ISSUE THREAD

**Issue by rterbush** [lovell/sharp#873]
I've attempted to install sharp on FreeBSD 11. Build using node-gyp is producing the following error:
```
gmake: Entering directory '/home/randy/Develop/tkg/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc: In function 'std::tuple<vips::VImage, sharp::ImageType> sharp::OpenInput(sharp::InputDescriptor*, VipsAccess)':
../src/common.cc:225:38: error: 'to_string' is not a member of 'std'
               option->set("density", std::to_string(descriptor->density).data());
                                      ^
../src/common.cc:262:38: error: 'to_string' is not a member of 'std'
               option->set("density", std::to_string(descriptor->density).data());
                                      ^
gmake: *** [sharp.target.mk:151: Release/obj.target/sharp/src/common.o] Error 1
gmake: Leaving directory '/home/randy/Develop/tkg/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System FreeBSD 11.1-BETA3
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
```

I've tried compiling with clang39, clang40, gcc48 and gcc5. The error above is the output from the gcc compiles.

**Comment by rterbush** [comment]
I'll also offer the following link that shows the solution that was used for the chromium port to FreeBSD.

https://bugs.freebsd.org/bugzilla/attachment.cgi?id=177658&action=diff

**Comment by lovell** [comment]
Hello, I'm not a FreeBSD user. Based on the Chromium bug report, am I right in thinking FreeBSD needs `_LIBCPP_ABI_UNSTABLE=1` and `_LIBCPP_TRIVIAL_PAIR_COPY_CTOR=1` defined for C++11 support? If so, that should be easy to add. Are you able to help test?

**Comment by rterbush** [comment]
@lovell Happy to test. Your read of those changes seem to be what is necessary. I tried in vane to set those values in my compile environment but either these values are not enough, or the environment was not getting passed properly to node-gyp.

**Comment by lovell** [comment]
I've investigated this a little further. How was libvips installed on this machine? My best guess would be that it was compiled with `_LIBCPP_ABI_UNSTABLE=1` defined, or perhaps with a specific `_LIBCPP_ABI_VERSION=?` value.

I suspect we need a way to determine the value of this compile-time value for FreeBSD in a similar manner to [that used for Linux gcc](https://github.com/lovell/sharp/blob/master/binding.gyp#L109-L110). I fear setting it for all *BSD users will break some installations.

**Comment by rterbush** [comment]
`_cxx11` is not present in the libvips-cpp.so as shown below.

```
 readelf -Ws /usr/local/lib/libvips-cpp.so | c++filt  | grep -F __c
    16: 0000000000000000   245 FUNC    GLOBAL DEFAULT  UND __cxa_begin_catch@CXXABI_1.3 (4)
    17: 0000000000000000   507 FUNC    WEAK   DEFAULT  UND __cxa_finalize@FBSD_1.0 (3)
    20: 0000000000000000    19 FUNC    GLOBAL DEFAULT  UND __cxa_allocate_exception@CXXABI_1.3 (4)
    34: 0000000000000000    72 OBJECT  GLOBAL DEFAULT  UND vtable for __cxxabiv1::__class_type_info@CXXABI_1.3 (4)
    35: 0000000000000000    85 FUNC    GLOBAL DEFAULT  UND __cxa_free_exception@CXXABI_1.3 (4)
    63: 0000000000000000    45 FUNC    GLOBAL DEFAULT  UND __cxa_call_unexpected@CXXABI_1.3 (4)
    64: 0000000000000000    72 OBJECT  GLOBAL DEFAULT  UND vtable for __cxxabiv1::__si_class_type_info@CXXABI_1.3 (4)
    82: 0000000000000000   297 FUNC    GLOBAL DEFAULT  UND __cxa_end_catch@CXXABI_1.3 (4)
    85: 0000000000000000   250 FUNC    GLOBAL DEFAULT  UND __cxa_throw@CXXABI_1.3 (4)
```
I've tried unsetting `_GLIBCXX_USE_CXX11_ABI=` but that is either not getting passed in the environment, or is not enough. Let me know if there is anything else I can test.

**Comment by lovell** [comment]
How was libvips installed on this machine?

**Comment by rterbush** [comment]
vips is compiled and installed through the ports mechanisms. There is no reference in any of that build process to these environment variables.

**Comment by lovell** [comment]
Great, thanks. https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=193528 appears to be very relevant to the gcc48 and gcc5 problem you report. Are you able to try gcc6 to see if it works?

**Comment by rterbush** [comment]
Good catch on that bug.

I can confirm that setting CXXFLAGS=-D_GLIBCXX_USE_C99 fixes the problem for a gcc49 build.

I've kicked off a build for gcc6 to see if that also solves the problem, but I think that gcc6 is a bit far forward for most systems and setting the CXXFLAGS might be a bit more portable. I'll report back the results for the results using gcc6.

**Comment by rterbush** [comment]
Confirmed that gcc6 also solves this problem.

**Comment by lovell** [comment]
Thank you, that's the gcc problem understood.

What was the compilation error from clang39 and clang40?

**Comment by rterbush** [comment]
The error when compiling with default clang is as follows:
```
gmake: Entering directory '/home/randy/Develop/tkg/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
In file included from ../src/common.cc:15:
In file included from /usr/include/c++/v1/cstdlib:85:
/usr/include/c++/v1/__config:73:2: error: "_LIBCPP_TRIVIAL_PAIR_COPY_CTOR" is no longer supported.        use _LIBCPP_DEPRECATED_ABI_DISABLE_PAIR_TRIVIAL_COPY_CTOR instead
#error "_LIBCPP_TRIVIAL_PAIR_COPY_CTOR" is no longer supported. \
 ^
1 error generated.
gmake: *** [sharp.target.mk:151: Release/obj.target/sharp/src/common.o] Error 1
```

This issue is reflected back in the original message and the link provided to the chromium bug. Trying to pass a a few defines to the compile process but it is not solving the problem.

**Comment by rterbush** [comment]
@lovell After doing a bit more digging, it appears that this is a problem with node-gyp. It is node-gyp that is adding the compile flag for -D_LIBCPP_TRIVIAL_PAIR_COPY_CTOR=1

Here is a link from the node-gyp files that explains the addition of that flag if you are interested. I'll find a way to report this for node-gyp.
https://lists.freebsd.org/pipermail/freebsd-toolchain/2016-March/002094.html

**Comment by rterbush** [comment]
I've confirmed this is a bug in the FreeBSD ports for the www/node package. I've reported the bug here:  https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220983

I'll leave this issue open in case you want to use it to track the changes for gcc. @lovell Thanks for working through this with me.

**Comment by lovell** [comment]
I've documented the gcc v4/v5 workaround in 6b34e8a. Let's leave this open for a while in case others run into the same problem with the upstream `www/node` ports. Thanks for reporting this and providing help to debug/understand the problem.

**Comment by tankakatan** [comment]
Great support, thank you!
