### ISSUE TITLE
Can't install sharp on Amazon Linux AMI

### ISSUE THREAD

**Issue by kiran-redhat** [lovell/sharp#879]
Unable to install sharp on Amazon Linux AMI (4.9.17-8.31.amzn1.x86_64) related release notes:
https://aws.amazon.com/amazon-linux-ami/2017.03-release-notes/.

More info:
4497 verbose about to build /home/myusername/BackstopJS/node_modules/sharp
4498 info build /home/myusername/BackstopJS/node_modules/sharp
4499 info linkStuff sharp@0.18.2
4500 silly linkStuff sharp@0.18.2 has /home/myusername/BackstopJS/node_modules as its parent node_modules
4501 verbose linkBins sharp@0.18.2
4502 verbose linkMans sharp@0.18.2
4503 verbose rebuildBundles sharp@0.18.2
4504 verbose rebuildBundles [ '.bin', 'caw', 'color', 'got', 'nan', 'semver', 'tar' ]
4505 info install sharp@0.18.2
4506 verbose unsafe-perm in lifecycle true
4507 info sharp@0.18.2 Failed to exec install script
4508 verbose unlock done using /home/myusername/.npm/_locks/sharp-724c992e50a0ae1d.lock for /home/myusername/BackstopJS/node_modules/sharp
4509 verbose stack Error: sharp@0.18.2 install: `node-gyp rebuild`
4509 verbose stack Exit status 1
4509 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
4509 verbose stack     at emitTwo (events.js:87:13)
4509 verbose stack     at EventEmitter.emit (events.js:172:7)
4509 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
4509 verbose stack     at emitTwo (events.js:87:13)
4509 verbose stack     at ChildProcess.emit (events.js:172:7)
4509 verbose stack     at maybeClose (internal/child_process.js:862:16)
4509 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
4510 verbose pkgid sharp@0.18.2
4511 verbose cwd /home/myusername/BackstopJS
4512 error Linux 4.9.17-8.31.amzn1.x86_64
4513 error argv "/usr/bin/node" "/usr/bin/npm" "install"
4514 error node v4.8.4
4515 error npm  v2.15.11
4516 error code ELIFECYCLE
4517 error sharp@0.18.2 install: `node-gyp rebuild`
4517 error Exit status 1
4518 error Failed at the sharp@0.18.2 install script 'node-gyp rebuild'.
4518 error This is most likely a problem with the sharp package,
4518 error not with npm itself.
4518 error Tell the author that this fails on your system:

**Comment by lovell** [comment]
Hello, are all the [prerequisites](http://sharp.dimens.io/en/stable/install/#prerequisites) installed?

https://aws.amazon.com/amazon-linux-ami/2017.03-packages/

* gcc-4.8.3
* python27-2.7.12

**Comment by kiran-redhat** [comment]
Yes, I have below:
Python 2.7.12
gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9)
Node v4.8.4

**Comment by lovell** [comment]
Thank you.

It looks like the underlying error message is somehow being suppressed. I'll try running the latest Amazon AMI image with Docker to see if I can reproduce this locally.

In the meantime, are you able to try with a more recent versions of Node (and therefore node-gyp) to see if they provide more useful error output?

**Comment by lovell** [comment]
Here's what I used to get Node v4.8.4 installed on Amazon Linux 2017.03 and ready for use with native modules (tested via `docker run -it --rm amazonlinux:2017.03`):

```sh
curl --silent --location https://rpm.nodesource.com/setup_4.x | bash
yum install -y gcc-c++ nodejs
npm install sharp
```
Perhaps `gcc-c++`, a `node-gyp` requirement, is the missing information here.

**Comment by kiran-redhat** [comment]
Hey @lovell , thank you for having a look. Looks like Amazon Linux AMI doesn't have gcc-c++, sharp install fine after 'sudo yum install gcc-c++'.

Closing issue.

**Comment by klemensz** [comment]
For anybody having problems with `node-gyp rebuild` failing with sharp on subsequent `npm install`s on Elastic Beanstalk and Amazon Linux, take a look at this issue: https://github.com/tomdale/fastboot-aws/issues/4#issuecomment-272497834
