### ISSUE TITLE
toBuffer with streams

### ISSUE THREAD

**Issue by lindskog** [lovell/sharp#881]
Hi! I want to resize an image and then write the output to a Buffer using sharp, where my input is a stream,  but I cannot get it to work. What is the best way to achieve this? I do not want to save the image anywhere, I just want to access the data in the buffer. The images I want to do this for are of type 'svg'. I have tried the following, but it does not seem to generate the correct data in the buffer:

```
function resizeImage(inputStream, width, height) {
  var resizeTransform = sharp().resize(width, height);
  return new Promise(function (resolve, reject) {
    inputStream.pipe(resizeTransform).toBuffer()
    .then(function(data) {
      console.log(data);
    })
    inputStream.on('end', resolve);
    inputStream.on('error', reject);
    resizeTransform.on('error', reject);
  });
}
```

**Comment by lovell** [comment]
Hello, there are some examples of Stream-based input with Buffer(-as-a-Promise) based output in the unit tests - see https://github.com/lovell/sharp/blob/d8765f955de2f037881da7487773ad02cea539cc/test/unit/io.js#L52-L89

Ignoring error handling on `inputStream`, your example might look something like:
```javascript
function resizeImage(inputStream, width, height) {
  var resizeTransform = sharp().resize(width, height);
  inputStream.pipe(resizeTransform);
  return resizeTransform.toBuffer();
}
```

**Comment by lindskog** [comment]
Hi! That helped, thank you very much!

**Comment by lindskog** [comment]
But I am not sure I understand what the buffer 'data' will contain. I read that it is supposed to be the output image data, but I seem to get the same data for every different image that I try. If I for example want to resize an image to be only one pixel, and I want access the RGB value for the colour of this pixel, how can I do this?

**Comment by lindskog** [comment]
I solved this by using the .raw() function!
