### ISSUE TITLE
Request: detect animated webp

### ISSUE THREAD

**Issue by ile** [lovell/sharp#882]
I would be useful to detect whether the .webp image is animated. 

It would, at least for me, change the way the image is processed. Normally I would just resize and output as jpeg, but for animated webp I would output to gif or webp.

Webp support isn't yet 100 % so I can't just output everything to webp, I have to select the ones I do...

**Comment by lovell** [comment]
Hello, this will require an addition to libvips to include the detection and exposure of frame count. In the meantime, perhaps use something like https://github.com/PeckZeg/animated-webp-info

**Comment by mooyoul** [comment]
I've released [node-webpinfo](https://github.com/mooyoul/node-webpinfo) for this usage. 
Also, this package does not requires any native addons or programs like libwebp. also this is WritableStream. so you can stream WebP data to get WebP information.

**Comment by lovell** [comment]
The number of frames in an animated WebP images is now made available in the `pages` property returned by `metadata()` thanks to https://github.com/lovell/sharp/issues/1205
