### ISSUE TITLE
Black line converting an SVG image

### ISSUE THREAD

**Issue by daviddelamo** [lovell/sharp#884]
Hello, I'm trying to use sharp to convert an SVG image to PNG (or any other format. The SVG I'm using have one text label defined in a "flowPara" tag and an background image. In SVG the image looks ok but when convert it to PNG a black line appears in the text position. Can this be a problem with my SVG?

My app can be tested in this direction https://hitoscreator.herokuapp.com/ only click the button to see the generated image.

The code is in github ( https://github.com/daviddelamo/hitoscreator ) the relevant classes are https://github.com/daviddelamo/hitoscreator/blob/master/public/pdf_templates/hoja_cultos_editable.svg and  https://github.com/daviddelamo/hitoscreator/blob/master/public/controller/svg.js

Hope you can help me, thanks in advance,
David.

**Comment by lovell** [comment]
Hello, this SVG was created by Inkscape, which attempts to use `flowRoot` from the draft SVG 1.2 standard and is therefore unsupported by librsvg.

**Comment by daviddelamo** [comment]
Hi! Where can I see wich SVG specification supports librsvg?. I've been looking the web and didn't found anything related.

**Comment by lovell** [comment]
https://www.w3.org/TR/SVG11/

**Comment by daviddelamo** [comment]
Thank you so much, selecting Text > Convert to text at Inskcape solves the issue and now is working.

Thanks again!
