### ISSUE TITLE
process.exit(0) after using sharp stream causes GLib-CRITICAL output

### ISSUE THREAD

**Issue by niftylettuce** [lovell/sharp#885]
Related to #418 and #409, I am using `aws-sdk` (Amazon's SDK JavaScript library) at <https://github.com/aws/aws-sdk-js> to run a simple function that uploads a `sharp` transformed file.  Immediately after uploading the file I exit the process and receive the following output:

```js

const AWS = require('aws-sdk');
const sharp = require('sharp');
const zlib = require('zlib');

const s3 = new AWS.S3({
  // ... 
});

const obj = {
  // ...
};

obj.Body = sharp('/path/to/myfile.jpg')
  .resize(100, null)
  .pipe(zlib.createGzip())
  .on('error', err => {
    throw err;
  });

await s3.upload(obj).promise();

process.exit(0);
```

```log
(sharp:30931): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:30931): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:30931): GLib-CRITICAL **: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed

(sharp:30931): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed
[1]    30931 segmentation fault  node test.js
```

**Comment by niftylettuce** [comment]
Also, if I do not put in `process.exit(0)` then there is no output for what it's worth...  This leads me to believe a stream isn't closed or something?

**Comment by lovell** [comment]
Hello, perhaps you intended to pass gzip's `ReadableStream` output to S3?
```javascript
obj.Body = zlib.createGzip();
sharp('/path/to/myfile.jpg')
  .resize(100, null)
  .pipe(obj.Body);
```

**Comment by niftylettuce** [comment]
It works how it is now though...

**Comment by lovell** [comment]
Yes, not sure quite what's happening here. Perhaps attach error handler to the sharp Stream (as well as the gzip Stream) to see if there's an error on the input side?
```javascript
obj.Body = sharp('/path/to/myfile.jpg')
  .resize(100, null)
  .on('error', err => console.log(`${err.message} from sharp`))
  .pipe(zlib.createGzip())
  .on('error', err => console.log(`${err.message} from gzip`));
```
(As an aside, JPEG images generally reduce in size very little via gzip compression, occasionally increasing in size, so this step may not be required.)

**Comment by niftylettuce** [comment]
Doesn't occur anymore - not sure what was up 🤦‍♂️

**Comment by lovell** [comment]
The AWS docs suggest its `promise()` method rejects using a second function parameter, rather than via catch, so perhaps async/await stuff won't work here? http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3/ManagedUpload.html#promise-property
