### ISSUE TITLE
Append images (vertically or horizontally)

### ISSUE THREAD

**Issue by HoneyryderChuck** [lovell/sharp#886]
I'm looking for a way to "join" images together, in this case horizontally. I can't seem to find an API in sharp which supports, although I've seen that libvips (the library underneath) [supports this functionality](https://stackoverflow.com/questions/31389451/appending-images-with-node-sharp-libvips). As I can't use neither ruby nor python, the link is useless to me. 

Is there a way?

**Comment by lovell** [comment]
Please see #699, #728, #864.

**Comment by HoneyryderChuck** [comment]
I've managed to make it work with successive calls to extend and  overlayWith. In hindsight, I have to say that I don't like the mess I've made of this await promise loop soup much. But judging by the other tickets, I guess you're working on the issue already. 

I'll close the ticket. Thx for the support.
