### ISSUE TITLE
Lambda giving error: Input file is missing or of an unsupported image format

### ISSUE THREAD

**Issue by JeffPlummer** [lovell/sharp#889]
I am having a bit of trouble getting sharp working on lambda.

My Setup:
Rather than your instructions using an EC2 instance to deploy to lambda, I've built a docker container (FROM amazonlinux) that builds my project with lambda compatible dependencies.  Seems to deploy and I'm not getting any bad library errors, so thinking the installation to lambda is fine.

My Code:
My node project uses "multer" (https://www.npmjs.com/package/multer) to receive a file, write it to "/tmp", and then calls the code shown below to convert the uploaded image file.  

Updates 1:
If I include a test.png in the project, i can use sharp on that file in the local directory on lambda without errors.  It is only the files uploaded to /tmp on lambda that are failing.  I don't think it is anything wacky with /tmp, because it still works if I copy the test.png to /tmp, and run sharp on /tmp/test.png.  

Updates 2:
I'm uploading the same file as the test file, and I would expect the 2 files to have the same hash.  and they don't.  So something is happening with the upload that is changing the file.  However, when I run the code locally, uploading to localhost, the hashes are the same.

```javascript
export class ConvertToZoomableService {

  public convertUploadedFile(fileInfo: UploadedFile): Promise<void> {
    console.log("Attempting conversion of file: " + fileInfo.path);
    console.log(sharp.format);
    console.log(sharp.versions);

    return new Promise<void>((resolve, reject) => {
      sharp(fileInfo.path)
        .png()
        .tile()
        .toFile('/tmp/' + fileInfo.originalname+'_'+fileInfo.filename+'.dz', function(err, info) {
          console.log(info);
          console.log(err);
          resolve();
        })
    })
  }
}
```

When the program runs I get a "Error: Input file is missing or of an unsupported image format".  Digging through the issues related to this error, I don't see anything that matches my problem.  My installed library seems to support png, and the versions seem ok.  I've also written some test code (not shown), that confirms the file is being uploaded and is in the "/tmp" directory by the time this code runs.

If I run the node project locally, it works fine.  Any ideas?

Thanks,
Jeff

Sharp.format results:
```
{ jpeg: 
{ id: 'jpeg',
input: { file: true, buffer: true, stream: true },
output: { file: true, buffer: true, stream: true } },
png: 
{ id: 'png',
input: { file: true, buffer: true, stream: true },
output: { file: true, buffer: true, stream: true } },
webp: 
{ id: 'webp',
input: { file: true, buffer: true, stream: true },
output: { file: true, buffer: true, stream: true } },
tiff: 
{ id: 'tiff',
input: { file: true, buffer: true, stream: true },
output: { file: true, buffer: true, stream: true } },
magick: 
{ id: 'magick',
input: { file: false, buffer: false, stream: false },
output: { file: false, buffer: false, stream: false } },
openslide: 
{ id: 'openslide',
input: { file: false, buffer: false, stream: false },
output: { file: false, buffer: false, stream: false } },
dz: 
{ id: 'dz',
input: { file: false, buffer: false, stream: false },
output: { file: true, buffer: true, stream: true } },
ppm: 
{ id: 'ppm',
input: { file: false, buffer: false, stream: false },
output: { file: false, buffer: false, stream: false } },
fits: 
{ id: 'fits',
input: { file: false, buffer: false, stream: false },
output: { file: false, buffer: false, stream: false } },
gif: 
{ id: 'gif',
input: { file: true, buffer: true, stream: true },
output: { file: false, buffer: false, stream: false } },
svg: 
{ id: 'svg',
input: { file: true, buffer: true, stream: true },
output: { file: false, buffer: false, stream: false } },
pdf: 
{ id: 'pdf',
input: { file: false, buffer: false, stream: false },
output: { file: false, buffer: false, stream: false } },
v: 
{ id: 'v',
input: { file: false, buffer: false, stream: false },
output: { file: false, buffer: false, stream: false } },
raw: 
{ id: 'raw',
input: { file: false, buffer: true, stream: true },
output: { file: false, buffer: true, stream: true } } }
```

Versions:
```
{ cairo: '1.14.8',
croco: '0.6.12',
exif: '0.6.21',
expat: '2.2.0',
ffi: '3.2.1',
fontconfig: '2.12.1',
freetype: '2.8',
gdkpixbuf: '2.36.6',
gif: '5.1.4',
glib: '2.53.1',
gsf: '1.14.41',
harfbuzz: '1.4.6',
jpeg: '1.5.1',
lcms: '2.8-d168300',
orc: '0.4.26',
pango: '1.40.5',
pixman: '0.34.0',
png: '1.6.29',
svg: '2.40.17',
tiff: '4.0.7-85e569c',
vips: '8.5.5',
webp: '0.6.0',
xml: '2.9.4',
zlib: '1.2.11' }
```

Docker Script:
```
FROM amazonlinux

RUN curl --silent --location https://rpm.nodesource.com/setup_4.x | bash -
RUN yum -y install nodejs shadow-utils gcc-c++ node-gyp python make


ENV PATH="/usr/sbin:${PATH}"

RUN mkdir -p /Users/jeffplummer
RUN useradd jeffplummer -m -d /Users/jeffplummer
RUN chown -R jeffplummer /Users/jeffplummer

# Create app directory
RUN mkdir -p /usr/imagemapserver
RUN chown -R jeffplummer /usr/imagemapserver


WORKDIR /usr/imagemapserver


RUN npm install claudia -g
RUN npm install typings -g
RUN npm install -g typescript

# Bundle app source
COPY . /usr/imagemapserver
RUN rm -rf /usr/imagemapserver/node_modules
RUN rm -rf /usr/imagemapserver/.git



USER jeffplummer
RUN npm install --production

EXPOSE 3000
CMD [ "claudia", "update", "--keep", "--profile", "seoready" ]
```

**Comment by JeffPlummer** [comment]
More updates.  For testing I've included a test.png file in my deployment, and wrote an endpoint that has sharp get metadata from that test file... AND IT WORKS.

 So it looks like the library is fine, but the uploading of data is somehow not working, or somehow corrupting the data.

**Comment by JeffPlummer** [comment]
I figured it out, and will leave it here for the next person.

API Gateway **MUST** be configured to support binary files.  If not configured, it will convert the uploaded file to something else.

@lovell You may want to update your docs regarding lambda deployment that if they are using api gateway, they must configure it to support binary or they must base64 encode/decode on the client and server.  (Good article: https://aws.amazon.com/jp/blogs/compute/binary-support-for-api-integrations-with-amazon-api-gateway/).  

Also note, your docs say that you must use node 4 when doing lambda.  I'm currently using 6 (the only other version supported by lambda) and it works just fine.

Regards,
Jeff

**Comment by lovell** [comment]
Glad to hear you got it working. Feel free to submit a PR to update and improve the [install docs](https://github.com/lovell/sharp/blob/master/docs/install.md).

**Comment by JeffPlummer** [comment]
Will do.  I'll add some changes to the docs and submit a PR early next week.
