### ISSUE TITLE
Error while running npm install sharp on Ubuntu 16.04

### ISSUE THREAD

**Issue by joaobelo92** [lovell/sharp#891]
Hi, I'm unable to install sharp on my production server because of the following errors. 
Any insight would be appreciated.

> sharp@0.18.1 install /home/joao/maria-evangelista-v2/node_modules/sharp
> node-gyp rebuild

make: Entering directory '/home/joao/maria-evangelista-v2/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
sharp.target.mk:119: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: *** [Release/obj.target/sharp/src/common.o] Error 4
make: Leaving directory '/home/joao/maria-evangelista-v2/node_modules/sharp/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-87-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/joao/maria-evangelista-v2/node_modules/sharp
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.18.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.18.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-29T23_42_46_778Z-debug.log

Thanks!

**Comment by joaobelo92** [comment]
Figured it out. 
Looks like 512mb of ram is not enough.

**Comment by thatguypark** [comment]
Same issue here on Mac Sierra.  (node@10.12.1, sharp@0.21.0)
Seems mine was also a memory issue.

Ran `sudo purge`, then ran `npm install sharp` again and it worked like a treat.
