### ISSUE TITLE
Unnecessary expected fixtures (dHash and transparency)

### ISSUE THREAD

**Issue by kleisauke** [lovell/sharp#893]
Not a serious bug, but I thought I'd just mention it.

Some of the expected fixtures can be replaced with a full black image, which makes them unnecessary:
[crop-strategy.png](https://github.com/lovell/sharp/blob/e0d622d347590ce183c0ac848d2a333cda5f238f/test/fixtures/expected/crop-strategy.png)
[embed-4-into-4.png](https://github.com/lovell/sharp/blob/e0d622d347590ce183c0ac848d2a333cda5f238f/test/fixtures/expected/embed-4-into-4.png)
[sharpen-rgba.png](https://github.com/lovell/sharp/blob/e0d622d347590ce183c0ac848d2a333cda5f238f/test/fixtures/expected/sharpen-rgba.png)
[threshold-128-transparency.png](https://github.com/lovell/sharp/blob/e0d622d347590ce183c0ac848d2a333cda5f238f/test/fixtures/expected/threshold-128-transparency.png)

When converting the image to a 9x8 greyscale image (for calculating the dHash) the transparency gets lost and becomes black. These fixtures only contains black text which causes that the dHash is equal to `0000000000000000` (which is the same as a full black image). 

To fix this we can flatten the transparency to a white background before greyscaling or change the text to a white color.

**Comment by lovell** [comment]
Thanks, good spot Kleis. As you say, should be a quick fix to improve the quality of the tests. Happy to accept a PR if you have the time, otherwise will do so before the next release.

**Comment by lovell** [comment]
Commit 11daa3b flattens the images to compare using mid-grey `#808080` before calculating the  fingerprint; all the tests still pass!
