### ISSUE TITLE
 question, resize image without to save locally

### ISSUE THREAD

**Issue by fedorovmichael** [lovell/sharp#895]
Hi,
It not issue, I have question, how can I resize image without to save locally and then to save it.
when I run bellow code, I get error: Error: Input buffer contains unsupported image format 
code:
var fs = require('fs');
var request = require('request');
var sharp = require('sharp');

function getImage()
{
   request('https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png', function (err, res, body) {     

    var binary = Buffer.from(body.toString(), 'base64');   

    sharp(binary).resize(198, 110).toFile('test.jpg', (err, info ) => 
      { 
          console.log('err: ', err);
          console.log('info: ', info);

      });      
  });
}

**Comment by lovell** [comment]
Hello, I don't quite follow the base64 part of this example, which is probably what's causing the "unsupported image format" error.

When using `request` you should be able to stream binary data directly, something like (untested):

```javascript
function getImage() {
  var resizer = sharp().resize(198, 110).toFile('test.jpg', (err, info) => { 
    console.log('err: ', err);
    console.log('info: ', info);
  });    
  request('https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png').pipe(resizer);
}
```

**Comment by fedorovmichael** [comment]
Hello,
Thank you very much, for your quick answer, works perfect.
