### ISSUE TITLE
any way to turn a readable stream into a byte array?

### ISSUE THREAD

**Issue by tL4302** [lovell/sharp#896]
Hi,
More a question than an issue - I was using sharp successfully to convert a .jpg into a buffer to feed into a facial recognition app (just using .toBuffer()). Now, instead of using .jpg images, I need to get this working when the input is a Readable stream. Is there any easy way to convert a readable stream to a buffer/byte array? I'm able to use .metadata() to read the stream's metadata, but haven't had any luck turning it into a byte array. Can you let me know if there is an easy way around this?

Thanks in advance,
Tina

**Comment by lovell** [comment]
Hello, are you able to provide a little more information about the desired input and output formats (e.g. JPEG, raw pixel data etc.) or, even better, some code samples to help demonstrate what you'd like to achieve. Perhaps start with an example of code that used "sharp successfully to convert a .jpg into a buffer".

**Comment by tL4302** [comment]
Sure - this was how I was converting a JPG to a buffer using sharp:

```javascript
sharp(imgFile).toBuffer().then(function(bufferdata) { 
     rekognition.detectFaces(params, function(err, bufferdata) { ... }
}
```

However, now instead of providing sharp with a .jpg file as input, we are providing a readable stream, which needs to be converted to a buffer, because the detectFaces function requires a buffer/byte array as argument. 

We ended up just converting the stream to buffer in node/js, then feeding that to the detectFaces() function. Just wondering if there was a way to convert the readable stream into a buffer within sharp.

**Comment by lovell** [comment]
Is this code using any of the image processing features of sharp? If not, your example could use `fs` directly and remove an unnecessary JPEG decode/encode roundtrip.

```javascript
const params = {
  Image: {
    Bytes: fs.readFileSync(imgFile)
  }
};
rekognition.detectFaces(params, function(err, data) { ... });
```
For Stream to Buffer conversion, perhaps then try something like https://github.com/stream-utils/stream-to-array (again assuming no image processing is taking place beyond JPEG decode/encode).
