### ISSUE TITLE
Pass location of GraphicsMagick into Sharp?

### ISSUE THREAD

**Issue by atwright147** [lovell/sharp#899]
Is there any way to tell Sharp where GraphicsMagick is installed?

I ask because I am looking to create a NPM package to install GraphicsMagick (it will be based on the way https://github.com/eugeneware/ffmpeg-static functions).

I would like to be able to pass a path to the binary into Sharp on initialisation and have libvips use that binary.

**Comment by lovell** [comment]
Hello, you'll need to globally install libvips from source, telling it where GraphicsMagick is, then (re)install sharp to use that global installation of libvips.

http://jcupitt.github.io/libvips/install.html#building-libvips-from-a-source-tarball

**Comment by lovell** [comment]
sharp, libvips and its dependencies all operate as shared libraries in the same process as node. It sounds like you're looking for something that will spawn a new process, so you may be using the wrong tool for the job.
