### ISSUE TITLE
File creation time stays the same on Windows for at least JPEG format

### ISSUE THREAD

**Issue by dlong500** [lovell/sharp#901]
I have a Windows 7 x64 machine, and if I use `toFile` to output a JPEG that already exists it _does_ overwrite the file but it leaves the modification date the same (which is very confusing).

However, if I am outputting a dz tile format using a compressed zip file the modification time does get updated when overwriting.

Interestingly, the operation appears to silently fail if an uncompressed tile format folder exists.  For example, if I give the `toFile` command a path of `c:\test\image1.dz` and there is already a folder at `c:\test\image1_files` the command will silently fail (with no error) and will not modify the `c:\test\image1.dzi` file.  If I delete the `c:\test\image1_files` folder first, the operation succeeds (and also updates the modification time of the `c:\test\image1.dzi` file.

**Comment by lovell** [comment]
Inspecting the libvips source code, `gsf_outfile_new_*` (part of glib) is used to create `.dz` files and (on Windows) `_wfopen` used to create `.jpeg` files. I suspect therein lies the difference. @jcupitt may be able to help here.

**Comment by jcupitt** [comment]
How bizarre! Yes, that much be very confusing. As @lovell says, jpeg write on Windows uses `_wfopen("x.jpg", "wb")`, which I would expect to change the modification date. I'll try and find out of there's anything else I should add there.

`dzsave` should fail with an error if the output directory exists. At the command-line:

```
john@kiwi:~/pics$ vips dzsave k2.jpg x
john@kiwi:~/pics$ vips dzsave k2.jpg x
dzsave: output directory ./x_files exists
john@kiwi:~/pics$ echo $?
1
```

Perhaps the error return code is not being picked up?

**Comment by jcupitt** [comment]
It looks like `_wfopen()` should work. libvips is not using any of the revolting BOM stuff, so any existing file really should be destroyed. 

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-wfopen

Perhaps the modification timestamp is only updated on `fclose()`? What if you shut down node (to make certain everything is closed), then check the timestamp?

**Comment by dlong500** [comment]
Wow, this is getting even more convoluted as I've tested further.  Here's more info:

The Windows default "Date" attribute column (what is shown in the explorer folder view by default) is apparently a very complicated mess of special cases (even to the point of having different metrics for different file types).

The modification time actually _is_ being updated.  However, the creation time remains the same, and the default Date attribute apparently uses the creation time for JPEG files.  This is extra confusing because if I modify a text file the Date attribute uses the modification time.

All this being said, I would still expect the creation time (as well as all other timestamps) to be updated when a file is actually being _overwritten_ and not just modified.

In terms of the node process, none of the date information changes when the script completely exits, and I can also edit or delete the files manually without problems, so I don't think anything is related to a file handle being help open.

**Comment by jcupitt** [comment]
I had no idea it was so complicated!

Do you think vips should update the 'modified' EXIF tag? I think perhaps not, since a simple size change doesn't feel like modification, but I'm very open to argument.

**Comment by dlong500** [comment]
I don't like the idea of getting into EXIF updates either.  Is there perhaps any way to force the setting of the creation date during the operation?  Given that the file is being overwritten by new data I don't see a benefit in keeping an old creation date, and that would effectively fix this issue as well as far as I can tell.

**Comment by jcupitt** [comment]
So do an explicit delete before writing the file?

That seems to defeat the point of having separate creation and modification timestamps, but I'm happy to add this to the Windows code if necessary. Does anyone have any other thoughts?

**Comment by jcupitt** [comment]
... is it just explorer that shows the EXIF modification date rather than file modification? What if you try to read the file dates from node? Does that give the real mod date, or the EXIF one?

If this is a hack to get around explorer's dodgy date display, it seems like less of a good idea.

**Comment by dlong500** [comment]
No, there is no EXIF data on the source images at all.  I made sure of that.  I'm also not using `withMetadata` so even if the source data contained EXIF info it would be stripped in the resulting output.

Is there a way we could make it an option to do the explicit delete?  Unless you are performing an operation on an existing image and wanting to output/overwrite that _same_ image I don't see a benefit to the creation date remaining the same.  If the source data is an entirely different image then it really isn't _modifying_ the output file even if it already exists--it simply is writing a completely new file.  In that scenario it seems like the creation date remaining the same is just a side-effect of how `_wfopen()` operates.

**Comment by dlong500** [comment]
Bottom line, I think what I'm hoping for is a way (at least a option) to ensure that the creation date on a file is brand new.  I don't care as much about the funky Windows Explorer "Date" column (though forcing a new creation date would in theory fix that issue as well).

But the concept of the output of a file operation having different results (different creation date) based on whether the _destination_ file exists or not seems a bit odd to me.

**Comment by jcupitt** [comment]
Sorry, I think I have to bow out here. I don't have a Windows machine to test on, and I don't know how the creation date timestamp is supposed to work (linux just has access and modify). 

Could you add a delete before each write in your code? That might be a simple fix.

**Comment by dlong500** [comment]
I suppose that is what I'll have to do for my client.  I don't prefer Windows myself (especially for these types of applications) but my client requires it at the moment.

Thanks for your time.

**Comment by lovell** [comment]
It doesn't look like glib/gsf has much in the way of special handling for writing files on Windows other than UTF-16 conversion of filename and mode - https://github.com/GNOME/glib/blob/6b948d9613f2dcdec72828f3429ba01403063ff2/glib/gstdio.c#L689-L748

Perhaps this is a recent change in Windows? There's probably a registry setting :)

**Comment by lovell** [comment]
https://groups.google.com/forum/#!topic/comp.lang.c/CGP1NM4bgOk/discussion appears relevant here too.

**Comment by dlong500** [comment]
To add more information that offers some useful insight, but also shows further complication to file date descriptors on Windows, there is a "feature" known as file system tunneling that occurs by default on Windows platforms (going way back to Windows NT).

In short, if certain conditions are met, files can actually be **deleted** and then re-created and **_retain the same file descriptors, including creation date_**.  So even deleting a file first won't suffice to prevent this problem.

Here's a post with more specifics: https://blogs.msdn.microsoft.com/oldnewthing/20050715-14/?p=34923/

What I've had to do is actually use the [Utime module](https://github.com/ronomon/utimes) and rewrite the creation/birth time after the image is created if the detected platform is `win32`.

**Comment by jcupitt** [comment]
How strange! I'd never come across this. 

So when opening a file for write on windows, libvips should also set the creation time, is that correct?

**Comment by dlong500** [comment]
I think that would probably fix the issue.  I can't imagine anyone wanting to regenerate an image via sharp/libvips and have it keep the creation date of an earlier file.  I think the FS tunneling feature was primarily a workaround to prevent 16-bit apps from inadvertently renaming a long file name to the 8 character short name when overwriting the file.

In any case, I think for consistency it makes sense to set the creation time on Windows because the FS tunneling "window" might expire for some operations but not others based on how long some image processing operation takes to complete.

I'm not very familiar with the particulars of file APIs on Windows so I don't know if setting the creation time when the file is opened is enough or if it needs to be done afterward with a call to `SetFileTime` or some equivalent API.

**Comment by jcupitt** [comment]
OK, libvips issue for this: https://github.com/jcupitt/libvips/issues/729

@lovell I guess you can close.

**Comment by jcupitt** [comment]
From my reading, it sounds like they added this behaviour since, from the point of view of the FS, there's no way to know when a program intends to overwrite a file with a new version (in which case the create date should be kept), or create a new file which happens to have the same name (in which case it should be reset). 

Later, they added ReplaceFile(), which does now send that info down to the FS from the application, but they kept this horrible hack for compatibility. 

It seems to me that adding creation time without the API to support it was the real cause of this mess.

**Comment by lovell** [comment]
Great research @dlong500.

Thanks @jcupitt for picking this up in libvips.

**Comment by jcupitt** [comment]
Could someone test this?

https://github.com/jcupitt/libvips/releases/download/v8.6.0-alpha3/vips-dev-w64-all-8.6.0-2.zip

It might fix the issue. I don't have a win machine handy :(

**Comment by dlong500** [comment]
I'll try to do some testing, though I've only used libvips through sharp so far so I'll have to build the library and learn the direct commands.

@lovell Is there an easy way to build a test version of sharp based on an alpha version of libvips?

**Comment by jcupitt** [comment]
It's a win binary, just unzip somewhere, `cd` to `vips/bin` and run:

```
vips text x.png "hello world"
```

And it should make a PNG file with some text in. Check the ctime (file props in Windows explorer), then try running the command again. Hopefully the ctime on the file will change. Or maybe not!

**Comment by dlong500** [comment]
I'm building the current stable version for additional testing, but on first glance it looks like the files are somehow being generated without a creation date at all.  When bringing up the properties window, the "Details" tab shows a blank creation date, and the "General" tab shows a Created Date of "Wednesday, ‎February ‎20, ‎1608, ‏‎1:35:28 AM" for any image that is created (which I suspect somehow maps to some type of zero value).

**Comment by jcupitt** [comment]
Let's move this discussion to the libvips issue. 

https://github.com/jcupitt/libvips/issues/729

At least it's changing now.
