### ISSUE TITLE
sharp error object contains messages from other sharp instances/operations

### ISSUE THREAD

**Issue by dlong500** [lovell/sharp#902]
In my efforts to get to the bottom of some other issues I was having, I ran across a rather peculiar issue that I'm hoping is just a complete usage mistake on my part.

When I process a folder of images with sharp to create deep zoom image data (uncompressed) and the deep zoom output already exists, the error object sometimes contains error messages from other sharp instances/operations.  The behavior is not consistent--sometimes the errant data shows up in different places, but in my testing with the included dataset it almost always has at least a couple incorrect/leaked error messages during the run.

I've tested on Windows 7 x64 as well as Ubuntu 16.04, with Node 8.2.1 and the of course the latest version of sharp (0.18.2).  The issue showed up in both environments for me, which leads me to believe it is either actually a bug or I'm completely doing something wrong in the code.

I've put together a demonstration repo that also contains the results from 8 successive runs on one of my machines in the README.  The repo also includes a sufficiently large (86MB) dataset of public domain hi-res JPEGs to make testing easier.  I wanted a large enough dataset to make sure the issue is demonstrated (especially if there is some type of concurrency-related bug at play).

The repo is here:
https://github.com/dlong500/sharp-error-output

**Comment by lovell** [comment]
Hello, did you see http://jcupitt.github.io/libvips/API/current/libvips-error.html#libvips-error.description

> "The error buffer is global, that is, it is shared between all threads. You can add to the buffer from any thread (there is a lock to prevent corruption), but it's sensible to only read and clear the buffer from the main thread of execution."

**Comment by lovell** [comment]
sharp uses the error message it is given by libvips' C++ wrapper, but this can fall foul of the above.

**Comment by dlong500** [comment]
Thanks for the link.  That definitely sheds light on the situation.  Do you have any suggestions on how to deal with this with respect to sharp?  I don't know how to access the error info except for using the data returned in the error object available in the catch block.

**Comment by dlong500** [comment]
If there was some type of ID that could potentially be tracked then it might at least be possible to use that to pull information out of the error buffer relevant to the particular error.

Because of this situation, would it ever be possible that the error object returned doesn't even include the message tied to that error at all?

**Comment by lovell** [comment]
Adding specific return codes for each possible source of error would be something for implementation within libvips.

A similar question came up previously in #562.

Perhaps for now improving sharp's documentation to make people aware of the global nature of libvips' error log would be a good start. Happy to accept a PR for this.

**Comment by dlong500** [comment]
I wonder if it might also be possible as a libvips enhancement to accept a "job ID" that it would use to tag error messages?  Return codes would certainly be nice too, but as demonstrated in my test repo you can end up with multiple of the same _type_ of error but from different jobs/operations.

**Comment by lovell** [comment]
libvips operations return an integer status code internally, generally either 0 (success) or -1 (failure). The C++ bindings check for and throw an Error on a non-zero status code. Modifying libvips operations to return context-specific, non-zero status codes, then attached as a property to an Error, would provide an element of thread safety as the correct error message could be derived from the status code.

It would be quite a lot of work to add though. Summoning @jcupitt for his expert knowledge here.

**Comment by jcupitt** [comment]
Hello, I'm not sure the job ID would be enough: images (and therefore error causes) can be shared between threads, so it's not always obvious where an error should be reported. Maybe I've misunderstood the proposal!

I think the best practice fix would be to add an extra error parameter to every API call to allow the return of an error struct. GLib provides the `GError` mechanism for this:

https://developer.gnome.org/glib/stable/glib-Error-Reporting.html

So the C API would look like:

```C
int vips_add (GError **error, VipsImage *left, VipsImage *right, VipsImage **out, ...);
```

And you'd use it with something like:

```
GError *error = NULL;

if (vips_add (&error, left, right, &out, NULL)) 
{
    // to handle rather than propogate the error
    printf ("seen error %s\n", error->message);
    g_error_free (error);
    return 0;
}
```

But it's a huge pain, and would obviously break the whole API. The libvips global error log was supposed to be way to get most of an error system without forcing every single function call to carry an extra thing that needs managing. 

Perhaps this change should be considered for libvips 9.

**Comment by dlong500** [comment]
I get the idea behind the global error log reducing complexity in libvips itself.  Unfortunately I think it has the opposite effect on apps using libvips where massive numbers of images are being processed and tracking errors with precision is extremely important.  If the app is using a logging mechanism like winston and writing the error messages to a logfile then things will get very confusing very quickly when duplicate and out-of-order error messages are showing up.

I think it would be better in the long run to return error messages along with the errors themselves.  I understand this would be a lot of work and potentially a breaking change for some existing apps that consume libvips (though I think it would make things a lot simpler in the consuming apps as well).  I agree that the target should be libvips 9, though I hope that wouldn't be too far down the road...

Thanks for your consideration.

**Comment by lovell** [comment]
@jcupitt Thank you for stepping in to help. Do all libvips operations use varargs? If so, perhaps `error` could be an optional parameter to avoid breaking existing code? This approach might also allow the concept to be (slowly) added to operations as required, in a prioritised manner, rather than all at once.
```c
if (vips_add (left, right, &out, NULL)) { ...
```

```c
if (vips_add (left, right, &out, "error", &error, NULL)) { ...
```

**Comment by jcupitt** [comment]
Yes, that could help, you're right. I think it would need some experimentation to find a nice solution. 

I'll open an enhancement issue on libvips, though don't expect action very soon (sorry).

**Comment by lovell** [comment]
@jcupitt Thank you!

@dlong500 I'll close this question - anyone interested can track progress via the libvips enhancement at https://github.com/jcupitt/libvips/issues/707.
