### ISSUE TITLE
Unexpected image rotation during resize

### ISSUE THREAD

**Issue by mcurcio** [lovell/sharp#903]
My generated images are always "horizontal" (larger in width) even when the input was "vertical" -- for instance, an upright phone picture.

My resize code is basically:
```js
sharp(originalImagePath)
    .resize(200, 200) // to make a small thumbnail
    .min()
    .toFile(outputImagePath);
```

**Comment by mcurcio** [comment]
My mistake! I just found the documentation for `rotate` and I now understand that my source phone image was actually wider than it was tall but has an EXIF tag to rotate.

For anyone else who may have this issue, the correct code is:
```js
sharp(originalImagePath)
    .rotate()
    .resize(200, 200) // to make a small thumbnail
    .min()
    .toFile(outputImagePath);
```

**Comment by alxvallejo** [comment]
How can you tell if the image has "an EXIF tag to rotate"? Your solution suggests you just rotate everything ... ?

**Comment by lovell** [comment]
@alxvallejo If you've not already done so, please see http://sharp.dimens.io/en/stable/api-operation/#rotate

> "If no angle is provided, it is determined from the EXIF data."

If there's no EXIF data, or if the EXIF data states there should be no rotation, then none will occur for a parameter-less call to `rotate()`.

**Comment by MentalGear** [comment]
@lovell Tightly & very well explained. You might want to add this phrase to the docs, because to be honest, I didn't get this just from the doc text.
"If there's no EXIF data, or if the EXIF data states there should be no rotation, then none will occur for a parameter-less call to rotate()."

**Comment by lovell** [comment]
@MentalGear Please feel free to submit a PR for the [JSDocs](https://github.com/lovell/sharp/blob/master/lib/operation.js#L12) with this improvement.

**Comment by demisx** [comment]
I believe the latest doc link is: https://sharp.pixelplumbing.com/en/stable/api-operation/#rotate

**Comment by avichal-neweradeveloper** [comment]
@lovell rotate() works but it is increasing my buffer size a few times
