### ISSUE TITLE
Expose XMP / IPTC via metadata API

### ISSUE THREAD

**Issue by rayshan** [lovell/sharp#904]
Hello!

Since metadata API exposes EXIF data, would the project consider supporting XMP and IPTC as well?

I briefly looked around the libvips wiki. It doesn't mention XMP or IPTC. Happy to open a ticket there as well.

**Comment by lovell** [comment]
Hello, libvips makes these available as `VIPS_META_XMP_NAME` and `VIPS_META_IPCT_NAME` properties  but they have yet to be exposed via sharp. Happy to accept a PR with this useful addition.
