### ISSUE TITLE
Blurry Images

### ISSUE THREAD

**Issue by Radostin** [lovell/sharp#905]
Hello,

I am encountering an issue with resizing images. It may be due to something I am doing. Basically, the output images are blurry.

This is the code I am using:
```js
    var quality = 100;
    var format  = 'png';

    S3.getObject({Bucket: BUCKET, Key: originalKey}).promise()
        .then(data => Sharp(data.Body)
        .resize(width, height)
        .toFormat(format)
        .quality(quality)
        .toBuffer()
    )
    .then(buffer => S3.putObject({
        Body: buffer,
        Bucket: BUCKET,
        ContentType: 'image/png',
        Key: key,
    }).promise()
    )
    .then(() => callback(null, {
        statusCode: '301',
        headers: {'location': URL+key},
        body: '',
    })
```
The original files are in PNG format; they are high-quality/high-resolution images.

I saw that there's PNG compression level setting, but I can't seem to figure out how to use it with the toBuffer() method.

I am using a MacBook with a retina display, I hope that's not the reason why they do appear blurry. If that's the case, is there a way to optimize them for retina. I've went through the docs and can't seem to figure it out.

The library is great!

Thank you in advance!

**Comment by lovell** [comment]
Hello, I notice you're using the now-removed `quality` API, but this was ignored for PNG images as they are lossless (you'll see there are now `quality` parameters only for lossy formats).

Please can you use the latest version of sharp and if you're still having problems provide an original PNG image and the resize dimensions that when used produce a blurry PNG output.
