### ISSUE TITLE
resized image is not displayed in Safari

### ISSUE THREAD

**Issue by MarkAntonio** [lovell/sharp#907]
Hello,

Would like to request assistance...
I resize the image to smaller dimension (200 by 200), convert it to base64 and store it to database.
I can display the resized image in chrome but in safari the base64 image can't be loaded.

Here is the code in resizing ...
`const resizeImageJPEG = (base64, dimension) => {
    const base64WithNoMetadata = base64.replace(JPEG_METADATA, '')
    const imageBuffer = Buffer.from(base64WithNoMetadata, ENCODING_BASE64)
    return new Promise(resolve => {
        const { width, height } = dimension
        sharp(imageBuffer).resize(width, height).toBuffer().then(data => {
            resolve(`${JPEG_METADATA}${data.toString(ENCODING_BASE64)}`)
        })
    })
}`

Thanks.

**Comment by lovell** [comment]
Hello, I'm not quite sure I understand what you're trying to achieve here. Are you able to clean up your example code with newlines and/or semi-colons? If you remove all the base64 encoding/decoding does it work?

**Comment by MarkAntonio** [comment]
sharp encoding/decoding is working ok. It is an issue with test image we used.  Even mac could not open it.  We observed that images that mac could not open, could not be rendered in safari and firefox browsers. 
Thank you for accommodating my question.
