### ISSUE TITLE
input/output image quality

### ISSUE THREAD

**Issue by FranckFreiburger** [lovell/sharp#908]
Is it possible to know (or detect) input image quality in order to save the image with the same quality ?

**Comment by lovell** [comment]
Hello, I'm assuming you're referring to JPEG images. These do not contain the "quality" at which they were created.

ImageMagick attempts to [reverse engineer](https://github.com/ImageMagick/ImageMagick/blob/master/coders/jpeg.c#L817) a value, but makes assumptions about the quantisation tables so is not always correct.

**Comment by FranckFreiburger** [comment]
Thanks for the answer.
Do you think it is possible to convert my question into a feature request, even if the result will be approximative ?

**Comment by lovell** [comment]
Perhaps ask over at the libvips repo to see if there's any interest, as it is through libvips that sharp interfaces with libjpeg. Alternatively you could re-implement the logic from ImageMagick separately. However your best bet is to invoke the ImageMagick logic at the command line:

```sh
identify -format '%Q' input.jpg
```

**Comment by joemanfoo** [comment]
And for the ImageMagick command line front - if you're looking to do this in script then take a look at:
`const spawn = require('child-process-promise').spawn`

then invoke like:
`return spawn('identify', ['-format', '"%Q"', 'input.jpg'])`

The above code might not work out of the box since I've only used spawn for `convert` calls in the past but the general use is to pass the parameters as an array so ought to work (:fingers-crossed)

This way you'll be able to access the return of the identify in the rest of your script.

Hope this helps!

**Comment by FranckFreiburger** [comment]
Thanks for your help,
In order to avoid ImageMagick dependency, I will **try** to mix https://github.com/eugeneware/jpeg-js/blob/master/lib/decoder.js and https://github.com/ImageMagick/ImageMagick/blob/master/coders/jpeg.c#L817

**Comment by styfle** [comment]
I've been reading through all the linked issues and solutions but they all seem to be for jpeg input.

Is there a solution to detect the quality of a png input?

**Comment by lovell** [comment]
@styfle Full colour PNGs are lossless and the concept of "quality" does not really apply. A conversion from a full colour PNG to a palette-based PNG is lossy, but there's no way of knowing from the output how much "quality" was "lost" from the input.

In summary, if you know you always want palette-based PNG output, I suggest using a quality of "100" and not thinking too much about it. This will ensure a conversion from a palette-based PNG to a palette-based PNG is (near) lossless, and a conversion from a full-colour PNG to a palette-based PNG minimises lossy-ness.
