### ISSUE TITLE
Yet another install problem on Windows

### ISSUE THREAD

**Issue by joemanfoo** [lovell/sharp#909]
[2017-08-11T19_27_20_806Z-debug.log.txt](https://github.com/lovell/sharp/files/1218872/2017-08-11T19_27_20_806Z-debug.log.txt)
Yesterday things would build...today they will not.

Attached is the log

**Comment by joemanfoo** [comment]
Completely removed `node_modules` folder and updated node from 6.11.1 to 6.11.2 and now I get:
`Error: 404 status code downloading 64-bit node.lib`

**Comment by joemanfoo** [comment]
I've tested with other npm modules for node-gyp and `bson`, `phantomjs`, and `bufferutils` all install fine so I don't think this is an issue with my gyp and build tools.

Here's the latest output after starting everything from scratch this evening...

    C:\Users\Joe\Downloads\node-test\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
    The system cannot find the path specified.
    gyp: Call to 'node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
    gyp ERR! configure error
    gyp ERR! stack Error: 'gyp' failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
    gyp ERR! stack     at emitTwo (events.js:106:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
    gyp ERR! System Windows_NT 10.0.15063
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd C:\Users\Joe\Downloads\node-test\node_modules\sharp
    gyp ERR! node -v v6.11.2
    gyp ERR! node-gyp -v v3.6.2
    gyp ERR! not ok
    npm WARN test@1.0.0 No description
    npm WARN test@1.0.0 No repository field.

    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! sharp@0.18.2 install: 'node-gyp rebuild'
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the sharp@0.18.2 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\Joe\AppData\Roaming\npm-cache\_logs\2017-08-12T01_31_45_710Z-debug.log
    PS C:\Users\Joe\Downloads\node-test> npm i --save phantomjs
    The system cannot find the path specified.
    npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
    npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
    npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

    > phantomjs@2.1.7 install C:\Users\Joe\Downloads\node-test\node_modules\phantomjs
    > node install.js

    Considering PhantomJS found at C:\Program Files (x86)\PhantomJS\phantomjs.EXE
    Found PhantomJS at C:\Program Files (x86)\PhantomJS\phantomjs.EXE ...verifying
    Writing location.js file
    PhantomJS is already installed on PATH at C:\Program Files (x86)\PhantomJS\phantomjs.EXE
    npm WARN test@1.0.0 No description
    npm WARN test@1.0.0 No repository field.

I'm thinking the main culprit is:
`gyp: Call to 'node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error`

**Comment by lovell** [comment]
Hello, the `The system cannot find the path specified.` message just above the error you highlight hints that the location of `node.exe` might be missing from the `PATH` environment variable. Perhaps something went wrong during the upgrade?

The `Error: 404 status code downloading 64-bit node.lib` message usually suggests multiple conflicting copies of `node-gyp`.

`bson` and `phantomjs` do not use `node-gyp` and `bufferutil` provides pre-compiled binaries.

Does `npm install bufferutil --build-from-source` work?

**Comment by joemanfoo** [comment]
Hi @lovell -

You are correct that `npm install bufferutil --build-from-source`  wouldn't work:
```
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Joe\Downloads\node-test\node_modules\bufferutil
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@3.0.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@3.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Joe\AppData\Roaming\npm-cache\_logs\2017-08-13T02_45_40_017Z-debug.log
```
The Path issue, I've had this computer up for years and have lost a drive and there's something that's sticking around that's tossing that message out. The system can find `node` and other related tools just fine but as you can see below kicks out that message on some tools but not others.

`node -v`: `v6.11.2` (no path issue)
`npm -v`: `5.3.0` (and I get a system cannot find the path specified)
`node-gyp -v`: `v3.6.2` (and I get a system cannot find the path specified)

So if the issue is with my installation of NPM, any suggestions on how do I go about fixing it?

**Comment by lovell** [comment]
Thanks for confirming. My best guess would be a stray, older version of npm and/or node-gyp that is causing a conflict. Perhaps remove everything that could be node/npm/node-gyp related from this machine and install it all afresh. Good luck!

**Comment by joemanfoo** [comment]
@lovell - This is all FYI and for what it's worth (fwiw) so the path issue wasn't at all related to node or NPM or node-gyp. I completely removed all node traces from the computer and when nodejs was re-installed and `npm -v` ran again, the same path message was there. The issue was from this:
`https://stackoverflow.com/questions/15485632/node-js-npm-error-message-system-cannot-find-the-path-specified`
and once done fixed the path error message.

I've been developing on two machines, my desktop (old) and my Surface Laptop. Previously I could only install sharp on my laptop as my desktop never was able to install the package. The other day, "all of a sudden" sharp would no longer install on my laptop either. So this sent me into having to address what is really going on.  I'm still in the process of tracking things down but the root likely applies (on the desktop at least) to Visual Studio being previously installed on my machine prior to trying to install windows-build-tools as there's a known issue (https://github.com/felixrieseberg/windows-build-tools/issues/9).

As for why the laptop suddenly stopped being able to install is likely what you mentioned being that there are multiple `npm` / `node-gyp` versions installed. I've been working on getting the desktop up and running before I turn focus to the laptop.

Once I figure all this out I'd be happy to write up some notes for fellow window's users should they run into the heartache I've bumped into. I love `sharp` and the code you've graciously provided to the community beyond words, I only wished I could contribute but lack the skill.

I'll update this thread, unless you'd prefer me to not do so, once I have something to share.

Thank you again kindly!
