### ISSUE TITLE
DCI-P3 colorspace support

### ISSUE THREAD

**Issue by yury** [lovell/sharp#910]
Does sharp support p3 wide colorspace?

We want preserve p3 colorspace, but with no luck :)

You can see the differences [here](https://webkit.org/blog-files/color-gamut/comparison.html)

**Comment by lovell** [comment]
Hello, #218 is tracking the work to add support for this feature.

**Comment by yury** [comment]
Thanks.

**Comment by wanna2014go** [comment]
> I wonder if there a solution for this?
