### ISSUE TITLE
Switch from custom trim operation to vips_find_trim

### ISSUE THREAD

**Issue by fwang2002** [lovell/sharp#914]
Is there any way to get crop offsets from the original image when use trim(). I mean not the original image in the pipe, but the nearest pipe item before trim.

**Comment by lovell** [comment]
Hello, this is not at the moment. After libvips 8.6 is released we can switch from sharp's internal trim operation to libvips' forthcoming `vips_find_trim` operation, which will allow us to expose the calculated offsets.

**Comment by jcupitt** [comment]
Hello, vips keeps metadata fields `xoffset` / `yoffset` which record the position of the input image in the output image. For example:

```
john@kiwi:~/pics$ vips smartcrop k2.jpg x.v 500 500
john@kiwi:~/pics$ vipsheader -f xoffset x.v
-339
john@kiwi:~/pics$ vipsheader -f yoffset x.v
-1542
```

They should be valid after any kind of coordinate transform.

**Comment by ArmorDarks** [comment]
libvips 8.6 has been released. Are there any chances to get this feature?

**Comment by lovell** [comment]
@ArmorDarks As always, happy to help with and accept a PR for this.

**Comment by lovell** [comment]
v0.21.0 now available with this change.
