### ISSUE TITLE
Alpine Linux: Failed at the sharp@0.18.2 install script 'node-gyp rebuild'

### ISSUE THREAD

**Issue by adil717** [lovell/sharp#916]
when I building the docker its throwing error on sharp module
 
here is my docker file and I tried to install node-gyp globally as well but still error with node-gyp mean in both case

`FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install -y software-properties-common vim
RUN add-apt-repository ppa:jonathonf/python-3.6
RUN apt-get update
RUN groupadd --gid 1000 node \
  && useradd --uid 1000 --gid node --shell /bin/bash --create-home node
RUN apt-get -y update && apt-get install -y \
  curl \
  wget 
ENV NPM_CONFIG_LOGLEVEL info
ENV NODE_VERSION 7.10.0
RUN curl -O https://nodejs.org/download/release/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.gz
RUN curl -O https://nodejs.org/download/release/v${NODE_VERSION}/SHASUMS256.txt
RUN grep node-v${NODE_VERSION}-linux-x64.tar.gz SHASUMS256.txt | sha256sum -c -
RUN tar -xvf node-v${NODE_VERSION}-linux-x64.tar.gz --strip-components=1 -C /usr/local
RUN apt-get install -y build-essential
RUN node -v
RUN npm -v
RUN npm install -g node-gyp
RUN mkdir -p /app
ADD package.json /app
WORKDIR /app/
ENV HOME /app
ENV NODE_ENV development
RUN npm install
ADD . /app

EXPOSE 3000
CMD npm start

`
npm ERR! Linux 4.4.0-83-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! sharp@0.18.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! **Failed at the sharp@0.18.2 install script 'node-gyp rebuild'.**
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by lovell** [comment]
Hello, are all the [prerequisites](http://sharp.dimens.io/en/stable/install/#prerequisites) installed? I don't see Python listed here.

**Comment by adil717** [comment]
I added the python but still the same message.check the updated file please

**Comment by adil717** [comment]
**after some change now got this error**
make: Entering directory '/app/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
Release/obj.target/libvips-cpp.stamp Stats {
  dev: 90,
  mode: 33188,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 20064,
  size: 0,
  blocks: 0,
  atime: 2017-08-21T09:51:44.000Z,
  mtime: 2017-08-21T09:51:44.000Z,
  ctime: 2017-08-21T09:51:44.723Z,
  birthtime: 2017-08-21T09:51:44.723Z }
  CXX(target) Release/obj.target/sharp/src/common.o
make: g++: Command not found
sharp.target.mk:158: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: Leaving directory '/app/node_modules/sharp/build'
make: *** [Release/obj.target/sharp/src/common.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-83-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/sharp
gyp ERR! node -v v7.10.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok

**Comment by adil717** [comment]
Now after more change facing this issue

> sharp@0.18.2 install /app/node_modules/sharp
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.2.1 | linux | x64
gyp http GET https://nodejs.org/download/release/v8.2.1/node-v8.2.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v8.2.1/node-v8.2.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v8.2.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v8.2.1/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/app/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/app/.node-gyp/8.2.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/app/.node-gyp/8.2.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/app/.node-gyp/8.2.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/app/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
ERROR: musl libc (x86_64) requires manual installation - please see http://sharp.dimens.io/en/stable/install/
gyp: Call to 'LDD_VERSION="musl libc (x86_64)
Version 1.1.16
Dynamic Program Loader
Usage: ldd [options] [--] pathname" node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-83-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/sharp
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm info lifecycle sharp@0.18.2~install: Failed to exec install script
npm WARN shop-catalogue@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.18.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.18.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2017-08-21T11_19_29_085Z-debug.log

**Comment by adil717** [comment]
I also tried using this docker file

FROM node:alpine

# Update apk and install node
RUN apk update && apk upgrade
RUN apk --update add python
RUN apk add nodejs
RUN apk add g++


RUN mkdir -p /app
ADD package.json /app
WORKDIR /app/
#RUN npm install node-gyp

ENV HOME /app
ENV NODE_ENV development

# Install dependencies
RUN npm install

# Development Only
#VOLUME ["/mnt_vol"]

# Production
ADD . /app

EXPOSE 3000
CMD npm start

**Comment by schoenwaldnils** [comment]
I have the same issue.
```
npm ERR! sharp@0.18.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.18.2 install script 'node-gyp rebuild'.
```

Any progress here?
This is sadly blocking my complete workflow :/

**Comment by EricBou** [comment]
Same problem here.  Since friday 18, my build fail with this error.  No code change, no modification on the build machine

npm ERR! sharp@0.18.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.18.2 install script 'node-gyp rebuild'.

Any solution or idéa

Thanks

**Comment by schoenwaldnils** [comment]
Maybe this helps digging into it.
I also get this:

```
> node-gyp rebuild
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/home/travis/build/finanzcheck/website/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
Release/obj.target/libvips-cpp.stamp Stats {
  dev: 64518,
  mode: 33188,
  nlink: 1,
  uid: 1000,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 9118494,
  size: 0,
  blocks: 0,
  atime: 2017-08-23T14:12:41.000Z,
  mtime: 2017-08-23T14:12:41.000Z,
  ctime: 2017-08-23T14:12:41.116Z,
  birthtime: 2017-08-23T14:12:41.116Z }
  CXX(target) Release/obj.target/sharp/src/common.o
In file included from ../src/common.cc:24:0:
../../nan/nan.h:45:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from /home/travis/.node-gyp/6.11.2/include/node/node.h:42:0,
                 from ../src/common.cc:22:
/home/travis/.node-gyp/6.11.2/include/node/v8.h:345:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/6.11.2/include/node/v8.h:481:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/6.11.2/include/node/v8.h:882:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/6.11.2/include/node/v8.h:5433:35: error: ‘virtual v8::EmbedderHeapTracer::~EmbedderHeapTracer()’ declared virtual cannot be defaulted in the class body
In file included from ../../nan/nan.h:192:0,
                 from ../src/common.cc:24:
```

There is a lot of `nan` and `NAN` there.
`node/NAN/v8`

**Comment by lovell** [comment]
Please see http://sharp.dimens.io/en/stable/install/#alpine-linux for Alpine Linux.

**Comment by lovell** [comment]
@schoenwaldnils Please see the C++11 compiler prerequisites http://sharp.dimens.io/en/stable/install/#prerequisites

**Comment by lovell** [comment]
Hope everyone got their problems sorted. Please open new issues if not.
