### ISSUE TITLE
Strange lines after resizing with background('white') and embed()

### ISSUE THREAD

**Issue by alanprot** [lovell/sharp#917]
I'm having some problem when resizing a image and trying to keep the aspect ratio and embed on a white background.

Follow the original Image:

![input](https://user-images.githubusercontent.com/4027760/29473287-930c38a6-842d-11e7-8b5a-3d04586d470c.jpg)

Result of `.resize(410, 220).background({r: 255, g: 255, b: 255, alpha: 1}).embed()`

![output](https://user-images.githubusercontent.com/4027760/29473418-24b41c74-842e-11e7-9eb7-80fa57f015dd.jpg)

As you can see there are two "black" lines that were not present on the original image.

Thanks

**Comment by lovell** [comment]
Hello, this looks like an artefact of libjpeg's shrink-on-load. I see the same thing at the command line via:

```
djpeg -scale 1/4 -bmp input.jpg >output.bmp
```

As a workaround, add `gamma(1)` to your pipeline to prevent this optimisation. See #883 for a related future possible enhancement.
