### ISSUE TITLE
sharp unit tests fails

### ISSUE THREAD

**Issue by tendermario** [lovell/sharp#918]
Hello, I was about to submit a PR to update the documentation that had me puzzled for a while. However, when running the tests, they currently fail:

```
533 passing (1m)
  2 failing

  1) Crop Attention strategy JPEG:
     Error: Expected maximum similarity distance: 5. Actual: 31.
      at test/fixtures/index.js:157:27
      at test/fixtures/index.js:33:9

  2) Input/output Convert SVG to PNG at 300DPI:
     Uncaught Error: Expected maximum similarity distance: 5. Actual: 16.
      at test/fixtures/index.js:157:27
      at test/fixtures/index.js:33:9



npm ERR! Test failed.  See above for more details.
```

My PR doesn't have anything to do with adding or removing tests, however I just wanted to follow the [Contributing](https://github.com/lovell/sharp/blob/master/CONTRIBUTING.md) guidelines as close as possible.

I'm not familiar with these tests enough to understand how to fix them or if the tests are inaccurate.

**Comment by lovell** [comment]
Hello, is this with libvips v8.5.7+? If so, these are due to changes in libvips. The CI jobs will (currently) use libvips v8.5.6.

**Comment by tendermario** [comment]
Yep! `vips -v` gives me `vips-8.5.7`. Must be it.
