### ISSUE TITLE
doc about install on alpine on docker

### ISSUE THREAD

**Issue by GongT** [lovell/sharp#920]
all package needed while install: (can delete after install)
> vips-dev fftw-dev python make g++ binutils

extra package required while running:
> vips

http://sharp.dimens.io/en/stable/install/#alpine-linux

**Comment by lovell** [comment]
Hello, Python and a C++11 compiler (and related tools) are http://sharp.dimens.io/en/stable/install/#prerequisites for all platforms, not just Alpine Linux.

`fftw-dev` is included under http://sharp.dimens.io/en/latest/install/#alpine-linux in the "latest" docs, which will be promoted to the "stable" docs after the next release.

**Comment by GongT** [comment]
ok, that's right, thanks!
