### ISSUE TITLE
sharp.libvipsVersion is not a function

### ISSUE THREAD

**Issue by sbatururimi** [lovell/sharp#923]
I have installed sharp using yarn. It seems to be installed but when building a React app, I got the above error in the browser
<img width="1113" alt="screen shot 2017-08-27 at 22 15 13" src="https://user-images.githubusercontent.com/1911418/29753224-3e4f114a-8b75-11e7-90ab-17d46fad528e.png">

version 0.18.2 installed with yarn

**Comment by lovell** [comment]
Hello, are you trying to run this in a browser? If so, this will not work as sharp is a server-side module that requires the Node.js runtime.

**Comment by sbatururimi** [comment]
Not really, trying to use it to resize images in a react app but the app failed to compile showing the above. Will try to use it in a pure server environment and will let you know.

**Comment by lovell** [comment]
@sbatururimi Were you able to make any progress with this?

**Comment by sbatururimi** [comment]
Not really. I tried to use it in a React App but seems that there is a problem to load the library maybe due to the browser, not sure. Didn't investigate deeply. I finally opted to move the whole sharp code outside the React App and it worked.

**Comment by lovell** [comment]
Thanks for the update, glad to hear to got something working.

If you're using a code bundler such as Webpack then you'll need to exclude sharp, possibly via `externals` - see #794 for more discussion about this.

**Comment by sbatururimi** [comment]
Thank you @lovell Will take a look!
