### ISSUE TITLE
Color manipulation on resize

### ISSUE THREAD

**Issue by tim-hanssen** [lovell/sharp#927]
We're resizing a image with sharp, almost using default configuration.

```
Sharp(data.Body)
      .resize(width, height)
      .crop(Sharp.gravity[cropPosition])
      .quality(quality)
      .toFormat('jpeg')
      .toBuffer()
```

Our images have some sort of 'color boost' on them. Is there a way to prevent this behaviour?

**Comment by lovell** [comment]
Hello, are you able to share an example input image (preferably via a file sharing service other than Github as it can mangle images)?

**Comment by lovell** [comment]
@tim-hanssen Are you able to share an example image that exhibits this behaviour?

**Comment by lovell** [comment]
Please feel free to re-open with a sample image.
