### ISSUE TITLE
MSB8007 Error on x64 windows 10

### ISSUE THREAD

**Issue by rui-cruz** [lovell/sharp#928]
Hi,

I'm trying to create a sample app with electron, but unfortunately I'm not able to try it:

> sharp@0.18.2 install C:\Users\infor\Desktop\app-electron\sample-app\sharp
 node-gyp rebuild

> C:\Users\infor\Desktop\sample-app\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@6.11.2 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "c:/Python27/python.exe" in the PATH
gyp verb `which` succeeded c:/Python27/python.exe c:\Python27\python.exe
gyp verb check python version `c:\Python27\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.3\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 6.11.2
gyp verb command install [ '6.11.2' ]
gyp verb install input version string "6.11.2"
gyp verb install installing version: 6.11.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 6.11.2
gyp verb build dir attempting to create "build" dir: C:\Users\infor\Desktop\app-electron\sample-app\sharp\build
gyp verb build dir "build" dir needed to be created? C:\Users\infor\Desktop\app-electron\sample-app\sharp\build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\infor\Desktop\app-electron\sample-app\sharp\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\infor\Desktop\app-electron\sample-app\sharp\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\infor\Desktop\app-electron\sample-app\sharp\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn c:\Python27\python.exe
gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\infor\\Desktop\\app-electron\\angular-electron\\node_modules\\sharp\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\infor\\.node-gyp\\6.11.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\infor\\.node-gyp\\6.11.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\infor\\Desktop\\app-electron\\angular-electron\\node_modules\\sharp',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\infor\\Desktop\\app-electron\\angular-electron\\node_modules\\sharp\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\infor\.node-gyp\6.11.2
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp verb "Release" dir needed to be created? null
gyp verb copying "node.lib" for x64 C:\Users\infor\.node-gyp\6.11.2\Release\node.lib
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 03/09/2017 02:44:49.
Project "C:\Users\infor\Desktop\app-electron\sample-app\sharp\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
The target "Midl" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\BuildCustomizations\masm.targets (28,5)" does not exist in the
 project, and will be ignored.
The target "CustomBuild" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\BuildCustomizations\masm.targets (29,5)" does not exist
 in the project, and will be ignored.
Project "C:\Users\infor\Desktop\app-electron\sample-app\sharp\build\binding.sln" (1) is building "C:\Users\infor\Desktop\app-electron\a
ngular-electron\node_modules\sharp\build\libvips-cpp.vcxproj" (2) on node 1 (default targets).
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform.Targets(23,7): error MSB8007: The Platform for project 'libvips-cpp.vcxproj' is invalid.
Platform='x64'. You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Platform that doesn't e
xist for this project. [C:\Users\infor\Desktop\app-electron\sample-app\sharp\build\libvips-cpp.vcxproj]
Done Building Project "C:\Users\infor\Desktop\app-electron\sample-app\sharp\build\libvips-cpp.vcxproj" (default targets) -- FAILED.

>Done Building Project "C:\Users\infor\Desktop\app-electron\sample-app\sharp\build\binding.sln" (default targets) -- FAILED.

>Build FAILED.

>"C:\Users\infor\Desktop\app-electron\sample-app\sharp\build\binding.sln" (default target) (1) ->
"C:\Users\infor\Desktop\app-electron\sample-app\sharp\build\libvips-cpp.vcxproj" (default target) (2) ->
(InvalidPlatformError target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform.Targets(23,7): error MSB8007: The Platform for project 'libvips-cpp.vcxproj' is invalid.
  Platform='x64'. You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Platform that doesn't
 exist for this project. [C:\Users\infor\Desktop\app-electron\sample-app\sharp\build\libvips-cpp.vcxproj]

>    0 Warning(s)
>    1 Error(s)

Any help is appreciated

Kind regards,
Rui

**Comment by lovell** [comment]
Hello, it looks like there may be multiple, conflicting copies of msbuild as both `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` and `C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\...` appear in the output.

You'll probably need to either uninstall an old one or set/update an environment variable to point to the new one, perhaps `VCTargetsPath`.

**Comment by rui-cruz** [comment]
Hi @lovell 
you were right! but I could only solve this issue on other laptop I bought yesterday..
I had to use this:
`# as admin `
> npm install --global --production windows-build-tools

Thank you very much!
