### ISSUE TITLE
How to get image pixels hash?

### ISSUE THREAD

**Issue by rui-cruz** [lovell/sharp#929]
Hi,

I need something similar to: imagemagick command "identify -verbose myimage.png", but I can't find on documentation.

Kind regards,
Rui

**Comment by lovell** [comment]
Hello, might https://www.npmjs.com/package/sharp-phash provide what you need?

**Comment by rui-cruz** [comment]
Hi @lovell ,

Thank you for your reply, I'll give it a try. What I need, is to detect if the user changed the original image somehow (not metadata), and if true, create new resizes again.

Thank you very much,
Rui
