### ISSUE TITLE
Docs: add link to Typescript typings

### ISSUE THREAD

**Issue by rui-cruz** [lovell/sharp#931]
Hey guys,

Is there any typings for Sharp?

Thank you,
Rui

**Comment by lovell** [comment]
Yes, please see https://www.npmjs.com/package/@types/sharp

I'll leave this open as a reminder to add a documentation link to these, thank you.

**Comment by rui-cruz** [comment]
Awsome! Can't wait to try it out!

Thank you very much!

**Comment by brooksbecton** [comment]
Where would ya'll like the types to be linked at? 
Maybe some where around the [Build Tools](http://sharp.dimens.io/en/stable/install/#build-tools)

**Comment by lovell** [comment]
@brooksbecton Sounds good, perhaps under that in a new "Code tools" section?

**Comment by brooksbecton** [comment]
I've made a PR here #975 

Let me know if anything is wrong and I'd be happy to correct it.
