### ISSUE TITLE
resize request exception error message is junk characters

### ISSUE THREAD

**Issue by vikramaditya234** [lovell/sharp#933]
Here is how I am using sharp:
>         sharp("sample.jpg")
>          .resize(parseInt(20))
>          .toBuffer()
>          .then(function(err, outputBuffer){
>             if (err) {
>                 throw err;
>             }
>         })
>         .catch(function (err){
>             console.log('exception in sharp: '+err);
>         });

This request is hitting exception and returning junk characters as error message:

> exception in sharp: ï¿½ï¿½ï¿½ï¿½C
%-(0%()(ï¿½ï¿½C
> 
> 
> (((((((((((((((((((((((((((((((((((((((((((((((((((ï¿½ï¿½
> "ï¿½ï¿½ï¿½ï¿½"!A1Qï¿½ï¿½ï¿½ï¿½!ï¿½ï¿½
> ?ï¿½ï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½ï¿½ï¿½Qï¿½Eï¿½ï¿½ï¿½;|ï¿½0ï¿½ï¿½ï¿½Ó¡Qï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½RYï¿½ï¿½fï¿½ï¿½4ï¿½ï¿½F%ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½> rMï¿½ï¿½ï¿½ï¿½
> PuTTYPuTTYPuTTYPuTTYPuTTYPuTTY

What am I doing wrong?

**Comment by lovell** [comment]
JavaScript Promises resolve with a value via `then()` and reject with an error via `catch()` .
```diff
-     .then(function(err, outputBuffer){
+     .then(function(outputBuffer){
```
