### ISSUE TITLE
Color picker

### ISSUE THREAD

**Issue by hybmg57** [lovell/sharp#934]
Does sharp support colorpicker like imagemagick?

equivalent of something like:

```
coords="20,20"
color=`convert someimage.jpg -format "%[pixel:s.p{$coords}]" info:`
convert -size 100x100 xc:"$color" background.jpg
```

I want to get color for each corner. Is it possible with Sharp?

**Comment by lovell** [comment]
Hello, you can access [raw](http://sharp.dimens.io/en/stable/api-output/#raw) pixel data as follows:

```javascript
const coords = { x: 20, y: 20 };
sharp('someimage.jpg')
  .raw()
  .toBuffer()
  .then(data => {
    // data is a Buffer of length (width * height * channels)
    // containing 8-bit RGB(A) pixel data.
  });
```

**Comment by hybmg57** [comment]
@lovell great! How do I access color data from within .then?
