### ISSUE TITLE
sharp still requires brew for OS X / macOS Sierra

### ISSUE THREAD

**Issue by niftylettuce** [lovell/sharp#939]
Myself and 3 others had the issue <https://github.com/ladjs/lad/issues/258>

`Library not loaded: @rpath/libvips-cpp.42.dylib`

We are all on Mac OS X or macOS Sierra platforms.

To workaround this, we had to run:

```sh
brew install homebrew/science/vips --with-webp --with-graphicsmagick
```

Then `rm -rf node_modules/sharp` and `yarn install` again to recompile.

I think that the installation instructions at <http://sharp.dimens.io/en/stable/install> need updated.

**Comment by goldo** [comment]
thanks a lot ! 👍  solved my problem

**Comment by lovell** [comment]
Hello, whilst sharp will work with a manual installation of vips, this step is optional as sharp will download its own pre-built binaries of libvips+dependencies. I believe something else is wrong here and will investigate.

**Comment by lovell** [comment]
Have commented in https://github.com/ladjs/lad/issues/258 - I suspect this may be a yarn bug (or "performance feature") when upgrading packages.

Part of the work for #186 will be to ensure the pre-built binaries are for the right platform/version. Perhaps the version-checking part of that could be worked on first to detect this kind of problem.

**Comment by goldo** [comment]
@lovell when I do this:
```
brew remove vips
rm -rf node_modules
npm cache clear
npm install
```
I still have the segmentation fault on my image (#937) 

Wether I'm using yarn or npm

**Comment by lovell** [comment]
@goldo Thanks, I don't believe this problem and #937 are related, so have re-opened the latter for separate tracking.

**Comment by lovell** [comment]
#186 is now in progress and will provide the version-checking logic I mentioned in https://github.com/lovell/sharp/issues/939#issuecomment-328043901 so I'll close this - please subscribe to #186 for updates.

**Comment by ifiokjr** [comment]
This issue cropped up for me after updating to macOS Mojave. I had been using `sharp` without issues prior to this. 

A variation of the first comment worked for me. 

```bash
brew  install vips --with-webp --with-graphicsmagick
rm -rf node_modules && yarn;
```

**Comment by niftylettuce** [comment]
Neat, I just use my service [Lipo.io](https://lipo.io) entirely now, 100% uptime!  Still have to figure out how to handle versioning and get a status page up or something + SLA.

**Comment by shakedlokits** [comment]
@niftylettuce It works! thank you! 👍

**Comment by MarginCall2019** [comment]
> Myself and 3 others had the issue [ladjs/lad#258](https://github.com/ladjs/lad/issues/258)
> 
> `Library not loaded: @rpath/libvips-cpp.42.dylib`
> 
> We are all on Mac OS X or macOS Sierra platforms.
> 
> To workaround this, we had to run:
> 
> ```shell
> brew install homebrew/science/vips --with-webp --with-graphicsmagick
> ```
> 
> Then `rm -rf node_modules/sharp` and `yarn install` again to recompile.
> 
> I think that the installation instructions at http://sharp.dimens.io/en/stable/install need updated.

thank you, you save my day.

**Comment by niftylettuce** [comment]
No problem!  I did make https://lipo.io as an alternative too, feel free to use it.
