### ISSUE TITLE
Electron: Unable to open profile vips_colourspace: no known route between 'cmyk' and 'srgb'

### ISSUE THREAD

**Issue by calebjessie** [lovell/sharp#941]
I get this error after building out my electron js app on Windows 10 64-bit.

`VipsIcc: File 'C:\Program Files\Assembler\resources\app.asar\node_modules\sharp\lib\icc\sRGB.icc' not found
icc_transform: unable to open profile "C:\Program Files\Assembler\resources\app.asar\node_modules\sharp\lib\icc\sRGB.icc"
vips_colourspace: no known route between 'cmyk' and 'srgb'`

I checked for the file to see if it actually exists or not and sure enough it's there.
Error only happens after I build the app so I'm not sure if this is an issue with the electron builder or the sharp package.

Any ideas?

**Comment by lovell** [comment]
Hello, is the ASAR file unpacked? I believe Electron patches `require` and the `fs` package so they work with the archive format directly but libvips will need the file on the real filesystem rather than via Electron's virtual filesytem.

**Comment by calebjessie** [comment]
Thanks for a timely response. There is an unpacked version `app.asar.unpacked` with several modules, sharp being one of them. After some research I found that electron-builder automatically detects node_modules that need to be unpacked. I explicitly set the app the not be packed at all and the error goes away.  Of course, this might be obvious and ultimately undesirable but I figured I'd test it out anyway.

**Comment by lovell** [comment]
https://github.com/lovell/sharp/issues/678#issuecomment-275956028 might be relevant here too.

**Comment by calebjessie** [comment]
I've tried to explicitly set sharp to be unpacked and still get the same error. I think it's important to note that the module works normally converting most images until it gets to a specific set of images. Then it throws the error a few times and returns to working normally. Currently I only look for '.jpg' images to convert. Though I don't see how this would affect whether or not the module looks in the unpacked asar.

**Comment by lovell** [comment]
This code path is reached for JPEG images in the CMYK colourspace that are missing the embedded profile. Technically these are invalid images, but sharp is nice and tries to use its own `lib\icc\sRGB.icc` profile instead because that's what you probably meant :)

**Comment by lovell** [comment]
My best guess would be that the value of `__dirname` at `require` time in `sharp/lib/constructor.js` is the virtual, packed directory rather than unpacked directory.

https://github.com/lovell/sharp/blob/master/lib/constructor.js#L106

If so, not sure how best to fix this one.

**Comment by calebjessie** [comment]
I see what you mean. Seeing that this isn't an issue with sharp itself and more with the packager I'm using I no longer want to take up your time! Thanks for your help anyway, Lovell.

**Comment by lovell** [comment]
https://github.com/electron/electron/issues/8206 seems relevant here.
