### ISSUE TITLE
Add text to image

### ISSUE THREAD

**Issue by nanom1t** [lovell/sharp#947]
Hi,

The sharp package is very useful for my Node.js app. Is it possible to add text to images? It will be awesome to have this feature if it does not exist yet.

Thanks

**Comment by lovell** [comment]
Hello, please see #477 and #512.

**Comment by nanom1t** [comment]
Thank you for your response. It works, but I have another issue or question.

I want to rotate text for 30 degrees. I'm using [rotate(30)](http://sharp.dimens.io/en/stable/api-operation/#rotate) method, but I cannot completely understand how it works.

How can I rotate png image to 30 degress using rotate method?
```
    throw new Error('Unsupported angle: angle must be a positive/negative multiple of 90 ' + angle);
    ^
Error: Unsupported angle: angle must be a positive/negative multiple of 90 45
    at Sharp.rotate (/vagrant/node_modules/sharp/lib/operation.js:41:11)
    at /vagrant/test.js:31:34
    at FSReqWrap.oncomplete (fs.js:123:15)
```
Thanks

**Comment by lovell** [comment]
Hello, I see you've found the docs, which state `angle` "must be a multiple of 90".

There has been some work to attempt to implement arbitrary angles, e.g. #906, but this is not yet supported.

**Comment by tunix** [comment]
@lovell Is writing text with an angle still not doable? I followed the issues you mentioned but couldn't really understand whether it's now supported or not. Couldn't find any pointers in the docs as well (except only rotating the whole image). Having issues with dependencies in lambda layers I'd be glad if sharp had this feature.

**Comment by lovell** [comment]
@tunix Please subscribe to #512 for future possible updates to a future possible enhancement.
