### ISSUE TITLE
Trim only top and bottom

### ISSUE THREAD

**Issue by hybmg57** [lovell/sharp#948]
Is there a way to use `.trim` for only top and the bottom and not left and right?

http://sharp.dimens.io/en/stable/api-operation/#trim

**Comment by lovell** [comment]
Hello, the `trim` operation will be switching to the libvips-provided version from the next release as part of #914. This work will expose the dimensions calculated by the trim operation so perhaps you could use these for a second call to extract the area you're interested in?

**Comment by hybmg57** [comment]
Hi @lovell so is it possible to achieve this at the current version? I have a few `.resize` operations but was trying to find a way so `trim` does not keep its original size but resize down to that trimmed version. This way I can minus from original width and put `extend` with left and right. Is it possible to do this?

**Comment by lovell** [comment]
This will only be possible after the work for #914 is done, and only then as a two-step operation, so your best bet is to subscribe to it for updates.

**Comment by hybmg57** [comment]
It would be great if someone had a workaround solution to this
