### ISSUE TITLE
Node v7.0.0+: Buffer passed to sharp may be rewritten/reused by other node code before being parsed?

### ISSUE THREAD

**Issue by lfdoherty** [lovell/sharp#950]
The result is that various random errors happen. I experienced this while streaming tar file entries into sharp from isaacs 'tar' module. If I hold onto the buffer in V8 it works fine:

```
sharp(buf)
	.raw()
	.toBuffer((err, data, info) => {
		if(err){
			console.log(filename)				
			console.log(buf) //without this line, random errors happen
			throw err;
		}
		// process the raw data...
	})
```

Otherwise, I get errors about corrupt headers, unsupported formats, etc.

Node 8.5.0, sharp 0.18.3

Thanks for this great module - really impressive performance and clean design.

**Comment by lovell** [comment]
Hello, my best guess would be that code not shown here is modifying the contents of `buf` after the construction of the `sharp` instance but before it has asynchronously finished processing it. If so, perhaps copy it first using something like `Buffer.from(buf)`.

(The use of `console.log` is masking the problem as it block IOs and can therefore make async logic appear to be synchronous.)

**Comment by lfdoherty** [comment]
To be clear, console.log is never called except when an error happens. As long as that line is there, no errors happen. So the only difference is in whether the VM is holding on to the buffer in case console.log happens (as far as I can see.) Buffers get allocated out of a pool, so my assumption is that under heavy allocation load, the buffer memory is being reclaimed by GC and reused too early.

I modified the program like so, same behaviour:

```
sharp(Buffer.from(buf))
	.raw()
	.toBuffer((err, data, info) => {
		if(err){
			if(buf[0] !== buf[1]){} //without this line, random errors happen
			throw err;
		}
		//process the raw data...
	})
```

**Comment by lfdoherty** [comment]
I should add - it's weird that retaining a handle to the "buf" that gets copied by Buffer.from(buf) works...  The only explanation I can think of is that it's using the same underlying chunk of memory as the buffer created by Buffer.from(buf), but it's weird that it *never* fails to be in the same chunk.  I checked, and retaining a handle to the buffer returned by Buffer.from(buf) has the same effect.

**Comment by lfdoherty** [comment]
Here's a repository with a test case: https://github.com/lfdoherty/sharp-buffer-loss-reproduction

**Comment by lovell** [comment]
Thanks for the test case, I'll take a look. Have you tried with any other versions of Node?

https://github.com/lovell/sharp/blob/master/src/pipeline.cc#L40-L45 contains the logic to explicitly tell V8 not to GC input Buffer instances. This doesn't/can't prevent other code modifying the contents of `buf` in-place.

(The reverse logic, to re-enable GC for input Buffers, is at https://github.com/lovell/sharp/blob/master/src/pipeline.cc#L1031-L1036)

**Comment by lfdoherty** [comment]
Good idea!

v8.5.0 (Ubuntu,OSX): fails
v7.10.1 (Ubuntu): fails
v7.5.0: fails
v7.0.0: passes
v6.11.3: passes
v4.8.4: passes

I'm still narrowing down which version of 7 it started breaking on...

**Comment by lovell** [comment]
I can reproduce using Node 8.0.0+ (V8 5.8) but it works perfectly using Node 6.11.3 (V8 5.1) and Node 4.8.4 (V8 4.5).

Perhaps there's been a change/regression in V8 around the way persistent handles behave during GC.

**Comment by lfdoherty** [comment]
v7.4.0: fails
v7.1.0: fails

**Comment by lovell** [comment]
I can confirm that Node 7.1.0 is where the failing behaviour begins.

https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V7.md#2016-11-08-version-710-current-evanlucas

Interestingly, if I set `Buffer.poolSize = 8200` (a slight increase from the default 8192) the problem appears to go away.

The next step is to try your example with a locally-modified version of sharp that dumps out Buffer memory locations as each instance is created and again as its pipeline is processed.

**Comment by lovell** [comment]
After some further debugging it looks like when a mark-sweep GC occurs after the call to `SaveToPersistent` but before the subsequent `GetFromPersistent`, the contents of that Buffer's memory location can be overridden. I don't believe this should be possible :(

This only occurs with Node 7.1.0+ and for Buffer objects backed by a SlowBuffer. Increasing `poolSize` so everything is a FastBuffer appears to "solve" the problem.

I feel like we should at least open an issue with nodejs/node to see if there's something obvious we're missing.

```
...
input buffer at 0x39cd100 of length 1399 first char ff
0000003716-S.jpg 1399
input buffer at 0x39cd680 of length 1399 first char ff
pipeline buffer at 0x398f060 of length 1256 first char ff
0000003717-S.jpg 1058
input buffer at 0x3a12730 of length 1058 first char ff
0000003718-S.jpg 1599
input buffer at 0x39cdc00 of length 1599 first char ff
0000003719-S.jpg 1262
input buffer at 0x39ce250 of length 1262 first char ff
0000003720-S.jpg 1267
input buffer at 0x3a29860 of length 1267 first char ff
0000003721-S.jpg 1382
input buffer at 0x3a29d60 of length 1382 first char ff
0000003722-S.jpg 1382
input buffer at 0x3a2a2d0 of length 1382 first char ff
0000003723-S.jpg 1425
input buffer at 0x3a2c850 of length 1425 first char ff
0000003724-S.jpg 1425
input buffer at 0x3a2cdf0 of length 1425 first char ff
0000003725-S.jpg 1487
input buffer at 0x3a2d390 of length 1487 first char ff
0000003726-S.jpg 1487
input buffer at 0x3a2d970 of length 1487 first char ff
0000003727-S.jpg 1432
input buffer at 0x3a2df50 of length 1432 first char ff
0000003728-S.jpg 1432
input buffer at 0x3a30500 of length 1432 first char ff
0000003729-S.jpg 1326
pipeline buffer at 0x39ccc10 of length 1256 first char ff
input buffer at 0x3a30aa0 of length 1326 first char ff
0000003730-S.jpg 1326
input buffer at 0x3a30fe0 of length 1326 first char ff
pipeline buffer at 0x39cd100 of length 1399 first char ff
pipeline buffer at 0x39cd680 of length 1399 first char 20
pipeline buffer at 0x3a12730 of length 1058 first char f0
pipeline buffer at 0x39cdc00 of length 1599 first char ff
[20770:0x3290a20]     2614 ms: Mark-sweep 19.0 (51.0) -> 6.0 (51.0) MB, 2.4 / 0.2 ms  (+ 7.1 ms in 85 steps since start of marking, biggest step 0.4 ms) GC interrupt GC in old space requested
pipeline buffer at 0x39ce250 of length 1262 first char 50
pipeline buffer at 0x3a29860 of length 1267 first char c0
0000003731-S.jpg 1443
pipeline buffer at 0x3a29d60 of length 1382 first char 70
pipeline buffer at 0x3a2a2d0 of length 1382 first char f0
pipeline buffer at 0x3a2c850 of length 1425 first char c0
input buffer at 0x360fe80 of length 1443 first char ff
pipeline buffer at 0x3a2cdf0 of length 1425 first char e0
pipeline buffer at 0x3a2d390 of length 1487 first char e0
pipeline buffer at 0x3a2d970 of length 1487 first char 0
pipeline buffer at 0x3a2df50 of length 1432 first char f0
pipeline buffer at 0x3a30500 of length 1432 first char b0
pipeline buffer at 0x3a30aa0 of length 1326 first char 50
```

**Comment by lfdoherty** [comment]
I spent some time reading the related code in nan and node.js, but without finding anything useful, so I don't have any other ideas...

**Comment by lovell** [comment]
Well this is a little embarrassing, it turns out sharp was using an erroneous pass-by-value rather than pass-by-ref when building the list of input Buffer objects that need to be persisted.

The rather simple change in commit 6a1c7b7 ensures the call to `SaveToPersistent` is actually made every time.

I'm still trying to work out which change in Node v7.0.0+ exposed/exacerbated this problem, perhaps https://github.com/nodejs/node/commit/5292a1358f834d4788ab10dbe83bf5ea2d35a54d

**Comment by lovell** [comment]
Commit e6bfa52 (a refactor, natch) is where I broke it so v0.16.0-v0.18.3 inclusive are affected :(

**Comment by lfdoherty** [comment]
Yes, that seems to fix it.  

In my experience, some of the hardest bugs to fix are the ones where the bad code doesn't break things nearly as consistently or frequently as you'd think it would.

**Comment by lovell** [comment]
v0.18.4 now available, thank you for reporting this.
