### ISSUE TITLE
npm install sharp encounter exception

### ISSUE THREAD

**Issue by spursy** [lovell/sharp#951]
**My nodejs version is 8.5.0,**

**The followed is my error mes:**

```
4241 error Make sure you have the latest version of node.js and npm installed.
4241 error If you do, this is most likely a problem with the sharp package,
4241 error not with npm itself.
4241 error Tell the author that this fails on your system:
4241 error     node-gyp rebuild
4241 error You can get information on how to open an issue for this project with:
4241 error     npm bugs sharp
4241 error Or if that isn't available, you can get their info via:
4241 error     npm owner ls sharp
4241 error There is likely additional logging output above.
4242 verbose exit [ 1, true ]
```

**Comment by lovell** [comment]
Hello, please provide more of the install log, most likely the bit just above this that should hopefully contain the specific error message.

Please also check you have the necessary [prerequisites](http://sharp.dimens.io/en/stable/install/#prerequisites) installed.

**Comment by actraiser** [comment]
I encountered a similar error when upgrading from sharp 0.18.2 (works fine) to 0.18.3 the other day. What I see in the error below are two suspicious items: 

`/bin/sh: c++filt: not found`
`/bin/sh: readelf: not found`

I am on a node-alpine Docker-Image with Node 8.5.0, yarn 1.0.2 installed. All required libraries (for sharp 0.18.2) get installed during Image built. After going back to sharp 0.18.2, it worked again.

Do you happen to know in which packages **c++filt** and **readelf** are supposed to be included? 

-act

```
**/app $ yarn add sharp@latest**
yarn add v1.0.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "ajv-keywords@1.5.1" has incorrect peer dependency "ajv@>=4.10.0".
[5/5] Building fresh packages...

error /app/node_modules/sharp: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /app/node_modules/sharp
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.5.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/app/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/rocco/.node-gyp/8.5.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/rocco/.node-gyp/8.5.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/rocco/.node-gyp/8.5.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/app/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
/bin/sh: c++filt: not found
/bin/sh: readelf: not found
gyp: Call to 'if readelf -Ws "$(PKG_CONFIG_PATH=":$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --variable libdir vips-cpp)/libvips-cpp.so" | c++filt | grep -qF __cxx11;then echo "1";else echo "0";fi' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.9.41-moby
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/sharp

```

**Comment by ddibiase** [comment]
Having the same issue:

2415 silly install sharp@0.18.3
2416 info lifecycle sharp@0.18.3~install: sharp@0.18.3
2417 verbose lifecycle sharp@0.18.3~install: unsafe-perm in lifecycle true
2418 verbose lifecycle sharp@0.18.3~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/ddibiase-macbook/Projects/dfx-api/node_modules/sharp/node_modules/.bin:/Users/ddibiase-macbook/Projects/dfx-api/node_modules/.bin:/Users/ddibiase-macbook/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin
2419 verbose lifecycle sharp@0.18.3~install: CWD: /Users/ddibiase-macbook/Projects/api/node_modules/sharp
2420 silly lifecycle sharp@0.18.3~install: Args: [ '-c', 'node-gyp rebuild' ]
2421 silly lifecycle sharp@0.18.3~install: Returned: code: 126  signal: null
2422 info lifecycle sharp@0.18.3~install: Failed to exec install script
2423 verbose unlock done using /Users/ddibiase-macbook/.npm/_locks/staging-39439585c2d4d6db.lock for /Users/ddibiase-macbook/Projects/api/node_modules/.staging
2425 verbose stack Error: sharp@0.18.3 install: `node-gyp rebuild`
2425 verbose stack Exit status 126
2425 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
2425 verbose stack     at emitTwo (events.js:125:13)
2425 verbose stack     at EventEmitter.emit (events.js:213:7)
2425 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
2425 verbose stack     at emitTwo (events.js:125:13)
2425 verbose stack     at ChildProcess.emit (events.js:213:7)
2425 verbose stack     at maybeClose (internal/child_process.js:927:16)
2425 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
2426 verbose pkgid sharp@0.18.3
2427 verbose cwd /Users/ddibiase-macbook/Projects/dfx-api
2428 verbose Darwin 16.7.0
2429 verbose argv "/usr/local/Cellar/node/8.1.0_1/bin/node" "/usr/local/bin/npm" "update" "--save"
2430 verbose node v8.5.0
2431 verbose npm  v5.3.0
2432 error code ELIFECYCLE
2433 error errno 126
2434 error sharp@0.18.3 install: `node-gyp rebuild`
2434 error Exit status 126
2435 error Failed at the sharp@0.18.3 install script.
2435 error This is probably not a problem with npm. There is likely additional logging output above.
2436 verbose exit [ 126, true ]

**Comment by ddibiase** [comment]
Additional details, I was using `n` to grab the latest Node 8.5.0. When I reinstalled Node with brew however and tried reinstalling the node-gyp compile worked however I now get this error:
```
Error: Cannot find module '../build/Release/sharp.node'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ddibiase-macbook/Projects/api/dist/node_modules/sharp/lib/constructor.js:9:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ddibiase-macbook/Projects/api/dist/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:
```

**Comment by lovell** [comment]
@ddibiase Your problem, which may not be related to the original comment, looks like something to do with file permissions (`Returned: code: 126`). If possible, try to run `npm install` without using any root permissions/users within a directory that also requires no root permissions.

**Comment by spursy** [comment]
1622 silly generateActionsToTake Finishing
1623 silly diffTrees action count 1
1624 silly diffTrees update sharp@0.18.3
1625 silly decomposeActions action count 9
1626 silly decomposeActions remove sharp@0.18.3
1627 silly decomposeActions fetch sharp@0.18.3
1628 silly decomposeActions extract sharp@0.18.3
1629 silly decomposeActions test sharp@0.18.3
1630 silly decomposeActions preinstall sharp@0.18.3
1631 silly decomposeActions build sharp@0.18.3
1632 silly decomposeActions install sharp@0.18.3
1633 silly decomposeActions postinstall sharp@0.18.3
1634 silly decomposeActions finalize sharp@0.18.3
1635 silly runTopLevelLifecycles Starting
1636 silly executeActions Starting
1637 silly install executeActions
1638 silly doSerial global-install 0
1639 silly doParallel fetch 1
1640 verbose correctMkdir C:\Users\spursy\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
1641 verbose lock using C:\Users\spursy\AppData\Roaming\npm-cache\_locks\staging-77e82d53849738f4.lock for D:\picScrop\myapp\node_modules\.staging
1642 silly doParallel extract 1
1643 silly extract sharp@0.18.3
1644 verbose unbuild node_modules\.staging\sharp-58f61182
1645 silly gentlyRm D:\picScrop\myapp\node_modules\.staging\sharp-58f61182 is being purged from base D:\picScrop\myapp
1646 verbose gentlyRm don't care about contents; nuking D:\picScrop\myapp\node_modules\.staging\sharp-58f61182
1647 verbose tar unpack C:\Users\spursy\AppData\Roaming\npm-cache\sharp\0.18.3\package.tgz
1648 verbose tar unpacking to D:\picScrop\myapp\node_modules\.staging\sharp-58f61182
1649 silly gentlyRm D:\picScrop\myapp\node_modules\.staging\sharp-58f61182 is being purged
1650 verbose gentlyRm don't care about contents; nuking D:\picScrop\myapp\node_modules\.staging\sharp-58f61182
1651 silly gunzTarPerm modes [ '777', '666' ]
1652 silly gunzTarPerm extractEntry package.json
1653 silly gunzTarPerm modified mode [ 'package.json', 436, 438 ]
1654 silly gunzTarPerm extractEntry .npmignore
1655 silly gunzTarPerm modified mode [ '.npmignore', 436, 438 ]
1656 silly gunzTarPerm extractEntry README.md
1657 silly gunzTarPerm modified mode [ 'README.md', 436, 438 ]
1658 silly gunzTarPerm extractEntry LICENSE
1659 silly gunzTarPerm modified mode [ 'LICENSE', 436, 438 ]
1660 silly gunzTarPerm extractEntry binding.js
1661 silly gunzTarPerm modified mode [ 'binding.js', 436, 438 ]
1662 silly gunzTarPerm extractEntry binding.gyp
1663 silly gunzTarPerm modified mode [ 'binding.gyp', 436, 438 ]
1664 silly gunzTarPerm extractEntry docs/api-output.md
1665 silly gunzTarPerm modified mode [ 'docs/api-output.md', 436, 438 ]
1666 silly gunzTarPerm extractEntry docs/api-channel.md
1667 silly gunzTarPerm modified mode [ 'docs/api-channel.md', 436, 438 ]
1668 silly gunzTarPerm extractEntry docs/api-composite.md
1669 silly gunzTarPerm modified mode [ 'docs/api-composite.md', 436, 438 ]
1670 silly gunzTarPerm extractEntry docs/api-constructor.md
1671 silly gunzTarPerm modified mode [ 'docs/api-constructor.md', 436, 438 ]
1672 silly gunzTarPerm extractEntry docs/api-input.md
1673 silly gunzTarPerm modified mode [ 'docs/api-input.md', 436, 438 ]
1674 silly gunzTarPerm extractEntry docs/api-operation.md
1675 silly gunzTarPerm modified mode [ 'docs/api-operation.md', 420, 438 ]
1676 silly gunzTarPerm extractEntry docs/api-colour.md
1677 silly gunzTarPerm modified mode [ 'docs/api-colour.md', 436, 438 ]
1678 silly gunzTarPerm extractEntry docs/api-resize.md
1679 silly gunzTarPerm modified mode [ 'docs/api-resize.md', 436, 438 ]
1680 silly gunzTarPerm extractEntry docs/api-utility.md
1681 silly gunzTarPerm modified mode [ 'docs/api-utility.md', 436, 438 ]
1682 silly gunzTarPerm extractEntry docs/changelog.md
1683 silly gunzTarPerm modified mode [ 'docs/changelog.md', 436, 438 ]
1684 silly gunzTarPerm extractEntry docs/index.md
1685 silly gunzTarPerm modified mode [ 'docs/index.md', 436, 438 ]
1686 silly gunzTarPerm extractEntry docs/install.md
1687 silly gunzTarPerm modified mode [ 'docs/install.md', 420, 438 ]
1688 silly gunzTarPerm extractEntry docs/performance.md
1689 silly gunzTarPerm modified mode [ 'docs/performance.md', 436, 438 ]
1690 silly gunzTarPerm extractEntry lib/channel.js
1691 silly gunzTarPerm modified mode [ 'lib/channel.js', 420, 438 ]
1692 silly gunzTarPerm extractEntry lib/composite.js
1693 silly gunzTarPerm modified mode [ 'lib/composite.js', 436, 438 ]
1694 silly gunzTarPerm extractEntry lib/constructor.js
1695 silly gunzTarPerm modified mode [ 'lib/constructor.js', 436, 438 ]
1696 silly gunzTarPerm extractEntry lib/resize.js
1697 silly gunzTarPerm modified mode [ 'lib/resize.js', 436, 438 ]
1698 silly gunzTarPerm extractEntry lib/output.js
1699 silly gunzTarPerm modified mode [ 'lib/output.js', 436, 438 ]
1700 silly gunzTarPerm extractEntry lib/colour.js
1701 silly gunzTarPerm modified mode [ 'lib/colour.js', 420, 438 ]
1702 silly gunzTarPerm extractEntry lib/input.js
1703 silly gunzTarPerm modified mode [ 'lib/input.js', 420, 438 ]
1704 silly gunzTarPerm extractEntry lib/is.js
1705 silly gunzTarPerm modified mode [ 'lib/is.js', 436, 438 ]
1706 silly gunzTarPerm extractEntry lib/operation.js
1707 silly gunzTarPerm modified mode [ 'lib/operation.js', 420, 438 ]
1708 silly gunzTarPerm extractEntry lib/utility.js
1709 silly gunzTarPerm modified mode [ 'lib/utility.js', 436, 438 ]
1710 silly gunzTarPerm extractEntry lib/index.js
1711 silly gunzTarPerm modified mode [ 'lib/index.js', 420, 438 ]
1712 silly gunzTarPerm extractEntry lib/icc/cmyk.icm
1713 silly gunzTarPerm modified mode [ 'lib/icc/cmyk.icm', 436, 438 ]
1714 silly gunzTarPerm extractEntry lib/icc/sRGB.icc
1715 silly gunzTarPerm modified mode [ 'lib/icc/sRGB.icc', 436, 438 ]
1716 silly gunzTarPerm extractEntry CONTRIBUTING.md
1717 silly gunzTarPerm modified mode [ 'CONTRIBUTING.md', 436, 438 ]
1718 silly gunzTarPerm extractEntry src/operations.h
1719 silly gunzTarPerm modified mode [ 'src/operations.h', 436, 438 ]
1720 silly gunzTarPerm extractEntry src/common.cc
1721 silly gunzTarPerm modified mode [ 'src/common.cc', 436, 438 ]
1722 silly gunzTarPerm extractEntry src/libvips/cplusplus/VError.cpp
1723 silly gunzTarPerm modified mode [ 'src/libvips/cplusplus/VError.cpp', 436, 438 ]
1724 silly gunzTarPerm extractEntry src/libvips/cplusplus/VImage.cpp
1725 silly gunzTarPerm modified mode [ 'src/libvips/cplusplus/VImage.cpp', 436, 438 ]
1726 silly gunzTarPerm extractEntry src/libvips/cplusplus/VInterpolate.cpp
1727 silly gunzTarPerm modified mode [ 'src/libvips/cplusplus/VInterpolate.cpp', 436, 438 ]
1728 silly gunzTarPerm extractEntry src/libvips/cplusplus/vips-operators.cpp
1729 silly gunzTarPerm modified mode [ 'src/libvips/cplusplus/vips-operators.cpp', 436, 438 ]
1730 silly gunzTarPerm extractEntry src/metadata.cc
1731 silly gunzTarPerm modified mode [ 'src/metadata.cc', 420, 438 ]
1732 silly gunzTarPerm extractEntry src/metadata.h
1733 silly gunzTarPerm modified mode [ 'src/metadata.h', 436, 438 ]
1734 silly gunzTarPerm extractEntry src/operations.cc
1735 silly gunzTarPerm modified mode [ 'src/operations.cc', 436, 438 ]
1736 silly gunzTarPerm extractEntry src/common.h
1737 silly gunzTarPerm modified mode [ 'src/common.h', 436, 438 ]
1738 silly gunzTarPerm extractEntry src/pipeline.cc
1739 silly gunzTarPerm modified mode [ 'src/pipeline.cc', 436, 438 ]
1740 silly gunzTarPerm extractEntry src/pipeline.h
1741 silly gunzTarPerm modified mode [ 'src/pipeline.h', 436, 438 ]
1742 silly gunzTarPerm extractEntry src/sharp.cc
1743 silly gunzTarPerm modified mode [ 'src/sharp.cc', 436, 438 ]
1744 silly gunzTarPerm extractEntry src/utilities.cc
1745 silly gunzTarPerm modified mode [ 'src/utilities.cc', 436, 438 ]
1746 silly gunzTarPerm extractEntry src/utilities.h
1747 silly gunzTarPerm modified mode [ 'src/utilities.h', 436, 438 ]
1748 silly gentlyRm D:\picScrop\myapp\node_modules\.staging\sharp-58f61182\node_modules is being purged
1749 verbose gentlyRm don't care about contents; nuking D:\picScrop\myapp\node_modules\.staging\sharp-58f61182\node_modules
1750 silly doParallel preinstall 1
1751 silly preinstall sharp@0.18.3
1752 info lifecycle sharp@0.18.3~preinstall: sharp@0.18.3
1753 silly lifecycle sharp@0.18.3~preinstall: no script for preinstall, continuing
1754 silly doReverseSerial remove 1
1755 silly remove D:\picScrop\myapp\node_modules\sharp
1756 verbose unbuild node_modules\sharp
1757 info lifecycle sharp@0.18.3~preuninstall: sharp@0.18.3
1758 silly lifecycle sharp@0.18.3~preuninstall: no script for preuninstall, continuing
1759 info lifecycle sharp@0.18.3~uninstall: sharp@0.18.3
1760 silly lifecycle sharp@0.18.3~uninstall: no script for uninstall, continuing
1761 verbose unbuild rmStuff sharp@0.18.3 from D:\picScrop\myapp\node_modules
1762 info lifecycle sharp@0.18.3~postuninstall: sharp@0.18.3
1763 silly lifecycle sharp@0.18.3~postuninstall: no script for postuninstall, continuing
1764 silly gentlyRm D:\picScrop\myapp\node_modules\sharp is being purged from base D:\picScrop\myapp
1765 verbose gentlyRm don't care about contents; nuking D:\picScrop\myapp\node_modules\sharp
1766 silly vacuum-fs purging D:\picScrop\myapp\node_modules\sharp
1767 silly vacuum-fs quitting because other entries in D:\picScrop\myapp\node_modules
1768 silly doSerial move 0
1769 silly doSerial finalize 1
1770 silly finalize D:\picScrop\myapp\node_modules\sharp
1771 silly doSerial build 1
1772 silly build sharp@0.18.3
1773 info linkStuff sharp@0.18.3
1774 silly linkStuff sharp@0.18.3 has D:\picScrop\myapp\node_modules as its parent node_modules
1775 verbose linkBins sharp@0.18.3
1776 verbose linkMans sharp@0.18.3
1777 silly doSerial global-link 0
1778 silly doParallel update-linked 0
1779 silly doSerial install 1
1780 silly install sharp@0.18.3
1781 info lifecycle sharp@0.18.3~install: sharp@0.18.3
1782 verbose lifecycle sharp@0.18.3~install: unsafe-perm in lifecycle true
1783 verbose lifecycle sharp@0.18.3~install: PATH: C:\Users\spursy\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\picScrop\myapp\node_modules\sharp\node_modules\.bin;D:\picScrop\myapp\node_modules\.bin;C:\Program Files\ImageMagick-7.0.7-Q16;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\MinGW\bin\;C:\MinGW\mingw32\bin\;D:\Program Files\MongoDB\Server\3.4\bin;D:\Program Files\nodejs\;D:\Program Files\TortoiseSVN\bin;D:\Program Files\TortoiseGit\bin;D:\Program Files\Git\cmd;C:\Program Files\ImageMagick-7.0.7-Q16;D:\Program Files\Python\Scripts\;D:\Program Files\Python\;D:\Program Files (x86)\Microsoft VS Code\bin;C:\MinGW\bin;C:\Users\spursy\AppData\Roaming\npm
1784 verbose lifecycle sharp@0.18.3~install: CWD: D:\picScrop\myapp\node_modules\sharp
1785 silly lifecycle sharp@0.18.3~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
1786 silly lifecycle sharp@0.18.3~install: Returned: code: 1  signal: null
1787 info lifecycle sharp@0.18.3~install: Failed to exec install script
1788 verbose unlock done using C:\Users\spursy\AppData\Roaming\npm-cache\_locks\staging-77e82d53849738f4.lock for D:\picScrop\myapp\node_modules\.staging
1789 silly rollbackFailedOptional Starting
1790 silly gentlyRm D:\picScrop\myapp\node_modules\sharp is being purged from base D:\picScrop\myapp
1791 verbose gentlyRm don't care about contents; nuking D:\picScrop\myapp\node_modules\sharp
1792 silly gentlyRm D:\picScrop\myapp\node_modules\sharp is being purged from base D:\picScrop\myapp
1793 verbose gentlyRm don't care about contents; nuking D:\picScrop\myapp\node_modules\sharp
1794 silly gentlyRm D:\picScrop\myapp\node_modules\sharp is being purged from base D:\picScrop\myapp
1795 verbose gentlyRm don't care about contents; nuking D:\picScrop\myapp\node_modules\sharp
1796 silly gentlyRm D:\picScrop\myapp\node_modules\sharp is being purged from base D:\picScrop\myapp
1797 verbose gentlyRm don't care about contents; nuking D:\picScrop\myapp\node_modules\sharp
1798 silly gentlyRm D:\picScrop\myapp\node_modules\sharp is being purged from base D:\picScrop\myapp
1799 verbose gentlyRm don't care about contents; nuking D:\picScrop\myapp\node_modules\sharp
1800 silly gentlyRm D:\picScrop\myapp\node_modules\sharp is being purged from base D:\picScrop\myapp
1801 verbose gentlyRm don't care about contents; nuking D:\picScrop\myapp\node_modules\sharp
1802 silly gentlyRm D:\picScrop\myapp\node_modules\sharp is being purged from base D:\picScrop\myapp
1803 verbose gentlyRm don't care about contents; nuking D:\picScrop\myapp\node_modules\sharp
1804 silly gentlyRm D:\picScrop\myapp\node_modules\sharp is being purged from base D:\picScrop\myapp
1805 verbose gentlyRm don't care about contents; nuking D:\picScrop\myapp\node_modules\sharp
1806 silly gentlyRm D:\picScrop\myapp\node_modules\sharp is being purged from base D:\picScrop\myapp
1807 verbose gentlyRm don't care about contents; nuking D:\picScrop\myapp\node_modules\sharp
1808 silly vacuum-fs purging D:\picScrop\myapp\node_modules\sharp
1809 silly vacuum-fs purging D:\picScrop\myapp\node_modules\sharp
1810 silly vacuum-fs purging D:\picScrop\myapp\node_modules\sharp
1811 silly vacuum-fs purging D:\picScrop\myapp\node_modules\sharp
1812 silly vacuum-fs purging D:\picScrop\myapp\node_modules\sharp
1813 silly vacuum-fs purging D:\picScrop\myapp\node_modules\sharp
1814 silly vacuum-fs purging D:\picScrop\myapp\node_modules\sharp
1815 silly vacuum-fs purging D:\picScrop\myapp\node_modules\sharp
1816 silly vacuum-fs purging D:\picScrop\myapp\node_modules\sharp
1817 silly vacuum-fs quitting because other entries in D:\picScrop\myapp\node_modules
1818 silly vacuum-fs quitting because other entries in D:\picScrop\myapp\node_modules
1819 silly vacuum-fs quitting because other entries in D:\picScrop\myapp\node_modules
1820 silly vacuum-fs quitting because other entries in D:\picScrop\myapp\node_modules
1821 silly vacuum-fs quitting because other entries in D:\picScrop\myapp\node_modules
1822 silly vacuum-fs quitting because other entries in D:\picScrop\myapp\node_modules
1823 silly vacuum-fs quitting because other entries in D:\picScrop\myapp\node_modules
1824 silly vacuum-fs quitting because other entries in D:\picScrop\myapp\node_modules
1825 silly vacuum-fs quitting because other entries in D:\picScrop\myapp\node_modules
1826 silly rollbackFailedOptional Finishing
1827 silly runTopLevelLifecycles Finishing
1828 silly install printInstalled
1829 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
1830 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
1831 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
1831 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
1831 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
1831 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
1832 verbose stack Error: sharp@0.18.3 install: `node-gyp rebuild`
1832 verbose stack Exit status 1
1832 verbose stack     at EventEmitter.<anonymous> (C:\Users\spursy\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
1832 verbose stack     at emitTwo (events.js:125:13)
1832 verbose stack     at EventEmitter.emit (events.js:213:7)
1832 verbose stack     at ChildProcess.<anonymous> (C:\Users\spursy\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
1832 verbose stack     at emitTwo (events.js:125:13)
1832 verbose stack     at ChildProcess.emit (events.js:213:7)
1832 verbose stack     at maybeClose (internal/child_process.js:927:16)
1832 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
1833 verbose pkgid sharp@0.18.3
1834 verbose cwd D:\picScrop\myapp
1835 verbose Windows_NT 6.1.7601
1836 verbose argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\spursy\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "sharp"
1837 verbose node v8.5.0
1838 verbose npm  v4.5.0
1839 error code ELIFECYCLE
1840 error errno 1
1841 error sharp@0.18.3 install: `node-gyp rebuild`
1841 error Exit status 1
1842 error Failed at the sharp@0.18.3 install script 'node-gyp rebuild'.
1842 error Make sure you have the latest version of node.js and npm installed.
1842 error If you do, this is most likely a problem with the sharp package,
1842 error not with npm itself.
1842 error Tell the author that this fails on your system:
1842 error     node-gyp rebuild
1842 error You can get information on how to open an issue for this project with:
1842 error     npm bugs sharp
1842 error Or if that isn't available, you can get their info via:
1842 error     npm owner ls sharp
1842 error There is likely additional logging output above.
1843 verbose exit [ 1, true ]

**Comment by spursy** [comment]
@lovell @ddibiase    
I have found my reason, It is due to I have not installs **windows-build-tools**.
please refer to [node-gyn installation](https://github.com/nodejs/node-gyp#installation)
