### ISSUE TITLE
Cannot find module 'sharp'

### ISSUE THREAD

**Issue by bassie1995** [lovell/sharp#953]
I've been trying updating to the newest Alpine stuff for Docker, but am not getting sharp to work as Node keeps telling me it can't find the module.

My Dockerfile is currently this (relevant parts):
```
WORKDIR /app
COPY package.json ./

RUN apk add alpine-sdk python2 g++ make binutils vips-tools vips-dev fftw-dev --update-cache --repository https://dl-3.alpinelinux.org/alpine/edge/testing/

RUN rm -rf /app/node_modules

RUN npm i
RUN npm i pm2 -g

CMD node app.js
```

I left prints out, but `ls node_modules` and `npm list --depth=0` both show sharp installed.

When running the container, this shows up:
```
web_1    | module.js:529
web_1    |     throw err;
web_1    |     ^
web_1    |
web_1    | Error: Cannot find module 'sharp'
web_1    |     at Function.Module._resolveFilename (module.js:527:15)
web_1    |     at Function.Module._load (module.js:476:23)
web_1    |     at Module.require (module.js:568:17)
web_1    |     at require (internal/module.js:11:18)
web_1    |     at Object.<anonymous> (/app/controllers/house.js:3:15)
web_1    |     at Module._compile (module.js:624:30)
web_1    |     at Object.Module._extensions..js (module.js:635:10)
web_1    |     at Module.load (module.js:545:32)
web_1    |     at tryModuleLoad (module.js:508:12)
web_1    |     at Function.Module._load (module.js:500:3)
web_1    |     at Module.require (module.js:568:17)
web_1    |     at require (internal/module.js:11:18)
web_1    |     at Object.<anonymous> (/app/app.js:53:25)
web_1    |     at Module._compile (module.js:624:30)
web_1    |     at Object.Module._extensions..js (module.js:635:10)
web_1    |     at Module.load (module.js:545:32)
web_1    |     at tryModuleLoad (module.js:508:12)
web_1    |     at Function.Module._load (module.js:500:3)
web_1    |     at Function.Module.runMain (module.js:665:10)
web_1    |     at startup (bootstrap_node.js:201:16)
web_1    |     at bootstrap_node.js:626:3
huisordner_web_1 exited with code 1
```

I cannot get this to work, and assume sharp isn't really installing correctly (but no errors during `npm install`!), any suggestions?

 Thanks!

**Comment by lovell** [comment]
Hello, `web_1` suggests you're using Docker Compose. Perhaps check the volume config is correct for the "web" service and not trampling what's in your image.

**Comment by bassie1995** [comment]
Hi, I'm using the same config as on the production server (this guy: https://github.com/lovell/sharp/issues/773), but you make a good point.

My `docker-compose.yml` is as follows:
```
version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      NODE_ENV: production
[...]
```

It seems this should not generate any issues, but I do remember it having issues not seeing `package.json`, after which I manually set it to the `WORKDIR /app` and did `COPY package.json ./`.

If I remove that, I again get the same issue: `npm WARN saveError ENOENT: no such file or directory, open '/package.json'`.

Seems it is working correctly, though, when I do include them.

**Comment by bassie1995** [comment]
Well, it seems having `WORKDIR /app` did cause me issues, I assume somehow with Docker compose (although I couldn't even guess as to how). Uhhh thanks for the help once again!
