### ISSUE TITLE
Feature Request: Convert color space

### ISSUE THREAD

**Issue by neophob** [lovell/sharp#957]
Hi

thanks for sharp, wonderful lib! I need it to resize images. 

What I'm looking is a way to convert the colorspace, for example I want to convert it from ARGB(8888) to RGB(565). I can do this in JS, but I doubt it's high performance.

Any chance we can implement a conversion function in sharp?

**Comment by lovell** [comment]
Hello, I think #218 covers this.

**Comment by edzis** [comment]
@lovell I am also having ARGB inputs and I fail to convert them with sharp. Did you mean that #218 has the recipe to do that or that this will be supported once the ideas discussed in #218  will be implemented?

**Comment by lovell** [comment]
@edzis Raw, uncompressed ARGB input will need to be byte-swapped before passing to sharp as it expects 4 channel RGBA (or 2 for greyscale+A) raw input to have the alpha channel at the end.
