### ISSUE TITLE
File is correct but meta data are showing wrong, am I doing something wrong

### ISSUE THREAD

**Issue by bikashD** [lovell/sharp#958]
```
eachOfSeries(imgArr, (element, index, callback) => {
    element.toFile('c' + index + '.jpg');
    element.metadata((e, m) => {
        console.log(e, m);
    });
}, () => {

});
```

**Comment by lovell** [comment]
Hello, it's not clear from this example what `element` is. My best guess would be that it is a sharp instance with a chained `resize` operation. If so, and you're after post-processing metadata, use something like:

```javascript
element
  .toFile('c' + index + '.jpg')
  .then(console.log);
```

**Comment by bikashD** [comment]
https://github.com/lovell/sharp/issues/870
It is solved by above answer. thanks for quick reply. Yes element is sharp instance
