### ISSUE TITLE
Having 403 error while npm install

### ISSUE THREAD

**Issue by rssilva** [lovell/sharp#968]
While running `npm install` I got a `403` on https://dl.bintray.com/lovell/sharp/libvips-8.4.2-darwin-x64.tar.gz

**Comment by erkstruwe** [comment]
Wow, this will be bad for a number of people...

**Comment by rssilva** [comment]
oh, sorry, this is duplicate from https://github.com/lovell/sharp/issues/841

**Comment by JordanFriendshuh** [comment]
It's not really a duplicate, the examples in that issue were 404s and 500s from bintray.  This is a 403 which might mean the file got moved/deleted/etc...

**Comment by lovell** [comment]
Please see #964
