### ISSUE TITLE
docs: withoutEnlargement is false by default

### ISSUE THREAD

**Issue by mahnunchik** [lovell/sharp#972]
`withoutEnlargement` is `false` by default but documentation says it should be `true`: http://sharp.dimens.io/en/stable/api-resize/#withoutenlargement

**Comment by lovell** [comment]
Hello, this is a little confusing as, when the function is called without a parameter, the "default" is `true`. This is not quite the same thing as the default being `true` when the function has not been called, but this is ambiguous and we should fix the docs.

The same is true of [sequentialRead](http://sharp.dimens.io/en/stable/api-input/#sequentialread) (and possibly others I can't think of right now).

It's probably worth adding some text to the jsdoc to make it explicit that the default behaviour is `false` in both cases. PR welcome!

**Comment by mahnunchik** [comment]
Hi @lovell 
Thank you for the clarification. I think it is good idea to add some text to the documentation.

**Comment by aureliusm** [comment]
Hi, I fixed that value 😄  https://github.com/lovell/sharp/pull/974

**Comment by valkyrie-101** [comment]
Hi, I changed the jsdoc. Documentation should be clear enough now.

**Comment by lovell** [comment]
The docs website will be updated with the improvement in aad16ac from the next release, thanks all.
