### ISSUE TITLE
SVG to JPG not working with image files

### ISSUE THREAD

**Issue by hbar-digital** [lovell/sharp#973]
I'm trying to rasterize an SVG image which contains an image tag pointing to a local file. However, the image is not rendered. I've tried the same svg directly with rsvg-convert and it works. I've tried relative and absolute paths with the image in the project root or descendant folder. Sharp does work if the image tag contains a data uri.

Any help would be appreciated!

**Comment by lovell** [comment]
Hello, is this with file-based input or Buffer/Stream based input? If the latter please try the former as librsvg places security limits on the location of included files.

It's also worth trying with absolute filesystem paths or ensuring paths are relative to the process' working directory (which may not be the same as the directory your script is in).

**Comment by lovell** [comment]
@hbar-digital Were you able to make any progress with this?

**Comment by hbar-digital** [comment]
@lovell You are correct in that it's a librsvg limitation as I was using a stream based input. The workaround was to convert the image to base64.

**Comment by lovell** [comment]
Thanks for confirming. I'll close as this is a security feature of librsvg with a workaround for trusted input.
