### ISSUE TITLE
Performance issues during building (compiling) in low memory environments

### ISSUE THREAD

**Issue by nanom1t** [lovell/sharp#978]
Hi,

I'm using Sharp in my Node.js application and it works good. However, I've faced with performance issues during building (compiling). I have a Linode VPS (1 Gb RAM, 1 CPU Core). 

The package manager (yarn or npm) starts to build sharp dependency (I guess from sources with node-gyp). It eats a lot of RAM / CPU and causes VPS reboot.
```
$ yarn install
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
**[1/3] ⡀ sharp: CXX(target) Release/obj.target/sharp/src/common.o**
[-/3] ⡀ waiting...
[3/3] ⢀ node-sass: Downloading binary from https://github.com/sass/node
[-/3] ⢀ waiting...
**Write failed: Broken pipe**
```
Here is some monitoring graphics with RAM and CPU utilization (they are not clear, because of reboots during building):
![screen shot 2017-10-06 at 4 30 11 pm](https://user-images.githubusercontent.com/6481192/31280802-3a94b978-aab6-11e7-9dae-108b74595d32.png)
![screen shot 2017-10-06 at 4 30 24 pm](https://user-images.githubusercontent.com/6481192/31280803-3a99afc8-aab6-11e7-89a9-8370fc31242e.png)
You can see that the building process utilizes almost 100% of CPU and RAM. Then my server goes to reboot. This problem happens especially during Sharp building process.

I realize that I have a small VPS with not enough size of RAM and CPU, but it is not the best idea for me to buy a larger VPS only because of building one Node.js dependency. This issue happens only during deploy process (when I install app dependencies).

Is it possible to optimize performance of Sharp building process?

Thanks

**Comment by lovell** [comment]
In a RAM-constrained environment you can reduce the memory required by the `g++` compiler by reducing the level of optimisation from [-O3](https://github.com/lovell/sharp/blob/eb8773fe3e4fba331564053ff9a8df81bc1f79ed/binding.gyp#L195) to `-Os` by using something like:

```sh
CXXFLAGS="-Os" npm install sharp
```

If you haven't already seen it, please subscribe to #186 for updates about removing the compilation step for as many people as possible.

**Comment by lovell** [comment]
Hope this helped.
