### ISSUE TITLE
Electron: SVG from buffer gives error unsupported image object

### ISSUE THREAD

**Issue by jpittner** [lovell/sharp#979]
sharp.format.svg.input[buffer/file/stream] = all true, using sharp 0.18.4 on osx 10.11.6, electron 1.7.5.

Taking the example from the main page:
```
const roundedCorners = new Buffer(
  '<svg><rect x="0" y="0" width="200" height="200" rx="50" ry="50"/></svg>'
);

const roundedCornerResizer =
  sharp()
    .resize(200, 200)
    .overlayWith(roundedCorners, { cutout: true })
    .png();
```

This returns error unsupported input object. 

I'm trying something similar in my code - take a jpeg and overlay it with an svg from buffer, but I keep running into this error. Any tips to track down what's going on here?

**Comment by lovell** [comment]
Hello, that example also includes the following, which is probably where the error originates:
```javascript
readableStream
  .pipe(roundedCornerResizer)
  .pipe(writableStream);
```
What is the equivalent of `readableStream` in your code?

**Comment by jpittner** [comment]
Hi, I used toFile(filename) to pipe it to a file, but even with out that, it gives me the same error.

**Comment by lovell** [comment]
Please can you show the code you're using to input data? (`toFile` relates to output.)

**Comment by jpittner** [comment]
```
var src = fs.createReadStream(filename);
var tgt = fs.createWriteStream(target);

src.pipe(roundedCornerResizer).pipe(tgt);
```

However the error is thrown before any of this happens, when I'm creating the resizer itself.

**Comment by lovell** [comment]
Does using only the following also throw (at [input.js#L26](https://github.com/lovell/sharp/blob/master/lib/input.js#L26))?
```javascript
sharp().overlayWith(new Buffer('<svg/>'));
```
If so, perhaps the [is.buffer](https://github.com/lovell/sharp/blob/master/lib/is.js#L48) check is failing on Electron. Is a `Buffer` in Electron the same as a `Buffer` in Node?

**Comment by jpittner** [comment]
It does fail, yes. This isn't something I would have thought of, after all Electron is essentially Node with some fancy clothes on. The Electron API doesn't mention any changes to the Buffer class.

**Comment by lovell** [comment]
Are there any other dependencies? If so, could they or their dependencies be monkey-patching `Buffer`?

**Comment by lovell** [comment]
@jpittner Were you able to make any progress with this?

**Comment by lovell** [comment]
Closing as there has been no update and no further reports. Please re-open with the requested details if this is still occurring.

**Comment by vitaliy-kravchenko-dev** [comment]
@jpittner, I have had the same problem in Electron.
Next solution works for me:

```typescript
// electron.service.ts
import {Injectable} from '@angular/core';
// ....
import * as buffer from 'buffer';

@Injectable()
export class ElectronService {
   // ....
  buffer: typeof buffer;

  constructor() {
    // Conditional imports
    if (this.isElectron()) {
      // .....
      this.buffer= window.require('buffer');
      // ....
      const roundedCorners = new this.buffer.Buffer(
         '<svg><rect x="0" y="0" width="200" height="200" rx="50" ry="50"/></svg>'
       );
       // ....
    }
  }

  isElectron() {
    return window && window.process && window.process.type;
  }
}
```
Dependencies:
* Angular _5.2.9_
* Sharp _0.20.2_
* Electron _1.8.4_

**Comment by vitkrv** [comment]
@jpittner, I have had the same problem in Electron.
Next solution works for me:

```typescript
// electron.service.ts
import {Injectable} from '@angular/core';
// ....
import * as buffer from 'buffer';

@Injectable()
export class ElectronService {
   // ....
  buffer: typeof buffer;

  constructor() {
    // Conditional imports
    if (this.isElectron()) {
      // .....
      this.buffer = window.require('buffer');
      // ....
      const roundedCorners = new this.buffer.Buffer(
         '<svg><rect x="0" y="0" width="200" height="200" rx="50" ry="50"/></svg>'
       );
       // ....
    }
  }

  isElectron() {
    return window && window.process && window.process.type;
  }
}
```
Dependencies:
* Angular _5.2.9_
* Sharp _0.20.2_
* Electron _1.8.4_
