### ISSUE TITLE
Dissolve image into another

### ISSUE THREAD

**Issue by stefanobaldo** [lovell/sharp#981]
It would be possible dissolve a transparent image into an image? The best I could get overlaying a raw pixel buffer containing tiled semi-transparent pixel value was this:

![opacity](https://user-images.githubusercontent.com/1918151/31345267-952d8400-aceb-11e7-9d47-9b436d063996.png)

Actually what I need is this:

![opacity-ok](https://user-images.githubusercontent.com/1918151/31345320-c8af32e2-aceb-11e7-908e-dceae379c0e3.png)

Is there any way to achieve this? I used to do this using GM `-dissolve` option, but I am upgrading my API to use sharp and this the only feature I could not get done.

**Comment by lovell** [comment]
Please see #618 (and please don't ghost-post and cross-post).
