### ISSUE TITLE
Format for manipulating pixels directly from JS?

### ISSUE THREAD

**Issue by jtlapp** [lovell/sharp#983]
I'm developing a library for processing GIF animations in Javascript. The library currently wraps Jimp but I'm wondering if I might write an adapter for sharp as well.

I've abstracted the GIF encoder and decoder, so that they provide image frames in a format that is consistent across the GIF library, independent of encoder/decoder. I'm currently using the Jimp data format, which is an array of numbers at four numbers per pixel -- RGBA.

Does sharp have a similar pixel format that allows my library to manipulate pixels directly? What is that format? How do I get it? I had trouble finding it looking through the code and docs.

For example, my decoder would pull a GIF into JS as a series of images. Right now I store those images in Jimp form, allowing Jimp to manipulate them and write them back out (as everything but GIF animations). I'd like to be able to load images in a form that sharp can work with as well. After manipulating the GIF image frames in JS (yeah, slow) or sharp, an encoder supporting multi-frame GIFs will write the animation back out.

**Comment by lovell** [comment]
Hello, sharp can deal with Buffers containing raw, uncompressed RGBA data as both [input](http://sharp.dimens.io/en/stable/api-constructor/#sharp) and [output](http://sharp.dimens.io/en/stable/api-output/#raw), e.g. (untested):

```javascript
const { data, width, height } = jimpImage.bitmap;

sharp(data, { raw: { width, height, channels: 4 }})
  .resize(width / 2)
  .raw()
  .toBuffer((err, rgbaBuffer, info) => { ... });
```

**Comment by jtlapp** [comment]
Excellent! Thank you! I assume that I can also convert back after manipulating it in sharp?

**Comment by lovell** [comment]
Yes, hence the use of the `raw` output selector in that example.

**Comment by jtlapp** [comment]
Oh I gotcha! You took it to sharp and back. Perfect. Thank you!
