### ISSUE TITLE
Sharp for AWS Lambda in Visual Studio for Windows

### ISSUE THREAD

**Issue by tbruestle** [lovell/sharp#984]
I'm trying to implement Sharp in my AWS Lambda expressions in Visual Studio. The npm import downloads Windows based libraries that are incompatible with AWS Lambda expressions. This results in a "invalid ELF header" error. I see it suggested that people build Sharp themselves in EC2 then port it to Visual Studio. Is there a precompiled library so this step can be skipped? Does it somehow need to be built on an EC2 instance associated with the account? Also, how do we add this library into into Visual Studio? Any help would be appreciated.

**Comment by lovell** [comment]
When packaging native modules for AWS Lambda, you'll need to use the same OS and Node version at `npm install` time as at runtime. This is not specific to sharp.

In the case of Windows, this means the `node_modules` for local development will be different to the `node_modules` in the bundled .zip you provide to run on AWS Lambda.

Your options are either as documented in http://sharp.dimens.io/en/stable/install/#aws-lambda or perhaps experiment creating the bundled .zip inside a Docker-managed container such as https://hub.docker.com/r/lambci/lambda/ (you'll need the `:build` tag).

**Comment by lovell** [comment]
@tbruestle Were you able to make any progress with this?

**Comment by lovell** [comment]
Closing as inactive, please re-open with more details if required.
