### ISSUE TITLE
Question about overlayWith and color profiles

### ISSUE THREAD

**Issue by rui-cruz** [lovell/sharp#993]
Hi,

I've been reading issues and how-to create compositions with sharp, and a question pops out on my head.. 
How sharp handles different colorprofiles when overlaying?
Should I have a promise of each file buffer with toColorspace('srgb') and then reduce/forkJoin all? or is automatic?

Thank you!

**Comment by lovell** [comment]
The summary is: it will try to convert to sRGB for you.

Most use cases will involve using an image with an alpha channel as the overlay, typically PNG or (automagically-rasterised) SVG, which will "just work".

I've not tried but I suspect attempting to use a profile-less CMYK JPEG as the overlay may fail at the moment, but that will be a rare scenario as JPEG has no alpha channel.

**Comment by lovell** [comment]
@rui-cruz Did this answer your question?

**Comment by rui-cruz** [comment]
My goal is to create a "collage" of images on a blank image. This collage can be huge.. but my concern was about color-profiles. At this time I had not tested yet, You can close for now, and later I'll give you feedback.

Thank you @lovell
