### ISSUE TITLE
Silent crash when calling sharp without arguments

### ISSUE THREAD

**Issue by whmountains** [lovell/sharp#994]
Minimal test case:

```js
const sharp = require('sharp')
const main = async () => {
  const image = sharp()
  const info = await image.metadata()
  console.log('done')
}

main()
```

The process simply exits with status 0.  There is no error message, and 'done' is never logged to the console.

**Comment by lovell** [comment]
Hello, the parameter-less constructor is for Stream-based input.

> "JPEG, PNG, WebP, GIF, SVG, TIFF or raw pixel image data can be streamed into the object when not present." http://sharp.dimens.io/en/stable/api-constructor/#sharp

In your example, this might look like the following:
```diff
  const image = sharp()
+ readableSteam.pipe(image)
  const info = await image.metadata()
```

**Comment by whmountains** [comment]
Thank you, I missed that.
