### ISSUE TITLE
Ensure clone is only used with Stream-based input

### ISSUE THREAD

**Issue by whmountains** [lovell/sharp#995]
## Steps to Reproduce

```js
const sharp = require('sharp')

const main = async () => {
  const image = sharp('test.jpg')

  for (let i = 0; i < 25; i++) {
    await image
      .clone()
      .resize(800)
      .toFormat('jpeg')
      .toBuffer()
  }
}

main()
```

## Error Message

```
(node:93880) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit
```

It always shows up after processing the ninth image.

**Comment by whmountains** [comment]
I can also reproduce this using old-fashioned callbacks:

```js
const image = require('sharp')('test.jpg')

const runTask = () => {
  image
    .clone()
    .resize(800)
    .toFormat('jpeg')
    .toBuffer((err, buff) => {
      console.log('done', counter++)
      if (counter < 25) {
        setImmediate(runTask)
      }
    })
}

runTask()
```

**Comment by lovell** [comment]
Hello, the use of [clone](http://sharp.dimens.io/en/stable/api-input/#clone) is unnecessary here as Stream-based input is not being used.

The reason you see a warning is because Node has [an internal default of 10](https://nodejs.org/docs/latest/api/events.html#events_emitter_setmaxlisteners_n) and this code is creating 25 instances.

**Comment by whmountains** [comment]
Thank you for the response.  Knowing what function is causing the problem helps a lot!

If `clone()` can only be used for streaming inputs, what am I supposed to do when I need to create two independent outputs from the same input?

```js
const image = require('sharp')('test.jpg')

// create a jpeg version that's 800px wide
image.resize(800).jpeg().toBuffer()

// create a webp version without changing the resolution
// This doesn't work because the previous output already set the width to 800px
image.webp().toBuffer()
```
Of course I could just output the webp image first, but that's missing the point.  In a large complex app I need a way to pass a "clean" source object to many different functions without worrying about how they interact.

Thanks!

**Comment by whmountains** [comment]
Could you just add a check to the clone function that doesn't register the listener if streaming mode is disabled?

input.js:149

```js
if (this._isStreamInput()) {
    // Pass 'finish' event to clone for Stream-based input
    this.on('finish', function () {
      // Clone inherits input data
      that._flattenBufferIn();
      clone.options.bufferIn = that.options.bufferIn;
      clone.emit('finish');
    });
  }```

**Comment by lovell** [comment]
> pass a "clean" source object to many different functions

The input is not mutated so you can do the following:

```javascript
const sharp = require('sharp');

// create a jpeg version that's 800px wide
sharp('test.jpg').resize(800).jpeg().toBuffer()

// create a webp version without changing the resolution
sharp('test.jpg').webp().toBuffer()
```

If you would prefer to pass a sharp instance then perhaps try:

```javascript
const sharp = require('sharp');

const image = () => sharp('test.jpg');

// create a jpeg version that's 800px wide
image().resize(800).jpeg().toBuffer()

// create a webp version without changing the resolution
image().webp().toBuffer()
```

Both of these approaches have the benefit of input caching within libvips.

**Comment by whmountains** [comment]
Thank you.  That is a reasonable workaround.

Are you opposed to also patching `clone()` to allow it to be used for this?

**Comment by lovell** [comment]
Perhaps `clone()` should throw an Error when `_isStreamInput()` is false?

**Comment by whmountains** [comment]
That sounds reasonable to me.

**Comment by lovell** [comment]
PR welcome for this - please target at the `suit` branch as this would be a breaking API change.

**Comment by Razinsky** [comment]
I'm using a stream-based input and `.clone()` and have 16 instances. I get the same EventEmitter warning. Is there a way to silence this warning anyway?

Thanks!

**Comment by lovell** [comment]
@Razinsky see https://nodejs.org/docs/latest/api/events.html#events_emitter_setmaxlisteners_n

```javascript
sharp()
  .setMaxListeners(0)
  .clone()
  ...
```

**Comment by Razinsky** [comment]
Oh ... yeah well I didn't saw that method was exposed :) So easy.

Thanks for the quick answer!

**Comment by lovell** [comment]
Commit 9fa04a0 adds a check before attaching the event listener. This will be in v0.19.0. Thanks for reporting this.

**Comment by lovell** [comment]
sharp v0.19.0 now available.
