### ISSUE TITLE
Cannot use WebP images <100 bytes as input

### ISSUE THREAD

**Issue by whmountains** [lovell/sharp#996]
This only happens with some images.  I've attached the an example input and output to help reproduce this:

```js
const sharp = require('sharp')

const main = async () => {
  const image = sharp(path.join(__dirname, '../src/input.jpg'))
  const imageBuffer = await image
    .resize(10)
    .webp()
    .toBuffer()

  const resultInfo = await sharp(imageBuffer).metadata()
  console.log(resultInfo)
}

main()
```

The error I get on line 10 is:

```
Error: Input buffer contains unsupported image format
```

I can also save the image to disk using `.toFile('10px-output.webp')`, but sharp still can't read it.  Chrome reads it just fine, however.

Here is a zip file containing the input file I used and the output I got:
[images.zip](https://github.com/lovell/sharp/files/1392358/Archive.zip)

**Comment by lovell** [comment]
Hello, this 92 byte WebP input image is tripping the 100 byte minimum check within libvips.

https://github.com/jcupitt/libvips/blob/master/libvips/foreign/webp2vips.c#L70

I've managed to create a valid 44 byte WebP image that also fails.

@jcupitt What would your recommendation be here?

**Comment by whmountains** [comment]
Nice debugging @lovell!

**Comment by jcupitt** [comment]
Oh dear, I wish WebP was clearer on issues like this.

Googling around, it seems that WebP has "RIFF xxxx WEBP" in the first 12 bytes, I'll change libvips to look for that.

**Comment by jcupitt** [comment]
OK, git master now sniffs the webp file type by looking for a magic number rather than trying to decode the header. This will be in 8.6, due RSN.

Thanks!

**Comment by jcupitt** [comment]
... I tested it with all the webp images I have, and tried making a webp just slightly larger than the magic number, and it all seems to work.

**Comment by lovell** [comment]
@jcupitt Brilliant, thanks John, and thank you @whmountains for reporting.

**Comment by lovell** [comment]
sharp v0.19.0 with libvips v8.6.1 as a dependency is now available.
