### ISSUE TITLE
Expose vips_rotate/vips_affine for arbitrary tilt (and/or skew and scale)

### ISSUE THREAD

**Issue by yuanzhanghu** [lovell/sharp#998]
Hi There, 
Sharp is very very good,  chainable api,  ease to use.   Really appreciated for the this great project. 
While is it possible to support rotate angles other than 90/180/270/360 ?  Cuz i tested that node-easyimage has supported this feature already. 

Thanks!

**Comment by lovell** [comment]
Hello, there has been a previous PR #906 related to this, but it was closed.

Let's use this issue to track your request to expose the [vips_affine](http://jcupitt.github.io/libvips/API/current/libvips-resample.html#vips-affine) operation, which provides arbitrary tilt, skew and scale features. A possible API to expose is mentioned in https://github.com/lovell/sharp/pull/906#issuecomment-321075215

**Comment by lovell** [comment]
The forthcoming libvips v8.7.0 provides a new `vips_rotate` operation.

Perhaps rather than expose the full affine transformation logic, we could provide what most people seem to need via the existing `rotate()` operation and it extend it to also accept an angle where `angle % 90 != 0`.

This would also mean extending the signature to accept an object to pass in an optional `background` parameter.

```javascript
rotate() // existing signature, auto-rotate based on EXIF
rotate(angle) // existing signature, default to a black background
rotate({ angle, background })
```

As always, happy to help with and accept a PR for this.

**Comment by badtrip987** [comment]
Any news on this?

**Comment by Pizzacus** [comment]
Any news on this? <sup><sup>Again</sup></sup>

**Comment by lovell** [comment]
`vips_rotate` will be added in the forthcoming libvips v8.7.0.

**Comment by kimmobrunfeldt** [comment]
I would need the raw vips_affeine functionality in my use case. We're implementing our own internal placeit.net type of service.

**Comment by freezy** [comment]
libvips v8.7.0 final released! Anything else holding this back? :)

**Comment by lovell** [comment]
@freezy The forthcoming sharp v0.21.0 will require/depend upon libvips v8.7.0. As I said in https://github.com/lovell/sharp/issues/998#issuecomment-376699203, "happy to help with and accept a PR for this."

**Comment by freezy** [comment]
I might have a look. However I'm not familiar with the vips API and their documentation seems currently unavailable.

**Comment by Pizzacus** [comment]
it seems like https://jcupitt.github.io/libvips/ is broken, but https://libvips.github.io/libvips/ works fine, try that one!

**Comment by lovell** [comment]
libvips moved to a new GitHub org today - we're slowly fixing all the links.

**Comment by freezy** [comment]
Yup, noticed. :)

**Comment by freezy** [comment]
About the API: @lovell proposed an overload of `rotate()` taking in an object with properties `angle`  and `background`.

Wouldn't it be simpler to leave it as-is, just add an additional background parameter and `vips_rotate` when the angle is different than `0`, `90`, `180` and `270`? For example:

```javascript
rotate() // existing signature, auto-rotate based on EXIF
rotate(90) // existing signature, uses vips_rot
rotate(45) // new signature, uses vips_rotate
```

**Comment by lovell** [comment]
@freezy Thanks for tackling this. Given that `background` is optional it should probably be a named parameter.

How about the following:
```javascript
rotate() // existing signature, auto-rotate based on EXIF
rotate(90) // existing signature, uses vips_rot
rotate(45) // existing signature, uses vips_rotate
rotate(45, { background: '#ff00ff' }) // new signature, uses vips_rotate
```

**Comment by freezy** [comment]
Works for me!

**Comment by freezy** [comment]
So with just handing the angle to `vips_rotate` it won't change the image's dimensions, i.e. the edges of the image are cut off. Is this intended behavior, or should I look into resizing the image as well?

**Comment by lovell** [comment]
@freezy Is there logic to ensure the channel counts match, e.g. https://github.com/lovell/sharp/blob/master/src/pipeline.cc#L442-L452 ? The error mentions libvips' `linear` operation - is there also something other than rotation involved in your scenario?

**Comment by freezy** [comment]
@lovell Yes, actually, I've put that code that is already used twice in the lib into [a function](https://github.com/freezy/sharp/blob/rotate/src/common.cc#L608-L639) (though I haven't replaced the original calls yet). I don't do anything else than [rotating](https://github.com/freezy/sharp/blob/rotate/src/pipeline.cc#L507-L512).

**Comment by freezy** [comment]
My alpha function was buggy. I've created #1383 with the correct one. With that, rotation works with transparent background as well. Will clean up stuff, add doc and tests, then you'll get a PR.

**Comment by freezy** [comment]
Got a PR ready and will submit as soon as #1383 is closed!
