### ISSUE TITLE
How to trim with images that have similar colours

### ISSUE THREAD

**Issue by hybmg57** [lovell/sharp#999]
I have an image that has similar colours like below

Original:
![12](https://user-images.githubusercontent.com/1248928/31799560-81c6e476-b586-11e7-8aee-01c55be927be.png)

Trimmed:
![12_585x754](https://user-images.githubusercontent.com/1248928/31799559-818df5c6-b586-11e7-9572-efed099e8528.png)

So the image has similar colours to the background and I need a way to trim without cutting the image. Is this possible?

**Comment by lovell** [comment]
Have you tried altering the `tolerance` parameter of the [trim](http://sharp.dimens.io/en/stable/api-operation/#trim) operation?

**Comment by hybmg57** [comment]
Yes I did try with many from 90 down to 1 but it didn't help

**Comment by lovell** [comment]
OK, thanks for confirming. Your best bet is to wait as sharp will be switching to libvips' internal trim operation in the next release - please subscribe to #914 for updates.

**Comment by hybmg57** [comment]
Is there a way to prevent from trimming to ensure these type of images are detected and not cut off?

**Comment by lovell** [comment]
For now you'll need to write your own logic that scans pixel values to determine the best values to pass to a subsequent [extract](http://sharp.dimens.io/en/stable/api-operation/#extract) operation. Use [raw](http://sharp.dimens.io/en/stable/api-output/#raw) to access uncompressed pixel data.

**Comment by hybmg57** [comment]
@lovell how would you do this? Currently I have something like:

```
return sharp_obj
    .metadata()
    .then(function(original_metadata) {
      return sharp_obj
        .raw()
        .toBuffer()
        .then(output_buffer => {
          const coords = { x: 0, y: 0 }
          const offset = 3 * (1 * coords.x + coords.y) // channels * (width * y + x);
          const red = output_buffer[offset]
          const green = output_buffer[offset + 1]
          const blue = output_buffer[offset + 2]
          background.r = red
          background.g = green
          background.b = blue
```

Would I have to scan through looping offset coords with x and y? I wanted to ensure top bit of the image is not cut off

Thanks!

**Comment by lovell** [comment]
libvips' implementation is at https://github.com/jcupitt/libvips/blob/master/libvips/arithmetic/find_trim.c but otherwise StackOverflow is your friend here.
